# -*- coding: utf-8 -*-
#
# MOOSE documentation build configuration file, created by
# sphinx-quickstart on Tue Jul  1 19:05:47 2014.
# updated on Thr Jan 21 00:30:10 2016
# This file is execfile()d with the current directory set to its containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

#Workaround to fix bug where extensions werent added
from docutils.parsers.rst.directives.admonitions import BaseAdmonition
#from sphinx.util import compat
#compat.make_admonition = BaseAdmonition

import subprocess
import os
import sys
import mock

conf_dir_ = os.path.abspath(os.path.dirname( __file__ ))

# Always load local Sphinx extensions
sys.path.insert(0, os.path.join(conf_dir_, 'Extensions'))

# Resolve moose-core path:
# 1. use MOOSE_CORE_PATH if set
# 2. otherwise docs/moose-core (submodule location in this repo)
# 3. fallback: repo root / moose-core
_repo_root = os.path.abspath(os.path.join(conf_dir_, '..', '..'))
_docs_dir = os.path.abspath(os.path.join(conf_dir_, '..'))
_moose_core = (os.environ.get('MOOSE_CORE_PATH')
               or (os.path.join(_docs_dir, 'moose-core') if os.path.isdir(os.path.join(_docs_dir, 'moose-core')) else None)
               or os.path.join(_repo_root, 'moose-core'))

_moose_examples = os.environ.get('MOOSE_EXAMPLES_PATH') or os.path.join(_docs_dir, 'moose-examples')

if os.path.isdir(_moose_core):
    sys.path.insert(0, os.path.join(_moose_core, 'python'))
else:
    print("[conf.py] moose-core not found. Set MOOSE_CORE_PATH or init the submodule.")

if os.path.isdir(_moose_examples):
    sys.path.append(os.path.join(_moose_examples, 'snippets'))
    sys.path.append(os.path.join(_moose_examples, 'tutorials/ChemicalOscillators'))
    sys.path.append(os.path.join(_moose_examples, 'tutorials/ChemicalBistables'))
    sys.path.append(os.path.join(_moose_examples, 'tutorials/ExcInhNet'))
    sys.path.append(os.path.join(_moose_examples, 'neuroml/lobster_pyloric'))
    sys.path.append(os.path.join(_moose_examples, 'tutorials/ExcInhNetCaPlasticity'))
    sys.path.append(os.path.join(_moose_examples, 'squid'))
else:
    print("[conf.py] moose-examples not found. Set MOOSE_EXAMPLES_PATH or init the submodule.")


def _parse_moose_version():
    """Read version and release codename from moose-core CHANGELOG.md."""
    import re
    if not _moose_core:
        return None, None
    changelog = os.path.join(_moose_core, 'CHANGELOG.md')
    if not os.path.exists(changelog):
        return None, None
    with open(changelog) as f:
        lines = f.readlines()
    for i, line in enumerate(lines):
        m = re.match(r'##\s+\[(\d+\.\d+[\.\d]*)\]', line)
        if m:
            ver = m.group(1)
            codename = None
            for next_line in lines[i+1:]:
                stripped = next_line.strip()
                if stripped and not stripped.startswith('#'):
                    codename = stripped
                    break
            return ver, codename
    return None, None


def _write_latest_release():
    """Extract latest release section from CHANGELOG.md and write as RST."""
    import re
    if not _moose_core:
        return
    changelog = os.path.join(_moose_core, 'CHANGELOG.md')
    if not os.path.exists(changelog):
        return
    with open(changelog) as f:
        lines = f.readlines()

    # Find first versioned release
    start = None
    ver = ''
    date = ''
    for i, line in enumerate(lines):
        m = re.match(r'##\s+\[(\d+\.\d+[\.\d]*)\]\s*-?\s*(.*)', line)
        if m:
            start = i
            ver = m.group(1)
            date = m.group(2).strip()
            break

    if start is None:
        return

    # Collect lines until the next ## release entry
    section = []
    for line in lines[start + 1:]:
        if re.match(r'##\s+\[', line):
            break
        section.append(line)

    # GitHub release link
    gh_url = f'https://github.com/MooseNeuro/moose-core/releases/tag/v{ver}'
    gh_link = f'\n> **[View release v{ver} on GitHub]({gh_url})**\n\n'

    # Build MD output
    out_path = os.path.join(os.path.dirname(__file__), '_latest_release.md')
    with open(out_path, 'w') as f:
        f.write(f'## {ver}' + (f' — {date}' if date else '') + '\n')
        f.write(gh_link)
        f.write(''.join(section))

_write_latest_release()

# -- General configuration -----------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = ['sphinx.ext.autodoc',
              'sphinx.ext.mathjax',
              'sphinx.ext.autosummary',
              'sphinx.ext.todo',
              'sphinx.ext.viewcode',
              'sphinx_copybutton',
              'hidden_code_block',
              'myst_parser',
#              'breathe',
#              'exhale'
        ]

todo_include_todos = True

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix of source filenames.
source_suffix = '.rst'

# The encoding of source files.
#source_encoding = 'utf-8-sig'

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = u'MOOSE'
copyright = u'2006-2026, Upinder Singh Bhalla, Niraj Dudani, Subhasis Ray, ' + \
        'Aditya Gilra,Harsha Rani, Aviral Goel, Dilawar Singh,' + \
        'Malav Shah, Dhruva Gowda Storz'

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# Auto-read from moose-core CHANGELOG.md on every deploy
_ver, _codename = _parse_moose_version()
version = _ver or '4.2.0'
release = (_codename or 'Kalakand') + ' ' + version

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'English'

# There are two options for replacing |today|: either, you set today to some
# non-false value, then it is used:
today = ''
# Else, today_fmt is used as the format for a strftime call.
today_fmt = '%B %d, %Y'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = ['_build']

# The reST default role (used for this markup: `text`) to use for all documents.
#default_role = None

# If true, '()' will be appended to :func: etc. cross-reference text.
add_function_parentheses = True

# If true, the current module name will be prepended to all description
# unit titles (such as .. function::).
#add_module_names = True

# If true, sectionauthor and moduleauthor directives will be shown in the
# output. They are ignored by default.
#show_authors = False

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'default'
pygments_dark_style = 'github-dark'

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = True

# A list of ignored prefixes for module index sorting.
#modindex_common_prefix = []


# -- Options for HTML output ---------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
html_theme = 'furo'

# sphinx_static/ is at repo root — outside the outdir (public/docs/) so Sphinx copies it correctly
html_static_path = [os.path.join(conf_dir_, 'sphinx_static')]
html_css_files = ['custom.css']
html_js_files = ['custom.js']

html_theme_options = {
    "light_css_variables": {
        "color-brand-primary": "#41729f",
        "color-brand-content": "#41729f",
        "color-sidebar-background": "#ffffff",
        "color-sidebar-background-border": "#c3e0e5",
        "color-sidebar-brand-text": "#274472",
        "color-sidebar-search-foreground": "#274472",
        "color-sidebar-search-background": "#f5f9fc",
        "color-sidebar-search-background--focus": "#e8f2f8",
        "color-sidebar-search-border": "#c3e0e5",
        "color-sidebar-search-icon": "#5885af",
        "color-sidebar-link-text": "#41729f",
        "color-sidebar-link-text--top-level": "#274472",
        "color-sidebar-item-background--hover": "#f5f9fc",
        "color-sidebar-item-background--current": "transparent",
        "color-sidebar-caption-text": "#5885af",
        "color-highlight-on-target": "transparent",
        "color-background-secondary": "#f5f9fc",
    },
    "dark_css_variables": {
        "color-brand-primary": "#5885af",
        "color-brand-content": "#7aafd4",
        "color-sidebar-background": "#1a1c1e",
        "color-sidebar-background-border": "#2d2f31",
        "color-sidebar-link-text": "rgba(255,255,255,0.75)",
        "color-sidebar-link-text--top-level": "#c3e0e5",
        "color-sidebar-item-background--hover": "rgba(88,133,175,0.15)",
        "color-sidebar-item-background--current": "rgba(88,133,175,0.25)",
        "color-sidebar-caption-text": "rgba(195,224,229,0.5)",
        "color-highlight-on-target": "transparent",
        "color-foreground-primary": "#e8e8e8",
        "color-foreground-secondary": "#aaaaaa",
        "color-foreground-muted": "#888888",
        "color-background-primary": "#131416",
        "color-background-secondary": "#1a1c1e",
        "color-background-border": "#303335",
    },
}

# Add any paths that contain custom themes here, relative to this directory.
#html_theme_path = []

# The name for this set of Sphinx documents.  If None, it defaults to
# "<project> v<release> documentation".
#html_title = None

# A shorter title for the navigation bar.  Default is the same as html_title.
#html_short_title = None

# The name of an image file (relative to this directory) to place at the top
# of the sidebar.
html_logo = 'images/moose_logo.png'

# If not '', a 'Last updated on:' timestamp is inserted at every page bottom,
# using the given strftime format.
#html_last_updated_fmt = '%b %d, %Y'

# If true, SmartyPants will be used to convert quotes and dashes to
# typographically correct entities.
#html_use_smartypants = True

# Custom sidebar templates, maps document names to template names.
#html_sidebars = {}

# Additional templates that should be rendered to pages, maps page names to
# template names.
#html_additional_pages = {}

# If false, no module index is generated.
#html_domain_indices = True

# If false, no index is generated.
#html_use_index = True

# If true, the index is split into individual pages for each letter.
#html_split_index = False

# If true, links to the reST sources are added to the pages.
#html_show_sourcelink = True

# If true, "Created using Sphinx" is shown in the HTML footer. Default is True.
#html_show_sphinx = True

# If true, "(C) Copyright ..." is shown in the HTML footer. Default is True.
#html_show_copyright = True

# If true, an OpenSearch description file will be output, and all pages will
# contain a <link> tag referring to it.  The value of this option must be the
# base URL from which the finished HTML is served.
#html_use_opensearch = ''

# This is the file name suffix for HTML files (e.g. ".xhtml").
#html_file_suffix = None

# Output file base name for HTML help builder.
htmlhelp_basename = 'MOOSE'


# -- Options for LaTeX output --------------------------------------------------

latex_elements = {
# The paper size ('letterpaper' or 'a4paper').
'papersize': 'a4paper',

# The font size ('10pt', '11pt' or '12pt').
'pointsize': '11pt',

# Additional stuff for the LaTeX preamble.
'preamble': r'''
\usepackage{libertine} 
\usepackage{mathpazo}
\usepackage{epstopdf}
% Convert GIF to PNG in pdf.
\epstopdfDeclareGraphicsRule{.gif}{png}{.png}{convert gif:#1 png:\OutputFile}
\AppendGraphicsExtensions{.gif}
    '''
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title, author, documentclass [howto/manual]).
latex_documents = [
  ('index', 'MOOSE.tex', u'MOOSE User Manual',
   r'Upinder Singh Bhalla, Niraj Dudani, Subhasis Ray \\Aditya Gilra,Harsha Rani, Aviral Goel \\ Dilawar Singh, Malav Shah, Dhruva Gowda Storz' 
   , 'manual'
   ),
]

# The name of an image file (relative to this directory) to place at the top of
# the title page.
latex_logo = 'images/moose_logo.png'

# For "manual" documents, if this is true, then toplevel headings are parts,
# not chapters.
latex_use_parts = True

# If true, show page references after internal links.
latex_show_pagerefs = True

# If true, show URL addresses after external links.
#latex_show_urls = True

# Documents to append as an appendix to all manuals.
#latex_appendices = []

# If false, no module index is generated.
latex_domain_indices = True


# -- Options for manual page output --------------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    ('index', 'moose', u'MOOSE User Manual',
     [u'Upinder Bhalla, Niraj Dudani, Subhasis Ray, Aditya Gilra,Harsha Rani, Aviral Goel, Dilawar Singh, Malav Shah, Dhruva Gowda Storz'], 1)
]

# If true, show URL addresses after external links.
man_show_urls = True


# -- Options for Texinfo output ------------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
  ('index', 'MOOSE', u'MOOSE Documentation',
   u'Upinder Bhalla, Niraj Dudani, Subhasis Ray, Aditya Gilra,Harsha Rani, Aviral Goel, Dilawar Singh, Malav Shah, Dhruva Gowda Storz'
   , 'MOOSE'
   , 'MOOSE is the Multiscale Object-Oriented Simulation Environment.',
   'Science'),
]

# Documents to append as an appendix to all manuals.
#texinfo_appendices = []

# If false, no module index is generated.
texinfo_domain_indices = True

# How to display URL addresses: 'footnote', 'no', or 'inline'.
#texinfo_show_urls = 'footnote'

#numpydoc option
numpydoc_show_class_members = False

# autodoc options to mock MOOSE module
autodoc_mock_imports = [ 'numpy' , 'moose.sbml' , 'moose.genesis' , 'moose.LIF'
        , 'moogli.extensions.moose' , 'extensions.moose', 'moose' , 'moose.SBML'
        , 'pylab' , 'moose.genesis' , 'datetime' , 'getpass' , 'h5py'
        , 'matplotlib' , 'squid' , 'PyQt4' , 'moogli' , 'moose.utils'
        , 'math' , 'SquidAxon' , '_moogli' , 'XRRRates' , 'neuroml.NeuroML'
        ,'neuroml' , 'rdesigneur' , 'pyplot' , 'gnuplot' , 'cm'
        , 'matplotlib.pyplot' , 'matplotlib.image' , 'matplotlib.cm' , 'shapes'
        , 'chemUtil.add_Delete_ChemicalSolver'
        ]

#include reference files
exclude_patterns = ['_latest_release.md']

#run the doxygen thingy
import subprocess, os
read_the_docs_build = os.environ.get('READTHEDOCS', None) == 'True'

#if not read_the_docs_build:
#    subprocess.call('cd doxygen; echo HELLO......................; doxygen Doxyfile', shell=True)
suppress_warnings = ["app.add_node", "myst.header"]

# -- Breathe / Exhale (C++ API via Doxygen XML) --------------------------------
# _doxy_xml = os.path.abspath(os.path.join(conf_dir_, '../../moose-core/docs/doxygen/cpp/xml'))

# breathe_projects = {"MOOSE": _doxy_xml}
# breathe_default_project = "MOOSE"

# exhale_args = {
#     "containmentFolder":     os.path.join(conf_dir_, "api_from_doc_source"),
#     "rootFileName":          "library_root.rst",
#     "rootFileTitle":         "C++ API",
#     "doxygenStripFromPath":  os.path.abspath(os.path.join(conf_dir_, "../../moose-core")),
#     "createTreeView":        True,
# }

import re

def _plain_to_math(text):
    """Convert a plain-text ODE/equation string to minimal LaTeX."""
    t = text.strip()
    t = re.sub(r'\bd\s*(\w+)\s*/\s*d(\w+)\b', r'\\frac{d\1}{d\2}', t)
    t = re.sub(r'\^(\w+)', r'^{\1}', t)
    t = re.sub(r'\b([A-Z])m\b', r'\1_m', t)
    t = re.sub(r'\btau_(\w+)\b', r'\\tau_{\1}', t)
    t = re.sub(r'\btau\b', r'\\tau', t)
    t = re.sub(r'\bexp\b', r'\\exp', t)
    t = re.sub(r'\bsqrt\b', r'\\sqrt', t)
    t = re.sub(r'\*', r' ', t)
    return t

def _is_equation(line):
    """Return True if line looks like a plain-text differential/algebraic equation."""
    s = line.strip()
    if not s or s.startswith('#') or s.startswith('..'):
        return False  # RST directives already handled
    # Find first standalone = (not <=, >=, !=, ==)
    eq_match = re.search(r'(?<![<>!=])=(?!=)', s)
    if not eq_match:
        return False
    # If the LHS contains a comma, it's prose not math
    lhs = s[:eq_match.start()]
    if ',' in lhs:
        return False
    # Allow spaces between d and variable: d Vm /dt, d u / dt, dVm/dt
    has_deriv = bool(re.search(r'd\s*\w+\s*/\s*d\w+', s))
    has_math  = bool(re.search(r'\b\w+[\*/^]\w+', s))  # tight ops only (avoids RST *italic*)
    # Exclude Python-style assignments (lines with word = word without spaces around ops)
    is_code   = bool(re.match(r'^\w+\s*=\s*\w', s) and '*' not in s and '/' not in s)
    return (has_deriv or has_math) and not is_code

def _fix_docstring(app, what, name, obj, options, lines):
    """Post-process docstrings to improve RST rendering without editing upstream source."""
    new_lines = []
    i = 0
    in_literal = False   # inside a :: literal block — skip all transforms
    lit_base = 0         # indent level of the :: line
    after_colons = False # waiting for content after a :: line

    while i < len(lines):
        line = lines[i]
        stripped = line.strip()
        indent = len(line) - len(line.lstrip()) if stripped else None

        # --- Literal-block state machine ---
        if after_colons:
            if stripped == '':
                new_lines.append(line)
                i += 1
                continue
            after_colons = False
            if indent is not None and indent > lit_base:
                in_literal = True  # entering literal block; fall through to in_literal check

        if in_literal:
            if stripped == '':
                new_lines.append(line)
                i += 1
                continue
            if indent is not None and indent <= lit_base:
                in_literal = False  # dedented — exit block, fall through to normal processing
            else:
                new_lines.append(line)  # inside block, pass through unchanged
                i += 1
                continue

        # --- Normal RST processing (not in a literal block) ---

        # Wrap bare path-like strings in backticks for inline code
        line = re.sub(
            r'(?<![`\w])(/[\w{}/._-]+(?:/[\w{}/._-]+)+)',
            r'``\1``',
            line
        )

        # Convert bare "References:" paragraph into a rubric
        if line.strip() == 'References:':
            new_lines.append('.. rubric:: References')
            i += 1
            continue

        # Detect start of a literal block (line ending with ::)
        if stripped and line.rstrip().endswith('::'):
            lit_base = indent if indent is not None else 0
            after_colons = True
            new_lines.append(line)
            i += 1
            continue

        # Convert plain-text equation lines to .. math:: blocks
        if _is_equation(line):
            eq_indent = len(line) - len(line.lstrip())
            pad = ' ' * eq_indent
            latex = _plain_to_math(line)
            new_lines.append('')
            new_lines.append(pad + '.. math::')
            new_lines.append('')
            new_lines.append(pad + '   ' + latex)
            new_lines.append('')
            i += 1
            continue

        new_lines.append(line)
        i += 1

    lines[:] = new_lines

def _fix_source_rst(app, docname, source):
    """Transform RST source before parsing — fixes hardcoded plain text in classes_demos."""
    if 'classes_demos' not in docname:
        return
    text = source[0]

    # 1. Remove bare function.name()[source] lines (automodule already renders these as dt.sig)
    text = re.sub(r'^\w+\.[\w.]+\([^)]*\)\[source\]\s*\n', '', text, flags=re.MULTILINE)

    # 2. Remove duplicate heading that follows automodule + :members:
    text = re.sub(
        r'(\.\. automodule::.*\n\s+:members:.*\n\n+)[^\n]+\n\n',
        r'\1',
        text
    )

    # 3. Wrap moose.connect() calls and formula lines into code blocks
    lines = text.split('\n')
    result = []
    code_buf = []

    def flush_code():
        if code_buf:
            result.append('')
            result.append('.. code-block:: python')
            result.append('')
            result.extend('   ' + l for l in code_buf)
            result.append('')
            code_buf.clear()

    for line in lines:
        if re.match(r'^(moose\.connect\(|f\([a-zA-Z0-9]|[a-zA-Z] ?= .+[\*\+])', line):
            code_buf.append(line)
        else:
            flush_code()
            result.append(line)
    flush_code()

    source[0] = '\n'.join(result)

def _skip_external_members(app, what, name, obj, skip, options):
    """Skip members that were imported from external packages (e.g. via 'from pylab import *').
    Only keeps members whose __module__ belongs to the documented module."""
    import inspect
    if skip:
        return True
    if what in ('function', 'class', 'exception', 'method'):
        obj_module = getattr(obj, '__module__', None)
        top_module = name.split('.')[0]
        if obj_module is None:
            # C-extension builtins (numpy random functions etc.) — always external
            if inspect.isbuiltin(obj):
                return True
        elif not obj_module.startswith(top_module):
            return True
    return skip

def setup(app):
    app.connect('autodoc-process-docstring', _fix_docstring)
    app.connect('source-read', _fix_source_rst)
    app.connect('autodoc-skip-member', _skip_external_members)
