MOOSE - Multiscale Object Oriented Simulation Environment: /home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/signeur/Adaptor.cpp File Reference
Adaptor.cpp File Reference
#include "../basecode/header.h"
#include "Adaptor.h"
Functions
static SrcFinfo1< double > * output ()
static SrcFinfo1< vector< double > * > * requestOut ()
Variables
static const Cinfo * adaptorCinfo = Adaptor::initCinfo()
Function Documentation
output()
static SrcFinfo1< double > * output () static
This is the adaptor class. It is used in interfacing different kinds of solver with each other, especially for electrical to chemical signeur models.
Definition at line 21 of file Adaptor.cpp.
{
    static SrcFinfo1< double > output( "output",
            "Sends the output value every timestep."
    );
    return &output;
}
References SrcFinfo1< T >::SrcFinfo1().
Referenced by Adaptor::initCinfo(), and Adaptor::process().
requestOut()
static SrcFinfo1< vector< double > * > * requestOut () static
Definition at line 39 of file Adaptor.cpp.
{
    static SrcFinfo1< vector< double >* > requestOut( "requestOut",
            "Sends out a request to a field with a double or array of doubles. "
            "Issued from the process call."
            "Works for any number of targets."
    );
    return &requestOut;
}
References SrcFinfo1< T >::SrcFinfo1().
Referenced by Adaptor::initCinfo(), Adaptor::process(), and Adaptor::reinit().
Variable Documentation
adaptorCinfo
const Cinfo* adaptorCinfo = Adaptor::initCinfo() static
Definition at line 288 of file Adaptor.cpp.