MOOSE - Multiscale Object Oriented Simulation Environment: /home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/basecode/Cinfo.cpp File Reference
Cinfo.cpp File Reference
#include "header.h"
#include "Finfo.h"
#include "../shell/Shell.h"
#include "Dinfo.h"
#include <iomanip>
Functions
void buildFinfoElement (Id parent, vector< Finfo * > &f, const string &name)
Variables
static const Cinfo * cinfoCinfo = Cinfo::initCinfo()
static DestFinfo dummy ("dummy", "This Finfo is a dummy. If you are reading this you " "have used an invalid index", 0)
Function Documentation
buildFinfoElement()
void buildFinfoElement (Id parent, vector< Finfo * > & f, const string & name)
Definition at line 192 of file Cinfo.cpp.
{
    if(f.size() > 0) {
        char* data = reinterpret_cast<char*>(&f[0]);
        Id id = Id::nextId();
        Element* e =
            new GlobalDataElement(id, Finfo::initCinfo(), name, f.size());
        Finfo::initCinfo()->dinfo()->assignData(e->data(0), f.size(), data,
                                                f.size());
        Shell::adopt(parent, id, 0);
    }
}
References Shell::adopt(), DinfoBase::assignData(), Element::data(), Cinfo::dinfo(), GlobalDataElement::GlobalDataElement(), Finfo::initCinfo(), and Id::nextId().
Referenced by Cinfo::makeCinfoElements().
Variable Documentation
cinfoCinfo
const Cinfo* cinfoCinfo = Cinfo::initCinfo() static
Definition at line 394 of file Cinfo.cpp.
dummy
DestFinfo dummy("dummy", "This Finfo is a dummy. If you are reading this you " "have used an invalid index", 0) ("dummy" , "This Finfo is a dummy. If you are reading this you " "have used an invalid index" , 0) static
Referenced by Cinfo::getDestFinfo(), Cinfo::getFieldElementFinfo(), Cinfo::getLookupFinfo(), Cinfo::getSharedFinfo(), and Cinfo::getValueFinfo().