MOOSE - Multiscale Object Oriented Simulation Environment: Test Class Reference
Test Class Reference
Public Member Functions
void handleS0 ()
void handleS1 (const Eref &e, string s)
void handleS2 (const Eref &e, int i1, int i2)
void process (const Eref &e, ProcPtr p)
Test ()
Static Public Member Functions
static const Cinfo * initCinfo ()
Public Attributes
int i1_
int i2_
int numAcks_
string s_
Static Public Attributes
static Finfo * sharedVec [6]
Detailed Description
Definition at line 986 of file testAsync.cpp.
Constructor & Destructor Documentation
Test()
Test::Test () inline
Definition at line 988 of file testAsync.cpp.
           : numAcks_(0)
    {
        ;
    }
References numAcks_.
Member Function Documentation
handleS0()
void Test::handleS0 () inline
Definition at line 998 of file testAsync.cpp.
    {
        numAcks_++;
    }
References numAcks_.
Referenced by testSharedMsg().
handleS1()
void Test::handleS1 (const Eref & e, string s) inline
Definition at line 1003 of file testAsync.cpp.
    {
        s_ = s + s_;
        s0.send(e);
    }
References s0, s_, and SrcFinfo0::send().
Referenced by testSharedMsg().
handleS2()
void Test::handleS2 (const Eref & e, int i1, int i2) inline
Definition at line 1009 of file testAsync.cpp.
    {
        i1_ += 10 * i1;
        i2_ += 10 * i2;
        s0.send(e);
    }
References i1_, i2_, s0, and SrcFinfo0::send().
Referenced by testSharedMsg().
initCinfo()
static const Cinfo * Test::initCinfo () inline static
Definition at line 1018 of file testAsync.cpp.
    {
        static SharedFinfo shared("shared", "", sharedVec,
                                  sizeof(sharedVec) / sizeof(const Finfo*));
        static Finfo* testFinfos[] = {
            &shared,
        };
        static Dinfo<Test> dinfo;
        static Cinfo testCinfo("Test", 0, testFinfos,
                               sizeof(testFinfos) / sizeof(Finfo*), &dinfo);
        return &testCinfo;
    }
References Cinfo::Cinfo(), SharedFinfo::SharedFinfo(), and sharedVec.
Referenced by testMsgSrcDestFields(), and testSharedMsg().
process()
void Test::process (const Eref & e, ProcPtr p) inline
Definition at line 993 of file testAsync.cpp.
    {
        ;
    }
Member Data Documentation
i1_
int Test::i1_
Definition at line 1034 of file testAsync.cpp.
Referenced by handleS2(), and testSharedMsg().
i2_
int Test::i2_
Definition at line 1035 of file testAsync.cpp.
Referenced by handleS2(), and testSharedMsg().
numAcks_
int Test::numAcks_
Definition at line 1036 of file testAsync.cpp.
Referenced by handleS0(), Test(), and testSharedMsg().
s_
string Test::s_
Definition at line 1033 of file testAsync.cpp.
Referenced by handleS1(), and testSharedMsg().
sharedVec
Finfo * Test::sharedVec static
Definition at line 1016 of file testAsync.cpp.
Referenced by initCinfo(), testMsgSrcDestFields(), and testSharedMsg().
The documentation for this class was generated from the following file:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/basecode/testAsync.cpp