MOOSE - Multiscale Object Oriented Simulation Environment: PulseGen Class Reference
PulseGen Class Reference
#include <PulseGen.h>
Public Member Functions
double getBaseLevel () const
unsigned int getCount () const
double getDelay (unsigned int index) const
double getFirstDelay () const
double getFirstLevel () const
double getFirstWidth () const
double getLevel (unsigned int index) const
double getOutput () const
double getPreviousInput () const
double getSecondDelay () const
double getSecondLevel () const
double getSecondWidth () const
unsigned int getTrigMode () const
double getTrigTime () const
double getWidth (unsigned int index) const
void input (double input)
void process (const Eref &e, ProcPtr p)
PulseGen ()
void reinit (const Eref &e, ProcPtr p)
void setBaseLevel (double value)
void setCount (unsigned int count)
void setDelay (unsigned int pulseNo, double delay)
void setFirstDelay (double value)
void setFirstLevel (double value)
void setFirstWidth (double value)
void setLevel (unsigned int pulseNo, double level)
void setSecondDelay (double value)
void setSecondLevel (double value)
void setSecondWidth (double value)
void setTrigMode (unsigned int value)
void setWidth (unsigned int pulseNo, double width)
~PulseGen ()
Static Public Member Functions
static const Cinfo * initCinfo ()
Protected Attributes
double baseLevel_
vector< double > delay_
double input_
vector< double > level_
double output_
double prevInput_
bool secondPulse_
unsigned int trigMode_
double trigTime_
vector< double > width_
Static Private Attributes
static const int EXT_GATE = 2
static const int EXT_TRIG = 1
static const int FREE_RUN = 0
Detailed Description
PulseGen acts as a pulse generator. It generates square pulses of specified duration and amplitude. Two consecutive pulses are separated by specified delay.
Definition at line 40 of file PulseGen.h.
Constructor & Destructor Documentation
PulseGen()
PulseGen::PulseGen ()
Definition at line 148 of file PulseGen.cpp.
{
    level_.reserve(2);
    width_.reserve(2);
    delay_.reserve(2);
    level_.resize(2);
    width_.resize(2);
    delay_.resize(2);
    level_.assign(2, 0.0);
    delay_.assign(2, 0.0);
    width_.assign(2, 0.0);
    output_ = 0.0;
    baseLevel_ = 0.0;
    trigTime_ = -1;
    trigMode_ = 0;
    prevInput_ = 0;
}
References baseLevel_, delay_, level_, output_, prevInput_, trigMode_, trigTime_, and width_.
~PulseGen()
PulseGen::~PulseGen ()
Definition at line 166 of file PulseGen.cpp.
{
    ;
}
Member Function Documentation
getBaseLevel()
double PulseGen::getBaseLevel () const
Definition at line 249 of file PulseGen.cpp.
{
    return baseLevel_;
}
References baseLevel_.
Referenced by initCinfo().
getCount()
unsigned int PulseGen::getCount () const
Definition at line 287 of file PulseGen.cpp.
{
    return level_.size();
}
References level_.
Referenced by initCinfo().
getDelay()
double PulseGen::getDelay (unsigned int index) const
Definition at line 330 of file PulseGen.cpp.
{
    if (index < delay_.size()) {
        return delay_[index];
    } else {
        cout << "WARNING: PulseGen::getDelay - invalid index." << endl;
        return 0.0;
    }
}
References delay_.
Referenced by initCinfo().
getFirstDelay()
double PulseGen::getFirstDelay () const
Definition at line 195 of file PulseGen.cpp.
{
    return delay_[0];
}
References delay_.
Referenced by initCinfo().
getFirstLevel()
double PulseGen::getFirstLevel () const
Definition at line 177 of file PulseGen.cpp.
{
    return level_[0];
}
References level_.
Referenced by initCinfo().
getFirstWidth()
double PulseGen::getFirstWidth () const
Definition at line 187 of file PulseGen.cpp.
{
    return width_[0];
}
References width_.
Referenced by initCinfo().
getLevel()
double PulseGen::getLevel (unsigned int index) const
Definition at line 292 of file PulseGen.cpp.
{
    if (index < level_.size()) {
        return level_[index];
    } else {
        cout << "WARNING: PulseGen::getLevel - invalid index." << endl;
        return 0.0;
    }
}
References level_.
Referenced by initCinfo().
getOutput()
double PulseGen::getOutput () const
Definition at line 261 of file PulseGen.cpp.
{
    return output_;
}
References output_.
Referenced by initCinfo().
getPreviousInput()
double PulseGen::getPreviousInput () const
Definition at line 266 of file PulseGen.cpp.
{
    return prevInput_;
}
References prevInput_.
getSecondDelay()
double PulseGen::getSecondDelay () const
Definition at line 237 of file PulseGen.cpp.
{
    if (delay_.size() >= 2) {
        return delay_[1];
    }
    return 0.0;
}
References delay_.
Referenced by initCinfo().
getSecondLevel()
double PulseGen::getSecondLevel () const
Definition at line 207 of file PulseGen.cpp.
{
    if (level_.size() >= 2) {
        return level_[1];
    } else {
        return 0.0;
    }
}
References level_.
Referenced by initCinfo().
getSecondWidth()
double PulseGen::getSecondWidth () const
Definition at line 223 of file PulseGen.cpp.
{
    if (width_.size() >= 2) {
        return width_[1];
    } else {
        return 0.0;
    }
}
References width_.
Referenced by initCinfo().
getTrigMode()
unsigned int PulseGen::getTrigMode () const
Definition at line 257 of file PulseGen.cpp.
{
    return trigMode_;
}
References trigMode_.
Referenced by initCinfo().
getTrigTime()
double PulseGen::getTrigTime () const
getWidth()
double PulseGen::getWidth (unsigned int index) const
Definition at line 312 of file PulseGen.cpp.
{
    if (index < width_.size()) {
        return width_[index];
    } else {
        cout << "WARNING: PulseGen::getWidth - invalid index." << endl;
        return 0.0;
    }
}
References width_.
Referenced by initCinfo().
initCinfo()
const Cinfo * PulseGen::initCinfo () static
Definition at line 41 of file PulseGen.cpp.
{
    // Field definitions
    static ReadOnlyValueFinfo<PulseGen, double> output(
        "outputValue", "Output amplitude", &PulseGen::getOutput);
    static ValueFinfo<PulseGen, double> baseLevel(
        "baseLevel", "Basal level of the stimulus", &PulseGen::setBaseLevel,
        &PulseGen::getBaseLevel);
    static ValueFinfo<PulseGen, double> firstLevel(
        "firstLevel", "Amplitude of the first pulse in a sequence",
        &PulseGen::setFirstLevel, &PulseGen::getFirstLevel);
    static ValueFinfo<PulseGen, double> firstWidth(
        "firstWidth", "Width of the first pulse in a sequence",
        &PulseGen::setFirstWidth, &PulseGen::getFirstWidth);
    static ValueFinfo<PulseGen, double> firstDelay(
        "firstDelay", "Delay to start of the first pulse in a sequence",
        &PulseGen::setFirstDelay, &PulseGen::getFirstDelay);
    static ValueFinfo<PulseGen, double> secondLevel(
        "secondLevel", "Amplitude of the second pulse in a sequence",
        &PulseGen::setSecondLevel, &PulseGen::getSecondLevel);
    static ValueFinfo<PulseGen, double> secondWidth(
        "secondWidth", "Width of the second pulse in a sequence",
        &PulseGen::setSecondWidth, &PulseGen::getSecondWidth);
    static ValueFinfo<PulseGen, double> secondDelay(
        "secondDelay", "Delay to start of of the second pulse in a sequence",
        &PulseGen::setSecondDelay, &PulseGen::getSecondDelay);
    static ValueFinfo<PulseGen, unsigned int> count(
        "count", "Number of pulses in a sequence", &PulseGen::setCount,
        &PulseGen::getCount);
    static ValueFinfo<PulseGen, unsigned int> trigMode(
        "trigMode",
        "Trigger mode for pulses in the sequence.\n"
        " 0 : free-running mode where it keeps looping its output\n"
        " 1 : external trigger, where it is triggered by an external input (and"
        " stops after creating the first train of pulses)\n"
        " 2 : external gate mode, where it keeps generating the pulses in a"
        " loop as long as the input is high.",
        &PulseGen::setTrigMode, &PulseGen::getTrigMode);
    static LookupValueFinfo<PulseGen, unsigned int, double> level(
        "level", "Level of the pulse at specified index", &PulseGen::setLevel,
        &PulseGen::getLevel);
    static LookupValueFinfo<PulseGen, unsigned int, double> width(
        "width", "Width of the pulse at specified index", &PulseGen::setWidth,
        &PulseGen::getWidth);
    static LookupValueFinfo<PulseGen, unsigned int, double> delay(
        "delay", "Delay of the pulse at specified index", &PulseGen::setDelay,
        &PulseGen::getDelay);
    // Dest messages
    static DestFinfo levelIn(
        "levelIn", "Handle level value coming from other objects",
        new OpFunc2<PulseGen, unsigned int, double>(&PulseGen::setLevel));
    static DestFinfo widthIn(
        "widthIn", "Handle width value coming from other objects",
        new OpFunc2<PulseGen, unsigned int, double>(&PulseGen::setWidth));
    static DestFinfo delayIn(
        "delayIn", "Handle delay value coming from other objects",
        new OpFunc2<PulseGen, unsigned int, double>(&PulseGen::setDelay));
    static DestFinfo input(
        "input",
        "Handle incoming input that determines gating/triggering onset. "
        "Note that although this is a double field, the underlying field is"
        " integer. So fractional part of input will be truncated",
        new OpFunc1<PulseGen, double>(&PulseGen::input));
    // Shared messages
    static DestFinfo process(
        "process", "Handles process call, updates internal time stamp.",
        new ProcOpFunc<PulseGen>(&PulseGen::process));
    static DestFinfo reinit("reinit", "Handles reinit call.",
                            new ProcOpFunc<PulseGen>(&PulseGen::reinit));
    static Finfo* processShared[] = {&process, &reinit};
    static SharedFinfo proc(
        "proc",
        "This is a shared message to receive Process messages "
        "from the scheduler objects."
        "The first entry in the shared msg is a MsgDest "
        "for the Process operation. It has a single argument, "
        "ProcInfo, which holds lots of information about current "
        "time, thread, dt and so on. The second entry is a MsgDest "
        "for the Reinit operation. It also uses ProcInfo. ",
        processShared, sizeof(processShared) / sizeof(Finfo*));
    static Finfo* pulseGenFinfos[] = {
        &output,      &baseLevel,   &firstLevel,  &firstWidth, &firstDelay,
        &secondLevel, &secondWidth, &secondDelay, &count,      &trigMode,
        &level,       &width,       &delay,       &input,      outputOut(),
        &levelIn,     &widthIn,     &delayIn,     &proc, };
    static string doc[] = {
        "Name", "PulseGen", "Author", "Subhasis Ray", "Description",
        "PulseGen: general purpose pulse generator. This can generate any "
        "number of pulses with specified level and duration.", };
    static Dinfo<PulseGen> dinfo;
    static Cinfo pulseGenCinfo("PulseGen", Neutral::initCinfo(), pulseGenFinfos,
                               sizeof(pulseGenFinfos) / sizeof(Finfo*), &dinfo,
                               doc, sizeof(doc) / sizeof(string));
    return &pulseGenCinfo;
}
References Cinfo::Cinfo(), DestFinfo::DestFinfo(), getBaseLevel(), getCount(), getDelay(), getFirstDelay(), getFirstLevel(), getFirstWidth(), getLevel(), getOutput(), getSecondDelay(), getSecondLevel(), getSecondWidth(), getTrigMode(), getWidth(), Neutral::initCinfo(), input(), LookupValueFinfo< T, L, F >::LookupValueFinfo(), OpFunc1< T, A >::OpFunc1(), OpFunc2< T, A1, A2 >::OpFunc2(), outputOut(), process(), ProcOpFunc< T >::ProcOpFunc(), ReadOnlyValueFinfo< T, F >::ReadOnlyValueFinfo(), reinit(), setBaseLevel(), setCount(), setDelay(), setFirstDelay(), setFirstLevel(), setFirstWidth(), setLevel(), setSecondDelay(), setSecondLevel(), setSecondWidth(), setTrigMode(), setWidth(), SharedFinfo::SharedFinfo(), and ValueFinfo< T, F >::ValueFinfo().
input()
void PulseGen::input (double input)
Definition at line 354 of file PulseGen.cpp.
{
    input_ = value;
}
References input_.
Referenced by initCinfo().
process()
void PulseGen::process (const Eref & e, ProcPtr p)
Definition at line 359 of file PulseGen.cpp.
{
    double currentTime = p->currTime;
    double period = width_[0] + delay_[0];
    double phase = 0.0;
    for (unsigned int ii = 1;
         ii < width_.size() && (width_[ii] > 0.0 || delay_[ii] > 0.0); ++ii) {
        double incr = delay_[ii] + width_[ii] - width_[ii - 1];
        if (incr > 0) {
            period += incr;
        }
    }
    switch (trigMode_) {
        case PulseGen::FREE_RUN:
            phase = fmod(currentTime, period);
            break;
        case PulseGen::EXT_TRIG:
            if (input_ == 0) {
                if (trigTime_ < 0) {
                    phase = period;
                } else {
                    phase = currentTime - trigTime_;
                }
            } else {
                if (prevInput_ == 0) {
                    trigTime_ = currentTime;
                }
                phase = currentTime - trigTime_;
            }
            prevInput_ = input_;
            break;
        case PulseGen::EXT_GATE:
            if (input_ == 0) {
                phase = period;       /* output = baselevel */
            } else {                  /* gate high */
                if (prevInput_ == 0) {/* low -> high */
                    trigTime_ = currentTime;
                }
                phase = fmod(currentTime - trigTime_, period);
            }
            prevInput_ = input_;
            break;
        default:
            cerr << "ERROR: PulseGen::newProcessFunc( const Conn* , ProcInfo ) "
                    "- invalid triggerMode - " << trigMode_ << endl;
    }
    if (phase >= period) {  // we have crossed all pulses
        output_ = baseLevel_;
        return;
    }
    // go through all pulse positions to check which pulse/interpulse
    // are we are in and set the output level accordingly
    for (unsigned int ii = 0; ii < width_.size(); ++ii) {
        if (phase <
            delay_[ii]) {  // we are in the baseline area - before ii-th pulse
            output_ = baseLevel_;
            break;
        } else if (phase <
                   delay_[ii] + width_[ii]) {  // we are inside th ii-th pulse
            output_ = level_[ii];
            break;
        }
        phase -= delay_[ii];
    }
    outputOut()->send(e, output_);
}
References baseLevel_, ProcInfo::currTime, delay_, EXT_GATE, EXT_TRIG, FREE_RUN, input_, level_, output_, outputOut(), prevInput_, SrcFinfo1< T >::send(), trigMode_, trigTime_, and width_.
Referenced by initCinfo().
reinit()
void PulseGen::reinit (const Eref & e, ProcPtr p)
Definition at line 426 of file PulseGen.cpp.
{
    trigTime_ = -1;
    prevInput_ = 0;
    output_ = baseLevel_;
    input_ = 0;
    outputOut()->send(e, output_);
}
References baseLevel_, input_, output_, outputOut(), prevInput_, SrcFinfo1< T >::send(), and trigTime_.
Referenced by initCinfo().
setBaseLevel()
void PulseGen::setBaseLevel (double value)
Definition at line 245 of file PulseGen.cpp.
{
    baseLevel_ = level;
}
References baseLevel_.
Referenced by initCinfo().
setCount()
void PulseGen::setCount (unsigned int count)
Definition at line 271 of file PulseGen.cpp.
{
    if (count <= 0) {
        cout << "WARNING: invalid pulse count specified." << endl;
        return;
    }
    // we want to keep it compact - reserve will ensure we do not
    // overallocate in resize call
    level_.reserve(count);
    delay_.reserve(count);
    width_.reserve(count);
    level_.resize(count, 0.0);
    delay_.resize(count, 0.0);
    width_.resize(count, 0.0);
}
References delay_, level_, and width_.
Referenced by initCinfo().
setDelay()
void PulseGen::setDelay (unsigned int pulseNo, double delay)
Definition at line 340 of file PulseGen.cpp.
{
    if (index < delay_.size()) {
        delay_[index] = delay;
    } else {
        cout << "WARNING: PulseGen::setDelay - invalid index. First set the "
                "number of pulses by setting 'count' field." << endl;
    }
}
References delay_.
Referenced by initCinfo().
setFirstDelay()
void PulseGen::setFirstDelay (double value)
Definition at line 191 of file PulseGen.cpp.
{
    delay_[0] = delay;
}
References delay_.
Referenced by initCinfo().
setFirstLevel()
void PulseGen::setFirstLevel (double value)
Definition at line 172 of file PulseGen.cpp.
{
    level_[0] = level;
}
References level_.
Referenced by initCinfo().
setFirstWidth()
void PulseGen::setFirstWidth (double value)
Definition at line 182 of file PulseGen.cpp.
{
    width_[0] = width;
}
References width_.
Referenced by initCinfo().
setLevel()
void PulseGen::setLevel (unsigned int pulseNo, double level)
Definition at line 302 of file PulseGen.cpp.
{
    if (index < level_.size()) {
        level_[index] = level;
    } else {
        cout << "WARNING: PulseGen::setLevel - invalid index. First set the "
                "number of pulses by setting 'count' field." << endl;
    }
}
References level_.
Referenced by initCinfo().
setSecondDelay()
void PulseGen::setSecondDelay (double value)
Definition at line 231 of file PulseGen.cpp.
{
    if (delay_.size() >= 2) {
        delay_[1] = delay;
    }
}
References delay_.
Referenced by initCinfo().
setSecondLevel()
void PulseGen::setSecondLevel (double value)
Definition at line 200 of file PulseGen.cpp.
{
    if (level_.size() >= 2) {
        level_[1] = level;
    }
}
References level_.
Referenced by initCinfo().
setSecondWidth()
void PulseGen::setSecondWidth (double value)
Definition at line 216 of file PulseGen.cpp.
{
    if (width_.size() >= 2) {
        width_[1] = width;
    }
}
References width_.
Referenced by initCinfo().
setTrigMode()
void PulseGen::setTrigMode (unsigned int value)
Definition at line 253 of file PulseGen.cpp.
{
    trigMode_ = mode;
}
References trigMode_.
Referenced by initCinfo().
setWidth()
void PulseGen::setWidth (unsigned int pulseNo, double width)
Definition at line 321 of file PulseGen.cpp.
{
    if (index < width_.size()) {
        width_[index] = width;
    } else {
        cout << "WARNING: PulseGen::setWidth - invalid index. First set the "
                "number of pulses by setting 'count' field." << endl;
    }
}
References width_.
Referenced by initCinfo().
Member Data Documentation
baseLevel_
double PulseGen::baseLevel_ protected
Definition at line 127 of file PulseGen.h.
Referenced by getBaseLevel(), process(), PulseGen(), reinit(), and setBaseLevel().
delay_
vector<double> PulseGen::delay_ protected
Definition at line 122 of file PulseGen.h.
Referenced by getDelay(), getFirstDelay(), getSecondDelay(), process(), PulseGen(), setCount(), setDelay(), setFirstDelay(), and setSecondDelay().
EXT_GATE
const int PulseGen::EXT_GATE = 2 static private
With trigMode = EXT_GATE, the pulse occurs firstDelay later from the leading edge of the input.
Definition at line 67 of file PulseGen.h.
Referenced by process().
EXT_TRIG
const int PulseGen::EXT_TRIG = 1 static private
With trigMode = EXT_TRIG the pulse generator may be triggered or may generate a single pulse and then stop. The logic depends on trigTime field. If trigTime is negative (which it is by default and remains so unless there is a non zero input trigger to the PulseGen object), the output remains at baselevel. For trigTime >= 0, if there is no input trigger, the PulseGen object will produce pair of pulses, the first one starting at firstDelay and staying at firstLevel for firstWidth time. And then the second one starting at secondDelay time after the start of the first pulse, staying at secondLevel for secondWidth time. If secondDelay is less than firstWidth, there will be no second pulse.
Definition at line 62 of file PulseGen.h.
Referenced by process().
FREE_RUN
const int PulseGen::FREE_RUN = 0 static private
With trigMode = FREE_RUN the pulse generator will create a train of pulses determined by the firstDealy, firstWidth, firstLevel, secondDelay, secondWidth and secondLevel.
Definition at line 46 of file PulseGen.h.
Referenced by process().
input_
double PulseGen::input_ protected
Definition at line 133 of file PulseGen.h.
Referenced by input(), process(), and reinit().
level_
vector<double> PulseGen::level_ protected
Definition at line 123 of file PulseGen.h.
Referenced by getCount(), getFirstLevel(), getLevel(), getSecondLevel(), process(), PulseGen(), setCount(), setFirstLevel(), setLevel(), and setSecondLevel().
output_
double PulseGen::output_ protected
Definition at line 126 of file PulseGen.h.
Referenced by getOutput(), process(), PulseGen(), and reinit().
prevInput_
double PulseGen::prevInput_ protected
Definition at line 132 of file PulseGen.h.
Referenced by getPreviousInput(), process(), PulseGen(), and reinit().
secondPulse_
bool PulseGen::secondPulse_ protected
Definition at line 130 of file PulseGen.h.
trigMode_
unsigned int PulseGen::trigMode_ protected
Definition at line 129 of file PulseGen.h.
Referenced by getTrigMode(), process(), PulseGen(), and setTrigMode().
trigTime_
double PulseGen::trigTime_ protected
Definition at line 128 of file PulseGen.h.
Referenced by process(), PulseGen(), and reinit().
width_
vector<double> PulseGen::width_ protected
Definition at line 124 of file PulseGen.h.
Referenced by getFirstWidth(), getSecondWidth(), getWidth(), process(), PulseGen(), setCount(), setFirstWidth(), setSecondWidth(), and setWidth().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/device/PulseGen.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/device/PulseGen.cpp