MOOSE - Multiscale Object Oriented Simulation Environment: SynHandlerBase Class Reference
SynHandlerBase Class Reference abstract
#include <SynHandlerBase.h>
Public Member Functions
virtual void addSpike (unsigned int index, double time, double weight)=0
virtual unsigned int addSynapse ()=0
virtual void dropSynapse (unsigned int droppedSynNumber)=0
unsigned int getNumSynapses () const
Synapse * getSynapse (unsigned int i)
virtual double getTopSpike (unsigned int index) const =0
void process (const Eref &e, ProcPtr p)
bool rangeWarning (const string &field, double value)
void reinit (const Eref &e, ProcPtr p)
void setNumSynapses (unsigned int num)
SynHandlerBase ()
virtual unsigned int vGetNumSynapses () const =0
virtual Synapse * vGetSynapse (unsigned int i)=0
virtual void vProcess (const Eref &e, ProcPtr p)=0
virtual void vReinit (const Eref &e, ProcPtr p)=0
virtual void vSetNumSynapses (unsigned int num)=0
virtual ~SynHandlerBase ()
Static Public Member Functions
static SrcFinfo1< double > * activationOut ()
static const Cinfo * initCinfo ()
Detailed Description
This is a pure virtual base class for accessing and handling synapses. It provides a uniform interface so that all classes that use synapses can do so without duplication. The derived classes have the responsibility of handling the synaptic events as well as possible return events from the parent.
Definition at line 22 of file SynHandlerBase.h.
Constructor & Destructor Documentation
SynHandlerBase()
SynHandlerBase::SynHandlerBase ()
Definition at line 94 of file SynHandlerBase.cpp.
{
    ;
}
~SynHandlerBase()
SynHandlerBase::~SynHandlerBase () virtual
Definition at line 99 of file SynHandlerBase.cpp.
{
    ;
}
Member Function Documentation
activationOut()
SrcFinfo1< double > * SynHandlerBase::activationOut () static
Definition at line 16 of file SynHandlerBase.cpp.
{
    static SrcFinfo1< double > activationOut(
        "activationOut",
        "Sends out level of activation on all synapses converging to "
        "this SynHandler"
    );
    return &activationOut;
}
References SrcFinfo1< T >::SrcFinfo1().
Referenced by initCinfo(), GraupnerBrunel2012CaPlasticitySynHandler::vProcess(), SeqSynHandler::vProcess(), SimpleSynHandler::vProcess(), and STDPSynHandler::vProcess().
addSpike()
virtual void SynHandlerBase::addSpike (unsigned int index, double time, double weight) pure virtual
Record arrival of a new spike event. The 'time' is time for eventual arrival of the spike, and is typically well in the future. The index specifies which synapse the spike came to.
Implemented in GraupnerBrunel2012CaPlasticitySynHandler, SeqSynHandler, SimpleSynHandler, and STDPSynHandler.
Referenced by Synapse::addSpike().
addSynapse()
virtual unsigned int SynHandlerBase::addSynapse () pure virtual
Adds a new synapse, returns its index. This is triggered by addMsg of inputs to the child synapse. The SynHandler has to ensure that we have enough synapses allocated to handle the new message, and the return value is used so that the new message knows the fieldIndex to send the message to.
Implemented in GraupnerBrunel2012CaPlasticitySynHandler, SeqSynHandler, SimpleSynHandler, and STDPSynHandler.
Referenced by Synapse::addMsgCallback().
dropSynapse()
virtual void SynHandlerBase::dropSynapse (unsigned int droppedSynNumber) pure virtual
Drops an existing synapse, triggered by deleteMsg of an input to the child synapse. This is a little messy because we can't change the indices of the other synapses. The Handler has to figure out how to handle the 'holes' in its array of synapses.
Implemented in GraupnerBrunel2012CaPlasticitySynHandler, SeqSynHandler, SimpleSynHandler, and STDPSynHandler.
Referenced by Synapse::dropMsgCallback().
getNumSynapses()
unsigned int SynHandlerBase::getNumSynapses () const
Returns number of synapses defined.
Definition at line 109 of file SynHandlerBase.cpp.
{
    return vGetNumSynapses();
}
References vGetNumSynapses().
Referenced by GraupnerBrunel2012CaPlasticitySynHandler::initCinfo(), SeqSynHandler::initCinfo(), SimpleSynHandler::initCinfo(), STDPSynHandler::initCinfo(), initCinfo(), testSetGetSynapse(), and testSetGetVec().
getSynapse()
Synapse * SynHandlerBase::getSynapse (unsigned int i)
Gets specified synapse
Definition at line 114 of file SynHandlerBase.cpp.
{
    return vGetSynapse( i );
}
References vGetSynapse().
Referenced by GraupnerBrunel2012CaPlasticitySynHandler::initCinfo(), SeqSynHandler::initCinfo(), SimpleSynHandler::initCinfo(), STDPSynHandler::initCinfo(), and testSetGetSynapse().
getTopSpike()
virtual double SynHandlerBase::getTopSpike (unsigned int index) const pure virtual
Implemented in GraupnerBrunel2012CaPlasticitySynHandler, SeqSynHandler, SimpleSynHandler, and STDPSynHandler.
Referenced by Synapse::getTopSpike().
initCinfo()
const Cinfo * SynHandlerBase::initCinfo () static
These are the base set of fields for any object managing synapses. Note that these are duplicated in SynChanBase: if you change anything here it must also be reflected there.
Definition at line 31 of file SynHandlerBase.cpp.
{
    static ValueFinfo< SynHandlerBase, unsigned int > numSynapses(
        "numSynapses",
        "Number of synapses on SynHandler. Duplicate field for num_synapse",
        &SynHandlerBase::setNumSynapses,
        &SynHandlerBase::getNumSynapses
    );
    static DestFinfo process( "process",
                              "Handles 'process' call. Checks if any spike events are due for"
                              "handling at this timestep, and does learning rule stuff if needed",
                              new ProcOpFunc< SynHandlerBase >(& SynHandlerBase::process ) );
    static DestFinfo reinit( "reinit",
                             "Handles 'reinit' call. Initializes all the synapses.",
                             new ProcOpFunc< SynHandlerBase >(& SynHandlerBase::reinit ) );
    static Finfo* processShared[] =
    {
        &process, &reinit
    };
    static SharedFinfo proc( "proc",
                             "Shared Finfo to receive Process messages from the clock.",
                             processShared, sizeof( processShared ) / sizeof( Finfo* )
                           );
    static Finfo* synHandlerFinfos[] =
    {
        &numSynapses,       // Value
        activationOut(),    // SrcFinfo
        &proc,              // SharedFinfo
    };
    static string doc[] =
    {
        "Name", "SynHandlerBase",
        "Author", "Upi Bhalla",
        "Description",
        "Base class for handling synapse arrays converging onto a given "
        "channel or integrate-and-fire neuron. This class provides the "
        "interface for channels/intFires to connect to a range of synapse "
        "types, including simple synapses, synapses with different "
        "plasticity rules, and variants yet to be implemented. "
    };
    static ZeroSizeDinfo< int > dinfo;
    static Cinfo synHandlerCinfo (
        "SynHandlerBase",
        Neutral::initCinfo(),
        synHandlerFinfos,
        sizeof( synHandlerFinfos ) / sizeof ( Finfo* ),
        &dinfo,
        doc,
        sizeof( doc ) / sizeof( string )
    );
    return &synHandlerCinfo;
}
References activationOut(), Cinfo::Cinfo(), DestFinfo::DestFinfo(), getNumSynapses(), Neutral::initCinfo(), process(), ProcOpFunc< T >::ProcOpFunc(), reinit(), setNumSynapses(), SharedFinfo::SharedFinfo(), and ValueFinfo< T, F >::ValueFinfo().
Referenced by GraupnerBrunel2012CaPlasticitySynHandler::initCinfo(), SeqSynHandler::initCinfo(), SimpleSynHandler::initCinfo(), and STDPSynHandler::initCinfo().
process()
void SynHandlerBase::process (const Eref & e, ProcPtr p)
Definition at line 119 of file SynHandlerBase.cpp.
{
    vProcess( e, p );
}
References vProcess().
Referenced by initCinfo().
rangeWarning()
bool SynHandlerBase::rangeWarning (const string & field, double value)
A utility function to check for assignment to fields that must be > 0
Definition at line 129 of file SynHandlerBase.cpp.
{
    if ( value < RANGE )
    {
        cout << "Warning: Ignored attempt to set " << field <<
             " of SynHandler " <<
             // c->target().e->name() <<
             " to less than " << RANGE << endl;
        return 1;
    }
    return 0;
}
References RANGE.
Referenced by GraupnerBrunel2012CaPlasticitySynHandler::setTauCa(), STDPSynHandler::setTauMinus(), STDPSynHandler::setTauPlus(), and GraupnerBrunel2012CaPlasticitySynHandler::setTauSyn().
reinit()
void SynHandlerBase::reinit (const Eref & e, ProcPtr p)
Definition at line 124 of file SynHandlerBase.cpp.
{
    vReinit( e, p );
}
References vReinit().
Referenced by initCinfo().
setNumSynapses()
void SynHandlerBase::setNumSynapses (unsigned int num)
Resizes the synapse storage
Definition at line 104 of file SynHandlerBase.cpp.
{
    vSetNumSynapses( num );
}
References vSetNumSynapses().
Referenced by GraupnerBrunel2012CaPlasticitySynHandler::initCinfo(), SeqSynHandler::initCinfo(), SimpleSynHandler::initCinfo(), STDPSynHandler::initCinfo(), and initCinfo().
vGetNumSynapses()
virtual unsigned int SynHandlerBase::vGetNumSynapses () const pure virtual
Implemented in GraupnerBrunel2012CaPlasticitySynHandler, SeqSynHandler, SimpleSynHandler, and STDPSynHandler.
Referenced by getNumSynapses().
vGetSynapse()
virtual Synapse * SynHandlerBase::vGetSynapse (unsigned int i) pure virtual
Implemented in GraupnerBrunel2012CaPlasticitySynHandler, SeqSynHandler, SimpleSynHandler, and STDPSynHandler.
Referenced by getSynapse().
vProcess()
virtual void SynHandlerBase::vProcess (const Eref & e, ProcPtr p) pure virtual
Implemented in GraupnerBrunel2012CaPlasticitySynHandler, SeqSynHandler, SimpleSynHandler, and STDPSynHandler.
Referenced by process().
vReinit()
virtual void SynHandlerBase::vReinit (const Eref & e, ProcPtr p) pure virtual
Implemented in GraupnerBrunel2012CaPlasticitySynHandler, SeqSynHandler, SimpleSynHandler, and STDPSynHandler.
Referenced by reinit().
vSetNumSynapses()
virtual void SynHandlerBase::vSetNumSynapses (unsigned int num) pure virtual
Implemented in GraupnerBrunel2012CaPlasticitySynHandler, SeqSynHandler, SimpleSynHandler, and STDPSynHandler.
Referenced by setNumSynapses().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/synapse/SynHandlerBase.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/synapse/SynHandlerBase.cpp