MOOSE - Multiscale Object Oriented Simulation Environment: Annotator Class Reference
Annotator Class Reference
#include <Annotator.h>
Public Member Functions
Annotator ()
string getColor () const
string getdirpath () const
double getheight () const
string getIcon () const
string getmodeltype () const
string getNotes () const
double getRuntime () const
string getSolver () const
string getTextColor () const
double getwidth () const
double getX () const
double getY () const
double getZ () const
void setColor (string v)
void setdirpath (string v)
void setheight (double v)
void setIcon (string v)
void setmodeltype (string v)
void setNotes (string v)
void setRuntime (double v)
void setSolver (string v)
void setTextColor (string v)
void setwidth (double v)
void setX (double v)
void setY (double v)
void setZ (double v)
Static Public Member Functions
static const Cinfo * initCinfo ()
Private Attributes
string color_
string dirpath_
double height_
string icon_
string modeltype_
string notes_
double runtime_
string solver_
string textColor_
double width_
double x_
double y_
double z_
Detailed Description
Definition at line 12 of file Annotator.h.
Constructor & Destructor Documentation
Annotator()
Annotator::Annotator ()
Definition at line 131 of file Annotator.cpp.
    : x_( 0.0 ), y_( 0.0 ), z_( 0.0 ), height_(0.0), width_( 0.0 ),
        notes_( "" ), color_( "white" ), textColor_( "black" ),
        icon_( "sphere" ),solver_( "ee"),runtime_(100.0),dirpath_(""),modeltype_("")
{
    ;
}
References color_, dirpath_, height_, icon_, modeltype_, notes_, runtime_, solver_, textColor_, width_, x_, y_, and z_.
Member Function Documentation
getColor()
string Annotator::getColor () const
Definition at line 199 of file Annotator.cpp.
{
    return color_;
}
References color_.
Referenced by initCinfo().
getdirpath()
string Annotator::getdirpath () const
Definition at line 246 of file Annotator.cpp.
{
    return dirpath_;
}
References dirpath_.
Referenced by initCinfo().
getheight()
double Annotator::getheight () const
Definition at line 169 of file Annotator.cpp.
{
    return height_;
}
References height_.
Referenced by initCinfo().
getIcon()
string Annotator::getIcon () const
Definition at line 219 of file Annotator.cpp.
{
    return icon_;
}
References icon_.
Referenced by initCinfo().
getmodeltype()
string Annotator::getmodeltype () const
Definition at line 255 of file Annotator.cpp.
{
    return modeltype_;
}
References modeltype_.
Referenced by initCinfo().
getNotes()
string Annotator::getNotes () const
Definition at line 189 of file Annotator.cpp.
{
    return notes_;
}
References notes_.
Referenced by initCinfo().
getRuntime()
double Annotator::getRuntime () const
Definition at line 237 of file Annotator.cpp.
{
    return runtime_;
}
References runtime_.
Referenced by initCinfo().
getSolver()
string Annotator::getSolver () const
Definition at line 228 of file Annotator.cpp.
{
    return solver_;
}
References solver_.
Referenced by initCinfo().
getTextColor()
string Annotator::getTextColor () const
Definition at line 209 of file Annotator.cpp.
{
    return textColor_;
}
References textColor_.
Referenced by initCinfo().
getwidth()
double Annotator::getwidth () const
Definition at line 179 of file Annotator.cpp.
{
    return width_;
}
References width_.
Referenced by initCinfo().
getX()
double Annotator::getX () const
Definition at line 139 of file Annotator.cpp.
{
    return x_;
}
References x_.
Referenced by initCinfo().
getY()
double Annotator::getY () const
Definition at line 149 of file Annotator.cpp.
{
    return y_;
}
References y_.
Referenced by initCinfo().
getZ()
double Annotator::getZ () const
Definition at line 159 of file Annotator.cpp.
{
    return z_;
}
References z_.
Referenced by initCinfo().
initCinfo()
const Cinfo * Annotator::initCinfo () static
Definition at line 12 of file Annotator.cpp.
{
        // Field Definitions
        static ValueFinfo< Annotator, double > x(
            "x",
            "x field. Typically display coordinate x",
            &Annotator::setX,
            &Annotator::getX
        );
        static ValueFinfo< Annotator, double > y(
            "y",
            "y field. Typically display coordinate y",
            &Annotator::setY,
            &Annotator::getY
        );
        static ValueFinfo< Annotator, double > z(
            "z",
            "z field. Typically display coordinate z",
            &Annotator::setZ,
            &Annotator::getZ
        );
        static ValueFinfo< Annotator, double > width(
            "width",
            "width field. Typically display width",
            &Annotator::setwidth,
            &Annotator::getwidth
        );
        static ValueFinfo< Annotator, double > height(
            "height",
            "height field. Typically display height",
            &Annotator::setheight,
            &Annotator::getheight
        );
        static ValueFinfo< Annotator, string > notes(
            "notes",
            "A string to hold some text notes about parent object",
            &Annotator::setNotes,
            &Annotator::getNotes
        );
        static ValueFinfo< Annotator, string > color(
            "color",
            "A string to hold a text string specifying display color."
            "Can be a regular English color name, or an rgb code rrrgggbbb",
            &Annotator::setColor,
            &Annotator::getColor
        );
        static ValueFinfo< Annotator, string > textColor(
            "textColor",
            "A string to hold a text string specifying color for text label"
            "that might be on the display for this object."
            "Can be a regular English color name, or an rgb code rrrgggbbb",
            &Annotator::setTextColor,
            &Annotator::getTextColor
        );
        static ValueFinfo< Annotator, string > icon(
            "icon",
            "A string to specify icon to use for display",
            &Annotator::setIcon,
            &Annotator::getIcon
        );
        static ValueFinfo< Annotator, string > solver(
            "solver",
            "A string to specify solver to store for Gui",
            &Annotator::setSolver,
            &Annotator::getSolver
        );
        static ValueFinfo< Annotator, double > runtime(
            "runtime",
            "runtime field. Store runtime ",
            &Annotator::setRuntime,
            &Annotator::getRuntime
        );
        static ValueFinfo< Annotator, string > dirpath(
            "dirpath",
            "directory path for Gui",
            &Annotator::setdirpath,
            &Annotator::getdirpath
        );
        static ValueFinfo< Annotator, string > modeltype(
            "modeltype",
            "model type ",
            &Annotator::setmodeltype,
            &Annotator::getmodeltype
        );
    static Finfo* annotatorFinfos[] = {
        &x, // Value
        &y, // Value
        &z, // Value
        &width,
        &height,
        &notes, // Value
        &color, // Value
        &textColor, // Value
        &icon,  // Value
        &solver,
        &runtime,
        &dirpath,
        &modeltype,
    };
    static Dinfo< Annotator > dinfo;
    static Cinfo annotatorCinfo (
        "Annotator",
        Neutral::initCinfo(),
        annotatorFinfos,
        sizeof( annotatorFinfos ) / sizeof ( Finfo* ),
        &dinfo
    );
    return &annotatorCinfo;
}
References Cinfo::Cinfo(), getColor(), getdirpath(), getheight(), getIcon(), getmodeltype(), getNotes(), getRuntime(), getSolver(), getTextColor(), getwidth(), getX(), getY(), getZ(), Neutral::initCinfo(), setColor(), setdirpath(), setheight(), setIcon(), setmodeltype(), setNotes(), setRuntime(), setSolver(), setTextColor(), setwidth(), setX(), setY(), setZ(), and ValueFinfo< T, F >::ValueFinfo().
setColor()
void Annotator::setColor (string v)
Definition at line 204 of file Annotator.cpp.
{
    color_ = v;
}
References color_.
Referenced by initCinfo().
setdirpath()
void Annotator::setdirpath (string v)
Definition at line 251 of file Annotator.cpp.
{
    dirpath_ = v;
}
References dirpath_.
Referenced by initCinfo().
setheight()
void Annotator::setheight (double v)
Definition at line 174 of file Annotator.cpp.
{
    height_ = v;
}
References height_.
Referenced by initCinfo().
setIcon()
void Annotator::setIcon (string v)
Definition at line 224 of file Annotator.cpp.
{
    icon_ = v;
}
References icon_.
Referenced by initCinfo().
setmodeltype()
void Annotator::setmodeltype (string v)
Definition at line 260 of file Annotator.cpp.
{
    modeltype_ = v;
}
References modeltype_.
Referenced by initCinfo().
setNotes()
void Annotator::setNotes (string v)
Definition at line 194 of file Annotator.cpp.
{
    notes_ = v;
}
References notes_.
Referenced by initCinfo().
setRuntime()
void Annotator::setRuntime (double v)
Definition at line 242 of file Annotator.cpp.
{
    runtime_ = v;
}
References runtime_.
Referenced by initCinfo().
setSolver()
void Annotator::setSolver (string v)
Definition at line 233 of file Annotator.cpp.
{
    solver_ = v;
}
References solver_.
Referenced by initCinfo().
setTextColor()
void Annotator::setTextColor (string v)
Definition at line 214 of file Annotator.cpp.
{
    textColor_ = v;
}
References textColor_.
Referenced by initCinfo().
setwidth()
void Annotator::setwidth (double v)
Definition at line 184 of file Annotator.cpp.
{
    width_ = v;
}
References width_.
Referenced by initCinfo().
setX()
void Annotator::setX (double v)
Definition at line 144 of file Annotator.cpp.
{
    x_ = v;
}
References x_.
Referenced by initCinfo().
setY()
void Annotator::setY (double v)
Definition at line 154 of file Annotator.cpp.
{
    y_ = v;
}
References y_.
Referenced by initCinfo().
setZ()
void Annotator::setZ (double v)
Definition at line 164 of file Annotator.cpp.
{
    z_ = v;
}
References z_.
Referenced by initCinfo().
Member Data Documentation
color_
string Annotator::color_ private
Definition at line 55 of file Annotator.h.
Referenced by Annotator(), getColor(), and setColor().
dirpath_
string Annotator::dirpath_ private
Definition at line 60 of file Annotator.h.
Referenced by Annotator(), getdirpath(), and setdirpath().
height_
double Annotator::height_ private
Definition at line 52 of file Annotator.h.
Referenced by Annotator(), getheight(), and setheight().
icon_
string Annotator::icon_ private
Definition at line 57 of file Annotator.h.
Referenced by Annotator(), getIcon(), and setIcon().
modeltype_
string Annotator::modeltype_ private
Definition at line 61 of file Annotator.h.
Referenced by Annotator(), getmodeltype(), and setmodeltype().
notes_
string Annotator::notes_ private
Definition at line 54 of file Annotator.h.
Referenced by Annotator(), getNotes(), and setNotes().
runtime_
double Annotator::runtime_ private
Definition at line 59 of file Annotator.h.
Referenced by Annotator(), getRuntime(), and setRuntime().
solver_
string Annotator::solver_ private
Definition at line 58 of file Annotator.h.
Referenced by Annotator(), getSolver(), and setSolver().
textColor_
string Annotator::textColor_ private
Definition at line 56 of file Annotator.h.
Referenced by Annotator(), getTextColor(), and setTextColor().
width_
double Annotator::width_ private
Definition at line 53 of file Annotator.h.
Referenced by Annotator(), getwidth(), and setwidth().
x_
double Annotator::x_ private
Definition at line 49 of file Annotator.h.
Referenced by Annotator(), getX(), and setX().
y_
double Annotator::y_ private
Definition at line 50 of file Annotator.h.
Referenced by Annotator(), getY(), and setY().
z_
double Annotator::z_ private
Definition at line 51 of file Annotator.h.
Referenced by Annotator(), getZ(), and setZ().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/utility/Annotator.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/utility/Annotator.cpp