MOOSE - Multiscale Object Oriented Simulation Environment: CylBase Class Reference
CylBase Class Reference
#include <CylBase.h>
Public Member Functions
CylBase ()
CylBase (double x, double y, double z, double dia, double length, unsigned int numDivs)
vector< double > getCoordinates (const CylBase &parent, unsigned int entry) const
double getDia () const
double getDiffusionArea (const CylBase &parent, unsigned int index) const
bool getIsCylinder () const
double getLength () const
double getMiddleArea (const CylBase &parent, unsigned int index) const
Return cross-section area of middle of specified voxel.
unsigned int getNumDivs () const
double getVoxelLength () const
Return length of voxel. All are equal.
double getX () const
double getY () const
double getZ () const
void matchCubeMeshEntries (const ChemCompt *other, const CylBase &parent, unsigned int startIndex, double granularity, vector< VoxelJunction > &ret, bool useCylinderCurve, bool useCylinderCap) const
double nearest (double x, double y, double z, const CylBase &parent, double &linePos, double &r) const
double nearest (double x, double y, double z, const CylBase &parent, unsigned int &index) const
double selectGridSize (double h, double dia1, double granularity) const
void setDia (double v)
void setIsCylinder (bool v)
void setLength (double v)
void setNumDivs (unsigned int v)
void setX (double v)
void setY (double v)
void setZ (double v)
double volume (const CylBase &parent) const
Returns vol of current node. Usually needs to refer to parent.
double voxelVolume (const CylBase &parent, unsigned int fid) const
Private Attributes
double dia_
bool isCylinder_
Number of subdivisions of cylinder.
double length_
Diameter of node end.
unsigned int numDivs_
Length of compartment.
double x_
end of the node. The start is given by parent coords.
double y_
double z_
Detailed Description
Base class for cylinder calculations.
Definition at line 17 of file CylBase.h.
Constructor & Destructor Documentation
CylBase() [1/2]
CylBase::CylBase (double x, double y, double z, double dia, double length, unsigned int numDivs)
Definition at line 23 of file CylBase.cpp.
    :
        x_( x ),
        y_( y ),
        z_( z ),
        dia_( dia ),
        length_( length ),
        numDivs_( numDivs ),
        isCylinder_( false )
{
    ;
}
References dia_, isCylinder_, length_, numDivs_, x_, y_, and z_.
Referenced by PsdMesh::handlePsdList(), and NeuroMesh::innerBuildDefaultMesh().
CylBase() [2/2]
CylBase::CylBase ()
Definition at line 37 of file CylBase.cpp.
    :
        x_( 0.0 ),
        y_( 0.0 ),
        z_( 0.0 ),
        dia_( 1.0 ),
        length_( 1.0 ),
        numDivs_( 1 ),
        isCylinder_( false )
{
    ;
}
References dia_, isCylinder_, length_, numDivs_, x_, y_, and z_.
Member Function Documentation
getCoordinates()
vector< double > CylBase::getCoordinates (const CylBase & parent, unsigned int fid) const
Returns a vector with the coordinates of the specified MeshEntry. The MeshEntry (entry argument) is a voxel within this CylBase, 'entry' is indexed from 0 to numDivs. The parent is the parent CylBase with its own set of coords. The function does interpolation from the ends of the Node. These are detailed coordinates representative of the shape of the MeshEntry. For cylinders it is x1y1z1 x2y2z2 r0 r1 phi0 phi1 For spheres it is xyzdia.
Virtual function to return coords of mesh Entry. For Cylindrical mesh, coords are x1y1z1 x2y2z2 r0 r1 phi0 phi1
Definition at line 169 of file CylBase.cpp.
{
    assert( numDivs_ > fid );
    double frac0 = ( static_cast< double >( fid ) ) /
                static_cast< double >( numDivs_ );
    double frac1 = ( static_cast< double >( fid + 1 ) ) /
                static_cast< double >( numDivs_ );
    double r0 = 0.5 * ( parent.dia_ * ( 1.0 - frac0 ) + dia_ * frac0 );
    // equivalent: double r0 = parent.dia_ + frac0 * ( dia_ - parent.dia_ );
    double r1 = 0.5 * ( parent.dia_ * ( 1.0 - frac1 ) + dia_ * frac1 );
    vector< double > ret( 10, 0.0 );
    ret[0] = parent.x_ + frac0 * ( x_ - parent.x_ );
    ret[1] = parent.y_ + frac0 * ( y_ - parent.y_ );
    ret[2] = parent.z_ + frac0 * ( z_ - parent.z_ );
    ret[3] = parent.x_ + frac1 * ( x_ - parent.x_ );
    ret[4] = parent.y_ + frac1 * ( y_ - parent.y_ );
    ret[5] = parent.z_ + frac1 * ( z_ - parent.z_ );
    ret[6] = r0;
    ret[7] = r1;
    ret[8] = 0;
    ret[9] = 0;
    return ret;
}
References dia_, numDivs_, x_, y_, and z_.
Referenced by NeuroMesh::getCoordinates(), NeuroMesh::vGetVoxelMidpoint(), and PsdMesh::vGetVoxelMidpoint().
getDia()
double CylBase::getDia () const
Definition at line 85 of file CylBase.cpp.
{
    return dia_;
}
References dia_.
Referenced by NeuroNode::findStartNode(), PsdMesh::getCoordinates(), NeuroMesh::innerSetNumEntries(), SpineEntry::psdCoords(), SpineEntry::rootArea(), SpineEntry::setVolume(), SpineEntry::spineCoords(), NeuroMesh::vSetVolumeNotRates(), and PsdMesh::vSetVolumeNotRates().
getDiffusionArea()
double CylBase::getDiffusionArea (const CylBase & parent, unsigned int fid) const
Returns diffusion cross-section from specified index to next. For index 0, this is cross-section to parent. For index numDivs-1, it is the cross-section from the second-last to the last voxel in this CylBase. Thus there is no valid value for (index == numDivs - 1), it has to be computed external to the CylBase, typically by calling the getDiffusionArea for the child CylBase.
Returns diffusion cross-section from specified index to previous. For index 0, this is cross-section area of parent. For index numDivs-1, it is the cross-section from the second-last to the last voxel in this CylBase. For index numDivs it is the area of this CylBase. Thus there is no valid value for (index > numDivs), it has to be computed external to the CylBase, typically by calling the getDiffusionArea for the child CylBase.
Definition at line 207 of file CylBase.cpp.
{
    assert( fid < numDivs_ + 1 );
    if ( isCylinder_ )
            return M_PI * dia_ * dia_ / 4.0;
    double frac0 = ( static_cast< double >( fid ) ) /
                static_cast< double >( numDivs_ );
    double r0 = 0.5 * ( parent.dia_ * ( 1.0 - frac0 ) + dia_ * frac0 );
    return M_PI * r0 * r0;
}
References dia_, isCylinder_, and numDivs_.
Referenced by NeuroMesh::getAdx(), NeuroMesh::getDiffusionArea(), PsdMesh::getDiffusionArea(), PsdMesh::getMeshEntryVolume(), PsdMesh::handlePsdList(), PsdMesh::matchNeuroMeshEntries(), and PsdMesh::matchSpineMeshEntries().
getIsCylinder()
bool CylBase::getIsCylinder () const
Definition at line 115 of file CylBase.cpp.
{
    return isCylinder_;
}
References isCylinder_.
getLength()
double CylBase::getLength () const
Definition at line 95 of file CylBase.cpp.
{
    return length_;
}
References length_.
Referenced by NeuroNode::calculateLength(), SpineEntry::diffusionLength(), NeuroMesh::getAdx(), NeuroMesh::innerSetNumEntries(), NeuroMesh::insertSingleDummy(), SpineEntry::setVolume(), NeuroMesh::updateCoords(), NeuroMesh::vSetVolumeNotRates(), and PsdMesh::vSetVolumeNotRates().
getMiddleArea()
double CylBase::getMiddleArea (const CylBase & parent, unsigned int index) const
Return cross-section area of middle of specified voxel.
Return the cross section area of the middle of the specified voxel.
Definition at line 220 of file CylBase.cpp.
{
    assert( fid < numDivs_ );
    if ( isCylinder_ )
            return M_PI * dia_ * dia_ / 4.0;
    double frac0 = ( 0.5 + static_cast< double >( fid ) ) /
                static_cast< double >( numDivs_ );
    double r0 = 0.5 * ( parent.dia_ * ( 1.0 - frac0 ) + dia_ * frac0 );
    return M_PI * r0 * r0;
}
References dia_, isCylinder_, and numDivs_.
Referenced by NeuroMesh::updateCoords().
getNumDivs()
unsigned int CylBase::getNumDivs () const
Definition at line 105 of file CylBase.cpp.
{
    return numDivs_;
}
References numDivs_.
Referenced by NeuroMesh::getAdx(), NeuroMesh::getDendVoxelsOnCompartment(), NeuroMesh::getEndVoxelInCompt(), NeuroMesh::indexToSpace(), NeuroNode::isDummyNode(), NeuroMesh::nearest(), NeuroMesh::updateCoords(), and NeuroMesh::vGetVoxelMidpoint().
getVoxelLength()
double CylBase::getVoxelLength () const
Return length of voxel. All are equal.
Definition at line 232 of file CylBase.cpp.
{
    return length_ / numDivs_;
}
References length_, and numDivs_.
Referenced by NeuroMesh::updateCoords().
getX()
double CylBase::getX () const
Definition at line 55 of file CylBase.cpp.
{
    return x_;
}
References x_.
Referenced by NeuroNode::calculateLength(), PsdMesh::getCoordinates(), NeuroMesh::indexToSpace(), PsdMesh::indexToSpace(), NeuroMesh::insertDummyNodes(), SpineEntry::mid(), PsdMesh::nearest(), SpineEntry::positionShaftBase(), SpineEntry::psdCoords(), SpineEntry::setVolume(), SpineEntry::spineCoords(), and NeuroMesh::updateShaftParents().
getY()
double CylBase::getY () const
Definition at line 65 of file CylBase.cpp.
{
    return y_;
}
References y_.
Referenced by NeuroNode::calculateLength(), PsdMesh::getCoordinates(), NeuroMesh::indexToSpace(), PsdMesh::indexToSpace(), NeuroMesh::insertDummyNodes(), SpineEntry::mid(), PsdMesh::nearest(), SpineEntry::positionShaftBase(), SpineEntry::psdCoords(), SpineEntry::setVolume(), SpineEntry::spineCoords(), and NeuroMesh::updateShaftParents().
getZ()
double CylBase::getZ () const
Definition at line 75 of file CylBase.cpp.
{
    return z_;
}
References z_.
Referenced by NeuroNode::calculateLength(), PsdMesh::getCoordinates(), NeuroMesh::indexToSpace(), PsdMesh::indexToSpace(), NeuroMesh::insertDummyNodes(), SpineEntry::mid(), PsdMesh::nearest(), SpineEntry::positionShaftBase(), SpineEntry::psdCoords(), SpineEntry::setVolume(), SpineEntry::spineCoords(), and NeuroMesh::updateShaftParents().
matchCubeMeshEntries()
void CylBase::matchCubeMeshEntries (const ChemCompt * other, const CylBase & parent, unsigned int startIndex, double granularity, vector< VoxelJunction > & ret, bool useCylinderCurve, bool useCylinderCap) const
Definition at line 317 of file CylBase.cpp.
{
    const CubeMesh* other = dynamic_cast< const CubeMesh* >( compt );
    assert( other );
    const double EPSILON = 1e-18;
    Vec a( parent.x_ - x_, parent.y_ - y_, parent.z_ - z_ );
    Vec u;
    Vec v;
    a.orthogonalAxes( u, v );
    double h = selectGridSize( other->getDx(), parent.dia_/2, granularity );
    double lambda = length_ / numDivs_;
    unsigned int num = static_cast<unsigned int>(floor( 0.1 + lambda / h ));
    // March along axis of cylinder.
    // q is the location of the point along axis.
    double rSlope = ( dia_ - parent.dia_ ) * 0.5 / length_;
    for ( unsigned int i = 0; i < numDivs_; ++i ) {
        vector< double >area( other->getNumEntries(), 0.0 );
        if ( useCylinderCurve ) {
            for ( unsigned int j = 0; j < num; ++j ) {
                unsigned int m = i * num + j;
                double frac = ( m * h + h/2.0 ) / length_;
                double q0 = x_ + a.a0() * frac;
                double q1 = y_ + a.a1() * frac;
                double q2 = z_ + a.a2() * frac;
                // get radius of cylinder at this point.
                double r = dia_/2.0;
                if ( !isCylinder_ ) // Use the more complicated conic value
                r = parent.dia_/2.0 + frac * rSlope;
                fillPointsOnCircle( u, v, Vec( q0, q1, q2 ),
                            h, r, area, other );
            }
        }
        if ( useCylinderCap && i == numDivs_ - 1 ) {
            fillPointsOnDisc( u, v, Vec( x_, y_, z_ ),
                            h, dia_/2.0, area, other );
        }
        // Go through all cubeMesh entries and compute diffusion
        // cross-section. Assume this is through a membrane, so the
        // only factor relevant is area. Not the distance.
        for ( unsigned int k = 0; k < area.size(); ++k ) {
            if ( area[k] > EPSILON ) {
                ret.push_back( VoxelJunction( i + startIndex, k, area[k] ));
            }
        }
    }
}
References Vec::a0(), Vec::a1(), Vec::a2(), dia_, fillPointsOnCircle(), fillPointsOnDisc(), CubeMesh::getDx(), ChemCompt::getNumEntries(), isCylinder_, length_, numDivs_, Vec::orthogonalAxes(), selectGridSize(), Vec::Vec(), VoxelJunction::VoxelJunction(), x_, y_, and z_.
Referenced by SpineEntry::matchCubeMeshEntries(), NeuroMesh::matchCubeMeshEntries(), PsdMesh::matchCubeMeshEntries(), SpineEntry::matchCubeMeshEntriesToHead(), and SpineEntry::matchCubeMeshEntriesToPSD().
nearest() [1/2]
double CylBase::nearest (double x, double y, double z, const CylBase & parent, double & linePos, double & r) const
Definition at line 375 of file CylBase.cpp.
{
    const double EPSILON = 1e-8; // 10 nm is too small for any compt.
    // Consider a = parent and b = self, and c = x,y,z.
    // Fraction along cylinder axis ab = k
    // k = (c - a).(b - a)/((b-a).(b-a))
    //
    // Then, point p along line from parent to self is
    // p = k( self-parent) + parent.
    //
    // So distance from c to p is what we want.
    //
    // If k is
    //
    Vec a( parent.x_, parent.y_, parent.z_ );
    Vec b( x_, y_, z_ );
    Vec c( x, y, z );
    double dist = b.distance( a );
    assert( dist > EPSILON );
    double k = ( b - a ).dotProduct( c - a );
    k /= dist * dist;
    Vec pt = a.pointOnLine( b, k );
    double ret = c.distance(pt);
    linePos = k;
    // For now I disable the positioning with a tapering cylinder.
    // double rSlope = 0.5 * ( dia_ - parent.dia_ ) / numDivs_;
    double rSlope = 0;
    r = dia_/2.0 + k * numDivs_ * rSlope;
    return ret;
}
References dia_, Vec::distance(), Vec::dotProduct(), numDivs_, Vec::operator-(), Vec::pointOnLine(), Vec::Vec(), x_, y_, and z_.
Referenced by nearest(), and NeuroMesh::nearest().
nearest() [2/2]
double CylBase::nearest (double x, double y, double z, const CylBase & parent, unsigned int & index) const
Definition at line 411 of file CylBase.cpp.
{
    double k = 0.0;
    double r;
    double ret = nearest( x, y, z, parent, k, r );
    if ( k < 0.0 ) {
        ret = -ret;
        index = 0;
    } else if ( k > 1.0 ) {
        ret = -ret;
        index = numDivs_ - 1;
    } else { // Inside length of cylinder, now is it inside radius?
        index = static_cast<unsigned int>(k * numDivs_);
        if ( index >= numDivs_ )
            index = numDivs_ - 1;
        // double ri = r0_ + (index + 0.5) * rSlope_;
        if ( ret > r * 1.01 ) // Handle roundoff
            ret = -ret;
    }
    return ret;
}
References nearest(), and numDivs_.
Referenced by NeuroMesh::updateShaftParents().
selectGridSize()
double CylBase::selectGridSize (double h, double dia1, double granularity) const
Utility commands for building interface to cube mesh
Definition at line 239 of file CylBase.cpp.
{
    if ( length_ < 1e-7 && numDivs_ == 1 ) { // It is a disc, not a cylinder
        return granularity * dia_ / 2.0;
    }
    double lambda = length_ / numDivs_;
    if ( h > lambda )
        h = lambda;
    if ( h > dia_ / 2.0 )
        h = dia_ / 2.0;
    if ( h > dia1/2.0 )
        h = dia1/2.0;
    h *= granularity;
    unsigned int num = static_cast<unsigned int>(ceil( lambda / h ));
    h = lambda / num;
    return h;
}
References dia_, length_, and numDivs_.
Referenced by matchCubeMeshEntries().
setDia()
void CylBase::setDia (double v)
Definition at line 80 of file CylBase.cpp.
{
    dia_ = v;
}
References dia_.
Referenced by PsdMesh::handlePsdList(), NeuroMesh::NeuroMesh(), NeuroNode::NeuroNode(), PsdMesh::PsdMesh(), PsdMesh::setMeshEntryVolume(), SpineEntry::setVolume(), SpineEntry::SpineEntry(), SpineEntry::SpineEntry(), NeuroMesh::vSetVolumeNotRates(), and PsdMesh::vSetVolumeNotRates().
setIsCylinder()
void CylBase::setIsCylinder (bool v)
Definition at line 110 of file CylBase.cpp.
{
    isCylinder_ = v;
}
References isCylinder_.
Referenced by PsdMesh::handlePsdList(), NeuroMesh::insertSingleDummy(), PsdMesh::PsdMesh(), NeuroMesh::setGeometryPolicy(), SpineEntry::SpineEntry(), and SpineEntry::SpineEntry().
setLength()
void CylBase::setLength (double v)
Definition at line 90 of file CylBase.cpp.
{
    length_ = v;
}
References length_.
Referenced by NeuroNode::calculateLength(), PsdMesh::handlePsdList(), NeuroMesh::NeuroMesh(), NeuroNode::NeuroNode(), PsdMesh::PsdMesh(), SpineEntry::setVolume(), SpineEntry::SpineEntry(), SpineEntry::SpineEntry(), NeuroMesh::vSetVolumeNotRates(), and PsdMesh::vSetVolumeNotRates().
setNumDivs()
void CylBase::setNumDivs (unsigned int v)
Definition at line 100 of file CylBase.cpp.
{
    numDivs_ = v;
}
References numDivs_.
Referenced by NeuroMesh::insertSingleDummy(), NeuroMesh::NeuroMesh(), PsdMesh::PsdMesh(), SpineEntry::SpineEntry(), SpineEntry::SpineEntry(), and NeuroMesh::updateCoords().
setX()
void CylBase::setX (double v)
Definition at line 50 of file CylBase.cpp.
{
    x_ = v;
}
References x_.
Referenced by NeuroMesh::insertSingleDummy(), NeuroNode::NeuroNode(), SpineEntry::positionShaftBase(), SpineEntry::setVolume(), SpineEntry::SpineEntry(), and SpineEntry::SpineEntry().
setY()
void CylBase::setY (double v)
Definition at line 60 of file CylBase.cpp.
{
    y_ = v;
}
References y_.
Referenced by NeuroMesh::insertSingleDummy(), NeuroNode::NeuroNode(), SpineEntry::positionShaftBase(), SpineEntry::setVolume(), SpineEntry::SpineEntry(), and SpineEntry::SpineEntry().
setZ()
void CylBase::setZ (double v)
Definition at line 70 of file CylBase.cpp.
{
    z_ = v;
}
References z_.
Referenced by NeuroMesh::insertSingleDummy(), NeuroNode::NeuroNode(), SpineEntry::positionShaftBase(), SpineEntry::setVolume(), SpineEntry::SpineEntry(), and SpineEntry::SpineEntry().
volume()
double CylBase::volume (const CylBase & parent) const
Returns vol of current node. Usually needs to refer to parent.
The entire volume for a truncated cone is given by: V = 1/3 pi.length.(r0^2 + r0.r1 + r1^2) where the length is the length of the cone r0 is radius at base r1 is radius at top. Note that this converges to volume of a cone if r0 or r1 is zero, and to the volume of a cylinder if r0 == r1.
Definition at line 132 of file CylBase.cpp.
{
    if ( isCylinder_ )
            return length_ * dia_ * dia_ * M_PI / 4.0;
    double r0 = parent.dia_/2.0;
    double r1 = dia_/2.0;
    return length_ * ( r0*r0 + r0 *r1 + r1 * r1 ) * M_PI / 3.0;
}
References dia_, isCylinder_, and length_.
Referenced by PsdMesh::handlePsdList(), SpineEntry::setVolume(), SpineEntry::volume(), and NeuroMesh::vSetVolumeNotRates().
voxelVolume()
double CylBase::voxelVolume (const CylBase & parent, unsigned int fid) const
Returns volume of specified voxel (MeshEntry)
Returns volume of MeshEntry. This isn't the best subdivision of the cylinder from the viewpoint of keeping the length constants all the same for different volumes. Ideally the thinner segments should have a smaller length. But this is simple and so is the diffusion calculation, so leave it. Easy to fine-tune later by modifying how one computes frac0 and frac1.
Definition at line 149 of file CylBase.cpp.
{
    assert( numDivs_ > fid );
    if ( isCylinder_ )
            return length_ * dia_ * dia_ * M_PI / ( 4.0 * numDivs_ );
    double frac0 = ( static_cast< double >( fid ) ) /
                static_cast< double >( numDivs_ );
    double frac1 = ( static_cast< double >( fid + 1 ) ) /
                static_cast< double >( numDivs_ );
    double r0 = 0.5 * ( parent.dia_ * ( 1.0 - frac0 ) + dia_ * frac0 );
    double r1 = 0.5 * ( parent.dia_ * ( 1.0 - frac1 ) + dia_ * frac1 );
    double s0 = length_ * frac0;
    double s1 = length_ * frac1;
    return (s1 - s0) * ( r0*r0 + r0 *r1 + r1 * r1 ) * M_PI / 3.0;
}
References dia_, isCylinder_, length_, and numDivs_.
Referenced by NeuroMesh::getMeshEntryVolume(), and NeuroMesh::updateCoords().
Member Data Documentation
dia_
double CylBase::dia_ private
Definition at line 107 of file CylBase.h.
Referenced by CylBase(), CylBase(), getCoordinates(), getDia(), getDiffusionArea(), getMiddleArea(), matchCubeMeshEntries(), nearest(), selectGridSize(), setDia(), volume(), and voxelVolume().
isCylinder_
bool CylBase::isCylinder_ private
Number of subdivisions of cylinder.
Definition at line 110 of file CylBase.h.
Referenced by CylBase(), CylBase(), getDiffusionArea(), getIsCylinder(), getMiddleArea(), matchCubeMeshEntries(), setIsCylinder(), volume(), and voxelVolume().
length_
double CylBase::length_ private
Diameter of node end.
Definition at line 108 of file CylBase.h.
Referenced by CylBase(), CylBase(), getLength(), getVoxelLength(), matchCubeMeshEntries(), selectGridSize(), setLength(), volume(), and voxelVolume().
numDivs_
unsigned int CylBase::numDivs_ private
Length of compartment.
Definition at line 109 of file CylBase.h.
Referenced by CylBase(), CylBase(), getCoordinates(), getDiffusionArea(), getMiddleArea(), getNumDivs(), getVoxelLength(), matchCubeMeshEntries(), nearest(), nearest(), selectGridSize(), setNumDivs(), and voxelVolume().
x_
double CylBase::x_ private
end of the node. The start is given by parent coords.
Definition at line 103 of file CylBase.h.
Referenced by CylBase(), CylBase(), getCoordinates(), getX(), matchCubeMeshEntries(), nearest(), and setX().
y_
double CylBase::y_ private
Definition at line 104 of file CylBase.h.
Referenced by CylBase(), CylBase(), getCoordinates(), getY(), matchCubeMeshEntries(), nearest(), and setY().
z_
double CylBase::z_ private
Definition at line 105 of file CylBase.h.
Referenced by CylBase(), CylBase(), getCoordinates(), getZ(), matchCubeMeshEntries(), nearest(), and setZ().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/mesh/CylBase.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/mesh/CylBase.cpp