MOOSE - Multiscale Object Oriented Simulation Environment: VectorTable Class Reference
VectorTable Class Reference
#include <VectorTable.h>
Public Member Functions
unsigned int getDiv () const
double getInvDx () const
double getMax () const
double getMin () const
vector< double > getTable () const
double lookupByIndex (unsigned int) const
double lookupByValue (double) const
void setDiv (unsigned int)
void setMax (double)
void setMin (double)
void setTable (vector< double >)
bool tableIsEmpty () const
VectorTable ()
Static Public Member Functions
static const Cinfo * initCinfo ()
Private Attributes
double invDx_
vector< double > table_
unsigned int xDivs_
double xMax_
double xMin_
Friends
istream & operator>> (istream &, VectorTable &)
Detailed Description
Definition at line 21 of file VectorTable.h.
Constructor & Destructor Documentation
VectorTable()
VectorTable::VectorTable ()
Definition at line 102 of file VectorTable.cpp.
                         : xDivs_(INIT_XDIV), xMin_(INIT_XMIN), xMax_(INIT_XMAX),
                                                         invDx_(-1), table_(0)
{ ; }
References invDx_, table_, xDivs_, xMax_, and xMin_.
Referenced by MarkovRateTable::innerSetVtChildTable().
Member Function Documentation
getDiv()
unsigned int VectorTable::getDiv () const
Definition at line 181 of file VectorTable.cpp.
{
    return xDivs_;
}
References xDivs_.
Referenced by initCinfo(), MarkovRateTable::isRate1d(), MarkovRateTable::isRateConstant(), and MarkovSolverBase::setLookupParams().
getInvDx()
double VectorTable::getInvDx () const
Definition at line 211 of file VectorTable.cpp.
{
    return invDx_;
}
References invDx_.
Referenced by initCinfo().
getMax()
double VectorTable::getMax () const
Definition at line 201 of file VectorTable.cpp.
{
    return xMax_;
}
References xMax_.
Referenced by initCinfo(), and MarkovSolverBase::setLookupParams().
getMin()
double VectorTable::getMin () const
Definition at line 191 of file VectorTable.cpp.
{
    return xMin_;
}
References xMin_.
Referenced by initCinfo(), and MarkovSolverBase::setLookupParams().
getTable()
vector< double > VectorTable::getTable () const
Definition at line 142 of file VectorTable.cpp.
{
    if ( table_.size() == 0 )
    {
        cerr << "VectorTable::getTable : Warning : Table is empty\n";
    }
    return table_;
}
References table_.
Referenced by initCinfo().
initCinfo()
const Cinfo * VectorTable::initCinfo () static
Definition at line 18 of file VectorTable.cpp.
{
    //Field information.
    static ValueFinfo< VectorTable, unsigned int > xdivs("xdivs",
            "Number of divisions.",
            &VectorTable::setDiv,
            &VectorTable::getDiv
            );
    static ValueFinfo< VectorTable, double > xmin("xmin",
            "Minimum value in table.",
            &VectorTable::setMin,
            &VectorTable::getMin
            );
    static ValueFinfo< VectorTable, double > xmax("xmax",
            "Maximum value in table.",
            &VectorTable::setMax,
            &VectorTable::getMax
            );
    static ReadOnlyValueFinfo< VectorTable, double > invdx("invdx",
            "Maximum value in table.",
            &VectorTable::getInvDx
            );
    static ValueFinfo< VectorTable, vector< double > > table("table",
            "The lookup table.",
            &VectorTable::setTable,
            &VectorTable::getTable
            );
    static ReadOnlyLookupValueFinfo< VectorTable, double, double >
            lookupvalue(
            "lookupvalue",
            "Lookup function that performs interpolation to return a value.",
            &VectorTable::lookupByValue
            );
    static ReadOnlyLookupValueFinfo< VectorTable, unsigned int, double >
            lookupindex(
            "lookupindex",
            "Lookup function that returns value by index.",
            &VectorTable::lookupByIndex
            );
    static Finfo* vectorTableFinfos[] =
    {
        &xdivs,
        &xmin,
        &xmax,
        &invdx,
        &table,
        &lookupvalue,
        &lookupindex
    };
    static string doc[] =
    {
        "Name", "VectorTable",
        "Author", "Vishaka Datta S, 2011, NCBS",
        "Description", "This is a minimal 1D equivalent of the Interpol2D class. "
        "Provides simple functions for getting and setting up the table, along "
        "with a lookup function. This class is to be used while supplying lookup "
        "tables to the MarkovChannel class, in cases where the transition rate "
        "varies with either membrane voltage or ligand concentration."
    };
    static Dinfo< VectorTable > dinfo;
    static Cinfo VectorTableCinfo(
        "VectorTable",
        Neutral::initCinfo(),
        vectorTableFinfos,
        sizeof( vectorTableFinfos )/sizeof( Finfo* ),
        &dinfo,
        doc,
        sizeof( doc ) / sizeof( string )
    );
    return &VectorTableCinfo;
}
References Cinfo::Cinfo(), getDiv(), getInvDx(), getMax(), getMin(), getTable(), Neutral::initCinfo(), lookupByIndex(), lookupByValue(), ReadOnlyLookupValueFinfo< T, L, F >::ReadOnlyLookupValueFinfo(), ReadOnlyValueFinfo< T, F >::ReadOnlyValueFinfo(), setDiv(), setMax(), setMin(), setTable(), and ValueFinfo< T, F >::ValueFinfo().
lookupByIndex()
double VectorTable::lookupByIndex (unsigned int index) const
Definition at line 122 of file VectorTable.cpp.
{
    if ( tableIsEmpty() )
        return 0;
    /*  NOTE: Why commented out?
     *  index is unsigned int, can't be less than zero.
    */
#if 0
    //Applying similar wrapping as is done in lookupByValue.
    if ( index < 0 )
        index = 0;
#endif
    if ( index >= table_.size() )
        index = table_.size() - 1;
    return table_[index];
}
References table_, and tableIsEmpty().
Referenced by initCinfo(), and MarkovRateTable::lookup1dIndex().
lookupByValue()
double VectorTable::lookupByValue (double x) const
Definition at line 107 of file VectorTable.cpp.
{
    if ( table_.size() == 1 )
        return table_[0];
    if ( x < xMin_ || doubleEq( x, xMin_ ) )
        return table_[0];
    if ( x > xMax_ || doubleEq( x, xMax_ ) )
        return table_.back();
    unsigned int index = static_cast< unsigned int>( ( x - xMin_ ) * invDx_ );
    double frac = ( x - xMin_ - index / invDx_ ) * invDx_;
    return table_[ index ] * ( 1 - frac ) + table_[ index + 1 ] * frac;
}
References doubleEq(), invDx_, table_, xMax_, and xMin_.
Referenced by initCinfo(), and MarkovRateTable::lookup1dValue().
setDiv()
void VectorTable::setDiv (unsigned int xDivs)
Definition at line 186 of file VectorTable.cpp.
{
    xDivs_ = xDivs;
}
References xDivs_.
Referenced by initCinfo(), and MarkovRateTable::setConstantRate().
setMax()
void VectorTable::setMax (double xMax)
Definition at line 206 of file VectorTable.cpp.
{
    xMax_ = xMax;
}
References xMax_.
Referenced by initCinfo(), and MarkovRateTable::setConstantRate().
setMin()
void VectorTable::setMin (double xMin)
Definition at line 196 of file VectorTable.cpp.
{
    xMin_ = xMin;
}
References xMin_.
Referenced by initCinfo(), and MarkovRateTable::setConstantRate().
setTable()
void VectorTable::setTable (vector< double > table)
Definition at line 155 of file VectorTable.cpp.
{
    if ( table.size() > 1 && xMin_ == xMax_ )
    {
        cerr << "VectorTable::setTable : Error : xmin and xmax cannot be the same when there are more than "
            "two entries in the table!\n";
        return;
    }
    if ( table.empty() )
    {
        cerr << "VectorTable::setTable : Error : Cannot set with empty table!\n";
        return;
    }
    table_ = table;
    xDivs_ = table.size() - 1;
    //This is in case the lookup table has only one entry, in which case,
    //the transition rate being considered is assumed to be constant.
    if ( table.size() > 1 )
        invDx_ = xDivs_ / ( xMax_ - xMin_ );
    else
        invDx_ = 0;
}
References invDx_, table_, xDivs_, xMax_, and xMin_.
Referenced by initCinfo(), and MarkovRateTable::setConstantRate().
tableIsEmpty()
bool VectorTable::tableIsEmpty () const
Definition at line 216 of file VectorTable.cpp.
{
    return table_.empty();
}
References table_.
Referenced by lookupByIndex().
Friends And Related Symbol Documentation
operator>>
istream & operator>> (istream & , VectorTable &) friend
Referenced by operator>>().
Member Data Documentation
invDx_
double VectorTable::invDx_ private
Definition at line 53 of file VectorTable.h.
Referenced by getInvDx(), lookupByValue(), operator>>(), setTable(), and VectorTable().
table_
vector< double > VectorTable::table_ private
Definition at line 55 of file VectorTable.h.
Referenced by getTable(), lookupByIndex(), lookupByValue(), operator>>(), setTable(), tableIsEmpty(), and VectorTable().
xDivs_
unsigned int VectorTable::xDivs_ private
Definition at line 50 of file VectorTable.h.
Referenced by getDiv(), operator>>(), setDiv(), setTable(), and VectorTable().
xMax_
double VectorTable::xMax_ private
Definition at line 52 of file VectorTable.h.
Referenced by getMax(), lookupByValue(), operator>>(), setMax(), setTable(), and VectorTable().
xMin_
double VectorTable::xMin_ private
Definition at line 51 of file VectorTable.h.
Referenced by getMin(), lookupByValue(), operator>>(), setMin(), setTable(), and VectorTable().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/biophysics/VectorTable.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/biophysics/VectorTable.cpp