MOOSE - Multiscale Object Oriented Simulation Environment: HSolve Class Reference
HSolve Class Reference
#include <HSolve.h>
Public Member Functions
void addConc (Id id, double conc)
void addGkEk (Id id, double v1, double v2)
Interface to compartments.
void addInject (Id id, double value)
double getCa (Id id) const
Interface to CaConc.
int getCaAdvance () const
double getCaBasal (Id id) const
double getCaCeiling (Id id) const
int getCaDiv () const
double getCaFloor (Id id) const
double getCaMax () const
double getCaMin () const
double getCm (Id id) const
double getDt () const
double getEk (Id id) const
double getEm (Id id) const
double getGk (Id id) const
double getHHChannelGbar (Id id) const
double getIa (Id id) const
double getIk (Id id) const
double getIm (Id id) const
double getInitVm (Id id) const
double getInject (Id id) const
int getInstant (Id id) const
string getPath (const Eref &e) const
double getRa (Id id) const
double getRm (Id id) const
Id getSeed () const
int getVDiv () const
double getVm (Id id) const
double getVMax () const
double getVMin () const
double getX (Id id) const
double getY (Id id) const
double getZ (Id id) const
HSolve ()
void iCa (Id id, double iCa)
void process (const Eref &hsolve, ProcPtr p)
void reinit (const Eref &hsolve, ProcPtr p)
void setCa (Id id, double Ca)
void setCaAdvance (int caAdvance)
void setCaBasal (Id id, double CaBasal)
void setCaCeiling (Id id, double floor)
void setCaDiv (int caDiv)
void setCaFloor (Id id, double floor)
void setCaMax (double caMax)
void setCaMin (double caMin)
void setCm (Id id, double value)
void setDt (double dt)
void setEk (Id id, double value)
void setEm (Id id, double value)
void setGk (Id id, double value)
void setHHChannelGbar (Id id, double value)
void setHHmodulation (Id id, double value)
Assign scale factor for HH channel conductance.
void setInitVm (Id id, double value)
void setInject (Id id, double value)
void setInstant (Id id, int instant)
void setPath (const Eref &e, string path)
void setPowers (Id id, double Xpower, double Ypower, double Zpower)
Interface to channels.
void setRa (Id id, double value)
void setRm (Id id, double value)
void setSeed (Id seed)
void setTauB (Id id, double tau, double B)
void setVDiv (int vDiv)
void setVm (Id id, double value)
void setVMax (double vMax)
void setVMin (double vMin)
void setX (Id id, double value)
void setY (Id id, double value)
void setZ (Id id, double value)
~HSolve ()
Public Member Functions inherited from HSolveActive
HSolveActive ()
void reinit (ProcPtr info)
void setup (Id seed, double dt)
void step (ProcPtr info)
Equivalent to process.
Public Member Functions inherited from HSolvePassive
void setup (Id seed, double dt)
void solve ()
Public Member Functions inherited from HinesMatrix
double getA (unsigned int row, unsigned int col) const
double getB (unsigned int row) const
unsigned int getSize () const
double getVMid (unsigned int row) const
HinesMatrix ()
void setup (const vector< TreeNodeStruct > &tree, double dt)
Static Public Member Functions
static void deleteIncomingMessages (Element *orig, const string finfo)
static const std::set< string > & handledClasses ()
static const Cinfo * initCinfo ()
Interface to external channels.
Private Member Functions
unsigned int localIndex (Id id) const
void mapIds ()
void mapIds (vector< Id > id)
void setup (Eref hsolve)
void unzombify () const
void zombify (Eref hsolve) const
Static Private Member Functions
static vector< Id > children (Id obj)
static Id deepSearchForCompartment (Id base)
Private Attributes
double dt_
map< Id, unsigned int > localIndex_
string path_
Id seed_
high_resolution_clock::time_point t0_
high_resolution_clock::time_point t1_
double totalTime_ = 0.0
Additional Inherited Members
Protected Types inherited from HinesMatrix
typedef vector< double >::iterator vdIterator
Protected Member Functions inherited from HSolvePassive
void backwardSubstitute ()
void forwardEliminate ()
void updateMatrix ()
Protected Attributes inherited from HSolveActive
vector< double > ca_
Ca conc in each pool.
vector< double > caActivation_
calcium pool
int caAdvance_
vector< CaConcStruct > caConc_
Ca pool info.
vector< Id > caConcId_
calcium from difshells
vector< unsigned int > caCount_
each compartment
vector< int > caDependIndex_
depdt channel depend upon?
int caDiv_
double caMax_
double caMin_
vector< LookupRow * > caRow_
vector< LookupRow > caRowCompt_
LookupTable caTable_
vector< double * > caTarget_
vector< unsigned int > chan2compt_
vector< unsigned int > chan2state_
a state index
vector< ChannelStruct > channel_
to compartment: chan2compt
vector< int > channelCount_
compartment
vector< Id > channelId_
Used for localIndex-ing.
vector< LookupColumn > column_
to lookup for this species
vector< CurrentStruct > current_
Channel current.
vector< currentVecIter > currentBoundary_
vector< double > externalCalcium_
vector< double > externalCurrent_
vector< Id > gateId_
Used for localIndex-ing.
vector< bool > gCaDepend_
depend on Ca conc?
vector< unsigned int > outCa_
vector< unsigned int > outIk_
vector< unsigned int > outVm_
vector< double > prevExtCurr_
Last tick's externalCurrent.
vector< SpikeGenStruct > spikegen_
vector< double > state_
Fraction of gates open.
vector< SynChanStruct > synchan_
int vDiv_
double vMax_
double vMin_
LookupTable vTable_
Protected Attributes inherited from HSolvePassive
vector< CompartmentStruct > compartment_
vector< Id > compartmentId_
map< unsigned int, InjectStruct > inject_
vector< TreeNodeStruct > tree_
vector< double > V_
Protected Attributes inherited from HinesMatrix
vector< vdIterator > backOperand_
double dt_
vector< double > HJ_
vector< double > HJCopy_
vector< double > HS_
vector< JunctionStruct > junction_
unsigned int nCompt_
vector< vdIterator > operand_
int stage_
reached. Used in getA.
vector< double > VMid_
middle of a time step.
Detailed Description
HSolve adapts the integrator HSolveActive into a MOOSE class.
Definition at line 20 of file HSolve.h.
Constructor & Destructor Documentation
HSolve()
HSolve::HSolve ()
Definition at line 197 of file HSolve.cpp.
    : dt_( 50e-6 )
{
}
References dt_.
~HSolve()
HSolve::~HSolve ()
Definition at line 202 of file HSolve.cpp.
{
    unzombify();
#if 0
    char* p = getenv( "MOOSE_SHOW_SOLVER_PERF" );
    if( p != NULL )
    {
        cout << "Info: HSolve took " << totalTime_ << " seconds and took " << numSteps_
             << " steps." << endl;
    }
#endif
}
References unzombify().
Member Function Documentation
addConc()
void HSolve::addConc (Id id, double conc)
Definition at line 254 of file HSolveInterface.cpp.
{
    unsigned int index = localIndex( id );
    assert(  index < externalCalcium_.size() );
    externalCalcium_[ index ] = conc;
}
References HSolveActive::externalCalcium_, and localIndex().
Referenced by ZombieHHChannel::vHandleConc().
addGkEk()
void HSolve::addGkEk (Id id, double v1, double v2)
Interface to compartments.
Definition at line 246 of file HSolveInterface.cpp.
{
    unsigned int index = localIndex( id );
    assert( 2 * index + 1 < externalCurrent_.size() );
    externalCurrent_[ 2 * index ] += Gk;
    externalCurrent_[ 2 * index + 1 ] += Gk * Ek;
}
References HSolveActive::externalCurrent_, and localIndex().
Referenced by ZombieCompartment::vHandleChannel().
addInject()
void HSolve::addInject (Id id, double value)
Definition at line 213 of file HSolveInterface.cpp.
{
    unsigned int index = localIndex( id );
    // Not assert( index < inject_.size() ), because inject_ is a map.
    assert( index < nCompt_ );
    inject_[ index ].injectVarying += value;
}
References HSolvePassive::inject_, InjectStruct::injectVarying, localIndex(), and HinesMatrix::nCompt_.
Referenced by ZombieCompartment::vInjectMsg().
children()
vector< Id > HSolve::children (Id obj) static private
Definition at line 398 of file HSolve.cpp.
{
    //~ return Field< vector< Id > >::get( obj, "children" );
    //~ return Field< vector< Id > >::fastGet( obj.eref(), "children" );
    //~ return localGet< Neutral, vector< Id > >( obj.eref(), "children" );
    vector< Id > c;
    Neutral::children( obj.eref(), c );
    return c;
}
References Neutral::children(), and Id::eref().
Referenced by deepSearchForCompartment().
deepSearchForCompartment()
Id HSolve::deepSearchForCompartment (Id base) static private
This function performs a depth-first search (for a compartment) in the tree with its root at 'base'. Returns (Id of) a compartment if found, else a blank Id.
Definition at line 346 of file HSolve.cpp.
{
    /*
     * 'cstack' is a stack-of-stacks used to perform the depth-first search.
     *     The 0th entry in 'cstack' is a stack containing simply the base.
     *     The i-th entry in 'cstack' contains children of the node at the top
     *         of the stack at position ( i - 1 ).
     *     Hence, at any time, the top of the i-th stack is the i-th node on
     *     the ancestral path from the 'base' node to the 'current' node
     *     (more below) which is being examined. Also, the remaining nodes in
     *     the i-th stack are the siblings of this ancestor.
     *
     * 'current' is the node at the top of the top of 'cstack'. If this node is
     *     a Compartment, then the search is completed, returning 'current'.
     *     Otherwise, the children of 'current' are pushed onto 'cstack' for a
     *     deeper search. If the deeper search yields nothing, then this
     *     'current' node is discarded. When an entire stack of siblings is
     *     exhausted in this way, then this empty stack is discarded, and
     *     the search moves 1 level up.
     *
     * 'result' is a blank Id (moose root element) if the search failed.
     *     Otherwise, it is a compartment that was found under 'base'.
     */
    vector< vector< Id > > cstack( 1, vector< Id >( 1, base ) );
    Id current;
    Id result;
    while ( !cstack.empty() )
        if ( cstack.back().empty() )
        {
            cstack.pop_back();
            if ( !cstack.empty() )
                cstack.back().pop_back();
        }
        else
        {
            current = cstack.back().back();
            // if ( current()->cinfo() == moose::Compartment::initCinfo() )
            // Compartment is base class for SymCompartment.
            if ( current.element()->cinfo()->isA( "Compartment" ) )
            {
                result = current;
                break;
            }
            cstack.push_back( children( current ) );
        }
    return result;
}
References children(), Element::cinfo(), Id::element(), and Cinfo::isA().
Referenced by setPath().
deleteIncomingMessages()
void HSolve::deleteIncomingMessages (Element * orig, const string finfo) static
Delete messages coming into this particular element if its class that is handled by HSolve
Utility function to delete incoming messages on orig. To be used in zombifying elements.
Definition at line 521 of file HSolve.cpp.
{
    const DestFinfo * concenDest = dynamic_cast<const DestFinfo*>(orig->cinfo()->findFinfo(finfo));
    assert(concenDest);
    ObjId mid = orig->findCaller(concenDest->getFid());
    while (! mid.bad())
    {
        const Msg * msg = Msg::getMsg(mid);
        assert(msg);
        ObjId other = msg->findOtherEnd(orig->id());
        Element * otherEl = other.id.element();
        if (otherEl &&  HSolve::handledClasses().find(otherEl->cinfo()->name()) != HSolve::handledClasses().end())
        {
            Msg::deleteMsg(mid);
        }
        else
        {
            break; // Have to do this otherwise it is an infinite loop
        }
        mid = orig->findCaller(concenDest->getFid());
    }
}
References ObjId::bad(), Element::cinfo(), Msg::deleteMsg(), Id::element(), Element::findCaller(), Cinfo::findFinfo(), Msg::findOtherEnd(), DestFinfo::getFid(), Msg::getMsg(), handledClasses(), Element::id(), ObjId::id, and Cinfo::name().
getCa()
double HSolve::getCa (Id id) const
Interface to CaConc.
Definition at line 453 of file HSolveInterface.cpp.
{
    unsigned int index = localIndex( id );
    assert( index < caConc_.size() );
    return ca_[ index ];
}
References HSolveActive::ca_, HSolveActive::caConc_, and localIndex().
Referenced by ZombieCaConc::vGetCa().
getCaAdvance()
int HSolve::getCaAdvance () const
Definition at line 436 of file HSolve.cpp.
{
    return caAdvance_;
}
References HSolveActive::caAdvance_.
Referenced by initCinfo().
getCaBasal()
double HSolve::getCaBasal (Id id) const
Definition at line 482 of file HSolveInterface.cpp.
{
    unsigned int index = localIndex( id );
    assert( index < caConc_.size() );
    return caConc_[ index ].CaBasal_;
}
References CaConcStruct::CaBasal_, HSolveActive::caConc_, and localIndex().
Referenced by ZombieCaConc::vGetCaBasal().
getCaCeiling()
double HSolve::getCaCeiling (Id id) const
Definition at line 505 of file HSolveInterface.cpp.
{
    unsigned int index = localIndex( id );
    assert( index < caConc_.size() );
    return caConc_[ index ].ceiling_;
}
References HSolveActive::caConc_, CaConcStruct::ceiling_, and localIndex().
Referenced by ZombieCaConc::vGetCeiling().
getCaDiv()
int HSolve::getCaDiv () const
Definition at line 476 of file HSolve.cpp.
{
    return caDiv_;
}
References HSolveActive::caDiv_.
Referenced by initCinfo().
getCaFloor()
double HSolve::getCaFloor (Id id) const
Definition at line 520 of file HSolveInterface.cpp.
{
    unsigned int index = localIndex( id );
    assert( index < caConc_.size() );
    return caConc_[ index ].floor_;
}
References HSolveActive::caConc_, CaConcStruct::floor_, and localIndex().
Referenced by ZombieCaConc::vGetFloor().
getCaMax()
double HSolve::getCaMax () const
Definition at line 496 of file HSolve.cpp.
{
    return caMax_;
}
References HSolveActive::caMax_.
Referenced by initCinfo().
getCaMin()
double HSolve::getCaMin () const
Definition at line 486 of file HSolve.cpp.
{
    return caMin_;
}
References HSolveActive::caMin_.
Referenced by initCinfo().
getCm()
double HSolve::getCm (Id id) const
Definition at line 81 of file HSolveInterface.cpp.
{
    unsigned int index = localIndex( id );
    assert( index < tree_.size() );
    return tree_[ index ].Cm;
}
References TreeNodeStruct::Cm, localIndex(), and HSolvePassive::tree_.
Referenced by ZombieCompartment::vGetCm().
getDt()
double HSolve::getDt () const
Definition at line 420 of file HSolve.cpp.
{
    return dt_;
}
References dt_.
Referenced by initCinfo().
getEk()
double HSolve::getEk (Id id) const
Definition at line 302 of file HSolveInterface.cpp.
{
    unsigned int index = localIndex( id );
    assert( index < current_.size() );
    return current_[ index ].Ek;
}
References HSolveActive::current_, CurrentStruct::Ek, and localIndex().
Referenced by ZombieHHChannel::vGetEk().
getEm()
double HSolve::getEm (Id id) const
Definition at line 98 of file HSolveInterface.cpp.
{
    unsigned int index = localIndex( id );
    assert( index < tree_.size() );
    return tree_[ index ].Em;
}
References TreeNodeStruct::Em, localIndex(), and HSolvePassive::tree_.
Referenced by ZombieCompartment::vGetEm().
getGk()
double HSolve::getGk (Id id) const
Definition at line 316 of file HSolveInterface.cpp.
{
    unsigned int index = localIndex( id );
    assert( index < current_.size() );
    return current_[ index ].Gk;
}
References HSolveActive::current_, CurrentStruct::Gk, and localIndex().
Referenced by ZombieHHChannel::vGetGk().
getHHChannelGbar()
double HSolve::getHHChannelGbar (Id id) const
Definition at line 287 of file HSolveInterface.cpp.
{
    unsigned int index = localIndex( id );
    assert( index < channel_.size() );
    return channel_[ index ].Gbar_;
}
References HSolveActive::channel_, ChannelStruct::Gbar_, and localIndex().
Referenced by ZombieHHChannel::vGetGbar().
getIa()
double HSolve::getIa (Id id) const
Definition at line 185 of file HSolveInterface.cpp.
{
    return 0;
}
getIk()
double HSolve::getIk (Id id) const
Definition at line 330 of file HSolveInterface.cpp.
{
    unsigned int index = localIndex( id );
    assert( index < current_.size() );
    unsigned int comptIndex = chan2compt_[ index ];
    assert( comptIndex < V_.size() );
    return ( current_[ index ].Ek - V_[ comptIndex ] ) * current_[ index ].Gk;
}
References HSolveActive::chan2compt_, HSolveActive::current_, CurrentStruct::Ek, CurrentStruct::Gk, localIndex(), and HSolvePassive::V_.
Referenced by ZombieHHChannel::vGetIk().
getIm()
double HSolve::getIm (Id id) const
Definition at line 161 of file HSolveInterface.cpp.
{
    unsigned int index = localIndex( id );
    assert( index < nCompt_ );
    double Im =
        compartment_[ index ].EmByRm - V_[ index ] / tree_[ index ].Rm;
    vector< CurrentStruct >::const_iterator icurrent;
    if ( index == 0 )
        icurrent = current_.begin();
    else
        icurrent = currentBoundary_[ index - 1 ];
    for ( ; icurrent < currentBoundary_[ index ]; ++icurrent )
        Im += ( icurrent->Ek - V_[ index ] ) * icurrent->Gk;
    assert( 2 * index + 1 < externalCurrent_.size() );
    Im += prevExtCurr_[2*index+1] - prevExtCurr_[2*index]*V_[index];
    return Im;
}
References HSolvePassive::compartment_, HSolveActive::current_, HSolveActive::currentBoundary_, CurrentStruct::Ek, CompartmentStruct::EmByRm, HSolveActive::externalCurrent_, CurrentStruct::Gk, localIndex(), HinesMatrix::nCompt_, HSolveActive::prevExtCurr_, TreeNodeStruct::Rm, HSolvePassive::tree_, and HSolvePassive::V_.
Referenced by ZombieCompartment::vGetIm().
getInitVm()
double HSolve::getInitVm (Id id) const
Definition at line 146 of file HSolveInterface.cpp.
{
    unsigned int index = localIndex( id );
    assert( index < tree_.size() );
    return tree_[ index ].initVm;
}
References TreeNodeStruct::initVm, localIndex(), and HSolvePassive::tree_.
Referenced by ZombieCompartment::vGetInitVm().
getInject()
double HSolve::getInject (Id id) const
Definition at line 190 of file HSolveInterface.cpp.
{
    unsigned int index = localIndex( id );
    // Not assert( index < inject_.size() ), because inject_ is a map.
    assert( index < nCompt_ );
    map< unsigned int, InjectStruct >::const_iterator i;
    i = inject_.find( index );
    if ( i != inject_.end() )
        return i->second.injectBasal;
    return 0.0;
}
References HSolvePassive::inject_, InjectStruct::injectBasal, localIndex(), and HinesMatrix::nCompt_.
Referenced by ZombieCompartment::vGetInject().
getInstant()
int HSolve::getInstant (Id id) const
Definition at line 273 of file HSolveInterface.cpp.
{
    unsigned int index = localIndex( id );
    assert( index < channel_.size() );
    return channel_[ index ].instant_;
}
References HSolveActive::channel_, ChannelStruct::instant_, and localIndex().
Referenced by ZombieHHChannel::vGetInstant().
getPath()
string HSolve::getPath (const Eref & e) const
Path to the compartments
Definition at line 336 of file HSolve.cpp.
{
    return path_;
}
References path_.
Referenced by initCinfo().
getRa()
double HSolve::getRa (Id id) const
Definition at line 132 of file HSolveInterface.cpp.
{
    unsigned int index = localIndex( id );
    assert( index < tree_.size() );
    return tree_[ index ].Ra;
}
References localIndex(), TreeNodeStruct::Ra, and HSolvePassive::tree_.
Referenced by ZombieCompartment::vGetRa().
getRm()
double HSolve::getRm (Id id) const
Definition at line 115 of file HSolveInterface.cpp.
{
    unsigned int index = localIndex( id );
    assert( index < tree_.size() );
    return tree_[ index ].Rm;
}
References localIndex(), TreeNodeStruct::Rm, and HSolvePassive::tree_.
Referenced by ZombieCompartment::vGetRm().
getSeed()
Id HSolve::getSeed () const
For searching for compartments: seed is the starting compt.
Definition at line 310 of file HSolve.cpp.
{
    return seed_;
}
References seed_.
Referenced by initCinfo().
getVDiv()
int HSolve::getVDiv () const
Definition at line 446 of file HSolve.cpp.
{
    return vDiv_;
}
References HSolveActive::vDiv_.
Referenced by initCinfo().
getVm()
double HSolve::getVm (Id id) const
Definition at line 66 of file HSolveInterface.cpp.
{
    assert(this);
    unsigned int index = localIndex( id );
    assert( index < V_.size() );
    return V_[ index ];
}
References localIndex(), and HSolvePassive::V_.
Referenced by ZombieCompartment::vGetVm().
getVMax()
double HSolve::getVMax () const
Definition at line 466 of file HSolve.cpp.
{
    return vMax_;
}
References HSolveActive::vMax_.
Referenced by initCinfo().
getVMin()
double HSolve::getVMin () const
Definition at line 456 of file HSolve.cpp.
{
    return vMin_;
}
References HSolveActive::vMin_.
Referenced by initCinfo().
getX()
double HSolve::getX (Id id) const
Definition at line 341 of file HSolveInterface.cpp.
{
    unsigned int index = localIndex( id );
    assert( index < channel_.size() );
    if ( channel_[ index ].Xpower_ == 0.0 )
        return 0.0;
    unsigned int stateIndex = chan2state_[ index ];
    assert( stateIndex < state_.size() );
    return state_[ stateIndex ];
}
References HSolveActive::chan2state_, HSolveActive::channel_, localIndex(), HSolveActive::state_, and ChannelStruct::Xpower_.
Referenced by ZombieHHChannel::vGetX().
getY()
double HSolve::getY (Id id) const
Definition at line 369 of file HSolveInterface.cpp.
{
    unsigned int index = localIndex( id );
    assert( index < channel_.size() );
    if ( channel_[ index ].Ypower_ == 0.0 )
        return 0.0;
    unsigned int stateIndex = chan2state_[ index ];
    if ( channel_[ index ].Xpower_ > 0.0 )
        ++stateIndex;
    assert( stateIndex < state_.size() );
    return state_[ stateIndex ];
}
References HSolveActive::chan2state_, HSolveActive::channel_, localIndex(), HSolveActive::state_, ChannelStruct::Xpower_, and ChannelStruct::Ypower_.
Referenced by ZombieHHChannel::vGetY().
getZ()
double HSolve::getZ (Id id) const
Definition at line 405 of file HSolveInterface.cpp.
{
    unsigned int index = localIndex( id );
    assert( index < channel_.size() );
    if ( channel_[ index ].Zpower_ == 0.0 )
        return 0.0;
    unsigned int stateIndex = chan2state_[ index ];
    if ( channel_[ index ].Xpower_ > 0.0 )
        ++stateIndex;
    if ( channel_[ index ].Ypower_ > 0.0 )
        ++stateIndex;
    assert( stateIndex < state_.size() );
    return state_[ stateIndex ];
}
References HSolveActive::chan2state_, HSolveActive::channel_, localIndex(), HSolveActive::state_, ChannelStruct::Xpower_, ChannelStruct::Ypower_, and ChannelStruct::Zpower_.
Referenced by ZombieHHChannel::vGetZ().
handledClasses()
const set< string > & HSolve::handledClasses () static
Returns the set of classes "handled" by HSolve
Definition at line 501 of file HSolve.cpp.
{
    static set<string> classes;
    if (classes.empty())
    {
        classes.insert("CaConc");
        classes.insert("ZombieCaConc");
        classes.insert("HHChannel");
        classes.insert("ZombieHHChannel");
        classes.insert("Compartment");
        classes.insert("SymCompartment");
        classes.insert("ZombieCompartment");
    }
    return classes;
}
Referenced by deleteIncomingMessages().
iCa()
void HSolve::iCa (Id id, double iCa)
Definition at line 469 of file HSolveInterface.cpp.
{
    unsigned int index = localIndex( id );
    assert( index < caConc_.size() );
    caActivation_[index] += iCa;
    /*
    ca_[ index ] = Ca;
    caConc_[ index ].setCa( Ca );
    */
}
References HSolveActive::caActivation_, HSolveActive::caConc_, and localIndex().
Referenced by ZombieCaConc::vCurrent().
initCinfo()
const Cinfo * HSolve::initCinfo () static
Interface to external channels.
Definition at line 37 of file HSolve.cpp.
{
    static DestFinfo process(
        "process",
        "Handles 'process' call: Solver advances by one time-step.",
        new ProcOpFunc< HSolve >( &HSolve::process )
    );
    static DestFinfo reinit(
        "reinit",
        "Handles 'reinit' call: Solver reads in model.",
        new ProcOpFunc< HSolve >( &HSolve::reinit )
    );
    static Finfo* processShared[] =
    {
        &process,
        &reinit
    };
    static SharedFinfo proc(
        "proc",
        "Handles 'reinit' and 'process' calls from a clock.",
        processShared,
        sizeof( processShared ) / sizeof( Finfo* )
    );
    static ValueFinfo< HSolve, Id > seed(
        "seed",
        "Use this field to specify path to a 'seed' compartment, that is, "
        "any compartment within a neuron. The HSolve object uses this seed as "
        "a handle to discover the rest of the neuronal model, which means all "
        "the remaining compartments, channels, synapses, etc.",
        &HSolve::setSeed,
        &HSolve::getSeed
    );
    static ElementValueFinfo< HSolve, string > target(
        "target",
        "Specifies the path to a compartmental model to be taken over. "
        "This can be the path to any container object that has the model "
        "under it (found by performing a deep search). Alternatively, this "
        "can also be the path to any compartment within the neuron. This "
        "compartment will be used as a handle to discover the rest of the "
        "model, which means all the remaining compartments, channels, "
        "synapses, etc.",
        &HSolve::setPath,
        &HSolve::getPath
    );
    static ValueFinfo< HSolve, double > dt(
        "dt",
        "The time-step for this solver.",
        &HSolve::setDt,
        &HSolve::getDt
    );
    static ValueFinfo< HSolve, int > caAdvance(
        "caAdvance",
        "This flag determines how current flowing into a calcium pool "
        "is computed. A value of 0 means that the membrane potential at the "
        "beginning of the time-step is used for the calculation. This is how "
        "GENESIS does its computations. A value of 1 means the membrane "
        "potential at the middle of the time-step is used. This is the "
        "correct way of integration, and is the default way.",
        &HSolve::setCaAdvance,
        &HSolve::getCaAdvance
    );
    static ValueFinfo< HSolve, int > vDiv(
        "vDiv",
        "Specifies number of divisions for lookup tables of voltage-sensitive "
        "channels.",
        &HSolve::setVDiv,
        &HSolve::getVDiv
    );
    static ValueFinfo< HSolve, double > vMin(
        "vMin",
        "Specifies the lower bound for lookup tables of voltage-sensitive "
        "channels. Default is to automatically decide based on the tables of "
        "the channels that the solver reads in.",
        &HSolve::setVMin,
        &HSolve::getVMin
    );
    static ValueFinfo< HSolve, double > vMax(
        "vMax",
        "Specifies the upper bound for lookup tables of voltage-sensitive "
        "channels. Default is to automatically decide based on the tables of "
        "the channels that the solver reads in.",
        &HSolve::setVMax,
        &HSolve::getVMax
    );
    static ValueFinfo< HSolve, int > caDiv(
        "caDiv",
        "Specifies number of divisions for lookup tables of calcium-sensitive "
        "channels.",
        &HSolve::setCaDiv,
        &HSolve::getCaDiv
    );
    static ValueFinfo< HSolve, double > caMin(
        "caMin",
        "Specifies the lower bound for lookup tables of calcium-sensitive "
        "channels. Default is to automatically decide based on the tables of "
        "the channels that the solver reads in.",
        &HSolve::setCaMin,
        &HSolve::getCaMin
    );
    static ValueFinfo< HSolve, double > caMax(
        "caMax",
        "Specifies the upper bound for lookup tables of calcium-sensitive "
        "channels. Default is to automatically decide based on the tables of "
        "the channels that the solver reads in.",
        &HSolve::setCaMax,
        &HSolve::getCaMax
    );
    static Finfo* hsolveFinfos[] =
    {
        &seed,              // Value
        &target,              // Value
        &dt,                // Value
        &caAdvance,         // Value
        &vDiv,              // Value
        &vMin,              // Value
        &vMax,              // Value
        &caDiv,             // Value
        &caMin,             // Value
        &caMax,             // Value
        &proc,              // Shared
    };
    static string doc[] =
    {
        "Name",             "HSolve",
        "Author",           "Niraj Dudani, 2007, NCBS",
        "Description",      "HSolve: Hines solver, for solving "
        "branching neuron models.",
    };
    static Dinfo< HSolve > dinfo;
    static Cinfo hsolveCinfo(
        "HSolve",
        Neutral::initCinfo(),
        hsolveFinfos,
        sizeof( hsolveFinfos ) / sizeof( Finfo* ),
        &dinfo,
        doc,
        sizeof(doc)/sizeof(string)
    );
    return &hsolveCinfo;
}
References Cinfo::Cinfo(), DestFinfo::DestFinfo(), ElementValueFinfo< T, F >::ElementValueFinfo(), getCaAdvance(), getCaDiv(), getCaMax(), getCaMin(), getDt(), getPath(), getSeed(), getVDiv(), getVMax(), getVMin(), Neutral::initCinfo(), process(), ProcOpFunc< T >::ProcOpFunc(), reinit(), setCaAdvance(), setCaDiv(), setCaMax(), setCaMin(), setDt(), setPath(), setSeed(), setVDiv(), setVMax(), setVMin(), SharedFinfo::SharedFinfo(), and ValueFinfo< T, F >::ValueFinfo().
localIndex()
unsigned int HSolve::localIndex (Id id) const private
Definition at line 23 of file HSolveInterface.cpp.
{
    /* can easily replace with an array lookup with some holes, as
     * done in the Stoich class. */
    map< Id, unsigned int >::const_iterator i;
    i = localIndex_.find( id );
    if ( i != localIndex_.end() )
        return i->second;
    assert( 0 );
    return ~0;
}
References localIndex_.
Referenced by addConc(), addGkEk(), addInject(), getCa(), getCaBasal(), getCaCeiling(), getCaFloor(), getCm(), getEk(), getEm(), getGk(), getHHChannelGbar(), getIk(), getIm(), getInitVm(), getInject(), getInstant(), getRa(), getRm(), getVm(), getX(), getY(), getZ(), iCa(), setCa(), setCaBasal(), setCaCeiling(), setCaFloor(), setCm(), setEk(), setEm(), setGk(), setHHChannelGbar(), setHHmodulation(), setInitVm(), setInject(), setInstant(), setPowers(), setRa(), setRm(), setTauB(), setVm(), setX(), setY(), and setZ().
mapIds() [1/2]
void HSolve::mapIds () private
Definition at line 49 of file HSolveInterface.cpp.
{
    mapIds( compartmentId_ );
    mapIds( caConcId_ );
    mapIds( channelId_ );
    //~ mapIds( gateId_ );
    // Doesn't seem to be needed. Perhaps even the externalChannelId_ vector
    // is not needed.
    //~ for ( unsigned int ic = 0; ic < compartmentId_.size(); ++ic )
    //~ mapIds( externalChannelId_[ ic ] );
}
References HSolveActive::caConcId_, HSolveActive::channelId_, HSolvePassive::compartmentId_, and mapIds().
Referenced by setup().
mapIds() [2/2]
void HSolve::mapIds (vector< Id > id) private
Definition at line 38 of file HSolveInterface.cpp.
{
    for ( unsigned int i = 0; i < id.size(); ++i )
    {
        // We don't expect these Id's to have been registered already.
        assert( localIndex_.find( id[ i ] ) == localIndex_.end() );
        localIndex_[ id[ i ] ] = i;
    }
}
References localIndex_.
Referenced by mapIds().
process()
void HSolve::process (const Eref & hsolve, ProcPtr p)
Definition at line 221 of file HSolve.cpp.
{
    t0_ = high_resolution_clock::now();
    this->HSolveActive::step( p );
    t1_ = high_resolution_clock::now();
    addSolverProf( "HSolve", duration_cast<duration<double>>(t1_ - t0_).count(), 1 );
}
References moose::addSolverProf(), HSolveActive::step(), t0_, and t1_.
Referenced by initCinfo().
reinit()
void HSolve::reinit (const Eref & hsolve, ProcPtr p)
Definition at line 229 of file HSolve.cpp.
{
    dt_ = p->dt;
    this->HSolveActive::reinit( p );
}
References ProcInfo::dt, dt_, and HSolveActive::reinit().
Referenced by initCinfo().
setCa()
void HSolve::setCa (Id id, double Ca)
Definition at line 460 of file HSolveInterface.cpp.
{
    unsigned int index = localIndex( id );
    assert( index < caConc_.size() );
    ca_[ index ] = Ca;
    caConc_[ index ].setCa( Ca );
}
References HSolveActive::ca_, HSolveActive::caConc_, localIndex(), and CaConcStruct::setCa().
Referenced by ZombieCaConc::vSetCa(), and ZombieCaConc::vSetCaBasal().
setCaAdvance()
void HSolve::setCaAdvance (int caAdvance)
Definition at line 425 of file HSolve.cpp.
{
    if ( caAdvance != 0 && caAdvance != 1 )
    {
        cerr << "Error: HSolve: caAdvance should be either 0 or 1.\n";
        return;
    }
    caAdvance_ = caAdvance;
}
References HSolveActive::caAdvance_.
Referenced by initCinfo().
setCaBasal()
void HSolve::setCaBasal (Id id, double CaBasal)
Definition at line 489 of file HSolveInterface.cpp.
{
    unsigned int index = localIndex( id );
    assert( index < caConc_.size() );
    caConc_[ index ].setCaBasal( CaBasal );
}
References HSolveActive::caConc_, localIndex(), and CaConcStruct::setCaBasal().
setCaCeiling()
void HSolve::setCaCeiling (Id id, double floor)
Definition at line 512 of file HSolveInterface.cpp.
{
    unsigned int index = localIndex( id );
    assert( index < caConc_.size() );
    caConc_[ index ].ceiling_ = ceiling;
}
References HSolveActive::caConc_, CaConcStruct::ceiling_, and localIndex().
Referenced by ZombieCaConc::vSetCeiling().
setCaDiv()
void HSolve::setCaDiv (int caDiv)
Definition at line 471 of file HSolve.cpp.
{
    caDiv_ = caDiv;
}
References HSolveActive::caDiv_.
Referenced by initCinfo().
setCaFloor()
void HSolve::setCaFloor (Id id, double floor)
Definition at line 527 of file HSolveInterface.cpp.
{
    unsigned int index = localIndex( id );
    assert( index < caConc_.size() );
    caConc_[ index ].floor_ = floor;
}
References HSolveActive::caConc_, CaConcStruct::floor_, and localIndex().
Referenced by ZombieCaConc::vSetFloor().
setCaMax()
void HSolve::setCaMax (double caMax)
Definition at line 491 of file HSolve.cpp.
{
    caMax_ = caMax;
}
References HSolveActive::caMax_.
Referenced by initCinfo().
setCaMin()
void HSolve::setCaMin (double caMin)
Definition at line 481 of file HSolve.cpp.
{
    caMin_ = caMin;
}
References HSolveActive::caMin_.
Referenced by initCinfo().
setCm()
void HSolve::setCm (Id id, double value)
Definition at line 88 of file HSolveInterface.cpp.
{
    unsigned int index = localIndex( id );
    assert( index < tree_.size() );
    tree_[ index ].Cm = value;
    // Also update data structures used for calculations.
    assert( tree_.size() == compartment_.size() );
    compartment_[index].CmByDt = 2.0 * value / dt_;
}
References TreeNodeStruct::Cm, CompartmentStruct::CmByDt, HSolvePassive::compartment_, dt_, localIndex(), and HSolvePassive::tree_.
Referenced by ZombieCompartment::vSetCm().
setDt()
void HSolve::setDt (double dt)
Definition at line 409 of file HSolve.cpp.
{
    if ( dt < 0.0 )
    {
        cerr << "Error: HSolve: 'dt' must be positive.\n";
        return;
    }
    dt_ = dt;
}
References dt_.
Referenced by initCinfo().
setEk()
void HSolve::setEk (Id id, double value)
Definition at line 309 of file HSolveInterface.cpp.
{
    unsigned int index = localIndex( id );
    assert( index < current_.size() );
    current_[ index ].Ek = value;
}
References HSolveActive::current_, CurrentStruct::Ek, and localIndex().
Referenced by ZombieHHChannel::vSetEk().
setEm()
void HSolve::setEm (Id id, double value)
Definition at line 105 of file HSolveInterface.cpp.
{
    unsigned int index = localIndex( id );
    assert( index < tree_.size() );
    tree_[ index ].Em = value;
    // Also update data structures used for calculations.
    assert( tree_.size() == compartment_.size() );
    compartment_[index].EmByRm = value / tree_[index].Rm;
}
References HSolvePassive::compartment_, TreeNodeStruct::Em, CompartmentStruct::EmByRm, localIndex(), TreeNodeStruct::Rm, and HSolvePassive::tree_.
Referenced by ZombieCompartment::vSetEm().
setGk()
void HSolve::setGk (Id id, double value)
Definition at line 323 of file HSolveInterface.cpp.
{
    unsigned int index = localIndex( id );
    assert( index < current_.size() );
    current_[ index ].Gk = value;
}
References HSolveActive::current_, CurrentStruct::Gk, and localIndex().
Referenced by ZombieHHChannel::vSetGk().
setHHChannelGbar()
void HSolve::setHHChannelGbar (Id id, double value)
Definition at line 294 of file HSolveInterface.cpp.
{
    unsigned int index = localIndex( id );
    assert( index < channel_.size() );
    channel_[ index ].Gbar_ = value;
}
References HSolveActive::channel_, ChannelStruct::Gbar_, and localIndex().
Referenced by ZombieHHChannel::vSetGbar().
setHHmodulation()
void HSolve::setHHmodulation (Id id, double value)
Assign scale factor for HH channel conductance.
Definition at line 445 of file HSolveInterface.cpp.
{
    unsigned int index = localIndex( id );
    assert( index < channel_.size() );
    if ( value > 0.0 )
            channel_[index].modulation_ = value;
}
References HSolveActive::channel_, localIndex(), and ChannelStruct::modulation_.
Referenced by ZombieHHChannel::vSetModulation().
setInitVm()
void HSolve::setInitVm (Id id, double value)
Definition at line 153 of file HSolveInterface.cpp.
{
    unsigned int index = localIndex( id );
    assert( index < tree_.size() );
    tree_[ index ].initVm = value;
}
References TreeNodeStruct::initVm, localIndex(), and HSolvePassive::tree_.
Referenced by ZombieCompartment::vSetInitVm().
setInject()
void HSolve::setInject (Id id, double value)
Definition at line 205 of file HSolveInterface.cpp.
{
    unsigned int index = localIndex( id );
    // Not assert( index < inject_.size() ), because inject_ is a map.
    assert( index < nCompt_ );
    inject_[ index ].injectBasal = value;
}
References HSolvePassive::inject_, InjectStruct::injectBasal, localIndex(), and HinesMatrix::nCompt_.
Referenced by ZombieCompartment::vSetInject().
setInstant()
void HSolve::setInstant (Id id, int instant)
Definition at line 280 of file HSolveInterface.cpp.
{
    unsigned int index = localIndex( id );
    assert( index < channel_.size() );
    channel_[ index ].instant_ = instant;
}
References HSolveActive::channel_, ChannelStruct::instant_, and localIndex().
Referenced by ZombieHHChannel::vSetInstant().
setPath()
void HSolve::setPath (const Eref & e, string path)
Definition at line 315 of file HSolve.cpp.
{
    if ( dt_ == 0.0 )
    {
        cerr << "Error: HSolve::setPath(): Must set 'dt' first.\n";
        return;
    }
    seed_ = deepSearchForCompartment( Id( path ) );
    if ( seed_ == Id() )
        cerr << "Warning: HSolve::setPath(): No compartments found at or below '"
             << path << "'.\n";
    else
    {
        // cout << "HSolve: Seed compartment found at '" << seed_.path() << "'.\n";
        path_ = path;
        setup( hsolve );
    }
}
References deepSearchForCompartment(), dt_, Id::Id(), Id::Id(), Id::operator==(), path_, seed_, and setup().
Referenced by initCinfo().
setPowers()
void HSolve::setPowers (Id id, double Xpower, double Ypower, double Zpower)
Interface to channels.
Definition at line 262 of file HSolveInterface.cpp.
{
    unsigned int index = localIndex( id );
    assert( index < channel_.size() );
    channel_[ index ].setPowers( Xpower, Ypower, Zpower );
}
References HSolveActive::channel_, localIndex(), and ChannelStruct::setPowers().
Referenced by ZombieHHChannel::vSetXpower(), ZombieHHChannel::vSetYpower(), and ZombieHHChannel::vSetZpower().
setRa()
void HSolve::setRa (Id id, double value)
Definition at line 139 of file HSolveInterface.cpp.
{
    unsigned int index = localIndex( id );
    assert( index < tree_.size() );
    tree_[ index ].Ra = value;
}
References localIndex(), TreeNodeStruct::Ra, and HSolvePassive::tree_.
Referenced by ZombieCompartment::vSetRa().
setRm()
void HSolve::setRm (Id id, double value)
Definition at line 122 of file HSolveInterface.cpp.
{
    unsigned int index = localIndex( id );
    assert( index < tree_.size() );
    tree_[ index ].Rm = value;
    // Also update data structures used for calculations.
    assert( tree_.size() == compartment_.size() );
    compartment_[index].EmByRm = tree_[index].Em / value;
}
References HSolvePassive::compartment_, TreeNodeStruct::Em, CompartmentStruct::EmByRm, localIndex(), TreeNodeStruct::Rm, and HSolvePassive::tree_.
Referenced by ZombieCompartment::vSetRm().
setSeed()
void HSolve::setSeed (Id seed)
Definition at line 299 of file HSolve.cpp.
{
    if ( !seed.element()->cinfo()->isA( "Compartment" ) )
    {
        cerr << "Error: HSolve::setSeed(): Seed object '" << seed.path()
             << "' is not derived from type 'Compartment'." << endl;
        return;
    }
    seed_ = seed;
}
References Element::cinfo(), Id::element(), Cinfo::isA(), Id::path(), and seed_.
Referenced by initCinfo(), and Cell::setupSolver().
setTauB()
void HSolve::setTauB (Id id, double tau, double B)
Definition at line 497 of file HSolveInterface.cpp.
{
    unsigned int index = localIndex( id );
    assert( index < caConc_.size() );
    caConc_[ index ].setTauB( tau, B, dt_ );
}
References HSolveActive::caConc_, dt_, localIndex(), and CaConcStruct::setTauB().
Referenced by ZombieCaConc::vSetB(), and ZombieCaConc::vSetTau().
setup()
void HSolve::setup (Eref hsolve) private
Definition at line 286 of file HSolve.cpp.
{
    // Setup solver.
    this->HSolveActive::setup( seed_, dt_ );
    mapIds();
    zombify( hsolve );
}
References dt_, mapIds(), seed_, HSolveActive::setup(), and zombify().
Referenced by setPath().
setVDiv()
void HSolve::setVDiv (int vDiv)
Definition at line 441 of file HSolve.cpp.
{
    vDiv_ = vDiv;
}
References HSolveActive::vDiv_.
Referenced by initCinfo().
setVm()
void HSolve::setVm (Id id, double value)
Definition at line 74 of file HSolveInterface.cpp.
{
    unsigned int index = localIndex( id );
    assert( index < V_.size() );
    V_[ index ] = value;
}
References localIndex(), and HSolvePassive::V_.
Referenced by ZombieCompartment::vSetVm().
setVMax()
void HSolve::setVMax (double vMax)
Definition at line 461 of file HSolve.cpp.
{
    vMax_ = vMax;
}
References HSolveActive::vMax_.
Referenced by initCinfo().
setVMin()
void HSolve::setVMin (double vMin)
Definition at line 451 of file HSolve.cpp.
{
    vMin_ = vMin;
}
References HSolveActive::vMin_.
Referenced by initCinfo().
setX()
void HSolve::setX (Id id, double value)
Definition at line 355 of file HSolveInterface.cpp.
{
    unsigned int index = localIndex( id );
    assert( index < channel_.size() );
    if ( channel_[ index ].Xpower_ == 0.0 )
        return;
    unsigned int stateIndex = chan2state_[ index ];
    assert( stateIndex < state_.size() );
    state_[ stateIndex ] = value;
}
References HSolveActive::chan2state_, HSolveActive::channel_, localIndex(), HSolveActive::state_, and ChannelStruct::Xpower_.
Referenced by ZombieHHChannel::vSetX().
setY()
void HSolve::setY (Id id, double value)
Definition at line 387 of file HSolveInterface.cpp.
{
    unsigned int index = localIndex( id );
    assert( index < channel_.size() );
    if ( channel_[ index ].Ypower_ == 0.0 )
        return;
    unsigned int stateIndex = chan2state_[ index ];
    if ( channel_[ index ].Xpower_ > 0.0 )
        ++stateIndex;
    assert( stateIndex < state_.size() );
    state_[ stateIndex ] = value;
}
References HSolveActive::chan2state_, HSolveActive::channel_, localIndex(), HSolveActive::state_, ChannelStruct::Xpower_, and ChannelStruct::Ypower_.
Referenced by ZombieHHChannel::vSetY().
setZ()
void HSolve::setZ (Id id, double value)
Definition at line 425 of file HSolveInterface.cpp.
{
    unsigned int index = localIndex( id );
    assert( index < channel_.size() );
    if ( channel_[ index ].Zpower_ == 0.0 )
        return;
    unsigned int stateIndex = chan2state_[ index ];
    if ( channel_[ index ].Xpower_ > 0.0 )
        ++stateIndex;
    if ( channel_[ index ].Ypower_ > 0.0 )
        ++stateIndex;
    assert( stateIndex < state_.size() );
    state_[ stateIndex ] = value;
}
References HSolveActive::chan2state_, HSolveActive::channel_, localIndex(), HSolveActive::state_, ChannelStruct::Xpower_, ChannelStruct::Ypower_, and ChannelStruct::Zpower_.
Referenced by ZombieHHChannel::vSetZ().
unzombify()
void HSolve::unzombify () const private
Definition at line 264 of file HSolve.cpp.
{
    vector< Id >::const_iterator i;
    for ( i = compartmentId_.begin(); i != compartmentId_.end(); ++i )
        if ( i->element() ) {
            CompartmentBase::zombify( i->eref().element(),
                       Compartment::initCinfo(), Id() );
        }
    for ( i = caConcId_.begin(); i != caConcId_.end(); ++i )
        if ( i->element() ) {
            CaConcBase::zombify( i->eref().element(), CaConc::initCinfo(), Id() );
        }
    for ( i = channelId_.begin(); i != channelId_.end(); ++i )
        if ( i->element() ) {
            HHChannelBase::zombify( i->eref().element(),
                        HHChannel::initCinfo(), Id() );
        }
}
References HSolveActive::caConcId_, HSolveActive::channelId_, HSolvePassive::compartmentId_, Eref::element(), Id::element(), Id::eref(), Id::Id(), CaConc::initCinfo(), moose::Compartment::initCinfo(), HHChannel::initCinfo(), CaConcBase::zombify(), moose::CompartmentBase::zombify(), and HHChannelBase::zombify().
Referenced by ~HSolve().
zombify()
void HSolve::zombify (Eref hsolve) const private
Definition at line 235 of file HSolve.cpp.
{
    vector< Id >::const_iterator i;
    vector< ObjId > temp;
    for ( i = compartmentId_.begin(); i != compartmentId_.end(); ++i )
        temp.push_back( ObjId( *i, 0 ) );
    for ( i = compartmentId_.begin(); i != compartmentId_.end(); ++i ) {
        CompartmentBase::zombify( i->eref().element(),
                       ZombieCompartment::initCinfo(), hsolve.id() );
    }
    temp.clear();
    for ( i = caConcId_.begin(); i != caConcId_.end(); ++i )
        temp.push_back( ObjId( *i, 0 ) );
    // Shell::dropClockMsgs( temp, "process" );
    for ( i = caConcId_.begin(); i != caConcId_.end(); ++i ) {
        CaConcBase::zombify( i->eref().element(), ZombieCaConc::initCinfo(), hsolve.id() );
    }
    temp.clear();
    for ( i = channelId_.begin(); i != channelId_.end(); ++i )
        temp.push_back( ObjId( *i, 0 ) );
    for ( i = channelId_.begin(); i != channelId_.end(); ++i ) {
        HHChannelBase::zombify( i->eref().element(),
                        ZombieHHChannel::initCinfo(), hsolve.id() );
    }
}
References HSolveActive::caConcId_, HSolveActive::channelId_, HSolvePassive::compartmentId_, Eref::element(), Id::eref(), Eref::id(), ZombieCaConc::initCinfo(), ZombieCompartment::initCinfo(), ZombieHHChannel::initCinfo(), ObjId::ObjId(), CaConcBase::zombify(), moose::CompartmentBase::zombify(), and HHChannelBase::zombify().
Referenced by setup().
Member Data Documentation
dt_
double HSolve::dt_ private
Definition at line 173 of file HSolve.h.
Referenced by getDt(), HSolve(), reinit(), setCm(), setDt(), setPath(), setTauB(), and setup().
localIndex_
map< Id, unsigned int > HSolve::localIndex_ private
Definition at line 171 of file HSolve.h.
Referenced by localIndex(), and mapIds().
path_
string HSolve::path_ private
Definition at line 174 of file HSolve.h.
Referenced by getPath(), and setPath().
seed_
Id HSolve::seed_ private
Definition at line 175 of file HSolve.h.
Referenced by getSeed(), setPath(), setSeed(), and setup().
t0_
high_resolution_clock::time_point HSolve::t0_ private
Definition at line 178 of file HSolve.h.
Referenced by process().
t1_
high_resolution_clock::time_point HSolve::t1_ private
Definition at line 178 of file HSolve.h.
Referenced by process().
totalTime_
double HSolve::totalTime_ = 0.0 private
Definition at line 177 of file HSolve.h.
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/hsolve/HSolve.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/hsolve/HSolve.cpp
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/hsolve/HSolveInterface.cpp