MOOSE - Multiscale Object Oriented Simulation Environment: NonlinearSystem Class Reference
NonlinearSystem Class Reference
#include <NonlinearSystem.h>
Public Member Functions
int apply ()
bool compute_at (const vector_type &x, vector_type &result)
int compute_jacobians (const vector_type &x, bool compute_inverse=false)
bool find_roots_gnewton (double tolerance, size_t max_iter)
Find roots using Newton-Raphson method.
template<typename T >
void initialize (const T &x)
NonlinearSystem (size_t systemSize)
int system (const vector_type &x, vector_type &f)
string to_string ()
Public Attributes
double dx_
vector_type f_
matrix_type invJ_
bool is_f_positive_
bool is_jacobian_valid_
matrix_type J_
ReacInfo ri
const size_t size_
vector_type slopes_
vector_type x1
vector_type x2
vector_type x_
Detailed Description
Definition at line 89 of file NonlinearSystem.h.
Constructor & Destructor Documentation
NonlinearSystem()
NonlinearSystem::NonlinearSystem (size_t systemSize) inline
Definition at line 94 of file NonlinearSystem.h.
                                         : size_( systemSize )
    {
        f_.resize( size_, 0);
        slopes_.resize( size_, 0);
        x_.resize( size_, 0 );
        J_.resize( size_, size_, 0);
        invJ_.resize( size_, size_, 0);
        x2.resize( size_, 0);
        x1.resize( size_, 0);
        ri.nVec.resize( size_ );
        // Find machine epsilon to decide on dx. Machine eps is typically 2.22045e-16 on 64 bit machines/intel.
        // Square root of this value is a very good value. The values matches with GSL solver nicely.
        // Making this value too small or too big gonna cause error in blas methods especially when
        // computing inverse.
        // Gnu-GSL uses GSL_SQRT_DBL_EPSILON  which is 1.4901161193847656e-08
        // dx_ = 1.4901161193847656e-08;
        dx_ = std::sqrt( numeric_limits<double>::epsilon() );
    }
References dx_, f_, invJ_, J_, size_, slopes_, x1, x2, and x_.
Member Function Documentation
apply()
int NonlinearSystem::apply () inline
Definition at line 122 of file NonlinearSystem.h.
    {
        return system(x_, f_);
    }
References f_, system(), and x_.
Referenced by find_roots_gnewton(), and initialize().
compute_at()
bool NonlinearSystem::compute_at (const vector_type & x, vector_type & result) inline
Definition at line 117 of file NonlinearSystem.h.
    {
        return system(x, result);
    }
References system().
Referenced by compute_jacobians().
compute_jacobians()
int NonlinearSystem::compute_jacobians (const vector_type & x, bool compute_inverse = false) inline
Definition at line 127 of file NonlinearSystem.h.
    {
        for( size_t i = 0; i < size_; i++)
        {
            // This trick I leart by looking at GSL implmentation.
            double dx = dx_ * std::fabs(x[i]);
            if( dx == 0 )
                dx = dx_;
            for( size_t j = 0; j < size_; j++)
            {
                vector_type temp = x;
                temp[j] += dx;
                vector_type res1, res2;
                auto r1 = compute_at(temp, res1);
                auto r2 = compute_at(x, res2);
                if( 0 == r1 && 0 == r2 )
                {
                    J_(i, j) = (res1[i] - res2[i]) / dx;
                    if( std::isnan(J_(i,j)) || std::isinf(J_(i,j)) )
                    {
                        /* Try increasing dx */
                        J_.clear();
                        return -1;
                    }
                }
                else
                {
                    J_.clear();
                    return -1;
                }
            }
        }
        if( compute_inverse )
        {
            try {
                inverse( J_, invJ_ );
            } catch ( exception & e ) {
                J_.clear();
                invJ_.clear();
                return -1;
            }
        }
        return 0;
    }
References compute_at(), dx_, invJ_, J_, and size_.
Referenced by find_roots_gnewton(), and initialize().
find_roots_gnewton()
bool NonlinearSystem::find_roots_gnewton (double tolerance, size_t max_iter) inline
Find roots using Newton-Raphson method.
Parameters
tolerance 1e-7
max_iter Maximum number of iteration allowed , default 100
Returns
If successful, return true. Check the variable x_ at which the system f_ is close to zero (within the tolerance).
Definition at line 260 of file NonlinearSystem.h.
    {
        double norm2OfDiff = 1.0;
        size_t iter = 0;
        if(0 != apply() )
            return false;
        while( ublas::norm_2(f_) > tolerance )
        {
            iter += 1;
            ri.nIter = iter;
            if( 0 != compute_jacobians( x_, true ) )
            {
                J_.clear();
                invJ_.clear();
                return false;
            }
            vector_type correction = ublas::prod( invJ_, f_ );
            x_ -=  correction;
            // If could not compute the value of system successfully.
            if( 0 != apply() )
            {
                x_.clear();
                return false;
            }
            if( iter >= max_iter )
                break;
        }
        return true;
    }
References apply(), compute_jacobians(), invJ_, J_, and x_.
initialize()
template<typename T > void NonlinearSystem::initialize (const T & x) inline
Definition at line 176 of file NonlinearSystem.h.
    {
        vector_type init;
        init.resize(size_, 0);
        for( size_t i = 0; i < size_; i++)
            init[i] = x[i];
        x_ = init;
        if( 0 == apply() )
        {
            if( 0 != compute_jacobians( init ) )
            {
                return;
            }
        }
        else
            return;
    }
References apply(), compute_jacobians(), size_, and x_.
system()
int NonlinearSystem::system (const vector_type & x, vector_type & f) inline
Definition at line 209 of file NonlinearSystem.h.
    {
        size_t num_consv = ri.num_mols - ri.rank;
        for ( size_t i = 0; i < ri.num_mols; ++i )
        {
            double temp = x[i] * x[i] ;
            // if overflow
            if ( std::isnan( temp ) || std::isinf( temp ) )
                return -1;
            else
                ri.nVec[i] = temp;
        }
        vector< double > vels;
        ri.pool->updateReacVelocities( &ri.nVec[0], vels );
        assert( vels.size() == static_cast< unsigned int >( ri.num_reacs ) );
        // y = Nr . v
        // Note that Nr is row-echelon: diagonal and above.
        f.resize( ri.rank + num_consv);
        for ( size_t i = 0; i < ri.rank; ++i )
        {
            double temp = 0;
            for ( size_t j = i; j < ri.num_reacs; ++j )
                temp += ri.Nr(i, j ) * vels[j];
            f[i] = temp ;
        }
        // dT = gamma.S - T
        for ( size_t i = 0; i < num_consv; ++i )
        {
            double dT = - ri.T[i];
            for ( size_t  j = 0; j < ri.num_mols; ++j )
                dT += ri.gamma(i, j) * x[j] * x[j];
            f[ i + ri.rank] = dT ;
        }
        return 0;
    }
Referenced by apply(), and compute_at().
to_string()
string NonlinearSystem::to_string () inline
Definition at line 196 of file NonlinearSystem.h.
    {
        stringstream ss;
        ss << "=======================================================";
        ss << endl << setw(25) << "State of system: " ;
        ss << " Argument: " << x_ << " Value : " << f_;
        ss << endl << setw(25) << "Jacobian: " << J_;
        ss << endl << setw(25) << "Inverse Jacobian: " << invJ_;
        ss << endl;
        return ss.str();
    }
References f_, invJ_, J_, and x_.
Member Data Documentation
dx_
double NonlinearSystem::dx_
Definition at line 299 of file NonlinearSystem.h.
Referenced by compute_jacobians(), and NonlinearSystem().
f_
vector_type NonlinearSystem::f_
Definition at line 301 of file NonlinearSystem.h.
Referenced by apply(), NonlinearSystem(), and to_string().
invJ_
matrix_type NonlinearSystem::invJ_
Definition at line 305 of file NonlinearSystem.h.
Referenced by compute_jacobians(), find_roots_gnewton(), NonlinearSystem(), and to_string().
is_f_positive_
bool NonlinearSystem::is_f_positive_
Definition at line 308 of file NonlinearSystem.h.
is_jacobian_valid_
bool NonlinearSystem::is_jacobian_valid_
Definition at line 307 of file NonlinearSystem.h.
J_
matrix_type NonlinearSystem::J_
Definition at line 304 of file NonlinearSystem.h.
Referenced by compute_jacobians(), find_roots_gnewton(), NonlinearSystem(), and to_string().
ri
ReacInfo NonlinearSystem::ri
Definition at line 313 of file NonlinearSystem.h.
size_
const size_t NonlinearSystem::size_
Definition at line 297 of file NonlinearSystem.h.
Referenced by compute_jacobians(), initialize(), and NonlinearSystem().
slopes_
vector_type NonlinearSystem::slopes_
Definition at line 303 of file NonlinearSystem.h.
Referenced by NonlinearSystem().
x1
vector_type NonlinearSystem::x1
Definition at line 311 of file NonlinearSystem.h.
Referenced by NonlinearSystem().
x2
vector_type NonlinearSystem::x2
Definition at line 311 of file NonlinearSystem.h.
Referenced by NonlinearSystem().
x_
vector_type NonlinearSystem::x_
Definition at line 302 of file NonlinearSystem.h.
Referenced by apply(), find_roots_gnewton(), initialize(), NonlinearSystem(), and to_string().
The documentation for this class was generated from the following file:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/ksolve/NonlinearSystem.h