MOOSE - Multiscale Object Oriented Simulation Environment: Gsolve Class Reference
Gsolve Class Reference
#include <Gsolve.h>
Public Member Functions
size_t advance_chunk (const size_t begin, const size_t end, ProcPtr p)
void fillIncrementFuncDep ()
void fillMmEnzDep ()
void fillPoolFuncDep ()
void getBlock (vector< double > &values) const
bool getClockedUpdate () const
Flag: returns true if randomized round to integers is done.
Id getCompartment () const
Inherited from KsolveBase.
double getConcInit (const Eref &e) const
get initial conc of molecules in given pool and voxel. Bdry cond.
double getDiffConst (const Eref &e) const
Diffusion constant: Only one per pool, voxel number is ignored.
double getN (const Eref &e) const
Get # of molecules in given pool and voxel. Varies with time.
unsigned int getNumAllVoxels () const
vector< unsigned int > getNumFire (unsigned int voxel) const
unsigned int getNumLocalVoxels () const
Number of voxels here. pools_.size() == getNumLocalVoxels.
unsigned int getNumPools () const
Inherited.
unsigned int getNumThreads () const
vector< double > getNvec (unsigned int voxel) const
Returns the vector of pool Num at the specified voxel.
unsigned int getPoolIndex (const Eref &e) const
Return pool index, using Stoich ptr to do lookup.
double getR1 (unsigned int reacIdx, const Eref &e) const
bool getRandInit () const
Flag: returns true if randomized round to integers is done.
int getRngSeedOffset () const
return rngSeedOffset used to give distinct rand seeds to each voxel
Id getStoich () const
double getVolumeOfPool (const Eref &e) const
Return volume of pool e.
unsigned int getVoxelIndex (const Eref &e) const
Gsolve ()
void initProc (const Eref &e, ProcPtr p)
void initReinit (const Eref &e, ProcPtr p)
void insertMathDepReacs (unsigned int mathDepIndex, unsigned int firedReac)
void makeReacDepsUnique ()
Gsolve & operator= (const Gsolve &)
VoxelPoolsBase * pools (unsigned int i)
Return a pointer to the specified VoxelPool.
void process (const Eref &e, ProcPtr p)
void rebuildGssaSystem ()
size_t recalcTimeChunk (const size_t begin, const size_t end, ProcPtr p)
void reinit (const Eref &e, ProcPtr p)
void setBlock (const vector< double > &values)
void setClockedUpdate (bool val)
Flag: set true if randomized round to integers is to be done.
void setCompartment (Id compt)
Assigns compartment.
void setConcInit (const Eref &e, double v)
Set initial conc of molecules in given pool and voxel. Bdry cond.
void setDiffConst (const Eref &e, double v)
Diffusion constant: Only one per pool, voxel number is ignored.
void setDsolve (Id dsolve)
void setN (const Eref &e, double v)
Set # of molecules in given pool and voxel. Varies with time.
void setNumAllVoxels (unsigned int num)
void setNumPools (unsigned int num)
void setNumThreads (unsigned int x)
void setNumVarTotPools (unsigned int var, unsigned int tot)
Inherited.
void setNvec (unsigned int voxel, vector< double > vec)
void setRandInit (bool val)
Flag: set true if randomized round to integers is to be done.
void setRngSeedOffset (int val)
assign rngSeedOffset used to give distinct rand seeds to each voxel
void setStoich (Id stoich)
void updateRateTerms (unsigned int index)
void updateVoxelVol (vector< double > vols)
double volume (unsigned int i) const
Inherited.
~Gsolve ()
Public Member Functions inherited from KsolveBase
Id getCompartment () const
virtual double getMotorConst (const Eref &e)
KsolveBase ()
virtual void notifyAddMsgDestPool (const Eref &e, ObjId msgId)
virtual void notifyAddMsgSrcPool (const Eref &e, ObjId msgId)
virtual void notifyAddPool (const Eref &e)
virtual void notifyDestroyPool (const Eref &e)
virtual void notifyRemovePool (const Eref &e)
virtual void setIsBuffered (const Eref &e, bool val)
Set buffer status of pool. Changes class between Pool and BufPool.
virtual void setMotorConst (const Eref &e, double val)
virtual void setPrev ()
Used to tell Dsolver to assign 'prev' values.
virtual void updateJunctions (double dt)
Used for telling Dsolver to handle all ops across Junctions.
Static Public Member Functions
static const Cinfo * initCinfo ()
Private Attributes
Id dsolve_
KsolveBase * dsolvePtr_
Pointer to diffusion solver.
size_t grainSize_
size_t numThreads_
Number of threads to use when parallel version of Gsolve is used.
vector< GssaVoxelPools > pools_
moose::RNG rng_
int rngSeedOffset_
Offset * voxIdx is added to rng seed for each voxel to get indept.
unsigned int startVoxel_
First voxel indexed on the current node.
Stoich * stoichPtr_
Utility ptr used to help Pool Id lookups by the Ksolve.
GssaSystem sys_
bool useClockedUpdate_
Flag: True if atot should be updated every clock tick.
Additional Inherited Members
Protected Attributes inherited from KsolveBase
Id compartment_
Id of Chem compartment used to figure out volumes of voxels.
bool isBuilt_
Flag: True when solver setup has been completed.
Id stoich_
Detailed Description
Definition at line 17 of file Gsolve.h.
Constructor & Destructor Documentation
Gsolve()
Gsolve::Gsolve ()
Definition at line 239 of file Gsolve.cpp.
               :
    numThreads_ ( 1 ),
    pools_( 1 ),
    startVoxel_( 0 ),
    dsolve_(),
    dsolvePtr_(nullptr),
    useClockedUpdate_( false ),
    rngSeedOffset_( 1031 )
{
    // Initialize with global seed.
    rng_.setSeed(moose::getGlobalSeed());
    numThreads_ = moose::getEnvInt("MOOSE_NUM_THREADS", 1);
}
References dsolve_, dsolvePtr_, moose::getEnvInt(), moose::getGlobalSeed(), Id::Id(), numThreads_, pools_, rng_, rngSeedOffset_, moose::RNG::setSeed(), startVoxel_, and useClockedUpdate_.
~Gsolve()
Gsolve::~Gsolve ()
Definition at line 258 of file Gsolve.cpp.
{
    ;
}
Member Function Documentation
advance_chunk()
size_t Gsolve::advance_chunk (const size_t begin, const size_t end, ProcPtr p)
Definition at line 574 of file Gsolve.cpp.
{
    assert( begin <= std::min(end, pools_.size()) );
    size_t tot = 0;
    for (size_t i = begin; i < std::min(end, pools_.size() ); i++)
    {
        pools_[i].advance( p, &sys_ );
        tot += 1;
    }
    return tot;
}
References GssaVoxelPools::advance(), pools_, and sys_.
Referenced by process().
fillIncrementFuncDep()
void Gsolve::fillIncrementFuncDep ()
Here we fill in the dependencies involving incrementFuncs. These are the functions that evaluate an expression that specifies rate of change of # of a target molecule. There are two dependencies:
When a reaction fires, all the incrementFuncs that depend on the reactants must update their rates. This is added to sys_.dependency[] which is the usual handler for reac dependencies. Note that the inputs to the incrementFuncs are NOT present in the stoichiometry matrix, so this has to be done as a separate step.
When the incrementFunc fires, then downstream reacs must update their rates. This is handled by default with the regular dependency calculations, since incrementFuncs are treated like regular reactions.
Definition at line 781 of file Gsolve.cpp.
{
    // create map of funcs that depend on specified molecule.
    vector< vector< unsigned int > > funcMap( stoichPtr_->getNumAllPools() );
    const vector< RateTerm* >& rates = stoichPtr_->getRateTerms();
    vector< FuncRate* > incrementRates;
    vector< unsigned int > incrementRateIndex;
    const vector< RateTerm* >::const_iterator q;
    for ( unsigned int i = 0; i < rates.size(); ++i )
    {
        FuncRate *term =
            dynamic_cast< FuncRate* >( rates[i] );
        if (term)
        {
            incrementRates.push_back( term );
            incrementRateIndex.push_back( i );
        }
    }
    for ( unsigned int k = 0; k < incrementRates.size(); ++k )
    {
        const vector< unsigned int >& molIndex =
            incrementRates[k]->getFuncArgIndex();
        for ( unsigned int j = 0; j < molIndex.size(); ++j )
            funcMap[ molIndex[j] ].push_back( incrementRateIndex[k] );
    }
    unsigned int numRates = stoichPtr_->getNumRates();
    sys_.dependentMathExpn.resize( numRates );
    vector< unsigned int > indices;
    for ( unsigned int i = 0; i < numRates; ++i )
    {
        // Algorithm:
        // 1.Go through stoich matrix finding all the poolIndices affected
        // by each Rate Term.
        // 2.Use funcMap to look up FuncRateTerms affected by these indices
        // 3. Add the rateTerm->FuncRateTerm mapping to the dependencies.
        const int* entry;
        const unsigned int* colIndex;
        unsigned int numInRow =
            sys_.transposeN.getRow( i, &entry, &colIndex );
        // 1.Go through stoich matrix finding all the poolIndices affected
        // by each Rate Term.
        for ( unsigned int j = 0; j < numInRow; ++j )
        {
            unsigned int molIndex = colIndex[j]; // Affected poolIndex
            // 2.Use funcMap to look up FuncRateTerms affected by these indices
            vector< unsigned int >& funcs = funcMap[ molIndex ];
            // 3. Add the rateTerm->FuncRateTerm mapping to the dependencies.
            vector< unsigned int >& rdep = sys_.dependency[i];
            rdep.insert( rdep.end(), funcs.begin(), funcs.end() );
        }
    }
}
References GssaSystem::dependency, GssaSystem::dependentMathExpn, FuncRate::getFuncArgIndex(), Stoich::getNumAllPools(), Stoich::getNumRates(), Stoich::getRateTerms(), SparseMatrix< T >::getRow(), stoichPtr_, sys_, and GssaSystem::transposeN.
Referenced by rebuildGssaSystem().
fillMmEnzDep()
void Gsolve::fillMmEnzDep ()
Fill in dependency list for all MMEnzs on reactions. The dependencies of MMenz products are already in the system, so here we just need to add cases where any reaction product is the Enz of an MMEnz.
Definition at line 667 of file Gsolve.cpp.
{
    unsigned int numRates = stoichPtr_->getNumRates();
    vector< unsigned int > indices;
    // Make a map to look up enzyme RateTerm using
    // the key of the enzyme molecule.
    map< unsigned int, unsigned int > enzMolMap;
    for ( unsigned int i = 0; i < numRates; ++i )
    {
        const MMEnzymeBase* mme = dynamic_cast< const MMEnzymeBase* >(
                                      stoichPtr_->rates( i ) );
        if ( mme )
        {
            vector< unsigned int > reactants;
            mme->getReactants( reactants );
            if ( reactants.size() > 1 )
                enzMolMap[ reactants.front() ] = i; // front is enzyme.
        }
    }
    // Use the map to fill in deps.
    for ( unsigned int i = 0; i < numRates; ++i )
    {
        // Extract the row of all molecules that depend on the reac.
        const int* entry;
        const unsigned int* colIndex;
        unsigned int numInRow =
            sys_.transposeN.getRow( i, &entry, &colIndex );
        for( unsigned int j = 0; j < numInRow; ++j )
        {
            map< unsigned int, unsigned int >::iterator pos =
                enzMolMap.find( colIndex[j] );
            if ( pos != enzMolMap.end() )
                sys_.dependency[i].push_back( pos->second );
        }
    }
}
References GssaSystem::dependency, Stoich::getNumRates(), RateTerm::getReactants(), SparseMatrix< T >::getRow(), Stoich::rates(), stoichPtr_, sys_, and GssaSystem::transposeN.
Referenced by rebuildGssaSystem().
fillPoolFuncDep()
void Gsolve::fillPoolFuncDep ()
Here we fill in the dependencies involving poolFuncs. These are the functions that evaluate an expression and assign directly to the
of a target molecule.
There are two dependencies:
When a reaction fires, all the Functions that depend on the reactants must update their target molecule. This is in sys_.dependentMathExpn[].
All the reactions that depend on the updated target molecules must now recompute their propensity. This, along with other reac dependencies, is in sys_.dependency[].
Definition at line 718 of file Gsolve.cpp.
{
    // create map of funcs that depend on specified molecule.
    vector< vector< unsigned int > > funcMap(
        stoichPtr_->getNumAllPools() );
    unsigned int numFuncs = stoichPtr_->getNumFuncs();
    for ( unsigned int i = 0; i < numFuncs; ++i )
    {
        const FuncTerm *f = stoichPtr_->funcs( i );
        vector< unsigned int > molIndex = f->getReactantIndex();
        for ( unsigned int j = 0; j < molIndex.size(); ++j )
            funcMap[ molIndex[j] ].push_back( i );
    }
    // The output of each func is a mol indexed as
    // numVarMols + numBufMols + i
    unsigned int numRates = stoichPtr_->getNumRates();
    sys_.dependentMathExpn.resize( numRates );
    vector< unsigned int > indices;
    for ( unsigned int i = 0; i < numRates; ++i )
    {
        vector< unsigned int >& dep = sys_.dependentMathExpn[ i ];
        dep.resize( 0 );
        // Extract the row of all molecules that depend on the reac.
        const int* entry;
        const unsigned int* colIndex;
        unsigned int numInRow =
            sys_.transposeN.getRow( i, &entry, &colIndex );
        for ( unsigned int j = 0; j < numInRow; ++j )
        {
            unsigned int molIndex = colIndex[j];
            vector< unsigned int >& funcs = funcMap[ molIndex ];
            dep.insert( dep.end(), funcs.begin(), funcs.end() );
            for ( unsigned int k = 0; k < funcs.size(); ++k )
            {
                // unsigned int outputMol = funcs[k] + funcOffset;
                unsigned int outputMol = stoichPtr_->funcs( funcs[k] )->getTarget();
                // Insert reac deps here. Columns are reactions.
                vector< int > e; // Entries: we don't need.
                vector< unsigned int > c; // Column index: the reactions.
                stoichPtr_->getStoichiometryMatrix().
                getRow( outputMol, e, c );
                // Each of the reacs (col entries) depend on this func.
                vector< unsigned int > rdep = sys_.dependency[i];
                rdep.insert( rdep.end(), c.begin(), c.end() );
            }
        }
    }
}
References GssaSystem::dependency, GssaSystem::dependentMathExpn, Stoich::funcs(), Stoich::getNumAllPools(), Stoich::getNumFuncs(), Stoich::getNumRates(), FuncTerm::getReactantIndex(), SparseMatrix< T >::getRow(), SparseMatrix< T >::getRow(), Stoich::getStoichiometryMatrix(), FuncTerm::getTarget(), stoichPtr_, sys_, and GssaSystem::transposeN.
Referenced by rebuildGssaSystem().
getBlock()
void Gsolve::getBlock (vector< double > & values) const virtual
Gets block of data. The first 4 entries are passed in on the 'values' vector: the start voxel, numVoxels, start pool#, numPools. These are followed by numVoxels * numPools of data values which are filled in by the function. We assert that the entire requested block is present in this KsolveBase. The block is organized as an array of arrays of voxels; values[pool#][voxel#]
Note that numVoxels and numPools are the number in the current block, not the upper limit of the block. So values.size() == 4 + numPools * numVoxels.
Implements KsolveBase.
Definition at line 1061 of file Gsolve.cpp.
{
    unsigned int startVoxel = static_cast<unsigned int>(values[0]);
    unsigned int numVoxels = static_cast<unsigned int>(values[1]);
    unsigned int startPool = static_cast<unsigned int>(values[2]);
    unsigned int numPools = static_cast<unsigned int>(values[3]);
    assert( startVoxel >= startVoxel_ );
    assert( numVoxels <= pools_.size() );
    assert( pools_.size() > 0 );
    assert( numPools + startPool <= pools_[0].size() );
    values.resize( 4 + numVoxels * numPools );
    for ( unsigned int i = 0; i < numVoxels; ++i )
    {
        const double* v = pools_[ startVoxel + i ].S();
        for ( unsigned int j = 0; j < numPools; ++j )
        {
            values[ 4 + j * numVoxels + i]  = v[ j + startPool ];
        }
    }
}
References pools_, VoxelPoolsBase::S(), VoxelPoolsBase::size(), and startVoxel_.
Referenced by process().
getClockedUpdate()
bool Gsolve::getClockedUpdate () const
Flag: returns true if randomized round to integers is done.
Definition at line 396 of file Gsolve.cpp.
{
    return useClockedUpdate_;
}
References useClockedUpdate_.
Referenced by initCinfo().
getCompartment()
Id Gsolve::getCompartment () const
Inherited from KsolveBase.
Definition at line 289 of file Gsolve.cpp.
{
    return compartment_;
}
References KsolveBase::compartment_.
Referenced by initCinfo().
getConcInit()
double Gsolve::getConcInit (const Eref & e) const virtual
get initial conc of molecules in given pool and voxel. Bdry cond.
Implements KsolveBase.
Definition at line 1016 of file Gsolve.cpp.
{
    unsigned int vox = getVoxelIndex( e );
    if ( vox != OFFNODE )
        return pools_[vox].getConcInit( getPoolIndex( e ) );
    return 0.0;
}
References VoxelPoolsBase::getConcInit(), getPoolIndex(), getVoxelIndex(), OFFNODE, and pools_.
getDiffConst()
double Gsolve::getDiffConst (const Eref & e) const virtual
Diffusion constant: Only one per pool, voxel number is ignored.
Implements KsolveBase.
Definition at line 1035 of file Gsolve.cpp.
{
    return 0;
}
getN()
double Gsolve::getN (const Eref & e) const virtual
Get # of molecules in given pool and voxel. Varies with time.
Implements KsolveBase.
Definition at line 985 of file Gsolve.cpp.
{
    unsigned int vox = getVoxelIndex( e );
    if ( vox != OFFNODE )
        return pools_[vox].getN( getPoolIndex( e ) );
    return 0.0;
}
References VoxelPoolsBase::getN(), getPoolIndex(), getVoxelIndex(), OFFNODE, and pools_.
getNumAllVoxels()
unsigned int Gsolve::getNumAllVoxels () const
Definition at line 316 of file Gsolve.cpp.
{
    return pools_.size(); // Need to redo.
}
References pools_.
Referenced by initCinfo().
getNumFire()
vector< unsigned int > Gsolve::getNumFire (unsigned int voxel) const
Definition at line 364 of file Gsolve.cpp.
{
    static vector< unsigned int > dummy;
    if ( voxel < pools_.size() )
    {
        return const_cast< GssaVoxelPools* >( &( pools_[ voxel ]) )->numFire();
    }
    return dummy;
}
References GssaVoxelPools::numFire(), and pools_.
Referenced by initCinfo().
getNumLocalVoxels()
unsigned int Gsolve::getNumLocalVoxels () const virtual
Number of voxels here. pools_.size() == getNumLocalVoxels.
Implements KsolveBase.
Definition at line 311 of file Gsolve.cpp.
{
    return pools_.size();
}
References pools_.
Referenced by initCinfo(), and process().
getNumPools()
unsigned int Gsolve::getNumPools () const virtual
Inherited.
Implements KsolveBase.
Definition at line 1054 of file Gsolve.cpp.
{
    if ( pools_.size() > 0 )
        return pools_[0].size();
    return 0;
}
References pools_, and VoxelPoolsBase::size().
Referenced by initCinfo().
getNumThreads()
unsigned int Gsolve::getNumThreads () const
Definition at line 1157 of file Gsolve.cpp.
{
    return numThreads_;
}
References numThreads_.
Referenced by initCinfo(), and reinit().
getNvec()
vector< double > Gsolve::getNvec (unsigned int voxel) const
Returns the vector of pool Num at the specified voxel.
Definition at line 332 of file Gsolve.cpp.
{
    static vector< double > dummy;
    if ( voxel < pools_.size() )
    {
        return const_cast< GssaVoxelPools* >( &( pools_[ voxel ]) )->Svec();
    }
    return dummy;
}
References pools_, and VoxelPoolsBase::Svec().
Referenced by initCinfo().
getPoolIndex()
unsigned int Gsolve::getPoolIndex (const Eref & er) const virtual
Return pool index, using Stoich ptr to do lookup.
Implements KsolveBase.
Definition at line 927 of file Gsolve.cpp.
{
    return stoichPtr_->convertIdToPoolIndex( e.id() );
}
References Stoich::convertIdToPoolIndex(), Eref::id(), and stoichPtr_.
Referenced by getConcInit(), getN(), setConcInit(), and setN().
getR1()
double Gsolve::getR1 (unsigned int reacIdx, const Eref & e) const virtual
Get rate const in a given reac and voxel. Usually fixed but may vary if the reac is controlled by a function.
Implements KsolveBase.
Definition at line 993 of file Gsolve.cpp.
{
    unsigned int vox = getVoxelIndex( e );
    if ( vox != OFFNODE )
        return pools_[vox].getR1( reacIdx );
    return 0.0;
}
References VoxelPoolsBase::getR1(), getVoxelIndex(), OFFNODE, and pools_.
getRandInit()
bool Gsolve::getRandInit () const
Flag: returns true if randomized round to integers is done.
Definition at line 375 of file Gsolve.cpp.
{
    return sys_.useRandInit;
}
References sys_, and GssaSystem::useRandInit.
Referenced by initCinfo().
getRngSeedOffset()
int Gsolve::getRngSeedOffset () const
return rngSeedOffset used to give distinct rand seeds to each voxel
Definition at line 386 of file Gsolve.cpp.
{
    return rngSeedOffset_;
}
References rngSeedOffset_.
Referenced by initCinfo().
getStoich()
Id Gsolve::getStoich () const
Definition at line 267 of file Gsolve.cpp.
{
    return stoich_;
}
References KsolveBase::stoich_.
Referenced by initCinfo().
getVolumeOfPool()
double Gsolve::getVolumeOfPool (const Eref & e) const virtual
Return volume of pool e.
Implements KsolveBase.
Definition at line 1024 of file Gsolve.cpp.
{
    unsigned int vox = getVoxelIndex( e );
    return pools_[vox].getVolume();
}
References VoxelPoolsBase::getVolume(), getVoxelIndex(), and pools_.
getVoxelIndex()
unsigned int Gsolve::getVoxelIndex (const Eref & e) const
Definition at line 932 of file Gsolve.cpp.
{
    unsigned int ret = e.dataIndex();
    if ( (ret < startVoxel_) || (ret >= startVoxel_ + pools_.size()))
        return OFFNODE;
    return ret - startVoxel_;
}
References Eref::dataIndex(), OFFNODE, pools_, and startVoxel_.
Referenced by getConcInit(), getN(), getR1(), getVolumeOfPool(), setConcInit(), and setN().
initCinfo()
const Cinfo * Gsolve::initCinfo () static
Definition at line 56 of file Gsolve.cpp.
{
    // Field definitions
    static ValueFinfo< Gsolve, Id > stoich (
        "stoich",
        "Stoichiometry object for handling this reaction system.",
        &Gsolve::setStoich,
        &Gsolve::getStoich
    );
    static ValueFinfo< Gsolve, Id > compartment (
        "compartment",
        "Compartment that contains this reaction system.",
        &Gsolve::setCompartment,
        &Gsolve::getCompartment
    );
    static ReadOnlyValueFinfo< Gsolve, unsigned int > numLocalVoxels(
        "numLocalVoxels",
        "Number of voxels in the core reac-diff system, on the "
        "current solver. ",
        &Gsolve::getNumLocalVoxels
    );
    static LookupValueFinfo<Gsolve, unsigned int, vector< double > > nVec(
        "nVec",
        "vector of pool counts",
        &Gsolve::setNvec,
        &Gsolve::getNvec
    );
    static ValueFinfo< Gsolve, unsigned int > numAllVoxels(
        "numAllVoxels",
        "Number of voxels in the entire reac-diff system, "
        "including proxy voxels to represent abutting compartments.",
        &Gsolve::setNumAllVoxels,
        &Gsolve::getNumAllVoxels
    );
    static ValueFinfo< Gsolve, unsigned int > numPools(
        "numPools",
        "Number of molecular pools in the entire reac-diff system, "
        "including variable, function and buffered.",
        &Gsolve::setNumPools,
        &Gsolve::getNumPools
    );
    static ValueFinfo< Gsolve, unsigned int > numThreads(
        "numThreads",
        "Number of threads to use in GSolve",
        &Gsolve::setNumThreads,
        &Gsolve::getNumThreads
    );
    static ValueFinfo< Gsolve, bool > useRandInit(
        "useRandInit",
        "Flag: True when using probabilistic (random) rounding.\n "
        "Default: True.\n "
        "When initializing the mol# from floating-point concInit values, "
        "we have two options. One is to look at each concInit, obtain "
        "nInit, and round to the nearest integer. The other is to look "
        "at each nInit (coming from concInit), "
        "and probabilistically round up or down depending on the  "
        "value. For example, if we had a nInit value of 1.49,  "
        "this would always be rounded to 1.0 if the flag is false, "
        "and would be rounded to 1.0 and 2.0 in the ratio 51:49 if "
        "the flag is true. ",
        &Gsolve::setRandInit,
        &Gsolve::getRandInit
    );
    static ValueFinfo< Gsolve, int > rngSeedOffset(
        "rngSeedOffset",
        "Get rng sequence independence by adding rngSeedOffset*(1+voxIdx)"
        " to the global rngSeed in each voxel, upon reinit.",
        &Gsolve::setRngSeedOffset,
        &Gsolve::getRngSeedOffset
    );
    static ValueFinfo< Gsolve, bool > useClockedUpdate(
        "useClockedUpdate",
        "Flag: True to cause all reaction propensities to be updated "
        "on every clock tick.\n"
        "Default: False.\n"
        "This flag should be set when the reaction system "
        "includes a function with a dependency on time or on external "
        "events. It has a significant speed penalty so the flag "
        "should not be set unless there are such functions. ",
        &Gsolve::setClockedUpdate,
        &Gsolve::getClockedUpdate
    );
    static ReadOnlyLookupValueFinfo<
    Gsolve, unsigned int, vector< unsigned int > > numFire(
        "numFire",
        "Vector of the number of times each reaction has fired."
        "Indexed by the voxel number."
        "Zeroed out at reinit.",
        &Gsolve::getNumFire
    );
    // DestFinfo definitions
    static DestFinfo process( "process",
            "Handles process call",
            new ProcOpFunc< Gsolve >( &Gsolve::process ) );
    static DestFinfo reinit( "reinit",
            "Handles reinit call",
            new ProcOpFunc< Gsolve >( &Gsolve::reinit ) );
    static DestFinfo voxelVol( "voxelVol",
            "Handles updates to all voxels. Comes from parent "
            "ChemCompt object.",
            new OpFunc1< Gsolve, vector< double > >(
                &Gsolve::updateVoxelVol )
            );
    static DestFinfo initProc( "initProc",
            "Handles initProc call from Clock",
            new ProcOpFunc< Gsolve >( &Gsolve::initProc ) );
    static DestFinfo initReinit( "initReinit",
            "Handles initReinit call from Clock",
            new ProcOpFunc< Gsolve >( &Gsolve::initReinit ) );
    // Shared definitions
    static Finfo* procShared[] =
    {
        &process, &reinit
    };
    static SharedFinfo proc( "proc",
            "Shared message for process and reinit",
            procShared, sizeof( procShared ) / sizeof( const Finfo* )
            );
    static Finfo* initShared[] =
    {
        &initProc, &initReinit
    };
    static SharedFinfo init( "init",
            "Shared message for initProc and initReinit. This is used"
            " when the system has cross-compartment reactions. ",
            initShared, sizeof( initShared ) / sizeof( const Finfo* )
            );
    static Finfo* gsolveFinfos[] =
    {
        &stoich,           // Value
        &numLocalVoxels,   // ReadOnlyValue
        &nVec,             // LookupValue
        &numAllVoxels,     // ReadOnlyValue
        &numPools,         // Value
        &numThreads,       // Value
        &voxelVol,         // DestFinfo
        &proc,             // SharedFinfo
        &init,             // SharedFinfo
        // Here we put new fields that were not there in the Ksolve.
        &useRandInit,      // Value
        &useClockedUpdate, // Value
        &numFire,          // ReadOnlyLookupValue
    };
    static Dinfo< Gsolve > dinfo;
    static  Cinfo gsolveCinfo( "Gsolve",
            Neutral::initCinfo(),
            gsolveFinfos,
            sizeof(gsolveFinfos)/sizeof(Finfo *),
            &dinfo
            );
    return &gsolveCinfo;
}
References Cinfo::Cinfo(), DestFinfo::DestFinfo(), getClockedUpdate(), getCompartment(), getNumAllVoxels(), getNumFire(), getNumLocalVoxels(), getNumPools(), getNumThreads(), getNvec(), getRandInit(), getRngSeedOffset(), getStoich(), Neutral::initCinfo(), initProc(), initReinit(), LookupValueFinfo< T, L, F >::LookupValueFinfo(), OpFunc1< T, A >::OpFunc1(), process(), ProcOpFunc< T >::ProcOpFunc(), ReadOnlyLookupValueFinfo< T, L, F >::ReadOnlyLookupValueFinfo(), ReadOnlyValueFinfo< T, F >::ReadOnlyValueFinfo(), reinit(), setClockedUpdate(), setCompartment(), setNumAllVoxels(), setNumPools(), setNumThreads(), setNvec(), setRandInit(), setRngSeedOffset(), setStoich(), SharedFinfo::SharedFinfo(), updateVoxelVol(), and ValueFinfo< T, F >::ValueFinfo().
initProc()
void Gsolve::initProc (const Eref & e, ProcPtr p)
Definition at line 620 of file Gsolve.cpp.
{;}
Referenced by initCinfo().
initReinit()
void Gsolve::initReinit (const Eref & e, ProcPtr p)
Definition at line 623 of file Gsolve.cpp.
{
    if ( !stoichPtr_ )
        return;
    for( size_t i = 0 ; i < pools_.size(); ++i )
        pools_[i].reinit( &sys_, i * rngSeedOffset_ );
}
References pools_, GssaVoxelPools::reinit(), rngSeedOffset_, stoichPtr_, and sys_.
Referenced by initCinfo().
insertMathDepReacs()
void Gsolve::insertMathDepReacs (unsigned int mathDepIndex, unsigned int firedReac)
Inserts reactions that depend on molecules modified by the specified MathExpn, into the dependency list. Later.
Definition at line 891 of file Gsolve.cpp.
{
    /*
    unsigned int molIndex = sumTotals_[ mathDepIndex ].target( S_ );
    vector< unsigned int > reacIndices;
    // Extract the row of all reacs that depend on the target molecule
    if ( N_.getRowIndices( molIndex, reacIndices ) > 0 ) {
        vector< unsigned int >& dep = dependency_[ firedReac ];
        dep.insert( dep.end(), reacIndices.begin(), reacIndices.end() );
    }
    */
}
makeReacDepsUnique()
void Gsolve::makeReacDepsUnique ()
STL stuff follows, with the usual weirdness.
Definition at line 908 of file Gsolve.cpp.
{
    unsigned int numRates = stoichPtr_->getNumRates();
    for ( unsigned int i = 0; i < numRates; ++i )
    {
        vector< unsigned int >& dep = sys_.dependency[ i ];
        // Here we want to remove self-entries as well as duplicates.
        sort( dep.begin(), dep.end() );
        vector< unsigned int >::iterator k = dep.begin();
        vector<unsigned int>::iterator pos = unique( dep.begin(), dep.end() );
        dep.resize( pos - dep.begin() );
    }
}
References GssaSystem::dependency, Stoich::getNumRates(), stoichPtr_, and sys_.
Referenced by rebuildGssaSystem().
operator=()
Gsolve & Gsolve::operator= (const Gsolve &)
Definition at line 253 of file Gsolve.cpp.
{
    return *this;
}
pools()
VoxelPoolsBase * Gsolve::pools (unsigned int i) virtual
Return a pointer to the specified VoxelPool.
Implements KsolveBase.
Definition at line 1143 of file Gsolve.cpp.
{
    if ( pools_.size() > i )
        return &pools_[i];
    return 0;
}
References pools_.
process()
void Gsolve::process (const Eref & e, ProcPtr p)
Definition at line 410 of file Gsolve.cpp.
{
    // cout << stoichPtr_ << "    dsolve = " <<    dsolvePtr_ << endl;
    if ( !stoichPtr_ )
        return;
    // First, handle incoming diffusion values. Note potential for
    // issues with roundoff if diffusion is not integral.
    if ( dsolvePtr_ )
    {
        vector< double > dvalues( 4 );
        dvalues[0] = 0;
        dvalues[1] = getNumLocalVoxels();
        dvalues[2] = 0;
        dvalues[3] = stoichPtr_->getNumVarPools();
        dsolvePtr_->getBlock( dvalues );
        dsolvePtr_->setPrev();
        // Here we need to convert to integers, just in case. Normally
        // one would use a stochastic (integral) diffusion method with
        // the GSSA, but in mixed models it may be more complicated.
        vector< double >::iterator i = dvalues.begin() + 4;
        for ( ; i != dvalues.end(); ++i )
        {
#if 0
            *i = std::round( *i );
#else
            // *i = approximateWithInteger_debug(__FUNCTION__, *i, rng_);
            *i = approximateWithInteger(*i, rng_);
#endif
        }
        setBlock( dvalues );
    }
    if ( dsolvePtr_ )
    {
        for ( auto i = pools_.begin(); i != pools_.end(); ++i )
            i->refreshAtot( &sys_ );
    }
    if( 1 == numThreads_ || 1 == pools_.size())
    {
        if( numThreads_ > 1 )
        {
            cerr << "Warn: Not enough voxel. Reverting back to serial mode. " << endl;
            numThreads_ = 1;
        }
        for ( size_t i = 0; i < pools_.size(); i++ )
            pools_[i].advance( p, &sys_ );
    }
    else
    {
        /*-----------------------------------------------------------------------------
         *  Somewhat complicated computation to compute the number of threads. 1
         *  thread per (at least) voxel pool is ideal situation.
         *-----------------------------------------------------------------------------*/
#if USING_ASYNC
        vector<std::future<size_t>> vecFutures;
        for (size_t i = 0; i < numThreads_; i++)
            vecFutures.push_back(
                std::async( THREAD_LAUNCH_POLICY
                    , [this, i, p](){
                        return this->advance_chunk(i*this->grainSize_, (i+1)*this->grainSize_, p);
                    })
                );
        // Block in same order
        size_t tot = 0;
        for (auto& fut : vecFutures) tot += fut.get();
        // We have processed all the pools.
        assert( tot >= pools_.size() );
#else
        vector<std::thread> vecThreads;
        for (size_t i = 0; i < numThreads_; i++)
        {
            // Use lambda. It is roughly 10% faster than std::bind and does not
            // involve copying data.
            vecThreads.push_back(
                std::thread(
                    [this, i, p](){ this->advance_chunk(i*this->grainSize_, (i+1)*this->grainSize_, p); }
                    )
                );
        }
        for( auto &v : vecThreads )
            v.join();
#endif
    }
    if ( useClockedUpdate_ )   // Check if a clocked stim is to be updated
    {
        if(numThreads_ == 1)
        {
            for ( auto &v : pools_ )
                v.recalcTime( &sys_, p->currTime );
        }
        else
        {
#if USING_ASYNC
        vector<std::future<size_t>> vecFutures;
        for (size_t i = 0; i < numThreads_; i++)
            vecFutures.push_back(
                std::async( THREAD_LAUNCH_POLICY
                    , [this, i, p](){
                        return this->recalcTimeChunk(i*this->grainSize_, (i+1)*this->grainSize_, p);
                    })
                );
        // Block in same order
        size_t tot = 0;
        for (auto& fut : vecFutures) tot += fut.get();
        assert( tot >= pools_.size() ); // We have processed all the pools.
#else
            vector<std::thread> vecThreads;
            for (size_t i = 0; i < numThreads_; i++)
            {
                // Use lambda. It is roughly 10% faster than std::bind and does not
                // involve copying data.
                vecThreads.push_back(
                        std::thread(
                            [this, i, p](){
                                this->recalcTimeChunk(i*this->grainSize_, (i+1)*this->grainSize_, p);
                            }
                        )
                    );
            }
            for( auto &v : vecThreads )
                v.join();
#endif
        }
    }
    // Finally, assemble and send the integrated values off for the Dsolve.
    if ( dsolvePtr_ )
    {
        vector< double > kvalues( 4 );
        kvalues[0] = 0;
        kvalues[1] = getNumLocalVoxels();
        kvalues[2] = 0;
        kvalues[3] = stoichPtr_->getNumVarPools();
        getBlock( kvalues );
        dsolvePtr_->setBlock( kvalues );
        // Now use the values in the Dsolve to update junction fluxes
        // for diffusion, channels, and xreacs
        dsolvePtr_->updateJunctions( p->dt );
        // Here the Gsolve may need to do something to convert to integers
    }
}
References GssaVoxelPools::advance(), advance_chunk(), approximateWithInteger(), ProcInfo::currTime, dsolvePtr_, ProcInfo::dt, getBlock(), KsolveBase::getBlock(), getNumLocalVoxels(), Stoich::getNumVarPools(), grainSize_, numThreads_, pools_, GssaVoxelPools::recalcTime(), recalcTimeChunk(), GssaVoxelPools::refreshAtot(), rng_, setBlock(), KsolveBase::setBlock(), KsolveBase::setPrev(), stoichPtr_, sys_, KsolveBase::updateJunctions(), and useClockedUpdate_.
Referenced by initCinfo().
rebuildGssaSystem()
void Gsolve::rebuildGssaSystem ()
Definition at line 635 of file Gsolve.cpp.
{
    stoichPtr_->convertRatesToStochasticForm();
    sys_.transposeN = stoichPtr_->getStoichiometryMatrix();
    sys_.transposeN.transpose();
    sys_.transposeN.truncateRow( stoichPtr_->getNumVarPools() + stoichPtr_->getNumProxyPools() );
    vector< vector< unsigned int > > & dep = sys_.dependency;
    dep.resize( stoichPtr_->getNumRates() );
    for ( unsigned int i = 0; i < stoichPtr_->getNumRates(); ++i )
    {
        sys_.transposeN.getGillespieDependence( i, dep[i] );
    }
    fillMmEnzDep();
    fillPoolFuncDep();
    fillIncrementFuncDep();
    makeReacDepsUnique();
    for ( vector< GssaVoxelPools >::iterator
            i = pools_.begin(); i != pools_.end(); ++i )
    {
        i->setNumReac( stoichPtr_->getNumRates() );
        i->updateAllRateTerms( stoichPtr_->getRateTerms(),
                               stoichPtr_->getNumCoreRates() );
    }
    sys_.isReady = true;
}
References Stoich::convertRatesToStochasticForm(), GssaSystem::dependency, fillIncrementFuncDep(), fillMmEnzDep(), fillPoolFuncDep(), KinSparseMatrix::getGillespieDependence(), Stoich::getNumCoreRates(), Stoich::getNumProxyPools(), Stoich::getNumRates(), Stoich::getNumVarPools(), Stoich::getRateTerms(), Stoich::getStoichiometryMatrix(), GssaSystem::isReady, makeReacDepsUnique(), pools_, GssaVoxelPools::setNumReac(), stoichPtr_, sys_, SparseMatrix< T >::transpose(), GssaSystem::transposeN, KinSparseMatrix::truncateRow(), and GssaVoxelPools::updateAllRateTerms().
Referenced by reinit().
recalcTimeChunk()
size_t Gsolve::recalcTimeChunk (const size_t begin, const size_t end, ProcPtr p)
Definition at line 562 of file Gsolve.cpp.
{
    assert( begin >= std::min(pools_.size(), end));
    size_t tot = 0;
    for (size_t i = begin; i < std::min(pools_.size(), end); i++)  {
        tot += 1;
        pools_[i].recalcTime( &sys_, p->currTime );
    }
    return tot;
}
References ProcInfo::currTime, pools_, GssaVoxelPools::recalcTime(), and sys_.
Referenced by process().
reinit()
void Gsolve::reinit (const Eref & e, ProcPtr p)
Definition at line 586 of file Gsolve.cpp.
{
    if ( !stoichPtr_ )
        return;
    if ( !sys_.isReady )
        rebuildGssaSystem();
    // First reinit concs. We also assign distinct rng seeds per voxel
    for( unsigned int i = 0; i < pools_.size(); ++i ) {
        pools_[i].reinit( &sys_, (i+1) * rngSeedOffset_ );
    }
    // Second, update the atots.
    for ( auto i = pools_.begin(); i != pools_.end(); ++i )
        i->refreshAtot( &sys_ );
    // LoadBalancing. Recompute the optimal number of threads.
    size_t nvPools = pools_.size( );
    grainSize_ = (size_t) std::ceil((double)nvPools / (double)numThreads_);
    assert( grainSize_ * numThreads_ >= nvPools);
    numThreads_ = (size_t) std::ceil((double)nvPools / (double)grainSize_);
    // MOOSE_DEBUG( "Grain size is " << grainSize_ << ". Num threads " << numThreads_);
    if(1 < numThreads_)
        cout << "Info: Setting up threaded gsolve with " << getNumThreads( )
             << " threads. " << endl;
}
References getNumThreads(), grainSize_, GssaSystem::isReady, numThreads_, pools_, rebuildGssaSystem(), GssaVoxelPools::refreshAtot(), GssaVoxelPools::reinit(), rngSeedOffset_, stoichPtr_, and sys_.
Referenced by initCinfo().
setBlock()
void Gsolve::setBlock (const vector< double > & values) virtual
Sets block of data. The first 4 entries on the 'values' vector are the start voxel, numVoxels, start pool#, numPools. These are followed by numVoxels * numPools of data values.
Implements KsolveBase.
Definition at line 1084 of file Gsolve.cpp.
{
    unsigned int startVoxel = static_cast<unsigned int>(values[0]);
    unsigned int numVoxels = static_cast<unsigned int>(values[1]);
    unsigned int startPool = static_cast<unsigned int>(values[2]);
    unsigned int numPools = static_cast<unsigned int>(values[3]);
    assert( startVoxel >= startVoxel_ );
    assert( numVoxels <= pools_.size() );
    assert( pools_.size() > 0 );
    assert( numPools + startPool <= pools_[0].size() );
    for ( unsigned int i = 0; i < numVoxels; ++i )
    {
        double* v = pools_[ startVoxel + i ].varS();
        for ( unsigned int j = 0; j < numPools; ++j )
        {
            v[ j + startPool ] = values[ 4 + j * numVoxels + i ];
        }
    }
}
References pools_, VoxelPoolsBase::size(), startVoxel_, and VoxelPoolsBase::varS().
Referenced by process().
setClockedUpdate()
void Gsolve::setClockedUpdate (bool val)
Flag: set true if randomized round to integers is to be done.
Definition at line 401 of file Gsolve.cpp.
{
    useClockedUpdate_ = val;
}
References useClockedUpdate_.
Referenced by initCinfo().
setCompartment()
void Gsolve::setCompartment (Id compartment) virtual
Assigns compartment.
Reimplemented from KsolveBase.
Definition at line 272 of file Gsolve.cpp.
{
    if ( ( compt.element()->cinfo()->isA( "ChemCompt" ) ) )
    {
        compartment_ = compt;
        vector< double > vols = Field< vector< double > >::get( compt, "voxelVolume" );
        if ( vols.size() > 0 )
        {
            pools_.resize( vols.size() );
            for ( unsigned int i = 0; i < vols.size(); ++i )
            {
                pools_[i].setVolume( vols[i] );
            }
        }
    }
}
References Element::cinfo(), KsolveBase::compartment_, Id::element(), Field< A >::get(), Cinfo::isA(), pools_, and VoxelPoolsBase::setVolume().
Referenced by initCinfo().
setConcInit()
void Gsolve::setConcInit (const Eref & e, double val) virtual
Set initial conc of molecules in given pool and voxel. Bdry cond.
Implements KsolveBase.
Definition at line 1001 of file Gsolve.cpp.
{
    unsigned int vox = getVoxelIndex( e );
    if ( vox != OFFNODE )
    {
        pools_[vox].setConcInit( getPoolIndex( e ), v );
        if ( e.element()->cinfo()->isA( "BufPool" ) )
        {
            // refresh rates because concInit controls ongoing value of n.
            if ( sys_.isReady )
                pools_[vox].refreshAtot( &sys_ );
        }
    }
}
References Element::cinfo(), Eref::element(), getPoolIndex(), getVoxelIndex(), Cinfo::isA(), GssaSystem::isReady, OFFNODE, pools_, GssaVoxelPools::refreshAtot(), VoxelPoolsBase::setConcInit(), and sys_.
setDiffConst()
void Gsolve::setDiffConst (const Eref & e, double val) virtual
Diffusion constant: Only one per pool, voxel number is ignored.
Implements KsolveBase.
Definition at line 1030 of file Gsolve.cpp.
{
    ; // Do nothing.
}
setDsolve()
void Gsolve::setDsolve (Id dsolve) virtual
Inherited. Needed for reac-diff calculations so the Gsolve can orchestrate the data transfer between the itself and the diffusion solver.
Implements KsolveBase.
Definition at line 940 of file Gsolve.cpp.
{
    if ( dsolve == Id () )
    {
        dsolvePtr_ = 0;
        dsolve_ = Id();
    }
    else if ( dsolve.element()->cinfo()->isA( "Dsolve" ) )
    {
        dsolve_ = dsolve;
        dsolvePtr_ = reinterpret_cast<KsolveBase*>(dsolve.eref().data());
    }
    else
    {
        cout << "Warning: Gsolve::setDsolve: Object '" << dsolve.path() <<
             "' should be class Dsolve, is: " <<
             dsolve.element()->cinfo()->name() << endl;
    }
}
References Element::cinfo(), Eref::data(), dsolve_, dsolvePtr_, Id::element(), Id::eref(), Id::Id(), Cinfo::isA(), Cinfo::name(), Id::operator==(), and Id::path().
setN()
void Gsolve::setN (const Eref & e, double val) virtual
Set # of molecules in given pool and voxel. Varies with time.
Implements KsolveBase.
Definition at line 965 of file Gsolve.cpp.
{
    unsigned int vox = getVoxelIndex( e );
    if ( vox != OFFNODE )
    {
        if ( e.element()->cinfo()->isA( "BufPool" ) )
        {
            // Do NOT round it here, it is folded into rate term.
            pools_[vox].setN( getPoolIndex( e ), v );
            // refresh rates because concInit controls ongoing value of n.
            if ( sys_.isReady )
                pools_[vox].refreshAtot( &sys_ );
        }
        else
        {
            pools_[vox].setN( getPoolIndex( e ), std::round( v ) );
        }
    }
}
References Element::cinfo(), Eref::element(), getPoolIndex(), getVoxelIndex(), Cinfo::isA(), GssaSystem::isReady, OFFNODE, pools_, GssaVoxelPools::refreshAtot(), VoxelPoolsBase::setN(), and sys_.
setNumAllVoxels()
void Gsolve::setNumAllVoxels (unsigned int num) virtual
Assigns the number of voxels used in the entire reac-diff system. Note that fewer than this may be used on any given node.
Implements KsolveBase.
Definition at line 322 of file Gsolve.cpp.
{
    if ( numVoxels == 0 )
    {
        return;
    }
    pools_.resize( numVoxels );
    sys_.isReady = false;
}
References GssaSystem::isReady, pools_, and sys_.
Referenced by initCinfo().
setNumPools()
void Gsolve::setNumPools (unsigned int num) virtual
Assigns number of different pools (chemical species) present in each voxel.
Implements KsolveBase.
Definition at line 1040 of file Gsolve.cpp.
{
    sys_.isReady = false;
    unsigned int numVoxels = pools_.size();
    for ( unsigned int i = 0 ; i < numVoxels; ++i )
    {
        pools_[i].resizeArrays( numPoolSpecies );
    }
}
References GssaSystem::isReady, pools_, VoxelPoolsBase::resizeArrays(), and sys_.
Referenced by initCinfo(), and setNumVarTotPools().
setNumThreads()
void Gsolve::setNumThreads (unsigned int x)
Definition at line 1162 of file Gsolve.cpp.
{
    numThreads_ = x;
}
References numThreads_.
Referenced by initCinfo().
setNumVarTotPools()
void Gsolve::setNumVarTotPools (unsigned int var, unsigned int tot) virtual
Inherited.
Implements KsolveBase.
Definition at line 1050 of file Gsolve.cpp.
{
    setNumPools( tot );
}
References setNumPools().
setNvec()
void Gsolve::setNvec (unsigned int voxel, vector< double > vec)
Definition at line 342 of file Gsolve.cpp.
{
    if ( voxel < pools_.size() )
    {
        if ( nVec.size() != pools_[voxel].size() )
        {
            cout << "Warning: Gsolve::setNvec: size mismatch ( " <<
                 nVec.size() << ", " << pools_[voxel].size() << ")\n";
            return;
        }
        double* s = pools_[voxel].varS();
        for ( unsigned int i = 0; i < nVec.size(); ++i )
        {
            s[i] = std::round( nVec[i] );
            if ( s[i] < 0.0 )
                s[i] = 0.0;
        }
        if ( sys_.isReady )
            pools_[voxel].refreshAtot( &sys_ );
    }
}
References GssaSystem::isReady, pools_, GssaVoxelPools::refreshAtot(), VoxelPoolsBase::size(), sys_, and VoxelPoolsBase::varS().
Referenced by initCinfo().
setRandInit()
void Gsolve::setRandInit (bool val)
Flag: set true if randomized round to integers is to be done.
Definition at line 380 of file Gsolve.cpp.
{
    sys_.useRandInit = val;
}
References sys_, and GssaSystem::useRandInit.
Referenced by initCinfo().
setRngSeedOffset()
void Gsolve::setRngSeedOffset (int val)
assign rngSeedOffset used to give distinct rand seeds to each voxel
Definition at line 391 of file Gsolve.cpp.
{
    rngSeedOffset_ = val;
}
References rngSeedOffset_.
Referenced by initCinfo().
setStoich()
void Gsolve::setStoich (Id stoich) virtual
Informs the ZPI about the stoich, used during subsequent computations. Called to wrap up the model building. The Stoich does this call after it has set up its own path.
Implements KsolveBase.
Definition at line 294 of file Gsolve.cpp.
{
    // This call is done _before_ setting the path on stoich
    assert( stoich.element()->cinfo()->isA( "Stoich" ) );
    stoich_ = stoich;
    stoichPtr_ = reinterpret_cast< Stoich* >( stoich.eref().data() );
    if ( stoichPtr_->getNumAllPools() == 0 )
    {
        stoichPtr_ = 0;
        return;
    }
    sys_.stoich = stoichPtr_;
    sys_.isReady = false;
    for ( unsigned int i = 0; i < pools_.size(); ++i )
        pools_[i].setStoich( stoichPtr_ );
}
References Element::cinfo(), Eref::data(), Id::element(), Id::eref(), Stoich::getNumAllPools(), Cinfo::isA(), GssaSystem::isReady, pools_, GssaVoxelPools::setStoich(), GssaSystem::stoich, KsolveBase::stoich_, stoichPtr_, and sys_.
Referenced by initCinfo().
updateRateTerms()
void Gsolve::updateRateTerms (unsigned int index) virtual
Rescale specified voxel rate term following rate constant change or volume change. If index == ~0U then does all terms.
Implements KsolveBase.
Definition at line 1122 of file Gsolve.cpp.
{
    if ( index == ~0U )
    {
        // unsigned int numCrossRates = stoichPtr_->getNumRates() - stoichPtr_->getNumCoreRates();
        for ( unsigned int i = 0 ; i < pools_.size(); ++i )
        {
            pools_[i].updateAllRateTerms( stoichPtr_->getRateTerms(),
                    stoichPtr_->getNumCoreRates() );
        }
    }
    else if ( index < stoichPtr_->getNumRates() )
    {
        for ( unsigned int i = 0 ; i < pools_.size(); ++i )
            pools_[i].updateRateTerms( stoichPtr_->getRateTerms(),
                    stoichPtr_->getNumCoreRates(), index );
    }
}
References Stoich::getNumCoreRates(), Stoich::getNumRates(), Stoich::getRateTerms(), pools_, stoichPtr_, GssaVoxelPools::updateAllRateTerms(), and GssaVoxelPools::updateRateTerms().
Referenced by updateVoxelVol().
updateVoxelVol()
void Gsolve::updateVoxelVol (vector< double > vols)
Handles request to change volumes of voxels in this Ksolve, and all cascading effects of this. At this point it won't handle change in size of voxel array.
Definition at line 1107 of file Gsolve.cpp.
{
    // For now we assume identical numbers of voxels. Also assume
    // identical voxel junctions. But it should not be too hard to
    // update those too.
    if ( vols.size() == pools_.size() )
    {
        for ( unsigned int i = 0; i < vols.size(); ++i )
        {
            pools_[i].setVolumeAndDependencies( vols[i] );
        }
        updateRateTerms( ~0U );
    }
}
References pools_, GssaVoxelPools::setVolumeAndDependencies(), and updateRateTerms().
Referenced by initCinfo().
volume()
double Gsolve::volume (unsigned int i) const virtual
Inherited.
Implements KsolveBase.
Definition at line 1150 of file Gsolve.cpp.
{
    if ( pools_.size() > i )
        return pools_[i].getVolume();
    return 0.0;
}
References VoxelPoolsBase::getVolume(), and pools_.
Member Data Documentation
dsolve_
Id Gsolve::dsolve_ private
Id of diffusion solver, needed for coordinating numerics.
Definition at line 171 of file Gsolve.h.
Referenced by Gsolve(), and setDsolve().
dsolvePtr_
KsolveBase* Gsolve::dsolvePtr_ private
Pointer to diffusion solver.
Definition at line 174 of file Gsolve.h.
Referenced by Gsolve(), process(), and setDsolve().
grainSize_
size_t Gsolve::grainSize_ private
Definition at line 149 of file Gsolve.h.
Referenced by process(), and reinit().
numThreads_
size_t Gsolve::numThreads_ private
Number of threads to use when parallel version of Gsolve is used.
Definition at line 148 of file Gsolve.h.
Referenced by getNumThreads(), Gsolve(), process(), reinit(), and setNumThreads().
pools_
vector< GssaVoxelPools > Gsolve::pools_ private
Each VoxelPools entry handles all the pools in a single voxel. Each entry knows how to update itself in order to complete the kinetic calculations for that voxel. The ksolver does multinode management by indexing only the subset of entries present on this node.
Definition at line 160 of file Gsolve.h.
Referenced by advance_chunk(), getBlock(), getConcInit(), getN(), getNumAllVoxels(), getNumFire(), getNumLocalVoxels(), getNumPools(), getNvec(), getR1(), getVolumeOfPool(), getVoxelIndex(), Gsolve(), initReinit(), pools(), process(), rebuildGssaSystem(), recalcTimeChunk(), reinit(), setBlock(), setCompartment(), setConcInit(), setN(), setNumAllVoxels(), setNumPools(), setNvec(), setStoich(), updateRateTerms(), updateVoxelVol(), and volume().
rng_
moose::RNG Gsolve::rng_ private
Definition at line 180 of file Gsolve.h.
Referenced by Gsolve(), and process().
rngSeedOffset_
int Gsolve::rngSeedOffset_ private
Offset * voxIdx is added to rng seed for each voxel to get indept.
Definition at line 183 of file Gsolve.h.
Referenced by getRngSeedOffset(), Gsolve(), initReinit(), reinit(), and setRngSeedOffset().
startVoxel_
unsigned int Gsolve::startVoxel_ private
First voxel indexed on the current node.
Definition at line 163 of file Gsolve.h.
Referenced by getBlock(), getVoxelIndex(), Gsolve(), and setBlock().
stoichPtr_
Stoich* Gsolve::stoichPtr_ private
Utility ptr used to help Pool Id lookups by the Ksolve.
Definition at line 166 of file Gsolve.h.
Referenced by fillIncrementFuncDep(), fillMmEnzDep(), fillPoolFuncDep(), getPoolIndex(), initReinit(), makeReacDepsUnique(), process(), rebuildGssaSystem(), reinit(), setStoich(), and updateRateTerms().
sys_
GssaSystem Gsolve::sys_ private
Definition at line 151 of file Gsolve.h.
Referenced by advance_chunk(), fillIncrementFuncDep(), fillMmEnzDep(), fillPoolFuncDep(), getRandInit(), initReinit(), makeReacDepsUnique(), process(), rebuildGssaSystem(), recalcTimeChunk(), reinit(), setConcInit(), setN(), setNumAllVoxels(), setNumPools(), setNvec(), setRandInit(), and setStoich().
useClockedUpdate_
bool Gsolve::useClockedUpdate_ private
Flag: True if atot should be updated every clock tick.
Definition at line 177 of file Gsolve.h.
Referenced by getClockedUpdate(), Gsolve(), process(), and setClockedUpdate().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/ksolve/Gsolve.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/ksolve/Gsolve.cpp