MOOSE - Multiscale Object Oriented Simulation Environment: Function Class Reference
Function Class Reference
#include <Function.h>
Public Member Functions
void addYs (vector< string > &names)
void clearAll ()
void clearVariables ()
Function ()
bool getAllowUnknowVariable () const
double getConst (string name) const
double getDerivative () const
bool getDoEvalAtReinit () const
double getEval () const
string getExpr (const Eref &e) const
string getIndependent () const
unsigned int getMode () const
unsigned int getNumVar () const
double getRate () const
bool getUseTrigger () const
double getValue () const
unsigned int getVarIndex (string name) const
vector< string > getVars () const
Variable * getX (unsigned int ii)
vector< double > getY () const
bool innerSetExpr (const Eref &e, const string expr)
Function & operator= (const Function &rhs)
void process (const Eref &e, ProcPtr p)
void reinit (const Eref &e, ProcPtr p)
void setAllowUnknownVariable (bool value)
void setConst (string name, double value)
void setDoEvalAtReinit (bool doEvalAtReinit)
void setExpr (const Eref &e, const string expr)
void setIndependent (string index)
void setMode (unsigned int mode)
void setNumVar (unsigned int num)
void setSolver (const Eref &e, ObjId stoich)
void setUseTrigger (bool useTrigger)
void setVar (unsigned int index, double value)
set the value of index-th variable
void setVarIndex (string name, unsigned int val)
void setVarValues (vector< string > vars, vector< double > vals)
bool symbolExists (const string &name) const
~Function ()
Static Public Member Functions
static const Cinfo * initCinfo ()
Static Public Attributes
static const int VARMAX
Protected Attributes
bool allowUnknownVar_
map< string, shared_ptr< double > > consts_
bool doEvalAtReinit_
string independent_
double lastValue_
unsigned int mode_
unsigned int num_xi_ {0}
unsigned int numVar_
moose::MooseParser * parser_ {}
double rate_
void * stoich_
double t_
bool useTrigger_
bool valid_
double value_
map< string, unsigned int > varIndex_
vector< Variable * > xs_ {}
vector< double * > ys_ {}
Detailed Description
Definition at line 23 of file Function.h.
Constructor & Destructor Documentation
Function()
Function::Function ()
Definition at line 331 of file Function.cpp.
                      {n}" are treated as input variables, that
  are requested via the outgoing `requestOut` message from other
  objects' value fields.
- Any name that has already been assigned as a constant (e.g.,
  inserted with `Function.c['name'] = value` or predefined
  mathematical constants like `pi`, `e`) is treated as constant.
- All other names are assumed to be variables and assigned successive
  entries in the `x` field.
Input (independent) variables come from other elements, either pushed
~Function()
Function::~Function ()
Definition at line 395 of file Function.cpp.
Member Function Documentation
addYs()
void Function::addYs (vector< string > & names)
Add ys variable (names of the form "y{digits}")
Parameters
name set of strings of the form "y{digits}"
clearAll()
void Function::clearAll ()
Definition at line 829 of file Function.cpp.
          :
    {
        rateOut()->send(e, rate_);
        lastValue_ = value_;
    break;
    }
    default:
    {
        valueOut()->send(e, value_);
References lastValue_, rate_, rateOut(), SrcFinfo1< T >::send(), and value_.
clearVariables()
void Function::clearVariables ()
Definition at line 815 of file Function.cpp.
    {
    case 1:
    {
        valueOut()->send(e, value_);
        lastValue_ = value_;
    break;
    }
    case 2:
    {
        derivativeOut()->send(e, getDerivative());
        lastValue_ = value_;
        break;
    }
References derivativeOut(), getDerivative(), lastValue_, SrcFinfo1< T >::send(), value_, and valueOut().
getAllowUnknowVariable()
bool Function::getAllowUnknowVariable () const
Definition at line 603 of file Function.cpp.
Referenced by initCinfo().
getConst()
double Function::getConst (string name) const
Definition at line 697 of file Function.cpp.
{
    if (!valid_)
References valid_.
Referenced by initCinfo().
getDerivative()
double Function::getDerivative () const
Definition at line 647 of file Function.cpp.
{
    return mode_;
}
void Function::setUseTrigger(bool useTrigger)
{
    useTrigger_ = useTrigger;
}
References mode_.
Referenced by clearVariables(), and initCinfo().
getDoEvalAtReinit()
bool Function::getDoEvalAtReinit () const
Definition at line 593 of file Function.cpp.
{
        string name = 'x' + to_string(ii);
        xs_[ii] = new Variable(name);
        varIndex_[name] = ii;
Referenced by initCinfo().
getEval()
double Function::getEval () const
Definition at line 616 of file Function.cpp.
                     {
        unsigned int old_yi_count = ys_.size();
References ys_.
Referenced by initCinfo().
getExpr()
string Function::getExpr (const Eref & e) const
Definition at line 557 of file Function.cpp.
{
            others.push_back(name);
        }
    }
    std::sort(xs.begin(), xs.end());
    std::sort(ys.begin(), ys.end());
    std::sort(others.begin(), others.end());
    // keep the existing variables aside for relocation
Referenced by initCinfo().
getIndependent()
string Function::getIndependent () const
Definition at line 634 of file Function.cpp.
{
    if (!valid_) {
        cerr << __func__ << " Error: " << e.objId().path()
             << "::getExpr() - invalid parser state. Assign a correct "
References Eref::objId(), ObjId::path(), and valid_.
Referenced by initCinfo().
getMode()
unsigned int Function::getMode () const
Definition at line 573 of file Function.cpp.
Referenced by initCinfo().
getNumVar()
unsigned int Function::getNumVar () const
Definition at line 666 of file Function.cpp.
Referenced by initCinfo().
getRate()
double Function::getRate () const
Definition at line 622 of file Function.cpp.
{
                ys_[ii] = new double(0.0);
                parser_->DefineVar('y' + to_string(ii), ys_[ii]);
            }
        }
Referenced by initCinfo().
getUseTrigger()
bool Function::getUseTrigger () const
Definition at line 583 of file Function.cpp.
Referenced by initCinfo().
getValue()
double Function::getValue () const
Definition at line 610 of file Function.cpp.
{
        unsigned int idx = num_xi_ + known.size() + ii;
        xs_[idx] = new Variable(new_named[ii]);
        parser_->DefineVar(new_named[ii], xs_[idx]->ptr());
Referenced by initCinfo().
getVarIndex()
unsigned int Function::getVarIndex (string name) const
Definition at line 707 of file Function.cpp.
{
    return independent_;
Referenced by initCinfo().
getVars()
vector< string > Function::getVars () const
getX()
Variable * Function::getX (unsigned int ii)
Definition at line 681 of file Function.cpp.
                                            : deprecated" << endl;
    return true;
}
double Function::getValue() const
{
    // return parser_->Eval( );
    return value_;
}
Referenced by initCinfo().
getY()
vector< double > Function::getY () const
Definition at line 639 of file Function.cpp.
{
Referenced by initCinfo().
initCinfo()
const Cinfo * Function::initCinfo () static
Definition at line 66 of file Function.cpp.
{
    // Value fields
    static  ReadOnlyValueFinfo< Function, double > value(
        "value",
        "Value calculated in the last evaluation of the function. This gets"
    " updated in each simulation step.",
        &Function::getValue
    );
    static  ReadOnlyValueFinfo< Function, double > evalResult(
        "evalResult",
        "Result of the function evaluation with current variable values. This"
    " can be used for evaluating the function without running a simulation"
    " step.",
        &Function::getEval
    );
    static ReadOnlyValueFinfo< Function, double > derivative(
        "derivative",
        "Derivative of the function at given variable values. This is calulated"
        " using 5-point stencil "
        " <http://en.wikipedia.org/wiki/Five-point_stencil> at current value of"
        " independent variable. Note that unlike hand-calculated derivatives,"
        " numerical derivatives are not exact.",
        &Function::getDerivative
    );
    static ReadOnlyValueFinfo< Function, double > rate(
        "rate",
        "Derivative of the function at given variable values. This is computed"
        " as the difference of the current and previous value of the function"
        " divided by the time step.",
        &Function::getRate
    );
    static ValueFinfo< Function, unsigned int > mode(
        "mode",
        "Mode of operation (default 1): \n"
        " 1: only the function value will be sent out.\n"
        " 2: only the derivative with respect to the independent variable will be sent out.\n"
        " 3: only rate (time derivative) will be sent out.\n"
        " anything else: all three, value, derivative and rate will be sent out.\n",
        &Function::setMode,
        &Function::getMode
    );
    static ValueFinfo< Function, bool > useTrigger(
        "useTrigger",
        "When *false*, disables event-driven calculation and turns on "
        "Process-driven calculations. \n"
        "When *true*, enables event-driven calculation and turns off "
        "Process-driven calculations. \n"
        "Defaults to *false*. \n",
        &Function::setUseTrigger,
        &Function::getUseTrigger
    );
    static ValueFinfo< Function, bool > doEvalAtReinit(
        "doEvalAtReinit",
        "Deprecated: This does not have any use."
    "When *false*, disables function evaluation at reinit, and "
        "just emits a value of zero to any message targets. \n"
        "When *true*, does a function evaluation at reinit and sends "
        "the computed value to any message targets. \n"
        "Defaults to *false*. \n",
        &Function::setDoEvalAtReinit,
        &Function::getDoEvalAtReinit
    );
    static ValueFinfo< Function, bool > allowUnknownVariable(
        "allowUnknownVariable",
        "DEPRECATED: When *false*, expression can only have ci, xi, yi and t."
        "When set to *true*, expression can have arbitrary names."
        "Defaults to *true*.\n",
        &Function::setAllowUnknownVariable,
        &Function::getAllowUnknowVariable
    );
    static ElementValueFinfo< Function, string > expr(
        "expr",
        "Mathematical expression defining the function. The underlying parser\n"
        "is exprtk (https://archive.codeplex.com/?p=exprtk) . In addition to the\n"
        "available functions and operators  from exprtk, a few functions are added.\n"
        "\nMajor Functions\n"
        "Name        args    explanation\n"
        "sin         1       sine function\n"
        "cos         1       cosine function\n"
        "tan         1       tangens function\n"
        "asin        1       arcus sine function\n"
        "acos        1       arcus cosine function\n"
        "atan        1       arcus tangens function\n"
        "sinh        1       hyperbolic sine function\n"
        "cosh        1       hyperbolic cosine\n"
        "tanh        1       hyperbolic tangens function\n"
        "asinh       1       hyperbolic arcus sine function\n"
        "acosh       1       hyperbolic arcus tangens function\n"
        "atanh       1       hyperbolic arcur tangens function\n"
        "log2        1       logarithm to the base 2\n"
        "log10       1       logarithm to the base 10\n"
        "log         1       logarithm to the base 10\n"
        "ln          1       logarithm to base e (2.71828...)\n"
        "exp         1       e raised to the power of x\n"
        "sqrt        1       square root of a value\n"
        "sign        1       sign function -1 if x<0; 1 if x>0\n"
        "abs         1       absolute value\n"
        "min         var.    min of all arguments\n"
        "max         var.    max of all arguments\n"
        "sum         var.    sum of all arguments\n"
        "avg         var.    mean value of all arguments\n"
        "rnd         0       rand(), random float between 0 and 1, honors global moose.seed.\n"
        "rand        1       rand(seed), random float between 0 and 1, \n"
        "                    if seed = -1, then a 'random' seed is used.\n"
        "rand2       3       rand(a, b, seed), random float between a and b, \n"
        "                    if seed = -1, a 'random' seed is created using either\n"
        "                    by random_device or by reading system clock\n"
        "\nOperators\n"
        "Op  meaning                      priority\n"
        "=   assignment                     -1\n"
        "&&,and  logical and                1\n"
        "||,or  logical or                  2\n"
        "<=  less or equal                  4\n"
        ">=  greater or equal               4\n"
        "!=,not  not equal                  4\n"
        "==  equal                          4\n"
        ">   greater than                   4\n"
        "<   less than                      4\n"
        "+   addition                       5\n"
        "-   subtraction                    5\n"
        "*   multiplication                 6\n"
        "/   division                       6\n"
        "^   raise x to the power of y      7\n"
        "%   floating point modulo          7\n"
        "\n"
        "?:  if then else operator          C++ style syntax\n"
        "\n\n"
        "For more information see https://archive.codeplex.com/?p=exprtk \n",
        &Function::setExpr,
        &Function::getExpr
    );
    static ReadOnlyValueFinfo< Function, unsigned int > numVars(
        "numVars",
        "Number of variables used by Function. It is determined by parsing"
    " when `expr` is set",
        &Function::getNumVar
    );
    static FieldElementFinfo< Function, Variable > inputs(
        "x",
        "Input variables (indexed) to the function."
    " The values can be passed via messages to the `input` field on each"
    " entry.",
        Variable::initCinfo(),
        &Function::getX,
        &Function::setNumVar,
        &Function::getNumVar
    );
    static LookupValueFinfo < Function, string, double > constants(
        "c",
        "Constants used in the function. These must be assigned before"
        " specifying the function expression.",
        &Function::setConst,
        &Function::getConst
    );
    static LookupValueFinfo< Function, string, unsigned int > xindex(
        "xindex",
        "Returns the index of a given variable which can be used with field `x`."
        " Note that we have a mechanism to map string (variable name) to integer "
        " (variable index).",
        &Function::setVarIndex,
        &Function::getVarIndex
    );
    static ReadOnlyValueFinfo< Function, vector < double > > y(
        "y",
        "Variable values received from target fields by 'requestOut' message",
        &Function::getY
    );
    static ValueFinfo<Function, string> independent(
        "independent",
        "Index of independent variable. Differentiation is done based on this."
        " Defaults to the first assigned variable.",
        &Function::setIndependent,
        &Function::getIndependent
    );
    static DestFinfo setSolver( "setSolver",
        "Assigns solver to this Function.",
        new EpFunc1< Function, ObjId >( &Function::setSolver ) );
    // Shared messages
    static DestFinfo process( "process",
            "Handles process call, updates internal time stamp.",
            new ProcOpFunc< Function >( &Function::process )
            );
    static DestFinfo reinit( "reinit",
            "Handles reinit call.",
            new ProcOpFunc< Function >( &Function::reinit )
            );
    static Finfo* processShared[] = { &process, &reinit };
    static SharedFinfo proc( "proc",
            "This is a shared message to receive Process messages "
            "from the scheduler objects."
            "The first entry in the shared msg is a MsgDest "
            "for the Process operation. It has a single argument, "
            "ProcInfo, which holds lots of information about current "
            "time, thread, dt and so on. The second entry is a MsgDest "
            "for the Reinit operation. It also uses ProcInfo. ",
            processShared, sizeof( processShared ) / sizeof( Finfo* )
            );
    static Finfo *functionFinfos[] = {
        &value,
    &evalResult,
        &rate,
        &derivative,
        &mode,
        &useTrigger,
        &doEvalAtReinit,
        &allowUnknownVariable,
        &expr,
        &numVars,
        &inputs,
        &xindex,
        &constants,
        &independent,
    &setSolver,         // DestFinfo
        &proc,
        requestOut(),
        valueOut(),
        rateOut(),
        derivativeOut(),
    };
    static string doc[] = {
        "Name", "Function", "Author", "Subhasis Ray/Dilawar Singh",
        "Description",
        R"#(
General purpose function calculator using real numbers.
It can parse mathematical expression defining a function and evaluate it and/or
its derivative for specified variable values.  You can assign expressions of
the form::
 f(t, x, y, var, p, q, Ca, CaMKII)
NOTE: `t` represents time. You CAN NOT use to for any other purpose.
The constants must be defined before setting the expression using
the lookup field `c`. Once set, their values cannot be changed.
References derivativeOut(), DestFinfo::DestFinfo(), ElementValueFinfo< T, F >::ElementValueFinfo(), EpFunc1< T, A >::EpFunc1(), FieldElementFinfo< T, F >::FieldElementFinfo(), getAllowUnknowVariable(), getConst(), getDerivative(), getDoEvalAtReinit(), getEval(), getExpr(), getIndependent(), getMode(), getNumVar(), getRate(), getUseTrigger(), getValue(), getVarIndex(), getX(), getY(), Variable::initCinfo(), LookupValueFinfo< T, L, F >::LookupValueFinfo(), process(), ProcOpFunc< T >::ProcOpFunc(), rateOut(), ReadOnlyValueFinfo< T, F >::ReadOnlyValueFinfo(), reinit(), requestOut(), setAllowUnknownVariable(), setConst(), setDoEvalAtReinit(), setExpr(), setIndependent(), setMode(), setNumVar(), setSolver(), setUseTrigger(), setVarIndex(), SharedFinfo::SharedFinfo(), ValueFinfo< T, F >::ValueFinfo(), and valueOut().
innerSetExpr()
bool Function::innerSetExpr (const Eref & e, const string expr)
@Synopsis Set expression in the parser. This function support two mode: with dynamic lookup and without it. When dynamicLookup_ is set to true, unknown variables are created at the compile time. Otherwise, an error is raised.
@Param eref @Param expr Expression to set. @Param dynamicLookup Whether to allow unknown variables in the expression. (default to true in moose>=4.0.0)
@Returns True if compilation was successful.
Definition at line 454 of file Function.cpp.
                     : rhs.xs_) {
            xs_.push_back(new Variable(x->getName()));
            varIndex_[x->getName()] = xs_.size() - 1;
            parser_->DefineVar(xs_.back()->getName(), xs_.back()->ptr());
        }
        // Add all the Ys now.
        for (unsigned int i = 0; i < rhs.ys_.size(); i++) {
            ys_.push_back(new double(0.0));
            parser_->DefineVar('y' + to_string(i), ys_[i]);
        }
        parser_->DefineVar("t", &t_);
        parser_->SetExpr(rhs.parser_->GetExpr());
    }
    return *this;
}
Function::~Function()
{
    for (auto *x : xs_) {
        delete x;
    }
    for (auto *y : ys_) {
        delete y;
    }
    delete parser_;
}
/* --------------------------------------------------------------------------*/
/* ----------------------------------------------------------------------------*/
void Function::setExpr(const Eref& eref, const string expression)
{
    string expr = moose::trim(expression);
    if(expr.empty())
        return;
    expr = moose::MooseParser::Reformat(expr);
    if (valid_ && expr == parser_->GetExpr()) {
        MOOSE_WARN("No changes in the expression.");
        return;
    }
    try
    {
        valid_ = innerSetExpr(eref, expr);
    }
    catch (moose::Parser::ParserException &e) {
        clearAll();
        valid_ = false;
        cerr << "Error setting expression on: " << eref.objId().path() << endl;
        cerr << "\tExpression: '" << expr << "'" << endl;
        cerr << e.GetMsg() << endl;
    }
}
/* --------------------------------------------------------------------------*/
/* ----------------------------------------------------------------------------*/
bool Function::innerSetExpr(const Eref& eref, const string expr)
{
    ASSERT_FALSE(expr.empty(), "Empty expression not allowed here.");
    // NOTE: Don't clear the expression here. Sometime the user extend the
    // expression by calling this function agian. For example:
    //
    // >>> f.expr = 'x0+x2'
    // >>> # connect x0 and x2
    // >>> f.expr += '+ 100+y0'
    // >>> # connect more etc.
    // First, add the xi, yi and t to the symbol table.
    vector<string> vars;
    parser_->ParseVariables(expr, vars);
    vector<string> xs;      // variable names x0, x1, ...
    vector<string> ys;      // variable names y0, y1, ...
    vector<string> others;  // all other variable names
    const regex xpattern("x\\d+");
    const regex ypattern("y\\d+");
    smatch sm;
    for (auto &name : vars) {
        if (regex_search(name, sm, xpattern)) {
            xs.push_back(name);
        }
        else if (regex_search(name, sm, ypattern)) {
References moose::MooseParser::DefineVar(), Variable::getName(), parser_, Variable::ptr(), Variable::Variable(), varIndex_, and xs_.
operator=()
Function & Function::operator= (const Function & rhs)
Definition at line 350 of file Function.cpp.
                                                  {field}`, the object has
a corresponding dest field `get{Field}`. The "requestOut" src field is
connected to this.
This class handles only real numbers (C-double). Predefined constants
are: pi=3.141592..., e=2.718281...
Example::
The following python example illustrates a Function which has a user-defined
constant 'A', two pushed variables, 'Vm' and 'n', which come from a
compartment object, and one pulled variable 'y0', which is read from
the 'diameter' field of the compartment. It also uses the global mathematical
constant 'pi'.
  comp = moose.Compartment('comp')
  comp.diameter = 2.0
  pool = moose.Pool('pool')
  func = moose.Function('f')
  # A made-up example to illustrate push, pull vars and constants
  func.c['A'] = 6.022e23   # constant
  func.expr = 'Vm + y0 * n * pi / A'
  i_v = func.xindex['Vm']
  i_n = func.xindex['n']
  # There should be two x vars, one for `Vm`, the other for `n`
  assert func.x.num == 2
  moose.connect(comp, 'VmOut', func.x[i_v], 'input')
  moose.conncet(pool, 'nOut', func.x[i_n], 'input')
  moose.connect(func, 'requestOut', comp, 'getDiameter')
)#"
    };
    static Dinfo< Function > dinfo;
process()
void Function::process (const Eref & e, ProcPtr p)
Definition at line 719 of file Function.cpp.
{
    double value = 0.0;
    if (!valid_) {
        cerr << __func__ << "Error:  invalid state" << endl;
    }
    else {
        value = parser_->Derivative(independent_);
    }
    return value;
}
void Function::setNumVar(const unsigned int num)
{
    // Deprecated: numVar has no effect. MOOSE infer number of variables
    // from the expression.
    cerr << "Function::setNumVar is deprecated. Function object infers number of variables from the expression." << endl;
}
unsigned int Function::getNumVar() const
{
    return xs_.size();
}
void Function::setVar(unsigned int index, double value)
{
    if(index < xs_.size())
    {
        xs_[index]->setValue(value);
        return;
    }
    MOOSE_WARN("Function: index " << index << " out of bounds.");
}
Variable* Function::getX(unsigned int ii)
{
    static Variable dummy("DUMMY");
    if(ii >= xs_.size())
    {
        //MOOSE_WARN("No active variable for index " << ii);
        return &dummy;
    }
    return xs_[ii];
}
Referenced by initCinfo().
reinit()
void Function::reinit (const Eref & e, ProcPtr p)
Definition at line 769 of file Function.cpp.
{
    parser_->DefineConst(name.c_str(), value);
}
double Function::getConst(string name) const
{
    return parser_->GetConst(name);
}
void Function::setVarIndex(string name, unsigned int val)
{
    cerr << "Function::setVarIndex : This should not be used." << endl;
}
unsigned int Function::getVarIndex(string name) const
{
    if(varIndex_.find(name) == varIndex_.end())
        return numeric_limits<unsigned int>::max();
    return varIndex_.at(name);
}
bool Function::symbolExists(const string& name) const
{
    return varIndex_.find(name) != varIndex_.end();
}
void Function::process(const Eref &e, ProcPtr p)
{
    if(! valid_)
        return;
    // Update values of incoming variables.
    vector<double> databuf;
    requestOut()->send(e, &databuf);
    for (unsigned int ii = 0; (ii < databuf.size()) && (ii < ys_.size()); ++ii)
        *ys_[ii] = databuf[ii];
    t_ = p->currTime;
    value_ = getEval();
    rate_ = (value_ - lastValue_) / p->dt;
    if (useTrigger_ && value_ < TriggerThreshold) {
        lastValue_ = value_;
        return;
References moose::MooseParser::DefineConst(), and parser_.
Referenced by initCinfo().
setAllowUnknownVariable()
void Function::setAllowUnknownVariable (bool value)
Definition at line 598 of file Function.cpp.
{
Referenced by initCinfo().
setConst()
void Function::setConst (string name, double value)
Definition at line 692 of file Function.cpp.
{
    return parser_->Eval( );
}
References moose::MooseParser::Eval(), and parser_.
Referenced by initCinfo().
setDoEvalAtReinit()
void Function::setDoEvalAtReinit (bool doEvalAtReinit)
Definition at line 588 of file Function.cpp.
Referenced by initCinfo().
setExpr()
void Function::setExpr (const Eref & e, const string expr)
@Synopsis Assign an expression to the parser. Calls innerSetExpr to do the task.
@Param eref @Param expression
Definition at line 415 of file Function.cpp.
{
}
// Careful: This is a critical function. Also since during zombiefication, deep
// copy is expected. Merely copying the parser won't work.
Function& Function::operator=(const Function& rhs)
{
    // protect from self-assignment.
    if( this == &rhs)
        return *this;
    // delete allocated vars, clear parser
    clearAll();
    valid_ = rhs.valid_;
    lastValue_ = rhs.lastValue_;
    value_ = rhs.value_;
Referenced by initCinfo().
setIndependent()
void Function::setIndependent (string index)
Definition at line 629 of file Function.cpp.
Referenced by initCinfo().
setMode()
void Function::setMode (unsigned int mode)
Definition at line 568 of file Function.cpp.
                     {
        unsigned int num_xi_new = std::stoul(xs.back().substr(1)) + 1;
        if (num_xi_new > num_xi_) {
Referenced by initCinfo().
setNumVar()
void Function::setNumVar (unsigned int num)
Definition at line 659 of file Function.cpp.
{
    return useTrigger_;
}
void Function::setDoEvalAtReinit(bool doEvalAtReinit)
References useTrigger_.
Referenced by initCinfo().
setSolver()
void Function::setSolver (const Eref & e, ObjId stoich)
Definition at line 839 of file Function.cpp.
{
    if (! (valid_ || parser_->GetExpr().empty()))
    {
        MOOSE_WARN("Error: " << e.objId().path() << "::reinit() - invalid parser state"
                << endl << " Expr: '" << parser_->GetExpr() << "'.");
        return;
    }
    t_ = p->currTime;
    if (doEvalAtReinit_){
        lastValue_ = value_ = getEval();
    }
    else
        lastValue_ = value_ = 0.0;
    rate_ = 0.0;
    switch (mode_){
    case 1:
    {
        valueOut()->send(e, value_);
        break;
    }
    case 2:
    {
        derivativeOut()->send(e, 0.0);
Referenced by initCinfo().
setUseTrigger()
void Function::setUseTrigger (bool useTrigger)
Definition at line 578 of file Function.cpp.
Referenced by initCinfo().
setVar()
void Function::setVar (unsigned int index, double value)
set the value of index-th variable
Definition at line 671 of file Function.cpp.
{
    cerr << "Function::setAllowUnknownVariable: deprecated" << endl;
}
bool Function::getAllowUnknowVariable() const
setVarIndex()
void Function::setVarIndex (string name, unsigned int val)
Definition at line 702 of file Function.cpp.
Referenced by initCinfo().
setVarValues()
void Function::setVarValues (vector< string > vars, vector< double > vals)
symbolExists()
bool Function::symbolExists (const string & name) const
Definition at line 714 of file Function.cpp.
{
    vector < double > ret(ys_.size());
References ys_.
Member Data Documentation
allowUnknownVar_
bool Function::allowUnknownVar_ protected
Definition at line 128 of file Function.h.
consts_
map<string, shared_ptr<double> > Function::consts_ protected
Definition at line 147 of file Function.h.
doEvalAtReinit_
bool Function::doEvalAtReinit_ protected
Definition at line 127 of file Function.h.
independent_
string Function::independent_ protected
Definition at line 131 of file Function.h.
lastValue_
double Function::lastValue_ protected
Definition at line 122 of file Function.h.
Referenced by clearAll(), and clearVariables().
mode_
unsigned int Function::mode_ protected
Definition at line 125 of file Function.h.
Referenced by getDerivative().
num_xi_
unsigned int Function::num_xi_ {0} protected
last index of the x{i} vars - to track boundary of indexed and named variables
Definition at line 142 of file Function.h.
{0};
numVar_
unsigned int Function::numVar_ protected
Definition at line 121 of file Function.h.
parser_
moose::MooseParser* Function::parser_ {} protected
Definition at line 153 of file Function.h.
{};
Referenced by innerSetExpr(), reinit(), and setConst().
rate_
double Function::rate_ protected
Definition at line 124 of file Function.h.
Referenced by clearAll().
stoich_
void* Function::stoich_ protected
Definition at line 150 of file Function.h.
t_
double Function::t_ protected
Definition at line 130 of file Function.h.
useTrigger_
bool Function::useTrigger_ protected
Definition at line 126 of file Function.h.
Referenced by setNumVar().
valid_
bool Function::valid_ protected
Definition at line 120 of file Function.h.
Referenced by getConst(), and getIndependent().
value_
double Function::value_ protected
Definition at line 123 of file Function.h.
Referenced by clearAll(), and clearVariables().
varIndex_
map<string, unsigned int> Function::varIndex_ protected
Definition at line 138 of file Function.h.
Referenced by innerSetExpr().
VARMAX
const int Function::VARMAX static
Definition at line 26 of file Function.h.
xs_
vector<Variable*> Function::xs_ {} protected
Definition at line 135 of file Function.h.
{};
Referenced by innerSetExpr().
ys_
vector<double*> Function::ys_ {} protected
Definition at line 146 of file Function.h.
{};
Referenced by getEval(), and symbolExists().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/builtins/Function.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/builtins/Function.cpp