MOOSE - Multiscale Object Oriented Simulation Environment: FuncReac Class Reference
FuncReac Class Reference
#include <FuncRateTerm.h>
Public Member Functions
RateTerm * copyWithVolScaling (double vol, double sub, double prd) const
FuncReac (double k, vector< unsigned int > v)
unsigned int getReactants (vector< unsigned int > &molIndex) const
double operator() (const double *S) const
Computes the rate. The argument is the molecule array.
void rescaleVolume (short comptIndex, const vector< short > &compartmentLookup, double ratio)
void setReactants (const vector< unsigned int > &molIndex)
Public Member Functions inherited from FuncRate
FuncRate (double k, unsigned int targetPoolIndex)
const string & getExpr () const
const vector< unsigned int > & getFuncArgIndex ()
double getR1 () const
Used by Zombie to return rate terms.
void setExpr (const string &s)
void setFuncArgIndex (const vector< unsigned int > &mol)
void setReactants (const vector< unsigned int > &molIndex)
Public Member Functions inherited from ExternReac
double getR2 () const
Used by Zombie to return rate terms.
void rescaleVolume (short comptIndex, const vector< short > &compartmentLookup, double ratio)
void setR1 (double k1)
Used by Zombie to assign rate terms.
void setR2 (double k2)
Used by Zombie to assign rate terms.
void setRates (double k1, double k2)
Public Member Functions inherited from RateTerm
RateTerm ()
virtual ~RateTerm ()
Private Attributes
unsigned int numSubstrates_
vector< unsigned int > v_
Additional Inherited Members
Static Public Attributes inherited from RateTerm
static const double EPSILON = 1.0e-6
Protected Attributes inherited from FuncRate
shared_ptr< FuncTerm > func_
double funcVolPower_
double k_
Detailed Description
This FuncReac manages a one-way NOrder reaction whose rate is determined by a Function, but which also has regular substrates and products.
dproduct/dt = func(x0, x1, x2..., t) * [sub0] * [sub1] * ....
The values x0, x1, x2 are expected to be concentrations so that they do not depend on volume. The substrates sub0, sub1, ... are # of molecules. The term k_ is scaled so that it is unity at vol = 1/NA m^3. k_ = (NA * vol)^(numSub-1) The copyWithVolScaling operation scales it up and down from there.
Definition at line 105 of file FuncRateTerm.h.
Constructor & Destructor Documentation
FuncReac()
FuncReac::FuncReac (double k, vector< unsigned int > v) inline
Definition at line 108 of file FuncRateTerm.h.
            : FuncRate( k, 0 ),
            v_( v )
        {;}
References FuncRate::FuncRate(), and v_.
Referenced by copyWithVolScaling(), and Stoich::installAndUnschedFuncReac().
Member Function Documentation
copyWithVolScaling()
RateTerm * FuncReac::copyWithVolScaling (double vol, double sub, double prd) const inline virtual
Duplicates rate term and then applies volume scaling. Arguments are volume of reference voxel, product of vol/refVol for all substrates: applied to R1 product of vol/refVol for all products: applied to R2
Note that unless the reaction is cross-compartment, the vol/refVol will be one.
Reimplemented from FuncRate.
Definition at line 148 of file FuncRateTerm.h.
        {
            assert( v_.size() > 0 );
            double ratio = sub * pow( NA * vol,
                            funcVolPower_ + (int)( v_.size() ) - 1 );
            FuncReac* ret = new FuncReac( k_ / ratio, v_ );
            ret->func_ = func_;
            ret->funcVolPower_ = funcVolPower_;
            return ret;
        }
References FuncRate::func_, FuncReac(), FuncRate::funcVolPower_, FuncRate::k_, NA, and v_.
getReactants()
unsigned int FuncReac::getReactants (vector< unsigned int > & molIndex) const inline virtual
This function finds the reactant indices in the vector S. It returns the number of substrates found, which are the first entries in molIndex. The products are the remaining ones. Note that it does NOT find products for unidirectional reactions, which is a bit of a problem.
Reimplemented from FuncRate.
Definition at line 127 of file FuncRateTerm.h.
        {
            molIndex = v_;
            return numSubstrates_;
        }
References numSubstrates_, and v_.
operator()()
double FuncReac::operator() (const double * S) const inline virtual
Computes the rate. The argument is the molecule array.
Reimplemented from FuncRate.
Definition at line 113 of file FuncRateTerm.h.
        {
            // double ret = k_ * func_( S, 0.0 ); // get rate from func calculation.
            double t = Field< double >::get( Id(1), "currentTime" );
            double ret = (*func_)( S, t ); //get rate from func calculation.
            *(const_cast< double * >( &k_ ) ) = ret;
            vector< unsigned int >::const_iterator i;
            for ( i = v_.begin(); i != v_.end(); i++) {
                assert( !std::isnan( S[ *i ] ) );
                ret *= S[ *i ];
            }
            return ret;
        }
References FuncRate::func_, Field< A >::get(), Id::Id(), FuncRate::k_, FuncTerm::operator()(), and v_.
rescaleVolume()
void FuncReac::rescaleVolume (short comptIndex, const vector< short > & compartmentLookup, double ratio) inline
Definition at line 138 of file FuncRateTerm.h.
        {
            for ( unsigned int i = 1; i < v_.size(); ++i ) {
                if ( comptIndex == compartmentLookup[ v_[i] ] )
                    k_ /= ratio;
            }
        }
References FuncRate::k_, and v_.
setReactants()
void FuncReac::setReactants (const vector< unsigned int > & molIndex) inline
Definition at line 133 of file FuncRateTerm.h.
        {
            v_ = molIndex;
        }
References v_.
Member Data Documentation
numSubstrates_
unsigned int FuncReac::numSubstrates_ private
Definition at line 162 of file FuncRateTerm.h.
Referenced by getReactants().
v_
vector< unsigned int > FuncReac::v_ private
Definition at line 161 of file FuncRateTerm.h.
Referenced by copyWithVolScaling(), FuncReac(), getReactants(), operator()(), rescaleVolume(), and setReactants().
The documentation for this class was generated from the following file:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/ksolve/FuncRateTerm.h