MOOSE - Multiscale Object Oriented Simulation Environment: Conv< vector< vector< T > > > Class Template Reference
Conv< vector< vector< T > > > Class Template Reference
#include <Conv.h>
Static Public Member Functions
static const vector< vector< T > > buf2val (double **buf)
static string rttiType ()
static unsigned int size (const vector< vector< T > > &val)
static void str2val (vector< vector< T > > &val, const string &s)
static void val2buf (const vector< vector< T > > &val, double **buf)
static void val2str (string &s, const vector< vector< T > > &val)
Detailed Description
template<class T>
class Conv< vector< vector< T > > >
Still more specialized partial specialization. This works with any field that has a uniform size. Assume strings are the only exception. The first double in the vector vec_ holds the # of data entries that follow it. This excludes the space for the size entry itself. This can be a ragged array: the number of entries in each vector need not be the same. The order of entries is: 0 : Dimension of left index, can be zero. As double. 1:numDim : Dimensions of right index. Any and all can be zero. Double. numDim+1 to total: Data, in condensed format.
Definition at line 548 of file Conv.h.
Member Function Documentation
buf2val()
template<class T > static const vector< vector< T > > Conv< vector< vector< T > > >::buf2val (double ** buf) inline static
Definition at line 565 of file Conv.h.
        {
            static vector< vector< T > > ret;
            ret.clear();
            unsigned int numEntries = (unsigned int)**buf; // first entry is vec size
            ret.resize( numEntries );
            (*buf)++;
            for ( unsigned int i = 0; i < numEntries; ++i ) {
          unsigned int rowSize = (unsigned int)**buf;
                (*buf)++;
                for ( unsigned int j = 0; j < rowSize; ++j )
                    ret[i].push_back( Conv< T >::buf2val( buf ) );
            }
            return ret;
        }
Referenced by testConvVectorOfVectors().
rttiType()
template<class T > static string Conv< vector< vector< T > > >::rttiType () inline static
Definition at line 601 of file Conv.h.
{
            string ret = "vector< vector<" + Conv< T >::rttiType() + "> >";
            return ret;
        }
size()
template<class T > static unsigned int Conv< vector< vector< T > > >::size (const vector< vector< T > > & val) inline static
Definition at line 551 of file Conv.h.
        {
            unsigned int ret = 1 + val.size();
            for ( unsigned int i = 0; i < val.size(); ++i ) {
                if ( val[i].size() > 0 ) {
                    ret += val[i].size() * Conv< T >::size( val[i][0] );
                } else  {
                    T temp = T();
                    ret += val[i].size() * Conv< T >::size( temp );
                }
            }
            return ret;
        }
Referenced by testConvVectorOfVectors().
str2val()
template<class T > static void Conv< vector< vector< T > > >::str2val (vector< vector< T > > & val, const string & s) inline static
Definition at line 594 of file Conv.h.
{
            cout << "Specialized Conv< vector< vector< T > > >::str2val not done\n";
        }
val2buf()
template<class T > static void Conv< vector< vector< T > > >::val2buf (const vector< vector< T > > & val, double ** buf) inline static
Definition at line 581 of file Conv.h.
        {
            double* temp = *buf;
            *temp++ = (double)val.size();
            for( unsigned int i = 0; i < val.size(); ++i ) {
          *temp++ = (double)val[i].size();
                for ( unsigned int j = 0; j < val[i].size(); ++j ) {
                    Conv< T >::val2buf( val[i][j], &temp );
                }
            }
            *buf = temp;
        }
Referenced by testConvVectorOfVectors().
val2str()
template<class T > static void Conv< vector< vector< T > > >::val2str (string & s, const vector< vector< T > > & val) inline static
Definition at line 598 of file Conv.h.
{
            cout << "Specialized Conv< vector< vector< T > > >::val2str not done\n";
        }
The documentation for this class was generated from the following file:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/basecode/Conv.h