MOOSE - Multiscale Object Oriented Simulation Environment: ProcOpFunc< T > Class Template Reference
ProcOpFunc< T > Class Template Reference
#include <ProcOpFunc.h>
Public Member Functions
ProcOpFunc (void(T::*func)(const Eref &e, ProcPtr))
string rttiType () const
Public Member Functions inherited from EpFunc1< T, ProcPtr >
EpFunc1 (void(T::*func)(const Eref &, ProcPtr))
void op (const Eref &e, ProcPtr arg) const
Public Member Functions inherited from OpFunc1Base< A >
bool checkFinfo (const Finfo *s) const
const OpFunc * makeHopFunc (HopIndex hopIndex) const
virtual void op (const Eref &e, A arg) const =0
void opBuffer (const Eref &e, double *buf) const
Executes the OpFunc by converting args.
virtual void opVec (const Eref &e, const vector< A > &arg, const OpFunc1Base< A > *op) const
void opVecBuffer (const Eref &e, double *buf) const
Executes the OpFunc for all data by converting a vector of args.
Public Member Functions inherited from OpFunc
OpFunc ()
unsigned int opIndex () const
bool setIndex (unsigned int i)
Used when rebuilding the Fid->OpFunc mapping.
virtual ~OpFunc ()
Additional Inherited Members
Static Public Member Functions inherited from OpFunc
static const OpFunc * lookop (unsigned int opIndex)
static unsigned int rebuildOpIndex ()
cleans out the entire Ops vector. Returns size of orig vector.
Detailed Description
template<class T>
class ProcOpFunc< T >
This specialized set of classes is derived from OpFunc, and is used to handle Process type calls which need to bypass the Queueing system. These include process, reinit, and other intermediate stage process ops.
Definition at line 73 of file ProcOpFunc.h.
Constructor & Destructor Documentation
ProcOpFunc()
template<class T > ProcOpFunc< T >::ProcOpFunc (void(T::*)(const Eref &e, ProcPtr) func) inline
Definition at line 76 of file ProcOpFunc.h.
            : EpFunc1< T, ProcPtr >( func )
            {;}
Referenced by CaConcBase::initCinfo(), ChanBase::initCinfo(), moose::CompartmentBase::initCinfo(), DifBufferBase::initCinfo(), DifShellBase::initCinfo(), GapJunction::initCinfo(), IntFire::initCinfo(), IzhikevichNrn::initCinfo(), MarkovOdeSolver::initCinfo(), MarkovRateTable::initCinfo(), MarkovSolver::initCinfo(), MarkovSolverBase::initCinfo(), MMPump::initCinfo(), RandSpike::initCinfo(), SpikeGen::initCinfo(), moose::VClamp::initCinfo(), Arith::initCinfo(), Function::initCinfo(), Interpol::initCinfo(), SocketStreamer::initCinfo(), Stats::initCinfo(), StimulusTable::initCinfo(), Streamer::initCinfo(), Table::initCinfo(), TimeTable::initCinfo(), DiffAmp::initCinfo(), PIDController::initCinfo(), PulseGen::initCinfo(), RC::initCinfo(), Dsolve::initCinfo(), Cell::initCinfo(), HSolve::initCinfo(), ConcChan::initCinfo(), Gsolve::initCinfo(), Ksolve::initCinfo(), MeshEntry::initCinfo(), Adaptor::initCinfo(), and SynHandlerBase::initCinfo().
Member Function Documentation
rttiType()
template<class T > string ProcOpFunc< T >::rttiType () const inline virtual
Reimplemented from OpFunc1Base< A >.
Definition at line 80 of file ProcOpFunc.h.
{
            return "const ProcInfo*";
        }
The documentation for this class was generated from the following file:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/basecode/ProcOpFunc.h