MOOSE - Multiscale Object Oriented Simulation Environment: moose::CompartmentDataHolder Class Reference
moose::CompartmentDataHolder Class Reference
#include <CompartmentDataHolder.h>
Public Member Functions
CompartmentDataHolder ()
void readData (const CompartmentBase *c, const Eref &e)
void writeData (CompartmentBase *c, const Eref &e)
Private Attributes
double Cm_
double diameter_
double Em_
double initVm_
double inject_
double length_
double Ra_
double Rm_
double x0_
double x_
double y0_
double y_
double z0_
double z_
Detailed Description
Definition at line 19 of file CompartmentDataHolder.h.
Constructor & Destructor Documentation
CompartmentDataHolder()
CompartmentDataHolder::CompartmentDataHolder ()
Definition at line 16 of file CompartmentDataHolder.cpp.
        :
            Cm_( 1.0 ),
            Ra_( 1.0 ),
            Rm_( 1.0 ),
            Em_( -0.06 ),
            initVm_( -0.06 ),
            inject_( 0.0 ),
            diameter_( 1.0e-6 ),
            length_( 100.0e-6 ),
            x0_( 0.0 ),
            y0_( 0.0 ),
            z0_( 0.0 ),
            x_( 0.0 ),
            y_( 0.0 ),
            z_( 0.0 )
{;}
References Cm_, diameter_, Em_, initVm_, inject_, length_, Ra_, Rm_, x0_, x_, y0_, y_, z0_, and z_.
Member Function Documentation
readData()
void CompartmentDataHolder::readData (const CompartmentBase * c, const Eref & e)
Definition at line 35 of file CompartmentDataHolder.cpp.
{
        Cm_ = cb->getCm( er );
        Rm_ = cb->getRm( er );
        Ra_ = cb->getRa( er );
        Em_ = cb->getEm( er );
        initVm_ = cb->getInitVm( er );
        inject_ = cb->getInject( er );
        x0_ = cb->getX0();
        y0_ = cb->getY0();
        z0_ = cb->getZ0();
        x_ = cb->getX();
        y_ = cb->getY();
        z_ = cb->getZ();
        length_ = cb->getLength();
        diameter_ = cb->getDiameter();
}
References Cm_, diameter_, Em_, moose::CompartmentBase::getCm(), moose::CompartmentBase::getDiameter(), moose::CompartmentBase::getEm(), moose::CompartmentBase::getInitVm(), moose::CompartmentBase::getInject(), moose::CompartmentBase::getLength(), moose::CompartmentBase::getRa(), moose::CompartmentBase::getRm(), moose::CompartmentBase::getX(), moose::CompartmentBase::getX0(), moose::CompartmentBase::getY(), moose::CompartmentBase::getY0(), moose::CompartmentBase::getZ(), moose::CompartmentBase::getZ0(), initVm_, inject_, length_, Ra_, Rm_, x0_, x_, y0_, y_, z0_, and z_.
Referenced by moose::CompartmentBase::zombify().
writeData()
void CompartmentDataHolder::writeData (CompartmentBase * c, const Eref & e)
Definition at line 55 of file CompartmentDataHolder.cpp.
{
        cb->setCm( er, Cm_ );
        cb->setRm( er, Rm_ );
        cb->setRa( er, Ra_ );
        cb->setEm( er, Em_ );
        cb->setInitVm( er, initVm_ );
        cb->setInject( er, inject_ );
        cb->setX0( x0_ );
        cb->setY0( y0_ );
        cb->setZ0( z0_ );
        cb->setX( x_ );
        cb->setY( y_ );
        cb->setZ( z_ );
        cb->setLength( length_ );
        cb->setDiameter( diameter_ );
}
References Cm_, diameter_, Em_, initVm_, inject_, length_, Ra_, Rm_, moose::CompartmentBase::setCm(), moose::CompartmentBase::setDiameter(), moose::CompartmentBase::setEm(), moose::CompartmentBase::setInitVm(), moose::CompartmentBase::setInject(), moose::CompartmentBase::setLength(), moose::CompartmentBase::setRa(), moose::CompartmentBase::setRm(), moose::CompartmentBase::setX(), moose::CompartmentBase::setX0(), moose::CompartmentBase::setY(), moose::CompartmentBase::setY0(), moose::CompartmentBase::setZ(), moose::CompartmentBase::setZ0(), x0_, x_, y0_, y_, z0_, and z_.
Referenced by moose::CompartmentBase::zombify().
Member Data Documentation
Cm_
double moose::CompartmentDataHolder::Cm_ private
Definition at line 26 of file CompartmentDataHolder.h.
Referenced by CompartmentDataHolder(), readData(), and writeData().
diameter_
double moose::CompartmentDataHolder::diameter_ private
Definition at line 33 of file CompartmentDataHolder.h.
Referenced by CompartmentDataHolder(), readData(), and writeData().
Em_
double moose::CompartmentDataHolder::Em_ private
Definition at line 29 of file CompartmentDataHolder.h.
Referenced by CompartmentDataHolder(), readData(), and writeData().
initVm_
double moose::CompartmentDataHolder::initVm_ private
Definition at line 30 of file CompartmentDataHolder.h.
Referenced by CompartmentDataHolder(), readData(), and writeData().
inject_
double moose::CompartmentDataHolder::inject_ private
Definition at line 31 of file CompartmentDataHolder.h.
Referenced by CompartmentDataHolder(), readData(), and writeData().
length_
double moose::CompartmentDataHolder::length_ private
Definition at line 34 of file CompartmentDataHolder.h.
Referenced by CompartmentDataHolder(), readData(), and writeData().
Ra_
double moose::CompartmentDataHolder::Ra_ private
Definition at line 27 of file CompartmentDataHolder.h.
Referenced by CompartmentDataHolder(), readData(), and writeData().
Rm_
double moose::CompartmentDataHolder::Rm_ private
Definition at line 28 of file CompartmentDataHolder.h.
Referenced by CompartmentDataHolder(), readData(), and writeData().
x0_
double moose::CompartmentDataHolder::x0_ private
Definition at line 35 of file CompartmentDataHolder.h.
Referenced by CompartmentDataHolder(), readData(), and writeData().
x_
double moose::CompartmentDataHolder::x_ private
Definition at line 38 of file CompartmentDataHolder.h.
Referenced by CompartmentDataHolder(), readData(), and writeData().
y0_
double moose::CompartmentDataHolder::y0_ private
Definition at line 36 of file CompartmentDataHolder.h.
Referenced by CompartmentDataHolder(), readData(), and writeData().
y_
double moose::CompartmentDataHolder::y_ private
Definition at line 39 of file CompartmentDataHolder.h.
Referenced by CompartmentDataHolder(), readData(), and writeData().
z0_
double moose::CompartmentDataHolder::z0_ private
Definition at line 37 of file CompartmentDataHolder.h.
Referenced by CompartmentDataHolder(), readData(), and writeData().
z_
double moose::CompartmentDataHolder::z_ private
Definition at line 40 of file CompartmentDataHolder.h.
Referenced by CompartmentDataHolder(), readData(), and writeData().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/biophysics/CompartmentDataHolder.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/biophysics/CompartmentDataHolder.cpp