MOOSE - Multiscale Object Oriented Simulation Environment: moose::CompartmentBase Class Reference
moose::CompartmentBase Class Reference abstract
#include <CompartmentBase.h>
Public Member Functions
void cable ()
CompartmentBase ()
void displace (double dx, double dy, double dz)
Displaces compartment by specified distance vector.
double getCm (const Eref &e) const
vector< double > getCoords () const
double getDiameter () const
double getEm (const Eref &e) const
double getIm (const Eref &e) const
double getInitVm (const Eref &e) const
double getInject (const Eref &e) const
double getLength () const
double getRa (const Eref &e) const
double getRm (const Eref &e) const
double getVm (const Eref &e) const
double getX () const
double getX0 () const
double getY () const
double getY0 () const
double getZ () const
double getZ0 () const
void handleAxial (double Vm)
void handleChannel (const Eref &e, double Gk, double Ek)
void handleRaxial (double Ra, double Vm)
void initProc (const Eref &e, ProcPtr p)
void initReinit (const Eref &e, ProcPtr p)
void injectMsg (const Eref &e, double current)
void process (const Eref &e, ProcPtr p)
void randInject (const Eref &e, double prob, double current)
bool rangeWarning (const string &field, double value)
void reinit (const Eref &e, ProcPtr p)
void setCm (const Eref &e, double Cm)
void setCoords (vector< double > value)
void setDiameter (double diameter)
void setEm (const Eref &e, double Em)
void setGeomAndElec (const Eref &e, double length, double dia)
Scales electrical values along with setting length, dia.
void setInitVm (const Eref &e, double initVm)
void setInject (const Eref &e, double Inject)
void setLength (double length)
void setRa (const Eref &e, double Ra)
void setRm (const Eref &e, double Rm)
void setVm (const Eref &e, double Vm)
void setX (double value)
void setX0 (double value)
void setY (double value)
void setY0 (double value)
void setZ (double value)
void setZ0 (double value)
void updateLength ()
virtual double vGetCm (const Eref &e) const =0
virtual double vGetEm (const Eref &e) const =0
virtual double vGetIm (const Eref &e) const =0
virtual double vGetInitVm (const Eref &e) const =0
virtual double vGetInject (const Eref &e) const =0
virtual double vGetRa (const Eref &e) const =0
virtual double vGetRm (const Eref &e) const =0
virtual double vGetVm (const Eref &e) const =0
virtual void vHandleAxial (double Vm)=0
virtual void vHandleChannel (const Eref &e, double Gk, double Ek)=0
virtual void vHandleRaxial (double Ra, double Vm)=0
virtual void vInitProc (const Eref &e, ProcPtr p)=0
virtual void vInitReinit (const Eref &e, ProcPtr p)=0
virtual void vInjectMsg (const Eref &e, double current)=0
virtual void vProcess (const Eref &e, ProcPtr p)=0
virtual void vRandInject (const Eref &e, double prob, double current)=0
virtual void vReinit (const Eref &e, ProcPtr p)=0
virtual void vSetCm (const Eref &e, double Cm)=0
virtual void vSetEm (const Eref &e, double Em)=0
virtual void vSetInitVm (const Eref &e, double initVm)=0
virtual void vSetInject (const Eref &e, double Inject)=0
virtual void vSetRa (const Eref &e, double Ra)=0
virtual void vSetRm (const Eref &e, double Rm)=0
virtual void vSetSolver (const Eref &e, Id hsolve)
virtual void vSetVm (const Eref &e, double Vm)=0
virtual ~CompartmentBase ()
Static Public Member Functions
static const Cinfo * initCinfo ()
static SrcFinfo1< double > * VmOut ()
static void zombify (Element *orig, const Cinfo *zClass, Id hsolve)
Private Attributes
double diameter_
double length_
double x0_
double x_
double y0_
double y_
double z0_
double z_
Detailed Description
Definition at line 22 of file CompartmentBase.h.
Constructor & Destructor Documentation
CompartmentBase()
CompartmentBase::CompartmentBase ()
Definition at line 370 of file CompartmentBase.cpp.
{
    x_ = 0.0;
    y_ = 0.0;
    z_ = 0.0;
    x0_ = 0.0;
    y0_ = 0.0;
    z0_ = 0.0;
    diameter_ = 0.0;
    length_ = 0.0;
}
References diameter_, length_, x0_, x_, y0_, y_, z0_, and z_.
~CompartmentBase()
CompartmentBase::~CompartmentBase () virtual
Definition at line 382 of file CompartmentBase.cpp.
{
    ;
}
Member Function Documentation
cable()
void CompartmentBase::cable ()
Dummy function to act as recipient of 'cable' message, which is just for grouping compartments.
Definition at line 651 of file CompartmentBase.cpp.
{
    ;
}
Referenced by initCinfo().
displace()
void CompartmentBase::displace (double dx, double dy, double dz)
Displaces compartment by specified distance vector.
Definition at line 656 of file CompartmentBase.cpp.
{
    x0_ += dx;
    x_ += dx;
    y0_ += dy;
    y_ += dy;
    z0_ += dz;
    z_ += dz;
}
References x0_, x_, y0_, y_, z0_, and z_.
Referenced by initCinfo().
getCm()
double CompartmentBase::getCm (const Eref & e) const
Definition at line 426 of file CompartmentBase.cpp.
{
    return vGetCm( e );
}
References vGetCm().
Referenced by initCinfo(), and moose::CompartmentDataHolder::readData().
getCoords()
vector< double > CompartmentBase::getCoords () const
Definition at line 596 of file CompartmentBase.cpp.
{
    vector< double > ret = { x0_, y0_, z0_, x_, y_, z_, diameter_ };
    return ret;
}
References diameter_, x0_, x_, y0_, y_, z0_, and z_.
Referenced by initCinfo().
getDiameter()
double CompartmentBase::getDiameter () const
Definition at line 483 of file CompartmentBase.cpp.
{
    return diameter_;
}
References diameter_.
Referenced by initCinfo(), and moose::CompartmentDataHolder::readData().
getEm()
double CompartmentBase::getEm (const Eref & e) const
Definition at line 415 of file CompartmentBase.cpp.
{
    return vGetEm( e );
}
References vGetEm().
Referenced by initCinfo(), and moose::CompartmentDataHolder::readData().
getIm()
double CompartmentBase::getIm (const Eref & e) const
Definition at line 453 of file CompartmentBase.cpp.
{
    return vGetIm( e );
}
References vGetIm().
Referenced by initCinfo().
getInitVm()
double CompartmentBase::getInitVm (const Eref & e) const
Definition at line 473 of file CompartmentBase.cpp.
{
    return vGetInitVm( e );
}
References vGetInitVm().
Referenced by initCinfo(), and moose::CompartmentDataHolder::readData().
getInject()
double CompartmentBase::getInject (const Eref & e) const
Definition at line 463 of file CompartmentBase.cpp.
{
    return vGetInject( e );
}
References vGetInject().
Referenced by initCinfo(), and moose::CompartmentDataHolder::readData().
getLength()
double CompartmentBase::getLength () const
Definition at line 503 of file CompartmentBase.cpp.
{
    return length_;
}
References length_.
Referenced by initCinfo(), and moose::CompartmentDataHolder::readData().
getRa()
double CompartmentBase::getRa (const Eref & e) const
Definition at line 448 of file CompartmentBase.cpp.
{
    return vGetRa( e );
}
References vGetRa().
Referenced by initCinfo(), and moose::CompartmentDataHolder::readData().
getRm()
double CompartmentBase::getRm (const Eref & e) const
Definition at line 437 of file CompartmentBase.cpp.
{
    return vGetRm( e );
}
References vGetRm().
Referenced by initCinfo(), and moose::CompartmentDataHolder::readData().
getVm()
double CompartmentBase::getVm (const Eref & e) const
Definition at line 405 of file CompartmentBase.cpp.
{
    return vGetVm( e );
}
References vGetVm().
Referenced by initCinfo().
getX()
double CompartmentBase::getX () const
Definition at line 553 of file CompartmentBase.cpp.
{
    return x_;
}
References x_.
Referenced by initCinfo(), and moose::CompartmentDataHolder::readData().
getX0()
double CompartmentBase::getX0 () const
Definition at line 520 of file CompartmentBase.cpp.
{
    return x0_;
}
References x0_.
Referenced by initCinfo(), and moose::CompartmentDataHolder::readData().
getY()
double CompartmentBase::getY () const
Definition at line 564 of file CompartmentBase.cpp.
{
    return y_;
}
References y_.
Referenced by initCinfo(), and moose::CompartmentDataHolder::readData().
getY0()
double CompartmentBase::getY0 () const
Definition at line 531 of file CompartmentBase.cpp.
{
    return y0_;
}
References y0_.
Referenced by initCinfo(), and moose::CompartmentDataHolder::readData().
getZ()
double CompartmentBase::getZ () const
Definition at line 575 of file CompartmentBase.cpp.
{
    return z_;
}
References z_.
Referenced by initCinfo(), and moose::CompartmentDataHolder::readData().
getZ0()
double CompartmentBase::getZ0 () const
Definition at line 542 of file CompartmentBase.cpp.
{
    return z0_;
}
References z0_.
Referenced by initCinfo(), and moose::CompartmentDataHolder::readData().
handleAxial()
void CompartmentBase::handleAxial (double Vm)
handleAxial handles incoming axial message data.
Definition at line 636 of file CompartmentBase.cpp.
{
    vHandleAxial( Vm );
}
References vHandleAxial().
Referenced by initCinfo().
handleChannel()
void CompartmentBase::handleChannel (const Eref & e, double Gk, double Ek)
handleChannel handles information coming from the channel to the compartment
Definition at line 626 of file CompartmentBase.cpp.
{
    vHandleChannel( e, Gk, Ek );
}
References vHandleChannel().
Referenced by initCinfo().
handleRaxial()
void CompartmentBase::handleRaxial (double Ra, double Vm)
handleRaxial handles incoming raxial message data.
Definition at line 631 of file CompartmentBase.cpp.
{
    vHandleRaxial( Ra, Vm );
}
References vHandleRaxial().
Referenced by initCinfo().
initCinfo()
const Cinfo * CompartmentBase::initCinfo () static
Initializes the class info.
The initCinfo() function sets up the CompartmentBase class. This function uses the common trick of having an internal static value which is created the first time the function is called. There are several static arrays set up here. The ones which use SharedFinfos are for shared messages where multiple kinds of information go along the same connection.
Definition at line 59 of file CompartmentBase.cpp.
{
    // Shared messages
    static DestFinfo process( "process",
        "Handles 'process' call",
        new ProcOpFunc< CompartmentBase >( &CompartmentBase::process ) );
    static DestFinfo reinit( "reinit",
        "Handles 'reinit' call",
        new ProcOpFunc< CompartmentBase >( &CompartmentBase::reinit ) );
    static Finfo* processShared[] =
    {
        &process, &reinit
    };
    static SharedFinfo proc( "proc",
        "This is a shared message to receive Process messages from the scheduler"
        "objects. The Process should be called _second_ in each clock tick, after the Init message."
        "The first entry in the shared msg is a MsgDest "
        "for the Process operation. It has a single argument, "
        "ProcInfo, which holds lots of information about current "
        "time, thread, dt and so on. The second entry is a MsgDest "
        "for the Reinit operation. It also uses ProcInfo. "
        "- Handles 'reinit' and 'process' calls.",
        processShared, sizeof( processShared ) / sizeof( Finfo* )
    );
    static DestFinfo initProc( "initProc",
        "Handles Process call for the 'init' phase of the CompartmentBase "
        "calculations. These occur as a separate Tick cycle from the "
        "regular proc cycle, and should be called before the proc msg.",
        new ProcOpFunc< CompartmentBase >( &CompartmentBase::initProc ) );
    static DestFinfo initReinit( "initReinit",
        "Handles Reinit call for the 'init' phase of the CompartmentBase "
        "calculations.",
        new ProcOpFunc< CompartmentBase >( &CompartmentBase::initReinit ) );
    static Finfo* initShared[] =
    {
        &initProc, &initReinit
    };
    static SharedFinfo init( "init",
            "This is a shared message to receive Init messages from "
            "the scheduler objects. Its job is to separate the "
            "compartmental calculations from the message passing. "
            "It doesn't really need to be shared, as it does not use "
            "the reinit part, but the scheduler objects expect this "
            "form of message for all scheduled output. The first "
            "entry is a MsgDest for the Process operation. It has a "
            "single argument, ProcInfo, which holds lots of "
            "information about current time, thread, dt and so on. "
            "The second entry is a dummy MsgDest for the Reinit "
            "operation. It also uses ProcInfo. "
            "- Handles 'initProc' and 'initReinit' calls.",
        initShared, sizeof( initShared ) / sizeof( Finfo* )
    );
    static DestFinfo handleChannel( "handleChannel",
        "Handles conductance and Reversal potential arguments from Channel",
        new EpFunc2< CompartmentBase, double, double >( &CompartmentBase::handleChannel ) );
    // VmOut is declared above as it needs to be in scope for later funcs.
    static Finfo* channelShared[] =
    {
        &handleChannel, CompartmentBase::VmOut()
    };
    static SharedFinfo channel( "channel",
            "This is a shared message from a compartment to channels. "
            "The first entry is a MsgDest for the info coming from "
            "the channel. It expects Gk and Ek from the channel "
            "as args. The second entry is a MsgSrc sending Vm "
            "- Handles 'handleChannel' and 'VmOut' calls.",
        channelShared, sizeof( channelShared ) / sizeof( Finfo* )
    );
    // axialOut declared above as it is needed in file scope
    static DestFinfo handleRaxial( "handleRaxial",
        "Handles Raxial info: arguments are Ra and Vm.",
        new OpFunc2< CompartmentBase, double, double >(
            &CompartmentBase::handleRaxial )
    );
    static Finfo* axialShared[] =
    {
        axialOut(), &handleRaxial
    };
    static SharedFinfo axial( "axial",
            "This is a shared message between asymmetric compartments. "
            "axial messages (this kind) connect up to raxial "
            "messages (defined below). The soma should use raxial "
            "messages to connect to the axial message of all the "
            "immediately adjacent dendritic compartments.This puts "
            "the (low) somatic resistance in series with these "
            "dendrites. Dendrites should then use raxial messages to"
            "connect on to more distal dendrites. In other words, "
            "raxial messages should face outward from the soma. "
            "The first entry is a MsgSrc sending Vm to the axialFunc"
            "of the target compartment. The second entry is a MsgDest "
            "for the info coming from the other compt. It expects "
            "Ra and Vm from the other compt as args. Note that the "
            "message is named after the source type. "
            "- Handles 'axialOut' and 'handleRaxial' calls.",
        axialShared, sizeof( axialShared ) / sizeof( Finfo* )
    );
    static DestFinfo handleAxial( "handleAxial",
        "Handles Axial information. Argument is just Vm.",
        new OpFunc1< CompartmentBase, double >( &CompartmentBase::handleAxial ) );
    // rxialOut declared above as it is needed in file scope
    static Finfo* raxialShared[] =
    {
        &handleAxial, raxialOut()
    };
    static SharedFinfo raxial( "raxial",
            "This is a raxial shared message between asymmetric compartments. The \n"
            "first entry is a MsgDest for the info coming from the other compt. It \n"
            "expects Vm from the other compt as an arg. The second is a MsgSrc sending \n"
            "Ra and Vm to the raxialFunc of the target compartment. \n"
            "- Handles 'handleAxial' and 'raxialOut' calls.",
            raxialShared, sizeof( raxialShared ) / sizeof( Finfo* )
    );
    // Value Finfos.
        static ElementValueFinfo< CompartmentBase, double > Vm( "Vm",
            "membrane potential",
            &CompartmentBase::setVm,
            &CompartmentBase::getVm
        );
        static ElementValueFinfo< CompartmentBase, double > Cm( "Cm",
            "Membrane capacitance",
             &CompartmentBase::setCm,
            &CompartmentBase::getCm
        );
        static ElementValueFinfo< CompartmentBase, double > Em( "Em",
            "Resting membrane potential",
             &CompartmentBase::setEm,
            &CompartmentBase::getEm
        );
        static ReadOnlyElementValueFinfo< CompartmentBase, double > Im( "Im",
            "Current going through membrane",
            &CompartmentBase::getIm
        );
        static ElementValueFinfo< CompartmentBase, double > inject( "inject",
            "Current injection to deliver into compartment",
            &CompartmentBase::setInject,
            &CompartmentBase::getInject
        );
        static ElementValueFinfo< CompartmentBase, double > initVm( "initVm",
            "Initial value for membrane potential",
            &CompartmentBase::setInitVm,
            &CompartmentBase::getInitVm
        );
        static ElementValueFinfo< CompartmentBase, double > Rm( "Rm",
            "Membrane resistance",
            &CompartmentBase::setRm,
            &CompartmentBase::getRm
        );
        static ElementValueFinfo< CompartmentBase, double > Ra( "Ra",
            "Axial resistance of compartment",
            &CompartmentBase::setRa,
            &CompartmentBase::getRa
        );
        static ValueFinfo< CompartmentBase, double > diameter( "diameter",
            "Diameter of compartment",
            &CompartmentBase::setDiameter,
            &CompartmentBase::getDiameter
        );
        static ValueFinfo< CompartmentBase, double > length( "length",
            "Length of compartment",
            &CompartmentBase::setLength,
            &CompartmentBase::getLength
        );
        static ValueFinfo< CompartmentBase, double > x0( "x0",
            "X coordinate of start of compartment",
            &CompartmentBase::setX0,
            &CompartmentBase::getX0
        );
        static ValueFinfo< CompartmentBase, double > y0( "y0",
            "Y coordinate of start of compartment",
            &CompartmentBase::setY0,
            &CompartmentBase::getY0
        );
        static ValueFinfo< CompartmentBase, double > z0( "z0",
            "Z coordinate of start of compartment",
            &CompartmentBase::setZ0,
            &CompartmentBase::getZ0
        );
        static ValueFinfo< CompartmentBase, double > x( "x",
            "x coordinate of end of compartment",
            &CompartmentBase::setX,
            &CompartmentBase::getX
        );
        static ValueFinfo< CompartmentBase, double > y( "y",
            "y coordinate of end of compartment",
            &CompartmentBase::setY,
            &CompartmentBase::getY
        );
        static ValueFinfo< CompartmentBase, double > z( "z",
            "z coordinate of end of compartment",
            &CompartmentBase::setZ,
            &CompartmentBase::getZ
        );
        static ValueFinfo< CompartmentBase, vector< double > > coords( "coords",
            "Vector with all coords: [x0 y0 z0 x y z dia]",
            &CompartmentBase::setCoords,
            &CompartmentBase::getCoords
        );
    // DestFinfo definitions
        static DestFinfo injectMsg( "injectMsg",
            "The injectMsg corresponds to the INJECT message in the "
            "GENESIS compartment. Unlike the 'inject' field, any value "
            "assigned by handleInject applies only for a single timestep."
            "So it needs to be updated every dt for a steady (or varying)"
            "injection current",
            new EpFunc1< CompartmentBase,  double >( &CompartmentBase::injectMsg )
        );
        static DestFinfo randInject( "randInject",
            "Sends a random injection current to the compartment. Must be"
            "updated each timestep."
            "Arguments to randInject are probability and current.",
            new EpFunc2< CompartmentBase, double, double > (
                &CompartmentBase::randInject ) );
        static DestFinfo cable( "cable",
            "Message for organizing compartments into groups, called"
            "cables. Doesn't do anything.",
            new OpFunc0< CompartmentBase >( &CompartmentBase::cable )
        );
        static DestFinfo displace( "displace",
            "Displaces compartment by specified vector",
            new OpFunc3< CompartmentBase, double, double, double>(
                    &CompartmentBase::displace )
        );
        static DestFinfo setGeomAndElec( "setGeomAndElec",
            "Assigns length and dia and accounts for any electrical "
            "scaling needed as a result.",
            new EpFunc2< CompartmentBase, double, double>(
                    &CompartmentBase::setGeomAndElec )
        );
    static Finfo* compartmentFinfos[] =
    {
        &Vm,                // Value
        &Cm,                // Value
        &Em,                // Value
        &Im,                // ReadOnlyValue
        &inject,            // Value
        &initVm,            // Value
        &Rm,                // Value
        &Ra,                // Value
        &diameter,          // Value
        &length,            // Value
        &x0,                // Value
        &y0,                // Value
        &z0,                // Value
        &x,                 // Value
        &y,                 // Value
        &z,                 // Value
        &coords,            // Value
        &injectMsg,         // DestFinfo
        &randInject,        // DestFinfo
        &injectMsg,         // DestFinfo
        &cable,             // DestFinfo
        &displace,          // DestFinfo
        &setGeomAndElec,    // DestFinfo
        &proc,              // SharedFinfo
        &init,              // SharedFinfo
        &channel,           // SharedFinfo
        &axial,             // SharedFinfo
        &raxial             // SharedFinfo
    };
    static string doc[] =
    {
        "Name", "CompartmentBase",
        "Author", "Upi Bhalla",
        "Description", "CompartmentBase object, for branching neuron models.",
    };
        static ZeroSizeDinfo< int > dinfo;
    static Cinfo compartmentCinfo(
                "CompartmentBase",
                Neutral::initCinfo(),
                compartmentFinfos,
                sizeof( compartmentFinfos ) / sizeof( Finfo* ),
                &dinfo,
                doc,
                sizeof(doc)/sizeof(string)
    );
    return &compartmentCinfo;
}
References axialOut(), cable(), Cinfo::Cinfo(), DestFinfo::DestFinfo(), displace(), ElementValueFinfo< T, F >::ElementValueFinfo(), EpFunc1< T, A >::EpFunc1(), EpFunc2< T, A1, A2 >::EpFunc2(), getCm(), getCoords(), getDiameter(), getEm(), getIm(), getInitVm(), getInject(), getLength(), getRa(), getRm(), getVm(), getX(), getX0(), getY(), getY0(), getZ(), getZ0(), handleAxial(), handleChannel(), handleRaxial(), Neutral::initCinfo(), initProc(), initReinit(), injectMsg(), OpFunc0< T >::OpFunc0(), OpFunc1< T, A >::OpFunc1(), OpFunc2< T, A1, A2 >::OpFunc2(), OpFunc3< T, A1, A2, A3 >::OpFunc3(), process(), ProcOpFunc< T >::ProcOpFunc(), randInject(), raxialOut(), ReadOnlyElementValueFinfo< T, F >::ReadOnlyElementValueFinfo(), reinit(), setCm(), setCoords(), setDiameter(), setEm(), setGeomAndElec(), setInitVm(), setInject(), setLength(), setRa(), setRm(), setVm(), setX(), setX0(), setY(), setY0(), setZ(), setZ0(), SharedFinfo::SharedFinfo(), ValueFinfo< T, F >::ValueFinfo(), and VmOut().
Referenced by moose::Compartment::initCinfo(), and ZombieCompartment::initCinfo().
initProc()
void CompartmentBase::initProc (const Eref & e, ProcPtr p)
The initProc function is for a second phase of 'process' operations. It sends the axial and raxial messages to other compartments. It has to be executed out of phase with the main process so that all compartments are equivalent and there is no calling order dependence in the results.
Definition at line 616 of file CompartmentBase.cpp.
{
    vInitProc( e, p );
}
References vInitProc().
Referenced by initCinfo().
initReinit()
void CompartmentBase::initReinit (const Eref & e, ProcPtr p)
Empty function to do another reinit step out of phase with the main one. Nothing needs doing there.
Definition at line 621 of file CompartmentBase.cpp.
{
    vInitReinit( e, p );
}
References vInitReinit().
Referenced by initCinfo().
injectMsg()
void CompartmentBase::injectMsg (const Eref & e, double current)
Injects a constantly updated current into the compartment. Unlike the 'inject' field, this injected current is applicable only for a single timestep. So this is meant to be used as the destination of a message rather than as a one-time assignment.
Definition at line 641 of file CompartmentBase.cpp.
{
    vInjectMsg( e, current );
}
References vInjectMsg().
Referenced by initCinfo().
process()
void CompartmentBase::process (const Eref & e, ProcPtr p)
The process function does the object updating and sends out messages to channels, nernsts, and so on.
Definition at line 606 of file CompartmentBase.cpp.
{
    vProcess( e, p );
}
References vProcess().
Referenced by initCinfo().
randInject()
void CompartmentBase::randInject (const Eref & e, double prob, double current)
Injects a constantly updated current into the compartment, with a probability prob. Note that it isn't the current amplitude that is random, it is the presence or absence of the current that is probabilistic.
Definition at line 646 of file CompartmentBase.cpp.
{
    vRandInject( e, prob, current );
}
References vRandInject().
Referenced by initCinfo().
rangeWarning()
bool CompartmentBase::rangeWarning (const string & field, double value)
A utility function to check for assignment to fields that must be > 0
Definition at line 387 of file CompartmentBase.cpp.
{
    if ( value < RANGE ) {
        cout << "Warning: Ignored attempt to set " << field <<
                " of compartment " <<
                // c->target().e->name() <<
                " to " << value << " as it is less than " << RANGE << endl;
        return 1;
    }
    return 0;
}
References RANGE.
Referenced by setCm(), setRa(), setRm(), moose::Compartment::vSetCm(), ZombieCompartment::vSetCm(), moose::Compartment::vSetRa(), ZombieCompartment::vSetRa(), moose::Compartment::vSetRm(), and ZombieCompartment::vSetRm().
reinit()
void CompartmentBase::reinit (const Eref & e, ProcPtr p)
The reinit function reinitializes all fields.
Definition at line 611 of file CompartmentBase.cpp.
{
    vReinit( e, p );
}
References vReinit().
Referenced by initCinfo().
setCm()
void CompartmentBase::setCm (const Eref & e, double Cm)
Definition at line 420 of file CompartmentBase.cpp.
{
    if ( rangeWarning( "Cm", Cm ) ) return;
    vSetCm( e, Cm );
}
References rangeWarning(), and vSetCm().
Referenced by initCinfo(), makeCompt(), and moose::CompartmentDataHolder::writeData().
setCoords()
void CompartmentBase::setCoords (vector< double > value)
Definition at line 580 of file CompartmentBase.cpp.
{
    if (value.size() < 7 ) {
        cout << "Warning: CompartmentBase:setCoords. Vector size = " << value.size() << ", require 7 = [ x0 y0 z0 x y z dia ] \n";
        return;
    }
    x0_ = value[0];
    y0_ = value[1];
    z0_ = value[2];
    x_ = value[3];
    y_ = value[4];
    z_ = value[5];
    diameter_ = value[6];
    updateLength();
}
References diameter_, updateLength(), x0_, x_, y0_, y_, z0_, and z_.
Referenced by initCinfo().
setDiameter()
void CompartmentBase::setDiameter (double diameter)
Definition at line 478 of file CompartmentBase.cpp.
{
    diameter_ = value;
}
References diameter_.
Referenced by initCinfo(), makeCompt(), setGeomAndElec(), and moose::CompartmentDataHolder::writeData().
setEm()
void CompartmentBase::setEm (const Eref & e, double Em)
Definition at line 410 of file CompartmentBase.cpp.
{
    vSetEm( e, Em );
}
References vSetEm().
Referenced by initCinfo(), and moose::CompartmentDataHolder::writeData().
setGeomAndElec()
void CompartmentBase::setGeomAndElec (const Eref & e, double length, double dia)
Scales electrical values along with setting length, dia.
Definition at line 675 of file CompartmentBase.cpp.
{
    if ( length_ > 0 && diameter_ > 0 && len > 0 && dia > 0 &&
            doubleEq( length_ * length_,
            (x_-x0_)*(x_-x0_) + (y_-y0_)*(y_-y0_) + (z_-z0_)*(z_-z0_) ) ) {
        vSetRm( e, vGetRm( e ) * diameter_ * length_ / ( dia * len ) );
        vSetCm( e, vGetCm( e ) * dia * len / ( diameter_ * length_ ) );
        vSetRa( e, vGetRa( e ) * len * (diameter_ * diameter_) /
                ( length_ * dia * dia ) );
        // Rescale channel Gbars here
        vector< ObjId > chans;
        allChildren( e.objId(), ALLDATA, "ISA=ChanBase", chans );
        for ( unsigned int i = 0; i < chans.size(); ++i ) {
            if ( hasScaleFormula( chans[i].eref() ) )
                continue; // Later we will eval the formula with len and dia
            double gbar = Field< double >::get( chans[i], "Gbar" );
            gbar *= len * dia / ( length_ * diameter_ );
            Field< double >::set( chans[i], "Gbar", gbar );
        }
        // Rescale CaConc sizes here
        vector< ObjId > concs;
        allChildren( e.objId(), ALLDATA, "ISA=CaConcBase", concs );
        for ( unsigned int i = 0; i < concs.size(); ++i ) {
            Field< double >::set( concs[i], "length", len );
            Field< double >::set( concs[i], "diameter", dia );
        }
        setLength( len );
        setDiameter( dia );
    }
}
References allChildren(), ALLDATA, diameter_, doubleEq(), ObjId::eref(), Field< A >::get(), hasScaleFormula(), length_, Eref::objId(), Field< A >::set(), setDiameter(), setLength(), vGetCm(), vGetRa(), vGetRm(), vSetCm(), vSetRa(), vSetRm(), x0_, x_, y0_, y_, z0_, and z_.
Referenced by initCinfo().
setInitVm()
void CompartmentBase::setInitVm (const Eref & e, double initVm)
Definition at line 468 of file CompartmentBase.cpp.
{
    vSetInitVm( e, initVm );
}
References vSetInitVm().
Referenced by initCinfo(), and moose::CompartmentDataHolder::writeData().
setInject()
void CompartmentBase::setInject (const Eref & e, double Inject)
Definition at line 458 of file CompartmentBase.cpp.
{
    vSetInject( e, Inject );
}
References vSetInject().
Referenced by initCinfo(), and moose::CompartmentDataHolder::writeData().
setLength()
void CompartmentBase::setLength (double length)
Definition at line 488 of file CompartmentBase.cpp.
{
    // If length is assigned correctly, also redo the end coords to match.
    if ( value > 0 && length_ > 0 &&
            doubleEq( length_ * length_,
            (x_-x0_)*(x_-x0_) + (y_-y0_)*(y_-y0_) + (z_-z0_)*(z_-z0_) ) ) {
        double ratio = value / length_;
        x_ = x0_ + ratio * ( x_ - x0_ );
        y_ = y0_ + ratio * ( y_ - y0_ );
        z_ = z0_ + ratio * ( z_ - z0_ );
    }
    length_ = value;
}
References doubleEq(), length_, x0_, x_, y0_, y_, z0_, and z_.
Referenced by initCinfo(), makeCompt(), setGeomAndElec(), and moose::CompartmentDataHolder::writeData().
setRa()
void CompartmentBase::setRa (const Eref & e, double Ra)
Definition at line 442 of file CompartmentBase.cpp.
{
    if ( rangeWarning( "Ra", Ra ) ) return;
    vSetRa( e, Ra );
}
References rangeWarning(), and vSetRa().
Referenced by initCinfo(), makeCompt(), and moose::CompartmentDataHolder::writeData().
setRm()
void CompartmentBase::setRm (const Eref & e, double Rm)
Definition at line 431 of file CompartmentBase.cpp.
{
    if ( rangeWarning( "Rm", Rm ) ) return;
    vSetRm( e, Rm );
}
References rangeWarning(), and vSetRm().
Referenced by initCinfo(), makeCompt(), and moose::CompartmentDataHolder::writeData().
setVm()
void CompartmentBase::setVm (const Eref & e, double Vm)
Definition at line 400 of file CompartmentBase.cpp.
{
    vSetVm( e, Vm );
}
References vSetVm().
Referenced by initCinfo().
setX()
void CompartmentBase::setX (double value)
Definition at line 547 of file CompartmentBase.cpp.
{
    x_ = value;
    updateLength();
}
References updateLength(), and x_.
Referenced by initCinfo(), makeCompt(), and moose::CompartmentDataHolder::writeData().
setX0()
void CompartmentBase::setX0 (double value)
Definition at line 514 of file CompartmentBase.cpp.
{
    x0_ = value;
    updateLength();
}
References updateLength(), and x0_.
Referenced by initCinfo(), makeCompt(), and moose::CompartmentDataHolder::writeData().
setY()
void CompartmentBase::setY (double value)
Definition at line 558 of file CompartmentBase.cpp.
{
    y_ = value;
    updateLength();
}
References updateLength(), and y_.
Referenced by initCinfo(), makeCompt(), and moose::CompartmentDataHolder::writeData().
setY0()
void CompartmentBase::setY0 (double value)
Definition at line 525 of file CompartmentBase.cpp.
{
    y0_ = value;
    updateLength();
}
References updateLength(), and y0_.
Referenced by initCinfo(), makeCompt(), and moose::CompartmentDataHolder::writeData().
setZ()
void CompartmentBase::setZ (double value)
Definition at line 569 of file CompartmentBase.cpp.
{
    z_ = value;
    updateLength();
}
References updateLength(), and z_.
Referenced by initCinfo(), makeCompt(), and moose::CompartmentDataHolder::writeData().
setZ0()
void CompartmentBase::setZ0 (double value)
Definition at line 536 of file CompartmentBase.cpp.
{
    z0_ = value;
    updateLength();
}
References updateLength(), and z0_.
Referenced by initCinfo(), makeCompt(), and moose::CompartmentDataHolder::writeData().
updateLength()
void CompartmentBase::updateLength ()
A utility function update length if any of the coords change
Definition at line 508 of file CompartmentBase.cpp.
{
    length_ = sqrt( (x_-x0_)*(x_-x0_) +
                    (y_-y0_)*(y_-y0_) + (z_-z0_)*(z_-z0_) );
}
References length_, x0_, x_, y0_, y_, z0_, and z_.
Referenced by setCoords(), setX(), setX0(), setY(), setY0(), setZ(), and setZ0().
vGetCm()
virtual double moose::CompartmentBase::vGetCm (const Eref & e) const pure virtual
Implemented in moose::Compartment, and ZombieCompartment.
Referenced by getCm(), and setGeomAndElec().
vGetEm()
virtual double moose::CompartmentBase::vGetEm (const Eref & e) const pure virtual
Implemented in moose::Compartment, and ZombieCompartment.
Referenced by getEm().
vGetIm()
virtual double moose::CompartmentBase::vGetIm (const Eref & e) const pure virtual
Implemented in moose::Compartment, and ZombieCompartment.
Referenced by getIm().
vGetInitVm()
virtual double moose::CompartmentBase::vGetInitVm (const Eref & e) const pure virtual
Implemented in moose::Compartment, and ZombieCompartment.
Referenced by getInitVm().
vGetInject()
virtual double moose::CompartmentBase::vGetInject (const Eref & e) const pure virtual
Implemented in moose::Compartment, and ZombieCompartment.
Referenced by getInject().
vGetRa()
virtual double moose::CompartmentBase::vGetRa (const Eref & e) const pure virtual
Implemented in moose::Compartment, and ZombieCompartment.
Referenced by getRa(), and setGeomAndElec().
vGetRm()
virtual double moose::CompartmentBase::vGetRm (const Eref & e) const pure virtual
Implemented in moose::Compartment, and ZombieCompartment.
Referenced by getRm(), and setGeomAndElec().
vGetVm()
virtual double moose::CompartmentBase::vGetVm (const Eref & e) const pure virtual
Implemented in moose::Compartment, and ZombieCompartment.
Referenced by getVm().
vHandleAxial()
virtual void moose::CompartmentBase::vHandleAxial (double Vm) pure virtual
handleAxial handles incoming axial message data.
Implemented in moose::Compartment, and ZombieCompartment.
Referenced by handleAxial().
vHandleChannel()
virtual void moose::CompartmentBase::vHandleChannel (const Eref & e, double Gk, double Ek) pure virtual
handleChannel handles information coming from the channel to the compartment
Implemented in moose::Compartment, and ZombieCompartment.
Referenced by handleChannel().
vHandleRaxial()
virtual void moose::CompartmentBase::vHandleRaxial (double Ra, double Vm) pure virtual
handleRaxial handles incoming raxial message data.
Implemented in moose::Compartment, and ZombieCompartment.
Referenced by handleRaxial().
vInitProc()
virtual void moose::CompartmentBase::vInitProc (const Eref & e, ProcPtr p) pure virtual
The initProc function is for a second phase of 'process' operations. It sends the axial and raxial messages to other compartments. It has to be executed out of phase with the main process so that all compartments are equivalent and there is no calling order dependence in the results.
Implemented in moose::Compartment, SymCompartment, and ZombieCompartment.
Referenced by initProc().
vInitReinit()
virtual void moose::CompartmentBase::vInitReinit (const Eref & e, ProcPtr p) pure virtual
Empty function to do another reinit step out of phase with the main one. Nothing needs doing there.
Implemented in moose::Compartment, SymCompartment, and ZombieCompartment.
Referenced by initReinit().
vInjectMsg()
virtual void moose::CompartmentBase::vInjectMsg (const Eref & e, double current) pure virtual
Injects a constantly updated current into the compartment. Unlike the 'inject' field, this injected current is applicable only for a single timestep. So this is meant to be used as the destination of a message rather than as a one-time assignment.
Implemented in moose::Compartment, and ZombieCompartment.
Referenced by injectMsg().
VmOut()
SrcFinfo1< double > * CompartmentBase::VmOut () static
This Finfo is used to send out Vm to channels, spikegens, etc
It is exposed here so that HSolve can also use it to send out the Vm to the recipients.
Definition at line 26 of file CompartmentBase.cpp.
{
    static SrcFinfo1< double > VmOut( "VmOut",
        "Sends out Vm value of compartment on each timestep" );
    return &VmOut;
}
References SrcFinfo1< T >::SrcFinfo1().
Referenced by initCinfo(), HSolveActive::sendValues(), moose::Compartment::vProcess(), moose::AdExIF::vProcess(), moose::AdThreshIF::vProcess(), moose::ExIF::vProcess(), moose::IzhIF::vProcess(), moose::LIF::vProcess(), moose::QIF::vProcess(), and moose::Compartment::vReinit().
vProcess()
virtual void moose::CompartmentBase::vProcess (const Eref & e, ProcPtr p) pure virtual
The process function does the object updating and sends out messages to channels, nernsts, and so on.
Implemented in moose::Compartment, ZombieCompartment, moose::AdExIF, moose::AdThreshIF, moose::ExIF, moose::IzhIF, moose::LIF, moose::QIF, and moose::IntFireBase.
Referenced by process().
vRandInject()
virtual void moose::CompartmentBase::vRandInject (const Eref & e, double prob, double current) pure virtual
Injects a constantly updated current into the compartment, with a probability prob. Note that it isn't the current amplitude that is random, it is the presence or absence of the current that is probabilistic.
Implemented in moose::Compartment, and ZombieCompartment.
Referenced by randInject().
vReinit()
virtual void moose::CompartmentBase::vReinit (const Eref & e, ProcPtr p) pure virtual
The reinit function reinitializes all fields.
Implemented in moose::Compartment, SymCompartment, ZombieCompartment, moose::AdExIF, moose::AdThreshIF, moose::ExIF, moose::IzhIF, moose::LIF, moose::QIF, and moose::IntFireBase.
Referenced by reinit().
vSetCm()
virtual void moose::CompartmentBase::vSetCm (const Eref & e, double Cm) pure virtual
Implemented in moose::Compartment, and ZombieCompartment.
Referenced by setCm(), and setGeomAndElec().
vSetEm()
virtual void moose::CompartmentBase::vSetEm (const Eref & e, double Em) pure virtual
Implemented in moose::Compartment, and ZombieCompartment.
Referenced by setEm().
vSetInitVm()
virtual void moose::CompartmentBase::vSetInitVm (const Eref & e, double initVm) pure virtual
Implemented in moose::Compartment, and ZombieCompartment.
Referenced by setInitVm().
vSetInject()
virtual void moose::CompartmentBase::vSetInject (const Eref & e, double Inject) pure virtual
Implemented in moose::Compartment, and ZombieCompartment.
Referenced by setInject().
vSetRa()
virtual void moose::CompartmentBase::vSetRa (const Eref & e, double Ra) pure virtual
Implemented in moose::Compartment, and ZombieCompartment.
Referenced by setGeomAndElec(), and setRa().
vSetRm()
virtual void moose::CompartmentBase::vSetRm (const Eref & e, double Rm) pure virtual
Implemented in moose::Compartment, and ZombieCompartment.
Referenced by setGeomAndElec(), and setRm().
vSetSolver()
void CompartmentBase::vSetSolver (const Eref & e, Id hsolve) virtual
Reimplemented in ZombieCompartment.
Definition at line 713 of file CompartmentBase.cpp.
{;}
Referenced by zombify().
vSetVm()
virtual void moose::CompartmentBase::vSetVm (const Eref & e, double Vm) pure virtual
Implemented in moose::Compartment, and ZombieCompartment.
Referenced by setVm().
zombify()
void CompartmentBase::zombify (Element * orig, const Cinfo * zClass, Id hsolve) static
This function is used to swap Cinfos of any CompartmentBase derived class. Used for making ZombieCompartments.
Definition at line 717 of file CompartmentBase.cpp.
{
    if ( orig->cinfo() == zClass )
        return;
    unsigned int start = orig->localDataStart();
    unsigned int num = orig->numLocalData();
    if ( num == 0 )
        return;
    vector< CompartmentDataHolder > cdh( num );
    for ( unsigned int i = 0; i < num; ++i ) {
        Eref er( orig, i + start );
        const CompartmentBase* cb =
            reinterpret_cast< const CompartmentBase* >( er.data() );
        cdh[i].readData( cb, er );
    }
    orig->zombieSwap( zClass );
    for ( unsigned int i = 0; i < num; ++i ) {
        Eref er( orig, i + start );
        CompartmentBase* cb = reinterpret_cast< CompartmentBase* >( er.data() );
        cb->vSetSolver( er, hsolve );
        cdh[i].writeData( cb, er );
    }
}
References Element::cinfo(), Eref::data(), Eref::Eref(), Element::localDataStart(), Element::numLocalData(), moose::CompartmentDataHolder::readData(), vSetSolver(), moose::CompartmentDataHolder::writeData(), and Element::zombieSwap().
Referenced by HSolve::unzombify(), and HSolve::zombify().
Member Data Documentation
diameter_
double moose::CompartmentBase::diameter_ private
Definition at line 256 of file CompartmentBase.h.
Referenced by CompartmentBase(), getCoords(), getDiameter(), setCoords(), setDiameter(), and setGeomAndElec().
length_
double moose::CompartmentBase::length_ private
Definition at line 257 of file CompartmentBase.h.
Referenced by CompartmentBase(), getLength(), setGeomAndElec(), setLength(), and updateLength().
x0_
double moose::CompartmentBase::x0_ private
Definition at line 258 of file CompartmentBase.h.
Referenced by CompartmentBase(), displace(), getCoords(), getX0(), setCoords(), setGeomAndElec(), setLength(), setX0(), and updateLength().
x_
double moose::CompartmentBase::x_ private
Definition at line 261 of file CompartmentBase.h.
Referenced by CompartmentBase(), displace(), getCoords(), getX(), setCoords(), setGeomAndElec(), setLength(), setX(), and updateLength().
y0_
double moose::CompartmentBase::y0_ private
Definition at line 259 of file CompartmentBase.h.
Referenced by CompartmentBase(), displace(), getCoords(), getY0(), setCoords(), setGeomAndElec(), setLength(), setY0(), and updateLength().
y_
double moose::CompartmentBase::y_ private
Definition at line 262 of file CompartmentBase.h.
Referenced by CompartmentBase(), displace(), getCoords(), getY(), setCoords(), setGeomAndElec(), setLength(), setY(), and updateLength().
z0_
double moose::CompartmentBase::z0_ private
Definition at line 260 of file CompartmentBase.h.
Referenced by CompartmentBase(), displace(), getCoords(), getZ0(), setCoords(), setGeomAndElec(), setLength(), setZ0(), and updateLength().
z_
double moose::CompartmentBase::z_ private
Definition at line 263 of file CompartmentBase.h.
Referenced by CompartmentBase(), displace(), getCoords(), getZ(), setCoords(), setGeomAndElec(), setLength(), setZ(), and updateLength().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/biophysics/CompartmentBase.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/biophysics/CompartmentBase.cpp