MOOSE - Multiscale Object Oriented Simulation Environment: HHGateBase Class Reference
HHGateBase Class Reference
#include <HHGateBase.h>
Public Member Functions
bool checkOriginal (Id id, const string &field) const
HHGateBase ()
HHGateBase (Id originalChanId, Id originalGateId)
bool isOriginalChannel (Id id) const
bool isOriginalGate (Id id) const
Id originalChannelId () const
Id originalGateId () const
Static Public Member Functions
static const Cinfo * initCinfo ()
Protected Attributes
Id originalChanId_
Id originalGateId_
Detailed Description
This class is the base for gates in Hodgkin-Huxley type channels (HHGates). HHGates are typically shared. This means that when you make a copy or a vector of an HHChannel, there is only a single HHGate created, and its pointer is used by all the copies. The lookup functions are thread-safe. Field assignment to the HHGate should be possible only from the original HHChannel, but all the others do have read permission. This base class only factors out the tracking of the ownership.
Definition at line 23 of file HHGateBase.h.
Constructor & Destructor Documentation
HHGateBase() [1/2]
HHGateBase::HHGateBase ()
Dummy constructor, to keep Dinfo happy. Should never be used
Definition at line 17 of file HHGateBase.cpp.
                       : originalChanId_(0), originalGateId_(0)
{
    cerr << "# HHGateBase::HHGateBase() should never be called" << endl;
}
References Id::Id(), originalChanId_, and originalGateId_.
HHGateBase() [2/2]
HHGateBase::HHGateBase (Id originalChanId, Id originalGateId)
This constructor is the one meant to be used. It takes the originalId of the parent HHChannel as a required argument, so that any subsequent 'write' functions can be checked to see if they are legal. Also tracks its own Id.
Definition at line 22 of file HHGateBase.cpp.
    : originalChanId_(originalChanId), originalGateId_(originalGateId)
{
    // cerr << "# HHGateBase::HHGateBase(): originalChanId:" << originalChanId << ", originalGateId: " << originalGateId << endl;
    ;
}
References originalChanId_, and originalGateId_.
Referenced by HHGate::HHGate(), HHGate::HHGate(), HHGate2D::HHGate2D(), HHGateF::HHGateF(), and HHGateF::HHGateF().
Member Function Documentation
checkOriginal()
bool HHGateBase::checkOriginal (Id id, const string & field) const
Checks if the provided Id is the one that the HHGate was created on. If true, fine, otherwise complains about trying to set the field.
Definition at line 33 of file HHGateBase.cpp.
{
    if(id == originalGateId_)
        return true;
    cout << "Warning: HHGateBase: attempt to set field '" << field << "' on "
         << id.path() << ", which is not the original Gate element. Ignored.\n";
    return false;
}
References Id::operator==(), originalGateId_, and Id::path().
Referenced by HHGateF::setAlpha(), HHGate::setAlpha(), HHGate::setAlphaExpr(), HHGateF::setBeta(), HHGate::setBeta(), HHGate::setBetaExpr(), HHGate::setDivs(), HHGateF::setInf(), HHGate::setInfExpr(), HHGate::setMax(), HHGate::setMin(), HHGate::setMinfinity(), HHGate::setTableA(), HHGate::setTableB(), HHGateF::setTau(), HHGate::setTau(), HHGate::setTauExpr(), HHGate::setupAlpha(), HHGate::setupGate(), HHGate::setupTau(), and HHGate::setUseInterpolation().
initCinfo()
static const Cinfo * HHGateBase::initCinfo () static
isOriginalChannel()
bool HHGateBase::isOriginalChannel (Id id) const
isOriginalChannel returns true if the provided Id is the Id of the channel on which the HHGate was created.
Definition at line 43 of file HHGateBase.cpp.
{
    // cerr << "# Received: " << id << ", original: " << originalChanId_ << endl;
    return (id == originalChanId_);
}
References Id::operator==(), and originalChanId_.
Referenced by HHChannel::checkOriginal(), HHChannelF::checkOriginal(), and HHChannelF2D::checkOriginal().
isOriginalGate()
bool HHGateBase::isOriginalGate (Id id) const
isOriginalChannel returns true if the provided Id is the Id of the Gate created at the same time as the original channel.
Definition at line 49 of file HHGateBase.cpp.
{
    return (id == originalGateId_);
}
References Id::operator==(), and originalGateId_.
originalChannelId()
Id HHGateBase::originalChannelId () const
Returns the Id of the original Channel.
Definition at line 54 of file HHGateBase.cpp.
{
    return originalChanId_;
}
References originalChanId_.
originalGateId()
Id HHGateBase::originalGateId () const
Returns the Id of the original Gate.
Definition at line 59 of file HHGateBase.cpp.
{
    return originalGateId_;
}
References originalGateId_.
Referenced by HSolveUtils::gates(), and HSolveUtils::rates().
Member Data Documentation
originalChanId_
Id HHGateBase::originalChanId_ protected
Id of original channel, the one which has actually allocated it, All other Elements have to treat the values as readonly.
Definition at line 77 of file HHGateBase.h.
Referenced by HHGateBase(), HHGateBase(), isOriginalChannel(), and originalChannelId().
originalGateId_
Id HHGateBase::originalGateId_ protected
Id of original Gate, the one which was created with the original channel. All other Elements have to treat the values as readonly.
Definition at line 84 of file HHGateBase.h.
Referenced by checkOriginal(), HHGateBase(), HHGateBase(), isOriginalGate(), and originalGateId().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/biophysics/HHGateBase.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/biophysics/HHGateBase.cpp