MOOSE - Multiscale Object Oriented Simulation Environment: HopFunc1< A > Class Template Reference
HopFunc1< A > Class Template Reference
#include <HopFunc.h>
Public Member Functions
void dataOpVec (const Eref &e, const vector< A > &arg, const OpFunc1Base< A > *op) const
HopFunc1 (HopIndex hopIndex)
unsigned int localFieldOpVec (const Eref &er, const vector< A > &arg, const OpFunc1Base< A > *op) const
Executes the local vector assignment. Returns number of entries.
unsigned int localOpVec (Element *elm, const vector< A > &arg, const OpFunc1Base< A > *op, unsigned int k) const
Executes the local vector assignment. Returns current arg index.
void op (const Eref &e, A arg) const
void opVec (const Eref &er, const vector< A > &arg, const OpFunc1Base< A > *op) const
unsigned int remoteOpVec (const Eref &er, const vector< A > &arg, const OpFunc1Base< A > *op, unsigned int start, unsigned int end) const
Dispatches remote vector assignment. start and end are arg index.
Public Member Functions inherited from OpFunc1Base< A >
bool checkFinfo (const Finfo *s) const
const OpFunc * makeHopFunc (HopIndex hopIndex) const
void opBuffer (const Eref &e, double *buf) const
Executes the OpFunc by converting args.
void opVecBuffer (const Eref &e, double *buf) const
Executes the OpFunc for all data by converting a vector of args.
string rttiType () const
Public Member Functions inherited from OpFunc
OpFunc ()
unsigned int opIndex () const
bool setIndex (unsigned int i)
Used when rebuilding the Fid->OpFunc mapping.
virtual ~OpFunc ()
Private Attributes
HopIndex hopIndex_
Additional Inherited Members
Static Public Member Functions inherited from OpFunc
static const OpFunc * lookop (unsigned int opIndex)
static unsigned int rebuildOpIndex ()
cleans out the entire Ops vector. Returns size of orig vector.
Detailed Description
template<class A>
class HopFunc1< A >
Definition at line 45 of file HopFunc.h.
Constructor & Destructor Documentation
HopFunc1()
template<class A > HopFunc1< A >::HopFunc1 (HopIndex hopIndex) inline
Definition at line 48 of file HopFunc.h.
                : hopIndex_( hopIndex )
        {;}
References HopFunc1< A >::hopIndex_.
Member Function Documentation
dataOpVec()
template<class A > void HopFunc1< A >::dataOpVec (const Eref & e, const vector< A > & arg, const OpFunc1Base< A > * op) const inline
Definition at line 123 of file HopFunc.h.
        {
            Element* elm = e.element();
            vector< unsigned int > endOnNode( mooseNumNodes(), 0 );
            unsigned int lastEnd = 0;
            for ( unsigned int i = 0; i < mooseNumNodes(); ++i ) {
                endOnNode[i] = elm->getNumOnNode(i) + lastEnd;
                lastEnd = endOnNode[i];
            }
            unsigned int k = 0; // counter for index to arg vector.
            // The global case just sends all entries to all nodes.
            for ( unsigned int i = 0; i < mooseNumNodes(); ++i ) {
                if ( i == mooseMyNode() ) {
                    k = localOpVec( elm, arg, op, k );
                    assert( k == endOnNode[i] );
                } else {
                    if ( !elm->isGlobal() ) {
                        unsigned int start = elm->startDataIndex( i );
                        if ( start < elm->numData() ) {
                            Eref starter( elm,  start );
                            assert( elm->getNode( starter.dataIndex() ) == i );
                            k = remoteOpVec( starter, arg, op, k, endOnNode[i]);
                        }
                    }
                }
            }
            if ( elm->isGlobal() ) {
                Eref starter( elm,  0 );
                remoteOpVec( starter, arg, op, 0, arg.size() );
            }
        }
References Eref::dataIndex(), Eref::element(), Eref::Eref(), Element::getNode(), Element::getNumOnNode(), Element::isGlobal(), HopFunc1< A >::localOpVec(), mooseMyNode(), mooseNumNodes(), Element::numData(), HopFunc1< A >::remoteOpVec(), and Element::startDataIndex().
Referenced by HopFunc1< A >::opVec().
localFieldOpVec()
template<class A > unsigned int HopFunc1< A >::localFieldOpVec (const Eref & er, const vector< A > & arg, const OpFunc1Base< A > * op) const inline
Executes the local vector assignment. Returns number of entries.
Definition at line 78 of file HopFunc.h.
        {
            assert( er.getNode() == mooseMyNode() );
            unsigned int di = er.dataIndex();
            Element* elm = er.element();
            unsigned int numField =
                    elm->numField( di - er.element()->localDataStart()  );
            for ( unsigned int q = 0; q < numField; ++q ) {
                Eref temp( elm, di, q );
                op->op( temp, arg[ q % arg.size() ] );
            }
            return numField;
        }
References Eref::dataIndex(), Eref::element(), Eref::Eref(), Eref::getNode(), Element::localDataStart(), mooseMyNode(), and Element::numField().
Referenced by HopFunc1< A >::opVec().
localOpVec()
template<class A > unsigned int HopFunc1< A >::localOpVec (Element * elm, const vector< A > & arg, const OpFunc1Base< A > * op, unsigned int k) const inline
Executes the local vector assignment. Returns current arg index.
Definition at line 59 of file HopFunc.h.
        {
            unsigned int numLocalData = elm->numLocalData();
            unsigned int start = elm->localDataStart();
            for ( unsigned int p = 0; p < numLocalData; ++p ) {
                unsigned int numField = elm->numField( p );
                for ( unsigned int q = 0; q < numField; ++q ) {
                    Eref er( elm, p + start, q );
                    op->op( er, arg[ k % arg.size() ] );
                    k++;
                }
            }
            return k;
        }
References Eref::Eref(), Element::localDataStart(), Element::numField(), and Element::numLocalData().
Referenced by HopFunc1< A >::dataOpVec().
op()
template<class A > void HopFunc1< A >::op (const Eref & e, A arg) const inline virtual
Implements OpFunc1Base< A >.
Definition at line 51 of file HopFunc.h.
        {
            double* buf = addToBuf( e, hopIndex_, Conv< A >::size( arg ) );
            Conv< A >::val2buf( arg, &buf );
            dispatchBuffers( e, hopIndex_ );
        }
References dispatchBuffers(), and HopFunc1< A >::hopIndex_.
opVec()
template<class A > void HopFunc1< A >::opVec (const Eref & er, const vector< A > & arg, const OpFunc1Base< A > * op) const inline virtual
Reimplemented from OpFunc1Base< A >.
Definition at line 156 of file HopFunc.h.
        {
            Element* elm = er.element();
            if ( elm->hasFields() ) {
                if ( er.getNode() == mooseMyNode() ) {
            // True for globals as well as regular objects on current node
                    localFieldOpVec( er, arg, op );
                }
                if ( elm->isGlobal() || er.getNode() != mooseMyNode() ) {
                    // Go just to the node where the fields reside, and
                    // assign the vector there. May be all nodes if global.
                    remoteOpVec( er, arg, op, 0, arg.size() );
                }
            } else {
                dataOpVec( er, arg, op );
            }
        }
References HopFunc1< A >::dataOpVec(), Eref::element(), Eref::getNode(), Element::hasFields(), Element::isGlobal(), HopFunc1< A >::localFieldOpVec(), mooseMyNode(), and HopFunc1< A >::remoteOpVec().
remoteOpVec()
template<class A > unsigned int HopFunc1< A >::remoteOpVec (const Eref & er, const vector< A > & arg, const OpFunc1Base< A > * op, unsigned int start, unsigned int end) const inline
Dispatches remote vector assignment. start and end are arg index.
Definition at line 96 of file HopFunc.h.
        {
            unsigned int k = start;
            unsigned int nn = end - start;
            if ( mooseNumNodes() > 1 && nn > 0 ) {
                // nn includes dataIndices. FieldIndices are handled by
                // other functions.
                    vector< A > temp( nn );
                // Have to do the insertion entry by entry because the
                // argument vector may wrap around.
                for ( unsigned int j = 0; j < nn; ++j ) {
                    unsigned int x = k % arg.size();
                    temp[j] = arg[x];
                    k++;
                }
                double* buf = addToBuf( er, hopIndex_,
                        Conv< vector< A > >::size( temp ) );
                Conv< vector< A > >::val2buf( temp, &buf );
                dispatchBuffers( er, hopIndex_ );
                // HopIndex says that it is a SetVec call.
            }
            return k;
        }
References mooseNumNodes().
Referenced by HopFunc1< A >::dataOpVec(), and HopFunc1< A >::opVec().
Member Data Documentation
hopIndex_
template<class A > HopIndex HopFunc1< A >::hopIndex_ private
Definition at line 175 of file HopFunc.h.
Referenced by HopFunc1< A >::HopFunc1(), and HopFunc1< A >::op().
The documentation for this class was generated from the following file:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/basecode/HopFunc.h