MOOSE - Multiscale Object Oriented Simulation Environment: Neutral Class Reference
Neutral Class Reference
#include <Neutral.h>
Public Member Functions
void blockNodeBalance (const Eref &e, unsigned int, unsigned int, unsigned int)
unsigned int buildTree (const Eref &e, vector< Id > &tree) const
void destroy (const Eref &e, int stage)
void generalNodeBalance (const Eref &e, unsigned int myNode, vector< unsigned int > nodeAssignment)
vector< Id > getChildren (const Eref &e) const
string getClass (const Eref &e) const
vector< string > getDestFields (const Eref &e) const
Information function to return names of all DestFinfos.
double getDt (const Eref &e) const
Returns dt associated with this object based on its clock tick.
unsigned int getFieldIndex (const Eref &e) const
fieldIndex specifies field entry if FieldElement. Otherwise zero
unsigned int getId (const Eref &e) const
Id is the Id of the object, converted to unsigned int.
vector< ObjId > getIncomingMsgs (const Eref &e) const
unsigned int getIndex (const Eref &e) const
Index is the dataIndex of the object.
vector< string > getMsgDestFunctions (const Eref &e, string src) const
vector< ObjId > getMsgDests (const Eref &e, string src) const
string getName (const Eref &e) const
vector< Id > getNeighbors (const Eref &e, string field) const
unsigned int getNumData (const Eref &e) const
unsigned int getNumField (const Eref &e) const
ObjId getObjId (const Eref &e) const
vector< ObjId > getOutgoingMsgs (const Eref &e) const
ObjId getParent (const Eref &e) const
string getPath (const Eref &e) const
vector< string > getSourceFields (const Eref &e) const
Information function to return names of all SrcFinfos.
Neutral getThis () const
int getTick (const Eref &e) const
Returns clock tick of this object.
vector< string > getValueFields (const Eref &e) const
Information function to return names of all value Finfos.
bool isA (const Eref &e, string className) const
Neutral ()
void notifyAddMsgDest (const Eref &e, ObjId msgId)
void notifyAddMsgSrc (const Eref &e, ObjId msgId)
void notifyCopy (const Eref &e, ObjId orig)
void notifyCreate (const Eref &e, ObjId parent)
void notifyDestroy (const Eref &e)
Default notification functions, do nothing in the Neutral.
void notifyMove (const Eref &e, ObjId newParent)
void setName (const Eref &e, string name)
void setNumData (const Eref &e, unsigned int num)
void setNumField (const Eref &e, unsigned int num)
void setThis (Neutral v)
void setTick (const Eref &e, int num)
Static Public Member Functions
static Id child (const Eref &e, const string &name)
static void children (const Eref &e, vector< Id > &ret)
static const Cinfo * initCinfo ()
static bool isDescendant (Id me, Id ancestor)
static bool isGlobalField (const string &field)
static ObjId parent (const Eref &e)
static ObjId parent (ObjId id)
static string path (const Eref &e)
Friends
ostream & operator<< (ostream &s, const Neutral &d)
istream & operator>> (istream &s, Neutral &d)
Detailed Description
Definition at line 14 of file Neutral.h.
Constructor & Destructor Documentation
Neutral()
Neutral::Neutral ()
Definition at line 257 of file Neutral.cpp.
{
    ;
}
Member Function Documentation
blockNodeBalance()
void Neutral::blockNodeBalance (const Eref & e, unsigned int , unsigned int , unsigned int)
Request conversion of data into a blockDataHandler subclass, and to carry out node balancing of data as per args.
Definition at line 615 of file Neutral.cpp.
{
}
Referenced by initCinfo().
buildTree()
unsigned int Neutral::buildTree (const Eref & e, vector< Id > & tree) const
Builds a vector of all descendants of e
Definition at line 557 of file Neutral.cpp.
{
    unsigned int ret = 1;
    Eref er(e.element(), ALLDATA);
    vector<Id> kids = getChildren(er);
    sort(kids.begin(), kids.end());
    kids.erase(unique(kids.begin(), kids.end()), kids.end());
    for(vector<Id>::iterator i = kids.begin(); i != kids.end(); ++i)
        ret += buildTree(i->eref(), tree);
    tree.push_back(e.element()->id());
    return ret;
}
References ALLDATA, buildTree(), Eref::element(), Id::eref(), Eref::Eref(), getChildren(), and Element::id().
Referenced by buildTree(), destroy(), and verifyKids().
child()
Id Neutral::child (const Eref & e, const string & name) static
Finds specific named child
Definition at line 652 of file Neutral.cpp.
{
    static const Finfo* pf = neutralCinfo->findFinfo("parentMsg");
    static const DestFinfo* pf2 = dynamic_cast<const DestFinfo*>(pf);
    static const FuncId pafid = pf2->getFid();
    static const Finfo* cf = neutralCinfo->findFinfo("childOut");
    static const SrcFinfo* cf2 = dynamic_cast<const SrcFinfo*>(cf);
    static const BindIndex bi = cf2->getBindIndex();
    const vector<MsgFuncBinding>* bvec = e.element()->getMsgAndFunc(bi);
    vector<Id> ret;
    for(vector<MsgFuncBinding>::const_iterator i = bvec->begin();
        i != bvec->end(); ++i) {
        if(i->fid == pafid) {
            const Msg* m = Msg::getMsg(i->mid);
            assert(m);
            Element* e2 = m->e2();
            if(e2->getName() == name) {
                if(e.dataIndex() == ALLDATA)  // Child of any index is OK
                {
                    return e2->id();
                } else {
                    ObjId parent = m->findOtherEnd(m->getE2());
                    // If child is a fieldElement, then all parent indices
                    // are permitted. Otherwise insist parent dataIndex OK.
                    if(e2->hasFields() || parent == e.objId())
                        return e2->id();
                }
            }
        }
    }
    return Id();
}
References ALLDATA, Eref::dataIndex(), Msg::e2(), Eref::element(), MsgFuncBinding::fid, Cinfo::findFinfo(), Msg::findOtherEnd(), SrcFinfo::getBindIndex(), Msg::getE2(), DestFinfo::getFid(), Msg::getMsg(), Element::getMsgAndFunc(), Element::getName(), Element::hasFields(), Id::Id(), Element::id(), MsgFuncBinding::mid, neutralCinfo, Eref::objId(), and ObjId::operator==().
Referenced by ReadKkit::assignPoolCompartments(), buildFromProto(), ReadKkit::buildSumTotal(), SetGet::checkSet(), ReadKkit::convertKineticsToGroup(), doClassSpecificMessaging(), Shell::doCopy(), Shell::doCreate(), Shell::doFind(), Shell::doMove(), ReadKkit::findCompartmentsFromAnnotation(), kineticsHasReactions(), setName(), Neuron::setSpineAndPsdMesh(), testCopy(), and testTreeTraversal().
children()
void Neutral::children (const Eref & e, vector< Id > & ret) static
return ids of all the children in ret.
Definition at line 325 of file Neutral.cpp.
{
    /*
    vector< Id > temp;
    getNeighbors( ret, neutralCinfo->findFinfo( "childOut" ) );
    for ( vector< Id >::iterator i = temp.begin(); i != temp.end(); ++i ) {
    if ( ret
    }
    */
    static const Finfo* pf = neutralCinfo->findFinfo("parentMsg");
    static const DestFinfo* pf2 = dynamic_cast<const DestFinfo*>(pf);
    static const FuncId pafid = pf2->getFid();
    static const Finfo* cf = neutralCinfo->findFinfo("childOut");
    static const SrcFinfo* cf2 = dynamic_cast<const SrcFinfo*>(cf);
    static const BindIndex bi = cf2->getBindIndex();
    const vector<MsgFuncBinding>* bvec = e.element()->getMsgAndFunc(bi);
    for(vector<MsgFuncBinding>::const_iterator i = bvec->begin();
        i != bvec->end(); ++i) {
        if(i->fid == pafid) {
            const Msg* m = Msg::getMsg(i->mid);
            assert(m);
            vector<vector<Eref>> kids;
            m->targets(kids);
            if(e.dataIndex() == ALLDATA) {
                for(vector<vector<Eref>>::iterator i = kids.begin();
                    i != kids.end(); ++i) {
                    for(vector<Eref>::iterator j = i->begin(); j != i->end();
                        ++j)
                        ret.push_back(j->id());
                }
            } else {
                const vector<Eref>& temp = kids[e.dataIndex()];
                for(vector<Eref>::const_iterator i = temp.begin();
                    i != temp.end(); ++i)
                    ret.push_back(i->id());
            }
        }
    }
}
References ALLDATA, Eref::dataIndex(), Eref::element(), MsgFuncBinding::fid, Cinfo::findFinfo(), SrcFinfo::getBindIndex(), DestFinfo::getFid(), Msg::getMsg(), Element::getMsgAndFunc(), Eref::id(), MsgFuncBinding::mid, neutralCinfo, and Msg::targets().
Referenced by ReadCell::addChannelMessage(), addSpine(), allChildren(), Neuron::buildSegmentTree(), checkChildren(), pymoose::MooseVec::children(), Cell::children(), HSolve::children(), Shell::cleanSimulation(), ReadKkit::convertKineticsToGroup(), ReadCspace::deployParameters(), ReadKkit::findCompartmentsFromAnnotation(), ChemCompt::getChildConcs(), getChildren(), hasScaleFormula(), innerCopyElements(), kineticsHasReactions(), ReadCspace::makePlots(), ChemCompt::setChildConcs(), singleLevelWildcard(), testCopyFieldElement(), testTable(), and verifyKids().
destroy()
void Neutral::destroy (const Eref & e, int stage)
Destroys Element and all children
Definition at line 593 of file Neutral.cpp.
{
    if(e.element()->cinfo()->isA("Msg")) {
        Msg::deleteMsg(e.objId());
        return;
    }
    vector<Id> tree;
    Eref er(e.element(), ALLDATA);
    unsigned int numDescendants = buildTree(er, tree);
    /*
    cout << "Neutral::destroy: id = " << e.id() <<
        ", name = " << e.element()->getName() <<
        ", numDescendants = " << numDescendants << endl;
        */
    assert(numDescendants == tree.size());
    Element::destroyElementTree(tree);
}
References ALLDATA, buildTree(), Element::cinfo(), Msg::deleteMsg(), Element::destroyElementTree(), Eref::element(), Eref::Eref(), Cinfo::isA(), and Eref::objId().
Referenced by Shell::destroy(), and initCinfo().
generalNodeBalance()
void Neutral::generalNodeBalance (const Eref & e, unsigned int myNode, vector< unsigned int > nodeAssignment)
Request conversion of data into a generalDataHandler subclass, and to carry out node balancing of data as per args.
Definition at line 624 of file Neutral.cpp.
{
}
Referenced by initCinfo().
getChildren()
vector< Id > Neutral::getChildren (const Eref & e) const
Looks up all the Element children of the current Element
Gets Element children, not individual entries in the array.
Definition at line 317 of file Neutral.cpp.
{
    vector<Id> ret;
    children(e, ret);
    return ret;
}
References children().
Referenced by buildTree(), initCinfo(), testCopy(), and testMove().
getClass()
string Neutral::getClass (const Eref & e) const
Looks up the Class name of the current Element
Definition at line 373 of file Neutral.cpp.
{
    return e.element()->cinfo()->name();
}
References Element::cinfo(), Eref::element(), and Cinfo::name().
Referenced by initCinfo().
getDestFields()
vector< string > Neutral::getDestFields (const Eref & e) const
Information function to return names of all DestFinfos.
Definition at line 460 of file Neutral.cpp.
{
    unsigned int num = e.element()->cinfo()->getNumDestFinfo();
    vector<string> ret(num);
    for(unsigned int i = 0; i < num; ++i) {
        const Finfo* f = e.element()->cinfo()->getDestFinfo(i);
        assert(f);
        ret[i] = f->name();
    }
    return ret;
}
References Element::cinfo(), Eref::element(), Cinfo::getDestFinfo(), Cinfo::getNumDestFinfo(), and Finfo::name().
Referenced by initCinfo().
getDt()
double Neutral::getDt (const Eref & e) const
Returns dt associated with this object based on its clock tick.
Definition at line 427 of file Neutral.cpp.
{
    int tick = e.element()->getTick();
    if(tick < 0)
        return 0.0;
    Id clockId(1);
    return LookupField<unsigned int, double>::get(clockId, "tickDt", tick);
}
References Eref::element(), LookupField< L, A >::get(), Element::getTick(), and Id::Id().
Referenced by initCinfo().
getFieldIndex()
unsigned int Neutral::getFieldIndex (const Eref & e) const
fieldIndex specifies field entry if FieldElement. Otherwise zero
Definition at line 412 of file Neutral.cpp.
{
    return e.fieldIndex();
}
References Eref::fieldIndex().
Referenced by initCinfo().
getId()
unsigned int Neutral::getId (const Eref & e) const
Id is the Id of the object, converted to unsigned int.
Definition at line 402 of file Neutral.cpp.
{
    return e.id().value();
}
References Eref::id(), and Id::value().
Referenced by initCinfo().
getIncomingMsgs()
vector< ObjId > Neutral::getIncomingMsgs (const Eref & e) const
Readonly field access function for getting all incoming Msgs.
Definition at line 489 of file Neutral.cpp.
{
    vector<ObjId> ret;
    const vector<ObjId>& msgIn = e.element()->msgIn();
    for(unsigned int i = 0; i < msgIn.size(); ++i) {
        const Msg* m = Msg::getMsg(msgIn[i]);
        assert(m);
        if(m->e2() == e.element())
            ret.push_back(m->mid());
    }
    return ret;
}
References Msg::e2(), Eref::element(), Msg::getMsg(), Msg::mid(), and Element::msgIn().
Referenced by initCinfo().
getIndex()
unsigned int Neutral::getIndex (const Eref & e) const
Index is the dataIndex of the object.
Definition at line 407 of file Neutral.cpp.
{
    return e.dataIndex();
}
References Eref::dataIndex().
Referenced by initCinfo().
getMsgDestFunctions()
vector< string > Neutral::getMsgDestFunctions (const Eref & e, string src) const
Return vector of function names called on each target ObjId of the specified SrcFinfo, by the current object. Twin function to getMsgDests.
Definition at line 532 of file Neutral.cpp.
{
    vector<string> ret(0);
    const Finfo* finfo = e.element()->cinfo()->findFinfo(field);
    const SrcFinfo* sf = dynamic_cast<const SrcFinfo*>(finfo);
    if(sf) {
        vector<ObjId> tgt;
        vector<string> func;
        e.element()->getMsgTargetAndFunctions(e.dataIndex(), sf, tgt, func);
        return func;
    } else {
        cout << "Warning: Neutral::getMsgDestFunctions: Id.Field '"
             << e.id().path() << "." << field
             << "' not found or not a SrcFinfo\n";
    }
    return ret;
}
References Element::cinfo(), Eref::dataIndex(), Eref::element(), Cinfo::findFinfo(), Element::getMsgTargetAndFunctions(), Eref::id(), and Id::path().
Referenced by initCinfo().
getMsgDests()
vector< ObjId > Neutral::getMsgDests (const Eref & e, string src) const
Return vector of target ObjIds called by the specified SrcFinfo, by the current object. Twin function to getMsgDestFunctions.
Definition at line 515 of file Neutral.cpp.
{
    const Finfo* finfo = e.element()->cinfo()->findFinfo(field);
    const SrcFinfo* sf = dynamic_cast<const SrcFinfo*>(finfo);
    if(sf) {
        vector<ObjId> tgt;
        vector<string> func;
        e.element()->getMsgTargetAndFunctions(e.dataIndex(), sf, tgt, func);
        return tgt;
    } else {
        cout << "Warning: Neutral::getMsgDests: Id.Field '" << e.id().path()
             << "." << field << "' not found or not a SrcFinfo\n";
    }
    static vector<ObjId> ret(0);
    return ret;
}
References Element::cinfo(), Eref::dataIndex(), Eref::element(), Cinfo::findFinfo(), Element::getMsgTargetAndFunctions(), Eref::id(), and Id::path().
Referenced by initCinfo().
getName()
string Neutral::getName (const Eref & e) const
Definition at line 299 of file Neutral.cpp.
{
    return e.element()->getName();
}
References Eref::element(), and Element::getName().
Referenced by initCinfo().
getNeighbors()
vector< Id > Neutral::getNeighbors (const Eref & e, string field) const
Readonly field access function for getting Ids connected to current Id via specified Field. Field is specified by its name. Returns an empty vector if it fails.
Definition at line 503 of file Neutral.cpp.
{
    vector<Id> ret;
    const Finfo* finfo = e.element()->cinfo()->findFinfo(field);
    if(finfo)
        e.element()->getNeighbors(ret, finfo);
    else
        cout << "Warning: Neutral::getNeighbors: Id.Field '" << e.id().path()
             << "." << field << "' not found\n";
    return ret;
}
References Element::cinfo(), Eref::element(), Cinfo::findFinfo(), Element::getNeighbors(), Eref::id(), and Id::path().
Referenced by initCinfo().
getNumData()
unsigned int Neutral::getNumData (const Eref & e) const
Definition at line 378 of file Neutral.cpp.
{
    return e.element()->numData();
}
References Eref::element(), and Element::numData().
Referenced by initCinfo().
getNumField()
unsigned int Neutral::getNumField (const Eref & e) const
Definition at line 388 of file Neutral.cpp.
{
    assert(e.isDataHere());
    unsigned int rawIndex = e.element()->rawIndex(e.dataIndex());
    return e.element()->numField(rawIndex);
}
References Eref::dataIndex(), Eref::element(), Eref::isDataHere(), Element::numField(), and Element::rawIndex().
Referenced by initCinfo().
getObjId()
ObjId Neutral::getObjId (const Eref & e) const
Simply returns own ObjId
Definition at line 304 of file Neutral.cpp.
{
    return e.objId();
}
References Eref::objId().
Referenced by initCinfo().
getOutgoingMsgs()
vector< ObjId > Neutral::getOutgoingMsgs (const Eref & e) const
Readonly field access function for getting all outgoing Msgs.
Definition at line 472 of file Neutral.cpp.
{
    vector<ObjId> ret;
    unsigned int numBindIndex = e.element()->cinfo()->numBindIndex();
    for(unsigned int i = 0; i < numBindIndex; ++i) {
        const vector<MsgFuncBinding>* v = e.element()->getMsgAndFunc(i);
        if(v) {
            for(vector<MsgFuncBinding>::const_iterator mb = v->begin();
                mb != v->end(); ++mb) {
                ret.push_back(mb->mid);
            }
        }
    }
    return ret;
}
References Element::cinfo(), Eref::element(), Element::getMsgAndFunc(), MsgFuncBinding::mid, and Cinfo::numBindIndex().
Referenced by initCinfo().
getParent()
ObjId Neutral::getParent (const Eref & e) const
Looks up the full Id info for the parent of the current Element
Definition at line 309 of file Neutral.cpp.
{
    return parent(e);
}
References parent().
Referenced by initCinfo(), and testCopy().
getPath()
string Neutral::getPath (const Eref & e) const
Traverses to root, building path.
Definition at line 368 of file Neutral.cpp.
{
    return path(e);
}
References path().
Referenced by initCinfo().
getSourceFields()
vector< string > Neutral::getSourceFields (const Eref & e) const
Information function to return names of all SrcFinfos.
Definition at line 448 of file Neutral.cpp.
{
    unsigned int num = e.element()->cinfo()->getNumSrcFinfo();
    vector<string> ret(num);
    for(unsigned int i = 0; i < num; ++i) {
        const Finfo* f = e.element()->cinfo()->getSrcFinfo(i);
        assert(f);
        ret[i] = f->name();
    }
    return ret;
}
References Element::cinfo(), Eref::element(), Cinfo::getNumSrcFinfo(), Cinfo::getSrcFinfo(), and Finfo::name().
Referenced by initCinfo().
getThis()
Neutral Neutral::getThis () const
Field access functions for the entire object. For Neutrals the getThis function does return the Neutral object, but it has no data to set. However, the function name acts as a placeholder and derived objects can override the function so that the entire object can be accessed as a field and also used for inter-node data transfer.
Definition at line 271 of file Neutral.cpp.
{
    return *this;
}
Referenced by initCinfo().
getTick()
int Neutral::getTick (const Eref & e) const
Returns clock tick of this object.
Definition at line 417 of file Neutral.cpp.
{
    return e.element()->getTick();
}
References Eref::element(), and Element::getTick().
Referenced by initCinfo().
getValueFields()
vector< string > Neutral::getValueFields (const Eref & e) const
Information function to return names of all value Finfos.
Definition at line 436 of file Neutral.cpp.
{
    unsigned int num = e.element()->cinfo()->getNumValueFinfo();
    vector<string> ret(num);
    for(unsigned int i = 0; i < num; ++i) {
        const Finfo* f = e.element()->cinfo()->getValueFinfo(i);
        assert(f);
        ret[i] = f->name();
    }
    return ret;
}
References Element::cinfo(), Eref::element(), Cinfo::getNumValueFinfo(), Cinfo::getValueFinfo(), and Finfo::name().
Referenced by initCinfo().
initCinfo()
const Cinfo * Neutral::initCinfo () static
Standard initialization function, used whenever we want to look up the class Cinfo
Definition at line 16 of file Neutral.cpp.
{
    // Element Value Finfos
    static ElementValueFinfo<Neutral, string> name(
        "name", "Name of object", &Neutral::setName, &Neutral::getName);
    // Should be renamed to myId
    static ReadOnlyElementValueFinfo<Neutral, ObjId> me(
        "me", "ObjId for current object", &Neutral::getObjId);
    static ReadOnlyElementValueFinfo<Neutral, ObjId> parent(
        "parent", "Parent ObjId for current object", &Neutral::getParent);
    static ReadOnlyElementValueFinfo<Neutral, vector<Id>> children(
        "children", "vector of ObjIds listing all children of current object",
        &Neutral::getChildren);
    static ReadOnlyElementValueFinfo<Neutral, string> path(
        "path", "text path for object", &Neutral::getPath);
    static ReadOnlyElementValueFinfo<Neutral, string> className(
        "className", "Class Name of object", &Neutral::getClass);
    static ElementValueFinfo<Neutral, unsigned int> numData(
        "numData",
        "# of Data entries on Element."
        "Note that on a FieldElement this does NOT refer to field entries,"
        "but to the number of DataEntries on the parent of the "
        "FieldElement.",
        &Neutral::setNumData, &Neutral::getNumData);
    static ElementValueFinfo<Neutral, unsigned int> numField(
        "numField",
        "For a FieldElement: number of entries of self."
        "For a regular Element: One.",
        &Neutral::setNumField, &Neutral::getNumField);
    static ReadOnlyElementValueFinfo<Neutral, unsigned int> id(
        "idValue", "Object id of self, converted to an unsigned int.",
        &Neutral::getId);
    static ReadOnlyElementValueFinfo<Neutral, unsigned int> index(
        "index",
        "For a FieldElement: Object index of parent."
        "For a regular Element: Object index (dataId) of self.",
        &Neutral::getIndex);
    static ReadOnlyElementValueFinfo<Neutral, unsigned int> fieldIndex(
        "fieldIndex",
        "For a FieldElement: field Index of self."
        "For a regular Element: zero.",
        &Neutral::getFieldIndex);
    static ElementValueFinfo<Neutral, int> tick(
        "tick",
        "Clock tick for this Element for periodic execution in the "
        "main simulation event loop. A default is normally assigned, "
        "based on object class, but one can override to any value "
        "between 0 and 19. Assigning to -1 means that the object is "
        "disabled and will not be called during simulation execution "
        "The actual timestep (dt) belonging to a clock tick is defined "
        "by the Clock object.",
        &Neutral::setTick, &Neutral::getTick);
    static ReadOnlyElementValueFinfo<Neutral, double> dt(
        "dt", "Timestep used for this Element. Zero if not scheduled.",
        &Neutral::getDt);
    static ReadOnlyElementValueFinfo<Neutral, vector<string>> valueFields(
        "valueFields",
        "List of all value fields on Element."
        "These fields are accessed through the assignment operations "
        "in the Python interface."
        "These fields may also be accessed as functions through the "
        "set<FieldName> and get<FieldName> commands.",
        &Neutral::getValueFields);
    static ReadOnlyElementValueFinfo<Neutral, vector<string>> sourceFields(
        "sourceFields",
        "List of all source fields on Element, that is fields that "
        "can act as message sources. ",
        &Neutral::getSourceFields);
    static ReadOnlyElementValueFinfo<Neutral, vector<string>> destFields(
        "destFields",
        "List of all destination fields on Element, that is, fields"
        "that are accessed as Element functions.",
        &Neutral::getDestFields);
    static ReadOnlyElementValueFinfo<Neutral, vector<ObjId>> msgOut(
        "msgOut", "Messages going out from this Element",
        &Neutral::getOutgoingMsgs);
    static ReadOnlyElementValueFinfo<Neutral, vector<ObjId>> msgIn(
        "msgIn", "Messages coming in to this Element",
        &Neutral::getIncomingMsgs);
    static ReadOnlyLookupElementValueFinfo<Neutral, string, vector<Id>>
        neighbors("neighbors",
                  "Ids of Elements connected this Element on specified field.",
                  &Neutral::getNeighbors);
    static ReadOnlyLookupElementValueFinfo<Neutral, string, vector<ObjId>>
        msgDests("msgDests",
                 "ObjIds receiving messages from the specified SrcFinfo",
                 &Neutral::getMsgDests);
    static ReadOnlyLookupElementValueFinfo<Neutral, string, vector<string>>
        msgDestFunctions(
            "msgDestFunctions",
            "Matching function names for each ObjId receiving a msg from "
            "the specified SrcFinfo",
            &Neutral::getMsgDestFunctions);
    static ReadOnlyLookupElementValueFinfo<Neutral, string, bool> isA(
        "isA",
        "Returns true if the current object is derived from the specified "
        "the specified class",
        &Neutral::isA);
    // Value Finfos
    static ValueFinfo<Neutral, Neutral> thisFinfo(
        "this", "Access function for entire object", &Neutral::setThis,
        &Neutral::getThis);
    // SrcFinfos
    static SrcFinfo1<int> childOut("childOut", "Message to child Elements");
    // DestFinfos
    static DestFinfo notifyCreate("notifyCreate",
                "Called when object is created. Arg is parent.",
                new EpFunc1<Neutral, ObjId >(&Neutral::notifyCreate));
    static DestFinfo notifyCopy("notifyCopy",
                "Called when object is copied. Arg is original.",
                new EpFunc1<Neutral, ObjId >(&Neutral::notifyCreate));
    static DestFinfo notifyDestroy("notifyDestroy",
                "Called when object is destroyed.",
                new EpFunc0<Neutral>(&Neutral::notifyDestroy));
    static DestFinfo notifyMove("notifyMove",
                "Called when object is moved. Arg is new parent.",
                new EpFunc1<Neutral, ObjId>(&Neutral::notifyMove));
    static DestFinfo notifyAddMsgSrc("notifyAddMsgSrc",
                "Called when a message is created, current object is src. Arg is msgId.",
                new EpFunc1<Neutral, ObjId>(&Neutral::notifyAddMsgSrc));
    static DestFinfo notifyAddMsgDest("notifyAddMsgDest",
                "Called when a message is created, current object is dest. Arg is msgId.",
                new EpFunc1<Neutral, ObjId>(&Neutral::notifyAddMsgDest));
    static DestFinfo parentMsg("parentMsg", "Message from Parent Element(s)",
                new EpFunc1<Neutral, int>(&Neutral::destroy));
    static DestFinfo blockNodeBalance(
        "blockNodeBalance",
        "Request conversion of data into a blockDataHandler subclass,"
        "and to carry out node balancing of data."
        "The amount of data is not altered, and if the data is already a"
        "blockDataHandler subclass it retains its original dimensions"
        "If converting from a generalDataHandler to blockHandler it treats"
        "it as a linear array"
        "The function preserves the old data and shuffles info around"
        "between nodes to complete the balancing."
        "Arguments are: myNode, startNode, endNode",
        new EpFunc3<Neutral, unsigned int, unsigned int, unsigned int>(
            &Neutral::blockNodeBalance));
    static DestFinfo generalNodeBalance(
        "generalNodeBalance",
        "Request conversion of data into a generalDataHandler subclass,"
        "and to carry out node balancing of data as per specified args."
        "The amount of data is not altered. The generalDataHandler loses"
        "any dimensional information that may have been present in an "
        "earlier blockDataHandler incarnation."
        "Arguments are: myNode, nodeAssignment",
        new EpFunc2<Neutral, unsigned int, vector<unsigned int>>(
            &Neutral::generalNodeBalance));
    // Setting up the Finfo list.
    static Finfo* neutralFinfos[] = {&childOut,          // SrcFinfo
                                     &parentMsg,         // DestFinfo
                                     &thisFinfo,         // Value
                                     &name,              // Value
                                     &me,                // ReadOnlyValue
                                     &parent,            // ReadOnlyValue
                                     &children,          // ReadOnlyValue
                                     &path,              // ReadOnlyValue
                                     &className,         // ReadOnlyValue
                                     &numData,           // Value
                                     &numField,          // Value
                                     &id,                // ReadOnlyValue
                                     &index,             // ReadOnlyValue
                                     &fieldIndex,        // ReadOnlyValue
                                     &tick,              // Value
                                     &dt,                // ReadOnlyValue
                                     &valueFields,       // ReadOnlyValue
                                     &sourceFields,      // ReadOnlyValue
                                     &destFields,        // ReadOnlyValue
                                     &msgOut,            // ReadOnlyValue
                                     &msgIn,             // ReadOnlyValue
                                     &neighbors,         // ReadOnlyLookupValue
                                     &msgDests,          // ReadOnlyLookupValue
                                     &msgDestFunctions,  // ReadOnlyLookupValue
                                     &isA,               // ReadOnlyLookupValue
                                     &notifyCreate,      // DestFinfo
                                     &notifyCopy,        // DestFinfo
                                     &notifyDestroy,     // DestFinfo
                                     &notifyMove,        // DestFinfo
                                     &notifyAddMsgSrc,   // DestFinfo
                                     &notifyAddMsgDest,  // DestFinfo
    };
    // Setting up the Cinfo.
    static string doc[] = {
        "Name", "Neutral", "Author", "Upinder S. Bhalla, 2007, NCBS",
        "Description",
        "Neutral: Base class for all MOOSE classes. Provides"
        "access functions for housekeeping fields and operations, message"
        "traversal, and so on."};
    static Dinfo<Neutral> dinfo;
    static Cinfo neutralCinfo("Neutral", 0,  // No base class.
                              neutralFinfos,
                              sizeof(neutralFinfos) / sizeof(Finfo*), &dinfo,
                              doc, sizeof(doc) / sizeof(string));
    return &neutralCinfo;
}
References blockNodeBalance(), Cinfo::Cinfo(), DestFinfo::DestFinfo(), destroy(), ElementValueFinfo< T, F >::ElementValueFinfo(), EpFunc0< T >::EpFunc0(), EpFunc1< T, A >::EpFunc1(), EpFunc2< T, A1, A2 >::EpFunc2(), EpFunc3< T, A1, A2, A3 >::EpFunc3(), generalNodeBalance(), getChildren(), getClass(), getDestFields(), getDt(), getFieldIndex(), getId(), getIncomingMsgs(), getIndex(), getMsgDestFunctions(), getMsgDests(), getName(), getNeighbors(), getNumData(), getNumField(), getObjId(), getOutgoingMsgs(), getParent(), getPath(), getSourceFields(), getThis(), getTick(), getValueFields(), isA(), notifyAddMsgDest(), notifyAddMsgSrc(), notifyCreate(), notifyDestroy(), notifyMove(), ReadOnlyElementValueFinfo< T, F >::ReadOnlyElementValueFinfo(), ReadOnlyLookupElementValueFinfo< T, L, F >::ReadOnlyLookupElementValueFinfo(), setName(), setNumData(), setNumField(), setThis(), setTick(), SrcFinfo1< T >::SrcFinfo1(), and ValueFinfo< T, F >::ValueFinfo().
Referenced by Shell::adopt(), init(), Cinfo::initCinfo(), Finfo::initCinfo(), TestId::initCinfo(), CaConcBase::initCinfo(), ChanBase::initCinfo(), moose::CompartmentBase::initCinfo(), DifBufferBase::initCinfo(), DifShellBase::initCinfo(), GapJunction::initCinfo(), HHGate::initCinfo(), HHGate2D::initCinfo(), HHGateF::initCinfo(), IntFire::initCinfo(), IzhikevichNrn::initCinfo(), MarkovOdeSolver::initCinfo(), MarkovRateTable::initCinfo(), MarkovSolverBase::initCinfo(), MMPump::initCinfo(), Nernst::initCinfo(), Neuron::initCinfo(), RandSpike::initCinfo(), SpikeGen::initCinfo(), Spine::initCinfo(), moose::VClamp::initCinfo(), VectorTable::initCinfo(), Arith::initCinfo(), Group::initCinfo(), Interpol2D::initCinfo(), Mstring::initCinfo(), Stats::initCinfo(), TableBase::initCinfo(), Variable::initCinfo(), DiffAmp::initCinfo(), PIDController::initCinfo(), PulseGen::initCinfo(), RC::initCinfo(), Dsolve::initCinfo(), Cell::initCinfo(), HSolve::initCinfo(), ConcChan::initCinfo(), EnzBase::initCinfo(), Reac::initCinfo(), Species::initCinfo(), Gsolve::initCinfo(), Ksolve::initCinfo(), SteadyState::initCinfo(), Stoich::initCinfo(), Boundary::initCinfo(), ChemCompt::initCinfo(), MeshEntry::initCinfo(), PostMaster::initCinfo(), Msg::initCinfo(), PyRun::initCinfo(), Clock::initCinfo(), Shell::initCinfo(), Adaptor::initCinfo(), Synapse::initCinfo(), SynHandlerBase::initCinfo(), Annotator::initCinfo(), Msg::initMsgManagers(), PoolBase::initPoolBaseCinfo(), innerCopyMsgs(), Shell::innerMove(), Cinfo::isA(), FieldElementFinfoBase::postCreationFunc(), showFields(), testCinfoFields(), testFinfoFields(), testIsA(), and testSetGetExtField().
isA()
bool Neutral::isA (const Eref & e, string className) const
Returns True if the object is derived from the specified class
Definition at line 550 of file Neutral.cpp.
{
    return e.element()->cinfo()->isA(className);
}
References Element::cinfo(), Eref::element(), and Cinfo::isA().
Referenced by initCinfo().
isDescendant()
bool Neutral::isDescendant (Id me, Id ancestor) static
Checks if 'me' is a descendant of 'ancestor'
Definition at line 634 of file Neutral.cpp.
{
    static const Finfo* pf = neutralCinfo->findFinfo("parentMsg");
    static const DestFinfo* pf2 = dynamic_cast<const DestFinfo*>(pf);
    static const FuncId pafid = pf2->getFid();
    Eref e = me.eref();
    while(e.element()->id() != Id() && e.element()->id() != ancestor) {
        ObjId mid = e.element()->findCaller(pafid);
        assert(mid != ObjId());
        ObjId fid = Msg::getMsg(mid)->findOtherEnd(e.objId());
        e = fid.eref();
    }
    return (e.element()->id() == ancestor);
}
References Eref::element(), Id::eref(), ObjId::eref(), Element::findCaller(), Cinfo::findFinfo(), Msg::findOtherEnd(), DestFinfo::getFid(), Msg::getMsg(), Id::Id(), Element::id(), neutralCinfo, ObjId::ObjId(), Eref::objId(), Id::operator!=(), ObjId::operator!=(), and Id::operator==().
Referenced by Shell::doCopy(), Shell::doMove(), and testDescendant().
isGlobalField()
bool Neutral::isGlobalField (const string & field) static
Checks if specified field is a global, typically because it is present on the Element and therefore should be assigned uniformly on all nodes
Definition at line 769 of file Neutral.cpp.
{
    if(field.length() < 8)
        return 0;
    if(field.substr(0, 4) == "set_") {
        if(field == "set_name")
            return 1;
        if(field == "set_group")
            return 1;
        if(field == "set_lastDimension")  // This is the critical one!
            return 1;
    }
    return 0;
}
notifyAddMsgDest()
void Neutral::notifyAddMsgDest (const Eref & e, ObjId msgId)
Definition at line 584 of file Neutral.cpp.
{;}
Referenced by initCinfo().
notifyAddMsgSrc()
void Neutral::notifyAddMsgSrc (const Eref & e, ObjId msgId)
Definition at line 582 of file Neutral.cpp.
{;}
Referenced by initCinfo().
notifyCopy()
void Neutral::notifyCopy (const Eref & e, ObjId orig)
Definition at line 578 of file Neutral.cpp.
{;}
notifyCreate()
void Neutral::notifyCreate (const Eref & e, ObjId parent)
Definition at line 576 of file Neutral.cpp.
{;}
Referenced by initCinfo().
notifyDestroy()
void Neutral::notifyDestroy (const Eref & e)
Default notification functions, do nothing in the Neutral.
Called before object is destroyed, to set its affairs in order. Notably, if it is under a solver, it tells solver goodbye.
Definition at line 574 of file Neutral.cpp.
{;}
Referenced by initCinfo().
notifyMove()
void Neutral::notifyMove (const Eref & e, ObjId newParent)
Definition at line 580 of file Neutral.cpp.
{;}
Referenced by initCinfo().
parent() [1/2]
ObjId Neutral::parent (const Eref & e) static
Returns parent object
Definition at line 689 of file Neutral.cpp.
{
    return Neutral::parent(e.objId());
}
References Eref::objId(), and parent().
Referenced by Synapse::addMsgCallback(), Shell::doFind(), Synapse::dropMsgCallback(), getCompt(), getParent(), ReadCspace::printMol(), MeshEntry::reinit(), setName(), storeFunctionMsgs(), and testObjIdToAndFromPath().
parent() [2/2]
ObjId Neutral::parent (ObjId id) static
Definition at line 694 of file Neutral.cpp.
{
    static const Finfo* pf = neutralCinfo->findFinfo("parentMsg");
    static const DestFinfo* pf2 = dynamic_cast<const DestFinfo*>(pf);
    static const FuncId pafid = pf2->getFid();
    if(oid.id == Id()) {
        cout << "Warning: Neutral::parent: tried to take parent of root\n";
        return Id();
    }
    ObjId mid = oid.element()->findCaller(pafid);
    assert(mid != ObjId());
    ObjId pa = Msg::getMsg(mid)->findOtherEnd(oid);
    return pa;
}
References ObjId::element(), Element::findCaller(), Cinfo::findFinfo(), Msg::findOtherEnd(), DestFinfo::getFid(), Msg::getMsg(), Id::Id(), ObjId::id, neutralCinfo, ObjId::ObjId(), ObjId::operator!=(), and Id::operator==().
Referenced by addSpine(), doClassSpecificMessaging(), ReadKkit::findCompartmentsFromAnnotation(), findModelParent(), innerCopyElements(), pymoose::MooseVec::parent(), and parent().
path()
string Neutral::path (const Eref & e) static
Finds the path of element e
Definition at line 713 of file Neutral.cpp.
{
    static const Finfo* pf = neutralCinfo->findFinfo("parentMsg");
    static const DestFinfo* pf2 = dynamic_cast<const DestFinfo*>(pf);
    static const FuncId pafid = pf2->getFid();
    vector<ObjId> pathVec;
    ObjId curr = e.objId();
    stringstream ss;
    pathVec.push_back(curr);
    while(curr.id != Id()) {
        ObjId mid = curr.eref().element()->findCaller(pafid);
        if(mid == ObjId()) {
            cout << "Error: Neutral::path:Cannot follow msg of ObjId: "
                 << e.objId() << " for func: " << pafid << endl;
            break;
        }
        curr = Msg::getMsg(mid)->findOtherEnd(curr);
        pathVec.push_back(curr);
    }
    if(pathVec.size() <= 1)
        return "/";
    for(unsigned int i = 1; i < pathVec.size(); ++i) {
        ss << "/";
        ObjId& oid = pathVec[pathVec.size() - i - 1];
        ss << oid.element()->getName();
        if(!oid.element()->hasFields())
            ss << "[" << oid.dataIndex << "]";
        /*
        if ( !oid.element()->hasFields() )
                ss << "[" << oid.dataIndex << "]";
        if ( oid.element()->numData() > 1 )
                ss << "[" << oid.dataIndex << "]";
                */
    }
    // Append braces if Eref was for a fieldElement. This should
    // work even if it is off-node.
    if(e.element()->hasFields()) {
        ss << "[" << e.fieldIndex() << "]";
    }
    return ss.str();
}
References ObjId::dataIndex, Eref::element(), ObjId::element(), ObjId::eref(), Eref::fieldIndex(), Element::findCaller(), Cinfo::findFinfo(), Msg::findOtherEnd(), DestFinfo::getFid(), Msg::getMsg(), Element::getName(), Element::hasFields(), Id::Id(), ObjId::id, neutralCinfo, ObjId::ObjId(), Eref::objId(), Id::operator!=(), and ObjId::operator==().
Referenced by getPath(), Id::path(), and ObjId::path().
setName()
void Neutral::setName (const Eref & e, string name)
Field access functions for the name of the Element/Neutral
Definition at line 276 of file Neutral.cpp.
{
    if(e.id().value() <= 3) {
        cout << "Warning: Neutral::setName on '" << e.id().path()
             << "'. Cannot rename core objects\n";
        return;
    }
    if(!Shell::isNameValid(name)) {
        cout << "Warning: Neutral::setName on '" << e.id().path()
             << "'. Illegal character in name.\n";
        return;
    }
    ObjId pa = parent(e);
    Id sibling = Neutral::child(pa.eref(), name);
    if(sibling == Id())  // OK, no existing object with same name.
    {
        e.element()->setName(name);
    } else {
        cout << "Warning: Neutral::setName: an object with the name '" << name
             << "'\n already exists on the same parent. Not changed\n";
    }
}
References child(), Eref::element(), ObjId::eref(), Id::Id(), Eref::id(), Shell::isNameValid(), Id::operator==(), parent(), Id::path(), Element::setName(), and Id::value().
Referenced by initCinfo().
setNumData()
void Neutral::setNumData (const Eref & e, unsigned int num)
numData is the number of data entries on this Element.
Definition at line 383 of file Neutral.cpp.
{
    e.element()->resize(num);
}
References Eref::element(), and Element::resize().
Referenced by initCinfo().
setNumField()
void Neutral::setNumField (const Eref & e, unsigned int num)
numField is the size of the field array on the FieldElement specified by the Eref including its data index.
Definition at line 395 of file Neutral.cpp.
{
    assert(e.isDataHere());
    unsigned int rawIndex = e.element()->rawIndex(e.dataIndex());
    e.element()->resizeField(rawIndex, num);
}
References Eref::dataIndex(), Eref::element(), Eref::isDataHere(), Element::rawIndex(), and Element::resizeField().
Referenced by initCinfo().
setThis()
void Neutral::setThis (Neutral v)
Field access functions for the entire object. For Neutrals the setThis function is a dummy: it doesn't do anything because the Neutral has no data to set. However, the function name acts as a placeholder and derived objects can override the function so that the entire object can be accessed as a field and also for inter-node data transfer.
Definition at line 266 of file Neutral.cpp.
{
    ;
}
Referenced by initCinfo().
setTick()
void Neutral::setTick (const Eref & e, int num)
The clock Tick specifies the timing and order of execution of the 'process' action of this object in the simulation. The timing is set by assigning the appropriate dt to this tick in the Clock object. A value of -1 means that the object is disabled.
Definition at line 422 of file Neutral.cpp.
{
    e.element()->setTick(num);
}
References Eref::element(), and Element::setTick().
Referenced by initCinfo().
Friends And Related Symbol Documentation
operator<<
ostream & operator<< (ostream & s, const Neutral & d) friend
operator>>
istream & operator>> (istream & s, Neutral & d) friend
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/shell/Neutral.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/shell/Neutral.cpp