MOOSE - Multiscale Object Oriented Simulation Environment: CylMesh Class Reference
CylMesh Class Reference
#include <CylMesh.h>
Public Member Functions
void buildStencil ()
CylMesh ()
double extendedMeshEntryVolume (unsigned int fid) const
Volume of mesh Entry including abutting diff-coupled voxels.
std::vector< double > getCoordinates (unsigned int fid) const
Virtual function to return coords of mesh Entry.
std::vector< double > getCoords (const Eref &e) const
x0,y0,z0, x1,y1,z1, dia0, dia1. Note use of diamter, not radius.
double getDiffLength (const Eref &e) const
std::vector< double > getDiffusionArea (unsigned int fid) const
Virtual function to return diffusion X-section area.
std::vector< double > getDiffusionScaling (unsigned int fid) const
Virtual function to return scale factor for diffusion. 1 here.
unsigned int getMeshDimensions (unsigned int fid) const
Virtual function to return dimensions of specified entry.
double getMeshEntryVolume (unsigned int fid) const
Virtual function to return volume of mesh Entry.
unsigned int getMeshType (unsigned int fid) const
Virtual function to return MeshType of specified entry.
std::vector< unsigned int > getParentVoxel () const
Inherited virtual, do nothing for now.
double getR0 (const Eref &e) const
double getR1 (const Eref &e) const
double getTotLength () const
const std::vector< double > & getVoxelArea () const
const std::vector< double > & getVoxelLength () const
double getX0 (const Eref &e) const
double getX1 (const Eref &e) const
double getY0 (const Eref &e) const
double getY1 (const Eref &e) const
double getZ0 (const Eref &e) const
double getZ1 (const Eref &e) const
void indexToSpace (unsigned int index, double &x, double &y, double &z) const
void innerBuildDefaultMesh (const Eref &e, double volume, unsigned int numEntries)
Virtual func to make a mesh with specified Volume and numEntries.
unsigned int innerGetDimensions () const
unsigned int innerGetNumEntries () const
void innerHandleNodeInfo (const Eref &e, unsigned int numNodes, unsigned int numThreads)
void innerHandleRequestMeshStats (const Eref &e, const SrcFinfo2< unsigned int, std::vector< double > > *meshStatsFinfo)
More inherited virtual funcs: request comes in for mesh stats.
void innerSetCoords (const Eref &e, const std::vector< double > &v)
void innerSetNumEntries (unsigned int n)
Inherited virtual func.
void matchCubeMeshEntries (const CubeMesh *other, std::vector< VoxelJunction > &ret) const
void matchCylMeshEntries (const CylMesh *other, std::vector< VoxelJunction > &ret) const
void matchMeshEntries (const ChemCompt *other, std::vector< VoxelJunction > &ret) const
void matchNeuroMeshEntries (const NeuroMesh *other, std::vector< VoxelJunction > &ret) const
double nearest (double x, double y, double z, double &linePos, double &r) const
double nearest (double x, double y, double z, unsigned int &index) const
double selectGridVolume (double h) const
void setCoords (const Eref &e, std::vector< double > v)
void setDiffLength (const Eref &e, double v)
void setR0 (const Eref &e, double v)
void setR1 (const Eref &e, double v)
void setX0 (const Eref &e, double v)
void setX1 (const Eref &e, double v)
void setY0 (const Eref &e, double v)
void setY1 (const Eref &e, double v)
void setZ0 (const Eref &e, double v)
void setZ1 (const Eref &e, double v)
void transmitChange (const Eref &e)
void updateCoords (const Eref &e, const std::vector< double > &childConcs)
double vGetEntireVolume () const
Inherited virtual. Returns entire volume of compartment.
const std::vector< double > & vGetVoxelMidpoint () const
Virtual func so that derived classes can return voxel midpoint.
const std::vector< double > & vGetVoxelVolume () const
Virtual func so that derived classes can pass voxel volume back.
bool vSetVolumeNotRates (double volume)
Inherited virtual. Resizes len and dia of each voxel.
~CylMesh ()
Public Member Functions inherited from MeshCompt
void addRow (unsigned int index, const vector< double > &entry, const vector< unsigned int > &colIndex)
void clearExtendedMeshEntryVolume ()
Inherited virtual function to clear the vector of MeshEntryVolume.
double extendedMeshEntryVolume (unsigned int fid) const
Virtual function to return volume of mesh Entry, including.
void extendStencil (const ChemCompt *other, const vector< VoxelJunction > &vj)
Add boundary voxels to stencil for cross-solver junctions.
vector< unsigned int > getNeighbors (unsigned int fid) const
Looks up stencil to return vector of indices of coupled voxels.
const SparseMatrix< double > & getStencil () const
Returns entire sparse matrix of mesh. Used by diffusion solver.
unsigned int getStencilRow (unsigned int meshIndex, const double **entry, const unsigned int **colIndex) const
vector< double > innerGetStencilRate (unsigned int row) const
void innerResetStencil ()
virtual func implemented here.
MeshCompt ()
void setStencilSize (unsigned int numRows, unsigned int numCols)
~MeshCompt ()
Public Member Functions inherited from ChemCompt
void buildDefaultMesh (const Eref &e, double volume, unsigned int numEntries)
void buildJunction (ChemCompt *other, vector< VoxelJunction > &ret)
ChemCompt ()
void flipRet (vector< VoxelJunction > &ret) const
Utility function for swapping first and second in VoxelJunctions.
void getChildConcs (const Eref &e, vector< double > &childConcs) const
unsigned int getDimensions () const
double getEntireVolume (const Eref &e) const
bool getIsMembraneBound () const
string getMethod () const
unsigned int getNumEntries () const
vector< double > getOneVoxelMidpoint (unsigned int vox) const
Looks up specified voxel midpoint, from vGetVoxelMidpoint.
double getOneVoxelVolume (const Eref &e, unsigned int voxel) const
vector< unsigned int > getStencilIndex (unsigned int row) const
vector< double > getStencilRate (unsigned int row) const
vector< double > getVoxelMidpoint () const
Returns vector of all voxel midpoints in compartment.
vector< double > getVoxelVolume () const
Returns vector of all voxel volumes in compartment.
void handleNodeInfo (const Eref &e, unsigned int numNodes, unsigned int numThreads)
MeshEntry * lookupEntry (unsigned int index)
virtual void matchMeshEntries (const ChemCompt *other, vector< VoxelJunction > &ret) const =0
void resetStencil ()
unsigned int setChildConcs (const Eref &e, const vector< double > &childConcs, unsigned int start) const
void setEntireVolume (const Eref &e, double volume)
void setIsMembraneBound (bool v)
virtual void setMeshEntryVolume (unsigned int fid, double volume)
void setMethod (string method)
void setNumEntries (unsigned int num)
void setOneVoxelVolume (const Eref &e, unsigned int voxel, double volume)
void setVolumeNotRates (double volume)
virtual ~ChemCompt ()
Static Public Member Functions
static const Cinfo * initCinfo ()
Static Public Member Functions inherited from ChemCompt
static double distance (double x, double y, double z)
static const Cinfo * initCinfo ()
static SrcFinfo1< vector< double > > * voxelVolOut ()
Private Attributes
double diffLength_
Radius at other end.
bool isToroid_
double lenSlope_
Utility value: dr/dx.
unsigned int numEntries_
double r0_
coords
double r1_
Radius at one end.
double rSlope_
Utility value: Total length of cylinder.
double surfaceGranularity_
Length constant for diffusion. Equal to dx.
double totLen_
bool useCaps_
double x0_
double x1_
coords
double y0_
coords
double y1_
coords
double z0_
coords
double z1_
coords
Detailed Description
The CylMesh represents a chemically identified compartment shaped like an extended cylinder. This is psuedo-1 dimension: Only the axial dimension is considered for diffusion and subdivisions. Typically used in modelling small segments of dendrite
Definition at line 19 of file CylMesh.h.
Constructor & Destructor Documentation
CylMesh()
CylMesh::CylMesh ()
Definition at line 169 of file CylMesh.cpp.
                 :
        numEntries_( 100 ),
        useCaps_( 0 ),
        isToroid_( false ),
        x0_( 0.0 ),
        y0_( 0.0 ),
        z0_( 0.0 ),
        x1_( 100.0e-6 ),
        y1_( 0.0 ),
        z1_( 0.0 ),
        r0_( 1.0e-6 ),
        r1_( 1.0e-6 ),
        diffLength_( 1.0e-6 ),
        surfaceGranularity_( 0.1 ),
        totLen_( 100.0e-6 ),
        rSlope_( 0.0 ),
        lenSlope_( 0.0 )
{
    ;
}
References diffLength_, isToroid_, lenSlope_, numEntries_, r0_, r1_, rSlope_, surfaceGranularity_, totLen_, useCaps_, x0_, x1_, y0_, y1_, z0_, and z1_.
~CylMesh()
CylMesh::~CylMesh ()
Definition at line 190 of file CylMesh.cpp.
{
    ;
}
Member Function Documentation
buildStencil()
void CylMesh::buildStencil ()
Definition at line 815 of file CylMesh.cpp.
{
    setStencilSize( numEntries_, numEntries_ );
    for ( unsigned int i = 0; i < numEntries_; ++i ) {
        double rLow = r0_ + i * rSlope_;
        double rHigh = r0_ + (i + 1.0) * rSlope_;
        double aLow = rLow * rLow * PI;
        double aHigh = rHigh * rHigh * PI;
        vector< double > entry;
        vector< unsigned int > colIndex;
        if ( i == 0 ) {
            colIndex.push_back( 1 );
            entry.push_back( aHigh / diffLength_ );
            if ( isToroid_ ) {
                colIndex.push_back( numEntries_ - 1 );
                entry.push_back( aLow / diffLength_ );
            }
        } else if ( i == numEntries_ - 1 ) {
            if ( isToroid_ ) {
                colIndex.push_back( 0 );
                if ( r0_ < r1_ )
                    entry.push_back( r0_ * r0_ * PI / diffLength_ );
                else
                    entry.push_back( r1_ * r1_ * PI / diffLength_ );
            }
            colIndex.push_back( numEntries_ - 2 );
            entry.push_back( aLow / diffLength_ );
        } else { // Mostly it is in the middle.
            colIndex.push_back( i - 1 );
            entry.push_back( aLow / diffLength_ );
            colIndex.push_back( i + 1 );
            entry.push_back( aHigh / diffLength_ );
        }
        addRow( i, entry, colIndex );
    }
    innerResetStencil();
}
References MeshCompt::addRow(), diffLength_, MeshCompt::innerResetStencil(), isToroid_, numEntries_, PI, r0_, r1_, rSlope_, and MeshCompt::setStencilSize().
Referenced by innerSetNumEntries(), and updateCoords().
extendedMeshEntryVolume()
double CylMesh::extendedMeshEntryVolume (unsigned int fid) const virtual
Volume of mesh Entry including abutting diff-coupled voxels.
Virtual function to return volume of mesh Entry, including for diffusively coupled voxels from other solvers.
Implements ChemCompt.
Definition at line 599 of file CylMesh.cpp.
{
    if ( fid < numEntries_ ) {
        return getMeshEntryVolume( fid );
    } else {
        return MeshCompt::extendedMeshEntryVolume( fid - numEntries_ );
    }
}
References MeshCompt::extendedMeshEntryVolume(), getMeshEntryVolume(), and numEntries_.
getCoordinates()
vector< double > CylMesh::getCoordinates (unsigned int fid) const virtual
Virtual function to return coords of mesh Entry.
Virtual function to return coords of mesh Entry. For Cylindrical mesh, coords are x1y1z1 x2y2z2 r0 r1 phi0 phi1
Implements ChemCompt.
Definition at line 519 of file CylMesh.cpp.
{
    vector< double > ret(10, 0.0);
    double len0 = diffLength_ * 2 * r0_ / ( r0_ + r1_ );
    // double len0 = diffLength_ * 2 * ( r0_ + rSlope_ / 0.5) / ( r0_ + r1_ );
    double lenStart = len0 + lenSlope_ * 0.5;
    double axialStart = fid * lenStart + ( ( fid * (fid - 1 ) )/2 ) * lenSlope_;
    // fid * totLen_/numEntries_ + (fid - frac ) * lenSlope_;
    double axialEnd =
        (fid + 1) * lenStart + ( ( fid * (fid + 1 ) )/2 ) * lenSlope_;
    // (fid + 1) * totLen_/numEntries_ + (fid - frac + 1.0) * lenSlope_;
    ret[0] = x0_ + (x1_ - x0_ ) * axialStart/totLen_;
    ret[1] = y0_ + (y1_ - y0_ ) * axialStart/totLen_;
    ret[2] = z0_ + (z1_ - z0_ ) * axialStart/totLen_;
    ret[3] = x0_ + (x1_ - x0_ ) * axialEnd/totLen_;
    ret[4] = y0_ + (y1_ - y0_ ) * axialEnd/totLen_;
    ret[5] = z0_ + (z1_ - z0_ ) * axialEnd/totLen_;
    ret[6] = r0_ + fid * rSlope_;
    ret[7] = r0_ + (fid + 1.0) * rSlope_;
    ret[8] = 0;
    ret[9] = 0;
    return ret;
}
References diffLength_, lenSlope_, r0_, r1_, rSlope_, totLen_, x0_, x1_, y0_, y1_, z0_, and z1_.
getCoords()
vector< double > CylMesh::getCoords (const Eref & e) const
x0,y0,z0, x1,y1,z1, dia0, dia1. Note use of diamter, not radius.
Definition at line 387 of file CylMesh.cpp.
{
    vector< double > ret( 9 );
    ret[0] = x0_;
    ret[1] = y0_;
    ret[2] = z0_;
    ret[3] = x1_;
    ret[4] = y1_;
    ret[5] = z1_;
    ret[6] = r0_ * 2.0;
    ret[7] = r1_ * 2.0;
    ret[8] = diffLength_;
    return ret;
}
References diffLength_, r0_, r1_, x0_, x1_, y0_, y1_, z0_, and z1_.
Referenced by initCinfo().
getDiffLength()
double CylMesh::getDiffLength (const Eref & e) const
Definition at line 430 of file CylMesh.cpp.
{
    return diffLength_;
}
References diffLength_.
Referenced by initCinfo().
getDiffusionArea()
vector< double > CylMesh::getDiffusionArea (unsigned int fid) const virtual
Virtual function to return diffusion X-section area.
Virtual function to return diffusion X-section area for each neighbor.
Implements ChemCompt.
Definition at line 550 of file CylMesh.cpp.
{
    if ( numEntries_ <= 1 )
        return vector< double >( 0 );
    double rlow = r0_ + fid * rSlope_;
    double rhigh = r0_ + (fid + 1.0) * rSlope_;
    if ( fid == 0 ) {
        if ( isToroid_ ) {
            vector < double > ret( 2 );
            ret[0] = rlow * rlow * PI;
            ret[1] = rhigh * rhigh * PI;
            return ret;
        } else {
            return vector < double >( 1, rhigh * rhigh * PI );
        }
    }
    if ( fid == (numEntries_ - 1 ) ) {
        if ( isToroid_ ) {
            vector < double > ret( 2 );
            ret[0] = rlow * rlow * PI;
            ret[1] = r0_ * r0_ * PI; // Wrapping around
            return ret;
        } else {
            return vector < double >( 1, rlow * rlow * PI );
        }
    }
    vector< double > ret( 2 );
    ret[0] = rlow * rlow * PI;
    ret[1] = rhigh * rhigh * PI;
    return ret;
}
References isToroid_, numEntries_, PI, r0_, and rSlope_.
getDiffusionScaling()
vector< double > CylMesh::getDiffusionScaling (unsigned int fid) const virtual
Virtual function to return scale factor for diffusion. 1 here.
Implements ChemCompt.
Definition at line 586 of file CylMesh.cpp.
{
    if ( numEntries_ <= 1 )
        return vector< double >( 0 );
    if ( !isToroid_ && ( fid == 0 || fid == (numEntries_ - 1) ) )
        return vector< double >( 1, 1.0 );
    return vector< double >( 2, 1.0 );
}
References isToroid_, and numEntries_.
getMeshDimensions()
unsigned int CylMesh::getMeshDimensions (unsigned int fid) const virtual
Virtual function to return dimensions of specified entry.
Implements ChemCompt.
Definition at line 460 of file CylMesh.cpp.
{
    return 3;
}
getMeshEntryVolume()
double CylMesh::getMeshEntryVolume (unsigned int fid) const virtual
Virtual function to return volume of mesh Entry.
diffLength = length constant for diffusive spread len = length of each mesh entry totLen = total length of cylinder diffLength = k * r^2 Each entry has the same number of diffLengths, L = len/diffLength. Thinner entries have shorter diffLength. This gives a moderately nasty quadratic. However, as len(i) is prop to diffLength(i), and diffLength(i) is prop to r(i)^2 and the cyl-mesh is assumed a gently sloping cone we get len(i) is prop to (r0 + slope.x)^2 and ignoring the 2nd-order term we have len(i) is approx proportional to x position.
dr/dx = (r1-r0)/len ri = r0 + i * dr/dx r(i+1)-ri = (r1-r0)/numEntries len = k * r^2 we get k from integ_r0,r1(len.dr) = totLen So k.r^3/3 | r0, r1 = totLen => k/3 * (r1^3 - r0^3) = totLen => k = 3 * totLen / (r1^3 - r0^3); This is bad if r1 == r0, and is generally unpleasant.
Simple definition of rSlope: rSlope is measured per meshEntry, not per length: rSlope = (r1 - r0) / numEntries; Let's just compute len0 from r0 and diffLength. len0/diffLength = 2 * r0 / (r0 + r1) so len0 = diffLength * 2 * r0 / (r0 + r1) and dlen/dx = lenSlope = diffLength * rSlope * 2/(r0 + r1)
Drop the following calculations: // dlen/dx = dr/dx * dlen/dr = ((r1-r0)/len) * 2k.r // To linearize, let 2r = r0 + r1. // so dlen/dx = ((r1-r0)/len) * k * (r0 + r1) // len(i) = len0 + i * dlen/dx // len0 = totLen/numEntries - (numEntries/2) * dlen/dx
Implements ChemCompt.
Definition at line 507 of file CylMesh.cpp.
{
    double len0 = diffLength_ * 2 * r0_ / ( r0_ + r1_ );
    double ri = r0_ + (fid + 0.5) * rSlope_;
    double leni = len0 + ( fid + 0.5 ) * lenSlope_;
    return leni * ri * ri * PI;
}
References diffLength_, lenSlope_, PI, r0_, r1_, and rSlope_.
Referenced by extendedMeshEntryVolume(), matchCylMeshEntries(), vGetEntireVolume(), and vGetVoxelVolume().
getMeshType()
unsigned int CylMesh::getMeshType (unsigned int fid) const virtual
Virtual function to return MeshType of specified entry.
Implements ChemCompt.
Definition at line 451 of file CylMesh.cpp.
{
    if ( !isToroid_ && useCaps_ && ( fid == 0 || fid == numEntries_ - 1 ) )
        return SPHERE_SHELL_SEG;
    return CYL;
}
References CYL, isToroid_, numEntries_, SPHERE_SHELL_SEG, and useCaps_.
getParentVoxel()
vector< unsigned int > CylMesh::getParentVoxel () const virtual
Inherited virtual, do nothing for now.
Implements MeshCompt.
Definition at line 686 of file CylMesh.cpp.
{
    vector< unsigned int > ret( numEntries_ );
    if ( numEntries_ > 0 )
        ret[0] = static_cast< unsigned int >( -1 );
    for (unsigned int i = 1; i < numEntries_; ++i )
        ret[i] = i-1;
    return ret;
}
References numEntries_.
getR0()
double CylMesh::getR0 (const Eref & e) const
Definition at line 283 of file CylMesh.cpp.
{
    return r0_;
}
References r0_.
Referenced by initCinfo().
getR1()
double CylMesh::getR1 (const Eref & e) const
Definition at line 352 of file CylMesh.cpp.
{
    return r1_;
}
References r1_.
Referenced by initCinfo().
getTotLength()
double CylMesh::getTotLength () const
Definition at line 436 of file CylMesh.cpp.
{
    return totLen_;
}
References totLen_.
Referenced by initCinfo().
getVoxelArea()
const vector< double > & CylMesh::getVoxelArea () const virtual
Implements MeshCompt.
Definition at line 724 of file CylMesh.cpp.
{
    static vector< double > area;
    area.resize( numEntries_ );
    for ( unsigned int i = 0; i < numEntries_; ++i ) {
        double frac = ( 0.5 + static_cast< double >( i ) ) /
            static_cast< double >( numEntries_ );
        double r = r0_ * ( 1.0 - frac ) + r1_ * frac;
        area[i] = r * r * PI;
    }
    return area;
}
References numEntries_, PI, r0_, and r1_.
getVoxelLength()
const vector< double > & CylMesh::getVoxelLength () const virtual
Implements MeshCompt.
Definition at line 737 of file CylMesh.cpp.
{
    static vector< double > length;
    length.assign( numEntries_, totLen_ / numEntries_ );
    return length;
}
References numEntries_, and totLen_.
getX0()
double CylMesh::getX0 (const Eref & e) const
Definition at line 244 of file CylMesh.cpp.
{
    return x0_;
}
References x0_.
Referenced by initCinfo().
getX1()
double CylMesh::getX1 (const Eref & e) const
Definition at line 313 of file CylMesh.cpp.
{
    return x1_;
}
References x1_.
Referenced by initCinfo().
getY0()
double CylMesh::getY0 (const Eref & e) const
Definition at line 257 of file CylMesh.cpp.
{
    return y0_;
}
References y0_.
Referenced by initCinfo().
getY1()
double CylMesh::getY1 (const Eref & e) const
Definition at line 326 of file CylMesh.cpp.
{
    return y1_;
}
References y1_.
Referenced by initCinfo().
getZ0()
double CylMesh::getZ0 (const Eref & e) const
Definition at line 270 of file CylMesh.cpp.
{
    return z0_;
}
References z0_.
Referenced by initCinfo().
getZ1()
double CylMesh::getZ1 (const Eref & e) const
Definition at line 339 of file CylMesh.cpp.
{
    return z1_;
}
References z1_.
Referenced by initCinfo().
indexToSpace()
void CylMesh::indexToSpace (unsigned int index, double & x, double & y, double & z) const virtual
Converts specified index to xyz coords of middle of voxel Values out of range return original xyz
Implements ChemCompt.
Definition at line 1056 of file CylMesh.cpp.
{
    if ( index < numEntries_ ) {
        double k = ( index + 0.5 ) / static_cast< double >( numEntries_ );
        x = ( x1_ - x0_ ) * k + x0_;
        y = ( y1_ - y0_ ) * k + y0_;
        z = ( z1_ - z0_ ) * k + z0_;
    }
}
References numEntries_, x0_, x1_, y0_, y1_, z0_, and z1_.
initCinfo()
const Cinfo * CylMesh::initCinfo () static
Definition at line 27 of file CylMesh.cpp.
{
    // Field Definitions
    static ElementValueFinfo< CylMesh, double > x0(
            "x0",
            "x coord of one end",
            &CylMesh::setX0,
            &CylMesh::getX0
            );
    static ElementValueFinfo< CylMesh, double > y0(
            "y0",
            "y coord of one end",
            &CylMesh::setY0,
            &CylMesh::getY0
            );
    static ElementValueFinfo< CylMesh, double > z0(
            "z0",
            "z coord of one end",
            &CylMesh::setZ0,
            &CylMesh::getZ0
            );
    static ElementValueFinfo< CylMesh, double > r0(
            "r0",
            "Radius of one end",
            &CylMesh::setR0,
            &CylMesh::getR0
            );
    static ElementValueFinfo< CylMesh, double > x1(
            "x1",
            "x coord of other end",
            &CylMesh::setX1,
            &CylMesh::getX1
            );
    static ElementValueFinfo< CylMesh, double > y1(
            "y1",
            "y coord of other end",
            &CylMesh::setY1,
            &CylMesh::getY1
            );
    static ElementValueFinfo< CylMesh, double > z1(
            "z1",
            "z coord of other end",
            &CylMesh::setZ1,
            &CylMesh::getZ1
            );
    static ElementValueFinfo< CylMesh, double > r1(
            "r1",
            "Radius of other end",
            &CylMesh::setR1,
            &CylMesh::getR1
            );
    static ElementValueFinfo< CylMesh, vector< double > > coords(
            "coords",
            "All the coords as a single vector: x0 y0 z0  x1 y1 z1  r0 r1 diffLength",
            &CylMesh::setCoords,
            &CylMesh::getCoords
            );
    static ElementValueFinfo< CylMesh, double > diffLength(
            "diffLength",
            "Length constant to use for subdivisions"
            "The system will attempt to subdivide using compartments of"
            "length diffLength on average. If the cylinder has different end"
            "diameters r0 and r1, it will scale to smaller lengths"
            "for the smaller diameter end and vice versa."
            "Once the value is set it will recompute diffLength as "
            "totLength/numEntries",
            &CylMesh::setDiffLength,
            &CylMesh::getDiffLength
            );
    static ReadOnlyValueFinfo< CylMesh, unsigned int > numDiffCompts(
            "numDiffCompts",
            "Number of diffusive compartments in model",
            &CylMesh::innerGetNumEntries
            );
    static ReadOnlyValueFinfo< CylMesh, double > totLength(
            "totLength",
            "Total length of cylinder",
            &CylMesh::getTotLength
            );
    // MsgDest Definitions
    // Field Elements
    static Finfo* cylMeshFinfos[] = {
        &x0,            // Value
        &y0,            // Value
        &z0,            // Value
        &r0,            // Value
        &x1,            // Value
        &y1,            // Value
        &z1,            // Value
        &r1,            // Value
        &diffLength,            // Value
        &coords,        // Value
        &numDiffCompts,        // ReadOnlyValue
        &totLength,        // ReadOnlyValue
    };
    static string doc[] =
    {
        "Name", "CylMesh",
        "Author", "Upi Bhalla",
        "Description", "Chemical compartment with cylindrical geometry. "
                "Defaults to a uniform cylinder of radius 1 micron, "
                "length 100 microns, and voxel length 1 micron so there "
                "are 100 voxels in the cylinder. "
                "The cylinder can be given a linear taper, by assigning "
                "different radii r0 and r1 to the two ends. ",
    };
    static Dinfo< CylMesh > dinfo;
    static Cinfo cylMeshCinfo (
        "CylMesh",
        ChemCompt::initCinfo(),
        cylMeshFinfos,
        sizeof( cylMeshFinfos ) / sizeof ( Finfo* ),
        &dinfo,
        doc,
        sizeof(doc)/sizeof(string)
    );
    return &cylMeshCinfo;
}
References Cinfo::Cinfo(), ElementValueFinfo< T, F >::ElementValueFinfo(), getCoords(), getDiffLength(), getR0(), getR1(), getTotLength(), getX0(), getX1(), getY0(), getY1(), getZ0(), getZ1(), ChemCompt::initCinfo(), innerGetNumEntries(), ReadOnlyValueFinfo< T, F >::ReadOnlyValueFinfo(), setCoords(), setDiffLength(), setR0(), setR1(), setX0(), setX1(), setY0(), setY1(), setZ0(), and setZ1().
innerBuildDefaultMesh()
void CylMesh::innerBuildDefaultMesh (const Eref & e, double volume, unsigned int numEntries) virtual
Virtual func to make a mesh with specified Volume and numEntries.
Single voxel cylinder with diameter = length. vol = volume = pi.r^2.len. So len = 2r, volume = pi*r^2*2r = 2pi*r^3 so r = (volume/2pi)^(1/3)
Implements ChemCompt.
Definition at line 671 of file CylMesh.cpp.
{
    double r = pow( ( volume / ( PI * 2 ) ), 1.0 / 3 );
    vector< double > coords( 9, 0 );
    coords[3] = 2 * r;
    coords[6] = r;
    coords[7] = r;
    coords[8] = 2 * r / numEntries;
    setCoords( e, coords );
}
References PI, and setCoords().
innerGetDimensions()
unsigned int CylMesh::innerGetDimensions () const virtual
Implements ChemCompt.
Definition at line 441 of file CylMesh.cpp.
{
    return 3;
}
innerGetNumEntries()
unsigned int CylMesh::innerGetNumEntries () const virtual
Inherited virtual func. Returns number of MeshEntry in array
Implements ChemCompt.
Definition at line 645 of file CylMesh.cpp.
{
    return numEntries_;
}
References numEntries_.
Referenced by initCinfo().
innerHandleNodeInfo()
void CylMesh::innerHandleNodeInfo (const Eref & e, unsigned int numNodes, unsigned int numThreads) virtual
Implements ChemCompt.
Definition at line 621 of file CylMesh.cpp.
{
    /*
       unsigned int numEntries = numEntries_;
       vector< double > vols( numEntries, volume_ / numEntries );
       vector< unsigned int > localEntries( numEntries );
       vector< vector< unsigned int > > outgoingEntries;
       vector< vector< unsigned int > > incomingEntries;
       */
    /*
       double oldvol = getMeshEntryVolume( 0 );
       meshSplit()->send( e,
       oldvol,
       vols, localEntries,
       outgoingEntries, incomingEntries );
       */
}
innerHandleRequestMeshStats()
void CylMesh::innerHandleRequestMeshStats (const Eref & e, const SrcFinfo2< unsigned int, std::vector< double > > * meshStatsFinfo)
More inherited virtual funcs: request comes in for mesh stats.
Definition at line 613 of file CylMesh.cpp.
{
    vector< double > ret( static_cast<unsigned int>(vGetEntireVolume() / numEntries_) ,1 );
    meshStatsFinfo->send( e, 1, ret );
}
References numEntries_, SrcFinfo2< T1, T2 >::send(), and vGetEntireVolume().
innerSetCoords()
void CylMesh::innerSetCoords (const Eref & e, const std::vector< double > & v)
Definition at line 357 of file CylMesh.cpp.
{
    vector< double > childConcs;
    getChildConcs( e, childConcs );
    x0_ = v[0];
    y0_ = v[1];
    z0_ = v[2];
    x1_ = v[3];
    y1_ = v[4];
    z1_ = v[5];
    r0_ = v[6];
    r1_ = v[7];
    diffLength_ = v[8];
    updateCoords( e, childConcs );
}
References diffLength_, ChemCompt::getChildConcs(), r0_, r1_, updateCoords(), x0_, x1_, y0_, y1_, z0_, and z1_.
Referenced by setCoords().
innerSetNumEntries()
void CylMesh::innerSetNumEntries (unsigned int n) virtual
Inherited virtual func.
Inherited virtual func. Assigns number of MeshEntries.
Implements ChemCompt.
Definition at line 653 of file CylMesh.cpp.
{
    static const unsigned int WayTooLarge = 1000000;
    if ( n == 0 || n > WayTooLarge ) {
        cout << "Warning: CylMesh::innerSetNumEntries( " << n <<
            " ): out of range\n";
        return;
    }
    assert( n > 0 );
    numEntries_ = n;
    diffLength_ = totLen_ / n;
    rSlope_ = ( r1_ - r0_ ) / numEntries_;
    lenSlope_ = diffLength_ * rSlope_ * 2 / ( r0_ + r1_ );
    buildStencil();
}
References buildStencil(), diffLength_, lenSlope_, numEntries_, r0_, r1_, rSlope_, and totLen_.
matchCubeMeshEntries()
void CylMesh::matchCubeMeshEntries (const CubeMesh * other, std::vector< VoxelJunction > & ret) const
Definition at line 1013 of file CylMesh.cpp.
{
    const double EPSILON = 1e-18;
    Vec a( x1_ - x0_, y1_ - y0_, z1_ - z0_ );
    Vec u;
    Vec v;
    a.orthogonalAxes( u, v );
    double h = selectGridVolume( other->getDx() );
    unsigned int num = static_cast<unsigned int>(floor( 0.1 + diffLength_ / h ));
    // March along axis of cylinder.
    // q is the location of the point along axis.
    for ( unsigned int i = 0; i < numEntries_; ++i ) {
        vector< double >area( other->getNumEntries(), 0.0 );
        for ( unsigned int j = 0; j < num; ++j ) {
            unsigned int m = i * num + j;
            double frac = ( m * h + h/2.0 ) / totLen_;
            double q0 = x0_ + a.a0() * frac;
            double q1 = y0_ + a.a1() * frac;
            double q2 = z0_ + a.a2() * frac;
            // get radius of cylinder at this point.
            double r = r0_ + ( m * h + h / 2.0 ) * rSlope_;
            fillPointsOnCircle( u, v, Vec( q0, q1, q2 ),
                    h, r, area, other );
        }
        // Go through all cubeMesh entries and compute diffusion
        // cross-section. Assume this is through a membrane, so the
        // only factor relevant is area. Not the distance.
        for ( unsigned int k = 0; k < area.size(); ++k ) {
            if ( area[k] > EPSILON ) {
                ret.push_back( VoxelJunction( i, k, area[k] ) );
            }
        }
    }
}
References Vec::a0(), Vec::a1(), Vec::a2(), diffLength_, fillPointsOnCircle(), CubeMesh::getDx(), ChemCompt::getNumEntries(), numEntries_, Vec::orthogonalAxes(), r0_, rSlope_, selectGridVolume(), totLen_, Vec::Vec(), VoxelJunction::VoxelJunction(), x0_, x1_, y0_, y1_, z0_, and z1_.
Referenced by matchMeshEntries().
matchCylMeshEntries()
void CylMesh::matchCylMeshEntries (const CylMesh * other, std::vector< VoxelJunction > & ret) const
Definition at line 891 of file CylMesh.cpp.
{
    const double EPSILON = 1e-3;
    ret.clear();
    // Should really estimate the distance from the centre of the smaller
    // cylinder cap disk to the plane of the larger disk, provided it is
    // within the radius of the disk. The subsequent calculations are the
    // same though.
    double dr1 =     // startOfSelf-to-startOfOther
        distance(x0_ - other->x0_, y0_ - other->y0_, z0_ - other->z0_ );
    double dr2 =  // endOfSelf-to-endOfOther
        distance(x1_ - other->x1_, y1_ - other->y1_, z1_ - other->z1_ );
    double dr3 = // endOfSelf-to-startOfOther
        distance(x1_ - other->x0_, y1_ - other->y0_, z1_ - other->z0_ );
    double dr4 =  // startOfSelf-to-endOfOther
        distance(x0_ - other->x1_, y0_ - other->y1_, z0_ - other->z1_ );
    if ( dr1 <= dr2 && dr1 <= dr3 && dr1 <= dr4 ) {
        if ( ( dr1/totLen_ < EPSILON && dr1/other->totLen_ < EPSILON ) ) {
            double xda;
            if ( r0_ < other->r0_ )
                xda = 2 * r0_ * r0_ * PI / ( diffLength_ + other->diffLength_ );
            else
                xda = 2 * other->r0_ * other->r0_ * PI /
                    ( diffLength_ + other->diffLength_ );
            ret.push_back( VoxelJunction( 0, 0, xda ) );
            ret.back().first = 0;
            ret.back().second = 0;
            ret.back().firstVol = getMeshEntryVolume( 0 );
            ret.back().secondVol = other->getMeshEntryVolume( 0 );
        }
    } else if ( dr2 <= dr3 && dr2 <= dr4 ) {
        if ( ( dr2/totLen_ < EPSILON && dr2/other->totLen_ < EPSILON ) ) {
            double xda;
            if ( r1_ < other->r1_ )
                xda = 2 * r1_ * r1_ * PI / ( diffLength_ + other->diffLength_ );
            else
                xda = 2 * other->r1_ * other->r1_ * PI /
                    ( diffLength_ + other->diffLength_ );
            ret.push_back( VoxelJunction( numEntries_ - 1,
                        other->numEntries_ - 1, xda ) );
            ret.back().first = numEntries_;
            ret.back().second = other->numEntries_ - 1;
            ret.back().firstVol = getMeshEntryVolume( numEntries_ - 1 );
            ret.back().secondVol = other->getMeshEntryVolume( other->numEntries_ - 1 );
        }
    } else if ( dr3 <= dr4 ) {
        if ( ( dr3/totLen_ < EPSILON && dr3/other->totLen_ < EPSILON ) ) {
            double xda;
            if ( r1_ < other->r0_ )
                xda = 2 * r1_ * r1_ * PI / ( diffLength_ + other->diffLength_ );
            else
                xda = 2 * other->r0_ * other->r0_ * PI /
                    ( diffLength_ + other->diffLength_ );
            ret.push_back( VoxelJunction( numEntries_ - 1, 0, xda ) );
            ret.back().first = numEntries_ - 1;
            ret.back().second = 0;
            ret.back().firstVol = getMeshEntryVolume( numEntries_ - 1 );
            ret.back().secondVol = other->getMeshEntryVolume( 0 );
        }
    } else {
        if ( ( dr4/totLen_ < EPSILON && dr4/other->totLen_ < EPSILON ) ) {
            double xda;
            if ( r0_ < other->r1_ )
                xda = 2 * r0_ * r0_ * PI / ( diffLength_ + other->diffLength_ );
            else
                xda = 2 * other->r1_ * other->r1_ * PI /
                    ( diffLength_ + other->diffLength_ );
            ret.push_back( VoxelJunction( 0, other->numEntries_ - 1, xda ));
            ret.back().first = 0;
            ret.back().second = other->numEntries_ - 1;
            ret.back().firstVol = getMeshEntryVolume( 0 );
            ret.back().secondVol = other->getMeshEntryVolume( other->numEntries_ - 1 );
        }
    }
}
References diffLength_, ChemCompt::distance(), VoxelJunction::first, VoxelJunction::firstVol, getMeshEntryVolume(), numEntries_, PI, r0_, r1_, VoxelJunction::second, VoxelJunction::secondVol, totLen_, VoxelJunction::VoxelJunction(), x0_, x1_, y0_, y1_, z0_, and z1_.
Referenced by matchMeshEntries().
matchMeshEntries()
void CylMesh::matchMeshEntries (const ChemCompt * other, std::vector< VoxelJunction > & ret) const
Definition at line 857 of file CylMesh.cpp.
{
    // This is seriously ugly, and what virtual funcs were meant to handle.
    // Dirty hack for now.
    const CylMesh* cyl = dynamic_cast< const CylMesh* >( other );
    if ( cyl ) {
        matchCylMeshEntries( cyl, ret );
        return;
    }
    const EndoMesh* em = dynamic_cast< const EndoMesh* >( other );
    if ( em )
    {
        em->matchMeshEntries( this, ret );
        flipRet( ret );
        return;
    }
    const CubeMesh* cube = dynamic_cast< const CubeMesh* >( other );
    if ( cube ) {
        matchCubeMeshEntries( cube, ret );
        return;
    }
    const NeuroMesh* nm = dynamic_cast< const NeuroMesh* >( other );
    if ( nm ) {
        matchNeuroMeshEntries( nm, ret );
        return;
    }
    cout << "Warning:CylMesh::matchMeshEntries: "  <<
        " unknown mesh type\n";
}
References ChemCompt::flipRet(), matchCubeMeshEntries(), matchCylMeshEntries(), EndoMesh::matchMeshEntries(), and matchNeuroMeshEntries().
matchNeuroMeshEntries()
void CylMesh::matchNeuroMeshEntries (const NeuroMesh * other, std::vector< VoxelJunction > & ret) const
Definition at line 1051 of file CylMesh.cpp.
{
}
Referenced by matchMeshEntries().
nearest() [1/2]
double CylMesh::nearest (double x, double y, double z, double & linePos, double & r) const
Definition at line 1075 of file CylMesh.cpp.
{
    // Consider r0 = x0,y0,z0 and r1 = x1, y1, z1, and r = x,y,z.
    // Fraction along cylinder = k
    //
    // Then, point p along line from r0 to r1 is
    // p = k( r0-r1) + r1.
    //
    // Solving,
    // k = (r0 - r1).(r - r1) / (|r0-r1|^2)
    //
    double dist = distance( x1_ - x0_, y1_ - y0_, z1_ - z0_ );
    double k = dotprd(
            x1_ - x0_, y1_ - y0_, z1_ - z0_,
            x - x0_, y - y0_, z - z0_ ) / ( dist * dist );
    // x2, y2, z2 are the coords of the nearest point.
    double x2 = k * (x1_ - x0_) + x0_;
    double y2 = k * (y1_ - y0_) + y0_;
    double z2 = k * (z1_ - z0_) + z0_;
    double ret = distance( x - x2, y - y2, z - z2 );
    linePos = k;
    r = r0_ + k * numEntries_ * rSlope_;
    return ret;
}
References ChemCompt::distance(), dotprd(), numEntries_, r0_, rSlope_, x0_, x1_, y0_, y1_, z0_, and z1_.
Referenced by nearest().
nearest() [2/2]
double CylMesh::nearest (double x, double y, double z, unsigned int & index) const virtual
Returns distance and index of nearest mesh entry. Computes each mesh entry position as its geometric centre. If the current location is not inside a valid mesh entry, distance returned is negative.
Implements ChemCompt.
Definition at line 1105 of file CylMesh.cpp.
{
    double k = 0.0;
    double r;
    double ret = nearest( x, y, z, k, r );
    if ( k < 0.0 ) {
        ret = -ret;
        index = 0;
    } else if ( k > 1.0 ) {
        ret = -ret;
        index = numEntries_ - 1;
    } else { // Inside length of cylinder, now is it inside radius?
        index = static_cast<unsigned int>(k * numEntries_);
        double ri = r0_ + (index + 0.5) * rSlope_;
        if ( ret > ri )
            ret = -ret;
    }
    return ret;
}
References nearest(), numEntries_, r0_, and rSlope_.
selectGridVolume()
double CylMesh::selectGridVolume (double h) const
Definition at line 970 of file CylMesh.cpp.
{
    if ( h > diffLength_ )
        h = diffLength_;
    if ( h > r0_ )
        h = r0_;
    if ( h > r1_ )
        h = r1_;
    h *= surfaceGranularity_;
    unsigned int num = static_cast<unsigned int>(ceil( diffLength_ / h ));
    h = diffLength_ / num;
    return h;
}
References diffLength_, r0_, r1_, and surfaceGranularity_.
Referenced by matchCubeMeshEntries().
setCoords()
void CylMesh::setCoords (const Eref & e, std::vector< double > v)
Definition at line 377 of file CylMesh.cpp.
{
    if ( v.size() < 9 ) {
        cout << "CylMesh::setCoords: Warning: size of argument vec should be >= 9, was " << v.size() << endl;
    }
    innerSetCoords( e, v );
    transmitChange( e );
}
References innerSetCoords(), and transmitChange().
Referenced by initCinfo(), and innerBuildDefaultMesh().
setDiffLength()
void CylMesh::setDiffLength (const Eref & e, double v)
Definition at line 407 of file CylMesh.cpp.
{
    diffLength_ = v;
    unsigned int numVoxels = (unsigned int) ((x1_-x0_)/diffLength_);
    if( numVoxels >= SM_MAX_COLUMNS )
    {
        stringstream ss;
        ss << "setDiffLength: Too many voxels (" << numVoxels << ") would be created "
                << "for current value of x1=" << x1_ << "m, and x0=" << x0_
                << "m (max " <<  SM_MAX_COLUMNS << " allowed). ";
        x1_ = x0_ + diffLength_ * (SM_MAX_COLUMNS - 1);
        ss << " Changing the length of the compartment: "
            << "x0= " << x0_ << ", x1= " << x1_;
        MOOSE_WARN(ss.str());
    }
    if(numVoxels > 0)
    {
        vector< double > childConcs;
        getChildConcs( e, childConcs );
        updateCoords( e, childConcs );
    }
}
References diffLength_, ChemCompt::getChildConcs(), SM_MAX_COLUMNS, updateCoords(), x0_, and x1_.
Referenced by initCinfo().
setR0()
void CylMesh::setR0 (const Eref & e, double v)
Definition at line 275 of file CylMesh.cpp.
{
    vector< double > childConcs;
    getChildConcs( e, childConcs );
    r0_ = v;
    updateCoords( e, childConcs );
}
References ChemCompt::getChildConcs(), r0_, and updateCoords().
Referenced by initCinfo().
setR1()
void CylMesh::setR1 (const Eref & e, double v)
Definition at line 344 of file CylMesh.cpp.
{
    vector< double > childConcs;
    getChildConcs( e, childConcs );
    r1_ = v;
    updateCoords( e, childConcs );
}
References ChemCompt::getChildConcs(), r1_, and updateCoords().
Referenced by initCinfo().
setX0()
void CylMesh::setX0 (const Eref & e, double v)
Definition at line 236 of file CylMesh.cpp.
{
    vector< double > childConcs;
    getChildConcs( e, childConcs );
    x0_ = v;
    updateCoords( e, childConcs );
}
References ChemCompt::getChildConcs(), updateCoords(), and x0_.
Referenced by initCinfo().
setX1()
void CylMesh::setX1 (const Eref & e, double v)
Definition at line 289 of file CylMesh.cpp.
{
    unsigned int numVoxels = static_cast<unsigned int>((v - x0_) / diffLength_);
    x1_ = v;
    if( numVoxels >= SM_MAX_COLUMNS )
    {
        x1_ = diffLength_ * (SM_MAX_COLUMNS-1);
        MOOSE_WARN("setX1: Too many voxels (" << numVoxels << ") would be created  "
                << "with current diffLength of " << diffLength_
                << "m (maximum voxels allowed=" <<  SM_MAX_COLUMNS << "). "
                << " Changing length of the compartment: "
                << "x0=" << x0_ << ", x1=" << x1_
                << ". You should change `diffLength` before setting `x1`."
                );
    }
    if(numVoxels > 0)
    {
        vector< double > childConcs;
        getChildConcs( e, childConcs );
        updateCoords( e, childConcs );
    }
}
References diffLength_, ChemCompt::getChildConcs(), SM_MAX_COLUMNS, updateCoords(), x0_, and x1_.
Referenced by initCinfo().
setY0()
void CylMesh::setY0 (const Eref & e, double v)
Definition at line 249 of file CylMesh.cpp.
{
    vector< double > childConcs;
    getChildConcs( e, childConcs );
    y0_ = v;
    updateCoords( e, childConcs );
}
References ChemCompt::getChildConcs(), updateCoords(), and y0_.
Referenced by initCinfo().
setY1()
void CylMesh::setY1 (const Eref & e, double v)
Definition at line 318 of file CylMesh.cpp.
{
    vector< double > childConcs;
    getChildConcs( e, childConcs );
    y1_ = v;
    updateCoords( e, childConcs );
}
References ChemCompt::getChildConcs(), updateCoords(), and y1_.
Referenced by initCinfo().
setZ0()
void CylMesh::setZ0 (const Eref & e, double v)
Definition at line 262 of file CylMesh.cpp.
{
    vector< double > childConcs;
    getChildConcs( e, childConcs );
    z0_ = v;
    updateCoords( e, childConcs );
}
References ChemCompt::getChildConcs(), updateCoords(), and z0_.
Referenced by initCinfo().
setZ1()
void CylMesh::setZ1 (const Eref & e, double v)
Definition at line 331 of file CylMesh.cpp.
{
    vector< double > childConcs;
    getChildConcs( e, childConcs );
    z1_ = v;
    updateCoords( e, childConcs );
}
References ChemCompt::getChildConcs(), updateCoords(), and z1_.
Referenced by initCinfo().
transmitChange()
void CylMesh::transmitChange (const Eref & e)
Definition at line 771 of file CylMesh.cpp.
{
    /*
       Id meshEntry( e.id().value() + 1 );
       assert(
       meshEntry.eref().data() == reinterpret_cast< char* >( lookupEntry( 0 ) )
       );
       double oldvol = getMeshEntryVolume( 0 );
       unsigned int totalNumEntries = numEntries_;
       unsigned int localNumEntries = totalNumEntries;
       unsigned int startEntry = 0;
       vector< unsigned int > localIndices( localNumEntries ); // empty
       for ( unsigned int i = 0; i < localNumEntries; ++i )
       localIndices[i] = i;
       vector< double > vols( localNumEntries, volume_ / numEntries_ );
       vector< vector< unsigned int > > outgoingEntries; // [node#][Entry#]
       vector< vector< unsigned int > > incomingEntries; // [node#][Entry#]
    // This function updates the size of the FieldDataHandler for the
    // MeshEntries.
    DataHandler* dh = meshEntry.element()->dataHandler();
    FieldDataHandlerBase* fdh = dynamic_cast< FieldDataHandlerBase* >( dh );
    assert( fdh );
    if ( totalNumEntries > fdh->getMaxFieldEntries() ) {
    fdh->setMaxFieldEntries( localNumEntries );
    }
    // This message tells the Stoich about the new mesh, and also about
    // how it communicates with other nodes.
    meshSplit()->fastSend( e,
    oldvol,
    vols, localIndices,
    outgoingEntries, incomingEntries );
    // This func goes down to the MeshEntry to tell all the pools and
    // Reacs to deal with the new mesh. They then update the stoich.
    lookupEntry( 0 )->triggerRemesh( meshEntry.eref(),
    oldvol, startEntry, localIndices, vols );
    */
}
Referenced by setCoords().
updateCoords()
void CylMesh::updateCoords (const Eref & e, const std::vector< double > & childConcs)
Recomputes all local coordinate and meshing data following a change in any of the coord parameters
This assumes that diffLength is the quantity to preserve, over numEntries. So when the compartment changes volume, numEntries changes. diffLength will be fine-tuned to be a clean multiple.
Definition at line 204 of file CylMesh.cpp.
{
    double temp = sqrt(
            ( x1_ - x0_ ) * ( x1_ - x0_ ) +
            ( y1_ - y0_ ) * ( y1_ - y0_ ) +
            ( z1_ - z0_ ) * ( z1_ - z0_ )
            );
    if ( doubleEq( temp, 0.0 ) ) {
        cout << "Error: CylMesh::updateCoords:\n"
            "total length of compartment = 0 with these parameters\n";
        return;
    }
    totLen_ = temp;
    temp = totLen_ / diffLength_;
    if ( temp < 1.0 ) {
        diffLength_ = totLen_;
        numEntries_ = 1;
    } else {
        numEntries_ = static_cast< unsigned int >( round ( temp ) );
        diffLength_ = totLen_ / numEntries_;
    }
    rSlope_ = ( r1_ - r0_ ) / numEntries_;
    lenSlope_ = diffLength_ * rSlope_ * 2 / ( r0_ + r1_ );
    // dx2_[0] = diffLength_;
    // dx2_[1] = diffLength_;
    buildStencil();
    setChildConcs( e, concs, 0 );
}
References buildStencil(), diffLength_, doubleEq(), lenSlope_, numEntries_, r0_, r1_, rSlope_, ChemCompt::setChildConcs(), totLen_, x0_, x1_, y0_, y1_, z0_, and z1_.
Referenced by innerSetCoords(), setDiffLength(), setR0(), setR1(), setX0(), setX1(), setY0(), setY1(), setZ0(), and setZ1().
vGetEntireVolume()
double CylMesh::vGetEntireVolume () const virtual
Inherited virtual. Returns entire volume of compartment.
Implements ChemCompt.
Definition at line 744 of file CylMesh.cpp.
{
    double vol = 0.0;
    for ( unsigned int i = 0; i < numEntries_; ++i )
        vol += getMeshEntryVolume( i );
    return vol;
}
References getMeshEntryVolume(), and numEntries_.
Referenced by innerHandleRequestMeshStats(), and vSetVolumeNotRates().
vGetVoxelMidpoint()
const vector< double > & CylMesh::vGetVoxelMidpoint () const virtual
Virtual func so that derived classes can return voxel midpoint.
Implements ChemCompt.
Definition at line 706 of file CylMesh.cpp.
{
    static vector< double > midpoint( numEntries_ * 3, 0.0 );
    midpoint.resize( numEntries_ * 3 );
    double dx = ( x1_ - x0_ ) / numEntries_;
    double dy = ( y1_ - y0_ ) / numEntries_;
    double dz = ( z1_ - z0_ ) / numEntries_;
    vector< double >::iterator j = midpoint.begin();
    for ( unsigned int i = 0; i < numEntries_; ++i )
        *j++ = x0_ + dx * i;
    for ( unsigned int i = 0; i < numEntries_; ++i )
        *j++ = y0_ + dy * i;
    for ( unsigned int i = 0; i < numEntries_; ++i )
        *j++ = z0_ + dz * i;
    return midpoint;
}
References numEntries_, x0_, x1_, y0_, y1_, z0_, and z1_.
vGetVoxelVolume()
const vector< double > & CylMesh::vGetVoxelVolume () const virtual
Virtual func so that derived classes can pass voxel volume back.
Implements ChemCompt.
Definition at line 697 of file CylMesh.cpp.
{
    static vector< double > vol;
    vol.resize( numEntries_ );
    for ( unsigned int i = 0; i < numEntries_; ++i )
        vol[i] = getMeshEntryVolume( i );
    return vol;
}
References getMeshEntryVolume(), and numEntries_.
vSetVolumeNotRates()
bool CylMesh::vSetVolumeNotRates (double volume) virtual
Inherited virtual. Resizes len and dia of each voxel.
Implements ChemCompt.
Definition at line 752 of file CylMesh.cpp.
{
    double oldVol = vGetEntireVolume();
    double linScale = pow( volume/oldVol, 1.0 / 3.0 );
    x1_ *= linScale;
    y1_ *= linScale;
    z1_ *= linScale;
    r0_ *= linScale;
    r1_ *= linScale;
    totLen_ *= linScale;
    // Have to scale this so numEntries remains the same.
    diffLength_ = totLen_ / numEntries_;
    return true;
}
References diffLength_, numEntries_, r0_, r1_, totLen_, vGetEntireVolume(), x1_, y1_, and z1_.
Member Data Documentation
diffLength_
double CylMesh::diffLength_ private
Radius at other end.
Definition at line 180 of file CylMesh.h.
Referenced by buildStencil(), CylMesh(), getCoordinates(), getCoords(), getDiffLength(), getMeshEntryVolume(), innerSetCoords(), innerSetNumEntries(), matchCubeMeshEntries(), matchCylMeshEntries(), selectGridVolume(), setDiffLength(), setX1(), updateCoords(), and vSetVolumeNotRates().
isToroid_
bool CylMesh::isToroid_ private
Definition at line 167 of file CylMesh.h.
Referenced by buildStencil(), CylMesh(), getDiffusionArea(), getDiffusionScaling(), and getMeshType().
lenSlope_
double CylMesh::lenSlope_ private
Utility value: dr/dx.
Definition at line 191 of file CylMesh.h.
Referenced by CylMesh(), getCoordinates(), getMeshEntryVolume(), innerSetNumEntries(), and updateCoords().
numEntries_
unsigned int CylMesh::numEntries_ private
Definition at line 165 of file CylMesh.h.
Referenced by buildStencil(), CylMesh(), extendedMeshEntryVolume(), getDiffusionArea(), getDiffusionScaling(), getMeshType(), getParentVoxel(), getVoxelArea(), getVoxelLength(), indexToSpace(), innerGetNumEntries(), innerHandleRequestMeshStats(), innerSetNumEntries(), matchCubeMeshEntries(), matchCylMeshEntries(), nearest(), nearest(), updateCoords(), vGetEntireVolume(), vGetVoxelMidpoint(), vGetVoxelVolume(), and vSetVolumeNotRates().
r0_
double CylMesh::r0_ private
coords
Definition at line 177 of file CylMesh.h.
Referenced by buildStencil(), CylMesh(), getCoordinates(), getCoords(), getDiffusionArea(), getMeshEntryVolume(), getR0(), getVoxelArea(), innerSetCoords(), innerSetNumEntries(), matchCubeMeshEntries(), matchCylMeshEntries(), nearest(), nearest(), selectGridVolume(), setR0(), updateCoords(), and vSetVolumeNotRates().
r1_
double CylMesh::r1_ private
Radius at one end.
Definition at line 178 of file CylMesh.h.
Referenced by buildStencil(), CylMesh(), getCoordinates(), getCoords(), getMeshEntryVolume(), getR1(), getVoxelArea(), innerSetCoords(), innerSetNumEntries(), matchCylMeshEntries(), selectGridVolume(), setR1(), updateCoords(), and vSetVolumeNotRates().
rSlope_
double CylMesh::rSlope_ private
Utility value: Total length of cylinder.
Definition at line 190 of file CylMesh.h.
Referenced by buildStencil(), CylMesh(), getCoordinates(), getDiffusionArea(), getMeshEntryVolume(), innerSetNumEntries(), matchCubeMeshEntries(), nearest(), nearest(), and updateCoords().
surfaceGranularity_
double CylMesh::surfaceGranularity_ private
Length constant for diffusion. Equal to dx.
surfaceGranularity_ decides how finely to subdivide DiffLength or cubic mesh side, when computing surface area of intersections between them when diffusing. Defaults to 0.1
Definition at line 187 of file CylMesh.h.
Referenced by CylMesh(), and selectGridVolume().
totLen_
double CylMesh::totLen_ private
Definition at line 189 of file CylMesh.h.
Referenced by CylMesh(), getCoordinates(), getTotLength(), getVoxelLength(), innerSetNumEntries(), matchCubeMeshEntries(), matchCylMeshEntries(), updateCoords(), and vSetVolumeNotRates().
useCaps_
bool CylMesh::useCaps_ private
Definition at line 166 of file CylMesh.h.
Referenced by CylMesh(), and getMeshType().
x0_
double CylMesh::x0_ private
Definition at line 169 of file CylMesh.h.
Referenced by CylMesh(), getCoordinates(), getCoords(), getX0(), indexToSpace(), innerSetCoords(), matchCubeMeshEntries(), matchCylMeshEntries(), nearest(), setDiffLength(), setX0(), setX1(), updateCoords(), and vGetVoxelMidpoint().
x1_
double CylMesh::x1_ private
coords
Definition at line 173 of file CylMesh.h.
Referenced by CylMesh(), getCoordinates(), getCoords(), getX1(), indexToSpace(), innerSetCoords(), matchCubeMeshEntries(), matchCylMeshEntries(), nearest(), setDiffLength(), setX1(), updateCoords(), vGetVoxelMidpoint(), and vSetVolumeNotRates().
y0_
double CylMesh::y0_ private
coords
Definition at line 170 of file CylMesh.h.
Referenced by CylMesh(), getCoordinates(), getCoords(), getY0(), indexToSpace(), innerSetCoords(), matchCubeMeshEntries(), matchCylMeshEntries(), nearest(), setY0(), updateCoords(), and vGetVoxelMidpoint().
y1_
double CylMesh::y1_ private
coords
Definition at line 174 of file CylMesh.h.
Referenced by CylMesh(), getCoordinates(), getCoords(), getY1(), indexToSpace(), innerSetCoords(), matchCubeMeshEntries(), matchCylMeshEntries(), nearest(), setY1(), updateCoords(), vGetVoxelMidpoint(), and vSetVolumeNotRates().
z0_
double CylMesh::z0_ private
coords
Definition at line 171 of file CylMesh.h.
Referenced by CylMesh(), getCoordinates(), getCoords(), getZ0(), indexToSpace(), innerSetCoords(), matchCubeMeshEntries(), matchCylMeshEntries(), nearest(), setZ0(), updateCoords(), and vGetVoxelMidpoint().
z1_
double CylMesh::z1_ private
coords
Definition at line 175 of file CylMesh.h.
Referenced by CylMesh(), getCoordinates(), getCoords(), getZ1(), indexToSpace(), innerSetCoords(), matchCubeMeshEntries(), matchCylMeshEntries(), nearest(), setZ1(), updateCoords(), vGetVoxelMidpoint(), and vSetVolumeNotRates().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/mesh/CylMesh.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/mesh/CylMesh.cpp