MOOSE - Multiscale Object Oriented Simulation Environment: FieldElementFinfoBase Class Reference
FieldElementFinfoBase Class Reference abstract
#include <FieldElementFinfo.h>
Public Member Functions
FieldElementFinfoBase (const string &name, const string &doc, const Cinfo *fieldCinfo, bool deferCreate)
virtual unsigned int getNumField (const char *parent) const =0
virtual func to get size of Field array, using char* for parent
virtual char * lookupField (char *parent, unsigned int fieldIndex) const =0
void postCreationFunc (Id parent, Element *parentElm) const
void registerFinfo (Cinfo *c)
virtual void setNumField (char *parent, unsigned int num) const =0
virtual func to resize Field array, using char* for parent
bool strGet (const Eref &tgt, const string &field, string &returnValue) const
bool strSet (const Eref &tgt, const string &field, const string &arg) const
virtual ~FieldElementFinfoBase ()
Public Member Functions inherited from Finfo
virtual bool addMsg (const Finfo *target, ObjId mid, Element *src) const
virtual bool checkTarget (const Finfo *target) const
const string & docs () const
Returns documentation string.
Finfo (const string &name, const string &doc)
virtual vector< string > innerDest () const
virtual vector< string > innerSrc () const
const string & name () const
virtual string rttiType () const
virtual ~Finfo ()
Protected Attributes
bool deferCreate_
const Cinfo * fieldCinfo_
DestFinfo * getNum_
DestFinfo * setNum_
Additional Inherited Members
Static Public Member Functions inherited from Finfo
static const Cinfo * initCinfo ()
Detailed Description
This class sets up fields that should be accessed as independent FieldElements. These fields are typically complex ones with several sub-fields, and are also typically arranged in an array. Examples are Synapses on an IntFire Neuron.
The creation of this one Finfo sets up three things: First, the information for the FieldElement that will handle the class. Second, the set and get functions for the size of the array of Fields. Third, an automatic creation of the FieldElement whenever an Element of the Parent class is made. This defaults to a child, but can be moved.
Definition at line 26 of file FieldElementFinfo.h.
Constructor & Destructor Documentation
FieldElementFinfoBase()
FieldElementFinfoBase::FieldElementFinfoBase (const string & name, const string & doc, const Cinfo * fieldCinfo, bool deferCreate) inline
Definition at line 29 of file FieldElementFinfo.h.
        :   Finfo( name, doc),
           setNum_( 0 ),
           getNum_( 0 ),
           fieldCinfo_( fieldCinfo ),
           deferCreate_( deferCreate )
    {
        ;
    }
References deferCreate_, fieldCinfo_, Finfo::Finfo(), getNum_, and setNum_.
~FieldElementFinfoBase()
virtual FieldElementFinfoBase::~FieldElementFinfoBase () inline virtual
Definition at line 44 of file FieldElementFinfo.h.
    {
        if ( setNum_ )
            delete setNum_;
        if ( getNum_ )
            delete getNum_;
    }
References getNum_, and setNum_.
Member Function Documentation
getNumField()
virtual unsigned int FieldElementFinfoBase::getNumField (const char * parent) const pure virtual
virtual func to get size of Field array, using char* for parent
Implemented in FieldElementFinfo< T, F >.
Referenced by FieldElement::numField().
lookupField()
virtual char * FieldElementFinfoBase::lookupField (char * parent, unsigned int fieldIndex) const pure virtual
virtual function to look up pointer for Field object. This casts everything down to chars so that the FieldElement can use it.
Implemented in FieldElementFinfo< T, F >.
Referenced by FieldElement::data().
postCreationFunc()
void FieldElementFinfoBase::postCreationFunc (Id parent, Element * parentElm) const virtual
Virtual function, defined in Finfo.h and overridden here.
Reimplemented from Finfo.
Definition at line 14 of file FieldElementFinfo.cpp.
{
    static const Finfo* pf = Neutral::initCinfo()->findFinfo( "parentMsg" );
    static const Finfo* f1 = Neutral::initCinfo()->findFinfo( "childOut" );
    if ( deferCreate_ )
        return;
    Id kid = Id::nextId();
    Element* e = new FieldElement( parent, kid, fieldCinfo_, name(), this );
    Msg* m = new OneToOneDataIndexMsg( parent.eref(), Eref( e, 0 ), 0 );
    assert( m );
    if ( !f1->addMsg( pf, m->mid(), parent.element() ) )
    {
        cout << "FieldElementFinfoBase::postCreationFunc: Error: \n" <<
             " unable to add parent->child msg from " <<
             parent.element()->getName() << " to " << name() << "\n";
        return;
    }
}
References Finfo::addMsg(), deferCreate_, Id::element(), Id::eref(), Eref::Eref(), fieldCinfo_, FieldElement::FieldElement(), Cinfo::findFinfo(), Element::getName(), Neutral::initCinfo(), Msg::mid(), Finfo::name(), Id::nextId(), and OneToOneDataIndexMsg::OneToOneDataIndexMsg().
registerFinfo()
void FieldElementFinfoBase::registerFinfo (Cinfo * c) inline virtual
Returns string-ified form to handle template expectations for name field string getName() const; Assign function Ids, bindIndex and so on.
Implements Finfo.
Definition at line 52 of file FieldElementFinfo.h.
    {
        c->registerFinfo( setNum_ );
        c->registerFinfo( getNum_ );
        c->registerPostCreationFinfo( this );
    }
References getNum_, Cinfo::registerFinfo(), Cinfo::registerPostCreationFinfo(), and setNum_.
setNumField()
virtual void FieldElementFinfoBase::setNumField (char * parent, unsigned int num) const pure virtual
virtual func to resize Field array, using char* for parent
Implemented in FieldElementFinfo< T, F >.
Referenced by FieldElement::resizeField().
strGet()
bool FieldElementFinfoBase::strGet (const Eref & tgt, const string & field, string & returnValue) const inline virtual
Function to return value of field into a string argument. Returns true on success. Normally called only from SetGet::strGet.
Implements Finfo.
Definition at line 65 of file FieldElementFinfo.h.
    {
        return 0; // always fails
    }
strSet()
bool FieldElementFinfoBase::strSet (const Eref & tgt, const string & field, const string & arg) const inline virtual
Function to set this field using a string argument. Returns true on success. Normally called only from SetGet::strSet.
Implements Finfo.
Definition at line 59 of file FieldElementFinfo.h.
    {
        return 0; // always fails
    }
Member Data Documentation
deferCreate_
bool FieldElementFinfoBase::deferCreate_ protected
Definition at line 100 of file FieldElementFinfo.h.
Referenced by FieldElementFinfoBase(), and postCreationFunc().
fieldCinfo_
const Cinfo* FieldElementFinfoBase::fieldCinfo_ protected
Definition at line 99 of file FieldElementFinfo.h.
Referenced by FieldElementFinfoBase(), and postCreationFunc().
getNum_
DestFinfo* FieldElementFinfoBase::getNum_ protected
Definition at line 98 of file FieldElementFinfo.h.
Referenced by FieldElementFinfo< T, F >::FieldElementFinfo(), FieldElementFinfoBase(), registerFinfo(), and ~FieldElementFinfoBase().
setNum_
DestFinfo* FieldElementFinfoBase::setNum_ protected
Definition at line 97 of file FieldElementFinfo.h.
Referenced by FieldElementFinfo< T, F >::FieldElementFinfo(), FieldElementFinfoBase(), registerFinfo(), and ~FieldElementFinfoBase().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/basecode/FieldElementFinfo.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/basecode/FieldElementFinfo.cpp