MOOSE - Multiscale Object Oriented Simulation Environment: CspaceReacInfo Class Reference
CspaceReacInfo Class Reference
#include <ReadCspace.h>
Public Member Functions
CspaceReacInfo ()
CspaceReacInfo (const string &name, double r1, double r2)
string name ()
bool operator< (const CspaceReacInfo &other) const
double r1 ()
double r2 ()
Private Attributes
string name_
double r1_
double r2_
Detailed Description
Definition at line 40 of file ReadCspace.h.
Constructor & Destructor Documentation
CspaceReacInfo() [1/2]
CspaceReacInfo::CspaceReacInfo (const string & name, double r1, double r2) inline
Definition at line 43 of file ReadCspace.h.
            : name_( name ), r1_( r1 ), r2_( r2 )
        {
            ;
        }
References name_, r1_, and r2_.
Referenced by ReadCspace::printEnz(), and ReadCspace::printReac().
CspaceReacInfo() [2/2]
CspaceReacInfo::CspaceReacInfo () inline
Definition at line 48 of file ReadCspace.h.
            : name_( "" ), r1_( 0.1 ), r2_( 0.1 )
        {
            ;
        }
References name_, r1_, and r2_.
Member Function Documentation
name()
string CspaceReacInfo::name () inline
Definition at line 59 of file ReadCspace.h.
                      {
            return name_;
        }
References name_.
Referenced by ReadCspace::printFooter().
operator<()
bool CspaceReacInfo::operator< (const CspaceReacInfo & other) const inline
Definition at line 54 of file ReadCspace.h.
        {
            return ( name_ < other.name_ );
        }
References name_.
r1()
double CspaceReacInfo::r1 () inline
Definition at line 62 of file ReadCspace.h.
                    {
            return r1_;
        }
References r1_.
Referenced by ReadCspace::printFooter().
r2()
double CspaceReacInfo::r2 () inline
Definition at line 65 of file ReadCspace.h.
                    {
            return r2_;
        }
References r2_.
Referenced by ReadCspace::printFooter().
Member Data Documentation
name_
string CspaceReacInfo::name_ private
Definition at line 69 of file ReadCspace.h.
Referenced by CspaceReacInfo(), CspaceReacInfo(), name(), and operator<().
r1_
double CspaceReacInfo::r1_ private
Definition at line 70 of file ReadCspace.h.
Referenced by CspaceReacInfo(), CspaceReacInfo(), and r1().
r2_
double CspaceReacInfo::r2_ private
Definition at line 71 of file ReadCspace.h.
Referenced by CspaceReacInfo(), CspaceReacInfo(), and r2().
The documentation for this class was generated from the following file:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/kinetics/ReadCspace.h