MOOSE - Multiscale Object Oriented Simulation Environment: SwcSegment Class Reference
SwcSegment Class Reference
#include <SwcSegment.h>
Public Member Functions
void addChild (unsigned int kid)
double distance (const SwcSegment &other) const
void figureOutType ()
double getElecDistFromSoma () const
double getGeomDistFromSoma () const
double getPathDistFromSoma () const
const vector< int > & kids () const
double L () const
double length () const
unsigned int myIndex () const
bool OK () const
unsigned int parent () const
double radius () const
void replaceKids (const vector< int > &kids)
void setBad ()
void setCumulativeDistance (double len, double L, double pSoma, double eSoma)
void setGeometricalDistanceFromSoma (const SwcSegment &soma)
void setParent (unsigned int pa)
SwcSegment ()
SwcSegment (const string &line)
SwcSegment (int i, short type, double x, double y, double z, double r, int parent)
unsigned short type () const
const Vec & vec () const
Static Public Attributes
static const short AXON = 2
static const short BASAL = 3
static const short CUSTOM = 7
static const short DEND = 4
static const short END = 6
static const short FORK = 5
static const short SOMA = 1
static const string typeName []
static const short UNDEF = 0
Protected Attributes
double electrotonicDistanceFromSoma_
electrotonic dist from soma, summed along dend.
double geometricalDistanceFromSoma_
geometrical distance from soma.
vector< int > kids_
double L_
Length of segment.
double length_
Radius of segment.
unsigned int myIndex_
unsigned int parent_
Number of length constants in segment.
double pathDistanceFromSoma_
Index of parent. Is ~0 for soma.
double radius_
coordinates of end of segment
short type_
Index of self.
Vec v_
Detailed Description
This defines a single segment in an SWC file used in NeuroMorpho Note that this is not going to work well for dendritic spines which come off in the middle of a parent compartment, and which have to be started from the surface rather than the axis of the dendrite.
Definition at line 18 of file SwcSegment.h.
Constructor & Destructor Documentation
SwcSegment() [1/3]
SwcSegment::SwcSegment () inline
Definition at line 21 of file SwcSegment.h.
                : myIndex_( 0 ), type_( 0 ), radius_( 0.0 ),
                length_( 0.0 ), L_( 0.0 ),
                parent_( ~0U ),
                geometricalDistanceFromSoma_( 0.0 ),
                electrotonicDistanceFromSoma_( 0.0 )
        {;}
References electrotonicDistanceFromSoma_, geometricalDistanceFromSoma_, L_, length_, myIndex_, parent_, radius_, and type_.
SwcSegment() [2/3]
SwcSegment::SwcSegment (const string & line)
Definition at line 29 of file SwcSegment.cpp.
        :
            geometricalDistanceFromSoma_( 0.0 ),
            electrotonicDistanceFromSoma_( 0.0 )
{
    vector< string > args;
    stringstream ss( line );
    string temp;
    while (ss >> temp ) {
        args.push_back( temp );
    }
    if ( args.size() == 7 ) {
        myIndex_ = atoi( args[0].c_str() );
        type_ = atoi( args[1].c_str() );
        double x = atof( args[2].c_str() );
        double y = atof( args[3].c_str() );
        double z = atof( args[4].c_str() );
        v_ = Vec( x, y, z );
        radius_ = atof( args[5].c_str() );
        int pa = atoi( args[6].c_str() );
        if ( pa > 0 )
            parent_ = pa;
        else
            parent_ = ~0U;
    } else {
        type_ = UNDEF;
    }
}
References electrotonicDistanceFromSoma_, geometricalDistanceFromSoma_, myIndex_, parent_, radius_, type_, UNDEF, v_, and Vec::Vec().
Referenced by ReadSwc::ReadSwc().
SwcSegment() [3/3]
SwcSegment::SwcSegment (int i, short type, double x, double y, double z, double r, int parent)
Definition at line 58 of file SwcSegment.cpp.
                :
                        myIndex_( i ),
                        type_( type ),
                        v_( x, y, z ),
                        radius_( r ),
                        length_( 0.0 ),
                        L_( 0.0 ),
                        geometricalDistanceFromSoma_( 0.0 ),
                        electrotonicDistanceFromSoma_( 0.0 )
{
    if ( parent >= 0 )
        parent_ = parent;
    else
        parent_ = ~0U;
}
References electrotonicDistanceFromSoma_, geometricalDistanceFromSoma_, L_, length_, myIndex_, parent_, radius_, type_, v_, and Vec::Vec().
Referenced by fillSegments().
Member Function Documentation
addChild()
void SwcSegment::addChild (unsigned int kid) inline
Definition at line 56 of file SwcSegment.h.
{
            kids_.push_back( kid );
        }
References kids_.
Referenced by ReadSwc::assignKids(), and Neuron::buildSegmentTree().
distance()
double SwcSegment::distance (const SwcSegment & other) const inline
Definition at line 87 of file SwcSegment.h.
{
            return v_.distance( other.v_ );
        }
References Vec::distance(), and v_.
Referenced by ReadSwc::cleanZeroLength(), makeCompt(), ReadSwc::traverseBranch(), and traverseCumulativeDistance().
figureOutType()
void SwcSegment::figureOutType ()
Definition at line 77 of file SwcSegment.cpp.
{
    if ( type_ == SOMA ) // already defined as soma
        return;
    if ( type_ == BASAL )
        return;
    if ( type_ == AXON )
        return;
    type_ = DEND; // Fall back for all other types
}
References AXON, BASAL, DEND, SOMA, and type_.
Referenced by ReadSwc::assignKids(), and Neuron::buildSegmentTree().
getElecDistFromSoma()
double SwcSegment::getElecDistFromSoma () const inline
Definition at line 117 of file SwcSegment.h.
{
            return electrotonicDistanceFromSoma_;
        }
References electrotonicDistanceFromSoma_.
Referenced by Neuron::evalExprForElist(), Neuron::getElecDistFromSoma(), and Neuron::updateSegmentLengths().
getGeomDistFromSoma()
double SwcSegment::getGeomDistFromSoma () const inline
Definition at line 113 of file SwcSegment.h.
{
            return geometricalDistanceFromSoma_;
        }
References geometricalDistanceFromSoma_.
Referenced by Neuron::evalExprForElist(), Neuron::getGeomDistFromSoma(), and Neuron::updateSegmentLengths().
getPathDistFromSoma()
double SwcSegment::getPathDistFromSoma () const inline
Definition at line 109 of file SwcSegment.h.
{
            return pathDistanceFromSoma_;
        }
References pathDistanceFromSoma_.
Referenced by Neuron::evalExprForElist(), Neuron::getPathDistFromSoma(), and Neuron::updateSegmentLengths().
kids()
const vector< int > & SwcSegment::kids () const inline
Definition at line 62 of file SwcSegment.h.
        {
            return kids_;
        }
References kids_.
Referenced by ReadSwc::build(), ReadSwc::cleanMultipointSoma(), ReadSwc::cleanZeroLength(), ReadSwc::parseBranches(), ReadSwc::traverseBranch(), and traverseCumulativeDistance().
L()
double SwcSegment::L () const inline
Definition at line 83 of file SwcSegment.h.
{
            return L_;
        }
References L_.
Referenced by ReadSwc::traverseBranch().
length()
double SwcSegment::length () const inline
Definition at line 79 of file SwcSegment.h.
{
            return length_;
        }
References length_.
Referenced by Neuron::makeSpacingDistrib().
myIndex()
unsigned int SwcSegment::myIndex () const inline
Definition at line 52 of file SwcSegment.h.
{
            return myIndex_;
        }
References myIndex_.
Referenced by ReadSwc::assignKids(), ReadSwc::build(), ReadSwc::cleanMultipointSoma(), ReadSwc::cleanZeroLength(), SwcBranch::printDiagnostics(), ReadSwc::traverseBranch(), and ReadSwc::validate().
OK()
bool SwcSegment::OK () const inline
Definition at line 34 of file SwcSegment.h.
        {
            return type_!=UNDEF && type_!=CUSTOM;
        }
References CUSTOM, type_, and UNDEF.
Referenced by ReadSwc::build(), ReadSwc::parseBranches(), and ReadSwc::ReadSwc().
parent()
unsigned int SwcSegment::parent () const inline
Definition at line 44 of file SwcSegment.h.
{
            return parent_;
        }
References parent_.
Referenced by ReadSwc::assignKids(), ReadSwc::build(), Neuron::buildSegmentTree(), ReadSwc::cleanMultipointSoma(), ReadSwc::cleanZeroLength(), makeCompt(), ReadSwc::parseBranches(), SwcBranch::printDiagnostics(), ReadSwc::traverseBranch(), and ReadSwc::validate().
radius()
double SwcSegment::radius () const inline
Definition at line 76 of file SwcSegment.h.
{
            return radius_;
        }
References radius_.
Referenced by ReadSwc::cleanMultipointSoma(), makeCompt(), SwcBranch::SwcBranch(), ReadSwc::traverseBranch(), and ReadSwc::validate().
replaceKids()
void SwcSegment::replaceKids (const vector< int > & kids) inline
Definition at line 67 of file SwcSegment.h.
        {
            kids_ = kids;
        }
References kids_.
Referenced by ReadSwc::cleanMultipointSoma(), and ReadSwc::cleanZeroLength().
setBad()
void SwcSegment::setBad () inline
Definition at line 39 of file SwcSegment.h.
                      {
            type_ = UNDEF;
        }
References type_, and UNDEF.
Referenced by ReadSwc::cleanMultipointSoma(), and ReadSwc::cleanZeroLength().
setCumulativeDistance()
void SwcSegment::setCumulativeDistance (double len, double L, double pSoma, double eSoma) inline
Definition at line 100 of file SwcSegment.h.
        {
            length_ = len;
            L_ = L;
            pathDistanceFromSoma_ = pSoma;
            electrotonicDistanceFromSoma_ = eSoma;
        }
References electrotonicDistanceFromSoma_, L_, length_, and pathDistanceFromSoma_.
Referenced by traverseCumulativeDistance().
setGeometricalDistanceFromSoma()
void SwcSegment::setGeometricalDistanceFromSoma (const SwcSegment & soma) inline
Definition at line 95 of file SwcSegment.h.
        {
            geometricalDistanceFromSoma_ = v_.distance( soma.v_ );
        }
References Vec::distance(), geometricalDistanceFromSoma_, and v_.
Referenced by Neuron::updateSegmentLengths().
setParent()
void SwcSegment::setParent (unsigned int pa) inline
Definition at line 48 of file SwcSegment.h.
{
            parent_ = pa;
        }
References parent_.
Referenced by ReadSwc::cleanMultipointSoma(), ReadSwc::cleanZeroLength(), and ReadSwc::parseBranches().
type()
unsigned short SwcSegment::type () const inline
Definition at line 72 of file SwcSegment.h.
{
            return type_;
        }
References type_.
Referenced by ReadSwc::build(), ReadSwc::cleanMultipointSoma(), ReadSwc::diagnostics(), and ReadSwc::testIfOnlyBasalsArePresent().
vec()
const Vec & SwcSegment::vec () const inline
Definition at line 91 of file SwcSegment.h.
{
            return v_;
        }
References v_.
Referenced by ReadSwc::cleanMultipointSoma(), Neuron::evalExprForElist(), and makeCompt().
Member Data Documentation
AXON
const short SwcSegment::AXON = 2 static
Definition at line 124 of file SwcSegment.h.
Referenced by ReadSwc::build(), and figureOutType().
BASAL
const short SwcSegment::BASAL = 3 static
Definition at line 125 of file SwcSegment.h.
Referenced by ReadSwc::build(), figureOutType(), and ReadSwc::testIfOnlyBasalsArePresent().
CUSTOM
const short SwcSegment::CUSTOM = 7 static
Definition at line 129 of file SwcSegment.h.
Referenced by OK().
DEND
const short SwcSegment::DEND = 4 static
Definition at line 126 of file SwcSegment.h.
Referenced by figureOutType(), and ReadSwc::testIfOnlyBasalsArePresent().
electrotonicDistanceFromSoma_
double SwcSegment::electrotonicDistanceFromSoma_ protected
electrotonic dist from soma, summed along dend.
Definition at line 161 of file SwcSegment.h.
Referenced by getElecDistFromSoma(), setCumulativeDistance(), SwcSegment(), SwcSegment(), and SwcSegment().
END
const short SwcSegment::END = 6 static
Definition at line 128 of file SwcSegment.h.
FORK
const short SwcSegment::FORK = 5 static
Definition at line 127 of file SwcSegment.h.
geometricalDistanceFromSoma_
double SwcSegment::geometricalDistanceFromSoma_ protected
geometrical distance from soma.
Definition at line 158 of file SwcSegment.h.
Referenced by getGeomDistFromSoma(), setGeometricalDistanceFromSoma(), SwcSegment(), SwcSegment(), and SwcSegment().
kids_
vector< int > SwcSegment::kids_ protected
Definition at line 163 of file SwcSegment.h.
Referenced by addChild(), kids(), replaceKids(), and SwcBranch::SwcBranch().
L_
double SwcSegment::L_ protected
Length of segment.
Definition at line 151 of file SwcSegment.h.
Referenced by L(), setCumulativeDistance(), SwcSegment(), and SwcSegment().
length_
double SwcSegment::length_ protected
Radius of segment.
Definition at line 150 of file SwcSegment.h.
Referenced by length(), setCumulativeDistance(), SwcSegment(), and SwcSegment().
myIndex_
unsigned int SwcSegment::myIndex_ protected
Definition at line 134 of file SwcSegment.h.
Referenced by myIndex(), SwcBranch::SwcBranch(), SwcSegment(), SwcSegment(), and SwcSegment().
parent_
unsigned int SwcSegment::parent_ protected
Number of length constants in segment.
Definition at line 152 of file SwcSegment.h.
Referenced by parent(), setParent(), SwcBranch::SwcBranch(), SwcSegment(), SwcSegment(), and SwcSegment().
pathDistanceFromSoma_
double SwcSegment::pathDistanceFromSoma_ protected
Index of parent. Is ~0 for soma.
dist from soma: not direct, but threaded along dend
Definition at line 155 of file SwcSegment.h.
Referenced by getPathDistFromSoma(), and setCumulativeDistance().
radius_
double SwcSegment::radius_ protected
coordinates of end of segment
Definition at line 149 of file SwcSegment.h.
Referenced by radius(), SwcSegment(), SwcSegment(), and SwcSegment().
SOMA
const short SwcSegment::SOMA = 1 static
Definition at line 123 of file SwcSegment.h.
Referenced by ReadSwc::build(), ReadSwc::cleanMultipointSoma(), and figureOutType().
type_
short SwcSegment::type_ protected
Index of self.
The type of the segment is supposedly as below for SWC files. Seems to be honored in the breach in actual files. 0 = undefined 1 = soma 2 = axon 3 = dendrite 4 = apical dendrite 5 = fork point 6 = end point 7 = custom
Definition at line 147 of file SwcSegment.h.
Referenced by figureOutType(), OK(), setBad(), SwcSegment(), SwcSegment(), SwcSegment(), and type().
typeName
const string SwcSegment::typeName[] static
Definition at line 131 of file SwcSegment.h.
UNDEF
const short SwcSegment::UNDEF = 0 static
Definition at line 122 of file SwcSegment.h.
Referenced by OK(), setBad(), and SwcSegment().
v_
Vec SwcSegment::v_ protected
Definition at line 148 of file SwcSegment.h.
Referenced by distance(), setGeometricalDistanceFromSoma(), SwcSegment(), SwcSegment(), and vec().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/biophysics/SwcSegment.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/biophysics/SwcSegment.cpp