MOOSE - Multiscale Object Oriented Simulation Environment: Species Class Reference
Species Class Reference
#include <Species.h>
Public Member Functions
double getMolWt () const
void handleMolWtRequest (const Eref &e)
void setMolWt (double v)
Species ()
Static Public Member Functions
static const Cinfo * initCinfo ()
Private Attributes
double molWt_
Detailed Description
The species is a unique chemically distinct compound. Examples are Ca2+, PKC, H2O Each pool is associated with a chemical species. Each molecule is associated with a species too.
Definition at line 19 of file Species.h.
Constructor & Destructor Documentation
Species()
Species::Species ()
Definition at line 77 of file Species.cpp.
    : molWt_( 1 )
{
    ;
}
References molWt_.
Member Function Documentation
getMolWt()
double Species::getMolWt () const
Definition at line 101 of file Species.cpp.
{
    return molWt_;
}
References molWt_.
Referenced by initCinfo().
handleMolWtRequest()
void Species::handleMolWtRequest (const Eref & e)
Definition at line 87 of file Species.cpp.
{
    molWtOut()->send( e, molWt_ );
}
References molWt_, molWtOut(), and SrcFinfo1< T >::send().
Referenced by initCinfo().
initCinfo()
const Cinfo * Species::initCinfo () static
Definition at line 21 of file Species.cpp.
{
        // Field Definitions
        static ValueFinfo< Species, double > molWt(
            "molWt",
            "Molecular weight of species",
            &Species::setMolWt,
            &Species::getMolWt
        );
        // MsgDest Definitions
        static DestFinfo handleMolWtRequest( "handleMolWtRequest",
            "Handle requests for molWt.",
            new EpFunc0< Species >( &Species::handleMolWtRequest )
            );
        // SharedMsg Definitions
        static Finfo* poolShared[] = {
            &handleMolWtRequest, molWtOut()
        };
        static SharedFinfo pool( "pool",
            "Connects to pools of this Species type",
            poolShared, sizeof( poolShared ) / sizeof( const Finfo* )
        );
    static Finfo* speciesFinfos[] = {
        &molWt,         // Value
        &pool,          // SharedFinfo, connecting to any pool of this Species
    };
    static Dinfo< Species > dinfo;
    static Cinfo speciesCinfo (
        "Species",
        Neutral::initCinfo(),
        speciesFinfos,
        sizeof( speciesFinfos ) / sizeof ( Finfo* ),
        &dinfo
    );
    return &speciesCinfo;
}
References Cinfo::Cinfo(), DestFinfo::DestFinfo(), EpFunc0< T >::EpFunc0(), getMolWt(), handleMolWtRequest(), Neutral::initCinfo(), molWtOut(), setMolWt(), SharedFinfo::SharedFinfo(), and ValueFinfo< T, F >::ValueFinfo().
setMolWt()
void Species::setMolWt (double v)
Definition at line 96 of file Species.cpp.
{
    molWt_ = v;
}
References molWt_.
Referenced by initCinfo().
Member Data Documentation
molWt_
double Species::molWt_ private
Definition at line 39 of file Species.h.
Referenced by getMolWt(), handleMolWtRequest(), setMolWt(), and Species().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/kinetics/Species.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/kinetics/Species.cpp