MOOSE - Multiscale Object Oriented Simulation Environment: FuncRate Class Reference
FuncRate Class Reference
#include <FuncRateTerm.h>
Public Member Functions
RateTerm * copyWithVolScaling (double vol, double sub, double prd) const
FuncRate (double k, unsigned int targetPoolIndex)
const string & getExpr () const
const vector< unsigned int > & getFuncArgIndex ()
double getR1 () const
Used by Zombie to return rate terms.
unsigned int getReactants (vector< unsigned int > &molIndex) const
double operator() (const double *S) const
Computes the rate. The argument is the molecule array.
void setExpr (const string &s)
void setFuncArgIndex (const vector< unsigned int > &mol)
void setReactants (const vector< unsigned int > &molIndex)
Public Member Functions inherited from ExternReac
double getR2 () const
Used by Zombie to return rate terms.
void rescaleVolume (short comptIndex, const vector< short > &compartmentLookup, double ratio)
void setR1 (double k1)
Used by Zombie to assign rate terms.
void setR2 (double k2)
Used by Zombie to assign rate terms.
void setRates (double k1, double k2)
Public Member Functions inherited from RateTerm
RateTerm ()
virtual ~RateTerm ()
Protected Attributes
shared_ptr< FuncTerm > func_
double funcVolPower_
double k_
Additional Inherited Members
Static Public Attributes inherited from RateTerm
static const double EPSILON = 1.0e-6
Detailed Description
This FuncRate manages a one-way reaction whose rate is determined by a Function. It has no substrates, just controls the rate of change of a target molecule.
dtarget/dt = func(x0, x1, x2..., t)
The values x0, x1, x2.. are numbers at this point. So is the rate output of this function. There may be a problem if there is a volume change.
Definition at line 21 of file FuncRateTerm.h.
Constructor & Destructor Documentation
FuncRate()
FuncRate::FuncRate (double k, unsigned int targetPoolIndex) inline
Definition at line 24 of file FuncRateTerm.h.
                                                           :
            k_( k )
            , func_(shared_ptr<FuncTerm>(new FuncTerm()))
            , funcVolPower_( 0.0 )
    {
        func_->setTarget( targetPoolIndex );
    }
References func_, FuncTerm::FuncTerm(), funcVolPower_, k_, and FuncTerm::setTarget().
Referenced by copyWithVolScaling(), FuncReac::FuncReac(), and Stoich::installAndUnschedFuncRate().
Member Function Documentation
copyWithVolScaling()
RateTerm * FuncRate::copyWithVolScaling (double vol, double sub, double prd) const inline virtual
Duplicates rate term and then applies volume scaling. Arguments are volume of reference voxel, product of vol/refVol for all substrates: applied to R1 product of vol/refVol for all products: applied to R2
Note that unless the reaction is cross-compartment, the vol/refVol will be one.
Reimplemented from ExternReac.
Reimplemented in FuncReac.
Definition at line 70 of file FuncRateTerm.h.
        {
            assert(! std::isnan(vol));
            double ratio = sub * pow( NA * vol, funcVolPower_ );
            FuncRate* ret = new FuncRate( k_ / ratio, func_->getTarget() );
            ret->funcVolPower_ = funcVolPower_;
            ret->func_ = func_;
            return ret;
        }
References func_, FuncRate(), funcVolPower_, FuncTerm::getTarget(), k_, and NA.
getExpr()
const string & FuncRate::getExpr () const inline
Definition at line 66 of file FuncRateTerm.h.
{
            return func_->getExpr();
        }
References func_, and FuncTerm::getExpr().
getFuncArgIndex()
const vector< unsigned int > & FuncRate::getFuncArgIndex () inline
Definition at line 54 of file FuncRateTerm.h.
        {
            return func_->getReactantIndex();
        }
References func_, and FuncTerm::getReactantIndex().
Referenced by Gsolve::fillIncrementFuncDep().
getR1()
double FuncRate::getR1 () const inline virtual
Used by Zombie to return rate terms.
Reimplemented from ExternReac.
Definition at line 80 of file FuncRateTerm.h.
{
            return k_;
        }
References k_.
getReactants()
unsigned int FuncRate::getReactants (vector< unsigned int > & molIndex) const inline virtual
This function finds the reactant indices in the vector S. It returns the number of substrates found, which are the first entries in molIndex. The products are the remaining ones. Note that it does NOT find products for unidirectional reactions, which is a bit of a problem.
Reimplemented from ExternReac.
Reimplemented in FuncReac.
Definition at line 40 of file FuncRateTerm.h.
{
            molIndex.resize( 1 );
            molIndex[0] = func_->getTarget();
            // This is the number of substrates to the reac. It is zero.
            return 0;
            // The target molecule is handled as a product.
        }
References func_, and FuncTerm::getTarget().
operator()()
double FuncRate::operator() (const double * S) const inline virtual
Computes the rate. The argument is the molecule array.
Reimplemented from ExternReac.
Reimplemented in FuncReac.
Definition at line 32 of file FuncRateTerm.h.
{
            double t = Field< double >::get( Id(1), "currentTime" );
            auto v = (*func_)( S, t ); // get rate from func calculation.
            *(const_cast< double * >( &k_ ) ) = v;
            assert(! std::isnan(v));
            return v;
        }
References func_, Field< A >::get(), Id::Id(), k_, and FuncTerm::operator()().
setExpr()
void FuncRate::setExpr (const string & s) inline
Definition at line 63 of file FuncRateTerm.h.
{
            func_->setExpr( s );
        }
References func_, and FuncTerm::setExpr().
Referenced by Stoich::installAndUnschedFuncRate(), Stoich::installAndUnschedFuncReac(), and Stoich::setFunctionExpr().
setFuncArgIndex()
void FuncRate::setFuncArgIndex (const vector< unsigned int > & mol) inline
Definition at line 59 of file FuncRateTerm.h.
{
            func_->setReactantIndex( mol );
        }
References func_, and FuncTerm::setReactantIndex().
Referenced by Stoich::installAndUnschedFuncRate(), and Stoich::installAndUnschedFuncReac().
setReactants()
void FuncRate::setReactants (const vector< unsigned int > & molIndex) inline
Definition at line 49 of file FuncRateTerm.h.
{
            assert( molIndex.size() > 0 );
            func_->setTarget( molIndex[0] );
        }
References func_, and FuncTerm::setTarget().
Member Data Documentation
func_
shared_ptr<FuncTerm> FuncRate::func_ protected
Definition at line 86 of file FuncRateTerm.h.
Referenced by copyWithVolScaling(), FuncReac::copyWithVolScaling(), FuncRate(), getExpr(), getFuncArgIndex(), getReactants(), operator()(), FuncReac::operator()(), setExpr(), setFuncArgIndex(), and setReactants().
funcVolPower_
double FuncRate::funcVolPower_ protected
Definition at line 87 of file FuncRateTerm.h.
Referenced by copyWithVolScaling(), FuncReac::copyWithVolScaling(), and FuncRate().
k_
double FuncRate::k_ protected
Definition at line 85 of file FuncRateTerm.h.
Referenced by copyWithVolScaling(), FuncReac::copyWithVolScaling(), FuncRate(), getR1(), operator()(), FuncReac::operator()(), and FuncReac::rescaleVolume().
The documentation for this class was generated from the following file:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/ksolve/FuncRateTerm.h