MOOSE - Multiscale Object Oriented Simulation Environment: OpFunc0Base Class Reference
OpFunc0Base Class Reference abstract
#include <OpFuncBase.h>
Public Member Functions
bool checkFinfo (const Finfo *s) const
const OpFunc * makeHopFunc (HopIndex hopIndex) const
virtual void op (const Eref &e) const =0
void opBuffer (const Eref &e, double *buf) const
Executes the OpFunc by converting args.
string rttiType () const
Public Member Functions inherited from OpFunc
OpFunc ()
unsigned int opIndex () const
virtual void opVecBuffer (const Eref &e, double *buf) const
Executes the OpFunc for all data by converting a vector of args.
bool setIndex (unsigned int i)
Used when rebuilding the Fid->OpFunc mapping.
virtual ~OpFunc ()
Additional Inherited Members
Static Public Member Functions inherited from OpFunc
static const OpFunc * lookop (unsigned int opIndex)
static unsigned int rebuildOpIndex ()
cleans out the entire Ops vector. Returns size of orig vector.
Detailed Description
Definition at line 82 of file OpFuncBase.h.
Member Function Documentation
checkFinfo()
bool OpFunc0Base::checkFinfo (const Finfo * s) const inline virtual
Implements OpFunc.
Definition at line 85 of file OpFuncBase.h.
    {
        return dynamic_cast< const SrcFinfo0* >( s );
    }
makeHopFunc()
const OpFunc * OpFunc0Base::makeHopFunc (HopIndex hopIndex) const virtual
Implements OpFunc.
Definition at line 32 of file OpFuncBase.cpp.
{
    return new HopFunc0( hopIndex );
}
References HopFunc0::HopFunc0().
Referenced by SetGet0::set().
op()
virtual void OpFunc0Base::op (const Eref & e) const pure virtual
Implemented in EpFunc0< T >, HopFunc0, and OpFunc0< T >.
Referenced by opBuffer(), SrcFinfo0::send(), and SetGet0::set().
opBuffer()
void OpFunc0Base::opBuffer (const Eref & e, double * buf) const virtual
Executes the OpFunc by converting args.
Implements OpFunc.
Definition at line 37 of file OpFuncBase.cpp.
{
    op( e );
}
References op().
rttiType()
string OpFunc0Base::rttiType () const inline virtual
Implements OpFunc.
Definition at line 96 of file OpFuncBase.h.
    {
        return "void";
    }
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/basecode/OpFuncBase.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/basecode/OpFuncBase.cpp