MOOSE - Multiscale Object Oriented Simulation Environment: ZeroOrder Class Reference
ZeroOrder Class Reference
#include <RateTerm.h>
Public Member Functions
RateTerm * copyWithVolScaling (double vol, double sub, double prd) const
double getR1 () const
Used by Zombie to return rate terms.
double getR2 () const
Used by Zombie to return rate terms.
unsigned int getReactants (vector< unsigned int > &molIndex) const
double operator() (const double *S) const
Computes the rate. The argument is the molecule array.
void rescaleVolume (short comptIndex, const vector< short > &compartmentLookup, double ratio)
void setK (double k)
void setR1 (double k1)
Used by Zombie to assign rate terms.
void setR2 (double k2)
Used by Zombie to assign rate terms.
void setRates (double k1, double k2)
ZeroOrder (double k)
Public Member Functions inherited from RateTerm
RateTerm ()
virtual ~RateTerm ()
Protected Attributes
double k_
Additional Inherited Members
Static Public Attributes inherited from RateTerm
static const double EPSILON = 1.0e-6
Detailed Description
Definition at line 276 of file RateTerm.h.
Constructor & Destructor Documentation
ZeroOrder()
ZeroOrder::ZeroOrder (double k) inline
Definition at line 279 of file RateTerm.h.
        : k_( k )
    {
        assert( !std::isnan( k_ ) );
    }
References k_.
Referenced by copyWithVolScaling(), FirstOrder::FirstOrder(), Flux::Flux(), installDummy(), Stoich::installDummyEnzyme(), Stoich::makeHalfReaction(), NOrder::NOrder(), SecondOrder::SecondOrder(), and StochSecondOrderSingleSubstrate::StochSecondOrderSingleSubstrate().
Member Function Documentation
copyWithVolScaling()
RateTerm * ZeroOrder::copyWithVolScaling (double vol, double sub, double prd) const inline virtual
Duplicates rate term and then applies volume scaling. Arguments are volume of reference voxel, product of vol/refVol for all substrates: applied to R1 product of vol/refVol for all products: applied to R2
Note that unless the reaction is cross-compartment, the vol/refVol will be one.
Implements RateTerm.
Definition at line 335 of file RateTerm.h.
    {
        return new ZeroOrder( k_ );
    }
References k_, and ZeroOrder().
Referenced by BidirectionalReaction::copyWithVolScaling().
getR1()
double ZeroOrder::getR1 () const inline virtual
Used by Zombie to return rate terms.
Implements RateTerm.
Definition at line 313 of file RateTerm.h.
    {
        return k_;
    }
References k_.
Referenced by BidirectionalReaction::getR1(), and BidirectionalReaction::getR2().
getR2()
double ZeroOrder::getR2 () const inline virtual
Used by Zombie to return rate terms.
Implements RateTerm.
Definition at line 318 of file RateTerm.h.
    {
        return 0.0;
    }
getReactants()
unsigned int ZeroOrder::getReactants (vector< unsigned int > & molIndex) const inline virtual
This function finds the reactant indices in the vector S. It returns the number of substrates found, which are the first entries in molIndex. The products are the remaining ones. Note that it does NOT find products for unidirectional reactions, which is a bit of a problem.
Implements RateTerm.
Definition at line 323 of file RateTerm.h.
    {
        molIndex.resize( 0 );
        return 0;
    }
Referenced by BidirectionalReaction::getReactants(), Stoich::innerInstallReaction(), and Stoich::installEnzyme().
operator()()
double ZeroOrder::operator() (const double * S) const inline virtual
Computes the rate. The argument is the molecule array.
Implements RateTerm.
Definition at line 285 of file RateTerm.h.
    {
        assert(! std::isnan( k_ ) );
        return k_;
    }
References k_.
Referenced by BidirectionalReaction::operator()().
rescaleVolume()
void ZeroOrder::rescaleVolume (short comptIndex, const vector< short > & compartmentLookup, double ratio) inline virtual
This is used to rescale the RateTerm kinetics when the compartment volume changes. This is needed because the kinetics are in extensive units, that is, mol numbers, rather than in intensive units like concentration. So when the volume changes the rate terms change. Each Rate term checks if any of its reactant molecules are affected, and if so, rescales. Ratio is newVol / oldVol
Implements RateTerm.
Definition at line 329 of file RateTerm.h.
    {
        return; // Nothing needs to be scaled.
    }
Referenced by BidirectionalReaction::rescaleVolume().
setK()
void ZeroOrder::setK (double k) inline
Definition at line 291 of file RateTerm.h.
    {
        assert( !std::isnan( k ) );
        if ( k >= 0.0 )
            k_ = k;
    }
References k_.
Referenced by setR1(), BidirectionalReaction::setR1(), BidirectionalReaction::setR2(), setRates(), and BidirectionalReaction::setRates().
setR1()
void ZeroOrder::setR1 (double k1) inline virtual
Used by Zombie to assign rate terms.
Implements RateTerm.
Definition at line 303 of file RateTerm.h.
    {
        setK( k1 );
    }
References setK().
setR2()
void ZeroOrder::setR2 (double k2) inline virtual
Used by Zombie to assign rate terms.
Implements RateTerm.
Definition at line 308 of file RateTerm.h.
    {
        ;
    }
setRates()
void ZeroOrder::setRates (double k1, double k2) inline virtual
Assign the rates.
Implements RateTerm.
Definition at line 298 of file RateTerm.h.
    {
        setK( k1 );
    }
References setK().
Member Data Documentation
k_
double ZeroOrder::k_ protected
Definition at line 341 of file RateTerm.h.
Referenced by copyWithVolScaling(), Flux::copyWithVolScaling(), FirstOrder::copyWithVolScaling(), SecondOrder::copyWithVolScaling(), StochSecondOrderSingleSubstrate::copyWithVolScaling(), NOrder::copyWithVolScaling(), StochNOrder::copyWithVolScaling(), getR1(), operator()(), Flux::operator()(), FirstOrder::operator()(), SecondOrder::operator()(), StochSecondOrderSingleSubstrate::operator()(), NOrder::operator()(), StochNOrder::operator()(), SecondOrder::rescaleVolume(), StochSecondOrderSingleSubstrate::rescaleVolume(), NOrder::rescaleVolume(), setK(), and ZeroOrder().
The documentation for this class was generated from the following file:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/ksolve/RateTerm.h