MOOSE - Multiscale Object Oriented Simulation Environment: GetEpFunc1< T, L, A > Class Template Reference
GetEpFunc1< T, L, A > Class Template Reference
#include <EpFunc.h>
Public Member Functions
GetEpFunc1 (A(T::*func)(const Eref &e, L) const)
void op (const Eref &e, L index, ObjId recipient, FuncId fid) const
A returnOp (const Eref &e, const L &index) const
Public Member Functions inherited from LookupGetOpFuncBase< L, A >
bool checkFinfo (const Finfo *s) const
const OpFunc * makeHopFunc (HopIndex hopIndex) const
const OpFunc * makeHopFunc (HopIndex hopIndex, const L &index) const
void opBuffer (const Eref &e, double *buf) const
Executes the OpFunc by converting args.
string rttiType () const
Public Member Functions inherited from OpFunc
OpFunc ()
unsigned int opIndex () const
virtual void opVecBuffer (const Eref &e, double *buf) const
Executes the OpFunc for all data by converting a vector of args.
bool setIndex (unsigned int i)
Used when rebuilding the Fid->OpFunc mapping.
virtual ~OpFunc ()
Private Attributes
A(T::* func_)(const Eref &e, L) const
Additional Inherited Members
Static Public Member Functions inherited from OpFunc
static const OpFunc * lookop (unsigned int opIndex)
static unsigned int rebuildOpIndex ()
cleans out the entire Ops vector. Returns size of orig vector.
Detailed Description
template<class T, class L, class A>
class GetEpFunc1< T, L, A >
This specialized EpFunc is for returning a single field value, but the field lookup requires an index argument as well. Unlike the regular GetOpFunc, this variant takes the Eref and Qinfo. It generates an opFunc that takes a single argument: FuncId of the function on the object that requested the value. The EpFunc then sends back a message with the info.
Definition at line 222 of file EpFunc.h.
Constructor & Destructor Documentation
GetEpFunc1()
template<class T , class L , class A > GetEpFunc1< T, L, A >::GetEpFunc1 (A(T::*)(const Eref &e, L) const func) inline
Definition at line 226 of file EpFunc.h.
        : func_( func )
    {;}
Member Function Documentation
op()
template<class T , class L , class A > void GetEpFunc1< T, L, A >::op (const Eref & e, L index, ObjId recipient, FuncId fid) const inline virtual
Implements LookupGetOpFuncBase< L, A >.
Definition at line 231 of file EpFunc.h.
    {
        const OpFunc *f = recipient.element()->cinfo()->getOpFunc( fid);
        const OpFunc1Base< A >* recvOpFunc =
            dynamic_cast< const OpFunc1Base< A >* >( f );
        assert( recvOpFunc );
        recvOpFunc->op( recipient.eref(), returnOp( e, index ) );
    }
References Element::cinfo(), ObjId::element(), ObjId::eref(), Cinfo::getOpFunc(), and GetEpFunc1< T, L, A >::returnOp().
returnOp()
template<class T , class L , class A > A GetEpFunc1< T, L, A >::returnOp (const Eref & e, const L & index) const inline virtual
Implements LookupGetOpFuncBase< L, A >.
Definition at line 241 of file EpFunc.h.
    {
        return ( reinterpret_cast< T* >( e.data() )->*func_)(
                   e, index );
    }
References Eref::data().
Referenced by GetEpFunc1< T, L, A >::op().
Member Data Documentation
func_
template<class T , class L , class A > A(T::* GetEpFunc1< T, L, A >::func_) (const Eref &e, L) const private
Definition at line 248 of file EpFunc.h.
The documentation for this class was generated from the following file:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/basecode/EpFunc.h