MOOSE - Multiscale Object Oriented Simulation Environment: Vec Class Reference
Vec Class Reference
#include <Vec.h>
Public Member Functions
double a0 () const
double a1 () const
double a2 () const
Vec crossProduct (const Vec &other) const
double distance (const Vec &other) const
double dotProduct (const Vec &other) const
double length () const
Vec operator* (const double &other) const
Vec operator+ (const Vec &other) const
Vec operator- (const Vec &other) const
bool operator== (const Vec &other) const
void orthogonalAxes (Vec &u, Vec &v) const
Generates vectors u and v to form a mutually orthogonal system.
Vec pointOnLine (const Vec &end, double k)
void unitLength ()
Rescales vector so it has unit length.
Vec ()
Vec (double a0, double a1, double a2)
Private Attributes
double a0_
double a1_
double a2_
Detailed Description
Definition at line 13 of file Vec.h.
Constructor & Destructor Documentation
Vec() [1/2]
Vec::Vec (double a0, double a1, double a2)
Definition at line 14 of file Vec.cpp.
                : a0_( a0 ), a1_( a1 ), a2_( a2 )
{;}
References a0_, a1_, and a2_.
Referenced by addSpine(), PresynMesh::buildOnDendrites(), coordSystem(), crossProduct(), Neuron::evalExprForElist(), NeuroMesh::indexToSpace(), CylBase::matchCubeMeshEntries(), CylMesh::matchCubeMeshEntries(), CylBase::nearest(), PsdMesh::nearest(), SpineMesh::nearest(), operator*(), operator+(), operator-(), orthogonalAxes(), pointOnLine(), reorientSpine(), SwcSegment::SwcSegment(), SwcSegment::SwcSegment(), and testVec().
Vec() [2/2]
Vec::Vec () inline
Definition at line 16 of file Vec.h.
            : a0_( 0.0 ), a1_( 0.0 ), a2_( 0.0 )
        {;}
References a0_, a1_, and a2_.
Member Function Documentation
a0()
double Vec::a0 () const inline
Definition at line 34 of file Vec.h.
{
                return a0_;
        }
References a0_.
Referenced by addSpine(), PresynMesh::buildOnDendrites(), ReadSwc::cleanMultipointSoma(), coordSystem(), Neuron::evalExprForElist(), fillPointsOnCircle(), fillPointsOnCircle(), fillPointsOnDisc(), NeuroMesh::indexToSpace(), makeCompt(), CylBase::matchCubeMeshEntries(), CylMesh::matchCubeMeshEntries(), and reorientSpine().
a1()
double Vec::a1 () const inline
Definition at line 37 of file Vec.h.
{
                return a1_;
        }
References a1_.
Referenced by PresynMesh::buildOnDendrites(), ReadSwc::cleanMultipointSoma(), coordSystem(), Neuron::evalExprForElist(), fillPointsOnCircle(), fillPointsOnCircle(), fillPointsOnDisc(), NeuroMesh::indexToSpace(), makeCompt(), CylBase::matchCubeMeshEntries(), CylMesh::matchCubeMeshEntries(), and reorientSpine().
a2()
double Vec::a2 () const inline
Definition at line 40 of file Vec.h.
{
                return a2_;
        }
References a2_.
Referenced by PresynMesh::buildOnDendrites(), ReadSwc::cleanMultipointSoma(), coordSystem(), Neuron::evalExprForElist(), fillPointsOnCircle(), fillPointsOnCircle(), fillPointsOnDisc(), NeuroMesh::indexToSpace(), makeCompt(), CylBase::matchCubeMeshEntries(), CylMesh::matchCubeMeshEntries(), and reorientSpine().
crossProduct()
Vec Vec::crossProduct (const Vec & other) const
Definition at line 26 of file Vec.cpp.
{
    double c0 = a1_ * other.a2_ - a2_ * other.a1_;
    double c1 = a2_ * other.a0_ - a0_ * other.a2_;
    double c2 = a0_ * other.a1_ - a1_ * other.a0_;
    return Vec( c0, c1, c2 );
}
References a0_, a1_, a2_, and Vec().
Referenced by coordSystem(), orthogonalAxes(), and testVec().
distance()
double Vec::distance (const Vec & other) const
Definition at line 81 of file Vec.cpp.
{
    return ( *this - other ).length();
}
References length(), and operator-().
Referenced by SwcSegment::distance(), CylBase::nearest(), PsdMesh::nearest(), SpineMesh::nearest(), and SwcSegment::setGeometricalDistanceFromSoma().
dotProduct()
double Vec::dotProduct (const Vec & other) const
Definition at line 22 of file Vec.cpp.
{
            return a0_ * other.a0_ + a1_ * other.a1_ + a2_ * other.a2_;
}
References a0_, a1_, and a2_.
Referenced by CylBase::nearest(), reorientSpine(), and testVec().
length()
double Vec::length () const
Definition at line 18 of file Vec.cpp.
{
            return sqrt( a0_*a0_ + a1_*a1_ + a2_*a2_ );
}
References a0_, a1_, and a2_.
Referenced by coordSystem(), distance(), Neuron::evalExprForElist(), orthogonalAxes(), and unitLength().
operator*()
Vec Vec::operator* (const double & other) const
Definition at line 76 of file Vec.cpp.
{
    return Vec( a0_ * other, a1_ * other, a2_ * other );
}
References a0_, a1_, a2_, and Vec().
Referenced by addSpine(), and reorientSpine().
operator+()
Vec Vec::operator+ (const Vec & other) const
Definition at line 72 of file Vec.cpp.
{
    return Vec( a0_ + other.a0_, a1_ + other.a1_, a2_ + other.a2_ );
}
References a0_, a1_, a2_, and Vec().
Referenced by reorientSpine().
operator-()
Vec Vec::operator- (const Vec & other) const
Definition at line 68 of file Vec.cpp.
{
    return Vec( a0_ - other.a0_, a1_ - other.a1_, a2_ - other.a2_ );
}
References a0_, a1_, a2_, and Vec().
Referenced by PresynMesh::buildOnDendrites(), distance(), and CylBase::nearest().
operator==()
bool Vec::operator== (const Vec & other) const
Definition at line 61 of file Vec.cpp.
{
    return
        doubleEq( a0_, other.a0_) &&
        doubleEq( a1_, other.a1_) &&
        doubleEq( a2_, other.a2_);
}
References a0_, a1_, a2_, and doubleEq().
Referenced by testVec().
orthogonalAxes()
void Vec::orthogonalAxes (Vec & u, Vec & v) const
Generates vectors u and v to form a mutually orthogonal system.
Definition at line 41 of file Vec.cpp.
{
    assert( !doubleEq( length(), 0 ) );
    if ( doubleApprox( a1_, 0 ) && doubleApprox( a2_, 0 ) ) {
        u = crossProduct( Vec( a0_, a1_, a2_ - a0_ ) );
    } else {
        u = crossProduct( Vec( a0_ + a1_ + a2_, a1_, a2_ ) );
    }
    v = crossProduct( u );
    u.unitLength();
    v.unitLength();
}
References a0_, a1_, a2_, crossProduct(), doubleApprox(), doubleEq(), length(), unitLength(), and Vec().
Referenced by PresynMesh::buildOnDendrites(), CylBase::matchCubeMeshEntries(), CylMesh::matchCubeMeshEntries(), and testVec().
pointOnLine()
Vec Vec::pointOnLine (const Vec & end, double k)
Returns a point on the line from self to 'end', a fraction k from the 'self'. r = self + k.(end - self)
Definition at line 53 of file Vec.cpp.
{
    return Vec(
                    a0_ + k * ( end.a0_ - a0_ ),
                    a1_ + k * ( end.a1_ - a1_ ),
                    a2_ + k * ( end.a2_ - a2_ ) );
}
References a0_, a1_, a2_, and Vec().
Referenced by NeuroMesh::indexToSpace(), and CylBase::nearest().
unitLength()
void Vec::unitLength ()
Rescales vector so it has unit length.
Definition at line 33 of file Vec.cpp.
                     {
    double len = length();
    assert( len > 0.0 );
    a0_ /= len;
    a1_ /= len;
    a2_ /= len;
}
References a0_, a1_, a2_, and length().
Referenced by orthogonalAxes().
Member Data Documentation
a0_
double Vec::a0_ private
Definition at line 60 of file Vec.h.
Referenced by a0(), crossProduct(), dotProduct(), length(), operator*(), operator+(), operator-(), operator==(), orthogonalAxes(), pointOnLine(), unitLength(), Vec(), and Vec().
a1_
double Vec::a1_ private
Definition at line 61 of file Vec.h.
Referenced by a1(), crossProduct(), dotProduct(), length(), operator*(), operator+(), operator-(), operator==(), orthogonalAxes(), pointOnLine(), unitLength(), Vec(), and Vec().
a2_
double Vec::a2_ private
Definition at line 62 of file Vec.h.
Referenced by a2(), crossProduct(), dotProduct(), length(), operator*(), operator+(), operator-(), operator==(), orthogonalAxes(), pointOnLine(), unitLength(), Vec(), and Vec().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/utility/Vec.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/utility/Vec.cpp