MOOSE - Multiscale Object Oriented Simulation Environment: OpFunc6< T, A1, A2, A3, A4, A5, A6 > Class Template Reference
OpFunc6< T, A1, A2, A3, A4, A5, A6 > Class Template Reference
#include <OpFunc.h>
Public Member Functions
void op (const Eref &e, A1 arg1, A2 arg2, A3 arg3, A4 arg4, A5 arg5, A6 arg6) const
OpFunc6 (void(T::*func)(A1, A2, A3, A4, A5, A6))
Public Member Functions inherited from OpFunc6Base< A1, A2, A3, A4, A5, A6 >
bool checkFinfo (const Finfo *s) const
const OpFunc * makeHopFunc (HopIndex hopIndex) const
void opBuffer (const Eref &e, double *buf) const
Executes the OpFunc by converting args.
string rttiType () const
Public Member Functions inherited from OpFunc
OpFunc ()
unsigned int opIndex () const
virtual void opVecBuffer (const Eref &e, double *buf) const
Executes the OpFunc for all data by converting a vector of args.
bool setIndex (unsigned int i)
Used when rebuilding the Fid->OpFunc mapping.
virtual ~OpFunc ()
Private Attributes
void(T::* func_)(A1, A2, A3, A4, A5, A6)
Additional Inherited Members
Static Public Member Functions inherited from OpFunc
static const OpFunc * lookop (unsigned int opIndex)
static unsigned int rebuildOpIndex ()
cleans out the entire Ops vector. Returns size of orig vector.
Detailed Description
template<class T, class A1, class A2, class A3, class A4, class A5, class A6>
class OpFunc6< T, A1, A2, A3, A4, A5, A6 >
Definition at line 114 of file OpFunc.h.
Constructor & Destructor Documentation
OpFunc6()
template<class T , class A1 , class A2 , class A3 , class A4 , class A5 , class A6 > OpFunc6< T, A1, A2, A3, A4, A5, A6 >::OpFunc6 (void(T::*)(A1, A2, A3, A4, A5, A6) func) inline
Definition at line 117 of file OpFunc.h.
        : func_( func )
    {;}
References OpFunc6< T, A1, A2, A3, A4, A5, A6 >::func_.
Member Function Documentation
op()
template<class T , class A1 , class A2 , class A3 , class A4 , class A5 , class A6 > void OpFunc6< T, A1, A2, A3, A4, A5, A6 >::op (const Eref & e, A1 arg1, A2 arg2, A3 arg3, A4 arg4, A5 arg5, A6 arg6) const inline virtual
Implements OpFunc6Base< A1, A2, A3, A4, A5, A6 >.
Definition at line 121 of file OpFunc.h.
    {
        (reinterpret_cast< T* >( e.data() )->*func_)(
            arg1, arg2, arg3, arg4, arg5, arg6 );
    }
References Eref::data(), and OpFunc6< T, A1, A2, A3, A4, A5, A6 >::func_.
Member Data Documentation
func_
template<class T , class A1 , class A2 , class A3 , class A4 , class A5 , class A6 > void(T::* OpFunc6< T, A1, A2, A3, A4, A5, A6 >::func_) (A1, A2, A3, A4, A5, A6) private
Definition at line 129 of file OpFunc.h.
Referenced by OpFunc6< T, A1, A2, A3, A4, A5, A6 >::op(), and OpFunc6< T, A1, A2, A3, A4, A5, A6 >::OpFunc6().
The documentation for this class was generated from the following file:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/basecode/OpFunc.h