MOOSE - Multiscale Object Oriented Simulation Environment: GetOpFunc< T, A > Class Template Reference
GetOpFunc< T, A > Class Template Reference
#include <OpFunc.h>
Public Member Functions
GetOpFunc (A(T::*func)() const)
void op (const Eref &e, vector< A > *ret) const
A returnOp (const Eref &e) const
Public Member Functions inherited from GetOpFuncBase< A >
const OpFunc * makeHopFunc (HopIndex hopIndex) const
void opBuffer (const Eref &e, double *buf) const
Executes the OpFunc by converting args.
Public Member Functions inherited from OpFunc1Base< vector< A > * >
bool checkFinfo (const Finfo *s) const
const OpFunc * makeHopFunc (HopIndex hopIndex) const
void opBuffer (const Eref &e, double *buf) const
Executes the OpFunc by converting args.
virtual void opVec (const Eref &e, const vector< vector< A > * > &arg, const OpFunc1Base< vector< A > * > *op) const
void opVecBuffer (const Eref &e, double *buf) const
Executes the OpFunc for all data by converting a vector of args.
string rttiType () const
Public Member Functions inherited from OpFunc
OpFunc ()
unsigned int opIndex () const
bool setIndex (unsigned int i)
Used when rebuilding the Fid->OpFunc mapping.
virtual ~OpFunc ()
Private Attributes
A(T::* func_)() const
Additional Inherited Members
Static Public Member Functions inherited from OpFunc
static const OpFunc * lookop (unsigned int opIndex)
static unsigned int rebuildOpIndex ()
cleans out the entire Ops vector. Returns size of orig vector.
Detailed Description
template<class T, class A>
class GetOpFunc< T, A >
This specialized OpFunc is for returning a single field value It generates an opFunc that takes a single argument, a reference to a vector into which the return value should be appended. It manages the 'get' function that retrieves the return value. Note that the 'get' function must be blocking in case the request goes off node.
Definition at line 141 of file OpFunc.h.
Constructor & Destructor Documentation
GetOpFunc()
template<class T , class A > GetOpFunc< T, A >::GetOpFunc (A(T::*)() const func) inline
Definition at line 144 of file OpFunc.h.
                                      : func_( func )
    {;}
Member Function Documentation
op()
template<class T , class A > void GetOpFunc< T, A >::op (const Eref & e, vector< A > * ret) const inline virtual
Implements OpFunc1Base< vector< A > * >.
Definition at line 147 of file OpFunc.h.
    {
        ret->push_back( returnOp( e ) );
    }
References GetOpFunc< T, A >::returnOp().
returnOp()
template<class T , class A > A GetOpFunc< T, A >::returnOp (const Eref & e) const inline virtual
Implements GetOpFuncBase< A >.
Definition at line 152 of file OpFunc.h.
    {
        return ( reinterpret_cast< T* >( e.data() )->*func_)();
    }
References Eref::data().
Referenced by GetOpFunc< T, A >::op().
Member Data Documentation
func_
template<class T , class A > A(T::* GetOpFunc< T, A >::func_) () const private
Definition at line 158 of file OpFunc.h.
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/basecode/SetGet.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/basecode/OpFunc.h