MOOSE - Multiscale Object Oriented Simulation Environment: GraupnerBrunel2012CaPlasticitySynHandler Class Reference
GraupnerBrunel2012CaPlasticitySynHandler Class Reference
#include <GraupnerBrunel2012CaPlasticitySynHandler.h>
Public Member Functions
void addPostSpike (const Eref &e, double time)
void addSpike (unsigned int index, double time, double weight)
unsigned int addSynapse ()
Adds a new synapse, returns its index.
void dropSynapse (unsigned int droppedSynNumber)
bool getBistable () const
double getCa () const
double getCaInit () const
double getCaPost () const
double getCaPre () const
double getDelayD () const
double getGammaD () const
double getGammaP () const
double getNoiseSD () const
bool getNoisy () const
double getTauCa () const
double getTauSyn () const
double getThetaD () const
double getThetaP () const
double getTopSpike (unsigned int index) const
double getWeightMax () const
double getWeightMin () const
double getWeightScale () const
GraupnerBrunel2012CaPlasticitySynHandler ()
GraupnerBrunel2012CaPlasticitySynHandler & operator= (const GraupnerBrunel2012CaPlasticitySynHandler &other)
void reinitSeed ()
void setBistable (bool v)
void setCa (double v)
void setCaInit (double v)
void setCaPost (double v)
void setCaPre (double v)
void setDelayD (double v)
void setGammaD (double v)
void setGammaP (double v)
void setNoiseSD (double v)
void setNoisy (bool v)
void setTauCa (double v)
void setTauSyn (double v)
void setThetaD (double v)
void setThetaP (double v)
void setWeightMax (double v)
void setWeightMin (double v)
void setWeightScale (double v)
weightFactors updateCaWeightFactors (double currTime)
void updateWeight (Synapse *synPtr, weightFactors *wFacPtr)
unsigned int vGetNumSynapses () const
Synapse * vGetSynapse (unsigned int i)
void vProcess (const Eref &e, ProcPtr p)
void vReinit (const Eref &e, ProcPtr p)
void vSetNumSynapses (unsigned int num)
~GraupnerBrunel2012CaPlasticitySynHandler ()
Public Member Functions inherited from SynHandlerBase
unsigned int getNumSynapses () const
Synapse * getSynapse (unsigned int i)
void process (const Eref &e, ProcPtr p)
bool rangeWarning (const string &field, double value)
void reinit (const Eref &e, ProcPtr p)
void setNumSynapses (unsigned int num)
SynHandlerBase ()
virtual ~SynHandlerBase ()
Static Public Member Functions
static const Cinfo * initCinfo ()
Static Public Member Functions inherited from SynHandlerBase
static SrcFinfo1< double > * activationOut ()
static const Cinfo * initCinfo ()
Private Attributes
bool bistable_
double Ca_
double CaInit_
double CaPost_
double CaPre_
double delayD_
priority_queue< PreSynEvent, vector< PreSynEvent >, CompareSynEvent > delayDPreEvents_
moose::MOOSE_NORMAL_DISTRIBUTION< double > dist_
priority_queue< PreSynEvent, vector< PreSynEvent >, CompareSynEvent > events_
double gammaD_
double gammaP_
double lastCaUpdateTime_
double noiseSD_
bool noisy_
priority_queue< PostSynEvent, vector< PostSynEvent >, ComparePostSynEvent > postEvents_
moose::MOOSE_RANDOM_DEVICE rd_
moose::MOOSE_RNG_DEFAULT_ENGINE rng_
unsigned long seed_
vector< Synapse > synapses_
double tauCa_
double tauSyn_
double thetaD_
double thetaP_
double weightMax_
double weightMin_
double weightScale_
Detailed Description
This handles simple synapses without plasticity. It uses a priority queue to manage them. This gets inefficient for large numbers of synapses but is pretty robust.
Definition at line 43 of file GraupnerBrunel2012CaPlasticitySynHandler.h.
Constructor & Destructor Documentation
GraupnerBrunel2012CaPlasticitySynHandler()
GraupnerBrunel2012CaPlasticitySynHandler::GraupnerBrunel2012CaPlasticitySynHandler ()
Definition at line 238 of file GraupnerBrunel2012CaPlasticitySynHandler.cpp.
{
    Ca_          = 0.0;
    CaInit_      = 0.0;
    tauCa_       = 1.0;
    tauSyn_      = 1.0;
    CaPre_       = 0.0;
    CaPost_      = 0.0;
    thetaD_      = 0.0;
    thetaP_      = 0.0;
    gammaD_      = 0.0;
    gammaP_      = 0.0;
    delayD_      = 0.0;
    weightMin_   = 0.0;
    weightMax_   = 0.0;
    weightScale_ = 1.0;
    noisy_       = false;
    noiseSD_     = 0.0;
    bistable_    = true;
    seed_        = 0;
    dist_ = moose::MOOSE_NORMAL_DISTRIBUTION<double>{0, 1};
    reinitSeed();
    // std::cout << " Mean " << dist_.mean() << " std " << dist_.stddev() << std::endl;
}
References bistable_, Ca_, CaInit_, CaPost_, CaPre_, delayD_, dist_, gammaD_, gammaP_, noiseSD_, noisy_, moose::normal_distribution< T >::normal_distribution(), reinitSeed(), seed_, tauCa_, tauSyn_, thetaD_, thetaP_, weightMax_, weightMin_, and weightScale_.
~GraupnerBrunel2012CaPlasticitySynHandler()
GraupnerBrunel2012CaPlasticitySynHandler::~GraupnerBrunel2012CaPlasticitySynHandler ()
Definition at line 264 of file GraupnerBrunel2012CaPlasticitySynHandler.cpp.
{
}
Member Function Documentation
addPostSpike()
void GraupnerBrunel2012CaPlasticitySynHandler::addPostSpike (const Eref & e, double time)
Definition at line 339 of file GraupnerBrunel2012CaPlasticitySynHandler.cpp.
{
    postEvents_.push( PostSynEvent( time ) );
}
References postEvents_, and PostSynEvent::PostSynEvent().
Referenced by initCinfo().
addSpike()
void GraupnerBrunel2012CaPlasticitySynHandler::addSpike (unsigned int index, double time, double weight) virtual
Record arrival of a new spike event. The 'time' is time for eventual arrival of the spike, and is typically well in the future. The index specifies which synapse the spike came to.
Implements SynHandlerBase.
Definition at line 322 of file GraupnerBrunel2012CaPlasticitySynHandler.cpp.
{
    assert( index < synapses_.size() );
    events_.push( PreSynEvent( index, time, weight ) );
    delayDPreEvents_.push( PreSynEvent( index, time+delayD_, weight ) );
}
References delayD_, delayDPreEvents_, events_, PreSynEvent::PreSynEvent(), and synapses_.
addSynapse()
unsigned int GraupnerBrunel2012CaPlasticitySynHandler::addSynapse () virtual
Adds a new synapse, returns its index.
Implements SynHandlerBase.
Definition at line 604 of file GraupnerBrunel2012CaPlasticitySynHandler.cpp.
{
    unsigned int newSynIndex = synapses_.size();
    synapses_.resize( newSynIndex + 1 );
    synapses_[newSynIndex].setHandler( this );
    return newSynIndex;
}
References Synapse::setHandler(), and synapses_.
dropSynapse()
void GraupnerBrunel2012CaPlasticitySynHandler::dropSynapse (unsigned int droppedSynNumber) virtual
Drops an existing synapse, triggered by deleteMsg of an input to the child synapse. This is a little messy because we can't change the indices of the other synapses. The Handler has to figure out how to handle the 'holes' in its array of synapses.
Implements SynHandlerBase.
Definition at line 613 of file GraupnerBrunel2012CaPlasticitySynHandler.cpp.
{
    assert( msgLookup < synapses_.size() );
    synapses_[msgLookup].setWeight( -1.0 );
}
References Synapse::setWeight(), and synapses_.
getBistable()
bool GraupnerBrunel2012CaPlasticitySynHandler::getBistable () const
Definition at line 756 of file GraupnerBrunel2012CaPlasticitySynHandler.cpp.
{
    return bistable_;
}
References bistable_.
Referenced by initCinfo().
getCa()
double GraupnerBrunel2012CaPlasticitySynHandler::getCa () const
Definition at line 624 of file GraupnerBrunel2012CaPlasticitySynHandler.cpp.
{
    return Ca_;
}
References Ca_.
Referenced by initCinfo().
getCaInit()
double GraupnerBrunel2012CaPlasticitySynHandler::getCaInit () const
Definition at line 634 of file GraupnerBrunel2012CaPlasticitySynHandler.cpp.
{
    return CaInit_;
}
References CaInit_.
Referenced by initCinfo().
getCaPost()
double GraupnerBrunel2012CaPlasticitySynHandler::getCaPost () const
Definition at line 654 of file GraupnerBrunel2012CaPlasticitySynHandler.cpp.
{
    return CaPost_;
}
References CaPost_.
Referenced by initCinfo().
getCaPre()
double GraupnerBrunel2012CaPlasticitySynHandler::getCaPre () const
Definition at line 644 of file GraupnerBrunel2012CaPlasticitySynHandler.cpp.
{
    return CaPre_;
}
References CaPre_.
Referenced by initCinfo().
getDelayD()
double GraupnerBrunel2012CaPlasticitySynHandler::getDelayD () const
Definition at line 704 of file GraupnerBrunel2012CaPlasticitySynHandler.cpp.
{
    return delayD_;
}
References delayD_.
Referenced by initCinfo().
getGammaD()
double GraupnerBrunel2012CaPlasticitySynHandler::getGammaD () const
Definition at line 684 of file GraupnerBrunel2012CaPlasticitySynHandler.cpp.
{
    return gammaD_;
}
References gammaD_.
Referenced by initCinfo().
getGammaP()
double GraupnerBrunel2012CaPlasticitySynHandler::getGammaP () const
Definition at line 694 of file GraupnerBrunel2012CaPlasticitySynHandler.cpp.
{
    return gammaP_;
}
References gammaP_.
Referenced by initCinfo().
getNoiseSD()
double GraupnerBrunel2012CaPlasticitySynHandler::getNoiseSD () const
Definition at line 746 of file GraupnerBrunel2012CaPlasticitySynHandler.cpp.
{
    return noiseSD_;
}
References noiseSD_.
Referenced by initCinfo().
getNoisy()
bool GraupnerBrunel2012CaPlasticitySynHandler::getNoisy () const
Definition at line 736 of file GraupnerBrunel2012CaPlasticitySynHandler.cpp.
{
    return noisy_;
}
References noisy_.
Referenced by initCinfo().
getTauCa()
double GraupnerBrunel2012CaPlasticitySynHandler::getTauCa () const
Definition at line 715 of file GraupnerBrunel2012CaPlasticitySynHandler.cpp.
{
    return tauCa_;
}
References tauCa_.
Referenced by initCinfo().
getTauSyn()
double GraupnerBrunel2012CaPlasticitySynHandler::getTauSyn () const
Definition at line 726 of file GraupnerBrunel2012CaPlasticitySynHandler.cpp.
{
    return tauSyn_;
}
References tauSyn_.
Referenced by initCinfo().
getThetaD()
double GraupnerBrunel2012CaPlasticitySynHandler::getThetaD () const
Definition at line 674 of file GraupnerBrunel2012CaPlasticitySynHandler.cpp.
{
    return thetaD_;
}
References thetaD_.
Referenced by initCinfo().
getThetaP()
double GraupnerBrunel2012CaPlasticitySynHandler::getThetaP () const
Definition at line 664 of file GraupnerBrunel2012CaPlasticitySynHandler.cpp.
{
    return thetaP_;
}
References thetaP_.
Referenced by initCinfo().
getTopSpike()
double GraupnerBrunel2012CaPlasticitySynHandler::getTopSpike (unsigned int index) const virtual
Implements SynHandlerBase.
Definition at line 330 of file GraupnerBrunel2012CaPlasticitySynHandler.cpp.
{
    if ( events_.empty() )
        return 0.0;
    return events_.top().time;
}
References events_, and SynEvent::time.
getWeightMax()
double GraupnerBrunel2012CaPlasticitySynHandler::getWeightMax () const
Definition at line 766 of file GraupnerBrunel2012CaPlasticitySynHandler.cpp.
{
    return weightMax_;
}
References weightMax_.
Referenced by initCinfo().
getWeightMin()
double GraupnerBrunel2012CaPlasticitySynHandler::getWeightMin () const
Definition at line 776 of file GraupnerBrunel2012CaPlasticitySynHandler.cpp.
{
    return weightMin_;
}
References weightMin_.
Referenced by initCinfo().
getWeightScale()
double GraupnerBrunel2012CaPlasticitySynHandler::getWeightScale () const
Definition at line 786 of file GraupnerBrunel2012CaPlasticitySynHandler.cpp.
{
    return weightScale_;
}
References weightScale_.
Referenced by initCinfo().
initCinfo()
const Cinfo * GraupnerBrunel2012CaPlasticitySynHandler::initCinfo () static
Definition at line 21 of file GraupnerBrunel2012CaPlasticitySynHandler.cpp.
{
    static string doc[] =
    {
        "Name", "GraupnerBrunel2012CaPlasticitySynHandler",
        "Author", "Aditya Gilra",
        "Description",
        "The GraupnerBrunel2012CaPlasticitySynHandler handles synapses"
        "with Ca-based plasticity as per Higgins et al. 2014 and Graupner and Brunel 2012."
        "Note 1:"
        "   Here, Ca ('chemical Ca') is updated only at each pre-spike, pre-spike+delayD and post-spike!"
        "   So it is inaccurate to use it for say Ca-dependent K channels in the electrical compartment,"
        "   for which you use are advised to use the CaPool i.e. 'electrical Ca'."
        "Note 2:"
        "   Ca here is post-synaptic 'chemical Ca' common for all synapses in this SynHandler,"
        "   so weights of all pre-synapses connected to this SynHandler get updated"
        "   at each pre-spike, pre-spike+delayD and post-spike!"
        "   So if all pre-synaptic weights start out the same, they remain the same!!"
        "   If you want to consider each pre-synapse independently,"
        "   have independent SynHandlers for each synapse."
        "   If these SynHandlers are in the same electrical compartment,"
        "   you're essentially assuming these are on different spines,"
        "   with their own 'chemical Ca' which won't match the"
        "   'electrical Ca' of the compartment (=dendrite)."
        "   If you put each SynHandler with a single synapse"
        "   in its own electrical compartment (=spine),"
        "   only then can you have an 'electrical Ca'"
        "   corresponding to the 'chemical Ca'."
        "Three priority queues are used to manage pre, post, and pre+delayD spikes."
    };
    static ValueFinfo< GraupnerBrunel2012CaPlasticitySynHandler, double > Ca(
        "Ca",
        "Ca is a post-synaptic decaying variable as a proxy for Ca concentration"
        "and receives an impulse whenever a pre- or post- spike occurs."
        "Caution: Ca is updated via an event-based rule, so it is only updated and valid"
        "when a pre- or post- spike has occured, or at time delayD after a pre-spike."
        "Do not use it to control a Ca dependent current, etc."
        "See notes in the class Description: all pre-synapses get updated via the same post-synaptic Ca.",
        &GraupnerBrunel2012CaPlasticitySynHandler::setCa,
        &GraupnerBrunel2012CaPlasticitySynHandler::getCa
    );
    static ValueFinfo< GraupnerBrunel2012CaPlasticitySynHandler, double > CaInit(
        "CaInit",
        "CaInit is the initial value for Ca",
        &GraupnerBrunel2012CaPlasticitySynHandler::setCaInit,
        &GraupnerBrunel2012CaPlasticitySynHandler::getCaInit
    );
    static ValueFinfo< GraupnerBrunel2012CaPlasticitySynHandler, double > tauCa(
        "tauCa",
        "tauCa is the time constant for decay of Ca",
        &GraupnerBrunel2012CaPlasticitySynHandler::setTauCa,
        &GraupnerBrunel2012CaPlasticitySynHandler::getTauCa
    );
    static ValueFinfo< GraupnerBrunel2012CaPlasticitySynHandler, double > tauSyn(
        "tauSyn",
        "tauSyn is the time constant for synaptic weight evolution equation",
        &GraupnerBrunel2012CaPlasticitySynHandler::setTauSyn,
        &GraupnerBrunel2012CaPlasticitySynHandler::getTauSyn
    );
    static ValueFinfo< GraupnerBrunel2012CaPlasticitySynHandler, double > CaPre(
        "CaPre",
        "CaPre is added to Ca on every pre-spike",
        &GraupnerBrunel2012CaPlasticitySynHandler::setCaPre,
        &GraupnerBrunel2012CaPlasticitySynHandler::getCaPre
    );
    static ValueFinfo< GraupnerBrunel2012CaPlasticitySynHandler, double > CaPost(
        "CaPost",
        "CaPost is added to Ca on every post-spike",
        &GraupnerBrunel2012CaPlasticitySynHandler::setCaPost,
        &GraupnerBrunel2012CaPlasticitySynHandler::getCaPost
    );
    static ValueFinfo< GraupnerBrunel2012CaPlasticitySynHandler, double > delayD(
        "delayD",
        "Time delay D after pre-spike, when Ca is increased by Capre."
        " delayD represents NMDA rise time.",
        &GraupnerBrunel2012CaPlasticitySynHandler::setDelayD,
        &GraupnerBrunel2012CaPlasticitySynHandler::getDelayD
    );
    static ValueFinfo< GraupnerBrunel2012CaPlasticitySynHandler, double > gammaP(
        "gammaP",
        "gammaP is the potentiation factor for synaptic weight increase if Ca>thetaP",
        &GraupnerBrunel2012CaPlasticitySynHandler::setGammaP,
        &GraupnerBrunel2012CaPlasticitySynHandler::getGammaP
    );
    static ValueFinfo< GraupnerBrunel2012CaPlasticitySynHandler, double > gammaD(
        "gammaD",
        "gammaD is the depression factor for synaptic weight decrease if Ca>thetaD",
        &GraupnerBrunel2012CaPlasticitySynHandler::setGammaD,
        &GraupnerBrunel2012CaPlasticitySynHandler::getGammaD
    );
    static ValueFinfo< GraupnerBrunel2012CaPlasticitySynHandler, double > thetaP(
        "thetaP",
        "Potentiation threshold for Ca"
        "User must ensure thetaP>thetaD, else simulation results will be wrong.",
        &GraupnerBrunel2012CaPlasticitySynHandler::setThetaP,
        &GraupnerBrunel2012CaPlasticitySynHandler::getThetaP
    );
    static ValueFinfo< GraupnerBrunel2012CaPlasticitySynHandler, double > thetaD(
        "thetaD",
        "Depression threshold for Ca"
        "User must ensure thetaP>thetaD, else simulation results will be wrong.",
        &GraupnerBrunel2012CaPlasticitySynHandler::setThetaD,
        &GraupnerBrunel2012CaPlasticitySynHandler::getThetaD
    );
    static ValueFinfo< GraupnerBrunel2012CaPlasticitySynHandler, bool > bistable(
        "bistable",
        "If true, the synapse is bistable as in GraupnerBrunel2012 paper."
        "The effect of potential on the weight update is usually ignorable"
        " if Ca is above thetaP and thetaD most of the time.",
        &GraupnerBrunel2012CaPlasticitySynHandler::setBistable,
        &GraupnerBrunel2012CaPlasticitySynHandler::getBistable
    );
    static ValueFinfo< GraupnerBrunel2012CaPlasticitySynHandler, bool > noisy(
        "noisy",
        "If true, turn noise on as per noiseSD",
        &GraupnerBrunel2012CaPlasticitySynHandler::setNoisy,
        &GraupnerBrunel2012CaPlasticitySynHandler::getNoisy
    );
    static ValueFinfo< GraupnerBrunel2012CaPlasticitySynHandler, double > noiseSD(
        "noiseSD",
        "Standard deviation of noise added to Ca",
        &GraupnerBrunel2012CaPlasticitySynHandler::setNoiseSD,
        &GraupnerBrunel2012CaPlasticitySynHandler::getNoiseSD
    );
    static ValueFinfo< GraupnerBrunel2012CaPlasticitySynHandler, double > weightMax(
        "weightMax",
        "An upper bound on the weight",
        &GraupnerBrunel2012CaPlasticitySynHandler::setWeightMax,
        &GraupnerBrunel2012CaPlasticitySynHandler::getWeightMax
    );
    static ValueFinfo< GraupnerBrunel2012CaPlasticitySynHandler, double > weightMin(
        "weightMin",
        "A lower bound on the weight",
        &GraupnerBrunel2012CaPlasticitySynHandler::setWeightMin,
        &GraupnerBrunel2012CaPlasticitySynHandler::getWeightMin
    );
    static ValueFinfo< GraupnerBrunel2012CaPlasticitySynHandler, double > weightScale(
        "weightScale",
        "Scale all pre-synaptic weights by weightScale before adding to activation (default 1.0)"
        "In the terminology of the paper Higgins et al 2012, weight is synaptic efficacy,"
        "while weightScale*weight is what finally is added to activation variable.",
        &GraupnerBrunel2012CaPlasticitySynHandler::setWeightScale,
        &GraupnerBrunel2012CaPlasticitySynHandler::getWeightScale
    );
    static DestFinfo addPostSpike(
        "addPostSpike",
        "Handles arriving spike messages from post-synaptic neuron, inserts into postEvent queue.",
        new EpFunc1< GraupnerBrunel2012CaPlasticitySynHandler, \
        double >( &GraupnerBrunel2012CaPlasticitySynHandler::addPostSpike ) );
    static FieldElementFinfo< SynHandlerBase, Synapse > synFinfo(
        "synapse",
        "Sets up field Elements for synapse",
        Synapse::initCinfo(),
        &SynHandlerBase::getSynapse,
        &SynHandlerBase::setNumSynapses,
        &SynHandlerBase::getNumSynapses
    );
    static Finfo* GraupnerBrunel2012CaPlasticitySynHandlerFinfos[] =
    {
        &synFinfo,     // FieldElement
        &addPostSpike, // DestFinfo
        &Ca,           // Field
        &CaInit,       // Field
        &tauCa,        // Field
        &tauSyn,       // Field
        &CaPre,        // Field
        &CaPost,       // Field
        &delayD,       // Field
        &thetaP,       // Field
        &thetaD,       // Field
        &gammaP,       // Field
        &gammaD,       // Field
        &weightMax,    // Field
        &weightMin,    // Field
        &weightScale,  // Field
        &noisy,        // Field
        &noiseSD,      // Field
        &bistable      // Field
    };
    static Dinfo< GraupnerBrunel2012CaPlasticitySynHandler > dinfo;
    static Cinfo synHandlerCinfo (
        "GraupnerBrunel2012CaPlasticitySynHandler",
        SynHandlerBase::initCinfo(),
        GraupnerBrunel2012CaPlasticitySynHandlerFinfos,
        sizeof( GraupnerBrunel2012CaPlasticitySynHandlerFinfos ) / sizeof ( Finfo* ),
        &dinfo,
        doc,
        sizeof( doc ) / sizeof( string )
    );
    return &synHandlerCinfo;
}
References addPostSpike(), Cinfo::Cinfo(), DestFinfo::DestFinfo(), EpFunc1< T, A >::EpFunc1(), FieldElementFinfo< T, F >::FieldElementFinfo(), getBistable(), getCa(), getCaInit(), getCaPost(), getCaPre(), getDelayD(), getGammaD(), getGammaP(), getNoiseSD(), getNoisy(), SynHandlerBase::getNumSynapses(), SynHandlerBase::getSynapse(), getTauCa(), getTauSyn(), getThetaD(), getThetaP(), getWeightMax(), getWeightMin(), getWeightScale(), Synapse::initCinfo(), SynHandlerBase::initCinfo(), setBistable(), setCa(), setCaInit(), setCaPost(), setCaPre(), setDelayD(), setGammaD(), setGammaP(), setNoiseSD(), setNoisy(), SynHandlerBase::setNumSynapses(), setTauCa(), setTauSyn(), setThetaD(), setThetaP(), setWeightMax(), setWeightMin(), setWeightScale(), and ValueFinfo< T, F >::ValueFinfo().
operator=()
GraupnerBrunel2012CaPlasticitySynHandler & GraupnerBrunel2012CaPlasticitySynHandler::operator= (const GraupnerBrunel2012CaPlasticitySynHandler & other)
Definition at line 279 of file GraupnerBrunel2012CaPlasticitySynHandler.cpp.
{
    synapses_ = ssh.synapses_;
    for ( vector< Synapse >::iterator
            i = synapses_.begin(); i != synapses_.end(); ++i )
        i->setHandler( this );
    // For no apparent reason, priority queues don't have a clear operation.
    while( !events_.empty() )
        events_.pop();
    while( !delayDPreEvents_.empty() )
        events_.pop();
    while( !postEvents_.empty() )
        postEvents_.pop();
    return *this;
}
References delayDPreEvents_, events_, postEvents_, Synapse::setHandler(), and synapses_.
reinitSeed()
void GraupnerBrunel2012CaPlasticitySynHandler::reinitSeed (void)
Definition at line 268 of file GraupnerBrunel2012CaPlasticitySynHandler.cpp.
{
    if( 0 == seed_ )
        seed_ = moose::getGlobalSeed();
    if( 0 == seed_ )
        seed_ = rd_();
    rng_.seed( seed_ );
}
References moose::getGlobalSeed(), rd_, rng_, and seed_.
Referenced by GraupnerBrunel2012CaPlasticitySynHandler().
setBistable()
void GraupnerBrunel2012CaPlasticitySynHandler::setBistable (bool v)
Definition at line 751 of file GraupnerBrunel2012CaPlasticitySynHandler.cpp.
{
    bistable_ = v;
}
References bistable_.
Referenced by initCinfo().
setCa()
void GraupnerBrunel2012CaPlasticitySynHandler::setCa (double v)
Definition at line 619 of file GraupnerBrunel2012CaPlasticitySynHandler.cpp.
{
    Ca_ = v;
}
References Ca_.
Referenced by initCinfo().
setCaInit()
void GraupnerBrunel2012CaPlasticitySynHandler::setCaInit (double v)
Definition at line 629 of file GraupnerBrunel2012CaPlasticitySynHandler.cpp.
{
    CaInit_ = v;
}
References CaInit_.
Referenced by initCinfo().
setCaPost()
void GraupnerBrunel2012CaPlasticitySynHandler::setCaPost (double v)
Definition at line 649 of file GraupnerBrunel2012CaPlasticitySynHandler.cpp.
{
    CaPost_ = v;
}
References CaPost_.
Referenced by initCinfo().
setCaPre()
void GraupnerBrunel2012CaPlasticitySynHandler::setCaPre (double v)
Definition at line 639 of file GraupnerBrunel2012CaPlasticitySynHandler.cpp.
{
    CaPre_ = v;
}
References CaPre_.
Referenced by initCinfo().
setDelayD()
void GraupnerBrunel2012CaPlasticitySynHandler::setDelayD (double v)
Definition at line 699 of file GraupnerBrunel2012CaPlasticitySynHandler.cpp.
{
    delayD_ = v;
}
References delayD_.
Referenced by initCinfo().
setGammaD()
void GraupnerBrunel2012CaPlasticitySynHandler::setGammaD (double v)
Definition at line 679 of file GraupnerBrunel2012CaPlasticitySynHandler.cpp.
{
    gammaD_ = v;
}
References gammaD_.
Referenced by initCinfo().
setGammaP()
void GraupnerBrunel2012CaPlasticitySynHandler::setGammaP (double v)
Definition at line 689 of file GraupnerBrunel2012CaPlasticitySynHandler.cpp.
{
    gammaP_ = v;
}
References gammaP_.
Referenced by initCinfo().
setNoiseSD()
void GraupnerBrunel2012CaPlasticitySynHandler::setNoiseSD (double v)
Definition at line 741 of file GraupnerBrunel2012CaPlasticitySynHandler.cpp.
{
    noiseSD_ = v;
}
References noiseSD_.
Referenced by initCinfo().
setNoisy()
void GraupnerBrunel2012CaPlasticitySynHandler::setNoisy (bool v)
Definition at line 731 of file GraupnerBrunel2012CaPlasticitySynHandler.cpp.
{
    noisy_ = v;
}
References noisy_.
Referenced by initCinfo().
setTauCa()
void GraupnerBrunel2012CaPlasticitySynHandler::setTauCa (double v)
Definition at line 709 of file GraupnerBrunel2012CaPlasticitySynHandler.cpp.
{
    if ( rangeWarning( "tauCa", v ) ) return;
    tauCa_ = v;
}
References SynHandlerBase::rangeWarning(), and tauCa_.
Referenced by initCinfo().
setTauSyn()
void GraupnerBrunel2012CaPlasticitySynHandler::setTauSyn (double v)
Definition at line 720 of file GraupnerBrunel2012CaPlasticitySynHandler.cpp.
{
    if ( rangeWarning( "tauSyn", v ) ) return;
    tauSyn_ = v;
}
References SynHandlerBase::rangeWarning(), and tauSyn_.
Referenced by initCinfo().
setThetaD()
void GraupnerBrunel2012CaPlasticitySynHandler::setThetaD (double v)
Definition at line 669 of file GraupnerBrunel2012CaPlasticitySynHandler.cpp.
{
    thetaD_ = v;
}
References thetaD_.
Referenced by initCinfo().
setThetaP()
void GraupnerBrunel2012CaPlasticitySynHandler::setThetaP (double v)
Definition at line 659 of file GraupnerBrunel2012CaPlasticitySynHandler.cpp.
{
    thetaP_ = v;
}
References thetaP_.
Referenced by initCinfo().
setWeightMax()
void GraupnerBrunel2012CaPlasticitySynHandler::setWeightMax (double v)
Definition at line 761 of file GraupnerBrunel2012CaPlasticitySynHandler.cpp.
{
    weightMax_ = v;
}
References weightMax_.
Referenced by initCinfo().
setWeightMin()
void GraupnerBrunel2012CaPlasticitySynHandler::setWeightMin (double v)
Definition at line 771 of file GraupnerBrunel2012CaPlasticitySynHandler.cpp.
{
    weightMin_ = v;
}
References weightMin_.
Referenced by initCinfo().
setWeightScale()
void GraupnerBrunel2012CaPlasticitySynHandler::setWeightScale (double v)
Definition at line 781 of file GraupnerBrunel2012CaPlasticitySynHandler.cpp.
{
    weightScale_ = v;
}
References weightScale_.
Referenced by initCinfo().
updateCaWeightFactors()
weightFactors GraupnerBrunel2012CaPlasticitySynHandler::updateCaWeightFactors (double currTime)
Definition at line 344 of file GraupnerBrunel2012CaPlasticitySynHandler.cpp.
{
    double CaOld = Ca_;
    double deltaT = currTime-lastCaUpdateTime_;
    // Update Ca, but CaPre and CaPost are added in vProcess()
    Ca_ *= exp(-deltaT/tauCa_);
    lastCaUpdateTime_ = currTime;
    weightFactors wUp; // by default all are set to 0.0
    // calculate/approximate time spent above potentiation and depression thresholds
    // see pg 13 of Higgins et al | October 2014 | Volume 10 | Issue 10 | e1003834 | PLOS Comp Biol
    // starting from bottom condition, going upwards in the algorithm given in above paper
    if (CaOld <= thetaD_)
    {
    }
    else if (CaOld <= thetaP_)
    {
        //cout << "tD<Caold<tP" << "\n";
        if (Ca_ <= thetaD_)
        {
            wUp.tD = tauCa_*log(CaOld/thetaD_);
            //cout << "Ca<tD" << "\n";
        }
        else
        {
            wUp.tD = deltaT;
            //cout << "Ca>tD" << "\n";
        }
    }
    else
    {
        //cout << "Caold>tP" << "\n";
        if (Ca_ <= thetaD_)
        {
            wUp.tP = tauCa_*log(CaOld/thetaP_);
            wUp.tD = tauCa_*log(thetaP_/thetaD_);
            //cout << "Ca<tD" << "\n";
            //cout << "Caold = " << CaOld << "thetaP = " << thetaP_ << "\n";
        }
        else if (Ca_ <= thetaP_)
        {
            wUp.tP = tauCa_*log(CaOld/thetaP_);
            wUp.tD = deltaT - wUp.tP;
            //cout << "Ca<tP" << "\n";
        }
        else
        {
            wUp.tP = deltaT;
            //cout << "Ca>tP" << "\n";
        }
    }
    wUp.t0 = deltaT - wUp.tP - wUp.tD;
    // Depending on tP and tD, I return A,B,C factors for weight update
    // (see page 13 of Higgins et al 2014).
    // A,B,C,D,E are used to compute the weight change for one or multiple synapses
    // A is weight independent, B,D are weight dependent and C,E are accumulated noise
    if (wUp.tP > 0)
    {
        double gPgD = gammaP_+gammaD_;
        wUp.A = gammaP_/gPgD*(1.0-exp(-wUp.tP*gPgD/tauSyn_));
        wUp.B = exp(-wUp.tP*gPgD/tauSyn_);
        if (noisy_)
        {
            wUp.C = noiseSD_ * dist_(rng_) *
                    sqrt( ( 1.0-exp(-2*gPgD*wUp.tP/tauSyn_) ) / gPgD );
            // cout << " A = " << wUp.A << " B = " << wUp.B << " C = " << wUp.C << "\n";
        }
        else
        {
            wUp.C = 0.0;
        }
    }
    if (wUp.tD > 0)
    {
        wUp.D = exp(-wUp.tD*gammaD_/tauSyn_);
        if (noisy_)
        {
            wUp.E = noiseSD_ * dist_( rng_ ) *
                    sqrt( ( 1.0-exp(-2*gammaD_*wUp.tD/tauSyn_) ) / 2.0/gammaD_ );
            //cout << "D = " << wUp.D << " E = " << wUp.E << "\n";
        }
        else
        {
            wUp.E = 0.0;
        }
    }
    //cout << currTime  << " tD = " << wUp.tD << " tP = " << wUp.tP << "\n";
    // tP, tD, A, B, C, D, E of wUp
    // are set to 0.0 by default in struct constructor
    return wUp;     // return by value, i.e. copies the struct, so wUp going out of scope doesn't matter
    // malloc and returning pointer is more expensive for small structs
    // see: http://stackoverflow.com/questions/9590827/is-it-safe-to-return-a-struct-in-c-c
}
References weightFactors::A, weightFactors::B, weightFactors::C, Ca_, weightFactors::D, dist_, weightFactors::E, gammaD_, gammaP_, lastCaUpdateTime_, noiseSD_, noisy_, moose::normal_distribution< T >::operator()(), rng_, weightFactors::t0, tauCa_, tauSyn_, weightFactors::tD, thetaD_, thetaP_, and weightFactors::tP.
Referenced by vProcess().
updateWeight()
void GraupnerBrunel2012CaPlasticitySynHandler::updateWeight (Synapse * synPtr, weightFactors * wFacPtr)
Definition at line 441 of file GraupnerBrunel2012CaPlasticitySynHandler.cpp.
{
    double newWeight = synPtr->getWeight();
    //cout << " oldweight = " << newWeight << "\n";
    if (wFacPtr->tP > 0.0)
    {
        newWeight = wFacPtr->A + wFacPtr->B*newWeight + wFacPtr->C;
        //cout << " midweight = " << newWeight << "\n";
    }
    if (wFacPtr->tD > 0.0)
    {
        newWeight = wFacPtr->D*newWeight + wFacPtr->E; // update the weight again
        //cout << " newweight = " << newWeight << "\n";
    }
    // potential is usually ignorable when t0 is small,
    // i.e. Ca is mostly above thetaD or thetaP
    //cout << "before bistable newWeight = " << newWeight << "\n";
    if (bistable_)
    {
        double chi0 = pow((newWeight-0.5),2.0) / (newWeight*(newWeight-1));
        double weightDeviation = 0.5*sqrt( 1.0 + 1.0/(chi0*exp(wFacPtr->t0/2.0/tauSyn_)-1.0) );
        if (newWeight<0.5)
        {
            newWeight = 0.5 - weightDeviation;
        }
        else
        {
            newWeight = 0.5 + weightDeviation;
        }
    }
    //cout << "after bistable newWeight = " << newWeight << "\n";
    // clip weight within [weightMin,weightMax]
    newWeight = std::max(weightMin_, std::min(newWeight, weightMax_));
    //cout << " clipweight = " << newWeight << "\n";
    //cout << " A = " << wFacPtr->A << " B = " << wFacPtr->B << " C = " << wFacPtr->C
    //    << " D = " << wFacPtr->D << " E = " << wFacPtr->E << " newW = "<< newWeight << "\n";
    synPtr->setWeight( newWeight );
}
References weightFactors::A, weightFactors::B, bistable_, weightFactors::C, weightFactors::D, weightFactors::E, Synapse::getWeight(), Synapse::setWeight(), weightFactors::t0, tauSyn_, weightFactors::tD, weightFactors::tP, weightMax_, and weightMin_.
Referenced by vProcess().
vGetNumSynapses()
unsigned int GraupnerBrunel2012CaPlasticitySynHandler::vGetNumSynapses () const virtual
Implements SynHandlerBase.
Definition at line 307 of file GraupnerBrunel2012CaPlasticitySynHandler.cpp.
{
    return synapses_.size();
}
References synapses_.
vGetSynapse()
Synapse * GraupnerBrunel2012CaPlasticitySynHandler::vGetSynapse (unsigned int i) virtual
Implements SynHandlerBase.
Definition at line 312 of file GraupnerBrunel2012CaPlasticitySynHandler.cpp.
{
    static Synapse dummy;
    if ( i < synapses_.size() )
        return &synapses_[i];
    cout << "Warning: GraupnerBrunel2012CaPlasticitySynHandler::getSynapse: index: " << i <<
         " is out of range: " << synapses_.size() << endl;
    return &dummy;
}
References synapses_.
vProcess()
void GraupnerBrunel2012CaPlasticitySynHandler::vProcess (const Eref & e, ProcPtr p) virtual
Implements SynHandlerBase.
Definition at line 482 of file GraupnerBrunel2012CaPlasticitySynHandler.cpp.
{
    double activation = 0.0;
    double currTime = p->currTime;
    bool CaFactorsUpdated = false; // Ca-decay and weight Factors updation is done only once
    // if any pre-spike, pre-spike+delayD or post-spike occurs
    // Ca is bumped by CaPre and CaPost on
    // pre-spike+delayD and post-spike respectively
    // At the end, if any event above occurred,
    // change all pre-synaptic weights based on Ca
    weightFactors wFacs;
    // process pre-synaptic spike events for activation, Ca and weight update
    while( !events_.empty() && events_.top().time <= currTime )
    {
        PreSynEvent currEvent = events_.top();
        unsigned int synIndex = currEvent.synIndex;
        // Warning, coder! 'STDPSynapse currSyn = synapses_[synIndex];' is wrong,
        // it creates a new, shallow-copied object.
        // We want only to point to the same object.
        Synapse* currSynPtr = &synapses_[synIndex];
        // activate the synapse for every pre-spike
        // If the synapse has a delay, the weight could be updated during the delay!
        // currEvent.weight is the weight before the delay!
        // Might be better to use currSynPtr->getWeight()
        //      or even the latest updated weight below?!
        // Using currSynPtr->getWeight().
        // Still, weight update is event driven and not continuous
        //      so using currSynPtr->getWeight() takes care of
        //      weight updates due to events/spikes during the delay
        //      but doesn't take care of continuous weight evolution during the delay.
        // The weight update is done
        //          after sending the current weight to activation
        // Maybe I should use the updated weight to send to activation?!
        // See: http://www.genesis-sim.org/GENESIS/Hyperdoc/Manual-26.html#synchan
        // Send out weight / dt for every spike
        //      Since it is an impulse active only for one dt,
        //      need to send it divided by dt.
        // Can connect activation to SynChan (double exp)
        //      or to LIF as an impulse to voltage.
        //activation += currEvent.weight * weightScale_ / p->dt;
        activation += currSynPtr->getWeight() * weightScale_ / p->dt;
        // update only once for this time-step if an event occurs
        if (!CaFactorsUpdated)
        {
            // update Ca and weightFactors
            wFacs = updateCaWeightFactors( currTime );
            CaFactorsUpdated = true;
        }
        events_.pop();
    }
    if ( activation != 0.0 )
        SynHandlerBase::activationOut()->send( e, activation );
    // process delayed pre-synaptic spike events for Ca and weight update
    // delayD after pre-spike accounts for NMDA rise time
    while( !delayDPreEvents_.empty() && delayDPreEvents_.top().time <= currTime )
    {
        // Update Ca, and add CaPre
        // update only once for this time-step if an event occurs
        if (!CaFactorsUpdated)
        {
            // update Ca and weightFactors
            wFacs = updateCaWeightFactors( currTime );
            CaFactorsUpdated = true;
        }
        Ca_ += CaPre_;
        delayDPreEvents_.pop();
    }
    // process post-synaptic spike events for Ca and weight update
    while( !postEvents_.empty() && postEvents_.top().time <= currTime )
    {
        // update Ca, then add CaPost
        // update only once for this time-step if an event occurs
        if (!CaFactorsUpdated)
        {
            // update Ca and weightFactors
            wFacs = updateCaWeightFactors( currTime );
            CaFactorsUpdated = true;
        }
        Ca_ += CaPost_;
        postEvents_.pop();
    }
    // If any event has happened, update all pre-synaptic weights
    // If you want individual Ca for each pre-synapse
    // create individual SynHandlers for each
    if (CaFactorsUpdated)
    {
        // Change weight of all synapses
        for (unsigned int i=0; i<synapses_.size(); i++)
        {
            // Warning, coder! 'Synapse currSyn = synapses_[i];' is wrong,
            // it creates a new, shallow-copied object.
            // We want only to point to the same object.
            Synapse* currSynPtrHere = &synapses_[i];
            updateWeight(currSynPtrHere,&wFacs);
        }
    }
}
References SynHandlerBase::activationOut(), Ca_, CaPost_, CaPre_, ProcInfo::currTime, delayDPreEvents_, ProcInfo::dt, events_, Synapse::getWeight(), postEvents_, SrcFinfo1< T >::send(), synapses_, PreSynEvent::synIndex, SynEvent::time, PostSynEvent::time, updateCaWeightFactors(), updateWeight(), and weightScale_.
vReinit()
void GraupnerBrunel2012CaPlasticitySynHandler::vReinit (const Eref & e, ProcPtr p) virtual
Implements SynHandlerBase.
Definition at line 592 of file GraupnerBrunel2012CaPlasticitySynHandler.cpp.
{
    // For no apparent reason, priority queues don't have a clear operation.
    while( !events_.empty() )
        events_.pop();
    while( !delayDPreEvents_.empty() )
        events_.pop();
    while( !postEvents_.empty() )
        postEvents_.pop();
    Ca_ = CaInit_;
}
References Ca_, CaInit_, delayDPreEvents_, events_, and postEvents_.
vSetNumSynapses()
void GraupnerBrunel2012CaPlasticitySynHandler::vSetNumSynapses (unsigned int num) virtual
Implements SynHandlerBase.
Definition at line 299 of file GraupnerBrunel2012CaPlasticitySynHandler.cpp.
{
    unsigned int prevSize = synapses_.size();
    synapses_.resize( v );
    for ( unsigned int i = prevSize; i < v; ++i )
        synapses_[i].setHandler( this );
}
References Synapse::setHandler(), and synapses_.
Member Data Documentation
bistable_
bool GraupnerBrunel2012CaPlasticitySynHandler::bistable_ private
Definition at line 129 of file GraupnerBrunel2012CaPlasticitySynHandler.h.
Referenced by getBistable(), GraupnerBrunel2012CaPlasticitySynHandler(), setBistable(), and updateWeight().
Ca_
double GraupnerBrunel2012CaPlasticitySynHandler::Ca_ private
Definition at line 120 of file GraupnerBrunel2012CaPlasticitySynHandler.h.
Referenced by getCa(), GraupnerBrunel2012CaPlasticitySynHandler(), setCa(), updateCaWeightFactors(), vProcess(), and vReinit().
CaInit_
double GraupnerBrunel2012CaPlasticitySynHandler::CaInit_ private
Definition at line 121 of file GraupnerBrunel2012CaPlasticitySynHandler.h.
Referenced by getCaInit(), GraupnerBrunel2012CaPlasticitySynHandler(), setCaInit(), and vReinit().
CaPost_
double GraupnerBrunel2012CaPlasticitySynHandler::CaPost_ private
Definition at line 125 of file GraupnerBrunel2012CaPlasticitySynHandler.h.
Referenced by getCaPost(), GraupnerBrunel2012CaPlasticitySynHandler(), setCaPost(), and vProcess().
CaPre_
double GraupnerBrunel2012CaPlasticitySynHandler::CaPre_ private
Definition at line 124 of file GraupnerBrunel2012CaPlasticitySynHandler.h.
Referenced by getCaPre(), GraupnerBrunel2012CaPlasticitySynHandler(), setCaPre(), and vProcess().
delayD_
double GraupnerBrunel2012CaPlasticitySynHandler::delayD_ private
Definition at line 126 of file GraupnerBrunel2012CaPlasticitySynHandler.h.
Referenced by addSpike(), getDelayD(), GraupnerBrunel2012CaPlasticitySynHandler(), and setDelayD().
delayDPreEvents_
priority_queue< PreSynEvent, vector< PreSynEvent >, CompareSynEvent > GraupnerBrunel2012CaPlasticitySynHandler::delayDPreEvents_ private
Definition at line 117 of file GraupnerBrunel2012CaPlasticitySynHandler.h.
Referenced by addSpike(), operator=(), vProcess(), and vReinit().
dist_
moose::MOOSE_NORMAL_DISTRIBUTION<double> GraupnerBrunel2012CaPlasticitySynHandler::dist_ private
Definition at line 142 of file GraupnerBrunel2012CaPlasticitySynHandler.h.
Referenced by GraupnerBrunel2012CaPlasticitySynHandler(), and updateCaWeightFactors().
events_
priority_queue< PreSynEvent, vector< PreSynEvent >, CompareSynEvent > GraupnerBrunel2012CaPlasticitySynHandler::events_ private
Definition at line 116 of file GraupnerBrunel2012CaPlasticitySynHandler.h.
Referenced by addSpike(), getTopSpike(), operator=(), vProcess(), and vReinit().
gammaD_
double GraupnerBrunel2012CaPlasticitySynHandler::gammaD_ private
Definition at line 132 of file GraupnerBrunel2012CaPlasticitySynHandler.h.
Referenced by getGammaD(), GraupnerBrunel2012CaPlasticitySynHandler(), setGammaD(), and updateCaWeightFactors().
gammaP_
double GraupnerBrunel2012CaPlasticitySynHandler::gammaP_ private
Definition at line 133 of file GraupnerBrunel2012CaPlasticitySynHandler.h.
Referenced by getGammaP(), GraupnerBrunel2012CaPlasticitySynHandler(), setGammaP(), and updateCaWeightFactors().
lastCaUpdateTime_
double GraupnerBrunel2012CaPlasticitySynHandler::lastCaUpdateTime_ private
Definition at line 137 of file GraupnerBrunel2012CaPlasticitySynHandler.h.
Referenced by updateCaWeightFactors().
noiseSD_
double GraupnerBrunel2012CaPlasticitySynHandler::noiseSD_ private
Definition at line 128 of file GraupnerBrunel2012CaPlasticitySynHandler.h.
Referenced by getNoiseSD(), GraupnerBrunel2012CaPlasticitySynHandler(), setNoiseSD(), and updateCaWeightFactors().
noisy_
bool GraupnerBrunel2012CaPlasticitySynHandler::noisy_ private
Definition at line 127 of file GraupnerBrunel2012CaPlasticitySynHandler.h.
Referenced by getNoisy(), GraupnerBrunel2012CaPlasticitySynHandler(), setNoisy(), and updateCaWeightFactors().
postEvents_
priority_queue< PostSynEvent, vector< PostSynEvent >, ComparePostSynEvent > GraupnerBrunel2012CaPlasticitySynHandler::postEvents_ private
Definition at line 118 of file GraupnerBrunel2012CaPlasticitySynHandler.h.
Referenced by addPostSpike(), operator=(), vProcess(), and vReinit().
rd_
moose::MOOSE_RANDOM_DEVICE GraupnerBrunel2012CaPlasticitySynHandler::rd_ private
Definition at line 141 of file GraupnerBrunel2012CaPlasticitySynHandler.h.
Referenced by reinitSeed().
rng_
moose::MOOSE_RNG_DEFAULT_ENGINE GraupnerBrunel2012CaPlasticitySynHandler::rng_ private
Definition at line 143 of file GraupnerBrunel2012CaPlasticitySynHandler.h.
Referenced by reinitSeed(), and updateCaWeightFactors().
seed_
unsigned long GraupnerBrunel2012CaPlasticitySynHandler::seed_ private
Definition at line 140 of file GraupnerBrunel2012CaPlasticitySynHandler.h.
Referenced by GraupnerBrunel2012CaPlasticitySynHandler(), and reinitSeed().
synapses_
vector< Synapse > GraupnerBrunel2012CaPlasticitySynHandler::synapses_ private
Definition at line 114 of file GraupnerBrunel2012CaPlasticitySynHandler.h.
Referenced by addSpike(), addSynapse(), dropSynapse(), operator=(), vGetNumSynapses(), vGetSynapse(), vProcess(), and vSetNumSynapses().
tauCa_
double GraupnerBrunel2012CaPlasticitySynHandler::tauCa_ private
Definition at line 122 of file GraupnerBrunel2012CaPlasticitySynHandler.h.
Referenced by getTauCa(), GraupnerBrunel2012CaPlasticitySynHandler(), setTauCa(), and updateCaWeightFactors().
tauSyn_
double GraupnerBrunel2012CaPlasticitySynHandler::tauSyn_ private
Definition at line 123 of file GraupnerBrunel2012CaPlasticitySynHandler.h.
Referenced by getTauSyn(), GraupnerBrunel2012CaPlasticitySynHandler(), setTauSyn(), updateCaWeightFactors(), and updateWeight().
thetaD_
double GraupnerBrunel2012CaPlasticitySynHandler::thetaD_ private
Definition at line 130 of file GraupnerBrunel2012CaPlasticitySynHandler.h.
Referenced by getThetaD(), GraupnerBrunel2012CaPlasticitySynHandler(), setThetaD(), and updateCaWeightFactors().
thetaP_
double GraupnerBrunel2012CaPlasticitySynHandler::thetaP_ private
Definition at line 131 of file GraupnerBrunel2012CaPlasticitySynHandler.h.
Referenced by getThetaP(), GraupnerBrunel2012CaPlasticitySynHandler(), setThetaP(), and updateCaWeightFactors().
weightMax_
double GraupnerBrunel2012CaPlasticitySynHandler::weightMax_ private
Definition at line 134 of file GraupnerBrunel2012CaPlasticitySynHandler.h.
Referenced by getWeightMax(), GraupnerBrunel2012CaPlasticitySynHandler(), setWeightMax(), and updateWeight().
weightMin_
double GraupnerBrunel2012CaPlasticitySynHandler::weightMin_ private
Definition at line 135 of file GraupnerBrunel2012CaPlasticitySynHandler.h.
Referenced by getWeightMin(), GraupnerBrunel2012CaPlasticitySynHandler(), setWeightMin(), and updateWeight().
weightScale_
double GraupnerBrunel2012CaPlasticitySynHandler::weightScale_ private
Definition at line 136 of file GraupnerBrunel2012CaPlasticitySynHandler.h.
Referenced by getWeightScale(), GraupnerBrunel2012CaPlasticitySynHandler(), setWeightScale(), and vProcess().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/synapse/GraupnerBrunel2012CaPlasticitySynHandler.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/synapse/GraupnerBrunel2012CaPlasticitySynHandler.cpp