MOOSE - Multiscale Object Oriented Simulation Environment: FieldElementFinfo< T, F > Class Template Reference
FieldElementFinfo< T, F > Class Template Reference
#include <FieldElementFinfo.h>
Public Member Functions
FieldElementFinfo (const string &name, const string &doc, const Cinfo *fieldCinfo, F *(T::*lookupField)(unsigned int), void(T::*setNumField)(unsigned int num), unsigned int(T::*getNumField)() const, bool deferCreate=0)
unsigned int getNumField (const char *parent) const
virtual func to get size of Field array, using char* for parent
char * lookupField (char *parent, unsigned int fieldIndex) const
string rttiType () const
Virtual function to look up type of FieldElementFinfo.
void setNumField (char *parent, unsigned int num) const
virtual func to resize Field array, using char* for parent
Public Member Functions inherited from FieldElementFinfoBase
FieldElementFinfoBase (const string &name, const string &doc, const Cinfo *fieldCinfo, bool deferCreate)
void postCreationFunc (Id parent, Element *parentElm) const
void registerFinfo (Cinfo *c)
bool strGet (const Eref &tgt, const string &field, string &returnValue) const
bool strSet (const Eref &tgt, const string &field, const string &arg) const
virtual ~FieldElementFinfoBase ()
Public Member Functions inherited from Finfo
virtual bool addMsg (const Finfo *target, ObjId mid, Element *src) const
virtual bool checkTarget (const Finfo *target) const
const string & docs () const
Returns documentation string.
Finfo (const string &name, const string &doc)
virtual vector< string > innerDest () const
virtual vector< string > innerSrc () const
const string & name () const
virtual ~Finfo ()
Private Attributes
unsigned int(T::* getNumField_)() const
F *(T::* lookupField_)(unsigned int)
void(T::* setNumField_)(unsigned int num)
Additional Inherited Members
Static Public Member Functions inherited from Finfo
static const Cinfo * initCinfo ()
Protected Attributes inherited from FieldElementFinfoBase
bool deferCreate_
const Cinfo * fieldCinfo_
DestFinfo * getNum_
DestFinfo * setNum_
Detailed Description
template<class T, class F>
class FieldElementFinfo< T, F >
Definition at line 104 of file FieldElementFinfo.h.
Constructor & Destructor Documentation
FieldElementFinfo()
template<class T , class F > FieldElementFinfo< T, F >::FieldElementFinfo (const string & name, const string & doc, const Cinfo * fieldCinfo, F *(T::*)(unsigned int) lookupField, void(T::*)(unsigned int num) setNumField, unsigned int(T::*)() const getNumField, bool deferCreate = 0) inline
Definition at line 107 of file FieldElementFinfo.h.
        : FieldElementFinfoBase( name, doc, fieldCinfo, deferCreate ),
          lookupField_( lookupField ),
          setNumField_( setNumField ),
          getNumField_( getNumField )
    {
        string setname = "setNum" + name;
        setname[6] = std::toupper( setname[6] );
        // setNumField is a tricky operation, because it may require
        // cross-node rescaling of the
        // FieldDataHandler::fieldDimension. To acheive this we
        // wrap the setNumField in something more interesting
        // than a simple OpFunc.
        setNum_ = new DestFinfo(
            setname,
            "Assigns number of field entries in field array.",
            new OpFunc1< T, unsigned int >( setNumField ) );
        string getname = "getNum" + name;
        getname[6] = std::toupper( getname[6] );
        getNum_ = new DestFinfo(
            getname,
            "Requests number of field entries in field array."
            "The requesting Element must "
            "provide a handler for the returned value.",
            new GetOpFunc< T, unsigned int >( getNumField ) );
    }
References FieldElementFinfoBase::getNum_, FieldElementFinfo< T, F >::getNumField_, FieldElementFinfoBase::setNum_, and FieldElementFinfo< T, F >::setNumField_.
Referenced by HHChannel::initCinfo(), HHChannel2D::initCinfo(), Neuron::initCinfo(), Function::initCinfo(), ChemCompt::initCinfo(), GraupnerBrunel2012CaPlasticitySynHandler::initCinfo(), SeqSynHandler::initCinfo(), SimpleSynHandler::initCinfo(), and STDPSynHandler::initCinfo().
Member Function Documentation
getNumField()
template<class T , class F > unsigned int FieldElementFinfo< T, F >::getNumField (const char * parent) const inline virtual
virtual func to get size of Field array, using char* for parent
Implements FieldElementFinfoBase.
Definition at line 167 of file FieldElementFinfo.h.
    {
        const T* pa = reinterpret_cast< const T* >( parent );
        return ( pa->*getNumField_ )();
    }
References FieldElementFinfo< T, F >::getNumField_.
lookupField()
template<class T , class F > char * FieldElementFinfo< T, F >::lookupField (char * parent, unsigned int fieldIndex) const inline virtual
virtual function to look up pointer for Field object. This casts everything down to chars so that the FieldElement can use it.
Implements FieldElementFinfoBase.
Definition at line 148 of file FieldElementFinfo.h.
    {
        T* pa = reinterpret_cast< T* >( parent );
        if ( fieldIndex < ( pa->*getNumField_ )() )
        {
            F* self = ( pa->*lookupField_ )( fieldIndex );
            return reinterpret_cast< char* >( self );
        }
        return 0;
    }
References FieldElementFinfo< T, F >::getNumField_.
rttiType()
template<class T , class F > string FieldElementFinfo< T, F >::rttiType () const inline virtual
Virtual function to look up type of FieldElementFinfo.
Reimplemented from Finfo.
Definition at line 176 of file FieldElementFinfo.h.
    {
        return Conv<F>::rttiType();
    }
setNumField()
template<class T , class F > void FieldElementFinfo< T, F >::setNumField (char * parent, unsigned int num) const inline virtual
virtual func to resize Field array, using char* for parent
Implements FieldElementFinfoBase.
Definition at line 160 of file FieldElementFinfo.h.
    {
        T* pa = reinterpret_cast< T* >( parent );
        ( pa->*setNumField_ )( num );
    }
References FieldElementFinfo< T, F >::setNumField_.
Member Data Documentation
getNumField_
template<class T , class F > unsigned int(T::* FieldElementFinfo< T, F >::getNumField_) () const private
Definition at line 184 of file FieldElementFinfo.h.
Referenced by FieldElementFinfo< T, F >::FieldElementFinfo(), FieldElementFinfo< T, F >::getNumField(), and FieldElementFinfo< T, F >::lookupField().
lookupField_
template<class T , class F > F *(T::* FieldElementFinfo< T, F >::lookupField_) (unsigned int) private
Definition at line 182 of file FieldElementFinfo.h.
setNumField_
template<class T , class F > void(T::* FieldElementFinfo< T, F >::setNumField_) (unsigned int num) private
Definition at line 183 of file FieldElementFinfo.h.
Referenced by FieldElementFinfo< T, F >::FieldElementFinfo(), and FieldElementFinfo< T, F >::setNumField().
The documentation for this class was generated from the following file:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/basecode/FieldElementFinfo.h