MOOSE - Multiscale Object Oriented Simulation Environment: Reac Class Reference
Reac Class Reference
#include <Reac.h>
Public Member Functions
ObjId getCompartment (const Eref &e) const
Look up the ObjId of the parent compartment of the reac.
double getConcKb (const Eref &e) const
get Kb in concentration units
double getConcKf (const Eref &e) const
get Kf in concentration units
double getNumKb (const Eref &e) const
double getNumKf (const Eref &e) const
unsigned int getNumPrd (const Eref &e) const
Get number of products.
unsigned int getNumSub (const Eref &e) const
Get number of substrates.
void prd (double v)
Reac ()
void setConcKb (const Eref &e, double v)
set Kb in concentration units
void setConcKf (const Eref &e, double v)
set Kf in concentration units
void setNumKb (const Eref &e, double v)
void setNumKf (const Eref &e, double v)
void setSolver (const Eref &e, ObjId stoich)
void sub (double v)
virtual ~Reac ()
Static Public Member Functions
static const Cinfo * initCinfo ()
Private Attributes
double concKb_
double concKf_
Stoich * stoich_
Detailed Description
Definition at line 13 of file Reac.h.
Constructor & Destructor Documentation
Reac()
Reac::Reac ()
Definition at line 190 of file Reac.cpp.
    : concKf_( 0.1 ), concKb_( 0.2 ), stoich_( 0 )
{ ; }
References concKb_, concKf_, and stoich_.
~Reac()
Reac::~Reac () virtual
Definition at line 194 of file Reac.cpp.
{;}
Member Function Documentation
getCompartment()
ObjId Reac::getCompartment (const Eref & e) const
Look up the ObjId of the parent compartment of the reac.
Definition at line 273 of file Reac.cpp.
{
    return getCompt( e.id() );
}
References getCompt(), and Eref::id().
Referenced by initCinfo().
getConcKb()
double Reac::getConcKb (const Eref & e) const
get Kb in concentration units
Definition at line 252 of file Reac.cpp.
{
    return concKb_;
}
References concKb_.
Referenced by initCinfo().
getConcKf()
double Reac::getConcKf (const Eref & e) const
get Kf in concentration units
Definition at line 240 of file Reac.cpp.
{
    return concKf_;
}
References concKf_.
Referenced by initCinfo().
getNumKb()
double Reac::getNumKb (const Eref & e) const
Definition at line 227 of file Reac.cpp.
{
    double volScale = convertConcToNumRateUsingMesh( e, prdOut(), 0 );
    return concKb_ / volScale;
}
References concKb_, convertConcToNumRateUsingMesh(), and prdOut().
Referenced by initCinfo().
getNumKf()
double Reac::getNumKf (const Eref & e) const
Definition at line 209 of file Reac.cpp.
{
    // Return value for voxel 0. Conceivably I might want to use the
    // DataId part to specify which voxel to use, but that isn't in the
    // current definition for Reacs as being a single entity for the
    // entire compartment.
    double volScale = convertConcToNumRateUsingMesh( e, subOut(), 0 );
    return concKf_ / volScale;
}
References concKf_, convertConcToNumRateUsingMesh(), and subOut().
Referenced by initCinfo().
getNumPrd()
unsigned int Reac::getNumPrd (const Eref & e) const
Get number of products.
Definition at line 265 of file Reac.cpp.
{
    const vector< MsgFuncBinding >* mfb =
        e.element()->getMsgAndFunc( prdOut()->getBindIndex() );
    assert( mfb );
    return ( mfb->size() );
}
References Eref::element(), SrcFinfo::getBindIndex(), Element::getMsgAndFunc(), and prdOut().
Referenced by initCinfo().
getNumSub()
unsigned int Reac::getNumSub (const Eref & e) const
Get number of substrates.
Definition at line 257 of file Reac.cpp.
{
    const vector< MsgFuncBinding >* mfb =
        e.element()->getMsgAndFunc( subOut()->getBindIndex() );
    assert( mfb );
    return ( mfb->size() );
}
References Eref::element(), SrcFinfo::getBindIndex(), Element::getMsgAndFunc(), and subOut().
Referenced by initCinfo().
initCinfo()
const Cinfo * Reac::initCinfo () static
Definition at line 46 of file Reac.cpp.
{
        // Field Definitions
        static ElementValueFinfo< Reac, double > kf(
            "numKf",
            "Forward rate constant, in # units",
            &Reac::setNumKf,
            &Reac::getNumKf
        );
        static ElementValueFinfo< Reac, double > kb(
            "numKb",
            "Reverse rate constant, in # units",
            &Reac::setNumKb,
            &Reac::getNumKb
        );
        static ElementValueFinfo< Reac, double > Kf(
            "Kf",
            "Forward rate constant, in concentration units",
            &Reac::setConcKf,
            &Reac::getConcKf
        );
        static ElementValueFinfo< Reac, double > Kb(
            "Kb",
            "Reverse rate constant, in concentration units",
            &Reac::setConcKb,
            &Reac::getConcKb
        );
        static ReadOnlyElementValueFinfo< Reac, unsigned int > numSub(
            "numSubstrates",
            "Number of substrates of reaction",
            &Reac::getNumSub
        );
        static ReadOnlyElementValueFinfo< Reac, unsigned int > numPrd(
            "numProducts",
            "Number of products of reaction",
            &Reac::getNumPrd
        );
        static ReadOnlyElementValueFinfo< Reac, ObjId > compartment(
            "compartment",
            "ObjId of parent compartment of Reac. "
            "If the compartment isn't"
            "available this returns the root ObjId.",
            &Reac::getCompartment
        );
        // MsgDest Definitions
        /*
        static DestFinfo process( "process",
            "Handles process call",
            new ProcOpFunc< Reac >( &Reac::process ) );
        static DestFinfo reinit( "reinit",
            "Handles reinit call",
            new ProcOpFunc< Reac >( &Reac::reinit ) );
            */
        static DestFinfo setSolver( "setSolver",
            "Assigns solver to this Reac.",
            new EpFunc1< Reac, ObjId >( &Reac::setSolver ) );
        // Shared Msg Definitions
        static DestFinfo subDest( "subDest",
                "Handles # of molecules of substrate",
                new OpFunc1< Reac, double >( &Reac::sub ) );
        static DestFinfo prdDest( "prdDest",
                "Handles # of molecules of product",
                new OpFunc1< Reac, double >( &Reac::prd ) );
        static Finfo* subShared[] = {
            subOut(), &subDest
        };
        static Finfo* prdShared[] = {
            prdOut(), &prdDest
        };
        static SharedFinfo sub( "sub",
            "Connects to substrate pool",
            subShared, sizeof( subShared ) / sizeof( const Finfo* )
        );
        static SharedFinfo prd( "prd",
            "Connects to substrate pool",
            prdShared, sizeof( prdShared ) / sizeof( const Finfo* )
        );
        /*
        static Finfo* procShared[] = {
            &process, &reinit
        };
        static SharedFinfo proc( "proc",
            "Shared message for process and reinit",
            procShared, sizeof( procShared ) / sizeof( const Finfo* )
        );
        */
    static Finfo* reacFinfos[] = {
        &kf,    // Value
        &kb,    // Value
        &Kf,    // Value
        &Kb,    // Value
        &numSub,    // ReadOnlyValue
        &numPrd,    // ReadOnlyValue
        &compartment,   // ReadOnlyValue
        &sub,               // SharedFinfo
        &prd,               // SharedFinfo
        // &proc,               // SharedFinfo
        &setSolver,         // DestFinfo
    };
    static string doc[] =
    {
        "Name", "Reac",
        "Author", "Upinder S. Bhalla, 2012, 2020 NCBS",
        "Description", "Class for reactions. Handles both standalone and"
        "solved configurations"
    };
    static Dinfo<Reac> dinfo;
    static Cinfo reacCinfo (
        "Reac",
        Neutral::initCinfo(),
        reacFinfos,
        sizeof( reacFinfos ) / sizeof ( Finfo* ),
        &dinfo,
        doc,
        sizeof( doc ) / sizeof( string )
    );
    return &reacCinfo;
}
References Cinfo::Cinfo(), DestFinfo::DestFinfo(), ElementValueFinfo< T, F >::ElementValueFinfo(), EpFunc1< T, A >::EpFunc1(), getCompartment(), getConcKb(), getConcKf(), getNumKb(), getNumKf(), getNumPrd(), getNumSub(), Neutral::initCinfo(), OpFunc1< T, A >::OpFunc1(), prd(), prdOut(), ReadOnlyElementValueFinfo< T, F >::ReadOnlyElementValueFinfo(), setConcKb(), setConcKf(), setNumKb(), setNumKf(), setSolver(), SharedFinfo::SharedFinfo(), sub(), and subOut().
Referenced by findParentComptOfReac(), and testTwoReacGetNeighbors().
prd()
void Reac::prd (double v)
Definition at line 286 of file Reac.cpp.
{;}
Referenced by initCinfo().
setConcKb()
void Reac::setConcKb (const Eref & e, double v)
set Kb in concentration units
Definition at line 245 of file Reac.cpp.
{
    concKb_ = v;
    if ( stoich_ )
        stoich_->setReacKb( e, v );
}
References concKb_, Stoich::setReacKb(), and stoich_.
Referenced by initCinfo().
setConcKf()
void Reac::setConcKf (const Eref & e, double v)
set Kf in concentration units
Definition at line 233 of file Reac.cpp.
{
    concKf_ = v;
    if ( stoich_ )
        stoich_->setReacKf( e, v );
}
References concKf_, Stoich::setReacKf(), and stoich_.
Referenced by initCinfo().
setNumKb()
void Reac::setNumKb (const Eref & e, double v)
Definition at line 219 of file Reac.cpp.
{
    double volScale = convertConcToNumRateUsingMesh( e, prdOut(), 0 );
    concKb_ = v * volScale;
    if ( stoich_ )
        stoich_->setReacKb( e, concKb_ );
}
References concKb_, convertConcToNumRateUsingMesh(), prdOut(), Stoich::setReacKb(), and stoich_.
Referenced by initCinfo().
setNumKf()
void Reac::setNumKf (const Eref & e, double v)
Definition at line 201 of file Reac.cpp.
{
    double volScale = convertConcToNumRateUsingMesh( e, subOut(), 0 );
    concKf_ = v * volScale;
    if ( stoich_ )
        stoich_->setReacKf( e, concKf_ );
}
References concKf_, convertConcToNumRateUsingMesh(), Stoich::setReacKf(), stoich_, and subOut().
Referenced by initCinfo().
setSolver()
void Reac::setSolver (const Eref & e, ObjId stoich)
Some of this should go into notifyAddReac
Definition at line 293 of file Reac.cpp.
{
    if ( newStoich.bad() ) {
        cout << "Warning: Reac::setSolver: Bad Stoich " <<
                e.id().path() << endl;
        return;
    }
    if ( newStoich == ObjId() ) { // Unsetting stoich.
        if ( stoich_ != 0 )
            stoich_->notifyRemoveReac( e );
        stoich_ = 0;
        return;
    }
    if ( !newStoich.element()->cinfo()->isA( "Stoich" ) ) {
        cout << "Warning: Reac::setSolver: object " << newStoich.path() << "is not a Stoich for " <<
                e.id().path() << endl;
        return;
    }
    assert( newStoich.element()->cinfo()->isA( "Stoich" ) );
    Stoich* stoichPtr = reinterpret_cast< Stoich* >( newStoich.eref().data( ) );
    if ( stoich_ == stoichPtr )
        return;
    if ( stoich_ != 0 )
        stoich_->notifyRemoveReac( e );
    stoich_ = stoichPtr;
    vector< Id > sub;
    vector< Id > prd;
    e.element()->getNeighbors( sub, subOut() );
    e.element()->getNeighbors( prd, prdOut() );
    stoich_->installReaction( e.id(), sub, prd );
    stoich_->setReacKf( e, concKf_ );
    stoich_->setReacKb( e, concKb_ );
}
References ObjId::bad(), Element::cinfo(), concKb_, concKf_, Eref::data(), Eref::element(), ObjId::element(), ObjId::eref(), Element::getNeighbors(), Eref::id(), Stoich::installReaction(), Cinfo::isA(), Stoich::notifyRemoveReac(), ObjId::ObjId(), ObjId::operator==(), Id::path(), ObjId::path(), prdOut(), Stoich::setReacKb(), Stoich::setReacKf(), stoich_, and subOut().
Referenced by initCinfo().
sub()
void Reac::sub (double v)
Definition at line 283 of file Reac.cpp.
{;}
Referenced by initCinfo().
Member Data Documentation
concKb_
double Reac::concKb_ private
Definition at line 64 of file Reac.h.
Referenced by getConcKb(), getNumKb(), Reac(), setConcKb(), setNumKb(), and setSolver().
concKf_
double Reac::concKf_ private
Definition at line 63 of file Reac.h.
Referenced by getConcKf(), getNumKf(), Reac(), setConcKf(), setNumKf(), and setSolver().
stoich_
Stoich* Reac::stoich_ private
Definition at line 65 of file Reac.h.
Referenced by Reac(), setConcKb(), setConcKf(), setNumKb(), setNumKf(), and setSolver().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/kinetics/Reac.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/kinetics/Reac.cpp