MOOSE - Multiscale Object Oriented Simulation Environment: SpikeGen Class Reference
SpikeGen Class Reference
#include <SpikeGen.h>
Public Member Functions
bool getEdgeTriggered () const
bool getFired () const
double getLastSpikeTime () const
double getRefractT () const
double getThreshold () const
void handleVm (double val)
void process (const Eref &e, ProcPtr p)
void reinit (const Eref &e, ProcPtr p)
void setEdgeTriggered (bool yes)
void setRefractT (double val)
void setThreshold (double threshold)
SpikeGen ()
Static Public Member Functions
static const Cinfo * initCinfo ()
Private Attributes
bool edgeTriggered_
bool fired_
double lastEvent_
double refractT_
double threshold_
double V_
Detailed Description
Definition at line 13 of file SpikeGen.h.
Constructor & Destructor Documentation
SpikeGen()
SpikeGen::SpikeGen ()
Definition at line 127 of file SpikeGen.cpp.
    : threshold_(0.0),
      refractT_(0.0),
      lastEvent_(0.0),
      V_(0.0),
      fired_( 0 ),
      edgeTriggered_(1)
{;}
References edgeTriggered_, fired_, lastEvent_, refractT_, threshold_, and V_.
Member Function Documentation
getEdgeTriggered()
bool SpikeGen::getEdgeTriggered () const
Definition at line 193 of file SpikeGen.cpp.
{
    return edgeTriggered_;
}
References edgeTriggered_.
Referenced by initCinfo().
getFired()
bool SpikeGen::getFired () const
Definition at line 179 of file SpikeGen.cpp.
{
    return fired_;
}
References fired_.
Referenced by initCinfo().
getLastSpikeTime()
double SpikeGen::getLastSpikeTime () const
Definition at line 184 of file SpikeGen.cpp.
{
    return lastEvent_;
}
References lastEvent_.
Referenced by initCinfo().
getRefractT()
double SpikeGen::getRefractT () const
Definition at line 154 of file SpikeGen.cpp.
{
    return refractT_;
}
References refractT_.
Referenced by initCinfo().
getThreshold()
double SpikeGen::getThreshold () const
Definition at line 145 of file SpikeGen.cpp.
{
    return threshold_;
}
References threshold_.
Referenced by initCinfo().
handleVm()
void SpikeGen::handleVm (double val)
Definition at line 224 of file SpikeGen.cpp.
{
    V_ = val;
}
References V_.
Referenced by initCinfo(), and SpikeGenStruct::send().
initCinfo()
const Cinfo * SpikeGen::initCinfo () static
Definition at line 22 of file SpikeGen.cpp.
{
    // Shared message definitions
    static DestFinfo process( "process",
        "Handles process call",
        new ProcOpFunc< SpikeGen >( &SpikeGen::process ) );
    static DestFinfo reinit( "reinit",
        "Handles reinit call",
        new ProcOpFunc< SpikeGen >( &SpikeGen::reinit ) );
    static Finfo* processShared[] =
    {
        &process, &reinit
    };
    static SharedFinfo proc( "proc",
        "Shared message to receive Process message from scheduler",
        processShared, sizeof( processShared ) / sizeof( Finfo* ) );
    // Dest Finfos.
    static DestFinfo Vm( "Vm",
            "Handles Vm message coming in from compartment",
            new OpFunc1< SpikeGen, double >( &SpikeGen::handleVm ) );
    // Value Finfos.
    static ValueFinfo< SpikeGen, double > threshold( "threshold",
        "Spiking threshold, must cross it going up",
        &SpikeGen::setThreshold,
        &SpikeGen::getThreshold
    );
    static ValueFinfo< SpikeGen, double > refractT( "refractT",
        "Refractory Time.",
        &SpikeGen::setRefractT,
        &SpikeGen::getRefractT
    );
    static ValueFinfo< SpikeGen, double > absRefract( "abs_refract",
        "Absolute refractory time. Synonym for refractT.",
        &SpikeGen::setRefractT,
        &SpikeGen::getRefractT
    );
    static ReadOnlyValueFinfo< SpikeGen, bool > hasFired( "hasFired",
        "True if SpikeGen has just fired",
        &SpikeGen::getFired
    );
    static ReadOnlyValueFinfo< SpikeGen, double > lastSpikeTime( "lastSpikeTime",
        "Time of most recent spike event.",
        &SpikeGen::getLastSpikeTime
    );
    static ValueFinfo< SpikeGen, bool > edgeTriggered( "edgeTriggered",
        "When edgeTriggered = 0, the SpikeGen will fire an event in each "
        "timestep while incoming Vm is > threshold and at least abs_refract"
        "time has passed since last event. This may be problematic if the "
        "incoming Vm remains above threshold for longer than abs_refract. "
        "Setting edgeTriggered to 1 resolves this as the SpikeGen generates"
        "an event only on the rising edge of the incoming Vm and will "
        "remain idle unless the incoming Vm goes below threshold.",
        &SpikeGen::setEdgeTriggered,
        &SpikeGen::getEdgeTriggered
    );
    static Finfo* spikeGenFinfos[] =
    {
        spikeOut(), // SrcFinfo
        &proc,      // Shared
        &Vm,        // Dest
        &threshold, // Value
        &refractT,  // Value
        &absRefract,    // Value
        &hasFired,  // ReadOnlyValue
        &lastSpikeTime, // ReadOnlyValue
        &edgeTriggered, // Value
    };
    static string doc[] =
    {
        "Name", "SpikeGen",
        "Author", "Upi Bhalla",
        "Description", "SpikeGen object, for detecting threshold crossings."
        "The threshold detection can work in multiple modes.\n "
        "If the refractT < 0.0, then it fires an event only at the rising "
        "edge of the input voltage waveform"
    };
    static Dinfo< SpikeGen > dinfo;
    static Cinfo spikeGenCinfo(
        "SpikeGen",
        Neutral::initCinfo(),
        spikeGenFinfos, sizeof( spikeGenFinfos ) / sizeof( Finfo* ),
        &dinfo,
                doc,
                sizeof(doc)/sizeof(string)
    );
    return &spikeGenCinfo;
}
References Cinfo::Cinfo(), DestFinfo::DestFinfo(), getEdgeTriggered(), getFired(), getLastSpikeTime(), getRefractT(), getThreshold(), handleVm(), Neutral::initCinfo(), OpFunc1< T, A >::OpFunc1(), process(), ProcOpFunc< T >::ProcOpFunc(), ReadOnlyValueFinfo< T, F >::ReadOnlyValueFinfo(), reinit(), setEdgeTriggered(), setRefractT(), setThreshold(), SharedFinfo::SharedFinfo(), spikeOut(), and ValueFinfo< T, F >::ValueFinfo().
Referenced by HSolveActive::readSynapses().
process()
void SpikeGen::process (const Eref & e, ProcPtr p)
Definition at line 202 of file SpikeGen.cpp.
{
    double t = p->currTime;
    if ( V_ > threshold_ ) {
        if ((t + p->dt/2.0) >= (lastEvent_ + refractT_)) {
            if ( !( edgeTriggered_ && fired_ ) ) {
                spikeOut()->send( e, t );
                lastEvent_ = t;
                fired_ = true;
            }
        }
    } else {
            fired_ = false;
    }
}
References ProcInfo::currTime, ProcInfo::dt, edgeTriggered_, fired_, lastEvent_, refractT_, SrcFinfo1< T >::send(), spikeOut(), threshold_, and V_.
Referenced by initCinfo(), and SpikeGenStruct::send().
reinit()
void SpikeGen::reinit (const Eref & e, ProcPtr p)
Definition at line 219 of file SpikeGen.cpp.
{
    lastEvent_ = -refractT_ ;
}
References lastEvent_, and refractT_.
Referenced by initCinfo(), and SpikeGenStruct::reinit().
setEdgeTriggered()
void SpikeGen::setEdgeTriggered (bool yes)
Definition at line 189 of file SpikeGen.cpp.
{
    edgeTriggered_ = yes;
}
References edgeTriggered_.
Referenced by initCinfo().
setRefractT()
void SpikeGen::setRefractT (double val)
Definition at line 150 of file SpikeGen.cpp.
{
    refractT_ = val;
}
References refractT_.
Referenced by initCinfo().
setThreshold()
void SpikeGen::setThreshold (double threshold)
Definition at line 141 of file SpikeGen.cpp.
{
    threshold_ = threshold;
}
References threshold_.
Referenced by initCinfo().
Member Data Documentation
edgeTriggered_
bool SpikeGen::edgeTriggered_ private
Definition at line 55 of file SpikeGen.h.
Referenced by getEdgeTriggered(), process(), setEdgeTriggered(), and SpikeGen().
fired_
bool SpikeGen::fired_ private
Definition at line 54 of file SpikeGen.h.
Referenced by getFired(), process(), and SpikeGen().
lastEvent_
double SpikeGen::lastEvent_ private
Definition at line 52 of file SpikeGen.h.
Referenced by getLastSpikeTime(), process(), reinit(), and SpikeGen().
refractT_
double SpikeGen::refractT_ private
Definition at line 51 of file SpikeGen.h.
Referenced by getRefractT(), process(), reinit(), setRefractT(), and SpikeGen().
threshold_
double SpikeGen::threshold_ private
Definition at line 50 of file SpikeGen.h.
Referenced by getThreshold(), process(), setThreshold(), and SpikeGen().
V_
double SpikeGen::V_ private
Definition at line 53 of file SpikeGen.h.
Referenced by handleVm(), process(), and SpikeGen().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/biophysics/SpikeGen.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/biophysics/SpikeGen.cpp