MOOSE - Multiscale Object Oriented Simulation Environment: Field< A > Class Template Reference
Field< A > Class Template Reference
#include <SetGet.h>
Public Member Functions
Field ()
Public Member Functions inherited from SetGet1< A >
bool checkOpClass (const OpFunc *op) const
SetGet1 ()
Public Member Functions inherited from SetGet
SetGet ()
virtual ~SetGet ()
Static Public Member Functions
static A get (const ObjId &dest, const string &field)
static void getVec (ObjId dest, const string &field, vector< A > &vec)
static bool innerStrGet (const ObjId &dest, const string &field, string &str)
static bool innerStrSet (const ObjId &dest, const string &field, const string &arg)
static bool set (const ObjId &dest, const string &field, A arg)
static bool setRepeat (ObjId destId, const string &field, A arg)
static bool setVec (ObjId destId, const string &field, const vector< A > &arg)
Static Public Member Functions inherited from SetGet1< A >
static bool innerStrSet (const ObjId &dest, const string &field, const string &val)
static bool set (const ObjId &dest, const string &field, A arg)
static bool setRepeat (ObjId destId, const string &field, const A &arg)
static bool setVec (ObjId destId, const string &field, const vector< A > &arg)
Static Public Member Functions inherited from SetGet
static const OpFunc * checkSet (const string &field, ObjId &tgt, FuncId &fid)
static const vector< double * > * dispatchGet (const ObjId &tgt, FuncId tgtFid, const double *arg, unsigned int size)
Sends out request for data, and awaits its return.
static bool strGet (const ObjId &tgt, const string &field, string &ret)
static bool strSet (const ObjId &dest, const string &field, const string &val)
Detailed Description
template<class A>
class Field< A >
Definition at line 260 of file SetGet.h.
Constructor & Destructor Documentation
Field()
template<class A > Field< A >::Field () inline
Definition at line 263 of file SetGet.h.
    {
        ;
    }
Member Function Documentation
get()
template<class A > static A Field< A >::get (const ObjId & dest, const string & field) inline static
Definition at line 307 of file SetGet.h.
    {
        ObjId tgt( dest );
        FuncId fid;
        string fullFieldName = "get" + field;
        fullFieldName[3] = std::toupper( fullFieldName[3] );
        const OpFunc* func = SetGet::checkSet( fullFieldName, tgt, fid );
        const GetOpFuncBase< A >* gof = dynamic_cast< const GetOpFuncBase< A >* >( func );
        if ( gof )
        {
            if ( tgt.isDataHere() )
            {
                return gof->returnOp( tgt.eref() );
            }
            else
            {
                const OpFunc* op2 = gof->makeHopFunc(
                                        HopIndex( gof->opIndex(), MooseGetHop ) );
                const OpFunc1Base< A* >* hop =
                    dynamic_cast< const OpFunc1Base< A* >* >( op2 );
                assert( hop );
                // Blocking function.
                A ret;
                hop->op( tgt.eref(), &ret );
                delete op2;
                return ret;
            }
        }
        cout << "Warning: Field::Get conversion error for " <<
             dest.id.path() << "." << field << endl;
        return A();
    }
References SetGet::checkSet(), ObjId::eref(), ObjId::id, ObjId::isDataHere(), MooseGetHop, ObjId::ObjId(), and Id::path().
Referenced by ReadCell::addCaConc(), ReadCell::addChannelMessage(), addSpine(), ReadCell::buildCompartment(), Dsolve::buildMeshJunctions(), Dsolve::buildNeuroMeshJunctions(), PresynMesh::buildOnDendrites(), PresynMesh::buildOnSpineHeads(), ReadKkit::buildSumTotal(), checkOutput(), ReadKkit::convertEnzRatesToConcUnits(), ReadKkit::convertMMenzRatesToConcUnits(), ReadKkit::convertPoolAmountToConcUnits(), ReadKkit::convertReacRatesToConcUnits(), coordSystem(), HSolveActive::createLookupTables(), estimateDefaultVol(), estimateSimTimes(), Neuron::evalExprForElist(), Dsolve::fillConcChans(), fillSegIndex(), fillSegments(), ReadKkit::findCompartmentsFromAnnotation(), HSolveUtils::gates(), ChemCompt::getChildConcs(), EndoMesh::getElecComptMap(), Spine::getHeadDiameter(), Spine::getHeadLength(), Stoich::getProxyPools(), Spine::getShaftDiameter(), Spine::getShaftLength(), HSolvePassive::initialize(), Field< A >::innerStrGet(), NeuroMesh::insertDummyNodes(), Stoich::installAndUnschedFunc(), Stoich::installAndUnschedFuncRate(), Stoich::installAndUnschedFuncReac(), kineticsHasReactions(), ReadKkit::loadTab(), makeCompt(), makeReacTest(), mapVoxelsBetweenMeshes(), Dsolve::mapXfersBetweenDsolves(), NeuroNode::NeuroNode(), PoolBase::notifyCopy(), FuncRate::operator()(), FuncReac::operator()(), positionCompt(), printGrid(), Stoich::printRates(), HSolveUtils::rates(), HSolveActive::readCalcium(), ReadCell::ReadCell(), HSolveActive::readGates(), HSolveActive::readHHChannels(), moose::VClamp::reinit(), Neuron::scaleHeadDiffusion(), KsolveBase::setCompartment(), Gsolve::setCompartment(), Dsolve::setCompartment(), Stoich::setCompartment(), moose::CompartmentBase::setGeomAndElec(), Spine::setHeadDiameter(), Spine::setHeadLength(), Spine::setHeadVolume(), Dsolve::setPath(), Spine::setShaftDiameter(), Spine::setShaftLength(), Neuron::setSpineAndPsdMesh(), Dsolve::setStoich(), ReadKkit::setupSlaveMsg(), SpineEntry::SpineEntry(), storeCplxEnzMsgs(), storeEnzMsgs(), storeFunctionMsgs(), storeMMenzMsgs(), storePlotMsgs(), storeReacMsgs(), HSolvePassive::storeTree(), testBuildStoich(), testCalcJunction(), testCellDiffn(), testCinfoElements(), testCopy(), testCopyFieldElement(), testCylDiffn(), testCylDiffnWithStoich(), testGet(), testGetMsg(), testMMenzProcess(), testMove(), testMsgElementListing(), testObjIdToAndFromPath(), testPoolVolumeScaling(), testReacVolumeScaling(), ReadCspace::testReadModel(), testReMesh(), testSendSpike(), testSetGet(), testSetGetDouble(), testSetGetExtField(), testSetGetSynapse(), testShellAddMsg(), testShellSetGet(), testSmallCellDiffn(), testSparseMsg(), testStats(), testSyncSynapseSize(), testTable(), testTaperingCylDiffn(), testTreeTraversal(), testVolScaling(), traverseCumulativeDistance(), trimPath(), Stoich::updateRatesAfterRemesh(), Neuron::updateSegmentLengths(), NeuroMesh::updateShaftParents(), writeEnz(), writeGroup(), writeKkit(), writePool(), writeReac(), Stoich::zombifyModel(), and Stoich::zombifyPoolFuncWithScaling().
getVec()
template<class A > static void Field< A >::getVec (ObjId dest, const string & field, vector< A > & vec) inline static
Returns a vector of values
Definition at line 345 of file SetGet.h.
    {
        vec.resize( 0 );
        ObjId tgt( dest );
        FuncId fid;
        string fullFieldName = "get" + field;
        fullFieldName[3] = std::toupper( fullFieldName[3] );
        const OpFunc* func = SetGet::checkSet( fullFieldName, tgt, fid );
        const GetOpFuncBase< A >* gof =
            dynamic_cast< const GetOpFuncBase< A >* >( func );
        if ( gof )
        {
            const OpFunc* op2 = gof->makeHopFunc(
                                    HopIndex( gof->opIndex(), MooseGetVecHop ) );
            const GetHopFunc< A >* hop =
                dynamic_cast< const GetHopFunc< A >* >( op2 );
            hop->opGetVec( tgt.eref(), vec, gof );
            delete op2;
            return;
        }
        cout << "Warning: Field::getVec conversion error for " <<
             dest.path() << endl;
    }
References SetGet::checkSet(), ObjId::eref(), MooseGetVecHop, ObjId::ObjId(), and ObjId::path().
Referenced by benchmarkMsg(), testCellDiffn(), testCopyFieldElement(), testCylDiffn(), testCylDiffnWithStoich(), testMpiFibonacci(), testSetGetVec(), testSetRepeat(), testShellAddMsg(), testShellSetGet(), testSmallCellDiffn(), and testTaperingCylDiffn().
innerStrGet()
template<class A > static bool Field< A >::innerStrGet (const ObjId & dest, const string & field, string & str) inline static
Blocking call for finding a value and returning in a string.
Definition at line 374 of file SetGet.h.
    {
        Conv< A >::val2str( str, get( dest, field ) );
        return 1;
    }
References Field< A >::get().
innerStrSet()
template<class A > static bool Field< A >::innerStrSet (const ObjId & dest, const string & field, const string & arg) inline static
Blocking call using string conversion
Definition at line 296 of file SetGet.h.
    {
        A val;
        // Do NOT add 'set_' to the field name, as the 'set' func
        // does it anyway.
        Conv< A >::str2val( val, arg );
        return set( dest, field, val );
    }
References Field< A >::set().
set()
template<class A > static bool Field< A >::set (const ObjId & dest, const string & field, A arg) inline static
Blocking, typed 'Set' call
Definition at line 271 of file SetGet.h.
    {
        string temp = "set" + field;
        temp[3] = std::toupper( temp[3] );
        return SetGet1< A >::set( dest, temp, arg );
    }
Referenced by ReadCell::addCaConc(), ReadCell::addCanonicalChannel(), ReadCell::addSpikeGen(), assignParam(), assignSingleCompartmentParams(), benchmarkMsg(), ReadKkit::buildChan(), ReadCell::buildChannels(), ReadCell::buildCompartment(), ReadKkit::buildEnz(), ReadKkit::buildInfo(), ReadKkit::buildPool(), ReadKkit::buildReac(), ReadKkit::buildStim(), ReadKkit::buildSumTotal(), ReadKkit::buildTable(), ReadKkit::call(), ReadKkit::convertEnzRatesToConcUnits(), ReadKkit::convertMMenzRatesToConcUnits(), ReadKkit::convertPoolAmountToConcUnits(), ReadKkit::convertReacRatesToConcUnits(), ReadCspace::deployParameters(), ReadKkit::findCompartmentsFromAnnotation(), Field< A >::innerStrSet(), ReadKkit::loadTab(), makeCompt(), makeReacTest(), positionCompt(), ReadKkit::read(), ReadCspace::readModelString(), reorientSpine(), ChemCompt::setChildConcs(), moose::CompartmentBase::setGeomAndElec(), ReadKkit::setupSlaveMsg(), testBuildStoich(), testCalcJunction(), testCellDiffn(), testChildren(), testCopyFieldElement(), testCylDiffn(), testCylDiffnWithStoich(), testMMenzProcess(), testMpiFibonacci(), testObjIdToAndFromPath(), testPoolVolumeScaling(), testReacVolumeScaling(), testReMesh(), testRunGsolve(), testRunKsolve(), testRunKsolveWithLSODA(), testSendSpike(), testSetGet(), testSetGetDouble(), testSetGetExtField(), testSmallCellDiffn(), testStats(), testSyncSynapseSize(), testTaperingCylDiffn(), testTreeTraversal(), testVolScaling(), testWildcard(), and Stoich::zombifyModel().
setRepeat()
template<class A > static bool Field< A >::setRepeat (ObjId destId, const string & field, A arg) inline static
Definition at line 286 of file SetGet.h.
    {
        string temp = "set" + field;
        temp[3] = std::toupper( temp[3] );
        return SetGet1< A >::setRepeat( destId, temp, arg );
    }
Referenced by testCopyFieldElement(), and testSetRepeat().
setVec()
template<class A > static bool Field< A >::setVec (ObjId destId, const string & field, const vector< A > & arg) inline static
Definition at line 278 of file SetGet.h.
    {
        string temp = "set" + field;
        temp[3] = std::toupper( temp[3] );
        return SetGet1< A >::setVec( destId, temp, arg );
    }
Referenced by testCopyFieldElement(), testSetGetExtField(), testSetGetSynapse(), testSetGetVec(), testSetRepeat(), testSparseMsg(), and testSyncSynapseSize().
The documentation for this class was generated from the following file:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/basecode/SetGet.h