MOOSE - Multiscale Object Oriented Simulation Environment: VoxelPools Class Reference
VoxelPools Class Reference
#include <VoxelPools.h>
Public Member Functions
void advance (const ProcInfo *p)
Do the numerical integration. Advance the simulation.
const string getMethod ()
const Stoich * getStoich ()
void print () const
Used for debugging.
void reinit (double dt)
void setInitDt (double dt)
Set initial timestep to use by the solver.
void setStoich (Stoich *stoich, const OdeSystem *ode)
void setVolumeAndDependencies (double vol)
Handles volume change and subsequent cascading updates.
void updateAllRateTerms (const vector< RateTerm * > &rates, unsigned int numCoreRates)
Updates all the rate constants from the reference rates vector.
void updateRates (const double *s, double *yprime) const
void updateRateTerms (const vector< RateTerm * > &rates, unsigned int numCoreRates, unsigned int index)
void updateReacVelocities (const double *s, vector< double > &v) const
VoxelPools ()
virtual ~VoxelPools ()
Public Member Functions inherited from VoxelPoolsBase
void addProxyTransferIndex (unsigned int comptIndex, unsigned int transferIndex)
void addProxyVoxy (unsigned int comptIndex, Id comptId, unsigned int voxel)
Adds the index of a voxel to which proxy data should go.
void backwardReacVolumeFactor (unsigned int i, double volume)
const double * Cinit () const
void filterCrossRateTerms (const vector< Id > &offSolverReacs, const vector< pair< Id, Id > > &offSolverReacCompts)
void forwardReacVolumeFactor (unsigned int i, double volume)
double getConcInit (unsigned int) const
double getDiffConst (unsigned int) const
double getN (unsigned int) const
double getR1 (unsigned int) const
double getVolume () const
Return the volume of the voxel.
double getXreacScaleProducts (unsigned int i) const
double getXreacScaleSubstrates (unsigned int i) const
bool hasXfer (unsigned int comptIndex) const
True when this voxel has data to be transferred.
bool isVoxelJunctionPresent (Id i1, Id i2) const
void print () const
Debugging utility.
void reinit ()
void resetXreacScale (unsigned int size)
void resizeArrays (unsigned int totNumPools)
Allocate # of pools.
const double * S () const
void scaleVolsBufsRates (double ratio, const Stoich *stoichPtr)
void setConcInit (unsigned int, double v)
void setDiffConst (unsigned int, double v)
void setN (unsigned int i, double v)
void setNumVoxels (unsigned int)
void setVolume (double vol)
Just assigns the volume without any cascading to other values.
unsigned int size () const
vector< double > & Svec ()
Returns a handle to the mol # vector.
double * varCinit ()
double * varS ()
VoxelPoolsBase ()
void xferIn (const vector< unsigned int > &poolIndex, const vector< double > &values, const vector< double > &lastValues, unsigned int voxelIndex)
void xferInOnlyProxies (const vector< unsigned int > &poolIndex, const vector< double > &values, unsigned int numProxyPools, unsigned int voxelIndex)
void xferOut (unsigned int voxelIndex, vector< double > &values, const vector< unsigned int > &poolIndex)
Assembles data values for sending out for x-compt reacs.
virtual ~VoxelPoolsBase ()
Static Public Member Functions
static void lsodaSys (double t, double *y, double *dydt, void *params)
Private Attributes
double epsAbs_
double epsRel_
int lsodaState_
LSODA_ODE_SYSTEM_TYPE lsodaSystem
string method_
std::shared_ptr< LSODA > pLSODA
Additional Inherited Members
Protected Attributes inherited from VoxelPoolsBase
unsigned int numVoxels_
vector< RateTerm * > rates_
const Stoich * stoichPtr_
Detailed Description
This is the class for handling reac-diff voxels used for deterministic computations.
Definition at line 28 of file VoxelPools.h.
Constructor & Destructor Documentation
VoxelPools()
VoxelPools::VoxelPools ()
Definition at line 37 of file VoxelPools.cpp.
                       : pLSODA(nullptr)
{
    lsodaState_ = 1;
#ifdef USE_GSL
    driver_ = 0;
#endif
}
References lsodaState_, and pLSODA.
~VoxelPools()
VoxelPools::~VoxelPools () virtual
Definition at line 45 of file VoxelPools.cpp.
{
    for ( unsigned int i = 0; i < rates_.size(); ++i )
        delete( rates_[i] );
#ifdef USE_GSL
    if ( driver_ )
        gsl_odeiv2_driver_free( driver_ );
#endif
}
References VoxelPoolsBase::rates_.
Member Function Documentation
advance()
void VoxelPools::advance (const ProcInfo * p)
Do the numerical integration. Advance the simulation.
Definition at line 108 of file VoxelPools.cpp.
{
    double t = p->currTime - p->dt;
    Ksolve* k = reinterpret_cast<Ksolve*>( stoichPtr_->getKsolve().eref().data() );
    if( getMethod() == "lsoda" )
    {
        // True if first step or restart, or if diffusion. Tells LSODA to
        // recalculate using new pool n values, which slows it down a bit.
        if ( p->isStart() || (numVoxels_ > 1) )
            lsodaState_ = 1;
        size_t totVar = stoichPtr_->getNumVarPools() + stoichPtr_->getNumProxyPools();
        vector<double> yout(size()+1);
        pLSODA->lsoda_update( &VoxelPools::lsodaSys, size()
                , Svec(), yout , &t
                , p->currTime, &lsodaState_, this
                );
        // Now update the y from yout. This is different thant normal GSL or
        // BOOST based approach.
        // totVar += stoichPtr_->getNumFuncPools();
        for (size_t i = 0; i < totVar; i++)
            varS()[i] = yout[i+1];
        if( lsodaState_ == 0 )
        {
            cerr << "Error: VoxelPools::advance: LSODA integration error at time "
                 << t << "\n";
            assert(0);
        }
    }
    else
    {
#ifdef USE_GSL
        int status = gsl_odeiv2_driver_apply( driver_, &t, p->currTime, varS());
        if ( status != GSL_SUCCESS )
        {
            cerr << "Error: VoxelPools::advance: GSL integration error at time "
                << t << "\n";
            cerr << "Error info: " << status << ", " <<
                gsl_strerror( status ) << endl;
            if ( status == GSL_EMAXITER )
                cerr << "Max number of steps exceeded\n";
            else if ( status == GSL_ENOPROG )
                cerr << "Timestep has gotten too small\n";
            else if ( status == GSL_EBADFUNC )
                cerr << "Internal error\n";
            assert( 0 );
        }
#elif USE_BOOST_ODE
        // NOTE: Make sure to assing vp to BoostSys vp. In next call, it will be used by
        // updateRates func. Unlike gsl call, we can't pass extra void*  to gslFunc.
        VoxelPools* vp = reinterpret_cast< VoxelPools* >( this );
        /*-----------------------------------------------------------------------------
NOTE: 04/21/2016 11:31:42 AM
We need to call updateFuncs  here (unlike in GSL solver) because there
is no way we can update const vector_type_& y in evalRatesUsingBoost
function. In gsl implmentation one could do it, because const_cast can
take away the constantness of double*. This probably makes the call bit
cleaner.
         *-----------------------------------------------------------------------------*/
        stoichPtr_->updateFuncs( &Svec()[0], p->currTime );
        /*-----------------------------------------------------------------------------
         * Using integrate function works with with default stepper type.
         *
         *  NOTICE to developer:
         *  If you are planning your own custom typdedef of stepper_type_ (see
         *  file BoostSystem.h), the you may run into troble. Have a look at this
         *  http://boostw.boost.org/doc/libs/1_56_0/boost/numeric/odeint/integrate/integrate.hpp
         *
         * To make numerical results comparable with "gsl" solvers,
         * by default, we pick adaptive step-size control. Use a suffix 'c' to
         * force a constant step size. The numerical accuracy of constant step
         * size solver is low.
         * More details can be found here:
         * https://www.boost.org/doc/libs/1_72_0/libs/numeric/odeint/doc/html/boost_numeric_odeint/odeint_in_detail/steppers.html
         */
        const double fixedDt = 0.1;
        if( method_ == "rk2" )
            odeint::integrate_const( rk_midpoint_stepper_type_()
                    , [this](const vector_type_& dy, vector_type_& dydt, const double t) {
                    VoxelPools::evalRates(this, dy, dydt );
                    }
                    , Svec()
                    , p->currTime - p->dt, p->currTime, std::min( p->dt, fixedDt )
                    );
        else if( method_ == "rk4c" )
            odeint::integrate_const( rk4_stepper_type_()
                    , [this](const vector_type_& dy, vector_type_& dydt, const double t) {
                    VoxelPools::evalRates(this, dy, dydt );
                    }
                    , Svec()
                    , p->currTime - p->dt, p->currTime, std::min( p->dt, fixedDt )
                    );
        else if( method_ == "rk5c")
            odeint::integrate_const( rk_karp_stepper_type_()
                    , [this](const vector_type_& dy, vector_type_& dydt, const double t) {
                    VoxelPools::evalRates(this, dy, dydt );
                    }
                    , Svec()
                    , p->currTime - p->dt, p->currTime, std::min( p->dt, fixedDt )
                    );
        else if( method_ == "rk5ck" )
            odeint::integrate_adaptive(
                    odeint::make_controlled<rk_karp_stepper_type_>( epsAbs_, epsRel_ )
                    , [this](const vector_type_& dy, vector_type_& dydt, const double t) {
                    VoxelPools::evalRates(this, dy, dydt );
                    }
                    , Svec()
                    , p->currTime - p->dt
                    , p->currTime
                    , p->dt
                    );
        else if ("rk54c" == method_ )
            odeint::integrate_const( rk_karp_stepper_type_()
                    , [this](const vector_type_& dy, vector_type_& dydt, const double t) {
                    VoxelPools::evalRates(this, dy, dydt );
                    }
                    , Svec()
                    , p->currTime - p->dt, p->currTime, std::min( p->dt, fixedDt )
                    );
        else if ("rk54" == method_ )
            odeint::integrate_adaptive(
                    odeint::make_controlled<rk_karp_stepper_type_>( epsAbs_, epsRel_ )
                    , [this](const vector_type_& dy, vector_type_& dydt, const double t) {
                    VoxelPools::evalRates(this, dy, dydt );
                    }
                    , Svec()
                    , p->currTime - p->dt
                    , p->currTime
                    , p->dt
                    );
        else if ("rk5c" == method_ )
            odeint::integrate_const( rk_dopri_stepper_type_()
                    , [this](const vector_type_& dy, vector_type_& dydt, const double t) {
                    VoxelPools::evalRates(this, dy, dydt );
                    }
                    , Svec()
                    , p->currTime - p->dt
                    , p->currTime
                    , std::min( p->dt, fixedDt )
                    );
        else if ("rk5" == method_  || "gsl" == method_)
            odeint::integrate_adaptive(
                    odeint::make_controlled<rk_dopri_stepper_type_>( epsAbs_, epsRel_ )
                    , [this](const vector_type_& dy, vector_type_& dydt, const double t) {
                    VoxelPools::evalRates(this, dy, dydt );
                    }
                    , Svec()
                    , p->currTime - p->dt
                    , p->currTime
                    , p->dt
                    );
        else if( method_ == "rk8c" )
            odeint::integrate_const( rk_felhberg_stepper_type_()
                    , [this](const vector_type_& dy, vector_type_& dydt, const double t) {
                    VoxelPools::evalRates(this, dy, dydt );
                    }
                    , Svec()
                    , p->currTime - p->dt, p->currTime, std::min( p->dt, fixedDt )
                    );
        else if( method_ == "rk8" )
            odeint::integrate_adaptive(
                    odeint::make_controlled<rk_felhberg_stepper_type_>( epsAbs_, epsRel_ )
                    , [this](const vector_type_& dy, vector_type_& dydt, const double t) {
                    VoxelPools::evalRates(this, dy, dydt );
                    }
                    , Svec()
                    , p->currTime - p->dt
                    , p->currTime
                    , p->dt
                    );
        else
            odeint::integrate_adaptive(
                    odeint::make_controlled<rk_karp_stepper_type_>( epsAbs_, epsRel_ )
                    , [this](const vector_type_& dy, vector_type_& dydt, const double t) {
                    VoxelPools::evalRates(this, dy, dydt );
                    }
                    , Svec()
                    , p->currTime - p->dt
                    , p->currTime
                    , p->dt
                    );
#endif   // USE_GSL
    }
    if ( !stoichPtr_->getAllowNegative() )   // clean out negatives
    {
        unsigned int nv = stoichPtr_->getNumVarPools();
        double* vs = varS();
        for ( unsigned int i = 0; i < nv; ++i )
        {
            if ( std::signbit(vs[i]) )
                vs[i] = 0.0;
        }
    }
}
References ProcInfo::currTime, Eref::data(), ProcInfo::dt, Id::eref(), Stoich::getAllowNegative(), Stoich::getKsolve(), getMethod(), Stoich::getNumProxyPools(), Stoich::getNumVarPools(), ProcInfo::isStart(), lsodaState_, lsodaSys(), VoxelPoolsBase::numVoxels_, pLSODA, VoxelPoolsBase::size(), VoxelPoolsBase::stoichPtr_, VoxelPoolsBase::Svec(), and VoxelPoolsBase::varS().
Referenced by Ksolve::advance_chunk(), Ksolve::advance_pool(), and Ksolve::process().
getMethod()
const string VoxelPools::getMethod ()
Definition at line 102 of file VoxelPools.cpp.
{
    Ksolve* k = reinterpret_cast<Ksolve*>( stoichPtr_->getKsolve().eref().data() );
    return k->getMethod( );
}
References Eref::data(), Id::eref(), Stoich::getKsolve(), Ksolve::getMethod(), and VoxelPoolsBase::stoichPtr_.
Referenced by advance(), and reinit().
getStoich()
const Stoich * VoxelPools::getStoich ()
lsodaSys()
void VoxelPools::lsodaSys (double t, double * y, double * dydt, void * param) static
@Synopsis Function to pass LSODA::lsoda_update function. Since it is a * static function, we have to make sure void* param holds the value of pointer * to VoxelPools. * * @Param t * @Param y * @Param dydt * @Param params Address of VoxelPools as void*.
Definition at line 348 of file VoxelPools.cpp.
{
    VoxelPools* vp = reinterpret_cast< VoxelPools* >( param );
    // Fill in the values.
    // Ensure that the buffered values are assigned to y.
    size_t totVar = vp->stoichPtr_->getNumVarPools() + vp->stoichPtr_->getNumProxyPools();
    for( size_t ii = totVar + vp->stoichPtr_->getNumFuncPools(); ii < vp->size(); ii++ ) {
        y[ii] = vp->Svec()[ii];
    }
    vp->stoichPtr_->updateFuncs( y, t );
    for( size_t ii = totVar; ii < totVar + vp->stoichPtr_->getNumFuncPools(); ii++ ) {
        vp->Svec()[ii] = y[ii];
    }
    vp->updateRates( y, dydt );
}
References Stoich::getNumFuncPools(), Stoich::getNumProxyPools(), Stoich::getNumVarPools(), VoxelPoolsBase::size(), VoxelPoolsBase::stoichPtr_, VoxelPoolsBase::Svec(), Stoich::updateFuncs(), and updateRates().
Referenced by advance().
print()
void VoxelPools::print () const
Used for debugging.
For debugging: Print contents of voxel pool.
Definition at line 459 of file VoxelPools.cpp.
{
    cout << "numAllRates = " << rates_.size() <<
         ", numLocalRates= " << stoichPtr_->getNumCoreRates() << endl;
    VoxelPoolsBase::print();
}
References Stoich::getNumCoreRates(), VoxelPoolsBase::print(), VoxelPoolsBase::rates_, and VoxelPoolsBase::stoichPtr_.
Referenced by Ksolve::print().
reinit()
void VoxelPools::reinit (double dt)
Definition at line 58 of file VoxelPools.cpp.
{
    VoxelPoolsBase::reinit();
    lsodaState_ = 1;
#ifdef USE_GSL
    if ( !driver_ )
        return;
    gsl_odeiv2_driver_reset( driver_ );
    gsl_odeiv2_driver_reset_hstart( driver_, dt / 10.0 );
#endif
    // If method is LDODA create lSODA object and save the address of this as
    // param (void*).
    if( getMethod() == "lsoda" )
    {
        pLSODA.reset(new LSODA());
        pLSODA->param = (void *) this;
    }
}
References getMethod(), lsodaState_, pLSODA, and VoxelPoolsBase::reinit().
Referenced by Ksolve::initReinit(), and Ksolve::reinit().
setInitDt()
void VoxelPools::setInitDt (double dt)
Set initial timestep to use by the solver.
Definition at line 313 of file VoxelPools.cpp.
{
#ifdef USE_GSL
    gsl_odeiv2_driver_reset_hstart( driver_, dt );
#endif
}
setStoich()
void VoxelPools::setStoich (Stoich * stoich, const OdeSystem * ode)
setStoich: Assigns the ODE system and Stoich. Stoich may be modified to create a new RateTerm vector in case the volume of this VoxelPools is new.
Definition at line 78 of file VoxelPools.cpp.
{
    stoichPtr_ = s;
    if( ode )
    {
        epsAbs_ = ode->epsAbs;
        epsRel_ = ode->epsRel;
        method_ = ode->method;
    }
#ifdef USE_GSL
    if ( ode )
    {
        sys_ = ode->gslSys;
        if ( driver_ )
            gsl_odeiv2_driver_free( driver_ );
        driver_ = gsl_odeiv2_driver_alloc_y_new( &sys_, ode->gslStep
                  , ode->initStepSize, ode->epsAbs, ode->epsRel);
    }
#endif
    VoxelPoolsBase::reinit();
}
References OdeSystem::epsAbs, epsAbs_, OdeSystem::epsRel, epsRel_, OdeSystem::method, method_, VoxelPoolsBase::reinit(), and VoxelPoolsBase::stoichPtr_.
setVolumeAndDependencies()
void VoxelPools::setVolumeAndDependencies (double vol) virtual
Handles volume change and subsequent cascading updates.
Handle volume updates. Inherited Virtual func.
Reimplemented from VoxelPoolsBase.
Definition at line 470 of file VoxelPools.cpp.
{
    VoxelPoolsBase::setVolumeAndDependencies(vol);
    updateAllRateTerms(stoichPtr_->getRateTerms(), stoichPtr_->getNumCoreRates());
}
References Stoich::getNumCoreRates(), Stoich::getRateTerms(), VoxelPoolsBase::setVolumeAndDependencies(), VoxelPoolsBase::stoichPtr_, and updateAllRateTerms().
Referenced by Ksolve::updateVoxelVol().
updateAllRateTerms()
void VoxelPools::updateAllRateTerms (const vector< RateTerm * > & rates, unsigned int numCoreRates) virtual
Updates all the rate constants from the reference rates vector.
Implements VoxelPoolsBase.
Definition at line 369 of file VoxelPools.cpp.
{
    // Clear out old rates if any
    for ( unsigned int i = 0; i < rates_.size(); ++i )
        delete( rates_[i] );
    rates_.resize(rates.size());
    for ( unsigned int i = 0; i < numCoreRates; ++i )
    {
        rates_[i] = rates[i]->copyWithVolScaling( getVolume(), 1, 1 );
    }
    for ( unsigned int i = numCoreRates; i < rates.size(); ++i )
    {
        rates_[i] = rates[i]->copyWithVolScaling(  getVolume(),
                getXreacScaleSubstrates(i-numCoreRates),
                getXreacScaleProducts(i-numCoreRates)
                );
    }
}
References RateTerm::copyWithVolScaling(), VoxelPoolsBase::getVolume(), VoxelPoolsBase::getXreacScaleProducts(), VoxelPoolsBase::getXreacScaleSubstrates(), and VoxelPoolsBase::rates_.
Referenced by setVolumeAndDependencies(), and Ksolve::updateRateTerms().
updateRates()
void VoxelPools::updateRates (const double * s, double * yprime) const
Core computation function. Updates the reaction velocities vector yprime given the current mol 'n' vector s.
Definition at line 411 of file VoxelPools.cpp.
{
    const KinSparseMatrix& N = stoichPtr_->getStoichiometryMatrix();
    vector< double > v( N.nColumns(), 0.0 );
    vector< double >::iterator j = v.begin();
    // totVar should include proxyPools only if this voxel uses them
    unsigned int totVar = stoichPtr_->getNumVarPools() + stoichPtr_->getNumProxyPools();
    // totVar should include proxyPools if this voxel does not use them
    unsigned int totInvar = stoichPtr_->getNumBufPools();
    assert( N.nColumns() == 0 || N.nRows() == stoichPtr_->getNumAllPools() );
    assert( N.nColumns() == rates_.size() );
    for ( auto i = rates_.cbegin(); i != rates_.end(); i++)
        *j++ = (**i)( s );
    for (unsigned int i = 0; i < totVar; ++i)
    {
        auto rate = N.computeRowRate( i, v );
        assert(! std::isnan(rate));
        *yprime++ = rate;
    }
    for (unsigned int i = 0; i < totInvar ; ++i)
        *yprime++ = 0.0;
}
References KinSparseMatrix::computeRowRate(), Stoich::getNumAllPools(), Stoich::getNumBufPools(), Stoich::getNumProxyPools(), Stoich::getNumVarPools(), Stoich::getStoichiometryMatrix(), SparseMatrix< T >::nColumns(), SparseMatrix< T >::nRows(), RateTerm::operator()(), VoxelPoolsBase::rates_, and VoxelPoolsBase::stoichPtr_.
Referenced by lsodaSys().
updateRateTerms()
void VoxelPools::updateRateTerms (const vector< RateTerm * > & rates, unsigned int numCoreRates, unsigned int index) virtual
updateRateTerms updates the rate consts of a belonging to the specified index on the rates vector. It does recaling and assigning using values from the internal rates vector.
Implements VoxelPoolsBase.
Definition at line 392 of file VoxelPools.cpp.
{
    // During setup or expansion of the reac system, it is possible to
    // call this function before the rates_ term is assigned. Disable.
    if ( index >= rates_.size() )
        return;
    delete( rates_[index] );
    if ( index >= numCoreRates )
    {
        rates_[index] = rates[index]->copyWithVolScaling(
                            getVolume(),
                            getXreacScaleSubstrates(index - numCoreRates),
                            getXreacScaleProducts(index - numCoreRates ) );
    }
    else
        rates_[index] = rates[index]->copyWithVolScaling(getVolume(), 1.0, 1.0);
}
References RateTerm::copyWithVolScaling(), VoxelPoolsBase::getVolume(), VoxelPoolsBase::getXreacScaleProducts(), VoxelPoolsBase::getXreacScaleSubstrates(), and VoxelPoolsBase::rates_.
Referenced by Ksolve::updateRateTerms().
updateReacVelocities()
void VoxelPools::updateReacVelocities (const double * s, vector< double > & v) const
updateReacVelocities computes the velocity v of each reaction from the vector s of pool #s. This is a utility function for programs like SteadyState that need to analyze velocity.
updateReacVelocities computes the velocity v of each reaction. This is a utility function for programs like SteadyState that need to analyze velocity.
Definition at line 440 of file VoxelPools.cpp.
{
    const KinSparseMatrix& N = stoichPtr_->getStoichiometryMatrix();
    assert( N.nColumns() == rates_.size() );
    v.clear();
    v.resize( rates_.size(), 0.0 );
    vector< RateTerm* >::const_iterator i;
    vector< double >::iterator j = v.begin();
    for ( i = rates_.begin(); i != rates_.end(); i++)
    {
        *j++ = (**i)( s );
        assert(! std::isnan(*(j-1)));
    }
}
References Stoich::getStoichiometryMatrix(), SparseMatrix< T >::nColumns(), RateTerm::operator()(), VoxelPoolsBase::rates_, and VoxelPoolsBase::stoichPtr_.
Referenced by Ksolve::getEstimatedDt().
Member Data Documentation
epsAbs_
double VoxelPools::epsAbs_ private
Definition at line 111 of file VoxelPools.h.
Referenced by setStoich().
epsRel_
double VoxelPools::epsRel_ private
Definition at line 112 of file VoxelPools.h.
Referenced by setStoich().
lsodaState_
int VoxelPools::lsodaState_ private
Definition at line 104 of file VoxelPools.h.
Referenced by advance(), reinit(), and VoxelPools().
lsodaSystem
LSODA_ODE_SYSTEM_TYPE VoxelPools::lsodaSystem private
Definition at line 103 of file VoxelPools.h.
method_
string VoxelPools::method_ private
Definition at line 113 of file VoxelPools.h.
Referenced by setStoich().
pLSODA
std::shared_ptr<LSODA> VoxelPools::pLSODA private
Definition at line 102 of file VoxelPools.h.
Referenced by advance(), reinit(), and VoxelPools().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/ksolve/VoxelPools.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/ksolve/VoxelPools.cpp