MOOSE - Multiscale Object Oriented Simulation Environment: OpFunc1Base< A > Class Template Reference
OpFunc1Base< A > Class Template Reference abstract
#include <OpFuncBase.h>
Public Member Functions
bool checkFinfo (const Finfo *s) const
const OpFunc * makeHopFunc (HopIndex hopIndex) const
virtual void op (const Eref &e, A arg) const =0
void opBuffer (const Eref &e, double *buf) const
Executes the OpFunc by converting args.
virtual void opVec (const Eref &e, const vector< A > &arg, const OpFunc1Base< A > *op) const
void opVecBuffer (const Eref &e, double *buf) const
Executes the OpFunc for all data by converting a vector of args.
string rttiType () const
Public Member Functions inherited from OpFunc
OpFunc ()
unsigned int opIndex () const
bool setIndex (unsigned int i)
Used when rebuilding the Fid->OpFunc mapping.
virtual ~OpFunc ()
Additional Inherited Members
Static Public Member Functions inherited from OpFunc
static const OpFunc * lookop (unsigned int opIndex)
static unsigned int rebuildOpIndex ()
cleans out the entire Ops vector. Returns size of orig vector.
Detailed Description
template<class A>
class OpFunc1Base< A >
Definition at line 102 of file OpFuncBase.h.
Member Function Documentation
checkFinfo()
template<class A > bool OpFunc1Base< A >::checkFinfo (const Finfo * s) const inline virtual
Implements OpFunc.
Definition at line 106 of file OpFuncBase.h.
    {
        return dynamic_cast< const SrcFinfo1< A >* >( s );
    }
makeHopFunc()
template<class A > const OpFunc * OpFunc1Base< A >::makeHopFunc (HopIndex hopIndex) const virtual
Deferred specification of function from OpFunc1Base, so it is after the declaration of the HopFunc class to which it refers.
Implements OpFunc.
Definition at line 183 of file HopFunc.h.
{
    return new HopFunc1< A >( hopIndex );
}
op()
template<class A > virtual void OpFunc1Base< A >::op (const Eref & e, A arg) const pure virtual
Implemented in GetHopFunc< A >, EpFunc1< T, A >, HopFunc1< A >, OpFunc1< T, A >, GetEpFunc< T, A >, and GetOpFunc< T, A >.
Referenced by OpFunc1Base< A >::opBuffer(), and OpFunc1Base< A >::opVecBuffer().
opBuffer()
template<class A > void OpFunc1Base< A >::opBuffer (const Eref & e, double * buf) const inline virtual
Executes the OpFunc by converting args.
Implements OpFunc.
Definition at line 115 of file OpFuncBase.h.
    {
        op( e, Conv< A >::buf2val( &buf ) );
    }
References OpFunc1Base< A >::op().
opVec()
template<class A > virtual void OpFunc1Base< A >::opVec (const Eref & e, const vector< A > & arg, const OpFunc1Base< A > * op) const inline virtual
Reimplemented in HopFunc1< A >.
Definition at line 149 of file OpFuncBase.h.
    { ; } // overridden in HopFuncs.
opVecBuffer()
template<class A > void OpFunc1Base< A >::opVecBuffer (const Eref & e, double * buf) const inline virtual
Executes the OpFunc for all data by converting a vector of args.
Reimplemented from OpFunc.
Definition at line 120 of file OpFuncBase.h.
    {
        vector< A > temp = Conv< vector< A > >::buf2val( &buf );
        Element* elm = e.element();
        if ( elm->hasFields() )   // Assignment is to field array.
        {
            unsigned int di = e.dataIndex();
            unsigned int nf = elm->numField( di -
                                             elm->localDataStart() );
            for ( unsigned int i = 0; i < nf; ++i)
            {
                Eref er( elm, di, i );
                op( er, temp[ i % temp.size() ] );
            }
        }
        else     // Assignment is to data entries.
        {
            unsigned int k = 0;
            unsigned int start = elm->localDataStart();
            unsigned int end = start + elm->numLocalData();
            for ( unsigned int i = start; i < end; ++i)
            {
                Eref er( elm, i, 0 );
                op( er, temp[ k % temp.size() ] );
                ++k;
            }
        }
    }
References Eref::dataIndex(), Eref::element(), Eref::Eref(), Element::hasFields(), Element::localDataStart(), Element::numField(), Element::numLocalData(), and OpFunc1Base< A >::op().
rttiType()
template<class A > string OpFunc1Base< A >::rttiType () const inline virtual
Implements OpFunc.
Reimplemented in ProcOpFunc< T >.
Definition at line 153 of file OpFuncBase.h.
    {
        return Conv< A >::rttiType();
    }
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/basecode/SrcFinfo.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/basecode/OpFuncBase.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/basecode/HopFunc.h