MOOSE - Multiscale Object Oriented Simulation Environment: MgBlock Class Reference
MgBlock Class Reference
#include <MgBlock.h>
Public Member Functions
double getCMg () const
double getKMg_A () const
double getKMg_B () const
double getZk () const
MgBlock ()
void origChannel (const Eref &e, double Gk, double Ek)
void setCMg (double CMg)
void setKMg_A (double Gbar)
void setKMg_B (double Ek)
void setZk (double Zk)
void vProcess (const Eref &e, ProcPtr p)
void vReinit (const Eref &e, ProcPtr p)
Public Member Functions inherited from ChanCommon
ChanCommon ()
double getGbar () const
Utility function to acces Gbar.
double getVm () const
Utility function to access Vm.
void sendProcessMsgs (const Eref &e, const ProcPtr info)
void sendReinitMsgs (const Eref &e, const ProcPtr info)
void updateIk ()
double vGetEk (const Eref &e) const override
double vGetGbar (const Eref &e) const override
double vGetGk (const Eref &e) const override
double vGetIk (const Eref &e) const override
double vGetModulation (const Eref &e) const override
void vHandleVm (double Vm) override
void vSetEk (const Eref &e, double Ek) override
void vSetGbar (const Eref &e, double Gbar) override
void vSetGk (const Eref &e, double Gk) override
void vSetIk (const Eref &e, double Ic) override
void vSetModulation (const Eref &e, double modulation) override
virtual ~ChanCommon ()=0
Public Member Functions inherited from ChanBase
ChanBase ()
double getEk (const Eref &e) const
double getGbar (const Eref &e) const
double getGk (const Eref &e) const
double getIk (const Eref &e) const
double getModulation (const Eref &e) const
void handleVm (double Vm)
void process (const Eref &e, const ProcPtr info)
void reinit (const Eref &e, const ProcPtr info)
void setEk (const Eref &e, double Ek)
void setGbar (const Eref &e, double Gbar)
void setGk (const Eref &e, double Gk)
void setIk (const Eref &e, double Ic)
void setModulation (const Eref &e, double modulation)
virtual ~ChanBase ()=0
Static Public Member Functions
static const Cinfo * initCinfo ()
Static Public Member Functions inherited from ChanCommon
static const Cinfo * initCinfo ()
Specify the Class Info static variable for initialization.
Static Public Member Functions inherited from ChanBase
static SrcFinfo2< double, double > * channelOut ()
static SrcFinfo1< double > * IkOut ()
static const Cinfo * initCinfo ()
Specify the Class Info static variable for initialization.
static SrcFinfo1< double > * permeability ()
Private Attributes
double CMg_
[Mg] in mM
double KMg_A_
1/eta
double KMg_B_
1/gamma
double origGk_
double Zk_
charge
Additional Inherited Members
Protected Member Functions inherited from ChanCommon
double getModulation () const
Protected Attributes inherited from ChanCommon
double Vm_
Vm_ is input variable from compartment, used for most rates.
Detailed Description
Definition at line 16 of file MgBlock.h.
Constructor & Destructor Documentation
MgBlock()
MgBlock::MgBlock ()
Definition at line 89 of file MgBlock.cpp.
    :   Zk_( 0.0 ),
        KMg_A_( 1.0 ), // These are NOT the same as the A, B state
        KMg_B_( 1.0 ), // variables used for Exp Euler integration.
        CMg_( 1.0 ),    // Conc of Mg in mM
                origGk_(0.0)
{;}
References CMg_, KMg_A_, KMg_B_, origGk_, and Zk_.
Member Function Documentation
getCMg()
double MgBlock::getCMg () const
Definition at line 133 of file MgBlock.cpp.
{
    return CMg_;
}
References CMg_.
Referenced by initCinfo().
getKMg_A()
double MgBlock::getKMg_A () const
Definition at line 109 of file MgBlock.cpp.
{
    return KMg_A_;
}
References KMg_A_.
Referenced by initCinfo().
getKMg_B()
double MgBlock::getKMg_B () const
Definition at line 121 of file MgBlock.cpp.
{
    return KMg_B_;
}
References KMg_B_.
Referenced by initCinfo().
getZk()
double MgBlock::getZk () const
Definition at line 137 of file MgBlock.cpp.
{
    return Zk_;
}
References Zk_.
Referenced by initCinfo().
initCinfo()
const Cinfo * MgBlock::initCinfo () static
Definition at line 17 of file MgBlock.cpp.
{
    // Shared messages
    // Dest definitions
    static DestFinfo origChannel( "origChannel",
        "",
        new EpFunc2< MgBlock, double, double > (&MgBlock::origChannel )
    );
    // Field definitions
    static ValueFinfo< MgBlock, double > KMg_A( "KMg_A",
            "1/eta",
            &MgBlock::setKMg_A,
            &MgBlock::getKMg_A
        );
    static ValueFinfo< MgBlock, double > KMg_B( "KMg_B",
            "1/gamma",
            &MgBlock::setKMg_B,
            &MgBlock::getKMg_B
        );
    static ValueFinfo< MgBlock, double > CMg( "CMg",
            "[Mg] in mM",
            &MgBlock::setCMg,
            &MgBlock::getCMg
        );
    static ValueFinfo< MgBlock, double > Zk( "Zk",
            "Charge on ion",
            &MgBlock::setZk,
            &MgBlock::getZk
        );
    static Finfo* MgBlockFinfos[] =
    {
        &origChannel,   // Dest
        &KMg_A,         // Value
        &KMg_B,         // Value
        &CMg,           // Value
        &Zk,            // Value
    };
    static string doc[] =
    {
        "Name", "MgBlock",
        "Author", "Upinder S. Bhalla, 2007, NCBS",
        "Description", "MgBlock: Hodgkin-Huxley type voltage-gated Ion channel. Something "
                "like the old tabchannel from GENESIS, but also presents "
                "a similar interface as hhchan from GENESIS. ",
    };
    static Dinfo< MgBlock > dinfo;
    static Cinfo MgBlockCinfo(
        "MgBlock",
        ChanBase::initCinfo(),
        MgBlockFinfos,
        sizeof( MgBlockFinfos )/sizeof(Finfo *),
        &dinfo,
        doc,
        sizeof( doc ) / sizeof( string )
    );
    return &MgBlockCinfo;
}
References Cinfo::Cinfo(), DestFinfo::DestFinfo(), EpFunc2< T, A1, A2 >::EpFunc2(), getCMg(), getKMg_A(), getKMg_B(), getZk(), ChanBase::initCinfo(), origChannel(), setCMg(), setKMg_A(), setKMg_B(), setZk(), and ValueFinfo< T, F >::ValueFinfo().
origChannel()
void MgBlock::origChannel (const Eref & e, double Gk, double Ek)
Assign the local Vm_ to the incoming Vm from the compartment
Definition at line 178 of file MgBlock.cpp.
{
    // setGk( Gk );
    origGk_ = Gk;
    setEk( e, Ek );
}
References origGk_, and ChanBase::setEk().
Referenced by initCinfo().
setCMg()
void MgBlock::setCMg (double CMg)
Definition at line 125 of file MgBlock.cpp.
{
    if ( CMg < EPSILON ) {
        cout << "Error: CMg = " << CMg << " must be > 0. Not set.\n";
    } else {
        CMg_ = CMg;
    }
}
References CMg_, and EPSILON.
Referenced by initCinfo().
setKMg_A()
void MgBlock::setKMg_A (double Gbar)
Definition at line 101 of file MgBlock.cpp.
{
    if ( KMg_A < EPSILON ) {
        cout << "Error: KMg_A=" << KMg_A << " must be > 0. Not set.\n";
    } else {
        KMg_A_ = KMg_A;
    }
}
References EPSILON, and KMg_A_.
Referenced by initCinfo().
setKMg_B()
void MgBlock::setKMg_B (double Ek)
Definition at line 113 of file MgBlock.cpp.
{
    if ( KMg_B < EPSILON ) {
        cout << "Error: KMg_B=" << KMg_B << " must be > 0. Not set.\n";
    } else {
        KMg_B_ = KMg_B;
    }
}
References EPSILON, and KMg_B_.
Referenced by initCinfo().
setZk()
void MgBlock::setZk (double Zk)
Definition at line 141 of file MgBlock.cpp.
{
    Zk_ = Zk;
}
References Zk_.
Referenced by initCinfo().
vProcess()
void MgBlock::vProcess (const Eref & e, ProcPtr p) virtual
processFunc handles the update and calculations every clock tick. It first sends the request for evaluation of the gate variables to the respective gate objects and recieves their response immediately through a return message. This is done so that many channel instances can share the same gate lookup tables, but do so cleanly. Such messages should never go to a remote node. Then the function does its own little calculations to send back to the parent compartment through regular messages.
Implements ChanBase.
Definition at line 150 of file MgBlock.cpp.
{
    double KMg = KMg_A_ * exp(Vm_/KMg_B_);
    ChanBase::setGk( e, origGk_ * KMg / ( KMg + CMg_ ) );
    // ChanBase::setGk( ChanBase::getGk() * KMg / ( KMg + CMg_ ) );
    // Gk_ = Gk_ * KMg / (KMg + CMg_);
    updateIk();
    // send2< double, double >( e, channelSlot, Gk_, Ek_ );
    // Ik_ = Gk_ * (Ek_ - Vm_);
    sendProcessMsgs( e, info );
}
References CMg_, KMg_A_, KMg_B_, origGk_, ChanCommon::sendProcessMsgs(), ChanBase::setGk(), ChanCommon::updateIk(), and ChanCommon::Vm_.
vReinit()
void MgBlock::vReinit (const Eref & e, ProcPtr p) virtual
Reinitializes the values for the channel. This involves computing the steady-state value for the channel gates using the provided Vm from the parent compartment. It involves a similar cycle through the gates and then updates to the parent compartment as for the processFunc.
Implements ChanBase.
Definition at line 163 of file MgBlock.cpp.
{
    Zk_ = 0;
    if ( CMg_ < EPSILON || KMg_B_ < EPSILON || KMg_A_ < EPSILON ) {
        cout << "Error: MgBlock::innerReinitFunc: fields KMg_A, KMg_B, CMg\nmust be greater than zero. Resetting to 1 to avoid numerical errors\n";
        if ( CMg_ < EPSILON ) CMg_ = 1.0;
        if ( KMg_B_ < EPSILON ) KMg_B_ = 1.0;
        if ( KMg_A_ < EPSILON ) KMg_A_ = 1.0;
    }
    sendReinitMsgs( e, info );
}
References CMg_, EPSILON, KMg_A_, KMg_B_, ChanCommon::sendReinitMsgs(), and Zk_.
Member Data Documentation
CMg_
double MgBlock::CMg_ private
[Mg] in mM
Definition at line 75 of file MgBlock.h.
Referenced by getCMg(), MgBlock(), setCMg(), vProcess(), and vReinit().
KMg_A_
double MgBlock::KMg_A_ private
1/eta
Definition at line 71 of file MgBlock.h.
Referenced by getKMg_A(), MgBlock(), setKMg_A(), vProcess(), and vReinit().
KMg_B_
double MgBlock::KMg_B_ private
1/gamma
Definition at line 73 of file MgBlock.h.
Referenced by getKMg_B(), MgBlock(), setKMg_B(), vProcess(), and vReinit().
origGk_
double MgBlock::origGk_ private
Original Gk passed by NMDA channel, we keep this separate from Gk so that the computed Gk can be recorded without being overwritten by origChannel message.
Definition at line 80 of file MgBlock.h.
Referenced by MgBlock(), origChannel(), and vProcess().
Zk_
double MgBlock::Zk_ private
charge
Definition at line 69 of file MgBlock.h.
Referenced by getZk(), MgBlock(), setZk(), and vReinit().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/biophysics/MgBlock.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/biophysics/MgBlock.cpp