MOOSE - Multiscale Object Oriented Simulation Environment: SymCompartment Class Reference
SymCompartment Class Reference
#include <SymCompartment.h>
Public Member Functions
void raxialCylinder (double Ra, double Vm)
void raxialSphere (double Ra, double Vm)
void raxialSym (double Ra, double Vm)
void sumRaxial (double Ra)
SymCompartment ()
void vInitProc (const Eref &e, ProcPtr p)
void vInitReinit (const Eref &e, ProcPtr p)
void vReinit (const Eref &e, ProcPtr p)
~SymCompartment ()
Public Member Functions inherited from moose::Compartment
void cable ()
Compartment ()
virtual double vGetCm (const Eref &e) const
virtual double vGetEm (const Eref &e) const
virtual double vGetIm (const Eref &e) const
virtual double vGetInitVm (const Eref &e) const
virtual double vGetInject (const Eref &e) const
virtual double vGetRa (const Eref &e) const
virtual double vGetRm (const Eref &e) const
virtual double vGetVm (const Eref &e) const
void vHandleAxial (double Vm)
void vHandleChannel (const Eref &e, double Gk, double Ek)
void vHandleRaxial (double Ra, double Vm)
void vInjectMsg (const Eref &e, double current)
void vProcess (const Eref &e, ProcPtr p)
void vRandInject (const Eref &e, double prob, double current)
virtual void vSetCm (const Eref &e, double Cm)
virtual void vSetEm (const Eref &e, double Em)
virtual void vSetInitVm (const Eref &e, double initVm)
virtual void vSetInject (const Eref &e, double Inject)
virtual void vSetRa (const Eref &e, double Ra)
virtual void vSetRm (const Eref &e, double Rm)
virtual void vSetVm (const Eref &e, double Vm)
virtual ~Compartment ()
Public Member Functions inherited from moose::CompartmentBase
void cable ()
CompartmentBase ()
void displace (double dx, double dy, double dz)
Displaces compartment by specified distance vector.
double getCm (const Eref &e) const
vector< double > getCoords () const
double getDiameter () const
double getEm (const Eref &e) const
double getIm (const Eref &e) const
double getInitVm (const Eref &e) const
double getInject (const Eref &e) const
double getLength () const
double getRa (const Eref &e) const
double getRm (const Eref &e) const
double getVm (const Eref &e) const
double getX () const
double getX0 () const
double getY () const
double getY0 () const
double getZ () const
double getZ0 () const
void handleAxial (double Vm)
void handleChannel (const Eref &e, double Gk, double Ek)
void handleRaxial (double Ra, double Vm)
void initProc (const Eref &e, ProcPtr p)
void initReinit (const Eref &e, ProcPtr p)
void injectMsg (const Eref &e, double current)
void process (const Eref &e, ProcPtr p)
void randInject (const Eref &e, double prob, double current)
bool rangeWarning (const string &field, double value)
void reinit (const Eref &e, ProcPtr p)
void setCm (const Eref &e, double Cm)
void setCoords (vector< double > value)
void setDiameter (double diameter)
void setEm (const Eref &e, double Em)
void setGeomAndElec (const Eref &e, double length, double dia)
Scales electrical values along with setting length, dia.
void setInitVm (const Eref &e, double initVm)
void setInject (const Eref &e, double Inject)
void setLength (double length)
void setRa (const Eref &e, double Ra)
void setRm (const Eref &e, double Rm)
void setVm (const Eref &e, double Vm)
void setX (double value)
void setX0 (double value)
void setY (double value)
void setY0 (double value)
void setZ (double value)
void setZ0 (double value)
void updateLength ()
virtual void vSetSolver (const Eref &e, Id hsolve)
virtual ~CompartmentBase ()
Static Public Member Functions
static const Cinfo * initCinfo ()
Static Public Member Functions inherited from moose::Compartment
static const Cinfo * initCinfo ()
Static Public Member Functions inherited from moose::CompartmentBase
static const Cinfo * initCinfo ()
static SrcFinfo1< double > * VmOut ()
static void zombify (Element *orig, const Cinfo *zClass, Id hsolve)
Private Attributes
double coeff_
double RaSum_
Additional Inherited Members
Protected Attributes inherited from moose::Compartment
double A_
double B_
double Cm_
double Em_
double Im_
double initVm_
double inject_
double lastIm_
double Ra_
double Rm_
double sumInject_
double Vm_
Detailed Description
The SymCompartment class sets up a symmetric compartment for branched nerve calculations. Handles electronic structure and also channels. This version splits the Ra between either end of the compartment and is hence slightly cleaner than the asymmetric compartment. The default EE method is not a particularly efficient way of doing the calculations, so we should use a solver for any substantial calculations.
Definition at line 24 of file SymCompartment.h.
Constructor & Destructor Documentation
SymCompartment()
SymCompartment::SymCompartment ()
Definition at line 283 of file SymCompartment.cpp.
                              :
        coeff_(0.0),
        RaSum_(0.0)
{
    ;
}
References coeff_, and RaSum_.
~SymCompartment()
SymCompartment::~SymCompartment () inline
Definition at line 28 of file SymCompartment.h.
{;}
Member Function Documentation
initCinfo()
const Cinfo * SymCompartment::initCinfo () static
Definition at line 50 of file SymCompartment.cpp.
{
        // process and init and reinit are inherited from Compartment.
    // Dest Finfos
        static DestFinfo raxialSphere( "raxialSphere",
                "Expects Ra and Vm from other compartment. This is a special case when"
                " other compartments are evenly distributed on a spherical compartment.",
                new OpFunc2< SymCompartment, double, double >(
                &SymCompartment::raxialSphere)
        );
        static DestFinfo raxialCylinder( "raxialCylinder",
                "Expects Ra and Vm from other compartment. This is a special case when"
                " other compartments are evenly distributed on the curved surface"
                " of the cylindrical compartment, so we assume that the"
                " cylinder does not add any further resistance.",
                new OpFunc2< SymCompartment, double, double >(
                &SymCompartment::raxialCylinder)
        );
    static DestFinfo raxialSym( "raxialSym",
        "Expects Ra and Vm from other compartment.",
        new OpFunc2< SymCompartment, double, double >(
            &SymCompartment::raxialSym )
    );
    static DestFinfo sumRaxial( "sumRaxial",
        "Expects Ra from other compartment.",
        new OpFunc1< SymCompartment, double >(
        &SymCompartment::sumRaxial )
    );
    // Shared Finfos.
    // The SrcFinfos raxialOut, sumRaxialOut and requestSumAxial
    // are defined above to get them into file-wide scope.
    static Finfo* distalShared[] =
    {
            &raxialSym, &sumRaxial,// &handleSumRaxialRequest,
            distalOut(), sumRaxialOut(), //requestSumAxial()
    };
    static Finfo* proximalShared[] =
    {
            &raxialSym, &sumRaxial,
            proximalOut(), sumRaxialOut(),
    };
    static SharedFinfo proximal( "proximal",
        "This is a shared message between symmetric compartments.\n"
        "It goes from the proximal end of the current compartment to\n"
        "distal end of the compartment closer to the soma.\n",
        proximalShared, sizeof( proximalShared ) / sizeof( Finfo* )
    );
    static SharedFinfo distal( "distal",
       "This is a shared message between symmetric compartments.\n"
       "It goes from the distal end of the current compartment to the \n"
       "proximal end of one further from the soma. \n"
       "The Ra values collected from children and\n"
       "sibling nodes are used for computing the equivalent resistance \n"
       "between each pair of nodes using star-mesh transformation.\n"
       "Mathematically this is the same as the proximal message, but\n"
       "the distinction is important for traversal and clarity.\n",
        distalShared, sizeof( distalShared ) / sizeof( Finfo* )
    );
    static SharedFinfo sibling( "sibling",
        "This is a shared message between symmetric compartments.\n"
        "Conceptually, this goes from the proximal end of the current \n"
        "compartment to the proximal end of a sibling compartment \n"
        "on a branch in a dendrite. However,\n"
        "this works out to the same as a 'distal' message in terms of \n"
        "equivalent circuit.  The Ra values collected from siblings \n"
        "and parent node are used for \n"
        "computing the equivalent resistance between each pair of\n"
         "nodes using star-mesh transformation.\n",
        distalShared, sizeof( distalShared ) / sizeof( Finfo* )
    );
    static Finfo* sphereShared[] = {
            &raxialSphere,
            distalOut(),
        };
    static SharedFinfo sphere( "sphere",
        "This is a shared message between a spherical compartment \n"
        "(typically soma) and a number of evenly spaced cylindrical \n"
        "compartments, typically primary dendrites.\n"
        "The sphere contributes the usual Ra/2 to the resistance\n"
        "between itself and children. The child compartments \n"
        "do not connect across to each other\n"
        "through sibling messages. Instead they just connect to the soma\n"
        "through the 'proximalOnly' message\n",
        sphereShared, sizeof( sphereShared )/sizeof( Finfo* )
    );
    static Finfo* cylinderShared[] = {
            &raxialCylinder,
            cylinderOut(),
        };
    static SharedFinfo cylinder( "cylinder",
        "This is a shared message between a cylindrical compartment \n"
        "(typically a dendrite) and a number of evenly spaced child \n"
        "compartments, typically dendritic spines, protruding from the\n"
        "curved surface of the cylinder. We assume that the resistance\n"
        "from the cylinder curved surface to its axis is negligible.\n"
        "The child compartments do not need to connect across to each \n"
        "other through sibling messages. Instead they just connect to the\n"
        "parent dendrite through the 'proximalOnly' message\n",
        cylinderShared, sizeof( cylinderShared )/sizeof( Finfo* )
    );
    static Finfo* proximalOnlyShared[] = {
            &raxialSphere,
            proximalOut(),
        };
    static SharedFinfo proximalOnly( "proximalOnly",
        "This is a shared message between a dendrite and a parent\n"
        "compartment whose offspring are spatially separated from each\n"
        "other. For example, evenly spaced dendrites emerging from a soma\n"
        "or spines emerging from a common parent dendrite. In these cases\n"
        "the sibling dendrites do not need to connect to each other\n"
        "through 'sibling' messages. Instead they just connect to the\n"
        "parent compartment (soma or dendrite) through this message\n",
        proximalOnlyShared, sizeof( proximalOnlyShared )/sizeof( Finfo* )
    );
    static Finfo* symCompartmentFinfos[] =
    {
    // SharedFinfo definitions
        // The inherited process and init messages do not need to be
        // overridden.
        &proximal,
        &distal,
        &sibling,
        &sphere,
        &cylinder,
        &proximalOnly
    // MsgSrc definitions
    // DestFinfo definitions
    };
    // static SchedInfo schedInfo[] = { { process, 0, 0 }, { init, 0, 1 } };
    static string doc[] =
    {
        "Name", "SymCompartment",
        "Author", "Upi Bhalla; updated and documented by Subhasis Ray",
        "Description", "SymCompartment object, for branching neuron models. In symmetric\n"
                "compartments the axial resistance is equally divided on two sides of\n"
                "the node. The equivalent circuit of the passive compartment becomes:\n"
                "(NOTE: you must use a fixed-width font like Courier for correct rendition of the diagrams below)::\n"
                "                                       \n"
                "         Ra/2    B    Ra/2               \n"
                "       A-/\\/\\/\\_____/\\/\\/\\-- C           \n"
                "                 |                      \n"
                "             ____|____                  \n"
                "            |         |                 \n"
                "            |         \\                 \n"
                "            |         / Rm              \n"
                "           ---- Cm    \\                 \n"
                "           ----       /                 \n"
                "            |         |                 \n"
                "            |       _____               \n"
                "            |        ---  Em            \n"
                "            |_________|                 \n"
                "                |                       \n"
                "              __|__                     \n"
                "              /////                     \n"
                "                                       \n"
                "                                       \n\n"
                "In case of branching, the B-C part of the parent's axial resistance\n"
                "forms a Y with the A-B part of the children::\n\n"
                "                               B'              \n"
                "                               |               \n"
                "                               /               \n"
                "                               \\              \n"
                "                               /               \n"
                "                               \\              \n"
                "                               /               \n"
                "                               |A'             \n"
                "                B              |               \n"
                "  A-----/\\/\\/\\-----/\\/\\/\\------|C        \n"
                "                               |               \n"
                "                               |A\"            \n"
                "                               /               \n"
                "                               \\              \n"
                "                               /               \n"
                "                               \\              \n"
                "                               /               \n"
                "                               |               \n"
                "                               B\"             \n\n\n"
                "As per basic circuit analysis techniques, the C node is replaced using\n"
                "star-mesh transform. This requires all sibling compartments at a\n"
                "branch point to be connected via 'sibling' messages by the user (or\n"
                "by the cell reader in case of prototypes). For the same reason, the\n"
                "child compartment must be connected to the parent by\n"
                "distal-proximal message pair. The calculation of the\n"
                "coefficient for computing equivalent resistances in the mesh is done\n"
                "at reinit.",
    };
        static Dinfo< SymCompartment > dinfo;
    static Cinfo symCompartmentCinfo(
            "SymCompartment",
            moose::Compartment::initCinfo(),
            symCompartmentFinfos,
            sizeof( symCompartmentFinfos ) / sizeof( Finfo* ),
                        &dinfo,
                        doc, sizeof(doc)/sizeof(string)
    );
    return &symCompartmentCinfo;
}
References Cinfo::Cinfo(), cylinderOut(), DestFinfo::DestFinfo(), distalOut(), moose::Compartment::initCinfo(), OpFunc1< T, A >::OpFunc1(), OpFunc2< T, A1, A2 >::OpFunc2(), proximalOut(), raxialCylinder(), raxialSphere(), raxialSym(), SharedFinfo::SharedFinfo(), sumRaxial(), and sumRaxialOut().
Referenced by ReadCell::buildCompartment().
raxialCylinder()
void SymCompartment::raxialCylinder (double Ra, double Vm)
Definition at line 367 of file SymCompartment.cpp.
{
    double invR = 2.0 / Ra;
    A_ += Vm * invR;
    B_ += invR;
    Im_ += ( Vm - Vm_ ) * invR;
}
References moose::Compartment::A_, moose::Compartment::B_, moose::Compartment::Im_, and moose::Compartment::Vm_.
Referenced by initCinfo().
raxialSphere()
void SymCompartment::raxialSphere (double Ra, double Vm)
Definition at line 359 of file SymCompartment.cpp.
{
    double invR = 2.0 / ( Ra + Ra_ );
    A_ += Vm * invR;
    B_ += invR;
    Im_ += ( Vm - Vm_ ) * invR;
}
References moose::Compartment::A_, moose::Compartment::B_, moose::Compartment::Im_, moose::Compartment::Ra_, and moose::Compartment::Vm_.
Referenced by initCinfo().
raxialSym()
void SymCompartment::raxialSym (double Ra, double Vm)
Definition at line 338 of file SymCompartment.cpp.
{
    // cout << "SymCompartment " << ":: raxialSym: Ra = " << Ra << ", Vm = " << Vm << endl;
        /*
    Ra *= coeff_;
    A_ += Vm / Ra;
    B_ += 1.0 / Ra;
    Im_ += ( Vm - Vm_ ) / Ra;
    */
    double R = Ra * coeff_;
    // cout << "raxialSym:R=" << R << endl;
    A_ += Vm / R;
    B_ += 1.0 / R;
    Im_ += (Vm - Vm_) / R;
    // double invR = 2.0 / ( Ra + Ra_ );
    // A_ += Vm * invR;
    // B_ += invR;
    // Im_ += ( Vm - Vm_ ) * invR;
}
References moose::Compartment::A_, moose::Compartment::B_, coeff_, moose::Compartment::Im_, and moose::Compartment::Vm_.
Referenced by initCinfo().
sumRaxial()
void SymCompartment::sumRaxial (double Ra)
Definition at line 331 of file SymCompartment.cpp.
{
    RaSum_ += Ra_/Ra;
    coeff_ = ( 1 + RaSum_ ) / 2.0;
    // cout << "SymCompartment::sumRaxial: coeff = " << coeff_ << endl;
}
References coeff_, moose::Compartment::Ra_, and RaSum_.
Referenced by initCinfo().
vInitProc()
void SymCompartment::vInitProc (const Eref & e, ProcPtr p) virtual
The initProc function is for a second phase of 'process' operations. It sends the axial and raxial messages to other compartments. It has to be executed out of phase with the main process so that all compartments are equivalent and there is no calling order dependence in the results.
Reimplemented from moose::Compartment.
Definition at line 296 of file SymCompartment.cpp.
{
    // cout << "SymCompartment " << e.id().path() << ":: innerInitProc: A = " << A_ << ", B = " << B_ << endl;
    distalOut()->send( e, Ra_, Vm_ ); // to kids
    proximalOut()->send( e, Ra_, Vm_ ); // to parent
    cylinderOut()->send( e, 1e-6, Vm_ ); // to kids
}
References cylinderOut(), distalOut(), proximalOut(), moose::Compartment::Ra_, SrcFinfo2< T1, T2 >::send(), and moose::Compartment::Vm_.
vInitReinit()
void SymCompartment::vInitReinit (const Eref & e, ProcPtr p) virtual
Empty function to do another reinit step out of phase with the main one. Nothing needs doing there.
Reimplemented from moose::Compartment.
Definition at line 320 of file SymCompartment.cpp.
{
    // cout << "SymCompartment " << e.id().path() << ":: innerInitReinit: coeff = " << coeff_ << ", coeff2 = " << coeff2_ << endl;
    // coeff_ = 0.0;
    // coeff2_ = 0.0;
    // RaSum_ = 0.0;
    // RaSum2_ = 0.0;
    // requestSumAxial()->send( e );
    // requestSumAxial2()->send( e );
}
vReinit()
void SymCompartment::vReinit (const Eref & e, ProcPtr p) virtual
The reinit function reinitializes all fields.
Reimplemented from moose::Compartment.
Definition at line 305 of file SymCompartment.cpp.
{
    moose::Compartment::vReinit( e, p );
        // We don't want to recalculate these every time step - the request... methods are not required
        // requestSumAxial()->send( e );
        // requestSumAxial2()->send( e );
    sumRaxialOut()->send( e, Ra_ );
    // sumRaxial2Out()->send( e, Ra_ );
    // cout << "SymCompartment " << e.id().path() << ":: innerReinit: coeff = " << coeff_ << ", coeff2 = " << coeff2_ << endl;
}
References moose::Compartment::Ra_, SrcFinfo1< T >::send(), sumRaxialOut(), and moose::Compartment::vReinit().
Member Data Documentation
coeff_
double SymCompartment::coeff_ private
Definition at line 46 of file SymCompartment.h.
Referenced by raxialSym(), sumRaxial(), and SymCompartment().
RaSum_
double SymCompartment::RaSum_ private
Definition at line 47 of file SymCompartment.h.
Referenced by sumRaxial(), and SymCompartment().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/biophysics/SymCompartment.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/biophysics/SymCompartment.cpp