MOOSE - Multiscale Object Oriented Simulation Environment: SetGet6< A1, A2, A3, A4, A5, A6 > Class Template Reference
SetGet6< A1, A2, A3, A4, A5, A6 > Class Template Reference
#include <SetGet.h>
Public Member Functions
SetGet6 ()
Public Member Functions inherited from SetGet
virtual bool checkOpClass (const OpFunc *op) const =0
SetGet ()
virtual ~SetGet ()
Static Public Member Functions
static bool innerStrSet (const ObjId &dest, const string &field, const string &val)
static bool set (const ObjId &dest, const string &field, A1 arg1, A2 arg2, A3 arg3, A4 arg4, A5 arg5, A6 arg6)
Static Public Member Functions inherited from SetGet
static const OpFunc * checkSet (const string &field, ObjId &tgt, FuncId &fid)
static const vector< double * > * dispatchGet (const ObjId &tgt, FuncId tgtFid, const double *arg, unsigned int size)
Sends out request for data, and awaits its return.
static bool strGet (const ObjId &tgt, const string &field, string &ret)
static bool strSet (const ObjId &dest, const string &field, const string &val)
Detailed Description
template<class A1, class A2, class A3, class A4, class A5, class A6>
class SetGet6< A1, A2, A3, A4, A5, A6 >
SetGet6 handles 6-argument Sets. It does not deal with Gets.
Definition at line 870 of file SetGet.h.
Constructor & Destructor Documentation
SetGet6()
template<class A1 , class A2 , class A3 , class A4 , class A5 , class A6 > SetGet6< A1, A2, A3, A4, A5, A6 >::SetGet6 () inline
Definition at line 874 of file SetGet.h.
    {
        ;
    }
Member Function Documentation
innerStrSet()
template<class A1 , class A2 , class A3 , class A4 , class A5 , class A6 > static bool SetGet6< A1, A2, A3, A4, A5, A6 >::innerStrSet (const ObjId & dest, const string & field, const string & val) inline static
Blocking call using string conversion.
Definition at line 916 of file SetGet.h.
    {
        A1 arg1;
        A2 arg2;
        A3 arg3;
        A4 arg4;
        A5 arg5;
        A6 arg6;
        string::size_type pos = val.find_first_of( "," );
        Conv< A1 >::str2val( arg1, val.substr( 0, pos ) );
        string temp = val.substr( pos + 1 );
        pos = temp.find_first_of( "," );
        Conv< A2 >::str2val( arg2, temp.substr( 0, pos ) );
        temp = temp.substr( pos + 1 );
        pos = temp.find_first_of( "," );
        Conv< A3 >::str2val( arg3, temp.substr( 0, pos ) );
        temp = temp.substr( pos + 1 );
        pos = temp.find_first_of( "," );
        Conv< A4 >::str2val( arg4, temp.substr( 0, pos ) );
        temp = temp.substr( pos + 1 );
        pos = temp.find_first_of( "," );
        Conv< A5 >::str2val( arg5, temp.substr( 0, pos ) );
        Conv< A6 >::str2val( arg6, temp.substr( pos + 1 ) );
        return set( dest, field, arg1, arg2, arg3, arg4, arg5, arg6 );
    }
References SetGet6< A1, A2, A3, A4, A5, A6 >::set().
set()
template<class A1 , class A2 , class A3 , class A4 , class A5 , class A6 > static bool SetGet6< A1, A2, A3, A4, A5, A6 >::set (const ObjId & dest, const string & field, A1 arg1, A2 arg2, A3 arg3, A4 arg4, A5 arg5, A6 arg6) inline static
Blocking, typed 'Set' call
Definition at line 882 of file SetGet.h.
    {
        FuncId fid;
        ObjId tgt( dest );
        const OpFunc* func = checkSet( field, tgt, fid );
        const OpFunc6Base< A1, A2, A3, A4, A5, A6 >* op =
            dynamic_cast< const OpFunc6Base< A1, A2, A3, A4, A5, A6 >* >( func);
        if ( op )
        {
            if ( tgt.isOffNode() )
            {
                const OpFunc* op2 = op->makeHopFunc(
                                        HopIndex( op->opIndex(), MooseSetHop ) );
                const OpFunc6Base< A1, A2, A3, A4, A5, A6 >* hop =
                    dynamic_cast< const OpFunc6Base< A1, A2, A3, A4, A5, A6 >* >( op2 );
                hop->op( tgt.eref(), arg1, arg2, arg3, arg4, arg5, arg6 );
                delete op2;
                if ( tgt.isGlobal() )
                    op->op( tgt.eref(), arg1, arg2, arg3, arg4, arg5, arg6 );
                return true;
            }
            else
            {
                op->op( tgt.eref(), arg1, arg2, arg3, arg4, arg5, arg6);
                return true;
            }
        }
        return 0;
    }
References SetGet::checkSet(), ObjId::eref(), ObjId::isGlobal(), ObjId::isOffNode(), MooseSetHop, and ObjId::ObjId().
Referenced by Shell::doAddMsg(), Shell::doCreate(), and SetGet6< A1, A2, A3, A4, A5, A6 >::innerStrSet().
The documentation for this class was generated from the following file:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/basecode/SetGet.h