MOOSE - Multiscale Object Oriented Simulation Environment: Stats Class Reference
Stats Class Reference
#include <Stats.h>
Public Member Functions
void doWindowCalculation () const
double getMean () const
unsigned int getNum () const
double getSdev () const
double getSum () const
unsigned int getWindowLength () const
double getWmean () const
unsigned int getWnum () const
double getWsdev () const
double getWsum () const
void innerWindowCalculation ()
void input (double v)
void process (const Eref &e, ProcPtr p)
void reinit (const Eref &e, ProcPtr p)
void setWindowLength (unsigned int len)
Stats ()
virtual void vProcess (const Eref &e, ProcPtr p)
Virtual func for handling process calls for derived classes.
virtual void vReinit (const Eref &e, ProcPtr p)
Static Public Member Functions
static const Cinfo * initCinfo ()
Private Attributes
bool isWindowDirty_
double lastt_
double mean_
unsigned int num_
vector< double > samples_
double sdev_
double sum_
double sumsq_
double wmean_
unsigned int wnum_
double wsdev_
double wsum_
Detailed Description
Definition at line 12 of file Stats.h.
Constructor & Destructor Documentation
Stats()
Stats::Stats ()
Definition at line 134 of file Stats.cpp.
    :
    mean_( 0.0 ), sdev_( 0.0 ), sum_( 0.0 ), num_( 0 ),
    wmean_( 0.0 ), wsdev_( 0.0 ), wsum_( 0.0 ), wnum_( 0 ),
    sumsq_( 0.0 ), isWindowDirty_( true )
{
    ;
}
References isWindowDirty_, mean_, num_, sdev_, sum_, sumsq_, wmean_, wnum_, wsdev_, and wsum_.
Referenced by SpikeStats::SpikeStats().
Member Function Documentation
doWindowCalculation()
void Stats::doWindowCalculation () const
Definition at line 262 of file Stats.cpp.
{
    Stats* temp = const_cast< Stats* >( this );
    temp->innerWindowCalculation();
}
References innerWindowCalculation().
Referenced by getWmean(), getWnum(), getWsdev(), and getWsum().
getMean()
double Stats::getMean () const
Definition at line 197 of file Stats.cpp.
{
    if ( num_ > 0 )
        return sum_ / num_;
    return 0.0;
}
References num_, and sum_.
Referenced by initCinfo().
getNum()
unsigned int Stats::getNum () const
Definition at line 216 of file Stats.cpp.
{
    return num_;
}
References num_.
Referenced by initCinfo().
getSdev()
double Stats::getSdev () const
Definition at line 204 of file Stats.cpp.
{
    if ( num_ > 0 )
        return sqrt( ( sumsq_ - sum_ * sum_ / num_ ) / num_ );
    return 0.0;
}
References num_, sum_, and sumsq_.
Referenced by initCinfo().
getSum()
double Stats::getSum () const
Definition at line 211 of file Stats.cpp.
{
    return sum_;
}
References sum_.
Referenced by initCinfo().
getWindowLength()
unsigned int Stats::getWindowLength () const
Definition at line 255 of file Stats.cpp.
{
    return samples_.size();
}
References samples_.
Referenced by initCinfo().
getWmean()
double Stats::getWmean () const
Definition at line 221 of file Stats.cpp.
{
    doWindowCalculation();
    return wmean_;
}
References doWindowCalculation(), and wmean_.
Referenced by initCinfo().
getWnum()
unsigned int Stats::getWnum () const
Definition at line 239 of file Stats.cpp.
{
    doWindowCalculation();
    return wnum_;
}
References doWindowCalculation(), and wnum_.
Referenced by initCinfo().
getWsdev()
double Stats::getWsdev () const
Definition at line 227 of file Stats.cpp.
{
    doWindowCalculation();
    return wsdev_;
}
References doWindowCalculation(), and wsdev_.
Referenced by initCinfo().
getWsum()
double Stats::getWsum () const
Definition at line 233 of file Stats.cpp.
{
    doWindowCalculation();
    return wsum_;
}
References doWindowCalculation(), and wsum_.
Referenced by initCinfo().
initCinfo()
const Cinfo * Stats::initCinfo () static
Definition at line 21 of file Stats.cpp.
{
        // Field Definitions
        static ReadOnlyValueFinfo< Stats, double > mean(
            "mean",
            "Mean of all sampled values or of spike rate.",
            &Stats::getMean
        );
        static ReadOnlyValueFinfo< Stats, double > sdev(
            "sdev",
            "Standard Deviation of all sampled values, or of rate.",
            &Stats::getSdev
        );
        static ReadOnlyValueFinfo< Stats, double > sum(
            "sum",
            "Sum of all sampled values, or total number of spikes.",
            &Stats::getSum
        );
        static ReadOnlyValueFinfo< Stats, unsigned int > num(
            "num",
            "Number of all sampled values, or total number of spikes.",
            &Stats::getNum
        );
        static ValueFinfo< Stats, unsigned int > windowLength(
            "windowLength",
            "Number of bins for windowed stats. "
            "Ignores windowing if this value is zero. ",
            &Stats::setWindowLength,
            &Stats::getWindowLength
        );
        static ReadOnlyValueFinfo< Stats, double > wmean(
            "wmean",
            "Mean of sampled values or of spike rate within window.",
            &Stats::getWmean
        );
        static ReadOnlyValueFinfo< Stats, double > wsdev(
            "wsdev",
            "Standard Deviation of sampled values, or rate, within window.",
            &Stats::getWsdev
        );
        static ReadOnlyValueFinfo< Stats, double > wsum(
            "wsum",
            "Sum of all sampled values, or total number of spikes, within window.",
            &Stats::getWsum
        );
        static ReadOnlyValueFinfo< Stats, unsigned int > wnum(
            "wnum",
            "Number of all sampled values, or total number of spikes, "
            "within window.",
            &Stats::getWnum
        );
        // MsgDest Definitions
        static DestFinfo process( "process",
            "Handles process call",
            new ProcOpFunc< Stats >( &Stats::process ) );
        static DestFinfo reinit( "reinit",
            "Handles reinit call",
            new ProcOpFunc< Stats >( &Stats::reinit ) );
        static DestFinfo input( "input",
            "Handles continuous value input as a time-series. "
            "Multiple inputs are allowed, they will be merged. ",
            new OpFunc1< Stats, double >( &Stats::input ) );
        // SharedFinfo Definitions
        static Finfo* procShared[] = {
            &process, &reinit
        };
        static SharedFinfo proc( "proc",
            "Shared message for process and reinit",
            procShared, sizeof( procShared ) / sizeof( const Finfo* )
        );
    static Finfo* statsFinfos[] = {
        &mean,  // ReadOnlyValue
        &sdev,  // ReadOnlyValue
        &sum,   // ReadOnlyValue
        &num,   // ReadOnlyValue
        &wmean, // ReadOnlyValue
        &wsdev, // ReadOnlyValue
        &wsum,  // ReadOnlyValue
        &wnum,  // ReadOnlyValue
        &windowLength,  // Value
        &input,     // DestFinfo
        requestOut(),       // SrcFinfo
        &proc       // SharedFinfo
    };
    static Dinfo< Stats > dinfo;
    static Cinfo statsCinfo (
        "Stats",
        Neutral::initCinfo(),
        statsFinfos,
        sizeof( statsFinfos ) / sizeof ( Finfo* ),
        &dinfo
    );
    return &statsCinfo;
}
References Cinfo::Cinfo(), DestFinfo::DestFinfo(), getMean(), getNum(), getSdev(), getSum(), getWindowLength(), getWmean(), getWnum(), getWsdev(), getWsum(), Neutral::initCinfo(), input(), OpFunc1< T, A >::OpFunc1(), process(), ProcOpFunc< T >::ProcOpFunc(), ReadOnlyValueFinfo< T, F >::ReadOnlyValueFinfo(), reinit(), requestOut(), setWindowLength(), SharedFinfo::SharedFinfo(), and ValueFinfo< T, F >::ValueFinfo().
Referenced by SpikeStats::initCinfo().
innerWindowCalculation()
void Stats::innerWindowCalculation ()
Definition at line 268 of file Stats.cpp.
{
    if ( isWindowDirty_ ) {
        double wsumsq = 0.0;
        wsum_ = 0.0;
        unsigned int max = samples_.size();
        if ( max > num_ )
            max = num_;
        for ( unsigned int i = 0; i < max; ++i ) {
            wsum_ += samples_[i];
            wsumsq += samples_[i] * samples_[i];
        }
        if ( max > 0 ) {
            wmean_ = wsum_ / max;
            wsdev_ = sqrt( ( wsumsq - wsum_ * wsum_ / max ) / max );
        }
        wnum_ = max;
        isWindowDirty_ = false;
    }
}
References isWindowDirty_, num_, samples_, wmean_, wnum_, wsdev_, and wsum_.
Referenced by doWindowCalculation().
input()
void Stats::input (double v)
Definition at line 183 of file Stats.cpp.
{
    sum_ += v;
    sumsq_ += v * v;
    if ( samples_.size() > 0 )
        samples_[ num_ % samples_.size() ] = v;
    ++num_;
    isWindowDirty_ = true;
}
References isWindowDirty_, num_, samples_, sum_, and sumsq_.
Referenced by initCinfo(), SpikeStats::vProcess(), and vProcess().
process()
void Stats::process (const Eref & e, ProcPtr p)
Definition at line 147 of file Stats.cpp.
{
    this->vProcess( e, p );
}
References vProcess().
Referenced by initCinfo().
reinit()
void Stats::reinit (const Eref & e, ProcPtr p)
Definition at line 161 of file Stats.cpp.
{
    this->vReinit( e, p );
}
References vReinit().
Referenced by initCinfo().
setWindowLength()
void Stats::setWindowLength (unsigned int len)
Definition at line 245 of file Stats.cpp.
{
    if ( len < 1e6 ) {
        samples_.resize( len, 0.0 );
        isWindowDirty_ = true;
    } else {
        samples_.resize( 0 );
    }
}
References isWindowDirty_, and samples_.
Referenced by initCinfo().
vProcess()
void Stats::vProcess (const Eref & e, ProcPtr p) virtual
Virtual func for handling process calls for derived classes.
Reimplemented in SpikeStats.
Definition at line 152 of file Stats.cpp.
{
    vector< double > v;
    requestOut()->send( e, &v );
    for ( vector< double >::const_iterator
                    i = v.begin(); i != v.end(); ++i )
        input( *i );
}
References input(), requestOut(), and SrcFinfo1< T >::send().
Referenced by process().
vReinit()
void Stats::vReinit (const Eref & e, ProcPtr p) virtual
Reimplemented in SpikeStats.
Definition at line 166 of file Stats.cpp.
{
    mean_ = 0.0;
    sdev_ = 0.0;
    sum_ = 0.0;
    num_ = 0;
    sumsq_ = 0.0;
    wmean_ = 0.0;
    wsdev_ = 0.0;
    wsum_ = 0.0;
    wnum_ = 0;
    samples_.assign( samples_.size(), 0.0 );
}
References mean_, num_, samples_, sdev_, sum_, sumsq_, wmean_, wnum_, wsdev_, and wsum_.
Referenced by reinit(), and SpikeStats::vReinit().
Member Data Documentation
isWindowDirty_
bool Stats::isWindowDirty_ private
Definition at line 66 of file Stats.h.
Referenced by innerWindowCalculation(), input(), setWindowLength(), and Stats().
lastt_
double Stats::lastt_ private
Definition at line 64 of file Stats.h.
mean_
double Stats::mean_ private
Definition at line 55 of file Stats.h.
Referenced by Stats(), and vReinit().
num_
unsigned int Stats::num_ private
Definition at line 58 of file Stats.h.
Referenced by getMean(), getNum(), getSdev(), innerWindowCalculation(), input(), Stats(), and vReinit().
samples_
vector< double > Stats::samples_ private
Definition at line 65 of file Stats.h.
Referenced by getWindowLength(), innerWindowCalculation(), input(), setWindowLength(), and vReinit().
sdev_
double Stats::sdev_ private
Definition at line 56 of file Stats.h.
Referenced by Stats(), and vReinit().
sum_
double Stats::sum_ private
Definition at line 57 of file Stats.h.
Referenced by getMean(), getSdev(), getSum(), input(), Stats(), and vReinit().
sumsq_
double Stats::sumsq_ private
Definition at line 63 of file Stats.h.
Referenced by getSdev(), input(), Stats(), and vReinit().
wmean_
double Stats::wmean_ private
Definition at line 59 of file Stats.h.
Referenced by getWmean(), innerWindowCalculation(), Stats(), and vReinit().
wnum_
unsigned int Stats::wnum_ private
Definition at line 62 of file Stats.h.
Referenced by getWnum(), innerWindowCalculation(), Stats(), and vReinit().
wsdev_
double Stats::wsdev_ private
Definition at line 60 of file Stats.h.
Referenced by getWsdev(), innerWindowCalculation(), Stats(), and vReinit().
wsum_
double Stats::wsum_ private
Definition at line 61 of file Stats.h.
Referenced by getWsum(), innerWindowCalculation(), Stats(), and vReinit().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/builtins/Stats.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/builtins/Stats.cpp