MOOSE - Multiscale Object Oriented Simulation Environment: Conv< string > Class Reference
Conv< string > Class Reference
#include <Conv.h>
Static Public Member Functions
static const string buf2val (double **buf)
static string rttiType ()
static unsigned int size (const string &val)
static void str2val (string &val, const string &s)
static void val2buf (const string &val, double **buf)
static void val2str (string &s, const string &val)
Detailed Description
This stores the data as the equivalent of a char* string, terminated with the usual \0, but allocates it as a double[].
Definition at line 164 of file Conv.h.
Member Function Documentation
buf2val()
static const string Conv< string >::buf2val (double ** buf) inline static
Definition at line 181 of file Conv.h.
{
            static string ret;
            ret = reinterpret_cast< const char* >( *buf );
            *buf += size( ret );
            return ret;
        }
References size().
rttiType()
static string Conv< string >::rttiType () inline static
Definition at line 208 of file Conv.h.
{
            return "string";
        }
size()
static unsigned int Conv< string >::size (const string & val) inline static
This is the size used in the serialized form, as a double* Note that we do some ugly stuff to get alignment on 8-byte boundaries. We need to have strlen + 1 as a minimum.
Definition at line 173 of file Conv.h.
        {
            // extra char for termination of the string.
            return 1 + val.length() / sizeof( double );
        }
Referenced by buf2val(), and val2buf().
str2val()
static void Conv< string >::str2val (string & val, const string & s) inline static
Definition at line 200 of file Conv.h.
{
            val = s;
        }
val2buf()
static void Conv< string >::val2buf (const string & val, double ** buf) inline static
Converts data contents into double* buf. Buf must be allocated ahead of time. Returns size of value. Needs to be specialized for variable size and pointer-containing types T.
Definition at line 194 of file Conv.h.
{
            char* temp = reinterpret_cast< char* >( *buf );
            strcpy( temp, val.c_str() );
            *buf += size( val );
        }
References size().
val2str()
static void Conv< string >::val2str (string & s, const string & val) inline static
Definition at line 204 of file Conv.h.
{
            s = val;
        }
The documentation for this class was generated from the following file:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/basecode/Conv.h