MOOSE - Multiscale Object Oriented Simulation Environment: nuParser Class Reference
nuParser Class Reference
Public Types
enum valArgs {
EXPR , P , G , EL ,
LEN , DIA , MAXP , MAXG ,
MAXL , X , Y , Z ,
OLDVAL
}
Defines the order of arguments in the val array.
Public Member Functions
double eval (vector< double >::const_iterator arg0)
nuParser (const string &expr)
Public Member Functions inherited from moose::MooseParser
void ClearAll ()
void ClearVariables ()
bool CompileExpr ()
void DefineConst (const string &cname, const double val)
void DefineFun1 (const string &funcName, double(&func)(double))
bool DefineVar (const string varName, double *const v)
double Derivative (const string &name, unsigned int nth=1) const
double Diff (const double a, const double b) const
double Eval (bool check=false) const
double GetConst (const string &name) const
Parser::varmap_type GetConstants () const
const string & GetExpr () const
Parser::symbol_table_t & GetSymbolTable ()
double GetVarValue (const string &name) const
bool IsConst (const string &name) const
MooseParser ()
bool ParseVariables (const string &expr, vector< string > &vars)
Internal function to do a first pass of parsing to obtain variable names.
void PrintSymbolTable () const
bool SetExpr (const string &expr)
~MooseParser ()
Static Public Member Functions
static double H (double arg)
Static Public Member Functions inherited from moose::MooseParser
static double Fmod (double a, double b)
static double Ln (double v)
static double Rand ()
static double Rand2 (double a, double b)
static string Reformat (const string user_expr)
static double SRand (double seed)
static double SRand2 (double a, double b, double seed)
Public Attributes
double dia
double g
double L
double len
double maxG
double maxL
double maxP
double oldVal
double p
bool useOldVal
double x
double y
double z
Static Public Attributes
static const unsigned int numVal = 13
Detailed Description
Definition at line 27 of file Neuron.cpp.
Member Enumeration Documentation
valArgs
enum nuParser::valArgs
Defines the order of arguments in the val array.
Enumerator
EXPR
P
G
EL
LEN
DIA
MAXP
MAXG
MAXL
X
Y
Z
OLDVAL
Definition at line 67 of file Neuron.cpp.
                 { EXPR, P, G, EL, LEN, DIA, MAXP, MAXG, MAXL,
                   X, Y, Z, OLDVAL
                 };
Constructor & Destructor Documentation
nuParser()
nuParser::nuParser (const string & expr) inline
Definition at line 30 of file Neuron.cpp.
                                  :
        moose::MooseParser(),
        p(0.0), // geometrical path distance wound through dendrite
        g(0.0), // geometrical path distance direct from soma.
        L(0.0), // electrical distance arg
        len(0.0), // Length of compt in metres
        dia(0.0), // Diameter of compt in metres
        maxP(0.0), // Maximum value of *p* for this neuron.
        maxG(0.0), // Maximum value of *g* for this neuron.
        maxL(0.0), // Maximum value of *L* for this neuron.
        x(0.0), // X position of segment.
        y(0.0), // Y position of segment.
        z(0.0), // Z position of segment.
        oldVal(0.0), // Original value of field, if needed.
        useOldVal( false ) // is the 'orig' field needed?
    {
        DefineVar( "p",      &p );
        DefineVar( "g",      &g );
        DefineVar( "L",      &L );
        DefineVar( "len",    &len );
        DefineVar( "dia",    &dia );
        DefineVar( "maxP",   &maxP );
        DefineVar( "maxG",   &maxG );
        DefineVar( "maxL",   &maxL );
        DefineVar( "x",      &x );
        DefineVar( "y",      &y );
        DefineVar( "z",      &z );
        DefineVar( "oldVal", &oldVal );
        DefineFun1( "H",     nuParser::H );
        if ( expr.find( "oldVal" ) != string::npos )
            useOldVal = true;
        SetExpr( expr );
    }
References moose::MooseParser::DefineFun1(), moose::MooseParser::DefineVar(), dia, g, H(), L, len, maxG, maxL, maxP, moose::MooseParser::MooseParser(), oldVal, p, moose::MooseParser::SetExpr(), useOldVal, x, y, and z.
Referenced by Neuron::evalExprForElist(), makeAngleDistrib(), makeSizeDistrib(), Neuron::makeSpacingDistrib(), setCompartmentParams(), and setMechParams().
Member Function Documentation
eval()
double nuParser::eval (vector< double >::const_iterator arg0) inline
Definition at line 76 of file Neuron.cpp.
    {
        p = *(arg0 + nuParser::P );
        g = *(arg0 + nuParser::G );
        L = *(arg0 + nuParser::EL );
        len = *(arg0 + nuParser::LEN );
        dia = *(arg0 + nuParser::DIA );
        maxP = *(arg0 + nuParser::MAXP );
        maxG = *(arg0 + nuParser::MAXG );
        maxL = *(arg0 + nuParser::MAXL );
        x = *(arg0 + nuParser::X );
        y = *(arg0 + nuParser::Y );
        z = *(arg0 + nuParser::Z );
        oldVal = *(arg0 + nuParser::OLDVAL );
        return Eval();
    }
References DIA, dia, EL, moose::MooseParser::Eval(), G, g, L, LEN, len, MAXG, maxG, MAXL, maxL, MAXP, maxP, OLDVAL, oldVal, P, p, X, x, Y, y, Z, and z.
Referenced by Neuron::evalExprForElist(), makeAngleDistrib(), makeSizeDistrib(), Neuron::makeSpacingDistrib(), setCompartmentParams(), and setMechParams().
H()
static double nuParser::H (double arg) inline static
Definition at line 71 of file Neuron.cpp.
    {
        return ( arg > 0.0);
    }
Referenced by nuParser().
Member Data Documentation
dia
double nuParser::dia
Definition at line 98 of file Neuron.cpp.
Referenced by eval(), and nuParser().
g
double nuParser::g
Definition at line 95 of file Neuron.cpp.
Referenced by eval(), and nuParser().
L
double nuParser::L
Definition at line 96 of file Neuron.cpp.
Referenced by eval(), and nuParser().
len
double nuParser::len
Definition at line 97 of file Neuron.cpp.
Referenced by eval(), and nuParser().
maxG
double nuParser::maxG
Definition at line 100 of file Neuron.cpp.
Referenced by eval(), and nuParser().
maxL
double nuParser::maxL
Definition at line 101 of file Neuron.cpp.
Referenced by eval(), and nuParser().
maxP
double nuParser::maxP
Definition at line 99 of file Neuron.cpp.
Referenced by eval(), and nuParser().
numVal
const unsigned int nuParser::numVal = 13 static
Definition at line 93 of file Neuron.cpp.
Referenced by buildFromProto(), Neuron::evalExprForElist(), Neuron::getExprElist(), makeAngleDistrib(), makeSizeDistrib(), Neuron::makeSpacingDistrib(), setCompartmentParams(), and setMechParams().
oldVal
double nuParser::oldVal
Definition at line 105 of file Neuron.cpp.
Referenced by eval(), and nuParser().
p
double nuParser::p
Definition at line 94 of file Neuron.cpp.
Referenced by eval(), and nuParser().
useOldVal
bool nuParser::useOldVal
Definition at line 106 of file Neuron.cpp.
Referenced by nuParser().
x
double nuParser::x
Definition at line 102 of file Neuron.cpp.
Referenced by eval(), and nuParser().
y
double nuParser::y
Definition at line 103 of file Neuron.cpp.
Referenced by eval(), and nuParser().
z
double nuParser::z
Definition at line 104 of file Neuron.cpp.
Referenced by eval(), and nuParser().
The documentation for this class was generated from the following file:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/biophysics/Neuron.cpp