MOOSE - Multiscale Object Oriented Simulation Environment: SpineEntry Class Reference
SpineEntry Class Reference
#include <SpineEntry.h>
Public Member Functions
void apex (double &x, double &y, double &z) const
Return coords of middle of PSD.
double diffusionLength () const
unsigned int fid () const
Returns index of self. Only a single voxel.
double headArea () const
Id headId () const
Returns Id of shaft electrical compartment.
void matchCubeMeshEntries (const ChemCompt *other, unsigned int myIndex, double granularity, vector< VoxelJunction > &ret)
void matchCubeMeshEntriesToHead (const ChemCompt *compt, unsigned int myIndex, double granularity, vector< VoxelJunction > &ret) const
Returns Id of head electrical compartment.
void matchCubeMeshEntriesToPSD (const ChemCompt *compt, unsigned int myIndex, double granularity, vector< VoxelJunction > &ret) const
unsigned int matchNeuroMeshEntriesToShaft (const ChemCompt *compt, unsigned int myIndex, double &area, double &length) const
void mid (double &x, double &y, double &z) const
Return coords of centre of spine head.
unsigned int parent () const
Returns index of parent entry located on NeuroMesh.
void positionShaftBase (double x, double y, double z)
vector< double > psdCoords () const
double rootArea () const
void setParent (unsigned int parent)
Assigns index of parent entry located on NeuroMesh.
void setVolume (double volume)
Id shaftId () const
vector< double > spineCoords () const
SpineEntry ()
SpineEntry (Id shaft, Id head, unsigned int parent)
double volume () const
Return volume of spine. Ignores shaft volume. Virtual func.
Private Attributes
CylBase head_
Shaft cylinder.
Id headId_
unsigned int parent_
head cylinder.
CylBase root_
CylBase shaft_
Anchor point on dendrite.
Id shaftId_
Id of electrical compartment in which this diffusive compt lives.
Detailed Description
Helper class for the SpineMesh. Defines a single spine.
Definition at line 17 of file SpineEntry.h.
Constructor & Destructor Documentation
SpineEntry() [1/2]
SpineEntry::SpineEntry (Id shaft, Id head, unsigned int parent)
This builds the node using info from the compartment.
Helper class for the SpineMesh. Defines the geometry of the spine and provides the innter function for mapping to CubeMeshes.
Definition at line 24 of file SpineEntry.cpp.
        :
                parent_( parent ),
                shaftId_( shaft ),
                headId_( head )
{
    double dia = Field< double >::get( shaft, "diameter" );
    double length = Field< double >::get( shaft, "length" );
    double x0 = Field< double >::get( shaft, "x0" );
    double y0 = Field< double >::get( shaft, "y0" );
    double z0 = Field< double >::get( shaft, "z0" );
    double x1 = Field< double >::get( shaft, "x" );
    double y1 = Field< double >::get( shaft, "y" );
    double z1 = Field< double >::get( shaft, "z" );
    double x2 = Field< double >::get( head, "x" );
    double y2 = Field< double >::get( head, "y" );
    double z2 = Field< double >::get( head, "z" );
    double hdia = Field< double >::get( head, "diameter" );
    double hlength = Field< double >::get( head, "length" );
    // cout << "SpineEntry: " << parent_ << " " << x0 << " " << x1 << " " << x2 << " : " << y0 << " " << y1<< " " << y2 << " : " << z0 << " " << z1 << " " << z2 << " " << hdia << endl;
    root_.setX( x0 );
    root_.setY( y0 );
    root_.setZ( z0 );
    shaft_.setX( x1 );
    shaft_.setY( y1 );
    shaft_.setZ( z1 );
    head_.setX( x2 );
    head_.setY( y2 );
    head_.setZ( z2 );
    root_.setDia( dia );
    root_.setLength( length );
    root_.setNumDivs( 0 );
    root_.setIsCylinder( true );
    shaft_.setDia( dia );
    shaft_.setLength( length );
    shaft_.setNumDivs( 1 );
    shaft_.setIsCylinder( true );
    head_.setDia( hdia );
    head_.setLength( hlength );
    head_.setNumDivs( 1 );
    head_.setIsCylinder( true );
}
References Field< A >::get(), head_, headId_, parent_, root_, CylBase::setDia(), CylBase::setIsCylinder(), CylBase::setLength(), CylBase::setNumDivs(), CylBase::setX(), CylBase::setY(), CylBase::setZ(), shaft_, and shaftId_.
Referenced by SpineMesh::handleSpineList(), and NeuroMesh::transmitSpineInfo().
SpineEntry() [2/2]
SpineEntry::SpineEntry ()
Empty constructor for vectors
Definition at line 71 of file SpineEntry.cpp.
        :
                parent_( 0 ),
                shaftId_( Id() ),
                headId_( Id() )
{
    const double defaultLength = 1e-6;
    root_.setX( 0 );
    root_.setY( 0 );
    root_.setZ( 0 );
    shaft_.setX( defaultLength );
    shaft_.setY( 0 );
    shaft_.setZ( 0 );
    head_.setX( defaultLength * 2 );
    head_.setY( 0 );
    head_.setZ( 0 );
    root_.setDia( defaultLength );
    root_.setLength( defaultLength );
    root_.setNumDivs( 0 );
    root_.setIsCylinder( true );
    shaft_.setDia( defaultLength );
    shaft_.setLength( defaultLength );
    shaft_.setNumDivs( 1 );
    shaft_.setIsCylinder( true );
    head_.setDia( defaultLength );
    head_.setLength( defaultLength );
    head_.setNumDivs( 1 );
    head_.setIsCylinder( true );
}
References head_, headId_, Id::Id(), parent_, root_, CylBase::setDia(), CylBase::setIsCylinder(), CylBase::setLength(), CylBase::setNumDivs(), CylBase::setX(), CylBase::setY(), CylBase::setZ(), shaft_, and shaftId_.
Member Function Documentation
apex()
void SpineEntry::apex (double & x, double & y, double & z) const
Return coords of middle of PSD.
diffusionLength()
double SpineEntry::diffusionLength () const
Definition at line 179 of file SpineEntry.cpp.
{
    // I've simplified this because a) it doesn't make much sense to add
    // a diffusion length with a different axial size and b) it makes the
    // resizing hugely complicated.
    // return shaft_.getLength() + 0.5 * head_.getLength();
    return shaft_.getLength();
}
References CylBase::getLength(), and shaft_.
Referenced by SpineMesh::handleSpineList(), and SpineMesh::matchNeuroMeshEntries().
fid()
unsigned int SpineEntry::fid () const
Returns index of self. Only a single voxel.
headArea()
double SpineEntry::headArea () const
headId()
Id SpineEntry::headId () const
Returns Id of shaft electrical compartment.
Definition at line 114 of file SpineEntry.cpp.
{
        return headId_;
}
References headId_.
Referenced by SpineMesh::getElecComptMap().
matchCubeMeshEntries()
void SpineEntry::matchCubeMeshEntries (const ChemCompt * other, unsigned int myIndex, double granularity, vector< VoxelJunction > & ret)
Definition at line 131 of file SpineEntry.cpp.
{
        // First flag is for curve, second is for cap of cylinder.
    head_.matchCubeMeshEntries( compt, shaft_, myIndex,
            granularity, ret, true, true );
}
References head_, CylBase::matchCubeMeshEntries(), and shaft_.
matchCubeMeshEntriesToHead()
void SpineEntry::matchCubeMeshEntriesToHead (const ChemCompt * compt, unsigned int myIndex, double granularity, vector< VoxelJunction > & ret) const
Returns Id of head electrical compartment.
Generate list of matching CubeMesh entries to the single Head entry.
Definition at line 145 of file SpineEntry.cpp.
{
    head_.matchCubeMeshEntries( compt, shaft_, myIndex,
            granularity, ret, true, false );
}
References head_, CylBase::matchCubeMeshEntries(), and shaft_.
Referenced by SpineMesh::matchCubeMeshEntries().
matchCubeMeshEntriesToPSD()
void SpineEntry::matchCubeMeshEntriesToPSD (const ChemCompt * compt, unsigned int myIndex, double granularity, vector< VoxelJunction > & ret) const
Generate list of matching CubeMeshEntries to the single PSD.
Definition at line 153 of file SpineEntry.cpp.
{
    // First flag is for curve, second is for cap of cylinder.
    head_.matchCubeMeshEntries( compt, shaft_, myIndex,
            granularity, ret, false, true );
}
References head_, CylBase::matchCubeMeshEntries(), and shaft_.
matchNeuroMeshEntriesToShaft()
unsigned int SpineEntry::matchNeuroMeshEntriesToShaft (const ChemCompt * compt, unsigned int myIndex, double & area, double & length) const
Find the matching matching NeuroMesh entry index to the root of the shaft of this spine. Also compute the area and diffusion length of the shaft.
Find the matching NeuroMesh entry index to the root of the shaft of this spine. Also compute the area and diffusion length of the shaft.
Definition at line 167 of file SpineEntry.cpp.
{
        return 0;
}
mid()
void SpineEntry::mid (double & x, double & y, double & z) const
Return coords of centre of spine head.
Definition at line 124 of file SpineEntry.cpp.
{
    x = ( shaft_.getX() + head_.getX() ) / 2.0;
    y = ( shaft_.getY() + head_.getY() ) / 2.0;
    z = ( shaft_.getZ() + head_.getZ() ) / 2.0;
}
References CylBase::getX(), CylBase::getY(), CylBase::getZ(), head_, and shaft_.
Referenced by SpineMesh::indexToSpace(), SpineMesh::nearest(), psdCoords(), and SpineMesh::vGetVoxelMidpoint().
parent()
unsigned int SpineEntry::parent () const
Returns index of parent entry located on NeuroMesh.
Definition at line 104 of file SpineEntry.cpp.
{
        return parent_;
}
References parent_.
Referenced by SpineMesh::getNeuronVoxel(), and SpineMesh::matchNeuroMeshEntries().
positionShaftBase()
void SpineEntry::positionShaftBase (double x, double y, double z)
moves Spine entry so that shaft base is now positioned at xyz.
Definition at line 248 of file SpineEntry.cpp.
{
    double dx = x - root_.getX();
    double dy = y - root_.getY();
    double dz = y - root_.getZ();
    root_.setX( x );
    root_.setY( y );
    root_.setZ( z );
    shaft_.setX( dx + shaft_.getX() );
    shaft_.setY( dy + shaft_.getY() );
    shaft_.setZ( dz + shaft_.getZ() );
    head_.setX( dx + head_.getX() );
    head_.setY( dy + head_.getY() );
    head_.setZ( dz + head_.getZ() );
}
References CylBase::getX(), CylBase::getY(), CylBase::getZ(), head_, root_, CylBase::setX(), CylBase::setY(), CylBase::setZ(), and shaft_.
psdCoords()
vector< double > SpineEntry::psdCoords () const
psdCoords is used to build the PsdMesh. The function returns 8 coords to define the psd: centre xyz direction xyz dia, diffusion distance to middle of spine Head.
Definition at line 206 of file SpineEntry.cpp.
{
    vector< double > ret( 8, 0.0 );
    double m0, m1, m2;
    mid( m0, m1, m2 );
    ret[0] = m0;
    ret[1] = m1;
    ret[2] = m2;
    ret[3] = head_.getX() - m0;
    ret[4] = head_.getY() - m1;
    ret[5] = head_.getZ() - m2;
    /*
    ret[0] = head_.getX();
    ret[1] = head_.getY();
    ret[2] = head_.getZ();
    double m0, m1, m2;
    mid( m0, m1, m2 );
    ret[3] = ret[0] - m0;
    ret[4] = ret[1] - m1;
    ret[5] = ret[2] - m2;
    */
    ret[6] = head_.getDia();
    ret[7] = sqrt( ret[3] * ret[3] + ret[4] * ret[4] + ret[5] * ret[5] );
    return ret;
}
References CylBase::getDia(), CylBase::getX(), CylBase::getY(), CylBase::getZ(), head_, and mid().
Referenced by NeuroMesh::transmitSpineInfo().
rootArea()
double SpineEntry::rootArea () const
Definition at line 174 of file SpineEntry.cpp.
{
    return root_.getDia() * root_.getDia() * PI * 0.25;
}
References CylBase::getDia(), PI, and root_.
Referenced by SpineMesh::handleSpineList(), and SpineMesh::matchNeuroMeshEntries().
setParent()
void SpineEntry::setParent (unsigned int parent)
Assigns index of parent entry located on NeuroMesh.
Definition at line 119 of file SpineEntry.cpp.
{
    parent_ = parent;
}
References parent_.
setVolume()
void SpineEntry::setVolume (double volume)
Resizes SpineEntry. Takes original shaft base and scales up from there. Retains original shaft dimensions, only the head is scaled.
Definition at line 234 of file SpineEntry.cpp.
{
    double volscale = volume / head_.volume( shaft_ );
    double linscale = pow( volscale, 1.0 / 3.0 );
    head_.setLength( head_.getLength() * linscale );
    head_.setDia( head_.getDia() * linscale );
    double dx = head_.getX() - shaft_.getX();
    double dy = head_.getY() - shaft_.getY();
    double dz = head_.getZ() - shaft_.getZ();
    head_.setX( dx * linscale + shaft_.getX() );
    head_.setY( dy * linscale + shaft_.getY() );
    head_.setZ( dz * linscale + shaft_.getZ() );
}
References CylBase::getDia(), CylBase::getLength(), CylBase::getX(), CylBase::getY(), CylBase::getZ(), head_, CylBase::setDia(), CylBase::setLength(), CylBase::setX(), CylBase::setY(), CylBase::setZ(), shaft_, and CylBase::volume().
Referenced by SpineMesh::setMeshEntryVolume(), and SpineMesh::vSetVolumeNotRates().
shaftId()
Id SpineEntry::shaftId () const
Definition at line 109 of file SpineEntry.cpp.
{
        return shaftId_;
}
References shaftId_.
spineCoords()
vector< double > SpineEntry::spineCoords () const
x1y1z1 x2y2z2 x3y3z3 r0 r1. Here x1 is farthest, x2 is junction between neck and shaft, and x3 is on the dend. r0 is radius of spine head, r1 of shaft.
Definition at line 188 of file SpineEntry.cpp.
{
    vector< double > ret( 11 );
    ret[0] = head_.getX();
    ret[1] = head_.getY();
    ret[2] = head_.getZ();
    ret[3] = shaft_.getX();
    ret[4] = shaft_.getY();
    ret[5] = shaft_.getZ();
    ret[6] = root_.getX();
    ret[7] = root_.getY();
    ret[8] = root_.getZ();
    ret[9] = head_.getDia();
    ret[10] = shaft_.getDia();
    return ret;
}
References CylBase::getDia(), CylBase::getX(), CylBase::getY(), CylBase::getZ(), head_, root_, and shaft_.
Referenced by SpineMesh::getCoordinates().
volume()
double SpineEntry::volume () const
Return volume of spine. Ignores shaft volume. Virtual func.
Definition at line 140 of file SpineEntry.cpp.
{
    return head_.volume( shaft_ );
}
References head_, shaft_, and CylBase::volume().
Referenced by SpineMesh::getMeshEntryVolume(), SpineMesh::handleSpineList(), and SpineMesh::matchNeuroMeshEntries().
Member Data Documentation
head_
CylBase SpineEntry::head_ private
Shaft cylinder.
Definition at line 113 of file SpineEntry.h.
Referenced by matchCubeMeshEntries(), matchCubeMeshEntriesToHead(), matchCubeMeshEntriesToPSD(), mid(), positionShaftBase(), psdCoords(), setVolume(), spineCoords(), SpineEntry(), SpineEntry(), and volume().
headId_
Id SpineEntry::headId_ private
Definition at line 121 of file SpineEntry.h.
Referenced by headId(), SpineEntry(), and SpineEntry().
parent_
unsigned int SpineEntry::parent_ private
head cylinder.
Index of parent entry on NeuroMesh.
Definition at line 117 of file SpineEntry.h.
Referenced by parent(), setParent(), SpineEntry(), and SpineEntry().
root_
CylBase SpineEntry::root_ private
Definition at line 111 of file SpineEntry.h.
Referenced by positionShaftBase(), rootArea(), spineCoords(), SpineEntry(), and SpineEntry().
shaft_
CylBase SpineEntry::shaft_ private
Anchor point on dendrite.
Definition at line 112 of file SpineEntry.h.
Referenced by diffusionLength(), matchCubeMeshEntries(), matchCubeMeshEntriesToHead(), matchCubeMeshEntriesToPSD(), mid(), positionShaftBase(), setVolume(), spineCoords(), SpineEntry(), SpineEntry(), and volume().
shaftId_
Id SpineEntry::shaftId_ private
Id of electrical compartment in which this diffusive compt lives.
Definition at line 120 of file SpineEntry.h.
Referenced by shaftId(), SpineEntry(), and SpineEntry().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/mesh/SpineEntry.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/mesh/SpineEntry.cpp