MOOSE - Multiscale Object Oriented Simulation Environment: Interpol Class Reference
Interpol Class Reference
#include <Interpol.h>
Public Member Functions
double getXmax () const
double getXmin () const
double getY () const
void handleInput (double x)
Interpol ()
Interpol (double xmin, double xmax)
void process (const Eref &e, ProcPtr p)
void reinit (const Eref &e, ProcPtr p)
void setXmax (double value)
void setXmin (double value)
Public Member Functions inherited from TableBase
void clearVec ()
void compareVec (vector< double > other, string op)
void compareXplot (string fname, string plotname, string op)
const vector< double > & data ()
double getOutputValue () const
string getPlotDump () const
unsigned int getVecSize () const
vector< double > getVector () const
double getY (unsigned int index) const
double interpolate (double x, double xmin, double xmax) const
void linearTransform (double scale, double offset)
void loadCSV (string fname, int startLine, int colNum, char separator)
void loadXplot (string fname, string plotname)
void loadXplotRange (string fname, string plotname, unsigned int start, unsigned int end)
double * lookupVec (unsigned int index)
void plainPlot (string file)
void setOutputValue (double val)
void setPlotDump (string v)
void setVecSize (unsigned int num)
void setVector (vector< double > val)
TableBase ()
void xplot (string file, string plotname)
Static Public Member Functions
static const Cinfo * initCinfo ()
Static Public Member Functions inherited from TableBase
static const Cinfo * initCinfo ()
Static Public Attributes
static const unsigned int MAX_DIVS
Protected Attributes
double x_
double xmax_
double xmin_
double y_
Additional Inherited Members
Protected Member Functions inherited from TableBase
vector< double > & vec ()
Detailed Description
1 Dimensional table, with interpolation. The internal vector is accessed like this: table_[ xIndex ] with the x-coordinate used as the index.
Definition at line 56 of file Interpol.h.
Constructor & Destructor Documentation
Interpol() [1/2]
Interpol::Interpol ()
Definition at line 148 of file Interpol.cpp.
                  : xmin_(0.0), xmax_(1.0)
{
}
References xmax_, and xmin_.
Interpol() [2/2]
Interpol::Interpol (double xmin, double xmax)
Definition at line 152 of file Interpol.cpp.
        : xmin_(xmin),
          xmax_(xmax)
{}
References xmax_, and xmin_.
Member Function Documentation
getXmax()
double Interpol::getXmax () const
Definition at line 180 of file Interpol.cpp.
{
    return xmax_;
}
References xmax_.
Referenced by initCinfo().
getXmin()
double Interpol::getXmin () const
Definition at line 166 of file Interpol.cpp.
{
    return xmin_;
}
References xmin_.
Referenced by initCinfo().
getY()
double Interpol::getY () const
Definition at line 185 of file Interpol.cpp.
{
    return y_;
}
References y_.
Referenced by initCinfo().
handleInput()
void Interpol::handleInput (double x)
Definition at line 209 of file Interpol.cpp.
{
    x_ = v;
}
References x_.
Referenced by initCinfo().
initCinfo()
const Cinfo * Interpol::initCinfo () static
Definition at line 61 of file Interpol.cpp.
{
    // Field Definitions
    static ValueFinfo< Interpol, double > xmin(
        "xmin",
        "Minimum value of x. x below this will result in y[0] being returned.",
        &Interpol::setXmin,
        &Interpol::getXmin
                                               );
    static ValueFinfo< Interpol, double > xmax(
        "xmax",
        "Maximum value of x. x above this will result in y[last] being"
        " returned.",
        &Interpol::setXmax,
        &Interpol::getXmax);
    static ReadOnlyValueFinfo< Interpol, double > y(
        "y",
        "Looked up value.",
        &Interpol::getY);
    // MsgDest Definitions
    static DestFinfo input( "input",
                            "Interpolates using the input as x value.",
                            new OpFunc1< Interpol, double >( &Interpol::handleInput ));
    static DestFinfo process( "process",
                              "Handles process call, updates internal time stamp.",
                              new ProcOpFunc< Interpol >( &Interpol::process ) );
    static DestFinfo reinit( "reinit",
                             "Handles reinit call.",
                             new ProcOpFunc< Interpol >( &Interpol::reinit ) );
    // SharedMsg Definitions
    static Finfo* procShared[] = {
        &process, &reinit
    };
    static SharedFinfo proc( "proc",
                             "Shared message for process and reinit",
                             procShared, sizeof( procShared ) / sizeof( const Finfo* )
                             );
    // Field Element for the vector data
    // Use a limit of 2^20 entries for the tables, about 1 million.
    static Finfo* interpolFinfos[] = {
        &xmin,      // Value
        &xmax,      // Value
        &y,
        // &xdivs,      // Value
        lookupOut(),
        &input,     // DestFinfo
        &proc,          // SharedFinfo
    };
    static string doc[] =
            {
                "Name", "Interpol",
                "Author", "Upinder Bhalla, Subhasis Ray, 2014, NCBS",
                "Description", "Interpol: Interpolation class. "
                "Handles lookup from a 1-dimensional array of real-numbered values."
                "Returns 'y' value based on given 'x' value. "
                "Can either use interpolation or roundoff to the nearest index.",
            };
    static Dinfo< Interpol > dinfo;
    static Cinfo interpolCinfo (
        "Interpol",
        TableBase::initCinfo(),
        interpolFinfos,
        sizeof( interpolFinfos ) / sizeof ( Finfo* ),
        &dinfo,
        doc,
        sizeof(doc) / sizeof(string));
    return &interpolCinfo;
}
References Cinfo::Cinfo(), DestFinfo::DestFinfo(), getXmax(), getXmin(), getY(), handleInput(), TableBase::initCinfo(), lookupOut(), OpFunc1< T, A >::OpFunc1(), process(), ProcOpFunc< T >::ProcOpFunc(), ReadOnlyValueFinfo< T, F >::ReadOnlyValueFinfo(), reinit(), setXmax(), setXmin(), SharedFinfo::SharedFinfo(), and ValueFinfo< T, F >::ValueFinfo().
process()
void Interpol::process (const Eref & e, ProcPtr p)
Definition at line 194 of file Interpol.cpp.
{
    y_ = interpolate(xmin_, xmax_, x_);
    lookupOut()->send( e, y_ );
}
References TableBase::interpolate(), lookupOut(), SrcFinfo1< T >::send(), x_, xmax_, xmin_, and y_.
Referenced by initCinfo().
reinit()
void Interpol::reinit (const Eref & e, ProcPtr p)
Definition at line 200 of file Interpol.cpp.
{
    x_ = 0.0;
}
References x_.
Referenced by initCinfo().
setXmax()
void Interpol::setXmax (double value)
Definition at line 171 of file Interpol.cpp.
{
    if (almostEqual(value, xmin_)){
        cerr << "Error: Interpol::setXmax: Xmin ~= Xmax : Assignment failed\n";
        return;
    }
    xmax_ = value;
}
References almostEqual(), xmax_, and xmin_.
Referenced by initCinfo().
setXmin()
void Interpol::setXmin (double value)
Definition at line 157 of file Interpol.cpp.
{
    if (almostEqual(value, xmax_)){
        cerr << "Error: Interpol::setXmin: Xmin ~= Xmax : Assignment failed\n";
        return;
    }
    xmin_ = value;
}
References almostEqual(), xmax_, and xmin_.
Referenced by initCinfo().
Member Data Documentation
MAX_DIVS
const unsigned int Interpol::MAX_DIVS static
Definition at line 79 of file Interpol.h.
x_
double Interpol::x_ protected
Definition at line 81 of file Interpol.h.
Referenced by handleInput(), process(), and reinit().
xmax_
double Interpol::xmax_ protected
Definition at line 83 of file Interpol.h.
Referenced by getXmax(), Interpol(), Interpol(), process(), setXmax(), and setXmin().
xmin_
double Interpol::xmin_ protected
Definition at line 82 of file Interpol.h.
Referenced by getXmin(), Interpol(), Interpol(), process(), setXmax(), and setXmin().
y_
double Interpol::y_ protected
Definition at line 84 of file Interpol.h.
Referenced by getY(), and process().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/builtins/Interpol.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/builtins/Interpol.cpp