MOOSE - Multiscale Object Oriented Simulation Environment: HopFunc0 Class Reference
HopFunc0 Class Reference
#include <HopFunc.h>
Public Member Functions
HopFunc0 (HopIndex hopIndex)
void op (const Eref &e) const
Public Member Functions inherited from OpFunc0Base
bool checkFinfo (const Finfo *s) const
const OpFunc * makeHopFunc (HopIndex hopIndex) const
void opBuffer (const Eref &e, double *buf) const
Executes the OpFunc by converting args.
string rttiType () const
Public Member Functions inherited from OpFunc
OpFunc ()
unsigned int opIndex () const
virtual void opVecBuffer (const Eref &e, double *buf) const
Executes the OpFunc for all data by converting a vector of args.
bool setIndex (unsigned int i)
Used when rebuilding the Fid->OpFunc mapping.
virtual ~OpFunc ()
Private Attributes
HopIndex hopIndex_
Additional Inherited Members
Static Public Member Functions inherited from OpFunc
static const OpFunc * lookop (unsigned int opIndex)
static unsigned int rebuildOpIndex ()
cleans out the entire Ops vector. Returns size of orig vector.
Detailed Description
Function to hop across nodes. This one has no arguments, just tells the remote object that an event has occurred.
Definition at line 29 of file HopFunc.h.
Constructor & Destructor Documentation
HopFunc0()
HopFunc0::HopFunc0 (HopIndex hopIndex) inline
Definition at line 32 of file HopFunc.h.
                : hopIndex_( hopIndex )
        {;}
References hopIndex_.
Referenced by OpFunc0Base::makeHopFunc().
Member Function Documentation
op()
void HopFunc0::op (const Eref & e) const inline virtual
Implements OpFunc0Base.
Definition at line 35 of file HopFunc.h.
        {
            addToBuf( e, hopIndex_, 0 );
            dispatchBuffers( e, hopIndex_ );
        }
References addToBuf(), dispatchBuffers(), and hopIndex_.
Member Data Documentation
hopIndex_
HopIndex HopFunc0::hopIndex_ private
Definition at line 41 of file HopFunc.h.
Referenced by HopFunc0(), and op().
The documentation for this class was generated from the following file:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/basecode/HopFunc.h