MOOSE - Multiscale Object Oriented Simulation Environment: Boundary Class Reference
Boundary Class Reference
#include <Boundary.h>
Public Member Functions
Boundary ()
double getReflectivity () const
void setReflectivity (const double v)
Static Public Member Functions
static const Cinfo * initCinfo ()
Private Attributes
double reflectivity_
Detailed Description
manages geometries and optionally keeps track of adjacent compartments, if any.
Definition at line 17 of file Boundary.h.
Constructor & Destructor Documentation
Boundary()
Boundary::Boundary ()
Definition at line 78 of file Boundary.cpp.
    : reflectivity_( 1.0 )
{
    ;
}
References reflectivity_.
Member Function Documentation
getReflectivity()
double Boundary::getReflectivity () const
Definition at line 89 of file Boundary.cpp.
{
    return reflectivity_;
}
References reflectivity_.
Referenced by initCinfo().
initCinfo()
const Cinfo * Boundary::initCinfo () static
Definition at line 16 of file Boundary.cpp.
{
        static ValueFinfo< Boundary, double > reflectivity(
            "reflectivity",
            "What happens to a molecule hitting it: bounces, absorbed, diffused?",
            &Boundary::setReflectivity,
            &Boundary::getReflectivity
        );
        /*
        static DestFinfo geometry( "geometry",
            "Size message coming from geometry object for this Boundary"
            "The three arguments are volume, area, and perimeter. The"
            "receiving function decides which it cares about."
            "The originating geometry may return zero on some of the"
            "dimensions if they do not apply",
            new UpFunc3< ChemCompt, double, double, double >( &ChemCompt::extent ) );
            */
        static DestFinfo adjacent( "adjacent",
            "Dummy message coming from adjacent compartment to current one"
            "Implies that compts are peers: do not surround each other",
            new OpFuncDummy() );
        static DestFinfo outside( "outside",
            "Dummy message coming from surrounding compartment to this one."
            "Implies that the originating compartment surrounds this one",
            new OpFuncDummy() );
        static SrcFinfo0 toAdjacent( "toAdjacent",
            "Dummy message going to adjacent compartment."
        );
        static SrcFinfo0 toInside( "toInside",
            "Dummy message going to surrounded compartment."
        );
    static Finfo* boundaryFinfos[] = {
        &reflectivity,  // Field
        // &geometry,       // DestFinfo
        &adjacent,      // DestFinfo
        &outside,       // DestFinfo
        &toAdjacent,    // SrcFinfo
        &toInside,      // SrcFinfo
    };
    static Dinfo< Boundary > dinfo;
    static Cinfo boundaryCinfo (
        "Boundary",
        // No base class, but eventually I guess it will be neutral.
        Neutral::initCinfo(),
        boundaryFinfos,
        sizeof( boundaryFinfos ) / sizeof ( Finfo* ),
        &dinfo
    );
    return &boundaryCinfo;
}
References Cinfo::Cinfo(), getReflectivity(), Neutral::initCinfo(), setReflectivity(), SrcFinfo0::SrcFinfo0(), and ValueFinfo< T, F >::ValueFinfo().
setReflectivity()
void Boundary::setReflectivity (const double v)
Definition at line 84 of file Boundary.cpp.
{
    reflectivity_ = v;
}
References reflectivity_.
Referenced by initCinfo().
Member Data Documentation
reflectivity_
double Boundary::reflectivity_ private
Boundary condition. Reflective = 1. Completely diffusive = 0 Unless it is completely reflective, there should be an adjacent compartment into which the molecules diffuse.
Definition at line 32 of file Boundary.h.
Referenced by Boundary(), getReflectivity(), and setReflectivity().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/mesh/Boundary.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/mesh/Boundary.cpp