MOOSE - Multiscale Object Oriented Simulation Environment: moose::RNG Class Reference
moose::RNG Class Reference
#include <RNG.h>
Public Member Functions
double getSeed (void)
RNG ()
void setRandomSeed ()
void setSeed (const unsigned long seed)
If seed if 0 then set seed to a random number else set seed to the given number.
double uniform (const double a, const double b)
Generate a uniformly distributed random number between a and b.
double uniform (void)
Return a uniformly distributed random number between 0 and 1 (exclusive).
~RNG ()
Private Attributes
moose::MOOSE_UNIFORM_DISTRIBUTION< double > dist_
double res_
moose::MOOSE_RNG_DEFAULT_ENGINE rng_
double seed_
Detailed Description
Definition at line 42 of file RNG.h.
Constructor & Destructor Documentation
RNG()
moose::RNG::RNG ()
Definition at line 15 of file RNG.cpp.
{
    // Setup a random seed if possible.
    setRandomSeed( );
}
References setRandomSeed().
~RNG()
moose::RNG::~RNG ()
Definition at line 21 of file RNG.cpp.
{ ; }
Member Function Documentation
getSeed()
double moose::RNG::getSeed (void)
Definition at line 30 of file RNG.cpp.
{
    return seed_;
}
References seed_.
setRandomSeed()
void moose::RNG::setRandomSeed ()
Definition at line 24 of file RNG.cpp.
{
    MOOSE_RANDOM_DEVICE rd_;
    setSeed( rd_() );
}
References setSeed().
Referenced by RNG().
setSeed()
void moose::RNG::setSeed (const unsigned long seed)
If seed if 0 then set seed to a random number else set seed to the given number.
Parameters
seed
Definition at line 41 of file RNG.cpp.
{
    seed_ = seed;
    if( seed == 0 )
    {
        MOOSE_RANDOM_DEVICE rd_;
        seed_ = rd_();
    }
    rng_.seed( seed);
}
References rng_, and seed_.
Referenced by Gsolve::Gsolve(), moose::mtseed(), GssaVoxelPools::reinit(), SparseMsg::setRandomConnectivity(), setRandomSeed(), SparseMsg::setSeed(), and ZombieCompartment::vReinit().
uniform() [1/2]
double moose::RNG::uniform (const double a, const double b)
Generate a uniformly distributed random number between a and b.
Parameters
a Lower limit (inclusive)
b Upper limit (inclusive).
Definition at line 58 of file RNG.cpp.
{
    return ( b - a ) * dist_( rng_ ) + a;
}
References dist_, and rng_.
uniform() [2/2]
double moose::RNG::uniform (void)
Return a uniformly distributed random number between 0 and 1 (exclusive).
Returns
randum number.
Definition at line 69 of file RNG.cpp.
{
    return dist_( rng_ );
}
References dist_, and rng_.
Referenced by GssaVoxelPools::advance(), approximateWithInteger(), ZombieCompartment::mtrand(), moose::mtrand(), GssaVoxelPools::pickReac(), SparseMsg::randomConnect(), and GssaVoxelPools::recalcTime().
Member Data Documentation
dist_
moose::MOOSE_UNIFORM_DISTRIBUTION<double> moose::RNG::dist_ private
Definition at line 66 of file RNG.h.
Referenced by uniform(), and uniform().
res_
double moose::RNG::res_ private
Definition at line 62 of file RNG.h.
rng_
moose::MOOSE_RNG_DEFAULT_ENGINE moose::RNG::rng_ private
Definition at line 65 of file RNG.h.
Referenced by setSeed(), uniform(), and uniform().
seed_
double moose::RNG::seed_ private
Definition at line 63 of file RNG.h.
Referenced by getSeed(), and setSeed().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/randnum/RNG.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/randnum/RNG.cpp