MOOSE - Multiscale Object Oriented Simulation Environment: PoolBase Class Reference
PoolBase Class Reference
#include <PoolBase.h>
Public Member Functions
void decrement (double val)
ObjId getCompartment (const Eref &e) const
Lookup up parent compartment of pool, return '/' if not found.
double getConc (const Eref &e) const
double getConcInit (const Eref &e) const
vector< double > getCoords (const Eref &e) const
double getDiffConst (const Eref &e) const
bool getIsBuffered (const Eref &e) const
vector< double > getMidPoint (const Eref &e) const
Return [x,y,z] of midpoint of current pool from parent compt.voxel.
double getMotorConst (const Eref &e) const
double getN (const Eref &e) const
double getNinit (const Eref &e) const
SpeciesId getSpecies (const Eref &e) const
double getVolume (const Eref &e) const
void handleMolWt (const Eref &e, double v)
void increment (double val)
void innerSetConcInit (const Eref &e, double conc)
void innerSetN (const Eref &e, double v)
void nIn (double val)
void notifyAddMsgDest (const Eref &e, ObjId msgId)
void notifyAddMsgSrc (const Eref &e, ObjId msgId)
void notifyCopy (const Eref &e, ObjId orig)
void notifyCreate (const Eref &e, ObjId parent)
void notifyDestroy (const Eref &e)
notification functions
void notifyMove (const Eref &e, ObjId newParent)
PoolBase ()
void reac (double A, double B)
void setConc (const Eref &e, double v)
void setConcInit (const Eref &e, double v)
void setDiffConst (const Eref &e, double v)
void setIsBuffered (const Eref &e, bool v)
void setMotorConst (const Eref &e, double v)
void setN (const Eref &e, double v)
void setNinit (const Eref &e, double v)
void setSolvers (const Eref &e, ObjId ksolve, ObjId dsolve)
void setSpecies (const Eref &e, SpeciesId v)
void setVolume (const Eref &e, double v)
~PoolBase ()
Static Public Member Functions
static const Cinfo * initBufPoolCinfo ()
static const Cinfo * initPoolBaseCinfo ()
static const Cinfo * initPoolCinfo ()
Protected Attributes
double concInit_
double diffConst_
KsolveBase * dsolve_
KsolveBase * ksolve_
double motorConst_
Friends
void checkVal (double time, const PoolBase *m, unsigned int size)
void forceCheckVal (double time, Element *e, unsigned int size)
void testSyncArray (unsigned int size, unsigned int numThreads, unsigned int method)
Detailed Description
The PoolBase class is the base class for molecular pools. A pool is a set of molecules of a given species, in a uniform chemical context. Note that the same species might be present in other compartments, or be handled by other solvers. PoolBase is the base class for mass-action, single particle and other numerical variants of pools. Note that in this version it only acts as an interface for the solvers.
Definition at line 27 of file PoolBase.h.
Constructor & Destructor Documentation
PoolBase()
PoolBase::PoolBase ()
Definition at line 325 of file PoolBase.cpp.
    :
        dsolve_( 0 ),
        ksolve_( 0 ),
        concInit_( 0.0 ),
        diffConst_( 0.0 ),
        motorConst_( 0.0 )
{;}
References concInit_, diffConst_, dsolve_, ksolve_, and motorConst_.
~PoolBase()
PoolBase::~PoolBase ()
Definition at line 334 of file PoolBase.cpp.
{
    // notify the ksolve and dsolve that we are going.
    ;
}
Member Function Documentation
decrement()
void PoolBase::decrement (double val)
Definition at line 349 of file PoolBase.cpp.
{
}
Referenced by initPoolBaseCinfo().
getCompartment()
ObjId PoolBase::getCompartment (const Eref & e) const
Lookup up parent compartment of pool, return '/' if not found.
Definition at line 538 of file PoolBase.cpp.
{
    return getCompt( e.id() );
}
References getCompt(), and Eref::id().
Referenced by initPoolBaseCinfo().
getConc()
double PoolBase::getConc (const Eref & e) const
Definition at line 485 of file PoolBase.cpp.
{
    return getN( e ) / ( NA * getVolume( e ) );
}
References getN(), getVolume(), and NA.
Referenced by initPoolBaseCinfo().
getConcInit()
double PoolBase::getConcInit (const Eref & e) const
Definition at line 497 of file PoolBase.cpp.
{
    return concInit_;
}
References concInit_.
Referenced by initPoolBaseCinfo().
getCoords()
vector< double > PoolBase::getCoords (const Eref & e) const
Return coords of current pool from parent compt.voxel. The entries differ depending on the kind of voxel.
Definition at line 550 of file PoolBase.cpp.
{
    ObjId compt = getCompt( e.id() );
    return LookupField< unsigned int, vector< double > >::get( compt, "voxelCoords", e.dataIndex() );
}
References Eref::dataIndex(), LookupField< L, A >::get(), getCompt(), and Eref::id().
Referenced by initPoolBaseCinfo().
getDiffConst()
double PoolBase::getDiffConst (const Eref & e) const
Definition at line 511 of file PoolBase.cpp.
{
    return diffConst_;
}
References diffConst_.
Referenced by initPoolBaseCinfo(), and Dsolve::setStoich().
getIsBuffered()
bool PoolBase::getIsBuffered (const Eref & e) const
Definition at line 624 of file PoolBase.cpp.
{
    // return e.element()->cinfo()->name() == "BufPool";
    return e.element()->cinfo() == bufPoolCinfo;
}
References bufPoolCinfo, Element::cinfo(), and Eref::element().
Referenced by initPoolBaseCinfo(), setConcInit(), and setN().
getMidPoint()
vector< double > PoolBase::getMidPoint (const Eref & e) const
Return [x,y,z] of midpoint of current pool from parent compt.voxel.
Definition at line 543 of file PoolBase.cpp.
{
    ObjId compt = getCompt( e.id() );
    return LookupField< unsigned int, vector< double > >::get( compt, "oneVoxelMidpoint", e.dataIndex() );
}
References Eref::dataIndex(), LookupField< L, A >::get(), getCompt(), and Eref::id().
Referenced by initPoolBaseCinfo().
getMotorConst()
double PoolBase::getMotorConst (const Eref & e) const
Definition at line 523 of file PoolBase.cpp.
{
    return motorConst_;
}
References motorConst_.
Referenced by initPoolBaseCinfo(), and Dsolve::setStoich().
getN()
double PoolBase::getN (const Eref & e) const
Definition at line 458 of file PoolBase.cpp.
{
    if ( ksolve_ )
        return ksolve_->getN( e );
    else
        return NA * getVolume( e ) * concInit_;
}
References concInit_, KsolveBase::getN(), getVolume(), ksolve_, and NA.
Referenced by getConc(), and initPoolBaseCinfo().
getNinit()
double PoolBase::getNinit (const Eref & e) const
Definition at line 472 of file PoolBase.cpp.
{
    return concInit_ * NA * getVolume( e );
}
References concInit_, getVolume(), and NA.
Referenced by initPoolBaseCinfo().
getSpecies()
unsigned int PoolBase::getSpecies (const Eref & e) const
Definition at line 561 of file PoolBase.cpp.
{
    return 0;
}
Referenced by initPoolBaseCinfo().
getVolume()
double PoolBase::getVolume (const Eref & e) const
Definition at line 533 of file PoolBase.cpp.
{
    return lookupVolumeFromMesh( e );
}
References lookupVolumeFromMesh().
Referenced by getConc(), getN(), getNinit(), initPoolBaseCinfo(), setConc(), setConcInit(), setN(), and setNinit().
handleMolWt()
void PoolBase::handleMolWt (const Eref & e, double v)
Definition at line 361 of file PoolBase.cpp.
{
}
Referenced by initPoolBaseCinfo().
increment()
void PoolBase::increment (double val)
Definition at line 345 of file PoolBase.cpp.
{
}
Referenced by initPoolBaseCinfo().
initBufPoolCinfo()
const Cinfo * PoolBase::initBufPoolCinfo () static
Definition at line 289 of file PoolBase.cpp.
{
    static string doc[] =
    {
        "Name", "BufPool",
        "Author", "Upi Bhalla",
        "Description", "Buffered Pool of molecules of a given species."
    };
    static Dinfo< PoolBase > dinfo;
    static Cinfo poolCinfo (
        "BufPool",
        PoolBase::initPoolBaseCinfo(),
        0,
        0,
        &dinfo,
        doc, sizeof( doc )/sizeof( string )
    );
    return &poolCinfo;
}
References Cinfo::Cinfo(), and initPoolBaseCinfo().
initPoolBaseCinfo()
const Cinfo * PoolBase::initPoolBaseCinfo () static
Definition at line 23 of file PoolBase.cpp.
{
    // Field Definitions
    static ElementValueFinfo< PoolBase, double > n(
        "n",
        "Number of molecules in pool",
        &PoolBase::setN,
        &PoolBase::getN
    );
    static ElementValueFinfo< PoolBase, double > nInit(
        "nInit",
        "Initial value of number of molecules in pool",
        &PoolBase::setNinit,
        &PoolBase::getNinit
    );
    static ElementValueFinfo< PoolBase, double > diffConst(
        "diffConst",
        "Diffusion constant of molecule",
        &PoolBase::setDiffConst,
        &PoolBase::getDiffConst
    );
    static ElementValueFinfo< PoolBase, double > motorConst(
        "motorConst",
        "Motor transport rate molecule. + is away from soma, - is "
        "towards soma. Only relevant for ZombiePool subclasses.",
        &PoolBase::setMotorConst,
        &PoolBase::getMotorConst
    );
    static ElementValueFinfo< PoolBase, double > conc(
        "conc",
        "Concentration of molecules in this pool",
        &PoolBase::setConc,
        &PoolBase::getConc
    );
    static ElementValueFinfo< PoolBase, double > concInit(
        "concInit",
        "Initial value of molecular concentration in pool",
        &PoolBase::setConcInit,
        &PoolBase::getConcInit
    );
    static ElementValueFinfo< PoolBase, double > volume(
        "volume",
        "Volume of compartment. Units are SI. "
        "Utility field, the actual volume info is "
        "stored on a volume mesh entry in the parent compartment."
        "This mapping is implicit: the parent compartment must be "
        "somewhere up the element tree, and must have matching mesh "
        "entries. If the compartment isn't"
        "available the volume is just taken as 1",
        &PoolBase::setVolume,
        &PoolBase::getVolume
    );
    static ReadOnlyElementValueFinfo< PoolBase, ObjId > compartment(
        "compartment",
        "ObjId of parent compartment of pool. "
        "If the compartment isn't"
        "available this returns the root ObjId.",
        &PoolBase::getCompartment
    );
    static ReadOnlyElementValueFinfo< PoolBase, vector< double > > coords(
        "coords",
        "coordinates of pool, based on mid-point of voxel in which it is "
        "situated. If the parent compartment isn't"
        "available this returns [0, 0, 0].",
        &PoolBase::getCoords
    );
    static ReadOnlyElementValueFinfo< PoolBase, vector< double > > midPoint(
        "midPoint",
        "mid-point of voxel in which Pool is "
        "situated. If the parent compartment isn't"
        "available this returns [0, 0, 0].",
        &PoolBase::getMidPoint
    );
    static ElementValueFinfo< PoolBase, unsigned int > speciesId(
        "speciesId",
        "Species identifier for this mol pool. Eventually link to ontology.",
        &PoolBase::setSpecies,
        &PoolBase::getSpecies
    );
    static ElementValueFinfo< PoolBase, bool > isBuffered(
        "isBuffered",
        "Flag: True if Pool is buffered. "
        "In the case of Pool and BufPool the field can be assigned, to "
        "change the type of the Pool object to BufPool, or vice versa. "
        "None of the messages are affected. "
        "This object class flip can only be done in the non-zombified "
        "form of the Pool/BufPool. In Zombies it is read-only.",
        &PoolBase::setIsBuffered,
        &PoolBase::getIsBuffered
    );
    // MsgDest Definitions
    static DestFinfo reacDest( "reacDest",
                               "Handles reaction input",
                               new OpFunc2< PoolBase, double, double >( &PoolBase::reac )
                             );
    static DestFinfo handleMolWt( "handleMolWt",
                                  "Separate finfo to assign molWt, and consequently diffusion const."
                                  "Should only be used in SharedMsg with species.",
                                  new EpFunc1< PoolBase, double >( &PoolBase::handleMolWt )
                                );
    static DestFinfo notifyCreate("notifyCreate",
                "Called when object is created. Arg is parent.",
                new EpFunc1<PoolBase, ObjId >(&PoolBase::notifyCreate));
    static DestFinfo notifyCopy("notifyCopy",
                "Called when object is created. Arg is original.",
                new EpFunc1<PoolBase, ObjId >(&PoolBase::notifyCopy));
    static DestFinfo notifyDestroy("notifyDestroy",
                "Called when object is destroyed.",
                new EpFunc0<PoolBase>(&PoolBase::notifyDestroy));
    static DestFinfo notifyMove("notifyMove",
                "Called when object is moved. Arg is new parent.",
                new EpFunc1<PoolBase, ObjId>(&PoolBase::notifyMove));
    static DestFinfo notifyAddMsgSrc("notifyAddMsgSrc",
                "Called when a message is created, current object is src. Arg is msgId.",
                new EpFunc1<PoolBase, ObjId>(&PoolBase::notifyAddMsgSrc));
    static DestFinfo notifyAddMsgDest("notifyAddMsgSrc",
                "Called when a message is created, current object is dest. Arg is msgId.",
                new EpFunc1<PoolBase, ObjId>(&PoolBase::notifyAddMsgDest));
    static DestFinfo setSolvers( "setSolvers",
                "Assigns solvers to Pool. Args: ksolve, dsolve",
                new EpFunc2< PoolBase, ObjId, ObjId >(&PoolBase::setSolvers)
    );
    // MsgDest Definitions: These three are used for non-reaction
    // calculations involving algebraically defined rate terms.
    static DestFinfo increment( "increment",
                                "Increments mol numbers by specified amount. Can be +ve or -ve",
                                new OpFunc1< PoolBase, double >( &PoolBase::increment )
                              );
    static DestFinfo decrement( "decrement",
                                "Decrements mol numbers by specified amount. Can be +ve or -ve",
                                new OpFunc1< PoolBase, double >( &PoolBase::decrement )
                              );
    static DestFinfo nIn( "nIn",
                          "Assigns the number of molecules in Pool to specified value",
                          new OpFunc1< PoolBase, double >( &PoolBase::nIn )
                        );
    // SrcFinfo Definitions
    static SrcFinfo1< double > nOut(
        "nOut",
        "Sends out # of molecules in pool on each timestep"
    );
    static SrcFinfo0 requestMolWt(
        "requestMolWt",
        "Requests Species object for mol wt"
    );
    // SharedMsg Definitions
    static Finfo* reacShared[] =
    {
        &reacDest, &nOut
    };
    static SharedFinfo reac( "reac",
                             "Connects to reaction",
                             reacShared, sizeof( reacShared ) / sizeof( const Finfo* )
                           );
    static Finfo* speciesShared[] =
    {
        &requestMolWt, &handleMolWt
    };
    static SharedFinfo species( "species",
                                "Shared message for connecting to species objects",
                                speciesShared, sizeof( speciesShared ) / sizeof ( const Finfo* )
                              );
    static Finfo* poolFinfos[] =
    {
        &n,         // Value
        &nInit,     // Value
        &diffConst, // Value
        &motorConst,    // Value
        &conc,      // Value
        &concInit,  // Value
        &volume,    // ReadOnlyElementValue
        &compartment,   // ReadOnlyElementValue
        &midPoint,  // ReadOnlyElementValue
        &coords,    // ReadOnlyElementValue
        &speciesId, // Value
        &isBuffered,    // Value
        &increment,         // DestFinfo
        &decrement,         // DestFinfo
        &nIn,               // DestFinfo
        &reac,              // SharedFinfo
        &species,           // SharedFinfo
        &notifyCreate,       // DestFinfo
        &notifyCopy,         // DestFinfo
        &notifyDestroy,     // DestFinfo
        &notifyMove,         // DestFinfo
        &notifyAddMsgSrc,    // DestFinfo
        &notifyAddMsgDest,   // DestFinfo
        &setSolvers,     // DestFinfo
    };
    static string doc[] =
    {
        "Name", "PoolBase",
        "Author", "Upi Bhalla",
        "Description", "Base class for pools."
    };
    // static ZeroSizeDinfo< int > dinfo;
    static Dinfo< PoolBase > dinfo;
    static Cinfo poolCinfo (
        "PoolBase",
        Neutral::initCinfo(),
        poolFinfos,
        sizeof( poolFinfos ) / sizeof ( Finfo* ),
        &dinfo,
        doc,
        sizeof( doc )/sizeof( string ),
        true // Ban creation as this is an abstract base class.
    );
    return &poolCinfo;
}
References Cinfo::Cinfo(), decrement(), DestFinfo::DestFinfo(), ElementValueFinfo< T, F >::ElementValueFinfo(), EpFunc0< T >::EpFunc0(), EpFunc1< T, A >::EpFunc1(), EpFunc2< T, A1, A2 >::EpFunc2(), getCompartment(), getConc(), getConcInit(), getCoords(), getDiffConst(), getIsBuffered(), getMidPoint(), getMotorConst(), getN(), getNinit(), getSpecies(), getVolume(), handleMolWt(), increment(), Neutral::initCinfo(), nIn(), notifyAddMsgDest(), notifyAddMsgSrc(), notifyCopy(), notifyCreate(), notifyDestroy(), notifyMove(), OpFunc1< T, A >::OpFunc1(), OpFunc2< T, A1, A2 >::OpFunc2(), reac(), ReadOnlyElementValueFinfo< T, F >::ReadOnlyElementValueFinfo(), setConc(), setConcInit(), setDiffConst(), setIsBuffered(), setMotorConst(), setN(), setNinit(), setSolvers(), setSpecies(), setVolume(), SharedFinfo::SharedFinfo(), SrcFinfo0::SrcFinfo0(), and SrcFinfo1< T >::SrcFinfo1().
Referenced by initBufPoolCinfo(), and initPoolCinfo().
initPoolCinfo()
const Cinfo * PoolBase::initPoolCinfo () static
Definition at line 269 of file PoolBase.cpp.
{
    static string doc[] =
    {
        "Name", "Pool",
        "Author", "Upi Bhalla",
        "Description", "Pool of molecules of a given species."
    };
    static Dinfo< PoolBase > dinfo;
    static Cinfo poolCinfo (
        "Pool",
        PoolBase::initPoolBaseCinfo(),
        0,
        0,
        &dinfo,
        doc, sizeof( doc )/sizeof( string )
    );
    return &poolCinfo;
}
References Cinfo::Cinfo(), and initPoolBaseCinfo().
innerSetConcInit()
void PoolBase::innerSetConcInit (const Eref & e, double conc)
Definition at line 439 of file PoolBase.cpp.
{
    if ( conc < 0.0 )
        conc = 0.0;
    concInit_ = conc;
    if ( ksolve_ )
        ksolve_->setConcInit( e, conc );
    if ( dsolve_ )
        dsolve_->setConcInit( e, conc );
}
References concInit_, dsolve_, ksolve_, and KsolveBase::setConcInit().
Referenced by setConcInit(), and setN().
innerSetN()
void PoolBase::innerSetN (const Eref & e, double v)
Definition at line 429 of file PoolBase.cpp.
{
    if ( v < 0.0 )
        v = 0.0;
    if ( ksolve_ )
        ksolve_->setN(e, v);
    if ( dsolve_ )
        dsolve_->setN(e, v);
}
References dsolve_, ksolve_, and KsolveBase::setN().
Referenced by setConcInit(), and setN().
nIn()
void PoolBase::nIn (double val)
Definition at line 353 of file PoolBase.cpp.
{
}
Referenced by initPoolBaseCinfo().
notifyAddMsgDest()
void PoolBase::notifyAddMsgDest (const Eref & e, ObjId msgId)
Definition at line 419 of file PoolBase.cpp.
{
    if ( ksolve_ )
        ksolve_->notifyAddMsgDestPool( e, msgId );
}
References ksolve_, and KsolveBase::notifyAddMsgDestPool().
Referenced by initPoolBaseCinfo().
notifyAddMsgSrc()
void PoolBase::notifyAddMsgSrc (const Eref & e, ObjId msgId)
Definition at line 413 of file PoolBase.cpp.
{
    if ( ksolve_ )
        ksolve_->notifyAddMsgSrcPool( e, msgId );
}
References ksolve_, and KsolveBase::notifyAddMsgSrcPool().
Referenced by initPoolBaseCinfo().
notifyCopy()
void PoolBase::notifyCopy (const Eref & e, ObjId orig)
Definition at line 386 of file PoolBase.cpp.
{
    if ( ksolve_ )
        ksolve_->notifyAddPool( e );
    if ( dsolve_ )
        dsolve_->notifyAddPool( e );
    // setNinit( e, Field< double >::get( old, "nInit" ) );
    // setN( e, Field< double >::get( old, "n" ) );
    double c = Field< double >::get( old, "concInit" );
    setConcInit( e, c );
    c = Field< double >::get( old, "conc" );
    setConc( e, c );
}
References dsolve_, Field< A >::get(), ksolve_, KsolveBase::notifyAddPool(), setConc(), and setConcInit().
Referenced by initPoolBaseCinfo().
notifyCreate()
void PoolBase::notifyCreate (const Eref & e, ObjId parent)
Definition at line 377 of file PoolBase.cpp.
{
    // cout << "Creating poolBase " << e.id().path() << endl;
    if ( ksolve_ )
        ksolve_->notifyAddPool( e );
    if ( dsolve_ )
        dsolve_->notifyAddPool( e );
}
References dsolve_, ksolve_, and KsolveBase::notifyAddPool().
Referenced by initPoolBaseCinfo().
notifyDestroy()
void PoolBase::notifyDestroy (const Eref & e)
notification functions
Definition at line 369 of file PoolBase.cpp.
{
    if ( ksolve_ )
        ksolve_->notifyRemovePool( e );
    if ( dsolve_ )
        dsolve_->notifyRemovePool( e );
}
References dsolve_, ksolve_, and KsolveBase::notifyRemovePool().
Referenced by initPoolBaseCinfo().
notifyMove()
void PoolBase::notifyMove (const Eref & e, ObjId newParent)
Definition at line 401 of file PoolBase.cpp.
{
    // cout << "Moving poolBase " << e.id().path() << " onto " << newParent.path() << endl;
    if ( ksolve_ ) {
        ksolve_->notifyRemovePool( e );
    }
    if ( dsolve_ != 0 ) {
        dsolve_->notifyRemovePool( e );
    }
    // Assign to new ksolve if newParent is a solver.
}
References dsolve_, ksolve_, and KsolveBase::notifyRemovePool().
Referenced by initPoolBaseCinfo().
reac()
void PoolBase::reac (double A, double B)
Definition at line 357 of file PoolBase.cpp.
{
}
Referenced by initPoolBaseCinfo().
setConc()
void PoolBase::setConc (const Eref & e, double v)
Definition at line 478 of file PoolBase.cpp.
{
    double n = NA * conc * getVolume( e );
    setN( e, n );
}
References getVolume(), NA, and setN().
Referenced by initPoolBaseCinfo(), and notifyCopy().
setConcInit()
void PoolBase::setConcInit (const Eref & e, double v)
Definition at line 490 of file PoolBase.cpp.
{
    innerSetConcInit( e, conc );
    if ( getIsBuffered( e ) )
        innerSetN( e, NA * getVolume( e ) * conc );
}
References getIsBuffered(), getVolume(), innerSetConcInit(), innerSetN(), and NA.
Referenced by initPoolBaseCinfo(), notifyCopy(), and setNinit().
setDiffConst()
void PoolBase::setDiffConst (const Eref & e, double v)
Definition at line 502 of file PoolBase.cpp.
{
    if ( v < 0.0 )
        v = 0.0;
    diffConst_ = v;
    if ( dsolve_ )
        dsolve_->setDiffConst( e, v );
}
References diffConst_, dsolve_, and KsolveBase::setDiffConst().
Referenced by initPoolBaseCinfo().
setIsBuffered()
void PoolBase::setIsBuffered (const Eref & e, bool v)
Functions to examine and change class between Pool and BufPool.
Changing the buffering flag changes the class between Pool and BufPool.
Definition at line 606 of file PoolBase.cpp.
{
    Element* elm = e.element();
    bool isBuf = ( elm->cinfo() == bufPoolCinfo );
    if ( v == isBuf ) return;
    if ( v ) {
        elm->replaceCinfo( bufPoolCinfo );
    } else {
        elm->replaceCinfo( poolCinfo );
    }
    if ( ksolve_ )
        ksolve_->setIsBuffered( e, v );
    if ( dsolve_ )
        dsolve_->setIsBuffered( e, v );
}
References bufPoolCinfo, Element::cinfo(), dsolve_, Eref::element(), ksolve_, poolCinfo, Element::replaceCinfo(), and KsolveBase::setIsBuffered().
Referenced by initPoolBaseCinfo().
setMotorConst()
void PoolBase::setMotorConst (const Eref & e, double v)
Definition at line 516 of file PoolBase.cpp.
{
    motorConst_ = v;
    if ( dsolve_ )
        dsolve_->setMotorConst( e, v );
}
References dsolve_, motorConst_, and KsolveBase::setMotorConst().
Referenced by initPoolBaseCinfo().
setN()
void PoolBase::setN (const Eref & e, double v)
Definition at line 450 of file PoolBase.cpp.
{
    innerSetN( e, v );
    if ( getIsBuffered( e ) ) {
        innerSetConcInit( e, v / ( NA * getVolume( e ) ) );
    }
}
References getIsBuffered(), getVolume(), innerSetConcInit(), innerSetN(), and NA.
Referenced by initPoolBaseCinfo(), and setConc().
setNinit()
void PoolBase::setNinit (const Eref & e, double v)
Definition at line 466 of file PoolBase.cpp.
{
    double c = v / ( NA * getVolume( e ) );
    setConcInit( e, c );
}
References getVolume(), NA, and setConcInit().
Referenced by initPoolBaseCinfo().
setSolvers()
void PoolBase::setSolvers (const Eref & e, ObjId ksolve, ObjId dsolve)
Definition at line 566 of file PoolBase.cpp.
{
    if ( ks == ObjId() ) {
        if ( ksolve_ )
            ksolve_->notifyRemovePool( e );
        ksolve_ = 0;
    } else if ( ! ks.bad() ) {
        string nm = ks.element()->cinfo()->name();
        if ( nm == "Ksolve" || nm == "Gsolve" ) {
            KsolveBase* k = reinterpret_cast< KsolveBase *>(ks.data() );
            if ( k && k != ksolve_ ) {
                if ( ksolve_ )
                    ksolve_->notifyRemovePool( e );
                ksolve_ = k;
                k->notifyAddPool( e );
            }
        }
    }
    if ( ds == ObjId() ) {
        if ( dsolve_ ) {
            dsolve_->notifyRemovePool( e );
        }
        dsolve_ = 0;
    } else if ( ! ds.bad() ) {
        string nm = ds.element()->cinfo()->name();
        if ( nm == "Dsolve" ) {
            KsolveBase* d = reinterpret_cast< KsolveBase *>(ds.data() );
            if ( d && d != dsolve_ ) {
                if ( dsolve_ )
                    dsolve_->notifyRemovePool( e );
                dsolve_ = d;
                d->notifyAddPool( e );
            }
        }
    }
}
References ObjId::bad(), Element::cinfo(), ObjId::data(), dsolve_, ObjId::element(), ksolve_, Cinfo::name(), KsolveBase::notifyAddPool(), KsolveBase::notifyRemovePool(), ObjId::ObjId(), and ObjId::operator==().
Referenced by initPoolBaseCinfo().
setSpecies()
void PoolBase::setSpecies (const Eref & e, SpeciesId v)
Definition at line 556 of file PoolBase.cpp.
{
    ;
}
Referenced by initPoolBaseCinfo().
setVolume()
void PoolBase::setVolume (const Eref & e, double v)
Volume is usually volume, but we also permit areal density This is obtained by looking up the corresponding spatial mesh entry in the parent compartment. If the message isn't set then it defaults to 1.0.
Definition at line 528 of file PoolBase.cpp.
{
    ; // illegal op
}
Referenced by initPoolBaseCinfo().
Friends And Related Symbol Documentation
checkVal
void checkVal (double time, const PoolBase * m, unsigned int size) friend
forceCheckVal
void forceCheckVal (double time, Element * e, unsigned int size) friend
testSyncArray
void testSyncArray (unsigned int size, unsigned int numThreads, unsigned int method) friend
Member Data Documentation
concInit_
double PoolBase::concInit_ protected
Definition at line 123 of file PoolBase.h.
Referenced by getConcInit(), getN(), getNinit(), innerSetConcInit(), and PoolBase().
diffConst_
double PoolBase::diffConst_ protected
Definition at line 124 of file PoolBase.h.
Referenced by getDiffConst(), PoolBase(), and setDiffConst().
dsolve_
KsolveBase* PoolBase::dsolve_ protected
The KsolveBase pointers hold the solvers for the PoolBase. At least one must be assigned. Field assignments propagate from the pool to whichever is assigned. Field lookups first check the dsolve, then the ksolve. The PoolBase may be managed by the diffusion solver without the involvement of the Stoich class at all. So instead of routing the zombie operations through the Stoich, we have pointers directly into the Dsolve and Ksolve.
Definition at line 120 of file PoolBase.h.
Referenced by innerSetConcInit(), innerSetN(), notifyCopy(), notifyCreate(), notifyDestroy(), notifyMove(), PoolBase(), setDiffConst(), setIsBuffered(), setMotorConst(), and setSolvers().
ksolve_
KsolveBase* PoolBase::ksolve_ protected
Definition at line 121 of file PoolBase.h.
Referenced by getN(), innerSetConcInit(), innerSetN(), notifyAddMsgDest(), notifyAddMsgSrc(), notifyCopy(), notifyCreate(), notifyDestroy(), notifyMove(), PoolBase(), setIsBuffered(), and setSolvers().
motorConst_
double PoolBase::motorConst_ protected
Definition at line 125 of file PoolBase.h.
Referenced by getMotorConst(), PoolBase(), and setMotorConst().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/kinetics/PoolBase.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/kinetics/PoolBase.cpp