MOOSE - Multiscale Object Oriented Simulation Environment: Shell Class Reference
Shell Class Reference
#include <Shell.h>
Public Member Functions
void addClockMsgs (const vector< ObjId > &list, const string &field, unsigned int tick, unsigned int msgIndex)
void destroy (const Eref &e, ObjId oid)
ObjId doAddMsg (const string &msgType, ObjId src, const string &srcField, ObjId dest, const string &destField)
Id doCopy (Id orig, ObjId newParent, string newName, unsigned int n, bool toGlobal, bool copyExtMsgs)
Returns the Id of the root of the copied tree upon success.
Id doCreate (string type, ObjId parent, string name, unsigned int numData, NodePolicy nodePolicy=MooseBlockBalance, unsigned int preferredNode=1)
Id doCreate2 (string type, ObjId parent, string name, unsigned int numData)
bool doDelete (ObjId oid)
ObjId doFind (const string &path) const
Id doLoadModel (const string &fname, const string &modelpath, const string &solverClass="", double RM=1.0, double RA=1.0, double CM=0.01)
Returns the Id of the loaded model.
void doMove (Id orig, ObjId newParent)
void doNonBlockingStart (double runtime)
void doQuit ()
void doReacDiffMesh (Id baseCompartment)
void doReinit ()
void doSaveModel (Id model, const string &fileName, bool qflag=0) const
void doSetClock (unsigned int tickNum, double dt)
void doSetParserIdleFlag (bool isParserIdle)
void doStart (double runtime, bool notify=false)
void doStop ()
void doSyncDataHandler (Id tgt)
void doTerminate ()
void doUseClock (string path, string field, unsigned int tick)
string doVersion ()
void error (const string &text)
void expectVector (bool flag)
ObjId getCwe () const
const ProcInfo * getProcInfo (unsigned int index) const
void handleAck (unsigned int ackNode, unsigned int status)
void handleAddMsg (const Eref &e, string msgType, ObjId src, string srcField, ObjId dest, string destField, unsigned int msgIndex)
void handleCopy (const Eref &e, vector< ObjId > args, string newName, unsigned int n, bool toGlobal, bool copyExtMsgs)
void handleCreate (const Eref &e, string type, ObjId parent, Id newElm, string name, NodeBalance nb, unsigned int parentMsgIndex)
void handleMove (const Eref &e, Id orig, ObjId newParent)
void handleQuit ()
This function is NOT called when simulation ends normally.
void handleSync (const Eref &e, Id elm, FuncId fid)
void handleUseClock (const Eref &e, string path, string field, unsigned int tick, unsigned int msgIndex)
void initAck ()
const Msg * innerAddMsg (string msgType, ObjId src, string srcField, ObjId dest, string destField, unsigned int msgIndex)
bool innerCopy (const vector< ObjId > &args, const string &newName, unsigned int n, bool toGlobal, bool copyExtMsgs)
Does actual work of copying. Returns true on success.
void innerCreate (string type, ObjId parent, Id newElm, string name, const NodeBalance &nb, unsigned int parentMsgIndex)
bool innerMove (Id orig, ObjId newParent)
bool innerUseClock (string path, string field, unsigned int tick, unsigned int msgIndex)
bool isAckPending () const
bool isRunning () const
void setCwe (ObjId cwe)
void setShellElement (Element *shelle)
void setupSocketStreamer (const string host, const int port)
Shell ()
void start (double runTime)
void waitForAck ()
void warning (const string &text)
~Shell ()
Static Public Member Functions
static bool adopt (Id parent, Id child, unsigned int msgIndex)
Adaptor for above function. Also static function.
static bool adopt (ObjId parent, Id child, unsigned int msgIndex)
static bool chopPath (const string &path, vector< string > &ret, vector< unsigned int > &index)
static bool chopString (const string &path, vector< string > &ret, char separator='/')
static void cleanSimulation ()
Clean-up MOOSE before shutting down. This function is called whenever keyboard interrupt terminates the simulation.
static void clearRestructuringQ ()
static void dropClockMsgs (const vector< ObjId > &list, const string &field)
static bool inBlockingParserCall ()
static const Cinfo * initCinfo ()
static bool isNameValid (const string &name)
static bool isParserIdle ()
static bool isSingleThreaded ()
static bool keepLooping ()
static void launchParser ()
static void launchThreads ()
static void loadBalance ()
static unsigned int myNode ()
static unsigned int numCores ()
static unsigned int numNodes ()
static unsigned int numProcessThreads ()
static const ProcInfo * procInfo ()
Static func for returning the ProcInfo of the shell.
static unsigned int reduceInt (unsigned int val)
static void setHardware (unsigned int numCores, unsigned int numNodes, unsigned int myNode)
Static Public Attributes
static const unsigned int ErrorStatus = ~1
static const unsigned int OkStatus = ~0
Private Attributes
ObjId cwe_
Current working Element.
vector< double * > getBuf_
bool gettingVector_
unsigned int numGetVecReturns_
Element * shelle_
Static Private Attributes
static vector< unsigned int > acked_
static bool doReinit_
static bool isBlockedOnParser_ = 0
static bool isParserIdle_
static bool keepLooping_ = 1
static unsigned int myNode_
static unsigned int numAcks_ = 0
static unsigned int numCores_
static unsigned int numNodes_
static unsigned int numProcessThreads_
static ProcInfo p_
static double runtime_
static vector< ProcInfo > threadProcs_
Detailed Description
Definition at line 42 of file Shell.h.
Constructor & Destructor Documentation
Shell()
Shell::Shell ()
Definition at line 144 of file Shell.cpp.
             : gettingVector_(0), numGetVecReturns_(0), cwe_(ObjId())
{
    getBuf_.resize(1, 0);
}
References cwe_, getBuf_, gettingVector_, numGetVecReturns_, and ObjId::ObjId().
~Shell()
Shell::~Shell ()
Definition at line 149 of file Shell.cpp.
{
    ;
}
Member Function Documentation
addClockMsgs()
void Shell::addClockMsgs (const vector< ObjId > & list, const string & field, unsigned int tick, unsigned int msgIndex)
Utility function to set up messages to schedule a list of Ids using the specified field and tick
Definition at line 834 of file Shell.cpp.
{
    if (!Id(1).element()) return;
    ObjId clockId(1);
    dropClockMsgs(list, field);  // Forbid duplicate PROCESS actions.
    for (vector<ObjId>::const_iterator i = list.begin(); i != list.end(); ++i) {
        if (i->element()) {
            stringstream ss;
            ss << "proc" << tick;
            const Msg* m = innerAddMsg("OneToAll", clockId, ss.str(), *i, field,
                                       msgIndex++);
            if (m) i->element()->innerSetTick(tick);
        }
    }
}
References dropClockMsgs(), Id::element(), ObjId::element(), Id::Id(), innerAddMsg(), Element::innerSetTick(), and ObjId::ObjId().
Referenced by innerUseClock().
adopt() [1/2]
bool Shell::adopt (Id parent, Id child, unsigned int msgIndex) static
Adaptor for above function. Also static function.
Definition at line 619 of file Shell.cpp.
{
    return adopt(ObjId(parent), child, msgIndex);
}
References adopt(), and ObjId::ObjId().
Referenced by buildFinfoElement(), init(), Msg::initMsgManagers(), pymoose::initShell(), Cinfo::makeCinfoElements(), testSetGetExtField(), and testStrSet().
adopt() [2/2]
bool Shell::adopt (ObjId parent, Id child, unsigned int msgIndex) static
Static utility function. Attaches child element to parent element. Must only be called from functions executing in parallel on all nodes, as it does a local message addition MsgIndex is needed to be sure that the same msg identifies parent-child connection on all nodes.
Definition at line 591 of file Shell.cpp.
{
    static const Finfo* pf = Neutral::initCinfo()->findFinfo("parentMsg");
    // static const DestFinfo* pf2 = dynamic_cast< const DestFinfo* >( pf );
    // static const FuncId pafid = pf2->getFid();
    static const Finfo* f1 = Neutral::initCinfo()->findFinfo("childOut");
    assert(!(child.element() == 0));
    assert(!(child == Id()));
    assert(!(parent.element() == 0));
    Msg* m = new OneToAllMsg(parent.eref(), child.element(), msgIndex);
    assert(m);
    // cout << myNode_ << ", Shell::adopt: mid = " << m->mid() << ", pa =" <<
    // parent << "." << parent()->getName() << ", kid=" << child << "." <<
    // child()->getName() << "\n";
    if (!f1->addMsg(pf, m->mid(), parent.element())) {
        cout << "move: Error: unable to add parent->child msg from "
             << parent.element()->getName() << " to "
             << child.element()->getName() << "\n";
        return 0;
    }
    return 1;
}
References Finfo::addMsg(), Id::element(), ObjId::element(), ObjId::eref(), Cinfo::findFinfo(), Element::getName(), Id::Id(), Neutral::initCinfo(), Msg::mid(), OneToAllMsg::OneToAllMsg(), and Id::operator==().
Referenced by adopt(), innerCopyElements(), and innerCreate().
chopPath()
bool Shell::chopPath (const string & path, vector< string > & ret, vector< unsigned int > & index) static
Chop up the path into a vector of Element names, and also fills out a matching vector of indices. If at any level of the path there are no indices or the index is zero, the index entry * remains empty. Otherwise the entry contains a vector with index values for this level of the path. The zeroth position of this index vector is the slowest varying, i.e., most significant. Returns true if it starts at '/'.
Example: /foo/bar[10]/zod[3][4][5] would return: ret: {"foo", "bar", "zod" } index: { {}, {10}, {3,4,5} }
static func.
Example: /foo/bar[10]/zod[3] would return: ret: {"foo", "bar", "zod" } index: { 0, 10, 3 }
Definition at line 470 of file Shell.cpp.
{
    bool isAbsolute = chopString(path, ret, '/');
    if (isAbsolute) {
        index.clear();
    } else {
        index.clear();
    }
    for (unsigned int i = 0; i < ret.size(); ++i) {
        index.push_back(0);
        if (ret[i] == ".") continue;
        if (ret[i] == "..") {
            continue;
        }
        if (!extractIndex(ret[i], index[i])) {
            cout << "Error: Shell::chopPath: Failed to parse indices in path '"
                 << path << "'\n";
            ret.resize(0);
            index.resize(0);
            return isAbsolute;
        }
        unsigned int pos = ret[i].find_first_of('[');
        if (ret[i].find_first_of('[') != string::npos)
            ret[i] = ret[i].substr(0, pos);
    }
    return isAbsolute;
}
References chopString(), and extractIndex().
Referenced by doFind(), and testChopPath().
chopString()
bool Shell::chopString (const string & path, vector< string > & ret, char separator = '/') static
Chops up the names in the string into the vector of strings, using the specified separator. Returns true if it is an absolute path, that is, starts with the separator.
Static func to subdivide a string at the specified separator.
Definition at line 423 of file Shell.cpp.
{
    // /foo/bar/zod
    // foo/bar/zod
    // ./foo/bar/zod
    // ../foo/bar/zod
    // .
    // /
    // ..
    ret.resize(0);
    if (path.length() == 0) return 1;  // Treat it as an absolute path
    bool isAbsolute = 0;
    string temp = path;
    if (path[0] == separator) {
        isAbsolute = 1;
        if (path.length() == 1) return 1;
        temp = temp.substr(1);
    }
    auto pos = temp.find_first_of(separator);
    ret.push_back(temp.substr(0, pos));
    while (pos != string::npos) {
        temp = temp.substr(pos + 1);
        if (temp.length() == 0) break;
        pos = temp.find_first_of(separator);
        ret.push_back(temp.substr(0, pos));
    }
    return isAbsolute;
}
Referenced by chopPath(), findBraceContent(), innerFind(), matchBeforeBrace(), simpleWildcardFind(), and testChopString().
cleanSimulation()
void Shell::cleanSimulation () static
Clean-up MOOSE before shutting down. This function is called whenever keyboard interrupt terminates the simulation.
Cleans up all Elements except /root itself, /clock, /classes, and /Msgs. In due course will also do suitable reinitialization of tick and other values.
Definition at line 918 of file Shell.cpp.
{
    Eref sheller = Id().eref();
    Shell* s = reinterpret_cast<Shell*>(sheller.data());
    vector<Id> kids;
    Neutral::children(sheller, kids);
    for (vector<Id>::iterator i = kids.begin(); i != kids.end(); ++i) {
        if (i->value() > 4) /* These are created by users */
        {
            LOG(moose::debug, "Shell::cleanSimulation: deleted cruft at "
                                  << i->value() << ": " << i->path());
            s->doDelete(*i);
        }
    }
    LOG(moose::info, "Cleaned up!");
}
References Neutral::children(), Eref::data(), moose::debug, doDelete(), Id::eref(), Id::Id(), moose::info, Id::path(), and Id::value().
Referenced by pymoose::handleKeyboardInterrupts(), and pymoose::start().
clearRestructuringQ()
static void Shell::clearRestructuringQ () static
Works through internal queue of operations that modify the structure of the simulation. These operations have to be carefully separated from any other functions or messaging, so this happens while all other threads are blocked.
destroy()
void Shell::destroy (const Eref & e, ObjId oid)
Definition at line 657 of file Shell.cpp.
{
    Neutral* n = reinterpret_cast<Neutral*>(e.data());
    assert(n);
    // cout << myNode_ << ": Shell::destroy done for element id: " << eid << ",
    // name = " << eid.element()->getName() << endl;
    SetGet0::set( oid, "notifyDestroy" );
    n->destroy(oid.eref(), 0);
    if (cwe_.id == oid.id) cwe_ = ObjId();
}
References cwe_, Eref::data(), Neutral::destroy(), ObjId::eref(), ObjId::id, ObjId::ObjId(), Id::operator==(), and SetGet0::set().
Referenced by initCinfo().
doAddMsg()
ObjId Shell::doAddMsg (const string & msgType, ObjId src, const string & srcField, ObjId dest, const string & destField)
Sets up a Message of specified type. Later need to consider doing this through MsgSpecs only. Here the 'args' vector handles whatever arguments we may need to pass to the specified msgType.
Definition at line 254 of file Shell.cpp.
{
    if (!src.id.element()) {
        cout << myNode_ << ": Error: Shell::doAddMsg: src not found" << endl;
        return ObjId();
    }
    if (!dest.id.element()) {
        cout << myNode_ << ": Error: Shell::doAddMsg: dest not found" << endl;
        return ObjId(0, BADINDEX);
    }
    const Finfo* f1 = src.id.element()->cinfo()->findFinfo(srcField);
    if (!f1) {
        cout << myNode_ << ": Shell::doAddMsg: Error: Failed to find field '"
             << srcField << "' on src: " << src.id.element()->getName() << endl;
        return ObjId(0, BADINDEX);
    }
    const Finfo* f2 = dest.id.element()->cinfo()->findFinfo(destField);
    if (!f2) {
        cout << myNode_ << ": Shell::doAddMsg: Error: Failed to find field '"
             << destField << "' on dest: " << dest.id.element()->getName()
             << endl;
        return ObjId(0, BADINDEX);
    }
    if (!f1->checkTarget(f2)) {
        cout << myNode_
             << ": Shell::doAddMsg: Error: Src/Dest Msg type mismatch: "
             << srcField << "/" << destField << endl;
        return ObjId(0, BADINDEX);
    }
    const Msg* m = innerAddMsg(msgType, src, srcField, dest, destField, 0);
    SetGet6<string, ObjId, string, ObjId, string, unsigned int>::set(
        ObjId(),   // Apply command to Shell
        "addMsg",  // Function to call.
        msgType, src, srcField, dest, destField, m->mid().dataIndex);
    return m->mid();
    // const Msg* m = innerAddMsg( msgType, src, srcField, dest, destField );
    // return m->mid();
    // return Msg::lastMsg()->mid();
}
References BADINDEX, Finfo::checkTarget(), Element::cinfo(), ObjId::dataIndex, Id::element(), Cinfo::findFinfo(), Element::getName(), ObjId::id, innerAddMsg(), Msg::mid(), myNode_, ObjId::ObjId(), ObjId::ObjId(), and SetGet6< A1, A2, A3, A4, A5, A6 >::set().
Referenced by ReadCell::addCanonicalChannel(), ReadCell::addChannelMessage(), ReadKkit::addmsg(), ReadCell::addSpikeGen(), addSpine(), benchmarkMsg(), ReadSwc::build(), ReadCell::buildCompartment(), ReadKkit::buildEnz(), ReadKkit::buildSumTotal(), pymoose::connect(), doClassSpecificMessaging(), ReadCspace::expandEnzyme(), ReadCspace::expandReaction(), ReadKkit::innerAddMsg(), makeCompt(), ReadCspace::makePlots(), makeReacTest(), Stoich::setElist(), testAssortedMsg(), testCalcJunction(), testGetMsg(), testMMenzProcess(), testMpiFibonacci(), testMsgElementListing(), testPoolVolumeScaling(), testReacVolumeScaling(), testShellAddMsg(), testStats(), and testTwoReacGetNeighbors().
doCopy()
Id Shell::doCopy (Id orig, ObjId newParent, string newName, unsigned int n, bool toGlobal, bool copyExtMsgs)
Returns the Id of the root of the copied tree upon success.
Copies orig Element to newParent. n specifies how many copies are made. copyExtMsgs specifies whether to also copy messages from orig to objects outside the copy tree. Usually we don't do this.
Definition at line 16 of file ShellCopy.cpp.
{
    if (newName.length() > 0 && !isNameValid(newName)) {
        cout << "Error: Shell::doCopy: Illegal name '" + newName +
                    "' for copy.\n";
        return Id();
    }
    if (Neutral::isDescendant(newParent, orig)) {
        cout << "Error: Shell::doCopy: Cannot copy object to descendant in "
                "tree\n";
        return Id();
    }
    if (n < 1) {
        cout << "Warning: Shell::doCopy( " << orig.path() << " to "
             << newParent.path() << " ) : numCopies must be > 0, using 1 \n";
        return Id();
    }
    if (Neutral::child(newParent.eref(), newName) != Id()) {
        cout << "Error: Shell::doCopy: Cannot copy object '" << newName
             << "' onto '" << newParent.path()
             << "' since object with same name already present.\n";
        return Id();
    }
    Eref sheller(shelle_, 0);
    Id newElm = Id::nextId();
    vector<ObjId> args;
    args.push_back(orig);
    args.push_back(newParent);
    args.push_back(newElm);
    SetGet5<vector<ObjId>, string, unsigned int, bool, bool>::set(
        ObjId(), "copy", args, newName, n, toGlobal, copyExtMsg);
    /*
    if ( innerCopy( args, newName, n, toGlobal, copyExtMsg ) )
            return newElm;
    else
            return Id();
    */
    return newElm;
}
References Neutral::child(), ObjId::eref(), Eref::Eref(), Id::Id(), Neutral::isDescendant(), isNameValid(), Id::nextId(), ObjId::ObjId(), Id::operator!=(), Id::path(), ObjId::path(), SetGet5< A1, A2, A3, A4, A5 >::set(), and shelle_.
Referenced by ReadCell::addChannel(), addSpine(), ReadCell::buildCompartment(), buildFromProto(), pymoose::copy(), testCopy(), testCopyFieldElement(), and testGetMsg().
doCreate()
Id Shell::doCreate (string type, ObjId parent, string name, unsigned int numData, NodePolicy nodePolicy = MooseBlockBalance, unsigned int preferredNode = 1)
Create an Element. Returns its id. type: Specifies classname of Objects in Element. parent: Id of parent element name: Name to be used for identifying Element. numData: Size of array.
This is the version used by the parser. Acts as a blocking, serial-like interface to a potentially multithread, multinode call. Returns the new Id index upon success, otherwise returns Id(). The data of the new Element is not necessarily allocated at this point, that can be deferred till the global Instantiate or Reset calls. Idea is that the model should be fully defined before load balancing.
Definition at line 168 of file Shell.cpp.
{
    const Cinfo* c = Cinfo::find(type);
    if (!isNameValid(name)) {
        stringstream ss;
        ss << "Shell::doCreate: bad character in the name '" << name
           << "'. No Element created.";
        warning(ss.str());
        return Id();
    }
    if (c) {
        if (c->banCreation()) {
            stringstream ss;
            ss << "Shell::doCreate: Cannot create an object of class '" << type
               << "' because it is an abstract base class or a FieldElement.\n";
            warning(ss.str());
            return Id();
        }
        Element* pa = parent.element();
        if (!pa) {
            cerr << "Shell::doCreate: Parent Element'" << parent
               << "' not found. No Element created." << endl;
            return Id();
        }
        // TODO: This should be an error in future.
        // This logic of handling already existing path is now handled in
        // melements.cpp . Calling this section should become an error in
        // future.
        if (Neutral::child(parent.eref(), name) != Id()) {
            string msg = "Object with path '" + parent.path() + "/" +
                         name + "' already exists. "
                         " Use `moose.element` to access the existing element.";
            throw runtime_error(msg);
            return Id();
        }
        // Get the new Id ahead of time and pass to all nodes.
        Id ret = Id::nextId();
        NodeBalance nb(numData, nodePolicy, preferredNode);
        // Get the parent MsgIndex ahead of time and pass to all nodes.
        unsigned int parentMsgIndex = OneToAllMsg::numMsg();
        SetGet6<string, ObjId, Id, string, NodeBalance, unsigned int>::set(
            ObjId(),        // Apply command to Shell
            "create",       // Function to call.
            type,           // class of new object
            parent,         // Parent
            ret,            // id of new object
            name,           // name of new object
            nb,             // Node balance configuration
            parentMsgIndex  // Message index of child-parent msg.
            );
        // innerCreate( type, parent, ret, name, numData, isGlobal );
        return ret;
    } else {
        stringstream ss;
        ss << "Shell::doCreate: Class '" << type
           << "' not known. No Element created";
        warning(ss.str());
    }
    return Id();
}
References Cinfo::banCreation(), Neutral::child(), ObjId::element(), ObjId::eref(), Cinfo::find(), Id::Id(), isNameValid(), Id::nextId(), NodeBalance::NodeBalance(), OneToAllMsg::numMsg(), ObjId::ObjId(), Id::operator!=(), ObjId::path(), SetGet6< A1, A2, A3, A4, A5, A6 >::set(), and warning().
Referenced by ReadKkit::assignPoolCompartments(), benchmarkMsg(), ReadKkit::buildChan(), ReadCell::buildCompartment(), ReadKkit::buildEnz(), ReadKkit::buildGraph(), ReadKkit::buildGroup(), ReadKkit::buildInfo(), ReadKkit::buildPlot(), ReadKkit::buildPool(), ReadKkit::buildReac(), ReadKkit::buildStim(), ReadKkit::buildSumTotal(), ReadKkit::buildTable(), ReadKkit::convertKineticsToGroup(), doCreate2(), doLoadModel(), ReadCspace::expandEnzyme(), ReadCspace::expandReaction(), ReadKkit::findCompartmentsFromAnnotation(), makeCompt(), makeCompt(), ReadCspace::makeMolecule(), ReadCspace::makePlots(), makeReacTest(), makeStandardElements(), ReadCell::read(), ReadKkit::read(), ReadCell::startGraftCell(), testAssortedMsg(), testBuildStoich(), testCalcJunction(), testCellDiffn(), testChildren(), testClockMessaging(), testCopy(), testCopyFieldElement(), testCylDiffn(), testCylDiffnWithStoich(), testDescendant(), testFilterOffNodeTargets(), testFindModelParent(), testGetMsg(), testInterNodeOps(), testMMenz(), testMMenzProcess(), testMove(), testMpiFibonacci(), testMsgElementListing(), testObjIdToAndFromPath(), testPoolVolumeScaling(), testReacVolumeScaling(), testReMesh(), testRunGsolve(), testRunKsolve(), testRunKsolveWithLSODA(), testShellAddMsg(), testShellParserCreateDelete(), testShellParserStart(), testShellSetGet(), testSmallCellDiffn(), testStats(), testSyncSynapseSize(), testTable(), testTaperingCylDiffn(), testTreeTraversal(), testTwoReacGetNeighbors(), testVolScaling(), and testWildcard().
doCreate2()
Id Shell::doCreate2 (string type, ObjId parent, string name, unsigned int numData)
Definition at line 238 of file Shell.cpp.
{
    return doCreate(type, parent, name, numData, MooseBlockBalance, 1);
}
References doCreate(), and MooseBlockBalance.
Referenced by pymoose::createElementFromPath().
doDelete()
bool Shell::doDelete (ObjId oid)
Delete specified Element and all its children and all Msgs connected to it. This also works for Msgs, which are also identified by an ObjId. Unlike regular objects, only the one Msg entry specified by the DataIndex part of the ObjId argument is deleted.
Definition at line 244 of file Shell.cpp.
{
    SetGet1<ObjId>::set(ObjId(), "delete", oid);
    /*
       Neutral n;
       n.destroy( i.eref(), 0 );
       */
    return true;
}
References ObjId::ObjId(), and SetGet1< A >::set().
Referenced by addSpine(), benchmarkMsg(), cleanSimulation(), ReadKkit::convertKineticsToGroup(), pymoose::doDelete(), ReadKkit::findCompartmentsFromAnnotation(), testAssortedMsg(), testBuildStoich(), testCalcJunction(), testCellDiffn(), testChildren(), testClockMessaging(), testCopy(), testCopyFieldElement(), testCylDiffn(), testCylDiffnWithStoich(), testDescendant(), testFilterOffNodeTargets(), testFindModelParent(), testGetMsg(), testInterNodeOps(), testMMenz(), testMMenzProcess(), testMove(), testMsgElementListing(), testObjIdToAndFromPath(), testPoolVolumeScaling(), testReacVolumeScaling(), testReadKkit(), ReadCspace::testReadModel(), testReMesh(), testRunGsolve(), testRunKsolve(), testRunKsolveWithLSODA(), testSetupReac(), testShellAddMsg(), testShellParserCreateDelete(), testShellSetGet(), testSmallCellDiffn(), testStats(), testSyncSynapseSize(), testTable(), testTaperingCylDiffn(), testTreeTraversal(), testTwoReacGetNeighbors(), testVolScaling(), and testWildcard().
doFind()
ObjId Shell::doFind (const string & path) const
Looks up the Id specified by the given path. May include relative references and the internal cwe (current working Element) on the shell
Definition at line 500 of file Shell.cpp.
{
    if (path == "/" || path == "/root") return ObjId();
    ObjId curr;
    vector<string> names;
    vector<unsigned int> indices;
    bool isAbsolute = chopPath(path, names, indices);
    assert(names.size() == indices.size());
    if (!isAbsolute) curr = cwe_;
    for (unsigned int i = 0; i < names.size(); ++i) {
        if (names[i] == ".") {
        } else if (names[i] == "..") {
            curr = Neutral::parent(curr.eref());
        } else {
            ObjId pa = curr;
            curr = Neutral::child(curr.eref(), names[i]);
            if (curr == ObjId())  // Neutral::child returned Id(), ie, bad.
                return ObjId(0, BADINDEX);
            if (curr.element()->hasFields()) {
                curr.dataIndex = pa.dataIndex;
                curr.fieldIndex = indices[i];
            } else {
                curr.dataIndex = indices[i];
                if (curr.element()->numData() <= curr.dataIndex)
                    return ObjId(0, BADINDEX);
            }
        }
    }
    assert(curr.element());
    if (curr.element()->numData() <= curr.dataIndex) return ObjId(0, BADINDEX);
    if (curr.fieldIndex > 0 && !curr.element()->hasFields())
        return ObjId(0, BADINDEX);
    return curr;
}
References BADINDEX, Neutral::child(), chopPath(), cwe_, ObjId::dataIndex, ObjId::element(), ObjId::eref(), ObjId::fieldIndex, Element::hasFields(), Element::numData(), ObjId::ObjId(), ObjId::ObjId(), ObjId::operator==(), and Neutral::parent().
Referenced by ReadCell::addChannelMessage(), ReadKkit::buildChan(), ReadKkit::buildEnz(), ReadKkit::buildGraph(), ReadKkit::buildGroup(), ReadKkit::buildPlot(), ReadKkit::buildPool(), ReadKkit::buildReac(), ReadKkit::buildStim(), ReadKkit::buildTable(), Id::Id(), ObjId::ObjId(), and testTreeTraversal().
doLoadModel()
Id Shell::doLoadModel (const string & fname, const string & modelpath, const string & solverClass = "", double RM = 1.0, double RA = 1.0, double CM = 0.01)
Returns the Id of the loaded model.
Loads in a model to a specified path. Tries to figure out model type from fname or contents of file. Currently knows about kkit, cspace. Soon to learn .p, SBML, NeuroML. Later to learn NineML
Definition at line 132 of file LoadModels.cpp.
{
    ifstream fin( fileName.c_str() );
    if ( !fin )
    {
        LOG( moose::failed, "Shell::doLoadModel: could not open file " << fileName );
        return Id();
    }
    string modelName;
    Id parentId;
    if ( !( findModelParent ( cwe_, modelPath, parentId, modelName ) ) )
        return Id();
    string line;
    switch ( findModelType( fileName, fin, line ) )
    {
    case DOTP:
    {
        ReadCell rc;
        return rc.read( fileName, modelName, parentId );
        return Id();
    }
    case SWC:
    {
        LOG( moose::info, "In doLoadModel for SWC" );
        ReadSwc rs( fileName );
        Id model = parentId;
        if ( !parentId.element()->cinfo()->isA( "Neuron" ) )
        {
            model = doCreate( "Neuron", parentId, modelName, 1 );
        }
        rs.build( model, 0.5e-3, RM, RA, CM );
        return model;
    }
    case KKIT:
    {
        string sc = solverClass;
        ReadKkit rk;
        Id ret = rk.read( fileName, modelName, parentId, sc);
        return ret;
    }
    break;
    case CSPACE:
    {
        string sc = solverClass;
        ReadCspace rc;
        Id ret = rc.readModelString( line, modelName, parentId, sc);
        rc.makePlots( 1.0 );
        return ret;
    }
    case UNKNOWN:
    default:
        cout << "Error: Shell::doLoadModel: File type of '" <<
             fileName << "' is unknown\n";
    }
    return Id();
}
References ReadSwc::build(), Element::cinfo(), CSPACE, cwe_, doCreate(), DOTP, Id::element(), moose::failed, findModelParent(), findModelType(), Id::Id(), moose::info, Cinfo::isA(), KKIT, ReadCspace::makePlots(), ReadCell::read(), ReadKkit::read(), ReadCspace::readModelString(), ReadSwc::ReadSwc(), SWC, and UNKNOWN.
Referenced by pymoose::loadModelInternal().
doMove()
void Shell::doMove (Id orig, ObjId newParent)
shifts orig Element (including offspring) to newParent. All old hierarchy, data, Msgs etc are preserved below the orig.
Definition at line 364 of file Shell.cpp.
{
    if (orig == Id()) {
        cout << "Error: Shell::doMove: Cannot move root Element\n";
        return;
    }
    if (newParent.element() == 0) {
        cout << "Error: Shell::doMove: Cannot move object to null parent \n";
        return;
    }
    if (Neutral::isDescendant(newParent, orig)) {
        cout << "Error: Shell::doMove: Cannot move object to descendant in "
                "tree\n";
        return;
    }
    const string& name = orig.element()->getName();
    if (Neutral::child(newParent.eref(), name) != Id()) {
        stringstream ss;
        ss << "Shell::doMove: Object with same name already present: '"
           << newParent.path() << "/" << name << "'. Move failed.";
        warning(ss.str());
        return;
    }
    SetGet2<Id, ObjId>::set(ObjId(), "move", orig, newParent);
}
References Neutral::child(), Id::element(), ObjId::element(), ObjId::eref(), Element::getName(), Id::Id(), Neutral::isDescendant(), ObjId::ObjId(), Id::operator!=(), Id::operator==(), ObjId::path(), SetGet2< A1, A2 >::set(), and warning().
Referenced by addSpine(), ReadKkit::assignPoolCompartments(), ReadKkit::assignReacCompartments(), ReadKkit::convertKineticsToGroup(), ReadKkit::findCompartmentsFromAnnotation(), pymoose::move(), testMove(), and testObjIdToAndFromPath().
doNonBlockingStart()
void Shell::doNonBlockingStart (double runtime)
Starts off simulation, to run for 'runtime' more than current time. This version returns at once, and the parser can go on to do other things. It has to check with the Shell::isRunning function (accessible as a MOOSE field) to find out if it is finished. Can call 'doStop', 'doTerminate' or 'doReinit' at any time to stop the run with increasing levels of prejudice.
doQuit()
void Shell::doQuit ()
Cleanly quits simulation, wrapping up all nodes and threads.
Definition at line 300 of file Shell.cpp.
{
    SetGet0::set(ObjId(), "quit");
}
References ObjId::ObjId(), and SetGet0::set().
Referenced by launchParser(), and testShellParserQuit().
doReacDiffMesh()
void Shell::doReacDiffMesh (Id baseCompartment)
This function builds a reac-diffusion mesh starting at the specified ChemCompt, which houses MeshEntry FieldElements. Assumes that the dimensions of the baseCompartment have just been redefined, and we now need to go through and update the child reaction system.
doReinit()
void Shell::doReinit ()
Reinitializes simulation: time goes to zero, all scheduled objects are set to initial conditions. If simulation is already running, first stops it.
Definition at line 338 of file Shell.cpp.
{
    Id clockId(1);
    SetGet0::set(clockId, "reinit");
}
References Id::Id(), and SetGet0::set().
Referenced by benchmarkMsg(), ReadKkit::read(), ReadKkit::run(), testCalcJunction(), testCellDiffn(), testCylDiffn(), testCylDiffnWithStoich(), testGetMsg(), testMMenzProcess(), testRunGsolve(), testRunKsolve(), testRunKsolveWithLSODA(), testSetupReac(), testSmallCellDiffn(), testStats(), and testTaperingCylDiffn().
doSaveModel()
void Shell::doSaveModel (Id model, const string & fileName, bool qFlag = 0) const
Saves specified model to specified file, using filetype identified by filename extension. Currently known filetypes are: .g: Kkit model
Still to come: .p: GENESIS neuron morphology and channel spec file .sbml: SBML file .nml: NeuroML file .9ml: NineML file .snml: SigNeurML
Saves specified model to specified file, using filetype identified by filename extension. Currently known filetypes are: .g: Kkit model .cspace: cspace model
Still to come: .p: GENESIS neuron morphology and channel spec file .sbml: SBML file .nml: NeuroML file .9ml: NineML file .snml: SigNeurML
Definition at line 31 of file SaveModels.cpp.
{
    // string modelFamily = Field< string >::get( model, "modelFamily" );
    // if ( modelFamily != "kinetic" ) {
    //  cout << "Warning: Shell::doSaveModel: Do not know how to save "
    //          "model of family '" << modelFamily << "'.\n";
    //  return;
    // }
    unsigned int pos = fileName.find( "." );
    string fileType = fileName.substr( pos );
    if ( fileType == ".g" ) { // kkit model requested.
            // cout << "Cannot write kkit model at this point\n";
            writeKkit( model, fileName );
    } else if (fileType == ".cspace"){
            // writeCspace( model, fileName );
            cout << "Cannot write cspace model at this point\n";
    } else {
        cout << "Warning: Shell::doSaveModel: Do not know how to save "
                "model of file type '" << fileType << "'.\n";
    }
}
References writeKkit().
doSetClock()
void Shell::doSetClock (unsigned int tickNum, double dt)
Definition at line 351 of file Shell.cpp.
{
    LookupField<unsigned int, double>::set(ObjId(1), "tickDt", tickNum, dt);
}
References ObjId::ObjId(), and LookupField< L, A >::set().
Referenced by benchmarkMsg(), initCinfo(), main(), makeReacTest(), ReadKkit::run(), pymoose::setClock(), setMethod(), testCalcJunction(), testCellDiffn(), testCylDiffn(), testCylDiffnWithStoich(), testFibonacci(), testGetMsg(), testMMenzProcess(), testMpiFibonacci(), testRunGsolve(), testRunKsolve(), testRunKsolveWithLSODA(), testShellAddMsg(), testShellParserStart(), testSmallCellDiffn(), testStats(), and testTaperingCylDiffn().
doSetParserIdleFlag()
void Shell::doSetParserIdleFlag (bool isParserIdle)
This function is called by the parser to tell the ProcessLoop to wait a bit between cycles. Used when we are waiting for user input and there is no point in having the ProcessLoop go at full speed. When flag is true, then the ProcessLoop will sleep a bit, when false it will work at full speed.
doStart()
void Shell::doStart (double runtime, bool notify = false)
Starts off simulation, to run for 'runtime' more than current time. This version is blocking, and returns only when the simulation is done. If ‘nofity = true’ then also notify user whenever 10% of simulation is over.
Definition at line 305 of file Shell.cpp.
{
    Id clockId(1);
    SetGet2<double, bool>::set(clockId, "start", runtime, notify);
    /*-----------------------------------------------------------------------------
     *  Now that simulation is over, call cleanUp function of Streamer class
     *  objects. The purpose of this is to write whatever is left in tables to
     *  the output file.
     *-----------------------------------------------------------------------------*/
    vector<ObjId> streamers;
    wildcardFind("/##[TYPE=Streamer]", streamers);
    // LOG( moose::debug,  "total streamers " << streamers.size( ) );
    for (vector<ObjId>::const_iterator itr = streamers.begin();
         itr != streamers.end(); itr++) {
        Streamer* pStreamer = reinterpret_cast<Streamer*>(itr->data());
        pStreamer->cleanUp();
    }
    // Print the stats collected by profiling map.
    char* p = getenv("MOOSE_SHOW_SOLVER_PERF");
    if (p != NULL) moose::printSolverProfMap();
}
References Streamer::cleanUp(), ObjId::data(), Id::Id(), moose::printSolverProfMap(), SetGet2< A1, A2 >::set(), and wildcardFind().
Referenced by benchmarkMsg(), ReadKkit::run(), pymoose::start(), testCalcJunction(), testCellDiffn(), testCylDiffn(), testCylDiffnWithStoich(), testFibonacci(), testGetMsg(), testMMenzProcess(), testMpiFibonacci(), testRunGsolve(), testRunKsolve(), testRunKsolveWithLSODA(), testSetupReac(), testShellAddMsg(), testShellParserStart(), testSmallCellDiffn(), testStats(), and testTaperingCylDiffn().
doStop()
void Shell::doStop ()
Cleanly stops simulation, ready to take up again from where the stop occurred. Waits till current operations are done.
Definition at line 344 of file Shell.cpp.
{
    Id clockId(1);
    SetGet0::set(clockId, "stop");
}
References Id::Id(), and SetGet0::set().
doSyncDataHandler()
void Shell::doSyncDataHandler (Id tgt)
This function synchronizes fieldDimension on the DataHandler across nodes. Used after function calls that might alter the number of Field entries in the table.. The tgt is the FieldElement whose fieldDimension needs updating.
doTerminate()
void Shell::doTerminate ()
Terminate ongoing simulation, with prejudice. Uncleanly stops simulation. Things may be in a mess with different objects at different times, but it stops at once.
doUseClock()
void Shell::doUseClock (string path, string field, unsigned int tick)
Connects up process messages from the specified Tick to the targets on the path. Does so for whole Elements, not individual entries in the Element array. The target on the path usually has the 'process' field but other options are allowed, like 'init'
Definition at line 356 of file Shell.cpp.
{
    unsigned int msgIndex = OneToAllMsg::numMsg();
    SetGet4<string, string, unsigned int, unsigned int>::set(
        ObjId(), "useClock", path, field, tick, msgIndex);
    // innerUseClock( path, field, tick);
}
References OneToAllMsg::numMsg(), ObjId::ObjId(), and SetGet4< A1, A2, A3, A4 >::set().
Referenced by benchmarkMsg(), main(), setMethod(), testCalcJunction(), testCellDiffn(), testCylDiffn(), testCylDiffnWithStoich(), testGetMsg(), testMMenzProcess(), testMpiFibonacci(), testRunGsolve(), testRunKsolve(), testRunKsolveWithLSODA(), testShellAddMsg(), testShellParserStart(), testSmallCellDiffn(), testStats(), testTaperingCylDiffn(), and pymoose::useClock().
doVersion()
string Shell::doVersion ()
Returns version number of the software.
Definition at line 544 of file Shell.cpp.
{
    string v = MOOSE_VERSION;
    return v;
}
dropClockMsgs()
void Shell::dropClockMsgs (const vector< ObjId > & list, const string & field) static
Utility function to unschedule the specified elist operating on the specified field, typically 'process'
Definition at line 804 of file Shell.cpp.
{
    vector<ObjId> msgs;  // These are the messages to delete.
    for (vector<ObjId>::const_iterator i = list.begin(); i != list.end(); ++i) {
        // Sanity check: shouldn't try to operate on already deleted objects
        if (i->element()) {
            const Finfo* f = i->element()->cinfo()->findFinfo(field);
            const DestFinfo* df = dynamic_cast<const DestFinfo*>(f);
            if (df) {
                FuncId fid = df->getFid();
                // These are the messages to be zapped
                vector<ObjId> caller;
                if (i->element()->getInputMsgs(caller, fid) > 0) {
                    msgs.insert(msgs.end(), caller.begin(), caller.end());
                }
            } else {
                insertSharedMsgs(f, i->element(), msgs);
            }
        }
    }
    // Do the unique/erase bit. My favourite example of C++ hideousity.
    sort(msgs.begin(), msgs.end());
    msgs.erase(unique(msgs.begin(), msgs.end()), msgs.end());
    // Delete them.
    for (vector<ObjId>::iterator i = msgs.begin(); i != msgs.end(); ++i)
        Msg::deleteMsg(*i);
}
References Element::cinfo(), Msg::deleteMsg(), ObjId::element(), Cinfo::findFinfo(), DestFinfo::getFid(), Element::getInputMsgs(), and insertSharedMsgs().
Referenced by addClockMsgs().
error()
void Shell::error (const string & text)
Definition at line 909 of file Shell.cpp.
{
    cout << "Error: Shell:: " << text << endl;
}
expectVector()
void Shell::expectVector (bool flag)
set the gettingVector_ flag
getCwe()
ObjId Shell::getCwe () const
Returns the current working Element of the Shell
Definition at line 555 of file Shell.cpp.
{
    return cwe_;
}
References cwe_.
Referenced by ReadCell::addChannelMessage(), Neuron::buildElist(), pymoose::createElementFromPath(), Neuron::getExprElist(), Neuron::getExprVal(), initCinfo(), and innerFind().
getProcInfo()
const ProcInfo * Shell::getProcInfo (unsigned int index) const
handleAck()
void Shell::handleAck (unsigned int ackNode, unsigned int status)
Generic handler for ack msgs from various nodes. Keeps track of which nodes have responded.
handleAddMsg()
void Shell::handleAddMsg (const Eref & e, string msgType, ObjId src, string srcField, ObjId dest, string destField, unsigned int msgIndex)
Connects src to dest on appropriate fields, with specified msgType. This wrapper function sends the ack back to the master node.
Wrapper function, that does the ack. Other functions also use the inner function to build message trees, so we don't want it to emit multiple acks.
Definition at line 673 of file Shell.cpp.
{
    // Node 0 will have already called innerAddMsg to get the msgIndex
    if (myNode() != 0)
        innerAddMsg(msgType, src, srcField, dest, destField, msgIndex);
    /*
    if ( innerAddMsg( msgType, src, srcField, dest, destField ) )
        ack()->send( Eref( shelle_, 0 ), Shell::myNode(), OkStatus );
    else
        ack()->send( Eref( shelle_, 0), Shell::myNode(), ErrorStatus );
    */
}
References innerAddMsg(), and myNode().
Referenced by initCinfo().
handleCopy()
void Shell::handleCopy (const Eref & e, vector< ObjId > args, string newName, unsigned int n, bool toGlobal, bool copyExtMsgs)
Deep copy of source element to target, renaming it to newName. The Args are orig, newParent, newElm where the newElm is the Id passed in for the root of the copy. All subsequent created Elements should have successive Ids. The copy may generate an array with n entries. Normally only copies msgs within the tree, but if the flag copyExtMsgs is true then it copies external Msgs too.
Definition at line 166 of file ShellCopy.cpp.
{
    if (!innerCopy(args, newName, n, toGlobal, copyExtMsgs)) {
        cout << "Error on Shell::myNode()::Shell::handleCopy for " << newName
             << ", " << n << endl;
    }
    /*
    static const Finfo* ackf =
            Shell::initCinfo()->findFinfo( "ack" );
    static const SrcFinfo2< unsigned int, unsigned int >*
            ack = dynamic_cast< const SrcFinfo2< unsigned int, unsigned int >*
    >( ackf );
    assert( ackf );
    assert( ack );
    if ( innerCopy( args, newName, n, toGlobal, copyExtMsgs ) )
            ack->send( Eref( shelle_, 0 ), Shell::myNode(), ErrorStatus );
    else
            ack->send( Eref( shelle_, 0 ), Shell::myNode(), OkStatus );
    */
}
References innerCopy().
Referenced by initCinfo().
handleCreate()
void Shell::handleCreate (const Eref & e, string type, ObjId parent, Id newElm, string name, NodeBalance nb, unsigned int parentMsgIndex)
This function handles the message request to create an Element. This request specifies the Id of the new Element and is handled on all nodes.
In due course we also have to set up the node decomposition of the Element, but for now the num indicates the total # of array entries. This gets a bit complicated if the Element is a multidim array.
Definition at line 577 of file Shell.cpp.
{
    innerCreate(type, parent, newElm, name, nb, parentMsgIndex);
}
References innerCreate().
Referenced by initCinfo().
handleMove()
void Shell::handleMove (const Eref & e, Id orig, ObjId newParent)
Handler to move Element orig onto the newParent.
Definition at line 773 of file Shell.cpp.
{
    innerMove(orig, newParent);
    /*
    if ( innerMove( orig, newParent ) )
        ack()->send( Eref( shelle_, 0 ), Shell::myNode(), OkStatus );
    else
        ack()->send( Eref( shelle_, 0 ), Shell::myNode(), ErrorStatus );
        */
}
References innerMove().
Referenced by initCinfo().
handleQuit()
void Shell::handleQuit ()
This function is NOT called when simulation ends normally.
Wraps up operations. Doesn't quit instantly, completes the current process cycle first.
Definition at line 893 of file Shell.cpp.
{
    Shell::keepLooping_ = 0;
}
References keepLooping_.
Referenced by initCinfo().
handleSync()
void Shell::handleSync (const Eref & e, Id elm, FuncId fid)
Handles sync of DataHandler indexing across nodes
handleUseClock()
void Shell::handleUseClock (const Eref & e, string path, string field, unsigned int tick, unsigned int msgIndex)
Definition at line 874 of file Shell.cpp.
{
    // cout << q->getProcInfo()->threadIndexInGroup << ": in
    // Shell::handleUseClock with path " << path << endl << flush;
    innerUseClock(path, field, tick, msgIndex);
    /*
    if ( innerUseClock( path, field, tick ) )
        ack()->send( Eref( shelle_, 0 ),
                Shell::myNode(), OkStatus );
    else
        ack()->send( Eref( shelle_, 0 ),
                Shell::myNode(), ErrorStatus );
                */
}
References innerUseClock().
Referenced by initCinfo().
inBlockingParserCall()
bool Shell::inBlockingParserCall () static
True when the parser is in a call which is being blocked because it requires the event loop to complete some actions.
Definition at line 86 of file ShellThreads.cpp.
{
    return isBlockedOnParser_;
}
References isBlockedOnParser_.
initAck()
void Shell::initAck ()
Initialize acks. This call should be done before the 'send' goes out, because with the wonders of threading we might get a response to the 'send' before this call is executed. This MUST be followed by a waitForAck call.
initCinfo()
const Cinfo * Shell::initCinfo () static
Definition at line 50 of file Shell.cpp.
{
    // Value Finfos
    static ReadOnlyValueFinfo<Shell, bool> isRunning(
        "isRunning", "Flag: Checks if simulation is in progress",
        &Shell::isRunning);
    static ValueFinfo<Shell, ObjId> cwe("cwe", "Current working Element",
                                        &Shell::setCwe, &Shell::getCwe);
    // Dest Finfos: Functions handled by Shell
    static DestFinfo handleUseClock(
        "useClock",
        "Deals with assignment of path to a given clock."
        " Arguments: path, field, tick number. ",
        new EpFunc4<Shell, string, string, unsigned int, unsigned int>(
            &Shell::handleUseClock));
    static DestFinfo handleCreate(
        "create", "create( class, parent, newElm, name, numData, isGlobal )",
        new EpFunc6<Shell, string, ObjId, Id, string, NodeBalance,
                    unsigned int>(&Shell::handleCreate));
    static DestFinfo handleDelete(
        "delete",
        "When applied to a regular object, this function operates "
        "on the Id (element) specified by the ObjId argument. "
        "The function deletes the entire object "
        "array on this Id, including all dataEntries on it,"
        "all its messages, and all its children. The DataIndex here "
        "is ignored, and all dataEntries are destroyed. \n"
        "When applied to a message: Destroys only that one specific "
        "message identified by the full ObjId. \n"
        "Args: ObjId\n",
        new EpFunc1<Shell, ObjId>(&Shell::destroy));
    static DestFinfo handleAddMsg(
        "addMsg",
        "Makes a msg. Arguments are:"
        " msgtype, src object, src field, dest object, dest field",
        new EpFunc6<Shell, string, ObjId, string, ObjId, string, unsigned int>(
            &Shell::handleAddMsg));
    static DestFinfo handleQuit(
        "quit", "Stops simulation running and quits the simulator",
        new OpFunc0<Shell>(&Shell::handleQuit));
    static DestFinfo handleMove(
        "move",
        "handleMove( Id orig, Id newParent ): "
        "moves an Element to a new parent",
        new EpFunc2<Shell, Id, ObjId>(&Shell::handleMove));
    static DestFinfo handleCopy(
        "copy",
        "handleCopy( vector< Id > args, string newName, unsigned int nCopies, "
        "bool toGlobal, bool copyExtMsgs ): "
        " The vector< Id > has Id orig, Id newParent, Id newElm. "
        "This function copies an Element and all its children to a new parent."
        " May also expand out the original into nCopies copies."
        " Normally all messages within the copy tree are also copied. "
        " If the flag copyExtMsgs is true, then all msgs going out are also "
        "copied.",
        new EpFunc5<Shell, vector<ObjId>, string, unsigned int, bool, bool>(
            &Shell::handleCopy));
    static DestFinfo setclock(
        "setclock", "Assigns clock ticks. Args: tick#, dt",
        new OpFunc2<Shell, unsigned int, double>(&Shell::doSetClock));
    static Finfo* shellFinfos[] = {&setclock,   &handleCreate,   &handleDelete,
                                   &handleCopy, &handleMove,     &handleAddMsg,
                                   &handleQuit, &handleUseClock, };
    static Dinfo<Shell> d;
    static Cinfo shellCinfo("Shell", Neutral::initCinfo(), shellFinfos,
                            sizeof(shellFinfos) / sizeof(Finfo*),
                            &d
                            // new Dinfo< Shell >()
                            );
#ifdef ENABLE_LOGGER
    float time = (float(clock() - t) / CLOCKS_PER_SEC);
    logger.initializationTime.push_back(time);
#endif
    return &shellCinfo;
}
References Cinfo::Cinfo(), DestFinfo::DestFinfo(), destroy(), doSetClock(), EpFunc1< T, A >::EpFunc1(), EpFunc2< T, A1, A2 >::EpFunc2(), EpFunc4< T, A1, A2, A3, A4 >::EpFunc4(), EpFunc5< T, A1, A2, A3, A4, A5 >::EpFunc5(), EpFunc6< T, A1, A2, A3, A4, A5, A6 >::EpFunc6(), getCwe(), handleAddMsg(), handleCopy(), handleCreate(), handleMove(), handleQuit(), handleUseClock(), Neutral::initCinfo(), isRunning(), OpFunc0< T >::OpFunc0(), OpFunc2< T, A1, A2 >::OpFunc2(), ReadOnlyValueFinfo< T, F >::ReadOnlyValueFinfo(), setCwe(), and ValueFinfo< T, F >::ValueFinfo().
Referenced by init().
innerAddMsg()
const Msg * Shell::innerAddMsg (string msgType, ObjId src, string srcField, ObjId dest, string destField, unsigned int msgIndex)
Connects src to dest on appropriate fields, with specified msgType. This inner function does NOT send an ack. Returns true on success
The actual function that adds messages. Does NOT send an ack. The msgIndex specifies the index on which to place this message. If the value is zero it does an automatic placement. Returns zero on failure.
Definition at line 694 of file Shell.cpp.
{
    /*
    cout << myNode_ << ", Shell::handleAddMsg: " <<
        msgType << ", " << mid <<
        ", src =" << src << "." << srcField <<
        ", dest =" << dest << "." << destField << "\n";
        */
    const Finfo* f1 = src.id.element()->cinfo()->findFinfo(srcField);
    if (f1 == 0) return 0;
    const Finfo* f2 = dest.id.element()->cinfo()->findFinfo(destField);
    if (f2 == 0) return 0;
    // Should have been done before msgs request went out.
    assert(f1->checkTarget(f2));
    Msg* m = 0;
    if (msgType == "diagonal" || msgType == "Diagonal") {
        m = new DiagonalMsg(src.id.element(), dest.id.element(), msgIndex);
    } else if (msgType == "sparse" || msgType == "Sparse") {
        m = new SparseMsg(src.id.element(), dest.id.element(), msgIndex);
    } else if (msgType == "Single" || msgType == "single") {
        m = new SingleMsg(src.eref(), dest.eref(), msgIndex);
    } else if (msgType == "OneToAll" || msgType == "oneToAll") {
        m = new OneToAllMsg(src.eref(), dest.id.element(), msgIndex);
    } else if (msgType == "AllToOne" || msgType == "allToOne") {
        m = new OneToAllMsg(dest.eref(), src.id.element(),
                            msgIndex);  // Little hack.
    } else if (msgType == "OneToOne" || msgType == "oneToOne") {
        m = new OneToOneMsg(src.eref(), dest.eref(), msgIndex);
    } else {
        cout << myNode_
             << ": Error: Shell::handleAddMsg: msgType not known: " << msgType
             << endl;
        return m;
    }
    if (m) {
        if (f1->addMsg(f2, m->mid(), src.id.element())) {
            SetGet1< ObjId >::set( src, "notifyAddMsgSrc", m->mid() );
            SetGet1< ObjId >::set( dest, "notifyAddMsgDest", m->mid() );
            return m;
        }
        delete m;
        m = 0;
    }
    cout << myNode_
         << ": Error: Shell::handleAddMsg: Unable to make/connect Msg: "
         << msgType << " from " << src.id.element()->getName() << " to "
         << dest.id.element()->getName() << endl;
    return m;
}
References Finfo::addMsg(), Finfo::checkTarget(), Element::cinfo(), DiagonalMsg::DiagonalMsg(), Id::element(), ObjId::eref(), Cinfo::findFinfo(), Element::getName(), ObjId::id, Msg::mid(), myNode_, OneToAllMsg::OneToAllMsg(), OneToOneMsg::OneToOneMsg(), SetGet1< A >::set(), SingleMsg::SingleMsg(), and SparseMsg::SparseMsg().
Referenced by addClockMsgs(), doAddMsg(), and handleAddMsg().
innerCopy()
bool Shell::innerCopy (const vector< ObjId > & args, const string & newName, unsigned int n, bool toGlobal, bool copyExtMsgs)
Does actual work of copying. Returns true on success.
Definition at line 149 of file ShellCopy.cpp.
{
    map<Id, Id> tree;
    // args are orig, newParent, newElm.
    assert(args.size() == 3);
    Element* e =
        innerCopyElements(args[0], args[1], args[2], n, toGlobal, tree);
    if (!e) {
        return 0;
    }
    if (newName != "") e->setName(newName);
    // innerCopyData( orig, newParent );
    innerCopyMsgs(tree, n, copyExtMsgs);
    return 1;
}
References innerCopyElements(), innerCopyMsgs(), and Element::setName().
Referenced by handleCopy().
innerCreate()
void Shell::innerCreate (string type, ObjId parent, Id newElm, string name, const NodeBalance & nb, unsigned int msgIndex)
Function that does the actual work of creating a new Element. The Class of the Moose objects formed is specified by type. The NodeBalance specifies how many entries and how they are distributed across nodes. The parentMsgIndex specifies the index for the parent-child message.
This function actually creates the object. Runs on all nodes. Assumes we've already done all the argument checking.
Definition at line 628 of file Shell.cpp.
{
    const Cinfo* c = Cinfo::find(type);
    if (c)
    {
        Element* ret = 0;
        switch (nb.policy) {
            case MooseGlobal:
                ret = new GlobalDataElement(newElm, c, name, nb.numData);
                break;
            case MooseBlockBalance:
                ret = new LocalDataElement(newElm, c, name, nb.numData);
                break;
            case MooseSingleNode:
                cout << "Error: Shell::innerCreate: Yet to implement "
                        "SingleNodeDataElement. Making BlockBalance.\n";
                ret = new LocalDataElement(newElm, c, name, nb.numData);
                break;
        };
        assert(ret);
        adopt(parent, newElm, msgIndex);
        ret->setTick(Clock::lookupDefaultTick(c->name()));
        SetGet1< ObjId >::set( newElm, "notifyCreate", parent );
    }
    else
        assert(0);
}
References adopt(), Cinfo::find(), GlobalDataElement::GlobalDataElement(), LocalDataElement::LocalDataElement(), Clock::lookupDefaultTick(), MooseBlockBalance, MooseGlobal, MooseSingleNode, Cinfo::name(), NodeBalance::numData, NodeBalance::policy, SetGet1< A >::set(), and Element::setTick().
Referenced by handleCreate(), and Cell::setupSolver().
innerMove()
bool Shell::innerMove (Id orig, ObjId newParent)
Moves Element orig onto the newParent.
Definition at line 748 of file Shell.cpp.
{
    static const Finfo* pf = Neutral::initCinfo()->findFinfo("parentMsg");
    static const DestFinfo* pf2 = dynamic_cast<const DestFinfo*>(pf);
    static const FuncId pafid = pf2->getFid();
    static const Finfo* f1 = Neutral::initCinfo()->findFinfo("childOut");
    assert(!(orig == Id()));
    assert(!(newParent.element() == 0));
    ObjId mid = orig.element()->findCaller(pafid);
    Msg::deleteMsg(mid);
    Msg* m = new OneToAllMsg(newParent.eref(), orig.element(), 0);
    assert(m);
    if (!f1->addMsg(pf, m->mid(), newParent.element())) {
        cout << "move: Error: unable to add parent->child msg from "
             << newParent.element()->getName() << " to "
             << orig.element()->getName() << "\n";
        return 0;
    }
    SetGet1< ObjId >::set( orig, "notifyMove", newParent );
    return 1;
}
References Finfo::addMsg(), Msg::deleteMsg(), Id::element(), ObjId::element(), ObjId::eref(), Element::findCaller(), Cinfo::findFinfo(), DestFinfo::getFid(), Element::getName(), Id::Id(), Neutral::initCinfo(), Msg::mid(), OneToAllMsg::OneToAllMsg(), Id::operator==(), and SetGet1< A >::set().
Referenced by handleMove().
innerUseClock()
bool Shell::innerUseClock (string path, string field, unsigned int tick, unsigned int msgIndex)
Sets up scheduling for elements on the path.
Definition at line 851 of file Shell.cpp.
{
    vector<ObjId> list;
    wildcardFind(path, list);  // By default scans only Elements.
    if (list.size() == 0) {
        // cout << "Warning: Shell::innerUseClock: no Elements found on path "
        // << path << endl;
        return 0;
    }
    // string tickField = "proc";
    // Hack to get around a common error.
    if (field.substr(0, 4) == "proc" || field.substr(0, 4) == "Proc")
        field = "proc";
    if (field.substr(0, 4) == "init" || field.substr(0, 4) == "Init")
        field = "init";
    addClockMsgs(list, field, tick, msgIndex);
    for (vector<ObjId>::iterator i = list.begin(); i != list.end(); ++i)
        i->id.element()->innerSetTick(tick);
    return 1;
}
References addClockMsgs(), Id::element(), ObjId::id, Element::innerSetTick(), and wildcardFind().
Referenced by handleUseClock().
isAckPending()
bool Shell::isAckPending () const
Test for receipt of acks from all nodes
isNameValid()
bool Shell::isNameValid (const string & name) static
Checks that the provided name is valid for an object. This returns false if it finds the reserved path chars /#[]
Static func to check if an object name is legal. True if legal.
Definition at line 457 of file Shell.cpp.
{
    return (name.length() > 0 &&
            name.find_first_of("[] #?\"/\\") == string::npos);
}
Referenced by doCopy(), doCreate(), and Neutral::setName().
isParserIdle()
static bool Shell::isParserIdle () static
Flag to indicate if the parser is idle. If so, the main ProcessLoop should also slow down to avoid pounding on the CPUs
isRunning()
bool Shell::isRunning () const
Returns flag to indicate whether simulation is still running
Definition at line 560 of file Shell.cpp.
{
    static Id clockId(1);
    assert(clockId.element() != 0);
    return (reinterpret_cast<const Clock*>(clockId.eref().data()))->isRunning();
}
References Eref::data(), Id::element(), Id::eref(), Id::Id(), and Clock::isRunning().
Referenced by initCinfo().
isSingleThreaded()
static bool Shell::isSingleThreaded () static
True in single-threaded mode. This is a special mode of the system in which it does not start up the event loop at all, and the whole thing operates on one thread, which is ultimately under the control of the parser. Note that this is distinct from running on one core. It is possible, and even recommended, to run in multithread mode even when the system has just one core to run it on.
keepLooping()
bool Shell::keepLooping () static
True as long as the main process loop is looping
Definition at line 899 of file Shell.cpp.
{
    return keepLooping_;
}
References keepLooping_.
Referenced by main().
launchParser()
void Shell::launchParser () static
Launches Parser. Blocking when the parser blocks.
Definition at line 28 of file ShellThreads.cpp.
{
    Id shellId;
    Shell* s = reinterpret_cast< Shell* >( shellId.eref().data() );
    bool quit = 0;
    cout << "moose : " << flush;
    while ( !quit ) {
        string temp;
        cin >> temp;
        if ( temp == "quit" || temp == "q" ) {
            s->doQuit();
            quit = 1;
        }
    }
    cout << "\nQuitting Moose\n" << flush;
}
References Eref::data(), doQuit(), and Id::eref().
Referenced by main().
launchThreads()
static void Shell::launchThreads () static
This function sets up the threading for the entire system. It creates all the worker threads and the threads for handling MPI and handling shell requests.
loadBalance()
void Shell::loadBalance () static
Stub for eventual function to handle load balancing. This must be called to set up default groups.
Regular shell function that requires that the information about the hardware have been loaded in. For now the function just assigns SimGroups
Definition at line 60 of file ShellThreads.cpp.
{
    // Need more info here on how to set up groups distributed over
    // nodes. In fact this will have to be computed _after_ the
    // simulation is loaded. Will also need quite a bit of juggling between
    // nodes when things get really scaled up.
    //
    // Note that the messages have to be rebuilt after this call.
    // Note that this function is called independently on each node.
}
Referenced by init().
myNode()
unsigned int Shell::myNode () static
Definition at line 81 of file ShellThreads.cpp.
{
    return myNode_;
}
References myNode_.
Referenced by PostMaster::addToSendBuf(), PostMaster::addToSetBuf(), PostMaster::dispatchSetBuf(), PostMaster::getMyNode(), LocalDataElement::getNode(), GlobalDataElement::getNode(), MsgElement::getNode(), FieldElement::getNumOnNode(), handleAddMsg(), Eref::isDataHere(), ObjId::isDataHere(), ObjId::isOffNode(), LocalDataElement::LocalDataElement(), main(), mooseMyNode(), TestSched::process(), Element::putTargetsInDigest(), PostMaster::remoteFieldGetVec(), LocalDataElement::setDataSize(), SetGet::strGet(), SetGet::strSet(), testInterNodeOps(), and testShellParserStart().
numCores()
unsigned int Shell::numCores () static
Definition at line 71 of file ShellThreads.cpp.
{
    return numCores_;
}
References numCores_.
numNodes()
unsigned int Shell::numNodes () static
Definition at line 76 of file ShellThreads.cpp.
{
    return numNodes_;
}
References numNodes_.
Referenced by PostMaster::clearPending(), Element::digestMessages(), dispatchBuffers(), filterOffNodeTargets(), PostMaster::getNumNodes(), ObjId::isOffNode(), LocalDataElement::LocalDataElement(), main(), mooseNumNodes(), PostMaster::PostMaster(), Element::putOffNodeTargetsInDigest(), Element::putTargetsInDigest(), PostMaster::remoteGetVec(), LocalDataElement::setDataSize(), testFibonacci(), testFilterOffNodeTargets(), and testSyncSynapseSize().
numProcessThreads()
static unsigned int Shell::numProcessThreads () static
procInfo()
static const ProcInfo * Shell::procInfo () static
Static func for returning the ProcInfo of the shell.
reduceInt()
static unsigned int Shell::reduceInt (unsigned int val) static
Checks for highest 'val' on all nodes
setCwe()
void Shell::setCwe (ObjId cwe)
Assigns the current working Element of the Shell
Definition at line 550 of file Shell.cpp.
{
    cwe_ = val;
}
References cwe_.
Referenced by ReadCell::addChannelMessage(), Neuron::buildElist(), Neuron::getExprElist(), Neuron::getExprVal(), initCinfo(), and testTreeTraversal().
setHardware()
void Shell::setHardware (unsigned int numCores, unsigned int numNodes, unsigned int myNode) static
Assigns the hardware availability. Assumes that each node will have the same number of cores available.
Definition at line 47 of file ShellThreads.cpp.
{
    numCores_ = numCores;
    numNodes_ = numNodes;
    myNode_ = myNode;
    acked_.resize( numNodes, 0 );
}
References acked_, myNode_, numCores_, and numNodes_.
Referenced by init(), and pymoose::initShell().
setShellElement()
void Shell::setShellElement (Element * shelle)
Definition at line 154 of file Shell.cpp.
{
    shelle_ = shelle;
}
References shelle_.
Referenced by init(), and pymoose::initShell().
setupSocketStreamer()
void Shell::setupSocketStreamer (const string host, const int port)
start()
void Shell::start (double runTime)
Sets of a simulation for duration runTime. Handles cases including single-thread, multithread, and multinode
waitForAck()
void Shell::waitForAck ()
test for completion of request. This MUST be preceded by an initAck call.
warning()
void Shell::warning (const string & text)
Definition at line 904 of file Shell.cpp.
{
    moose::showWarn(text);
}
References moose::showWarn().
Referenced by doCreate(), and doMove().
Member Data Documentation
acked_
vector< unsigned int > Shell::acked_ static private
Definition at line 590 of file Shell.h.
Referenced by setHardware().
cwe_
ObjId Shell::cwe_ private
Current working Element.
Definition at line 607 of file Shell.h.
Referenced by destroy(), doFind(), doLoadModel(), getCwe(), setCwe(), and Shell().
doReinit_
bool Shell::doReinit_ static private
Flag to tell system to reinitialize. We use this to defer the actual operation to the 'process' call for a clean reinit.
Definition at line 597 of file Shell.h.
ErrorStatus
const unsigned int Shell::ErrorStatus = ~1 static
Definition at line 463 of file Shell.h.
getBuf_
vector< double* > Shell::getBuf_ private
Buffer into which return values from the 'get' command are placed Only index 0 is used for any single-value 'get' call. If it was the 'getVec' command then the array is filled up
Definition at line 526 of file Shell.h.
Referenced by Shell().
gettingVector_
bool Shell::gettingVector_ private
Flag, used by the 'get' subsystem which maintains a buffer for returned value. True when the returned value is a vector.
Definition at line 532 of file Shell.h.
Referenced by Shell().
isBlockedOnParser_
bool Shell::isBlockedOnParser_ = 0 static private
Flag: True when the parser thread is blocked waiting for some system call to be handled by the threading and the MPI connected nodes.
Definition at line 545 of file Shell.h.
Referenced by inBlockingParserCall().
isParserIdle_
bool Shell::isParserIdle_ static private
Definition at line 604 of file Shell.h.
keepLooping_
bool Shell::keepLooping_ = 1 static private
Flag: Tells the ProcessLoop to keep on going. Should only be altered during a barrier.
Definition at line 551 of file Shell.h.
Referenced by handleQuit(), and keepLooping().
myNode_
unsigned int Shell::myNode_ static private
Identifier for current node
Definition at line 574 of file Shell.h.
Referenced by doAddMsg(), innerAddMsg(), myNode(), and setHardware().
numAcks_
unsigned int Shell::numAcks_ = 0 static private
Array of threads, initialized in launchThreads.
Definition at line 589 of file Shell.h.
numCores_
unsigned int Shell::numCores_ static private
Number of CPU cores in system.
Definition at line 556 of file Shell.h.
Referenced by numCores(), and setHardware().
numGetVecReturns_
unsigned int Shell::numGetVecReturns_ private
Counter, used by the 'get' subsystem in order to keep track of number of returned values, especially for getVec.
Definition at line 538 of file Shell.h.
Referenced by Shell().
numNodes_
unsigned int Shell::numNodes_ static private
Number of nodes in MPI-based system. Each node may have many threads.
Definition at line 569 of file Shell.h.
Referenced by numNodes(), and setHardware().
numProcessThreads_
unsigned int Shell::numProcessThreads_ static private
Number of threads dedicated to the ProcessLoop. The parser thread is the master thread. Additional threads may be created for graphics, but not now.
Definition at line 563 of file Shell.h.
OkStatus
const unsigned int Shell::OkStatus = ~0 static
Definition at line 462 of file Shell.h.
p_
ProcInfo Shell::p_ static private
Shell owns its own ProcInfo, has global thread/node info. Used to talk to parser and for thread specification in setup operations.
Definition at line 581 of file Shell.h.
runtime_
double Shell::runtime_ static private
Simulation run time
Definition at line 602 of file Shell.h.
shelle_
Element* Shell::shelle_ private
Definition at line 519 of file Shell.h.
Referenced by doCopy(), and setShellElement().
threadProcs_
vector< ProcInfo > Shell::threadProcs_ static private
Definition at line 583 of file Shell.h.
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/shell/Shell.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/shell/LoadModels.cpp
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/shell/SaveModels.cpp
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/shell/Shell.cpp
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/shell/ShellCopy.cpp
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/shell/ShellThreads.cpp