MOOSE - Multiscale Object Oriented Simulation Environment: SrcFinfo1< T > Class Template Reference
SrcFinfo1< T > Class Template Reference
#include <SrcFinfo.h>
Public Member Functions
string rttiType () const
void send (const Eref &er, T arg) const
void sendBuffer (const Eref &e, double *buf) const
void sendTo (const Eref &er, Id tgt, T arg) const
void sendVec (const Eref &er, const vector< T > &arg) const
SrcFinfo1 (const string &name, const string &doc)
~SrcFinfo1 ()
Public Member Functions inherited from SrcFinfo
bool addMsg (const Finfo *target, ObjId mid, Element *src) const
bool checkTarget (const Finfo *target) const
BindIndex getBindIndex () const
void registerFinfo (Cinfo *c)
void setBindIndex (BindIndex b)
SrcFinfo (const string &name, const string &doc)
bool strGet (const Eref &tgt, const string &field, string &returnValue) const
bool strSet (const Eref &tgt, const string &field, const string &arg) const
~SrcFinfo ()
Public Member Functions inherited from Finfo
const string & docs () const
Returns documentation string.
Finfo (const string &name, const string &doc)
virtual vector< string > innerDest () const
virtual vector< string > innerSrc () const
const string & name () const
virtual void postCreationFunc (Id newId, Element *newElm) const
virtual ~Finfo ()
Additional Inherited Members
Static Public Member Functions inherited from Finfo
static const Cinfo * initCinfo ()
Static Public Attributes inherited from SrcFinfo
static const BindIndex BadBindIndex = 65535
Detailed Description
template<class T>
class SrcFinfo1< T >
Definition at line 90 of file SrcFinfo.h.
Constructor & Destructor Documentation
~SrcFinfo1()
template<class T > SrcFinfo1< T >::~SrcFinfo1 () inline
Definition at line 93 of file SrcFinfo.h.
{;}
SrcFinfo1()
template<class T > SrcFinfo1< T >::SrcFinfo1 (const string & name, const string & doc) inline
Definition at line 95 of file SrcFinfo.h.
            : SrcFinfo( name, doc )
            { ; }
Referenced by SynHandlerBase::activationOut(), axialOut(), buildProcessVec(), DifShellBase::concentrationOut(), CaConcBase::concOut(), moose::VClamp::currentOut(), derivativeOut(), Eout(), eventOut(), ICaOut(), ChanBase::IkOut(), Neutral::initCinfo(), PoolBase::initPoolBaseCinfo(), instRatesOut(), lookupOut(), lookupOut(), molWtOut(), output(), output(), output(), outputOut(), outputOut(), outputOut(), outputOut(), ChanBase::permeability(), rateOut(), requestOut(), requestOut(), requestOut(), requestOut(), spikeOut(), spikeOut(), spikeOut(), spikeOut(), moose::IntFireBase::spikeOut(), stateOut(), stateOut(), sumRaxialOut(), testMsgField(), testSendMsg(), testSharedMsg(), valueOut(), moose::CompartmentBase::VmOut(), VmOut(), and ChemCompt::voxelVolOut().
Member Function Documentation
rttiType()
template<class T > string SrcFinfo1< T >::rttiType () const inline virtual
Returns the documentation string for the Finfo string docs() const; Returns the RTTI type string for the finfo by referring to an internal virtual function. string type() const; Returns the list of subsidiary SrcFinfos. Used in Shared Finfos, empty otherwise. Goes via internal virtual function. vector< string > src() const; Returns the list of subsidiary destFinfos. Used in SharedFinfos and ValueFinfos, empty otherwise. Goes via internal virtual function. vector< string > dest() const; Returns an RTTI type string for this Finfo.
Reimplemented from Finfo.
Definition at line 203 of file SrcFinfo.h.
{
            return Conv<T>::rttiType();
        }
send()
template<class T > void SrcFinfo1< T >::send (const Eref & er, T arg) const inline
Definition at line 99 of file SrcFinfo.h.
        {
            const vector< MsgDigest >& md = er.msgDigest( getBindIndex() );
            for ( vector< MsgDigest >::const_iterator
                i = md.begin(); i != md.end(); ++i ) {
                const OpFunc1Base< T >* f =
                    dynamic_cast< const OpFunc1Base< T >* >( i->func );
                assert( f );
                for ( vector< Eref >::const_iterator
                    j = i->targets.begin(); j != i->targets.end(); ++j ) {
                    if ( j->dataIndex() == ALLDATA ) {
                        Element* e = j->element();
                        unsigned int start = e->localDataStart();
                        unsigned int end = start + e->numLocalData();
                        for ( unsigned int k = start; k < end; ++k )
                            f->op( Eref( e, k ), arg );
                    } else  {
                        f->op( *j, arg );
                        // Need to send stuff offnode too here. The
                        // target in this case is just the src Element.
                        // Its ObjId gets stuffed into the send buf.
                        // On the other node it will execute
                        // its own send command with the passed in args.
                    }
                }
            }
        }
References ALLDATA, Eref::dataIndex(), Eref::element(), Eref::Eref(), MsgDigest::func, SrcFinfo::getBindIndex(), Element::localDataStart(), Eref::msgDigest(), Element::numLocalData(), and MsgDigest::targets.
Referenced by Function::clearAll(), Function::clearVariables(), Nernst::handleCin(), Nernst::handleCout(), Species::handleMolWtRequest(), Clock::handleReinit(), Clock::handleStep(), Interpol2D::lookupReturn(), MarkovRateTable::process(), MarkovSolverBase::process(), MarkovOdeSolver::process(), IntFire::process(), RandSpike::process(), SpikeGen::process(), moose::VClamp::process(), Arith::process(), Interpol::process(), StimulusTable::process(), Table::process(), TimeTable::process(), DiffAmp::process(), PulseGen::process(), Adaptor::process(), RC::process(), PIDController::process(), IzhikevichNrn::process(), MarkovRateTable::reinit(), MarkovSolverBase::reinit(), MarkovOdeSolver::reinit(), StimulusTable::reinit(), Table::reinit(), DiffAmp::reinit(), PulseGen::reinit(), RC::reinit(), PIDController::reinit(), IzhikevichNrn::reinit(), SrcFinfo1< T >::sendBuffer(), ChanCommon::sendProcessMsgs(), ChanCommon::sendReinitMsgs(), HSolveActive::sendValues(), CubeMesh::setCoords(), ChemCompt::setEntireVolume(), testCreateMsg(), testMsgField(), testSendMsg(), testSharedMsg(), moose::Compartment::vInitProc(), CaConc::vProcess(), moose::Compartment::vProcess(), DifShell::vProcess(), NMDAChan::vProcess(), Stats::vProcess(), moose::AdExIF::vProcess(), moose::AdThreshIF::vProcess(), moose::ExIF::vProcess(), moose::IzhIF::vProcess(), moose::LIF::vProcess(), moose::QIF::vProcess(), GraupnerBrunel2012CaPlasticitySynHandler::vProcess(), SeqSynHandler::vProcess(), SimpleSynHandler::vProcess(), STDPSynHandler::vProcess(), CaConc::vReinit(), moose::Compartment::vReinit(), DifShell::vReinit(), NMDAChan::vReinit(), and SymCompartment::vReinit().
sendBuffer()
template<class T > void SrcFinfo1< T >::sendBuffer (const Eref & e, double * buf) const inline virtual
Sends contents of buffer on to msg targets Buffer has a header with the TgtInfo.
Implements SrcFinfo.
Definition at line 198 of file SrcFinfo.h.
        {
            send( e, Conv< T >::buf2val( &buf ) );
        }
References SrcFinfo1< T >::send().
sendTo()
template<class T > void SrcFinfo1< T >::sendTo (const Eref & er, Id tgt, T arg) const inline
Definition at line 127 of file SrcFinfo.h.
        {
            const vector< MsgDigest >& md = er.msgDigest( getBindIndex() );
            for ( vector< MsgDigest >::const_iterator
                i = md.begin(); i != md.end(); ++i ) {
                const OpFunc1Base< T >* f =
                    dynamic_cast< const OpFunc1Base< T >* >( i->func );
                assert( f );
                for ( vector< Eref >::const_iterator
                    j = i->targets.begin(); j != i->targets.end(); ++j ) {
                    if ( j->element() != tgt.element() )
                        continue; // Wasteful unless very few dests.
                    if ( j->dataIndex() == ALLDATA ) {
                        Element* e = j->element();
                        unsigned int start = e->localDataStart();
                        unsigned int end = start + e->numLocalData();
                        for ( unsigned int k = start; k < end; ++k )
                            f->op( Eref( e, k ), arg );
                    } else  {
                        f->op( *j, arg );
                        // Need to send stuff offnode too here. The
                        // target in this case is just the src Element.
                        // Its ObjId gets stuffed into the send buf.
                        // On the other node it will execute
                        // its own send command with the passed in args.
                    }
                }
            }
        }
References ALLDATA, Eref::dataIndex(), Eref::element(), Id::element(), Eref::Eref(), MsgDigest::func, SrcFinfo::getBindIndex(), Element::localDataStart(), Eref::msgDigest(), Element::numLocalData(), and MsgDigest::targets.
sendVec()
template<class T > void SrcFinfo1< T >::sendVec (const Eref & er, const vector< T > & arg) const inline
Each target gets successive entries from the arg vector. Rolls over if the # of targets exceeds vector size. Fails totally if the targets are off-node.
Definition at line 162 of file SrcFinfo.h.
        {
            if ( arg.size() == 0 )
                return;
            const vector< MsgDigest >& md = er.msgDigest( getBindIndex() );
            unsigned int argPos = 0;
            for ( vector< MsgDigest >::const_iterator
                i = md.begin(); i != md.end(); ++i ) {
                const OpFunc1Base< T >* f =
                    dynamic_cast< const OpFunc1Base< T >* >( i->func );
                assert( f );
                for ( vector< Eref >::const_iterator
                    j = i->targets.begin(); j != i->targets.end(); ++j ) {
                    if ( j->dataIndex() == ALLDATA ) {
                        Element* e = j->element();
                        unsigned int start = e->localDataStart();
                        unsigned int end = start + e->numLocalData();
                        for ( unsigned int k = start; k < end; ++k ) {
                            f->op( Eref( e, k ), arg[ argPos++ ] );
                            if ( argPos >= arg.size() )
                                argPos = 0;
                        }
                    } else  {
                        f->op( *j, arg[ argPos++ ] );
                            if ( argPos >= arg.size() )
                                argPos = 0;
                        // Need to send stuff offnode too here. The
                        // target in this case is just the src Element.
                        // Its ObjId gets stuffed into the send buf.
                        // On the other node it will execute
                        // its own send command with the passed in args.
                    }
                }
            }
        }
References ALLDATA, Eref::dataIndex(), Eref::element(), Eref::Eref(), MsgDigest::func, SrcFinfo::getBindIndex(), Element::localDataStart(), Eref::msgDigest(), Element::numLocalData(), and MsgDigest::targets.
The documentation for this class was generated from the following file:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/basecode/SrcFinfo.h