MOOSE - Multiscale Object Oriented Simulation Environment: HHGateF2D Class Reference
HHGateF2D Class Reference
#include <HHGateF2D.h>
Public Member Functions
HHGateF2D ()
HHGateF2D (Id originalChanId, Id originalGateId)
double lookupA (vector< double > v) const
double lookupB (vector< double > v) const
void lookupBoth (double v, double c, double *A, double *B) const
HHGateF2D & operator= (const HHGateF2D &)
Public Member Functions inherited from HHGateF
string getAlpha (const Eref &e) const
string getBeta (const Eref &e) const
string getInf (const Eref &e) const
string getTau (const Eref &e) const
HHGateF ()
HHGateF (Id originalChanId, Id originalGateId)
double lookupA (double v) const
double lookupB (double v) const
void lookupBoth (double v, double *A, double *B) const
HHGateF & operator= (const HHGateF &)
void setAlpha (const Eref &e, const string expr)
Set the expression for evaluating alpha.
void setBeta (const Eref &e, const string expr)
Set the expression for evaluating beta.
void setInf (const Eref &e, const string expr)
Set the expression for evaluating inf.
void setTau (const Eref &e, const string expr)
Set the expression for evaluating tau.
Public Member Functions inherited from HHGateBase
bool checkOriginal (Id id, const string &field) const
HHGateBase ()
HHGateBase (Id originalChanId, Id originalGateId)
bool isOriginalChannel (Id id) const
bool isOriginalGate (Id id) const
Id originalChannelId () const
Id originalGateId () const
Static Public Member Functions
static const Cinfo * initCinfo ()
Static Public Member Functions inherited from HHGateF
static const Cinfo * initCinfo ()
Static Public Member Functions inherited from HHGateBase
static const Cinfo * initCinfo ()
Private Attributes
double conc_
Additional Inherited Members
Protected Attributes inherited from HHGateF
exprtk::expression< double > alpha_
string alphaExpr_
Store the user-specified expression strings.
double alphav_
exprtk::expression< double > beta_
string betaExpr_
double betav_
double infv_
exprtk::parser< double > parser_
exprtk::symbol_table< double > symTab_
bool tauInf_
double tauv_
double v_
Protected Attributes inherited from HHGateBase
Id originalChanId_
Id originalGateId_
Detailed Description
Definition at line 20 of file HHGateF2D.h.
Constructor & Destructor Documentation
HHGateF2D() [1/2]
HHGateF2D::HHGateF2D ()
Definition at line 91 of file HHGateF2D.cpp.
{
    cerr << "Warning: HHGateF2D::HHGateF2D(): this should never be called"
         << endl;
}
HHGateF2D() [2/2]
HHGateF2D::HHGateF2D (Id originalChanId, Id originalGateId)
Definition at line 97 of file HHGateF2D.cpp.
    : HHGateF(originalChanId, originalGateId)
{
    symTab_.add_variable("c", conc_);
    symTab_.add_variable("alpha", alphav_);
    symTab_.add_variable("beta", betav_);
    symTab_.add_variable("tau", tauv_);
    symTab_.add_variable("inf", infv_);
    alpha_.register_symbol_table(symTab_);
    beta_.register_symbol_table(symTab_);
}
References HHGateF::HHGateF().
Referenced by HHChannelF2D::innerCreateGate().
Member Function Documentation
initCinfo()
const Cinfo * HHGateF2D::initCinfo () static
Definition at line 14 of file HHGateF2D.cpp.
{
    // Field definitions.
    static ReadOnlyLookupValueFinfo<HHGateF2D, vector<double>, double> A(
        "A",
        "lookupA: Compute the A gate value from two doubles, passed"
        " in as a vector.\n"
        " This is same as `alpha(V)` the gate transition rate"
        " from closed to open state in the Hodgkin-Huxley formulation.\n"
        " Unlike HHGate2D, HHGateF2D uses formula"
        " evaluation to get more accurate value, which is also"
        " slower.",
        &HHGateF2D::lookupA);
    static ReadOnlyLookupValueFinfo<HHGateF2D, vector<double>, double> B(
        "B",
        "lookupB: Compute B gate value from two doubles in a vector.\n"
        " This is same as `alpha(V)+beta(V)` in the Hodgkin-Huxley formulation,"
        " where alpha(V) is the gate transition rate from closed to open and "
        "beta(V)"
        " is the transition rate from open to closed state.",
        &HHGateF2D::lookupB);
    // DestFinfos
    static Finfo* HHGateF2DFinfos[] = {
        &A,  // ReadOnlyLookupValue
        &B,  // ReadOnlyLookupValue
    };
    static string doc[] = {
        "Name",
        "HHGateF2D",
        "Author",
        "Subhasis Ray, 2025, CHINTA. This is based on HHGate2D"
        " implementation by Niraj Dudani, 2009, NCBS.",
        "Description",
        "HHGateF2D: Gate for Hodkgin-Huxley type channels, equivalent to the"
        " m and h terms on the Na squid channel and the n term on K.\n"
        " This is specialized for dependency on two variables, voltage"
        " and concentration (usually [Ca2+]).\n"
        " Unlike HHGate2D, HHGateF2D evaluates the formulas for the gate"
        " parameters directly. This is slower than HHGate2D's"
        " interpolation-table lookup, but numerically more accurate, which can"
        " be important when the concentration can vary in an exponential"
        " scale. It also saves one from the large memory requirement for"
        " storing large 2D arrays.\n"
        " The formulas must be specified as in the form f(v, c),"
        " where v and c are the variable names. For example:\n"
        " \"1500/(1 + (c / 1.5e-4 * exp(-77 * v)))\"\n"
        " While the names correspond to voltage and concentration, they can be"
        " any two parameters mapped to the corresponding fields in"
        " HHChannelF2D.\n"
        " Additionally, like HHGateF, HHGateF2D provides the following "
        " predefined variable names to facilitate intermediate "
        " calculations:\n"
        "  `alpha` for forward rate,\n"
        "  `beta` for backward rate,\n"
        "  `tau` for time constant, and\n"
        "  `inf` for steady state open fraction\n"
        " as per Hodgkin and Huxley's formulation.\n"
    };
    static Dinfo<HHGateF2D> dinfo;
    static Cinfo HHGateF2DCinfo("HHGateF2D", HHGateF::initCinfo(),
                                HHGateF2DFinfos,
                                sizeof(HHGateF2DFinfos) / sizeof(Finfo*),
                                &dinfo, doc, sizeof(doc) / sizeof(string));
    return &HHGateF2DCinfo;
}
References HHGateF::initCinfo().
lookupA()
double HHGateF2D::lookupA (vector< double > v) const
Definition at line 137 of file HHGateF2D.cpp.
{
    if(v.size() < 2) {
        cerr << "Error: HHGateF2D::lookupA: 2 real numbers needed to lookup "
                "2D table.\n";
        return 0.0;
    }
    if(v.size() > 2) {
        cerr << "Error: HHGateF2D::getAValue: Only 2 real numbers needed to "
                "lookup 2D table. "
                "Using only first 2.\n";
    }
    v_ = v[0];
    conc_ = v[1];
    return tauInf_ ? beta_.value() / alpha_.value() : alpha_.value();
}
References conc_, and HHGateF::v_.
lookupB()
double HHGateF2D::lookupB (vector< double > v) const
Definition at line 155 of file HHGateF2D.cpp.
{
    if(v.size() < 2) {
        cerr << "Error: HHGateF2D::lookupB: 2 real numbers needed to lookup "
                "2D table.\n";
        return 0.0;
    }
    if(v.size() > 2) {
        cerr << "Error: HHGateF2D::getAValue: Only 2 real numbers needed to "
                "lookup 2D table. "
                "Using only first 2.\n";
    }
    return tauInf_ ? 1.0 / alpha_.value() : alpha_.value() + beta_.value();
}
lookupBoth()
void HHGateF2D::lookupBoth (double v, double c, double * A, double * B) const
Single call to get both A and B values in a single lookup
Definition at line 172 of file HHGateF2D.cpp.
{
    *A = lookupA(vector<double>{v, c});
    *B = lookupB(vector<double>{v, c});
    // cerr << "HHGateF2D::lookupBoth(" << v << ", " << c << ",*A=" << * A << ",
    // *B="<< * B << ")" << endl;
}
Referenced by HHChannelF2D::vProcess(), and HHChannelF2D::vReinit().
operator=()
HHGateF2D & HHGateF2D::operator= (const HHGateF2D & rhs)
Definition at line 109 of file HHGateF2D.cpp.
{
    // protect from self-assignment.
    if(this == &rhs)
        return *this;
    v_ = rhs.v_;
    conc_ = rhs.conc_;
    symTab_.add_variable("v", v_);
    symTab_.add_variable("c", conc_);
    symTab_.add_variable("alpha", alphav_);
    symTab_.add_variable("beta", betav_);
    symTab_.add_variable("tau", tauv_);
    symTab_.add_variable("inf", infv_);
    symTab_.add_constants();
    alpha_.register_symbol_table(symTab_);
    beta_.register_symbol_table(symTab_);
    alphaExpr_ = rhs.alphaExpr_;
    betaExpr_ = rhs.betaExpr_;
    parser_.compile(alphaExpr_, alpha_);
    parser_.compile(betaExpr_, beta_);
    tauInf_ = rhs.tauInf_;
    return *this;
}
References HHGateF::alphaExpr_, HHGateF::betaExpr_, conc_, HHGateF::tauInf_, and HHGateF::v_.
Member Data Documentation
conc_
double HHGateF2D::conc_ mutable private
Definition at line 36 of file HHGateF2D.h.
Referenced by lookupA(), and operator=().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/biophysics/HHGateF2D.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/biophysics/HHGateF2D.cpp