MOOSE - Multiscale Object Oriented Simulation Environment: SrcFinfo3< T1, T2, T3 > Class Template Reference
SrcFinfo3< T1, T2, T3 > Class Template Reference
#include <SrcFinfo.h>
Public Member Functions
string rttiType () const
void send (const Eref &e, const T1 &arg1, const T2 &arg2, const T3 &arg3) const
void sendBuffer (const Eref &e, double *buf) const
SrcFinfo3 (const string &name, const string &doc)
~SrcFinfo3 ()
Public Member Functions inherited from SrcFinfo
bool addMsg (const Finfo *target, ObjId mid, Element *src) const
bool checkTarget (const Finfo *target) const
BindIndex getBindIndex () const
void registerFinfo (Cinfo *c)
void setBindIndex (BindIndex b)
SrcFinfo (const string &name, const string &doc)
bool strGet (const Eref &tgt, const string &field, string &returnValue) const
bool strSet (const Eref &tgt, const string &field, const string &arg) const
~SrcFinfo ()
Public Member Functions inherited from Finfo
const string & docs () const
Returns documentation string.
Finfo (const string &name, const string &doc)
virtual vector< string > innerDest () const
virtual vector< string > innerSrc () const
const string & name () const
virtual void postCreationFunc (Id newId, Element *newElm) const
virtual ~Finfo ()
Additional Inherited Members
Static Public Member Functions inherited from Finfo
static const Cinfo * initCinfo ()
Static Public Attributes inherited from SrcFinfo
static const BindIndex BadBindIndex = 65535
Detailed Description
template<class T1, class T2, class T3>
class SrcFinfo3< T1, T2, T3 >
Definition at line 289 of file SrcFinfo.h.
Constructor & Destructor Documentation
~SrcFinfo3()
template<class T1 , class T2 , class T3 > SrcFinfo3< T1, T2, T3 >::~SrcFinfo3 () inline
Definition at line 292 of file SrcFinfo.h.
{;}
SrcFinfo3()
template<class T1 , class T2 , class T3 > SrcFinfo3< T1, T2, T3 >::SrcFinfo3 (const string & name, const string & doc) inline
Definition at line 294 of file SrcFinfo.h.
            : SrcFinfo( name, doc )
            { ; }
Referenced by psdListOut(), and spineListOut().
Member Function Documentation
rttiType()
template<class T1 , class T2 , class T3 > string SrcFinfo3< T1, T2, T3 >::rttiType () const inline virtual
Returns the documentation string for the Finfo string docs() const; Returns the RTTI type string for the finfo by referring to an internal virtual function. string type() const; Returns the list of subsidiary SrcFinfos. Used in Shared Finfos, empty otherwise. Goes via internal virtual function. vector< string > src() const; Returns the list of subsidiary destFinfos. Used in SharedFinfos and ValueFinfos, empty otherwise. Goes via internal virtual function. vector< string > dest() const; Returns an RTTI type string for this Finfo.
Reimplemented from Finfo.
Definition at line 330 of file SrcFinfo.h.
{
            return Conv<T1>::rttiType() + "," + Conv< T2 >::rttiType() +
                "," + Conv<T3>::rttiType();
        }
send()
template<class T1 , class T2 , class T3 > void SrcFinfo3< T1, T2, T3 >::send (const Eref & e, const T1 & arg1, const T2 & arg2, const T3 & arg3) const inline
Definition at line 298 of file SrcFinfo.h.
        {
            const vector< MsgDigest >& md = e.msgDigest( getBindIndex() );
            for ( vector< MsgDigest >::const_iterator
                i = md.begin(); i != md.end(); ++i ) {
                const OpFunc3Base< T1, T2, T3 >* f =
                    dynamic_cast< const OpFunc3Base< T1, T2, T3 >* >(
                                    i->func );
                assert( f );
                for ( vector< Eref >::const_iterator
                    j = i->targets.begin(); j != i->targets.end(); ++j ) {
                    if ( j->dataIndex() == ALLDATA ) {
                        Element* e = j->element();
                        unsigned int start = e->localDataStart();
                        unsigned int end = start + e->numData();
                        for ( unsigned int k = start; k < end; ++k )
                            f->op( Eref( e, k ), arg1, arg2, arg3 );
                    } else  {
                        f->op( *j, arg1, arg2, arg3 );
                    }
                }
            }
        }
References ALLDATA, Eref::dataIndex(), Eref::element(), Eref::Eref(), MsgDigest::func, SrcFinfo::getBindIndex(), Element::localDataStart(), Eref::msgDigest(), Element::numData(), and MsgDigest::targets.
Referenced by SrcFinfo3< T1, T2, T3 >::sendBuffer(), and NeuroMesh::transmitSpineInfo().
sendBuffer()
template<class T1 , class T2 , class T3 > void SrcFinfo3< T1, T2, T3 >::sendBuffer (const Eref & e, double * buf) const inline virtual
Sends contents of buffer on to msg targets Buffer has a header with the TgtInfo.
Implements SrcFinfo.
Definition at line 323 of file SrcFinfo.h.
        {
            const T1& arg1 = Conv< T1 >::buf2val( &buf );
            const T2& arg2 = Conv< T2 >::buf2val( &buf );
            send( e, arg1, arg2, Conv< T3 >::buf2val( &buf ) );
        }
References SrcFinfo3< T1, T2, T3 >::send().
The documentation for this class was generated from the following file:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/basecode/SrcFinfo.h