MOOSE - Multiscale Object Oriented Simulation Environment: DifBufferBase Class Reference
DifBufferBase Class Reference abstract
#include <DifBufferBase.h>
Public Member Functions
void buffer (const Eref &e, double C)
DifBufferBase ()
void fluxFromIn (const Eref &e, double innerC, double innerThickness)
void fluxFromOut (const Eref &e, double outerC, double outerThickness)
double getActivation (const Eref &e) const
double getBBound (const Eref &e) const
double getBFree (const Eref &e) const
double getBTot (const Eref &e) const
double getD (const Eref &e) const
double getDiameter (const Eref &e) const
double getInnerArea (const Eref &e) const
double getKb (const Eref &e) const
double getKf (const Eref &e) const
double getLength (const Eref &e) const
double getOuterArea (const Eref &e) const
unsigned int getShapeMode (const Eref &e) const
double getThickness (const Eref &e) const
double getVolume (const Eref &e) const
void process (const Eref &e, ProcPtr p)
void reinit (const Eref &e, ProcPtr p)
void setActivation (const Eref &e, double value)
void setBBound (const Eref &e, double value)
void setBFree (const Eref &e, double value)
void setBTot (const Eref &e, double value)
void setD (const Eref &e, double value)
void setDiameter (const Eref &e, double value)
void setInnerArea (const Eref &e, double innerArea)
void setKb (const Eref &e, double value)
void setKf (const Eref &e, double value)
void setLength (const Eref &e, double value)
void setOuterArea (const Eref &e, double outerArea)
void setShapeMode (const Eref &e, unsigned int value)
void setThickness (const Eref &e, double value)
void setVolume (const Eref &e, double volume)
virtual void vBuffer (const Eref &e, double C)=0
virtual void vFluxFromIn (const Eref &e, double innerC, double innerThickness)=0
virtual void vFluxFromOut (const Eref &e, double outerC, double outerThickness)=0
virtual double vGetActivation (const Eref &e) const =0
virtual double vGetBBound (const Eref &e) const =0
virtual double vGetBFree (const Eref &e) const =0
virtual double vGetBTot (const Eref &e) const =0
virtual double vGetD (const Eref &e) const =0
virtual double vGetDiameter (const Eref &e) const =0
virtual double vGetInnerArea (const Eref &e) const =0
virtual double vGetKb (const Eref &e) const =0
virtual double vGetKf (const Eref &e) const =0
virtual double vGetLength (const Eref &e) const =0
virtual double vGetOuterArea (const Eref &e) const =0
virtual unsigned int vGetShapeMode (const Eref &e) const =0
virtual double vGetThickness (const Eref &e) const =0
virtual double vGetVolume (const Eref &e) const =0
virtual void vProcess (const Eref &e, ProcPtr p)=0
virtual void vReinit (const Eref &e, ProcPtr p)=0
virtual void vSetActivation (const Eref &e, double value)=0
virtual void vSetBBound (const Eref &e, double value)=0
virtual void vSetBFree (const Eref &e, double value)=0
virtual void vSetBTot (const Eref &e, double value)=0
virtual void vSetD (const Eref &e, double value)=0
virtual void vSetDiameter (const Eref &e, double diameter)=0
virtual void vSetInnerArea (const Eref &e, double innerArea)=0
virtual void vSetKb (const Eref &e, double value)=0
virtual void vSetKf (const Eref &e, double value)=0
virtual void vSetLength (const Eref &e, double length)=0
virtual void vSetOuterArea (const Eref &e, double outerArea)=0
virtual void vSetShapeMode (const Eref &e, unsigned int shapeMode)=0
virtual void vSetThickness (const Eref &e, double thickness)=0
virtual void vSetVolume (const Eref &e, double volume)=0
Static Public Member Functions
static const Cinfo * initCinfo ()
static SrcFinfo2< double, double > * innerDifSourceOut ()
static SrcFinfo2< double, double > * outerDifSourceOut ()
static SrcFinfo4< double, double, double, double > * reactionOut ()
Detailed Description
Definition at line 14 of file DifBufferBase.h.
Constructor & Destructor Documentation
DifBufferBase()
DifBufferBase::DifBufferBase ()
Definition at line 231 of file DifBufferBase.cpp.
{ ; }
Member Function Documentation
buffer()
void DifBufferBase::buffer (const Eref & e, double C)
Definition at line 378 of file DifBufferBase.cpp.
{
  vBuffer(e,C);
}
References vBuffer().
Referenced by initCinfo().
fluxFromIn()
void DifBufferBase::fluxFromIn (const Eref & e, double innerC, double innerThickness)
Definition at line 396 of file DifBufferBase.cpp.
{
  vFluxFromIn(e,innerC,innerThickness);
}
References vFluxFromIn().
Referenced by initCinfo().
fluxFromOut()
void DifBufferBase::fluxFromOut (const Eref & e, double outerC, double outerThickness)
Definition at line 392 of file DifBufferBase.cpp.
{
  vFluxFromOut(e,outerC,outerThickness);
}
References vFluxFromOut().
Referenced by initCinfo().
getActivation()
double DifBufferBase::getActivation (const Eref & e) const
Definition at line 235 of file DifBufferBase.cpp.
{
  return vGetActivation(e);
}
References vGetActivation().
Referenced by initCinfo().
getBBound()
double DifBufferBase::getBBound (const Eref & e) const
Definition at line 256 of file DifBufferBase.cpp.
{
  return vGetBBound(e);
}
References vGetBBound().
Referenced by initCinfo().
getBFree()
double DifBufferBase::getBFree (const Eref & e) const
Definition at line 246 of file DifBufferBase.cpp.
{
  return vGetBFree(e);
}
References vGetBFree().
Referenced by initCinfo().
getBTot()
double DifBufferBase::getBTot (const Eref & e) const
Definition at line 265 of file DifBufferBase.cpp.
{
  return vGetBTot(e);
}
References vGetBTot().
Referenced by initCinfo().
getD()
double DifBufferBase::getD (const Eref & e) const
Definition at line 296 of file DifBufferBase.cpp.
{
  return vGetD(e);
}
References vGetD().
Referenced by initCinfo().
getDiameter()
double DifBufferBase::getDiameter (const Eref & e) const
Definition at line 331 of file DifBufferBase.cpp.
{
  return vGetDiameter(e);
}
References vGetDiameter().
Referenced by initCinfo().
getInnerArea()
double DifBufferBase::getInnerArea (const Eref & e) const
Definition at line 371 of file DifBufferBase.cpp.
{
  return vGetInnerArea(e);
}
References vGetInnerArea().
Referenced by initCinfo().
getKb()
double DifBufferBase::getKb (const Eref & e) const
Definition at line 286 of file DifBufferBase.cpp.
{
  return vGetKb(e);
}
References vGetKb().
Referenced by initCinfo().
getKf()
double DifBufferBase::getKf (const Eref & e) const
Definition at line 276 of file DifBufferBase.cpp.
{
  return vGetKf(e);
}
References vGetKf().
Referenced by initCinfo().
getLength()
double DifBufferBase::getLength (const Eref & e) const
Definition at line 321 of file DifBufferBase.cpp.
{
  return vGetLength(e);
}
References vGetLength().
Referenced by initCinfo().
getOuterArea()
double DifBufferBase::getOuterArea (const Eref & e) const
Definition at line 361 of file DifBufferBase.cpp.
{
  return vGetOuterArea(e);
}
References vGetOuterArea().
Referenced by initCinfo().
getShapeMode()
unsigned int DifBufferBase::getShapeMode (const Eref & e) const
Definition at line 311 of file DifBufferBase.cpp.
{
  return vGetShapeMode(e);
}
References vGetShapeMode().
Referenced by initCinfo().
getThickness()
double DifBufferBase::getThickness (const Eref & e) const
Definition at line 341 of file DifBufferBase.cpp.
{
  return vGetThickness(e);
}
References vGetThickness().
Referenced by initCinfo().
getVolume()
double DifBufferBase::getVolume (const Eref & e) const
Definition at line 351 of file DifBufferBase.cpp.
{
  return vGetVolume(e);
}
References vGetVolume().
Referenced by initCinfo().
initCinfo()
const Cinfo * DifBufferBase::initCinfo () static
Definition at line 29 of file DifBufferBase.cpp.
{
  static DestFinfo process( "process",
                            "Handles process call",
                            new ProcOpFunc< DifBufferBase >(  &DifBufferBase::process) );
  static DestFinfo reinit( "reinit",
                           "Reinit happens only in stage 0",
                           new ProcOpFunc< DifBufferBase >( &DifBufferBase::reinit));
  static Finfo* processShared[] = {
    &process,
    &reinit
  };
  static SharedFinfo proc(
              "proc",
              "Here we create 2 shared finfos to attach with the Ticks. This is because we want to perform DifBufferBase "
              "computations in 2 stages, much as in the Compartment object. "
              "In the first stage we send out the concentration value to other DifBufferBases and Buffer elements. We also",
              processShared,
              sizeof( processShared ) / sizeof( Finfo* ));
  static DestFinfo concentration("concentration",
                                 "Receives concentration (from DifShell).",
                                 new EpFunc1<DifBufferBase, double>(&DifBufferBase::buffer));
  static Finfo* bufferShared[] = {
    &concentration, DifBufferBase::reactionOut()
  };
  static SharedFinfo buffer( "buffer",
                             "This is a shared message with DifShell. "
                             "During stage 0:\n "
                             " - DifBufferBase sends ion concentration\n"
                             " - Buffer updates buffer concentration and sends it back immediately using a call-back.\n"
                             " - DifShell updates the time-derivative ( dC / dt ) \n"
                             "\n"
                             "During stage 1: \n"
                             " - DifShell advances concentration C \n\n"
                             "This scheme means that the Buffer does not need to be scheduled, and it does its computations when "
                             "it receives a cue from the DifShell. May not be the best idea, but it saves us from doing the above "
                             "computations in 3 stages instead of 2." ,
                             bufferShared,
                             sizeof( bufferShared ) / sizeof( Finfo* ));
  static DestFinfo fluxFromOut( "fluxFromOut",
                                "Destination message",
                                new EpFunc2< DifBufferBase, double, double > ( &DifBufferBase::fluxFromOut ));
  static Finfo* innerDifShared[] = {
    &fluxFromOut,
    DifBufferBase::innerDifSourceOut()
  };
  static SharedFinfo innerDif( "innerDif",
                               "This shared message (and the next) is between DifBufferBases: adjoining shells exchange information to "
                               "find out the flux between them. "
                               "Using this message, an inner shell sends to, and receives from its outer shell." ,
                               innerDifShared,
                               sizeof( innerDifShared ) / sizeof( Finfo* ));
  static DestFinfo fluxFromIn( "fluxFromIn", "",
                               new EpFunc2< DifBufferBase, double, double> ( &DifBufferBase::fluxFromIn) );
  static Finfo* outerDifShared[] = {
    &fluxFromIn,
    DifBufferBase::outerDifSourceOut(),
  };
  static  SharedFinfo outerDif( "outerDif",
                                "Using this message, an outer shell sends to, and receives from its inner shell." ,
                                outerDifShared,
                                sizeof( outerDifShared ) / sizeof( Finfo* ));
  // Field defs
  static ElementValueFinfo<DifBufferBase, double> activation("activation",
                                 "Ion concentration from incoming conc message.",
                                 &DifBufferBase::setActivation,
                                 &DifBufferBase::getActivation);
  static ElementValueFinfo<DifBufferBase, double> kf("kf",
                             "Forward rate constant of buffer molecules 1/mM/s (?)",
                             &DifBufferBase::setKf,
                             &DifBufferBase::getKf);
  static ElementValueFinfo<DifBufferBase, double> kb("kb",
                             "Backward rate constant of buffer molecules. 1/s",
                             &DifBufferBase::setKb,
                             &DifBufferBase::getKb);
  static ElementValueFinfo<DifBufferBase, double> D("D",
                            "Diffusion constant of buffer molecules. m^2/s",
                            &DifBufferBase::setD,
                            &DifBufferBase::getD);
  static ElementValueFinfo<DifBufferBase, double> bFree("bFree",
                            "Free buffer concentration",
                            &DifBufferBase::setBFree,
                            &DifBufferBase::getBFree);
  static ElementValueFinfo<DifBufferBase, double> bBound("bBound",
                             "Bound buffer concentration",
                             &DifBufferBase::setBBound,
                             &DifBufferBase::getBBound);
  static ElementValueFinfo<DifBufferBase, double> bTot("bTot",
                               "Total buffer concentration.",
                               &DifBufferBase::setBTot,
                               &DifBufferBase::getBTot);
  static ElementValueFinfo<DifBufferBase, double> length("length",
                             "Length of shell",
                             &DifBufferBase::setLength,
                             &DifBufferBase::getLength);
  static ElementValueFinfo<DifBufferBase, double> diameter("diameter",
                               "Diameter of shell",
                               &DifBufferBase::setDiameter,
                               &DifBufferBase::getDiameter);
  static ElementValueFinfo<DifBufferBase, unsigned int> shapeMode("shapeMode",
                                  "shape of the shell: SHELL=0, SLICE=SLAB=1, USERDEF=3",
                                  &DifBufferBase::setShapeMode,
                                  &DifBufferBase::getShapeMode);
  static ElementValueFinfo<DifBufferBase, double> thickness("thickness",
                                "Thickness of shell",
                                &DifBufferBase::setThickness,
                                &DifBufferBase::getThickness);
  static ElementValueFinfo<DifBufferBase, double> innerArea("innerArea",
                                "Inner area of shell",
                                &DifBufferBase::setInnerArea,
                                &DifBufferBase::getInnerArea);
  static ElementValueFinfo<DifBufferBase, double> outerArea("outerArea",
                                "Outer area of shell",
                                &DifBufferBase::setOuterArea,
                                &DifBufferBase::getOuterArea);
  static ElementValueFinfo< DifBufferBase, double> volume( "volume", "",
                               &DifBufferBase::setVolume,
                               &DifBufferBase::getVolume );
  // DestFinfo
  static Finfo * difBufferFinfos[] = {
    // Field definitions
    &activation,
    &D,
    &bFree,
    &bBound,
    &bTot,
    &kf,
    &kb,
    //&prevFree,
    //&prevBound,
    &length,
    &diameter,
    &shapeMode,
    &thickness,
    &innerArea,
    &outerArea,
    &volume,
    // SharedFinfo definitions
    &proc,
    &buffer,
    &innerDif,
    &outerDif,
    //
    reactionOut(),
    innerDifSourceOut(),
    outerDifSourceOut(),
    // DestFinfo definitions
    &concentration,
  };
  static string doc[] = {
    "Name", "DifBufferBase",
    "Author", "Subhasis Ray (ported from GENESIS2)",
    "Description", "Models diffusible buffer where total concentration is constant. It is"
    " coupled with a DifShell.",
  };
  static ZeroSizeDinfo<int> dinfo;
  static Cinfo difBufferCinfo(
                  "DifBufferBase",
                  Neutral::initCinfo(),
                  difBufferFinfos,
                  sizeof(difBufferFinfos)/sizeof(Finfo*),
                  &dinfo,
                  doc,
                  sizeof(doc)/sizeof(string));
  return &difBufferCinfo;
}
References buffer(), Cinfo::Cinfo(), DestFinfo::DestFinfo(), ElementValueFinfo< T, F >::ElementValueFinfo(), EpFunc1< T, A >::EpFunc1(), EpFunc2< T, A1, A2 >::EpFunc2(), fluxFromIn(), fluxFromOut(), getActivation(), getBBound(), getBFree(), getBTot(), getD(), getDiameter(), getInnerArea(), getKb(), getKf(), getLength(), getOuterArea(), getShapeMode(), getThickness(), getVolume(), Neutral::initCinfo(), innerDifSourceOut(), outerDifSourceOut(), process(), ProcOpFunc< T >::ProcOpFunc(), reactionOut(), reinit(), setActivation(), setBBound(), setBFree(), setBTot(), setD(), setDiameter(), setInnerArea(), setKb(), setKf(), setLength(), setOuterArea(), setShapeMode(), setThickness(), setVolume(), and SharedFinfo::SharedFinfo().
Referenced by DifBuffer::initCinfo().
innerDifSourceOut()
SrcFinfo2< double, double > * DifBufferBase::innerDifSourceOut () static
Definition at line 17 of file DifBufferBase.cpp.
{
  static SrcFinfo2< double, double > sourceOut("innerDifSourceOut",
                           "Sends out source information.");
  return &sourceOut;
}
References SrcFinfo2< T1, T2 >::SrcFinfo2().
Referenced by initCinfo(), DifBuffer::vProcess(), and DifBuffer::vReinit().
outerDifSourceOut()
SrcFinfo2< double, double > * DifBufferBase::outerDifSourceOut () static
Definition at line 23 of file DifBufferBase.cpp.
{
  static SrcFinfo2< double, double > sourceOut("outerDifSourceOut",
                           "Sends out source information.");
  return &sourceOut;
}
References SrcFinfo2< T1, T2 >::SrcFinfo2().
Referenced by initCinfo(), DifBuffer::vProcess(), and DifBuffer::vReinit().
process()
void DifBufferBase::process (const Eref & e, ProcPtr p)
Definition at line 388 of file DifBufferBase.cpp.
{
  vProcess( e, p );
}
References vProcess().
Referenced by initCinfo().
reactionOut()
SrcFinfo4< double, double, double, double > * DifBufferBase::reactionOut () static
Definition at line 7 of file DifBufferBase.cpp.
{
  static SrcFinfo4< double, double, double, double > reactionOut(
                                 "reactionOut",
                                 "Sends out reaction rates (forward and backward), and concentrations"
                                 " (free-buffer and bound-buffer molecules).");
  return &reactionOut;
}
References SrcFinfo4< T1, T2, T3, T4 >::SrcFinfo4().
Referenced by initCinfo(), and DifBuffer::vProcess().
reinit()
void DifBufferBase::reinit (const Eref & e, ProcPtr p)
Definition at line 383 of file DifBufferBase.cpp.
{
  vReinit( e, p );
}
References vReinit().
Referenced by initCinfo().
setActivation()
void DifBufferBase::setActivation (const Eref & e, double value)
Definition at line 240 of file DifBufferBase.cpp.
{
  vSetActivation(e,value);
}
References vSetActivation().
Referenced by initCinfo().
setBBound()
void DifBufferBase::setBBound (const Eref & e, double value)
Definition at line 260 of file DifBufferBase.cpp.
{
  vSetBBound(e,value);
}
References vSetBBound().
Referenced by initCinfo().
setBFree()
void DifBufferBase::setBFree (const Eref & e, double value)
Definition at line 251 of file DifBufferBase.cpp.
{
  vSetBFree(e,value);
}
References vSetBFree().
Referenced by initCinfo().
setBTot()
void DifBufferBase::setBTot (const Eref & e, double value)
Definition at line 270 of file DifBufferBase.cpp.
{
  vSetBTot(e,value);
}
References vSetBTot().
Referenced by initCinfo().
setD()
void DifBufferBase::setD (const Eref & e, double value)
Definition at line 301 of file DifBufferBase.cpp.
{
  vSetD(e,value);
}
References vSetD().
Referenced by initCinfo().
setDiameter()
void DifBufferBase::setDiameter (const Eref & e, double value)
Definition at line 326 of file DifBufferBase.cpp.
{
  vSetDiameter(e,diameter);
}
References vSetDiameter().
Referenced by initCinfo().
setInnerArea()
void DifBufferBase::setInnerArea (const Eref & e, double innerArea)
Definition at line 366 of file DifBufferBase.cpp.
{
  vSetInnerArea(e,innerArea);
}
References vSetInnerArea().
Referenced by initCinfo().
setKb()
void DifBufferBase::setKb (const Eref & e, double value)
Definition at line 291 of file DifBufferBase.cpp.
{
  vSetKb(e,value);
}
References vSetKb().
Referenced by initCinfo().
setKf()
void DifBufferBase::setKf (const Eref & e, double value)
Definition at line 281 of file DifBufferBase.cpp.
{
  vSetKf(e,value);
}
References vSetKf().
Referenced by initCinfo().
setLength()
void DifBufferBase::setLength (const Eref & e, double value)
Definition at line 316 of file DifBufferBase.cpp.
{
  vSetLength(e,length);
}
References vSetLength().
Referenced by initCinfo().
setOuterArea()
void DifBufferBase::setOuterArea (const Eref & e, double outerArea)
Definition at line 356 of file DifBufferBase.cpp.
{
  vSetOuterArea(e,outerArea);
}
References vSetOuterArea().
Referenced by initCinfo().
setShapeMode()
void DifBufferBase::setShapeMode (const Eref & e, unsigned int value)
Definition at line 306 of file DifBufferBase.cpp.
{
  vSetShapeMode(e,shapeMode);
}
References vSetShapeMode().
Referenced by initCinfo().
setThickness()
void DifBufferBase::setThickness (const Eref & e, double value)
Definition at line 336 of file DifBufferBase.cpp.
{
  vSetThickness(e,thickness);
}
References vSetThickness().
Referenced by initCinfo().
setVolume()
void DifBufferBase::setVolume (const Eref & e, double volume)
Definition at line 346 of file DifBufferBase.cpp.
{
  vSetVolume(e,volume);
}
References vSetVolume().
Referenced by initCinfo().
vBuffer()
virtual void DifBufferBase::vBuffer (const Eref & e, double C) pure virtual
Implemented in DifBuffer.
Referenced by buffer().
vFluxFromIn()
virtual void DifBufferBase::vFluxFromIn (const Eref & e, double innerC, double innerThickness) pure virtual
Implemented in DifBuffer.
Referenced by fluxFromIn().
vFluxFromOut()
virtual void DifBufferBase::vFluxFromOut (const Eref & e, double outerC, double outerThickness) pure virtual
Implemented in DifBuffer.
Referenced by fluxFromOut().
vGetActivation()
virtual double DifBufferBase::vGetActivation (const Eref & e) const pure virtual
Implemented in DifBuffer.
Referenced by getActivation().
vGetBBound()
virtual double DifBufferBase::vGetBBound (const Eref & e) const pure virtual
Implemented in DifBuffer.
Referenced by getBBound().
vGetBFree()
virtual double DifBufferBase::vGetBFree (const Eref & e) const pure virtual
Implemented in DifBuffer.
Referenced by getBFree().
vGetBTot()
virtual double DifBufferBase::vGetBTot (const Eref & e) const pure virtual
Implemented in DifBuffer.
Referenced by getBTot().
vGetD()
virtual double DifBufferBase::vGetD (const Eref & e) const pure virtual
Implemented in DifBuffer.
Referenced by getD().
vGetDiameter()
virtual double DifBufferBase::vGetDiameter (const Eref & e) const pure virtual
Implemented in DifBuffer.
Referenced by getDiameter().
vGetInnerArea()
virtual double DifBufferBase::vGetInnerArea (const Eref & e) const pure virtual
Implemented in DifBuffer.
Referenced by getInnerArea().
vGetKb()
virtual double DifBufferBase::vGetKb (const Eref & e) const pure virtual
Implemented in DifBuffer.
Referenced by getKb().
vGetKf()
virtual double DifBufferBase::vGetKf (const Eref & e) const pure virtual
Implemented in DifBuffer.
Referenced by getKf().
vGetLength()
virtual double DifBufferBase::vGetLength (const Eref & e) const pure virtual
Implemented in DifBuffer.
Referenced by getLength().
vGetOuterArea()
virtual double DifBufferBase::vGetOuterArea (const Eref & e) const pure virtual
Implemented in DifBuffer.
Referenced by getOuterArea().
vGetShapeMode()
virtual unsigned int DifBufferBase::vGetShapeMode (const Eref & e) const pure virtual
Implemented in DifBuffer.
Referenced by getShapeMode().
vGetThickness()
virtual double DifBufferBase::vGetThickness (const Eref & e) const pure virtual
Implemented in DifBuffer.
Referenced by getThickness().
vGetVolume()
virtual double DifBufferBase::vGetVolume (const Eref & e) const pure virtual
Implemented in DifBuffer.
Referenced by getVolume().
vProcess()
virtual void DifBufferBase::vProcess (const Eref & e, ProcPtr p) pure virtual
Implemented in DifBuffer.
Referenced by process().
vReinit()
virtual void DifBufferBase::vReinit (const Eref & e, ProcPtr p) pure virtual
Implemented in DifBuffer.
Referenced by reinit().
vSetActivation()
virtual void DifBufferBase::vSetActivation (const Eref & e, double value) pure virtual
Implemented in DifBuffer.
Referenced by setActivation().
vSetBBound()
virtual void DifBufferBase::vSetBBound (const Eref & e, double value) pure virtual
Implemented in DifBuffer.
Referenced by setBBound().
vSetBFree()
virtual void DifBufferBase::vSetBFree (const Eref & e, double value) pure virtual
Implemented in DifBuffer.
Referenced by setBFree().
vSetBTot()
virtual void DifBufferBase::vSetBTot (const Eref & e, double value) pure virtual
Implemented in DifBuffer.
Referenced by setBTot().
vSetD()
virtual void DifBufferBase::vSetD (const Eref & e, double value) pure virtual
Implemented in DifBuffer.
Referenced by setD().
vSetDiameter()
virtual void DifBufferBase::vSetDiameter (const Eref & e, double diameter) pure virtual
Implemented in DifBuffer.
Referenced by setDiameter().
vSetInnerArea()
virtual void DifBufferBase::vSetInnerArea (const Eref & e, double innerArea) pure virtual
Implemented in DifBuffer.
Referenced by setInnerArea().
vSetKb()
virtual void DifBufferBase::vSetKb (const Eref & e, double value) pure virtual
Implemented in DifBuffer.
Referenced by setKb().
vSetKf()
virtual void DifBufferBase::vSetKf (const Eref & e, double value) pure virtual
Implemented in DifBuffer.
Referenced by setKf().
vSetLength()
virtual void DifBufferBase::vSetLength (const Eref & e, double length) pure virtual
Implemented in DifBuffer.
Referenced by setLength().
vSetOuterArea()
virtual void DifBufferBase::vSetOuterArea (const Eref & e, double outerArea) pure virtual
Implemented in DifBuffer.
Referenced by setOuterArea().
vSetShapeMode()
virtual void DifBufferBase::vSetShapeMode (const Eref & e, unsigned int shapeMode) pure virtual
Implemented in DifBuffer.
Referenced by setShapeMode().
vSetThickness()
virtual void DifBufferBase::vSetThickness (const Eref & e, double thickness) pure virtual
Implemented in DifBuffer.
Referenced by setThickness().
vSetVolume()
virtual void DifBufferBase::vSetVolume (const Eref & e, double volume) pure virtual
Implemented in DifBuffer.
Referenced by setVolume().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/biophysics/DifBufferBase.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/biophysics/DifBufferBase.cpp