MOOSE - Multiscale Object Oriented Simulation Environment: MMEnzyme1 Class Reference
MMEnzyme1 Class Reference
#include <RateTerm.h>
Public Member Functions
RateTerm * copyWithVolScaling (double vol, double sub, double prd) const
unsigned int getReactants (vector< unsigned int > &molIndex) const
MMEnzyme1 (double Km, double kcat, unsigned int enz, unsigned int sub)
double operator() (const double *S) const
Computes the rate. The argument is the molecule array.
Public Member Functions inherited from MMEnzymeBase
unsigned int getEnzIndex () const
double getR1 () const
Used by Zombie to return rate terms.
double getR2 () const
Used by Zombie to return rate terms.
MMEnzymeBase (double Km, double kcat, unsigned int enz)
void rescaleVolume (short comptIndex, const vector< short > &compartmentLookup, double ratio)
void setKcat (double kcat)
void setKm (double Km)
void setR1 (double Km)
Used by Zombie to assign rate terms.
void setR2 (double kcat)
Used by Zombie to assign rate terms.
void setRates (double Km, double kcat)
Public Member Functions inherited from RateTerm
RateTerm ()
virtual ~RateTerm ()
Private Attributes
unsigned int sub_
Additional Inherited Members
Static Public Attributes inherited from RateTerm
static const double EPSILON = 1.0e-6
Protected Attributes inherited from MMEnzymeBase
unsigned int enz_
double kcat_
double Km_
Detailed Description
Definition at line 146 of file RateTerm.h.
Constructor & Destructor Documentation
MMEnzyme1()
MMEnzyme1::MMEnzyme1 (double Km, double kcat, unsigned int enz, unsigned int sub) inline
Definition at line 149 of file RateTerm.h.
        : MMEnzymeBase( Km, kcat, enz ), sub_( sub )
    {
        ;
    }
References MMEnzymeBase::MMEnzymeBase(), and sub_.
Referenced by copyWithVolScaling(), and Stoich::installMMenz().
Member Function Documentation
copyWithVolScaling()
RateTerm * MMEnzyme1::copyWithVolScaling (double vol, double sub, double prd) const inline virtual
Duplicates rate term and then applies volume scaling. Arguments are volume of reference voxel, product of vol/refVol for all substrates: applied to R1 product of vol/refVol for all products: applied to R2
Note that unless the reaction is cross-compartment, the vol/refVol will be one.
Implements RateTerm.
Definition at line 172 of file RateTerm.h.
    {
        double ratio = vol * sub * NA;
        return new MMEnzyme1( ratio * Km_, kcat_, enz_, sub_);
    }
References MMEnzymeBase::enz_, MMEnzymeBase::kcat_, MMEnzymeBase::Km_, MMEnzyme1(), NA, and sub_.
getReactants()
unsigned int MMEnzyme1::getReactants (vector< unsigned int > & molIndex) const inline virtual
This function finds the reactant indices in the vector S. It returns the number of substrates found, which are the first entries in molIndex. The products are the remaining ones. Note that it does NOT find products for unidirectional reactions, which is a bit of a problem.
Implements RateTerm.
Definition at line 164 of file RateTerm.h.
    {
        molIndex.resize( 2 );
        molIndex[0] = enz_;
        molIndex[1] = sub_;
        return 2;
    }
References MMEnzymeBase::enz_, and sub_.
operator()()
double MMEnzyme1::operator() (const double * S) const inline virtual
Computes the rate. The argument is the molecule array.
Implements RateTerm.
Definition at line 156 of file RateTerm.h.
    {
        //  assert( S[ sub_ ] >= -EPSILON
        auto val = ( kcat_ * S[ sub_ ] * S[ enz_ ] ) / ( Km_ + S[ sub_ ] );
        assert(! std::isnan(val));
        return val;
    }
References MMEnzymeBase::enz_, MMEnzymeBase::kcat_, MMEnzymeBase::Km_, and sub_.
Member Data Documentation
sub_
unsigned int MMEnzyme1::sub_ private
Definition at line 180 of file RateTerm.h.
Referenced by copyWithVolScaling(), getReactants(), MMEnzyme1(), and operator()().
The documentation for this class was generated from the following file:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/ksolve/RateTerm.h