MOOSE - Multiscale Object Oriented Simulation Environment: KinSparseMatrix Class Reference
KinSparseMatrix Class Reference
#include <KinSparseMatrix.h>
Public Member Functions
double computeRowRate (unsigned int row, const vector< double > &v) const
void fireReac (unsigned int reacIndex, vector< double > &S, double direction) const
void getGillespieDependence (unsigned int row, vector< unsigned int > &cols) const
void truncateRow (unsigned int maxColumnIndex)
Public Member Functions inherited from SparseMatrix< int >
void addRow (unsigned int rowNum, const vector< int > &entry, const vector< unsigned int > &colIndexArg)
void addRow (unsigned int rowNum, const vector< int > &row)
void clear ()
const vector< unsigned int > & colIndex () const
int get (unsigned int row, unsigned int column) const
unsigned int getColumn (unsigned int col, vector< int > &entry, vector< unsigned int > &rowIndex) const
unsigned int getRow (unsigned int row, const int **entry, const unsigned int **colIndex) const
unsigned int getRow (unsigned int row, vector< int > &e, vector< unsigned int > &c) const
const vector< int > & matrixEntry () const
Here we expose the sparse matrix for MOOSE use.
unsigned int nColumns () const
unsigned int nEntries () const
unsigned int nRows () const
void pairFill (const vector< unsigned int > &row, const vector< unsigned int > &col, int value)
void print () const
void printInternal () const
void printTriplet (const vector< Triplet< int > > &t)
void reorderColumns (const vector< unsigned int > &colMap)
const vector< unsigned int > & rowStart () const
void set (unsigned int row, unsigned int column, int value)
void setSize (unsigned int nrows, unsigned int ncolumns)
SparseMatrix ()
SparseMatrix (unsigned int nrows, unsigned int ncolumns)
void transpose ()
void tripletFill (const vector< unsigned int > &row, const vector< unsigned int > &col, const vector< int > &z, bool retainSize=false)
void unset (unsigned int row, unsigned int column)
Private Attributes
vector< unsigned int > rowTruncated_
Additional Inherited Members
Protected Attributes inherited from SparseMatrix< int >
vector< unsigned int > colIndex_
Non-zero entries in the SparseMatrix.
vector< int > N_
unsigned int ncolumns_
unsigned int nrows_
vector< unsigned int > rowStart_
Start index in the N_ and colIndex_ vectors, of each row.
Detailed Description
Definition at line 13 of file KinSparseMatrix.h.
Member Function Documentation
computeRowRate()
double KinSparseMatrix::computeRowRate (unsigned int row, const vector< double > & v) const
Returns all non-zero column indices, for the specified row. This gives reac #s in orig matrix, and molecule #s in the transposed matrix Not needed. The getRow function does all this, more efficiently. int getRowIndices(unsigned int row, vector< unsigned int >& indices); Returns the dot product of the specified row with the vector v. v corresponds to the vector of reaction rates. v must have nColumns entries.
Returns the dot product of the specified row with the vector v. v corresponds to the vector of reaction rates. v must have nColumns entries.
Definition at line 28 of file KinSparseMatrix.cpp.
{
    assert( nColumns() == 0 || row < nRows() );
    assert( v.size() == nColumns() );
    const int* entry = 0;
    const unsigned int* colIndex = 0;
    unsigned int numEntries = getRow( row, &entry, &colIndex );
    const int* end = entry + numEntries;
    double ret = 0.0;
    for ( const int* i = entry; i != end; ++i )
    {
        ret += *i * v[ *colIndex++ ];
        assert(! std::isnan(ret));
    }
    //assert ( !std::isnan(ret) );
    return ret;
}
References SparseMatrix< T >::getRow(), SparseMatrix< T >::nColumns(), and SparseMatrix< T >::nRows().
Referenced by VoxelPools::updateRates().
fireReac()
void KinSparseMatrix::fireReac (unsigned int reacIndex, vector< double > & S, double direction) const
Fires a stochastic reaction: It undergoes a single transition This operation updates the mol concs due to the reacn. Direction is +1 or -1, specifies direction of reaction
This too operates on the transposed matrix, because we need to get all the molecules for a given reac: a column in the original N matrix. Direction [-1,+1] specifies whether the reaction is forward or backward.
Definition at line 105 of file KinSparseMatrix.cpp.
{
    assert( ncolumns_ == S.size() && reacIndex < nrows_ );
    unsigned int rowBeginIndex = rowStart_[ reacIndex ];
    // vector< int >::const_iterator rowEnd = N_.begin() + rowStart_[ reacIndex + 1];
    vector< int >::const_iterator rowBegin =
        N_.begin() + rowBeginIndex;
    vector< int >::const_iterator rowEnd =
        N_.begin() + rowTruncated_[ reacIndex ];
    vector< unsigned int >::const_iterator molIndex =
        colIndex_.begin() + rowBeginIndex;
    for ( vector< int >::const_iterator i = rowBegin; i != rowEnd; ++i )
    {
        double& x = S[ *molIndex++ ];
        x += *i * direction;
        x *= (x > 0 );
        // assert( S[ *molIndex ] + *i * direction >= 0.0 );
        // S[ *molIndex++ ] += *i * direction;
    }
}
References rowTruncated_.
Referenced by GssaVoxelPools::advance().
getGillespieDependence()
void KinSparseMatrix::getGillespieDependence (unsigned int row, vector< unsigned int > & deps) const
Does a special self-product of the specified row. Output is the set of nonzero indices in the product abs(Rij) * neg(Rjk) for the specified index i, where neg(val) is true only if val < 0.
Has to operate on transposed matrix row argument refers to reac# in this transformed situation. Fills up 'deps' with reac::s that depend on the row argument. Does NOT ensure that list is unique.
Definition at line 56 of file KinSparseMatrix.cpp.
{
    deps.resize( 0 );
    // vector< unsigned int > deps;
    for ( unsigned int i = 0; i < nrows_; ++i )
    {
        // i is index for reac # here. Note that matrix is transposed.
        unsigned int j = rowStart_[ row ];
        unsigned int jend = rowStart_[ row + 1 ];
        unsigned int k = rowStart_[ i ];
        unsigned int kend = rowStart_[ i + 1 ];
        while ( j < jend && k < kend )
        {
            if ( colIndex_[ j ] == colIndex_[ k ] )
            {
                /* Pre 28 Nov 2015. Why below zero? Shouldn't it be any?
                if ( N_[ k ] < 0 ) {
                    deps.push_back( i );
                }
                */
                assert( round( N_[k] ) != 0 );
                deps.push_back( i );
                ++j;
                ++k;
            }
            else if ( colIndex_[ j ] < colIndex_[ k ] )
            {
                ++j;
            }
            else if ( colIndex_[ j ] > colIndex_[ k ] )
            {
                ++k;
            }
            else
            {
                assert( 0 );
            }
        }
    }
}
Referenced by Gsolve::rebuildGssaSystem().
truncateRow()
void KinSparseMatrix::truncateRow (unsigned int maxColumnIndex)
This function generates a new internal list of rowEnds, such that they are all less than the maxColumnIndex. It is used because in fireReac we don't want to update all the molecules, only those that are variable.
Definition at line 134 of file KinSparseMatrix.cpp.
{
    rowTruncated_.resize( nrows_, 0 );
    if ( colIndex_.size() == 0 )
        return;
    for ( unsigned int i = 0; i < nrows_; ++i )
    {
        unsigned int endCol = rowStart_[ i ];
        for ( unsigned int j = rowStart_[ i ];
                j < rowStart_[ i + 1 ]; ++j )
        {
            if ( colIndex_[ j ] < maxColumnIndex )
            {
                endCol = j + 1;
            }
            else
            {
                break;
            }
        }
        rowTruncated_[ i ] = endCol;
    }
}
References rowTruncated_.
Referenced by Gsolve::rebuildGssaSystem().
Member Data Documentation
rowTruncated_
vector< unsigned int > KinSparseMatrix::rowTruncated_ private
End colIndex for rows (molecules in the transposed matrix) so that only variable molecules are below the colIndex.
Definition at line 67 of file KinSparseMatrix.h.
Referenced by fireReac(), and truncateRow().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/ksolve/KinSparseMatrix.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/ksolve/KinSparseMatrix.cpp