MOOSE - Multiscale Object Oriented Simulation Environment: GlobalDataElement Class Reference
GlobalDataElement Class Reference
#include <GlobalDataElement.h>
Public Member Functions
Element * copyElement (Id newParent, Id newId, unsigned int n, bool toGlobal) const
unsigned int getNode (unsigned int dataIndex) const
Inherited virtual. Returns node location of specified object.
unsigned int getNumOnNode (unsigned int node) const
Inherited virtual.
GlobalDataElement (Id id, const Cinfo *c, const string &name, unsigned int numData=1)
GlobalDataElement (Id id, const Element *orig, unsigned int n)
bool isGlobal () const
True if there is a copy of every dataEntry on all nodes.
unsigned int localDataStart () const
Inherited virtual. Returns index of first entry on this node.
unsigned int numData () const
Inherited virtual. Returns number of data entries.
unsigned int rawIndex (unsigned int dataId) const
Converts dataId to index on current node.
unsigned int startDataIndex (unsigned int node) const
Inherited virtual. Returns start dataIndex on specified node.
~GlobalDataElement ()
Public Member Functions inherited from DataElement
char * data (unsigned int rawIndex, unsigned int fieldIndex=0) const
DataElement (Id id, const Cinfo *c, const string &name, unsigned int numData=1)
DataElement (Id id, const Element *orig, unsigned int n, unsigned int startEntry)
bool hasFields () const
Do not define getNode() or rawIndex() funcs, those are derived.
unsigned int numField (unsigned int rawIndex) const
Define only in derived classes: getNode(unsigned int dataIndex) const;.
unsigned int numLocalData () const
Defined only in derived classes: unsigned int numData() const;.
void resize (unsigned int newNumData)
void resizeField (unsigned int rawIndex, unsigned int newNumField)
unsigned int totNumLocalField () const
void zombieSwap (const Cinfo *newCinfo)
Virtual func.
~DataElement ()
Public Member Functions inherited from Element
void addMsg (ObjId mid)
void addMsgAndFunc (ObjId mid, FuncId fid, BindIndex bindIndex)
const Cinfo * cinfo () const
void clearAllMsgs ()
Used upon ending of MOOSE session, to rapidly clear out messages.
void clearBinding (BindIndex b)
void digestMessages ()
void dropAllMsgsFromSrc (Id src)
void dropMsg (ObjId mid)
Element (Id id, const Cinfo *c, const string &name)
unsigned int findBinding (MsgFuncBinding b) const
ObjId findCaller (FuncId fid) const
unsigned int getFieldsOfOutgoingMsg (ObjId mid, vector< pair< BindIndex, FuncId > > &ret) const
unsigned int getInputMsgs (vector< ObjId > &caller, FuncId fid) const
unsigned int getInputsWithTgtIndex (vector< pair< Id, unsigned int > > &ret, const DestFinfo *finfo) const
const vector< MsgFuncBinding > * getMsgAndFunc (BindIndex b) const
unsigned int getMsgSourceAndSender (FuncId fid, vector< ObjId > &src, vector< string > &sender) const
unsigned int getMsgTargetAndFunctions (DataId srcDataId, const SrcFinfo *finfo, vector< ObjId > &tgt, vector< string > &func) const
vector< ObjId > getMsgTargets (DataId srcDataId, const SrcFinfo *finfo) const
const string & getName () const
unsigned int getNeighbors (vector< Id > &ret, const Finfo *finfo) const
int getTick () const
bool hasMsgs (BindIndex b) const
Id id () const
void innerSetTick (unsigned int tick)
bool isDoomed () const
void markAsDoomed ()
void markRewired ()
const vector< MsgDigest > & msgDigest (unsigned int index)
const vector< ObjId > & msgIn () const
void printMsgDigest (unsigned int srcIndex, unsigned int dataIndex) const
void putOffNodeTargetsInDigest (unsigned int srcNum, vector< vector< bool > > &targetNodes)
void putTargetsInDigest (unsigned int srcNum, const MsgFuncBinding &mfb, const FuncOrder &fo, vector< vector< bool > > &targetNodes)
void replaceCinfo (const Cinfo *newCinfo)
Support function for zombieSwap, replaces Cinfo.
void setName (const string &val)
void setTick (int t)
void showFields () const
void showMsg () const
virtual ~Element ()
Additional Inherited Members
Static Public Member Functions inherited from Element
static void destroyElementTree (const vector< Id > &tree)
Detailed Description
This is the usual class for managing the MOOSE interface. Handles the data. Elaborates on base class for how it handles destruction. Does block-wise partitioning between nodes.
Definition at line 21 of file GlobalDataElement.h.
Constructor & Destructor Documentation
GlobalDataElement() [1/2]
GlobalDataElement::GlobalDataElement (Id id, const Cinfo * c, const string & name, unsigned int numData = 1)
This is the main constructor, used by Shell::innerCreate which makes most Elements. Also used to create base Elements to init the simulator in main.cpp. Id is the Id of the new Element Cinfo is the class name is its name numData is the number of data entries, defaults to a singleton. The isGlobal flag specifies whether the created objects should be replicated on all nodes, or partitioned without replication.
Definition at line 14 of file GlobalDataElement.cpp.
    :
        DataElement( id, c, name, numData )
{;}
References DataElement::DataElement().
Referenced by buildFinfoElement(), init(), Msg::initMsgManagers(), Shell::innerCreate(), Cinfo::makeCinfoElements(), showFields(), test2ArgSetVec(), testArith(), testCreateMsg(), testGet(), testLookupSetGet(), testMsgField(), testMsgSrcDestFields(), testSendMsg(), testSendSpike(), testSetGet(), testSetGetDouble(), testSetGetExtField(), testSetGetSynapse(), testSetGetVec(), testSetRepeat(), testSharedMsg(), testSparseMsg(), testStrGet(), and testStrSet().
GlobalDataElement() [2/2]
GlobalDataElement::GlobalDataElement (Id id, const Element * orig, unsigned int n)
This constructor copies over the original n times. It is used for doing all copies, in Shell::innerCopyElements.
Definition at line 28 of file GlobalDataElement.cpp.
    :
        DataElement( id, orig, n, 0 )
{;}
References DataElement::DataElement().
Referenced by copyElement().
~GlobalDataElement()
GlobalDataElement::~GlobalDataElement ()
Virtual Destructor
Definition at line 35 of file GlobalDataElement.cpp.
{;}
Member Function Documentation
copyElement()
Element * GlobalDataElement::copyElement (Id newParent, Id newId, unsigned int n, bool toGlobal) const virtual
Virtual copier. Makes a copy of self.
Implements Element.
Definition at line 38 of file GlobalDataElement.cpp.
{
    if ( toGlobal )
        return new GlobalDataElement( newId, this, n );
    else
        return new LocalDataElement( newId, this, n );
}
References GlobalDataElement(), and LocalDataElement::LocalDataElement().
getNode()
unsigned int GlobalDataElement::getNode (unsigned int dataIndex) const virtual
Inherited virtual. Returns node location of specified object.
Implements Element.
Definition at line 58 of file GlobalDataElement.cpp.
{
    // Assume numData = 95. DataId = 0-9: 0, DataId=80-89:8, DataId >= 90:9
    return Shell::myNode();
}
References Shell::myNode().
getNumOnNode()
unsigned int GlobalDataElement::getNumOnNode (unsigned int node) const virtual
Inherited virtual.
Implements Element.
Definition at line 67 of file GlobalDataElement.cpp.
{
    return numLocalData();
}
References DataElement::numLocalData().
isGlobal()
bool GlobalDataElement::isGlobal () const inline virtual
True if there is a copy of every dataEntry on all nodes.
Implements Element.
Definition at line 79 of file GlobalDataElement.h.
{
            return true;
        }
localDataStart()
unsigned int GlobalDataElement::localDataStart () const inline virtual
Inherited virtual. Returns index of first entry on this node.
Implements Element.
Definition at line 63 of file GlobalDataElement.h.
{
            return 0;
        }
numData()
unsigned int GlobalDataElement::numData () const virtual
Inherited virtual. Returns number of data entries.
Implements Element.
Definition at line 53 of file GlobalDataElement.cpp.
{
    return numLocalData();
}
References DataElement::numLocalData().
rawIndex()
unsigned int GlobalDataElement::rawIndex (unsigned int dataId) const virtual
Converts dataId to index on current node.
Implements Element.
Definition at line 63 of file GlobalDataElement.cpp.
{
    return dataId;
}
startDataIndex()
unsigned int GlobalDataElement::startDataIndex (unsigned int node) const inline virtual
Inherited virtual. Returns start dataIndex on specified node.
Implements Element.
Definition at line 71 of file GlobalDataElement.h.
        {
            return 0;
        }
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/basecode/GlobalDataElement.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/basecode/GlobalDataElement.cpp