MOOSE - Multiscale Object Oriented Simulation Environment: CaConcBase Class Reference
CaConcBase Class Reference abstract
#include <CaConcBase.h>
Public Member Functions
CaConcBase ()
void current (const Eref &e, double I)
void currentFraction (const Eref &e, double I, double fraction)
void decrease (const Eref &e, double I)
double getB (const Eref &e) const
double getCa (const Eref &e) const
double getCaBasal (const Eref &e) const
double getCeiling (const Eref &e) const
double getDiameter (const Eref &e) const
double getFloor (const Eref &e) const
double getLength (const Eref &e) const
double getTau (const Eref &e) const
double getThickness (const Eref &e) const
void increase (const Eref &e, double I)
void process (const Eref &, ProcPtr info)
void reinit (const Eref &, ProcPtr info)
void setB (const Eref &e, double val)
void setCa (const Eref &e, double val)
void setCaBasal (const Eref &e, double val)
void setCeiling (const Eref &e, double val)
void setDiameter (const Eref &e, double val)
void setFloor (const Eref &e, double val)
void setLength (const Eref &e, double val)
void setTau (const Eref &e, double val)
void setThickness (const Eref &e, double val)
void updateDimensions (const Eref &e)
virtual void vCurrent (const Eref &e, double I)=0
virtual void vCurrentFraction (const Eref &e, double I, double fraction)=0
virtual void vDecrease (const Eref &e, double I)=0
virtual double vGetB (const Eref &e) const =0
virtual double vGetCa (const Eref &e) const =0
virtual double vGetCaBasal (const Eref &e) const =0
virtual double vGetCeiling (const Eref &e) const =0
virtual double vGetFloor (const Eref &e) const =0
virtual double vGetTau (const Eref &e) const =0
virtual void vIncrease (const Eref &e, double I)=0
virtual void vProcess (const Eref &, ProcPtr info)=0
virtual void vReinit (const Eref &, ProcPtr info)=0
virtual void vSetB (const Eref &e, double val)=0
virtual void vSetCa (const Eref &e, double val)=0
virtual void vSetCaBasal (const Eref &e, double val)=0
virtual void vSetCeiling (const Eref &e, double val)=0
virtual void vSetFloor (const Eref &e, double val)=0
virtual void vSetSolver (const Eref &e, Id hsolve)
Used to set up the solver. Dummy for regular classes.
virtual void vSetTau (const Eref &e, double val)=0
Static Public Member Functions
static SrcFinfo1< double > * concOut ()
static const Cinfo * initCinfo ()
static void zombify (Element *orig, const Cinfo *zClass, Id hsolve)
Private Attributes
double diameter_
double length_
double thickness_
Detailed Description
This is the base class for CaConc. It handles calcium current influx, conversion to calcium concentration, buffering, and pumps. It obeys the equation:
dC/dt = B*Ik - C/tau where Ca = Ca_base + C.
From the GENESIS notes: In SI units, where concentration is moles/m^3 (milli-moles/liter) and current is in amperes, theory gives B = 5.2e-6/(shell volume). In practice, B is a parameter to be fitted or estimated from experiment, as buffering, non-uniform distribution of Ca, etc., will modify this value. If thick = 0, the readcell routine calculates B by dividing the "density" parameter in the cell parameter file by the volume of the compartment. Otherwise, it scales as a true shell, with the volume of a shell having thickness thick. A negative value of the "density" parameter may be used to indicate that it should be taken as an absolute value of B, without scaling.
This is a base class to provide the interface functions.
Definition at line 38 of file CaConcBase.h.
Constructor & Destructor Documentation
CaConcBase()
CaConcBase::CaConcBase ()
Definition at line 166 of file CaConcBase.cpp.
                       : thickness_(0.0)
{
    ;
}
References thickness_.
Referenced by CaConc::CaConc(), and ZombieCaConc::ZombieCaConc().
Member Function Documentation
concOut()
SrcFinfo1< double > * CaConcBase::concOut () static
Definition at line 27 of file CaConcBase.cpp.
{
    static SrcFinfo1<double> concOut("concOut", "Concentration of Ca in pool");
    return &concOut;
}
References SrcFinfo1< T >::SrcFinfo1().
Referenced by initCinfo(), HSolveActive::sendValues(), CaConc::vProcess(), and CaConc::vReinit().
current()
void CaConcBase::current (const Eref & e, double I)
Definition at line 296 of file CaConcBase.cpp.
{
    vCurrent(e, I);
}
References vCurrent().
Referenced by initCinfo().
currentFraction()
void CaConcBase::currentFraction (const Eref & e, double I, double fraction)
Definition at line 301 of file CaConcBase.cpp.
{
    vCurrentFraction(e, I, fraction);
}
References vCurrentFraction().
Referenced by initCinfo().
decrease()
void CaConcBase::decrease (const Eref & e, double I)
Definition at line 311 of file CaConcBase.cpp.
{
    vDecrease(e, I);
}
References vDecrease().
Referenced by initCinfo().
getB()
double CaConcBase::getB (const Eref & e) const
Definition at line 206 of file CaConcBase.cpp.
{
    return vGetB(e);
}
References vGetB().
Referenced by initCinfo(), and zombify().
getCa()
double CaConcBase::getCa (const Eref & e) const
Definition at line 179 of file CaConcBase.cpp.
{
    return vGetCa(e);
}
References vGetCa().
Referenced by initCinfo(), and zombify().
getCaBasal()
double CaConcBase::getCaBasal (const Eref & e) const
Definition at line 188 of file CaConcBase.cpp.
{
    return vGetCaBasal(e);
}
References vGetCaBasal().
Referenced by initCinfo(), and zombify().
getCeiling()
double CaConcBase::getCeiling (const Eref & e) const
Definition at line 214 of file CaConcBase.cpp.
{
    return vGetCeiling(e);
}
References vGetCeiling().
Referenced by initCinfo(), and zombify().
getDiameter()
double CaConcBase::getDiameter (const Eref & e) const
Definition at line 267 of file CaConcBase.cpp.
{
    return diameter_;
}
References diameter_.
Referenced by initCinfo(), and zombify().
getFloor()
double CaConcBase::getFloor (const Eref & e) const
Definition at line 223 of file CaConcBase.cpp.
{
    return vGetFloor(e);
}
References vGetFloor().
Referenced by initCinfo(), and zombify().
getLength()
double CaConcBase::getLength (const Eref & e) const
Definition at line 277 of file CaConcBase.cpp.
{
    return length_;
}
References length_.
Referenced by initCinfo(), and zombify().
getTau()
double CaConcBase::getTau (const Eref & e) const
Definition at line 197 of file CaConcBase.cpp.
{
    return vGetTau(e);
}
References vGetTau().
Referenced by initCinfo(), and zombify().
getThickness()
double CaConcBase::getThickness (const Eref & e) const
Definition at line 256 of file CaConcBase.cpp.
{
    return thickness_;
}
References thickness_.
Referenced by initCinfo(), and zombify().
increase()
void CaConcBase::increase (const Eref & e, double I)
Definition at line 306 of file CaConcBase.cpp.
{
    vIncrease(e, I);
}
References vIncrease().
Referenced by initCinfo().
initCinfo()
const Cinfo * CaConcBase::initCinfo () static
Definition at line 33 of file CaConcBase.cpp.
{
    // Shared message definitions
    static DestFinfo process("process", "Handles process call",
                             new ProcOpFunc<CaConcBase>(&CaConcBase::process));
    static DestFinfo reinit("reinit", "Handles reinit call",
                            new ProcOpFunc<CaConcBase>(&CaConcBase::reinit));
    static Finfo* processShared[] = {&process, &reinit};
    static SharedFinfo proc(
        "proc", "Shared message to receive Process message from scheduler",
        processShared, sizeof(processShared) / sizeof(Finfo*));
    // Field definitions
    static ElementValueFinfo<CaConcBase, double> Ca(
        "Ca", "Calcium concentration.", &CaConcBase::setCa, &CaConcBase::getCa);
    static ElementValueFinfo<CaConcBase, double> CaBasal(
        "CaBasal", "Basal Calcium concentration.", &CaConcBase::setCaBasal,
        &CaConcBase::getCaBasal);
    static ElementValueFinfo<CaConcBase, double> Ca_base(
        "Ca_base", "Basal Calcium concentration, synonym for CaBasal",
        &CaConcBase::setCaBasal, &CaConcBase::getCaBasal);
    static ElementValueFinfo<CaConcBase, double> tau(
        "tau", "Settling time for Ca concentration", &CaConcBase::setTau,
        &CaConcBase::getTau);
    static ElementValueFinfo<CaConcBase, double> B(
        "B",
        "Volume scaling factor. "
        "Deprecated. This is a legacy field from GENESIS and exposes "
        "internal calculations. Please do not use. \n"
        "B = 1/(vol * F* VALENCE) so that it obeys:\n"
        "dC/dt = B*I_Ca - C/tau",
        &CaConcBase::setB, &CaConcBase::getB);
    static ElementValueFinfo<CaConcBase, double> thick(
        "thick",
        "Thickness of Ca shell, assumed cylindrical. Legal range is between 0 "
        "\n"
        "and the radius. If outside this range it is taken as the radius. \n"
        " Default zero, ie, the shell is the entire thickness of the cylinder "
        "\n",
        &CaConcBase::setThickness, &CaConcBase::getThickness);
    static ElementValueFinfo<CaConcBase, double> length(
        "length", "Length of Ca shell, assumed cylindrical",
        &CaConcBase::setLength, &CaConcBase::getLength);
    static ElementValueFinfo<CaConcBase, double> diameter(
        "diameter", "Diameter of Ca shell, assumed cylindrical",
        &CaConcBase::setDiameter, &CaConcBase::getDiameter);
    static ElementValueFinfo<CaConcBase, double> ceiling(
        "ceiling",
        "Ceiling value for Ca concentration. If Ca > ceiling, Ca = ceiling. \n"
        "If ceiling <= 0.0, there is no upper limit on Ca concentration value.",
        &CaConcBase::setCeiling, &CaConcBase::getCeiling);
    static ElementValueFinfo<CaConcBase, double> floor(
        "floor", "Floor value for Ca concentration. If Ca < floor, Ca = floor",
        &CaConcBase::setFloor, &CaConcBase::getFloor);
    // MsgDest definitions
    static DestFinfo current(
        "current", "Calcium Ion current, due to be converted to conc.",
        new EpFunc1<CaConcBase, double>(&CaConcBase::current));
    static DestFinfo currentFraction(
        "currentFraction",
        "Fraction of total Ion current, that is carried by Ca2+.",
        new EpFunc2<CaConcBase, double, double>(&CaConcBase::currentFraction));
    static DestFinfo increase(
        "increase", "Any input current that increases the concentration.",
        new EpFunc1<CaConcBase, double>(&CaConcBase::increase));
    static DestFinfo decrease(
        "decrease", "Any input current that decreases the concentration.",
        new EpFunc1<CaConcBase, double>(&CaConcBase::decrease));
    static DestFinfo basal(
        "basal", "Synonym for assignment of basal conc.",
        new EpFunc1<CaConcBase, double>(&CaConcBase::setCaBasal));
    static Finfo* CaConcBaseFinfos[] = {
        &proc,             // Shared
        concOut(),         // Src
        &Ca,               // Value
        &CaBasal,          // Value
        &Ca_base,          // Value
        &tau,              // Value
        &B,                // Value
        &thick,            // Value
        &diameter,         // Value
        &length,           // Value
        &ceiling,          // Value
        &floor,            // Value
        &current,          // Dest
        &currentFraction,  // Dest
        &increase,         // Dest
        &decrease,         // Dest
        &basal,            // Dest
    };
    // We want the Ca updates before channel updates, so along with compts.
    // static SchedInfo schedInfo[] = { { process, 0, 0 } };
    static string doc[] = {
        "Name",
        "CaConcBase",
        "Author",
        "Upinder S. Bhalla, 2014, NCBS",
        "Description",
        "CaConcBase: Base class for Calcium concentration pool. \n"
        "Takes current from a channel and keeps track of calcium buildup and \n"
        " depletion by a single exponential process. ",
    };
    static ZeroSizeDinfo<int> dinfo;
    static Cinfo CaConcBaseCinfo("CaConcBase", Neutral::initCinfo(),
                                 CaConcBaseFinfos,
                                 sizeof(CaConcBaseFinfos) / sizeof(Finfo*),
                                 &dinfo, doc, sizeof(doc) / sizeof(string));
    return &CaConcBaseCinfo;
}
References Cinfo::Cinfo(), concOut(), current(), currentFraction(), decrease(), DestFinfo::DestFinfo(), ElementValueFinfo< T, F >::ElementValueFinfo(), EpFunc1< T, A >::EpFunc1(), EpFunc2< T, A1, A2 >::EpFunc2(), getB(), getCa(), getCaBasal(), getCeiling(), getDiameter(), getFloor(), getLength(), getTau(), getThickness(), increase(), Neutral::initCinfo(), process(), ProcOpFunc< T >::ProcOpFunc(), reinit(), setB(), setCa(), setCaBasal(), setCeiling(), setDiameter(), setFloor(), setLength(), setTau(), setThickness(), and SharedFinfo::SharedFinfo().
Referenced by CaConc::initCinfo(), and ZombieCaConc::initCinfo().
process()
void CaConcBase::process (const Eref & e, ProcPtr info)
Definition at line 291 of file CaConcBase.cpp.
{
    vProcess(e, p);
}
References vProcess().
Referenced by initCinfo().
reinit()
void CaConcBase::reinit (const Eref & e, ProcPtr info)
Definition at line 286 of file CaConcBase.cpp.
{
    vReinit(e, p);
}
References vReinit().
Referenced by initCinfo().
setB()
void CaConcBase::setB (const Eref & e, double val)
Definition at line 202 of file CaConcBase.cpp.
{
    vSetB(e, B);
}
References vSetB().
Referenced by initCinfo(), and zombify().
setCa()
void CaConcBase::setCa (const Eref & e, double val)
Definition at line 175 of file CaConcBase.cpp.
{
    vSetCa(e, Ca);
}
References vSetCa().
Referenced by initCinfo(), and zombify().
setCaBasal()
void CaConcBase::setCaBasal (const Eref & e, double val)
Definition at line 184 of file CaConcBase.cpp.
{
    vSetCaBasal(e, CaBasal);
}
References vSetCaBasal().
Referenced by initCinfo(), and zombify().
setCeiling()
void CaConcBase::setCeiling (const Eref & e, double val)
Definition at line 210 of file CaConcBase.cpp.
{
    vSetCeiling(e, ceiling);
}
References vSetCeiling().
Referenced by initCinfo(), and zombify().
setDiameter()
void CaConcBase::setDiameter (const Eref & e, double val)
Definition at line 261 of file CaConcBase.cpp.
{
    diameter_ = diameter;
    updateDimensions(e);
}
References diameter_, and updateDimensions().
Referenced by initCinfo(), and zombify().
setFloor()
void CaConcBase::setFloor (const Eref & e, double val)
Definition at line 219 of file CaConcBase.cpp.
{
    vSetFloor(e, floor);
}
References vSetFloor().
Referenced by initCinfo(), and zombify().
setLength()
void CaConcBase::setLength (const Eref & e, double val)
Definition at line 272 of file CaConcBase.cpp.
{
    length_ = length;
    updateDimensions(e);
}
References length_, and updateDimensions().
Referenced by initCinfo(), and zombify().
setTau()
void CaConcBase::setTau (const Eref & e, double val)
Definition at line 193 of file CaConcBase.cpp.
{
    vSetTau(e, tau);
}
References vSetTau().
Referenced by initCinfo(), and zombify().
setThickness()
void CaConcBase::setThickness (const Eref & e, double val)
Definition at line 250 of file CaConcBase.cpp.
{
    thickness_ = thickness;
    updateDimensions(e);
}
References thickness_, and updateDimensions().
Referenced by initCinfo(), and zombify().
updateDimensions()
void CaConcBase::updateDimensions (const Eref & e)
Definition at line 228 of file CaConcBase.cpp.
{
    double vol{0};
    if(length_ > 0) {
        vol = PI * diameter_ * diameter_ * length_ * 0.25;
    }
    else {
        vol = PI * diameter_ * diameter_ * diameter_ * 0.5 / 3;
    }
    if(thickness_ > 0 && thickness_ < diameter_ / 2.0) {
        double coreRadius = diameter_ / 2.0 - thickness_;
        if(length_ > 0) {
            vol -= PI * coreRadius * coreRadius * length_;
        }
        else {
            vol -= 4 * PI * coreRadius * coreRadius * coreRadius / 3;
        }
    }
    double B = 1.0 / (VALENCE * FaradayConst * vol);
    vSetB(e, B);
}
References diameter_, FaradayConst, length_, PI, thickness_, and vSetB().
Referenced by setDiameter(), setLength(), and setThickness().
vCurrent()
virtual void CaConcBase::vCurrent (const Eref & e, double I) pure virtual
Implemented in CaConc, and ZombieCaConc.
Referenced by current().
vCurrentFraction()
virtual void CaConcBase::vCurrentFraction (const Eref & e, double I, double fraction) pure virtual
Implemented in CaConc, and ZombieCaConc.
Referenced by currentFraction().
vDecrease()
virtual void CaConcBase::vDecrease (const Eref & e, double I) pure virtual
Implemented in CaConc, and ZombieCaConc.
Referenced by decrease().
vGetB()
virtual double CaConcBase::vGetB (const Eref & e) const pure virtual
Implemented in CaConc, and ZombieCaConc.
Referenced by getB().
vGetCa()
virtual double CaConcBase::vGetCa (const Eref & e) const pure virtual
Implemented in CaConc, and ZombieCaConc.
Referenced by getCa().
vGetCaBasal()
virtual double CaConcBase::vGetCaBasal (const Eref & e) const pure virtual
Implemented in CaConc, and ZombieCaConc.
Referenced by getCaBasal().
vGetCeiling()
virtual double CaConcBase::vGetCeiling (const Eref & e) const pure virtual
Implemented in CaConc, and ZombieCaConc.
Referenced by getCeiling().
vGetFloor()
virtual double CaConcBase::vGetFloor (const Eref & e) const pure virtual
Implemented in CaConc, and ZombieCaConc.
Referenced by getFloor().
vGetTau()
virtual double CaConcBase::vGetTau (const Eref & e) const pure virtual
Implemented in CaConc, and ZombieCaConc.
Referenced by getTau().
vIncrease()
virtual void CaConcBase::vIncrease (const Eref & e, double I) pure virtual
Implemented in CaConc, and ZombieCaConc.
Referenced by increase().
vProcess()
virtual void CaConcBase::vProcess (const Eref & , ProcPtr info) pure virtual
Implemented in CaConc, and ZombieCaConc.
Referenced by process().
vReinit()
virtual void CaConcBase::vReinit (const Eref & , ProcPtr info) pure virtual
Implemented in CaConc, and ZombieCaConc.
Referenced by reinit().
vSetB()
virtual void CaConcBase::vSetB (const Eref & e, double val) pure virtual
Implemented in CaConc, and ZombieCaConc.
Referenced by setB(), and updateDimensions().
vSetCa()
virtual void CaConcBase::vSetCa (const Eref & e, double val) pure virtual
Implemented in CaConc, and ZombieCaConc.
Referenced by setCa().
vSetCaBasal()
virtual void CaConcBase::vSetCaBasal (const Eref & e, double val) pure virtual
Implemented in CaConc, and ZombieCaConc.
Referenced by setCaBasal().
vSetCeiling()
virtual void CaConcBase::vSetCeiling (const Eref & e, double val) pure virtual
Implemented in CaConc, and ZombieCaConc.
Referenced by setCeiling().
vSetFloor()
virtual void CaConcBase::vSetFloor (const Eref & e, double val) pure virtual
Implemented in CaConc, and ZombieCaConc.
Referenced by setFloor().
vSetSolver()
void CaConcBase::vSetSolver (const Eref & e, Id hsolve) virtual
Used to set up the solver. Dummy for regular classes.
Reimplemented in ZombieCaConc.
Definition at line 321 of file CaConcBase.cpp.
{
    ;
}
Referenced by zombify().
vSetTau()
virtual void CaConcBase::vSetTau (const Eref & e, double val) pure virtual
Implemented in CaConc, and ZombieCaConc.
Referenced by setTau().
zombify()
void CaConcBase::zombify (Element * orig, const Cinfo * zClass, Id hsolve) static
Swaps Cinfos in order to make Zombies.
Definition at line 327 of file CaConcBase.cpp.
{
    if(orig->cinfo() == zClass)
        return;
    unsigned int start = orig->localDataStart();
    unsigned int num = orig->numLocalData();
    if(num == 0)
        return;
    vector<double> data(num * 9);
    unsigned int j = 0;
    for(unsigned int i = 0; i < num; ++i) {
        Eref er(orig, i + start);
        const CaConcBase* cb = reinterpret_cast<const CaConcBase*>(er.data());
        data[j + 0] = cb->getCa(er);
        data[j + 1] = cb->getCaBasal(er);
        data[j + 2] = cb->getTau(er);
        data[j + 3] = cb->getB(er);
        data[j + 4] = cb->getCeiling(er);
        data[j + 5] = cb->getFloor(er);
        data[j + 6] = cb->getThickness(er);
        data[j + 7] = cb->getLength(er);
        data[j + 8] = cb->getDiameter(er);
        j += 9;
    }
    orig->zombieSwap(zClass);
    j = 0;
    for(unsigned int i = 0; i < num; ++i) {
        Eref er(orig, i + start);
        CaConcBase* cb = reinterpret_cast<CaConcBase*>(er.data());
        cb->vSetSolver(er, hsolve);
        cb->setCa(er, data[j + 0]);
        cb->setCaBasal(er, data[j + 1]);
        cb->setTau(er, data[j + 2]);
        cb->setB(er, data[j + 3]);
        cb->setCeiling(er, data[j + 4]);
        cb->setFloor(er, data[j + 5]);
        cb->setThickness(er, data[j + 6]);
        cb->setLength(er, data[j + 7]);
        cb->setDiameter(er, data[j + 8]);
        j += 9;  // was 7?
    }
}
References Element::cinfo(), Eref::data(), Eref::Eref(), getB(), getCa(), getCaBasal(), getCeiling(), getDiameter(), getFloor(), getLength(), getTau(), getThickness(), Element::localDataStart(), Element::numLocalData(), setB(), setCa(), setCaBasal(), setCeiling(), setDiameter(), setFloor(), setLength(), setTau(), setThickness(), vSetSolver(), and Element::zombieSwap().
Referenced by HSolve::unzombify(), and HSolve::zombify().
Member Data Documentation
diameter_
double CaConcBase::diameter_ private
Definition at line 123 of file CaConcBase.h.
Referenced by getDiameter(), setDiameter(), and updateDimensions().
length_
double CaConcBase::length_ private
Definition at line 124 of file CaConcBase.h.
Referenced by getLength(), setLength(), and updateDimensions().
thickness_
double CaConcBase::thickness_ private
Definition at line 122 of file CaConcBase.h.
Referenced by CaConcBase(), getThickness(), setThickness(), and updateDimensions().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/biophysics/CaConcBase.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/biophysics/CaConcBase.cpp