MOOSE - Multiscale Object Oriented Simulation Environment: EnzBase Class Reference
EnzBase Class Reference abstract
#include <EnzBase.h>
Public Member Functions
void enz (double n)
EnzBase ()
ObjId getCompartment (const Eref &e) const
double getKcat (const Eref &e) const
double getKm (const Eref &e) const
double getNumKm (const Eref &e) const
unsigned int getNumPrd (const Eref &e) const
unsigned int getNumSub (const Eref &e) const
void prd (double n)
void setKcat (const Eref &e, double v)
void setKm (const Eref &e, double v)
void setNumKm (const Eref &e, double v)
void sub (double n)
virtual void vSetKcat (const Eref &e, double v)=0
virtual void vSetKm (const Eref &e, double v)=0
virtual ~EnzBase ()
Static Public Member Functions
static const Cinfo * initCinfo ()
Protected Attributes
double kcat_
double Km_
Detailed Description
This class is the base class for enzymes, both the classical Michaelis- Menten form and the form with explicit enz-substrate complexes that MOOSE prefers.
Definition at line 18 of file EnzBase.h.
Constructor & Destructor Documentation
EnzBase()
EnzBase::EnzBase ()
Definition at line 147 of file EnzBase.cpp.
    :
        Km_( 5.0e-3 ),
        kcat_( 1.0 )
{;}
References kcat_, and Km_.
~EnzBase()
EnzBase::~EnzBase () virtual
Definition at line 153 of file EnzBase.cpp.
{;}
Member Function Documentation
enz()
void EnzBase::enz (double n)
Definition at line 165 of file EnzBase.cpp.
{;}
Referenced by initCinfo(), and testMMenz().
getCompartment()
ObjId EnzBase::getCompartment (const Eref & e) const
Definition at line 228 of file EnzBase.cpp.
{
    return getCompt( e.id() );
}
References getCompt(), and Eref::id().
Referenced by initCinfo().
getKcat()
double EnzBase::getKcat (const Eref & e) const
Definition at line 207 of file EnzBase.cpp.
{
        return kcat_;
}
References kcat_.
Referenced by Enz::initCinfo(), initCinfo(), and testMMenz().
getKm()
double EnzBase::getKm (const Eref & e) const
Definition at line 179 of file EnzBase.cpp.
{
    return Km_;
}
References Km_.
Referenced by initCinfo(), and testMMenz().
getNumKm()
double EnzBase::getNumKm (const Eref & e) const
Definition at line 191 of file EnzBase.cpp.
{
    double volScale = convertConcToNumRateUsingMesh( enz, subOut(), 1 );
    return Km_ * volScale;
}
References convertConcToNumRateUsingMesh(), Km_, and subOut().
Referenced by initCinfo().
getNumPrd()
unsigned int EnzBase::getNumPrd (const Eref & e) const
Definition at line 220 of file EnzBase.cpp.
{
    const vector< MsgFuncBinding >* mfb =
        e.element()->getMsgAndFunc( prdOut()->getBindIndex() );
    assert( mfb );
    return ( mfb->size() );
}
References Eref::element(), SrcFinfo::getBindIndex(), Element::getMsgAndFunc(), and prdOut().
Referenced by initCinfo().
getNumSub()
unsigned int EnzBase::getNumSub (const Eref & e) const
Definition at line 212 of file EnzBase.cpp.
{
    const vector< MsgFuncBinding >* mfb =
        e.element()->getMsgAndFunc( subOut()->getBindIndex() );
    assert( mfb );
    return ( mfb->size() );
}
References Eref::element(), SrcFinfo::getBindIndex(), Element::getMsgAndFunc(), and subOut().
Referenced by initCinfo().
initCinfo()
const Cinfo * EnzBase::initCinfo () static
Definition at line 33 of file EnzBase.cpp.
{
        // Field Definitions
        static ElementValueFinfo< EnzBase, double > Km(
            "Km",
            "Michaelis-Menten constant in SI conc units (milliMolar)",
            &EnzBase::setKm,
            &EnzBase::getKm
        );
        static ElementValueFinfo< EnzBase, double > numKm(
            "numKm",
            "Michaelis-Menten constant in number units, volume dependent",
            &EnzBase::setNumKm,
            &EnzBase::getNumKm
        );
        static ElementValueFinfo< EnzBase, double > kcat(
            "kcat",
            "Forward rate constant for enzyme, units 1/sec",
            &EnzBase::setKcat,
            &EnzBase::getKcat
        );
        static ReadOnlyElementValueFinfo< EnzBase, unsigned int > numSub(
            "numSubstrates",
            "Number of substrates in this MM reaction. Usually 1."
            "Does not include the enzyme itself",
            &EnzBase::getNumSub
        );
        static ReadOnlyElementValueFinfo< EnzBase, unsigned int > numPrd(
            "numProducts",
            "Number of products in this MM reaction. Usually 1.",
            &EnzBase::getNumPrd
        );
        static ReadOnlyElementValueFinfo< EnzBase, ObjId > compartment(
            "compartment",
            "ObjId of parent compartment of pool. "
            "If the compartment isn't"
            "available this returns the root ObjId.",
            &EnzBase::getCompartment
        );
        // MsgDest Definitions
        static DestFinfo enzDest( "enzDest",
                "Handles # of molecules of Enzyme",
                new OpFunc1< EnzBase, double >( &EnzBase::enz ) );
        static DestFinfo subDest( "subDest",
                "Handles # of molecules of substrate",
                new OpFunc1< EnzBase, double >( &EnzBase::sub ) );
        static DestFinfo prdDest( "prdDest",
                "Handles # of molecules of product. Dummy.",
                new OpFunc1< EnzBase, double >( &EnzBase::prd ) );
        static Finfo* subShared[] = {
            subOut(), &subDest
        };
        static Finfo* prdShared[] = {
            prdOut(), &prdDest
        };
        static SharedFinfo sub( "sub",
            "Connects to substrate molecule",
            subShared, sizeof( subShared ) / sizeof( const Finfo* )
        );
        static SharedFinfo prd( "prd",
            "Connects to product molecule",
            prdShared, sizeof( prdShared ) / sizeof( const Finfo* )
        );
    static Finfo* enzBaseFinfos[] = {
        &Km,    // ElementValue
        &numKm, // ElementValue
        &kcat,  // Value
        &numSub,    // ReadOnlyElementValue
        &numPrd,    // ReadOnlyElementValue
        &compartment,   // ReadOnlyElementValue
        &enzDest,           // DestFinfo
        &sub,               // SharedFinfo
        &prd,               // SharedFinfo
    };
    static string doc[] =
    {
        "Name", "EnzBase",
        "Author", "Upi Bhalla",
        "Description", "Abstract base class for enzymes."
    };
    static ZeroSizeDinfo< int > dinfo;
    static Cinfo enzBaseCinfo (
        "EnzBase",
        Neutral::initCinfo(),
        enzBaseFinfos,
        sizeof( enzBaseFinfos ) / sizeof ( Finfo* ),
        &dinfo,
        doc,
        sizeof( doc )/sizeof( string ),
        true // Don't create it, it is a an astract base class.
    );
    return &enzBaseCinfo;
}
References Cinfo::Cinfo(), DestFinfo::DestFinfo(), ElementValueFinfo< T, F >::ElementValueFinfo(), enz(), getCompartment(), getKcat(), getKm(), getNumKm(), getNumPrd(), getNumSub(), Neutral::initCinfo(), OpFunc1< T, A >::OpFunc1(), prd(), prdOut(), ReadOnlyElementValueFinfo< T, F >::ReadOnlyElementValueFinfo(), setKcat(), setKm(), setNumKm(), SharedFinfo::SharedFinfo(), sub(), and subOut().
Referenced by enzDest(), findMeshOfEnz(), Enz::initCinfo(), MMenz::initCinfo(), and MMenz::setSolver().
prd()
void EnzBase::prd (double n)
Definition at line 162 of file EnzBase.cpp.
{;}
Referenced by initCinfo().
setKcat()
void EnzBase::setKcat (const Eref & e, double v)
Definition at line 198 of file EnzBase.cpp.
{
    // We don't set it here because we need the old value in the Enz
    // function.
    if ( v < 0.0 )
        v = 0.0;
    vSetKcat( e, v );
}
References vSetKcat().
Referenced by Enz::initCinfo(), and initCinfo().
setKm()
void EnzBase::setKm (const Eref & e, double v)
Definition at line 172 of file EnzBase.cpp.
{
    if ( v < EPSILON )
        v = EPSILON;
    vSetKm( enz, v );
}
References vSetKm().
Referenced by initCinfo().
setNumKm()
void EnzBase::setNumKm (const Eref & e, double v)
Definition at line 184 of file EnzBase.cpp.
{
    double volScale = convertConcToNumRateUsingMesh( enz, subOut(), 1 );
    Km_ = v / volScale;
    vSetKm( enz, Km_ );
}
References convertConcToNumRateUsingMesh(), Km_, subOut(), and vSetKm().
Referenced by initCinfo().
sub()
void EnzBase::sub (double n)
Definition at line 160 of file EnzBase.cpp.
{;}
Referenced by Enz::initCinfo(), initCinfo(), and testMMenz().
vSetKcat()
virtual void EnzBase::vSetKcat (const Eref & e, double v) pure virtual
Implemented in Enz, and MMenz.
Referenced by setKcat().
vSetKm()
virtual void EnzBase::vSetKm (const Eref & e, double v) pure virtual
Implemented in Enz, and MMenz.
Referenced by setKm(), and setNumKm().
Member Data Documentation
kcat_
double EnzBase::kcat_ protected
Definition at line 57 of file EnzBase.h.
Referenced by EnzBase(), Enz::getConcK1(), Enz::getK1(), getKcat(), Enz::getRatio(), Enz::setConcK1(), Enz::setK1(), Enz::setRatio(), Enz::setSolver(), MMenz::setSolver(), Enz::vSetKcat(), MMenz::vSetKcat(), and Enz::vSetKm().
Km_
double EnzBase::Km_ protected
Definition at line 56 of file EnzBase.h.
Referenced by EnzBase(), Enz::getConcK1(), Enz::getK1(), getKm(), getNumKm(), Enz::setConcK1(), Enz::setK1(), Enz::setKmK1(), setNumKm(), Enz::setRatio(), Enz::setSolver(), MMenz::setSolver(), Enz::vSetKcat(), Enz::vSetKm(), and MMenz::vSetKm().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/kinetics/EnzBase.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/kinetics/EnzBase.cpp