MOOSE - Multiscale Object Oriented Simulation Environment: Stoich Class Reference
Stoich Class Reference
#include <Stoich.h>
Public Member Functions
void allocateModel (const vector< Id > &elist)
Calculate sizes of all arrays, and allocate them.
void allocateModelObject (Id id)
Identifies and allocates objects in the Stoich.
void buildFuncLookup ()
void buildPoolLookup ()
Functions to build the maps between Ids and internal indices.
void buildRateTermLookup ()
void clearFuncTargetPools ()
Removes funcTargetPools from the list of varPools and bufPools.
unsigned int convertIdToFuncIndex (Id id) const
unsigned int convertIdToPoolIndex (Id id) const
unsigned int convertIdToReacIndex (Id id) const
void convertRatesToStochasticForm ()
void deAllocateModel ()
Clears out old model.
const FuncTerm * funcs (unsigned int i) const
bool getAllowNegative () const
vector< unsigned int > getColIndex () const
Id getCompartment () const
Id getDsolve () const
double getEnzK2 (const Eref &e) const
Get rate k2 (1/sec) for enzyme.
double getEnzK3 (const Eref &e) const
Get rate k3, aka kcat, for enzyme.
double getEnzNumK1 (const Eref &e) const
Id getKsolve () const
vector< int > getMatrixEntry () const
double getMMenzKcat (const Eref &e) const
double getMMenzNumKm (const Eref &e) const
unsigned int getNumAllPools () const
unsigned int getNumBufPools () const
Returns number of local buffered pools.
unsigned int getNumCoreRates () const
Number of rate terms for reactions purely on this compartment.
unsigned int getNumFuncPools () const
Returns number of local func target pools.
unsigned int getNumFuncs () const
unsigned int getNumProxyPools () const
unsigned int getNumRates () const
unsigned int getNumVarPools () const
Returns number of local pools that are updated by solver.
vector< Id > getOffSolverCompts () const
const vector< Id > & getOffSolverPools () const
bool getOneWay () const
string getPath (const Eref &e) const
Id getPoolByIndex (unsigned int index) const
vector< unsigned int > getPoolIdMap () const
vector< Id > getProxyPools (Id i) const
double getR1 (const Eref &e) const
double getR1offset1 (const Eref &e) const
double getR1offset2 (const Eref &e) const
double getR2 (const Eref &e) const
const vector< RateTerm * > & getRateTerms () const
Returns a reference to the entire rates_ vector.
double getReacNumKf (const Eref &e) const
string getReacSystemPath (const Eref &e) const
vector< unsigned int > getRowStart () const
unsigned int getSpecies (unsigned int poolIndex) const
int getStatus () const
const KinSparseMatrix & getStoichiometryMatrix () const
Updates the rates for cross-compartment reactions.
unsigned int innerInstallReaction (Id reacId, const vector< Id > &subs, const vector< Id > &prds)
void installAndUnschedFunc (Id func, Id pool, double volScale)
void installAndUnschedFuncRate (Id func, Id pool)
void installAndUnschedFuncReac (Id func, Id reac)
void installDummyEnzyme (Id enzId, Id enzMolId)
This is used when the enzyme lacks sub or prd.
void installEnzyme (Id enzId, Id enzMolId, Id cplxId, const vector< Id > &subs, const vector< Id > &prds)
void installEnzyme (ZeroOrder *r1, ZeroOrder *r2, ZeroOrder *r3, Id enzId, Id enzMolId, const vector< Id > &prds)
void installMMenz (Id enzId, const vector< Id > &enzMolId, const vector< Id > &subs, const vector< Id > &prds)
void installMMenz (MMEnzymeBase *meb, unsigned int rateIndex, const vector< Id > &subs, const vector< Id > &prds)
This is the internal variant to install the MMenz.
void installReaction (Id reacId, const vector< Id > &subs, const vector< Id > &prds)
bool isFuncTarget (unsigned int poolIndex) const
Returns true if the specified pool is controlled by a func.
void locateOffSolverReacs (Id myCompt, vector< Id > &elist)
ZeroOrder * makeHalfReaction (double rate, const vector< Id > &reactants)
Utility function to make a half reac and return the rate term.
void notifyRemoveEnz (const Eref &e)
void notifyRemoveFunc (const Eref &e)
void notifyRemoveMMenz (const Eref &e)
void notifyRemoveReac (const Eref &e)
const vector< Id > & offSolverPoolMap (Id compt) const
void print () const
Utility function, prints out N_, used for debugging.
void printRates () const
Another utility function, prints out all Kf, kf, Kb, kb.
const RateTerm * rates (unsigned int i) const
Utility function to return a rates_ entry.
void resizeArrays ()
Using the computed array sizes, now allocate space for them.
void scaleBufsAndRates (unsigned int index, double volScale)
Used to handle run-time size updates for spines.
void setAllowNegative (bool v)
void setCompartment (Id v)
assigns compartment occupied by Stoich.
void setDsolve (Id v)
assigns diffusion solver: Dsovle or a Gillespie voxel stepper
void setElist (const Eref &e, const vector< ObjId > &elist)
void setEnzK1 (const Eref &e, double v) const
Later handle all the volumes when this conversion is done.
void setEnzK2 (const Eref &e, double v) const
Set rate k2 (1/sec) for enzyme.
void setEnzK3 (const Eref &e, double v) const
Set rate k3 (1/sec) for enzyme.
void setFunctionExpr (const Eref &e, string expr)
void setKsolve (Id v)
assigns kinetic solver: Ksovle or GSSAsolve.
void setMMenzKcat (const Eref &e, double v) const
void setMMenzKm (const Eref &e, double v) const
void setOneWay (bool v)
void setPath (const Eref &e, string path)
void setReacKb (const Eref &e, double v) const
void setReacKf (const Eref &e, double v) const
void setReacSystemPath (const Eref &e, string wildcard)
void setSpecies (unsigned int poolIndex, unsigned int s)
Stoich ()
void unZombifyModel ()
void unZombifyPools ()
unZombifies Pools. Helper for unZombifyModel.
void updateFuncs (double *s, double t) const
Updates the function values, within s.
void updateRatesAfterRemesh ()
void updateReacVelocities (const double *s, vector< double > &vel, unsigned int volIndex) const
void zombifyChemCompt (Id compt)
void zombifyModel (const Eref &e, const vector< Id > &elist)
Id zombifyPoolFuncWithScaling (const Eref &e, Id pool)
~Stoich ()
Static Public Member Functions
static const Cinfo * initCinfo ()
Static Public Attributes
static const unsigned int PoolIsNotOnSolver
Private Attributes
bool allowNegative_
vector< Id > bufPoolVec_
Id compartment_
Contains Id of compartment holding reac system. Optional.
KsolveBase * dinterface_
Pointer for dsolve.
Id dsolve_
This contains the Id of the Diffusion solver. Optional.
vector< Id > enzVec_
map< Id, unsigned int > funcLookup_
vector< FuncTerm * > funcs_
The FuncTerms handle mathematical ops on mol levels.
vector< unsigned int > funcTarget_
vector< Id > funcTargetPoolVec_
vector< Id > incrementFuncVec_
KsolveBase * kinterface_
Pointer for ksolve.
Id ksolve_
This contains the Id of the Kinetic solver.
vector< Id > mmEnzVec_
KinSparseMatrix N_
N_ is the stoichiometry matrix. All pools * all reac terms.
unsigned int numVoxels_
Number of voxels in reac system.
vector< pair< Id, Id > > offSolverEnzCompts_
vector< Id > offSolverEnzVec_
vector< pair< Id, Id > > offSolverMMenzCompts_
vector< Id > offSolverMMenzVec_
map< Id, vector< Id > > offSolverPoolMap_
vector< Id > offSolverPoolVec_
vector< pair< Id, Id > > offSolverReacCompts_
vector< Id > offSolverReacVec_
vector< Id > poolFuncVec_
map< Id, unsigned int > poolLookup_
vector< vector< Id > > prdComptVec_
vector< RateTerm * > rates_
map< Id, unsigned int > rateTermLookup_
vector< Id > reacFuncVec_
vector< Id > reacVec_
vector< unsigned int > species_
int status_
vector< vector< Id > > subComptVec_
bool useOneWay_
vector< Id > varPoolVec_
string wildcard_
Detailed Description
Definition at line 51 of file Stoich.h.
Constructor & Destructor Documentation
Stoich()
Stoich::Stoich ()
Definition at line 282 of file Stoich.cpp.
    : useOneWay_(false),
      allowNegative_(false),
      wildcard_(""),
      ksolve_(),       // Must be reassigned to build stoich system.
      dsolve_(),       // Must be assigned if diffusion is planned.
      compartment_(),  // Must be assigned if diffusion is planned.
      kinterface_(nullptr),
      dinterface_(nullptr),
      rates_(0),  // No RateTerms yet.
      // uniqueVols_( 1, 1.0 ),
      numVoxels_(1),
      status_(-1)
{
    ;
}
References allowNegative_, compartment_, dinterface_, dsolve_, Id::Id(), kinterface_, ksolve_, numVoxels_, rates_, status_, useOneWay_, and wildcard_.
~Stoich()
Stoich::~Stoich ()
Definition at line 299 of file Stoich.cpp.
{
    unZombifyModel();
    // Note that we cannot do the unZombify here, because it is too
    // prone to problems with the ordering of the delete operations
    // relative to the zombies.
    for(vector<RateTerm*>::iterator j = rates_.begin(); j != rates_.end(); ++j)
        delete *j;
    for(vector<FuncTerm*>::iterator j = funcs_.begin(); j != funcs_.end(); ++j)
        delete *j;
}
References funcs_, rates_, and unZombifyModel().
Member Function Documentation
allocateModel()
void Stoich::allocateModel (const vector< Id > & elist)
Calculate sizes of all arrays, and allocate them.
Definition at line 969 of file Stoich.cpp.
{
    for(auto i = elist.begin(); i != elist.end(); ++i) {
        allocateModelObject(*i);
    }
    resizeArrays();
    buildPoolLookup();
    buildRateTermLookup();
    buildFuncLookup();
}
References allocateModelObject(), buildFuncLookup(), buildPoolLookup(), buildRateTermLookup(), and resizeArrays().
Referenced by setElist().
allocateModelObject()
void Stoich::allocateModelObject (Id id)
Identifies and allocates objects in the Stoich.
Definition at line 792 of file Stoich.cpp.
{
    static const Cinfo* poolCinfo = Cinfo::find("Pool");
    static const Cinfo* bufPoolCinfo = Cinfo::find("BufPool");
    static const Cinfo* reacCinfo = Cinfo::find("Reac");
    static const Cinfo* enzCinfo = Cinfo::find("Enz");
    static const Cinfo* mmEnzCinfo = Cinfo::find("MMenz");
    static const Cinfo* functionCinfo = Cinfo::find("Function");
    static const Finfo* f1 = functionCinfo->findFinfo("valueOut");
    static const SrcFinfo* sf = dynamic_cast<const SrcFinfo*>(f1);
    assert(sf);
    Element* ei = id.element();
    if(ei->cinfo() == poolCinfo) {
        // objMap_[ id.value() - objMapStart_ ] = numVarPools_;
        varPoolVec_.push_back(id);
        // ++numVarPools_;
    }
    else if(ei->cinfo() == bufPoolCinfo) {
        bufPoolVec_.push_back(id);
    }
    else if(ei->cinfo() == mmEnzCinfo) {
        mmEnzVec_.push_back(ei->id());
        // objMap_[ id.value() - objMapStart_ ] = numReac_;
        // ++numReac_;
    }
    else if(ei->cinfo() == reacCinfo) {
        reacVec_.push_back(ei->id());
        /*
        if ( useOneWay_ ) {
            objMap_[ id.value() - objMapStart_ ] = numReac_;
            numReac_ += 2;
        } else {
            objMap_[ id.value() - objMapStart_ ] = numReac_;
            ++numReac_;
        }
        */
    }
    else if(ei->cinfo() == enzCinfo) {
        enzVec_.push_back(ei->id());
        /*
        if ( useOneWay_ ) {
            objMap_[ id.value() - objMapStart_ ] = numReac_;
            numReac_ += 3;
        } else {
            objMap_[ id.value() - objMapStart_ ] = numReac_;
            numReac_ += 2;
        }
        */
    }
    else if(ei->cinfo() == functionCinfo) {
        vector<ObjId> tgt;
        vector<string> func;
        ei->getMsgTargetAndFunctions(0, sf, tgt, func);
        if(func.size() > 0 && func[0] == "increment") {
            incrementFuncVec_.push_back(ei->id());
            // objMap_[ id.value() - objMapStart_ ] = numReac_;
            // numReac_++;
        }
        else if(func.size() > 0 && func[0] == "setNumKf") {
            reacFuncVec_.push_back(ei->id());
        }
        else  // Assume it controls the N of a pool.
        {
            poolFuncVec_.push_back(ei->id());
            // objMap_[ id.value() - objMapStart_ ] = numFunctions_;
            // ++numFunctions_;
            assert(tgt.size() == 1);
            funcTargetPoolVec_.push_back(tgt[0]);
        }
    }
}
References bufPoolVec_, Element::cinfo(), Id::element(), enzVec_, Cinfo::find(), Cinfo::findFinfo(), funcTargetPoolVec_, Element::getMsgTargetAndFunctions(), Element::id(), incrementFuncVec_, mmEnzVec_, poolFuncVec_, reacFuncVec_, reacVec_, and varPoolVec_.
Referenced by allocateModel().
buildFuncLookup()
void Stoich::buildFuncLookup ()
Definition at line 1037 of file Stoich.cpp.
{
    funcLookup_.clear();
    int funcNum = 0;
    vector<Id>::iterator i;
    for(i = poolFuncVec_.begin(); i != poolFuncVec_.end(); ++i)
        funcLookup_[*i] = funcNum++;
}
References funcLookup_, and poolFuncVec_.
Referenced by allocateModel().
buildPoolLookup()
void Stoich::buildPoolLookup ()
Functions to build the maps between Ids and internal indices.
Definition at line 984 of file Stoich.cpp.
{
    // The order of pools is: varPools, offSolverVarPools, funcTargetPools,
    // bufPools.
    poolLookup_.clear();
    int poolNum = 0;
    vector<Id>::iterator i;
    for(i = varPoolVec_.begin(); i != varPoolVec_.end(); ++i)
        poolLookup_[*i] = poolNum++;
    for(i = offSolverPoolVec_.begin(); i != offSolverPoolVec_.end(); ++i)
        poolLookup_[*i] = poolNum++;
    for(i = funcTargetPoolVec_.begin(); i != funcTargetPoolVec_.end(); ++i)
        poolLookup_[*i] = poolNum++;
    for(i = bufPoolVec_.begin(); i != bufPoolVec_.end(); ++i)
        poolLookup_[*i] = poolNum++;
}
References bufPoolVec_, funcTargetPoolVec_, offSolverPoolVec_, poolLookup_, and varPoolVec_.
Referenced by allocateModel().
buildRateTermLookup()
void Stoich::buildRateTermLookup ()
Definition at line 1001 of file Stoich.cpp.
{
    // The order of pools is: varPools, offSolverVarPools, bufPools.
    rateTermLookup_.clear();
    int termNum = 0;
    vector<Id>::iterator i;
    for(i = reacVec_.begin(); i != reacVec_.end(); ++i) {
        rateTermLookup_[*i] = termNum;
        termNum += 1 + useOneWay_;
    }
    for(i = enzVec_.begin(); i != enzVec_.end(); ++i) {
        rateTermLookup_[*i] = termNum;
        termNum += 2 + useOneWay_;
    }
    for(i = mmEnzVec_.begin(); i != mmEnzVec_.end(); ++i) {
        rateTermLookup_[*i] = termNum;
        termNum += 1;
    }
    for(i = incrementFuncVec_.begin(); i != incrementFuncVec_.end(); ++i) {
        rateTermLookup_[*i] = termNum;
        termNum += 1;
    }
    for(i = offSolverReacVec_.begin(); i != offSolverReacVec_.end(); ++i) {
        rateTermLookup_[*i] = termNum;
        termNum += 1 + useOneWay_;
    }
    for(i = offSolverEnzVec_.begin(); i != offSolverEnzVec_.end(); ++i) {
        rateTermLookup_[*i] = termNum;
        termNum += 2 + useOneWay_;
    }
    for(i = offSolverMMenzVec_.begin(); i != offSolverMMenzVec_.end(); ++i) {
        rateTermLookup_[*i] = termNum;
        termNum += 1;
    }
}
References enzVec_, incrementFuncVec_, mmEnzVec_, offSolverEnzVec_, offSolverMMenzVec_, offSolverReacVec_, rateTermLookup_, reacVec_, and useOneWay_.
Referenced by allocateModel().
clearFuncTargetPools()
void Stoich::clearFuncTargetPools ()
Removes funcTargetPools from the list of varPools and bufPools.
Definition at line 873 of file Stoich.cpp.
{
    vector<Id> temp;
    for(auto pid : varPoolVec_) {
        if(std::find(funcTargetPoolVec_.begin(), funcTargetPoolVec_.end(),
                     pid) == funcTargetPoolVec_.end())
            temp.push_back(pid);
    }
    varPoolVec_ = temp;
    temp.clear();
    for(auto pid : bufPoolVec_) {
        if(std::find(funcTargetPoolVec_.begin(), funcTargetPoolVec_.end(),
                     pid) == funcTargetPoolVec_.end())
            temp.push_back(pid);
    }
    bufPoolVec_ = temp;
}
References bufPoolVec_, funcTargetPoolVec_, and varPoolVec_.
Referenced by resizeArrays().
convertIdToFuncIndex()
unsigned int Stoich::convertIdToFuncIndex (Id id) const
Definition at line 1408 of file Stoich.cpp.
{
    map<Id, unsigned int>::const_iterator i = funcLookup_.find(id);
    if(i != funcLookup_.end()) {
        return i->second;
    }
    return ~0U;
}
References funcLookup_.
Referenced by installAndUnschedFunc(), and setFunctionExpr().
convertIdToPoolIndex()
unsigned int Stoich::convertIdToPoolIndex (Id id) const
Definition at line 1391 of file Stoich.cpp.
{
    map<Id, unsigned int>::const_iterator i = poolLookup_.find(id);
    if(i != poolLookup_.end()) {
        return i->second;
    }
    return ~0U;
}
References poolLookup_.
Referenced by Gsolve::getPoolIndex(), Ksolve::getPoolIndex(), installAndUnschedFunc(), installAndUnschedFuncRate(), installAndUnschedFuncReac(), installEnzyme(), installMMenz(), installMMenz(), and makeHalfReaction().
convertIdToReacIndex()
unsigned int Stoich::convertIdToReacIndex (Id id) const
Definition at line 1400 of file Stoich.cpp.
{
    map<Id, unsigned int>::const_iterator i = rateTermLookup_.find(id);
    if(i != rateTermLookup_.end())
        return i->second;
    return ~0U;
}
References rateTermLookup_.
Referenced by VoxelPoolsBase::filterCrossRateTerms(), getR1(), getR1offset1(), getR1offset2(), getR2(), Ksolve::getRateVecFromId(), Ksolve::getRateVecFromPath(), getReacNumKf(), innerInstallReaction(), installAndUnschedFuncRate(), installAndUnschedFuncReac(), installDummyEnzyme(), installEnzyme(), installEnzyme(), installMMenz(), setEnzK1(), setEnzK2(), setEnzK3(), setFunctionExpr(), setMMenzKcat(), setMMenzKm(), setReacKb(), and setReacKf().
convertRatesToStochasticForm()
void Stoich::convertRatesToStochasticForm ()
This function is used when the stoich class is employed by a Gsolver for doing stochastic calculations. Here we fix the issue of having a single substrate at more than first order. As the first molecule of the substrate is consumed, the number is depleted by one and so its forward rate is reduced. And so on. This also protects against going negative in mol number or concentration.
Definition at line 1177 of file Stoich.cpp.
{
    for(unsigned int i = 0; i < rates_.size(); ++i) {
        vector<unsigned int> molIndex;
        if(rates_[i]->getReactants(molIndex) > 1) {
            if(molIndex.size() == 2 && molIndex[0] == molIndex[1]) {
                RateTerm* oldRate = rates_[i];
                rates_[i] = new StochSecondOrderSingleSubstrate(
                    oldRate->getR1(), molIndex[0]);
                delete oldRate;
            }
            else if(molIndex.size() > 2) {
                RateTerm* oldRate = rates_[i];
                rates_[i] = new StochNOrder(oldRate->getR1(), molIndex);
                delete oldRate;
            }
        }
    }
}
References RateTerm::getR1(), RateTerm::getReactants(), rates_, StochNOrder::StochNOrder(), and StochSecondOrderSingleSubstrate::StochSecondOrderSingleSubstrate().
Referenced by Gsolve::rebuildGssaSystem().
deAllocateModel()
void Stoich::deAllocateModel ()
Clears out old model.
Clear out any existing model data.
Definition at line 932 of file Stoich.cpp.
{
    varPoolVec_.clear();
    bufPoolVec_.clear();
    funcTargetPoolVec_.clear();
    reacVec_.clear();
    enzVec_.clear();
    mmEnzVec_.clear();
    poolFuncVec_.clear();
    incrementFuncVec_.clear();
    reacFuncVec_.clear();
    // Unclear where these are set up and used. The locateOffSolverReacs
    // function doesn't seem to be called anywhere.
    offSolverPoolVec_.clear();
    offSolverReacVec_.clear();
    offSolverEnzVec_.clear();
    offSolverMMenzVec_.clear();
    offSolverReacCompts_.clear();
    offSolverEnzCompts_.clear();
    offSolverMMenzCompts_.clear();
    offSolverPoolMap_.clear();
    // Clear out the rate terms
    for(auto j = rates_.begin(); j != rates_.end(); ++j) {
        delete *j;
    }
    rates_.clear();
    // Clear out the funcs
    for(auto j = funcs_.begin(); j != funcs_.end(); ++j) {
        delete *j;
    }
    funcs_.clear();
}
References bufPoolVec_, enzVec_, funcs_, funcTargetPoolVec_, incrementFuncVec_, mmEnzVec_, offSolverEnzCompts_, offSolverEnzVec_, offSolverMMenzCompts_, offSolverMMenzVec_, offSolverPoolMap_, offSolverPoolVec_, offSolverReacCompts_, offSolverReacVec_, poolFuncVec_, rates_, reacFuncVec_, reacVec_, and varPoolVec_.
Referenced by setElist().
funcs()
const FuncTerm * Stoich::funcs (unsigned int i) const
Definition at line 618 of file Stoich.cpp.
{
    assert(i < funcs_.size());
    assert(funcs_[i]);
    return funcs_[i];
}
References funcs_.
Referenced by Gsolve::fillPoolFuncDep().
getAllowNegative()
bool Stoich::getAllowNegative () const
Definition at line 332 of file Stoich.cpp.
{
    return allowNegative_;
}
References allowNegative_.
Referenced by VoxelPools::advance(), and initCinfo().
getColIndex()
vector< unsigned int > Stoich::getColIndex () const
Definition at line 636 of file Stoich.cpp.
{
    return N_.colIndex();
}
References SparseMatrix< T >::colIndex(), and N_.
Referenced by initCinfo().
getCompartment()
Id Stoich::getCompartment () const
Definition at line 520 of file Stoich.cpp.
{
    return compartment_;
}
References compartment_.
Referenced by initCinfo().
getDsolve()
Id Stoich::getDsolve () const
Definition at line 491 of file Stoich.cpp.
{
    return dsolve_;
}
References dsolve_.
Referenced by initCinfo().
getEnzK2()
double Stoich::getEnzK2 (const Eref & e) const
Get rate k2 (1/sec) for enzyme.
Definition at line 1873 of file Stoich.cpp.
{
    if(useOneWay_)
        return getR1offset1(e);
    else
        return getR2(e);
}
References getR1offset1(), getR2(), and useOneWay_.
getEnzK3()
double Stoich::getEnzK3 (const Eref & e) const
Get rate k3, aka kcat, for enzyme.
Definition at line 1881 of file Stoich.cpp.
{
    if(useOneWay_)
        return getR1offset2(e);
    else
        return getR1offset1(e);
}
References getR1offset1(), getR1offset2(), and useOneWay_.
getEnzNumK1()
double Stoich::getEnzNumK1 (const Eref & e) const
Definition at line 1868 of file Stoich.cpp.
{
    return getR1(e);
}
References getR1().
getKsolve()
Id Stoich::getKsolve () const
Definition at line 473 of file Stoich.cpp.
{
    return ksolve_;
}
References ksolve_.
Referenced by VoxelPools::advance(), VoxelPools::getMethod(), initCinfo(), and Ksolve::print().
getMatrixEntry()
vector< int > Stoich::getMatrixEntry () const
Definition at line 631 of file Stoich.cpp.
{
    return N_.matrixEntry();
}
References SparseMatrix< T >::matrixEntry(), and N_.
Referenced by initCinfo().
getMMenzKcat()
double Stoich::getMMenzKcat (const Eref & e) const
Definition at line 1828 of file Stoich.cpp.
{
    return getR2(e);
}
References getR2().
getMMenzNumKm()
double Stoich::getMMenzNumKm (const Eref & e) const
Definition at line 1812 of file Stoich.cpp.
{
    return getR1(e);
}
References getR1().
getNumAllPools()
unsigned int Stoich::getNumAllPools () const
Returns total number of pools. Includes the pools whose actual calculations happen on another solver, but are given a proxy here in order to handle cross-compartment reactions.
Definition at line 540 of file Stoich.cpp.
{
    return varPoolVec_.size() + offSolverPoolVec_.size() +
           funcTargetPoolVec_.size() + bufPoolVec_.size();
}
References bufPoolVec_, funcTargetPoolVec_, offSolverPoolVec_, and varPoolVec_.
Referenced by Gsolve::fillIncrementFuncDep(), Gsolve::fillPoolFuncDep(), Ksolve::getEstimatedDt(), initCinfo(), Gsolve::setStoich(), and VoxelPools::updateRates().
getNumBufPools()
unsigned int Stoich::getNumBufPools () const
Returns number of local buffered pools.
Definition at line 530 of file Stoich.cpp.
{
    return bufPoolVec_.size();
}
References bufPoolVec_.
Referenced by initCinfo(), VoxelPoolsBase::scaleVolsBufsRates(), and VoxelPools::updateRates().
getNumCoreRates()
unsigned int Stoich::getNumCoreRates () const
Number of rate terms for reactions purely on this compartment.
Utility function to return # of core rates for reacs which are entirely located on current compartment, including all reactants
Definition at line 595 of file Stoich.cpp.
{
    return reacVec_.size() * (1 + useOneWay_) +
           enzVec_.size() * (2 + useOneWay_) + mmEnzVec_.size() +
           incrementFuncVec_.size();
}
References enzVec_, incrementFuncVec_, mmEnzVec_, reacVec_, and useOneWay_.
Referenced by installEnzyme(), installMMenz(), installReaction(), VoxelPools::print(), Gsolve::rebuildGssaSystem(), VoxelPoolsBase::scaleVolsBufsRates(), GssaVoxelPools::setVolumeAndDependencies(), VoxelPools::setVolumeAndDependencies(), Gsolve::updateRateTerms(), and Ksolve::updateRateTerms().
getNumFuncPools()
unsigned int Stoich::getNumFuncPools () const
Returns number of local func target pools.
Definition at line 535 of file Stoich.cpp.
{
    return funcTargetPoolVec_.size();
}
References funcTargetPoolVec_.
Referenced by initCinfo(), and VoxelPools::lsodaSys().
getNumFuncs()
unsigned int Stoich::getNumFuncs () const
Definition at line 613 of file Stoich.cpp.
{
    return funcs_.size();
}
References funcs_.
Referenced by Gsolve::fillPoolFuncDep().
getNumProxyPools()
unsigned int Stoich::getNumProxyPools () const
Returns number of proxy pools here for cross-compartment reactions
Definition at line 546 of file Stoich.cpp.
{
    return offSolverPoolVec_.size();
}
References offSolverPoolVec_.
Referenced by VoxelPools::advance(), initCinfo(), VoxelPools::lsodaSys(), Gsolve::rebuildGssaSystem(), VoxelPools::updateRates(), and VoxelPoolsBase::xferInOnlyProxies().
getNumRates()
unsigned int Stoich::getNumRates () const
Utility function to return # of rates_ entries. This includes the cross-solver reactions.
Definition at line 589 of file Stoich.cpp.
{
    return rates_.size();
}
References rates_.
Referenced by GssaVoxelPools::advance(), Gsolve::fillIncrementFuncDep(), Gsolve::fillMmEnzDep(), Gsolve::fillPoolFuncDep(), Ksolve::getEstimatedDt(), initCinfo(), Gsolve::makeReacDepsUnique(), Gsolve::rebuildGssaSystem(), Gsolve::updateRateTerms(), and Ksolve::updateRateTerms().
getNumVarPools()
unsigned int Stoich::getNumVarPools () const
Returns number of local pools that are updated by solver.
Definition at line 525 of file Stoich.cpp.
{
    return varPoolVec_.size();
}
References varPoolVec_.
Referenced by VoxelPools::advance(), initCinfo(), VoxelPools::lsodaSys(), Gsolve::process(), Ksolve::process(), Gsolve::rebuildGssaSystem(), GssaVoxelPools::reinit(), VoxelPoolsBase::scaleVolsBufsRates(), VoxelPools::updateRates(), and VoxelPoolsBase::xferInOnlyProxies().
getOffSolverCompts()
vector< Id > Stoich::getOffSolverCompts () const
List all the compartments to which the current compt is coupled, by cross-compartment reactions. Self not included.
Definition at line 1974 of file Stoich.cpp.
{
    vector<Id> ret;
    for(map<Id, vector<Id>>::const_iterator i = offSolverPoolMap_.begin();
        i != offSolverPoolMap_.end(); ++i)
        ret.push_back(i->first);
    return ret;
}
References offSolverPoolMap_.
getOffSolverPools()
const vector< Id > & Stoich::getOffSolverPools () const
Definition at line 1969 of file Stoich.cpp.
{
    return offSolverPoolVec_;
}
References offSolverPoolVec_.
getOneWay()
bool Stoich::getOneWay () const
Definition at line 322 of file Stoich.cpp.
{
    return useOneWay_;
}
References useOneWay_.
Referenced by VoxelPoolsBase::filterCrossRateTerms().
getPath()
string Stoich::getPath (const Eref & e) const
Definition at line 440 of file Stoich.cpp.
{
    cout << "DeprecationWarning:: Use Soitch::reacSystemPath instead. In "
            "the future, it will be an error."
         << endl;
    return getReacSystemPath(e);
}
References getReacSystemPath().
getPoolByIndex()
Id Stoich::getPoolByIndex (unsigned int index) const
Definition at line 579 of file Stoich.cpp.
{
    map<Id, unsigned int>::const_iterator i;
    for(i = poolLookup_.begin(); i != poolLookup_.end(); ++i) {
        if(i->second == index)
            return i->first;
    }
    return Id();
}
References Id::Id(), and poolLookup_.
getPoolIdMap()
vector< unsigned int > Stoich::getPoolIdMap () const
Map to look up the index of the pool from its Id. poolIndex = poolIdMap[ Id::value() - poolOffset ] where the poolOffset is the smallest Id::value. poolOffset is passed back as the last entry of this vector. Any Ids that are not pools return EMPTY=~0.
Definition at line 551 of file Stoich.cpp.
{
    if(poolLookup_.size() == 0)
        return vector<unsigned int>(1, 0);
    unsigned int minId = 1000000;
    unsigned int maxId = 0;
    unsigned int maxIndex = 0;
    for(auto i = poolLookup_.cbegin(); i != poolLookup_.end(); ++i) {
        unsigned int j = i->first.value();
        if(j < minId)
            minId = j;
        if(j > maxId)
            maxId = j;
        if(maxIndex < i->second)
            maxIndex = i->second;
    }
    vector<unsigned int> ret(maxId - minId + 2, ~0U);
    for(auto i = poolLookup_.cbegin(); i != poolLookup_.end(); ++i) {
        unsigned int j = i->first.value() - minId;
        ret[j] = i->second;
    }
    ret[ret.size() - 1] = minId;
    return ret;
}
References poolLookup_, and Id::value().
Referenced by initCinfo().
getProxyPools()
vector< Id > Stoich::getProxyPools (Id i) const
Definition at line 646 of file Stoich.cpp.
{
    static vector<Id> dummy;
    if(!i.element()->cinfo()->isA("Stoich")) {
        cout << "Warning: Stoich::getProxyPools: argument " << i
             << " is not a Stoich\n";
        return dummy;
    }
    Id compt = Field<Id>::get(i, "compartment");
    map<Id, vector<Id>>::const_iterator j = offSolverPoolMap_.find(compt);
    if(j != offSolverPoolMap_.end())
        return j->second;
    return dummy;
}
References Element::cinfo(), Id::element(), Field< A >::get(), Cinfo::isA(), and offSolverPoolMap_.
Referenced by initCinfo().
getR1()
double Stoich::getR1 (const Eref & e) const
Returns the internal rate in #/voxel, for R1, for the specified Eref.
Looks up the matching rate for R1. Later we may have additional scaling terms for the specified voxel.
Definition at line 1893 of file Stoich.cpp.
{
    return rates_[convertIdToReacIndex(e.id())]->getR1();
}
References convertIdToReacIndex(), RateTerm::getR1(), Eref::id(), and rates_.
Referenced by getEnzNumK1(), and getMMenzNumKm().
getR1offset1()
double Stoich::getR1offset1 (const Eref & e) const
Returns internal rate R1 in #/voxel, for the rate term following the one directly referred to by the Eref e. Enzymes define multiple successive rate terms, so we look up the first, and then select one after it.
Definition at line 1897 of file Stoich.cpp.
{
    return rates_[convertIdToReacIndex(e.id()) + 1]->getR1();
}
References convertIdToReacIndex(), RateTerm::getR1(), Eref::id(), and rates_.
Referenced by getEnzK2(), and getEnzK3().
getR1offset2()
double Stoich::getR1offset2 (const Eref & e) const
Returns internal rate R1 in #/voxel, for the rate term two after the one directly referred to by the Eref e. Enzymes define multiple successive rate terms, so we look up the first, and then select the second one after it.
Definition at line 1901 of file Stoich.cpp.
{
    return rates_[convertIdToReacIndex(e.id()) + 2]->getR1();
}
References convertIdToReacIndex(), RateTerm::getR1(), Eref::id(), and rates_.
Referenced by getEnzK3().
getR2()
double Stoich::getR2 (const Eref & e) const
Returns the internal rate in #/voxel, for R2, for the specified reacIndex and voxel index. In some cases R2 is undefined, and it then returns 0.
Looks up the matching rate for R2. Later we may have additional scaling terms for the specified voxel.
Definition at line 1910 of file Stoich.cpp.
{
    return rates_[convertIdToReacIndex(e.id())]->getR2();
}
References convertIdToReacIndex(), RateTerm::getR2(), Eref::id(), and rates_.
Referenced by getEnzK2(), and getMMenzKcat().
getRateTerms()
const vector< RateTerm * > & Stoich::getRateTerms () const
Returns a reference to the entire rates_ vector.
Definition at line 608 of file Stoich.cpp.
{
    return rates_;
}
References rates_.
Referenced by Gsolve::fillIncrementFuncDep(), Gsolve::rebuildGssaSystem(), VoxelPoolsBase::scaleVolsBufsRates(), GssaVoxelPools::setVolumeAndDependencies(), VoxelPools::setVolumeAndDependencies(), Gsolve::updateRateTerms(), and Ksolve::updateRateTerms().
getReacNumKf()
double Stoich::getReacNumKf (const Eref & e) const
Return forward reaction rate in #/second units.
Definition at line 1754 of file Stoich.cpp.
{
    unsigned int i = convertIdToReacIndex(e.id());
    if(i != ~0U) {
        return kinterface_->getR1(i, e);
        // return rates_[i]->getR1(e);
    }
    return 0.0;
}
References convertIdToReacIndex(), KsolveBase::getR1(), Eref::id(), and kinterface_.
getReacSystemPath()
string Stoich::getReacSystemPath (const Eref & e) const
Definition at line 448 of file Stoich.cpp.
{
    return wildcard_;
}
References wildcard_.
Referenced by getPath(), and initCinfo().
getRowStart()
vector< unsigned int > Stoich::getRowStart () const
Definition at line 641 of file Stoich.cpp.
{
    return N_.rowStart();
}
References N_, and SparseMatrix< T >::rowStart().
Referenced by initCinfo().
getSpecies()
SpeciesId Stoich::getSpecies (unsigned int poolIndex) const
Returns SpeciesId of specified pool
Definition at line 1938 of file Stoich.cpp.
{
    return species_[poolIndex];
}
References species_.
getStatus()
int Stoich::getStatus () const
getStatus(): Flag to track status of Stoich object. -1: No path yet assigned. 0: Success 1: Warning: Missing reactant in Reac or Enz 2: Warning: Missing substrate in MMenz 4: Warning: Compartment not defined 8: Warning: Neither Ksolve nor Dsolve defined 16: Warning: No objects found on path
Definition at line 661 of file Stoich.cpp.
{
    return status_;
}
References status_.
Referenced by initCinfo().
getStoichiometryMatrix()
const KinSparseMatrix & Stoich::getStoichiometryMatrix () const
Updates the rates for cross-compartment reactions.
Get the rate for a single reaction specified by r, as per all the mol numbers in s. double getReacVelocity(unsigned int r, const double* s, unsigned int volIndex) const; Returns the stoich matrix. Used by gsolve.
Definition at line 1197 of file Stoich.cpp.
{
    return N_;
}
References N_.
Referenced by Gsolve::fillPoolFuncDep(), Gsolve::rebuildGssaSystem(), VoxelPools::updateRates(), VoxelPools::updateReacVelocities(), and GssaVoxelPools::updateReacVelocities().
initCinfo()
const Cinfo * Stoich::initCinfo () static
Definition at line 34 of file Stoich.cpp.
{
    // Field Definitions
    /*
static ElementValueFinfo<Stoich, string> path(
    "path", "Wildcard path for reaction system handled by Stoich",
    &Stoich::setPath, &Stoich::getPath);
    */
    static ElementValueFinfo<Stoich, string> reacSystemPath(
        "reacSystemPath", "Wildcard path for reaction system handled by Stoich",
        &Stoich::setReacSystemPath, &Stoich::getReacSystemPath);
    static ValueFinfo<Stoich, Id> ksolve(
        "ksolve",
        "Id of Kinetic reaction solver class that works with this "
        "Stoich. "
        " Must be of class Ksolve, or Gsolve (at present) "
        " Must be assigned before the path is set.",
        &Stoich::setKsolve, &Stoich::getKsolve);
    static ValueFinfo<Stoich, Id> dsolve(
        "dsolve",
        "Id of Diffusion solver class that works with this Stoich."
        " Must be of class Dsolve "
        " If left unset then the system will be assumed to work in a"
        " non-diffusive, well-stirred cell. If it is going to be "
        " used it must be assigned before the path is set.",
        &Stoich::setDsolve, &Stoich::getDsolve);
    static ValueFinfo<Stoich, Id> compartment(
        "compartment",
        "Id of chemical compartment class that works with this Stoich."
        " Must be derived from class ChemCompt."
        " If left unset then the system will be assumed to work in a"
        " non-diffusive, well-stirred cell. If it is going to be "
        " used it must be assigned before the path is set.",
        &Stoich::setCompartment, &Stoich::getCompartment);
    static ValueFinfo<Stoich, bool> allowNegative(
        "allowNegative",
        "Flag: allow negative values if true. Default is false."
        " This is used to protect the chemical system from going unstable"
        " in cases where the numerical integration gives a negative value."
        " Typically it is a small negative value but is obviously"
        " physically impossible. In some cases we want to use the "
        " solvers to handle general systems of equations (not purely "
        " chemical ones), so we have this flag to allow it.",
        &Stoich::setAllowNegative, &Stoich::getAllowNegative);
    static ReadOnlyValueFinfo<Stoich, unsigned int> numVarPools(
        "numVarPools",
        "Number of time-varying pools to be computed by the "
        "numerical engine",
        &Stoich::getNumVarPools);
    static ReadOnlyValueFinfo<Stoich, unsigned int> numBufPools(
        "numBufPools",
        "Number of buffered pools to be computed by the "
        "numerical engine.",
        &Stoich::getNumBufPools);
    static ReadOnlyValueFinfo<Stoich, unsigned int> numFuncPools(
        "numFuncPools",
        "Number of pools controlled by functions computed by the "
        "numerical engine.",
        &Stoich::getNumFuncPools);
    static ReadOnlyValueFinfo<Stoich, unsigned int> numAllPools(
        "numAllPools",
        "Total number of pools handled by the numerical engine. "
        "This includes variable ones, buffered ones, and functions. "
        "It includes local pools as well as cross-solver proxy pools.",
        &Stoich::getNumAllPools);
    static ReadOnlyValueFinfo<Stoich, unsigned int> numProxyPools(
        "numProxyPools",
        "Number of pools here by proxy as substrates of a cross-"
        "compartment reaction.",
        &Stoich::getNumProxyPools);
    static ReadOnlyValueFinfo<Stoich, vector<unsigned int>> poolIdMap(
        "poolIdMap",
        "Map to look up the index of the pool from its Id."
        "poolIndex = poolIdMap[ Id::value() - poolOffset ] "
        "where the poolOffset is the smallest Id::value. "
        "poolOffset is passed back as the last entry of this vector."
        " Any Ids that are not pools return EMPTY=~0. ",
        &Stoich::getPoolIdMap);
    static ReadOnlyValueFinfo<Stoich, unsigned int> numRates(
        "numRates", "Total number of rate terms in the reaction system.",
        &Stoich::getNumRates);
    // Stuff here for getting Stoichiometry matrix to manipulate in
    // Python.
    static ReadOnlyValueFinfo<Stoich, vector<int>> matrixEntry(
        "matrixEntry",
        "The non-zero matrix entries in the sparse matrix. Their"
        "column indices are in a separate vector and the row"
        "information in a third",
        &Stoich::getMatrixEntry);
    // Stuff here for getting Stoichiometry matrix to manipulate in
    // Python.
    static ReadOnlyValueFinfo<Stoich, vector<unsigned int>> columnIndex(
        "columnIndex", "Column Index of each matrix entry",
        &Stoich::getColIndex);
    // Stuff here for getting Stoichiometry matrix to manipulate in
    // Python.
    static ReadOnlyValueFinfo<Stoich, vector<unsigned int>> rowStart(
        "rowStart", "Row start for each block of entries and column indices",
        &Stoich::getRowStart);
    // Proxy pool information
    static ReadOnlyLookupValueFinfo<Stoich, Id, vector<Id>> proxyPools(
        "proxyPools",
        "Return vector of proxy pools for X-compt reactions between "
        "current stoich, and the argument, which is a StoichId. "
        "The returned pools belong to the compartment handling the "
        "Stoich specified in the argument. "
        "If no pools are found, return an empty vector.",
        &Stoich::getProxyPools);
    static ReadOnlyValueFinfo<Stoich, int> status(
        "status",
        "Status of Stoich in the model building process. Values are: "
        "-1: Reaction path not yet assigned.\n "
        "0: Successfully built stoichiometry matrix.\n "
        "1: Warning: Missing a reactant in a Reac or Enz.\n "
        "2: Warning: Missing a substrate in an MMenz.\n "
        "3: Warning: Missing substrates as well as reactants.\n "
        "4: Warning: Compartment not defined.\n "
        "8: Warning: Neither Ksolve nor Dsolve defined.\n "
        "16: Warning: No objects found on path.\n "
        "",
        &Stoich::getStatus);
    // MsgDest Definitions
    static DestFinfo unzombify("unzombify",
                               "Restore all zombies to their native state",
                               new OpFunc0<Stoich>(&Stoich::unZombifyModel));
    static DestFinfo scaleBufsAndRates(
        "scaleBufsAndRates",
        "Args: voxel#, volRatio\n"
        "Handles requests for runtime volume changes in the specified "
        "voxel#, Used in adaptors changing spine vols.",
        new OpFunc2<Stoich, unsigned int, double>(&Stoich::scaleBufsAndRates));
    // SrcFinfo Definitions
    // SharedMsg Definitions
    static Finfo* stoichFinfos[] = {
        // &path,               // ElementValue, deprecated.
        &reacSystemPath,     // ElementValue
        &ksolve,             // Value
        &dsolve,             // Value
        &compartment,        // Value
        &allowNegative,      // Value
        &numVarPools,        // ReadOnlyValue
        &numBufPools,        // ReadOnlyValue
        &numFuncPools,       // ReadOnlyValue
        &numAllPools,        // ReadOnlyValue
        &numProxyPools,      // ReadOnlyValue
        &poolIdMap,          // ReadOnlyValue
        &numRates,           // ReadOnlyValue
        &matrixEntry,        // ReadOnlyValue
        &columnIndex,        // ReadOnlyValue
        &rowStart,           // ReadOnlyValue
        &proxyPools,         // ReadOnlyLookupValue
        &status,             // ReadOnlyLookupValue
        &unzombify,          // DestFinfo
        &scaleBufsAndRates,  // DestFinfo
    };
    static string doc[] = {
        "Name",
        "Stoich",
        "Author",
        "Upinder S. Bhalla, 2007?, NCBS",
        "Description",
        "Stoich is the class that handles the stoichiometry matrix for a"
        " reaction system, and also setting up the computations for reaction"
        " rates. It has to coordinate the operation of a number of model"
        " definition classes, most importantly: Pools, Reacs and Enz(yme)s."
        " It also coordinates the setup of a large number of numerical solution"
        " engines, or solvers: Ksolve, Gsolve, Dsolve, and SteadyState."
        " The setup process has to follow a tight order, most of which is"
        " internally manged by the Stoich."
        " The Stoich itself does not do any 'process' functions. It just sets "
        "up"
        " data structures for the other objects that do the crunching."
        "\n"
        "\n 1. Compartment is set up to a cell (neuroMesh) or volume (other "
        "meshes)"
        "\n 2. Compartment assigned to Stoich. Here it assigns unique vols."
        "\n 3. Dsolve and Ksolve assigned to Stoich using setKsolve and "
        "setDsolve."
        "\n      3.1 At this point the Stoich::useOneWay_ flag is set if it is "
        "a Gsolve."
        "\n 4. Call Stoich::setWildcard. All the rest happens internally, done "
        "by Stoich:"
        "\n         4.1 assign compartment to Dsolve and Ksolve."
        "\n         4.2 assign numPools and compts to Dsolve and Ksolve."
        "\n         4.3 During Zombification, zeroth vector< RateTerm* > is "
        "built."
        "\n         4.4 afterZombification, stoich builds rateTerm vector for "
        "all vols."
        "\n         4.5 Stoich assigns itself to Dsolve and Ksolve."
        "\n             - Ksolve sets up volIndex on each VoxelPool"
        "\n             - Dsolve gets vector of pools, extracts DiffConst and "
        "MotorConst"
        "\n         4.6 Dsolve assigned to Ksolve::dsolve_ field by the Stoich."
        "\n     5. Reinit,"
        "\n         5.1 Dsolve builds matrix, provided dt has changed. It "
        "needs dt."
        "\n         5.2 Ksolve builds solvers if not done already, assigning "
        "initDt"
        "\n"
        "\n As seen by the user, this reduces to just 4 stages:"
        "\n - Make the objects."
        "\n - Assign compartment, Ksolve and Dsolve to stoich."
        "\n - Set the stoich path."
        "\n - Reinit.",
    };
    static Dinfo<Stoich> dinfo;
    static Cinfo stoichCinfo("Stoich", Neutral::initCinfo(), stoichFinfos,
                             sizeof(stoichFinfos) / sizeof(Finfo*), &dinfo);
    return &stoichCinfo;
}
References Cinfo::Cinfo(), DestFinfo::DestFinfo(), ElementValueFinfo< T, F >::ElementValueFinfo(), getAllowNegative(), getColIndex(), getCompartment(), getDsolve(), getKsolve(), getMatrixEntry(), getNumAllPools(), getNumBufPools(), getNumFuncPools(), getNumProxyPools(), getNumRates(), getNumVarPools(), getPoolIdMap(), getProxyPools(), getReacSystemPath(), getRowStart(), getStatus(), Neutral::initCinfo(), OpFunc0< T >::OpFunc0(), OpFunc2< T, A1, A2 >::OpFunc2(), ReadOnlyLookupValueFinfo< T, L, F >::ReadOnlyLookupValueFinfo(), ReadOnlyValueFinfo< T, F >::ReadOnlyValueFinfo(), scaleBufsAndRates(), setAllowNegative(), setCompartment(), setDsolve(), setKsolve(), setReacSystemPath(), unZombifyModel(), and ValueFinfo< T, F >::ValueFinfo().
innerInstallReaction()
unsigned int Stoich::innerInstallReaction (Id reacId, const vector< Id > & subs, const vector< Id > & prds)
This takes the specified forward and reverse half-reacs belonging to the specified Reac, and builds them into the Stoich.
Definition at line 1473 of file Stoich.cpp.
{
    ZeroOrder* forward = makeHalfReaction(0, subs);
    ZeroOrder* reverse = makeHalfReaction(0, prds);
    unsigned int rateIndex = convertIdToReacIndex(reacId);
    unsigned int revRateIndex = rateIndex;
    if(useOneWay_) {
        rates_[rateIndex] = forward;
        revRateIndex = rateIndex + 1;
        rates_[revRateIndex] = reverse;
    }
    else {
        rates_[rateIndex] = new BidirectionalReaction(forward, reverse);
    }
    vector<unsigned int> molIndex;
    vector<double> reacScaleSubstrates;
    vector<double> reacScaleProducts;
    if(useOneWay_) {
        unsigned int numReactants = forward->getReactants(molIndex);
        for(unsigned int i = 0; i < numReactants; ++i) {
            int temp = N_.get(molIndex[i], rateIndex);
            N_.set(molIndex[i], rateIndex, temp - 1);
            temp = N_.get(molIndex[i], revRateIndex);
            N_.set(molIndex[i], revRateIndex, temp + 1);
        }
        numReactants = reverse->getReactants(molIndex);
        for(unsigned int i = 0; i < numReactants; ++i) {
            int temp = N_.get(molIndex[i], rateIndex);
            N_.set(molIndex[i], rateIndex, temp + 1);
            temp = N_.get(molIndex[i], revRateIndex);
            N_.set(molIndex[i], revRateIndex, temp - 1);
        }
    }
    else {
        unsigned int numReactants = forward->getReactants(molIndex);
        for(unsigned int i = 0; i < numReactants; ++i) {
            int temp = N_.get(molIndex[i], rateIndex);
            N_.set(molIndex[i], rateIndex, temp - 1);
        }
        numReactants = reverse->getReactants(molIndex);
        for(unsigned int i = 0; i < numReactants; ++i) {
            int temp = N_.get(molIndex[i], revRateIndex);
            N_.set(molIndex[i], rateIndex, temp + 1);
        }
    }
    return rateIndex;
}
References BidirectionalReaction::BidirectionalReaction(), convertIdToReacIndex(), SparseMatrix< T >::get(), ZeroOrder::getReactants(), makeHalfReaction(), N_, rates_, SparseMatrix< T >::set(), and useOneWay_.
Referenced by installReaction().
installAndUnschedFunc()
void Stoich::installAndUnschedFunc (Id func, Id pool, double volScale)
This installs a FuncTerm, which evaluates a function to specify the conc of the specific pool. The pool is a BufPool.
Definition at line 1050 of file Stoich.cpp.
{
    static const Cinfo* varCinfo = Cinfo::find("Variable");
    static const Finfo* funcInputFinfo = varCinfo->findFinfo("input");
    static const DestFinfo* df = dynamic_cast<const DestFinfo*>(funcInputFinfo);
    assert(df);
    // Unsched Func
    func.element()->setTick(-2);  // Disable with option to resurrect.
    // Install the FuncTerm
    FuncTerm* ft = new FuncTerm();
    Id ei(func.value() + 1);
    unsigned int numSrc = Field<unsigned int>::get(func, "numVars");
    string _expr = Field<string>::get(func, "expr");
    vector<pair<Id, unsigned int>> srcPools;
    unsigned int n = ei.element()->getInputsWithTgtIndex(srcPools, df);
    ASSERT_EQ(numSrc, n, "NumMsgVsYs Expr=" + _expr);
    vector<unsigned int> poolIndex(numSrc, 0);
    for(unsigned int i = 0; i < numSrc; ++i) {
        unsigned int j = srcPools[i].second;
        if(j >= numSrc) {
            cout << "Warning: Stoich::installAndUnschedFunc: tgt index not "
                    "allocated, "
                 << j << ", " << numSrc << endl;
            continue;
        }
        poolIndex[j] = convertIdToPoolIndex(srcPools[i].first);
    }
    ft->setReactantIndex(poolIndex);
    string expr = Field<string>::get(func, "expr");
    ft->setExpr(expr);
    // Tie the output of the FuncTerm to the pool it controls.
    unsigned int targetIndex = convertIdToPoolIndex(pool);
    ft->setTarget(targetIndex);
    ft->setVolScale(volScale);
    unsigned int funcIndex = convertIdToFuncIndex(func);
    assert(funcIndex != ~0U);
    // funcTarget_ vector tracks which pools are controlled by which func.
    funcTarget_[targetIndex] = funcIndex;
    funcs_[funcIndex] = ft;
}
References convertIdToFuncIndex(), convertIdToPoolIndex(), Id::element(), Cinfo::find(), Cinfo::findFinfo(), funcs_, funcTarget_, FuncTerm::FuncTerm(), Field< A >::get(), Element::getInputsWithTgtIndex(), Id::Id(), FuncTerm::setExpr(), FuncTerm::setReactantIndex(), FuncTerm::setTarget(), Element::setTick(), FuncTerm::setVolScale(), and Id::value().
Referenced by zombifyPoolFuncWithScaling().
installAndUnschedFuncRate()
void Stoich::installAndUnschedFuncRate (Id func, Id pool)
This installs a FuncRate, which evaluates a function to specify the rate of change of conc of the specific pool. The pool is a Pool.
Definition at line 1096 of file Stoich.cpp.
{
    static const Cinfo* varCinfo = Cinfo::find("Variable");
    static const Finfo* funcInputFinfo = varCinfo->findFinfo("input");
    static const DestFinfo* df = dynamic_cast<const DestFinfo*>(funcInputFinfo);
    assert(df);
    // Unsched Func
    func.element()->setTick(-2);  // Disable with option to resurrect.
    // Note that we set aside this index during allocateModelObject
    unsigned int rateIndex = convertIdToReacIndex(func);
    unsigned int tempIndex = convertIdToPoolIndex(pool);
    assert(rateIndex != ~0U);
    assert(tempIndex != ~0U);
    // Install the FuncReac
    FuncRate* fr = new FuncRate(1.0, tempIndex);
    rates_[rateIndex] = fr;
    int stoichEntry = N_.get(tempIndex, rateIndex);
    N_.set(tempIndex, rateIndex, stoichEntry + 1);
    Id ei(func.value() + 1);
    unsigned int numSrc = Field<unsigned int>::get(func, "numVars");
    vector<pair<Id, unsigned int>> srcPools;
    unsigned int n = ei.element()->getInputsWithTgtIndex(srcPools, df);
    ASSERT_EQ(numSrc, n, "NumMsgXS");
    vector<unsigned int> poolIndex(numSrc, 0);
    for(unsigned int i = 0; i < numSrc; ++i) {
        unsigned int j = srcPools[i].second;
        if(j >= numSrc) {
            cout << "Warning: Stoich::installAndUnschedFuncRate: tgt index "
                    "not "
                    "allocated, "
                 << j << ", " << numSrc << endl;
            continue;
        }
        poolIndex[j] = convertIdToPoolIndex(srcPools[i].first);
    }
    fr->setFuncArgIndex(poolIndex);
    string expr = Field<string>::get(func, "expr");
    fr->setExpr(expr);
}
References convertIdToPoolIndex(), convertIdToReacIndex(), Id::element(), Cinfo::find(), Cinfo::findFinfo(), FuncRate::FuncRate(), Field< A >::get(), SparseMatrix< T >::get(), Element::getInputsWithTgtIndex(), Id::Id(), N_, rates_, SparseMatrix< T >::set(), FuncRate::setExpr(), FuncRate::setFuncArgIndex(), Element::setTick(), and Id::value().
Referenced by zombifyModel().
installAndUnschedFuncReac()
void Stoich::installAndUnschedFuncReac (Id func, Id reac)
This installs a FuncReac, which evaluates a function to specify the rate (Kf) of the specified reaction.
Definition at line 1139 of file Stoich.cpp.
{
    static const Cinfo* varCinfo = Cinfo::find("Variable");
    // static const Finfo* funcSrcFinfo = varCinfo->findFinfo( "input" );
    static const Finfo* funcSrcFinfo = varCinfo->findFinfo("input");
    assert(funcSrcFinfo);
    // Unsched Func
    func.element()->setTick(-2);  // Disable with option to resurrect.
    unsigned int rateIndex = convertIdToReacIndex(reac);
    assert(rateIndex != ~0U);
    // Install the FuncReac
    double k = rates_[rateIndex]->getR1();
    vector<unsigned int> reactants;
    unsigned int numForward = rates_[rateIndex]->getReactants(reactants);
    // The reactants vector has both substrates and products.
    reactants.resize(numForward);
    FuncReac* fr = new FuncReac(k, reactants);
    delete rates_[rateIndex];
    rates_[rateIndex] = fr;
    Id ei(func.value() + 1);
    unsigned int numSrc = Field<unsigned int>::get(func, "numVars");
    vector<Id> srcPools;
#ifndef NDEBUG
    unsigned int n =
        ei.element()->getNeighbors(srcPools, funcSrcFinfo);
    assert(numSrc == n);
#endif
    vector<unsigned int> poolIndex(numSrc, 0);
    for(unsigned int i = 0; i < numSrc; ++i)
        poolIndex[i] = convertIdToPoolIndex(srcPools[i]);
    fr->setFuncArgIndex(poolIndex);
    string expr = Field<string>::get(func, "expr");
    fr->setExpr(expr);
}
References convertIdToPoolIndex(), convertIdToReacIndex(), Id::element(), Cinfo::find(), Cinfo::findFinfo(), FuncReac::FuncReac(), Field< A >::get(), Element::getNeighbors(), RateTerm::getR1(), RateTerm::getReactants(), Id::Id(), rates_, FuncRate::setExpr(), FuncRate::setFuncArgIndex(), Element::setTick(), and Id::value().
Referenced by zombifyModel().
installDummyEnzyme()
void Stoich::installDummyEnzyme (Id enzId, Id enzMolId)
This is used when the enzyme lacks sub or prd.
Definition at line 1604 of file Stoich.cpp.
{
    ZeroOrder* r1 = new ZeroOrder(0.0);  // Dummy
    ZeroOrder* r2 = new ZeroOrder(0.0);  // Dummy
    ZeroOrder* r3 = new ZeroOrder(0.0);  // Dummy
    vector<Id> dummy;
    unsigned int rateIndex = convertIdToReacIndex(enzId);
    if(useOneWay_) {
        rates_[rateIndex] = r1;
        rates_[rateIndex + 1] = r2;
        rates_[rateIndex + 2] = r3;
    }
    else {
        rates_[rateIndex] = new BidirectionalReaction(r1, r2);
        rates_[rateIndex + 1] = r3;
    }
    status_ = 1;
}
References BidirectionalReaction::BidirectionalReaction(), convertIdToReacIndex(), rates_, status_, useOneWay_, and ZeroOrder::ZeroOrder().
Referenced by Enz::setSolver().
installEnzyme() [1/2]
void Stoich::installEnzyme (Id enzId, Id enzMolId, Id cplxId, const vector< Id > & subs, const vector< Id > & prds)
Definition at line 1623 of file Stoich.cpp.
{
    vector<Id> temp(subs);
    temp.insert(temp.begin(), enzMolId);
    ZeroOrder* r1 = makeHalfReaction(0, temp);
    temp.clear();
    temp.resize(1, cplxId);
    ZeroOrder* r2 = makeHalfReaction(0, temp);
    ZeroOrder* r3 = makeHalfReaction(0, temp);
    installEnzyme(r1, r2, r3, enzId, enzMolId, prds);
    unsigned int rateIndex = convertIdToReacIndex(enzId);
    if(rateIndex < getNumCoreRates())  // Only handle off-compt reacs
        return;
    vector<Id> subCompt;
    vector<Id> dummy;
    for(vector<Id>::const_iterator i = subs.begin(); i != subs.end(); ++i)
        subCompt.push_back(getCompt(*i).id);
    if(useOneWay_) {
        // enz is split into 3 reactions. Only the first might be off-compt
        subComptVec_.push_back(subCompt);
        subComptVec_.push_back(dummy);
        subComptVec_.push_back(dummy);
        prdComptVec_.push_back(dummy);
        prdComptVec_.push_back(dummy);
        prdComptVec_.push_back(dummy);
        // assert ( 2 + rateIndex - getNumCoreRates() ==
        // subComptVec_.size()); assert ( 2 + rateIndex - getNumCoreRates()
        // == prdComptVec_.size());
    }
    else {
        // enz is split into 2 reactions. Only the first might be off-compt
        subComptVec_.push_back(subCompt);
        subComptVec_.push_back(dummy);
        prdComptVec_.push_back(dummy);
        prdComptVec_.push_back(dummy);
        // assert ( 1+rateIndex - getNumCoreRates() == subComptVec_.size()
        // ); assert ( 1+rateIndex - getNumCoreRates() ==
        // prdComptVec_.size() );
    }
}
References convertIdToReacIndex(), getCompt(), getNumCoreRates(), ObjId::id, installEnzyme(), makeHalfReaction(), prdComptVec_, subComptVec_, and useOneWay_.
Referenced by Enz::setSolver().
installEnzyme() [2/2]
void Stoich::installEnzyme (ZeroOrder * r1, ZeroOrder * r2, ZeroOrder * r3, Id enzId, Id enzMolId, const vector< Id > & prds)
This takes the forward, backward and product formation half-reacs belonging to the specified Enzyme, and builds them into the Stoich. This is the low-level function.
Definition at line 1667 of file Stoich.cpp.
{
    unsigned int rateIndex = convertIdToReacIndex(enzId);
    if(useOneWay_) {
        rates_[rateIndex] = r1;
        rates_[rateIndex + 1] = r2;
        rates_[rateIndex + 2] = r3;
    }
    else {
        rates_[rateIndex] = new BidirectionalReaction(r1, r2);
        rates_[rateIndex + 1] = r3;
    }
    vector<unsigned int> poolIndex;
    unsigned int numReactants = r2->getReactants(poolIndex);
    assert(numReactants == 1);  // Should be cplx as the only product
    unsigned int cplxPool = poolIndex[0];
    if(useOneWay_) {
        numReactants = r1->getReactants(poolIndex);  // Substrates
        for(unsigned int i = 0; i < numReactants; ++i) {
            int temp = N_.get(poolIndex[i], rateIndex);  // terms for r1
            N_.set(poolIndex[i], rateIndex, temp - 1);
            temp = N_.get(poolIndex[i], rateIndex + 1);  // terms for r2
            N_.set(poolIndex[i], rateIndex + 1, temp + 1);
        }
        int temp = N_.get(cplxPool, rateIndex);  // term for r1
        N_.set(cplxPool, rateIndex, temp + 1);
        temp = N_.get(cplxPool, rateIndex + 1);  // term for r2
        N_.set(cplxPool, rateIndex + 1, temp - 1);
    }
    else  // Regular bidirectional reactions.
    {
        numReactants = r1->getReactants(poolIndex);  // Substrates
        for(unsigned int i = 0; i < numReactants; ++i) {
            int temp = N_.get(poolIndex[i], rateIndex);
            N_.set(poolIndex[i], rateIndex, temp - 1);
        }
        int temp = N_.get(cplxPool, rateIndex);
        N_.set(cplxPool, rateIndex, temp + 1);
    }
    // Now assign reaction 3. The complex is the only substrate here.
    // Reac 3 is already unidirectional, so all we need to do to handle
    // one-way reactions is to get the index right.
    unsigned int reac3index = (useOneWay_) ? rateIndex + 2 : rateIndex + 1;
    int temp = N_.get(cplxPool, reac3index);
    N_.set(cplxPool, reac3index, temp - 1);
    // For the products, we go to the prd list directly.
    for(unsigned int i = 0; i < prds.size(); ++i) {
        unsigned int j = convertIdToPoolIndex(prds[i]);
        int temp = N_.get(j, reac3index);
        N_.set(j, reac3index, temp + 1);
    }
    // Enz is also a product here.
    unsigned int enzPool = convertIdToPoolIndex(enzMolId);
    temp = N_.get(enzPool, reac3index);
    N_.set(enzPool, reac3index, temp + 1);
}
References BidirectionalReaction::BidirectionalReaction(), convertIdToPoolIndex(), convertIdToReacIndex(), SparseMatrix< T >::get(), ZeroOrder::getReactants(), N_, rates_, SparseMatrix< T >::set(), and useOneWay_.
Referenced by installEnzyme().
installMMenz() [1/2]
void Stoich::installMMenz (Id enzId, const vector< Id > & enzMols, const vector< Id > & subs, const vector< Id > & prds)
This takes the baseclass for an MMEnzyme and builds the MMenz into the Stoich.
Definition at line 1537 of file Stoich.cpp.
{
    MMEnzymeBase* meb;
    unsigned int enzSiteIndex = convertIdToReacIndex(enzId);
    RateTerm** entry = &rates_[enzSiteIndex];
    if(enzMols.size() != 1) {
        installDummy(entry, enzId, "enzmols");
        status_ |= 2;
        return;
    }
    if(prds.size() < 1) {
        installDummy(entry, enzId, "products");
        status_ |= 1;
        return;
    }
    unsigned int enzIndex = convertIdToPoolIndex(enzMols[0]);
    if(subs.size() == 1) {
        unsigned int subIndex = convertIdToPoolIndex(subs[0]);
        meb = new MMEnzyme1(1, 1, enzIndex, subIndex);
    }
    else if(subs.size() > 1) {
        vector<unsigned int> v;
        for(unsigned int i = 0; i < subs.size(); ++i)
            v.push_back(convertIdToPoolIndex(subs[i]));
        ZeroOrder* rateTerm = new NOrder(1.0, v);
        meb = new MMEnzyme(1, 1, enzIndex, rateTerm);
    }
    else {
        installDummy(entry, enzId, "substrates");
        status_ |= 2;
        return;
    }
    installMMenz(meb, enzSiteIndex, subs, prds);
    if(enzSiteIndex < getNumCoreRates())  // Only handle off-compt reacs
        return;
    vector<Id> subCompt;
    vector<Id> dummy;
    for(auto i = subs.cbegin(); i != subs.end(); ++i)
        subCompt.push_back(getCompt(*i).id);
    subComptVec_.push_back(subCompt);
    prdComptVec_.push_back(dummy);
    assert(enzSiteIndex - getNumCoreRates() == subComptVec_.size());
    assert(enzSiteIndex - getNumCoreRates() == prdComptVec_.size());
}
References convertIdToPoolIndex(), convertIdToReacIndex(), getCompt(), getNumCoreRates(), ObjId::id, installDummy(), installMMenz(), MMEnzyme::MMEnzyme(), MMEnzyme1::MMEnzyme1(), NOrder::NOrder(), prdComptVec_, rates_, status_, and subComptVec_.
Referenced by MMenz::setSolver().
installMMenz() [2/2]
void Stoich::installMMenz (MMEnzymeBase * meb, unsigned int rateIndex, const vector< Id > & subs, const vector< Id > & prds)
This is the internal variant to install the MMenz.
This is the inner function to do the installation.
Definition at line 1586 of file Stoich.cpp.
{
    rates_[rateIndex] = meb;
    for(unsigned int i = 0; i < subs.size(); ++i) {
        unsigned int poolIndex = convertIdToPoolIndex(subs[i]);
        int temp = N_.get(poolIndex, rateIndex);
        N_.set(poolIndex, rateIndex, temp - 1);
    }
    for(unsigned int i = 0; i < prds.size(); ++i) {
        unsigned int poolIndex = convertIdToPoolIndex(prds[i]);
        int temp = N_.get(poolIndex, rateIndex);
        N_.set(poolIndex, rateIndex, temp + 1);
    }
}
References convertIdToPoolIndex(), SparseMatrix< T >::get(), N_, rates_, and SparseMatrix< T >::set().
Referenced by installMMenz().
installReaction()
void Stoich::installReaction (Id reacId, const vector< Id > & subs, const vector< Id > & prds)
Definition at line 1441 of file Stoich.cpp.
{
    static vector<Id> dummy;
    unsigned int rateIndex = innerInstallReaction(reacId, subs, prds);
    if(rateIndex < getNumCoreRates())  // Only handle off-compt reacs
        return;
    vector<Id> subCompt;
    vector<Id> prdCompt;
    for(vector<Id>::const_iterator i = subs.begin(); i != subs.end(); ++i)
        subCompt.push_back(getCompt(*i).id);
    for(vector<Id>::const_iterator i = prds.begin(); i != prds.end(); ++i)
        prdCompt.push_back(getCompt(*i).id);
    assert(rateIndex - getNumCoreRates() == subComptVec_.size());
    assert(rateIndex - getNumCoreRates() == prdComptVec_.size());
    if(useOneWay_) {
        subComptVec_.push_back(subCompt);
        subComptVec_.push_back(prdCompt);
        prdComptVec_.push_back(dummy);
        prdComptVec_.push_back(dummy);
    }
    else {
        subComptVec_.push_back(subCompt);
        prdComptVec_.push_back(prdCompt);
    }
}
References getCompt(), getNumCoreRates(), ObjId::id, innerInstallReaction(), prdComptVec_, subComptVec_, and useOneWay_.
Referenced by Reac::setSolver().
isFuncTarget()
bool Stoich::isFuncTarget (unsigned int poolIndex) const
Returns true if the specified pool is controlled by a func.
Definition at line 625 of file Stoich.cpp.
{
    assert(poolIndex < funcTarget_.size());
    return (funcTarget_[poolIndex] != ~0U);
}
References funcTarget_.
Referenced by VoxelPoolsBase::scaleVolsBufsRates().
locateOffSolverReacs()
void Stoich::locateOffSolverReacs (Id myCompt, vector< Id > & elist)
Scans through elist to find any reactions that connect to pools not located on solver. Removes these reactions from the elist and maintains Ids of the affected reactions, and their off-solver pools, in offSolverReacs_ and offSolverPools_.
Definition at line 734 of file Stoich.cpp.
{
    map<Id, Id> poolComptMap;  // < pool, compt >
    vector<Id> temp;
    temp.reserve(elist.size());
    for(vector<Id>::const_iterator i = elist.begin(); i != elist.end(); ++i) {
        const Element* e = i->element();
        if(e->cinfo()->isA("Reac") || e->cinfo()->isA("EnzBase")) {
            vector<Id> compts;
            if(isOffSolverReac(e, myCompt, compts, poolComptMap)) {
                if(e->cinfo()->isA("Reac")) {
                    offSolverReacVec_.push_back(*i);
                    offSolverReacCompts_.push_back(extractCompts(compts));
                }
                else if(e->cinfo()->isA("Enz")) {
                    offSolverEnzVec_.push_back(*i);
                    offSolverEnzCompts_.push_back(extractCompts(compts));
                }
                else if(e->cinfo()->isA("MMEnz")) {
                    offSolverMMenzVec_.push_back(*i);
                    offSolverMMenzCompts_.push_back(extractCompts(compts));
                }
            }
            else {
                temp.push_back(*i);
            }
        }
        else {
            temp.push_back(*i);
        }
    }
    offSolverPoolMap_.clear();
    for(map<Id, Id>::iterator i = poolComptMap.begin(); i != poolComptMap.end();
        ++i) {
        // fill in the map for activeOffSolverPools.
        offSolverPoolMap_[i->second].push_back(i->first);
    }
    // Ensure we don't have repeats, and the pools are ordered by compt
    offSolverPoolVec_.clear();
    for(map<Id, vector<Id>>::iterator i = offSolverPoolMap_.begin();
        i != offSolverPoolMap_.end(); ++i) {
        if(i->first != myCompt) {
            offSolverPoolVec_.insert(offSolverPoolVec_.end(), i->second.begin(),
                                     i->second.end());
        }
    }
    elist = temp;
}
References Element::cinfo(), Id::element(), extractCompts(), Cinfo::isA(), isOffSolverReac(), offSolverEnzCompts_, offSolverEnzVec_, offSolverMMenzCompts_, offSolverMMenzVec_, offSolverPoolMap_, offSolverPoolVec_, offSolverReacCompts_, offSolverReacVec_, and Id::operator!=().
makeHalfReaction()
ZeroOrder * Stoich::makeHalfReaction (double rate, const vector< Id > & reactants)
Utility function to make a half reac and return the rate term.
Definition at line 1417 of file Stoich.cpp.
{
    ZeroOrder* rateTerm = 0;
    if(reactants.size() == 1) {
        rateTerm = new FirstOrder(rate, convertIdToPoolIndex(reactants[0]));
    }
    else if(reactants.size() == 2) {
        rateTerm = new SecondOrder(rate, convertIdToPoolIndex(reactants[0]),
                                   convertIdToPoolIndex(reactants[1]));
    }
    else if(reactants.size() > 2) {
        vector<unsigned int> temp;
        for(unsigned int i = 0; i < reactants.size(); ++i)
            temp.push_back(convertIdToPoolIndex(reactants[i]));
        rateTerm = new NOrder(rate, temp);
    }
    else {
        cout << "Warning: Stoich::makeHalfReaction: no reactants\n";
        status_ |= 1;
        rateTerm = new ZeroOrder(0.0);  // Dummy RateTerm to avoid crash.
    }
    return rateTerm;
}
References convertIdToPoolIndex(), FirstOrder::FirstOrder(), NOrder::NOrder(), SecondOrder::SecondOrder(), status_, and ZeroOrder::ZeroOrder().
Referenced by innerInstallReaction(), and installEnzyme().
notifyRemoveEnz()
void Stoich::notifyRemoveEnz (const Eref & e)
Definition at line 1211 of file Stoich.cpp.
{
    ;
}  // To fill
Referenced by Enz::setSolver().
notifyRemoveFunc()
void Stoich::notifyRemoveFunc (const Eref & e)
Definition at line 1221 of file Stoich.cpp.
{
    ;
}  // To fill
notifyRemoveMMenz()
void Stoich::notifyRemoveMMenz (const Eref & e)
Definition at line 1216 of file Stoich.cpp.
{
    ;
}  // To fill
Referenced by MMenz::setSolver().
notifyRemoveReac()
void Stoich::notifyRemoveReac (const Eref & e)
Definition at line 1206 of file Stoich.cpp.
{
    ;
}  // To fill
Referenced by Reac::setSolver().
offSolverPoolMap()
const vector< Id > & Stoich::offSolverPoolMap (Id compt) const
Looks up the vector of pool Ids originating from the specified compartment, that are represented on this compartment as proxies.
Definition at line 1984 of file Stoich.cpp.
{
    static vector<Id> blank(0);
    map<Id, vector<Id>>::const_iterator i = offSolverPoolMap_.find(compt);
    if(i != offSolverPoolMap_.end())
        return i->second;
    return blank;
}
References offSolverPoolMap_.
print()
void Stoich::print () const
Utility function, prints out N_, used for debugging.
Definition at line 1949 of file Stoich.cpp.
{
    N_.print();
}
References N_, and SparseMatrix< T >::print().
printRates()
void Stoich::printRates () const
Another utility function, prints out all Kf, kf, Kb, kb.
Definition at line 1955 of file Stoich.cpp.
{
    for(vector<Id>::const_iterator i = reacVec_.begin(); i != reacVec_.end();
        ++i) {
        double Kf = Field<double>::get(*i, "Kf");
        double Kb = Field<double>::get(*i, "Kb");
        double kf = Field<double>::get(*i, "kf");
        double kb = Field<double>::get(*i, "kb");
        cout << "Id=" << *i << ", (Kf,Kb) = (" << Kf << ", " << Kb
             << "), (kf, kb) = (" << kf << ", " << kb << ")\n";
    }
}
References Field< A >::get(), and reacVec_.
rates()
const RateTerm * Stoich::rates (unsigned int i) const
Utility function to return a rates_ entry.
Definition at line 602 of file Stoich.cpp.
{
    assert(i < rates_.size());
    return rates_[i];
}
References rates_.
Referenced by Gsolve::fillMmEnzDep().
resizeArrays()
void Stoich::resizeArrays ()
Using the computed array sizes, now allocate space for them.
Builds the objMap vector, which maps all Ids to the internal indices for pools and reacs that are used in the solver. In addition to the elist, it also scans through the offSolverPools and offSolverReacs to build the map. void allocateObjMap(const vector< Id >& elist);
Definition at line 893 of file Stoich.cpp.
{
    myUnique(funcTargetPoolVec_);
    myUnique(varPoolVec_);
    myUnique(bufPoolVec_);
    myUnique(offSolverPoolVec_);
    myUnique(reacVec_);
    myUnique(offSolverReacVec_);
    myUnique(enzVec_);
    myUnique(offSolverEnzVec_);
    myUnique(mmEnzVec_);
    myUnique(offSolverMMenzVec_);
    clearFuncTargetPools();
    unsigned int totNumPools = varPoolVec_.size() + bufPoolVec_.size() +
                               funcTargetPoolVec_.size() +
                               offSolverPoolVec_.size();
    species_.resize(totNumPools, 0);
    funcTarget_.clear();
    // Only the pools controlled by a func (targets) have positive indices.
    funcTarget_.resize(totNumPools, ~0);
    unsigned int totNumRates =
        (reacVec_.size() + offSolverReacVec_.size()) * (1 + useOneWay_) +
        (enzVec_.size() + offSolverEnzVec_.size()) * (2 + useOneWay_) +
        mmEnzVec_.size() + offSolverMMenzVec_.size() + incrementFuncVec_.size();
    rates_.resize(totNumRates, 0);
    funcs_.resize(poolFuncVec_.size(), 0);
    N_.setSize(totNumPools, totNumRates);
    if(kinterface_)
        kinterface_->setNumPools(totNumPools);
    if(dinterface_)  // Need to set both the numVar and numTot
        dinterface_->setNumVarTotPools(varPoolVec_.size(), totNumPools);
}
References bufPoolVec_, clearFuncTargetPools(), dinterface_, enzVec_, funcs_, funcTarget_, funcTargetPoolVec_, incrementFuncVec_, kinterface_, mmEnzVec_, myUnique(), N_, offSolverEnzVec_, offSolverMMenzVec_, offSolverPoolVec_, offSolverReacVec_, poolFuncVec_, rates_, reacVec_, KsolveBase::setNumPools(), KsolveBase::setNumVarTotPools(), SparseMatrix< T >::setSize(), species_, useOneWay_, and varPoolVec_.
Referenced by allocateModel().
scaleBufsAndRates()
void Stoich::scaleBufsAndRates (unsigned int index, double volScale)
Used to handle run-time size updates for spines.
Definition at line 2079 of file Stoich.cpp.
{
    if(!kinterface_ || status_ != 0)
        return;
    kinterface_->pools(index)->scaleVolsBufsRates(volScale, this);
}
References kinterface_, KsolveBase::pools(), VoxelPoolsBase::scaleVolsBufsRates(), and status_.
Referenced by initCinfo().
setAllowNegative()
void Stoich::setAllowNegative (bool v)
Definition at line 327 of file Stoich.cpp.
{
    allowNegative_ = v;
}
References allowNegative_.
Referenced by initCinfo().
setCompartment()
void Stoich::setCompartment (Id v)
assigns compartment occupied by Stoich.
Definition at line 496 of file Stoich.cpp.
{
    if(!(compartment.element()->cinfo()->isA("ChemCompt"))) {
        cerr << "Error: Stoich::setCompartment: invalid class assigned,"
                " should be ChemCompt or derived class\n";
        return;
    }
    compartment_ = compartment;
    vector<double> temp;
    vector<double> vols =
        Field<vector<double>>::get(compartment, "voxelVolume");
    if(vols.size() > 0) {
        numVoxels_ = vols.size();
        sort(vols.begin(), vols.end());
        double bigVol = vols.back();
        assert(bigVol > 0.0);
        temp.push_back(vols[0] / bigVol);
        for(auto i = vols.begin(); i != vols.end(); ++i) {
            if(!doubleEq(temp.back(), *i / bigVol))
                temp.push_back(*i / bigVol);
        }
    }
}
References Element::cinfo(), compartment_, doubleEq(), Id::element(), Field< A >::get(), Cinfo::isA(), and numVoxels_.
Referenced by initCinfo().
setDsolve()
void Stoich::setDsolve (Id v)
assigns diffusion solver: Dsovle or a Gillespie voxel stepper
Definition at line 478 of file Stoich.cpp.
{
    dsolve_ = Id();
    dinterface_ = 0;
    if(!(dsolve.element()->cinfo()->isA("Dsolve"))) {
        cout << "Error: Stoich::setDsolve: invalid class assigned,"
                " should be Dsolve\n";
        return;
    }
    dsolve_ = dsolve;
    dinterface_ = reinterpret_cast<KsolveBase*>(dsolve.eref().data());
}
References Element::cinfo(), Eref::data(), dinterface_, dsolve_, Id::element(), Id::eref(), Id::Id(), and Cinfo::isA().
Referenced by initCinfo().
setElist()
void Stoich::setElist (const Eref & e, const vector< ObjId > & elist)
Internal function which sets up the model based on the provided elist of all elements managed by this solver.
Definition at line 385 of file Stoich.cpp.
{
    if(compartment_ == Id()) {
        cerr << "Warning: Stoich::setElist/setReacSystemPath: Compartment not "
                "set. Aborting."
             << endl;
        status_ = 4;
        return;
    }
    if(!(kinterface_ || dinterface_)) {
        cerr << "Warning: Stoich::setElist/setReacSystemPath: Neither solver "
                "has been set. Aborting."
             << endl;
        status_ = 8;
        return;
    }
    status_ = 0;
    if(kinterface_)
        kinterface_->setCompartment(compartment_);
    if(dinterface_)
        dinterface_->setCompartment(compartment_);
    vector<Id> temp;
    filterWildcards(temp, elist);
    if(temp.size() == 0) {
        cerr << "Warning: Stoich::setElist/setReacSystemPath: No kinetics "
                "objects "
                "found on path. Aborting."
             << endl;
        status_ = 16;
        return;
    }
    // allocateObjMap( temp );
    deAllocateModel();
    allocateModel(temp);
    if(kinterface_) {
        // kinterface_->setNumPools( n );
        kinterface_->setStoich(e.id());
        Shell* shell = reinterpret_cast<Shell*>(Id().eref().data());
        shell->doAddMsg("Single", compartment_, "voxelVolOut", ksolve_,
                        "voxelVol");
    }
    if(dinterface_) {
        // dinterface_->setNumPools( n );
        dinterface_->setStoich(e.id());
    }
    zombifyModel(e, temp);
    if(kinterface_) {
        kinterface_->setDsolve(dsolve_);
        kinterface_->updateRateTerms();
    }
}
References allocateModel(), compartment_, Eref::data(), deAllocateModel(), dinterface_, Shell::doAddMsg(), dsolve_, Id::eref(), filterWildcards(), Id::Id(), Eref::id(), kinterface_, ksolve_, Id::operator==(), KsolveBase::setCompartment(), KsolveBase::setDsolve(), KsolveBase::setStoich(), status_, KsolveBase::updateRateTerms(), and zombifyModel().
Referenced by setReacSystemPath().
setEnzK1()
void Stoich::setEnzK1 (const Eref & e, double v) const
Later handle all the volumes when this conversion is done.
Sets the rate v (given in millimolor concentration units) for the forward enzyme reaction of binding substrate to enzyme. Does this throughout the compartment in which the enzyme lives. Internally the stoich uses #/voxel units so this involves querying the volume subsystem about volumes for each voxel, and scaling accordingly.
Definition at line 1834 of file Stoich.cpp.
{
    unsigned int index = convertIdToReacIndex(e.id());
    rates_[index]->setR1(v);
    kinterface_->updateRateTerms(index);
}
References convertIdToReacIndex(), Eref::id(), kinterface_, rates_, RateTerm::setR1(), and KsolveBase::updateRateTerms().
Referenced by Enz::setConcK1(), Enz::setK1(), Enz::setSolver(), updateRatesAfterRemesh(), Enz::vSetKcat(), and Enz::vSetKm().
setEnzK2()
void Stoich::setEnzK2 (const Eref & e, double v) const
Set rate k2 (1/sec) for enzyme.
Definition at line 1842 of file Stoich.cpp.
{
    unsigned int index = convertIdToReacIndex(e.id());
    if(useOneWay_) {
        rates_[index + 1]->setR1(v);
        kinterface_->updateRateTerms(index + 1);
    }
    else {
        rates_[index]->setR2(v);
        kinterface_->updateRateTerms(index);
    }
}
References convertIdToReacIndex(), Eref::id(), kinterface_, rates_, RateTerm::setR1(), RateTerm::setR2(), KsolveBase::updateRateTerms(), and useOneWay_.
Referenced by Enz::setK2(), Enz::setRatio(), Enz::setSolver(), updateRatesAfterRemesh(), and Enz::vSetKcat().
setEnzK3()
void Stoich::setEnzK3 (const Eref & e, double v) const
Set rate k3 (1/sec) for enzyme.
Definition at line 1855 of file Stoich.cpp.
{
    unsigned int index = convertIdToReacIndex(e.id());
    if(useOneWay_) {
        rates_[index + 2]->setR1(v);
        kinterface_->updateRateTerms(index + 2);
    }
    else {
        rates_[index + 1]->setR1(v);
        kinterface_->updateRateTerms(index + 1);
    }
}
References convertIdToReacIndex(), Eref::id(), kinterface_, rates_, RateTerm::setR1(), KsolveBase::updateRateTerms(), and useOneWay_.
Referenced by Enz::setSolver(), updateRatesAfterRemesh(), and Enz::vSetKcat().
setFunctionExpr()
void Stoich::setFunctionExpr (const Eref & e, string expr)
Sets the arithmetic expression used in a FuncRate or FuncReac
Definition at line 1915 of file Stoich.cpp.
{
    unsigned int index = convertIdToReacIndex(e.id());
    FuncRate* fr = 0;
    if(index != ~0U)
        fr = dynamic_cast<FuncRate*>(rates_[index]);
    if(fr) {
        fr->setExpr(expr);
    }
    else {
        index = convertIdToFuncIndex(e.id());
        if(index != ~0U) {
            FuncTerm* ft = dynamic_cast<FuncTerm*>(funcs_[index]);
            if(ft) {
                ft->setExpr(expr);
                return;
            }
        }
        cout << "Warning: Stoich::setFunctionExpr( " << e.id().path() << ", "
             << expr << " ): func not found";
    }
}
References convertIdToFuncIndex(), convertIdToReacIndex(), funcs_, Eref::id(), Id::path(), rates_, FuncTerm::setExpr(), and FuncRate::setExpr().
setKsolve()
void Stoich::setKsolve (Id v)
assigns kinetic solver: Ksovle or GSSAsolve.
Definition at line 453 of file Stoich.cpp.
{
    ksolve_ = Id();
    kinterface_ = nullptr;
    if(!(ksolve.element()->cinfo()->isA("Ksolve") ||
         ksolve.element()->cinfo()->isA("Gsolve"))) {
        cout << "Error: Stoich::setKsolve: invalid class assigned,"
                " should be either Ksolve or Gsolve\n";
        return;
    }
    ksolve_ = ksolve;
    kinterface_ = reinterpret_cast<KsolveBase*>(ksolve.eref().data());
    if(ksolve.element()->cinfo()->isA("Gsolve"))
        setOneWay(true);
    else
        setOneWay(false);
}
References Element::cinfo(), Eref::data(), Id::element(), Id::eref(), Id::Id(), Cinfo::isA(), kinterface_, ksolve_, and setOneWay().
Referenced by initCinfo().
setMMenzKcat()
void Stoich::setMMenzKcat (const Eref & e, double v) const
Sets the kcat for MMenz. No conversions needed.
Definition at line 1817 of file Stoich.cpp.
{
    unsigned int index = convertIdToReacIndex(e.id());
    RateTerm* rt = rates_[index];
    // MMEnzymeBase* enz = dynamic_cast< MMEnzymeBase* >( rt );
    // assert( enz );
    rt->setR2(v);
    kinterface_->updateRateTerms(index);
}
References convertIdToReacIndex(), Eref::id(), kinterface_, rates_, RateTerm::setR2(), and KsolveBase::updateRateTerms().
Referenced by MMenz::setSolver(), updateRatesAfterRemesh(), and MMenz::vSetKcat().
setMMenzKm()
void Stoich::setMMenzKm (const Eref & e, double v) const
Sets the Km for MMenz, using appropriate volume conversion to go from the argument (in millimolar) to #/voxel. This may do the assignment among many voxels containing the enz in case there are different volumes.
Definition at line 1786 of file Stoich.cpp.
{
    // Identify MMenz rate term
    unsigned int index = convertIdToReacIndex(e.id());
    RateTerm* rt = rates_[index];
    // MMEnzymeBase* enz = dynamic_cast< MMEnzymeBase* >( rt );
    // assert( enz );
    // Identify MMenz Enzyme substrate. I would have preferred the parent,
    // but that gets messy.
    // unsigned int enzMolIndex = enz->getEnzIndex();
    // This function can be replicated to handle multiple different voxels.
    /*
    vector< double > vols;
    getReactantVols( e, subOut, vols );
    if ( vols.size() == 0 ) {
        cerr << "Error: Stoich::setMMenzKm: no substrates for enzyme " <<
            e << endl;
        return;
    }
    */
    // Do scaling and assignment.
    rt->setR1(v);
    kinterface_->updateRateTerms(index);
}
References convertIdToReacIndex(), Eref::id(), kinterface_, rates_, RateTerm::setR1(), and KsolveBase::updateRateTerms().
Referenced by MMenz::setSolver(), updateRatesAfterRemesh(), and MMenz::vSetKm().
setOneWay()
void Stoich::setOneWay (bool v)
Definition at line 317 of file Stoich.cpp.
{
    useOneWay_ = v;
}
References useOneWay_.
Referenced by setKsolve().
setPath()
void Stoich::setPath (const Eref & e, string path)
Take the provided wildcard path to build the list of elements managed by this solver.
Definition at line 337 of file Stoich.cpp.
{
    cout << "DeprecationWarning:: Use Soitch::readSystemPath instead. In "
            "the future, it will be an error."
         << endl;
    setReacSystemPath(e, v);
}
References setReacSystemPath().
setReacKb()
void Stoich::setReacKb (const Eref & e, double v) const
Sets the reverse rate v (given in millimolor concentration units) for the specified reaction throughout the compartment in which the reaction lives. Internally the stoich uses #/voxel units so this involves querying the volume subsystem about volumes for each voxel, and scaling accordingly.
For now assume a single rate term.
Definition at line 1767 of file Stoich.cpp.
{
    unsigned int i = convertIdToReacIndex(e.id());
    if(i == ~0U)
        return;
    if(useOneWay_) {
        rates_[i + 1]->setR1(v);
        kinterface_->updateRateTerms(i + 1);
    }
    else {
        rates_[i]->setR2(v);
        kinterface_->updateRateTerms(i);
    }
}
References convertIdToReacIndex(), Eref::id(), kinterface_, rates_, RateTerm::setR1(), RateTerm::setR2(), KsolveBase::updateRateTerms(), and useOneWay_.
Referenced by Reac::setConcKb(), Reac::setNumKb(), Reac::setSolver(), and updateRatesAfterRemesh().
setReacKf()
void Stoich::setReacKf (const Eref & e, double v) const
Sets the forward rate v (given in millimolor concentration units) for the specified reaction throughout the compartment in which the reaction lives. Internally the stoich uses #/voxel units so this involves querying the volume subsystem about volumes for each voxel, and scaling accordingly.
Sets the forward rate v (given in millimoloar concentration units) for the specified reaction throughout the compartment in which the reaction lives. Internally the stoich uses #/voxel units so this involves querying the volume subsystem about volumes for each voxel, and scaling accordingly. For now assume a uniform voxel volume and hence just convert on 0 meshIndex.
Definition at line 1744 of file Stoich.cpp.
{
    unsigned int i = convertIdToReacIndex(e.id());
    if(i != ~0U) {
        // rates_[ i ]->setR1( v / volScale );
        rates_[i]->setR1(v);
        kinterface_->updateRateTerms(i);
    }
}
References convertIdToReacIndex(), Eref::id(), kinterface_, rates_, RateTerm::setR1(), and KsolveBase::updateRateTerms().
Referenced by Reac::setConcKf(), Reac::setNumKf(), Reac::setSolver(), and updateRatesAfterRemesh().
setReacSystemPath()
void Stoich::setReacSystemPath (const Eref & e, string wildcard)
Definition at line 345 of file Stoich.cpp.
{
    if(wildcard_ != "" && wildcard_ != v) {
        // unzombify( wildcard_ );
        cerr << __func__ << ":: need to clear old reacSystemPath." << endl;
        status_ = -1;
        return;
    }
    if(ksolve_ == Id()) {
        cout << "Stoich::setReacSystemPath: need to first set ksolve.\n";
        status_ = -1;
        return;
    }
    vector<ObjId> elist;
    wildcard_ = v;
    wildcardFind(wildcard_, elist);
    setElist(e, elist);
}
References Id::Id(), ksolve_, Id::operator==(), setElist(), status_, wildcard_, and wildcardFind().
Referenced by initCinfo(), and setPath().
setSpecies()
void Stoich::setSpecies (unsigned int poolIndex, unsigned int s)
Assigns SpeciesId of specified pool
Definition at line 1943 of file Stoich.cpp.
{
    species_[poolIndex] = s;
}
References species_.
unZombifyModel()
void Stoich::unZombifyModel ()
Converts back to ExpEuler type basic kinetic Elements.
Definition at line 1344 of file Stoich.cpp.
{
    static const Cinfo* functionCinfo = Cinfo::find("Function");
    unZombifyPools();
    vector<Id> temp = reacVec_;
    temp.insert(temp.end(), offSolverReacVec_.begin(), offSolverReacVec_.end());
    for(vector<Id>::iterator i = temp.begin(); i != temp.end(); ++i) {
        Element* e = i->element();
        if(e != 0 && e->cinfo()->isA("Reac"))
            SetGet1<ObjId>::set(*i, "setSolver", Id());  // Clear stoich
    }
    temp = mmEnzVec_;
    temp.insert(temp.end(), offSolverMMenzVec_.begin(),
                offSolverMMenzVec_.end());
    for(vector<Id>::iterator i = temp.begin(); i != temp.end(); ++i) {
        Element* e = i->element();
        if(e != 0 && e->cinfo()->isA("EnzBase")) {
            SetGet1<ObjId>::set(*i, "setSolver", Id());  // Clear stoich
        }
    }
    temp = enzVec_;
    temp.insert(temp.end(), offSolverEnzVec_.begin(), offSolverEnzVec_.end());
    for(vector<Id>::iterator i = temp.begin(); i != temp.end(); ++i) {
        Element* e = i->element();
        if(e != 0 && e->cinfo()->isA("EnzBase")) {
            SetGet1<ObjId>::set(*i, "setSolver", Id());  // Clear stoich
        }
    }
    temp = poolFuncVec_;
    temp.insert(temp.end(), incrementFuncVec_.begin(), incrementFuncVec_.end());
    for(vector<Id>::iterator i = temp.begin(); i != temp.end(); ++i) {
        Element* e = i->element();
        if(e != 0 && e->cinfo()->isA("Function")) {
            SetGet1<ObjId>::set(*i, "setSolver", Id());
        }
        if(e != 0 && e->getTick() == -2) {
            int t = Clock::lookupDefaultTick(e->cinfo()->name());
            e->setTick(t);
        }
    }
}
References Element::cinfo(), Id::element(), enzVec_, Cinfo::find(), Element::getTick(), Id::Id(), incrementFuncVec_, Cinfo::isA(), Clock::lookupDefaultTick(), mmEnzVec_, Cinfo::name(), offSolverEnzVec_, offSolverMMenzVec_, offSolverReacVec_, poolFuncVec_, reacVec_, SetGet1< A >::set(), Element::setTick(), and unZombifyPools().
Referenced by initCinfo(), and ~Stoich().
unZombifyPools()
void Stoich::unZombifyPools ()
unZombifies Pools. Helper for unZombifyModel.
Definition at line 1322 of file Stoich.cpp.
{
    static ObjId root = ObjId();
    unsigned int i;
    for(auto i = varPoolVec_.begin(); i != varPoolVec_.end(); ++i) {
        Element* e = i->element();
        if(e && !e->isDoomed())
            SetGet2<ObjId, ObjId>::set(*i, "setSolvers", root, root);
    }
    for(auto i = bufPoolVec_.begin(); i != bufPoolVec_.end(); ++i) {
        Element* e = i->element();
        if(e && !e->isDoomed())
            SetGet2<ObjId, ObjId>::set(*i, "setSolvers", root, root);
    }
    for(auto i = funcTargetPoolVec_.begin(); i != funcTargetPoolVec_.end();
        ++i) {
        Element* e = i->element();
        if(e && !e->isDoomed())
            SetGet2<ObjId, ObjId>::set(*i, "setSolvers", root, root);
    }
}
References bufPoolVec_, Id::element(), funcTargetPoolVec_, Element::isDoomed(), ObjId::ObjId(), SetGet2< A1, A2 >::set(), and varPoolVec_.
Referenced by unZombifyModel().
updateFuncs()
void Stoich::updateFuncs (double * s, double t) const
Updates the function values, within s.
Definition at line 1998 of file Stoich.cpp.
{
    for(auto i = funcs_.cbegin(); i != funcs_.end(); ++i)
        if(*i)
            (*i)->evalPool(s, t);
}
References FuncTerm::evalPool(), and funcs_.
Referenced by GssaVoxelPools::advance(), VoxelPools::lsodaSys(), GssaVoxelPools::refreshAtot(), GssaVoxelPools::reinit(), and GssaVoxelPools::updateDependentMathExpn().
updateRatesAfterRemesh()
void Stoich::updateRatesAfterRemesh ()
This function scans all reacs and enzymes and recalculates the internal rate terms depending on the reference terms stored in the original chemical object.
updateJunctionRates: Updates the rates for cross-compartment reactions. These are located at the end of the rates_ vector, and are directly indexed by the reacTerms. void Stoich::updateJunctionRates(const double* s, const vector< unsigned int >& reacTerms, double* yprime) { for (vector< unsigned int >::const_iterator i = reacTerms.begin(); i != reacTerms.end(); ++i) { assert(*i < rates_[0].size()); yprime++ += (*rates_[0][*i])(s); } }
Definition at line 2022 of file Stoich.cpp.
{
    for(vector<Id>::iterator i = reacVec_.begin(); i != reacVec_.end(); ++i) {
        double Kf = Field<double>::get(*i, "Kf");
        double Kb = Field<double>::get(*i, "Kb");
        setReacKf(i->eref(), Kf);
        setReacKb(i->eref(), Kb);
    }
    vector<Id>::iterator i;
    for(i = offSolverReacVec_.begin(); i != offSolverReacVec_.end(); ++i) {
        assert(i->element()->cinfo()->isA("Reac"));
        double Kf = Field<double>::get(*i, "Kf");
        double Kb = Field<double>::get(*i, "Kb");
        setReacKf(i->eref(), Kf);
        setReacKb(i->eref(), Kb);
    }
    for(i = offSolverEnzVec_.begin(); i != offSolverEnzVec_.end(); ++i) {
        assert(i->element()->cinfo()->isA("Enz"));
        double concK1 = Field<double>::get(*i, "concK1");
        double k3 = Field<double>::get(*i, "k3");
        double k2 = Field<double>::get(*i, "k2");
        setEnzK3(i->eref(), k3);
        setEnzK2(i->eref(), k2);
        setEnzK1(i->eref(), concK1);
    }
    for(i = offSolverMMenzVec_.begin(); i != offSolverMMenzVec_.end(); ++i) {
        assert(i->element()->cinfo()->isA("MMEnz"));
        double Km = Field<double>::get(*i, "Km");
        double kcat = Field<double>::get(*i, "kcat");
        setMMenzKm(i->eref(), Km);
        setMMenzKcat(i->eref(), kcat);
    }
}
References Element::cinfo(), Id::element(), Id::eref(), Field< A >::get(), Cinfo::isA(), offSolverEnzVec_, offSolverMMenzVec_, offSolverReacVec_, reacVec_, setEnzK1(), setEnzK2(), setEnzK3(), setMMenzKcat(), setMMenzKm(), setReacKb(), and setReacKf().
updateReacVelocities()
void Stoich::updateReacVelocities (const double * s, vector< double > & vel, unsigned int volIndex) const
Updates the yprime array, rate of change of each molecule The volIndex specifies which set of rates to use, since the rates are volume dependent. Moved to VoxelPools void updateRates(const double* s, double* yprime, unsigned int volIndex) const; Computes the velocity of each reaction, vel. The volIndex specifies which set of rates to use, since the rates are volume dependent.
zombifyChemCompt()
void Stoich::zombifyChemCompt (Id compt)
zombifyModel()
void Stoich::zombifyModel (const Eref & e, const vector< Id > & elist)
zombifyModel marches through the specified id list and converts all entries into zombies. The first arg e is the Eref of the Stoich itself.
Definition at line 1264 of file Stoich.cpp.
{
    static const Cinfo* poolCinfo = Cinfo::find("Pool");
    static const Cinfo* bufPoolCinfo = Cinfo::find("BufPool");
    static const Cinfo* reacCinfo = Cinfo::find("Reac");
    static const Cinfo* enzCinfo = Cinfo::find("Enz");
    static const Cinfo* mmEnzCinfo = Cinfo::find("MMenz");
    // static const Finfo* funcSrcFinfo = Cinfo::find(
    // "Function")->findFinfo( "valueOut" ); vector< Id > meshEntries;
    vector<Id> temp = elist;
    temp.insert(temp.end(), offSolverReacVec_.begin(), offSolverReacVec_.end());
    temp.insert(temp.end(), offSolverEnzVec_.begin(), offSolverEnzVec_.end());
    temp.insert(temp.end(), offSolverMMenzVec_.begin(),
                offSolverMMenzVec_.end());
    for(vector<Id>::const_iterator i = temp.begin(); i != temp.end(); ++i) {
        Element* ei = i->element();
        if(ei->cinfo() == poolCinfo || ei->cinfo() == bufPoolCinfo) {
            // We need to check the increment message before we zombify the
            // pool, because ZombiePool doesn't have this message.
            Id funcId = findFuncMsgSrc(*i, "increment");
            if(funcId != Id()) {
                Element* fe = funcId.element();
                installAndUnschedFuncRate(funcId, (*i));
                SetGet1<ObjId>::set(funcId, "setSolver", e.id());
            }
            else {  // Regular conc controller via func.
                funcId = zombifyPoolFuncWithScaling(e, *i);
            }
            double concInit = Field<double>::get(*i, "concInit");
            SetGet2<ObjId, ObjId>::set(*i, "setSolvers", ksolve_, dsolve_);
            Field<double>::set(*i, "concInit", concInit);
            ei->resize(numVoxels_);
            for(unsigned int j = 0; j < numVoxels_; ++j) {
                ObjId oi(ei->id(), j);
                Field<double>::set(oi, "concInit", concInit);
            }
        }
        else if(ei->cinfo() == reacCinfo) {
            SetGet1<ObjId>::set(*i, "setSolver", e.id());
            Id funcId = findFuncMsgSrc(*i, "setNumKf");
            if(funcId != Id()) {
                Element* fe = funcId.element();
                installAndUnschedFuncReac(funcId, (*i));
                SetGet1<ObjId>::set(funcId, "setSolver", e.id());
            }
        }
        else if(ei->cinfo() == mmEnzCinfo) {
            SetGet1<ObjId>::set(*i, "setSolver", e.id());
            // EnzBase::zombify(ei, zombieMMenzCinfo, e.id());
        }
        else if(ei->cinfo() == enzCinfo) {
            SetGet1<ObjId>::set(*i, "setSolver", e.id());
        }
    }
}
References Element::cinfo(), dsolve_, Id::element(), Cinfo::find(), findFuncMsgSrc(), Field< A >::get(), Id::Id(), Element::id(), Eref::id(), installAndUnschedFuncRate(), installAndUnschedFuncReac(), ksolve_, numVoxels_, ObjId::ObjId(), offSolverEnzVec_, offSolverMMenzVec_, offSolverReacVec_, Id::operator!=(), Element::resize(), SetGet1< A >::set(), Field< A >::set(), SetGet2< A1, A2 >::set(), and zombifyPoolFuncWithScaling().
Referenced by setElist().
zombifyPoolFuncWithScaling()
Id Stoich::zombifyPoolFuncWithScaling (const Eref & e, Id pool)
Utility function to find if incoming message assigns N or conc, and to appropriately zombify the function and set up its parameters including volume scaling.
Definition at line 1240 of file Stoich.cpp.
{
    double scale = 1.0;
    Id funcId = findFuncMsgSrc(pool, "setN");
    if(funcId == Id()) {
        funcId = findFuncMsgSrc(pool, "setNInit");  // Note funny caps
        if(funcId == Id()) {
            scale = NA * Field<double>::get(pool, "volume");
            funcId = findFuncMsgSrc(pool, "setConc");
            if(funcId == Id()) {
                funcId = findFuncMsgSrc(pool, "setConcInit");
            }
        }
    }
    if(funcId != Id()) {
        Element* fe = funcId.element();
        installAndUnschedFunc(funcId, pool, scale);
        SetGet1<ObjId>::set(funcId, "setSolver", e.id());
    }
    return funcId;
}
References Id::element(), findFuncMsgSrc(), Field< A >::get(), Id::Id(), Eref::id(), installAndUnschedFunc(), NA, Id::operator!=(), Id::operator==(), and SetGet1< A >::set().
Referenced by zombifyModel().
Member Data Documentation
allowNegative_
bool Stoich::allowNegative_ private
True if pools are permitted to take negative concentrations. This may happen if solver is handling a general equation system that is not constrained by chemical rules. Defaults to False, so that we cannot have negative concs.
Definition at line 518 of file Stoich.h.
Referenced by getAllowNegative(), setAllowNegative(), and Stoich().
bufPoolVec_
vector<Id> Stoich::bufPoolVec_ private
Vector of bufPool Ids.
Definition at line 600 of file Stoich.h.
Referenced by allocateModelObject(), buildPoolLookup(), clearFuncTargetPools(), deAllocateModel(), getNumAllPools(), getNumBufPools(), resizeArrays(), and unZombifyPools().
compartment_
Id Stoich::compartment_ private
Contains Id of compartment holding reac system. Optional.
Definition at line 529 of file Stoich.h.
Referenced by getCompartment(), setCompartment(), setElist(), and Stoich().
dinterface_
KsolveBase* Stoich::dinterface_ private
Pointer for dsolve.
Definition at line 534 of file Stoich.h.
Referenced by resizeArrays(), setDsolve(), setElist(), and Stoich().
dsolve_
Id Stoich::dsolve_ private
This contains the Id of the Diffusion solver. Optional.
Definition at line 526 of file Stoich.h.
Referenced by getDsolve(), setDsolve(), setElist(), Stoich(), and zombifyModel().
enzVec_
vector<Id> Stoich::enzVec_ private
Map back from enz index to Id. Needed to unzombify
Definition at line 618 of file Stoich.h.
Referenced by allocateModelObject(), buildRateTermLookup(), deAllocateModel(), getNumCoreRates(), resizeArrays(), and unZombifyModel().
funcLookup_
map<Id, unsigned int> Stoich::funcLookup_ private
Definition at line 661 of file Stoich.h.
Referenced by buildFuncLookup(), and convertIdToFuncIndex().
funcs_
vector<FuncTerm*> Stoich::funcs_ private
The FuncTerms handle mathematical ops on mol levels.
Definition at line 565 of file Stoich.h.
Referenced by deAllocateModel(), funcs(), getNumFuncs(), installAndUnschedFunc(), resizeArrays(), setFunctionExpr(), updateFuncs(), and ~Stoich().
funcTarget_
vector<unsigned int> Stoich::funcTarget_ private
vector tracks which pool is controlled by which func. Unused entries are flagged by ~0. funcTarget_[ poolIndex ] == funcIndex
Definition at line 637 of file Stoich.h.
Referenced by installAndUnschedFunc(), isFuncTarget(), and resizeArrays().
funcTargetPoolVec_
vector<Id> Stoich::funcTargetPoolVec_ private
vector of id of pools controlled by a func.
Definition at line 642 of file Stoich.h.
Referenced by allocateModelObject(), buildPoolLookup(), clearFuncTargetPools(), deAllocateModel(), getNumAllPools(), getNumFuncPools(), resizeArrays(), and unZombifyPools().
incrementFuncVec_
vector<Id> Stoich::incrementFuncVec_ private
Vector of funcs controlling pool increment, that is dN/dt This is handled as a rateTerm.
Definition at line 648 of file Stoich.h.
Referenced by allocateModelObject(), buildRateTermLookup(), deAllocateModel(), getNumCoreRates(), resizeArrays(), and unZombifyModel().
kinterface_
KsolveBase* Stoich::kinterface_ private
Pointer for ksolve.
Definition at line 532 of file Stoich.h.
Referenced by getReacNumKf(), resizeArrays(), scaleBufsAndRates(), setElist(), setEnzK1(), setEnzK2(), setEnzK3(), setKsolve(), setMMenzKcat(), setMMenzKm(), setReacKb(), setReacKf(), and Stoich().
ksolve_
Id Stoich::ksolve_ private
This contains the Id of the Kinetic solver.
Definition at line 523 of file Stoich.h.
Referenced by getKsolve(), setElist(), setKsolve(), setReacSystemPath(), Stoich(), and zombifyModel().
mmEnzVec_
vector<Id> Stoich::mmEnzVec_ private
Map back from enz index to Id. Needed to unzombify
Definition at line 624 of file Stoich.h.
Referenced by allocateModelObject(), buildRateTermLookup(), deAllocateModel(), getNumCoreRates(), resizeArrays(), and unZombifyModel().
N_
KinSparseMatrix Stoich::N_ private
N_ is the stoichiometry matrix. All pools * all reac terms.
Definition at line 568 of file Stoich.h.
Referenced by getColIndex(), getMatrixEntry(), getRowStart(), getStoichiometryMatrix(), innerInstallReaction(), installAndUnschedFuncRate(), installEnzyme(), installMMenz(), print(), and resizeArrays().
numVoxels_
unsigned int Stoich::numVoxels_ private
Number of voxels in reac system.
This tracks the unique volumes handled by the reac system. Maps one-to-one with the vector of vector of RateTerms. vector< double > uniqueVols_;
Definition at line 562 of file Stoich.h.
Referenced by setCompartment(), Stoich(), and zombifyModel().
offSolverEnzCompts_
vector<pair<Id, Id> > Stoich::offSolverEnzCompts_ private
Definition at line 736 of file Stoich.h.
Referenced by deAllocateModel(), and locateOffSolverReacs().
offSolverEnzVec_
vector<Id> Stoich::offSolverEnzVec_ private
Definition at line 619 of file Stoich.h.
Referenced by buildRateTermLookup(), deAllocateModel(), locateOffSolverReacs(), resizeArrays(), unZombifyModel(), updateRatesAfterRemesh(), and zombifyModel().
offSolverMMenzCompts_
vector<pair<Id, Id> > Stoich::offSolverMMenzCompts_ private
Definition at line 737 of file Stoich.h.
Referenced by deAllocateModel(), and locateOffSolverReacs().
offSolverMMenzVec_
vector<Id> Stoich::offSolverMMenzVec_ private
Definition at line 625 of file Stoich.h.
Referenced by buildRateTermLookup(), deAllocateModel(), locateOffSolverReacs(), resizeArrays(), unZombifyModel(), updateRatesAfterRemesh(), and zombifyModel().
offSolverPoolMap_
map<Id, vector<Id> > Stoich::offSolverPoolMap_ private
Map of vectors of Ids of offSolver pools. Each map entry contains the vector of Ids of proxy pools coming from the specified compartment. In use, the junction will copy the pool indices over for data transfer.
Definition at line 724 of file Stoich.h.
Referenced by deAllocateModel(), getOffSolverCompts(), getProxyPools(), locateOffSolverReacs(), and offSolverPoolMap().
offSolverPoolVec_
vector<Id> Stoich::offSolverPoolVec_ private
These are pools that were not in the original scope of the solver, but have to be brought in because they are reactants of one or more of the offSolverReacs.
Definition at line 607 of file Stoich.h.
Referenced by buildPoolLookup(), deAllocateModel(), getNumAllPools(), getNumProxyPools(), getOffSolverPools(), locateOffSolverReacs(), and resizeArrays().
offSolverReacCompts_
vector<pair<Id, Id> > Stoich::offSolverReacCompts_ private
Tracks the reactions that go off the current solver. vector< Id > offSolverReacs_; Which compartment(s) does the off solver reac connect to? Usually it is just one, in which case the second id is Id()
Definition at line 735 of file Stoich.h.
Referenced by deAllocateModel(), and locateOffSolverReacs().
offSolverReacVec_
vector<Id> Stoich::offSolverReacVec_ private
Definition at line 613 of file Stoich.h.
Referenced by buildRateTermLookup(), deAllocateModel(), locateOffSolverReacs(), resizeArrays(), unZombifyModel(), updateRatesAfterRemesh(), and zombifyModel().
poolFuncVec_
vector<Id> Stoich::poolFuncVec_ private
Vector of funcs controlling pool number, that is N.
Definition at line 630 of file Stoich.h.
Referenced by allocateModelObject(), buildFuncLookup(), deAllocateModel(), resizeArrays(), and unZombifyModel().
PoolIsNotOnSolver
const unsigned int Stoich::PoolIsNotOnSolver static
Returns the index of the matching volume, which is also the index into the RateTerm vector. unsigned int indexOfMatchingVolume(double vol) const;
Definition at line 502 of file Stoich.h.
poolLookup_
map<Id, unsigned int> Stoich::poolLookup_ private
Definition at line 659 of file Stoich.h.
Referenced by buildPoolLookup(), convertIdToPoolIndex(), getPoolByIndex(), and getPoolIdMap().
prdComptVec_
vector<vector<Id> > Stoich::prdComptVec_ private
prdComptVec_[rateTermIndex][product#]: Identifies compts for each product for each cross-compartment RateTerm in the rates_vector.
Definition at line 751 of file Stoich.h.
Referenced by installEnzyme(), installMMenz(), and installReaction().
rates_
vector<RateTerm*> Stoich::rates_ private
The RateTerms handle the update operations for reaction rate v_. This is the master vector of RateTerms, and it is scaled to a volume such that the 'n' units and the conc units are identical. Duplicates of this vector are made in each voxel with a different volume. The duplicates have rates scaled as per volume. The RateTerms vector also includes reactions that have off-compartment products. These need special volume scaling involving all the interactiong compartments.
Definition at line 553 of file Stoich.h.
Referenced by convertRatesToStochasticForm(), deAllocateModel(), getNumRates(), getR1(), getR1offset1(), getR1offset2(), getR2(), getRateTerms(), innerInstallReaction(), installAndUnschedFuncRate(), installAndUnschedFuncReac(), installDummyEnzyme(), installEnzyme(), installMMenz(), installMMenz(), rates(), resizeArrays(), setEnzK1(), setEnzK2(), setEnzK3(), setFunctionExpr(), setMMenzKcat(), setMMenzKm(), setReacKb(), setReacKf(), Stoich(), and ~Stoich().
rateTermLookup_
map<Id, unsigned int> Stoich::rateTermLookup_ private
Definition at line 660 of file Stoich.h.
Referenced by buildRateTermLookup(), and convertIdToReacIndex().
reacFuncVec_
vector<Id> Stoich::reacFuncVec_ private
Vector of funcs controlling reac rate, that is numKf This is handled as a rateTerm.
Definition at line 654 of file Stoich.h.
Referenced by allocateModelObject(), and deAllocateModel().
reacVec_
vector<Id> Stoich::reacVec_ private
Vector of reaction ids.
Definition at line 612 of file Stoich.h.
Referenced by allocateModelObject(), buildRateTermLookup(), deAllocateModel(), getNumCoreRates(), printRates(), resizeArrays(), unZombifyModel(), and updateRatesAfterRemesh().
species_
vector<unsigned int> Stoich::species_ private
Lookup from each molecule to its Species identifer This will eventually be tied into an ontology reference.
Definition at line 540 of file Stoich.h.
Referenced by getSpecies(), resizeArrays(), and setSpecies().
status_
int Stoich::status_ private
Number of variable molecules that the solver deals with, that are local to the solver. Number of variable molecules that the solver deals with, including the proxy molecules which belong in other compartments.
unsigned int totVarPools_; Number of buffered molecules Looks up the rate term from the Id for a reac, enzyme, or func. map< Id, unsigned int > rateTermLookup_; Number functions, currently only the ones controlling molecule numbers, like sumtotals. unsigned int numFunctions_; Number of reactions in the solver model. This includes conversion reactions A + B <—> C enzyme reactions E + S <—> E.S —> E + P and MM enzyme reactions rate = E.S.kcat / (Km + S) The enzyme reactions count as two reaction steps. unsigned int numReac_; Flag to track status of Stoich object. -1: No path yet assigned. 0: Success 1: Warning: Missing reactant in Reac or Enz 2: Warning: Missing substrate in MMenz 4: Warning: Compartment not defined 8: Warning: Neither Ksolve nore Dsolve defined
Definition at line 711 of file Stoich.h.
Referenced by getStatus(), installDummyEnzyme(), installMMenz(), makeHalfReaction(), scaleBufsAndRates(), setElist(), setReacSystemPath(), and Stoich().
subComptVec_
vector<vector<Id> > Stoich::subComptVec_ private
subComptVec_[rateTermIndex][substrate#]: Identifies compts for each substrate for each cross-compartment RateTerm in the rates_vector.
Definition at line 744 of file Stoich.h.
Referenced by installEnzyme(), installMMenz(), and installReaction().
useOneWay_
bool Stoich::useOneWay_ private
True if the stoich matrix is set up to handle only one-way reactions, as is needed in the case of the Gillespie algorithm.
Definition at line 510 of file Stoich.h.
Referenced by buildRateTermLookup(), getEnzK2(), getEnzK3(), getNumCoreRates(), getOneWay(), innerInstallReaction(), installDummyEnzyme(), installEnzyme(), installEnzyme(), installReaction(), resizeArrays(), setEnzK2(), setEnzK3(), setOneWay(), setReacKb(), and Stoich().
varPoolVec_
vector<Id> Stoich::varPoolVec_ private
Maps Ids to objects in the S_, RateTerm, and FuncTerm vectors. There will be holes in this map, but look up is very fast. The calling Id must know what it wants to find: all it gets back is an integer. The alternative is to have multiple maps, but that is slower. Assume no arrays. Each Pool/reac etc must be a unique Element. Later we'll deal with diffusion. Minor efficiency: We will usually have a set of objects that are nearly contiguous in the map. May as well start with the first of them. Vector of variablePool Ids.
Definition at line 595 of file Stoich.h.
Referenced by allocateModelObject(), buildPoolLookup(), clearFuncTargetPools(), deAllocateModel(), getNumAllPools(), getNumVarPools(), resizeArrays(), and unZombifyPools().
wildcard_
string Stoich::wildcard_ private
Definition at line 520 of file Stoich.h.
Referenced by getReacSystemPath(), setReacSystemPath(), and Stoich().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/ksolve/Stoich.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/ksolve/Stoich.cpp