MOOSE - Multiscale Object Oriented Simulation Environment: FinfoWrapper Class Reference
FinfoWrapper Class Reference
#include <Finfo.h>
Public Member Functions
vector< string > dest () const
string docs () const
FinfoWrapper (const Finfo *other)
string getName () const
vector< string > src () const
string type () const
Private Attributes
const Finfo * f_
Detailed Description
Definition at line 150 of file Finfo.h.
Constructor & Destructor Documentation
FinfoWrapper()
FinfoWrapper::FinfoWrapper (const Finfo * other) inline
Definition at line 152 of file Finfo.h.
                                     : f_(other)
    {
        ;
    }
References f_.
Referenced by Cinfo::findFinfoWrapper().
Member Function Documentation
dest()
vector< string > FinfoWrapper::dest () const
Returns the list of subsidiary destFinfos. Used in SharedFinfos and ValueFinfos, empty otherwise. Goes via internal virtual function.
Definition at line 91 of file Finfo.cpp.
{
    return f_->innerDest();
}
References f_, and Finfo::innerDest().
Referenced by Finfo::initCinfo(), and testFinfoFields().
docs()
string FinfoWrapper::docs () const
Definition at line 76 of file Finfo.cpp.
{
    return f_->docs();
}
References Finfo::docs(), and f_.
Referenced by Finfo::initCinfo(), and testFinfoFields().
getName()
string FinfoWrapper::getName () const
Definition at line 71 of file Finfo.cpp.
{
    return f_->name();
}
References f_, and Finfo::name().
Referenced by Finfo::initCinfo(), and testFinfoFields().
src()
vector< string > FinfoWrapper::src () const
Returns the list of subsidiary SrcFinfos. Used in Shared Finfos, empty otherwise. Goes via internal virtual function.
Definition at line 86 of file Finfo.cpp.
{
    return f_->innerSrc();
}
References f_, and Finfo::innerSrc().
Referenced by Finfo::initCinfo(), and testFinfoFields().
type()
string FinfoWrapper::type () const
Definition at line 81 of file Finfo.cpp.
{
    return f_->rttiType();
}
References f_, and Finfo::rttiType().
Referenced by Finfo::initCinfo(), and testFinfoFields().
Member Data Documentation
f_
const Finfo* FinfoWrapper::f_ private
Definition at line 174 of file Finfo.h.
Referenced by dest(), docs(), FinfoWrapper(), getName(), src(), and type().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/basecode/Finfo.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/basecode/Finfo.cpp