MOOSE - Multiscale Object Oriented Simulation Environment: MMenz Class Reference
MMenz Class Reference
#include <MMenz.h>
Public Member Functions
MMenz ()
void setSolver (const Eref &e, ObjId solver)
void vSetKcat (const Eref &e, double v)
void vSetKm (const Eref &e, double v)
virtual ~MMenz ()
Public Member Functions inherited from EnzBase
void enz (double n)
EnzBase ()
ObjId getCompartment (const Eref &e) const
double getKcat (const Eref &e) const
double getKm (const Eref &e) const
double getNumKm (const Eref &e) const
unsigned int getNumPrd (const Eref &e) const
unsigned int getNumSub (const Eref &e) const
void prd (double n)
void setKcat (const Eref &e, double v)
void setKm (const Eref &e, double v)
void setNumKm (const Eref &e, double v)
void sub (double n)
virtual ~EnzBase ()
Static Public Member Functions
static const Cinfo * initCinfo ()
Static Public Member Functions inherited from EnzBase
static const Cinfo * initCinfo ()
Private Attributes
Stoich * stoich_
Additional Inherited Members
Protected Attributes inherited from EnzBase
double kcat_
double Km_
Detailed Description
This class represents the Michaelis-Menten type enzyme, obeying the equation V = kcat.[Etot].[S]/(Km + [S])
Definition at line 18 of file MMenz.h.
Constructor & Destructor Documentation
MMenz()
MMenz::MMenz ()
Definition at line 83 of file MMenz.cpp.
    :
        stoich_( 0 )
{;}
References stoich_.
~MMenz()
MMenz::~MMenz () virtual
Definition at line 88 of file MMenz.cpp.
{;}
Member Function Documentation
initCinfo()
const Cinfo * MMenz::initCinfo () static
Definition at line 29 of file MMenz.cpp.
{
        // Field Definitions
        // MsgDest Definitions
        static DestFinfo setSolver( "setSolver",
            "Assigns solver to this MMEnz.",
            new EpFunc1< MMenz, ObjId >( &MMenz::setSolver ) );
        // Shared Msg Definitions
    static Finfo* mmEnzFinfos[] = {
        &setSolver,     // DestFinfo
    };
    static string doc[] = {
        "Name", "MMenz",
        "Author", "Upi Bhalla",
        "Description", "Class for MM (Michaelis-Menten) enzyme."
    };
    static Dinfo< MMenz > dinfo;
    static Cinfo MMenzCinfo (
        "MMenz",
        EnzBase::initCinfo(),
        mmEnzFinfos,
        sizeof( mmEnzFinfos ) / sizeof ( Finfo* ),
        &dinfo,
        doc,
        sizeof(doc)/sizeof(string)
    );
    return &MMenzCinfo;
}
References Cinfo::Cinfo(), DestFinfo::DestFinfo(), EpFunc1< T, A >::EpFunc1(), EnzBase::initCinfo(), and setSolver().
setSolver()
void MMenz::setSolver (const Eref & e, ObjId solver)
Now set up the RateTerm
Definition at line 113 of file MMenz.cpp.
{
    static const DestFinfo* enzFinfo = dynamic_cast< const DestFinfo* >(
        EnzBase::initCinfo()->findFinfo( "enzDest" ) );
    static const SrcFinfo* subFinfo = dynamic_cast< const SrcFinfo* >(
        EnzBase::initCinfo()->findFinfo( "subOut" ) );
    static const SrcFinfo* prdFinfo = dynamic_cast< const SrcFinfo* >(
        EnzBase::initCinfo()->findFinfo( "prdOut" ) );
    assert( enzFinfo );
    assert( subFinfo );
    assert( prdFinfo );
    if ( solver == ObjId() ) { // Clear solver
        if ( stoich_ )
            stoich_->notifyRemoveMMenz( e );
        stoich_ = 0;
        return;
    }
    assert( solver.element()->cinfo()->isA( "Stoich" ) );
    Stoich* stoichPtr = reinterpret_cast< Stoich* >( solver.data() );
    if ( stoich_ == stoichPtr )
        return;
    if (stoich_)
        stoich_->notifyRemoveMMenz( e );
    stoich_ = stoichPtr;
    vector< Id > enzvec;
    vector< Id > subvec;
    vector< Id > prdvec;
    unsigned int num = e.element()->getNeighbors( enzvec, enzFinfo );
    num = e.element()->getNeighbors( subvec, subFinfo );
    num = e.element()->getNeighbors( prdvec, prdFinfo );
    stoich_->installMMenz( e.id(), enzvec, subvec, prdvec );
    stoich_->setMMenzKm( e, Km_ );
    stoich_->setMMenzKcat( e, kcat_ );
}
References Element::cinfo(), ObjId::data(), Eref::element(), ObjId::element(), Cinfo::findFinfo(), Element::getNeighbors(), Eref::id(), EnzBase::initCinfo(), Stoich::installMMenz(), Cinfo::isA(), EnzBase::kcat_, EnzBase::Km_, Stoich::notifyRemoveMMenz(), ObjId::ObjId(), ObjId::operator==(), Stoich::setMMenzKcat(), Stoich::setMMenzKm(), and stoich_.
Referenced by initCinfo().
vSetKcat()
void MMenz::vSetKcat (const Eref & e, double v) virtual
Implements EnzBase.
Definition at line 102 of file MMenz.cpp.
{
    kcat_ = v;
    if ( stoich_ )
        stoich_->setMMenzKcat( e, v );
}
References EnzBase::kcat_, Stoich::setMMenzKcat(), and stoich_.
Referenced by testMMenz().
vSetKm()
void MMenz::vSetKm (const Eref & e, double v) virtual
Implements EnzBase.
Definition at line 95 of file MMenz.cpp.
{
    Km_ = v;
    if ( stoich_ )
        stoich_->setMMenzKm( e, v );
}
References EnzBase::Km_, Stoich::setMMenzKm(), and stoich_.
Referenced by testMMenz().
Member Data Documentation
stoich_
Stoich* MMenz::stoich_ private
Definition at line 39 of file MMenz.h.
Referenced by MMenz(), setSolver(), vSetKcat(), and vSetKm().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/kinetics/MMenz.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/kinetics/MMenz.cpp