MOOSE - Multiscale Object Oriented Simulation Environment: moose::AdThreshIF Class Reference
moose::AdThreshIF Class Reference
#include <AdThreshIF.h>
Public Member Functions
AdThreshIF ()
double getA0 (const Eref &e) const
double getTauThresh (const Eref &e) const
double getThreshAdaptive (const Eref &e) const
double getThreshJump (const Eref &e) const
void setA0 (const Eref &e, double val)
void setTauThresh (const Eref &e, double val)
void setThreshAdaptive (const Eref &e, double val)
void setThreshJump (const Eref &e, double val)
void vProcess (const Eref &e, ProcPtr p)
void vReinit (const Eref &e, ProcPtr p)
virtual ~AdThreshIF ()
Public Member Functions inherited from moose::IntFireBase
void activation (double val)
double getLastEventTime (const Eref &e) const
double getRefractoryPeriod (const Eref &e) const
double getThresh (const Eref &e) const
double getVReset (const Eref &e) const
bool hasFired (const Eref &e) const
IntFireBase ()
void setRefractoryPeriod (const Eref &e, double val)
void setThresh (const Eref &e, double val)
void setVReset (const Eref &e, double val)
virtual ~IntFireBase ()
Public Member Functions inherited from moose::Compartment
void cable ()
Compartment ()
virtual double vGetCm (const Eref &e) const
virtual double vGetEm (const Eref &e) const
virtual double vGetIm (const Eref &e) const
virtual double vGetInitVm (const Eref &e) const
virtual double vGetInject (const Eref &e) const
virtual double vGetRa (const Eref &e) const
virtual double vGetRm (const Eref &e) const
virtual double vGetVm (const Eref &e) const
void vHandleAxial (double Vm)
void vHandleChannel (const Eref &e, double Gk, double Ek)
void vHandleRaxial (double Ra, double Vm)
void vInitProc (const Eref &e, ProcPtr p)
void vInitReinit (const Eref &e, ProcPtr p)
void vInjectMsg (const Eref &e, double current)
void vRandInject (const Eref &e, double prob, double current)
virtual void vSetCm (const Eref &e, double Cm)
virtual void vSetEm (const Eref &e, double Em)
virtual void vSetInitVm (const Eref &e, double initVm)
virtual void vSetInject (const Eref &e, double Inject)
virtual void vSetRa (const Eref &e, double Ra)
virtual void vSetRm (const Eref &e, double Rm)
virtual void vSetVm (const Eref &e, double Vm)
virtual ~Compartment ()
Public Member Functions inherited from moose::CompartmentBase
void cable ()
CompartmentBase ()
void displace (double dx, double dy, double dz)
Displaces compartment by specified distance vector.
double getCm (const Eref &e) const
vector< double > getCoords () const
double getDiameter () const
double getEm (const Eref &e) const
double getIm (const Eref &e) const
double getInitVm (const Eref &e) const
double getInject (const Eref &e) const
double getLength () const
double getRa (const Eref &e) const
double getRm (const Eref &e) const
double getVm (const Eref &e) const
double getX () const
double getX0 () const
double getY () const
double getY0 () const
double getZ () const
double getZ0 () const
void handleAxial (double Vm)
void handleChannel (const Eref &e, double Gk, double Ek)
void handleRaxial (double Ra, double Vm)
void initProc (const Eref &e, ProcPtr p)
void initReinit (const Eref &e, ProcPtr p)
void injectMsg (const Eref &e, double current)
void process (const Eref &e, ProcPtr p)
void randInject (const Eref &e, double prob, double current)
bool rangeWarning (const string &field, double value)
void reinit (const Eref &e, ProcPtr p)
void setCm (const Eref &e, double Cm)
void setCoords (vector< double > value)
void setDiameter (double diameter)
void setEm (const Eref &e, double Em)
void setGeomAndElec (const Eref &e, double length, double dia)
Scales electrical values along with setting length, dia.
void setInitVm (const Eref &e, double initVm)
void setInject (const Eref &e, double Inject)
void setLength (double length)
void setRa (const Eref &e, double Ra)
void setRm (const Eref &e, double Rm)
void setVm (const Eref &e, double Vm)
void setX (double value)
void setX0 (double value)
void setY (double value)
void setY0 (double value)
void setZ (double value)
void setZ0 (double value)
void updateLength ()
virtual void vSetSolver (const Eref &e, Id hsolve)
virtual ~CompartmentBase ()
Static Public Member Functions
static const Cinfo * initCinfo ()
Static Public Member Functions inherited from moose::IntFireBase
static const Cinfo * initCinfo ()
static SrcFinfo1< double > * spikeOut ()
Message src for outgoing spikes.
Static Public Member Functions inherited from moose::Compartment
static const Cinfo * initCinfo ()
Static Public Member Functions inherited from moose::CompartmentBase
static const Cinfo * initCinfo ()
static SrcFinfo1< double > * VmOut ()
static void zombify (Element *orig, const Cinfo *zClass, Id hsolve)
Private Attributes
double a0_
double tauThresh_
double threshAdaptive_
double threshJump_
Additional Inherited Members
Protected Attributes inherited from moose::IntFireBase
double activation_
bool fired_
double lastEvent_
double refractT_
double threshold_
double vReset_
Protected Attributes inherited from moose::Compartment
double A_
double B_
double Cm_
double Em_
double Im_
double initVm_
double inject_
double lastIm_
double Ra_
double Rm_
double sumInject_
double Vm_
Detailed Description
The IntFire class sets up an integrate-and-fire compartment.
Definition at line 19 of file AdThreshIF.h.
Constructor & Destructor Documentation
AdThreshIF()
AdThreshIF::AdThreshIF ()
Definition at line 89 of file AdThreshIF.cpp.
{threshAdaptive_ = 0.0;
tauThresh_ = 1.0;
a0_ = 0.0;
threshJump_ = 0.0;}
References a0_, tauThresh_, threshAdaptive_, and threshJump_.
~AdThreshIF()
AdThreshIF::~AdThreshIF () virtual
Definition at line 95 of file AdThreshIF.cpp.
{;}
Member Function Documentation
getA0()
double AdThreshIF::getA0 (const Eref & e) const
Definition at line 168 of file AdThreshIF.cpp.
{
    return a0_;
}
References a0_.
Referenced by initCinfo().
getTauThresh()
double AdThreshIF::getTauThresh (const Eref & e) const
Definition at line 158 of file AdThreshIF.cpp.
{
    return tauThresh_;
}
References tauThresh_.
Referenced by initCinfo().
getThreshAdaptive()
double AdThreshIF::getThreshAdaptive (const Eref & e) const
Definition at line 148 of file AdThreshIF.cpp.
{
    return threshAdaptive_;
}
References threshAdaptive_.
Referenced by initCinfo().
getThreshJump()
double AdThreshIF::getThreshJump (const Eref & e) const
Definition at line 178 of file AdThreshIF.cpp.
{
    return threshJump_;
}
References threshJump_.
Referenced by initCinfo().
initCinfo()
const Cinfo * AdThreshIF::initCinfo () static
Initializes the class info.
Definition at line 19 of file AdThreshIF.cpp.
{
    static string doc[] =
    {
        "Name", "AdThreshIF",
        "Author", "Aditya Gilra",
        "Description", "Leaky Integrate-and-Fire neuron with adaptive threshold."
        "Based on Rossant, C., Goodman, D.F.M., Platkiewicz, J., and Brette, R. (2010)."
        "Rm*Cm * dVm/dt = -(Vm-Em) + Rm*I"
        "tauThresh * d threshAdaptive / dt = a0*(Vm-Em) - threshAdaptive "
        "at each spike, threshAdaptive is increased by threshJump "
        "the spiking threshold adapts as thresh + threshAdaptive "
    };
    static ElementValueFinfo< AdThreshIF, double > threshAdaptive(
        "threshAdaptive",
        "adaptative part of the threshold that decays with time constant tauThresh",
        &AdThreshIF::setThreshAdaptive,
        &AdThreshIF::getThreshAdaptive
    );
    static ElementValueFinfo< AdThreshIF, double > tauThresh(
        "tauThresh",
        "time constant of adaptative part of the threshold",
        &AdThreshIF::setTauThresh,
        &AdThreshIF::getTauThresh
    );
    static ElementValueFinfo< AdThreshIF, double > a0(
        "a0",
        "factor for voltage-dependent term in evolution of adaptative threshold: "
        "tauThresh * d threshAdaptive / dt = a0*(Vm-Em) - threshAdaptive ",
        &AdThreshIF::setA0,
        &AdThreshIF::getA0
    );
    static ElementValueFinfo< AdThreshIF, double > threshJump(
        "threshJump",
        "threshJump is added to threshAdaptive on each spike",
        &AdThreshIF::setThreshJump,
        &AdThreshIF::getThreshJump
    );
    static Finfo* AdThreshIFFinfos[] = {
        &threshAdaptive,// Value
        &tauThresh,     // Value
        &a0,            // Value
        &threshJump     // Value
    };
    static Dinfo< AdThreshIF > dinfo;
    static Cinfo AdThreshIFCinfo(
                "AdThreshIF",
                IntFireBase::initCinfo(),
                AdThreshIFFinfos,
                sizeof( AdThreshIFFinfos ) / sizeof (Finfo*),
                &dinfo,
                doc,
                sizeof(doc)/sizeof(string)
    );
    return &AdThreshIFCinfo;
}
References Cinfo::Cinfo(), ElementValueFinfo< T, F >::ElementValueFinfo(), getA0(), getTauThresh(), getThreshAdaptive(), getThreshJump(), moose::IntFireBase::initCinfo(), setA0(), setTauThresh(), setThreshAdaptive(), and setThreshJump().
setA0()
void AdThreshIF::setA0 (const Eref & e, double val)
Definition at line 163 of file AdThreshIF.cpp.
{
    a0_ = val;
}
References a0_.
Referenced by initCinfo().
setTauThresh()
void AdThreshIF::setTauThresh (const Eref & e, double val)
Definition at line 153 of file AdThreshIF.cpp.
{
    tauThresh_ = val;
}
References tauThresh_.
Referenced by initCinfo().
setThreshAdaptive()
void AdThreshIF::setThreshAdaptive (const Eref & e, double val)
Definition at line 143 of file AdThreshIF.cpp.
{
    threshAdaptive_ = val;
}
References threshAdaptive_.
Referenced by initCinfo().
setThreshJump()
void AdThreshIF::setThreshJump (const Eref & e, double val)
Definition at line 173 of file AdThreshIF.cpp.
{
    threshJump_ = val;
}
References threshJump_.
Referenced by initCinfo().
vProcess()
void AdThreshIF::vProcess (const Eref & e, ProcPtr p) virtual
The process function does the object updating and sends out messages to channels, nernsts, and so on.
Implements moose::IntFireBase.
Definition at line 102 of file AdThreshIF.cpp.
{
    fired_ = false;
    if ( p->currTime < lastEvent_ + refractT_ ) {
        Vm_ = vReset_;
        A_ = 0.0;
        B_ = 1.0 / Rm_;
        sumInject_ = 0.0;
        VmOut()->send( e, Vm_ );
    } else {
        // activation can be a continous variable (graded synapse).
        // So integrate it at every time step, thus *dt.
        // For a delta-fn synapse, SynHandler-s divide by dt and send activation.
        // See: http://www.genesis-sim.org/GENESIS/Hyperdoc/Manual-26.html#synchan
        //          for this continuous definition of activation.
        Vm_ += activation_ * p->dt;
        activation_ = 0.0;
        if ( Vm_ > (threshold_+threshAdaptive_) ) {
            Vm_ = vReset_;
            threshAdaptive_ += threshJump_;
            lastEvent_ = p->currTime;
            fired_ = true;
            spikeOut()->send( e, p->currTime );
            VmOut()->send( e, Vm_ );
        } else {
            threshAdaptive_ += (-threshAdaptive_ + a0_*(Vm_-Em_)) * p->dt/tauThresh_;
            Compartment::vProcess( e, p );  // this sends out Vm message also,
                                            // so do Vm_ calculations before
        }
    }
}
References a0_, moose::Compartment::A_, moose::IntFireBase::activation_, moose::Compartment::B_, ProcInfo::currTime, ProcInfo::dt, moose::Compartment::Em_, moose::IntFireBase::fired_, moose::IntFireBase::lastEvent_, moose::IntFireBase::refractT_, moose::Compartment::Rm_, SrcFinfo1< T >::send(), moose::IntFireBase::spikeOut(), moose::Compartment::sumInject_, tauThresh_, threshAdaptive_, threshJump_, moose::IntFireBase::threshold_, moose::Compartment::Vm_, moose::CompartmentBase::VmOut(), moose::Compartment::vProcess(), and moose::IntFireBase::vReset_.
vReinit()
void AdThreshIF::vReinit (const Eref & e, ProcPtr p) virtual
The reinit function reinitializes all fields.
Implements moose::IntFireBase.
Definition at line 134 of file AdThreshIF.cpp.
{
    activation_ = 0.0;
    threshAdaptive_ = 0.0;
    fired_ = false;
    lastEvent_ = -refractT_; // Allow it to fire right away.
    Compartment::vReinit( e, p );
}
References moose::IntFireBase::activation_, moose::IntFireBase::fired_, moose::IntFireBase::lastEvent_, moose::IntFireBase::refractT_, threshAdaptive_, and moose::Compartment::vReinit().
Member Data Documentation
a0_
double moose::AdThreshIF::a0_ private
Definition at line 53 of file AdThreshIF.h.
Referenced by AdThreshIF(), getA0(), setA0(), and vProcess().
tauThresh_
double moose::AdThreshIF::tauThresh_ private
Definition at line 52 of file AdThreshIF.h.
Referenced by AdThreshIF(), getTauThresh(), setTauThresh(), and vProcess().
threshAdaptive_
double moose::AdThreshIF::threshAdaptive_ private
Definition at line 51 of file AdThreshIF.h.
Referenced by AdThreshIF(), getThreshAdaptive(), setThreshAdaptive(), vProcess(), and vReinit().
threshJump_
double moose::AdThreshIF::threshJump_ private
Definition at line 54 of file AdThreshIF.h.
Referenced by AdThreshIF(), getThreshJump(), setThreshJump(), and vProcess().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/intfire/AdThreshIF.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/intfire/AdThreshIF.cpp