MOOSE - Multiscale Object Oriented Simulation Environment: Cell Class Reference
Cell Class Reference
#include <Cell.h>
Classes
struct MethodInfo
Public Member Functions
Cell ()
string getDescription () const
int getImplicit () const
string getMethod () const
Id getSetup () const
unsigned int getSolverClock () const
string getSolverName () const
int getVariableDt () const
void processDummy (const Eref &e, ProcPtr p)
void reinit (const Eref &e, ProcPtr p)
void setMethod (string value)
void setSolverClock (unsigned int value)
void setSolverName (string value)
void setupf (Id cell)
Static Public Member Functions
static void addMethod (const string &name, const string &description, int isVariableDt, int isImplicit)
static const Cinfo * initCinfo ()
Private Member Functions
void setupSolver (Id cell, Id seed) const
Static Private Member Functions
static vector< Id > children (Id obj)
static Id findCompt (Id cell)
Private Attributes
string method_
Shell * shell_
unsigned int solverClock_
string solverName_
Static Private Attributes
static map< string, MethodInfo > methodMap_
Detailed Description
Definition at line 13 of file Cell.h.
Constructor & Destructor Documentation
Cell()
Cell::Cell ()
Definition at line 118 of file Cell.cpp.
    : solverClock_(2),
      solverName_("_integ"),
      shell_(reinterpret_cast<Shell*>(Id().eref().data()))
{
    setMethod("hsolve");
}
References Eref::data(), Id::eref(), Id::Id(), setMethod(), shell_, solverClock_, and solverName_.
Member Function Documentation
addMethod()
void Cell::addMethod (const string & name, const string & description, int isVariableDt, int isImplicit) static
Definition at line 126 of file Cell.cpp.
{
    methodMap_[name] = MethodInfo(description, isVariableDt, isImplicit);
}
References Cell::MethodInfo::MethodInfo(), and methodMap_.
Referenced by initCinfo().
children()
vector< Id > Cell::children (Id obj) static private
Definition at line 192 of file Cell.cpp.
{
    //~ return Field< vector< Id > >::get( obj, "children" );
    //~ return Field< vector< Id > >::fastGet( obj.eref(), "children" );
    //~ return localGet< Neutral, vector< Id > >( obj.eref(), "children" );
    vector<Id> c;
    Neutral::children(obj.eref(), c);
    return c;
}
References Neutral::children(), and Id::eref().
Referenced by findCompt().
findCompt()
Id Cell::findCompt (Id cell) static private
This function performs a depth-first search of the tree under the current cell. First compartment found is returned as the seed.
Definition at line 207 of file Cell.cpp.
{
    /* 'curr' is the current element under consideration. 'cstack' is a list
     * of all elements (and their immediate siblings) found on the path from
     * the root element (the Cell) to the current element.
     */
    vector<vector<Id>> cstack;
    Id seed;
    const Cinfo* compartmentCinfo = Cinfo::find("Compartment");
    cstack.push_back(children(cell));
    while(!cstack.empty()) {
        const vector<Id>& child = cstack.back();
        if(child.empty()) {
            cstack.pop_back();
            if(!cstack.empty())
                cstack.back().pop_back();
        } else {
            moose::showWarn("TODO: Commented out code. ");
            Id curr = child.back();
#if 0  /* ----- #if 0 : If0Label_1 ----- */
            //~ string className = Field< string >::get( curr, "class" );
            if ( curr()->cinfo() == compartmentCinfo )
            {
                seed = curr;
                break;
            }
#endif /* ----- #if 0 : If0Label_1 ----- */
            cstack.push_back(children(curr));
        }
    }
    return seed;
}
References children(), Cinfo::find(), and moose::showWarn().
Referenced by reinit(), and setupf().
getDescription()
string Cell::getDescription () const
Definition at line 313 of file Cell.cpp.
{
    return methodMap_[method_].description;
}
References Cell::MethodInfo::description, method_, and methodMap_.
Referenced by initCinfo().
getImplicit()
int Cell::getImplicit () const
Definition at line 308 of file Cell.cpp.
{
    return methodMap_[method_].isImplicit;
}
References Cell::MethodInfo::isImplicit, method_, and methodMap_.
Referenced by initCinfo().
getMethod()
string Cell::getMethod () const
Definition at line 278 of file Cell.cpp.
{
    return method_;
}
References method_.
Referenced by initCinfo().
getSetup()
Id Cell::getSetup () const
Definition at line 165 of file Cell.cpp.
{
    return Id();
}
References Id::Id().
Referenced by initCinfo().
getSolverClock()
unsigned int Cell::getSolverClock () const
Definition at line 288 of file Cell.cpp.
{
    return solverClock_;
}
References solverClock_.
Referenced by initCinfo().
getSolverName()
string Cell::getSolverName () const
Definition at line 298 of file Cell.cpp.
{
    return solverName_;
}
References solverName_.
Referenced by initCinfo().
getVariableDt()
int Cell::getVariableDt () const
Definition at line 303 of file Cell.cpp.
{
    return methodMap_[method_].isVariableDt;
}
References Cell::MethodInfo::isVariableDt, method_, and methodMap_.
Referenced by initCinfo().
initCinfo()
const Cinfo * Cell::initCinfo () static
Definition at line 23 of file Cell.cpp.
{
    static DestFinfo process("process",
                             "Cell does not process at simulation time--"
                             "it only sets up the solver at reset.",
                             new ProcOpFunc<Cell>(&Cell::processDummy));
    static DestFinfo reinit(
        "reinit", "Handles 'reinit' call: This triggers setting up the solver.",
        new ProcOpFunc<Cell>(&Cell::reinit)
        //~ new EpFunc0< Cell >( &Cell::reinit )
        );
    static Finfo* processShared[] = {&process, &reinit};
    static SharedFinfo proc(
        "proc",
        "This shared message exists only to receive a 'reinit' call, which is "
        "taken as a trigger to create and set up HSolve.",
        processShared, sizeof(processShared) / sizeof(Finfo*));
    static DestFinfo setup1("setup1", "Setup.",
                            new OpFunc1<Cell, Id>(&Cell::setupf));
    static ValueFinfo<Cell, Id> setup2("setupv", "Setupv.", &Cell::setupf,
                                       &Cell::getSetup);
    static ValueFinfo<Cell, string> method(
        "method",
        "Specifies the integration method to be used for the neuron managed "
        "by this Cell object.",
        &Cell::setMethod, &Cell::getMethod);
    static ValueFinfo<Cell, unsigned int> solverClock(
        "solverClock",
        "Specifies which clock to use for the HSolve, if it is used.",
        &Cell::setSolverClock, &Cell::getSolverClock);
    static ValueFinfo<Cell, string> solverName(
        "solverName", "Specifies name for the solver object.",
        &Cell::setSolverName, &Cell::getSolverName);
    static ReadOnlyValueFinfo<Cell, int> variableDt(
        "variableDt",
        "Read-only field which tells if the current method is a variable "
        "time-step method.",
        &Cell::getVariableDt);
    static ReadOnlyValueFinfo<Cell, int> implicit(
        "implicit",
        "Read-only field which tells if the current method is an implicit "
        "method.",
        &Cell::getImplicit);
    static ReadOnlyValueFinfo<Cell, string> description(
        "description",
        "Read-only field giving a short description of the currently selected "
        "integration method.",
        &Cell::getDescription);
    static Finfo* cellFinfos[] = {&method,                    // Value
                                  &solverClock,               // Value
                                  &solverName,                // Value
                                  &setup2,      &variableDt,  // ReadOnlyValue
                                  &implicit,                  // ReadOnlyValue
                                  &description,               // ReadOnlyValue
                                  &setup1,      &proc,        // Shared
    };
    static string doc[] = {"Name", "Cell", "Author", "Niraj Dudani, 2012, NCBS",
                           "Description",
                           "Container for a neuron's components. "
                           "Also manages automatic solver setup. "
                           "In case of solver setup, assumes that all the "
                           "compartments under this Cell belong to a single "
                           "neuron. If more than 1 group of axially "
                           "connected compartments are present, then only "
                           "one of them will be taken over by the solver.", };
    static Cinfo cellCinfo("Cell", Neutral::initCinfo(), cellFinfos,
                           sizeof(cellFinfos) / sizeof(Finfo*),
                           new Dinfo<Cell>());
    Cell::addMethod("ee", "Exponential Euler.", 0, 0);
    Cell::addMethod("hsolve", "Hines' algorithm.", 0, 1);
    return &cellCinfo;
}
References addMethod(), Cinfo::Cinfo(), DestFinfo::DestFinfo(), Dinfo< D >::Dinfo(), getDescription(), getImplicit(), getMethod(), getSetup(), getSolverClock(), getSolverName(), getVariableDt(), Neutral::initCinfo(), OpFunc1< T, A >::OpFunc1(), processDummy(), ProcOpFunc< T >::ProcOpFunc(), ReadOnlyValueFinfo< T, F >::ReadOnlyValueFinfo(), reinit(), setMethod(), setSolverClock(), setSolverName(), setupf(), SharedFinfo::SharedFinfo(), and ValueFinfo< T, F >::ValueFinfo().
processDummy()
void Cell::processDummy (const Eref & e, ProcPtr p)
Definition at line 136 of file Cell.cpp.
{
    ;
}
Referenced by initCinfo().
reinit()
void Cell::reinit (const Eref & e, ProcPtr p)
Definition at line 141 of file Cell.cpp.
{
    cout << ".. Cell::reinit()" << endl;
    //~ if ( q->protectedAddToStructuralQ() )
    //~ return;
    // Delete existing solver
    //~ string solverPath = cell.id().path() + "/" + solverName_;
    //~ Id solver( solverPath );
    //~ if ( solver.path() == solverPath )
    //~ solver.destroy();
    if(method_ == "ee")
        return;
    // Find any compartment that is a descendant of this cell
    Id seed = findCompt(cell.id());
    if(seed == Id())  // No compartment found.
        return;
    setupSolver(cell.id(), seed);
}
References findCompt(), Id::Id(), Eref::id(), method_, Id::operator==(), and setupSolver().
Referenced by initCinfo().
setMethod()
void Cell::setMethod (string value)
Definition at line 264 of file Cell.cpp.
{
    map<string, MethodInfo>::iterator i = methodMap_.find(value);
    if(i != methodMap_.end()) {
        method_ = value;
    } else {
        method_ = "hsolve";
        cerr << "Warning: Cell::setMethod(): method '" << value
             << "' not known. Using '" << method_ << "'.\n";
        setMethod(method_);
    }
}
References method_, methodMap_, and setMethod().
Referenced by Cell(), initCinfo(), and setMethod().
setSolverClock()
void Cell::setSolverClock (unsigned int value)
Definition at line 283 of file Cell.cpp.
{
    solverClock_ = value;
}
References solverClock_.
Referenced by initCinfo().
setSolverName()
void Cell::setSolverName (string value)
Definition at line 293 of file Cell.cpp.
{
    solverName_ = value;
}
References solverName_.
Referenced by initCinfo().
setupf()
void Cell::setupf (Id cell)
Definition at line 169 of file Cell.cpp.
{
    cout << "Cell::setup()" << endl;
    cout << ".... cell path: " << cell.path() << endl;
    //~ return;
    // Delete existing solver
    string solverPath = cell.path() + "/" + solverName_;
    Id solver(solverPath);
    if(solver.path() == solverPath)
        solver.destroy();
    if(method_ == "ee")
        return;
    // Find any compartment that is a descendant of this cell
    Id seed = findCompt(cell);
    if(seed == Id())  // No compartment found.
        return;
    setupSolver(cell, seed);
}
References Id::destroy(), findCompt(), Id::Id(), Id::Id(), method_, Id::operator==(), Id::path(), setupSolver(), and solverName_.
Referenced by initCinfo().
setupSolver()
void Cell::setupSolver (Id cell, Id seed) const private
Definition at line 247 of file Cell.cpp.
{
    Id solver = Id::nextId();
    moose::showWarn(
        "FIXME: Using 0 for parentMsgIndex in function call Shell::innerCreate"
        "0 in first and third argument to NodeBalance. "
        "I am not sure if I should be doing this here in this function.");
    NodeBalance nb(0, MooseBlockBalance, 0);
    shell_->innerCreate("HSolve", cell, solver, solverName_, nb, 0);
    HSolve* data = reinterpret_cast<HSolve*>(solver.eref().data());
    data->setSeed(seed);
}
References Eref::data(), Id::eref(), Shell::innerCreate(), MooseBlockBalance, Id::nextId(), NodeBalance::NodeBalance(), HSolve::setSeed(), shell_, moose::showWarn(), and solverName_.
Referenced by reinit(), and setupf().
Member Data Documentation
method_
string Cell::method_ private
Definition at line 71 of file Cell.h.
Referenced by getDescription(), getImplicit(), getMethod(), getVariableDt(), reinit(), setMethod(), and setupf().
methodMap_
map< string, Cell::MethodInfo > Cell::methodMap_ static private
Definition at line 79 of file Cell.h.
Referenced by addMethod(), getDescription(), getImplicit(), getVariableDt(), and setMethod().
shell_
Shell* Cell::shell_ private
Definition at line 74 of file Cell.h.
Referenced by Cell(), and setupSolver().
solverClock_
unsigned int Cell::solverClock_ private
Definition at line 72 of file Cell.h.
Referenced by Cell(), getSolverClock(), and setSolverClock().
solverName_
string Cell::solverName_ private
Definition at line 73 of file Cell.h.
Referenced by Cell(), getSolverName(), setSolverName(), setupf(), and setupSolver().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/hsolve/Cell.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/hsolve/Cell.cpp