MOOSE - Multiscale Object Oriented Simulation Environment: MarkovChannel Class Reference
MarkovChannel Class Reference
#include <MarkovChannel.h>
Public Member Functions
vector< double > getGbars () const
vector< double > getInitialState () const
double getLigandConc () const
vector< vector< bool > > getLigandGated () const
unsigned int getNumOpenStates () const
unsigned int getNumStates () const
vector< double > getState () const
vector< string > getStateLabels () const
double getVm () const
void handleLigandConc (double)
void handleState (vector< double >)
MarkovChannel ()
MarkovChannel (unsigned int, unsigned int)
void setGbars (vector< double >)
void setInitialState (vector< double >)
void setLigandConc (double)
void setLigandGated (vector< vector< bool > >)
void setNumOpenStates (unsigned int)
void setNumStates (unsigned int)
void setState (vector< double >)
void setStateLabels (vector< string >)
void setVm (double)
void vProcess (const Eref &, const ProcPtr)
void vReinit (const Eref &, const ProcPtr)
~MarkovChannel ()
Public Member Functions inherited from ChanCommon
ChanCommon ()
double getGbar () const
Utility function to acces Gbar.
double getVm () const
Utility function to access Vm.
void sendProcessMsgs (const Eref &e, const ProcPtr info)
void sendReinitMsgs (const Eref &e, const ProcPtr info)
void updateIk ()
double vGetEk (const Eref &e) const override
double vGetGbar (const Eref &e) const override
double vGetGk (const Eref &e) const override
double vGetIk (const Eref &e) const override
double vGetModulation (const Eref &e) const override
void vHandleVm (double Vm) override
void vSetEk (const Eref &e, double Ek) override
void vSetGbar (const Eref &e, double Gbar) override
void vSetGk (const Eref &e, double Gk) override
void vSetIk (const Eref &e, double Ic) override
void vSetModulation (const Eref &e, double modulation) override
virtual ~ChanCommon ()=0
Public Member Functions inherited from ChanBase
ChanBase ()
double getEk (const Eref &e) const
double getGbar (const Eref &e) const
double getGk (const Eref &e) const
double getIk (const Eref &e) const
double getModulation (const Eref &e) const
void handleVm (double Vm)
void process (const Eref &e, const ProcPtr info)
void reinit (const Eref &e, const ProcPtr info)
void setEk (const Eref &e, double Ek)
void setGbar (const Eref &e, double Gbar)
void setGk (const Eref &e, double Gk)
void setIk (const Eref &e, double Ic)
void setModulation (const Eref &e, double modulation)
virtual ~ChanBase ()=0
Static Public Member Functions
static const Cinfo * initCinfo ()
Static Public Member Functions inherited from ChanCommon
static const Cinfo * initCinfo ()
Specify the Class Info static variable for initialization.
Static Public Member Functions inherited from ChanBase
static SrcFinfo2< double, double > * channelOut ()
static SrcFinfo1< double > * IkOut ()
static const Cinfo * initCinfo ()
Specify the Class Info static variable for initialization.
static SrcFinfo1< double > * permeability ()
Private Attributes
double g_
vector< double > Gbars_
vector< double > initialState_
double ligandConc_
unsigned int numOpenStates_
unsigned int numStates_
vector< double > state_
vector< string > stateLabels_
Additional Inherited Members
Protected Member Functions inherited from ChanCommon
double getModulation () const
Protected Attributes inherited from ChanCommon
double Vm_
Vm_ is input variable from compartment, used for most rates.
Detailed Description
Definition at line 15 of file MarkovChannel.h.
Constructor & Destructor Documentation
MarkovChannel() [1/2]
MarkovChannel::MarkovChannel ()
Definition at line 130 of file MarkovChannel.cpp.
                             :
    g_(0),
    ligandConc_(0),
    numStates_(0),
    numOpenStates_(0)
{ ; }
References g_, ligandConc_, numOpenStates_, and numStates_.
MarkovChannel() [2/2]
MarkovChannel::MarkovChannel (unsigned int numStates, unsigned int numOpenStates)
Definition at line 137 of file MarkovChannel.cpp.
                                                                               :
    g_(0), ligandConc_(0), numStates_(numStates), numOpenStates_(numOpenStates)
{
    stateLabels_.resize( numStates );
    state_.resize( numStates );
    initialState_.resize( numStates );
    Gbars_.resize( numOpenStates ) ;
}
References g_, Gbars_, initialState_, ligandConc_, numOpenStates_, numStates_, state_, and stateLabels_.
~MarkovChannel()
MarkovChannel::~MarkovChannel ()
Definition at line 146 of file MarkovChannel.cpp.
{
    ;
}
Member Function Documentation
getGbars()
vector< double > MarkovChannel::getGbars () const
Definition at line 217 of file MarkovChannel.cpp.
{
    return Gbars_;
}
References Gbars_.
Referenced by initCinfo().
getInitialState()
vector< double > MarkovChannel::getInitialState () const
Definition at line 206 of file MarkovChannel.cpp.
{
    return initialState_;
}
References initialState_.
Referenced by initCinfo().
getLigandConc()
double MarkovChannel::getLigandConc () const
Definition at line 161 of file MarkovChannel.cpp.
{
    return ligandConc_;
}
References ligandConc_.
Referenced by initCinfo().
getLigandGated()
vector< vector< bool > > MarkovChannel::getLigandGated () const
getNumOpenStates()
unsigned int MarkovChannel::getNumOpenStates () const
Definition at line 181 of file MarkovChannel.cpp.
{
    return numOpenStates_;
}
References numOpenStates_.
Referenced by initCinfo().
getNumStates()
unsigned int MarkovChannel::getNumStates () const
Definition at line 171 of file MarkovChannel.cpp.
{
    return numStates_;
}
References numStates_.
Referenced by initCinfo().
getState()
vector< double > MarkovChannel::getState () const
Definition at line 201 of file MarkovChannel.cpp.
{
    return state_;
}
References state_.
Referenced by initCinfo().
getStateLabels()
vector< string > MarkovChannel::getStateLabels () const
Definition at line 191 of file MarkovChannel.cpp.
{
    return stateLabels_;
}
References stateLabels_.
Referenced by initCinfo().
getVm()
double MarkovChannel::getVm () const
Definition at line 151 of file MarkovChannel.cpp.
{
    return Vm_;
}
References ChanCommon::Vm_.
Referenced by initCinfo().
handleLigandConc()
void MarkovChannel::handleLigandConc (double ligandConc)
Definition at line 262 of file MarkovChannel.cpp.
{
    ligandConc_ = ligandConc;
}
References ligandConc_.
Referenced by initCinfo().
handleState()
void MarkovChannel::handleState (vector< double > state)
Definition at line 267 of file MarkovChannel.cpp.
{
    state_ = state;
}
References state_.
Referenced by initCinfo().
initCinfo()
const Cinfo * MarkovChannel::initCinfo () static
Definition at line 22 of file MarkovChannel.cpp.
{
    //Field information.
    static ValueFinfo< MarkovChannel, double > ligandconc( "ligandConc",
            "Ligand concentration.",
            &MarkovChannel::setLigandConc,
            &MarkovChannel::getLigandConc
                                                         );
    static ValueFinfo< MarkovChannel, double > vm( "Vm",
            "Membrane voltage.",
            &MarkovChannel::setVm,
            &MarkovChannel::getVm
                                                 );
    static ValueFinfo< MarkovChannel, unsigned int > numstates( "numStates",
            "The number of states that the channel can occupy.",
            &MarkovChannel::setNumStates,
            &MarkovChannel::getNumStates
                                                              );
    static ValueFinfo< MarkovChannel, unsigned int > numopenstates( "numOpenStates",
            "The number of states which are open/conducting.",
            &MarkovChannel::setNumOpenStates,
            &MarkovChannel::getNumOpenStates
                                                                  );
    static ValueFinfo< MarkovChannel, vector< string > > labels("labels",
            "Labels for each state.",
            &MarkovChannel::setStateLabels,
            &MarkovChannel::getStateLabels
                                                               );
    static ReadOnlyValueFinfo< MarkovChannel, vector< double > > state( "state",
            "This is a row vector that contains the probabilities of finding the channel in each state.",
            &MarkovChannel::getState
                                                                      );
    static ValueFinfo< MarkovChannel, vector< double > > initialstate( "initialState",
            "This is a row vector that contains the probabilities of finding the channel in each state at t = 0. The state of the channel is reset to this value during a call to reinit()",
            &MarkovChannel::setInitialState,
            &MarkovChannel::getInitialState
                                                                     );
    static ValueFinfo< MarkovChannel, vector< double > > gbar( "gbar",
            "A row vector containing the conductance associated with each of the open/conducting states.",
            &MarkovChannel::setGbars,
            &MarkovChannel::getGbars
                                                             );
    //MsgDest functions
    static DestFinfo handleligandconc( "handleLigandConc",
            "Deals with incoming messages containing information of ligand concentration",
            new OpFunc1< MarkovChannel, double >(&MarkovChannel::handleLigandConc) );
    static DestFinfo handlestate("handleState",
            "Deals with incoming message from MarkovSolver object containing state information of the channel.\n",
            new OpFunc1< MarkovChannel, vector< double > >(&MarkovChannel::handleState) );
    static Finfo* MarkovChannelFinfos[] =
    {
        &ligandconc,
        &vm,
        &numstates,
        &numopenstates,
        &state,
        &initialstate,
        &labels,
        &gbar,
        &handleligandconc,
        &handlestate,
    };
    static string doc[] =
    {
        "Name", "MarkovChannel",
        "Author", "Vishaka Datta S, 2011, NCBS Bangalore",
        "Description", "MarkovChannel.\n"
        "It deals with ion channels which can be found in one of multiple states, "
        "some of which are conducting. This implementation assumes the occurence "
        "of first order kinetics to calculate the probabilities of the channel "
        "being found in all states. Further, the rates of transition between these "
        "states can be constant, voltage-dependent or ligand dependent (only one "
        "ligand species). The current flow obtained from the channel is calculated "
        "in a deterministic method by solving the system of differential equations "
        "obtained from the assumptions above."
    };
    static Dinfo< MarkovChannel > dinfo;
    static Cinfo MarkovChannelCinfo(
        "MarkovChannel",
        ChanBase::initCinfo(),
        MarkovChannelFinfos,
        sizeof( MarkovChannelFinfos )/ sizeof( Finfo* ),
        &dinfo,
        doc,
        sizeof(doc) / sizeof(string)
    );
    return &MarkovChannelCinfo;
}
References Cinfo::Cinfo(), DestFinfo::DestFinfo(), getGbars(), getInitialState(), getLigandConc(), getNumOpenStates(), getNumStates(), getState(), getStateLabels(), getVm(), handleLigandConc(), handleState(), ChanBase::initCinfo(), OpFunc1< T, A >::OpFunc1(), ReadOnlyValueFinfo< T, F >::ReadOnlyValueFinfo(), setGbars(), setInitialState(), setLigandConc(), setNumOpenStates(), setNumStates(), setStateLabels(), setVm(), and ValueFinfo< T, F >::ValueFinfo().
setGbars()
void MarkovChannel::setGbars (vector< double > Gbars)
Definition at line 222 of file MarkovChannel.cpp.
{
    Gbars_ = Gbars;
}
References Gbars_.
Referenced by initCinfo().
setInitialState()
void MarkovChannel::setInitialState (vector< double > initialState)
Definition at line 211 of file MarkovChannel.cpp.
{
    initialState_ = initialState;
    state_ = initialState;
}
References initialState_, and state_.
Referenced by initCinfo().
setLigandConc()
void MarkovChannel::setLigandConc (double ligandConc)
Definition at line 166 of file MarkovChannel.cpp.
{
    ligandConc_ = ligandConc;
}
References ligandConc_.
Referenced by initCinfo().
setLigandGated()
void MarkovChannel::setLigandGated (vector< vector< bool > >)
setNumOpenStates()
void MarkovChannel::setNumOpenStates (unsigned int numOpenStates)
Definition at line 186 of file MarkovChannel.cpp.
{
    numOpenStates_ = numOpenStates;
}
References numOpenStates_.
Referenced by initCinfo().
setNumStates()
void MarkovChannel::setNumStates (unsigned int numStates)
Definition at line 176 of file MarkovChannel.cpp.
{
    numStates_ = numStates;
}
References numStates_.
Referenced by initCinfo().
setState()
void MarkovChannel::setState (vector< double >)
setStateLabels()
void MarkovChannel::setStateLabels (vector< string >)
Definition at line 196 of file MarkovChannel.cpp.
{
    stateLabels_ = stateLabels;
}
References stateLabels_.
Referenced by initCinfo().
setVm()
void MarkovChannel::setVm (double Vm)
Definition at line 156 of file MarkovChannel.cpp.
{
    Vm_ = Vm;
}
References ChanCommon::Vm_.
Referenced by initCinfo().
vProcess()
void MarkovChannel::vProcess (const Eref & e, const ProcPtr p) virtual
Implements ChanBase.
Definition at line 231 of file MarkovChannel.cpp.
{
    g_ = 0.0;
    //Cannot use the Gbar_ variable of the ChanBase class. The conductance
    //Gk_ calculated here is the "expected conductance" of the channel due to its
    //stochastic nature.
    for( unsigned int i = 0; i < numOpenStates_; ++i )
        g_ += Gbars_[i] * state_[i];
    setGk( e, g_ );
    updateIk();
    sendProcessMsgs( e, p );
}
References g_, Gbars_, numOpenStates_, ChanCommon::sendProcessMsgs(), ChanBase::setGk(), state_, and ChanCommon::updateIk().
vReinit()
void MarkovChannel::vReinit (const Eref & e, const ProcPtr p) virtual
Implements ChanBase.
Definition at line 248 of file MarkovChannel.cpp.
{
    g_ = 0.0;
    if ( initialState_.empty() )
    {
        cerr << "MarkovChannel::reinit : Initial state has not been set.!\n";
        return;
    }
    state_ = initialState_;
    sendReinitMsgs( e, p );
}
References g_, initialState_, ChanCommon::sendReinitMsgs(), and state_.
Member Data Documentation
g_
double MarkovChannel::g_ private
Definition at line 73 of file MarkovChannel.h.
Referenced by MarkovChannel(), MarkovChannel(), vProcess(), and vReinit().
Gbars_
vector< double > MarkovChannel::Gbars_ private
Definition at line 81 of file MarkovChannel.h.
Referenced by getGbars(), MarkovChannel(), setGbars(), and vProcess().
initialState_
vector< double > MarkovChannel::initialState_ private
Definition at line 80 of file MarkovChannel.h.
Referenced by getInitialState(), MarkovChannel(), setInitialState(), and vReinit().
ligandConc_
double MarkovChannel::ligandConc_ private
Definition at line 74 of file MarkovChannel.h.
Referenced by getLigandConc(), handleLigandConc(), MarkovChannel(), MarkovChannel(), and setLigandConc().
numOpenStates_
unsigned int MarkovChannel::numOpenStates_ private
Definition at line 76 of file MarkovChannel.h.
Referenced by getNumOpenStates(), MarkovChannel(), MarkovChannel(), setNumOpenStates(), and vProcess().
numStates_
unsigned int MarkovChannel::numStates_ private
Definition at line 75 of file MarkovChannel.h.
Referenced by getNumStates(), MarkovChannel(), MarkovChannel(), and setNumStates().
state_
vector< double > MarkovChannel::state_ private
Definition at line 79 of file MarkovChannel.h.
Referenced by getState(), handleState(), MarkovChannel(), setInitialState(), vProcess(), and vReinit().
stateLabels_
vector< string > MarkovChannel::stateLabels_ private
Definition at line 78 of file MarkovChannel.h.
Referenced by getStateLabels(), MarkovChannel(), and setStateLabels().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/biophysics/MarkovChannel.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/biophysics/MarkovChannel.cpp