MOOSE - Multiscale Object Oriented Simulation Environment: DiffPoolVec Class Reference
DiffPoolVec Class Reference
#include <DiffPoolVec.h>
Public Member Functions
void advance (double dt)
DiffPoolVec ()
double getConcInit (unsigned int vox) const
double getDiffConst () const
unsigned int getId () const
double getMotorConst () const
double getN (unsigned int vox) const
unsigned int getNumVoxels () const
const vector< double > & getNvec () const
Used by parent solver to manipulate 'n'.
double getPrev (unsigned int vox) const
void process ()
void reinit (const vector< double > &vols)
void setConcInit (unsigned int vox, double value)
void setDiffConst (double value)
void setId (unsigned int id)
void setMotorConst (double value)
void setN (unsigned int vox, double value)
void setNumVoxels (unsigned int num)
void setNvec (const vector< double > &n)
Used by parent solver to manipulate 'n'.
void setNvec (unsigned int start, unsigned int num, vector< double >::const_iterator q)
void setOps (const vector< Triplet< double > > &ops_, const vector< double > &diagVal_)
Assigns prev_ = n_.
void setPrevVec ()
Private Attributes
vector< double > concInit_
vector< double > diagVal_
double diffConst_
Boundary condition: Initial 'n'.
unsigned int id_
Assign operations.
double motorConst_
Diffusion const, assumed uniform.
vector< double > n_
Integer conversion of Id of pool handled.
vector< Triplet< double > > ops_
Motor const, ie, transport rate.
vector< double > prev_
Number of molecules of pool in each voxel.
Detailed Description
This is a FieldElement of the Dsolve class. It manages (ie., zombifies) a specific pool, and the pool maintains a pointer to it. For accessing volumes, this maintains a pointer to the relevant ChemCompt.
Definition at line 18 of file DiffPoolVec.h.
Constructor & Destructor Documentation
DiffPoolVec()
DiffPoolVec::DiffPoolVec ()
Default is to create it with a single compartment, independent of any solver, so that we can set it up as a dummy DiffPool for the Pool to work on in single-compartment models.
Definition at line 25 of file DiffPoolVec.cpp.
    : id_( 0 ), n_( 1, 0.0 ), concInit_( 1, 0.0 ),
      diffConst_( 1.0e-12 ), motorConst_( 0.0 )
{
    ;
}
References concInit_, diffConst_, id_, motorConst_, and n_.
Member Function Documentation
advance()
void DiffPoolVec::advance (double dt)
Definition at line 144 of file DiffPoolVec.cpp.
{
    if ( ops_.size() == 0 ) return;
    for (auto i = ops_.cbegin(); i != ops_.end(); ++i )
        n_[i->c_] -= n_[i->b_] * i->a_;
    assert( n_.size() == diagVal_.size() );
    auto iy = n_.begin();
    for ( auto i = diagVal_.cbegin(); i != diagVal_.end(); ++i )
        *iy++ *= *i;
}
References diagVal_, n_, and ops_.
Referenced by Dsolve::process().
getConcInit()
double DiffPoolVec::getConcInit (unsigned int vox) const
Definition at line 32 of file DiffPoolVec.cpp.
{
    assert( voxel < concInit_.size() );
    return concInit_[ voxel ];
}
References concInit_.
Referenced by Dsolve::getConcInit().
getDiffConst()
double DiffPoolVec::getDiffConst () const
Definition at line 87 of file DiffPoolVec.cpp.
{
    return diffConst_;
}
References diffConst_.
Referenced by Dsolve::build(), Dsolve::calcJnDiff(), and Dsolve::getDiffConst().
getId()
unsigned int DiffPoolVec::getId () const
Definition at line 123 of file DiffPoolVec.cpp.
{
    return id_;
}
References id_.
Referenced by Dsolve::mapDiffPoolsBetweenDsolves(), and Dsolve::mapXfersBetweenDsolves().
getMotorConst()
double DiffPoolVec::getMotorConst () const
Definition at line 97 of file DiffPoolVec.cpp.
{
    return motorConst_;
}
References motorConst_.
Referenced by Dsolve::build().
getN()
double DiffPoolVec::getN (unsigned int vox) const
Definition at line 44 of file DiffPoolVec.cpp.
{
    assert( voxel < n_.size() );
    return n_[ voxel ];
}
References n_.
Referenced by Dsolve::calcJnChan(), Dsolve::calcJnDiff(), Dsolve::calcJnXfer(), Dsolve::calcLocalChan(), Dsolve::calcOtherJnChan(), and Dsolve::getN().
getNumVoxels()
unsigned int DiffPoolVec::getNumVoxels () const
Definition at line 113 of file DiffPoolVec.cpp.
{
    return n_.size();
}
References n_.
Referenced by Dsolve::calcLocalChan(), and Dsolve::setNvec().
getNvec()
const vector< double > & DiffPoolVec::getNvec () const
Used by parent solver to manipulate 'n'.
Definition at line 62 of file DiffPoolVec.cpp.
{
    return n_;
}
References n_.
Referenced by Dsolve::getBlock(), and Dsolve::getNvec().
getPrev()
double DiffPoolVec::getPrev (unsigned int vox) const
Definition at line 56 of file DiffPoolVec.cpp.
{
    assert( voxel < n_.size() );
    return prev_[ voxel ];
}
References n_, and prev_.
Referenced by Dsolve::calcJnXfer().
process()
void DiffPoolVec::process ()
reinit()
void DiffPoolVec::reinit (const vector< double > & vols)
Definition at line 158 of file DiffPoolVec.cpp.
{
    const double NA_ = 6.0221415e23;
    assert( n_.size() == concInit_.size() );
    // vector< double > vols( concInit_.size(), 1.0 );
    vector< double > nInit( concInit_.size(), 0.0 );
    for ( size_t i = 0; i < concInit_.size(); ++i )
        nInit[i] = concInit_[i] * NA_ * vols[i];
    prev_ = n_ = nInit;
}
References concInit_, n_, and prev_.
Referenced by Dsolve::reinit().
setConcInit()
void DiffPoolVec::setConcInit (unsigned int vox, double value)
Definition at line 38 of file DiffPoolVec.cpp.
{
    assert( voxel < concInit_.size() );
    concInit_[ voxel ] = v;
}
References concInit_.
Referenced by Dsolve::setConcInit().
setDiffConst()
void DiffPoolVec::setDiffConst (double value)
Definition at line 92 of file DiffPoolVec.cpp.
{
    diffConst_ = v;
}
References diffConst_.
Referenced by Dsolve::setDiffConst(), Dsolve::setPath(), and Dsolve::setStoich().
setId()
void DiffPoolVec::setId (unsigned int id)
Definition at line 118 of file DiffPoolVec.cpp.
{
    id_ = id;
}
References id_.
Referenced by Dsolve::setPath(), and Dsolve::setStoich().
setMotorConst()
void DiffPoolVec::setMotorConst (double value)
Definition at line 102 of file DiffPoolVec.cpp.
{
    motorConst_ = v;
}
References motorConst_.
Referenced by Dsolve::setMotorConst(), Dsolve::setPath(), and Dsolve::setStoich().
setN()
void DiffPoolVec::setN (unsigned int vox, double value)
Definition at line 50 of file DiffPoolVec.cpp.
{
    assert( voxel < n_.size() );
    n_[ voxel ] = v;
}
References n_.
Referenced by Dsolve::calcJnChan(), Dsolve::calcJnDiff(), Dsolve::calcJnXfer(), Dsolve::calcLocalChan(), Dsolve::calcOtherJnChan(), and Dsolve::setN().
setNumVoxels()
void DiffPoolVec::setNumVoxels (unsigned int num)
Definition at line 107 of file DiffPoolVec.cpp.
{
    concInit_.resize( num, 0.0 );
    n_.resize( num, 0.0 );
}
References concInit_, and n_.
Referenced by Dsolve::build(), Dsolve::setNumAllVoxels(), Dsolve::setNumPools(), and Dsolve::setNumVarTotPools().
setNvec() [1/2]
void DiffPoolVec::setNvec (const vector< double > & n)
Used by parent solver to manipulate 'n'.
Definition at line 67 of file DiffPoolVec.cpp.
{
    assert( vec.size() == n_.size() );
    n_ = vec;
}
References n_.
Referenced by Dsolve::setNvec().
setNvec() [2/2]
void DiffPoolVec::setNvec (unsigned int start, unsigned int num, vector< double >::const_iterator q)
Definition at line 73 of file DiffPoolVec.cpp.
{
    assert( start + num <= n_.size() );
    vector< double >::iterator p = n_.begin() + start;
    for ( unsigned int i = 0; i < num; ++i )
        *p++ = *q++;
}
References n_.
Referenced by Dsolve::setBlock().
setOps()
void DiffPoolVec::setOps (const vector< Triplet< double > > & ops_, const vector< double > & diagVal_)
Assigns prev_ = n_.
Definition at line 128 of file DiffPoolVec.cpp.
{
    if ( ops.size() > 0 )
    {
        assert( diagVal.size() == n_.size() );
        ops_ = ops;
        diagVal_ = diagVal;
    }
    else
    {
        ops_.clear();
        diagVal_.clear();
    }
}
References diagVal_, n_, and ops_.
Referenced by Dsolve::build().
setPrevVec()
void DiffPoolVec::setPrevVec ()
Definition at line 82 of file DiffPoolVec.cpp.
{
    prev_ = n_;
}
References n_, and prev_.
Referenced by Dsolve::setPrev().
Member Data Documentation
concInit_
vector< double > DiffPoolVec::concInit_ private
molecules of pool on previous timestep
Definition at line 59 of file DiffPoolVec.h.
Referenced by DiffPoolVec(), getConcInit(), reinit(), setConcInit(), and setNumVoxels().
diagVal_
vector< double > DiffPoolVec::diagVal_ private
Definition at line 63 of file DiffPoolVec.h.
Referenced by advance(), and setOps().
diffConst_
double DiffPoolVec::diffConst_ private
Boundary condition: Initial 'n'.
Definition at line 60 of file DiffPoolVec.h.
Referenced by DiffPoolVec(), getDiffConst(), and setDiffConst().
id_
unsigned int DiffPoolVec::id_ private
Assign operations.
Definition at line 56 of file DiffPoolVec.h.
Referenced by DiffPoolVec(), getId(), and setId().
motorConst_
double DiffPoolVec::motorConst_ private
Diffusion const, assumed uniform.
Definition at line 61 of file DiffPoolVec.h.
Referenced by DiffPoolVec(), getMotorConst(), and setMotorConst().
n_
vector< double > DiffPoolVec::n_ private
Integer conversion of Id of pool handled.
Definition at line 57 of file DiffPoolVec.h.
Referenced by advance(), DiffPoolVec(), getN(), getNumVoxels(), getNvec(), getPrev(), reinit(), setN(), setNumVoxels(), setNvec(), setNvec(), setOps(), and setPrevVec().
ops_
vector< Triplet< double > > DiffPoolVec::ops_ private
Motor const, ie, transport rate.
Definition at line 62 of file DiffPoolVec.h.
Referenced by advance(), and setOps().
prev_
vector< double > DiffPoolVec::prev_ private
Number of molecules of pool in each voxel.
Definition at line 58 of file DiffPoolVec.h.
Referenced by getPrev(), reinit(), and setPrevVec().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/diffusion/DiffPoolVec.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/diffusion/DiffPoolVec.cpp