MOOSE - Multiscale Object Oriented Simulation Environment: OneToAllMsg Class Reference
OneToAllMsg Class Reference
#include <OneToAllMsg.h>
Public Member Functions
Msg * copy (Id origSrc, Id newSrc, Id newTgt, FuncId fid, unsigned int b, unsigned int n) const
ObjId findOtherEnd (ObjId end) const
Eref firstTgt (const Eref &src) const
DataId getI1 () const
Return the first DataId.
Id managerId () const
OneToAllMsg (Eref e1, Element *e2, unsigned int msgIndex)
void setI1 (DataId i1)
void sources (vector< vector< Eref > > &v) const
void targets (vector< vector< Eref > > &v) const
~OneToAllMsg ()
Public Member Functions inherited from Msg
Element * e1 () const
Element * e2 () const
ObjId getAdjacent (ObjId) const
vector< string > getDestFieldsOnE1 () const
vector< string > getDestFieldsOnE2 () const
Id getE1 () const
Id getE2 () const
vector< string > getSrcFieldsOnE1 () const
vector< string > getSrcFieldsOnE2 () const
bool isForward (const Element *src) const
ObjId mid () const
Msg (ObjId mid, Element *e1, Element *e2)
Constructor.
virtual ~Msg ()
Destructor.
Static Public Member Functions
static const Cinfo * initCinfo ()
Setup function for Element-style access to Msg fields.
static char * lookupMsg (unsigned int index)
Static function for Msg access.
static unsigned int numMsg ()
Assign the first DataId.
Static Public Member Functions inherited from Msg
static void clearAllMsgs ()
static void deleteMsg (ObjId mid)
static const Msg * getMsg (ObjId m)
static const Cinfo * initCinfo ()
static unsigned int initMsgManagers ()
static bool isLastTrump ()
True when MOOSE has been terminated and is being cleaned up.
static const Msg * lastMsg ()
Private Attributes
DataId i1_
Static Private Attributes
static Id managerId_
static vector< OneToAllMsg * > msg_
Friends
unsigned int Msg::initMsgManagers ()
void testGetMsgs ()
Additional Inherited Members
Protected Attributes inherited from Msg
Element * e1_
Index of this Msg on the msg_ vector.
Element * e2_
Element 1 attached to Msg.
ObjId mid_
Static Protected Attributes inherited from Msg
static bool lastTrump_ = false
Flag to indicate termination of program.
static Id msgManagerId_
Element 2 attached to Msg.
Detailed Description
Manages projection from a single entry in e1 to all array entries in e2.
Definition at line 18 of file OneToAllMsg.h.
Constructor & Destructor Documentation
OneToAllMsg()
OneToAllMsg::OneToAllMsg (Eref e1, Element * e2, unsigned int msgIndex)
Definition at line 17 of file OneToAllMsg.cpp.
    :
        Msg(
            ObjId( managerId_, (msgIndex != 0) ? msgIndex: msg_.size() ),
            e1.element(), e2
           ),
        i1_( e1.dataIndex() )
{
    if ( msgIndex == 0 ) {
        msg_.push_back( this );
    } else {
        if ( msg_.size() <= msgIndex )
            msg_.resize( msgIndex + 1 );
        msg_[ msgIndex ] = this;
    }
}
References Eref::dataIndex(), Eref::element(), i1_, managerId_, Msg::Msg(), msg_, and ObjId::ObjId().
Referenced by addClockMsg(), Shell::adopt(), copy(), Shell::innerAddMsg(), Shell::innerMove(), and testFibonacci().
~OneToAllMsg()
OneToAllMsg::~OneToAllMsg ()
Definition at line 34 of file OneToAllMsg.cpp.
{
    assert( mid_.dataIndex < msg_.size() );
    msg_[ mid_.dataIndex ] = 0; // ensure deleted ptr isn't reused.
}
References ObjId::dataIndex, Msg::mid_, and msg_.
Member Function Documentation
copy()
Msg * OneToAllMsg::copy (Id origSrc, Id newSrc, Id newTgt, FuncId fid, unsigned int b, unsigned int n) const virtual
Make a copy of this Msg. The original msg was on origSrc. The new Msg should go from newSrc to newTgt, and have the function fid, on bindIndex b. The copy may have to be a higher-order Msg type to handle arrays if n > 1. Note that n is not the number of msgs, but the multiplier by which numData will be scaled.
Implements Msg.
Definition at line 81 of file OneToAllMsg.cpp.
{
    const Element* orig = origSrc.element();
    if ( n <= 1 ) {
        OneToAllMsg* ret = 0;
        if ( orig == e1() ) {
            ret = new OneToAllMsg(
                    Eref( newSrc.element(), i1_ ), newTgt.element(), 0 );
            ret->e1()->addMsgAndFunc( ret->mid(), fid, b );
        } else if ( orig == e2() ) {
            ret = new OneToAllMsg(
                    Eref( newTgt.element(), i1_ ), newSrc.element(), 0 );
            ret->e2()->addMsgAndFunc( ret->mid(), fid, b );
        } else {
            assert( 0 );
        }
        return ret;
    } else {
        // Here we need a SliceMsg which goes from one 2-d array to another.
        cout << "Error: OneToAllMsg::copy: SliceToSliceMsg not yet implemented\n";
        return 0;
    }
}
References Element::addMsgAndFunc(), Msg::e1(), Msg::e2(), Id::element(), Eref::Eref(), i1_, Msg::mid(), and OneToAllMsg().
findOtherEnd()
ObjId OneToAllMsg::findOtherEnd (ObjId) const virtual
Find the other end of this Msg. In most cases this is a straightforward return of e1 or e2, plus perhaps a DataId. But in some complex msgs we need to figure out DataIds that match with the target. In many-to-one cases we just return the first entry. If no Element match, return ObjId(Id(), DataId::bad()) If Element e matches but not DataId, return ObjId(e.id(), DataId::bad())
Implements Msg.
Definition at line 69 of file OneToAllMsg.cpp.
{
    if ( f.element() == e1() ) {
        if ( f.dataIndex == i1_ )
            return ObjId( e2()->id(), 0 );
    } else if ( f.element() == e2() ) {
        return ObjId( e1()->id(), i1_ );
    }
    return ObjId( 0, BADINDEX );
}
References BADINDEX, ObjId::dataIndex, Msg::e1(), Msg::e2(), ObjId::element(), i1_, Element::id(), and ObjId::ObjId().
firstTgt()
Eref OneToAllMsg::firstTgt (const Eref & src) const virtual
Obtain the first target Eref for the specified Src Eref It is really meant only to work with messages with a single target ObjId for each given src, typically OneToOne.
Implements Msg.
Definition at line 40 of file OneToAllMsg.cpp.
{
    if ( src.element() == e1_ )
        return Eref( e2_, 0 );
    else if ( src.element() == e2_ )
        return Eref( e1_, i1_ );
    return Eref( 0, 0 );
}
References Msg::e1_, Msg::e2_, Eref::element(), Eref::Eref(), and i1_.
getI1()
DataId OneToAllMsg::getI1 () const
Return the first DataId.
Return the first DataId
Definition at line 143 of file OneToAllMsg.cpp.
{
    return i1_;
}
References i1_.
Referenced by initCinfo().
initCinfo()
const Cinfo * OneToAllMsg::initCinfo () static
Setup function for Element-style access to Msg fields.
Definition at line 110 of file OneToAllMsg.cpp.
{
    // Field definitions.
    static ValueFinfo< OneToAllMsg, DataId > i1(
        "i1",
        "DataId of source Element.",
        &OneToAllMsg::setI1,
        &OneToAllMsg::getI1
    );
    static Finfo* msgFinfos[] = {
        &i1,        // value
    };
    static Dinfo< short > dinfo;
    static Cinfo msgCinfo (
        "OneToAllMsg",  // name
        Msg::initCinfo(),               // base class
        msgFinfos,
        sizeof( msgFinfos ) / sizeof( Finfo* ), // num Fields
        &dinfo
    );
    return &msgCinfo;
}
References Cinfo::Cinfo(), getI1(), Msg::initCinfo(), setI1(), and ValueFinfo< T, F >::ValueFinfo().
Referenced by Msg::initMsgManagers().
lookupMsg()
char * OneToAllMsg::lookupMsg (unsigned int index) static
Static function for Msg access.
Definition at line 162 of file OneToAllMsg.cpp.
{
    assert( index < msg_.size() );
    return reinterpret_cast< char* >( msg_[index] );
}
References msg_.
Referenced by Msg::clearAllMsgs(), and Msg::initMsgManagers().
managerId()
Id OneToAllMsg::managerId () const
Definition at line 64 of file OneToAllMsg.cpp.
{
    return OneToAllMsg::managerId_;
}
References managerId_.
numMsg()
unsigned int OneToAllMsg::numMsg () static
Assign the first DataId.
Static function for Msg access.
Msg lookup functions
Definition at line 156 of file OneToAllMsg.cpp.
{
    return msg_.size();
}
References msg_.
Referenced by Msg::clearAllMsgs(), Shell::doCreate(), Shell::doUseClock(), and Msg::initMsgManagers().
setI1()
void OneToAllMsg::setI1 (DataId i1)
Definition at line 148 of file OneToAllMsg.cpp.
{
    i1_ = i1;
    e1()->markRewired();
    e2()->markRewired();
}
References Msg::e1(), Msg::e2(), i1_, and Element::markRewired().
Referenced by initCinfo().
sources()
void OneToAllMsg::sources (vector< vector< Eref > > & v) const virtual
Return all the sources of e2 from e1, that is, all the msgs coming into specified entries on e2 from e1.
ALLDATA used when the sources include all data entries on a source. Indexing is v[dataId in range e2.numData][src list]
Implements Msg.
Definition at line 49 of file OneToAllMsg.cpp.
{
    // Same single source for all targets.
    v.clear();
    vector< Eref > temp( 1, Eref( e1_, i1_ ) );
    v.assign( e2_->numData(), temp  );
}
References Msg::e1_, Msg::e2_, Eref::Eref(), i1_, and Element::numData().
targets()
void OneToAllMsg::targets (vector< vector< Eref > > & v) const virtual
Return all the targets of e1 on e2, that is, all the msgs going from specified entries on e1 to e2. ALLDATA used when the targets include all data entries on a target. Indexing is v[dataId in range e1.numData][tgt list]
Implements Msg.
Definition at line 57 of file OneToAllMsg.cpp.
{
    v.clear();
    v.resize( e1_->numData() );
    v[i1_].resize( 1, Eref( e2_, ALLDATA ) );
}
References ALLDATA, Msg::e1_, Msg::e2_, Eref::Eref(), i1_, and Element::numData().
Friends And Related Symbol Documentation
Msg::initMsgManagers
unsigned int Msg::initMsgManagers () friend
testGetMsgs
void testGetMsgs () friend
Tests message inspection fields on Neutral. These include msgOut: all outgoing Msgs, reported as ObjId of their managers msgIn: all incoming Msgs, reported as ObjId of their managers msgSrc: All source Ids of messages coming into specified field msgDest: All dest Ids of messages going out of specified field
Definition at line 1518 of file testShell.cpp.
{
    Eref sheller = Id().eref();
    Shell* shell = reinterpret_cast<Shell*>(sheller.data());
    unsigned int numData = 5;
    // Set up the objects.
    Id a1 = shell->doCreate("Arith", Id(), "a1", numData);
    Id a2 = shell->doCreate("Arith", Id(), "a2", numData);
    Id b1 = shell->doCreate("Arith", Id(), "b1", numData);
    Id b2 = shell->doCreate("Arith", Id(), "b2", numData);
    Id c1 = shell->doCreate("Arith", Id(), "c1", numData);
    Id c2 = shell->doCreate("Arith", Id(), "c2", numData);
    Id d1 = shell->doCreate("Arith", Id(), "d1", numData);
    Id d2 = shell->doCreate("Arith", Id(), "d2", numData);
    Id e1 = shell->doCreate("Arith", Id(), "e1", numData);
    Id e2 = shell->doCreate("Arith", Id(), "e2", numData);
    // Set up messaging
    // Should give 04000
    ObjId m1 =
        shell->doAddMsg("Single", ObjId(a1, 3), "output", ObjId(a2, 1), "arg3");
    assert(m1 != ObjId());
    // Should give 33333
    ObjId m2 = shell->doAddMsg("OneToAll", ObjId(a1, 2), "output", ObjId(b2, 0),
                               "arg3");
    assert(m2 != ObjId());
    // Should give 12345
    ObjId m3 = shell->doAddMsg("OneToOne", ObjId(a1, 0), "output", ObjId(c2, 0),
                               "arg3");
    assert(m3 != ObjId());
    // Should give 01234
    ObjId m4 = shell->doAddMsg("Diagonal", ObjId(a1, 0), "output", ObjId(d2, 0),
                               "arg3");
    assert(m4 != ObjId());
    // Should give 54321
    ObjId m5 =
        shell->doAddMsg("Sparse", ObjId(a1, 0), "output", ObjId(e2, 0), "arg3");
    assert(m5 != ObjId());
    // Check that the outgoing Msgs are OK.
    // Nov 2013: Wait till the Msg ObjIds are set up.
    /*
    vector< ObjId > msgMgrs =
            Field< vector< ObjId > >::get( a1, "msgOut" );
    assert( msgMgrs.size() == 5 ); // 5 above.
    for ( unsigned int i = 0; i < 5; ++i )
            assert( Field< Id >::get( msgMgrs[i], "e1" ) == a1 );
    assert( Field< string >::get( msgMgrs[0], "className" ) == "SingleMsg" );
    assert( Field< string >::get( msgMgrs[1], "className" ) == "OneToAllMsg" );
    assert( Field< string >::get( msgMgrs[2], "className" ) == "OneToOneMsg" );
    assert( Field< string >::get( msgMgrs[3], "className" ) == "DiagonalMsg" );
    assert( Field< string >::get( msgMgrs[4], "className" ) == "SparseMsg" );
    assert( Field< Id >::get( msgMgrs[0], "e2" ) == a2 );
    assert( Field< Id >::get( msgMgrs[1], "e2" ) == b2 );
    assert( Field< Id >::get( msgMgrs[2], "e2" ) == c2 );
    assert( Field< Id >::get( msgMgrs[3], "e2" ) == d2 );
    assert( Field< Id >::get( msgMgrs[4], "e2" ) == e2 );
    cout << "." << flush;
    // Check that the incoming Msgs are OK.
    msgMgrs = Field< vector< ObjId > >::get( a1, "msgIn" );
    assert( msgMgrs.size() == 1 ); // parent msg
    assert( msgMgrs[0].id == OneToAllMsg::managerId_ );
    assert( Field< Id >::get( msgMgrs[0], "e1" ) == Id() );
    assert( Field< Id >::get( msgMgrs[0], "e2" ) == a1 );
    msgMgrs = Field< vector< ObjId > >::get( a2, "msgIn" );
    assert( msgMgrs.size() == 2 ); // parent msg + input msg
    assert( Field< Id >::get( msgMgrs[0], "e1" ) == Id() );
    assert( Field< Id >::get( msgMgrs[0], "e2" ) == a2 );
    assert( Field< Id >::get( msgMgrs[1], "e1" ) == a1 );
    assert( Field< Id >::get( msgMgrs[1], "e2" ) == a2 );
    msgMgrs = Field< vector< ObjId > >::get( b2, "msgIn" );
    assert( msgMgrs.size() == 2 ); // parent msg + input msg
    assert( Field< Id >::get( msgMgrs[0], "e1" ) == Id() );
    assert( Field< Id >::get( msgMgrs[0], "e2" ) == b2 );
    assert( Field< Id >::get( msgMgrs[1], "e1" ) == a1 );
    assert( Field< Id >::get( msgMgrs[1], "e2" ) == b2 );
    msgMgrs = Field< vector< ObjId > >::get( c2, "msgIn" );
    assert( msgMgrs.size() == 2 ); // parent msg + input msg
    assert( Field< Id >::get( msgMgrs[0], "e1" ) == Id() );
    assert( Field< Id >::get( msgMgrs[0], "e2" ) == c2 );
    assert( Field< Id >::get( msgMgrs[1], "e1" ) == a1 );
    assert( Field< Id >::get( msgMgrs[1], "e2" ) == c2 );
    msgMgrs = Field< vector< ObjId > >::get( d2, "msgIn" );
    assert( msgMgrs.size() == 2 ); // parent msg + input msg
    assert( Field< Id >::get( msgMgrs[0], "e1" ) == Id() );
    assert( Field< Id >::get( msgMgrs[0], "e2" ) == d2 );
    assert( Field< Id >::get( msgMgrs[1], "e1" ) == a1 );
    assert( Field< Id >::get( msgMgrs[1], "e2" ) == d2 );
    msgMgrs = Field< vector< ObjId > >::get( e2, "msgIn" );
    assert( msgMgrs.size() == 2 ); // parent msg + input msg
    assert( Field< Id >::get( msgMgrs[0], "e1" ) == Id() );
    assert( Field< Id >::get( msgMgrs[0], "e2" ) == e2 );
    assert( Field< Id >::get( msgMgrs[1], "e1" ) == a1 );
    assert( Field< Id >::get( msgMgrs[1], "e2" ) == e2 );
    cout << "." << flush;
    */
    // Check that the MsgSrcs are OK.
    vector<Id> srcIds;
    srcIds = LookupField<string, vector<Id>>::get(a2, "neighbors", "arg3");
    assert(srcIds.size() == 1);
    assert(srcIds[0] == a1);
    srcIds.resize(0);
    srcIds = LookupField<string, vector<Id>>::get(b2, "neighbors", "arg3");
    assert(srcIds.size() == 1);
    assert(srcIds[0] == a1);
    srcIds.resize(0);
    srcIds = LookupField<string, vector<Id>>::get(c2, "neighbors", "arg3");
    assert(srcIds.size() == 1);
    assert(srcIds[0] == a1);
    ObjId m6 =
        shell->doAddMsg("Single", ObjId(b1, 3), "output", ObjId(b2, 1), "arg3");
    assert(m6 != ObjId());
    srcIds.resize(0);
    srcIds = LookupField<string, vector<Id>>::get(b2, "neighbors", "arg3");
    assert(srcIds.size() == 2);
    assert(srcIds[0] == a1);
    assert(srcIds[1] == b1);
    cout << "." << flush;
    // Check that the MsgDests are OK.
    vector<Id> destIds;
    destIds = LookupField<string, vector<Id>>::get(a1, "neighbors", "output");
    assert(destIds.size() == 5);
    assert(destIds[0] == a2);
    assert(destIds[1] == b2);
    assert(destIds[2] == c2);
    assert(destIds[3] == d2);
    assert(destIds[4] == e2);
    destIds.resize(0);
    destIds = LookupField<string, vector<Id>>::get(b1, "neighbors", "output");
    assert(destIds.size() == 1);
    assert(destIds[0] == b2);
    cout << "." << flush;
    // Clean up.
    shell->doDelete(a1);
    shell->doDelete(a2);
    shell->doDelete(b1);
    shell->doDelete(b2);
    shell->doDelete(c1);
    shell->doDelete(c2);
    shell->doDelete(d1);
    shell->doDelete(d2);
    shell->doDelete(e1);
    shell->doDelete(e2);
}
Referenced by testShell().
Member Data Documentation
i1_
DataId OneToAllMsg::i1_ private
Definition at line 49 of file OneToAllMsg.h.
Referenced by copy(), findOtherEnd(), firstTgt(), getI1(), OneToAllMsg(), setI1(), sources(), and targets().
managerId_
Id OneToAllMsg::managerId_ static private
Definition at line 50 of file OneToAllMsg.h.
Referenced by Msg::initMsgManagers(), managerId(), and OneToAllMsg().
msg_
vector< OneToAllMsg * > OneToAllMsg::msg_ static private
Definition at line 51 of file OneToAllMsg.h.
Referenced by lookupMsg(), numMsg(), OneToAllMsg(), and ~OneToAllMsg().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/msg/OneToAllMsg.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/msg/OneToAllMsg.cpp