MOOSE - Multiscale Object Oriented Simulation Environment: Streamer Class Reference
Streamer Class Reference
#include <Streamer.h>
Public Member Functions
void addTable (ObjId table)
Add a table to streamer.
void addTables (vector< ObjId > tables)
Add multiple tables to Streamer.
void cleanUp (void)
This function is called from Shell when simulation is called to write the left-over data to streamer file.
string getDatafilePath (void) const
string getFormat (void) const
unsigned int getNumTables (void) const
Get the number of tables handled by Streamer.
unsigned int getNumWriteEvents (void) const
Streamer & operator= (const Streamer &st)
void process (const Eref &e, ProcPtr p)
This function is called at its clock tick.
void reinit (const Eref &e, ProcPtr p)
Reinit.
void removeTable (ObjId table)
Remove a table from Streamer.
void removeTables (vector< ObjId > table)
Remove multiple tables – if found – from Streamer.
void setDatafilePath (string path)
void setFormat (string format)
Streamer ()
void zipWithTime ()
This function prepares data to be written to a file.
~Streamer ()
Public Member Functions inherited from StreamerBase
string getOutFilepath () const
StreamerBase & operator= (const StreamerBase &st)
void setOutFilepath (string stream)
StreamerBase ()
string vectorToCSV (const vector< double > &ys, const string &fmt)
~StreamerBase ()
Public Member Functions inherited from TableBase
void clearVec ()
void compareVec (vector< double > other, string op)
void compareXplot (string fname, string plotname, string op)
const vector< double > & data ()
double getOutputValue () const
string getPlotDump () const
unsigned int getVecSize () const
vector< double > getVector () const
double getY (unsigned int index) const
double interpolate (double x, double xmin, double xmax) const
void linearTransform (double scale, double offset)
void loadCSV (string fname, int startLine, int colNum, char separator)
void loadXplot (string fname, string plotname)
void loadXplotRange (string fname, string plotname, unsigned int start, unsigned int end)
double * lookupVec (unsigned int index)
void plainPlot (string file)
void setOutputValue (double val)
void setPlotDump (string v)
void setVecSize (unsigned int num)
void setVector (vector< double > val)
TableBase ()
void xplot (string file, string plotname)
Static Public Member Functions
static const Cinfo * initCinfo ()
Static Public Member Functions inherited from StreamerBase
static void writeToCSVFile (const string &filepath, const OpenMode openMode, const vector< double > &data, const vector< string > &columns)
Write data to csv file. See the documentation of writeToOutfile for details.
static void writeToNPYFile (const string &filepath, const OpenMode openmode, const vector< double > &data, const vector< string > &columns)
Write to NPY format. See the documentation of writeToOutfile for more details.
static void writeToOutFile (const string &filepath, const string &format, const OpenMode openmode, const vector< double > &data, const vector< string > &columns)
Write to a output file in given format.
Static Public Member Functions inherited from TableBase
static const Cinfo * initCinfo ()
Private Attributes
vector< string > columns_
double currTime_
vector< double > data_
string datafilePath_
string format_
bool isOutfilePathSet_
unsigned int numWriteEvents_
vector< double > tableDt_
vector< ObjId > tableIds_
vector< Table * > tables_
vector< unsigned int > tableTick_
Additional Inherited Members
Protected Member Functions inherited from TableBase
vector< double > & vec ()
Detailed Description
Definition at line 33 of file Streamer.h.
Constructor & Destructor Documentation
Streamer()
Streamer::Streamer ()
Definition at line 144 of file Streamer.cpp.
{
    // Not all compilers allow initialization during the declaration of class
    // methods.
    format_ = "csv";
    numWriteEvents_ = 0;
    columns_.push_back("time");               /* First column is time. */
    tables_.resize(0);
    tableIds_.resize(0);
    tableTick_.resize(0);
    tableDt_.resize(0);
    data_.resize(0);
}
References columns_, data_, format_, numWriteEvents_, tableDt_, tableIds_, tables_, and tableTick_.
~Streamer()
Streamer::~Streamer ()
Definition at line 164 of file Streamer.cpp.
{
}
Member Function Documentation
addTable()
void Streamer::addTable (ObjId table)
Add a table to streamer.
Parameters
table Id of table.
Definition at line 283 of file Streamer.cpp.
{
    // If this table is not already in the vector, add it.
    for( unsigned int i = 0; i < tableIds_.size(); i++)
        if( table.path() == tableIds_[i].path() )
            return;                             /* Already added. */
    Table* t = reinterpret_cast<Table*>(table.eref().data());
    tableIds_.push_back( table );
    tables_.push_back( t );
    tableTick_.push_back( table.element()->getTick() );
    // NOTE: Table can also have name. If name is set by User, use the name to
    // for column name, else use modify the table path to generate a suitable
    // column name.
    if(t->getColumnName().size() > 0)
        columns_.push_back(t->getColumnName());
    else
        columns_.push_back(moose::moosePathToColumnName(table.path()));
}
References columns_, Eref::data(), ObjId::element(), ObjId::eref(), Table::getColumnName(), Element::getTick(), moose::moosePathToColumnName(), ObjId::path(), tableIds_, tables_, and tableTick_.
Referenced by addTables(), and initCinfo().
addTables()
void Streamer::addTables (vector< ObjId > tables)
Add multiple tables to Streamer.
Parameters
tables
Definition at line 309 of file Streamer.cpp.
{
    if( tables.size() == 0 )
        return;
    for(auto it = tables.begin(); it != tables.end(); it++)
        addTable( *it );
}
References addTable().
Referenced by initCinfo().
cleanUp()
void Streamer::cleanUp (void)
This function is called from Shell when simulation is called to write the left-over data to streamer file.
Definition at line 255 of file Streamer.cpp.
{
    zipWithTime( );
    StreamerBase::writeToOutFile( datafilePath_, format_, APPEND, data_, columns_ );
    data_.clear( );
}
References APPEND, columns_, data_, datafilePath_, format_, StreamerBase::writeToOutFile(), and zipWithTime().
Referenced by Shell::doStart().
getDatafilePath()
string Streamer::getDatafilePath (void) const
Definition at line 376 of file Streamer.cpp.
{
    return datafilePath_;
}
References datafilePath_.
Referenced by initCinfo().
getFormat()
string Streamer::getFormat (void) const
Definition at line 402 of file Streamer.cpp.
{
    return format_;
}
References format_.
Referenced by initCinfo().
getNumTables()
unsigned int Streamer::getNumTables (void) const
Get the number of tables handled by Streamer.
Returns
Number of tables.
Definition at line 357 of file Streamer.cpp.
{
    return tables_.size();
}
References tables_.
Referenced by initCinfo().
getNumWriteEvents()
unsigned int Streamer::getNumWriteEvents (void) const
@Synopsis Get number of write events in streamer. Useful for debugging and performance measuerments.
@Returns
Definition at line 370 of file Streamer.cpp.
{
    return numWriteEvents_;
}
References numWriteEvents_.
Referenced by initCinfo().
initCinfo()
const Cinfo * Streamer::initCinfo () static
Definition at line 19 of file Streamer.cpp.
{
    /*-----------------------------------------------------------------------------
     * Finfos
     *-----------------------------------------------------------------------------*/
    static ValueFinfo< Streamer, string > datafile(
        "datafile"
        , "File/stream to write table data to. Default is is __moose_tables__.dat.n"
        " By default, this object writes data every second \n"
        , &Streamer::setDatafilePath
        , &Streamer::getDatafilePath
    );
    static ValueFinfo< Streamer, string > outfile(
        "outfile"
        , "Use datafile (deprecated)"
        , &Streamer::setDatafilePath
        , &Streamer::getDatafilePath
    );
    static ValueFinfo< Streamer, string > format(
        "format"
        , "Format of output file, default is csv"
        , &Streamer::setFormat
        , &Streamer::getFormat
    );
    static ReadOnlyValueFinfo<Streamer, unsigned int> numTables (
        "numTables"
        , "Number of Tables handled by Streamer "
        , &Streamer::getNumTables
    );
    static ReadOnlyValueFinfo<Streamer, unsigned int> numWriteEvents(
        "numWriteEvents"
        , "Number of time streamer was called to write. (For debugging/performance reason only)"
        , &Streamer::getNumWriteEvents
    );
    /*-----------------------------------------------------------------------------
     *
     *-----------------------------------------------------------------------------*/
    static DestFinfo process(
        "process"
        , "Handle process call"
        , new ProcOpFunc< Streamer >( &Streamer::process )
    );
    static DestFinfo reinit(
        "reinit"
        , "Handles reinit call"
        , new ProcOpFunc< Streamer > ( &Streamer::reinit )
    );
    static DestFinfo addTable(
        "addTable"
        , "Add a table to Streamer"
        , new OpFunc1<Streamer, ObjId>( &Streamer::addTable )
    );
    static DestFinfo addTables(
        "addTables"
        , "Add many tables to Streamer"
        , new OpFunc1<Streamer, vector<ObjId> >( &Streamer::addTables )
    );
    static DestFinfo removeTable(
        "removeTable"
        , "Remove a table from Streamer"
        , new OpFunc1<Streamer, ObjId>( &Streamer::removeTable )
    );
    static DestFinfo removeTables(
        "removeTables"
        , "Remove tables -- if found -- from Streamer"
        , new OpFunc1<Streamer, vector<ObjId> >( &Streamer::removeTables )
    );
    /*-----------------------------------------------------------------------------
     *  ShareMsg definitions.
     *-----------------------------------------------------------------------------*/
    static Finfo* procShared[] =
    {
        &process, &reinit, &addTable, &addTables, &removeTable, &removeTables
    };
    static SharedFinfo proc(
        "proc",
        "Shared message for process and reinit",
        procShared, sizeof( procShared ) / sizeof( const Finfo* )
    );
    static Finfo * tableStreamFinfos[] =
    {
        &datafile, &outfile, &format, &proc, &numTables, &numWriteEvents
    };
    static string doc[] =
    {
        "Name", "Streamer",
        "Author", "Dilawar Singh, 2016, NCBS, Bangalore.",
        "Description", "Streamer: Stream moose.Table data to out-streams\n"
    };
    static Dinfo< Streamer > dinfo;
    static Cinfo tableStreamCinfo(
        "Streamer",
        TableBase::initCinfo(),
        tableStreamFinfos,
        sizeof( tableStreamFinfos )/sizeof(Finfo *),
        &dinfo,
        doc,
        sizeof(doc) / sizeof(string)
    );
    return &tableStreamCinfo;
}
References addTable(), addTables(), Cinfo::Cinfo(), DestFinfo::DestFinfo(), getDatafilePath(), getFormat(), getNumTables(), getNumWriteEvents(), TableBase::initCinfo(), OpFunc1< T, A >::OpFunc1(), process(), ProcOpFunc< T >::ProcOpFunc(), ReadOnlyValueFinfo< T, F >::ReadOnlyValueFinfo(), reinit(), removeTable(), removeTables(), setDatafilePath(), setFormat(), SharedFinfo::SharedFinfo(), and ValueFinfo< T, F >::ValueFinfo().
operator=()
Streamer & Streamer::operator= (const Streamer & st)
Definition at line 158 of file Streamer.cpp.
{
    return *this;
}
process()
void Streamer::process (const Eref & e, ProcPtr p)
This function is called at its clock tick.
Dest functions. The process function called by scheduler on every tick
Parameters
e
p
Definition at line 268 of file Streamer.cpp.
{
    // LOG( moose::debug, "Writing Streamer data to file." );
    zipWithTime( );
    StreamerBase::writeToOutFile( datafilePath_, format_, APPEND, data_, columns_ );
    data_.clear();
    numWriteEvents_ += 1;
}
References APPEND, columns_, data_, datafilePath_, format_, numWriteEvents_, StreamerBase::writeToOutFile(), and zipWithTime().
Referenced by initCinfo().
reinit()
void Streamer::reinit (const Eref & e, ProcPtr p)
Reinit.
The reinit function called by scheduler for the reset
Parameters
e
p
Definition at line 174 of file Streamer.cpp.
{
    if( tables_.size() == 0 )
    {
        moose::showWarn( "Zero tables in streamer. Disabling Streamer" );
        e.element()->setTick( -2 );             /* Disable process */
        return;
    }
    Clock* clk = reinterpret_cast<Clock*>( Id(1).eref().data() );
    for (unsigned int i = 0; i < tableIds_.size(); i++)
    {
        int tickNum = tableIds_[i].element()->getTick();
        double tick = clk->getTickDt( tickNum );
        tableDt_.push_back( tick );
        // Make sure that all tables have the same tick.
        if( i > 0 )
        {
            if( tick != tableDt_[0] )
            {
                moose::showWarn( "Table " + tableIds_[i].path() + " has "
                                 " different clock dt. "
                                 " Make sure all tables added to Streamer have the same "
                                 " dt value."
                               );
            }
        }
    }
    // Push each table dt_ into vector of dt
    for( unsigned int i = 0; i < tables_.size(); i++)
    {
        Id tId = tableIds_[i];
        int tickNum = tId.element()->getTick();
        tableDt_.push_back( clk->getTickDt(tickNum) );
    }
    // Make sure all tables have same dt_ else disable the streamer.
    vector<unsigned int> invalidTables;
    for (unsigned int i = 1; i < tableTick_.size(); i++)
    {
        if( tableTick_[i] != tableTick_[0] )
        {
            LOG( moose::warning
                 , "Table " << tableIds_[i].path()
                 << " has tick (dt) which is different than the first table."
                 << endl
                 << " Got " << tableTick_[i] << " expected " << tableTick_[0]
                 << endl << " Disabling this table."
               );
            invalidTables.push_back( i );
        }
    }
    for (unsigned int i = 0; i < invalidTables.size(); i++)
    {
        tables_.erase( tables_.begin() + i );
        tableDt_.erase( tableDt_.begin() + i );
        tableIds_.erase( tableIds_.begin() + i );
    }
    if( ! isOutfilePathSet_ )
    {
        string defaultPath = "_tables/" + moose::moosePathToUserPath( e.id().path() );
        setDatafilePath( defaultPath );
    }
    // Prepare data. Add columns names and write whatever values are available
    // write now.
    currTime_ = 0.0;
    zipWithTime( );
    StreamerBase::writeToOutFile(datafilePath_, format_, WRITE, data_, columns_);
    data_.clear( );
}
References columns_, currTime_, Eref::data(), data_, datafilePath_, Eref::element(), Id::element(), ObjId::element(), Id::eref(), format_, Element::getTick(), Clock::getTickDt(), Eref::id(), Id::Id(), isOutfilePathSet_, moose::moosePathToUserPath(), Id::path(), ObjId::path(), setDatafilePath(), Element::setTick(), moose::showWarn(), tableDt_, tableIds_, tables_, tableTick_, moose::warning, WRITE, StreamerBase::writeToOutFile(), and zipWithTime().
Referenced by initCinfo().
removeTable()
void Streamer::removeTable (ObjId table)
Remove a table from Streamer.
Parameters
table. Id of table.
Definition at line 323 of file Streamer.cpp.
{
    int matchIndex = -1;
    for (unsigned int i = 0; i < tableIds_.size(); i++)
        if( table.path() == tableIds_[i].path() )
        {
            matchIndex = i;
            break;
        }
    if( matchIndex > -1 )
    {
        tableIds_.erase( tableIds_.begin() + matchIndex );
        tables_.erase( tables_.begin() + matchIndex );
        columns_.erase( columns_.begin() + matchIndex );
    }
}
References columns_, ObjId::path(), tableIds_, and tables_.
Referenced by initCinfo(), and removeTables().
removeTables()
void Streamer::removeTables (vector< ObjId > tables)
Remove multiple tables – if found – from Streamer.
Parameters
tables
Definition at line 346 of file Streamer.cpp.
{
    for(auto it = tables.cbegin(); it != tables.cend(); it++)
        removeTable( *it );
}
References removeTable().
Referenced by initCinfo().
setDatafilePath()
void Streamer::setDatafilePath (string path)
Definition at line 381 of file Streamer.cpp.
{
    datafilePath_ = filepath;
    isOutfilePathSet_ = true;
    if( ! moose::createParentDirs( filepath ) )
        datafilePath_ = moose::toFilename( datafilePath_ );
    string format = moose::getExtension( datafilePath_, true );
    if( format.size() > 0)
        setFormat( format );
    else
        setFormat( "csv" );
}
References moose::createParentDirs(), datafilePath_, moose::getExtension(), isOutfilePathSet_, setFormat(), and moose::toFilename().
Referenced by initCinfo(), and reinit().
setFormat()
void Streamer::setFormat (string format)
Definition at line 396 of file Streamer.cpp.
{
    format_ = fmt;
}
References format_.
Referenced by initCinfo(), and setDatafilePath().
zipWithTime()
void Streamer::zipWithTime ()
This function prepares data to be written to a file.
Definition at line 410 of file Streamer.cpp.
{
    unsigned int numEntriesInEachTable = tables_[0]->getVecSize( );
    //LOG( moose::debug, "Entries in each table " << numEntriesInEachTable );
    // Collect data from all table. If some table does not have enough data,
    // fill it with nan
    vector< vector< double > > collectedData;
    for( unsigned int i = 0; i < tables_.size( ); i++ )
    {
        vector<double> tVec( tables_[i]->getVector( ) );
        if( tVec.size( ) <= numEntriesInEachTable )
        {
#if 0
            LOG( moose::debug
                 , "Table " << tables_[i]->getName( ) << " is not functional. Filling with zero "
               );
#endif
            tVec.resize( numEntriesInEachTable, 0 );
        }
        collectedData.push_back( tVec );
    }
    // Turn it into a table format. Its like taking a transpose of vector<
    // vector >.
    double allTableDt = tableDt_[ 0 ];
    for( unsigned int i = 0; i < collectedData[0].size( ); i++ )
    {
        data_.push_back( currTime_ );
        currTime_ += allTableDt;
        for( unsigned int ii = 0; ii < collectedData.size(); ii++ )
            data_.push_back( collectedData[ ii ][ i ] );
    }
    // After collection data from table, clear tables.
    for(unsigned int i = 0; i < tables_.size(); i++ )
        tables_[i]->clearVec( );
    return;
}
References TableBase::clearVec(), currTime_, data_, TableBase::getVecSize(), TableBase::getVector(), tableDt_, and tables_.
Referenced by cleanUp(), process(), and reinit().
Member Data Documentation
columns_
vector<string> Streamer::columns_ private
Definition at line 94 of file Streamer.h.
Referenced by addTable(), cleanUp(), process(), reinit(), removeTable(), and Streamer().
currTime_
double Streamer::currTime_ private
Definition at line 89 of file Streamer.h.
Referenced by reinit(), and zipWithTime().
data_
vector<double> Streamer::data_ private
Definition at line 97 of file Streamer.h.
Referenced by cleanUp(), process(), reinit(), Streamer(), and zipWithTime().
datafilePath_
string Streamer::datafilePath_ private
Definition at line 76 of file Streamer.h.
Referenced by cleanUp(), getDatafilePath(), process(), reinit(), and setDatafilePath().
format_
string Streamer::format_ private
Definition at line 77 of file Streamer.h.
Referenced by cleanUp(), getFormat(), process(), reinit(), setFormat(), and Streamer().
isOutfilePathSet_
bool Streamer::isOutfilePathSet_ private
Definition at line 81 of file Streamer.h.
Referenced by reinit(), and setDatafilePath().
numWriteEvents_
unsigned int Streamer::numWriteEvents_ private
Definition at line 79 of file Streamer.h.
Referenced by getNumWriteEvents(), process(), and Streamer().
tableDt_
vector<double> Streamer::tableDt_ private
Definition at line 84 of file Streamer.h.
Referenced by reinit(), Streamer(), and zipWithTime().
tableIds_
vector<ObjId> Streamer::tableIds_ private
Definition at line 92 of file Streamer.h.
Referenced by addTable(), reinit(), removeTable(), and Streamer().
tables_
vector<Table*> Streamer::tables_ private
Definition at line 93 of file Streamer.h.
Referenced by addTable(), getNumTables(), reinit(), removeTable(), Streamer(), and zipWithTime().
tableTick_
vector<unsigned int> Streamer::tableTick_ private
Definition at line 85 of file Streamer.h.
Referenced by addTable(), reinit(), and Streamer().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/builtins/Streamer.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/builtins/Streamer.cpp