MOOSE - Multiscale Object Oriented Simulation Environment: Arith Class Reference
Arith Class Reference
#include <Arith.h>
Public Member Functions
void addSpike (unsigned int synIndex, const double time)
void arg1 (double v)
void arg1x2 (double arg1, double arg2)
void arg2 (double v)
void arg3 (double v)
Arith ()
double getArg1 () const
string getFunction () const
double getIdentifiedArg (unsigned int i) const
double getOutput () const
void process (const Eref &e, ProcPtr p)
void reinit (const Eref &e, ProcPtr p)
void setFunction (string v)
void setIdentifiedArg (unsigned int i, double val)
void setOutput (double v)
Static Public Member Functions
static const Cinfo * initCinfo ()
Private Attributes
double arg1_
double arg2_
double arg3_
string function_
double output_
Friends
void testCopyMsgOps ()
void testTicks ()
Detailed Description
Definition at line 12 of file Arith.h.
Constructor & Destructor Documentation
Arith()
Arith::Arith ()
Definition at line 116 of file Arith.cpp.
    : function_( "sum" ),
    output_( 0.0 ),
    arg1_( 0.0 ), arg2_( 0.0 ), arg3_( 0.0 )
{
    ;
}
References arg1_, arg2_, arg3_, function_, and output_.
Member Function Documentation
addSpike()
void Arith::addSpike (unsigned int synIndex, const double time)
Inserts an event into the pendingEvents queue for spikes.
arg1()
void Arith::arg1 (double v)
Definition at line 147 of file Arith.cpp.
{
    arg1_ = arg;
}
References arg1_.
Referenced by initCinfo(), testArith(), and testFibonacci().
arg1x2()
void Arith::arg1x2 (double arg1, double arg2)
Definition at line 164 of file Arith.cpp.
{
    output_ = a1 * a2;
}
References output_.
Referenced by initCinfo().
arg2()
void Arith::arg2 (double v)
Definition at line 152 of file Arith.cpp.
{
    arg2_ = arg;
}
References arg2_.
Referenced by initCinfo(), testArith(), and testFibonacci().
arg3()
void Arith::arg3 (double v)
Definition at line 157 of file Arith.cpp.
{
    if ( doReport )
        cout << arg << "    " << &arg3_ << endl;
    arg3_ += arg;
}
References arg3_, and doReport.
Referenced by initCinfo().
getArg1()
double Arith::getArg1 () const
Definition at line 190 of file Arith.cpp.
{
    return arg1_;
}
References arg1_.
Referenced by checkArg1(), initCinfo(), testCreateMsg(), and testLookupSetGet().
getFunction()
string Arith::getFunction () const
Definition at line 175 of file Arith.cpp.
{
    return function_;
}
References function_.
Referenced by initCinfo().
getIdentifiedArg()
double Arith::getIdentifiedArg (unsigned int i) const
Definition at line 195 of file Arith.cpp.
{
    if ( i == 0 )
        return output_;
    if ( i == 1 )
        return arg1_;
    if ( i == 2 )
        return arg2_;
    if ( i == 3 )
        return arg3_;
    return 0;
}
References arg1_, arg2_, arg3_, and output_.
Referenced by initCinfo(), and testLookupSetGet().
getOutput()
double Arith::getOutput () const
Definition at line 185 of file Arith.cpp.
{
    return output_;
}
References output_.
Referenced by initCinfo(), test2ArgSetVec(), testArith(), testFibonacci(), testLookupSetGet(), testMsgField(), testSendMsg(), testSetGet(), testSetGetExtField(), and testStrSet().
initCinfo()
const Cinfo * Arith::initCinfo () static
Definition at line 22 of file Arith.cpp.
{
        // Field Definitions
        static ValueFinfo< Arith, string > function(
            "function",
            "Arithmetic function to perform on inputs.",
            &Arith::setFunction,
            &Arith::getFunction
        );
        static ValueFinfo< Arith, double > outputValue(
            "outputValue",
            "Value of output as computed last timestep.",
            &Arith::setOutput,
            &Arith::getOutput
        );
        static ReadOnlyValueFinfo< Arith, double > arg1Value(
            "arg1Value",
            "Value of arg1 as computed last timestep.",
            &Arith::getArg1
        );
        static LookupValueFinfo< Arith, unsigned int, double > anyValue(
            "anyValue",
            "Value of any of the internal fields, output, arg1, arg2, arg3,"
            "as specified by the index argument from 0 to 3.",
            &Arith::setIdentifiedArg,
            &Arith::getIdentifiedArg
        );
        // MsgDest Definitions
        static DestFinfo arg1( "arg1",
            "Handles argument 1. This just assigns it",
            new OpFunc1< Arith, double >( &Arith::arg1 ) );
        static DestFinfo arg2( "arg2",
            "Handles argument 2. This just assigns it",
            new OpFunc1< Arith, double >( &Arith::arg2 ) );
        static DestFinfo arg3( "arg3",
            "Handles argument 3. This sums in each input, and clears each clock tick.",
            new OpFunc1< Arith, double >( &Arith::arg3 ) );
        static DestFinfo arg1x2( "arg1x2",
            "Store the product of the two arguments in output_",
            new OpFunc2< Arith, double, double >( &Arith::arg1x2 ) );
        static DestFinfo process( "process",
            "Handles process call",
            new ProcOpFunc< Arith >( &Arith::process ) );
        static DestFinfo reinit( "reinit",
            "Handles reinit call",
            new ProcOpFunc< Arith >( &Arith::reinit ) );
        // SharedFinfo Definitions
        static Finfo* procShared[] = {
            &process, &reinit
        };
        static SharedFinfo proc( "proc",
            "Shared message for process and reinit",
            procShared, sizeof( procShared ) / sizeof( const Finfo* )
        );
    static Finfo* arithFinfos[] = {
        &function,  // Value
        &outputValue,   // Value
        &arg1Value, // ReadOnly value
        &anyValue,  // LookupValue
        &arg1,      // DestFinfo
        &arg2,      // DestFinfo
        &arg3,      // DestFinfo
        &arg1x2,    // DestFinfo
        output(),   // SrcFinfo
        &proc       // SharedFinfo
    };
    static Dinfo< Arith > dinfo;
    static Cinfo arithCinfo (
        "Arith",
        Neutral::initCinfo(),
        arithFinfos,
        sizeof( arithFinfos ) / sizeof ( Finfo* ),
        &dinfo
    );
    return &arithCinfo;
}
References arg1(), arg1x2(), arg2(), arg3(), Cinfo::Cinfo(), DestFinfo::DestFinfo(), getArg1(), getFunction(), getIdentifiedArg(), getOutput(), Neutral::initCinfo(), LookupValueFinfo< T, L, F >::LookupValueFinfo(), OpFunc1< T, A >::OpFunc1(), OpFunc2< T, A1, A2 >::OpFunc2(), output(), process(), ProcOpFunc< T >::ProcOpFunc(), ReadOnlyValueFinfo< T, F >::ReadOnlyValueFinfo(), reinit(), setFunction(), setIdentifiedArg(), setOutput(), SharedFinfo::SharedFinfo(), and ValueFinfo< T, F >::ValueFinfo().
Referenced by test2ArgSetVec(), testArith(), testAssortedMsg(), testCreateMsg(), testFibonacci(), testGet(), testIsA(), testLookupSetGet(), testMsgField(), testSendMsg(), testSetGet(), testSetGetExtField(), testStrGet(), and testStrSet().
process()
void Arith::process (const Eref & e, ProcPtr p)
Definition at line 125 of file Arith.cpp.
{
    output_ = arg1_ + arg2_ + arg3_; // Doing a hard-coded function.
    // cout << "process: " << e.element()->getName() << ", " << e.objId() << arg3_ << ", " << &arg3_ << endl;
    if ( doReport ) {
        cout <<
            e.element()->getName() << ", " << e.objId() << "        " <<
            arg3_ << "  " << &arg3_ << endl;
    }
    output()->send( e, output_ );
    arg3_ = 0.0;
}
References arg1_, arg2_, arg3_, doReport, Eref::element(), Element::getName(), Eref::objId(), output(), output_, and SrcFinfo1< T >::send().
Referenced by initCinfo(), and testArith().
reinit()
void Arith::reinit (const Eref & e, ProcPtr p)
Definition at line 138 of file Arith.cpp.
{
    // cout << "reinit: " << e.element()->getName() << ", " << e.objId() << arg3_ << endl;
    arg1_ = 0.0;
    arg2_ = 0.0;
    arg3_ = 0.0;
    output_ = 0.0;
}
References arg1_, arg2_, arg3_, and output_.
Referenced by initCinfo().
setFunction()
void Arith::setFunction (string v)
Definition at line 170 of file Arith.cpp.
{
    function_ = v;
}
References function_.
Referenced by initCinfo().
setIdentifiedArg()
void Arith::setIdentifiedArg (unsigned int i, double val)
Definition at line 208 of file Arith.cpp.
{
    if ( i == 0 )
        output_ = val;
    if ( i == 1 )
        arg1_ = val;
    if ( i == 2 )
        arg2_ = val;
    if ( i == 3 )
        arg3_ = val;
}
References arg1_, arg2_, arg3_, and output_.
Referenced by initCinfo(), and testLookupSetGet().
setOutput()
void Arith::setOutput (double v)
Definition at line 180 of file Arith.cpp.
{
    output_ = v;
}
References output_.
Referenced by initCinfo(), testGet(), and testStrGet().
Friends And Related Symbol Documentation
testCopyMsgOps
void testCopyMsgOps () friend
Definition at line 1079 of file testShell.cpp.
{
    Eref sheller = Id().eref();
    Shell* shell = reinterpret_cast<Shell*>(sheller.data());
    Id pa = shell->doCreate("Neutral", Id(), "pa", 1, MooseGlobal);
    unsigned int size = 5;
    // Set up the objects.
    Id a1 = shell->doCreate("Arith", pa, "a1", size, MooseGlobal);
    Id a2 = shell->doCreate("Arith", pa, "a2", size, MooseGlobal);
    Id b1 = shell->doCreate("Arith", pa, "b1", size, MooseGlobal);
    Id b2 = shell->doCreate("Arith", pa, "b2", size, MooseGlobal);
    Id c1 = shell->doCreate("Arith", pa, "c1", size, MooseGlobal);
    Id c2 = shell->doCreate("Arith", pa, "c2", size, MooseGlobal);
    Id d1 = shell->doCreate("Arith", pa, "d1", size, MooseGlobal);
    Id d2 = shell->doCreate("Arith", pa, "d2", size, MooseGlobal);
    Id e1 = shell->doCreate("Arith", pa, "e1", size, MooseGlobal);
    Id e2 = shell->doCreate("Arith", pa, "e2", size, MooseGlobal);
    // Set up initial conditions and some scheduling.
    shell->doSetClock(0, 1.0);
    shell->doReinit();
    bool ret = 0;
    vector<double> init;  // 12345
    for (unsigned int i = 1; i < 6; ++i) init.push_back(i);
    ret = SetGet1<double>::setVec(a1, "arg1", init);  // 12345
    assert(ret);
    ret = SetGet1<double>::setVec(b1, "arg1", init);  // 12345
    assert(ret);
    ret = SetGet1<double>::setVec(c1, "arg1", init);  // 12345
    assert(ret);
    ret = SetGet1<double>::setVec(d1, "arg1", init);  // 12345
    assert(ret);
    ret = SetGet1<double>::setVec(e1, "arg1", init);  // 12345
    assert(ret);
    // Set up messaging
    // Should give 04000
    ObjId m1 =
        shell->doAddMsg("Single", ObjId(a1, 3), "output", ObjId(a2, 1), "arg1");
    assert(m1 != ObjId());
    // Should give 33333
    ObjId m2 = shell->doAddMsg("OneToAll", ObjId(b1, 2), "output", ObjId(b2, 0),
                               "arg1");
    assert(m2 != ObjId());
    // Should give 12345
    ObjId m3 = shell->doAddMsg("OneToOne", ObjId(c1, 0), "output", ObjId(c2, 0),
                               "arg1");
    assert(m3 != ObjId());
    // Should give 01234
    ObjId m4 = shell->doAddMsg("Diagonal", ObjId(d1, 0), "output", ObjId(d2, 0),
                               "arg1");
    assert(m4 != ObjId());
    // Should give 54321
    ObjId m5 =
        shell->doAddMsg("Sparse", ObjId(e1, 0), "output", ObjId(e2, 0), "arg1");
    assert(m5 != ObjId());
    ret = SetGet3<unsigned int, unsigned int, unsigned int>::set(m5, "setEntry",
                                                                 0, 4, 0);
    assert(ret);
    ret = SetGet3<unsigned int, unsigned int, unsigned int>::set(m5, "setEntry",
                                                                 1, 3, 0);
    assert(ret);
    ret = SetGet3<unsigned int, unsigned int, unsigned int>::set(m5, "setEntry",
                                                                 2, 2, 0);
    assert(ret);
    ret = SetGet3<unsigned int, unsigned int, unsigned int>::set(m5, "setEntry",
                                                                 3, 1, 0);
    assert(ret);
    ret = SetGet3<unsigned int, unsigned int, unsigned int>::set(m5, "setEntry",
                                                                 4, 0, 0);
    assert(ret);
    assert(ret);
    // ObjId clock( Id( 1 ), 0 );
    // Copy it
    Id pa2 = shell->doCopy(pa, Id(), "pa2", 1, false, false);
    // Pull out the child Ids.
    vector<Id> kids = Field<vector<Id>>::get(pa2, "children");
    assert(kids.size() == 10);
    shell->doUseClock("/pa2/#", "process", 0);
    unsigned int j = 0;
    assert(kids[j].element()->getName() == "a1");
    ++j;
    assert(kids[j].element()->getName() == "a2");
    ++j;
    assert(kids[j].element()->getName() == "b1");
    ++j;
    assert(kids[j].element()->getName() == "b2");
    ++j;
    assert(kids[j].element()->getName() == "c1");
    ++j;
    assert(kids[j].element()->getName() == "c2");
    ++j;
    assert(kids[j].element()->getName() == "d1");
    ++j;
    assert(kids[j].element()->getName() == "d2");
    ++j;
    assert(kids[j].element()->getName() == "e1");
    ++j;
    assert(kids[j].element()->getName() == "e2");
    ++j;
    /*
    vector< double > retVec;
    Field< double >::getVec( kids[0], "arg1Value", retVec );
    assert( retVec.size() == 5 );
    assert( doubleEq( retVec[i], init[i] ) );
    */
    for (unsigned int i = 0; i < 5; ++i) {
        double x = Field<double>::get(ObjId(kids[0], i), "arg1Value");
        assert(doubleEq(x, init[i]));
    }
    // Run it
    shell->doStart(2);
    // Check output.
    ret = checkOutput(kids[1], 0, 4, 0, 0, 0);
    assert(ret);
    ret = checkOutput(kids[2], 1, 2, 3, 4, 5);
    assert(ret);
    ret = checkOutput(kids[3], 3, 3, 3, 3, 3);
    assert(ret);
    ret = checkOutput(kids[5], 1, 2, 3, 4, 5);
    assert(ret);
    ret = checkOutput(kids[7], 0, 1, 2, 3, 4);
    assert(ret);
    ret = checkOutput(kids[9], 5, 4, 3, 2, 1);
    assert(ret);
    // Clean up.
    shell->doDelete(pa);
    shell->doDelete(pa2);
    cout << "." << flush;
}
Referenced by testMpiShell().
testTicks
void testTicks () friend
Member Data Documentation
arg1_
double Arith::arg1_ private
Definition at line 60 of file Arith.h.
Referenced by arg1(), Arith(), getArg1(), getIdentifiedArg(), process(), reinit(), and setIdentifiedArg().
arg2_
double Arith::arg2_ private
Definition at line 61 of file Arith.h.
Referenced by arg2(), Arith(), getIdentifiedArg(), process(), reinit(), and setIdentifiedArg().
arg3_
double Arith::arg3_ private
Definition at line 62 of file Arith.h.
Referenced by arg3(), Arith(), getIdentifiedArg(), process(), reinit(), and setIdentifiedArg().
function_
string Arith::function_ private
Definition at line 58 of file Arith.h.
Referenced by Arith(), getFunction(), and setFunction().
output_
double Arith::output_ private
Definition at line 59 of file Arith.h.
Referenced by arg1x2(), Arith(), getIdentifiedArg(), getOutput(), process(), reinit(), setIdentifiedArg(), and setOutput().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/builtins/Arith.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/builtins/Arith.cpp