MOOSE - Multiscale Object Oriented Simulation Environment: ChemCompt Class Reference
ChemCompt Class Reference abstract
#include <ChemCompt.h>
Public Member Functions
void buildDefaultMesh (const Eref &e, double volume, unsigned int numEntries)
void buildJunction (ChemCompt *other, vector< VoxelJunction > &ret)
ChemCompt ()
virtual void clearExtendedMeshEntryVolume ()=0
clear out extended mesh entries for rebuilding.
virtual double extendedMeshEntryVolume (unsigned int fid) const =0
Volume of mesh Entry including abutting diff-coupled voxels.
virtual void extendStencil (const ChemCompt *other, const vector< VoxelJunction > &vj)=0
void flipRet (vector< VoxelJunction > &ret) const
Utility function for swapping first and second in VoxelJunctions.
void getChildConcs (const Eref &e, vector< double > &childConcs) const
virtual vector< double > getCoordinates (unsigned int fid) const =0
Virtual function to return coords of mesh Entry.
virtual vector< double > getDiffusionArea (unsigned int fid) const =0
Virtual function to return diffusion X-section area per neighbor.
virtual vector< double > getDiffusionScaling (unsigned int fid) const =0
Virtual function to return scale factor for diffusion. 1 here.
unsigned int getDimensions () const
double getEntireVolume (const Eref &e) const
bool getIsMembraneBound () const
virtual unsigned int getMeshDimensions (unsigned int fid) const =0
Virtual function to return dimensions of specified entry.
virtual double getMeshEntryVolume (unsigned int fid) const =0
Virtual function to return volume of mesh Entry.
virtual unsigned int getMeshType (unsigned int fid) const =0
Virtual function to return MeshType of specified entry.
string getMethod () const
virtual vector< unsigned int > getNeighbors (unsigned int fid) const =0
Virtual function to return info on Entries connected to this one.
unsigned int getNumEntries () const
vector< double > getOneVoxelMidpoint (unsigned int vox) const
Looks up specified voxel midpoint, from vGetVoxelMidpoint.
double getOneVoxelVolume (const Eref &e, unsigned int voxel) const
vector< unsigned int > getStencilIndex (unsigned int row) const
vector< double > getStencilRate (unsigned int row) const
virtual unsigned int getStencilRow (unsigned int meshIndex, const double **entry, const unsigned int **colIndex) const =0
vector< double > getVoxelMidpoint () const
Returns vector of all voxel midpoints in compartment.
vector< double > getVoxelVolume () const
Returns vector of all voxel volumes in compartment.
void handleNodeInfo (const Eref &e, unsigned int numNodes, unsigned int numThreads)
virtual void indexToSpace (unsigned int index, double &x, double &y, double &z) const =0
virtual void innerBuildDefaultMesh (const Eref &e, double volume, unsigned int numEntries)=0
virtual unsigned int innerGetDimensions () const =0
virtual unsigned int innerGetNumEntries () const =0
virtual vector< double > innerGetStencilRate (unsigned int row) const =0
Virtual func for getting stencil rates for the derived classes.
virtual void innerHandleNodeInfo (const Eref &e, unsigned int numNodes, unsigned int numThreads)=0
virtual void innerResetStencil ()=0
virtual void innerSetNumEntries (unsigned int n)=0
MeshEntry * lookupEntry (unsigned int index)
virtual void matchMeshEntries (const ChemCompt *other, vector< VoxelJunction > &ret) const =0
virtual double nearest (double x, double y, double z, unsigned int &index) const =0
void resetStencil ()
unsigned int setChildConcs (const Eref &e, const vector< double > &childConcs, unsigned int start) const
void setEntireVolume (const Eref &e, double volume)
void setIsMembraneBound (bool v)
virtual void setMeshEntryVolume (unsigned int fid, double volume)
void setMethod (string method)
void setNumEntries (unsigned int num)
void setOneVoxelVolume (const Eref &e, unsigned int voxel, double volume)
void setVolumeNotRates (double volume)
virtual double vGetEntireVolume () const =0
virtual const vector< double > & vGetVoxelMidpoint () const =0
Virtual func so that derived classes can return voxel midpoint.
virtual const vector< double > & vGetVoxelVolume () const =0
Virtual func so that derived classes can pass voxel volume back.
virtual bool vSetVolumeNotRates (double volume)=0
Virtual function for actually doing this.
virtual ~ChemCompt ()
Static Public Member Functions
static double distance (double x, double y, double z)
static const Cinfo * initCinfo ()
static SrcFinfo1< vector< double > > * voxelVolOut ()
Private Attributes
vector< Boundary > boundaries_
Wrapper for self ptr.
MeshEntry entry_
bool isMembraneBound_
string method_
Detailed Description
The ChemCompt represents a chemically identified compartment. This may be spatially extended, and may even be discontinuous. The same set of reactions and molecules populates any given compartment. Examples of compartments might be: nucleus, cell membrane, early endosomes, spine heads. Connects to one or more 'Geometry' elements to define its boundaries.
Definition at line 23 of file ChemCompt.h.
Constructor & Destructor Documentation
ChemCompt()
ChemCompt::ChemCompt ()
Definition at line 224 of file ChemCompt.cpp.
    :
    entry_( this ),
    isMembraneBound_( false )
{
    ;
}
References entry_, isMembraneBound_, and MeshEntry::MeshEntry().
~ChemCompt()
ChemCompt::~ChemCompt () virtual
Definition at line 232 of file ChemCompt.cpp.
{
    /*
    for ( unsigned int i = 0; i < stencil_.size(); ++i ) {
    if ( stencil_[i] )
        delete stencil_[i];
    }
    */
}
Member Function Documentation
buildDefaultMesh()
void ChemCompt::buildDefaultMesh (const Eref & e, double volume, unsigned int numEntries)
buildDefaultMesh tells the ChemCompt to make a standard mesh partitioning with the specified total volume and the specified number of subdivisions. For example, a CubeMesh of volume 8 and subdivisions 8 would make a 2x2x2 mesh. This function is specialized in each derived class.
Definition at line 246 of file ChemCompt.cpp.
{
    this->innerBuildDefaultMesh( e, volume, numEntries );
}
References innerBuildDefaultMesh().
Referenced by initCinfo().
buildJunction()
void ChemCompt::buildJunction (ChemCompt * other, vector< VoxelJunction > & ret)
Wrapper function to buld junction between two meshes, and to extend the meshes so that their stencils also handle update to the voxels abutting the boundary on the neighbor mesh.
Definition at line 460 of file ChemCompt.cpp.
{
    matchMeshEntries( other, ret );
    extendStencil( other, ret );
}
References extendStencil(), and matchMeshEntries().
clearExtendedMeshEntryVolume()
virtual void ChemCompt::clearExtendedMeshEntryVolume () pure virtual
clear out extended mesh entries for rebuilding.
Implemented in MeshCompt.
distance()
double ChemCompt::distance (double x, double y, double z) static
Definition at line 483 of file ChemCompt.cpp.
{
    return sqrt(x*x + y*y + z*z);
}
Referenced by CylMesh::matchCylMeshEntries(), CylMesh::nearest(), and CubeMesh::nearest().
extendedMeshEntryVolume()
virtual double ChemCompt::extendedMeshEntryVolume (unsigned int fid) const pure virtual
Volume of mesh Entry including abutting diff-coupled voxels.
Implemented in CubeMesh, CylMesh, EndoMesh, MeshCompt, NeuroMesh, PresynMesh, PsdMesh, and SpineMesh.
extendStencil()
virtual void ChemCompt::extendStencil (const ChemCompt * other, const vector< VoxelJunction > & vj) pure virtual
Function to add voxels for boundaries. This is done so that the solver can do reaction-diffusion computations on the entire mesh including voxels of neighboring solvers abutting the boundary. It uses these to stitch together the computations that span multiple solvers and compartments.
Implemented in MeshCompt.
Referenced by buildJunction().
flipRet()
void ChemCompt::flipRet (vector< VoxelJunction > & ret) const
Utility function for swapping first and second in VoxelJunctions.
Definition at line 466 of file ChemCompt.cpp.
{
    vector< VoxelJunction >::iterator i;
    for ( i = ret.begin(); i != ret.end(); ++i )
    {
        unsigned int temp = i->first;
        i->first = i->second;
        i->second = temp;
        double vol = i->firstVol;
        i->firstVol = i->secondVol;
        i->secondVol = vol;
    }
}
References VoxelJunction::first, VoxelJunction::firstVol, VoxelJunction::second, and VoxelJunction::secondVol.
Referenced by CubeMesh::matchCubeMeshEntries(), CubeMesh::matchCylMeshEntries(), CylMesh::matchMeshEntries(), CubeMesh::matchMeshEntries(), NeuroMesh::matchMeshEntries(), and SpineMesh::matchMeshEntries().
getChildConcs()
void ChemCompt::getChildConcs (const Eref & e, vector< double > & childConcs) const
Recursively traverses all children, depth_first, scooping up concentration terms: conc and concInit for pools, Kf and Kb for Reacs, and Km for enzymes. These are inserted in order into the vector of childConcs. Does not traverse into children of other ChemCompts
Definition at line 294 of file ChemCompt.cpp.
{
    vector< Id > kids;
    Neutral::children( e, kids );
    for ( vector < Id >::iterator i = kids.begin(); i != kids.end(); ++i )
    {
        if ( i->element()->cinfo()->isA( "PoolBase" ) )
        {
            childConcs.push_back( Field< double >::get( *i, "conc" ) );
            childConcs.push_back( Field< double >::get( *i, "concInit" ) );
        }
        else if ( i->element()->cinfo()->isA( "Reac" ) )
        {
            childConcs.push_back( Field< double >::get( *i, "Kf" ) );
            childConcs.push_back( Field< double >::get( *i, "Kb" ) );
        }
        else if ( i->element()->cinfo()->isA( "EnzBase" ) )
        {
            childConcs.push_back( Field< double >::get( *i, "Km" ) );
        }
        else if ( i->element()->cinfo()->isA( "ChemCompt" ) )
        {
            // Do NOT traverse into child ChemCompts, they look after their
            // own volumes.
            continue;
        }
        getChildConcs( i->eref(), childConcs );
    }
}
References Neutral::children(), Element::cinfo(), Id::element(), Id::eref(), Field< A >::get(), getChildConcs(), and Cinfo::isA().
Referenced by getChildConcs(), CylMesh::innerSetCoords(), CylMesh::setDiffLength(), setEntireVolume(), CylMesh::setR0(), CylMesh::setR1(), CylMesh::setX0(), CylMesh::setX1(), CylMesh::setY0(), CylMesh::setY1(), CylMesh::setZ0(), and CylMesh::setZ1().
getCoordinates()
vector< double > ChemCompt::getCoordinates (unsigned int fid) const pure virtual
Virtual function to return coords of mesh Entry.
Implemented in CubeMesh, CylMesh, EndoMesh, NeuroMesh, PresynMesh, PsdMesh, and SpineMesh.
Definition at line 366 of file ChemCompt.cpp.
{
    return this->getCoordinates( fid );
}
References getCoordinates().
Referenced by MeshEntry::getCoordinates(), EndoMesh::getCoordinates(), getCoordinates(), and initCinfo().
getDiffusionArea()
virtual vector< double > ChemCompt::getDiffusionArea (unsigned int fid) const pure virtual
Virtual function to return diffusion X-section area per neighbor.
Implemented in CubeMesh, CylMesh, EndoMesh, NeuroMesh, PresynMesh, PsdMesh, and SpineMesh.
Referenced by MeshEntry::getDiffusionArea().
getDiffusionScaling()
virtual vector< double > ChemCompt::getDiffusionScaling (unsigned int fid) const pure virtual
Virtual function to return scale factor for diffusion. 1 here.
Implemented in CubeMesh, CylMesh, EndoMesh, NeuroMesh, PresynMesh, PsdMesh, and SpineMesh.
Referenced by MeshEntry::getDiffusionScaling().
getDimensions()
unsigned int ChemCompt::getDimensions () const
Returns # of dimensions of mesh. This is 3 for cube, and 1 for cylinder or neurons.
Definition at line 400 of file ChemCompt.cpp.
{
    return this->innerGetDimensions();
}
References innerGetDimensions().
Referenced by initCinfo(), testCubeMesh(), and testCubeMeshExtendStencil().
getEntireVolume()
double ChemCompt::getEntireVolume (const Eref & e) const
Returns volume, area, or length of compartment, depending on dimensionality.
Definition at line 289 of file ChemCompt.cpp.
{
    return vGetEntireVolume();
}
References vGetEntireVolume().
Referenced by initCinfo().
getIsMembraneBound()
bool ChemCompt::getIsMembraneBound () const
Definition at line 415 of file ChemCompt.cpp.
{
    return isMembraneBound_;
}
References isMembraneBound_.
Referenced by initCinfo().
getMeshDimensions()
virtual unsigned int ChemCompt::getMeshDimensions (unsigned int fid) const pure virtual
Virtual function to return dimensions of specified entry.
Implemented in CubeMesh, CylMesh, EndoMesh, NeuroMesh, PresynMesh, PsdMesh, and SpineMesh.
Referenced by MeshEntry::getDimensions().
getMeshEntryVolume()
virtual double ChemCompt::getMeshEntryVolume (unsigned int fid) const pure virtual
Virtual function to return volume of mesh Entry.
Implemented in CubeMesh, CylMesh, EndoMesh, NeuroMesh, PresynMesh, PsdMesh, and SpineMesh.
Referenced by MeshCompt::extendStencil(), EndoMesh::getMeshEntryVolume(), getOneVoxelVolume(), and MeshEntry::getVolume().
getMeshType()
virtual unsigned int ChemCompt::getMeshType (unsigned int fid) const pure virtual
Virtual function to return MeshType of specified entry.
Implemented in CubeMesh, CylMesh, EndoMesh, NeuroMesh, PresynMesh, PsdMesh, and SpineMesh.
Referenced by MeshEntry::getMeshType().
getMethod()
string ChemCompt::getMethod () const
getNeighbors()
virtual vector< unsigned int > ChemCompt::getNeighbors (unsigned int fid) const pure virtual
Virtual function to return info on Entries connected to this one.
Implemented in MeshCompt.
Referenced by MeshEntry::getNeighbors(), and getStencilIndex().
getNumEntries()
unsigned int ChemCompt::getNumEntries () const
Returns the number of MeshEntries on this ChemCompt
Definition at line 450 of file ChemCompt.cpp.
{
    return this->innerGetNumEntries();
}
References innerGetNumEntries().
Referenced by Dsolve::build(), EndoMesh::getDiffusionArea(), EndoMesh::getDiffusionScaling(), initCinfo(), EndoMesh::innerHandleRequestMeshStats(), CylBase::matchCubeMeshEntries(), CylMesh::matchCubeMeshEntries(), and MeshEntry::triggerRemesh().
getOneVoxelMidpoint()
vector< double > ChemCompt::getOneVoxelMidpoint (unsigned int vox) const
Looks up specified voxel midpoint, from vGetVoxelMidpoint.
Definition at line 371 of file ChemCompt.cpp.
{
    const vector< double >& v = vGetVoxelMidpoint();
    vector< double > ret = { 0.0, 0.0, 0.0 };
    unsigned int numVoxels = v.size() / 3;
    if ( vox < numVoxels ) {
        ret[0] = v[vox];
        ret[1] = v[vox + numVoxels];
        ret[2] = v[vox + numVoxels * 2];
    }
    return ret;
}
References vGetVoxelMidpoint().
Referenced by initCinfo().
getOneVoxelVolume()
double ChemCompt::getOneVoxelVolume (const Eref & e, unsigned int voxel) const
Returns volume of specified voxel
Definition at line 384 of file ChemCompt.cpp.
{
    return this->getMeshEntryVolume( dataIndex );
}
References getMeshEntryVolume().
Referenced by initCinfo().
getStencilIndex()
vector< unsigned int > ChemCompt::getStencilIndex (unsigned int row) const
Function to return the stencil indices used in the diffusion calculations for voxelized compartments. Refers to the getNeighbors virtual function.
Definition at line 410 of file ChemCompt.cpp.
{
    return this->getNeighbors( row );
}
References getNeighbors().
Referenced by initCinfo().
getStencilRate()
vector< double > ChemCompt::getStencilRate (unsigned int row) const
Function to return the stencil values used in the diffusion calculations for voxelized compartments.
Definition at line 405 of file ChemCompt.cpp.
{
    return this->innerGetStencilRate( row );
}
References innerGetStencilRate().
Referenced by initCinfo().
getStencilRow()
virtual unsigned int ChemCompt::getStencilRow (unsigned int meshIndex, const double ** entry, const unsigned int ** colIndex) const pure virtual
Function to look up scale factor derived from area and length of compartment junction, for all the mesh entries connected to the specified one. Modeled on equivalent function in SparseMatrix. meshIndex: index of reference mesh entry entry: array of values of scale factor colIndex: array of relative indices for each entry. The values returned here are the offset from the meshIndex. Returns number of entries and colIndexes. For a 1-D mesh, there will be 2 except at boundaries For a 2-D mesh, there will be 4 except at boundaries For a 3-D mesh, there will be 6 except at boundaries For a neuromesh, there will be a variable number depending on branching. For a CylMesh there are 2 except at boundaries.
Implemented in MeshCompt.
getVoxelMidpoint()
vector< double > ChemCompt::getVoxelMidpoint () const
Returns vector of all voxel midpoints in compartment.
Definition at line 361 of file ChemCompt.cpp.
{
    return this->vGetVoxelMidpoint();
}
References vGetVoxelMidpoint().
Referenced by initCinfo().
getVoxelVolume()
vector< double > ChemCompt::getVoxelVolume () const
Returns vector of all voxel volumes in compartment.
Definition at line 356 of file ChemCompt.cpp.
{
    return this->vGetVoxelVolume();
}
References vGetVoxelVolume().
Referenced by Dsolve::build(), initCinfo(), and mapVoxelsBetweenMeshes().
handleNodeInfo()
void ChemCompt::handleNodeInfo (const Eref & e, unsigned int numNodes, unsigned int numThreads)
Definition at line 252 of file ChemCompt.cpp.
{
    // Pass it down to derived classes along with the SrcFinfo
    innerHandleNodeInfo( e, numNodes, numThreads );
}
References innerHandleNodeInfo().
Referenced by initCinfo().
indexToSpace()
virtual void ChemCompt::indexToSpace (unsigned int index, double & x, double & y, double & z) const pure virtual
Converts specified index to xyz coords of middle of voxel Values out of range return original xyz
Implemented in CubeMesh, CylMesh, EndoMesh, NeuroMesh, PresynMesh, PsdMesh, and SpineMesh.
Referenced by EndoMesh::indexToSpace().
initCinfo()
const Cinfo * ChemCompt::initCinfo () static
Definition at line 26 of file ChemCompt.cpp.
{
    // Field Definitions
    static ElementValueFinfo< ChemCompt, double > volume(
        "volume",
        "Volume of entire chemical domain."
        "Assigning this only works if the chemical compartment has"
        "only a single voxel. Otherwise ignored."
        "This function goes through all objects below this on the"
        "tree, and rescales their molecule #s and rates as per the"
        "volume change. This keeps concentration the same, and also"
        "maintains rates as expressed in volume units.",
        &ChemCompt::setEntireVolume,
        &ChemCompt::getEntireVolume
    );
    static ReadOnlyValueFinfo< ChemCompt, vector< double > >
    voxelVolume(
        "voxelVolume",
        "Vector of volumes of each of the voxels.",
        &ChemCompt::getVoxelVolume
    );
    static ReadOnlyValueFinfo< ChemCompt, vector< double > >
    voxelMidpoint(
        "voxelMidpoint",
        "Vector of midpoint coordinates of each of the voxels. The "
        "size of this vector is 3N, where N is the number of voxels. "
        "The first N entries are for x, next N for y, last N are z. ",
        &ChemCompt::getVoxelMidpoint
    );
    static ReadOnlyLookupValueFinfo<
            ChemCompt, unsigned int, vector< double > >
    oneVoxelMidpoint(
        "oneVoxelMidpoint",
        "Vector of midpoint coordinates of specified voxel.",
        &ChemCompt::getOneVoxelMidpoint
    );
    static ReadOnlyLookupValueFinfo<
            ChemCompt, unsigned int, vector< double > >
    voxelCoords(
               "voxelCoords",
               "Returns vector of coords of voxel specified by fid."
               "Coords for CubeMesh are x1y1z1 x2y2z2."
               "Coords for Cylinder, Neuro, Spine and PSD are: "
               "x1y1z1 x2y2z2 dia0 dia1 phi0 phi1"
               "Last two of these are ignored here."
               "Returns empty vec if voxel idx is wrong.",
               &ChemCompt::getCoordinates
    );
    static LookupElementValueFinfo<
    ChemCompt, unsigned int, double >
    oneVoxelVolume(
        "oneVoxelVolume",
        "Volume of specified voxel.",
        &ChemCompt::setOneVoxelVolume,
        &ChemCompt::getOneVoxelVolume
    );
    static ReadOnlyValueFinfo< ChemCompt, unsigned int > numDimensions(
        "numDimensions",
        "Number of spatial dimensions of this compartment. Usually 3 or 2",
        &ChemCompt::getDimensions
    );
    static ReadOnlyLookupValueFinfo< ChemCompt, unsigned int, vector< double > > stencilRate(
        "stencilRate",
        "vector of diffusion rates in the stencil for specified voxel."
        "The identity of the coupled voxels is given by the partner "
        "field 'stencilIndex'."
        "Returns an empty vector for non-voxelized compartments.",
        &ChemCompt::getStencilRate
    );
    static ReadOnlyLookupValueFinfo< ChemCompt, unsigned int, vector< unsigned int > > stencilIndex(
        "stencilIndex",
        "vector of voxels diffusively coupled to the specified voxel."
        "The diffusion rates into the coupled voxels is given by the "
        "partner field 'stencilRate'."
        "Returns an empty vector for non-voxelized compartments.",
        &ChemCompt::getStencilIndex
    );
    static ValueFinfo< ChemCompt, bool > isMembraneBound(
        "isMembraneBound",
        "Flag, set to True for meshes where each voxel is membrane "
        "bound. \n"
        "NeuroMesh and SpineMesh are false. \n"
        "CubeMesh, CylMesh, and EndoMesh can be either. If they are "
        "membrane bound they can still interact via channels and "
        "cross-compartment reactions. ",
        &ChemCompt::setIsMembraneBound,
        &ChemCompt::getIsMembraneBound
    );
    // MsgDest Definitions
    static DestFinfo buildDefaultMesh( "buildDefaultMesh",
                                       "Tells ChemCompt derived class to build a default mesh with the"
                                       "specified volume and number of meshEntries.",
                                       new EpFunc2< ChemCompt, double, unsigned int >(
                                           &ChemCompt::buildDefaultMesh )
                                     );
    static DestFinfo setVolumeNotRates( "setVolumeNotRates",
                                        "Changes volume but does not notify any child objects."
                                        "Only works if the ChemCompt has just one voxel."
                                        "This function will invalidate any concentration term in"
                                        "the model. If you don't know why you would want to do this,"
                                        "then you shouldn't use this function.",
                                        new OpFunc1< ChemCompt, double >(
                                            &ChemCompt::setVolumeNotRates )
                                      );
    static DestFinfo handleNodeInfo( "handleNodeInfo",
                                     "Tells ChemCompt how many nodes and threads per node it is "
                                     "allowed to use. Triggers a return meshSplitOut message.",
                                     new EpFunc2< ChemCompt, unsigned int, unsigned int >(
                                         &ChemCompt::handleNodeInfo )
                                   );
    static DestFinfo resetStencil( "resetStencil",
                                   "Resets the diffusion stencil to the core stencil that only "
                                   "includes the within-mesh diffusion. This is needed prior to "
                                   "building up the cross-mesh diffusion through junctions.",
                                   new OpFunc0< ChemCompt >(
                                       &ChemCompt::resetStencil )
                                 );
    // Field Elements
    static FieldElementFinfo< ChemCompt, MeshEntry > entryFinfo(
        "mesh",
        "Field Element for mesh entries",
        MeshEntry::initCinfo(),
        &ChemCompt::lookupEntry,
        &ChemCompt::setNumEntries,
        &ChemCompt::getNumEntries,
        false
    );
    static Finfo* chemMeshFinfos[] =
    {
        &volume,            // Value
        &voxelVolume,       // ReadOnlyLookupValue
        &voxelMidpoint,     // ReadOnlyValue
        &oneVoxelMidpoint,      // ReadOnlyLookupValue
        &oneVoxelVolume,    // ReadOnlyLookupValue
        &voxelCoords,   // ReadOnlyLookupValue
        &numDimensions, // ReadOnlyValue
        &stencilRate,   // ReadOnlyLookupValue
        &stencilIndex,  // ReadOnlyLookupValue
        &isMembraneBound,   // Value
        voxelVolOut(),  // SrcFinfo
        &buildDefaultMesh,  // DestFinfo
        &setVolumeNotRates,     // DestFinfo
        &resetStencil,  // DestFinfo
        &entryFinfo,    // FieldElementFinfo
    };
    static string doc[] =
    {
        "Name", "ChemCompt",
        "Author", "Upi Bhalla",
        "Description", "Pure virtual base class for chemical compartments"
    };
    static Dinfo< short > dinfo;
    static Cinfo chemMeshCinfo (
        "ChemCompt",
        Neutral::initCinfo(),
        chemMeshFinfos,
        sizeof( chemMeshFinfos ) / sizeof ( Finfo* ),
        &dinfo,
        doc,
        sizeof(doc)/sizeof( string ),
        true // This is a base class, not be be created directly.
    );
    return &chemMeshCinfo;
}
References buildDefaultMesh(), Cinfo::Cinfo(), DestFinfo::DestFinfo(), ElementValueFinfo< T, F >::ElementValueFinfo(), EpFunc2< T, A1, A2 >::EpFunc2(), FieldElementFinfo< T, F >::FieldElementFinfo(), getCoordinates(), getDimensions(), getEntireVolume(), getIsMembraneBound(), getNumEntries(), getOneVoxelMidpoint(), getOneVoxelVolume(), getStencilIndex(), getStencilRate(), getVoxelMidpoint(), getVoxelVolume(), handleNodeInfo(), MeshEntry::initCinfo(), Neutral::initCinfo(), LookupElementValueFinfo< T, L, F >::LookupElementValueFinfo(), lookupEntry(), OpFunc0< T >::OpFunc0(), OpFunc1< T, A >::OpFunc1(), ReadOnlyLookupValueFinfo< T, L, F >::ReadOnlyLookupValueFinfo(), ReadOnlyValueFinfo< T, F >::ReadOnlyValueFinfo(), resetStencil(), setEntireVolume(), setIsMembraneBound(), setNumEntries(), setOneVoxelVolume(), setVolumeNotRates(), ValueFinfo< T, F >::ValueFinfo(), and voxelVolOut().
Referenced by CubeMesh::initCinfo(), CylMesh::initCinfo(), EndoMesh::initCinfo(), NeuroMesh::initCinfo(), PresynMesh::initCinfo(), PsdMesh::initCinfo(), and SpineMesh::initCinfo().
innerBuildDefaultMesh()
virtual void ChemCompt::innerBuildDefaultMesh (const Eref & e, double volume, unsigned int numEntries) pure virtual
Implemented in NeuroMesh, CubeMesh, CylMesh, EndoMesh, PresynMesh, PsdMesh, and SpineMesh.
Referenced by buildDefaultMesh().
innerGetDimensions()
virtual unsigned int ChemCompt::innerGetDimensions () const pure virtual
Implemented in CubeMesh, CylMesh, EndoMesh, NeuroMesh, PresynMesh, PsdMesh, and SpineMesh.
Referenced by getDimensions().
innerGetNumEntries()
virtual unsigned int ChemCompt::innerGetNumEntries () const pure virtual
Implemented in CubeMesh, CylMesh, EndoMesh, NeuroMesh, PresynMesh, PsdMesh, and SpineMesh.
Referenced by getNumEntries(), EndoMesh::getParentVoxel(), and EndoMesh::innerGetNumEntries().
innerGetStencilRate()
virtual vector< double > ChemCompt::innerGetStencilRate (unsigned int row) const pure virtual
Virtual func for getting stencil rates for the derived classes.
Implemented in MeshCompt.
Referenced by getStencilRate().
innerHandleNodeInfo()
virtual void ChemCompt::innerHandleNodeInfo (const Eref & e, unsigned int numNodes, unsigned int numThreads) pure virtual
Implemented in CubeMesh, CylMesh, EndoMesh, NeuroMesh, PresynMesh, PsdMesh, and SpineMesh.
Referenced by handleNodeInfo().
innerResetStencil()
virtual void ChemCompt::innerResetStencil () pure virtual
Implemented in MeshCompt.
Referenced by resetStencil().
innerSetNumEntries()
virtual void ChemCompt::innerSetNumEntries (unsigned int n) pure virtual
Implemented in CubeMesh, CylMesh, EndoMesh, NeuroMesh, PresynMesh, PsdMesh, and SpineMesh.
Referenced by setNumEntries().
lookupEntry()
MeshEntry * ChemCompt::lookupEntry (unsigned int index)
Returns the matched lookupEntry
Definition at line 439 of file ChemCompt.cpp.
{
    return &entry_;
}
References entry_.
Referenced by PsdMesh::handlePsdList(), SpineMesh::handleSpineList(), and initCinfo().
matchMeshEntries()
virtual void ChemCompt::matchMeshEntries (const ChemCompt * other, vector< VoxelJunction > & ret) const pure virtual
Returns the meshIndices (NOT spatial indices) of all adjacent mesh entry pairs on ether side of the (self, other) junction. meshIndices are the indices that look up entries in the vector of pools. spatialIndices are (iz * ny + iy) * nx + ix, that is, a linear conversion of cartesian spatial indices. So, for two touching cubes, the return vector is the paired meshIndices on either side of the plane of contact. If one mesh has a finer mesh than the other, or if there are more than one contact points from self to other (for example, at a corner), then we just have multiple pairs using the same meshIndex of the repeated voxel.
Implemented in CubeMesh, EndoMesh, NeuroMesh, PresynMesh, PsdMesh, and SpineMesh.
Referenced by buildJunction(), mapVoxelsBetweenMeshes(), and CubeMesh::matchCylMeshEntries().
nearest()
virtual double ChemCompt::nearest (double x, double y, double z, unsigned int & index) const pure virtual
Returns distance and index of nearest mesh entry. Computes each mesh entry position as its geometric centre. If the current location is not inside a valid mesh entry, distance returned is negative.
Implemented in CubeMesh, CylMesh, EndoMesh, NeuroMesh, PresynMesh, PsdMesh, and SpineMesh.
Referenced by EndoMesh::nearest().
resetStencil()
void ChemCompt::resetStencil ()
Reset stencil m_ to coreStencil_. This is needed as a prelude to rebuilding the junctions using extendStencil.
Definition at line 259 of file ChemCompt.cpp.
{
    this->innerResetStencil();
}
References innerResetStencil().
Referenced by initCinfo().
setChildConcs()
unsigned int ChemCompt::setChildConcs (const Eref & e, const vector< double > & childConcs, unsigned int start) const
Recursively traverses all children, depth_first, restoring concentration terms as scooped up by getChildConcs. Does conc and concInit for pools, Kf and Kb for Reacs, and Km for enzymes. These are restored in order into the vector of childConcs. Does not traverse into children of other ChemCompts.
Definition at line 324 of file ChemCompt.cpp.
{
    vector< Id > kids;
    Neutral::children( e, kids );
    for ( vector < Id >::iterator i = kids.begin(); i != kids.end(); ++i )
    {
        if ( i->element()->cinfo()->isA( "PoolBase" ) )
        {
            Field< double >::set( *i, "conc", conc[ start++ ] );
            Field< double >::set( *i, "concInit", conc[start++] );
        }
        else if ( i->element()->cinfo()->isA( "Reac" ) )
        {
            Field< double >::set( *i, "Kf", conc[ start++ ] );
            Field< double >::set( *i, "Kb", conc[ start++ ] );
        }
        else if ( i->element()->cinfo()->isA( "EnzBase" ) )
        {
            Field< double >::set( *i, "Km", conc[ start++ ] );
        }
        else if ( i->element()->cinfo()->isA( "ChemCompt" ) )
        {
            // Do NOT traverse into child ChemCompts, they look after their
            // own volumes.
            continue;
        }
        start = setChildConcs( i->eref(), conc, start );
    }
    return start;
}
References Neutral::children(), Element::cinfo(), Id::element(), Id::eref(), Cinfo::isA(), Field< A >::set(), and setChildConcs().
Referenced by setChildConcs(), setEntireVolume(), and CylMesh::updateCoords().
setEntireVolume()
void ChemCompt::setEntireVolume (const Eref & e, double volume)
This is a little nasty. It calls buildDefaultMesh with the current numEntries. Should not be used if the mesh has been changed to something more interesting. Perhaps I need to do something like changeVolOfExistingMesh.
Definition at line 268 of file ChemCompt.cpp.
{
    // If the reac system is not solved, then explicitly do scaling
    vector< ObjId > tgtVec =
        e.element()->getMsgTargets( e.dataIndex(), voxelVolOut() );
    if ( tgtVec.size() == 0 )
    {
        vector< double > childConcs;
        getChildConcs( e, childConcs );
        if ( vSetVolumeNotRates( volume ) )
        {
            setChildConcs( e, childConcs, 0 );
        }
    }
    else
    {
        vSetVolumeNotRates( volume );
        voxelVolOut()->send( e, this->vGetVoxelVolume() );
    }
}
References Eref::dataIndex(), Eref::element(), getChildConcs(), Element::getMsgTargets(), SrcFinfo1< T >::send(), setChildConcs(), vGetVoxelVolume(), voxelVolOut(), and vSetVolumeNotRates().
Referenced by initCinfo().
setIsMembraneBound()
void ChemCompt::setIsMembraneBound (bool v)
Definition at line 420 of file ChemCompt.cpp.
{
    isMembraneBound_ = v;
}
References isMembraneBound_.
Referenced by initCinfo().
setMeshEntryVolume()
void ChemCompt::setMeshEntryVolume (unsigned int fid, double volume) virtual
Virtual function to assign volume of mesh Entry. Does nothing in most cases, but is operational in SpineMesh and PsdMesh.
Reimplemented in PsdMesh, and SpineMesh.
Definition at line 395 of file ChemCompt.cpp.
{
    cout << "Warning: ChemCompt::setMeshEntryVolume: Undefined except for PSD and spine mesh.\n";
}
Referenced by setOneVoxelVolume().
setMethod()
void ChemCompt::setMethod (string method)
Hint to system indicating method to be used on this compartment. Defaults to blank, which then leaves the decision to the calling function. Doesn't do anything unless the ChemCompt is parsed by the SimManager.
setNumEntries()
void ChemCompt::setNumEntries (unsigned int num)
Dummy function. The numEntries is only set by other functions that define compartment decomposition.
Definition at line 444 of file ChemCompt.cpp.
{
    this->innerSetNumEntries( num );
    // cout << "Warning: ChemCompt::setNumEntries: No effect. Use subclass-specific functions\nto build or resize mesh.\n";
}
References innerSetNumEntries().
Referenced by initCinfo().
setOneVoxelVolume()
void ChemCompt::setOneVoxelVolume (const Eref & e, unsigned int voxel, double volume)
Definition at line 389 of file ChemCompt.cpp.
{
    this->setMeshEntryVolume( dataIndex, volume );
}
References setMeshEntryVolume().
Referenced by initCinfo().
setVolumeNotRates()
void ChemCompt::setVolumeNotRates (double volume)
Returns true on success. Changes volume but does not notify any child objects. For some classes, this only works if the ChemCompt has just one voxel. It will return false if it can't handle it. This function will invalidate any concentration term in the model. If you don't know why you would want to do this, then you shouldn't use this function.",
Definition at line 430 of file ChemCompt.cpp.
{
    vSetVolumeNotRates( volume ); // Pass on to derived classes.
}
References vSetVolumeNotRates().
Referenced by initCinfo().
vGetEntireVolume()
virtual double ChemCompt::vGetEntireVolume () const pure virtual
Implemented in CubeMesh, CylMesh, EndoMesh, NeuroMesh, PresynMesh, PsdMesh, and SpineMesh.
Referenced by getEntireVolume().
vGetVoxelMidpoint()
virtual const vector< double > & ChemCompt::vGetVoxelMidpoint () const pure virtual
Virtual func so that derived classes can return voxel midpoint.
Implemented in CubeMesh, CylMesh, EndoMesh, NeuroMesh, PresynMesh, PsdMesh, and SpineMesh.
Referenced by getOneVoxelMidpoint(), getVoxelMidpoint(), and EndoMesh::vGetVoxelMidpoint().
vGetVoxelVolume()
virtual const vector< double > & ChemCompt::vGetVoxelVolume () const pure virtual
Virtual func so that derived classes can pass voxel volume back.
Implemented in CubeMesh, CylMesh, EndoMesh, NeuroMesh, PresynMesh, PsdMesh, and SpineMesh.
Referenced by Dsolve::calcLocalChan(), EndoMesh::getVoxelArea(), EndoMesh::getVoxelLength(), getVoxelVolume(), EndoMesh::matchMeshEntries(), Dsolve::reinit(), setEntireVolume(), and EndoMesh::vGetVoxelVolume().
voxelVolOut()
SrcFinfo1< vector< double > > * ChemCompt::voxelVolOut () static
Definition at line 17 of file ChemCompt.cpp.
{
    static SrcFinfo1< vector< double > > voxelVolOut( "voxelVolOut",
            "Sends updated voxel volume out to Ksolve, Gsolve, and Dsolve."
            "Used to request a recalculation of rates and of initial numbers."
                                                    );
    return &voxelVolOut;
}
References SrcFinfo1< T >::SrcFinfo1().
Referenced by initCinfo(), CubeMesh::setCoords(), and setEntireVolume().
vSetVolumeNotRates()
virtual bool ChemCompt::vSetVolumeNotRates (double volume) pure virtual
Virtual function for actually doing this.
Implemented in CubeMesh, CylMesh, EndoMesh, NeuroMesh, PresynMesh, PsdMesh, and SpineMesh.
Referenced by setEntireVolume(), and setVolumeNotRates().
Member Data Documentation
boundaries_
vector<Boundary> ChemCompt::boundaries_ private
Wrapper for self ptr.
The Boundaries are Element Fields. They appear as distinct Elements, though they are controlled by the ChemCompt. These are the interfaces between compartments, or just the boundaries of the current one. Each Boundary can be diffusive, reflective, or an interface where molecules in different compartments can talk to each other. All boundaries have a message to a Geometry. The Geometries may be shared, which is why the boundary isn't a Geometry itself. If it is an interface (diffusive or other) then the boundary also contains a message to the adjacent compartment.
Definition at line 336 of file ChemCompt.h.
entry_
MeshEntry ChemCompt::entry_ private
Definition at line 322 of file ChemCompt.h.
Referenced by ChemCompt(), and lookupEntry().
isMembraneBound_
bool ChemCompt::isMembraneBound_ private
Flag, set to True for meshes where each voxel is membrane bound. NeuroMesh and SpineMesh are false CubeMesh, CylMesh, and EndoMesh can be either. If they are membrane bound they can still interact via channels and cross-compartment reactions.
Definition at line 352 of file ChemCompt.h.
Referenced by ChemCompt(), getIsMembraneBound(), and setIsMembraneBound().
method_
string ChemCompt::method_ private
Hint to system indicating method to be used on this compartment. Defaults to blank, which then leaves the decision to the calling function.
Definition at line 343 of file ChemCompt.h.
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/mesh/ChemCompt.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/mesh/ChemCompt.cpp