MOOSE - Multiscale Object Oriented Simulation Environment: OpFunc0< T > Class Template Reference
OpFunc0< T > Class Template Reference
#include <OpFunc.h>
Public Member Functions
void op (const Eref &e) const
OpFunc0 (void(T::*func)())
Public Member Functions inherited from OpFunc0Base
bool checkFinfo (const Finfo *s) const
const OpFunc * makeHopFunc (HopIndex hopIndex) const
void opBuffer (const Eref &e, double *buf) const
Executes the OpFunc by converting args.
string rttiType () const
Public Member Functions inherited from OpFunc
OpFunc ()
unsigned int opIndex () const
virtual void opVecBuffer (const Eref &e, double *buf) const
Executes the OpFunc for all data by converting a vector of args.
bool setIndex (unsigned int i)
Used when rebuilding the Fid->OpFunc mapping.
virtual ~OpFunc ()
Private Attributes
void(T::* func_)()
Additional Inherited Members
Static Public Member Functions inherited from OpFunc
static const OpFunc * lookop (unsigned int opIndex)
static unsigned int rebuildOpIndex ()
cleans out the entire Ops vector. Returns size of orig vector.
Detailed Description
template<class T>
class OpFunc0< T >
Definition at line 13 of file OpFunc.h.
Constructor & Destructor Documentation
OpFunc0()
template<class T > OpFunc0< T >::OpFunc0 (void(T::*)() func) inline
Definition at line 16 of file OpFunc.h.
        : func_( func )
    {;}
References OpFunc0< T >::func_.
Referenced by moose::CompartmentBase::initCinfo(), TableBase::initCinfo(), Stoich::initCinfo(), ChemCompt::initCinfo(), SparseMsg::initCinfo(), Clock::initCinfo(), Shell::initCinfo(), and testSharedMsg().
Member Function Documentation
op()
template<class T > void OpFunc0< T >::op (const Eref & e) const inline virtual
Implements OpFunc0Base.
Definition at line 20 of file OpFunc.h.
    {
        (reinterpret_cast< T* >( e.data() )->*func_)();
    }
References Eref::data(), and OpFunc0< T >::func_.
Member Data Documentation
func_
template<class T > void(T::* OpFunc0< T >::func_) () private
Definition at line 25 of file OpFunc.h.
Referenced by OpFunc0< T >::op(), and OpFunc0< T >::OpFunc0().
The documentation for this class was generated from the following file:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/basecode/OpFunc.h