MOOSE - Multiscale Object Oriented Simulation Environment: Cinfo Class Reference
Cinfo Class Reference
#include <Cinfo.h>
Public Member Functions
bool banCreation () const
const Cinfo * baseCinfo () const
Cinfo ()
Cinfo (const Cinfo &other)
Cinfo (const std::string &name, const Cinfo *baseCinfo, Finfo **finfoArray, unsigned int nFinfos, DinfoBase *d, const std::string *doc=0, unsigned int numDoc=0, bool banCreation=false)
const string & destFinfoName (FuncId fid) const
const DinfoBase * dinfo () const
const Finfo * findFinfo (const string &name) const
const FinfoWrapper findFinfoWrapper (const string &name) const
const map< string, Finfo * > & finfoMap () const
string getBaseClass () const
Finfo * getDestFinfo (unsigned int i) const
string getDocs () const
string getDocsEntry (string key) const
Finfo * getFieldElementFinfo (unsigned int i) const
string getFinfoType (const Finfo *finfo) const
Finfo * getLookupFinfo (unsigned int i) const
unsigned int getNumDestFinfo () const
unsigned int getNumFieldElementFinfo () const
unsigned int getNumLookupFinfo () const
unsigned int getNumSharedFinfo () const
unsigned int getNumSrcFinfo () const
unsigned int getNumValueFinfo () const
const OpFunc * getOpFunc (FuncId fid) const
Finfo * getSharedFinfo (unsigned int i) const
Finfo * getSrcFinfo (unsigned int i) const
Finfo * getValueFinfo (unsigned int i) const
void init (Finfo **finfoArray, unsigned int nFinfos)
bool isA (const string &ancestor) const
const std::string & name () const
unsigned int numBindIndex () const
void overrideFunc (FuncId fid, const OpFunc *f)
void postCreationFunc (Id newId, Element *newElm) const
BindIndex registerBindIndex ()
void registerFinfo (Finfo *f)
FuncId registerOpFunc (const OpFunc *f)
void registerPostCreationFinfo (const Finfo *f)
void reportFids () const
void setNumFinfo (unsigned int v)
const string & srcFinfoName (BindIndex bid) const
~Cinfo ()
Static Public Member Functions
static const Cinfo * find (const std::string &name)
static const Cinfo * initCinfo ()
static void makeCinfoElements (Id parent)
static void rebuildOpIndex ()
Static Private Member Functions
static map< string, Cinfo * > & cinfoMap ()
Private Attributes
bool banCreation_
const Cinfo * baseCinfo_
vector< Finfo * > destFinfos_
Keep track of all DestFinfos.
const DinfoBase * dinfo_
std::map< std::string, std::string > doc_
vector< Finfo * > fieldElementFinfos_
Keep track of all FieldElementFinfos.
map< string, Finfo * > finfoMap_
vector< const OpFunc * > funcs_
vector< Finfo * > lookupFinfos_
Keep track of all LookupFinfos.
string name_
BindIndex numBindIndex_
vector< const Finfo * > postCreationFinfos_
vector< Finfo * > sharedFinfos_
Keep track of all SharedFinfos.
vector< Finfo * > srcFinfos_
Keep track of all SrcFinfos.
vector< Finfo * > valueFinfos_
Keep track of all ValueFinfos.
Static Private Attributes
static unsigned int numCoreOpFunc_ = 0
Detailed Description
Class to manage class information for all the other classes.
Definition at line 21 of file Cinfo.h.
Constructor & Destructor Documentation
Cinfo() [1/3]
Cinfo::Cinfo (const std::string & name, const Cinfo * baseCinfo, Finfo ** finfoArray, unsigned int nFinfos, DinfoBase * d, const std::string * doc = 0, unsigned int numDoc = 0, bool banCreation = false)
The Cinfo intializer is used for static initialization of all the MOOSE Cinfos. Each MOOSE class must set up a function to build its Cinfo. This function must be called statically in the MOOSE class .cpp file. Note how it takes the base *Cinfo as an argument. This lets us call the base Cinfo initializer when making each Cinfo class, thus ensuring the correct static initialization sequence, despite the somewhat loose semantics for this sequence in most C++ compilers.
Definition at line 21 of file Cinfo.cpp.
    : name_(name),
      baseCinfo_(baseCinfo),
      dinfo_(d),
      numBindIndex_(0),
      banCreation_(banCreation)
{
    if(cinfoMap().find(name) != cinfoMap().end()) {
        cout << "Warning: Duplicate Cinfo name " << name << endl;
    }
    init(finfoArray, nFinfos);
    cinfoMap()[name] = this;
    doc_.clear();
    if(doc && numDoc) {
        for(unsigned int i = 0; i < numDoc - 1; i += 2) {
            const string argName = doc[i];
            const string argVal = doc[i + 1];
            // cout << "in initCinfo for " << name << ", doc[" << i << "] = " <<
            // doc[i] << ", " << doc[i+1] << endl;
            // doc_[ doc[i] ] = doc[i+i];
            doc_[argName] = argVal;
        }
    }
}
References banCreation_, baseCinfo_, cinfoMap(), dinfo_, doc_, init(), name_, and numBindIndex_.
Referenced by PoolBase::initBufPoolCinfo(), initCinfo(), Finfo::initCinfo(), TestId::initCinfo(), Test::initCinfo(), CaConc::initCinfo(), CaConcBase::initCinfo(), ChanBase::initCinfo(), moose::Compartment::initCinfo(), moose::CompartmentBase::initCinfo(), DifBuffer::initCinfo(), DifBufferBase::initCinfo(), DifShell::initCinfo(), DifShellBase::initCinfo(), GapJunction::initCinfo(), HHChannel::initCinfo(), HHChannel2D::initCinfo(), HHChannelBase::initCinfo(), HHGate2D::initCinfo(), IntFire::initCinfo(), IzhikevichNrn::initCinfo(), Leakage::initCinfo(), MarkovChannel::initCinfo(), MarkovOdeSolver::initCinfo(), MarkovRateTable::initCinfo(), MarkovSolver::initCinfo(), MarkovSolverBase::initCinfo(), MgBlock::initCinfo(), MMPump::initCinfo(), Nernst::initCinfo(), Neuron::initCinfo(), NMDAChan::initCinfo(), RandSpike::initCinfo(), SpikeGen::initCinfo(), Spine::initCinfo(), SymCompartment::initCinfo(), SynChan::initCinfo(), moose::VClamp::initCinfo(), VectorTable::initCinfo(), Arith::initCinfo(), Group::initCinfo(), Interpol::initCinfo(), Interpol2D::initCinfo(), Mstring::initCinfo(), SocketStreamer::initCinfo(), SpikeStats::initCinfo(), Stats::initCinfo(), StimulusTable::initCinfo(), Streamer::initCinfo(), Table::initCinfo(), TableBase::initCinfo(), TimeTable::initCinfo(), Variable::initCinfo(), DiffAmp::initCinfo(), PIDController::initCinfo(), PulseGen::initCinfo(), RC::initCinfo(), Dsolve::initCinfo(), Cell::initCinfo(), HSolve::initCinfo(), ZombieCaConc::initCinfo(), ZombieCompartment::initCinfo(), ZombieHHChannel::initCinfo(), moose::AdExIF::initCinfo(), moose::AdThreshIF::initCinfo(), moose::ExIF::initCinfo(), moose::IntFireBase::initCinfo(), moose::IzhIF::initCinfo(), moose::LIF::initCinfo(), moose::QIF::initCinfo(), ConcChan::initCinfo(), Enz::initCinfo(), EnzBase::initCinfo(), MMenz::initCinfo(), Reac::initCinfo(), Species::initCinfo(), Gsolve::initCinfo(), Ksolve::initCinfo(), Stoich::initCinfo(), Boundary::initCinfo(), ChemCompt::initCinfo(), CubeMesh::initCinfo(), CylMesh::initCinfo(), EndoMesh::initCinfo(), MeshEntry::initCinfo(), NeuroMesh::initCinfo(), PresynMesh::initCinfo(), PsdMesh::initCinfo(), SpineMesh::initCinfo(), PostMaster::initCinfo(), DiagonalMsg::initCinfo(), Msg::initCinfo(), OneToAllMsg::initCinfo(), OneToOneDataIndexMsg::initCinfo(), OneToOneMsg::initCinfo(), SingleMsg::initCinfo(), SparseMsg::initCinfo(), Clock::initCinfo(), TestSched::initCinfo(), Neutral::initCinfo(), Shell::initCinfo(), Adaptor::initCinfo(), GraupnerBrunel2012CaPlasticitySynHandler::initCinfo(), SeqSynHandler::initCinfo(), SimpleSynHandler::initCinfo(), STDPSynapse::initCinfo(), STDPSynHandler::initCinfo(), Synapse::initCinfo(), SynHandlerBase::initCinfo(), Annotator::initCinfo(), PoolBase::initPoolBaseCinfo(), and PoolBase::initPoolCinfo().
Cinfo() [2/3]
Cinfo::Cinfo ()
This initializer is used only as a dummy, to keep Dinfo happy
Definition at line 48 of file Cinfo.cpp.
    : name_("dummy"),
      baseCinfo_(0),
      dinfo_(0),
      numBindIndex_(0),
      banCreation_(false)
{
    ;
}
References banCreation_, baseCinfo_, dinfo_, name_, and numBindIndex_.
Cinfo() [3/3]
Cinfo::Cinfo (const Cinfo & other)
This is also a dummy initializer for Dinfo.
Definition at line 58 of file Cinfo.cpp.
    : name_("dummy"),
      baseCinfo_(0),
      dinfo_(0),
      numBindIndex_(0),
      banCreation_(false)
{
    ;
}
References banCreation_, baseCinfo_, dinfo_, name_, and numBindIndex_.
~Cinfo()
Cinfo::~Cinfo ()
Definition at line 80 of file Cinfo.cpp.
{
    ;
}  // The dinfos are statically allocated, we don't free them.
Member Function Documentation
banCreation()
bool Cinfo::banCreation () const
True if this class should never be instantiated in MOOSE. This may happen if it is a pure virtual class, or if this Cinfo is for a FieldElement which cannot be created in isolation but only as a child of another class.
Definition at line 272 of file Cinfo.cpp.
{
    return banCreation_;
}
References banCreation_.
Referenced by Shell::doCreate().
baseCinfo()
const Cinfo * Cinfo::baseCinfo () const
Definition at line 251 of file Cinfo.cpp.
{
    return baseCinfo_;
}
References baseCinfo_.
Referenced by pymoose::getClassFieldsDoc(), and DestFinfo::registerFinfo().
cinfoMap()
map< string, Cinfo * > & Cinfo::cinfoMap () static private
Definition at line 348 of file Cinfo.cpp.
{
    static map<std::string, Cinfo*> lookup_;
    return lookup_;
}
Referenced by Cinfo(), find(), makeCinfoElements(), and rebuildOpIndex().
destFinfoName()
const string & Cinfo::destFinfoName (FuncId fid) const
Returns the name of the DestFinfo having the specified FuncId, on this Cinfo. Returns "" on failure.
Definition at line 602 of file Cinfo.cpp.
{
    static const string err = "";
    for(vector<Finfo*>::const_iterator i = destFinfos_.begin();
        i != destFinfos_.end(); ++i) {
        const DestFinfo* df = dynamic_cast<const DestFinfo*>(*i);
        assert(df);
        if(df->getFid() == fid) {
            return df->name();
        }
    }
    if(baseCinfo_)
        return baseCinfo_->destFinfoName(fid);
    cout << "Error: Cinfo::destFinfoName( " << fid << " ): not found\n";
    return err;
}
References baseCinfo_, destFinfoName(), destFinfos_, DestFinfo::getFid(), and Finfo::name().
Referenced by destFinfoName(), Msg::getDestFieldsOnE1(), Msg::getDestFieldsOnE2(), Element::getMsgTargetAndFunctions(), and testMsgSrcDestFields().
dinfo()
const DinfoBase * Cinfo::dinfo () const
Returns the Dinfo, which manages creation and destruction of the data, and knows about its size.
Definition at line 316 of file Cinfo.cpp.
{
    return dinfo_;
}
References dinfo_.
Referenced by buildFinfoElement(), DataElement::DataElement(), DataElement::DataElement(), makeCinfoElements(), DataElement::resize(), DataElement::zombieSwap(), and DataElement::~DataElement().
find()
const Cinfo * Cinfo::find (const std::string & name) static
Finds the Cinfo with the specified name.
Definition at line 243 of file Cinfo.cpp.
{
    map<string, Cinfo*>::iterator i = cinfoMap().find(name);
    if(i != cinfoMap().end())
        return i->second;
    return 0;
}
References cinfoMap().
Referenced by Stoich::allocateModelObject(), Shell::doCreate(), Dsolve::fillConcChans(), findAllConnectedCompartments(), Cell::findCompt(), pymoose::getClassDoc(), getComptParent(), pymoose::getDoc(), pymoose::getFieldNames(), pymoose::getFieldTypeDict(), getSlaveEnable(), Shell::innerCreate(), Stoich::installAndUnschedFunc(), Stoich::installAndUnschedFuncRate(), Stoich::installAndUnschedFuncReac(), Enz::setSolver(), testSyncSynapseSize(), Stoich::unZombifyModel(), and Stoich::zombifyModel().
findFinfo()
const Finfo * Cinfo::findFinfo (const string & name) const
Finds Finfo by name in the list for this class, ignoring any element-specific fields. Returns 0 on failure.
Looks up Finfo from name.
Definition at line 259 of file Cinfo.cpp.
{
    auto i = finfoMap_.find(name);
    if(i != finfoMap_.end())
        return i->second;
    return 0;
}
References finfoMap_.
Referenced by addClockMsg(), ReadKkit::addmsg(), Shell::adopt(), Stoich::allocateModelObject(), ReadCell::buildCompartment(), SetGet::checkSet(), Neutral::child(), Neutral::children(), convertConcToNumRateUsingMesh(), HSolve::deleteIncomingMessages(), Shell::doAddMsg(), Shell::dropClockMsgs(), enzDest(), Dsolve::fillConcChans(), findAllConnectedCompartments(), findFinfoWrapper(), findFuncMsgSrc(), findMeshOfEnz(), findParentComptOfReac(), pymoose::MooseVec::getAttribute(), getComptParent(), pymoose::getDoc(), pymoose::getFieldGeneric(), Neutral::getMsgDestFunctions(), Neutral::getMsgDests(), Neutral::getNeighbors(), getSlaveEnable(), Shell::innerAddMsg(), innerCopyMsgs(), Shell::innerMove(), Stoich::installAndUnschedFunc(), Stoich::installAndUnschedFuncRate(), Stoich::installAndUnschedFuncReac(), Neutral::isDescendant(), isOffSolverReac(), localGet(), Neutral::parent(), Neutral::path(), FieldElementFinfoBase::postCreationFunc(), HSolveActive::readSynapses(), DestFinfo::registerFinfo(), pymoose::MooseVec::setAttribute(), pymoose::MooseVec::setAttrOneToAll(), pymoose::MooseVec::setAttrOneToOne(), pymoose::setFieldGeneric(), Enz::setSolver(), MMenz::setSolver(), Element::setTick(), SetGet::strGet(), SetGet::strSet(), HSolveUtils::targets(), testAssortedMsg(), testCinfoFields(), testCreateMsg(), testFibonacci(), testFinfoFields(), testMsgField(), testMsgSrcDestFields(), testSendMsg(), testSendSpike(), testSharedMsg(), testShellAddMsg(), testSparseMsg(), testSyncSynapseSize(), testTwoReacGetNeighbors(), tryParent(), and FieldElement::zombieSwap().
findFinfoWrapper()
const FinfoWrapper Cinfo::findFinfoWrapper (const string & name) const
Definition at line 267 of file Cinfo.cpp.
{
    return FinfoWrapper(findFinfo(name));
}
References findFinfo(), and FinfoWrapper::FinfoWrapper().
finfoMap()
const map< string, Finfo * > & Cinfo::finfoMap () const
Returns the map between name and field info
Definition at line 311 of file Cinfo.cpp.
{
    return finfoMap_;
}
References finfoMap_.
Referenced by Element::showFields(), and Element::showMsg().
getBaseClass()
string Cinfo::getBaseClass () const
Return the name of the base class
Definition at line 423 of file Cinfo.cpp.
{
    if(baseCinfo_)
        return baseCinfo_->name();
    else
        return "none";
}
References baseCinfo_, and name().
Referenced by initCinfo(), and testCinfoFields().
getDestFinfo()
Finfo * Cinfo::getDestFinfo (unsigned int i) const
Return the specified DestFinfo
Definition at line 462 of file Cinfo.cpp.
{
    if(i >= getNumDestFinfo())
        return &dummy;
    if(baseCinfo_) {
        if(i >= baseCinfo_->getNumDestFinfo())
            return destFinfos_[i - baseCinfo_->getNumDestFinfo()];
        else
            return const_cast<Cinfo*>(baseCinfo_)->getDestFinfo(i);
    }
    return destFinfos_[i];
}
References baseCinfo_, destFinfos_, dummy, getDestFinfo(), and getNumDestFinfo().
Referenced by Neutral::getDestFields(), getDestFinfo(), pymoose::getFinfoDict(), and testCinfoFields().
getDocs()
string Cinfo::getDocs () const
Return the documentation string
Definition at line 399 of file Cinfo.cpp.
{
    ostringstream doc;
    for(auto ii = doc_.cbegin(); ii != doc_.cend(); ++ii) {
        doc << endl
            << std::setw(15) << std::left << ii->first << ": " << ii->second;
    }
    return doc.str();
}
References doc_.
Referenced by initCinfo(), and testCinfoFields().
getDocsEntry()
string Cinfo::getDocsEntry (string key) const
Get a specifi entry from the docs map
Definition at line 409 of file Cinfo.cpp.
{
    if (auto result = doc_.find(key); result != doc_.end()){
    return result->second;
    } else {
    return "";
    }
}
References doc_.
Referenced by pymoose::getClassDoc().
getFieldElementFinfo()
Finfo * Cinfo::getFieldElementFinfo (unsigned int i) const
Return the specified FieldElementFinfo
Definition at line 554 of file Cinfo.cpp.
{
    if(i >= getNumFieldElementFinfo())
        return &dummy;
    if(baseCinfo_) {
        if(i >= baseCinfo_->getNumFieldElementFinfo())
            return fieldElementFinfos_[i -
                                       baseCinfo_->getNumFieldElementFinfo()];
        else
            return const_cast<Cinfo*>(baseCinfo_)->getFieldElementFinfo(i);
    }
    return fieldElementFinfos_[i];
}
References baseCinfo_, dummy, fieldElementFinfos_, getFieldElementFinfo(), and getNumFieldElementFinfo().
Referenced by getFieldElementFinfo(), and pymoose::getFinfoDict().
getFinfoType()
string Cinfo::getFinfoType (const Finfo * f) const
Returns the type of Finfo.
@Synopsis Finfo derived class, using dynamic_cast figure out.
@Param f const Finfo*
@Returns String representing the polymorphic type of Finfo.
Definition at line 157 of file Cinfo.cpp.
{
    if(dynamic_cast<const DestFinfo*>(f)) {
        return "DestFinfo";
    }
    else if(dynamic_cast<const SrcFinfo*>(f)) {
        return "SrcFinfo";
    }
    else if(dynamic_cast<const ValueFinfoBase*>(f)) {
        return "ValueFinfo";
    }
    else if(dynamic_cast<const LookupValueFinfoBase*>(f)) {
        return "LookupValueFinfo";
    }
    else if(dynamic_cast<const SharedFinfo*>(f)) {
        return "SharedFinfo";
    }
    else if(dynamic_cast<const FieldElementFinfoBase*>(f)) {
        return "FieldElementFinfo";
    }
    return "";
}
Referenced by pymoose::MooseVec::getAttribute(), pymoose::getDoc(), and pymoose::getFieldGeneric().
getLookupFinfo()
Finfo * Cinfo::getLookupFinfo (unsigned int i) const
Return the specified LookupFinfo
Definition at line 508 of file Cinfo.cpp.
{
    if(i >= getNumLookupFinfo())
        return &dummy;
    if(baseCinfo_) {
        if(i >= baseCinfo_->getNumLookupFinfo())
            return lookupFinfos_[i - baseCinfo_->getNumLookupFinfo()];
        else
            return const_cast<Cinfo*>(baseCinfo_)->getLookupFinfo(i);
    }
    return lookupFinfos_[i];
}
References baseCinfo_, dummy, getLookupFinfo(), getNumLookupFinfo(), and lookupFinfos_.
Referenced by pymoose::getFinfoDict(), getLookupFinfo(), and testCinfoFields().
getNumDestFinfo()
unsigned int Cinfo::getNumDestFinfo () const
Return number of DestFinfo
Definition at line 476 of file Cinfo.cpp.
{
    if(baseCinfo_)
        return destFinfos_.size() + baseCinfo_->getNumDestFinfo();
    else
        return destFinfos_.size();
}
References baseCinfo_, destFinfos_, and getNumDestFinfo().
Referenced by Neutral::getDestFields(), getDestFinfo(), pymoose::getFinfoDict(), getNumDestFinfo(), and testCinfoFields().
getNumFieldElementFinfo()
unsigned int Cinfo::getNumFieldElementFinfo () const
Return number of FieldElementFinfos
Definition at line 569 of file Cinfo.cpp.
{
    if(baseCinfo_)
        return fieldElementFinfos_.size() +
               baseCinfo_->getNumFieldElementFinfo();
    else
        return fieldElementFinfos_.size();
}
References baseCinfo_, fieldElementFinfos_, and getNumFieldElementFinfo().
Referenced by getFieldElementFinfo(), pymoose::getFinfoDict(), and getNumFieldElementFinfo().
getNumLookupFinfo()
unsigned int Cinfo::getNumLookupFinfo () const
Return number of LookupFinfo
Definition at line 522 of file Cinfo.cpp.
{
    if(baseCinfo_)
        return lookupFinfos_.size() + baseCinfo_->getNumLookupFinfo();
    else
        return lookupFinfos_.size();
}
References baseCinfo_, getNumLookupFinfo(), and lookupFinfos_.
Referenced by pymoose::getFinfoDict(), getLookupFinfo(), getNumLookupFinfo(), and testCinfoFields().
getNumSharedFinfo()
unsigned int Cinfo::getNumSharedFinfo () const
Return number of SharedFinfos
Definition at line 545 of file Cinfo.cpp.
{
    if(baseCinfo_)
        return sharedFinfos_.size() + baseCinfo_->getNumSharedFinfo();
    else
        return sharedFinfos_.size();
}
References baseCinfo_, getNumSharedFinfo(), and sharedFinfos_.
Referenced by pymoose::getFinfoDict(), getNumSharedFinfo(), getSharedFinfo(), and testCinfoFields().
getNumSrcFinfo()
unsigned int Cinfo::getNumSrcFinfo () const
Return number of SrcFinfos
Definition at line 453 of file Cinfo.cpp.
{
    if(baseCinfo_)
        return srcFinfos_.size() + baseCinfo_->getNumSrcFinfo();
    else
        return srcFinfos_.size();
}
References baseCinfo_, getNumSrcFinfo(), and srcFinfos_.
Referenced by pymoose::getFinfoDict(), getNumSrcFinfo(), Neutral::getSourceFields(), getSrcFinfo(), and testCinfoFields().
getNumValueFinfo()
unsigned int Cinfo::getNumValueFinfo () const
Return number of ValueFinfo
Definition at line 499 of file Cinfo.cpp.
{
    if(baseCinfo_)
        return valueFinfos_.size() + baseCinfo_->getNumValueFinfo();
    else
        return valueFinfos_.size();
}
References baseCinfo_, getNumValueFinfo(), and valueFinfos_.
Referenced by pymoose::getFinfoDict(), getNumValueFinfo(), Neutral::getValueFields(), getValueFinfo(), and testCinfoFields().
getOpFunc()
const OpFunc * Cinfo::getOpFunc (FuncId fid) const
looks up OpFunc by FuncId
Definition at line 280 of file Cinfo.cpp.
{
    if(fid < funcs_.size())
        return funcs_[fid];
    return 0;
}
References funcs_.
Referenced by GetEpFunc1< T, L, A >::op(), GetOpFunc1< T, L, A >::op(), putFuncsInOrder(), and Element::putOffNodeTargetsInDigest().
getSharedFinfo()
Finfo * Cinfo::getSharedFinfo (unsigned int i) const
Return the specified SharedFinfo
Definition at line 531 of file Cinfo.cpp.
{
    if(i >= getNumSharedFinfo())
        return &dummy;
    if(baseCinfo_) {
        if(i >= baseCinfo_->getNumSharedFinfo())
            return sharedFinfos_[i - baseCinfo_->getNumSharedFinfo()];
        else
            return const_cast<Cinfo*>(baseCinfo_)->getSharedFinfo(i);
    }
    return sharedFinfos_[i];
}
References baseCinfo_, dummy, getNumSharedFinfo(), getSharedFinfo(), and sharedFinfos_.
Referenced by pymoose::getFinfoDict(), getSharedFinfo(), and testCinfoFields().
getSrcFinfo()
Finfo * Cinfo::getSrcFinfo (unsigned int i) const
Return the specified SrcFinfo
Definition at line 438 of file Cinfo.cpp.
{
    if(i >= getNumSrcFinfo())
        return 0;
    if(baseCinfo_) {
        if(i >= baseCinfo_->getNumSrcFinfo())
            return srcFinfos_[i - baseCinfo_->getNumSrcFinfo()];
        else
            return baseCinfo_->getSrcFinfo(i);
        // return const_cast< Cinfo* >( baseCinfo_ )->getSrcFinfo( i );
    }
    return srcFinfos_[i];
}
References baseCinfo_, getNumSrcFinfo(), getSrcFinfo(), and srcFinfos_.
Referenced by pymoose::getFinfoDict(), Neutral::getSourceFields(), getSrcFinfo(), and testCinfoFields().
getValueFinfo()
Finfo * Cinfo::getValueFinfo (unsigned int i) const
Return the specified ValueFinfo
Definition at line 485 of file Cinfo.cpp.
{
    if(i >= getNumValueFinfo())
        return &dummy;
    if(baseCinfo_) {
        if(i >= baseCinfo_->getNumValueFinfo())
            return valueFinfos_[i - baseCinfo_->getNumValueFinfo()];
        else
            return const_cast<Cinfo*>(baseCinfo_)->getValueFinfo(i);
    }
    return valueFinfos_[i];
}
References baseCinfo_, dummy, getNumValueFinfo(), getValueFinfo(), and valueFinfos_.
Referenced by pymoose::getFinfoDict(), Neutral::getValueFields(), getValueFinfo(), and testCinfoFields().
init()
void Cinfo::init (Finfo ** finfoArray, unsigned int nFinfos)
Initializes the Cinfo. Must be called exactly once for each Cinfo.
init: initializes the Cinfo. Must be called just once
Definition at line 92 of file Cinfo.cpp.
{
    if(baseCinfo_) {
        // Copy over base Finfos.
        numBindIndex_ = baseCinfo_->numBindIndex_;
        finfoMap_ = baseCinfo_->finfoMap_;
        funcs_ = baseCinfo_->funcs_;
        postCreationFinfos_ = baseCinfo_->postCreationFinfos_;
    }
    for(unsigned int i = 0; i < nFinfos; i++) {
        registerFinfo(finfoArray[i]);
    }
}
References baseCinfo_, finfoMap_, funcs_, numBindIndex_, postCreationFinfos_, and registerFinfo().
Referenced by Cinfo().
initCinfo()
const Cinfo * Cinfo::initCinfo () static
Initializer for the MOOSE fields for Cinfo
Definition at line 366 of file Cinfo.cpp.
{
    // Field Definitions
    static ReadOnlyValueFinfo<Cinfo, string> docs("docs", "Documentation",
                                                  &Cinfo::getDocs);
    static ReadOnlyValueFinfo<Cinfo, string> baseClass(
        "baseClass", "Name of base class", &Cinfo::getBaseClass);
    static string doc[] = {"Name",        "Cinfo",
                           "Author",      "Upi Bhalla",
                           "Description", "Class information object."};
    static Finfo* cinfoFinfos[] = {
        &docs,       // ReadOnlyValue
        &baseClass,  // ReadOnlyValue
    };
    static Dinfo<Cinfo> dinfo;
    static Cinfo cinfoCinfo("Cinfo", Neutral::initCinfo(), cinfoFinfos,
                            sizeof(cinfoFinfos) / sizeof(Finfo*), &dinfo, doc,
                            sizeof(doc) / sizeof(string));
    return &cinfoCinfo;
}
References Cinfo(), getBaseClass(), getDocs(), Neutral::initCinfo(), and ReadOnlyValueFinfo< T, F >::ReadOnlyValueFinfo().
Referenced by makeCinfoElements().
isA()
bool Cinfo::isA (const string & ancestor) const
Returns true if the current Cinfo is derived from the ancestor
Definition at line 321 of file Cinfo.cpp.
{
    if(ancestor == "Neutral")
        return true;
    const Cinfo* base = this;
    while(base && base != Neutral::initCinfo()) {
        if(ancestor == base->name_)
            return true;
        base = base->baseCinfo_;
    }
    return false;
}
References baseCinfo_, Neutral::initCinfo(), and name_.
Referenced by addSpine(), assignParam(), Dsolve::buildMeshJunctions(), Dsolve::buildNeuroMeshJunctions(), PresynMesh::buildOnDendrites(), PresynMesh::buildOnSpineHeads(), ReadKkit::buildSumTotal(), NeuroNode::buildTree(), Dsolve::calcJunction(), HSolve::deepSearchForCompartment(), ReadCspace::deployParameters(), Neutral::destroy(), doClassSpecificMessaging(), Shell::doLoadModel(), estimateDefaultVol(), Neuron::evalExprForElist(), fillSegIndex(), fillSegments(), VoxelPoolsBase::filterCrossRateTerms(), filterWildcards(), findAllConnectedCompartments(), findFuncMsgSrc(), ChemCompt::getChildConcs(), getCompt(), getComptParent(), Spine::getHead(), Spine::getHeadDiameter(), Spine::getHeadLength(), getParentFromMsg(), Stoich::getProxyPools(), getReactantVols(), Spine::getShaft(), Spine::getShaftDiameter(), Spine::getShaftLength(), getSlaveEnable(), Neutral::isA(), isOffSolverReac(), isPartOfDend(), ReadKkit::loadTab(), Stoich::locateOffSolverReacs(), ReadCspace::makePlots(), Dsolve::makePoolMapFromElist(), matchInsideBrace(), ReadCspace::printMol(), ReadCell::read(), Neuron::setChannelDistribution(), ChemCompt::setChildConcs(), KsolveBase::setCompartment(), Gsolve::setCompartment(), Dsolve::setCompartment(), Stoich::setCompartment(), Gsolve::setConcInit(), Gsolve::setDsolve(), Ksolve::setDsolve(), Stoich::setDsolve(), Spine::setHeadDiameter(), Spine::setHeadLength(), Spine::setHeadVolume(), Stoich::setKsolve(), Gsolve::setN(), HSolve::setSeed(), Spine::setShaftDiameter(), Spine::setShaftLength(), Enz::setSolver(), MMenz::setSolver(), Reac::setSolver(), Neuron::setSpineAndPsdMesh(), Dsolve::setStoich(), SteadyState::setStoich(), Gsolve::setStoich(), Ksolve::setStoich(), EndoMesh::setSurround(), ReadKkit::setupSlaveMsg(), testIsA(), Stoich::unZombifyModel(), Stoich::updateRatesAfterRemesh(), ZombieCaConc::vSetSolver(), ZombieCompartment::vSetSolver(), and ZombieHHChannel::vSetSolver().
makeCinfoElements()
void Cinfo::makeCinfoElements (Id parent) static
Utility function used at init to create the inspection Elements for each of the Cinfos.
Definition at line 206 of file Cinfo.cpp.
{
    static Dinfo<Cinfo> dummy;
    vector<unsigned int> dims(1, 0);
    vector<Id> cinfoElements;
    for(map<string, Cinfo*>::iterator i = cinfoMap().begin();
        i != cinfoMap().end(); ++i) {
        Id id = Id::nextId();
        char* data = reinterpret_cast<char*>(i->second);
        Element* e = new GlobalDataElement(id, Cinfo::initCinfo(), i->first);
        Cinfo::initCinfo()->dinfo()->assignData(e->data(0), 1, data, 1);
        // Cinfo* temp = reinterpret_cast< Cinfo* >( e->data( 0 ) );
        Shell::adopt(parent, id, 0);
        cinfoElements.push_back(id);
        // cout << "Cinfo::makeCinfoElements: parent= " << parent << ", Id = "
        // << id << ", name = " << i->first << endl;
    }
    vector<Id>::iterator j = cinfoElements.begin();
    for(map<string, Cinfo*>::iterator i = cinfoMap().begin();
        i != cinfoMap().end(); ++i) {
        buildFinfoElement(*j, i->second->srcFinfos_, "srcFinfo");
        buildFinfoElement(*j, i->second->destFinfos_, "destFinfo");
        buildFinfoElement(*j, i->second->valueFinfos_, "valueFinfo");
        buildFinfoElement(*j, i->second->lookupFinfos_, "lookupFinfo");
        buildFinfoElement(*j, i->second->sharedFinfos_, "sharedFinfo");
        buildFinfoElement(*j, i->second->fieldElementFinfos_,
                          "fieldElementFinfo");
        j++;
    }
}
References Shell::adopt(), DinfoBase::assignData(), buildFinfoElement(), cinfoMap(), Element::data(), destFinfos_, dinfo(), fieldElementFinfos_, GlobalDataElement::GlobalDataElement(), initCinfo(), lookupFinfos_, Id::nextId(), sharedFinfos_, srcFinfos_, and valueFinfos_.
Referenced by init(), and pymoose::initShell().
name()
const std::string & Cinfo::name () const
Return the name of the Cinfo
Definition at line 301 of file Cinfo.cpp.
{
    return name_;
}
References name_.
Referenced by ReadCell::addCaConc(), ReadCell::addCanonicalChannel(), ReadCell::addSpikeGen(), pymoose::createElementFromPath(), HSolve::deleteIncomingMessages(), pymoose::MooseVec::dtype(), pymoose::fieldDocFormatted(), getBaseClass(), Neutral::getClass(), pymoose::getClassFieldsDoc(), innerCopyElements(), Shell::innerCreate(), matchInsideBrace(), Dsolve::setCompartment(), Gsolve::setDsolve(), Ksolve::setDsolve(), PoolBase::setSolvers(), EndoMesh::setSurround(), Element::setTick(), HSolveUtils::targets(), Stoich::unZombifyModel(), and Element::zombieSwap().
numBindIndex()
unsigned int Cinfo::numBindIndex () const
Finds the funcId by name. Returns 0 on failure. const FuncId findFuncId(const string& name) const; Number of SrcMsgs in total. Each has a unique number to bind to an entry in the msgBinding vector in the Element.
Definition at line 306 of file Cinfo.cpp.
{
    return numBindIndex_;
}
References numBindIndex_.
Referenced by Element::Element(), Neutral::getOutgoingMsgs(), and Eref::msgDigest().
overrideFunc()
void Cinfo::overrideFunc (FuncId fid, const OpFunc * f)
Used in derived classes, to replace the original OpFunc with the new one.
Definition at line 113 of file Cinfo.cpp.
{
    assert(funcs_.size() > fid);
    funcs_[fid] = f;
}
References funcs_.
Referenced by DestFinfo::registerFinfo().
postCreationFunc()
void Cinfo::postCreationFunc (Id newId, Element * newElm) const
Handles any operations that must be done after an Element is created. Scans through all Finfos as they are the ones to manage such requests. Examples are to create FieldElements.
Definition at line 185 of file Cinfo.cpp.
{
    for(vector<const Finfo*>::const_iterator i = postCreationFinfos_.begin();
        i != postCreationFinfos_.end(); ++i)
        (*i)->postCreationFunc(newId, newElm);
}
References postCreationFinfos_, and Finfo::postCreationFunc().
Referenced by DataElement::DataElement().
rebuildOpIndex()
void Cinfo::rebuildOpIndex () static
Ensures that the Func Ids are always in a fixed order, regardless of the sequence of static initialization of Cinfos.
Definition at line 622 of file Cinfo.cpp.
{
    numCoreOpFunc_ = OpFunc::rebuildOpIndex();
    unsigned int num = 0;
    for(map<string, Cinfo*>::iterator i = cinfoMap().begin();
        i != cinfoMap().end(); ++i) {
        vector<const OpFunc*>& vec = i->second->funcs_;
        for(vector<const OpFunc*>::iterator j = vec.begin(); j != vec.end();
            ++j) {
            OpFunc* of = const_cast<OpFunc*>(*j);
            num += of->setIndex(num);
        }
    }
    numCoreOpFunc_ = num;
}
References cinfoMap(), funcs_, numCoreOpFunc_, OpFunc::rebuildOpIndex(), and OpFunc::setIndex().
Referenced by init(), and pymoose::initShell().
registerBindIndex()
BindIndex Cinfo::registerBindIndex ()
Returns the next free value for BindIndex, and keeps track of the total number set up.
Definition at line 119 of file Cinfo.cpp.
{
    return numBindIndex_++;
}
References numBindIndex_.
Referenced by SrcFinfo::registerFinfo().
registerFinfo()
void Cinfo::registerFinfo (Finfo * f)
registerFinfo: Puts Finfo information into Cinfo, and updates fields on Finfo as necessary.
Definition at line 124 of file Cinfo.cpp.
{
    finfoMap_[f->name()] = f;
    f->registerFinfo(this);
    if(dynamic_cast<DestFinfo*>(f)) {
        destFinfos_.push_back(f);
    }
    else if(dynamic_cast<SrcFinfo*>(f)) {
        srcFinfos_.push_back(f);
    }
    else if(dynamic_cast<ValueFinfoBase*>(f)) {
        valueFinfos_.push_back(f);
    }
    else if(dynamic_cast<LookupValueFinfoBase*>(f)) {
        lookupFinfos_.push_back(f);
    }
    else if(dynamic_cast<SharedFinfo*>(f)) {
        sharedFinfos_.push_back(f);
    }
    else if(dynamic_cast<FieldElementFinfoBase*>(f)) {
        fieldElementFinfos_.push_back(f);
    }
}
References destFinfos_, fieldElementFinfos_, finfoMap_, lookupFinfos_, Finfo::name(), Finfo::registerFinfo(), sharedFinfos_, srcFinfos_, and valueFinfos_.
Referenced by init(), ElementValueFinfo< T, F >::registerFinfo(), ReadOnlyElementValueFinfo< T, F >::registerFinfo(), FieldElementFinfoBase::registerFinfo(), LookupElementValueFinfo< T, L, F >::registerFinfo(), ReadOnlyLookupElementValueFinfo< T, L, F >::registerFinfo(), LookupValueFinfo< T, L, F >::registerFinfo(), ReadOnlyLookupValueFinfo< T, L, F >::registerFinfo(), SharedFinfo::registerFinfo(), ValueFinfo< T, F >::registerFinfo(), and ReadOnlyValueFinfo< T, F >::registerFinfo().
registerOpFunc()
FuncId Cinfo::registerOpFunc (const OpFunc * f)
Registers the OpFunc, assigns it a FuncId and returns the FuncId.
Definition at line 106 of file Cinfo.cpp.
{
    FuncId ret = funcs_.size();
    funcs_.push_back(f);
    return ret;
}
References funcs_.
Referenced by DestFinfo::registerFinfo().
registerPostCreationFinfo()
void Cinfo::registerPostCreationFinfo (const Finfo * f)
Registers a finfo as needing post-creation work
Definition at line 180 of file Cinfo.cpp.
{
    postCreationFinfos_.push_back(f);
}
References postCreationFinfos_.
Referenced by FieldElementFinfoBase::registerFinfo().
reportFids()
void Cinfo::reportFids () const
Utility function for debugging
Definition at line 334 of file Cinfo.cpp.
{
    for(map<string, Finfo*>::const_iterator i = finfoMap_.begin();
        i != finfoMap_.end(); ++i) {
        const DestFinfo* df = dynamic_cast<const DestFinfo*>(i->second);
        if(df) {
            cout << df->getFid() << "   " << df->name() << endl;
        }
    }
}
References finfoMap_, DestFinfo::getFid(), and Finfo::name().
setNumFinfo()
void Cinfo::setNumFinfo (unsigned int v)
Dummy function. We never allow this assignment.
Definition at line 579 of file Cinfo.cpp.
{
    ;
}
srcFinfoName()
const string & Cinfo::srcFinfoName (BindIndex bid) const
Returns the name of the SrcFinfo having the specified BindIndex, on this Cinfo. Returns "" on failure.
Definition at line 585 of file Cinfo.cpp.
{
    static const string err = "";
    for(vector<Finfo*>::const_iterator i = srcFinfos_.begin();
        i != srcFinfos_.end(); ++i) {
        const SrcFinfo* sf = dynamic_cast<const SrcFinfo*>(*i);
        assert(sf);
        if(sf->getBindIndex() == bid) {
            return sf->name();
        }
    }
    if(baseCinfo_)
        return baseCinfo_->srcFinfoName(bid);
    cout << "Error: Cinfo::srcFinfoName( " << bid << " ): not found\n";
    return err;
}
References baseCinfo_, SrcFinfo::getBindIndex(), Finfo::name(), srcFinfoName(), and srcFinfos_.
Referenced by Element::getMsgSourceAndSender(), Msg::getSrcFieldsOnE1(), Msg::getSrcFieldsOnE2(), srcFinfoName(), and testMsgSrcDestFields().
Member Data Documentation
banCreation_
bool Cinfo::banCreation_ private
Definition at line 297 of file Cinfo.h.
Referenced by banCreation(), Cinfo(), Cinfo(), and Cinfo().
baseCinfo_
const Cinfo* Cinfo::baseCinfo_ private
Definition at line 291 of file Cinfo.h.
Referenced by baseCinfo(), Cinfo(), Cinfo(), Cinfo(), destFinfoName(), getBaseClass(), getDestFinfo(), getFieldElementFinfo(), getLookupFinfo(), getNumDestFinfo(), getNumFieldElementFinfo(), getNumLookupFinfo(), getNumSharedFinfo(), getNumSrcFinfo(), getNumValueFinfo(), getSharedFinfo(), getSrcFinfo(), getValueFinfo(), init(), isA(), and srcFinfoName().
destFinfos_
vector<Finfo*> Cinfo::destFinfos_ private
Keep track of all DestFinfos.
Definition at line 308 of file Cinfo.h.
Referenced by destFinfoName(), getDestFinfo(), getNumDestFinfo(), makeCinfoElements(), and registerFinfo().
dinfo_
const DinfoBase* Cinfo::dinfo_ private
Definition at line 292 of file Cinfo.h.
Referenced by Cinfo(), Cinfo(), Cinfo(), and dinfo().
doc_
std::map<std::string, std::string> Cinfo::doc_ private
Definition at line 295 of file Cinfo.h.
Referenced by Cinfo(), getDocs(), and getDocsEntry().
fieldElementFinfos_
vector<Finfo*> Cinfo::fieldElementFinfos_ private
Keep track of all FieldElementFinfos.
Definition at line 320 of file Cinfo.h.
Referenced by getFieldElementFinfo(), getNumFieldElementFinfo(), makeCinfoElements(), and registerFinfo().
finfoMap_
map<string, Finfo*> Cinfo::finfoMap_ private
This looks up Finfos by name.
Definition at line 302 of file Cinfo.h.
Referenced by findFinfo(), finfoMap(), init(), registerFinfo(), and reportFids().
funcs_
vector<const OpFunc*> Cinfo::funcs_ private
Definition at line 328 of file Cinfo.h.
Referenced by getOpFunc(), init(), overrideFunc(), rebuildOpIndex(), and registerOpFunc().
lookupFinfos_
vector<Finfo*> Cinfo::lookupFinfos_ private
Keep track of all LookupFinfos.
Definition at line 314 of file Cinfo.h.
Referenced by getLookupFinfo(), getNumLookupFinfo(), makeCinfoElements(), and registerFinfo().
name_
string Cinfo::name_ private
Definition at line 287 of file Cinfo.h.
Referenced by Cinfo(), Cinfo(), Cinfo(), isA(), and name().
numBindIndex_
BindIndex Cinfo::numBindIndex_ private
Definition at line 294 of file Cinfo.h.
Referenced by Cinfo(), Cinfo(), Cinfo(), init(), numBindIndex(), and registerBindIndex().
numCoreOpFunc_
unsigned int Cinfo::numCoreOpFunc_ = 0 static private
Definition at line 332 of file Cinfo.h.
Referenced by rebuildOpIndex().
postCreationFinfos_
vector<const Finfo*> Cinfo::postCreationFinfos_ private
These are special Finfos which have to be invoked after the Element is created, and their postCreationFuncs called. They are typically things like FieldElementFinfos.
Definition at line 327 of file Cinfo.h.
Referenced by init(), postCreationFunc(), and registerPostCreationFinfo().
sharedFinfos_
vector<Finfo*> Cinfo::sharedFinfos_ private
Keep track of all SharedFinfos.
Definition at line 317 of file Cinfo.h.
Referenced by getNumSharedFinfo(), getSharedFinfo(), makeCinfoElements(), and registerFinfo().
srcFinfos_
vector<Finfo*> Cinfo::srcFinfos_ private
Keep track of all SrcFinfos.
Definition at line 305 of file Cinfo.h.
Referenced by getNumSrcFinfo(), getSrcFinfo(), makeCinfoElements(), registerFinfo(), and srcFinfoName().
valueFinfos_
vector<Finfo*> Cinfo::valueFinfos_ private
Keep track of all ValueFinfos.
Definition at line 311 of file Cinfo.h.
Referenced by getNumValueFinfo(), getValueFinfo(), makeCinfoElements(), and registerFinfo().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/basecode/Cinfo.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/basecode/Cinfo.cpp