MOOSE - Multiscale Object Oriented Simulation Environment: Id Class Reference
Id Class Reference
#include <Id.h>
Public Member Functions
void bindIdToElement (Element *e)
void destroy () const
Element * element () const
Synonym for Id::operator()()
Eref eref () const
Id ()
Id (const ObjId &oi)
Id (const std::string &path)
Id (unsigned int id)
bool operator!= (const Id &other) const
bool operator< (const Id &other) const
bool operator== (const Id &other) const
std::string path () const
unsigned int value () const
void zeroOut () const
~Id ()
Static Public Member Functions
static void clearAllElements ()
static std::string id2str (Id id)
static bool isValid (Id id)
static bool isValid (unsigned int id)
static Id nextId ()
static unsigned int numIds ()
static Id str2Id (const std::string &s)
Static Private Member Functions
static vector< Element * > & elements ()
Private Attributes
unsigned int id_
Friends
ostream & operator<< (ostream &s, const Id &i)
istream & operator>> (istream &s, Id &i)
Detailed Description
This class manages id lookups for elements. Ids provide a uniform handle for every object, independent of which node they are located on.
Definition at line 21 of file Id.h.
Constructor & Destructor Documentation
Id() [1/4]
Id::Id ()
Returns the root Id
Definition at line 18 of file Id.cpp.
    : id_(0)
{
    ;
}
References id_.
Referenced by ReadCell::addChannel(), ReadCell::addChannelMessage(), SharedFinfo::addMsg(), addSpine(), Shell::adopt(), ReadKkit::assignPoolCompartments(), ReadKkit::assignReacCompartments(), benchmarkMsg(), Dsolve::build(), ReadSwc::build(), ReadKkit::buildChan(), ReadCell::buildChannels(), ReadCell::buildCompartment(), Neuron::buildElist(), ReadKkit::buildEnz(), buildFromProto(), ReadKkit::buildGraph(), ReadKkit::buildGroup(), ReadKkit::buildInfo(), ReadKkit::buildPlot(), ReadKkit::buildPool(), ReadKkit::buildReac(), Neuron::buildSegmentTree(), ReadKkit::buildStim(), ReadKkit::buildSumTotal(), ReadKkit::buildTable(), Dsolve::calcJunction(), ReadKkit::call(), Cell::Cell(), checkForSpine(), SetGet::checkSet(), Neutral::child(), Shell::cleanSimulation(), pymoose::createElementFromPath(), Element::destroyElementTree(), doClassSpecificMessaging(), Shell::doCopy(), Shell::doCreate(), Shell::doLoadModel(), Shell::doMove(), ReadCspace::expandEnzyme(), ReadCspace::expandReaction(), extractCompts(), fillSegIndex(), fillSegments(), ReadCell::findChannel(), findFuncMsgSrc(), findModelParent(), findParentComptOfReac(), ReadKkit::findSumTotSrc(), getComptParent(), Neuron::getExprElist(), Neuron::getExprVal(), Spine::getHead(), getParentFromMsg(), Stoich::getPoolByIndex(), Ksolve::getRateVecFromId(), Ksolve::getRateVecFromPath(), Cell::getSetup(), Spine::getShaft(), pymoose::getShellPtr(), Gsolve::Gsolve(), HHChannelBase::HHChannelBase(), Id(), init(), Msg::initMsgManagers(), pymoose::initShell(), NeuroMesh::innerBuildDefaultMesh(), innerFind(), Shell::innerMove(), Neuron::installSpines(), Neutral::isDescendant(), isOffSolverReac(), VoxelPoolsBase::isVoxelJunctionPresent(), kineticsHasReactions(), Ksolve::Ksolve(), KsolveBase::KsolveBase(), pymoose::loadModelInternal(), ReadKkit::loadTab(), makeCompt(), makeCompt(), ReadCspace::makeMolecule(), ReadCspace::makePlots(), Dsolve::makePoolMapFromElist(), makeReacTest(), makeStandardElements(), Dsolve::mapDiffPoolsBetweenDsolves(), Dsolve::mapXfersBetweenDsolves(), NeuroNode::NeuroNode(), ObjId::ObjId(), ObjId::ObjId(), Neutral::parent(), Neutral::path(), NeuroMesh::putSomaAtStart(), ReadCell::read(), ReadKkit::read(), ReadCell::ReadCell(), ReadCspace::ReadCspace(), ReadCell::readData(), ReadKkit::ReadKkit(), ReadCspace::readModelString(), ReadCell::readScript(), Cell::reinit(), Neuron::scaleBufAndRates(), Neuron::setChannelDistribution(), Gsolve::setDsolve(), Ksolve::setDsolve(), Stoich::setDsolve(), Stoich::setElist(), Stoich::setKsolve(), setMethod(), Neutral::setName(), HSolve::setPath(), Stoich::setReacSystemPath(), Enz::setSolver(), Cell::setupf(), ReadKkit::setupSlaveMsg(), SpineEntry::SpineEntry(), ReadCell::startGraftCell(), SteadyState::SteadyState(), Stoich::Stoich(), testAssortedMsg(), testBuildStoich(), testCalcJunction(), testCellDiffn(), testChildren(), testCinfoElements(), testClockMessaging(), testCopy(), testCopyFieldElement(), testCubeMesh(), testCylDiffn(), testCylDiffnWithStoich(), testDescendant(), testFibonacci(), testFilterOffNodeTargets(), testFindModelParent(), testGetMsg(), testInterNodeOps(), testMMenz(), testMMenzProcess(), testMove(), testMpiFibonacci(), testMsgElementListing(), testObjIdToAndFromPath(), testPoolVolumeScaling(), testReacVolumeScaling(), testReadKkit(), ReadCspace::testReadModel(), testReMesh(), testRunGsolve(), testRunKsolve(), testRunKsolveWithLSODA(), testSetGetExtField(), testSetupReac(), testShellAddMsg(), testShellParserCreateDelete(), testShellParserQuit(), testShellParserStart(), testShellSetGet(), testSmallCellDiffn(), testStats(), testStrSet(), testSyncSynapseSize(), testTable(), testTaperingCylDiffn(), testTreeTraversal(), testTwoReacGetNeighbors(), testVolScaling(), testWildcard(), tryParent(), HSolve::unzombify(), Stoich::unZombifyModel(), writeEnz(), writeKkit(), Stoich::zombifyModel(), and Stoich::zombifyPoolFuncWithScaling().
Id() [2/4]
Id::Id (unsigned int id)
Creates an id with the specified Element number
Definition at line 25 of file Id.cpp.
                      : id_(id)
{
    ;
}
References id_.
Referenced by addClockMsg(), Shell::addClockMsgs(), Conv< Id >::buf2val(), Dsolve::calcJunction(), Shell::doReinit(), Shell::doStart(), Shell::doStop(), Element::dropAllMsgsFromSrc(), estimateSimTimes(), Neutral::getDt(), Neuron::getSpineFromCompartment(), PsdMesh::handlePsdList(), SpineMesh::handleSpineList(), HHGate2D::HHGate2D(), HHGateBase::HHGateBase(), init(), pymoose::initShell(), Stoich::installAndUnschedFunc(), Stoich::installAndUnschedFuncRate(), Stoich::installAndUnschedFuncReac(), isDoingReinit(), Shell::isRunning(), makeReacTest(), Dsolve::mapDiffPoolsBetweenDsolves(), Dsolve::mapXfersBetweenDsolves(), nextId(), FuncRate::operator()(), FuncReac::operator()(), Streamer::reinit(), Table::reinit(), Clock::reportClock(), Dsolve::setStoich(), Element::setTick(), SocketStreamer::SocketStreamer(), storeFunctionMsgs(), testCopyFieldElement(), testFibonacci(), testGetMsg(), testHopFunc(), testObjIdToAndFromPath(), testPoolVolumeScaling(), testReacVolumeScaling(), testSendSpike(), testSetGetExtField(), testSetGetSynapse(), testSetGetVec(), testSetRepeat(), testShellAddMsg(), testSparseMsg(), testSyncSynapseSize(), testTreeTraversal(), testTwoReacGetNeighbors(), HHChannel::vCreateGate(), HHChannel2D::vCreateGate(), HHChannelF::vCreateGate(), and HHChannelF2D::vCreateGate().
Id() [3/4]
Id::Id (const std::string & path)
Returns an id found by traversing the specified path
Definition at line 30 of file Id.cpp.
{
    Shell* shell = reinterpret_cast<Shell*>(Id().eref().data());
    assert(shell);
    id_ = shell->doFind(path).id.id_;
}
References Eref::data(), Shell::doFind(), eref(), Id(), ObjId::id, and id_.
Referenced by buildFromProto(), ReadKkit::call(), ReadKkit::findCompartmentsFromAnnotation(), findModelParent(), HSolveUtils::gates(), Ksolve::getRateVecFromPath(), Neuron::installSpines(), ReadKkit::loadTab(), ReadCspace::makePlots(), makeStandardElements(), ReadKkit::read(), ReadCell::ReadCell(), ReadCspace::readModelString(), ReadCell::readScript(), Neuron::setChannelDistribution(), setMethod(), HSolve::setPath(), Cell::setupf(), ReadKkit::setupSlaveMsg(), ReadCell::startGraftCell(), str2Id(), Conv< Id >::str2val(), testCinfoElements(), testMsgElementListing(), ReadCspace::testReadModel(), testReMesh(), testRunGsolve(), testRunKsolve(), testRunKsolveWithLSODA(), testSetupReac(), and writeKkit().
Id() [4/4]
Id::Id (const ObjId & oi)
Downconverts an OjbId to an Id
Definition at line 37 of file Id.cpp.
                      : id_(oi.id.id_)
{
    ;
}
References ObjId::id, and id_.
~Id()
Id::~Id () inline
Destroys an Id. Doesn't do anything much.
Definition at line 49 of file Id.h.
    {
    }
Member Function Documentation
bindIdToElement()
void Id::bindIdToElement (Element * e)
The specified element is placed into current id.
Definition at line 150 of file Id.cpp.
{
    if (elements().size() <= id_) {
        if (elements().size() % 1000 == 0) {
            elements().reserve(elements().size() + 1000);
        }
        elements().resize(id_ + 1, 0);
    }
    assert(elements()[id_] == 0);
    /*
    if ( elements()[ id_ ] != 0 )
        cout << "Warning: assigning Element to existing id " << id_ << "\n";
        */
    elements()[id_] = e;
    // cout << "Id::bindIdToElement '" << e->getName() << "' = " << id_ << endl;
}
References elements(), and id_.
Referenced by Element::Element().
clearAllElements()
void Id::clearAllElements () static
Used to clean up all Elements when the simulation is terminated
Definition at line 200 of file Id.cpp.
{
    for (vector<Element*>::iterator i = elements().begin();
         i != elements().end(); ++i) {
        if (*i) {
            (*i)->clearAllMsgs();
            delete *i;
        }
    }
}
References Element::clearAllMsgs(), and elements().
Referenced by main().
destroy()
void Id::destroy () const
Cleanly deletes the associated Element, and zeroes out contents of elements vector at the location pointed to by this->id_.
Definition at line 176 of file Id.cpp.
{
    if (elements()[id_]) {
        // cout << "Id::destroy '" << elements()[ id_ ]->getName() << "' = " <<
        // id_ << endl;
        delete elements()[id_];
        elements()[id_] = 0;
        // Put id_ on 'available' list
    } else {
        cout << "Warning: Id::destroy: " << id_ << " already zeroed\n";
    }
}
References elements(), and id_.
Referenced by Element::destroyElementTree(), Cell::setupf(), testArith(), testFibonacci(), testLookupSetGet(), testMpiFibonacci(), testMsgSrcDestFields(), testSetGetExtField(), testSharedMsg(), and testShellParserStart().
element()
Element * Id::element () const
Synonym for Id::operator()()
Returns the Element pointed to by the id If it is off-node, returns an allocated wrapper element with postmaster and id information. Calling func has to free it. This wrapper element may also point to UNKNOWN NODE, in which case the master node IdManager has to figure out where it belongs. Returns 0 on failure. Deprecated. Element* operator()() const; Returns the Element pointed to by the Id. Perhaps cleaner to use than operator()() as it is an explicit function.
Here we work with a single big array of all ids. Off-node elements are represented by their postmasters. When we hit a postmaster we put the id into a special field on it. Note that this is horrendously thread-unsafe.
Definition at line 115 of file Id.cpp.
{
    return elements()[id_];
}
References elements(), and id_.
Referenced by ReadCell::addCaConc(), ReadCell::addCanonicalChannel(), ReadCell::addChannel(), ReadCell::addChannelMessage(), addClockMsg(), Shell::addClockMsgs(), ReadKkit::addmsg(), ReadCell::addSpikeGen(), addSpine(), Shell::adopt(), allChildren(), Stoich::allocateModelObject(), assignParam(), ObjId::bad(), ReadSwc::build(), ReadCell::buildChannels(), ReadCell::buildCompartment(), buildFromProto(), Dsolve::buildMeshJunctions(), Dsolve::buildNeuroMeshJunctions(), ReadKkit::buildSumTotal(), Dsolve::calcJunction(), checkArg1(), checkChildren(), checkForSpine(), SetGet::checkSet(), ReadKkit::convertKineticsToGroup(), DiagonalMsg::copy(), OneToAllMsg::copy(), OneToOneDataIndexMsg::copy(), OneToOneMsg::copy(), SingleMsg::copy(), SparseMsg::copy(), ObjId::data(), FieldElement::data(), HSolve::deepSearchForCompartment(), HSolve::deleteIncomingMessages(), ReadCspace::deployParameters(), Element::destroyElementTree(), Shell::doAddMsg(), doClassSpecificMessaging(), Shell::doLoadModel(), Shell::doMove(), Element::dropAllMsgsFromSrc(), ObjId::element(), ObjId::eref(), estimateDefaultVol(), fillSegIndex(), fillSegments(), VoxelPoolsBase::filterCrossRateTerms(), NeuroMesh::filterSpines(), NeuroNode::filterSpines(), findAllConnectedCompartments(), ReadKkit::findCompartmentsFromAnnotation(), findFuncMsgSrc(), findMeshOfEnz(), findModelParent(), DiagonalMsg::findOtherEnd(), findParentComptOfReac(), NeuroNode::findStartNode(), pymoose::VecLookupField::get(), ChemCompt::getChildConcs(), getComptParent(), Spine::getHead(), Spine::getHeadDiameter(), Spine::getHeadLength(), FieldElement::getNode(), FieldElement::getNumOnNode(), getParentFromMsg(), Stoich::getProxyPools(), Spine::getShaft(), Spine::getShaftDiameter(), Spine::getShaftLength(), getSlaveEnable(), LookupField< L, A >::getVec(), hasScaleFormula(), Shell::innerAddMsg(), innerCopyElements(), innerCopyMsgs(), Shell::innerMove(), Shell::innerUseClock(), Stoich::installAndUnschedFunc(), Stoich::installAndUnschedFuncRate(), Stoich::installAndUnschedFuncReac(), ObjId::isDataHere(), isDoingReinit(), FieldElement::isGlobal(), ObjId::isGlobal(), ObjId::isOffNode(), isOffSolverReac(), Shell::isRunning(), ReadKkit::loadTab(), FieldElement::localDataStart(), Stoich::locateOffSolverReacs(), main(), ReadCspace::makePlots(), Dsolve::mapDiffPoolsBetweenDsolves(), Dsolve::mapXfersBetweenDsolves(), FieldElement::numData(), FieldElement::numField(), FieldElement::numLocalData(), FieldElementFinfoBase::postCreationFunc(), ReadCspace::printEnz(), ReadCspace::printMol(), ReadCspace::printReac(), NeuroMesh::putSomaAtStart(), FieldElement::rawIndex(), ReadCell::read(), ReadCell::ReadCell(), HSolveActive::readSynapses(), SocketStreamer::reinit(), Streamer::reinit(), FieldElement::resizeField(), SrcFinfo2< T1, T2 >::sendTo(), SrcFinfo1< T >::sendTo(), pymoose::VecLookupField::set(), Neuron::setChannelDistribution(), ChemCompt::setChildConcs(), KsolveBase::setCompartment(), Gsolve::setCompartment(), Dsolve::setCompartment(), Stoich::setCompartment(), Gsolve::setDsolve(), Ksolve::setDsolve(), Stoich::setDsolve(), Spine::setHeadDiameter(), Spine::setHeadLength(), Spine::setHeadVolume(), Stoich::setKsolve(), Dsolve::setPath(), HSolve::setSeed(), Spine::setShaftDiameter(), Spine::setShaftLength(), Dsolve::setStoich(), SteadyState::setStoich(), Gsolve::setStoich(), Ksolve::setStoich(), ReadKkit::setupSlaveMsg(), showFields(), singleLevelWildcard(), FieldElement::startDataIndex(), HSolveUtils::targets(), test2ArgSetVec(), testAssortedMsg(), testCellDiffn(), testCopy(), testCopyFieldElement(), testCreateMsg(), testCylDiffnWithStoich(), testFilterOffNodeTargets(), testGet(), testMsgElementListing(), testMsgField(), testMsgSrcDestFields(), testSendMsg(), testSendSpike(), testSetGet(), testSetGetDouble(), testSetGetSynapse(), testSetGetVec(), testSetRepeat(), testSharedMsg(), testSmallCellDiffn(), testSparseMsg(), testStrGet(), testStrSet(), testSyncSynapseSize(), testTaperingCylDiffn(), testTreeTraversal(), testTwoReacGetNeighbors(), tryParent(), HSolve::unzombify(), Stoich::unZombifyModel(), Stoich::unZombifyPools(), Stoich::updateRatesAfterRemesh(), pymoose::VecElementField::VecElementField(), ZombieCaConc::vSetSolver(), ZombieCompartment::vSetSolver(), ZombieHHChannel::vSetSolver(), Stoich::zombifyModel(), and Stoich::zombifyPoolFuncWithScaling().
elements()
vector< Element * > & Id::elements () static private
Definition at line 57 of file Id.cpp.
{
    static vector<Element*> e;
    return e;
}
Referenced by bindIdToElement(), clearAllElements(), destroy(), element(), eref(), isValid(), isValid(), nextId(), numIds(), and zeroOut().
eref()
Eref Id::eref () const
Returns the Eref to the element plus index
Definition at line 127 of file Id.cpp.
{
    return Eref(elements()[id_], 0);
    // return Eref( elements()[ id_ ], index_ );
}
References elements(), Eref::Eref(), and id_.
Referenced by ReadCell::addChannelMessage(), addClockMsg(), addSpine(), VoxelPools::advance(), ReadKkit::assignPoolCompartments(), benchmarkMsg(), ReadSwc::build(), Neuron::buildElist(), ReadKkit::buildEnz(), buildFromProto(), ReadKkit::buildSumTotal(), Neutral::buildTree(), Dsolve::calcJunction(), Dsolve::calcLocalChan(), Cell::Cell(), checkChildren(), Cell::children(), HSolve::children(), SteadyState::classifyState(), Shell::cleanSimulation(), ReadKkit::convertKineticsToGroup(), OneToOneDataIndexMsg::copy(), OneToOneMsg::copy(), ReadCspace::deployParameters(), doClassSpecificMessaging(), ReadCspace::expandEnzyme(), ReadCspace::expandReaction(), ReadKkit::findCompartmentsFromAnnotation(), HSolveUtils::gates(), ChemCompt::getChildConcs(), getCompt(), Neuron::getExprElist(), Neuron::getExprVal(), VoxelPools::getMethod(), pymoose::getShellPtr(), PsdMesh::handlePsdList(), SpineMesh::handleSpineList(), Id(), MarkovSolverBase::init(), init(), pymoose::initShell(), innerCopyElements(), Neutral::isDescendant(), isDoingReinit(), Shell::isRunning(), kineticsHasReactions(), Shell::launchParser(), makeCompt(), makeCompt(), ReadCspace::makeMolecule(), ReadCspace::makePlots(), makeReacTest(), makeStandardElements(), Dsolve::mapChansBetweenDsolves(), Dsolve::mapDiffPoolsBetweenDsolves(), mapVoxelsBetweenMeshes(), Dsolve::mapXfersBetweenDsolves(), ObjId::ObjId(), path(), FieldElementFinfoBase::postCreationFunc(), ReadCspace::printMol(), HSolveUtils::rates(), ReadCell::ReadCell(), ReadKkit::ReadKkit(), HSolveActive::readSynapses(), Streamer::reinit(), Table::reinit(), Dsolve::reinit(), Clock::reportClock(), HSolveActive::sendValues(), ChemCompt::setChildConcs(), Gsolve::setDsolve(), Ksolve::setDsolve(), Stoich::setDsolve(), Stoich::setElist(), MarkovRateTable::setInt2dChildTable(), Stoich::setKsolve(), Dsolve::setStoich(), SteadyState::setStoich(), Gsolve::setStoich(), Ksolve::setStoich(), Cell::setupSolver(), MarkovRateTable::setVtChildTable(), Element::showFields(), SocketStreamer::SocketStreamer(), storeFunctionMsgs(), testAssortedMsg(), testBuildStoich(), testCalcJunction(), testCellDiffn(), testChildren(), testClockMessaging(), testCopy(), testCopyFieldElement(), testCreateMsg(), testCubeMesh(), testCylDiffn(), testCylDiffnWithStoich(), testDescendant(), testFibonacci(), testFilterOffNodeTargets(), testFindModelParent(), testGetMsg(), testHopFunc(), testInterNodeOps(), testMMenz(), testMMenzProcess(), testMove(), testMpiFibonacci(), testMsgElementListing(), testMsgField(), testMsgSrcDestFields(), testObjIdToAndFromPath(), testPoolVolumeScaling(), testReacVolumeScaling(), testReadKkit(), ReadCspace::testReadModel(), testReMesh(), testRunGsolve(), testRunKsolve(), testRunKsolveWithLSODA(), testSendMsg(), testSendSpike(), testSetupReac(), testSharedMsg(), testShellAddMsg(), testShellParserCreateDelete(), testShellParserQuit(), testShellParserStart(), testShellSetGet(), testSmallCellDiffn(), testStats(), testSyncSynapseSize(), testTable(), testTaperingCylDiffn(), testTreeTraversal(), testTwoReacGetNeighbors(), testVolScaling(), testWildcard(), HSolve::unzombify(), Stoich::updateRatesAfterRemesh(), verifyKids(), ZombieCaConc::vSetSolver(), ZombieCompartment::vSetSolver(), ZombieHHChannel::vSetSolver(), and HSolve::zombify().
id2str()
string Id::id2str (Id id) static
Returns a string holding the ascii value of the id_ .
Definition at line 68 of file Id.cpp.
{
    return id.path();
}
References path().
isValid() [1/2]
static bool Id::isValid (Id id) inline static
Definition at line 149 of file Id.h.
    {
        return (id.id_ < elements().size()) && (elements()[id.id_] != 0);
    }
References elements(), and id_.
isValid() [2/2]
static bool Id::isValid (unsigned int id) inline static
Definition at line 154 of file Id.h.
    {
        return (id < elements().size()) && (elements()[id] != 0);
    }
References elements().
nextId()
Id Id::nextId () static
Reserves an id for assigning to an Element. Each time it is called a new id is reserved, even if previous ones have not been used yet.
Definition at line 134 of file Id.cpp.
{
    // Should really look up 'available' list.
    // Should really put the returned value onto the 'reserved' list
    // so they don't go dangling.
    Id ret(elements().size());
    elements().push_back(0);
    return ret;
}
References elements(), and Id().
Referenced by buildFinfoElement(), Shell::doCopy(), Shell::doCreate(), init(), Msg::initMsgManagers(), pymoose::initShell(), innerCopyElements(), Cinfo::makeCinfoElements(), FieldElementFinfoBase::postCreationFunc(), Cell::setupSolver(), showFields(), test2ArgSetVec(), testArith(), testCreateMsg(), testFibonacci(), testGet(), testLookupSetGet(), testMsgField(), testMsgSrcDestFields(), testSendMsg(), testSendSpike(), testSetGet(), testSetGetDouble(), testSetGetExtField(), testSetGetSynapse(), testSetGetVec(), testSetRepeat(), testSharedMsg(), testSparseMsg(), testStrGet(), and testStrSet().
numIds()
unsigned int Id::numIds () static
Returns the number of Ids in use.
Definition at line 145 of file Id.cpp.
{
    return elements().size();
}
References elements().
operator!=()
bool Id::operator!= (const Id & other) const inline
Definition at line 133 of file Id.h.
    {
        // return id_ != other.id_ || index_ != other.index_;
        return id_ != other.id_;
    }
References id_.
Referenced by ReadCell::addChannel(), SharedFinfo::addMsg(), ReadKkit::assignPoolCompartments(), ReadKkit::assignReacCompartments(), ReadSwc::build(), ReadKkit::buildChan(), ReadCell::buildChannels(), ReadCell::buildCompartment(), ReadKkit::buildEnz(), ReadKkit::buildGraph(), ReadKkit::buildGroup(), ReadKkit::buildInfo(), ReadKkit::buildPlot(), ReadKkit::buildPool(), ReadKkit::buildReac(), ReadKkit::buildStim(), ReadKkit::buildTable(), Dsolve::calcJunction(), ReadKkit::call(), ReadKkit::convertKineticsToGroup(), Shell::doCopy(), Shell::doCreate(), Shell::doMove(), ReadCspace::expandEnzyme(), extractCompts(), fillSegIndex(), fillSegments(), Ksolve::getRateVecFromId(), Ksolve::getRateVecFromPath(), Neutral::isDescendant(), isOffSolverReac(), kineticsHasReactions(), ReadKkit::loadTab(), Stoich::locateOffSolverReacs(), makeCompt(), ReadCspace::makePlots(), makeStandardElements(), Dsolve::mapDiffPoolsBetweenDsolves(), Dsolve::mapXfersBetweenDsolves(), ObjId::operator!=(), Neutral::path(), ReadKkit::read(), ReadCspace::readModelString(), Neuron::setChannelDistribution(), setMethod(), ReadKkit::setupSlaveMsg(), testCalcJunction(), testCinfoElements(), testCopy(), testMsgElementListing(), testReadKkit(), testReMesh(), testSyncSynapseSize(), testTreeTraversal(), writeEnz(), writeKkit(), Stoich::zombifyModel(), and Stoich::zombifyPoolFuncWithScaling().
operator<()
bool Id::operator< (const Id & other) const inline
Definition at line 139 of file Id.h.
    {
        //  return ( id_ < other.id_ ) ||
        //      ( id_ == other.id_ && index_ < other.index_ );
        return (id_ < other.id_);
    }
References id_.
Referenced by extractCompts(), ObjId::operator<(), and sortByShaftIds().
operator==()
bool Id::operator== (const Id & other) const inline
Definition at line 127 of file Id.h.
    {
        // return id_ == other.id_ && index_ == other.index_;
        return id_ == other.id_;
    }
References id_.
Referenced by Shell::adopt(), ReadKkit::assignPoolCompartments(), ReadKkit::assignReacCompartments(), Dsolve::build(), ReadSwc::build(), ReadCell::buildChannels(), buildFromProto(), Neuron::buildSegmentTree(), ReadKkit::buildSumTotal(), HHGateBase::checkOriginal(), SetGet::checkSet(), Shell::destroy(), Element::destroyElementTree(), doClassSpecificMessaging(), Shell::doMove(), extractCompts(), findModelParent(), NeuroMesh::getDendVoxelsOnCompartment(), Neuron::getParentCompartmentOfSpine(), Ksolve::getRateVecFromPath(), Neuron::getSpineFromCompartment(), NeuroMesh::getSpineVoxelsOnCompartment(), init(), pymoose::initShell(), Shell::innerMove(), Neuron::installSpines(), Neutral::isDescendant(), HHGate2D::isOriginalChannel(), HHGateBase::isOriginalChannel(), HHGate2D::isOriginalGate(), HHGateBase::isOriginalGate(), VoxelPoolsBase::isVoxelJunctionPresent(), pymoose::loadModelInternal(), makeStandardElements(), ObjId::operator<(), ObjId::operator==(), Neutral::parent(), NeuroMesh::putSomaAtStart(), ReadCell::readData(), ReadCell::readScript(), Cell::reinit(), Neuron::scaleBufAndRates(), Gsolve::setDsolve(), Ksolve::setDsolve(), Stoich::setElist(), Neutral::setName(), HSolve::setPath(), Stoich::setReacSystemPath(), Neuron::setSpineAndPsdMesh(), Cell::setupf(), testChildren(), testCopy(), testCopyFieldElement(), testFindModelParent(), testMove(), testObjIdToAndFromPath(), testTreeTraversal(), testTwoReacGetNeighbors(), verifyKids(), and Stoich::zombifyPoolFuncWithScaling().
path()
string Id::path () const
Returns the full pathname of the object on the id.
Definition at line 74 of file Id.cpp.
{
    string ret = Neutral::path(eref());
    // FIXME: Monday 09 March 2020 12:30:27 PM IST, Dilawar Singh
    // This beaks the path comparison. Getting x.path from x returned in a
    // list by moose.wildcardFind() and getting path from here doesn't math
    // when this is enabled.
    // If we want to remove [0] then it should be done globally and not just
    // here.
    // Trim off trailing []
    assert(ret.length() > 0);
    while (ret.back() == ']') {
        size_t pos = ret.find_last_of('[');
        if (pos != string::npos && pos > 0) {
            ret = ret.substr(0, pos);
        }
    }
    return ret;
}
References eref(), and Neutral::path().
Referenced by SocketStreamer::addTable(), ReadCell::buildCompartment(), Dsolve::buildMeshJunctions(), Dsolve::buildNeuroMeshJunctions(), PresynMesh::buildOnDendrites(), PresynMesh::buildOnSpineHeads(), Neuron::buildSegmentTree(), NeuroNode::buildTree(), HHGateBase::checkOriginal(), SetGet::checkSet(), ReadKkit::childPoolVol(), Shell::cleanSimulation(), Dsolve::convertIdToPoolIndex(), HHChannel::destroyGate(), HHChannel2D::destroyGate(), HHChannelF::destroyGate(), HHChannelF2D::destroyGate(), diagnoseTree(), Shell::doCopy(), NeuroNode::findConnectedCompartments(), findModelParent(), HSolveUtils::gates(), Field< A >::get(), LookupField< L, A >::get(), Neutral::getMsgDestFunctions(), Neutral::getMsgDests(), Neutral::getNeighbors(), LookupField< L, A >::getVec(), id2str(), HHChannel::innerCreateGate(), HHChannel2D::innerCreateGate(), HHChannelF::innerCreateGate(), HHChannelF2D::innerCreateGate(), HHChannel::innerDestroyGate(), HHChannel2D::innerDestroyGate(), HHChannelF::innerDestroyGate(), HHChannelF2D::innerDestroyGate(), installDummy(), isOffSolverReac(), ReadCspace::makePlots(), makeStandardElements(), Ksolve::print(), printJunction(), ReadKkit::read(), ReadCell::ReadCell(), ReadCspace::readModelString(), ReadCell::readScript(), Streamer::reinit(), Table::reinit(), SocketStreamer::removeTable(), HHGate::setAlpha(), HHGate::setBeta(), Gsolve::setDsolve(), Ksolve::setDsolve(), Stoich::setFunctionExpr(), setMethod(), HHGate::setMinfinity(), Neutral::setName(), HSolve::setSeed(), Reac::setSolver(), Neuron::setSpineAndPsdMesh(), HHGate::setTableA(), HHGate::setTau(), Cell::setupf(), ReadCell::startGraftCell(), storePlotMsgs(), testMsgElementListing(), ReadCspace::testReadModel(), testTreeTraversal(), Conv< Id >::val2str(), HHChannel::vCreateGate(), HHChannel2D::vCreateGate(), HHChannelF::vCreateGate(), HHChannelF2D::vCreateGate(), ZombieCaConc::vSetSolver(), ZombieCompartment::vSetSolver(), ZombieHHChannel::vSetSolver(), writeEnz(), writeGroup(), writeKkit(), and writePlot().
str2Id()
Id Id::str2Id (const std::string & s) static
Returns an id whose value is string-converted from the specified string.
Static func to extract an id from a string. We need to accept ids out of the existing range, but it would be nice to have a heuristic on how outrageous the incoming value is.
Definition at line 47 of file Id.cpp.
{
    // unsigned int val = atoi( s.c_str() );
    return Id(s);
}
References Id().
value()
unsigned int Id::value () const
Definition at line 195 of file Id.cpp.
{
    return id_;
}
References id_.
Referenced by ReadKkit::buildSumTotal(), Shell::cleanSimulation(), Dsolve::convertIdToPoolIndex(), Dsolve::fillConcChans(), Neutral::getId(), Stoich::getPoolIdMap(), Neuron::getSpineFromCompartment(), PsdMesh::handlePsdList(), SpineMesh::handleSpineList(), pymoose::MooseVec::id(), init(), pymoose::initShell(), Dsolve::innerBuildMeshJunctions(), Stoich::installAndUnschedFunc(), Stoich::installAndUnschedFuncRate(), Stoich::installAndUnschedFuncReac(), Dsolve::makePoolMapFromElist(), makeReacTest(), std::hash< Id >::operator()(), Neutral::setName(), Dsolve::setPath(), Dsolve::setStoich(), storeFunctionMsgs(), testCopyFieldElement(), testObjIdToAndFromPath(), testPoolVolumeScaling(), testReacVolumeScaling(), testSendSpike(), testSetGetExtField(), testSetGetSynapse(), testSetGetVec(), testSetRepeat(), testSparseMsg(), testSyncSynapseSize(), testTreeTraversal(), testTwoReacGetNeighbors(), Conv< Id >::val2buf(), HHChannel::vCreateGate(), HHChannel2D::vCreateGate(), HHChannelF::vCreateGate(), and HHChannelF2D::vCreateGate().
zeroOut()
void Id::zeroOut () const
Used to clean out any specific Id.
Definition at line 189 of file Id.cpp.
{
    assert(id_ < elements().size());
    elements()[id_] = 0;
}
References elements(), and id_.
Referenced by Element::~Element().
Friends And Related Symbol Documentation
operator<<
ostream & operator<< (ostream & s, const Id & i) friend
operator>>
istream & operator>> (istream & s, Id & i) friend
Referenced by operator>>().
Member Data Documentation
id_
unsigned int Id::id_ private
Definition at line 176 of file Id.h.
Referenced by bindIdToElement(), destroy(), element(), eref(), Id(), Id(), Id(), Id(), isValid(), operator!=(), operator<(), operator<<(), operator==(), operator>>(), value(), and zeroOut().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/basecode/Id.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/basecode/Id.cpp