MOOSE - Multiscale Object Oriented Simulation Environment: SparseMatrix< T > Class Template Reference
SparseMatrix< T > Class Template Reference
#include <SparseMatrix.h>
Public Member Functions
void addRow (unsigned int rowNum, const vector< T > &entry, const vector< unsigned int > &colIndexArg)
void addRow (unsigned int rowNum, const vector< T > &row)
void clear ()
const vector< unsigned int > & colIndex () const
T get (unsigned int row, unsigned int column) const
unsigned int getColumn (unsigned int col, vector< T > &entry, vector< unsigned int > &rowIndex) const
unsigned int getRow (unsigned int row, const T **entry, const unsigned int **colIndex) const
unsigned int getRow (unsigned int row, vector< T > &e, vector< unsigned int > &c) const
const vector< T > & matrixEntry () const
Here we expose the sparse matrix for MOOSE use.
unsigned int nColumns () const
unsigned int nEntries () const
unsigned int nRows () const
void pairFill (const vector< unsigned int > &row, const vector< unsigned int > &col, T value)
void print () const
void printInternal () const
void printTriplet (const vector< Triplet< T > > &t)
void reorderColumns (const vector< unsigned int > &colMap)
const vector< unsigned int > & rowStart () const
void set (unsigned int row, unsigned int column, T value)
void setSize (unsigned int nrows, unsigned int ncolumns)
SparseMatrix ()
SparseMatrix (unsigned int nrows, unsigned int ncolumns)
void transpose ()
void tripletFill (const vector< unsigned int > &row, const vector< unsigned int > &col, const vector< T > &z, bool retainSize=false)
void unset (unsigned int row, unsigned int column)
Protected Attributes
vector< unsigned int > colIndex_
Non-zero entries in the SparseMatrix.
vector< T > N_
unsigned int ncolumns_
unsigned int nrows_
vector< unsigned int > rowStart_
Start index in the N_ and colIndex_ vectors, of each row.
Detailed Description
template<class T>
class SparseMatrix< T >
Definition at line 63 of file SparseMatrix.h.
Constructor & Destructor Documentation
SparseMatrix() [1/2]
template<class T > SparseMatrix< T >::SparseMatrix () inline
Definition at line 69 of file SparseMatrix.h.
        : nrows_( 0 ), ncolumns_( 0 ), rowStart_( 1, 0 )
    {
        N_.resize( 0 );
        N_.reserve( SM_RESERVE );
        colIndex_.resize( 0 );
        colIndex_.reserve( SM_RESERVE );
    }
References SparseMatrix< T >::ncolumns_, SparseMatrix< T >::nrows_, and SparseMatrix< T >::SparseMatrix().
Referenced by FastMatrixElim::FastMatrixElim(), and SparseMatrix< T >::SparseMatrix().
SparseMatrix() [2/2]
template<class T > SparseMatrix< T >::SparseMatrix (unsigned int nrows, unsigned int ncolumns) inline
Definition at line 78 of file SparseMatrix.h.
    {
        setSize( nrows, ncolumns );
    }
References SparseMatrix< T >::setSize().
Referenced by NeuroMesh::buildStencil(), FastMatrixElim::FastMatrixElim(), testSparseMatrix(), testSparseMatrix2(), and testSparseMatrixReorder().
Member Function Documentation
addRow() [1/2]
template<class T > void SparseMatrix< T >::addRow (unsigned int rowNum, const vector< T > & entry, const vector< unsigned int > & colIndexArg) inline
Used to set an entire row of entries, already in sparse form. Assumes that the SparseMatrix has been suitably allocated. rowNum must be done in increasing order in successive calls.
Definition at line 410 of file SparseMatrix.h.
    {
        assert( rowNum < nrows_ );
        assert( rowStart_.size() == (nrows_ + 1 ) );
        assert( rowStart_[ rowNum ] == N_.size() );
        assert( entry.size() == colIndexArg.size() );
        assert( N_.size() == colIndex_.size() );
        if ( ncolumns_ == 0 )
            return;
        N_.insert( N_.end(), entry.begin(), entry.end() );
        colIndex_.insert( colIndex_.end(),
                          colIndexArg.begin(), colIndexArg.end() );
        rowStart_[rowNum + 1] = N_.size();
    }
References SparseMatrix< T >::ncolumns_, and SparseMatrix< T >::nrows_.
Referenced by MeshCompt::addRow(), FastMatrixElim::buildForDiffusion(), MeshCompt::extendStencil(), and FastMatrixElim::shuffleRows().
addRow() [2/2]
template<class T > void SparseMatrix< T >::addRow (unsigned int rowNum, const vector< T > & row) inline
Adds a row to the sparse matrix, must go strictly in row order. This is dangerous as there is a test for an empty entry ~0. For many types, ~0 may actually be a perfectly legal entry.
Definition at line 387 of file SparseMatrix.h.
    {
        assert( rowNum < nrows_ );
        assert( rowStart_.size() == (nrows_ + 1 ) );
        assert( N_.size() == colIndex_.size() );
        if ( ncolumns_ == 0 )
            return;
        for ( unsigned int i = 0; i < ncolumns_; ++i )
        {
            if ( row[i] != T( ~0 ) )
            {
                N_.push_back( row[i] );
                colIndex_.push_back( i );
            }
        }
        rowStart_[rowNum + 1] = N_.size();
    }
References SparseMatrix< T >::ncolumns_, and SparseMatrix< T >::nrows_.
Referenced by SparseMsg::randomConnect().
clear()
template<class T > void SparseMatrix< T >::clear () inline
Definition at line 443 of file SparseMatrix.h.
    {
        N_.resize( 0 );
        colIndex_.resize( 0 );
        assert( rowStart_.size() == (nrows_ + 1) );
        rowStart_.assign( nrows_ + 1, 0 );
    }
Referenced by SparseMsg::clear(), MeshCompt::extendStencil(), SparseMsg::randomConnect(), MeshCompt::setStencilSize(), FastMatrixElim::shuffleRows(), and testSparseMatrix2().
colIndex()
template<class T > const vector< unsigned int > & SparseMatrix< T >::colIndex () const inline
Definition at line 431 of file SparseMatrix.h.
    {
        return colIndex_;
    }
Referenced by Stoich::getColIndex(), SparseMsg::getColIndex(), and SparseMsg::getEntryPairs().
get()
template<class T > T SparseMatrix< T >::get (unsigned int row, unsigned int column) const inline
Returns the entry identified by row, column. Returns T(0) if not found
Definition at line 253 of file SparseMatrix.h.
    {
        if ( nrows_ == 0 || ncolumns_ == 0 )
            return 0;
        assert( row < nrows_ && column < ncolumns_ );
        vector< unsigned int >::const_iterator i;
        vector< unsigned int >::const_iterator begin =
            colIndex_.begin() + rowStart_[ row ];
        vector< unsigned int >::const_iterator end =
            colIndex_.begin() + rowStart_[ row + 1 ];
        i = find( begin, end, column );
        if ( i == end )   // most common situation for a sparse Stoich matrix.
        {
            return 0;
        }
        else
        {
            return N_[ rowStart_[row] + (i - begin) ];
        }
    }
References SparseMatrix< T >::ncolumns_, and SparseMatrix< T >::nrows_.
Referenced by FastMatrixElim::buildBackwardSub(), FastMatrixElim::buildForwardElim(), Stoich::innerInstallReaction(), Stoich::installAndUnschedFuncRate(), Stoich::installEnzyme(), Stoich::installMMenz(), printSparseMatrix(), testFastMatrixElim(), testSetDiffusionAndTransport(), testSparseMatrix2(), testSparseMatrixFill(), and testSparseMatrixReorder().
getColumn()
template<class T > unsigned int SparseMatrix< T >::getColumn (unsigned int col, vector< T > & entry, vector< unsigned int > & rowIndex) const inline
This is an unnatural lookup here, across the grain of the sparse matrix. Ideally should use copy_if, but the C++ chaps forgot it.
Definition at line 342 of file SparseMatrix.h.
    {
        entry.resize( 0 );
        rowIndex.resize( 0 );
        unsigned int row = 0;
        for ( unsigned int i = 0; i < N_.size(); ++i )
        {
            if ( col == colIndex_[i] )
            {
                entry.push_back( N_[i] );
                while ( rowStart_[ row + 1 ] <= i )
                    row++;
                rowIndex.push_back( row );
            }
        }
        return entry.size();
    }
Referenced by SparseMsg::findOtherEnd().
getRow() [1/2]
template<class T > unsigned int SparseMatrix< T >::getRow (unsigned int row, const T ** entry, const unsigned int ** colIndex) const inline
Used to get an entire row of entries. Returns # entries. Passes back iterators for the row and for the column index.
Ideally I should provide a forall type function so that the user passes in their operation as a functor, and it is applied to the entire row.
Definition at line 288 of file SparseMatrix.h.
    {
        if ( row >= nrows_ || ncolumns_ == 0 )
        {
            entry = 0;
            colIndex = 0;
            return 0;
        }
        unsigned int rs = rowStart_[row];
        if ( rs >= N_.size() )
        {
            entry = 0;
            colIndex = 0;
            return 0;
        }
        *entry = &( N_[ rs ] );
        *colIndex = &( colIndex_[rs] );
        return rowStart_[row + 1] - rs;
    }
References SparseMatrix< T >::ncolumns_, and SparseMatrix< T >::nrows_.
Referenced by KinSparseMatrix::computeRowRate(), MeshCompt::extendStencil(), fillErefsFromMatrix(), Gsolve::fillIncrementFuncDep(), Gsolve::fillMmEnzDep(), Gsolve::fillPoolFuncDep(), SparseMsg::findOtherEnd(), SparseMsg::firstTgt(), MeshCompt::getNeighbors(), MeshCompt::getStencilRow(), MeshCompt::innerGetStencilRate(), printSparseMatrix(), testSparseMatrix(), and SparseMsg::updateAfterFill().
getRow() [2/2]
template<class T > unsigned int SparseMatrix< T >::getRow (unsigned int row, vector< T > & e, vector< unsigned int > & c) const inline
getRow: vector version. Used to get an entire row of entries. Returns # entries.
Definition at line 314 of file SparseMatrix.h.
    {
        e.clear();
        c.clear();
        if ( row >= nrows_ || ncolumns_ == 0 )
        {
            return 0;
        }
        unsigned int rs = rowStart_[row];
        if ( rs >= N_.size() )
        {
            return 0;
        }
        unsigned int ret = rowStart_[row + 1] - rs;
        e.insert( e.begin(),
                  N_.begin() + rs, N_.begin() + rs + ret );
        c.insert( c.begin(),
                  colIndex_.begin() + rs, colIndex_.begin() + rs + ret );
        return ret;
    }
References SparseMatrix< T >::ncolumns_, and SparseMatrix< T >::nrows_.
Referenced by Gsolve::fillPoolFuncDep(), and FastMatrixElim::shuffleRows().
matrixEntry()
template<class T > const vector< T > & SparseMatrix< T >::matrixEntry () const inline
Here we expose the sparse matrix for MOOSE use.
Definition at line 427 of file SparseMatrix.h.
    {
        return N_;
    }
Referenced by Stoich::getMatrixEntry(), and SparseMsg::getMatrixEntry().
nColumns()
template<class T > unsigned int SparseMatrix< T >::nColumns () const inline
Definition at line 92 of file SparseMatrix.h.
    {
        return ncolumns_;
    }
References SparseMatrix< T >::ncolumns_.
Referenced by KinSparseMatrix::computeRowRate(), fillErefsFromMatrix(), SparseMsg::getNumColumns(), printSparseMatrix(), SparseMsg::randomConnect(), testSparseMatrix(), testSparseMatrixFill(), testSparseMatrixReorder(), VoxelPools::updateRates(), VoxelPools::updateReacVelocities(), and GssaVoxelPools::updateReacVelocities().
nEntries()
template<class T > unsigned int SparseMatrix< T >::nEntries () const inline
Definition at line 97 of file SparseMatrix.h.
    {
        return N_.size();
    }
Referenced by SparseMsg::firstTgt(), SparseMsg::getNumEntries(), and testSparseMatrixFill().
nRows()
template<class T > unsigned int SparseMatrix< T >::nRows () const inline
Definition at line 87 of file SparseMatrix.h.
    {
        return nrows_;
    }
References SparseMatrix< T >::nrows_.
Referenced by KinSparseMatrix::computeRowRate(), MeshCompt::extendStencil(), fillErefsFromMatrix(), SparseMsg::getEntryPairs(), SparseMsg::getNumRows(), printSparseMatrix(), SparseMsg::randomConnect(), testSparseMatrix(), testSparseMatrixFill(), testSparseMatrixReorder(), SparseMsg::updateAfterFill(), and VoxelPools::updateRates().
pairFill()
template<class T > void SparseMatrix< T >::pairFill (const vector< unsigned int > & row, const vector< unsigned int > & col, T value) inline
Definition at line 627 of file SparseMatrix.h.
    {
        vector< T > z( row.size(), value );
        tripletFill( row, col, z );
    }
print()
template<class T > void SparseMatrix< T >::print () const inline
Prints out the contents in matrix form
Definition at line 650 of file SparseMatrix.h.
    {
        for ( unsigned int i = 0; i < nrows_; ++i )
        {
            unsigned int k = rowStart_[i];
            unsigned int end = rowStart_[i + 1];
            unsigned int nextColIndex = colIndex_[k];
            for ( unsigned int j = 0; j < ncolumns_; ++j )
            {
                if ( j < nextColIndex )
                {
                    cout << "0  ";
                }
                else if ( k < end )
                {
                    cout << N_[k] << "  ";
                    ++k;
                    nextColIndex = colIndex_[k];
                }
                else
                {
                    cout << "0  ";
                }
            }
            cout << endl;
        }
    }
References SparseMatrix< T >::ncolumns_, and SparseMatrix< T >::nrows_.
Referenced by Dsolve::build(), and Stoich::print().
printInternal()
template<class T > void SparseMatrix< T >::printInternal () const inline
Prints out the contents in internal form
Definition at line 681 of file SparseMatrix.h.
    {
        unsigned int max = (nrows_ < N_.size() ) ? N_.size() : nrows_+1;
        cout << "#  ";
        for ( unsigned int i = 0; i < max; ++i )
            cout << i << "  ";
        cout << "\nrs   ";
        for ( unsigned int i = 0; i < rowStart_.size(); ++i )
            cout << rowStart_[i] << "   ";
        cout << "\ncol  ";
        for ( unsigned int i = 0; i < N_.size(); ++i )
            cout << colIndex_[i] << "   ";
        cout << "\nN    ";
        for ( unsigned int i = 0; i < N_.size(); ++i )
            cout << N_[i] << "  ";
        cout << endl;
    }
printTriplet()
template<class T > void SparseMatrix< T >::printTriplet (const vector< Triplet< T > > & t) inline
Definition at line 638 of file SparseMatrix.h.
    {
        for ( unsigned int i = 0; i < t.size(); ++i )
        {
            cout << i << "  " << t[i].a_ << "   " << t[i].b_ <<
                 "  " << t[i].c_ << endl;
        }
    }
reorderColumns()
template<class T > void SparseMatrix< T >::reorderColumns (const vector< unsigned int > & colMap) inline
Reorder columns from the matrix based on a map of old to new column indices. newCols contains the indices of columns from the old matrix that are to be retained, in the order that they will occupy in the new matrix. It can have fewer or more indices than the original.
Definition at line 533 of file SparseMatrix.h.
    {
        unsigned int numNewColumns = colMap.size();;
        SparseMatrix< T > old = *this;
        setSize( nrows_, numNewColumns );
        if ( numNewColumns == 0 )
            return;
        for ( unsigned int i = 0; i < old.nrows_; ++i )
        {
            const T* entry;
            const unsigned int* colIndex;
            unsigned int n = old.getRow( i, &entry, &colIndex );
            // Make the full-length vectors of the new row.
            vector< T > newEntry( numNewColumns );
            vector< bool > isNewEntry( numNewColumns, false );
            unsigned int numOccupiedEntries = 0;
            for ( unsigned int j = 0; j < n; ++j )
            {
                assert( colIndex[j] < old.ncolumns_ );
                for ( unsigned int q = 0; q < colMap.size(); ++q )
                {
                    if ( colMap[q] == colIndex[j] )
                    {
                        isNewEntry[q] = true;
                        newEntry[q] = entry[j];
                        ++numOccupiedEntries;
                    }
                }
            }
            // Compress the full-length vector into the sparse form
            vector< T > sparseEntry;
            vector< unsigned int > sparseCols;
            sparseEntry.reserve( numOccupiedEntries );
            sparseCols.reserve( numOccupiedEntries );
            for ( unsigned int q = 0; q < numNewColumns; ++q )
            {
                if ( isNewEntry[q] )
                {
                    sparseEntry.push_back( newEntry[q] );
                    sparseCols.push_back( q );
                }
            }
            addRow( i, sparseEntry, sparseCols );
        }
    }
References SparseMatrix< T >::nrows_, and SparseMatrix< T >::setSize().
Referenced by testSparseMatrix(), testSparseMatrix2(), and testSparseMatrixReorder().
rowStart()
template<class T > const vector< unsigned int > & SparseMatrix< T >::rowStart () const inline
Definition at line 435 of file SparseMatrix.h.
    {
        return rowStart_;
    }
Referenced by SparseMsg::getEntryPairs(), Stoich::getRowStart(), and SparseMsg::getRowStart().
set()
template<class T > void SparseMatrix< T >::set (unsigned int row, unsigned int column, T value) inline
Assigns and if necessary adds an entry in the matrix. This variant does NOT remove any existing entry.
Definition at line 161 of file SparseMatrix.h.
    {
        if ( nrows_ == 0 || ncolumns_ == 0 )
            return;
        vector< unsigned int >::iterator i;
        vector< unsigned int >::iterator begin =
            colIndex_.begin() + rowStart_[ row ];
        vector< unsigned int >::iterator end =
            colIndex_.begin() + rowStart_[ row + 1 ];
        if ( begin == end )   // Entire row was empty.
        {
            unsigned long offset = begin - colIndex_.begin();
            colIndex_.insert( colIndex_.begin() + offset, column );
            N_.insert( N_.begin() + offset, value );
            for ( unsigned int j = row + 1; j <= nrows_; j++ )
                rowStart_[ j ]++;
            return;
        }
        if ( column > *( end - 1 ) )   // add entry at end of row.
        {
            unsigned long offset = end - colIndex_.begin();
            colIndex_.insert( colIndex_.begin() + offset, column );
            N_.insert( N_.begin() + offset, value );
            for ( unsigned int j = row + 1; j <= nrows_; j++ )
                rowStart_[ j ]++;
            return;
        }
        for ( i = begin; i != end; i++ )
        {
            if ( *i == column )   // Found desired entry. By defn it is nonzero.
            {
                N_[ i - colIndex_.begin()] = value;
                return;
            }
            else if ( *i > column )     // Desired entry is blank.
            {
                unsigned long offset = i - colIndex_.begin();
                colIndex_.insert( colIndex_.begin() + offset, column );
                N_.insert( N_.begin() + offset, value );
                for ( unsigned int j = row + 1; j <= nrows_; j++ )
                    rowStart_[ j ]++;
                return;
            }
        }
    }
References SparseMatrix< T >::ncolumns_, and SparseMatrix< T >::nrows_.
Referenced by Stoich::innerInstallReaction(), Stoich::installAndUnschedFuncRate(), Stoich::installEnzyme(), Stoich::installMMenz(), SparseMsg::setEntry(), testSparseMatrix(), testSparseMatrix2(), and testSparseMatrixReorder().
setSize()
template<class T > void SparseMatrix< T >::setSize (unsigned int nrows, unsigned int ncolumns) inline
Should be called only at the start. Subsequent resizing destroys the contents.
Definition at line 126 of file SparseMatrix.h.
    {
        if ( nrows == 0 || ncolumns == 0 )
        {
            N_.clear();
            rowStart_.resize( 1 );
            rowStart_[0] = 0;
            colIndex_.clear();
            nrows_ = 0;
            ncolumns_ = 0;
            return;
        }
        if ( nrows < SM_MAX_ROWS && ncolumns < SM_MAX_COLUMNS )
        {
            N_.clear();
            N_.reserve( 2 * nrows );
            nrows_ = nrows;
            ncolumns_ = ncolumns;
            rowStart_.clear();
            rowStart_.resize( nrows + 1, 0 );
            colIndex_.clear();
            colIndex_.reserve( 2 * nrows );
        }
        else
        {
            cerr << "Error: SparseMatrix::setSize( " <<
                 nrows << ", " << ncolumns << ") out of range: ( " <<
                 SM_MAX_ROWS << ", " << SM_MAX_COLUMNS << ")\n";
        }
    }
References SparseMatrix< T >::ncolumns_, SparseMatrix< T >::nrows_, SM_MAX_COLUMNS, and SM_MAX_ROWS.
Referenced by MeshCompt::extendStencil(), FastMatrixElim::makeTestMatrix(), SparseMatrix< T >::reorderColumns(), Stoich::resizeArrays(), MeshCompt::setStencilSize(), FastMatrixElim::shuffleRows(), SparseMatrix< T >::SparseMatrix(), SparseMsg::SparseMsg(), testSparseMatrix2(), testSparseMatrixReorder(), and SparseMatrix< T >::tripletFill().
transpose()
template<class T > void SparseMatrix< T >::transpose () inline
Does a transpose, using as workspace a vector of size 3 N_ 0257 -> 0011122
Definition at line 456 of file SparseMatrix.h.
    {
        vector< Triplet< T > > t;
        unsigned int rowIndex = 0;
        if ( rowStart_.size() < 2 )
            return;
        /*
        for ( unsigned int i = 0; i < rowStart_.size(); ++i )
            cout << rowStart_[i] << " ";
        cout << endl;
        */
        // cout << "rowNum = ";
        unsigned int rs = rowStart_[0];
        for ( unsigned int i = 0; i < N_.size(); ++i )
        {
            while( rs == rowStart_[ rowIndex + 1 ] )
            {
                rowIndex++;
            }
            rs++;
            /*
            if ( i == rowStart_[j] ) {
                rowNum++;
                j++;
            }
            */
            // cout << rowNum << " ";
            // The rowNum is going to be the new colIndex.
            Triplet< T > x( N_[i], rowIndex, colIndex_[i] );
            t.push_back( x );
        }
        // cout << endl;
        // cout << "before sort\n"; printTriplet( t );
        stable_sort( t.begin(), t.end() );
        // cout << "after sort\n"; printTriplet( t );
        unsigned int j = ~0;
        rowStart_.resize( 0 );
        rowStart_.push_back( 0 );
        unsigned int ci = 0;
        for ( unsigned int i = 0; i < N_.size(); ++i )
        {
            N_[i] = t[i].a_;
            colIndex_[i] = t[i].b_;
            while ( ci != t[i].c_ )
            {
                rowStart_.push_back( i );
                ci++;
            }
            /*
            if ( t[i].c_ != j ) {
                j = t[i].c_;
                rowStart_.push_back( i );
            }
            */
        }
        for ( j = ci; j < ncolumns_; ++j )
            rowStart_.push_back( N_.size() );
        // rowStart_.push_back( N_.size() );
        j = nrows_;
        nrows_ = ncolumns_;
        ncolumns_ = j;
        assert( rowStart_.size() == nrows_ + 1 );
    }
References SparseMatrix< T >::ncolumns_, and SparseMatrix< T >::nrows_.
Referenced by FastMatrixElim::checkSymmetricShape(), FastMatrixElim::isSymmetric(), SparseMsg::randomConnect(), Gsolve::rebuildGssaSystem(), SparseMsg::sources(), testSparseMatrix(), testSparseMatrix2(), SparseMsg::transpose(), and SparseMsg::updateAfterFill().
tripletFill()
template<class T > void SparseMatrix< T >::tripletFill (const vector< unsigned int > & row, const vector< unsigned int > & col, const vector< T > & z, bool retainSize = false) inline
Definition at line 583 of file SparseMatrix.h.
    {
        unsigned int len = row.size();
        if ( len > col.size() ) len = col.size();
        if ( len > z.size() ) len = z.size();
        vector< Triplet< T > > trip( len );
        for ( unsigned int i = 0; i < len; ++i )
            trip[i]= Triplet< T >(z[i], row[i], col[i] );
        sort( trip.begin(), trip.end(), Triplet< T >::cmp );
        unsigned int nr = nrows_;
        unsigned int nc = ncolumns_;
        if ( !retainSize ) {
            nr = trip.back().b_ + 1;
            nc = 0;
            for ( typename vector< Triplet< T > >::iterator i =
                trip.begin(); i != trip.end(); ++i )
            {
                if ( nc < i->c_ )
                    nc = i->c_;
            }
            nc++;
        }
        setSize( nr, nc );
        vector< unsigned int > colIndex( nc );
        vector< T > entry( nc );
        typename vector< Triplet< T > >::iterator j = trip.begin();
        for ( unsigned int i = 0; i < nr; ++i )
        {
            colIndex.clear();
            entry.clear();
            while( j != trip.end() && j->b_ == i )
            {
                colIndex.push_back( j->c_ );
                entry.push_back( j->a_ );
                j++;
            }
            addRow( i, entry, colIndex );
        }
    }
References SparseMatrix< T >::ncolumns_, SparseMatrix< T >::nrows_, and SparseMatrix< T >::setSize().
Referenced by SparseMsg::pairFill(), testSparseMatrixFill(), and SparseMsg::tripletFill().
unset()
template<class T > void SparseMatrix< T >::unset (unsigned int row, unsigned int column) inline
Removes specified entry.
Definition at line 212 of file SparseMatrix.h.
    {
        if ( nrows_ == 0 || ncolumns_ == 0 )
            return;
        vector< unsigned int >::iterator i;
        vector< unsigned int >::iterator begin =
            colIndex_.begin() + rowStart_[ row ];
        vector< unsigned int >::iterator end =
            colIndex_.begin() + rowStart_[ row + 1 ];
        if ( begin == end )   // Entire row was empty. Ignore
        {
            return;
        }
        if ( column > *( end - 1 ) )   // End of row. Ignore
        {
            return;
        }
        for ( i = begin; i != end; i++ )
        {
            if ( *i == column )   // Found desired entry. Zap it.
            {
                unsigned long offset = i - colIndex_.begin();
                colIndex_.erase( i );
                N_.erase( N_.begin() + offset );
                for ( unsigned int j = row + 1; j <= nrows_; j++ )
                    rowStart_[ j ]--;
                return;
            }
            else if ( *i > column )     //Desired entry is blank. Ignore
            {
                return;
            }
        }
    }
References SparseMatrix< T >::ncolumns_, and SparseMatrix< T >::nrows_.
Referenced by SparseMsg::unsetEntry().
Member Data Documentation
colIndex_
template<class T > vector< unsigned int > SparseMatrix< T >::colIndex_ protected
Non-zero entries in the SparseMatrix.
Definition at line 709 of file SparseMatrix.h.
N_
template<class T > vector< T > SparseMatrix< T >::N_ protected
Definition at line 703 of file SparseMatrix.h.
ncolumns_
template<class T > unsigned int SparseMatrix< T >::ncolumns_ protected
Definition at line 702 of file SparseMatrix.h.
Referenced by SparseMatrix< T >::addRow(), SparseMatrix< T >::addRow(), SparseMatrix< T >::get(), SparseMatrix< T >::getRow(), SparseMatrix< T >::getRow(), SparseMatrix< T >::nColumns(), SparseMatrix< T >::print(), SparseMatrix< T >::set(), SparseMatrix< T >::setSize(), SparseMatrix< T >::SparseMatrix(), SparseMatrix< T >::transpose(), SparseMatrix< T >::tripletFill(), and SparseMatrix< T >::unset().
nrows_
template<class T > unsigned int SparseMatrix< T >::nrows_ protected
Definition at line 701 of file SparseMatrix.h.
Referenced by SparseMatrix< T >::addRow(), SparseMatrix< T >::addRow(), SparseMatrix< T >::get(), SparseMatrix< T >::getRow(), SparseMatrix< T >::getRow(), SparseMatrix< T >::nRows(), SparseMatrix< T >::print(), SparseMatrix< T >::reorderColumns(), SparseMatrix< T >::set(), SparseMatrix< T >::setSize(), SparseMatrix< T >::SparseMatrix(), SparseMatrix< T >::transpose(), SparseMatrix< T >::tripletFill(), and SparseMatrix< T >::unset().
rowStart_
template<class T > vector< unsigned int > SparseMatrix< T >::rowStart_ protected
Start index in the N_ and colIndex_ vectors, of each row.
Definition at line 712 of file SparseMatrix.h.
The documentation for this class was generated from the following file:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/basecode/SparseMatrix.h