MOOSE - Multiscale Object Oriented Simulation Environment: BidirectionalReaction Class Reference
BidirectionalReaction Class Reference
#include <RateTerm.h>
Public Member Functions
BidirectionalReaction (ZeroOrder *forward, ZeroOrder *backward)
RateTerm * copyWithVolScaling (double vol, double sub, double prd) const
double getR1 () const
Used by Zombie to return rate terms.
double getR2 () const
Used by Zombie to return rate terms.
unsigned int getReactants (vector< unsigned int > &molIndex) const
double operator() (const double *S) const
Computes the rate. The argument is the molecule array.
void rescaleVolume (short comptIndex, const vector< short > &compartmentLookup, double ratio)
void setR1 (double kf)
Used by Zombie to assign rate terms.
void setR2 (double kb)
Used by Zombie to assign rate terms.
void setRates (double kf, double kb)
~BidirectionalReaction ()
Public Member Functions inherited from RateTerm
RateTerm ()
virtual ~RateTerm ()
Private Attributes
ZeroOrder * backward_
ZeroOrder * forward_
Additional Inherited Members
Static Public Attributes inherited from RateTerm
static const double EPSILON = 1.0e-6
Detailed Description
Definition at line 584 of file RateTerm.h.
Constructor & Destructor Documentation
BidirectionalReaction()
BidirectionalReaction::BidirectionalReaction (ZeroOrder * forward, ZeroOrder * backward) inline
Definition at line 587 of file RateTerm.h.
        : forward_( forward ), backward_( backward )
    {
        // Here we allocate internal forward and backward terms
        // with the correct number of args.
        ;
    }
References backward_, and forward_.
Referenced by copyWithVolScaling(), Stoich::innerInstallReaction(), Stoich::installDummyEnzyme(), and Stoich::installEnzyme().
~BidirectionalReaction()
BidirectionalReaction::~BidirectionalReaction () inline
Definition at line 595 of file RateTerm.h.
    {
        delete forward_;
        delete backward_;
    }
References backward_, and forward_.
Member Function Documentation
copyWithVolScaling()
RateTerm * BidirectionalReaction::copyWithVolScaling (double vol, double sub, double prd) const inline virtual
Duplicates rate term and then applies volume scaling. Arguments are volume of reference voxel, product of vol/refVol for all substrates: applied to R1 product of vol/refVol for all products: applied to R2
Note that unless the reaction is cross-compartment, the vol/refVol will be one.
Implements RateTerm.
Definition at line 650 of file RateTerm.h.
    {
        ZeroOrder* f = static_cast< ZeroOrder* >(
                           forward_->copyWithVolScaling( vol, sub, 1 ) );
        ZeroOrder* b = static_cast< ZeroOrder* >(
                           backward_->copyWithVolScaling( vol, prd, 1 ) );
        return new BidirectionalReaction( f, b );
    }
References backward_, BidirectionalReaction(), ZeroOrder::copyWithVolScaling(), and forward_.
getR1()
double BidirectionalReaction::getR1 () const inline virtual
Used by Zombie to return rate terms.
Implements RateTerm.
Definition at line 624 of file RateTerm.h.
    {
        return forward_->getR1();
    }
References forward_, and ZeroOrder::getR1().
getR2()
double BidirectionalReaction::getR2 () const inline virtual
Used by Zombie to return rate terms.
Implements RateTerm.
Definition at line 629 of file RateTerm.h.
    {
        return backward_->getR1();
    }
References backward_, and ZeroOrder::getR1().
getReactants()
unsigned int BidirectionalReaction::getReactants (vector< unsigned int > & molIndex) const inline virtual
This function finds the reactant indices in the vector S. It returns the number of substrates found, which are the first entries in molIndex. The products are the remaining ones. Note that it does NOT find products for unidirectional reactions, which is a bit of a problem.
Implements RateTerm.
Definition at line 634 of file RateTerm.h.
    {
        forward_->getReactants( molIndex );
        unsigned int ret = molIndex.size();
        vector< unsigned int > temp;
        backward_->getReactants( temp );
        molIndex.insert( molIndex.end(), temp.begin(), temp.end() );
        return ret;
    }
References backward_, forward_, and ZeroOrder::getReactants().
operator()()
double BidirectionalReaction::operator() (const double * S) const inline virtual
Computes the rate. The argument is the molecule array.
Implements RateTerm.
Definition at line 601 of file RateTerm.h.
    {
        auto v = (*forward_)( S ) - (*backward_)( S );
        assert(! std::isnan(v));
        return v;
    }
References backward_, forward_, and ZeroOrder::operator()().
rescaleVolume()
void BidirectionalReaction::rescaleVolume (short comptIndex, const vector< short > & compartmentLookup, double ratio) inline virtual
This is used to rescale the RateTerm kinetics when the compartment volume changes. This is needed because the kinetics are in extensive units, that is, mol numbers, rather than in intensive units like concentration. So when the volume changes the rate terms change. Each Rate term checks if any of its reactant molecules are affected, and if so, rescales. Ratio is newVol / oldVol
Implements RateTerm.
Definition at line 644 of file RateTerm.h.
    {
        forward_->rescaleVolume( comptIndex, compartmentLookup, ratio );
        backward_->rescaleVolume( comptIndex, compartmentLookup, ratio);
    }
References backward_, forward_, and ZeroOrder::rescaleVolume().
setR1()
void BidirectionalReaction::setR1 (double k1) inline virtual
Used by Zombie to assign rate terms.
Implements RateTerm.
Definition at line 614 of file RateTerm.h.
    {
        forward_->setK( kf );
    }
References forward_, and ZeroOrder::setK().
setR2()
void BidirectionalReaction::setR2 (double k2) inline virtual
Used by Zombie to assign rate terms.
Implements RateTerm.
Definition at line 619 of file RateTerm.h.
    {
        backward_->setK( kb );
    }
References backward_, and ZeroOrder::setK().
setRates()
void BidirectionalReaction::setRates (double k1, double k2) inline virtual
Assign the rates.
Implements RateTerm.
Definition at line 608 of file RateTerm.h.
    {
        forward_->setK( kf );
        backward_->setK( kb );
    }
References backward_, forward_, and ZeroOrder::setK().
Member Data Documentation
backward_
ZeroOrder* BidirectionalReaction::backward_ private
Definition at line 662 of file RateTerm.h.
Referenced by BidirectionalReaction(), copyWithVolScaling(), getR2(), getReactants(), operator()(), rescaleVolume(), setR2(), setRates(), and ~BidirectionalReaction().
forward_
ZeroOrder* BidirectionalReaction::forward_ private
Definition at line 661 of file RateTerm.h.
Referenced by BidirectionalReaction(), copyWithVolScaling(), getR1(), getReactants(), operator()(), rescaleVolume(), setR1(), setRates(), and ~BidirectionalReaction().
The documentation for this class was generated from the following file:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/ksolve/RateTerm.h