MOOSE - Multiscale Object Oriented Simulation Environment: Conv< T > Class Template Reference
Conv< T > Class Template Reference
#include <Conv.h>
Static Public Member Functions
static const T & buf2val (double **buf)
static string rttiType ()
static unsigned int size (const T &val)
static void str2val (T &val, const string &s)
static void val2buf (const T &val, double **buf)
static void val2str (string &s, const T &val)
Detailed Description
template<class T>
class Conv< T >
Definition at line 30 of file Conv.h.
Member Function Documentation
buf2val()
template<class T > static const T & Conv< T >::buf2val (double ** buf) inline static
Definition at line 44 of file Conv.h.
{
            const T* ret = reinterpret_cast< const T* >( *buf );
            *buf += size( *ret );
            return *ret;
        }
References Conv< T >::size().
rttiType()
template<class T > static string Conv< T >::rttiType () inline static
Definition at line 82 of file Conv.h.
{
            if ( typeid( T ) == typeid( char ))
                return "char";
            if ( typeid( T ) == typeid( int ) )
                return "int";
            if ( typeid( T ) == typeid( short ) )
                return "short";
            if ( typeid( T ) == typeid( long ) )
                return "long";
            if ( typeid( T ) == typeid( size_t ) )
                return "size_t";
            if ( typeid( T ) == typeid( unsigned int ) )
                return "unsigned int";
            if ( typeid( T ) == typeid( unsigned long ) )
                return "unsigned long";
            if ( typeid( T ) == typeid( float ) )
                return "float";
            if ( typeid( T ) == typeid( double ) )
                return "double";
            if ( typeid( T ) == typeid( Id ) )
                return "Id";
            if ( typeid( T ) == typeid( ObjId ) )
                return "ObjId";
            if ( typeid( T ) == typeid( vector<ObjId>) )
                return "vector<ObjId>";
            if ( typeid( T ) == typeid( vector<ObjId>*) )
                return "vector<ObjId>*";
            if ( typeid( T ) == typeid( vector<Id>) )
                return "vector<Id>";
            if ( typeid( T ) == typeid( vector<Id>*) )
                return "vector<Id>*";
#if 0
            // typeid of incomplete type Neutral (after forward declarting it)
            // is not supported by c++ standard. Though following compiles with
            // gcc (but not with clang).
            if ( typeid( T ) == typeid( Neutral ) )
                return "Neutral";
            if ( typeid( T ) == typeid( vector<Neutral> ) )
                return "vector<Neutral>";
            if ( typeid( T ) == typeid( vector<Neutral>*) )
                return "vector<Neutral>*";
#endif
            if ( typeid( T ) == typeid( vector<string>) )
                return "vector<string>";
            if ( typeid( T ) == typeid( vector<double>) )
                return "vector<double>";
            if ( typeid( T ) == typeid( vector<double>*) )
                return "vector<double>*";
            if ( typeid( T ) == typeid( vector<bool>) )
                return "vector<bool>";
            if ( typeid( T ) == typeid( vector<bool>*) )
                return "vector<bool>*";
            if ( typeid( T ) == typeid( vector<unsigned int>) )
                return "vector<unsigned int>";
            if ( typeid( T ) == typeid( vector<unsigned int>*) )
                return "vector<unsigned int>*";
            if ( typeid( T ) == typeid( vector<vector<double>>) )
                return "vector<vector<double>>";
            if ( typeid( T ) == typeid( vector<vector<double>>*) )
                return "vector<vector<double>>*";
            if ( typeid( T ) == typeid( vector<vector<ObjId>>) )
                return "vector<vector<ObjId>>";
            if ( typeid( T ) == typeid( vector<vector<ObjId>>*) )
                return "vector<vector<ObjId>>*";
            if ( typeid( T ) == typeid( vector<vector<Id>>) )
                return "vector<vector<Id>>";
            if ( typeid( T ) == typeid( vector<vector<Id>>*) )
                return "vector<vector<Id>>*";
            if ( typeid( T ) == typeid( vector<vector<string>>) )
                return "vector<vector<string>>";
            if ( typeid( T ) == typeid( vector<vector<string>>*) )
                return "vector<vector<string>>*";
            return typeid(T).name(); // this is not portable but may be more useful than "bad"
        }
size()
template<class T > static unsigned int Conv< T >::size (const T & val) inline static
Size, in units of sizeof(double). So a double would be 1, something with 1 chars would be 1 as well, but something with 9 chars would be 2.
Definition at line 38 of file Conv.h.
        {
            return 1 + ( sizeof( T ) - 1 ) / sizeof( double );
        }
Referenced by Conv< T >::buf2val(), and Conv< T >::val2buf().
str2val()
template<class T > static void Conv< T >::str2val (T & val, const string & s) inline static
Default conversion from string just puts the string into the char* pointer.
Definition at line 65 of file Conv.h.
{
            istringstream is( s );
            is >> val;
        }
val2buf()
template<class T > static void Conv< T >::val2buf (const T & val, double ** buf) inline static
Converts data contents into double* buf. Buf must be allocated ahead of time. Returns size of value. Needs to be specialized for variable size and pointer-containing types T.
Definition at line 56 of file Conv.h.
{
            *reinterpret_cast< T* >( *buf ) = val;
            *buf += size( val );
        }
References Conv< T >::size().
val2str()
template<class T > static void Conv< T >::val2str (string & s, const T & val) inline static
Default conversion into string just puts the char* representation into the string. Arguably a bad way to do it.
Definition at line 74 of file Conv.h.
{
            stringstream ss;
            ss << val;
            s = ss.str();
            // ostringstream os( s );
            // os << val;
        }
The documentation for this class was generated from the following file:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/basecode/Conv.h