MOOSE - Multiscale Object Oriented Simulation Environment: SrcFinfo2< T1, T2 > Class Template Reference
SrcFinfo2< T1, T2 > Class Template Reference
#include <SrcFinfo.h>
Public Member Functions
string rttiType () const
void send (const Eref &e, const T1 &arg1, const T2 &arg2) const
void sendBuffer (const Eref &e, double *buf) const
void sendTo (const Eref &e, Id tgt, const T1 &arg1, const T2 &arg2) const
SrcFinfo2 (const string &name, const string &doc)
~SrcFinfo2 ()
Public Member Functions inherited from SrcFinfo
bool addMsg (const Finfo *target, ObjId mid, Element *src) const
bool checkTarget (const Finfo *target) const
BindIndex getBindIndex () const
void registerFinfo (Cinfo *c)
void setBindIndex (BindIndex b)
SrcFinfo (const string &name, const string &doc)
bool strGet (const Eref &tgt, const string &field, string &returnValue) const
bool strSet (const Eref &tgt, const string &field, const string &arg) const
~SrcFinfo ()
Public Member Functions inherited from Finfo
const string & docs () const
Returns documentation string.
Finfo (const string &name, const string &doc)
virtual vector< string > innerDest () const
virtual vector< string > innerSrc () const
const string & name () const
virtual void postCreationFunc (Id newId, Element *newElm) const
virtual ~Finfo ()
Additional Inherited Members
Static Public Member Functions inherited from Finfo
static const Cinfo * initCinfo ()
Static Public Attributes inherited from SrcFinfo
static const BindIndex BadBindIndex = 65535
Detailed Description
template<class T1, class T2>
class SrcFinfo2< T1, T2 >
Definition at line 212 of file SrcFinfo.h.
Constructor & Destructor Documentation
~SrcFinfo2()
template<class T1 , class T2 > SrcFinfo2< T1, T2 >::~SrcFinfo2 () inline
Definition at line 215 of file SrcFinfo.h.
{;}
SrcFinfo2()
template<class T1 , class T2 > SrcFinfo2< T1, T2 >::SrcFinfo2 (const string & name, const string & doc) inline
Definition at line 217 of file SrcFinfo.h.
            : SrcFinfo( name, doc )
            { ; }
Referenced by channel1Out(), channel2Out(), ChanBase::channelOut(), cplxOut(), cylinderOut(), distalOut(), enzOut(), DifBufferBase::innerDifSourceOut(), DifShellBase::innerDifSourceOut(), inPoolOut(), DifBufferBase::outerDifSourceOut(), DifShellBase::outerDifSourceOut(), outPoolOut(), prdOut(), prdOut(), proximalOut(), MMPump::PumpOut(), raxialOut(), subOut(), subOut(), and testSharedMsg().
Member Function Documentation
rttiType()
template<class T1 , class T2 > string SrcFinfo2< T1, T2 >::rttiType () const inline virtual
Returns the documentation string for the Finfo string docs() const; Returns the RTTI type string for the finfo by referring to an internal virtual function. string type() const; Returns the list of subsidiary SrcFinfos. Used in Shared Finfos, empty otherwise. Goes via internal virtual function. vector< string > src() const; Returns the list of subsidiary destFinfos. Used in SharedFinfos and ValueFinfos, empty otherwise. Goes via internal virtual function. vector< string > dest() const; Returns an RTTI type string for this Finfo.
Reimplemented from Finfo.
Definition at line 281 of file SrcFinfo.h.
{
            return Conv<T1>::rttiType() + "," + Conv< T2 >::rttiType();
        }
send()
template<class T1 , class T2 > void SrcFinfo2< T1, T2 >::send (const Eref & e, const T1 & arg1, const T2 & arg2) const inline
Definition at line 221 of file SrcFinfo.h.
        {
            const vector< MsgDigest >& md = e.msgDigest( getBindIndex() );
            for ( vector< MsgDigest >::const_iterator
                i = md.begin(); i != md.end(); ++i ) {
                const OpFunc2Base< T1, T2 >* f =
                    dynamic_cast< const OpFunc2Base< T1, T2 >* >( i->func );
                assert( f );
                for ( vector< Eref >::const_iterator
                    j = i->targets.begin(); j != i->targets.end(); ++j ) {
                    if ( j->dataIndex() == ALLDATA ) {
                        Element* e = j->element();
                        unsigned int start = e->localDataStart();
                        unsigned int end = start + e->numData();
                        for ( unsigned int k = start; k < end; ++k )
                            f->op( Eref( e, k ), arg1, arg2 );
                    } else  {
                        f->op( *j, arg1, arg2 );
                    }
                }
            }
        }
References ALLDATA, Eref::dataIndex(), Eref::element(), Eref::Eref(), MsgDigest::func, SrcFinfo::getBindIndex(), Element::localDataStart(), Eref::msgDigest(), Element::numData(), and MsgDigest::targets.
Referenced by CylMesh::innerHandleRequestMeshStats(), CubeMesh::innerHandleRequestMeshStats(), EndoMesh::innerHandleRequestMeshStats(), PresynMesh::innerHandleRequestMeshStats(), GapJunction::process(), MMPump::process(), SrcFinfo2< T1, T2 >::sendBuffer(), ChanCommon::sendProcessMsgs(), ChanCommon::sendReinitMsgs(), testSharedMsg(), moose::Compartment::vInitProc(), SymCompartment::vInitProc(), DifBuffer::vProcess(), DifShell::vProcess(), DifBuffer::vReinit(), and DifShell::vReinit().
sendBuffer()
template<class T1 , class T2 > void SrcFinfo2< T1, T2 >::sendBuffer (const Eref & e, double * buf) const inline virtual
Sends contents of buffer on to msg targets Buffer has a header with the TgtInfo.
Implements SrcFinfo.
Definition at line 270 of file SrcFinfo.h.
        {
            // Note that buf2val alters the buf ptr as a side-effect, in
            // order to advance to the next argument. However, the order
            // in which argument evaluation is called within a multi-
            // argument function is undefined. So we have to explicitly
            // ensure the ordering of argument calls.
            const T1& arg1 = Conv< T1 >::buf2val( &buf );
            send( e, arg1, Conv< T2 >::buf2val( &buf ) );
        }
References SrcFinfo2< T1, T2 >::send().
sendTo()
template<class T1 , class T2 > void SrcFinfo2< T1, T2 >::sendTo (const Eref & e, Id tgt, const T1 & arg1, const T2 & arg2) const inline
Definition at line 244 of file SrcFinfo.h.
        {
            const vector< MsgDigest >& md = e.msgDigest( getBindIndex() );
            for ( vector< MsgDigest >::const_iterator
                i = md.begin(); i != md.end(); ++i ) {
                const OpFunc2Base< T1, T2 >* f =
                    dynamic_cast< const OpFunc2Base< T1, T2 >* >( i->func );
                assert( f );
                for ( vector< Eref >::const_iterator
                    j = i->targets.begin(); j != i->targets.end(); ++j ) {
                    if ( j->element() != tgt.element() )
                        continue; // Wasteful unless very few dests.
                    if ( j->dataIndex() == ALLDATA ) {
                        Element* e = j->element();
                        unsigned int start = e->localDataStart();
                        unsigned int end = start + e->numData();
                        for ( unsigned int k = start; k < end; ++k )
                            f->op( Eref( e, k ), arg1, arg2 );
                    } else  {
                        f->op( *j, arg1, arg2 );
                    }
                }
            }
        }
References ALLDATA, Eref::dataIndex(), Eref::element(), Id::element(), Eref::Eref(), MsgDigest::func, SrcFinfo::getBindIndex(), Element::localDataStart(), Eref::msgDigest(), Element::numData(), and MsgDigest::targets.
The documentation for this class was generated from the following file:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/basecode/SrcFinfo.h