MOOSE - Multiscale Object Oriented Simulation Environment: ZombieCaConc Class Reference
ZombieCaConc Class Reference
#include <ZombieCaConc.h>
Public Member Functions
void vCurrent (const Eref &e, double I)
void vCurrentFraction (const Eref &e, double I, double fraction)
void vDecrease (const Eref &e, double I)
double vGetB (const Eref &e) const
double vGetCa (const Eref &e) const
double vGetCaBasal (const Eref &e) const
double vGetCeiling (const Eref &e) const
double vGetFloor (const Eref &e) const
double vGetTau (const Eref &e) const
void vIncrease (const Eref &e, double I)
void vProcess (const Eref &e, ProcPtr info)
void vReinit (const Eref &e, ProcPtr info)
void vSetB (const Eref &e, double val)
void vSetCa (const Eref &e, double val)
void vSetCaBasal (const Eref &e, double val)
void vSetCeiling (const Eref &e, double val)
void vSetFloor (const Eref &e, double val)
void vSetSolver (const Eref &e, Id hsolve)
Used to set up the solver. Dummy for regular classes.
void vSetTau (const Eref &e, double val)
ZombieCaConc ()
Public Member Functions inherited from CaConcBase
CaConcBase ()
void current (const Eref &e, double I)
void currentFraction (const Eref &e, double I, double fraction)
void decrease (const Eref &e, double I)
double getB (const Eref &e) const
double getCa (const Eref &e) const
double getCaBasal (const Eref &e) const
double getCeiling (const Eref &e) const
double getDiameter (const Eref &e) const
double getFloor (const Eref &e) const
double getLength (const Eref &e) const
double getTau (const Eref &e) const
double getThickness (const Eref &e) const
void increase (const Eref &e, double I)
void process (const Eref &, ProcPtr info)
void reinit (const Eref &, ProcPtr info)
void setB (const Eref &e, double val)
void setCa (const Eref &e, double val)
void setCaBasal (const Eref &e, double val)
void setCeiling (const Eref &e, double val)
void setDiameter (const Eref &e, double val)
void setFloor (const Eref &e, double val)
void setLength (const Eref &e, double val)
void setTau (const Eref &e, double val)
void setThickness (const Eref &e, double val)
void updateDimensions (const Eref &e)
Static Public Member Functions
static const Cinfo * initCinfo ()
Static Public Member Functions inherited from CaConcBase
static SrcFinfo1< double > * concOut ()
static const Cinfo * initCinfo ()
static void zombify (Element *orig, const Cinfo *zClass, Id hsolve)
Private Attributes
double B_
HSolve * hsolve_
double tau_
double thickness_
Detailed Description
Zombie object that lets HSolve do its calculations, while letting the user interact with this object as if it were the original object.
Definition at line 18 of file ZombieCaConc.h.
Constructor & Destructor Documentation
ZombieCaConc()
ZombieCaConc::ZombieCaConc () inline
Definition at line 21 of file ZombieCaConc.h.
        : CaConcBase(),
        hsolve_( NULL ),
        tau_( 0.0 ),
        B_( 0.0 ),
        thickness_( 0.0 )
    {
        ;
    }
References B_, CaConcBase::CaConcBase(), hsolve_, tau_, and thickness_.
Member Function Documentation
initCinfo()
const Cinfo * ZombieCaConc::initCinfo () static
Definition at line 21 of file ZombieCaConc.cpp.
{
    static string doc[] =
    {
        "Name", "ZombieCaConc",
        "Author", "Upinder S. Bhalla, 2007, NCBS",
        "Description", "ZombieCaConc: Calcium concentration pool. Takes current from a "
                "channel and keeps track of calcium buildup and depletion by a "
                "single exponential process. ",
    };
    static Dinfo< ZombieCaConc > dinfo;
    static Cinfo zombieCaConcCinfo(
        "ZombieCaConc",
        CaConcBase::initCinfo(),
        0,
        0,
        &dinfo,
        doc,
        sizeof( doc )/ sizeof( string )
    );
    return &zombieCaConcCinfo;
}
References Cinfo::Cinfo(), and CaConcBase::initCinfo().
Referenced by HSolve::zombify().
vCurrent()
void ZombieCaConc::vCurrent (const Eref & e, double I) virtual
Implements CaConcBase.
Definition at line 128 of file ZombieCaConc.cpp.
{
    //~ activation_ += I;
    hsolve_->iCa( e.id(), I );
}
References hsolve_, HSolve::iCa(), and Eref::id().
vCurrentFraction()
void ZombieCaConc::vCurrentFraction (const Eref & e, double I, double fraction) virtual
Implements CaConcBase.
Definition at line 134 of file ZombieCaConc.cpp.
{
    //~ activation_ += I * fraction;
}
vDecrease()
void ZombieCaConc::vDecrease (const Eref & e, double I) virtual
Implements CaConcBase.
Definition at line 144 of file ZombieCaConc.cpp.
{
    //~ activation_ -= fabs( I );
}
vGetB()
double ZombieCaConc::vGetB (const Eref & e) const virtual
Implements CaConcBase.
Definition at line 89 of file ZombieCaConc.cpp.
{
    return B_;
}
References B_.
vGetCa()
double ZombieCaConc::vGetCa (const Eref & e) const virtual
Implements CaConcBase.
Definition at line 57 of file ZombieCaConc.cpp.
{
    return hsolve_->getCa( e.id() );
}
References HSolve::getCa(), hsolve_, and Eref::id().
vGetCaBasal()
double ZombieCaConc::vGetCaBasal (const Eref & e) const virtual
Implements CaConcBase.
Definition at line 67 of file ZombieCaConc.cpp.
{
    return hsolve_->getCaBasal( e.id() );
}
References HSolve::getCaBasal(), hsolve_, and Eref::id().
vGetCeiling()
double ZombieCaConc::vGetCeiling (const Eref & e) const virtual
Implements CaConcBase.
Definition at line 99 of file ZombieCaConc.cpp.
{
    return hsolve_->getCaCeiling( e.id() );
}
References HSolve::getCaCeiling(), hsolve_, and Eref::id().
vGetFloor()
double ZombieCaConc::vGetFloor (const Eref & e) const virtual
Implements CaConcBase.
Definition at line 109 of file ZombieCaConc.cpp.
{
    return hsolve_->getCaFloor( e.id() );
}
References HSolve::getCaFloor(), hsolve_, and Eref::id().
vGetTau()
double ZombieCaConc::vGetTau (const Eref & e) const virtual
Implements CaConcBase.
Definition at line 78 of file ZombieCaConc.cpp.
{
    return tau_;
}
References tau_.
vIncrease()
void ZombieCaConc::vIncrease (const Eref & e, double I) virtual
Implements CaConcBase.
Definition at line 139 of file ZombieCaConc.cpp.
{
    //~ activation_ += fabs( I );
}
vProcess()
void ZombieCaConc::vProcess (const Eref & e, ProcPtr info) virtual
Implements CaConcBase.
Definition at line 123 of file ZombieCaConc.cpp.
{
    ;
}
vReinit()
void ZombieCaConc::vReinit (const Eref & e, ProcPtr info) virtual
Implements CaConcBase.
Definition at line 118 of file ZombieCaConc.cpp.
{
    ;
}
vSetB()
void ZombieCaConc::vSetB (const Eref & e, double val) virtual
Implements CaConcBase.
Definition at line 83 of file ZombieCaConc.cpp.
{
    B_ = B;
    hsolve_->setTauB( e.id(), tau_, B_ );
}
References B_, hsolve_, Eref::id(), HSolve::setTauB(), and tau_.
vSetCa()
void ZombieCaConc::vSetCa (const Eref & e, double val) virtual
Implements CaConcBase.
Definition at line 52 of file ZombieCaConc.cpp.
{
    hsolve_->setCa( e.id(), Ca );
}
References hsolve_, Eref::id(), and HSolve::setCa().
vSetCaBasal()
void ZombieCaConc::vSetCaBasal (const Eref & e, double val) virtual
Implements CaConcBase.
Definition at line 62 of file ZombieCaConc.cpp.
{
    hsolve_->setCa( e.id(), CaBasal );
}
References hsolve_, Eref::id(), and HSolve::setCa().
vSetCeiling()
void ZombieCaConc::vSetCeiling (const Eref & e, double val) virtual
Implements CaConcBase.
Definition at line 94 of file ZombieCaConc.cpp.
{
    hsolve_->setCaCeiling( e.id(), ceiling );
}
References hsolve_, Eref::id(), and HSolve::setCaCeiling().
vSetFloor()
void ZombieCaConc::vSetFloor (const Eref & e, double val) virtual
Implements CaConcBase.
Definition at line 104 of file ZombieCaConc.cpp.
{
    hsolve_->setCaFloor( e.id(), floor );
}
References hsolve_, Eref::id(), and HSolve::setCaFloor().
vSetSolver()
void ZombieCaConc::vSetSolver (const Eref & e, Id hsolve) virtual
Used to set up the solver. Dummy for regular classes.
Reimplemented from CaConcBase.
Definition at line 150 of file ZombieCaConc.cpp.
{
    if ( !hsolve.element()->cinfo()->isA( "HSolve" ) ) {
        cout << "Error: ZombieCaConc::vSetSolver: Object: " <<
                hsolve.path() << " is not an HSolve. Aborted\n";
        hsolve_ = 0;
        return;
    }
    hsolve_ = reinterpret_cast< HSolve* >( hsolve.eref().data() );
}
References Element::cinfo(), Eref::data(), Id::element(), Id::eref(), hsolve_, Cinfo::isA(), and Id::path().
vSetTau()
void ZombieCaConc::vSetTau (const Eref & e, double val) virtual
Implements CaConcBase.
Definition at line 72 of file ZombieCaConc.cpp.
{
    tau_ = tau;
    hsolve_->setTauB( e.id(), tau_, B_ );
}
References B_, hsolve_, Eref::id(), HSolve::setTauB(), and tau_.
Member Data Documentation
B_
double ZombieCaConc::B_ private
Definition at line 66 of file ZombieCaConc.h.
Referenced by vGetB(), vSetB(), vSetTau(), and ZombieCaConc().
hsolve_
HSolve* ZombieCaConc::hsolve_ private
Definition at line 63 of file ZombieCaConc.h.
Referenced by vCurrent(), vGetCa(), vGetCaBasal(), vGetCeiling(), vGetFloor(), vSetB(), vSetCa(), vSetCaBasal(), vSetCeiling(), vSetFloor(), vSetSolver(), vSetTau(), and ZombieCaConc().
tau_
double ZombieCaConc::tau_ private
Definition at line 65 of file ZombieCaConc.h.
Referenced by vGetTau(), vSetB(), vSetTau(), and ZombieCaConc().
thickness_
double ZombieCaConc::thickness_ private
Definition at line 67 of file ZombieCaConc.h.
Referenced by ZombieCaConc().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/hsolve/ZombieCaConc.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/hsolve/ZombieCaConc.cpp