MOOSE - Multiscale Object Oriented Simulation Environment: Conv< vector< T > > Class Template Reference
Conv< vector< T > > Class Template Reference
#include <Conv.h>
Static Public Member Functions
static const vector< T > buf2val (double **buf)
static string rttiType ()
static unsigned int size (const vector< T > &val)
static void str2val (vector< T > &val, const string &s)
static void val2buf (const vector< T > &val, double **buf)
static void val2str (string &s, const vector< T > &val)
Detailed Description
template<class T>
class Conv< vector< T > >
Trying to do a partial specialization. This works with anything that has a uniform size. Assume strings are the only exception. The first double in the vector vec_ holds the # of data entries that follow it. This excludes the space for the size entry itself.
Definition at line 615 of file Conv.h.
Member Function Documentation
buf2val()
template<class T > static const vector< T > Conv< vector< T > >::buf2val (double ** buf) inline static
Definition at line 630 of file Conv.h.
        {
            static vector< T > ret;
            ret.clear();
            unsigned int numEntries = (unsigned int)**buf; // first entry is vec size
            (*buf)++;
            for ( unsigned int i = 0; i < numEntries; ++i )
                ret.push_back( Conv< T >::buf2val( buf ) );
            return ret;
        }
Referenced by testConvVector().
rttiType()
template<class T > static string Conv< vector< T > >::rttiType () inline static
Definition at line 658 of file Conv.h.
{
            string ret = "vector<" + Conv< T >::rttiType() + ">";
            return ret;
        }
size()
template<class T > static unsigned int Conv< vector< T > >::size (const vector< T > & val) inline static
Size of returned array in doubles.
Definition at line 621 of file Conv.h.
        {
            unsigned int ret = 1;
            for ( unsigned int i = 0; i < val.size(); ++i ) {
                ret += Conv< T >::size( val[i] );
            }
            return ret;
        }
Referenced by testConvVector().
str2val()
template<class T > static void Conv< vector< T > >::str2val (vector< T > & val, const string & s) inline static
Definition at line 651 of file Conv.h.
{
            cout << "Specialized Conv< vector< T > >::str2val not done\n";
        }
val2buf()
template<class T > static void Conv< vector< T > >::val2buf (const vector< T > & val, double ** buf) inline static
Definition at line 641 of file Conv.h.
        {
            double* temp = *buf;
            *temp++ = (double)val.size();
            for( unsigned int i = 0; i < val.size(); ++i ) {
                Conv< T >::val2buf( val[i], &temp );
            }
            *buf = temp;
        }
Referenced by testConvVector().
val2str()
template<class T > static void Conv< vector< T > >::val2str (string & s, const vector< T > & val) inline static
Definition at line 655 of file Conv.h.
{
            cout << "Specialized Conv< vector< T > >::val2str not done\n";
        }
The documentation for this class was generated from the following file:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/basecode/Conv.h