MOOSE - Multiscale Object Oriented Simulation Environment: NeuroNode Class Reference
NeuroNode Class Reference
#include <NeuroNode.h>
Public Member Functions
void addChild (unsigned int child)
double calculateLength (const CylBase &parent)
const vector< unsigned int > & children () const
void clearChildren ()
Id elecCompt () const
void findConnectedCompartments (const map< Id, unsigned int > &nodeMap, const vector< NeuroNode > &nodes)
void innerTraverse (vector< NeuroNode > &tree, const vector< NeuroNode > &nodes, vector< unsigned int > &seen) const
bool isDummyNode () const
bool isSphere () const
bool isStartNode () const
NeuroNode ()
NeuroNode (const CylBase &cb, unsigned int parent, const vector< unsigned int > &children, unsigned int startFid_, Id elecCompt, bool isSphere)
NeuroNode (Id elecCompt)
unsigned int parent () const
void setParent (unsigned int parent)
void setParentAndChildren (unsigned int index, int dendParent, vector< NeuroNode > &nodes, const unordered_map< Id, unsigned int > &dendMap)
void setStartFid (unsigned int f)
unsigned int startFid () const
Public Member Functions inherited from CylBase
CylBase ()
CylBase (double x, double y, double z, double dia, double length, unsigned int numDivs)
vector< double > getCoordinates (const CylBase &parent, unsigned int entry) const
double getDia () const
double getDiffusionArea (const CylBase &parent, unsigned int index) const
bool getIsCylinder () const
double getLength () const
double getMiddleArea (const CylBase &parent, unsigned int index) const
Return cross-section area of middle of specified voxel.
unsigned int getNumDivs () const
double getVoxelLength () const
Return length of voxel. All are equal.
double getX () const
double getY () const
double getZ () const
void matchCubeMeshEntries (const ChemCompt *other, const CylBase &parent, unsigned int startIndex, double granularity, vector< VoxelJunction > &ret, bool useCylinderCurve, bool useCylinderCap) const
double nearest (double x, double y, double z, const CylBase &parent, double &linePos, double &r) const
double nearest (double x, double y, double z, const CylBase &parent, unsigned int &index) const
double selectGridSize (double h, double dia1, double granularity) const
void setDia (double v)
void setIsCylinder (bool v)
void setLength (double v)
void setNumDivs (unsigned int v)
void setX (double v)
void setY (double v)
void setZ (double v)
double volume (const CylBase &parent) const
Returns vol of current node. Usually needs to refer to parent.
double voxelVolume (const CylBase &parent, unsigned int fid) const
Static Public Member Functions
static void buildSpinyTree (vector< ObjId > &elist, vector< NeuroNode > &nodes, vector< Id > &shaftId, vector< Id > &headId, vector< unsigned int > &spineParent)
static void buildTree (vector< NeuroNode > &nodes, vector< ObjId > elist)
static void filterSpines (vector< NeuroNode > &nodes, vector< Id > &shaftId, vector< Id > &headId, vector< unsigned int > &parent)
static unsigned int findStartNode (const vector< NeuroNode > &nodes)
static unsigned int removeDisconnectedNodes (vector< NeuroNode > &nodes)
static void traverse (vector< NeuroNode > &nodes, unsigned int start)
Private Attributes
vector< unsigned int > children_
Id elecCompt_
Id of electrical compartment in which this diffusive compt lives.
bool isSphere_
unsigned int parent_
unsigned int startFid_
Detailed Description
Helper class for the NeuroMesh. Defines the geometry of the branching neuron.
Definition at line 18 of file NeuroNode.h.
Constructor & Destructor Documentation
NeuroNode() [1/3]
NeuroNode::NeuroNode (const CylBase & cb, unsigned int parent, const vector< unsigned int > & children, unsigned int startFid, Id elecCompt, bool isSphere)
This function explicitly fills in all fields of the NeuroNode
Helper class for the NeuroMesh. Defines the geometry of the branching neuron.
Definition at line 28 of file NeuroNode.cpp.
        :
                CylBase( cb ),
                parent_( parent ),
                children_( children ),
                startFid_( startFid ),
                elecCompt_( elecCompt ),
                isSphere_( isSphere )
{;}
References children_, elecCompt_, isSphere_, parent_, and startFid_.
Referenced by NeuroMesh::innerBuildDefaultMesh().
NeuroNode() [2/3]
NeuroNode::NeuroNode (Id elecCompt)
This builds the node using info from the compartment. But the parent and children have to be filled in later
Definition at line 41 of file NeuroNode.cpp.
        :
                parent_( ~0 ),
                startFid_( 0 ),
                elecCompt_( elecCompt ),
                isSphere_( false )
{
    double dia = Field< double >::get( elecCompt, "diameter" );
    setDia( dia );
    double length = Field< double >::get( elecCompt, "length" );
    setLength( length );
    double x = Field< double >::get( elecCompt, "x" );
    double y = Field< double >::get( elecCompt, "y" );
    double z = Field< double >::get( elecCompt, "z" );
    setX( x );
    setY( y );
    setZ( z );
}
References elecCompt_, Field< A >::get(), isSphere_, parent_, CylBase::setDia(), CylBase::setLength(), CylBase::setX(), CylBase::setY(), CylBase::setZ(), and startFid_.
Referenced by buildSpinyTree(), and buildTree().
NeuroNode() [3/3]
NeuroNode::NeuroNode ()
Empty constructor for vectors
Definition at line 61 of file NeuroNode.cpp.
        :
                parent_( ~0 ),
                startFid_( 0 ),
                elecCompt_( Id() ),
                isSphere_( false )
{;}
References elecCompt_, Id::Id(), isSphere_, parent_, and startFid_.
Member Function Documentation
addChild()
void NeuroNode::addChild (unsigned int child)
Fills in child vector
Definition at line 101 of file NeuroNode.cpp.
{
    children_.push_back( child );
}
References children_.
Referenced by NeuroMesh::insertDummyNodes(), NeuroMesh::insertSingleDummy(), reassignNodeIndices(), and setParentAndChildren().
buildSpinyTree()
void NeuroNode::buildSpinyTree (vector< ObjId > & elist, vector< NeuroNode > & nodes, vector< Id > & shaftId, vector< Id > & headId, vector< unsigned int > & spineParent) static
This function takes a list of elements and builds a tree. Info on any attached spines are placed in the shaft_, head_, and parent_ vectors. The list of elements can be discontiguous. This is meant to be insensitive to vagaries in how the user has set up the compartment messaging, provided that there is at least one recognized message between connected compartments.
static function.
Definition at line 491 of file NeuroNode.cpp.
{
    nodes.clear();
    sort( elist.begin(), elist.end() );
    unordered_map< Id, unsigned int > dendMap;
    vector< Id > dend;
    for ( vector< ObjId >::iterator
        i = elist.begin(); i != elist.end(); ++i ) {
        if ( isPartOfDend( *i ) ) {
            dendMap[ *i ] = dend.size();
            //cout << "st: dendMap[" << *i << "] = " << dend.size() << endl;
            dend.push_back( *i );
        }
    }
    vector< int > seen( dend.size(), 0 );
    vector< int > dendParent( dend.size(), -1 );
    int numSeen = 0;
    for ( unsigned int i = 0; i < dend.size(); ++i ) {
        if ( !seen[i] )
            spinyTraverse( i, dend, dendMap, seen, ++numSeen,
            shaftId, headId,
            dendParent, spineParent );
    }
    // Here I sort by shaftIds. I have 4 parallel arrays, so I get the
    // Index order of the whole lot that will sort the shaftIds.
    sortByShaftIds( shaftId, headId, spineParent );
    if ( numSeen == 0 )
        return;
    for ( unsigned int i = 0; i < dend.size(); ++i )
        nodes.push_back( NeuroNode( dend[i] ) );
    for ( unsigned int i = 0; i < dend.size(); ++i )
        nodes[i].setParentAndChildren( i, dendParent[i], nodes, dendMap );
    if ( numSeen > 1 ) {
        cout << "Warning: NeuroNode::buildSpinyTree: There are " <<
            numSeen << " distinct subgroups on the given path\n";
    }
}
References isPartOfDend(), NeuroNode(), setParentAndChildren(), sortByShaftIds(), and spinyTraverse().
Referenced by NeuroMesh::setSubTree().
buildTree()
void NeuroNode::buildTree (vector< NeuroNode > & nodes, vector< ObjId > elist) static
This function takes a list of elements that include connected compartments, and constructs a tree of nodes out of them. The generated nodes vector starts with the soma, and is a depth-first sequence of nodes. This is meant to be insensitive to vagaries in how the user has set up the compartment messaging, provided that there is at least one recognized message between connected compartments.
This function takes a list of elements that include connected compartments, and constructs a tree of nodes out of them. The generated nodes vector starts with the soma, and is a depth-first sequence of nodes. This is meant to be insensitive to vagaries in how the user has set up the compartment messaging, provided that there is at least one recognized message between connected compartments.
static function.
Definition at line 558 of file NeuroNode.cpp.
{
    nodes.clear();
    map< Id, unsigned int > nodeMap;
    for ( vector< ObjId >::iterator
        i = elist.begin(); i != elist.end(); ++i ) {
        if ( i->element()->cinfo()->isA( "CompartmentBase" ) )
            nodes.push_back( NeuroNode( *i ) );
    }
    if ( nodes.size() <= 1 )
        return;
    for ( unsigned int i = 0; i < nodes.size(); ++i ) {
        if ( nodeMap.find( nodes[i].elecCompt() ) != nodeMap.end() ) {
            cout << "Warning: NeuroNode.buildTree(): Node[" << i <<
                "] refers to existing compartment: " <<
                nodes[i].elecCompt().path() << endl;
        }
        nodeMap[ nodes[i].elecCompt() ] = i;
    }
    assert( nodeMap.size() == nodes.size() );
    for ( unsigned int i = 0; i < nodes.size(); ++i )
        nodes[i].findConnectedCompartments( nodeMap, nodes );
    unsigned int numRemoved = removeDisconnectedNodes( nodes );
    if ( numRemoved > 0 ) {
        cout << "Warning: NeuroNode::buildTree: Removed " <<
                numRemoved << " nodes because they were not connected\n";
    }
    unsigned int start = findStartNode( nodes );
    traverse( nodes, start );
}
References Element::cinfo(), elecCompt(), ObjId::element(), findConnectedCompartments(), findStartNode(), Cinfo::isA(), NeuroNode(), Id::path(), removeDisconnectedNodes(), and traverse().
Referenced by NeuroMesh::setSubTree().
calculateLength()
double NeuroNode::calculateLength (const CylBase & parent)
Calculates and returns compartment length, from parent xyz to self xyz. Assigns own length as a side-effect.
Definition at line 121 of file NeuroNode.cpp.
{
    if ( &parent == this ) // Do nothing
            return getLength();
    double dx = parent.getX() - getX();
    double dy = parent.getY() - getY();
    double dz = parent.getZ() - getZ();
    double ret = sqrt( dx * dx + dy * dy + dz * dz );
    setLength( ret );
    return ret;
}
References CylBase::getLength(), CylBase::getX(), CylBase::getY(), CylBase::getZ(), and CylBase::setLength().
Referenced by NeuroMesh::insertSingleDummy().
children()
const vector< unsigned int > & NeuroNode::children () const
Definition at line 96 of file NeuroNode.cpp.
{
        return children_;
}
References children_.
Referenced by NeuroMesh::insertDummyNodes(), and reassignNodeIndices().
clearChildren()
void NeuroNode::clearChildren ()
Zeroes out the child vector
Definition at line 106 of file NeuroNode.cpp.
{
    children_.resize( 0 );
}
References children_.
Referenced by NeuroMesh::insertDummyNodes(), NeuroMesh::insertSingleDummy(), and reassignNodeIndices().
elecCompt()
Id NeuroNode::elecCompt () const
Definition at line 79 of file NeuroNode.cpp.
{
        return elecCompt_;
}
References elecCompt_.
Referenced by buildTree(), diagnoseTree(), filterSpines(), NeuroMesh::getDendVoxelsOnCompartment(), NeuroMesh::getElecComptList(), NeuroMesh::getElecComptMap(), NeuroMesh::insertDummyNodes(), and NeuroMesh::putSomaAtStart().
filterSpines()
void NeuroNode::filterSpines (vector< NeuroNode > & nodes, vector< Id > & shaftId, vector< Id > & headId, vector< unsigned int > & parent) static
Trims off all spines from tree. Does so by identifying a set of reasonable names: shaft, head, spine, and variants in capitals. Having done this it builds two matching vectors of vector of shafts and heads, which is a hack that assumes that there are no sub-branches in spines. The returned nodes vector has non spine/shaft compartments only. The returned shaftId vector has all the shaft compartments. The returned headId vector has all the shaft compartments. The returned parent vector has the indices of the parent node for each shaft. There should be exactly the same number of entries in the shaftId, headId and parent vectors.
Trims off all spines from tree. Does so by identifying a set of reasonable names: shaft, head, spine, and variants in capitals. Having done this it builds two matching vectors of vector of shafts and heads, which is a hack that assumes that there are no sub-branches in spines. Then there is an index for parent NeuroNode entry. Static function
Definition at line 620 of file NeuroNode.cpp.
{
    headId.clear();
    shaftId.clear();
    parent.clear();
    vector< NeuroNode > temp;
    temp.reserve( nodes.size() );
    vector< unsigned int > nodeToTempMap( nodes.size(), ~0U );
    vector< unsigned int > shaft;
    vector< unsigned int > reverseShaft( nodes.size(), ~0U );
    vector< unsigned int > head;
    for ( unsigned int i = 0; i < nodes.size(); ++i ) {
        const NeuroNode& n = nodes[i];
        string name = n.elecCompt_.element()->getName();
        for ( string::iterator j = name.begin(); j != name.end(); ++j )
            *j = tolower(*j);
        if ( name.find( "shaft" ) != string::npos ||
            name.find( "neck" ) != string::npos ) {
            reverseShaft[i] = shaft.size();
            shaft.push_back( i );
            // Remove from nodes vector by simply not copying.
        } else if ( name.find( "spine" ) != string::npos ||
            name.find( "head" ) != string::npos ) {
            head.push_back( i );
            // Remove from nodes vector by simply not copying.
        } else {
            nodeToTempMap[i] = temp.size();
            temp.push_back( n );
        }
        /*
        const char* name = n.elecCompt_.element()->getName().c_str();
        if ( strncasecmp( name, "shaft", 5 ) == 0 ||
            strncasecmp( name, "neck", 4 ) == 0 ||
            strncasecmp( name, "spine_neck", 10 ) == 0 ||
            strncasecmp( name, "spine_shaft", 11 ) == 0 ||
            strncasecmp( name, "stalk", 5 ) == 0 ) {
            reverseShaft[i] = shaft.size();
            shaft.push_back( i );
            // Remove from nodes vector by simply not copying.
        } else if ( strncasecmp( name, "spine", 5 ) == 0 ||
            strncasecmp( name, "head", 4 ) == 0 ) {
            head.push_back( i );
            // Remove from nodes vector by simply not copying.
        } else {
            nodeToTempMap[i] = temp.size();
            temp.push_back( n );
        }
        */
    }
    // Now go through finding spine shafts.
    for ( unsigned int i = 0; i < head.size(); ++i ) {
        const NeuroNode& n = nodes[ head[i] ];
        headId.push_back( n.elecCompt() );
        assert( reverseShaft[ n.parent() ] != ~0U );
        const NeuroNode& pa = nodes[ n.parent() ];
        shaftId.push_back( pa.elecCompt() );
        assert( nodeToTempMap[ pa.parent() ] != ~0U );
        parent.push_back( nodeToTempMap[ pa.parent() ] );
    }
    assert( shaftId.size() == headId.size() );
    reassignNodeIndices( temp, nodeToTempMap );
    nodes = temp;
}
References elecCompt(), elecCompt_, Id::element(), Element::getName(), parent(), and reassignNodeIndices().
findConnectedCompartments()
void NeuroNode::findConnectedCompartments (const map< Id, unsigned int > & nodeMap, const vector< NeuroNode > & nodes)
Finds all the compartments connected to current node, put them all into the 'children' vector even if they may be 'parent' by the messaging. This is because this function has to be robust enough to sort this out
Definition at line 198 of file NeuroNode.cpp.
{
    vector< Id > all = findAllConnectedCompartments( elecCompt_ );
    // Now we have a list of all compartments connected to the current one.
    // Convert to node indices.
    children_.resize( all.size() );
    // Note that the nodeMap only includes compts on list, which may be a
    // subset of compts in entire model. So we only want to explore those.
    for ( unsigned int i = 0; i < all.size(); ++i ) {
        map< Id, unsigned int >::const_iterator k = nodeMap.find( all[i] );
        if ( k != nodeMap.end() ) {
            children_[i] = k->second;
        } else {
            cout << "Warning: NeuroNode::findConnectedCompartments: could not find compartment " << all[i].path() << endl;
            // bruteForceFind( nodes, all[i] );
        }
    }
}
References children_, elecCompt_, findAllConnectedCompartments(), and Id::path().
Referenced by buildTree().
findStartNode()
unsigned int NeuroNode::findStartNode (const vector< NeuroNode > & nodes) static
Find the start node, typically the soma, of a model. In terms of the solution, this should be the node at the root of the tree. Returns index in nodes vector. Technically the matrix solution could begin from any terminal branch, but it helps to keep the soma identical to the root of the tree.
Uses two heuristics to locate the start node: Looks for the node with the largest diameter, and also looks for node(s) with 'soma' in their name. If these disagree then it goes with the 'soma' node. If there are many of the soma nodes, it goes with the fattest.
Find the start node, typically the soma, of a model. In terms of the solution, this should be the node at the root of the tree. Returns index in nodes vector. Technically the matrix solution could begin from any terminal branch, but it helps to keep the soma identical to the root of the tree.
Uses two heuristics to locate the start node: Looks for the node with the largest diameter, and also looks for node(s) with 'soma' in their name. If these disagree then it goes with the 'soma' node. If there are many of the soma nodes, it goes with the fattest.
static func
Definition at line 270 of file NeuroNode.cpp.
{
    double maxDia = 0.0;
    unsigned int somaIndex = ~0;
    for ( unsigned int i = 0; i < nodes.size(); ++i ) {
        const char* name = nodes[i].elecCompt_.element()->getName().c_str();
        if ( moose::strncasecmp( name, "soma", 4 ) == 0 ) {
            if ( maxDia < nodes[i].getDia() ) {
                maxDia = nodes[i].getDia();
                somaIndex = i;
            }
        }
    }
    if ( somaIndex == ~0U ) { // Didn't find any compartment called soma
        for ( unsigned int i =0; i < nodes.size(); ++i ) {
            if ( maxDia < nodes[i].getDia() ) {
                maxDia = nodes[i].getDia();
                somaIndex = i;
            }
        }
    }
    assert( somaIndex != ~0U );
    return somaIndex;
}
References elecCompt_, Id::element(), CylBase::getDia(), Element::getName(), and moose::strncasecmp().
Referenced by buildTree().
innerTraverse()
void NeuroNode::innerTraverse (vector< NeuroNode > & tree, const vector< NeuroNode > & nodes, vector< unsigned int > & seen) const
Helper recursive function for traversing nodes to build tree.
Definition at line 351 of file NeuroNode.cpp.
{
    unsigned int pa = tree.size() - 1;
    tree.back().children_.clear();
    for ( vector< unsigned int >::const_iterator i =
                    children_.begin(); i != children_.end(); ++i ) {
        assert( *i < nodes.size() );
        // Check that it is an unseen node, ie, not a parent.
        if ( seen[ *i ] == ~0U )  {
            seen[ *i ] = tree.size();
            tree[pa].children_.push_back( tree.size() );
            tree.push_back( nodes[ *i ] );
            tree.back().parent_ = pa;
            nodes[*i].innerTraverse( tree, nodes, seen );
        }
    }
    assert( tree.size() <= nodes.size() );
}
References children_, innerTraverse(), and parent_.
Referenced by innerTraverse(), and traverse().
isDummyNode()
bool NeuroNode::isDummyNode () const
True when this is a dummy node to represent the coordinates of the start end of a compartment. For example, the start coords of a compartment sitting on a spherical soma, or the start coords of a spine neck along a longer dendritic compartment. In all other cases the start coordinates are just those of the end of the parent compartment.
When the isDummyNode is true, the elecCompt represents the Id of the compartment whose start it is.
Definition at line 83 of file NeuroNode.cpp.
{
        return ( getNumDivs() == 0 );
}
References CylBase::getNumDivs().
Referenced by NeuroMesh::getAdx(), NeuroMesh::getDendVoxelsOnCompartment(), NeuroMesh::getElecComptList(), NeuroMesh::getEndVoxelInCompt(), NeuroMesh::getNumSegments(), NeuroMesh::getStartVoxelInCompt(), NeuroMesh::innerSetNumEntries(), NeuroMesh::insertDummyNodes(), NeuroMesh::matchCubeMeshEntries(), NeuroMesh::nearest(), NeuroMesh::updateCoords(), and NeuroMesh::vGetVoxelMidpoint().
isSphere()
bool NeuroNode::isSphere () const
Definition at line 87 of file NeuroNode.cpp.
{
        return isSphere_;
}
References isSphere_.
Referenced by NeuroMesh::getMeshType(), and NeuroMesh::innerSetNumEntries().
isStartNode()
bool NeuroNode::isStartNode () const
Definition at line 91 of file NeuroNode.cpp.
{
        return ( startFid_ == 0 );
}
References startFid_.
parent()
unsigned int NeuroNode::parent () const
Definition at line 69 of file NeuroNode.cpp.
{
        return parent_;
}
References parent_.
Referenced by diagnoseTree(), filterSpines(), NeuroMesh::getAdx(), NeuroMesh::getCoordinates(), NeuroMesh::getDiffusionArea(), NeuroMesh::getMeshEntryVolume(), NeuroMesh::indexToSpace(), NeuroMesh::insertDummyNodes(), NeuroMesh::matchCubeMeshEntries(), NeuroMesh::nearest(), reassignNodeIndices(), NeuroMesh::updateCoords(), NeuroMesh::updateShaftParents(), and NeuroMesh::vGetVoxelMidpoint().
removeDisconnectedNodes()
unsigned int NeuroNode::removeDisconnectedNodes (vector< NeuroNode > & nodes) static
Go through nodes vector and eliminate entries that have zero children, that is, are not connected to any others. Need to clean up 'children_' list after this is called.
Go through nodes vector and eliminate entries that have zero children, that is, are not connected to any others. Need to clean up 'children_' list.
static func
Definition at line 227 of file NeuroNode.cpp.
{
    vector< NeuroNode > temp;
    vector< unsigned int > nodeMap( nodes.size() );
    unsigned int j = 0;
    for ( unsigned int i = 0; i < nodes.size(); ++i ) {
        if ( nodes[i].children_.size() > 0 ) {
            temp.push_back( nodes[i] );
            nodeMap[i] = j;
            ++j;
        } else {
            nodeMap[i] = ~0;
        }
    }
    for ( unsigned int i = 0; i < temp.size(); ++i ) {
        vector< unsigned int >& c = temp[i].children_;
        for ( vector< unsigned int >::iterator
                        j = c.begin(); j != c.end(); ++j ) {
            assert( nodeMap[ *j ] != ~0U );
            *j = nodeMap[ *j ];
        }
    }
    unsigned int numRemoved = nodes.size() - temp.size();
    nodes = temp;
    return numRemoved;
}
References children_.
Referenced by buildTree().
setParent()
void NeuroNode::setParent (unsigned int parent)
Assigns parent node info
Definition at line 111 of file NeuroNode.cpp.
{
    parent_ = parent;
}
References parent_.
Referenced by NeuroMesh::insertSingleDummy(), and reassignNodeIndices().
setParentAndChildren()
void NeuroNode::setParentAndChildren (unsigned int index, int dendParent, vector< NeuroNode > & nodes, const unordered_map< Id, unsigned int > & dendMap)
Definition at line 533 of file NeuroNode.cpp.
{
    if (dendParent < 0 || static_cast< unsigned int >(dendParent) >= nodes.size() )
        return;
    parent_ = dendParent;
    const unordered_map< Id, unsigned int >::const_iterator dendLookup =
            dendMap.find( nodes[dendParent].elecCompt_ );
    if ( dendLookup != dendMap.end() ) {
        assert( dendLookup->second < nodes.size() );
        nodes[ dendLookup->second ].addChild( index );
    }
}
References addChild(), elecCompt_, and parent_.
Referenced by buildSpinyTree().
setStartFid()
void NeuroNode::setStartFid (unsigned int f)
Assignes startFid
Definition at line 116 of file NeuroNode.cpp.
{
    startFid_ = fid;
}
References startFid_.
Referenced by NeuroMesh::updateCoords().
startFid()
unsigned int NeuroNode::startFid () const
Definition at line 74 of file NeuroNode.cpp.
{
        return startFid_;
}
References startFid_.
Referenced by NeuroMesh::getAdx(), NeuroMesh::getCoordinates(), NeuroMesh::getDendVoxelsOnCompartment(), NeuroMesh::getDiffusionArea(), NeuroMesh::getEndVoxelInCompt(), NeuroMesh::getMeshEntryVolume(), NeuroMesh::getStartVoxelInCompt(), NeuroMesh::indexToSpace(), NeuroMesh::matchCubeMeshEntries(), NeuroMesh::nearest(), NeuroMesh::updateCoords(), and NeuroMesh::updateShaftParents().
traverse()
void NeuroNode::traverse (vector< NeuroNode > & nodes, unsigned int start) static
Traverses the nodes list starting from the 'start' node, and sets up correct parent-child information. This involves removing the identified 'parent' node from the 'children_' vector and assigning it to the parent_ field. Then it redoes the entire nodes vector (with due care for indexing of children and parents) so that it is in the correct order for a depth-first traversal. This means that you can take any entry in the list, and the immediately following entries will be all the descendants, if any.
Traverses the nodes list starting from the 'start' node, and sets up correct parent-child information. This involves removing the identified 'parent' node from the 'children_' vector and assigning it to the parent_ field. Then it redoes the entire nodes vector (with due care for indexing of children and parents) so that it is in the correct order for a depth-first traversal. This means that you can take any entry in the list, and the immediately following entries will be all the descendants, if any.
Static func
Definition at line 332 of file NeuroNode.cpp.
{
    vector< unsigned int > seen( nodes.size(), ~0 );
    vector< NeuroNode > tree;
    tree.reserve( nodes.size() );
    seen[ start ] = 0;
    tree.push_back( nodes[ start ] );
    tree.back().parent_ = ~0;
    nodes[start].innerTraverse( tree, nodes, seen );
    if ( tree.size() < nodes.size() ) {
        cout << "Warning: NeuroNode::traverse() unable to traverse all nodes:\n";
       cout << "Traversed= " << tree.size() << " < total numNodes = " << nodes.size() << endl;
       cout << "This situation may arise if the CellPortion has disjoint compartments\n";
        diagnoseTree( tree, nodes );
    }
    nodes = tree;
}
References diagnoseTree(), innerTraverse(), and parent_.
Referenced by buildTree().
Member Data Documentation
children_
vector< unsigned int > NeuroNode::children_ private
Index of children of this NeuroNode.
Definition at line 202 of file NeuroNode.h.
Referenced by addChild(), children(), clearChildren(), findConnectedCompartments(), innerTraverse(), NeuroNode(), and removeDisconnectedNodes().
elecCompt_
Id NeuroNode::elecCompt_ private
Id of electrical compartment in which this diffusive compt lives.
Definition at line 212 of file NeuroNode.h.
Referenced by elecCompt(), filterSpines(), findConnectedCompartments(), findStartNode(), NeuroNode(), NeuroNode(), NeuroNode(), and setParentAndChildren().
isSphere_
bool NeuroNode::isSphere_ private
Special case for soma, perhaps for spine heads. When true, xyz are centre, and dia is dia.
Definition at line 218 of file NeuroNode.h.
Referenced by isSphere(), NeuroNode(), NeuroNode(), and NeuroNode().
parent_
unsigned int NeuroNode::parent_ private
Index of parent NeuroNode, typically a diffusive compartment. In the special case where the junction to the parent electrical compartment is NOT at the end of the parent compartment, this refers instead to a dummy NeuroNode which has the coordinates.
One of the nodes, typically the soma, will have no parent. This is indicated by the value ~0U.
Definition at line 197 of file NeuroNode.h.
Referenced by innerTraverse(), NeuroNode(), NeuroNode(), NeuroNode(), parent(), setParent(), setParentAndChildren(), and traverse().
startFid_
unsigned int NeuroNode::startFid_ private
Index of starting MeshEntry handled by this NeuroNode. Assumes a block of contiguous fids are handled by each NeuroNode.
Definition at line 208 of file NeuroNode.h.
Referenced by isStartNode(), NeuroNode(), NeuroNode(), NeuroNode(), setStartFid(), and startFid().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/mesh/NeuroNode.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/mesh/NeuroNode.cpp