MOOSE - Multiscale Object Oriented Simulation Environment: Dinfo< D > Class Template Reference
Dinfo< D > Class Template Reference
#include <Dinfo.h>
Public Member Functions
char * allocData (unsigned int numData) const
void assignData (char *data, unsigned int copyEntries, const char *orig, unsigned int origEntries) const
char * copyData (const char *orig, unsigned int origEntries, unsigned int copyEntries, unsigned int startEntry) const
void destroyData (char *d) const
Dinfo ()
Dinfo (bool isOneZombie)
bool isA (const DinfoBase *other) const
unsigned int size () const
unsigned int sizeIncrement () const
Public Member Functions inherited from DinfoBase
DinfoBase ()
DinfoBase (bool isOneZombie)
bool isOneZombie () const
virtual ~DinfoBase ()
Private Attributes
unsigned int sizeIncrement_
Detailed Description
template<class D>
class Dinfo< D >
Definition at line 60 of file Dinfo.h.
Constructor & Destructor Documentation
Dinfo() [1/2]
template<class D > Dinfo< D >::Dinfo () inline
Definition at line 63 of file Dinfo.h.
            : sizeIncrement_( sizeof( D ) )
        {;}
References Dinfo< D >::sizeIncrement_.
Referenced by TestId::initCinfo(), and Cell::initCinfo().
Dinfo() [2/2]
template<class D > Dinfo< D >::Dinfo (bool isOneZombie) inline
Definition at line 66 of file Dinfo.h.
            : DinfoBase( isOneZombie ),
                sizeIncrement_( isOneZombie ? 0 : sizeof( D ) )
        {;}
References Dinfo< D >::sizeIncrement_.
Member Function Documentation
allocData()
template<class D > char * Dinfo< D >::allocData (unsigned int numData) const inline virtual
Implements DinfoBase.
Definition at line 71 of file Dinfo.h.
{
            if ( numData == 0 )
                return 0;
            else
                return reinterpret_cast< char* >( new( nothrow) D[ numData ] );
        }
assignData()
template<class D > void Dinfo< D >::assignData (char * copy, unsigned int copyEntries, const char * orig, unsigned int origEntries) const inline virtual
Assigns data contents from 'orig' over to 'copy'. Tiles the origEntries onto the copyEntries. So if there are fewer origEntries, the orig data contents are repeated till the copy is full.
Implements DinfoBase.
Definition at line 106 of file Dinfo.h.
        {
            if ( origEntries == 0 || copyEntries == 0 ||
                orig == 0 || data == 0 ) {
                return;
            }
            if ( isOneZombie() )
                copyEntries = 1;
            const D* origData = reinterpret_cast< const D* >( orig );
            D* tgt = reinterpret_cast< D* >( data );
            for ( unsigned int i = 0; i < copyEntries; ++i ) {
                tgt[ i ] = origData[ i % origEntries ];
            }
            /*
            for ( unsigned int i = 0; i < copyEntries; i+= origEntries ) {
                unsigned int numCopies = origEntries;
                if ( copyEntries - i < origEntries )
                    numCopies = copyEntries - i;
                for ( unsigned int j = 0; j < numCopies; ++j ) {
                    tgt[i +j] = origData[j];
                }
                // memcpy( data + i * sizeof( D ), orig, sizeof( D ) * numCopies );
                // Memcpy is fast but it does not permit for C++ to do
                // various constructor and assignment operations that are
                // important if D has pointers in it.
            }
            */
        }
References DinfoBase::isOneZombie().
copyData()
template<class D > char * Dinfo< D >::copyData (const char * orig, unsigned int origEntries, unsigned int copyEntries, unsigned int startEntry) const inline virtual
Return a newly allocated copy of the original data, repeated copyEntries times. Orig data untouched. Analogous to copying a vector into a bigger one. Repeat the original data as many times as possible.
Implements DinfoBase.
Definition at line 78 of file Dinfo.h.
        {
            if ( origEntries == 0 )
                return 0;
            if ( isOneZombie() )
                copyEntries = 1;
            D* ret = new( nothrow ) D[copyEntries];
            if ( !ret )
                return 0;
            const D* origData = reinterpret_cast< const D* >( orig );
            for ( unsigned int i = 0; i < copyEntries; ++i ) {
                ret[ i ] = origData[ ( i + startEntry ) % origEntries ];
            }
            /*
            D* ret = new D[ numData * numCopies ];
            const D* origData = reinterpret_cast< const D* >( orig );
            for ( unsigned int i = 0; i < numData; ++i ) {
                for ( unsigned int j = 0; j < numCopies; ++j ) {
                    ret[ i * numCopies + j ] = origData[ i ];
                }
            }
            */
            return reinterpret_cast< char* >( ret );
        }
References DinfoBase::isOneZombie().
destroyData()
template<class D > void Dinfo< D >::destroyData (char * d) const inline virtual
Implements DinfoBase.
Definition at line 137 of file Dinfo.h.
{
            delete[] reinterpret_cast< D* >( d );
        }
isA()
template<class D > bool Dinfo< D >::isA (const DinfoBase * other) const inline virtual
Implements DinfoBase.
Definition at line 170 of file Dinfo.h.
{
            return dynamic_cast< const Dinfo< D >* >( other );
        }
size()
template<class D > unsigned int Dinfo< D >::size () const inline virtual
Implements DinfoBase.
Reimplemented in ZeroSizeDinfo< D >.
Definition at line 141 of file Dinfo.h.
{
            return sizeof( D );
        }
sizeIncrement()
template<class D > unsigned int Dinfo< D >::sizeIncrement () const inline virtual
This little hack is used for lookups of a data entry in an array. Normally sizeIncrement is identical to size. However, if it is a OneZombie then we always need to return the original pointer, so here sizeIncrement becomes zero.
Implements DinfoBase.
Reimplemented in ZeroSizeDinfo< D >.
Definition at line 151 of file Dinfo.h.
{
            return sizeIncrement_;
        }
References Dinfo< D >::sizeIncrement_.
Member Data Documentation
sizeIncrement_
template<class D > unsigned int Dinfo< D >::sizeIncrement_ private
Definition at line 174 of file Dinfo.h.
Referenced by Dinfo< D >::Dinfo(), Dinfo< D >::Dinfo(), and Dinfo< D >::sizeIncrement().
The documentation for this class was generated from the following file:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/basecode/Dinfo.h