MOOSE - Multiscale Object Oriented Simulation Environment: MMPump Class Reference
MMPump Class Reference
#include <MMPump.h>
Public Member Functions
double getKd (const Eref &e) const
int getVal (const Eref &e) const
double getVmax (const Eref &e) const
MMPump ()
void process (const Eref &e, ProcPtr p)
void reinit (const Eref &e, ProcPtr p)
void setKd (const Eref &e, double value)
void setVal (const Eref &e, int value)
void setVmax (const Eref &e, double value)
Static Public Member Functions
static const Cinfo * initCinfo ()
static SrcFinfo2< double, double > * PumpOut ()
Private Attributes
double Kd_
double Vmax_
Detailed Description
Definition at line 14 of file MMPump.h.
Constructor & Destructor Documentation
MMPump()
MMPump::MMPump ()
Definition at line 98 of file MMPump.cpp.
{ ; }
Member Function Documentation
getKd()
double MMPump::getKd (const Eref & e) const
Definition at line 119 of file MMPump.cpp.
{
  return Kd_;
}
References Kd_.
Referenced by initCinfo().
getVal()
int MMPump::getVal (const Eref & e) const
getVmax()
double MMPump::getVmax (const Eref & e) const
Definition at line 104 of file MMPump.cpp.
{
  return Vmax_;
}
References Vmax_.
Referenced by initCinfo().
initCinfo()
const Cinfo * MMPump::initCinfo () static
Definition at line 14 of file MMPump.cpp.
{
  static DestFinfo process( "process",
                "Handles process call",
                new ProcOpFunc< MMPump>(&MMPump::process ) );
  static DestFinfo reinit( "reinit",
               "Reinit happens only in stage 0",
               new ProcOpFunc< MMPump>( &MMPump::reinit ));
  static Finfo* processShared[] = {
    &process, &reinit
  };
  static SharedFinfo proc(
              "proc",
              "Shared message to receive Process message from scheduler",
              processShared, sizeof( processShared ) / sizeof( Finfo* ));
  // Field defs
  static ElementValueFinfo<MMPump, double> Vmax("Vmax",
                          "maximum pump velocity, scaled by mebrane"
                            "surface area. i.e., max ion flux in moles/sec",
                          &MMPump::setVmax,
                          &MMPump::getVmax);
  static ElementValueFinfo<MMPump, double> Kd("Kd",
                         "half-maximal activating concentration in mM",
                         &MMPump::setKd,
                         &MMPump::getKd);
  // DestFinfo
  static Finfo * difMMPumpFinfos[] = {
    // Field definitions
    &Vmax,
    &Kd,
    // SharedFinfo definitions
    &proc,
    PumpOut(),
    // DestFinfo definitions
  };
  static string doc[] = {
    "Name", "MMPump",
    "Author", "Subhasis Ray (ported from GENESIS2)",
    "Description", "Models Michaelis-Menten pump. It is coupled with a DifShell.",
  };
  static ZeroSizeDinfo<int> dinfo;
  static Cinfo MMPumpCinfo(
                  "MMPump",
                  Neutral::initCinfo(),
                  difMMPumpFinfos,
                  sizeof(difMMPumpFinfos)/sizeof(Finfo*),
                  &dinfo,
                  doc,
                  sizeof(doc)/sizeof(string));
  return &MMPumpCinfo;
}
References Cinfo::Cinfo(), DestFinfo::DestFinfo(), ElementValueFinfo< T, F >::ElementValueFinfo(), getKd(), getVmax(), Neutral::initCinfo(), process(), ProcOpFunc< T >::ProcOpFunc(), PumpOut(), reinit(), setKd(), setVmax(), and SharedFinfo::SharedFinfo().
process()
void MMPump::process (const Eref & e, ProcPtr p)
Definition at line 133 of file MMPump.cpp.
{
  PumpOut()->send(e,Vmax_,Kd_);
}
References Kd_, PumpOut(), SrcFinfo2< T1, T2 >::send(), and Vmax_.
Referenced by initCinfo().
PumpOut()
SrcFinfo2< double, double > * MMPump::PumpOut () static
Definition at line 7 of file MMPump.cpp.
{
  static SrcFinfo2< double,double > pumpOut( "PumpOut",
                    "Sends out MMPump parameters.");
  return &pumpOut;
}
References SrcFinfo2< T1, T2 >::SrcFinfo2().
Referenced by initCinfo(), and process().
reinit()
void MMPump::reinit (const Eref & e, ProcPtr p)
Definition at line 138 of file MMPump.cpp.
{
  return;
}
Referenced by initCinfo().
setKd()
void MMPump::setKd (const Eref & e, double value)
Definition at line 123 of file MMPump.cpp.
{
if (value  < 0.0) {
    cerr << "Error: MMPump: Kd cannot be negative!\n";
    return;
  }
  Kd_ = value;
}
References Kd_.
Referenced by initCinfo().
setVal()
void MMPump::setVal (const Eref & e, int value)
setVmax()
void MMPump::setVmax (const Eref & e, double value)
Definition at line 109 of file MMPump.cpp.
{
if (value  < 0.0) {
    cerr << "Error: MMPump: Vmax cannot be negative!\n";
    return;
  }
  Vmax_ = value;
}
References Vmax_.
Referenced by initCinfo().
Member Data Documentation
Kd_
double MMPump::Kd_ private
Definition at line 39 of file MMPump.h.
Referenced by getKd(), process(), and setKd().
Vmax_
double MMPump::Vmax_ private
Definition at line 38 of file MMPump.h.
Referenced by getVmax(), process(), and setVmax().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/biophysics/MMPump.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/biophysics/MMPump.cpp