MOOSE - Multiscale Object Oriented Simulation Environment: HHChannelF2D Class Reference
HHChannelF2D Class Reference
#include <HHChannelF2D.h>
Public Member Functions
bool checkOriginal (Id chanId) const override
Returns true if channel is original, false if copy.
void conc1 (double conc)
void conc2 (double conc)
void destroyGate (const Eref &e, string gateType) override
unsigned int getNumXgates () const
unsigned int getNumYgates () const
Returns 1 if Y gate present, otherwise 0.
unsigned int getNumZgates () const
Returns 1 if Z gate present, otherwise 0.
HHGateF2D * getXgate (unsigned int i)
Access function used for the X gate. The index is ignored.
string getXindex () const
HHGateF2D * getYgate (unsigned int i)
Access function used for the Y gate. The index is ignored.
string getYindex () const
HHGateF2D * getZgate (unsigned int i)
Access function used for the Z gate. The index is ignored.
string getZindex () const
HHChannelF2D ()
void innerCreateGate (const string &gateName, HHGateF2D **gatePtr, Id chanId, Id gateId)
Inner utility function for creating the gate.
void innerDestroyGate (const string &gateName, HHGateF2D **gatePtr, Id chanId)
void setNumGates (unsigned int num)
Dummy assignment function for the number of gates.
void setXindex (string index)
void setYindex (string index)
void setZindex (string index)
void vCreateGate (const Eref &e, string gateType) override
void vProcess (const Eref &e, ProcPtr p) override
void vReinit (const Eref &e, ProcPtr p) override
Public Member Functions inherited from HHChannelBase
void createGate (const Eref &e, string gateType)
int getInstant (const Eref &e) const
int getUseConcentration (const Eref &e) const
double getX (const Eref &e) const
HHGate * getXgate (unsigned int i)
double getXpower (const Eref &e) const
double getY (const Eref &e) const
HHGate * getYgate (unsigned int i)
double getYpower (const Eref &e) const
double getZ (const Eref &e) const
HHGate * getZgate (unsigned int i)
double getZpower (const Eref &e) const
void handleConc (const Eref &e, double conc)
HHChannelBase ()
bool setGatePower (const Eref &e, double power, double *assignee, const string &gateType)
void setInstant (const Eref &e, int Instant)
void setNumGates (unsigned int num)
void setUseConcentration (const Eref &e, int value)
void setX (const Eref &e, double X)
void setXpower (const Eref &e, double Xpower)
void setY (const Eref &e, double Y)
void setYpower (const Eref &e, double Ypower)
void setZ (const Eref &e, double Z)
void setZpower (const Eref &e, double Zpower)
virtual int vGetInstant (const Eref &e) const
virtual double vGetX (const Eref &e) const
virtual double vGetY (const Eref &e) const
virtual double vGetZ (const Eref &e) const
virtual void vHandleConc (const Eref &e, double conc)
virtual void vSetInstant (const Eref &e, int Instant)
virtual void vSetSolver (const Eref &e, Id hsolve)
virtual void vSetUseConcentration (const Eref &e, int value)
virtual void vSetX (const Eref &e, double X)
virtual void vSetXpower (const Eref &e, double Xpower)
virtual void vSetY (const Eref &e, double Y)
virtual void vSetYpower (const Eref &e, double Ypower)
virtual void vSetZ (const Eref &e, double Z)
virtual void vSetZpower (const Eref &e, double Zpower)
virtual ~HHChannelBase ()=0
Public Member Functions inherited from ChanCommon
ChanCommon ()
double getGbar () const
Utility function to acces Gbar.
double getVm () const
Utility function to access Vm.
void sendProcessMsgs (const Eref &e, const ProcPtr info)
void sendReinitMsgs (const Eref &e, const ProcPtr info)
void updateIk ()
double vGetEk (const Eref &e) const override
double vGetGbar (const Eref &e) const override
double vGetGk (const Eref &e) const override
double vGetIk (const Eref &e) const override
double vGetModulation (const Eref &e) const override
void vHandleVm (double Vm) override
void vSetEk (const Eref &e, double Ek) override
void vSetGbar (const Eref &e, double Gbar) override
void vSetGk (const Eref &e, double Gk) override
void vSetIk (const Eref &e, double Ic) override
void vSetModulation (const Eref &e, double modulation) override
virtual ~ChanCommon ()=0
Public Member Functions inherited from ChanBase
ChanBase ()
double getEk (const Eref &e) const
double getGbar (const Eref &e) const
double getGk (const Eref &e) const
double getIk (const Eref &e) const
double getModulation (const Eref &e) const
void handleVm (double Vm)
void process (const Eref &e, const ProcPtr info)
void reinit (const Eref &e, const ProcPtr info)
void setEk (const Eref &e, double Ek)
void setGbar (const Eref &e, double Gbar)
void setGk (const Eref &e, double Gk)
void setIk (const Eref &e, double Ic)
void setModulation (const Eref &e, double modulation)
virtual ~ChanBase ()=0
Static Public Member Functions
static const Cinfo * initCinfo ()
Static Public Member Functions inherited from HHChannelBase
static const Cinfo * initCinfo ()
static double power1 (double x, double p)
static double power2 (double x, double p)
static double power3 (double x, double p)
static double power4 (double x, double p)
static double powerN (double x, double p)
static PFDD selectPower (double power)
static void zombify (Element *orig, const Cinfo *zClass, Id hsolve)
Static Public Member Functions inherited from ChanCommon
static const Cinfo * initCinfo ()
Specify the Class Info static variable for initialization.
Static Public Member Functions inherited from ChanBase
static SrcFinfo2< double, double > * channelOut ()
static SrcFinfo1< double > * IkOut ()
static const Cinfo * initCinfo ()
Specify the Class Info static variable for initialization.
static SrcFinfo1< double > * permeability ()
Private Member Functions
int dependency (string index, unsigned int dim)
double depValue (int dependency)
Private Attributes
double conc1_
double conc2_
int Xdep0_
int Xdep1_
HHGateF2D * xGate_
string Xindex_
int Ydep0_
int Ydep1_
HHGateF2D * yGate_
string Yindex_
int Zdep0_
int Zdep1_
HHGateF2D * zGate_
HHGateF2D for the yGate.
string Zindex_
Additional Inherited Members
Protected Member Functions inherited from HHChannelBase
double integrate (double state, double dt, double A, double B)
Protected Member Functions inherited from ChanCommon
double getModulation () const
Protected Attributes inherited from HHChannelBase
double g_
int instant_
Id myId_
double(* takeXpower_)(double, double)
double(* takeYpower_)(double, double)
double(* takeZpower_)(double, double)
bool useConcentration_
Flag for use of conc for input to Z gate calculations.
double X_
bool xInited_
Flag to indicate if gates have been created.
double Xpower_
Exponent for X gate.
double Y_
bool yInited_
double Ypower_
Exponent for Y gate.
double Z_
bool zInited_
double Zpower_
Exponent for Z gate.
Protected Attributes inherited from ChanCommon
double Vm_
Vm_ is input variable from compartment, used for most rates.
Static Protected Attributes inherited from HHChannelBase
static const double EPSILON = 1.0e-10
static const int INSTANT_X = 1
static const int INSTANT_Y = 2
static const int INSTANT_Z = 4
Detailed Description
Definition at line 30 of file HHChannelF2D.h.
Constructor & Destructor Documentation
HHChannelF2D()
HHChannelF2D::HHChannelF2D ()
Definition at line 173 of file HHChannelF2D.cpp.
    : HHChannelBase(),
      conc1_(0.0),
      conc2_(0.0),
      Xdep0_(-1),
      Xdep1_(-1),
      Ydep0_(-1),
      Ydep1_(-1),
      Zdep0_(-1),
      Zdep1_(-1),
      xGate_(0),
      yGate_(0),
      zGate_(0)
{
    ;
}
References conc1_, conc2_, HHChannelBase::HHChannelBase(), Xdep0_, Xdep1_, xGate_, Ydep0_, Ydep1_, yGate_, Zdep0_, Zdep1_, and zGate_.
Member Function Documentation
checkOriginal()
bool HHChannelF2D::checkOriginal (Id chanId) const override virtual
Returns true if channel is original, false if copy.
If the gate exists and has only this element for input, then change the gate power. If the gate exists and has multiple parents, then make a new gate, set its power. If the gate does not exist, make a new gate, set its power.
The function is designed with the idea that if copies of this channel are made, then they all point back to the original HHGate. (Unless they are cross-node copies). It is only if we subsequently alter the HHGate of this channel that we need to make our own variant of the HHGate, or disconnect from an existing one.
Reimplemented from HHChannelBase.
Definition at line 474 of file HHChannelF2D.cpp.
{
    bool isOriginal = 1;
    if(xGate_) {
        isOriginal = xGate_->isOriginalChannel(chanId);
    }
    else if(yGate_) {
        isOriginal = yGate_->isOriginalChannel(chanId);
    }
    else if(zGate_) {
        isOriginal = zGate_->isOriginalChannel(chanId);
    }
    return isOriginal;
}
References HHGateBase::isOriginalChannel(), xGate_, yGate_, and zGate_.
Referenced by destroyGate(), and vCreateGate().
conc1()
void HHChannelF2D::conc1 (double conc)
Assign the local conc_ to the incoming conc from the concentration calculations for the compartment. Typically the message source will be a CaConc object, but there are other options for computing the conc.
Definition at line 336 of file HHChannelF2D.cpp.
{
    conc1_ = conc;
}
References conc1_.
conc2()
void HHChannelF2D::conc2 (double conc)
Definition at line 341 of file HHChannelF2D.cpp.
{
    conc2_ = conc;
}
References conc2_.
dependency()
int HHChannelF2D::dependency (string index, unsigned int dim) private
Definition at line 296 of file HHChannelF2D.cpp.
{
    static vector<map<string, int>> dep;
    if(dep.empty()) {
        dep.resize(2);
        dep[0]["VOLT_INDEX"] = 0;
        dep[0]["C1_INDEX"] = 1;
        dep[0]["C2_INDEX"] = 2;
        dep[0]["VOLT_C1_INDEX"] = 0;
        dep[0]["VOLT_C2_INDEX"] = 0;
        dep[0]["C1_C2_INDEX"] = 1;
        dep[1]["VOLT_INDEX"] = -1;
        dep[1]["C1_INDEX"] = -1;
        dep[1]["C2_INDEX"] = -1;
        dep[1]["VOLT_C1_INDEX"] = 1;
        dep[1]["VOLT_C2_INDEX"] = 2;
        dep[1]["C1_C2_INDEX"] = 2;
    }
    if(dep[dim].find(index) == dep[dim].end())
        return -1;
    if(dep[dim][index] == 0)
        return 0;
    if(dep[dim][index] == 1)
        return 1;
    if(dep[dim][index] == 2)
        return 2;
    return -1;
}
Referenced by setXindex(), setYindex(), and setZindex().
depValue()
double HHChannelF2D::depValue (int dependency) private
Definition at line 281 of file HHChannelF2D.cpp.
{
    switch(dep) {
        case 0:
            return Vm_;
        case 1:
            return conc1_;
        case 2:
            return conc2_;
        default:
            assert(0);
            return 0.0;
    }
}
References conc1_, conc2_, and ChanCommon::Vm_.
Referenced by vProcess(), and vReinit().
destroyGate()
void HHChannelF2D::destroyGate (const Eref & e, string gateType) override virtual
Utility function for destroying gate. Works only on original HHChannel. Somewhat dangerous, should never be used after a copy has been made as the pointer of the gate will be in use elsewhere.
Reimplemented from HHChannelBase.
Definition at line 533 of file HHChannelF2D.cpp.
{
    if(!checkOriginal(e.id())) {
        cout << "Warning: HHChannelF2D::destroyGate: Not allowed from copied "
                "channel:\n"
             << e.id().path() << "\n";
        return;
    }
    if(gateType == "X")
        innerDestroyGate("xGate", &xGate_, e.id());
    else if(gateType == "Y")
        innerDestroyGate("yGate", &yGate_, e.id());
    else if(gateType == "Z")
        innerDestroyGate("zGate", &zGate_, e.id());
    else
        cout << "Warning: HHChannelF2D::destroyGate: Unknown gate type '"
             << gateType << "'. Ignored\n";
}
References checkOriginal(), Eref::id(), innerDestroyGate(), Id::path(), xGate_, yGate_, and zGate_.
getNumXgates()
unsigned int HHChannelF2D::getNumXgates () const
Access function for the number of Xgates. Gives 1 if present, otherwise 0.
Definition at line 268 of file HHChannelF2D.cpp.
{
    return xGate_ != nullptr;
}
References xGate_.
getNumYgates()
unsigned int HHChannelF2D::getNumYgates () const
Returns 1 if Y gate present, otherwise 0.
Definition at line 272 of file HHChannelF2D.cpp.
{
    return yGate_ != nullptr;
}
References yGate_.
getNumZgates()
unsigned int HHChannelF2D::getNumZgates () const
Returns 1 if Z gate present, otherwise 0.
Definition at line 276 of file HHChannelF2D.cpp.
{
    return zGate_ != nullptr;
}
References zGate_.
getXgate()
HHGateF2D * HHChannelF2D::getXgate (unsigned int i)
Access function used for the X gate. The index is ignored.
Definition at line 249 of file HHChannelF2D.cpp.
{
    return xGate_;
}
References xGate_.
getXindex()
string HHChannelF2D::getXindex () const
Definition at line 194 of file HHChannelF2D.cpp.
{
    return Xindex_;
}
References Xindex_.
getYgate()
HHGateF2D * HHChannelF2D::getYgate (unsigned int i)
Access function used for the Y gate. The index is ignored.
Definition at line 254 of file HHChannelF2D.cpp.
{
    return yGate_;
}
References yGate_.
getYindex()
string HHChannelF2D::getYindex () const
Definition at line 211 of file HHChannelF2D.cpp.
{
    return Yindex_;
}
References Yindex_.
getZgate()
HHGateF2D * HHChannelF2D::getZgate (unsigned int i)
Access function used for the Z gate. The index is ignored.
Definition at line 259 of file HHChannelF2D.cpp.
{
    return zGate_;
}
References zGate_.
getZindex()
string HHChannelF2D::getZindex () const
Definition at line 228 of file HHChannelF2D.cpp.
{
    return Zindex_;
}
References Zindex_.
initCinfo()
const Cinfo * HHChannelF2D::initCinfo () static
Definition at line 20 of file HHChannelF2D.cpp.
{
    // Shared messages
    // Field definitions
    static ValueFinfo<HHChannelF2D, string> Xindex(
        "Xindex",
        "String specifying input variable assignment for X gate. This tells the"
        " channel which input (dest field) to use for which parameter in the"
        " gate equations."
        " It can take the following string values:\n"
        " \"VOLT_INDEX\": use only voltage input received via dest field 'Vm'"
        " (assigned to the `v` variable in the equations).\n"
        " \"C1_INDEX\": use only concentration input received via  dest field"
        " 'concen' (assigned to `c` variable in the equations).\n"
        " \"C2_INDEX\": use only concentration input received via dest field"
        " 'concen2'  (assigned to `c` variable in the equations)\n"
        " \"VOLT_C1_INDEX\": assign voltage input 'Vm' to `v` and concentration"
        " input 'concen' to `c`\n"
        " \"VOLT_C2_INDEX\": assign voltage input 'Vm' to `v` and concentration"
        " input 'concen2' to `c`\n"
        " \"C1_C2_INDEX\": assign concentration input 'concen' to `v` and "
        "concentration"
        " input 'concen2' to `c`"
        ,
        &HHChannelF2D::setXindex, &HHChannelF2D::getXindex);
    static ValueFinfo<HHChannelF2D, string> Yindex(
        "Yindex",
        "String specifying input variable assignment for Y gate. This tells the"
        " channel which input (dest field) to use for which parameter in the"
        " gate equations."
        " It can take the following string values:\n"
        " \"VOLT_INDEX\": use only voltage input received via dest field 'Vm'"
        " (assigned to the `v` variable in the equations).\n"
        " \"C1_INDEX\": use only concentration input received via  dest field"
        " 'concen' (assigned to `c` variable in the equations).\n"
        " \"C2_INDEX\": use only concentration input received via dest field"
        " 'concen2'  (assigned to `c` variable in the equations)\n"
        " \"VOLT_C1_INDEX\": assign voltage input 'Vm' to `v` and concentration"
        " input 'concen' to `c`\n"
        " \"VOLT_C2_INDEX\": assign voltage input 'Vm' to `v` and concentration"
        " input 'concen2' to `c`\n"
        " \"C1_C2_INDEX\": assign concentration input 'concen' to `v` and "
        "concentration"
        " input 'concen2' to `c`"
        ,
        &HHChannelF2D::setYindex, &HHChannelF2D::getYindex);
    static ValueFinfo<HHChannelF2D, string> Zindex(
        "Zindex",
        "String specifying input variable assignment for Y gate. This tells the"
        " channel which input (dest field) to use for which parameter in the"
        " gate equations."
        " It can take the following string values:\n"
        " \"VOLT_INDEX\": use only voltage input received via dest field 'Vm'"
        " (assigned to the `v` variable in the equations).\n"
        " \"C1_INDEX\": use only concentration input received via  dest field"
        " 'concen' (assigned to `c` variable in the equations).\n"
        " \"C2_INDEX\": use only concentration input received via dest field"
        " 'concen2'  (assigned to `c` variable in the equations)\n"
        " \"VOLT_C1_INDEX\": assign voltage input 'Vm' to `v` and concentration"
        " input 'concen' to `c`\n"
        " \"VOLT_C2_INDEX\": assign voltage input 'Vm' to `v` and concentration"
        " input 'concen2' to `c`\n"
        " \"C1_C2_INDEX\": assign concentration input 'concen' to `v` and "
        "concentration"
        " input 'concen2' to `c`",
        &HHChannelF2D::setZindex, &HHChannelF2D::getZindex);
    static ElementValueFinfo<HHChannelF2D, double> Xpower(
        "Xpower", "Power for X gate", &HHChannelF2D::setXpower,
        &HHChannelF2D::getXpower);
    static ElementValueFinfo<HHChannelF2D, double> Ypower(
        "Ypower", "Power for Y gate", &HHChannelF2D::setYpower,
        &HHChannelF2D::getYpower);
    static ElementValueFinfo<HHChannelF2D, double> Zpower(
        "Zpower", "Power for Z gate", &HHChannelF2D::setZpower,
        &HHChannelF2D::getZpower);
    // MsgSrc definitions
    // MsgDest definitions
    static DestFinfo concen(
        "concen",
        "Incoming message from Concen object to specific conc to use"
        "as the first concen variable",
        new OpFunc1<HHChannelF2D, double>(&HHChannelF2D::conc1));
    static DestFinfo concen2(
        "concen2",
        "Incoming message from Concen object to specific conc to use"
        "as the second concen variable",
        new OpFunc1<HHChannelF2D, double>(&HHChannelF2D::conc2));
    // FieldElementFinfo definition for HHGates. Note that these are made
    // with the deferCreate flag off, so that the HHGates are created
    // right away even if they are empty.
    // I assume that we only have a single HHGate entry for each one.
    static FieldElementFinfo<HHChannelF2D, HHGateF2D> gateX(
        "gateX", "Sets up HHGate X for channel", HHGateF2D::initCinfo(),
        &HHChannelF2D::getXgate, &HHChannelF2D::setNumGates,
        &HHChannelF2D::getNumXgates);
    static FieldElementFinfo<HHChannelF2D, HHGateF2D> gateY(
        "gateY", "Sets up HHGate Y for channel", HHGateF2D::initCinfo(),
        &HHChannelF2D::getYgate, &HHChannelF2D::setNumGates,
        &HHChannelF2D::getNumYgates);
    static FieldElementFinfo<HHChannelF2D, HHGateF2D> gateZ(
        "gateZ", "Sets up HHGate Z for channel", HHGateF2D::initCinfo(),
        &HHChannelF2D::getZgate, &HHChannelF2D::setNumGates,
        &HHChannelF2D::getNumZgates);
    static Finfo *HHChannelF2DFinfos[] = {
        &Xindex,   // Value
        &Yindex,   // Value
        &Zindex,   // Value
        &Xpower,   // Value
        &Ypower,   // Value
        &Zpower,   // Value
        &concen,   // Dest
        &concen2,  // Dest
        &gateX,    // FieldElement
        &gateY,    // FieldElement
        &gateZ     // FieldElement
    };
    static string doc[] = {
        "Name",
        "HHChannelF2D",
        "Author",
        "Niraj Dudani, 2009, NCBS, Updated Upi Bhalla, 2011",
        "Description",
        "HHChannelF2D: Hodgkin-Huxley type voltage-gated Ion channel. "
        "Something "
        "like the old tabchannel from GENESIS, but also presents "
        "a similar interface as hhchan from GENESIS. ",
    };
    static Dinfo<HHChannelF2D> dinfo;
    static Cinfo HHChannelF2DCinfo("HHChannelF2D", ChanBase::initCinfo(),
                                   HHChannelF2DFinfos,
                                   sizeof(HHChannelF2DFinfos) / sizeof(Finfo *),
                                   &dinfo, doc, sizeof(doc) / sizeof(string));
    return &HHChannelF2DCinfo;
}
References ChanBase::initCinfo().
innerCreateGate()
void HHChannelF2D::innerCreateGate (const string & gateName, HHGateF2D ** gatePtr, Id chanId, Id gateId)
Inner utility function for creating the gate.
Definition at line 489 of file HHChannelF2D.cpp.
{
    // Shell* shell = reinterpret_cast< Shell* >( ObjId( Id(), 0 ).data() );
    if(*gatePtr) {
        cout << "Warning: HHChannelF2D::createGate: '" << gateName
             << "' on Element '" << chanId.path() << "' already present\n";
        return;
    }
    *gatePtr = new HHGateF2D(chanId, gateId);
}
References HHGateF2D::HHGateF2D(), and Id::path().
Referenced by vCreateGate().
innerDestroyGate()
void HHChannelF2D::innerDestroyGate (const string & gateName, HHGateF2D ** gatePtr, Id chanId)
Inner utility for destroying the gate
Definition at line 521 of file HHChannelF2D.cpp.
{
    if(*gatePtr == nullptr) {
        cout << "Warning: HHChannelF2D::destroyGate: '" << gateName
             << "' on Element '" << chanId.path() << "' not present\n";
        return;
    }
    delete(*gatePtr);
    *gatePtr = nullptr;
}
References Id::path().
Referenced by destroyGate().
setNumGates()
void HHChannelF2D::setNumGates (unsigned int num)
Dummy assignment function for the number of gates.
Definition at line 264 of file HHChannelF2D.cpp.
{
    ;
}
setXindex()
void HHChannelF2D::setXindex (string index)
Definition at line 199 of file HHChannelF2D.cpp.
{
    if(Xindex == Xindex_)
        return;
    Xindex_ = Xindex;
    Xdep0_ = dependency(Xindex, 0);
    Xdep1_ = dependency(Xindex, 1);
    assert(Xdep0_ >= 0);
}
References dependency(), Xdep0_, Xdep1_, and Xindex_.
setYindex()
void HHChannelF2D::setYindex (string index)
Definition at line 216 of file HHChannelF2D.cpp.
{
    if(Yindex == Yindex_)
        return;
    Yindex_ = Yindex;
    Ydep0_ = dependency(Yindex, 0);
    Ydep1_ = dependency(Yindex, 1);
    assert(Ydep0_ >= 0);
}
References dependency(), Ydep0_, Ydep1_, and Yindex_.
setZindex()
void HHChannelF2D::setZindex (string index)
Definition at line 233 of file HHChannelF2D.cpp.
{
    if(Zindex == Zindex_)
        return;
    Zindex_ = Zindex;
    Zdep0_ = dependency(Zindex, 0);
    Zdep1_ = dependency(Zindex, 1);
    assert(Zdep0_ >= 0);
}
References dependency(), Zdep0_, Zdep1_, and Zindex_.
vCreateGate()
void HHChannelF2D::vCreateGate (const Eref & e, string gateType) override virtual
Function for safely creating each gate, identified by strings as X, Y and Z. Will only work on a new channel, not on a copy. The idea is that the gates are always referred to the original 'library' channel, and their contents cannot be touched except by the original.
Implements HHChannelBase.
Definition at line 501 of file HHChannelF2D.cpp.
{
    if(!checkOriginal(e.id())) {
        cout << "Warning: HHChannelF2D::createGate: Not allowed from copied "
                "channel:\n"
             << e.id().path() << "\n";
        return;
    }
    if(gateType == "X")
        innerCreateGate("xGate", &xGate_, e.id(), Id(e.id().value() + 1));
    else if(gateType == "Y")
        innerCreateGate("yGate", &yGate_, e.id(), Id(e.id().value() + 2));
    else if(gateType == "Z")
        innerCreateGate("zGate", &zGate_, e.id(), Id(e.id().value() + 3));
    else
        cout << "Warning: HHChannelF2D::createGate: Unknown gate type '"
             << gateType << "'. Ignored\n";
}
References checkOriginal(), Eref::id(), Id::Id(), innerCreateGate(), Id::path(), Id::value(), xGate_, yGate_, and zGate_.
vProcess()
void HHChannelF2D::vProcess (const Eref & e, ProcPtr p) override virtual
processFunc handles the update and calculations every clock tick. It first sends the request for evaluation of the gate variables to the respective gate objects and recieves their response immediately through a return message. This is done so that many channel instances can share the same gate lookup tables, but do so cleanly. Such messages should never go to a remote node. Then the function does its own little calculations to send back to the parent compartment through regular messages.
Implements ChanBase.
Definition at line 350 of file HHChannelF2D.cpp.
{
    g_ += ChanBase::getGbar(e);
    double A = 0;
    double B = 0;
    if(Xpower_ > 0) {
        xGate_->lookupBoth(depValue(Xdep0_), depValue(Xdep1_), &A, &B);
        if(instant_ & INSTANT_X)
            X_ = A / B;
        else
            X_ = integrate(X_, info->dt, A, B);
        g_ *= takeXpower_(X_, Xpower_);
    }
    if(Ypower_ > 0) {
        yGate_->lookupBoth(depValue(Ydep0_), depValue(Ydep1_), &A, &B);
        if(instant_ & INSTANT_Y)
            Y_ = A / B;
        else
            Y_ = integrate(Y_, info->dt, A, B);
        g_ *= takeYpower_(Y_, Ypower_);
    }
    if(Zpower_ > 0) {
        zGate_->lookupBoth(depValue(Zdep0_), depValue(Zdep1_), &A, &B);
        if(instant_ & INSTANT_Z)
            Z_ = A / B;
        else
            Z_ = integrate(Z_, info->dt, A, B);
        g_ *= takeZpower_(Z_, Zpower_);
    }
    ChanBase::setGk(e, g_ * vGetModulation(e));
    updateIk();
    // Gk_ = g_;
    // Ik_ = ( Ek_ - Vm_ ) * g_;
    // Send out the relevant channel messages.
    sendProcessMsgs(e, info);
    g_ = 0.0;
}
References depValue(), ProcInfo::dt, HHChannelBase::g_, ChanBase::getGbar(), HHChannelBase::instant_, HHChannelBase::INSTANT_X, HHChannelBase::INSTANT_Y, HHChannelBase::INSTANT_Z, HHChannelBase::integrate(), HHGateF2D::lookupBoth(), ChanCommon::sendProcessMsgs(), ChanBase::setGk(), HHChannelBase::takeXpower_, HHChannelBase::takeYpower_, HHChannelBase::takeZpower_, ChanCommon::updateIk(), ChanCommon::vGetModulation(), HHChannelBase::X_, Xdep0_, Xdep1_, xGate_, HHChannelBase::Xpower_, HHChannelBase::Y_, Ydep0_, Ydep1_, yGate_, HHChannelBase::Ypower_, HHChannelBase::Z_, Zdep0_, Zdep1_, zGate_, and HHChannelBase::Zpower_.
vReinit()
void HHChannelF2D::vReinit (const Eref & er, ProcPtr info) override virtual
Reinitializes the values for the channel. This involves computing the steady-state value for the channel gates using the provided Vm from the parent compartment. It involves a similar cycle through the gates and then updates to the parent compartment as for the processFunc.
Here we get the steady-state values for the gate (the 'instant' calculation) as A_/B_.
Implements ChanBase.
Definition at line 398 of file HHChannelF2D.cpp.
{
    g_ = ChanBase::getGbar(er);
    Element *e = er.element();
    double A = 0.0;
    double B = 0.0;
    if(Xpower_ > 0) {
        xGate_->lookupBoth(depValue(Xdep0_), depValue(Xdep1_), &A, &B);
        if(B < EPSILON) {
            cout << "Warning: B_ value for " << e->getName()
                 << " is ~0. Check X table\n";
            return;
        }
        if(!xInited_)
            X_ = A / B;
        g_ *= takeXpower_(X_, Xpower_);
    }
    if(Ypower_ > 0) {
        yGate_->lookupBoth(depValue(Ydep0_), depValue(Ydep1_), &A, &B);
        if(B < EPSILON) {
            cout << "Warning: B value for " << e->getName()
                 << " is ~0. Check Y table\n";
            return;
        }
        if(!yInited_)
            Y_ = A / B;
        g_ *= takeYpower_(Y_, Ypower_);
    }
    if(Zpower_ > 0) {
        zGate_->lookupBoth(depValue(Zdep0_), depValue(Zdep1_), &A, &B);
        if(B < EPSILON) {
            cout << "Warning: B value for " << e->getName()
                 << " is ~0. Check Z table\n";
            return;
        }
        if(!zInited_)
            Z_ = A / B;
        g_ *= takeZpower_(Z_, Zpower_);
    }
    ChanBase::setGk(er, g_ * vGetModulation(er));
    updateIk();
    // Gk_ = g_;
    // Ik_ = ( Ek_ - Vm_ ) * g_;
    // Send out the relevant channel messages.
    // Same for reinit as for process.
    sendReinitMsgs(er, info);
    g_ = 0.0;
}
References depValue(), Eref::element(), HHChannelBase::EPSILON, HHChannelBase::g_, ChanBase::getGbar(), Element::getName(), HHGateF2D::lookupBoth(), ChanCommon::sendReinitMsgs(), ChanBase::setGk(), HHChannelBase::takeXpower_, HHChannelBase::takeYpower_, HHChannelBase::takeZpower_, ChanCommon::updateIk(), ChanCommon::vGetModulation(), HHChannelBase::X_, Xdep0_, Xdep1_, xGate_, HHChannelBase::xInited_, HHChannelBase::Xpower_, HHChannelBase::Y_, Ydep0_, Ydep1_, yGate_, HHChannelBase::yInited_, HHChannelBase::Ypower_, HHChannelBase::Z_, Zdep0_, Zdep1_, zGate_, HHChannelBase::zInited_, and HHChannelBase::Zpower_.
Member Data Documentation
conc1_
double HHChannelF2D::conc1_ private
Definition at line 134 of file HHChannelF2D.h.
Referenced by conc1(), depValue(), and HHChannelF2D().
conc2_
double HHChannelF2D::conc2_ private
Definition at line 135 of file HHChannelF2D.h.
Referenced by conc2(), depValue(), and HHChannelF2D().
Xdep0_
int HHChannelF2D::Xdep0_ private
Definition at line 141 of file HHChannelF2D.h.
Referenced by HHChannelF2D(), setXindex(), vProcess(), and vReinit().
Xdep1_
int HHChannelF2D::Xdep1_ private
Definition at line 142 of file HHChannelF2D.h.
Referenced by HHChannelF2D(), setXindex(), vProcess(), and vReinit().
xGate_
HHGateF2D* HHChannelF2D::xGate_ private
HHGateF2D data structure for the xGate. This is writable only on the HHChannel that originally created the HHGate, for others it must be treated as readonly.
Definition at line 153 of file HHChannelF2D.h.
Referenced by checkOriginal(), destroyGate(), getNumXgates(), getXgate(), HHChannelF2D(), vCreateGate(), vProcess(), and vReinit().
Xindex_
string HHChannelF2D::Xindex_ private
Definition at line 137 of file HHChannelF2D.h.
Referenced by getXindex(), and setXindex().
Ydep0_
int HHChannelF2D::Ydep0_ private
Definition at line 143 of file HHChannelF2D.h.
Referenced by HHChannelF2D(), setYindex(), vProcess(), and vReinit().
Ydep1_
int HHChannelF2D::Ydep1_ private
Definition at line 144 of file HHChannelF2D.h.
Referenced by HHChannelF2D(), setYindex(), vProcess(), and vReinit().
yGate_
HHGateF2D* HHChannelF2D::yGate_ private
Definition at line 154 of file HHChannelF2D.h.
Referenced by checkOriginal(), destroyGate(), getNumYgates(), getYgate(), HHChannelF2D(), vCreateGate(), vProcess(), and vReinit().
Yindex_
string HHChannelF2D::Yindex_ private
Definition at line 138 of file HHChannelF2D.h.
Referenced by getYindex(), and setYindex().
Zdep0_
int HHChannelF2D::Zdep0_ private
Definition at line 145 of file HHChannelF2D.h.
Referenced by HHChannelF2D(), setZindex(), vProcess(), and vReinit().
Zdep1_
int HHChannelF2D::Zdep1_ private
Definition at line 146 of file HHChannelF2D.h.
Referenced by HHChannelF2D(), setZindex(), vProcess(), and vReinit().
zGate_
HHGateF2D* HHChannelF2D::zGate_ private
HHGateF2D for the yGate.
Definition at line 155 of file HHChannelF2D.h.
Referenced by checkOriginal(), destroyGate(), getNumZgates(), getZgate(), HHChannelF2D(), vCreateGate(), vProcess(), and vReinit().
Zindex_
string HHChannelF2D::Zindex_ private
Definition at line 139 of file HHChannelF2D.h.
Referenced by getZindex(), and setZindex().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/biophysics/HHChannelF2D.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/biophysics/HHChannelF2D.cpp