MOOSE - Multiscale Object Oriented Simulation Environment: StochSecondOrderSingleSubstrate Class Reference
StochSecondOrderSingleSubstrate Class Reference
#include <RateTerm.h>
Public Member Functions
RateTerm * copyWithVolScaling (double vol, double sub, double prd) const
unsigned int getReactants (vector< unsigned int > &molIndex) const
double operator() (const double *S) const
Computes the rate. The argument is the molecule array.
void rescaleVolume (short comptIndex, const vector< short > &compartmentLookup, double ratio)
StochSecondOrderSingleSubstrate (double k, unsigned int y)
Public Member Functions inherited from ZeroOrder
RateTerm * copyWithVolScaling (double vol, double sub, double prd) const
double getR1 () const
Used by Zombie to return rate terms.
double getR2 () const
Used by Zombie to return rate terms.
unsigned int getReactants (vector< unsigned int > &molIndex) const
double operator() (const double *S) const
Computes the rate. The argument is the molecule array.
void rescaleVolume (short comptIndex, const vector< short > &compartmentLookup, double ratio)
void setK (double k)
void setR1 (double k1)
Used by Zombie to assign rate terms.
void setR2 (double k2)
Used by Zombie to assign rate terms.
void setRates (double k1, double k2)
ZeroOrder (double k)
Public Member Functions inherited from RateTerm
RateTerm ()
virtual ~RateTerm ()
Private Attributes
const unsigned int y_
Additional Inherited Members
Static Public Attributes inherited from RateTerm
static const double EPSILON = 1.0e-6
Protected Attributes inherited from ZeroOrder
double k_
Detailed Description
The reason for this class is that if we have a single substrate acting in 2nd order, we must account for the removal of one molecule halfway through the reaction. This has a major effect when there is only one molecule to start with: the eventual # would become negative if we didn't do this correction!
Definition at line 470 of file RateTerm.h.
Constructor & Destructor Documentation
StochSecondOrderSingleSubstrate()
StochSecondOrderSingleSubstrate::StochSecondOrderSingleSubstrate (double k, unsigned int y) inline
Definition at line 473 of file RateTerm.h.
        : ZeroOrder( k ), y_( y )
    {;}
References y_, and ZeroOrder::ZeroOrder().
Referenced by Stoich::convertRatesToStochasticForm(), and copyWithVolScaling().
Member Function Documentation
copyWithVolScaling()
RateTerm * StochSecondOrderSingleSubstrate::copyWithVolScaling (double vol, double sub, double prd) const inline virtual
Duplicates rate term and then applies volume scaling. Arguments are volume of reference voxel, product of vol/refVol for all substrates: applied to R1 product of vol/refVol for all products: applied to R2
Note that unless the reaction is cross-compartment, the vol/refVol will be one.
Implements RateTerm.
Definition at line 500 of file RateTerm.h.
    {
        double ratio = sub * vol * NA;
        return new StochSecondOrderSingleSubstrate( k_ / ratio, y_ );
    }
References ZeroOrder::k_, NA, StochSecondOrderSingleSubstrate(), and y_.
getReactants()
unsigned int StochSecondOrderSingleSubstrate::getReactants (vector< unsigned int > & molIndex) const inline virtual
This function finds the reactant indices in the vector S. It returns the number of substrates found, which are the first entries in molIndex. The products are the remaining ones. Note that it does NOT find products for unidirectional reactions, which is a bit of a problem.
Implements RateTerm.
Definition at line 485 of file RateTerm.h.
    {
        molIndex.resize( 2 );
        molIndex[0] = y_;
        molIndex[1] = y_;
        return 2;
    }
References y_.
operator()()
double StochSecondOrderSingleSubstrate::operator() (const double * S) const inline virtual
Computes the rate. The argument is the molecule array.
Implements RateTerm.
Definition at line 477 of file RateTerm.h.
    {
        double y = S[ y_ ];
        auto res = k_ * ( y - 1 ) * y;
        assert(! std::isnan(res) );
        return res;
    }
References ZeroOrder::k_, and y_.
rescaleVolume()
void StochSecondOrderSingleSubstrate::rescaleVolume (short comptIndex, const vector< short > & compartmentLookup, double ratio) inline virtual
This is used to rescale the RateTerm kinetics when the compartment volume changes. This is needed because the kinetics are in extensive units, that is, mol numbers, rather than in intensive units like concentration. So when the volume changes the rate terms change. Each Rate term checks if any of its reactant molecules are affected, and if so, rescales. Ratio is newVol / oldVol
Implements RateTerm.
Definition at line 493 of file RateTerm.h.
    {
        if ( comptIndex == compartmentLookup[ y_ ] )
            k_ /= ratio;
    }
References ZeroOrder::k_, and y_.
Member Data Documentation
y_
const unsigned int StochSecondOrderSingleSubstrate::y_ private
Definition at line 508 of file RateTerm.h.
Referenced by copyWithVolScaling(), getReactants(), operator()(), rescaleVolume(), and StochSecondOrderSingleSubstrate().
The documentation for this class was generated from the following file:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/ksolve/RateTerm.h