MOOSE - Multiscale Object Oriented Simulation Environment: MMEnzyme Class Reference
MMEnzyme Class Reference
#include <RateTerm.h>
Public Member Functions
RateTerm * copyWithVolScaling (double vol, double sub, double prd) const
unsigned int getReactants (vector< unsigned int > &molIndex) const
MMEnzyme (double Km, double kcat, unsigned int enz, RateTerm *sub)
double operator() (const double *S) const
Computes the rate. The argument is the molecule array.
Public Member Functions inherited from MMEnzymeBase
unsigned int getEnzIndex () const
double getR1 () const
Used by Zombie to return rate terms.
double getR2 () const
Used by Zombie to return rate terms.
MMEnzymeBase (double Km, double kcat, unsigned int enz)
void rescaleVolume (short comptIndex, const vector< short > &compartmentLookup, double ratio)
void setKcat (double kcat)
void setKm (double Km)
void setR1 (double Km)
Used by Zombie to assign rate terms.
void setR2 (double kcat)
Used by Zombie to assign rate terms.
void setRates (double Km, double kcat)
Public Member Functions inherited from RateTerm
RateTerm ()
virtual ~RateTerm ()
Private Attributes
RateTerm * substrates_
Additional Inherited Members
Static Public Attributes inherited from RateTerm
static const double EPSILON = 1.0e-6
Protected Attributes inherited from MMEnzymeBase
unsigned int enz_
double kcat_
double Km_
Detailed Description
Definition at line 183 of file RateTerm.h.
Constructor & Destructor Documentation
MMEnzyme()
MMEnzyme::MMEnzyme (double Km, double kcat, unsigned int enz, RateTerm * sub) inline
Definition at line 186 of file RateTerm.h.
        : MMEnzymeBase( Km, kcat, enz ), substrates_( sub )
    {
        ;
    }
References MMEnzymeBase::MMEnzymeBase(), and substrates_.
Referenced by copyWithVolScaling(), and Stoich::installMMenz().
Member Function Documentation
copyWithVolScaling()
RateTerm * MMEnzyme::copyWithVolScaling (double vol, double sub, double prd) const inline virtual
Duplicates rate term and then applies volume scaling. Arguments are volume of reference voxel, product of vol/refVol for all substrates: applied to R1 product of vol/refVol for all products: applied to R2
Note that unless the reaction is cross-compartment, the vol/refVol will be one.
Implements RateTerm.
Definition at line 210 of file RateTerm.h.
    {
        double ratio = sub * vol * NA;
        return new MMEnzyme( ratio * Km_, kcat_, enz_, substrates_ );
    }
References MMEnzymeBase::enz_, MMEnzymeBase::kcat_, MMEnzymeBase::Km_, MMEnzyme(), NA, and substrates_.
getReactants()
unsigned int MMEnzyme::getReactants (vector< unsigned int > & molIndex) const inline virtual
This function finds the reactant indices in the vector S. It returns the number of substrates found, which are the first entries in molIndex. The products are the remaining ones. Note that it does NOT find products for unidirectional reactions, which is a bit of a problem.
Implements RateTerm.
Definition at line 203 of file RateTerm.h.
    {
        substrates_->getReactants( molIndex );
        molIndex.insert( molIndex.begin(), enz_ );
        return molIndex.size();
    }
References MMEnzymeBase::enz_, RateTerm::getReactants(), and substrates_.
operator()()
double MMEnzyme::operator() (const double * S) const inline virtual
Computes the rate. The argument is the molecule array.
Implements RateTerm.
Definition at line 193 of file RateTerm.h.
    {
        double sub = (*substrates_)( S );
        // the subtrates_() operator returns the conc product.
        assert( sub >= -EPSILON );
        auto val = ( sub * kcat_ * S[ enz_ ] ) / ( Km_ + sub );
        assert(! std::isnan(val));
        return val;
    }
References MMEnzymeBase::enz_, RateTerm::EPSILON, MMEnzymeBase::kcat_, MMEnzymeBase::Km_, RateTerm::operator()(), and substrates_.
Member Data Documentation
substrates_
RateTerm* MMEnzyme::substrates_ private
Definition at line 217 of file RateTerm.h.
Referenced by copyWithVolScaling(), getReactants(), MMEnzyme(), and operator()().
The documentation for this class was generated from the following file:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/ksolve/RateTerm.h