MOOSE - Multiscale Object Oriented Simulation Environment: SetGet1< A > Class Template Reference
SetGet1< A > Class Template Reference
#include <SetGet.h>
Public Member Functions
bool checkOpClass (const OpFunc *op) const
SetGet1 ()
Public Member Functions inherited from SetGet
SetGet ()
virtual ~SetGet ()
Static Public Member Functions
static bool innerStrSet (const ObjId &dest, const string &field, const string &val)
static bool set (const ObjId &dest, const string &field, A arg)
static bool setRepeat (ObjId destId, const string &field, const A &arg)
static bool setVec (ObjId destId, const string &field, const vector< A > &arg)
Static Public Member Functions inherited from SetGet
static const OpFunc * checkSet (const string &field, ObjId &tgt, FuncId &fid)
static const vector< double * > * dispatchGet (const ObjId &tgt, FuncId tgtFid, const double *arg, unsigned int size)
Sends out request for data, and awaits its return.
static bool strGet (const ObjId &tgt, const string &field, string &ret)
static bool strSet (const ObjId &dest, const string &field, const string &val)
Detailed Description
template<class A>
class SetGet1< A >
Definition at line 161 of file SetGet.h.
Constructor & Destructor Documentation
SetGet1()
template<class A > SetGet1< A >::SetGet1 () inline
Definition at line 164 of file SetGet.h.
    {
        ;
    }
Member Function Documentation
checkOpClass()
template<class A > bool SetGet1< A >::checkOpClass (const OpFunc * op) const inline virtual
Implements SetGet.
Definition at line 254 of file SetGet.h.
    {
        return dynamic_cast< const OpFunc1Base< A > * >( op );
    }
innerStrSet()
template<class A > static bool SetGet1< A >::innerStrSet (const ObjId & dest, const string & field, const string & val) inline static
Blocking call using string conversion
Definition at line 246 of file SetGet.h.
    {
        A arg;
        Conv< A >::str2val( arg, val );
        return set( dest, field, arg );
    }
References SetGet1< A >::set().
set()
template<class A > static bool SetGet1< A >::set (const ObjId & dest, const string & field, A arg) inline static
Blocking, typed 'Set' call
Definition at line 172 of file SetGet.h.
    {
        FuncId fid;
        ObjId tgt( dest );
        const OpFunc* func = checkSet( field, tgt, fid );
        const OpFunc1Base< A >* op = dynamic_cast< const OpFunc1Base< A >* >( func );
        if ( op )
        {
            if ( tgt.isOffNode() )
            {
                const OpFunc* op2 = op->makeHopFunc(
                                        HopIndex( op->opIndex(), MooseSetHop ) );
                const OpFunc1Base< A >* hop =
                    dynamic_cast< const OpFunc1Base< A >* >( op2 );
                hop->op( tgt.eref(), arg );
                delete op2;
                if ( tgt.isGlobal() )
                    op->op( tgt.eref(), arg );
                return true;
            }
            else
            {
                op->op( tgt.eref(), arg );
                return true;
            }
        }
        return false;
    }
References SetGet::checkSet(), ObjId::eref(), ObjId::isGlobal(), ObjId::isOffNode(), MooseSetHop, and ObjId::ObjId().
Referenced by ReadKkit::assignPoolCompartments(), Shell::doDelete(), Shell::innerAddMsg(), innerCopyElements(), innerCopyMsgs(), Shell::innerCreate(), Shell::innerMove(), SetGet1< A >::innerStrSet(), testGetMsg(), testMpiFibonacci(), testShellSetGet(), Stoich::unZombifyModel(), Stoich::zombifyModel(), and Stoich::zombifyPoolFuncWithScaling().
setRepeat()
template<class A > static bool SetGet1< A >::setRepeat (ObjId destId, const string & field, const A & arg) inline static
Sets all target array values to the single value
Definition at line 236 of file SetGet.h.
    {
        vector< A >temp ( 1, arg );
        return setVec( destId, field, temp );
    }
References SetGet1< A >::setVec().
Referenced by testSparseMsg().
setVec()
template<class A > static bool SetGet1< A >::setVec (ObjId destId, const string & field, const vector< A > & arg) inline static
setVec assigns all the entries in the target Id to the specified vector of values. If the target is a FieldElement it assigns the entries on the specific DataIndex provided in the ObjId argument. The vector is used as a circular buffer: if the number of targets exceeds the vector size, it rolls over.
Definition at line 210 of file SetGet.h.
    {
        if ( arg.size() == 0 ) return 0;
        ObjId tgt( destId );
        FuncId fid;
        const OpFunc* func = checkSet( field, tgt, fid );
        const OpFunc1Base< A >* op = dynamic_cast< const OpFunc1Base< A >* >( func );
        if ( op )
        {
            const OpFunc* op2 = op->makeHopFunc(
                                    HopIndex( op->opIndex(), MooseSetVecHop ) );
            const OpFunc1Base< A >* hop =
                dynamic_cast< const OpFunc1Base< A >* >( op2 );
            hop->opVec( tgt.eref(), arg, op );
            delete op2;
            return true;
        }
        return false;
    }
References SetGet::checkSet(), ObjId::eref(), MooseSetVecHop, and ObjId::ObjId().
Referenced by benchmarkMsg(), SetGet1< A >::setRepeat(), testAssortedMsg(), testShellAddMsg(), and testShellSetGet().
The documentation for this class was generated from the following file:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/basecode/SetGet.h