MOOSE - Multiscale Object Oriented Simulation Environment: moose::MooseParser Class Reference
moose::MooseParser Class Reference
#include <MooseParser.h>
Public Member Functions
void ClearAll ()
void ClearVariables ()
bool CompileExpr ()
void DefineConst (const string &cname, const double val)
void DefineFun1 (const string &funcName, double(&func)(double))
bool DefineVar (const string varName, double *const v)
double Derivative (const string &name, unsigned int nth=1) const
double Diff (const double a, const double b) const
double Eval (bool check=false) const
double GetConst (const string &name) const
Parser::varmap_type GetConstants () const
const string & GetExpr () const
Parser::symbol_table_t & GetSymbolTable ()
double GetVarValue (const string &name) const
bool IsConst (const string &name) const
MooseParser ()
bool ParseVariables (const string &expr, vector< string > &vars)
Internal function to do a first pass of parsing to obtain variable names.
void PrintSymbolTable () const
bool SetExpr (const string &expr)
~MooseParser ()
Static Public Member Functions
static double Fmod (double a, double b)
static double Ln (double v)
static double Rand ()
static double Rand2 (double a, double b)
static string Reformat (const string user_expr)
static double SRand (double seed)
static double SRand2 (double a, double b, double seed)
Private Attributes
string expr_ {"0"}
Parser::expression_t expression_
unsigned int num_user_defined_funcs_ {0}
Parser::symbol_table_t symbolTable_
bool valid_ {false}
Detailed Description
Definition at line 56 of file MooseParser.h.
Constructor & Destructor Documentation
MooseParser()
moose::MooseParser::MooseParser ()
Definition at line 42 of file MooseParser.cpp.
{
    symbolTable_.add_constants();
    init_symtab(symbolTable_);
    expression_.register_symbol_table(symbolTable_);
    SetExpr(expr_);
}
References expr_, expression_, moose::init_symtab(), SetExpr(), and symbolTable_.
Referenced by nuParser::nuParser().
~MooseParser()
moose::MooseParser::~MooseParser ()
Definition at line 50 of file MooseParser.cpp.
{
}
Member Function Documentation
ClearAll()
void moose::MooseParser::ClearAll ()
Definition at line 365 of file MooseParser.cpp.
{
  ClearVariables();
  symbolTable_.clear_local_constants();
}
References ClearVariables(), and symbolTable_.
Referenced by FuncTerm::setReactantIndex().
ClearVariables()
void moose::MooseParser::ClearVariables ()
Definition at line 358 of file MooseParser.cpp.
{
    expr_ = "";
    expression_.release();
    symbolTable_.clear_variables();
}
References expr_, expression_, and symbolTable_.
Referenced by ClearAll().
CompileExpr()
bool moose::MooseParser::CompileExpr ()
@Synopsis Compile a given expression.
@Returns Return true if successful, throws exception if compilation fails. Exception includes a detailed diagnostic.
Definition at line 262 of file MooseParser.cpp.
{
    // User should make sure that symbol table has been setup. Do not raise
    // exception here. User can set expression again.
    // GCC specific
    ASSERT_FALSE(expr_.empty(),
                 __func__ << ": Empty expression not allowed here");
    // expression_.release();
    // symbolTable_.clear_variables();
    Parser::parser_t parser;
    parser.enable_unknown_symbol_resolver();
    valid_ = parser.compile(expr_, expression_);
    // This should never occur, as we are running this as a second pass
    if (!valid_) {
        expr_ = "";
        stringstream ss;
        ss << "Failed to parse '" << expr_ << "' :" << endl;
        for (unsigned int i = 0; i < parser.error_count(); ++i)
        {
            Parser::error_t error = parser.get_error(i);
            ss << "Error[" << i << "] Position: " << error.token.position
               << " Type: [" << exprtk::parser_error::to_str(error.mode)
               << "] Msg: " << error.diagnostic << endl;
            // map is
            Parser::varmap_type vars;
            auto n = symbolTable_.get_variable_list(vars);
            ss << "More Information:\nTotal variables " << n << ".";
            for (auto i : vars)
                ss << "\t" << i.first << "=" << i.second << " "
                   << symbolTable_.get_variable(i.first)->ref();
            ss << endl;
        }
        valid_ = false;
        throw moose::Parser::exception_type(ss.str());
    }
    return valid_;
}
References expr_, expression_, moose::Parser::ParserException::ParserException(), symbolTable_, and valid_.
Referenced by SetExpr().
DefineConst()
void moose::MooseParser::DefineConst (const string & cname, const double val)
Definition at line 145 of file MooseParser.cpp.
{
    if (symbolTable_.is_constant_node(constName)) {
        cout << "Warning: Ignoring attempt to change existing constant "
             << constName << endl;
    }
    else if (!symbolTable_.add_constant(constName, value)) {
        cout << "Warning: Failed to set constant " << constName << " = "
             << value << endl;
    }
}
References symbolTable_.
Referenced by Function::reinit().
DefineFun1()
void moose::MooseParser::DefineFun1 (const string & funcName, double(&)(double) func)
Definition at line 157 of file MooseParser.cpp.
{
    // Add a function. This function currently handles only one argument
    // function.
    num_user_defined_funcs_ += 1;
    symbolTable_.add_function(funcName, func);
}
References num_user_defined_funcs_, and symbolTable_.
Referenced by nuParser::nuParser().
DefineVar()
bool moose::MooseParser::DefineVar (const string varName, double *const v)
Definition at line 134 of file MooseParser.cpp.
{
    // Use in copy assignment.
    auto* existing = symbolTable_.get_variable(varName);
    if (existing){
        existing->ref() = *val;
        return true;
    }
    return symbolTable_.add_variable(varName, *val);
}
References symbolTable_.
Referenced by Function::innerSetExpr(), nuParser::nuParser(), FuncTerm::setReactantIndex(), and SeqSynHandler::updateKernel().
Derivative()
double moose::MooseParser::Derivative (const string & name, unsigned int nth = 1) const
Definition at line 303 of file MooseParser.cpp.
{
    if(nth > 3)
    {
        cout << "Error: " << nth << "th derivative is not supported." << endl;
        return 0.0;
    }
    if(nth == 3)
        return exprtk::third_derivative(expression_, name);
    if(nth == 2)
        return exprtk::second_derivative(expression_, name);
    return exprtk::derivative(expression_, name);
}
References expression_.
Diff()
double moose::MooseParser::Diff (const double a, const double b) const
Definition at line 337 of file MooseParser.cpp.
{
    return a-b;
}
Eval()
double moose::MooseParser::Eval (bool check = false) const
Definition at line 317 of file MooseParser.cpp.
{
    if(! valid_)
    {
        throw runtime_error("MooseParser::Eval: Invalid parser state.");
    }
    if(expr_.empty())
    {
        cout << "MooseParser::Eval: Warn: Expr is empty " << endl;
        return 0.0;
    }
    // PrintSymbolTable();
    // Make sure that no symbol is unknown at this point. Else emit error. The
    // Function::reinit must take of it.
    return expression_.value();
}
References expr_, expression_, and valid_.
Referenced by nuParser::eval(), FuncTerm::evalPool(), FuncTerm::operator()(), Function::setConst(), and SeqSynHandler::updateKernel().
Fmod()
double moose::MooseParser::Fmod (double a, double b) static
Definition at line 86 of file MooseParser.cpp.
{
    return fmod(a, b);
}
Referenced by moose::init_symtab().
GetConst()
double moose::MooseParser::GetConst (const string & name) const
Definition at line 348 of file MooseParser.cpp.
{
    if(!IsConst(name)) {
    // if(!GetSymbolTable().type_store.is_constant(name)) {
        cout << "Warning: no constant defined with name " << name << endl;
        return 0.0;
    }
    return symbolTable_.get_variable(name)->value();
}
References IsConst(), and symbolTable_.
GetConstants()
Parser::varmap_type moose::MooseParser::GetConstants () const
Get a vector of <name, value> pairs of all defined constants
Definition at line 105 of file MooseParser.cpp.
{
    Parser::varmap_type constants;
    Parser::varmap_type vars;
    symbolTable_.get_variable_list(vars);
    for (auto var : vars) {
        if (symbolTable_.is_constant_node(var.first)) {
            constants.push_back(var);
        }
    }
    return constants;
}
References symbolTable_.
GetExpr()
const string & moose::MooseParser::GetExpr () const
Definition at line 371 of file MooseParser.cpp.
{
    return expr_;
}
References expr_.
GetSymbolTable()
Parser::symbol_table_t & moose::MooseParser::GetSymbolTable ()
Definition at line 95 of file MooseParser.cpp.
{
    return symbolTable_;
}
References symbolTable_.
GetVarValue()
double moose::MooseParser::GetVarValue (const string & name) const
Definition at line 100 of file MooseParser.cpp.
{
    return symbolTable_.get_variable(name)->value();
}
References symbolTable_.
IsConst()
bool moose::MooseParser::IsConst (const string & name) const
Definition at line 342 of file MooseParser.cpp.
{
    return symbolTable_.is_constant_node(name);
}
References symbolTable_.
Referenced by GetConst().
Ln()
double moose::MooseParser::Ln (double v) static
Definition at line 57 of file MooseParser.cpp.
{
    return std::log(v);
}
Referenced by moose::init_symtab().
ParseVariables()
bool moose::MooseParser::ParseVariables (const string & expr, vector< string > & vars)
Internal function to do a first pass of parsing to obtain variable names.
Definition at line 209 of file MooseParser.cpp.
{
    ASSERT_FALSE(expr.empty(),
                 __func__ << ": Empty expression not allowed here");
    Parser::symbol_table_t symtab;
    Parser::expression_t expression;
    Parser::parser_t parser;
    parser.enable_unknown_symbol_resolver();
    symtab.add_constants();
    init_symtab(symtab);
    expression.register_symbol_table(symtab);
    bool res = parser.compile(expr, expression);
    if (!res) {
        Parser::varmap_type varmap;
        stringstream ss;
        ss << "Failed to parse '" << expr << "' :" << endl;
        for (unsigned int i = 0; i < parser.error_count(); ++i) {
            Parser::error_t error = parser.get_error(i);
            ss << "Error[" << i << "] Position: " << error.token.position
               << " Type: [" << exprtk::parser_error::to_str(error.mode)
               << "] Msg: " << error.diagnostic << endl;
            // map is
            auto n = symtab.get_variable_list(varmap);
            ss << "More Information:\nTotal variables " << n << ".";
            for (auto i : varmap)
                ss << "\t" << i.first << "=" << i.second << " "
                   << symtab.get_variable(i.first)->ref();
            ss << endl;
        }
        // Throw the error, this is handled in callee.
        throw moose::Parser::exception_type(ss.str());
    }
    vector<string> varlist;
    symtab.get_variable_list(varlist);
    for (auto name : varlist) {
        if (!symtab.is_constant_node(name)) {
            vars.push_back(name);
        }
    }
    return res;
}
References moose::init_symtab(), and moose::Parser::ParserException::ParserException().
PrintSymbolTable()
void moose::MooseParser::PrintSymbolTable (void) const
Definition at line 118 of file MooseParser.cpp.
{
    stringstream ss;
    auto symbTable = symbolTable_;
    vector<pair<string, double>> vars;
    auto n = symbTable.get_variable_list(vars);
    ss << "More Information:\nTotal variables " << n << ".";
    for (auto i : vars)
        ss << "\t" << i.first << "=" << i.second << " "
           << symbTable.get_variable(i.first)->ref();
    cerr << ss.str() << endl;
}
References symbolTable_.
Rand()
double moose::MooseParser::Rand () static
Definition at line 62 of file MooseParser.cpp.
{
    return moose::mtrand();
}
References moose::mtrand().
Referenced by moose::init_symtab().
Rand2()
double moose::MooseParser::Rand2 (double a, double b) static
Definition at line 74 of file MooseParser.cpp.
{
    return moose::mtrand( a, b );
}
References moose::mtrand().
Referenced by moose::init_symtab().
Reformat()
string moose::MooseParser::Reformat (const string user_expr) static
@Synopsis EXPRTK does not have && and || but have 'and' and 'or' symbol. Replace && with 'and' and '||' with 'or'.
@Param user_expr
@Returns
Definition at line 176 of file MooseParser.cpp.
{
    string expr( user_expr );
    // Replate || with 'or'
    moose::str_replace_all( expr, "||", " or " );
    // Replace && with 'and'
    moose::str_replace_all( expr, "&&", " and " );
    // Trickt business: Replace ! with not but do not change !=
    moose::str_replace_all( expr, "!=", "@@@" ); // placeholder
    moose::str_replace_all( expr, "!", " not " );
    moose::str_replace_all( expr, "@@@", "!=" ); // change back @@@ to !=
    return expr;
}
References moose::str_replace_all().
Referenced by SetExpr().
SetExpr()
bool moose::MooseParser::SetExpr (const string & user_expr)
@Synopsis Set expression on parser.
@Param user_expr
@Returns
Definition at line 202 of file MooseParser.cpp.
{
    ASSERT_FALSE( user_expr.empty(), "Empty expression" );
    expr_ = Reformat(user_expr);
    return CompileExpr();
}
References CompileExpr(), expr_, and Reformat().
Referenced by MooseParser(), nuParser::nuParser(), FuncTerm::setExpr(), and SeqSynHandler::updateKernel().
SRand()
double moose::MooseParser::SRand (double seed = -1) static
Definition at line 67 of file MooseParser.cpp.
{
    if( seed >= 0 )
        moose::mtseed( (unsigned int) seed );
    return moose::mtrand();
}
References moose::mtrand(), and moose::mtseed().
Referenced by moose::init_symtab().
SRand2()
double moose::MooseParser::SRand2 (double a, double b, double seed = -1) static
Definition at line 79 of file MooseParser.cpp.
{
    if( seed >= 0 )
        moose::mtseed( (unsigned int) seed );
    return moose::mtrand( a, b );
}
References moose::mtrand(), and moose::mtseed().
Referenced by moose::init_symtab().
Member Data Documentation
expr_
string moose::MooseParser::expr_ {"0"} private
Definition at line 129 of file MooseParser.h.
{"0"};
Referenced by ClearVariables(), CompileExpr(), Eval(), GetExpr(), MooseParser(), and SetExpr().
expression_
Parser::expression_t moose::MooseParser::expression_ private
Definition at line 131 of file MooseParser.h.
Referenced by ClearVariables(), CompileExpr(), Derivative(), Eval(), and MooseParser().
num_user_defined_funcs_
unsigned int moose::MooseParser::num_user_defined_funcs_ {0} private
Definition at line 133 of file MooseParser.h.
{0};
Referenced by DefineFun1().
symbolTable_
Parser::symbol_table_t moose::MooseParser::symbolTable_ private
Definition at line 132 of file MooseParser.h.
Referenced by ClearAll(), ClearVariables(), CompileExpr(), DefineConst(), DefineFun1(), DefineVar(), GetConst(), GetConstants(), GetSymbolTable(), GetVarValue(), IsConst(), MooseParser(), and PrintSymbolTable().
valid_
bool moose::MooseParser::valid_ {false} private
Definition at line 134 of file MooseParser.h.
{false};
Referenced by CompileExpr(), and Eval().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/builtins/MooseParser.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/builtins/MooseParser.cpp