MOOSE - Multiscale Object Oriented Simulation Environment: ConcChan Class Reference
ConcChan Class Reference
#include <ConcChan.h>
Public Member Functions
ConcChan ()
double flux (double inConc, double outConc, double dt)
double getFlux () const
double getNumChan () const
double getPermeability () const
void inPool (double conc)
void outPool (double conc)
void process (const Eref &e, ProcPtr p)
void reinit (const Eref &e, ProcPtr p)
void setNumChan (double v)
void setPermeability (double v)
~ConcChan ()
Static Public Member Functions
static const Cinfo * initCinfo ()
Protected Attributes
double charge_
Flux of molecule through channel.
double flux_
Number of molecules of channel.
double n_
permeability in vol/(#.s) units.
double permeability_
double Vm_
Later: for including Nernst calculations.
Detailed Description
Definition at line 13 of file ConcChan.h.
Constructor & Destructor Documentation
ConcChan()
ConcChan::ConcChan ()
Definition at line 135 of file ConcChan.cpp.
    : permeability_( 0.1 ),
        n_( 0.0 ),
        flux_( 0.0 ),
        charge_( 0.0 ),
        Vm_( 0.0 )
{
    ;
}
References charge_, flux_, n_, permeability_, and Vm_.
~ConcChan()
ConcChan::~ConcChan ()
Definition at line 145 of file ConcChan.cpp.
{;}
Member Function Documentation
flux()
double ConcChan::flux (double inConc, double outConc, double dt)
Definition at line 201 of file ConcChan.cpp.
{
    return permeability_ * n_ * ( outConc - inConc ) * dt;
    // Later add stuff for voltage dependence.
    // Also use exp Euler
}
References n_, and permeability_.
getFlux()
double ConcChan::getFlux () const
Definition at line 193 of file ConcChan.cpp.
{
    return flux_;
}
References flux_.
Referenced by initCinfo().
getNumChan()
double ConcChan::getNumChan () const
Definition at line 188 of file ConcChan.cpp.
{
    return n_;
}
References n_.
Referenced by initCinfo().
getPermeability()
double ConcChan::getPermeability () const
Definition at line 178 of file ConcChan.cpp.
{
    return permeability_;
}
References permeability_.
Referenced by initCinfo().
initCinfo()
const Cinfo * ConcChan::initCinfo () static
Definition at line 29 of file ConcChan.cpp.
{
        // Field Definitions
        static ValueFinfo< ConcChan, double > permeability(
            "permeability",
            "Permability, in units of vol/(#s) i.e., 1/(numconc.s) "
            "Flux (#/s) = permeability * N * (#out/vol_out - #in/vol_in)",
            &ConcChan::setPermeability,
            &ConcChan::getPermeability
        );
        static ValueFinfo< ConcChan, double > numChan(
            "numChan",
            "numChan is the number of molecules of the channel.",
            &ConcChan::setNumChan,
            &ConcChan::getNumChan
        );
        static ReadOnlyValueFinfo< ConcChan, double > flux(
            "flux",
            "Flux of molecules through channel, in units of #/s ",
            &ConcChan::getFlux
        );
        // MsgDest Definitions
        static DestFinfo process( "process",
            "Handles process call",
            new ProcOpFunc< ConcChan >( &ConcChan::process ) );
        static DestFinfo reinit( "reinit",
            "Handles reinit call",
            new ProcOpFunc< ConcChan >( &ConcChan::reinit ) );
        // Shared Msg Definitions
        static DestFinfo inPool( "inPool",
                "Handles # of molecules of pool inside membrane",
                new OpFunc1< ConcChan, double >( &ConcChan::inPool ) );
        static DestFinfo outPool( "outPool",
                "Handles # of molecules of pool outside membrane",
                new OpFunc1< ConcChan, double >( &ConcChan::outPool ) );
        static Finfo* inShared[] = {
            inPoolOut(), &inPool
        };
        static Finfo* outShared[] = {
            outPoolOut(), &outPool
        };
        static SharedFinfo in( "in",
            "Connects to pool on inside",
            inShared, sizeof( inShared ) / sizeof( const Finfo* )
        );
        static SharedFinfo out( "out",
            "Connects to pool on outside",
            outShared, sizeof( outShared ) / sizeof( const Finfo* )
        );
        static Finfo* procShared[] = {
            &process, &reinit
        };
        static SharedFinfo proc( "proc",
            "Shared message for process and reinit",
            procShared, sizeof( procShared ) / sizeof( const Finfo* )
        );
    static Finfo* concChanFinfos[] = {
        &permeability,      // Value
        &numChan,           // Value
        &flux,              // ReadOnlyValue
        &in,                // SharedFinfo
        &out,               // SharedFinfo
        &proc,              // SharedFinfo
    };
    static string doc[] =
    {
        "Name", "ConcChan",
        "Author", "Upinder S. Bhalla, 2018, NCBS",
        "Description", "Channel for molecular flow between cellular "
        "compartments. Need not be ions, and the flux is not a current, "
        "but number of molecules/sec. ",
    };
    static Dinfo< ConcChan > dinfo;
    static Cinfo concChanCinfo (
        "ConcChan",
        Neutral::initCinfo(),
        concChanFinfos,
        sizeof( concChanFinfos ) / sizeof ( Finfo* ),
        &dinfo,
        doc,
        sizeof( doc ) / sizeof( string )
    );
    return &concChanCinfo;
}
References Cinfo::Cinfo(), DestFinfo::DestFinfo(), getFlux(), getNumChan(), getPermeability(), Neutral::initCinfo(), inPool(), inPoolOut(), OpFunc1< T, A >::OpFunc1(), outPool(), outPoolOut(), process(), ProcOpFunc< T >::ProcOpFunc(), ReadOnlyValueFinfo< T, F >::ReadOnlyValueFinfo(), reinit(), setNumChan(), setPermeability(), SharedFinfo::SharedFinfo(), and ValueFinfo< T, F >::ValueFinfo().
inPool()
void ConcChan::inPool (double conc)
Definition at line 161 of file ConcChan.cpp.
{
}
Referenced by initCinfo().
outPool()
void ConcChan::outPool (double conc)
Definition at line 165 of file ConcChan.cpp.
{
}
Referenced by initCinfo().
process()
void ConcChan::process (const Eref & e, ProcPtr p)
Definition at line 153 of file ConcChan.cpp.
{
}
Referenced by initCinfo().
reinit()
void ConcChan::reinit (const Eref & e, ProcPtr p)
Definition at line 157 of file ConcChan.cpp.
{
}
Referenced by initCinfo().
setNumChan()
void ConcChan::setNumChan (double v)
Definition at line 183 of file ConcChan.cpp.
{
    n_ = v;
}
References n_.
Referenced by initCinfo().
setPermeability()
void ConcChan::setPermeability (double v)
Definition at line 173 of file ConcChan.cpp.
{
    permeability_ = v;
}
References permeability_.
Referenced by initCinfo().
Member Data Documentation
charge_
double ConcChan::charge_ protected
Flux of molecule through channel.
Definition at line 48 of file ConcChan.h.
Referenced by ConcChan().
flux_
double ConcChan::flux_ protected
Number of molecules of channel.
Definition at line 47 of file ConcChan.h.
Referenced by ConcChan(), and getFlux().
n_
double ConcChan::n_ protected
permeability in vol/(#.s) units.
Definition at line 46 of file ConcChan.h.
Referenced by ConcChan(), flux(), getNumChan(), and setNumChan().
permeability_
double ConcChan::permeability_ protected
Definition at line 45 of file ConcChan.h.
Referenced by ConcChan(), flux(), getPermeability(), and setPermeability().
Vm_
double ConcChan::Vm_ protected
Later: for including Nernst calculations.
Definition at line 49 of file ConcChan.h.
Referenced by ConcChan().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/kinetics/ConcChan.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/kinetics/ConcChan.cpp