MOOSE - Multiscale Object Oriented Simulation Environment: Finfo Class Reference
Finfo Class Reference abstract
#include <Finfo.h>
Public Member Functions
virtual bool addMsg (const Finfo *target, ObjId mid, Element *src) const
virtual bool checkTarget (const Finfo *target) const
const string & docs () const
Returns documentation string.
Finfo (const string &name, const string &doc)
virtual vector< string > innerDest () const
virtual vector< string > innerSrc () const
const string & name () const
virtual void postCreationFunc (Id newId, Element *newElm) const
virtual void registerFinfo (Cinfo *c)=0
virtual string rttiType () const
virtual bool strGet (const Eref &tgt, const string &field, string &returnValue) const =0
virtual bool strSet (const Eref &tgt, const string &field, const string &arg) const =0
virtual ~Finfo ()
Static Public Member Functions
static const Cinfo * initCinfo ()
Private Attributes
string doc_
string name_
Detailed Description
Definition at line 12 of file Finfo.h.
Constructor & Destructor Documentation
Finfo()
Finfo::Finfo (const string & name, const string & doc)
Definition at line 13 of file Finfo.cpp.
                                                  : name_(name), doc_(doc)
{
    ;
}
References doc_, and name_.
Referenced by DestFinfo::DestFinfo(), FieldElementFinfoBase::FieldElementFinfoBase(), LookupValueFinfoBase::LookupValueFinfoBase(), SharedFinfo::SharedFinfo(), SrcFinfo::SrcFinfo(), and ValueFinfoBase::ValueFinfoBase().
~Finfo()
virtual Finfo::~Finfo () inline virtual
Definition at line 15 of file Finfo.h.
    {
        ;
    }
Member Function Documentation
addMsg()
virtual bool Finfo::addMsg (const Finfo * target, ObjId mid, Element * src) const inline virtual
Sets up specified Msg between src and dest. Does all the type checking. Returns 1 on success. Defaults to 0 because many Finfo combinations won't work.
Reimplemented in SharedFinfo, and SrcFinfo.
Definition at line 91 of file Finfo.h.
    {
        return 0;
    }
Referenced by addClockMsg(), Shell::adopt(), Shell::innerAddMsg(), Shell::innerMove(), FieldElementFinfoBase::postCreationFunc(), testCreateMsg(), testFibonacci(), testMsgSrcDestFields(), testSendSpike(), testSharedMsg(), and testSparseMsg().
checkTarget()
virtual bool Finfo::checkTarget (const Finfo * target) const inline virtual
Registers the Msg slot to be used for transmitting messages. SrcFinfos take the 'current' value and increment it, other msgs leave it alone. virtual BindIndex registerBindIndex(BindIndex current) = 0; Checks that the type of target Finfo matches self, and is safe to exchange messages with. Is called only from msg src, so most Finfos return 0. SrcFinfo and SharedFinfo will need to implement this.
Reimplemented in SharedFinfo, and SrcFinfo.
Definition at line 80 of file Finfo.h.
    {
        return 0;
    }
Referenced by Shell::doAddMsg(), and Shell::innerAddMsg().
docs()
const string & Finfo::docs () const
Returns documentation string.
Definition at line 64 of file Finfo.cpp.
{
    return doc_;
}
References doc_.
Referenced by FinfoWrapper::docs(), pymoose::fieldDocFormatted(), and pymoose::getDoc().
initCinfo()
const Cinfo * Finfo::initCinfo () static
Returns the Class Info for this Finfo
Definition at line 22 of file Finfo.cpp.
{
    static ReadOnlyValueFinfo<FinfoWrapper, string> fieldName(
        "fieldName", "Name of field handled by Finfo", &FinfoWrapper::getName);
    static ReadOnlyValueFinfo<FinfoWrapper, string> docs(
        "docs", "Documentation for Finfo", &FinfoWrapper::docs);
    static ReadOnlyValueFinfo<FinfoWrapper, string> type(
        "type", "RTTI type info for this Finfo", &FinfoWrapper::type);
    static ReadOnlyValueFinfo<FinfoWrapper, vector<string>> src(
        "src", "Subsidiary SrcFinfos. Useful for SharedFinfos",
        &FinfoWrapper::src);
    static ReadOnlyValueFinfo<FinfoWrapper, vector<string>> dest(
        "dest", "Subsidiary DestFinfos. Useful for SharedFinfos",
        &FinfoWrapper::dest);
    static Finfo* finfoFinfos[] = {
        &fieldName,  // ReadOnlyValue
        &docs,       // ReadOnlyValue
        &type,       // ReadOnlyValue
        &src,        // ReadOnlyValue
        &dest,       // ReadOnlyValue
    };
    static Dinfo<Finfo*> dinfo;
    static Cinfo finfoCinfo("Finfo", Neutral::initCinfo(), finfoFinfos,
                            sizeof(finfoFinfos) / sizeof(Finfo*), &dinfo);
    return &finfoCinfo;
}
References Cinfo::Cinfo(), FinfoWrapper::dest(), FinfoWrapper::docs(), FinfoWrapper::getName(), Neutral::initCinfo(), ReadOnlyValueFinfo< T, F >::ReadOnlyValueFinfo(), FinfoWrapper::src(), and FinfoWrapper::type().
Referenced by buildFinfoElement().
innerDest()
vector< string > Finfo::innerDest () const virtual
Returns subsidiary DestFinfos
Reimplemented in SharedFinfo, and ValueFinfoBase.
Definition at line 108 of file Finfo.cpp.
{
    static vector<string> ret;
    return ret;
}
Referenced by FinfoWrapper::dest().
innerSrc()
vector< string > Finfo::innerSrc () const virtual
Returns subsidiary SrcFinfos
Reimplemented in SharedFinfo.
Definition at line 102 of file Finfo.cpp.
{
    static vector<string> ret;
    return ret;
}
Referenced by FinfoWrapper::src().
name()
const string & Finfo::name () const
Returns the Finfo name
Definition at line 59 of file Finfo.cpp.
{
    return name_;
}
References name_.
Referenced by convertConcToNumRateUsingMesh(), pymoose::createDestFunction(), Cinfo::destFinfoName(), pymoose::ElementField::ElementField(), pymoose::VecElementField::getAttribute(), Neutral::getDestFields(), pymoose::getFieldValue(), pymoose::getFinfoDict(), FinfoWrapper::getName(), Neutral::getSourceFields(), Neutral::getValueFields(), SharedFinfo::innerDest(), ValueFinfoBase::innerDest(), SharedFinfo::innerSrc(), FieldElementFinfoBase::postCreationFunc(), DestFinfo::registerFinfo(), Cinfo::registerFinfo(), Cinfo::reportFids(), pymoose::VecElementField::setAttribute(), Element::showFields(), Element::showMsg(), pymoose::VecElementField::size(), pymoose::VecElementField::sizes(), Cinfo::srcFinfoName(), testCinfoFields(), and testMsgSrcDestFields().
postCreationFunc()
virtual void Finfo::postCreationFunc (Id newId, Element * newElm) const inline virtual
This function is called on each new Element after it is created, in case any stuff needs doing. Typical uses are to create FieldElements automatically as soon as the parent is made. Used in FieldElementFinfo.h
Reimplemented in FieldElementFinfoBase.
Definition at line 62 of file Finfo.h.
    {
        ;
    }
Referenced by Cinfo::postCreationFunc().
registerFinfo()
virtual void Finfo::registerFinfo (Cinfo * c) pure virtual
Returns string-ified form to handle template expectations for name field string getName() const; Assign function Ids, bindIndex and so on.
Implemented in DestFinfo, ElementValueFinfo< T, F >, ReadOnlyElementValueFinfo< T, F >, FieldElementFinfoBase, LookupElementValueFinfo< T, L, F >, ReadOnlyLookupElementValueFinfo< T, L, F >, LookupValueFinfo< T, L, F >, ReadOnlyLookupValueFinfo< T, L, F >, SharedFinfo, SrcFinfo, ValueFinfo< T, F >, and ReadOnlyValueFinfo< T, F >.
Referenced by Cinfo::registerFinfo().
rttiType()
string Finfo::rttiType () const virtual
Returns the documentation string for the Finfo string docs() const; Returns the RTTI type string for the finfo by referring to an internal virtual function. string type() const; Returns the list of subsidiary SrcFinfos. Used in Shared Finfos, empty otherwise. Goes via internal virtual function. vector< string > src() const; Returns the list of subsidiary destFinfos. Used in SharedFinfos and ValueFinfos, empty otherwise. Goes via internal virtual function. vector< string > dest() const; Returns an RTTI type string for this Finfo.
Reimplemented in DestFinfo, ElementValueFinfo< T, F >, ReadOnlyElementValueFinfo< T, F >, FieldElementFinfo< T, F >, LookupElementValueFinfo< T, L, F >, ReadOnlyLookupElementValueFinfo< T, L, F >, LookupValueFinfo< T, L, F >, ReadOnlyLookupValueFinfo< T, L, F >, SharedFinfo, SrcFinfo0, SrcFinfo1< T >, SrcFinfo2< T1, T2 >, SrcFinfo3< T1, T2, T3 >, SrcFinfo4< T1, T2, T3, T4 >, SrcFinfo5< T1, T2, T3, T4, T5 >, SrcFinfo6< T1, T2, T3, T4, T5, T6 >, ValueFinfo< T, F >, and ReadOnlyValueFinfo< T, F >.
Definition at line 97 of file Finfo.cpp.
{
    return typeid(*this).name();
}
Referenced by pymoose::createDestFunction(), pymoose::fieldDocFormatted(), pymoose::MooseVec::getAttribute(), pymoose::getDoc(), pymoose::getFieldGeneric(), pymoose::getFieldValue(), pymoose::LookupField::LookupField(), pymoose::MooseVec::setAttribute(), pymoose::setFieldGeneric(), FinfoWrapper::type(), and pymoose::VecLookupField::VecLookupField().
strGet()
virtual bool Finfo::strGet (const Eref & tgt, const string & field, string & returnValue) const pure virtual
Function to return value of field into a string argument. Returns true on success. Normally called only from SetGet::strGet.
Implemented in DestFinfo, ElementValueFinfo< T, F >, ReadOnlyElementValueFinfo< T, F >, FieldElementFinfoBase, LookupElementValueFinfo< T, L, F >, ReadOnlyLookupElementValueFinfo< T, L, F >, LookupValueFinfo< T, L, F >, ReadOnlyLookupValueFinfo< T, L, F >, SharedFinfo, SrcFinfo, ValueFinfo< T, F >, and ReadOnlyValueFinfo< T, F >.
Referenced by Element::showFields(), and SetGet::strGet().
strSet()
virtual bool Finfo::strSet (const Eref & tgt, const string & field, const string & arg) const pure virtual
Function to set this field using a string argument. Returns true on success. Normally called only from SetGet::strSet.
Implemented in DestFinfo, ElementValueFinfo< T, F >, ReadOnlyElementValueFinfo< T, F >, FieldElementFinfoBase, LookupElementValueFinfo< T, L, F >, ReadOnlyLookupElementValueFinfo< T, L, F >, LookupValueFinfo< T, L, F >, ReadOnlyLookupValueFinfo< T, L, F >, SharedFinfo, SrcFinfo, ValueFinfo< T, F >, and ReadOnlyValueFinfo< T, F >.
Referenced by SetGet::strSet().
Member Data Documentation
doc_
string Finfo::doc_ private
Definition at line 146 of file Finfo.h.
Referenced by docs(), and Finfo().
name_
string Finfo::name_ private
Definition at line 145 of file Finfo.h.
Referenced by Finfo(), and name().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/basecode/Finfo.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/basecode/Finfo.cpp