MOOSE - Multiscale Object Oriented Simulation Environment: HopFunc3< A1, A2, A3 > Class Template Reference
HopFunc3< A1, A2, A3 > Class Template Reference
#include <HopFunc.h>
Public Member Functions
HopFunc3 (HopIndex hopIndex)
void op (const Eref &e, A1 arg1, A2 arg2, A3 arg3) const
Public Member Functions inherited from OpFunc3Base< A1, A2, A3 >
bool checkFinfo (const Finfo *s) const
const OpFunc * makeHopFunc (HopIndex hopIndex) const
void opBuffer (const Eref &e, double *buf) const
Executes the OpFunc by converting args.
string rttiType () const
Public Member Functions inherited from OpFunc
OpFunc ()
unsigned int opIndex () const
virtual void opVecBuffer (const Eref &e, double *buf) const
Executes the OpFunc for all data by converting a vector of args.
bool setIndex (unsigned int i)
Used when rebuilding the Fid->OpFunc mapping.
virtual ~OpFunc ()
Private Attributes
HopIndex hopIndex_
Additional Inherited Members
Static Public Member Functions inherited from OpFunc
static const OpFunc * lookop (unsigned int opIndex)
static unsigned int rebuildOpIndex ()
cleans out the entire Ops vector. Returns size of orig vector.
Detailed Description
template<class A1, class A2, class A3>
class HopFunc3< A1, A2, A3 >
Definition at line 276 of file HopFunc.h.
Constructor & Destructor Documentation
HopFunc3()
template<class A1 , class A2 , class A3 > HopFunc3< A1, A2, A3 >::HopFunc3 (HopIndex hopIndex) inline
Definition at line 280 of file HopFunc.h.
                : hopIndex_( hopIndex )
        {;}
References HopFunc3< A1, A2, A3 >::hopIndex_.
Referenced by testHopFunc().
Member Function Documentation
op()
template<class A1 , class A2 , class A3 > void HopFunc3< A1, A2, A3 >::op (const Eref & e, A1 arg1, A2 arg2, A3 arg3) const inline virtual
Implements OpFunc3Base< A1, A2, A3 >.
Definition at line 284 of file HopFunc.h.
        {
            double* buf = addToBuf( e, hopIndex_,
                Conv< A1 >::size( arg1 ) + Conv< A2 >::size( arg2 ) +
                Conv< A3 >::size( arg3 ) );
            Conv< A1 >::val2buf( arg1, &buf );
            Conv< A2 >::val2buf( arg2, &buf );
            Conv< A3 >::val2buf( arg3, &buf );
            dispatchBuffers( e, hopIndex_ );
        }
References dispatchBuffers(), and HopFunc3< A1, A2, A3 >::hopIndex_.
Referenced by testHopFunc().
Member Data Documentation
hopIndex_
template<class A1 , class A2 , class A3 > HopIndex HopFunc3< A1, A2, A3 >::hopIndex_ private
Definition at line 295 of file HopFunc.h.
Referenced by HopFunc3< A1, A2, A3 >::HopFunc3(), and HopFunc3< A1, A2, A3 >::op().
The documentation for this class was generated from the following file:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/basecode/HopFunc.h