MOOSE - Multiscale Object Oriented Simulation Environment: SocketStreamer Class Reference
SocketStreamer Class Reference
#include <SocketStreamer.h>
Public Member Functions
void addTable (ObjId table)
Add a table to streamer.
void addTables (vector< ObjId > tables)
Add multiple tables to SocketStreamer.
void cleanUp (void)
void configureSocketServer (void)
void connect (void)
void dataToStream (map< string, vector< double > > &vec)
bool enoughDataToStream (unsigned int minsize=10)
string getAddress (void) const
string getFormat (void) const
unsigned int getNumTables (void) const
Get the number of tables handled by SocketStreamer.
unsigned int getPort (void) const
void initServer (void)
void initTCPServer (void)
void initUDSServer (void)
void listenToClients (unsigned int numMaxClients)
pair< unsigned int, unsigned int > minMaxNumberOfElemementsInTables ()
SocketStreamer & operator= (const SocketStreamer &st)
void process (const Eref &e, ProcPtr p)
This function is called at its clock tick.
void reinit (const Eref &e, ProcPtr p)
Reinit. We make sure it is non-blocking.
void removeTable (ObjId table)
Remove a table from SocketStreamer.
void removeTables (vector< ObjId > table)
Remove multiple tables – if found – from SocketStreamer.
void setAddress (const string addr)
void setFormat (string format)
void setPort (const unsigned int port)
SocketStreamer ()
void stream (void)
int streamData ()
~SocketStreamer ()
Public Member Functions inherited from StreamerBase
string getOutFilepath () const
StreamerBase & operator= (const StreamerBase &st)
void setOutFilepath (string stream)
StreamerBase ()
string vectorToCSV (const vector< double > &ys, const string &fmt)
~StreamerBase ()
Public Member Functions inherited from TableBase
void clearVec ()
void compareVec (vector< double > other, string op)
void compareXplot (string fname, string plotname, string op)
const vector< double > & data ()
double getOutputValue () const
string getPlotDump () const
unsigned int getVecSize () const
vector< double > getVector () const
double getY (unsigned int index) const
double interpolate (double x, double xmin, double xmax) const
void linearTransform (double scale, double offset)
void loadCSV (string fname, int startLine, int colNum, char separator)
void loadXplot (string fname, string plotname)
void loadXplotRange (string fname, string plotname, unsigned int start, unsigned int end)
double * lookupVec (unsigned int index)
void plainPlot (string file)
void setOutputValue (double val)
void setPlotDump (string v)
void setVecSize (unsigned int num)
void setVector (vector< double > val)
TableBase ()
void xplot (string file, string plotname)
Static Public Member Functions
static void addStringToDoubleVec (vector< double > &res, const string s)
static const Cinfo * initCinfo ()
Static Public Member Functions inherited from StreamerBase
static void writeToCSVFile (const string &filepath, const OpenMode openMode, const vector< double > &data, const vector< string > &columns)
Write data to csv file. See the documentation of writeToOutfile for details.
static void writeToNPYFile (const string &filepath, const OpenMode openmode, const vector< double > &data, const vector< string > &columns)
Write to NPY format. See the documentation of writeToOutfile for more details.
static void writeToOutFile (const string &filepath, const string &format, const OpenMode openmode, const vector< double > &data, const vector< string > &columns)
Write to a output file in given format.
Static Public Member Functions inherited from TableBase
static const Cinfo * initCinfo ()
Private Attributes
bool all_done_ = false
string buffer_
int clientfd_
Clock * clk_ = nullptr
vector< string > columns_
double currTime_
bool isValid_ = true
int numMaxClients_
std::thread processThread_
unsigned int processTickMicroSec
struct sockaddr_in sockAddrTCP_
struct sockaddr_un sockAddrUDS_
int sockfd_
MooseSocketInfo sockInfo_
vector< double > tableDt_
vector< Id > tableIds_
vector< Table * > tables_
vector< unsigned int > tableTick_
double thisDt_
std::chrono::high_resolution_clock::time_point timeStamp_
vector< double > vecToStream_
Additional Inherited Members
Protected Member Functions inherited from TableBase
vector< double > & vec ()
Detailed Description
Definition at line 53 of file SocketStreamer.h.
Constructor & Destructor Documentation
SocketStreamer()
SocketStreamer::SocketStreamer ()
Definition at line 142 of file SocketStreamer.cpp.
                               :
     currTime_(0.0)
    , numMaxClients_(1)
    , sockfd_(-1)
    , clientfd_(-1)
    , sockInfo_( MooseSocketInfo( "file://MOOSE" ) )
{
    clk_ = reinterpret_cast<Clock*>( Id(1).eref().data() );
    // Not all compilers allow initialization during the declaration of class
    // methods.
    columns_.push_back( "time" );               /* First column is time. */
    tables_.resize(0);
    tableIds_.resize(0);
    tableTick_.resize(0);
    tableDt_.resize(0);
}
References clientfd_, clk_, columns_, currTime_, Eref::data(), Id::eref(), Id::Id(), MooseSocketInfo::MooseSocketInfo(), numMaxClients_, sockfd_, sockInfo_, tableDt_, tableIds_, tables_, and tableTick_.
~SocketStreamer()
SocketStreamer::~SocketStreamer ()
Definition at line 167 of file SocketStreamer.cpp.
{
    // Now cleanup the socket as well.
    all_done_ = true;
    if(sockfd_ > 0)
    {
        LOG(moose::debug, "Closing socket " << sockfd_ );
        shutdown(sockfd_, SHUT_RDWR);
        close(sockfd_);
        if( sockInfo_.type == UNIX_DOMAIN_SOCKET )
            ::unlink( sockInfo_.filepath.c_str() );
    }
    if( processThread_.joinable())
        processThread_.join();
    // Close the client as well.
    if( clientfd_ > -1 )
    {
        shutdown(clientfd_, SHUT_RDWR);
        close(clientfd_);
    }
}
References all_done_, clientfd_, moose::debug, MooseSocketInfo::filepath, processThread_, sockfd_, sockInfo_, MooseSocketInfo::type, and UNIX_DOMAIN_SOCKET.
Member Function Documentation
addStringToDoubleVec()
void SocketStreamer::addStringToDoubleVec (vector< double > & res, const string s) static
Definition at line 192 of file SocketStreamer.cpp.
{
    for(char c : s)
        res.push_back((double)c);
}
Referenced by streamData().
addTable()
void SocketStreamer::addTable (ObjId table)
Add a table to streamer.
Parameters
table Id of table.
Definition at line 491 of file SocketStreamer.cpp.
{
    // If this table is not already in the vector, add it.
    for( unsigned int i = 0; i < tableIds_.size(); i++)
        if( table.path() == tableIds_[i].path() )
            return;                             /* Already added. */
    Table* t = reinterpret_cast<Table*>(table.eref().data());
    tableIds_.push_back( table );
    tables_.push_back( t );
    tableTick_.push_back( table.element()->getTick() );
    // NOTE: If user can make sure that names are unique in table, using name is
    // better than using the full path.
    if( t->getColumnName().size() > 0 )
        columns_.push_back( t->getColumnName( ) );
    else
        columns_.push_back( moose::moosePathToUserPath( table.path() ) );
}
References columns_, Eref::data(), ObjId::element(), ObjId::eref(), Table::getColumnName(), Element::getTick(), moose::moosePathToUserPath(), Id::path(), ObjId::path(), tableIds_, tables_, and tableTick_.
Referenced by addTables(), and initCinfo().
addTables()
void SocketStreamer::addTables (vector< ObjId > tables)
Add multiple tables to SocketStreamer.
Parameters
tables
Definition at line 516 of file SocketStreamer.cpp.
{
    if( tables.size() == 0 )
        return;
    for(auto t : tables)
        addTable(t);
}
References addTable().
Referenced by initCinfo().
cleanUp()
void SocketStreamer::cleanUp (void)
configureSocketServer()
void SocketStreamer::configureSocketServer (void)
Definition at line 229 of file SocketStreamer.cpp.
{
    // One can set socket option using setsockopt function. See manual page
    // for details. We are making it 'reusable'.
    int on = 1;
#ifdef SO_REUSEPORT
    if(0 > setsockopt(sockfd_, SOL_SOCKET, SO_REUSEPORT, (const char *)&on, sizeof(on)))
        LOG(moose::warning, "Warn: setsockopt() failed");
#endif
    if(0 > setsockopt(sockfd_, SOL_SOCKET, SO_REUSEADDR, (const char *)&on, sizeof(on)))
        LOG(moose::warning, "Warn: setsockopt() failed");
}
References sockfd_, and moose::warning.
Referenced by initTCPServer(), and initUDSServer().
connect()
void SocketStreamer::connect (void)
Definition at line 389 of file SocketStreamer.cpp.
{
    // If server was invalid then there is no point.
    if( ! isValid_ )
        return;
    struct sockaddr_storage clientAddr;
    socklen_t addrLen = sizeof(clientAddr);
    clientfd_ = ::accept(sockfd_,(struct sockaddr*) &clientAddr, &addrLen);
    assert( clientfd_ );
    char ipstr[INET6_ADDRSTRLEN];
    int port = -1;
    // deal with both IPv4 and IPv6:
    if (clientAddr.ss_family == AF_INET)
    {
        struct sockaddr_in *s = (struct sockaddr_in *)&clientAddr;
        port = ntohs(s->sin_port);
        inet_ntop(AF_INET, &s->sin_addr, ipstr, sizeof ipstr);
    }
    else
    { // AF_INET6
        struct sockaddr_in6 *s = (struct sockaddr_in6 *)&clientAddr;
        port = ntohs(s->sin6_port);
        inet_ntop(AF_INET6, &s->sin6_addr, ipstr, sizeof ipstr);
    }
    LOG(moose::info, "Connected to " << ipstr << ':' << port);
    return;
}
References clientfd_, moose::info, isValid_, and sockfd_.
Referenced by reinit().
dataToStream()
void SocketStreamer::dataToStream (map< string, vector< double > > & data)
@Synopsis Convert data to JSON.
@Returns JSON representation.
Definition at line 323 of file SocketStreamer.cpp.
{
    for( unsigned int i = 0; i < tables_.size(); i++)
    {
        vector<double> vec;
        tables_[i]->collectData(vec, true, false);
        if( ! vec.empty() )
            data[columns_[i+1]] = vec;
    }
}
References Table::collectData(), columns_, and tables_.
Referenced by streamData().
enoughDataToStream()
bool SocketStreamer::enoughDataToStream (unsigned int minsize = 10)
Definition at line 381 of file SocketStreamer.cpp.
{
    for( unsigned int i = 0; i < tables_.size(); i++)
        if(tables_[i]->getVector().size() >= minsize)
            return true;
    return false;
}
References TableBase::getVector(), and tables_.
getAddress()
string SocketStreamer::getAddress (void) const
Definition at line 586 of file SocketStreamer.cpp.
{
    return sockInfo_.address;
}
References MooseSocketInfo::address, and sockInfo_.
Referenced by initCinfo().
getFormat()
string SocketStreamer::getFormat (void) const
getNumTables()
unsigned int SocketStreamer::getNumTables (void) const
Get the number of tables handled by SocketStreamer.
Returns
Number of tables.
Definition at line 565 of file SocketStreamer.cpp.
{
    return tables_.size();
}
References tables_.
Referenced by initCinfo().
getPort()
unsigned int SocketStreamer::getPort (void) const
Definition at line 576 of file SocketStreamer.cpp.
{
    return sockInfo_.port;
}
References MooseSocketInfo::port, and sockInfo_.
Referenced by initCinfo().
initCinfo()
const Cinfo * SocketStreamer::initCinfo () static
Definition at line 33 of file SocketStreamer.cpp.
{
    /*-----------------------------------------------------------------------------
     * Finfos
     *-----------------------------------------------------------------------------*/
    static ValueFinfo< SocketStreamer, unsigned int > port(
        "port"
        , "Set port number for streaming. Valid only of TCP socket."
        , &SocketStreamer::setPort
        , &SocketStreamer::getPort
    );
    static ValueFinfo< SocketStreamer, string > address(
        "address"
        , "Set adresss for socket e.g. http://localhost:31416 (host:port for TCP SOCKET) "
        ", or file:///tmp/MOOSE_SOCK for UNIX domain socket."
        , &SocketStreamer::setAddress
        , &SocketStreamer::getAddress
    );
    static ReadOnlyValueFinfo< SocketStreamer, unsigned int > numTables (
        "numTables"
        , "Number of Tables handled by SocketStreamer "
        , &SocketStreamer::getNumTables
    );
    /*-----------------------------------------------------------------------------
     *
     *-----------------------------------------------------------------------------*/
    static DestFinfo process(
        "process"
        , "Handle process call"
        , new ProcOpFunc<SocketStreamer>(&SocketStreamer::process)
    );
    static DestFinfo reinit(
        "reinit"
        , "Handles reinit call"
        , new ProcOpFunc<SocketStreamer> (&SocketStreamer::reinit)
    );
    static DestFinfo addTable(
        "addTable"
        , "Add a table to SocketStreamer"
        , new OpFunc1<SocketStreamer, ObjId>(&SocketStreamer::addTable)
    );
    static DestFinfo addTables(
        "addTables"
        , "Add many tables to SocketStreamer"
        , new OpFunc1<SocketStreamer, vector<ObjId> >(&SocketStreamer::addTables)
    );
    static DestFinfo removeTable(
        "removeTable"
        , "Remove a table from SocketStreamer"
        , new OpFunc1<SocketStreamer, ObjId>(&SocketStreamer::removeTable)
    );
    static DestFinfo removeTables(
        "removeTables"
        , "Remove tables -- if found -- from SocketStreamer"
        , new OpFunc1<SocketStreamer, vector<ObjId>>(&SocketStreamer::removeTables)
    );
    /*-----------------------------------------------------------------------------
     *  ShareMsg definitions.
     *-----------------------------------------------------------------------------*/
    static Finfo* procShared[] =
    {
        &process, &reinit, &addTable, &addTables, &removeTable, &removeTables
    };
    static SharedFinfo proc(
        "proc",
        "Shared message for process and reinit",
        procShared, sizeof( procShared ) / sizeof( const Finfo* )
    );
    static Finfo * socketStreamFinfo[] =
    {
        &port, &address, &proc, &numTables
    };
    static string doc[] =
    {
        "Name", "SocketStreamer",
        "Author", "Dilawar Singh (@dilawar, github), 2018",
        "Description", "SocketStreamer: Stream moose.Table data to a socket.\n"
    };
    static Dinfo< SocketStreamer > dinfo;
    static Cinfo tableStreamCinfo(
        "SocketStreamer",
        TableBase::initCinfo(),
        socketStreamFinfo,
        sizeof( socketStreamFinfo )/sizeof(Finfo *),
        &dinfo,
        doc,
        sizeof(doc) / sizeof(string)
    );
    return &tableStreamCinfo;
}
References addTable(), addTables(), Cinfo::Cinfo(), DestFinfo::DestFinfo(), getAddress(), getNumTables(), getPort(), TableBase::initCinfo(), OpFunc1< T, A >::OpFunc1(), process(), ProcOpFunc< T >::ProcOpFunc(), ReadOnlyValueFinfo< T, F >::ReadOnlyValueFinfo(), reinit(), removeTable(), removeTables(), setAddress(), setPort(), SharedFinfo::SharedFinfo(), and ValueFinfo< T, F >::ValueFinfo().
initServer()
void SocketStreamer::initServer (void)
Definition at line 215 of file SocketStreamer.cpp.
{
    if( sockInfo_.type == UNIX_DOMAIN_SOCKET )
        initUDSServer();
    else
        initTCPServer();
    LOG(moose::info,  "Successfully initialized streamer socket: " << sockfd_);
    //  Listen for incoming clients. This function does nothing if connection is
    //  already made.
    listenToClients(1);
}
References moose::info, initTCPServer(), initUDSServer(), listenToClients(), sockfd_, sockInfo_, MooseSocketInfo::type, and UNIX_DOMAIN_SOCKET.
Referenced by reinit().
initTCPServer()
void SocketStreamer::initTCPServer (void)
Definition at line 285 of file SocketStreamer.cpp.
{
    // Create a blocking socket.
    LOG( moose::debug, "Creating TCP socket on port: "  << sockInfo_.port );
    sockfd_ = socket(AF_INET, SOCK_STREAM, 0);
    if( 0 > sockfd_ )
    {
        perror("socket");
        isValid_ = false;
        return;
    }
    configureSocketServer();
    bzero((char*) &sockAddrTCP_, sizeof(sockAddrTCP_));
    sockAddrTCP_.sin_family = AF_INET;
    sockAddrTCP_.sin_addr.s_addr = INADDR_ANY;
    sockAddrTCP_.sin_port = htons( sockInfo_.port );
    // Bind. Make sure bind is not std::bind
    if(0 > ::bind(sockfd_, (struct sockaddr*) &sockAddrTCP_, sizeof(sockAddrTCP_)))
    {
        isValid_ = false;
        LOG(moose::warning, "Warn: Failed to create server at "
                << sockInfo_.host << ":" << sockInfo_.port
                << ". File descriptor: " << sockfd_
                << ". Erorr: " << strerror(errno)
           );
        return;
    }
}
References configureSocketServer(), moose::debug, MooseSocketInfo::host, isValid_, MooseSocketInfo::port, sockAddrTCP_, sockfd_, sockInfo_, and moose::warning.
Referenced by initServer().
initUDSServer()
void SocketStreamer::initUDSServer (void)
Definition at line 244 of file SocketStreamer.cpp.
{
    // PF_UNIX means that sockets are local.
    sockfd_ = socket(PF_UNIX, SOCK_STREAM, 0);
    if( ! sockfd_)
    {
        isValid_ = false;
        perror( "Socket" );
    }
    if( sockfd_ > 0 )
    {
        bzero(&sockAddrUDS_, sizeof(sockAddrUDS_));
        sockAddrUDS_.sun_family = AF_UNIX;
        strncpy(sockAddrUDS_.sun_path, sockInfo_.filepath.c_str(), sizeof(sockAddrUDS_.sun_path)-1);
        configureSocketServer();
        // Bind. Make sure bind is not std::bind
        if(0 > ::bind(sockfd_, (struct sockaddr*) &sockAddrUDS_, sizeof(sockAddrUDS_)))
        {
            isValid_ = false;
            LOG(moose::warning, "Warn: Failed to create socket at " << sockInfo_.filepath
                << ". File descriptor: " << sockfd_
                << ". Erorr: " << strerror(errno)
               );
        }
        if(access(sockInfo_.filepath.c_str(), F_OK) != 0)
        {
            LOG( moose::warning, "No file " << sockInfo_.filepath << " exists." );
            isValid_ = false;
        }
    }
    if( (! isValid_) || (sockfd_ < 0) )
    {
        LOG( moose::warning, "Failed to create socket : " << sockInfo_ );
        ::unlink( sockInfo_.filepath.c_str() );
    }
}
References configureSocketServer(), MooseSocketInfo::filepath, isValid_, sockAddrUDS_, sockfd_, sockInfo_, and moose::warning.
Referenced by initServer().
listenToClients()
void SocketStreamer::listenToClients (unsigned int numMaxClients)
@Synopsis Connect to a client. If already connected to one, then do not make any more connections.
Definition at line 204 of file SocketStreamer.cpp.
{
    assert(0 < sockfd_ );
    assert( numMaxClients > 0 );
    numMaxClients_ = numMaxClients;
    if(-1 == listen(sockfd_, numMaxClients_))
        LOG(moose::error, "Failed listen() on socket " << sockfd_
                << ". Error was: " << strerror(errno) );
}
References moose::error, numMaxClients_, and sockfd_.
Referenced by initServer().
minMaxNumberOfElemementsInTables()
pair< unsigned int, unsigned int > SocketStreamer::minMaxNumberOfElemementsInTables ()
operator=()
SocketStreamer & SocketStreamer::operator= (const SocketStreamer & st)
Definition at line 160 of file SocketStreamer.cpp.
{
    return *this;
}
process()
void SocketStreamer::process (const Eref & e, ProcPtr p)
This function is called at its clock tick.
Dest functions. The process function called by scheduler on every tick
Parameters
e
p
Definition at line 478 of file SocketStreamer.cpp.
{
    // processTickMicroSec = std::chrono::duration_cast<std::chrono::microseconds>(
            // std::chrono::high_resolution_clock::now() - timeStamp_).count();
    // timeStamp_ = std::chrono::high_resolution_clock::now();
    stream();
}
References stream().
Referenced by initCinfo().
reinit()
void SocketStreamer::reinit (const Eref & e, ProcPtr p)
Reinit. We make sure it is non-blocking.
The reinit function called by scheduler for the reset
Parameters
e
p
Definition at line 440 of file SocketStreamer.cpp.
{
    if( tables_.size() == 0 )
    {
        moose::showWarn( "No table found. Disabling SocketStreamer.\nDid you forget"
                " to call addTables() on SocketStreamer object. " + e.objId().path()
                );
        e.element()->setTick( -2 );             /* Disable process */
        return;
    }
    thisDt_ = clk_->getTickDt( e.element()->getTick() );
    // Push each table dt_ into vector of dt
    for( unsigned int i = 0; i < tables_.size(); i++)
    {
        Id tId = tableIds_[i];
        int tickNum = tId.element()->getTick();
        tableDt_.push_back( clk_->getTickDt( tickNum ) );
    }
    // This should only be called once.
    initServer();
    // Launch a thread in background which monitors the any client trying to
    // make connection to server.
    processThread_ = std::thread(&SocketStreamer::connect, this);
    // NOw introduce some delay.
    timeStamp_ = std::chrono::high_resolution_clock::now();
}
References clk_, connect(), Eref::element(), Id::element(), Element::getTick(), Clock::getTickDt(), initServer(), Eref::objId(), ObjId::path(), processThread_, Element::setTick(), moose::showWarn(), tableDt_, tableIds_, tables_, thisDt_, and timeStamp_.
Referenced by initCinfo().
removeTable()
void SocketStreamer::removeTable (ObjId table)
Remove a table from SocketStreamer.
Parameters
table. Id of table.
Definition at line 530 of file SocketStreamer.cpp.
{
    int matchIndex = -1;
    for (unsigned int i = 0; i < tableIds_.size(); i++)
    {
        if( table.path() == tableIds_[i].path() )
        {
            matchIndex = i;
            break;
        }
    }
    if( matchIndex > -1 )
    {
        tableIds_.erase( tableIds_.begin() + matchIndex );
        tables_.erase( tables_.begin() + matchIndex );
        columns_.erase( columns_.begin() + matchIndex );
    }
}
References columns_, Id::path(), ObjId::path(), tableIds_, and tables_.
Referenced by initCinfo(), and removeTables().
removeTables()
void SocketStreamer::removeTables (vector< ObjId > tables)
Remove multiple tables – if found – from SocketStreamer.
Parameters
tables
Definition at line 555 of file SocketStreamer.cpp.
{
    for(auto &t: tables) removeTable(t);
}
References removeTable().
Referenced by initCinfo().
setAddress()
void SocketStreamer::setAddress (const string addr)
Definition at line 581 of file SocketStreamer.cpp.
{
    sockInfo_.setAddress(addr);
}
References MooseSocketInfo::setAddress(), and sockInfo_.
Referenced by initCinfo().
setFormat()
void SocketStreamer::setFormat (string format)
setPort()
void SocketStreamer::setPort (const unsigned int port)
Definition at line 571 of file SocketStreamer.cpp.
{
    sockInfo_.port = port;
}
References MooseSocketInfo::port, and sockInfo_.
Referenced by initCinfo().
stream()
void SocketStreamer::stream (void)
Definition at line 420 of file SocketStreamer.cpp.
{
    if(clientfd_ > 0)
    {
        if( EPIPE == streamData() )
        {
            LOG( moose::warning, "Broken pipe. Couldn't stream." );
            return;
        }
    }
    else
        LOG( moose::warning, "No client." );
}
References clientfd_, streamData(), and moose::warning.
Referenced by process().
streamData()
int SocketStreamer::streamData ()
@Synopsis Stream data over socket.
@Returns True of success, false otherwise. It is callee job to clean up data_ on a successful return from this function.
Definition at line 342 of file SocketStreamer.cpp.
{
    map<string, vector<double>> data;
    dataToStream(data);
    if(data.empty())
    {
        LOG(moose::debug, "No data in tables.");
        return 0;
    }
    // Construct a void* array to send over the socket. Serialize the data.
    // e.g. H 10 / a / t a b l e / a V 4 0.1 0.2 0.3 0.2
    // H => Header start (chars)
    // V => Value starts (double)
    for(auto v: data)
    {
        // First header.
        vecToStream_.push_back((double)'H');
        vecToStream_.push_back(v.first.size());
        addStringToDoubleVec(vecToStream_, v.first);
        // Now data.
        vecToStream_.push_back((double)'V');
        vecToStream_.push_back(v.second.size());
        vecToStream_.insert(vecToStream_.end(), v.second.begin(), v.second.end());
    }
    unsigned int dtypeSize = sizeof(double);
    int sent = send(clientfd_, (void*) &vecToStream_[0], dtypeSize*vecToStream_.size(), MSG_MORE);
    LOG(moose::debug, "Sent " << sent << " bytes." );
    if( sent < 0 )
        return errno;
    vecToStream_.erase(vecToStream_.begin(), vecToStream_.begin()+(sent/dtypeSize));
    return 0;
}
References addStringToDoubleVec(), clientfd_, dataToStream(), moose::debug, and vecToStream_.
Referenced by stream().
Member Data Documentation
all_done_
bool SocketStreamer::all_done_ = false private
Definition at line 147 of file SocketStreamer.h.
Referenced by ~SocketStreamer().
buffer_
string SocketStreamer::buffer_ private
Definition at line 150 of file SocketStreamer.h.
clientfd_
int SocketStreamer::clientfd_ private
Definition at line 140 of file SocketStreamer.h.
Referenced by connect(), SocketStreamer(), stream(), streamData(), and ~SocketStreamer().
clk_
Clock* SocketStreamer::clk_ = nullptr private
Definition at line 155 of file SocketStreamer.h.
Referenced by reinit(), and SocketStreamer().
columns_
vector<string> SocketStreamer::columns_ private
Definition at line 135 of file SocketStreamer.h.
Referenced by addTable(), dataToStream(), removeTable(), and SocketStreamer().
currTime_
double SocketStreamer::currTime_ private
Definition at line 130 of file SocketStreamer.h.
Referenced by SocketStreamer().
isValid_
bool SocketStreamer::isValid_ = true private
Definition at line 148 of file SocketStreamer.h.
Referenced by connect(), initTCPServer(), and initUDSServer().
numMaxClients_
int SocketStreamer::numMaxClients_ private
Definition at line 138 of file SocketStreamer.h.
Referenced by listenToClients(), and SocketStreamer().
processThread_
std::thread SocketStreamer::processThread_ private
Definition at line 149 of file SocketStreamer.h.
Referenced by reinit(), and ~SocketStreamer().
processTickMicroSec
unsigned int SocketStreamer::processTickMicroSec private
Definition at line 161 of file SocketStreamer.h.
sockAddrTCP_
struct sockaddr_in SocketStreamer::sockAddrTCP_ private
Definition at line 143 of file SocketStreamer.h.
Referenced by initTCPServer().
sockAddrUDS_
struct sockaddr_un SocketStreamer::sockAddrUDS_ private
Definition at line 144 of file SocketStreamer.h.
Referenced by initUDSServer().
sockfd_
int SocketStreamer::sockfd_ private
Definition at line 139 of file SocketStreamer.h.
Referenced by configureSocketServer(), connect(), initServer(), initTCPServer(), initUDSServer(), listenToClients(), SocketStreamer(), and ~SocketStreamer().
sockInfo_
MooseSocketInfo SocketStreamer::sockInfo_ private
Definition at line 158 of file SocketStreamer.h.
Referenced by getAddress(), getPort(), initServer(), initTCPServer(), initUDSServer(), setAddress(), setPort(), SocketStreamer(), and ~SocketStreamer().
tableDt_
vector<double> SocketStreamer::tableDt_ private
Definition at line 128 of file SocketStreamer.h.
Referenced by reinit(), and SocketStreamer().
tableIds_
vector<Id> SocketStreamer::tableIds_ private
Definition at line 133 of file SocketStreamer.h.
Referenced by addTable(), reinit(), removeTable(), and SocketStreamer().
tables_
vector<Table*> SocketStreamer::tables_ private
Definition at line 134 of file SocketStreamer.h.
Referenced by addTable(), dataToStream(), enoughDataToStream(), getNumTables(), reinit(), removeTable(), and SocketStreamer().
tableTick_
vector<unsigned int> SocketStreamer::tableTick_ private
Definition at line 129 of file SocketStreamer.h.
Referenced by addTable(), and SocketStreamer().
thisDt_
double SocketStreamer::thisDt_ private
Definition at line 152 of file SocketStreamer.h.
Referenced by reinit().
timeStamp_
std::chrono::high_resolution_clock::time_point SocketStreamer::timeStamp_ private
Definition at line 162 of file SocketStreamer.h.
Referenced by reinit().
vecToStream_
vector<double> SocketStreamer::vecToStream_ private
Definition at line 151 of file SocketStreamer.h.
Referenced by streamData().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/builtins/SocketStreamer.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/builtins/SocketStreamer.cpp