MOOSE - Multiscale Object Oriented Simulation Environment: Eref Class Reference
Eref Class Reference
#include <Eref.h>
Public Member Functions
char * data () const
unsigned int dataIndex () const
Element * element () const
Eref ()
Eref (const Eref &other)
Eref (Element *e, unsigned int index, unsigned int field=0)
unsigned int fieldIndex () const
unsigned int getNode () const
Id id () const
bool isDataHere () const
const vector< MsgDigest > & msgDigest (unsigned int bindIndex) const
ObjId objId () const
Private Attributes
Element * e_
unsigned int f_
unsigned int i_
Friends
ostream & operator<< (ostream &s, const Eref &e)
Detailed Description
Definition at line 13 of file Eref.h.
Constructor & Destructor Documentation
Eref() [1/3]
Eref::Eref ()
Definition at line 13 of file Eref.cpp.
            : e_( 0 ), i_( 0 ), f_( 0 )
{
    ;
}
References e_, f_, and i_.
Eref() [2/3]
Eref::Eref (const Eref & other)
Definition at line 19 of file Eref.cpp.
            : e_( other.e_ ), i_( other.i_ ), f_( other.f_ )
{
    ;
}
References e_, f_, and i_.
Referenced by SpikeGenStruct::SpikeGenStruct().
Eref() [3/3]
Eref::Eref (Element * e, unsigned int index, unsigned int field = 0)
Definition at line 25 of file Eref.cpp.
            : e_( e ), i_( index ), f_( field )
{
    ;
}
References e_, f_, and i_.
Referenced by Neutral::buildTree(), checkArg1(), OneToAllMsg::copy(), SingleMsg::copy(), HopFunc1< A >::dataOpVec(), Neutral::destroy(), Shell::doCopy(), Id::eref(), ObjId::eref(), fillErefsFromMatrix(), DiagonalMsg::firstTgt(), OneToAllMsg::firstTgt(), OneToOneDataIndexMsg::firstTgt(), OneToOneMsg::firstTgt(), SingleMsg::firstTgt(), SparseMsg::firstTgt(), Element::getInputsWithTgtIndex(), GetHopFunc< A >::getLocalFieldVec(), GetHopFunc< A >::getLocalVec(), Element::getMsgTargets(), getReactantVols(), LookupField< L, A >::getVec(), innerGetVec(), HopFunc1< A >::localFieldOpVec(), HopFunc1< A >::localOpVec(), HopFunc2< A1, A2 >::opVec(), OpFunc1Base< A >::opVecBuffer(), OpFunc2Base< A1, A2 >::opVecBuffer(), FieldElementFinfoBase::postCreationFunc(), printGrid(), Element::putOffNodeTargetsInDigest(), SrcFinfo0::send(), SrcFinfo2< T1, T2 >::send(), SrcFinfo3< T1, T2, T3 >::send(), SrcFinfo4< T1, T2, T3, T4 >::send(), SrcFinfo5< T1, T2, T3, T4, T5 >::send(), SrcFinfo6< T1, T2, T3, T4, T5, T6 >::send(), SrcFinfo1< T >::send(), SrcFinfo2< T1, T2 >::sendTo(), SrcFinfo1< T >::sendTo(), SrcFinfo1< T >::sendVec(), DiagonalMsg::sources(), OneToAllMsg::sources(), OneToOneDataIndexMsg::sources(), OneToOneMsg::sources(), SingleMsg::sources(), DiagonalMsg::targets(), OneToAllMsg::targets(), OneToOneDataIndexMsg::targets(), OneToOneMsg::targets(), SingleMsg::targets(), testArith(), testCopyFieldElement(), testCreateMsg(), testFilterOffNodeTargets(), testMsgField(), testSendMsg(), testSetGetVec(), testStrSet(), testTreeTraversal(), CaConcBase::zombify(), moose::CompartmentBase::zombify(), and HHChannelBase::zombify().
Member Function Documentation
data()
char * Eref::data () const
Returns data entry.
Definition at line 47 of file Eref.cpp.
{
    assert( isDataHere() );
    return e_->data( e_->rawIndex( i_ ), f_ );
}
References Element::data(), e_, f_, i_, isDataHere(), and Element::rawIndex().
Referenced by ReadCell::addChannelMessage(), addSpine(), SocketStreamer::addTable(), Streamer::addTable(), VoxelPools::advance(), benchmarkMsg(), ReadSwc::build(), Neuron::buildElist(), buildFromProto(), Dsolve::calcJunction(), Dsolve::calcLocalChan(), Cell::Cell(), checkArg1(), SteadyState::classifyState(), Shell::cleanSimulation(), Shell::destroy(), ReadCspace::expandEnzyme(), ReadCspace::expandReaction(), HSolveUtils::gates(), getEpFuncData(), Neuron::getExprElist(), Neuron::getExprVal(), VoxelPools::getMethod(), pymoose::getShellPtr(), Id::Id(), MarkovSolverBase::init(), init(), pymoose::initShell(), isDoingReinit(), Shell::isRunning(), Shell::launchParser(), makeCompt(), makeCompt(), ReadCspace::makeMolecule(), ReadCspace::makePlots(), makeReacTest(), makeStandardElements(), Dsolve::mapChansBetweenDsolves(), Dsolve::mapDiffPoolsBetweenDsolves(), mapVoxelsBetweenMeshes(), Dsolve::mapXfersBetweenDsolves(), ObjId::ObjId(), EpFunc0< T >::op(), OpFunc0< T >::op(), EpFunc1< T, A >::op(), OpFunc1< T, A >::op(), EpFunc2< T, A1, A2 >::op(), OpFunc2< T, A1, A2 >::op(), EpFunc3< T, A1, A2, A3 >::op(), OpFunc3< T, A1, A2, A3 >::op(), EpFunc4< T, A1, A2, A3, A4 >::op(), OpFunc4< T, A1, A2, A3, A4 >::op(), EpFunc5< T, A1, A2, A3, A4, A5 >::op(), OpFunc5< T, A1, A2, A3, A4, A5 >::op(), EpFunc6< T, A1, A2, A3, A4, A5, A6 >::op(), OpFunc6< T, A1, A2, A3, A4, A5, A6 >::op(), HSolveUtils::rates(), ReadCell::ReadCell(), ReadKkit::ReadKkit(), Streamer::reinit(), Table::reinit(), Dsolve::reinit(), SpikeGenStruct::reinit(), Clock::reportClock(), GetOpFunc< T, A >::returnOp(), GetEpFunc1< T, L, A >::returnOp(), GetOpFunc1< T, L, A >::returnOp(), SpikeGenStruct::send(), Gsolve::setDsolve(), Ksolve::setDsolve(), Stoich::setDsolve(), Stoich::setElist(), MarkovRateTable::setInt2dChildTable(), Stoich::setKsolve(), Reac::setSolver(), Dsolve::setStoich(), SteadyState::setStoich(), Gsolve::setStoich(), Ksolve::setStoich(), Cell::setupSolver(), MarkovRateTable::setVtChildTable(), SocketStreamer::SocketStreamer(), testAssortedMsg(), testBuildStoich(), testCalcJunction(), testCellDiffn(), testChildren(), testClockMessaging(), testCopy(), testCopyFieldElement(), testCylDiffn(), testCylDiffnWithStoich(), testDescendant(), testFibonacci(), testFilterOffNodeTargets(), testFindModelParent(), testGetMsg(), testInterNodeOps(), testMMenz(), testMMenzProcess(), testMove(), testMpiFibonacci(), testMsgElementListing(), testMsgField(), testObjIdToAndFromPath(), testPoolVolumeScaling(), testReacVolumeScaling(), testReadKkit(), ReadCspace::testReadModel(), testReMesh(), testRunGsolve(), testRunKsolve(), testRunKsolveWithLSODA(), testSendSpike(), testSetupReac(), testSharedMsg(), testShellAddMsg(), testShellParserCreateDelete(), testShellParserQuit(), testShellParserStart(), testShellSetGet(), testSmallCellDiffn(), testStats(), testStrSet(), testSyncSynapseSize(), testTable(), testTaperingCylDiffn(), testTreeTraversal(), testTwoReacGetNeighbors(), testVolScaling(), testWildcard(), verifyKids(), ZombieCaConc::vSetSolver(), ZombieCompartment::vSetSolver(), ZombieHHChannel::vSetSolver(), CaConcBase::zombify(), moose::CompartmentBase::zombify(), and HHChannelBase::zombify().
dataIndex()
unsigned int Eref::dataIndex () const inline
Returns data index, for now typecast to unsigned int.
Definition at line 38 of file Eref.h.
    {
        return i_;
    }
References i_.
Referenced by Synapse::addSpike(), Neutral::child(), Neutral::children(), HopFunc1< A >::dataOpVec(), filterOffNodeTargets(), DiagonalMsg::firstTgt(), OneToOneDataIndexMsg::firstTgt(), OneToOneMsg::firstTgt(), SparseMsg::firstTgt(), Dsolve::getConcInit(), PoolBase::getCoords(), Neutral::getIndex(), Element::getInputsWithTgtIndex(), GetHopFunc< A >::getLocalFieldVec(), PoolBase::getMidPoint(), Neutral::getMsgDestFunctions(), Neutral::getMsgDests(), Element::getMsgTargets(), Dsolve::getN(), Neutral::getNumField(), Neuron::getSpineFromCompartment(), Dsolve::getVolumeOfPool(), Gsolve::getVoxelIndex(), Ksolve::getVoxelIndex(), innerGetVec(), HopFunc1< A >::localFieldOpVec(), lookupVolumeFromMesh(), OneToAllMsg::OneToAllMsg(), OneToOneMsg::OneToOneMsg(), OpFunc1Base< A >::opVecBuffer(), Element::printMsgDigest(), IntFire::process(), MeshEntry::reinit(), Adaptor::reinit(), SrcFinfo0::send(), SrcFinfo2< T1, T2 >::send(), SrcFinfo3< T1, T2, T3 >::send(), SrcFinfo4< T1, T2, T3, T4 >::send(), SrcFinfo5< T1, T2, T3, T4, T5 >::send(), SrcFinfo6< T1, T2, T3, T4, T5, T6 >::send(), SrcFinfo1< T >::send(), SrcFinfo2< T1, T2 >::sendTo(), SrcFinfo1< T >::sendTo(), SrcFinfo1< T >::sendVec(), Dsolve::setConcInit(), ChemCompt::setEntireVolume(), Dsolve::setN(), Neutral::setNumField(), SingleMsg::SingleMsg(), and testSendMsg().
element()
Element * Eref::element () const inline
Returns Element part
Definition at line 30 of file Eref.h.
    {
        return e_;
    }
References e_.
Referenced by Clock::buildTicks(), Neutral::buildTree(), Neutral::child(), Neutral::children(), convertConcToNumRateUsingMesh(), convertConcToNumRateUsingVol(), HopFunc1< A >::dataOpVec(), Neutral::destroy(), PostMaster::dispatchSetBuf(), filterOffNodeTargets(), DiagonalMsg::firstTgt(), OneToAllMsg::firstTgt(), OneToOneDataIndexMsg::firstTgt(), OneToOneMsg::firstTgt(), SingleMsg::firstTgt(), SparseMsg::firstTgt(), Neutral::getClass(), Neutral::getDestFields(), Neutral::getDt(), Neutral::getIncomingMsgs(), PoolBase::getIsBuffered(), GetHopFunc< A >::getLocalFieldVec(), Neutral::getMsgDestFunctions(), Neutral::getMsgDests(), Element::getMsgTargets(), GetHopFunc< A >::getMultiNodeVec(), Neutral::getName(), Neutral::getNeighbors(), Neutral::getNumData(), Neutral::getNumField(), EnzBase::getNumPrd(), Reac::getNumPrd(), EnzBase::getNumSub(), Reac::getNumSub(), Neutral::getOutgoingMsgs(), getReactantVols(), Neutral::getSourceFields(), Neutral::getTick(), Neutral::getValueFields(), innerGetVec(), Neutral::isA(), Neutral::isDescendant(), HopFunc1< A >::localFieldOpVec(), localGet(), OneToAllMsg::OneToAllMsg(), OneToOneDataIndexMsg::OneToOneDataIndexMsg(), OneToOneMsg::OneToOneMsg(), GetHopFunc< A >::opGetVec(), HopFunc2< A1, A2 >::opVec(), HopFunc1< A >::opVec(), OpFunc1Base< A >::opVecBuffer(), OpFunc2Base< A1, A2 >::opVecBuffer(), Neutral::path(), Arith::process(), moose::VClamp::reinit(), SocketStreamer::reinit(), Streamer::reinit(), Table::reinit(), Adaptor::reinit(), SrcFinfo0::send(), SrcFinfo2< T1, T2 >::send(), SrcFinfo3< T1, T2, T3 >::send(), SrcFinfo4< T1, T2, T3, T4 >::send(), SrcFinfo5< T1, T2, T3, T4, T5 >::send(), SrcFinfo6< T1, T2, T3, T4, T5, T6 >::send(), SrcFinfo1< T >::send(), SrcFinfo2< T1, T2 >::sendTo(), SrcFinfo1< T >::sendTo(), SrcFinfo1< T >::sendVec(), Gsolve::setConcInit(), ChemCompt::setEntireVolume(), PoolBase::setIsBuffered(), Gsolve::setN(), Neutral::setName(), Neutral::setNumData(), Neutral::setNumField(), Enz::setSolver(), MMenz::setSolver(), Reac::setSolver(), Neutral::setTick(), SingleMsg::SingleMsg(), testCreateMsg(), testFibonacci(), testMsgField(), testSendMsg(), testShellAddMsg(), NeuroMesh::transmitSpineInfo(), HSolve::unzombify(), HHChannel::vReinit(), HHChannel2D::vReinit(), HHChannelF::vReinit(), HHChannelF2D::vReinit(), and HSolve::zombify().
fieldIndex()
unsigned int Eref::fieldIndex () const inline
Returns field index, for now typecast to unsigned int. This is really an extra bit of baggage used here not for immediate lookup, but to pass to EpFuncs that know how to use this for lookup.
Definition at line 49 of file Eref.h.
    {
        return f_;
    }
References f_.
Referenced by Synapse::addSpike(), PostMaster::addToSendBuf(), MeshEntry::getCoordinates(), MeshEntry::getDiffusionArea(), MeshEntry::getDiffusionScaling(), MeshEntry::getDimensions(), Neutral::getFieldIndex(), Spine::getHead(), Spine::getHeadDiameter(), Spine::getHeadLength(), Element::getInputsWithTgtIndex(), MeshEntry::getMeshType(), MeshEntry::getNeighbors(), Spine::getShaft(), Spine::getShaftDiameter(), Spine::getShaftLength(), Synapse::getTopSpike(), MeshEntry::getVolume(), Neutral::path(), Element::printMsgDigest(), Spine::setHeadDiameter(), Spine::setHeadLength(), Spine::setHeadVolume(), Spine::setShaftDiameter(), Spine::setShaftLength(), and SingleMsg::SingleMsg().
getNode()
unsigned int Eref::getNode () const
Returns node upon which specified data entry resides . If this is a GlobalElement then it returns the local node.
Definition at line 58 of file Eref.cpp.
{
    return e_->getNode( i_ );
}
References e_, Element::getNode(), and i_.
Referenced by PostMaster::dispatchSetBuf(), filterOffNodeTargets(), HopFunc1< A >::localFieldOpVec(), GetHopFunc< A >::opGetVec(), HopFunc1< A >::opVec(), PostMaster::remoteFieldGetVec(), and testFilterOffNodeTargets().
id()
Id Eref::id () const
Returns the Id corresponding to the Eref. Loses information.
Definition at line 68 of file Eref.cpp.
{
    return e_->id();
}
References e_, and Element::id().
Referenced by Dsolve::buildMeshJunctions(), Neuron::buildSegmentTree(), Neutral::children(), Dsolve::convertIdToPoolIndex(), HHChannel::destroyGate(), HHChannel2D::destroyGate(), HHChannelF::destroyGate(), HHChannelF2D::destroyGate(), EnzBase::getCompartment(), PoolBase::getCompartment(), Reac::getCompartment(), PoolBase::getCoords(), Neutral::getId(), PoolBase::getMidPoint(), Neutral::getMsgDestFunctions(), Neutral::getMsgDests(), Element::getMsgTargets(), Neutral::getNeighbors(), Gsolve::getPoolIndex(), Ksolve::getPoolIndex(), Stoich::getR1(), Stoich::getR1offset1(), Stoich::getR1offset2(), Stoich::getR2(), Stoich::getReacNumKf(), Neuron::getSpineFromCompartment(), PsdMesh::handlePsdList(), SpineMesh::handleSpineList(), lookupVolumeFromMesh(), Ksolve::notifyAddPool(), Ksolve::notifyRemovePool(), Streamer::reinit(), Table::reinit(), Cell::reinit(), HHGateF::setAlpha(), HHGate::setAlpha(), HHGate::setAlphaExpr(), HHGateF::setBeta(), HHGate::setBeta(), HHGate::setBetaExpr(), HHGate::setDivs(), Stoich::setElist(), Stoich::setEnzK1(), Stoich::setEnzK2(), Stoich::setEnzK3(), Stoich::setFunctionExpr(), HHGateF::setInf(), HHGate::setInfExpr(), HHGate::setMax(), HHGate::setMin(), HHGate::setMinfinity(), Stoich::setMMenzKcat(), Stoich::setMMenzKm(), Neutral::setName(), Stoich::setReacKb(), Stoich::setReacKf(), Enz::setSolver(), MMenz::setSolver(), Reac::setSolver(), HHGate::setTableA(), HHGate::setTableB(), HHGateF::setTau(), HHGate::setTau(), HHGate::setTauExpr(), HHGate::setupAlpha(), HHGate::setupGate(), HHGate::setupTau(), HHGate::setUseInterpolation(), HHChannel::vCreateGate(), HHChannel2D::vCreateGate(), HHChannelF::vCreateGate(), HHChannelF2D::vCreateGate(), ZombieCaConc::vCurrent(), ZombieCaConc::vGetCa(), ZombieCaConc::vGetCaBasal(), ZombieCaConc::vGetCeiling(), ZombieCompartment::vGetCm(), ZombieHHChannel::vGetEk(), ZombieCompartment::vGetEm(), ZombieCaConc::vGetFloor(), ZombieHHChannel::vGetGbar(), ZombieHHChannel::vGetGk(), ZombieHHChannel::vGetIk(), ZombieCompartment::vGetIm(), ZombieCompartment::vGetInitVm(), ZombieCompartment::vGetInject(), ZombieHHChannel::vGetInstant(), ZombieCompartment::vGetRa(), ZombieCompartment::vGetRm(), ZombieCompartment::vGetVm(), ZombieHHChannel::vGetX(), ZombieHHChannel::vGetY(), ZombieHHChannel::vGetZ(), ZombieCompartment::vHandleChannel(), ZombieHHChannel::vHandleConc(), ZombieCompartment::vInjectMsg(), ZombieCaConc::vSetB(), ZombieCaConc::vSetCa(), ZombieCaConc::vSetCaBasal(), ZombieCaConc::vSetCeiling(), ZombieCompartment::vSetCm(), ZombieHHChannel::vSetEk(), ZombieCompartment::vSetEm(), ZombieCaConc::vSetFloor(), ZombieHHChannel::vSetGbar(), ZombieHHChannel::vSetGk(), ZombieCompartment::vSetInitVm(), ZombieCompartment::vSetInject(), ZombieHHChannel::vSetInstant(), ZombieHHChannel::vSetModulation(), ZombieCompartment::vSetRa(), ZombieCompartment::vSetRm(), ZombieCaConc::vSetTau(), ZombieCompartment::vSetVm(), ZombieHHChannel::vSetX(), ZombieHHChannel::vSetXpower(), ZombieHHChannel::vSetY(), ZombieHHChannel::vSetYpower(), ZombieHHChannel::vSetZ(), ZombieHHChannel::vSetZpower(), HSolve::zombify(), Stoich::zombifyModel(), and Stoich::zombifyPoolFuncWithScaling().
isDataHere()
bool Eref::isDataHere () const
True if the data are on the current node
Definition at line 53 of file Eref.cpp.
{
    return ( e_->getNode( i_ ) == Shell::myNode() );
}
References e_, Element::getNode(), i_, and Shell::myNode().
Referenced by data(), Neutral::getNumField(), Neutral::setNumField(), OneToOneMsg::sources(), and OneToOneMsg::targets().
msgDigest()
const vector< MsgDigest > & Eref::msgDigest (unsigned int bindIndex) const
Returns the digested version of the specified msgsrc. If the message has changed, this call triggers the digestion operation.
Definition at line 73 of file Eref.cpp.
{
    return e_->msgDigest( i_ * e_->cinfo()->numBindIndex() + bindIndex );
}
References Element::cinfo(), e_, i_, Element::msgDigest(), and Cinfo::numBindIndex().
Referenced by Element::getMsgTargets(), SrcFinfo0::send(), SrcFinfo2< T1, T2 >::send(), SrcFinfo3< T1, T2, T3 >::send(), SrcFinfo4< T1, T2, T3, T4 >::send(), SrcFinfo5< T1, T2, T3, T4, T5 >::send(), SrcFinfo6< T1, T2, T3, T4, T5, T6 >::send(), SrcFinfo1< T >::send(), SrcFinfo2< T1, T2 >::sendTo(), SrcFinfo1< T >::sendTo(), and SrcFinfo1< T >::sendVec().
objId()
ObjId Eref::objId () const
Returns the ObjId corresponding to the Eref. All info is kept.
Definition at line 63 of file Eref.cpp.
{
    return ObjId( e_->id(), i_, f_ );
}
References e_, f_, i_, Element::id(), and ObjId::ObjId().
Referenced by PostMaster::addToSendBuf(), PostMaster::addToSetBuf(), addToTestBuf(), Neuron::buildElist(), Dsolve::buildNeuroMeshJunctions(), Neutral::child(), Neutral::destroy(), HHGate::fillFromExpr(), Neuron::getExprElist(), Neuron::getExprVal(), Function::getIndependent(), Element::getMsgTargetAndFunctions(), Element::getMsgTargets(), Neutral::getObjId(), Neutral::isDescendant(), Neutral::parent(), Neutral::path(), Arith::process(), SocketStreamer::reinit(), moose::CompartmentBase::setGeomAndElec(), Enz::setSolver(), ElementValueFinfo< T, F >::strGet(), ReadOnlyElementValueFinfo< T, F >::strGet(), LookupElementValueFinfo< T, L, F >::strGet(), ReadOnlyLookupElementValueFinfo< T, L, F >::strGet(), LookupValueFinfo< T, L, F >::strGet(), ReadOnlyLookupValueFinfo< T, L, F >::strGet(), ValueFinfo< T, F >::strGet(), ReadOnlyValueFinfo< T, F >::strGet(), ElementValueFinfo< T, F >::strSet(), LookupElementValueFinfo< T, L, F >::strSet(), LookupValueFinfo< T, L, F >::strSet(), ValueFinfo< T, F >::strSet(), testGetMsg(), and HHChannel::vReinit().
Friends And Related Symbol Documentation
operator<<
ostream & operator<< (ostream & s, const Eref & e) friend
Member Data Documentation
e_
Element* Eref::e_ private
Definition at line 81 of file Eref.h.
Referenced by data(), element(), Eref(), Eref(), Eref(), getNode(), id(), isDataHere(), msgDigest(), objId(), and operator<<().
f_
unsigned int Eref::f_ private
Definition at line 83 of file Eref.h.
Referenced by data(), Eref(), Eref(), Eref(), fieldIndex(), objId(), and operator<<().
i_
unsigned int Eref::i_ private
Definition at line 82 of file Eref.h.
Referenced by data(), dataIndex(), Eref(), Eref(), Eref(), getNode(), isDataHere(), msgDigest(), objId(), and operator<<().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/basecode/Eref.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/basecode/Eref.cpp