MOOSE - Multiscale Object Oriented Simulation Environment: MarkovSolverBase Class Reference
MarkovSolverBase Class Reference
#include <MarkovSolverBase.h>
Public Member Functions
Vector * bilinearInterpolate () const
virtual Matrix * computeMatrixExponential ()
void computeState ()
void fillupTable ()
Vector getInitialState () const
double getInvDx () const
double getInvDy () const
Matrix getQ () const
Vector getState () const
unsigned int getXdivs () const
double getXmax () const
double getXmin () const
unsigned int getYdivs () const
double getYmax () const
double getYmin () const
void handleLigandConc (double)
void handleVm (double)
void init (Id, double)
void innerFillupTable (vector< unsigned int >, string, unsigned int, unsigned int)
Vector * linearInterpolate () const
MarkovSolverBase ()
void process (const Eref &, ProcPtr)
void reinit (const Eref &, ProcPtr)
void setInitialState (Vector)
void setXdivs (unsigned int)
void setXmax (double)
void setXmin (double)
void setYdivs (unsigned int)
void setYmax (double)
void setYmin (double)
virtual ~MarkovSolverBase ()
Static Public Member Functions
static const Cinfo * initCinfo ()
Protected Attributes
Matrix * Q_
Private Member Functions
void setLookupParams ()
Private Attributes
double dt_
Matrix * expMat_
vector< Matrix * > expMats1d_
vector< vector< Matrix * > > expMats2d_
Vector initialState_
double invDx_
double invDy_
double ligandConc_
MarkovRateTable * rateTable_
unsigned int size_
Vector state_
double Vm_
unsigned int xDivs_
double xMax_
double xMin_
unsigned int yDivs_
double yMax_
double yMin_
Detailed Description
Definition at line 51 of file MarkovSolverBase.h.
Constructor & Destructor Documentation
MarkovSolverBase()
MarkovSolverBase::MarkovSolverBase ()
Definition at line 189 of file MarkovSolverBase.cpp.
                                   : Q_(0), expMats1d_(0), expMat_(0),
    expMats2d_(0), xMin_(DBL_MAX), xMax_(DBL_MIN), xDivs_(0u),
    yMin_(DBL_MAX), yMax_(DBL_MIN), yDivs_(0u), size_(0u), Vm_(0),
    ligandConc_(0), dt_(0)
{
    ;
}
References dt_, expMat_, expMats1d_, expMats2d_, ligandConc_, Q_, size_, Vm_, xDivs_, xMax_, xMin_, yDivs_, yMax_, and yMin_.
~MarkovSolverBase()
MarkovSolverBase::~MarkovSolverBase () virtual
Definition at line 197 of file MarkovSolverBase.cpp.
{
    if ( Q_ )
        delete Q_;
    if ( !expMats1d_.empty() )
    {
        while ( !expMats1d_.empty() )
        {
            delete expMats1d_.back();
            expMats1d_.pop_back();
        }
    }
    if ( !expMats2d_.empty() )
    {
        unsigned int n = expMats2d_.size();
        for( unsigned int i = 0; i < n; ++i )
        {
            for ( unsigned int j = 0; j < expMats2d_[i].size(); ++j )
                delete expMats2d_[i][j];
        }
    }
    if ( expMat_ != 0 )
        delete expMat_;
}
References expMat_, expMats1d_, expMats2d_, and Q_.
Member Function Documentation
bilinearInterpolate()
Vector * MarkovSolverBase::bilinearInterpolate () const
Definition at line 317 of file MarkovSolverBase.cpp.
{
    bool isEndOfX = false;
    bool isEndOfY = false;
    unsigned int xIndex =
        static_cast< unsigned int >( ( Vm_ - xMin_ ) * invDx_ );
    unsigned int yIndex =
        static_cast< unsigned int >( ( ligandConc_ - yMin_ ) * invDy_ );
    double xv = (Vm_ - xMin_) * invDx_;
    double yv = (ligandConc_ - yMin_) * invDy_;
    double xF = xv - xIndex;
    double yF = yv - yIndex;
    double xFyF = xF * yF;
    ( xIndex == xDivs_ ) ? isEndOfX = true : isEndOfX = false;
    ( yIndex == yDivs_ ) ? isEndOfY = true : isEndOfY = false;
    vector< vector< Matrix* > >::const_iterator iExpQ0 =
        expMats2d_.begin() + xIndex;
    vector< Matrix* >::const_iterator iExpQ00 = iExpQ0->begin() + yIndex;
    vector< Matrix* >::const_iterator iExpQ10;
    Matrix* expQ00 = *iExpQ00;
    Matrix* expQ01;
    Matrix* expQ10;
    Matrix* expQ11;
#if ENABLE_CPP1
    // Intialization to supress compiler warning.
    Vector *state00 = nullptr;
    Vector *state01 = nullptr;
    Vector *state10 = nullptr;
    Vector *state11 = nullptr;
    Vector *result = nullptr;
#else
    Vector *state00 = NULL, *state01 = NULL
        , *state10 = NULL, *state11 = NULL
        , *result = NULL
        ;
#endif
    state00 = vecMatMul( &state_, expQ00 );
    if ( isEndOfX )
    {
        if ( isEndOfY )
            return state00;
        else
        {
            expQ01 = *(iExpQ00 + 1);
            state01 = vecMatMul( &state_, expQ01 );
            result =  vecVecScalAdd( state00, state01,
                    (1 - yF), yF );
        }
    }
    else
    {
        iExpQ10 = ( iExpQ0 + 1 )->begin() + yIndex;
        expQ10 = *iExpQ10;
        state10 = vecMatMul( &state_, expQ10 );
        if ( isEndOfY )
        {
            result =  vecVecScalAdd( state00, state10, ( 1 - xF ), xF );
        }
        else
        {
            expQ01 = *( iExpQ00 + 1 );
            expQ11 = *( iExpQ10 + 1 );
            state01 = vecMatMul( &state_, expQ01 );
            state11 = vecMatMul( &state_, expQ11 );
            Vector *temp1, *temp2;
            temp1 = vecVecScalAdd( state00, state10,
                    ( 1 - xF - yF + xFyF ),
                    ( xF - xFyF )
                    );
            temp2 = vecVecScalAdd( state01, state11, ( yF - xFyF ), xFyF );
            result = vecVecScalAdd( temp1, temp2, 1.0, 1.0 );
            delete temp1;
            delete temp2;
        }
    }
    if ( state00 )
        delete state00;
    if ( state01 )
        delete state01;
    if ( state10 )
        delete state10;
    if ( state11 )
        delete state11;
    return result;
}
References expMats2d_, invDx_, invDy_, ligandConc_, state_, vecMatMul(), vecVecScalAdd(), Vm_, xDivs_, xMin_, yDivs_, and yMin_.
Referenced by computeState().
computeMatrixExponential()
Matrix * MarkovSolverBase::computeMatrixExponential () virtual
Reimplemented in MarkovSolver.
Definition at line 600 of file MarkovSolverBase.cpp.
{
    return 0;
}
Referenced by fillupTable().
computeState()
void MarkovSolverBase::computeState ()
Definition at line 463 of file MarkovSolverBase.cpp.
{
    Vector* newState;
    bool useBilinear = false;
    // useLinear = false;
    if ( rateTable_->areAnyRates2d() ||
            ( rateTable_->areAllRates1d() &&
              rateTable_->areAnyRatesVoltageDep() &&
              rateTable_->areAnyRatesLigandDep()
            )  )
    {
        useBilinear = true;
    }
    /*
    else if ( rateTable_->areAllRatesVoltageDep() ||
                        rateTable_->areAllRatesLigandDep() )
    {
        useLinear = true;
    }
    */
    //Heavily borrows from the Interpol2D::interpolate function.
    if ( useBilinear )
        newState = bilinearInterpolate();
    else
        newState = linearInterpolate();
    state_ = *newState;
    delete newState;
}
References MarkovRateTable::areAllRates1d(), MarkovRateTable::areAnyRates2d(), MarkovRateTable::areAnyRatesLigandDep(), MarkovRateTable::areAnyRatesVoltageDep(), bilinearInterpolate(), linearInterpolate(), rateTable_, and state_.
Referenced by process().
fillupTable()
void MarkovSolverBase::fillupTable ()
Definition at line 524 of file MarkovSolverBase.cpp.
{
    double dx = (xMax_ - xMin_) / xDivs_;
    double dy = (yMax_ - yMin_) / yDivs_;
    vector< unsigned int > listOf1dRates = rateTable_->getListOf1dRates();
    vector< unsigned int > listOf2dRates = rateTable_->getListOf2dRates();
    vector< unsigned int > listOfConstantRates =
                                                 rateTable_->getListOfConstantRates();
    //Set constant rates in the Q matrix, if any.
    innerFillupTable( listOfConstantRates, "constant",
                                        0, 0 );
    //xIndex loops through all voltages, yIndex loops through all
    //ligand concentrations.
    if ( rateTable_->areAnyRates2d() ||
            ( rateTable_->areAllRates1d() &&
              rateTable_->areAnyRatesVoltageDep() &&
              rateTable_->areAnyRatesLigandDep()
            )  )
    {
        double voltage = xMin_, ligandConc = yMin_;
        for ( unsigned int xIndex = 0; xIndex < xDivs_ + 1; ++xIndex )
        {
            ligandConc = yMin_;
            for( unsigned int yIndex = 0; yIndex < yDivs_ + 1; ++yIndex )
            {
                innerFillupTable( listOf2dRates, "2D", xIndex, yIndex );
                //This is a very klutzy way of updating 1D rates as the same
                //lookup is done multiple times. But this all occurs at setup,
                //and lookups arent that slow either. This way is also easier
                //to maintain.
                innerFillupTable( listOf1dRates, "1D", xIndex, yIndex );
                expMats2d_[xIndex][yIndex] = computeMatrixExponential();
                ligandConc += dy;
            }
            voltage += dx;
        }
    }
    else if ( rateTable_->areAllRatesLigandDep() )
    {
        double x = xMin_;
        vector< unsigned int > listOfLigandRates =
                                                    rateTable_->getListOfLigandRates();
        for ( unsigned int xIndex = 0; xIndex < xDivs_ + 1; ++xIndex )
        {
            innerFillupTable( listOfLigandRates, "1D", xIndex, 0 );
            expMats1d_[xIndex] = computeMatrixExponential();
            x += dx;
        }
    }
    else if ( rateTable_->areAllRatesVoltageDep() )
    {
        double x = xMin_;
        vector< unsigned int > listOfVoltageRates =
                                                 rateTable_->getListOfVoltageRates();
        for ( unsigned int xIndex = 0; xIndex < xDivs_ + 1; ++xIndex )
        {
            innerFillupTable( listOfVoltageRates, "1D", xIndex, 0 );
            expMats1d_[xIndex] = computeMatrixExponential();
            x += dx;
        }
    }
    else if ( rateTable_->areAllRatesConstant() )
    {
        expMat_ = computeMatrixExponential();
        return;
    }
}
References MarkovRateTable::areAllRates1d(), MarkovRateTable::areAllRatesConstant(), MarkovRateTable::areAllRatesLigandDep(), MarkovRateTable::areAllRatesVoltageDep(), MarkovRateTable::areAnyRates2d(), MarkovRateTable::areAnyRatesLigandDep(), MarkovRateTable::areAnyRatesVoltageDep(), computeMatrixExponential(), expMat_, expMats1d_, expMats2d_, MarkovRateTable::getListOf1dRates(), MarkovRateTable::getListOf2dRates(), MarkovRateTable::getListOfConstantRates(), MarkovRateTable::getListOfLigandRates(), MarkovRateTable::getListOfVoltageRates(), innerFillupTable(), rateTable_, xDivs_, xMax_, xMin_, yDivs_, yMax_, and yMin_.
Referenced by init().
getInitialState()
Vector MarkovSolverBase::getInitialState () const
Definition at line 238 of file MarkovSolverBase.cpp.
{
    return initialState_;
}
References initialState_.
Referenced by initCinfo().
getInvDx()
double MarkovSolverBase::getInvDx () const
Definition at line 278 of file MarkovSolverBase.cpp.
{
    return invDx_;
}
References invDx_.
Referenced by initCinfo().
getInvDy()
double MarkovSolverBase::getInvDy () const
Definition at line 312 of file MarkovSolverBase.cpp.
{
    return invDy_;
}
References invDy_.
Referenced by initCinfo().
getQ()
Matrix MarkovSolverBase::getQ () const
Definition at line 228 of file MarkovSolverBase.cpp.
{
    return *Q_;
}
References Q_.
Referenced by initCinfo().
getState()
Vector MarkovSolverBase::getState () const
Definition at line 233 of file MarkovSolverBase.cpp.
{
    return state_;
}
References state_.
Referenced by initCinfo().
getXdivs()
unsigned int MarkovSolverBase::getXdivs () const
Definition at line 274 of file MarkovSolverBase.cpp.
{
    return xDivs_;
}
References xDivs_.
Referenced by initCinfo().
getXmax()
double MarkovSolverBase::getXmax () const
Definition at line 264 of file MarkovSolverBase.cpp.
{
    return xMax_;
}
References xMax_.
Referenced by initCinfo().
getXmin()
double MarkovSolverBase::getXmin () const
Definition at line 254 of file MarkovSolverBase.cpp.
{
    return xMin_;
}
References xMin_.
Referenced by initCinfo().
getYdivs()
unsigned int MarkovSolverBase::getYdivs () const
Definition at line 307 of file MarkovSolverBase.cpp.
{
    return yDivs_;
}
References yDivs_.
Referenced by initCinfo().
getYmax()
double MarkovSolverBase::getYmax () const
Definition at line 297 of file MarkovSolverBase.cpp.
{
    return yMax_;
}
References yMax_.
Referenced by initCinfo().
getYmin()
double MarkovSolverBase::getYmin () const
Definition at line 287 of file MarkovSolverBase.cpp.
{
    return yMin_;
}
References yMin_.
Referenced by initCinfo().
handleLigandConc()
void MarkovSolverBase::handleLigandConc (double ligandConc)
Definition at line 634 of file MarkovSolverBase.cpp.
{
    ligandConc_ = ligandConc;
}
References ligandConc_.
Referenced by initCinfo().
handleVm()
void MarkovSolverBase::handleVm (double Vm)
Definition at line 629 of file MarkovSolverBase.cpp.
{
    Vm_ = Vm;
}
References Vm_.
Referenced by initCinfo().
init()
void MarkovSolverBase::init (Id rateTableId, double dt)
Definition at line 641 of file MarkovSolverBase.cpp.
{
    MarkovRateTable* rateTable = reinterpret_cast< MarkovRateTable* >(
            rateTableId.eref().data() );
    size_ = rateTable->getSize();
    rateTable_ = rateTable;
    setLookupParams( );
    if ( rateTable->areAnyRates2d() ||
            ( rateTable->areAllRates1d() &&
              rateTable->areAnyRatesVoltageDep() &&
              rateTable->areAnyRatesLigandDep()
            )  )
    {
        expMats2d_.resize( xDivs_ + 1 );
        for( unsigned int i = 0; i < xDivs_ + 1; ++i )
            expMats2d_[i].resize( yDivs_ + 1);
    }
    else if ( rateTable->areAllRatesLigandDep() ||
                        rateTable->areAllRatesVoltageDep() )
    {
        expMats1d_.resize( xDivs_ + 1);
    }
    else    //All rates must be constant.
    {
        expMat_ = matAlloc( size_ );
    }
    //Initializing Q.
    Q_ = matAlloc( size_ );
    //The state at t = t0 + dt is exp( dt * Q ) * [state at t = t0].
    //Hence, we need to scale the terms of Q by dt.
    dt_ = dt;
    //Fills up the newly setup tables with exponentials.
    fillupTable( );
}
References MarkovRateTable::areAllRates1d(), MarkovRateTable::areAllRatesLigandDep(), MarkovRateTable::areAllRatesVoltageDep(), MarkovRateTable::areAnyRates2d(), MarkovRateTable::areAnyRatesLigandDep(), MarkovRateTable::areAnyRatesVoltageDep(), Eref::data(), dt_, Id::eref(), expMat_, expMats1d_, expMats2d_, fillupTable(), MarkovRateTable::getSize(), matAlloc(), Q_, rateTable_, setLookupParams(), size_, xDivs_, and yDivs_.
Referenced by initCinfo().
initCinfo()
const Cinfo * MarkovSolverBase::initCinfo () static
Definition at line 28 of file MarkovSolverBase.cpp.
{
    //SharedFinfos
    static DestFinfo handleVm("handleVm",
            "Handles incoming message containing voltage information.",
            new OpFunc1< MarkovSolverBase, double >(&MarkovSolverBase::handleVm)
            );
    static Finfo* channelShared[] =
    {
        &handleVm
    };
    static SharedFinfo channel("channel",
            "This message couples the MarkovSolverBase to the Compartment. The "
            "compartment needs Vm in order to look up the correct matrix "
            "exponential for computing the state.",
            channelShared, sizeof( channelShared ) / sizeof( Finfo* )
            );
    //DestFinfos
    static DestFinfo process(   "process",
            "Handles process call",
            new ProcOpFunc< MarkovSolverBase >( &MarkovSolverBase::process ) );
    static DestFinfo reinit( "reinit",
            "Handles reinit call",
            new ProcOpFunc< MarkovSolverBase >( &MarkovSolverBase::reinit ) );
    static Finfo* processShared[] =
    {
        &process, &reinit
    };
    static SharedFinfo proc( "proc",
            "This is a shared message to receive Process message from the"
            "scheduler. The first entry is a MsgDest for the Process "
            "operation. It has a single argument, ProcInfo, which "
            "holds lots of information about current time, thread, dt and"
            "so on. The second entry is a MsgDest for the Reinit "
            "operation. It also uses ProcInfo.",
        processShared, sizeof( processShared ) / sizeof( Finfo* )
    );
    static DestFinfo ligandConc("ligandConc",
            "Handles incoming message containing ligand concentration.",
            new OpFunc1< MarkovSolverBase, double >(&MarkovSolverBase::handleLigandConc)
            );
    static DestFinfo init("init",
            "Setups the table of matrix exponentials associated with the"
            " solver object.",
            new OpFunc2< MarkovSolverBase, Id, double >(&MarkovSolverBase::init)
            );
    //*ValueFinfos
    static ReadOnlyValueFinfo< MarkovSolverBase, Matrix > Q("Q",
            "Instantaneous rate matrix.",
            &MarkovSolverBase::getQ
            );
    static ReadOnlyValueFinfo< MarkovSolverBase, Vector > state("state",
            "Current state of the channel.",
            &MarkovSolverBase::getState
            );
    static ValueFinfo< MarkovSolverBase, Vector > initialstate("initialState",
            "Initial state of the channel.",
            &MarkovSolverBase::setInitialState,
            &MarkovSolverBase::getInitialState
            );
    static ValueFinfo< MarkovSolverBase, double > xmin( "xmin",
        "Minimum value for x axis of lookup table",
            &MarkovSolverBase::setXmin,
            &MarkovSolverBase::getXmin
        );
    static ValueFinfo< MarkovSolverBase, double > xmax( "xmax",
        "Maximum value for x axis of lookup table",
            &MarkovSolverBase::setXmax,
            &MarkovSolverBase::getXmax
        );
    static ValueFinfo< MarkovSolverBase, unsigned int > xdivs( "xdivs",
        "# of divisions on x axis of lookup table",
            &MarkovSolverBase::setXdivs,
            &MarkovSolverBase::getXdivs
        );
    static ReadOnlyValueFinfo< MarkovSolverBase, double > invdx( "invdx",
        "Reciprocal of increment on x axis of lookup table",
            &MarkovSolverBase::getInvDx
        );
    static ValueFinfo< MarkovSolverBase, double > ymin( "ymin",
        "Minimum value for y axis of lookup table",
            &MarkovSolverBase::setYmin,
            &MarkovSolverBase::getYmin
        );
    static ValueFinfo< MarkovSolverBase, double > ymax( "ymax",
        "Maximum value for y axis of lookup table",
            &MarkovSolverBase::setYmax,
            &MarkovSolverBase::getYmax
        );
    static ValueFinfo< MarkovSolverBase, unsigned int > ydivs( "ydivs",
        "# of divisions on y axis of lookup table",
            &MarkovSolverBase::setYdivs,
            &MarkovSolverBase::getYdivs
        );
    static ReadOnlyValueFinfo< MarkovSolverBase, double > invdy( "invdy",
        "Reciprocal of increment on y axis of lookup table",
            &MarkovSolverBase::getInvDy
        );
    static Finfo* markovSolverFinfos[] =
    {
        &channel,                       //SharedFinfo
        &proc,                          //SharedFinfo
        stateOut(),                 //SrcFinfo
        &ligandConc,                //DestFinfo
        &init,                          //DestFinfo
        &Q,                                 //ReadOnlyValueFinfo
        &state,                         //ReadOnlyValueFinfo
        &initialstate,          //ReadOnlyValueFinfo
        &xmin,                          //ValueFinfo
        &xmax,                          //ValueFinfo
        &xdivs,                         //ValueFinfo
        &invdx,                         //ReadOnlyValueFinfo
        &ymin,                          //ValueFinfo
        &ymax,                          //ValueFinfo
        &ydivs,                         //ValueFinfo
        &invdy                          //ReadOnlyValueFinfo
    };
    static string doc[] =
    {
        "Name", "MarkovSolverBase",
        "Author", "Vishaka Datta S, 2011, NCBS",
        "Description", "Solver for Markov Channel."
    };
    static Dinfo< MarkovSolverBase > dinfo;
    static Cinfo markovSolverBaseCinfo(
            "MarkovSolverBase",
            Neutral::initCinfo(),
            markovSolverFinfos,
            sizeof( markovSolverFinfos ) / sizeof( Finfo* ),
            &dinfo,
            doc,
            sizeof(doc) / sizeof(string)
        );
    return &markovSolverBaseCinfo;
}
References Cinfo::Cinfo(), DestFinfo::DestFinfo(), getInitialState(), getInvDx(), getInvDy(), getQ(), getState(), getXdivs(), getXmax(), getXmin(), getYdivs(), getYmax(), getYmin(), handleLigandConc(), handleVm(), init(), Neutral::initCinfo(), OpFunc1< T, A >::OpFunc1(), OpFunc2< T, A1, A2 >::OpFunc2(), process(), ProcOpFunc< T >::ProcOpFunc(), ReadOnlyValueFinfo< T, F >::ReadOnlyValueFinfo(), reinit(), setInitialState(), setXdivs(), setXmax(), setXmin(), setYdivs(), setYmax(), setYmin(), SharedFinfo::SharedFinfo(), stateOut(), and ValueFinfo< T, F >::ValueFinfo().
Referenced by MarkovSolver::initCinfo().
innerFillupTable()
void MarkovSolverBase::innerFillupTable (vector< unsigned int > , string , unsigned int , unsigned int)
Definition at line 496 of file MarkovSolverBase.cpp.
{
    unsigned int n = rateIndices.size(), i, j;
    for ( unsigned int k = 0; k < n; ++k )
    {
        i = ( ( rateIndices[k] / 10 ) % 10 ) - 1;
        j = ( rateIndices[k] % 10 ) - 1;
        (*Q_)[i][i] += (*Q_)[i][j];
        if ( rateType.compare("2D") == 0 )
            (*Q_)[i][j] = rateTable_->lookup2dIndex( i, j, xIndex, yIndex );
        else if ( rateType.compare("1D") == 0 )
            (*Q_)[i][j] = rateTable_->lookup1dIndex( i, j, xIndex );
        else if ( rateType.compare("constant") == 0 )
            (*Q_)[i][j] = rateTable_->lookup1dValue( i, j, 1.0 );
        (*Q_)[i][j] *= dt_;
        (*Q_)[i][i] -= (*Q_)[i][j];
    }
}
References dt_, MarkovRateTable::lookup1dIndex(), MarkovRateTable::lookup1dValue(), MarkovRateTable::lookup2dIndex(), Q_, and rateTable_.
Referenced by fillupTable().
linearInterpolate()
Vector * MarkovSolverBase::linearInterpolate () const
Definition at line 419 of file MarkovSolverBase.cpp.
{
    double x;
    if ( rateTable_->areAllRatesVoltageDep() )
        x = Vm_;
    else
        x = ligandConc_;
    if ( x < xMin_ )
        return vecMatMul( &state_, expMats1d_[0] );
    else if ( x > xMax_ )
        return vecMatMul( &state_, expMats1d_.back() );
    unsigned int xIndex = static_cast< unsigned int >( ( x - xMin_) * invDx_ );
    double xv = ( x - xMin_ ) * invDx_;
    double xF = xv - xIndex;
    vector< Matrix* >::const_iterator iExpQ =
                                                                                    expMats1d_.begin() + xIndex;
    Vector *state0, *state1, *result;
    state0 = vecMatMul( &state_, *iExpQ );
    state1 = vecMatMul( &state_, *( iExpQ + 1 ) );
    result = vecVecScalAdd( state0, state1, 1 - xF, xF );
    delete state0;
    delete state1;
    return result;
}
References MarkovRateTable::areAllRatesVoltageDep(), expMats1d_, invDx_, ligandConc_, rateTable_, state_, vecMatMul(), vecVecScalAdd(), Vm_, xMax_, and xMin_.
Referenced by computeState().
process()
void MarkovSolverBase::process (const Eref & e, ProcPtr p)
Definition at line 622 of file MarkovSolverBase.cpp.
{
    computeState();
    stateOut()->send( e, state_ );
}
References computeState(), SrcFinfo1< T >::send(), state_, and stateOut().
Referenced by initCinfo(), and MarkovSolver::process().
reinit()
void MarkovSolverBase::reinit (const Eref & e, ProcPtr p)
Definition at line 609 of file MarkovSolverBase.cpp.
{
    if ( initialState_.empty() )
    {
        cerr << "MarkovSolverBase::reinit : Initial state has not been "
                        "set.\n";
        return;
    }
    state_ = initialState_;
    stateOut()->send( e, state_ );
}
References initialState_, SrcFinfo1< T >::send(), state_, and stateOut().
Referenced by initCinfo(), and MarkovSolver::reinit().
setInitialState()
void MarkovSolverBase::setInitialState (Vector state)
Definition at line 243 of file MarkovSolverBase.cpp.
{
    initialState_ = state;
    state_ = initialState_;
}
References initialState_, and state_.
Referenced by initCinfo().
setLookupParams()
void MarkovSolverBase::setLookupParams () private
Definition at line 697 of file MarkovSolverBase.cpp.
{
    if ( rateTable_->areAnyRates1d() )
    {
        vector< unsigned int > listOfLigandRates
                                                        = rateTable_->getListOfLigandRates();
        vector< unsigned int > listOfVoltageRates
                                                        = rateTable_->getListOfVoltageRates();
        double temp;
        double yMax = DBL_MIN, yMin = DBL_MAX;
        unsigned int yDivs = 0u;
        unsigned int divs, i, j;
        for( unsigned int k = 0; k < listOfLigandRates.size(); ++k )
        {
            i = ( ( listOfLigandRates[k] / 10 ) % 10 ) - 1;
            j = ( listOfLigandRates[k] % 10 ) - 1;
            temp = rateTable_->getVtChildTable( i, j )->getMin();
            if ( yMin > temp )
                yMin = temp;
            temp = rateTable_->getVtChildTable( i, j )->getMax();
            if ( yMax < temp )
                yMax = temp;
            divs = rateTable_->getVtChildTable( i, j )->getDiv();
            if ( yDivs < divs )
                yDivs = divs;
        }
        if ( ( rateTable_->areAllRatesLigandDep() &&
                     rateTable_->areAllRates1d() ) )
        {
            xMin_ = yMin;
            xMax_ = yMax;
            xDivs_ = yDivs;
            invDx_ = yDivs / ( yMax - yMin );
        }
        else
        {
            yMin_= yMin;
            yMax_ = yMax;
            yDivs_ = yDivs;
            invDy_ = yDivs / ( yMax - yMin );
        }
        for( unsigned int k = 0; k < listOfVoltageRates.size(); ++k )
        {
            i = ( ( listOfVoltageRates[k] / 10 ) % 10 ) - 1;
            j = ( listOfVoltageRates[k] % 10 ) - 1;
            temp = rateTable_->getVtChildTable( i, j )->getMin();
            if ( xMin_ > temp )
                xMin_ = temp;
            temp = rateTable_->getVtChildTable( i, j )->getMax();
            if ( xMax_ < temp )
                xMax_ = temp;
            divs = rateTable_->getVtChildTable( i, j )->getDiv();
            if ( xDivs_ < divs )
                xDivs_ = divs;
        }
    }
    if ( rateTable_->areAnyRates2d() )
    {
        vector< unsigned int > listOf2dRates = rateTable_->getListOf2dRates();
        double temp;
        unsigned int divs, i, j;
        for( unsigned int k = 0; k < listOf2dRates.size(); ++k )
        {
            i = ( ( listOf2dRates[k] / 10 ) % 10 ) - 1;
            j = ( listOf2dRates[k] % 10 ) - 1;
            temp = rateTable_->getInt2dChildTable( i, j )->getXmin();
            if ( xMin_ > temp )
                xMin_ = temp;
            temp = rateTable_->getInt2dChildTable( i, j )->getXmax();
            if ( xMax_ < temp )
                xMax_ = temp;
            temp = rateTable_->getInt2dChildTable( i, j )->getYmin();
            if ( yMin_ > temp )
                yMin_ = temp;
            temp = rateTable_->getInt2dChildTable( i, j )->getYmax();
            if ( yMax_ < temp )
                yMax_ = temp;
            divs = rateTable_->getInt2dChildTable( i, j )->getXdivs();
            if ( xDivs_ < divs )
                xDivs_ = divs;
            divs = rateTable_->getInt2dChildTable( i, j )->getYdivs();
            if ( yDivs_ < divs )
                yDivs_ = divs;
        }
        invDx_ = xDivs_ / ( xMax_ - xMin_ );
        invDy_ = yDivs_ / ( yMax_ - yMin_ );
    }
}
References MarkovRateTable::areAllRates1d(), MarkovRateTable::areAllRatesLigandDep(), MarkovRateTable::areAnyRates1d(), MarkovRateTable::areAnyRates2d(), VectorTable::getDiv(), MarkovRateTable::getInt2dChildTable(), MarkovRateTable::getListOf2dRates(), MarkovRateTable::getListOfLigandRates(), MarkovRateTable::getListOfVoltageRates(), VectorTable::getMax(), VectorTable::getMin(), MarkovRateTable::getVtChildTable(), Interpol2D::getXdivs(), Interpol2D::getXmax(), Interpol2D::getXmin(), Interpol2D::getYdivs(), Interpol2D::getYmax(), Interpol2D::getYmin(), invDx_, invDy_, rateTable_, xDivs_, xMax_, xMin_, yDivs_, yMax_, and yMin_.
Referenced by init().
setXdivs()
void MarkovSolverBase::setXdivs (unsigned int xDivs)
Definition at line 269 of file MarkovSolverBase.cpp.
{
    xDivs_ = xDivs;
}
References xDivs_.
Referenced by initCinfo().
setXmax()
void MarkovSolverBase::setXmax (double xMax)
Definition at line 259 of file MarkovSolverBase.cpp.
{
    xMax_ = xMax;
}
References xMax_.
Referenced by initCinfo().
setXmin()
void MarkovSolverBase::setXmin (double xMin)
Definition at line 249 of file MarkovSolverBase.cpp.
{
    xMin_ = xMin;
}
References xMin_.
Referenced by initCinfo().
setYdivs()
void MarkovSolverBase::setYdivs (unsigned int yDivs)
Definition at line 302 of file MarkovSolverBase.cpp.
{
    yDivs_ = yDivs;
}
References yDivs_.
Referenced by initCinfo().
setYmax()
void MarkovSolverBase::setYmax (double yMax)
Definition at line 292 of file MarkovSolverBase.cpp.
{
    yMax_ = yMax;
}
References yMax_.
Referenced by initCinfo().
setYmin()
void MarkovSolverBase::setYmin (double yMin)
Definition at line 282 of file MarkovSolverBase.cpp.
{
    yMin_ = yMin;
}
References yMin_.
Referenced by initCinfo().
Member Data Documentation
dt_
double MarkovSolverBase::dt_ private
Definition at line 211 of file MarkovSolverBase.h.
Referenced by init(), innerFillupTable(), and MarkovSolverBase().
expMat_
Matrix* MarkovSolverBase::expMat_ private
Definition at line 172 of file MarkovSolverBase.h.
Referenced by fillupTable(), init(), MarkovSolverBase(), and ~MarkovSolverBase().
expMats1d_
vector< Matrix* > MarkovSolverBase::expMats1d_ private
Definition at line 170 of file MarkovSolverBase.h.
Referenced by fillupTable(), init(), linearInterpolate(), MarkovSolverBase(), and ~MarkovSolverBase().
expMats2d_
vector< vector< Matrix* > > MarkovSolverBase::expMats2d_ private
Definition at line 175 of file MarkovSolverBase.h.
Referenced by bilinearInterpolate(), fillupTable(), init(), MarkovSolverBase(), and ~MarkovSolverBase().
initialState_
Vector MarkovSolverBase::initialState_ private
Definition at line 198 of file MarkovSolverBase.h.
Referenced by getInitialState(), reinit(), and setInitialState().
invDx_
double MarkovSolverBase::invDx_ private
Definition at line 179 of file MarkovSolverBase.h.
Referenced by bilinearInterpolate(), getInvDx(), linearInterpolate(), and setLookupParams().
invDy_
double MarkovSolverBase::invDy_ private
Definition at line 183 of file MarkovSolverBase.h.
Referenced by bilinearInterpolate(), getInvDy(), and setLookupParams().
ligandConc_
double MarkovSolverBase::ligandConc_ private
Definition at line 207 of file MarkovSolverBase.h.
Referenced by bilinearInterpolate(), handleLigandConc(), linearInterpolate(), and MarkovSolverBase().
Q_
Matrix* MarkovSolverBase::Q_ protected
Definition at line 130 of file MarkovSolverBase.h.
Referenced by MarkovSolver::computeMatrixExponential(), getQ(), init(), innerFillupTable(), MarkovSolverBase(), and ~MarkovSolverBase().
rateTable_
MarkovRateTable* MarkovSolverBase::rateTable_ private
Definition at line 192 of file MarkovSolverBase.h.
Referenced by computeState(), fillupTable(), init(), innerFillupTable(), linearInterpolate(), and setLookupParams().
size_
unsigned int MarkovSolverBase::size_ private
Definition at line 202 of file MarkovSolverBase.h.
Referenced by init(), and MarkovSolverBase().
state_
Vector MarkovSolverBase::state_ private
Definition at line 195 of file MarkovSolverBase.h.
Referenced by bilinearInterpolate(), computeState(), getState(), linearInterpolate(), process(), reinit(), and setInitialState().
Vm_
double MarkovSolverBase::Vm_ private
Definition at line 205 of file MarkovSolverBase.h.
Referenced by bilinearInterpolate(), handleVm(), linearInterpolate(), and MarkovSolverBase().
xDivs_
unsigned int MarkovSolverBase::xDivs_ private
Definition at line 180 of file MarkovSolverBase.h.
Referenced by bilinearInterpolate(), fillupTable(), getXdivs(), init(), MarkovSolverBase(), setLookupParams(), and setXdivs().
xMax_
double MarkovSolverBase::xMax_ private
Definition at line 178 of file MarkovSolverBase.h.
Referenced by fillupTable(), getXmax(), linearInterpolate(), MarkovSolverBase(), setLookupParams(), and setXmax().
xMin_
double MarkovSolverBase::xMin_ private
Definition at line 177 of file MarkovSolverBase.h.
Referenced by bilinearInterpolate(), fillupTable(), getXmin(), linearInterpolate(), MarkovSolverBase(), setLookupParams(), and setXmin().
yDivs_
unsigned int MarkovSolverBase::yDivs_ private
Definition at line 184 of file MarkovSolverBase.h.
Referenced by bilinearInterpolate(), fillupTable(), getYdivs(), init(), MarkovSolverBase(), setLookupParams(), and setYdivs().
yMax_
double MarkovSolverBase::yMax_ private
Definition at line 182 of file MarkovSolverBase.h.
Referenced by fillupTable(), getYmax(), MarkovSolverBase(), setLookupParams(), and setYmax().
yMin_
double MarkovSolverBase::yMin_ private
Definition at line 181 of file MarkovSolverBase.h.
Referenced by bilinearInterpolate(), fillupTable(), getYmin(), MarkovSolverBase(), setLookupParams(), and setYmin().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/biophysics/MarkovSolverBase.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/biophysics/MarkovSolverBase.cpp