MOOSE - Multiscale Object Oriented Simulation Environment: NOrder Class Reference
NOrder Class Reference
#include <RateTerm.h>
Public Member Functions
RateTerm * copyWithVolScaling (double vol, double sub, double prd) const
unsigned int getReactants (vector< unsigned int > &molIndex) const
NOrder (double k, vector< unsigned int > v)
double operator() (const double *S) const
Computes the rate. The argument is the molecule array.
void rescaleVolume (short comptIndex, const vector< short > &compartmentLookup, double ratio)
Public Member Functions inherited from ZeroOrder
RateTerm * copyWithVolScaling (double vol, double sub, double prd) const
double getR1 () const
Used by Zombie to return rate terms.
double getR2 () const
Used by Zombie to return rate terms.
unsigned int getReactants (vector< unsigned int > &molIndex) const
double operator() (const double *S) const
Computes the rate. The argument is the molecule array.
void rescaleVolume (short comptIndex, const vector< short > &compartmentLookup, double ratio)
void setK (double k)
void setR1 (double k1)
Used by Zombie to assign rate terms.
void setR2 (double k2)
Used by Zombie to assign rate terms.
void setRates (double k1, double k2)
ZeroOrder (double k)
Public Member Functions inherited from RateTerm
RateTerm ()
virtual ~RateTerm ()
Protected Attributes
vector< unsigned int > v_
Protected Attributes inherited from ZeroOrder
double k_
Additional Inherited Members
Static Public Attributes inherited from RateTerm
static const double EPSILON = 1.0e-6
Detailed Description
Definition at line 511 of file RateTerm.h.
Constructor & Destructor Documentation
NOrder()
NOrder::NOrder (double k, vector< unsigned int > v) inline
Definition at line 514 of file RateTerm.h.
        : ZeroOrder( k ), v_( v )
    {;}
References v_, and ZeroOrder::ZeroOrder().
Referenced by copyWithVolScaling(), Stoich::installMMenz(), Stoich::makeHalfReaction(), and StochNOrder::StochNOrder().
Member Function Documentation
copyWithVolScaling()
RateTerm * NOrder::copyWithVolScaling (double vol, double sub, double prd) const inline virtual
Duplicates rate term and then applies volume scaling. Arguments are volume of reference voxel, product of vol/refVol for all substrates: applied to R1 product of vol/refVol for all products: applied to R2
Note that unless the reaction is cross-compartment, the vol/refVol will be one.
Implements RateTerm.
Reimplemented in StochNOrder.
Definition at line 546 of file RateTerm.h.
    {
        assert( v_.size() > 0 );
        double ratio = sub * pow( NA * vol, (int)( v_.size() ) - 1 );
        return new NOrder( k_ / ratio, v_ );
    }
References ZeroOrder::k_, NA, NOrder(), and v_.
getReactants()
unsigned int NOrder::getReactants (vector< unsigned int > & molIndex) const inline virtual
This function finds the reactant indices in the vector S. It returns the number of substrates found, which are the first entries in molIndex. The products are the remaining ones. Note that it does NOT find products for unidirectional reactions, which is a bit of a problem.
Implements RateTerm.
Definition at line 530 of file RateTerm.h.
    {
        molIndex = v_;
        return v_.size();
    }
References v_.
operator()()
double NOrder::operator() (const double * S) const inline virtual
Computes the rate. The argument is the molecule array.
Implements RateTerm.
Reimplemented in StochNOrder.
Definition at line 518 of file RateTerm.h.
    {
        double ret = k_;
        vector< unsigned int >::const_iterator i;
        for ( i = v_.begin(); i != v_.end(); i++)
        {
            assert(! std::isnan( S[ *i ] ) );
            ret *= S[ *i ];
        }
        return ret;
    }
References ZeroOrder::k_, and v_.
rescaleVolume()
void NOrder::rescaleVolume (short comptIndex, const vector< short > & compartmentLookup, double ratio) inline virtual
This is used to rescale the RateTerm kinetics when the compartment volume changes. This is needed because the kinetics are in extensive units, that is, mol numbers, rather than in intensive units like concentration. So when the volume changes the rate terms change. Each Rate term checks if any of its reactant molecules are affected, and if so, rescales. Ratio is newVol / oldVol
Implements RateTerm.
Definition at line 536 of file RateTerm.h.
    {
        for ( unsigned int i = 1; i < v_.size(); ++i )
        {
            if ( comptIndex == compartmentLookup[ v_[i] ] )
                k_ /= ratio;
        }
    }
References ZeroOrder::k_, and v_.
Member Data Documentation
v_
vector< unsigned int > NOrder::v_ protected
Definition at line 555 of file RateTerm.h.
Referenced by copyWithVolScaling(), StochNOrder::copyWithVolScaling(), getReactants(), NOrder(), operator()(), StochNOrder::operator()(), rescaleVolume(), and StochNOrder::StochNOrder().
The documentation for this class was generated from the following file:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/ksolve/RateTerm.h