MOOSE - Multiscale Object Oriented Simulation Environment: SrcFinfo Class Reference
SrcFinfo Class Reference abstract
#include <SrcFinfo.h>
Public Member Functions
bool addMsg (const Finfo *target, ObjId mid, Element *src) const
bool checkTarget (const Finfo *target) const
BindIndex getBindIndex () const
void registerFinfo (Cinfo *c)
virtual void sendBuffer (const Eref &e, double *buf) const =0
void setBindIndex (BindIndex b)
SrcFinfo (const string &name, const string &doc)
bool strGet (const Eref &tgt, const string &field, string &returnValue) const
bool strSet (const Eref &tgt, const string &field, const string &arg) const
~SrcFinfo ()
Public Member Functions inherited from Finfo
const string & docs () const
Returns documentation string.
Finfo (const string &name, const string &doc)
virtual vector< string > innerDest () const
virtual vector< string > innerSrc () const
const string & name () const
virtual void postCreationFunc (Id newId, Element *newElm) const
virtual string rttiType () const
virtual ~Finfo ()
Static Public Attributes
static const BindIndex BadBindIndex = 65535
Private Attributes
unsigned short bindIndex_
Additional Inherited Members
Static Public Member Functions inherited from Finfo
static const Cinfo * initCinfo ()
Detailed Description
This set of classes define Message Sources. Their main job is to supply a type-safe send operation, and to provide typechecking for it.
Definition at line 17 of file SrcFinfo.h.
Constructor & Destructor Documentation
SrcFinfo()
SrcFinfo::SrcFinfo (const string & name, const string & doc)
Definition at line 18 of file SrcFinfo.cpp.
    : Finfo( name, doc ), bindIndex_( BadBindIndex )
{ ; }
References BadBindIndex, bindIndex_, and Finfo::Finfo().
Referenced by SrcFinfo0::SrcFinfo0().
~SrcFinfo()
SrcFinfo::~SrcFinfo () inline
Definition at line 22 of file SrcFinfo.h.
{;}
Member Function Documentation
addMsg()
bool SrcFinfo::addMsg (const Finfo * target, ObjId mid, Element * src) const virtual
First checks that the target will work, then adds the Msg.
Reimplemented from Finfo.
Definition at line 50 of file SrcFinfo.cpp.
{
    const DestFinfo* d = dynamic_cast< const DestFinfo* >( target );
    if ( d ) {
        if ( d->getOpFunc()->checkFinfo( this ) ) {
            src->addMsgAndFunc( mid, d->getFid(), bindIndex_ );
            return 1;
        }
    }
    return 0;
}
References Element::addMsgAndFunc(), bindIndex_, OpFunc::checkFinfo(), DestFinfo::getFid(), and DestFinfo::getOpFunc().
Referenced by SharedFinfo::addMsg().
checkTarget()
bool SrcFinfo::checkTarget (const Finfo * target) const virtual
Checks that the target will work for this Msg.
Reimplemented from Finfo.
Definition at line 41 of file SrcFinfo.cpp.
{
    const DestFinfo* d = dynamic_cast< const DestFinfo* >( target );
    if ( d ) {
        return d->getOpFunc()->checkFinfo( this );
    }
    return 0;
}
References OpFunc::checkFinfo(), and DestFinfo::getOpFunc().
Referenced by SharedFinfo::checkTarget().
getBindIndex()
BindIndex SrcFinfo::getBindIndex () const
Definition at line 28 of file SrcFinfo.cpp.
{
    // Treat this assertion as a warning that the SrcFinfo is being used
    // without initialization.
    assert( bindIndex_ != BadBindIndex );
    return bindIndex_;
}
References BadBindIndex, and bindIndex_.
Referenced by Clock::buildTicks(), Neutral::child(), Neutral::children(), convertConcToNumRateUsingVol(), Element::getMsgTargetAndFunctions(), Element::getMsgTargets(), EnzBase::getNumPrd(), Reac::getNumPrd(), EnzBase::getNumSub(), Reac::getNumSub(), Element::getOutputs(), getReactantVols(), innerCopyMsgs(), SrcFinfo0::send(), SrcFinfo2< T1, T2 >::send(), SrcFinfo3< T1, T2, T3 >::send(), SrcFinfo4< T1, T2, T3, T4 >::send(), SrcFinfo5< T1, T2, T3, T4, T5 >::send(), SrcFinfo6< T1, T2, T3, T4, T5, T6 >::send(), SrcFinfo1< T >::send(), SrcFinfo2< T1, T2 >::sendTo(), SrcFinfo1< T >::sendTo(), SrcFinfo1< T >::sendVec(), Element::showFields(), Element::showMsg(), Cinfo::srcFinfoName(), testMsgField(), testMsgSrcDestFields(), testSendMsg(), and NeuroMesh::transmitSpineInfo().
registerFinfo()
void SrcFinfo::registerFinfo (Cinfo * c) virtual
Returns string-ified form to handle template expectations for name field string getName() const; Assign function Ids, bindIndex and so on.
Implements Finfo.
Definition at line 22 of file SrcFinfo.cpp.
{
    bindIndex_ = c->registerBindIndex();
}
References bindIndex_, and Cinfo::registerBindIndex().
sendBuffer()
virtual void SrcFinfo::sendBuffer (const Eref & e, double * buf) const pure virtual
Sends contents of buffer on to msg targets Buffer has a header with the TgtInfo.
Implemented in SrcFinfo0, SrcFinfo1< T >, SrcFinfo2< T1, T2 >, SrcFinfo3< T1, T2, T3 >, SrcFinfo4< T1, T2, T3, T4 >, SrcFinfo5< T1, T2, T3, T4, T5 >, and SrcFinfo6< T1, T2, T3, T4, T5, T6 >.
setBindIndex()
void SrcFinfo::setBindIndex (BindIndex b)
Definition at line 36 of file SrcFinfo.cpp.
{
    bindIndex_ = b;
}
References bindIndex_.
Referenced by testMsgField(), and testSendMsg().
strGet()
bool SrcFinfo::strGet (const Eref & tgt, const string & field, string & returnValue) const inline virtual
Function to return value of field into a string argument. Returns true on success. Normally called only from SetGet::strGet.
Implements Finfo.
Definition at line 33 of file SrcFinfo.h.
{
            return 0; // always fails
        }
strSet()
bool SrcFinfo::strSet (const Eref & tgt, const string & field, const string & arg) const inline virtual
Function to set this field using a string argument. Returns true on success. Normally called only from SetGet::strSet.
Implements Finfo.
Definition at line 28 of file SrcFinfo.h.
{
            return 0; // always fails
        }
Member Data Documentation
BadBindIndex
const BindIndex SrcFinfo::BadBindIndex = 65535 static
This set of classes define Message Sources. Their main job is to supply a type-safe send operation, and to provide typechecking for it.
Definition at line 58 of file SrcFinfo.h.
Referenced by getBindIndex(), and SrcFinfo().
bindIndex_
unsigned short SrcFinfo::bindIndex_ private
Index into the msgBinding_ vector.
Definition at line 63 of file SrcFinfo.h.
Referenced by addMsg(), getBindIndex(), registerFinfo(), setBindIndex(), and SrcFinfo().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/basecode/SrcFinfo.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/basecode/SrcFinfo.cpp