MOOSE - Multiscale Object Oriented Simulation Environment: moose::QIF Class Reference
moose::QIF Class Reference
#include <QIF.h>
Public Member Functions
double getA0 (const Eref &e) const
double getVCritical (const Eref &e) const
QIF ()
void setA0 (const Eref &e, double val)
void setVCritical (const Eref &e, double val)
void vProcess (const Eref &e, ProcPtr p)
void vReinit (const Eref &e, ProcPtr p)
virtual ~QIF ()
Public Member Functions inherited from moose::IntFireBase
void activation (double val)
double getLastEventTime (const Eref &e) const
double getRefractoryPeriod (const Eref &e) const
double getThresh (const Eref &e) const
double getVReset (const Eref &e) const
bool hasFired (const Eref &e) const
IntFireBase ()
void setRefractoryPeriod (const Eref &e, double val)
void setThresh (const Eref &e, double val)
void setVReset (const Eref &e, double val)
virtual ~IntFireBase ()
Public Member Functions inherited from moose::Compartment
void cable ()
Compartment ()
virtual double vGetCm (const Eref &e) const
virtual double vGetEm (const Eref &e) const
virtual double vGetIm (const Eref &e) const
virtual double vGetInitVm (const Eref &e) const
virtual double vGetInject (const Eref &e) const
virtual double vGetRa (const Eref &e) const
virtual double vGetRm (const Eref &e) const
virtual double vGetVm (const Eref &e) const
void vHandleAxial (double Vm)
void vHandleChannel (const Eref &e, double Gk, double Ek)
void vHandleRaxial (double Ra, double Vm)
void vInitProc (const Eref &e, ProcPtr p)
void vInitReinit (const Eref &e, ProcPtr p)
void vInjectMsg (const Eref &e, double current)
void vRandInject (const Eref &e, double prob, double current)
virtual void vSetCm (const Eref &e, double Cm)
virtual void vSetEm (const Eref &e, double Em)
virtual void vSetInitVm (const Eref &e, double initVm)
virtual void vSetInject (const Eref &e, double Inject)
virtual void vSetRa (const Eref &e, double Ra)
virtual void vSetRm (const Eref &e, double Rm)
virtual void vSetVm (const Eref &e, double Vm)
virtual ~Compartment ()
Public Member Functions inherited from moose::CompartmentBase
void cable ()
CompartmentBase ()
void displace (double dx, double dy, double dz)
Displaces compartment by specified distance vector.
double getCm (const Eref &e) const
vector< double > getCoords () const
double getDiameter () const
double getEm (const Eref &e) const
double getIm (const Eref &e) const
double getInitVm (const Eref &e) const
double getInject (const Eref &e) const
double getLength () const
double getRa (const Eref &e) const
double getRm (const Eref &e) const
double getVm (const Eref &e) const
double getX () const
double getX0 () const
double getY () const
double getY0 () const
double getZ () const
double getZ0 () const
void handleAxial (double Vm)
void handleChannel (const Eref &e, double Gk, double Ek)
void handleRaxial (double Ra, double Vm)
void initProc (const Eref &e, ProcPtr p)
void initReinit (const Eref &e, ProcPtr p)
void injectMsg (const Eref &e, double current)
void process (const Eref &e, ProcPtr p)
void randInject (const Eref &e, double prob, double current)
bool rangeWarning (const string &field, double value)
void reinit (const Eref &e, ProcPtr p)
void setCm (const Eref &e, double Cm)
void setCoords (vector< double > value)
void setDiameter (double diameter)
void setEm (const Eref &e, double Em)
void setGeomAndElec (const Eref &e, double length, double dia)
Scales electrical values along with setting length, dia.
void setInitVm (const Eref &e, double initVm)
void setInject (const Eref &e, double Inject)
void setLength (double length)
void setRa (const Eref &e, double Ra)
void setRm (const Eref &e, double Rm)
void setVm (const Eref &e, double Vm)
void setX (double value)
void setX0 (double value)
void setY (double value)
void setY0 (double value)
void setZ (double value)
void setZ0 (double value)
void updateLength ()
virtual void vSetSolver (const Eref &e, Id hsolve)
virtual ~CompartmentBase ()
Static Public Member Functions
static const Cinfo * initCinfo ()
Static Public Member Functions inherited from moose::IntFireBase
static const Cinfo * initCinfo ()
static SrcFinfo1< double > * spikeOut ()
Message src for outgoing spikes.
Static Public Member Functions inherited from moose::Compartment
static const Cinfo * initCinfo ()
Static Public Member Functions inherited from moose::CompartmentBase
static const Cinfo * initCinfo ()
static SrcFinfo1< double > * VmOut ()
static void zombify (Element *orig, const Cinfo *zClass, Id hsolve)
Private Attributes
double a0_
double vCritical_
Additional Inherited Members
Protected Attributes inherited from moose::IntFireBase
double activation_
bool fired_
double lastEvent_
double refractT_
double threshold_
double vReset_
Protected Attributes inherited from moose::Compartment
double A_
double B_
double Cm_
double Em_
double Im_
double initVm_
double inject_
double lastIm_
double Ra_
double Rm_
double sumInject_
double Vm_
Detailed Description
The Quadratic Integrate and Fire class sets up an integrate-and-fire compartment, with a qudratic sub threshold behaviour.
Definition at line 21 of file QIF.h.
Constructor & Destructor Documentation
QIF()
QIF::QIF ()
Definition at line 70 of file QIF.cpp.
{a0_ = 0.0;
vCritical_ = 0.0;}
References a0_, and vCritical_.
~QIF()
QIF::~QIF () virtual
Definition at line 74 of file QIF.cpp.
{;}
Member Function Documentation
getA0()
double QIF::getA0 (const Eref & e) const
Definition at line 139 of file QIF.cpp.
{
    return a0_;
}
References a0_.
Referenced by initCinfo().
getVCritical()
double QIF::getVCritical (const Eref & e) const
Definition at line 129 of file QIF.cpp.
{
    return vCritical_;
}
References vCritical_.
Referenced by initCinfo().
initCinfo()
const Cinfo * QIF::initCinfo () static
Initializes the class info.
Definition at line 19 of file QIF.cpp.
{
    static string doc[] =
    {
        "Name", "QIF",
        "Author", "Aditya Gilra",
        "Description", "Leaky Integrate-and-Fire neuron with Quadratic term in Vm."
        "Based on Spiking Neuron Models book by Gerstner and Kistler."
        "Rm*Cm * dVm/dt = a0*(Vm-Em)*(Vm-vCritical) + Rm*I"
    };
    static ElementValueFinfo< QIF, double > vCritical(
        "vCritical",
        "Critical voltage for spike initiation",
        &QIF::setVCritical,
        &QIF::getVCritical
    );
    static ElementValueFinfo< QIF, double > a0(
        "a0",
        "Parameter in Rm*Cm dVm/dt = a0*(Vm-Em)*(Vm-vCritical) + Rm*I, a0>0",
        &QIF::setA0,
        &QIF::getA0
    );
    static Finfo* QIFFinfos[] = {
        &vCritical,     // Value
        &a0             // Value
    };
    static Dinfo< QIF > dinfo;
    static Cinfo QIFCinfo(
                "QIF",
                IntFireBase::initCinfo(), // this is the initCinfo of the parent class
                QIFFinfos,
                sizeof( QIFFinfos ) / sizeof (Finfo*),
                &dinfo,
                doc,
                sizeof(doc)/sizeof(string)
    );
    return &QIFCinfo;
}
References Cinfo::Cinfo(), ElementValueFinfo< T, F >::ElementValueFinfo(), getA0(), getVCritical(), moose::IntFireBase::initCinfo(), setA0(), and setVCritical().
setA0()
void QIF::setA0 (const Eref & e, double val)
Definition at line 134 of file QIF.cpp.
{
    a0_ = val;
}
References a0_.
Referenced by initCinfo().
setVCritical()
void QIF::setVCritical (const Eref & e, double val)
Definition at line 124 of file QIF.cpp.
{
    vCritical_ = val;
}
References vCritical_.
Referenced by initCinfo().
vProcess()
void QIF::vProcess (const Eref & e, ProcPtr p) virtual
The process function does the object updating and sends out messages to channels, nernsts, and so on.
Implements moose::IntFireBase.
Definition at line 81 of file QIF.cpp.
{
    // fully taking over Compartment's vProcess due to quadratic term in Vm
    // we no longer care about A and B
    fired_ = false;
    if ( p->currTime < lastEvent_ + refractT_ ) {
        Vm_ = vReset_;
        sumInject_ = 0.0;
        VmOut()->send( e, Vm_ );
    } else {
        // activation can be a continous variable (graded synapse).
        // So integrate it at every time step, thus *dt.
        // For a delta-fn synapse, SynHandler-s divide by dt and send activation.
        // See: http://www.genesis-sim.org/GENESIS/Hyperdoc/Manual-26.html#synchan
        //          for this continuous definition of activation.
        Vm_ += activation_ * p->dt;
        activation_ = 0.0;
        if ( Vm_ > threshold_ ) {
            Vm_ = vReset_;
            lastEvent_ = p->currTime;
            fired_ = true;
            spikeOut()->send( e, p->currTime );
            VmOut()->send( e, Vm_ );
        } else {
            Vm_ += ( (inject_+sumInject_)
                    + a0_*(Vm_-Em_)*(Vm_-vCritical_)/Rm_ ) * p->dt / Cm_;
            lastIm_ = Im_;
            Im_ = 0.0;
            sumInject_ = 0.0;
            // Send out Vm to channels, SpikeGens, etc.
            VmOut()->send( e, Vm_ );
        }
    }
}
References a0_, moose::IntFireBase::activation_, moose::Compartment::Cm_, ProcInfo::currTime, ProcInfo::dt, moose::Compartment::Em_, moose::IntFireBase::fired_, moose::Compartment::Im_, moose::Compartment::inject_, moose::IntFireBase::lastEvent_, moose::Compartment::lastIm_, moose::IntFireBase::refractT_, moose::Compartment::Rm_, SrcFinfo1< T >::send(), moose::IntFireBase::spikeOut(), moose::Compartment::sumInject_, moose::IntFireBase::threshold_, vCritical_, moose::Compartment::Vm_, moose::CompartmentBase::VmOut(), and moose::IntFireBase::vReset_.
vReinit()
void QIF::vReinit (const Eref & e, ProcPtr p) virtual
The reinit function reinitializes all fields.
Implements moose::IntFireBase.
Definition at line 116 of file QIF.cpp.
{
    activation_ = 0.0;
    fired_ = false;
    lastEvent_ = -refractT_; // Allow it to fire right away.
    Compartment::vReinit( e, p );
}
References moose::IntFireBase::activation_, moose::IntFireBase::fired_, moose::IntFireBase::lastEvent_, moose::IntFireBase::refractT_, and moose::Compartment::vReinit().
Member Data Documentation
a0_
double moose::QIF::a0_ private
Definition at line 50 of file QIF.h.
Referenced by getA0(), QIF(), setA0(), and vProcess().
vCritical_
double moose::QIF::vCritical_ private
Definition at line 49 of file QIF.h.
Referenced by getVCritical(), QIF(), setVCritical(), and vProcess().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/intfire/QIF.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/intfire/QIF.cpp