MOOSE - Multiscale Object Oriented Simulation Environment: moose::IntFireBase Class Reference
moose::IntFireBase Class Reference abstract
#include <IntFireBase.h>
Public Member Functions
void activation (double val)
double getLastEventTime (const Eref &e) const
double getRefractoryPeriod (const Eref &e) const
double getThresh (const Eref &e) const
double getVReset (const Eref &e) const
bool hasFired (const Eref &e) const
IntFireBase ()
void setRefractoryPeriod (const Eref &e, double val)
void setThresh (const Eref &e, double val)
void setVReset (const Eref &e, double val)
virtual void vProcess (const Eref &e, ProcPtr p)=0
virtual void vReinit (const Eref &e, ProcPtr p)=0
virtual ~IntFireBase ()
Public Member Functions inherited from moose::Compartment
void cable ()
Compartment ()
virtual double vGetCm (const Eref &e) const
virtual double vGetEm (const Eref &e) const
virtual double vGetIm (const Eref &e) const
virtual double vGetInitVm (const Eref &e) const
virtual double vGetInject (const Eref &e) const
virtual double vGetRa (const Eref &e) const
virtual double vGetRm (const Eref &e) const
virtual double vGetVm (const Eref &e) const
void vHandleAxial (double Vm)
void vHandleChannel (const Eref &e, double Gk, double Ek)
void vHandleRaxial (double Ra, double Vm)
void vInitProc (const Eref &e, ProcPtr p)
void vInitReinit (const Eref &e, ProcPtr p)
void vInjectMsg (const Eref &e, double current)
void vRandInject (const Eref &e, double prob, double current)
virtual void vSetCm (const Eref &e, double Cm)
virtual void vSetEm (const Eref &e, double Em)
virtual void vSetInitVm (const Eref &e, double initVm)
virtual void vSetInject (const Eref &e, double Inject)
virtual void vSetRa (const Eref &e, double Ra)
virtual void vSetRm (const Eref &e, double Rm)
virtual void vSetVm (const Eref &e, double Vm)
virtual ~Compartment ()
Public Member Functions inherited from moose::CompartmentBase
void cable ()
CompartmentBase ()
void displace (double dx, double dy, double dz)
Displaces compartment by specified distance vector.
double getCm (const Eref &e) const
vector< double > getCoords () const
double getDiameter () const
double getEm (const Eref &e) const
double getIm (const Eref &e) const
double getInitVm (const Eref &e) const
double getInject (const Eref &e) const
double getLength () const
double getRa (const Eref &e) const
double getRm (const Eref &e) const
double getVm (const Eref &e) const
double getX () const
double getX0 () const
double getY () const
double getY0 () const
double getZ () const
double getZ0 () const
void handleAxial (double Vm)
void handleChannel (const Eref &e, double Gk, double Ek)
void handleRaxial (double Ra, double Vm)
void initProc (const Eref &e, ProcPtr p)
void initReinit (const Eref &e, ProcPtr p)
void injectMsg (const Eref &e, double current)
void process (const Eref &e, ProcPtr p)
void randInject (const Eref &e, double prob, double current)
bool rangeWarning (const string &field, double value)
void reinit (const Eref &e, ProcPtr p)
void setCm (const Eref &e, double Cm)
void setCoords (vector< double > value)
void setDiameter (double diameter)
void setEm (const Eref &e, double Em)
void setGeomAndElec (const Eref &e, double length, double dia)
Scales electrical values along with setting length, dia.
void setInitVm (const Eref &e, double initVm)
void setInject (const Eref &e, double Inject)
void setLength (double length)
void setRa (const Eref &e, double Ra)
void setRm (const Eref &e, double Rm)
void setVm (const Eref &e, double Vm)
void setX (double value)
void setX0 (double value)
void setY (double value)
void setY0 (double value)
void setZ (double value)
void setZ0 (double value)
void updateLength ()
virtual void vSetSolver (const Eref &e, Id hsolve)
virtual ~CompartmentBase ()
Static Public Member Functions
static const Cinfo * initCinfo ()
static SrcFinfo1< double > * spikeOut ()
Message src for outgoing spikes.
Static Public Member Functions inherited from moose::Compartment
static const Cinfo * initCinfo ()
Static Public Member Functions inherited from moose::CompartmentBase
static const Cinfo * initCinfo ()
static SrcFinfo1< double > * VmOut ()
static void zombify (Element *orig, const Cinfo *zClass, Id hsolve)
Protected Attributes
double activation_
bool fired_
double lastEvent_
double refractT_
double threshold_
double vReset_
Protected Attributes inherited from moose::Compartment
double A_
double B_
double Cm_
double Em_
double Im_
double initVm_
double inject_
double lastIm_
double Ra_
double Rm_
double sumInject_
double Vm_
Detailed Description
The IntFire class sets up an integrate-and-fire compartment.
Definition at line 19 of file IntFireBase.h.
Constructor & Destructor Documentation
IntFireBase()
IntFireBase::IntFireBase ()
Definition at line 111 of file IntFireBase.cpp.
    :
    threshold_( 0.0 ),
    vReset_( 0.0 ),
    activation_( 0.0 ),
    refractT_( 0.0 ),
    lastEvent_( 0.0 ),
    fired_( false )
{;}
References activation_, fired_, lastEvent_, refractT_, threshold_, and vReset_.
~IntFireBase()
IntFireBase::~IntFireBase () virtual
Definition at line 121 of file IntFireBase.cpp.
{
    ;
}
Member Function Documentation
activation()
void IntFireBase::activation (double val)
activation handles information coming from the SynHandler to the intFire.
Definition at line 171 of file IntFireBase.cpp.
{
    activation_ += v;
}
References activation_.
Referenced by initCinfo().
getLastEventTime()
double IntFireBase::getLastEventTime (const Eref & e) const
Definition at line 157 of file IntFireBase.cpp.
{
    return lastEvent_;
}
References lastEvent_.
Referenced by initCinfo().
getRefractoryPeriod()
double IntFireBase::getRefractoryPeriod (const Eref & e) const
Definition at line 152 of file IntFireBase.cpp.
{
    return refractT_;
}
References refractT_.
Referenced by initCinfo().
getThresh()
double IntFireBase::getThresh (const Eref & e) const
Definition at line 132 of file IntFireBase.cpp.
{
    return threshold_;
}
References threshold_.
Referenced by initCinfo().
getVReset()
double IntFireBase::getVReset (const Eref & e) const
Definition at line 142 of file IntFireBase.cpp.
{
    return vReset_;
}
References vReset_.
Referenced by initCinfo().
hasFired()
bool IntFireBase::hasFired (const Eref & e) const
Definition at line 162 of file IntFireBase.cpp.
{
    return fired_;
}
References fired_.
Referenced by initCinfo().
initCinfo()
const Cinfo * IntFireBase::initCinfo () static
Initializes the class info.
Definition at line 27 of file IntFireBase.cpp.
{
    // Field Definitions
    static ElementValueFinfo< IntFireBase, double > thresh(
        "thresh",
        "firing threshold",
        &IntFireBase::setThresh,
        &IntFireBase::getThresh
    );
    static ElementValueFinfo< IntFireBase, double > vReset(
        "vReset",
        "voltage is set to vReset after firing",
        &IntFireBase::setVReset,
        &IntFireBase::getVReset
    );
    static ElementValueFinfo< IntFireBase, double > refractoryPeriod(
        "refractoryPeriod",
        "Minimum time between successive spikes",
        &IntFireBase::setRefractoryPeriod,
        &IntFireBase::getRefractoryPeriod
    );
    static ReadOnlyElementValueFinfo< IntFireBase, double > lastEventTime(
        "lastEventTime",
        "Timestamp of last firing.",
        &IntFireBase::getLastEventTime
    );
    static ReadOnlyElementValueFinfo< IntFireBase, bool > hasFired(
        "hasFired",
        "The object has fired within the last timestep",
        &IntFireBase::hasFired
    );
    // MsgDest Definitions
    static DestFinfo activation(
        "activation",
        "Handles value of synaptic activation arriving on this object",
        new OpFunc1< IntFireBase, double >( &IntFireBase::activation ));
    static Finfo* intFireFinfos[] =
    {
        &thresh,                // Value
        &vReset,                // Value
        &refractoryPeriod,      // Value
        &hasFired,              // ReadOnlyValue
        &lastEventTime,         // ReadOnlyValue
        &activation,            // DestFinfo
        IntFireBase::spikeOut() // MsgSrc
    };
    static string doc[] =
    {
        "Name", "IntFireBase",
        "Author", "Upi Bhalla",
        "Description", "Base class for Integrate-and-fire compartment.",
    };
    static ZeroSizeDinfo< int > dinfo;
    static Cinfo intFireBaseCinfo(
        "IntFireBase",
        Compartment::initCinfo(),
        intFireFinfos,
        sizeof( intFireFinfos ) / sizeof (Finfo*),
        &dinfo,
        doc,
        sizeof(doc)/sizeof(string)
    );
    return &intFireBaseCinfo;
}
References activation(), Cinfo::Cinfo(), DestFinfo::DestFinfo(), ElementValueFinfo< T, F >::ElementValueFinfo(), getLastEventTime(), getRefractoryPeriod(), getThresh(), getVReset(), hasFired(), moose::Compartment::initCinfo(), OpFunc1< T, A >::OpFunc1(), ReadOnlyElementValueFinfo< T, F >::ReadOnlyElementValueFinfo(), setRefractoryPeriod(), setThresh(), setVReset(), and spikeOut().
Referenced by moose::AdThreshIF::initCinfo(), moose::ExIF::initCinfo(), moose::IzhIF::initCinfo(), moose::LIF::initCinfo(), and moose::QIF::initCinfo().
setRefractoryPeriod()
void IntFireBase::setRefractoryPeriod (const Eref & e, double val)
Definition at line 147 of file IntFireBase.cpp.
{
    refractT_ = val;
}
References refractT_.
Referenced by initCinfo().
setThresh()
void IntFireBase::setThresh (const Eref & e, double val)
Definition at line 127 of file IntFireBase.cpp.
{
    threshold_ = val;
}
References threshold_.
Referenced by initCinfo().
setVReset()
void IntFireBase::setVReset (const Eref & e, double val)
Definition at line 137 of file IntFireBase.cpp.
{
    vReset_ = val;
}
References vReset_.
Referenced by initCinfo().
spikeOut()
SrcFinfo1< double > * IntFireBase::spikeOut () static
Message src for outgoing spikes.
Definition at line 17 of file IntFireBase.cpp.
{
    static SrcFinfo1< double > spikeOut(
        "spikeOut",
        "Sends out spike events. The argument is the timestamp of "
        "the spike. "
    );
    return &spikeOut;
}
References SrcFinfo1< T >::SrcFinfo1().
Referenced by initCinfo(), moose::AdExIF::vProcess(), moose::AdThreshIF::vProcess(), moose::ExIF::vProcess(), moose::IzhIF::vProcess(), moose::LIF::vProcess(), and moose::QIF::vProcess().
vProcess()
virtual void moose::IntFireBase::vProcess (const Eref & e, ProcPtr p) pure virtual
The process function does the object updating and sends out messages to channels, nernsts, and so on.
Reimplemented from moose::Compartment.
Implemented in moose::AdExIF, moose::AdThreshIF, moose::ExIF, moose::IzhIF, moose::LIF, and moose::QIF.
vReinit()
virtual void moose::IntFireBase::vReinit (const Eref & e, ProcPtr p) pure virtual
The reinit function reinitializes all fields.
Reimplemented from moose::Compartment.
Implemented in moose::AdExIF, moose::AdThreshIF, moose::ExIF, moose::IzhIF, moose::LIF, and moose::QIF.
Member Data Documentation
activation_
double moose::IntFireBase::activation_ protected
Definition at line 63 of file IntFireBase.h.
Referenced by activation(), IntFireBase(), moose::AdExIF::vProcess(), moose::AdThreshIF::vProcess(), moose::ExIF::vProcess(), moose::IzhIF::vProcess(), moose::LIF::vProcess(), moose::QIF::vProcess(), moose::AdExIF::vReinit(), moose::AdThreshIF::vReinit(), moose::ExIF::vReinit(), moose::IzhIF::vReinit(), moose::LIF::vReinit(), and moose::QIF::vReinit().
fired_
bool moose::IntFireBase::fired_ protected
Definition at line 66 of file IntFireBase.h.
Referenced by hasFired(), IntFireBase(), moose::AdExIF::vProcess(), moose::AdThreshIF::vProcess(), moose::ExIF::vProcess(), moose::IzhIF::vProcess(), moose::LIF::vProcess(), moose::QIF::vProcess(), moose::AdExIF::vReinit(), moose::AdThreshIF::vReinit(), moose::ExIF::vReinit(), moose::IzhIF::vReinit(), moose::LIF::vReinit(), and moose::QIF::vReinit().
lastEvent_
double moose::IntFireBase::lastEvent_ protected
Definition at line 65 of file IntFireBase.h.
Referenced by getLastEventTime(), IntFireBase(), moose::AdExIF::vProcess(), moose::AdThreshIF::vProcess(), moose::ExIF::vProcess(), moose::IzhIF::vProcess(), moose::LIF::vProcess(), moose::QIF::vProcess(), moose::AdExIF::vReinit(), moose::AdThreshIF::vReinit(), moose::ExIF::vReinit(), moose::IzhIF::vReinit(), moose::LIF::vReinit(), and moose::QIF::vReinit().
refractT_
double moose::IntFireBase::refractT_ protected
Definition at line 64 of file IntFireBase.h.
Referenced by getRefractoryPeriod(), IntFireBase(), setRefractoryPeriod(), moose::AdExIF::vProcess(), moose::AdThreshIF::vProcess(), moose::ExIF::vProcess(), moose::IzhIF::vProcess(), moose::LIF::vProcess(), moose::QIF::vProcess(), moose::AdExIF::vReinit(), moose::AdThreshIF::vReinit(), moose::ExIF::vReinit(), moose::IzhIF::vReinit(), moose::LIF::vReinit(), and moose::QIF::vReinit().
threshold_
double moose::IntFireBase::threshold_ protected
Definition at line 61 of file IntFireBase.h.
Referenced by getThresh(), IntFireBase(), setThresh(), moose::AdExIF::vProcess(), moose::AdThreshIF::vProcess(), moose::ExIF::vProcess(), moose::LIF::vProcess(), and moose::QIF::vProcess().
vReset_
double moose::IntFireBase::vReset_ protected
Definition at line 62 of file IntFireBase.h.
Referenced by getVReset(), IntFireBase(), setVReset(), moose::AdExIF::vProcess(), moose::AdThreshIF::vProcess(), moose::ExIF::vProcess(), moose::IzhIF::vProcess(), moose::LIF::vProcess(), and moose::QIF::vProcess().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/intfire/IntFireBase.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/intfire/IntFireBase.cpp