MOOSE - Multiscale Object Oriented Simulation Environment: DifShellBase Class Reference
DifShellBase Class Reference abstract
#include <DifShellBase.h>
Public Member Functions
void buffer (const Eref &e, double kf, double kb, double bFree, double bBound)
DifShellBase ()
void eqTauPump (const Eref &e, double kP)
void fInflux (const Eref &e, double I, double fraction)
void fluxFromIn (const Eref &e, double innerC, double innerThickness)
void fluxFromOut (const Eref &e, double outerC, double outerThickness)
void fOutflux (const Eref &e, double I, double fraction)
double getC (const Eref &e) const
double getCeq (const Eref &e) const
double getD (const Eref &e) const
double getDiameter (const Eref &e) const
double getInnerArea (const Eref &e) const
double getLeak (const Eref &e) const
double getLength (const Eref &e) const
double getOuterArea (const Eref &e) const
unsigned int getShapeMode (const Eref &e) const
double getThickness (const Eref &e) const
double getValence (const Eref &e) const
double getVolume (const Eref &e) const
void hillPump (const Eref &e, double vMax, double Kd, unsigned int hill)
void influx (const Eref &e, double I)
void mmPump (const Eref &e, double vMax, double Kd)
void outflux (const Eref &e, double I)
void process (const Eref &e, ProcPtr p)
void reinit (const Eref &e, ProcPtr p)
void setC (const Eref &e, double C)
void setCeq (const Eref &e, double Ceq)
void setD (const Eref &e, double D)
void setDiameter (const Eref &e, double diameter)
void setInnerArea (const Eref &e, double innerArea)
void setLeak (const Eref &e, double leak)
void setLength (const Eref &e, double length)
void setOuterArea (const Eref &e, double outerArea)
void setShapeMode (const Eref &e, unsigned int shapeMode)
void setThickness (const Eref &e, double thickness)
void setValence (const Eref &e, double valence)
void setVolume (const Eref &e, double volume)
void storeInflux (const Eref &e, double flux)
void storeOutflux (const Eref &e, double flux)
void tauPump (const Eref &e, double kP, double Ceq)
virtual void vBuffer (const Eref &e, double kf, double kb, double bFree, double bBound)=0
virtual void vEqTauPump (const Eref &e, double kP)=0
virtual void vFInflux (const Eref &e, double I, double fraction)=0
virtual void vFluxFromIn (const Eref &e, double innerC, double innerThickness)=0
virtual void vFluxFromOut (const Eref &e, double outerC, double outerThickness)=0
virtual void vFOutflux (const Eref &e, double I, double fraction)=0
virtual double vGetC (const Eref &e) const =0
virtual double vGetCeq (const Eref &e) const =0
virtual double vGetD (const Eref &e) const =0
virtual double vGetDiameter (const Eref &e) const =0
virtual double vGetInnerArea (const Eref &e) const =0
virtual double vGetLeak (const Eref &e) const =0
virtual double vGetLength (const Eref &e) const =0
virtual double vGetOuterArea (const Eref &e) const =0
virtual unsigned int vGetShapeMode (const Eref &e) const =0
virtual double vGetThickness (const Eref &e) const =0
virtual double vGetValence (const Eref &e) const =0
virtual double vGetVolume (const Eref &e) const =0
virtual void vHillPump (const Eref &e, double vMax, double Kd, unsigned int hill)=0
virtual void vInflux (const Eref &e, double I)=0
virtual void vMMPump (const Eref &e, double vMax, double Kd)=0
virtual void vOutflux (const Eref &e, double I)=0
virtual void vProcess (const Eref &e, ProcPtr p)=0
virtual void vReinit (const Eref &e, ProcPtr p)=0
virtual void vSetC (const Eref &e, double C)=0
virtual void vSetCeq (const Eref &e, double Ceq)=0
virtual void vSetD (const Eref &e, double D)=0
virtual void vSetDiameter (const Eref &e, double diameter)=0
virtual void vSetInnerArea (const Eref &e, double innerArea)=0
virtual void vSetLeak (const Eref &e, double leak)=0
virtual void vSetLength (const Eref &e, double length)=0
virtual void vSetOuterArea (const Eref &e, double outerArea)=0
virtual void vSetShapeMode (const Eref &e, unsigned int shapeMode)=0
virtual void vSetThickness (const Eref &e, double thickness)=0
virtual void vSetValence (const Eref &e, double valence)=0
virtual void vSetVolume (const Eref &e, double volume)=0
virtual void vStoreInflux (const Eref &e, double flux)=0
virtual void vStoreOutflux (const Eref &e, double flux)=0
virtual void vTauPump (const Eref &e, double kP, double Ceq)=0
Static Public Member Functions
static SrcFinfo1< double > * concentrationOut ()
static const Cinfo * initCinfo ()
static SrcFinfo2< double, double > * innerDifSourceOut ()
static SrcFinfo2< double, double > * outerDifSourceOut ()
Detailed Description
Definition at line 15 of file DifShellBase.h.
Constructor & Destructor Documentation
DifShellBase()
DifShellBase::DifShellBase ()
Definition at line 230 of file DifShellBase.cpp.
{ ; }
Member Function Documentation
buffer()
void DifShellBase::buffer (const Eref & e, double kf, double kb, double bFree, double bBound)
Definition at line 366 of file DifShellBase.cpp.
{
  vBuffer( e, kf, kb, bFree, bBound );
}
References vBuffer().
Referenced by initCinfo().
concentrationOut()
SrcFinfo1< double > * DifShellBase::concentrationOut () static
Definition at line 15 of file DifShellBase.cpp.
{
  static SrcFinfo1< double > concentrationOut("concentrationOut",
                          "Sends out concentration");
  return &concentrationOut;
}
References SrcFinfo1< T >::SrcFinfo1().
Referenced by initCinfo(), DifShell::vProcess(), and DifShell::vReinit().
eqTauPump()
void DifShellBase::eqTauPump (const Eref & e, double kP)
Definition at line 436 of file DifShellBase.cpp.
{
  vEqTauPump(e, kP );
}
References vEqTauPump().
Referenced by initCinfo().
fInflux()
void DifShellBase::fInflux (const Eref & e, double I, double fraction)
Definition at line 403 of file DifShellBase.cpp.
{
  vFInflux(e, I, fraction );
}
References vFInflux().
Referenced by initCinfo().
fluxFromIn()
void DifShellBase::fluxFromIn (const Eref & e, double innerC, double innerThickness)
Definition at line 383 of file DifShellBase.cpp.
{
  vFluxFromIn( e, innerC, innerThickness );
}
References vFluxFromIn().
Referenced by initCinfo().
fluxFromOut()
void DifShellBase::fluxFromOut (const Eref & e, double outerC, double outerThickness)
Definition at line 376 of file DifShellBase.cpp.
{
  vFluxFromOut(e, outerC, outerThickness );
}
References vFluxFromOut().
Referenced by initCinfo().
fOutflux()
void DifShellBase::fOutflux (const Eref & e, double I, double fraction)
Definition at line 410 of file DifShellBase.cpp.
{
  vFOutflux(e, I, fraction );
}
References vFOutflux().
Referenced by initCinfo().
getC()
double DifShellBase::getC (const Eref & e) const
Definition at line 237 of file DifShellBase.cpp.
{
  return vGetC(e);
}
References vGetC().
Referenced by initCinfo().
getCeq()
double DifShellBase::getCeq (const Eref & e) const
Definition at line 247 of file DifShellBase.cpp.
{
  return vGetCeq(e);
}
References vGetCeq().
Referenced by initCinfo().
getD()
double DifShellBase::getD (const Eref & e) const
Definition at line 257 of file DifShellBase.cpp.
{
  return vGetD(e);
}
References vGetD().
Referenced by initCinfo().
getDiameter()
double DifShellBase::getDiameter (const Eref & e) const
Definition at line 307 of file DifShellBase.cpp.
{
  return vGetDiameter(e);
}
References vGetDiameter().
Referenced by initCinfo().
getInnerArea()
double DifShellBase::getInnerArea (const Eref & e) const
Definition at line 347 of file DifShellBase.cpp.
{
  return vGetInnerArea(e);
}
References vGetInnerArea().
Referenced by initCinfo().
getLeak()
double DifShellBase::getLeak (const Eref & e) const
Definition at line 277 of file DifShellBase.cpp.
{
  return vGetLeak(e);
}
References vGetLeak().
Referenced by initCinfo().
getLength()
double DifShellBase::getLength (const Eref & e) const
Definition at line 297 of file DifShellBase.cpp.
{
  return vGetLength(e);
}
References vGetLength().
Referenced by initCinfo().
getOuterArea()
double DifShellBase::getOuterArea (const Eref & e) const
Definition at line 337 of file DifShellBase.cpp.
{
  return vGetOuterArea(e);
}
References vGetOuterArea().
Referenced by initCinfo().
getShapeMode()
unsigned int DifShellBase::getShapeMode (const Eref & e) const
Definition at line 287 of file DifShellBase.cpp.
{
  return vGetShapeMode(e);
}
References vGetShapeMode().
Referenced by initCinfo().
getThickness()
double DifShellBase::getThickness (const Eref & e) const
Definition at line 317 of file DifShellBase.cpp.
{
  return vGetThickness(e);
}
References vGetThickness().
Referenced by initCinfo().
getValence()
double DifShellBase::getValence (const Eref & e) const
Definition at line 267 of file DifShellBase.cpp.
{
  return vGetValence(e);
}
References vGetValence().
Referenced by initCinfo().
getVolume()
double DifShellBase::getVolume (const Eref & e) const
Definition at line 327 of file DifShellBase.cpp.
{
  return vGetVolume(e);
}
References vGetVolume().
Referenced by initCinfo().
hillPump()
void DifShellBase::hillPump (const Eref & e, double vMax, double Kd, unsigned int hill)
Definition at line 449 of file DifShellBase.cpp.
{
  vHillPump(e, vMax, Kd, hill );
}
References vHillPump().
Referenced by initCinfo().
influx()
void DifShellBase::influx (const Eref & e, double I)
Definition at line 391 of file DifShellBase.cpp.
{
  vInflux( e, I );
}
References vInflux().
Referenced by initCinfo().
initCinfo()
const Cinfo * DifShellBase::initCinfo () static
Definition at line 34 of file DifShellBase.cpp.
{
  static DestFinfo process( "process",
                "Handles process call",
                new ProcOpFunc< DifShellBase>(&DifShellBase::process ) );
  static DestFinfo reinit( "reinit",
               "Reinit happens only in stage 0",
               new ProcOpFunc< DifShellBase>( &DifShellBase::reinit ));
  static Finfo* processShared[] = {
    &process, &reinit
  };
  static SharedFinfo proc(
              "proc",
              "Shared message to receive Process message from scheduler",
              processShared, sizeof( processShared ) / sizeof( Finfo* ));
  static DestFinfo reaction( "reaction",
                 "Here the DifShell receives reaction rates (forward and backward), and concentrations for the "
                 "free-buffer and bound-buffer molecules.",
                 new EpFunc4< DifShellBase, double, double, double, double >( &DifShellBase::buffer ));
  static Finfo* bufferShared[] = {
    DifShellBase::concentrationOut(), &reaction
  };
  static SharedFinfo buffer( "buffer",
                 "This is a shared message from a DifShell to a Buffer (FixBuffer or DifBuffer). " ,
                 bufferShared,
                 sizeof( bufferShared ) / sizeof( Finfo* ));
  static DestFinfo fluxFromOut( "fluxFromOut",
                "Destination message",
                new EpFunc2< DifShellBase, double, double > ( &DifShellBase::fluxFromOut ));
  static Finfo* innerDifShared[] = {
    &fluxFromOut,  DifShellBase::innerDifSourceOut(),
  };
  static SharedFinfo innerDif( "innerDif",
                   "This shared message (and the next) is between DifShells: adjoining shells exchange information to "
                   "find out the flux between them. "
                   "Using this message, an inner shell sends to, and receives from its outer shell." ,
                   innerDifShared,
                   sizeof( innerDifShared ) / sizeof( Finfo* ));
  static DestFinfo fluxFromIn( "fluxFromIn", "",
                   new EpFunc2< DifShellBase, double, double> ( &DifShellBase::fluxFromIn ) );
  static Finfo* outerDifShared[] = {
    &fluxFromIn,  DifShellBase::outerDifSourceOut(),
  };
  static  SharedFinfo outerDif( "outerDif",
                "Using this message, an outer shell sends to, and receives from its inner shell." ,
                outerDifShared,
                sizeof( outerDifShared ) / sizeof( Finfo* ));
  static ElementValueFinfo< DifShellBase, double> C( "C",
                             "Concentration C",// is computed by the DifShell",
                             &DifShellBase::setC,
                             &DifShellBase::getC);
  static ElementValueFinfo< DifShellBase, double> Ceq( "Ceq", "",
                               &DifShellBase::setCeq,
                               &DifShellBase::getCeq);
  static ElementValueFinfo< DifShellBase, double> D( "D", "",
                             &DifShellBase::setD,
                             &DifShellBase::getD);
  static ElementValueFinfo< DifShellBase, double> valence( "valence", "",
                               &DifShellBase::setValence,
                               &DifShellBase::getValence);
  static ElementValueFinfo< DifShellBase, double> leak( "leak", "",
                            &DifShellBase::setLeak,
                            &DifShellBase::getLeak);
  static ElementValueFinfo< DifShellBase, unsigned int> shapeMode( "shapeMode", "",
                                   &DifShellBase::setShapeMode,
                                   &DifShellBase::getShapeMode);
  static ElementValueFinfo< DifShellBase, double> length( "length", "",
                              &DifShellBase::setLength,
                              &DifShellBase::getLength);
  static ElementValueFinfo< DifShellBase, double> diameter( "diameter", "",
                                &DifShellBase::setDiameter,
                                &DifShellBase::getDiameter );
  static ElementValueFinfo< DifShellBase, double> thickness( "thickness", "",
                                 &DifShellBase::setThickness,
                                 &DifShellBase::getThickness );
  static ElementValueFinfo< DifShellBase, double> volume( "volume", "",
                              &DifShellBase::setVolume,
                              &DifShellBase::getVolume );
  static ElementValueFinfo< DifShellBase, double> outerArea( "outerArea", "",
                                 &DifShellBase::setOuterArea,
                                 &DifShellBase::getOuterArea);
  static ElementValueFinfo< DifShellBase, double> innerArea( "innerArea", "",
                                 &DifShellBase::setInnerArea,
                                 &DifShellBase::getInnerArea );
  static DestFinfo mmPump( "mmPump", "Here DifShell receives pump outflux",
               new EpFunc2< DifShellBase, double, double >( &DifShellBase::mmPump ) );
  static DestFinfo influx( "influx", "",
               new EpFunc1< DifShellBase, double > (&DifShellBase::influx ));
  static DestFinfo outflux( "outflux", "",
                new EpFunc1< DifShellBase, double >( &DifShellBase::influx ));
  static DestFinfo fInflux( "fInflux", "",
                new EpFunc2< DifShellBase, double, double >( &DifShellBase::fInflux ));
  static DestFinfo fOutflux( "fOutflux", "",
                 new EpFunc2< DifShellBase, double, double> (&DifShellBase::fOutflux ));
  static DestFinfo storeInflux( "storeInflux", "",
                new EpFunc1< DifShellBase, double >( &DifShellBase::storeInflux ) );
  static DestFinfo storeOutflux( "storeOutflux", "",
                 new EpFunc1< DifShellBase, double > ( &DifShellBase::storeOutflux ) );
  static DestFinfo tauPump( "tauPump","",
                new EpFunc2< DifShellBase, double, double >( &DifShellBase::tauPump ) );
  static DestFinfo eqTauPump( "eqTauPump", "",
                  new EpFunc1< DifShellBase, double >( &DifShellBase::eqTauPump ) );
  static DestFinfo hillPump( "hillPump", "",
                 new EpFunc3< DifShellBase, double, double, unsigned int >( &DifShellBase::hillPump ) );
  static Finfo* difShellBaseFinfos[] = {
    // Field definitions
    &C,
    &Ceq,
    &D,
    &valence,
    &leak,
    &shapeMode,
    &length,
    &diameter,
    &thickness,
    &volume,
    &outerArea,
    &innerArea,
    // MsgSrc definitions
    // SharedFinfo definitions
    &proc,
    &buffer,
    concentrationOut(),
    innerDifSourceOut(),
    outerDifSourceOut(),
    &innerDif,
    &outerDif,
    // DestFinfo definitions
    &influx,
    &outflux,
    &fInflux,
    &fOutflux,
    &storeInflux,
    &storeOutflux,
    &tauPump,
    &eqTauPump,
    &mmPump,
    &hillPump,
  };
  static string doc[] =
    {
      "Name", "DifShellBase",
      "Author", "Niraj Dudani. Ported to async13 by Subhasis Ray/Asia Jedrzejewska-Szmek",
      "Description", "DifShell object: Models diffusion of an ion (typically calcium) within an "
      "electric compartment. A DifShell is an iso-concentration region with respect to "
      "the ion. Adjoining DifShells exchange flux of this ion, and also keep track of "
      "changes in concentration due to pumping, buffering and channel currents, by "
      "talking to the appropriate objects.",
    };
  static ZeroSizeDinfo< int > dinfo;
  //static Dinfo< DifShellBase> dinfo;
  static Cinfo difShellBaseCinfo(
                 "DifShellBase",
                 Neutral::initCinfo(),
                 difShellBaseFinfos,
                 sizeof( difShellBaseFinfos ) / sizeof( Finfo* ),
                 &dinfo,
                 doc,
                 sizeof( doc ) / sizeof( string ));
  return &difShellBaseCinfo;
}
References buffer(), Cinfo::Cinfo(), concentrationOut(), DestFinfo::DestFinfo(), ElementValueFinfo< T, F >::ElementValueFinfo(), EpFunc1< T, A >::EpFunc1(), EpFunc2< T, A1, A2 >::EpFunc2(), EpFunc3< T, A1, A2, A3 >::EpFunc3(), EpFunc4< T, A1, A2, A3, A4 >::EpFunc4(), eqTauPump(), fInflux(), fluxFromIn(), fluxFromOut(), fOutflux(), getC(), getCeq(), getD(), getDiameter(), getInnerArea(), getLeak(), getLength(), getOuterArea(), getShapeMode(), getThickness(), getValence(), getVolume(), hillPump(), influx(), Neutral::initCinfo(), innerDifSourceOut(), mmPump(), outerDifSourceOut(), process(), ProcOpFunc< T >::ProcOpFunc(), reinit(), setC(), setCeq(), setD(), setDiameter(), setInnerArea(), setLeak(), setLength(), setOuterArea(), setShapeMode(), setThickness(), setValence(), setVolume(), SharedFinfo::SharedFinfo(), storeInflux(), storeOutflux(), and tauPump().
Referenced by DifShell::initCinfo().
innerDifSourceOut()
SrcFinfo2< double, double > * DifShellBase::innerDifSourceOut () static
Definition at line 22 of file DifShellBase.cpp.
{
  static SrcFinfo2< double, double > sourceOut("innerDifSourceOut",
                           "Sends out source information.");
  return &sourceOut;
}
References SrcFinfo2< T1, T2 >::SrcFinfo2().
Referenced by initCinfo(), DifShell::vProcess(), and DifShell::vReinit().
mmPump()
void DifShellBase::mmPump (const Eref & e, double vMax, double Kd)
Definition at line 442 of file DifShellBase.cpp.
{
  vMMPump(e, vMax, Kd );
}
References vMMPump().
Referenced by initCinfo().
outerDifSourceOut()
SrcFinfo2< double, double > * DifShellBase::outerDifSourceOut () static
Definition at line 28 of file DifShellBase.cpp.
{
  static SrcFinfo2< double, double > sourceOut("outerDifSourceOut",
                           "Sends out source information.");
  return &sourceOut;
}
References SrcFinfo2< T1, T2 >::SrcFinfo2().
Referenced by initCinfo(), DifShell::vProcess(), and DifShell::vReinit().
outflux()
void DifShellBase::outflux (const Eref & e, double I)
Definition at line 397 of file DifShellBase.cpp.
{
  vOutflux(e, I );
}
References vOutflux().
process()
void DifShellBase::process (const Eref & e, ProcPtr p)
Definition at line 361 of file DifShellBase.cpp.
{
  vProcess( e, p );
}
References vProcess().
Referenced by initCinfo().
reinit()
void DifShellBase::reinit (const Eref & e, ProcPtr p)
Definition at line 356 of file DifShellBase.cpp.
{
  vReinit( e, p );
}
References vReinit().
Referenced by initCinfo().
setC()
void DifShellBase::setC (const Eref & e, double C)
Definition at line 233 of file DifShellBase.cpp.
{
  vSetC(e,C);
}
References vSetC().
Referenced by initCinfo().
setCeq()
void DifShellBase::setCeq (const Eref & e, double Ceq)
Definition at line 242 of file DifShellBase.cpp.
{
  vSetCeq(e,Ceq);
}
References vSetCeq().
Referenced by initCinfo().
setD()
void DifShellBase::setD (const Eref & e, double D)
Definition at line 252 of file DifShellBase.cpp.
{
  vSetD(e,D);
}
References vSetD().
Referenced by initCinfo().
setDiameter()
void DifShellBase::setDiameter (const Eref & e, double diameter)
Definition at line 302 of file DifShellBase.cpp.
{
  vSetDiameter(e,diameter);
}
References vSetDiameter().
Referenced by initCinfo().
setInnerArea()
void DifShellBase::setInnerArea (const Eref & e, double innerArea)
Definition at line 342 of file DifShellBase.cpp.
{
  vSetInnerArea(e,innerArea);
}
References vSetInnerArea().
Referenced by initCinfo().
setLeak()
void DifShellBase::setLeak (const Eref & e, double leak)
Definition at line 272 of file DifShellBase.cpp.
{
  vSetLeak(e,leak);
}
References vSetLeak().
Referenced by initCinfo().
setLength()
void DifShellBase::setLength (const Eref & e, double length)
Definition at line 292 of file DifShellBase.cpp.
{
  vSetLength(e,length);
}
References vSetLength().
Referenced by initCinfo().
setOuterArea()
void DifShellBase::setOuterArea (const Eref & e, double outerArea)
Definition at line 332 of file DifShellBase.cpp.
{
  vSetOuterArea(e,outerArea);
}
References vSetOuterArea().
Referenced by initCinfo().
setShapeMode()
void DifShellBase::setShapeMode (const Eref & e, unsigned int shapeMode)
Definition at line 282 of file DifShellBase.cpp.
{
  vSetShapeMode(e,shapeMode);
}
References vSetShapeMode().
Referenced by initCinfo().
setThickness()
void DifShellBase::setThickness (const Eref & e, double thickness)
Definition at line 312 of file DifShellBase.cpp.
{
  vSetThickness(e,thickness);
}
References vSetThickness().
Referenced by initCinfo().
setValence()
void DifShellBase::setValence (const Eref & e, double valence)
Definition at line 262 of file DifShellBase.cpp.
{
  vSetValence(e,valence);
}
References vSetValence().
Referenced by initCinfo().
setVolume()
void DifShellBase::setVolume (const Eref & e, double volume)
Definition at line 322 of file DifShellBase.cpp.
{
  vSetVolume(e,volume);
}
References vSetVolume().
Referenced by initCinfo().
storeInflux()
void DifShellBase::storeInflux (const Eref & e, double flux)
Definition at line 417 of file DifShellBase.cpp.
{
  vStoreInflux( e, flux );
}
References vStoreInflux().
Referenced by initCinfo().
storeOutflux()
void DifShellBase::storeOutflux (const Eref & e, double flux)
Definition at line 423 of file DifShellBase.cpp.
{
  vStoreOutflux(e, flux );
}
References vStoreOutflux().
Referenced by initCinfo().
tauPump()
void DifShellBase::tauPump (const Eref & e, double kP, double Ceq)
Definition at line 429 of file DifShellBase.cpp.
{
  vTauPump( e, kP, Ceq );
}
References vTauPump().
Referenced by initCinfo().
vBuffer()
virtual void DifShellBase::vBuffer (const Eref & e, double kf, double kb, double bFree, double bBound) pure virtual
Implemented in DifShell.
Referenced by buffer().
vEqTauPump()
virtual void DifShellBase::vEqTauPump (const Eref & e, double kP) pure virtual
Implemented in DifShell.
Referenced by eqTauPump().
vFInflux()
virtual void DifShellBase::vFInflux (const Eref & e, double I, double fraction) pure virtual
Implemented in DifShell.
Referenced by fInflux().
vFluxFromIn()
virtual void DifShellBase::vFluxFromIn (const Eref & e, double innerC, double innerThickness) pure virtual
Implemented in DifShell.
Referenced by fluxFromIn().
vFluxFromOut()
virtual void DifShellBase::vFluxFromOut (const Eref & e, double outerC, double outerThickness) pure virtual
Implemented in DifShell.
Referenced by fluxFromOut().
vFOutflux()
virtual void DifShellBase::vFOutflux (const Eref & e, double I, double fraction) pure virtual
Implemented in DifShell.
Referenced by fOutflux().
vGetC()
virtual double DifShellBase::vGetC (const Eref & e) const pure virtual
Implemented in DifShell.
Referenced by getC().
vGetCeq()
virtual double DifShellBase::vGetCeq (const Eref & e) const pure virtual
Implemented in DifShell.
Referenced by getCeq().
vGetD()
virtual double DifShellBase::vGetD (const Eref & e) const pure virtual
Implemented in DifShell.
Referenced by getD().
vGetDiameter()
virtual double DifShellBase::vGetDiameter (const Eref & e) const pure virtual
Implemented in DifShell.
Referenced by getDiameter().
vGetInnerArea()
virtual double DifShellBase::vGetInnerArea (const Eref & e) const pure virtual
Implemented in DifShell.
Referenced by getInnerArea().
vGetLeak()
virtual double DifShellBase::vGetLeak (const Eref & e) const pure virtual
Implemented in DifShell.
Referenced by getLeak().
vGetLength()
virtual double DifShellBase::vGetLength (const Eref & e) const pure virtual
Implemented in DifShell.
Referenced by getLength().
vGetOuterArea()
virtual double DifShellBase::vGetOuterArea (const Eref & e) const pure virtual
Implemented in DifShell.
Referenced by getOuterArea().
vGetShapeMode()
virtual unsigned int DifShellBase::vGetShapeMode (const Eref & e) const pure virtual
Implemented in DifShell.
Referenced by getShapeMode().
vGetThickness()
virtual double DifShellBase::vGetThickness (const Eref & e) const pure virtual
Implemented in DifShell.
Referenced by getThickness().
vGetValence()
virtual double DifShellBase::vGetValence (const Eref & e) const pure virtual
Implemented in DifShell.
Referenced by getValence().
vGetVolume()
virtual double DifShellBase::vGetVolume (const Eref & e) const pure virtual
Implemented in DifShell.
Referenced by getVolume().
vHillPump()
virtual void DifShellBase::vHillPump (const Eref & e, double vMax, double Kd, unsigned int hill) pure virtual
Implemented in DifShell.
Referenced by hillPump().
vInflux()
virtual void DifShellBase::vInflux (const Eref & e, double I) pure virtual
Implemented in DifShell.
Referenced by influx().
vMMPump()
virtual void DifShellBase::vMMPump (const Eref & e, double vMax, double Kd) pure virtual
Implemented in DifShell.
Referenced by mmPump().
vOutflux()
virtual void DifShellBase::vOutflux (const Eref & e, double I) pure virtual
Implemented in DifShell.
Referenced by outflux().
vProcess()
virtual void DifShellBase::vProcess (const Eref & e, ProcPtr p) pure virtual
Implemented in DifShell.
Referenced by process().
vReinit()
virtual void DifShellBase::vReinit (const Eref & e, ProcPtr p) pure virtual
Implemented in DifShell.
Referenced by reinit().
vSetC()
virtual void DifShellBase::vSetC (const Eref & e, double C) pure virtual
Implemented in DifShell.
Referenced by setC().
vSetCeq()
virtual void DifShellBase::vSetCeq (const Eref & e, double Ceq) pure virtual
Implemented in DifShell.
Referenced by setCeq().
vSetD()
virtual void DifShellBase::vSetD (const Eref & e, double D) pure virtual
Implemented in DifShell.
Referenced by setD().
vSetDiameter()
virtual void DifShellBase::vSetDiameter (const Eref & e, double diameter) pure virtual
Implemented in DifShell.
Referenced by setDiameter().
vSetInnerArea()
virtual void DifShellBase::vSetInnerArea (const Eref & e, double innerArea) pure virtual
Implemented in DifShell.
Referenced by setInnerArea().
vSetLeak()
virtual void DifShellBase::vSetLeak (const Eref & e, double leak) pure virtual
Implemented in DifShell.
Referenced by setLeak().
vSetLength()
virtual void DifShellBase::vSetLength (const Eref & e, double length) pure virtual
Implemented in DifShell.
Referenced by setLength().
vSetOuterArea()
virtual void DifShellBase::vSetOuterArea (const Eref & e, double outerArea) pure virtual
Implemented in DifShell.
Referenced by setOuterArea().
vSetShapeMode()
virtual void DifShellBase::vSetShapeMode (const Eref & e, unsigned int shapeMode) pure virtual
Implemented in DifShell.
Referenced by setShapeMode().
vSetThickness()
virtual void DifShellBase::vSetThickness (const Eref & e, double thickness) pure virtual
Implemented in DifShell.
Referenced by setThickness().
vSetValence()
virtual void DifShellBase::vSetValence (const Eref & e, double valence) pure virtual
Implemented in DifShell.
Referenced by setValence().
vSetVolume()
virtual void DifShellBase::vSetVolume (const Eref & e, double volume) pure virtual
Implemented in DifShell.
Referenced by setVolume().
vStoreInflux()
virtual void DifShellBase::vStoreInflux (const Eref & e, double flux) pure virtual
Implemented in DifShell.
Referenced by storeInflux().
vStoreOutflux()
virtual void DifShellBase::vStoreOutflux (const Eref & e, double flux) pure virtual
Implemented in DifShell.
Referenced by storeOutflux().
vTauPump()
virtual void DifShellBase::vTauPump (const Eref & e, double kP, double Ceq) pure virtual
Implemented in DifShell.
Referenced by tauPump().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/biophysics/DifShellBase.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/biophysics/DifShellBase.cpp