MOOSE - Multiscale Object Oriented Simulation Environment: MarkovRateTable Class Reference
MarkovRateTable Class Reference
#include <MarkovRateTable.h>
Public Member Functions
bool areAllRates1d ()
bool areAllRates2d ()
bool areAllRatesConstant ()
bool areAllRatesLigandDep ()
bool areAllRatesVoltageDep ()
bool areAnyRates1d ()
bool areAnyRates2d ()
bool areAnyRatesLigandDep ()
bool areAnyRatesVoltageDep ()
bool areIndicesOutOfBounds (unsigned int, unsigned int) const
Interpol2D * getInt2dChildTable (unsigned int, unsigned int) const
double getLigandConc () const
vector< unsigned int > getListOf1dRates ()
vector< unsigned int > getListOf2dRates ()
vector< unsigned int > getListOfConstantRates ()
vector< unsigned int > getListOfLigandRates ()
vector< unsigned int > getListOfVoltageRates ()
vector< vector< double > > getQ () const
unsigned int getSize () const
double getVm () const
VectorTable * getVtChildTable (unsigned int, unsigned int) const
void handleLigandConc (double)
void handleVm (double)
void init (unsigned int)
void initConstantRates ()
void innerSetInt2dChildTable (unsigned int, unsigned int, Interpol2D)
void innerSetVtChildTable (unsigned int, unsigned int, VectorTable, unsigned int)
bool isRate1d (unsigned int, unsigned int) const
bool isRate2d (unsigned int, unsigned int) const
bool isRateConstant (unsigned int, unsigned int) const
bool isRateLigandDep (unsigned int, unsigned int) const
bool isRateZero (unsigned int, unsigned int) const
double lookup1dIndex (unsigned int, unsigned int, unsigned int)
double lookup1dValue (unsigned int, unsigned int, double)
double lookup2dIndex (unsigned int, unsigned int, unsigned int, unsigned int)
double lookup2dValue (unsigned int, unsigned int, double, double)
MarkovRateTable ()
void process (const Eref &, ProcPtr)
void reinit (const Eref &, ProcPtr)
void setConstantRate (unsigned int, unsigned int, double)
void setInt2dChildTable (unsigned int, unsigned int, Id)
void setLigandConc (double)
void setVm (double)
void setVtChildTable (unsigned int, unsigned int, Id, unsigned int)
void updateRates ()
~MarkovRateTable ()
Static Public Member Functions
static const Cinfo * initCinfo ()
Private Member Functions
bool isInitialized () const
Private Attributes
vector< vector< Interpol2D * > > int2dTables_
double ligandConc_
vector< unsigned int > listOf1dRates_
vector< unsigned int > listOf2dRates_
vector< unsigned int > listOfConstantRates_
vector< unsigned int > listOfLigandRates_
vector< unsigned int > listOfVoltageRates_
vector< vector< double > > Q_
unsigned int size_
vector< vector< unsigned int > > useLigandConc_
double Vm_
vector< vector< VectorTable * > > vtTables_
Friends
istream & operator>> (istream &, MarkovRateTable &)
Detailed Description
Definition at line 48 of file MarkovRateTable.h.
Constructor & Destructor Documentation
MarkovRateTable()
MarkovRateTable::MarkovRateTable ()
Definition at line 170 of file MarkovRateTable.cpp.
                                 :
    Vm_(0),
    ligandConc_(0),
    size_(0)
{ ; }
References ligandConc_, size_, and Vm_.
~MarkovRateTable()
MarkovRateTable::~MarkovRateTable ()
Definition at line 176 of file MarkovRateTable.cpp.
{
    for ( unsigned int i = 0; i < size_; ++i )
    {
        for ( unsigned int j = 0; j < size_; ++j )
        {
            if ( isRate1d( i, j ) || isRateConstant( i, j ) )
                delete vtTables_[i][j];
            if ( isRate2d( i, j ) )
                delete int2dTables_[i][j];
        }
    }
}
References int2dTables_, isRate1d(), isRate2d(), isRateConstant(), size_, and vtTables_.
Member Function Documentation
areAllRates1d()
bool MarkovRateTable::areAllRates1d ()
Definition at line 444 of file MarkovRateTable.cpp.
{
    return areAnyRates1d() && !areAnyRates2d();
}
References areAnyRates1d(), and areAnyRates2d().
Referenced by areAllRatesLigandDep(), areAllRatesVoltageDep(), MarkovSolverBase::computeState(), MarkovSolverBase::fillupTable(), MarkovSolverBase::init(), and MarkovSolverBase::setLookupParams().
areAllRates2d()
bool MarkovRateTable::areAllRates2d ()
Definition at line 455 of file MarkovRateTable.cpp.
{
    return areAnyRates2d() && !areAnyRates1d();
}
References areAnyRates1d(), and areAnyRates2d().
areAllRatesConstant()
bool MarkovRateTable::areAllRatesConstant ()
Definition at line 432 of file MarkovRateTable.cpp.
{
    return listOf1dRates_.empty() && listOf2dRates_.empty() &&
            !listOfConstantRates_.empty();
}
References listOf1dRates_, listOf2dRates_, and listOfConstantRates_.
Referenced by MarkovSolverBase::fillupTable(), and process().
areAllRatesLigandDep()
bool MarkovRateTable::areAllRatesLigandDep ()
Definition at line 466 of file MarkovRateTable.cpp.
{
    return areAllRates1d() && !areAnyRatesVoltageDep() &&
            areAnyRatesLigandDep();
}
References areAllRates1d(), areAnyRatesLigandDep(), and areAnyRatesVoltageDep().
Referenced by MarkovSolverBase::fillupTable(), MarkovSolverBase::init(), and MarkovSolverBase::setLookupParams().
areAllRatesVoltageDep()
bool MarkovRateTable::areAllRatesVoltageDep ()
Definition at line 478 of file MarkovRateTable.cpp.
{
    return areAllRates1d() && areAnyRatesVoltageDep() &&
            !areAnyRatesLigandDep();
}
References areAllRates1d(), areAnyRatesLigandDep(), and areAnyRatesVoltageDep().
Referenced by MarkovSolverBase::fillupTable(), MarkovSolverBase::init(), and MarkovSolverBase::linearInterpolate().
areAnyRates1d()
bool MarkovRateTable::areAnyRates1d ()
Definition at line 439 of file MarkovRateTable.cpp.
{
    return !listOf1dRates_.empty();
}
References listOf1dRates_.
Referenced by areAllRates1d(), areAllRates2d(), and MarkovSolverBase::setLookupParams().
areAnyRates2d()
bool MarkovRateTable::areAnyRates2d ()
Definition at line 450 of file MarkovRateTable.cpp.
{
    return !listOf2dRates_.empty();
}
References listOf2dRates_.
Referenced by areAllRates1d(), areAllRates2d(), MarkovSolverBase::computeState(), MarkovSolverBase::fillupTable(), MarkovSolverBase::init(), and MarkovSolverBase::setLookupParams().
areAnyRatesLigandDep()
bool MarkovRateTable::areAnyRatesLigandDep ()
Definition at line 461 of file MarkovRateTable.cpp.
{
    return !listOfLigandRates_.empty();
}
References listOfLigandRates_.
Referenced by areAllRatesLigandDep(), areAllRatesVoltageDep(), MarkovSolverBase::computeState(), MarkovSolverBase::fillupTable(), and MarkovSolverBase::init().
areAnyRatesVoltageDep()
bool MarkovRateTable::areAnyRatesVoltageDep ()
Definition at line 473 of file MarkovRateTable.cpp.
{
    return !listOfVoltageRates_.empty();
}
References listOfVoltageRates_.
Referenced by areAllRatesLigandDep(), areAllRatesVoltageDep(), MarkovSolverBase::computeState(), MarkovSolverBase::fillupTable(), and MarkovSolverBase::init().
areIndicesOutOfBounds()
bool MarkovRateTable::areIndicesOutOfBounds (unsigned int i, unsigned int j) const
Definition at line 427 of file MarkovRateTable.cpp.
{
    return ( i > size_ || j > size_ );
}
References size_.
Referenced by innerSetInt2dChildTable(), innerSetVtChildTable(), lookup1dIndex(), lookup1dValue(), lookup2dIndex(), and lookup2dValue().
getInt2dChildTable()
Interpol2D * MarkovRateTable::getInt2dChildTable (unsigned int i, unsigned int j) const
Definition at line 236 of file MarkovRateTable.cpp.
{
    if ( isRate2d( i, j ) )
        return int2dTables_[i][j];
    else
    {
        cerr << "MarkovRateTable::getInt2dChildTable : Error : No two parameter"
                " rate table set for (" << i+1 << "," << j+1 << "). Returning NULL.\n";
        return 0;
    }
}
References int2dTables_, and isRate2d().
Referenced by MarkovSolverBase::setLookupParams().
getLigandConc()
double MarkovRateTable::getLigandConc () const
Definition at line 383 of file MarkovRateTable.cpp.
{
    return ligandConc_;
}
References ligandConc_.
Referenced by initCinfo().
getListOf1dRates()
vector< unsigned int > MarkovRateTable::getListOf1dRates ()
Definition at line 543 of file MarkovRateTable.cpp.
{
    return listOf1dRates_;
}
References listOf1dRates_.
Referenced by MarkovSolverBase::fillupTable().
getListOf2dRates()
vector< unsigned int > MarkovRateTable::getListOf2dRates ()
Definition at line 548 of file MarkovRateTable.cpp.
{
    return listOf2dRates_;
}
References listOf2dRates_.
Referenced by MarkovSolverBase::fillupTable(), and MarkovSolverBase::setLookupParams().
getListOfConstantRates()
vector< unsigned int > MarkovRateTable::getListOfConstantRates ()
Definition at line 563 of file MarkovRateTable.cpp.
{
    return listOfConstantRates_;
}
References listOfConstantRates_.
Referenced by MarkovSolverBase::fillupTable().
getListOfLigandRates()
vector< unsigned int > MarkovRateTable::getListOfLigandRates ()
Definition at line 558 of file MarkovRateTable.cpp.
{
    return listOfLigandRates_;
}
References listOfLigandRates_.
Referenced by MarkovSolverBase::fillupTable(), and MarkovSolverBase::setLookupParams().
getListOfVoltageRates()
vector< unsigned int > MarkovRateTable::getListOfVoltageRates ()
Definition at line 553 of file MarkovRateTable.cpp.
{
    return listOfVoltageRates_;
}
References listOfVoltageRates_.
Referenced by MarkovSolverBase::fillupTable(), and MarkovSolverBase::setLookupParams().
getQ()
vector< vector< double > > MarkovRateTable::getQ () const
Definition at line 363 of file MarkovRateTable.cpp.
{
    return Q_;
}
References Q_.
Referenced by initCinfo().
getSize()
unsigned int MarkovRateTable::getSize () const
Definition at line 368 of file MarkovRateTable.cpp.
{
    return size_;
}
References size_.
Referenced by MarkovSolverBase::init(), and initCinfo().
getVm()
double MarkovRateTable::getVm () const
Definition at line 373 of file MarkovRateTable.cpp.
{
    return Vm_;
}
References Vm_.
Referenced by initCinfo().
getVtChildTable()
VectorTable * MarkovRateTable::getVtChildTable (unsigned int i, unsigned int j) const
Definition at line 190 of file MarkovRateTable.cpp.
{
    if ( isRate1d( i, j ) || isRateConstant( i, j ) )
        return vtTables_[i][j];
    else
    {
        cerr << "MarkovRateTable::getVtChildTable : Error : No one parameter rate "
                "table set for (" << i+1 << "," << j+1 << "). Returing NULL.\n";
        return 0;
    }
}
References isRate1d(), isRateConstant(), and vtTables_.
Referenced by MarkovSolverBase::setLookupParams().
handleLigandConc()
void MarkovRateTable::handleLigandConc (double ligandConc)
Definition at line 649 of file MarkovRateTable.cpp.
{
    ligandConc_ = ligandConc;
}
References ligandConc_.
Referenced by initCinfo().
handleVm()
void MarkovRateTable::handleVm (double Vm)
Definition at line 644 of file MarkovRateTable.cpp.
{
    Vm_ = Vm;
}
References Vm_.
Referenced by initCinfo().
init()
void MarkovRateTable::init (unsigned int size)
Definition at line 630 of file MarkovRateTable.cpp.
{
    size_ = size;
    if ( vtTables_.empty() )
        vtTables_ = resize< VectorTable* >( vtTables_, size, 0 );
    if ( int2dTables_.empty() )
        int2dTables_ = resize< Interpol2D* >( int2dTables_, size, 0 );
    if ( useLigandConc_.empty() )
        useLigandConc_ = resize< unsigned int >( useLigandConc_, size, 0 );
    if ( Q_.empty() )
        Q_ = resize< double >( Q_, size, 0 );
}
References int2dTables_, Q_, resize(), size_, useLigandConc_, and vtTables_.
Referenced by initCinfo().
initCinfo()
const Cinfo * MarkovRateTable::initCinfo () static
Definition at line 27 of file MarkovRateTable.cpp.
{
    //SharedFinfos
    static DestFinfo handleVm("handleVm",
                              "Handles incoming message containing voltage information.",
                              new OpFunc1< MarkovRateTable, double >(&MarkovRateTable::handleVm)
                              );
    static Finfo* channelShared[] =
            {
        &handleVm
            };
    static SharedFinfo channel("channel",
                               "This message couples the rate table to the compartment. The rate table"
                               " needs updates on voltage in order to compute the rate table.",
                               channelShared, sizeof( channelShared ) / sizeof( Finfo* )
                               );
    //DestFinfos
    static DestFinfo process(   "process",
                                "Handles process call",
                                new ProcOpFunc< MarkovRateTable >( &MarkovRateTable::process ) );
    static DestFinfo reinit( "reinit",
                             "Handles reinit call",
                             new ProcOpFunc< MarkovRateTable >( &MarkovRateTable::reinit ) );
    static Finfo* processShared[] =
            {
        &process, &reinit
            };
    static SharedFinfo proc( "proc",
                             "This is a shared message to receive Process message from the"
                             "scheduler. The first entry is a MsgDest for the Process "
                             "operation. It has a single argument, ProcInfo, which "
                             "holds lots of information about current time, thread, dt and"
                             "so on. The second entry is a MsgDest for the Reinit "
                             "operation. It also uses ProcInfo.",
                             processShared, sizeof( processShared ) / sizeof( Finfo* )
                             );
    static DestFinfo init("init",
                          "Initialization of the class. Allocates memory for all the tables.",
                          new OpFunc1< MarkovRateTable, unsigned int >(&MarkovRateTable::init) );
    static DestFinfo handleLigandConc("handleLigandConc",
                                      "Handles incoming message containing ligand concentration.",
                                      new OpFunc1< MarkovRateTable, double >(&MarkovRateTable::handleLigandConc) );
    static DestFinfo set1d("set1d",
                           "Setting up of 1D lookup table for the (i,j)'th rate.",
                           new OpFunc4< MarkovRateTable, unsigned int, unsigned int, Id,
                           unsigned int >
                           ( &MarkovRateTable::setVtChildTable )
                           );
    static DestFinfo set2d("set2d",
                           "Setting up of 2D lookup table for the (i,j)'th rate.",
                           new OpFunc3< MarkovRateTable, unsigned int, unsigned int, Id >
                           ( &MarkovRateTable::setInt2dChildTable )
                           );
    static DestFinfo setconst("setconst",
                              "Setting a constant value for the (i,j)'th rate. Internally, this is"
                              " stored as a 1-D rate with a lookup table containing 1 entry.",
                              new OpFunc3< MarkovRateTable, unsigned int, unsigned int, double >
                              ( &MarkovRateTable::setConstantRate )
                              );
    //Field information.
    static ValueFinfo< MarkovRateTable, double > ligandconc( "ligandConc",
                                                             "Ligand concentration.",
                                                             &MarkovRateTable::setLigandConc,
                                                             &MarkovRateTable::getLigandConc
                                                             );
    static ValueFinfo< MarkovRateTable, double > vm( "Vm",
                                                     "Membrane voltage.",
                                                     &MarkovRateTable::setVm,
                                                     &MarkovRateTable::getVm
                                                     );
    static ReadOnlyValueFinfo< MarkovRateTable, vector< vector< double > > >
            Q( "Q",
               "Instantaneous rate matrix.",
               &MarkovRateTable::getQ
               );
    //Really no point in allowing access to Vm_ and ligandConc_ when it is
    //available from the MarkovChannel class.
    static ReadOnlyValueFinfo< MarkovRateTable, unsigned int >
            size( "size",
                  "Dimension of the families of lookup tables. Is always equal to the number of states in the model.",
                  &MarkovRateTable::getSize
                  );
    static Finfo* markovRateTableFinfos[] =
            {
        &channel,                       //SharedFinfo
        instRatesOut(),         //SrcFinfo
        &proc,                          //DestFinfo
        &init,                          //DestFinfo
        &handleLigandConc,  //DestFinfo
        &set1d,                         //DestFinfo
        &set2d,                         //DestFinfo
        &setconst,                  //DestFinfo
        &vm,                                //ValueFinfo
        &ligandconc,                //ValueFinfo
        &Q,                                 //ReadOnlyValueFinfo
        &size,                          //ReadOnlyValueFinfo
            };
    static string doc[] =
    {
        "Name", "MarkovRateTable",
        "Author", "Vishaka Datta S, 2011, NCBS",
        "Description", "Rate Table for Markov channel calculations. "
    };
    static Dinfo< MarkovRateTable > dinfo;
    static Cinfo MarkovRateTableCinfo(
        "MarkovRateTable",
        Neutral::initCinfo(),
        markovRateTableFinfos,
        sizeof(markovRateTableFinfos)/sizeof(Finfo *),
        &dinfo,
        doc,
        sizeof( doc ) / sizeof( string )
                                      );
    return &MarkovRateTableCinfo;
}
References Cinfo::Cinfo(), DestFinfo::DestFinfo(), getLigandConc(), getQ(), getSize(), getVm(), handleLigandConc(), handleVm(), init(), Neutral::initCinfo(), instRatesOut(), OpFunc1< T, A >::OpFunc1(), OpFunc3< T, A1, A2, A3 >::OpFunc3(), OpFunc4< T, A1, A2, A3, A4 >::OpFunc4(), process(), ProcOpFunc< T >::ProcOpFunc(), ReadOnlyValueFinfo< T, F >::ReadOnlyValueFinfo(), reinit(), setConstantRate(), setInt2dChildTable(), setLigandConc(), setVm(), setVtChildTable(), SharedFinfo::SharedFinfo(), and ValueFinfo< T, F >::ValueFinfo().
initConstantRates()
void MarkovRateTable::initConstantRates ()
Definition at line 525 of file MarkovRateTable.cpp.
{
    unsigned int n = listOfConstantRates_.size(), i, j;
    for ( unsigned int k = 0; k < n; ++k )
    {
        i = ( ( listOfConstantRates_[k] / 10 ) % 10 ) - 1;
        j = ( listOfConstantRates_[k] % 10 ) - 1;
        Q_[i][i] += Q_[i][j];
        //Doesn't really matter which value is looked up as there is only one
        //entry in the table.
        Q_[i][j] = lookup1dValue( i, j, 0.0 );
        Q_[i][i] -= Q_[i][j];
    }
}
References listOfConstantRates_, lookup1dValue(), and Q_.
Referenced by reinit().
innerSetInt2dChildTable()
void MarkovRateTable::innerSetInt2dChildTable (unsigned int i, unsigned int j, Interpol2D int2dTable)
Definition at line 248 of file MarkovRateTable.cpp.
{
    if ( areIndicesOutOfBounds( i, j ) )
    {
        cerr << "MarkovRateTable::innerSetInt2dChildTable : Error : Table requested"
                "   is out of bounds\n";
        return;
    }
    if ( isRate1d( i, j ) || isRate2d( i, j ) || isRateConstant( i, j ) )
    {
        cerr << "MarkovRateTable::innerSetInt2dChildTable : Error : Rate (" <<
                i+1 << "," << j+1 << ") has already been set!\n";
        return;
    }
    if ( i == j )
    {
        cerr << "MarkovRateTable::innerSetInt2dChildTable : Error : Cannot "
                "set diagonal rate (" << i+1 << "," << i+1 << endl;
        return;
    }
    //If table isn't already initialized, do so.
    if ( int2dTables_[i][j] == 0 )
        int2dTables_[i][j] = new Interpol2D();
    //Checking to see if this rate has already been set with a one parameter rate
    //table.
    *int2dTables_[i][j] = int2dTable;
}
References areIndicesOutOfBounds(), int2dTables_, Interpol2D::Interpol2D(), isRate1d(), isRate2d(), and isRateConstant().
Referenced by setInt2dChildTable().
innerSetVtChildTable()
void MarkovRateTable::innerSetVtChildTable (unsigned int i, unsigned int j, VectorTable vecTable, unsigned int ligandFlag)
Definition at line 202 of file MarkovRateTable.cpp.
{
    if ( areIndicesOutOfBounds( i, j ) )
    {
        cerr << "MarkovRateTable::innerSetVtChildTable : Error : Table requested"
                "is out of bounds!.\n";
        return;
    }
    //Checking to see if this rate has already been set with a 2-parameter rate.
    if ( isRate2d( i, j ) || isRateConstant( i, j ) || isRate1d( i, j ) )
    {
        cerr << "MarkovRateTable::innerSetVtChildTable : Error : "
                "Rate (" << i+1 << "," << j+1 << ")has already been set.\n";
        return;
    }
    if ( i == j )
    {
        cerr << "MarkovRateTable::innerSetVtChildTable : Error : Cannot "
                "set diagonal rate (" << i+1 << "," << i+1 << endl;
        return;
    }
    //If table hasnt been allocated any memory, do so.
    if ( vtTables_[i][j] == 0 )
        vtTables_[i][j] = new VectorTable();
    *vtTables_[i][j] = vecTable;
    useLigandConc_[i][j] = ligandFlag;
}
References areIndicesOutOfBounds(), isRate1d(), isRate2d(), isRateConstant(), useLigandConc_, VectorTable::VectorTable(), and vtTables_.
Referenced by setConstantRate(), and setVtChildTable().
isInitialized()
bool MarkovRateTable::isInitialized () const private
Definition at line 600 of file MarkovRateTable.cpp.
{
    return ( size_ > 0 );
}
References size_.
Referenced by reinit().
isRate1d()
bool MarkovRateTable::isRate1d (unsigned int i, unsigned int j) const
Definition at line 406 of file MarkovRateTable.cpp.
{
    //Second condition is necessary because for a constant rate, the 1D lookup
    //table class is set, but has only one entry. So a constant rate would pass
    //off as a one-parameter rate transition if not for this check.
    if ( vtTables_[i][j] == 0 )
        return false;
    else
        return ( vtTables_[i][j]->getDiv() > 0 );
}
References VectorTable::getDiv(), and vtTables_.
Referenced by getVtChildTable(), innerSetInt2dChildTable(), innerSetVtChildTable(), isRateLigandDep(), lookup1dIndex(), lookup1dValue(), operator>>(), and ~MarkovRateTable().
isRate2d()
bool MarkovRateTable::isRate2d (unsigned int i, unsigned int j) const
Definition at line 422 of file MarkovRateTable.cpp.
{
    return ( int2dTables_[i][j] != 0 );
}
References int2dTables_.
Referenced by getInt2dChildTable(), innerSetInt2dChildTable(), innerSetVtChildTable(), isRateConstant(), lookup2dIndex(), lookup2dValue(), operator>>(), and ~MarkovRateTable().
isRateConstant()
bool MarkovRateTable::isRateConstant (unsigned int i, unsigned int j) const
Definition at line 398 of file MarkovRateTable.cpp.
{
    if ( isRate2d( i, j ) || isRateZero( i, j ) )
        return false;
    return ( vtTables_[i][j]->getDiv() == 0 );
}
References VectorTable::getDiv(), isRate2d(), isRateZero(), and vtTables_.
Referenced by getVtChildTable(), innerSetInt2dChildTable(), innerSetVtChildTable(), lookup1dIndex(), lookup1dValue(), and ~MarkovRateTable().
isRateLigandDep()
bool MarkovRateTable::isRateLigandDep (unsigned int i, unsigned int j) const
Definition at line 417 of file MarkovRateTable.cpp.
{
    return ( isRate1d( i, j ) && useLigandConc_[i][j] > 0 );
}
References isRate1d(), and useLigandConc_.
Referenced by updateRates().
isRateZero()
bool MarkovRateTable::isRateZero (unsigned int i, unsigned int j) const
Definition at line 393 of file MarkovRateTable.cpp.
{
    return ( vtTables_[i][j] == 0 && int2dTables_[i][j] == 0 );
}
References int2dTables_, and vtTables_.
Referenced by isRateConstant().
lookup1dIndex()
double MarkovRateTable::lookup1dIndex (unsigned int i, unsigned int j, unsigned int xIndex)
Definition at line 299 of file MarkovRateTable.cpp.
{
    if ( areIndicesOutOfBounds( i, j ) )
    {
        cerr << "MarkovRateTable::lookup1dIndex : Lookup requested on non-"
                "existent table at (" << i << "," << j << "). Returning 0.\n";
        return 0;
    }
    if ( !isRate1d( i, j ) && !isRateConstant( i, j ) )
    {
        cerr << "MarkovRateTable::lookup1dIndex : No 1D or constant rate set at ("
             << i << "," << j << "). Returning 0.\n";
        return 0;
    }
    return vtTables_[i][j]->lookupByIndex( xIndex );
}
References areIndicesOutOfBounds(), isRate1d(), isRateConstant(), VectorTable::lookupByIndex(), and vtTables_.
Referenced by MarkovSolverBase::innerFillupTable().
lookup1dValue()
double MarkovRateTable::lookup1dValue (unsigned int i, unsigned int j, double x)
Definition at line 280 of file MarkovRateTable.cpp.
{
    if ( areIndicesOutOfBounds( i, j ) )
    {
        cerr << "MarkovRateTable::lookup1dValue : Lookup requested on non-existent"
                "table at (" << i + 1 << "," << j + 1 << "). Returning 0.\n";
        return 0;
    }
    if ( !isRate1d( i, j ) && !isRateConstant( i, j ) )
    {
        cerr << "MarkovRateTable::lookup1dValue : No 1D or constant rate set at "
                "(" << i + 1 << "," << j + 1 << "). Returning 0.\n";
        return 0;
    }
    return vtTables_[i][j]->lookupByValue( x );
}
References areIndicesOutOfBounds(), isRate1d(), isRateConstant(), VectorTable::lookupByValue(), and vtTables_.
Referenced by initConstantRates(), MarkovSolverBase::innerFillupTable(), and updateRates().
lookup2dIndex()
double MarkovRateTable::lookup2dIndex (unsigned int i, unsigned int j, unsigned int xIndex, unsigned int yIndex)
Definition at line 339 of file MarkovRateTable.cpp.
{
    if ( areIndicesOutOfBounds( i, j ) )
    {
        cerr << "MarkovRateTable::lookup2dIndex : Lookup requested on non-existent"
                " table at (" << i+1 << "," << j+1 << "). Returning 0.\n";
        return 0;
    }
    if ( !isRate2d( i, j ) )
    {
        cerr << "MarkovRateTable::lookup2dIndex : No 2D rate set at (" << i+1 << ","
             << j+1 << "). Returning 0.\n";
        return 0;
    }
    vector< unsigned int > indices;
    indices.push_back( xIndex );
    indices.push_back( yIndex );
    return int2dTables_[i][j]->getTableValue( indices );
}
References areIndicesOutOfBounds(), Interpol2D::getTableValue(), int2dTables_, and isRate2d().
Referenced by MarkovSolverBase::innerFillupTable().
lookup2dValue()
double MarkovRateTable::lookup2dValue (unsigned int i, unsigned int j, double x, double y)
Definition at line 319 of file MarkovRateTable.cpp.
{
    if ( areIndicesOutOfBounds( i, j ) )
    {
        cerr << "MarkovRateTable::lookup2dValue : Lookup requested on non-existent"
                " table at (" << i + 1<< "," << j+1 << "). Returning 0.\n";
        return 0;
    }
    if ( !isRate2d( i, j ) )
    {
        cerr << "MarkovRateTable::lookup2dValue : No 2D rate set at (" << i+1 << ","
             << j+1 << "). Returning 0.\n";
        return 0;
    }
    return int2dTables_[i][j]->innerLookup( x, y );
}
References areIndicesOutOfBounds(), Interpol2D::innerLookup(), int2dTables_, and isRate2d().
Referenced by updateRates().
process()
void MarkovRateTable::process (const Eref & e, ProcPtr info)
Definition at line 608 of file MarkovRateTable.cpp.
{
    if ( !areAllRatesConstant() )
        updateRates();
    instRatesOut()->send( e, Q_ );
}
References areAllRatesConstant(), instRatesOut(), Q_, SrcFinfo1< T >::send(), and updateRates().
Referenced by initCinfo().
reinit()
void MarkovRateTable::reinit (const Eref & e, ProcPtr info)
Definition at line 616 of file MarkovRateTable.cpp.
{
    if ( isInitialized() )
        initConstantRates();
    else
        cerr << "MarkovRateTable::reinit : MarkovRateTable class has not been"
                " initialized!.";
    instRatesOut()->send( e, Q_ );
}
References initConstantRates(), instRatesOut(), isInitialized(), Q_, and SrcFinfo1< T >::send().
Referenced by initCinfo().
setConstantRate()
void MarkovRateTable::setConstantRate (unsigned int i, unsigned int j, double rate)
Definition at line 685 of file MarkovRateTable.cpp.
{
    VectorTable vecTable;
    vecTable.setMin( rate );
    vecTable.setMax( rate );
    vecTable.setDiv( 1 );
    vector< double > rateWrap;
    rateWrap.push_back( rate );
    vecTable.setTable( rateWrap );
    innerSetVtChildTable( i - 1, j - 1, vecTable, 0 );
    listOfConstantRates_.push_back( i * 10 + j );
}
References innerSetVtChildTable(), listOfConstantRates_, VectorTable::setDiv(), VectorTable::setMax(), VectorTable::setMin(), and VectorTable::setTable().
Referenced by initCinfo().
setInt2dChildTable()
void MarkovRateTable::setInt2dChildTable (unsigned int i, unsigned int j, Id int2dTabId)
Definition at line 670 of file MarkovRateTable.cpp.
{
    Interpol2D* int2dTable = reinterpret_cast< Interpol2D* >
            ( int2dTabId.eref().data() );
    innerSetInt2dChildTable( i - 1, j - 1, *int2dTable );
    listOf2dRates_.push_back( i * 10 + j );
}
References Eref::data(), Id::eref(), innerSetInt2dChildTable(), and listOf2dRates_.
Referenced by initCinfo().
setLigandConc()
void MarkovRateTable::setLigandConc (double ligandConc)
Definition at line 388 of file MarkovRateTable.cpp.
{
    ligandConc_ = ligandConc;
}
References ligandConc_.
Referenced by initCinfo().
setVm()
void MarkovRateTable::setVm (double Vm)
Definition at line 378 of file MarkovRateTable.cpp.
{
    Vm_ = Vm;
}
References Vm_.
Referenced by initCinfo().
setVtChildTable()
void MarkovRateTable::setVtChildTable (unsigned int i, unsigned int j, Id vecTabId, unsigned int ligandFlag)
Definition at line 654 of file MarkovRateTable.cpp.
{
    VectorTable* vecTable = reinterpret_cast< VectorTable* >
            ( vecTabId.eref().data() );
    innerSetVtChildTable( i - 1, j - 1, *vecTable, ligandFlag );
    listOf1dRates_.push_back( i * 10 + j );
    if ( ligandFlag > 0 )
        listOfLigandRates_.push_back( i * 10 + j );
    else
        listOfVoltageRates_.push_back( i * 10 + j );
}
References Eref::data(), Id::eref(), innerSetVtChildTable(), listOf1dRates_, listOfLigandRates_, and listOfVoltageRates_.
Referenced by initCinfo().
updateRates()
void MarkovRateTable::updateRates ()
Definition at line 484 of file MarkovRateTable.cpp.
{
    double temp;
    unsigned int i,j;
    //Update 1D rates, if any.
    for( unsigned int k = 0; k < listOf1dRates_.size(); ++k )
    {
        j = ( listOf1dRates_[k] % 10 ) - 1;
        i = ( ( listOf1dRates_[k] / 10 ) % 10 ) - 1;
        temp = Q_[i][j];
        if ( isRateLigandDep( i, j ) )
            Q_[i][j] = lookup1dValue( i, j, ligandConc_ );
        else
        {
            Q_[i][j] = lookup1dValue( i, j, Vm_ );
        }
        //Ensures that the row sums to zero.
        if ( !doubleEq( temp, Q_[i][j] ) )
            Q_[i][i] = Q_[i][i] - Q_[i][j] + temp;
    }
    //Update 2D rates, if any.
    for( unsigned int k = 0; k < listOf2dRates_.size(); ++k )
    {
        j = ( listOf2dRates_[k] % 10 ) - 1;
        i = ( ( listOf2dRates_[k] / 10 ) % 10 ) - 1;
        temp = Q_[i][j];
        Q_[i][j] = lookup2dValue( i, j, Vm_, ligandConc_ );
        //Ensures that the row sums to zero.
        if ( !doubleEq( temp, Q_[i][j] ) )
            Q_[i][i] = Q_[i][i] - Q_[i][j] + temp;
    }
}
References doubleEq(), isRateLigandDep(), ligandConc_, listOf1dRates_, listOf2dRates_, lookup1dValue(), lookup2dValue(), Q_, and Vm_.
Referenced by process().
Friends And Related Symbol Documentation
operator>>
istream & operator>> (istream & , MarkovRateTable &) friend
Member Data Documentation
int2dTables_
vector< vector< Interpol2D* > > MarkovRateTable::int2dTables_ private
Definition at line 176 of file MarkovRateTable.h.
Referenced by getInt2dChildTable(), init(), innerSetInt2dChildTable(), isRate2d(), isRateZero(), lookup2dIndex(), lookup2dValue(), operator>>(), and ~MarkovRateTable().
ligandConc_
double MarkovRateTable::ligandConc_ private
Definition at line 200 of file MarkovRateTable.h.
Referenced by getLigandConc(), handleLigandConc(), MarkovRateTable(), operator>>(), setLigandConc(), and updateRates().
listOf1dRates_
vector< unsigned int > MarkovRateTable::listOf1dRates_ private
Definition at line 187 of file MarkovRateTable.h.
Referenced by areAllRatesConstant(), areAnyRates1d(), getListOf1dRates(), setVtChildTable(), and updateRates().
listOf2dRates_
vector< unsigned int > MarkovRateTable::listOf2dRates_ private
Definition at line 188 of file MarkovRateTable.h.
Referenced by areAllRatesConstant(), areAnyRates2d(), getListOf2dRates(), setInt2dChildTable(), and updateRates().
listOfConstantRates_
vector< unsigned int > MarkovRateTable::listOfConstantRates_ private
Definition at line 189 of file MarkovRateTable.h.
Referenced by areAllRatesConstant(), getListOfConstantRates(), initConstantRates(), and setConstantRate().
listOfLigandRates_
vector< unsigned int > MarkovRateTable::listOfLigandRates_ private
Definition at line 190 of file MarkovRateTable.h.
Referenced by areAnyRatesLigandDep(), getListOfLigandRates(), and setVtChildTable().
listOfVoltageRates_
vector< unsigned int > MarkovRateTable::listOfVoltageRates_ private
Definition at line 191 of file MarkovRateTable.h.
Referenced by areAnyRatesVoltageDep(), getListOfVoltageRates(), and setVtChildTable().
Q_
vector< vector< double > > MarkovRateTable::Q_ private
Definition at line 194 of file MarkovRateTable.h.
Referenced by getQ(), init(), initConstantRates(), process(), reinit(), and updateRates().
size_
unsigned int MarkovRateTable::size_ private
Definition at line 207 of file MarkovRateTable.h.
Referenced by areIndicesOutOfBounds(), getSize(), init(), isInitialized(), MarkovRateTable(), operator>>(), and ~MarkovRateTable().
useLigandConc_
vector< vector< unsigned int > > MarkovRateTable::useLigandConc_ private
Definition at line 181 of file MarkovRateTable.h.
Referenced by init(), innerSetVtChildTable(), isRateLigandDep(), and operator>>().
Vm_
double MarkovRateTable::Vm_ private
Definition at line 199 of file MarkovRateTable.h.
Referenced by getVm(), handleVm(), MarkovRateTable(), operator>>(), setVm(), and updateRates().
vtTables_
vector< vector< VectorTable* > > MarkovRateTable::vtTables_ private
Definition at line 171 of file MarkovRateTable.h.
Referenced by getVtChildTable(), init(), innerSetVtChildTable(), isRate1d(), isRateConstant(), isRateZero(), lookup1dIndex(), lookup1dValue(), operator>>(), and ~MarkovRateTable().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/biophysics/MarkovRateTable.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/biophysics/MarkovRateTable.cpp