MOOSE - Multiscale Object Oriented Simulation Environment: NMDAChan Class Reference
NMDAChan Class Reference
#include <NMDAChan.h>
Public Member Functions
void assignIntCa (double v)
double getCMg () const
double getCondFraction () const
double getExtCa () const
Set external conc.
double getICa () const
double getIntCa () const
Set external conc.
double getIntCaOffset () const
double getIntCaScale () const
double getKMg_A () const
double getKMg_B () const
double getPermeability () const
double getTemperature () const
NMDAChan ()
void setCMg (double CMg)
void setCondFraction (double v)
void setExtCa (double conc)
void setIntCa (double conc)
void setIntCaOffset (double v)
void setIntCaScale (double v)
void setKMg_A (double Gbar)
void setKMg_B (double Ek)
void setPermeability (double permeability)
void setTemperature (double temperature)
void vProcess (const Eref &e, ProcPtr p)
void vReinit (const Eref &e, ProcPtr p)
~NMDAChan ()
Public Member Functions inherited from SynChan
void activation (double val)
double calcGk ()
Update alpha function terms for synaptic channel.
bool getNormalizeWeights () const
double getTau1 () const
double getTau2 () const
void normalizeGbar ()
void setNormalizeWeights (bool value)
void setTau1 (double tau1)
void setTau2 (double tau2)
SynChan ()
void vProcess (const Eref &e, ProcPtr p)
void vReinit (const Eref &e, ProcPtr p)
void vSetGbar (const Eref &e, double Gbar)
~SynChan ()
Public Member Functions inherited from ChanCommon
ChanCommon ()
double getGbar () const
Utility function to acces Gbar.
double getVm () const
Utility function to access Vm.
void sendProcessMsgs (const Eref &e, const ProcPtr info)
void sendReinitMsgs (const Eref &e, const ProcPtr info)
void updateIk ()
double vGetEk (const Eref &e) const override
double vGetGbar (const Eref &e) const override
double vGetGk (const Eref &e) const override
double vGetIk (const Eref &e) const override
double vGetModulation (const Eref &e) const override
void vHandleVm (double Vm) override
void vSetEk (const Eref &e, double Ek) override
void vSetGk (const Eref &e, double Gk) override
void vSetIk (const Eref &e, double Ic) override
void vSetModulation (const Eref &e, double modulation) override
virtual ~ChanCommon ()=0
Public Member Functions inherited from ChanBase
ChanBase ()
double getEk (const Eref &e) const
double getGbar (const Eref &e) const
double getGk (const Eref &e) const
double getIk (const Eref &e) const
double getModulation (const Eref &e) const
void handleVm (double Vm)
void process (const Eref &e, const ProcPtr info)
void reinit (const Eref &e, const ProcPtr info)
void setEk (const Eref &e, double Ek)
void setGbar (const Eref &e, double Gbar)
void setGk (const Eref &e, double Gk)
void setIk (const Eref &e, double Ic)
void setModulation (const Eref &e, double modulation)
virtual ~ChanBase ()=0
Static Public Member Functions
static const Cinfo * initCinfo ()
Static Public Member Functions inherited from SynChan
static const Cinfo * initCinfo ()
Static Public Member Functions inherited from ChanCommon
static const Cinfo * initCinfo ()
Specify the Class Info static variable for initialization.
Static Public Member Functions inherited from ChanBase
static SrcFinfo2< double, double > * channelOut ()
static SrcFinfo1< double > * IkOut ()
static const Cinfo * initCinfo ()
Specify the Class Info static variable for initialization.
static SrcFinfo1< double > * permeability ()
Private Attributes
double Cin_
double CMg_
[Mg] in mM
double condFraction_
double const_
double Cout_
double ICa_
double intCaOffset_
double intCaScale_
double KMg_A_
1/eta
double KMg_B_
1/gamma
double temperature_
Static Private Attributes
static const double valency_ = 2.0
Additional Inherited Members
Protected Member Functions inherited from ChanCommon
double getModulation () const
Protected Attributes inherited from SynChan
double activation_
double dt_
double norm_
int normalizeWeights_
double tau1_
double tau2_
double X_
double xconst1_
double xconst2_
double Y_
double yconst1_
double yconst2_
Protected Attributes inherited from ChanCommon
double Vm_
Vm_ is input variable from compartment, used for most rates.
Detailed Description
The NMDAChan incorporates calculations for Mg block, Nernst potential and/or GHK estimates for the fraction of current carried by Ca. These can also be done by messaging but it is messy and slow, so I've lumped them. Also I've assumed that we're only dealing with the GHK equation for Ca. This is not so good considering that other ions also go through the channel.
Definition at line 21 of file NMDAChan.h.
Constructor & Destructor Documentation
NMDAChan()
NMDAChan::NMDAChan ()
Definition at line 168 of file NMDAChan.cpp.
    :
        KMg_A_( 1.0 ), // These are NOT the same as the A, B state
        KMg_B_( 1.0 ), //. variables used for Exp Euler integration.
        CMg_( 1.0 ),
        temperature_( 300 ),
        Cout_( 1.5 ),
        Cin_( 0.0008 ),
        intCaScale_( 1.0 ),
        intCaOffset_( 0.0 ),
        condFraction_( 0.02 ),
        ICa_( 0.0 ),
        const_( FaradayConst * valency_ / (GasConst * temperature_ ) )
{;}
References Cin_, CMg_, condFraction_, const_, Cout_, FaradayConst, GasConst, ICa_, intCaOffset_, intCaScale_, KMg_A_, KMg_B_, temperature_, and valency_.
~NMDAChan()
NMDAChan::~NMDAChan ()
Definition at line 183 of file NMDAChan.cpp.
{;}
Member Function Documentation
assignIntCa()
void NMDAChan::assignIntCa (double v)
Definition at line 306 of file NMDAChan.cpp.
{
    Cin_ = v * intCaScale_ + intCaOffset_;
}
References Cin_, intCaOffset_, and intCaScale_.
Referenced by initCinfo().
getCMg()
double NMDAChan::getCMg () const
Definition at line 222 of file NMDAChan.cpp.
{
    return CMg_;
}
References CMg_.
Referenced by initCinfo().
getCondFraction()
double NMDAChan::getCondFraction () const
Definition at line 279 of file NMDAChan.cpp.
{
    return condFraction_;
}
References condFraction_.
Referenced by initCinfo().
getExtCa()
double NMDAChan::getExtCa () const
Set external conc.
Definition at line 235 of file NMDAChan.cpp.
{
    return Cout_;
}
References Cout_.
Referenced by initCinfo().
getICa()
double NMDAChan::getICa () const
Definition at line 284 of file NMDAChan.cpp.
{
    return ICa_;
}
References ICa_.
Referenced by initCinfo().
getIntCa()
double NMDAChan::getIntCa () const
Set external conc.
Definition at line 249 of file NMDAChan.cpp.
{
    return Cin_;
}
References Cin_.
Referenced by initCinfo().
getIntCaOffset()
double NMDAChan::getIntCaOffset () const
Definition at line 269 of file NMDAChan.cpp.
{
    return intCaOffset_;
}
References intCaOffset_.
Referenced by initCinfo().
getIntCaScale()
double NMDAChan::getIntCaScale () const
Definition at line 259 of file NMDAChan.cpp.
{
    return intCaScale_;
}
References intCaScale_.
Referenced by initCinfo().
getKMg_A()
double NMDAChan::getKMg_A () const
Definition at line 198 of file NMDAChan.cpp.
{
    return KMg_A_;
}
References KMg_A_.
Referenced by initCinfo().
getKMg_B()
double NMDAChan::getKMg_B () const
Definition at line 210 of file NMDAChan.cpp.
{
    return KMg_B_;
}
References KMg_B_.
Referenced by initCinfo().
getPermeability()
double NMDAChan::getPermeability () const
getTemperature()
double NMDAChan::getTemperature () const
Definition at line 289 of file NMDAChan.cpp.
{
    return temperature_;
}
References temperature_.
Referenced by initCinfo().
initCinfo()
const Cinfo * NMDAChan::initCinfo () static
Definition at line 27 of file NMDAChan.cpp.
{
    // Shared messages
    // Dest definitions
    // Field definitions
    static ValueFinfo< NMDAChan, double > KMg_A( "KMg_A",
            "1/eta",
            &NMDAChan::setKMg_A,
            &NMDAChan::getKMg_A
        );
    static ValueFinfo< NMDAChan, double > KMg_B( "KMg_B",
            "1/gamma",
            &NMDAChan::setKMg_B,
            &NMDAChan::getKMg_B
        );
    static ValueFinfo< NMDAChan, double > CMg( "CMg",
            "[Mg] in mM",
            &NMDAChan::setCMg,
            &NMDAChan::getCMg
        );
    static ValueFinfo< NMDAChan, double > temperature( "temperature",
            "Temperature in degrees Kelvin.",
            &NMDAChan::setTemperature,
            &NMDAChan::getTemperature
        );
    static ValueFinfo< NMDAChan, double > extCa( "extCa",
            "External concentration of Calcium in millimolar",
            &NMDAChan::setExtCa,
            &NMDAChan::getExtCa
        );
    static ValueFinfo< NMDAChan, double > intCa( "intCa",
            "Internal concentration of Calcium in millimolar."
            "This is the final value used by the internal calculations, "
            "and may also be updated by the assignIntCa message after "
            "offset and scaling.",
            &NMDAChan::setIntCa,
            &NMDAChan::getIntCa
        );
    static ValueFinfo< NMDAChan, double > intCaScale( "intCaScale",
            "Scale factor for internal concentration of Calcium in mM, "
            "applied to values coming in through the assignIntCa message. "
            "Required because in many models the units of calcium may "
            "differ. ",
            &NMDAChan::setIntCaScale,
            &NMDAChan::getIntCaScale
        );
    static ValueFinfo< NMDAChan, double > intCaOffset( "intCaOffset",
            "Offsetfor internal concentration of Calcium in mM, "
            "applied _after_ the scaling to mM is done. "
            "Applied to values coming in through the assignIntCa message. "
            "Required because in many models the units of calcium may "
            "differ. ",
            &NMDAChan::setIntCaOffset,
            &NMDAChan::getIntCaOffset
        );
    static ValueFinfo< NMDAChan, double > condFraction( "condFraction",
            "Fraction of total channel conductance that is due to the "
            "passage of Ca ions. This is related to the ratio of "
            "permeabilities of different ions, and is typically in "
            "the range of 0.02. This small fraction is largely because "
            "the concentrations of Na and K ions are far larger than that "
            "of Ca. Thus, even though the channel is more permeable to "
            "Ca, the conductivity and hence current due to Ca is smaller. ",
            &NMDAChan::setCondFraction,
            &NMDAChan::getCondFraction
        );
    static ReadOnlyValueFinfo< NMDAChan, double > ICa( "ICa",
            "Current carried by Ca ions",
            &NMDAChan::getICa
        );
    static ElementValueFinfo< ChanBase, double > permeability(
            "permeability",
            "Permeability. Alias for Gbar. Note that the mapping is not"
            " really correct. Permeability is in units of m/s whereas "
            "Gbar is 1/ohm. Some nasty scaling is involved in the "
            "conversion, some of which itself involves concentration "
            "variables. Done internally. ",
            &ChanBase::setGbar,
            &ChanBase::getGbar
        );
        static DestFinfo assignIntCa( "assignIntCa",
            "Assign the internal concentration of Ca. The final value "
            "is computed as: "
            "     intCa = assignIntCa * intCaScale + intCaOffset ",
            new OpFunc1< NMDAChan,  double >( &NMDAChan::assignIntCa )
        );
    static Finfo* NMDAChanFinfos[] =
    {
        &KMg_A,         // Value
        &KMg_B,         // Value
        &CMg,           // Value
        &temperature,           // Value
        &extCa,         // Value
        &intCa,         // Value
        &intCaScale,            // Value
        &intCaOffset,           // Value
        &condFraction,          // Value
        &ICa,           // ReadOnlyValue
        &permeability,          // ElementValue
        &assignIntCa,           // Dest
        ICaOut(),           // Src
    };
    static string doc[] =
    {
        "Name", "NMDAChan",
        "Author", "Upinder S. Bhalla, 2007, NCBS",
        "Description", "NMDAChan: Ligand-gated ion channel incorporating "
                "both the Mg block and a GHK calculation for Calcium "
                "component of the current carried by the channel. "
                "Assumes a steady reversal potential regardless of "
                "Ca gradients. "
                "Derived from SynChan. "
    };
    static Dinfo< NMDAChan > dinfo;
    static Cinfo NMDAChanCinfo(
        "NMDAChan",
        SynChan::initCinfo(),
        NMDAChanFinfos,
        sizeof( NMDAChanFinfos )/sizeof(Finfo *),
        &dinfo,
        doc,
        sizeof( doc ) / sizeof( string )
    );
    return &NMDAChanCinfo;
}
References assignIntCa(), Cinfo::Cinfo(), DestFinfo::DestFinfo(), ElementValueFinfo< T, F >::ElementValueFinfo(), getCMg(), getCondFraction(), getExtCa(), ChanBase::getGbar(), getICa(), getIntCa(), getIntCaOffset(), getIntCaScale(), getKMg_A(), getKMg_B(), getTemperature(), ICaOut(), SynChan::initCinfo(), OpFunc1< T, A >::OpFunc1(), ReadOnlyValueFinfo< T, F >::ReadOnlyValueFinfo(), setCMg(), setCondFraction(), setExtCa(), ChanBase::setGbar(), setIntCa(), setIntCaOffset(), setIntCaScale(), setKMg_A(), setKMg_B(), setTemperature(), and ValueFinfo< T, F >::ValueFinfo().
setCMg()
void NMDAChan::setCMg (double CMg)
Definition at line 214 of file NMDAChan.cpp.
{
    if ( CMg < EPSILON ) {
        cout << "Error: CMg = " << CMg << " must be > 0. Not set.\n";
    } else {
        CMg_ = CMg;
    }
}
References CMg_, and EPSILON.
Referenced by initCinfo().
setCondFraction()
void NMDAChan::setCondFraction (double v)
Definition at line 274 of file NMDAChan.cpp.
{
    condFraction_ = v;
}
References condFraction_.
Referenced by initCinfo().
setExtCa()
void NMDAChan::setExtCa (double conc)
Definition at line 227 of file NMDAChan.cpp.
{
    if ( Cout < EPSILON ) {
        cout << "Error: Cout = " << Cout << " must be > 0. Not set.\n";
    } else {
        Cout_ = Cout;
    }
}
References Cout_, and EPSILON.
Referenced by initCinfo().
setIntCa()
void NMDAChan::setIntCa (double conc)
Definition at line 240 of file NMDAChan.cpp.
{
    if ( Cin < 0.0 ) {
        cout << "Error: IntCa = " << Cin << " must be > 0. Not set.\n";
    } else {
        Cin_ = Cin;
    }
}
References Cin_.
Referenced by initCinfo().
setIntCaOffset()
void NMDAChan::setIntCaOffset (double v)
Definition at line 264 of file NMDAChan.cpp.
{
    intCaOffset_ = v;
}
References intCaOffset_.
Referenced by initCinfo().
setIntCaScale()
void NMDAChan::setIntCaScale (double v)
Definition at line 254 of file NMDAChan.cpp.
{
    intCaScale_ = v;
}
References intCaScale_.
Referenced by initCinfo().
setKMg_A()
void NMDAChan::setKMg_A (double Gbar)
Definition at line 190 of file NMDAChan.cpp.
{
    if ( KMg_A < EPSILON ) {
        cout << "Error: KMg_A=" << KMg_A << " must be > 0. Not set.\n";
    } else {
        KMg_A_ = KMg_A;
    }
}
References EPSILON, and KMg_A_.
Referenced by initCinfo().
setKMg_B()
void NMDAChan::setKMg_B (double Ek)
Definition at line 202 of file NMDAChan.cpp.
{
    if ( KMg_B < EPSILON ) {
        cout << "Error: KMg_B=" << KMg_B << " must be > 0. Not set.\n";
    } else {
        KMg_B_ = KMg_B;
    }
}
References EPSILON, and KMg_B_.
Referenced by initCinfo().
setPermeability()
void NMDAChan::setPermeability (double permeability)
setTemperature()
void NMDAChan::setTemperature (double temperature)
Definition at line 293 of file NMDAChan.cpp.
{
    if ( temperature < EPSILON ) {
        cout << "Error: temperature = " << temperature << " must be > 0. Not set.\n";
        return;
    }
    temperature_ = temperature;
    const_ = ( FaradayConst / GasConst ) * valency_ / temperature_;
}
References const_, EPSILON, FaradayConst, GasConst, temperature_, and valency_.
Referenced by initCinfo().
vProcess()
void NMDAChan::vProcess (const Eref & e, ProcPtr info) virtual
Note the implicit mapping between permeability and conductance. From the GENESIS source code: A thought about the units, by EDS 6/95 (based on Hille 92): Units: p in M/s EF/RT and z are dimensionless F in C/mol Cin and Cout in mM==mol/m^3 Then Ik is really in units of C/s/m^2==A/m^2, so we compute a current density. As we replace in practice p by Gbar, which has already been scaled for surface, we get rid of the density factor.
Implements ChanBase.
Definition at line 330 of file NMDAChan.cpp.
{
    // First do the regular channel current calculations for the
    // summed ions, in which the NMDAR behaves like a regular channel
    // modulo the Mg block.
    double Gk = SynChan::calcGk();
    double KMg = KMg_A_ * exp(Vm_/KMg_B_);
    Gk *= KMg / (KMg + CMg_);
    ChanBase::setGk( e, Gk );
    ChanCommon::updateIk();
    // Here we do the calculations for the Ca portion of the current.
    // Total current is still done using a regular reversal potl for chan.
    // Here we use Gk = Permeability * Z * FaradayConst * area / dV.
    // Note that Cin and Cout are in moles/m^3, and FaradayConst is in
    // Coulombs/mole.
    //
    // The GHK flux equation for an ion S (Hille 2001):
    // \Phi_{S} = P_{S}z_{S}^2\frac{V_{m}F^{2}}{RT}\frac{[\mbox{S}]_{i} - [\mbox{S}]_{o}\exp(-z_{S}V_{m}F/RT)}{1 - \exp(-z_{S}V_{m}F/RT)}
    // where
    // \PhiS is the current across the membrane carried by ion S, measured in amperes per square meter (A·m−2)
    // PS is the permeability of the membrane for ion S measured in m·s−1
    // zS is the valence of ion S
    // Vm is the transmembrane potential in volts
    // F is the Faraday constant, equal to 96,485 C·mol−1 or J·V−1·mol−1
    // R is the gas constant, equal to 8.314 J·K−1·mol−1
    // T is the absolute temperature, measured in Kelvin (= degrees Celsius + 273.15)
    // [S]i is the intracellular concentration of ion S, measured in mol·m−3 or mmol·l−1
    // [S]o is the extracellular concentration of ion S, measured in mol·m−3
    //
    // Put this into cleaner text, we get
    //
    // ICa (A/m^2) = perm * Z * Vm * F * const * (Cin-Cout * e2exponent)
    //                                             ----------------------
    //                                                (1-e2exponent)
    //
    // where const = zF/RT (Coulombs/J/K * K ) = Coul/J = 1/V
    // and exponent = const * Vm ( unitless)
    //
    // We want ICa in Amps. We use perm times area which is m^3/s
    // Flux ( mol/sec) = Perm (m/s ) * area (m^2) * (Cout - Cin) (mol/m^3)
    //
    // But we also have
    //
    // Flux (mol/sec) = Gk ( Coul/(sec*V) ) * dV (V) / (zF (Coul/Mol))
    //
    // So Perm( m/s ) * Area = Gk * dV / (Z*F * (cout - cin) )
    //
    // Note that dV should be just the Nernst potential for the ion, since
    // the calculation of flux from permeability assumes no extra flux
    // due to charge gradients.
    //
    // e2exponent = exp( -const * Vm)
    //
    // ICa (A) = (Gk * dV / (zF*(cout-cin) ) * Vm * zF * const * (Cin-Cout * e2exponent)
    //                                             ----------------------
    //                                                (1-e2exponent)
    //
    //                    = Gk * dV * Vm * const*(cin - cout*e2exponent)
    //                                     ------------------------------
    //                                     (cout-cin) *  (1-e2exponent)
    //
    // Note how the calculation for Perm in terms of Gk has to use
    // different terms for dV and conc, than the GHK portion.
    //
    // A further factor comes in because we want to relate the Gk for
    // Ca to that for the channel as a whole. We know from Hille that
    // the permeability of NMDAR for Ca is about 4x that for Na.
    //
    // Here is the calculation:
    // Gchan = GNa + GK + GCa                                   (Eq1)
    // IChan = 0 = GNa*ENa + GK*EK + GCa*ECa                    (Eq2)
    //
    // Perm_Ca * area = GCa * ECa / ( ZF * (cout - cin ) )      (Eq3a)
    // Perm_Na * area = GNa * ENa / ( ZF * (cout - cin ) )      (Eq3b)
    // But Perm_Na ~ 0.25 * perm_Ca
    // So GNa*ENa / (F * (cout - cin ) ) ~ 0.25*GCa*ECa/(2F*(cout-cin) )
    // Cancelling
    //
    // GNa * 0.060 / (cout - cin|Na) ~ 0.25*GCa*0.128/(2*(cout-cin|Ca))
    // GNa * 0.060 / 130 ~ GCa * 0.25 * 0.128 / (2*1.5)
    // GNa ~ GCa * 130 * 0.25 * 0.128 / ( 2 * 1.5 * 0.060)
    // GNa ~ 23 GCa (!!!!!!)                                    (Eq4)
    //
    // Now plug into Eq2:
    //
    // 0 = 23GCa*0.06 - GK*0.08 + GCa*0.128
    // So
    // GK = GCa(0.06*23 + 0.128) / 0.06 = 25*GCa.   (Not surprised any more)
    //
    // Finally, put into Eq1:
    //
    // Gchan = 23GCa + 25GCa + GCa
    // So GCa = Gchan / 49. So condFraction ~0.02 in the vicinity of 0.0mV.
    //
    // Rather than build in this calculation, I'll just provide the user
    // with a scaling field to use and set it to the default of 0.02
    //
    double ErevCa = log( Cout_ / Cin_ ) / const_;
    double dV = ErevCa;
    //double dV = ErevCa - Vm_;
    // double dV = vGetEk( e ) - Vm_;
    // double dV = Vm_;
    double exponent = const_ * Vm_;
    double e2e = exp( -exponent );
    if ( fabs( exponent) < 0.00001 ) { // Exponent too near zero, use Taylor
        ICa_ = Gk * dV * exponent * ( Cin_ - Cout_ * e2e ) /
                ( ( Cin_ - Cout_ ) * (1 - 0.5 * exponent ) );
    } else {
        ICa_ = Gk * dV * exponent * ( Cin_ - Cout_ * e2e ) /
                ( ( Cin_ - Cout_ ) * (1 - e2e ) );
    }
    ICa_ *= condFraction_; // Scale Ca current by fraction carried by Ca.
    sendProcessMsgs( e, info );
    ICaOut()->send( e, ICa_ );
}
References SynChan::calcGk(), Cin_, CMg_, condFraction_, const_, Cout_, ICa_, ICaOut(), KMg_A_, KMg_B_, SrcFinfo1< T >::send(), ChanCommon::sendProcessMsgs(), ChanBase::setGk(), ChanCommon::updateIk(), and ChanCommon::Vm_.
vReinit()
void NMDAChan::vReinit (const Eref & e, ProcPtr p) virtual
Implements ChanBase.
Definition at line 449 of file NMDAChan.cpp.
{
    SynChan::vReinit( e, info );
    if ( CMg_ < EPSILON || KMg_B_ < EPSILON || KMg_A_ < EPSILON ) {
        cout << "Error: NMDAChan::innerReinitFunc: fields KMg_A, KMg_B, CMg\nmust be greater than zero. Resetting to 1 to avoid numerical errors\n";
        if ( CMg_ < EPSILON ) CMg_ = 1.0;
        if ( KMg_B_ < EPSILON ) KMg_B_ = 1.0;
        if ( KMg_A_ < EPSILON ) KMg_A_ = 1.0;
    }
    sendReinitMsgs( e, info );
    ICaOut()->send( e, 0.0 );
}
References CMg_, EPSILON, ICaOut(), KMg_A_, KMg_B_, SrcFinfo1< T >::send(), ChanCommon::sendReinitMsgs(), and SynChan::vReinit().
Member Data Documentation
Cin_
double NMDAChan::Cin_ private
Definition at line 79 of file NMDAChan.h.
Referenced by assignIntCa(), getIntCa(), NMDAChan(), setIntCa(), and vProcess().
CMg_
double NMDAChan::CMg_ private
[Mg] in mM
Definition at line 72 of file NMDAChan.h.
Referenced by getCMg(), NMDAChan(), setCMg(), vProcess(), and vReinit().
condFraction_
double NMDAChan::condFraction_ private
Definition at line 82 of file NMDAChan.h.
Referenced by getCondFraction(), NMDAChan(), setCondFraction(), and vProcess().
const_
double NMDAChan::const_ private
Definition at line 84 of file NMDAChan.h.
Referenced by NMDAChan(), setTemperature(), and vProcess().
Cout_
double NMDAChan::Cout_ private
Definition at line 78 of file NMDAChan.h.
Referenced by getExtCa(), NMDAChan(), setExtCa(), and vProcess().
ICa_
double NMDAChan::ICa_ private
Definition at line 83 of file NMDAChan.h.
Referenced by getICa(), NMDAChan(), and vProcess().
intCaOffset_
double NMDAChan::intCaOffset_ private
Definition at line 81 of file NMDAChan.h.
Referenced by assignIntCa(), getIntCaOffset(), NMDAChan(), and setIntCaOffset().
intCaScale_
double NMDAChan::intCaScale_ private
Definition at line 80 of file NMDAChan.h.
Referenced by assignIntCa(), getIntCaScale(), NMDAChan(), and setIntCaScale().
KMg_A_
double NMDAChan::KMg_A_ private
1/eta
Definition at line 68 of file NMDAChan.h.
Referenced by getKMg_A(), NMDAChan(), setKMg_A(), vProcess(), and vReinit().
KMg_B_
double NMDAChan::KMg_B_ private
1/gamma
Definition at line 70 of file NMDAChan.h.
Referenced by getKMg_B(), NMDAChan(), setKMg_B(), vProcess(), and vReinit().
temperature_
double NMDAChan::temperature_ private
Original Gk passed by NMDA channel, we keep this separate from Gk so that the computed Gk can be recorded without being overwritten by origChannel message.
Definition at line 77 of file NMDAChan.h.
Referenced by getTemperature(), NMDAChan(), and setTemperature().
valency_
const double NMDAChan::valency_ = 2.0 static private
Definition at line 87 of file NMDAChan.h.
Referenced by NMDAChan(), and setTemperature().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/biophysics/NMDAChan.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/biophysics/NMDAChan.cpp