MOOSE - Multiscale Object Oriented Simulation Environment: GetHopFunc< A > Class Template Reference
GetHopFunc< A > Class Template Reference
#include <HopFunc.h>
Public Member Functions
GetHopFunc (HopIndex hopIndex)
void getLocalFieldVec (const Eref &er, vector< A > &ret, const GetOpFuncBase< A > *op) const
void getLocalVec (Element *elm, vector< A > &ret, const GetOpFuncBase< A > *op) const
void getMultiNodeVec (const Eref &e, vector< A > &ret, const GetOpFuncBase< A > *op) const
void getRemoteFieldVec (const Eref &e, vector< A > &ret, const GetOpFuncBase< A > *op) const
void op (const Eref &e, A *ret) const
void opGetVec (const Eref &e, vector< A > &ret, const GetOpFuncBase< A > *op) const
Public Member Functions inherited from OpFunc1Base< A * >
bool checkFinfo (const Finfo *s) const
const OpFunc * makeHopFunc (HopIndex hopIndex) const
void opBuffer (const Eref &e, double *buf) const
Executes the OpFunc by converting args.
virtual void opVec (const Eref &e, const vector< A * > &arg, const OpFunc1Base< A * > *op) const
void opVecBuffer (const Eref &e, double *buf) const
Executes the OpFunc for all data by converting a vector of args.
string rttiType () const
Public Member Functions inherited from OpFunc
OpFunc ()
unsigned int opIndex () const
bool setIndex (unsigned int i)
Used when rebuilding the Fid->OpFunc mapping.
virtual ~OpFunc ()
Private Attributes
HopIndex hopIndex_
Additional Inherited Members
Static Public Member Functions inherited from OpFunc
static const OpFunc * lookop (unsigned int opIndex)
static unsigned int rebuildOpIndex ()
cleans out the entire Ops vector. Returns size of orig vector.
Detailed Description
template<class A>
class GetHopFunc< A >
Definition at line 407 of file HopFunc.h.
Constructor & Destructor Documentation
GetHopFunc()
template<class A > GetHopFunc< A >::GetHopFunc (HopIndex hopIndex) inline
Definition at line 410 of file HopFunc.h.
                : hopIndex_( hopIndex )
        {;}
References GetHopFunc< A >::hopIndex_.
Member Function Documentation
getLocalFieldVec()
template<class A > void GetHopFunc< A >::getLocalFieldVec (const Eref & er, vector< A > & ret, const GetOpFuncBase< A > * op) const inline
Definition at line 420 of file HopFunc.h.
        {
            unsigned int p = er.dataIndex();
            Element* elm = er.element();
            unsigned int numField = elm->numField(
                            p - elm->localDataStart() );
            for ( unsigned int q = 0; q < numField; ++q ) {
                Eref temp( elm, p, q );
                ret.push_back( op->returnOp( temp ) );
            }
        }
References Eref::dataIndex(), Eref::element(), Eref::Eref(), Element::localDataStart(), and Element::numField().
Referenced by GetHopFunc< A >::opGetVec().
getLocalVec()
template<class A > void GetHopFunc< A >::getLocalVec (Element * elm, vector< A > & ret, const GetOpFuncBase< A > * op) const inline
Definition at line 446 of file HopFunc.h.
        {
            unsigned int start = elm->localDataStart();
            unsigned int end = start + elm->numLocalData();
            for ( unsigned int p = start; p < end; ++p ) {
                Eref er( elm, p, 0 );
                ret.push_back( op->returnOp( er ) );
            }
        }
References Eref::Eref(), Element::localDataStart(), and Element::numLocalData().
Referenced by GetHopFunc< A >::getMultiNodeVec(), and GetHopFunc< A >::opGetVec().
getMultiNodeVec()
template<class A > void GetHopFunc< A >::getMultiNodeVec (const Eref & e, vector< A > & ret, const GetOpFuncBase< A > * op) const inline
Definition at line 457 of file HopFunc.h.
        {
            Element* elm = e.element();
            vector< vector< double > > buf;
            vector< unsigned int > numOnNode;
            remoteGetVec( e, hopIndex_.bindIndex(), buf, numOnNode );
            assert( numOnNode.size() == mooseNumNodes() );
            assert( buf.size() == mooseNumNodes() );
            assert( buf.size() == numOnNode.size() );
            for ( unsigned int i = 0; i < mooseNumNodes(); ++i ) {
                if ( i == mooseMyNode() ) {
                    getLocalVec( elm, ret, op );
                } else {
                    vector< double >& temp = buf[i];
                    assert( static_cast< unsigned int >( temp[0] ) ==
                                            numOnNode[i] );
                    double* val = &temp[1]; // zeroth entry is numOnNode.
                    for ( unsigned int j = 0; j < numOnNode[i]; ++j ) {
                    // val++; // Skip the index.
                    // ret.push_back( Conv< A >::buf2val( &temp[k + 1] ) );
                        ret.push_back( Conv< A >::buf2val( &val ) );
                    }
                }
            }
        }
References HopIndex::bindIndex(), Eref::element(), GetHopFunc< A >::getLocalVec(), GetHopFunc< A >::hopIndex_, mooseMyNode(), mooseNumNodes(), and remoteGetVec().
Referenced by GetHopFunc< A >::opGetVec().
getRemoteFieldVec()
template<class A > void GetHopFunc< A >::getRemoteFieldVec (const Eref & e, vector< A > & ret, const GetOpFuncBase< A > * op) const inline
Definition at line 433 of file HopFunc.h.
        {
            vector< double > buf;
            remoteFieldGetVec( e, hopIndex_.bindIndex(), buf );
            assert( buf.size() > 0 );
            unsigned int numField = static_cast<unsigned int>(buf[0]);
            double* val = &buf[1]; // zeroth entry is numField.
            for ( unsigned int j = 0; j < numField; ++j ) {
                ret.push_back( Conv< A >::buf2val( &val ) );
            }
        }
References HopIndex::bindIndex(), GetHopFunc< A >::hopIndex_, and remoteFieldGetVec().
Referenced by GetHopFunc< A >::opGetVec().
op()
template<class A > void GetHopFunc< A >::op (const Eref & e, A * ret) const inline virtual
Implements OpFunc1Base< A * >.
Definition at line 414 of file HopFunc.h.
        {
            double* buf = remoteGet( e, hopIndex_.bindIndex() );
            *ret = Conv< A >::buf2val( &buf );
        }
References HopIndex::bindIndex(), GetHopFunc< A >::hopIndex_, and remoteGet().
opGetVec()
template<class A > void GetHopFunc< A >::opGetVec (const Eref & e, vector< A > & ret, const GetOpFuncBase< A > * op) const inline
Definition at line 484 of file HopFunc.h.
        {
            Element* elm = e.element();
            ret.clear();
            ret.reserve( elm->numData() );
            if ( elm->hasFields() ) {
                if ( e.getNode() == mooseMyNode() ) {
                    getLocalFieldVec( e, ret, op );
                } else {
                    getRemoteFieldVec( e, ret, op );
                }
            } else {
                if ( mooseNumNodes() == 1 || elm->isGlobal() ) {
                    getLocalVec( elm, ret, op );
                } else {
                    getMultiNodeVec( e, ret, op );
                }
            }
        }
References Eref::element(), GetHopFunc< A >::getLocalFieldVec(), GetHopFunc< A >::getLocalVec(), GetHopFunc< A >::getMultiNodeVec(), Eref::getNode(), GetHopFunc< A >::getRemoteFieldVec(), Element::hasFields(), Element::isGlobal(), mooseMyNode(), mooseNumNodes(), and Element::numData().
Member Data Documentation
hopIndex_
template<class A > HopIndex GetHopFunc< A >::hopIndex_ private
Definition at line 505 of file HopFunc.h.
Referenced by GetHopFunc< A >::GetHopFunc(), GetHopFunc< A >::getMultiNodeVec(), GetHopFunc< A >::getRemoteFieldVec(), and GetHopFunc< A >::op().
The documentation for this class was generated from the following file:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/basecode/HopFunc.h