MOOSE - Multiscale Object Oriented Simulation Environment: MarkovOdeSolver Class Reference
MarkovOdeSolver Class Reference
#include <MarkovOdeSolver.h>
Public Member Functions
double getAbsoluteAccuracy () const
double getInternalDt () const
bool getIsInitialized () const
string getMethod () const
double getRelativeAccuracy () const
void handleQ (vector< vector< double > >)
void init (vector< double >)
MarkovOdeSolver ()
void process (const Eref &e, ProcPtr info)
void reinit (const Eref &e, ProcPtr info)
void setAbsoluteAccuracy (double value)
void setInternalDt (double value)
void setMethod (string method)
void setRelativeAccuracy (double value)
~MarkovOdeSolver ()
Static Public Member Functions
static const Cinfo * initCinfo ()
Private Member Functions
void OdeSystem (const vector< double > &y, vector< double > &dydt)
Private Attributes
double absAccuracy_
vector< double > initialState_
double internalStepSize_
bool isInitialized_
string method_
unsigned int nVars_
vector< vector< double > > Q_
double relAccuracy_
vector< double > state_
vector< double > stateOde_
Detailed Description
Definition at line 30 of file MarkovOdeSolver.h.
Constructor & Destructor Documentation
MarkovOdeSolver()
MarkovOdeSolver::MarkovOdeSolver ()
Definition at line 139 of file MarkovOdeSolver.cpp.
{
    isInitialized_ = 0;
    method_ = "rk5";
#ifdef  USE_GSL
    gslStepType_ = gsl_odeiv_step_rkf45;
    gslEvolve_ = NULL;
    gslControl_ = NULL;
    gslStep_ = 0;
#endif     /* -----  not USE_GSL  ----- */
    nVars_ = 0;
    absAccuracy_ = 1e-8;
    relAccuracy_ = 1e-8;
    internalStepSize_ = 1.0e-6;
}
References absAccuracy_, internalStepSize_, isInitialized_, method_, nVars_, and relAccuracy_.
~MarkovOdeSolver()
MarkovOdeSolver::~MarkovOdeSolver ()
Definition at line 155 of file MarkovOdeSolver.cpp.
{
#ifdef  USE_GSL
    if ( gslEvolve_ )
        gsl_odeiv_evolve_free( gslEvolve_ );
    if ( gslControl_ )
        gsl_odeiv_control_free( gslControl_ );
    if ( gslStep_ )
        gsl_odeiv_step_free( gslStep_ );
#endif     /* -----  not USE_GSL  ----- */
}
Member Function Documentation
getAbsoluteAccuracy()
double MarkovOdeSolver::getAbsoluteAccuracy () const
Definition at line 288 of file MarkovOdeSolver.cpp.
{
    return absAccuracy_;
}
References absAccuracy_.
Referenced by initCinfo().
getInternalDt()
double MarkovOdeSolver::getInternalDt () const
Definition at line 297 of file MarkovOdeSolver.cpp.
{
    return internalStepSize_;
}
References internalStepSize_.
Referenced by initCinfo().
getIsInitialized()
bool MarkovOdeSolver::getIsInitialized () const
Definition at line 212 of file MarkovOdeSolver.cpp.
{
    return isInitialized_;
}
References isInitialized_.
Referenced by initCinfo().
getMethod()
string MarkovOdeSolver::getMethod () const
Definition at line 217 of file MarkovOdeSolver.cpp.
{
    return method_;
}
References method_.
Referenced by initCinfo().
getRelativeAccuracy()
double MarkovOdeSolver::getRelativeAccuracy () const
Definition at line 278 of file MarkovOdeSolver.cpp.
{
    return relAccuracy_;
}
References relAccuracy_.
Referenced by initCinfo().
handleQ()
void MarkovOdeSolver::handleQ (vector< vector< double > >)
Definition at line 436 of file MarkovOdeSolver.cpp.
{
    Q_ = Q;
}
References Q_.
Referenced by initCinfo().
init()
void MarkovOdeSolver::init (vector< double > initialState)
Definition at line 312 of file MarkovOdeSolver.cpp.
{
    nVars_ = initialState.size();
    state_ = initialState;
    initialState_ = initialState;
    Q_.resize( nVars_ );
    for ( unsigned int i = 0; i < nVars_; ++i )
        Q_[i].resize( nVars_, 0.0 );
    stateOde_.resize( nVars_ );
    isInitialized_ = 1;
#ifdef  USE_GSL
    assert( gslStepType_ != 0 );
    if ( gslStep_ )
        gsl_odeiv_step_free(gslStep_);
    gslStep_ = gsl_odeiv_step_alloc( gslStepType_, nVars_ );
    assert( gslStep_ != 0 );
    if ( !gslEvolve_ )
        gslEvolve_ = gsl_odeiv_evolve_alloc(nVars_);
    else
        gsl_odeiv_evolve_reset(gslEvolve_);
    assert(gslEvolve_ != 0);
    if ( !gslControl_ )
        gslControl_ = gsl_odeiv_control_y_new( absAccuracy_, relAccuracy_ );
    else
        gsl_odeiv_control_init(gslControl_,absAccuracy_, relAccuracy_, 1, 0);
    assert(gslControl_!= 0);
    gslSys_.function = &MarkovOdeSolver::evalSystem;
    gslSys_.jacobian = 0;
    gslSys_.dimension = nVars_;
    gslSys_.params = static_cast< void * >( &Q_ );
#endif     /* -----  not USE_GSL  ----- */
}
References initialState_, isInitialized_, nVars_, Q_, state_, and stateOde_.
Referenced by initCinfo().
initCinfo()
const Cinfo * MarkovOdeSolver::initCinfo () static
Definition at line 33 of file MarkovOdeSolver.cpp.
{
    // Field definitions
    static ReadOnlyValueFinfo< MarkovOdeSolver, bool > isInitialized(
        "isInitialized",
        "True if the message has come in to set solver parameters.",
        &MarkovOdeSolver::getIsInitialized
    );
    static ValueFinfo< MarkovOdeSolver, string > method( "method",
            "Numerical method to use.",
            &MarkovOdeSolver::setMethod,
            &MarkovOdeSolver::getMethod
                                                       );
    static ValueFinfo< MarkovOdeSolver, double > relativeAccuracy(
        "relativeAccuracy",
        "Accuracy criterion",
        &MarkovOdeSolver::setRelativeAccuracy,
        &MarkovOdeSolver::getRelativeAccuracy
    );
    static ValueFinfo< MarkovOdeSolver, double > absoluteAccuracy(
        "absoluteAccuracy",
        "Another accuracy criterion",
        &MarkovOdeSolver::setAbsoluteAccuracy,
        &MarkovOdeSolver::getAbsoluteAccuracy
    );
    static ValueFinfo< MarkovOdeSolver, double > internalDt(
        "internalDt",
        "internal timestep to use.",
        &MarkovOdeSolver::setInternalDt,
        &MarkovOdeSolver::getInternalDt
    );
    // DestFinfo definitions
    static DestFinfo init( "init",
                           "Initialize solver parameters.",
                           new OpFunc1< MarkovOdeSolver, vector< double > >
                           ( &MarkovOdeSolver::init )
                         );
    static DestFinfo handleQ( "handleQ",
                              "Handles information regarding the instantaneous rate matrix from "
                              "the MarkovRateTable class.",
                              new OpFunc1< MarkovOdeSolver, vector< vector< double > > >( &MarkovOdeSolver::handleQ) );
    static DestFinfo process( "process",
                              "Handles process call",
                              new ProcOpFunc< MarkovOdeSolver >( &MarkovOdeSolver::process ) );
    static DestFinfo reinit( "reinit",
                             "Handles reinit call",
                             new ProcOpFunc< MarkovOdeSolver >( &MarkovOdeSolver::reinit ) );
    // Shared definitions
    static Finfo* procShared[] =
    {
        &process, &reinit
    };
    static SharedFinfo proc( "proc",
                             "Shared message for process and reinit",
                             procShared, sizeof( procShared ) / sizeof( const Finfo* )
                           );
    static Finfo* MarkovOdeFinfos[] =
    {
        &isInitialized,         // ValueFinfo
        &method,                // ValueFinfo
        &relativeAccuracy,      // ValueFinfo
        &absoluteAccuracy,      // ValueFinfo
        &internalDt,            // ValueFinfo
        &init,                  // DestFinfo
        &handleQ,               // DestFinfo
        &proc,                  // SharedFinfo
        stateOut(),             // SrcFinfo
    };
    static string doc[] =
    {
        "Name", "MarkovOdeSolver",
        "Author", "Vishaka Datta (c) 2011, Dilawar Singh (c) 2018",
        "Description", "Solver for Markov Channel."
    };
    static Dinfo< MarkovOdeSolver > dinfo;
    static Cinfo MarkovOdeSolverCinfo(
        "MarkovOdeSolver",
        Neutral::initCinfo(),
        MarkovOdeFinfos,
        sizeof(MarkovOdeFinfos)/sizeof(Finfo *),
        &dinfo,
        doc,
        sizeof(doc) / sizeof(string)
    );
    return &MarkovOdeSolverCinfo;
}
References Cinfo::Cinfo(), DestFinfo::DestFinfo(), getAbsoluteAccuracy(), getInternalDt(), getIsInitialized(), getMethod(), getRelativeAccuracy(), handleQ(), init(), Neutral::initCinfo(), OpFunc1< T, A >::OpFunc1(), process(), ProcOpFunc< T >::ProcOpFunc(), ReadOnlyValueFinfo< T, F >::ReadOnlyValueFinfo(), reinit(), setAbsoluteAccuracy(), setInternalDt(), setMethod(), setRelativeAccuracy(), SharedFinfo::SharedFinfo(), stateOut(), and ValueFinfo< T, F >::ValueFinfo().
OdeSystem()
void MarkovOdeSolver::OdeSystem (const vector< double > & y, vector< double > & dydt) private
process()
void MarkovOdeSolver::process (const Eref & e, ProcPtr info)
Definition at line 352 of file MarkovOdeSolver.cpp.
{
    double nextt = p->currTime + p->dt;
    double t = p->currTime;
    double sum = 0;
    for ( unsigned int i = 0; i < nVars_; ++i )
        stateOde_[i] = state_[i];
#ifdef  USE_GSL
    while( t < nextt )
    {
        int status = gsl_odeiv_evolve_apply ( gslEvolve_, gslControl_, gslStep_, &gslSys_,
                &t, nextt, &internalStepSize_, &stateOde_[0]
                );
        //Simple idea borrowed from Dieter Jaeger's implementation of a Markov
        //channel to deal with potential round-off error.
        sum = 0;
        for ( unsigned int i = 0; i < nVars_; i++ )
            sum += stateOde_[i];
        for ( unsigned int i = 0; i < nVars_; i++ )
            stateOde_[i] /= sum;
        if( status != GSL_SUCCESS )
            break;
    }
#endif
#if USE_BOOST_ODE
    auto sys = [this](const vector<double>& dy, vector<double>& dydt, const double t)
    {
        this->OdeSystem(dy, dydt);
    };
    // It works well in practice for this setup.
    if( method_ == "rk5" || method_ == "gsl" || method_ == "boost" )
        odeint::integrate( sys, stateOde_, t, nextt, p->dt );
    else if( method_ == "rk5a" || method_ == "adaptive" )
        odeint::integrate_adaptive(
                odeint::make_controlled<rk_dopri_stepper_type_>( absAccuracy_, relAccuracy_ )
                , sys, stateOde_, t, nextt, p->dt
                );
    else if( method_ == "rk4" )
        odeint::integrate_const( rk4_stepper_type_()
                , sys, stateOde_, t, nextt, p->dt
                );
    else if ("rk54" == method_ )
        odeint::integrate_const( rk_karp_stepper_type_()
                , sys, stateOde_, t, nextt, p->dt
                );
    else if ("rkck" == method_ || "rkcka" == method_)
        odeint::integrate_adaptive(
                odeint::make_controlled<rk_karp_stepper_type_>( absAccuracy_, relAccuracy_ )
                , sys, stateOde_, t, nextt, p->dt
                );
    else if( method_ == "rk8a" || "rk8" == method_ )
        odeint::integrate_adaptive( rk_felhberg_stepper_type_()
                , sys, stateOde_, t, nextt, p->dt
                );
    else
        odeint::integrate( sys, stateOde_, t, nextt, p->dt );
#endif     /* -----  not USE_GSL  ----- */
    for ( unsigned int i = 0; i < nVars_; ++i )
        state_[i] = stateOde_[i];
    stateOut()->send( e, state_ );
}
References ProcInfo::currTime, ProcInfo::dt, nVars_, SrcFinfo1< T >::send(), state_, stateOde_, and stateOut().
Referenced by initCinfo().
reinit()
void MarkovOdeSolver::reinit (const Eref & e, ProcPtr info)
Definition at line 424 of file MarkovOdeSolver.cpp.
{
    state_ = initialState_;
    if ( initialState_.empty() )
    {
        cerr << "MarkovOdeSolver::reinit : "
             "Initial state has not been set. Solver has not been initialized."
             "Call init() before running.\n";
    }
    stateOut()->send( e, state_ );
}
References initialState_, SrcFinfo1< T >::send(), state_, and stateOut().
Referenced by initCinfo().
setAbsoluteAccuracy()
void MarkovOdeSolver::setAbsoluteAccuracy (double value)
Definition at line 292 of file MarkovOdeSolver.cpp.
{
    absAccuracy_ = value;
}
References absAccuracy_.
Referenced by initCinfo().
setInternalDt()
void MarkovOdeSolver::setInternalDt (double value)
Definition at line 302 of file MarkovOdeSolver.cpp.
{
    internalStepSize_ = value;
}
References internalStepSize_.
Referenced by initCinfo().
setMethod()
void MarkovOdeSolver::setMethod (string method)
Definition at line 222 of file MarkovOdeSolver.cpp.
{
    method_ = method;
#ifdef USE_GSL
    gslStepType_ = 0;
    if ( method == "rk2" )
    {
        gslStepType_ = gsl_odeiv_step_rk2;
    }
    else if ( method == "rk4" )
    {
        gslStepType_ = gsl_odeiv_step_rk4;
    }
    else if ( method == "rk5" )
    {
        gslStepType_ = gsl_odeiv_step_rkf45;
    }
    else if ( method == "rkck" )
    {
        gslStepType_ = gsl_odeiv_step_rkck;
    }
    else if ( method == "rk8pd" )
    {
        gslStepType_ = gsl_odeiv_step_rk8pd;
    }
    else if ( method == "rk2imp" )
    {
        gslStepType_ = gsl_odeiv_step_rk2imp;
    }
    else if ( method == "rk4imp" )
    {
        gslStepType_ = gsl_odeiv_step_rk4imp;
    }
    else if ( method == "bsimp" )
    {
        gslStepType_ = gsl_odeiv_step_rk4imp;
        cout << "Warning: implicit Bulirsch-Stoer method not yet implemented: needs Jacobian\n";
    }
    else if ( method == "gear1" )
    {
        gslStepType_ = gsl_odeiv_step_gear1;
    }
    else if ( method == "gear2" )
    {
        gslStepType_ = gsl_odeiv_step_gear2;
    }
    else
    {
        cout << "Warning: MarkovOdeSolver::innerSetMethod: method '" <<
             method << "' not known, using rk5\n";
        gslStepType_ = gsl_odeiv_step_rkf45;
    }
#endif
}
References method_.
Referenced by initCinfo().
setRelativeAccuracy()
void MarkovOdeSolver::setRelativeAccuracy (double value)
Definition at line 283 of file MarkovOdeSolver.cpp.
{
    relAccuracy_ = value;
}
References relAccuracy_.
Referenced by initCinfo().
Member Data Documentation
absAccuracy_
double MarkovOdeSolver::absAccuracy_ private
Definition at line 64 of file MarkovOdeSolver.h.
Referenced by getAbsoluteAccuracy(), MarkovOdeSolver(), and setAbsoluteAccuracy().
initialState_
vector< double > MarkovOdeSolver::initialState_ private
Definition at line 73 of file MarkovOdeSolver.h.
Referenced by init(), and reinit().
internalStepSize_
double MarkovOdeSolver::internalStepSize_ private
Definition at line 66 of file MarkovOdeSolver.h.
Referenced by getInternalDt(), MarkovOdeSolver(), and setInternalDt().
isInitialized_
bool MarkovOdeSolver::isInitialized_ private
Definition at line 62 of file MarkovOdeSolver.h.
Referenced by getIsInitialized(), init(), and MarkovOdeSolver().
method_
string MarkovOdeSolver::method_ private
Definition at line 63 of file MarkovOdeSolver.h.
Referenced by getMethod(), MarkovOdeSolver(), and setMethod().
nVars_
unsigned int MarkovOdeSolver::nVars_ private
Definition at line 71 of file MarkovOdeSolver.h.
Referenced by init(), MarkovOdeSolver(), and process().
Q_
vector< vector< double > > MarkovOdeSolver::Q_ private
Definition at line 74 of file MarkovOdeSolver.h.
Referenced by handleQ(), and init().
relAccuracy_
double MarkovOdeSolver::relAccuracy_ private
Definition at line 65 of file MarkovOdeSolver.h.
Referenced by getRelativeAccuracy(), MarkovOdeSolver(), and setRelativeAccuracy().
state_
vector< double > MarkovOdeSolver::state_ private
Definition at line 72 of file MarkovOdeSolver.h.
Referenced by init(), process(), and reinit().
stateOde_
vector<double> MarkovOdeSolver::stateOde_ private
Definition at line 67 of file MarkovOdeSolver.h.
Referenced by init(), and process().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/biophysics/MarkovOdeSolver.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/biophysics/MarkovOdeSolver.cpp