MOOSE - Multiscale Object Oriented Simulation Environment: pymoose::MooseVec Class Reference
pymoose::MooseVec Class Reference
#include <MooseVec.h>
Public Member Functions
vector< MooseVec > children () const
ObjId connectToSingle (const string &srcfield, const ObjId &tgt, const string &tgtfield, const string &msgtype)
ObjId connectToVec (const string &srcfield, const MooseVec &tgt, const string &tgtfield, const string &msgtype)
const string dtype () const
const vector< ObjId > & elements ()
nb::object getAttribute (const string &key)
template<typename T >
nb::ndarray< T, nb::numpy > getAttributeNumpy (const string &name)
ObjId getDataItem (size_t i) const
ObjId getFieldItem (size_t i) const
ObjId getItem (int index) const
vector< ObjId > getItemRange (const nb::slice &slice) const
const ObjId & getItemRef (const int i) const
size_t id () const
size_t len () const
MooseVec (const Id &id)
MooseVec (const ObjId &oid)
MooseVec (const string &path, unsigned int n=1, const string &dtype="")
const string name () const
ObjId oid () const
ObjId parent () const
const string path () const
bool setAttribute (const string &name, const nb::object &val)
template<typename T >
bool setAttrOneToAll (const string &name, const T &val)
template<typename T >
bool setAttrOneToOne (const string &name, const vector< T > &val)
size_t size () const
Private Attributes
vector< ObjId > elements_ {}
ObjId oid_
Detailed Description
Definition at line 21 of file MooseVec.h.
Constructor & Destructor Documentation
MooseVec() [1/3]
pymoose::MooseVec::MooseVec (const string & path, unsigned int n = 1, const string & dtype = "")
Create a MooseVec from path. If path does not exist and dtype is a valid moose class name, then create the object. Otherwise python wrapper should raise an error
Definition at line 24 of file MooseVec.cpp.
{
    // If path is given and it does not exists, then create one. The old api
    // support it.
    oid_ = ObjId(path);
    if(oid_.bad()) {
        if(!dtype.empty()) {
            oid_ = createElementFromPath(dtype, path, n);
        }
        else {
            throw nb::value_error(
                (path +
                    ": path does not exist. Pass `dtype=classname` to create.").c_str());
        }
    }
}
References ObjId::bad(), pymoose::createElementFromPath(), ObjId::ObjId(), and oid_.
MooseVec() [2/3]
pymoose::MooseVec::MooseVec (const Id & id)
Definition at line 45 of file MooseVec.cpp.
                               : oid_(id)
{
}
References ObjId::ObjId(), and oid_.
Referenced by pymoose::copy().
MooseVec() [3/3]
pymoose::MooseVec::MooseVec (const ObjId & oid)
Definition at line 41 of file MooseVec.cpp.
                                   : oid_(oid)
{
}
References ObjId::ObjId(), and oid_.
Referenced by pymoose::ElementField::getAttribute(), and pymoose::ElementField::setAttribute().
Member Function Documentation
children()
vector< MooseVec > pymoose::MooseVec::children () const
Definition at line 77 of file MooseVec.cpp.
{
    vector<Id> childIds;
    Neutral::children(oid_.eref(), childIds);
    vector<MooseVec> res;
    res.reserve(childIds.size());
    for(const auto& id : childIds) {
        res.emplace_back(id);
    }
    return res;
}
References Neutral::children(), ObjId::eref(), and oid_.
connectToSingle()
ObjId pymoose::MooseVec::connectToSingle (const string & srcfield, const ObjId & tgt, const string & tgtfield, const string & msgtype)
Definition at line 222 of file MooseVec.cpp.
{
    return connect(oid_, srcfield, tgt, tgtfield, msgtype);
}
References pymoose::connect(), and oid_.
connectToVec()
ObjId pymoose::MooseVec::connectToVec (const string & srcfield, const MooseVec & tgt, const string & tgtfield, const string & msgtype)
Definition at line 228 of file MooseVec.cpp.
{
    if(size() != tgt.size())
        throw nb::value_error(
            ("Length mismatch. " + to_string(size()) +
                " vs " + to_string(tgt.size())).c_str());
    return connect(oid_, srcfield, tgt.oid_, tgtfield, msgtype);
}
References pymoose::connect(), and oid_.
dtype()
const string pymoose::MooseVec::dtype () const
Definition at line 49 of file MooseVec.cpp.
{
    return oid_.element()->cinfo()->name();
}
References Element::cinfo(), ObjId::element(), Cinfo::name(), and oid_.
elements()
const vector< ObjId > & pymoose::MooseVec::elements ()
Definition at line 243 of file MooseVec.cpp.
{
    if (elements_.empty()) {
        elements_.reserve(size());
        for (size_t ii = 0; ii < size(); ii++) {
            elements_.push_back(getItem(ii));
        }
    }
    return elements_;
}
References size().
getAttribute()
nb::object pymoose::MooseVec::getAttribute (const string & key)
Definition at line 123 of file MooseVec.cpp.
{
    // Special id level attributes
    if(name == "numData") {
        return nb::cast(Field<unsigned int>::get(oid_, "numData"));
    }
    if(name == "numField") {
        return nb::cast(Field<unsigned int>::get(oid_, "numField"));
    }
    // If type is double, int, bool etc, then return the numpy array. else
    // return the list of python object.
    auto cinfo = oid_.element()->cinfo();
    auto finfo = cinfo->findFinfo(name);
    if (!finfo) {
        throw nb::attribute_error((name + " not found on " + path()).c_str());
    }
    auto rttType = finfo->rttiType();
    if(rttType == "double")
        return nb::cast(getAttributeNumpy<double>(name));
    if(rttType == "unsigned int")
        return nb::cast(getAttributeNumpy<unsigned int>(name));
    if(rttType == "int")
        return nb::cast(getAttributeNumpy<int>(name));
    if(rttType == "bool")
        return nb::cast(getAttributeNumpy<bool>(name));
    string finfoType = cinfo->getFinfoType(finfo);
    if(finfoType == "LookupValueFinfo") {
        return nb::cast(VecLookupField(oid_, finfo));
    }
    if(finfoType == "FieldElementFinfo") {
        return nb::cast(VecElementField(oid_, finfo));
    }
    cerr << "DEBUG: None of the simply handled types:  " << finfoType << endl;
    // For complex types, return list objects
    nb::list result;
    for(size_t ii = 0; ii < size(); ii++){
        result.append(getFieldGeneric(getItem(ii), name));
    }
    return result;
}
References Element::cinfo(), ObjId::element(), Cinfo::findFinfo(), Cinfo::getFinfoType(), oid_, Finfo::rttiType(), and size().
getAttributeNumpy()
template<typename T > nb::ndarray< T, nb::numpy > pymoose::MooseVec::getAttributeNumpy (const string & name) inline
Definition at line 57 of file MooseVec.h.
    {
        size_t nn = size();
        T* data = new T[nn];
        for(size_t ii = 0; ii < nn; ++ii) {
            data[ii] = Field<T>::get(getItem(ii), name);
        }
        nb::capsule owner(data, [](void* p) noexcept {
            delete[] static_cast<T*>(p);
        });
        return nb::ndarray<T, nb::numpy>(data, {nn}, owner);
    }
References getItem(), and size().
getDataItem()
ObjId pymoose::MooseVec::getDataItem (size_t i) const
Definition at line 113 of file MooseVec.cpp.
{
    return ObjId(oid_.id, dataIndex, oid_.fieldIndex);
}
References ObjId::fieldIndex, ObjId::id, ObjId::ObjId(), and oid_.
Referenced by getItem().
getFieldItem()
ObjId pymoose::MooseVec::getFieldItem (size_t i) const
Definition at line 118 of file MooseVec.cpp.
{
    return ObjId(oid_.id, oid_.dataIndex, fieldIndex);
}
References ObjId::dataIndex, ObjId::id, ObjId::ObjId(), and oid_.
Referenced by getItem().
getItem()
ObjId pymoose::MooseVec::getItem (int index) const
Get vector element. Vector element could be dataIndex or fieldIndex. Allows negative indexing.
Definition at line 89 of file MooseVec.cpp.
{
    // Handle negative indexing.
    size_t i = (index < 0) ? size() + index : static_cast<size_t>(index);
    if(i >= size()) {
        throw nb::index_error(("Index " + to_string(i) + " out of range").c_str());
    }
    if(oid_.element()->hasFields()) {
        return getFieldItem(i);
    }
    return getDataItem(i);
}
References ObjId::element(), getDataItem(), getFieldItem(), Element::hasFields(), oid_, and size().
Referenced by getAttributeNumpy(), setAttrOneToAll(), and setAttrOneToOne().
getItemRange()
vector< ObjId > pymoose::MooseVec::getItemRange (const nb::slice & slice) const
Definition at line 102 of file MooseVec.cpp.
{
    auto [start, stop, step, length] = slice.compute(size());
    vector<ObjId> res;
    res.reserve(length);
    for(size_t ii = start; ii < stop; ii += step) {
        res.push_back(getItem(static_cast<int>(ii)));
    }
    return res;
}
References size().
getItemRef()
const ObjId & pymoose::MooseVec::getItemRef (const int i) const
id()
size_t pymoose::MooseVec::id () const
Definition at line 254 of file MooseVec.cpp.
{
    return oid_.id.value();
}
References ObjId::id, oid_, and Id::value().
len()
size_t pymoose::MooseVec::len () const
name()
const string pymoose::MooseVec::name () const
Definition at line 62 of file MooseVec.cpp.
{
    return oid_.element()->getName();
}
References ObjId::element(), Element::getName(), and oid_.
oid()
ObjId pymoose::MooseVec::oid () const
Definition at line 238 of file MooseVec.cpp.
{
    return oid_;
}
References oid_.
Referenced by pymoose::connectToVec().
parent()
ObjId pymoose::MooseVec::parent () const
Definition at line 72 of file MooseVec.cpp.
{
    return Neutral::parent(oid_);
}
References oid_, and Neutral::parent().
path()
const string pymoose::MooseVec::path () const
Definition at line 67 of file MooseVec.cpp.
{
    return oid_.path();
}
References oid_, and ObjId::path().
setAttribute()
bool pymoose::MooseVec::setAttribute (const string & name, const nb::object & val)
@Synopsis API function. Set attribute on vector. This is the top-level generic function.
@Param name @Param val
@Returns
Definition at line 178 of file MooseVec.cpp.
{
    auto cinfo = oid_.element()->cinfo();
    auto finfo = cinfo->findFinfo(name);
    if (!finfo) {
        throw nb::attribute_error((name + " not found on " + path()).c_str());
    }
    auto rttType = finfo->rttiType();
    bool isIterable = nb::isinstance<nb::iterable>(val) && !nb::isinstance<nb::str>(val);
    if(isIterable) {
        if(rttType == "double")
            return setAttrOneToOne<double>(name, nb::cast<vector<double>>(val));
        if(rttType == "unsigned int")
            return setAttrOneToOne<unsigned int>(
                name, nb::cast<vector<unsigned int>>(val));
        if(rttType == "int")
            return setAttrOneToOne<int>(
                name, nb::cast<vector<int>>(val));
        if(rttType == "bool")
            return setAttrOneToOne<bool>(name, nb::cast<vector<bool>>(val));
        if(rttType == "string")
            return setAttrOneToOne<string>(name, nb::cast<vector<string>>(val));
    }
    else {
        if(rttType == "double")
            return setAttrOneToAll<double>(name, nb::cast<double>(val));
        if(rttType == "unsigned int")
            return setAttrOneToAll<unsigned int>(name,
                nb::cast<unsigned int>(val));
        if(rttType == "int")
            return setAttrOneToAll< int>(name,
                nb::cast<int>(val));
        if(rttType == "bool")
            return setAttrOneToAll<bool>(name, nb::cast<bool>(val));
          if (rttType == "string")
              return setAttrOneToAll<string>(name, nb::cast<string>(val));
    }
    throw nb::type_error(("Unsupported type: " + rttType).c_str());
}
References Element::cinfo(), ObjId::element(), Cinfo::findFinfo(), oid_, and Finfo::rttiType().
setAttrOneToAll()
template<typename T > bool pymoose::MooseVec::setAttrOneToAll (const string & name, const T & val) inline
Definition at line 71 of file MooseVec.h.
    {
        auto cinfo = oid_.element()->cinfo();
        auto finfo = cinfo->findFinfo(name);
        if(!finfo) {
            throw nb::attribute_error((name + " not found").c_str());
        }
        bool res = true;
        for (size_t i = 0; i < size(); i++)
        {
                res &= Field<T>::set(getItem(i), name, val);
        }
        return res;
    }
References Element::cinfo(), ObjId::element(), Cinfo::findFinfo(), getItem(), oid_, and size().
setAttrOneToOne()
template<typename T > bool pymoose::MooseVec::setAttrOneToOne (const string & name, const vector< T > & val) inline
Definition at line 87 of file MooseVec.h.
    {
        auto cinfo = oid_.element()->cinfo();
        auto finfo = cinfo->findFinfo(name);
        if(!finfo) {
            throw nb::attribute_error((name + " not found").c_str());
        }
        if (val.size() != size()) {
            throw nb::value_error(("Length mismatch: expected " +
                to_string(size()) + ", got " +
                    to_string(val.size())).c_str());
        }
          bool res = true;
          for (size_t i = 0; i < size(); i++) {
              res &= Field<T>::set(getItem(i), name, val[i]);
          }
          return res;
    }
References Element::cinfo(), ObjId::element(), Cinfo::findFinfo(), getItem(), oid_, and size().
size()
size_t pymoose::MooseVec::size () const
Definition at line 54 of file MooseVec.cpp.
{
    if(oid_.element()->hasFields()){
        return Field<unsigned int>::get(oid_, "numField");
    }
    return oid_.element()->numData();
}
References ObjId::element(), Element::hasFields(), Element::numData(), and oid_.
Referenced by elements(), getAttribute(), getAttributeNumpy(), getItem(), getItemRange(), setAttrOneToAll(), and setAttrOneToOne().
Member Data Documentation
elements_
vector<ObjId> pymoose::MooseVec::elements_ {} private
Definition at line 146 of file MooseVec.h.
{};
oid_
ObjId pymoose::MooseVec::oid_ private
Definition at line 145 of file MooseVec.h.
Referenced by children(), connectToSingle(), connectToVec(), dtype(), getAttribute(), getDataItem(), getFieldItem(), getItem(), id(), MooseVec(), MooseVec(), MooseVec(), name(), oid(), parent(), path(), setAttribute(), setAttrOneToAll(), setAttrOneToOne(), and size().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/pymoose/MooseVec.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/pymoose/MooseVec.cpp