MOOSE - Multiscale Object Oriented Simulation Environment: Table Class Reference
Table Class Reference
#include <Table.h>
Public Member Functions
void clearAllVecs ()
void collectData (vector< double > &data, bool withTime=true, bool clear=false)
string getColumnName () const
string getDatafile (void) const
double getDt (void) const
string getFormat () const
double getThreshold () const
bool getUseSpikeMode (void) const
bool getUseStreamer (void) const
void input (double v)
void mergeWithTime (vector< double > &data)
Take the vector from table and timestamp it. It must only be called when packing the data for writing.
Table & operator= (const Table &tab)
void process (const Eref &e, ProcPtr p)
void reinit (const Eref &e, ProcPtr p)
Reinitialize.
void setColumnName (const string colname)
void setDatafile (string filepath)
void setFormat (const string format)
void setThreshold (double v)
void setUseSpikeMode (bool status)
void setUseStreamer (bool status)
void spike (double v)
Table ()
string toJSON (bool withTime=true, bool clear=false)
~Table ()
Public Member Functions inherited from TableBase
void clearVec ()
void compareVec (vector< double > other, string op)
void compareXplot (string fname, string plotname, string op)
const vector< double > & data ()
double getOutputValue () const
string getPlotDump () const
unsigned int getVecSize () const
vector< double > getVector () const
double getY (unsigned int index) const
double interpolate (double x, double xmin, double xmax) const
void linearTransform (double scale, double offset)
void loadCSV (string fname, int startLine, int colNum, char separator)
void loadXplot (string fname, string plotname)
void loadXplotRange (string fname, string plotname, unsigned int start, unsigned int end)
double * lookupVec (unsigned int index)
void plainPlot (string file)
void setOutputValue (double val)
void setPlotDump (string v)
void setVecSize (unsigned int num)
void setVector (vector< double > val)
TableBase ()
void xplot (string file, string plotname)
Static Public Member Functions
static const Cinfo * initCinfo ()
Static Public Member Functions inherited from TableBase
static const Cinfo * initCinfo ()
Private Attributes
vector< string > columns_
vector< double > data_
string datafile_
double dt_
dt of its clock. Needed for creating time co-ordinates,
bool fired_
string format_
format of data. Default to csv.
double input_
unsigned int lastN_ = 0
double lastTime_
string tableColumnName_
Column name of this table. Use it when writing data to a datafile.
string tablePath_
double threshold_
vector< double > tvec_
bool useFileStreamer_
If stream is set to true, then stream to datafile_. Default value of datafile_ is table path starting from pwd/_tables_ . On table, set streamToFile to true.
bool useSpikeMode_
Additional Inherited Members
Protected Member Functions inherited from TableBase
vector< double > & vec ()
Detailed Description
Receives and records inputs. Handles plot and spiking data in batch mode.
Definition at line 18 of file Table.h.
Constructor & Destructor Documentation
Table()
Table::Table ()
Definition at line 219 of file Table.cpp.
             :
    threshold_( 0.0 ),
    lastTime_( 0.0 ),
    input_( 0.0 ),
    fired_(false),
    useSpikeMode_(false),
    dt_( 0.0 ),
    lastN_(0),
    useFileStreamer_(false),
    datafile_(""),
    format_("csv")
{
}
References datafile_, dt_, fired_, format_, input_, lastN_, lastTime_, threshold_, useFileStreamer_, and useSpikeMode_.
~Table()
Table::~Table ()
Definition at line 233 of file Table.cpp.
{
    // Make sure to write to rest of the entries to file before closing down.
    if( useFileStreamer_ )
    {
        mergeWithTime( data_ );
        assert( ! datafile_.empty() );
        StreamerBase::writeToOutFile( datafile_, format_, APPEND, data_, columns_);
        clearAllVecs();
    }
}
References APPEND, clearAllVecs(), columns_, data_, datafile_, format_, mergeWithTime(), useFileStreamer_, and StreamerBase::writeToOutFile().
Member Function Documentation
clearAllVecs()
void Table::clearAllVecs ()
Definition at line 287 of file Table.cpp.
{
    clearVec();
    tvec_.clear();
    data_.clear();
}
References TableBase::clearVec(), data_, and tvec_.
Referenced by collectData(), process(), reinit(), toJSON(), and ~Table().
collectData()
void Table::collectData (vector< double > & data, bool withTime = true, bool clear = false)
@Synopsis Collect data in given vector. Its similar to toJSON function.
@Param data @Param withTime @Param clear
Definition at line 524 of file Table.cpp.
{
    auto v = vec();
    if( clear )
        lastN_ = 0;
    for (unsigned int i = lastN_; i < v.size(); i++)
    {
        if(withTime)
            data.push_back(tvec_[i]);
        data.push_back(v[i]);
    }
    if( clear )
        clearAllVecs();
    else
        lastN_ = v.size();
}
References clearAllVecs(), lastN_, tvec_, and TableBase::vec().
Referenced by SocketStreamer::dataToStream().
getColumnName()
string Table::getColumnName (void) const
Definition at line 409 of file Table.cpp.
{
    return tableColumnName_;
}
References tableColumnName_.
Referenced by SocketStreamer::addTable(), Streamer::addTable(), and initCinfo().
getDatafile()
string Table::getDatafile (void) const
Definition at line 456 of file Table.cpp.
{
    return datafile_;
}
References datafile_.
Referenced by initCinfo().
getDt()
double Table::getDt (void) const
Definition at line 462 of file Table.cpp.
{
    return dt_;
}
References dt_.
getFormat()
string Table::getFormat (void) const
Definition at line 403 of file Table.cpp.
{
    return format_;
}
References format_.
Referenced by initCinfo().
getThreshold()
double Table::getThreshold () const
Definition at line 385 of file Table.cpp.
{
    return threshold_;
}
References threshold_.
Referenced by initCinfo().
getUseSpikeMode()
bool Table::getUseSpikeMode (void) const
Definition at line 436 of file Table.cpp.
{
    return useSpikeMode_;
}
References useSpikeMode_.
Referenced by initCinfo().
getUseStreamer()
bool Table::getUseStreamer (void) const
Definition at line 425 of file Table.cpp.
{
    return useFileStreamer_;
}
References useFileStreamer_.
Referenced by initCinfo().
initCinfo()
const Cinfo * Table::initCinfo () static
Definition at line 39 of file Table.cpp.
{
    // Field Definitions
    static ValueFinfo< Table, double > threshold(
        "threshold"
        , "threshold used when Table acts as a buffer for spikes"
        , &Table::setThreshold
        , &Table::getThreshold
    );
    static ValueFinfo< Table, bool > useStreamer(
        "useStreamer"
        , "When set to true, write to a file instead writing in memory."
        " If `outfile` is not set, streamer writes to default path."
        , &Table::setUseStreamer
        , &Table::getUseStreamer
    );
    static ValueFinfo< Table, bool > useSpikeMode(
        "useSpikeMode"
        , "When set to true, look for spikes in a time-series."
        " Normally used for monitoring Vm for action potentials."
        " Could be used for any thresholded event. Default is False."
        , &Table::setUseSpikeMode
        , &Table::getUseSpikeMode
    );
    static ValueFinfo< Table, string > datafile(
        "datafile"
        , "Set the name of file to which data is written to. If set, "
        " streaming support is automatically enabled."
        , &Table::setDatafile
        , &Table::getDatafile
    );
    static ValueFinfo< Table, string > outfile(
        "outfile"
        , "Use datafile (deprecated)"
        , &Table::setDatafile
        , &Table::getDatafile
    );
    static ValueFinfo< Table, string > format(
        "format"
        , "Data format for table: default csv"
        , &Table::setFormat
        , &Table::getFormat
    );
    // relevant for Streamer class.  When data is written to a datafile, this is
    // used to create column name.
    static ValueFinfo< Table, string > columnName(
        "columnName"
        , "Name of the table written in header of data file."
        , &Table::setColumnName
        , &Table::getColumnName
    );
    // MsgDest Definitions
    static DestFinfo spike(
        "spike",
        "Fills spike timings into the Table. Signal has to exceed thresh",
        new OpFunc1< Table, double >( &Table::spike )
    );
    static DestFinfo process(
        "process",
        "Handles process call, updates internal time stamp.",
        new ProcOpFunc< Table >( &Table::process )
    );
    static DestFinfo reinit(
        "reinit",
        "Handles reinit call.",
        new ProcOpFunc< Table >( &Table::reinit )
    );
    // SharedMsg Definitions
    static Finfo* procShared[] =
    {
        &process, &reinit
    };
    static SharedFinfo proc(
        "proc"
        , "Shared message for process and reinit"
        , procShared, sizeof( procShared ) / sizeof( const Finfo* )
    );
    // Field Element for the vector data
    // Use a limit of 2^20 entries for the tables, about 1 million.
    static Finfo* tableFinfos[] =
    {
        &threshold,     // Value
        &format,                // Value
        &columnName,            // Value
        &datafile,              // Value
        &outfile,               // Value
        &useStreamer,           // Value
        &useSpikeMode,          // Value
        handleInput(),      // DestFinfo
        &spike,         // DestFinfo
        requestOut(),       // SrcFinfo
        &proc,          // SharedFinfo
    };
    static string doc[] =
    {
        "Name", "Table",
        "Author", "Upi Bhalla",
        "Description",
        "Table for accumulating data values, or spike timings. "
        "Can either receive incoming doubles, or can explicitly "
        "request values from fields provided they are doubles. "
        "The latter mode of use is preferable if you wish to have "
        "independent control of how often you sample from the output "
        "variable. \n"
        "Typically used for storing simulation output into memory, or to file"
        " when stream is set to True \n"
        "There are two functionally identical variants of the Table "
        "class: Table and Table2. Their only difference is that the "
        "default scheduling of the Table (Clock Tick 8, dt = 0.1 ms ) "
        "makes it suitable for "
        "tracking electrical compartmental models of neurons and "
        "networks. \n"
        "Table2 (Clock Tick 18, dt = 1.0 s) is good for tracking "
        "biochemical signaling pathway outputs. \n"
        "These are just the default values and Tables can be assigned"
        " to any Clock Tick and timestep in the usual manner.",
    };
    static Dinfo< Table > dinfo;
    static Cinfo tableCinfo (
        "Table",
        TableBase::initCinfo(),
        tableFinfos,
        sizeof( tableFinfos ) / sizeof ( Finfo* ),
        &dinfo,
        doc,
        sizeof( doc ) / sizeof( string )
    );
    static string doc2[] =
    {
        doc[0], "Table2", doc[2], doc[3], doc[4], doc[5]
    };
    doc2[1] = "Table2";
    static Cinfo table2Cinfo (
        "Table2",
        TableBase::initCinfo(),
        tableFinfos,
        sizeof( tableFinfos ) / sizeof ( Finfo* ),
        &dinfo,
        doc2,
        sizeof( doc2 ) / sizeof( string )
    );
    return &tableCinfo;
}
References Cinfo::Cinfo(), DestFinfo::DestFinfo(), getColumnName(), getDatafile(), getFormat(), getThreshold(), getUseSpikeMode(), getUseStreamer(), handleInput(), TableBase::initCinfo(), OpFunc1< T, A >::OpFunc1(), process(), ProcOpFunc< T >::ProcOpFunc(), reinit(), requestOut(), setColumnName(), setDatafile(), setFormat(), setThreshold(), setUseSpikeMode(), setUseStreamer(), SharedFinfo::SharedFinfo(), spike(), and ValueFinfo< T, F >::ValueFinfo().
input()
void Table::input (double v)
Definition at line 355 of file Table.cpp.
{
    vec().push_back( v );
}
References TableBase::vec().
Referenced by handleInput(), and testTable().
mergeWithTime()
void Table::mergeWithTime (vector< double > & data)
Take the vector from table and timestamp it. It must only be called when packing the data for writing.
Definition at line 471 of file Table.cpp.
{
    auto v = vec();
    for (unsigned int i = 0; i < v.size(); i++)
    {
        data.push_back(tvec_[i]);
        data.push_back(v[i]);
    }
}
References tvec_, and TableBase::vec().
Referenced by process(), reinit(), and ~Table().
operator=()
Table & Table::operator= (const Table & tab)
Definition at line 245 of file Table.cpp.
{
    return *this;
}
process()
void Table::process (const Eref & e, ProcPtr p)
Definition at line 255 of file Table.cpp.
{
    lastTime_ = p->currTime;
    tvec_.push_back(lastTime_);
    // Copy incoming data to ret and insert into vector.
    vector< double > ret;
    requestOut()->send( e, &ret );
    if (useSpikeMode_)
    {
        for ( auto i = ret.begin(); i != ret.end(); ++i )
            spike( *i );
    }
    else
        vec().insert( vec().end(), ret.begin(), ret.end() );
    /*  If we are streaming to a file, let's write to a file. And clean the
     *  vector.
     *  Write at every 5 seconds or whenever size of vector is more than 10k.
     */
    if( useFileStreamer_ )
    {
        if( fmod(lastTime_, 5.0) == 0.0 || getVecSize() >= 10000 )
        {
            mergeWithTime( data_ );
            StreamerBase::writeToOutFile( datafile_, format_, APPEND, data_, columns_ );
            clearAllVecs();
        }
        }
    }
References APPEND, clearAllVecs(), columns_, ProcInfo::currTime, data_, datafile_, format_, TableBase::getVecSize(), lastTime_, mergeWithTime(), requestOut(), SrcFinfo1< T >::send(), spike(), tvec_, useFileStreamer_, useSpikeMode_, TableBase::vec(), and StreamerBase::writeToOutFile().
Referenced by initCinfo().
reinit()
void Table::reinit (const Eref & e, ProcPtr p)
Reinitialize.
Parameters
e
p
Create the default filepath for this table.
Definition at line 300 of file Table.cpp.
{
    tablePath_ = e.id().path();
    unsigned int numTick = e.element()->getTick();
    Clock* clk = reinterpret_cast<Clock*>(Id(1).eref().data());
    dt_ = clk->getTickDt( numTick );
    fired_ = false;
    // Set column name for this table. It is used in Streamer to generate
    // column names because path can be pretty verbose and name may not be
    // unique. This is the default column name.
    if( tableColumnName_.empty() )
        tableColumnName_ = moose::moosePathToColumnName(tablePath_);
    columns_ = {"time", tableColumnName_};
    if( useFileStreamer_ )
    {
        // If user has not set the filepath, then use the table path prefixed
        // with rootdit as path.
        if( datafile_.empty() )
            setDatafile(moose::moosePathToUserPath(tablePath_) + '.' + format_);
    }
    input_ = 0.0;
    vec().resize( 0 );
    lastTime_ = 0;
    vector< double > ret;
    requestOut()->send( e, &ret );
    if (useSpikeMode_)
    {
        for ( auto i = ret.begin(); i != ret.end(); ++i )
            spike( *i );
    }
    else
        vec().insert( vec().end(), ret.begin(), ret.end() );
    tvec_.push_back(lastTime_);
    if( useFileStreamer_ )
    {
        mergeWithTime( data_ );
        StreamerBase::writeToOutFile(datafile_, format_, WRITE, data_, columns_);
        clearAllVecs();
    }
}
References clearAllVecs(), columns_, Eref::data(), data_, datafile_, dt_, Eref::element(), Id::eref(), fired_, format_, Element::getTick(), Clock::getTickDt(), Eref::id(), Id::Id(), input_, lastTime_, mergeWithTime(), moose::moosePathToColumnName(), moose::moosePathToUserPath(), Id::path(), requestOut(), SrcFinfo1< T >::send(), setDatafile(), spike(), tableColumnName_, tablePath_, tvec_, useFileStreamer_, useSpikeMode_, TableBase::vec(), WRITE, and StreamerBase::writeToOutFile().
Referenced by initCinfo().
setColumnName()
void Table::setColumnName (const string colname)
Definition at line 414 of file Table.cpp.
{
    tableColumnName_ = colname ;
}
References tableColumnName_.
Referenced by initCinfo().
setDatafile()
void Table::setDatafile (string filepath)
Definition at line 443 of file Table.cpp.
{
    datafile_ = moose::createMOOSEPath( filepath );
    if( ! moose::createParentDirs( datafile_ ) )
        datafile_ = moose::toFilename( datafile_ );
    setUseStreamer( true );
    // If possible get the format of file as well.
    format_ = moose::getExtension( datafile_, true );
    if( format_.size() == 0 )
        format_ = "csv";
}
References moose::createMOOSEPath(), moose::createParentDirs(), datafile_, format_, moose::getExtension(), setUseStreamer(), and moose::toFilename().
Referenced by initCinfo(), and reinit().
setFormat()
void Table::setFormat (const string format)
Definition at line 391 of file Table.cpp.
{
    if( format == "csv" )
        format_ = format;
    else
        LOG( moose::warning
             , "Unsupported format " << format
             << " only csv is supported for single table."
           );
}
References format_, and moose::warning.
Referenced by initCinfo().
setThreshold()
void Table::setThreshold (double v)
Definition at line 380 of file Table.cpp.
{
    threshold_ = v;
}
References threshold_.
Referenced by initCinfo().
setUseSpikeMode()
void Table::setUseSpikeMode (bool status)
Definition at line 431 of file Table.cpp.
{
    useSpikeMode_ = useSpikeMode;
}
References useSpikeMode_.
Referenced by initCinfo().
setUseStreamer()
void Table::setUseStreamer (bool status)
Definition at line 420 of file Table.cpp.
{
    useFileStreamer_ = useStreamer;
}
References useFileStreamer_.
Referenced by initCinfo(), and setDatafile().
spike()
void Table::spike (double v)
Definition at line 360 of file Table.cpp.
{
    if ( fired_ )
    { // Wait for it to go below threshold
        if ( v < threshold_ )
            fired_ = false;
    }
    else
    {
        if ( v > threshold_ )
        {
            // wait for it to go above threshold.
            fired_ = true;
            vec().push_back( lastTime_ );
        }
    }
}
References fired_, lastTime_, threshold_, and TableBase::vec().
Referenced by initCinfo(), process(), and reinit().
toJSON()
string Table::toJSON (bool withTime = true, bool clear = false)
@Synopsis. Convert table data to JOSN.
@Returns string.
Definition at line 488 of file Table.cpp.
{
    stringstream ss;
    auto v = vec();
    if( clear )
        lastN_ = 0;
    for (unsigned int i = lastN_; i < v.size(); i++)
    {
        if(withTime)
            ss << '[' << tvec_[i] << ',' << v[i] << "],";
        else
            ss << v[i] << ',';
    }
    string res = ss.str();
    if(',' == res.back())
        res.pop_back();
    if( clear )
        clearAllVecs();
    else
        lastN_ += v.size();
    return res;
}
References clearAllVecs(), lastN_, tvec_, and TableBase::vec().
Member Data Documentation
columns_
vector<string> Table::columns_ private
Definition at line 89 of file Table.h.
Referenced by process(), reinit(), and ~Table().
data_
vector<double> Table::data_ private
Definition at line 85 of file Table.h.
Referenced by clearAllVecs(), process(), reinit(), and ~Table().
datafile_
string Table::datafile_ private
Definition at line 116 of file Table.h.
Referenced by getDatafile(), process(), reinit(), setDatafile(), Table(), and ~Table().
dt_
double Table::dt_ private
dt of its clock. Needed for creating time co-ordinates,
Definition at line 94 of file Table.h.
Referenced by getDt(), reinit(), and Table().
fired_
bool Table::fired_ private
Definition at line 82 of file Table.h.
Referenced by reinit(), spike(), and Table().
format_
string Table::format_ private
format of data. Default to csv.
Definition at line 121 of file Table.h.
Referenced by getFormat(), process(), reinit(), setDatafile(), setFormat(), Table(), and ~Table().
input_
double Table::input_ private
Definition at line 81 of file Table.h.
Referenced by reinit(), and Table().
lastN_
unsigned int Table::lastN_ = 0 private
Definition at line 98 of file Table.h.
Referenced by collectData(), Table(), and toJSON().
lastTime_
double Table::lastTime_ private
Definition at line 80 of file Table.h.
Referenced by process(), reinit(), spike(), and Table().
tableColumnName_
string Table::tableColumnName_ private
Column name of this table. Use it when writing data to a datafile.
Definition at line 105 of file Table.h.
Referenced by getColumnName(), reinit(), and setColumnName().
tablePath_
string Table::tablePath_ private
Definition at line 100 of file Table.h.
Referenced by reinit().
threshold_
double Table::threshold_ private
Definition at line 79 of file Table.h.
Referenced by getThreshold(), setThreshold(), spike(), and Table().
tvec_
vector<double> Table::tvec_ private
Definition at line 86 of file Table.h.
Referenced by clearAllVecs(), collectData(), mergeWithTime(), process(), reinit(), and toJSON().
useFileStreamer_
bool Table::useFileStreamer_ private
If stream is set to true, then stream to datafile_. Default value of datafile_ is table path starting from pwd/_tables_ . On table, set streamToFile to true.
Definition at line 112 of file Table.h.
Referenced by getUseStreamer(), process(), reinit(), setUseStreamer(), Table(), and ~Table().
useSpikeMode_
bool Table::useSpikeMode_ private
Definition at line 83 of file Table.h.
Referenced by getUseSpikeMode(), process(), reinit(), setUseSpikeMode(), and Table().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/builtins/Table.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/builtins/Table.cpp