MOOSE - Multiscale Object Oriented Simulation Environment: HHGate Class Reference
HHGate Class Reference
#include <HHGate.h>
Public Member Functions
vector< double > computeTable (string expr, double xmin, double xmax, unsigned int xdivs)
void fillFromExpr (const Eref &e)
Fill the tables by evaluating expressions.
vector< double > getAlpha (const Eref &e) const
string getAlphaExpr (const Eref &e) const
vector< double > getAlphaParms (const Eref &e) const
vector< double > getBeta (const Eref &e) const
string getBetaExpr (const Eref &e) const
unsigned int getDivs (const Eref &e) const
int getForm () const
string getInfExpr (const Eref &e) const
double getMax (const Eref &e) const
double getMin (const Eref &e) const
vector< double > getMinfinity (const Eref &e) const
vector< double > getTableA (const Eref &e) const
vector< double > getTableB (const Eref &e) const
vector< double > getTau (const Eref &e) const
string getTauExpr (const Eref &e) const
bool getUseInterpolation (const Eref &e) const
HHGate ()
HHGate (Id originalChanId, Id originalGateId)
double lookupA (double v) const
double lookupB (double v) const
void lookupBoth (double v, double *A, double *B) const
double lookupTable (const vector< double > &tab, double v) const
void setAlpha (const Eref &e, vector< double > val)
void setAlphaExpr (const Eref &e, string expr)
Set/get expression for alpha.
void setBeta (const Eref &e, vector< double > val)
void setBetaExpr (const Eref &e, string expr)
Set/get expression for beta.
void setDivs (const Eref &e, unsigned int val)
void setInfExpr (const Eref &e, string expr)
Set/get expression for inf.
void setMax (const Eref &e, double val)
void setMin (const Eref &e, double val)
void setMinfinity (const Eref &e, vector< double > val)
void setTableA (const Eref &e, vector< double > v)
void setTableB (const Eref &e, vector< double > v)
void setTau (const Eref &e, vector< double > val)
void setTauExpr (const Eref &e, string expr)
Set/get expression for tau.
void setupAlpha (const Eref &e, vector< double > parms)
void setupGate (const Eref &e, vector< double > parms)
void setupTables (const vector< double > &parms, bool doTau)
void setupTau (const Eref &e, vector< double > parms)
void setUseInterpolation (const Eref &e, bool val)
void tabFill (vector< double > &table, unsigned int newXdivs, double newXmin, double newXmax)
void tweakAlpha ()
void tweakTables (bool doTau)
void tweakTau ()
void updateAlphaBeta ()
void updateTables ()
void updateTauMinf ()
Public Member Functions inherited from HHGateBase
bool checkOriginal (Id id, const string &field) const
HHGateBase ()
HHGateBase (Id originalChanId, Id originalGateId)
bool isOriginalChannel (Id id) const
bool isOriginalGate (Id id) const
Id originalChannelId () const
Id originalGateId () const
Static Public Member Functions
static const Cinfo * initCinfo ()
Static Public Member Functions inherited from HHGateBase
static const Cinfo * initCinfo ()
Private Attributes
vector< double > A_
The actual lookup table for calculations. Holds alpha(V).
vector< double > alpha_
5 parameters for alpha
string alphaExpr_
Strings for expressions.
vector< double > B_
The lookup table for calculations. Holds alpha(V) + beta(V).
vector< double > beta_
5 parameters for beta
string betaExpr_
int form_
double invDx_
increment of the range.
bool isDirectTable_
bool lookupByInterpolation_
vector< double > mInfinity_
5 parameters for mInfinity
Id originalChanId_
Id originalGateId_
vector< double > tau_
5 parameters for tau
double xmax_
Max of the voltage (or conc) range.
double xmin_
Minimum of the voltage (or conc) range.
Friends
void testHHGateLookup ()
void testHHGateSetup ()
Additional Inherited Members
Protected Attributes inherited from HHGateBase
Id originalChanId_
Id originalGateId_
Detailed Description
This class handles a single gate on an HHChannel. It is equivalent to the m and h terms on the Hodgkin-Huxley Na channel, or the n term on the K channel. It stores the voltage-dependence (sometimes concentration-dependence) of the gating variables for opening the channel. It does so in a tabular form which can be directly filled using experimental data points. It also provides a set of utility functions for defining the gate in functional forms, and accessing those original functional forms. The HHGate is accessed as a FieldElement, which means that it is available as a pointer on the HHChannel. HHGates are typically shared. This means that when you make a copy or a vector of an HHChannel, there is only a single HHGate created, and its pointer is used by all the copies. The lookup functions are thread-safe. Field assignment to the HHGate should be possible only from the original HHChannel, but all the others do have read permission.
Definition at line 35 of file HHGate.h.
Constructor & Destructor Documentation
HHGate() [1/2]
HHGate::HHGate ()
Dummy constructor, to keep Dinfo happy. Should never be used
Definition at line 283 of file HHGate.cpp.
    : HHGateBase(0, 0),
      xmin_(0),
      xmax_(1),
      invDx_(1),
      form_(0),
      alphaExpr_(""),
      betaExpr_(""),
      lookupByInterpolation_(0),
      isDirectTable_(0)
{
    cerr << "# HHGate::HHGate() should never be called" << endl;
}
References alphaExpr_, betaExpr_, form_, HHGateBase::HHGateBase(), invDx_, isDirectTable_, lookupByInterpolation_, xmax_, and xmin_.
HHGate() [2/2]
HHGate::HHGate (Id originalChanId, Id originalGateId)
This constructor is the one meant to be used. It takes the originalId of the parent HHChannel as a required argument, so that any subsequent 'write' functions can be checked to see if they are legal. Also tracks its own Id.
Definition at line 297 of file HHGate.cpp.
    : HHGateBase(originalChanId, originalGateId),
      A_(1, 0.0),
      B_(1, 0.0),
      xmin_(0),
      xmax_(1),
      invDx_(1),
      form_(0),
      alphaExpr_(""),
      betaExpr_(""),
      lookupByInterpolation_(0),
      isDirectTable_(0)
{
    ;
}
References alphaExpr_, betaExpr_, form_, HHGate(), HHGateBase::HHGateBase(), invDx_, isDirectTable_, lookupByInterpolation_, xmax_, and xmin_.
Referenced by HHGate(), and HHChannel::innerCreateGate().
Member Function Documentation
computeTable()
vector< double > HHGate::computeTable (string expr, double xmin, double xmax, unsigned int xdivs)
fillFromExpr()
void HHGate::fillFromExpr (const Eref & e)
Fill the tables by evaluating expressions.
Definition at line 450 of file HHGate.cpp.
{
    if(form_ == 0) {
        return;
    }
    exprtk::symbol_table<double> symTab_;
    exprtk::expression<double> alpha_;
    exprtk::expression<double> beta_;
    exprtk::parser<double> parser_;
    double v_;
    // Add extra variables to allow intermediate expressions for cases
    // where there is conditional on alpha/beta or tau/inf values
    double a_;
    double b_;
    double tau_;
    double inf_;
    symTab_.add_variable("v", v_);
    symTab_.add_variable("c", v_);
    symTab_.add_variable("alpha", a_);
    symTab_.add_variable("beta", b_);
    symTab_.add_variable("tau", tau_);
    symTab_.add_variable("inf", inf_);
    symTab_.add_constants();
    alpha_.register_symbol_table(symTab_);
    beta_.register_symbol_table(symTab_);
    if(moose::trim(alphaExpr_).length() == 0) {
        cerr << "Error: Element: " << e.objId().path()
             << ": HHGate::tabFillExpr: empty expression for A" << endl;
        return;
    }
    if(!parser_.compile(alphaExpr_, alpha_)) {
        cerr << "Error: Element: " << e.objId().path()
             << ": HHGate::tabFillExpr: cannot compile expression!\n"
             << alphaExpr_ << endl
             << parser_.error() << endl;
        return;
    }
    if(moose::trim(alphaExpr_).length() == 0) {
        cerr << "Error: Element: " << e.objId().path()
             << ": HHGate::tabFillExpr: empty expression for B" << endl;
        return;
    }
    if(!parser_.compile(betaExpr_, beta_)) {
        cerr << "Error: Element: " << e.objId().path()
             << ": HHGate::tabFillExpr: cannot compile expression!\n"
             << betaExpr_ << endl
             << parser_.error() << endl;
        return;
    }
    if((xmax_ == 1) && (xmin_ == 0)) {
        cout << "Warning: " << e.objId().path()
             << ": HHGate::tabFillExpr: `min` and `max` have default values. "
                "Did you forget to"
             << " set them?" << endl;
    }
    unsigned int xdivs = A_.size() - 1;
    assert(A_.size() == B_.size());
    invDx_ = static_cast<double>(xdivs) / (xmax_ - xmin_);
    double dv = (xmax_ - xmin_) / xdivs;
    double prevA{0}, prevB{0};
    for(int ii = 0; ii <= xdivs; ++ii) {
        v_ = xmin_ + ii * dv;
        // Check singularity to avoid division by 0/nan values
        double a_{alpha_.value()}, b_{beta_.value()};
    // Check for nan
    if (a_ != a_){
        a_ = prevA;
    }
    if (b_ != b_){
        b_ = prevB;
    }
        if(form_ == 1) {  // alpha/beta
            b_ += a_;     // B = alpha + beta
            A_[ii] = a_;
            B_[ii] = fabs(b_) < SINGULARITY? SINGULARITY: b_;
        prevA = a_;
        prevB = B_[ii] - a_;
        }
        else {  // form = 2, tau/inf
        if (fabs(a_) < SINGULARITY){
        a_ = prevA;
        b_ = prevB;
        } else {
        B_[ii] = 1 / a_;
        A_[ii] = b_ / a_;
        prevA = a_;
        prevB = b_;
        }
        }
    }
}
References alphaExpr_, betaExpr_, form_, invDx_, Eref::objId(), ObjId::path(), SINGULARITY, moose::trim(), xmax_, and xmin_.
Referenced by HHChannel::vReinit().
getAlpha()
vector< double > HHGate::getAlpha (const Eref & e) const
Definition at line 369 of file HHGate.cpp.
{
    return alpha_;
}
getAlphaExpr()
string HHGate::getAlphaExpr (const Eref & e) const
Definition at line 543 of file HHGate.cpp.
{
    return form_ == 1 ? alphaExpr_ : "";
}
References alphaExpr_, and form_.
getAlphaParms()
vector< double > HHGate::getAlphaParms (const Eref & e) const
Definition at line 738 of file HHGate.cpp.
{
    vector<double> ret = alpha_;
    ret.insert(ret.end(), beta_.begin(), beta_.end());
    ret.push_back((double)A_.size());
    ret.push_back(xmin_);
    ret.push_back(xmax_);
    return ret;
}
References xmax_, and xmin_.
getBeta()
vector< double > HHGate::getBeta (const Eref & e) const
Definition at line 389 of file HHGate.cpp.
{
    return beta_;
}
getBetaExpr()
string HHGate::getBetaExpr (const Eref & e) const
Definition at line 556 of file HHGate.cpp.
{
    return form_ == 1 ? betaExpr_ : "";
}
References betaExpr_, and form_.
getDivs()
unsigned int HHGate::getDivs (const Eref & e) const
Definition at line 645 of file HHGate.cpp.
{
    return A_.size() - 1;
}
getForm()
int HHGate::getForm () const
Definition at line 595 of file HHGate.cpp.
{
    return form_;
}
References form_.
Referenced by HHChannel::vReinit().
getInfExpr()
string HHGate::getInfExpr (const Eref & e) const
Definition at line 582 of file HHGate.cpp.
{
    return form_ == 2 ? betaExpr_ : "";
}
References betaExpr_, and form_.
getMax()
double HHGate::getMax (const Eref & e) const
Definition at line 622 of file HHGate.cpp.
{
    return xmax_;
}
References xmax_.
Referenced by HHChannel::vReinit().
getMin()
double HHGate::getMin (const Eref & e) const
Definition at line 600 of file HHGate.cpp.
{
    return xmin_;
}
References xmin_.
Referenced by HHChannel::vReinit().
getMinfinity()
vector< double > HHGate::getMinfinity (const Eref & e) const
Definition at line 429 of file HHGate.cpp.
{
    return mInfinity_;
}
getTableA()
vector< double > HHGate::getTableA (const Eref & e) const
Definition at line 668 of file HHGate.cpp.
{
    return A_;
}
getTableB()
vector< double > HHGate::getTableB (const Eref & e) const
Definition at line 689 of file HHGate.cpp.
{
    return B_;
}
getTau()
vector< double > HHGate::getTau (const Eref & e) const
Definition at line 409 of file HHGate.cpp.
{
    return tau_;
}
getTauExpr()
string HHGate::getTauExpr (const Eref & e) const
Definition at line 569 of file HHGate.cpp.
{
    return form_ == 2 ? alphaExpr_ : "";
}
References alphaExpr_, and form_.
getUseInterpolation()
bool HHGate::getUseInterpolation (const Eref & e) const
Definition at line 709 of file HHGate.cpp.
{
    return lookupByInterpolation_;
}
References lookupByInterpolation_.
initCinfo()
const Cinfo * HHGate::initCinfo () static
Definition at line 21 of file HHGate.cpp.
{
    // Field definitions.
    static ReadOnlyLookupValueFinfo<HHGate, double, double> A(
        "A",
        "lookupA: Look up the A gate value from a double. Usually does"
        "so by direct scaling and offset to an integer lookup, using"
        "a fine enough table granularity that there is little error."
        "Alternatively uses linear interpolation."
        "The range of the double is predefined based on knowledge of"
        "voltage or conc ranges, and the granularity is specified by"
        "the min, max, and divs fields.",
        &HHGate::lookupA);
    static ReadOnlyLookupValueFinfo<HHGate, double, double> B(
        "B",
        "lookupB: Look up the B gate value from a double."
        "Note that this looks up the raw tables, which are transformed"
        "from the reference parameters.",
        &HHGate::lookupB);
    static ElementValueFinfo<HHGate, vector<double>> alpha(
        "alpha",
        "Parameters for voltage-dependent rates, alpha:"
        "Set up alpha term using 5 parameters, as follows:"
        "y(x) = (A + B * x) / (C + exp((x + D) / F))"
        "The original HH equations can readily be cast into this form",
        &HHGate::setAlpha, &HHGate::getAlpha);
    static ElementValueFinfo<HHGate, vector<double>> beta(
        "beta",
        "Parameters for voltage-dependent rates, beta:"
        "Set up beta term using 5 parameters, as follows:"
        "y(x) = (A + B * x) / (C + exp((x + D) / F))"
        "The original HH equations can readily be cast into this form",
        &HHGate::setBeta, &HHGate::getBeta);
    static ElementValueFinfo<HHGate, vector<double>> tau(
        "tau",
        "Parameters for voltage-dependent rates, tau:"
        "Set up tau curve using 5 parameters, as follows:"
        "y(x) = (A + B * x) / (C + exp((x + D) / F))",
        &HHGate::setTau, &HHGate::getTau);
    static ElementValueFinfo<HHGate, vector<double>> mInfinity(
        "mInfinity", "Deprecated. Use `inf` instead.", &HHGate::setMinfinity,
        &HHGate::getMinfinity);
    static ElementValueFinfo<HHGate, vector<double>> inf(
        "inf",
        "Parameters for voltage-dependent rates, inf:"
        "Set up inf curve using 5 parameters, as follows:"
        "y(x) = (A + B * x) / (C + exp((x + D) / F))"
        "The original HH equations can readily be cast into this form",
        &HHGate::setMinfinity, &HHGate::getMinfinity);
    static ElementValueFinfo<HHGate, string> alphaExpr(
        "alphaExpr",
        "Explicit expression for computing `alpha`."
        " For using this, `betaExpr` must be set as well.\n"
        " SYNTAX: The expression evaluation uses exprtk syntax,"
        " with predefined variables `alpha`, `beta`, `tau`, `inf`, and `v`."
        " `v` is the input variable, the others can be used as"
        " local variables for intermediate computations.\n"
        "Example:\n"
        "~(alpha:=0.3 * exp(-80 * (v -(-46e-3))) + 3.5,"
        "alpha < 3.8? 3.8: alpha)\n"
        " first computes a local variable `alpha` by the first formula,"
        " and if it is < 3.8 then returns 3.8, otherwise returns the"
        " computed value.",
        &HHGate::setAlphaExpr, &HHGate::getAlphaExpr);
    static ElementValueFinfo<HHGate, string> betaExpr(
        "betaExpr",
        "Explicit expression for computing `beta`."
        " For using this, `alphaExpr` must be set as well."
        " See `alphaExpr` and `HHChannelF` documentation.",
        &HHGate::setBetaExpr, &HHGate::getBetaExpr);
    static ElementValueFinfo<HHGate, string> tauExpr(
        "tauExpr",
        "Explicit expression for computing `tau`."
        " For using this, `infExpr` must be set as well."
        " See `alphaExpr` and `HHChannelF` documentation.",
        &HHGate::setTauExpr, &HHGate::getTauExpr);
    static ElementValueFinfo<HHGate, string> infExpr(
        "infExpr",
        "Explicit expression for computing `inf`."
        " When using this, `tauExpr` must be set as well."
        " See `alphaExpr` and `HHChannelF` documentation.",
        &HHGate::setInfExpr, &HHGate::getInfExpr);
    static ElementValueFinfo<HHGate, double> min(
        "min", "Minimum range for lookup", &HHGate::setMin, &HHGate::getMin);
    static ElementValueFinfo<HHGate, double> max(
        "max", "Minimum range for lookup", &HHGate::setMax, &HHGate::getMax);
    static ElementValueFinfo<HHGate, unsigned int> divs(
        "divs", "Divisions for lookup. Zero means to use linear interpolation",
        &HHGate::setDivs, &HHGate::getDivs);
    static ElementValueFinfo<HHGate, vector<double>> tableA(
        "tableA", "Table of A entries", &HHGate::setTableA, &HHGate::getTableA);
    static ElementValueFinfo<HHGate, vector<double>> tableB(
        "tableB", "Table of alpha + beta entries", &HHGate::setTableB,
        &HHGate::getTableB);
    static ElementValueFinfo<HHGate, bool> useInterpolation(
        "useInterpolation",
        "Flag: use linear interpolation if true, else direct lookup",
        &HHGate::setUseInterpolation, &HHGate::getUseInterpolation);
    static ReadOnlyValueFinfo<HHGate, int> form(
        "form",
        "Form of the gate specification:\n 0 for old-style tables,\n"
        " 1 for expression string in alpha-beta form, and\n"
        " 2 for expression string in tau-inf form.\n"
        "This is set automatically when the user assigns the gate"
        " tables or the expressions.",
        &HHGate::getForm);
    static ElementValueFinfo<HHGate, vector<double>> alphaParms(
        "alphaParms",
        "Set up both gates using 13 parameters, as follows:"
        "setupAlpha AA AB AC AD AF BA BB BC BD BF xdivs xmin xmax"
        "Here AA-AF are Coefficients A to F of the alpha (forward) term"
        "Here BA-BF are Coefficients A to F of the beta (reverse) term"
        "Here xdivs is the number of entries in the table,"
        "xmin and xmax define the range for lookup."
        "Outside this range the returned value will be the low [high]"
        "entry of the table."
        "The equation describing each table is:"
        "y(x) = (A + B * x) / (C + exp((x + D) / F))"
        "The original HH equations can readily be cast into this form",
        &HHGate::setupAlpha, &HHGate::getAlphaParms);
    // DestFinfos
    static DestFinfo setupAlpha(
        "setupAlpha",
        "Set up both gates using 13 parameters, as follows:"
        "setupAlpha AA AB AC AD AF BA BB BC BD BF xdivs xmin xmax"
        "Here AA-AF are Coefficients A to F of the alpha (forward) term"
        "Here BA-BF are Coefficients A to F of the beta (reverse) term"
        "Here xdivs is the number of entries in the table,"
        "xmin and xmax define the range for lookup."
        "Outside this range the returned value will be the low [high]"
        "entry of the table."
        "The equation describing each table is:"
        "y(x) = (A + B * x) / (C + exp((x + D) / F))"
        "The original HH equations can readily be cast into this form",
        new EpFunc1<HHGate, vector<double>>(&HHGate::setupAlpha));
    static DestFinfo setupTau(
        "setupTau",
        "Identical to setupAlpha, except that the forms specified by"
        "the 13 parameters are for the tau and m-infinity curves rather"
        "than the alpha and beta terms. So the parameters are:"
        "setupTau TA TB TC TD TF MA MB MC MD MF xdivs xmin xmax"
        "As before, the equation describing each curve is:"
        "y(x) = (A + B * x) / (C + exp((x + D) / F))",
        new EpFunc1<HHGate, vector<double>>(&HHGate::setupTau));
    static DestFinfo tweakAlpha(
        "tweakAlpha",
        "Dummy function for backward compatibility. It used to convert"
        "the tables from alpha, beta values to alpha, alpha+beta"
        "because the internal calculations used these forms. Not"
        "needed now, deprecated.",
        new OpFunc0<HHGate>(&HHGate::tweakAlpha));
    static DestFinfo tweakTau(
        "tweakTau",
        "Dummy function for backward compatibility. It used to convert"
        "the tables from tau, inf values to alpha, alpha+beta"
        "because the internal calculations used these forms. Not"
        "needed now, deprecated.",
        new OpFunc0<HHGate>(&HHGate::tweakTau));
    static DestFinfo setupGate(
        "setupGate",
        "Sets up one gate at a time using the alpha/beta form."
        "Has 9 parameters, as follows:"
        "setupGate A B C D F xdivs xmin xmax is_beta"
        "This sets up the gate using the equation:"
        "y(x) = (A + B * x) / (C + exp((x + D) / F))"
        "Deprecated.",
        new EpFunc1<HHGate, vector<double>>(&HHGate::setupGate));
    static DestFinfo fillFromExpr(
        "fillFromExpr",
        "If the gating variables are specified as string expressions"
        " (alphaExpr/betaExpr/tauExpr/infExpr), then fill up the"
        " tables by evaluating the expressions. This function is"
        " for debugging. If assigned, the expressions are evaluated to fill"
        " the tables at `reinit()`",
        new EpFunc0<HHGate>(&HHGate::fillFromExpr));
    static Finfo* HHGateFinfos[] = {
        &A,          // ReadOnlyLookupValue
        &B,          // ReadOnlyLookupValue
        &alpha,      // ElementValue
        &beta,       // ElementValue
        &tau,        // ElementValue
        &mInfinity,  // ElementValue
        &inf,        // ElementValue
        &alphaExpr,
        &betaExpr,
        &tauExpr,
        &infExpr,
        &min,               // ElementValue
        &max,               // ElementValue
        &divs,              // ElementValue
        &tableA,            // ElementValue
        &tableB,            // ElementValue
        &useInterpolation,  // ElementValue
        &alphaParms,        // ElementValue
        &setupAlpha,        // Dest
        &setupTau,          // Dest
        &tweakAlpha,        // Dest
        &tweakTau,          // Dest
        &setupGate,         // Dest
        &fillFromExpr,       // Dest
    };
    static string doc[] = {
        "Name",
        "HHGate",
        "Author",
        "Upinder S. Bhalla, 2011, NCBS. Updates by Subhasis Ray, 2025, CHINTA",
        "Description",
        "HHGate: Gate for Hodkgin-Huxley type channels, equivalent to the"
        " m and h terms on the Na squid channel and the n term on K."
        " This takes the voltage and state variable from the channel,"
        " computes the new value of the state variable and a scaling,"
        " depending on gate power, for the conductance.\n"
    "This class uses a pair of lookup tables to quickly"
    " find the gating terms for a given voltage.\n"
    "To populate the tables one can directly assign precomputed arrays"
    " to `tableA` and `tableB` fields, or use specify string equations"
    " for `alphaExpr/betaExpr` or `tauExpr/infExpr`."
    " This requires the fields the range of input voltages be specified"
    " through the fields `min`, `max` and `divs`.\n"
    " When the gate equations can be expressed in the standard form"
    " `y(x) = (A + B * x) / (C + exp((x + D) / F))` one can "
    " set `alphaParms` or call `setupAlpha()` or `setupTau()`"
    " functions with the proper arguments to setup the tables."
    ,
    };
    static Dinfo<HHGate> dinfo;
    static Cinfo HHGateCinfo("HHGate", Neutral::initCinfo(), HHGateFinfos,
                             sizeof(HHGateFinfos) / sizeof(Finfo*), &dinfo, doc,
                             sizeof(doc) / sizeof(string));
    return &HHGateCinfo;
}
References Neutral::initCinfo().
Referenced by HHChannel::initCinfo().
lookupA()
double HHGate::lookupA (double v) const
lookupA: Look up the A vector from a double. Typically does so by direct scaling and offset to an integer lookup, using a fine enough table granularity that there is little error. Alternatively uses linear interpolation. The range of the double is predefined based on knowledge of voltage or conc ranges, and the granularity is specified by the xmin, xmax, and invDx fields.
Definition at line 334 of file HHGate.cpp.
{
    return lookupTable(A_, v);
}
lookupB()
double HHGate::lookupB (double v) const
lookupB: Look up the B vector from a double, similar to lookupA.
Definition at line 339 of file HHGate.cpp.
{
    return lookupTable(B_, v);
}
lookupBoth()
void HHGate::lookupBoth (double v, double * A, double * B) const
Single call to get both A and B values by lookup
Definition at line 344 of file HHGate.cpp.
{
    if(v <= xmin_) {
        *A = A_[0];
        *B = B_[0];
    }
    else if(v >= xmax_) {
        *A = A_.back();
        *B = B_.back();
    }
    else {
        unsigned int index = static_cast<unsigned int>((v - xmin_) * invDx_);
        assert(A_.size() > index && B_.size() > index);
        if(lookupByInterpolation_) {
            double frac = (v - xmin_ - index / invDx_) * invDx_;
            *A = A_[index] * (1 - frac) + A_[index + 1] * frac;
            *B = B_[index] * (1 - frac) + B_[index + 1] * frac;
        }
        else {
            *A = A_[index];
            *B = B_[index];
        }
    }
}
References invDx_, lookupByInterpolation_, xmax_, and xmin_.
Referenced by HSolveUtils::rates(), HHChannel::vProcess(), and HHChannel::vReinit().
lookupTable()
double HHGate::lookupTable (const vector< double > & tab, double v) const
Returns looked up value of specified table
Definition at line 317 of file HHGate.cpp.
{
    if(v <= xmin_)
        return tab[0];
    if(v >= xmax_)
        return tab.back();
    if(lookupByInterpolation_) {
        unsigned int index = static_cast<unsigned int>((v - xmin_) * invDx_);
        assert(tab.size() > index);
        double frac = (v - xmin_ - index / invDx_) * invDx_;
        return tab[index] * (1 - frac) + tab[index + 1] * frac;
    }
    else {
        return tab[static_cast<unsigned int>((v - xmin_) * invDx_)];
    }
}
References invDx_, lookupByInterpolation_, xmax_, and xmin_.
setAlpha()
void HHGate::setAlpha (const Eref & e, vector< double > val)
Definition at line 374 of file HHGate.cpp.
{
    if(val.size() != 5) {
        cout << "Error: HHGate::setAlpha on " << e.id().path()
             << ": Number of entries on argument vector should be 5, was "
             << val.size() << endl;
        return;
    }
    if(checkOriginal(e.id(), "alpha")) {
        alpha_ = val;
        updateTauMinf();
        updateTables();
    }
}
References HHGateBase::checkOriginal(), Eref::id(), Id::path(), updateTables(), and updateTauMinf().
setAlphaExpr()
void HHGate::setAlphaExpr (const Eref & e, string expr)
Set/get expression for alpha.
Definition at line 548 of file HHGate.cpp.
{
    if(checkOriginal(e.id(), "alphaExpr")) {
        form_ = 1;
        alphaExpr_ = expr;
    }
}
References alphaExpr_, HHGateBase::checkOriginal(), form_, and Eref::id().
setBeta()
void HHGate::setBeta (const Eref & e, vector< double > val)
Definition at line 394 of file HHGate.cpp.
{
    if(val.size() != 5) {
        cout << "Error: HHGate::setBeta on " << e.id().path()
             << ": Number of entries on argument vector should be 5, was "
             << val.size() << endl;
        return;
    }
    if(checkOriginal(e.id(), "beta")) {
        beta_ = val;
        updateTauMinf();
        updateTables();
    }
}
References HHGateBase::checkOriginal(), Eref::id(), Id::path(), updateTables(), and updateTauMinf().
setBetaExpr()
void HHGate::setBetaExpr (const Eref & e, string expr)
Set/get expression for beta.
Definition at line 561 of file HHGate.cpp.
{
    if(checkOriginal(e.id(), "betaExpr")) {
        form_ = 1;
        betaExpr_ = expr;
    }
}
References betaExpr_, HHGateBase::checkOriginal(), form_, and Eref::id().
setDivs()
void HHGate::setDivs (const Eref & e, unsigned int val)
Stuff here to redo sizes.
Definition at line 650 of file HHGate.cpp.
{
    if(checkOriginal(e.id(), "divs")) {
        if(isDirectTable_) {
            invDx_ = static_cast<double>(val) / (xmax_ - xmin_);
            tabFill(A_, val, xmin_, xmax_);
            tabFill(B_, val, xmin_, xmax_);
        }
        else {
            A_.resize(val + 1);
            B_.resize(val + 1);
            invDx_ = static_cast<double>(val) / (xmax_ - xmin_);
            updateTables();
        }
    }
}
References HHGateBase::checkOriginal(), Eref::id(), invDx_, isDirectTable_, updateTables(), xmax_, and xmin_.
setInfExpr()
void HHGate::setInfExpr (const Eref & e, string expr)
Set/get expression for inf.
Definition at line 587 of file HHGate.cpp.
{
    if(checkOriginal(e.id(), "infExpr")) {
        form_ = 2;
        betaExpr_ = expr;
    }
}
References betaExpr_, HHGateBase::checkOriginal(), form_, and Eref::id().
setMax()
void HHGate::setMax (const Eref & e, double val)
Definition at line 627 of file HHGate.cpp.
{
    if(checkOriginal(e.id(), "max")) {
        xmax_ = val;
        unsigned int xdivs = A_.size() - 1;
        if(isDirectTable_ && xdivs > 0) {
            // Set up using direct assignment of table values.
            invDx_ = static_cast<double>(xdivs) / (val - xmin_);
            tabFill(A_, xdivs, xmin_, val);
            tabFill(B_, xdivs, xmin_, val);
        }
        else {
            // Set up using functional form. here we just recalculate.
            updateTables();
        }
    }
}
References HHGateBase::checkOriginal(), Eref::id(), invDx_, isDirectTable_, updateTables(), xmax_, and xmin_.
setMin()
void HHGate::setMin (const Eref & e, double val)
Definition at line 605 of file HHGate.cpp.
{
    if(checkOriginal(e.id(), "min")) {
        xmin_ = val;
        unsigned int xdivs = A_.size() - 1;
        if(isDirectTable_ && xdivs > 0) {
            // Stuff here to stretch out table using interpolation.
            invDx_ = static_cast<double>(xdivs) / (xmax_ - val);
            tabFill(A_, xdivs, val, xmax_);
            tabFill(B_, xdivs, val, xmax_);
        }
        else {
            updateTables();
        }
    }
}
References HHGateBase::checkOriginal(), Eref::id(), invDx_, isDirectTable_, updateTables(), xmax_, and xmin_.
setMinfinity()
void HHGate::setMinfinity (const Eref & e, vector< double > val)
Definition at line 434 of file HHGate.cpp.
{
    if(val.size() != 5) {
        cout << "Error: HHGate::setMinfinity on " << e.id().path()
             << ": Number of entries on argument vector should be 5, was "
             << val.size() << endl;
        return;
    }
    if(checkOriginal(e.id(), "mInfinity")) {
        mInfinity_ = val;
        updateAlphaBeta();
        updateTables();
    }
}
References HHGateBase::checkOriginal(), Eref::id(), Id::path(), updateAlphaBeta(), and updateTables().
setTableA()
void HHGate::setTableA (const Eref & e, vector< double > v)
Definition at line 673 of file HHGate.cpp.
{
    if(v.size() < 2) {
        cout << "Warning: HHGate::setTableA: size must be >= 2 entries on "
             << e.id().path() << endl;
        return;
    }
    if(checkOriginal(e.id(), "tableA")) {
        isDirectTable_ = 1;
        A_ = v;
        unsigned int xdivs = A_.size() - 1;
        invDx_ = static_cast<double>(xdivs) / (xmax_ - xmin_);
        form_ = 0;
    }
}
References HHGateBase::checkOriginal(), form_, Eref::id(), invDx_, isDirectTable_, Id::path(), xmax_, and xmin_.
setTableB()
void HHGate::setTableB (const Eref & e, vector< double > v)
Definition at line 694 of file HHGate.cpp.
{
    if(checkOriginal(e.id(), "tableB")) {
        isDirectTable_ = 1;
        if(A_.size() != v.size()) {
            cout << "Warning: HHGate::setTableB: size should be same as table "
                    "A: "
                 << v.size() << " != " << A_.size() << ". Ignoring.\n";
            return;
        }
        B_ = v;
        form_ = 0;
    }
}
References HHGateBase::checkOriginal(), form_, Eref::id(), and isDirectTable_.
setTau()
void HHGate::setTau (const Eref & e, vector< double > val)
Definition at line 414 of file HHGate.cpp.
{
    if(val.size() != 5) {
        cout << "Error: HHGate::setTau on " << e.id().path()
             << ": Number of entries on argument vector should be 5, was "
             << val.size() << endl;
        return;
    }
    if(checkOriginal(e.id(), "tau")) {
        tau_ = val;
        updateAlphaBeta();
        updateTables();
    }
}
References HHGateBase::checkOriginal(), Eref::id(), Id::path(), updateAlphaBeta(), and updateTables().
setTauExpr()
void HHGate::setTauExpr (const Eref & e, string expr)
Set/get expression for tau.
Definition at line 574 of file HHGate.cpp.
{
    if(checkOriginal(e.id(), "tauExpr")) {
        form_ = 2;
        alphaExpr_ = expr;
    }
}
References alphaExpr_, HHGateBase::checkOriginal(), form_, and Eref::id().
setupAlpha()
void HHGate::setupAlpha (const Eref & e, vector< double > parms)
Definition at line 720 of file HHGate.cpp.
{
    if(checkOriginal(e.id(), "setupAlpha")) {
        if(parms.size() != 13) {
            cout << "HHGate::setupAlpha: Error: parms.size() != 13\n";
            return;
        }
        setupTables(parms, false);
        alpha_.resize(5, 0);
        beta_.resize(5, 0);
        for(unsigned int i = 0; i < 5; ++i)
            alpha_[i] = parms[i];
        for(unsigned int i = 5; i < 10; ++i)
            beta_[i - 5] = parms[i];
        form_ = 0;
    }
}
References HHGateBase::checkOriginal(), form_, and Eref::id().
setupGate()
void HHGate::setupGate (const Eref & e, vector< double > parms)
Definition at line 912 of file HHGate.cpp.
{
    // The nine arguments are :
    // A B C D F size min max isbeta
    // If size == 0 then we check that the gate has already been allocated.
    // If isbeta is true then we also have to do the conversion to
    // HHGate form of alpha, alpha+beta, assuming that the alpha gate
    // has already been setup. This uses tweakTables.
    // We may need to resize the tables if they don't match here.
    if(!checkOriginal(e.id(), "setupGate"))
        return;
    if(parms.size() != 9) {
        cout << "HHGate::setupGate: Error: parms.size() != 9\n";
        return;
    }
    double A = parms[0];
    double B = parms[1];
    double C = parms[2];
    double D = parms[3];
    double F = parms[4];
    int size = static_cast<int>(parms[5]);
    double min = parms[6];
    double max = parms[7];
    bool isBeta = static_cast<bool>(parms[8]);
    vector<double>& ip = (isBeta) ? B_ : A_;
    if(size <= 0)  // Look up size, min, max from the interpol
    {
        size = ip.size() - 1;
        if(size <= 0) {
            cout << "Error: setupGate has zero size\n";
            return;
        }
    }
    else {
        ip.resize(size + 1);
    }
    double dx = (max - min) / static_cast<double>(size);
    double x = min + dx / 2.0;
    for(int i = 0; i <= size; i++) {
        if(fabs(F) < SINGULARITY) {
            ip[i] = 0.0;
        }
        else {
            double temp2 = C + exp((x + D) / F);
            if(fabs(temp2) < SINGULARITY)
                ip[i] = ip[i - 1];
            else
                ip[i] = (A + B * x) / temp2;
        }
    }
    if(isBeta) {
        assert(A_.size() > 0);
        // Here we ensure that the tables are the same size
        if(A_.size() != B_.size()) {
            if(A_.size() > B_.size()) {
                // Note that the tabFill expects to allocate the
                // terminating entry, so we put in size - 1.
                tabFill(B_, A_.size() - 1, xmin_, xmax_);
            }
            else {
                tabFill(A_, B_.size() - 1, xmin_, xmax_);
            }
        }
        // Then we do the tweaking to convert to HHChannel form.
        tweakTables(0);
    }
    form_ = 0;
}
References HHGateBase::checkOriginal(), form_, Eref::id(), SINGULARITY, and tweakTables().
setupTables()
void HHGate::setupTables (const vector< double > & parms, bool doTau)
Sets up the tables one at a time. Based on GENESIS/src/olf/new_interp.c, function setup_tab_values, fine tuned by Erik De Schutter.
Definition at line 780 of file HHGate.cpp.
{
    assert(parms.size() == 13);
    static const int XDIVS = 10;
    static const int XMIN = 11;
    static const int XMAX = 12;
    if(parms[XDIVS] < 1)
        return;
    unsigned int xdivs = static_cast<unsigned int>(parms[XDIVS]);
    A_.resize(xdivs + 1);
    B_.resize(xdivs + 1);
    xmin_ = parms[XMIN];
    xmax_ = parms[XMAX];
    assert(xmax_ > xmin_);
    invDx_ = xdivs / (xmax_ - xmin_);
    double dx = (xmax_ - xmin_) / xdivs;
    double x = xmin_;
    double prevAentry = 0.0;
    double prevBentry = 0.0;
    double temp;
    double temp2 = 0.0;
    unsigned int i;
    for(i = 0; i <= xdivs; i++) {
        if(fabs(parms[4]) < SINGULARITY) {
            temp = 0.0;
            A_[i] = temp;
        }
        else {
            temp2 = parms[2] + exp((x + parms[3]) / parms[4]);
            if(fabs(temp2) < SINGULARITY) {
                temp2 = parms[2] + exp((x + dx / 10.0 + parms[3]) / parms[4]);
                temp = (parms[0] + parms[1] * (x + dx / 10)) / temp2;
                temp2 = parms[2] + exp((x - dx / 10.0 + parms[3]) / parms[4]);
                temp += (parms[0] + parms[1] * (x - dx / 10)) / temp2;
                temp /= 2.0;
                // cout << "interpolated temp = " << temp << ", prev = " <<
                // prevAentry << endl;
                // temp = prevAentry;
                A_[i] = temp;
            }
            else {
                temp = (parms[0] + parms[1] * x) / temp2;
                A_[i] = temp;
            }
        }
        if(fabs(parms[9]) < SINGULARITY) {
            B_[i] = 0.0;
        }
        else {
            temp2 = parms[7] + exp((x + parms[8]) / parms[9]);
            if(fabs(temp2) < SINGULARITY) {
                temp2 = parms[7] + exp((x + dx / 10.0 + parms[8]) / parms[9]);
                temp = (parms[5] + parms[6] * (x + dx / 10)) / temp2;
                temp2 = parms[7] + exp((x - dx / 10.0 + parms[8]) / parms[9]);
                temp += (parms[5] + parms[6] * (x - dx / 10)) / temp2;
                temp /= 2.0;
                B_[i] = temp;
                // B_[i] = prevBentry;
            }
            else {
                B_[i] = (parms[5] + parms[6] * x) / temp2;
                // B_.table_[i] = ( parms[5] + parms[6] * x ) / temp2;
            }
        }
        // There are cleaner ways to do this, but this keeps
        // the relation to the GENESIS version clearer.
        // Note the additional SINGULARITY check, to fix a bug
        // in the earlier code.
        if(doTau == 0 && fabs(temp2) > SINGULARITY)
            B_[i] += temp;
        prevAentry = A_[i];
        prevBentry = B_[i];
        x += dx;
    }
    prevAentry = 0.0;
    prevBentry = 0.0;
    if(doTau) {
        for(i = 0; i <= xdivs; i++) {
            temp = A_[i];
            temp2 = B_[i];
            if(fabs(temp) < SINGULARITY) {
                A_[i] = prevAentry;
                B_[i] = prevBentry;
            }
            else {
                A_[i] = temp2 / temp;
                B_[i] = 1.0 / temp;
            }
            prevAentry = A_[i];
            prevBentry = B_[i];
        }
    }
    form_ = 0;
}
References form_, invDx_, SINGULARITY, xmax_, and xmin_.
setupTau()
void HHGate::setupTau (const Eref & e, vector< double > parms)
Definition at line 753 of file HHGate.cpp.
{
    if(checkOriginal(e.id(), "setupTau")) {
        if(parms.size() != 13) {
            cout << "HHGate::setupTau: Error: parms.size() != 13\n";
            return;
        }
        setupTables(parms, true);
        form_ = 0;
    }
}
References HHGateBase::checkOriginal(), form_, and Eref::id().
setUseInterpolation()
void HHGate::setUseInterpolation (const Eref & e, bool val)
Definition at line 714 of file HHGate.cpp.
{
    if(checkOriginal(e.id(), "useInterpolation"))
        lookupByInterpolation_ = val;
}
References HHGateBase::checkOriginal(), Eref::id(), and lookupByInterpolation_.
Referenced by HSolveUtils::rates().
tabFill()
void HHGate::tabFill (vector< double > & table, unsigned int newXdivs, double newXmin, double newXmax)
tabFill does interpolation and range resizing for a table representing a lookup function. newXdivs is one less than the size of the table; it is the number of subdivisions that the table represents. Does NOT alter the existing xmin and xmax, but it does resize the table.
This utility function does interpolation and range resizing for a table representing a lookup function. newXdivs is one less than the size of the table; it is the number of subdivisions that the table represents.
Definition at line 997 of file HHGate.cpp.
{
    if(newXdivs < 3) {
        cout << "Error: tabFill: # divs must be >= 3. Not filling table.\n";
        return;
    }
    vector<double> old = table;
    double newDx = (newXmax - newXmin) / newXdivs;
    table.resize(newXdivs + 1);
    bool origLookupMode = lookupByInterpolation_;
    lookupByInterpolation_ = 1;
    for(unsigned int i = 0; i <= newXdivs; ++i) {
        table[i] = lookupTable(table, newXmin + i * newDx);
    }
    lookupByInterpolation_ = origLookupMode;
}
References lookupByInterpolation_.
tweakAlpha()
void HHGate::tweakAlpha ()
Definition at line 765 of file HHGate.cpp.
{
    ;  // Dummy
}
tweakTables()
void HHGate::tweakTables (bool doTau)
Tweaks the A and B entries in the tables from the original alpha/beta or inf/tau values. See code in GENESIS/src/olf/new_interp.c, function tweak_tab_values
Definition at line 887 of file HHGate.cpp.
{
    unsigned int i;
    unsigned int size = A_.size();
    assert(size == B_.size());
    if(doTau) {
        for(i = 0; i < size; i++) {
            double temp = A_[i];
            double temp2 = B_[i];
            if(fabs(temp) < SINGULARITY) {
                if(temp < 0.0)
                    temp = -SINGULARITY;
                else
                    temp = SINGULARITY;
            }
            A_[i] = temp2 / temp;
            B_[i] = 1.0 / temp;
        }
    }
    else {
        for(i = 0; i < size; i++)
            B_[i] = A_[i] + B_[i];
    }
}
References SINGULARITY.
Referenced by setupGate().
tweakTau()
void HHGate::tweakTau ()
Definition at line 770 of file HHGate.cpp.
{
    ;  // Dummy
}
updateAlphaBeta()
void HHGate::updateAlphaBeta ()
Update the alpha and beta parameters because the tau or minfinity tables have changed.
Definition at line 1018 of file HHGate.cpp.
{
}
Referenced by setMinfinity(), and setTau().
updateTables()
void HHGate::updateTables ()
Take the current alpha/beta parameters, and xdivs, xmin, xmax; and rebuild the tables.
Definition at line 1026 of file HHGate.cpp.
{
    if(alpha_.size() == 0 || beta_.size() == 0)
        return;
    vector<double> parms = alpha_;
    parms.insert(parms.end(), beta_.begin(), beta_.end());
    parms.push_back((double)A_.size());
    parms.push_back(xmin_);
    parms.push_back(xmax_);
    setupTables(parms, 0);
}
References xmax_, and xmin_.
Referenced by setAlpha(), setBeta(), setDivs(), setMax(), setMin(), setMinfinity(), and setTau().
updateTauMinf()
void HHGate::updateTauMinf ()
Update the Tau and Minfinity parameters because the alpha or beta tables have changed.
Definition at line 1022 of file HHGate.cpp.
{
}
Referenced by setAlpha(), and setBeta().
Friends And Related Symbol Documentation
testHHGateLookup
void testHHGateLookup () friend
testHHGateSetup
void testHHGateSetup () friend
Member Data Documentation
A_
vector<double> HHGate::A_ private
The actual lookup table for calculations. Holds alpha(V).
Definition at line 195 of file HHGate.h.
alpha_
vector<double> HHGate::alpha_ private
5 parameters for alpha
Definition at line 177 of file HHGate.h.
alphaExpr_
string HHGate::alphaExpr_ private
Strings for expressions.
Definition at line 189 of file HHGate.h.
Referenced by fillFromExpr(), getAlphaExpr(), getTauExpr(), HHGate(), HHGate(), setAlphaExpr(), and setTauExpr().
B_
vector<double> HHGate::B_ private
The lookup table for calculations. Holds alpha(V) + beta(V).
Definition at line 198 of file HHGate.h.
beta_
vector<double> HHGate::beta_ private
5 parameters for beta
Definition at line 180 of file HHGate.h.
betaExpr_
string HHGate::betaExpr_ private
Definition at line 190 of file HHGate.h.
Referenced by fillFromExpr(), getBetaExpr(), getInfExpr(), HHGate(), HHGate(), setBetaExpr(), and setInfExpr().
form_
int HHGate::form_ private
Flag if the expressions are in tau-inf form or explicitly set 0 - not using expression, 1 - alpha/beta, 2 - tau/inf
Definition at line 193 of file HHGate.h.
Referenced by fillFromExpr(), getAlphaExpr(), getBetaExpr(), getForm(), getInfExpr(), getTauExpr(), HHGate(), HHGate(), setAlphaExpr(), setBetaExpr(), setInfExpr(), setTableA(), setTableB(), setTauExpr(), setupAlpha(), setupGate(), setupTables(), and setupTau().
invDx_
double HHGate::invDx_ private
increment of the range.
Definition at line 207 of file HHGate.h.
Referenced by fillFromExpr(), HHGate(), HHGate(), lookupBoth(), lookupTable(), setDivs(), setMax(), setMin(), setTableA(), and setupTables().
isDirectTable_
bool HHGate::isDirectTable_ private
Flag to indicate if table entries have been assigned directly (as direct experimental data, or an externally defined V-dep function). When zero it means that the curve-fit forms from setupAlpha etc. have been used.
Definition at line 234 of file HHGate.h.
Referenced by HHGate(), HHGate(), setDivs(), setMax(), setMin(), setTableA(), and setTableB().
lookupByInterpolation_
bool HHGate::lookupByInterpolation_ private
Flag: Use linear interpolation for lookup if true, use direct table lookup if false.
Definition at line 226 of file HHGate.h.
Referenced by getUseInterpolation(), HHGate(), HHGate(), lookupBoth(), lookupTable(), setUseInterpolation(), and tabFill().
mInfinity_
vector<double> HHGate::mInfinity_ private
5 parameters for mInfinity
Definition at line 186 of file HHGate.h.
originalChanId_
Id HHGate::originalChanId_ private
Id of original channel, the one which has actually allocated it, All other Elements have to treat the values as readonly.
Definition at line 213 of file HHGate.h.
originalGateId_
Id HHGate::originalGateId_ private
Id of original Gate, the one which was created with the original channel. All other Elements have to treat the values as readonly.
Definition at line 220 of file HHGate.h.
tau_
vector<double> HHGate::tau_ private
5 parameters for tau
Definition at line 183 of file HHGate.h.
xmax_
double HHGate::xmax_ private
Max of the voltage (or conc) range.
Definition at line 204 of file HHGate.h.
Referenced by fillFromExpr(), getAlphaParms(), getMax(), HHGate(), HHGate(), lookupBoth(), lookupTable(), setDivs(), setMax(), setMin(), setTableA(), setupTables(), and updateTables().
xmin_
double HHGate::xmin_ private
Minimum of the voltage (or conc) range.
Definition at line 201 of file HHGate.h.
Referenced by fillFromExpr(), getAlphaParms(), getMin(), HHGate(), HHGate(), lookupBoth(), lookupTable(), setDivs(), setMax(), setMin(), setTableA(), setupTables(), and updateTables().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/biophysics/HHGate.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/biophysics/HHGate.cpp