MOOSE - Multiscale Object Oriented Simulation Environment: moose::VClamp Class Reference
moose::VClamp Class Reference
#include <VClamp.h>
Public Member Functions
double getCommand () const
double getCurrent () const
double getGain () const
unsigned int getMode () const
double getTau () const
double getTd () const
double getTi () const
double getVin () const
void process (const Eref &e, ProcPtr p)
void reinit (const Eref &e, ProcPtr p)
void setCommand (double v)
void setGain (double value)
void setMode (unsigned int mode)
void setTau (double value)
void setTd (double value)
void setTi (double value)
void setVin (double v)
VClamp ()
~VClamp ()
Static Public Member Functions
static SrcFinfo1< double > * currentOut ()
static const Cinfo * initCinfo ()
Protected Attributes
double cmdIn_
double command_
double current_
double dtByTi_
double e1_
double e2_
double e_
double expt_
double Kp_
unsigned int mode_
double oldCmdIn_
double tau_
double tauByDt_
double td_
double tdByDt_
double ti_
double v1_
double vIn_
Static Private Attributes
static const unsigned DERIVATIVE_ON_PV = 1
static const unsigned PROPORTIONAL_ON_PV = 2
Detailed Description
Definition at line 51 of file VClamp.h.
Constructor & Destructor Documentation
VClamp()
VClamp::VClamp ()
Definition at line 196 of file VClamp.cpp.
              : vIn_(0.0), command_(0.0), current_(0.0), mode_(0), ti_(0.0), td_(-1.0),
                  Kp_(0.0),
                  tau_(0.0),
                  tdByDt_(1.0),
                  dtByTi_(1.0),
                  e_(0.0),
                  e1_(0.0),
                  e2_(0.0)
{
}
References command_, current_, dtByTi_, e1_, e2_, e_, Kp_, mode_, tau_, td_, tdByDt_, ti_, and vIn_.
~VClamp()
VClamp::~VClamp ()
Definition at line 207 of file VClamp.cpp.
{
    ;
}
Member Function Documentation
currentOut()
SrcFinfo1< double > * VClamp::currentOut () static
Definition at line 58 of file VClamp.cpp.
{
    static SrcFinfo1< double > currentOut("currentOut",
                                          "Sends out current output of the clamping circuit. This should be"
                                          " connected to the `injectMsg` field of a compartment to voltage clamp"
                                          " it.");
    return &currentOut;
}
References SrcFinfo1< T >::SrcFinfo1().
Referenced by initCinfo(), process(), and reinit().
getCommand()
double VClamp::getCommand () const
Definition at line 217 of file VClamp.cpp.
{
    return cmdIn_;
}
References cmdIn_.
Referenced by initCinfo().
getCurrent()
double VClamp::getCurrent () const
Definition at line 261 of file VClamp.cpp.
{
    return current_;
}
References current_.
Referenced by initCinfo().
getGain()
double VClamp::getGain () const
Definition at line 256 of file VClamp.cpp.
{
    return Kp_;
}
References Kp_.
Referenced by initCinfo().
getMode()
unsigned int VClamp::getMode () const
Definition at line 282 of file VClamp.cpp.
{
    return mode_;
}
References mode_.
Referenced by initCinfo().
getTau()
double VClamp::getTau () const
Definition at line 246 of file VClamp.cpp.
{
    return tau_;
}
References tau_.
Referenced by initCinfo().
getTd()
double VClamp::getTd () const
Definition at line 236 of file VClamp.cpp.
{
    return td_;
}
References td_.
Referenced by initCinfo().
getTi()
double VClamp::getTi () const
Definition at line 227 of file VClamp.cpp.
{
    return ti_;
}
References ti_.
Referenced by initCinfo().
getVin()
double VClamp::getVin () const
Definition at line 271 of file VClamp.cpp.
{
    return vIn_;
}
References vIn_.
Referenced by initCinfo().
initCinfo()
const Cinfo * VClamp::initCinfo () static
Definition at line 68 of file VClamp.cpp.
{
    static DestFinfo process("process",
                             "Handles 'process' call on each time step.",
                             new ProcOpFunc< VClamp >( &VClamp::process));
    static DestFinfo reinit("reinit",
                            "Handles 'reinit' call",
                            new ProcOpFunc< VClamp >( &VClamp::reinit));
    static Finfo * processShared[] = {
        &process,
        &reinit
    };
    static SharedFinfo proc("proc",
                            "Shared message to receive Process messages from the scheduler",
                            processShared, sizeof(processShared) / sizeof(Finfo*));
    static ValueFinfo< VClamp, double> command("command",
                                               "Command input received by the clamp circuit.",
                                               &VClamp::setCommand,
                                               &VClamp::getCommand);
    static ValueFinfo< VClamp, unsigned int> mode("mode",
                                                  "Working mode of the PID controller.\n"
                                                  "\n"
                                                  "   mode = 0, standard PID with proportional, integral and derivative"
                                                  " all acting on the error.\n"
                                                  "\n"
                                                  "   mode = 1, derivative action based on command input\n"
                                                  "\n"
                                                  "   mode = 2, proportional action and derivative action are based on"
                                                  " command input.",
                                                  &VClamp::setMode,
                                                  &VClamp::getMode);
    static ValueFinfo< VClamp, double> ti("ti",
                                          "Integration time of the PID controller. Defaults to 1e9, i.e. integral"
                                          " action is negligibly small.",
                                          &VClamp::setTi,
                                          &VClamp::getTi);
    static ValueFinfo< VClamp, double> td("td",
                                          "Derivative time of the PID controller. This defaults to 0,"
                                          "i.e. derivative action is unused.",
                                          &VClamp::setTd,
                                          &VClamp::getTd);
    static ValueFinfo< VClamp, double> tau("tau",
                                          "Time constant of the lowpass filter at input of the PID"
                                           " controller. This smooths out abrupt changes in the input. Set it to "
                                           " 5 * dt or more to avoid overshoots.",
                                          &VClamp::setTau,
                                          &VClamp::getTau);
    static ValueFinfo< VClamp, double> gain("gain",
                                          "Proportional gain of the PID controller.",
                                          &VClamp::setGain,
                                          &VClamp::getGain);
    static ReadOnlyValueFinfo< VClamp, double> current("current",
                                            "The amount of current injected by the clamp into the membrane.",
                                            &VClamp::getCurrent);
    static ReadOnlyValueFinfo<VClamp, double> sensed("sensed",
                                                     "Membrane potential read from compartment.",
                                                     &VClamp::getVin);
    static DestFinfo sensedIn("sensedIn",
                              "The `VmOut` message of the Compartment object should be connected"
                              " here.",
                              new OpFunc1<VClamp, double>( &VClamp::setVin));
    static DestFinfo commandIn("commandIn",
                              "  The command voltage source should be connected to this.",
                              new OpFunc1<VClamp, double>( &VClamp::setCommand));
    static Finfo* vclampFinfos[] = {
        currentOut(),
        &command,
        &current,
        &sensed,
        &mode,
        &ti,
        &td,
        &tau,
        &gain,
        &sensedIn,
        &commandIn,
        &proc
    };
    static string doc[] = {
        "Name", "VClamp",
        "Author", "Subhasis Ray",
        "Description", "Voltage clamp object for holding neuronal compartments at a specific"
        " voltage.\n"
        "\n"
        "This implementation uses a builtin RC circuit to filter the "
        " command input and then use a PID to bring the sensed voltage (Vm from"
        " compartment) to the filtered command potential.\n"
        "\n"
        "Usage: Connect the `currentOut` source of VClamp to `injectMsg`"
        " dest of Compartment. Connect the `VmOut` source of Compartment to"
        " `set_sensed` dest of VClamp. Either set `command` field to a"
        " fixed value, or connect an appropriate source of command potential"
        " (like the `outputOut` message of an appropriately configured"
        " PulseGen) to `set_command` dest.\n"
        "The default settings for the RC filter and PID controller should be"
        " fine. For step change in command voltage, good defaults with"
        "integration time step dt are as follows:\n"
        "    time constant of RC filter, tau = 5 * dt\n"
        "    proportional gain of PID, gain = Cm/dt where Cm is the membrane"
        "    capacitance of the compartment\n"
        "    integration time of PID, ti = dt\n"
        "    derivative time  of PID, td = 0\n"
        "\n",
    };
    static Dinfo< VClamp > dinfo;
    static Cinfo vclampCinfo(
        "VClamp",
        Neutral::initCinfo(),
        vclampFinfos,
        sizeof(vclampFinfos) / sizeof(Finfo*),
        &dinfo,
        doc,
        sizeof(doc)/sizeof(string));
    return &vclampCinfo;
}
References Cinfo::Cinfo(), currentOut(), DestFinfo::DestFinfo(), getCommand(), getCurrent(), getGain(), getMode(), getTau(), getTd(), getTi(), getVin(), Neutral::initCinfo(), OpFunc1< T, A >::OpFunc1(), process(), ProcOpFunc< T >::ProcOpFunc(), ReadOnlyValueFinfo< T, F >::ReadOnlyValueFinfo(), reinit(), setCommand(), setGain(), setMode(), setTau(), setTd(), setTi(), setVin(), SharedFinfo::SharedFinfo(), and ValueFinfo< T, F >::ValueFinfo().
process()
void VClamp::process (const Eref & e, ProcPtr p)
Definition at line 287 of file VClamp.cpp.
{
    assert(ti_ > 0);
    assert(td_ >= 0);
    assert(tau_ > 0);
    double dCmd = cmdIn_ - oldCmdIn_;
    command_ = cmdIn_ + dCmd * ( 1 - tauByDt_) + (command_ - cmdIn_ + dCmd * tauByDt_) * expt_;
    oldCmdIn_ = cmdIn_;
    e_ = command_ - vIn_;
    if (mode_ == 0){
        current_ +=  Kp_ * ((1 + dtByTi_ + tdByDt_) * e_ - ( 1 + 2 * tdByDt_) * e1_ + tdByDt_ * e2_);
        e2_ = e1_;
        e1_ = e_;
    } else if (mode_ == DERIVATIVE_ON_PV){ // Here the derivative error term is replaced by process variable
        current_ +=  Kp_ * ((1 + dtByTi_) * e_ - e1_ + tdByDt_ * ( vIn_ - 2 * v1_ + e2_));
        e2_ = v1_;
        v1_ = vIn_;
        e1_ = e_;
    } else if (mode_ == PROPORTIONAL_ON_PV){ // Here the proportional as well as the derivative error term is replaced by process variable
        current_ +=  Kp_ * (vIn_ - v1_ + dtByTi_ * e_ + tdByDt_ * ( vIn_ - 2 * v1_ + e2_));
        e2_ = v1_;
        v1_ = vIn_;
    }
    currentOut()->send(e, current_);
}
References cmdIn_, command_, current_, currentOut(), DERIVATIVE_ON_PV, dtByTi_, e1_, e2_, e_, expt_, Kp_, mode_, oldCmdIn_, PROPORTIONAL_ON_PV, SrcFinfo1< T >::send(), tau_, tauByDt_, td_, tdByDt_, ti_, v1_, and vIn_.
Referenced by initCinfo().
reinit()
void VClamp::reinit (const Eref & e, ProcPtr p)
Definition at line 313 of file VClamp.cpp.
{
    vIn_ = 0.0;
    v1_ = 0;
    command_ = cmdIn_ = oldCmdIn_ = e_ = e1_ = e2_ = 0;
    if (ti_ == 0){
        ti_ = p->dt;
    }
    if (td_ < 0){
        td_ = 0.0;
    }
    if (tau_ == 0.0){
        tau_ = 5 * p->dt;
    }
    if (p->dt / tau_ > 1e-15){
        expt_ = exp(-p->dt/tau_);
    } else {
        expt_ = 1 - p->dt/tau_;
    }
    tauByDt_ = tau_ / p->dt;
    dtByTi_ = p->dt/ti_;
    tdByDt_ = td_ / p->dt;
    vector<Id> compartments;
    unsigned int numComp = e.element()->getNeighbors(compartments, currentOut());
    if (numComp > 0){
        double Cm = Field<double>::get(compartments[0], "Cm");
        if (Kp_ == 0){
            Kp_ = Cm / p->dt;
        }
        command_ = cmdIn_ = oldCmdIn_ =
            Field<double>::get(compartments[0], "initVm");
    }
}
References cmdIn_, command_, currentOut(), ProcInfo::dt, dtByTi_, e1_, e2_, e_, Eref::element(), expt_, Field< A >::get(), Element::getNeighbors(), Kp_, oldCmdIn_, tau_, tauByDt_, td_, tdByDt_, ti_, v1_, and vIn_.
Referenced by initCinfo().
setCommand()
void VClamp::setCommand (double v)
Definition at line 212 of file VClamp.cpp.
{
    cmdIn_ = value;
}
References cmdIn_.
Referenced by initCinfo().
setGain()
void VClamp::setGain (double value)
Definition at line 251 of file VClamp.cpp.
{
    Kp_ = value;
}
References Kp_.
Referenced by initCinfo().
setMode()
void VClamp::setMode (unsigned int mode)
Definition at line 277 of file VClamp.cpp.
{
    mode_ = mode;
}
References mode_.
Referenced by initCinfo().
setTau()
void VClamp::setTau (double value)
Definition at line 241 of file VClamp.cpp.
{
    tau_ = value;
}
References tau_.
Referenced by initCinfo().
setTd()
void VClamp::setTd (double value)
Definition at line 231 of file VClamp.cpp.
{
    td_ = value;
}
References td_.
Referenced by initCinfo().
setTi()
void VClamp::setTi (double value)
Definition at line 222 of file VClamp.cpp.
{
    ti_ = value;
}
References ti_.
Referenced by initCinfo().
setVin()
void VClamp::setVin (double v)
Definition at line 266 of file VClamp.cpp.
{
    vIn_ = value;
}
References vIn_.
Referenced by initCinfo().
Member Data Documentation
cmdIn_
double moose::VClamp::cmdIn_ protected
Definition at line 99 of file VClamp.h.
Referenced by getCommand(), process(), reinit(), and setCommand().
command_
double moose::VClamp::command_ protected
Definition at line 83 of file VClamp.h.
Referenced by process(), reinit(), and VClamp().
current_
double moose::VClamp::current_ protected
Definition at line 84 of file VClamp.h.
Referenced by getCurrent(), process(), and VClamp().
DERIVATIVE_ON_PV
const unsigned int VClamp::DERIVATIVE_ON_PV = 1 static private
Definition at line 53 of file VClamp.h.
Referenced by process().
dtByTi_
double moose::VClamp::dtByTi_ protected
Definition at line 93 of file VClamp.h.
Referenced by process(), reinit(), and VClamp().
e1_
double moose::VClamp::e1_ protected
Definition at line 96 of file VClamp.h.
Referenced by process(), reinit(), and VClamp().
e2_
double moose::VClamp::e2_ protected
Definition at line 97 of file VClamp.h.
Referenced by process(), reinit(), and VClamp().
e_
double moose::VClamp::e_ protected
Definition at line 95 of file VClamp.h.
Referenced by process(), reinit(), and VClamp().
expt_
double moose::VClamp::expt_ protected
Definition at line 101 of file VClamp.h.
Referenced by process(), and reinit().
Kp_
double moose::VClamp::Kp_ protected
Definition at line 90 of file VClamp.h.
Referenced by getGain(), process(), reinit(), setGain(), and VClamp().
mode_
unsigned int moose::VClamp::mode_ protected
Definition at line 85 of file VClamp.h.
Referenced by getMode(), process(), setMode(), and VClamp().
oldCmdIn_
double moose::VClamp::oldCmdIn_ protected
Definition at line 100 of file VClamp.h.
Referenced by process(), and reinit().
PROPORTIONAL_ON_PV
const unsigned int VClamp::PROPORTIONAL_ON_PV = 2 static private
Definition at line 54 of file VClamp.h.
Referenced by process().
tau_
double moose::VClamp::tau_ protected
Definition at line 91 of file VClamp.h.
Referenced by getTau(), process(), reinit(), setTau(), and VClamp().
tauByDt_
double moose::VClamp::tauByDt_ protected
Definition at line 94 of file VClamp.h.
Referenced by process(), and reinit().
td_
double moose::VClamp::td_ protected
Definition at line 89 of file VClamp.h.
Referenced by getTd(), process(), reinit(), setTd(), and VClamp().
tdByDt_
double moose::VClamp::tdByDt_ protected
Definition at line 92 of file VClamp.h.
Referenced by process(), reinit(), and VClamp().
ti_
double moose::VClamp::ti_ protected
Definition at line 88 of file VClamp.h.
Referenced by getTi(), process(), reinit(), setTi(), and VClamp().
v1_
double moose::VClamp::v1_ protected
Definition at line 98 of file VClamp.h.
Referenced by process(), and reinit().
vIn_
double moose::VClamp::vIn_ protected
Definition at line 82 of file VClamp.h.
Referenced by getVin(), process(), reinit(), setVin(), and VClamp().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/biophysics/VClamp.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/biophysics/VClamp.cpp