MOOSE - Multiscale Object Oriented Simulation Environment: SetGet2< A1, A2 > Class Template Reference
SetGet2< A1, A2 > Class Template Reference
#include <SetGet.h>
Public Member Functions
SetGet2 ()
Public Member Functions inherited from SetGet
virtual bool checkOpClass (const OpFunc *op) const =0
SetGet ()
virtual ~SetGet ()
Static Public Member Functions
static bool innerStrSet (const ObjId &dest, const string &field, const string &val)
static bool set (const ObjId &dest, const string &field, A1 arg1, A2 arg2)
static bool setVec (Id destId, const string &field, const vector< A1 > &arg1, const vector< A2 > &arg2)
Static Public Member Functions inherited from SetGet
static const OpFunc * checkSet (const string &field, ObjId &tgt, FuncId &fid)
static const vector< double * > * dispatchGet (const ObjId &tgt, FuncId tgtFid, const double *arg, unsigned int size)
Sends out request for data, and awaits its return.
static bool strGet (const ObjId &tgt, const string &field, string &ret)
static bool strSet (const ObjId &dest, const string &field, const string &val)
Detailed Description
template<class A1, class A2>
class SetGet2< A1, A2 >
SetGet2 handles 2-argument Sets. It does not deal with Gets.
Definition at line 385 of file SetGet.h.
Constructor & Destructor Documentation
SetGet2()
template<class A1 , class A2 > SetGet2< A1, A2 >::SetGet2 () inline
Definition at line 388 of file SetGet.h.
    {
        ;
    }
Member Function Documentation
innerStrSet()
template<class A1 , class A2 > static bool SetGet2< A1, A2 >::innerStrSet (const ObjId & dest, const string & field, const string & val) inline static
Blocking call using string conversion.
Definition at line 473 of file SetGet.h.
    {
        A1 arg1;
        A2 arg2;
        string::size_type pos = val.find_first_of( "," );
        Conv< A1 >::str2val( arg1, val.substr( 0, pos ) );
        Conv< A2 >::str2val( arg2, val.substr( pos + 1 ) );
        return set( dest, field, arg1, arg2 );
    }
References SetGet2< A1, A2 >::set().
set()
template<class A1 , class A2 > static bool SetGet2< A1, A2 >::set (const ObjId & dest, const string & field, A1 arg1, A2 arg2) inline static
Blocking, typed 'Set' call
Definition at line 396 of file SetGet.h.
    {
        FuncId fid;
        ObjId tgt( dest );
        const OpFunc* func = checkSet( field, tgt, fid );
        const OpFunc2Base< A1, A2 >* op =
            dynamic_cast< const OpFunc2Base< A1, A2 >* >( func );
        if ( op )
        {
            if ( tgt.isOffNode() )
            {
                const OpFunc* op2 = op->makeHopFunc(
                                        HopIndex( op->opIndex(), MooseSetHop ) );
                const OpFunc2Base< A1, A2 >* hop =
                    dynamic_cast< const OpFunc2Base< A1, A2 >* >( op2 );
                hop->op( tgt.eref(), arg1, arg2 );
                delete op2;
                if ( tgt.isGlobal() )
                    op->op( tgt.eref(), arg1, arg2 );
                return true;
            }
            else
            {
                op->op( tgt.eref(), arg1, arg2 );
                return true;
            }
        }
        return false;
    }
References SetGet::checkSet(), ObjId::eref(), ObjId::isGlobal(), ObjId::isOffNode(), MooseSetHop, and ObjId::ObjId().
Referenced by Synapse::addMsgCallback(), addSpine(), benchmarkMsg(), ReadKkit::buildEnz(), Shell::doMove(), Shell::doStart(), ReadKkit::dumpPlots(), ReadKkit::findCompartmentsFromAnnotation(), SetGet2< A1, A2 >::innerStrSet(), makeStandardElements(), Neuron::scaleBufAndRates(), Neuron::scaleHeadDiffusion(), Neuron::scaleShaftDiffusion(), Spine::setHeadDiameter(), Spine::setHeadLength(), Spine::setHeadVolume(), Spine::setShaftDiameter(), Spine::setShaftLength(), ReadKkit::setupSlaveMsg(), testCalcJunction(), testReMesh(), testRunGsolve(), testRunKsolve(), testRunKsolveWithLSODA(), Stoich::unZombifyPools(), and Stoich::zombifyModel().
setVec()
template<class A1 , class A2 > static bool SetGet2< A1, A2 >::setVec (Id destId, const string & field, const vector< A1 > & arg1, const vector< A2 > & arg2) inline static
Assign a vector of targets, using matching vectors of arguments arg1 and arg2. Specifically, index i on the target receives arguments arg1[i], arg2[i]. Note that there is no requirement for the size of the argument vectors to be equal to the size of the target array of objects. If there are fewer arguments then the index cycles back, so as to tile the target array with as many arguments as we have.
Not yet implemented correct handling for FieldElements.
Definition at line 439 of file SetGet.h.
    {
        ObjId tgt( destId, 0 );
        FuncId fid;
        const OpFunc* func = checkSet( field, tgt, fid );
        const OpFunc2Base< A1, A2 >* op =
            dynamic_cast< const OpFunc2Base< A1, A2 >* >( func );
        if ( op )
        {
            /*
            unsigned int size = tgt.element()->numData();
            // total # of entries on element and maybe to include fields
            for ( unsigned int i = 0; i < size; ++i ) {
                Eref er( tgt.element(), i );
                op->op( er, arg1[ i % arg1.size() ],
                                arg2[ i % arg2.size() ] );
            }
            return true;
            */
            const OpFunc* op2 = op->makeHopFunc(
                                    HopIndex( op->opIndex(), MooseSetVecHop ) );
            const OpFunc2Base< A1, A2 >* hop =
                dynamic_cast< const OpFunc2Base< A1, A2 >* >( op2 );
            hop->opVec( tgt.eref(), arg1, arg2, op );
            delete op2;
            return true;
        }
        return false;
    }
References SetGet::checkSet(), ObjId::eref(), MooseSetVecHop, and ObjId::ObjId().
Referenced by test2ArgSetVec().
The documentation for this class was generated from the following file:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/basecode/SetGet.h