MOOSE - Multiscale Object Oriented Simulation Environment: OneToOneMsg Class Reference
OneToOneMsg Class Reference
#include <OneToOneMsg.h>
Public Member Functions
Msg * copy (Id origSrc, Id newSrc, Id newTgt, FuncId fid, unsigned int b, unsigned int n) const
ObjId findOtherEnd (ObjId end) const
Eref firstTgt (const Eref &src) const
Id managerId () const
OneToOneMsg (const Eref &e1, const Eref &e2, unsigned int msgIndex)
void sources (vector< vector< Eref > > &v) const
void targets (vector< vector< Eref > > &v) const
~OneToOneMsg ()
Public Member Functions inherited from Msg
Element * e1 () const
Element * e2 () const
ObjId getAdjacent (ObjId) const
vector< string > getDestFieldsOnE1 () const
vector< string > getDestFieldsOnE2 () const
Id getE1 () const
Id getE2 () const
vector< string > getSrcFieldsOnE1 () const
vector< string > getSrcFieldsOnE2 () const
bool isForward (const Element *src) const
ObjId mid () const
Msg (ObjId mid, Element *e1, Element *e2)
Constructor.
virtual ~Msg ()
Destructor.
Static Public Member Functions
static const Cinfo * initCinfo ()
Setup function for Element-style access to Msg fields.
static char * lookupMsg (unsigned int index)
Static function for Msg access.
static unsigned int numMsg ()
Msg lookup functions.
Static Public Member Functions inherited from Msg
static void clearAllMsgs ()
static void deleteMsg (ObjId mid)
static const Msg * getMsg (ObjId m)
static const Cinfo * initCinfo ()
static unsigned int initMsgManagers ()
static bool isLastTrump ()
True when MOOSE has been terminated and is being cleaned up.
static const Msg * lastMsg ()
Private Attributes
DataId i1_
DataId i2_
Static Private Attributes
static Id managerId_
static vector< OneToOneMsg * > msg_
Friends
unsigned int Msg::initMsgManagers ()
Additional Inherited Members
Protected Attributes inherited from Msg
Element * e1_
Index of this Msg on the msg_ vector.
Element * e2_
Element 1 attached to Msg.
ObjId mid_
Static Protected Attributes inherited from Msg
static bool lastTrump_ = false
Flag to indicate termination of program.
static Id msgManagerId_
Element 2 attached to Msg.
Detailed Description
Manages a projection where each entry in source array connects to the corresponding entry (with same index) in dest array. If there is a mismatch in number of entries, the overhang is ignored. If the dest array is a FieldElement, then it uses its internal DataId i2_ to fill in the DataIndex for the dest. The OneToOne matching is assumed to be between DataIndex on e1 and FieldIndex on e2.
Definition at line 22 of file OneToOneMsg.h.
Constructor & Destructor Documentation
OneToOneMsg()
OneToOneMsg::OneToOneMsg (const Eref & e1, const Eref & e2, unsigned int msgIndex)
Definition at line 17 of file OneToOneMsg.cpp.
    : Msg( ObjId( managerId_, (msgIndex != 0) ? msgIndex: msg_.size() ),
                    e1.element(), e2.element() ),
    i1_( e1.dataIndex() ),
    i2_( e2.dataIndex() )
{
    if ( msgIndex == 0 ) {
        msg_.push_back( this );
    } else {
        if ( msg_.size() <= msgIndex )
            msg_.resize( msgIndex + 1 );
        msg_[ msgIndex ] = this;
    }
}
References Eref::dataIndex(), Eref::element(), i1_, i2_, managerId_, Msg::Msg(), msg_, and ObjId::ObjId().
Referenced by copy(), Shell::innerAddMsg(), testCreateMsg(), testMsgSrcDestFields(), testSendMsg(), and testSharedMsg().
~OneToOneMsg()
OneToOneMsg::~OneToOneMsg ()
Definition at line 33 of file OneToOneMsg.cpp.
{
    assert( mid_.dataIndex < msg_.size() );
    msg_[ mid_.dataIndex ] = 0; // ensure deleted ptr isn't reused.
}
References ObjId::dataIndex, Msg::mid_, and msg_.
Member Function Documentation
copy()
Msg * OneToOneMsg::copy (Id origSrc, Id newSrc, Id newTgt, FuncId fid, unsigned int b, unsigned int n) const virtual
Make a copy of this Msg. The original msg was on origSrc. The new Msg should go from newSrc to newTgt, and have the function fid, on bindIndex b. The copy may have to be a higher-order Msg type to handle arrays if n > 1. Note that n is not the number of msgs, but the multiplier by which numData will be scaled.
Implements Msg.
Definition at line 128 of file OneToOneMsg.cpp.
{
    const Element* orig = origSrc.element();
    // This works both for 1-copy and for n-copies
    OneToOneMsg* ret = 0;
    if ( orig == e1() ) {
        ret = new OneToOneMsg( newSrc.eref(), newTgt.eref(), 0 );
        ret->e1()->addMsgAndFunc( ret->mid(), fid, b );
    } else if ( orig == e2() ) {
        ret = new OneToOneMsg( newTgt.eref(), newSrc.eref(), 0 );
        ret->e2()->addMsgAndFunc( ret->mid(), fid, b );
    } else
        assert( 0 );
    // ret->e1()->addMsgAndFunc( ret->mid(), fid, b );
    return ret;
}
References Element::addMsgAndFunc(), Msg::e1(), Msg::e2(), Id::element(), Id::eref(), Msg::mid(), and OneToOneMsg().
findOtherEnd()
ObjId OneToOneMsg::findOtherEnd (ObjId) const virtual
Find the other end of this Msg. In most cases this is a straightforward return of e1 or e2, plus perhaps a DataId. But in some complex msgs we need to figure out DataIds that match with the target. In many-to-one cases we just return the first entry. If no Element match, return ObjId(Id(), DataId::bad()) If Element e matches but not DataId, return ObjId(e.id(), DataId::bad())
Implements Msg.
Definition at line 118 of file OneToOneMsg.cpp.
{
    if ( f.element() == e1() )
        return ObjId( e2()->id(), f.dataIndex );
    else if ( f.element() == e2() )
        return ObjId( e1()->id(), f.dataIndex );
    return ObjId( 0, BADINDEX );
}
References BADINDEX, ObjId::dataIndex, Msg::e1(), Msg::e2(), ObjId::element(), Element::id(), and ObjId::ObjId().
firstTgt()
Eref OneToOneMsg::firstTgt (const Eref & src) const virtual
This is a little tricky because we might be mapping between data entries and field entries here. May wish also to apply to exec operations. At this point, the effect of trying to go between regular data entries and field entries is undefined.
Implements Msg.
Definition at line 46 of file OneToOneMsg.cpp.
{
    if ( src.element() == e1_ ) {
        if ( e2_->hasFields() )
            return Eref( e2_, i2_, src.dataIndex() );
        else
            return Eref( e2_, src.dataIndex(), 0 );
    } else if ( src.element() == e2_ ) {
        return Eref( e1_, src.dataIndex() );
    }
    return Eref( 0, 0 );
}
References Eref::dataIndex(), Msg::e1_, Msg::e2_, Eref::element(), Eref::Eref(), Element::hasFields(), and i2_.
initCinfo()
const Cinfo * OneToOneMsg::initCinfo () static
Setup function for Element-style access to Msg fields.
Definition at line 163 of file OneToOneMsg.cpp.
{
    // Field definitions. Nothing here.
    static Dinfo< short > dinfo;
    static Cinfo msgCinfo (
        "OneToOneMsg",  // name
        Msg::initCinfo(),               // base class
        0,                              // Finfo array
        0,                              // Num Fields
        &dinfo
    );
    return &msgCinfo;
}
References Cinfo::Cinfo(), and Msg::initCinfo().
Referenced by Msg::initMsgManagers().
lookupMsg()
char * OneToOneMsg::lookupMsg (unsigned int index) static
Static function for Msg access.
Definition at line 153 of file OneToOneMsg.cpp.
{
    assert( index < msg_.size() );
    return reinterpret_cast< char* >( msg_[index] );
}
References msg_.
Referenced by Msg::clearAllMsgs(), and Msg::initMsgManagers().
managerId()
Id OneToOneMsg::managerId () const
Definition at line 113 of file OneToOneMsg.cpp.
{
    return OneToOneMsg::managerId_;
}
References managerId_.
numMsg()
unsigned int OneToOneMsg::numMsg () static
Msg lookup functions.
Static function for Msg access.
Definition at line 147 of file OneToOneMsg.cpp.
{
    return msg_.size();
}
References msg_.
Referenced by Msg::clearAllMsgs(), and Msg::initMsgManagers().
sources()
void OneToOneMsg::sources (vector< vector< Eref > > & v) const virtual
Return all the sources of e2 from e1, that is, all the msgs coming into specified entries on e2 from e1.
ALLDATA used when the sources include all data entries on a source. Indexing is v[dataId in range e2.numData][src list]
Implements Msg.
Definition at line 60 of file OneToOneMsg.cpp.
{
    v.resize( 0 );
    unsigned int n = e1_->numData();
    if ( e2_->hasFields() ) {
        if ( Eref( e2_, i2_ ).isDataHere() ) {
            assert( i2_ > e2_->localDataStart() );
            unsigned int nf = e2_->numField( i2_ - e2_->localDataStart() );
            if ( n > nf )
                n = nf;
            v.resize( n );
            for ( unsigned int i = 0; i < n; ++i ) {
                v[i].resize( 1, Eref( e1_, i ) );
            }
        }
    } else {
        if ( n > e2_->numData() )
            n = e2_->numData();
        v.resize( e2_->numData() );
        for ( unsigned int i = 0; i < n; ++i ) {
            v[i].resize( 1, Eref( e1_, i ) );
        }
    }
}
References Msg::e1_, Msg::e2_, Eref::Eref(), Element::hasFields(), i2_, Eref::isDataHere(), Element::localDataStart(), Element::numData(), and Element::numField().
targets()
void OneToOneMsg::targets (vector< vector< Eref > > & v) const virtual
Return all the targets of e1 on e2, that is, all the msgs going from specified entries on e1 to e2. ALLDATA used when the targets include all data entries on a target. Indexing is v[dataId in range e1.numData][tgt list]
Implements Msg.
Definition at line 85 of file OneToOneMsg.cpp.
{
    unsigned int n = e1_->numData();
    v.resize( e1_->numData() );
    if ( e2_->hasFields() ) {
        if ( Eref( e2_, i2_ ).isDataHere() ) {
            assert( i2_ > e2_->localDataStart() );
            unsigned int nf = e2_->numField( i2_ - e2_->localDataStart() );
            if ( n > nf )
                n = nf;
            for ( unsigned int i = 0; i < n; ++i )
                v[i].resize( 1, Eref( e2_, i2_, i ) );
        } else { // Don't know target node # of entries, so send all.
            unsigned int start = e1_->localDataStart();
            unsigned int end = start + e1_->numLocalData();
            for ( unsigned int i = start; i < end; ++i ) {
                v[i].resize( 1, Eref( e2_, i2_, i ) );
            }
        }
    } else {
        if ( n > e2_->numData() )
            n = e2_->numData();
        for ( unsigned int i = 0; i < n; ++i ) {
            v[i].resize( 1, Eref( e2_, i ) );
        }
    }
}
References Msg::e1_, Msg::e2_, Eref::Eref(), Element::hasFields(), i2_, Eref::isDataHere(), Element::localDataStart(), Element::numData(), Element::numField(), and Element::numLocalData().
Friends And Related Symbol Documentation
Msg::initMsgManagers
unsigned int Msg::initMsgManagers () friend
Member Data Documentation
i1_
DataId OneToOneMsg::i1_ private
Definition at line 48 of file OneToOneMsg.h.
Referenced by OneToOneMsg().
i2_
DataId OneToOneMsg::i2_ private
Definition at line 49 of file OneToOneMsg.h.
Referenced by firstTgt(), OneToOneMsg(), sources(), and targets().
managerId_
Id OneToOneMsg::managerId_ static private
Definition at line 50 of file OneToOneMsg.h.
Referenced by Msg::initMsgManagers(), managerId(), and OneToOneMsg().
msg_
vector< OneToOneMsg * > OneToOneMsg::msg_ static private
Definition at line 51 of file OneToOneMsg.h.
Referenced by lookupMsg(), numMsg(), OneToOneMsg(), and ~OneToOneMsg().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/msg/OneToOneMsg.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/msg/OneToOneMsg.cpp