MOOSE - Multiscale Object Oriented Simulation Environment: SetGet4< A1, A2, A3, A4 > Class Template Reference
SetGet4< A1, A2, A3, A4 > Class Template Reference
#include <SetGet.h>
Public Member Functions
SetGet4 ()
Public Member Functions inherited from SetGet
virtual bool checkOpClass (const OpFunc *op) const =0
SetGet ()
virtual ~SetGet ()
Static Public Member Functions
static bool innerStrSet (const ObjId &dest, const string &field, const string &val)
static bool set (const ObjId &dest, const string &field, A1 arg1, A2 arg2, A3 arg3, A4 arg4)
Static Public Member Functions inherited from SetGet
static const OpFunc * checkSet (const string &field, ObjId &tgt, FuncId &fid)
static const vector< double * > * dispatchGet (const ObjId &tgt, FuncId tgtFid, const double *arg, unsigned int size)
Sends out request for data, and awaits its return.
static bool strGet (const ObjId &tgt, const string &field, string &ret)
static bool strSet (const ObjId &dest, const string &field, const string &val)
Detailed Description
template<class A1, class A2, class A3, class A4>
class SetGet4< A1, A2, A3, A4 >
SetGet4 handles 4-argument Sets. It does not deal with Gets.
Definition at line 728 of file SetGet.h.
Constructor & Destructor Documentation
SetGet4()
template<class A1 , class A2 , class A3 , class A4 > SetGet4< A1, A2, A3, A4 >::SetGet4 () inline
Definition at line 731 of file SetGet.h.
    {
        ;
    }
Member Function Documentation
innerStrSet()
template<class A1 , class A2 , class A3 , class A4 > static bool SetGet4< A1, A2, A3, A4 >::innerStrSet (const ObjId & dest, const string & field, const string & val) inline static
Blocking call using string conversion. As yet we don't have 2 arg conversion from a single string. So this is a dummy
Definition at line 775 of file SetGet.h.
    {
        A1 arg1;
        A2 arg2;
        A3 arg3;
        A4 arg4;
        string::size_type pos = val.find_first_of( "," );
        Conv< A1 >::str2val( arg1, val.substr( 0, pos ) );
        string temp = val.substr( pos + 1 );
        pos = temp.find_first_of( "," );
        Conv< A2 >::str2val( arg2, temp.substr( 0, pos ) );
        temp = temp.substr( pos + 1 );
        pos = temp.find_first_of( "," );
        Conv< A3 >::str2val( arg3, temp.substr( 0, pos ) );
        Conv< A4 >::str2val( arg4, temp.substr( pos + 1 ) );
        return set( dest, field, arg1, arg2, arg3, arg4 );
    }
References SetGet4< A1, A2, A3, A4 >::set().
set()
template<class A1 , class A2 , class A3 , class A4 > static bool SetGet4< A1, A2, A3, A4 >::set (const ObjId & dest, const string & field, A1 arg1, A2 arg2, A3 arg3, A4 arg4) inline static
Blocking, typed 'Set' call
Definition at line 739 of file SetGet.h.
    {
        FuncId fid;
        ObjId tgt( dest );
        const OpFunc* func = checkSet( field, tgt, fid );
        const OpFunc4Base< A1, A2, A3, A4 >* op =
            dynamic_cast< const OpFunc4Base< A1, A2, A3, A4 >* >( func);
        if ( op )
        {
            if ( tgt.isOffNode() )
            {
                const OpFunc* op2 = op->makeHopFunc(
                                        HopIndex( op->opIndex(), MooseSetHop ) );
                const OpFunc4Base< A1, A2, A3, A4 >* hop =
                    dynamic_cast< const OpFunc4Base< A1, A2, A3, A4 >* >( op2 );
                hop->op( tgt.eref(), arg1, arg2, arg3, arg4 );
                delete op2;
                if ( tgt.isGlobal() )
                    op->op( tgt.eref(), arg1, arg2, arg3, arg4 );
                return true;
            }
            else
            {
                op->op( tgt.eref(), arg1, arg2, arg3, arg4 );
                return true;
            }
        }
        return 0;
    }
References SetGet::checkSet(), ObjId::eref(), ObjId::isGlobal(), ObjId::isOffNode(), MooseSetHop, and ObjId::ObjId().
Referenced by Shell::doUseClock(), and SetGet4< A1, A2, A3, A4 >::innerStrSet().
The documentation for this class was generated from the following file:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/basecode/SetGet.h