MOOSE - Multiscale Object Oriented Simulation Environment: CubeMesh Class Reference
CubeMesh Class Reference
#include <CubeMesh.h>
Public Member Functions
void addStoich (Id stoich)
void assignVoxels (vector< pair< unsigned int, unsigned int > > &intersect, double xmin, double xmax, double ymin, double ymax, double zmin, double zmax) const
void buildMesh (Id geom, double x, double y, double z)
void buildStencil ()
int compareMeshSpacing (const CubeMesh *other) const
Return 0 if spacing same, -1 if self smaller, +1 if self bigger.
CubeMesh ()
void defineIntersection (const CubeMesh *other, double &xmin, double &xmax, double &ymin, double &ymax, double &zmin, double &zmax) const
Defines a cuboid volume of intersection between self and other.
void deriveM2sFromS2m ()
void deriveS2mFromM2s ()
double extendedMeshEntryVolume (unsigned int fid) const
Virtual function to return volume of mesh Entry, including.
void fillSpaceToMeshLookup ()
void fillThreeDimSurface ()
void fillTwoDimSurface ()
Fills surface_ vector with spatial meshIndices for a rectangle.
bool getAlwaysDiffuse () const
vector< double > getCoordinates (unsigned int fid) const
Virtual function to return coords of mesh Entry.
vector< double > getCoords (const Eref &e) const
vector< double > getDiffusionArea (unsigned int fid) const
Virtual function to return diffusion X-section area.
vector< double > getDiffusionScaling (unsigned int fid) const
Virtual function to return scale factor for diffusion. 1 here.
double getDx () const
double getDy () const
double getDz () const
bool getIsToroid () const
unsigned int getMeshDimensions (unsigned int fid) const
Virtual function to return dimensions of specified entry.
double getMeshEntryVolume (unsigned int fid) const
Virtual function to return volume of mesh Entry.
vector< unsigned int > getMeshToSpace () const
unsigned int getMeshType (unsigned int fid) const
Virtual function to return MeshType of specified entry.
unsigned int getNx () const
unsigned int getNy () const
unsigned int getNz () const
vector< unsigned int > getParentVoxel () const
Inherited virtual, do nothing for now.
bool getPreserveNumEntries () const
vector< unsigned int > getSpaceToMesh () const
vector< unsigned int > getSurface () const
const vector< double > & getVoxelArea () const
const vector< double > & getVoxelLength () const
double getX0 () const
double getX1 () const
double getY0 () const
double getY1 () const
double getZ0 () const
double getZ1 () const
void indexToSpace (unsigned int index, double &x, double &y, double &z) const
Converts the integer meshIndex to spatial coords.
void innerBuildDefaultMesh (const Eref &e, double volume, unsigned int numEntries)
Virtual func to make a mesh with specified Volume and numEntries.
unsigned int innerGetDimensions () const
unsigned int innerGetNumEntries () const
void innerHandleNodeInfo (const Eref &e, unsigned int numNodes, unsigned int numThreads)
void innerHandleRequestMeshStats (const Eref &e, const SrcFinfo2< unsigned int, vector< double > > *meshStatsFinfo)
More inherited virtual funcs: request comes in for mesh stats.
void innerSetCoords (const vector< double > &v)
void innerSetNumEntries (unsigned int n)
Inherited virtual func.
bool isInsideCuboid (double x, double y, double z) const
bool isInsideSpheroid (double x, double y, double z) const
void matchAllEntries (const CubeMesh *other, vector< VoxelJunction > &ret) const
void matchCubeMeshEntries (const CubeMesh *other, vector< VoxelJunction > &ret) const
void matchCylMeshEntries (const ChemCompt *other, vector< VoxelJunction > &ret) const
void matchMeshEntries (const ChemCompt *other, vector< VoxelJunction > &ret) const
double nearest (double x, double y, double z, unsigned int &index) const
unsigned int neighbor (unsigned int spaceIndex, int dx, int dy, int dz) const
unsigned int numDims () const
Utility function for returning # of dimensions in mesh.
void setAlwaysDiffuse (bool v)
void setCoords (const Eref &e, vector< double > v)
void setDiffScale (const CubeMesh *other, vector< VoxelJunction > &ret) const
Assigns diffusion scaling info for the voxel junctions.
void setDx (double v)
void setDy (double v)
void setDz (double v)
void setIsToroid (bool v)
void setJunctionVol (const CubeMesh *other, vector< VoxelJunction > &ret) const
Assigns volume info for the voxel junctions.
void setMeshToSpace (vector< unsigned int > v)
void setNx (unsigned int v)
void setNy (unsigned int v)
void setNz (unsigned int v)
void setPreserveNumEntries (bool v)
void setSpaceToMesh (vector< unsigned int > v)
void setSurface (vector< unsigned int > v)
void setX0 (double v)
void setX1 (double v)
void setY0 (double v)
void setY1 (double v)
void setZ0 (double v)
void setZ1 (double v)
unsigned int spaceToIndex (double x, double y, double z) const
Converts the 3-D coords to an index. EMPTY if out of range.
const vector< unsigned int > & surface () const
Utility and test function to read surface.
void transmitChange (const Eref &e, double oldvol)
void updateCoords ()
void updateM2s ()
void updateS2m ()
double vGetEntireVolume () const
Virtual func to get volume of entire compartment.
const vector< double > & vGetVoxelMidpoint () const
Virtual func so that derived classes can return voxel midpoint.
const vector< double > & vGetVoxelVolume () const
Virtual func so that derived classes can pass voxel volume back.
bool vSetVolumeNotRates (double volume)
Virtual func, assigns volume, usually to single voxel.
~CubeMesh ()
Public Member Functions inherited from MeshCompt
void addRow (unsigned int index, const vector< double > &entry, const vector< unsigned int > &colIndex)
void clearExtendedMeshEntryVolume ()
Inherited virtual function to clear the vector of MeshEntryVolume.
double extendedMeshEntryVolume (unsigned int fid) const
Virtual function to return volume of mesh Entry, including.
void extendStencil (const ChemCompt *other, const vector< VoxelJunction > &vj)
Add boundary voxels to stencil for cross-solver junctions.
vector< unsigned int > getNeighbors (unsigned int fid) const
Looks up stencil to return vector of indices of coupled voxels.
const SparseMatrix< double > & getStencil () const
Returns entire sparse matrix of mesh. Used by diffusion solver.
unsigned int getStencilRow (unsigned int meshIndex, const double **entry, const unsigned int **colIndex) const
vector< double > innerGetStencilRate (unsigned int row) const
void innerResetStencil ()
virtual func implemented here.
MeshCompt ()
void setStencilSize (unsigned int numRows, unsigned int numCols)
~MeshCompt ()
Public Member Functions inherited from ChemCompt
void buildDefaultMesh (const Eref &e, double volume, unsigned int numEntries)
void buildJunction (ChemCompt *other, vector< VoxelJunction > &ret)
ChemCompt ()
void flipRet (vector< VoxelJunction > &ret) const
Utility function for swapping first and second in VoxelJunctions.
void getChildConcs (const Eref &e, vector< double > &childConcs) const
unsigned int getDimensions () const
double getEntireVolume (const Eref &e) const
bool getIsMembraneBound () const
string getMethod () const
unsigned int getNumEntries () const
vector< double > getOneVoxelMidpoint (unsigned int vox) const
Looks up specified voxel midpoint, from vGetVoxelMidpoint.
double getOneVoxelVolume (const Eref &e, unsigned int voxel) const
vector< unsigned int > getStencilIndex (unsigned int row) const
vector< double > getStencilRate (unsigned int row) const
vector< double > getVoxelMidpoint () const
Returns vector of all voxel midpoints in compartment.
vector< double > getVoxelVolume () const
Returns vector of all voxel volumes in compartment.
void handleNodeInfo (const Eref &e, unsigned int numNodes, unsigned int numThreads)
MeshEntry * lookupEntry (unsigned int index)
void resetStencil ()
unsigned int setChildConcs (const Eref &e, const vector< double > &childConcs, unsigned int start) const
void setEntireVolume (const Eref &e, double volume)
void setIsMembraneBound (bool v)
virtual void setMeshEntryVolume (unsigned int fid, double volume)
void setMethod (string method)
void setNumEntries (unsigned int num)
void setOneVoxelVolume (const Eref &e, unsigned int voxel, double volume)
void setVolumeNotRates (double volume)
virtual ~ChemCompt ()
Static Public Member Functions
static const Cinfo * initCinfo ()
Static Public Member Functions inherited from ChemCompt
static double distance (double x, double y, double z)
static const Cinfo * initCinfo ()
static SrcFinfo1< vector< double > > * voxelVolOut ()
Static Public Attributes
static const unsigned int ABUTX = ~2
static const unsigned int ABUTY = ~3
static const unsigned int ABUTZ = ~4
static const unsigned int EMPTY = ~0
static const unsigned int MULTI = ~5
static const unsigned int SURFACE = ~1
Private Attributes
bool alwaysDiffuse_
Flag: Should dx change or nx, with vol?
double dx_
coords
double dy_
Cuboid edge.
double dz_
Cuboid edge.
bool isToroid_
vector< unsigned int > m2s_
unsigned int nx_
Cuboid edge.
unsigned int ny_
unsigned int nz_
bool preserveNumEntries_
Flag: Should the ends loop around mathemagically?
vector< unsigned int > s2m_
vector< unsigned int > surface_
double x0_
Flag: should all voxels diffuse to any tgt?
double x1_
coords
double y0_
coords
double y1_
coords
double z0_
coords
double z1_
coords
Detailed Description
The CubeMesh represents a chemically identified compartment shaped like a cuboid. This is not really an effective geometry for most neurons because it would have to be rather finely subdivided to fit a typical dendrite or soma volume, but it is general.
Definition at line 19 of file CubeMesh.h.
Constructor & Destructor Documentation
CubeMesh()
CubeMesh::CubeMesh ()
Definition at line 262 of file CubeMesh.cpp.
    :
    isToroid_( 0 ),
    preserveNumEntries_( 1 ),
    alwaysDiffuse_( false ),
    x0_( 0.0 ),
    y0_( 0.0 ),
    z0_( 0.0 ),
    x1_( 10e-6 ),
    y1_( 10e-6 ),
    z1_( 10e-6 ),
    dx_( 10e-6 ),
    dy_( 10e-6 ),
    dz_( 10e-6 ),
    nx_( 1 ),
    ny_( 1 ),
    nz_( 1 ),
    m2s_( 1, 0 ),
    s2m_( 1, 0 )
{
    updateCoords();
}
References alwaysDiffuse_, dx_, dy_, dz_, isToroid_, m2s_, nx_, ny_, nz_, preserveNumEntries_, s2m_, updateCoords(), x0_, x1_, y0_, y1_, z0_, and z1_.
~CubeMesh()
CubeMesh::~CubeMesh ()
Definition at line 285 of file CubeMesh.cpp.
{
    ;
}
Member Function Documentation
addStoich()
void CubeMesh::addStoich (Id stoich)
assignVoxels()
void CubeMesh::assignVoxels (vector< pair< unsigned int, unsigned int > > & intersect, double xmin, double xmax, double ymin, double ymax, double zmin, double zmax) const
Definition at line 1465 of file CubeMesh.cpp.
{
    unsigned int nx =static_cast<unsigned int>( 0.5 + ( xmax - xmin ) / dx_);
    unsigned int ny = static_cast<unsigned int>(0.5 + ( ymax - ymin ) / dy_);
    unsigned int nz = static_cast<unsigned int>(0.5 + ( zmax - zmin ) / dz_);
    // offset terms for nx, ny, nz from coord system for coarser grid.
    // Note that these can go negative if the intersect grid goes past
    // the coarse grid.
    int ox = static_cast<int>(round( ( xmin - x0_ ) / dx_ ));
    int oy = static_cast<int>(round( ( ymin - y0_ ) / dy_ ));
    int oz = static_cast<int>(round( ( zmin - z0_ ) / dz_ ));
    // Scan through mesh surface using coarser grid, assign cuboid voxels
    for ( vector< unsigned int >::const_iterator i = surface_.begin();
            i != surface_.end(); ++i )
    {
        unsigned int index = *i;
        double x, y, z;
        indexToSpace( index, x, y, z );
        if ( x >= xmin && x <= xmax && y >= ymin && y <= ymax &&
                z >= zmin && z <= zmax )
        {
            int ix = index % nx_ - ox;
            assert( ix >= 0 );
            unsigned int uix = ix;
            index /= nx_;
            int iy = index % ny_ - oy;
            assert( iy >= 0 );
            unsigned int uiy = iy;
            index /= ny_;
            int iz = index % nz_ - oz;
            assert( iz >= 0 );
            unsigned int uiz = iz;
            unsigned int meshIndex = s2m_[ *i ];
            setIntersectVoxel( intersect, uix, uiy, uiz, nx, ny, nz,
                               meshIndex );
        }
    }
}
References dx_, dy_, dz_, indexToSpace(), nx_, ny_, nz_, s2m_, setIntersectVoxel(), surface_, x0_, y0_, and z0_.
Referenced by matchCubeMeshEntries().
buildMesh()
void CubeMesh::buildMesh (Id geom, double x, double y, double z)
Definition at line 711 of file CubeMesh.cpp.
{
    ;
}
Referenced by initCinfo().
buildStencil()
void CubeMesh::buildStencil ()
Sets up the stencil that defines how to combine neighboring mesh elements to set up the diffusion du/dt term, using the method of lines. This is a very general function. It uses the information in the m2s_ and s2m_ vectors to work out the adjacency matrix. So we could use an arbitrary 3-D image to define the diffusive volume and boundaries using m2s_ and s2m_. We could also use geometric shapes through the fillSpaceToMeshLookup() function, which is currently a dummy and just does a cuboid.
Definition at line 1089 of file CubeMesh.cpp.
{
    static const unsigned int flag = EMPTY;
    // fillSpaceToMeshLookup();
    unsigned int num = m2s_.size();
    setStencilSize( num, num );
    for ( unsigned int i = 0; i < num; ++i )
    {
        unsigned int q = m2s_[i];
        unsigned int ix = q % nx_;
        unsigned int iy = ( q / nx_ ) % ny_;
        unsigned int iz = ( q / ( nx_ * ny_ ) ) % nz_;
        vector< double > entry;
        vector< unsigned int > colIndex;
        vector< Ecol > e;
        if ( ix > 0 && s2m_[q-1] != flag )
        {
            e.push_back( Ecol( dy_ * dz_ / dx_, s2m_[q-1] ) );
        }
        if ( ( ix < nx_ - 1 ) && s2m_[q+1] != flag )
        {
            e.push_back( Ecol( dy_ * dz_ / dx_, s2m_[q+1] ) );
        }
        if ( iy > 0 && s2m_[ q-nx_ ] != flag )
        {
            assert( q >= nx_ );
            e.push_back( Ecol( dx_ * dz_ / dy_, s2m_[q-nx_] ) );
        }
        if ( iy < ny_ - 1 && s2m_[ q+nx_ ] != flag )
        {
            assert( q+nx_ < s2m_.size() );
            e.push_back( Ecol( dx_ * dz_ / dy_, s2m_[q+nx_] ) );
        }
        if ( iz > 0 && s2m_[ q - nx_*ny_ ] != flag )
        {
            assert( q >= nx_ * ny_ );
            e.push_back( Ecol( dx_ * dy_ / dz_, s2m_[q - nx_ * ny_] ) );
        }
        if ( iz < nz_ - 1 && s2m_[ q + nx_*ny_ ] )
        {
            assert( q+nx_ < s2m_.size() );
            e.push_back( Ecol( dx_ * dy_ / dz_, s2m_[q + nx_ * ny_] ) );
        }
        sort( e.begin(), e.end() );
        for ( vector< Ecol >::iterator j = e.begin(); j != e.end(); ++j )
        {
            entry.push_back( j->e_ );
            colIndex.push_back( j->col_ );
        }
        addRow( i, entry, colIndex );
    }
    innerResetStencil();
}
References MeshCompt::addRow(), Ecol::col_, dx_, dy_, dz_, Ecol::e_, Ecol::Ecol(), EMPTY, MeshCompt::innerResetStencil(), m2s_, nx_, ny_, nz_, s2m_, and MeshCompt::setStencilSize().
Referenced by deriveM2sFromS2m(), deriveS2mFromM2s(), and updateCoords().
compareMeshSpacing()
int CubeMesh::compareMeshSpacing (const CubeMesh * other) const
Return 0 if spacing same, -1 if self smaller, +1 if self bigger.
Definition at line 1264 of file CubeMesh.cpp.
{
    if ( doubleApprox( dx_, other->dx_ ) &&
            doubleApprox( dy_, other->dy_ ) &&
            doubleApprox( dz_, other->dz_ ) )
        return 0; // equal
    if ( dx_ >= other->dx_ &&
            dy_ >= other->dy_ &&
            dz_ >= other->dz_ )
        return 1; // bigger
    if ( dx_ <= other->dx_ &&
            dy_ <= other->dy_ &&
            dz_ <= other->dz_ )
        return -1; // smaller than other.
    cout << "Warning: CubeMesh::compareMeshSpacing: inconsistent spacing\n";
    return 0;
}
References doubleApprox(), dx_, dy_, and dz_.
Referenced by matchCubeMeshEntries().
defineIntersection()
void CubeMesh::defineIntersection (const CubeMesh * other, double & xmin, double & xmax, double & ymin, double & ymax, double & zmin, double & zmax) const
Defines a cuboid volume of intersection between self and other.
Definition at line 1286 of file CubeMesh.cpp.
{
    const double meshSlop = 0.2;
    xmin = ( x0_ > other->x0_ ) ? x0_ : other->x0_;
    xmax = ( x1_ < other->x1_ ) ? x1_ : other->x1_;
    ymin = ( y0_ > other->y0_ ) ? y0_ : other->y0_;
    ymax = ( y1_ < other->y1_ ) ? y1_ : other->y1_;
    zmin = ( z0_ > other->z0_ ) ? z0_ : other->z0_;
    zmax = ( z1_ < other->z1_ ) ? z1_ : other->z1_;
    // Align to coarser mesh
    double temp = ( xmin - x0_) / dx_;
    if ( temp - floor( temp ) > meshSlop )
        xmin = floor( temp ) * dx_;
    temp = ( ymin - y0_) / dy_;
    if ( temp - floor( temp ) > meshSlop )
        ymin = floor( temp ) * dy_;
    temp = ( zmin - z0_) / dz_;
    if ( temp - floor( temp ) > meshSlop )
        zmin = floor( temp ) * dz_;
    // Provide 1 voxel padding all around.
    xmin -= dx_;
    xmax += dx_;
    ymin -= dy_;
    ymax += dy_;
    zmin -= dz_;
    zmax += dz_;
    swapIfBackward( xmin, xmax );
    swapIfBackward( ymin, ymax );
    swapIfBackward( zmin, zmax );
}
References dx_, dy_, dz_, swapIfBackward(), x0_, x1_, y0_, y1_, z0_, and z1_.
Referenced by matchCubeMeshEntries().
deriveM2sFromS2m()
void CubeMesh::deriveM2sFromS2m ()
Updates the m2s_ vector after s2m_ has been changed, and rebuilds the Stencil too. Any earlier junction information is lost.
Definition at line 1059 of file CubeMesh.cpp.
{
    m2s_.clear();
    assert( s2m_.size() == nx_ * ny_ * nz_ );
    for ( unsigned int i = 0; i < s2m_.size(); ++i )
    {
        if ( s2m_[i] != EMPTY )
        {
            m2s_.push_back( i );
            assert( m2s_.size() == s2m_[i] + 1 );
        }
    }
    buildStencil();
}
References buildStencil(), EMPTY, m2s_, nx_, ny_, nz_, and s2m_.
Referenced by setSpaceToMesh().
deriveS2mFromM2s()
void CubeMesh::deriveS2mFromM2s ()
Updates the s2m_ vector after m2s_ has been changed, and rebuilds the Stencil too. Any earlier junction information is lost.
Definition at line 1074 of file CubeMesh.cpp.
{
    s2m_.clear();
    s2m_.resize( nx_ * ny_ * nz_, EMPTY );
    for ( unsigned int i = 0; i < m2s_.size(); ++i )
    {
        s2m_[ m2s_[i] ] = i;
    }
    buildStencil();
}
References buildStencil(), EMPTY, m2s_, nx_, ny_, nz_, and s2m_.
Referenced by setMeshToSpace().
extendedMeshEntryVolume()
double CubeMesh::extendedMeshEntryVolume (unsigned int fid) const virtual
Virtual function to return volume of mesh Entry, including.
Utility function to return volume of any voxel including those diffusively coupled and aubtting the present volume.
Implements ChemCompt.
Definition at line 808 of file CubeMesh.cpp.
{
    if ( fid >= m2s_.size() )
    {
        return MeshCompt::extendedMeshEntryVolume( fid - m2s_.size() );
    }
    return dx_ * dy_ * dz_;
}
References dx_, dy_, dz_, MeshCompt::extendedMeshEntryVolume(), and m2s_.
fillSpaceToMeshLookup()
void CubeMesh::fillSpaceToMeshLookup ()
Definition at line 1025 of file CubeMesh.cpp.
{
    static const unsigned int flag = EMPTY;
    unsigned int num = 0;
    unsigned int q = 0;
    m2s_.clear();
    s2m_.resize( nx_ * ny_ * nz_, flag );
    for( unsigned int k = 0; k < nz_; ++k )
    {
        double z = k * dz_ + z0_;
        for( unsigned int j = 0; j < ny_; ++j )
        {
            double y = j * dy_ + y0_;
            for( unsigned int i = 0; i < nx_; ++i )
            {
                double x = i * dx_ + x0_;
                if ( isInsideCuboid( x, y, z ) )
                {
                    s2m_[q] = num;
                    m2s_.push_back( q );
                    ++num;
                }
                else
                {
                    s2m_[q] = flag;
                }
                ++q;
            }
        }
    }
    assert( m2s_.size() == num );
}
References dx_, dy_, dz_, EMPTY, isInsideCuboid(), m2s_, nx_, ny_, nz_, s2m_, x0_, y0_, and z0_.
fillThreeDimSurface()
void CubeMesh::fillThreeDimSurface ()
Fills surface_ vector with spatial meshIndices for a cuboid, that is, puts the surfaces of the cuboid in the vector.
Definition at line 347 of file CubeMesh.cpp.
{
    unsigned int size = nx_ * ny_ * nz_;
    // z == 0 plane
    for ( unsigned int j = 0; j < ny_; ++j )
        for ( unsigned int k = 0; k < nx_; ++k )
            surface_.push_back( j * nx_ + k );
    // z == nz_-1 plane
    unsigned int offset = size - nx_ * ny_;
    for ( unsigned int j = 0; j < ny_; ++j )
        for ( unsigned int k = 0; k < nx_; ++k )
            surface_.push_back( offset + j * nx_ + k );
    // y == 0 plane
    for ( unsigned int i = 0; i < nz_; ++i )
        for ( unsigned int k = 0; k < nx_; ++k )
            surface_.push_back( i * nx_ * ny_ + k );
    // y == ny_-1 plane
    offset = nx_ * ( ny_ - 1 );
    for ( unsigned int i = 0; i < nz_; ++i )
        for ( unsigned int k = 0; k < nx_; ++k )
            surface_.push_back( offset + i * nx_ * ny_ + k );
    // x == 0 plane
    for ( unsigned int i = 0; i < nz_; ++i )
        for ( unsigned int j = 0; j < ny_; ++j )
            surface_.push_back( ( i * ny_ + j ) * nx_ );
    // x == nx_-1 plane
    offset = nx_ - 1;
    for ( unsigned int i = 0; i < nz_; ++i )
        for ( unsigned int j = 0; j < ny_; ++j )
            surface_.push_back( offset + ( i * ny_ + j ) * nx_ );
    sort( surface_.begin(), surface_.end() );
    surface_.erase( unique( surface_.begin(), surface_.end() ),
                    surface_.end() );
}
References nx_, ny_, nz_, and surface_.
Referenced by updateCoords().
fillTwoDimSurface()
void CubeMesh::fillTwoDimSurface ()
Fills surface_ vector with spatial meshIndices for a rectangle.
Definition at line 305 of file CubeMesh.cpp.
{
    unsigned int size = nx_ * ny_ * nz_;
    if ( nx_ == 1 )
    {
        for ( unsigned int j = 0; j < ny_; ++j )
            surface_.push_back( j  );
        for ( unsigned int j = size - ny_; j < size; ++j )
            surface_.push_back( j  );
        for ( unsigned int i = 1; i < nz_ - 1; ++i )
            surface_.push_back( i * ny_  );
        for ( unsigned int i = 1; i < nz_ - 1; ++i )
            surface_.push_back( ny_ - 1 + i * ny_  );
    }
    else if ( ny_ == 1 )
    {
        for ( unsigned int k = 0; k < nx_; ++k )
            surface_.push_back( k  );
        for ( unsigned int k = size - nx_; k < size; ++k )
            surface_.push_back( k  );
        for ( unsigned int i = 1; i < nz_ - 1; ++i )
            surface_.push_back( i * nx_  );
        for ( unsigned int i = 1; i < nz_ - 1; ++i )
            surface_.push_back( nx_ - 1 + i * nx_  );
    }
    else if ( nz_ == 1 )
    {
        for ( unsigned int k = 0; k < nx_; ++k )
            surface_.push_back( k  );
        for ( unsigned int k = size - nx_; k < size; ++k )
            surface_.push_back( k  );
        for ( unsigned int j = 1; j < ny_ - 1; ++j )
            surface_.push_back( j * nx_  );
        for ( unsigned int j = 1; j < ny_ - 1; ++j )
            surface_.push_back( j * nx_ + nx_ - 1  );
    }
    // Ah, C++ STL. Look on my works, ye mighty, and despair.
    sort( surface_.begin(), surface_.end() );
    surface_.erase( unique( surface_.begin(), surface_.end() ),
                    surface_.end() );
}
References nx_, ny_, nz_, and surface_.
getAlwaysDiffuse()
bool CubeMesh::getAlwaysDiffuse () const
Definition at line 607 of file CubeMesh.cpp.
{
    // alwaysDiffuse is normally false.
    return alwaysDiffuse_;
}
References alwaysDiffuse_.
Referenced by initCinfo().
getCoordinates()
vector< double > CubeMesh::getCoordinates (unsigned int fid) const virtual
Virtual function to return coords of mesh Entry.
Virtual function to return coords of mesh Entry. For Cuboid mesh, coords are x1y1z1 x2y2z2
Implements ChemCompt.
Definition at line 819 of file CubeMesh.cpp.
{
    assert( fid < m2s_.size() );
    unsigned int spaceIndex = m2s_[fid];
    unsigned int ix = spaceIndex % nx_;
    unsigned int iy = (spaceIndex / nx_) % ny_;
    unsigned int iz = (spaceIndex / ( nx_ * ny_ )) % nz_;
    vector< double > ret( 6 );
    ret[0] = x0_ + ix * dx_;
    ret[1] = y0_ + iy * dy_;
    ret[2] = z0_ + iz * dz_;
    ret[3] = x0_ + ix * dx_ + dx_;
    ret[4] = y0_ + iy * dy_ + dx_;
    ret[5] = z0_ + iz * dz_ + dx_;
    return ret;
}
References dx_, dy_, dz_, m2s_, nx_, ny_, nz_, x0_, y0_, and z0_.
getCoords()
vector< double > CubeMesh::getCoords (const Eref & e) const
Definition at line 650 of file CubeMesh.cpp.
{
    vector< double > ret( 9 );
    ret[0] = x0_;
    ret[1] = y0_;
    ret[2] = z0_;
    ret[3] = x1_;
    ret[4] = y1_;
    ret[5] = z1_;
    ret[6] = dx_;
    ret[7] = dy_;
    ret[8] = dz_;
    return ret;
}
References dx_, dy_, dz_, x0_, x1_, y0_, y1_, z0_, and z1_.
Referenced by initCinfo(), and testCubeMesh().
getDiffusionArea()
vector< double > CubeMesh::getDiffusionArea (unsigned int fid) const virtual
Virtual function to return diffusion X-section area.
Virtual function to return diffusion X-section area for each neighbor.
Implements ChemCompt.
Definition at line 864 of file CubeMesh.cpp.
{
    assert( fid < m2s_.size() );
    vector< double > ret;
    unsigned int spaceIndex = m2s_[fid];
    unsigned int nIndex = neighbor( spaceIndex, 0, 0, 1 );
    if ( nIndex != EMPTY )
        ret.push_back( dx_ * dy_ );
    nIndex = neighbor( spaceIndex, 0, 0, -1 );
    if ( nIndex != EMPTY )
        ret.push_back( dx_ * dy_ );
    nIndex = neighbor( spaceIndex, 0, 1, 0 );
    if ( nIndex != EMPTY )
        ret.push_back( dz_ * dx_ );
    nIndex = neighbor( spaceIndex, 0, -1, 0 );
    if ( nIndex != EMPTY )
        ret.push_back( dz_ * dx_ );
    nIndex = neighbor( spaceIndex, 1, 0, 0 );
    if ( nIndex != EMPTY )
        ret.push_back( dy_ * dz_ );
    nIndex = neighbor( spaceIndex, -1, 0, 0 );
    if ( nIndex != EMPTY )
        ret.push_back( dy_ * dz_ );
    return ret;
}
References dx_, dy_, dz_, EMPTY, m2s_, and neighbor().
getDiffusionScaling()
vector< double > CubeMesh::getDiffusionScaling (unsigned int fid) const virtual
Virtual function to return scale factor for diffusion. 1 here.
Implements ChemCompt.
Definition at line 899 of file CubeMesh.cpp.
{
    return vector< double >( 6, 1.0 );
}
getDx()
double CubeMesh::getDx () const
Definition at line 518 of file CubeMesh.cpp.
{
    return dx_;
}
References dx_.
Referenced by initCinfo(), CylBase::matchCubeMeshEntries(), CylMesh::matchCubeMeshEntries(), and testCubeMesh().
getDy()
double CubeMesh::getDy () const
Definition at line 530 of file CubeMesh.cpp.
{
    return dy_;
}
References dy_.
Referenced by initCinfo(), and testCubeMesh().
getDz()
double CubeMesh::getDz () const
Definition at line 542 of file CubeMesh.cpp.
{
    return dz_;
}
References dz_.
Referenced by initCinfo(), and testCubeMesh().
getIsToroid()
bool CubeMesh::getIsToroid () const
Definition at line 587 of file CubeMesh.cpp.
{
    return isToroid_;
}
References isToroid_.
Referenced by initCinfo().
getMeshDimensions()
unsigned int CubeMesh::getMeshDimensions (unsigned int fid) const virtual
Virtual function to return dimensions of specified entry.
Implements ChemCompt.
Definition at line 795 of file CubeMesh.cpp.
{
    return 3;
}
Referenced by testCubeMesh(), and testCubeMeshExtendStencil().
getMeshEntryVolume()
double CubeMesh::getMeshEntryVolume (unsigned int fid) const virtual
Virtual function to return volume of mesh Entry.
Implements ChemCompt.
Definition at line 801 of file CubeMesh.cpp.
{
    return dx_ * dy_ * dz_;
}
References dx_, dy_, and dz_.
getMeshToSpace()
vector< unsigned int > CubeMesh::getMeshToSpace () const
Definition at line 675 of file CubeMesh.cpp.
{
    return m2s_;
}
References m2s_.
Referenced by initCinfo(), and testCubeMeshJunctionTwoDimSurface().
getMeshType()
unsigned int CubeMesh::getMeshType (unsigned int fid) const virtual
Virtual function to return MeshType of specified entry.
Implements ChemCompt.
Definition at line 789 of file CubeMesh.cpp.
{
    return CUBOID;
}
References CUBOID.
Referenced by testCubeMesh(), and testCubeMeshExtendStencil().
getNx()
unsigned int CubeMesh::getNx () const
Definition at line 553 of file CubeMesh.cpp.
{
    return nx_;
}
References nx_.
Referenced by initCinfo(), and testCubeMesh().
getNy()
unsigned int CubeMesh::getNy () const
Definition at line 565 of file CubeMesh.cpp.
{
    return ny_;
}
References ny_.
Referenced by initCinfo(), and testCubeMesh().
getNz()
unsigned int CubeMesh::getNz () const
Definition at line 576 of file CubeMesh.cpp.
{
    return nz_;
}
References nz_.
Referenced by initCinfo(), and testCubeMesh().
getParentVoxel()
vector< unsigned int > CubeMesh::getParentVoxel () const virtual
Inherited virtual, do nothing for now.
Implements MeshCompt.
Definition at line 923 of file CubeMesh.cpp.
{
    unsigned int numEntries = innerGetNumEntries();
    vector< unsigned int > ret( numEntries );
    if ( numEntries > 0 )
        ret[0] = static_cast< unsigned int >( -1 );
    for (unsigned int i = 1; i < numEntries; ++i )
        ret[i] = i-1;
    return ret;
}
References innerGetNumEntries().
getPreserveNumEntries()
bool CubeMesh::getPreserveNumEntries () const
Definition at line 597 of file CubeMesh.cpp.
{
    return preserveNumEntries_;
}
References preserveNumEntries_.
Referenced by initCinfo().
getSpaceToMesh()
vector< unsigned int > CubeMesh::getSpaceToMesh () const
Definition at line 686 of file CubeMesh.cpp.
{
    return s2m_;
}
References s2m_.
Referenced by initCinfo(), and testCubeMeshJunctionTwoDimSurface().
getSurface()
vector< unsigned int > CubeMesh::getSurface () const
Definition at line 696 of file CubeMesh.cpp.
{
    return surface_;
}
References surface_.
Referenced by initCinfo().
getVoxelArea()
const vector< double > & CubeMesh::getVoxelArea () const virtual
Implements MeshCompt.
Definition at line 962 of file CubeMesh.cpp.
{
    static vector< double > area;
    if ( nx_ * ny_ == 1 )
        area.resize( nz_, dx_ * dy_ );
    else if ( nx_ * nz_ == 1 )
        area.resize( ny_, dx_ * dz_ );
    else if ( ny_ * nz_ == 1 )
        area.resize( nx_, dy_ * dz_ );
    else
        area.resize( nx_, dy_ * dz_ ); // Just put in a number.
    assert( area.size() == nx_ * ny_ * nz_ );
    return area;
}
References dx_, dy_, dz_, nx_, ny_, and nz_.
getVoxelLength()
const vector< double > & CubeMesh::getVoxelLength () const virtual
Implements MeshCompt.
Definition at line 977 of file CubeMesh.cpp.
{
    static vector< double > length;
    if ( dx_ > dy_ && dx_ > dz_ )
        length.assign( innerGetNumEntries(), dx_ );
    else if ( dy_ > dz_ )
        length.assign( innerGetNumEntries(), dy_ );
    else
        length.assign( innerGetNumEntries(), dz_ );
    return length;
}
References dx_, dy_, dz_, and innerGetNumEntries().
getX0()
double CubeMesh::getX0 () const
Definition at line 452 of file CubeMesh.cpp.
{
    return x0_;
}
References x0_.
Referenced by initCinfo(), and testCubeMesh().
getX1()
double CubeMesh::getX1 () const
Definition at line 485 of file CubeMesh.cpp.
{
    return x1_;
}
References x1_.
Referenced by initCinfo(), and testCubeMesh().
getY0()
double CubeMesh::getY0 () const
Definition at line 463 of file CubeMesh.cpp.
{
    return y0_;
}
References y0_.
Referenced by initCinfo(), and testCubeMesh().
getY1()
double CubeMesh::getY1 () const
Definition at line 496 of file CubeMesh.cpp.
{
    return y1_;
}
References y1_.
Referenced by initCinfo(), and testCubeMesh().
getZ0()
double CubeMesh::getZ0 () const
Definition at line 474 of file CubeMesh.cpp.
{
    return z0_;
}
References z0_.
Referenced by initCinfo(), and testCubeMesh().
getZ1()
double CubeMesh::getZ1 () const
Definition at line 507 of file CubeMesh.cpp.
{
    return z1_;
}
References z1_.
Referenced by initCinfo(), and testCubeMesh().
indexToSpace()
void CubeMesh::indexToSpace (unsigned int index, double & x, double & y, double & z) const virtual
Converts the integer meshIndex to spatial coords.
Implements ChemCompt.
Definition at line 1192 of file CubeMesh.cpp.
{
    assert ( index < nx_ * ny_ * nz_ );
    // index = m2s_[index];
    unsigned int ix = index % nx_;
    index /= nx_;
    unsigned int iy = index % ny_;
    index /= ny_;
    unsigned int iz = index % nz_;
    x = x0_ + ix * dx_ + dx_ * 0.5;
    y = y0_ + iy * dy_ + dy_ * 0.5;
    z = z0_ + iz * dz_ + dz_ * 0.5;
}
References dx_, dy_, dz_, nx_, ny_, nz_, x0_, y0_, and z0_.
Referenced by assignVoxels(), matchCubeMeshEntries(), and nearest().
initCinfo()
const Cinfo * CubeMesh::initCinfo () static
Definition at line 31 of file CubeMesh.cpp.
{
    // Field Definitions
    static ValueFinfo< CubeMesh, double > x0(
        "x0",
        "X coord of one end",
        &CubeMesh::setX0,
        &CubeMesh::getX0
    );
    static ValueFinfo< CubeMesh, double > y0(
        "y0",
        "Y coord of one end",
        &CubeMesh::setY0,
        &CubeMesh::getY0
    );
    static ValueFinfo< CubeMesh, double > z0(
        "z0",
        "Z coord of one end",
        &CubeMesh::setZ0,
        &CubeMesh::getZ0
    );
    static ValueFinfo< CubeMesh, double > x1(
        "x1",
        "X coord of other end",
        &CubeMesh::setX1,
        &CubeMesh::getX1
    );
    static ValueFinfo< CubeMesh, double > y1(
        "y1",
        "Y coord of other end",
        &CubeMesh::setY1,
        &CubeMesh::getY1
    );
    static ValueFinfo< CubeMesh, double > z1(
        "z1",
        "Z coord of other end",
        &CubeMesh::setZ1,
        &CubeMesh::getZ1
    );
    static ValueFinfo< CubeMesh, double > dx(
        "dx",
        "X size for mesh",
        &CubeMesh::setDx,
        &CubeMesh::getDx
    );
    static ValueFinfo< CubeMesh, double > dy(
        "dy",
        "Y size for mesh",
        &CubeMesh::setDy,
        &CubeMesh::getDy
    );
    static ValueFinfo< CubeMesh, double > dz(
        "dz",
        "Z size for mesh",
        &CubeMesh::setDz,
        &CubeMesh::getDz
    );
    static ValueFinfo< CubeMesh, unsigned int > nx(
        "nx",
        "Number of subdivisions in mesh in X",
        &CubeMesh::setNx,
        &CubeMesh::getNx
    );
    static ValueFinfo< CubeMesh, unsigned int > ny(
        "ny",
        "Number of subdivisions in mesh in Y",
        &CubeMesh::setNy,
        &CubeMesh::getNy
    );
    static ValueFinfo< CubeMesh, unsigned int > nz(
        "nz",
        "Number of subdivisions in mesh in Z",
        &CubeMesh::setNz,
        &CubeMesh::getNz
    );
    static ValueFinfo< CubeMesh, bool > isToroid(
        "isToroid",
        "Flag. True when the mesh should be toroidal, that is,"
        "when going beyond the right face brings us around to the"
        "left-most mesh entry, and so on. If we have nx, ny, nz"
        "entries, this rule means that the coordinate (x, ny, z)"
        "will map onto (x, 0, z). Similarly,"
        "(-1, y, z) -> (nx-1, y, z)"
        "Default is false",
        &CubeMesh::setIsToroid,
        &CubeMesh::getIsToroid
    );
    static ValueFinfo< CubeMesh, bool > preserveNumEntries(
        "preserveNumEntries",
        "Flag. When it is true, the numbers nx, ny, nz remain"
        "unchanged when x0, x1, y0, y1, z0, z1 are altered. Thus"
        "dx, dy, dz would change instead. When it is false, then"
        "dx, dy, dz remain the same and nx, ny, nz are altered."
        "Default is true",
        &CubeMesh::setPreserveNumEntries,
        &CubeMesh::getPreserveNumEntries
    );
    static ValueFinfo< CubeMesh, bool > alwaysDiffuse(
        "alwaysDiffuse",
        "Flag. When it is true, the mesh matches up sequential "
        "mesh entries for diffusion and chmestry. This is regardless "
        "of spatial location, and is guaranteed to set up at least "
        "the home reaction system"
        "Default is false",
        &CubeMesh::setAlwaysDiffuse,
        &CubeMesh::getAlwaysDiffuse
    );
    static ElementValueFinfo< CubeMesh, vector< double > > coords(
        "coords",
        "Set all the coords of the cuboid at once. Order is:"
        "x0 y0 z0   x1 y1 z1   dx dy dz"
        "When this is done, it recalculates the numEntries since "
        "dx, dy and dz are given explicitly."
        "As a special hack, you can leave out dx, dy and dz and use "
        "a vector of size 6. In this case the operation assumes that "
        "nx, ny and nz are to be preserved and dx, dy and dz will "
        "be recalculated. ",
        &CubeMesh::setCoords,
        &CubeMesh::getCoords
    );
    static ValueFinfo< CubeMesh, vector< unsigned int > > meshToSpace(
        "meshToSpace",
        "Array in which each mesh entry stores spatial (cubic) index",
        &CubeMesh::setMeshToSpace,
        &CubeMesh::getMeshToSpace
    );
    static ValueFinfo< CubeMesh, vector< unsigned int > > spaceToMesh(
        "spaceToMesh",
        "Array in which each space index (obtained by linearizing "
        "the xyz coords) specifies which meshIndex is present."
        "In many cases the index will store the EMPTY flag if there is"
        "no mesh entry at that spatial location",
        &CubeMesh::setSpaceToMesh,
        &CubeMesh::getSpaceToMesh
    );
    static ValueFinfo< CubeMesh, vector< unsigned int > > surface(
        "surface",
        "Array specifying surface of arbitrary volume within the "
        "CubeMesh. All entries must fall within the cuboid. "
        "Each entry of the array is a spatial index obtained by "
        "linearizing the ix, iy, iz coordinates within the cuboid. "
        "So, each entry == ( iz * ny + iy ) * nx + ix"
        "Note that the voxels listed on the surface are WITHIN the "
        "volume of the CubeMesh object",
        &CubeMesh::setSurface,
        &CubeMesh::getSurface
    );
    // MsgDest Definitions
    static DestFinfo buildMesh( "buildMesh",
                                "Build cubical mesh for geom surface specified by Id, using"
                                "specified x y z coords as an inside point in mesh",
                                new OpFunc4< CubeMesh, Id, double, double, double >(
                                    &CubeMesh::buildMesh )
                              );
    // Field Elements
    static Finfo* cubeMeshFinfos[] =
    {
        &isToroid,      // Value
        &preserveNumEntries,        // Value
        &alwaysDiffuse,     // Value
        &x0,            // Value
        &y0,            // Value
        &z0,            // Value
        &x1,            // Value
        &y1,            // Value
        &z1,            // Value
        &dx,            // Value
        &dy,            // Value
        &dz,            // Value
        &nx,            // Value
        &ny,            // Value
        &nz,            // Value
        &coords,        // Value
        &meshToSpace,   // Value
        &spaceToMesh,   // Value
        &surface,       // Value
    };
    static string doc[] =
    {
        "Name", "CubeMesh",
        "Author", "Upi Bhalla",
        "Description", "Chemical compartment with cuboid grid. "
        "Defaults to a cube of size 10 microns, with mesh size "
        "also 10 microns, so that there is just 1 cubic voxel. "
        "These defaults are similar to that of a typical cell. "
        "Can be configured to have different x,y,z dimensions and "
        "also different dx,dy,dz voxel sizes. ",
    };
    static Dinfo< CubeMesh > dinfo;
    static Cinfo cubeMeshCinfo (
        "CubeMesh",
        ChemCompt::initCinfo(),
        cubeMeshFinfos,
        sizeof( cubeMeshFinfos ) / sizeof ( Finfo* ),
        &dinfo,
        doc,
        sizeof(doc)/sizeof(string)
    );
    return &cubeMeshCinfo;
}
References buildMesh(), Cinfo::Cinfo(), DestFinfo::DestFinfo(), ElementValueFinfo< T, F >::ElementValueFinfo(), getAlwaysDiffuse(), getCoords(), getDx(), getDy(), getDz(), getIsToroid(), getMeshToSpace(), getNx(), getNy(), getNz(), getPreserveNumEntries(), getSpaceToMesh(), getSurface(), getX0(), getX1(), getY0(), getY1(), getZ0(), getZ1(), ChemCompt::initCinfo(), OpFunc4< T, A1, A2, A3, A4 >::OpFunc4(), setAlwaysDiffuse(), setCoords(), setDx(), setDy(), setDz(), setIsToroid(), setMeshToSpace(), setNx(), setNy(), setNz(), setPreserveNumEntries(), setSpaceToMesh(), setSurface(), setX0(), setX1(), setY0(), setY1(), setZ0(), setZ1(), and ValueFinfo< T, F >::ValueFinfo().
innerBuildDefaultMesh()
void CubeMesh::innerBuildDefaultMesh (const Eref & e, double volume, unsigned int numEntries) virtual
Virtual func to make a mesh with specified Volume and numEntries.
Builds something as close to a cube as can get. This needs a smarter boundary handling code than I have here. For now, goes for the nearest cube
Implements ChemCompt.
Definition at line 721 of file CubeMesh.cpp.
{
    double approxN = numEntries;
    approxN = pow( approxN, 1.0 / 3.0 );
    unsigned int smaller = static_cast<unsigned int>(floor( approxN ));
    unsigned int bigger = static_cast<unsigned int>(ceil( approxN ));
    unsigned int numSide;
    if ( smaller != bigger )
    {
        numSide = smaller;
    }
    else
    {
        unsigned int smallerVol = smaller * smaller * smaller;
        unsigned int biggerVol = bigger * bigger * bigger;
        if ( numEntries - smallerVol < biggerVol - numEntries )
            numSide = smaller;
        else
            numSide = bigger;
    }
    double side = pow( volume, 1.0 / 3.0 );
    vector< double > coords( 9, side );
    coords[0] = coords[1] = coords[2] = 0;
    coords[6] = coords[7] = coords[8] = side / numSide;
    nx_ = ny_ = nz_ = numSide;
    setCoords( e, coords );
}
References nx_, ny_, nz_, and setCoords().
innerGetDimensions()
unsigned int CubeMesh::innerGetDimensions () const virtual
Implements ChemCompt.
Definition at line 701 of file CubeMesh.cpp.
{
    return 3;
}
innerGetNumEntries()
unsigned int CubeMesh::innerGetNumEntries () const virtual
Inherited virtual func. Returns number of MeshEntry in array
Implements ChemCompt.
Definition at line 909 of file CubeMesh.cpp.
{
    return m2s_.size();
}
References m2s_.
Referenced by getParentVoxel(), getVoxelLength(), and testCubeMesh().
innerHandleNodeInfo()
void CubeMesh::innerHandleNodeInfo (const Eref & e, unsigned int numNodes, unsigned int numThreads) virtual
Generate node decomposition of mesh, send it out along meshSplitFinfo msg
Implements ChemCompt.
Definition at line 760 of file CubeMesh.cpp.
{
    /*
    unsigned int numEntries = nx_ * ny_ * nz_ ;
    vector< double > vols( numEntries, dx_ * dy_ * dz_ );
    vector< unsigned int > localEntries( numEntries );
    vector< vector< unsigned int > > outgoingEntries;
    vector< vector< unsigned int > > incomingEntries;
    double oldvol = getMeshEntryVolume( 0 );
    meshSplit()->send( e,
        oldvol,
        vols, localEntries,
        outgoingEntries, incomingEntries );
        */
}
innerHandleRequestMeshStats()
void CubeMesh::innerHandleRequestMeshStats (const Eref & e, const SrcFinfo2< unsigned int, vector< double > > * meshStatsFinfo)
More inherited virtual funcs: request comes in for mesh stats.
Definition at line 751 of file CubeMesh.cpp.
{
    vector< double > meshVolumes( 1, dx_ * dy_ * dz_ );
    meshStatsFinfo->send( e, nx_ * ny_ * nz_, meshVolumes);
}
References dx_, dy_, dz_, nx_, ny_, nz_, and SrcFinfo2< T1, T2 >::send().
innerSetCoords()
void CubeMesh::innerSetCoords (const vector< double > & v)
Definition at line 613 of file CubeMesh.cpp.
{
    if ( v.size() < 6 )
        return;
    x0_ = v[0];
    y0_ = v[1];
    z0_ = v[2];
    x1_ = v[3];
    y1_ = v[4];
    z1_ = v[5];
    bool temp = preserveNumEntries_;
    if ( v.size() >= 9 )
    {
        dx_ = v[6];
        dy_ = v[7];
        dz_ = v[8];
        preserveNumEntries_ = 0;
    }
    else
    {
        preserveNumEntries_ = 1;
    }
    updateCoords();
    preserveNumEntries_ = temp;
}
References dx_, dy_, dz_, preserveNumEntries_, updateCoords(), x0_, x1_, y0_, y1_, z0_, and z1_.
Referenced by setCoords(), testCubeMesh(), testCubeMeshExtendStencil(), testCubeMeshFillTwoDimSurface(), testCubeMeshJunctionDiffSizeMesh(), testCubeMeshJunctionTwoDimSurface(), and testCubeMeshMultiJunctionTwoD().
innerSetNumEntries()
void CubeMesh::innerSetNumEntries (unsigned int n) virtual
Inherited virtual func.
Inherited virtual func. Assigns number of MeshEntries.
Implements ChemCompt.
Definition at line 917 of file CubeMesh.cpp.
{
    cout << "Warning: CubeMesh::innerSetNumEntries is readonly.\n";
}
isInsideCuboid()
bool CubeMesh::isInsideCuboid (double x, double y, double z) const
Definition at line 1006 of file CubeMesh.cpp.
{
    return ( x >= x0_ && x < x1_ && y >= y0_ && y < y1_ &&
             z >= z0_ && z < z1_ );
}
References x0_, x1_, y0_, y1_, z0_, and z1_.
Referenced by fillSpaceToMeshLookup().
isInsideSpheroid()
bool CubeMesh::isInsideSpheroid (double x, double y, double z) const
Definition at line 1012 of file CubeMesh.cpp.
{
    double cx = ( x0_ + x1_ ) / 2.0;
    double cy = ( y0_ + y1_ ) / 2.0;
    double cz = ( z0_ + z1_ ) / 2.0;
    double rx = ( x - cx ) / fabs( x1_ - x0_ ) / 2.0;
    double ry = ( y - cy ) / fabs( y1_ - y0_ ) / 2.0;
    double rz = ( z - cz ) / fabs( z1_ - z0_ ) / 2.0;
    return ( ( rx * rx + ry * ry + rz * rz ) < 1.0 );
}
References x0_, x1_, y0_, y1_, z0_, and z1_.
matchAllEntries()
void CubeMesh::matchAllEntries (const CubeMesh * other, vector< VoxelJunction > & ret) const
Dumbed-down version that does mesh matching based only on index. Useful for non-spatial matching and single-voxel systems.
Version that assumes all voxels are in contact and able to diffuse with matching voxels on other mesh
Definition at line 1563 of file CubeMesh.cpp.
{
    ret.clear();
    unsigned int min = m2s_.size();
    if ( min > other->m2s_.size() )
        min = other->m2s_.size();
    ret.resize( min );
    for ( unsigned int i = 0; i < min; ++i )
    {
        ret[i] = VoxelJunction( i, i );
    }
}
References m2s_, and VoxelJunction::VoxelJunction().
Referenced by matchMeshEntries().
matchCubeMeshEntries()
void CubeMesh::matchCubeMeshEntries (const CubeMesh * other, vector< VoxelJunction > & ret) const
Specialization for cube-to-cube mesh matching. Return vector is of pairs of meshIndices (not spatialIndices).
Definition at line 1510 of file CubeMesh.cpp.
{
    // Flip meshes if the current grid is finer.
    // There are still problems here because a finer grid will end
    // up with 2 levels deep defined as being abutting.
    if ( compareMeshSpacing( other ) == -1 )
    {
        other->matchMeshEntries( this, ret );
        flipRet( ret );
        return;
    }
    ret.resize( 0 );
    // Define intersecting cuboid
    double xmin, xmax, ymin, ymax, zmin, zmax;
    defineIntersection( other, xmin, xmax, ymin, ymax, zmin, zmax );
    // Allocate intersecting cuboid
    unsigned int nx = static_cast<unsigned int>(0.5 + ( xmax - xmin ) / dx_);
    unsigned int ny = static_cast<unsigned int>(0.5 + ( ymax - ymin ) / dy_);
    unsigned int nz = static_cast<unsigned int>(0.5 + ( zmax - zmin ) / dz_);
    vector< PII > intersect( nx * ny * nz, PII( EMPTY, EMPTY ) );
    assignVoxels( intersect, xmin, xmax, ymin, ymax, zmin, zmax );
    // Scan through finer mesh surface, check for occupied voxels.
    for ( vector< unsigned int >::const_iterator i =
                other->surface_.begin();
            i != other->surface_.end(); ++i )
    {
        double x, y, z;
        other->indexToSpace( *i, x, y, z );
        if ( x >= xmin && x <= xmax && y >= ymin && y <= ymax &&
                z >= zmin && z <= zmax )
        {
            unsigned int ix = static_cast<unsigned int>(( x - xmin ) / dx_);
            unsigned int iy = static_cast<unsigned int>(( y - ymin ) / dy_);
            unsigned int iz = static_cast<unsigned int>(( z - zmin ) / dz_);
            unsigned int meshIndex = other->s2m_[ *i ];
            checkAbut( intersect, ix, iy, iz, nx, ny, nz, meshIndex, ret );
        }
    }
    // Scan through the VoxelJunctions and populate their diffScale field
    setDiffScale( other, ret );
    // Scan through the VoxelJunctions and populate their volume field
    setJunctionVol( other, ret );
    sort( ret.begin(), ret.end() );
}
References assignVoxels(), checkAbut(), compareMeshSpacing(), defineIntersection(), dx_, dy_, dz_, EMPTY, ChemCompt::flipRet(), indexToSpace(), matchMeshEntries(), s2m_, setDiffScale(), setJunctionVol(), and surface_.
Referenced by matchMeshEntries(), testCubeMeshJunctionDiffSizeMesh(), and testCubeMeshJunctionTwoDimSurface().
matchCylMeshEntries()
void CubeMesh::matchCylMeshEntries (const ChemCompt * other, vector< VoxelJunction > & ret) const
Definition at line 1576 of file CubeMesh.cpp.
{
    other->matchMeshEntries( this, ret );
    flipRet( ret );
}
References ChemCompt::flipRet(), and ChemCompt::matchMeshEntries().
matchMeshEntries()
void CubeMesh::matchMeshEntries (const ChemCompt * other, vector< VoxelJunction > & ret) const virtual
Key virtual function for generating a map between facing surfaces on a CubeMesh and another ChemCompt
Implements ChemCompt.
Definition at line 1155 of file CubeMesh.cpp.
{
    const CubeMesh* cm = dynamic_cast< const CubeMesh* >( other );
    if ( cm )
    {
        if ( alwaysDiffuse_ )
            matchAllEntries( cm, ret );
        else
            matchCubeMeshEntries( cm, ret );
        /*
        if ( compareMeshSpacing( cm ) == 0 ) { // Equal spacing.
                matchSameSpacing( cm, ret );
        } else if ( compareMeshSpacing( cm ) == -1 ) { // self is finer
                cout << "Warning:CubeMesh::matchMeshEntries: cannot yet handle unequal meshes\n";
        } else { // other is finer.
                cout << "Warning:CubeMesh::matchMeshEntries: cannot yet handle unequal meshes\n";
        }
        */
        return;
    }
    const EndoMesh* em = dynamic_cast< const EndoMesh* >( other );
    if ( em )
    {
        em->matchMeshEntries( this, ret );
        flipRet( ret );
        return;
    }
    cout << "Warning:CubeMesh::matchMeshEntries: cannot yet handle Neuro or Cyl meshes.\n";
}
References alwaysDiffuse_, ChemCompt::flipRet(), matchAllEntries(), matchCubeMeshEntries(), and EndoMesh::matchMeshEntries().
Referenced by matchCubeMeshEntries().
nearest()
double CubeMesh::nearest (double x, double y, double z, unsigned int & index) const virtual
Virtual function to return the distance and index of nearest meshEntry. Places entry at centre of voxel.
Implements ChemCompt.
Definition at line 1223 of file CubeMesh.cpp.
{
    if ( x > x0_ && x < x1_ && y > y0_ && y < y1_ && z > z0_ && z < z1_ )
    {
        unsigned int ix = static_cast<unsigned int>(( x - x0_ ) / dx_);
        unsigned int iy = static_cast<unsigned int>(( y - y0_ ) / dy_);
        unsigned int iz = static_cast<unsigned int>(( z - z0_ ) / dz_);
        index = ( iz * ny_ + iy ) * nx_ + ix;
        unsigned int innerIndex = s2m_[ index ];
        if ( innerIndex != EMPTY )   // Inside filled volume
        {
            index = innerIndex;
            double tx = x0_ + ix * dx_ + dx_ * 0.5;
            double ty = y0_ + iy * dy_ + dy_ * 0.5;
            double tz = z0_ + iz * dz_ + dz_ * 0.5;
            return distance( x - tx, y - ty, z - tz );
        }
        else     // Outside volume. Look over surface for nearest.
        {
            double rmin = 1e99;
            for ( vector< unsigned int >::const_iterator
                    i = surface_.begin(); i != surface_.end(); ++i )
            {
                double tx, ty, tz;
                indexToSpace( *i, tx, ty, tz );
                double r = distance( tx - x, ty - y, tz - z );
                if ( rmin > r )
                {
                    rmin = r;
                    index = *i;
                }
            }
            return -rmin; // Negative distance indicates xyz is outside vol
        }
    }
    // Should really figure out nearest corner anyway.
    index = 0;
    return -1.0;
}
References ChemCompt::distance(), dx_, dy_, dz_, EMPTY, indexToSpace(), nx_, ny_, s2m_, surface_, x0_, x1_, y0_, y1_, z0_, and z1_.
neighbor()
unsigned int CubeMesh::neighbor (unsigned int spaceIndex, int dx, int dy, int dz) const
Definition at line 840 of file CubeMesh.cpp.
{
    int ix = spaceIndex % nx_;
    int iy = (spaceIndex / nx_) % ny_;
    int iz = (spaceIndex / ( nx_ * ny_ )) % nz_;
    ix += dx;
    iy += dy;
    iz += dz;
    if ( ix < 0 || ix >= static_cast< int >( nx_ ) )
        return EMPTY;
    if ( iy < 0 || iy >= static_cast< int >( ny_ ) )
        return EMPTY;
    if ( iz < 0 || iz >= static_cast< int >( nz_ ) )
        return EMPTY;
    unsigned int nIndex = ( ( iz * ny_ ) + iy ) * nx_ + ix;
    return s2m_[nIndex];
}
References EMPTY, nx_, ny_, nz_, and s2m_.
Referenced by getDiffusionArea().
numDims()
unsigned int CubeMesh::numDims () const
Utility function for returning # of dimensions in mesh.
Definition at line 1186 of file CubeMesh.cpp.
{
    return ( ( nx_ > 1 ) + ( ny_ > 1 ) + ( nz_ > 1 ) );
}
References nx_, ny_, and nz_.
Referenced by testCubeMeshFillTwoDimSurface().
setAlwaysDiffuse()
void CubeMesh::setAlwaysDiffuse (bool v)
Definition at line 602 of file CubeMesh.cpp.
{
    alwaysDiffuse_ = v;
}
References alwaysDiffuse_.
Referenced by initCinfo().
setCoords()
void CubeMesh::setCoords (const Eref & e, vector< double > v)
Definition at line 643 of file CubeMesh.cpp.
{
    // double oldVol = getMeshEntryVolume( 0 );
    innerSetCoords( v );
    ChemCompt::voxelVolOut()->send( e, vGetVoxelVolume() );
}
References innerSetCoords(), SrcFinfo1< T >::send(), vGetVoxelVolume(), and ChemCompt::voxelVolOut().
Referenced by initCinfo(), and innerBuildDefaultMesh().
setDiffScale()
void CubeMesh::setDiffScale (const CubeMesh * other, vector< VoxelJunction > & ret) const
Assigns diffusion scaling info for the voxel junctions.
Definition at line 1583 of file CubeMesh.cpp.
{
    for ( vector< VoxelJunction >::iterator i = ret.begin();
            i != ret.end(); ++i )
    {
        if ( doubleEq( i->diffScale, 0 ) )   // Junction across x plane
        {
            double selfXA = dy_ * dz_;
            double otherXA = other->dy_ * other->dz_;
            if ( selfXA <= otherXA )
                i->diffScale = 2 * selfXA / ( dx_ + other->dx_ );
            else
                i->diffScale = 2 * otherXA / ( dx_ + other->dx_ );
        }
        else if ( doubleEq( i->diffScale, 1 ) )     // across y plane
        {
            double selfXA = dx_ * dz_;
            double otherXA = other->dx_ * other->dz_;
            if ( selfXA <= otherXA )
                i->diffScale = 2 * selfXA / ( dy_ + other->dy_ );
            else
                i->diffScale = 2 * otherXA / ( dy_ + other->dy_ );
        }
        else if ( doubleEq( i->diffScale, 2 ) )     // across z plane
        {
            double selfXA = dx_ * dy_;
            double otherXA = other->dx_ * other->dy_;
            if ( selfXA <= otherXA )
                i->diffScale = 2 * selfXA / ( dz_ + other->dz_ );
            else
                i->diffScale = 2 * otherXA / ( dz_ + other->dz_ );
        }
        else
        {
            assert( 0 );
        }
    }
}
References VoxelJunction::diffScale, doubleEq(), dx_, dy_, and dz_.
Referenced by matchCubeMeshEntries().
setDx()
void CubeMesh::setDx (double v)
Definition at line 512 of file CubeMesh.cpp.
{
    dx_ = v;
    updateCoords();
}
References dx_, and updateCoords().
Referenced by initCinfo().
setDy()
void CubeMesh::setDy (double v)
Definition at line 524 of file CubeMesh.cpp.
{
    dy_ = v;
    updateCoords();
}
References dy_, and updateCoords().
Referenced by initCinfo().
setDz()
void CubeMesh::setDz (double v)
Definition at line 536 of file CubeMesh.cpp.
{
    dz_ = v;
    updateCoords();
}
References dz_, and updateCoords().
Referenced by initCinfo().
setIsToroid()
void CubeMesh::setIsToroid (bool v)
Definition at line 582 of file CubeMesh.cpp.
{
    isToroid_ = v;
}
References isToroid_.
Referenced by initCinfo().
setJunctionVol()
void CubeMesh::setJunctionVol (const CubeMesh * other, vector< VoxelJunction > & ret) const
Assigns volume info for the voxel junctions.
Definition at line 1624 of file CubeMesh.cpp.
{
    double myVol = dx_ * dy_ * dz_;
    double otherVol = other->dx_ * other->dy_ * other->dz_;
    for ( vector< VoxelJunction >::iterator i = ret.begin();
            i != ret.end(); ++i )
    {
        i->firstVol = myVol;
        i->secondVol = otherVol;
    }
}
References dx_, dy_, dz_, VoxelJunction::firstVol, and VoxelJunction::secondVol.
Referenced by matchCubeMeshEntries().
setMeshToSpace()
void CubeMesh::setMeshToSpace (vector< unsigned int > v)
Definition at line 669 of file CubeMesh.cpp.
{
    m2s_ = v;
    deriveS2mFromM2s();
}
References deriveS2mFromM2s(), and m2s_.
Referenced by initCinfo(), and testCubeMeshJunctionTwoDimSurface().
setNx()
void CubeMesh::setNx (unsigned int v)
Definition at line 547 of file CubeMesh.cpp.
{
    nx_ = v;
    updateCoords();
}
References nx_, and updateCoords().
Referenced by initCinfo().
setNy()
void CubeMesh::setNy (unsigned int v)
Definition at line 559 of file CubeMesh.cpp.
{
    ny_ = v;
    updateCoords();
}
References ny_, and updateCoords().
Referenced by initCinfo().
setNz()
void CubeMesh::setNz (unsigned int v)
Definition at line 570 of file CubeMesh.cpp.
{
    nz_ = v;
    updateCoords();
}
References nz_, and updateCoords().
Referenced by initCinfo().
setPreserveNumEntries()
void CubeMesh::setPreserveNumEntries (bool v)
Definition at line 592 of file CubeMesh.cpp.
{
    preserveNumEntries_ = v;
}
References preserveNumEntries_.
Referenced by initCinfo(), testCubeMesh(), testCubeMeshExtendStencil(), testCubeMeshFillTwoDimSurface(), testCubeMeshJunctionDiffSizeMesh(), testCubeMeshJunctionTwoDimSurface(), and testCubeMeshMultiJunctionTwoD().
setSpaceToMesh()
void CubeMesh::setSpaceToMesh (vector< unsigned int > v)
Definition at line 680 of file CubeMesh.cpp.
{
    s2m_ = v;
    deriveM2sFromS2m();
}
References deriveM2sFromS2m(), and s2m_.
Referenced by initCinfo(), and testCubeMeshJunctionTwoDimSurface().
setSurface()
void CubeMesh::setSurface (vector< unsigned int > v)
Definition at line 691 of file CubeMesh.cpp.
{
    surface_ = v;
}
References surface_.
Referenced by initCinfo(), and testCubeMeshJunctionTwoDimSurface().
setX0()
void CubeMesh::setX0 (double v)
Definition at line 446 of file CubeMesh.cpp.
{
    x0_ = v;
    updateCoords();
}
References updateCoords(), and x0_.
Referenced by initCinfo(), and testCubeMesh().
setX1()
void CubeMesh::setX1 (double v)
Definition at line 479 of file CubeMesh.cpp.
{
    x1_ = v;
    updateCoords();
}
References updateCoords(), and x1_.
Referenced by initCinfo(), and testCubeMesh().
setY0()
void CubeMesh::setY0 (double v)
Definition at line 457 of file CubeMesh.cpp.
{
    y0_ = v;
    updateCoords();
}
References updateCoords(), and y0_.
Referenced by initCinfo(), and testCubeMesh().
setY1()
void CubeMesh::setY1 (double v)
Definition at line 490 of file CubeMesh.cpp.
{
    y1_ = v;
    updateCoords();
}
References updateCoords(), and y1_.
Referenced by initCinfo(), and testCubeMesh().
setZ0()
void CubeMesh::setZ0 (double v)
Definition at line 468 of file CubeMesh.cpp.
{
    z0_ = v;
    updateCoords();
}
References updateCoords(), and z0_.
Referenced by initCinfo(), and testCubeMesh().
setZ1()
void CubeMesh::setZ1 (double v)
Definition at line 501 of file CubeMesh.cpp.
{
    z1_ = v;
    updateCoords();
}
References updateCoords(), and z1_.
Referenced by initCinfo(), and testCubeMesh().
spaceToIndex()
unsigned int CubeMesh::spaceToIndex (double x, double y, double z) const
Converts the 3-D coords to an index. EMPTY if out of range.
Definition at line 1209 of file CubeMesh.cpp.
{
    if ( x > x0_ && x < x1_ && y > y0_ && y < y1_ && z > z0_ && z < z1_ )
    {
        unsigned int ix = static_cast<unsigned int>(( x - x0_ ) / dx_);
        unsigned int iy = static_cast<unsigned int>(( y - y0_ ) / dy_);
        unsigned int iz = static_cast<unsigned int>(( z - z0_ ) / dz_);
        unsigned int index = ( iz * ny_ + iy ) * nx_ + ix;
        unsigned int innerIndex = s2m_[ index ];
        return innerIndex;
    }
    return EMPTY;
}
References dx_, dy_, dz_, EMPTY, nx_, ny_, s2m_, x0_, x1_, y0_, y1_, z0_, and z1_.
Referenced by fillPointsOnCircle(), fillPointsOnCircle(), and fillPointsOnDisc().
surface()
const vector< unsigned int > & CubeMesh::surface () const
Utility and test function to read surface.
Definition at line 1148 of file CubeMesh.cpp.
{
    return surface_;
}
References surface_.
Referenced by testCubeMeshFillTwoDimSurface(), testCubeMeshJunctionDiffSizeMesh(), testCubeMeshJunctionTwoDimSurface(), and testCubeMeshMultiJunctionTwoD().
transmitChange()
void CubeMesh::transmitChange (const Eref & e, double oldvol)
updateCoords()
void CubeMesh::updateCoords ()
Recomputes all local coordinate and meshing data following a change in any of the coord parameters
This assumes that dx, dy, dz are the quantities to preserve, over numEntries. So when the compartment changes volume, so does numEntries. dx, dy, dz do not change, some of the sub-cuboids will partially be outside.
Temporarily fill out the whole cube for m2s and s2m. These
Definition at line 391 of file CubeMesh.cpp.
{
    swapIfBackward( x0_, x1_ );
    swapIfBackward( y0_, y1_ );
    swapIfBackward( z0_, z1_ );
    if ( preserveNumEntries_ )
    {
        dx_ = ( x1_ - x0_ ) / nx_;
        dy_ = ( y1_ - y0_ ) / ny_;
        dz_ = ( z1_ - z0_ ) / nz_;
    }
    else
    {
        nx_ = static_cast<unsigned int>(round( (x1_ - x0_) / dx_ ));
        ny_ = static_cast<unsigned int>(round( (y1_ - y0_) / dy_ ));
        nz_ = static_cast<unsigned int>(round( (z1_ - z0_) / dz_ ));
        if ( nx_ == 0 ) nx_ = 1;
        if ( ny_ == 0 ) ny_ = 1;
        if ( nz_ == 0 ) nz_ = 1;
    }
    // will change for none-cube geometries.
    unsigned int size = nx_ * ny_ * nz_;
    m2s_.resize( size );
    s2m_.resize( size );
    for ( unsigned int i = 0; i < size; ++i )
    {
        m2s_[i] = s2m_[i] = i;
    }
    // Fill out surface vector
    surface_.resize( 0 );
    /*
    if ( numDims() == 0 ) {
        surface_.push_back( 0 );
    } else if ( numDims() == 1 ) {
        surface_.push_back( 0 );
        if ( size > 1 )
            surface_.push_back( size - 1 );
    } else if ( numDims() == 2 ) {
        fillTwoDimSurface();
    } else if ( numDims() == 3 ) {
        fillThreeDimSurface();
    }
    */
    fillThreeDimSurface();
    // volume_ = ( x1_ - x0_ ) * ( y1_ - y0_ ) * ( z1_ - z0_ );
    assert( size >= 0 );
    buildStencil();
}
References buildStencil(), dx_, dy_, dz_, fillThreeDimSurface(), m2s_, nx_, ny_, nz_, preserveNumEntries_, s2m_, surface_, swapIfBackward(), x0_, x1_, y0_, y1_, z0_, and z1_.
Referenced by CubeMesh(), innerSetCoords(), setDx(), setDy(), setDz(), setNx(), setNy(), setNz(), setX0(), setX1(), setY0(), setY1(), setZ0(), and setZ1().
updateM2s()
void CubeMesh::updateM2s ()
updateS2m()
void CubeMesh::updateS2m ()
vGetEntireVolume()
double CubeMesh::vGetEntireVolume () const virtual
Virtual func to get volume of entire compartment.
Implements ChemCompt.
Definition at line 778 of file CubeMesh.cpp.
{
    return fabs( (x1_ - x0_) * (y1_ - y0_) * (z1_ - z0_) );
}
References x0_, x1_, y0_, y1_, z0_, and z1_.
Referenced by vSetVolumeNotRates().
vGetVoxelMidpoint()
const vector< double > & CubeMesh::vGetVoxelMidpoint () const virtual
Virtual func so that derived classes can return voxel midpoint.
Implements ChemCompt.
Definition at line 943 of file CubeMesh.cpp.
{
    static vector< double > midpoint;
    midpoint.resize( m2s_.size() * 3 );
    for ( unsigned int i = 0; i < m2s_.size(); ++i ) // x coords. Lowest.
        midpoint[i] = x0_ + ( 0.5 + (m2s_[i] % nx_ ) ) * dx_;
    for ( unsigned int i = 0; i < m2s_.size(); ++i )   // y coords. Middle.
    {
        unsigned int k = i + m2s_.size();
        midpoint[k] = y0_ + ( 0.5 + ( (m2s_[i] / nx_) % ny_ ) ) * dy_;
    }
    for ( unsigned int i = 0; i < m2s_.size(); ++i )   // z coords. Top.
    {
        unsigned int k = i + m2s_.size() * 2;
        midpoint[k] = z0_ + ( 0.5 + ( m2s_[i] / ( nx_ * ny_ ) ) ) * dz_;
    }
    return midpoint;
}
References dx_, dy_, dz_, m2s_, nx_, ny_, x0_, y0_, and z0_.
vGetVoxelVolume()
const vector< double > & CubeMesh::vGetVoxelVolume () const virtual
Virtual func so that derived classes can pass voxel volume back.
Implements ChemCompt.
Definition at line 935 of file CubeMesh.cpp.
{
    static vector< double > vol;
    vol.clear();
    vol.resize( nx_ * ny_ * nz_, dx_ * dy_ * dz_ );
    return vol;
}
References dx_, dy_, dz_, nx_, ny_, and nz_.
Referenced by setCoords().
vSetVolumeNotRates()
bool CubeMesh::vSetVolumeNotRates (double volume) virtual
Virtual func, assigns volume, usually to single voxel.
Implements ChemCompt.
Definition at line 989 of file CubeMesh.cpp.
{
    // Leave x0,y0.z0 and nx,ny,nz the same. Do NOT update any rates.
    double oldvol = vGetEntireVolume();
    double linscale = pow( vol / oldvol, 1.0 / 3.0 );
    dx_ *= linscale;
    dy_ *= linscale;
    dz_ *= linscale;
    x1_ = x0_ + dx_;
    y1_ = y0_ + dy_;
    z1_ = z0_ + dz_;
    return true;
}
References dx_, dy_, dz_, vGetEntireVolume(), x0_, x1_, y0_, y1_, z0_, and z1_.
Member Data Documentation
ABUTX
const unsigned int CubeMesh::ABUTX = ~2 static
Definition at line 287 of file CubeMesh.h.
Referenced by checkAbut(), setIntersectVoxel(), and testIntersectVoxel().
ABUTY
const unsigned int CubeMesh::ABUTY = ~3 static
Definition at line 288 of file CubeMesh.h.
Referenced by checkAbut(), and setIntersectVoxel().
ABUTZ
const unsigned int CubeMesh::ABUTZ = ~4 static
Definition at line 289 of file CubeMesh.h.
Referenced by checkAbut(), and setIntersectVoxel().
alwaysDiffuse_
bool CubeMesh::alwaysDiffuse_ private
Flag: Should dx change or nx, with vol?
Definition at line 297 of file CubeMesh.h.
Referenced by CubeMesh(), getAlwaysDiffuse(), matchMeshEntries(), and setAlwaysDiffuse().
dx_
double CubeMesh::dx_ private
coords
Definition at line 307 of file CubeMesh.h.
Referenced by assignVoxels(), buildStencil(), compareMeshSpacing(), CubeMesh(), defineIntersection(), extendedMeshEntryVolume(), fillSpaceToMeshLookup(), getCoordinates(), getCoords(), getDiffusionArea(), getDx(), getMeshEntryVolume(), getVoxelArea(), getVoxelLength(), indexToSpace(), innerHandleRequestMeshStats(), innerSetCoords(), matchCubeMeshEntries(), nearest(), setDiffScale(), setDx(), setJunctionVol(), spaceToIndex(), updateCoords(), vGetVoxelMidpoint(), vGetVoxelVolume(), and vSetVolumeNotRates().
dy_
double CubeMesh::dy_ private
Cuboid edge.
Definition at line 308 of file CubeMesh.h.
Referenced by assignVoxels(), buildStencil(), compareMeshSpacing(), CubeMesh(), defineIntersection(), extendedMeshEntryVolume(), fillSpaceToMeshLookup(), getCoordinates(), getCoords(), getDiffusionArea(), getDy(), getMeshEntryVolume(), getVoxelArea(), getVoxelLength(), indexToSpace(), innerHandleRequestMeshStats(), innerSetCoords(), matchCubeMeshEntries(), nearest(), setDiffScale(), setDy(), setJunctionVol(), spaceToIndex(), updateCoords(), vGetVoxelMidpoint(), vGetVoxelVolume(), and vSetVolumeNotRates().
dz_
double CubeMesh::dz_ private
Cuboid edge.
Definition at line 309 of file CubeMesh.h.
Referenced by assignVoxels(), buildStencil(), compareMeshSpacing(), CubeMesh(), defineIntersection(), extendedMeshEntryVolume(), fillSpaceToMeshLookup(), getCoordinates(), getCoords(), getDiffusionArea(), getDz(), getMeshEntryVolume(), getVoxelArea(), getVoxelLength(), indexToSpace(), innerHandleRequestMeshStats(), innerSetCoords(), matchCubeMeshEntries(), nearest(), setDiffScale(), setDz(), setJunctionVol(), spaceToIndex(), updateCoords(), vGetVoxelMidpoint(), vGetVoxelVolume(), and vSetVolumeNotRates().
EMPTY
const unsigned int CubeMesh::EMPTY = ~0 static
Definition at line 285 of file CubeMesh.h.
Referenced by buildStencil(), checkAbut(), deriveM2sFromS2m(), deriveS2mFromM2s(), fillPointsOnCircle(), fillPointsOnCircle(), fillPointsOnDisc(), fillSpaceToMeshLookup(), getDiffusionArea(), matchCubeMeshEntries(), nearest(), neighbor(), setAbut(), spaceToIndex(), and testIntersectVoxel().
isToroid_
bool CubeMesh::isToroid_ private
Definition at line 295 of file CubeMesh.h.
Referenced by CubeMesh(), getIsToroid(), and setIsToroid().
m2s_
vector< unsigned int > CubeMesh::m2s_ private
of entries in z in surround volume
For spherical mesh, coords are xyz r0 r1 theta0 theta1 phi0 phi1 For Cylindrical mesh, coords are x1y1z1 x2y2z2 r0 r1 phi0 phi1 For cuboid mesh, coords are x1y1z1 x2y2z2 For tetrahedral mesh, coords are x1y1z1 x2y2z2 x3y3z3 x4y4z4 Later worry about planar meshes. Those would be surfaces Mesh to Space lookup. Indexed by linear mesh index, from 0 to number of actual mesh entries (occupied cuboids). Returns spatial index, from 0 to nx * ny * nz - 1. Needed whenever the cuboid mesh is not filling the entire volume of the cube, that is, in most cases.
Definition at line 330 of file CubeMesh.h.
Referenced by buildStencil(), CubeMesh(), deriveM2sFromS2m(), deriveS2mFromM2s(), extendedMeshEntryVolume(), fillSpaceToMeshLookup(), getCoordinates(), getDiffusionArea(), getMeshToSpace(), innerGetNumEntries(), matchAllEntries(), setMeshToSpace(), updateCoords(), and vGetVoxelMidpoint().
MULTI
const unsigned int CubeMesh::MULTI = ~5 static
Definition at line 290 of file CubeMesh.h.
Referenced by checkAbut(), setAbut(), and testIntersectVoxel().
nx_
unsigned int CubeMesh::nx_ private
Cuboid edge.
Definition at line 311 of file CubeMesh.h.
Referenced by assignVoxels(), buildStencil(), CubeMesh(), deriveM2sFromS2m(), deriveS2mFromM2s(), fillSpaceToMeshLookup(), fillThreeDimSurface(), fillTwoDimSurface(), getCoordinates(), getNx(), getVoxelArea(), indexToSpace(), innerBuildDefaultMesh(), innerHandleRequestMeshStats(), nearest(), neighbor(), numDims(), setNx(), spaceToIndex(), updateCoords(), vGetVoxelMidpoint(), and vGetVoxelVolume().
ny_
unsigned int CubeMesh::ny_ private
of entries in x in surround volume
Definition at line 312 of file CubeMesh.h.
Referenced by assignVoxels(), buildStencil(), CubeMesh(), deriveM2sFromS2m(), deriveS2mFromM2s(), fillSpaceToMeshLookup(), fillThreeDimSurface(), fillTwoDimSurface(), getCoordinates(), getNy(), getVoxelArea(), indexToSpace(), innerBuildDefaultMesh(), innerHandleRequestMeshStats(), nearest(), neighbor(), numDims(), setNy(), spaceToIndex(), updateCoords(), vGetVoxelMidpoint(), and vGetVoxelVolume().
nz_
unsigned int CubeMesh::nz_ private
of entries in y in surround volume
Definition at line 313 of file CubeMesh.h.
Referenced by assignVoxels(), buildStencil(), CubeMesh(), deriveM2sFromS2m(), deriveS2mFromM2s(), fillSpaceToMeshLookup(), fillThreeDimSurface(), fillTwoDimSurface(), getCoordinates(), getNz(), getVoxelArea(), indexToSpace(), innerBuildDefaultMesh(), innerHandleRequestMeshStats(), neighbor(), numDims(), setNz(), updateCoords(), and vGetVoxelVolume().
preserveNumEntries_
bool CubeMesh::preserveNumEntries_ private
Flag: Should the ends loop around mathemagically?
Definition at line 296 of file CubeMesh.h.
Referenced by CubeMesh(), getPreserveNumEntries(), innerSetCoords(), setPreserveNumEntries(), and updateCoords().
s2m_
vector< unsigned int > CubeMesh::s2m_ private
Space to Mesh lookup. Indexed by spatial index, from 0 to nx * ny * nz - 1. Specifically, point x y z is indexed as (z * ny + y) * nx + x. Returns mesh index to look up molecules etc in the specific volume. In case the spatial location is outside the included volume of the mesh, returns ~0.
Definition at line 339 of file CubeMesh.h.
Referenced by assignVoxels(), buildStencil(), CubeMesh(), deriveM2sFromS2m(), deriveS2mFromM2s(), fillSpaceToMeshLookup(), getSpaceToMesh(), matchCubeMeshEntries(), nearest(), neighbor(), setSpaceToMesh(), spaceToIndex(), and updateCoords().
SURFACE
const unsigned int CubeMesh::SURFACE = ~1 static
Definition at line 286 of file CubeMesh.h.
Referenced by checkAbut(), setAbut(), setIntersectVoxel(), and testIntersectVoxel().
surface_
vector< unsigned int > CubeMesh::surface_ private
Vector of spatial meshIndices comprising surface of volume in CubeMesh.
Definition at line 345 of file CubeMesh.h.
Referenced by assignVoxels(), fillThreeDimSurface(), fillTwoDimSurface(), getSurface(), matchCubeMeshEntries(), nearest(), setSurface(), surface(), and updateCoords().
x0_
double CubeMesh::x0_ private
Flag: should all voxels diffuse to any tgt?
Definition at line 299 of file CubeMesh.h.
Referenced by assignVoxels(), CubeMesh(), defineIntersection(), fillSpaceToMeshLookup(), getCoordinates(), getCoords(), getX0(), indexToSpace(), innerSetCoords(), isInsideCuboid(), isInsideSpheroid(), nearest(), setX0(), spaceToIndex(), updateCoords(), vGetEntireVolume(), vGetVoxelMidpoint(), and vSetVolumeNotRates().
x1_
double CubeMesh::x1_ private
coords
Definition at line 303 of file CubeMesh.h.
Referenced by CubeMesh(), defineIntersection(), getCoords(), getX1(), innerSetCoords(), isInsideCuboid(), isInsideSpheroid(), nearest(), setX1(), spaceToIndex(), updateCoords(), vGetEntireVolume(), and vSetVolumeNotRates().
y0_
double CubeMesh::y0_ private
coords
Definition at line 300 of file CubeMesh.h.
Referenced by assignVoxels(), CubeMesh(), defineIntersection(), fillSpaceToMeshLookup(), getCoordinates(), getCoords(), getY0(), indexToSpace(), innerSetCoords(), isInsideCuboid(), isInsideSpheroid(), nearest(), setY0(), spaceToIndex(), updateCoords(), vGetEntireVolume(), vGetVoxelMidpoint(), and vSetVolumeNotRates().
y1_
double CubeMesh::y1_ private
coords
Definition at line 304 of file CubeMesh.h.
Referenced by CubeMesh(), defineIntersection(), getCoords(), getY1(), innerSetCoords(), isInsideCuboid(), isInsideSpheroid(), nearest(), setY1(), spaceToIndex(), updateCoords(), vGetEntireVolume(), and vSetVolumeNotRates().
z0_
double CubeMesh::z0_ private
coords
Definition at line 301 of file CubeMesh.h.
Referenced by assignVoxels(), CubeMesh(), defineIntersection(), fillSpaceToMeshLookup(), getCoordinates(), getCoords(), getZ0(), indexToSpace(), innerSetCoords(), isInsideCuboid(), isInsideSpheroid(), nearest(), setZ0(), spaceToIndex(), updateCoords(), vGetEntireVolume(), vGetVoxelMidpoint(), and vSetVolumeNotRates().
z1_
double CubeMesh::z1_ private
coords
Definition at line 305 of file CubeMesh.h.
Referenced by CubeMesh(), defineIntersection(), getCoords(), getZ1(), innerSetCoords(), isInsideCuboid(), isInsideSpheroid(), nearest(), setZ1(), spaceToIndex(), updateCoords(), vGetEntireVolume(), and vSetVolumeNotRates().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/mesh/CubeMesh.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/mesh/CubeMesh.cpp