MOOSE - Multiscale Object Oriented Simulation Environment: NeuroMesh Class Reference
NeuroMesh Class Reference
#include <NeuroMesh.h>
Public Member Functions
void buildNodeTree (const map< Id, unsigned int > &comptMap)
void buildStencil ()
Utility function to set up Stencil for diffusion in NeuroMesh.
double extendedMeshEntryVolume (unsigned int fid) const
Vol of all mesh Entries including abutting diff-coupled voxels.
bool filterSpines (Id compt)
double getAdx (unsigned int curr, unsigned int &parentFid) const
vector< double > getCoordinates (unsigned int fid) const
Virtual function to return coords of mesh Entry.
vector< unsigned int > getDendVoxelsOnCompartment (ObjId compt) const
double getDiffLength () const
vector< double > getDiffusionArea (unsigned int fid) const
Virtual function to return diffusion X-section area.
vector< double > getDiffusionScaling (unsigned int fid) const
Virtual function to return scale factor for diffusion. 1 here.
vector< Id > getElecComptList () const
vector< Id > getElecComptMap () const
vector< unsigned int > getEndVoxelInCompt () const
string getGeometryPolicy () const
unsigned int getMeshDimensions (unsigned int fid) const
Virtual function to return dimensions of specified entry.
double getMeshEntryVolume (unsigned int fid) const
Virtual function to return volume of mesh Entry.
unsigned int getMeshType (unsigned int fid) const
Virtual function to return MeshType of specified entry.
const vector< NeuroNode > & getNodes () const
unsigned int getNumDiffCompts () const
unsigned int getNumSegments () const
vector< unsigned int > getParentVoxel () const
bool getSeparateSpines () const
vector< int > getSpineVoxelOnDendVoxel () const
vector< unsigned int > getSpineVoxelsOnCompartment (ObjId compt) const
vector< unsigned int > getStartVoxelInCompt () const
vector< ObjId > getSubTree (const Eref &e) const
string getSubTreePath (const Eref &e) const
const vector< double > & getVoxelArea () const
const vector< double > & getVoxelLength () const
void indexToSpace (unsigned int index, double &x, double &y, double &z) const
void innerBuildDefaultMesh (const Eref &e, double size, unsigned int numEntries)
Virtual func to make a mesh with specified size and numEntries.
unsigned int innerGetDimensions () const
unsigned int innerGetNumEntries () const
void innerHandleNodeInfo (const Eref &e, unsigned int numNodes, unsigned int numThreads)
void innerHandleRequestMeshStats (const Eref &e, const SrcFinfo2< unsigned int, vector< double > > *meshStatsFinfo)
void innerSetNumEntries (unsigned int n)
Inherited virtual func.
void insertDummyNodes ()
void insertSingleDummy (unsigned int parent, unsigned int self, double x, double y, double z)
void matchCubeMeshEntries (const ChemCompt *other, vector< VoxelJunction > &ret) const
void matchMeshEntries (const ChemCompt *other, vector< VoxelJunction > &ret) const
void matchNeuroMeshEntries (const ChemCompt *other, vector< VoxelJunction > &ret) const
double nearest (double x, double y, double z, unsigned int &index) const
NeuroMesh ()
NeuroMesh (const NeuroMesh &other)
NeuroMesh & operator= (const NeuroMesh &other)
Id putSomaAtStart (Id origSoma, unsigned int maxDiaIndex)
This shuffles the nodes_ vector to put soma node at the start.
void setDiffLength (double v)
void setGeometryPolicy (string v)
void setSeparateSpines (bool v)
void setSubTree (const Eref &e, vector< ObjId > compartments)
void setSubTreePath (const Eref &e, string path)
void transmitSpineInfo (const Eref &e)
void updateCoords ()
void updateShaftParents ()
double vGetEntireVolume () const
const vector< double > & vGetVoxelMidpoint () const
Virtual func so that derived classes can return voxel midpoint.
const vector< double > & vGetVoxelVolume () const
Virtual func so that derived classes can pass voxel volume back.
bool vSetVolumeNotRates (double volume)
~NeuroMesh ()
Public Member Functions inherited from MeshCompt
void addRow (unsigned int index, const vector< double > &entry, const vector< unsigned int > &colIndex)
void clearExtendedMeshEntryVolume ()
Inherited virtual function to clear the vector of MeshEntryVolume.
void extendStencil (const ChemCompt *other, const vector< VoxelJunction > &vj)
Add boundary voxels to stencil for cross-solver junctions.
vector< unsigned int > getNeighbors (unsigned int fid) const
Looks up stencil to return vector of indices of coupled voxels.
const SparseMatrix< double > & getStencil () const
Returns entire sparse matrix of mesh. Used by diffusion solver.
unsigned int getStencilRow (unsigned int meshIndex, const double **entry, const unsigned int **colIndex) const
vector< double > innerGetStencilRate (unsigned int row) const
void innerResetStencil ()
virtual func implemented here.
MeshCompt ()
void setStencilSize (unsigned int numRows, unsigned int numCols)
~MeshCompt ()
Public Member Functions inherited from ChemCompt
void buildDefaultMesh (const Eref &e, double volume, unsigned int numEntries)
void buildJunction (ChemCompt *other, vector< VoxelJunction > &ret)
ChemCompt ()
void flipRet (vector< VoxelJunction > &ret) const
Utility function for swapping first and second in VoxelJunctions.
void getChildConcs (const Eref &e, vector< double > &childConcs) const
unsigned int getDimensions () const
double getEntireVolume (const Eref &e) const
bool getIsMembraneBound () const
string getMethod () const
unsigned int getNumEntries () const
vector< double > getOneVoxelMidpoint (unsigned int vox) const
Looks up specified voxel midpoint, from vGetVoxelMidpoint.
double getOneVoxelVolume (const Eref &e, unsigned int voxel) const
vector< unsigned int > getStencilIndex (unsigned int row) const
vector< double > getStencilRate (unsigned int row) const
vector< double > getVoxelMidpoint () const
Returns vector of all voxel midpoints in compartment.
vector< double > getVoxelVolume () const
Returns vector of all voxel volumes in compartment.
void handleNodeInfo (const Eref &e, unsigned int numNodes, unsigned int numThreads)
MeshEntry * lookupEntry (unsigned int index)
void resetStencil ()
unsigned int setChildConcs (const Eref &e, const vector< double > &childConcs, unsigned int start) const
void setEntireVolume (const Eref &e, double volume)
void setIsMembraneBound (bool v)
virtual void setMeshEntryVolume (unsigned int fid, double volume)
void setMethod (string method)
void setNumEntries (unsigned int num)
void setOneVoxelVolume (const Eref &e, unsigned int voxel, double volume)
void setVolumeNotRates (double volume)
virtual ~ChemCompt ()
Static Public Member Functions
static const Cinfo * initCinfo ()
Static Public Member Functions inherited from ChemCompt
static double distance (double x, double y, double z)
static const Cinfo * initCinfo ()
static SrcFinfo1< vector< double > > * voxelVolOut ()
Private Attributes
vector< double > area_
double diffLength_
string geometryPolicy_
vector< Id > head_
Id of shaft compartment.
vector< double > length_
Pre-calculation of length of each MeshEntry.
vector< unsigned int > nodeIndex_
vector< NeuroNode > nodes_
vector< unsigned int > parent_
Id of head compartment.
vector< unsigned int > parentVoxel_
Index of parent voxel of spines.
bool separateSpines_
Max permitted length constant for diffusion.
vector< Id > shaft_
string subTreePath_
double surfaceGranularity_
vector< double > vs_
Detailed Description
The NeuroMesh represents sections of a neuron whose spatial attributes are obtained from a neuronal model. Like the CylMesh, this is pseudo-1 dimension: Only the axial dimension is considered for diffusion and subdivisions. Branching is also handled.
Dendritic spines typically contain different reaction systems from the dendrite, but each spine has the same reactions. So they deserve their own mesh: SpineMesh. The idea is the the SpineMesh has just the spine head compartment, which duplicate the same reactions, but does not diffuse to other spine heads. Instead it has an effective diffusion constant to the parent dendrite compartment, obtained by treating the spine neck as a diffusion barrier with zero volume.
Definition at line 31 of file NeuroMesh.h.
Constructor & Destructor Documentation
NeuroMesh() [1/2]
NeuroMesh::NeuroMesh ()
Definition at line 285 of file NeuroMesh.cpp.
    :
    nodes_(1),
    subTreePath_( "Undefined" ),
    nodeIndex_(1, 0 ),
    vs_( 1, NA * 1e-9 ),
    area_( 1, 1.0e-12 ),
    length_( 1, 1.0e-6 ),
    diffLength_( 1.0e-6 ),
    separateSpines_( false ),
    geometryPolicy_( "default" ),
    surfaceGranularity_( 0.1 ),
    parentVoxel_(1, -1)
{
    nodes_[0].setLength( diffLength_ );
    nodes_[0].setDia( diffLength_ );
    nodes_[0].setNumDivs( 1 );
}
References area_, diffLength_, geometryPolicy_, length_, NA, nodeIndex_, nodes_, parentVoxel_, separateSpines_, CylBase::setDia(), CylBase::setLength(), CylBase::setNumDivs(), subTreePath_, surfaceGranularity_, and vs_.
NeuroMesh() [2/2]
NeuroMesh::NeuroMesh (const NeuroMesh & other)
Definition at line 304 of file NeuroMesh.cpp.
    :
    diffLength_( other.diffLength_ ),
    separateSpines_( other.separateSpines_ ),
    geometryPolicy_( other.geometryPolicy_ ),
    surfaceGranularity_( other.surfaceGranularity_ )
{
    ;
}
References diffLength_, geometryPolicy_, separateSpines_, and surfaceGranularity_.
~NeuroMesh()
NeuroMesh::~NeuroMesh ()
Definition at line 327 of file NeuroMesh.cpp.
{
    ;
}
Member Function Documentation
buildNodeTree()
void NeuroMesh::buildNodeTree (const map< Id, unsigned int > & comptMap)
buildNodeTree: This connects up parent and child nodes and if needed inserts dummy nodes to build up the model tree.
buildStencil()
void NeuroMesh::buildStencil ()
Utility function to set up Stencil for diffusion in NeuroMesh.
Definition at line 1164 of file NeuroMesh.cpp.
{
    parentVoxel_.clear();
    setStencilSize( nodeIndex_.size(), nodeIndex_.size() );
    SparseMatrix< double > sm( nodeIndex_.size(), nodeIndex_.size() );
    vector< vector< double > > paEntry( nodeIndex_.size() );
    vector< vector< unsigned int > > paColIndex( nodeIndex_.size() );
    // It is very easy to set up the matrix using the parent as there is
    // only one parent for every voxel.
    for ( unsigned int i = 0; i < nodeIndex_.size(); ++i )
    {
        unsigned int parentFid;
        double adx = getAdx( i, parentFid );
        parentVoxel_.push_back( parentFid );
        if ( adx < 0.0 ) // No diffusion, so don't put in any entry.
            continue;
        /*
        const NeuroNode &nn = nodes_[ nodeIndex_[i] ];
        const NeuroNode *pa = &nodes_[ nn.parent() ];
        double L1 = nn.getLength() / nn.getNumDivs();
        double L2 = L1;
        unsigned int parentFid = i - 1;
        if ( nn.startFid() == i ) {
            // We're at the start of the node, need to refer to parent for L
            const NeuroNode* realParent = pa;
            if ( pa->isDummyNode() ) {
                realParent = &nodes_[ realParent->parent() ];
                if ( realParent->isDummyNode() ) {
                    // Still dummy. So we're at a terminus. No diffusion
                    continue;
                }
            }
            L2 = realParent->getLength() / realParent->getNumDivs();
            parentFid = realParent->startFid() +
                    realParent->getNumDivs() - 1;
        }
        assert( parentFid < nodeIndex_.size() );
        double length = 0.5 * (L1 + L2 );
        // Note that we use the parent node here even if it is a dummy.
        // It has the correct diameter.
        double adx = nn.getDiffusionArea( *pa, i - nn.startFid() ) / length;
        */
        paEntry[ i ].push_back( adx );
        paColIndex[ i ].push_back( parentFid );
        // Now put in the symmetric entries.
        paEntry[ parentFid ].push_back( adx );
        paColIndex[ parentFid ].push_back( i );
    }
    // Now go through the paEntry and paColIndex and build sparse matrix.
    // We have to do this separately because the sparse matrix has to be
    // build up in row order, and sorted, whereas the entries above
    // are random access.
    for ( unsigned int i = 0; i < nodeIndex_.size(); ++i )
    {
        unsigned int num = paColIndex[i].size();
        vector< Ecol > e( num );
        vector< double > entry( num );
        vector< unsigned int > colIndex( num );
        for ( unsigned int j = 0; j < num; ++j )
        {
            e[j] = Ecol( paEntry[i][j], paColIndex[i][j] );
        }
        sort( e.begin(), e.end() );
        for ( unsigned int j = 0; j < num; ++j )
        {
            entry[j] = e[j].e_;
            colIndex[j] = e[j].col_;
        }
        addRow( i, entry, colIndex );
    }
    innerResetStencil();
}
References MeshCompt::addRow(), Ecol::col_, Ecol::e_, Ecol::Ecol(), getAdx(), MeshCompt::innerResetStencil(), nodeIndex_, parentVoxel_, MeshCompt::setStencilSize(), and SparseMatrix< T >::SparseMatrix().
Referenced by updateCoords().
extendedMeshEntryVolume()
double NeuroMesh::extendedMeshEntryVolume (unsigned int fid) const virtual
Vol of all mesh Entries including abutting diff-coupled voxels.
Virtual function to return volume of mesh Entry, including for diffusively coupled voxels from other solvers.
Reimplemented from MeshCompt.
Definition at line 969 of file NeuroMesh.cpp.
{
    if ( fid < nodeIndex_.size() )
    {
        return getMeshEntryVolume( fid );
    }
    else
    {
        return MeshCompt::extendedMeshEntryVolume( fid - nodeIndex_.size() );
    }
}
References MeshCompt::extendedMeshEntryVolume(), getMeshEntryVolume(), and nodeIndex_.
filterSpines()
bool NeuroMesh::filterSpines (Id compt)
Returns true if it finds a compartment name that looks like it ought to be on a spine. It filters out the names "neck", "shaft", "spine" and "head". The latter two are classified into the head_ vector. The first two are classified into the shaft_ vector.
Definition at line 571 of file NeuroMesh.cpp.
{
    if ( compt.element()->getName().find( "shaft" ) != string::npos ||
            compt.element()->getName().find( "neck" ) != string::npos )
    {
        shaft_.push_back( compt );
        return true;
    }
    if ( compt.element()->getName().find( "spine" ) != string::npos ||
            compt.element()->getName().find( "head" ) != string::npos )
    {
        head_.push_back( compt );
        return true;
    }
    return false;
}
References Id::element(), Element::getName(), head_, and shaft_.
getAdx()
double NeuroMesh::getAdx (unsigned int curr, unsigned int & parentFid) const
Helper function for buildStencil, calculates diffusion term adx for rate between current compartment curr, and parent. By product: also passes back parent compartment index.
Definition at line 1124 of file NeuroMesh.cpp.
{
    const NeuroNode &nn = nodes_[ nodeIndex_[i] ];
    if ( nn.isDummyNode() || nn.parent() == ~0U )
        return -1; // No diffusion, bail out.
    const NeuroNode *pa = &nodes_[ nn.parent() ];
    double L1 = nn.getLength() / nn.getNumDivs();
    double L2 = L1;
    parentFid = i - 1;
    if ( nn.startFid() == i )
    {
        // We're at the start of the node, need to refer to parent for L
        const NeuroNode* realParent = pa;
        if ( pa->isDummyNode() )
        {
            if ( pa->parent() == ~0U )
            {
                parentFid = -1;
                return -1; // No diffusion, bail out.
            }
            assert( pa->parent() < nodes_.size() );
            realParent = &nodes_[ realParent->parent() ];
            if ( realParent->isDummyNode() )
            {
                // Still dummy. So we're at a terminus. No diffusion
                return -1;
            }
        }
        L2 = realParent->getLength() / realParent->getNumDivs();
        parentFid = realParent->startFid() +
                    realParent->getNumDivs() - 1;
    }
    assert( parentFid < nodeIndex_.size() );
    double length = 0.5 * (L1 + L2 );
    // Note that we use the parent node here even if it is a dummy.
    // It has the correct diameter.
    double adx = nn.getDiffusionArea( *pa, i - nn.startFid() ) / length;
    return adx;
}
References CylBase::getDiffusionArea(), CylBase::getLength(), CylBase::getNumDivs(), NeuroNode::isDummyNode(), nodeIndex_, nodes_, NeuroNode::parent(), and NeuroNode::startFid().
Referenced by buildStencil().
getCoordinates()
vector< double > NeuroMesh::getCoordinates (unsigned int fid) const virtual
Virtual function to return coords of mesh Entry.
Virtual function to return coords of mesh Entry. For Cylindrical mesh, coords are x1y1z1 x2y2z2 dia0 dia1 diffLength
Implements ChemCompt.
Definition at line 921 of file NeuroMesh.cpp.
{
    assert( fid < nodeIndex_.size() );
    assert( nodeIndex_[fid] < nodes_.size() );
    const NeuroNode& node = nodes_[ nodeIndex_[fid] ];
    assert( fid >= node.startFid() );
    assert ( node.parent() < nodes_.size() );
    const NeuroNode& parent = nodes_[ node.parent() ];
    return node.getCoordinates( parent, fid - node.startFid() );
}
References CylBase::getCoordinates(), nodeIndex_, nodes_, NeuroNode::parent(), and NeuroNode::startFid().
getDendVoxelsOnCompartment()
vector< unsigned int > NeuroMesh::getDendVoxelsOnCompartment (ObjId compt) const
Definition at line 783 of file NeuroMesh.cpp.
{
    vector< unsigned int > ret;
    for ( vector< NeuroNode >::const_iterator
            i = nodes_.begin(); i != nodes_.end(); ++i )
    {
        if ( !i->isDummyNode() && i->elecCompt() == compt.id )
        {
            for ( unsigned int j = 0; j < i->getNumDivs(); ++j )
            {
                ret.push_back( j + i->startFid() );
            }
        }
    }
    return ret;
}
References NeuroNode::elecCompt(), CylBase::getNumDivs(), ObjId::id, NeuroNode::isDummyNode(), nodes_, Id::operator==(), and NeuroNode::startFid().
Referenced by initCinfo().
getDiffLength()
double NeuroMesh::getDiffLength () const
Definition at line 403 of file NeuroMesh.cpp.
{
    return diffLength_;
}
References diffLength_.
Referenced by initCinfo().
getDiffusionArea()
vector< double > NeuroMesh::getDiffusionArea (unsigned int fid) const virtual
Virtual function to return diffusion X-section area.
Virtual function to return diffusion X-section area for each neighbor.
Implements ChemCompt.
Definition at line 934 of file NeuroMesh.cpp.
{
    assert( fid < nodeIndex_.size() );
    assert( nodeIndex_[fid] < nodes_.size() );
    const NeuroNode& node = nodes_[ nodeIndex_[fid] ];
    assert( fid >= node.startFid() );
    assert ( node.parent() < nodes_.size() );
    const NeuroNode& parent = nodes_[ node.parent() ];
    vector< double > ret;
    vector< unsigned int > neighbors = getNeighbors( fid );
    for ( unsigned int i = 0; i < neighbors.size(); ++i )
    {
        ret.push_back( node.getDiffusionArea( parent, neighbors[ i ] ) );
    }
    return ret;
}
References CylBase::getDiffusionArea(), MeshCompt::getNeighbors(), nodeIndex_, nodes_, NeuroNode::parent(), and NeuroNode::startFid().
getDiffusionScaling()
vector< double > NeuroMesh::getDiffusionScaling (unsigned int fid) const virtual
Virtual function to return scale factor for diffusion. 1 here.
Virtual function to return scale factor for diffusion. I think all dendite tips need to return just one entry of 1.
Implements ChemCompt.
Definition at line 954 of file NeuroMesh.cpp.
{
    /*
    if ( nodeIndex_.size() <= 1 )
    return vector< double >( 0 );
    if ( !isToroid_ && ( fid == 0 || fid == (nodeIndex_.size() - 1) ) )
    return vector< double >( 1, 1.0 );
    */
    return vector< double >( 2, 1.0 );
}
getElecComptList()
vector< Id > NeuroMesh::getElecComptList () const
Definition at line 736 of file NeuroMesh.cpp.
{
    vector< Id > ret;
    for ( vector< NeuroNode >::const_iterator
            i = nodes_.begin(); i != nodes_.end(); ++i )
    {
        if ( !i->isDummyNode() )
            ret.push_back( i->elecCompt() );
    }
    return ret;
}
References NeuroNode::elecCompt(), NeuroNode::isDummyNode(), and nodes_.
Referenced by getSubTree(), and initCinfo().
getElecComptMap()
vector< Id > NeuroMesh::getElecComptMap () const
Definition at line 724 of file NeuroMesh.cpp.
{
    vector< Id > ret( nodeIndex_.size() );
    for ( unsigned int i = 0; i < nodeIndex_.size(); ++i )
    {
        ret[i] = nodes_[nodeIndex_[i]].elecCompt();
        // cout << i << "   " << nodeIndex_[i] << " " << ret[i] << endl;
    }
    return ret;
}
References NeuroNode::elecCompt(), nodeIndex_, and nodes_.
Referenced by initCinfo().
getEndVoxelInCompt()
vector< unsigned int > NeuroMesh::getEndVoxelInCompt () const
Definition at line 760 of file NeuroMesh.cpp.
{
    vector< unsigned int > ret;
    for ( vector< NeuroNode >::const_iterator
            i = nodes_.begin(); i != nodes_.end(); ++i )
    {
        if ( !i->isDummyNode() )
            ret.push_back( i->startFid() + i->getNumDivs() );
    }
    return ret;
}
References CylBase::getNumDivs(), NeuroNode::isDummyNode(), nodes_, and NeuroNode::startFid().
Referenced by initCinfo().
getGeometryPolicy()
string NeuroMesh::getGeometryPolicy () const
Definition at line 434 of file NeuroMesh.cpp.
{
    return geometryPolicy_;
}
References geometryPolicy_.
Referenced by initCinfo().
getMeshDimensions()
unsigned int NeuroMesh::getMeshDimensions (unsigned int fid) const virtual
Virtual function to return dimensions of specified entry.
Implements ChemCompt.
Definition at line 898 of file NeuroMesh.cpp.
{
    return 3;
}
getMeshEntryVolume()
double NeuroMesh::getMeshEntryVolume (unsigned int fid) const virtual
Virtual function to return volume of mesh Entry.
Implements ChemCompt.
Definition at line 904 of file NeuroMesh.cpp.
{
    if ( nodeIndex_.size() == 0 )
        return 1.0; // A default value to use before init
    assert( fid < nodeIndex_.size() );
    assert( nodeIndex_[fid] < nodes_.size() );
    const NeuroNode& node = nodes_[ nodeIndex_[fid] ];
    assert( fid >= node.startFid() );
    if ( node.parent() == ~0U )
        return node.voxelVolume( node, fid - node.startFid() );
    assert ( node.parent() < nodes_.size() );
    const NeuroNode& parent = nodes_[ node.parent() ];
    return node.voxelVolume( parent, fid - node.startFid() );
}
References nodeIndex_, nodes_, NeuroNode::parent(), NeuroNode::startFid(), and CylBase::voxelVolume().
Referenced by extendedMeshEntryVolume(), and SpineMesh::matchNeuroMeshEntries().
getMeshType()
unsigned int NeuroMesh::getMeshType (unsigned int fid) const virtual
Virtual function to return MeshType of specified entry.
Implements ChemCompt.
Definition at line 887 of file NeuroMesh.cpp.
{
    assert( fid < nodeIndex_.size() );
    assert( nodeIndex_[fid] < nodes_.size() );
    if ( nodes_[ nodeIndex_[fid] ].isSphere() )
        return SPHERE_SHELL_SEG;
    return CYL;
}
References CYL, NeuroNode::isSphere(), nodeIndex_, nodes_, and SPHERE_SHELL_SEG.
getNodes()
const vector< NeuroNode > & NeuroMesh::getNodes () const
Definition at line 1240 of file NeuroMesh.cpp.
{
    return nodes_;
}
References nodes_.
getNumDiffCompts()
unsigned int NeuroMesh::getNumDiffCompts () const
Definition at line 714 of file NeuroMesh.cpp.
{
    return nodeIndex_.size();
}
References nodeIndex_.
Referenced by initCinfo().
getNumSegments()
unsigned int NeuroMesh::getNumSegments () const
Definition at line 705 of file NeuroMesh.cpp.
{
    unsigned int ret = 0;
    for ( vector< NeuroNode >::const_iterator i = nodes_.begin();
            i != nodes_.end(); ++i )
        ret += !i->isDummyNode();
    return ret;
}
References NeuroNode::isDummyNode(), and nodes_.
Referenced by initCinfo().
getParentVoxel()
vector< unsigned int > NeuroMesh::getParentVoxel () const virtual
Implements MeshCompt.
Definition at line 719 of file NeuroMesh.cpp.
{
    return parentVoxel_;
}
References parentVoxel_.
Referenced by initCinfo().
getSeparateSpines()
bool NeuroMesh::getSeparateSpines () const
Definition at line 700 of file NeuroMesh.cpp.
{
    return separateSpines_;
}
References separateSpines_.
Referenced by initCinfo().
getSpineVoxelOnDendVoxel()
vector< int > NeuroMesh::getSpineVoxelOnDendVoxel () const
Definition at line 772 of file NeuroMesh.cpp.
{
    vector< int > ret( nodeIndex_.size(), -1 ); //-1 means no spine present
    for ( unsigned int i = 0; i < parent_.size(); ++i )
    {
        assert( parent_[i] < ret.size() );
        ret[ parent_[i] ] = i;
    }
    return ret;
}
References nodeIndex_, and parent_.
Referenced by initCinfo().
getSpineVoxelsOnCompartment()
vector< unsigned int > NeuroMesh::getSpineVoxelsOnCompartment (ObjId compt) const
Definition at line 800 of file NeuroMesh.cpp.
{
    vector< unsigned int > ret;
    assert( shaft_.size() == head_.size() );
    for ( unsigned int i = 0; i < shaft_.size(); ++i )
    {
        if ( shaft_[i] == compt.id || head_[i] == compt.id )
            ret.push_back(i);
    }
    return ret;
}
References head_, ObjId::id, Id::operator==(), and shaft_.
Referenced by initCinfo().
getStartVoxelInCompt()
vector< unsigned int > NeuroMesh::getStartVoxelInCompt () const
Definition at line 748 of file NeuroMesh.cpp.
{
    vector< unsigned int > ret;
    for ( vector< NeuroNode >::const_iterator
            i = nodes_.begin(); i != nodes_.end(); ++i )
    {
        if ( !i->isDummyNode() )
            ret.push_back( i->startFid() );
    }
    return ret;
}
References NeuroNode::isDummyNode(), nodes_, and NeuroNode::startFid().
Referenced by initCinfo().
getSubTree()
vector< ObjId > NeuroMesh::getSubTree (const Eref & e) const
Definition at line 668 of file NeuroMesh.cpp.
{
    vector< Id > temp = getElecComptList();
    vector< ObjId > ret( temp.size() );
    for ( unsigned int i = 0; i < ret.size(); ++i )
        ret[i] = temp[i];
    return ret;
}
References getElecComptList().
Referenced by initCinfo().
getSubTreePath()
string NeuroMesh::getSubTreePath (const Eref & e) const
Definition at line 686 of file NeuroMesh.cpp.
{
    return subTreePath_;
}
References subTreePath_.
Referenced by initCinfo().
getVoxelArea()
const vector< double > & NeuroMesh::getVoxelArea () const virtual
Implements MeshCompt.
Definition at line 843 of file NeuroMesh.cpp.
{
    return area_;
}
References area_.
getVoxelLength()
const vector< double > & NeuroMesh::getVoxelLength () const virtual
Implements MeshCompt.
Definition at line 848 of file NeuroMesh.cpp.
{
    return length_;
}
References length_.
indexToSpace()
void NeuroMesh::indexToSpace (unsigned int index, double & x, double & y, double & z) const virtual
Converts specified index to xyz coords of middle of voxel Values out of range return original xyz
Implements ChemCompt.
Definition at line 1281 of file NeuroMesh.cpp.
{
    if ( index >= innerGetNumEntries() )
        return;
    const NeuroNode& nn = nodes_[ nodeIndex_[ index ] ];
    const NeuroNode& pa = nodes_[ nn.parent() ];
    Vec a( pa.getX(), pa.getY(), pa.getZ() );
    Vec b( nn.getX(), nn.getY(), nn.getZ() );
    double frac = ( ( index - nn.startFid() ) + 0.5 ) / nn.getNumDivs();
    Vec pt = a.pointOnLine( b, frac );
    x = pt.a0();
    y = pt.a1();
    z = pt.a2();
}
References Vec::a0(), Vec::a1(), Vec::a2(), CylBase::getNumDivs(), CylBase::getX(), CylBase::getY(), CylBase::getZ(), innerGetNumEntries(), nodeIndex_, nodes_, NeuroNode::parent(), Vec::pointOnLine(), NeuroNode::startFid(), and Vec::Vec().
initCinfo()
const Cinfo * NeuroMesh::initCinfo () static
Definition at line 64 of file NeuroMesh.cpp.
{
    // Field Definitions
    static ElementValueFinfo< NeuroMesh, vector< ObjId > > subTree(
        "subTree",
        "Set of compartments in which to embed chemical reaction "
        "systems. If the compartments happen to be contiguous"
        "then also set up diffusion between them. Can also"
        "handle cases where the same cell is divided into multiple"
        "non-diffusively-coupled compartments",
        &NeuroMesh::setSubTree,
        &NeuroMesh::getSubTree
    );
    static ElementValueFinfo< NeuroMesh, string > subTreePath(
        "subTreePath",
        "Set of compartments to model, defined as a path string. "
        "If they happen to be contiguous "
        "then also set up diffusion between the compartments. Can also"
        "handle cases where the same cell is divided into multiple"
        "non-diffusively-coupled compartments",
        &NeuroMesh::setSubTreePath,
        &NeuroMesh::getSubTreePath
    );
    static ValueFinfo< NeuroMesh, bool > separateSpines(
        "separateSpines",
        "Flag: when separateSpines is true, the traversal separates "
        "any compartment with the strings "
        "'spine', 'head', 'shaft' or 'neck' in its name,"
        "Allows to set up separate mesh for spines, based on the "
        "same cell model. Requires for the spineListOut message to"
        "be sent to the target SpineMesh object.",
        &NeuroMesh::setSeparateSpines,
        &NeuroMesh::getSeparateSpines
    );
    static ReadOnlyValueFinfo< NeuroMesh, unsigned int > numSegments(
        "numSegments",
        "Number of cylindrical/spherical segments in model",
        &NeuroMesh::getNumSegments
    );
    static ReadOnlyValueFinfo< NeuroMesh, unsigned int > numDiffCompts(
        "numDiffCompts",
        "Number of diffusive compartments in model",
        &NeuroMesh::getNumDiffCompts
    );
    static ReadOnlyValueFinfo< NeuroMesh, vector< unsigned int > > parentVoxel(
        "parentVoxel",
        "Vector of indices of parents of each voxel.",
        &NeuroMesh::getParentVoxel
    );
    static ReadOnlyValueFinfo< NeuroMesh, vector< Id > > elecComptMap(
        "elecComptMap",
        "Vector of Ids of electrical compartments that map to each "
        "voxel. This is necessary because the order of the IDs may "
        "differ from the ordering of the voxels. Additionally, there "
        "are typically many more voxels than there are electrical "
        "compartments. So many voxels point to the same elecCompt.",
        &NeuroMesh::getElecComptMap
    );
    static ReadOnlyValueFinfo< NeuroMesh, vector< Id > > elecComptList(
        "elecComptList",
        "Vector of Ids of all electrical compartments in this "
        "NeuroMesh. Ordering is as per the tree structure built in "
        "the NeuroMesh, and may differ from Id order. Ordering "
        "matches that used for startVoxelInCompt and endVoxelInCompt",
        &NeuroMesh::getElecComptList
    );
    static ReadOnlyValueFinfo< NeuroMesh, vector< unsigned int > > startVoxelInCompt(
        "startVoxelInCompt",
        "Index of first voxel that maps to each electrical "
        "compartment. Each elecCompt has one or more voxels. "
        "The voxels in a compartment are numbered sequentially.",
        &NeuroMesh::getStartVoxelInCompt
    );
    static ReadOnlyValueFinfo< NeuroMesh, vector< unsigned int > > endVoxelInCompt(
        "endVoxelInCompt",
        "Index of end voxel that maps to each electrical "
        "compartment. In keeping with C and Python convention, this "
        "is one more than the last voxel. "
        "Each elecCompt has one or more voxels. "
        "The voxels in a compartment are numbered sequentially.",
        &NeuroMesh::getEndVoxelInCompt
    );
    static ReadOnlyValueFinfo< NeuroMesh, vector< int > > spineVoxelOnDendVoxel(
        "spineVoxelOnDendVoxel",
        "Voxel index of spine voxel on each dend voxel. Assume that "
        "there is never more than one spine per dend voxel. If no "
        "spine present, the entry is -1. Note that the "
        "same index is used both for spine head and PSDs.",
        &NeuroMesh::getSpineVoxelOnDendVoxel
    );
    static ReadOnlyLookupValueFinfo< NeuroMesh, ObjId,
           vector< unsigned int > > dendVoxelsOnCompartment(
               "dendVoxelsOnCompartment",
               "Returns vector of all chem voxels on specified electrical "
               "compartment of the dendrite. Returns empty vec if none "
               "found, or if the compartment isn't on the dendrite.",
               &NeuroMesh::getDendVoxelsOnCompartment
           );
    static ReadOnlyLookupValueFinfo< NeuroMesh, ObjId,
           vector< unsigned int > > spineVoxelsOnCompartment(
               "spineVoxelsOnCompartment",
               "Returns vector of all chem voxels on specified electrical "
               "compartment, which should be a spine head or shaft . "
               "Returns empty vec if no chem voxels "
               "found, or if the compartment isn't on the dendrite. "
               "Note that spine and PSD voxel indices are the same for a "
               "given spine head.",
               &NeuroMesh::getSpineVoxelsOnCompartment
           );
    static ValueFinfo< NeuroMesh, double > diffLength(
        "diffLength",
        "Diffusive length constant to use for subdivisions. "
        "The system will"
        "attempt to subdivide cell using diffusive compartments of"
        "the specified diffusion lengths as a maximum."
        "In order to get integral numbers"
        "of compartments in each segment, it may subdivide more "
        "finely."
        "Uses default of 0.5 microns, that is, half typical lambda."
        "For default, consider a tau of about 1 second for most"
        "reactions, and a diffusion const of about 1e-12 um^2/sec."
        "This gives lambda of 1 micron",
        &NeuroMesh::setDiffLength,
        &NeuroMesh::getDiffLength
    );
    static ValueFinfo< NeuroMesh, string > geometryPolicy(
        "geometryPolicy",
        "Policy for how to interpret electrical model geometry (which "
        "is a branching 1-dimensional tree) in terms of 3-D constructs"
        "like spheres, cylinders, and cones."
        "There are three options, default, trousers, and cylinder:"
        "default mode:"
        " - Use frustrums of cones. Distal diameter is always from compt dia."
        " - For linear dendrites (no branching), proximal diameter is "
        " diameter of the parent compartment"
        " - For branching dendrites and dendrites emerging from soma,"
        " proximal diameter is from compt dia. Don't worry about overlap."
        " - Place somatic dendrites on surface of spherical soma, or at ends"
        " of cylindrical soma"
        " - Place dendritic spines on surface of cylindrical dendrites, not"
        " emerging from their middle."
        "trousers mode:"
        " - Use frustrums of cones. Distal diameter is always from compt dia."
        " - For linear dendrites (no branching), proximal diameter is "
        " diameter of the parent compartment"
        " - For branching dendrites, use a trouser function. Avoid overlap."
        " - For soma, use some variant of trousers. Here we must avoid overlap"
        " - For spines, use a way to smoothly merge into parent dend. Radius of"
        " curvature should be similar to that of the spine neck."
        " - Place somatic dendrites on surface of spherical soma, or at ends"
        " of cylindrical soma"
        " - Place dendritic spines on surface of cylindrical dendrites, not"
        " emerging from their middle."
        "cylinder mode:"
        " - Use cylinders. Diameter is just compartment dia."
        " - Place somatic dendrites on surface of spherical soma, or at ends"
        " of cylindrical soma"
        " - Place dendritic spines on surface of cylindrical dendrites, not"
        " emerging from their middle."
        " - Ignore spatial overlap.",
        &NeuroMesh::setGeometryPolicy,
        &NeuroMesh::getGeometryPolicy
    );
    // MsgDest Definitions
    // Field Elements
    static Finfo* neuroMeshFinfos[] =
    {
        &subTree,       // Value
        &subTreePath,       // Value
        &separateSpines,    // Value
        &numSegments,       // ReadOnlyValue
        &numDiffCompts,     // ReadOnlyValue
        &parentVoxel,           // ReadOnlyValue
        &elecComptList,         // ReadOnlyValue
        &elecComptMap,          // ReadOnlyValue
        &startVoxelInCompt,         // ReadOnlyValue
        &endVoxelInCompt,           // ReadOnlyValue
        &spineVoxelOnDendVoxel,     // ReadOnlyValue
        &dendVoxelsOnCompartment,   // ReadOnlyLookupValue
        &spineVoxelsOnCompartment,  // ReadOnlyLookupValue
        &diffLength,            // Value
        &geometryPolicy,        // Value
        spineListOut(),         // SrcFinfo
        psdListOut(),           // SrcFinfo
    };
    static Dinfo< NeuroMesh > dinfo;
    static Cinfo neuroMeshCinfo (
        "NeuroMesh",
        ChemCompt::initCinfo(),
        neuroMeshFinfos,
        sizeof( neuroMeshFinfos ) / sizeof ( Finfo* ),
        &dinfo
    );
    return &neuroMeshCinfo;
}
References Cinfo::Cinfo(), ElementValueFinfo< T, F >::ElementValueFinfo(), getDendVoxelsOnCompartment(), getDiffLength(), getElecComptList(), getElecComptMap(), getEndVoxelInCompt(), getGeometryPolicy(), getNumDiffCompts(), getNumSegments(), getParentVoxel(), getSeparateSpines(), getSpineVoxelOnDendVoxel(), getSpineVoxelsOnCompartment(), getStartVoxelInCompt(), getSubTree(), getSubTreePath(), ChemCompt::initCinfo(), psdListOut(), ReadOnlyLookupValueFinfo< T, L, F >::ReadOnlyLookupValueFinfo(), ReadOnlyValueFinfo< T, F >::ReadOnlyValueFinfo(), setDiffLength(), setGeometryPolicy(), setSeparateSpines(), setSubTree(), setSubTreePath(), spineListOut(), and ValueFinfo< T, F >::ValueFinfo().
innerBuildDefaultMesh()
void NeuroMesh::innerBuildDefaultMesh (const Eref & e, double size, unsigned int numEntries) virtual
Virtual func to make a mesh with specified size and numEntries.
This is a bit odd, effectively asks to build an imaginary neuron and then subdivide it. I'll make do with a ball-and-stick model: Soma with a single apical dendrite with reasonable diameter. I will interpret size as total length of neuron, not as volume. Soma will have a diameter of up to 20 microns, anything bigger than this is treated as soma of 20 microns + dendrite of (specified length - 10 microns) for radius of soma. This means we avoid having miniscule dendrites protruding from soma, the shortest one will be 10 microns.
Implements ChemCompt.
Definition at line 1076 of file NeuroMesh.cpp.
{
    if ( size > 10e-3 )
    {
        cout << "Warning: attempt to build a neuron of dendritic length " <<
             size << " metres.\n Seems improbable.\n" <<
             "Using default of 0.001 m\n";
        size = 1e-3;
    }
    diffLength_ = size / numEntries;
    vector< unsigned int > noChildren( 0 );
    vector< unsigned int > oneChild( 1, 2 );
    if ( size < 20e-6 )
    {
        CylBase cb( 0, 0, 0, size, 0, numEntries );
        NeuroNode soma( cb, 0, noChildren, 0, Id(), true );
        nodes_.resize( 1, soma );
        nodeIndex_.resize( 1, 0 );
    }
    else
    {
        CylBase cb( 0, 0, 0, 20e-6, 0, 1 );
        NeuroNode soma( cb, 0, oneChild, 0, Id(), true );
        nodes_.resize( 1, soma );
        nodeIndex_.resize( 1, 0 );
        CylBase cbDummy( 0, 0, 10e-6, 4e-6, 0, 0 );
        NeuroNode dummy( cbDummy, 0, noChildren, 1, Id(), false );
        nodes_.push_back( dummy );
        CylBase cbDend( 0, 0, size, 2e-6, size - 10e-6, numEntries - 1);
        NeuroNode dend( cbDend, 1, noChildren, 2, Id(), false );
        nodes_.push_back( dend );
        for ( unsigned int i = 1; i < numEntries; ++i )
            nodeIndex_.push_back( 2 );
    }
    updateCoords();
}
References CylBase::CylBase(), diffLength_, Id::Id(), NeuroNode::NeuroNode(), nodeIndex_, nodes_, and updateCoords().
innerGetDimensions()
unsigned int NeuroMesh::innerGetDimensions () const virtual
Implements ChemCompt.
Definition at line 439 of file NeuroMesh.cpp.
{
    return 3;
}
innerGetNumEntries()
unsigned int NeuroMesh::innerGetNumEntries () const virtual
Inherited virtual func. Returns number of MeshEntry in array
Implements ChemCompt.
Definition at line 1028 of file NeuroMesh.cpp.
{
    return nodeIndex_.size();
}
References nodeIndex_.
Referenced by indexToSpace().
innerHandleNodeInfo()
void NeuroMesh::innerHandleNodeInfo (const Eref & e, unsigned int numNodes, unsigned int numThreads) virtual
Implements ChemCompt.
Definition at line 999 of file NeuroMesh.cpp.
{
    /*
    unsigned int numEntries = nodeIndex_.size();
    vector< double > vols( numEntries, 0.0 );
    double oldVol = getMeshEntryVolume( 0 );
    for ( unsigned int i = 0; i < numEntries; ++i ) {
    assert( nodeIndex_[i] < nodes_.size() );
    NeuroNode& node = nodes_[ nodeIndex_[i] ];
    assert( nodes_.size() > node.parent() );
    NeuroNode& parent = nodes_[ node.parent() ];
    vols[i] = node.voxelVolume( parent, i );
    }
    vector< unsigned int > localEntries( numEntries );
    vector< vector< unsigned int > > outgoingEntries;
    vector< vector< unsigned int > > incomingEntries;
    meshSplit()->send( e,
    oldVol,
    vols, localEntries,
    outgoingEntries, incomingEntries );
    */
}
innerHandleRequestMeshStats()
void NeuroMesh::innerHandleRequestMeshStats (const Eref & e, const SrcFinfo2< unsigned int, vector< double > > * meshStatsFinfo)
innerSetNumEntries()
void NeuroMesh::innerSetNumEntries (unsigned int n) virtual
Inherited virtual func.
Inherited virtual func. Assigns number of MeshEntries. This one doesn't set exact number, because each compartment has to fit integral numbers of voxels.
Implements ChemCompt.
Definition at line 1038 of file NeuroMesh.cpp.
{
    static const unsigned int WayTooLarge = 1000000;
    if ( n == 0 || n > WayTooLarge )
    {
        cout << "Warning: NeuroMesh::innerSetNumEntries( " << n <<
             " ): out of range\n";
        return;
    }
    double totalLength = 0;
    for ( vector< NeuroNode >::iterator i = nodes_.begin();
            i != nodes_.end(); ++i )
    {
        if ( !i->isDummyNode() )
        {
            if ( i->isSphere() )
                totalLength += i->getDia();
            else
                totalLength += i->getLength();
        }
    }
    assert( totalLength > 0 );
    diffLength_ = totalLength / n;
    updateCoords();
}
References diffLength_, CylBase::getDia(), CylBase::getLength(), NeuroNode::isDummyNode(), NeuroNode::isSphere(), nodes_, and updateCoords().
insertDummyNodes()
void NeuroMesh::insertDummyNodes ()
Puts in all the required dummy nodes for the tree.
Definition at line 528 of file NeuroMesh.cpp.
{
    // First deal with the soma, always positioned at node 0.
    unsigned int num = nodes_.size();
    for ( unsigned int i = 0; i < num; ++i )
    {
        if ( nodes_[i].parent() == ~0U )
        {
            Id elec = nodes_[i].elecCompt();
            double x = Field< double >::get( elec, "x0" );
            double y = Field< double >::get( elec, "y0" );
            double z = Field< double >::get( elec, "z0" );
            insertSingleDummy( ~0U, i, x, y, z );
        }
    }
    // Second pass: insert dummy nodes for children.
    // Need to know if parent has multiple children, because each of
    // them will need a dummyNode to connect to.
    // In all the policies so far, the dummy nodes take the same diameter
    // as the children that they host.
    for ( unsigned int i = 0; i < nodes_.size(); ++i )
    {
        vector< unsigned int > kids = nodes_[i].children();
        if ( (!nodes_[i].isDummyNode()) && kids.size() > 1 )
        {
            for( unsigned int j = 0; j < kids.size(); ++j )
            {
                double x = nodes_[i].getX(); // use coords of parent.
                double y = nodes_[i].getY();
                double z = nodes_[i].getZ();
                insertSingleDummy( i, kids[j], x, y, z );
                // Replace the old kid entry with the dummy
                kids[j] = nodes_.size() - 1;
            }
            // Connect up the parent to the dummy nodes.
            nodes_[i].clearChildren();
            for( unsigned int j = 0; j < kids.size(); ++j )
                nodes_[i].addChild( kids[j] );
        }
    }
}
References NeuroNode::addChild(), NeuroNode::children(), NeuroNode::clearChildren(), NeuroNode::elecCompt(), Field< A >::get(), CylBase::getX(), CylBase::getY(), CylBase::getZ(), insertSingleDummy(), NeuroNode::isDummyNode(), nodes_, and NeuroNode::parent().
Referenced by setSubTree().
insertSingleDummy()
void NeuroMesh::insertSingleDummy (unsigned int parent, unsigned int self, double x, double y, double z)
Puts in a dummy node between parent and self. Used to set up the correct size of proximal compartments.
Definition at line 501 of file NeuroMesh.cpp.
{
    static const double EPSILON = 1e-8;
    NeuroNode dummy( nodes_[ self ] );
    dummy.clearChildren();
    dummy.setNumDivs( 0 );
    bool isCylinder = (geometryPolicy_ == "cylinder" );
    dummy.setIsCylinder( isCylinder );
    dummy.setX( x );
    dummy.setY( y );
    dummy.setZ( z );
    // Now insert the dummy as a surrogate parent.
    dummy.setParent( parent );
    dummy.addChild( self );
    nodes_[ self ].setParent( nodes_.size() );
    // Idiot check for a bad dimensioned compartment.
    if ( nodes_[self].calculateLength( dummy ) < EPSILON )
    {
        double length = nodes_[self].getLength();
        dummy.setX( x - length );
        assert( doubleEq( nodes_[self].calculateLength( dummy ), length) );
    }
    nodes_.push_back( dummy );
}
References NeuroNode::addChild(), NeuroNode::calculateLength(), NeuroNode::clearChildren(), doubleEq(), geometryPolicy_, CylBase::getLength(), nodes_, CylBase::setIsCylinder(), CylBase::setNumDivs(), NeuroNode::setParent(), CylBase::setX(), CylBase::setY(), and CylBase::setZ().
Referenced by insertDummyNodes().
matchCubeMeshEntries()
void NeuroMesh::matchCubeMeshEntries (const ChemCompt * other, vector< VoxelJunction > & ret) const
Definition at line 1327 of file NeuroMesh.cpp.
{
    for( unsigned int i = 0; i < nodes_.size(); ++i )
    {
        const NeuroNode& nn = nodes_[i];
        if ( !nn.isDummyNode() )
        {
            assert( nn.parent() < nodes_.size() );
            const NeuroNode& pa = nodes_[ nn.parent() ];
            nn.matchCubeMeshEntries( other, pa, nn.startFid(),
                                     surfaceGranularity_, ret, true, false );
        }
    }
}
References NeuroNode::isDummyNode(), CylBase::matchCubeMeshEntries(), nodes_, NeuroNode::parent(), NeuroNode::startFid(), and surfaceGranularity_.
Referenced by matchMeshEntries().
matchMeshEntries()
void NeuroMesh::matchMeshEntries (const ChemCompt * other, vector< VoxelJunction > & ret) const virtual
Returns the meshIndices (NOT spatial indices) of all adjacent mesh entry pairs on ether side of the (self, other) junction. meshIndices are the indices that look up entries in the vector of pools. spatialIndices are (iz * ny + iy) * nx + ix, that is, a linear conversion of cartesian spatial indices. So, for two touching cubes, the return vector is the paired meshIndices on either side of the plane of contact. If one mesh has a finer mesh than the other, or if there are more than one contact points from self to other (for example, at a corner), then we just have multiple pairs using the same meshIndex of the repeated voxel.
Implements ChemCompt.
Definition at line 1249 of file NeuroMesh.cpp.
{
    const CubeMesh* cm = dynamic_cast< const CubeMesh* >( other );
    if ( cm )
    {
        matchCubeMeshEntries( other, ret );
        return;
    }
    const EndoMesh* em = dynamic_cast< const EndoMesh* >( other );
    if ( em )
    {
        em->matchMeshEntries( this, ret );
        flipRet( ret );
        return;
    }
    const SpineMesh* sm = dynamic_cast< const SpineMesh* >( other );
    if ( sm )
    {
        sm->matchNeuroMeshEntries( this, ret );
        flipRet( ret );
        return;
    }
    const NeuroMesh* nm = dynamic_cast< const NeuroMesh* >( other );
    if ( nm )
    {
        matchNeuroMeshEntries( other, ret );
        return;
    }
    cout << "Warning: NeuroMesh::matchMeshEntries: unknown class\n";
}
References ChemCompt::flipRet(), matchCubeMeshEntries(), EndoMesh::matchMeshEntries(), matchNeuroMeshEntries(), and SpineMesh::matchNeuroMeshEntries().
matchNeuroMeshEntries()
void NeuroMesh::matchNeuroMeshEntries (const ChemCompt * other, vector< VoxelJunction > & ret) const
Definition at line 1343 of file NeuroMesh.cpp.
{
}
Referenced by matchMeshEntries().
nearest()
double NeuroMesh::nearest (double x, double y, double z, unsigned int & index) const virtual
This works a little different from other subclass versions of the function. It finds the index of the mesh entry whose centre is closest to the specified coords, and returns the distance to the centre. Doesn't worry about whether this distance is inside or outside cell.
Implements ChemCompt.
Definition at line 1297 of file NeuroMesh.cpp.
{
    double best = 1e12;
    index = 0;
    for( unsigned int i = 0; i < nodes_.size(); ++i )
    {
        const NeuroNode& nn = nodes_[i];
        if ( !nn.isDummyNode() )
        {
            assert( nn.parent() < nodes_.size() );
            const NeuroNode& pa = nodes_[ nn.parent() ];
            double linePos;
            double r;
            double near = nn.nearest( x, y, z, pa, linePos, r );
            if ( linePos >= 0 && linePos < 1.0 )
            {
                if ( best > near )
                {
                    best = near;
                    index = static_cast<unsigned int>(linePos * nn.getNumDivs() + nn.startFid());
                }
            }
        }
    }
    if ( best == 1e12 )
        return -1;
    return best;
}
References CylBase::getNumDivs(), NeuroNode::isDummyNode(), CylBase::nearest(), nodes_, NeuroNode::parent(), and NeuroNode::startFid().
operator=()
NeuroMesh & NeuroMesh::operator= (const NeuroMesh & other)
Definition at line 314 of file NeuroMesh.cpp.
{
    nodes_ = other.nodes_;
    nodeIndex_ = other.nodeIndex_;
    vs_ = other.vs_;
    area_ = other.area_;
    length_ = other.length_;
    diffLength_ = other.diffLength_;
    separateSpines_ = other.separateSpines_;
    geometryPolicy_ = other.geometryPolicy_;
    return *this;
}
References area_, diffLength_, geometryPolicy_, length_, nodeIndex_, nodes_, separateSpines_, and vs_.
putSomaAtStart()
Id NeuroMesh::putSomaAtStart (Id origSoma, unsigned int maxDiaIndex)
This shuffles the nodes_ vector to put soma node at the start.
Definition at line 466 of file NeuroMesh.cpp.
{
    Id soma = origSoma;
    if ( nodes_[maxDiaIndex].elecCompt() == soma )   // Happy, happy
    {
        ;
    }
    else if ( soma == Id() )
    {
        soma = nodes_[maxDiaIndex].elecCompt();
    }
    else     // Disagreement. Ugh.
    {
        string name = nodes_[ maxDiaIndex ].elecCompt().element()->getName();
        // OK, somehow this model has more than one soma compartment.
        if ( moose::strncasecmp( name.c_str(), "soma", 4 ) == 0 )
        {
            soma = nodes_[maxDiaIndex].elecCompt();
        }
        else
        {
            cout << "Warning: NeuroMesh::putSomaAtStart: named 'soma' compartment isn't biggest\n";
            soma = nodes_[maxDiaIndex].elecCompt();
        }
    }
    // Move soma to start of nodes_ vector.
    if ( maxDiaIndex != 0 )
    {
        NeuroNode temp = nodes_[0];
        nodes_[0] = nodes_[maxDiaIndex];
        nodes_[maxDiaIndex] = temp;
    }
    return soma;
}
References NeuroNode::elecCompt(), Id::element(), Element::getName(), Id::Id(), nodes_, Id::operator==(), and moose::strncasecmp().
setDiffLength()
void NeuroMesh::setDiffLength (double v)
Definition at line 397 of file NeuroMesh.cpp.
{
    diffLength_ = v;
    updateCoords();
}
References diffLength_, and updateCoords().
Referenced by initCinfo().
setGeometryPolicy()
void NeuroMesh::setGeometryPolicy (string v)
Definition at line 408 of file NeuroMesh.cpp.
{
    // STL magic! Converts the string v to lower case. Unfortunately
    // someone has overloaded tolower so it can have one or two args, so
    // this marvellous construct is useless.
    // std::transform( v.begin(), v.end(), v.begin(), std::tolower );
    for( string::iterator i = v.begin(); i != v.end(); ++i )
        *i = tolower( *i );
    if ( !( v == "cylinder" || v == "trousers" || v == "default" ) )
    {
        cout << "Warning: NeuroMesh::setGeometryPolicy( " << v <<
             " ):\n Mode must be one of cylinder, trousers, or default."
             "Using default\n";
        v = "default";
    }
    if ( v == geometryPolicy_ )
        return;
    geometryPolicy_ = v;
    bool isCylinder = ( v == "cylinder" );
    for ( vector< NeuroNode >::iterator
            i = nodes_.begin(); i != nodes_.end(); ++i )
        i->setIsCylinder( isCylinder );
}
References geometryPolicy_, nodes_, and CylBase::setIsCylinder().
Referenced by initCinfo().
setSeparateSpines()
void NeuroMesh::setSeparateSpines (bool v)
Flag. True if NeuroMesh should configure a separate SpineMesh. The process is that both the NeuroMesh and SpineMesh should have been created, and a spineList message sent from the NeuroMesh to the SpineMesh. This may cascade down to PsdMesh.
Definition at line 691 of file NeuroMesh.cpp.
{
    if ( v != separateSpines_ )
    {
        separateSpines_ = v;
        updateCoords();
    }
}
References separateSpines_, and updateCoords().
Referenced by initCinfo().
setSubTree()
void NeuroMesh::setSubTree (const Eref & e, vector< ObjId > compartments)
The SubTree is a set of compartments to model. The first entry is the root of the tree, closest to the soma. The system does handle non-contiguous sets.
Definition at line 648 of file NeuroMesh.cpp.
{
    sort( compts.begin(), compts.end() );
    if ( separateSpines_ )
    {
        NeuroNode::buildSpinyTree( compts, nodes_, shaft_, head_, parent_);
        insertDummyNodes();
        updateCoords();
        updateShaftParents();
        transmitSpineInfo( e );
    }
    else
    {
        NeuroNode::buildTree( nodes_, compts );
        insertDummyNodes();
        updateCoords();
    }
    subTreePath_ = "Undefined: subTree set as a compartment list";
}
References NeuroNode::buildSpinyTree(), NeuroNode::buildTree(), head_, insertDummyNodes(), nodes_, parent_, separateSpines_, shaft_, subTreePath_, transmitSpineInfo(), updateCoords(), and updateShaftParents().
Referenced by initCinfo(), and setSubTreePath().
setSubTreePath()
void NeuroMesh::setSubTreePath (const Eref & e, string path)
This overloaded function sets up a presumed contiguous set of compartments, complains if they are not contiguous due to the check in NeuroNode::traverse.
The 'path' argument specifies a wildcard list of compartments, which can be also a comma-separated explicit list. Does not have to be in any particular order.
Definition at line 678 of file NeuroMesh.cpp.
{
    vector< ObjId > compts;
    wildcardFind( path, compts );
    setSubTree( e, compts );
    subTreePath_ = path;
}
References setSubTree(), subTreePath_, and wildcardFind().
Referenced by initCinfo().
transmitSpineInfo()
void NeuroMesh::transmitSpineInfo (const Eref & e)
Transmits the information about spines to SpineMesh and PsdMesh.
Definition at line 589 of file NeuroMesh.cpp.
{
    spineListOut()->send( e, shaft_, head_, parent_ );
    vector< double > ret;
    vector< double > psdCoords;
    vector< unsigned int > index( head_.size(), 0 );
    if ( e.element()->hasMsgs( psdListOut()->getBindIndex() ) )
    {
        // Later can refine to deal with spineless PSDs.
        for ( unsigned int i = 0; i < head_.size(); ++i )
        {
            SpineEntry se =
                SpineEntry( shaft_[i], head_[i], parent_[i] );
            ret = se.psdCoords();
            assert( ret.size() == 8 );
            psdCoords.insert( psdCoords.end(), ret.begin(), ret.end() );
            index[i] = i;
        }
        // ids.clear();
        // e.element()->getNeighbors( ids, psdListOut() );
        psdListOut()->send( e, psdCoords, head_, index );
    }
}
References Eref::element(), SrcFinfo::getBindIndex(), Element::hasMsgs(), head_, parent_, SpineEntry::psdCoords(), psdListOut(), SrcFinfo3< T1, T2, T3 >::send(), shaft_, SpineEntry::SpineEntry(), and spineListOut().
Referenced by setSubTree().
updateCoords()
void NeuroMesh::updateCoords ()
Recomputes all local coordinate and meshing data following a change in any of the coord parameters
This assumes that lambda is the quantity to preserve, over numEntries. So when the compartment changes size, so does numEntries. Assumes that the soma node is at index 0.
Definition at line 341 of file NeuroMesh.cpp.
{
    unsigned int startFid = 0;
    if ( nodes_.size() <= 1 ) // One for soma and one for dummy pa of soma
    {
        buildStencil();
        return;
    }
    for ( vector< NeuroNode >::iterator i = nodes_.begin();
            i != nodes_.end(); ++i )
    {
        if ( !i->isDummyNode() )
        {
            double len = i->getLength();
            unsigned int numDivs = static_cast<unsigned int>(floor( 0.5 + len / diffLength_ ));
            if ( numDivs < 1 )
                numDivs = 1;
            i->setNumDivs( numDivs );
            i->setStartFid( startFid );
            startFid += numDivs;
        }
    }
    nodeIndex_.resize( startFid );
    for ( unsigned int i = 0; i < nodes_.size(); ++i )
    {
        if ( !nodes_[i].isDummyNode() )
        {
            unsigned int end = nodes_[i].startFid() +nodes_[i].getNumDivs();
            assert( end <= startFid );
            assert( nodes_[i].getNumDivs() > 0 );
            for ( unsigned int j = nodes_[i].startFid(); j < end; ++j )
                nodeIndex_[j] = i;
        }
    }
    // Assign volumes and areas
    vs_.resize( startFid );
    area_.resize( startFid );
    length_.resize( startFid );
    for ( unsigned int i = 0; i < nodes_.size(); ++i )
    {
        const NeuroNode& nn = nodes_[i];
        if ( !nn.isDummyNode() )
        {
            assert( nn.parent() < nodes_.size() );
            const NeuroNode& parent = nodes_[ nn.parent() ];
            for ( unsigned int j = 0; j < nn.getNumDivs(); ++j )
            {
                vs_[j + nn.startFid()] = nn.voxelVolume( parent, j );
                area_[j + nn.startFid()] = nn.getMiddleArea( parent, j);
                length_[j + nn.startFid()] = nn.getVoxelLength();
            }
        }
    }
    buildStencil();
}
References area_, buildStencil(), diffLength_, CylBase::getLength(), CylBase::getMiddleArea(), CylBase::getNumDivs(), CylBase::getVoxelLength(), NeuroNode::isDummyNode(), length_, nodeIndex_, nodes_, NeuroNode::parent(), CylBase::setNumDivs(), NeuroNode::setStartFid(), NeuroNode::startFid(), CylBase::voxelVolume(), and vs_.
Referenced by innerBuildDefaultMesh(), innerSetNumEntries(), setDiffLength(), setSeparateSpines(), and setSubTree().
updateShaftParents()
void NeuroMesh::updateShaftParents ()
converts the parents_ vector from identifying the parent NeuroNode to identifying the parent voxel, for each shaft entry.
Definition at line 618 of file NeuroMesh.cpp.
{
    assert( shaft_.size() == parent_.size() );
    vector< unsigned int > pa = parent_;
    for ( unsigned int i = 0; i < shaft_.size(); ++i )
    {
        const NeuroNode& nn = nodes_[ pa[i] ];
        double x0 = Field< double >::get( shaft_[i], "x0" );
        double y0 = Field< double >::get( shaft_[i], "y0" );
        double z0 = Field< double >::get( shaft_[i], "z0" );
        const NeuroNode& pn = nodes_[ nn.parent() ];
        unsigned int index = 0;
        double r = nn.nearest( x0, y0, z0, pn, index );
        if ( r >= 0.0 )
        {
            parent_[i] = index + nn.startFid();
        }
        else
        {
            cout << "Warning: NeuroMesh::updateShaftParents: may be"
                 " misaligned on " << i << ", r=" << r <<
                 "\n pt=(" << x0 << "," << y0 << "," << z0 << ")" <<
                 "pa=(" << nn.getX() << "," << nn.getY() << "," << nn.getZ() << ")" <<
                 "\n";
            parent_[i] = index + nn.startFid();
        }
    }
}
References Field< A >::get(), CylBase::getX(), CylBase::getY(), CylBase::getZ(), CylBase::nearest(), nodes_, NeuroNode::parent(), parent_, shaft_, and NeuroNode::startFid().
Referenced by setSubTree().
vGetEntireVolume()
double NeuroMesh::vGetEntireVolume () const virtual
Inherited virtual func. Returns volume of soma and whole dendritic tree of neuron, excluding spines. Any axonal compartments are also included.
Implements ChemCompt.
Definition at line 853 of file NeuroMesh.cpp.
{
    double ret = 0.0;
    for ( vector< double >::const_iterator i =
                vs_.begin(); i != vs_.end(); ++i )
        ret += *i;
    return ret;
}
References vs_.
vGetVoxelMidpoint()
const vector< double > & NeuroMesh::vGetVoxelMidpoint () const virtual
Virtual func so that derived classes can return voxel midpoint.
Implements ChemCompt.
Definition at line 817 of file NeuroMesh.cpp.
{
    static vector< double > midpoint;
    unsigned int num = vs_.size();
    midpoint.resize( num * 3 );
    vector< double >::iterator k = midpoint.begin();
    for ( unsigned int i = 0; i < nodes_.size(); ++i )
    {
        const NeuroNode& nn = nodes_[i];
        if ( !nn.isDummyNode() )
        {
            assert( nn.parent() < nodes_.size() );
            const NeuroNode& parent = nodes_[ nn.parent() ];
            for ( unsigned int j = 0; j < nn.getNumDivs(); ++j )
            {
                vector< double > coords = nn.getCoordinates( parent, j );
                *k = ( coords[0] + coords[3] ) / 2.0;
                *(k + num ) = ( coords[1] + coords[4] ) / 2.0;
                *(k + 2 * num ) = ( coords[2] + coords[5] ) / 2.0;
                k++;
            }
        }
    }
    return midpoint;
}
References CylBase::getCoordinates(), CylBase::getNumDivs(), NeuroNode::isDummyNode(), nodes_, NeuroNode::parent(), and vs_.
vGetVoxelVolume()
const vector< double > & NeuroMesh::vGetVoxelVolume () const virtual
Virtual func so that derived classes can pass voxel volume back.
Implements ChemCompt.
Definition at line 812 of file NeuroMesh.cpp.
{
    return vs_;
}
References vs_.
vSetVolumeNotRates()
bool NeuroMesh::vSetVolumeNotRates (double volume) virtual
Inherited virtual func. In the NeuroMesh this carries out a rescaling on all dimensions. The length and diameter of each compartment are scaled by the same factor = volscale^(1/3) The rescaling carries through to the spines and PSDs, which are also updated. They are not permitted to change their own volumes.
Implements ChemCompt.
Definition at line 862 of file NeuroMesh.cpp.
{
    assert( parentVoxel_.size() == nodeIndex_.size() );
    assert( parentVoxel_.size() == 1 );
    assert( vs_.size() == 1 );
    if ( parentVoxel_.size() > 1 ) // Can't handle multicompartments yet.
        return false;
    NeuroNode& n = nodes_[0];
    double oldvol = n.volume( nodes_[0] );
    double scale = pow( volume / oldvol, 1.0/3.0 );
    n.setLength( n.getLength() * scale );
    n.setDia( n.getDia() * scale );
    vs_[0] *= volume / oldvol;
    area_[0] *= scale * scale;
    length_[0] *= scale;
    diffLength_ = length_[0];
    return true;
}
References area_, diffLength_, CylBase::getDia(), CylBase::getLength(), length_, nodeIndex_, nodes_, parentVoxel_, CylBase::setDia(), CylBase::setLength(), CylBase::volume(), and vs_.
Member Data Documentation
area_
vector< double > NeuroMesh::area_ private
Mesh junction area pre-calculations for each MeshEntry. This is the cross-section area of the middle of each voxel.
Definition at line 300 of file NeuroMesh.h.
Referenced by getVoxelArea(), NeuroMesh(), operator=(), updateCoords(), and vSetVolumeNotRates().
diffLength_
double NeuroMesh::diffLength_ private
Definition at line 306 of file NeuroMesh.h.
Referenced by getDiffLength(), innerBuildDefaultMesh(), innerSetNumEntries(), NeuroMesh(), NeuroMesh(), operator=(), setDiffLength(), updateCoords(), and vSetVolumeNotRates().
geometryPolicy_
string NeuroMesh::geometryPolicy_ private
Definition at line 316 of file NeuroMesh.h.
Referenced by getGeometryPolicy(), insertSingleDummy(), NeuroMesh(), NeuroMesh(), operator=(), and setGeometryPolicy().
head_
vector< Id > NeuroMesh::head_ private
Id of shaft compartment.
Definition at line 330 of file NeuroMesh.h.
Referenced by filterSpines(), getSpineVoxelsOnCompartment(), setSubTree(), and transmitSpineInfo().
length_
vector< double > NeuroMesh::length_ private
Pre-calculation of length of each MeshEntry.
Definition at line 303 of file NeuroMesh.h.
Referenced by getVoxelLength(), NeuroMesh(), operator=(), updateCoords(), and vSetVolumeNotRates().
nodeIndex_
vector< unsigned int > NeuroMesh::nodeIndex_ private
nodeIndex_[fid_for_MeshEntry]. Looks up index of NeuroNode from the fid of each MeshEntry. In other words, node# = nodeIndex_[ voxel# ]. This is needed because there are typically many voxels in each electrical compartment of the neuron. The nodes_ map closely to the electrical compartments.
Definition at line 287 of file NeuroMesh.h.
Referenced by buildStencil(), extendedMeshEntryVolume(), getAdx(), getCoordinates(), getDiffusionArea(), getElecComptMap(), getMeshEntryVolume(), getMeshType(), getNumDiffCompts(), getSpineVoxelOnDendVoxel(), indexToSpace(), innerBuildDefaultMesh(), innerGetNumEntries(), NeuroMesh(), operator=(), updateCoords(), and vSetVolumeNotRates().
nodes_
vector< NeuroNode > NeuroMesh::nodes_ private
Array of geometry specifiers for each segment of the neuronal model. Includes information equivalent to the CylMesh, as well as information to tie the node back to the original 'compartment' from the neuronal model.
Definition at line 270 of file NeuroMesh.h.
Referenced by getAdx(), getCoordinates(), getDendVoxelsOnCompartment(), getDiffusionArea(), getElecComptList(), getElecComptMap(), getEndVoxelInCompt(), getMeshEntryVolume(), getMeshType(), getNodes(), getNumSegments(), getStartVoxelInCompt(), indexToSpace(), innerBuildDefaultMesh(), innerSetNumEntries(), insertDummyNodes(), insertSingleDummy(), matchCubeMeshEntries(), nearest(), NeuroMesh(), operator=(), putSomaAtStart(), setGeometryPolicy(), setSubTree(), updateCoords(), updateShaftParents(), vGetVoxelMidpoint(), and vSetVolumeNotRates().
parent_
vector< unsigned int > NeuroMesh::parent_ private
Id of head compartment.
Definition at line 331 of file NeuroMesh.h.
Referenced by getSpineVoxelOnDendVoxel(), setSubTree(), transmitSpineInfo(), and updateShaftParents().
parentVoxel_
vector< unsigned int > NeuroMesh::parentVoxel_ private
Index of parent voxel of spines.
Index of parent voxel of each voxel. The root voxel has a parent of -1.
Definition at line 336 of file NeuroMesh.h.
Referenced by buildStencil(), getParentVoxel(), NeuroMesh(), and vSetVolumeNotRates().
separateSpines_
bool NeuroMesh::separateSpines_ private
Max permitted length constant for diffusion.
Flag. True if NeuroMesh should configure a separate SpineMesh. The process is that both the NeuroMesh and SpineMesh should have been created, and a spineList message sent from the NeuroMesh to the SpineMesh.
Definition at line 314 of file NeuroMesh.h.
Referenced by getSeparateSpines(), NeuroMesh(), NeuroMesh(), operator=(), setSeparateSpines(), and setSubTree().
shaft_
vector< Id > NeuroMesh::shaft_ private
The shaft vector and the matching head vector track the dendritic spines. The parent is the voxel to which the spine is attached.
Definition at line 329 of file NeuroMesh.h.
Referenced by filterSpines(), getSpineVoxelsOnCompartment(), setSubTree(), transmitSpineInfo(), and updateShaftParents().
subTreePath_
string NeuroMesh::subTreePath_ private
Path of sub-tree used for the chemical model. This is undefined if the user assigns the subtree as a vector of objects, which is the case when using rdesigneur.
Definition at line 277 of file NeuroMesh.h.
Referenced by getSubTreePath(), NeuroMesh(), setSubTree(), and setSubTreePath().
surfaceGranularity_
double NeuroMesh::surfaceGranularity_ private
Decides how finely to subdivide diffLength_ or radius or cubic mesh side when computing surfacearea of intersections with CubeMesh. Defaults to 0.1.
Definition at line 323 of file NeuroMesh.h.
Referenced by matchCubeMeshEntries(), NeuroMesh(), and NeuroMesh().
vs_
vector< double > NeuroMesh::vs_ private
Volscale pre-calculations for each MeshEntry. vs = #molecules / vol where vol is expressed in m^3.
Definition at line 294 of file NeuroMesh.h.
Referenced by NeuroMesh(), operator=(), updateCoords(), vGetEntireVolume(), vGetVoxelMidpoint(), vGetVoxelVolume(), and vSetVolumeNotRates().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/mesh/NeuroMesh.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/mesh/NeuroMesh.cpp