MOOSE - Multiscale Object Oriented Simulation Environment: ObjId Class Reference
ObjId Class Reference
#include <ObjId.h>
Public Member Functions
bool bad () const
char * data () const
Element * element () const
Eref eref () const
bool isDataHere () const
bool isGlobal () const
Returns true if the Element is global.
bool isOffNode () const
Returns true if we need to go off-node for calling operations.
ObjId ()
ObjId (const ObjId &obj)
ObjId (const string &path)
ObjId (Id i, unsigned int d=0, unsigned int f=0)
bool operator!= (const ObjId &other) const
bool operator< (const ObjId &other) const
bool operator== (const ObjId &other) const
string path () const
Public Attributes
unsigned int dataIndex
unsigned int fieldIndex
Id id
Friends
ostream & operator<< (ostream &s, const ObjId &i)
istream & operator>> (istream &s, ObjId &i)
Detailed Description
This class manages lookups for specific data entries in elements, in a node-independent manner. It is basically a composite of Id and DataIndex.
Definition at line 18 of file ObjId.h.
Constructor & Destructor Documentation
ObjId() [1/4]
ObjId::ObjId () inline
Returns the root Id
Definition at line 30 of file ObjId.h.
        : id(), dataIndex( 0 ), fieldIndex( 0 )
    {
        ;
    }
References dataIndex, fieldIndex, Id::Id(), and id.
Referenced by ReadKkit::addmsg(), ReadKkit::buildEnz(), ReadKkit::buildSumTotal(), Shell::destroy(), Shell::doAddMsg(), Shell::doCopy(), Shell::doCreate(), Shell::doDelete(), Shell::doFind(), Shell::doMove(), Shell::doQuit(), Shell::doUseClock(), ReadCspace::expandEnzyme(), getCompt(), PresynMesh::getEndVoxelInCompt(), Neuron::getParentCompartmentOfSpine(), Neuron::getSpineFromCompartment(), PresynMesh::getStartVoxelInCompt(), ReadKkit::innerAddMsg(), innerFind(), Neutral::isDescendant(), lookupVolumeFromMesh(), ReadCspace::makePlots(), MsgFuncBinding::MsgFuncBinding(), Neutral::parent(), Neutral::path(), ReadKkit::read(), Enz::setSolver(), MMenz::setSolver(), Reac::setSolver(), PoolBase::setSolvers(), Neuron::setSpineAndPsdMesh(), Shell::Shell(), testAssortedMsg(), testGetMsg(), testMpiFibonacci(), testPoolVolumeScaling(), testReacVolumeScaling(), testShellAddMsg(), testShellParserStart(), testStats(), testTable(), testTwoReacGetNeighbors(), testWildcard(), TgtInfo::TgtInfo(), and Stoich::unZombifyPools().
ObjId() [2/4]
ObjId::ObjId (const ObjId & obj) inline
Definition at line 36 of file ObjId.h.
        : id( obj.id ), dataIndex( obj.dataIndex ), fieldIndex( obj.fieldIndex )
    {
        ;
    }
References dataIndex, fieldIndex, and id.
Referenced by pymoose::ElementField::ElementField(), pymoose::ElementFieldIterator::ElementFieldIterator(), Field< A >::get(), LookupField< L, A >::get(), Field< A >::getVec(), pymoose::LookupField::LookupField(), matchMid::matchMid(), pymoose::MooseVec::MooseVec(), Msg::Msg(), MsgFuncBinding::MsgFuncBinding(), SetGet0::set(), SetGet1< A >::set(), SetGet2< A1, A2 >::set(), SetGet3< A1, A2, A3 >::set(), SetGet4< A1, A2, A3, A4 >::set(), SetGet5< A1, A2, A3, A4, A5 >::set(), SetGet6< A1, A2, A3, A4, A5, A6 >::set(), and SetGet1< A >::setVec().
ObjId() [3/4]
ObjId::ObjId (Id i, unsigned int d = 0, unsigned int f = 0) inline
Creates a ObjId using specified Id and DataIndex
Definition at line 45 of file ObjId.h.
        : id( i ), dataIndex( d ), fieldIndex( f )
    {
        ;
    }
References dataIndex, fieldIndex, and id.
Referenced by Shell::addClockMsgs(), addToBuf(), Shell::adopt(), allChildren(), benchmarkMsg(), ReadCell::buildCompartment(), ReadKkit::buildEnz(), ReadKkit::buildSumTotal(), checkOutput(), SetGet::checkSet(), pymoose::createElementFromPath(), DiagonalMsg::DiagonalMsg(), dispatchBuffers(), Shell::doAddMsg(), Shell::doFind(), Shell::doSetClock(), Dsolve::fillConcChans(), Element::findCaller(), DiagonalMsg::findOtherEnd(), OneToAllMsg::findOtherEnd(), OneToOneDataIndexMsg::findOtherEnd(), OneToOneMsg::findOtherEnd(), SingleMsg::findOtherEnd(), SparseMsg::findOtherEnd(), pymoose::VecElementField::getAttribute(), pymoose::MooseVec::getDataItem(), pymoose::MooseVec::getFieldItem(), pymoose::ElementField::getItem(), pymoose::VecElementField::getItem(), Element::getMsgSourceAndSender(), Element::getMsgTargets(), Neuron::getSpineFromCompartment(), LookupField< L, A >::getVec(), ReadKkit::innerAddMsg(), innerCopyElements(), pymoose::loadModelInternal(), main(), makeReacTest(), pymoose::MooseVec::MooseVec(), pymoose::ElementFieldIterator::next(), Eref::objId(), OneToAllMsg::OneToAllMsg(), OneToOneDataIndexMsg::OneToOneDataIndexMsg(), OneToOneMsg::OneToOneMsg(), printGrid(), ReadCell::ReadCell(), remoteFieldGetVec(), remoteGet(), remoteGetVec(), pymoose::VecElementField::setAttribute(), SetGet2< A1, A2 >::setVec(), singleLevelWildcard(), SingleMsg::SingleMsg(), pymoose::VecElementField::size(), pymoose::VecElementField::sizes(), SparseMsg::SparseMsg(), test2ArgSetVec(), testAssortedMsg(), testCalcJunction(), testCellDiffn(), testCinfoElements(), testCopy(), testCopyFieldElement(), testCylDiffn(), testCylDiffnWithStoich(), testGet(), testLookupSetGet(), testMMenzProcess(), testMove(), testMpiFibonacci(), testMsgElementListing(), testMsgSrcDestFields(), testObjIdToAndFromPath(), testPoolVolumeScaling(), testReMesh(), testRunGsolve(), testRunKsolve(), testRunKsolveWithLSODA(), testSendSpike(), testSetGet(), testSetGetDouble(), testSetGetExtField(), testSetGetSynapse(), testSetRepeat(), testShellAddMsg(), testShellSetGet(), testSmallCellDiffn(), testSparseMsg(), testStrGet(), testStrSet(), testSyncSynapseSize(), testTaperingCylDiffn(), testTreeTraversal(), testWildcard(), writeKkit(), HSolve::zombify(), and Stoich::zombifyModel().
ObjId() [4/4]
ObjId::ObjId (const string & path)
Creates an ObjId by reading the path string Returns bad on failure.
Definition at line 59 of file ObjId.cpp.
{
    Shell* shell = reinterpret_cast< Shell* >( Id().eref().data() );
    assert( shell );
    *this = shell->doFind( path );
}
References Eref::data(), Shell::doFind(), Id::eref(), and Id::Id().
Referenced by ReadCell::buildCompartment(), pymoose::createElementFromPath(), pymoose::MooseVec::MooseVec(), pymoose::VecElementField::size(), ReadCell::startGraftCell(), testObjIdToAndFromPath(), testRunGsolve(), testVolScaling(), and trimPath().
Member Function Documentation
bad()
bool ObjId::bad () const
True if the return value is bad: either returning a failure, or the DataIndex or FieldIndex is out of range. However, this is a node-local funtion so it can't report the FieldIndex status in all cases.
Definition at line 18 of file ObjId.cpp.
{
    Element* elm = id.element();
    return ( elm == 0 ||
             dataIndex == BADINDEX ||
             fieldIndex == BADINDEX ||
             dataIndex >= elm->numData()
             /*
              * We have a bit of a problem here. The FieldElement can exist
              * with zero fields, and is invalid for field lookups but valid
              * for the element level lookups. I should rather not create the
              * FieldElements this way.
             || (
                elm->getNode( dataIndex ) == Shell::myNode() &&
                fieldIndex >= elm->numField( dataIndex - elm->localDataStart() )
             )
              */
           );
}
References BADINDEX, dataIndex, Id::element(), fieldIndex, id, and Element::numData().
Referenced by ReadCell::addCanonicalChannel(), ReadCell::addChannelMessage(), Element::addMsg(), benchmarkMsg(), ReadCell::buildCompartment(), pymoose::convertToObjId(), pymoose::createElementFromPath(), HSolve::deleteIncomingMessages(), doClassSpecificMessaging(), Dsolve::fillConcChans(), pymoose::listElements(), pymoose::MooseVec::MooseVec(), HSolveActive::readSynapses(), Reac::setSolver(), PoolBase::setSolvers(), ReadCell::startGraftCell(), testAssortedMsg(), testCalcJunction(), testMsgElementListing(), and testTreeTraversal().
data()
char * ObjId::data () const
Returns data entry for this object
Definition at line 113 of file ObjId.cpp.
{
    return id.element()->data(
            id.element()->rawIndex( dataIndex ), fieldIndex
        );
}
References Element::data(), dataIndex, Id::element(), fieldIndex, id, and Element::rawIndex().
Referenced by Synapse::addMsgCallback(), addToBuf(), dispatchBuffers(), Shell::doStart(), Synapse::dropMsgCallback(), Msg::getMsg(), Dsolve::innerBuildMeshJunctions(), innerFind(), main(), ReadKkit::read(), remoteFieldGetVec(), remoteGet(), remoteGetVec(), Enz::setSolver(), MMenz::setSolver(), PoolBase::setSolvers(), EndoMesh::setSurround(), test2ArgSetVec(), testLookupSetGet(), testMsgField(), testSendSpike(), testSetGet(), testSetGetDouble(), testSetGetExtField(), and testStrGet().
element()
Element * ObjId::element () const
Returns Element part
Definition at line 125 of file ObjId.cpp.
{
    return id.element();
}
References Id::element(), and id.
Referenced by Shell::addClockMsgs(), SocketStreamer::addTable(), Streamer::addTable(), Shell::adopt(), Dsolve::buildMeshJunctions(), PresynMesh::buildOnDendrites(), PresynMesh::buildOnSpineHeads(), NeuroNode::buildTree(), SetGet::checkSet(), pymoose::copy(), pymoose::createElementFromPath(), Shell::doCreate(), Shell::doFind(), Shell::doMove(), Shell::dropClockMsgs(), pymoose::MooseVec::dtype(), ReadKkit::dumpPlots(), Neuron::evalExprForElist(), Dsolve::fillConcChans(), filterWildcards(), OneToAllMsg::findOtherEnd(), OneToOneDataIndexMsg::findOtherEnd(), OneToOneMsg::findOtherEnd(), SingleMsg::findOtherEnd(), SparseMsg::findOtherEnd(), pymoose::MooseVec::getAttribute(), getCompt(), pymoose::getFieldGeneric(), pymoose::MooseVec::getItem(), Shell::innerMove(), isPartOfDend(), Dsolve::makePoolMapFromElist(), matchBeforeBrace(), matchInsideBrace(), matchName(), pymoose::MooseVec::name(), GetEpFunc1< T, L, A >::op(), GetOpFunc1< T, L, A >::op(), Neutral::parent(), Neutral::path(), ReadCspace::printMol(), Streamer::reinit(), pymoose::MooseVec::setAttribute(), pymoose::MooseVec::setAttrOneToAll(), pymoose::MooseVec::setAttrOneToOne(), pymoose::setFieldGeneric(), Enz::setSolver(), MMenz::setSolver(), Reac::setSolver(), PoolBase::setSolvers(), Neuron::setSpineAndPsdMesh(), EndoMesh::setSurround(), pymoose::MooseVec::size(), SetGet::strGet(), SetGet::strSet(), testGet(), testMsgField(), testSyncSynapseSize(), and wildcardTestFunc().
eref()
Eref ObjId::eref () const
Returns the Eref matching itself.
Definition at line 66 of file ObjId.cpp.
{
    return Eref( id.element(), dataIndex, fieldIndex );
}
References dataIndex, Id::element(), Eref::Eref(), fieldIndex, and id.
Referenced by SocketStreamer::addTable(), Streamer::addTable(), Shell::adopt(), allChildren(), buildFromProto(), SetGet::checkSet(), pymoose::MooseVec::children(), Shell::destroy(), Shell::doCopy(), Shell::doCreate(), Shell::doFind(), Shell::doMove(), TgtInfo::eref(), Field< A >::get(), LookupField< L, A >::get(), Field< A >::getVec(), Shell::innerAddMsg(), Shell::innerMove(), Neutral::isDescendant(), pymoose::listElements(), GetEpFunc1< T, L, A >::op(), GetOpFunc1< T, L, A >::op(), path(), Neutral::path(), SetGet0::set(), SetGet1< A >::set(), SetGet2< A1, A2 >::set(), SetGet3< A1, A2, A3 >::set(), SetGet4< A1, A2, A3, A4 >::set(), SetGet5< A1, A2, A3, A4, A5 >::set(), SetGet6< A1, A2, A3, A4, A5, A6 >::set(), moose::CompartmentBase::setGeomAndElec(), Neutral::setName(), Reac::setSolver(), Neuron::setSpineAndPsdMesh(), SetGet2< A1, A2 >::setVec(), SetGet1< A >::setVec(), singleLevelWildcard(), SetGet::strGet(), SetGet::strSet(), testGetMsg(), testObjIdToAndFromPath(), testSendSpike(), testShellAddMsg(), and testTable().
isDataHere()
bool ObjId::isDataHere () const
True if the data is present on the current node. Always true for globals, which confuses the matter somewhat.
Definition at line 95 of file ObjId.cpp.
{
    return ( id.element()->getNode( dataIndex ) == Shell::myNode() );
}
References dataIndex, Id::element(), Element::getNode(), id, and Shell::myNode().
Referenced by SetGet::checkSet(), Field< A >::get(), and LookupField< L, A >::get().
isGlobal()
bool ObjId::isGlobal () const
Returns true if the Element is global.
Definition at line 100 of file ObjId.cpp.
{
    return ( id.element()->isGlobal() );
}
References Id::element(), id, and Element::isGlobal().
Referenced by SetGet0::set(), SetGet1< A >::set(), SetGet2< A1, A2 >::set(), SetGet3< A1, A2, A3 >::set(), SetGet4< A1, A2, A3, A4 >::set(), SetGet5< A1, A2, A3, A4, A5 >::set(), and SetGet6< A1, A2, A3, A4, A5, A6 >::set().
isOffNode()
bool ObjId::isOffNode () const
Returns true if we need to go off-node for calling operations.
Definition at line 105 of file ObjId.cpp.
{
    return ( Shell::numNodes() > 1 &&
             ( id.element()->isGlobal() ||
               id.element()->getNode( dataIndex ) != Shell::myNode() )
           );
}
References dataIndex, Id::element(), Element::getNode(), id, Element::isGlobal(), Shell::myNode(), and Shell::numNodes().
Referenced by SetGet0::set(), SetGet1< A >::set(), SetGet2< A1, A2 >::set(), SetGet3< A1, A2, A3 >::set(), SetGet4< A1, A2, A3, A4 >::set(), SetGet5< A1, A2, A3, A4, A5 >::set(), and SetGet6< A1, A2, A3, A4, A5, A6 >::set().
operator!=()
bool ObjId::operator!= (const ObjId & other) const
Definition at line 77 of file ObjId.cpp.
{
    return ( id != other.id || dataIndex != other.dataIndex ||
             fieldIndex != other.fieldIndex );
}
References dataIndex, fieldIndex, id, and Id::operator!=().
Referenced by ReadKkit::addmsg(), ReadKkit::buildEnz(), ReadKkit::buildSumTotal(), ReadCspace::expandEnzyme(), PresynMesh::getEndVoxelInCompt(), PresynMesh::getStartVoxelInCompt(), ReadKkit::innerAddMsg(), Neutral::isDescendant(), ReadCspace::makePlots(), myUnique(), Neutral::parent(), testGetMsg(), testPoolVolumeScaling(), testReacVolumeScaling(), testShellAddMsg(), testStats(), testTable(), testTwoReacGetNeighbors(), wildcardRelativeFind(), and wildcardTestFunc().
operator<()
bool ObjId::operator< (const ObjId & other) const
For sorting
Definition at line 83 of file ObjId.cpp.
{
    return ( id < other.id ||
             (id == other.id && (
                  dataIndex < other.dataIndex  ||
                  ( dataIndex == other.dataIndex &&
                    fieldIndex < other.fieldIndex )
              )
             )
           );
}
References dataIndex, fieldIndex, id, Id::operator<(), and Id::operator==().
operator==()
bool ObjId::operator== (const ObjId & other) const
For equality check
Definition at line 71 of file ObjId.cpp.
{
    return ( id == other.id && dataIndex == other.dataIndex &&
             fieldIndex == other.fieldIndex );
}
References dataIndex, fieldIndex, id, and Id::operator==().
Referenced by Neutral::child(), Shell::doFind(), getCompt(), Element::getFieldsOfOutgoingMsg(), PresynMesh::getNumBoutonsOnCompartment(), PresynMesh::getStartBoutonIndexFromCompartment(), lookupVolumeFromMesh(), matchMid::operator()(), MsgFuncBinding::operator==(), Neutral::path(), Enz::setSolver(), MMenz::setSolver(), Reac::setSolver(), PoolBase::setSolvers(), testAssortedMsg(), testCopy(), testMove(), testMsgSrcDestFields(), testObjIdToAndFromPath(), and testTreeTraversal().
path()
string ObjId::path () const
Returns the absolute path including all array indices.
Definition at line 120 of file ObjId.cpp.
{
    return Neutral::path( eref() );
}
References eref(), and Neutral::path().
Referenced by SocketStreamer::addTable(), Streamer::addTable(), pymoose::createElementFromPath(), doClassSpecificMessaging(), Shell::doCopy(), Shell::doCreate(), Shell::doMove(), pymoose::ElementField::ElementField(), HHGate::fillFromExpr(), pymoose::VecElementField::getAttribute(), Function::getIndependent(), Field< A >::getVec(), pymoose::listElements(), pymoose::MooseVec::path(), SocketStreamer::reinit(), Streamer::reinit(), SocketStreamer::removeTable(), Streamer::removeTable(), pymoose::VecElementField::setAttribute(), Enz::setSolver(), Reac::setSolver(), Neuron::setSpineAndPsdMesh(), EndoMesh::setSurround(), pymoose::VecElementField::size(), pymoose::VecElementField::sizes(), testObjIdToAndFromPath(), testTreeTraversal(), and HHChannel::vReinit().
Friends And Related Symbol Documentation
operator<<
ostream & operator<< (ostream & s, const ObjId & i) friend
operator>>
istream & operator>> (istream & s, ObjId & i) friend
Member Data Documentation
dataIndex
unsigned int ObjId::dataIndex
Definition at line 103 of file ObjId.h.
Referenced by allChildren(), bad(), SetGet::checkSet(), data(), Shell::doAddMsg(), Shell::doFind(), eref(), DiagonalMsg::findOtherEnd(), OneToAllMsg::findOtherEnd(), OneToOneDataIndexMsg::findOtherEnd(), OneToOneMsg::findOtherEnd(), SingleMsg::findOtherEnd(), SparseMsg::findOtherEnd(), pymoose::VecElementField::getAttribute(), pymoose::MooseVec::getFieldItem(), pymoose::ElementField::getItem(), innerCopyElements(), isDataHere(), isOffNode(), matchInsideBrace(), pymoose::ElementFieldIterator::next(), ObjId(), ObjId(), ObjId(), operator!=(), operator<(), operator<<(), operator==(), Neutral::path(), pymoose::VecElementField::setAttribute(), singleLevelWildcard(), testObjIdToAndFromPath(), DiagonalMsg::~DiagonalMsg(), OneToAllMsg::~OneToAllMsg(), OneToOneDataIndexMsg::~OneToOneDataIndexMsg(), OneToOneMsg::~OneToOneMsg(), SingleMsg::~SingleMsg(), and SparseMsg::~SparseMsg().
fieldIndex
unsigned int ObjId::fieldIndex
Definition at line 104 of file ObjId.h.
Referenced by bad(), SetGet::checkSet(), data(), Shell::doFind(), eref(), pymoose::MooseVec::getDataItem(), ObjId(), ObjId(), ObjId(), operator!=(), operator<(), operator<<(), operator==(), and testObjIdToAndFromPath().
id
Id ObjId::id
Here are the data values.
Definition at line 102 of file ObjId.h.
Referenced by ReadKkit::assignPoolCompartments(), ReadKkit::assignReacCompartments(), bad(), ReadKkit::buildChan(), ReadKkit::buildEnz(), ReadKkit::buildGraph(), ReadKkit::buildGroup(), PresynMesh::buildOnDendrites(), PresynMesh::buildOnSpineHeads(), ReadKkit::buildPlot(), ReadKkit::buildPool(), ReadKkit::buildReac(), ReadKkit::buildStim(), ReadKkit::buildTable(), SetGet::checkSet(), ReadKkit::childPoolVol(), convWildcards(), pymoose::copy(), data(), HSolve::deleteIncomingMessages(), Shell::destroy(), Shell::doAddMsg(), element(), eref(), Dsolve::fillConcChans(), filterWildcards(), findModelParent(), DiagonalMsg::findOtherEnd(), Field< A >::get(), LookupField< L, A >::get(), pymoose::VecElementField::getAttribute(), getCompt(), pymoose::MooseVec::getDataItem(), NeuroMesh::getDendVoxelsOnCompartment(), pymoose::MooseVec::getFieldItem(), pymoose::ElementField::getItem(), Neuron::getParentCompartmentOfSpine(), Neuron::getSpineFromCompartment(), Neuron::getSpinesOnCompartment(), NeuroMesh::getSpineVoxelsOnCompartment(), pymoose::MooseVec::id(), Id::Id(), Id::Id(), Shell::innerAddMsg(), Dsolve::innerBuildMeshJunctions(), Shell::innerUseClock(), Stoich::installEnzyme(), Stoich::installMMenz(), Stoich::installReaction(), isDataHere(), isGlobal(), isOffNode(), Dsolve::makePoolMapFromElist(), matchInsideBrace(), pymoose::ElementFieldIterator::next(), ObjId(), ObjId(), ObjId(), operator!=(), operator<(), operator<<(), operator==(), operator>>(), Neutral::parent(), Neutral::path(), pymoose::VecElementField::setAttribute(), testObjIdToAndFromPath(), and testTreeTraversal().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/basecode/ObjId.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/basecode/ObjId.cpp