MOOSE - Multiscale Object Oriented Simulation Environment: DestFinfo Class Reference
DestFinfo Class Reference
#include <DestFinfo.h>
Public Member Functions
DestFinfo (const string &name, const string &doc, OpFunc *func)
FuncId getFid () const
const OpFunc * getOpFunc () const
void registerFinfo (Cinfo *c)
string rttiType () const
bool strGet (const Eref &tgt, const string &field, string &returnValue) const
bool strSet (const Eref &tgt, const string &field, const string &arg) const
~DestFinfo ()
Public Member Functions inherited from Finfo
virtual bool addMsg (const Finfo *target, ObjId mid, Element *src) const
virtual bool checkTarget (const Finfo *target) const
const string & docs () const
Returns documentation string.
Finfo (const string &name, const string &doc)
virtual vector< string > innerDest () const
virtual vector< string > innerSrc () const
const string & name () const
virtual void postCreationFunc (Id newId, Element *newElm) const
virtual ~Finfo ()
Private Attributes
FuncId fid_
OpFunc * func_
Additional Inherited Members
Static Public Member Functions inherited from Finfo
static const Cinfo * initCinfo ()
Detailed Description
Definition at line 17 of file DestFinfo.h.
Constructor & Destructor Documentation
~DestFinfo()
DestFinfo::~DestFinfo ()
Definition at line 13 of file DestFinfo.cpp.
{
    delete func_;
}
References func_.
DestFinfo()
DestFinfo::DestFinfo (const string & name, const string & doc, OpFunc * func)
Definition at line 18 of file DestFinfo.cpp.
    : Finfo(name, doc), func_(func)
{
    ;
}
References Finfo::Finfo(), and func_.
Referenced by handleInput(), CaConcBase::initCinfo(), ChanBase::initCinfo(), moose::CompartmentBase::initCinfo(), DifBufferBase::initCinfo(), DifShellBase::initCinfo(), GapJunction::initCinfo(), HHChannel2D::initCinfo(), HHChannelBase::initCinfo(), IntFire::initCinfo(), IzhikevichNrn::initCinfo(), MarkovChannel::initCinfo(), MarkovOdeSolver::initCinfo(), MarkovRateTable::initCinfo(), MarkovSolver::initCinfo(), MarkovSolverBase::initCinfo(), MgBlock::initCinfo(), MMPump::initCinfo(), Nernst::initCinfo(), Neuron::initCinfo(), NMDAChan::initCinfo(), RandSpike::initCinfo(), SpikeGen::initCinfo(), SymCompartment::initCinfo(), SynChan::initCinfo(), moose::VClamp::initCinfo(), Arith::initCinfo(), Function::initCinfo(), Interpol::initCinfo(), Interpol2D::initCinfo(), SocketStreamer::initCinfo(), SpikeStats::initCinfo(), Stats::initCinfo(), StimulusTable::initCinfo(), Streamer::initCinfo(), Table::initCinfo(), TableBase::initCinfo(), TimeTable::initCinfo(), Variable::initCinfo(), DiffAmp::initCinfo(), PIDController::initCinfo(), PulseGen::initCinfo(), RC::initCinfo(), Dsolve::initCinfo(), Cell::initCinfo(), HSolve::initCinfo(), moose::IntFireBase::initCinfo(), ConcChan::initCinfo(), Enz::initCinfo(), EnzBase::initCinfo(), MMenz::initCinfo(), Reac::initCinfo(), Species::initCinfo(), Gsolve::initCinfo(), Ksolve::initCinfo(), Stoich::initCinfo(), ChemCompt::initCinfo(), CubeMesh::initCinfo(), MeshEntry::initCinfo(), PresynMesh::initCinfo(), PsdMesh::initCinfo(), SpineMesh::initCinfo(), PostMaster::initCinfo(), SparseMsg::initCinfo(), Clock::initCinfo(), Neutral::initCinfo(), Shell::initCinfo(), Adaptor::initCinfo(), GraupnerBrunel2012CaPlasticitySynHandler::initCinfo(), STDPSynHandler::initCinfo(), Synapse::initCinfo(), SynHandlerBase::initCinfo(), PoolBase::initPoolBaseCinfo(), and testSharedMsg().
Member Function Documentation
getFid()
FuncId DestFinfo::getFid () const
Definition at line 45 of file DestFinfo.cpp.
{
    return fid_;
}
References fid_.
Referenced by SrcFinfo::addMsg(), SetGet::checkSet(), Neutral::child(), Neutral::children(), HSolve::deleteIncomingMessages(), Cinfo::destFinfoName(), Shell::dropClockMsgs(), Dsolve::fillConcChans(), Element::getInputs(), Element::getInputsWithTgtIndex(), Shell::innerMove(), insertSharedMsgs(), Neutral::isDescendant(), Neutral::parent(), Neutral::path(), HSolveActive::readSynapses(), Cinfo::reportFids(), testAssortedMsg(), testMsgField(), testMsgSrcDestFields(), and testSendMsg().
getOpFunc()
const OpFunc * DestFinfo::getOpFunc () const
Definition at line 40 of file DestFinfo.cpp.
{
    return func_;
}
References func_.
Referenced by SrcFinfo::addMsg(), SetGet::checkSet(), SrcFinfo::checkTarget(), and localGet().
registerFinfo()
void DestFinfo::registerFinfo (Cinfo * c) virtual
Returns string-ified form to handle template expectations for name field string getName() const; Assign function Ids, bindIndex and so on.
Implements Finfo.
Definition at line 24 of file DestFinfo.cpp.
{
    if(c->baseCinfo()) {
        const Finfo* bf = c->baseCinfo()->findFinfo(name());
        if(bf) {
            const DestFinfo* df = dynamic_cast<const DestFinfo*>(bf);
            assert(df);
            fid_ = df->fid_;
            c->overrideFunc(fid_, func_);
            return;
        }
    }
    fid_ = c->registerOpFunc(func_);
    //  cout << c->name() << "." << name() << ": " << fid_ << endl;
}
References Cinfo::baseCinfo(), fid_, Cinfo::findFinfo(), func_, Finfo::name(), Cinfo::overrideFunc(), and Cinfo::registerOpFunc().
rttiType()
string DestFinfo::rttiType () const virtual
Returns the documentation string for the Finfo string docs() const; Returns the RTTI type string for the finfo by referring to an internal virtual function. string type() const; Returns the list of subsidiary SrcFinfos. Used in Shared Finfos, empty otherwise. Goes via internal virtual function. vector< string > src() const; Returns the list of subsidiary destFinfos. Used in SharedFinfos and ValueFinfos, empty otherwise. Goes via internal virtual function. vector< string > dest() const; Returns an RTTI type string for this Finfo.
Reimplemented from Finfo.
Definition at line 64 of file DestFinfo.cpp.
{
    return func_->rttiType();
}
References func_, and OpFunc::rttiType().
strGet()
bool DestFinfo::strGet (const Eref & tgt, const string & field, string & returnValue) const virtual
Function to return value of field into a string argument. Returns true on success. Normally called only from SetGet::strGet.
Implements Finfo.
Definition at line 57 of file DestFinfo.cpp.
{
    assert(0);
    return false;
}
strSet()
bool DestFinfo::strSet (const Eref & tgt, const string & field, const string & arg) const virtual
Function to set this field using a string argument. Returns true on success. Normally called only from SetGet::strSet.
Implements Finfo.
Definition at line 50 of file DestFinfo.cpp.
{
    assert(0);
    return false;
}
Member Data Documentation
fid_
FuncId DestFinfo::fid_ private
Definition at line 37 of file DestFinfo.h.
Referenced by getFid(), and registerFinfo().
func_
OpFunc* DestFinfo::func_ private
Definition at line 36 of file DestFinfo.h.
Referenced by DestFinfo(), getOpFunc(), registerFinfo(), rttiType(), and ~DestFinfo().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/basecode/DestFinfo.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/basecode/DestFinfo.cpp