MOOSE - Multiscale Object Oriented Simulation Environment: HHChannel2D Class Reference
HHChannel2D Class Reference
#include <HHChannel2D.h>
Public Member Functions
bool checkOriginal (Id chanId) const override
Returns true if channel is original, false if copy.
void conc1 (double conc)
void conc2 (double conc)
void destroyGate (const Eref &e, string gateType) override
unsigned int getNumXgates () const
unsigned int getNumYgates () const
Returns 1 if Y gate present, otherwise 0.
unsigned int getNumZgates () const
Returns 1 if Z gate present, otherwise 0.
HHGate2D * getXgate (unsigned int i)
Access function used for the X gate. The index is ignored.
string getXindex () const
HHGate2D * getYgate (unsigned int i)
Access function used for the Y gate. The index is ignored.
string getYindex () const
HHGate2D * getZgate (unsigned int i)
Access function used for the Z gate. The index is ignored.
string getZindex () const
HHChannel2D ()
void innerCreateGate (const string &gateName, HHGate2D **gatePtr, Id chanId, Id gateId)
Inner utility function for creating the gate.
void innerDestroyGate (const string &gateName, HHGate2D **gatePtr, Id chanId)
void setNumGates (unsigned int num)
Dummy assignment function for the number of gates.
void setXindex (string index)
void setYindex (string index)
void setZindex (string index)
void vCreateGate (const Eref &e, string gateType) override
void vProcess (const Eref &e, ProcPtr p) override
void vReinit (const Eref &e, ProcPtr p) override
Public Member Functions inherited from HHChannelBase
void createGate (const Eref &e, string gateType)
int getInstant (const Eref &e) const
int getUseConcentration (const Eref &e) const
double getX (const Eref &e) const
HHGate * getXgate (unsigned int i)
double getXpower (const Eref &e) const
double getY (const Eref &e) const
HHGate * getYgate (unsigned int i)
double getYpower (const Eref &e) const
double getZ (const Eref &e) const
HHGate * getZgate (unsigned int i)
double getZpower (const Eref &e) const
void handleConc (const Eref &e, double conc)
HHChannelBase ()
bool setGatePower (const Eref &e, double power, double *assignee, const string &gateType)
void setInstant (const Eref &e, int Instant)
void setNumGates (unsigned int num)
void setUseConcentration (const Eref &e, int value)
void setX (const Eref &e, double X)
void setXpower (const Eref &e, double Xpower)
void setY (const Eref &e, double Y)
void setYpower (const Eref &e, double Ypower)
void setZ (const Eref &e, double Z)
void setZpower (const Eref &e, double Zpower)
virtual int vGetInstant (const Eref &e) const
virtual double vGetX (const Eref &e) const
virtual double vGetY (const Eref &e) const
virtual double vGetZ (const Eref &e) const
virtual void vHandleConc (const Eref &e, double conc)
virtual void vSetInstant (const Eref &e, int Instant)
virtual void vSetSolver (const Eref &e, Id hsolve)
virtual void vSetUseConcentration (const Eref &e, int value)
virtual void vSetX (const Eref &e, double X)
virtual void vSetXpower (const Eref &e, double Xpower)
virtual void vSetY (const Eref &e, double Y)
virtual void vSetYpower (const Eref &e, double Ypower)
virtual void vSetZ (const Eref &e, double Z)
virtual void vSetZpower (const Eref &e, double Zpower)
virtual ~HHChannelBase ()=0
Public Member Functions inherited from ChanCommon
ChanCommon ()
double getGbar () const
Utility function to acces Gbar.
double getVm () const
Utility function to access Vm.
void sendProcessMsgs (const Eref &e, const ProcPtr info)
void sendReinitMsgs (const Eref &e, const ProcPtr info)
void updateIk ()
double vGetEk (const Eref &e) const override
double vGetGbar (const Eref &e) const override
double vGetGk (const Eref &e) const override
double vGetIk (const Eref &e) const override
double vGetModulation (const Eref &e) const override
void vHandleVm (double Vm) override
void vSetEk (const Eref &e, double Ek) override
void vSetGbar (const Eref &e, double Gbar) override
void vSetGk (const Eref &e, double Gk) override
void vSetIk (const Eref &e, double Ic) override
void vSetModulation (const Eref &e, double modulation) override
virtual ~ChanCommon ()=0
Public Member Functions inherited from ChanBase
ChanBase ()
double getEk (const Eref &e) const
double getGbar (const Eref &e) const
double getGk (const Eref &e) const
double getIk (const Eref &e) const
double getModulation (const Eref &e) const
void handleVm (double Vm)
void process (const Eref &e, const ProcPtr info)
void reinit (const Eref &e, const ProcPtr info)
void setEk (const Eref &e, double Ek)
void setGbar (const Eref &e, double Gbar)
void setGk (const Eref &e, double Gk)
void setIk (const Eref &e, double Ic)
void setModulation (const Eref &e, double modulation)
virtual ~ChanBase ()=0
Static Public Member Functions
static const Cinfo * initCinfo ()
Static Public Member Functions inherited from HHChannelBase
static const Cinfo * initCinfo ()
static double power1 (double x, double p)
static double power2 (double x, double p)
static double power3 (double x, double p)
static double power4 (double x, double p)
static double powerN (double x, double p)
static PFDD selectPower (double power)
static void zombify (Element *orig, const Cinfo *zClass, Id hsolve)
Static Public Member Functions inherited from ChanCommon
static const Cinfo * initCinfo ()
Specify the Class Info static variable for initialization.
Static Public Member Functions inherited from ChanBase
static SrcFinfo2< double, double > * channelOut ()
static SrcFinfo1< double > * IkOut ()
static const Cinfo * initCinfo ()
Specify the Class Info static variable for initialization.
static SrcFinfo1< double > * permeability ()
Private Member Functions
int dependency (string index, unsigned int dim)
double depValue (int dependency)
Private Attributes
double conc1_
double conc2_
int Xdep0_
int Xdep1_
HHGate2D * xGate_
string Xindex_
int Ydep0_
int Ydep1_
HHGate2D * yGate_
string Yindex_
int Zdep0_
int Zdep1_
HHGate2D * zGate_
HHGate2D for the yGate.
string Zindex_
Additional Inherited Members
Protected Member Functions inherited from HHChannelBase
double integrate (double state, double dt, double A, double B)
Protected Member Functions inherited from ChanCommon
double getModulation () const
Protected Attributes inherited from HHChannelBase
double g_
int instant_
Id myId_
double(* takeXpower_)(double, double)
double(* takeYpower_)(double, double)
double(* takeZpower_)(double, double)
bool useConcentration_
Flag for use of conc for input to Z gate calculations.
double X_
bool xInited_
Flag to indicate if gates have been created.
double Xpower_
Exponent for X gate.
double Y_
bool yInited_
double Ypower_
Exponent for Y gate.
double Z_
bool zInited_
double Zpower_
Exponent for Z gate.
Protected Attributes inherited from ChanCommon
double Vm_
Vm_ is input variable from compartment, used for most rates.
Static Protected Attributes inherited from HHChannelBase
static const double EPSILON = 1.0e-10
static const int INSTANT_X = 1
static const int INSTANT_Y = 2
static const int INSTANT_Z = 4
Detailed Description
Definition at line 30 of file HHChannel2D.h.
Constructor & Destructor Documentation
HHChannel2D()
HHChannel2D::HHChannel2D ()
Definition at line 123 of file HHChannel2D.cpp.
    : HHChannelBase(),
      conc1_(0.0),
      conc2_(0.0),
      Xdep0_(-1),
      Xdep1_(-1),
      Ydep0_(-1),
      Ydep1_(-1),
      Zdep0_(-1),
      Zdep1_(-1),
      xGate_(0),
      yGate_(0),
      zGate_(0)
{
    ;
}
References conc1_, conc2_, HHChannelBase::HHChannelBase(), Xdep0_, Xdep1_, xGate_, Ydep0_, Ydep1_, yGate_, Zdep0_, Zdep1_, and zGate_.
Member Function Documentation
checkOriginal()
bool HHChannel2D::checkOriginal (Id chanId) const override virtual
Returns true if channel is original, false if copy.
If the gate exists and has only this element for input, then change the gate power. If the gate exists and has multiple parents, then make a new gate, set its power. If the gate does not exist, make a new gate, set its power.
The function is designed with the idea that if copies of this channel are made, then they all point back to the original HHGate. (Unless they are cross-node copies). It is only if we subsequently alter the HHGate of this channel that we need to make our own variant of the HHGate, or disconnect from an existing one.
Reimplemented from HHChannelBase.
Definition at line 424 of file HHChannel2D.cpp.
{
    bool isOriginal = 1;
    if(xGate_) {
        isOriginal = xGate_->isOriginalChannel(chanId);
    }
    else if(yGate_) {
        isOriginal = yGate_->isOriginalChannel(chanId);
    }
    else if(zGate_) {
        isOriginal = zGate_->isOriginalChannel(chanId);
    }
    return isOriginal;
}
References HHGate2D::isOriginalChannel(), xGate_, yGate_, and zGate_.
Referenced by destroyGate(), and vCreateGate().
conc1()
void HHChannel2D::conc1 (double conc)
Assign the local conc_ to the incoming conc from the concentration calculations for the compartment. Typically the message source will be a CaConc object, but there are other options for computing the conc.
Definition at line 286 of file HHChannel2D.cpp.
{
    conc1_ = conc;
}
References conc1_.
Referenced by initCinfo().
conc2()
void HHChannel2D::conc2 (double conc)
Definition at line 291 of file HHChannel2D.cpp.
{
    conc2_ = conc;
}
References conc2_.
Referenced by initCinfo().
dependency()
int HHChannel2D::dependency (string index, unsigned int dim) private
Definition at line 246 of file HHChannel2D.cpp.
{
    static vector<map<string, int>> dep;
    if(dep.empty()) {
        dep.resize(2);
        dep[0]["VOLT_INDEX"] = 0;
        dep[0]["C1_INDEX"] = 1;
        dep[0]["C2_INDEX"] = 2;
        dep[0]["VOLT_C1_INDEX"] = 0;
        dep[0]["VOLT_C2_INDEX"] = 0;
        dep[0]["C1_C2_INDEX"] = 1;
        dep[1]["VOLT_INDEX"] = -1;
        dep[1]["C1_INDEX"] = -1;
        dep[1]["C2_INDEX"] = -1;
        dep[1]["VOLT_C1_INDEX"] = 1;
        dep[1]["VOLT_C2_INDEX"] = 2;
        dep[1]["C1_C2_INDEX"] = 2;
    }
    if(dep[dim].find(index) == dep[dim].end())
        return -1;
    if(dep[dim][index] == 0)
        return 0;
    if(dep[dim][index] == 1)
        return 1;
    if(dep[dim][index] == 2)
        return 2;
    return -1;
}
Referenced by setXindex(), setYindex(), and setZindex().
depValue()
double HHChannel2D::depValue (int dependency) private
Definition at line 231 of file HHChannel2D.cpp.
{
    switch(dep) {
        case 0:
            return Vm_;
        case 1:
            return conc1_;
        case 2:
            return conc2_;
        default:
            assert(0);
            return 0.0;
    }
}
References conc1_, conc2_, and ChanCommon::Vm_.
Referenced by vProcess(), and vReinit().
destroyGate()
void HHChannel2D::destroyGate (const Eref & e, string gateType) override virtual
Utility function for destroying gate. Works only on original HHChannel. Somewhat dangerous, should never be used after a copy has been made as the pointer of the gate will be in use elsewhere.
Reimplemented from HHChannelBase.
Definition at line 483 of file HHChannel2D.cpp.
{
    if(!checkOriginal(e.id())) {
        cout << "Warning: HHChannel2D::destroyGate: Not allowed from copied "
                "channel:\n"
             << e.id().path() << "\n";
        return;
    }
    if(gateType == "X")
        innerDestroyGate("xGate", &xGate_, e.id());
    else if(gateType == "Y")
        innerDestroyGate("yGate", &yGate_, e.id());
    else if(gateType == "Z")
        innerDestroyGate("zGate", &zGate_, e.id());
    else
        cout << "Warning: HHChannel2D::destroyGate: Unknown gate type '"
             << gateType << "'. Ignored\n";
}
References checkOriginal(), Eref::id(), innerDestroyGate(), Id::path(), xGate_, yGate_, and zGate_.
getNumXgates()
unsigned int HHChannel2D::getNumXgates () const
Access function for the number of Xgates. Gives 1 if present, otherwise 0.
Definition at line 218 of file HHChannel2D.cpp.
{
    return xGate_ != nullptr;
}
References xGate_.
Referenced by initCinfo().
getNumYgates()
unsigned int HHChannel2D::getNumYgates () const
Returns 1 if Y gate present, otherwise 0.
Definition at line 222 of file HHChannel2D.cpp.
{
    return yGate_ != nullptr;
}
References yGate_.
Referenced by initCinfo().
getNumZgates()
unsigned int HHChannel2D::getNumZgates () const
Returns 1 if Z gate present, otherwise 0.
Definition at line 226 of file HHChannel2D.cpp.
{
    return zGate_ != nullptr;
}
References zGate_.
Referenced by initCinfo().
getXgate()
HHGate2D * HHChannel2D::getXgate (unsigned int i)
Access function used for the X gate. The index is ignored.
Definition at line 199 of file HHChannel2D.cpp.
{
    return xGate_;
}
References xGate_.
Referenced by initCinfo().
getXindex()
string HHChannel2D::getXindex () const
Definition at line 144 of file HHChannel2D.cpp.
{
    return Xindex_;
}
References Xindex_.
Referenced by initCinfo().
getYgate()
HHGate2D * HHChannel2D::getYgate (unsigned int i)
Access function used for the Y gate. The index is ignored.
Definition at line 204 of file HHChannel2D.cpp.
{
    return yGate_;
}
References yGate_.
Referenced by initCinfo().
getYindex()
string HHChannel2D::getYindex () const
Definition at line 161 of file HHChannel2D.cpp.
{
    return Yindex_;
}
References Yindex_.
Referenced by initCinfo().
getZgate()
HHGate2D * HHChannel2D::getZgate (unsigned int i)
Access function used for the Z gate. The index is ignored.
Definition at line 209 of file HHChannel2D.cpp.
{
    return zGate_;
}
References zGate_.
Referenced by initCinfo().
getZindex()
string HHChannel2D::getZindex () const
Definition at line 178 of file HHChannel2D.cpp.
{
    return Zindex_;
}
References Zindex_.
Referenced by initCinfo().
initCinfo()
const Cinfo * HHChannel2D::initCinfo () static
Definition at line 25 of file HHChannel2D.cpp.
{
    // Shared messages
    // Field definitions
    static ValueFinfo<HHChannel2D, string> Xindex(
        "Xindex", "String for setting X index.", &HHChannel2D::setXindex,
        &HHChannel2D::getXindex);
    static ValueFinfo<HHChannel2D, string> Yindex(
        "Yindex", "String for setting Y index.", &HHChannel2D::setYindex,
        &HHChannel2D::getYindex);
    static ValueFinfo<HHChannel2D, string> Zindex(
        "Zindex", "String for setting Z index.", &HHChannel2D::setZindex,
        &HHChannel2D::getZindex);
    static ElementValueFinfo<HHChannel2D, double> Xpower(
        "Xpower", "Power for X gate", &HHChannel2D::setXpower,
        &HHChannel2D::getXpower);
    static ElementValueFinfo<HHChannel2D, double> Ypower(
        "Ypower", "Power for Y gate", &HHChannel2D::setYpower,
        &HHChannel2D::getYpower);
    static ElementValueFinfo<HHChannel2D, double> Zpower(
        "Zpower", "Power for Z gate", &HHChannel2D::setZpower,
        &HHChannel2D::getZpower);
    // MsgDest definitions
    static DestFinfo concen(
        "concen",
        "Incoming message from Concen object to specific conc to use"
        "as the first concen variable",
        new OpFunc1<HHChannel2D, double>(&HHChannel2D::conc1));
    static DestFinfo concen2(
        "concen2",
        "Incoming message from Concen object to specific conc to use"
        "as the second concen variable",
        new OpFunc1<HHChannel2D, double>(&HHChannel2D::conc2));
    // FieldElementFinfo definition for HHGates. Note that these are made
    // with the deferCreate flag off, so that the HHGates are created
    // right away even if they are empty.
    // I assume that we only have a single HHGate entry for each one.
    static FieldElementFinfo<HHChannel2D, HHGate2D> gateX(
        "gateX", "Sets up HHGate X for channel", HHGate2D::initCinfo(),
        &HHChannel2D::getXgate, &HHChannel2D::setNumGates,
        &HHChannel2D::getNumXgates);
    static FieldElementFinfo<HHChannel2D, HHGate2D> gateY(
        "gateY", "Sets up HHGate Y for channel", HHGate2D::initCinfo(),
        &HHChannel2D::getYgate, &HHChannel2D::setNumGates,
        &HHChannel2D::getNumYgates);
    static FieldElementFinfo<HHChannel2D, HHGate2D> gateZ(
        "gateZ", "Sets up HHGate Z for channel", HHGate2D::initCinfo(),
        &HHChannel2D::getZgate, &HHChannel2D::setNumGates,
        &HHChannel2D::getNumZgates);
    static Finfo *HHChannel2DFinfos[] = {
        &Xindex,  // Value
        &Yindex,  // Value
        &Zindex,  // Value
        &Xpower,  // Value
        &Ypower,  // Value
        &Zpower,  // Value
        // &instant,    // Value
        // &X,          // Value
        // &Y,          // Value
        // &Z,          // Value
        &concen,   // Dest
        &concen2,  // Dest
        &gateX,    // FieldElement
        &gateY,    // FieldElement
        &gateZ     // FieldElement
    };
    static string doc[] = {
        "Name",
        "HHChannel2D",
        "Author",
        "Niraj Dudani, 2009, NCBS, Updated Upi Bhalla, 2011",
        "Description",
        "HHChannel2D: Hodgkin-Huxley type voltage-gated Ion channel. Something "
        "like the old tabchannel from GENESIS, but also presents "
        "a similar interface as hhchan from GENESIS. ",
    };
    static Dinfo<HHChannel2D> dinfo;
    static Cinfo HHChannel2DCinfo("HHChannel2D", HHChannelBase::initCinfo(),
                                  HHChannel2DFinfos,
                                  sizeof(HHChannel2DFinfos) / sizeof(Finfo *),
                                  &dinfo, doc, sizeof(doc) / sizeof(string));
    return &HHChannel2DCinfo;
}
References Cinfo::Cinfo(), conc1(), conc2(), DestFinfo::DestFinfo(), ElementValueFinfo< T, F >::ElementValueFinfo(), FieldElementFinfo< T, F >::FieldElementFinfo(), getNumXgates(), getNumYgates(), getNumZgates(), getXgate(), getXindex(), HHChannelBase::getXpower(), getYgate(), getYindex(), HHChannelBase::getYpower(), getZgate(), getZindex(), HHChannelBase::getZpower(), HHChannelBase::initCinfo(), HHGate2D::initCinfo(), OpFunc1< T, A >::OpFunc1(), setNumGates(), setXindex(), HHChannelBase::setXpower(), setYindex(), HHChannelBase::setYpower(), setZindex(), HHChannelBase::setZpower(), and ValueFinfo< T, F >::ValueFinfo().
innerCreateGate()
void HHChannel2D::innerCreateGate (const string & gateName, HHGate2D ** gatePtr, Id chanId, Id gateId)
Inner utility function for creating the gate.
Definition at line 439 of file HHChannel2D.cpp.
{
    // Shell* shell = reinterpret_cast< Shell* >( ObjId( Id(), 0 ).data() );
    if(*gatePtr) {
        cout << "Warning: HHChannel2D::createGate: '" << gateName
             << "' on Element '" << chanId.path() << "' already present\n";
        return;
    }
    *gatePtr = new HHGate2D(chanId, gateId);
}
References HHGate2D::HHGate2D(), and Id::path().
Referenced by vCreateGate().
innerDestroyGate()
void HHChannel2D::innerDestroyGate (const string & gateName, HHGate2D ** gatePtr, Id chanId)
Inner utility for destroying the gate
Definition at line 471 of file HHChannel2D.cpp.
{
    if(*gatePtr == nullptr) {
        cout << "Warning: HHChannel2D::destroyGate: '" << gateName
             << "' on Element '" << chanId.path() << "' not present\n";
        return;
    }
    delete(*gatePtr);
    *gatePtr = nullptr;
}
References Id::path().
Referenced by destroyGate().
setNumGates()
void HHChannel2D::setNumGates (unsigned int num)
Dummy assignment function for the number of gates.
Definition at line 214 of file HHChannel2D.cpp.
{
    ;
}
Referenced by initCinfo().
setXindex()
void HHChannel2D::setXindex (string index)
Definition at line 149 of file HHChannel2D.cpp.
{
    if(Xindex == Xindex_)
        return;
    Xindex_ = Xindex;
    Xdep0_ = dependency(Xindex, 0);
    Xdep1_ = dependency(Xindex, 1);
    assert(Xdep0_ >= 0);
}
References dependency(), Xdep0_, Xdep1_, and Xindex_.
Referenced by initCinfo().
setYindex()
void HHChannel2D::setYindex (string index)
Definition at line 166 of file HHChannel2D.cpp.
{
    if(Yindex == Yindex_)
        return;
    Yindex_ = Yindex;
    Ydep0_ = dependency(Yindex, 0);
    Ydep1_ = dependency(Yindex, 1);
    assert(Ydep0_ >= 0);
}
References dependency(), Ydep0_, Ydep1_, and Yindex_.
Referenced by initCinfo().
setZindex()
void HHChannel2D::setZindex (string index)
Definition at line 183 of file HHChannel2D.cpp.
{
    if(Zindex == Zindex_)
        return;
    Zindex_ = Zindex;
    Zdep0_ = dependency(Zindex, 0);
    Zdep1_ = dependency(Zindex, 1);
    assert(Zdep0_ >= 0);
}
References dependency(), Zdep0_, Zdep1_, and Zindex_.
Referenced by initCinfo().
vCreateGate()
void HHChannel2D::vCreateGate (const Eref & e, string gateType) override virtual
Function for safely creating each gate, identified by strings as X, Y and Z. Will only work on a new channel, not on a copy. The idea is that the gates are always referred to the original 'library' channel, and their contents cannot be touched except by the original.
Implements HHChannelBase.
Definition at line 451 of file HHChannel2D.cpp.
{
    if(!checkOriginal(e.id())) {
        cout << "Warning: HHChannel2D::createGate: Not allowed from copied "
                "channel:\n"
             << e.id().path() << "\n";
        return;
    }
    if(gateType == "X")
        innerCreateGate("xGate", &xGate_, e.id(), Id(e.id().value() + 1));
    else if(gateType == "Y")
        innerCreateGate("yGate", &yGate_, e.id(), Id(e.id().value() + 2));
    else if(gateType == "Z")
        innerCreateGate("zGate", &zGate_, e.id(), Id(e.id().value() + 3));
    else
        cout << "Warning: HHChannel2D::createGate: Unknown gate type '"
             << gateType << "'. Ignored\n";
}
References checkOriginal(), Eref::id(), Id::Id(), innerCreateGate(), Id::path(), Id::value(), xGate_, yGate_, and zGate_.
vProcess()
void HHChannel2D::vProcess (const Eref & e, ProcPtr p) override virtual
processFunc handles the update and calculations every clock tick. It first sends the request for evaluation of the gate variables to the respective gate objects and recieves their response immediately through a return message. This is done so that many channel instances can share the same gate lookup tables, but do so cleanly. Such messages should never go to a remote node. Then the function does its own little calculations to send back to the parent compartment through regular messages.
Implements ChanBase.
Definition at line 300 of file HHChannel2D.cpp.
{
    g_ += ChanBase::getGbar(e);
    double A = 0;
    double B = 0;
    if(Xpower_ > 0) {
        xGate_->lookupBoth(depValue(Xdep0_), depValue(Xdep1_), &A, &B);
        if(instant_ & INSTANT_X)
            X_ = A / B;
        else
            X_ = integrate(X_, info->dt, A, B);
        g_ *= takeXpower_(X_, Xpower_);
    }
    if(Ypower_ > 0) {
        yGate_->lookupBoth(depValue(Ydep0_), depValue(Ydep1_), &A, &B);
        if(instant_ & INSTANT_Y)
            Y_ = A / B;
        else
            Y_ = integrate(Y_, info->dt, A, B);
        g_ *= takeYpower_(Y_, Ypower_);
    }
    if(Zpower_ > 0) {
        zGate_->lookupBoth(depValue(Zdep0_), depValue(Zdep1_), &A, &B);
        if(instant_ & INSTANT_Z)
            Z_ = A / B;
        else
            Z_ = integrate(Z_, info->dt, A, B);
        g_ *= takeZpower_(Z_, Zpower_);
    }
    ChanBase::setGk(e, g_ * vGetModulation(e));
    updateIk();
    // Gk_ = g_;
    // Ik_ = ( Ek_ - Vm_ ) * g_;
    // Send out the relevant channel messages.
    sendProcessMsgs(e, info);
    g_ = 0.0;
}
References depValue(), ProcInfo::dt, HHChannelBase::g_, ChanBase::getGbar(), HHChannelBase::instant_, HHChannelBase::INSTANT_X, HHChannelBase::INSTANT_Y, HHChannelBase::INSTANT_Z, HHChannelBase::integrate(), HHGate2D::lookupBoth(), ChanCommon::sendProcessMsgs(), ChanBase::setGk(), HHChannelBase::takeXpower_, HHChannelBase::takeYpower_, HHChannelBase::takeZpower_, ChanCommon::updateIk(), ChanCommon::vGetModulation(), HHChannelBase::X_, Xdep0_, Xdep1_, xGate_, HHChannelBase::Xpower_, HHChannelBase::Y_, Ydep0_, Ydep1_, yGate_, HHChannelBase::Ypower_, HHChannelBase::Z_, Zdep0_, Zdep1_, zGate_, and HHChannelBase::Zpower_.
vReinit()
void HHChannel2D::vReinit (const Eref & er, ProcPtr info) override virtual
Reinitializes the values for the channel. This involves computing the steady-state value for the channel gates using the provided Vm from the parent compartment. It involves a similar cycle through the gates and then updates to the parent compartment as for the processFunc.
Here we get the steady-state values for the gate (the 'instant' calculation) as A_/B_.
Implements ChanBase.
Definition at line 348 of file HHChannel2D.cpp.
{
    g_ = ChanBase::getGbar(er);
    Element *e = er.element();
    double A = 0.0;
    double B = 0.0;
    if(Xpower_ > 0) {
        xGate_->lookupBoth(depValue(Xdep0_), depValue(Xdep1_), &A, &B);
        if(B < EPSILON) {
            cout << "Warning: B_ value for " << e->getName()
                 << " is ~0. Check X table\n";
            return;
        }
        if(!xInited_)
            X_ = A / B;
        g_ *= takeXpower_(X_, Xpower_);
    }
    if(Ypower_ > 0) {
        yGate_->lookupBoth(depValue(Ydep0_), depValue(Ydep1_), &A, &B);
        if(B < EPSILON) {
            cout << "Warning: B value for " << e->getName()
                 << " is ~0. Check Y table\n";
            return;
        }
        if(!yInited_)
            Y_ = A / B;
        g_ *= takeYpower_(Y_, Ypower_);
    }
    if(Zpower_ > 0) {
        zGate_->lookupBoth(depValue(Zdep0_), depValue(Zdep1_), &A, &B);
        if(B < EPSILON) {
            cout << "Warning: B value for " << e->getName()
                 << " is ~0. Check Z table\n";
            return;
        }
        if(!zInited_)
            Z_ = A / B;
        g_ *= takeZpower_(Z_, Zpower_);
    }
    ChanBase::setGk(er, g_ * vGetModulation(er));
    updateIk();
    // Gk_ = g_;
    // Ik_ = ( Ek_ - Vm_ ) * g_;
    // Send out the relevant channel messages.
    // Same for reinit as for process.
    sendReinitMsgs(er, info);
    g_ = 0.0;
}
References depValue(), Eref::element(), HHChannelBase::EPSILON, HHChannelBase::g_, ChanBase::getGbar(), Element::getName(), HHGate2D::lookupBoth(), ChanCommon::sendReinitMsgs(), ChanBase::setGk(), HHChannelBase::takeXpower_, HHChannelBase::takeYpower_, HHChannelBase::takeZpower_, ChanCommon::updateIk(), ChanCommon::vGetModulation(), HHChannelBase::X_, Xdep0_, Xdep1_, xGate_, HHChannelBase::xInited_, HHChannelBase::Xpower_, HHChannelBase::Y_, Ydep0_, Ydep1_, yGate_, HHChannelBase::yInited_, HHChannelBase::Ypower_, HHChannelBase::Z_, Zdep0_, Zdep1_, zGate_, HHChannelBase::zInited_, and HHChannelBase::Zpower_.
Member Data Documentation
conc1_
double HHChannel2D::conc1_ private
Definition at line 140 of file HHChannel2D.h.
Referenced by conc1(), depValue(), and HHChannel2D().
conc2_
double HHChannel2D::conc2_ private
Definition at line 141 of file HHChannel2D.h.
Referenced by conc2(), depValue(), and HHChannel2D().
Xdep0_
int HHChannel2D::Xdep0_ private
Definition at line 147 of file HHChannel2D.h.
Referenced by HHChannel2D(), setXindex(), vProcess(), and vReinit().
Xdep1_
int HHChannel2D::Xdep1_ private
Definition at line 148 of file HHChannel2D.h.
Referenced by HHChannel2D(), setXindex(), vProcess(), and vReinit().
xGate_
HHGate2D* HHChannel2D::xGate_ private
HHGate2D data structure for the xGate. This is writable only on the HHChannel that originally created the HHGate, for others it must be treated as readonly.
Definition at line 159 of file HHChannel2D.h.
Referenced by checkOriginal(), destroyGate(), getNumXgates(), getXgate(), HHChannel2D(), vCreateGate(), vProcess(), and vReinit().
Xindex_
string HHChannel2D::Xindex_ private
Definition at line 143 of file HHChannel2D.h.
Referenced by getXindex(), and setXindex().
Ydep0_
int HHChannel2D::Ydep0_ private
Definition at line 149 of file HHChannel2D.h.
Referenced by HHChannel2D(), setYindex(), vProcess(), and vReinit().
Ydep1_
int HHChannel2D::Ydep1_ private
Definition at line 150 of file HHChannel2D.h.
Referenced by HHChannel2D(), setYindex(), vProcess(), and vReinit().
yGate_
HHGate2D* HHChannel2D::yGate_ private
Definition at line 160 of file HHChannel2D.h.
Referenced by checkOriginal(), destroyGate(), getNumYgates(), getYgate(), HHChannel2D(), vCreateGate(), vProcess(), and vReinit().
Yindex_
string HHChannel2D::Yindex_ private
Definition at line 144 of file HHChannel2D.h.
Referenced by getYindex(), and setYindex().
Zdep0_
int HHChannel2D::Zdep0_ private
Definition at line 151 of file HHChannel2D.h.
Referenced by HHChannel2D(), setZindex(), vProcess(), and vReinit().
Zdep1_
int HHChannel2D::Zdep1_ private
Definition at line 152 of file HHChannel2D.h.
Referenced by HHChannel2D(), setZindex(), vProcess(), and vReinit().
zGate_
HHGate2D* HHChannel2D::zGate_ private
HHGate2D for the yGate.
Definition at line 161 of file HHChannel2D.h.
Referenced by checkOriginal(), destroyGate(), getNumZgates(), getZgate(), HHChannel2D(), vCreateGate(), vProcess(), and vReinit().
Zindex_
string HHChannel2D::Zindex_ private
Definition at line 145 of file HHChannel2D.h.
Referenced by getZindex(), and setZindex().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/biophysics/HHChannel2D.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/biophysics/HHChannel2D.cpp