MOOSE - Multiscale Object Oriented Simulation Environment: Spine Class Reference
Spine Class Reference
#include <Spine.h>
Public Member Functions
double getAngle (const Eref &e) const
Id getHead (const Eref &e) const
double getHeadDiameter (const Eref &e) const
double getHeadLength (const Eref &e) const
double getHeadVolume (const Eref &e) const
double getInclination (const Eref &e) const
double getMaximumSize (const Eref &e) const
double getMinimumSize (const Eref &e) const
double getPsdArea (const Eref &e) const
Id getShaft (const Eref &e) const
double getShaftDiameter (const Eref &e) const
double getShaftLength (const Eref &e) const
double getTotalLength (const Eref &e) const
void setAngle (const Eref &e, double theta)
void setHeadDiameter (const Eref &e, double dia)
void setHeadLength (const Eref &e, double len)
void setHeadVolume (const Eref &e, double vol)
void setInclination (const Eref &e, double phi)
void setMaximumSize (const Eref &e, double len)
void setMinimumSize (const Eref &e, double len)
void setPsdArea (const Eref &e, double area)
void setShaftDiameter (const Eref &e, double dia)
void setShaftLength (const Eref &e, double len)
void setTotalLength (const Eref &e, double len)
Spine ()
Spine (const Neuron *parent)
Static Public Member Functions
static const Cinfo * initCinfo ()
Private Attributes
double maximumSize_
double minimumSize_
const Neuron * parent_
Detailed Description
The Spine is a dendritic spine, typically with 2 compartments, the shaft and the head. It is a FieldElement, so it gets all its values from the parent Neuron. Later we can put in a maturation profile, so that a linear number from 0 to 1 will define all the stages of spine growth from stub to filopodium to mature spine.
Definition at line 24 of file Spine.h.
Constructor & Destructor Documentation
Spine() [1/2]
Spine::Spine ()
Definition at line 172 of file Spine.cpp.
    : parent_( 0 ),
        minimumSize_( 20.0e-9 ),    // 20 nanometres
        maximumSize_( 10.0e-6 )     // 10 microns
{;}
References maximumSize_, minimumSize_, and parent_.
Spine() [2/2]
Spine::Spine (const Neuron * parent)
Definition at line 178 of file Spine.cpp.
    : parent_( parent ),
        minimumSize_( 20.0e-9 ),    // 20 nanometres
        maximumSize_( 10.0e-6 )     // 10 microns
{;}
References maximumSize_, minimumSize_, and parent_.
Referenced by Neuron::Neuron(), and Neuron::Neuron().
Member Function Documentation
getAngle()
double Spine::getAngle (const Eref & e) const
Definition at line 411 of file Spine.cpp.
{
    return 0;
}
Referenced by initCinfo().
getHead()
Id Spine::getHead (const Eref & e) const
Definition at line 197 of file Spine.cpp.
{
    vector< Id > sl = parent_->spineIds( e.fieldIndex() );
    if ( sl.size() > 1 &&
                    sl[1].element()->cinfo()->isA( "CompartmentBase" ) )
        return sl[1];
    return Id();
}
References Element::cinfo(), Id::element(), Eref::fieldIndex(), Id::Id(), Cinfo::isA(), parent_, and Neuron::spineIds().
Referenced by initCinfo().
getHeadDiameter()
double Spine::getHeadDiameter (const Eref & e) const
Definition at line 310 of file Spine.cpp.
{
    vector< Id > sl = parent_->spineIds( e.fieldIndex() );
    if ( sl.size() > 1 &&
            sl[1].element()->cinfo()->isA( "CompartmentBase" ) )
        return Field< double >::get( sl[1], "diameter" );
    return 0.0;
}
References Element::cinfo(), Id::element(), Eref::fieldIndex(), Field< A >::get(), Cinfo::isA(), parent_, and Neuron::spineIds().
Referenced by getHeadVolume(), getPsdArea(), and initCinfo().
getHeadLength()
double Spine::getHeadLength (const Eref & e) const
Definition at line 275 of file Spine.cpp.
{
    vector< Id > sl = parent_->spineIds( e.fieldIndex() );
    if ( sl.size() > 1 &&
                    sl[1].element()->cinfo()->isA( "CompartmentBase" ) )
        return Field< double >::get( sl[1], "length" );
    return 0.0;
}
References Element::cinfo(), Id::element(), Eref::fieldIndex(), Field< A >::get(), Cinfo::isA(), parent_, and Neuron::spineIds().
Referenced by getHeadVolume(), getTotalLength(), initCinfo(), and setTotalLength().
getHeadVolume()
double Spine::getHeadVolume (const Eref & e) const
Definition at line 355 of file Spine.cpp.
{
    double dia = getHeadDiameter( e );
    return getHeadLength( e ) * dia * dia * PI / 4.0;
}
References getHeadDiameter(), getHeadLength(), and PI.
Referenced by initCinfo().
getInclination()
double Spine::getInclination (const Eref & e) const
Definition at line 421 of file Spine.cpp.
{
    return 0;
}
Referenced by initCinfo().
getMaximumSize()
double Spine::getMaximumSize (const Eref & e) const
Definition at line 441 of file Spine.cpp.
{
    return maximumSize_;
}
References maximumSize_.
Referenced by initCinfo().
getMinimumSize()
double Spine::getMinimumSize (const Eref & e) const
Definition at line 431 of file Spine.cpp.
{
    return minimumSize_;
}
References minimumSize_.
Referenced by initCinfo().
getPsdArea()
double Spine::getPsdArea (const Eref & e) const
Definition at line 339 of file Spine.cpp.
{
    double ret = getHeadDiameter( e );
    return ret * ret * PI / 4.0;
}
References getHeadDiameter(), and PI.
Referenced by initCinfo().
getShaft()
Id Spine::getShaft (const Eref & e) const
Definition at line 188 of file Spine.cpp.
{
    const vector< Id >& sl = parent_->spineIds( e.fieldIndex() );
    if ( sl.size() > 0 &&
                    sl[0].element()->cinfo()->isA( "CompartmentBase" ) )
        return sl[0];
    return Id();
}
References Element::cinfo(), Id::element(), Eref::fieldIndex(), Id::Id(), Cinfo::isA(), parent_, and Neuron::spineIds().
Referenced by initCinfo().
getShaftDiameter()
double Spine::getShaftDiameter (const Eref & e) const
Definition at line 247 of file Spine.cpp.
{
    vector< Id > sl = parent_->spineIds( e.fieldIndex() );
    if ( sl.size() > 0 &&
                sl[0].element()->cinfo()->isA( "CompartmentBase" ) )
        return Field< double >::get( sl[0], "diameter" );
    return 0.0;
}
References Element::cinfo(), Id::element(), Eref::fieldIndex(), Field< A >::get(), Cinfo::isA(), parent_, and Neuron::spineIds().
Referenced by initCinfo().
getShaftLength()
double Spine::getShaftLength (const Eref & e) const
Definition at line 206 of file Spine.cpp.
{
    const vector< Id >& sl = parent_->spineIds( e.fieldIndex() );
    if ( sl.size() > 0 &&
                    sl[0].element()->cinfo()->isA( "CompartmentBase" ) )
        return Field< double >::get( sl[0], "length" );
    return 0.0;
}
References Element::cinfo(), Id::element(), Eref::fieldIndex(), Field< A >::get(), Cinfo::isA(), parent_, and Neuron::spineIds().
Referenced by getTotalLength(), initCinfo(), and setTotalLength().
getTotalLength()
double Spine::getTotalLength (const Eref & e) const
Definition at line 388 of file Spine.cpp.
{
    return getHeadLength( e ) + getShaftLength( e );
}
References getHeadLength(), and getShaftLength().
Referenced by initCinfo().
initCinfo()
const Cinfo * Spine::initCinfo () static
Definition at line 17 of file Spine.cpp.
{
        // Field Definitions
        static ReadOnlyElementValueFinfo< Spine, Id > shaft (
            "shaft",
            "Id of spine shaft.",
            &Spine::getShaft
        );
        static ReadOnlyElementValueFinfo< Spine, Id > head (
            "head",
            "Id of spine head.",
            &Spine::getHead
        );
        static ElementValueFinfo< Spine, double > shaftLength (
            "shaftLength",
            "Length of spine shaft.",
            &Spine::setShaftLength,
            &Spine::getShaftLength
        );
        static ElementValueFinfo< Spine, double > shaftDiameter (
            "shaftDiameter",
            "Diameter of spine shaft.",
            &Spine::setShaftDiameter,
            &Spine::getShaftDiameter
        );
        static ElementValueFinfo< Spine, double > headLength (
            "headLength",
            "Length of spine head.",
            &Spine::setHeadLength,
            &Spine::getHeadLength
        );
        static ElementValueFinfo< Spine, double > headDiameter (
            "headDiameter",
            "Diameter of spine head, and also the diameter of the PSD. ",
            &Spine::setHeadDiameter,
            &Spine::getHeadDiameter
        );
        static ElementValueFinfo< Spine, double > psdArea (
            "psdArea",
            "Area of the Post synaptic density, PSD. This is the same as "
            "the cross-section area of spine head, perpendicular to shaft. "
            "Assumes that the head is a cylinder and that its length "
            "does not change. \n"
            "This is useful to scale # of surface molecules on the PSD. ",
            &Spine::setPsdArea,
            &Spine::getPsdArea
        );
        static ElementValueFinfo< Spine, double > headVolume (
            "headVolume",
            "Volume of spine head, treating it as a cylinder. When this is "
            "scaled by the user, both the diameter and the length of the "
            "spine head scale by the cube root of the ratio to the "
            "previous volume. The diameter of the PSD is pegged to the "
            "diameter of the spine head. \n"
            "This is useful to scale total # of molecules in the head. ",
            &Spine::setHeadVolume,
            &Spine::getHeadVolume
        );
        static ElementValueFinfo< Spine, double > totalLength (
            "totalLength",
            "Length of entire spine. Scales both the length of the shaft "
            "and of the spine head, without changing any of the diameters.",
            &Spine::setTotalLength,
            &Spine::getTotalLength
        );
        static ElementValueFinfo< Spine, double > angle (
            "angle",
            "Angle of spine around shaft. Longitude. 0 is away from soma. "
            "Not yet implemented. ",
            &Spine::setAngle,
            &Spine::getAngle
        );
        static ElementValueFinfo< Spine, double > inclination (
            "inclination",
            "inclination of spine with ref to shaft. Normal is 0. "
            "Not yet activated. ",
            &Spine::setInclination,
            &Spine::getInclination
        );
        static ElementValueFinfo< Spine, double > minimumSize (
            "minimumSize",
            "Sanity check for the smallest permitted length or diameter. "
            "Used to avoid unreasonable physiological values, which "
            "are all too easily reached when simulations run unbounded. "
            "Defaults to 20 nanometers, which is somewhat smaller than the "
            "30 nm size estimated for synaptic vesicles. "
            "Does *not* retroactively resize anything. ",
            &Spine::setMinimumSize,
            &Spine::getMinimumSize
        );
        static ElementValueFinfo< Spine, double > maximumSize (
            "maximumSize",
            "Sanity check for the largest permitted length or diameter. "
            "Used to avoid unreasonable physiological values, which "
            "are all too easily reached when simulations run unbounded. "
            "Defaults to 10 microns, which is a pretty monstrous spine. "
            "Does *not* retroactively resize anything. ",
            &Spine::setMaximumSize,
            &Spine::getMaximumSize
        );
        // MsgDest Definitions
        // Shared definitions
        // SrcFinfo Definitions
    static Finfo* spineFinfos[] = {
        &shaft,             // ReadOnlyValue
        &head,              // ReadOnlyValue
        &shaftLength,       // Value
        &shaftDiameter,     // Value
        &headLength,        // Value
        &headDiameter,      // Value
        &psdArea,           // Value
        &headVolume,        // Value
        &totalLength,       // Value
    };
    static string doc[] =
    {
            "Name", "Spine",
            "Author", "Upi Bhalla",
            "Description", "Spine wrapper, used to change its morphology "
            "typically by a message from an adaptor. The Spine class "
            "takes care of a lot of resultant scaling to electrical, "
            "chemical, and diffusion properties. "
    };
    static Dinfo< Spine > dinfo;
    static Cinfo spineCinfo (
        "Spine",
        Neutral::initCinfo(),
        spineFinfos,
        sizeof( spineFinfos ) / sizeof ( Finfo* ),
        &dinfo,
        doc,
        sizeof(doc)/sizeof( string ),
        true // This IS a FieldElement, not be be created directly.
    );
    return &spineCinfo;
}
References Cinfo::Cinfo(), ElementValueFinfo< T, F >::ElementValueFinfo(), getAngle(), getHead(), getHeadDiameter(), getHeadLength(), getHeadVolume(), getInclination(), getMaximumSize(), getMinimumSize(), getPsdArea(), getShaft(), getShaftDiameter(), getShaftLength(), getTotalLength(), Neutral::initCinfo(), ReadOnlyElementValueFinfo< T, F >::ReadOnlyElementValueFinfo(), setAngle(), setHeadDiameter(), setHeadLength(), setHeadVolume(), setInclination(), setMaximumSize(), setMinimumSize(), setPsdArea(), setShaftDiameter(), setShaftLength(), and setTotalLength().
Referenced by Neuron::initCinfo().
setAngle()
void Spine::setAngle (const Eref & e, double theta)
Definition at line 416 of file Spine.cpp.
{
    ;
}
Referenced by initCinfo().
setHeadDiameter()
void Spine::setHeadDiameter (const Eref & e, double dia)
Definition at line 319 of file Spine.cpp.
{
    if ( dia < minimumSize_ )
        dia = minimumSize_;
    else if ( dia > maximumSize_ )
        dia = maximumSize_;
    vector< Id > sl = parent_->spineIds( e.fieldIndex() );
    if ( sl.size() > 1 &&
            sl[0].element()->cinfo()->isA( "CompartmentBase") )
    {
        double origLen = Field< double >::get( sl[1], "length" );
        double origDia = Field< double >::get( sl[1], "diameter" );
        SetGet2< double, double >::set(
            sl[1], "setGeomAndElec", origLen, dia );
        parent_->scaleHeadDiffusion( e.fieldIndex(), origLen, dia );
        parent_->scaleBufAndRates( e.fieldIndex(),
                        1.0, dia/origDia );
    }
}
References Element::cinfo(), Id::element(), Eref::fieldIndex(), Field< A >::get(), Cinfo::isA(), maximumSize_, minimumSize_, parent_, Neuron::scaleBufAndRates(), Neuron::scaleHeadDiffusion(), SetGet2< A1, A2 >::set(), and Neuron::spineIds().
Referenced by initCinfo(), and setPsdArea().
setHeadLength()
void Spine::setHeadLength (const Eref & e, double len)
Definition at line 284 of file Spine.cpp.
{
    if ( len < minimumSize_ )
        len = minimumSize_;
    else if ( len > maximumSize_ )
        len = maximumSize_;
    vector< Id > sl = parent_->spineIds( e.fieldIndex() );
    if ( sl.size() > 1 &&
                    sl[1].element()->cinfo()->isA( "CompartmentBase") )
    {
        double origDia = Field< double >::get( sl[1], "diameter" );
        double origLen = Field< double >::get( sl[1], "length" );
        SetGet2< double, double >::set(
            sl[1], "setGeomAndElec", len, origDia );
        // Here we've set the electrical and geometrical stuff. Now to
        // do the diffusion.
        // Assume the scaleDiffusion function propagates changes into the
        // VoxelJunctions used by the Dsolve.
        parent_->scaleHeadDiffusion( e.fieldIndex(), len, origDia );
        // Now scale the chem stuff. The PSD mesh is assumed to scale only
        // with top surface area of head, so it is not affected here.
        parent_->scaleBufAndRates( e.fieldIndex(), len/origLen, 1.0 );
    }
}
References Element::cinfo(), Id::element(), Eref::fieldIndex(), Field< A >::get(), Cinfo::isA(), maximumSize_, minimumSize_, parent_, Neuron::scaleBufAndRates(), Neuron::scaleHeadDiffusion(), SetGet2< A1, A2 >::set(), and Neuron::spineIds().
Referenced by initCinfo(), and setTotalLength().
setHeadVolume()
void Spine::setHeadVolume (const Eref & e, double vol)
Definition at line 362 of file Spine.cpp.
{
    if ( volume < 0 )
        volume = 0.0;
    double dia = pow( volume * 4.0 / PI, 1.0/3.0 );
    if ( dia < minimumSize_ )
        volume = pow( minimumSize_, 3.0 ) * PI / 4.0;
    else if ( dia > maximumSize_ )
        volume = pow( maximumSize_, 3.0 ) * PI / 4.0;
    vector< Id > sl = parent_->spineIds( e.fieldIndex() );
    if ( sl.size() > 1 &&
            sl[0].element()->cinfo()->isA( "CompartmentBase") )
    {
        double origLen = Field< double >::get( sl[1], "length" );
        double origDia = Field< double >::get( sl[1], "diameter" );
        double oldVolume = origLen * origDia * origDia * PI / 4.0;
        double ratio = pow( volume / oldVolume, 1.0/3.0 );
        SetGet2< double, double >::set(
            sl[1], "setGeomAndElec", origLen * ratio, origDia * ratio );
        parent_->scaleHeadDiffusion( e.fieldIndex(), origLen * ratio, origDia * ratio );
        parent_->scaleBufAndRates( e.fieldIndex(), ratio, ratio );
    }
}
References Element::cinfo(), Id::element(), Eref::fieldIndex(), Field< A >::get(), Cinfo::isA(), maximumSize_, minimumSize_, parent_, PI, Neuron::scaleBufAndRates(), Neuron::scaleHeadDiffusion(), SetGet2< A1, A2 >::set(), and Neuron::spineIds().
Referenced by initCinfo().
setInclination()
void Spine::setInclination (const Eref & e, double phi)
Definition at line 426 of file Spine.cpp.
{
    ;
}
Referenced by initCinfo().
setMaximumSize()
void Spine::setMaximumSize (const Eref & e, double len)
Definition at line 446 of file Spine.cpp.
{
    maximumSize_ = len;
}
References maximumSize_.
Referenced by initCinfo().
setMinimumSize()
void Spine::setMinimumSize (const Eref & e, double len)
Definition at line 436 of file Spine.cpp.
{
    minimumSize_ = len;
}
References minimumSize_.
Referenced by initCinfo().
setPsdArea()
void Spine::setPsdArea (const Eref & e, double area)
Definition at line 345 of file Spine.cpp.
{
    if ( area < 0 ) {
        setHeadDiameter( e, minimumSize_ );
    } else  {
        double dia = 2.0 * sqrt( area / PI );
        setHeadDiameter( e, dia );
    }
}
References minimumSize_, PI, and setHeadDiameter().
Referenced by initCinfo().
setShaftDiameter()
void Spine::setShaftDiameter (const Eref & e, double dia)
Definition at line 256 of file Spine.cpp.
{
    if ( dia < minimumSize_ )
        dia = minimumSize_;
    else if ( dia > maximumSize_ )
        dia = maximumSize_;
    vector< Id > sl = parent_->spineIds( e.fieldIndex() );
    if ( sl.size() > 1 &&
                    sl[0].element()->cinfo()->isA( "CompartmentBase") )
    {
        double origLen = Field< double >::get( sl[0], "length" );
        SetGet2< double, double >::set(
            sl[0], "setGeomAndElec", origLen, dia );
        // Dia is changing, leave the coords alone.
        parent_->scaleShaftDiffusion( e.fieldIndex(), origLen, dia );
    }
}
References Element::cinfo(), Id::element(), Eref::fieldIndex(), Field< A >::get(), Cinfo::isA(), maximumSize_, minimumSize_, parent_, Neuron::scaleShaftDiffusion(), SetGet2< A1, A2 >::set(), and Neuron::spineIds().
Referenced by initCinfo().
setShaftLength()
void Spine::setShaftLength (const Eref & e, double len)
Definition at line 215 of file Spine.cpp.
{
    if ( len < minimumSize_ )
        len = minimumSize_;
    else if ( len > maximumSize_ )
        len = maximumSize_;
    vector< Id > sl = parent_->spineIds( e.fieldIndex() );
    if ( sl.size() > 1 &&
            sl[0].element()->cinfo()->isA( "CompartmentBase" ) )
    {
        double origDia = Field< double >::get( sl[0], "diameter" );
        double dx = Field< double >::get( sl[0], "x" );
        double dy = Field< double >::get( sl[0], "y" );
        double dz = Field< double >::get( sl[0], "z" );
        SetGet2< double, double >::set(
            sl[0], "setGeomAndElec", len, origDia );
        dx = Field< double >::get( sl[0], "x" ) - dx;
        dy = Field< double >::get( sl[0], "y" ) - dy;
        dz = Field< double >::get( sl[0], "z" ) - dz;
        SetGet3< double, double, double >::set( sl[1], "displace",
            dx, dy, dz );
        // Here we've set the electrical and geometrical stuff. Now to
        // do the diffusion. Chem doesn't come into the picture for the
        // spine shaft.
        // Assume the scaleDiffusion function propagates changes into the
        // VoxelJunctions used by the Dsolve.
        parent_->scaleShaftDiffusion( e.fieldIndex(), len, origDia );
    }
}
References Element::cinfo(), Id::element(), Eref::fieldIndex(), Field< A >::get(), Cinfo::isA(), maximumSize_, minimumSize_, parent_, Neuron::scaleShaftDiffusion(), SetGet2< A1, A2 >::set(), SetGet3< A1, A2, A3 >::set(), and Neuron::spineIds().
Referenced by initCinfo(), and setTotalLength().
setTotalLength()
void Spine::setTotalLength (const Eref & e, double len)
Don't set this if either of them is out of range.
Definition at line 393 of file Spine.cpp.
{
    double shaftLen = getShaftLength( e );
    double headLen = getHeadLength( e );
    double totLen = shaftLen + headLen;
    shaftLen *= len / totLen;
    headLen *= len / totLen;
    if ( shaftLen < minimumSize_ || shaftLen > maximumSize_ ||
        headLen < minimumSize_ || headLen > maximumSize_ )
        return;
    setShaftLength( e, shaftLen );
    setHeadLength( e, headLen );
}
References getHeadLength(), getShaftLength(), maximumSize_, minimumSize_, setHeadLength(), and setShaftLength().
Referenced by initCinfo().
Member Data Documentation
maximumSize_
double Spine::maximumSize_ private
Definition at line 86 of file Spine.h.
Referenced by getMaximumSize(), setHeadDiameter(), setHeadLength(), setHeadVolume(), setMaximumSize(), setShaftDiameter(), setShaftLength(), setTotalLength(), Spine(), and Spine().
minimumSize_
double Spine::minimumSize_ private
Used as a sanity check for assigning dimensions, to avoid unreasonable physiological values. Defaults to 20 nanometers, which is somewhat smaller than the 30 nm size estimated for synaptic vesicles.
Definition at line 85 of file Spine.h.
Referenced by getMinimumSize(), setHeadDiameter(), setHeadLength(), setHeadVolume(), setMinimumSize(), setPsdArea(), setShaftDiameter(), setShaftLength(), setTotalLength(), Spine(), and Spine().
parent_
const Neuron* Spine::parent_ private
Definition at line 78 of file Spine.h.
Referenced by getHead(), getHeadDiameter(), getHeadLength(), getShaft(), getShaftDiameter(), getShaftLength(), setHeadDiameter(), setHeadLength(), setHeadVolume(), setShaftDiameter(), setShaftLength(), Spine(), and Spine().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/biophysics/Spine.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/biophysics/Spine.cpp