MOOSE - Multiscale Object Oriented Simulation Environment: RandSpike Class Reference
RandSpike Class Reference
#include <RandSpike.h>
Public Member Functions
bool getDoPeriodic () const
bool getFired () const
double getLastEvent () const
double getRate () const
double getRefractT () const
void process (const Eref &e, ProcPtr p)
RandSpike ()
void reinit (const Eref &e, ProcPtr p)
void setDoPeriodic (bool val)
void setLastEvent (double val)
void setRate (double rate)
void setRefractT (double val)
Static Public Member Functions
static const Cinfo * initCinfo ()
Private Attributes
bool doPeriodic_
bool fired_
double lastEvent_
double rate_
double realRate_
double refractT_
double threshold_
Detailed Description
Definition at line 13 of file RandSpike.h.
Constructor & Destructor Documentation
RandSpike()
RandSpike::RandSpike ()
Definition at line 125 of file RandSpike.cpp.
    :
    rate_( 0.0 ),
    realRate_( 0.0 ),
    refractT_(0.0),
    lastEvent_(0.0),
    threshold_(0.0),
    fired_( false ),
    doPeriodic_( false )
{
    ;
}
References doPeriodic_, fired_, lastEvent_, rate_, realRate_, refractT_, and threshold_.
Member Function Documentation
getDoPeriodic()
bool RandSpike::getDoPeriodic () const
Definition at line 194 of file RandSpike.cpp.
{
    return doPeriodic_;
}
References doPeriodic_.
Referenced by initCinfo().
getFired()
bool RandSpike::getFired () const
Definition at line 185 of file RandSpike.cpp.
{
    return fired_;
}
References fired_.
Referenced by initCinfo().
getLastEvent()
double RandSpike::getLastEvent () const
Definition at line 180 of file RandSpike.cpp.
{
    return lastEvent_;
}
References lastEvent_.
Referenced by initCinfo().
getRate()
double RandSpike::getRate () const
Definition at line 162 of file RandSpike.cpp.
{
    return rate_;
}
References rate_.
Referenced by initCinfo().
getRefractT()
double RandSpike::getRefractT () const
Definition at line 171 of file RandSpike.cpp.
{
    return refractT_;
}
References refractT_.
Referenced by initCinfo().
initCinfo()
const Cinfo * RandSpike::initCinfo () static
Definition at line 25 of file RandSpike.cpp.
{
    // Shared message definitions
    static DestFinfo process( "process",
                              "Handles process call",
                              new ProcOpFunc< RandSpike >( &RandSpike::process ) );
    static DestFinfo reinit( "reinit",
                             "Handles reinit call",
                             new ProcOpFunc< RandSpike >( &RandSpike::reinit ) );
    static Finfo* processShared[] =
    {
        &process, &reinit
    };
    static SharedFinfo proc( "proc",
                             "Shared message to receive Process message from scheduler",
                             processShared, sizeof( processShared ) / sizeof( Finfo* ) );
    // Dest Finfos.
    // Value Finfos.
    static ValueFinfo< RandSpike, double > rate( "rate",
            "Specifies rate for random spike train. Note that this is"
            "probabilistic, so the instantaneous rate may differ. "
            "If the rate is assigned be message and it varies slowly then "
            "the average firing rate will approach the specified rate",
            &RandSpike::setRate,
            &RandSpike::getRate
                                               );
    static ValueFinfo< RandSpike, double > refractT( "refractT",
            "Refractory Time.",
            &RandSpike::setRefractT,
            &RandSpike::getRefractT
                                                   );
    static ValueFinfo< RandSpike, double > lastEventT( "lastEventT",
            "Time of last event. Set this if you want to phase-shift periodic activity.",
            &RandSpike::setLastEvent,
            &RandSpike::getLastEvent
                                                   );
    static ValueFinfo< RandSpike, double > absRefract( "abs_refract",
            "Absolute refractory time. Synonym for refractT.",
            &RandSpike::setRefractT,
            &RandSpike::getRefractT
                                                     );
    static ValueFinfo< RandSpike, bool > doPeriodic( "doPeriodic",
            "Flag: when false, do Poisson process with specified mean rate.\n"
            "When true, fire periodically at specified rate.\n"
            "Defaults to false. Note that refractory time overrides this: "
            "Rate cannot exceed 1/refractT.",
            &RandSpike::setDoPeriodic,
            &RandSpike::getDoPeriodic
                                                   );
    static ReadOnlyValueFinfo< RandSpike, bool > hasFired( "hasFired",
            "True if RandSpike has just fired",
            &RandSpike::getFired
                                                         );
    static Finfo* spikeGenFinfos[] =
    {
        spikeOut(), // SrcFinfo
        &proc,      // Shared
        &rate,      // Value
        &refractT,  // Value
        &lastEventT,    // Value
        &absRefract,    // Value
        &doPeriodic,    // Value
        &hasFired,  // ReadOnlyValue
    };
    static string doc[] =
    {
        "Name", "RandSpike",
        "Author", "Upi Bhalla",
        "Description", "RandSpike object, generates random or regular "
        "spikes at "
        "specified mean rate. Based closely on GENESIS randspike. "
    };
    static Dinfo< RandSpike > dinfo;
    static Cinfo spikeGenCinfo(
        "RandSpike",
        Neutral::initCinfo(),
        spikeGenFinfos, sizeof( spikeGenFinfos ) / sizeof( Finfo* ),
        &dinfo,
        doc,
        sizeof(doc)/sizeof(string)
    );
    return &spikeGenCinfo;
}
References Cinfo::Cinfo(), DestFinfo::DestFinfo(), getDoPeriodic(), getFired(), getLastEvent(), getRate(), getRefractT(), Neutral::initCinfo(), process(), ProcOpFunc< T >::ProcOpFunc(), ReadOnlyValueFinfo< T, F >::ReadOnlyValueFinfo(), reinit(), setDoPeriodic(), setLastEvent(), setRate(), setRefractT(), SharedFinfo::SharedFinfo(), spikeOut(), and ValueFinfo< T, F >::ValueFinfo().
process()
void RandSpike::process (const Eref & e, ProcPtr p)
Definition at line 204 of file RandSpike.cpp.
{
    if ( refractT_ > p->currTime - lastEvent_  || rate_ <= 0.0 )
        return;
    fired_ = false;
    if (doPeriodic_)
    {
        if ( (p->currTime - lastEvent_) > 1.0/rate_ )
        {
            lastEvent_ = p->currTime;
            spikeOut()->send( e, p->currTime );
            fired_ = true;
        }
    }
    else
    {
        double prob = realRate_ * p->dt;
        if ( prob >= 1.0 || prob >= moose::mtrand() )
        {
            lastEvent_ = p->currTime;
            spikeOut()->send( e, p->currTime );
            fired_ = true;
        }
    }
}
References ProcInfo::currTime, doPeriodic_, ProcInfo::dt, fired_, lastEvent_, moose::mtrand(), rate_, realRate_, refractT_, SrcFinfo1< T >::send(), and spikeOut().
Referenced by initCinfo().
reinit()
void RandSpike::reinit (const Eref & e, ProcPtr p)
Definition at line 232 of file RandSpike.cpp.
{
    if ( rate_ <= 0.0 )
    {
        lastEvent_ = 0.0;
        realRate_ = 0.0;
    }
    else
    {
        double prob = moose::mtrand();
        double m = 1.0 / rate_;
        lastEvent_ = m * log( prob );
    }
}
References lastEvent_, moose::mtrand(), rate_, and realRate_.
Referenced by initCinfo().
setDoPeriodic()
void RandSpike::setDoPeriodic (bool val)
Definition at line 190 of file RandSpike.cpp.
{
    doPeriodic_ = val;
}
References doPeriodic_.
Referenced by initCinfo().
setLastEvent()
void RandSpike::setLastEvent (double val)
Definition at line 176 of file RandSpike.cpp.
{
    lastEvent_ = val;
}
References lastEvent_.
Referenced by initCinfo().
setRate()
void RandSpike::setRate (double rate)
Definition at line 143 of file RandSpike.cpp.
{
    if ( rate < 0.0 )
    {
        cout <<"Warning: RandSpike::setRate: Rate must be >= 0. Using 0.\n";
        rate = 0.0;
    }
    rate_ = rate;
    double prob = 1.0 - rate * refractT_;
    if ( prob <= 0.0 )
    {
        cout << "Warning: RandSpike::setRate: Rate is too high compared to refractory time\n";
        realRate_ = rate_;
    }
    else
    {
        realRate_ = rate_ / prob;
    }
}
References rate_, realRate_, and refractT_.
Referenced by initCinfo().
setRefractT()
void RandSpike::setRefractT (double val)
Definition at line 167 of file RandSpike.cpp.
{
    refractT_ = val;
}
References refractT_.
Referenced by initCinfo().
Member Data Documentation
doPeriodic_
bool RandSpike::doPeriodic_ private
Definition at line 51 of file RandSpike.h.
Referenced by getDoPeriodic(), process(), RandSpike(), and setDoPeriodic().
fired_
bool RandSpike::fired_ private
Definition at line 50 of file RandSpike.h.
Referenced by getFired(), process(), and RandSpike().
lastEvent_
double RandSpike::lastEvent_ private
Definition at line 48 of file RandSpike.h.
Referenced by getLastEvent(), process(), RandSpike(), reinit(), and setLastEvent().
rate_
double RandSpike::rate_ private
Definition at line 45 of file RandSpike.h.
Referenced by getRate(), process(), RandSpike(), reinit(), and setRate().
realRate_
double RandSpike::realRate_ private
Definition at line 46 of file RandSpike.h.
Referenced by process(), RandSpike(), reinit(), and setRate().
refractT_
double RandSpike::refractT_ private
Definition at line 47 of file RandSpike.h.
Referenced by getRefractT(), process(), RandSpike(), setRate(), and setRefractT().
threshold_
double RandSpike::threshold_ private
Definition at line 49 of file RandSpike.h.
Referenced by RandSpike().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/biophysics/RandSpike.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/biophysics/RandSpike.cpp