MOOSE - Multiscale Object Oriented Simulation Environment: Synapse Class Reference
Synapse Class Reference
#include <Synapse.h>
Public Member Functions
void addSpike (const Eref &e, double time)
double getDelay () const
double getTopSpike (const Eref &e) const
double getWeight () const
void setDelay (double v)
void setHandler (SynHandlerBase *h)
void setWeight (double v)
Synapse ()
Static Public Member Functions
static void addMsgCallback (const Eref &e, const string &finfoName, ObjId msg, unsigned int msgLookup)
static void dropMsgCallback (const Eref &e, const string &finfoName, ObjId msg, unsigned int msgLookup)
static const Cinfo * initCinfo ()
Private Attributes
double delay_
SynHandlerBase * handler_
double weight_
Detailed Description
This is the base class for synapses. It is meant to be used as a FieldElement entry on a parent object, derived from the SynHandlerBase.
Definition at line 18 of file Synapse.h.
Constructor & Destructor Documentation
Synapse()
Synapse::Synapse ()
Definition at line 72 of file Synapse.cpp.
    : weight_( 1.0 ), delay_( 0.0 ), handler_( 0 )
{
    ;
}
References delay_, handler_, and weight_.
Member Function Documentation
addMsgCallback()
void Synapse::addMsgCallback (const Eref & e, const string & finfoName, ObjId msg, unsigned int msgLookup) static
Definition at line 126 of file Synapse.cpp.
{
    if ( finfoName == "addSpike" ) {
        ObjId pa = Neutral::parent( e );
        SynHandlerBase* sh =
                reinterpret_cast< SynHandlerBase* >( pa.data() );
        unsigned int synapseNumber = sh->addSynapse();
        SetGet2< unsigned int, unsigned int >::set(
                        msg, "fieldIndex", msgLookup, synapseNumber );
    }
}
References SynHandlerBase::addSynapse(), ObjId::data(), Neutral::parent(), and SetGet2< A1, A2 >::set().
addSpike()
void Synapse::addSpike (const Eref & e, double time)
Definition at line 104 of file Synapse.cpp.
{
    static bool report = false;
    static unsigned int tgtDataIndex = 0;
    // static unsigned int tgtFieldIndex = 0;
    if ( report && e.dataIndex() == tgtDataIndex ) {
        cout << "   " << time << "," << e.fieldIndex();
    }
    handler_->addSpike( e.fieldIndex(), time + delay_, weight_ );
}
References SynHandlerBase::addSpike(), Eref::dataIndex(), delay_, Eref::fieldIndex(), handler_, and weight_.
Referenced by initCinfo().
dropMsgCallback()
void Synapse::dropMsgCallback (const Eref & e, const string & finfoName, ObjId msg, unsigned int msgLookup) static
Definition at line 145 of file Synapse.cpp.
{
    if ( finfoName == "addSpike" ) {
        ObjId pa = Neutral::parent( e );
        SynHandlerBase* sh =
                reinterpret_cast< SynHandlerBase* >( pa.data() );
        sh->dropSynapse( msgLookup );
    }
}
References ObjId::data(), SynHandlerBase::dropSynapse(), and Neutral::parent().
getDelay()
double Synapse::getDelay () const
Definition at line 93 of file Synapse.cpp.
{
    return delay_;
}
References delay_.
Referenced by initCinfo(), and testSetGetSynapse().
getTopSpike()
double Synapse::getTopSpike (const Eref & e) const
Definition at line 115 of file Synapse.cpp.
{
    return handler_->getTopSpike( e.fieldIndex() );
}
References Eref::fieldIndex(), SynHandlerBase::getTopSpike(), and handler_.
Referenced by initCinfo().
getWeight()
double Synapse::getWeight () const
Definition at line 88 of file Synapse.cpp.
{
    return weight_;
}
References weight_.
Referenced by initCinfo(), GraupnerBrunel2012CaPlasticitySynHandler::updateWeight(), GraupnerBrunel2012CaPlasticitySynHandler::vProcess(), and STDPSynHandler::vProcess().
initCinfo()
const Cinfo * Synapse::initCinfo () static
Definition at line 15 of file Synapse.cpp.
{
        static ValueFinfo< Synapse, double > weight(
            "weight",
            "Synaptic weight",
            &Synapse::setWeight,
            &Synapse::getWeight
        );
        static ValueFinfo< Synapse, double > delay(
            "delay",
            "Axonal propagation delay to this synapse",
            &Synapse::setDelay,
            &Synapse::getDelay
        );
        static ElementValueFinfo< Synapse, double > spikeTime(
            "spikeTime",
            "Value field interface to add spike (by assignment) and to "
            "read the value of the spike on top of the queue.",
            &Synapse::addSpike,
            &Synapse::getTopSpike
        );
        static DestFinfo addSpike( "addSpike",
            "Handles arriving spike messages, inserts into event queue.",
            new EpFunc1< Synapse, double >( &Synapse::addSpike ) );
    static Finfo* synapseFinfos[] = {
        &weight,        // Field
        &delay,         // Field
        &spikeTime,     // ElementField
        &addSpike,      // DestFinfo
    };
    static string doc[] =
    {
        "Name", "Synapse",
        "Author", "Upi Bhalla",
        "Description", "Synapse using ring buffer for events.",
    };
    static Dinfo< Synapse > dinfo;
    static Cinfo synapseCinfo (
        "Synapse",
        Neutral::initCinfo(),
        synapseFinfos,
        sizeof( synapseFinfos ) / sizeof ( Finfo* ),
        &dinfo,
        doc,
        sizeof( doc ) / sizeof( string ),
        true // This is a FieldElement.
    );
    return &synapseCinfo;
}
References addSpike(), Cinfo::Cinfo(), DestFinfo::DestFinfo(), ElementValueFinfo< T, F >::ElementValueFinfo(), EpFunc1< T, A >::EpFunc1(), getDelay(), getTopSpike(), getWeight(), Neutral::initCinfo(), setDelay(), setWeight(), and ValueFinfo< T, F >::ValueFinfo().
Referenced by GraupnerBrunel2012CaPlasticitySynHandler::initCinfo(), SeqSynHandler::initCinfo(), SimpleSynHandler::initCinfo(), STDPSynapse::initCinfo(), testSendSpike(), and testSparseMsg().
setDelay()
void Synapse::setDelay (double v)
Definition at line 83 of file Synapse.cpp.
{
    delay_ = v;
}
References delay_.
Referenced by initCinfo(), and testSendSpike().
setHandler()
void Synapse::setHandler (SynHandlerBase * h)
Definition at line 98 of file Synapse.cpp.
{
    handler_ = h;
}
References handler_.
Referenced by GraupnerBrunel2012CaPlasticitySynHandler::addSynapse(), SeqSynHandler::addSynapse(), SimpleSynHandler::addSynapse(), GraupnerBrunel2012CaPlasticitySynHandler::operator=(), SeqSynHandler::operator=(), SimpleSynHandler::operator=(), STDPSynapse::setHandler(), GraupnerBrunel2012CaPlasticitySynHandler::vSetNumSynapses(), SeqSynHandler::vSetNumSynapses(), and SimpleSynHandler::vSetNumSynapses().
setWeight()
void Synapse::setWeight (double v)
Definition at line 78 of file Synapse.cpp.
{
    weight_ = v;
}
References weight_.
Referenced by GraupnerBrunel2012CaPlasticitySynHandler::dropSynapse(), SeqSynHandler::dropSynapse(), SimpleSynHandler::dropSynapse(), STDPSynHandler::dropSynapse(), initCinfo(), testSendSpike(), GraupnerBrunel2012CaPlasticitySynHandler::updateWeight(), and STDPSynHandler::vProcess().
Member Data Documentation
delay_
double Synapse::delay_ private
Definition at line 43 of file Synapse.h.
Referenced by addSpike(), getDelay(), setDelay(), and Synapse().
handler_
SynHandlerBase* Synapse::handler_ private
Definition at line 44 of file Synapse.h.
Referenced by addSpike(), getTopSpike(), setHandler(), and Synapse().
weight_
double Synapse::weight_ private
Definition at line 42 of file Synapse.h.
Referenced by addSpike(), getWeight(), setWeight(), and Synapse().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/synapse/Synapse.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/synapse/Synapse.cpp