MOOSE - Multiscale Object Oriented Simulation Environment: VoxelPoolsBase Class Reference
VoxelPoolsBase Class Reference abstract
#include <VoxelPoolsBase.h>
Public Member Functions
void addProxyTransferIndex (unsigned int comptIndex, unsigned int transferIndex)
void addProxyVoxy (unsigned int comptIndex, Id comptId, unsigned int voxel)
Adds the index of a voxel to which proxy data should go.
void backwardReacVolumeFactor (unsigned int i, double volume)
const double * Cinit () const
void filterCrossRateTerms (const vector< Id > &offSolverReacs, const vector< pair< Id, Id > > &offSolverReacCompts)
void forwardReacVolumeFactor (unsigned int i, double volume)
double getConcInit (unsigned int) const
double getDiffConst (unsigned int) const
double getN (unsigned int) const
double getR1 (unsigned int) const
double getVolume () const
Return the volume of the voxel.
double getXreacScaleProducts (unsigned int i) const
double getXreacScaleSubstrates (unsigned int i) const
bool hasXfer (unsigned int comptIndex) const
True when this voxel has data to be transferred.
bool isVoxelJunctionPresent (Id i1, Id i2) const
void print () const
Debugging utility.
void reinit ()
void resetXreacScale (unsigned int size)
void resizeArrays (unsigned int totNumPools)
Allocate # of pools.
const double * S () const
void scaleVolsBufsRates (double ratio, const Stoich *stoichPtr)
void setConcInit (unsigned int, double v)
void setDiffConst (unsigned int, double v)
void setN (unsigned int i, double v)
void setNumVoxels (unsigned int)
void setVolume (double vol)
Just assigns the volume without any cascading to other values.
virtual void setVolumeAndDependencies (double vol)
unsigned int size () const
vector< double > & Svec ()
Returns a handle to the mol # vector.
virtual void updateAllRateTerms (const vector< RateTerm * > &rates, unsigned int numCoreRates)=0
virtual void updateRateTerms (const vector< RateTerm * > &rates, unsigned int numCoreRates, unsigned int index)=0
double * varCinit ()
double * varS ()
VoxelPoolsBase ()
void xferIn (const vector< unsigned int > &poolIndex, const vector< double > &values, const vector< double > &lastValues, unsigned int voxelIndex)
void xferInOnlyProxies (const vector< unsigned int > &poolIndex, const vector< double > &values, unsigned int numProxyPools, unsigned int voxelIndex)
void xferOut (unsigned int voxelIndex, vector< double > &values, const vector< unsigned int > &poolIndex)
Assembles data values for sending out for x-compt reacs.
virtual ~VoxelPoolsBase ()
Protected Attributes
unsigned int numVoxels_
vector< RateTerm * > rates_
const Stoich * stoichPtr_
Private Attributes
vector< double > Cinit_
map< Id, unsigned int > proxyComptMap_
vector< vector< unsigned int > > proxyPoolVoxels_
vector< vector< unsigned int > > proxyTransferIndex_
vector< double > S_
double volume_
vector< double > xReacScaleProducts_
vector< double > xReacScaleSubstrates_
Detailed Description
This is the base class for voxels used in reac-diffusion systems. Each voxel manages all the molecular pools that live in it. This is the S_ and Cinit_ vectors. Additionally, the last set of entries in S_ and Cinit_ refer to the proxy pools that participate in cross-node reactions, but are really located on other compartments.
Definition at line 31 of file VoxelPoolsBase.h.
Constructor & Destructor Documentation
VoxelPoolsBase()
VoxelPoolsBase::VoxelPoolsBase ()
Definition at line 24 of file VoxelPoolsBase.cpp.
                               :
    stoichPtr_( 0 ),
    S_(1),
    Cinit_(1),
    volume_(1.0)
{
    ;
}
References Cinit_, S_, stoichPtr_, and volume_.
Referenced by GssaVoxelPools::GssaVoxelPools().
~VoxelPoolsBase()
VoxelPoolsBase::~VoxelPoolsBase () virtual
Definition at line 33 of file VoxelPoolsBase.cpp.
{}
Member Function Documentation
addProxyTransferIndex()
void VoxelPoolsBase::addProxyTransferIndex (unsigned int comptIndex, unsigned int transferIndex)
Definition at line 258 of file VoxelPoolsBase.cpp.
{
    if ( comptIndex >= proxyTransferIndex_.size() )
        proxyTransferIndex_.resize( comptIndex + 1 );
    proxyTransferIndex_[comptIndex].push_back( transferIndex );
}
References proxyTransferIndex_.
addProxyVoxy()
void VoxelPoolsBase::addProxyVoxy (unsigned int comptIndex, Id comptId, unsigned int voxel)
Adds the index of a voxel to which proxy data should go.
Definition at line 246 of file VoxelPoolsBase.cpp.
{
    if ( comptIndex >= proxyPoolVoxels_.size() )
    {
        proxyPoolVoxels_.resize( comptIndex + 1 );
    }
    proxyPoolVoxels_[comptIndex].push_back( voxel );
    proxyComptMap_[otherComptId] = comptIndex;
}
References proxyComptMap_, and proxyPoolVoxels_.
backwardReacVolumeFactor()
void VoxelPoolsBase::backwardReacVolumeFactor (unsigned int i, double volume)
Multiply in scale factor for different cross-reac volumes, to be applied to specified RateTerm in the rates_ vector. Applies to backward reaction terms
Definition at line 304 of file VoxelPoolsBase.cpp.
{
    assert( i < xReacScaleProducts_.size() );
    xReacScaleProducts_[i] *= volume / getVolume();
    // cout << "backwardReacVolumeFactor[" << i << "] = "<< xReacScaleProducts_[i] <<endl;
}
References getVolume(), and xReacScaleProducts_.
Cinit()
const double * VoxelPoolsBase::Cinit () const
Returns the array of doubles of initial mol #s at the specified mesh index
Definition at line 72 of file VoxelPoolsBase.cpp.
{
    return &Cinit_[0];
}
References Cinit_.
filterCrossRateTerms()
void VoxelPoolsBase::filterCrossRateTerms (const vector< Id > & offSolverReacs, const vector< pair< Id, Id > > & offSolverReacCompts)
Changes cross rate terms to zero if there is no junction
Zeroes out rate terms that are involved in cross-reactions that are not present on current voxel.
Definition at line 325 of file VoxelPoolsBase.cpp.
{
    assert (offSolverReacs.size() == offSolverReacCompts.size() );
    // unsigned int numCoreRates = stoichPtr_->getNumCoreRates();
    for ( unsigned int i = 0; i < offSolverReacCompts.size(); ++i )
    {
        const pair< Id, Id >& p = offSolverReacCompts[i];
        if ( !isVoxelJunctionPresent( p.first, p.second) )
        {
            Id reacId = offSolverReacs[i];
            const Cinfo* reacCinfo = reacId.element()->cinfo();
            unsigned int k = stoichPtr_->convertIdToReacIndex( offSolverReacs[i] );
            // Start by replacing the immediate cross reaction term.
            if ( rates_[k] )
                delete rates_[k];
            rates_[k] = new ExternReac;
            if ( stoichPtr_->getOneWay() )
            {
                k++; // Delete the next entry too, it is the reverse reacn.
                assert( k < rates_.size() );
                if ( reacCinfo->isA( "Reac" ) )
                {
                    if ( rates_[k] )
                        delete rates_[k];
                    rates_[k] = new ExternReac;
                }
                if ( reacCinfo->isA( "Enz" ) )   // Delete next two.
                {
                    if ( rates_[k] )
                        delete rates_[k];
                    rates_[k] = new ExternReac;
                    k++;
                    assert( k < rates_.size() );
                    if ( rates_[k] )
                        delete rates_[k];
                    rates_[k] = new ExternReac;
                }
            }
            else
            {
                if ( reacCinfo->isA( "Enz" ) )   // Delete next one.
                {
                    k++;
                    assert( k < rates_.size() );
                    if ( rates_[k] )
                        delete rates_[k];
                    rates_[k] = new ExternReac;
                }
            }
        }
    }
}
References Element::cinfo(), Stoich::convertIdToReacIndex(), Id::element(), Stoich::getOneWay(), Cinfo::isA(), isVoxelJunctionPresent(), rates_, and stoichPtr_.
forwardReacVolumeFactor()
void VoxelPoolsBase::forwardReacVolumeFactor (unsigned int i, double volume)
Multiply in scale factor for different cross-reac volumes, to be applied to specified RateTerm in the rates_ vector. Applies to forward reaction terms
Definition at line 297 of file VoxelPoolsBase.cpp.
{
    assert( i < xReacScaleSubstrates_.size() );
    xReacScaleSubstrates_[i] *= volume / getVolume();
    // cout << "forwardReacVolumeFactor[" << i << "] = " << xReacScaleSubstrates_[i] <<endl;
}
References getVolume(), and xReacScaleSubstrates_.
getConcInit()
double VoxelPoolsBase::getConcInit (unsigned int i) const
Definition at line 176 of file VoxelPoolsBase.cpp.
{
    return Cinit_[i];
}
References Cinit_.
Referenced by Gsolve::getConcInit(), and Ksolve::getConcInit().
getDiffConst()
double VoxelPoolsBase::getDiffConst (unsigned int i) const
Definition at line 186 of file VoxelPoolsBase.cpp.
{
    return 0;
}
getN()
double VoxelPoolsBase::getN (unsigned int i) const
Definition at line 158 of file VoxelPoolsBase.cpp.
{
    return S_[i];
}
References S_.
Referenced by Gsolve::getN(), and Ksolve::getN().
getR1()
double VoxelPoolsBase::getR1 (unsigned int i) const
Definition at line 163 of file VoxelPoolsBase.cpp.
{
    return rates_[i]->getR1();
}
References RateTerm::getR1(), and rates_.
Referenced by Gsolve::getR1(), Ksolve::getR1(), and Ksolve::getR1vec().
getVolume()
double VoxelPoolsBase::getVolume () const
Return the volume of the voxel.
Definition at line 92 of file VoxelPoolsBase.cpp.
{
    return volume_;
}
References volume_.
Referenced by backwardReacVolumeFactor(), forwardReacVolumeFactor(), Gsolve::getVolumeOfPool(), Ksolve::getVolumeOfPool(), scaleVolsBufsRates(), GssaVoxelPools::updateAllRateTerms(), VoxelPools::updateAllRateTerms(), GssaVoxelPools::updateRateTerms(), VoxelPools::updateRateTerms(), Gsolve::volume(), and Ksolve::volume().
getXreacScaleProducts()
double VoxelPoolsBase::getXreacScaleProducts (unsigned int i) const
Return scale factor for specified entry on rate terms. Index is # of cross-compartment rate term.
Definition at line 316 of file VoxelPoolsBase.cpp.
{
    return xReacScaleProducts_[i];
}
References xReacScaleProducts_.
Referenced by scaleVolsBufsRates(), GssaVoxelPools::updateAllRateTerms(), VoxelPools::updateAllRateTerms(), GssaVoxelPools::updateRateTerms(), and VoxelPools::updateRateTerms().
getXreacScaleSubstrates()
double VoxelPoolsBase::getXreacScaleSubstrates (unsigned int i) const
Return scale factor for specified entry on rate terms. Index is # of cross-compartment rate term.
Definition at line 311 of file VoxelPoolsBase.cpp.
{
    return xReacScaleSubstrates_[i];
}
References xReacScaleSubstrates_.
Referenced by scaleVolsBufsRates(), GssaVoxelPools::updateAllRateTerms(), VoxelPools::updateAllRateTerms(), GssaVoxelPools::updateRateTerms(), and VoxelPools::updateRateTerms().
hasXfer()
bool VoxelPoolsBase::hasXfer (unsigned int comptIndex) const
True when this voxel has data to be transferred.
Assigns the Id and volume of the specified x-reac coupled compartment void setComptVolume(unsigned int comptIndex, Id id, double vol);
Definition at line 266 of file VoxelPoolsBase.cpp.
{
    if ( comptIndex >= proxyPoolVoxels_.size() )
        return false;
    return (proxyPoolVoxels_[ comptIndex ].size() > 0);
}
References proxyPoolVoxels_.
isVoxelJunctionPresent()
bool VoxelPoolsBase::isVoxelJunctionPresent (Id i1, Id i2) const
True when there is a junction. i1 must match, and if i2 is non-zero then it too must match.
Definition at line 273 of file VoxelPoolsBase.cpp.
{
    if ( i1 == Id () )
        return false;
    if ( proxyComptMap_.find( i1 ) == proxyComptMap_.end() )
        return false;
    if ( i2 == Id() ) // This is intentionally blank, only one jn.
        return true;
    // If there is an i2 but it isn't on the map, then not connected.
    if ( proxyComptMap_.find( i2 ) == proxyComptMap_.end() )
        return false;
    return true;
}
References Id::Id(), Id::operator==(), and proxyComptMap_.
Referenced by filterCrossRateTerms().
print()
void VoxelPoolsBase::print () const
Debugging utility.
Definition at line 381 of file VoxelPoolsBase.cpp.
{
    cout << "S_.size=" << S_.size() << ", volume = " << volume_ << endl;
    cout << "proxyPoolsVoxels.size()=" << proxyPoolVoxels_.size() <<
         ", proxyTransferIndex.size()=" << proxyTransferIndex_.size() <<
         endl;
    assert( proxyPoolVoxels_.size() == proxyTransferIndex_.size() );
    for ( unsigned int i = 0; i < proxyPoolVoxels_.size(); ++i )
    {
        cout << "ppv[" << i << "]=";
        const vector< unsigned int >& ppv = proxyPoolVoxels_[i];
        for ( unsigned int j = 0; j < ppv.size(); ++j )
        {
            cout << "   " << ppv[j];
        }
        cout << endl;
    }
    for ( unsigned int i = 0; i < proxyTransferIndex_.size(); ++i )
    {
        cout << "pti[" << i << "]=";
        const vector< unsigned int >& pti = proxyTransferIndex_[i];
        for ( unsigned int j = 0; j < pti.size(); ++j )
        {
            cout << "   " << pti[j];
        }
        cout << endl;
    }
    cout <<
         "xReacScaleSubstrates.size()=" << xReacScaleSubstrates_.size() <<
         ", xReacScaleProducts.size()=" << xReacScaleProducts_.size() <<
         endl;
    assert( xReacScaleSubstrates_.size() == xReacScaleProducts_.size() );
    for ( unsigned int i = 0; i < xReacScaleSubstrates_.size(); ++i )
    {
        cout << i << "  " << xReacScaleSubstrates_[i] << "  " <<
             xReacScaleProducts_[i] << endl;
    }
    cout << "##############    RATES    ######################\n";
    for ( unsigned int i = 0; i < rates_.size(); ++i )
    {
        cout << i << "  :   " << rates_[i]->getR1() << ",   " <<
             rates_[i]->getR2() << endl;
    }
}
References RateTerm::getR1(), RateTerm::getR2(), proxyPoolVoxels_, proxyTransferIndex_, rates_, S_, volume_, xReacScaleProducts_, and xReacScaleSubstrates_.
Referenced by VoxelPools::print().
reinit()
void VoxelPoolsBase::reinit ()
Assigns S = NA * vol * Cinit and sets up initial dt.
Definition at line 46 of file VoxelPoolsBase.cpp.
{
    S_.resize( Cinit_.size() );
    for( size_t i = 0; i < S_.size(); ++ i ) {
        S_[i] = Cinit_[i] * NA * volume_;
    }
}
References Cinit_, NA, S_, and volume_.
Referenced by GssaVoxelPools::reinit(), VoxelPools::reinit(), and VoxelPools::setStoich().
resetXreacScale()
void VoxelPoolsBase::resetXreacScale (unsigned int size)
Initialize/reset the vector xReacScaling_ for scale factors for each cross reaction in this voxel.
Definition at line 291 of file VoxelPoolsBase.cpp.
{
    xReacScaleSubstrates_.assign( size, 1.0 );
    xReacScaleProducts_.assign( size, 1.0 );
}
References xReacScaleProducts_, and xReacScaleSubstrates_.
resizeArrays()
void VoxelPoolsBase::resizeArrays (unsigned int totNumPools)
Allocate # of pools.
Using the computed array sizes, now allocate space for them.
Definition at line 40 of file VoxelPoolsBase.cpp.
{
    S_.resize( totNumPools, 0.0 );
    Cinit_.resize( totNumPools, 0.0);
}
References Cinit_, and S_.
Referenced by Ksolve::notifyAddPool(), Gsolve::setNumPools(), Ksolve::setNumPools(), and Ksolve::setNumVarTotPools().
S()
const double * VoxelPoolsBase::S () const
Returns the array of doubles of current mol #s at the specified mesh index
Definition at line 57 of file VoxelPoolsBase.cpp.
{
    return &S_[0];
}
References S_.
Referenced by Gsolve::getBlock(), Ksolve::getBlock(), GssaVoxelPools::refreshAtot(), and GssaVoxelPools::updateDependentRates().
scaleVolsBufsRates()
void VoxelPoolsBase::scaleVolsBufsRates (double ratio, const Stoich * stoichPtr)
Definition at line 109 of file VoxelPoolsBase.cpp.
{
    volume_ *= ratio; // Scale vol
    // Here we also need to set the Ns for the buffered pools.
    unsigned int start = stoichPtr_->getNumVarPools();
    unsigned int end = start + stoichPtr_->getNumBufPools();
    assert( end == Cinit_.size() );
    for ( unsigned int i = start; i < end; ++i )
    {
        // Must not reassign pools that are controlled by functions.
        if ( !stoichPtr->isFuncTarget(i) )
            S_[i] = Cinit_[i] * NA * volume_;
    }
    // Scale rates. Start by clearing out old rates if any
    for ( unsigned int i = 0; i < rates_.size(); ++i )
        delete( rates_[i] );
    unsigned int numCoreRates = stoichPtr->getNumCoreRates();
    const vector< RateTerm* >& rates = stoichPtr->getRateTerms();
    rates_.resize( rates.size() );
    for ( unsigned int i = 0; i < numCoreRates; ++i )
        rates_[i] = rates[i]->copyWithVolScaling( getVolume(), 1, 1 );
    for ( unsigned int i = numCoreRates; i < rates.size(); ++i )
    {
        rates_[i] = rates[i]->copyWithVolScaling(  getVolume(),
                    getXreacScaleSubstrates(i - numCoreRates),
                    getXreacScaleProducts(i - numCoreRates ) );
    }
}
References Cinit_, RateTerm::copyWithVolScaling(), Stoich::getNumBufPools(), Stoich::getNumCoreRates(), Stoich::getNumVarPools(), Stoich::getRateTerms(), getVolume(), getXreacScaleProducts(), getXreacScaleSubstrates(), Stoich::isFuncTarget(), NA, rates_, S_, stoichPtr_, and volume_.
Referenced by Stoich::scaleBufsAndRates().
setConcInit()
void VoxelPoolsBase::setConcInit (unsigned int i, double v)
Definition at line 169 of file VoxelPoolsBase.cpp.
{
    Cinit_[i] = v;
    if ( Cinit_[i] < 0.0 )
        Cinit_[i] = 0.0;
}
References Cinit_.
Referenced by Gsolve::setConcInit(), and Ksolve::setConcInit().
setDiffConst()
void VoxelPoolsBase::setDiffConst (unsigned int i, double v)
Definition at line 181 of file VoxelPoolsBase.cpp.
{
    ; // Do nothing.
}
setN()
void VoxelPoolsBase::setN (unsigned int i, double v)
Definition at line 151 of file VoxelPoolsBase.cpp.
{
    S_[i] = v;
    if ( S_[i] < 0.0 )
        S_[i] = 0.0;
}
References S_.
Referenced by Gsolve::setN(), and Ksolve::setN().
setNumVoxels()
void VoxelPoolsBase::setNumVoxels (unsigned int n)
Definition at line 142 of file VoxelPoolsBase.cpp.
{
    numVoxels_ = n;
}
References numVoxels_.
Referenced by Ksolve::reinit().
setVolume()
void VoxelPoolsBase::setVolume (double vol)
Just assigns the volume without any cascading to other values.
Definition at line 87 of file VoxelPoolsBase.cpp.
{
    volume_ = vol;
}
References volume_.
Referenced by KsolveBase::setCompartment(), and Gsolve::setCompartment().
setVolumeAndDependencies()
void VoxelPoolsBase::setVolumeAndDependencies (double vol) virtual
Assign the volume, and handle the cascading effects by scaling all the dependent values of n.
Reimplemented in GssaVoxelPools, and VoxelPools.
Definition at line 97 of file VoxelPoolsBase.cpp.
{
    double ratio = vol / volume_;
    volume_ = vol;
    for ( vector< double >::iterator i = S_.begin(); i != S_.end(); ++i )
        *i *= ratio;
    // I would like to update the xReacScaleSubstreates and Products here,
    // but I don't know the order of their reactions. So leave it to
    // a subsequent call via Ksolve or Stoich.
}
References S_, and volume_.
Referenced by GssaVoxelPools::setVolumeAndDependencies(), and VoxelPools::setVolumeAndDependencies().
size()
unsigned int VoxelPoolsBase::size () const
Returns # of pools
Definition at line 82 of file VoxelPoolsBase.cpp.
{
    return Cinit_.size();
}
References Cinit_.
Referenced by VoxelPools::advance(), Gsolve::getBlock(), Ksolve::getBlock(), Gsolve::getNumPools(), Ksolve::getNumPools(), VoxelPools::lsodaSys(), Ksolve::notifyAddPool(), Gsolve::setBlock(), Ksolve::setBlock(), Gsolve::setNvec(), and Ksolve::setNvec().
Svec()
vector< double > & VoxelPoolsBase::Svec ()
Returns a handle to the mol # vector.
Definition at line 62 of file VoxelPoolsBase.cpp.
{
    return S_;
}
References S_.
Referenced by VoxelPools::advance(), GssaVoxelPools::advance(), Gsolve::getNvec(), Ksolve::getNvec(), and VoxelPools::lsodaSys().
updateAllRateTerms()
virtual void VoxelPoolsBase::updateAllRateTerms (const vector< RateTerm * > & rates, unsigned int numCoreRates) pure virtual
Reassign entire rate vector.
Implemented in GssaVoxelPools, and VoxelPools.
updateRateTerms()
virtual void VoxelPoolsBase::updateRateTerms (const vector< RateTerm * > & rates, unsigned int numCoreRates, unsigned int index) pure virtual
Update specified index on rate terms. The entire rates vector is passed in for the source values, the index specifies which entry on the local rate vector is to be updated.
Implemented in GssaVoxelPools, and VoxelPools.
varCinit()
double * VoxelPoolsBase::varCinit ()
Returns the array of doubles of initial mol #s at the specified mesh index, as a writable array.
Definition at line 77 of file VoxelPoolsBase.cpp.
{
    return &Cinit_[0];
}
References Cinit_.
varS()
double * VoxelPoolsBase::varS ()
Returns the array of doubles of current mol #s at the specified mesh index. Dangerous, allows one to modify the values.
Definition at line 67 of file VoxelPoolsBase.cpp.
{
    return &S_[0];
}
References S_.
Referenced by VoxelPools::advance(), GssaVoxelPools::advance(), GssaVoxelPools::refreshAtot(), GssaVoxelPools::reinit(), Gsolve::setBlock(), Ksolve::setBlock(), Gsolve::setNvec(), Ksolve::setNvec(), GssaVoxelPools::updateDependentMathExpn(), and GssaVoxelPools::xferIn().
xferIn()
void VoxelPoolsBase::xferIn (const vector< unsigned int > & poolIndex, const vector< double > & values, const vector< double > & lastValues, unsigned int voxelIndex)
Digests incoming data values for cross-compt reactions. Sums the changes in the values onto the specified pools.
Definition at line 194 of file VoxelPoolsBase.cpp.
{
    unsigned int offset = voxelIndex * poolIndex.size();
    vector< double >::const_iterator i = values.begin() + offset;
    vector< double >::const_iterator j = lastValues.begin() + offset;
    for ( vector< unsigned int >::const_iterator
            k = poolIndex.begin(); k != poolIndex.end(); ++k )
    {
        S_[*k] += *i++ - *j++;
    }
}
References S_.
xferInOnlyProxies()
void VoxelPoolsBase::xferInOnlyProxies (const vector< unsigned int > & poolIndex, const vector< double > & values, unsigned int numProxyPools, unsigned int voxelIndex)
Used during initialization: Takes only the proxy pool values from the incoming transfer data, and assigns it to the proxy pools on current solver
Definition at line 210 of file VoxelPoolsBase.cpp.
{
    unsigned int offset = voxelIndex * poolIndex.size();
    vector< double >::const_iterator i = values.begin() + offset;
    unsigned int proxyEndIndex = stoichPtr_->getNumVarPools() +
                                 stoichPtr_->getNumProxyPools();
    for ( vector< unsigned int >::const_iterator
            k = poolIndex.begin(); k != poolIndex.end(); ++k )
    {
        if ( *k >= stoichPtr_->getNumVarPools() && *k < proxyEndIndex )
        {
            Cinit_[*k] = *i / ( NA * volume_ );
            S_[*k] = *i;
        }
        i++;
    }
}
References Cinit_, Stoich::getNumProxyPools(), Stoich::getNumVarPools(), NA, S_, stoichPtr_, and volume_.
xferOut()
void VoxelPoolsBase::xferOut (unsigned int voxelIndex, vector< double > & values, const vector< unsigned int > & poolIndex)
Assembles data values for sending out for x-compt reacs.
Definition at line 232 of file VoxelPoolsBase.cpp.
{
    unsigned int offset = voxelIndex * poolIndex.size();
    vector< double >::iterator i = values.begin() + offset;
    for ( vector< unsigned int >::const_iterator
            k = poolIndex.begin(); k != poolIndex.end(); ++k )
    {
        *i++ = S_[*k];
    }
}
References S_.
Member Data Documentation
Cinit_
vector< double > VoxelPoolsBase::Cinit_ private
Cinit_ specifies initial conc at t = 0. Whenever the reac system is rebuilt or reinited, all S_ values become set to Cinit. scaled for volume and NA. Also used for buffered molecules as the fixed values of these molecules.
Definition at line 246 of file VoxelPoolsBase.h.
Referenced by Cinit(), getConcInit(), reinit(), resizeArrays(), scaleVolsBufsRates(), setConcInit(), size(), varCinit(), VoxelPoolsBase(), and xferInOnlyProxies().
numVoxels_
unsigned int VoxelPoolsBase::numVoxels_ protected
Number of voxels. If > 1, set flag for LSODA to handle molecule flux on each timestep during diffusion, which slows it down.
Definition at line 220 of file VoxelPoolsBase.h.
Referenced by VoxelPools::advance(), and setNumVoxels().
proxyComptMap_
map< Id, unsigned int > VoxelPoolsBase::proxyComptMap_ private
Looks up comptIndex from compt. Actually just a set would do.
Definition at line 265 of file VoxelPoolsBase.h.
Referenced by addProxyVoxy(), and isVoxelJunctionPresent().
proxyPoolVoxels_
vector< vector< unsigned int > > VoxelPoolsBase::proxyPoolVoxels_ private
proxyPoolVoxels_[comptIndex][#] Used to build the transfer vector. Stores the voxels of proxy pools in specified compartment,
Definition at line 253 of file VoxelPoolsBase.h.
Referenced by addProxyVoxy(), hasXfer(), and print().
proxyTransferIndex_
vector< vector< unsigned int > > VoxelPoolsBase::proxyTransferIndex_ private
proxyTransferIndex_[comptIndex][#] Stores the index in the transfer vector for proxy pools that live on this voxel. The poolIndex and # of pools is known from the xferPoolIdx_ vector stored on the Ksolve.
Definition at line 260 of file VoxelPoolsBase.h.
Referenced by addProxyTransferIndex(), and print().
rates_
vector< RateTerm* > VoxelPoolsBase::rates_ protected
Definition at line 215 of file VoxelPoolsBase.h.
Referenced by filterCrossRateTerms(), getR1(), GssaVoxelPools::getReacVelocity(), VoxelPools::print(), print(), scaleVolsBufsRates(), GssaVoxelPools::updateAllRateTerms(), VoxelPools::updateAllRateTerms(), VoxelPools::updateRates(), GssaVoxelPools::updateRateTerms(), VoxelPools::updateRateTerms(), VoxelPools::updateReacVelocities(), GssaVoxelPools::updateReacVelocities(), GssaVoxelPools::~GssaVoxelPools(), and VoxelPools::~VoxelPools().
S_
vector< double > VoxelPoolsBase::S_ private
S_ is the array of molecules. Stored as n, number of molecules per mesh entry. The poolIndex specifies which molecular species pool to use.
The first numVarPools_ in the poolIndex are state variables and are integrated using the ODE solver or the GSSA solver. The next numBufPools_ are fixed but can be changed by the script. The next numFuncPools_ are computed using arbitrary functions of any of the molecule levels, and the time. The functions evaluate before the solver. The functions should not cascade as there is no guarantee of execution order.
Definition at line 237 of file VoxelPoolsBase.h.
Referenced by getN(), print(), reinit(), resizeArrays(), S(), scaleVolsBufsRates(), setN(), setVolumeAndDependencies(), Svec(), varS(), VoxelPoolsBase(), xferIn(), xferInOnlyProxies(), and xferOut().
stoichPtr_
const Stoich* VoxelPoolsBase::stoichPtr_ protected
Definition at line 214 of file VoxelPoolsBase.h.
Referenced by VoxelPools::advance(), filterCrossRateTerms(), VoxelPools::getMethod(), VoxelPools::lsodaSys(), VoxelPools::print(), scaleVolsBufsRates(), GssaVoxelPools::setStoich(), VoxelPools::setStoich(), GssaVoxelPools::setVolumeAndDependencies(), VoxelPools::setVolumeAndDependencies(), VoxelPools::updateRates(), VoxelPools::updateReacVelocities(), VoxelPoolsBase(), and xferInOnlyProxies().
volume_
double VoxelPoolsBase::volume_ private
This is what I would need to fully identify proxy compts and voxels for each proxy reac. vector< Id, Id, unsigned int, unsigned int> proxyComptVoxel Volume of voxel.
Definition at line 275 of file VoxelPoolsBase.h.
Referenced by getVolume(), print(), reinit(), scaleVolsBufsRates(), setVolume(), setVolumeAndDependencies(), VoxelPoolsBase(), and xferInOnlyProxies().
xReacScaleProducts_
vector< double > VoxelPoolsBase::xReacScaleProducts_ private
xReacScaleProducts_[crossRateTermIndex] Product of productVol/voxelVol for each of the products, for reverse reacs. Applied to R2 of the RateTerm. Used only for cross reactions.
Definition at line 291 of file VoxelPoolsBase.h.
Referenced by backwardReacVolumeFactor(), getXreacScaleProducts(), print(), and resetXreacScale().
xReacScaleSubstrates_
vector< double > VoxelPoolsBase::xReacScaleSubstrates_ private
xReacScaleSubstrates_[crossRateTermIndex] Product of substrateVol/voxelVol for each of the substrates, for forward reacs. Applied to R1 of the RateTerm. Used only for cross reactions.
Definition at line 283 of file VoxelPoolsBase.h.
Referenced by forwardReacVolumeFactor(), getXreacScaleSubstrates(), print(), and resetXreacScale().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/ksolve/VoxelPoolsBase.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/ksolve/VoxelPoolsBase.cpp