MOOSE - Multiscale Object Oriented Simulation Environment: HSolveUtils::Grid Class Reference
HSolveUtils::Grid Class Reference
#include <HSolveUtils.h>
Public Member Functions
double entry (unsigned int i)
Grid (double min, double max, unsigned int divs)
bool operator== (const Grid &other)
unsigned int size ()
Public Attributes
unsigned int divs_
double dx_
double max_
double min_
Detailed Description
Definition at line 42 of file HSolveUtils.h.
Constructor & Destructor Documentation
Grid()
HSolveUtils::Grid::Grid (double min, double max, unsigned int divs) inline
Definition at line 45 of file HSolveUtils.h.
            :
            min_( min ),
            max_( max ),
            divs_( divs )
        {
            dx_ = ( max_ - min_ ) / divs_;
        }
References divs_, dx_, max_, and min_.
Referenced by HSolveActive::createLookupTables(), and HSolveUtils::rates().
Member Function Documentation
entry()
double HSolveUtils::Grid::entry (unsigned int i)
Definition at line 198 of file HSolveUtils.cpp.
{
    assert( i <= divs_ + 1 );
    return ( min_ + dx_ * i );
}
References divs_, dx_, and min_.
Referenced by HSolveUtils::rates().
operator==()
bool HSolveUtils::Grid::operator== (const Grid & other) inline
Definition at line 57 of file HSolveUtils.h.
        {
            return
                min_ == other.min_ &&
                max_ == other.max_ &&
                divs_ == other.divs_;
        }
References divs_, max_, and min_.
Referenced by HSolveUtils::rates().
size()
unsigned int HSolveUtils::Grid::size ()
Definition at line 193 of file HSolveUtils.cpp.
{
    return divs_ + 1;
}
References divs_.
Referenced by HSolveActive::createLookupTables(), and HSolveUtils::rates().
Member Data Documentation
divs_
unsigned int HSolveUtils::Grid::divs_
Definition at line 67 of file HSolveUtils.h.
Referenced by entry(), Grid(), operator==(), and size().
dx_
double HSolveUtils::Grid::dx_
Definition at line 68 of file HSolveUtils.h.
Referenced by entry(), and Grid().
max_
double HSolveUtils::Grid::max_
Definition at line 66 of file HSolveUtils.h.
Referenced by Grid(), and operator==().
min_
double HSolveUtils::Grid::min_
Definition at line 65 of file HSolveUtils.h.
Referenced by entry(), Grid(), and operator==().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/hsolve/HSolveUtils.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/hsolve/HSolveUtils.cpp