MOOSE - Multiscale Object Oriented Simulation Environment: ReadSwc Class Reference
ReadSwc Class Reference
#include <ReadSwc.h>
Public Member Functions
void assignKids ()
bool build (Id parent, double lambda, double RM, double RA, double CM)
void cleanMultipointSoma ()
void cleanZeroLength ()
void diagnostics () const
void parseBranches ()
ReadSwc (const string &fname)
bool testIfOnlyBasalsArePresent () const
void traverseBranch (const SwcSegment &s, double &len, double &L, vector< int > &cable) const
bool validate () const
Private Attributes
vector< SwcBranch > branches_
vector< SwcSegment > segs_
Detailed Description
This class is used to read in SWC files as found in NeuroMorph.org and other places. Note that these are only passive models at this stage.
Definition at line 18 of file ReadSwc.h.
Constructor & Destructor Documentation
ReadSwc()
ReadSwc::ReadSwc (const string & fname)
Each line is of the form n T x y z R P
Definition at line 38 of file ReadSwc.cpp.
{
    ifstream fin(fname.c_str());
    if (!fin) {
        cerr << "ReadSwc:: could not open file " << fname << endl;
        return;
    }
    string temp;
    int badSegs = 0;
    while (getline(fin, temp)) {
        if (isWhitespaceOnly(temp))
            continue;
        auto pos = temp.find_first_not_of("\t ");
        if (pos == string::npos)
            continue;
        if (temp[pos] == '#')
            continue;
        SwcSegment t(temp);
        if (t.OK())
            segs_.push_back(SwcSegment(temp));
        else
            badSegs++;
    }
    bool valid = validate();
    if (valid) {
        assignKids();
        cleanMultipointSoma();
        cleanZeroLength();
        parseBranches();
    }
    cout << "ReadSwc: " << fname << "    : NumSegs = " << segs_.size()
         << ", bad = " << badSegs << ", Validated = " << valid
         << ", numBranches = " << branches_.size() << endl;
    diagnostics();
}
References assignKids(), branches_, cleanMultipointSoma(), cleanZeroLength(), diagnostics(), isWhitespaceOnly(), SwcSegment::OK(), parseBranches(), segs_, SwcSegment::SwcSegment(), and validate().
Referenced by Shell::doLoadModel().
Member Function Documentation
assignKids()
void ReadSwc::assignKids ()
Definition at line 108 of file ReadSwc.cpp.
{
    for (unsigned int i = 0; i < segs_.size(); ++i) {
        const SwcSegment& s = segs_[i];
        assert(s.parent() != s.myIndex());
        if (s.parent() != ~0U) {
            segs_[s.parent() - 1].addChild(i + 1);
        }
    }
    for (unsigned int i = 0; i < segs_.size(); ++i) {
        segs_[i].figureOutType();
    }
}
References SwcSegment::addChild(), SwcSegment::figureOutType(), SwcSegment::myIndex(), SwcSegment::parent(), and segs_.
Referenced by ReadSwc().
build()
bool ReadSwc::build (Id parent, double lambda, double RM, double RA, double CM)
Definition at line 382 of file ReadSwc.cpp.
{
    Shell* shell = reinterpret_cast<Shell*>(Id().eref().data());
    vector<Id> compts(segs_.size());
    unsigned int numSomas = 0;
    unsigned int numRootAxons = 0;
    unsigned int numRootBasals = 0;
    unsigned int numRootDends = 0;
    vector<unsigned int> numBranchesOnMyParent(branches_.size(), 0);
    vector<string> parentName(segs_.size());
    string segName;
    string basalName = "basal";
    if (testIfOnlyBasalsArePresent())
        basalName = "dend";
    for (unsigned int i = 0; i < branches_.size(); ++i) {
        SwcBranch& br = branches_[i];
        unsigned int myBranchIdx = numBranchesOnMyParent[br.parent()];
        numBranchesOnMyParent[br.parent()]++;
        for (unsigned int j = 0; j < br.segs_.size(); ++j) {
            stringstream ss;
            Id compt;
            SwcSegment& seg = segs_[br.segs_[j] - 1];
            unsigned int paIndex = seg.parent();
            if (paIndex == ~0U)  // root soma
            {
                // Check for 2-point soma: a live SOMA-type direct child whose
                // coordinates define the distal end of the soma cylinder.
                const SwcSegment* distalSoma = nullptr;
                for (int k : seg.kids()) {
                    if (segs_[k - 1].OK() &&
                        segs_[k - 1].type() == SwcSegment::SOMA) {
                        distalSoma = &segs_[k - 1];
                        break;
                    }
                }
                if (distalSoma) {
                    // 2-point soma: seg is proximal (root), distalSoma is distal.
                    // makeCompt uses the first arg as the distal segment to get
                    // len = distance(distal, proximal) since distal->parent != ~0U.
                    compt = makeCompt(parent, "soma", *distalSoma, seg, RM, RA, CM);
                    // Pre-fill the distal soma's slot so it's found when its
                    // branch or cable entry is processed later.
                    compts[distalSoma->myIndex() - 1] = compt;
                }
                else {
                    // 1-point soma: artificial cylinder of length = 2*r.
                    compt = makeCompt(parent, "soma", seg, seg, RM, RA, CM);
                }
                numSomas++;
            }
            else if (seg.type() == SwcSegment::SOMA) {
                // Distal end of a 2-point soma: compartment was already created
                // when the root soma was processed and stored in compts[].
                compt = compts[seg.myIndex() - 1];
                if (compt == Id()) {
                    // Defensive fallback (should not occur with valid SWC).
                    SwcSegment& pa = segs_[paIndex - 1];
                    compt = makeCompt(parent, "soma", seg, pa, RM, RA, CM);
                    numSomas++;
                }
                // Do NOT increment numSomas again — already counted at root soma.
            }
            else {
                SwcSegment& pa = segs_[paIndex - 1];
                if (pa.type() != seg.type()) {
                    if (seg.type() == SwcSegment::AXON) {
                        ss << "axon" << numRootAxons;
                        segName = ss.str();
                        numRootAxons++;
                    }
                    else if (seg.type() == SwcSegment::BASAL) {
                        ss << basalName << numRootBasals;
                        segName = ss.str();
                        numRootBasals++;
                    }
                    else {  // Everything else is a dend.
                        ss << "dend" << numRootDends;
                        segName = ss.str();
                        numRootDends++;
                    }
                }
                else if (j == 0) {  // extend name with branch idx
                    const string& paName =
                        compts[paIndex - 1].element()->getName();
                    string paBranchName = paName.substr(0, paName.rfind('_'));
                    ss << paBranchName << "." << myBranchIdx << "_0";
                    segName = ss.str();
                }
                else {
                    const string& paName =
                        compts[paIndex - 1].element()->getName();
                    string paBranchName = paName.substr(0, paName.rfind('_'));
                    ss << paBranchName << "_" << j;
                    segName = ss.str();
                }
                compt = makeCompt(parent, segName, seg, pa, RM, RA, CM);
                assert(compt != Id());
                assert(compts[paIndex - 1] != Id());
                shell->doAddMsg("Single", compts[paIndex - 1], "axial", compt,
                                "raxial");
            }
            assert(compt != Id());
            compts[seg.myIndex() - 1] = compt;
        }
    }
    return true;
}
References SwcSegment::AXON, SwcSegment::BASAL, branches_, Eref::data(), Shell::doAddMsg(), Id::element(), Id::eref(), Element::getName(), Id::Id(), SwcSegment::kids(), makeCompt(), SwcSegment::myIndex(), SwcSegment::OK(), Id::operator!=(), Id::operator==(), SwcSegment::parent(), segs_, SwcBranch::segs_, SwcSegment::SOMA, testIfOnlyBasalsArePresent(), and SwcSegment::type().
Referenced by Shell::doLoadModel().
cleanMultipointSoma()
void ReadSwc::cleanMultipointSoma ()
Definition at line 148 of file ReadSwc.cpp.
{
    // Find the root soma segment (parent == ~0U)
    int rootIdx = -1;
    for (unsigned int i = 0; i < segs_.size(); ++i) {
        if (segs_[i].parent() == ~0U) {
            rootIdx = static_cast<int>(i);
            break;
        }
    }
    if (rootIdx < 0 || segs_[rootIdx].type() != SwcSegment::SOMA)
        return;
    SwcSegment& soma = segs_[rootIdx];
    // Warn if the soma does not match the NeuroMorpho.org 3-point convention:
    // exactly 2 direct soma children, all sharing x,z,radius with root,
    // and y-offsets of exactly ±radius.
    static const double EPS = 1e-3;  // microns
    vector<int> directSomaKids;
    for (int k : soma.kids()) {
        if (segs_[k - 1].type() == SwcSegment::SOMA)
            directSomaKids.push_back(k);
    }
    if (directSomaKids.size() == 2) {
        const SwcSegment& s2 = segs_[directSomaKids[0] - 1];
        const SwcSegment& s3 = segs_[directSomaKids[1] - 1];
        double xs = soma.vec().a0(), ys = soma.vec().a1(), zs = soma.vec().a2(),
               rs = soma.radius();
        bool xzMatch =
            fabs(s2.vec().a0() - xs) < EPS && fabs(s2.vec().a2() - zs) < EPS &&
            fabs(s3.vec().a0() - xs) < EPS && fabs(s3.vec().a2() - zs) < EPS;
        bool radiiMatch =
            fabs(s2.radius() - rs) < EPS && fabs(s3.radius() - rs) < EPS;
        bool yMatch = (fabs(s2.vec().a1() - (ys - rs)) < EPS &&
                       fabs(s3.vec().a1() - (ys + rs)) < EPS) ||
                      (fabs(s3.vec().a1() - (ys - rs)) < EPS &&
                       fabs(s2.vec().a1() - (ys + rs)) < EPS);
        if (!xzMatch || !radiiMatch || !yMatch)
            cout << "ReadSwc::cleanMultipointSoma: Warning: 3-point soma "
                    "does not match "
                 << "NeuroMorpho.org convention"
                 << (!xzMatch ? " [x,z coords differ]" : "")
                 << (!radiiMatch ? " [radii differ]" : "")
                 << (!yMatch ? " [y-offsets != ±r]" : "") << endl;
    }
    else if (!directSomaKids.empty()) {
        // 1 child: may be 2-point (Arbor) soma or a chained soma.
        // >2 children: contour soma or non-standard file.
        cout << "ReadSwc::cleanMultipointSoma: Note: soma has "
             << directSomaKids.size() << " direct soma-type child(ren) "
             << "(NeuroMorpho.org standard expects 2)." << endl;
    }
    // 2-point soma (Arbor style): single direct SOMA child with no chained
    // SOMA grandchildren beneath it. Both points define the cylinder geometry
    // — do not collapse.
    if (directSomaKids.size() == 1) {
        int onlyKidIdx = directSomaKids[0];
        bool hasSomaGrandkids = false;
        for (int gk : segs_[onlyKidIdx - 1].kids()) {
            if (segs_[gk - 1].type() == SwcSegment::SOMA) {
                hasSomaGrandkids = true;
                break;
            }
        }
        if (!hasSomaGrandkids) {
            cout << "ReadSwc::cleanMultipointSoma: 2-point soma detected; "
                    "preserving geometry."
                 << endl;
            return;
        }
        // else: chained soma (child has soma grandkids) — fall through to collapse.
    }
    // Use a queue to handle chained soma segments (e.g. 1->2->3->dendrite)
    // not just direct children of root.
    vector<int> toProcess = soma.kids();
    vector<int> newKids;
    while (!toProcess.empty()) {
        vector<int> nextToProcess;
        for (int k : toProcess) {
            SwcSegment& kid = segs_[k - 1];
            if (kid.type() == SwcSegment::SOMA) {
                for (int grandkid : kid.kids()) {
                    segs_[grandkid - 1].setParent(soma.myIndex());
                    nextToProcess.push_back(grandkid);
                }
                kid.setBad();
                cout << "ReadSwc:: Merged multi-point soma segment " << k
                     << " into root soma" << endl;
            }
            else {
                newKids.push_back(k);
            }
        }
        toProcess = nextToProcess;
    }
    soma.replaceKids(newKids);
}
References Vec::a0(), Vec::a1(), Vec::a2(), SwcSegment::kids(), SwcSegment::myIndex(), SwcSegment::parent(), SwcSegment::radius(), SwcSegment::replaceKids(), segs_, SwcSegment::setBad(), SwcSegment::setParent(), SwcSegment::SOMA, SwcSegment::type(), and SwcSegment::vec().
Referenced by ReadSwc().
cleanZeroLength()
void ReadSwc::cleanZeroLength ()
Definition at line 122 of file ReadSwc.cpp.
{
    static double EPSILON = 1e-2;  // Assume units in microns.
    for (unsigned int i = 1; i < segs_.size(); ++i) {
        SwcSegment& s = segs_[i];
        SwcSegment& pa = segs_[s.parent() - 1];
        if (s.distance(pa) < EPSILON) {
            // Remove the zero length child from pa.kids_
            vector<int> temp;
            for (unsigned int j = 0; j < pa.kids().size(); ++j) {
                if (static_cast<unsigned int>(pa.kids()[j]) != s.myIndex())
                    temp.push_back(pa.kids()[j]);
            }
            // Go through all kids of s and reparent them.
            for (unsigned int j = 0; j < s.kids().size(); ++j) {
                SwcSegment& kid = segs_[s.kids()[j] - 1];
                kid.setParent(pa.myIndex());
                temp.push_back(kid.myIndex());
            }
            pa.replaceKids(temp);
            s.setBad();
            cout << "ReadSwc:: Cleaned zero length " << s.myIndex() << endl;
        }
    }
}
References SwcSegment::distance(), SwcSegment::kids(), SwcSegment::myIndex(), SwcSegment::parent(), SwcSegment::replaceKids(), segs_, SwcSegment::setBad(), and SwcSegment::setParent().
Referenced by ReadSwc().
diagnostics()
void ReadSwc::diagnostics () const
Definition at line 312 of file ReadSwc.cpp.
{
    vector<int> diag(14);
    for (unsigned int i = 0; i < segs_.size(); ++i) {
        const SwcSegment& s = segs_[i];
        if (s.type() < 14)
            diag[s.type()]++;
    }
    for (int i = 0; i < 14; ++i)
        cout << "ReadSwc::diagnostics: " << setw(12) << ": " << setw(5)
             << diag[i] << endl;
}
References segs_, and SwcSegment::type().
Referenced by ReadSwc().
parseBranches()
void ReadSwc::parseBranches ()
Definition at line 274 of file ReadSwc.cpp.
{
    // Fill vector of all branches.
    for (unsigned int i = 0; i < segs_.size(); ++i) {
        const SwcSegment& s = segs_[i];
        // Branch endpoints: root soma (always), forks (≥2 kids), or leaves (0
        // kids). Root must be explicit: after soma chain cleanup it may have
        // exactly 1 kid.
        if (s.OK() && (s.parent() == ~0U || s.kids().size() != 1)) {
            vector<int> cable;
            // int branchIndex = branches_.
            // branches_.push_back( i + 1 );
            double len = 0;
            double L = 0;
            traverseBranch(s, len, L, cable);
            // branchGeomLength_.push_back( len );
            // branchElectroLength_.push_back( L );
            SwcBranch br(branches_.size(), s, len, L, cable);
            branches_.push_back(br);
        }
    }
    // Assign the parent of each branch. This is known because the
    // parent of the first segment in the branch is the last segment
    // in the parent branch. I construct a reverse lookup table to find
    // the branch # from its last segment number.
    vector<int> reverseSeg(segs_.size() + 1, 0);
    for (unsigned int i = 0; i < branches_.size(); ++i)
        reverseSeg[branches_[i].segs_.back()] = i;
    for (unsigned int i = 0; i < branches_.size(); ++i) {
        int parentSeg = segs_[branches_[i].segs_[0] - 1].parent();
        if (parentSeg == ~0U)  // root - no parent
            continue;
        assert(parentSeg != 0);  // Note that segment indices start from 1
        branches_[i].setParent(reverseSeg[parentSeg]);
    }
}
References branches_, SwcSegment::kids(), SwcSegment::OK(), SwcSegment::parent(), segs_, SwcBranch::segs_, SwcSegment::setParent(), SwcBranch::SwcBranch(), and traverseBranch().
Referenced by ReadSwc().
testIfOnlyBasalsArePresent()
bool ReadSwc::testIfOnlyBasalsArePresent () const
Some SWCs label all non-soma segments as basals.
Definition at line 366 of file ReadSwc.cpp.
{
    unsigned int numDend = 0;
    unsigned int numBasal = 0;
    for (unsigned int i = 0; i < branches_.size(); ++i) {
        const SwcBranch& br = branches_[i];
        for (unsigned int j = 0; j < br.segs_.size(); ++j) {
            const SwcSegment& seg = segs_[br.segs_[j] - 1];
            numBasal += (seg.type() == SwcSegment::BASAL);
            numDend += (seg.type() == SwcSegment::DEND);
        }
    }
    return ((numBasal > 0) && (numDend == 0));
}
References SwcSegment::BASAL, branches_, SwcSegment::DEND, segs_, SwcBranch::segs_, and SwcSegment::type().
Referenced by build().
traverseBranch()
void ReadSwc::traverseBranch (const SwcSegment & s, double & len, double & L, vector< int > & cable) const
Definition at line 250 of file ReadSwc.cpp.
{
    const SwcSegment* prev = &s;
    cable.resize(1, s.myIndex());  // Always include the starting seg.
    // Note that the cable is filled up with entries in reverse order.
    if (s.parent() == ~0U) {
        len = s.radius();
        L = sqrt(len);
        return;
    }
    do {
        // Beware the indexing!
        const SwcSegment& pa = segs_[prev->parent() - 1];
        len += pa.distance(*prev);
        L += pa.L();
        cable.push_back(pa.myIndex());
        prev = &pa;
    } while ((prev->parent() != ~0U) && (prev->kids().size() == 1));
    cable.pop_back();  // Get rid of the last entry, it is on the parent.
}
References SwcSegment::distance(), SwcSegment::kids(), SwcSegment::L(), SwcSegment::myIndex(), SwcSegment::parent(), SwcSegment::radius(), and segs_.
Referenced by parseBranches().
validate()
bool ReadSwc::validate () const
Definition at line 76 of file ReadSwc.cpp.
{
    int numStart = 0;
    int numOrphans = 0;
    int badIndex = 0;
    int badRadius = 0;
    for (unsigned int i = 0; i < segs_.size(); ++i) {
        const SwcSegment& s = segs_[i];
        if (s.myIndex() != i + 1)
            badIndex++;
        if (s.parent() == ~0U) {
            numStart++;
        }
        else {
            if (s.parent() > i) {
                numOrphans++;
            }
        }
        if (s.radius() < MinRadius) {
            badRadius++;
        }
    }
    bool valid = (numStart == 1 && numOrphans == 0 && badRadius == 0);
    if (!valid) {
        cout << "ReadSwc::validate() failed: \nNumSegs = " << segs_.size()
             << ", numStart = " << numStart << ", orphans = " << numOrphans
             << ", badIndex = " << badIndex << ", badRadius = " << badRadius
             << ", numBranches = " << branches_.size() << endl;
    }
    return valid;
}
References branches_, MinRadius, SwcSegment::myIndex(), SwcSegment::parent(), SwcSegment::radius(), and segs_.
Referenced by ReadSwc().
Member Data Documentation
branches_
vector< SwcBranch > ReadSwc::branches_ private
branches holds the NeuroMorpho index of the end segment of each branch. Note that NeuroMorph index starts from 1. To traverse the branch, go to the end segment, and traverse through all parents till you get to a fork.
Definition at line 48 of file ReadSwc.h.
Referenced by build(), parseBranches(), ReadSwc(), testIfOnlyBasalsArePresent(), and validate().
segs_
vector< SwcSegment > ReadSwc::segs_ private
Definition at line 40 of file ReadSwc.h.
Referenced by assignKids(), build(), cleanMultipointSoma(), cleanZeroLength(), diagnostics(), parseBranches(), ReadSwc(), testIfOnlyBasalsArePresent(), traverseBranch(), and validate().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/biophysics/ReadSwc.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/biophysics/ReadSwc.cpp