MOOSE - Multiscale Object Oriented Simulation Environment: ZombieHHChannel Class Reference
ZombieHHChannel Class Reference
#include <ZombieHHChannel.h>
Public Member Functions
void vCreateGate (const Eref &e, string name) override
double vGetEk (const Eref &e) const override
double vGetGbar (const Eref &e) const override
double vGetGk (const Eref &e) const override
double vGetIk (const Eref &e) const override
int vGetInstant (const Eref &e) const override
double vGetX (const Eref &e) const override
double vGetY (const Eref &e) const override
double vGetZ (const Eref &e) const override
void vHandleConc (const Eref &e, double value) override
void vHandleVm (double Vm) override
void vProcess (const Eref &e, ProcPtr p) override
void vReinit (const Eref &e, ProcPtr p) override
void vSetEk (const Eref &e, double Ek) override
void vSetGbar (const Eref &e, double Gbar) override
void vSetGk (const Eref &e, double Gk) override
void vSetIk (const Eref &e, double Ik) override
void vSetInstant (const Eref &e, int instant) override
void vSetModulation (const Eref &e, double value) override
void vSetSolver (const Eref &e, Id hsolve) override
void vSetUseConcentration (const Eref &e, int value) override
void vSetX (const Eref &e, double X) override
void vSetXpower (const Eref &e, double Xpower) override
void vSetY (const Eref &e, double Y) override
void vSetYpower (const Eref &e, double Ypower) override
void vSetZ (const Eref &e, double Z) override
void vSetZpower (const Eref &e, double Zpower) override
ZombieHHChannel ()
Public Member Functions inherited from HHChannelBase
virtual bool checkOriginal (Id chanId) const
void createGate (const Eref &e, string gateType)
virtual void destroyGate (const Eref &e, string gateType)
int getInstant (const Eref &e) const
int getUseConcentration (const Eref &e) const
double getX (const Eref &e) const
HHGate * getXgate (unsigned int i)
double getXpower (const Eref &e) const
double getY (const Eref &e) const
HHGate * getYgate (unsigned int i)
double getYpower (const Eref &e) const
double getZ (const Eref &e) const
HHGate * getZgate (unsigned int i)
double getZpower (const Eref &e) const
void handleConc (const Eref &e, double conc)
HHChannelBase ()
bool setGatePower (const Eref &e, double power, double *assignee, const string &gateType)
void setInstant (const Eref &e, int Instant)
void setNumGates (unsigned int num)
void setUseConcentration (const Eref &e, int value)
void setX (const Eref &e, double X)
void setXpower (const Eref &e, double Xpower)
void setY (const Eref &e, double Y)
void setYpower (const Eref &e, double Ypower)
void setZ (const Eref &e, double Z)
void setZpower (const Eref &e, double Zpower)
virtual ~HHChannelBase ()=0
Public Member Functions inherited from ChanCommon
ChanCommon ()
double getGbar () const
Utility function to acces Gbar.
double getVm () const
Utility function to access Vm.
void sendProcessMsgs (const Eref &e, const ProcPtr info)
void sendReinitMsgs (const Eref &e, const ProcPtr info)
void updateIk ()
double vGetModulation (const Eref &e) const override
virtual ~ChanCommon ()=0
Public Member Functions inherited from ChanBase
ChanBase ()
double getEk (const Eref &e) const
double getGbar (const Eref &e) const
double getGk (const Eref &e) const
double getIk (const Eref &e) const
double getModulation (const Eref &e) const
void handleVm (double Vm)
void process (const Eref &e, const ProcPtr info)
void reinit (const Eref &e, const ProcPtr info)
void setEk (const Eref &e, double Ek)
void setGbar (const Eref &e, double Gbar)
void setGk (const Eref &e, double Gk)
void setIk (const Eref &e, double Ic)
void setModulation (const Eref &e, double modulation)
virtual ~ChanBase ()=0
Static Public Member Functions
static const Cinfo * initCinfo ()
Static Public Member Functions inherited from HHChannelBase
static const Cinfo * initCinfo ()
static double power1 (double x, double p)
static double power2 (double x, double p)
static double power3 (double x, double p)
static double power4 (double x, double p)
static double powerN (double x, double p)
static PFDD selectPower (double power)
static void zombify (Element *orig, const Cinfo *zClass, Id hsolve)
Static Public Member Functions inherited from ChanCommon
static const Cinfo * initCinfo ()
Specify the Class Info static variable for initialization.
Static Public Member Functions inherited from ChanBase
static SrcFinfo2< double, double > * channelOut ()
static SrcFinfo1< double > * IkOut ()
static const Cinfo * initCinfo ()
Specify the Class Info static variable for initialization.
static SrcFinfo1< double > * permeability ()
Private Member Functions
void copyFields (Id chanId, HSolve *hsolve_)
Private Attributes
HSolve * hsolve_
Additional Inherited Members
Protected Member Functions inherited from HHChannelBase
double integrate (double state, double dt, double A, double B)
Protected Member Functions inherited from ChanCommon
double getModulation () const
Protected Attributes inherited from HHChannelBase
double g_
int instant_
Id myId_
double(* takeXpower_)(double, double)
double(* takeYpower_)(double, double)
double(* takeZpower_)(double, double)
bool useConcentration_
Flag for use of conc for input to Z gate calculations.
double X_
bool xInited_
Flag to indicate if gates have been created.
double Xpower_
Exponent for X gate.
double Y_
bool yInited_
double Ypower_
Exponent for Y gate.
double Z_
bool zInited_
double Zpower_
Exponent for Z gate.
Protected Attributes inherited from ChanCommon
double Vm_
Vm_ is input variable from compartment, used for most rates.
Static Protected Attributes inherited from HHChannelBase
static const double EPSILON = 1.0e-10
static const int INSTANT_X = 1
static const int INSTANT_Y = 2
static const int INSTANT_Z = 4
Detailed Description
Zombie object that lets HSolve do its calculations, while letting the user interact with this object as if it were the original object.
ZombieHHChannel derives directly from Neutral, unlike the regular HHChannel which derives from ChanBase. ChanBase handles fields like Gbar, Gk, Ek, Ik, which are common to HHChannel, SynChan, etc. On the other hand, these fields are stored separately for HHChannel and SynChan in the HSolver. Hence we cannot have a ZombieChanBase which does, for example: hsolve_->setGk(id, Gk); Instead we must have ZombieHHChannel and ZombieSynChan which do: hsolve_->setHHChannelGk(id, Gk); and: hsolve_->setSynChanGk(id, Gk); respectively.
Definition at line 48 of file ZombieHHChannel.h.
Constructor & Destructor Documentation
ZombieHHChannel()
ZombieHHChannel::ZombieHHChannel ()
Definition at line 44 of file ZombieHHChannel.cpp.
{ ; }
Member Function Documentation
copyFields()
void ZombieHHChannel::copyFields (Id chanId, HSolve * hsolve_) private
initCinfo()
const Cinfo * ZombieHHChannel::initCinfo () static
Definition at line 12 of file ZombieHHChannel.cpp.
{
    static string doc[] =
    {
        "Name", "ZombieHHChannel",
        "Author", "Upinder S. Bhalla, 2007, 2014 NCBS",
        "Description", "ZombieHHChannel: Hodgkin-Huxley type voltage-gated Ion channel. Something "
        "like the old tabchannel from GENESIS, but also presents "
        "a similar interface as hhchan from GENESIS. ",
    };
    static Dinfo< ZombieHHChannel > dinfo;
    static Cinfo zombieHHChannelCinfo(
        "ZombieHHChannel",
        HHChannelBase::initCinfo(),
        0,
        0,
        &dinfo,
        doc,
        sizeof( doc ) / sizeof( string )
    );
    return &zombieHHChannelCinfo;
}
References Cinfo::Cinfo(), and HHChannelBase::initCinfo().
Referenced by HSolve::zombify().
vCreateGate()
void ZombieHHChannel::vCreateGate (const Eref & e, string name) override virtual
Implements HHChannelBase.
Definition at line 185 of file ZombieHHChannel.cpp.
{
    cout << "Warning: ZombieHHChannel::vCreateGate\n";
}
vGetEk()
double ZombieHHChannel::vGetEk (const Eref & e) const override virtual
Reimplemented from ChanCommon.
Definition at line 95 of file ZombieHHChannel.cpp.
{
    return hsolve_->getEk( e.id() );
}
References HSolve::getEk(), hsolve_, and Eref::id().
vGetGbar()
double ZombieHHChannel::vGetGbar (const Eref & e) const override virtual
Reimplemented from ChanCommon.
Definition at line 75 of file ZombieHHChannel.cpp.
{
    return hsolve_->getHHChannelGbar( e.id() );
}
References HSolve::getHHChannelGbar(), hsolve_, and Eref::id().
vGetGk()
double ZombieHHChannel::vGetGk (const Eref & e) const override virtual
Reimplemented from ChanCommon.
Definition at line 85 of file ZombieHHChannel.cpp.
{
    return hsolve_->getGk( e.id() );
}
References HSolve::getGk(), hsolve_, and Eref::id().
vGetIk()
double ZombieHHChannel::vGetIk (const Eref & e) const override virtual
Reimplemented from ChanCommon.
Definition at line 105 of file ZombieHHChannel.cpp.
{
    return hsolve_->getIk( e.id() );
}
References HSolve::getIk(), hsolve_, and Eref::id().
vGetInstant()
int ZombieHHChannel::vGetInstant (const Eref & e) const override virtual
Reimplemented from HHChannelBase.
Definition at line 115 of file ZombieHHChannel.cpp.
{
    return hsolve_->getInstant( e.id() );
}
References HSolve::getInstant(), hsolve_, and Eref::id().
vGetX()
double ZombieHHChannel::vGetX (const Eref & e) const override virtual
Reimplemented from HHChannelBase.
Definition at line 125 of file ZombieHHChannel.cpp.
{
    return hsolve_->getX( e.id() );
}
References HSolve::getX(), hsolve_, and Eref::id().
vGetY()
double ZombieHHChannel::vGetY (const Eref & e) const override virtual
Reimplemented from HHChannelBase.
Definition at line 135 of file ZombieHHChannel.cpp.
{
    return hsolve_->getY( e.id() );
}
References HSolve::getY(), hsolve_, and Eref::id().
vGetZ()
double ZombieHHChannel::vGetZ (const Eref & e) const override virtual
Reimplemented from HHChannelBase.
Definition at line 145 of file ZombieHHChannel.cpp.
{
    return hsolve_->getZ( e.id() );
}
References HSolve::getZ(), hsolve_, and Eref::id().
vHandleConc()
void ZombieHHChannel::vHandleConc (const Eref & e, double value) override virtual
Reimplemented from HHChannelBase.
Definition at line 178 of file ZombieHHChannel.cpp.
{
    hsolve_->addConc(e.id(),conc);
}
References HSolve::addConc(), hsolve_, and Eref::id().
vHandleVm()
void ZombieHHChannel::vHandleVm (double Vm) override virtual
Assign the local Vm_ to the incoming Vm from the compartment
Reimplemented from ChanCommon.
Definition at line 212 of file ZombieHHChannel.cpp.
{;}
vProcess()
void ZombieHHChannel::vProcess (const Eref & e, ProcPtr p) override virtual
Implements ChanBase.
Definition at line 168 of file ZombieHHChannel.cpp.
{
    ;
}
vReinit()
void ZombieHHChannel::vReinit (const Eref & e, ProcPtr p) override virtual
Implements ChanBase.
Definition at line 173 of file ZombieHHChannel.cpp.
{
    ;
}
vSetEk()
void ZombieHHChannel::vSetEk (const Eref & e, double Ek) override virtual
Reimplemented from ChanCommon.
Definition at line 90 of file ZombieHHChannel.cpp.
{
    hsolve_->setEk( e.id(), Ek );
}
References hsolve_, Eref::id(), and HSolve::setEk().
vSetGbar()
void ZombieHHChannel::vSetGbar (const Eref & e, double Gbar) override virtual
Reimplemented from ChanCommon.
Definition at line 69 of file ZombieHHChannel.cpp.
{
    // cout << "in ZombieHHChannel::setGbar( " << e.id().path() << ", " << Gbar << " )\n";
    hsolve_->setHHChannelGbar( e.id(), Gbar );
}
References hsolve_, Eref::id(), and HSolve::setHHChannelGbar().
vSetGk()
void ZombieHHChannel::vSetGk (const Eref & e, double Gk) override virtual
Reimplemented from ChanCommon.
Definition at line 80 of file ZombieHHChannel.cpp.
{
    hsolve_->setGk( e.id(), Gk );
}
References hsolve_, Eref::id(), and HSolve::setGk().
vSetIk()
void ZombieHHChannel::vSetIk (const Eref & e, double Ic) override virtual
Ik is read-only for MOOSE, but we provide the set func for derived classes to update it.
Reimplemented from ChanCommon.
Definition at line 100 of file ZombieHHChannel.cpp.
{
    ;   // dummy
}
vSetInstant()
void ZombieHHChannel::vSetInstant (const Eref & e, int instant) override virtual
Reimplemented from HHChannelBase.
Definition at line 110 of file ZombieHHChannel.cpp.
{
    hsolve_->setInstant( e.id(), instant );
}
References hsolve_, Eref::id(), and HSolve::setInstant().
vSetModulation()
void ZombieHHChannel::vSetModulation (const Eref & e, double value) override virtual
Reimplemented from ChanCommon.
Definition at line 156 of file ZombieHHChannel.cpp.
{
    if ( modulation > 0.0 ) {
            ChanCommon::vSetModulation(e, modulation);
            hsolve_->setHHmodulation( e.id(), modulation );
    }
}
References hsolve_, Eref::id(), HSolve::setHHmodulation(), and ChanCommon::vSetModulation().
vSetSolver()
void ZombieHHChannel::vSetSolver (const Eref & e, Id hsolve) override virtual
Reimplemented from HHChannelBase.
Definition at line 215 of file ZombieHHChannel.cpp.
{
    if ( !hsolve.element()->cinfo()->isA( "HSolve" ) ) {
        cout << "Error: ZombieHHChannel::vSetSolver: Object: " <<
                hsolve.path() << " is not an HSolve. Aborted\n";
        hsolve_ = 0;
        assert( 0 );
        return;
    }
    hsolve_ = reinterpret_cast< HSolve* >( hsolve.eref().data() );
}
References Element::cinfo(), Eref::data(), Id::element(), Id::eref(), hsolve_, Cinfo::isA(), and Id::path().
vSetUseConcentration()
void ZombieHHChannel::vSetUseConcentration (const Eref & e, int value) override virtual
Not trivial to change Ca-dependence once HSolve has been set up, and unlikely that one would want to change this field after setup, so keeping this field read-only.
Reimplemented from HHChannelBase.
Definition at line 150 of file ZombieHHChannel.cpp.
{
    cerr << "Error: HSolve::setUseConcentration(): Cannot change "
         "'useConcentration' once HSolve has been setup.\n";
}
vSetX()
void ZombieHHChannel::vSetX (const Eref & e, double X) override virtual
Reimplemented from HHChannelBase.
Definition at line 120 of file ZombieHHChannel.cpp.
{
    hsolve_->setX( e.id(), X );
}
References hsolve_, Eref::id(), and HSolve::setX().
vSetXpower()
void ZombieHHChannel::vSetXpower (const Eref & e, double power) override virtual
Assigns the Xpower for this gate. If the gate exists and has only this element for input, then change the gate value. If the gate exists and has multiple parents, then make a new gate. If the gate does not exist, make a new gate
Reimplemented from HHChannelBase.
Definition at line 51 of file ZombieHHChannel.cpp.
{
    Xpower_ = Xpower;
    hsolve_->setPowers( e.id(), Xpower_, Ypower_, Zpower_ );
}
References hsolve_, Eref::id(), HSolve::setPowers(), HHChannelBase::Xpower_, HHChannelBase::Ypower_, and HHChannelBase::Zpower_.
vSetY()
void ZombieHHChannel::vSetY (const Eref & e, double Y) override virtual
Reimplemented from HHChannelBase.
Definition at line 130 of file ZombieHHChannel.cpp.
{
    hsolve_->setY( e.id(), Y );
}
References hsolve_, Eref::id(), and HSolve::setY().
vSetYpower()
void ZombieHHChannel::vSetYpower (const Eref & e, double Ypower) override virtual
Reimplemented from HHChannelBase.
Definition at line 57 of file ZombieHHChannel.cpp.
{
    Ypower_ = Ypower;
    hsolve_->setPowers( e.id(), Xpower_, Ypower_, Zpower_ );
}
References hsolve_, Eref::id(), HSolve::setPowers(), HHChannelBase::Xpower_, HHChannelBase::Ypower_, and HHChannelBase::Zpower_.
vSetZ()
void ZombieHHChannel::vSetZ (const Eref & e, double Z) override virtual
Reimplemented from HHChannelBase.
Definition at line 140 of file ZombieHHChannel.cpp.
{
    hsolve_->setZ( e.id(), Z );
}
References hsolve_, Eref::id(), and HSolve::setZ().
vSetZpower()
void ZombieHHChannel::vSetZpower (const Eref & e, double Zpower) override virtual
Reimplemented from HHChannelBase.
Definition at line 63 of file ZombieHHChannel.cpp.
{
    Zpower_ = Zpower;
    hsolve_->setPowers( e.id(), Xpower_, Ypower_, Zpower_ );
}
References hsolve_, Eref::id(), HSolve::setPowers(), HHChannelBase::Xpower_, HHChannelBase::Ypower_, and HHChannelBase::Zpower_.
Member Data Documentation
hsolve_
HSolve* ZombieHHChannel::hsolve_ private
Definition at line 122 of file ZombieHHChannel.h.
Referenced by vGetEk(), vGetGbar(), vGetGk(), vGetIk(), vGetInstant(), vGetX(), vGetY(), vGetZ(), vHandleConc(), vSetEk(), vSetGbar(), vSetGk(), vSetInstant(), vSetModulation(), vSetSolver(), vSetX(), vSetXpower(), vSetY(), vSetYpower(), vSetZ(), and vSetZpower().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/hsolve/ZombieHHChannel.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/hsolve/ZombieHHChannel.cpp