MOOSE - Multiscale Object Oriented Simulation Environment: DiagonalMsg Class Reference
DiagonalMsg Class Reference
#include <DiagonalMsg.h>
Public Member Functions
Msg * copy (Id origSrc, Id newSrc, Id newTgt, FuncId fid, unsigned int b, unsigned int n) const
DiagonalMsg (Element *e1, Element *e2, unsigned int msgIndex)
ObjId findOtherEnd (ObjId end) const
Eref firstTgt (const Eref &src) const
int getStride () const
Id managerId () const
void setStride (int stride)
void sources (vector< vector< Eref > > &v) const
void targets (vector< vector< Eref > > &v) const
~DiagonalMsg ()
Public Member Functions inherited from Msg
Element * e1 () const
Element * e2 () const
ObjId getAdjacent (ObjId) const
vector< string > getDestFieldsOnE1 () const
vector< string > getDestFieldsOnE2 () const
Id getE1 () const
Id getE2 () const
vector< string > getSrcFieldsOnE1 () const
vector< string > getSrcFieldsOnE2 () const
bool isForward (const Element *src) const
ObjId mid () const
Msg (ObjId mid, Element *e1, Element *e2)
Constructor.
virtual ~Msg ()
Destructor.
Static Public Member Functions
static const Cinfo * initCinfo ()
Setup function for Element-style access to Msg fields.
static char * lookupMsg (unsigned int index)
Static function for Msg access.
static unsigned int numMsg ()
Msg lookup functions.
Static Public Member Functions inherited from Msg
static void clearAllMsgs ()
static void deleteMsg (ObjId mid)
static const Msg * getMsg (ObjId m)
static const Cinfo * initCinfo ()
static unsigned int initMsgManagers ()
static bool isLastTrump ()
True when MOOSE has been terminated and is being cleaned up.
static const Msg * lastMsg ()
Private Attributes
int stride_
Static Private Attributes
static Id managerId_
static vector< DiagonalMsg * > msg_
Friends
unsigned int Msg::initMsgManagers ()
Additional Inherited Members
Protected Attributes inherited from Msg
Element * e1_
Index of this Msg on the msg_ vector.
Element * e2_
Element 1 attached to Msg.
ObjId mid_
Static Protected Attributes inherited from Msg
static bool lastTrump_ = false
Flag to indicate termination of program.
static Id msgManagerId_
Element 2 attached to Msg.
Detailed Description
Connects up a series of data entries onto a matching series in a target Element. Inspects each entry, and uses the 'stride_' field to determine which should be its target.
* Suppose we have a stride of +1. Then
* Src:      1   2   3   4   n
* Dest: 2   3   4   5   n+1
*
* Suppose we have a stride of -2. Then
* Src:      1   2   3   4   n
* Dest: -   -   1   2   n-2
*
Definition at line 28 of file DiagonalMsg.h.
Constructor & Destructor Documentation
DiagonalMsg()
DiagonalMsg::DiagonalMsg (Element * e1, Element * e2, unsigned int msgIndex)
Definition at line 17 of file DiagonalMsg.cpp.
    : Msg( ObjId( managerId_, (msgIndex != 0) ? msgIndex: msg_.size() ),
                    e1, e2 ),
    stride_( 1 )
{
    if ( msgIndex == 0 ) {
        msg_.push_back( this );
    } else {
        if ( msg_.size() <= msgIndex )
            msg_.resize( msgIndex + 1 );
        msg_[ msgIndex ] = this;
    }
}
References managerId_, Msg::Msg(), msg_, ObjId::ObjId(), and stride_.
Referenced by copy(), Shell::innerAddMsg(), and testFibonacci().
~DiagonalMsg()
DiagonalMsg::~DiagonalMsg ()
Definition at line 31 of file DiagonalMsg.cpp.
{
    assert( mid_.dataIndex < msg_.size() );
    msg_[ mid_.dataIndex ] = 0; // ensure deleted ptr isn't reused.
}
References ObjId::dataIndex, Msg::mid_, and msg_.
Member Function Documentation
copy()
Msg * DiagonalMsg::copy (Id origSrc, Id newSrc, Id newTgt, FuncId fid, unsigned int b, unsigned int n) const virtual
Make a copy of this Msg. The original msg was on origSrc. The new Msg should go from newSrc to newTgt, and have the function fid, on bindIndex b. The copy may have to be a higher-order Msg type to handle arrays if n > 1. Note that n is not the number of msgs, but the multiplier by which numData will be scaled.
Implements Msg.
Definition at line 113 of file DiagonalMsg.cpp.
{
    const Element* orig = origSrc.element();
    if ( n <= 1 ) {
        DiagonalMsg* ret = 0;
        if ( orig == e1() ) {
            ret = new DiagonalMsg( newSrc.element(), newTgt.element(), 0 );
            ret->e1()->addMsgAndFunc( ret->mid(), fid, b );
        } else if ( orig == e2() ) {
            ret = new DiagonalMsg( newTgt.element(), newSrc.element(), 0 );
            ret->e2()->addMsgAndFunc( ret->mid(), fid, b );
        } else {
            assert( 0 );
        }
        ret->setStride( stride_ );
        return ret;
    } else {
        // Here we need a SliceMsg which goes from one 2-d array to another.
        cout << "Error: DiagonalMsg::copy: DiagonalSliceMsg not yet implemented\n";
        return 0;
    }
}
References Element::addMsgAndFunc(), DiagonalMsg(), Msg::e1(), Msg::e2(), Id::element(), Msg::mid(), setStride(), and stride_.
findOtherEnd()
ObjId DiagonalMsg::findOtherEnd (ObjId) const virtual
Find the other end of this Msg. In most cases this is a straightforward return of e1 or e2, plus perhaps a DataId. But in some complex msgs we need to figure out DataIds that match with the target. In many-to-one cases we just return the first entry. If no Element match, return ObjId(Id(), DataId::bad()) If Element e matches but not DataId, return ObjId(e.id(), DataId::bad())
Implements Msg.
Definition at line 93 of file DiagonalMsg.cpp.
{
    if ( f.id.element() == e1() ) {
        int i2 = f.dataIndex + stride_;
        if ( i2 >= 0 ) {
            unsigned int ui2 = i2;
            if ( ui2 < e2()->numData() )
                return ObjId( e2()->id(), DataId( ui2 ) );
        }
    } else if ( f.id.element() == e2() ) {
        int i1 = f.dataIndex - stride_;
        if ( i1 >= 0 ) {
            unsigned int ui1 = i1;
            if ( ui1 < e1()->numData() )
                return ObjId( e1()->id(), DataId( ui1 ));
        }
    }
    return ObjId( 0, BADINDEX );
}
References BADINDEX, ObjId::dataIndex, Msg::e1(), Msg::e2(), Id::element(), Element::id(), ObjId::id, Element::numData(), ObjId::ObjId(), and stride_.
firstTgt()
Eref DiagonalMsg::firstTgt (const Eref & src) const virtual
Obtain the first target Eref for the specified Src Eref It is really meant only to work with messages with a single target ObjId for each given src, typically OneToOne.
Implements Msg.
Definition at line 37 of file DiagonalMsg.cpp.
{
    if ( src.element() == e1_ ) {
        unsigned int nextData = src.dataIndex() + stride_;
        return Eref( e2_, nextData );
    }
    else if ( src.element() == e2_ ) {
        unsigned int nextData = src.dataIndex() - stride_;
        return Eref( e1_, nextData );
    }
    return Eref( 0, 0 );
}
References Eref::dataIndex(), Msg::e1_, Msg::e2_, Eref::element(), Eref::Eref(), and stride_.
getStride()
int DiagonalMsg::getStride () const
The stride is the increment to the src DataId that gives the dest DataId. It can be positive or negative, but bounds checking takes place and it does not wrap around. This function reads the stride.
Definition at line 88 of file DiagonalMsg.cpp.
{
    return stride_;
}
References stride_.
Referenced by initCinfo().
initCinfo()
const Cinfo * DiagonalMsg::initCinfo () static
Setup function for Element-style access to Msg fields.
Definition at line 154 of file DiagonalMsg.cpp.
{
    // Field definitions.
    static ValueFinfo< DiagonalMsg, int > stride(
        "stride",
        "The stride is the increment to the src DataId that gives the"
        "dest DataId. "
        "It can be positive or negative, but bounds checking"
        "takes place and it does not wrap around.",
        &DiagonalMsg::setStride,
        &DiagonalMsg::getStride
    );
    static Finfo* msgFinfos[] = {
        &stride,        // value
    };
    static Dinfo< short > dinfo;
    static Cinfo msgCinfo (
        "DiagonalMsg",  // name
        Msg::initCinfo(),               // base class
        msgFinfos,
        sizeof( msgFinfos ) / sizeof( Finfo* ), // num Fields
        &dinfo
    );
    return &msgCinfo;
}
References Cinfo::Cinfo(), getStride(), Msg::initCinfo(), setStride(), and ValueFinfo< T, F >::ValueFinfo().
Referenced by Msg::initMsgManagers().
lookupMsg()
char * DiagonalMsg::lookupMsg (unsigned int index) static
Static function for Msg access.
Definition at line 144 of file DiagonalMsg.cpp.
{
    assert( index < msg_.size() );
    return reinterpret_cast< char* >( msg_[index] );
}
References msg_.
Referenced by Msg::clearAllMsgs(), and Msg::initMsgManagers().
managerId()
Id DiagonalMsg::managerId () const
Definition at line 76 of file DiagonalMsg.cpp.
{
    return DiagonalMsg::managerId_;
}
References managerId_.
numMsg()
unsigned int DiagonalMsg::numMsg () static
Msg lookup functions.
Static function for Msg access.
Definition at line 138 of file DiagonalMsg.cpp.
{
    return msg_.size();
}
References msg_.
Referenced by Msg::clearAllMsgs(), and Msg::initMsgManagers().
setStride()
void DiagonalMsg::setStride (int stride)
The stride is the increment to the src DataId that gives the dest DataId. It can be positive or negative, but bounds checking takes place and it does not wrap around. This function assigns the stride.
Definition at line 81 of file DiagonalMsg.cpp.
{
    stride_ = stride;
    e1()->markRewired();
    e2()->markRewired();
}
References Msg::e1(), Msg::e2(), Element::markRewired(), and stride_.
Referenced by copy(), initCinfo(), and testFibonacci().
sources()
void DiagonalMsg::sources (vector< vector< Eref > > & v) const virtual
Return all the sources of e2 from e1, that is, all the msgs coming into specified entries on e2 from e1.
ALLDATA used when the sources include all data entries on a source. Indexing is v[dataId in range e2.numData][src list]
Implements Msg.
Definition at line 50 of file DiagonalMsg.cpp.
{
    v.clear();
    v.resize( e2_->numData() );
    int j = -stride_;
    int numData1 = e1_->numData();
    for ( unsigned int i = 0; i < e2_->numData(); ++i ) {
        if ( j >= 0 && j < numData1 )
            v[i].resize( 1, Eref( e1_, j ) );
        j++;
    }
}
References Msg::e1_, Msg::e2_, Eref::Eref(), Element::numData(), and stride_.
targets()
void DiagonalMsg::targets (vector< vector< Eref > > & v) const virtual
Return all the targets of e1 on e2, that is, all the msgs going from specified entries on e1 to e2. ALLDATA used when the targets include all data entries on a target. Indexing is v[dataId in range e1.numData][tgt list]
Implements Msg.
Definition at line 63 of file DiagonalMsg.cpp.
{
    v.clear();
    v.resize( e1_->numData() );
    int j = stride_;
    int numData2 = e2_->numData();
    for ( unsigned int i = 0; i < e1_->numData(); ++i ) {
        if ( j >= 0 && j < numData2 )
            v[i].resize( 1, Eref( e2_, j ) );
        j++;
    }
}
References Msg::e1_, Msg::e2_, Eref::Eref(), Element::numData(), and stride_.
Friends And Related Symbol Documentation
Msg::initMsgManagers
unsigned int Msg::initMsgManagers () friend
Member Data Documentation
managerId_
Id DiagonalMsg::managerId_ static private
Definition at line 71 of file DiagonalMsg.h.
Referenced by DiagonalMsg(), Msg::initMsgManagers(), and managerId().
msg_
vector< DiagonalMsg * > DiagonalMsg::msg_ static private
Definition at line 72 of file DiagonalMsg.h.
Referenced by DiagonalMsg(), lookupMsg(), numMsg(), and ~DiagonalMsg().
stride_
int DiagonalMsg::stride_ private
Definition at line 70 of file DiagonalMsg.h.
Referenced by copy(), DiagonalMsg(), findOtherEnd(), firstTgt(), getStride(), setStride(), sources(), and targets().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/msg/DiagonalMsg.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/msg/DiagonalMsg.cpp