MOOSE - Multiscale Object Oriented Simulation Environment: TableBase Class Reference
TableBase Class Reference
#include <TableBase.h>
Public Member Functions
void clearVec ()
void compareVec (vector< double > other, string op)
void compareXplot (string fname, string plotname, string op)
const vector< double > & data ()
double getOutputValue () const
string getPlotDump () const
unsigned int getVecSize () const
vector< double > getVector () const
double getY (unsigned int index) const
double interpolate (double x, double xmin, double xmax) const
void linearTransform (double scale, double offset)
void loadCSV (string fname, int startLine, int colNum, char separator)
void loadXplot (string fname, string plotname)
void loadXplotRange (string fname, string plotname, unsigned int start, unsigned int end)
double * lookupVec (unsigned int index)
void plainPlot (string file)
void setOutputValue (double val)
void setPlotDump (string v)
void setVecSize (unsigned int num)
void setVector (vector< double > val)
TableBase ()
void xplot (string file, string plotname)
Static Public Member Functions
static const Cinfo * initCinfo ()
Protected Member Functions
vector< double > & vec ()
Private Attributes
double output_
vector< double > vec_
Detailed Description
Base class for table operations. Provides basics for looking up table and interpolation, but no process or messaging. Derived classes deal with these.
Definition at line 19 of file TableBase.h.
Constructor & Destructor Documentation
TableBase()
TableBase::TableBase ()
Definition at line 164 of file TableBase.cpp.
                     : output_( 0 )
{
}
References output_.
Member Function Documentation
clearVec()
void TableBase::clearVec ()
Definition at line 444 of file TableBase.cpp.
{
    vec_.resize(0);
}
References vec_.
Referenced by Table::clearAllVecs(), initCinfo(), and Streamer::zipWithTime().
compareVec()
void TableBase::compareVec (vector< double > other, string op)
Definition at line 423 of file TableBase.cpp.
{
    // Note that this line below is illegal: it causes a race condition
    // vector< double > temp = Field< vector< double > >::get( other, "vec" );
    string hop = headop( op );
    if ( hop == "rmsd" )   // RMSDifference
    {
        output_ = getRMSDiff( vec_, temp );
    }
    if ( hop == "rmsr" )   // RMS ratio
    {
        output_ = getRMSRatio( vec_, temp );
    }
    if ( hop == "dotp" )
        cout << "TableBase::compareVec: DotProduct not yet done\n";
}
References getRMSDiff(), getRMSRatio(), headop(), output_, and vec_.
Referenced by initCinfo().
compareXplot()
void TableBase::compareXplot (string fname, string plotname, string op)
Definition at line 399 of file TableBase.cpp.
{
    vector< double > temp;
    if ( !innerLoadXplot( fname, plotname, temp ) )
    {
        cout << "TableBase::compareXplot: unable to load data from file " << fname <<endl;
    }
    string hop = headop( op );
    if ( hop == "rmsd" )   // RMSDifference
    {
        output_ = getRMSDiff( vec_, temp );
    }
    if ( hop == "rmsr" )   // RMS ratio
    {
        output_ = getRMSRatio( vec_, temp );
    }
    if ( hop == "dotp" )
        cout << "TableBase::compareXplot: DotProduct not yet done\n";
}
References getRMSDiff(), getRMSRatio(), headop(), innerLoadXplot(), output_, and vec_.
Referenced by initCinfo().
data()
const vector< double > & TableBase::data ()
Definition at line 528 of file TableBase.cpp.
{
    return vec_;
}
References vec_.
getOutputValue()
double TableBase::getOutputValue () const
Definition at line 453 of file TableBase.cpp.
{
    return output_;
}
References output_.
Referenced by initCinfo().
getPlotDump()
string TableBase::getPlotDump () const
Definition at line 533 of file TableBase.cpp.
{
    static string ret = "plot.Dump";
    return ret;
}
Referenced by initCinfo().
getVecSize()
unsigned int TableBase::getVecSize () const
Definition at line 507 of file TableBase.cpp.
{
    return vec_.size();
}
References vec_.
Referenced by initCinfo(), Table::process(), and Streamer::zipWithTime().
getVector()
vector< double > TableBase::getVector () const
Definition at line 512 of file TableBase.cpp.
{
    return vec_;
}
References vec_.
Referenced by SocketStreamer::enoughDataToStream(), initCinfo(), and Streamer::zipWithTime().
getY()
double TableBase::getY (unsigned int index) const
Definition at line 463 of file TableBase.cpp.
{
    if ( index < vec_.size() )
        return ( vec_[index] );
    return 0;
}
References vec_.
Referenced by initCinfo().
initCinfo()
const Cinfo * TableBase::initCinfo () static
Definition at line 17 of file TableBase.cpp.
{
    // Field Definitions
    static ValueFinfo< TableBase, vector< double > > vec(
        "vector",
        "vector with all table entries",
        &TableBase::setVector,
        &TableBase::getVector
    );
    static ValueFinfo< TableBase, string > plotDump(
        "plotDump",
        "'File plotname' for dumpling an xplot, as a workaround for an error "
        " in the xplot python interface. Note separator is a space. The return "
        "value is a dummy.",
        &TableBase::setPlotDump,
        &TableBase::getPlotDump
    );
    static ReadOnlyValueFinfo< TableBase, double > outputValue(
        "outputValue",
        "Output value holding current table entry or output of a calculation",
        &TableBase::getOutputValue
    );
    static ReadOnlyValueFinfo< TableBase, unsigned int > size(
        "size",
        "size of table. Note that this is the number of x divisions +1"
        "since it must represent the largest value as well as the"
        "smallest",
        &TableBase::getVecSize
    );
    static ReadOnlyLookupValueFinfo< TableBase, unsigned int, double > y(
        "y",
        "Value of table at specified index",
        &TableBase::getY
    );
    // MsgDest Definitions
    static DestFinfo linearTransform( "linearTransform",
            "Linearly scales and offsets data. Scale first, then offset.",
            new OpFunc2< TableBase
            , double
            , double >(&TableBase::linearTransform ) );
    static DestFinfo xplot( "xplot",
            "Dumps table contents to xplot-format file. "
            "Argument 1 is filename, argument 2 is plotname",
            new OpFunc2< TableBase, string, string >( &TableBase::xplot ) );
    static DestFinfo plainPlot( "plainPlot",
            "Dumps table contents to single-column ascii file. "
            "Uses scientific notation. "
            "Argument 1 is filename",
            new OpFunc1< TableBase, string >( &TableBase::plainPlot ) );
    static DestFinfo loadCSV( "loadCSV",
            "Reads a single column from a CSV file. "
            "Arguments: filename, column#, starting row#, separator",
            new OpFunc4< TableBase, string, int, int, char >(&TableBase::loadCSV ) );
    static DestFinfo loadXplot( "loadXplot",
                                "Reads a single plot from an xplot file. "
                                "Arguments: filename, plotname"
                                "When the file has 2 columns, the 2nd column is loaded.",
                                new OpFunc2< TableBase, string, string >(
                                    &TableBase::loadXplot ) );
    static DestFinfo loadXplotRange( "loadXplotRange",
                                     "Reads a single plot from an xplot file, and selects a "
                                     "subset of points from it. "
                                     "Arguments: filename, plotname, startindex, endindex"
                                     "Uses C convention: startindex included, endindex not included."
                                     "When the file has 2 columns, the 2nd column is loaded.",
                                     new OpFunc4< TableBase, string, string, unsigned int, unsigned int >(
                                         &TableBase::loadXplotRange ) );
    static DestFinfo compareXplot( "compareXplot",
                                   "Reads a plot from an xplot file and compares with contents of TableBase."
                                   "Result is put in 'output' field of table."
                                   "If the comparison fails (e.g., due to zero entries), the "
                                   "return value is -1."
                                   "Arguments: filename, plotname, comparison_operation"
                                   "Operations: rmsd (for RMSDifference), rmsr (RMSratio ), "
                                   "dotp (Dot product, not yet implemented).",
                                   new OpFunc3< TableBase, string, string, string >(
                                       &TableBase::compareXplot ) );
    static DestFinfo compareVec( "compareVec",
                                 "Compares contents of TableBase with a vector of doubles."
                                 "Result is put in 'output' field of table."
                                 "If the comparison fails (e.g., due to zero entries), the "
                                 "return value is -1."
                                 "Arguments: Other vector, comparison_operation"
                                 "Operations: rmsd (for RMSDifference), rmsr (RMSratio ), "
                                 "dotp (Dot product, not yet implemented).",
                                 new OpFunc2< TableBase, vector< double >, string >(
                                     &TableBase::compareVec ) );
    static DestFinfo clearVec(
        "clearVec",
        "Handles request to clear the data vector",
        new OpFunc0< TableBase > (&TableBase::clearVec));
    static Finfo* tableBaseFinfos[] =
    {
        &vec,           // Value
        &plotDump,      // Value, used for debugging xplot function.
        &outputValue,   // ReadOnlyValue
        &size,          // ReadOnlyValue
        &y,             // ReadOnlyLookupValue
        &linearTransform,   // DestFinfo
        &xplot,         // DestFinfo
        &plainPlot,         // DestFinfo
        &loadCSV,           // DestFinfo
        &loadXplot,         // DestFinfo
        &loadXplotRange,    // DestFinfo
        &compareXplot,      // DestFinfo
        &compareVec,        // DestFinfo
        &clearVec,
    };
    static Dinfo< TableBase > dinfo;
    static Cinfo tableCinfo (
        "TableBase",
        Neutral::initCinfo(),
        tableBaseFinfos,
        sizeof( tableBaseFinfos ) / sizeof ( Finfo* ),
        &dinfo
    );
    return &tableCinfo;
}
References Cinfo::Cinfo(), clearVec(), compareVec(), compareXplot(), DestFinfo::DestFinfo(), getOutputValue(), getPlotDump(), getVecSize(), getVector(), getY(), Neutral::initCinfo(), linearTransform(), loadCSV(), loadXplot(), loadXplotRange(), OpFunc0< T >::OpFunc0(), OpFunc1< T, A >::OpFunc1(), OpFunc2< T, A1, A2 >::OpFunc2(), OpFunc3< T, A1, A2, A3 >::OpFunc3(), OpFunc4< T, A1, A2, A3, A4 >::OpFunc4(), plainPlot(), ReadOnlyLookupValueFinfo< T, L, F >::ReadOnlyLookupValueFinfo(), ReadOnlyValueFinfo< T, F >::ReadOnlyValueFinfo(), setPlotDump(), setVector(), ValueFinfo< T, F >::ValueFinfo(), and xplot().
Referenced by Interpol::initCinfo(), SocketStreamer::initCinfo(), StimulusTable::initCinfo(), Streamer::initCinfo(), Table::initCinfo(), and TimeTable::initCinfo().
interpolate()
double TableBase::interpolate (double x, double xmin, double xmax) const
Definition at line 470 of file TableBase.cpp.
{
    if ( vec_.size() == 0 )
        return 0;
    if ( vec_.size() == 1 || input < xmin || xmin >= xmax )
        return vec_[0];
    if ( input > xmax )
        return ( vec_.back() );
    unsigned int xdivs = vec_.size() - 1;
    double fraction = ( input - xmin ) / ( xmax - xmin );
    if ( fraction < 0 )
        return vec_[0];
    unsigned int j = static_cast<unsigned int>(xdivs * fraction);
    if ( j >= ( vec_.size() - 1 ) )
        return vec_.back();
    double dx = (xmax - xmin ) / xdivs;
    double lowerBound = xmin + j * dx;
    double subFraction = ( input - lowerBound ) / dx;
    double y = vec_[j] + ( vec_[j + 1] - vec_[j] ) * subFraction;
    return y;
}
References vec_.
Referenced by Interpol::process(), StimulusTable::process(), and StimulusTable::reinit().
linearTransform()
void TableBase::linearTransform (double scale, double offset)
Definition at line 172 of file TableBase.cpp.
{
    for ( vector< double >::iterator i = vec_.begin(); i != vec_.end(); ++i)
        *i = *i * scale + offset;
}
References vec_.
Referenced by initCinfo().
loadCSV()
void TableBase::loadCSV (string fname, int startLine, int colNum, char separator)
Definition at line 344 of file TableBase.cpp.
{
    cout << "TODO: Not implemented yet" << endl;
}
Referenced by initCinfo().
loadXplot()
void TableBase::loadXplot (string fname, string plotname)
Definition at line 315 of file TableBase.cpp.
{
    if ( !innerLoadXplot( fname, plotname, vec_ ) )
    {
        cout << "TableBase::loadXplot: unable to load data from file " << fname <<endl;
        return;
    }
}
References innerLoadXplot(), and vec_.
Referenced by initCinfo().
loadXplotRange()
void TableBase::loadXplotRange (string fname, string plotname, unsigned int start, unsigned int end)
Definition at line 324 of file TableBase.cpp.
{
    vector< double > temp;
    if ( !innerLoadXplot( fname, plotname, temp ) )
    {
        cout << "TableBase::loadXplot: unable to load data from file " << fname <<endl;
        return;
    }
    if ( start > end || end > temp.size() )
    {
        cout << "TableBase::loadXplotRange: Bad range (" << start <<
             ", " << end << "] for table of size " << temp.size() <<
             " from file " << fname << endl;
        return;
    }
    vec_.clear();
    vec_.insert( vec_.end(), temp.begin() + start, temp.begin() + end );
}
References innerLoadXplot(), and vec_.
Referenced by initCinfo().
lookupVec()
double * TableBase::lookupVec (unsigned int index)
plainPlot()
void TableBase::plainPlot (string file)
Definition at line 178 of file TableBase.cpp.
{
    ofstream fout( fname.c_str(), ios_base::out );
    fout.precision( 18 );
    fout.setf( ios::scientific, ios::floatfield );
    for ( vector< double >::iterator i = vec_.begin(); i != vec_.end(); ++i)
        fout << *i << endl;
    fout << "\n";
}
References vec_.
Referenced by initCinfo().
setOutputValue()
void TableBase::setOutputValue (double val)
Definition at line 458 of file TableBase.cpp.
{
    output_ = v;
}
References output_.
Referenced by StimulusTable::process(), and StimulusTable::reinit().
setPlotDump()
void TableBase::setPlotDump (string v)
Definition at line 539 of file TableBase.cpp.
{
    auto pos = v.rfind(" ");
    string fname = v.substr( 0, pos );
    string plotname = "plot";
    if ( pos != string::npos )
        plotname = v.substr( pos );
    // cout << "setPlotDump( " << fname << ", " << plotname << " ),  " << v << "\n";
    xplot( fname, plotname );
}
References xplot().
Referenced by initCinfo().
setVecSize()
void TableBase::setVecSize (unsigned int num)
Definition at line 502 of file TableBase.cpp.
{
    vec_.resize( num );
}
References vec_.
setVector()
void TableBase::setVector (vector< double > val)
Definition at line 517 of file TableBase.cpp.
{
    vec_ = val;
}
References vec_.
Referenced by initCinfo().
vec()
vector< double > & TableBase::vec () protected
Definition at line 522 of file TableBase.cpp.
{
    return vec_;
}
References vec_.
Referenced by Table::collectData(), Table::input(), Table::mergeWithTime(), Table::process(), TimeTable::process(), Table::reinit(), TimeTable::setFilename(), Table::spike(), and Table::toJSON().
xplot()
void TableBase::xplot (string file, string plotname)
Definition at line 188 of file TableBase.cpp.
{
    ofstream fout( fname.c_str(), ios_base::app );
    fout << "/newplot\n";
    fout << "/plotname " << plotname << "\n";
    for ( vector< double >::iterator i = vec_.begin(); i != vec_.end(); ++i)
        fout << *i << endl;
    fout << "\n";
}
References vec_.
Referenced by initCinfo(), and setPlotDump().
Member Data Documentation
output_
double TableBase::output_ private
Definition at line 73 of file TableBase.h.
Referenced by compareVec(), compareXplot(), getOutputValue(), setOutputValue(), and TableBase().
vec_
vector< double > TableBase::vec_ private
Definition at line 74 of file TableBase.h.
Referenced by clearVec(), compareVec(), compareXplot(), data(), getVecSize(), getVector(), getY(), interpolate(), linearTransform(), loadXplot(), loadXplotRange(), plainPlot(), setVecSize(), setVector(), vec(), and xplot().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/builtins/TableBase.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/builtins/TableBase.cpp