MOOSE - Multiscale Object Oriented Simulation Environment: SingleMsg Class Reference
SingleMsg Class Reference
#include <SingleMsg.h>
Public Member Functions
Msg * copy (Id origSrc, Id newSrc, Id newTgt, FuncId fid, unsigned int b, unsigned int n) const
ObjId findOtherEnd (ObjId end) const
Eref firstTgt (const Eref &src) const
DataId getI1 () const
DataId getI2 () const
unsigned int getTargetField () const
DataId i1 () const
DataId i2 () const
Id managerId () const
void setI1 (DataId di)
void setI2 (DataId di)
void setTargetField (unsigned int f)
SingleMsg (const Eref &e1, const Eref &e2, unsigned int msgIndex)
void sources (vector< vector< Eref > > &v) const
void targets (vector< vector< Eref > > &v) const
~SingleMsg ()
Public Member Functions inherited from Msg
Element * e1 () const
Element * e2 () const
ObjId getAdjacent (ObjId) const
vector< string > getDestFieldsOnE1 () const
vector< string > getDestFieldsOnE2 () const
Id getE1 () const
Id getE2 () const
vector< string > getSrcFieldsOnE1 () const
vector< string > getSrcFieldsOnE2 () const
bool isForward (const Element *src) const
ObjId mid () const
Msg (ObjId mid, Element *e1, Element *e2)
Constructor.
virtual ~Msg ()
Destructor.
Static Public Member Functions
static const Cinfo * initCinfo ()
static char * lookupMsg (unsigned int index)
Static function for Msg access.
static unsigned int numMsg ()
Msg lookup functions.
Static Public Member Functions inherited from Msg
static void clearAllMsgs ()
static void deleteMsg (ObjId mid)
static const Msg * getMsg (ObjId m)
static const Cinfo * initCinfo ()
static unsigned int initMsgManagers ()
static bool isLastTrump ()
True when MOOSE has been terminated and is being cleaned up.
static const Msg * lastMsg ()
Private Attributes
unsigned int f2_
DataId i1_
DataId i2_
Static Private Attributes
static Id managerId_
static vector< SingleMsg * > msg_
Friends
unsigned int Msg::initMsgManagers ()
Additional Inherited Members
Protected Attributes inherited from Msg
Element * e1_
Index of this Msg on the msg_ vector.
Element * e2_
Element 1 attached to Msg.
ObjId mid_
Static Protected Attributes inherited from Msg
static bool lastTrump_ = false
Flag to indicate termination of program.
static Id msgManagerId_
Element 2 attached to Msg.
Detailed Description
This is a message from a single source object to a single target object. The source object must be a DataEntry. The target object may be on a FieldElement, and the target specification includes the index of the field object.
Definition at line 20 of file SingleMsg.h.
Constructor & Destructor Documentation
SingleMsg()
SingleMsg::SingleMsg (const Eref & e1, const Eref & e2, unsigned int msgIndex)
Definition at line 21 of file SingleMsg.cpp.
    : Msg( ObjId( managerId_, (msgIndex != 0 ) ? msgIndex: msg_.size() ),
           e1.element(), e2.element() ),
      i1_( e1.dataIndex() ),
      i2_( e2.dataIndex() ),
      f2_( e2.fieldIndex() )
{
    if ( msgIndex == 0 )
    {
        msg_.push_back( this );
        return;
    }
    else if ( msg_.size() <= msgIndex )
    {
        msg_.resize( msgIndex + 1 );
    }
    msg_[ msgIndex ] = this;
}
References Eref::dataIndex(), Eref::element(), f2_, Eref::fieldIndex(), i1_, i2_, managerId_, Msg::Msg(), msg_, and ObjId::ObjId().
Referenced by copy(), Shell::innerAddMsg(), testMsgField(), and testSendSpike().
~SingleMsg()
SingleMsg::~SingleMsg ()
Definition at line 40 of file SingleMsg.cpp.
{
    assert( mid_.dataIndex < msg_.size() );
    msg_[ mid_.dataIndex ] = 0; // ensure deleted ptr isn't reused.
}
References ObjId::dataIndex, Msg::mid_, and msg_.
Member Function Documentation
copy()
Msg * SingleMsg::copy (Id origSrc, Id newSrc, Id newTgt, FuncId fid, unsigned int b, unsigned int n) const virtual
Make a copy of this Msg. The original msg was on origSrc. The new Msg should go from newSrc to newTgt, and have the function fid, on bindIndex b. The copy may have to be a higher-order Msg type to handle arrays if n > 1. Note that n is not the number of msgs, but the multiplier by which numData will be scaled.
Implements Msg.
Definition at line 111 of file SingleMsg.cpp.
{
    const Element* orig = origSrc.element();
    if ( n <= 1 )
    {
        SingleMsg* ret = 0;
        if ( orig == e1() )
        {
            ret = new SingleMsg( Eref( newSrc.element(), i1_ ),
                                 Eref( newTgt.element(), i2_, f2_ ), 0 );
            ret->e1()->addMsgAndFunc( ret->mid(), fid, b );
        }
        else if ( orig == e2() )
        {
            ret = new SingleMsg( Eref( newTgt.element(), i1_ ),
                                 Eref( newSrc.element(), i2_, f2_ ), 0 );
            ret->e2()->addMsgAndFunc( ret->mid(), fid, b );
        }
        else
        {
            assert( 0 );
        }
        return ret;
    }
    else
    {
        // Here we need a SliceMsg which goes from one 2-d array to another.
        cout << "Error: SingleMsg::copy: SliceMsg not yet implemented\n";
        return 0;
    }
}
References Element::addMsgAndFunc(), Msg::e1(), Msg::e2(), Id::element(), Eref::Eref(), f2_, i1_, i2_, Msg::mid(), and SingleMsg().
findOtherEnd()
ObjId SingleMsg::findOtherEnd (ObjId) const virtual
Find the other end of this Msg. In most cases this is a straightforward return of e1 or e2, plus perhaps a DataId. But in some complex msgs we need to figure out DataIds that match with the target. In many-to-one cases we just return the first entry. If no Element match, return ObjId(Id(), DataId::bad()) If Element e matches but not DataId, return ObjId(e.id(), DataId::bad())
Implements Msg.
Definition at line 96 of file SingleMsg.cpp.
{
    if ( f.element() == e1() )
    {
        if ( f.dataIndex == i1_ )
            return ObjId( e2()->id(), i2_ );
    }
    else if ( f.element() == e2() )
    {
        if ( f.dataIndex == i2_ )
            return ObjId( e1()->id(), i1_ );
    }
    return ObjId( 0, BADINDEX );
}
References BADINDEX, ObjId::dataIndex, Msg::e1(), Msg::e2(), ObjId::element(), i1_, i2_, Element::id(), and ObjId::ObjId().
firstTgt()
Eref SingleMsg::firstTgt (const Eref & src) const virtual
Obtain the first target Eref for the specified Src Eref It is really meant only to work with messages with a single target ObjId for each given src, typically OneToOne.
Implements Msg.
Definition at line 46 of file SingleMsg.cpp.
{
    if ( src.element() == e1_ )
        return Eref( e2_, i2_, f2_ );
    else if ( src.element() == e2_ )
        return Eref( e1_, i1_ );
    return Eref( 0, 0 );
}
References Msg::e1_, Msg::e2_, Eref::element(), Eref::Eref(), f2_, i1_, and i2_.
getI1()
DataId SingleMsg::getI1 () const
Definition at line 187 of file SingleMsg.cpp.
{
    return i1_;
}
References i1_.
Referenced by initCinfo(), and testMsgField().
getI2()
DataId SingleMsg::getI2 () const
Definition at line 199 of file SingleMsg.cpp.
{
    return i2_;
}
References i2_.
Referenced by initCinfo(), and testMsgField().
getTargetField()
unsigned int SingleMsg::getTargetField () const
Definition at line 217 of file SingleMsg.cpp.
{
    return f2_;
}
References f2_.
i1()
DataId SingleMsg::i1 () const
Definition at line 81 of file SingleMsg.cpp.
{
    return i1_;
}
References i1_.
i2()
DataId SingleMsg::i2 () const
Definition at line 86 of file SingleMsg.cpp.
{
    return i2_;
}
References i2_.
initCinfo()
const Cinfo * SingleMsg::initCinfo () static
Definition at line 148 of file SingleMsg.cpp.
{
    // Field definitions.
    static ValueFinfo< SingleMsg, DataId > index1(
        "i1",
        "Index of source object.",
        &SingleMsg::setI1,
        &SingleMsg::getI1
    );
    static ValueFinfo< SingleMsg, DataId > index2(
        "i2",
        "Index of dest object.",
        &SingleMsg::setI2,
        &SingleMsg::getI2
    );
    static Finfo* singleMsgFinfos[] =
    {
        &index1,        // value
        &index2,        // value
    };
    static Dinfo< short > dinfo;
    static Cinfo singleMsgCinfo (
        "SingleMsg",                    // name
        Msg::initCinfo(),       // base class
        singleMsgFinfos,
        sizeof( singleMsgFinfos ) / sizeof( Finfo* ),   // num Fields
        &dinfo
    );
    return &singleMsgCinfo;
}
References Cinfo::Cinfo(), getI1(), getI2(), Msg::initCinfo(), setI1(), setI2(), and ValueFinfo< T, F >::ValueFinfo().
Referenced by Msg::initMsgManagers().
lookupMsg()
char * SingleMsg::lookupMsg (unsigned int index) static
Static function for Msg access.
Definition at line 229 of file SingleMsg.cpp.
{
    assert( index < msg_.size() );
    return reinterpret_cast< char* >( msg_[index] );
}
References msg_.
Referenced by Msg::clearAllMsgs(), and Msg::initMsgManagers().
managerId()
Id SingleMsg::managerId () const
Definition at line 91 of file SingleMsg.cpp.
{
    return SingleMsg::managerId_;
}
References managerId_.
numMsg()
unsigned int SingleMsg::numMsg () static
Msg lookup functions.
Static function for Msg access.
Definition at line 223 of file SingleMsg.cpp.
{
    return msg_.size();
}
References msg_.
Referenced by Msg::clearAllMsgs(), and Msg::initMsgManagers().
setI1()
void SingleMsg::setI1 (DataId di)
Definition at line 192 of file SingleMsg.cpp.
{
    i1_ = di;
    e1()->markRewired();
    e2()->markRewired();
}
References Msg::e1(), Msg::e2(), i1_, and Element::markRewired().
Referenced by initCinfo(), and testMsgField().
setI2()
void SingleMsg::setI2 (DataId di)
Definition at line 204 of file SingleMsg.cpp.
{
    i2_ = di;
    e1()->markRewired();
    e2()->markRewired();
}
References Msg::e1(), Msg::e2(), i2_, and Element::markRewired().
Referenced by initCinfo(), and testMsgField().
setTargetField()
void SingleMsg::setTargetField (unsigned int f)
Definition at line 211 of file SingleMsg.cpp.
{
    f2_ = f;
    e1()->markRewired();
}
References Msg::e1(), f2_, and Element::markRewired().
sources()
void SingleMsg::sources (vector< vector< Eref > > & v) const virtual
Return all the sources of e2 from e1, that is, all the msgs coming into specified entries on e2 from e1.
ALLDATA used when the sources include all data entries on a source. Indexing is v[dataId in range e2.numData][src list]
Implements Msg.
Definition at line 55 of file SingleMsg.cpp.
{
    v.clear();
    v.resize( e2_->numData() );
    v[i2_].resize( 1, Eref( e1_, i1_ ) );
}
References Msg::e1_, Msg::e2_, Eref::Eref(), i1_, i2_, and Element::numData().
targets()
void SingleMsg::targets (vector< vector< Eref > > & v) const virtual
Return all the targets of e1 on e2, that is, all the msgs going from specified entries on e1 to e2. ALLDATA used when the targets include all data entries on a target. Indexing is v[dataId in range e1.numData][tgt list]
Implements Msg.
Definition at line 62 of file SingleMsg.cpp.
{
    v.clear();
    v.resize( e1_->numData() );
    v[i1_].resize( 1, Eref( e2_, i2_, f2_ ) );
}
References Msg::e1_, Msg::e2_, Eref::Eref(), f2_, i1_, i2_, and Element::numData().
Friends And Related Symbol Documentation
Msg::initMsgManagers
unsigned int Msg::initMsgManagers () friend
Member Data Documentation
f2_
unsigned int SingleMsg::f2_ private
Definition at line 60 of file SingleMsg.h.
Referenced by copy(), firstTgt(), getTargetField(), setTargetField(), SingleMsg(), and targets().
i1_
DataId SingleMsg::i1_ private
Definition at line 58 of file SingleMsg.h.
Referenced by copy(), findOtherEnd(), firstTgt(), getI1(), i1(), setI1(), SingleMsg(), sources(), and targets().
i2_
DataId SingleMsg::i2_ private
Definition at line 59 of file SingleMsg.h.
Referenced by copy(), findOtherEnd(), firstTgt(), getI2(), i2(), setI2(), SingleMsg(), sources(), and targets().
managerId_
Id SingleMsg::managerId_ static private
Definition at line 61 of file SingleMsg.h.
Referenced by Msg::initMsgManagers(), managerId(), and SingleMsg().
msg_
vector< SingleMsg * > SingleMsg::msg_ static private
Definition at line 62 of file SingleMsg.h.
Referenced by lookupMsg(), numMsg(), SingleMsg(), and ~SingleMsg().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/msg/SingleMsg.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/msg/SingleMsg.cpp