MOOSE - Multiscale Object Oriented Simulation Environment: LookupField< L, A > Class Template Reference
LookupField< L, A > Class Template Reference
#include <SetGet.h>
Public Member Functions
LookupField (const ObjId &dest)
Public Member Functions inherited from SetGet2< L, A >
SetGet2 ()
Public Member Functions inherited from SetGet
virtual bool checkOpClass (const OpFunc *op) const =0
SetGet ()
virtual ~SetGet ()
Static Public Member Functions
static A get (const ObjId &dest, const string &field, L index)
static void getVec (Id dest, const string &field, vector< L > &index, vector< A > &vec)
static bool innerStrGet (const ObjId &dest, const string &field, const string &indexStr, string &str)
static bool innerStrSet (const ObjId &dest, const string &field, const string &indexStr, const string &val)
static bool set (const ObjId &dest, const string &field, L index, A arg)
static bool setRepeat (Id destId, const string &field, const vector< L > &index, A arg)
static bool setVec (Id destId, const string &field, const vector< L > &index, const vector< A > &arg)
static bool setVec (ObjId dest, const string &field, const vector< L > &index, const vector< A > &arg)
Static Public Member Functions inherited from SetGet2< L, A >
static bool innerStrSet (const ObjId &dest, const string &field, const string &val)
static bool set (const ObjId &dest, const string &field, L arg1, A arg2)
static bool setVec (Id destId, const string &field, const vector< L > &arg1, const vector< A > &arg2)
Static Public Member Functions inherited from SetGet
static const OpFunc * checkSet (const string &field, ObjId &tgt, FuncId &fid)
static const vector< double * > * dispatchGet (const ObjId &tgt, FuncId tgtFid, const double *arg, unsigned int size)
Sends out request for data, and awaits its return.
static bool strGet (const ObjId &tgt, const string &field, string &ret)
static bool strSet (const ObjId &dest, const string &field, const string &val)
Detailed Description
template<class L, class A>
class LookupField< L, A >
LookupField handles fields that have an index arguments. Examples include arrays and maps. The first argument in the 'Set' is the index, the second the value. The first and only argument in the 'get' is the index. Here A is the type of the value, and L the lookup index.
Definition at line 493 of file SetGet.h.
Constructor & Destructor Documentation
LookupField()
template<class L , class A > LookupField< L, A >::LookupField (const ObjId & dest) inline
Definition at line 496 of file SetGet.h.
        : SetGet2< L, A >( dest )
    {
        ;
    }
Member Function Documentation
get()
template<class L , class A > static A LookupField< L, A >::get (const ObjId & dest, const string & field, L index) inline static
Gets a value on a specific object, looking it up using the provided index.
Definition at line 570 of file SetGet.h.
    {
        ObjId tgt( dest );
        FuncId fid;
        string fullFieldName = "get" + field;
        fullFieldName[3] = std::toupper( fullFieldName[3] );
        const OpFunc* func = SetGet::checkSet( fullFieldName, tgt, fid);
        const LookupGetOpFuncBase< L, A >* gof =
            dynamic_cast< const LookupGetOpFuncBase< L, A >* >( func );
        if ( gof )
        {
            if ( tgt.isDataHere() )
            {
                return gof->returnOp( tgt.eref(), index );
            }
            else
            {
                /*
                const OpFunc* op2 = gof->makeHopFunc(
                HopIndex( gof->opIndex(), MooseGetHop ), index );
                const OpFunc1Base< A* >* hop =
                dynamic_cast< const OpFunc1Base< A* >* >( op2 );
                */
                cout << "Warning: LookupField::get: cannot cross nodes yet\n";
                return A();
                /*
                assert( hop );
                // Blocking function.
                hop->op( tgt.eref(), &ret );
                delete op2;
                return ret;
                */
            }
        }
        cout << "LookupField::get: Warning: Field::Get conversion error for " <<
             dest.id.path() << "." << field << endl;
        return A();
    }
References SetGet::checkSet(), ObjId::eref(), ObjId::id, ObjId::isDataHere(), ObjId::ObjId(), and Id::path().
Referenced by PoolBase::getCoords(), Neutral::getDt(), getEnzCplx(), getEnzMol(), PoolBase::getMidPoint(), LookupField< L, A >::innerStrGet(), lookupVolumeFromMesh(), storeCplxEnzMsgs(), storeFunctionMsgs(), storeMMenzMsgs(), storeReacMsgs(), testCellDiffn(), testCylDiffn(), testCylDiffnWithStoich(), testGetMsg(), testLookupSetGet(), testSmallCellDiffn(), testTable(), and writeKkit().
getVec()
template<class L , class A > static void LookupField< L, A >::getVec (Id dest, const string & field, vector< L > & index, vector< A > & vec) inline static
Blocking call that returns a vector of values in vec. This variant goes through each target object entry on dest, and passes in the same lookup index to each one. The results are put together in the vector vec.
Definition at line 615 of file SetGet.h.
    {
        vec.resize( 0 );
        ObjId tgt( dest );
        FuncId fid;
        string fullFieldName = "get" + field;
        fullFieldName[3] = std::toupper( fullFieldName[3] );
        const OpFunc* func = SetGet::checkSet( fullFieldName, tgt, fid );
        const LookupGetOpFuncBase< L, A >* gof =
            dynamic_cast< const LookupGetOpFuncBase< L, A >* >( func );
        if ( gof )
        {
            Element* elm = dest.element();
            unsigned int size = vec.size(); // temporary. See SetVec.
            vec.resize( size );
            for ( unsigned int i = 0; i < size; ++i )
            {
                Eref e( elm, i );
                vec[i] = gof->returnOp( e, index );
            }
            return;
        }
        cout << "Warning: Field::getVec conversion error for " <<
             dest.path() << endl;
    }
References SetGet::checkSet(), Id::element(), Eref::Eref(), ObjId::ObjId(), and Id::path().
innerStrGet()
template<class L , class A > static bool LookupField< L, A >::innerStrGet (const ObjId & dest, const string & field, const string & indexStr, string & str) inline static
Blocking virtual call for finding a value and returning in a string.
Definition at line 646 of file SetGet.h.
    {
        L index;
        Conv< L >::str2val( index, indexStr );
        A ret = get( dest, field, index );
        Conv<A>::val2str( str, ret );
        return 1;
    }
References LookupField< L, A >::get().
innerStrSet()
template<class L , class A > static bool LookupField< L, A >::innerStrSet (const ObjId & dest, const string & field, const string & indexStr, const string & val) inline static
Blocking call using string conversion
Definition at line 552 of file SetGet.h.
    {
        L index;
        Conv< L >::str2val( index, indexStr );
        A arg;
        // Do NOT add 'set_' to the field name, as the 'set' func
        // does it anyway.
        Conv< A >::str2val( arg, val );
        return set( dest, field, index, arg );
    }
References LookupField< L, A >::set().
set()
template<class L , class A > static bool LookupField< L, A >::set (const ObjId & dest, const string & field, L index, A arg) inline static
Blocking, typed 'Set' call. Identical to SetGet2::set.
Definition at line 505 of file SetGet.h.
    {
        string temp = "set" + field;
        temp[3] = std::toupper( temp[3] );
        return SetGet2< L, A >::set( dest, temp, index, arg );
    }
Referenced by Shell::doSetClock(), LookupField< L, A >::innerStrSet(), Neuron::scaleHeadDiffusion(), and testLookupSetGet().
setRepeat()
template<class L , class A > static bool LookupField< L, A >::setRepeat (Id destId, const string & field, const vector< L > & index, A arg) inline static
Faking setRepeat too. Just plugs into setVec.
Definition at line 542 of file SetGet.h.
    {
        vector< A > avec( index.size(), arg );
        return setVec( destId, field, index, avec );
    }
setVec() [1/2]
template<class L , class A > static bool LookupField< L, A >::setVec (Id destId, const string & field, const vector< L > & index, const vector< A > & arg) inline static
This setVec assigns goes through each object entry in the destId, and assigns the corresponding index and argument to it.
Definition at line 517 of file SetGet.h.
    {
        string temp = "set" + field;
        temp[3] = std::toupper( temp[3] );
        return SetGet2< L, A >::setVec( destId, temp, index, arg );
    }
setVec() [2/2]
template<class L , class A > static bool LookupField< L, A >::setVec (ObjId dest, const string & field, const vector< L > & index, const vector< A > & arg) inline static
This setVec takes a specific object entry, presumably one with an array of values within it. The it goes through each specified index and assigns the corresponding argument. This is a brute-force assignment.
Definition at line 531 of file SetGet.h.
    {
        string temp = "set" + field;
        temp[3] = std::toupper( temp[3] );
        return SetGet2< L, A >::setVec( dest, temp, index, arg );
    }
The documentation for this class was generated from the following file:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/basecode/SetGet.h