MOOSE - Multiscale Object Oriented Simulation Environment: ReadOnlyLookupElementValueFinfo< T, L, F > Class Template Reference
ReadOnlyLookupElementValueFinfo< T, L, F > Class Template Reference
#include <LookupElementValueFinfo.h>
Public Member Functions
ReadOnlyLookupElementValueFinfo (const string &name, const string &doc, F(T::*getFunc)(const Eref &e, L) const)
void registerFinfo (Cinfo *c)
string rttiType () const
bool strGet (const Eref &tgt, const string &field, string &returnValue) const
bool strSet (const Eref &tgt, const string &field, const string &arg) const
~ReadOnlyLookupElementValueFinfo ()
Public Member Functions inherited from LookupValueFinfoBase
LookupValueFinfoBase (const string &name, const string &doc)
~LookupValueFinfoBase ()
Public Member Functions inherited from Finfo
virtual bool addMsg (const Finfo *target, ObjId mid, Element *src) const
virtual bool checkTarget (const Finfo *target) const
const string & docs () const
Returns documentation string.
Finfo (const string &name, const string &doc)
virtual vector< string > innerDest () const
virtual vector< string > innerSrc () const
const string & name () const
virtual void postCreationFunc (Id newId, Element *newElm) const
virtual ~Finfo ()
Private Attributes
DestFinfo * get_
Additional Inherited Members
Static Public Member Functions inherited from Finfo
static const Cinfo * initCinfo ()
Detailed Description
template<class T, class L, class F>
class ReadOnlyLookupElementValueFinfo< T, L, F >
Definition at line 80 of file LookupElementValueFinfo.h.
Constructor & Destructor Documentation
~ReadOnlyLookupElementValueFinfo()
template<class T , class L , class F > ReadOnlyLookupElementValueFinfo< T, L, F >::~ReadOnlyLookupElementValueFinfo () inline
Definition at line 83 of file LookupElementValueFinfo.h.
{
            delete get_;
        }
References ReadOnlyLookupElementValueFinfo< T, L, F >::get_.
ReadOnlyLookupElementValueFinfo()
template<class T , class L , class F > ReadOnlyLookupElementValueFinfo< T, L, F >::ReadOnlyLookupElementValueFinfo (const string & name, const string & doc, F(T::*)(const Eref &e, L) const getFunc) inline
Definition at line 87 of file LookupElementValueFinfo.h.
            : LookupValueFinfoBase( name, doc )
        {
                string getname = "get" + name;
                getname[3] = std::toupper( getname[3] );
                get_ = new DestFinfo(
                    getname,
                    "Requests field value. The requesting Element must "
                    "provide a handler for the returned value.",
                    new GetEpFunc1< T, L, F >( getFunc ) );
        }
References ReadOnlyLookupElementValueFinfo< T, L, F >::get_.
Referenced by Neuron::initCinfo(), and Neutral::initCinfo().
Member Function Documentation
registerFinfo()
template<class T , class L , class F > void ReadOnlyLookupElementValueFinfo< T, L, F >::registerFinfo (Cinfo * c) inline virtual
Returns string-ified form to handle template expectations for name field string getName() const; Assign function Ids, bindIndex and so on.
Implements Finfo.
Definition at line 102 of file LookupElementValueFinfo.h.
{
            c->registerFinfo( get_ );
        }
References ReadOnlyLookupElementValueFinfo< T, L, F >::get_, and Cinfo::registerFinfo().
rttiType()
template<class T , class L , class F > string ReadOnlyLookupElementValueFinfo< T, L, F >::rttiType () const inline virtual
Returns the documentation string for the Finfo string docs() const; Returns the RTTI type string for the finfo by referring to an internal virtual function. string type() const; Returns the list of subsidiary SrcFinfos. Used in Shared Finfos, empty otherwise. Goes via internal virtual function. vector< string > src() const; Returns the list of subsidiary destFinfos. Used in SharedFinfos and ValueFinfos, empty otherwise. Goes via internal virtual function. vector< string > dest() const; Returns an RTTI type string for this Finfo.
Reimplemented from Finfo.
Definition at line 119 of file LookupElementValueFinfo.h.
{
                        return Conv<L>::rttiType() + "," + Conv<F>::rttiType();
        }
strGet()
template<class T , class L , class F > bool ReadOnlyLookupElementValueFinfo< T, L, F >::strGet (const Eref & tgt, const string & field, string & returnValue) const inline virtual
Function to return value of field into a string argument. Returns true on success. Normally called only from SetGet::strGet.
Implements Finfo.
Definition at line 111 of file LookupElementValueFinfo.h.
{
            string fieldPart = field.substr( 0, field.find( "[" ) );
            string indexPart = field.substr( field.find( "[" ) + 1, field.find( "]" ) );
            return LookupField< L, F >::innerStrGet(
                    tgt.objId(), fieldPart, indexPart, returnValue );
        }
References Eref::objId().
strSet()
template<class T , class L , class F > bool ReadOnlyLookupElementValueFinfo< T, L, F >::strSet (const Eref & tgt, const string & field, const string & arg) const inline virtual
Function to set this field using a string argument. Returns true on success. Normally called only from SetGet::strSet.
Implements Finfo.
Definition at line 106 of file LookupElementValueFinfo.h.
{
            return 0;
        }
Member Data Documentation
get_
template<class T , class L , class F > DestFinfo* ReadOnlyLookupElementValueFinfo< T, L, F >::get_ private
Definition at line 124 of file LookupElementValueFinfo.h.
Referenced by ReadOnlyLookupElementValueFinfo< T, L, F >::ReadOnlyLookupElementValueFinfo(), ReadOnlyLookupElementValueFinfo< T, L, F >::registerFinfo(), and ReadOnlyLookupElementValueFinfo< T, L, F >::~ReadOnlyLookupElementValueFinfo().
The documentation for this class was generated from the following file:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/basecode/LookupElementValueFinfo.h