MOOSE - Multiscale Object Oriented Simulation Environment: TgtInfo Class Reference
TgtInfo Class Reference
#include <PostMaster.h>
Public Member Functions
unsigned int bindIndex () const
unsigned int dataSize () const
Eref eref () const
void set (ObjId id, unsigned int bindIndex, unsigned int size)
TgtInfo ()
Static Public Attributes
static const unsigned int headerSize
Private Attributes
unsigned int bindIndex_
unsigned int dataSize_
ObjId id_
Detailed Description
This is how internode message passing works. I'll describe this at two levels: the movement of data, and then the setup.
Level 1: Movement of data.
Object Sender sends out an argument A in a regular message.
The SrcFinfo scans through targets in the MsgDigest via func,tgt pairs
The off-node (Func,tgt-Eref) pair holds a HopFunc and a special Eref. The main part of the Eref is the originating object. The FieldIndex of the Eref is the target node.
The HopFunc fills in the Send buffer of the postmaster. It uses the target node info, stuffs in the ObjId of the originating object, and converts and stuffs each of the arguments using Conv< A >. Thus the Send buffer contents are a header with TgtInfo, and then the actual arguments.
This happens for all outgoing messages this cycle.
Postmaster sends out buffers in process. It then waits for incoming stuff in the recvBufs.
The scene now shifts to the PostMaster on the remote node. In its 'process', the clearPending call is executed. It looks at the recvBuf and extracts the tgtInfo. This tells it what the originating object was, and what SrcFinfo to use for the outgoing message. !!!! fixme (Currently I use BindIndex which ought to be right but is done very indirectly. I need to check.)
we call the SrcFinfo::sendBuffer call from the originating object. The sendBuffer call converts the arguments back from the bufer to their native form and despatches using the regular messaging. Note that the MsgDigest will have done the right thing here to set up the regular messaging even for off-node DataIndices on this element.
Messages reach their targets.
Level 2. Setup.
Objects and messages set up the regular way. Objects may have subsets of their Data arrays placed on different nodes. Messages are globals, their contents are replicated on every node.
When a SrcFinfo::send call is about to execute for the first time, it is digested: Element::digestMessages. During this step each of the messages is expanded by putTargetsInDigeest into target Erefs.
The target Erefs are inspected in filterOffNodeTargets. Off-node targets are removed, and we record each pair of Source DataId and node.
We now call putOffNodeTargetsInDigest. This generates the HopFunc by calling OpFunc::makeHopFunc with the fid of the SrcFinfo.
putOffNodeTargetsInDigest then examines the Source/Node pairs and creates HopFunc/Eref pairs which are stuffed into the msgDigest. Note that these Erefs are the hacked version where the Eref specifies the originating object, plus using its FieldIndex to specify the target node.
Possible optimization here would be to have a sendToAll buffer that was filled when the digestMessages detected that a majority of target nodes received a given message. A setup time complication, not a runtime problem.
Definition at line 72 of file PostMaster.h.
Constructor & Destructor Documentation
TgtInfo()
TgtInfo::TgtInfo () inline
Definition at line 74 of file PostMaster.h.
                : id_(),
                bindIndex_( 0 ), dataSize_( 0 )
        {;}
References bindIndex_, dataSize_, id_, and ObjId::ObjId().
Member Function Documentation
bindIndex()
unsigned int TgtInfo::bindIndex () const inline
Definition at line 93 of file PostMaster.h.
{
            return bindIndex_;
        }
References bindIndex_.
Referenced by testHopFunc().
dataSize()
unsigned int TgtInfo::dataSize () const inline
Definition at line 89 of file PostMaster.h.
{
            return dataSize_;
        }
References dataSize_.
Referenced by testHopFunc().
eref()
Eref TgtInfo::eref () const inline
Definition at line 79 of file PostMaster.h.
{
            return Eref( id_.eref() );
        }
References ObjId::eref(), and id_.
set()
void TgtInfo::set (ObjId id, unsigned int bindIndex, unsigned int size) inline
Definition at line 83 of file PostMaster.h.
{
            id_ = id;
            bindIndex_ = bindIndex;
            dataSize_ = size;
        }
References bindIndex_, dataSize_, and id_.
Referenced by PostMaster::addToSendBuf(), PostMaster::addToSetBuf(), and addToTestBuf().
Member Data Documentation
bindIndex_
unsigned int TgtInfo::bindIndex_ private
Definition at line 100 of file PostMaster.h.
Referenced by bindIndex(), set(), and TgtInfo().
dataSize_
unsigned int TgtInfo::dataSize_ private
Definition at line 101 of file PostMaster.h.
Referenced by dataSize(), set(), and TgtInfo().
headerSize
const unsigned int TgtInfo::headerSize static
Initial value:
=
        1 + ( sizeof( TgtInfo ) - 1 )/sizeof( double )
Definition at line 97 of file PostMaster.h.
Referenced by PostMaster::addToSendBuf(), PostMaster::addToSetBuf(), addToTestBuf(), PostMaster::PostMaster(), and testHopFunc().
id_
ObjId TgtInfo::id_ private
Definition at line 99 of file PostMaster.h.
Referenced by eref(), set(), and TgtInfo().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/mpi/PostMaster.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/mpi/PostMaster.cpp