MOOSE - Multiscale Object Oriented Simulation Environment: GapJunction Class Reference
GapJunction Class Reference
#include <GapJunction.h>
Public Member Functions
GapJunction ()
double getGk () const
void process (const Eref &e, ProcPtr p)
void reinit (const Eref &e, ProcPtr p)
void setGk (double g)
void setVm1 (double Vm)
void setVm2 (double Vm)
~GapJunction ()
Static Public Member Functions
static const Cinfo * initCinfo ()
Protected Attributes
double Gk_
double Vm1_
double Vm2_
Detailed Description
Definition at line 48 of file GapJunction.h.
Constructor & Destructor Documentation
GapJunction()
GapJunction::GapJunction ()
Definition at line 170 of file GapJunction.cpp.
                        :Vm1_(0.0), Vm2_(0.0), Gk_(1e-9)
{
    ;
}
References Gk_, Vm1_, and Vm2_.
~GapJunction()
GapJunction::~GapJunction ()
Definition at line 175 of file GapJunction.cpp.
{
    ;
}
Member Function Documentation
getGk()
double GapJunction::getGk () const
Definition at line 185 of file GapJunction.cpp.
{
    return Gk_;
}
References Gk_.
Referenced by initCinfo().
initCinfo()
const Cinfo * GapJunction::initCinfo () static
Initializes the class info.
Definition at line 67 of file GapJunction.cpp.
{
    static ValueFinfo< GapJunction, double > Gk(
        "Gk",
        "Conductance of the gap junction",
        &GapJunction::setGk,
        &GapJunction::getGk);
    // Shared messages
    static DestFinfo process(
        "process",
        "Handles 'process' call",
        new ProcOpFunc< GapJunction >( &GapJunction::process ) );
    static DestFinfo reinit(
        "reinit",
        "Handles 'reinit' call",
        new ProcOpFunc< GapJunction >( &GapJunction::reinit ) );
    static Finfo* processShared[] = {
        &process, &reinit
    };
    static SharedFinfo proc(
        "proc",
        "This is a shared message to receive Process messages "
        "from the scheduler objects. The Process should be called "
        "_second_ in each clock tick, after the Init message."
        "The first entry in the shared msg is a MsgDest "
        "for the Process operation. It has a single argument, "
        "ProcInfo, which holds lots of information about current "
        "time, thread, dt and so on. The second entry is a MsgDest "
        "for the Reinit operation. It also uses ProcInfo. ",
        processShared, sizeof( processShared ) / sizeof( Finfo* ));
    static DestFinfo Vm1(
        "Vm1",
        "Handles Vm message from compartment",
        new OpFunc1 < GapJunction, double >( &GapJunction::setVm1 ));
    static Finfo * channel1Shared[] = {
        channel1Out(), &Vm1,
    };
    static SharedFinfo channel1(
        "channel1",
        "This is a shared message to couple the conductance and Vm from\n"
        "terminal 2 to the compartment at terminal 1. The first entry is source\n"
        "sending out Gk and Vm2, the second entry is destination for Vm1.",
        channel1Shared, sizeof(channel1Shared)/sizeof(Finfo*));
    static DestFinfo Vm2(
        "Vm2",
        "Handles Vm message from another compartment",
        new OpFunc1< GapJunction, double >( &GapJunction::setVm2 ));
    static Finfo * channel2Shared[] = {
        channel2Out(), &Vm2,
    };
    static SharedFinfo channel2(
        "channel2",
        "This is a shared message to couple the conductance and Vm from\n"
        "terminal 1 to the compartment at terminal 2. The first entry is source\n"
        "sending out Gk and Vm1, the second entry is destination for Vm2.",
        channel2Shared, sizeof(channel2Shared)/sizeof(Finfo*));
    static Finfo * gapJunctionFinfos[] =
    {
        &channel1,
        &channel2,
        &Gk,
        &proc
    };
    static string doc[] = {
        "Name", "GapJunction",
        "Author", "Subhasis Ray, 2013",
        "Description", "Implementation of gap junction between two compartments. The shared\n"
        "fields, 'channel1' and 'channel2' can be connected to the 'channel'\n"
        "message of the compartments at either end of the gap junction. The\n"
        "compartments will send their Vm to the gap junction and receive the\n"
        "conductance 'Gk' of the gap junction and the Vm of the other\n"
        "compartment."
    };
    static Dinfo< GapJunction > dinfo;
    static Cinfo gapJunctionCinfo(
        "GapJunction",
        Neutral::initCinfo(),
        gapJunctionFinfos,
        sizeof(gapJunctionFinfos)/sizeof(Finfo*),
        &dinfo,
        doc,
        sizeof(doc) / sizeof(string));
    return &gapJunctionCinfo;
}
References channel1Out(), channel2Out(), Cinfo::Cinfo(), DestFinfo::DestFinfo(), getGk(), Neutral::initCinfo(), OpFunc1< T, A >::OpFunc1(), process(), ProcOpFunc< T >::ProcOpFunc(), reinit(), setGk(), setVm1(), setVm2(), SharedFinfo::SharedFinfo(), and ValueFinfo< T, F >::ValueFinfo().
process()
void GapJunction::process (const Eref & e, ProcPtr p)
The process function does the object updating and sends out messages to channels, nernsts, and so on.
Definition at line 200 of file GapJunction.cpp.
{
    channel1Out()->send(e, Gk_, Vm2_);
    channel2Out()->send(e, Gk_, Vm1_);
}
References channel1Out(), channel2Out(), Gk_, SrcFinfo2< T1, T2 >::send(), Vm1_, and Vm2_.
Referenced by initCinfo().
reinit()
void GapJunction::reinit (const Eref & e, ProcPtr p)
The reinit function reinitializes all fields.
Definition at line 206 of file GapJunction.cpp.
{
    Vm1_ = 0.0;
    Vm2_ = 0.0;
}
References Vm1_, and Vm2_.
Referenced by initCinfo().
setGk()
void GapJunction::setGk (double g)
Definition at line 180 of file GapJunction.cpp.
{
    Gk_ = g;
}
References Gk_.
Referenced by initCinfo().
setVm1()
void GapJunction::setVm1 (double Vm)
Definition at line 190 of file GapJunction.cpp.
{
    Vm1_ = v;
}
References Vm1_.
Referenced by initCinfo().
setVm2()
void GapJunction::setVm2 (double Vm)
Definition at line 195 of file GapJunction.cpp.
{
    Vm2_ = v;
}
References Vm2_.
Referenced by initCinfo().
Member Data Documentation
Gk_
double GapJunction::Gk_ protected
Definition at line 78 of file GapJunction.h.
Referenced by GapJunction(), getGk(), process(), and setGk().
Vm1_
double GapJunction::Vm1_ protected
Definition at line 76 of file GapJunction.h.
Referenced by GapJunction(), process(), reinit(), and setVm1().
Vm2_
double GapJunction::Vm2_ protected
Definition at line 77 of file GapJunction.h.
Referenced by GapJunction(), process(), reinit(), and setVm2().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/biophysics/GapJunction.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/biophysics/GapJunction.cpp