MOOSE - Multiscale Object Oriented Simulation Environment: StimulusTable Class Reference
StimulusTable Class Reference
#include <StimulusTable.h>
Public Member Functions
bool getDoLoop () const
double getLoopTime () const
double getStartTime () const
double getStepPosition () const
double getStepSize () const
double getStopTime () const
void process (const Eref &e, ProcPtr p)
void reinit (const Eref &e, ProcPtr p)
void setDoLoop (bool v)
void setLoopTime (double v)
void setStartTime (double v)
void setStepPosition (double v)
void setStepSize (double v)
void setStopTime (double v)
StimulusTable ()
Public Member Functions inherited from TableBase
void clearVec ()
void compareVec (vector< double > other, string op)
void compareXplot (string fname, string plotname, string op)
const vector< double > & data ()
double getOutputValue () const
string getPlotDump () const
unsigned int getVecSize () const
vector< double > getVector () const
double getY (unsigned int index) const
double interpolate (double x, double xmin, double xmax) const
void linearTransform (double scale, double offset)
void loadCSV (string fname, int startLine, int colNum, char separator)
void loadXplot (string fname, string plotname)
void loadXplotRange (string fname, string plotname, unsigned int start, unsigned int end)
double * lookupVec (unsigned int index)
void plainPlot (string file)
void setOutputValue (double val)
void setPlotDump (string v)
void setVecSize (unsigned int num)
void setVector (vector< double > val)
TableBase ()
void xplot (string file, string plotname)
Static Public Member Functions
static const Cinfo * initCinfo ()
Static Public Member Functions inherited from TableBase
static const Cinfo * initCinfo ()
Private Attributes
bool doLoop_
double loopTime_
double start_
double stepPosition_
double stepSize_
double stop_
Additional Inherited Members
Protected Member Functions inherited from TableBase
vector< double > & vec ()
Detailed Description
Receives and records inputs. Handles plot and spiking data in batch mode.
Definition at line 16 of file StimulusTable.h.
Constructor & Destructor Documentation
StimulusTable()
StimulusTable::StimulusTable ()
Definition at line 138 of file StimulusTable.cpp.
    : start_( 0 ), stop_( 1 ), loopTime_( 1 ),
        stepSize_( 0 ), stepPosition_( 0 ),
    doLoop_( 0 )
{ ; }
References doLoop_, loopTime_, start_, stepPosition_, stepSize_, and stop_.
Member Function Documentation
getDoLoop()
bool StimulusTable::getDoLoop () const
Definition at line 243 of file StimulusTable.cpp.
{
    return doLoop_;
}
References doLoop_.
Referenced by initCinfo().
getLoopTime()
double StimulusTable::getLoopTime () const
Definition at line 211 of file StimulusTable.cpp.
{
    return loopTime_;
}
References loopTime_.
Referenced by initCinfo().
getStartTime()
double StimulusTable::getStartTime () const
Definition at line 184 of file StimulusTable.cpp.
{
    return start_;
}
References start_.
Referenced by initCinfo().
getStepPosition()
double StimulusTable::getStepPosition () const
Definition at line 231 of file StimulusTable.cpp.
{
    return stepPosition_;
}
References stepPosition_.
Referenced by initCinfo().
getStepSize()
double StimulusTable::getStepSize () const
Definition at line 221 of file StimulusTable.cpp.
{
    return stepSize_;
}
References stepSize_.
Referenced by initCinfo().
getStopTime()
double StimulusTable::getStopTime () const
Definition at line 196 of file StimulusTable.cpp.
{
    return stop_;
}
References stop_.
Referenced by initCinfo().
initCinfo()
const Cinfo * StimulusTable::initCinfo () static
Definition at line 23 of file StimulusTable.cpp.
{
        // Field Definitions
        static ValueFinfo< StimulusTable, double > startTime(
            "startTime",
            "Start time used when table is emitting values. For lookup"
            "values below this, the table just sends out its zero entry."
            "Corresponds to zeroth entry of table.",
            &StimulusTable::setStartTime,
            &StimulusTable::getStartTime
        );
        static ValueFinfo< StimulusTable, double > stopTime(
            "stopTime",
            "Time to stop emitting values."
            "If time exceeds this, then the table sends out its last entry."
            "The stopTime corresponds to the last entry of table.",
            &StimulusTable::setStopTime,
            &StimulusTable::getStopTime
        );
        static ValueFinfo< StimulusTable, double > loopTime(
            "loopTime",
            "If looping, this is the time between successive cycle starts."
            "Defaults to the difference between stopTime and startTime, "
            "so that the output waveform cycles with precisely the same "
            "duration as the table contents."
            "If larger than stopTime - startTime, then it pauses at the "
            "last table value till it is time to "
            "go around again."
            "If smaller than stopTime - startTime, then it begins the next "
            "cycle even before the first one has reached the end of the "
            "table.",
            &StimulusTable::setLoopTime,
            &StimulusTable::getLoopTime
        );
        static ValueFinfo< StimulusTable, double > stepSize(
            "stepSize",
            "Increment in lookup (x) value on every timestep. If it is"
            "less than or equal to zero, the StimulusTable uses the current time"
            "as the lookup value.",
            &StimulusTable::setStepSize,
            &StimulusTable::getStepSize
        );
        static ValueFinfo< StimulusTable, double > stepPosition(
            "stepPosition",
            "Current value of lookup (x) value."
            "If stepSize is less than or equal to zero, this is set to"
            "the current time to use as the lookup value.",
            &StimulusTable::setStepPosition,
            &StimulusTable::getStepPosition
        );
        static ValueFinfo< StimulusTable, bool > doLoop(
            "doLoop",
            "Flag: Should it loop around to startTime once it has reached"
            "stopTime. Default (zero) is to do a single pass.",
            &StimulusTable::setDoLoop,
            &StimulusTable::getDoLoop
        );
        // MsgDest Definitions
        static DestFinfo process( "process",
            "Handles process call, updates internal time stamp.",
            new ProcOpFunc< StimulusTable >( &StimulusTable::process ) );
        static DestFinfo reinit( "reinit",
            "Handles reinit call.",
            new ProcOpFunc< StimulusTable >( &StimulusTable::reinit ) );
        // SharedMsg Definitions
        static Finfo* procShared[] = {
            &process, &reinit
        };
        static SharedFinfo proc( "proc",
            "Shared message for process and reinit",
            procShared, sizeof( procShared ) / sizeof( const Finfo* )
        );
    static Finfo* stimulusTableFinfos[] = {
        &startTime,
        &stopTime,
        &loopTime,
        &stepSize,
        &stepPosition,
        &doLoop,
        output(),       // SrcFinfo
        &proc,          // SharedFinfo
    };
    static Dinfo< StimulusTable > dinfo;
    static Cinfo stimulusTableCinfo (
        "StimulusTable",
        TableBase::initCinfo(),
        stimulusTableFinfos,
        sizeof( stimulusTableFinfos ) / sizeof ( Finfo* ),
        &dinfo
    );
    return &stimulusTableCinfo;
}
References Cinfo::Cinfo(), DestFinfo::DestFinfo(), getDoLoop(), getLoopTime(), getStartTime(), getStepPosition(), getStepSize(), getStopTime(), TableBase::initCinfo(), output(), process(), ProcOpFunc< T >::ProcOpFunc(), reinit(), setDoLoop(), setLoopTime(), setStartTime(), setStepPosition(), setStepSize(), setStopTime(), SharedFinfo::SharedFinfo(), and ValueFinfo< T, F >::ValueFinfo().
process()
void StimulusTable::process (const Eref & e, ProcPtr p)
Definition at line 148 of file StimulusTable.cpp.
{
    if ( stepSize_ > 0 )
        stepPosition_ += stepSize_;
    else
        stepPosition_ = p->currTime;
    double lookupPosition = stepPosition_;
    if ( doLoop_ && ( stepPosition_ > start_ + loopTime_ ) ) {
        unsigned int i = static_cast<unsigned int>(floor( ( stepPosition_ - start_ ) / loopTime_ ));
            lookupPosition = stepPosition_ - loopTime_ * i;
    }
    double y = interpolate( start_, stop_, lookupPosition );
    setOutputValue( y );
    output()->send( e, y );
}
References ProcInfo::currTime, doLoop_, TableBase::interpolate(), loopTime_, output(), SrcFinfo1< T >::send(), TableBase::setOutputValue(), start_, stepPosition_, stepSize_, and stop_.
Referenced by initCinfo().
reinit()
void StimulusTable::reinit (const Eref & e, ProcPtr p)
Definition at line 167 of file StimulusTable.cpp.
{
    stepPosition_ = 0.0;
    double y = interpolate( start_, stop_, stepPosition_ );
    setOutputValue( y );
    output()->send( e, y );
}
References TableBase::interpolate(), output(), SrcFinfo1< T >::send(), TableBase::setOutputValue(), start_, stepPosition_, and stop_.
Referenced by initCinfo().
setDoLoop()
void StimulusTable::setDoLoop (bool v)
Definition at line 236 of file StimulusTable.cpp.
{
    doLoop_ = v;
    if ( loopTime_ == 0 )
        loopTime_ = stop_ - start_;
}
References doLoop_, loopTime_, start_, and stop_.
Referenced by initCinfo().
setLoopTime()
void StimulusTable::setLoopTime (double v)
Definition at line 201 of file StimulusTable.cpp.
{
    if ( loopTime_ >= 0 )
        loopTime_ = v;
    else
        cout << "StimulusTable::setLoopTime: Warning: Cannot set to " <<
            v << " as this value is below zero. Left unchanged at " <<
            loopTime_ << "\n";
}
References loopTime_.
Referenced by initCinfo().
setStartTime()
void StimulusTable::setStartTime (double v)
Definition at line 179 of file StimulusTable.cpp.
{
    start_ = v;
}
References start_.
Referenced by initCinfo().
setStepPosition()
void StimulusTable::setStepPosition (double v)
Definition at line 226 of file StimulusTable.cpp.
{
    stepPosition_ = v;
}
References stepPosition_.
Referenced by initCinfo().
setStepSize()
void StimulusTable::setStepSize (double v)
Definition at line 216 of file StimulusTable.cpp.
{
    stepSize_ = v;
}
References stepSize_.
Referenced by initCinfo().
setStopTime()
void StimulusTable::setStopTime (double v)
Definition at line 189 of file StimulusTable.cpp.
{
    if ( doLoop_ && doubleEq( loopTime_, stop_ - start_ ) )
        loopTime_ = v - start_;
    stop_ = v;
}
References doLoop_, doubleEq(), loopTime_, start_, and stop_.
Referenced by initCinfo().
Member Data Documentation
doLoop_
bool StimulusTable::doLoop_ private
Definition at line 55 of file StimulusTable.h.
Referenced by getDoLoop(), process(), setDoLoop(), setStopTime(), and StimulusTable().
loopTime_
double StimulusTable::loopTime_ private
Definition at line 52 of file StimulusTable.h.
Referenced by getLoopTime(), process(), setDoLoop(), setLoopTime(), setStopTime(), and StimulusTable().
start_
double StimulusTable::start_ private
Definition at line 50 of file StimulusTable.h.
Referenced by getStartTime(), process(), reinit(), setDoLoop(), setStartTime(), setStopTime(), and StimulusTable().
stepPosition_
double StimulusTable::stepPosition_ private
Definition at line 54 of file StimulusTable.h.
Referenced by getStepPosition(), process(), reinit(), setStepPosition(), and StimulusTable().
stepSize_
double StimulusTable::stepSize_ private
Definition at line 53 of file StimulusTable.h.
Referenced by getStepSize(), process(), setStepSize(), and StimulusTable().
stop_
double StimulusTable::stop_ private
Definition at line 51 of file StimulusTable.h.
Referenced by getStopTime(), process(), reinit(), setDoLoop(), setStopTime(), and StimulusTable().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/builtins/StimulusTable.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/builtins/StimulusTable.cpp