MOOSE - Multiscale Object Oriented Simulation Environment: KsolveBase Class Reference
KsolveBase Class Reference abstract
#include <KsolveBase.h>
Public Member Functions
virtual void getBlock (vector< double > &values) const =0
Id getCompartment () const
virtual double getConcInit (const Eref &e) const =0
get initial conc of molecules in given pool and voxel. Bdry cond.
virtual double getDiffConst (const Eref &e) const =0
Diffusion constant: Only one per pool, voxel number is ignored.
virtual double getMotorConst (const Eref &e)
virtual double getN (const Eref &e) const =0
Get # of molecules in given pool and voxel. Varies with time.
virtual unsigned int getNumLocalVoxels () const =0
Number of voxels here. pools_.size() == getNumLocalVoxels.
virtual unsigned int getNumPools () const =0
gets number of pools (species) handled by system.
virtual unsigned int getPoolIndex (const Eref &er) const =0
Return pool index, using Stoich ptr to do lookup.
virtual double getR1 (unsigned int reacIdx, const Eref &e) const =0
virtual double getVolumeOfPool (const Eref &e) const =0
Return volume of pool e.
KsolveBase ()
virtual void notifyAddMsgDestPool (const Eref &e, ObjId msgId)
virtual void notifyAddMsgSrcPool (const Eref &e, ObjId msgId)
virtual void notifyAddPool (const Eref &e)
virtual void notifyDestroyPool (const Eref &e)
virtual void notifyRemovePool (const Eref &e)
virtual VoxelPoolsBase * pools (unsigned int i)=0
Return a pointer to the specified VoxelPool.
virtual void setBlock (const vector< double > &values)=0
virtual void setCompartment (Id compartment)
Assigns compartment.
virtual void setConcInit (const Eref &e, double val)=0
Set initial conc of molecules in given pool and voxel. Bdry cond.
virtual void setDiffConst (const Eref &e, double val)=0
Diffusion constant: Only one per pool, voxel number is ignored.
virtual void setDsolve (Id dsolve)=0
Assigns the diffusion solver. Used by the reac solvers.
virtual void setIsBuffered (const Eref &e, bool val)
Set buffer status of pool. Changes class between Pool and BufPool.
virtual void setMotorConst (const Eref &e, double val)
virtual void setN (const Eref &e, double val)=0
Set # of molecules in given pool and voxel. Varies with time.
virtual void setNumAllVoxels (unsigned int numVoxels)=0
Assign number of voxels (size of pools_ vector)
virtual void setNumPools (unsigned int num)=0
Specifies number of pools (species) handled by system.
virtual void setNumVarTotPools (unsigned int var, unsigned int tot)=0
Specifies number of var pools and total pools including buffered .
virtual void setPrev ()
Used to tell Dsolver to assign 'prev' values.
virtual void setStoich (Id stoich)=0
virtual void updateJunctions (double dt)
Used for telling Dsolver to handle all ops across Junctions.
virtual void updateRateTerms (unsigned int index=~0U)=0
virtual double volume (unsigned int i) const =0
Return volume of voxel i.
Protected Attributes
Id compartment_
Id of Chem compartment used to figure out volumes of voxels.
bool isBuilt_
Flag: True when solver setup has been completed.
Id stoich_
Detailed Description
This pure virtual base class is for solvers that want to talk to pools. The Eref specifies both the pool identity and the voxel number within the pool.
Definition at line 18 of file KsolveBase.h.
Constructor & Destructor Documentation
KsolveBase()
KsolveBase::KsolveBase ()
Definition at line 32 of file KsolveBase.cpp.
    : stoich_(), compartment_(), isBuilt_(false)
{;}
References compartment_, Id::Id(), isBuilt_, and stoich_.
Member Function Documentation
getBlock()
virtual void KsolveBase::getBlock (vector< double > & values) const pure virtual
Gets block of data. The first 4 entries are passed in on the 'values' vector: the start voxel, numVoxels, start pool#, numPools. These are followed by numVoxels * numPools of data values which are filled in by the function. We assert that the entire requested block is present in this KsolveBase. The block is organized as an array of arrays of voxels; values[pool#][voxel#]
Note that numVoxels and numPools are the number in the current block, not the upper limit of the block. So values.size() == 4 + numPools * numVoxels.
Implemented in Dsolve, Gsolve, and Ksolve.
Referenced by Gsolve::process(), and Ksolve::process().
getCompartment()
Id KsolveBase::getCompartment () const
Definition at line 44 of file KsolveBase.cpp.
{
    return compartment_;
}
References compartment_.
Referenced by Dsolve::initCinfo(), and Ksolve::initCinfo().
getConcInit()
virtual double KsolveBase::getConcInit (const Eref & e) const pure virtual
get initial conc of molecules in given pool and voxel. Bdry cond.
Implemented in Dsolve, Gsolve, and Ksolve.
getDiffConst()
virtual double KsolveBase::getDiffConst (const Eref & e) const pure virtual
Diffusion constant: Only one per pool, voxel number is ignored.
Implemented in Dsolve, Gsolve, and Ksolve.
getMotorConst()
virtual double KsolveBase::getMotorConst (const Eref & e) inline virtual
Motor constant: Only one per pool, voxel number is ignored. Used only in Dsolves, so here I put in a dummy.
Definition at line 47 of file KsolveBase.h.
    { return 0.0;}
getN()
virtual double KsolveBase::getN (const Eref & e) const pure virtual
Get # of molecules in given pool and voxel. Varies with time.
Implemented in Dsolve, Gsolve, and Ksolve.
Referenced by PoolBase::getN().
getNumLocalVoxels()
virtual unsigned int KsolveBase::getNumLocalVoxels () const pure virtual
Number of voxels here. pools_.size() == getNumLocalVoxels.
Implemented in Dsolve, Gsolve, and Ksolve.
getNumPools()
virtual unsigned int KsolveBase::getNumPools () const pure virtual
gets number of pools (species) handled by system.
Implemented in Dsolve, Gsolve, and Ksolve.
getPoolIndex()
virtual unsigned int KsolveBase::getPoolIndex (const Eref & er) const pure virtual
Return pool index, using Stoich ptr to do lookup.
Implemented in Dsolve, Gsolve, and Ksolve.
getR1()
virtual double KsolveBase::getR1 (unsigned int reacIdx, const Eref & e) const pure virtual
Get rate const in a given reac and voxel. Usually fixed but may vary if the reac is controlled by a function.
Implemented in Dsolve, Gsolve, and Ksolve.
Referenced by Stoich::getReacNumKf().
getVolumeOfPool()
virtual double KsolveBase::getVolumeOfPool (const Eref & e) const pure virtual
Return volume of pool e.
Implemented in Dsolve, Gsolve, and Ksolve.
notifyAddMsgDestPool()
void KsolveBase::notifyAddMsgDestPool (const Eref & e, ObjId msgId) virtual
Reimplemented in Ksolve.
Definition at line 78 of file KsolveBase.cpp.
{;}
Referenced by PoolBase::notifyAddMsgDest().
notifyAddMsgSrcPool()
void KsolveBase::notifyAddMsgSrcPool (const Eref & e, ObjId msgId) virtual
Reimplemented in Ksolve.
Definition at line 75 of file KsolveBase.cpp.
{;}
Referenced by PoolBase::notifyAddMsgSrc().
notifyAddPool()
void KsolveBase::notifyAddPool (const Eref & e) virtual
Reimplemented in Ksolve.
Definition at line 69 of file KsolveBase.cpp.
{;}
Referenced by PoolBase::notifyCopy(), PoolBase::notifyCreate(), and PoolBase::setSolvers().
notifyDestroyPool()
void KsolveBase::notifyDestroyPool (const Eref & e) virtual
Reimplemented in Ksolve.
Definition at line 66 of file KsolveBase.cpp.
{;}
notifyRemovePool()
void KsolveBase::notifyRemovePool (const Eref & e) virtual
Reimplemented in Ksolve.
Definition at line 72 of file KsolveBase.cpp.
{;}
Referenced by PoolBase::notifyDestroy(), PoolBase::notifyMove(), and PoolBase::setSolvers().
pools()
virtual VoxelPoolsBase * KsolveBase::pools (unsigned int i) pure virtual
Return a pointer to the specified VoxelPool.
Implemented in Dsolve, Gsolve, and Ksolve.
Referenced by Stoich::scaleBufsAndRates(), and setCompartment().
setBlock()
virtual void KsolveBase::setBlock (const vector< double > & values) pure virtual
Sets block of data. The first 4 entries on the 'values' vector are the start voxel, numVoxels, start pool#, numPools. These are followed by numVoxels * numPools of data values.
Implemented in Dsolve, Gsolve, and Ksolve.
Referenced by Gsolve::process(), and Ksolve::process().
setCompartment()
void KsolveBase::setCompartment (Id compartment) virtual
Assigns compartment.
Reimplemented in Gsolve, and Dsolve.
Definition at line 49 of file KsolveBase.cpp.
{
    isBuilt_ = false; // We will have to now rebuild the whole thing.
    if ( compt.element()->cinfo()->isA( "ChemCompt" ) )
    {
        compartment_ = compt;
        vector<double> vols = Field<vector<double>>::get( compt, "voxelVolume" );
        if (vols.size() > 0)
        {
            setNumAllVoxels( vols.size() );
            for ( unsigned int i = 0; i < vols.size(); ++i )
                pools(i)->setVolume( vols[i] );
        }
    }
}
References Element::cinfo(), compartment_, Id::element(), Field< A >::get(), Cinfo::isA(), isBuilt_, pools(), setNumAllVoxels(), and VoxelPoolsBase::setVolume().
Referenced by Ksolve::initCinfo(), and Stoich::setElist().
setConcInit()
virtual void KsolveBase::setConcInit (const Eref & e, double val) pure virtual
Set initial conc of molecules in given pool and voxel. Bdry cond.
Implemented in Gsolve, Ksolve, and Dsolve.
Referenced by PoolBase::innerSetConcInit().
setDiffConst()
virtual void KsolveBase::setDiffConst (const Eref & e, double val) pure virtual
Diffusion constant: Only one per pool, voxel number is ignored.
Implemented in Gsolve, Ksolve, and Dsolve.
Referenced by PoolBase::setDiffConst().
setDsolve()
virtual void KsolveBase::setDsolve (Id dsolve) pure virtual
Assigns the diffusion solver. Used by the reac solvers.
Implemented in Gsolve, Ksolve, and Dsolve.
Referenced by Stoich::setElist().
setIsBuffered()
virtual void KsolveBase::setIsBuffered (const Eref & e, bool val) inline virtual
Set buffer status of pool. Changes class between Pool and BufPool.
Definition at line 38 of file KsolveBase.h.
{;}
Referenced by PoolBase::setIsBuffered().
setMotorConst()
virtual void KsolveBase::setMotorConst (const Eref & e, double val) inline virtual
Reimplemented in Dsolve.
Definition at line 49 of file KsolveBase.h.
    {;}
Referenced by PoolBase::setMotorConst().
setN()
virtual void KsolveBase::setN (const Eref & e, double val) pure virtual
Set # of molecules in given pool and voxel. Varies with time.
Implemented in Gsolve, Ksolve, and Dsolve.
Referenced by PoolBase::innerSetN().
setNumAllVoxels()
virtual void KsolveBase::setNumAllVoxels (unsigned int numVoxels) pure virtual
Assign number of voxels (size of pools_ vector)
Implemented in Gsolve, Ksolve, and Dsolve.
Referenced by setCompartment().
setNumPools()
virtual void KsolveBase::setNumPools (unsigned int num) pure virtual
Specifies number of pools (species) handled by system.
Implemented in Dsolve, Gsolve, and Ksolve.
Referenced by Stoich::resizeArrays().
setNumVarTotPools()
virtual void KsolveBase::setNumVarTotPools (unsigned int var, unsigned int tot) pure virtual
Specifies number of var pools and total pools including buffered .
Implemented in Dsolve, Gsolve, and Ksolve.
Referenced by Stoich::resizeArrays().
setPrev()
void KsolveBase::setPrev () virtual
Used to tell Dsolver to assign 'prev' values.
Reimplemented in Dsolve.
Definition at line 39 of file KsolveBase.cpp.
{;}
Referenced by Gsolve::process(), and Ksolve::process().
setStoich()
virtual void KsolveBase::setStoich (Id stoich) pure virtual
Informs the ZPI about the stoich, used during subsequent computations. Called to wrap up the model building. The Stoich does this call after it has set up its own path.
Implemented in Dsolve, Gsolve, and Ksolve.
Referenced by Stoich::setElist().
updateJunctions()
void KsolveBase::updateJunctions (double dt) virtual
Used for telling Dsolver to handle all ops across Junctions.
Reimplemented in Dsolve.
Definition at line 36 of file KsolveBase.cpp.
{;}
Referenced by Gsolve::process(), and Ksolve::process().
updateRateTerms()
virtual void KsolveBase::updateRateTerms (unsigned int index = ~0U) pure virtual
Informs the solver that the rate terms or volumes have changed and that the parameters must be updated. The index specifies which rateTerm to change, and if it is ~0U it means update all of them.
Implemented in Dsolve, Gsolve, and Ksolve.
Referenced by Stoich::setElist(), Stoich::setEnzK1(), Stoich::setEnzK2(), Stoich::setEnzK3(), Stoich::setMMenzKcat(), Stoich::setMMenzKm(), Stoich::setReacKb(), and Stoich::setReacKf().
volume()
virtual double KsolveBase::volume (unsigned int i) const pure virtual
Return volume of voxel i.
Implemented in Dsolve, Gsolve, and Ksolve.
Member Data Documentation
compartment_
Id KsolveBase::compartment_ protected
Id of Chem compartment used to figure out volumes of voxels.
Definition at line 148 of file KsolveBase.h.
Referenced by Dsolve::build(), Dsolve::buildMeshJunctions(), Dsolve::buildNeuroMeshJunctions(), Dsolve::calcLocalChan(), Gsolve::getCompartment(), getCompartment(), KsolveBase(), Ksolve::print(), Dsolve::reinit(), setCompartment(), Gsolve::setCompartment(), and Dsolve::setCompartment().
isBuilt_
bool KsolveBase::isBuilt_ protected
Flag: True when solver setup has been completed.
Definition at line 151 of file KsolveBase.h.
Referenced by KsolveBase(), Ksolve::process(), Ksolve::reinit(), setCompartment(), Ksolve::setMethod(), and Ksolve::setStoich().
stoich_
Id KsolveBase::stoich_ protected
Stoich is the class that sets up the reaction system and manages the stoichiometry matrix
Definition at line 145 of file KsolveBase.h.
Referenced by Dsolve::getStoich(), Gsolve::getStoich(), Ksolve::getStoich(), KsolveBase(), Dsolve::makePoolMapFromElist(), Ksolve::print(), Dsolve::setStoich(), Gsolve::setStoich(), and Ksolve::setStoich().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/ksolve/KsolveBase.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/ksolve/KsolveBase.cpp