MOOSE - Multiscale Object Oriented Simulation Environment: Conv< Id > Class Reference
Conv< Id > Class Reference
#include <Conv.h>
Static Public Member Functions
static const Id buf2val (double **buf)
static string rttiType ()
static unsigned int size (Id val)
static void str2val (Id &val, const string &s)
static void val2buf (Id id, double **buf)
static void val2str (string &s, Id val)
Detailed Description
The template specialization of Conv< Id > sets up alignment on word boundaries by storing the Id as a double. It also deals with the string conversion issues.
Definition at line 499 of file Conv.h.
Member Function Documentation
buf2val()
static const Id Conv< Id >::buf2val (double ** buf) inline static
Definition at line 510 of file Conv.h.
{
            Id ret( (unsigned int)**buf );
            (*buf)++;
            return ret;
        }
References Id::Id().
rttiType()
static string Conv< Id >::rttiType () inline static
Definition at line 529 of file Conv.h.
{
            return "Id";
        }
size()
static unsigned int Conv< Id >::size (Id val) inline static
This is the size used in the serialized form.
Definition at line 505 of file Conv.h.
        {
            return 1;
        }
str2val()
static void Conv< Id >::str2val (Id & val, const string & s) inline static
Definition at line 520 of file Conv.h.
{
            Id temp( s ); // converts the path
            val = temp;
        }
References Id::Id().
val2buf()
static void Conv< Id >::val2buf (Id id, double ** buf) inline static
Definition at line 515 of file Conv.h.
{
            **buf = id.value();
            (*buf)++;
        }
References Id::value().
val2str()
static void Conv< Id >::val2str (string & s, Id val) inline static
Definition at line 525 of file Conv.h.
{
            s = val.path();
        }
References Id::path().
The documentation for this class was generated from the following file:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/basecode/Conv.h