MOOSE - Multiscale Object Oriented Simulation Environment: Element Class Reference
Element Class Reference abstract
#include <Element.h>
Public Member Functions
void addMsg (ObjId mid)
void addMsgAndFunc (ObjId mid, FuncId fid, BindIndex bindIndex)
const Cinfo * cinfo () const
void clearAllMsgs ()
Used upon ending of MOOSE session, to rapidly clear out messages.
void clearBinding (BindIndex b)
virtual Element * copyElement (Id newParent, Id newId, unsigned int n, bool toGlobal) const =0
virtual char * data (unsigned int rawIndex, unsigned int fieldIndex=0) const =0
void digestMessages ()
void dropAllMsgsFromSrc (Id src)
void dropMsg (ObjId mid)
Element (Id id, const Cinfo *c, const string &name)
unsigned int findBinding (MsgFuncBinding b) const
ObjId findCaller (FuncId fid) const
unsigned int getFieldsOfOutgoingMsg (ObjId mid, vector< pair< BindIndex, FuncId > > &ret) const
unsigned int getInputMsgs (vector< ObjId > &caller, FuncId fid) const
unsigned int getInputsWithTgtIndex (vector< pair< Id, unsigned int > > &ret, const DestFinfo *finfo) const
const vector< MsgFuncBinding > * getMsgAndFunc (BindIndex b) const
unsigned int getMsgSourceAndSender (FuncId fid, vector< ObjId > &src, vector< string > &sender) const
unsigned int getMsgTargetAndFunctions (DataId srcDataId, const SrcFinfo *finfo, vector< ObjId > &tgt, vector< string > &func) const
vector< ObjId > getMsgTargets (DataId srcDataId, const SrcFinfo *finfo) const
const string & getName () const
unsigned int getNeighbors (vector< Id > &ret, const Finfo *finfo) const
virtual unsigned int getNode (unsigned int dataIndex) const =0
Returns node number of specified dataIndex.
virtual unsigned int getNumOnNode (unsigned int node) const =0
int getTick () const
virtual bool hasFields () const =0
bool hasMsgs (BindIndex b) const
Id id () const
void innerSetTick (unsigned int tick)
bool isDoomed () const
virtual bool isGlobal () const =0
True if there is a copy of every dataEntry on all nodes.
virtual unsigned int localDataStart () const =0
Returns index of first data entry on this node.
void markAsDoomed ()
void markRewired ()
const vector< MsgDigest > & msgDigest (unsigned int index)
const vector< ObjId > & msgIn () const
virtual unsigned int numData () const =0
Returns number of data entries across all nodes.
virtual unsigned int numField (unsigned int rawIndex) const =0
Returns number of field entries for specified data.
virtual unsigned int numLocalData () const =0
Returns number of local data entries on this node.
void printMsgDigest (unsigned int srcIndex, unsigned int dataIndex) const
void putOffNodeTargetsInDigest (unsigned int srcNum, vector< vector< bool > > &targetNodes)
void putTargetsInDigest (unsigned int srcNum, const MsgFuncBinding &mfb, const FuncOrder &fo, vector< vector< bool > > &targetNodes)
virtual unsigned int rawIndex (unsigned int dataIndex) const =0
void replaceCinfo (const Cinfo *newCinfo)
Support function for zombieSwap, replaces Cinfo.
virtual void resize (unsigned int newNumData)=0
virtual void resizeField (unsigned int rawIndex, unsigned int newNumField)=0
void setName (const string &val)
void setTick (int t)
void showFields () const
void showMsg () const
virtual unsigned int startDataIndex (unsigned int nodeNum) const =0
Returns start dataIndex on specified node.
virtual unsigned int totNumLocalField () const =0
virtual void zombieSwap (const Cinfo *zCinfo)
virtual func, this base version must be called by all derived classes
virtual ~Element ()
Static Public Member Functions
static void destroyElementTree (const vector< Id > &tree)
Private Member Functions
unsigned int getInputs (vector< Id > &ret, const DestFinfo *finfo) const
unsigned int getOutputs (vector< Id > &ret, const SrcFinfo *finfo) const
Private Attributes
const Cinfo * cinfo_
Stores the unique identifier for Element.
Id id_
Name of the Element.
bool isDoomed_
True if the element is marked for destruction.
bool isRewired_
True if messages have been changed and need to digestMessages.
vector< ObjId > m_
vector< vector< MsgFuncBinding > > msgBinding_
vector< vector< MsgDigest > > msgDigest_
string name_
int tick_
Returns tick on which element is scheduled. -1 for disabled.
Detailed Description
Base class for all object lookups. Provides the MOOSE interface so that it handles messaging, class info, and basic fields. Does not do data.
Definition at line 20 of file Element.h.
Constructor & Destructor Documentation
Element()
Element::Element (Id id, const Cinfo * c, const string & name)
This is the main constructor, used by Shell::innerCreate which makes most Elements. Also used to create base Elements to init the simulator in main.cpp. Id is the Id of the new Element Cinfo is the class name is its name numData is the number of data entries, defaults to a singleton. The isGlobal flag specifies whether the created objects should be replicated on all nodes, or partitioned without replication.
Definition at line 17 of file Element.cpp.
    :   name_( name ),
      id_( id ),
      cinfo_( c ),
      msgBinding_( c->numBindIndex() ),
      msgDigest_( c->numBindIndex() ),
      tick_( -1 ),
      isRewired_( false ),
      isDoomed_( false )
{
    id.bindIdToElement( this );
}
References Id::bindIdToElement(), cinfo_, id_, isDoomed_, isRewired_, msgBinding_, msgDigest_, name_, Cinfo::numBindIndex(), and tick_.
Referenced by DataElement::DataElement(), DataElement::DataElement(), FieldElement::FieldElement(), and MsgElement::MsgElement().
~Element()
Element::~Element () virtual
Destructor
Definition at line 31 of file Element.cpp.
{
    // A flag that the Element is doomed, used to avoid lookups
    // when deleting Msgs.
    id_.zeroOut();
    markAsDoomed();
    for ( vector< vector< MsgFuncBinding > >::iterator
            i = msgBinding_.begin(); i != msgBinding_.end(); ++i )
    {
        for ( vector< MsgFuncBinding >::iterator
                j = i->begin(); j != i->end(); ++j )
        {
            // This call internally protects against double deletion.
            Msg::deleteMsg( j->mid );
        }
    }
    for ( vector< ObjId >::iterator i = m_.begin(); i != m_.end(); ++i )
        Msg::deleteMsg( *i );
}
References Msg::deleteMsg(), id_, m_, markAsDoomed(), MsgFuncBinding::mid, msgBinding_, and Id::zeroOut().
Member Function Documentation
addMsg()
void Element::addMsg (ObjId mid)
Pushes the Msg mid onto the list. The position on the list does not matter.
Definition at line 79 of file Element.cpp.
{
    while ( m_.size() > 0 )
    {
        if ( m_.back().bad() )
            m_.pop_back();
        else
            break;
    }
    m_.push_back( m );
    markRewired();
}
References ObjId::bad(), m_, and markRewired().
Referenced by Msg::Msg().
addMsgAndFunc()
void Element::addMsgAndFunc (ObjId mid, FuncId fid, BindIndex bindIndex)
Pushes back the specified Msg and Func pair into the properly indexed place on the msgBinding_ vector.
Definition at line 128 of file Element.cpp.
{
    if ( msgBinding_.size() < bindIndex + 1U )
        msgBinding_.resize( bindIndex + 1 );
    msgBinding_[ bindIndex ].push_back( MsgFuncBinding( mid, fid ) );
    markRewired();
}
References markRewired(), msgBinding_, and MsgFuncBinding::MsgFuncBinding().
Referenced by SrcFinfo::addMsg(), DiagonalMsg::copy(), OneToAllMsg::copy(), OneToOneDataIndexMsg::copy(), OneToOneMsg::copy(), SingleMsg::copy(), SparseMsg::copy(), testMsgField(), and testSendMsg().
cinfo()
const Cinfo * Element::cinfo () const
Gets the class information for this Element
Definition at line 66 of file Element.cpp.
{
    return cinfo_;
}
References cinfo_.
Referenced by ReadCell::addCaConc(), ReadCell::addCanonicalChannel(), addClockMsg(), ReadKkit::addmsg(), ReadCell::addSpikeGen(), addSpine(), Stoich::allocateModelObject(), assignParam(), Dsolve::buildMeshJunctions(), Dsolve::buildNeuroMeshJunctions(), PresynMesh::buildOnDendrites(), PresynMesh::buildOnSpineHeads(), ReadKkit::buildSumTotal(), NeuroNode::buildTree(), Dsolve::calcJunction(), SetGet::checkSet(), convertConcToNumRateUsingMesh(), FieldElement::copyElement(), pymoose::createElementFromPath(), DataElement::DataElement(), DataElement::DataElement(), HSolve::deepSearchForCompartment(), HSolve::deleteIncomingMessages(), ReadCspace::deployParameters(), Neutral::destroy(), Shell::doAddMsg(), doClassSpecificMessaging(), Shell::doLoadModel(), Shell::dropClockMsgs(), pymoose::MooseVec::dtype(), estimateDefaultVol(), Neuron::evalExprForElist(), fillSegIndex(), fillSegments(), VoxelPoolsBase::filterCrossRateTerms(), filterWildcards(), findAllConnectedCompartments(), findFuncMsgSrc(), pymoose::MooseVec::getAttribute(), ChemCompt::getChildConcs(), Neutral::getClass(), getCompt(), getComptParent(), Neutral::getDestFields(), Msg::getDestFieldsOnE1(), Msg::getDestFieldsOnE2(), pymoose::getFieldGeneric(), Spine::getHead(), Spine::getHeadDiameter(), Spine::getHeadLength(), PoolBase::getIsBuffered(), Neutral::getMsgDestFunctions(), Neutral::getMsgDests(), getMsgSourceAndSender(), getMsgTargetAndFunctions(), Neutral::getNeighbors(), Neutral::getOutgoingMsgs(), getParentFromMsg(), Stoich::getProxyPools(), getReactantVols(), Spine::getShaft(), Spine::getShaftDiameter(), Spine::getShaftLength(), getSlaveEnable(), Neutral::getSourceFields(), Msg::getSrcFieldsOnE1(), Msg::getSrcFieldsOnE2(), Neutral::getValueFields(), Shell::innerAddMsg(), innerCopyElements(), Neutral::isA(), isOffSolverReac(), isPartOfDend(), ReadKkit::loadTab(), localGet(), Stoich::locateOffSolverReacs(), ReadCspace::makePlots(), Dsolve::makePoolMapFromElist(), matchInsideBrace(), Eref::msgDigest(), GetEpFunc1< T, L, A >::op(), GetOpFunc1< T, L, A >::op(), ReadCspace::printMol(), putFuncsInOrder(), putOffNodeTargetsInDigest(), ReadCell::read(), DataElement::resize(), pymoose::MooseVec::setAttribute(), pymoose::MooseVec::setAttrOneToAll(), pymoose::MooseVec::setAttrOneToOne(), Neuron::setChannelDistribution(), ChemCompt::setChildConcs(), KsolveBase::setCompartment(), Gsolve::setCompartment(), Dsolve::setCompartment(), Stoich::setCompartment(), Gsolve::setConcInit(), Gsolve::setDsolve(), Ksolve::setDsolve(), Stoich::setDsolve(), pymoose::setFieldGeneric(), Spine::setHeadDiameter(), Spine::setHeadLength(), Spine::setHeadVolume(), PoolBase::setIsBuffered(), Stoich::setKsolve(), Gsolve::setN(), Dsolve::setPath(), HSolve::setSeed(), Spine::setShaftDiameter(), Spine::setShaftLength(), Enz::setSolver(), MMenz::setSolver(), Reac::setSolver(), PoolBase::setSolvers(), Neuron::setSpineAndPsdMesh(), Dsolve::setStoich(), SteadyState::setStoich(), Gsolve::setStoich(), Ksolve::setStoich(), EndoMesh::setSurround(), setTick(), ReadKkit::setupSlaveMsg(), SetGet::strGet(), SetGet::strSet(), HSolveUtils::targets(), tryParent(), Stoich::unZombifyModel(), Stoich::updateRatesAfterRemesh(), ZombieCaConc::vSetSolver(), ZombieCompartment::vSetSolver(), ZombieHHChannel::vSetSolver(), DataElement::zombieSwap(), CaConcBase::zombify(), moose::CompartmentBase::zombify(), HHChannelBase::zombify(), Stoich::zombifyModel(), and DataElement::~DataElement().
clearAllMsgs()
void Element::clearAllMsgs ()
Used upon ending of MOOSE session, to rapidly clear out messages.
Used upon ending of MOOSE session, to rapidly clear out messages, secure in the knowledge that the data structures will be destroyed separately.
Definition at line 150 of file Element.cpp.
{
    markAsDoomed();
    m_.clear();
    msgBinding_.clear();
    msgDigest_.clear();
}
References m_, markAsDoomed(), msgBinding_, and msgDigest_.
Referenced by Id::clearAllElements().
clearBinding()
void Element::clearBinding (BindIndex b)
Clears out all Msgs on specified BindIndex. Used in Shell::set
Definition at line 136 of file Element.cpp.
{
    assert( b < msgBinding_.size() );
    vector< MsgFuncBinding > temp = msgBinding_[ b ];
    msgBinding_[ b ].resize( 0 );
    for( vector< MsgFuncBinding >::iterator i = temp.begin();
            i != temp.end(); ++i )
    {
        Msg::deleteMsg( i->mid );
    }
    markRewired();
}
References Msg::deleteMsg(), markRewired(), MsgFuncBinding::mid, and msgBinding_.
copyElement()
virtual Element * Element::copyElement (Id newParent, Id newId, unsigned int n, bool toGlobal) const pure virtual
Copier
Implemented in FieldElement, GlobalDataElement, LocalDataElement, and MsgElement.
Referenced by innerCopyElements().
data()
virtual char * Element::data (unsigned int rawIndex, unsigned int fieldIndex = 0) const pure virtual
Looks up specified field data entry. On regular objects just returns the data entry specified by the rawIndex. On FieldElements like synapses, does a second lookup on the field index. Note that the index is NOT a DataIndex: it is instead the raw index of the data on the current node. Index is also NOT the character offset, but the index to the data array in whatever type the data may be.
The DataIndex has to be filtered through the nodeMap to find a) if the entry is here, and b) what its raw index is.
Returns 0 if either index is out of range.
Implemented in DataElement, FieldElement, and MsgElement.
Referenced by buildFinfoElement(), Eref::data(), ObjId::data(), FieldElement::data(), DataElement::DataElement(), main(), Cinfo::makeCinfoElements(), FieldElement::numField(), FieldElement::resizeField(), testArith(), testCreateMsg(), testFibonacci(), testGet(), testSendMsg(), testSetGetSynapse(), and testSetGetVec().
destroyElementTree()
void Element::destroyElementTree (const vector< Id > & tree) static
Destroys all Elements in tree, being efficient about not trying to traverse through clearing messages to doomed Elements. Assumes tree includes all child elements. Typically the Neutral::destroy function builds up this tree and then calls this function.
Definition at line 676 of file Element.cpp.
{
    for( vector< Id >::const_iterator i = tree.begin();
            i != tree.end(); i++ )
        i->element()->markAsDoomed(); // Indicate that Element is doomed
    bool killShell = false;
    // Do not destroy the shell till the very end.
    for( vector< Id >::const_iterator i = tree.begin();
            i != tree.end(); i++ )
    {
        if ( *i == Id() )
            killShell = true;
        else
            i->destroy();
    }
    if ( killShell )
        Id().destroy();
}
References Id::destroy(), Id::element(), Id::Id(), markAsDoomed(), and Id::operator==().
Referenced by Neutral::destroy().
digestMessages()
void Element::digestMessages ()
Rebuild digested message array; traverse all messages to do so
Definition at line 569 of file Element.cpp.
{
    bool report = 0; // for debugging
    msgDigest_.clear();
    msgDigest_.resize( msgBinding_.size() * numData() );
    vector< bool > temp( Shell::numNodes(), false );
    vector< vector< bool > > targetNodes( numData(), temp );
    // targetNodes[srcDataId][node]. The idea is that if any dataEntry has
    // a target off-node, it should flag the entry here so that it can
    // send the message request to the proxy on that node.
    for ( unsigned int i = 0; i < msgBinding_.size(); ++i )
    {
        // Go through and identify functions with the same ptr.
        vector< FuncOrder > fo = putFuncsInOrder( this, msgBinding_[i] );
        for ( vector< FuncOrder >::const_iterator
                k = fo.begin(); k != fo.end(); ++k )
        {
            const MsgFuncBinding& mfb = msgBinding_[i][ k->index() ];
            putTargetsInDigest( i, mfb, *k, targetNodes );
        }
        if ( Shell::numNodes() > 1 )
        {
            if ( report )
            {
                unsigned int numPre = findNumDigest( msgDigest_,
                                                     msgBinding_.size(), numData(), i );
                putOffNodeTargetsInDigest( i, targetNodes );
                unsigned int numPost = findNumDigest( msgDigest_,
                                                      msgBinding_.size(), numData(), i );
                cout << "\nfor Element " << name_;
                cout << ", Func: " << i << ", numFunc = " << fo.size() <<
                     ", numPre= " << numPre <<
                     ", numPost= " << numPost << endl;
                for ( unsigned int j = 0; j < numData(); ++j )
                {
                    cout << endl << j << "  ";
                    for ( unsigned int node = 0; node < Shell::numNodes(); ++node)
                    {
                        cout << (int)targetNodes[j][node];
                    }
                }
                cout << endl;
            }
            else
            {
                putOffNodeTargetsInDigest( i, targetNodes );
            }
        }
    }
}
References findNumDigest(), FuncOrder::index(), msgBinding_, msgDigest_, name_, numData(), Shell::numNodes(), putFuncsInOrder(), putOffNodeTargetsInDigest(), and putTargetsInDigest().
Referenced by msgDigest().
dropAllMsgsFromSrc()
void Element::dropAllMsgsFromSrc (Id src)
Drop all messages arriving from src onto current Element, regardless of which field they come from.
Definition at line 197 of file Element.cpp.
{
    static Id clockId( 1 );
    const Element* clock = clockId.element();
    vector< ObjId > msgs;
    for ( vector< ObjId >::const_iterator i = m_.begin();
            i != m_.end(); ++i )
    {
        const Msg* m = Msg::getMsg( *i );
        const Element* src;
        if ( m->e1() == this )
        {
            src = m->e2();
        }
        else
        {
            src = m->e1();
        }
        if ( src == clock )
        {
            msgs.push_back( *i );
        }
    }
    sort( msgs.begin(), msgs.end() );
    // C++ detritus.
    msgs.erase( unique( msgs.begin(), msgs.end() ), msgs.end() );
    for( vector< ObjId >::iterator
            i = msgs.begin(); i != msgs.end(); ++i )
        Msg::deleteMsg( *i );
}
References Msg::deleteMsg(), Msg::e1(), Msg::e2(), Id::element(), Msg::getMsg(), Id::Id(), and m_.
Referenced by setTick().
dropMsg()
void Element::dropMsg (ObjId mid)
Removes the specified msg from the list.
Called from ~Msg. This requires the usual scan through all msgs, and could get inefficient.
Definition at line 113 of file Element.cpp.
{
    if ( isDoomed() ) // This is a flag that the Element is doomed.
        return;
    // Here we have the spectacularly ugly C++ erase-remove idiot.
    m_.erase( remove( m_.begin(), m_.end(), mid ), m_.end() );
    for ( vector< vector< MsgFuncBinding > >::iterator i = msgBinding_.begin(); i != msgBinding_.end(); ++i )
    {
        matchMid match( mid );
        i->erase( remove_if( i->begin(), i->end(), match ), i->end() );
    }
    markRewired();
}
References isDoomed(), m_, markRewired(), matchMid::matchMid(), and msgBinding_.
Referenced by Msg::~Msg().
findBinding()
unsigned int Element::findBinding (MsgFuncBinding b) const
Returns the binding index of the specified entry. Returns ~0 on failure.
Definition at line 374 of file Element.cpp.
{
    for ( unsigned int i = 0; i < msgBinding_.size(); ++i )
    {
        const vector< MsgFuncBinding >& mb = msgBinding_[i];
        vector< MsgFuncBinding>::const_iterator bi =
            find( mb.begin(), mb.end(), b );
        if ( bi != mb.end() )
            return i;
    }
    return ~0;
}
References msgBinding_.
Referenced by findCaller(), getInputMsgs(), and getMsgSourceAndSender().
findCaller()
ObjId Element::findCaller (FuncId fid) const
Returns the first Msg that calls the specified Fid, on current Element. Returns 0 on failure.
Definition at line 350 of file Element.cpp.
{
    for ( vector< ObjId >::const_iterator i = m_.begin();
            i != m_.end(); ++i )
    {
        const Msg* m = Msg::getMsg( *i );
        const Element* src;
        if ( m->e1() == this )
        {
            src = m->e2();
        }
        else
        {
            src = m->e1();
        }
        unsigned int ret = src->findBinding( MsgFuncBinding( *i, fid ) );
        if ( ret != ~0U )
        {
            return *i;
        }
    }
    return ObjId( 0, BADINDEX );
}
References BADINDEX, Msg::e1(), Msg::e2(), findBinding(), Msg::getMsg(), m_, MsgFuncBinding::MsgFuncBinding(), and ObjId::ObjId().
Referenced by HSolve::deleteIncomingMessages(), Shell::innerMove(), Neutral::isDescendant(), Neutral::parent(), Neutral::path(), HSolveActive::readSynapses(), and testAssortedMsg().
getFieldsOfOutgoingMsg()
unsigned int Element::getFieldsOfOutgoingMsg (ObjId mid, vector< pair< BindIndex, FuncId > > & ret) const
Fills in vector, each entry of which identifies the src and dest fields respectively. Src field is local and identified by BindIndex Dest field is a FuncId on the remote Element.
Definition at line 1009 of file Element.cpp.
{
    ret.resize( 0 );
    for ( unsigned int i = 0; i < msgBinding_.size(); ++i )
    {
        const vector< MsgFuncBinding >& mb = msgBinding_[i];
        for ( vector< MsgFuncBinding >::const_iterator j = mb.begin();
                j != mb.end(); ++j )
        {
            if ( j->mid == mid )
            {
                ret.push_back( pair< BindIndex, FuncId >( i, j->fid ));
            }
        }
    }
    return ret.size();
}
References MsgFuncBinding::fid, MsgFuncBinding::mid, msgBinding_, and ObjId::operator==().
Referenced by Msg::getDestFieldsOnE1(), Msg::getDestFieldsOnE2(), Msg::getSrcFieldsOnE1(), Msg::getSrcFieldsOnE2(), and testMsgSrcDestFields().
getInputMsgs()
unsigned int Element::getInputMsgs (vector< ObjId > & caller, FuncId fid) const
More general function. Fills up vector of ObjIds that call the specified Fid on current Element. Returns # found
Definition at line 984 of file Element.cpp.
{
    for ( vector< ObjId >::const_iterator i = m_.begin();
            i != m_.end(); ++i )
    {
        const Msg* m = Msg::getMsg( *i );
        const Element* src;
        if ( m->e1() == this )
        {
            src = m->e2();
        }
        else
        {
            src = m->e1();
        }
        unsigned int ret = src->findBinding( MsgFuncBinding( *i, fid ) );
        if ( ret != ~0U )
        {
            caller.push_back( *i );
        }
    }
    return caller.size();
}
References Msg::e1(), Msg::e2(), findBinding(), Msg::getMsg(), m_, and MsgFuncBinding::MsgFuncBinding().
Referenced by Shell::dropClockMsgs(), getInputs(), getInputsWithTgtIndex(), and insertSharedMsgs().
getInputs()
unsigned int Element::getInputs (vector< Id > & ret, const DestFinfo * finfo) const private
Fills in vector of Ids sending messeges to this DestFinfo on this Element. Returns # found
Definition at line 887 of file Element.cpp.
{
    assert( finfo ); // would like to check that finfo is on src.
    unsigned int oldSize = ret.size();
    FuncId fid = finfo->getFid();
    vector< ObjId > caller;
    getInputMsgs( caller, fid );
    for ( vector< ObjId >::iterator i = caller.begin();
            i != caller.end(); ++i  )
    {
        const Msg* m = Msg::getMsg( *i );
        assert( m );
        Id id = m->e1()->id();
        if ( m->e1() == this )
            id = m->e2()->id();
        ret.push_back( id );
    }
    return ret.size() - oldSize;
}
References Msg::e1(), Msg::e2(), DestFinfo::getFid(), getInputMsgs(), Msg::getMsg(), and id().
Referenced by getNeighbors().
getInputsWithTgtIndex()
unsigned int Element::getInputsWithTgtIndex (vector< pair< Id, unsigned int > > & ret, const DestFinfo * finfo) const
Returns vectors of sources of messages to a field or data element. To go with each entry, also return the field or data index of target.
Returns vectors of sources of messages to a field or data element. To go with each entry, also return the field or data index of target. Needed to track which inputs go to with field index of current element. So if A-->x0, B-->x1, and C-->x2, it will return A, B, C, no matter in which order the messages were created. If there are multiple messages to x0, it will return the first.
Definition at line 918 of file Element.cpp.
{
    assert( finfo ); // would like to check that finfo is on src.
    ret.clear();
    FuncId fid = finfo->getFid();
    vector< ObjId > caller;
    getInputMsgs( caller, fid );
    for ( vector< ObjId >::iterator i = caller.begin();
            i != caller.end(); ++i  )
    {
        const Msg* m = Msg::getMsg( *i );
        assert( m );
        if ( m->e1() == this )
        {
            Eref tgt = m->firstTgt( Eref( m->e2(), 0 ) );
            unsigned int idx = this->hasFields() ? tgt.fieldIndex(): tgt.dataIndex();
            ret.push_back( pair< Id, unsigned int >( m->e2()->id(), idx ) );
        }
        else if ( m->e2() == this )
        {
            Eref tgt = m->firstTgt( Eref( m->e1(), 0 ) );
            unsigned int idx = this->hasFields() ? tgt.fieldIndex(): tgt.dataIndex();
            ret.push_back( pair< Id, unsigned int >( m->e1()->id(), idx ) );
        }
    }
    return ret.size();
}
References Eref::dataIndex(), Msg::e1(), Msg::e2(), Eref::Eref(), Eref::fieldIndex(), Msg::firstTgt(), DestFinfo::getFid(), getInputMsgs(), Msg::getMsg(), hasFields(), and id().
Referenced by Stoich::installAndUnschedFunc(), and Stoich::installAndUnschedFuncRate().
getMsgAndFunc()
const vector< MsgFuncBinding > * Element::getMsgAndFunc (BindIndex b) const
gets the Msg/Func binding information for specified bindIndex. This is a vector. Returns 0 on failure.
Definition at line 300 of file Element.cpp.
{
    if ( b < msgBinding_.size() )
        return &( msgBinding_[ b ] );
    return 0;
}
References msgBinding_.
Referenced by Neutral::child(), Neutral::children(), convertConcToNumRateUsingVol(), getMsgTargetAndFunctions(), EnzBase::getNumPrd(), Reac::getNumPrd(), EnzBase::getNumSub(), Reac::getNumSub(), Neutral::getOutgoingMsgs(), getOutputs(), getReactantVols(), and innerCopyMsgs().
getMsgSourceAndSender()
unsigned int Element::getMsgSourceAndSender (FuncId fid, vector< ObjId > & src, vector< string > & sender) const
Fills in matching vectors of destination ObjIds and the destination function, for the specified source Finfo and dataId on this Element. Used in Neutral::msgDests and Neutral::msgDestFunctions. Returns number of dests found.
Definition at line 828 of file Element.cpp.
{
    for ( vector< ObjId >::const_iterator i = m_.begin();
            i != m_.end(); ++i )
    {
        const Msg* m = Msg::getMsg( *i );
        const Element* src;
        if ( m->e1() == this )
        {
            src = m->e2();
        }
        else
        {
            src = m->e1();
        }
        unsigned int ret = src->findBinding( MsgFuncBinding( *i, fid ) );
        if ( ret != ~0U )
        {
            // problem here, to get dataId
            srcObj.push_back( ObjId( src->id(), 0 ) );
            sender.push_back( src->cinfo()->srcFinfoName( ret ) );
        }
    }
    return srcObj.size();
}
References cinfo(), Msg::e1(), Msg::e2(), findBinding(), Msg::getMsg(), id(), m_, MsgFuncBinding::MsgFuncBinding(), ObjId::ObjId(), and Cinfo::srcFinfoName().
Referenced by testMsgSrcDestFields().
getMsgTargetAndFunctions()
unsigned int Element::getMsgTargetAndFunctions (DataId srcDataId, const SrcFinfo * finfo, vector< ObjId > & tgt, vector< string > & func) const
Fills in matching vectors of destination ObjIds and the destination function, for the specified source Finfo and dataId on this Element. Used in Neutral::msgDests and Neutral::msgDestFunctions. Returns number of dests found.
Definition at line 772 of file Element.cpp.
{
    assert( finfo ); // would like to check that finfo is on this.
    assert( srcDataId < this->numData() );
    tgt.resize( 0 );
    func.resize( 0 );
    const vector< MsgFuncBinding >* msgVec =
        getMsgAndFunc( finfo->getBindIndex() );
    for ( unsigned int i = 0; i < msgVec->size(); ++i )
    {
        const Msg* m = Msg::getMsg( (*msgVec)[i].mid );
        assert( m );
        FuncId fid = (*msgVec)[i].fid;
        if ( m->e1() == this )   // regular direction message.
        {
            string name = m->e2()->cinfo()->destFinfoName( fid );
            vector< vector< Eref > > t;
            m->targets( t );
            assert( t.size() == this->numData() );
            vector< Eref >& row = t[srcDataId];
            for ( vector< Eref >::const_iterator
                    e = row.begin(); e != row.end(); ++e )
            {
                tgt.push_back( e->objId() );
                func.push_back( name );
            }
        }
        else if ( m->e2() == this )
        {
            string name = m->e1()->cinfo()->destFinfoName( fid );
            vector< vector< Eref > > t;
            m->sources( t );
            assert( t.size() == this->numData() );
            vector< Eref >& row = t[srcDataId];
            for ( vector< Eref >::const_iterator
                    e = row.begin(); e != row.end(); ++e )
            {
                tgt.push_back( e->objId() );
                func.push_back( name );
            }
        }
        else
        {
            assert( 0 );
        }
    }
    return tgt.size();
}
References cinfo(), Cinfo::destFinfoName(), Msg::e1(), Msg::e2(), MsgFuncBinding::fid, SrcFinfo::getBindIndex(), Msg::getMsg(), getMsgAndFunc(), MsgFuncBinding::mid, numData(), Eref::objId(), Msg::sources(), and Msg::targets().
Referenced by Stoich::allocateModelObject(), Neutral::getMsgDestFunctions(), Neutral::getMsgDests(), and testMsgSrcDestFields().
getMsgTargets()
vector< ObjId > Element::getMsgTargets (DataId srcDataId, const SrcFinfo * finfo) const
Enumerates msg targets. Will get confused if some are across nodes.
Definition at line 856 of file Element.cpp.
{
    assert( finfo ); // would like to check that finfo is on this.
    assert( srcDataId < this->numData() );
    vector< ObjId > ret;
    Eref er( const_cast< Element* >( this ), srcDataId );
    const vector< MsgDigest >&md = er.msgDigest( finfo->getBindIndex() );
    for ( vector< MsgDigest >::const_iterator
            i = md.begin(); i != md.end(); ++i )
    {
        for ( vector< Eref >::const_iterator
                j = i->targets.begin(); j != i->targets.end(); ++j )
        {
            if ( j->dataIndex() == ALLDATA )
            {
                for ( unsigned int k = 0;
                        k < j->element()->numData(); ++k )
                    ret.push_back( ObjId( j->id(), k ) );
            }
            else
            {
                ret.push_back( j->objId() );
            }
        }
    }
    return ret;
}
References ALLDATA, Eref::dataIndex(), Eref::element(), Eref::Eref(), SrcFinfo::getBindIndex(), Eref::id(), Eref::msgDigest(), numData(), Eref::objId(), ObjId::ObjId(), and MsgDigest::targets.
Referenced by Adaptor::reinit(), and ChemCompt::setEntireVolume().
getName()
const string & Element::getName () const
Returns name of Element
Definition at line 56 of file Element.cpp.
{
    return name_;
}
References name_.
Referenced by ReadCell::addChannel(), ReadCell::addChannelMessage(), SharedFinfo::addMsg(), addSpine(), Shell::adopt(), ReadSwc::build(), ReadCell::buildChannels(), buildFromProto(), checkChildren(), checkForSpine(), Neutral::child(), ReadKkit::convertKineticsToGroup(), pymoose::copy(), FieldElement::copyElement(), DataElement::DataElement(), Shell::doAddMsg(), doClassSpecificMessaging(), Shell::doMove(), ReadKkit::dumpPlots(), estimateDefaultVol(), fillSegIndex(), NeuroMesh::filterSpines(), NeuroNode::filterSpines(), ReadKkit::findCompartmentsFromAnnotation(), findModelParent(), NeuroNode::findStartNode(), Msg::getDestFieldsOnE1(), Msg::getDestFieldsOnE2(), Neutral::getName(), Msg::getSrcFieldsOnE1(), Msg::getSrcFieldsOnE2(), hasScaleFormula(), Shell::innerAddMsg(), Shell::innerMove(), isPartOfDend(), ReadCspace::makePlots(), Dsolve::mapDiffPoolsBetweenDsolves(), Dsolve::mapXfersBetweenDsolves(), matchBeforeBrace(), matchName(), pymoose::MooseVec::name(), operator<<(), Neutral::path(), FieldElementFinfoBase::postCreationFunc(), ReadCspace::printEnz(), ReadCspace::printMol(), ReadCspace::printReac(), Arith::process(), NeuroMesh::putSomaAtStart(), ReadCell::ReadCell(), showMsg(), SetGet::strGet(), SetGet::strSet(), testCopy(), testCopyFieldElement(), testMsgElementListing(), testMsgField(), testStrSet(), testSyncSynapseSize(), HHChannel::vReinit(), HHChannel2D::vReinit(), HHChannelF::vReinit(), HHChannelF2D::vReinit(), wildcardTestFunc(), and FieldElement::zombieSwap().
getNeighbors()
unsigned int Element::getNeighbors (vector< Id > & ret, const Finfo * finfo) const
Fills in vector of Ids connected to this Finfo on this Element. Returns # found
Definition at line 949 of file Element.cpp.
{
    ret.resize( 0 );
    if ( !finfo )
        return 0;
    const SrcFinfo* srcF = dynamic_cast< const SrcFinfo* >( finfo );
    const DestFinfo* destF = dynamic_cast< const DestFinfo* >( finfo );
    const SharedFinfo* sharedF = dynamic_cast< const SharedFinfo* >( finfo );
    assert( srcF || destF || sharedF );
    if ( srcF )
        return getOutputs( ret, srcF );
    else if ( destF )
        return getInputs( ret, destF );
    else if ( ! sharedF->src().empty() )
        return getOutputs( ret, sharedF->src().front() );
    else if ( ! sharedF->dest().empty() )
    {
        Finfo* subFinfo = sharedF->dest().front();
        const DestFinfo* subDestFinfo =
            dynamic_cast< const DestFinfo* >( subFinfo );
        assert( subDestFinfo );
        return getInputs( ret, subDestFinfo );
    }
    else
    {
        assert( 0 );
    }
    return 0;
}
References SharedFinfo::dest(), getInputs(), getOutputs(), and SharedFinfo::src().
Referenced by ReadKkit::addmsg(), ReadCell::buildCompartment(), Dsolve::fillConcChans(), findAllConnectedCompartments(), findFuncMsgSrc(), findMeshOfEnz(), findParentComptOfReac(), getComptParent(), Neutral::getNeighbors(), getSlaveEnable(), Stoich::installAndUnschedFuncReac(), isOffSolverReac(), moose::VClamp::reinit(), Enz::setSolver(), MMenz::setSolver(), Reac::setSolver(), HSolveUtils::targets(), testShellAddMsg(), testTwoReacGetNeighbors(), and tryParent().
getNode()
virtual unsigned int Element::getNode (unsigned int dataIndex) const pure virtual
Returns node number of specified dataIndex.
Implemented in FieldElement, LocalDataElement, GlobalDataElement, and MsgElement.
Referenced by HopFunc1< A >::dataOpVec(), Eref::getNode(), FieldElement::getNode(), Eref::isDataHere(), ObjId::isDataHere(), and ObjId::isOffNode().
getNumOnNode()
virtual unsigned int Element::getNumOnNode (unsigned int node) const pure virtual
Returns number of data (or, if relevant, field) entries on specified node.
Implemented in FieldElement, GlobalDataElement, LocalDataElement, and MsgElement.
Referenced by HopFunc1< A >::dataOpVec(), and HopFunc2< A1, A2 >::opVec().
getOutputs()
unsigned int Element::getOutputs (vector< Id > & ret, const SrcFinfo * finfo) const private
Fills in vector of Ids receiving messages from this SrcFinfo. Returns # found
Definition at line 749 of file Element.cpp.
{
    assert( finfo ); // would like to check that finfo is on this.
    unsigned int oldSize = ret.size();
    const vector< MsgFuncBinding >* msgVec =
        getMsgAndFunc( finfo->getBindIndex() );
    if ( !msgVec )
        return 0;
    for ( unsigned int i = 0; i < msgVec->size(); ++i )
    {
        const Msg* m = Msg::getMsg( (*msgVec)[i].mid );
        assert( m );
        Id id = m->e2()->id();
        if ( m->e2() == this )
            id = m->e1()->id();
        ret.push_back( id );
    }
    return ret.size() - oldSize;
}
References Msg::e1(), Msg::e2(), SrcFinfo::getBindIndex(), Msg::getMsg(), getMsgAndFunc(), id(), and MsgFuncBinding::mid.
Referenced by getNeighbors().
getTick()
int Element::getTick () const
Returns Clock tick used by object. -1 means none. -2 means none for now because I am a zombie, but if I should be unzombified please put me back on my default clock tick.
Definition at line 186 of file Element.cpp.
{
    return tick_;
}
References tick_.
Referenced by SocketStreamer::addTable(), Streamer::addTable(), Neutral::getDt(), Neutral::getTick(), SocketStreamer::reinit(), Streamer::reinit(), Table::reinit(), and Stoich::unZombifyModel().
hasFields()
virtual bool Element::hasFields () const pure virtual
True if this is a FieldElement having an array of fields on each data entry. Clearly not true for the base Element.
Implemented in DataElement, FieldElement, and MsgElement.
Referenced by allChildren(), Neutral::child(), Shell::doFind(), OneToOneMsg::firstTgt(), getInputsWithTgtIndex(), pymoose::MooseVec::getItem(), innerGetVec(), GetHopFunc< A >::opGetVec(), HopFunc1< A >::opVec(), OpFunc1Base< A >::opVecBuffer(), Neutral::path(), singleLevelWildcard(), pymoose::MooseVec::size(), OneToOneMsg::sources(), and OneToOneMsg::targets().
hasMsgs()
bool Element::hasMsgs (BindIndex b) const
Returns true if there are one or more Msgs on the specified BindIndex
Definition at line 307 of file Element.cpp.
{
    return ( b < msgBinding_.size() && msgBinding_[b].size() > 0 );
}
References msgBinding_.
Referenced by Clock::buildTicks(), and NeuroMesh::transmitSpineInfo().
id()
Id Element::id () const
Returns the Id on this Elm
Definition at line 71 of file Element.cpp.
{
    return id_;
}
References id_.
Referenced by SharedFinfo::addMsg(), Stoich::allocateModelObject(), Neutral::buildTree(), Neutral::child(), HSolve::deleteIncomingMessages(), DiagonalMsg::findOtherEnd(), OneToAllMsg::findOtherEnd(), OneToOneDataIndexMsg::findOtherEnd(), OneToOneMsg::findOtherEnd(), SingleMsg::findOtherEnd(), SparseMsg::findOtherEnd(), Msg::getE1(), Msg::getE2(), getInputs(), getInputsWithTgtIndex(), getMsgSourceAndSender(), getOutputs(), Eref::id(), innerCopyElements(), innerCopyMsgs(), Neutral::isDescendant(), Eref::objId(), printGrid(), setTick(), showFields(), and Stoich::zombifyModel().
innerSetTick()
void Element::innerSetTick (unsigned int tick)
Direct assignment of tick field, without doing any of the message manipulation
Definition at line 191 of file Element.cpp.
{
    if ( tick < 32 )
        tick_ = tick;
}
References tick_.
Referenced by Shell::addClockMsgs(), and Shell::innerUseClock().
isDoomed()
bool Element::isDoomed () const
Definition at line 701 of file Element.cpp.
{
    return isDoomed_;
}
References isDoomed_.
Referenced by dropMsg(), and Stoich::unZombifyPools().
isGlobal()
virtual bool Element::isGlobal () const pure virtual
True if there is a copy of every dataEntry on all nodes.
Implemented in FieldElement, GlobalDataElement, LocalDataElement, and MsgElement.
Referenced by HopFunc1< A >::dataOpVec(), PostMaster::dispatchSetBuf(), filterOffNodeTargets(), FieldElement::getNumOnNode(), FieldElement::isGlobal(), ObjId::isGlobal(), ObjId::isOffNode(), GetHopFunc< A >::opGetVec(), HopFunc2< A1, A2 >::opVec(), HopFunc1< A >::opVec(), putTargetsInDigest(), and testCopyFieldElement().
localDataStart()
virtual unsigned int Element::localDataStart () const pure virtual
Returns index of first data entry on this node.
Implemented in FieldElement, GlobalDataElement, LocalDataElement, and MsgElement.
Referenced by GetHopFunc< A >::getLocalFieldVec(), GetHopFunc< A >::getLocalVec(), innerGetVec(), FieldElement::localDataStart(), HopFunc1< A >::localFieldOpVec(), HopFunc1< A >::localOpVec(), OpFunc1Base< A >::opVecBuffer(), OpFunc2Base< A1, A2 >::opVecBuffer(), putTargetsInDigest(), SparseMsg::randomConnect(), SrcFinfo0::send(), SrcFinfo2< T1, T2 >::send(), SrcFinfo3< T1, T2, T3 >::send(), SrcFinfo4< T1, T2, T3, T4 >::send(), SrcFinfo5< T1, T2, T3, T4, T5 >::send(), SrcFinfo6< T1, T2, T3, T4, T5, T6 >::send(), SrcFinfo1< T >::send(), SrcFinfo2< T1, T2 >::sendTo(), SrcFinfo1< T >::sendTo(), SrcFinfo1< T >::sendVec(), OneToOneMsg::sources(), OneToOneMsg::targets(), SparseMsg::updateAfterFill(), CaConcBase::zombify(), moose::CompartmentBase::zombify(), and HHChannelBase::zombify().
markAsDoomed()
void Element::markAsDoomed ()
Set flag to state that Element is due for destruction. Useful to avoid following messages that will soon be gone.
Definition at line 696 of file Element.cpp.
{
    isDoomed_ = true;
}
References isDoomed_.
Referenced by clearAllMsgs(), destroyElementTree(), and ~Element().
markRewired()
void Element::markRewired ()
Set flag to state that the messages on this Element have changed, and need to be re-digested.
Definition at line 706 of file Element.cpp.
{
    isRewired_ = true;
}
References isRewired_.
Referenced by addMsg(), addMsgAndFunc(), clearBinding(), dropMsg(), SparseMsg::randomConnect(), SingleMsg::setI1(), OneToAllMsg::setI1(), SingleMsg::setI2(), DiagonalMsg::setStride(), SingleMsg::setTargetField(), SparseMsg::transpose(), and SparseMsg::updateAfterFill().
msgDigest()
const vector< MsgDigest > & Element::msgDigest (unsigned int index)
Raw lookup into MsgDigest vector. One for each MsgSrc X ObjEntry. If the messages have been rewired, this call triggers the re-parsing of all messages before returning the digested msgs.
Definition at line 289 of file Element.cpp.
{
    if ( isRewired_ )
    {
        digestMessages();
        isRewired_ = false;
    }
    assert( index < msgDigest_.size() );
    return msgDigest_[ index ];
}
References digestMessages(), isRewired_, and msgDigest_.
Referenced by Eref::msgDigest(), and testSendMsg().
msgIn()
const vector< ObjId > & Element::msgIn () const
Returns all incoming Msgs.
Definition at line 387 of file Element.cpp.
{
    return m_;
}
References m_.
Referenced by Neutral::getIncomingMsgs().
numData()
virtual unsigned int Element::numData () const pure virtual
Returns number of data entries across all nodes.
Implemented in FieldElement, GlobalDataElement, LocalDataElement, and MsgElement.
Referenced by allChildren(), ObjId::bad(), SetGet::checkSet(), DataElement::DataElement(), HopFunc1< A >::dataOpVec(), digestMessages(), Shell::doFind(), fillErefsFromMatrix(), DiagonalMsg::findOtherEnd(), pymoose::VecLookupField::get(), getMsgTargetAndFunctions(), getMsgTargets(), Neutral::getNumData(), innerCopyElements(), FieldElement::numData(), GetHopFunc< A >::opGetVec(), SparseMsg::pairFill(), printGrid(), printMsgDigest(), putOffNodeTargetsInDigest(), SparseMsg::randomConnect(), SrcFinfo0::send(), SrcFinfo2< T1, T2 >::send(), SrcFinfo3< T1, T2, T3 >::send(), SrcFinfo4< T1, T2, T3, T4 >::send(), SrcFinfo5< T1, T2, T3, T4, T5 >::send(), SrcFinfo6< T1, T2, T3, T4, T5, T6 >::send(), SrcFinfo2< T1, T2 >::sendTo(), pymoose::VecLookupField::set(), singleLevelWildcard(), pymoose::MooseVec::size(), DiagonalMsg::sources(), OneToAllMsg::sources(), OneToOneDataIndexMsg::sources(), OneToOneMsg::sources(), SingleMsg::sources(), SparseMsg::SparseMsg(), DiagonalMsg::targets(), OneToAllMsg::targets(), OneToOneDataIndexMsg::targets(), OneToOneMsg::targets(), SingleMsg::targets(), testCellDiffn(), testCopyFieldElement(), testCylDiffnWithStoich(), testSetGetSynapse(), testSmallCellDiffn(), testSyncSynapseSize(), testTaperingCylDiffn(), and pymoose::VecElementField::VecElementField().
numField()
virtual unsigned int Element::numField (unsigned int rawIndex) const pure virtual
Returns number of field entries for specified data.
Implemented in DataElement, FieldElement, and MsgElement.
Referenced by allChildren(), GetHopFunc< A >::getLocalFieldVec(), Neutral::getNumField(), innerGetVec(), HopFunc1< A >::localFieldOpVec(), HopFunc1< A >::localOpVec(), HopFunc2< A1, A2 >::opVec(), OpFunc1Base< A >::opVecBuffer(), OpFunc2Base< A1, A2 >::opVecBuffer(), singleLevelWildcard(), OneToOneMsg::sources(), OneToOneMsg::targets(), testCopyFieldElement(), testSetGetSynapse(), and testSyncSynapseSize().
numLocalData()
virtual unsigned int Element::numLocalData () const pure virtual
Returns number of local data entries on this node.
Implemented in DataElement, FieldElement, and MsgElement.
Referenced by GetHopFunc< A >::getLocalVec(), innerGetVec(), HopFunc1< A >::localOpVec(), FieldElement::numLocalData(), HopFunc2< A1, A2 >::opVec(), OpFunc1Base< A >::opVecBuffer(), OpFunc2Base< A1, A2 >::opVecBuffer(), putTargetsInDigest(), SparseMsg::randomConnect(), SrcFinfo1< T >::send(), SrcFinfo1< T >::sendTo(), SrcFinfo1< T >::sendVec(), OneToOneMsg::targets(), SparseMsg::updateAfterFill(), CaConcBase::zombify(), moose::CompartmentBase::zombify(), and HHChannelBase::zombify().
printMsgDigest()
void Element::printMsgDigest (unsigned int srcIndex, unsigned int dataIndex) const
Utility function for debugging
Definition at line 711 of file Element.cpp.
{
    unsigned int numSrcMsgs = msgBinding_.size();
    unsigned int start = 0;
    unsigned int end = numData();
    if ( dataId < numData() )
    {
        start = dataId;
        end = dataId + 1;
    }
    for (unsigned int i = start; i < end; ++i )
    {
        cout << i << ": ";
        const vector< MsgDigest> & md =
            msgDigest_[numSrcMsgs * i + srcIndex];
        for ( unsigned int j = 0; j < md.size(); ++j )
        {
            cout << j << ": ";
            for ( unsigned int k = 0; k < md[j].targets.size(); ++k )
            {
                cout << "   " <<
                     md[j].targets[k].dataIndex() << "," <<
                     md[j].targets[k].fieldIndex();
            }
        }
        cout << endl;
    }
}
References Eref::dataIndex(), Eref::fieldIndex(), msgBinding_, msgDigest_, numData(), and MsgDigest::targets.
putOffNodeTargetsInDigest()
void Element::putOffNodeTargetsInDigest (unsigned int srcNum, vector< vector< bool > > & targetNodes)
Inner function that adds off-node targets to the MsgDigest
Definition at line 517 of file Element.cpp.
{
    if ( msgBinding_[ srcNum ].size() == 0 )
        return;
    const MsgFuncBinding& mfb = msgBinding_[ srcNum ][0];
    const Msg* msg = Msg::getMsg( mfb.mid );
    const OpFunc* func;
    if ( msg->e1() == this )
    {
        func = msg->e2()->cinfo()->getOpFunc( mfb.fid );
    }
    else
    {
        func = msg->e1()->cinfo()->getOpFunc( mfb.fid );
    }
    assert( func );
    // How do I eventually destroy these?
    const OpFunc* hop = func->makeHopFunc( srcNum );
    for ( unsigned int i = 0; i < numData(); ++i )
    {
        vector< Eref > tgts;
        for ( unsigned int j = 0; j < Shell::numNodes(); ++j )
        {
            if ( targetNodes[i][j] )
                tgts.push_back( Eref( this, i, j ) );
            // This is a hack. I encode the target node # in the FieldIndex
            // and the originating Eref in the remainder of the Eref.
            // The HopFunc has to extract both these things to push into
            // the correct SendBuffer.
        }
        if ( tgts.size() > 0 )
        {
            vector< MsgDigest >& md =
                msgDigest_[ msgBinding_.size() * i + srcNum ];
            md.push_back( MsgDigest( hop, tgts ) );
        }
    }
}
References cinfo(), Msg::e1(), Msg::e2(), Eref::Eref(), MsgFuncBinding::fid, Msg::getMsg(), Cinfo::getOpFunc(), OpFunc::makeHopFunc(), MsgFuncBinding::mid, msgBinding_, MsgDigest::MsgDigest(), msgDigest_, numData(), and Shell::numNodes().
Referenced by digestMessages().
putTargetsInDigest()
void Element::putTargetsInDigest (unsigned int srcNum, const MsgFuncBinding & mfb, const FuncOrder & fo, vector< vector< bool > > & targetNodes)
Inner function that adds targets to a single function in the MsgDigest
Definition at line 466 of file Element.cpp.
{
    const Msg* msg = Msg::getMsg( mfb.mid );
    vector< vector < Eref > > erefs;
    if ( msg->e1() == this )
        msg->targets( erefs );
    else if ( msg->e2() == this )
        msg->sources( erefs );
    else
        assert( 0 );
    if ( Shell::numNodes() > 1 )
        filterOffNodeTargets(
            localDataStart(),
            localDataStart() + numLocalData(),
            isGlobal(), Shell::myNode(),
            erefs, targetNodes );
    for ( unsigned int j = 0; j < erefs.size(); ++j )
    {
        vector< MsgDigest >& md =
            msgDigest_[ msgBinding_.size() * j + srcNum ];
        // k->func(); erefs[ j ];
        if ( md.size() == 0 || md.back().func != fo.func() )
        {
            md.push_back( MsgDigest( fo.func(), erefs[j] ) );
            /*
            if ( md.back().targets.size() > 0 )
                cout << "putTargetsInDigest: " << md.back().targets[0] <<
                    ", eref = " << erefs[j][0] << endl;
            else
                cout << "putTargetsInDigest: empty\n";
            */
        }
        else
        {
            md.back().targets.insert( md.back().targets.end(),
                                      erefs[ j ].begin(),
                                      erefs[ j ].end() );
        }
    }
}
References Msg::e1(), Msg::e2(), filterOffNodeTargets(), FuncOrder::func(), MsgDigest::func, Msg::getMsg(), isGlobal(), localDataStart(), MsgFuncBinding::mid, msgBinding_, MsgDigest::MsgDigest(), msgDigest_, Shell::myNode(), numLocalData(), Shell::numNodes(), Msg::sources(), MsgDigest::targets, and Msg::targets().
Referenced by digestMessages().
rawIndex()
virtual unsigned int Element::rawIndex (unsigned int dataIndex) const pure virtual
Converts dataIndex to index on current node. No error check.
Implemented in FieldElement, GlobalDataElement, LocalDataElement, and MsgElement.
Referenced by Eref::data(), ObjId::data(), Neutral::getNumField(), FieldElement::rawIndex(), and Neutral::setNumField().
replaceCinfo()
void Element::replaceCinfo (const Cinfo * newCinfo)
Support function for zombieSwap, replaces Cinfo.
Definition at line 740 of file Element.cpp.
{
    cinfo_ = newCinfo;
    // Stuff to be done for data is handled by derived classes in ZombeSwap.
}
References cinfo_.
Referenced by PoolBase::setIsBuffered(), DataElement::zombieSwap(), MsgElement::zombieSwap(), and FieldElement::zombieSwap().
resize()
virtual void Element::resize (unsigned int newNumData) pure virtual
Changes the number of entries in the data. Not permitted for FieldElements since they are just fields on the data.
Implemented in DataElement, FieldElement, LocalDataElement, and MsgElement.
Referenced by Neutral::setNumData(), Dsolve::setPath(), and Stoich::zombifyModel().
resizeField()
virtual void Element::resizeField (unsigned int rawIndex, unsigned int newNumField) pure virtual
Changes the number of fields on the specified data entry. Doesn't do anything for the regular Element.
Implemented in DataElement, FieldElement, and MsgElement.
Referenced by SparseMsg::randomConnect(), Neutral::setNumField(), and SparseMsg::updateAfterFill().
setName()
void Element::setName (const string & val)
Changes name of Element
Definition at line 61 of file Element.cpp.
{
    name_ = val;
}
References name_.
Referenced by addSpine(), ReadKkit::convertKineticsToGroup(), ReadKkit::findCompartmentsFromAnnotation(), Shell::innerCopy(), Neutral::setName(), testGet(), and testStrGet().
setTick()
void Element::setTick (int t)
Assigns clock tick to be used by object. -1 means none. This function does substantial message manipulation to set up the message from the Clock object to the current object to define the Tick. Furthermore, if the object has both init and proc methods, it will set them both up, with the init method on 't-1' and the proc method on 't'
Definition at line 251 of file Element.cpp.
{
    Id clockId( 1 );
    if ( t == tick_ )
        return;
    if ( tick_ >= 0 )   // Drop all messages coming here from clock.
    {
        dropAllMsgsFromSrc( clockId );
    }
    tick_ = t;
    if ( t < 0 || t > 31 )    // Only 32 ticks available.
    {
        // Don't need to add new ticks.
        return;
    }
    const Finfo* f2 = cinfo()->findFinfo( "init" );
    if ( f2 && dynamic_cast< const SharedFinfo* >( f2 ) )
    {
        // Must build init msg too. This comes on the previous tick.
        assert( t > 0 );
        addClockMsg( t-1, id(), f2 );
    }
    f2 = cinfo()->findFinfo( "proc" );
    if ( f2 )
    {
        addClockMsg( t, id(), f2 );
    }
    else
    {
        cout << "Element::setTick:Warning: Attempt to assign a tick to a '"
             << cinfo_->name() << "'.\nThis does not support process actions.\n";
        tick_ = -1;
    }
}
References addClockMsg(), cinfo(), cinfo_, dropAllMsgsFromSrc(), Cinfo::findFinfo(), id(), Id::Id(), Cinfo::name(), and tick_.
Referenced by innerCopyElements(), Shell::innerCreate(), Stoich::installAndUnschedFunc(), Stoich::installAndUnschedFuncRate(), Stoich::installAndUnschedFuncReac(), SocketStreamer::reinit(), Streamer::reinit(), Neutral::setTick(), Stoich::unZombifyModel(), and zombieSwap().
showFields()
void Element::showFields () const
Utility function for printing out all fields and their values
Definition at line 623 of file Element.cpp.
{
    vector< const SrcFinfo* > srcVec;
    vector< const DestFinfo* > destVec;
    vector< const SharedFinfo* > sharedVec;
    vector< const Finfo* > valueVec; // ValueFinfos are what is left.
    for ( map< string, Finfo* >::const_iterator i =
                cinfo_->finfoMap().begin();
            i != cinfo_->finfoMap().end(); ++i )
    {
        const SrcFinfo* sf = dynamic_cast< const SrcFinfo* >( i->second);
        const DestFinfo* df = dynamic_cast< const DestFinfo* >( i->second);
        const SharedFinfo* shf = dynamic_cast< const SharedFinfo* >( i->second);
        if ( sf )
            srcVec.push_back( sf );
        else if ( df )
            destVec.push_back( df );
        else if ( shf )
            sharedVec.push_back( shf );
        else
            valueVec.push_back( i->second );
    }
    cout << "Showing SrcFinfos: \n";
    for ( unsigned int i = 0; i < srcVec.size(); ++i )
        cout << i << ": " << srcVec[i]->name() << " Bind=" << srcVec[i]->getBindIndex() << endl;
    cout << "Showing " << destVec.size() << " DestFinfos: \n";
    /*
    for ( unsigned int i = 0; i < destVec.size(); ++i )
        cout << i << ": " << destVec[i]->name() << "    FuncId=" << destVec[i]->getFid() << endl;
        */
    cout << "Showing SharedFinfos: \n";
    for ( unsigned int i = 0; i < sharedVec.size(); ++i )
    {
        cout << i << ": " << sharedVec[i]->name() << "  Src=[ ";
        for ( unsigned int j = 0; j < sharedVec[i]->src().size(); ++j )
            cout << " " << sharedVec[i]->src()[j]->name();
        cout << " ] Dest=[ ";
        for ( unsigned int j = 0; j < sharedVec[i]->dest().size(); ++j )
            cout << " " << sharedVec[i]->dest()[j]->name();
        cout << " ]\n";
    }
    cout << "Listing ValueFinfos: \n";
    Eref er = this->id().eref();
    string val;
    for ( unsigned int i = 0; i < valueVec.size(); ++i )
    {
        valueVec[i]->strGet( er, valueVec[i]->name(), val );
        cout << i << ": " << valueVec[i]->name() << "   " <<
             val << endl;
    }
}
References cinfo_, SharedFinfo::dest(), Id::eref(), Cinfo::finfoMap(), SrcFinfo::getBindIndex(), id(), Finfo::name(), SharedFinfo::src(), and Finfo::strGet().
showMsg()
void Element::showMsg () const
Utility function for traversing and displaying all messages
Definition at line 313 of file Element.cpp.
{
    cout << "Outgoing: \n";
    for ( map< string, Finfo* >::const_iterator i =
                cinfo_->finfoMap().begin();
            i != cinfo_->finfoMap().end(); ++i )
    {
        const SrcFinfo* sf = dynamic_cast< const SrcFinfo* >( i->second );
        if ( sf && msgBinding_.size() > sf->getBindIndex() )
        {
            const vector< MsgFuncBinding >& mb = msgBinding_[ sf->getBindIndex()];
            unsigned int numTgt = mb.size();
            if ( numTgt > 0 )
            {
                for ( unsigned int j = 0; j < numTgt; ++j )
                {
                    cout << sf->name() << " bindId=" << sf->getBindIndex() << ": ";
                    cout << j << ": MessageId=" << mb[j].mid <<
                         ", FuncId=" << mb[j].fid <<
                         ", " << Msg::getMsg( mb[j].mid )->e1()->getName() <<
                         " -> " <<
                         Msg::getMsg( mb[j].mid )->e2()->getName() << endl;
                }
            }
        }
    }
    cout << "Dest and Src: \n";
    for ( unsigned int i = 0; i < m_.size(); ++i )
    {
        const Msg* m = Msg::getMsg( m_[i] );
        cout << i << ": MessageId= " << m_[i] <<
             ", e1= " << m->e1()->name_ <<
             ", e2= " << m->e2()->name_ << endl;
    }
}
References cinfo_, Msg::e1(), Msg::e2(), MsgFuncBinding::fid, Cinfo::finfoMap(), SrcFinfo::getBindIndex(), Msg::getMsg(), getName(), m_, MsgFuncBinding::mid, msgBinding_, Finfo::name(), and name_.
startDataIndex()
virtual unsigned int Element::startDataIndex (unsigned int nodeNum) const pure virtual
Returns start dataIndex on specified node.
Implemented in FieldElement, GlobalDataElement, LocalDataElement, and MsgElement.
Referenced by HopFunc1< A >::dataOpVec(), and FieldElement::startDataIndex().
totNumLocalField()
virtual unsigned int Element::totNumLocalField () const pure virtual
Returns number of field entries on local node. If this is not a FieldElement, returns numLocalData, assuming 1 field per data.
Implemented in DataElement, FieldElement, and MsgElement.
zombieSwap()
void Element::zombieSwap (const Cinfo * zCinfo) virtual
virtual func, this base version must be called by all derived classes
zombieSwap: replaces the Cinfo and data of the zombie. Allocates a new data block using zCinfo, that matches the number of entries of the old data block. Deletes old data. The base version calls the Clock object to assign a suitable default clock.
Reimplemented in DataElement, MsgElement, and FieldElement.
Definition at line 159 of file Element.cpp.
{
    // cout << name_ << ", cname=" << c->name() << ", t0 = " << this->tick_ << ", t1 = " << Clock::lookupDefaultTick( c->name() ) << endl;
    if ( tick_ == -1 )   // Object is already disabled, let it be.
    {
        return;
    }
    bool zombieInName = ( c->name().substr(0, 6) == "Zombie" );
    if ( tick_ == -2 && !zombieInName )   // Object was a zombie and wants to come home.
    {
        int t = Clock::lookupDefaultTick( c->name() );
        setTick( t );
    }
    else if ( tick_ >= 0 )     // disable clock, with option to return
    {
        if ( zombieInName )
        {
            setTick( -2 );
        }
        else
        {
            int t = Clock::lookupDefaultTick( c->name() );
            setTick( t );
        }
    }
}
References Clock::lookupDefaultTick(), Cinfo::name(), setTick(), and tick_.
Referenced by DataElement::zombieSwap(), MsgElement::zombieSwap(), CaConcBase::zombify(), moose::CompartmentBase::zombify(), and HHChannelBase::zombify().
Member Data Documentation
cinfo_
const Cinfo* Element::cinfo_ private
Stores the unique identifier for Element.
Class information
Definition at line 406 of file Element.h.
Referenced by cinfo(), Element(), replaceCinfo(), setTick(), showFields(), and showMsg().
id_
Id Element::id_ private
Name of the Element.
Definition at line 401 of file Element.h.
Referenced by Element(), id(), and ~Element().
isDoomed_
bool Element::isDoomed_ private
True if the element is marked for destruction.
Definition at line 446 of file Element.h.
Referenced by Element(), isDoomed(), and markAsDoomed().
isRewired_
bool Element::isRewired_ private
True if messages have been changed and need to digestMessages.
Definition at line 443 of file Element.h.
Referenced by Element(), markRewired(), and msgDigest().
m_
vector< ObjId > Element::m_ private
Message vector. This is the low-level messaging information. Contains info about incoming as well as outgoing Msgs.
Definition at line 412 of file Element.h.
Referenced by addMsg(), clearAllMsgs(), dropAllMsgsFromSrc(), dropMsg(), findCaller(), getInputMsgs(), getMsgSourceAndSender(), msgIn(), showMsg(), and ~Element().
msgBinding_
vector< vector < MsgFuncBinding > > Element::msgBinding_ private
Binds an outgoing message to its function. Each index (BindIndex) gives a vector of MsgFuncBindings, which are just pairs of ObjId, FuncId. SrcFinfo keeps track of the BindIndex to look things up. Note that a single BindIndex may refer to multiple Msg/Func pairs. This means that a single MsgSrc may dispatch data through multiple msgs using a single 'send' call.
Definition at line 423 of file Element.h.
Referenced by addMsgAndFunc(), clearAllMsgs(), clearBinding(), digestMessages(), dropMsg(), Element(), findBinding(), getFieldsOfOutgoingMsg(), getMsgAndFunc(), hasMsgs(), printMsgDigest(), putOffNodeTargetsInDigest(), putTargetsInDigest(), showMsg(), and ~Element().
msgDigest_
vector< vector < MsgDigest > > Element::msgDigest_ private
Digested vector of message traversal sets. Each set has a Func and element to lead off, followed by a list of target indices and fields. The indexing is like this: msgDigest_[ numSrcMsgs * dataIndex + srcMsgIndex ][ func# ] So we look up a vector of MsgDigests, each with a unique func, based on both the dataIndex and the message number. This is designed so that if we expand the number of data entries we don't have to redo the ordering.
Definition at line 437 of file Element.h.
Referenced by clearAllMsgs(), digestMessages(), Element(), msgDigest(), printMsgDigest(), putOffNodeTargetsInDigest(), and putTargetsInDigest().
name_
string Element::name_ private
Definition at line 399 of file Element.h.
Referenced by digestMessages(), Element(), getName(), setName(), and showMsg().
tick_
int Element::tick_ private
Returns tick on which element is scheduled. -1 for disabled.
Definition at line 440 of file Element.h.
Referenced by Element(), getTick(), innerSetTick(), setTick(), and zombieSwap().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/basecode/Element.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/basecode/Element.cpp