MOOSE - Multiscale Object Oriented Simulation Environment: PIDController Class Reference
PIDController Class Reference
#include <PIDController.h>
Public Member Functions
double getCommand () const
double getEDerivative () const
double getEIntegral () const
double getEPrevious () const
double getError () const
double getGain () const
double getOutput () const
double getSaturation () const
double getSensed () const
double getTauD () const
double getTauI () const
PIDController ()
void process (const Eref &e, ProcPtr process)
void reinit (const Eref &e, ProcPtr process)
void setCommand (double command)
void setGain (double gain)
void setSaturation (double saturation)
void setSensed (double sensed)
void setTauD (double tau_d)
void setTauI (double tau_i)
Static Public Member Functions
static const Cinfo * initCinfo ()
Private Attributes
double command_
double e_derivative_
double e_integral_
double e_previous_
double error_
double gain_
double output_
double saturation_
double sensed_
double tau_d_
double tau_i_
Detailed Description
Definition at line 44 of file PIDController.h.
Constructor & Destructor Documentation
PIDController()
PIDController::PIDController ()
Definition at line 186 of file PIDController.cpp.
                            :
        command_(0),
        saturation_(DBL_MAX),
        gain_(1),
        tau_i_(0),
        tau_d_(0),
        sensed_(0),
        output_(0),
        error_(0),
        e_integral_(0),
        e_derivative_(0),
        e_previous_(0)
{
    ;    // do nothing else
}
References command_, e_derivative_, e_integral_, e_previous_, error_, gain_, output_, saturation_, sensed_, tau_d_, and tau_i_.
Member Function Documentation
getCommand()
double PIDController::getCommand () const
Definition at line 207 of file PIDController.cpp.
{
    return command_;
}
References command_.
Referenced by initCinfo().
getEDerivative()
double PIDController::getEDerivative () const
Definition at line 281 of file PIDController.cpp.
{
    return e_derivative_;
}
References e_derivative_.
Referenced by initCinfo().
getEIntegral()
double PIDController::getEIntegral () const
Definition at line 276 of file PIDController.cpp.
{
    return e_integral_;
}
References e_integral_.
Referenced by initCinfo().
getEPrevious()
double PIDController::getEPrevious () const
Definition at line 286 of file PIDController.cpp.
{
    return e_previous_;
}
References e_previous_.
Referenced by initCinfo().
getError()
double PIDController::getError () const
Definition at line 271 of file PIDController.cpp.
{
    return error_;
}
References error_.
Referenced by initCinfo().
getGain()
double PIDController::getGain () const
Definition at line 232 of file PIDController.cpp.
{
    return gain_;
}
References gain_.
Referenced by initCinfo().
getOutput()
double PIDController::getOutput () const
Definition at line 222 of file PIDController.cpp.
{
    return output_;
}
References output_.
Referenced by initCinfo().
getSaturation()
double PIDController::getSaturation () const
Definition at line 266 of file PIDController.cpp.
{
    return saturation_;
}
References saturation_.
Referenced by initCinfo().
getSensed()
double PIDController::getSensed () const
Definition at line 217 of file PIDController.cpp.
{
    return sensed_;
}
References sensed_.
Referenced by initCinfo().
getTauD()
double PIDController::getTauD () const
Definition at line 252 of file PIDController.cpp.
{
    return tau_d_;
}
References tau_d_.
Referenced by initCinfo().
getTauI()
double PIDController::getTauI () const
Definition at line 242 of file PIDController.cpp.
{
    return tau_i_;
}
References tau_i_.
Referenced by initCinfo().
initCinfo()
const Cinfo * PIDController::initCinfo () static
Definition at line 54 of file PIDController.cpp.
{
       static DestFinfo process( "process",
                       "Handle process calls.",
                       new ProcOpFunc<PIDController>( &PIDController::process));
       static DestFinfo reinit( "reinit",
                       "Reinitialize the object.",
                       new ProcOpFunc<PIDController>( &PIDController::reinit ));
    static Finfo* processShared[] = {
        &process, &reinit
    };
        static ValueFinfo<PIDController, double> gain( "gain",
                                                "This is the proportional gain (Kp). This tuning parameter scales the"
                                                " proportional term. Larger gain usually results in faster response, but"
                                                " too much will lead to instability and oscillation.",
                                                &PIDController::setGain,
                                                &PIDController::getGain);
        static ValueFinfo<PIDController, double> saturation("saturation",
                                              "Bound on the permissible range of output. Defaults to maximum double"
                                              " value.",
                                              &PIDController::setSaturation,
                                              &PIDController::getSaturation);
        static ValueFinfo<PIDController, double> command("command",
                                              "The command (desired) value of the sensed parameter. In control theory"
                                              " this is commonly known as setpoint(SP).",
                                              &PIDController::setCommand,
                                              &PIDController::getCommand);
        static ReadOnlyValueFinfo<PIDController, double> sensed( "sensed",
                                                       "Sensed (measured) value. This is commonly known as process variable"
                                                       "(PV) in control theory.",
                                                       &PIDController::getSensed);
        static ValueFinfo<PIDController, double> tauI( "tauI",
                                               "The integration time constant, typically = dt. This is actually"
                                               " proportional gain divided by integral gain (Kp/Ki)). Larger Ki"
                                               " (smaller tauI) usually leads to fast elimination of steady state"
                                               " errors at the cost of larger overshoot.",
                                               &PIDController::setTauI,
                                               &PIDController::getTauI);
        static ValueFinfo<PIDController, double> tauD( "tauD",
                                               "The differentiation time constant, typically = dt / 4. This is"
                                               " derivative gain (Kd) times proportional gain (Kp). Larger Kd (tauD)"
                                               " decreases overshoot at the cost of slowing down transient response"
                                               " and may lead to instability.",
                                               &PIDController::setTauD,
                                               &PIDController::getTauD);
        static ReadOnlyValueFinfo<PIDController, double> outputValue( "outputValue",
                                                       "Output of the PIDController. This is given by:"
                                                       "      gain * ( error + INTEGRAL[ error dt ] / tau_i   + tau_d * d(error)/dt )\n"
                                                       "Where gain = proportional gain (Kp), tau_i = integral gain (Kp/Ki) and"
                                                       " tau_d = derivative gain (Kd/Kp). In control theory this is also known"
                                                       " as the manipulated variable (MV)",
                                                       &PIDController::getOutput);
        static ReadOnlyValueFinfo<PIDController, double> error( "error",
                                                       "The error term, which is the difference between command and sensed"
                                                       " value.",
                                                       &PIDController::getError);
        static ReadOnlyValueFinfo<PIDController, double> integral( "integral",
                                                       "The integral term. It is calculated as INTEGRAL(error dt) ="
                                                       " previous_integral + dt * (error + e_previous)/2.",
                                                       &PIDController::getEIntegral );
        static ReadOnlyValueFinfo<PIDController, double> derivative( "derivative",
                                                       "The derivative term. This is (error - e_previous)/dt.",
                                                       &PIDController::getEDerivative );
        static ReadOnlyValueFinfo<PIDController, double> e_previous( "e_previous",
                                                       "The error term for previous step.",
                                                       &PIDController::getEPrevious);
        static DestFinfo commandIn( "commandIn",
                       "Command (desired value) input. This is known as setpoint (SP) in"
                       " control theory." ,
                       new OpFunc1<PIDController, double>( &PIDController::setCommand ));
        static DestFinfo sensedIn( "sensedIn",
                       "Sensed parameter - this is the one to be tuned. This is known as"
                       " process variable (PV) in control theory. This comes from the process"
                       " we are trying to control.",
                       new OpFunc1<PIDController, double>( &PIDController::setSensed ));
        static DestFinfo gainDest( "gainDest",
                       "Destination message to control the PIDController gain dynamically.",
                       new OpFunc1<PIDController, double>(&PIDController::setGain));
        static SharedFinfo proc( "proc",
                         "This is a shared message to receive Process messages "
                         "from the scheduler objects."
                         "The first entry in the shared msg is a MsgDest "
                         "for the Process operation. It has a single argument, "
                         "ProcInfo, which holds lots of information about current "
                         "time, thread, dt and so on. The second entry is a MsgDest "
                         "for the Reinit operation. It also uses ProcInfo. ",
                         processShared, sizeof( processShared ) / sizeof( Finfo* )
                         );
    static Finfo* pidFinfos[] = {
        &gain,
        &saturation,
        &command,
        &sensed,
        &tauI,
        &tauD,
        &outputValue,
        &error,
        &integral,
        &derivative,
        &e_previous,
        outputOut(),
        &commandIn,
        &sensedIn,
        &gainDest,
        &proc
    };
    static string doc[] = {
        "Name", "PIDController",
        "Author", "Subhasis Ray",
        "Description", "PID feedback controller."
        "PID stands for Proportional-Integral-Derivative. It is used to"
        " feedback control dynamical systems. It tries to create a feedback"
        " output such that the sensed (measured) parameter is held at command"
        " value. Refer to wikipedia (http://wikipedia.org) for details on PID"
        " Controller." };
    static Dinfo<PIDController> dinfo;
    static Cinfo pidCinfo(
            "PIDController",
            Neutral::initCinfo(),
            pidFinfos,
            sizeof( pidFinfos ) / sizeof( Finfo* ),
            &dinfo,
            doc,
            sizeof(doc)/sizeof(string));
    return &pidCinfo;
}
References Cinfo::Cinfo(), DestFinfo::DestFinfo(), getCommand(), getEDerivative(), getEIntegral(), getEPrevious(), getError(), getGain(), getOutput(), getSaturation(), getSensed(), getTauD(), getTauI(), Neutral::initCinfo(), OpFunc1< T, A >::OpFunc1(), outputOut(), process(), ProcOpFunc< T >::ProcOpFunc(), ReadOnlyValueFinfo< T, F >::ReadOnlyValueFinfo(), reinit(), setCommand(), setGain(), setSaturation(), setSensed(), setTauD(), setTauI(), SharedFinfo::SharedFinfo(), and ValueFinfo< T, F >::ValueFinfo().
process()
void PIDController::process (const Eref & e, ProcPtr process)
Definition at line 291 of file PIDController.cpp.
{
    double dt = proc->dt;
    e_previous_ = error_;
    error_ = command_ - sensed_;
    e_integral_ += 0.5 * (error_ + e_previous_) * dt;
    e_derivative_ = (error_ - e_previous_) / dt;
    output_ = gain_ * (error_ + e_integral_ / tau_i_ + e_derivative_ * tau_d_);
    if (output_ > saturation_){
        output_ = saturation_;
        e_integral_ -= 0.5 * (error_ + e_previous_) * dt;
    } else if (output_ < -saturation_){
        output_ = -saturation_;
        e_integral_ -= 0.5 * (error_ + e_previous_) * dt;
    }
    outputOut()->send(e, output_);
}
References command_, ProcInfo::dt, e_derivative_, e_integral_, e_previous_, error_, gain_, output_, outputOut(), saturation_, SrcFinfo1< T >::send(), sensed_, tau_d_, and tau_i_.
Referenced by initCinfo().
reinit()
void PIDController::reinit (const Eref & e, ProcPtr process)
Definition at line 310 of file PIDController.cpp.
{
    if ( tau_i_ <= 0.0 ){
        tau_i_ = proc->dt;
    }
    if ( tau_d_ < 0.0 ){
        tau_d_ = proc->dt / 4;
    }
    sensed_ = 0.0;
    output_ = 0;
    error_ = 0;
    e_previous_ = error_;
    e_integral_ = 0;
    e_derivative_ = 0;
    outputOut()->send(e, output_);
}
References ProcInfo::dt, e_derivative_, e_integral_, e_previous_, error_, output_, outputOut(), SrcFinfo1< T >::send(), sensed_, tau_d_, and tau_i_.
Referenced by initCinfo().
setCommand()
void PIDController::setCommand (double command)
Definition at line 202 of file PIDController.cpp.
{
    command_ = command;
}
References command_.
Referenced by initCinfo().
setGain()
void PIDController::setGain (double gain)
Definition at line 227 of file PIDController.cpp.
{
    gain_ = gain;
}
References gain_.
Referenced by initCinfo().
setSaturation()
void PIDController::setSaturation (double saturation)
Definition at line 257 of file PIDController.cpp.
{
    if (saturation <= 0) {
        cout << "Error: PIDController::setSaturation - saturation must be positive." << endl;
    } else {
        saturation_ = saturation;
    }
}
References saturation_.
Referenced by initCinfo().
setSensed()
void PIDController::setSensed (double sensed)
Definition at line 212 of file PIDController.cpp.
{
    sensed_ = sensed;
}
References sensed_.
Referenced by initCinfo().
setTauD()
void PIDController::setTauD (double tau_d)
Definition at line 247 of file PIDController.cpp.
{
    tau_d_ = tau_d;
}
References tau_d_.
Referenced by initCinfo().
setTauI()
void PIDController::setTauI (double tau_i)
Definition at line 237 of file PIDController.cpp.
{
    tau_i_ = tau_i;
}
References tau_i_.
Referenced by initCinfo().
Member Data Documentation
command_
double PIDController::command_ private
Definition at line 70 of file PIDController.h.
Referenced by getCommand(), PIDController(), process(), and setCommand().
e_derivative_
double PIDController::e_derivative_ private
Definition at line 79 of file PIDController.h.
Referenced by getEDerivative(), PIDController(), process(), and reinit().
e_integral_
double PIDController::e_integral_ private
Definition at line 78 of file PIDController.h.
Referenced by getEIntegral(), PIDController(), process(), and reinit().
e_previous_
double PIDController::e_previous_ private
Definition at line 80 of file PIDController.h.
Referenced by getEPrevious(), PIDController(), process(), and reinit().
error_
double PIDController::error_ private
Definition at line 77 of file PIDController.h.
Referenced by getError(), PIDController(), process(), and reinit().
gain_
double PIDController::gain_ private
Definition at line 72 of file PIDController.h.
Referenced by getGain(), PIDController(), process(), and setGain().
output_
double PIDController::output_ private
Definition at line 76 of file PIDController.h.
Referenced by getOutput(), PIDController(), process(), and reinit().
saturation_
double PIDController::saturation_ private
Definition at line 71 of file PIDController.h.
Referenced by getSaturation(), PIDController(), process(), and setSaturation().
sensed_
double PIDController::sensed_ private
Definition at line 75 of file PIDController.h.
Referenced by getSensed(), PIDController(), process(), reinit(), and setSensed().
tau_d_
double PIDController::tau_d_ private
Definition at line 74 of file PIDController.h.
Referenced by getTauD(), PIDController(), process(), reinit(), and setTauD().
tau_i_
double PIDController::tau_i_ private
Definition at line 73 of file PIDController.h.
Referenced by getTauI(), PIDController(), process(), reinit(), and setTauI().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/device/PIDController.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/device/PIDController.cpp