MOOSE - Multiscale Object Oriented Simulation Environment: GssaVoxelPools Class Reference
GssaVoxelPools Class Reference
#include <GssaVoxelPools.h>
Public Member Functions
void advance (const ProcInfo *p)
void advance (const ProcInfo *p, const GssaSystem *g)
double getReacVelocity (unsigned int r, const double *s) const
GssaVoxelPools ()
vector< unsigned int > numFire () const
unsigned int pickReac ()
void recalcTime (const GssaSystem *g, double currTime)
bool refreshAtot (const GssaSystem *g)
void reinit (const GssaSystem *g, int rngSeedOffset)
void setNumReac (unsigned int n)
void setStoich (const Stoich *stoichPtr)
void setVolumeAndDependencies (double vol)
void updateAllRateTerms (const vector< RateTerm * > &rates, unsigned int numCoreRates)
void updateDependentMathExpn (const GssaSystem *g, unsigned int rindex, double time)
void updateDependentRates (const vector< unsigned int > &deps, const Stoich *stoich)
void updateRateTerms (const vector< RateTerm * > &rates, unsigned int numCoreRates, unsigned int index)
void updateReacVelocities (const GssaSystem *g, const double *s, vector< double > &v) const
void xferIn (XferInfo &xf, unsigned int voxelIndex, const GssaSystem *g)
virtual ~GssaVoxelPools ()
Public Member Functions inherited from VoxelPoolsBase
void addProxyTransferIndex (unsigned int comptIndex, unsigned int transferIndex)
void addProxyVoxy (unsigned int comptIndex, Id comptId, unsigned int voxel)
Adds the index of a voxel to which proxy data should go.
void backwardReacVolumeFactor (unsigned int i, double volume)
const double * Cinit () const
void filterCrossRateTerms (const vector< Id > &offSolverReacs, const vector< pair< Id, Id > > &offSolverReacCompts)
void forwardReacVolumeFactor (unsigned int i, double volume)
double getConcInit (unsigned int) const
double getDiffConst (unsigned int) const
double getN (unsigned int) const
double getR1 (unsigned int) const
double getVolume () const
Return the volume of the voxel.
double getXreacScaleProducts (unsigned int i) const
double getXreacScaleSubstrates (unsigned int i) const
bool hasXfer (unsigned int comptIndex) const
True when this voxel has data to be transferred.
bool isVoxelJunctionPresent (Id i1, Id i2) const
void print () const
Debugging utility.
void reinit ()
void resetXreacScale (unsigned int size)
void resizeArrays (unsigned int totNumPools)
Allocate # of pools.
const double * S () const
void scaleVolsBufsRates (double ratio, const Stoich *stoichPtr)
void setConcInit (unsigned int, double v)
void setDiffConst (unsigned int, double v)
void setN (unsigned int i, double v)
void setNumVoxels (unsigned int)
void setVolume (double vol)
Just assigns the volume without any cascading to other values.
unsigned int size () const
vector< double > & Svec ()
Returns a handle to the mol # vector.
double * varCinit ()
double * varS ()
VoxelPoolsBase ()
void xferIn (const vector< unsigned int > &poolIndex, const vector< double > &values, const vector< double > &lastValues, unsigned int voxelIndex)
void xferInOnlyProxies (const vector< unsigned int > &poolIndex, const vector< double > &values, unsigned int numProxyPools, unsigned int voxelIndex)
void xferOut (unsigned int voxelIndex, vector< double > &values, const vector< unsigned int > &poolIndex)
Assembles data values for sending out for x-compt reacs.
virtual ~VoxelPoolsBase ()
Private Attributes
double atot_
vector< unsigned int > numFire_
moose::RNG rng_
RNG.
double t_
Time at which next event will occur.
vector< double > v_
Additional Inherited Members
Protected Attributes inherited from VoxelPoolsBase
unsigned int numVoxels_
vector< RateTerm * > rates_
const Stoich * stoichPtr_
Detailed Description
Definition at line 17 of file GssaVoxelPools.h.
Constructor & Destructor Documentation
GssaVoxelPools()
GssaVoxelPools::GssaVoxelPools ()
Definition at line 43 of file GssaVoxelPools.cpp.
                              : VoxelPoolsBase(), t_( 0.0 ), atot_( 0.0 )
{;}
References atot_, t_, and VoxelPoolsBase::VoxelPoolsBase().
~GssaVoxelPools()
GssaVoxelPools::~GssaVoxelPools () virtual
Definition at line 46 of file GssaVoxelPools.cpp.
{
    for ( size_t i = 0; i < rates_.size(); ++i )
        delete( rates_[i] );
}
References VoxelPoolsBase::rates_.
Member Function Documentation
advance() [1/2]
void GssaVoxelPools::advance (const ProcInfo * p)
advance() [2/2]
void GssaVoxelPools::advance (const ProcInfo * p, const GssaSystem * g)
Definition at line 162 of file GssaVoxelPools.cpp.
{
    double nextt = p->currTime;
    while ( t_ < nextt )
    {
        if ( atot_ <= 0.0 )   // reac system is stuck, will not advance.
        {
            t_ = nextt;
            g->stoich->updateFuncs( varS(), t_ );
            return;
        }
        unsigned int rindex = pickReac();
        assert( g->stoich->getNumRates() == v_.size() );
        if ( rindex >= g->stoich->getNumRates() )
        {
            // probably cumulative roundoff error here.
            // Recalculate atot to avoid, and redo.
            if ( !refreshAtot( g ) )   // Stuck state.
            {
                t_ = nextt;
                g->stoich->updateFuncs( varS(), t_ );
                return;
            }
            // We had a roundoff error, fixed it, but now need to be sure
            // we only fire a reaction where this is permissible.
            for ( unsigned int i = v_.size(); i > 0; --i )
            {
                if ( fabs( v_[i-1] ) > 0.0 )
                {
                    rindex = i - 1;
                    break;
                }
            }
            assert( rindex < v_.size() );
        }
        double sign = std::copysign( 1, v_[rindex] );
        g->transposeN.fireReac( rindex, Svec(), sign );
        numFire_[rindex]++;
        double r = rng_.uniform();
        while ( r <= 0.0 )
            r = rng_.uniform();
        t_ -= ( 1.0 / atot_ ) * log( r );
        g->stoich->updateFuncs( varS(), t_ );
        updateDependentRates( g->dependency[ rindex ], g->stoich );
    }
}
References atot_, ProcInfo::currTime, GssaSystem::dependency, KinSparseMatrix::fireReac(), Stoich::getNumRates(), numFire_, pickReac(), refreshAtot(), rng_, GssaSystem::stoich, VoxelPoolsBase::Svec(), t_, GssaSystem::transposeN, moose::RNG::uniform(), updateDependentRates(), Stoich::updateFuncs(), v_, and VoxelPoolsBase::varS().
Referenced by Gsolve::advance_chunk(), and Gsolve::process().
getReacVelocity()
double GssaVoxelPools::getReacVelocity (unsigned int r, const double * s) const
Definition at line 322 of file GssaVoxelPools.cpp.
{
    double v = rates_[r]->operator()( s );
    return v;
}
References RateTerm::operator()(), and VoxelPoolsBase::rates_.
Referenced by updateDependentRates().
numFire()
vector< unsigned int > GssaVoxelPools::numFire () const
Definition at line 256 of file GssaVoxelPools.cpp.
{
    return numFire_;
}
References numFire_.
Referenced by Gsolve::getNumFire().
pickReac()
unsigned int GssaVoxelPools::pickReac ()
Definition at line 95 of file GssaVoxelPools.cpp.
{
    double r = rng_.uniform( ) * atot_;
    double sum = 0.0;
    // This is an inefficient way to do it. Can easily get to
    // log time or thereabouts by doing one or two levels of
    // subsidiary tables. Too many levels causes slow-down because
    // of overhead in managing the tree.
    // Slepoy, Thompson and Plimpton 2008
    // report a linear time version.
    for ( auto i = v_.cbegin(); i != v_.end(); ++i )
    {
        if ( r < ( sum += fabs( *i ) ) )
        {
            // double vel = fabs( getReacVelocity( i - v_.begin(), S() ) );
            // assert( vel >= 0 );
            return static_cast< unsigned int >( i - v_.begin() );
        }
    }
    return v_.size();
}
References atot_, rng_, moose::RNG::uniform(), and v_.
Referenced by advance().
recalcTime()
void GssaVoxelPools::recalcTime (const GssaSystem * g, double currTime)
Recalculates the time for the next event. Used when we have a clocked update of rates due to timed functions. In such cases the propensities may change invisibly, so we need to update time estimates
Definition at line 151 of file GssaVoxelPools.cpp.
{
    refreshAtot( g );
    assert( t_ > currTime );
    t_ = currTime;
    double r = rng_.uniform( );
    while( r == 0.0 )
        r = rng_.uniform( );
    t_ -= ( 1.0 / atot_ ) * log( r );
}
References atot_, refreshAtot(), rng_, t_, and moose::RNG::uniform().
Referenced by Gsolve::process(), and Gsolve::recalcTimeChunk().
refreshAtot()
bool GssaVoxelPools::refreshAtot (const GssaSystem * g)
Cleans out all reac rates and recalculates atot. Needed whenever a mol conc changes, or if there is a roundoff error. Returns true if OK, returns false if it is in a stuck state and atot<=0
Definition at line 130 of file GssaVoxelPools.cpp.
{
    g->stoich->updateFuncs( varS(), t_ );
    updateReacVelocities( g, S(), v_ );
    atot_ = 0;
    for ( auto i = v_.cbegin(); i != v_.cend(); ++i )
        atot_ += fabs(*i);
    atot_ *= SAFETY_FACTOR;
    // Check if the system is in a stuck state. If so, terminate.
    if ( atot_ <= 0.0 )
        return false;
    return true;
}
References atot_, VoxelPoolsBase::S(), SAFETY_FACTOR, GssaSystem::stoich, t_, Stoich::updateFuncs(), updateReacVelocities(), v_, and VoxelPoolsBase::varS().
Referenced by advance(), Gsolve::process(), recalcTime(), Gsolve::reinit(), reinit(), Gsolve::setConcInit(), Gsolve::setN(), Gsolve::setNvec(), and xferIn().
reinit()
void GssaVoxelPools::reinit (const GssaSystem * g, int rngSeedOffset)
Builds the gssa system as needed.
Definition at line 213 of file GssaVoxelPools.cpp.
{
    rng_.setSeed( moose::getGlobalSeed() + rngSeedOffset );
    VoxelPoolsBase::reinit(); // Assigns S = NA * vol * Cinit;
    unsigned int numVarPools = g->stoich->getNumVarPools();
    g->stoich->updateFuncs( varS(), 0 );
    double* n = varS();
    double error = 0.0;
    double _prev = 0.0;
    if( g->useRandInit )
    {
        map<double, vector<Eref>> groupByVal;
        for ( unsigned int i = 0; i < numVarPools; ++i )
        {
            _prev = n[i];
            n[i] = approximateWithInteger(_prev, rng_);
            error += fabs(_prev - n[i]);
        }
        // Show warning to user if extra molecules in the system after
        // converting floats to integer is larger than 1.0.
        // Jan 2024: Disable until I come up with a good way to handle.
        // Note also that this is likely when we have more pools.
        if( 0 && std::abs(error) >= 1.0 )
        {
            MOOSE_WARN( "Extra " << error
                        << " molecules in system after converting fractional to integer."
                      );
        }
    }
    else  // Just round to the nearest int.
    {
        for ( unsigned int i = 0; i < numVarPools; ++i )
            n[i] = std::round(n[i]);
    }
    t_ = 0.0;
    refreshAtot( g );
    numFire_.assign( v_.size(), 0 );
}
References approximateWithInteger(), moose::getGlobalSeed(), Stoich::getNumVarPools(), numFire_, refreshAtot(), VoxelPoolsBase::reinit(), rng_, moose::RNG::setSeed(), GssaSystem::stoich, t_, Stoich::updateFuncs(), GssaSystem::useRandInit, v_, and VoxelPoolsBase::varS().
Referenced by Gsolve::initReinit(), and Gsolve::reinit().
setNumReac()
void GssaVoxelPools::setNumReac (unsigned int n)
Definition at line 118 of file GssaVoxelPools.cpp.
{
    v_.clear();
    v_.resize( n, 0.0 );
    numFire_.resize( n, 0 );
}
References numFire_, and v_.
Referenced by Gsolve::rebuildGssaSystem().
setStoich()
void GssaVoxelPools::setStoich (const Stoich * stoichPtr)
Definition at line 329 of file GssaVoxelPools.cpp.
{
    stoichPtr_ = stoichPtr;
}
References VoxelPoolsBase::stoichPtr_.
Referenced by Gsolve::setStoich().
setVolumeAndDependencies()
void GssaVoxelPools::setVolumeAndDependencies (double vol) virtual
Assign the volume, and handle the cascading effects by scaling all the dependent values of concInit and rates if applicable.
Reimplemented from VoxelPoolsBase.
Definition at line 335 of file GssaVoxelPools.cpp.
{
    VoxelPoolsBase::setVolumeAndDependencies( vol );
    updateAllRateTerms(stoichPtr_->getRateTerms(), stoichPtr_->getNumCoreRates());
}
References Stoich::getNumCoreRates(), Stoich::getRateTerms(), VoxelPoolsBase::setVolumeAndDependencies(), VoxelPoolsBase::stoichPtr_, and updateAllRateTerms().
Referenced by Gsolve::updateVoxelVol().
updateAllRateTerms()
void GssaVoxelPools::updateAllRateTerms (const vector< RateTerm * > & rates, unsigned int numCoreRates) virtual
Reassign entire rate vector.
Implements VoxelPoolsBase.
Definition at line 265 of file GssaVoxelPools.cpp.
{
    for ( unsigned int i = 0; i < rates_.size(); ++i )
        delete( rates_[i] );
    rates_.resize( rates.size() );
    for ( unsigned int i = 0; i < numCoreRates; ++i )
        rates_[i] = rates[i]->copyWithVolScaling( getVolume(), 1, 1 );
    for ( unsigned int i = numCoreRates; i < rates.size(); ++i )
        rates_[i] = rates[i]->copyWithVolScaling( getVolume(),
                    getXreacScaleSubstrates(i - numCoreRates),
                    getXreacScaleProducts(i - numCoreRates ) );
}
References RateTerm::copyWithVolScaling(), VoxelPoolsBase::getVolume(), VoxelPoolsBase::getXreacScaleProducts(), VoxelPoolsBase::getXreacScaleSubstrates(), and VoxelPoolsBase::rates_.
Referenced by Gsolve::rebuildGssaSystem(), setVolumeAndDependencies(), and Gsolve::updateRateTerms().
updateDependentMathExpn()
void GssaVoxelPools::updateDependentMathExpn (const GssaSystem * g, unsigned int rindex, double time)
Definition at line 56 of file GssaVoxelPools.cpp.
{
    // The issue is that if the expression depends on t, we really need
    // to update it every timestep. But then a cascading set of reacs
    // should also be updated.
    // The lower commented block has all funcs updated every time step,
    // but this too
    // doesn't update the cascading reacs. So this is now handled by the
    // useClockedUpdate flag, and we use the lower block here instead.
    /*
    const vector< unsigned int >& deps = g->dependentMathExpn[ rindex ];
    for( vector< unsigned int >::const_iterator
            i = deps.begin(); i != deps.end(); ++i ) {
            g->stoich->funcs( *i )->evalPool( varS(), time );
    }
    */
    /*
    unsigned int numFuncs = g->stoich->getNumFuncs();
    for( unsigned int i = 0; i < numFuncs; ++i )
    {
        g->stoich->funcs( i )->evalPool( varS(), time );
    }
    */
    // This function is equivalent to the loop above.
    g->stoich->updateFuncs( varS(), time );
}
References GssaSystem::stoich, Stoich::updateFuncs(), and VoxelPoolsBase::varS().
updateDependentRates()
void GssaVoxelPools::updateDependentRates (const vector< unsigned int > & deps, const Stoich * stoich)
Definition at line 84 of file GssaVoxelPools.cpp.
{
    for ( auto i = deps.cbegin(); i != deps.end(); ++i )
    {
        atot_ -= fabs( v_[ *i ] );
        atot_ += fabs( v_[ *i ] = getReacVelocity( *i, S() ) );
    }
}
References atot_, getReacVelocity(), VoxelPoolsBase::S(), and v_.
Referenced by advance().
updateRateTerms()
void GssaVoxelPools::updateRateTerms (const vector< RateTerm * > & rates, unsigned int numCoreRates, unsigned int index) virtual
Update specified index on rate terms. The entire rates vector is passed in for the source values, the index specifies which entry on the local rate vector is to be updated.
Implements VoxelPoolsBase.
Definition at line 282 of file GssaVoxelPools.cpp.
{
    // During setup or expansion of the reac system, this might be called
    // before the local rates_ term is assigned. If so, ignore.
    if ( index >= rates_.size() )
        return;
    delete( rates_[index] );
    if ( index >= numCoreRates )
        rates_[index] = rates[index]->copyWithVolScaling(
                            getVolume(),
                            getXreacScaleSubstrates(index - numCoreRates),
                            getXreacScaleProducts(index - numCoreRates)
                        );
    else
        rates_[index] = rates[index]->copyWithVolScaling(getVolume(), 1.0, 1.0);
}
References RateTerm::copyWithVolScaling(), VoxelPoolsBase::getVolume(), VoxelPoolsBase::getXreacScaleProducts(), VoxelPoolsBase::getXreacScaleSubstrates(), and VoxelPoolsBase::rates_.
Referenced by Gsolve::updateRateTerms().
updateReacVelocities()
void GssaVoxelPools::updateReacVelocities (const GssaSystem * g, const double * s, vector< double > & v) const
updateReacVelocities computes the velocity v of each reaction. This is a utility function for programs like SteadyState that need to analyze velocity.
Definition at line 304 of file GssaVoxelPools.cpp.
{
    const KinSparseMatrix& N = g->stoich->getStoichiometryMatrix();
    assert( N.nColumns() == rates_.size() );
    vector< RateTerm* >::const_iterator i;
    v.clear();
    v.resize( rates_.size(), 0.0 );
    vector< double >::iterator j = v.begin();
    for ( i = rates_.begin(); i != rates_.end(); i++)
    {
        *j++ = (**i)( s );
        assert( !std::isnan( *( j-1 ) ) );
    }
}
References Stoich::getStoichiometryMatrix(), SparseMatrix< T >::nColumns(), RateTerm::operator()(), VoxelPoolsBase::rates_, and GssaSystem::stoich.
Referenced by refreshAtot().
xferIn()
void GssaVoxelPools::xferIn (XferInfo & xf, unsigned int voxelIndex, const GssaSystem * g)
Digests incoming data values for cross-compt reactions. Sums the changes in the values onto the specified pools.
Definition at line 342 of file GssaVoxelPools.cpp.
{
    unsigned int offset = voxelIndex * xf.xferPoolIdx.size();
    auto i = xf.values.cbegin() + offset;
    auto j = xf.lastValues.cbegin() + offset;
    auto m = xf.subzero.begin() + offset;
    double* s = varS();
    for ( auto k = xf.xferPoolIdx.cbegin(); k != xf.xferPoolIdx.end(); ++k )
    {
        double& x = s[*k];
        double dx = *i++ - *j++;
        // x += approximateWithInteger_debug(__FUNCTION__, dx, rng_);
        x += approximateWithInteger(dx, rng_);
        if ( x < *m )
        {
            *m -= x;
            x = 0;
        }
        else
        {
            x -= *m;
            *m = 0;
        }
        m++;
    }
    // If S has changed, then I should update rates of all affected reacs.
    // Go through stoich matrix to find affected reacs for each mol
    // Store in list, since some may be hit more than once in this func.
    // When done, go through and update all affected ones.
    // Does this fix the problem of negative concs?
    refreshAtot( g );
}
References approximateWithInteger(), XferInfo::lastValues, refreshAtot(), rng_, XferInfo::subzero, XferInfo::values, VoxelPoolsBase::varS(), and XferInfo::xferPoolIdx.
Member Data Documentation
atot_
double GssaVoxelPools::atot_ private
Total propensity of all the reactions in the system
Definition at line 84 of file GssaVoxelPools.h.
Referenced by advance(), GssaVoxelPools(), pickReac(), recalcTime(), refreshAtot(), and updateDependentRates().
numFire_
vector< unsigned int > GssaVoxelPools::numFire_ private
Definition at line 94 of file GssaVoxelPools.h.
Referenced by advance(), numFire(), reinit(), and setNumReac().
rng_
moose::RNG GssaVoxelPools::rng_ private
RNG.
Definition at line 99 of file GssaVoxelPools.h.
Referenced by advance(), pickReac(), recalcTime(), reinit(), and xferIn().
t_
double GssaVoxelPools::t_ private
Time at which next event will occur.
Definition at line 79 of file GssaVoxelPools.h.
Referenced by advance(), GssaVoxelPools(), recalcTime(), refreshAtot(), and reinit().
v_
vector< double > GssaVoxelPools::v_ private
State vector of reaction velocities. Only a subset are recalculated on each step.
Definition at line 90 of file GssaVoxelPools.h.
Referenced by advance(), pickReac(), refreshAtot(), reinit(), setNumReac(), and updateDependentRates().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/ksolve/GssaVoxelPools.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/ksolve/GssaVoxelPools.cpp