MOOSE - Multiscale Object Oriented Simulation Environment: HHGate2D Class Reference
HHGate2D Class Reference
#include <HHGate2D.h>
Public Member Functions
bool checkOriginal (Id id, const string &field) const
vector< vector< double > > getTableA (const Eref &e) const
vector< vector< double > > getTableB (const Eref &e) const
unsigned int getXdivs (const Eref &e) const
double getXmax (const Eref &e) const
double getXmin (const Eref &e) const
unsigned int getYdivs (const Eref &e) const
double getYmax (const Eref &e) const
double getYmin (const Eref &e) const
HHGate2D ()
HHGate2D (Id originalChanId, Id originalGateId)
bool isOriginalChannel (Id id) const
bool isOriginalGate (Id id) const
double lookupA (vector< double > v) const
double lookupB (vector< double > v) const
void lookupBoth (double v, double c, double *A, double *B) const
Id originalChannelId () const
void setTableA (const Eref &e, vector< vector< double > > value)
void setTableB (const Eref &e, vector< vector< double > > value)
void setXdivs (const Eref &e, unsigned int value)
void setXmax (const Eref &e, double value)
void setXmin (const Eref &e, double value)
void setYdivs (const Eref &e, unsigned int value)
void setYmax (const Eref &e, double value)
void setYmin (const Eref &e, double value)
Public Member Functions inherited from HHGateBase
bool checkOriginal (Id id, const string &field) const
HHGateBase ()
HHGateBase (Id originalChanId, Id originalGateId)
bool isOriginalChannel (Id id) const
bool isOriginalGate (Id id) const
Id originalChannelId () const
Id originalGateId () const
Static Public Member Functions
static const Cinfo * initCinfo ()
Static Public Member Functions inherited from HHGateBase
static const Cinfo * initCinfo ()
Private Attributes
Interpol2D A_
Interpol2D B_
Id originalChanId_
Id originalGateId_
Additional Inherited Members
Protected Attributes inherited from HHGateBase
Id originalChanId_
Id originalGateId_
Detailed Description
Definition at line 15 of file HHGate2D.h.
Constructor & Destructor Documentation
HHGate2D() [1/2]
HHGate2D::HHGate2D ()
Definition at line 103 of file HHGate2D.cpp.
                   : originalChanId_(0), originalGateId_(0)
{
    ;
}
References Id::Id(), originalChanId_, and originalGateId_.
HHGate2D() [2/2]
HHGate2D::HHGate2D (Id originalChanId, Id originalGateId)
Definition at line 108 of file HHGate2D.cpp.
    : HHGateBase(originalChanId, originalGateId)
{
    ;
}
References HHGateBase::HHGateBase().
Referenced by HHChannel2D::innerCreateGate().
Member Function Documentation
checkOriginal()
bool HHGate2D::checkOriginal (Id id, const string & field) const
Checks if the provided Id is the one that the HHGate was created on. If true, fine, otherwise complains about trying to set the field.
getTableA()
vector< vector< double > > HHGate2D::getTableA (const Eref & e) const
Returns the A interpol
Definition at line 161 of file HHGate2D.cpp.
{
    return A_.getTableVector();
}
References A_, and Interpol2D::getTableVector().
Referenced by initCinfo().
getTableB()
vector< vector< double > > HHGate2D::getTableB (const Eref & e) const
Returns the B interpol
Definition at line 171 of file HHGate2D.cpp.
{
    return B_.getTableVector();
}
References B_, and Interpol2D::getTableVector().
Referenced by initCinfo().
getXdivs()
unsigned int HHGate2D::getXdivs (const Eref & e) const
Definition at line 221 of file HHGate2D.cpp.
{
    return A_.getXdivs();
}
References A_, and Interpol2D::getXdivs().
Referenced by initCinfo().
getXmax()
double HHGate2D::getXmax (const Eref & e) const
Definition at line 210 of file HHGate2D.cpp.
{
    return A_.getXmax();
}
References A_, and Interpol2D::getXmax().
Referenced by initCinfo().
getXmin()
double HHGate2D::getXmin (const Eref & e) const
Definition at line 199 of file HHGate2D.cpp.
{
    return A_.getXmin();
}
References A_, and Interpol2D::getXmin().
Referenced by initCinfo().
getYdivs()
unsigned int HHGate2D::getYdivs (const Eref & e) const
Definition at line 254 of file HHGate2D.cpp.
{
    return A_.getYdivs();
}
References A_, and Interpol2D::getYdivs().
Referenced by initCinfo().
getYmax()
double HHGate2D::getYmax (const Eref & e) const
Definition at line 243 of file HHGate2D.cpp.
{
    return A_.getYmax();
}
References A_, and Interpol2D::getYmax().
Referenced by initCinfo().
getYmin()
double HHGate2D::getYmin (const Eref & e) const
Definition at line 232 of file HHGate2D.cpp.
{
    return A_.getYmin();
}
References A_, and Interpol2D::getYmin().
Referenced by initCinfo().
initCinfo()
const Cinfo * HHGate2D::initCinfo () static
Definition at line 18 of file HHGate2D.cpp.
{
    // Field definitions.
    static ReadOnlyLookupValueFinfo<HHGate2D, vector<double>, double> A(
        "A",
        "lookupA: Look up the A gate value from two doubles, passed"
        "in as a vector. Uses linear interpolation in the 2D table"
        "The range of the lookup doubles is predefined based on "
        "knowledge of voltage or conc ranges, and the granularity "
        "is specified by the xmin, xmax, and dx field, and their "
        "y-axis counterparts.",
        &HHGate2D::lookupA);
    static ReadOnlyLookupValueFinfo<HHGate2D, vector<double>, double> B(
        "B", "lookupB: Look up B gate value from two doubles in a vector.",
        &HHGate2D::lookupB);
    static ElementValueFinfo<HHGate2D, vector<vector<double>>> tableA(
        "tableA", "Table of A entries", &HHGate2D::setTableA,
        &HHGate2D::getTableA);
    static ElementValueFinfo<HHGate2D, vector<vector<double>>> tableB(
        "tableB", "Table of B entries", &HHGate2D::setTableB,
        &HHGate2D::getTableB);
    static ElementValueFinfo<HHGate2D, double> xmin(
        "xmin", "Minimum range for lookup", &HHGate2D::setXmin,
        &HHGate2D::getXmin);
    static ElementValueFinfo<HHGate2D, double> xmax(
        "xmax", "Minimum range for lookup", &HHGate2D::setXmax,
        &HHGate2D::getXmax);
    static ElementValueFinfo<HHGate2D, unsigned int> xdivs(
        "xdivs", "Divisions for lookup. Zero means to use linear interpolation",
        &HHGate2D::setXdivs, &HHGate2D::getXdivs);
    static ElementValueFinfo<HHGate2D, double> ymin(
        "ymin", "Minimum range for lookup", &HHGate2D::setYmin,
        &HHGate2D::getYmin);
    static ElementValueFinfo<HHGate2D, double> ymax(
        "ymax", "Minimum range for lookup", &HHGate2D::setYmax,
        &HHGate2D::getYmax);
    static ElementValueFinfo<HHGate2D, unsigned int> ydivs(
        "ydivs", "Divisions for lookup. Zero means to use linear interpolation",
        &HHGate2D::setYdivs, &HHGate2D::getYdivs);
    // DestFinfos
    static Finfo* HHGate2DFinfos[] = {
        &A,       // ReadOnlyLookupValue
        &B,       // ReadOnlyLookupValue
        &tableA,  // ElementValue
        &tableB,  // ElementValue
        &xmin,   &xmax, &xdivs, &ymin, &ymax, &ydivs,
    };
    static string doc[] = {
        "Name",
        "HHGate2D",
        "Author",
        "Niraj Dudani, 2009, NCBS. Updated by Subhasis Ray, 2014, 2024 NCBS.",
        "Description",
        "HHGate2D: Gate for Hodkgin-Huxley type channels, equivalent to the "
        "m and h terms on the Na squid channel and the n term on K. "
        "This takes the voltage and state variable from the channel, "
        "computes the new value of the state variable and a scaling, "
        "depending on gate power, for the conductance. These two "
        "terms are sent right back in a message to the channel.",
    };
    static Dinfo<HHGate2D> dinfo;
    static Cinfo HHGate2DCinfo("HHGate2D", Neutral::initCinfo(), HHGate2DFinfos,
                               sizeof(HHGate2DFinfos) / sizeof(Finfo*), &dinfo,
                               doc, sizeof(doc) / sizeof(string));
    return &HHGate2DCinfo;
}
References Cinfo::Cinfo(), ElementValueFinfo< T, F >::ElementValueFinfo(), getTableA(), getTableB(), getXdivs(), getXmax(), getXmin(), getYdivs(), getYmax(), getYmin(), Neutral::initCinfo(), lookupA(), lookupB(), ReadOnlyLookupValueFinfo< T, L, F >::ReadOnlyLookupValueFinfo(), setTableA(), setTableB(), setXdivs(), setXmax(), setXmin(), setYdivs(), setYmax(), and setYmin().
Referenced by HHChannel2D::initCinfo().
isOriginalChannel()
bool HHGate2D::isOriginalChannel (Id id) const
isOriginalChannel returns true if the provided Id is the Id of the channel on which the HHGate was created.
Definition at line 184 of file HHGate2D.cpp.
{
    return (id == originalChanId_);
}
References Id::operator==(), and originalChanId_.
Referenced by HHChannel2D::checkOriginal().
isOriginalGate()
bool HHGate2D::isOriginalGate (Id id) const
isOriginalChannel returns true if the provided Id is the Id of the Gate created at the same time as the original channel.
Definition at line 189 of file HHGate2D.cpp.
{
    return (id == originalGateId_);
}
References Id::operator==(), and originalGateId_.
lookupA()
double HHGate2D::lookupA (vector< double > v) const
Definition at line 117 of file HHGate2D.cpp.
{
    if(v.size() < 2) {
        cerr << "Error: HHGate2D::getAValue: 2 real numbers needed to lookup "
                "2D table.\n";
        return 0.0;
    }
    if(v.size() > 2) {
        cerr << "Error: HHGate2D::getAValue: Only 2 real numbers needed to "
                "lookup 2D table. "
                "Using only first 2.\n";
    }
    return A_.innerLookup(v[0], v[1]);
}
References A_, and Interpol2D::innerLookup().
Referenced by initCinfo().
lookupB()
double HHGate2D::lookupB (vector< double > v) const
Definition at line 134 of file HHGate2D.cpp.
{
    if(v.size() < 2) {
        cerr << "Error: HHGate2D::getAValue: 2 real numbers needed to lookup "
                "2D table.\n";
        return 0.0;
    }
    if(v.size() > 2) {
        cerr << "Error: HHGate2D::getAValue: Only 2 real numbers needed to "
                "lookup 2D table. "
                "Using only first 2.\n";
    }
    return B_.innerLookup(v[0], v[1]);
}
References B_, and Interpol2D::innerLookup().
Referenced by initCinfo().
lookupBoth()
void HHGate2D::lookupBoth (double v, double c, double * A, double * B) const
Single call to get both A and B values in a single lookup
Definition at line 151 of file HHGate2D.cpp.
{
    *A = A_.innerLookup(v, c);
    *B = B_.innerLookup(v, c);
}
References A_, B_, and Interpol2D::innerLookup().
Referenced by HHChannel2D::vProcess(), and HHChannel2D::vReinit().
originalChannelId()
Id HHGate2D::originalChannelId () const
Returns the Id of the original Channel.
Definition at line 194 of file HHGate2D.cpp.
{
    return originalChanId_;
}
References originalChanId_.
setTableA()
void HHGate2D::setTableA (const Eref & e, vector< vector< double > > value)
Definition at line 166 of file HHGate2D.cpp.
{
    A_.setTableVector(value);
}
References A_, and Interpol2D::setTableVector().
Referenced by initCinfo().
setTableB()
void HHGate2D::setTableB (const Eref & e, vector< vector< double > > value)
Definition at line 176 of file HHGate2D.cpp.
{
    B_.setTableVector(value);
}
References B_, and Interpol2D::setTableVector().
Referenced by initCinfo().
setXdivs()
void HHGate2D::setXdivs (const Eref & e, unsigned int value)
Definition at line 226 of file HHGate2D.cpp.
{
    A_.setXdivs(value);
    B_.setXdivs(value);
}
References A_, B_, and Interpol2D::setXdivs().
Referenced by initCinfo().
setXmax()
void HHGate2D::setXmax (const Eref & e, double value)
Definition at line 215 of file HHGate2D.cpp.
{
    A_.setXmax(value);
    B_.setXmax(value);
}
References A_, B_, and Interpol2D::setXmax().
Referenced by initCinfo().
setXmin()
void HHGate2D::setXmin (const Eref & e, double value)
Definition at line 204 of file HHGate2D.cpp.
{
    A_.setXmin(value);
    B_.setXmin(value);
}
References A_, B_, and Interpol2D::setXmin().
Referenced by initCinfo().
setYdivs()
void HHGate2D::setYdivs (const Eref & e, unsigned int value)
Definition at line 259 of file HHGate2D.cpp.
{
    A_.setYdivs(value);
    B_.setYdivs(value);
}
References A_, B_, and Interpol2D::setYdivs().
Referenced by initCinfo().
setYmax()
void HHGate2D::setYmax (const Eref & e, double value)
Definition at line 248 of file HHGate2D.cpp.
{
    A_.setYmax(value);
    B_.setYmax(value);
}
References A_, B_, and Interpol2D::setYmax().
Referenced by initCinfo().
setYmin()
void HHGate2D::setYmin (const Eref & e, double value)
Definition at line 237 of file HHGate2D.cpp.
{
    A_.setYmin(value);
    B_.setYmin(value);
}
References A_, B_, and Interpol2D::setYmin().
Referenced by initCinfo().
Member Data Documentation
A_
Interpol2D HHGate2D::A_ private
Definition at line 87 of file HHGate2D.h.
Referenced by getTableA(), getXdivs(), getXmax(), getXmin(), getYdivs(), getYmax(), getYmin(), lookupA(), lookupBoth(), setTableA(), setXdivs(), setXmax(), setXmin(), setYdivs(), setYmax(), and setYmin().
B_
Interpol2D HHGate2D::B_ private
Definition at line 88 of file HHGate2D.h.
Referenced by getTableB(), lookupB(), lookupBoth(), setTableB(), setXdivs(), setXmax(), setXmin(), setYdivs(), setYmax(), and setYmin().
originalChanId_
Id HHGate2D::originalChanId_ private
Definition at line 90 of file HHGate2D.h.
Referenced by HHGate2D(), isOriginalChannel(), and originalChannelId().
originalGateId_
Id HHGate2D::originalGateId_ private
Definition at line 91 of file HHGate2D.h.
Referenced by HHGate2D(), and isOriginalGate().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/biophysics/HHGate2D.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/biophysics/HHGate2D.cpp