MOOSE - Multiscale Object Oriented Simulation Environment: SimpleSynHandler Class Reference
SimpleSynHandler Class Reference
#include <SimpleSynHandler.h>
Public Member Functions
void addSpike (unsigned int index, double time, double weight)
unsigned int addSynapse ()
Adds a new synapse, returns its index.
void dropSynapse (unsigned int droppedSynNumber)
double getTopSpike (unsigned int index) const
SimpleSynHandler & operator= (const SimpleSynHandler &other)
SimpleSynHandler ()
unsigned int vGetNumSynapses () const
Synapse * vGetSynapse (unsigned int i)
void vProcess (const Eref &e, ProcPtr p)
void vReinit (const Eref &e, ProcPtr p)
void vSetNumSynapses (unsigned int num)
~SimpleSynHandler ()
Public Member Functions inherited from SynHandlerBase
unsigned int getNumSynapses () const
Synapse * getSynapse (unsigned int i)
void process (const Eref &e, ProcPtr p)
bool rangeWarning (const string &field, double value)
void reinit (const Eref &e, ProcPtr p)
void setNumSynapses (unsigned int num)
SynHandlerBase ()
virtual ~SynHandlerBase ()
Static Public Member Functions
static const Cinfo * initCinfo ()
Static Public Member Functions inherited from SynHandlerBase
static SrcFinfo1< double > * activationOut ()
static const Cinfo * initCinfo ()
Private Attributes
priority_queue< SynEvent, vector< SynEvent >, CompareSynEvent > events_
vector< Synapse > synapses_
Detailed Description
This handles simple synapses without plasticity. It uses a priority queue to manage them. This gets inefficient for large numbers of synapses but is pretty robust.
Definition at line 47 of file SimpleSynHandler.h.
Constructor & Destructor Documentation
SimpleSynHandler()
SimpleSynHandler::SimpleSynHandler ()
Definition at line 43 of file SimpleSynHandler.cpp.
{
    ;
}
~SimpleSynHandler()
SimpleSynHandler::~SimpleSynHandler ()
Definition at line 48 of file SimpleSynHandler.cpp.
{
    ;
}
Member Function Documentation
addSpike()
void SimpleSynHandler::addSpike (unsigned int index, double time, double weight) virtual
Record arrival of a new spike event. The 'time' is time for eventual arrival of the spike, and is typically well in the future. The index specifies which synapse the spike came to.
Implements SynHandlerBase.
Definition at line 86 of file SimpleSynHandler.cpp.
{
    assert(index < synapses_.size());
    events_.push(SynEvent(time, weight));
}
References events_, synapses_, and SynEvent::SynEvent().
addSynapse()
unsigned int SimpleSynHandler::addSynapse () virtual
Adds a new synapse, returns its index.
Implements SynHandlerBase.
Definition at line 121 of file SimpleSynHandler.cpp.
{
    unsigned int newSynIndex = synapses_.size();
    synapses_.resize(newSynIndex + 1);
    synapses_[newSynIndex].setHandler(this);
    return newSynIndex;
}
References Synapse::setHandler(), and synapses_.
dropSynapse()
void SimpleSynHandler::dropSynapse (unsigned int droppedSynNumber) virtual
Drops an existing synapse, triggered by deleteMsg of an input to the child synapse. This is a little messy because we can't change the indices of the other synapses. The Handler has to figure out how to handle the 'holes' in its array of synapses.
Implements SynHandlerBase.
Definition at line 129 of file SimpleSynHandler.cpp.
{
    assert(msgLookup < synapses_.size());
    synapses_[msgLookup].setWeight(-1.0);
}
References Synapse::setWeight(), and synapses_.
getTopSpike()
double SimpleSynHandler::getTopSpike (unsigned int index) const virtual
Implements SynHandlerBase.
Definition at line 92 of file SimpleSynHandler.cpp.
{
    if (events_.empty()) return 0.0;
    return events_.top().time;
}
References events_, and SynEvent::time.
initCinfo()
const Cinfo * SimpleSynHandler::initCinfo () static
Definition at line 17 of file SimpleSynHandler.cpp.
{
    static string doc[] = {
        "Name", "SimpleSynHandler", "Author", "Upi Bhalla", "Description",
        "The SimpleSynHandler handles simple synapses without plasticity. "
        "It uses a priority queue to manage them."};
    static FieldElementFinfo<SynHandlerBase, Synapse> synFinfo(
        "synapse", "Sets up field Elements for synapse", Synapse::initCinfo(),
        &SynHandlerBase::getSynapse, &SynHandlerBase::setNumSynapses,
        &SynHandlerBase::getNumSynapses);
    static Finfo* synHandlerFinfos[] = {&synFinfo  // FieldElement
    };
    static Dinfo<SimpleSynHandler> dinfo;
    static Cinfo synHandlerCinfo("SimpleSynHandler",
                                 SynHandlerBase::initCinfo(), synHandlerFinfos,
                                 sizeof(synHandlerFinfos) / sizeof(Finfo*),
                                 &dinfo, doc, sizeof(doc) / sizeof(string));
    return &synHandlerCinfo;
}
References Cinfo::Cinfo(), FieldElementFinfo< T, F >::FieldElementFinfo(), SynHandlerBase::getNumSynapses(), SynHandlerBase::getSynapse(), Synapse::initCinfo(), SynHandlerBase::initCinfo(), and SynHandlerBase::setNumSynapses().
Referenced by testCinfoFields(), testFinfoFields(), testSetGetSynapse(), testSetGetVec(), testSetRepeat(), and testSparseMsg().
operator=()
SimpleSynHandler & SimpleSynHandler::operator= (const SimpleSynHandler & other)
Definition at line 53 of file SimpleSynHandler.cpp.
{
    synapses_ = ssh.synapses_;
    for (auto i = synapses_.begin(); i != synapses_.end(); ++i)
        i->setHandler(this);
    // For no apparent reason, priority queues don't have a clear operation.
    while (!events_.empty()) events_.pop();
    return *this;
}
References events_, Synapse::setHandler(), and synapses_.
vGetNumSynapses()
unsigned int SimpleSynHandler::vGetNumSynapses () const virtual
Implements SynHandlerBase.
Definition at line 72 of file SimpleSynHandler.cpp.
{
    return synapses_.size();
}
References synapses_.
vGetSynapse()
Synapse * SimpleSynHandler::vGetSynapse (unsigned int i) virtual
Implements SynHandlerBase.
Definition at line 77 of file SimpleSynHandler.cpp.
{
    static Synapse dummy;
    if (i < synapses_.size()) return &synapses_[i];
    cout << "Warning: SimpleSynHandler::getSynapse: index: " << i
         << " is out of range: " << synapses_.size() << endl;
    return &dummy;
}
References synapses_.
vProcess()
void SimpleSynHandler::vProcess (const Eref & e, ProcPtr p) virtual
Implements SynHandlerBase.
Definition at line 98 of file SimpleSynHandler.cpp.
{
    double activation = 0.0;
    while (!events_.empty() && events_.top().time <= p->currTime) {
        // Send out weight / dt for every spike
        //      Since it is an impulse active only for one dt,
        //      need to send it divided by dt.
        // Can connect activation to SynChan (double exp)
        //      or to LIF as an impulse to voltage.
        // See:
        // http://www.genesis-sim.org/GENESIS/Hyperdoc/Manual-26.html#synchan
        activation += events_.top().weight / p->dt;
        events_.pop();
    }
    if (activation != 0.0) SynHandlerBase::activationOut()->send(e, activation);
}
References SynHandlerBase::activationOut(), ProcInfo::currTime, ProcInfo::dt, events_, SrcFinfo1< T >::send(), SynEvent::time, and SynEvent::weight.
vReinit()
void SimpleSynHandler::vReinit (const Eref & e, ProcPtr p) virtual
Implements SynHandlerBase.
Definition at line 115 of file SimpleSynHandler.cpp.
{
    // For no apparent reason, priority queues don't have a clear operation.
    while (!events_.empty()) events_.pop();
}
References events_.
vSetNumSynapses()
void SimpleSynHandler::vSetNumSynapses (unsigned int num) virtual
Implements SynHandlerBase.
Definition at line 65 of file SimpleSynHandler.cpp.
{
    unsigned int prevSize = synapses_.size();
    synapses_.resize(v);
    for (unsigned int i = prevSize; i < v; ++i) synapses_[i].setHandler(this);
}
References Synapse::setHandler(), and synapses_.
Member Data Documentation
events_
priority_queue< SynEvent, vector< SynEvent >, CompareSynEvent > SimpleSynHandler::events_ private
Definition at line 71 of file SimpleSynHandler.h.
Referenced by addSpike(), getTopSpike(), operator=(), vProcess(), and vReinit().
synapses_
vector< Synapse > SimpleSynHandler::synapses_ private
Definition at line 70 of file SimpleSynHandler.h.
Referenced by addSpike(), addSynapse(), dropSynapse(), operator=(), vGetNumSynapses(), vGetSynapse(), and vSetNumSynapses().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/synapse/SimpleSynHandler.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/synapse/SimpleSynHandler.cpp