MOOSE - Multiscale Object Oriented Simulation Environment: FuncTerm Class Reference
FuncTerm Class Reference
#include <FuncTerm.h>
Public Member Functions
void evalPool (double *s, double t) const
FuncTerm ()
const string & getExpr () const
const vector< unsigned int > & getReactantIndex () const
const unsigned int getTarget () const
double getVolScale () const
double operator() (const double *S, double t) const
const FuncTerm & operator= (const FuncTerm &other)
void setExpr (const string &e)
void setReactantIndex (const vector< unsigned int > &mol)
void setTarget (unsigned int tgt)
void setVolScale (double vs)
~FuncTerm ()
Private Attributes
double * args_
Index of the entity to be updated by Func.
string expr_
moose::MooseParser parser_
vector< unsigned int > reactantIndex_
unsigned int target_
double volScale_
Detailed Description
Definition at line 15 of file FuncTerm.h.
Constructor & Destructor Documentation
FuncTerm()
FuncTerm::FuncTerm ()
Definition at line 29 of file FuncTerm.cpp.
                  :
    reactantIndex_(1, 0) , volScale_(1.0) , target_(~0U) , args_(nullptr)
{
}
References args_, reactantIndex_, target_, and volScale_.
Referenced by FuncRate::FuncRate(), and Stoich::installAndUnschedFunc().
~FuncTerm()
FuncTerm::~FuncTerm ()
Definition at line 34 of file FuncTerm.cpp.
{
    if(args_)
        delete[] args_;
}
References args_.
Member Function Documentation
evalPool()
void FuncTerm::evalPool (double * s, double t) const
Definition at line 163 of file FuncTerm.cpp.
{
    if ( !args_ || target_ == ~0U )
        return;
    unsigned int i;
    for ( i = 0; i < reactantIndex_.size(); ++i )
        args_[i] = S[reactantIndex_[i]];
    args_[i] = t;
    try
    {
        S[ target_] = parser_.Eval() * volScale_;
        //assert(! std::isnan(S[target_]));
    }
    catch ( moose::Parser::exception_type & e )
    {
        showError( e );
        return;
    }
}
References args_, moose::MooseParser::Eval(), parser_, reactantIndex_, showError(), target_, and volScale_.
Referenced by Stoich::updateFuncs().
getExpr()
const string & FuncTerm::getExpr () const
Definition at line 101 of file FuncTerm.cpp.
{
    return expr_;
}
References expr_.
Referenced by FuncRate::getExpr().
getReactantIndex()
const vector< unsigned int > & FuncTerm::getReactantIndex () const
Definition at line 62 of file FuncTerm.cpp.
{
    return reactantIndex_;
}
References reactantIndex_.
Referenced by Gsolve::fillPoolFuncDep(), and FuncRate::getFuncArgIndex().
getTarget()
const unsigned int FuncTerm::getTarget () const
Definition at line 111 of file FuncTerm.cpp.
{
    return target_;
}
References target_.
Referenced by FuncRate::copyWithVolScaling(), Gsolve::fillPoolFuncDep(), and FuncRate::getReactants().
getVolScale()
double FuncTerm::getVolScale () const
Definition at line 121 of file FuncTerm.cpp.
{
    return volScale_;
}
References volScale_.
operator()()
double FuncTerm::operator() (const double * S, double t) const
This computes the value. The time t is an argument needed by some functions.
Definition at line 142 of file FuncTerm.cpp.
{
    if ( ! args_ )
        return 0.0;
    unsigned int i = 0;
    for ( i = 0; i < reactantIndex_.size(); ++i )
        args_[i] = S[reactantIndex_[i]];
    args_[i] = t;
    try
    {
        return parser_.Eval() * volScale_;
    }
    catch (moose::Parser::exception_type &e )
    {
        cerr << "Error: " << e.GetMsg() << endl;
        throw e;
    }
}
References args_, moose::MooseParser::Eval(), moose::Parser::ParserException::GetMsg(), parser_, reactantIndex_, and volScale_.
Referenced by FuncRate::operator()(), FuncReac::operator()(), and testFuncTerm().
operator=()
const FuncTerm & FuncTerm::operator= (const FuncTerm & other)
Definition at line 126 of file FuncTerm.cpp.
{
    args_ = nullptr;  // other is still using it.
    expr_ = other.expr_;
    volScale_ = other.volScale_;
    target_ = other.target_;
    reactantIndex_ = other.reactantIndex_;
    parser_ = other.parser_;
    setReactantIndex(reactantIndex_);
    return *this;
}
References args_, expr_, parser_, reactantIndex_, setReactantIndex(), target_, and volScale_.
setExpr()
void FuncTerm::setExpr (const string & expr)
@Synopsis Set expression on FuncTerm. Before calling this function, user should make sure that symbol_table has been linked to pointers to the variables.
@Param expr
Definition at line 82 of file FuncTerm.cpp.
{
    // Empty expression are not allowed.
    if(expr.empty())
        return;
    try
    {
        if(! parser_.SetExpr(expr))
            MOOSE_WARN("Failed to set expression: '" << expr << "'");
        expr_ = expr;
    }
    catch(moose::Parser::exception_type &e)
    {
        showError(e);
        return;
    }
}
References expr_, parser_, moose::MooseParser::SetExpr(), and showError().
Referenced by Stoich::installAndUnschedFunc(), FuncRate::setExpr(), Stoich::setFunctionExpr(), setReactantIndex(), and testFuncTerm().
setReactantIndex()
void FuncTerm::setReactantIndex (const vector< unsigned int > & mol)
This function finds the reactant indices in the vector S. It returns the number of indices found, which are the entries in molIndex.
Definition at line 40 of file FuncTerm.cpp.
{
    reactantIndex_ = mol;
    if ( args_ )
    {
        delete[] args_;
        parser_.ClearAll();
    }
    args_ = new double[mol.size()+1];
    for ( unsigned int i = 0; i < mol.size(); ++i )
    {
        args_[i] = 0.0;
        parser_.DefineVar( 'x'+to_string(i), &args_[i] );
    }
    // Define a 't' variable even if we don't always use it.
    args_[mol.size()] = 0.0;
    parser_.DefineVar( "t", &args_[mol.size()] );
    setExpr(expr_);
}
References args_, moose::MooseParser::ClearAll(), moose::MooseParser::DefineVar(), expr_, parser_, reactantIndex_, and setExpr().
Referenced by Stoich::installAndUnschedFunc(), operator=(), FuncRate::setFuncArgIndex(), and testFuncTerm().
setTarget()
void FuncTerm::setTarget (unsigned int tgt)
Definition at line 106 of file FuncTerm.cpp.
{
    target_ = t;
}
References target_.
Referenced by FuncRate::FuncRate(), Stoich::installAndUnschedFunc(), and FuncRate::setReactants().
setVolScale()
void FuncTerm::setVolScale (double vs)
Definition at line 116 of file FuncTerm.cpp.
{
    volScale_ = vs;
}
References volScale_.
Referenced by Stoich::installAndUnschedFunc().
Member Data Documentation
args_
double* FuncTerm::args_ private
Index of the entity to be updated by Func.
Definition at line 56 of file FuncTerm.h.
Referenced by evalPool(), FuncTerm(), operator()(), operator=(), setReactantIndex(), and ~FuncTerm().
expr_
string FuncTerm::expr_ private
Definition at line 58 of file FuncTerm.h.
Referenced by getExpr(), operator=(), setExpr(), and setReactantIndex().
parser_
moose::MooseParser FuncTerm::parser_ private
Definition at line 59 of file FuncTerm.h.
Referenced by evalPool(), operator()(), operator=(), setExpr(), and setReactantIndex().
reactantIndex_
vector< unsigned int > FuncTerm::reactantIndex_ private
Definition at line 46 of file FuncTerm.h.
Referenced by evalPool(), FuncTerm(), getReactantIndex(), operator()(), operator=(), and setReactantIndex().
target_
unsigned int FuncTerm::target_ private
Definition at line 54 of file FuncTerm.h.
Referenced by evalPool(), FuncTerm(), getTarget(), operator=(), and setTarget().
volScale_
double FuncTerm::volScale_ private
Scale factor to account for pool volume if we are assigning conc rather than N. Note that this conc will not be further updated so this is an undesirable option.
Definition at line 53 of file FuncTerm.h.
Referenced by evalPool(), FuncTerm(), getVolScale(), operator()(), operator=(), and setVolScale().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/ksolve/FuncTerm.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/ksolve/FuncTerm.cpp