MOOSE - Multiscale Object Oriented Simulation Environment: SetGet Class Reference
SetGet Class Reference abstract
#include <SetGet.h>
Public Member Functions
virtual bool checkOpClass (const OpFunc *op) const =0
SetGet ()
virtual ~SetGet ()
Static Public Member Functions
static const OpFunc * checkSet (const string &field, ObjId &tgt, FuncId &fid)
static const vector< double * > * dispatchGet (const ObjId &tgt, FuncId tgtFid, const double *arg, unsigned int size)
Sends out request for data, and awaits its return.
static bool strGet (const ObjId &tgt, const string &field, string &ret)
static bool strSet (const ObjId &dest, const string &field, const string &val)
Detailed Description
Definition at line 56 of file SetGet.h.
Constructor & Destructor Documentation
SetGet()
SetGet::SetGet () inline
Definition at line 59 of file SetGet.h.
    {
        ;
    }
~SetGet()
virtual SetGet::~SetGet () inline virtual
Definition at line 64 of file SetGet.h.
    {
        ;
    }
Member Function Documentation
checkOpClass()
virtual bool SetGet::checkOpClass (const OpFunc * op) const pure virtual
Implemented in SetGet0, and SetGet1< A >.
checkSet()
const OpFunc * SetGet::checkSet (const string & field, ObjId & tgt, FuncId & fid) static
Utility function to check that the target field matches this source type, to look up and pass back the fid, and to return the number of targetEntries. Tgt is passed in as the destination ObjId. May be changed inside, if the function determines that it should be directed to a child Element acting as a Value. Checks arg # and types for a 'set' call. Can be zero to 3 args. Returns # of tgts if good. This is 0 if bad. Passes back found fid.
Definition at line 15 of file SetGet.cpp.
{
    // string field = "set_" + destField;
    const Finfo* f = tgt.element()->cinfo()->findFinfo( field );
    if ( !f )   // Could be a child element? Note that field name will
    {
        // change from set_<name> to just <name>
        string f2 = field.substr( 3 );
        Id child = Neutral::child( tgt.eref(), f2 );
        if ( child == Id() )
        {
            cout << "Error: SetGet:checkSet:: No field or child named '" <<
                 field << "' was found on\n" << tgt.id.path() << endl;
        }
        else
        {
            if ( field.substr( 0, 3 ) == "set" )
                f = child.element()->cinfo()->findFinfo( "setThis" );
            else if ( field.substr( 0, 3 ) == "get" )
                f = child.element()->cinfo()->findFinfo( "getThis" );
            assert( f ); // should always work as Neutral has the field.
            if ( child.element()->numData() == tgt.element()->numData() )
            {
                tgt = ObjId( child, tgt.dataIndex, tgt.fieldIndex );
                if ( !tgt.isDataHere() )
                    return 0;
            }
            else if ( child.element()->numData() <= 1 )
            {
                tgt = ObjId( child, 0 );
                if ( !tgt.isDataHere() )
                    return 0;
            }
            else
            {
                cout << "SetGet::checkSet: child index mismatch\n";
                return 0;
            }
        }
    }
    const DestFinfo* df = dynamic_cast< const DestFinfo* >( f );
    if ( !df )
        return 0;
    fid = df->getFid();
    const OpFunc* func = df->getOpFunc();
    assert( func );
    return func;
}
References Neutral::child(), Element::cinfo(), ObjId::dataIndex, Id::element(), ObjId::element(), ObjId::eref(), ObjId::fieldIndex, Cinfo::findFinfo(), DestFinfo::getFid(), DestFinfo::getOpFunc(), Id::Id(), ObjId::id, ObjId::isDataHere(), Element::numData(), ObjId::ObjId(), Id::operator==(), and Id::path().
Referenced by Field< A >::get(), LookupField< L, A >::get(), LookupField< L, A >::getVec(), Field< A >::getVec(), SetGet0::set(), SetGet1< A >::set(), SetGet2< A1, A2 >::set(), SetGet3< A1, A2, A3 >::set(), SetGet4< A1, A2, A3, A4 >::set(), SetGet5< A1, A2, A3, A4, A5 >::set(), SetGet6< A1, A2, A3, A4, A5, A6 >::set(), SetGet2< A1, A2 >::setVec(), and SetGet1< A >::setVec().
dispatchGet()
static const vector< double * > * SetGet::dispatchGet (const ObjId & tgt, FuncId tgtFid, const double * arg, unsigned int size) static
Sends out request for data, and awaits its return.
strGet()
bool SetGet::strGet (const ObjId & tgt, const string & field, string & ret) static
Blocking 'get' call, returning into a string. There is a matching 'get<T> call, returning appropriate type.
Definition at line 69 of file SetGet.cpp.
{
    const Finfo* f = tgt.element()->cinfo()->findFinfo( field );
    if(!f) {
#ifndef NDEBUG
        cout << Shell::myNode() << ": Error: SetGet::strGet: Field " << field
             << " not found on Element " << tgt.element()->getName() << endl;
#endif
        return 0;
    }
    return f->strGet( tgt.eref(), field, ret );
}
References Element::cinfo(), ObjId::element(), ObjId::eref(), Cinfo::findFinfo(), Element::getName(), Shell::myNode(), and Finfo::strGet().
Referenced by testStrGet(), and wildcardFieldComparison().
strSet()
bool SetGet::strSet (const ObjId & dest, const string & field, const string & val) static
Blocking 'set' call, using automatic string conversion There is a matching blocking set call with typed arguments.
Definition at line 83 of file SetGet.cpp.
{
    const Finfo* f = tgt.element()->cinfo()->findFinfo( field );
    if ( !f )
    {
        cout << Shell::myNode() << ": Error: SetGet::strSet: Field " <<
             field << " not found on Element " << tgt.element()->getName() <<
             endl;
        return 0;
    }
    return f->strSet( tgt.eref(), field, v );
}
References Element::cinfo(), ObjId::element(), ObjId::eref(), Cinfo::findFinfo(), Element::getName(), Shell::myNode(), and Finfo::strSet().
Referenced by testStrSet().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/basecode/SetGet.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/basecode/SetGet.cpp