MOOSE - Multiscale Object Oriented Simulation Environment: DinfoBase Class Reference
DinfoBase Class Reference abstract
#include <Dinfo.h>
Public Member Functions
virtual char * allocData (unsigned int numData) const =0
virtual void assignData (char *copy, unsigned int copyEntries, const char *orig, unsigned int origEntries) const =0
virtual char * copyData (const char *orig, unsigned int origEntries, unsigned int copyEntries, unsigned int startEntry) const =0
virtual void destroyData (char *d) const =0
DinfoBase ()
DinfoBase (bool isOneZombie)
virtual bool isA (const DinfoBase *other) const =0
bool isOneZombie () const
virtual unsigned int size () const =0
virtual unsigned int sizeIncrement () const =0
virtual ~DinfoBase ()
Private Attributes
const bool isOneZombie_
Detailed Description
Definition at line 12 of file Dinfo.h.
Constructor & Destructor Documentation
DinfoBase() [1/2]
DinfoBase::DinfoBase () inline
Definition at line 15 of file Dinfo.h.
            : isOneZombie_( 0 )
        {;}
References isOneZombie_.
DinfoBase() [2/2]
DinfoBase::DinfoBase (bool isOneZombie) inline
Definition at line 18 of file Dinfo.h.
            : isOneZombie_( isOneZombie )
        {;}
References isOneZombie_.
~DinfoBase()
virtual DinfoBase::~DinfoBase () inline virtual
Definition at line 21 of file Dinfo.h.
        {;}
Member Function Documentation
allocData()
virtual char * DinfoBase::allocData (unsigned int numData) const pure virtual
Implemented in Dinfo< D >.
Referenced by DataElement::DataElement(), and DataElement::zombieSwap().
assignData()
virtual void DinfoBase::assignData (char * copy, unsigned int copyEntries, const char * orig, unsigned int origEntries) const pure virtual
Assigns data contents from 'orig' over to 'copy'. Tiles the origEntries onto the copyEntries. So if there are fewer origEntries, the orig data contents are repeated till the copy is full.
Implemented in Dinfo< D >.
Referenced by buildFinfoElement(), and Cinfo::makeCinfoElements().
copyData()
virtual char * DinfoBase::copyData (const char * orig, unsigned int origEntries, unsigned int copyEntries, unsigned int startEntry) const pure virtual
Return a newly allocated copy of the original data, repeated copyEntries times. Orig data untouched. Analogous to copying a vector into a bigger one. Repeat the original data as many times as possible.
Implemented in Dinfo< D >.
Referenced by DataElement::DataElement(), and DataElement::resize().
destroyData()
virtual void DinfoBase::destroyData (char * d) const pure virtual
Implemented in Dinfo< D >.
Referenced by DataElement::resize(), DataElement::zombieSwap(), and DataElement::~DataElement().
isA()
virtual bool DinfoBase::isA (const DinfoBase * other) const pure virtual
Implemented in Dinfo< D >.
isOneZombie()
bool DinfoBase::isOneZombie () const inline
Definition at line 53 of file Dinfo.h.
{
            return isOneZombie_;
        }
References isOneZombie_.
Referenced by Dinfo< D >::assignData(), and Dinfo< D >::copyData().
size()
virtual unsigned int DinfoBase::size () const pure virtual
Implemented in Dinfo< D >, and ZeroSizeDinfo< D >.
sizeIncrement()
virtual unsigned int DinfoBase::sizeIncrement () const pure virtual
Implemented in Dinfo< D >, and ZeroSizeDinfo< D >.
Referenced by DataElement::DataElement(), DataElement::DataElement(), and DataElement::zombieSwap().
Member Data Documentation
isOneZombie_
const bool DinfoBase::isOneZombie_ private
Definition at line 57 of file Dinfo.h.
Referenced by DinfoBase(), DinfoBase(), and isOneZombie().
The documentation for this class was generated from the following file:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/basecode/Dinfo.h