MOOSE - Multiscale Object Oriented Simulation Environment: EndoMesh Class Reference
EndoMesh Class Reference
#include <EndoMesh.h>
Public Member Functions
EndoMesh ()
double extendedMeshEntryVolume (unsigned int fid) const
Volume of mesh Entry including abutting diff-coupled voxels.
double getApower (const Eref &e) const
double getAscale (const Eref &e) const
vector< double > getCoordinates (unsigned int fid) const
Virtual function to return coords of mesh Entry.
vector< double > getDiffusionArea (unsigned int fid) const
Virtual function to return diffusion X-section area.
vector< double > getDiffusionScaling (unsigned int fid) const
Virtual function to return scale factor for diffusion. 1 here.
bool getDoAxialDiffusion (const Eref &e) const
vector< Id > getElecComptMap () const
unsigned int getMeshDimensions (unsigned int fid) const
Virtual function to return dimensions of specified entry.
double getMeshEntryVolume (unsigned int fid) const
Virtual function to return volume of mesh Entry.
unsigned int getMeshType (unsigned int fid) const
Virtual function to return MeshType of specified entry.
vector< unsigned int > getParentVoxel () const
Inherited virtual, do nothing for now.
double getRpower (const Eref &e) const
double getRscale (const Eref &e) const
ObjId getSurround (const Eref &e) const
const vector< double > & getVoxelArea () const
const vector< double > & getVoxelLength () const
double getVpower (const Eref &e) const
double getVscale (const Eref &e) const
void indexToSpace (unsigned int index, double &x, double &y, double &z) const
void innerBuildDefaultMesh (const Eref &e, double volume, unsigned int numEntries)
Virtual func to make a mesh with specified Volume and numEntries.
unsigned int innerGetDimensions () const
Virtual function to return # of spatial dimensions of mesh.
unsigned int innerGetNumEntries () const
void innerHandleNodeInfo (const Eref &e, unsigned int numNodes, unsigned int numThreads)
void innerHandleRequestMeshStats (const Eref &e, const SrcFinfo2< unsigned int, vector< double > > *meshStatsFinfo)
More inherited virtual funcs: request comes in for mesh stats.
void innerSetNumEntries (unsigned int n)
Inherited virtual func.
void matchMeshEntries (const ChemCompt *other, vector< VoxelJunction > &ret) const
double nearest (double x, double y, double z, unsigned int &index) const
void setApower (const Eref &e, double v)
void setAscale (const Eref &e, double v)
void setDoAxialDiffusion (const Eref &e, bool v)
void setRpower (const Eref &e, double v)
void setRscale (const Eref &e, double v)
void setSurround (const Eref &e, ObjId v)
void setVpower (const Eref &e, double v)
void setVscale (const Eref &e, double v)
double vGetEntireVolume () const
Inherited virtual. Returns entire volume of compartment.
const vector< double > & vGetVoxelMidpoint () const
Virtual func so that derived classes can return voxel midpoint.
const vector< double > & vGetVoxelVolume () const
Virtual func so that derived classes can pass voxel volume back.
bool vSetVolumeNotRates (double volume)
Inherited virtual. Resizes len and dia of each voxel.
~EndoMesh ()
Public Member Functions inherited from MeshCompt
void addRow (unsigned int index, const vector< double > &entry, const vector< unsigned int > &colIndex)
void clearExtendedMeshEntryVolume ()
Inherited virtual function to clear the vector of MeshEntryVolume.
double extendedMeshEntryVolume (unsigned int fid) const
Virtual function to return volume of mesh Entry, including.
void extendStencil (const ChemCompt *other, const vector< VoxelJunction > &vj)
Add boundary voxels to stencil for cross-solver junctions.
vector< unsigned int > getNeighbors (unsigned int fid) const
Looks up stencil to return vector of indices of coupled voxels.
const SparseMatrix< double > & getStencil () const
Returns entire sparse matrix of mesh. Used by diffusion solver.
unsigned int getStencilRow (unsigned int meshIndex, const double **entry, const unsigned int **colIndex) const
vector< double > innerGetStencilRate (unsigned int row) const
void innerResetStencil ()
virtual func implemented here.
MeshCompt ()
void setStencilSize (unsigned int numRows, unsigned int numCols)
~MeshCompt ()
Public Member Functions inherited from ChemCompt
void buildDefaultMesh (const Eref &e, double volume, unsigned int numEntries)
void buildJunction (ChemCompt *other, vector< VoxelJunction > &ret)
ChemCompt ()
void flipRet (vector< VoxelJunction > &ret) const
Utility function for swapping first and second in VoxelJunctions.
void getChildConcs (const Eref &e, vector< double > &childConcs) const
unsigned int getDimensions () const
double getEntireVolume (const Eref &e) const
bool getIsMembraneBound () const
string getMethod () const
unsigned int getNumEntries () const
vector< double > getOneVoxelMidpoint (unsigned int vox) const
Looks up specified voxel midpoint, from vGetVoxelMidpoint.
double getOneVoxelVolume (const Eref &e, unsigned int voxel) const
vector< unsigned int > getStencilIndex (unsigned int row) const
vector< double > getStencilRate (unsigned int row) const
vector< double > getVoxelMidpoint () const
Returns vector of all voxel midpoints in compartment.
vector< double > getVoxelVolume () const
Returns vector of all voxel volumes in compartment.
void handleNodeInfo (const Eref &e, unsigned int numNodes, unsigned int numThreads)
MeshEntry * lookupEntry (unsigned int index)
void resetStencil ()
unsigned int setChildConcs (const Eref &e, const vector< double > &childConcs, unsigned int start) const
void setEntireVolume (const Eref &e, double volume)
void setIsMembraneBound (bool v)
virtual void setMeshEntryVolume (unsigned int fid, double volume)
void setMethod (string method)
void setNumEntries (unsigned int num)
void setOneVoxelVolume (const Eref &e, unsigned int voxel, double volume)
void setVolumeNotRates (double volume)
virtual ~ChemCompt ()
Static Public Member Functions
static const Cinfo * initCinfo ()
Static Public Member Functions inherited from ChemCompt
static double distance (double x, double y, double z)
static const Cinfo * initCinfo ()
static SrcFinfo1< vector< double > > * voxelVolOut ()
Private Attributes
double aPower_
rEndo = rScale * pow(surroundVol, rPower_)
double aScale_
aEndo = aScale * pow(surroundVol, aPower_)
bool doAxialDiffusion_
vEndo = vScale * pow(surroundVol, vPower_)
Id insideMeshes_
const MeshCompt * parent_
double rPower_
EndoMeshes inside. Used to update.
double rScale_
rEndo = rScale * pow(surroundVol, rPower_)
ObjId surround_
double vPower_
aEndo = aScale * pow(surroundVol, aPower_)
double vScale_
vEndo = vScale * pow(surroundVol, vPower_)
Detailed Description
The EndoMesh is a cellular compartment entirely contained within another compartment. It supports diffusion only with its immediate surround, of which there can only be one, and with its immediate interior, which can be one or more EndoMeshes. Each voxel in the EndoMesh is well mixed, and does not exchange with any other voxels. Typically used in modelling endosomes, ER, mitochondria, and other organelles.
Definition at line 23 of file EndoMesh.h.
Constructor & Destructor Documentation
EndoMesh()
EndoMesh::EndoMesh ()
Definition at line 149 of file EndoMesh.cpp.
    :
        parent_( &defaultParent ),
        rPower_( 1.0 / 3.0 ),
        rScale_( 0.5 ),
        aPower_( 0.5 ),
        aScale_( 0.25 ),
        vPower_( 1.0 ),
        vScale_( 0.125 ),
        doAxialDiffusion_( false )
{
    ;
}
References aPower_, aScale_, defaultParent, doAxialDiffusion_, parent_, rPower_, rScale_, vPower_, and vScale_.
~EndoMesh()
EndoMesh::~EndoMesh ()
Definition at line 163 of file EndoMesh.cpp.
{
    ;
}
Member Function Documentation
extendedMeshEntryVolume()
double EndoMesh::extendedMeshEntryVolume (unsigned int fid) const virtual
Volume of mesh Entry including abutting diff-coupled voxels.
Virtual function to return volume of mesh Entry, including for diffusively coupled voxels from other solvers.
Implements ChemCompt.
Definition at line 325 of file EndoMesh.cpp.
{
    double vpa = parent_->extendedMeshEntryVolume( fid );
    return vScale_ * pow( vpa, vPower_ );
}
References MeshCompt::extendedMeshEntryVolume(), parent_, vPower_, and vScale_.
getApower()
double EndoMesh::getApower (const Eref & e) const
Definition at line 198 of file EndoMesh.cpp.
{
    return aPower_;
}
References aPower_.
Referenced by initCinfo().
getAscale()
double EndoMesh::getAscale (const Eref & e) const
Definition at line 208 of file EndoMesh.cpp.
{
    return aScale_;
}
References aScale_.
Referenced by initCinfo().
getCoordinates()
vector< double > EndoMesh::getCoordinates (unsigned int fid) const virtual
Virtual function to return coords of mesh Entry.
Virtual function to return coords of mesh Entry. For Endo mesh, coords are middle of parent followed by radius.
Implements ChemCompt.
Definition at line 294 of file EndoMesh.cpp.
{
    vector< double > temp = parent_->getCoordinates( fid );
    vector< double > ret;
    double vol = getMeshEntryVolume( fid );
    if ( temp.size() > 6 ) {
        ret.resize( 4 );
        ret[0] = 0.5 * (temp[0] + temp[3] );
        ret[1] = 0.5 * (temp[1] + temp[4] );
        ret[2] = 0.5 * (temp[2] + temp[5] );
        ret[3] = 2.0 * pow( vol*3.0/(4.0 * PI), 1.0/3.0 ); // Assume sphere
    }
    return ret;
}
References ChemCompt::getCoordinates(), getMeshEntryVolume(), parent_, and PI.
getDiffusionArea()
vector< double > EndoMesh::getDiffusionArea (unsigned int fid) const virtual
Virtual function to return diffusion X-section area.
Virtual function to return diffusion X-section area for each neighbor This applies if we have endo mesh voxels diffusing with each other
Implements ChemCompt.
Definition at line 311 of file EndoMesh.cpp.
{
    return vector< double >( parent_->getNumEntries(), 0.0 );
}
References ChemCompt::getNumEntries(), and parent_.
getDiffusionScaling()
vector< double > EndoMesh::getDiffusionScaling (unsigned int fid) const virtual
Virtual function to return scale factor for diffusion. 1 here.
Virtual function to return scale factor for diffusion. 1 here. This applies if we have endo mesh voxels diffusing with each other
Implements ChemCompt.
Definition at line 318 of file EndoMesh.cpp.
{
    return vector< double >( parent_->getNumEntries(), 0.0 );
}
References ChemCompt::getNumEntries(), and parent_.
getDoAxialDiffusion()
bool EndoMesh::getDoAxialDiffusion (const Eref & e) const
Definition at line 254 of file EndoMesh.cpp.
{
    return doAxialDiffusion_;
}
References doAxialDiffusion_.
Referenced by initCinfo().
getElecComptMap()
vector< Id > EndoMesh::getElecComptMap () const
Definition at line 259 of file EndoMesh.cpp.
{
    return Field< vector < Id > >::get( surround_, "elecComptMap" );
}
References Field< A >::get(), and surround_.
Referenced by initCinfo().
getMeshDimensions()
unsigned int EndoMesh::getMeshDimensions (unsigned int fid) const virtual
Virtual function to return dimensions of specified entry.
Implements ChemCompt.
Definition at line 275 of file EndoMesh.cpp.
{
    return 3;
}
getMeshEntryVolume()
double EndoMesh::getMeshEntryVolume (unsigned int fid) const virtual
Virtual function to return volume of mesh Entry.
Implements ChemCompt.
Definition at line 286 of file EndoMesh.cpp.
{
    double vpa = parent_->getMeshEntryVolume( fid );
    return vScale_ * pow( vpa, vPower_ );
}
References ChemCompt::getMeshEntryVolume(), parent_, vPower_, and vScale_.
Referenced by getCoordinates().
getMeshType()
unsigned int EndoMesh::getMeshType (unsigned int fid) const virtual
Virtual function to return MeshType of specified entry.
Implements ChemCompt.
Definition at line 269 of file EndoMesh.cpp.
{
    return ENDO;
}
References ENDO.
getParentVoxel()
vector< unsigned int > EndoMesh::getParentVoxel () const virtual
Inherited virtual, do nothing for now.
This means the sibling voxel immediately adjacent to it, not the voxel surrounding it. Should we wish to do diffusion we would need to use the parent voxel of the surround voxel. Otherewise use EMTPY_VOXEL == -1U.
Implements MeshCompt.
Definition at line 379 of file EndoMesh.cpp.
{
    if ( doAxialDiffusion_ )
        return parent_->getParentVoxel();
    vector< unsigned int > ret( parent_->innerGetNumEntries(), ~0U );
    return ret;
}
References doAxialDiffusion_, MeshCompt::getParentVoxel(), ChemCompt::innerGetNumEntries(), and parent_.
getRpower()
double EndoMesh::getRpower (const Eref & e) const
Definition at line 177 of file EndoMesh.cpp.
{
    return rPower_;
}
References rPower_.
Referenced by initCinfo().
getRscale()
double EndoMesh::getRscale (const Eref & e) const
Definition at line 188 of file EndoMesh.cpp.
{
    return rScale_;
}
References rScale_.
Referenced by initCinfo().
getSurround()
ObjId EndoMesh::getSurround (const Eref & e) const
Definition at line 244 of file EndoMesh.cpp.
{
    return surround_;
}
References surround_.
Referenced by initCinfo().
getVoxelArea()
const vector< double > & EndoMesh::getVoxelArea () const virtual
Implements MeshCompt.
Definition at line 402 of file EndoMesh.cpp.
{
    static vector< double > ret;
    ret = parent_->vGetVoxelVolume();
    for ( auto i = ret.begin(); i != ret.end(); ++i )
        *i = aScale_ * pow( *i, aPower_ );
    return ret;
}
References aPower_, aScale_, parent_, and ChemCompt::vGetVoxelVolume().
Referenced by matchMeshEntries().
getVoxelLength()
const vector< double > & EndoMesh::getVoxelLength () const virtual
Implements MeshCompt.
Definition at line 411 of file EndoMesh.cpp.
{
    static vector< double > ret;
    ret = parent_->vGetVoxelVolume();
    for ( auto i = ret.begin(); i != ret.end(); ++i )
        *i = vScale_ * pow( *i, vPower_ );
    return ret;
}
References parent_, ChemCompt::vGetVoxelVolume(), vPower_, and vScale_.
getVpower()
double EndoMesh::getVpower (const Eref & e) const
Definition at line 218 of file EndoMesh.cpp.
{
    return vPower_;
}
References vPower_.
Referenced by initCinfo().
getVscale()
double EndoMesh::getVscale (const Eref & e) const
Definition at line 228 of file EndoMesh.cpp.
{
    return vScale_;
}
References vScale_.
Referenced by initCinfo().
indexToSpace()
void EndoMesh::indexToSpace (unsigned int index, double & x, double & y, double & z) const virtual
Converts specified index to xyz coords of middle of voxel Values out of range return original xyz
Implements ChemCompt.
Definition at line 478 of file EndoMesh.cpp.
{
    parent_->indexToSpace( index, x, y, z );
}
References ChemCompt::indexToSpace(), and parent_.
initCinfo()
const Cinfo * EndoMesh::initCinfo () static
Definition at line 29 of file EndoMesh.cpp.
{
        // Field Definitions
        static ElementValueFinfo< EndoMesh, double > rPower(
            "rPower",
            "Used in rEndo = rScale * pow(surroundVol, rPower)."
            "Used to obtain radius of each endo voxel from matching "
            "surround voxel. Defaults to 1/3",
            &EndoMesh::setRpower,
            &EndoMesh::getRpower
        );
        static ElementValueFinfo< EndoMesh, double > rScale(
            "rScale",
            "Used in rEndo = rScale * pow(surroundVol, rPower)."
            "Used to obtain radius of each endo voxel from matching "
            "surround voxel. Defaults to 0.5",
            &EndoMesh::setRscale,
            &EndoMesh::getRscale
        );
        static ElementValueFinfo< EndoMesh, double > aPower(
            "aPower",
            "Used in rEndo = aScale * pow(surroundVol, aPower)."
            "Used to obtain area of each endo voxel from matching "
            "surround voxel. Defaults to 1/2",
            &EndoMesh::setApower,
            &EndoMesh::getApower
        );
        static ElementValueFinfo< EndoMesh, double > aScale(
            "aScale",
            "Used in rEndo = aScale * pow(surroundVol, aPower)."
            "Used to obtain area of each endo voxel from matching "
            "surround voxel. Defaults to 0.25",
            &EndoMesh::setAscale,
            &EndoMesh::getAscale
        );
        static ElementValueFinfo< EndoMesh, double > vPower(
            "vPower",
            "Used in rEndo = vScale * pow(surroundVol, vPower)."
            "Used to obtain volume of each endo voxel from matching "
            "surround voxel. Defaults to 1.",
            &EndoMesh::setVpower,
            &EndoMesh::getVpower
        );
        static ElementValueFinfo< EndoMesh, double > vScale(
            "vScale",
            "Used in rEndo = vScale * pow(surroundVol, vPower)."
            "Used to obtain volume of each endo voxel from matching "
            "surround voxel. Defaults to 0.125",
            &EndoMesh::setVscale,
            &EndoMesh::getVscale
        );
        static ElementValueFinfo< EndoMesh, ObjId > surround(
            "surround",
            "ObjId of compartment surrounding current EndoMesh",
            &EndoMesh::setSurround,
            &EndoMesh::getSurround
        );
        static ElementValueFinfo< EndoMesh, bool > doAxialDiffusion(
            "doAxialDiffusion",
            "Flag to determine if endoMesh should undertake axial "
            "diffusion. Defaults to 'false'. "
            "Should only be used within NeuroMesh and CylMesh. "
            "Must be assigned before Dsolver is built.",
            &EndoMesh::setDoAxialDiffusion,
            &EndoMesh::getDoAxialDiffusion
        );
        static ReadOnlyValueFinfo< EndoMesh, vector< Id > > elecComptMap(
            "elecComptMap",
            "Vector of Ids of electrical compartments that map to each "
            "voxel. This function simply asks the surround mesh for this.",
            &EndoMesh::getElecComptMap
        );
        // MsgDest Definitions
        // Field Elements
    static Finfo* endoMeshFinfos[] = {
        &rPower,            // Value
        &rScale,            // Value
        &aPower,            // Value
        &aScale,            // Value
        &vPower,            // Value
        &vScale,            // Value
        &surround,          // Value
        &doAxialDiffusion,  // Value
        &elecComptMap,      // ReadOnlyValue
    };
    static Dinfo< EndoMesh > dinfo;
    static Cinfo endoMeshCinfo (
        "EndoMesh",
        ChemCompt::initCinfo(),
        endoMeshFinfos,
        sizeof( endoMeshFinfos ) / sizeof ( Finfo* ),
        &dinfo
    );
    return &endoMeshCinfo;
}
References Cinfo::Cinfo(), ElementValueFinfo< T, F >::ElementValueFinfo(), getApower(), getAscale(), getDoAxialDiffusion(), getElecComptMap(), getRpower(), getRscale(), getSurround(), getVpower(), getVscale(), ChemCompt::initCinfo(), ReadOnlyValueFinfo< T, F >::ReadOnlyValueFinfo(), setApower(), setAscale(), setDoAxialDiffusion(), setRpower(), setRscale(), setSurround(), setVpower(), and setVscale().
innerBuildDefaultMesh()
void EndoMesh::innerBuildDefaultMesh (const Eref & e, double volume, unsigned int numEntries) virtual
Virtual func to make a mesh with specified Volume and numEntries.
Implements ChemCompt.
Definition at line 368 of file EndoMesh.cpp.
{
}
innerGetDimensions()
unsigned int EndoMesh::innerGetDimensions () const virtual
Virtual function to return # of spatial dimensions of mesh.
Implements ChemCompt.
Definition at line 281 of file EndoMesh.cpp.
{
    return 3;
}
innerGetNumEntries()
unsigned int EndoMesh::innerGetNumEntries () const virtual
Inherited virtual func. Returns number of MeshEntry in array
Implements ChemCompt.
Definition at line 354 of file EndoMesh.cpp.
{
    return parent_->innerGetNumEntries();
}
References ChemCompt::innerGetNumEntries(), and parent_.
innerHandleNodeInfo()
void EndoMesh::innerHandleNodeInfo (const Eref & e, unsigned int numNodes, unsigned int numThreads) virtual
Implements ChemCompt.
Definition at line 344 of file EndoMesh.cpp.
{
}
innerHandleRequestMeshStats()
void EndoMesh::innerHandleRequestMeshStats (const Eref & e, const SrcFinfo2< unsigned int, vector< double > > * meshStatsFinfo)
More inherited virtual funcs: request comes in for mesh stats.
Definition at line 336 of file EndoMesh.cpp.
{
    vector< double > ret( static_cast<unsigned int>(vGetEntireVolume() / parent_->getNumEntries()), 1);
    meshStatsFinfo->send( e, 1, ret );
}
References ChemCompt::getNumEntries(), parent_, SrcFinfo2< T1, T2 >::send(), and vGetEntireVolume().
innerSetNumEntries()
void EndoMesh::innerSetNumEntries (unsigned int n) virtual
Inherited virtual func.
Inherited virtual func. Dummy, because the EndoMesh just does what its parent does.
Implements ChemCompt.
Definition at line 363 of file EndoMesh.cpp.
{
}
matchMeshEntries()
void EndoMesh::matchMeshEntries (const ChemCompt * other, vector< VoxelJunction > & ret) const virtual
Returns the meshIndices (NOT spatial indices) of all adjacent mesh entry pairs on ether side of the (self, other) junction. meshIndices are the indices that look up entries in the vector of pools. spatialIndices are (iz * ny + iy) * nx + ix, that is, a linear conversion of cartesian spatial indices. So, for two touching cubes, the return vector is the paired meshIndices on either side of the plane of contact. If one mesh has a finer mesh than the other, or if there are more than one contact points from self to other (for example, at a corner), then we just have multiple pairs using the same meshIndex of the repeated voxel.
Consider concentric EndoMeshes in an outer cyl/sphere of radius r_0. Radii, from out to in, are r_0, r_1, r_2.... r_innermost. Consider that we are on EndoMesh n. The diffusion length in each case is 1/2(r_n-1 - r_n+1). For the innermost we use r_n+1 = 0 The diffusion XA is the area of the EndoMesh.
Implements ChemCompt.
Definition at line 438 of file EndoMesh.cpp.
{
    vector< double > vol = other->vGetVoxelVolume();
    const MeshCompt* mc = static_cast< const MeshCompt* >( other );
    vector< double > len = mc->getVoxelLength();
    assert( vol.size() == len.size() );
    ret.resize( vol.size() );
    vector< double > myVol = vGetVoxelVolume();
    assert( myVol.size() == vol.size() );
    vector< double > myArea = getVoxelArea();
    assert( myArea.size() == vol.size() );
    for ( unsigned int i = 0; i < vol.size(); ++i ) {
        double rSurround = sqrt( vol[i] / (len[i] * PI ) );
        ret[i].first = ret[i].second = i;
        ret[i].firstVol = myVol[i];
        ret[i].secondVol = vol[i];
        // For now we don't consider internal EndoMeshes.
        ret[i].diffScale = 2.0 * myArea[i] / rSurround;
    }
}
References VoxelJunction::diffScale, VoxelJunction::first, VoxelJunction::firstVol, getVoxelArea(), MeshCompt::getVoxelLength(), PI, VoxelJunction::second, VoxelJunction::secondVol, vGetVoxelVolume(), and ChemCompt::vGetVoxelVolume().
Referenced by CylMesh::matchMeshEntries(), CubeMesh::matchMeshEntries(), and NeuroMesh::matchMeshEntries().
nearest()
double EndoMesh::nearest (double x, double y, double z, unsigned int & index) const virtual
Returns distance and index of nearest mesh entry. Computes each mesh entry position as its geometric centre. If the current location is not inside a valid mesh entry, distance returned is negative.
Implements ChemCompt.
Definition at line 471 of file EndoMesh.cpp.
{
    return parent_->nearest( x, y, z, index );
}
References ChemCompt::nearest(), and parent_.
setApower()
void EndoMesh::setApower (const Eref & e, double v)
Definition at line 193 of file EndoMesh.cpp.
{
    aPower_ = v;
}
References aPower_.
Referenced by initCinfo().
setAscale()
void EndoMesh::setAscale (const Eref & e, double v)
Definition at line 203 of file EndoMesh.cpp.
{
    aScale_ = v;
}
References aScale_.
Referenced by initCinfo().
setDoAxialDiffusion()
void EndoMesh::setDoAxialDiffusion (const Eref & e, bool v)
Definition at line 249 of file EndoMesh.cpp.
{
    doAxialDiffusion_ = v;
}
References doAxialDiffusion_.
Referenced by initCinfo().
setRpower()
void EndoMesh::setRpower (const Eref & e, double v)
Definition at line 172 of file EndoMesh.cpp.
{
    rPower_ = v;
}
References rPower_.
Referenced by initCinfo().
setRscale()
void EndoMesh::setRscale (const Eref & e, double v)
Definition at line 182 of file EndoMesh.cpp.
{
    rScale_ = v;
    vScale_ = pow( rScale_, 1.0/rPower_ );
}
References rPower_, rScale_, and vScale_.
Referenced by initCinfo().
setSurround()
void EndoMesh::setSurround (const Eref & e, ObjId v)
Definition at line 233 of file EndoMesh.cpp.
{
    if ( !v.element()->cinfo()->isA( "ChemCompt" ) ) {
        cout << "Warning: 'surround' may only be set to an object of class 'ChemCompt'\n";
        cout << v.path() << " is of class " << v.element()->cinfo()->name() << endl;
        return;
    }
    surround_ = v;
    parent_ = reinterpret_cast< const MeshCompt* >( v.data() );
}
References Element::cinfo(), ObjId::data(), ObjId::element(), Cinfo::isA(), Cinfo::name(), parent_, ObjId::path(), and surround_.
Referenced by initCinfo().
setVpower()
void EndoMesh::setVpower (const Eref & e, double v)
Definition at line 213 of file EndoMesh.cpp.
{
    vPower_ = v;
}
References vPower_.
Referenced by initCinfo().
setVscale()
void EndoMesh::setVscale (const Eref & e, double v)
Definition at line 223 of file EndoMesh.cpp.
{
    vScale_ = v;
}
References vScale_.
Referenced by initCinfo().
vGetEntireVolume()
double EndoMesh::vGetEntireVolume () const virtual
Inherited virtual. Returns entire volume of compartment.
Implements ChemCompt.
Definition at line 420 of file EndoMesh.cpp.
{
    double vol = 0.0;
    auto vec = vGetVoxelVolume();
    for ( auto i = vec.begin(); i != vec.end(); ++i )
        vol += *i;
    return vol;
}
References vGetVoxelVolume().
Referenced by innerHandleRequestMeshStats().
vGetVoxelMidpoint()
const vector< double > & EndoMesh::vGetVoxelMidpoint () const virtual
Virtual func so that derived classes can return voxel midpoint.
Implements ChemCompt.
Definition at line 397 of file EndoMesh.cpp.
{
    return parent_->vGetVoxelMidpoint();
}
References parent_, and ChemCompt::vGetVoxelMidpoint().
vGetVoxelVolume()
const vector< double > & EndoMesh::vGetVoxelVolume () const virtual
Virtual func so that derived classes can pass voxel volume back.
Implements ChemCompt.
Definition at line 388 of file EndoMesh.cpp.
{
    static vector< double > ret;
    ret = parent_->vGetVoxelVolume();
    for ( auto i = ret.begin(); i != ret.end(); ++i )
        *i = vScale_ * pow( *i, vPower_ );
    return ret;
}
References parent_, ChemCompt::vGetVoxelVolume(), vPower_, and vScale_.
Referenced by matchMeshEntries(), and vGetEntireVolume().
vSetVolumeNotRates()
bool EndoMesh::vSetVolumeNotRates (double volume) virtual
Inherited virtual. Resizes len and dia of each voxel.
Implements ChemCompt.
Definition at line 429 of file EndoMesh.cpp.
{
    return true; // maybe should be false? Unsure
}
Member Data Documentation
aPower_
double EndoMesh::aPower_ private
rEndo = rScale * pow(surroundVol, rPower_)
Definition at line 143 of file EndoMesh.h.
Referenced by EndoMesh(), getApower(), getVoxelArea(), and setApower().
aScale_
double EndoMesh::aScale_ private
aEndo = aScale * pow(surroundVol, aPower_)
Definition at line 144 of file EndoMesh.h.
Referenced by EndoMesh(), getAscale(), getVoxelArea(), and setAscale().
doAxialDiffusion_
bool EndoMesh::doAxialDiffusion_ private
vEndo = vScale * pow(surroundVol, vPower_)
Definition at line 148 of file EndoMesh.h.
Referenced by EndoMesh(), getDoAxialDiffusion(), getParentVoxel(), and setDoAxialDiffusion().
insideMeshes_
Id EndoMesh::insideMeshes_ private
Definition at line 134 of file EndoMesh.h.
parent_
const MeshCompt* EndoMesh::parent_ private
Definition at line 132 of file EndoMesh.h.
Referenced by EndoMesh(), extendedMeshEntryVolume(), getCoordinates(), getDiffusionArea(), getDiffusionScaling(), getMeshEntryVolume(), getParentVoxel(), getVoxelArea(), getVoxelLength(), indexToSpace(), innerGetNumEntries(), innerHandleRequestMeshStats(), nearest(), setSurround(), vGetVoxelMidpoint(), and vGetVoxelVolume().
rPower_
double EndoMesh::rPower_ private
EndoMeshes inside. Used to update.
The reason why the powers don't have to be 1/3, 1/2 and 1 is because some organelles are not a simple linear vol relationship with their surround. I want to keep flexibility.
Definition at line 141 of file EndoMesh.h.
Referenced by EndoMesh(), getRpower(), setRpower(), and setRscale().
rScale_
double EndoMesh::rScale_ private
rEndo = rScale * pow(surroundVol, rPower_)
Definition at line 142 of file EndoMesh.h.
Referenced by EndoMesh(), getRscale(), and setRscale().
surround_
ObjId EndoMesh::surround_ private
Surrounding mesh. Use this for calculating all volume and diffusion terms, don't maintain any local variables.
Definition at line 131 of file EndoMesh.h.
Referenced by getElecComptMap(), getSurround(), and setSurround().
vPower_
double EndoMesh::vPower_ private
aEndo = aScale * pow(surroundVol, aPower_)
Definition at line 145 of file EndoMesh.h.
Referenced by EndoMesh(), extendedMeshEntryVolume(), getMeshEntryVolume(), getVoxelLength(), getVpower(), setVpower(), and vGetVoxelVolume().
vScale_
double EndoMesh::vScale_ private
vEndo = vScale * pow(surroundVol, vPower_)
Definition at line 146 of file EndoMesh.h.
Referenced by EndoMesh(), extendedMeshEntryVolume(), getMeshEntryVolume(), getVoxelLength(), getVscale(), setRscale(), setVscale(), and vGetVoxelVolume().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/mesh/EndoMesh.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/mesh/EndoMesh.cpp