MOOSE - Multiscale Object Oriented Simulation Environment: Group Class Reference
Group Class Reference
#include <Group.h>
Public Member Functions
Group ()
Static Public Member Functions
static const Cinfo * initCinfo ()
Detailed Description
Definition at line 12 of file Group.h.
Constructor & Destructor Documentation
Group()
Group::Group ()
Definition at line 46 of file Group.cpp.
{
    ;
}
Member Function Documentation
initCinfo()
const Cinfo * Group::initCinfo () static
Definition at line 25 of file Group.cpp.
{
    static Finfo* groupFinfos[] = {
        group(),    // Value
    };
    static Dinfo< Group > dinfo;
    static Cinfo groupCinfo (
        "Group",
        Neutral::initCinfo(),
        groupFinfos,
        sizeof( groupFinfos ) / sizeof ( Finfo* ),
        &dinfo
    );
    return &groupCinfo;
}
References Cinfo::Cinfo(), group(), and Neutral::initCinfo().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/builtins/Group.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/builtins/Group.cpp