MOOSE - Multiscale Object Oriented Simulation Environment: Enz Class Reference
Enz Class Reference
#include <Enz.h>
Public Member Functions
Enz ()
double getConcK1 (const Eref &e) const
double getK1 (const Eref &e) const
double getK2 (const Eref &e) const
double getRatio (const Eref &e) const
void setConcK1 (const Eref &e, double v)
void setK1 (const Eref &e, double v)
void setK2 (const Eref &e, double v)
void setKmK1 (double Km, double k1)
void setRatio (const Eref &e, double v)
void setSolver (const Eref &e, ObjId solver)
void vSetKcat (const Eref &e, double v)
void vSetKm (const Eref &e, double v)
~Enz ()
Public Member Functions inherited from EnzBase
void enz (double n)
EnzBase ()
ObjId getCompartment (const Eref &e) const
double getKcat (const Eref &e) const
double getKm (const Eref &e) const
double getNumKm (const Eref &e) const
unsigned int getNumPrd (const Eref &e) const
unsigned int getNumSub (const Eref &e) const
void prd (double n)
void setKcat (const Eref &e, double v)
void setKm (const Eref &e, double v)
void setNumKm (const Eref &e, double v)
void sub (double n)
virtual ~EnzBase ()
Static Public Member Functions
static const Cinfo * initCinfo ()
Static Public Member Functions inherited from EnzBase
static const Cinfo * initCinfo ()
Private Attributes
double k2_
Stoich * stoich_
Additional Inherited Members
Protected Attributes inherited from EnzBase
double kcat_
double Km_
Detailed Description
Definition at line 13 of file Enz.h.
Constructor & Destructor Documentation
Enz()
Enz::Enz ()
Definition at line 199 of file Enz.cpp.
        :
                stoich_( 0 ),
                k2_( 4.0 ) // EnzBase sets kcat_ to 1.0
{ ; }
References k2_, and stoich_.
~Enz()
Enz::~Enz ()
Definition at line 205 of file Enz.cpp.
{ ; }
Member Function Documentation
getConcK1()
double Enz::getConcK1 (const Eref & e) const
Definition at line 302 of file Enz.cpp.
{
    return (k2_ + kcat_)/Km_;
}
References k2_, EnzBase::kcat_, and EnzBase::Km_.
Referenced by initCinfo().
getK1()
double Enz::getK1 (const Eref & e) const
Definition at line 228 of file Enz.cpp.
{
    double volScale =
        convertConcToNumRateUsingMesh( e, subOut, true );
    return (k2_ + kcat_) / (volScale * Km_);
}
References convertConcToNumRateUsingMesh(), k2_, EnzBase::kcat_, EnzBase::Km_, and subOut.
Referenced by initCinfo().
getK2()
double Enz::getK2 (const Eref & e) const
Definition at line 245 of file Enz.cpp.
{
    return k2_;
}
References k2_.
Referenced by initCinfo().
getRatio()
double Enz::getRatio (const Eref & e) const
Definition at line 288 of file Enz.cpp.
{
    return k2_ / kcat_;
}
References k2_, and EnzBase::kcat_.
Referenced by initCinfo().
initCinfo()
const Cinfo * Enz::initCinfo () static
Definition at line 57 of file Enz.cpp.
{
        // Field Definitions
        static ElementValueFinfo< Enz, double > k1(
            "k1",
            "Forward reaction from enz + sub to complex, in # units."
            "This parameter is subordinate to the Km. This means that"
            "when Km is changed, this changes. It also means that when"
            "k2 or k3 (aka kcat) are changed, we assume that Km remains"
            "fixed, and as a result k1 must change. It is only when"
            "k1 is assigned directly that we assume that the user knows"
            "what they are doing, and we adjust Km accordingly."
            "k1 is also subordinate to the 'ratio' field, since setting "
            "the ratio reassigns k2."
            "Should you wish to assign the elementary rates k1, k2, k3,"
            "of an enzyme directly, always assign k1 last.",
            &Enz::setK1,
            &Enz::getK1
        );
        static ElementValueFinfo< Enz, double > k2(
            "k2",
            "Reverse reaction from complex to enz + sub",
            &Enz::setK2,
            &Enz::getK2
        );
        static ElementValueFinfo< Enz, double > k3(
            "k3",
            "Forward rate constant from complex to product + enz",
            &Enz::setKcat,
            &Enz::getKcat
        );
        static ElementValueFinfo< Enz, double > ratio(
            "ratio",
            "Ratio of k2/k3",
            &Enz::setRatio,
            &Enz::getRatio
        );
        static ElementValueFinfo< Enz, double > concK1(
            "concK1",
            "K1 expressed in concentration (1/millimolar.sec) units"
            "This parameter is subordinate to the Km. This means that"
            "when Km is changed, this changes. It also means that when"
            "k2 or k3 (aka kcat) are changed, we assume that Km remains"
            "fixed, and as a result concK1 must change. It is only when"
            "concK1 is assigned directly that we assume that the user knows"
            "what they are doing, and we adjust Km accordingly."
            "concK1 is also subordinate to the 'ratio' field, since"
            "setting the ratio reassigns k2."
            "Should you wish to assign the elementary rates concK1, k2, k3,"
            "of an enzyme directly, always assign concK1 last.",
            &Enz::setConcK1,
            &Enz::getConcK1
        );
        // MsgDest Definitions: most are inherited from EnzBase.
        static DestFinfo setSolver( "setSolver",
            "Assigns solver to this MMEnz.",
            new EpFunc1< Enz, ObjId >( &Enz::setSolver ) );
        static DestFinfo cplxDest( "cplxDest",
                "Handles # of molecules of enz-sub complex",
                // Dummy
                new OpFunc1< Enz, double >( &Enz::sub ) );
        static DestFinfo setKmK1( "setKmK1",
            "Assigns Km to enzyme. K1 arg is deprecated and ignored.",
            new OpFunc2< Enz, double, double >( &Enz::setKmK1 ) );
        // Shared Msg Definitions
        static Finfo* enzShared[] = {
            enzOut(), enzDest()
        };
        static Finfo* cplxShared[] = {
            cplxOut(), &cplxDest
        };
        static SharedFinfo enz( "enz",
            "Connects to enzyme pool",
            enzShared, sizeof( enzShared ) / sizeof( const Finfo* )
        );
        static SharedFinfo cplx( "cplx",
            "Connects to enz-sub complex pool",
            cplxShared, sizeof( cplxShared ) / sizeof( const Finfo* )
        );
    static Finfo* enzFinfos[] = {
        &k1,    // Value
        &k2,    // Value
        &k3,    // Value
        &ratio, // Value
        &concK1,    // Value
        &enz,               // SharedFinfo
        &cplx,              // SharedFinfo
        &setSolver,             // DestFinfo
        &setKmK1,           // DestFinfo
    };
    static string doc[] =
    {
            "Name", "Enz",
            "Author", "Upi Bhalla",
            "Description:",
            "Enz handles mass-action enzymes in which there is an "
            " explicit pool for the enzyme-substrate complex. "
            "It models the reaction: "
            "E + S <===> E.S ----> E + P"
    };
    static Dinfo< Enz > dinfo;
    static Cinfo enzCinfo (
        "Enz",
        EnzBase::initCinfo(),
        enzFinfos,
        sizeof( enzFinfos ) / sizeof ( Finfo* ),
        &dinfo,
        doc,
        sizeof( doc )/sizeof( string )
    );
    return &enzCinfo;
}
References Cinfo::Cinfo(), cplxOut(), DestFinfo::DestFinfo(), ElementValueFinfo< T, F >::ElementValueFinfo(), enzDest(), enzOut(), EpFunc1< T, A >::EpFunc1(), getConcK1(), getK1(), getK2(), EnzBase::getKcat(), getRatio(), EnzBase::initCinfo(), OpFunc1< T, A >::OpFunc1(), OpFunc2< T, A1, A2 >::OpFunc2(), setConcK1(), setK1(), setK2(), EnzBase::setKcat(), setKmK1(), setRatio(), setSolver(), SharedFinfo::SharedFinfo(), and EnzBase::sub().
setConcK1()
void Enz::setConcK1 (const Eref & e, double v)
Definition at line 293 of file Enz.cpp.
{
    if ( v <= EPSILON ) // raise error
        return;
    Km_ = (k2_ + kcat_) / v;
    if ( stoich_ )
        stoich_->setEnzK1( e, v );
}
References k2_, EnzBase::kcat_, EnzBase::Km_, Stoich::setEnzK1(), and stoich_.
Referenced by initCinfo(), and setRatio().
setK1()
void Enz::setK1 (const Eref & e, double v)
Definition at line 214 of file Enz.cpp.
{
    double volScale =
        convertConcToNumRateUsingMesh( e, subOut, true );
    double concK1 = v * volScale;
    if ( concK1 < EPSILON )
        concK1 = EPSILON;
    Km_ = (k2_ + kcat_)/concK1;
    if (stoich_)
        stoich_->setEnzK1( e, concK1 );
}
References convertConcToNumRateUsingMesh(), k2_, EnzBase::kcat_, EnzBase::Km_, Stoich::setEnzK1(), stoich_, and subOut.
Referenced by initCinfo().
setK2()
void Enz::setK2 (const Eref & e, double v)
Definition at line 236 of file Enz.cpp.
{
    if ( v < EPSILON )
        v = EPSILON;
    k2_ = v;
    if ( stoich_)
        stoich_->setEnzK2( e, v );
}
References k2_, Stoich::setEnzK2(), and stoich_.
Referenced by initCinfo().
setKmK1()
void Enz::setKmK1 (double Km, double k1)
Definition at line 307 of file Enz.cpp.
{
    Km_ = Km;
    // We don't need to set k1, it is implicit in Km.
}
References EnzBase::Km_.
Referenced by initCinfo().
setRatio()
void Enz::setRatio (const Eref & e, double v)
Definition at line 277 of file Enz.cpp.
{
    k2_ = v * kcat_;
    if ( stoich_ ) {
        stoich_->setEnzK2( e, k2_ );
        double k1 = ( k2_ + kcat_ ) / Km_;
        setConcK1( e, k1 );
    }
}
References k2_, EnzBase::kcat_, EnzBase::Km_, setConcK1(), Stoich::setEnzK2(), and stoich_.
Referenced by initCinfo().
setSolver()
void Enz::setSolver (const Eref & e, ObjId solver)
Definition at line 318 of file Enz.cpp.
{
    static const Finfo* subFinfo = Cinfo::find("Enz")->findFinfo( "subOut");
    static const Finfo* prdFinfo = Cinfo::find("Enz")->findFinfo( "prdOut");
    static const Finfo* enzFinfo = Cinfo::find("Enz")->findFinfo( "enzOut");
    static const Finfo* cplxFinfo= Cinfo::find("Enz")->findFinfo("cplxOut");
    assert( subFinfo );
    assert( prdFinfo );
    assert( enzFinfo );
    assert( cplxFinfo );
    vector< Id > enzMols;
    vector< Id > cplxMols;
    if ( stoich == ObjId() ) { // Clear solver
        if ( stoich_ )
            stoich_->notifyRemoveEnz( e );
        stoich_ = 0;
        return;
    }
    bool isOK = true;
    unsigned int numReactants;
    numReactants = e.element()->getNeighbors( enzMols, enzFinfo );
    bool hasEnz = ( numReactants == 1 );
    vector< Id > subs;
    numReactants = e.element()->getNeighbors( subs, subFinfo );
    bool hasSubs = ( numReactants > 0 );
    numReactants = e.element()->getNeighbors( cplxMols, cplxFinfo );
    bool hasCplx = ( numReactants == 1 );
    vector< Id > prds;
    numReactants = e.element()->getNeighbors( prds, prdFinfo );
    bool hasPrds = ( numReactants > 0 );
    assert( stoich.element()->cinfo()->isA( "Stoich" ) );
    stoich_ = reinterpret_cast< Stoich* >( stoich.data() );
    if ( hasEnz && hasSubs && hasCplx && hasPrds ) {
        stoich_->installEnzyme( e.id(), enzMols[0], cplxMols[0], subs, prds );
        double concK1 = ( k2_ + kcat_ ) / Km_;
        stoich_->setEnzK1( e, concK1 );
        stoich_->setEnzK2( e, k2_ );
        stoich_->setEnzK3( e, kcat_ );
    } else {
        stoich_->installDummyEnzyme( e.id(), Id() );
        string msg = "";
        if ( !hasEnz ) msg = msg + " enzyme";
        if ( !hasCplx ) msg = msg + " enzyme-substrate complex";
        if ( !hasSubs ) msg = msg + " substrates";
        if ( !hasPrds ) msg = msg + " products";
        cout << "Warning: Enz:setSolver: Dangling Enz '" <<
            e.objId().path() << "':\nMissing " << msg << endl;
    }
}
References Element::cinfo(), ObjId::data(), Eref::element(), ObjId::element(), Cinfo::find(), Cinfo::findFinfo(), Element::getNeighbors(), Id::Id(), Eref::id(), Stoich::installDummyEnzyme(), Stoich::installEnzyme(), Cinfo::isA(), k2_, EnzBase::kcat_, EnzBase::Km_, Stoich::notifyRemoveEnz(), ObjId::ObjId(), Eref::objId(), ObjId::operator==(), ObjId::path(), Stoich::setEnzK1(), Stoich::setEnzK2(), Stoich::setEnzK3(), and stoich_.
Referenced by initCinfo().
vSetKcat()
void Enz::vSetKcat (const Eref & e, double v) virtual
Implements EnzBase.
Definition at line 250 of file Enz.cpp.
{
    // Assumes kcat_ has been set by EnzBase::setKcat
    // Tries to preserve 'ratio'.
    double ratio = 4.0;
    if ( kcat_ > EPSILON ) {
        ratio = k2_/kcat_;
    }
    kcat_ = v;
    k2_ = v * ratio;
    double concK1 = v * (1.0 + ratio) / Km_;
    if (stoich_ ) {
        stoich_->setEnzK1( e, concK1 );
        stoich_->setEnzK3( e, kcat_ );
        stoich_->setEnzK2( e, k2_ );
    }
}
References k2_, EnzBase::kcat_, EnzBase::Km_, Stoich::setEnzK1(), Stoich::setEnzK2(), Stoich::setEnzK3(), and stoich_.
vSetKm()
void Enz::vSetKm (const Eref & e, double v) virtual
Implements EnzBase.
Definition at line 269 of file Enz.cpp.
{
    Km_ = v;
    double concK1 = ( k2_ + kcat_ ) / v;
    if ( stoich_ )
        stoich_->setEnzK1( e, concK1 );
}
References k2_, EnzBase::kcat_, EnzBase::Km_, Stoich::setEnzK1(), and stoich_.
Member Data Documentation
k2_
double Enz::k2_ private
Definition at line 49 of file Enz.h.
Referenced by Enz(), getConcK1(), getK1(), getK2(), getRatio(), setConcK1(), setK1(), setK2(), setRatio(), setSolver(), vSetKcat(), and vSetKm().
stoich_
Stoich* Enz::stoich_ private
Definition at line 48 of file Enz.h.
Referenced by Enz(), setConcK1(), setK1(), setK2(), setRatio(), setSolver(), vSetKcat(), and vSetKm().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/kinetics/Enz.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/kinetics/Enz.cpp