MOOSE - Multiscale Object Oriented Simulation Environment: RateTerm Class Reference
RateTerm Class Reference abstract
#include <RateTerm.h>
Public Member Functions
virtual RateTerm * copyWithVolScaling (double vol, double sub, double prd) const =0
virtual double getR1 () const =0
Used by Zombie to return rate terms.
virtual double getR2 () const =0
Used by Zombie to return rate terms.
virtual unsigned int getReactants (vector< unsigned int > &molIndex) const =0
virtual double operator() (const double *S) const =0
Computes the rate. The argument is the molecule array.
RateTerm ()
virtual void rescaleVolume (short comptIndex, const vector< short > &compartmentLookup, double ratio)=0
virtual void setR1 (double k1)=0
Used by Zombie to assign rate terms.
virtual void setR2 (double k2)=0
Used by Zombie to assign rate terms.
virtual void setRates (double k1, double k2)=0
virtual ~RateTerm ()
Static Public Attributes
static const double EPSILON = 1.0e-6
Detailed Description
Definition at line 18 of file RateTerm.h.
Constructor & Destructor Documentation
RateTerm()
RateTerm::RateTerm () inline
Definition at line 21 of file RateTerm.h.
{;}
~RateTerm()
virtual RateTerm::~RateTerm () inline virtual
Definition at line 22 of file RateTerm.h.
{;}
Member Function Documentation
copyWithVolScaling()
virtual RateTerm * RateTerm::copyWithVolScaling (double vol, double sub, double prd) const pure virtual
Duplicates rate term and then applies volume scaling. Arguments are volume of reference voxel, product of vol/refVol for all substrates: applied to R1 product of vol/refVol for all products: applied to R2
Note that unless the reaction is cross-compartment, the vol/refVol will be one.
Implemented in FuncRate, FuncReac, MMEnzyme1, MMEnzyme, ExternReac, ZeroOrder, Flux, FirstOrder, SecondOrder, StochSecondOrderSingleSubstrate, NOrder, StochNOrder, and BidirectionalReaction.
Referenced by VoxelPoolsBase::scaleVolsBufsRates(), GssaVoxelPools::updateAllRateTerms(), VoxelPools::updateAllRateTerms(), GssaVoxelPools::updateRateTerms(), and VoxelPools::updateRateTerms().
getR1()
virtual double RateTerm::getR1 () const pure virtual
Used by Zombie to return rate terms.
Implemented in FuncRate, MMEnzymeBase, ExternReac, ZeroOrder, and BidirectionalReaction.
Referenced by Stoich::convertRatesToStochasticForm(), Stoich::getR1(), VoxelPoolsBase::getR1(), Stoich::getR1offset1(), Stoich::getR1offset2(), Stoich::installAndUnschedFuncReac(), and VoxelPoolsBase::print().
getR2()
virtual double RateTerm::getR2 () const pure virtual
Used by Zombie to return rate terms.
Implemented in MMEnzymeBase, ExternReac, ZeroOrder, and BidirectionalReaction.
Referenced by Stoich::getR2(), and VoxelPoolsBase::print().
getReactants()
virtual unsigned int RateTerm::getReactants (vector< unsigned int > & molIndex) const pure virtual
This function finds the reactant indices in the vector S. It returns the number of substrates found, which are the first entries in molIndex. The products are the remaining ones. Note that it does NOT find products for unidirectional reactions, which is a bit of a problem.
Implemented in FuncRate, FuncReac, MMEnzyme1, MMEnzyme, ExternReac, ZeroOrder, Flux, FirstOrder, SecondOrder, StochSecondOrderSingleSubstrate, NOrder, and BidirectionalReaction.
Referenced by Stoich::convertRatesToStochasticForm(), Gsolve::fillMmEnzDep(), MMEnzyme::getReactants(), and Stoich::installAndUnschedFuncReac().
operator()()
virtual double RateTerm::operator() (const double * S) const pure virtual
Computes the rate. The argument is the molecule array.
Implemented in FuncRate, FuncReac, MMEnzyme1, MMEnzyme, ExternReac, ZeroOrder, Flux, FirstOrder, SecondOrder, StochSecondOrderSingleSubstrate, NOrder, StochNOrder, and BidirectionalReaction.
Referenced by GssaVoxelPools::getReacVelocity(), MMEnzyme::operator()(), VoxelPools::updateRates(), VoxelPools::updateReacVelocities(), and GssaVoxelPools::updateReacVelocities().
rescaleVolume()
virtual void RateTerm::rescaleVolume (short comptIndex, const vector< short > & compartmentLookup, double ratio) pure virtual
This is used to rescale the RateTerm kinetics when the compartment volume changes. This is needed because the kinetics are in extensive units, that is, mol numbers, rather than in intensive units like concentration. So when the volume changes the rate terms change. Each Rate term checks if any of its reactant molecules are affected, and if so, rescales. Ratio is newVol / oldVol
Implemented in MMEnzymeBase, ExternReac, ZeroOrder, Flux, FirstOrder, SecondOrder, StochSecondOrderSingleSubstrate, NOrder, and BidirectionalReaction.
setR1()
virtual void RateTerm::setR1 (double k1) pure virtual
Used by Zombie to assign rate terms.
Implemented in ExternReac, ZeroOrder, BidirectionalReaction, and MMEnzymeBase.
Referenced by Stoich::setEnzK1(), Stoich::setEnzK2(), Stoich::setEnzK3(), Stoich::setMMenzKm(), Stoich::setReacKb(), and Stoich::setReacKf().
setR2()
virtual void RateTerm::setR2 (double k2) pure virtual
Used by Zombie to assign rate terms.
Implemented in ExternReac, ZeroOrder, BidirectionalReaction, and MMEnzymeBase.
Referenced by Stoich::setEnzK2(), Stoich::setMMenzKcat(), and Stoich::setReacKb().
setRates()
virtual void RateTerm::setRates (double k1, double k2) pure virtual
Assign the rates.
Implemented in ExternReac, ZeroOrder, BidirectionalReaction, and MMEnzymeBase.
Member Data Documentation
EPSILON
const double RateTerm::EPSILON = 1.0e-6 static
Definition at line 52 of file RateTerm.h.
Referenced by MMEnzyme::operator()().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/ksolve/RateTerm.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/ksolve/RateTerm.cpp