MOOSE - Multiscale Object Oriented Simulation Environment: SpineMesh Class Reference
SpineMesh Class Reference
#include <SpineMesh.h>
Public Member Functions
void buildStencil ()
double extendedMeshEntryVolume (unsigned int fid) const
Vol of all mesh Entries including abutting diff-coupled voxels.
vector< double > getCoordinates (unsigned int fid) const
Virtual function to return coords of mesh Entry.
vector< double > getDiffusionArea (unsigned int fid) const
Virtual function to return diffusion X-section area.
vector< double > getDiffusionScaling (unsigned int fid) const
Virtual function to return scale factor for diffusion. 1 here.
vector< Id > getElecComptMap () const
vector< unsigned int > getEndVoxelInCompt () const
Returns index of end voxel mapping to elec compt, just first+1.
unsigned int getMeshDimensions (unsigned int fid) const
Virtual function to return dimensions of specified entry.
double getMeshEntryVolume (unsigned int fid) const
Virtual function to return volume of mesh Entry.
unsigned int getMeshType (unsigned int fid) const
Virtual function to return MeshType of specified entry.
vector< unsigned int > getNeuronVoxel () const
vector< unsigned int > getParentVoxel () const
vector< unsigned int > getStartVoxelInCompt () const
Returns index of first voxel mapping to elec compt.
const vector< double > & getVoxelArea () const
const vector< double > & getVoxelLength () const
void handleSpineList (const Eref &e, vector< Id > shaft, vector< Id > head, vector< unsigned int > parentVoxel)
void indexToSpace (unsigned int index, double &x, double &y, double &z) const
void innerBuildDefaultMesh (const Eref &e, double volume, unsigned int numEntries)
Virtual func to make a mesh with specified Volume and numEntries.
unsigned int innerGetDimensions () const
Returns # of dimensions, always 3 here. Inherited pure virt func.
unsigned int innerGetNumEntries () const
void innerHandleNodeInfo (const Eref &e, unsigned int numNodes, unsigned int numThreads)
void innerSetNumEntries (unsigned int n)
Inherited virtual func.
void matchCubeMeshEntries (const ChemCompt *other, vector< VoxelJunction > &ret) const
void matchMeshEntries (const ChemCompt *other, vector< VoxelJunction > &ret) const
void matchNeuroMeshEntries (const ChemCompt *other, vector< VoxelJunction > &ret) const
void matchSpineMeshEntries (const ChemCompt *other, vector< VoxelJunction > &ret) const
double nearest (double x, double y, double z, unsigned int &index) const
void setMeshEntryVolume (unsigned int fid, double volume)
Virtual function to assign volume of mesh Entry.
SpineMesh ()
SpineMesh (const SpineMesh &other)
const vector< SpineEntry > & spines () const
void transmitChange (const Eref &e)
void updateCoords ()
double vGetEntireVolume () const
Inherited virtual func.
const vector< double > & vGetVoxelMidpoint () const
Virtual func so that derived classes can return voxel midpoint.
const vector< double > & vGetVoxelVolume () const
Virtual func so that derived classes can pass voxel volume back.
bool vSetVolumeNotRates (double volume)
Inherited virtual func.
~SpineMesh ()
Public Member Functions inherited from MeshCompt
void addRow (unsigned int index, const vector< double > &entry, const vector< unsigned int > &colIndex)
void clearExtendedMeshEntryVolume ()
Inherited virtual function to clear the vector of MeshEntryVolume.
void extendStencil (const ChemCompt *other, const vector< VoxelJunction > &vj)
Add boundary voxels to stencil for cross-solver junctions.
vector< unsigned int > getNeighbors (unsigned int fid) const
Looks up stencil to return vector of indices of coupled voxels.
const SparseMatrix< double > & getStencil () const
Returns entire sparse matrix of mesh. Used by diffusion solver.
unsigned int getStencilRow (unsigned int meshIndex, const double **entry, const unsigned int **colIndex) const
vector< double > innerGetStencilRate (unsigned int row) const
void innerResetStencil ()
virtual func implemented here.
MeshCompt ()
void setStencilSize (unsigned int numRows, unsigned int numCols)
~MeshCompt ()
Public Member Functions inherited from ChemCompt
void buildDefaultMesh (const Eref &e, double volume, unsigned int numEntries)
void buildJunction (ChemCompt *other, vector< VoxelJunction > &ret)
ChemCompt ()
void flipRet (vector< VoxelJunction > &ret) const
Utility function for swapping first and second in VoxelJunctions.
void getChildConcs (const Eref &e, vector< double > &childConcs) const
unsigned int getDimensions () const
double getEntireVolume (const Eref &e) const
bool getIsMembraneBound () const
string getMethod () const
unsigned int getNumEntries () const
vector< double > getOneVoxelMidpoint (unsigned int vox) const
Looks up specified voxel midpoint, from vGetVoxelMidpoint.
double getOneVoxelVolume (const Eref &e, unsigned int voxel) const
vector< unsigned int > getStencilIndex (unsigned int row) const
vector< double > getStencilRate (unsigned int row) const
vector< double > getVoxelMidpoint () const
Returns vector of all voxel midpoints in compartment.
vector< double > getVoxelVolume () const
Returns vector of all voxel volumes in compartment.
void handleNodeInfo (const Eref &e, unsigned int numNodes, unsigned int numThreads)
MeshEntry * lookupEntry (unsigned int index)
void resetStencil ()
unsigned int setChildConcs (const Eref &e, const vector< double > &childConcs, unsigned int start) const
void setEntireVolume (const Eref &e, double volume)
void setIsMembraneBound (bool v)
void setMethod (string method)
void setNumEntries (unsigned int num)
void setOneVoxelVolume (const Eref &e, unsigned int voxel, double volume)
void setVolumeNotRates (double volume)
virtual ~ChemCompt ()
Static Public Member Functions
static const Cinfo * initCinfo ()
Static Public Member Functions inherited from ChemCompt
static double distance (double x, double y, double z)
static const Cinfo * initCinfo ()
static SrcFinfo1< vector< double > > * voxelVolOut ()
Private Attributes
vector< double > area_
vector< double > length_
Pre-calculation of length of each MeshEntry.
vector< SpineEntry > spines_
double surfaceGranularity_
vector< double > vs_
Detailed Description
The SpineMesh sets up the diffusion geometries for dendritic spines. It is filled by a message from a NeuroMesh that contains information about the matching voxel on the NeuroMesh, and the compartment Ids for the spine shaft and head. The SpineMesh can further generate a PSD mesh with the info for the PSD geometries. This assumes that the each spine is a single voxel: single diffusive compartment, well-stirred. The shaft is treated as zero volume diffusion barrier to the dendrite. The PSD is a separate compt with its own diffusion coupling to the spine head.
Definition at line 26 of file SpineMesh.h.
Constructor & Destructor Documentation
SpineMesh() [1/2]
SpineMesh::SpineMesh ()
Definition at line 152 of file SpineMesh.cpp.
    :
        spines_( 1 ),
        surfaceGranularity_( 0.1 ),
        vs_( 1, 1.0e-18 ),
        area_( 1, 1.0e-12 ),
        length_( 1, 1.0e-6 )
{;}
References area_, length_, spines_, surfaceGranularity_, and vs_.
SpineMesh() [2/2]
SpineMesh::SpineMesh (const SpineMesh & other)
Definition at line 161 of file SpineMesh.cpp.
    :
        spines_( other.spines_ ),
        surfaceGranularity_( other.surfaceGranularity_ )
{;}
References spines_, and surfaceGranularity_.
~SpineMesh()
SpineMesh::~SpineMesh ()
Definition at line 167 of file SpineMesh.cpp.
{
    ;
}
Member Function Documentation
buildStencil()
void SpineMesh::buildStencil ()
Definition at line 472 of file SpineMesh.cpp.
{
// stencil_[0] = new NeuroStencil(nodes_, nodeIndex_, vs_, area_);
    setStencilSize( spines_.size(), spines_.size() );
    innerResetStencil();
}
References MeshCompt::innerResetStencil(), MeshCompt::setStencilSize(), and spines_.
Referenced by updateCoords().
extendedMeshEntryVolume()
double SpineMesh::extendedMeshEntryVolume (unsigned int fid) const virtual
Vol of all mesh Entries including abutting diff-coupled voxels.
Virtual function to return volume of mesh Entry, including for diffusively coupled voxels from other solvers.
Reimplemented from MeshCompt.
Definition at line 345 of file SpineMesh.cpp.
{
    if ( fid < spines_.size() ) {
        return getMeshEntryVolume( fid );
    } else {
        return MeshCompt::extendedMeshEntryVolume( fid - spines_.size() );
    }
}
References MeshCompt::extendedMeshEntryVolume(), getMeshEntryVolume(), and spines_.
getCoordinates()
vector< double > SpineMesh::getCoordinates (unsigned int fid) const virtual
Virtual function to return coords of mesh Entry.
Virtual function to return coords of mesh Entry. For SpineMesh, coords are x1y1z1 x2y2z2 x3y3z3 r0 r1
Implements ChemCompt.
Definition at line 323 of file SpineMesh.cpp.
{
    return spines_[fid].spineCoords();
}
References SpineEntry::spineCoords(), and spines_.
getDiffusionArea()
vector< double > SpineMesh::getDiffusionArea (unsigned int fid) const virtual
Virtual function to return diffusion X-section area.
Virtual function to return diffusion X-section area for each neighbor.
Implements ChemCompt.
Definition at line 329 of file SpineMesh.cpp.
{
    vector< double > ret;
    return ret;
}
getDiffusionScaling()
vector< double > SpineMesh::getDiffusionScaling (unsigned int fid) const virtual
Virtual function to return scale factor for diffusion. 1 here.
Virtual function to return scale factor for diffusion. I think all dendite tips need to return just one entry of 1.
Implements ChemCompt.
Definition at line 338 of file SpineMesh.cpp.
{
    return vector< double >( 2, 1.0 );
}
getElecComptMap()
vector< Id > SpineMesh::getElecComptMap () const
Returns vector of Ids of electrical compts that map to respective voxels in SpineMesh
Definition at line 202 of file SpineMesh.cpp.
{
    vector< Id > ret( spines_.size() );
    for ( unsigned int i = 0; i < spines_.size(); ++i )
        ret[i] = spines_[i].headId();
    return ret;
}
References SpineEntry::headId(), and spines_.
Referenced by initCinfo().
getEndVoxelInCompt()
vector< unsigned int > SpineMesh::getEndVoxelInCompt () const
Returns index of end voxel mapping to elec compt, just first+1.
Definition at line 218 of file SpineMesh.cpp.
{
    vector< unsigned int > ret( spines_.size() );
    for ( unsigned int i = 0; i < ret.size(); ++i )
        ret[i] = i+1;
    return ret;
}
References spines_.
Referenced by initCinfo().
getMeshDimensions()
unsigned int SpineMesh::getMeshDimensions (unsigned int fid) const virtual
Virtual function to return dimensions of specified entry.
Implements ChemCompt.
Definition at line 299 of file SpineMesh.cpp.
{
    return 3;
}
getMeshEntryVolume()
double SpineMesh::getMeshEntryVolume (unsigned int fid) const virtual
Virtual function to return volume of mesh Entry.
Implements ChemCompt.
Definition at line 305 of file SpineMesh.cpp.
{
    if ( spines_.size() == 0 )
        return 1.0;
    assert( fid < spines_.size() );
    return spines_[ fid % spines_.size() ].volume();
}
References spines_, and SpineEntry::volume().
Referenced by extendedMeshEntryVolume(), handleSpineList(), and PsdMesh::matchSpineMeshEntries().
getMeshType()
unsigned int SpineMesh::getMeshType (unsigned int fid) const virtual
Virtual function to return MeshType of specified entry.
Implements ChemCompt.
Definition at line 292 of file SpineMesh.cpp.
{
    assert( fid < spines_.size() );
    return CYL;
}
References CYL, and spines_.
getNeuronVoxel()
vector< unsigned int > SpineMesh::getNeuronVoxel () const
Returns index of voxel on NeuroMesh to which this spine is connected.
Definition at line 194 of file SpineMesh.cpp.
{
    vector< unsigned int > ret( spines_.size(), ~0U );
    for ( unsigned int i = 0; i < spines_.size(); ++i )
        ret[i] = spines_[i].parent();
    return ret;
}
References SpineEntry::parent(), and spines_.
Referenced by initCinfo().
getParentVoxel()
vector< unsigned int > SpineMesh::getParentVoxel () const virtual
This function returns the diffusively connected parent voxel within the current (spine) mesh. Since each spine is treated as an independed voxel, there is no such voxel, so we return -1U for each spine. Note that there is a separate function that returns the parentVoxel referred to the NeuroMesh that this spine sits on.
Implements MeshCompt.
Definition at line 183 of file SpineMesh.cpp.
{
    vector< unsigned int > ret( spines_.size(), ~0U );
    // for ( unsigned int i = 0; i < spines_.size(); ++i )
    //  ret[i] = spines_[i].parent(); // Wrong, returns voxel on NeuroMesh
    return ret;
}
References spines_.
Referenced by initCinfo().
getStartVoxelInCompt()
vector< unsigned int > SpineMesh::getStartVoxelInCompt () const
Returns index of first voxel mapping to elec compt.
Definition at line 210 of file SpineMesh.cpp.
{
    vector< unsigned int > ret( spines_.size() );
    for ( unsigned int i = 0; i < ret.size(); ++i )
        ret[i] = i;
    return ret;
}
References spines_.
Referenced by initCinfo().
getVoxelArea()
const vector< double > & SpineMesh::getVoxelArea () const virtual
Implements MeshCompt.
Definition at line 400 of file SpineMesh.cpp.
{
    return area_;
}
References area_.
getVoxelLength()
const vector< double > & SpineMesh::getVoxelLength () const virtual
Implements MeshCompt.
Definition at line 405 of file SpineMesh.cpp.
{
    return length_;
}
References length_.
handleSpineList()
void SpineMesh::handleSpineList (const Eref & e, vector< Id > shaft, vector< Id > head, vector< unsigned int > parentVoxel)
Definition at line 244 of file SpineMesh.cpp.
{
        double oldVol = getMeshEntryVolume( 0 );
        assert( head.size() == parentVoxel.size() );
        assert( head.size() == shaft.size() );
        spines_.resize( head.size() );
        vs_.resize( head.size() );
        area_.resize( head.size() );
        length_.resize( head.size() );
        vector< double > ret;
        vector< double > psdCoords;
        vector< unsigned int > index( head.size(), 0 );
        for ( unsigned int i = 0; i < head.size(); ++i ) {
            spines_[i] = SpineEntry( shaft[i], head[i], parentVoxel[i] );
            // cout << i << "   " << head[i] << ", pa = " << parentVoxel[i] << endl;
            // ret = spines_[i].psdCoords();
            // assert( ret.size() == 8 );
            // psdCoords.insert( psdCoords.end(), ret.begin(), ret.end() );
            // index[i] = i;
            vs_[i] = spines_[i].volume();
            area_[i] = spines_[i].rootArea();
            length_[i] = spines_[i].diffusionLength();
        }
        updateCoords();
        Id meshEntry( e.id().value() + 1 );
        vector< unsigned int > localIndices( head.size() );
        vector< double > vols( head.size() );
        for ( unsigned int i = 0; i < head.size(); ++i ) {
            localIndices[i] = i;
            vols[i] = spines_[i].volume();
        }
        vector< vector< unsigned int > > outgoingEntries;
        vector< vector< unsigned int > > incomingEntries;
        // meshSplit()->send( e, oldVol, vols, localIndices, outgoingEntries, incomingEntries );
        lookupEntry( 0 )->triggerRemesh( meshEntry.eref(),
                        oldVol, 0, localIndices, vols );
}
References area_, SpineEntry::diffusionLength(), Id::eref(), getMeshEntryVolume(), Eref::id(), Id::Id(), length_, ChemCompt::lookupEntry(), SpineEntry::rootArea(), SpineEntry::SpineEntry(), spines_, MeshEntry::triggerRemesh(), updateCoords(), Id::value(), SpineEntry::volume(), and vs_.
Referenced by initCinfo().
indexToSpace()
void SpineMesh::indexToSpace (unsigned int index, double & x, double & y, double & z) const virtual
Converts specified index to xyz coords of middle of voxel Values out of range return original xyz
Implements ChemCompt.
Definition at line 505 of file SpineMesh.cpp.
{
    if ( index >= innerGetNumEntries() )
        return;
    spines_[ index ].mid( x, y, z );
}
References innerGetNumEntries(), SpineEntry::mid(), and spines_.
initCinfo()
const Cinfo * SpineMesh::initCinfo () static
Definition at line 46 of file SpineMesh.cpp.
{
        // Field Definitions
        static ReadOnlyValueFinfo< SpineMesh, vector< unsigned int > >
            parentVoxel
        (
            "parentVoxel",
            "Vector of indices of proximal voxels within this mesh."
            "Spines are at present modeled with just one compartment,"
            "so each entry in this vector is always set to EMPTY == -1U",
            &SpineMesh::getParentVoxel
        );
        static ReadOnlyValueFinfo< SpineMesh, vector< unsigned int > >
            neuronVoxel
        (
            "neuronVoxel",
            "Vector of indices of voxels on parent NeuroMesh, from which "
            "the respective spines emerge.",
            &SpineMesh::getNeuronVoxel
        );
        static ReadOnlyValueFinfo< SpineMesh, vector< Id > > elecComptMap(
            "elecComptMap",
            "Vector of Ids of electrical compartments that map to each "
            "voxel. This is necessary because the order of the IDs may "
            "differ from the ordering of the voxels. Note that there "
            "is always just one voxel per spine head. ",
            &SpineMesh::getElecComptMap
        );
        static ReadOnlyValueFinfo< SpineMesh, vector< Id > > elecComptList(
            "elecComptList",
            "Vector of Ids of all electrical compartments in this "
            "SpineMesh. Ordering is as per the tree structure built in "
            "the NeuroMesh, and may differ from Id order. Ordering "
            "matches that used for startVoxelInCompt and endVoxelInCompt",
            &SpineMesh::getElecComptMap
        );
        static ReadOnlyValueFinfo< SpineMesh, vector< unsigned int > > startVoxelInCompt(
            "startVoxelInCompt",
            "Index of first voxel that maps to each electrical "
            "compartment. This is a trivial function in the SpineMesh, as"
            "we have a single voxel per spine. So just a vector of "
            "its own indices.",
            &SpineMesh::getStartVoxelInCompt
        );
        static ReadOnlyValueFinfo< SpineMesh, vector< unsigned int > > endVoxelInCompt(
            "endVoxelInCompt",
            "Index of end voxel that maps to each electrical "
            "compartment. Since there is just one voxel per electrical "
            "compartment in the spine, this is just a vector of index+1",
            &SpineMesh::getEndVoxelInCompt
        );
        // MsgDest Definitions
        static DestFinfo spineList( "spineList",
            "Specifies the list of electrical compartments for the spine,"
            "and the associated parent voxel"
            "Arguments: shaft compartments, "
            "head compartments, parent voxel index ",
            new EpFunc3< SpineMesh, vector< Id >, vector< Id >,
            vector< unsigned int > >(
                &SpineMesh::handleSpineList )
        );
        // Field Elements
    static Finfo* spineMeshFinfos[] = {
        &parentVoxel,       // ReadOnlyValueFinfo
        &neuronVoxel,       // ReadOnlyValueFinfo
        &elecComptMap,      // ReadOnlyValueFinfo
        &elecComptList,     // ReadOnlyValueFinfo
        &startVoxelInCompt,     // ReadOnlyValueFinfo
        &endVoxelInCompt,       // ReadOnlyValueFinfo
        &spineList,         // DestFinfo
        // psdListOut(),        // SrcFinfo
    };
    static Dinfo< SpineMesh > dinfo;
    static Cinfo spineMeshCinfo (
        "SpineMesh",
        ChemCompt::initCinfo(),
        spineMeshFinfos,
        sizeof( spineMeshFinfos ) / sizeof ( Finfo* ),
        &dinfo
    );
    return &spineMeshCinfo;
}
References Cinfo::Cinfo(), DestFinfo::DestFinfo(), EpFunc3< T, A1, A2, A3 >::EpFunc3(), getElecComptMap(), getEndVoxelInCompt(), getNeuronVoxel(), getParentVoxel(), getStartVoxelInCompt(), handleSpineList(), ChemCompt::initCinfo(), and ReadOnlyValueFinfo< T, F >::ReadOnlyValueFinfo().
innerBuildDefaultMesh()
void SpineMesh::innerBuildDefaultMesh (const Eref & e, double volume, unsigned int numEntries) virtual
Virtual func to make a mesh with specified Volume and numEntries.
Not allowed.
Implements ChemCompt.
Definition at line 457 of file SpineMesh.cpp.
{
    cout << "Warning: SpineMesh::innerBuildDefaultMesh: attempt to build a default spine: not permitted\n";
}
innerGetDimensions()
unsigned int SpineMesh::innerGetDimensions () const virtual
Returns # of dimensions, always 3 here. Inherited pure virt func.
Implements ChemCompt.
Definition at line 238 of file SpineMesh.cpp.
{
    return 3;
}
innerGetNumEntries()
unsigned int SpineMesh::innerGetNumEntries () const virtual
Inherited virtual func. Returns number of MeshEntry in array
Implements ChemCompt.
Definition at line 440 of file SpineMesh.cpp.
{
    return spines_.size();
}
References spines_.
Referenced by indexToSpace().
innerHandleNodeInfo()
void SpineMesh::innerHandleNodeInfo (const Eref & e, unsigned int numNodes, unsigned int numThreads) virtual
Implements ChemCompt.
Definition at line 371 of file SpineMesh.cpp.
{
}
innerSetNumEntries()
void SpineMesh::innerSetNumEntries (unsigned int n) virtual
Inherited virtual func.
Inherited virtual func. Assigns number of MeshEntries. Doesn't do anything, we have to set spine # from geometry.
Implements ChemCompt.
Definition at line 449 of file SpineMesh.cpp.
{
}
matchCubeMeshEntries()
void SpineMesh::matchCubeMeshEntries (const ChemCompt * other, vector< VoxelJunction > & ret) const
Definition at line 554 of file SpineMesh.cpp.
{
    for( unsigned int i = 0; i < spines_.size(); ++i ) {
        const SpineEntry& se = spines_[i];
        se.matchCubeMeshEntriesToHead( other, i, surfaceGranularity_, ret );
    }
}
References SpineEntry::matchCubeMeshEntriesToHead(), spines_, and surfaceGranularity_.
Referenced by matchMeshEntries().
matchMeshEntries()
void SpineMesh::matchMeshEntries (const ChemCompt * other, vector< VoxelJunction > & ret) const virtual
Returns the meshIndices (NOT spatial indices) of all adjacent mesh entry pairs on ether side of the (self, other) junction. meshIndices are the indices that look up entries in the vector of pools. spatialIndices are (iz * ny + iy) * nx + ix, that is, a linear conversion of cartesian spatial indices. So, for two touching cubes, the return vector is the paired meshIndices on either side of the plane of contact. If one mesh has a finer mesh than the other, or if there are more than one contact points from self to other (for example, at a corner), then we just have multiple pairs using the same meshIndex of the repeated voxel.
Implements ChemCompt.
Definition at line 483 of file SpineMesh.cpp.
{
    const CubeMesh* cm = dynamic_cast< const CubeMesh* >( other );
    if ( cm ) {
        matchCubeMeshEntries( other, ret );
        return;
    }
    const NeuroMesh* nm = dynamic_cast< const NeuroMesh* >( other );
    if ( nm ) {
        matchNeuroMeshEntries( other, ret );
        return;
    }
    const PsdMesh* pm = dynamic_cast< const PsdMesh* >( other );
    if ( pm ) {
        pm->matchSpineMeshEntries( this, ret );
        flipRet( ret );
        return;
    }
    cout << "Warning: SpineMesh::matchMeshEntries: unknown class\n";
}
References ChemCompt::flipRet(), matchCubeMeshEntries(), matchNeuroMeshEntries(), and PsdMesh::matchSpineMeshEntries().
matchNeuroMeshEntries()
void SpineMesh::matchNeuroMeshEntries (const ChemCompt * other, vector< VoxelJunction > & ret) const
Definition at line 540 of file SpineMesh.cpp.
{
    const NeuroMesh* nm = dynamic_cast< const NeuroMesh* >( other );
    assert( nm );
    for ( unsigned int i = 0; i < spines_.size(); ++i ) {
        double xda = spines_[i].rootArea() / spines_[i].diffusionLength();
        ret.push_back( VoxelJunction( i, spines_[i].parent(), xda ) );
        ret.back().firstVol = spines_[i].volume();
        ret.back().secondVol =
                nm->getMeshEntryVolume( spines_[i].parent() );
    }
}
References SpineEntry::diffusionLength(), VoxelJunction::firstVol, NeuroMesh::getMeshEntryVolume(), SpineEntry::parent(), SpineEntry::rootArea(), VoxelJunction::secondVol, spines_, SpineEntry::volume(), and VoxelJunction::VoxelJunction().
Referenced by NeuroMesh::matchMeshEntries(), and matchMeshEntries().
matchSpineMeshEntries()
void SpineMesh::matchSpineMeshEntries (const ChemCompt * other, vector< VoxelJunction > & ret) const
Definition at line 535 of file SpineMesh.cpp.
{
}
nearest()
double SpineMesh::nearest (double x, double y, double z, unsigned int & index) const virtual
This works a little different from other subclass versions of the function. It finds the index of the mesh entry whose centre is closest to the specified coords, and returns the distance to the centre. Doesn't worry about whether this distance is inside or outside cell.
Implements ChemCompt.
Definition at line 513 of file SpineMesh.cpp.
{
    double best = 1e12;
    index = 0;
    for( unsigned int i = 0; i < spines_.size(); ++i ) {
        const SpineEntry& se = spines_[i];
        double a0, a1, a2;
        se.mid( a0, a1, a2 );
        Vec a( a0, a1, a2 );
        Vec b( x, y, z );
        double d = a.distance( b );
        if ( best > d ) {
            best = d;
            index = i;
        }
    }
    if ( best == 1e12 )
        return -1;
    return best;
}
References Vec::distance(), SpineEntry::mid(), spines_, and Vec::Vec().
setMeshEntryVolume()
void SpineMesh::setMeshEntryVolume (unsigned int fid, double volume) virtual
Virtual function to assign volume of mesh Entry.
Reimplemented from ChemCompt.
Definition at line 313 of file SpineMesh.cpp.
{
    if ( spines_.size() == 0 )
        return;
    assert( fid < spines_.size() );
    spines_[ fid % spines_.size() ].setVolume( volume );
}
References SpineEntry::setVolume(), and spines_.
spines()
const vector< SpineEntry > & SpineMesh::spines () const
Definition at line 464 of file SpineMesh.cpp.
{
        return spines_;
}
References spines_.
transmitChange()
void SpineMesh::transmitChange (const Eref & e)
updateCoords()
void SpineMesh::updateCoords ()
Recomputes all local coordinate and meshing data following a change in any of the coord parameters
This assumes that lambda is the quantity to preserve, over numEntries. So when the compartment changes volume, numEntries changes too. Assumes that the soma node is at index 0.
Definition at line 233 of file SpineMesh.cpp.
{
    buildStencil();
}
References buildStencil().
Referenced by handleSpineList().
vGetEntireVolume()
double SpineMesh::vGetEntireVolume () const virtual
Inherited virtual func.
Implements ChemCompt.
Definition at line 410 of file SpineMesh.cpp.
{
    double ret = 0.0;
    for ( vector< double >::const_iterator i =
                    vs_.begin(); i != vs_.end(); ++i )
        ret += *i;
    return ret;
}
References vs_.
Referenced by vSetVolumeNotRates().
vGetVoxelMidpoint()
const vector< double > & SpineMesh::vGetVoxelMidpoint () const virtual
Virtual func so that derived classes can return voxel midpoint.
Implements ChemCompt.
Definition at line 387 of file SpineMesh.cpp.
{
    static vector< double > midpoint;
    midpoint.resize( spines_.size() * 3 );
    for ( unsigned int i = 0; i < spines_.size(); ++i ) {
        spines_[i].mid( midpoint[i],
                        midpoint[i + spines_.size() ],
                        midpoint[i + 2 * spines_.size() ]
        );
    }
    return midpoint;
}
References SpineEntry::mid(), and spines_.
vGetVoxelVolume()
const vector< double > & SpineMesh::vGetVoxelVolume () const virtual
Virtual func so that derived classes can pass voxel volume back.
Implements ChemCompt.
Definition at line 382 of file SpineMesh.cpp.
{
    return vs_;
}
References vs_.
vSetVolumeNotRates()
bool SpineMesh::vSetVolumeNotRates (double volume) virtual
Inherited virtual func.
Implements ChemCompt.
Definition at line 419 of file SpineMesh.cpp.
{
    double volscale = volume / vGetEntireVolume();
    double linscale = pow( volscale, 1.0/3.0 );
    assert( vs_.size() == spines_.size() );
    assert( area_.size() == spines_.size() );
    assert( length_.size() == spines_.size() );
    for ( unsigned int i = 0; i < spines_.size(); ++i ) {
        spines_[i].setVolume( volume );
        vs_[i] *= volscale;
        area_[i] *= linscale * linscale;
        length_[i] *= linscale;
    }
    return true;
}
References area_, length_, SpineEntry::setVolume(), spines_, vGetEntireVolume(), and vs_.
Member Data Documentation
area_
vector< double > SpineMesh::area_ private
Mesh junction area pre-calculations for each MeshEntry. This is the cross-section area of the middle of each voxel.
Definition at line 203 of file SpineMesh.h.
Referenced by getVoxelArea(), handleSpineList(), SpineMesh(), and vSetVolumeNotRates().
length_
vector< double > SpineMesh::length_ private
Pre-calculation of length of each MeshEntry.
Definition at line 206 of file SpineMesh.h.
Referenced by getVoxelLength(), handleSpineList(), SpineMesh(), and vSetVolumeNotRates().
spines_
vector< SpineEntry > SpineMesh::spines_ private
These do the actual work.
Definition at line 183 of file SpineMesh.h.
Referenced by buildStencil(), extendedMeshEntryVolume(), getCoordinates(), getElecComptMap(), getEndVoxelInCompt(), getMeshEntryVolume(), getMeshType(), getNeuronVoxel(), getParentVoxel(), getStartVoxelInCompt(), handleSpineList(), indexToSpace(), innerGetNumEntries(), matchCubeMeshEntries(), matchNeuroMeshEntries(), nearest(), setMeshEntryVolume(), SpineMesh(), SpineMesh(), spines(), vGetVoxelMidpoint(), and vSetVolumeNotRates().
surfaceGranularity_
double SpineMesh::surfaceGranularity_ private
Decides how finely to subdivide diffLength_ or radius or cubic mesh side when computing surfacearea of intersections with CubeMesh. Defaults to 0.1.
Definition at line 190 of file SpineMesh.h.
Referenced by matchCubeMeshEntries(), SpineMesh(), and SpineMesh().
vs_
vector< double > SpineMesh::vs_ private
Volscale pre-calculations for each MeshEntry. vs = #molecules / vol where vol is expressed in m^3.
Definition at line 197 of file SpineMesh.h.
Referenced by handleSpineList(), SpineMesh(), vGetEntireVolume(), vGetVoxelVolume(), and vSetVolumeNotRates().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/mesh/SpineMesh.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/mesh/SpineMesh.cpp