MOOSE - Multiscale Object Oriented Simulation Environment: Leakage Class Reference
Leakage Class Reference
#include <Leakage.h>
Public Member Functions
Leakage ()
void vProcess (const Eref &e, ProcPtr p)
void vReinit (const Eref &e, ProcPtr p)
void vSetGbar (const Eref &e, double gbar)
~Leakage ()
Public Member Functions inherited from ChanCommon
ChanCommon ()
double getGbar () const
Utility function to acces Gbar.
double getVm () const
Utility function to access Vm.
void sendProcessMsgs (const Eref &e, const ProcPtr info)
void sendReinitMsgs (const Eref &e, const ProcPtr info)
void updateIk ()
double vGetEk (const Eref &e) const override
double vGetGbar (const Eref &e) const override
double vGetGk (const Eref &e) const override
double vGetIk (const Eref &e) const override
double vGetModulation (const Eref &e) const override
void vHandleVm (double Vm) override
void vSetEk (const Eref &e, double Ek) override
void vSetGk (const Eref &e, double Gk) override
void vSetIk (const Eref &e, double Ic) override
void vSetModulation (const Eref &e, double modulation) override
virtual ~ChanCommon ()=0
Public Member Functions inherited from ChanBase
ChanBase ()
double getEk (const Eref &e) const
double getGbar (const Eref &e) const
double getGk (const Eref &e) const
double getIk (const Eref &e) const
double getModulation (const Eref &e) const
void handleVm (double Vm)
void process (const Eref &e, const ProcPtr info)
void reinit (const Eref &e, const ProcPtr info)
void setEk (const Eref &e, double Ek)
void setGbar (const Eref &e, double Gbar)
void setGk (const Eref &e, double Gk)
void setIk (const Eref &e, double Ic)
void setModulation (const Eref &e, double modulation)
virtual ~ChanBase ()=0
Static Public Member Functions
static const Cinfo * initCinfo ()
Static Public Member Functions inherited from ChanCommon
static const Cinfo * initCinfo ()
Specify the Class Info static variable for initialization.
Static Public Member Functions inherited from ChanBase
static SrcFinfo2< double, double > * channelOut ()
static SrcFinfo1< double > * IkOut ()
static const Cinfo * initCinfo ()
Specify the Class Info static variable for initialization.
static SrcFinfo1< double > * permeability ()
Additional Inherited Members
Protected Member Functions inherited from ChanCommon
double getModulation () const
Protected Attributes inherited from ChanCommon
double Vm_
Vm_ is input variable from compartment, used for most rates.
Detailed Description
Definition at line 52 of file Leakage.h.
Constructor & Destructor Documentation
Leakage()
Leakage::Leakage ()
Definition at line 79 of file Leakage.cpp.
{
    ;
}
~Leakage()
Leakage::~Leakage ()
Definition at line 84 of file Leakage.cpp.
{
    ;
}
Member Function Documentation
initCinfo()
const Cinfo * Leakage::initCinfo () static
Definition at line 53 of file Leakage.cpp.
{
    static string doc[] =
    {
        "Name", "Leakage",
        "Author", "Subhasis Ray, 2009, Upi Bhalla 2014 NCBS",
        "Description", "Leakage: Passive leakage channel."
    };
    static Dinfo< Leakage > dinfo;
    static Cinfo LeakageCinfo(
        "Leakage",
        ChanBase::initCinfo(),
        0,
        0,
        &dinfo,
        doc,
        sizeof( doc ) / sizeof( string ));
    return &LeakageCinfo;
}
References Cinfo::Cinfo(), and ChanBase::initCinfo().
vProcess()
void Leakage::vProcess (const Eref & e, ProcPtr p) virtual
Implements ChanBase.
Definition at line 90 of file Leakage.cpp.
{
    ChanCommon::vSetGk( e, this->vGetGbar( e ) * this->vGetModulation( e ));
    updateIk();
    sendProcessMsgs(e, p);
}
References ChanCommon::sendProcessMsgs(), ChanCommon::updateIk(), ChanCommon::vGetGbar(), ChanCommon::vGetModulation(), and ChanCommon::vSetGk().
vReinit()
void Leakage::vReinit (const Eref & e, ProcPtr p) virtual
Implements ChanBase.
Definition at line 97 of file Leakage.cpp.
{
    ChanCommon::vSetGk( e, this->vGetGbar( e ) * this->vGetModulation( e ));
    updateIk();
    sendReinitMsgs(e, p);
}
References ChanCommon::sendReinitMsgs(), ChanCommon::updateIk(), ChanCommon::vGetGbar(), ChanCommon::vGetModulation(), and ChanCommon::vSetGk().
vSetGbar()
void Leakage::vSetGbar (const Eref & e, double gbar) virtual
Reimplemented from ChanCommon.
Definition at line 104 of file Leakage.cpp.
{
    ChanCommon::vSetGk( e, gbar * this->vGetModulation( e ) );
    ChanCommon::vSetGbar( e, gbar );
}
References ChanCommon::vGetModulation(), ChanCommon::vSetGbar(), and ChanCommon::vSetGk().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/biophysics/Leakage.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/biophysics/Leakage.cpp