MOOSE - Multiscale Object Oriented Simulation Environment: HHChannelBase Class Reference
HHChannelBase Class Reference abstract
#include <HHChannelBase.h>
Public Member Functions
virtual bool checkOriginal (Id chanId) const
void createGate (const Eref &e, string gateType)
virtual void destroyGate (const Eref &e, string gateType)
int getInstant (const Eref &e) const
int getUseConcentration (const Eref &e) const
double getX (const Eref &e) const
HHGate * getXgate (unsigned int i)
double getXpower (const Eref &e) const
double getY (const Eref &e) const
HHGate * getYgate (unsigned int i)
double getYpower (const Eref &e) const
double getZ (const Eref &e) const
HHGate * getZgate (unsigned int i)
double getZpower (const Eref &e) const
void handleConc (const Eref &e, double conc)
HHChannelBase ()
bool setGatePower (const Eref &e, double power, double *assignee, const string &gateType)
void setInstant (const Eref &e, int Instant)
void setNumGates (unsigned int num)
void setUseConcentration (const Eref &e, int value)
void setX (const Eref &e, double X)
void setXpower (const Eref &e, double Xpower)
void setY (const Eref &e, double Y)
void setYpower (const Eref &e, double Ypower)
void setZ (const Eref &e, double Z)
void setZpower (const Eref &e, double Zpower)
virtual void vCreateGate (const Eref &e, string gateType)=0
virtual int vGetInstant (const Eref &e) const
virtual double vGetX (const Eref &e) const
virtual double vGetY (const Eref &e) const
virtual double vGetZ (const Eref &e) const
virtual void vHandleConc (const Eref &e, double conc)
virtual void vSetInstant (const Eref &e, int Instant)
virtual void vSetSolver (const Eref &e, Id hsolve)
virtual void vSetUseConcentration (const Eref &e, int value)
virtual void vSetX (const Eref &e, double X)
virtual void vSetXpower (const Eref &e, double Xpower)
virtual void vSetY (const Eref &e, double Y)
virtual void vSetYpower (const Eref &e, double Ypower)
virtual void vSetZ (const Eref &e, double Z)
virtual void vSetZpower (const Eref &e, double Zpower)
virtual ~HHChannelBase ()=0
Public Member Functions inherited from ChanCommon
ChanCommon ()
double getGbar () const
Utility function to acces Gbar.
double getVm () const
Utility function to access Vm.
void sendProcessMsgs (const Eref &e, const ProcPtr info)
void sendReinitMsgs (const Eref &e, const ProcPtr info)
void updateIk ()
double vGetEk (const Eref &e) const override
double vGetGbar (const Eref &e) const override
double vGetGk (const Eref &e) const override
double vGetIk (const Eref &e) const override
double vGetModulation (const Eref &e) const override
void vHandleVm (double Vm) override
void vSetEk (const Eref &e, double Ek) override
void vSetGbar (const Eref &e, double Gbar) override
void vSetGk (const Eref &e, double Gk) override
void vSetIk (const Eref &e, double Ic) override
void vSetModulation (const Eref &e, double modulation) override
virtual ~ChanCommon ()=0
Public Member Functions inherited from ChanBase
ChanBase ()
double getEk (const Eref &e) const
double getGbar (const Eref &e) const
double getGk (const Eref &e) const
double getIk (const Eref &e) const
double getModulation (const Eref &e) const
void handleVm (double Vm)
void process (const Eref &e, const ProcPtr info)
void reinit (const Eref &e, const ProcPtr info)
void setEk (const Eref &e, double Ek)
void setGbar (const Eref &e, double Gbar)
void setGk (const Eref &e, double Gk)
void setIk (const Eref &e, double Ic)
void setModulation (const Eref &e, double modulation)
virtual void vProcess (const Eref &e, const ProcPtr info)=0
virtual void vReinit (const Eref &e, const ProcPtr info)=0
virtual ~ChanBase ()=0
Static Public Member Functions
static const Cinfo * initCinfo ()
static double power1 (double x, double p)
static double power2 (double x, double p)
static double power3 (double x, double p)
static double power4 (double x, double p)
static double powerN (double x, double p)
static PFDD selectPower (double power)
static void zombify (Element *orig, const Cinfo *zClass, Id hsolve)
Static Public Member Functions inherited from ChanCommon
static const Cinfo * initCinfo ()
Specify the Class Info static variable for initialization.
Static Public Member Functions inherited from ChanBase
static SrcFinfo2< double, double > * channelOut ()
static SrcFinfo1< double > * IkOut ()
static const Cinfo * initCinfo ()
Specify the Class Info static variable for initialization.
static SrcFinfo1< double > * permeability ()
Protected Member Functions
double integrate (double state, double dt, double A, double B)
Protected Member Functions inherited from ChanCommon
double getModulation () const
Protected Attributes
double g_
int instant_
Id myId_
double(* takeXpower_)(double, double)
double(* takeYpower_)(double, double)
double(* takeZpower_)(double, double)
bool useConcentration_
Flag for use of conc for input to Z gate calculations.
double X_
bool xInited_
Flag to indicate if gates have been created.
double Xpower_
Exponent for X gate.
double Y_
bool yInited_
double Ypower_
Exponent for Y gate.
double Z_
bool zInited_
double Zpower_
Exponent for Z gate.
Protected Attributes inherited from ChanCommon
double Vm_
Vm_ is input variable from compartment, used for most rates.
Static Protected Attributes
static const double EPSILON = 1.0e-10
static const int INSTANT_X = 1
static const int INSTANT_Y = 2
static const int INSTANT_Z = 4
Detailed Description
The HHChannelBase is the base class for defining Hodgkin-Huxley type channels, specifically dealing with derivatives used in the HSolver. This is derived from the ChanBase rather than the ChanCommon, since the Zombie classes used in the HSolver will not use the ChanCommon fields.
Definition at line 29 of file HHChannelBase.h.
Constructor & Destructor Documentation
HHChannelBase()
HHChannelBase::HHChannelBase ()
Definition at line 132 of file HHChannelBase.cpp.
    : instant_(0),
      X_(0.0),
      Y_(0.0),
      Z_(0.0),
      xInited_(false),
      yInited_(false),
      zInited_(false),
      g_(0.0),
      Xpower_(0.0),
      Ypower_(0.0),
      Zpower_(0.0),
      useConcentration_(0),
      myId_() {
    ;
}
References g_, Id::Id(), instant_, myId_, useConcentration_, X_, xInited_, Xpower_, Y_, yInited_, Ypower_, Z_, zInited_, and Zpower_.
Referenced by HHChannel2D::HHChannel2D(), and HHChannelF2D::HHChannelF2D().
~HHChannelBase()
HHChannelBase::~HHChannelBase () pure virtual
Definition at line 149 of file HHChannelBase.cpp.
{ ; }
Member Function Documentation
checkOriginal()
bool HHChannelBase::checkOriginal (Id chanId) const virtual
Reimplemented in HHChannel, HHChannel2D, HHChannelF, and HHChannelF2D.
Definition at line 190 of file HHChannelBase.cpp.
{
    cout << "Warning: HHChannelBase::checkOriginal(Id id) should be overriden by all derived classes." << endl;
    return true;
}
createGate()
void HHChannelBase::createGate (const Eref & e, string gateType)
Access function for the number of Xgates. Gives 1 if present, otherwise 0. Function for safely creating each gate, identified by strings as X, Y and Z. Will only work on a new channel, not on a copy. The idea is that the gates are always referred to the original 'library' channel, and their contents cannot be touched except by the original.
Definition at line 180 of file HHChannelBase.cpp.
{
    vCreateGate(e, gateType);
}
References vCreateGate().
Referenced by initCinfo(), and setGatePower().
destroyGate()
void HHChannelBase::destroyGate (const Eref & e, string gateType) virtual
Utility function for destroying gate. Works only on original HHChannel. Somewhat dangerous, should never be used after a copy has been made as the pointer of the gate will be in use elsewhere. This needs to be virtual as it needs to call subclass specific delete methods for the gate pointer.
Reimplemented in HHChannel, HHChannel2D, HHChannelF, and HHChannelF2D.
Definition at line 184 of file HHChannelBase.cpp.
{
    cerr << "HHChannelBase::destroyGate: This should never have been reached."
         << endl;
}
Referenced by setGatePower().
getInstant()
int HHChannelBase::getInstant (const Eref & e) const
Definition at line 208 of file HHChannelBase.cpp.
{ return vGetInstant(e); }
References vGetInstant().
Referenced by initCinfo().
getUseConcentration()
int HHChannelBase::getUseConcentration (const Eref & e) const
Definition at line 223 of file HHChannelBase.cpp.
{
    return useConcentration_;
}
References useConcentration_.
Referenced by initCinfo(), and zombify().
getX()
double HHChannelBase::getX (const Eref & e) const
Definition at line 211 of file HHChannelBase.cpp.
{ return vGetX(e); }
References vGetX().
Referenced by initCinfo().
getXgate()
HHGate * HHChannelBase::getXgate (unsigned int i)
Access function used for the X gate. The index is ignored.
getXpower()
double HHChannelBase::getXpower (const Eref & e) const
Definition at line 199 of file HHChannelBase.cpp.
{ return Xpower_; }
References Xpower_.
Referenced by HHChannel2D::initCinfo(), initCinfo(), and zombify().
getY()
double HHChannelBase::getY (const Eref & e) const
Definition at line 214 of file HHChannelBase.cpp.
{ return vGetY(e); }
References vGetY().
Referenced by initCinfo().
getYgate()
HHGate * HHChannelBase::getYgate (unsigned int i)
Access function used for the Y gate. The index is ignored.
getYpower()
double HHChannelBase::getYpower (const Eref & e) const
Definition at line 201 of file HHChannelBase.cpp.
{ return Ypower_; }
References Ypower_.
Referenced by HHChannel2D::initCinfo(), initCinfo(), and zombify().
getZ()
double HHChannelBase::getZ (const Eref & e) const
Definition at line 217 of file HHChannelBase.cpp.
{ return vGetZ(e); }
References vGetZ().
Referenced by initCinfo().
getZgate()
HHGate * HHChannelBase::getZgate (unsigned int i)
Access function used for the Z gate. The index is ignored.
getZpower()
double HHChannelBase::getZpower (const Eref & e) const
Definition at line 203 of file HHChannelBase.cpp.
{ return Zpower_; }
References Zpower_.
Referenced by HHChannel2D::initCinfo(), initCinfo(), and zombify().
handleConc()
void HHChannelBase::handleConc (const Eref & e, double conc)
Assign the local conc_ to the incoming conc from the concentration calculations for the compartment. Typically the message source will be a CaConc object, but there are other options for computing the conc.
Definition at line 281 of file HHChannelBase.cpp.
{
    vHandleConc(e, conc);
}
References vHandleConc().
Referenced by initCinfo().
initCinfo()
const Cinfo * HHChannelBase::initCinfo () static
Definition at line 22 of file HHChannelBase.cpp.
{
    // Shared messages
    // Field definitions
    static ElementValueFinfo<HHChannelBase, double> Xpower(
        "Xpower", "Power for X gate", &HHChannelBase::setXpower,
        &HHChannelBase::getXpower);
    static ElementValueFinfo<HHChannelBase, double> Ypower(
        "Ypower", "Power for Y gate", &HHChannelBase::setYpower,
        &HHChannelBase::getYpower);
    static ElementValueFinfo<HHChannelBase, double> Zpower(
        "Zpower", "Power for Z gate", &HHChannelBase::setZpower,
        &HHChannelBase::getZpower);
    static ElementValueFinfo<HHChannelBase, int> instant(
        "instant",
        "Bitmapped flag: bit 0 = Xgate, bit 1 = Ygate, bit 2 = Zgate"
        "When true, specifies that the lookup table value should be"
        "used directly as the state of the channel, rather than used"
        "as a rate term for numerical integration for the state",
        &HHChannelBase::setInstant, &HHChannelBase::getInstant);
    static ElementValueFinfo<HHChannelBase, double> X(
        "X", "State variable for X gate", &HHChannelBase::setX,
        &HHChannelBase::getX);
    static ElementValueFinfo<HHChannelBase, double> Y(
        "Y", "State variable for Y gate", &HHChannelBase::setY,
        &HHChannelBase::getY);
    static ElementValueFinfo<HHChannelBase, double> Z(
        "Z", "State variable for Y gate", &HHChannelBase::setZ,
        &HHChannelBase::getZ);
    static ElementValueFinfo<HHChannelBase, int> useConcentration(
        "useConcentration",
        "Flag: when true, use concentration message rather than Vm to"
        "control Z gate",
        &HHChannelBase::setUseConcentration,
        &HHChannelBase::getUseConcentration);
    // MsgSrc definitions
    // IkOut SrcFinfo defined in base classes.
    // MsgDest definitions
    static DestFinfo concen(
        "concen",
        "Incoming message from Concen object to specific conc to use"
        "in the Z gate calculations",
        new EpFunc1<HHChannelBase, double>(&HHChannelBase::handleConc));
    static DestFinfo createGate(
        "createGate",
        "Function to create specified gate."
        "Argument: Gate type [X Y Z]",
        new EpFunc1<HHChannelBase, string>(&HHChannelBase::createGate));
    // FieldElementFinfo definition for HHGates. Note that these are made
    // with the deferCreate flag off, so that the HHGates are created
    // right away even if they are empty.
    // Assume only a single entry allocated in each gate.
    static Finfo *HHChannelBaseFinfos[] = {
        &Xpower,            // Value
        &Ypower,            // Value
        &Zpower,            // Value
        &instant,           // Value
        &X,                 // Value
        &Y,                 // Value
        &Z,                 // Value
        &useConcentration,  // Value
        &concen,            // Dest
        &createGate,        // Dest
        // &gateX,             // FieldElement
        // &gateY,             // FieldElement
        // &gateZ              // FieldElement
    };
    static string doc[] = {
        "Name",
        "HHChannelBase",
        "Author",
        "Upinder S. Bhalla, 2014, NCBS",
        "Description",
        "HHChannelBase: Base class for "
        "Hodgkin-Huxley type voltage-gated Ion channels. Something "
        "like the old tabchannel from GENESIS, but also presents "
        "a similar interface as hhchan from GENESIS. ",
    };
    static ZeroSizeDinfo<int> dinfo;
    static Cinfo HHChannelBaseCinfo(
        "HHChannelBase", ChanBase::initCinfo(), HHChannelBaseFinfos,
        sizeof(HHChannelBaseFinfos) / sizeof(Finfo *), &dinfo, doc,
        sizeof(doc) / sizeof(string));
    return &HHChannelBaseCinfo;
}
References Cinfo::Cinfo(), createGate(), DestFinfo::DestFinfo(), ElementValueFinfo< T, F >::ElementValueFinfo(), EpFunc1< T, A >::EpFunc1(), getInstant(), getUseConcentration(), getX(), getXpower(), getY(), getYpower(), getZ(), getZpower(), handleConc(), ChanBase::initCinfo(), setInstant(), setUseConcentration(), setX(), setXpower(), setY(), setYpower(), setZ(), and setZpower().
Referenced by HHChannel::initCinfo(), HHChannel2D::initCinfo(), HHChannelF::initCinfo(), and ZombieHHChannel::initCinfo().
integrate()
double HHChannelBase::integrate (double state, double dt, double A, double B) protected
Returns the state variable for the new timestep based on the internal variables A_ and B_ which were passed in from the gate.
Definition at line 268 of file HHChannelBase.cpp.
{
    if (B > EPSILON) {
        double x = exp(-B * dt);
        return state * x + (A / B) * (1 - x);
    }
    return state + A * dt;
}
References EPSILON.
Referenced by HHChannel::vProcess(), HHChannel2D::vProcess(), HHChannelF::vProcess(), and HHChannelF2D::vProcess().
power1()
static double HHChannelBase::power1 (double x, double p) inline static
Definition at line 151 of file HHChannelBase.h.
    {
        return x;
    }
Referenced by selectPower().
power2()
static double HHChannelBase::power2 (double x, double p) inline static
Definition at line 155 of file HHChannelBase.h.
    {
        return x * x;
    }
Referenced by power4(), and selectPower().
power3()
static double HHChannelBase::power3 (double x, double p) inline static
Definition at line 159 of file HHChannelBase.h.
    {
        return x * x * x;
    }
Referenced by selectPower().
power4()
static double HHChannelBase::power4 (double x, double p) inline static
Definition at line 163 of file HHChannelBase.h.
    {
        return power2(x * x, p);
    }
References power2().
Referenced by selectPower().
powerN()
double HHChannelBase::powerN (double x, double p) static
Definition at line 330 of file HHChannelBase.cpp.
{
    if (x > 0.0) return exp(p * log(x));
    return 0.0;
}
Referenced by selectPower().
selectPower()
PFDD HHChannelBase::selectPower (double power) static
Definition at line 335 of file HHChannelBase.cpp.
{
    if (doubleEq(power, 0.0))
        return powerN;
    else if (doubleEq(power, 1.0))
        return power1;
    else if (doubleEq(power, 2.0))
        return power2;
    else if (doubleEq(power, 3.0))
        return power3;
    else if (doubleEq(power, 4.0))
        return power4;
    else
        return powerN;
}
References doubleEq(), power1(), power2(), power3(), power4(), and powerN().
Referenced by vSetXpower(), vSetYpower(), and vSetZpower().
setGatePower()
bool HHChannelBase::setGatePower (const Eref & e, double power, double * assignee, const string & gateType)
Utility for altering gate powers
Definition at line 350 of file HHChannelBase.cpp.
{
    if (power < 0) {
        cout << "Error: HHChannel2D::set" << gateType
             << "power: Cannot use negative power: " << power << endl;
        return false;
    }
    if (doubleEq(power, *assignee)) return false;
    if (doubleEq(*assignee, 0.0) && power > 0) {
        createGate(e, gateType);
    } else if (doubleEq(power, 0.0)) {
        destroyGate(e, gateType);
    }
    *assignee = power;
    return true;
}
References createGate(), destroyGate(), and doubleEq().
Referenced by vSetXpower(), vSetYpower(), and vSetZpower().
setInstant()
void HHChannelBase::setInstant (const Eref & e, int Instant)
Definition at line 205 of file HHChannelBase.cpp.
{
    vSetInstant(e, instant);
}
References vSetInstant().
Referenced by initCinfo().
setNumGates()
void HHChannelBase::setNumGates (unsigned int num)
Dummy assignment function for the number of gates.
setUseConcentration()
void HHChannelBase::setUseConcentration (const Eref & e, int value)
Definition at line 219 of file HHChannelBase.cpp.
{
    vSetUseConcentration(e, value);
}
References vSetUseConcentration().
Referenced by initCinfo().
setX()
void HHChannelBase::setX (const Eref & e, double X)
Definition at line 210 of file HHChannelBase.cpp.
{ vSetX(e, X); }
References vSetX().
Referenced by initCinfo().
setXpower()
void HHChannelBase::setXpower (const Eref & e, double power)
Assigns the Xpower for this gate. If the gate exists and has only this element for input, then change the gate value. If the gate exists and has multiple parents, then make a new gate. If the gate does not exist, make a new gate
Definition at line 168 of file HHChannelBase.cpp.
{
    if (checkPower(power)) vSetXpower(e, power);
}
References checkPower(), and vSetXpower().
Referenced by HHChannel2D::initCinfo(), and initCinfo().
setY()
void HHChannelBase::setY (const Eref & e, double Y)
Definition at line 213 of file HHChannelBase.cpp.
{ vSetY(e, Y); }
References vSetY().
Referenced by initCinfo().
setYpower()
void HHChannelBase::setYpower (const Eref & e, double Ypower)
Definition at line 172 of file HHChannelBase.cpp.
{
    if (checkPower(power)) vSetYpower(e, power);
}
References checkPower(), and vSetYpower().
Referenced by HHChannel2D::initCinfo(), and initCinfo().
setZ()
void HHChannelBase::setZ (const Eref & e, double Z)
Definition at line 216 of file HHChannelBase.cpp.
{ vSetZ(e, Z); }
References vSetZ().
Referenced by initCinfo().
setZpower()
void HHChannelBase::setZpower (const Eref & e, double Zpower)
Definition at line 176 of file HHChannelBase.cpp.
{
    if (checkPower(power)) vSetZpower(e, power);
}
References checkPower(), and vSetZpower().
Referenced by HHChannel2D::initCinfo(), and initCinfo().
vCreateGate()
virtual void HHChannelBase::vCreateGate (const Eref & e, string gateType) pure virtual
Implemented in HHChannel, HHChannel2D, HHChannelF, HHChannelF2D, and ZombieHHChannel.
Referenced by createGate().
vGetInstant()
int HHChannelBase::vGetInstant (const Eref & e) const virtual
Reimplemented in ZombieHHChannel.
Definition at line 231 of file HHChannelBase.cpp.
{ return instant_; }
References instant_.
Referenced by getInstant().
vGetX()
double HHChannelBase::vGetX (const Eref & e) const virtual
Reimplemented in ZombieHHChannel.
Definition at line 237 of file HHChannelBase.cpp.
{ return X_; }
References X_.
Referenced by getX().
vGetY()
double HHChannelBase::vGetY (const Eref & e) const virtual
Reimplemented in ZombieHHChannel.
Definition at line 243 of file HHChannelBase.cpp.
{ return Y_; }
References Y_.
Referenced by getY().
vGetZ()
double HHChannelBase::vGetZ (const Eref & e) const virtual
Reimplemented in ZombieHHChannel.
Definition at line 249 of file HHChannelBase.cpp.
{ return Z_; }
References Z_.
Referenced by getZ().
vHandleConc()
void HHChannelBase::vHandleConc (const Eref & e, double conc) virtual
Reimplemented in HHChannel, HHChannelF, and ZombieHHChannel.
Definition at line 276 of file HHChannelBase.cpp.
{
    cerr << "HHChannelBase::vHandleConc: This function should never be called."
         << endl;
}
Referenced by handleConc().
vSetInstant()
void HHChannelBase::vSetInstant (const Eref & e, int Instant) virtual
Reimplemented in ZombieHHChannel.
Definition at line 227 of file HHChannelBase.cpp.
{
    instant_ = instant;
}
References instant_.
Referenced by setInstant().
vSetSolver()
void HHChannelBase::vSetSolver (const Eref & e, Id hsolve) virtual
Reimplemented in ZombieHHChannel.
Definition at line 393 of file HHChannelBase.cpp.
{ ; }
Referenced by zombify().
vSetUseConcentration()
void HHChannelBase::vSetUseConcentration (const Eref & e, int value) virtual
Reimplemented in ZombieHHChannel.
Definition at line 251 of file HHChannelBase.cpp.
{
    useConcentration_ = value;
}
References useConcentration_.
Referenced by setUseConcentration().
vSetX()
void HHChannelBase::vSetX (const Eref & e, double X) virtual
Reimplemented in ZombieHHChannel.
Definition at line 233 of file HHChannelBase.cpp.
{
    X_ = X;
    xInited_ = true;
}
References X_, and xInited_.
Referenced by setX().
vSetXpower()
void HHChannelBase::vSetXpower (const Eref & e, double power) virtual
Assigns the Xpower for this gate. If the gate exists and has only this element for input, then change the gate value. If the gate exists and has multiple parents, then make a new gate. If the gate does not exist, make a new gate
Reimplemented in ZombieHHChannel.
Definition at line 376 of file HHChannelBase.cpp.
{
    if (setGatePower(e, power, &Xpower_, "X")) takeXpower_ = selectPower(power);
}
References selectPower(), setGatePower(), takeXpower_, and Xpower_.
Referenced by setXpower(), and zombify().
vSetY()
void HHChannelBase::vSetY (const Eref & e, double Y) virtual
Reimplemented in ZombieHHChannel.
Definition at line 239 of file HHChannelBase.cpp.
{
    Y_ = Y;
    yInited_ = true;
}
References Y_, and yInited_.
Referenced by setY().
vSetYpower()
void HHChannelBase::vSetYpower (const Eref & e, double Ypower) virtual
Reimplemented in ZombieHHChannel.
Definition at line 380 of file HHChannelBase.cpp.
{
    if (setGatePower(e, power, &Ypower_, "Y")) takeYpower_ = selectPower(power);
}
References selectPower(), setGatePower(), takeYpower_, and Ypower_.
Referenced by setYpower(), and zombify().
vSetZ()
void HHChannelBase::vSetZ (const Eref & e, double Z) virtual
Reimplemented in ZombieHHChannel.
Definition at line 245 of file HHChannelBase.cpp.
{
    Z_ = Z;
    zInited_ = true;
}
References Z_, and zInited_.
Referenced by setZ().
vSetZpower()
void HHChannelBase::vSetZpower (const Eref & e, double Zpower) virtual
Reimplemented in ZombieHHChannel.
Definition at line 384 of file HHChannelBase.cpp.
{
    if (setGatePower(e, power, &Zpower_, "Z")) {
        takeZpower_ = selectPower(power);
        useConcentration_ = 1;  // Not sure about this.
    }
}
References selectPower(), setGatePower(), takeZpower_, useConcentration_, and Zpower_.
Referenced by setZpower(), and zombify().
zombify()
void HHChannelBase::zombify (Element * orig, const Cinfo * zClass, Id hsolve) static
Definition at line 395 of file HHChannelBase.cpp.
{
    if (orig->cinfo() == zClass) return;
    unsigned int start = orig->localDataStart();
    unsigned int num = orig->numLocalData();
    if (num == 0) return;
    // Parameters are Gbar, Ek, Xpower, Ypower, Zpower, useConcentration
    // We also want to haul the original gates over, this is done earlier
    // in the HSolve building process. So just six terms.
    vector<double> chandata(num * 6, 0.0);
    vector<double>::iterator j = chandata.begin();
    for (unsigned int i = 0; i < num; ++i) {
        Eref er(orig, i + start);
        const HHChannelBase *hb =
            reinterpret_cast<const HHChannelBase *>(er.data());
        *j = hb->vGetGbar(er);
        *(j + 1) = hb->vGetEk(er);
        *(j + 2) = hb->getXpower(er);
        *(j + 3) = hb->getYpower(er);
        *(j + 4) = hb->getZpower(er);
        *(j + 5) = hb->getUseConcentration(er);
        j += 6;
    }
    orig->zombieSwap(zClass);
    j = chandata.begin();
    for (unsigned int i = 0; i < num; ++i) {
        Eref er(orig, i + start);
        HHChannelBase *hb = reinterpret_cast<HHChannelBase *>(er.data());
        hb->vSetSolver(er, hsolve);
        hb->vSetGbar(er, *j);
        hb->vSetEk(er, *(j + 1));
        hb->vSetXpower(er, *(j + 2));
        hb->vSetYpower(er, *(j + 3));
        hb->vSetZpower(er, *(j + 4));
        // hb->vSetUseConcentration( er, *(j+5) > 0.5 );
        // Disable this assignment because the Solver already reads the
        // value, and it triggers an error msg.
        j += 6;
    }
}
References Element::cinfo(), Eref::data(), Eref::Eref(), getUseConcentration(), getXpower(), getYpower(), getZpower(), Element::localDataStart(), Element::numLocalData(), ChanCommon::vGetEk(), ChanCommon::vGetGbar(), ChanCommon::vSetEk(), ChanCommon::vSetGbar(), vSetSolver(), vSetXpower(), vSetYpower(), vSetZpower(), and Element::zombieSwap().
Referenced by HSolve::unzombify(), and HSolve::zombify().
Member Data Documentation
EPSILON
const double HHChannelBase::EPSILON = 1.0e-10 static protected
Definition at line 208 of file HHChannelBase.h.
Referenced by integrate(), HHChannel::vReinit(), HHChannel2D::vReinit(), HHChannelF::vReinit(), and HHChannelF2D::vReinit().
g_
double HHChannelBase::g_ protected
Definition at line 203 of file HHChannelBase.h.
Referenced by HHChannelBase(), HHChannel::vProcess(), HHChannel2D::vProcess(), HHChannelF::vProcess(), HHChannelF2D::vProcess(), HHChannel::vReinit(), HHChannel2D::vReinit(), HHChannelF::vReinit(), and HHChannelF2D::vReinit().
instant_
int HHChannelBase::instant_ protected
Bitmasked flag indicating which gates are to be computed as instantaneous (i.e., no integration)
Definition at line 200 of file HHChannelBase.h.
Referenced by HHChannelBase(), vGetInstant(), HHChannel::vProcess(), HHChannel2D::vProcess(), HHChannelF::vProcess(), HHChannelF2D::vProcess(), and vSetInstant().
INSTANT_X
const int HHChannelBase::INSTANT_X = 1 static protected
Definition at line 209 of file HHChannelBase.h.
Referenced by HHChannel::vProcess(), HHChannel2D::vProcess(), HHChannelF::vProcess(), and HHChannelF2D::vProcess().
INSTANT_Y
const int HHChannelBase::INSTANT_Y = 2 static protected
Definition at line 210 of file HHChannelBase.h.
Referenced by HHChannel::vProcess(), HHChannel2D::vProcess(), HHChannelF::vProcess(), and HHChannelF2D::vProcess().
INSTANT_Z
const int HHChannelBase::INSTANT_Z = 4 static protected
Definition at line 211 of file HHChannelBase.h.
Referenced by HHChannel::vProcess(), HHChannel2D::vProcess(), HHChannelF::vProcess(), and HHChannelF2D::vProcess().
myId_
Id HHChannelBase::myId_ protected
conductance without modulation component is different from Gk_ in ChanCommon
Definition at line 206 of file HHChannelBase.h.
Referenced by HHChannelBase().
takeXpower_
double(* HHChannelBase::takeXpower_) (double, double) protected
Function pointers to specific power calculation function. This is an optimization to avoid the full pow function for simple commonly occurring integer exponents
Definition at line 185 of file HHChannelBase.h.
Referenced by HHChannel::vProcess(), HHChannel2D::vProcess(), HHChannelF::vProcess(), HHChannelF2D::vProcess(), HHChannel::vReinit(), HHChannel2D::vReinit(), HHChannelF::vReinit(), HHChannelF2D::vReinit(), and vSetXpower().
takeYpower_
double(* HHChannelBase::takeYpower_) (double, double) protected
Definition at line 186 of file HHChannelBase.h.
Referenced by HHChannel::vProcess(), HHChannel2D::vProcess(), HHChannelF::vProcess(), HHChannelF2D::vProcess(), HHChannel::vReinit(), HHChannel2D::vReinit(), HHChannelF::vReinit(), HHChannelF2D::vReinit(), and vSetYpower().
takeZpower_
double(* HHChannelBase::takeZpower_) (double, double) protected
Definition at line 187 of file HHChannelBase.h.
Referenced by HHChannel::vProcess(), HHChannel2D::vProcess(), HHChannelF::vProcess(), HHChannelF2D::vProcess(), HHChannel::vReinit(), HHChannel2D::vReinit(), HHChannelF::vReinit(), HHChannelF2D::vReinit(), and vSetZpower().
useConcentration_
bool HHChannelBase::useConcentration_ protected
Flag for use of conc for input to Z gate calculations.
Definition at line 195 of file HHChannelBase.h.
Referenced by getUseConcentration(), HHChannelBase(), HHChannel::vProcess(), HHChannelF::vProcess(), HHChannel::vReinit(), HHChannelF::vReinit(), vSetUseConcentration(), and vSetZpower().
X_
double HHChannelBase::X_ protected
Definition at line 202 of file HHChannelBase.h.
Referenced by HHChannelBase(), vGetX(), HHChannel::vProcess(), HHChannel2D::vProcess(), HHChannelF::vProcess(), HHChannelF2D::vProcess(), HHChannel::vReinit(), HHChannel2D::vReinit(), HHChannelF::vReinit(), HHChannelF2D::vReinit(), and vSetX().
xInited_
bool HHChannelBase::xInited_ protected
Flag to indicate if gates have been created.
Definition at line 197 of file HHChannelBase.h.
Referenced by HHChannelBase(), HHChannel::vReinit(), HHChannel2D::vReinit(), HHChannelF::vReinit(), HHChannelF2D::vReinit(), and vSetX().
Xpower_
double HHChannelBase::Xpower_ protected
Exponent for X gate.
Definition at line 189 of file HHChannelBase.h.
Referenced by getXpower(), HHChannelBase(), HHChannel::vProcess(), HHChannel2D::vProcess(), HHChannelF::vProcess(), HHChannelF2D::vProcess(), HHChannel::vReinit(), HHChannel2D::vReinit(), HHChannelF::vReinit(), HHChannelF2D::vReinit(), vSetXpower(), ZombieHHChannel::vSetXpower(), ZombieHHChannel::vSetYpower(), and ZombieHHChannel::vSetZpower().
Y_
double HHChannelBase::Y_ protected
Definition at line 202 of file HHChannelBase.h.
Referenced by HHChannelBase(), vGetY(), HHChannel::vProcess(), HHChannel2D::vProcess(), HHChannelF::vProcess(), HHChannelF2D::vProcess(), HHChannel::vReinit(), HHChannel2D::vReinit(), HHChannelF::vReinit(), HHChannelF2D::vReinit(), and vSetY().
yInited_
bool HHChannelBase::yInited_ protected
Definition at line 197 of file HHChannelBase.h.
Referenced by HHChannelBase(), HHChannel::vReinit(), HHChannel2D::vReinit(), HHChannelF::vReinit(), HHChannelF2D::vReinit(), and vSetY().
Ypower_
double HHChannelBase::Ypower_ protected
Exponent for Y gate.
Definition at line 191 of file HHChannelBase.h.
Referenced by getYpower(), HHChannelBase(), HHChannel::vProcess(), HHChannel2D::vProcess(), HHChannelF::vProcess(), HHChannelF2D::vProcess(), HHChannel::vReinit(), HHChannel2D::vReinit(), HHChannelF::vReinit(), HHChannelF2D::vReinit(), ZombieHHChannel::vSetXpower(), vSetYpower(), ZombieHHChannel::vSetYpower(), and ZombieHHChannel::vSetZpower().
Z_
double HHChannelBase::Z_ protected
Definition at line 202 of file HHChannelBase.h.
Referenced by HHChannelBase(), vGetZ(), HHChannel::vProcess(), HHChannel2D::vProcess(), HHChannelF::vProcess(), HHChannelF2D::vProcess(), HHChannel::vReinit(), HHChannel2D::vReinit(), HHChannelF::vReinit(), HHChannelF2D::vReinit(), and vSetZ().
zInited_
bool HHChannelBase::zInited_ protected
Definition at line 197 of file HHChannelBase.h.
Referenced by HHChannelBase(), HHChannel::vReinit(), HHChannel2D::vReinit(), HHChannelF::vReinit(), HHChannelF2D::vReinit(), and vSetZ().
Zpower_
double HHChannelBase::Zpower_ protected
Exponent for Z gate.
Definition at line 193 of file HHChannelBase.h.
Referenced by getZpower(), HHChannelBase(), HHChannel::vProcess(), HHChannel2D::vProcess(), HHChannelF::vProcess(), HHChannelF2D::vProcess(), HHChannel::vReinit(), HHChannel2D::vReinit(), HHChannelF::vReinit(), HHChannelF2D::vReinit(), ZombieHHChannel::vSetXpower(), ZombieHHChannel::vSetYpower(), vSetZpower(), and ZombieHHChannel::vSetZpower().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/biophysics/HHChannelBase.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/biophysics/HHChannelBase.cpp