MOOSE - Multiscale Object Oriented Simulation Environment: SharedFinfo Class Reference
SharedFinfo Class Reference
#include <SharedFinfo.h>
Public Member Functions
bool addMsg (const Finfo *target, ObjId mid, Element *src) const
bool checkTarget (const Finfo *target) const
const vector< Finfo * > & dest () const
vector< string > innerDest () const
vector< string > innerSrc () const
void registerFinfo (Cinfo *c)
string rttiType () const
This always returns void. We need to check the subsidiary Finfos.
SharedFinfo (const string &name, const string &doc, Finfo **entries, unsigned int numEntries)
const vector< SrcFinfo * > & src () const
bool strGet (const Eref &tgt, const string &field, string &returnValue) const
bool strSet (const Eref &tgt, const string &field, const string &arg) const
~SharedFinfo ()
Public Member Functions inherited from Finfo
const string & docs () const
Returns documentation string.
Finfo (const string &name, const string &doc)
const string & name () const
virtual void postCreationFunc (Id newId, Element *newElm) const
virtual ~Finfo ()
Private Attributes
vector< Finfo * > dest_
vector< SrcFinfo * > src_
Additional Inherited Members
Static Public Member Functions inherited from Finfo
static const Cinfo * initCinfo ()
Detailed Description
This is a SharedFinfo, which wraps an arbitrary set of regular Src and Dest Messages. Its main job is to do typechecking for setting up multiple data streams to go across the same Msg.
Definition at line 18 of file SharedFinfo.h.
Constructor & Destructor Documentation
SharedFinfo()
SharedFinfo::SharedFinfo (const string & name, const string & doc, Finfo ** entries, unsigned int numEntries)
This set of classes define Message Sources. Their main job is to supply a type-safe send operation, and to provide typechecking for it.
Definition at line 16 of file SharedFinfo.cpp.
    : Finfo( name, doc )
{
    for ( unsigned int i = 0; i < numEntries; ++i )
    {
        Finfo* foo = entries[i];
        SrcFinfo* s = dynamic_cast< SrcFinfo* >( foo );
        // SrcFinfo* s = dynamic_cast< SrcFinfo* >( entries[i] );
        if ( s != 0 )
            src_.push_back( s );
        else
            dest_.push_back( entries[i] );
    }
}
References dest_, Finfo::Finfo(), and src_.
Referenced by Test::initCinfo(), CaConcBase::initCinfo(), ChanBase::initCinfo(), moose::CompartmentBase::initCinfo(), DifBufferBase::initCinfo(), DifShellBase::initCinfo(), GapJunction::initCinfo(), IntFire::initCinfo(), IzhikevichNrn::initCinfo(), MarkovOdeSolver::initCinfo(), MarkovRateTable::initCinfo(), MarkovSolver::initCinfo(), MarkovSolverBase::initCinfo(), MMPump::initCinfo(), RandSpike::initCinfo(), SpikeGen::initCinfo(), SymCompartment::initCinfo(), moose::VClamp::initCinfo(), Arith::initCinfo(), Function::initCinfo(), Interpol::initCinfo(), Interpol2D::initCinfo(), SocketStreamer::initCinfo(), Stats::initCinfo(), StimulusTable::initCinfo(), Streamer::initCinfo(), Table::initCinfo(), TimeTable::initCinfo(), DiffAmp::initCinfo(), PIDController::initCinfo(), PulseGen::initCinfo(), RC::initCinfo(), Dsolve::initCinfo(), Cell::initCinfo(), HSolve::initCinfo(), ConcChan::initCinfo(), Enz::initCinfo(), EnzBase::initCinfo(), Reac::initCinfo(), Species::initCinfo(), Gsolve::initCinfo(), Ksolve::initCinfo(), MeshEntry::initCinfo(), PostMaster::initCinfo(), PyRun::initCinfo(), Clock::initCinfo(), Adaptor::initCinfo(), SynHandlerBase::initCinfo(), PoolBase::initPoolBaseCinfo(), and sharedProcVec().
~SharedFinfo()
SharedFinfo::~SharedFinfo () inline
Definition at line 24 of file SharedFinfo.h.
{;}
Member Function Documentation
addMsg()
bool SharedFinfo::addMsg (const Finfo * target, ObjId mid, Element * src) const virtual
First calls checkTarget on all targets, then sets up message. Returns true on success.
Reimplemented from Finfo.
Definition at line 95 of file SharedFinfo.cpp.
{
    if ( !checkTarget( target ) )
        return 0;
    const SharedFinfo* tgt = dynamic_cast< const SharedFinfo* >( target );
    // We have a problem if the src and dest elms (e1 and e2) are the
    // same, because this messes up the logic to assign the isForward flag.
    // This is an issue only if the target Finfo wants to send data back.
    // In other words, there are dest_ finfos on this SharedFinfo.
    // Report this problem.
    const Msg* m = Msg::getMsg( mid );
    assert( m->e1() == srcElm );
    Element* destElm = m->e2();
    if ( srcElm == destElm && srcElm->id() != Id() ) {
        if ( dest_.size() > 0 ) {
            cout << "Error: SharedFinfo::addMsg: MessageId " << mid <<
            endl <<
            "Source Element == DestElement == " << srcElm->getName() <<
            endl << "Recommend that you individually set up messages for" <<
            " the components of the SharedFinfo, to ensure that the " <<
            "direction of messaging is consistent.\n";
            return 0;
        }
    }
    for ( unsigned int i = 0; i < src_.size(); ++i ) {
        if ( !src_[i]->addMsg( tgt->dest_[i], mid, srcElm ) ) {
            // Should never happen. The checkTarget should preclude this.
            cerr << "Error:SharedFinfo::addMsg: Failed on MessageId " <<
                mid << ", unrecoverable\n";
            exit(0);
        }
    }
    for ( unsigned int i = 0; i < tgt->src_.size(); ++i ) {
        if ( !tgt->src_[i]->addMsg( dest_[i], mid, destElm ) ) {
            // Should never happen. The checkTarget should preclude this.
            cerr << "Error:SharedFinfo::addMsg: Failed on MessageId " <<
                mid << ", unrecoverable\n";
            exit( 0 );
        }
    }
    return 1;
}
References SrcFinfo::addMsg(), checkTarget(), dest_, Msg::e1(), Msg::e2(), Msg::getMsg(), Element::getName(), Id::Id(), Element::id(), Id::operator!=(), and src_.
checkTarget()
bool SharedFinfo::checkTarget (const Finfo * target) const virtual
Checks that the type of target Finfo matches self, and is safe to exchange messages with.
It is possible that we have DestFinfos in this SharedFinfo, that have not been registered. So we need to scan through. Note that the register operation overwrites values if they already exist. Best not to have conflicts!.
Reimplemented from Finfo.
Definition at line 74 of file SharedFinfo.cpp.
{
    const SharedFinfo* tgt = dynamic_cast< const SharedFinfo* >( target );
    if ( tgt ) {
        if ( src_.size() != tgt->dest_.size() &&
            dest_.size() != tgt->src_.size() )
            return 0;
        for ( unsigned int i = 0; i < src_.size(); ++i ) {
            if ( !src_[i]->checkTarget( tgt->dest_[i] ) )
                return 0;
        }
        for ( unsigned int i = 0; i < tgt->src_.size(); ++i ) {
            if ( !tgt->src_[i]->checkTarget( dest_[i] ) )
                return 0;
        }
        return 1;
    }
    return 0;
}
References SrcFinfo::checkTarget(), dest_, and src_.
Referenced by addMsg().
dest()
const vector< Finfo * > & SharedFinfo::dest () const
Definition at line 150 of file SharedFinfo.cpp.
{
    return dest_;
}
References dest_.
Referenced by Element::getNeighbors(), insertSharedMsgs(), and Element::showFields().
innerDest()
vector< string > SharedFinfo::innerDest () const virtual
Returns subsidiary DestFinfos
Reimplemented from Finfo.
Definition at line 167 of file SharedFinfo.cpp.
{
    vector< string > ret;
    for ( vector< Finfo* >::const_iterator i = dest_.begin();
        i != dest_.end(); ++i )
        ret.push_back( (*i)->name() );
    return ret;
}
References dest_, and Finfo::name().
innerSrc()
vector< string > SharedFinfo::innerSrc () const virtual
Returns subsidiary SrcFinfos
Reimplemented from Finfo.
Definition at line 158 of file SharedFinfo.cpp.
{
    vector< string > ret;
    for ( vector< SrcFinfo* >::const_iterator i = src_.begin();
        i != src_.end(); ++i )
        ret.push_back( (*i)->name() );
    return ret;
}
References Finfo::name(), and src_.
registerFinfo()
void SharedFinfo::registerFinfo (Cinfo * c) virtual
Returns string-ified form to handle template expectations for name field string getName() const; Assign function Ids, bindIndex and so on.
Implements Finfo.
Definition at line 32 of file SharedFinfo.cpp.
{
    for( vector< SrcFinfo* >::iterator i =
        src_.begin(); i != src_.end(); ++i)
        c->registerFinfo( *i );
    for( vector< Finfo* >::iterator i =
        dest_.begin(); i != dest_.end(); ++i)
        c->registerFinfo( *i );
}
References dest_, Cinfo::registerFinfo(), and src_.
rttiType()
string SharedFinfo::rttiType () const virtual
This always returns void. We need to check the subsidiary Finfos.
Reimplemented from Finfo.
Definition at line 176 of file SharedFinfo.cpp.
{
    return "void";
}
src()
const vector< SrcFinfo * > & SharedFinfo::src () const
Definition at line 144 of file SharedFinfo.cpp.
{
    return src_;
}
References src_.
Referenced by Element::getNeighbors(), and Element::showFields().
strGet()
bool SharedFinfo::strGet (const Eref & tgt, const string & field, string & returnValue) const virtual
Function to return value of field into a string argument. Returns true on success. Normally called only from SetGet::strGet.
Implements Finfo.
Definition at line 48 of file SharedFinfo.cpp.
{
    return 0;
}
strSet()
bool SharedFinfo::strSet (const Eref & tgt, const string & field, const string & arg) const virtual
Function to set this field using a string argument. Returns true on success. Normally called only from SetGet::strSet.
Implements Finfo.
Definition at line 42 of file SharedFinfo.cpp.
{
    return 0;
}
Member Data Documentation
dest_
vector< Finfo* > SharedFinfo::dest_ private
Definition at line 60 of file SharedFinfo.h.
Referenced by addMsg(), checkTarget(), dest(), innerDest(), registerFinfo(), and SharedFinfo().
src_
vector< SrcFinfo* > SharedFinfo::src_ private
Definition at line 59 of file SharedFinfo.h.
Referenced by addMsg(), checkTarget(), innerSrc(), registerFinfo(), SharedFinfo(), and src().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/basecode/SharedFinfo.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/basecode/SharedFinfo.cpp