MOOSE - Multiscale Object Oriented Simulation Environment: PresynMesh Class Reference
PresynMesh Class Reference
#include <PresynMesh.h>
Public Member Functions
void buildOnDendrites (vector< ObjId > v, double spacing)
void buildOnSpineHeads (vector< ObjId > v)
Requires that all objects in v are the head compartments of spines.
double extendedMeshEntryVolume (unsigned int fid) const
Volume of mesh Entry including abutting diff-coupled voxels.
vector< double > getAllBoutonOrientation () const
Already handled by voxelMidpoint.
vector< double > getAllBoutonVolumes () const
vector< int > getBoutonIndexOnTargetCompartments () const
double getBoutonSpacing () const
Spacing between boutons if compartments are dendrite segments.
vector< double > getCoordinates (unsigned int fid) const
Virtual function to return coords of mesh Entry.
vector< double > getDiffusionArea (unsigned int fid) const
Virtual function to return diffusion X-section area.
vector< double > getDiffusionScaling (unsigned int fid) const
Virtual function to return scale factor for diffusion. 1 here.
vector< Id > getElecComptMap () const
Complementary func returning vec of Ids, to match other Meshes.
vector< unsigned int > getEndVoxelInCompt () const
unsigned int getMeshDimensions (unsigned int fid) const
Virtual function to return dimensions of specified entry.
double getMeshEntryVolume (unsigned int fid) const
Virtual function to return volume of mesh Entry.
unsigned int getMeshType (unsigned int fid) const
Virtual function to return MeshType of specified entry.
unsigned int getNumBoutons () const
Report the number of boutons defined on mesh.
int getNumBoutonsOnCompartment (ObjId b) const
vector< unsigned int > getParentVoxel () const
Inherited virtual, do nothing for now.
vector< ObjId > getPostsynCompts () const
int getStartBoutonIndexFromCompartment (ObjId b) const
Already handled by oneVoxelVolume.
vector< unsigned int > getStartVoxelInCompt () const
vector< ObjId > getTargetCompartments () const
Returns the compartments to which each bouton projects.
const vector< double > & getVoxelArea () const
const vector< double > & getVoxelLength () const
void indexToSpace (unsigned int index, double &x, double &y, double &z) const
void innerBuildDefaultMesh (const Eref &e, double volume, unsigned int numEntries)
Virtual func to make a mesh with specified Volume and numEntries.
unsigned int innerGetDimensions () const
Virtual function to return # of spatial dimensions of mesh.
unsigned int innerGetNumEntries () const
void innerHandleNodeInfo (const Eref &e, unsigned int numNodes, unsigned int numThreads)
void innerHandleRequestMeshStats (const Eref &e, const SrcFinfo2< unsigned int, vector< double > > *meshStatsFinfo)
More inherited virtual funcs: request comes in for mesh stats.
void innerSetNumEntries (unsigned int n)
Inherited virtual func.
bool isOnSpines () const
Reports if this set of boutons is connected to spines vs dend.
void matchMeshEntries (const ChemCompt *other, vector< VoxelJunction > &ret) const
double nearest (double x, double y, double z, unsigned int &index) const
PresynMesh ()
void setAllBoutonVolumes (vector< double > &vols)
void setRadiusStats (double r, double sdev)
double vGetEntireVolume () const
Inherited virtual. Returns entire volume of compartment.
const vector< double > & vGetVoxelMidpoint () const
Virtual func so that derived classes can return voxel midpoint.
const vector< double > & vGetVoxelVolume () const
Virtual func so that derived classes can pass voxel volume back.
bool vSetVolumeNotRates (double volume)
Inherited virtual. Resizes len and dia of each voxel.
~PresynMesh ()
Public Member Functions inherited from MeshCompt
void addRow (unsigned int index, const vector< double > &entry, const vector< unsigned int > &colIndex)
void clearExtendedMeshEntryVolume ()
Inherited virtual function to clear the vector of MeshEntryVolume.
void extendStencil (const ChemCompt *other, const vector< VoxelJunction > &vj)
Add boundary voxels to stencil for cross-solver junctions.
vector< unsigned int > getNeighbors (unsigned int fid) const
Looks up stencil to return vector of indices of coupled voxels.
const SparseMatrix< double > & getStencil () const
Returns entire sparse matrix of mesh. Used by diffusion solver.
unsigned int getStencilRow (unsigned int meshIndex, const double **entry, const unsigned int **colIndex) const
vector< double > innerGetStencilRate (unsigned int row) const
void innerResetStencil ()
virtual func implemented here.
MeshCompt ()
void setStencilSize (unsigned int numRows, unsigned int numCols)
~MeshCompt ()
Public Member Functions inherited from ChemCompt
void buildDefaultMesh (const Eref &e, double volume, unsigned int numEntries)
void buildJunction (ChemCompt *other, vector< VoxelJunction > &ret)
ChemCompt ()
void flipRet (vector< VoxelJunction > &ret) const
Utility function for swapping first and second in VoxelJunctions.
void getChildConcs (const Eref &e, vector< double > &childConcs) const
unsigned int getDimensions () const
double getEntireVolume (const Eref &e) const
bool getIsMembraneBound () const
string getMethod () const
unsigned int getNumEntries () const
vector< double > getOneVoxelMidpoint (unsigned int vox) const
Looks up specified voxel midpoint, from vGetVoxelMidpoint.
double getOneVoxelVolume (const Eref &e, unsigned int voxel) const
vector< unsigned int > getStencilIndex (unsigned int row) const
vector< double > getStencilRate (unsigned int row) const
vector< double > getVoxelMidpoint () const
Returns vector of all voxel midpoints in compartment.
vector< double > getVoxelVolume () const
Returns vector of all voxel volumes in compartment.
void handleNodeInfo (const Eref &e, unsigned int numNodes, unsigned int numThreads)
MeshEntry * lookupEntry (unsigned int index)
void resetStencil ()
unsigned int setChildConcs (const Eref &e, const vector< double > &childConcs, unsigned int start) const
void setEntireVolume (const Eref &e, double volume)
void setIsMembraneBound (bool v)
virtual void setMeshEntryVolume (unsigned int fid, double volume)
void setMethod (string method)
void setNumEntries (unsigned int num)
void setOneVoxelVolume (const Eref &e, unsigned int voxel, double volume)
void setVolumeNotRates (double volume)
virtual ~ChemCompt ()
Static Public Member Functions
static const Cinfo * initCinfo ()
We assume the bouton to be a hemisphere.
Static Public Member Functions inherited from ChemCompt
static double distance (double x, double y, double z)
static const Cinfo * initCinfo ()
static SrcFinfo1< vector< double > > * voxelVolOut ()
Private Attributes
vector< Bouton > boutons_
These are the data structures for each of the boutons.
bool isOnSpines_
Flag: Is it on spines or along a dendritic tree?
double spacing_
spacing of presyn boutons along the NeuroMesh (dendrite).
Detailed Description
The PresynMesh is a set of synaptic boutons, all having the same reactions. No diffusion between them so it is easy. Two ways to set up: by matching one-to-one to a list of spines, or by matching many-to-one to dendritic segments.
Definition at line 40 of file PresynMesh.h.
Constructor & Destructor Documentation
PresynMesh()
PresynMesh::PresynMesh ()
Definition at line 185 of file PresynMesh.cpp.
    :
        isOnSpines_( false ),
        spacing_( 100e-6 )
{
    ;
}
References isOnSpines_, and spacing_.
~PresynMesh()
PresynMesh::~PresynMesh ()
Definition at line 193 of file PresynMesh.cpp.
{
    ;
}
Member Function Documentation
buildOnDendrites()
void PresynMesh::buildOnDendrites (vector< ObjId > v, double spacing)
Definition at line 413 of file PresynMesh.cpp.
{
    isOnSpines_ = false;
    spacing_ = spacing;
    boutons_.clear();
    for ( ObjId& v : compts ) {
        if ( !v.element()->cinfo()->isA( "CompartmentBase" ) )  {
            cout << "Error: Attempt to assign PresynMesh to a non_compartment: " << v.id.path() << endl;
            assert( 0 );
        }
        double length = Field< double >::get( v, "length" );
        double radius = Field< double >::get( v, "diameter" ) / 2.0;
        double x = Field< double >::get( v, "x" );
        double y = Field< double >::get( v, "y" );
        double z = Field< double >::get( v, "z" );
        double x0 = Field< double >::get( v, "x0" );
        double y0 = Field< double >::get( v, "y0" );
        double z0 = Field< double >::get( v, "z0" );
        Vec v0( x0, y0, z0 );
        Vec v1( x, y, z );
        Vec vAxial( v1 - v0 );
        Vec vRadial1( 0, 0, 0);
        Vec vRadial2( 0, 0, 0);
        vAxial.orthogonalAxes( vRadial1, vRadial2 );
        for (double r = 0.5 * spacing; r < length; r += spacing) {
            Bouton b;
            b.postsynCompt_ = v;
            b.vx_ = -vRadial1.a0(); // Components of the radial unit vector
            b.vy_ = -vRadial1.a1();
            b.vz_ = -vRadial1.a2();
            b.x_ = x0 + (r/length) * (x - x0) - (radius + 20e-9) * b.vx_;
            b.y_ = y0 + (r/length) * (y - y0) - (radius + 20e-9) * b.vy_;
            b.z_ = z0 + (r/length) * (z - z0) - (radius + 20e-9) * b.vz_;
            b.volume_ = DEFAULT_BOUTON_VOLUME;
            boutons_.push_back( b );
        }
    }
}
References Vec::a0(), Vec::a1(), Vec::a2(), boutons_, Element::cinfo(), DEFAULT_BOUTON_VOLUME, ObjId::element(), Field< A >::get(), ObjId::id, Cinfo::isA(), isOnSpines_, Vec::operator-(), Vec::orthogonalAxes(), Id::path(), Bouton::postsynCompt_, spacing_, Vec::Vec(), Bouton::volume_, Bouton::vx_, Bouton::vy_, Bouton::vz_, Bouton::x_, Bouton::y_, and Bouton::z_.
Referenced by initCinfo().
buildOnSpineHeads()
void PresynMesh::buildOnSpineHeads (vector< ObjId > v)
Requires that all objects in v are the head compartments of spines.
Definition at line 382 of file PresynMesh.cpp.
{
    isOnSpines_ = true;
    spacing_ = 0; // Indicate that the spacing term isn't being used.
    boutons_.resize( v.size() );
    for (unsigned int i = 0; i < v.size(); ++i ) {
        if ( !v[i].element()->cinfo()->isA( "CompartmentBase" ) )  {
            cout << "Error: Attempt to assign PresynMesh to a non_compartment: " << v[i].id.path() << endl;
            assert( 0 );
        }
        Bouton& b = boutons_[i];
        b.postsynCompt_ = v[i];
        double length = Field< double >::get( v[i], "length" );
        double diameter = Field< double >::get( v[i], "diameter" );
        // Set up coords on end of compt
        b.x_ = Field< double >::get( v[i], "x" );
        b.y_ = Field< double >::get( v[i], "y" );
        b.z_ = Field< double >::get( v[i], "z" );
        // Define unit vector of direction of presyn from x to x0. (toward)
        b.vx_ = (Field< double >::get( v[i], "x0" ) - b.x_) / length;
        b.vy_ = (Field< double >::get( v[i], "y0" ) - b.y_) / length;
        b.vz_ = (Field< double >::get( v[i], "z0" ) - b.z_) / length;
        // Shift bouton coords 20 nanometres away from spine end.
        b.x_ -= b.vx_ * 20e-9;
        b.y_ -= b.vy_ * 20e-9;
        b.z_ -= b.vz_ * 20e-9;
        b.volume_ = length * diameter * diameter * 0.25 * PI;
    }
}
References boutons_, Element::cinfo(), ObjId::element(), Field< A >::get(), ObjId::id, Cinfo::isA(), isOnSpines_, Id::path(), PI, Bouton::postsynCompt_, spacing_, Bouton::volume_, Bouton::vx_, Bouton::vy_, Bouton::vz_, Bouton::x_, Bouton::y_, and Bouton::z_.
Referenced by initCinfo().
extendedMeshEntryVolume()
double PresynMesh::extendedMeshEntryVolume (unsigned int fid) const virtual
Volume of mesh Entry including abutting diff-coupled voxels.
Virtual function to return volume of mesh Entry.
Reimplemented from MeshCompt.
Definition at line 353 of file PresynMesh.cpp.
{
    assert( fid < boutons_.size() );
    return( boutons_[fid].volume_ );
}
References boutons_, and Bouton::volume_.
getAllBoutonOrientation()
vector< double > PresynMesh::getAllBoutonOrientation () const
Already handled by voxelMidpoint.
getAllBoutonVolumes()
vector< double > PresynMesh::getAllBoutonVolumes () const
Return volumes for each bouton. This is already handled by the inherited function getVoxelVolume, but that is readonly.
getBoutonIndexOnTargetCompartments()
vector< int > PresynMesh::getBoutonIndexOnTargetCompartments () const
Returns xyz triplets for each bouton, for a len of 3*numBoutons Already handled by getVoxelMidpoint Returns index of each bouton on its target compartment For spines all entries will be zero.
getBoutonSpacing()
double PresynMesh::getBoutonSpacing () const
Spacing between boutons if compartments are dendrite segments.
Definition at line 258 of file PresynMesh.cpp.
{
    return spacing_;
}
References spacing_.
Referenced by initCinfo().
getCoordinates()
vector< double > PresynMesh::getCoordinates (unsigned int fid) const virtual
Virtual function to return coords of mesh Entry.
Virtual function to return coords of mesh Entry. Assume that it is a hemisphere with the flat face toward postsyn. midpoint, direction, diameter.
Implements ChemCompt.
Definition at line 322 of file PresynMesh.cpp.
{
    assert( fid < boutons_.size() );
    const Bouton& b = boutons_[fid];
    vector< double > ret(7);
    ret[0] = b.x_;  // Midpoint
    ret[1] = b.y_;
    ret[2] = b.z_;
    ret[3] = b.vx_; // direction
    ret[4] = b.vy_;
    ret[5] = b.vz_;
    ret[6] = 2.0 * pow( b.volume_ * 1.5 / PI, 1.0/3.0 );
    return ret;
}
References boutons_, PI, Bouton::volume_, Bouton::vx_, Bouton::vy_, Bouton::vz_, Bouton::x_, Bouton::y_, and Bouton::z_.
getDiffusionArea()
vector< double > PresynMesh::getDiffusionArea (unsigned int fid) const virtual
Virtual function to return diffusion X-section area.
Virtual function to return diffusion X-section area for each neighbor There is no diffusion so it is zero.
Implements ChemCompt.
Definition at line 340 of file PresynMesh.cpp.
{
    return vector< double >( boutons_.size(), 0.0 );
}
References boutons_.
getDiffusionScaling()
vector< double > PresynMesh::getDiffusionScaling (unsigned int fid) const virtual
Virtual function to return scale factor for diffusion. 1 here.
Virtual function to return scale factor for diffusion. There is no diffusion so it is zero.
Implements ChemCompt.
Definition at line 347 of file PresynMesh.cpp.
{
    return vector< double >( boutons_.size(), 0.0 );
}
References boutons_.
getElecComptMap()
vector< Id > PresynMesh::getElecComptMap () const
Complementary func returning vec of Ids, to match other Meshes.
Definition at line 212 of file PresynMesh.cpp.
{
    vector< Id > ret( boutons_.size() );
    for( unsigned int i = 0; i < boutons_.size(); i++ )
        ret[i] = boutons_[i].postsynCompt_;
    return ret;
}
References boutons_, and Bouton::postsynCompt_.
Referenced by initCinfo().
getEndVoxelInCompt()
vector< unsigned int > PresynMesh::getEndVoxelInCompt () const
Definition at line 239 of file PresynMesh.cpp.
{
    vector< unsigned int > ret( boutons_.size() );
    auto lastCompt = ObjId();
    unsigned int lastIndex = 0;
    for( unsigned int i = 0; i < boutons_.size(); i++ ) {
        if ( lastCompt != boutons_[i].postsynCompt_ ) {
            lastCompt = boutons_[i].postsynCompt_;
            lastIndex = i;
        }
        if ( i > 0 )
            ret[i-1] = lastIndex;
    }
    ret[ret.size() - 1] = boutons_.size();
    return ret;
}
References boutons_, ObjId::ObjId(), ObjId::operator!=(), and Bouton::postsynCompt_.
Referenced by initCinfo().
getMeshDimensions()
unsigned int PresynMesh::getMeshDimensions (unsigned int fid) const virtual
Virtual function to return dimensions of specified entry.
Implements ChemCompt.
Definition at line 301 of file PresynMesh.cpp.
{
    return 3;
}
getMeshEntryVolume()
double PresynMesh::getMeshEntryVolume (unsigned int fid) const virtual
Virtual function to return volume of mesh Entry.
Implements ChemCompt.
Definition at line 312 of file PresynMesh.cpp.
{
    if ( fid < boutons_.size() )
        return( boutons_[fid].volume_ );
    return 0.0;
}
References boutons_, and Bouton::volume_.
getMeshType()
unsigned int PresynMesh::getMeshType (unsigned int fid) const virtual
Virtual function to return MeshType of specified entry.
Implements ChemCompt.
Definition at line 295 of file PresynMesh.cpp.
{
    return PRESYN;
}
References PRESYN.
getNumBoutons()
unsigned int PresynMesh::getNumBoutons () const
Report the number of boutons defined on mesh.
Definition at line 263 of file PresynMesh.cpp.
{
    return boutons_.size();
}
References boutons_.
Referenced by initCinfo().
getNumBoutonsOnCompartment()
int PresynMesh::getNumBoutonsOnCompartment (ObjId b) const
Definition at line 282 of file PresynMesh.cpp.
{
    int ret = 0;
    for( const Bouton& b : boutons_ )
        ret += b.postsynCompt_ == c;
    return ret;
}
References boutons_, ObjId::operator==(), and Bouton::postsynCompt_.
Referenced by initCinfo().
getParentVoxel()
vector< unsigned int > PresynMesh::getParentVoxel () const virtual
Inherited virtual, do nothing for now.
This means the sibling voxel immediately adjacent to it, not the voxel surrounding it. Should we wish to do diffusion we would need to use the parent voxel of the surround voxel. Otherewise use EMTPY_VOXEL == -1U.
Implements MeshCompt.
Definition at line 505 of file PresynMesh.cpp.
{
    vector< unsigned int > ret( boutons_.size(), ~0U);
    return ret;
}
References boutons_.
getPostsynCompts()
vector< ObjId > PresynMesh::getPostsynCompts () const
Return list of postynaptic compartments, one per bouton. Note that there may be repeats.
Definition at line 202 of file PresynMesh.cpp.
{
    vector< ObjId > ret( boutons_.size() );
    for( unsigned int i = 0; i < boutons_.size(); i++ )
        ret[i] = boutons_[i].postsynCompt_;
    return ret;
}
References boutons_, and Bouton::postsynCompt_.
Referenced by initCinfo().
getStartBoutonIndexFromCompartment()
int PresynMesh::getStartBoutonIndexFromCompartment (ObjId b) const
Already handled by oneVoxelVolume.
Definition at line 273 of file PresynMesh.cpp.
{
    for( unsigned int i = 0; i < boutons_.size(); i++ ) {
        if (boutons_[i].postsynCompt_ == c)
            return i;
    }
    return -1;
}
References boutons_, ObjId::operator==(), and Bouton::postsynCompt_.
Referenced by initCinfo().
getStartVoxelInCompt()
vector< unsigned int > PresynMesh::getStartVoxelInCompt () const
Definition at line 222 of file PresynMesh.cpp.
{
    vector< unsigned int > ret( boutons_.size() );
    auto lastCompt = ObjId();
    unsigned int lastIndex = 0;
    for( unsigned int i = 0; i < boutons_.size(); i++ ) {
        if ( lastCompt != boutons_[i].postsynCompt_ ) {
            lastCompt = boutons_[i].postsynCompt_;
            lastIndex = i;
        }
        ret[i] = lastIndex;
    }
    return ret;
}
References boutons_, ObjId::ObjId(), ObjId::operator!=(), and Bouton::postsynCompt_.
Referenced by initCinfo().
getTargetCompartments()
vector< ObjId > PresynMesh::getTargetCompartments () const
Returns the compartments to which each bouton projects.
getVoxelArea()
const vector< double > & PresynMesh::getVoxelArea () const virtual
Implements MeshCompt.
Definition at line 530 of file PresynMesh.cpp.
{
    static vector< double > ret;
    ret = vGetVoxelVolume();
    for ( auto i = ret.begin(); i != ret.end(); ++i )
        *i = pow( *i, 2.0/3.0 );
    return ret;
}
References vGetVoxelVolume().
getVoxelLength()
const vector< double > & PresynMesh::getVoxelLength () const virtual
Implements MeshCompt.
Definition at line 539 of file PresynMesh.cpp.
{
    static vector< double > ret;
    ret = vGetVoxelVolume();
    for ( auto i = ret.begin(); i != ret.end(); ++i )
        *i = pow( *i, 1.0/3.0 );
    return ret;
}
References vGetVoxelVolume().
indexToSpace()
void PresynMesh::indexToSpace (unsigned int index, double & x, double & y, double & z) const virtual
Converts specified index to xyz coords of middle of voxel Values out of range return original xyz
Implements ChemCompt.
Definition at line 593 of file PresynMesh.cpp.
{
    if ( index >= boutons_.size() )
        return;
    x = boutons_[index].x_;
    y = boutons_[index].y_;
    z = boutons_[index].z_;
}
References boutons_, Bouton::x_, Bouton::y_, and Bouton::z_.
initCinfo()
const Cinfo * PresynMesh::initCinfo () static
We assume the bouton to be a hemisphere.
Definition at line 23 of file PresynMesh.cpp.
{
        // Field Definitions
        static ReadOnlyValueFinfo< PresynMesh, vector< ObjId > > postsynCompts(
            "postsynCompts",
            "Return list of all postsyn compts, one per bouton. Note that "
            "there may be repeats since a compt may receive multiple "
            "synaptic inputs.",
            &PresynMesh::getPostsynCompts
        );
        static ReadOnlyValueFinfo< PresynMesh, vector< Id > > elecComptMap(
            "elecComptMap",
            "Return list of Ids of all postsyn compts, one per bouton. "
            "Provided to match with the other Mesh classes. Note that "
            "there may be repeats since a compt may receive multiple "
            "synaptic inputs. Identical to elecComptList",
            &PresynMesh::getElecComptMap
        );
        static ReadOnlyValueFinfo< PresynMesh, vector< Id > > elecComptList(
            "elecComptList",
            "Return list of Ids of all postsyn compts, one per bouton. "
            "Provided to match with the other Mesh classes. Note that "
            "there may be repeats since a compt may receive multiple "
            "synaptic inputs. Identical to elecComptMap.",
            &PresynMesh::getElecComptMap
        );
        static ReadOnlyValueFinfo< PresynMesh, vector< unsigned int > > startVoxelInCompt(
            "startVoxelInCompt",
            "Index of starting voxel that maps to each electrical compartment.",
            &PresynMesh::getStartVoxelInCompt
        );
        static ReadOnlyValueFinfo< PresynMesh, vector< unsigned int > > endVoxelInCompt(
            "endVoxelInCompt",
            "Index of end voxel that maps to each electrical compartment, "
            "using C++ indexing. So if there was 1 voxel only it would "
            "return 1+startVoxelInCompt",
            &PresynMesh::getEndVoxelInCompt
        );
        static ReadOnlyValueFinfo< PresynMesh, double > boutonSpacing(
            "boutonSpacing",
            "Spacing in metres between boutons on a dendrite. "
            "Assigned when creating boutons on a dendrite. "
            "Not defined if the boutons are on spines, which are one-to-one.",
            &PresynMesh::getBoutonSpacing
        );
        static ReadOnlyValueFinfo< PresynMesh, unsigned int > numBoutons(
            "numBoutons",
            "Total number of boutons defined in this mesh.",
            &PresynMesh::getNumBoutons
        );
        static ReadOnlyValueFinfo< PresynMesh, bool > isOnSpines(
            "isOnSpines",
            "Flag to report if PresynMesh is connected to spines,"
            "in which case the connections are one-to-one. "
            "If false, then the mesh is conneced to the dendrite. ",
            &PresynMesh::isOnSpines
        );
        static ReadOnlyLookupValueFinfo< PresynMesh, ObjId, int >
            startBoutonIndexFromCompartment(
            "startBoutonIndexFromCompartment",
            "Look up index of first bouton on specified compartment.",
            &PresynMesh::getStartBoutonIndexFromCompartment
        );
        static ReadOnlyLookupValueFinfo< PresynMesh, ObjId, int >
            numBoutonsOnCompartment(
            "numBoutonsOnCompartment",
            "Number of boutons on specified electrical compartment.",
            &PresynMesh::getNumBoutonsOnCompartment
        );
        // MsgDest Definitions
        static DestFinfo buildOnSpineHeads( "buildOnSpineHeads",
            "Assigns list of dendritic spine heads to which the boutons "
            "should connect. Sets isOnSpines to true.",
            new OpFunc1< PresynMesh, vector< ObjId > >(
                &PresynMesh::buildOnSpineHeads ) );
        static DestFinfo buildOnDendrites( "buildOnDendrites",
            "Assigns list of dendritic compartments to which the boutons "
            "should connect. Also assigns spacing. "
            "Sets isOnSpines to false.",
            new OpFunc2< PresynMesh, vector< ObjId >, double >(
                &PresynMesh::buildOnDendrites ) );
        static DestFinfo setRadiusStats( "setRadiusStats",
            "Assigns radius to the presyn boutons. SI units. "
            "Assumes bouton is a hemisphere. Vol = 2/3 PI R^3 "
            "If isOnSpines is true, then it assigns as a scale factor to "
            "the postsynaptic radius. "
            "If isOnSpines is false, then it assigns absolute radius. "
            "Arguments are radius, standard_deviation. ",
            new OpFunc2< PresynMesh, double, double >(
                &PresynMesh::setRadiusStats ) );
        // Field Elements
    static Finfo* presynMeshFinfos[] = {
        &postsynCompts,         // ReadOnlyValue
        &elecComptMap,          // ReadOnlyValue
        &elecComptList,         // ReadOnlyValue
        &startVoxelInCompt,     // ReadOnlyValue
        &endVoxelInCompt,       // ReadOnlyValue
        &boutonSpacing,         // ReadOnlyValue
        &numBoutons,            // ReadOnlyValue
        &isOnSpines,            // ReadOnlyValue
        &startBoutonIndexFromCompartment,       // ReadOnlyValueLookup
        &numBoutonsOnCompartment,               // ReadOnlyValueLookup
        &buildOnSpineHeads,         // DestFinfo
        &buildOnDendrites,          // DestFinfo
        &setRadiusStats,            // DestFinfo
    };
    static Dinfo< PresynMesh > dinfo;
    static Cinfo presynMeshCinfo (
        "PresynMesh",
        ChemCompt::initCinfo(),
        presynMeshFinfos,
        sizeof( presynMeshFinfos ) / sizeof ( Finfo* ),
        &dinfo
    );
    return &presynMeshCinfo;
}
References buildOnDendrites(), buildOnSpineHeads(), Cinfo::Cinfo(), DestFinfo::DestFinfo(), getBoutonSpacing(), getElecComptMap(), getEndVoxelInCompt(), getNumBoutons(), getNumBoutonsOnCompartment(), getPostsynCompts(), getStartBoutonIndexFromCompartment(), getStartVoxelInCompt(), ChemCompt::initCinfo(), isOnSpines(), OpFunc1< T, A >::OpFunc1(), OpFunc2< T, A1, A2 >::OpFunc2(), ReadOnlyLookupValueFinfo< T, L, F >::ReadOnlyLookupValueFinfo(), ReadOnlyValueFinfo< T, F >::ReadOnlyValueFinfo(), and setRadiusStats().
innerBuildDefaultMesh()
void PresynMesh::innerBuildDefaultMesh (const Eref & e, double volume, unsigned int numEntries) virtual
Virtual func to make a mesh with specified Volume and numEntries.
Implements ChemCompt.
Definition at line 490 of file PresynMesh.cpp.
{
    boutons_.resize( numEntries );
    for ( Bouton& b : boutons_ ) {
        b.volume_ = volume;
    }
}
References boutons_, and Bouton::volume_.
innerGetDimensions()
unsigned int PresynMesh::innerGetDimensions () const virtual
Virtual function to return # of spatial dimensions of mesh.
Implements ChemCompt.
Definition at line 307 of file PresynMesh.cpp.
{
    return 3;
}
innerGetNumEntries()
unsigned int PresynMesh::innerGetNumEntries () const virtual
Inherited virtual func. Returns number of MeshEntry in array
Implements ChemCompt.
Definition at line 476 of file PresynMesh.cpp.
{
    return boutons_.size();
}
References boutons_.
innerHandleNodeInfo()
void PresynMesh::innerHandleNodeInfo (const Eref & e, unsigned int numNodes, unsigned int numThreads) virtual
Implements ChemCompt.
Definition at line 375 of file PresynMesh.cpp.
{
}
innerHandleRequestMeshStats()
void PresynMesh::innerHandleRequestMeshStats (const Eref & e, const SrcFinfo2< unsigned int, vector< double > > * meshStatsFinfo)
More inherited virtual funcs: request comes in for mesh stats.
Definition at line 364 of file PresynMesh.cpp.
{
    double aveVol = vGetEntireVolume();
    if ( boutons_.size() > 0 )
        aveVol /= boutons_.size();
    vector< double > ret( 1, aveVol );
    meshStatsFinfo->send( e, 1, ret );
}
References boutons_, SrcFinfo2< T1, T2 >::send(), and vGetEntireVolume().
innerSetNumEntries()
void PresynMesh::innerSetNumEntries (unsigned int n) virtual
Inherited virtual func.
Inherited virtual func.
Implements ChemCompt.
Definition at line 484 of file PresynMesh.cpp.
{
    boutons_.resize( n );
}
References boutons_.
isOnSpines()
bool PresynMesh::isOnSpines () const
Reports if this set of boutons is connected to spines vs dend.
Definition at line 268 of file PresynMesh.cpp.
{
    return isOnSpines_;
}
References isOnSpines_.
Referenced by initCinfo().
matchMeshEntries()
void PresynMesh::matchMeshEntries (const ChemCompt * other, vector< VoxelJunction > & ret) const virtual
Returns the meshIndices (NOT spatial indices) of all adjacent mesh entry pairs on ether side of the (self, other) junction. meshIndices are the indices that look up entries in the vector of pools. spatialIndices are (iz * ny + iy) * nx + ix, that is, a linear conversion of cartesian spatial indices. So, for two touching cubes, the return vector is the paired meshIndices on either side of the plane of contact. If one mesh has a finer mesh than the other, or if there are more than one contact points from self to other (for example, at a corner), then we just have multiple pairs using the same meshIndex of the repeated voxel.
Implements ChemCompt.
Definition at line 566 of file PresynMesh.cpp.
{
    ret.clear(); // No diffusion here.
}
nearest()
double PresynMesh::nearest (double x, double y, double z, unsigned int & index) const virtual
Returns distance and index of nearest mesh entry. Computes each mesh entry position as its geometric centre. If the current location is not inside a valid mesh entry, distance returned is negative.
Implements ChemCompt.
Definition at line 574 of file PresynMesh.cpp.
{
    double distance = 1e19;
    index = 0;
    for ( unsigned int i = 0; i < boutons_.size(); i++ ) {
        const Bouton& b = boutons_[i];
        double r = (b.x_ - x) * (b.x_ - x) + (b.y_ - y) * (b.y_ - y ) + (b.z_ - z) * (b.z_ - z);
        if ( distance > r ) {
            index = i;
            distance = r;
        }
    }
    if (distance == 1e19)
        return -1;
    return distance;
}
References boutons_, Bouton::x_, Bouton::y_, and Bouton::z_.
setAllBoutonVolumes()
void PresynMesh::setAllBoutonVolumes (vector< double > & vols)
setRadiusStats()
void PresynMesh::setRadiusStats (double r, double sdev)
setRadiusStats is meant to be called before the presynMesh is populated with the chemical system, but after the boutons are created.
Definition at line 458 of file PresynMesh.cpp.
{
    // As a placeholder, just go through assigning vols without the sdev.
    if ( isOnSpines_ ) {
        for ( Bouton& b : boutons_ )
            b.volume_ *= r*r*r; // Scale relative to postsyn.
    } else {
        double v = r*r*r*PI*2.0/3.0; // Hemisphere
        for ( Bouton& b : boutons_ )
            b.volume_ = v; // Absolute assignment.
    }
}
References boutons_, isOnSpines_, PI, and Bouton::volume_.
Referenced by initCinfo().
vGetEntireVolume()
double PresynMesh::vGetEntireVolume () const virtual
Inherited virtual. Returns entire volume of compartment.
Implements ChemCompt.
Definition at line 548 of file PresynMesh.cpp.
{
    double vol = 0.0;
    auto vec = vGetVoxelVolume();
    for ( auto i : vec )
        vol += i;
    return vol;
}
References vGetVoxelVolume().
Referenced by innerHandleRequestMeshStats().
vGetVoxelMidpoint()
const vector< double > & PresynMesh::vGetVoxelMidpoint () const virtual
Virtual func so that derived classes can return voxel midpoint.
Implements ChemCompt.
Definition at line 520 of file PresynMesh.cpp.
{
    static vector< double > ret;
    ret.clear();
    for ( auto i : boutons_ ) ret.push_back( i.x_ );
    for ( auto i : boutons_ ) ret.push_back( i.y_ );
    for ( auto i : boutons_ ) ret.push_back( i.z_ );
    return ret;
}
References boutons_, Bouton::x_, Bouton::y_, and Bouton::z_.
vGetVoxelVolume()
const vector< double > & PresynMesh::vGetVoxelVolume () const virtual
Virtual func so that derived classes can pass voxel volume back.
Implements ChemCompt.
Definition at line 511 of file PresynMesh.cpp.
{
    static vector< double > ret;
    ret.clear();
    for ( auto i : boutons_ )
        ret.push_back( i.volume_ );
    return ret;
}
References boutons_, and Bouton::volume_.
Referenced by getVoxelArea(), getVoxelLength(), and vGetEntireVolume().
vSetVolumeNotRates()
bool PresynMesh::vSetVolumeNotRates (double volume) virtual
Inherited virtual. Resizes len and dia of each voxel.
Implements ChemCompt.
Definition at line 557 of file PresynMesh.cpp.
{
    return true; // maybe should be false? Unsure
}
Member Data Documentation
boutons_
vector< Bouton > PresynMesh::boutons_ private
These are the data structures for each of the boutons.
Definition at line 184 of file PresynMesh.h.
Referenced by buildOnDendrites(), buildOnSpineHeads(), extendedMeshEntryVolume(), getCoordinates(), getDiffusionArea(), getDiffusionScaling(), getElecComptMap(), getEndVoxelInCompt(), getMeshEntryVolume(), getNumBoutons(), getNumBoutonsOnCompartment(), getParentVoxel(), getPostsynCompts(), getStartBoutonIndexFromCompartment(), getStartVoxelInCompt(), indexToSpace(), innerBuildDefaultMesh(), innerGetNumEntries(), innerHandleRequestMeshStats(), innerSetNumEntries(), nearest(), setRadiusStats(), vGetVoxelMidpoint(), and vGetVoxelVolume().
isOnSpines_
bool PresynMesh::isOnSpines_ private
Flag: Is it on spines or along a dendritic tree?
Definition at line 178 of file PresynMesh.h.
Referenced by buildOnDendrites(), buildOnSpineHeads(), isOnSpines(), PresynMesh(), and setRadiusStats().
spacing_
double PresynMesh::spacing_ private
spacing of presyn boutons along the NeuroMesh (dendrite).
Definition at line 181 of file PresynMesh.h.
Referenced by buildOnDendrites(), buildOnSpineHeads(), getBoutonSpacing(), and PresynMesh().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/mesh/PresynMesh.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/mesh/PresynMesh.cpp