MOOSE - Multiscale Object Oriented Simulation Environment: SynChan Class Reference
SynChan Class Reference
#include <SynChan.h>
Public Member Functions
void activation (double val)
double calcGk ()
Update alpha function terms for synaptic channel.
bool getNormalizeWeights () const
double getTau1 () const
double getTau2 () const
void normalizeGbar ()
void setNormalizeWeights (bool value)
void setTau1 (double tau1)
void setTau2 (double tau2)
SynChan ()
void vProcess (const Eref &e, ProcPtr p)
void vReinit (const Eref &e, ProcPtr p)
void vSetGbar (const Eref &e, double Gbar)
~SynChan ()
Public Member Functions inherited from ChanCommon
ChanCommon ()
double getGbar () const
Utility function to acces Gbar.
double getVm () const
Utility function to access Vm.
void sendProcessMsgs (const Eref &e, const ProcPtr info)
void sendReinitMsgs (const Eref &e, const ProcPtr info)
void updateIk ()
double vGetEk (const Eref &e) const override
double vGetGbar (const Eref &e) const override
double vGetGk (const Eref &e) const override
double vGetIk (const Eref &e) const override
double vGetModulation (const Eref &e) const override
void vHandleVm (double Vm) override
void vSetEk (const Eref &e, double Ek) override
void vSetGk (const Eref &e, double Gk) override
void vSetIk (const Eref &e, double Ic) override
void vSetModulation (const Eref &e, double modulation) override
virtual ~ChanCommon ()=0
Public Member Functions inherited from ChanBase
ChanBase ()
double getEk (const Eref &e) const
double getGbar (const Eref &e) const
double getGk (const Eref &e) const
double getIk (const Eref &e) const
double getModulation (const Eref &e) const
void handleVm (double Vm)
void process (const Eref &e, const ProcPtr info)
void reinit (const Eref &e, const ProcPtr info)
void setEk (const Eref &e, double Ek)
void setGbar (const Eref &e, double Gbar)
void setGk (const Eref &e, double Gk)
void setIk (const Eref &e, double Ic)
void setModulation (const Eref &e, double modulation)
virtual ~ChanBase ()=0
Static Public Member Functions
static const Cinfo * initCinfo ()
Static Public Member Functions inherited from ChanCommon
static const Cinfo * initCinfo ()
Specify the Class Info static variable for initialization.
Static Public Member Functions inherited from ChanBase
static SrcFinfo2< double, double > * channelOut ()
static SrcFinfo1< double > * IkOut ()
static const Cinfo * initCinfo ()
Specify the Class Info static variable for initialization.
static SrcFinfo1< double > * permeability ()
Protected Attributes
double activation_
double dt_
double norm_
int normalizeWeights_
double tau1_
double tau2_
double X_
double xconst1_
double xconst2_
double Y_
double yconst1_
double yconst2_
Protected Attributes inherited from ChanCommon
double Vm_
Vm_ is input variable from compartment, used for most rates.
Additional Inherited Members
Protected Member Functions inherited from ChanCommon
double getModulation () const
Detailed Description
Definition at line 13 of file SynChan.h.
Constructor & Destructor Documentation
SynChan()
SynChan::SynChan ()
Definition at line 95 of file SynChan.cpp.
    :
    tau1_( 1.0e-3 ), tau2_( 1.0e-3 ),
    normalizeWeights_( 0 ),
        xconst1_(0.0),
        yconst1_(1.0),
        xconst2_(1.0),
        yconst2_(0.0),
        norm_(1.0),
        activation_(0.0),
        X_(0.0),
        Y_(0.0),
        dt_( 25.0e-6 )
{ ; }
References activation_, dt_, norm_, normalizeWeights_, tau1_, tau2_, X_, xconst1_, xconst2_, Y_, yconst1_, and yconst2_.
~SynChan()
SynChan::~SynChan ()
Definition at line 110 of file SynChan.cpp.
{;}
Member Function Documentation
activation()
void SynChan::activation (double val)
Definition at line 253 of file SynChan.cpp.
{
    activation_ += val;
}
References activation_.
Referenced by initCinfo().
calcGk()
double SynChan::calcGk ()
Update alpha function terms for synaptic channel.
Utility function used to do the alpha function calculations for Gk. Separated out for convenience so that derived classes can use.
Definition at line 200 of file SynChan.cpp.
{
        /*
    X_ = getModulation() * activation_ * xconst1_ + X_ * xconst2_;
    Y_ = X_ * yconst1_ + Y_ * yconst2_;
    activation_ = 0.0;
    return Y_ * norm_;
    */
    X_ = activation_ * xconst1_ + X_ * xconst2_;
    Y_ = X_ * yconst1_ + Y_ * yconst2_;
    activation_ = 0.0;
    return Y_ * norm_ * getModulation();
}
References activation_, ChanCommon::getModulation(), norm_, X_, xconst1_, xconst2_, Y_, yconst1_, and yconst2_.
Referenced by NMDAChan::vProcess(), and vProcess().
getNormalizeWeights()
bool SynChan::getNormalizeWeights () const
Definition at line 166 of file SynChan.cpp.
{
    return normalizeWeights_;
}
References normalizeWeights_.
Referenced by initCinfo().
getTau1()
double SynChan::getTau1 () const
Definition at line 134 of file SynChan.cpp.
{
    return tau1_;
}
References tau1_.
Referenced by initCinfo().
getTau2()
double SynChan::getTau2 () const
Definition at line 156 of file SynChan.cpp.
{
    return tau2_;
}
References tau2_.
Referenced by initCinfo().
initCinfo()
const Cinfo * SynChan::initCinfo () static
Override base class function for spike handling
Definition at line 20 of file SynChan.cpp.
{
    // Shared message definitions
// Field definitions
    static ValueFinfo< SynChan, double > tau1( "tau1",
        "Decay time constant for the synaptic conductance, tau1 >= tau2.",
        &SynChan::setTau1,
        &SynChan::getTau1
    );
    static ValueFinfo< SynChan, double > tau2( "tau2",
        "Rise time constant for the synaptic conductance, tau1 >= tau2.",
        &SynChan::setTau2,
        &SynChan::getTau2
    );
    static ValueFinfo< SynChan, bool > normalizeWeights(
        "normalizeWeights",
        "Flag. If true, the overall conductance is normalized by the "
        "number of individual synapses in this SynChan object.",
        &SynChan::setNormalizeWeights,
        &SynChan::getNormalizeWeights
    );
    // MsgDest definitions
    static DestFinfo activation( "activation",
        "Sometimes we want to continuously activate the channel",
        new OpFunc1< SynChan, double >( &SynChan::activation )
    );
    static Finfo* SynChanFinfos[] =
    {
        &tau1,          // Value
        &tau2,          // Value
        &normalizeWeights,  // Value
        &activation,    // Dest
    };
    static string doc[] =
    {
        "Name", "SynChan",
        "Author", "Upinder S. Bhalla, 2007, 2014, NCBS",
        "Description", "SynChan: Synaptic channel incorporating "
        " weight and delay. Does not handle actual arrival of synaptic "
        " events, that is done by one of the derived classes of "
        "SynHandlerBase.\n"
        "In use, the SynChan sits on the compartment connected to it by "
        "the **channel** message. One or more of the SynHandler "
        "objects connects to the SynChan through the **activation** "
        "message. The SynHandlers each manage multiple synapses, and "
        "the handlers can be fixed weight or have a learning rule. "
    };
        static Dinfo< SynChan > dinfo;
    static Cinfo SynChanCinfo(
        "SynChan",
        ChanBase::initCinfo(),
        SynChanFinfos,
        sizeof( SynChanFinfos )/sizeof(Finfo *),
                &dinfo,
        doc,
        sizeof( doc )/sizeof( string )
    );
    return &SynChanCinfo;
}
References activation(), Cinfo::Cinfo(), DestFinfo::DestFinfo(), getNormalizeWeights(), getTau1(), getTau2(), ChanBase::initCinfo(), OpFunc1< T, A >::OpFunc1(), setNormalizeWeights(), setTau1(), setTau2(), and ValueFinfo< T, F >::ValueFinfo().
Referenced by NMDAChan::initCinfo().
normalizeGbar()
void SynChan::normalizeGbar ()
Definition at line 171 of file SynChan.cpp.
{
        if ( doubleEq( tau2_, 0.0 ) ) {
                // norm_ = 1.0;
                norm_ = ChanCommon::getGbar();
        } else {
                if ( doubleEq( tau1_, tau2_ ) ) {
                    norm_ = ChanCommon::getGbar() * SynE() / tau1_;
                } else {
                    double tpeak = tau1_ * tau2_ * log( tau1_ / tau2_ ) /
                            ( tau1_ - tau2_ );
                    norm_ = ChanCommon::getGbar() * ( tau1_ - tau2_ ) /
                            ( tau1_ * tau2_ * (
                            exp( -tpeak / tau1_ ) - exp( -tpeak / tau2_ )
                                                ));
                }
        }
        /*
         * Can't handle at this time. Simple but tedious to implement.
    if ( normalizeWeights_ && getNumSynapses() > 0 )
        norm_ /= static_cast< double >( getNumSynapses() );
        */
}
References doubleEq(), ChanCommon::getGbar(), norm_, SynE(), tau1_, and tau2_.
Referenced by setTau1(), setTau2(), vReinit(), and vSetGbar().
setNormalizeWeights()
void SynChan::setNormalizeWeights (bool value)
Definition at line 161 of file SynChan.cpp.
{
    normalizeWeights_ = value;
}
References normalizeWeights_.
Referenced by initCinfo().
setTau1()
void SynChan::setTau1 (double tau1)
Definition at line 123 of file SynChan.cpp.
{
    tau1_ = tau1;
    // Aditya added
    // required if changing tau1 during a simulation
    // (eg. Marder pyloric networks).
    xconst1_ = tau1_ * ( 1.0 - exp( -dt_ / tau1_ ) );
    xconst2_ = exp( -dt_ / tau1_ );
    normalizeGbar();
}
References dt_, normalizeGbar(), tau1_, xconst1_, and xconst2_.
Referenced by initCinfo().
setTau2()
void SynChan::setTau2 (double tau2)
Definition at line 139 of file SynChan.cpp.
{
    tau2_ = tau2;
    // Aditya added
    // required if changing tau1 during a simulation
    // (eg. Marder pyloric networks).
    if ( doubleEq( tau2_, 0.0 ) ) {
            yconst1_ = 1.0;
            yconst2_ = 0.0;
    } else {
            yconst1_ = tau2_ * ( 1.0 - exp( -dt_ / tau2_ ) );
            yconst2_ = exp( -dt_ / tau2_ );
    }
    normalizeGbar();
}
References doubleEq(), dt_, normalizeGbar(), tau2_, yconst1_, and yconst2_.
Referenced by initCinfo().
vProcess()
void SynChan::vProcess (const Eref & e, ProcPtr p) virtual
Implements ChanBase.
Definition at line 214 of file SynChan.cpp.
{
    // http://www.genesis-sim.org/GENESIS/Hyperdoc/Manual-26.html#synchan
    // For a spike event, activation = weight / dt
    //      is sent from SynHandler-s for one dt
    // For continuous activation in a graded synapse,
    //      send activation for continous dt-s.
    setGk( e, calcGk() );
    updateIk();
    sendProcessMsgs( e, info ); // Sends out messages for channel.
}
References calcGk(), ChanCommon::sendProcessMsgs(), ChanBase::setGk(), and ChanCommon::updateIk().
vReinit()
void SynChan::vReinit (const Eref & e, ProcPtr p) virtual
Implements ChanBase.
Definition at line 229 of file SynChan.cpp.
{
    dt_ = info->dt;
    activation_ = 0.0;
    ChanBase::setGk( e, 0.0 );
    ChanBase::setIk( e, 0.0 );
    X_ = 0.0;
    Y_ = 0.0;
    // These below statements are also called when setting tau1 and tau2
    // (required when changing tau1 and tau2 during a simulation).
    xconst1_ = tau1_ * ( 1.0 - exp( -dt_ / tau1_ ) );
    xconst2_ = exp( -dt_ / tau1_ );
        if ( doubleEq( tau2_, 0.0 ) ) {
                yconst1_ = 1.0;
                yconst2_ = 0.0;
        } else {
                yconst1_ = tau2_ * ( 1.0 - exp( -dt_ / tau2_ ) );
                yconst2_ = exp( -dt_ / tau2_ );
        }
    normalizeGbar();
    sendReinitMsgs(e, info);
}
References activation_, doubleEq(), ProcInfo::dt, dt_, normalizeGbar(), ChanCommon::sendReinitMsgs(), ChanBase::setGk(), ChanBase::setIk(), tau1_, tau2_, X_, xconst1_, xconst2_, Y_, yconst1_, and yconst2_.
Referenced by NMDAChan::vReinit().
vSetGbar()
void SynChan::vSetGbar (const Eref & e, double Gbar) virtual
Reimplemented from ChanCommon.
Definition at line 117 of file SynChan.cpp.
{
    ChanCommon::vSetGbar( e, Gbar );
    normalizeGbar();
}
References normalizeGbar(), and ChanCommon::vSetGbar().
Member Data Documentation
activation_
double SynChan::activation_ protected
Definition at line 82 of file SynChan.h.
Referenced by activation(), calcGk(), SynChan(), and vReinit().
dt_
double SynChan::dt_ protected
Definition at line 85 of file SynChan.h.
Referenced by setTau1(), setTau2(), SynChan(), and vReinit().
norm_
double SynChan::norm_ protected
Definition at line 81 of file SynChan.h.
Referenced by calcGk(), normalizeGbar(), and SynChan().
normalizeWeights_
int SynChan::normalizeWeights_ protected
Definition at line 76 of file SynChan.h.
Referenced by getNormalizeWeights(), setNormalizeWeights(), and SynChan().
tau1_
double SynChan::tau1_ protected
Definition at line 74 of file SynChan.h.
Referenced by getTau1(), normalizeGbar(), setTau1(), SynChan(), and vReinit().
tau2_
double SynChan::tau2_ protected
Definition at line 75 of file SynChan.h.
Referenced by getTau2(), normalizeGbar(), setTau2(), SynChan(), and vReinit().
X_
double SynChan::X_ protected
Definition at line 83 of file SynChan.h.
Referenced by calcGk(), SynChan(), and vReinit().
xconst1_
double SynChan::xconst1_ protected
Definition at line 77 of file SynChan.h.
Referenced by calcGk(), setTau1(), SynChan(), and vReinit().
xconst2_
double SynChan::xconst2_ protected
Definition at line 79 of file SynChan.h.
Referenced by calcGk(), setTau1(), SynChan(), and vReinit().
Y_
double SynChan::Y_ protected
Definition at line 84 of file SynChan.h.
Referenced by calcGk(), SynChan(), and vReinit().
yconst1_
double SynChan::yconst1_ protected
Definition at line 78 of file SynChan.h.
Referenced by calcGk(), setTau2(), SynChan(), and vReinit().
yconst2_
double SynChan::yconst2_ protected
Definition at line 80 of file SynChan.h.
Referenced by calcGk(), setTau2(), SynChan(), and vReinit().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/biophysics/SynChan.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/biophysics/SynChan.cpp