MOOSE - Multiscale Object Oriented Simulation Environment: FieldElement Class Reference
FieldElement Class Reference
#include <FieldElement.h>
Public Member Functions
Element * copyElement (Id newParent, Id newId, unsigned int n, bool toGlobal) const
char * data (unsigned int rawIndex, unsigned int fieldIndex=0) const
FieldElement (Id parent, Id kid, const Cinfo *c, const string &name, const FieldElementFinfoBase *fef)
unsigned int getNode (unsigned int dataId) const
Virtual: Returns location of specified dataId.
unsigned int getNumOnNode (unsigned int node) const
Inherited virtual.
bool hasFields () const
bool isGlobal () const
Virtual. Returns true if global, ie, if its parent is global.
unsigned int localDataStart () const
Virtual: Returns index of first data entry on this node.
unsigned int numData () const
Virtual: Returns number of data entries.
unsigned int numField (unsigned int rawIndex) const
Virtual: Returns number of field entries for specified data.
unsigned int numLocalData () const
Virtual: Returns number of data entries on current node.
unsigned int rawIndex (unsigned int dataId) const
Virtual: Returns converted dataId to index on current node.
void resize (unsigned int newNumData)
void resizeField (unsigned int rawIndex, unsigned int newNumField)
unsigned int startDataIndex (unsigned int node) const
Virtual: Returns start DataIndex on specified node.
unsigned int totNumLocalField () const
Virtual: Returns number of field entries on current node.
void zombieSwap (const Cinfo *zCinfo)
~FieldElement ()
Public Member Functions inherited from Element
void addMsg (ObjId mid)
void addMsgAndFunc (ObjId mid, FuncId fid, BindIndex bindIndex)
const Cinfo * cinfo () const
void clearAllMsgs ()
Used upon ending of MOOSE session, to rapidly clear out messages.
void clearBinding (BindIndex b)
void digestMessages ()
void dropAllMsgsFromSrc (Id src)
void dropMsg (ObjId mid)
Element (Id id, const Cinfo *c, const string &name)
unsigned int findBinding (MsgFuncBinding b) const
ObjId findCaller (FuncId fid) const
unsigned int getFieldsOfOutgoingMsg (ObjId mid, vector< pair< BindIndex, FuncId > > &ret) const
unsigned int getInputMsgs (vector< ObjId > &caller, FuncId fid) const
unsigned int getInputsWithTgtIndex (vector< pair< Id, unsigned int > > &ret, const DestFinfo *finfo) const
const vector< MsgFuncBinding > * getMsgAndFunc (BindIndex b) const
unsigned int getMsgSourceAndSender (FuncId fid, vector< ObjId > &src, vector< string > &sender) const
unsigned int getMsgTargetAndFunctions (DataId srcDataId, const SrcFinfo *finfo, vector< ObjId > &tgt, vector< string > &func) const
vector< ObjId > getMsgTargets (DataId srcDataId, const SrcFinfo *finfo) const
const string & getName () const
unsigned int getNeighbors (vector< Id > &ret, const Finfo *finfo) const
int getTick () const
bool hasMsgs (BindIndex b) const
Id id () const
void innerSetTick (unsigned int tick)
bool isDoomed () const
void markAsDoomed ()
void markRewired ()
const vector< MsgDigest > & msgDigest (unsigned int index)
const vector< ObjId > & msgIn () const
void printMsgDigest (unsigned int srcIndex, unsigned int dataIndex) const
void putOffNodeTargetsInDigest (unsigned int srcNum, vector< vector< bool > > &targetNodes)
void putTargetsInDigest (unsigned int srcNum, const MsgFuncBinding &mfb, const FuncOrder &fo, vector< vector< bool > > &targetNodes)
void replaceCinfo (const Cinfo *newCinfo)
Support function for zombieSwap, replaces Cinfo.
void setName (const string &val)
void setTick (int t)
void showFields () const
void showMsg () const
virtual ~Element ()
Private Attributes
const FieldElementFinfoBase * fef_
Id parent_
Additional Inherited Members
Static Public Member Functions inherited from Element
static void destroyElementTree (const vector< Id > &tree)
Detailed Description
Specialization of Element class, used to look up array fields within objects when those fields each need to have independent Element capabilies such as messaging and subfield lookup. Made automatically by Elements which have such fields.
Definition at line 18 of file FieldElement.h.
Constructor & Destructor Documentation
FieldElement()
FieldElement::FieldElement (Id parent, Id kid, const Cinfo * c, const string & name, const FieldElementFinfoBase * fef)
Definition at line 13 of file FieldElement.cpp.
    :
    Element( self, c, name ),
    parent_( parent ),
    fef_( fef )
{
    ;
}
References Element::Element(), fef_, and parent_.
Referenced by copyElement(), and FieldElementFinfoBase::postCreationFunc().
~FieldElement()
FieldElement::~FieldElement ()
Virtual func: leave the clearing of the messages to ElementBase, the data is cleared by the parent Element of this field.
Definition at line 30 of file FieldElement.cpp.
{
    ;
}
Member Function Documentation
copyElement()
Element * FieldElement::copyElement (Id newParent, Id newId, unsigned int n, bool toGlobal) const virtual
Virtual copier. Makes a copy of self.
Implements Element.
Definition at line 35 of file FieldElement.cpp.
{
    return new FieldElement( newParent, newId, cinfo(), getName(), fef_ );
}
References Element::cinfo(), fef_, FieldElement(), and Element::getName().
data()
char * FieldElement::data (unsigned int rawIndex, unsigned int fieldIndex = 0) const virtual
virtual. Looks up specified field field entry. First it finds the appropriate data entry from the rawIndex. Then it looks up the field using the lookupField. Returns the data entry specified by the rawIndex, fieldIndex.
Note that the index is NOT a DataIndex: it is instead the raw index of the data on the current node. Index is also NOT the character offset, but the index to the data array in whatever type the data may be.
The DataIndex has to be filtered through the nodeMap to find a) if the entry is here, and b) what its raw index is.
Returns 0 if either index is out of range.
Implements Element.
Definition at line 109 of file FieldElement.cpp.
{
    char* data = parent_.element()->data( rawIndex );
    return fef_->lookupField( data, fieldIndex );
}
References Element::data(), Id::element(), fef_, FieldElementFinfoBase::lookupField(), and parent_.
getNode()
unsigned int FieldElement::getNode (unsigned int dataId) const virtual
Virtual: Returns location of specified dataId.
Implements Element.
Definition at line 76 of file FieldElement.cpp.
{
    return parent_.element()->getNode( dataId );
}
References Id::element(), Element::getNode(), and parent_.
getNumOnNode()
unsigned int FieldElement::getNumOnNode (unsigned int node) const virtual
Inherited virtual.
Implements Element.
Definition at line 96 of file FieldElement.cpp.
{
    if ( node == Shell::myNode() || parent_.element()->isGlobal() )
    {
        return totNumLocalField();
    }
    // Here we need to refer to a postmaster function to get the
    // number of field entries on specified node. For now, a dummy.
    return totNumLocalField();
}
References Id::element(), Element::isGlobal(), Shell::myNode(), parent_, and totNumLocalField().
hasFields()
bool FieldElement::hasFields () const inline virtual
Virtual: True if this is a FieldElement having an array of fields on each data entry. So true in this case.
Implements Element.
Definition at line 62 of file FieldElement.h.
{
            return true;
        }
isGlobal()
bool FieldElement::isGlobal () const virtual
Virtual. Returns true if global, ie, if its parent is global.
Implements Element.
Definition at line 91 of file FieldElement.cpp.
{
    return parent_.element()->isGlobal();
}
References Id::element(), Element::isGlobal(), and parent_.
localDataStart()
unsigned int FieldElement::localDataStart () const virtual
Virtual: Returns index of first data entry on this node.
Implements Element.
Definition at line 55 of file FieldElement.cpp.
{
    return parent_.element()->localDataStart();
}
References Id::element(), Element::localDataStart(), and parent_.
numData()
unsigned int FieldElement::numData () const virtual
Virtual: Returns number of data entries.
Implements Element.
Definition at line 45 of file FieldElement.cpp.
{
    return parent_.element()->numData();
}
References Id::element(), Element::numData(), and parent_.
numField()
unsigned int FieldElement::numField (unsigned int rawIndex) const virtual
Virtual: Returns number of field entries for specified data.
Implements Element.
Definition at line 60 of file FieldElement.cpp.
{
    const char* data = parent_.element()->data( rawIndex );
    assert( data );
    return fef_->getNumField( data );
}
References Element::data(), Id::element(), fef_, FieldElementFinfoBase::getNumField(), and parent_.
Referenced by totNumLocalField().
numLocalData()
unsigned int FieldElement::numLocalData () const virtual
Virtual: Returns number of data entries on current node.
Implements Element.
Definition at line 50 of file FieldElement.cpp.
{
    return parent_.element()->numLocalData();
}
References Id::element(), Element::numLocalData(), and parent_.
Referenced by totNumLocalField().
rawIndex()
unsigned int FieldElement::rawIndex (unsigned int dataId) const virtual
Virtual: Returns converted dataId to index on current node.
Implements Element.
Definition at line 86 of file FieldElement.cpp.
{
    return parent_.element()->rawIndex( dataId );
}
References Id::element(), parent_, and Element::rawIndex().
resize()
void FieldElement::resize (unsigned int newNumData) virtual
virtual Changes the number of entries in the data. Not permitted for FieldElements since they are just fields on the data.
Implements Element.
Definition at line 116 of file FieldElement.cpp.
{
    assert( 0 );
}
resizeField()
void FieldElement::resizeField (unsigned int rawIndex, unsigned int newNumField) virtual
virtual. Changes the number of fields on the specified data entry.
Implements Element.
Definition at line 121 of file FieldElement.cpp.
{
    char* data = parent_.element()->data( rawIndex );
    fef_->setNumField( data, newNumField );
}
References Element::data(), Id::element(), fef_, parent_, and FieldElementFinfoBase::setNumField().
startDataIndex()
unsigned int FieldElement::startDataIndex (unsigned int node) const virtual
Virtual: Returns start DataIndex on specified node.
Implements Element.
Definition at line 81 of file FieldElement.cpp.
{
    return parent_.element()->startDataIndex( node );
}
References Id::element(), parent_, and Element::startDataIndex().
totNumLocalField()
unsigned int FieldElement::totNumLocalField () const virtual
Virtual: Returns number of field entries on current node.
Implements Element.
Definition at line 67 of file FieldElement.cpp.
{
    unsigned int ret = 0;
    unsigned int nd = numLocalData();
    for ( unsigned int i = 0; i < nd; ++i )
        ret += numField( i );
    return ret;
}
References numField(), and numLocalData().
Referenced by getNumOnNode().
zombieSwap()
void FieldElement::zombieSwap (const Cinfo * zCinfo) virtual
Virtual: after replacing Cinfo of parent, we need to replace Cinfo and fef here. The zCinfo is the new Cinfo for this FieldElement.
Reimplemented from Element.
Definition at line 130 of file FieldElement.cpp.
{
    const Finfo* f = zCinfo->findFinfo( getName() );
    assert( f );
    const FieldElementFinfoBase* zfef = dynamic_cast<
                                        const FieldElementFinfoBase* >( f );
    assert( zfef );
    fef_ = zfef;
    replaceCinfo( zCinfo );
}
References fef_, Cinfo::findFinfo(), Element::getName(), and Element::replaceCinfo().
Member Data Documentation
fef_
const FieldElementFinfoBase* FieldElement::fef_ private
Definition at line 118 of file FieldElement.h.
Referenced by copyElement(), data(), FieldElement(), numField(), resizeField(), and zombieSwap().
parent_
Id FieldElement::parent_ private
Definition at line 117 of file FieldElement.h.
Referenced by data(), FieldElement(), getNode(), getNumOnNode(), isGlobal(), localDataStart(), numData(), numField(), numLocalData(), rawIndex(), resizeField(), and startDataIndex().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/basecode/FieldElement.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/basecode/FieldElement.cpp