MOOSE - Multiscale Object Oriented Simulation Environment: ValueFinfo< T, F > Class Template Reference
ValueFinfo< T, F > Class Template Reference
#include <ValueFinfo.h>
Public Member Functions
void registerFinfo (Cinfo *c)
string rttiType () const
bool strGet (const Eref &tgt, const string &field, string &returnValue) const
bool strSet (const Eref &tgt, const string &field, const string &arg) const
ValueFinfo (const string &name, const string &doc, void(T::*setFunc)(F), F(T::*getFunc)() const)
~ValueFinfo ()
Public Member Functions inherited from ValueFinfoBase
DestFinfo * getFinfo () const
vector< string > innerDest () const
ValueFinfoBase (const string &name, const string &doc)
~ValueFinfoBase ()
Public Member Functions inherited from Finfo
virtual bool addMsg (const Finfo *target, ObjId mid, Element *src) const
virtual bool checkTarget (const Finfo *target) const
const string & docs () const
Returns documentation string.
Finfo (const string &name, const string &doc)
virtual vector< string > innerSrc () const
const string & name () const
virtual void postCreationFunc (Id newId, Element *newElm) const
virtual ~Finfo ()
Additional Inherited Members
Static Public Member Functions inherited from Finfo
static const Cinfo * initCinfo ()
Protected Attributes inherited from ValueFinfoBase
DestFinfo * get_
DestFinfo * set_
Detailed Description
template<class T, class F>
class ValueFinfo< T, F >
Definition at line 36 of file ValueFinfo.h.
Constructor & Destructor Documentation
~ValueFinfo()
template<class T , class F > ValueFinfo< T, F >::~ValueFinfo () inline
Definition at line 39 of file ValueFinfo.h.
                      {
            delete set_;
            delete get_;
        }
References ValueFinfoBase::get_, and ValueFinfoBase::set_.
ValueFinfo()
template<class T , class F > ValueFinfo< T, F >::ValueFinfo (const string & name, const string & doc, void(T::*)(F) setFunc, F(T::*)() const getFunc) inline
Definition at line 44 of file ValueFinfo.h.
            : ValueFinfoBase( name, doc )
        {
                string setname = "set" + name;
                setname[3] = std::toupper( setname[3] );
                set_ = new DestFinfo(
                    setname,
                    "Assigns field value.",
                    new OpFunc1< T, F >( setFunc ) );
                string getname = "get" + name;
                getname[3] = std::toupper( getname[3] );
                get_ = new DestFinfo(
                    getname,
                    "Requests field value. The requesting Element must "
                    "provide a handler for the returned value.",
                    new GetOpFunc< T, F >( getFunc ) );
        }
References ValueFinfoBase::get_, and ValueFinfoBase::set_.
Referenced by TestId::initCinfo(), moose::CompartmentBase::initCinfo(), GapJunction::initCinfo(), HHChannel2D::initCinfo(), IntFire::initCinfo(), IzhikevichNrn::initCinfo(), MarkovChannel::initCinfo(), MarkovOdeSolver::initCinfo(), MarkovRateTable::initCinfo(), MarkovSolverBase::initCinfo(), MgBlock::initCinfo(), Nernst::initCinfo(), Neuron::initCinfo(), NMDAChan::initCinfo(), RandSpike::initCinfo(), SpikeGen::initCinfo(), SynChan::initCinfo(), moose::VClamp::initCinfo(), VectorTable::initCinfo(), Arith::initCinfo(), Function::initCinfo(), Interpol::initCinfo(), Interpol2D::initCinfo(), Mstring::initCinfo(), SocketStreamer::initCinfo(), SpikeStats::initCinfo(), Stats::initCinfo(), StimulusTable::initCinfo(), Streamer::initCinfo(), Table::initCinfo(), TableBase::initCinfo(), TimeTable::initCinfo(), Variable::initCinfo(), DiffAmp::initCinfo(), PIDController::initCinfo(), PulseGen::initCinfo(), RC::initCinfo(), Dsolve::initCinfo(), Cell::initCinfo(), HSolve::initCinfo(), ConcChan::initCinfo(), Species::initCinfo(), Gsolve::initCinfo(), Ksolve::initCinfo(), Stoich::initCinfo(), Boundary::initCinfo(), ChemCompt::initCinfo(), CubeMesh::initCinfo(), NeuroMesh::initCinfo(), PsdMesh::initCinfo(), PostMaster::initCinfo(), DiagonalMsg::initCinfo(), OneToAllMsg::initCinfo(), SingleMsg::initCinfo(), SparseMsg::initCinfo(), Clock::initCinfo(), Neutral::initCinfo(), Shell::initCinfo(), Adaptor::initCinfo(), GraupnerBrunel2012CaPlasticitySynHandler::initCinfo(), SeqSynHandler::initCinfo(), STDPSynapse::initCinfo(), STDPSynHandler::initCinfo(), Synapse::initCinfo(), SynHandlerBase::initCinfo(), and Annotator::initCinfo().
Member Function Documentation
registerFinfo()
template<class T , class F > void ValueFinfo< T, F >::registerFinfo (Cinfo * c) inline virtual
Returns string-ified form to handle template expectations for name field string getName() const; Assign function Ids, bindIndex and so on.
Implements Finfo.
Definition at line 66 of file ValueFinfo.h.
{
            c->registerFinfo( set_ );
            c->registerFinfo( get_ );
        }
References ValueFinfoBase::get_, Cinfo::registerFinfo(), and ValueFinfoBase::set_.
rttiType()
template<class T , class F > string ValueFinfo< T, F >::rttiType () const inline virtual
Returns the documentation string for the Finfo string docs() const; Returns the RTTI type string for the finfo by referring to an internal virtual function. string type() const; Returns the list of subsidiary SrcFinfos. Used in Shared Finfos, empty otherwise. Goes via internal virtual function. vector< string > src() const; Returns the list of subsidiary destFinfos. Used in SharedFinfos and ValueFinfos, empty otherwise. Goes via internal virtual function. vector< string > dest() const; Returns an RTTI type string for this Finfo.
Reimplemented from Finfo.
Definition at line 81 of file ValueFinfo.h.
{
            return Conv<F>::rttiType();
        }
strGet()
template<class T , class F > bool ValueFinfo< T, F >::strGet (const Eref & tgt, const string & field, string & returnValue) const inline virtual
Function to return value of field into a string argument. Returns true on success. Normally called only from SetGet::strGet.
Implements Finfo.
Definition at line 76 of file ValueFinfo.h.
{
            return Field< F >::innerStrGet( tgt.objId(), field, returnValue );
        }
References Eref::objId().
strSet()
template<class T , class F > bool ValueFinfo< T, F >::strSet (const Eref & tgt, const string & field, const string & arg) const inline virtual
Function to set this field using a string argument. Returns true on success. Normally called only from SetGet::strSet.
Implements Finfo.
Definition at line 71 of file ValueFinfo.h.
{
            return Field< F >::innerStrSet( tgt.objId(), field, arg );
        }
References Eref::objId().
The documentation for this class was generated from the following file:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/basecode/ValueFinfo.h