MOOSE - Multiscale Object Oriented Simulation Environment: ElementValueFinfo< T, F > Class Template Reference
ElementValueFinfo< T, F > Class Template Reference
#include <ElementValueFinfo.h>
Public Member Functions
ElementValueFinfo (const string &name, const string &doc, void(T::*setFunc)(const Eref &, F), F(T::*getFunc)(const Eref &) const)
void registerFinfo (Cinfo *c)
string rttiType () const
bool strGet (const Eref &tgt, const string &field, string &returnValue) const
bool strSet (const Eref &tgt, const string &field, const string &arg) const
~ElementValueFinfo ()
Public Member Functions inherited from ValueFinfoBase
DestFinfo * getFinfo () const
vector< string > innerDest () const
ValueFinfoBase (const string &name, const string &doc)
~ValueFinfoBase ()
Public Member Functions inherited from Finfo
virtual bool addMsg (const Finfo *target, ObjId mid, Element *src) const
virtual bool checkTarget (const Finfo *target) const
const string & docs () const
Returns documentation string.
Finfo (const string &name, const string &doc)
virtual vector< string > innerSrc () const
const string & name () const
virtual void postCreationFunc (Id newId, Element *newElm) const
virtual ~Finfo ()
Additional Inherited Members
Static Public Member Functions inherited from Finfo
static const Cinfo * initCinfo ()
Protected Attributes inherited from ValueFinfoBase
DestFinfo * get_
DestFinfo * set_
Detailed Description
template<class T, class F>
class ElementValueFinfo< T, F >
This variant of ValueFinfo provides facilities to set and get values of fields that require information about the managing Element
Definition at line 18 of file ElementValueFinfo.h.
Constructor & Destructor Documentation
~ElementValueFinfo()
template<class T , class F > ElementValueFinfo< T, F >::~ElementValueFinfo () inline
Definition at line 21 of file ElementValueFinfo.h.
{
            delete set_;
            delete get_;
        }
References ValueFinfoBase::get_, and ValueFinfoBase::set_.
ElementValueFinfo()
template<class T , class F > ElementValueFinfo< T, F >::ElementValueFinfo (const string & name, const string & doc, void(T::*)(const Eref &, F) setFunc, F(T::*)(const Eref &) const getFunc) inline
Definition at line 26 of file ElementValueFinfo.h.
            : ValueFinfoBase( name, doc )
        {
                string setname = "set" + name;
                setname[3] = std::toupper( setname[3] );
                set_ = new DestFinfo(
                    setname,
                    "Assigns field value.",
                    new EpFunc1< T, F >( setFunc ) );
                string getname = "get" + name;
                getname[3] = std::toupper( getname[3] );
                get_ = new DestFinfo(
                    getname,
                    "Requests field value. The requesting Element must "
                    "provide a handler for the returned value.",
                    new GetEpFunc< T, F >( getFunc ) );
        }
References ValueFinfoBase::get_, and ValueFinfoBase::set_.
Referenced by CaConcBase::initCinfo(), ChanBase::initCinfo(), moose::CompartmentBase::initCinfo(), DifBufferBase::initCinfo(), DifShellBase::initCinfo(), HHChannel2D::initCinfo(), HHChannelBase::initCinfo(), HHGate2D::initCinfo(), MMPump::initCinfo(), Neuron::initCinfo(), NMDAChan::initCinfo(), Spine::initCinfo(), Function::initCinfo(), Dsolve::initCinfo(), HSolve::initCinfo(), moose::AdExIF::initCinfo(), moose::AdThreshIF::initCinfo(), moose::ExIF::initCinfo(), moose::IntFireBase::initCinfo(), moose::IzhIF::initCinfo(), moose::QIF::initCinfo(), Enz::initCinfo(), EnzBase::initCinfo(), Reac::initCinfo(), Stoich::initCinfo(), ChemCompt::initCinfo(), CubeMesh::initCinfo(), CylMesh::initCinfo(), EndoMesh::initCinfo(), NeuroMesh::initCinfo(), Neutral::initCinfo(), Synapse::initCinfo(), and PoolBase::initPoolBaseCinfo().
Member Function Documentation
registerFinfo()
template<class T , class F > void ElementValueFinfo< T, F >::registerFinfo (Cinfo * c) inline virtual
Returns string-ified form to handle template expectations for name field string getName() const; Assign function Ids, bindIndex and so on.
Implements Finfo.
Definition at line 48 of file ElementValueFinfo.h.
{
            c->registerFinfo( set_ );
            // c->registerElementField( set->getFid() );
            c->registerFinfo( get_ );
        }
References ValueFinfoBase::get_, Cinfo::registerFinfo(), and ValueFinfoBase::set_.
rttiType()
template<class T , class F > string ElementValueFinfo< T, F >::rttiType () const inline virtual
Returns the documentation string for the Finfo string docs() const; Returns the RTTI type string for the finfo by referring to an internal virtual function. string type() const; Returns the list of subsidiary SrcFinfos. Used in Shared Finfos, empty otherwise. Goes via internal virtual function. vector< string > src() const; Returns the list of subsidiary destFinfos. Used in SharedFinfos and ValueFinfos, empty otherwise. Goes via internal virtual function. vector< string > dest() const; Returns an RTTI type string for this Finfo.
Reimplemented from Finfo.
Definition at line 65 of file ElementValueFinfo.h.
{
            return Conv<F>::rttiType();
        }
strGet()
template<class T , class F > bool ElementValueFinfo< T, F >::strGet (const Eref & tgt, const string & field, string & returnValue) const inline virtual
Function to return value of field into a string argument. Returns true on success. Normally called only from SetGet::strGet.
Implements Finfo.
Definition at line 59 of file ElementValueFinfo.h.
{
            return Field< F >::innerStrGet(
                            tgt.objId(), field, returnValue );
        }
References Eref::objId().
strSet()
template<class T , class F > bool ElementValueFinfo< T, F >::strSet (const Eref & tgt, const string & field, const string & arg) const inline virtual
Function to set this field using a string argument. Returns true on success. Normally called only from SetGet::strSet.
Implements Finfo.
Definition at line 54 of file ElementValueFinfo.h.
{
            return Field< F >::innerStrSet( tgt.objId(), field, arg );
        }
References Eref::objId().
The documentation for this class was generated from the following file:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/basecode/ElementValueFinfo.h