MOOSE - Multiscale Object Oriented Simulation Environment: HopIndex Class Reference
HopIndex Class Reference
#include <OpFuncBase.h>
Public Member Functions
unsigned short bindIndex () const
HopIndex (unsigned short bindIndex, unsigned char hopType=MooseSendHop)
unsigned char hopType () const
Private Attributes
unsigned short bindIndex_
unsigned char hopType_
Detailed Description
Definition at line 23 of file OpFuncBase.h.
Constructor & Destructor Documentation
HopIndex()
HopIndex::HopIndex (unsigned short bindIndex, unsigned char hopType = MooseSendHop) inline
Definition at line 26 of file OpFuncBase.h.
        : bindIndex_( bindIndex ),
          hopType_( hopType )
    {;}
References bindIndex_, and hopType_.
Referenced by SetGet0::set(), and testHopFunc().
Member Function Documentation
bindIndex()
unsigned short HopIndex::bindIndex () const inline
Definition at line 32 of file OpFuncBase.h.
    {
        return bindIndex_;
    }
References bindIndex_.
Referenced by addToBuf(), GetHopFunc< A >::getMultiNodeVec(), GetHopFunc< A >::getRemoteFieldVec(), and GetHopFunc< A >::op().
hopType()
unsigned char HopIndex::hopType () const inline
Definition at line 37 of file OpFuncBase.h.
    {
        return hopType_;
    }
References hopType_.
Referenced by addToBuf(), and dispatchBuffers().
Member Data Documentation
bindIndex_
unsigned short HopIndex::bindIndex_ private
Definition at line 42 of file OpFuncBase.h.
Referenced by bindIndex(), and HopIndex().
hopType_
unsigned char HopIndex::hopType_ private
Definition at line 43 of file OpFuncBase.h.
Referenced by HopIndex(), and hopType().
The documentation for this class was generated from the following file:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/basecode/OpFuncBase.h