MOOSE - Multiscale Object Oriented Simulation Environment: TimeTable Class Reference
TimeTable Class Reference
#include <TimeTable.h>
Public Member Functions
string getFilename () const
int getMethod () const
double getState () const
void process (const Eref &e, ProcPtr p)
void reinit (const Eref &e, ProcPtr p)
void setFilename (string filename)
void setMethod (int method)
TimeTable ()
~TimeTable ()
Public Member Functions inherited from TableBase
void clearVec ()
void compareVec (vector< double > other, string op)
void compareXplot (string fname, string plotname, string op)
const vector< double > & data ()
double getOutputValue () const
string getPlotDump () const
unsigned int getVecSize () const
vector< double > getVector () const
double getY (unsigned int index) const
double interpolate (double x, double xmin, double xmax) const
void linearTransform (double scale, double offset)
void loadCSV (string fname, int startLine, int colNum, char separator)
void loadXplot (string fname, string plotname)
void loadXplotRange (string fname, string plotname, unsigned int start, unsigned int end)
double * lookupVec (unsigned int index)
void plainPlot (string file)
void setOutputValue (double val)
void setPlotDump (string v)
void setVecSize (unsigned int num)
void setVector (vector< double > val)
TableBase ()
void xplot (string file, string plotname)
Static Public Member Functions
static const Cinfo * initCinfo ()
Static Public Member Functions inherited from TableBase
static const Cinfo * initCinfo ()
Private Attributes
unsigned int curPos_
string filename_
int method_
double state_
vector< double > timeTable_
Additional Inherited Members
Protected Member Functions inherited from TableBase
vector< double > & vec ()
Detailed Description
Definition at line 12 of file TimeTable.h.
Constructor & Destructor Documentation
TimeTable()
TimeTable::TimeTable ()
Definition at line 101 of file TimeTable.cpp.
  :
  filename_(""),
  state_( 0.0 ),
  curPos_( 0 ),
  method_( 4 )
{ ; }
References curPos_, filename_, method_, and state_.
~TimeTable()
TimeTable::~TimeTable ()
Definition at line 109 of file TimeTable.cpp.
{ ; }
Member Function Documentation
getFilename()
string TimeTable::getFilename () const
Definition at line 117 of file TimeTable.cpp.
{
  return filename_;
}
References filename_.
Referenced by initCinfo().
getMethod()
int TimeTable::getMethod () const
Definition at line 166 of file TimeTable.cpp.
{
  return method_;
}
References method_.
Referenced by initCinfo().
getState()
double TimeTable::getState () const
Definition at line 172 of file TimeTable.cpp.
{
  return state_;
}
References state_.
Referenced by initCinfo().
initCinfo()
const Cinfo * TimeTable::initCinfo () static
Definition at line 24 of file TimeTable.cpp.
{
    // Field definitions
    static ValueFinfo< TimeTable, string > filename( "filename",
                                            "File to read lookup data from. The file should be contain two columns\n"
                                            "separated by any space character.",
                                            &TimeTable::setFilename,
                                            &TimeTable::getFilename);
    static ValueFinfo< TimeTable, int > method( "method",
                                                "Method to use for filling up the entries. Currently only method 4\n"
                                                "(loading from file) is supported.",
                                                &TimeTable::setMethod ,
                                                &TimeTable::getMethod);
    static ReadOnlyValueFinfo <TimeTable, double> state( "state",
                                                         "Current state of the time table.",
                                                         &TimeTable::getState );
    // MsgDest Definitions
    static DestFinfo process("process",
                             "Handle process call",
                             new ProcOpFunc< TimeTable >( &TimeTable::process));
    static DestFinfo reinit("reinit",
                            "Handles reinit call",
                            new ProcOpFunc< TimeTable > ( &TimeTable::reinit));
    // SharedMsg Definitions
    static Finfo* procShared[] = {
        &process, &reinit
    };
    static SharedFinfo proc( "proc",
                             "Shared message for process and reinit",
                             procShared, sizeof( procShared ) / sizeof( const Finfo* ));
    static Finfo * timeTableFinfos[] = {
        &filename,
        &method,
        &state,
        eventOut(),
        &proc,
    };
    static string doc[] = {
        "Name", "TimeTable",
        "Author", "Johannes Hjorth, 2008, KTH, Stockholm. Ported to buildQ branch using new API by Subhasis Ray, NCBS, Bangalore, 2013.",
        "Description", "TimeTable: Read in spike times from file and send out eventOut messages\n"
        "at the specified times.",
    };
    static Dinfo< TimeTable > dinfo;
    static Cinfo timeTableCinfo(
        "TimeTable",
        TableBase::initCinfo(),
        timeTableFinfos,
        sizeof( timeTableFinfos )/sizeof(Finfo *),
        &dinfo,
        doc,
        sizeof(doc)/sizeof(string));
    return &timeTableCinfo;
}
References Cinfo::Cinfo(), DestFinfo::DestFinfo(), eventOut(), getFilename(), getMethod(), getState(), TableBase::initCinfo(), process(), ProcOpFunc< T >::ProcOpFunc(), ReadOnlyValueFinfo< T, F >::ReadOnlyValueFinfo(), reinit(), setFilename(), setMethod(), SharedFinfo::SharedFinfo(), and ValueFinfo< T, F >::ValueFinfo().
process()
void TimeTable::process (const Eref & e, ProcPtr p)
The process function called by scheduler on every tick
Definition at line 187 of file TimeTable.cpp.
{
  // Two ways of telling the world about the spike events, both
  // happening in parallel
  //
  // state is a continous variable, switching from 0 to 1 when spiking
  // event is an event, that happens at the time of a spike
  //
  state_ = 0;
  if ( curPos_ < vec().size() &&
       p->currTime >= vec()[curPos_] ) {
      eventOut()->send( e, vec()[curPos_]);
      curPos_++;
      state_ = 1;
  }
}
References curPos_, ProcInfo::currTime, eventOut(), SrcFinfo1< T >::send(), state_, and TableBase::vec().
Referenced by initCinfo().
reinit()
void TimeTable::reinit (const Eref & e, ProcPtr p)
The reinit function called by scheduler for the reset
Definition at line 181 of file TimeTable.cpp.
{
  curPos_ = 0;
  state_ = 0;
}
References curPos_, and state_.
Referenced by initCinfo().
setFilename()
void TimeTable::setFilename (string filename)
Definition at line 122 of file TimeTable.cpp.
{
  filename_ = filename;
  std::ifstream fin( filename_.c_str() );
  string line;
  if( !fin.good()) {
    cout << "Error: TimeTable::innerload: Unable to open file"
         << filename_ << endl;
  }
  //~ If lines need to be skipped:
  //~ for(unsigned int i = 0; (i < skipLines) & fin.good() ; i++)
    //~ getline( fin, line );
  vec().clear();
  double dataPoint, dataPointOld = -1000;
  while( fin >> dataPoint ) {
      vec().push_back(dataPoint);
    if(dataPoint < dataPointOld) {
      cerr << "TimeTable: Warning: Spike times in file " << filename_
           << " are not in increasing order."
           << endl;
    }
    dataPointOld = dataPoint;
  }
}
References filename_, and TableBase::vec().
Referenced by initCinfo().
setMethod()
void TimeTable::setMethod (int method)
Definition at line 155 of file TimeTable.cpp.
{
  if ( method != 4 ) {
    cerr <<
      "Error: TimeTable::setMethod: "
      "Currently only method 4 (loading from file) supported.\n";
    return;
  }
  method_ = method;
}
References method_.
Referenced by initCinfo().
Member Data Documentation
curPos_
unsigned int TimeTable::curPos_ private
Definition at line 53 of file TimeTable.h.
Referenced by process(), reinit(), and TimeTable().
filename_
string TimeTable::filename_ private
Definition at line 44 of file TimeTable.h.
Referenced by getFilename(), setFilename(), and TimeTable().
method_
int TimeTable::method_ private
Definition at line 57 of file TimeTable.h.
Referenced by getMethod(), setMethod(), and TimeTable().
state_
double TimeTable::state_ private
Definition at line 50 of file TimeTable.h.
Referenced by getState(), process(), reinit(), and TimeTable().
timeTable_
vector< double > TimeTable::timeTable_ private
Definition at line 47 of file TimeTable.h.
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/builtins/TimeTable.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/builtins/TimeTable.cpp