MOOSE - Multiscale Object Oriented Simulation Environment: Neuron Class Reference
Neuron Class Reference
#include <Neuron.h>
Public Member Functions
void buildElist (const Eref &e, const vector< string > &line, vector< ObjId > &elist, vector< double > &val)
void buildSegmentTree (const Eref &e)
Fills up vector of segments. First entry is soma.
void evalExprForElist (const vector< ObjId > &elist, const string &expn, vector< double > &val) const
vector< string > getChannelDistribution (const Eref &e) const
double getCM () const
double getCompartmentLengthInLambdas () const
vector< ObjId > getCompartments () const
vector< double > getElecDistFromSoma () const
double getEm () const
vector< ObjId > getExprElist (const Eref &e, string line) const
vector< double > getExprVal (const Eref &e, string line) const
vector< double > getGeomDistFromSoma () const
unsigned int getNumBranches () const
unsigned int getNumCompartments () const
unsigned int getNumSpines () const
ObjId getParentCompartmentOfSpine (const Eref &e, ObjId compt) const
vector< string > getPassiveDistribution (const Eref &e) const
vector< double > getPathDistFromSoma () const
double getPhi () const
double getRA () const
double getRM () const
string getSourceFile () const
vector< string > getSpineDistribution (const Eref &e) const
ObjId getSpineFromCompartment (const Eref &e, ObjId compt) const
vector< ObjId > getSpinesOnCompartment (const Eref &e, ObjId compt) const
double getTheta () const
void installMechanism (const string &name, const vector< ObjId > &elist, const vector< double > &val, const vector< string > &line)
void installSpines (const vector< ObjId > &elist, const vector< double > &val, const vector< string > &line)
Spine * lookupSpine (unsigned int index)
void makeSpacingDistrib (const vector< ObjId > &elist, const vector< double > &val, vector< unsigned int > &seglistIndex, vector< unsigned int > &elistIndex, vector< double > &pos, const vector< string > &line) const
Neuron ()
Neuron (const Neuron &other)
void parseMechSpec (const Eref &e)
void scaleBufAndRates (unsigned int spineNum, double lenScale, double diaScale) const
void scaleHeadDiffusion (unsigned int spineNum, double len, double dia) const
Scale the diffusion parameters due to a change in the head dimensions.
void scaleShaftDiffusion (unsigned int spineNum, double len, double dia) const
Scale the diffusion parameters due to a change in the shaft dimensions.
void setChannelDistribution (const Eref &e, vector< string > v)
void setCM (double v)
void setCompartmentLengthInLambdas (double v)
void setEm (double v)
void setNumSpines (unsigned int num)
void setPassiveDistribution (const Eref &e, vector< string > v)
void setPhi (double v)
void setRA (double v)
void setRM (double v)
void setSourceFile (string v)
void setSpineAndPsdDsolve (ObjId spineDsolve, ObjId psdDsolve)
void setSpineAndPsdMesh (ObjId spineMesh, ObjId psdMesh)
Fills up vector of segments. First entry is soma.
void setSpineDistribution (const Eref &e, vector< string > v)
void setTheta (double v)
const vector< Id > & spineIds (unsigned int index) const
void updateSegmentLengths ()
Static Public Member Functions
static const Cinfo * initCinfo ()
Private Attributes
vector< vector< Id > > allSpinesPerCompt_
Id of each compt in each spine.
vector< SwcBranch > branches_
vector< string > channelDistribution_
double CM_
double compartmentLengthInLambdas_
double Em_
Id headDsolve_
double maxG_
double maxL_
double maxP_
vector< string > passiveDistribution_
double phi_
Id psdDsolve_
Id of the Dsolve for the head compt.
vector< Id > psdStoich_
Id of stoich associated with each PSD. Typically all the same.
double RA_
double RM_
vector< Id > segId_
map< Id, unsigned int > segIndex_
Map to look up Seg index from Id of associated compt.
vector< SwcSegment > segs_
Id of compartment in each Seg entry, below.
Id soma_
string sourceFile_
vector< string > spineDistribution_
Spine spineEntry_
Id of the Dsolve for the PSD compt.
vector< unsigned int > spineParentSegIndex_
Look up seg index of parent compartment, from index of spine.
vector< vector< Id > > spines_
vector< Id > spineStoich_
Id of stoich associated with each spine. Typically all the same.
vector< unsigned int > spineToMeshOrdering_
looks up spine/psd mesh index from FieldIndex of selected spine.
double theta_
Detailed Description
The Neuron class to hold the Compartment class elements.
Definition at line 18 of file Neuron.h.
Constructor & Destructor Documentation
Neuron() [1/2]
Neuron::Neuron ()
Definition at line 565 of file Neuron.cpp.
    :
    RM_( 1.0 ),
    RA_( 1.0 ),
    CM_( 0.01 ),
    Em_( -0.065 ),
    theta_( 0.0 ),
    phi_( 0.0 ),
    maxP_( 0.0 ),
    maxG_( 0.0 ),
    maxL_( 0.0 ),
    sourceFile_( "" ),
    compartmentLengthInLambdas_( 0.2 ),
    spineEntry_( this )
{
    ;
}
References CM_, compartmentLengthInLambdas_, Em_, maxG_, maxL_, maxP_, phi_, RA_, RM_, sourceFile_, Spine::Spine(), spineEntry_, and theta_.
Neuron() [2/2]
Neuron::Neuron (const Neuron & other)
Definition at line 585 of file Neuron.cpp.
    :
    RM_( other.RM_ ),
    RA_( other.RA_ ),
    CM_( other.CM_ ),
    Em_( other.Em_ ),
    theta_( other.theta_ ),
    phi_( other.phi_ ),
    maxP_( other.maxP_ ),
    maxG_( other.maxG_ ),
    maxL_( other.maxL_ ),
    sourceFile_( other.sourceFile_ ),
    compartmentLengthInLambdas_(other.compartmentLengthInLambdas_),
    channelDistribution_( other.channelDistribution_ ),
    passiveDistribution_( other.passiveDistribution_ ),
    spineDistribution_( other.spineDistribution_ ),
    spineEntry_( this )
{
    ;
}
References channelDistribution_, CM_, compartmentLengthInLambdas_, Em_, maxG_, maxL_, maxP_, passiveDistribution_, phi_, RA_, RM_, sourceFile_, Spine::Spine(), spineDistribution_, spineEntry_, and theta_.
Member Function Documentation
buildElist()
void Neuron::buildElist (const Eref & e, const vector< string > & line, vector< ObjId > & elist, vector< double > & val)
Definition at line 1143 of file Neuron.cpp.
{
    Shell* shell = reinterpret_cast< Shell* >( Id().eref().data() );
    const string& path = line[1];
    const string& expr = line[3];
    ObjId oldCwe = shell->getCwe();
    shell->setCwe( e.objId() );
    wildcardFind( path, elist );
    sort( elist.begin(), elist.end() );
    shell->setCwe( oldCwe );
    evalExprForElist( elist, expr, val );
}
References Eref::data(), Id::eref(), evalExprForElist(), Shell::getCwe(), Id::Id(), Eref::objId(), Shell::setCwe(), and wildcardFind().
Referenced by setChannelDistribution(), setPassiveDistribution(), and setSpineDistribution().
buildSegmentTree()
void Neuron::buildSegmentTree (const Eref & e)
Fills up vector of segments. First entry is soma.
Definition at line 1408 of file Neuron.cpp.
{
    vector< Id > kids;
    Neutral::children( e, kids );
    sort( kids.begin(), kids.end() );
    soma_ = fillSegIndex( kids, segIndex_ );
    if ( kids.size() == 0 || soma_ == Id() )
    {
        cout << "Error: Neuron::buildSegmentTree( " << e.id().path() <<
             " ): \n        Valid neuronal model not found.\n";
        return;
    }
    fillSegments( segs_, segIndex_, kids );
    int numPa = 0;
    for ( unsigned int i = 0; i < segs_.size(); ++i )
    {
        if ( segs_[i].parent() == ~0U )
        {
            numPa++;
        }
        else
        {
            segs_[ segs_[i].parent() ].addChild( i );
        }
    }
    for ( unsigned int i = 0; i < segs_.size(); ++i )
    {
        segs_[i].figureOutType();
    }
    if ( numPa != 1 )
    {
        cout << "Warning: Neuron.cpp: buildTree: num soma compartments = " << numPa << endl;
    }
    segId_.clear();
    segId_.resize( segIndex_.size(), Id() );
    for ( map< Id, unsigned int >::const_iterator
            i = segIndex_.begin(); i != segIndex_.end(); ++i )
    {
        assert( i->second < segId_.size() );
        segId_[ i->second ] = i->first;
    }
    // Allocate vector allSpinesPerCompt_ to use all entries of segId_
    allSpinesPerCompt_.clear();
    allSpinesPerCompt_.resize(segId_.size() );
    updateSegmentLengths();
}
References SwcSegment::addChild(), allSpinesPerCompt_, Neutral::children(), SwcSegment::figureOutType(), fillSegIndex(), fillSegments(), Id::Id(), Eref::id(), Id::operator==(), SwcSegment::parent(), Id::path(), segId_, segIndex_, segs_, soma_, and updateSegmentLengths().
Referenced by initCinfo().
evalExprForElist()
void Neuron::evalExprForElist (const vector< ObjId > & elist, const string & expn, vector< double > & val) const
Evaluates expn for every CompartmentBase entry in elist. Pushes value, length and dia for each elist entry into the 'val' vector.
Definition at line 1527 of file Neuron.cpp.
{
    val.clear();
    val.resize( elist.size() * nuParser::numVal );
    // Build the function
    double len = 0; // Length of compt in metres
    double dia = 0; // Diameter of compt in metres
    unsigned int valIndex = 0;
    try
    {
        nuParser parser( expn );
        for ( vector< ObjId >::const_iterator
                i = elist.begin(); i != elist.end(); ++i )
        {
            if ( i->element()->cinfo()->isA( "CompartmentBase" ) )
            {
                map< Id, unsigned int >:: const_iterator j =
                    segIndex_.find( *i );
                if ( j != segIndex_.end() )
                {
                    assert( j->second < segs_.size() );
                    val[valIndex + nuParser::P] =
                        segs_[j->second].getPathDistFromSoma();
                    val[valIndex + nuParser::G] =
                        segs_[j->second].getGeomDistFromSoma();
                    val[valIndex + nuParser::EL] =
                        segs_[j->second].getElecDistFromSoma();
                } else {
                    double somaX0 = Field<double>::get( soma_, "x0" );
                    double somaY0 = Field<double>::get( soma_, "y0" );
                    double somaZ0 = Field<double>::get( soma_, "z0" );
                    double comptX0 = Field<double>::get( *i, "x0" );
                    double comptY0 = Field<double>::get( *i, "y0" );
                    double comptZ0 = Field<double>::get( *i, "z0" );
                    Vec temp( somaX0-comptX0, somaY0-comptY0, somaZ0-comptZ0 );
                    double geomDistFromSoma = temp.length();
                    val[valIndex + nuParser::G] = geomDistFromSoma;
                    val[valIndex + nuParser::P] = geomDistFromSoma; //dummy
                    // Dummy, using typical lambda of 0.5 mm
                    val[valIndex + nuParser::EL] = geomDistFromSoma * 2e3;
                }
                dia = Field< double >::get( *i, "diameter" );
                len = Field< double >::get( *i, "length" );
                val[valIndex + nuParser::LEN] = len;
                val[valIndex + nuParser::DIA] = dia;
                val[valIndex + nuParser::MAXP] = maxP_;
                val[valIndex + nuParser::MAXG] = maxG_;
                val[valIndex + nuParser::MAXL] = maxL_;
                val[valIndex + nuParser::X] = segs_[j->second].vec().a0();
                val[valIndex + nuParser::Y] = segs_[j->second].vec().a1();
                val[valIndex + nuParser::Z] = segs_[j->second].vec().a2();
                // Can't assign oldVal on first arg
                val[valIndex + nuParser::OLDVAL] = 0.0;
                val[valIndex + nuParser::EXPR] = parser.eval(
                                             val.begin() + valIndex );
            }
            valIndex += nuParser::numVal;
        }
    }
    catch ( moose::Parser::exception_type& err )
    {
        cout << err.GetMsg() << endl;
    }
}
References Vec::a0(), Vec::a1(), Vec::a2(), Element::cinfo(), nuParser::DIA, nuParser::EL, ObjId::element(), nuParser::eval(), nuParser::EXPR, nuParser::G, Field< A >::get(), SwcSegment::getElecDistFromSoma(), SwcSegment::getGeomDistFromSoma(), moose::Parser::ParserException::GetMsg(), SwcSegment::getPathDistFromSoma(), Cinfo::isA(), nuParser::LEN, Vec::length(), nuParser::MAXG, maxG_, nuParser::MAXL, maxL_, nuParser::MAXP, maxP_, nuParser::numVal, nuParser::nuParser(), nuParser::OLDVAL, nuParser::P, segIndex_, segs_, soma_, SwcSegment::vec(), Vec::Vec(), nuParser::X, nuParser::Y, and nuParser::Z.
Referenced by buildElist(), getExprElist(), and getExprVal().
getChannelDistribution()
vector< string > Neuron::getChannelDistribution (const Eref & e) const
Definition at line 1204 of file Neuron.cpp.
{
    return channelDistribution_;
}
References channelDistribution_.
Referenced by initCinfo().
getCM()
double Neuron::getCM () const
Definition at line 865 of file Neuron.cpp.
{
    return CM_;
}
References CM_.
Referenced by initCinfo().
getCompartmentLengthInLambdas()
double Neuron::getCompartmentLengthInLambdas () const
Definition at line 919 of file Neuron.cpp.
{
    return compartmentLengthInLambdas_;
}
References compartmentLengthInLambdas_.
Referenced by initCinfo().
getCompartments()
vector< ObjId > Neuron::getCompartments () const
Definition at line 965 of file Neuron.cpp.
{
    vector< ObjId > ret( segId_.size() );
    for ( unsigned int i = 0; i < segId_.size(); ++i )
        ret[i] = segId_[i];
    return ret;
}
References segId_.
Referenced by initCinfo().
getElecDistFromSoma()
vector< double > Neuron::getElecDistFromSoma () const
Definition at line 957 of file Neuron.cpp.
{
    vector< double > ret( segs_.size(), 0.0 );
    for ( unsigned int i = 0; i < segs_.size(); ++i )
        ret[i] = segs_[i].getElecDistFromSoma();
    return ret;
}
References SwcSegment::getElecDistFromSoma(), and segs_.
Referenced by initCinfo().
getEm()
double Neuron::getEm () const
Definition at line 875 of file Neuron.cpp.
{
    return Em_;
}
References Em_.
Referenced by initCinfo().
getExprElist()
vector< ObjId > Neuron::getExprElist (const Eref & e, string line) const
Digest the path and the math expression to obtain an elist of compartments that satisfy both criteria. The argument 'line' has path followed by the math expression, separated by a space.
Definition at line 979 of file Neuron.cpp.
{
    Shell* shell = reinterpret_cast< Shell* >( Id().eref().data() );
    vector< ObjId > ret;
    vector< ObjId > elist;
    vector< double > val;
    unsigned long pos = line.find_first_of( " \t" );
    string path = line.substr( 0, pos );
    string expr = line.substr( pos );
    ObjId oldCwe = shell->getCwe();
    shell->setCwe( e.objId() );
    wildcardFind( path, elist );
    shell->setCwe( oldCwe );
    if ( elist.size() == 0 )
        return ret;
    evalExprForElist( elist, expr, val );
    ret.reserve( elist.size() );
    for ( unsigned int i = 0; i < elist.size(); ++i )
    {
        if ( val[i * nuParser::numVal] > 0 )
            ret.push_back( elist[i] );
    }
    return ret;
}
References Eref::data(), Id::eref(), evalExprForElist(), Shell::getCwe(), Id::Id(), nuParser::numVal, Eref::objId(), Shell::setCwe(), and wildcardFind().
Referenced by initCinfo().
getExprVal()
vector< double > Neuron::getExprVal (const Eref & e, string line) const
Digest the path and the math expression to obtain all the values pertaining to the elements in the path. There are nuParser::numVal * elist.size() entries. The argument 'line' has path followed by the math expression, separated by a space.
Definition at line 1011 of file Neuron.cpp.
{
    Shell* shell = reinterpret_cast< Shell* >( Id().eref().data() );
    vector< ObjId > elist;
    vector< double > val;
    unsigned long pos = line.find_first_of( " \t" );
    string path = line.substr( 0, pos );
    string expr = line.substr( pos );
    ObjId oldCwe = shell->getCwe();
    shell->setCwe( e.objId() );
    wildcardFind( path, elist );
    shell->setCwe( oldCwe );
    if ( elist.size() == 0 )
        return val;
    evalExprForElist( elist, expr, val );
    return val;
}
References Eref::data(), Id::eref(), evalExprForElist(), Shell::getCwe(), Id::Id(), Eref::objId(), Shell::setCwe(), and wildcardFind().
Referenced by initCinfo().
getGeomDistFromSoma()
vector< double > Neuron::getGeomDistFromSoma () const
Definition at line 949 of file Neuron.cpp.
{
    vector< double > ret( segs_.size(), 0.0 );
    for ( unsigned int i = 0; i < segs_.size(); ++i )
        ret[i] = segs_[i].getGeomDistFromSoma();
    return ret;
}
References SwcSegment::getGeomDistFromSoma(), and segs_.
Referenced by initCinfo().
getNumBranches()
unsigned int Neuron::getNumBranches () const
Definition at line 936 of file Neuron.cpp.
{
    return branches_.size();
}
References branches_.
Referenced by initCinfo().
getNumCompartments()
unsigned int Neuron::getNumCompartments () const
Definition at line 924 of file Neuron.cpp.
{
    return segId_.size();
}
References segId_.
Referenced by initCinfo().
getNumSpines()
unsigned int Neuron::getNumSpines () const
Definition at line 2106 of file Neuron.cpp.
{
    return spines_.size();
}
References spines_.
Referenced by initCinfo().
getParentCompartmentOfSpine()
ObjId Neuron::getParentCompartmentOfSpine (const Eref & e, ObjId compt) const
Definition at line 1083 of file Neuron.cpp.
{
    for ( unsigned int comptIndex = 0; comptIndex < allSpinesPerCompt_.size(); ++comptIndex )
    {
        const vector< Id >& v = allSpinesPerCompt_[comptIndex];
        for ( unsigned int j = 0; j < v.size(); j++ )
            if ( v[j] == compt.id )
                return segId_[ comptIndex ];
    }
    return ObjId();
}
References allSpinesPerCompt_, ObjId::id, ObjId::ObjId(), Id::operator==(), and segId_.
Referenced by initCinfo().
getPassiveDistribution()
vector< string > Neuron::getPassiveDistribution (const Eref & e) const
Definition at line 1229 of file Neuron.cpp.
{
    return passiveDistribution_;
}
References passiveDistribution_.
Referenced by initCinfo().
getPathDistFromSoma()
vector< double > Neuron::getPathDistFromSoma () const
Definition at line 941 of file Neuron.cpp.
{
    vector< double > ret( segs_.size(), 0.0 );
    for ( unsigned int i = 0; i < segs_.size(); ++i )
        ret[i] = segs_[i].getPathDistFromSoma();
    return ret;
}
References SwcSegment::getPathDistFromSoma(), and segs_.
Referenced by initCinfo().
getPhi()
double Neuron::getPhi () const
Definition at line 897 of file Neuron.cpp.
{
    return phi_;
}
References phi_.
Referenced by initCinfo().
getRA()
double Neuron::getRA () const
Definition at line 853 of file Neuron.cpp.
{
    return RA_;
}
References RA_.
Referenced by initCinfo().
getRM()
double Neuron::getRM () const
Definition at line 841 of file Neuron.cpp.
{
    return RM_;
}
References RM_.
Referenced by initCinfo().
getSourceFile()
string Neuron::getSourceFile () const
Definition at line 909 of file Neuron.cpp.
{
    return sourceFile_;
}
References sourceFile_.
Referenced by initCinfo().
getSpineDistribution()
vector< string > Neuron::getSpineDistribution (const Eref & e) const
Definition at line 1251 of file Neuron.cpp.
{
    return spineDistribution_;
}
References spineDistribution_.
Referenced by initCinfo().
getSpineFromCompartment()
ObjId Neuron::getSpineFromCompartment (const Eref & e, ObjId compt) const
Definition at line 1096 of file Neuron.cpp.
{
    for ( unsigned int i = 0; i < spines_.size(); ++i )
    {
        for ( auto j = spines_[i].begin(); j != spines_[i].end(); ++j ) {
            if ( *j == compt.id ) {
                Id spineBase = Id( e.id().value() + 1 );
                return ObjId( spineBase, e.dataIndex(), i );
            }
        }
    }
    return ObjId();
}
References Eref::dataIndex(), Eref::id(), Id::Id(), ObjId::id, ObjId::ObjId(), ObjId::ObjId(), Id::operator==(), spines_, and Id::value().
Referenced by initCinfo().
getSpinesOnCompartment()
vector< ObjId > Neuron::getSpinesOnCompartment (const Eref & e, ObjId compt) const
Definition at line 1067 of file Neuron.cpp.
{
    vector< ObjId > ret;
    map< Id, unsigned int >::const_iterator pos =
        segIndex_.find( compt.id );
    if ( pos != segIndex_.end() )
    {
        assert( pos->second < allSpinesPerCompt_.size() );
        const vector< Id >& spines = allSpinesPerCompt_[pos->second];
        for ( unsigned int i = 0; i < spines.size(); ++i )
            ret.push_back( spines[i] );
    }
    return ret;
}
References allSpinesPerCompt_, ObjId::id, and segIndex_.
Referenced by initCinfo().
getTheta()
double Neuron::getTheta () const
Definition at line 886 of file Neuron.cpp.
{
    return theta_;
}
References theta_.
Referenced by initCinfo().
initCinfo()
const Cinfo * Neuron::initCinfo () static
Initializes the class info.
Definition at line 111 of file Neuron.cpp.
{
    // ValueFinfos
    static ValueFinfo< Neuron, double > RM( "RM",
                                            "Membrane resistivity, in ohm.m^2. Default value is 1.0.",
                                            &Neuron::setRM,
                                            &Neuron::getRM
                                          );
    static ValueFinfo< Neuron, double > RA( "RA",
                                            "Axial resistivity of cytoplasm, in ohm.m. Default value is 1.0.",
                                            &Neuron::setRA,
                                            &Neuron::getRA
                                          );
    static ValueFinfo< Neuron, double > CM( "CM",
                                            "Membrane Capacitance, in F/m^2. Default value is 0.01",
                                            &Neuron::setCM,
                                            &Neuron::getCM
                                          );
    static ValueFinfo< Neuron, double > Em( "Em",
                                            "Resting membrane potential of compartments, in Volts. "
                                            "Default value is -0.065.",
                                            &Neuron::setEm,
                                            &Neuron::getEm
                                          );
    static ValueFinfo< Neuron, double > theta( "theta",
            "Angle to rotate cell geometry, around long axis of neuron. "
            "Think Longitude. Units are radians. "
            "Default value is zero, which means no rotation. ",
            &Neuron::setTheta,
            &Neuron::getTheta
                                             );
    static ValueFinfo< Neuron, double > phi( "phi",
            "Angle to rotate cell geometry, around elevation of neuron. "
            "Think Latitude. Units are radians. "
            "Default value is zero, which means no rotation. ",
            &Neuron::setPhi,
            &Neuron::getPhi
                                           );
    static ValueFinfo< Neuron, string > sourceFile( "sourceFile",
            "Name of source file from which to load a model. "
            "Accepts swc and dotp formats at present. "
            "Both these formats require that the appropriate channel "
            "definitions should have been loaded into /library. ",
            &Neuron::setSourceFile,
            &Neuron::getSourceFile
                                                  );
    static ValueFinfo< Neuron, double > compartmentLengthInLambdas(
        "compartmentLengthInLambdas",
        "Units: meters (SI). \n"
        "Electrotonic length to use for the largest compartment in the "
        "model. Used to define subdivision of branches into compartments. "
        "For example, if we set *compartmentLengthInLambdas*  to 0.1, "
        "and *lambda* (electrotonic length) is 250 microns, then it "
        "sets the compartment length to 25 microns. Thus a dendritic "
        "branch of 500 microns is subdivided into 20 commpartments. "
        "If the branch is shorter than *compartmentLengthInLambdas*, "
        "then it is not subdivided. "
        "If *compartmentLengthInLambdas* is set to 0 then the original "
        "compartmental structure of the model is preserved. "
        " Note that this routine does NOT merge branches, even if "
        "*compartmentLengthInLambdas* is bigger than the branch. "
        "While all this subdivision is being done, the Neuron class "
        "preserves as detailed a geometry as it can, so it can rebuild "
        "the more detailed version if needed. "
        "Default value of *compartmentLengthInLambdas* is 0. ",
        &Neuron::setCompartmentLengthInLambdas,
        &Neuron::getCompartmentLengthInLambdas
    );
    static ElementValueFinfo< Neuron, vector< string > >
    channelDistribution(
        "channelDistribution",
        "Specification for distribution of channels, CaConcens and "
        "any other model components that are defined as prototypes and "
        "have to be placed on the electrical compartments.\n"
        "Arguments: proto path field expr [field expr]...\n"
        " Each entry is terminated with an empty string. "
        "The prototype is any object created in */library*, "
        "If a channel matching the prototype name already exists, then "
        "all subsequent operations are applied to the extant channel and "
        "a new one is not created. "
        "The paired arguments are as follows: \n"
        "The *field* argument specifies the name of the parameter "
        "that is to be assigned by the expression.\n"
        "The *expression* argument is a mathematical expression in "
        "the muparser framework, which permits most operations including "
        "trig and transcendental ones. Of course it also handles simple "
        "numerical values like 1.0, 1e-10 and so on. "
        "Available arguments for muParser are:\n"
        " p, g, L, len, dia, maxP, maxG, maxL \n"
        "   p: path distance from soma, measured along dendrite, in metres.\n"
        "   g: geometrical distance from soma, in metres.\n"
        "   L: electrotonic distance (# of lambdas) from soma, along dend. No units.\n"
        "   len: length of compartment, in metres.\n"
        "   dia: for diameter of compartment, in metres.\n"
        "   maxP: Maximum value of *p* for this neuron. \n"
        "   maxG: Maximum value of *g* for this neuron. \n"
        "   maxL: Maximum value of *L* for this neuron.\n"
        "The expression for the first field must evaluate to > 0 "
        "for the channel to be installed. For example, for "
        "channels, if Field == Gbar, and func( r, L, len, dia) < 0, \n"
        "then the channel is not installed. This feature is typically "
        "used with the sign() or Heaviside H() function to limit range: "
        "for example: H(1 - L) will only put channels closer than "
        "one length constant from the soma, and zero elsewhere. \n"
        "Available fields are: \n"
        "Channels: Gbar (install), Ek \n"
        "CaConcen: shellDia (install), shellFrac (install), tau, min\n"
        "Unless otherwise noted, all fields are scaled appropriately by "
        "the dimensions of their compartment. Thus the channel "
        "maximal conductance Gbar is automatically scaled by the area "
        "of the compartment, and the user does not need to insert this "
        "scaling into the calculations.\n"
        "All parameters are expressed in SI units. Conductance, for "
        "example, is Siemens/sq metre. "
        "\n\n"
        "Some example function forms might be for a channel Gbar: \n"
        " p < 10e-6 ? 400 : 0.0 \n"
        "       equivalently, \n"
        " H(10e-6 - p) * 400 \n"
        "       equivalently, \n"
        " ( sign(10e-6 - p) + 1) * 200 \n"
        "Each of these forms instruct the function to "
        "set channel Gbar to 400 S/m^2 only within 10 microns path "
        "distance of soma\n"
        "\n"
        " L < 1.0 ? 100 * exp( -L ) : 0.0 \n"
        " ->Set channel Gbar to an exponentially falling function of "
        "electrotonic distance from soma, provided L is under "
        "1.0 lambdas. \n",
        &Neuron::setChannelDistribution,
        &Neuron::getChannelDistribution
    );
    static ElementValueFinfo< Neuron, vector< string > >
    passiveDistribution(
        "passiveDistribution",
        "Specification for distribution of passive properties of cell.\n"
        "Arguments: . path field expr [field expr]...\n"
        "Note that the arguments list starts with a period. "
        " Each entry is terminated with an empty string. "
        "The paired arguments are as follows: \n"
        "The *field* argument specifies the name of the parameter "
        "that is to be assigned by the expression.\n"
        "The *expression* argument is a mathematical expression in "
        "the muparser framework, which permits most operations including "
        "trig and transcendental ones. Of course it also handles simple "
        "numerical values like 1.0, 1e-10 and so on. "
        "Available arguments for muParser are:\n"
        " p, g, L, len, dia, maxP, maxG, maxL \n"
        "   p: path distance from soma, measured along dendrite, in metres.\n"
        "   g: geometrical distance from soma, in metres.\n"
        "   L: electrotonic distance (# of lambdas) from soma, along dend. No units.\n"
        "   len: length of compartment, in metres.\n"
        "   dia: for diameter of compartment, in metres.\n"
        "   maxP: Maximum value of *p* for this neuron. \n"
        "   maxG: Maximum value of *g* for this neuron. \n"
        "   maxL: Maximum value of *L* for this neuron.\n"
        "Available fields are: \n"
        "RM, RA, CM, Rm, Ra, Cm, Em, initVm \n"
        "The first three fields are scaled appropriately by "
        "the dimensions of their compartment. Thus the membrane "
        "resistivity RM (ohms.m^2) is automatically scaled by the area "
        "of the compartment, and the user does not need to insert this "
        "scaling into the calculations to compute Rm."
        "Using the Rm field lets the user directly assign the "
        "membrane resistance (in ohms), presumably using len and dia.\n"
        "Similarly, RA (ohms.m) and CM (Farads/m^2) are specific units "
        "and the actual values for each compartment are assigned by "
        "scaling by length and diameter. Ra (ohms) and Cm (Farads) "
        "require explicit evaluation of the expression. "
        "All parameters are expressed in SI units. Conductance, for "
        "example, is Siemens/sq metre.\n"
        "Note that time these calculations do NOT currently include spines\n",
        &Neuron::setPassiveDistribution,
        &Neuron::getPassiveDistribution
    );
    static ElementValueFinfo< Neuron, vector< string > >spineDistribution(
        "spineDistribution",
        "Specification for distribution of spines on dendrite. \n"
        "Arguments: proto path spacing expr [field expr]...\n"
        " Each entry is terminated with an empty string. "
        "The *prototype* is any spine object created in */library*, \n"
        "The *path* is the wildcard path of compartments on which to "
        "place the spine.\n"
        "The *spacing* is the spacing of spines, in metres. \n"
        "The *expression* argument is a mathematical expression in "
        "the muparser framework, which permits most operations including "
        "trig and transcendental ones. Of course it also handles simple "
        "numerical values like 1.0, 1e-10 and so on. "
        "The paired arguments are as follows: \n"
        "The *field* argument specifies the name of the parameter "
        "that is to be assigned by the expression.\n"
        "The *expression* argument is a mathematical expression as above. "
        "Available arguments for muParser are:\n"
        " p, g, L, len, dia, maxP, maxG, maxL \n"
        "   p: path distance from soma, measured along dendrite, in metres.\n"
        "   g: geometrical distance from soma, in metres.\n"
        "   L: electrotonic distance (# of lambdas) from soma, along dend. No units.\n"
        "   len: length of compartment, in metres.\n"
        "   dia: for diameter of compartment, in metres.\n"
        "   maxP: Maximum value of *p* for this neuron. \n"
        "   maxG: Maximum value of *g* for this neuron. \n"
        "   maxL: Maximum value of *L* for this neuron.\n"
        "The expression for the *spacing* field must evaluate to > 0 for "
        "the spine to be installed. For example, if the expresssion is\n"
        "       H(1 - L) \n"
        "then the systemwill only put spines closer than "
        "one length constant from the soma, and zero elsewhere. \n"
        "Available spine parameters are: \n"
        "spacing, minSpacing, size, sizeDistrib "
        "angle, angleDistrib \n"
        "minSpacing sets the granularity of sampling (typically about 0.1*"
        "spacing) for the usual case where spines are spaced randomly. "
        "If minSpacing < 0 then the spines are spaced equally at "
        "'spacing', unless the dendritic segment length is smaller than "
        "'spacing'. In that case it falls back to the regular random "
        "placement method.",
        &Neuron::setSpineDistribution,
        &Neuron::getSpineDistribution
    );
    static ReadOnlyValueFinfo< Neuron, unsigned int > numCompartments(
        "numCompartments",
        "Number of electrical compartments in model. ",
        &Neuron::getNumCompartments
    );
    static ReadOnlyValueFinfo< Neuron, unsigned int > numSpines(
        "numSpines",
        "Number of dendritic spines in model. ",
        &Neuron::getNumSpines
    );
    static ReadOnlyValueFinfo< Neuron, unsigned int > numBranches(
        "numBranches",
        "Number of branches in dendrites. ",
        &Neuron::getNumBranches
    );
    static ReadOnlyValueFinfo< Neuron, vector< double > > pathDistFromSoma(
        "pathDistanceFromSoma",
        "geometrical path distance of each segment from soma, measured by "
        "threading along the dendrite.",
        &Neuron::getPathDistFromSoma
    );
    static ReadOnlyValueFinfo< Neuron, vector< double > > geomDistFromSoma(
        "geometricalDistanceFromSoma",
        "geometrical distance of each segment from soma.",
        &Neuron::getGeomDistFromSoma
    );
    static ReadOnlyValueFinfo< Neuron, vector< double > > elecDistFromSoma(
        "electrotonicDistanceFromSoma",
        "geometrical distance of each segment from soma, as measured along "
        "the dendrite.",
        &Neuron::getElecDistFromSoma
    );
    static ReadOnlyValueFinfo< Neuron, vector< ObjId > > compartments(
        "compartments",
        "Vector of ObjIds of electrical compartments. Order matches order "
        "of segments, and also matches the order of the electrotonic and "
        "geometricalDistanceFromSoma vectors. ",
        &Neuron::getCompartments
    );
    static ReadOnlyLookupElementValueFinfo< Neuron, string, vector< ObjId > >
    compartmentsFromExpression(
        "compartmentsFromExpression",
        "Vector of ObjIds of electrical compartments that match the "
        "'path expression' pair in the argument string.",
        &Neuron::getExprElist
    );
    static ReadOnlyLookupElementValueFinfo< Neuron, string, vector< double > >
    valuesFromExpression(
        "valuesFromExpression",
        "Vector of values computed for each electrical compartment that "
        "matches the 'path expression' pair in the argument string."
        "This has 13 times the number of entries as # of compartments."
        "For each compartment the entries are: \n"
        "val, p, g, L, len, dia, maxP, maxG, maxL, x, y, z, 0",
        &Neuron::getExprVal
    );
    static ReadOnlyLookupElementValueFinfo< Neuron, string, vector< ObjId > >
    spinesFromExpression(
        "spinesFromExpression",
        //"Vector of ObjIds of spines/heads sitting on the electrical "
        //"compartments that match the 'path expression' pair in the "
        //"argument string.",
        "Vector of ObjIds of compartments comprising spines/heads "
        "that match the 'path expression' pair in the "
        "argument string.",
        &Neuron::getExprElist
    );
    static ReadOnlyLookupElementValueFinfo< Neuron, ObjId,vector< ObjId > >
    spinesOnCompartment(
        "spinesOnCompartment",
        "Vector of ObjIds of spines shafts/heads sitting on the specified "
        "electrical compartment. If each spine has a shaft and a head,"
        "and there are 10 spines on the compartment, there will be 20 "
        "entries in the returned vector, ordered "
        "shaft0, head0, shaft1, head1, ... ",
        &Neuron::getSpinesOnCompartment
    );
    static ReadOnlyLookupElementValueFinfo< Neuron, ObjId, ObjId >
    parentCompartmentOfSpine(
        "parentCompartmentOfSpine",
        "Returns parent compartment of specified spine compartment."
        "Both the spine head or its shaft will return the same parent.",
        &Neuron::getParentCompartmentOfSpine
    );
    /*
    static ReadOnlyLookupElementValueFinfo< Neuron, vector< ObjId >, vector< ObjId > >
    spineIdsFromCompartmentIds(
        "spineIdsFromCompartmentIds",
        "Vector of ObjIds of spine entries (FieldElements on this Neuron, "
        "used for scaling) that map to the the specified "
        "electrical compartments. If a bad compartment Id is given, the"
        "corresponding spine entry is the root Id.",
        &Neuron::getSpineIdsFromCompartmentIds
    );
    */
    static ReadOnlyLookupElementValueFinfo< Neuron, ObjId, ObjId >
    spineFromCompartment(
        "spineFromCompartment",
        "Returns ObjIds of spine entries (FieldElements on this Neuron, "
        "used for scaling) that map to the the specified "
        "electrical compartment. If a bad compartment Id is given, "
        "returns the root ObjId.",
        &Neuron::getSpineFromCompartment
    );
    // DestFinfos
    static DestFinfo buildSegmentTree( "buildSegmentTree",
                                       "Build the reference segment tree structure using the child "
                                       "compartments of the current Neuron. Fills in all the coords and "
                                       "length constant information into the segments, for later use "
                                       "when we build reduced compartment trees and channel "
                                       "distributions. Should only be called once, since subsequent use "
                                       "on a reduced model will lose the original full cell geometry. ",
                                       new EpFunc0< Neuron >( &Neuron::buildSegmentTree )
                                     );
    static DestFinfo setSpineAndPsdMesh( "setSpineAndPsdMesh",
                                         "Assigns the spine and psd mesh to the Neuron. This is used "
                                         "to build up a mapping from Spine entries on the Neuron to "
                                         "chem spines and PSDs, so that volume change operations from "
                                         "the Spine can propagate to the chem systems.",
                                         new OpFunc2< Neuron, ObjId, ObjId >( &Neuron::setSpineAndPsdMesh )
                                       );
    static DestFinfo setSpineAndPsdDsolve( "setSpineAndPsdDsolve",
                                           "Assigns the Dsolves used by spine and PSD to the Neuron. "
                                           "This is used "
                                           "to handle the rescaling of diffusion rates when spines are "
                                           "resized. ",
                                           new OpFunc2< Neuron, ObjId, ObjId >( &Neuron::setSpineAndPsdDsolve )
                                         );
    /*
    static DestFinfo rotateInSpace( "rotateInSpace",
        theta, phi
    static DestFinfo transformInSpace( "transformInSpace",
        transfMatrix(4x4)
    static DestFinfo saveAsNeuroML( "saveAsNeuroML", fname )
    static DestFinfo saveAsDotP( "saveAsDotP", fname )
    static DestFinfo saveAsSwc( "saveAsSwc", fname )
    */
    // FieldElement
    static FieldElementFinfo< Neuron, Spine > spineFinfo(
        "spine",
        "Field Element for spines. Used to handle dynamic "
        "geometry changes in spines. ",
        Spine::initCinfo(),
        &Neuron::lookupSpine,
        &Neuron::setNumSpines,
        &Neuron::getNumSpines,
        false
    );
    static Finfo* neuronFinfos[] =
    {
        &RM,                        // ValueFinfo
        &RA,                        // ValueFinfo
        &CM,                        // ValueFinfo
        &Em,                        // ValueFinfo
        &theta,                     // ValueFinfo
        &phi,                       // ValueFinfo
        &sourceFile,                // ValueFinfo
        &compartmentLengthInLambdas,    // ValueFinfo
        &numCompartments,           // ReadOnlyValueFinfo
        &numSpines,                 // ReadOnlyValueFinfo
        &numBranches,               // ReadOnlyValueFinfo
        &pathDistFromSoma,          // ReadOnlyValueFinfo
        &geomDistFromSoma,          // ReadOnlyValueFinfo
        &elecDistFromSoma,          // ReadOnlyValueFinfo
        &compartments,              // ReadOnlyValueFinfo
        &channelDistribution,       // ValueFinfo
        &passiveDistribution,       // ValueFinfo
        &spineDistribution,         // ValueFinfo
        // &mechSpec,               // ValueFinfo
        // &spineSpecification,     // ValueFinfo
        &compartmentsFromExpression,    // ReadOnlyLookupValueFinfo
        &valuesFromExpression,      // ReadOnlyLookupValueFinfo
        &spinesFromExpression,      // ReadOnlyLookupValueFinfo
        &spinesOnCompartment,       // ReadOnlyLookupValueFinfo
        &parentCompartmentOfSpine,  // ReadOnlyLookupValueFinfo
        &spineFromCompartment,      // ReadOnlyLookupValueFinfo
        &buildSegmentTree,          // DestFinfo
        &setSpineAndPsdMesh,        // DestFinfo
        &setSpineAndPsdDsolve,      // DestFinfo
        &spineFinfo,                // FieldElementFinfo
    };
    static string doc[] =
    {
        "Name", "Neuron",
        "Author", "C H Chaitanya, Upi Bhalla",
        "Description", "Neuron - Manager for neurons. "
        "Handles high-level specification of distribution of "
        "spines, channels and passive properties. Also manages "
        "spine resizing through a Spine FieldElement. ",
    };
    static Dinfo<Neuron> dinfo;
    static Cinfo neuronCinfo(
        "Neuron",
        Neutral::initCinfo(),
        neuronFinfos, sizeof( neuronFinfos ) / sizeof( Finfo* ),
        &dinfo,
        doc,
        sizeof(doc)/sizeof(string)
    );
    return &neuronCinfo;
}
References buildSegmentTree(), Cinfo::Cinfo(), DestFinfo::DestFinfo(), ElementValueFinfo< T, F >::ElementValueFinfo(), EpFunc0< T >::EpFunc0(), FieldElementFinfo< T, F >::FieldElementFinfo(), getChannelDistribution(), getCM(), getCompartmentLengthInLambdas(), getCompartments(), getElecDistFromSoma(), getEm(), getExprElist(), getExprVal(), getGeomDistFromSoma(), getNumBranches(), getNumCompartments(), getNumSpines(), getParentCompartmentOfSpine(), getPassiveDistribution(), getPathDistFromSoma(), getPhi(), getRA(), getRM(), getSourceFile(), getSpineDistribution(), getSpineFromCompartment(), getSpinesOnCompartment(), getTheta(), Spine::initCinfo(), Neutral::initCinfo(), lookupSpine(), OpFunc2< T, A1, A2 >::OpFunc2(), ReadOnlyLookupElementValueFinfo< T, L, F >::ReadOnlyLookupElementValueFinfo(), ReadOnlyValueFinfo< T, F >::ReadOnlyValueFinfo(), setChannelDistribution(), setCM(), setCompartmentLengthInLambdas(), setEm(), setNumSpines(), setPassiveDistribution(), setPhi(), setRA(), setRM(), setSourceFile(), setSpineAndPsdDsolve(), setSpineAndPsdMesh(), setSpineDistribution(), setTheta(), and ValueFinfo< T, F >::ValueFinfo().
installMechanism()
void Neuron::installMechanism (const string & name, const vector< ObjId > & elist, const vector< double > & val, const vector< string > & line)
installSpines()
void Neuron::installSpines (const vector< ObjId > & elist, const vector< double > & val, const vector< string > & line)
Now fill in allSpinesPerCompt_ vector. It was allocated in buildSegmentTree, right after segId_ was filled.
Definition at line 2039 of file Neuron.cpp.
{
    Id spineProto( "/library/" + line[0] );
    // Id spineProto( "/library/spine" );
    if ( spineProto == Id() )
    {
        cout << "Warning: Neuron::installSpines: Unable to find prototype spine: /library/" << line[0] << endl;
        return;
    }
    // Look up elist index from pos index, since there may be many
    // spines on each segment.
    vector< unsigned int > elistIndex;
    vector< double > pos; // spacing of the new spines along compt.
    vector< double > theta; // Angle of spines
    vector< double > size; // Size scaling of spines
    pos.reserve( elist.size() );
    elistIndex.reserve( elist.size() );
    vector< unsigned int > localSpineParentSegIndex;
    makeSpacingDistrib( elist, val,
                        localSpineParentSegIndex, elistIndex, pos, line);
    makeAngleDistrib( elist, val, elistIndex, theta, line );
    makeSizeDistrib( elist, val, elistIndex, size, line );
    unsigned int startNumSpines = spines_.size();
    for ( unsigned int k = 0; k < localSpineParentSegIndex.size(); ++k )
    {
        unsigned int i = localSpineParentSegIndex[k];
        Vec x, y, z;
        coordSystem( soma_, segId_[i], x, y, z );
        spines_.push_back(
            addSpine( segId_[i], spineProto, pos[k], theta[k],
                      x, y, z, size[k], k )
        );
    }
    // spineToMeshOrdering_.clear();
    spineToMeshOrdering_.resize( spines_.size(), 0 );
    // spineStoich_.clear();
    spineStoich_.resize( spines_.size() );
    // psdStoich_.clear();
    psdStoich_.resize( spines_.size() );
    for ( unsigned int i = 0; i < localSpineParentSegIndex.size(); ++i )
    {
        assert( allSpinesPerCompt_.size() > localSpineParentSegIndex[i] );
        vector< Id >& s = allSpinesPerCompt_[ localSpineParentSegIndex[i]];
        unsigned int j = startNumSpines + i;
        s.insert( s.end(), spines_[j].begin(), spines_[j].end() );
    }
}
References addSpine(), allSpinesPerCompt_, coordSystem(), Id::Id(), Id::Id(), makeAngleDistrib(), makeSizeDistrib(), makeSpacingDistrib(), Id::operator==(), psdStoich_, segId_, soma_, spines_, spineStoich_, and spineToMeshOrdering_.
Referenced by setSpineDistribution().
lookupSpine()
Spine * Neuron::lookupSpine (unsigned int index)
Definition at line 2095 of file Neuron.cpp.
{
    return &spineEntry_;
}
References spineEntry_.
Referenced by initCinfo().
makeSpacingDistrib()
void Neuron::makeSpacingDistrib (const vector< ObjId > & elist, const vector< double > & val, vector< unsigned int > & seglistIndex, vector< unsigned int > & elistIndex, vector< double > & pos, const vector< string > & line) const
Definition at line 1913 of file Neuron.cpp.
{
    string distribExpr = findArg( line, "spacingDistrib"  );
    pos.resize( 0 );
    elistIndex.resize( 0 );
    try
    {
        nuParser parser( distribExpr );
        for ( unsigned int i = 0; i < elist.size(); ++i )
        {
            unsigned int j = i * nuParser::numVal;
            if ( val[ j + nuParser::EXPR ] > 0 )
            {
                double spacing = val[ j + nuParser::EXPR ];
                double spacingDistrib = parser.eval( val.begin() + j );
                map< Id, unsigned int>::const_iterator
                lookupDend = segIndex_.find( elist[i] );
                if ( lookupDend != segIndex_.end() )
                {
                    double dendLength = segs_[lookupDend->second].length();
                    addPos( lookupDend->second, i,
                            spacing, spacingDistrib, dendLength,
                            seglistIndex, elistIndex, pos );
                }
            }
        }
    }
    catch ( moose::Parser::exception_type& err )
    {
        cerr << err.GetMsg() << endl;
    }
}
References addPos(), nuParser::eval(), nuParser::EXPR, findArg(), moose::Parser::ParserException::GetMsg(), SwcSegment::length(), nuParser::numVal, nuParser::nuParser(), segIndex_, and segs_.
Referenced by installSpines().
parseMechSpec()
void Neuron::parseMechSpec (const Eref & e)
scaleBufAndRates()
void Neuron::scaleBufAndRates (unsigned int spineNum, double lenScale, double diaScale) const
Definition at line 2122 of file Neuron.cpp.
{
    double volScale = lenScale * diaScale * diaScale;
    if ( doubleEq( volScale, 1.0 ) )
        return;
    if ( spineStoich_.size() == 0 )
        // Perhaps no chem stuff in model, but user could have forgotten
        // to assign psd and spine meshes.
        return;
    if ( spineNum > spineStoich_.size() )
    {
        cout << "Error: Neuron::scaleBufAndRates: spineNum too big: " <<
             spineNum << " >= " << spineStoich_.size() << endl;
        return;
    }
    Id ss = spineStoich_[ spineNum ];
    if ( ss == Id() )
    {
        // The chem system for the spine may not have been defined.
        // Later figure out how to deal with cases where there is a psd
        // but no spine.
        return;
    }
    Id ps = psdStoich_[ spineNum ];
    if ( ps == Id() )
    {
        // The chem system for the spine may not have been defined.
        return;
    }
    SetGet2< unsigned int, double >::set( ss, "scaleBufsAndRates",
                                          spineToMeshOrdering_[spineNum], volScale );
    volScale = diaScale * diaScale;
    SetGet2< unsigned int, double >::set( ps, "scaleBufsAndRates",
                                          spineToMeshOrdering_[spineNum], volScale );
}
References doubleEq(), Id::Id(), Id::operator==(), psdStoich_, SetGet2< A1, A2 >::set(), spineStoich_, and spineToMeshOrdering_.
Referenced by Spine::setHeadDiameter(), Spine::setHeadLength(), and Spine::setHeadVolume().
scaleHeadDiffusion()
void Neuron::scaleHeadDiffusion (unsigned int spineNum, double len, double dia) const
Scale the diffusion parameters due to a change in the head dimensions.
Definition at line 2173 of file Neuron.cpp.
{
    double vol = len * dia * dia * PI * 0.25;
    // Note that the diffusion scale for the PSD uses half the length
    // of the head compartment. I'm explicitly putting this in below.
    double diffScale = dia * dia * 0.25 * PI / (len/2.0);
    unsigned int meshIndex = spineToMeshOrdering_[ spineNum ];
    Id headCompt = Field< Id >::get( headDsolve_, "compartment" );
    LookupField< unsigned int, double >::set( headCompt, "oneVoxelVolume",
            meshIndex, vol );
    Id psdCompt = Field< Id >::get( psdDsolve_, "compartment" );
    double thick = Field< double >::get( psdCompt, "thickness" );
    double psdVol = thick * dia * dia * PI * 0.25;
    LookupField< unsigned int, double >::set( psdCompt, "oneVoxelVolume",
            meshIndex, psdVol );
    SetGet2< unsigned int, double >::set(
        headDsolve_, "setDiffVol1", meshIndex, vol );
    SetGet2< unsigned int, double >::set(
        psdDsolve_, "setDiffVol2", meshIndex, vol );
    SetGet2< unsigned int, double >::set(
        psdDsolve_, "setDiffVol1", meshIndex, psdVol );
    SetGet2< unsigned int, double >::set(
        psdDsolve_, "setDiffScale", meshIndex, diffScale );
}
References Field< A >::get(), headDsolve_, PI, psdDsolve_, SetGet2< A1, A2 >::set(), LookupField< L, A >::set(), and spineToMeshOrdering_.
Referenced by Spine::setHeadDiameter(), Spine::setHeadLength(), and Spine::setHeadVolume().
scaleShaftDiffusion()
void Neuron::scaleShaftDiffusion (unsigned int spineNum, double len, double dia) const
Scale the diffusion parameters due to a change in the shaft dimensions.
Definition at line 2161 of file Neuron.cpp.
{
    double diffScale = dia * dia * 0.25 * PI / len;
    SetGet2< unsigned int, double >::set(
        // Note that the buildNeuroMeshJunctions function is called
        // on the dendDsolve with the args smdsolve, pmdsolve.
        headDsolve_, "setDiffScale",
        spineToMeshOrdering_[ spineNum ], diffScale );
}
References headDsolve_, PI, SetGet2< A1, A2 >::set(), and spineToMeshOrdering_.
Referenced by Spine::setShaftDiameter(), and Spine::setShaftLength().
setChannelDistribution()
void Neuron::setChannelDistribution (const Eref & e, vector< string > v)
Definition at line 1159 of file Neuron.cpp.
{
    // Here we should clear the extant channels, if any.
    vector< vector< string > > lines;
    if ( parseDistrib( lines, v ) )
    {
        unsigned int index = 0;
        vector< unsigned int > chanIndices;
        vector< unsigned int > temp;
        channelDistribution_ = v;
        // We need to ensure that Ca_concs are created before any channels
        // since the channels may want to connect to them.
        for ( unsigned int i = 0; i < lines.size(); ++i )
        {
            Id proto( "/library/" + lines[i][0] );
            if ( proto != Id() ) {
                if ( proto.element()->cinfo()->isA( "CaConcBase" ) ) {
                    chanIndices.push_back( i );
                } else {
                    temp.push_back( i );
                }
            }
        }
        chanIndices.insert( chanIndices.end(), temp.begin(), temp.end() );
        assert( chanIndices.size() == lines.size() );
        for ( unsigned int i = 0; i < lines.size(); ++i )
        {
            vector< string >& temp = lines[chanIndices[i]];
            vector< ObjId > elist;
            vector< double > val;
            buildElist( e, temp, elist, val );
            vector< ObjId > mech( elist.size() );
            if ( buildFromProto( temp[0], elist, val, mech ) )
            {
                for ( unsigned int j = 2; j < temp.size(); j += 2 )
                {
                    setMechParams( mech, elist, val, temp[j], temp[j+1] );
                }
            }
        }
    }
}
References buildElist(), buildFromProto(), channelDistribution_, Element::cinfo(), Id::element(), Id::Id(), Id::Id(), Cinfo::isA(), Id::operator!=(), parseDistrib(), and setMechParams().
Referenced by initCinfo().
setCM()
void Neuron::setCM (double v)
Definition at line 858 of file Neuron.cpp.
{
    if ( v > 0.0 )
        CM_ = v;
    else
        cout << "Warning:: Neuron::setCM: value must be +ve, is " << v << endl;
}
References CM_.
Referenced by initCinfo().
setCompartmentLengthInLambdas()
void Neuron::setCompartmentLengthInLambdas (double v)
Definition at line 915 of file Neuron.cpp.
{
    compartmentLengthInLambdas_ = v;
}
References compartmentLengthInLambdas_.
Referenced by initCinfo().
setEm()
void Neuron::setEm (double v)
Definition at line 871 of file Neuron.cpp.
{
    Em_ = v;
}
References Em_.
Referenced by initCinfo().
setNumSpines()
void Neuron::setNumSpines (unsigned int num)
Ignore it. the number of spines is set when we build the tree.
Definition at line 2100 of file Neuron.cpp.
{
    ;
}
Referenced by initCinfo().
setPassiveDistribution()
void Neuron::setPassiveDistribution (const Eref & e, vector< string > v)
Definition at line 1209 of file Neuron.cpp.
{
    vector< vector< string > > lines;
    if ( parseDistrib( lines, v ) )
    {
        passiveDistribution_ = v;
        for ( unsigned int i = 0; i < lines.size(); ++i )
        {
            vector< string >& temp = lines[i];
            vector< ObjId > elist;
            vector< double > val;
            buildElist( e, temp, elist, val );
            for ( unsigned int j = 2; j < temp.size(); j += 2 )
            {
                setCompartmentParams( elist, val, temp[j], temp[j+1] );
            }
        }
    }
}
References buildElist(), parseDistrib(), passiveDistribution_, and setCompartmentParams().
Referenced by initCinfo().
setPhi()
void Neuron::setPhi (double v)
Definition at line 892 of file Neuron.cpp.
{
    phi_ = v;
    // Do stuff here for rotating it.
}
References phi_.
Referenced by initCinfo().
setRA()
void Neuron::setRA (double v)
Definition at line 846 of file Neuron.cpp.
{
    if ( v > 0.0 )
        RA_ = v;
    else
        cout << "Warning:: Neuron::setRA: value must be +ve, is " << v << endl;
}
References RA_.
Referenced by initCinfo().
setRM()
void Neuron::setRM (double v)
Definition at line 834 of file Neuron.cpp.
{
    if ( v > 0.0 )
        RM_ = v;
    else
        cout << "Warning:: Neuron::setRM: value must be +ve, is " << v << endl;
}
References RM_.
Referenced by initCinfo().
setSourceFile()
void Neuron::setSourceFile (string v)
Definition at line 903 of file Neuron.cpp.
{
    sourceFile_ = v;
    // Stuff here for loading it.
}
References sourceFile_.
Referenced by initCinfo().
setSpineAndPsdDsolve()
void Neuron::setSpineAndPsdDsolve (ObjId spineDsolve, ObjId psdDsolve)
Definition at line 1511 of file Neuron.cpp.
{
    headDsolve_ = spineDsolve;
    psdDsolve_ = psdDsolve;
}
References headDsolve_, and psdDsolve_.
Referenced by initCinfo().
setSpineAndPsdMesh()
void Neuron::setSpineAndPsdMesh (ObjId spineMesh, ObjId psdMesh)
Fills up vector of segments. First entry is soma.
Definition at line 1459 of file Neuron.cpp.
{
    if ( !spineMesh.element()->cinfo()->isA( "SpineMesh" ) )
    {
        cout << "Error: Neuron::setSpineAndPsdMesh: '" <<
             spineMesh.path() << "' is not a SpineMesh\n";
        return;
    }
    if ( !psdMesh.element()->cinfo()->isA( "PsdMesh" ) )
    {
        cout << "Error: Neuron::setSpineAndPsdMesh: '" <<
             psdMesh.path() << "' is not a PsdMesh\n";
        return;
    }
    Id spineStoich = Neutral::child( spineMesh.eref(), "stoich" );
    Id psdStoich = Neutral::child( psdMesh.eref(), "stoich" );
    if ( spineStoich == ObjId() || psdStoich == ObjId() )
    {
        cout << "Error: Neuron::setSpineAndPsdMesh: Stoich child not found\n";
        return;
    }
    vector< Id > spineList = Field< vector< Id > >::get(
                                 spineMesh, "elecComptList" );
    vector< Id > psdList = Field< vector< Id > >::get(
                               psdMesh, "elecComptList" );
    assert( spineList.size()== psdList.size() );
    map< Id, unsigned int > spineMap; // spineMap[ SpineOnNeuron ] = index
    for ( unsigned int i = 0; i < spines_.size(); ++i )
    {
        assert( spines_[i].size() > 1 );
        spineMap[ spines_[i][1] ] = i;
    }
    // We don't want to clear this because we can use a single vector
    // to overlay a number of spine meshes, since each will be a distinct
    // subset of the full list of spines. None is used twice.
    // spineToMeshOrdering_.clear();
    for( unsigned int i = 0; i < spineList.size(); ++i )
    {
        map< Id, unsigned int >::iterator j = spineMap.find( spineList[i]);
        if ( j == spineMap.end() )
        {
            cout << "Error: Neuron::setSpineAndPsdMesh: spine '" <<
                 spineList[i].path() << "' not found on Neuron\n";
            return;
        }
        spineToMeshOrdering_[ j->second ] = i;
        spineStoich_[ j->second ] = spineStoich;
        psdStoich_[ j->second ] = psdStoich;
    }
}
References Neutral::child(), Element::cinfo(), ObjId::element(), ObjId::eref(), Field< A >::get(), Cinfo::isA(), ObjId::ObjId(), Id::operator==(), Id::path(), ObjId::path(), psdStoich_, spines_, spineStoich_, and spineToMeshOrdering_.
Referenced by initCinfo().
setSpineDistribution()
void Neuron::setSpineDistribution (const Eref & e, vector< string > v)
Definition at line 1234 of file Neuron.cpp.
{
    // Here we should clear the extant spines, if any.
    vector< vector< string > > lines;
    if ( parseDistrib( lines, v ) )
    {
        spineDistribution_ = v;
        for ( unsigned int i = 0; i < lines.size(); ++i )
        {
            vector< ObjId > elist;
            vector< double > val;
            buildElist( e, lines[i], elist, val );
            installSpines( elist, val, lines[i] );
        }
    }
}
References buildElist(), installSpines(), parseDistrib(), and spineDistribution_.
Referenced by initCinfo().
setTheta()
void Neuron::setTheta (double v)
Definition at line 881 of file Neuron.cpp.
{
    theta_ = v;
    // Do stuff here for rotating it.
}
References theta_.
Referenced by initCinfo().
spineIds()
const vector< Id > & Neuron::spineIds (unsigned int index) const
Definition at line 2114 of file Neuron.cpp.
{
    static vector< Id > fail;
    if ( index < spines_.size() )
        return spines_[index];
    return fail;
}
References spines_.
Referenced by Spine::getHead(), Spine::getHeadDiameter(), Spine::getHeadLength(), Spine::getShaft(), Spine::getShaftDiameter(), Spine::getShaftLength(), Spine::setHeadDiameter(), Spine::setHeadLength(), Spine::setHeadVolume(), Spine::setShaftDiameter(), and Spine::setShaftLength().
updateSegmentLengths()
void Neuron::updateSegmentLengths ()
Definition at line 1379 of file Neuron.cpp.
{
    double len = Field< double >::get( soma_, "length" );
    double dia = Field< double >::get( soma_, "diameter" );
    if ( len < dia )
        len = dia;
    double Rm = Field< double >::get( soma_, "Rm" );
    double Ra = Field< double >::get( soma_, "Ra" );
    double L = sqrt( Ra / Rm );
    for ( unsigned int i = 0; i < segs_.size(); ++i )
    {
        segs_[i].setGeometricalDistanceFromSoma( segs_[0] );
    }
    traverseCumulativeDistance( segs_[0], segs_, segId_, len, L, 0, 0 );
    maxL_ = maxG_ = maxP_ = 0.0;
    for ( unsigned int i = 0; i < segs_.size(); ++i )
    {
        double p = segs_[i].getPathDistFromSoma();
        if ( maxP_ < p ) maxP_ = p;
        double g = segs_[i].getGeomDistFromSoma();
        if ( maxG_ < g ) maxG_ = g;
        double L = segs_[i].getElecDistFromSoma();
        if ( maxL_ < L ) maxL_ = L;
    }
}
References Field< A >::get(), SwcSegment::getElecDistFromSoma(), SwcSegment::getGeomDistFromSoma(), SwcSegment::getPathDistFromSoma(), maxG_, maxL_, maxP_, segId_, segs_, SwcSegment::setGeometricalDistanceFromSoma(), soma_, and traverseCumulativeDistance().
Referenced by buildSegmentTree().
Member Data Documentation
allSpinesPerCompt_
vector< vector< Id > > Neuron::allSpinesPerCompt_ private
Id of each compt in each spine.
Ids of all spines on each compt, looked up by segIndex of compt.
Definition at line 135 of file Neuron.h.
Referenced by buildSegmentTree(), getParentCompartmentOfSpine(), getSpinesOnCompartment(), and installSpines().
branches_
vector< SwcBranch > Neuron::branches_ private
Definition at line 156 of file Neuron.h.
Referenced by getNumBranches().
channelDistribution_
vector< string > Neuron::channelDistribution_ private
Definition at line 124 of file Neuron.h.
Referenced by getChannelDistribution(), Neuron(), and setChannelDistribution().
CM_
double Neuron::CM_ private
Definition at line 114 of file Neuron.h.
Referenced by getCM(), Neuron(), Neuron(), and setCM().
compartmentLengthInLambdas_
double Neuron::compartmentLengthInLambdas_ private
Definition at line 123 of file Neuron.h.
Referenced by getCompartmentLengthInLambdas(), Neuron(), Neuron(), and setCompartmentLengthInLambdas().
Em_
double Neuron::Em_ private
Definition at line 115 of file Neuron.h.
Referenced by getEm(), Neuron(), Neuron(), and setEm().
headDsolve_
Id Neuron::headDsolve_ private
Definition at line 144 of file Neuron.h.
Referenced by scaleHeadDiffusion(), scaleShaftDiffusion(), and setSpineAndPsdDsolve().
maxG_
double Neuron::maxG_ private
Definition at line 119 of file Neuron.h.
Referenced by evalExprForElist(), Neuron(), Neuron(), and updateSegmentLengths().
maxL_
double Neuron::maxL_ private
Definition at line 120 of file Neuron.h.
Referenced by evalExprForElist(), Neuron(), Neuron(), and updateSegmentLengths().
maxP_
double Neuron::maxP_ private
Definition at line 118 of file Neuron.h.
Referenced by evalExprForElist(), Neuron(), Neuron(), and updateSegmentLengths().
passiveDistribution_
vector< string > Neuron::passiveDistribution_ private
Definition at line 125 of file Neuron.h.
Referenced by getPassiveDistribution(), Neuron(), and setPassiveDistribution().
phi_
double Neuron::phi_ private
Definition at line 117 of file Neuron.h.
Referenced by getPhi(), Neuron(), Neuron(), and setPhi().
psdDsolve_
Id Neuron::psdDsolve_ private
Id of the Dsolve for the head compt.
Definition at line 145 of file Neuron.h.
Referenced by scaleHeadDiffusion(), and setSpineAndPsdDsolve().
psdStoich_
vector< Id > Neuron::psdStoich_ private
Id of stoich associated with each PSD. Typically all the same.
Definition at line 140 of file Neuron.h.
Referenced by installSpines(), scaleBufAndRates(), and setSpineAndPsdMesh().
RA_
double Neuron::RA_ private
Definition at line 113 of file Neuron.h.
Referenced by getRA(), Neuron(), Neuron(), and setRA().
RM_
double Neuron::RM_ private
Definition at line 112 of file Neuron.h.
Referenced by getRM(), Neuron(), Neuron(), and setRM().
segId_
vector< Id > Neuron::segId_ private
Definition at line 154 of file Neuron.h.
Referenced by buildSegmentTree(), getCompartments(), getNumCompartments(), getParentCompartmentOfSpine(), installSpines(), and updateSegmentLengths().
segIndex_
map< Id, unsigned int > Neuron::segIndex_ private
Map to look up Seg index from Id of associated compt.
Definition at line 129 of file Neuron.h.
Referenced by buildSegmentTree(), evalExprForElist(), getSpinesOnCompartment(), and makeSpacingDistrib().
segs_
vector< SwcSegment > Neuron::segs_ private
Id of compartment in each Seg entry, below.
Definition at line 155 of file Neuron.h.
Referenced by buildSegmentTree(), evalExprForElist(), getElecDistFromSoma(), getGeomDistFromSoma(), getPathDistFromSoma(), makeSpacingDistrib(), and updateSegmentLengths().
soma_
Id Neuron::soma_ private
Definition at line 121 of file Neuron.h.
Referenced by buildSegmentTree(), evalExprForElist(), installSpines(), and updateSegmentLengths().
sourceFile_
string Neuron::sourceFile_ private
Definition at line 122 of file Neuron.h.
Referenced by getSourceFile(), Neuron(), Neuron(), and setSourceFile().
spineDistribution_
vector< string > Neuron::spineDistribution_ private
Definition at line 126 of file Neuron.h.
Referenced by getSpineDistribution(), Neuron(), and setSpineDistribution().
spineEntry_
Spine Neuron::spineEntry_ private
Id of the Dsolve for the PSD compt.
Holder for spine operations. Contains pointer to current Neuron.
Definition at line 152 of file Neuron.h.
Referenced by lookupSpine(), Neuron(), and Neuron().
spineParentSegIndex_
vector< unsigned int > Neuron::spineParentSegIndex_ private
Look up seg index of parent compartment, from index of spine.
Definition at line 131 of file Neuron.h.
spines_
vector< vector< Id > > Neuron::spines_ private
Definition at line 132 of file Neuron.h.
Referenced by getNumSpines(), getSpineFromCompartment(), installSpines(), setSpineAndPsdMesh(), and spineIds().
spineStoich_
vector< Id > Neuron::spineStoich_ private
Id of stoich associated with each spine. Typically all the same.
Definition at line 138 of file Neuron.h.
Referenced by installSpines(), scaleBufAndRates(), and setSpineAndPsdMesh().
spineToMeshOrdering_
vector< unsigned int > Neuron::spineToMeshOrdering_ private
looks up spine/psd mesh index from FieldIndex of selected spine.
Definition at line 142 of file Neuron.h.
Referenced by installSpines(), scaleBufAndRates(), scaleHeadDiffusion(), scaleShaftDiffusion(), and setSpineAndPsdMesh().
theta_
double Neuron::theta_ private
Definition at line 116 of file Neuron.h.
Referenced by getTheta(), Neuron(), Neuron(), and setTheta().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/biophysics/Neuron.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/biophysics/Neuron.cpp