MOOSE - Multiscale Object Oriented Simulation Environment: HSolveUtils Class Reference
HSolveUtils Class Reference
#include <HSolveUtils.h>
Classes
class Grid
Static Public Member Functions
static int adjacent (Id compartment, Id exclude, vector< Id > &ret)
static int adjacent (Id compartment, vector< Id > &ret)
static int caDepend (Id channel, vector< Id > &ret)
static int caTarget (Id channel, vector< Id > &ret)
static int channels (Id compartment, vector< Id > &ret)
static int children (Id compartment, vector< Id > &ret)
static int gates (Id channel, vector< Id > &ret, bool getOriginals=true)
static int hhchannels (Id compartment, vector< Id > &ret)
static void initialize (Id object)
static int leakageChannels (Id compartment, vector< Id > &ret)
static void rates (Id gate, Grid grid, vector< double > &A, vector< double > &B)
static int spikegens (Id compartment, vector< Id > &ret)
static int synchans (Id compartment, vector< Id > &ret)
static int targets (Id object, string msg, vector< Id > &target, const vector< string > &filter, bool include=true)
static int targets (Id object, string msg, vector< Id > &target, string filter="", bool include=true)
Detailed Description
Definition at line 26 of file HSolveUtils.h.
Member Function Documentation
adjacent() [1/2]
int HSolveUtils::adjacent (Id compartment, Id exclude, vector< Id > & ret) static
Definition at line 25 of file HSolveUtils.cpp.
{
    int size = ret.size();
    adjacent( compartment, ret );
    ret.erase(
        remove( ret.begin(), ret.end(), exclude ),
        ret.end()
    );
    return ret.size() - size;
}
References adjacent().
Referenced by HSolvePassive::walkTree().
adjacent() [2/2]
int HSolveUtils::adjacent (Id compartment, vector< Id > & ret) static
Definition at line 36 of file HSolveUtils.cpp.
{
    int size = 0;
    size += targets( compartment, "axial", ret, "Compartment" );
    size += targets( compartment, "raxial", ret, "Compartment" );
    size += targets( compartment, "distalOut", ret, "SymCompartment" );
    size += targets( compartment, "proximalOut", ret, "SymCompartment" );
    size += targets( compartment, "cylinderOut", ret, "SymCompartment" );
    return size;
}
References targets().
Referenced by adjacent(), and HSolvePassive::walkTree().
caDepend()
int HSolveUtils::caDepend (Id channel, vector< Id > & ret) static
Definition at line 144 of file HSolveUtils.cpp.
{
    return targets( channel, "concen", ret, "CaConc" );
}
References targets().
Referenced by HSolveActive::readCalcium().
caTarget()
int HSolveUtils::caTarget (Id channel, vector< Id > & ret) static
Definition at line 139 of file HSolveUtils.cpp.
{
    return targets( channel, "IkOut", ret, "CaConc" );
}
References targets().
Referenced by HSolveActive::readCalcium().
channels()
int HSolveUtils::channels (Id compartment, vector< Id > & ret) static
Gives all channels (hhchannels, synchans, any other) attached to a given compartment.
Definition at line 59 of file HSolveUtils.cpp.
{
    return targets( compartment, "channel", ret );
}
References targets().
children()
int HSolveUtils::children (Id compartment, vector< Id > & ret) static
Definition at line 47 of file HSolveUtils.cpp.
{
    int size = targets( compartment, "axial", ret, "Compartment" );
    size += targets( compartment, "distalOut", ret, "SymCompartment" );
    size += targets( compartment, "cylinderOut", ret, "SymCompartment" );
    return size;
}
References targets().
Referenced by HSolvePassive::storeTree().
gates()
int HSolveUtils::gates (Id channel, vector< Id > & ret, bool getOriginals = true) static
The 'getOriginals' flag requests Id:s of the prototype gates from which copies were created, instead of Id:s of the copied gates. Default is true.
Definition at line 75 of file HSolveUtils.cpp.
{
//        dump("HSolveUtils::gates() is not tested with new hsolve api", "FIXME");
    unsigned int oldSize = ret.size();
    static string gateName[] = {
        string( "gateX[0]" ),
        string( "gateY[0]" ),
        string( "gateZ[0]" )
    };
    static string powerField[] = {
        string( "Xpower" ),
        string( "Ypower" ),
        string( "Zpower" )
    };
        unsigned int nGates = 3; // Number of possible gates
        for ( unsigned int i = 0; i < nGates; i++ ) {
            double power  = Field< double >::get ( channel, powerField[i] );
            if ( power > 0.0 ) {
                // string gatePath = moose::joinPath(channel.path(), gateName[i]);
                string gatePath = moose::fixPath( channel.path() ) +
                        "/" +  gateName[i];
                Id gate( gatePath );
                string gPath = moose::fixPath(gate.path());
                errorSS.str("");
                errorSS << "Got " << gatePath << " expected " << gPath;
                SIMPLE_ASSERT_MSG(gPath == gatePath, errorSS.str().c_str());
                if ( getOriginals ) {
                    HHGate* g = reinterpret_cast< HHGate* >( gate.eref().data() );
                    gate = g->originalGateId();
                }
                ret.push_back( gate );
            }
        }
        return ret.size() - oldSize;
}
References Eref::data(), Id::eref(), errorSS, moose::fixPath(), Field< A >::get(), Id::Id(), HHGateBase::originalGateId(), and Id::path().
Referenced by HSolveActive::readGates().
hhchannels()
int HSolveUtils::hhchannels (Id compartment, vector< Id > & ret) static
Definition at line 64 of file HSolveUtils.cpp.
{
    // Request for elements of type "HHChannel" only since
    // channel messages can lead to synchans as well.
    return targets( compartment, "channel", ret, "HHChannel" );
}
References targets().
Referenced by HSolveActive::readHHChannels().
initialize()
void HSolveUtils::initialize (Id object) static
Definition at line 12 of file HSolveUtils.cpp.
{
    //~ ProcInfoBase p;
    //~ SetConn c( object(), 0 );
    //~
    //~ if ( object()->className() == "Compartment" )
        //~ moose::Compartment::reinitFunc( &c, &p );
    //~ else if ( object()->className() == "HHChannel" )
        //~ HHChannel::reinitFunc( &c, &p );
    //~ else if ( object()->className() == "CaConc" )
        //~ CaConc::reinitFunc( &c, &p );
}
leakageChannels()
int HSolveUtils::leakageChannels (Id compartment, vector< Id > & ret) static
Definition at line 134 of file HSolveUtils.cpp.
{
    return targets( compartment, "channel", ret, "Leakage" );
}
References targets().
Referenced by HSolvePassive::initialize().
rates()
void HSolveUtils::rates (Id gate, HSolveUtils::Grid grid, vector< double > & A, vector< double > & B) static
Definition at line 205 of file HSolveUtils.cpp.
{
    // dump("HSolveUtils::rates() has not been tested yet.", "WARN");
    double min = Field< double >::get( gateId, "min" );
    double max = Field< double >::get( gateId, "max" );
    unsigned int divs = Field< unsigned int >::get( gateId, "divs" );
    if ( grid == Grid( min, max, divs ) ) {
        A = Field< vector< double > >::get( gateId, "tableA" );
        B = Field< vector< double > >::get( gateId, "tableB" );
        return;
    }
    A.resize( grid.size() );
    B.resize( grid.size() );
    /*
     * Getting Id of original (prototype) gate, so that we can set fields on
     * it. Copied gates are read-only.
     */
    HHGate* gate = reinterpret_cast< HHGate* >( gateId.eref().data() );
    gateId = gate->originalGateId();
    /*
     * Setting interpolation flag on. Will set back to its original value once
     * we're done.
     */
    bool useInterpolation = Field< bool >::get( gateId, "useInterpolation");
    gate->setUseInterpolation( gateId.eref(), true );
    unsigned int igrid;
    double* ia = &A[ 0 ];
    double* ib = &B[ 0 ];
    for ( igrid = 0; igrid < grid.size(); ++igrid ) {
        gate->lookupBoth( grid.entry( igrid ), ia, ib );
        ++ia, ++ib;
    }
    // Setting interpolation flag back to its original value.
    //~ HSolveUtils::set< HHGate, bool >
    //~ ( gateId, "useInterpolation", useInterpolation );
    gate->setUseInterpolation( gateId.eref(), useInterpolation );
}
References Eref::data(), HSolveUtils::Grid::entry(), Id::eref(), Field< A >::get(), HSolveUtils::Grid::Grid(), HHGate::lookupBoth(), HSolveUtils::Grid::operator==(), HHGateBase::originalGateId(), HHGate::setUseInterpolation(), and HSolveUtils::Grid::size().
Referenced by HSolveActive::createLookupTables().
spikegens()
int HSolveUtils::spikegens (Id compartment, vector< Id > & ret) static
Definition at line 122 of file HSolveUtils.cpp.
{
    return targets( compartment, "VmOut", ret, "SpikeGen" );
}
References targets().
Referenced by HSolveActive::readSynapses().
synchans()
int HSolveUtils::synchans (Id compartment, vector< Id > & ret) static
Definition at line 127 of file HSolveUtils.cpp.
{
    // "channel" msgs lead to SynChans as well HHChannels, so request
    // explicitly for former.
    return targets( compartment, "channel", ret, "SynChan" );
}
References targets().
Referenced by HSolveActive::readSynapses().
targets() [1/2]
int HSolveUtils::targets (Id object, string msg, vector< Id > & target, const vector< string > & filter, bool include = true) static
Appends to 'target' any destination objects of messages of the specified name found on the object. The filter restricts the returns to those objects of the specified class include is a flag, when false it flips the returns to objects not of the specified class.
Definition at line 303 of file HSolveUtils.cpp.
{
    unsigned int oldSize = target.size();
    vector< Id > all;
    Element* e = object.element();
    const Finfo* f = e->cinfo()->findFinfo( msg );
    if ( !f ) // Might not find SymCompartment Finfos if it is a Compartment
        return 0;
    e->getNeighbors( all, f );
    vector< Id >::iterator ia;
    if ( filter.empty() ) {
        target.insert( target.end(), all.begin(), all.end() );
    } else {
        for ( ia = all.begin(); ia != all.end(); ++ia ) {
            string className = (*ia).element()->cinfo()->name();
            bool hit =
                find(
                    filter.begin(),
                    filter.end(),
                    className
                ) != filter.end();
            if ( ( hit && include ) || ( !hit && !include ) )
                target.push_back( *ia );
        }
    }
    return target.size() - oldSize;
}
References Element::cinfo(), Id::element(), Cinfo::findFinfo(), Element::getNeighbors(), and Cinfo::name().
Referenced by HSolveActive::manageOutgoingMessages(), and targets().
targets() [2/2]
int HSolveUtils::targets (Id object, string msg, vector< Id > & target, string filter = "", bool include = true) static
Definition at line 281 of file HSolveUtils.cpp.
{
    vector< string > filter_v;
    if ( filter != "" )
        filter_v.push_back( filter );
    return targets( object, msg, target, filter_v, include );
}
References targets().
Referenced by adjacent(), caDepend(), caTarget(), channels(), children(), hhchannels(), leakageChannels(), spikegens(), and synchans().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/hsolve/HSolveUtils.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/hsolve/HSolveUtils.cpp