MOOSE - Multiscale Object Oriented Simulation Environment: ReadKkit Class Reference
ReadKkit Class Reference
#include <ReadKkit.h>
Public Types
enum ParseMode { DATA , INIT , COMMENT , LINE_CONTINUE }
Public Member Functions
void addmsg (const vector< string > &args)
void assignEnzCompartments ()
void assignMMenzCompartments ()
void assignPoolCompartments ()
void assignReacCompartments ()
Id buildChan (const vector< string > &args)
Id buildCompartment (const vector< string > &args)
Id buildEnz (const vector< string > &args)
Id buildGeometry (const vector< string > &args)
Id buildGraph (const vector< string > &args)
Id buildGroup (const vector< string > &args)
Id buildInfo (Id parent, map< string, int > &m, const vector< string > &args)
Id buildPlot (const vector< string > &args)
Id buildPool (const vector< string > &args)
Id buildReac (const vector< string > &args)
Id buildStim (const vector< string > &args)
void buildSumTotal (const string &src, const string &dest)
Id buildTable (const vector< string > &args)
Id buildText (const vector< string > &args)
void call (const vector< string > &args)
double childPoolVol (Id gid) const
string cleanPath (const string &path) const
void convertEnzRatesToConcUnits ()
Id convertKineticsToGroup (Id mgr)
If kinetics has no reacs, we convert it into a group.
void convertMMenzRatesToConcUnits ()
void convertParametersToConcUnits ()
void convertPoolAmountToConcUnits ()
Convert pool amounts. Initially given in n, but scaling issue.
void convertReacRatesToConcUnits ()
Convert Reac rates, initially in n units.
void dumpPlots (const string &filename)
int findCompartmentsFromAnnotation ()
Id findSumTotSrc (const string &src)
string getBasePath () const
double getDefaultVol () const
double getMaxTime () const
bool getMoveOntoCompartment () const
double getPlotDt () const
unsigned int getVersion () const
void innerAddMsg (const string &src, const map< string, Id > &m1, const string &srcMsg, const string &dest, const map< string, Id > &m2, const string &destMsg, bool isBackward=0)
void innerRead (ifstream &fin)
unsigned int loadTab (const vector< string > &args)
void objdump (const vector< string > &args)
string pathTail (const string &path, string &head) const
Id read (const string &filename, const string &cellname, Id parent, const string &solverClass="Stoich")
void readData (const string &line)
ParseMode readInit (const string &line)
ReadKkit ()
void run ()
void separateVols (Id pool, double vol)
void setMoveOntoCompartment (bool v)
void setupSlaveMsg (const string &src, const string &dest)
void textload (const vector< string > &args)
void undump (const vector< string > &args)
Private Attributes
Id baseId_
Base path into which entire kkit model will go.
string basePath_
map< string, Id > chanIds_
map< string, int > chanMap_
vector< Id > compartments_
double controldt_
regular numerical timestep from kkit.
double defaultVol_
Use both fast and sim dts.
vector< pair< Id, Id > > enzCplxMols_
map< string, Id > enzIds_
map< string, int > enzMap_
double fastdt_
Base Id onto which entire kkit model will go.
map< string, int > groupMap_
vector< string > groupPaths_
unsigned int initdumpVersion_
KKit version.
Id lastTab_
This keeps track of the last Table used in loadtab.
unsigned int lineNum_
double maxtime_
Timestep for updating plots.
map< string, Id > mmEnzIds_
bool moveOntoCompartment_
Initdump too has a version.
unsigned int numCompartments_
unsigned int numEnz_
unsigned int numMMenz_
unsigned int numOthers_
unsigned int numPlot_
unsigned int numPools_
unsigned int numReacs_
unsigned int numStim_
double plotdt_
Timestep for updating control graphics.
map< string, Id > plotIds_
map< Id, int > poolFlags_
map< string, Id > poolIds_
map< string, int > poolMap_
map< Id, double > poolVols_
map< string, Id > reacIds_
map< string, int > reacMap_
Shell * shell_
double simdt_
fast numerical timestep from kkit.
map< string, Id > stimIds_
map< string, int > stimMap_
vector< double > tabEntries_
This holds the vector of array entries for loadtab.
map< string, Id > tabIds_
map< string, int > tableMap_
double transientTime_
Simulation run time.
bool useVariableDt_
Time to run model at fastdt.
unsigned int version_
Default volume for new compartments.
vector< vector< Id > > volCategories_
List of Ids in each unique volume.
vector< double > vols_
This keeps track of unique volumes.
Static Private Attributes
static const double EPSILON = 1.0e-15
Detailed Description
Loads in a kkit.g model. It makes a separate compartment for each distinct volume it finds in the system. The largest volume gets set to /model/kinetics. The next volume is in /model/compartment_1. The next volume is in /model/compartment_2. And so on. Has two options for handling compartments and solvers. By default, it puts the entire reaction system on /kinetics and makes just one solver. If the moveOntoCompartments_ flag is set it will put each model entity onto the appropriate compartment. It will create separate solvers for each compartment.
Definition at line 28 of file ReadKkit.h.
Member Enumeration Documentation
ParseMode
enum ReadKkit::ParseMode
Enumerator
DATA
INIT
COMMENT
LINE_CONTINUE
Definition at line 31 of file ReadKkit.h.
    {
        DATA,
        INIT,
        COMMENT,
        LINE_CONTINUE
    };
Constructor & Destructor Documentation
ReadKkit()
ReadKkit::ReadKkit ()
Definition at line 52 of file ReadKkit.cpp.
    :
    basePath_( "" ),
    baseId_(),
    fastdt_( 0.001 ),
    simdt_( 0.01 ),
    controldt_( 0.1 ),
    plotdt_( 1 ),
    maxtime_( 1.0 ),
    transientTime_( 1.0 ),
    useVariableDt_( 0 ),
    defaultVol_( 1 ),
    version_( 11 ),
    initdumpVersion_( 3 ),
    moveOntoCompartment_( true ),
    numCompartments_( 0 ),
    numPools_( 0 ),
    numReacs_( 0 ),
    numEnz_( 0 ),
    numMMenz_( 0 ),
    numPlot_( 0 ),
    numStim_( 0 ),
    numOthers_( 0 ),
    lineNum_( 0 ),
    shell_( reinterpret_cast< Shell* >( Id().eref().data() ) )
{
    ;
}
References baseId_, basePath_, controldt_, Eref::data(), defaultVol_, Id::eref(), fastdt_, Id::Id(), initdumpVersion_, lineNum_, maxtime_, moveOntoCompartment_, numCompartments_, numEnz_, numMMenz_, numOthers_, numPlot_, numPools_, numReacs_, numStim_, plotdt_, shell_, simdt_, transientTime_, useVariableDt_, and version_.
Member Function Documentation
addmsg()
void ReadKkit::addmsg (const vector< string > & args)
Definition at line 1516 of file ReadKkit.cpp.
{
    string src = cleanPath( args[1] ).substr( 10 );
    string dest = cleanPath( args[2] ).substr( 10 );
    if ( args[3] == "REAC" )
    {
        if ( args[4] == "A" && args[5] == "B" )
        {
            if ( chanIds_.find( src ) != chanIds_.end() )
                innerAddMsg( src, chanIds_, "in", dest, poolIds_, "reac");
            else
                innerAddMsg( src, reacIds_, "sub", dest, poolIds_, "reac");
        }
        else if ( args[4] == "B" && args[5] == "A" )
        {
            if ( chanIds_.find( src ) != chanIds_.end() )
                innerAddMsg( src, chanIds_, "out", dest, poolIds_, "reac");
            else
                // dest pool is product of src reac
                innerAddMsg( src, reacIds_, "prd", dest, poolIds_, "reac");
        }
        else if ( args[4] == "sA" && args[5] == "B" )
        {
            // Msg from enzyme to substrate.
            if ( mmEnzIds_.find( src ) == mmEnzIds_.end() )
                innerAddMsg( src, enzIds_, "sub", dest, poolIds_, "reac" );
            else
                innerAddMsg( src, mmEnzIds_, "sub", dest, poolIds_, "reac" );
        }
    }
    else if ( args[3] == "ENZYME" )   // Msg from enz pool to enz site
    {
        if ( mmEnzIds_.find( dest ) == mmEnzIds_.end() )
            innerAddMsg( dest, enzIds_, "enz", src, poolIds_, "reac" );
        else
            innerAddMsg( src, poolIds_, "nOut", dest, mmEnzIds_, "enzDest", 1);
        // innerAddMsg( dest, mmEnzIds_, "enz", src, poolIds_, "nOut", 1);
        /*
        if ( mmEnzIds_.find( dest ) == mmEnzIds_.end() )
            innerAddMsg( src, poolIds_, "reac", dest, enzIds_, "enz" );
        else
            innerAddMsg( src, poolIds_, "nOut", dest, mmEnzIds_, "enz" );
            */
    }
    else if ( args[3] == "MM_PRD" )   // Msg from enz to Prd pool
    {
        if ( mmEnzIds_.find( src ) == mmEnzIds_.end() )
            innerAddMsg( src, enzIds_, "prd", dest, poolIds_, "reac" );
        else
            innerAddMsg( src, mmEnzIds_, "prd", dest, poolIds_, "reac" );
    }
    else if ( args[3] == "NUMCHAN" )   // Msg from chan pool to concchan
    {
        if ( chanIds_.find( dest ) != chanIds_.end() )
            innerAddMsg( src, poolIds_, "nOut", dest, chanIds_, "setNumChan");
    }
    else if ( args[3] == "PLOT" )   // Time-course output for pool
    {
        string head;
        string temp;
        dest = pathTail( cleanPath( args[2] ), head );
        string graph = pathTail( head, temp );
        temp = graph + "/" + dest;
        map< string, Id >::const_iterator i = plotIds_.find( temp );
        assert( i != plotIds_.end() );
        Id plot = i->second;
        i = poolIds_.find( src );
        Id pool;
        if ( i == poolIds_.end() )
        {
            i = enzIds_.find( src ); // might be plotting an enzCplx.
            if ( i == enzIds_.end() )
            {
                cout << "Error: ReadKkit: Unable to find src for plot: " <<
                     src << ", " << dest << endl;
                assert( 0 );
                return;
            }
            vector< Id > enzcplx;
            i->second.element()->getNeighbors( enzcplx,
                                               i->second.element()->cinfo()->findFinfo( "cplxOut" ) );
            assert( enzcplx.size() == 1 );
            pool = enzcplx[0];
        }
        else
        {
            pool = i->second;
        }
        if ( args[4] == "Co" || args[4] == "CoComplex" )
        {
            ObjId ret = shell_->doAddMsg( "Single",
                                          plot, "requestOut", pool, "getConc" );
            assert( ret != ObjId() );
        }
        else if ( args[4] == "n" || args[4] == "nComplex")
        {
            ObjId ret = shell_->doAddMsg( "Single",
                                          plot, "requestOut", pool, "getN" );
            assert( ret != ObjId() );
        }
        else
        {
            cout << "Unknown PLOT msg field '" << args[4] << "'\n";
        }
    }
    else if ( args[3] == "SUMTOTAL" )   // Summation function.
    {
        buildSumTotal( src, dest );
    }
    else if ( args[3] == "SLAVE" )   // Summation function.
    {
        if ( args[4] == "output" )
        {
            setupSlaveMsg( src, dest );
        }
    }
}
References buildSumTotal(), chanIds_, Element::cinfo(), cleanPath(), Shell::doAddMsg(), Id::element(), enzIds_, Cinfo::findFinfo(), Element::getNeighbors(), innerAddMsg(), mmEnzIds_, ObjId::ObjId(), ObjId::operator!=(), pathTail(), plotIds_, poolIds_, reacIds_, setupSlaveMsg(), and shell_.
Referenced by readData().
assignEnzCompartments()
void ReadKkit::assignEnzCompartments ()
Goes through all Enzs and connects them up to each of the compartments in which one or more of their reactants resides. Thus, if any of these compartments changes volume, the Enz will be informed.
Definition at line 983 of file ReadKkit.cpp.
{
    /*
    Should not be needed, because the parent pool will move.
    for ( map< string, Id >::iterator i = enzIds_.begin();
    i != enzIds_.end(); ++i ) {
    Id compt = getCompt( Neutral::parent( i->second ).id );
    if ( moveOntoCompartment_ ) {
        if ( ! (getCompt( i->second ).id == compt ) )
            shell_->doMove( i->second, compt );
    }
    }
    */
}
Referenced by read().
assignMMenzCompartments()
void ReadKkit::assignMMenzCompartments ()
Goes through all MMenzs and connects them up to each of the compartments in which one or more of their reactants resides. Thus, if any of these compartments changes volume, the MMenz will be informed.
Definition at line 1004 of file ReadKkit.cpp.
{
    /*
    Should not be needed, because the parent pool will move.
    for ( map< string, Id >::iterator i = mmEnzIds_.begin();
    i != mmEnzIds_.end(); ++i ) {
    Id compt = getCompt( Neutral::parent( i->second ).id );
    if ( moveOntoCompartment_ ) {
        if ( ! (getCompt( i->second ).id == compt ) )
            shell_->doMove( i->second, compt );
    }
    }
    */
}
Referenced by read().
assignPoolCompartments()
void ReadKkit::assignPoolCompartments ()
Definition at line 881 of file ReadKkit.cpp.
{
    Id kinId = Neutral::child( baseId_.eref(), "kinetics" );
    assert( kinId != Id() );
    vector< unsigned int > volOrder = findVolOrder( vols_ );
    assert( volCategories_.size() == vols_.size() );
    assert( volCategories_.size() == volOrder.size() );
    for ( unsigned int j = 0 ; j < volOrder.size(); ++j )
    {
        unsigned int i = volOrder[j];
        if ( vols_[i] < 0 ) // Special case for enz complexes: vol == -1.
            continue;
        string name;
        Id comptId;
        // if ( i == maxi )
        if ( j == 0 )
        {
            comptId = kinId;
        }
        else
        {
            stringstream ss;
            ss << "compartment_" << j;
            name = ss.str();
            comptId = Neutral::child( baseId_.eref(), name );
            if ( comptId == Id() )
                comptId = shell_->doCreate( "CubeMesh", baseId_, name, 1 );
        }
        SetGet1< double >::set( comptId, "setVolumeNotRates",vols_[i]);
        compartments_.push_back( comptId );
        for ( vector< Id >::iterator k = volCategories_[i].begin();
                k != volCategories_[i].end(); ++k )
        {
            // if ( moveOntoCompartment_ ) {
            if ( ! (getCompt( *k ).id == comptId ) )
                shell_->doMove( *k, comptId );
            // }
        }
    }
}
References baseId_, Neutral::child(), compartments_, Shell::doCreate(), Shell::doMove(), Id::eref(), findVolOrder(), getCompt(), Id::Id(), ObjId::id, Id::operator!=(), Id::operator==(), SetGet1< A >::set(), shell_, volCategories_, and vols_.
Referenced by read().
assignReacCompartments()
void ReadKkit::assignReacCompartments ()
Goes through all Reacs and connects them up to each of the compartments in which one or more of their reactants resides. Thus, if any of these compartments changes volume, the Reac will be informed.
Definition at line 944 of file ReadKkit.cpp.
{
    for ( map< string, Id >::iterator i = reacIds_.begin();
            i != reacIds_.end(); ++i )
    {
        Id compt = findParentComptOfReac( i->second );
        if ( compt != Id() )
        {
            if ( ! (getCompt( i->second ).id == compt ) )
                shell_->doMove( i->second, compt );
        }
    }
}
References Shell::doMove(), findParentComptOfReac(), getCompt(), Id::Id(), ObjId::id, Id::operator!=(), Id::operator==(), reacIds_, and shell_.
Referenced by read().
buildChan()
Id ReadKkit::buildChan (const vector< string > & args)
Build a Kchan entry in simulation. For now a dummy Neutral.
Definition at line 1338 of file ReadKkit.cpp.
{
    string head;
    string clean = cleanPath( args[2] );
    string tail = pathTail( clean, head );
    Id pa = shell_->doFind( head ).id;
    assert( pa != Id() );
    // cout << "Warning: Kchan not yet supported in MOOSE, creating dummy:\n" << "  " << clean << "\n";
    //
    double permeability = atof( args[ chanMap_["perm"] ].c_str() );
    Id chan = shell_->doCreate( "ConcChan", pa, tail, 1 );
    // Convert from perm in uM in GENESIS, to mM for MOOSE.
    Field< double >::set( chan, "permeability", permeability *1000.0 );
    assert( chan != Id() );
    string chanPath = clean.substr( 10 );
    chanIds_[ chanPath ] = chan;
    Id info = buildInfo( chan, chanMap_, args );
    return chan;
}
References buildInfo(), chanIds_, chanMap_, cleanPath(), Shell::doCreate(), Shell::doFind(), Id::Id(), ObjId::id, Id::operator!=(), pathTail(), Field< A >::set(), and shell_.
Referenced by undump().
buildCompartment()
Id ReadKkit::buildCompartment (const vector< string > & args)
Definition at line 798 of file ReadKkit.cpp.
{
    Id compt;
    numCompartments_++;
    return compt;
}
References numCompartments_.
buildEnz()
Id ReadKkit::buildEnz (const vector< string > & args)
vsf is vol scale factor, which is what GENESIS stores in 'vol' field n = vsf * conc(uM) Also, n = (conc (uM) / 1e6) * NA * vol so, vol = 1e6 * vsf / NA
Definition at line 1019 of file ReadKkit.cpp.
{
    string head;
    string clean = cleanPath( args[2] );
    string tail = pathTail( clean, head );
    Id pa = shell_->doFind( head ).id;
    assert ( pa != Id() );
    double k1 = atof( args[ enzMap_[ "k1" ] ].c_str() );
    double k2 = atof( args[ enzMap_[ "k2" ] ].c_str() );
    double k3 = atof( args[ enzMap_[ "k3" ] ].c_str() );
    // double volscale = atof( args[ enzMap_[ "vol" ] ].c_str() );
    double nComplexInit =
        atof( args[ enzMap_[ "nComplexInit" ] ].c_str() );
    // double vol = atof( args[ enzMap_[ "vol" ] ].c_str());
    bool isMM = atoi( args[ enzMap_[ "usecomplex" ] ].c_str());
    assert( poolVols_.find( pa ) != poolVols_.end() );
    double vol = poolVols_[ pa ];
    if ( isMM )
    {
        Id enz = shell_->doCreate( "MMenz", pa, tail, 1 );
        assert( enz != Id () );
        string mmEnzPath = clean.substr( 10 );
        mmEnzIds_[ mmEnzPath ] = enz;
        assert( k1 > EPSILON );
        // double Km = ( k2 + k3 ) / k1;
        // double Km = ( k2 + k3 ) / (1e6 * k1 / (KKIT_NA * vol) );
        double Km = ( k2 + k3 ) / (k1 * KKIT_NA * vol);
        Field< double >::set( enz, "Km", Km );
        Field< double >::set( enz, "kcat", k3 );
        Id info = buildInfo( enz, enzMap_, args );
        numMMenz_++;
        return enz;
    }
    else
    {
        Id enz = shell_->doCreate( "Enz", pa, tail, 1 );
        // double parentVol = Field< double >::get( pa, "volume" );
        assert( enz != Id () );
        string enzPath = clean.substr( 10 );
        enzIds_[ enzPath ] = enz;
        // Need to figure out what to do about these. Perhaps it is OK
        // to do this assignments in raw #/cell units.
        Field< double >::set( enz, "k3", k3 );
        Field< double >::set( enz, "k2", k2 );
        // Here we explicitly calculate Km because the substrates are
        // not set up till later, and without them the volume calculations
        // are confused.
        double volScale = lookupVolumeFromMesh(pa.eref());
        double Km = (k2+k3)/(k1 * KKIT_NA * vol ); // Scaling for uM to mM.
        SetGet2< double, double >::set( enz, "setKmK1", Km, k1 );
        string cplxName = tail + "_cplx";
        string cplxPath = enzPath + "/" + cplxName;
        Id cplx = shell_->doCreate( "Pool", enz, cplxName, 1 );
        assert( cplx != Id () );
        poolIds_[ cplxPath ] = cplx;
        // Field< double >::set( cplx, "nInit", nComplexInit );
        Field< double >::set( cplx, "nInit", nComplexInit );
        // Use this later to assign mesh entries to enz cplx.
        enzCplxMols_.push_back( pair< Id, Id >(  pa, cplx ) );
        separateVols( cplx, -1 ); // -1 vol is a flag to defer mesh assignment for the cplx pool.
        ObjId ret = shell_->doAddMsg( "OneToAll",
                                      ObjId( enz, 0 ), "cplx",
                                      ObjId( cplx, 0 ), "reac" );
        assert( ret != ObjId() );
        // cplx()->showFields();
        // enz()->showFields();
        // pa()->showFields();
        Id info = buildInfo( enz, enzMap_, args );
        numEnz_++;
        return enz;
    }
}
References buildInfo(), cleanPath(), Shell::doAddMsg(), Shell::doCreate(), Shell::doFind(), enzCplxMols_, enzIds_, enzMap_, EPSILON, Id::eref(), Id::Id(), ObjId::id, KKIT_NA, lookupVolumeFromMesh(), mmEnzIds_, numEnz_, numMMenz_, ObjId::ObjId(), ObjId::ObjId(), Id::operator!=(), ObjId::operator!=(), pathTail(), poolIds_, poolVols_, separateVols(), Field< A >::set(), SetGet2< A1, A2 >::set(), and shell_.
Referenced by undump().
buildGeometry()
Id ReadKkit::buildGeometry (const vector< string > & args)
Definition at line 1360 of file ReadKkit.cpp.
{
    Id geometry;
    numOthers_++;
    return geometry;
}
References numOthers_.
Referenced by undump().
buildGraph()
Id ReadKkit::buildGraph (const vector< string > & args)
Definition at line 1367 of file ReadKkit.cpp.
{
    string head;
    string tail = pathTail( cleanPath( args[2] ), head );
    Id pa = shell_->doFind( head ).id;
    assert( pa != Id() );
    Id graph = shell_->doCreate( "Neutral", pa, tail, 1 );
    assert( graph != Id() );
    numOthers_++;
    return graph;
}
References cleanPath(), Shell::doCreate(), Shell::doFind(), Id::Id(), ObjId::id, numOthers_, Id::operator!=(), pathTail(), and shell_.
Referenced by undump().
buildGroup()
Id ReadKkit::buildGroup (const vector< string > & args)
Definition at line 1133 of file ReadKkit.cpp.
{
    string head;
    string tail = pathTail( cleanPath( args[2] ), head );
    Id pa = shell_->doFind( head ).id;
    assert( pa != Id() );
    Id group = shell_->doCreate( "Neutral", pa, tail, 1 );
    assert( group != Id() );
    Id info = buildInfo( group, groupMap_, args );
    groupPaths_.push_back( head + "/" + tail );
    numOthers_++;
    return group;
}
References buildInfo(), cleanPath(), Shell::doCreate(), Shell::doFind(), groupMap_, groupPaths_, Id::Id(), ObjId::id, numOthers_, Id::operator!=(), pathTail(), and shell_.
Referenced by undump().
buildInfo()
Id ReadKkit::buildInfo (Id parent, map< string, int > & m, const vector< string > & args)
Definition at line 1116 of file ReadKkit.cpp.
{
    Id info = shell_->doCreate( "Annotator", parent, "info", 1 );
    assert( info != Id() );
    double x = atof( args[ m[ "x" ] ].c_str() );
    double y = atof( args[ m[ "y" ] ].c_str() );
    Field< double >::set( info, "x", x );
    Field< double >::set( info, "y", y );
    Field< string >::set( info, "color", args[ m[ "xtree_fg_req" ] ] );
    Field< string >::set( info, "textColor",
                          args[ m[ "xtree_textfg_req" ] ] );
    return info;
}
References Shell::doCreate(), Id::Id(), Id::operator!=(), Field< A >::set(), and shell_.
Referenced by buildChan(), buildEnz(), buildGroup(), buildPool(), buildReac(), and buildTable().
buildPlot()
Id ReadKkit::buildPlot (const vector< string > & args)
Definition at line 1380 of file ReadKkit.cpp.
{
    string head;
    string tail = pathTail( cleanPath( args[2] ), head ); // Name of plot
    string temp;
    string graph = pathTail( head, temp ); // Name of graph
    Id pa = shell_->doFind( head ).id;
    assert( pa != Id() );
    Id plot = shell_->doCreate( "Table2", pa, tail, 1 );
    assert( plot != Id() );
    temp = graph + "/" + tail;
    plotIds_[ temp ] = plot;
    numPlot_++;
    return plot;
}
References cleanPath(), Shell::doCreate(), Shell::doFind(), Id::Id(), ObjId::id, numPlot_, Id::operator!=(), pathTail(), plotIds_, and shell_.
Referenced by undump().
buildPool()
Id ReadKkit::buildPool (const vector< string > & args)
There is a problem with this conversion, because of the discrepancy of the correct NA and the version (6e23) used in kkit. I take the concentration as authoritative, not the # of molecules. This is because I use conc units for the rates as well, and to use n for pools and conc for reactions will always introduce errors. This is still not a great solution, because, for example, simulations involving receptor traffic are originally framed in terms of number of receptors, not conc.
vsf is vol scale factor, which is what GENESIS stores in 'vol' field n = vsf * conc(uM) Also, n = (conc (uM) / 1e6) * NA * vol so, vol = 1e6 * vsf / NA
Definition at line 1157 of file ReadKkit.cpp.
{
    string head;
    string clean = cleanPath( args[2] );
    string tail = pathTail( clean, head );
    Id pa = shell_->doFind( head ).id;
    assert( pa != Id() );
    // double nInit = atof( args[ poolMap_[ "nInit" ] ].c_str() );
    double nInit = atof( args[ poolMap_[ "nInit" ] ].c_str() );
    // double concInit = atof( args[ poolMap_[ "CoInit" ] ].c_str() );
    double vsf = atof( args[ poolMap_[ "vol" ] ].c_str() );
    double concInit = nInit * KKIT_NA / (vsf * NA);
    double vol = 1.0e3 * vsf / KKIT_NA; // Converts volscale to actual vol in m^3
    int slaveEnable = atoi( args[ poolMap_[ "slave_enable" ] ].c_str() );
    double diffConst = atof( args[ poolMap_[ "DiffConst" ] ].c_str() );
    // I used -ve D as a flag to replace pool-specific D
    // with the global value of D. Here we just ignore it.
    if ( diffConst < 0 )
        diffConst = 0;
    Id pool;
    if ( slaveEnable == 0 )
    {
        pool = shell_->doCreate( "Pool", pa, tail, 1 );
    }
    else if ( slaveEnable & 4 )
    {
        pool = shell_->doCreate( "BufPool", pa, tail, 1 );
    }
    else
    {
        pool = shell_->doCreate( "Pool", pa, tail, 1 );
        /*
        cout << "ReadKkit::buildPool: Unknown slave_enable flag '" <<
            slaveEnable << "' on " << clean << "\n";
            */
        poolFlags_[pool] = slaveEnable;
    }
    assert( pool != Id() );
    // skip the 10 chars of "/kinetics/"
    poolIds_[ clean.substr( 10 ) ] = pool;
    // Field< double >::set( pool, "nInit", nInit );
    Field< double >::set( pool, "nInit", nInit );
    Field< double >::set( pool, "concInit", concInit / 1e3 ); // conv to mM
    Field< double >::set( pool, "diffConst", diffConst );
    // SetGet1< double >::set( pool, "setVolume", vol );
    separateVols( pool, vol );
    poolVols_[pool] = vol;
    Id info = buildInfo( pool, poolMap_, args );
    /*
    cout << setw( 20 ) << head << setw( 15 ) << tail << "   " <<
        setw( 12 ) << nInit << "    " <<
        vol << "    " << diffConst << " " <<
        slaveEnable << endl;
        */
    numPools_++;
    return pool;
}
References buildInfo(), cleanPath(), Shell::doCreate(), Shell::doFind(), Id::Id(), ObjId::id, KKIT_NA, NA, numPools_, Id::operator!=(), pathTail(), poolFlags_, poolIds_, poolMap_, poolVols_, separateVols(), Field< A >::set(), and shell_.
Referenced by undump().
buildReac()
Id ReadKkit::buildReac (const vector< string > & args)
Definition at line 805 of file ReadKkit.cpp.
{
    string head;
    string clean = cleanPath( args[2] );
    string tail = pathTail( clean, head );
    Id pa = shell_->doFind( head ).id;
    assert( pa != Id() );
    double kf = atof( args[ reacMap_[ "kf" ] ].c_str() );
    double kb = atof( args[ reacMap_[ "kb" ] ].c_str() );
    // We have a slight problem because MOOSE has a more precise value for
    // NA than does kkit. Here we assume that the conc units from Kkit are
    // meant to be OK, so they override the #/cell (lower case k) units.
    // So we convert all the Kfs and Kbs in the entire system after
    // the model has been created, once we know the order of each reac.
    Id reac = shell_->doCreate( "Reac", pa, tail, 1 );
    reacIds_[ clean.substr( 10 ) ] = reac;
    // Here is another hack: The native values stored in the reac are
    // Kf and Kb, in conc units. However the 'clean' values from kkit
    // are the number values numKf and numKb. In the
    // function convertReacRatesToNumUnits we take the numKf and numKb and
    // do proper conc scaling.
    Field< double >::set( reac, "Kf", kf );
    Field< double >::set( reac, "Kb", kb );
    Id info = buildInfo( reac, reacMap_, args );
    numReacs_++;
    return reac;
}
References buildInfo(), cleanPath(), Shell::doCreate(), Shell::doFind(), Id::Id(), ObjId::id, numReacs_, Id::operator!=(), pathTail(), reacIds_, reacMap_, Field< A >::set(), and shell_.
Referenced by undump().
buildStim()
Id ReadKkit::buildStim (const vector< string > & args)
Build a Stim entry in simulation, i.e., a PulseGen
Definition at line 1303 of file ReadKkit.cpp.
{
    string head;
    string clean = cleanPath( args[2] );
    string tail = pathTail( clean, head );
    Id pa = shell_->doFind( head ).id;
    assert( pa != Id() );
    double level1 = atof( args[ stimMap_[ "firstLevel" ] ].c_str() );
    double width1 = atof( args[ stimMap_[ "firstWidth" ] ].c_str() );
    double delay1 = atof( args[ stimMap_[ "firstDelay" ] ].c_str() );
    double level2 = atof( args[ stimMap_[ "secondLevel" ] ].c_str() );
    double width2 = atof( args[ stimMap_[ "secondWidth" ] ].c_str() );
    double delay2 = atof( args[ stimMap_[ "secondLevel" ] ].c_str() );
    double baselevel = atof( args[ stimMap_[ "baseLevel" ] ].c_str() );
    Id stim = shell_->doCreate( "PulseGen", pa, tail, 1 );
    assert( stim != Id() );
    string stimPath = clean.substr( 10 );
    stimIds_[ stimPath ] = stim;
    Field< double >::set( stim, "firstLevel", level1 );
    Field< double >::set( stim, "firstWidth", width1 );
    Field< double >::set( stim, "firstDelay", delay1 );
    Field< double >::set( stim, "secondLevel", level2 );
    Field< double >::set( stim, "secondWidth", width2 );
    Field< double >::set( stim, "secondDelay", delay2 );
    Field< double >::set( stim, "baseLevel", baselevel );
    numStim_++;
    return stim;
}
References cleanPath(), Shell::doCreate(), Shell::doFind(), Id::Id(), ObjId::id, numStim_, Id::operator!=(), pathTail(), Field< A >::set(), shell_, stimIds_, and stimMap_.
Referenced by undump().
buildSumTotal()
void ReadKkit::buildSumTotal (const string & src, const string & dest)
Definition at line 1253 of file ReadKkit.cpp.
{
    map<string, Id>::iterator i = poolIds_.find(dest);
    assert( i != poolIds_.end() );
    Id destId = i->second;
    Id sumId;
    // Check if the pool has not yet been converted to handle SumTots.
    if ( destId.element()->cinfo()->isA( "PoolBase" ) )
    {
        sumId = Neutral::child( destId.eref(), "func" );
        if ( sumId == Id() ) {
            sumId = shell_->doCreate( "Function", destId, "func", 1 );
            Field< bool >::set( sumId, "allowUnknownVariable", false );
            ObjId ret = shell_->doAddMsg( "single",
                                      ObjId( sumId, 0 ), "valueOut",
                                      ObjId( destId, 0 ), "setN" );
            assert( ret != ObjId() );
        }
    }
    if ( sumId == Id() )
    {
        cout << "Error: ReadKkit::buildSumTotal: could not make Function on '"
             << dest << "'\n";
        return;
    }
    Id srcId = findSumTotSrc( src );
    unsigned int numVars = Field< unsigned int >::get( sumId, "numVars" );
    stringstream ss;
    for ( unsigned int i = 0; i < numVars; ++i )
        ss << "x" << i << "+";
    ss << "x" << numVars;
    Field<string>::set(sumId, "expr", ss.str());
    ObjId xi(sumId.value()+1, 0, numVars );
    // Field<unsigned int>::set( sumId, "numVars", numVars+1);
    ObjId ret = shell_->doAddMsg( "single",
                                  ObjId( srcId, 0 ), "nOut",
                                  xi, "input" );
    assert( ret != ObjId() );
}
References Neutral::child(), Element::cinfo(), Shell::doAddMsg(), Shell::doCreate(), Id::element(), Id::eref(), findSumTotSrc(), Field< A >::get(), Id::Id(), Cinfo::isA(), ObjId::ObjId(), ObjId::ObjId(), ObjId::operator!=(), Id::operator==(), poolIds_, Field< A >::set(), shell_, and Id::value().
Referenced by addmsg().
buildTable()
Id ReadKkit::buildTable (const vector< string > & args)
Definition at line 1404 of file ReadKkit.cpp.
{
    string head;
    string clean = cleanPath( args[2] );
    string tail = pathTail( clean, head ); // Name of xtab
    Id pa = shell_->doFind( head ).id;
    assert( pa != Id() );
    Id tab;
    int mode = atoi( args[ tableMap_[ "step_mode" ] ].c_str() );
    if ( mode == TAB_IO )
    {
    }
    else if ( mode == TAB_LOOP || mode == TAB_ONCE )
    {
        tab = shell_->doCreate( "StimulusTable", pa, tail, 1 );
        assert( tab != Id() );
        double stepSize = atof( args[ tableMap_[ "stepsize" ] ].c_str() );
        Field< double >::set( tab, "stepSize", stepSize );
        if ( mode == TAB_LOOP )
            Field< bool >::set( tab, "doLoop", 1 );
        double input = atof( args[ tableMap_[ "input" ] ].c_str() );
        Field< double >::set( tab, "startTime", -input );
        // The other StimulusTable parameters will have to wait till the
        // loadTab is invoked.
    }
    string temp = clean.substr( 10 );
    tabIds_[ temp ] = tab;
    Id info = buildInfo( tab, tableMap_, args );
    return tab;
}
References buildInfo(), cleanPath(), Shell::doCreate(), Shell::doFind(), Id::Id(), ObjId::id, Id::operator!=(), pathTail(), Field< A >::set(), shell_, TAB_IO, TAB_LOOP, TAB_ONCE, tabIds_, and tableMap_.
Referenced by undump().
buildText()
Id ReadKkit::buildText (const vector< string > & args)
Definition at line 1109 of file ReadKkit.cpp.
{
    Id text;
    numOthers_++;
    return text;
}
References numOthers_.
Referenced by undump().
call()
void ReadKkit::call (const vector< string > & args)
call /kinetics/foo/notes LOAD notes_string_here
Definition at line 717 of file ReadKkit.cpp.
{
    if ( args.size() > 3 )
    {
        unsigned int len = args[1].length();
        if ( ( args[1].substr( len - 5 ) ==  "notes" ) &&
                args[2] == "LOAD" )
        {
            if ( args[3].length() == 0 )
                return;
            //HARSHA: Added CleanPath.
            string objName = cleanPath(args[1].substr( 0, len - 5 ));
            Id test(basePath_+objName);
            Id obj( basePath_ + objName + "info" );
            if ( obj != Id() )
            {
                string notes = "";
                string space = "";
                for ( unsigned int i = 3; i < args.size(); ++i )
                {
                    unsigned int innerLength = args[i].length();
                    if ( innerLength == 0 )
                        continue;
                    unsigned int start = 0;
                    unsigned int end = innerLength;
                    if ( args[i][0] == '\"' )
                        start = 1;
                    if ( args[i][innerLength - 1] == '\"' )
                        end = innerLength - 1 - start;
                    notes += space + args[i].substr( start, end );
                    space = " ";
                }
                Field< string >::set( obj, "notes", notes );
            }
        }
    }
}
References basePath_, cleanPath(), Id::Id(), Id::Id(), Id::operator!=(), and Field< A >::set().
Referenced by readData().
childPoolVol()
double ReadKkit::childPoolVol (Id gid) const
Returns volume of group based on volume of first pool found in it. Uses the pool's saved volume info rather than vol of parent mesh.
Definition at line 378 of file ReadKkit.cpp.
{
    vector< ObjId > pools;
    simpleWildcardFind( gid.path() + "/##[ISA=PoolBase]", pools );
    for ( unsigned int i = 0; i < pools.size(); i++ ) {
        auto pv = poolVols_.find( pools[i].id );
        if ( pv != poolVols_.end() )
            return pv->second;
    }
    cout << "Warning: of " << pools.size() << " children of group " << gid.path() << ", none found in map poolVols_ of size " << pools.size() << ".\n Using default vol of 1e-18\n";
    return 1e-18;
}
References ObjId::id, Id::path(), poolVols_, and simpleWildcardFind().
Referenced by findCompartmentsFromAnnotation().
cleanPath()
string ReadKkit::cleanPath (const string & path) const
Utility function. Cleans up path strings. In most cases, it replaces things with underscores. Replaces square braces with underscores. Replaces '*' with 'p' as it is usually there to indicate phosphorylation Replaces '-' with underscore Replaces '@' with underscore Replaces ' ' with underscore
Definition at line 648 of file ReadKkit.cpp.
{
    // Could surely do this better with STL. But harder to understand.
    // Harsha: Cleaned up this function
    // minus was getting replaced with underscore, but in some genesis model
    // pool and reaction/Enzyme has same string name with
    // difference of minus and underscore like eIF4G_A-clx and eIF4G_A_clx,
    // which later created a problem as the same name exist in moose when minus
    // was replaced with underscore.
    //So replacing minus with _minus_ like I do in SBML
    size_t Iindex = 0;
    string cleanDigit="/";
    while(true)
    {
        size_t sindex = path.find('/',Iindex+1);
        if (sindex == string::npos)
        {
            if (isdigit((path.substr(Iindex+1,sindex-Iindex-1))[0]) )
                cleanDigit += '_' ;
            cleanDigit += path.substr(Iindex+1,sindex-Iindex-1);
            break;
        }
        if (isdigit((path.substr(Iindex+1,sindex-Iindex-1))[0]))
            cleanDigit+='_';
        cleanDigit += path.substr(Iindex+1,sindex-Iindex);
        Iindex = sindex;
    }
    string ret = cleanDigit;
    //string ret = path;
    string cleanString;
    for ( unsigned int i = 0; i < cleanDigit.length(); ++i )
    {
        char c = ret[i];
        if ( c == '*' )
            cleanString += "_p";
        else if ( c == '[' || c == ']' || c == '@' || c == ' ')
            cleanString += '_';
        else if (c == '-')
            cleanString += "_";
        else
            cleanString += c;
    }
    return cleanString;
}
Referenced by addmsg(), buildChan(), buildEnz(), buildGraph(), buildGroup(), buildPlot(), buildPool(), buildReac(), buildStim(), buildTable(), and call().
convertEnzRatesToConcUnits()
void ReadKkit::convertEnzRatesToConcUnits ()
Convert regular Enz rates. Binding step k1 has similar issues as reac rates. k2 and k3 are both in units of 1/time, so OK.
Definition at line 1789 of file ReadKkit.cpp.
{
    const double NA_RATIO = KKIT_NA / NA;
    for ( map< string, Id >::iterator i = enzIds_.begin();
            i != enzIds_.end(); ++i )
    {
        Id enz = i->second;
        double k1 = Field< double >::get( enz, "k1" );
        // At this point the k1 is inaaccurate because the
        // NA for kkit is not accurate. So we correct for this.
        double numSub =
            Field< unsigned int >::get( enz, "numSubstrates" );
        // Note that we always have the enz itself as a substrate term.
        if ( numSub > 0 )
            k1 *= pow( NA_RATIO, numSub );
        Field< double >::set( enz, "k1", k1 );
    }
}
References enzIds_, Field< A >::get(), KKIT_NA, NA, and Field< A >::set().
Referenced by convertParametersToConcUnits().
convertKineticsToGroup()
Id ReadKkit::convertKineticsToGroup (Id mgr)
If kinetics has no reacs, we convert it into a group.
Definition at line 296 of file ReadKkit.cpp.
{
    Id kinId = Neutral::child( mgr.eref(), "kinetics" );
    kinId.element()->setName( "kinetics_conv_to_group");
    Id newKin = shell_->doCreate( "Neutral", mgr, "kinetics", 1 );
    // Move all child objects onto newKin.
    vector< Id > kids;
    Neutral::children( kinId.eref(), kids );
    for ( auto k:  kids )
        if ( k.element()->getName() == "mesh" ) {
            shell_->doDelete( k );
        } else {
            shell_->doMove( k, newKin );
        }
    auto oldCompt = compartments_;
    compartments_.clear();
    for ( auto ii = oldCompt.begin(); ii != oldCompt.end(); ++ii ) {
        if ( *ii != kinId ) {
            compartments_.push_back( *ii );
        }
    }
    shell_->doDelete( kinId );
    return newKin;
}
References Neutral::child(), Neutral::children(), compartments_, Shell::doCreate(), Shell::doDelete(), Shell::doMove(), Id::element(), Id::eref(), Element::getName(), Id::operator!=(), Element::setName(), and shell_.
Referenced by read().
convertMMenzRatesToConcUnits()
void ReadKkit::convertMMenzRatesToConcUnits ()
Convert MMEnz rates. Km should be in conc units. Actually rates stored as k1, k2, k3 in num units, so this has to be computed and then converted.
Definition at line 1762 of file ReadKkit.cpp.
{
    const double NA_RATIO = KKIT_NA / NA;
    for ( map< string, Id >::iterator i = mmEnzIds_.begin();
            i != mmEnzIds_.end(); ++i )
    {
        Id enz = i->second;
        // This was set in the original # units.
        double numKm = Field< double >::get( enz, "Km" );
        // At this point the numKm is inaaccurate because the
        // NA for kkit is not accurate. So we correct for this.
        double numSub =
            Field< unsigned int >::get( enz, "numSubstrates" );
        // Note that we always have the enz itself as a substrate term.
        if ( numSub > 0 )
            numKm *= pow( NA_RATIO, -numSub );
        // Now we have the correct numKm, plug it into the MMenz, and
        // let it internally fix up the Km
        Field< double >::set( enz, "numKm", numKm );
    }
}
References Field< A >::get(), KKIT_NA, mmEnzIds_, NA, and Field< A >::set().
convertParametersToConcUnits()
void ReadKkit::convertParametersToConcUnits ()
We have a slight problem because MOOSE has a more precise value for NA than does kkit. Also, at the time the model is loaded, the volume relationships are unknown. So we need to fix up conc units of all pools reacs post-facto. Here we assume that the conc units from Kkit are meant to be OK, so they override the #/cell (lower case k) units. So we convert all the Kfs and Kbs in the entire system after the model has been created, once we know the order of each reac.
Definition at line 1704 of file ReadKkit.cpp.
{
    convertPoolAmountToConcUnits();
    convertReacRatesToConcUnits();
    // convertMMenzRatesToConcUnits();
    convertEnzRatesToConcUnits();
}
References convertEnzRatesToConcUnits(), convertPoolAmountToConcUnits(), and convertReacRatesToConcUnits().
Referenced by read().
convertPoolAmountToConcUnits()
void ReadKkit::convertPoolAmountToConcUnits ()
Convert pool amounts. Initially given in n, but scaling issue.
Definition at line 1712 of file ReadKkit.cpp.
{
    const double NA_RATIO = KKIT_NA / NA;
    for ( map< string, Id >::iterator i = poolIds_.begin();
            i != poolIds_.end(); ++i )
    {
        Id pool = i->second;
        double nInit = Field< double >::get( pool, "nInit" );
        double n = Field< double >::get( pool, "n" );
        nInit /= NA_RATIO;
        n /= NA_RATIO;
        Field< double >::set( pool, "nInit", nInit );
        Field< double >::set( pool, "n", n );
    }
}
References Field< A >::get(), KKIT_NA, NA, poolIds_, and Field< A >::set().
Referenced by convertParametersToConcUnits().
convertReacRatesToConcUnits()
void ReadKkit::convertReacRatesToConcUnits ()
Convert Reac rates, initially in n units.
Definition at line 1729 of file ReadKkit.cpp.
{
    const double NA_RATIO = KKIT_NA / NA;
    for ( map< string, Id >::iterator i = reacIds_.begin();
            i != reacIds_.end(); ++i )
    {
        Id reac = i->second;
        double kf = Field< double >::get( reac, "Kf" );
        double kb = Field< double >::get( reac, "Kb" );
        // Note funny access here, using the Conc unit term (Kf) to get the
        // num unit term (kf). When reading, there are no volumes so the
        // Kf gets assigned to what was the kf value from kkit.
        // At this point the kf and kb are off because the
        // NA for kkit is not accurate. So we correct for this.
        unsigned int numSub =
            Field< unsigned int >::get( reac, "numSubstrates" );
        unsigned int numPrd =
            Field< unsigned int >::get( reac, "numProducts" );
        if ( numSub > 1 )
            kf *= pow( NA_RATIO, numSub - 1.0 );
        if ( numPrd > 1 )
            kb *= pow( NA_RATIO, numPrd - 1.0 );
        // Now we have the correct numKf and numKb, plug them into the
        // reac, and let it internally fix up the Kf and Kb.
        Field< double >::set( reac, "numKf", kf );
        Field< double >::set( reac, "numKb", kb );
    }
}
References Field< A >::get(), KKIT_NA, NA, reacIds_, and Field< A >::set().
Referenced by convertParametersToConcUnits().
dumpPlots()
void ReadKkit::dumpPlots (const string & filename)
Definition at line 455 of file ReadKkit.cpp.
{
    // ofstream fout ( filename.c_str() );
    vector< ObjId > plots;
    string plotpath = basePath_ + "/graphs/##[TYPE=Table2]," +
                      basePath_ + "/moregraphs/##[TYPE=Table2]";
    wildcardFind( plotpath, plots );
    for ( vector< ObjId >::iterator
            i = plots.begin(); i != plots.end(); ++i )
        SetGet2< string, string >::set( *i, "xplot",
                                        filename, i->element()->getName() );
}
References basePath_, ObjId::element(), Element::getName(), SetGet2< A1, A2 >::set(), and wildcardFind().
Referenced by testReadKkit().
findCompartmentsFromAnnotation()
int ReadKkit::findCompartmentsFromAnnotation ()
Definition at line 391 of file ReadKkit.cpp.
{
    int ret = 0;
    // This will go ill with nested compartments. But start with this.
    for ( auto g : groupPaths_ ) {
        Id gid( g );
        Id noteId = Neutral::child( gid.eref(), "info" );
        string note = Field< string >::get( noteId, "notes" );
        // If it is a compartment, then the note should say "Compt" or
        // "Compartment".
        if ( note.find( "Compartment") == 0 ) {
            ret++;
            Id parent = Neutral::parent( gid );
            // Get the vol from the first pool.
            double vol = childPoolVol( gid );
            string name = gid.element()->getName();
            gid.element()->setName( "group_conv_to_compt_" + name);
            Id comptId = shell_->doCreate( "CubeMesh", parent, name, 1 );
            // Assign volume and numEntries in the mesh.
            SetGet2< double, unsigned int >::set( comptId, "buildDefaultMesh", 1e-15, 1 );
            compartments_.push_back( comptId );
            vector< Id > kids;
            // Move all child objects onto comptId. Volumes should be fine.
            Neutral::children( gid.eref(), kids );
            for ( auto k:  kids )
                shell_->doMove( k, comptId );
            // SetGet1< double >::set( comptId, "setVolumeNotRates", vol );
            // Now tell the mesh to resize.
            Field< double >::set( comptId, "volume", vol );
            shell_->doDelete( gid );
        }
    }
    return ret;
}
References Neutral::child(), childPoolVol(), Neutral::children(), compartments_, Shell::doCreate(), Shell::doDelete(), Shell::doMove(), Id::element(), Id::eref(), Field< A >::get(), Element::getName(), groupPaths_, Id::Id(), Neutral::parent(), Field< A >::set(), SetGet2< A1, A2 >::set(), Element::setName(), and shell_.
Referenced by read().
findSumTotSrc()
Id ReadKkit::findSumTotSrc (const string & src)
Finds the source pool for a SumTot. It also deals with cases where the source is an enz-substrate complex
Definition at line 1230 of file ReadKkit.cpp.
{
    map< string, Id >::iterator i = poolIds_.find( src );
    if ( i != poolIds_.end() )
    {
        return i->second;
    }
    i = enzIds_.find( src );
    if ( i != enzIds_.end() )
    {
        string head;
        string cplx = src + '/' + pathTail( src, head ) + "_cplx";
        i = poolIds_.find( cplx );
        if ( i != poolIds_.end() )
        {
            return i->second;
        }
    }
    cout << "Error: ReadKkit::findSumTotSrc: Cannot find source pool '" << src << endl;
    assert( 0 );
    return Id();
}
References enzIds_, Id::Id(), pathTail(), and poolIds_.
Referenced by buildSumTotal().
getBasePath()
string ReadKkit::getBasePath () const
Definition at line 100 of file ReadKkit.cpp.
{
    return basePath_;
}
References basePath_.
getDefaultVol()
double ReadKkit::getDefaultVol () const
Definition at line 95 of file ReadKkit.cpp.
{
    return defaultVol_;
}
References defaultVol_.
getMaxTime()
double ReadKkit::getMaxTime () const
Definition at line 85 of file ReadKkit.cpp.
{
    return maxtime_;
}
References maxtime_.
getMoveOntoCompartment()
bool ReadKkit::getMoveOntoCompartment () const
Definition at line 110 of file ReadKkit.cpp.
{
    return moveOntoCompartment_;
}
References moveOntoCompartment_.
getPlotDt()
double ReadKkit::getPlotDt () const
Definition at line 90 of file ReadKkit.cpp.
{
    return plotdt_;
}
References plotdt_.
getVersion()
unsigned int ReadKkit::getVersion () const
Definition at line 105 of file ReadKkit.cpp.
{
    return version_;
}
References version_.
innerAddMsg()
void ReadKkit::innerAddMsg (const string & src, const map< string, Id > & m1, const string & srcMsg, const string & dest, const map< string, Id > & m2, const string & destMsg, bool isBackward = 0)
Definition at line 1485 of file ReadKkit.cpp.
{
    map< string, Id >::const_iterator i = m1.find( src );
    assert( i != m1.end() );
    Id srcId = i->second;
    i = m2.find( dest );
    assert( i != m2.end() );
    Id destId = i->second;
    // dest pool is substrate of src reac
    if ( isBackward )
    {
        ObjId ret = shell_->doAddMsg( "AllToOne",
                                      ObjId( srcId, 0 ), srcMsg,
                                      ObjId( destId, 0 ), destMsg );
        assert( ret != ObjId() );
    }
    else
    {
        ObjId ret = shell_->doAddMsg( "OneToAll",
                                      ObjId( srcId, 0 ), srcMsg,
                                      ObjId( destId, 0 ), destMsg );
        assert( ret != ObjId() );
    }
}
References Shell::doAddMsg(), ObjId::ObjId(), ObjId::ObjId(), ObjId::operator!=(), and shell_.
Referenced by addmsg(), and setupSlaveMsg().
innerRead()
void ReadKkit::innerRead (ifstream & fin)
Definition at line 468 of file ReadKkit.cpp.
{
    string line;
    string temp;
    lineNum_ = 0;
    string::size_type pos;
    bool clearLine = 1;
    ParseMode parseMode = INIT;
    while ( getline( fin, temp ) )
    {
        lineNum_++;
        if ( clearLine )
            line = "";
        temp = moose::trim(temp);
        if ( temp.length() == 0 )
            continue;
        pos = temp.find_last_not_of( "\t " );
        if ( pos == string::npos )
        {
            // Nothing new in line, go with what was left earlier,
            // and clear out line for the next cycle.
            temp = "";
            clearLine = 1;
        }
        else
        {
            if ( temp[pos] == '\\' )
            {
                temp[pos] = ' ';
                line.append( temp );
                clearLine = 0;
                continue;
            }
            else
            {
                line.append( temp );
                clearLine = 1;
            }
        }
        pos = line.find_first_not_of( "\t " );
        if ( pos == string::npos )
            continue;
        else
            line = line.substr( pos );
        if ( line.substr( 0, 2 ) == "//" )
            continue;
        if ( (pos = line.find("//")) != string::npos )
            line = line.substr( 0, pos );
        if ( line.substr( 0, 2 ) == "/*" )
        {
            parseMode = COMMENT;
            line = line.substr( 2 );
        }
        if ( parseMode == COMMENT )
        {
            pos = line.find( "*/" );
            if ( pos != string::npos )
            {
                parseMode = DATA;
                if ( line.length() > pos + 2 )
                    line = line.substr( pos + 2 );
            }
        }
        if ( parseMode == DATA )
            readData( line );
        else if ( parseMode == INIT )
        {
            parseMode = readInit( line );
        }
    }
    /*
    cout << " innerRead: " <<
            lineNum_ << " lines read, " <<
            numCompartments_ << " compartments, " <<
            numPools_ << " molecules, " <<
            numReacs_ << " reacs, " <<
            numEnz_ << " enzs, " <<
            numMMenz_ << " MM enzs, " <<
            numOthers_ << " others," <<
            numPlot_ << " plots," <<
            " PlotDt = " << plotdt_ <<
            endl;
            */
}
References COMMENT, DATA, INIT, lineNum_, readData(), readInit(), and moose::trim().
Referenced by read().
loadTab()
unsigned int ReadKkit::loadTab (const vector< string > & args)
Definition at line 1441 of file ReadKkit.cpp.
{
    Id tab;
    unsigned int start = 0;
    if ( args[1].substr( 0, 5 ) == "-cont" || args[1] == "-end" )
    {
        start = 2;
        tab = lastTab_;
        assert( tab != Id() );
    }
    else
    {
        tabEntries_.resize( 0 );
        start = 7;
        assert( args.size() >= start );
        lastTab_ = tab = Id( basePath_ + args[1] );
        assert( tab != Id() );
        // int calc_mode = atoi( args[3].c_str() );
        // int xdivs = atoi( args[4].c_str() );
        if ( tab.element()->cinfo()->isA( "StimulusTable" ) )
        {
            double xmin = atof( args[5].c_str() );
            double xmax = atof( args[6].c_str() );
            double start = Field< double >::get( tab, "startTime" );
            start += xmin;
            Field< double >::set( tab, "startTime", start );
            Field< double >::set( tab, "stopTime", xmax );
        }
    }
    for ( unsigned int i = start; i < args.size(); ++i )
    {
        tabEntries_.push_back( atof( args[i].c_str() ) );
    }
    Field< vector< double > >::set( tab, "vector", tabEntries_ );
    // cout << "Loading table for " << args[0] << "," << args[1] << "," << clean << endl;
    if ( args[1] == "-end" )
        lastTab_ = Id();
    return 0;
}
References basePath_, Element::cinfo(), Id::element(), Field< A >::get(), Id::Id(), Id::Id(), Cinfo::isA(), lastTab_, Id::operator!=(), Field< A >::set(), and tabEntries_.
Referenced by readData().
objdump()
void ReadKkit::objdump (const vector< string > & args)
Definition at line 699 of file ReadKkit.cpp.
{
    if ( args[1] == "kpool" )
        assignArgs( poolMap_, args );
    else if ( args[1] == "kreac" )
        assignArgs( reacMap_, args );
    else if ( args[1] == "kenz" )
        assignArgs( enzMap_, args );
    else if ( args[1] == "group" )
        assignArgs( groupMap_, args );
    else if ( args[1] == "xtab" )
        assignArgs( tableMap_, args );
    else if ( args[1] == "stim" )
        assignArgs( stimMap_, args );
    else if ( args[1] == "kchan" )
        assignArgs( chanMap_, args );
}
References assignArgs(), chanMap_, enzMap_, groupMap_, poolMap_, reacMap_, stimMap_, and tableMap_.
Referenced by readData().
pathTail()
string ReadKkit::pathTail (const string & path, string & head) const
Splits up kkit path into head and tail portions, tail is returned. Note that this prepends the basePath to the head.
Definition at line 639 of file ReadKkit.cpp.
{
    string::size_type pos = path.find_last_of( "/" );
    assert( pos != string::npos );
    head = basePath_ + path.substr( 0, pos );
    return path.substr( pos + 1 );
}
References basePath_.
Referenced by addmsg(), buildChan(), buildEnz(), buildGraph(), buildGroup(), buildPlot(), buildPool(), buildReac(), buildStim(), buildTable(), and findSumTotSrc().
read()
Id ReadKkit::read (const string & filename, const string & cellname, Id parent, const string & solverClass = "Stoich")
The readcell function implements the old GENESIS cellreader functionality. Although it is really a parser operation, I put it here in Kinetics because the cell format is independent of parser and is likely to remain a legacy for a while.
Definition at line 326 of file ReadKkit.cpp.
{
    string method = methodArg;
    ifstream fin( filename.c_str() );
    if (!fin)
    {
        cerr << "ReadKkit::read: could not open file " << filename << endl;
        return Id();
    }
    if ( method.substr(0, 4) == "old_" )
    {
        moveOntoCompartment_ = false;
        method = method.substr( 4 );
    }
    Shell* s = reinterpret_cast< Shell* >( ObjId().data() );
    Id mgr = makeStandardElements( pa, modelname );
    assert( mgr != Id() );
    baseId_ = mgr;
    basePath_ = mgr.path();
    enzCplxMols_.resize( 0 );
    innerRead( fin );
    int movedCompts = findCompartmentsFromAnnotation();
    if ( movedCompts == 0) {
        assignPoolCompartments();
        assignReacCompartments();
        assignEnzCompartments();
        assignMMenzCompartments();
    } else if ( !kineticsHasReactions( mgr ) ) {
        Id newKinetics = convertKineticsToGroup( mgr );
    }
    convertParametersToConcUnits();
    setMethod( s, mgr, simdt_, plotdt_, method );
    //Harsha: Storing solver and runtime at model level rather than model level
    Id kinetics( basePath_+"/kinetics");
    assert(kinetics != Id());
    Id cInfo = s->doCreate( "Annotator", basePath_, "info", 1 );
    assert( cInfo != Id() );
    Field< string > ::set(cInfo, "solver", "ee");
    Field< double > ::set(cInfo, "runtime", maxtime_);
    s->doReinit();
    return mgr;
}
References assignEnzCompartments(), assignMMenzCompartments(), assignPoolCompartments(), assignReacCompartments(), baseId_, basePath_, convertKineticsToGroup(), convertParametersToConcUnits(), ObjId::data(), Shell::doCreate(), Shell::doReinit(), enzCplxMols_, findCompartmentsFromAnnotation(), Id::Id(), Id::Id(), innerRead(), kineticsHasReactions(), makeStandardElements(), maxtime_, moveOntoCompartment_, ObjId::ObjId(), Id::operator!=(), Id::path(), plotdt_, Field< A >::set(), setMethod(), and simdt_.
Referenced by Shell::doLoadModel(), and testReadKkit().
readData()
void ReadKkit::readData (const string & line)
Definition at line 620 of file ReadKkit.cpp.
{
    vector< string > argv;
    chopLine( line, argv );
    if ( argv[0] == "simundump" )
        undump( argv );
    else if ( argv[0] == "addmsg" )
        addmsg( argv );
    else if ( argv[0] == "call" )
        call( argv );
    else if ( argv[0] == "simobjdump" )
        objdump( argv );
    else if ( argv[0] == "xtextload" )
        textload( argv );
    else if ( argv[0] == "loadtab" )
        loadTab( argv );
}
References addmsg(), call(), chopLine(), loadTab(), objdump(), textload(), and undump().
Referenced by innerRead().
readInit()
ReadKkit::ParseMode ReadKkit::readInit (const string & line)
Definition at line 558 of file ReadKkit.cpp.
{
    vector< string > argv;
    chopLine( line, argv );
    if ( argv.size() < 3 )
        return INIT;
    if ( argv[0] == "FASTDT" )
    {
        fastdt_ = atof( argv[2].c_str() );
        return INIT;
    }
    if ( argv[0] == "SIMDT" )
    {
        simdt_ = atof( argv[2].c_str() );
        return INIT;
    }
    if ( argv[0] == "CONTROLDT" )
    {
        controldt_ = atof( argv[2].c_str() );
        return INIT;
    }
    if ( argv[0] == "PLOTDT" )
    {
        plotdt_ = atof( argv[2].c_str() );
        return INIT;
    }
    if ( argv[0] == "MAXTIME" )
    {
        maxtime_ = atof( argv[2].c_str() );
        return INIT;
    }
    if ( argv[0] == "TRANSIENT_TIME" )
    {
        transientTime_ = atof( argv[2].c_str() );
        return INIT;
    }
    if ( argv[0] == "VARIABLE_DT_FLAG" )
    {
        useVariableDt_ = atoi( argv[2].c_str() );
        return INIT;
    }
    if ( argv[0] == "DEFAULT_VOL" )
    {
        defaultVol_ = atof( argv[2].c_str() );
        return INIT;
    }
    if ( argv[0] == "VERSION" )
    {
        version_ = atoi( argv[2].c_str() );
        return INIT;
    }
    if ( argv[0] == "initdump" )
    {
        initdumpVersion_ = atoi( argv[2].c_str() );
        return DATA;
    }
    return INIT;
}
References chopLine(), controldt_, DATA, defaultVol_, fastdt_, INIT, initdumpVersion_, maxtime_, plotdt_, simdt_, transientTime_, useVariableDt_, and version_.
Referenced by innerRead().
run()
void ReadKkit::run ()
This function sets up the kkit model for a run using the GSL, which means numerical integration using the GSL, all the plots specified by the kkit file, and the timestep for plots as specified by the kkit file.
Definition at line 426 of file ReadKkit.cpp.
{
    shell_->doSetClock( 11, simdt_ );
    shell_->doSetClock( 12, simdt_ );
    shell_->doSetClock( 13, simdt_ );
    shell_->doSetClock( 14, simdt_ );
    shell_->doSetClock( 16, plotdt_ );
    shell_->doSetClock( 17, plotdt_ );
    shell_->doSetClock( 18, plotdt_ );
    shell_->doReinit();
    if ( useVariableDt_ )
    {
        shell_->doSetClock( 11, fastdt_ );
        shell_->doSetClock( 12, fastdt_ );
        shell_->doSetClock( 13, fastdt_ );
        shell_->doSetClock( 14, fastdt_ );
        shell_->doStart( transientTime_ );
        shell_->doSetClock( 11, simdt_ );
        shell_->doSetClock( 12, simdt_ );
        shell_->doSetClock( 13, simdt_ );
        shell_->doSetClock( 14, simdt_ );
        shell_->doStart( maxtime_ - transientTime_ );
    }
    else
    {
        shell_->doStart( maxtime_ );
    }
}
References Shell::doReinit(), Shell::doSetClock(), Shell::doStart(), fastdt_, maxtime_, plotdt_, shell_, simdt_, transientTime_, and useVariableDt_.
Referenced by testReadKkit().
separateVols()
void ReadKkit::separateVols (Id pool, double vol)
Definition at line 837 of file ReadKkit.cpp.
{
    static const double TINY = 1e-3;
    for ( unsigned int i = 0 ; i < vols_.size(); ++i )
    {
        if ( fabs( vols_[i] - vol ) / ( fabs( vols_[i] ) + fabs( vol ) ) < TINY )
        {
            volCategories_[i].push_back( pool );
            return;
        }
    }
    vols_.push_back( vol );
    vector< Id > temp( 1, pool );
    volCategories_.push_back( temp );
}
References volCategories_, and vols_.
Referenced by buildEnz(), and buildPool().
setMoveOntoCompartment()
void ReadKkit::setMoveOntoCompartment (bool v)
Definition at line 115 of file ReadKkit.cpp.
{
    moveOntoCompartment_ = v;
}
References moveOntoCompartment_.
setupSlaveMsg()
void ReadKkit::setupSlaveMsg (const string & src, const string & dest)
Definition at line 1637 of file ReadKkit.cpp.
{
    // Convert the pool to a BufPool, if it isn't one already
    Id destId( basePath_ + "/kinetics/" + dest );
    assert( destId != Id() );
    Field< bool >::set( destId, "isBuffered", true );
    map< string, Id >* nameMap;
    // Check if the src is a table or a stim
    Id srcId( basePath_ + "/kinetics/" + src );
    assert( srcId != Id() );
    string output = "output";
    if ( srcId.element()->cinfo()->isA( "TableBase" ) )
    {
        nameMap = &tabIds_;
    }
    else if ( srcId.element()->cinfo()->isA( "PulseGen" ) )
    {
        nameMap = &stimIds_;
        output = "output";
    }
    else
    {
        cout << "Error: Unknown source for SLAVE msg: (" << src <<
             ", " << dest << ")\n";
        return;
    }
    // NSLAVE is 1, CONCSLAVE is 2.
    map< Id, int >::iterator i = poolFlags_.find( destId );
    if ( i == poolFlags_.end() || !( i->second & 2 ) )
    {
        innerAddMsg( src, *nameMap, output, dest, poolIds_,
                     "setNInit" );
    }
    else
    {
        innerAddMsg( src, *nameMap, output, dest, poolIds_,
                     "setConcInit" );
        double CONCSCALE = 0.001;
        // Rescale from uM to millimolar.
        if ( nameMap == &tabIds_ )
        {
            SetGet2< double, double >::set( srcId, "linearTransform",
                                            CONCSCALE, 0 );
        }
        else if ( nameMap == &stimIds_ )
        {
            double x = Field< double >::get( srcId, "baseLevel" );
            Field< double >::set( srcId, "baseLevel", x * CONCSCALE );
            x = Field< double >::get( srcId, "firstLevel" );
            Field< double >::set( srcId, "firstLevel", x * CONCSCALE );
            x = Field< double >::get( srcId, "secondLevel" );
            Field< double >::set( srcId, "secondLevel", x * CONCSCALE );
        }
    }
    // cout << "Added slave msg from " << src << " to " << dest << endl;
}
References basePath_, Element::cinfo(), Id::element(), Field< A >::get(), Id::Id(), Id::Id(), innerAddMsg(), Cinfo::isA(), Id::operator!=(), poolFlags_, poolIds_, Field< A >::set(), SetGet2< A1, A2 >::set(), stimIds_, and tabIds_.
Referenced by addmsg().
textload()
void ReadKkit::textload (const vector< string > & args)
Definition at line 757 of file ReadKkit.cpp.
{
}
Referenced by readData().
undump()
void ReadKkit::undump (const vector< string > & args)
Definition at line 761 of file ReadKkit.cpp.
{
    if ( args[1] == "kpool" )
        buildPool( args );
    else if ( args[1] == "kreac" )
        buildReac( args );
    else if ( args[1] == "kenz" )
        buildEnz( args );
    else if ( args[1] == "text" )
        buildText( args );
    else if ( args[1] == "xplot" )
        buildPlot( args );
    else if ( args[1] == "xgraph" )
        buildGraph( args );
    else if ( args[1] == "group" )
        buildGroup( args );
    else if ( args[1] == "geometry" )
        buildGeometry( args );
    else if ( args[1] == "stim" )
        buildStim( args );
    else if ( args[1] == "xcoredraw" )
        ;
    else if ( args[1] == "xtree" )
        ;
    else if ( args[1] == "xtext" )
        ;
    else if ( args[1] == "doqcsinfo" )
        ;
    else if ( args[1] == "kchan" )
        buildChan( args );
    else if ( args[1] == "xtab" )
        buildTable( args );
    else
        cout << "ReadKkit::undump: Do not know how to build '" << args[1] <<
             "'\n";
}
References buildChan(), buildEnz(), buildGeometry(), buildGraph(), buildGroup(), buildPlot(), buildPool(), buildReac(), buildStim(), buildTable(), and buildText().
Referenced by readData().
Member Data Documentation
baseId_
Id ReadKkit::baseId_ private
Base path into which entire kkit model will go.
Definition at line 192 of file ReadKkit.h.
Referenced by assignPoolCompartments(), read(), and ReadKkit().
basePath_
string ReadKkit::basePath_ private
Definition at line 191 of file ReadKkit.h.
Referenced by call(), dumpPlots(), getBasePath(), loadTab(), pathTail(), read(), ReadKkit(), and setupSlaveMsg().
chanIds_
map< string, Id > ReadKkit::chanIds_ private
Definition at line 239 of file ReadKkit.h.
Referenced by addmsg(), and buildChan().
chanMap_
map< string, int > ReadKkit::chanMap_ private
Definition at line 231 of file ReadKkit.h.
Referenced by buildChan(), and objdump().
compartments_
vector< Id > ReadKkit::compartments_ private
Definition at line 258 of file ReadKkit.h.
Referenced by assignPoolCompartments(), convertKineticsToGroup(), and findCompartmentsFromAnnotation().
controldt_
double ReadKkit::controldt_ private
regular numerical timestep from kkit.
Definition at line 196 of file ReadKkit.h.
Referenced by readInit(), and ReadKkit().
defaultVol_
double ReadKkit::defaultVol_ private
Use both fast and sim dts.
Definition at line 201 of file ReadKkit.h.
Referenced by getDefaultVol(), readInit(), and ReadKkit().
enzCplxMols_
vector< pair< Id, Id > > ReadKkit::enzCplxMols_ private
Definition at line 259 of file ReadKkit.h.
Referenced by buildEnz(), and read().
enzIds_
map< string, Id > ReadKkit::enzIds_ private
Definition at line 234 of file ReadKkit.h.
Referenced by addmsg(), buildEnz(), convertEnzRatesToConcUnits(), and findSumTotSrc().
enzMap_
map< string, int > ReadKkit::enzMap_ private
Definition at line 227 of file ReadKkit.h.
Referenced by buildEnz(), and objdump().
EPSILON
const double ReadKkit::EPSILON = 1.0e-15 static private
Definition at line 267 of file ReadKkit.h.
Referenced by buildEnz().
fastdt_
double ReadKkit::fastdt_ private
Base Id onto which entire kkit model will go.
Definition at line 194 of file ReadKkit.h.
Referenced by readInit(), ReadKkit(), and run().
groupMap_
map< string, int > ReadKkit::groupMap_ private
Definition at line 228 of file ReadKkit.h.
Referenced by buildGroup(), and objdump().
groupPaths_
vector< string > ReadKkit::groupPaths_ private
Definition at line 240 of file ReadKkit.h.
Referenced by buildGroup(), and findCompartmentsFromAnnotation().
initdumpVersion_
unsigned int ReadKkit::initdumpVersion_ private
KKit version.
Definition at line 203 of file ReadKkit.h.
Referenced by readInit(), and ReadKkit().
lastTab_
Id ReadKkit::lastTab_ private
This keeps track of the last Table used in loadtab.
Definition at line 252 of file ReadKkit.h.
Referenced by loadTab().
lineNum_
unsigned int ReadKkit::lineNum_ private
Definition at line 223 of file ReadKkit.h.
Referenced by innerRead(), and ReadKkit().
maxtime_
double ReadKkit::maxtime_ private
Timestep for updating plots.
Definition at line 198 of file ReadKkit.h.
Referenced by getMaxTime(), read(), readInit(), ReadKkit(), and run().
mmEnzIds_
map< string, Id > ReadKkit::mmEnzIds_ private
Definition at line 235 of file ReadKkit.h.
Referenced by addmsg(), buildEnz(), and convertMMenzRatesToConcUnits().
moveOntoCompartment_
bool ReadKkit::moveOntoCompartment_ private
Initdump too has a version.
Normally ReadKkit puts things on the same tree as the kkit tree. This flag tells the system to reorganize the tree so that each pool or reac or enz is on an appropriate compartment. Reacs are a bit arbitrary though, just go onto same compt as substrate. Defaults to false.
Definition at line 212 of file ReadKkit.h.
Referenced by getMoveOntoCompartment(), read(), ReadKkit(), and setMoveOntoCompartment().
numCompartments_
unsigned int ReadKkit::numCompartments_ private
Definition at line 214 of file ReadKkit.h.
Referenced by buildCompartment(), and ReadKkit().
numEnz_
unsigned int ReadKkit::numEnz_ private
Definition at line 217 of file ReadKkit.h.
Referenced by buildEnz(), and ReadKkit().
numMMenz_
unsigned int ReadKkit::numMMenz_ private
Definition at line 218 of file ReadKkit.h.
Referenced by buildEnz(), and ReadKkit().
numOthers_
unsigned int ReadKkit::numOthers_ private
Definition at line 221 of file ReadKkit.h.
Referenced by buildGeometry(), buildGraph(), buildGroup(), buildText(), and ReadKkit().
numPlot_
unsigned int ReadKkit::numPlot_ private
Definition at line 219 of file ReadKkit.h.
Referenced by buildPlot(), and ReadKkit().
numPools_
unsigned int ReadKkit::numPools_ private
Definition at line 215 of file ReadKkit.h.
Referenced by buildPool(), and ReadKkit().
numReacs_
unsigned int ReadKkit::numReacs_ private
Definition at line 216 of file ReadKkit.h.
Referenced by buildReac(), and ReadKkit().
numStim_
unsigned int ReadKkit::numStim_ private
Definition at line 220 of file ReadKkit.h.
Referenced by buildStim(), and ReadKkit().
plotdt_
double ReadKkit::plotdt_ private
Timestep for updating control graphics.
Definition at line 197 of file ReadKkit.h.
Referenced by getPlotDt(), read(), readInit(), ReadKkit(), and run().
plotIds_
map< string, Id > ReadKkit::plotIds_ private
Definition at line 236 of file ReadKkit.h.
Referenced by addmsg(), and buildPlot().
poolFlags_
map< Id, int > ReadKkit::poolFlags_ private
Definition at line 261 of file ReadKkit.h.
Referenced by buildPool(), and setupSlaveMsg().
poolIds_
map< string, Id > ReadKkit::poolIds_ private
Definition at line 232 of file ReadKkit.h.
Referenced by addmsg(), buildEnz(), buildPool(), buildSumTotal(), convertPoolAmountToConcUnits(), findSumTotSrc(), and setupSlaveMsg().
poolMap_
map< string, int > ReadKkit::poolMap_ private
Definition at line 225 of file ReadKkit.h.
Referenced by buildPool(), and objdump().
poolVols_
map< Id, double > ReadKkit::poolVols_ private
Definition at line 263 of file ReadKkit.h.
Referenced by buildEnz(), buildPool(), and childPoolVol().
reacIds_
map< string, Id > ReadKkit::reacIds_ private
Definition at line 233 of file ReadKkit.h.
Referenced by addmsg(), assignReacCompartments(), buildReac(), and convertReacRatesToConcUnits().
reacMap_
map< string, int > ReadKkit::reacMap_ private
Definition at line 226 of file ReadKkit.h.
Referenced by buildReac(), and objdump().
shell_
Shell* ReadKkit::shell_ private
Definition at line 265 of file ReadKkit.h.
Referenced by addmsg(), assignPoolCompartments(), assignReacCompartments(), buildChan(), buildEnz(), buildGraph(), buildGroup(), buildInfo(), buildPlot(), buildPool(), buildReac(), buildStim(), buildSumTotal(), buildTable(), convertKineticsToGroup(), findCompartmentsFromAnnotation(), innerAddMsg(), ReadKkit(), and run().
simdt_
double ReadKkit::simdt_ private
fast numerical timestep from kkit.
Definition at line 195 of file ReadKkit.h.
Referenced by read(), readInit(), ReadKkit(), and run().
stimIds_
map< string, Id > ReadKkit::stimIds_ private
Definition at line 238 of file ReadKkit.h.
Referenced by buildStim(), and setupSlaveMsg().
stimMap_
map< string, int > ReadKkit::stimMap_ private
Definition at line 230 of file ReadKkit.h.
Referenced by buildStim(), and objdump().
tabEntries_
vector< double > ReadKkit::tabEntries_ private
This holds the vector of array entries for loadtab.
Definition at line 254 of file ReadKkit.h.
Referenced by loadTab().
tabIds_
map< string, Id > ReadKkit::tabIds_ private
Definition at line 237 of file ReadKkit.h.
Referenced by buildTable(), and setupSlaveMsg().
tableMap_
map< string, int > ReadKkit::tableMap_ private
Definition at line 229 of file ReadKkit.h.
Referenced by buildTable(), and objdump().
transientTime_
double ReadKkit::transientTime_ private
Simulation run time.
Definition at line 199 of file ReadKkit.h.
Referenced by readInit(), ReadKkit(), and run().
useVariableDt_
bool ReadKkit::useVariableDt_ private
Time to run model at fastdt.
Definition at line 200 of file ReadKkit.h.
Referenced by readInit(), ReadKkit(), and run().
version_
unsigned int ReadKkit::version_ private
Default volume for new compartments.
Definition at line 202 of file ReadKkit.h.
Referenced by getVersion(), readInit(), and ReadKkit().
volCategories_
vector< vector< Id > > ReadKkit::volCategories_ private
List of Ids in each unique volume.
Definition at line 257 of file ReadKkit.h.
Referenced by assignPoolCompartments(), and separateVols().
vols_
vector< double > ReadKkit::vols_ private
This keeps track of unique volumes.
Definition at line 249 of file ReadKkit.h.
Referenced by assignPoolCompartments(), and separateVols().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/kinetics/ReadKkit.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/kinetics/ReadKkit.cpp