MOOSE - Multiscale Object Oriented Simulation Environment: moose::normal_distribution< T > Class Template Reference
moose::normal_distribution< T > Class Template Reference
#include <NormalDistribution.hpp>
Public Member Functions
normal_distribution (T mean=0.0, T sigma=1.0)
double operator() (moose::MOOSE_RNG_DEFAULT_ENGINE &r)
~normal_distribution ()
Public Attributes
T mean_
T sigma_
Detailed Description
template<typename T = double>
class moose::normal_distribution< T >
@Synopsis Get a Normally Distribution value from a given RNG.
Template Parameters
T
Definition at line 143 of file NormalDistribution.hpp.
Constructor & Destructor Documentation
normal_distribution()
template<typename T = double> moose::normal_distribution< T >::normal_distribution (T mean = 0.0, T sigma = 1.0) inline
Definition at line 148 of file NormalDistribution.hpp.
                                                      :
        mean_(mean), sigma_(sigma)
    {
        mean_ = mean;
        sigma_ = sigma;
    }
References moose::normal_distribution< T >::mean_, and moose::normal_distribution< T >::sigma_.
Referenced by GraupnerBrunel2012CaPlasticitySynHandler::GraupnerBrunel2012CaPlasticitySynHandler(), and test_normal_dist().
~normal_distribution()
template<typename T = double> moose::normal_distribution< T >::~normal_distribution () inline
Definition at line 155 of file NormalDistribution.hpp.
{ ; }
Member Function Documentation
operator()()
template<typename T = double> double moose::normal_distribution< T >::operator() (moose::MOOSE_RNG_DEFAULT_ENGINE & r) inline
Definition at line 157 of file NormalDistribution.hpp.
    {
        unsigned long  U=0, sign=0, i=0, j=0;
        T  x=0, y=0;
        while (1)
        {
            U = r();
            i = U & 0x0000007F;     /* 7 bit to choose the step */
            sign = U & 0x00000080;  /* 1 bit for the sign */
            j = U>>8;           /* 24 bit for the x-value */
            x = j*details::wtab[i];
            if (j < details::ktab[i])  break;
            if (i<127)
            {
                double  y0 = 0, y1 = 0;
                y0 = details::ytab[i];
                y1 = details::ytab[i+1];
                y = y1+(y0-y1)*r();
            }
            else
            {
                x = PARAM_R - std::log(1.0 - r()) / PARAM_R;
                y = exp( - PARAM_R*(x-0.5* PARAM_R)) * r();
            }
            if (y < std::exp(-0.5*x*x))  break;
        }
        return  sign ? sigma_*x : -sigma_*x;
    }
References moose::details::ktab, moose::normal_distribution< T >::sigma_, moose::details::wtab, and moose::details::ytab.
Referenced by test_normal_dist(), and GraupnerBrunel2012CaPlasticitySynHandler::updateCaWeightFactors().
Member Data Documentation
mean_
template<typename T = double> T moose::normal_distribution< T >::mean_
Definition at line 191 of file NormalDistribution.hpp.
Referenced by moose::normal_distribution< T >::normal_distribution().
sigma_
template<typename T = double> T moose::normal_distribution< T >::sigma_
Definition at line 192 of file NormalDistribution.hpp.
Referenced by moose::normal_distribution< T >::normal_distribution(), and moose::normal_distribution< T >::operator()().
The documentation for this class was generated from the following file:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/randnum/NormalDistribution.hpp