MOOSE - Multiscale Object Oriented Simulation Environment: StreamerBase Class Reference
StreamerBase Class Reference
#include <StreamerBase.h>
Public Member Functions
string getOutFilepath () const
StreamerBase & operator= (const StreamerBase &st)
void setOutFilepath (string stream)
StreamerBase ()
string vectorToCSV (const vector< double > &ys, const string &fmt)
~StreamerBase ()
Public Member Functions inherited from TableBase
void clearVec ()
void compareVec (vector< double > other, string op)
void compareXplot (string fname, string plotname, string op)
const vector< double > & data ()
double getOutputValue () const
string getPlotDump () const
unsigned int getVecSize () const
vector< double > getVector () const
double getY (unsigned int index) const
double interpolate (double x, double xmin, double xmax) const
void linearTransform (double scale, double offset)
void loadCSV (string fname, int startLine, int colNum, char separator)
void loadXplot (string fname, string plotname)
void loadXplotRange (string fname, string plotname, unsigned int start, unsigned int end)
double * lookupVec (unsigned int index)
void plainPlot (string file)
void setOutputValue (double val)
void setPlotDump (string v)
void setVecSize (unsigned int num)
void setVector (vector< double > val)
TableBase ()
void xplot (string file, string plotname)
Static Public Member Functions
static void writeToCSVFile (const string &filepath, const OpenMode openMode, const vector< double > &data, const vector< string > &columns)
Write data to csv file. See the documentation of writeToOutfile for details.
static void writeToNPYFile (const string &filepath, const OpenMode openmode, const vector< double > &data, const vector< string > &columns)
Write to NPY format. See the documentation of writeToOutfile for more details.
static void writeToOutFile (const string &filepath, const string &format, const OpenMode openmode, const vector< double > &data, const vector< string > &columns)
Write to a output file in given format.
Static Public Member Functions inherited from TableBase
static const Cinfo * initCinfo ()
Private Attributes
string outfilePath_
Static Private Attributes
static const char delimiter_ = ' '
static const char eol = '\n'
Additional Inherited Members
Protected Member Functions inherited from TableBase
vector< double > & vec ()
Detailed Description
Definition at line 33 of file StreamerBase.h.
Constructor & Destructor Documentation
StreamerBase()
StreamerBase::StreamerBase ()
Definition at line 32 of file StreamerBase.cpp.
{
}
~StreamerBase()
StreamerBase::~StreamerBase ()
Definition at line 43 of file StreamerBase.cpp.
{
}
Member Function Documentation
getOutFilepath()
string StreamerBase::getOutFilepath (void) const
Definition at line 49 of file StreamerBase.cpp.
{
    return outfilePath_;
}
References outfilePath_.
operator=()
StreamerBase & StreamerBase::operator= (const StreamerBase & st)
Definition at line 36 of file StreamerBase.cpp.
{
    this->outfilePath_ = st.outfilePath_;
    return *this;
}
References outfilePath_.
setOutFilepath()
void StreamerBase::setOutFilepath (string stream)
Definition at line 54 of file StreamerBase.cpp.
{
    outfilePath_ = filepath;
}
References outfilePath_.
vectorToCSV()
string StreamerBase::vectorToCSV (const vector< double > & ys, const string & fmt)
@Synopsis Return a csv representation of a vector.
@Param ys vector of double.
@Returns CSV string.
Definition at line 142 of file StreamerBase.cpp.
{
    string res{""};
    for( auto v : ys )
        res += std::to_string(v) + ",";
    return res;
}
writeToCSVFile()
void StreamerBase::writeToCSVFile (const string & filepath, const OpenMode openMode, const vector< double > & data, const vector< string > & columns) static
Write data to csv file. See the documentation of writeToOutfile for details.
Definition at line 91 of file StreamerBase.cpp.
{
    string m = (openmode == WRITE_STR)?"w":"a";
    FILE* fp = fopen( filepath.c_str(), m.c_str());
    if( NULL == fp )
    {
        LOG( moose::warning, "Failed to open " << filepath );
        return;
    }
    // If writing in "w" mode, write the header first.
    if(openmode == WRITE_STR)
    {
        string headerText = "";
        for( vector<string>::const_iterator it = columns.begin();
            it != columns.end(); it++ )
            headerText += ( *it + delimiter_ );
        headerText += eol;
        fprintf(fp, "%s", headerText.c_str());
    }
    string text = "";
    for( unsigned int i = 0; i < data.size(); i+=columns.size() )
    {
        // Start of a new row.
        for( unsigned int ii = 0; ii < columns.size(); ii++ )
            text += moose::toString( data[i+ii] ) + delimiter_;
        // At the end of each row, we remove the delimiter_ and append newline_.
        *(text.end()-1) = eol;
    }
    fprintf(fp, "%s", text.c_str() );
    fclose(fp);
}
References delimiter_, eol, moose::toString(), moose::warning, and WRITE_STR.
Referenced by writeToOutFile().
writeToNPYFile()
void StreamerBase::writeToNPYFile (const string & filepath, const OpenMode openmode, const vector< double > & data, const vector< string > & columns) static
Write to NPY format. See the documentation of writeToOutfile for more details.
Definition at line 129 of file StreamerBase.cpp.
{
    //for(auto v: data) cout << v << ' ';
    //cout << endl;
    if(openmode == APPEND_BIN)
        return cnpy2::appendNumpy( filepath, data, columns);
    if(openmode == WRITE_BIN)
        return cnpy2::writeNumpy( filepath, data, columns);
}
References APPEND_BIN, cnpy2::appendNumpy(), WRITE_BIN, and cnpy2::writeNumpy().
Referenced by writeToOutFile().
writeToOutFile()
void StreamerBase::writeToOutFile (const string & filepath, const string & format, const OpenMode openmode, const vector< double > & data, const vector< string > & columns) static
Write to a output file in given format.
Parameters
filepath,path of output file. If parent directories do not exist, they will be created. If creation fails for some reason, data will be saved in current working directory. The name of the file will be computed from the given directory name by replacing '/' or '\' by '_'.
format
npy : numpy binary format (version 1 and 2), version 1 is default. csv or dat: comma separated value (delimiter ' ')
Parameters
openmode (write or append)
data,vector of values
ncols (number of columns). Incoming data will be formatted into a matrix with ncols.
Definition at line 60 of file StreamerBase.cpp.
{
    if( data.size() == 0 )
        return;
    if("npy" == outputFormat  || "npz" == outputFormat)
    {
        OpenMode m = (openmode == WRITE)?WRITE_BIN:APPEND_BIN;
        writeToNPYFile( filepath, m, data, columns );
    }
    else if( "csv" == outputFormat || "dat" == outputFormat )
    {
        OpenMode m = (openmode == WRITE)?WRITE_STR:APPEND_STR;
        writeToCSVFile( filepath, m, data, columns );
    }
    else
    {
        LOG( moose::warning, "Unsupported format " << outputFormat
                << ". Use npy or csv. Falling back to default csv"
           );
        OpenMode m = (openmode == WRITE)?WRITE_STR:APPEND_STR;
        writeToCSVFile( filepath, m, data, columns );
    }
}
References APPEND_BIN, APPEND_STR, moose::warning, WRITE, WRITE_BIN, WRITE_STR, writeToCSVFile(), and writeToNPYFile().
Referenced by Streamer::cleanUp(), Streamer::process(), Table::process(), Streamer::reinit(), Table::reinit(), and Table::~Table().
Member Data Documentation
delimiter_
const char StreamerBase::delimiter_ = ' ' static private
Definition at line 107 of file StreamerBase.h.
Referenced by writeToCSVFile().
eol
const char StreamerBase::eol = '\n' static private
Definition at line 106 of file StreamerBase.h.
Referenced by writeToCSVFile().
outfilePath_
string StreamerBase::outfilePath_ private
Definition at line 104 of file StreamerBase.h.
Referenced by getOutFilepath(), operator=(), and setOutFilepath().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/builtins/StreamerBase.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/builtins/StreamerBase.cpp