MOOSE - Multiscale Object Oriented Simulation Environment: IntFire Class Reference
IntFire Class Reference
#include <IntFire.h>
Public Member Functions
void activation (double v)
double getRefractoryPeriod () const
double getTau () const
double getThresh () const
double getVm () const
void innerAddSpike (unsigned int synIndex, double time)
IntFire ()
IntFire (double thresh, double tau)
void process (const Eref &e, ProcPtr p)
void reinit (const Eref &e, ProcPtr p)
void setRefractoryPeriod (double v)
void setTau (double v)
void setThresh (double v)
void setVm (double v)
Static Public Member Functions
static const Cinfo * initCinfo ()
Private Attributes
double activation_
double lastSpike_
double refractoryPeriod_
double tau_
double thresh_
double Vm_
Friends
void testStandaloneIntFire ()
void testSynapse ()
Detailed Description
Definition at line 14 of file IntFire.h.
Constructor & Destructor Documentation
IntFire() [1/2]
IntFire::IntFire ()
Definition at line 103 of file IntFire.cpp.
    : Vm_( 0.0 ), thresh_( 0.0 ), tau_( 1.0 ),
        refractoryPeriod_( 0.1 ), lastSpike_( -0.1 ),
        activation_( 0.0 )
{
    ;
}
References activation_, lastSpike_, refractoryPeriod_, tau_, thresh_, and Vm_.
IntFire() [2/2]
IntFire::IntFire (double thresh, double tau)
Definition at line 111 of file IntFire.cpp.
    : Vm_( 0.0 ), thresh_( thresh ), tau_( tau ), refractoryPeriod_( 0.1 ), lastSpike_( -1.0 ), activation_( 0.0 )
{
    ;
}
References activation_, lastSpike_, refractoryPeriod_, tau_, thresh_, and Vm_.
Member Function Documentation
activation()
void IntFire::activation (double v)
Definition at line 182 of file IntFire.cpp.
{
    activation_ += v;
}
References activation_.
Referenced by initCinfo().
getRefractoryPeriod()
double IntFire::getRefractoryPeriod () const
Definition at line 177 of file IntFire.cpp.
{
    return refractoryPeriod_;
}
References refractoryPeriod_.
Referenced by initCinfo().
getTau()
double IntFire::getTau () const
Definition at line 167 of file IntFire.cpp.
{
    return tau_;
}
References tau_.
Referenced by initCinfo().
getThresh()
double IntFire::getThresh () const
Definition at line 172 of file IntFire.cpp.
{
    return thresh_;
}
References thresh_.
Referenced by initCinfo().
getVm()
double IntFire::getVm () const
Definition at line 162 of file IntFire.cpp.
{
    return Vm_;
}
References Vm_.
Referenced by initCinfo(), testSendSpike(), and testSetGetDouble().
initCinfo()
const Cinfo * IntFire::initCinfo () static
Definition at line 23 of file IntFire.cpp.
{
        // Field Definitions
        static ValueFinfo< IntFire, double > Vm(
            "Vm",
            "Membrane potential",
            &IntFire::setVm,
            &IntFire::getVm
        );
        static ValueFinfo< IntFire, double > tau(
            "tau",
            "charging time-course",
            &IntFire::setTau,
            &IntFire::getTau
        );
        static ValueFinfo< IntFire, double > thresh(
            "thresh",
            "firing threshold",
            &IntFire::setThresh,
            &IntFire::getThresh
        );
        static ValueFinfo< IntFire, double > refractoryPeriod(
            "refractoryPeriod",
            "Minimum time between successive spikes",
            &IntFire::setRefractoryPeriod,
            &IntFire::getRefractoryPeriod
        );
        // MsgDest Definitions
        static DestFinfo activation( "activation",
            "Handles value of synaptic activation arriving on this IntFire",
            new OpFunc1< IntFire, double >( &IntFire::activation ) );
        static DestFinfo process( "process",
            "Handles process call",
            new ProcOpFunc< IntFire >( &IntFire::process ) );
        static DestFinfo reinit( "reinit",
            "Handles reinit call",
            new ProcOpFunc< IntFire >( &IntFire::reinit ) );
        // SharedFinfo Definitions
        static Finfo* procShared[] = {
            &process, &reinit
        };
        static SharedFinfo proc( "proc",
            "Shared message for process and reinit",
            procShared, sizeof( procShared ) / sizeof( const Finfo* )
        );
    static Finfo* intFireFinfos[] = {
        &Vm,    // Value
        &tau,   // Value
        &thresh,                // Value
        &refractoryPeriod,      // Value
        &activation,        // DestFinfo
        &proc,                  // SharedFinfo
        spikeOut(),         // MsgSrc
    };
    static Dinfo< IntFire > dinfo;
    static Cinfo intFireCinfo (
        "IntFire",
        Neutral::initCinfo(),
        intFireFinfos,
        sizeof( intFireFinfos ) / sizeof ( Finfo* ),
        &dinfo
    );
    return &intFireCinfo;
}
References activation(), Cinfo::Cinfo(), DestFinfo::DestFinfo(), getRefractoryPeriod(), getTau(), getThresh(), getVm(), Neutral::initCinfo(), OpFunc1< T, A >::OpFunc1(), process(), ProcOpFunc< T >::ProcOpFunc(), reinit(), setRefractoryPeriod(), setTau(), setThresh(), setVm(), SharedFinfo::SharedFinfo(), spikeOut(), and ValueFinfo< T, F >::ValueFinfo().
Referenced by testCinfoFields(), testFinfoFields(), testSendSpike(), testSetGetDouble(), and testSparseMsg().
innerAddSpike()
void IntFire::innerAddSpike (unsigned int synIndex, double time)
Overrides base class function. Inserts an event into the pendingEvents queue for spikes.
process()
void IntFire::process (const Eref & e, ProcPtr p)
Definition at line 117 of file IntFire.cpp.
{
    static bool report = false;
    static unsigned int reportIndex = 0;
    if ( report && e.dataIndex() == reportIndex )
        cout << "   " << p->currTime << "," << Vm_;
    Vm_ += activation_;
    activation_ = 0.0;
    if ( Vm_ > thresh_ && (p->currTime - lastSpike_) > refractoryPeriod_ ) {
        spikeOut()->send( e, p->currTime );
        Vm_ = -1.0e-7;
        lastSpike_ = p->currTime;
    } else {
        Vm_ *= ( 1.0 - p->dt / tau_ );
    }
}
References activation_, ProcInfo::currTime, Eref::dataIndex(), ProcInfo::dt, lastSpike_, refractoryPeriod_, SrcFinfo1< T >::send(), spikeOut(), tau_, thresh_, and Vm_.
Referenced by initCinfo(), and testSendSpike().
reinit()
void IntFire::reinit (const Eref & e, ProcPtr p)
Definition at line 135 of file IntFire.cpp.
{
    Vm_ = 0.0;
    activation_ = 0.0;
}
References activation_, and Vm_.
Referenced by initCinfo().
setRefractoryPeriod()
void IntFire::setRefractoryPeriod (double v)
Definition at line 156 of file IntFire.cpp.
{
    refractoryPeriod_ = v;
    lastSpike_ = -v;
}
References lastSpike_, and refractoryPeriod_.
Referenced by initCinfo().
setTau()
void IntFire::setTau (double v)
Definition at line 146 of file IntFire.cpp.
{
    tau_ = v;
}
References tau_.
Referenced by initCinfo(), and testSendSpike().
setThresh()
void IntFire::setThresh (double v)
Definition at line 151 of file IntFire.cpp.
{
    thresh_ = v;
}
References thresh_.
Referenced by initCinfo().
setVm()
void IntFire::setVm (double v)
Definition at line 141 of file IntFire.cpp.
{
    Vm_ = v;
}
References Vm_.
Referenced by initCinfo(), and testSendSpike().
Friends And Related Symbol Documentation
testStandaloneIntFire
void testStandaloneIntFire () friend
testSynapse
void testSynapse () friend
Definition at line 205 of file testSynapse.cpp.
{
#ifdef DO_UNIT_TESTS
    testRollingMatrix();
    testRollingMatrix2();
    testSeqSynapse();
#endif // DO_UNIT_TESTS
}
Member Data Documentation
activation_
double IntFire::activation_ private
Definition at line 55 of file IntFire.h.
Referenced by activation(), IntFire(), IntFire(), process(), and reinit().
lastSpike_
double IntFire::lastSpike_ private
Definition at line 54 of file IntFire.h.
Referenced by IntFire(), IntFire(), process(), and setRefractoryPeriod().
refractoryPeriod_
double IntFire::refractoryPeriod_ private
Definition at line 53 of file IntFire.h.
Referenced by getRefractoryPeriod(), IntFire(), IntFire(), process(), and setRefractoryPeriod().
tau_
double IntFire::tau_ private
Definition at line 52 of file IntFire.h.
Referenced by getTau(), IntFire(), IntFire(), process(), and setTau().
thresh_
double IntFire::thresh_ private
Definition at line 51 of file IntFire.h.
Referenced by getThresh(), IntFire(), IntFire(), process(), and setThresh().
Vm_
double IntFire::Vm_ private
Definition at line 50 of file IntFire.h.
Referenced by getVm(), IntFire(), IntFire(), process(), reinit(), and setVm().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/biophysics/IntFire.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/biophysics/IntFire.cpp