MOOSE - Multiscale Object Oriented Simulation Environment: HHGateF Class Reference
HHGateF Class Reference
#include <HHGateF.h>
Public Member Functions
string getAlpha (const Eref &e) const
string getBeta (const Eref &e) const
string getInf (const Eref &e) const
string getTau (const Eref &e) const
HHGateF ()
HHGateF (Id originalChanId, Id originalGateId)
double lookupA (double v) const
double lookupB (double v) const
void lookupBoth (double v, double *A, double *B) const
HHGateF & operator= (const HHGateF &)
void setAlpha (const Eref &e, const string expr)
Set the expression for evaluating alpha.
void setBeta (const Eref &e, const string expr)
Set the expression for evaluating beta.
void setInf (const Eref &e, const string expr)
Set the expression for evaluating inf.
void setTau (const Eref &e, const string expr)
Set the expression for evaluating tau.
Public Member Functions inherited from HHGateBase
bool checkOriginal (Id id, const string &field) const
HHGateBase ()
HHGateBase (Id originalChanId, Id originalGateId)
bool isOriginalChannel (Id id) const
bool isOriginalGate (Id id) const
Id originalChannelId () const
Id originalGateId () const
Static Public Member Functions
static const Cinfo * initCinfo ()
Static Public Member Functions inherited from HHGateBase
static const Cinfo * initCinfo ()
Protected Attributes
exprtk::expression< double > alpha_
string alphaExpr_
Store the user-specified expression strings.
double alphav_
exprtk::expression< double > beta_
string betaExpr_
double betav_
double infv_
exprtk::parser< double > parser_
exprtk::symbol_table< double > symTab_
bool tauInf_
double tauv_
double v_
Protected Attributes inherited from HHGateBase
Id originalChanId_
Id originalGateId_
Detailed Description
This class handles a single gate on an HHChannel. It is equivalent to the m and h terms on the Hodgkin-Huxley Na channel, or the n term on the K channel. It stores the voltage-dependence (sometimes concentration-dependence) of the gating variables for opening the channel. It does so in a tabular form which can be directly filled using experimental data points. It also provides a set of utility functions for defining the gate in functional forms, and accessing those original functional forms. The HHGateF is accessed as a FieldElement, which means that it is available as a pointer on the HHChannel. HHGateFs are typically shared. This means that when you make a copy or a vector of an HHChannel, there is only a single HHGateF created, and its pointer is used by all the copies. The lookup functions are thread-safe. Field assignment to the HHGateF should be possible only from the original HHChannel, but all the others do have read permission. Whereas HHGate uses interpolation tables, HHGateF uses direct formula evaluation, hence slower but possibly more accurate.
Definition at line 41 of file HHGateF.h.
Constructor & Destructor Documentation
HHGateF() [1/2]
HHGateF::HHGateF ()
Dummy constructor, to keep Dinfo happy. Should never be used
Definition at line 127 of file HHGateF.cpp.
                 : HHGateBase(0, 0)
{
    cerr << "Warning: HHGateF::HHGateF(): this should never be called" << endl;
}
References HHGateBase::HHGateBase().
HHGateF() [2/2]
HHGateF::HHGateF (Id originalChanId, Id originalGateId)
This constructor is the one meant to be used. It takes the originalId of the parent HHChannel as a required argument, so that any subsequent 'write' functions can be checked to see if they are legal. Also tracks its own Id.
Definition at line 132 of file HHGateF.cpp.
    : HHGateBase(originalChanId, originalGateId)
{
    symTab_.add_variable("v", v_);
    symTab_.add_variable("alpha", alphav_);
    symTab_.add_variable("beta", betav_);
    symTab_.add_variable("tau", tauv_);
    symTab_.add_variable("inf", infv_);
    symTab_.add_constants();
    alpha_.register_symbol_table(symTab_);
    beta_.register_symbol_table(symTab_);
}
References HHGateBase::HHGateBase().
Referenced by HHGateF2D::HHGateF2D(), and HHChannelF::innerCreateGate().
Member Function Documentation
getAlpha()
string HHGateF::getAlpha (const Eref & e) const
Definition at line 209 of file HHGateF.cpp.
{
    return tauInf_ ? "" : alphaExpr_;
}
References alphaExpr_, and tauInf_.
getBeta()
string HHGateF::getBeta (const Eref & e) const
Definition at line 228 of file HHGateF.cpp.
{
    return tauInf_ ? "" : betaExpr_;
}
References betaExpr_, and tauInf_.
getInf()
string HHGateF::getInf (const Eref & e) const
Definition at line 266 of file HHGateF.cpp.
{
    return tauInf_ ? betaExpr_ : "";
}
References betaExpr_, and tauInf_.
getTau()
string HHGateF::getTau (const Eref & e) const
Definition at line 247 of file HHGateF.cpp.
{
    return tauInf_ ? alphaExpr_ : "";
}
References alphaExpr_, and tauInf_.
initCinfo()
const Cinfo * HHGateF::initCinfo () static
Definition at line 14 of file HHGateF.cpp.
{
    // Field definitions.
    static ReadOnlyLookupValueFinfo<HHGateF, double, double> A(
        "A",
        "lookupA: Compute the A gate value from a double. "
        "This is done by evaluating the expressions for alpha/beta"
        " or tau/inf.",
        &HHGateF::lookupA);
    static ReadOnlyLookupValueFinfo<HHGateF, double, double> B(
        "B",
        "lookupB: Look up the B gate value from a double."
        "This is done by evaluating the expressions for alpha/beta"
        " or tau/inf.",
        &HHGateF::lookupB);
    static ElementValueFinfo<HHGateF, string> alpha(
        "alphaExpr",
        "Expression for voltage-dependent rates, forward rate `alpha`. "
        "This requires the expression for `beta` to be defined as well.\n"
        "The syntax follows exprtk, with variable name `v` for input variable"
        " (which can be voltage or concentration depending on message "
        "connection in case of HHGateF which takes only one input).\n"
        "For HHGateF2D which depends on two inputs, the variable names are "
        "`v` for voltage, and `c` for concentration.\n"
        "And additional set of variable names are available for cases "
        "that require intermediate calculations. These are:\n"
        " `alpha` for forward rate,\n"
        " `beta` for backward rate,\n"
        " `tau` for time constant, and\n"
        " `inf` for steady state open fraction\n"
        "as per Hodgkin and Huxley's formulation.\n"
        "This is useful for conditional values for these parameters:\n"
        "Example:\n"
        "~(alpha:=0.3 * exp(-80 * (v -(-46e-3))) + 3.5, alpha < 3.8? 3.8: "
        "alpha)\n"
        " first computes `alpha` by the first formula, and returns it "
        "only if the computed value is >= 3.8, otherwise it returns 3.8.",
        &HHGateF::setAlpha, &HHGateF::getAlpha);
    static ElementValueFinfo<HHGateF, string> beta(
        "betaExpr",
        "Expression for voltage-dependent rates, backward rate `beta`. "
        "This requires the expression for `alpha` to be defined as well. See"
        " documentation on `alpha` for details on predefined variable names.",
        &HHGateF::setBeta, &HHGateF::getBeta);
    static ElementValueFinfo<HHGateF, string> tau(
        "tauExpr",
        "Expression for voltage-dependent rates, time constant `tau`. "
        "This requires the expression for `inf` to be defined as well.\n"
        "See documentation for `alpha` for details on predefined variable"
        " names. Example of a complex conditional expression (based on "
        "Maex and De Schutter 1998):\n"
        "~(alpha := 750 * exp(81 * (v - (-39e-3))), "
        "beta := 750 * exp(-66 * (v - (-39e-3))), "
        "tau := 1/(alpha + beta), tau < 1e-5? 1e-5)"
        "\nThis computes alpha and beta and then from those, tau. "
        "However if the calculated value of tau falls under "
        "1e-5, it makes the value 1e-5.",
        &HHGateF::setTau, &HHGateF::getTau);
    static ElementValueFinfo<HHGateF, string> inf(
        "infExpr",
        "Expression for voltage-dependent rates, steady state open fraction "
        "`inf`. "
        "This requires the expression for `tau` to be defined as well.",
        &HHGateF::setInf, &HHGateF::getInf);
    // DestFinfos
    static Finfo* HHGateFFinfos[] = {
        &A,      // ReadOnlyLookupValue
        &B,      // ReadOnlyLookupValue
        &alpha,  // Value
        &beta,   // Value
        &tau,    // Value
        &inf,    // Value
    };
    static string doc[] = {
        "Name",
        "HHGateF",
        "Author",
        "Subhasis Ray, 2025, CHINTA",
        "Description",
        "Gating component of Hodkgin-Huxley type channels, equivalent to the "
        "m and h terms on the Na squid channel and the n term on K. "
        "This takes the voltage and state variable from the channel, "
        "computes the new value of the state variable and a scaling, "
        "depending on gate power, for the conductance. As opposed to HHGate, "
        "which uses lookup tables for speed, this evaluates explicit "
        "expressions for accuracy. This is a single variable gate, either "
        "voltage or concentration. So the expression also allows only one "
        "indpendent variable, which is assumed `v`. See the documentation of "
        "``Function`` class for details on the praser.",
    };
    static Dinfo<HHGateF> dinfo;
    static Cinfo HHGateFCinfo("HHGateF", Neutral::initCinfo(), HHGateFFinfos,
                              sizeof(HHGateFFinfos) / sizeof(Finfo*), &dinfo,
                              doc, sizeof(doc) / sizeof(string));
    return &HHGateFCinfo;
}
References Neutral::initCinfo().
Referenced by HHGateF2D::initCinfo().
lookupA()
double HHGateF::lookupA (double v) const
lookupA: Look up the A vector from a double. Typically does so by direct scaling and offset to an integer lookup, using a fine enough table granularity that there is little error. Alternatively uses linear interpolation. The range of the double is predefined based on knowledge of voltage or conc ranges, and the granularity is specified by the xmin, xmax, and invDx fields.
Definition at line 173 of file HHGateF.cpp.
{
    // TODO: check for divide by zero?
    v_ = v;
    return tauInf_ ? beta_.value() / alpha_.value() : alpha_.value();
}
References v_.
Referenced by lookupBoth().
lookupB()
double HHGateF::lookupB (double v) const
lookupB: Look up the B vector from a double, similar to lookupA.
Definition at line 180 of file HHGateF.cpp.
{
    // TODO: check for divide by zero?
    v_ = v;
    return tauInf_ ? 1.0 / alpha_.value() : alpha_.value() + beta_.value();
}
References v_.
Referenced by lookupBoth().
lookupBoth()
void HHGateF::lookupBoth (double v, double * A, double * B) const
Single call to get both A and B values by lookup
Definition at line 187 of file HHGateF.cpp.
{
    *A = lookupA(v);
    *B = lookupB(v);
    // cerr << "# HHGateF::lookupBoth: v=" << v << ", A=" << *A << ", B="<< *B
    // << endl;
}
References lookupA(), and lookupB().
Referenced by HHChannelF::vProcess(), and HHChannelF::vReinit().
operator=()
HHGateF & HHGateF::operator= (const HHGateF & rhs)
HHGates remain shared between copies of a channel, so it should never be copied. Yet we need to define this because eprtk parser deletes its copy assignment, which deletes compiler generated copy assignment operator for HHGateF, which raises error with Dinfo, which tries to reference the copy operator.
Definition at line 146 of file HHGateF.cpp.
{
    // protect from self-assignment.
    if(this == &rhs)
        return *this;
    v_ = rhs.v_;
    symTab_.add_variable("v", v_);
    symTab_.add_variable("alpha", alphav_);
    symTab_.add_variable("beta", betav_);
    symTab_.add_variable("tau", tauv_);
    symTab_.add_variable("inf", infv_);
    symTab_.add_constants();
    alpha_.register_symbol_table(symTab_);
    beta_.register_symbol_table(symTab_);
    alphaExpr_ = rhs.alphaExpr_;
    betaExpr_ = rhs.betaExpr_;
    parser_.compile(alphaExpr_, alpha_);
    parser_.compile(betaExpr_, beta_);
    tauInf_ = rhs.tauInf_;
    return *this;
}
References alphaExpr_, betaExpr_, tauInf_, and v_.
setAlpha()
void HHGateF::setAlpha (const Eref & e, const string expr)
Set the expression for evaluating alpha.
Definition at line 195 of file HHGateF.cpp.
{
    if(checkOriginal(e.id(), "alpha")) {
        if(!parser_.compile(expr, alpha_)) {
            cerr << "Error: Element: " << e.objId().path() << ": HHGateF::setAlpha: cannot compile expression!\n"
                 << parser_.error() << endl;
            return;
        }
        tauInf_ = false;
        alphaExpr_ = expr;
        parser_.compile(alphaExpr_, alpha_);
    }
}
References alphaExpr_, HHGateBase::checkOriginal(), Eref::id(), and tauInf_.
setBeta()
void HHGateF::setBeta (const Eref & e, const string expr)
Set the expression for evaluating beta.
Definition at line 214 of file HHGateF.cpp.
{
    if(checkOriginal(e.id(), "beta")) {
        if(!parser_.compile(expr, beta_)) {
            cerr << "Error: Element: " << e.objId().path() << ": HHGateF::setBeta: cannot compile expression!\n"
                 << parser_.error() << endl;
            return;
        }
        tauInf_ = false;
        betaExpr_ = expr;
        parser_.compile(betaExpr_, beta_);
    }
}
References betaExpr_, HHGateBase::checkOriginal(), Eref::id(), and tauInf_.
setInf()
void HHGateF::setInf (const Eref & e, const string expr)
Set the expression for evaluating inf.
Definition at line 252 of file HHGateF.cpp.
{
    if(checkOriginal(e.id(), "beta")) {
        if(!parser_.compile(expr, beta_)) {
            cerr << "Error: Element: " << e.objId().path() << ": HHGateF::setInf: cannot compile expression!\n"
                 << parser_.error() << endl;
            return;
        }
        tauInf_ = true;
        betaExpr_ = expr;
        parser_.compile(betaExpr_, beta_);
    }
}
References betaExpr_, HHGateBase::checkOriginal(), Eref::id(), and tauInf_.
setTau()
void HHGateF::setTau (const Eref & e, const string expr)
Set the expression for evaluating tau.
Definition at line 233 of file HHGateF.cpp.
{
    if(checkOriginal(e.id(), "alpha")) {
        if(!parser_.compile(expr, alpha_)) {
            cerr << "Error: Element: " << e.objId().path() << ": HHGateF::setTau: cannot compile expression!\n"
                 << parser_.error() << endl;
            return;
        }
        tauInf_ = true;
        alphaExpr_ = expr;
        parser_.compile(alphaExpr_, alpha_);
    }
}
References alphaExpr_, HHGateBase::checkOriginal(), Eref::id(), and tauInf_.
Member Data Documentation
alpha_
exprtk::expression<double> HHGateF::alpha_ protected
Definition at line 110 of file HHGateF.h.
alphaExpr_
string HHGateF::alphaExpr_ protected
Store the user-specified expression strings.
Definition at line 122 of file HHGateF.h.
Referenced by getAlpha(), getTau(), operator=(), HHGateF2D::operator=(), setAlpha(), and setTau().
alphav_
double HHGateF::alphav_ mutable protected
to allow intermediate expressions for cases where there is conditional on alpha/beta or tau/inf values
Definition at line 116 of file HHGateF.h.
beta_
exprtk::expression<double> HHGateF::beta_ protected
Definition at line 111 of file HHGateF.h.
betaExpr_
string HHGateF::betaExpr_ protected
Definition at line 123 of file HHGateF.h.
Referenced by getBeta(), getInf(), operator=(), HHGateF2D::operator=(), setBeta(), and setInf().
betav_
double HHGateF::betav_ mutable protected
Definition at line 117 of file HHGateF.h.
infv_
double HHGateF::infv_ mutable protected
Definition at line 119 of file HHGateF.h.
parser_
exprtk::parser<double> HHGateF::parser_ protected
Definition at line 112 of file HHGateF.h.
symTab_
exprtk::symbol_table<double> HHGateF::symTab_ protected
Definition at line 109 of file HHGateF.h.
tauInf_
bool HHGateF::tauInf_ protected
Whether the gate is expressed in tau-inf form. If false, it is alpha-beta form
Definition at line 108 of file HHGateF.h.
Referenced by getAlpha(), getBeta(), getInf(), getTau(), operator=(), HHGateF2D::operator=(), setAlpha(), setBeta(), setInf(), and setTau().
tauv_
double HHGateF::tauv_ mutable protected
Definition at line 118 of file HHGateF.h.
v_
double HHGateF::v_ mutable protected
Definition at line 113 of file HHGateF.h.
Referenced by lookupA(), HHGateF2D::lookupA(), lookupB(), operator=(), and HHGateF2D::operator=().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/biophysics/HHGateF.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/biophysics/HHGateF.cpp