MOOSE - Multiscale Object Oriented Simulation Environment: Flux Class Reference
Flux Class Reference
#include <RateTerm.h>
Public Member Functions
RateTerm * copyWithVolScaling (double vol, double sub, double prd) const
Flux (double k, unsigned int y)
unsigned int getReactants (vector< unsigned int > &molIndex) const
double operator() (const double *S) const
Computes the rate. The argument is the molecule array.
void rescaleVolume (short comptIndex, const vector< short > &compartmentLookup, double ratio)
Public Member Functions inherited from ZeroOrder
RateTerm * copyWithVolScaling (double vol, double sub, double prd) const
double getR1 () const
Used by Zombie to return rate terms.
double getR2 () const
Used by Zombie to return rate terms.
unsigned int getReactants (vector< unsigned int > &molIndex) const
double operator() (const double *S) const
Computes the rate. The argument is the molecule array.
void rescaleVolume (short comptIndex, const vector< short > &compartmentLookup, double ratio)
void setK (double k)
void setR1 (double k1)
Used by Zombie to assign rate terms.
void setR2 (double k2)
Used by Zombie to assign rate terms.
void setRates (double k1, double k2)
ZeroOrder (double k)
Public Member Functions inherited from RateTerm
RateTerm ()
virtual ~RateTerm ()
Private Attributes
unsigned int y_
Additional Inherited Members
Static Public Attributes inherited from RateTerm
static const double EPSILON = 1.0e-6
Protected Attributes inherited from ZeroOrder
double k_
Detailed Description
This rather odd reaction is used when we have an amount y of a molecule and we want it to proceed to zero at a fixed rate k. k would usually be 1/dt. Following dt seconds, we need to update y as it has nominally all been used up.
Definition at line 350 of file RateTerm.h.
Constructor & Destructor Documentation
Flux()
Flux::Flux (double k, unsigned int y) inline
Definition at line 353 of file RateTerm.h.
        : ZeroOrder( k ), y_( y )
    {;}
References y_, and ZeroOrder::ZeroOrder().
Referenced by copyWithVolScaling().
Member Function Documentation
copyWithVolScaling()
RateTerm * Flux::copyWithVolScaling (double vol, double sub, double prd) const inline virtual
Duplicates rate term and then applies volume scaling. Arguments are volume of reference voxel, product of vol/refVol for all substrates: applied to R1 product of vol/refVol for all products: applied to R2
Note that unless the reaction is cross-compartment, the vol/refVol will be one.
Implements RateTerm.
Definition at line 375 of file RateTerm.h.
    {
        return new Flux( k_, y_ );
    }
References Flux(), ZeroOrder::k_, and y_.
getReactants()
unsigned int Flux::getReactants (vector< unsigned int > & molIndex) const inline virtual
This function finds the reactant indices in the vector S. It returns the number of substrates found, which are the first entries in molIndex. The products are the remaining ones. Note that it does NOT find products for unidirectional reactions, which is a bit of a problem.
Implements RateTerm.
Definition at line 363 of file RateTerm.h.
    {
        molIndex.resize( 0 );
        return 0;
    }
operator()()
double Flux::operator() (const double * S) const inline virtual
Computes the rate. The argument is the molecule array.
Implements RateTerm.
Definition at line 357 of file RateTerm.h.
    {
        assert(! std::isnan( S[ y_ ] ) );
        return k_ * S[ y_ ];
    }
References ZeroOrder::k_, and y_.
rescaleVolume()
void Flux::rescaleVolume (short comptIndex, const vector< short > & compartmentLookup, double ratio) inline virtual
This is used to rescale the RateTerm kinetics when the compartment volume changes. This is needed because the kinetics are in extensive units, that is, mol numbers, rather than in intensive units like concentration. So when the volume changes the rate terms change. Each Rate term checks if any of its reactant molecules are affected, and if so, rescales. Ratio is newVol / oldVol
Implements RateTerm.
Definition at line 369 of file RateTerm.h.
    {
        return; // Nothing needs to be scaled.
    }
Member Data Documentation
y_
unsigned int Flux::y_ private
Definition at line 382 of file RateTerm.h.
Referenced by copyWithVolScaling(), Flux(), and operator()().
The documentation for this class was generated from the following file:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/ksolve/RateTerm.h