MOOSE - Multiscale Object Oriented Simulation Environment: ZombieCompartment Class Reference
ZombieCompartment Class Reference
#include <ZombieCompartment.h>
Public Member Functions
void dummy (const Eref &e, ProcPtr p)
double mtrand (void)
double vGetCm (const Eref &e) const
double vGetEm (const Eref &e) const
double vGetIm (const Eref &e) const
double vGetInitVm (const Eref &e) const
double vGetInject (const Eref &e) const
double vGetRa (const Eref &e) const
double vGetRm (const Eref &e) const
double vGetVm (const Eref &e) const
void vHandleAxial (double Vm)
void vHandleChannel (const Eref &e, double Gk, double Ek)
void vHandleRaxial (double Ra, double Vm)
void vInitProc (const Eref &e, ProcPtr p)
void vInitReinit (const Eref &e, ProcPtr p)
void vInjectMsg (const Eref &e, double current)
void vProcess (const Eref &e, ProcPtr p)
void vRandInject (const Eref &e, double prob, double current)
void vReinit (const Eref &e, ProcPtr p)
void vSetCm (const Eref &e, double Cm)
void vSetEm (const Eref &e, double Em)
void vSetInitVm (const Eref &e, double initVm)
void vSetInject (const Eref &e, double Inject)
void vSetRa (const Eref &e, double Ra)
void vSetRm (const Eref &e, double Rm)
void vSetSolver (const Eref &e, Id hsolve)
Assigns the solver to the zombie.
void vSetVm (const Eref &e, double Vm)
ZombieCompartment ()
virtual ~ZombieCompartment ()
Public Member Functions inherited from moose::CompartmentBase
void cable ()
CompartmentBase ()
void displace (double dx, double dy, double dz)
Displaces compartment by specified distance vector.
double getCm (const Eref &e) const
vector< double > getCoords () const
double getDiameter () const
double getEm (const Eref &e) const
double getIm (const Eref &e) const
double getInitVm (const Eref &e) const
double getInject (const Eref &e) const
double getLength () const
double getRa (const Eref &e) const
double getRm (const Eref &e) const
double getVm (const Eref &e) const
double getX () const
double getX0 () const
double getY () const
double getY0 () const
double getZ () const
double getZ0 () const
void handleAxial (double Vm)
void handleChannel (const Eref &e, double Gk, double Ek)
void handleRaxial (double Ra, double Vm)
void initProc (const Eref &e, ProcPtr p)
void initReinit (const Eref &e, ProcPtr p)
void injectMsg (const Eref &e, double current)
void process (const Eref &e, ProcPtr p)
void randInject (const Eref &e, double prob, double current)
bool rangeWarning (const string &field, double value)
void reinit (const Eref &e, ProcPtr p)
void setCm (const Eref &e, double Cm)
void setCoords (vector< double > value)
void setDiameter (double diameter)
void setEm (const Eref &e, double Em)
void setGeomAndElec (const Eref &e, double length, double dia)
Scales electrical values along with setting length, dia.
void setInitVm (const Eref &e, double initVm)
void setInject (const Eref &e, double Inject)
void setLength (double length)
void setRa (const Eref &e, double Ra)
void setRm (const Eref &e, double Rm)
void setVm (const Eref &e, double Vm)
void setX (double value)
void setX0 (double value)
void setY (double value)
void setY0 (double value)
void setZ (double value)
void setZ0 (double value)
void updateLength ()
virtual ~CompartmentBase ()
Static Public Member Functions
static const Cinfo * initCinfo ()
Static Public Member Functions inherited from moose::CompartmentBase
static const Cinfo * initCinfo ()
static SrcFinfo1< double > * VmOut ()
static void zombify (Element *orig, const Cinfo *zClass, Id hsolve)
Private Member Functions
void copyFields (moose::Compartment *c)
Private Attributes
HSolve * hsolve_
moose::RNG rng
Static Private Attributes
static const double EPSILON = 1.0e-15
Detailed Description
Zombie object that lets HSolve do its calculations, while letting the user interact with this object as if it were the original object.
Definition at line 35 of file ZombieCompartment.h.
Constructor & Destructor Documentation
ZombieCompartment()
ZombieCompartment::ZombieCompartment ()
Definition at line 57 of file ZombieCompartment.cpp.
{
    hsolve_   = NULL;
}
References hsolve_.
~ZombieCompartment()
ZombieCompartment::~ZombieCompartment () virtual
Definition at line 62 of file ZombieCompartment.cpp.
{
    ;
}
Member Function Documentation
copyFields()
void ZombieCompartment::copyFields (moose::Compartment * c) private
dummy()
void ZombieCompartment::dummy (const Eref & e, ProcPtr p)
initCinfo()
const Cinfo * ZombieCompartment::initCinfo () static
Initializes the class info.
The initCinfo() function sets up the Compartment class. This function uses the common trick of having an internal static value which is created the first time the function is called. There are several static arrays set up here. The ones which use SharedFinfos are for shared messages where multiple kinds of information go along the same connection.
Definition at line 23 of file ZombieCompartment.cpp.
{
    // static Finfo* compartmentFinfos[] = { };
    static string doc[] =
    {
        "Name", "ZombieCompartment",
        "Author", "Upi Bhalla",
        "Description", "Compartment object, for branching neuron models.",
    };
    static Dinfo< ZombieCompartment > dinfo;
    static Cinfo zombieCompartmentCinfo(
        "ZombieCompartment",
        CompartmentBase::initCinfo(),
        0,
        0,
        // compartmentFinfos,
        // sizeof( compartmentFinfos ) / sizeof( Finfo* ),
        &dinfo,
        doc,
        sizeof( doc )/ sizeof( string )
    );
    return &zombieCompartmentCinfo;
}
References Cinfo::Cinfo(), and moose::CompartmentBase::initCinfo().
Referenced by HSolve::zombify().
mtrand()
double ZombieCompartment::mtrand (void)
Definition at line 216 of file ZombieCompartment.cpp.
{
    return rng.uniform( );
}
References rng, and moose::RNG::uniform().
vGetCm()
double ZombieCompartment::vGetCm (const Eref & e) const virtual
Implements moose::CompartmentBase.
Definition at line 96 of file ZombieCompartment.cpp.
{
    return hsolve_->getCm( e.id() );
}
References HSolve::getCm(), hsolve_, and Eref::id().
vGetEm()
double ZombieCompartment::vGetEm (const Eref & e) const virtual
Implements moose::CompartmentBase.
Definition at line 85 of file ZombieCompartment.cpp.
{
    return hsolve_->getEm( e.id() );
}
References HSolve::getEm(), hsolve_, and Eref::id().
vGetIm()
double ZombieCompartment::vGetIm (const Eref & e) const virtual
Implements moose::CompartmentBase.
Definition at line 128 of file ZombieCompartment.cpp.
{
    return hsolve_->getIm( e.id() );
}
References HSolve::getIm(), hsolve_, and Eref::id().
vGetInitVm()
double ZombieCompartment::vGetInitVm (const Eref & e) const virtual
Implements moose::CompartmentBase.
Definition at line 148 of file ZombieCompartment.cpp.
{
    return hsolve_->getInitVm( e.id() );
}
References HSolve::getInitVm(), hsolve_, and Eref::id().
vGetInject()
double ZombieCompartment::vGetInject (const Eref & e) const virtual
Implements moose::CompartmentBase.
Definition at line 138 of file ZombieCompartment.cpp.
{
    return hsolve_->getInject( e.id() );
}
References HSolve::getInject(), hsolve_, and Eref::id().
vGetRa()
double ZombieCompartment::vGetRa (const Eref & e) const virtual
Implements moose::CompartmentBase.
Definition at line 118 of file ZombieCompartment.cpp.
{
    return hsolve_->getRa( e.id() );
}
References HSolve::getRa(), hsolve_, and Eref::id().
vGetRm()
double ZombieCompartment::vGetRm (const Eref & e) const virtual
Implements moose::CompartmentBase.
Definition at line 107 of file ZombieCompartment.cpp.
{
    return hsolve_->getRm( e.id() );
}
References HSolve::getRm(), hsolve_, and Eref::id().
vGetVm()
double ZombieCompartment::vGetVm (const Eref & e) const virtual
Implements moose::CompartmentBase.
Definition at line 74 of file ZombieCompartment.cpp.
{
    assert(hsolve_);
    return hsolve_->getVm( e.id() );
}
References HSolve::getVm(), hsolve_, and Eref::id().
vHandleAxial()
void ZombieCompartment::vHandleAxial (double Vm) virtual
handleAxial handles incoming axial message data.
Implements moose::CompartmentBase.
Definition at line 187 of file ZombieCompartment.cpp.
{
    ;
}
vHandleChannel()
void ZombieCompartment::vHandleChannel (const Eref & e, double Gk, double Ek) virtual
handleChannel handles information coming from the channel to the compartment
Implements moose::CompartmentBase.
Definition at line 177 of file ZombieCompartment.cpp.
{
    hsolve_->addGkEk( e.id(), Gk, Ek );
}
References HSolve::addGkEk(), hsolve_, and Eref::id().
vHandleRaxial()
void ZombieCompartment::vHandleRaxial (double Ra, double Vm) virtual
handleRaxial handles incoming raxial message data.
Implements moose::CompartmentBase.
Definition at line 182 of file ZombieCompartment.cpp.
{
    ;
}
vInitProc()
void ZombieCompartment::vInitProc (const Eref & e, ProcPtr p) virtual
The initProc function is for a second phase of 'process' operations. It sends the axial and raxial messages to other compartments. It has to be executed out of phase with the main process so that all compartments are equivalent and there is no calling order dependence in the results.
Implements moose::CompartmentBase.
Definition at line 167 of file ZombieCompartment.cpp.
{
    ;
}
vInitReinit()
void ZombieCompartment::vInitReinit (const Eref & e, ProcPtr p) virtual
Empty function to do another reinit step out of phase with the main one. Nothing needs doing there.
Implements moose::CompartmentBase.
Definition at line 172 of file ZombieCompartment.cpp.
{
    ;
}
vInjectMsg()
void ZombieCompartment::vInjectMsg (const Eref & e, double current) virtual
Injects a constantly updated current into the compartment. Unlike the 'inject' field, this injected current is applicable only for a single timestep. So this is meant to be used as the destination of a message rather than as a one-time assignment.
Implements moose::CompartmentBase.
Definition at line 192 of file ZombieCompartment.cpp.
{
    hsolve_->addInject( e.id(), current );
}
References HSolve::addInject(), hsolve_, and Eref::id().
vProcess()
void ZombieCompartment::vProcess (const Eref & e, ProcPtr p) virtual
The process function does the object updating and sends out messages to channels, nernsts, and so on.
Implements moose::CompartmentBase.
Definition at line 157 of file ZombieCompartment.cpp.
{
    ;
}
vRandInject()
void ZombieCompartment::vRandInject (const Eref & e, double prob, double current) virtual
Injects a constantly updated current into the compartment, with a probability prob. Note that it isn't the current amplitude that is random, it is the presence or absence of the current that is probabilistic.
Implements moose::CompartmentBase.
Definition at line 197 of file ZombieCompartment.cpp.
{
    //~ if ( mtrand() < prob * dt_ ) {
    //~ hsolve_->addInject( e.id(), current );
    //~ }
}
vReinit()
void ZombieCompartment::vReinit (const Eref & e, ProcPtr p) virtual
The reinit function reinitializes all fields.
Implements moose::CompartmentBase.
Definition at line 162 of file ZombieCompartment.cpp.
{
    rng.setSeed( moose::__rng_seed__ );
}
References moose::__rng_seed__, rng, and moose::RNG::setSeed().
vSetCm()
void ZombieCompartment::vSetCm (const Eref & e, double Cm) virtual
Implements moose::CompartmentBase.
Definition at line 90 of file ZombieCompartment.cpp.
{
    if ( rangeWarning( "Cm", Cm ) ) return;
    hsolve_->setCm( e.id(), Cm );
}
References hsolve_, Eref::id(), moose::CompartmentBase::rangeWarning(), and HSolve::setCm().
vSetEm()
void ZombieCompartment::vSetEm (const Eref & e, double Em) virtual
Implements moose::CompartmentBase.
Definition at line 80 of file ZombieCompartment.cpp.
{
    hsolve_->setEm( e.id(), Em );
}
References hsolve_, Eref::id(), and HSolve::setEm().
vSetInitVm()
void ZombieCompartment::vSetInitVm (const Eref & e, double initVm) virtual
Implements moose::CompartmentBase.
Definition at line 143 of file ZombieCompartment.cpp.
{
    hsolve_->setInitVm( e.id(), initVm );
}
References hsolve_, Eref::id(), and HSolve::setInitVm().
vSetInject()
void ZombieCompartment::vSetInject (const Eref & e, double Inject) virtual
Implements moose::CompartmentBase.
Definition at line 133 of file ZombieCompartment.cpp.
{
    hsolve_->setInject( e.id(), Inject );
}
References hsolve_, Eref::id(), and HSolve::setInject().
vSetRa()
void ZombieCompartment::vSetRa (const Eref & e, double Ra) virtual
Implements moose::CompartmentBase.
Definition at line 112 of file ZombieCompartment.cpp.
{
    if ( rangeWarning( "Ra", Ra ) ) return;
    hsolve_->setRa( e.id(), Ra );
}
References hsolve_, Eref::id(), moose::CompartmentBase::rangeWarning(), and HSolve::setRa().
vSetRm()
void ZombieCompartment::vSetRm (const Eref & e, double Rm) virtual
Implements moose::CompartmentBase.
Definition at line 101 of file ZombieCompartment.cpp.
{
    if ( rangeWarning( "Rm", Rm ) ) return;
    hsolve_->setRm( e.id(), Rm );
}
References hsolve_, Eref::id(), moose::CompartmentBase::rangeWarning(), and HSolve::setRm().
vSetSolver()
void ZombieCompartment::vSetSolver (const Eref & e, Id hsolve) virtual
Assigns the solver to the zombie.
Reimplemented from moose::CompartmentBase.
Definition at line 205 of file ZombieCompartment.cpp.
{
    if ( !hsolve.element()->cinfo()->isA( "HSolve" ) ) {
        cout << "Error: ZombieCompartment::vSetSolver: Object: " <<
                hsolve.path() << " is not an HSolve. Aborted\n";
        hsolve_ = 0;
        return;
    }
    hsolve_ = reinterpret_cast< HSolve* >( hsolve.eref().data() );
}
References Element::cinfo(), Eref::data(), Id::element(), Id::eref(), hsolve_, Cinfo::isA(), and Id::path().
vSetVm()
void ZombieCompartment::vSetVm (const Eref & e, double Vm) virtual
Implements moose::CompartmentBase.
Definition at line 68 of file ZombieCompartment.cpp.
{
    assert(hsolve_);
    hsolve_->setVm( e.id(), Vm );
}
References hsolve_, Eref::id(), and HSolve::setVm().
Member Data Documentation
EPSILON
const double ZombieCompartment::EPSILON = 1.0e-15 static private
Definition at line 143 of file ZombieCompartment.h.
hsolve_
HSolve* ZombieCompartment::hsolve_ private
Definition at line 141 of file ZombieCompartment.h.
Referenced by vGetCm(), vGetEm(), vGetIm(), vGetInitVm(), vGetInject(), vGetRa(), vGetRm(), vGetVm(), vHandleChannel(), vInjectMsg(), vSetCm(), vSetEm(), vSetInitVm(), vSetInject(), vSetRa(), vSetRm(), vSetSolver(), vSetVm(), and ZombieCompartment().
rng
moose::RNG ZombieCompartment::rng private
Definition at line 147 of file ZombieCompartment.h.
Referenced by mtrand(), and vReinit().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/hsolve/ZombieCompartment.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/hsolve/ZombieCompartment.cpp