MOOSE - Multiscale Object Oriented Simulation Environment: STDPSynapse Class Reference
STDPSynapse Class Reference
#include <STDPSynapse.h>
Public Member Functions
double getAPlus () const
void setAPlus (double v)
void setHandler (SynHandlerBase *h)
STDPSynapse ()
Public Member Functions inherited from Synapse
void addSpike (const Eref &e, double time)
double getDelay () const
double getTopSpike (const Eref &e) const
double getWeight () const
void setDelay (double v)
void setHandler (SynHandlerBase *h)
void setWeight (double v)
Synapse ()
Static Public Member Functions
static const Cinfo * initCinfo ()
Static Public Member Functions inherited from Synapse
static void addMsgCallback (const Eref &e, const string &finfoName, ObjId msg, unsigned int msgLookup)
static void dropMsgCallback (const Eref &e, const string &finfoName, ObjId msg, unsigned int msgLookup)
static const Cinfo * initCinfo ()
Private Attributes
double aPlus_
SynHandlerBase * handler_
Detailed Description
This is the base class for synapses with STDP. It is meant to be used as a FieldElement entry on a parent object, derived from the STDPSynHandlerBase.
Definition at line 18 of file STDPSynapse.h.
Constructor & Destructor Documentation
STDPSynapse()
STDPSynapse::STDPSynapse ()
Definition at line 55 of file STDPSynapse.cpp.
                         : handler_ (0)
{
    aPlus_ = 0.0;
}
References aPlus_, and handler_.
Member Function Documentation
getAPlus()
double STDPSynapse::getAPlus () const
Definition at line 71 of file STDPSynapse.cpp.
{
    return aPlus_;
}
References aPlus_.
Referenced by initCinfo(), and STDPSynHandler::vProcess().
initCinfo()
const Cinfo * STDPSynapse::initCinfo () static
Definition at line 15 of file STDPSynapse.cpp.
{
    static string doc[] =
    {
        "Name", "STDPSynapse",
        "Author", "Aditya Gilra",
        "Description", "Subclass of Synapse including variables for Spike Timing Dependent Plasticity (STDP).",
    };
    static ValueFinfo< STDPSynapse, double > aPlus(
        "aPlus",
        "aPlus is a pre-synaptic variable that keeps a decaying 'history' of previous pre-spike(s)"
        "and is used to update the synaptic weight when a post-synaptic spike appears."
        "It determines the t_pre < t_post (pre before post) part of the STDP window.",
        &STDPSynapse::setAPlus,
        &STDPSynapse::getAPlus
    );
    static Finfo* synapseFinfos[] = {
        &aPlus,     // Field
    };
    static Dinfo< STDPSynapse > dinfo;
    static Cinfo STDPSynapseCinfo (
        "STDPSynapse",
        Synapse::initCinfo(),
        synapseFinfos,
        sizeof( synapseFinfos ) / sizeof ( Finfo* ),
        &dinfo,
        doc,
        sizeof( doc ) / sizeof( string ),
        true // This is a FieldElement.
    );
    return &STDPSynapseCinfo;
}
References Cinfo::Cinfo(), getAPlus(), Synapse::initCinfo(), setAPlus(), and ValueFinfo< T, F >::ValueFinfo().
Referenced by STDPSynHandler::initCinfo().
setAPlus()
void STDPSynapse::setAPlus (double v)
Definition at line 66 of file STDPSynapse.cpp.
{
    aPlus_ = v;
}
References aPlus_.
Referenced by initCinfo(), and STDPSynHandler::vProcess().
setHandler()
void STDPSynapse::setHandler (SynHandlerBase * h)
Definition at line 60 of file STDPSynapse.cpp.
{
    handler_ = h;
    Synapse::setHandler( h );
}
References handler_, and Synapse::setHandler().
Referenced by STDPSynHandler::addSynapse(), STDPSynHandler::operator=(), and STDPSynHandler::vSetNumSynapses().
Member Data Documentation
aPlus_
double STDPSynapse::aPlus_ private
Definition at line 30 of file STDPSynapse.h.
Referenced by getAPlus(), setAPlus(), and STDPSynapse().
handler_
SynHandlerBase* STDPSynapse::handler_ private
Definition at line 31 of file STDPSynapse.h.
Referenced by setHandler(), and STDPSynapse().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/synapse/STDPSynapse.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/synapse/STDPSynapse.cpp