MOOSE - Multiscale Object Oriented Simulation Environment: Variable Class Reference
Variable Class Reference
#include <Variable.h>
Public Member Functions
string getName () const
double getValue () const
double * ptr ()
void setValue (const Eref &e, double v)
void setValue (double v)
Variable (const Variable &rhs)
Variable (string name="")
~Variable ()
Static Public Member Functions
static const Cinfo * initCinfo ()
Private Attributes
string name_ {"NONAME"}
double value_ {0.0}
Detailed Description
This class is used as FieldElement in Function. It is used as named variable of type double.
Definition at line 22 of file Variable.h.
Constructor & Destructor Documentation
Variable() [1/2]
Variable::Variable (string name = "") inline
Definition at line 27 of file Variable.h.
                            : name_(name), value_(0.0)
    {};
References name_, and value_.
Referenced by Function::innerSetExpr().
Variable() [2/2]
Variable::Variable (const Variable & rhs) inline
Definition at line 30 of file Variable.h.
                                 : name_(rhs.name_), value_(rhs.value_)
    {
        ;
    }
References name_, and value_.
~Variable()
Variable::~Variable () inline
Definition at line 35 of file Variable.h.
{};
Member Function Documentation
getName()
string Variable::getName () const inline
Definition at line 52 of file Variable.h.
    {
        return name_;
    }
References name_.
Referenced by Function::innerSetExpr().
getValue()
double Variable::getValue () const inline
Definition at line 47 of file Variable.h.
    {
        return value_;
    }
References value_.
Referenced by initCinfo().
initCinfo()
const Cinfo * Variable::initCinfo () static
Definition at line 12 of file Variable.cpp.
{
    static ValueFinfo< Variable, double > value(
        "value",
        "Variable value",
        &Variable::setValue,
        &Variable::getValue
        );
    static DestFinfo input(
        "input",
        "Handles incoming variable value.",
        new EpFunc1< Variable, double >( &Variable::setValue )
        );
    static Finfo * variableFinfos[] =
    {
        &value,
        &input
    };
    static string doc[] = {
        "Name", "Variable",
        "Author", "Subhasis Ray",
        "Description", "Variable for storing double values. This is used in Function class."
    };
    static Dinfo< Variable > dinfo;
    static Cinfo variableCinfo("Variable",
            Neutral::initCinfo(),
            variableFinfos,
            sizeof(variableFinfos) / sizeof(Finfo*),
            &dinfo,
            doc,
            sizeof(doc) / sizeof(string),
            true // is FieldElement, not to be created directly
            );
    return & variableCinfo;
}
References Cinfo::Cinfo(), DestFinfo::DestFinfo(), EpFunc1< T, A >::EpFunc1(), getValue(), Neutral::initCinfo(), setValue(), setValue(), and ValueFinfo< T, F >::ValueFinfo().
Referenced by Function::initCinfo().
ptr()
double * Variable::ptr () inline
Definition at line 57 of file Variable.h.
    {
        return &value_;
    }
References value_.
Referenced by Function::innerSetExpr().
setValue() [1/2]
void Variable::setValue (const Eref & e, double v) inline
Definition at line 42 of file Variable.h.
    {
        value_ = v;
    }
References value_.
Referenced by initCinfo().
setValue() [2/2]
void Variable::setValue (double v) inline
Definition at line 37 of file Variable.h.
    {
        value_ = v;
    }
References value_.
Referenced by initCinfo().
Member Data Documentation
name_
string Variable::name_ {"NONAME"} private
Definition at line 65 of file Variable.h.
{"NONAME"};
Referenced by getName(), Variable(), and Variable().
value_
double Variable::value_ {0.0} private
Definition at line 66 of file Variable.h.
{0.0};
Referenced by getValue(), ptr(), setValue(), setValue(), Variable(), and Variable().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/builtins/Variable.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/builtins/Variable.cpp