MOOSE - Multiscale Object Oriented Simulation Environment: ChanCommon Class Reference
ChanCommon Class Reference abstract
#include <ChanCommon.h>
Public Member Functions
ChanCommon ()
double getGbar () const
Utility function to acces Gbar.
double getVm () const
Utility function to access Vm.
void sendProcessMsgs (const Eref &e, const ProcPtr info)
void sendReinitMsgs (const Eref &e, const ProcPtr info)
void updateIk ()
double vGetEk (const Eref &e) const override
double vGetGbar (const Eref &e) const override
double vGetGk (const Eref &e) const override
double vGetIk (const Eref &e) const override
double vGetModulation (const Eref &e) const override
void vHandleVm (double Vm) override
void vSetEk (const Eref &e, double Ek) override
void vSetGbar (const Eref &e, double Gbar) override
void vSetGk (const Eref &e, double Gk) override
void vSetIk (const Eref &e, double Ic) override
void vSetModulation (const Eref &e, double modulation) override
virtual ~ChanCommon ()=0
Public Member Functions inherited from ChanBase
ChanBase ()
double getEk (const Eref &e) const
double getGbar (const Eref &e) const
double getGk (const Eref &e) const
double getIk (const Eref &e) const
double getModulation (const Eref &e) const
void handleVm (double Vm)
void process (const Eref &e, const ProcPtr info)
void reinit (const Eref &e, const ProcPtr info)
void setEk (const Eref &e, double Ek)
void setGbar (const Eref &e, double Gbar)
void setGk (const Eref &e, double Gk)
void setIk (const Eref &e, double Ic)
void setModulation (const Eref &e, double modulation)
virtual void vProcess (const Eref &e, const ProcPtr info)=0
virtual void vReinit (const Eref &e, const ProcPtr info)=0
virtual ~ChanBase ()=0
Static Public Member Functions
static const Cinfo * initCinfo ()
Specify the Class Info static variable for initialization.
Static Public Member Functions inherited from ChanBase
static SrcFinfo2< double, double > * channelOut ()
static SrcFinfo1< double > * IkOut ()
static const Cinfo * initCinfo ()
Specify the Class Info static variable for initialization.
static SrcFinfo1< double > * permeability ()
Protected Member Functions
double getModulation () const
Protected Attributes
double Vm_
Vm_ is input variable from compartment, used for most rates.
Private Attributes
double Ek_
Reversal potential of channel.
double Gbar_
Channel maximal conductance.
double Gk_
Channel actual conductance depending on opening of gates.
double Ik_
Channel current.
double modulation_
Channel modulation. Scales conductance.
Detailed Description
The ChanCommon.g handles the data fields for all ion channel classes in MOOSE, when they are using regular ee calculations rather than being zombified by the solver.
Definition at line 25 of file ChanCommon.h.
Constructor & Destructor Documentation
ChanCommon()
ChanCommon::ChanCommon ()
Definition at line 17 of file ChanCommon.cpp.
    :
    Vm_( 0.0 ),
    Gbar_( 0.0 ), modulation_( 1.0 ),
    Ek_( 0.0 ),
    Gk_( 0.0 ), Ik_( 0.0 )
{
    ;
}
References Ek_, Gbar_, Gk_, Ik_, modulation_, and Vm_.
~ChanCommon()
ChanCommon::~ChanCommon () pure virtual
Definition at line 27 of file ChanCommon.cpp.
{
    ;
}
Member Function Documentation
getGbar()
double ChanCommon::getGbar () const
Utility function to acces Gbar.
Definition at line 131 of file ChanCommon.cpp.
{
    return Gbar_;
}
References Gbar_.
Referenced by SynChan::normalizeGbar().
getModulation()
double ChanCommon::getModulation () const protected
Definition at line 56 of file ChanCommon.cpp.
{
    return modulation_;
}
References modulation_.
Referenced by SynChan::calcGk().
getVm()
double ChanCommon::getVm () const
Utility function to access Vm.
Definition at line 126 of file ChanCommon.cpp.
{
    return Vm_;
}
References Vm_.
initCinfo()
static const Cinfo * ChanCommon::initCinfo () static
Specify the Class Info static variable for initialization.
sendProcessMsgs()
void ChanCommon::sendProcessMsgs (const Eref & e, const ProcPtr info)
This function sends out the messages expected of a channel, after process. Used as a utility by various derived classes.
Definition at line 102 of file ChanCommon.cpp.
{
    ChanBase::channelOut()->send( e, Gk_, Ek_ );
    // This is used if the channel connects up to a conc pool and
    // handles influx of ions giving rise to a concentration change.
    ChanBase::IkOut()->send( e, Ik_ );
    // Needed by GHK-type objects
    ChanBase::permeability()->send( e, Gk_ );
}
References ChanBase::channelOut(), Ek_, Gk_, Ik_, ChanBase::IkOut(), ChanBase::permeability(), SrcFinfo2< T1, T2 >::send(), and SrcFinfo1< T >::send().
Referenced by MarkovChannel::vProcess(), Leakage::vProcess(), MgBlock::vProcess(), NMDAChan::vProcess(), SynChan::vProcess(), HHChannel::vProcess(), HHChannel2D::vProcess(), HHChannelF::vProcess(), and HHChannelF2D::vProcess().
sendReinitMsgs()
void ChanCommon::sendReinitMsgs (const Eref & e, const ProcPtr info)
Definition at line 113 of file ChanCommon.cpp.
{
    ChanBase::channelOut()->send( e, Gk_, Ek_ );
    ChanBase::IkOut()->send( e, Ik_ );
    // Needed by GHK-type objects
    ChanBase::permeability()->send( e, Gk_ );
}
References ChanBase::channelOut(), Ek_, Gk_, Ik_, ChanBase::IkOut(), ChanBase::permeability(), SrcFinfo2< T1, T2 >::send(), and SrcFinfo1< T >::send().
Referenced by MarkovChannel::vReinit(), Leakage::vReinit(), MgBlock::vReinit(), NMDAChan::vReinit(), SynChan::vReinit(), HHChannel::vReinit(), HHChannel2D::vReinit(), HHChannelF::vReinit(), and HHChannelF2D::vReinit().
updateIk()
void ChanCommon::updateIk ()
Utility function for a common computation using local variables
Definition at line 121 of file ChanCommon.cpp.
{
    Ik_ = ( Ek_ - Vm_ ) * Gk_;
}
References Ek_, Gk_, Ik_, and Vm_.
Referenced by MarkovChannel::vProcess(), Leakage::vProcess(), MgBlock::vProcess(), NMDAChan::vProcess(), SynChan::vProcess(), HHChannel::vProcess(), HHChannel2D::vProcess(), HHChannelF::vProcess(), HHChannelF2D::vProcess(), Leakage::vReinit(), HHChannel::vReinit(), HHChannel2D::vReinit(), HHChannelF::vReinit(), and HHChannelF2D::vReinit().
vGetEk()
double ChanCommon::vGetEk (const Eref & e) const override virtual
Implements ChanBase.
Reimplemented in ZombieHHChannel.
Definition at line 65 of file ChanCommon.cpp.
{
    return Ek_;
}
References Ek_.
Referenced by HHChannelBase::zombify().
vGetGbar()
double ChanCommon::vGetGbar (const Eref & e) const override virtual
Implements ChanBase.
Reimplemented in ZombieHHChannel.
Definition at line 41 of file ChanCommon.cpp.
{
    return Gbar_;
}
References Gbar_.
Referenced by Leakage::vProcess(), HHChannel::vProcess(), HHChannelF::vProcess(), Leakage::vReinit(), HHChannel::vReinit(), HHChannelF::vReinit(), and HHChannelBase::zombify().
vGetGk()
double ChanCommon::vGetGk (const Eref & e) const override virtual
Implements ChanBase.
Reimplemented in ZombieHHChannel.
Definition at line 74 of file ChanCommon.cpp.
{
    return Gk_;
}
References Gk_.
vGetIk()
double ChanCommon::vGetIk (const Eref & e) const override virtual
Implements ChanBase.
Reimplemented in ZombieHHChannel.
Definition at line 83 of file ChanCommon.cpp.
{
    return Ik_;
}
References Ik_.
vGetModulation()
double ChanCommon::vGetModulation (const Eref & e) const override virtual
Implements ChanBase.
Definition at line 51 of file ChanCommon.cpp.
{
    return modulation_;
}
References modulation_.
Referenced by Leakage::vProcess(), HHChannel::vProcess(), HHChannel2D::vProcess(), HHChannelF::vProcess(), HHChannelF2D::vProcess(), Leakage::vReinit(), HHChannel::vReinit(), HHChannel2D::vReinit(), HHChannelF::vReinit(), HHChannelF2D::vReinit(), and Leakage::vSetGbar().
vHandleVm()
void ChanCommon::vHandleVm (double Vm) override virtual
Assign the local Vm_ to the incoming Vm from the compartment
Implements ChanBase.
Reimplemented in ZombieHHChannel.
Definition at line 92 of file ChanCommon.cpp.
{
    Vm_ = Vm;
}
References Vm_.
vSetEk()
void ChanCommon::vSetEk (const Eref & e, double Ek) override virtual
Implements ChanBase.
Reimplemented in ZombieHHChannel.
Definition at line 61 of file ChanCommon.cpp.
{
    Ek_ = Ek;
}
References Ek_.
Referenced by HHChannelBase::zombify().
vSetGbar()
void ChanCommon::vSetGbar (const Eref & e, double Gbar) override virtual
Implements ChanBase.
Reimplemented in Leakage, SynChan, and ZombieHHChannel.
Definition at line 36 of file ChanCommon.cpp.
{
    Gbar_ = Gbar;
}
References Gbar_.
Referenced by Leakage::vSetGbar(), SynChan::vSetGbar(), and HHChannelBase::zombify().
vSetGk()
void ChanCommon::vSetGk (const Eref & e, double Gk) override virtual
Implements ChanBase.
Reimplemented in ZombieHHChannel.
Definition at line 70 of file ChanCommon.cpp.
{
    Gk_ = Gk;
}
References Gk_.
Referenced by Leakage::vProcess(), HHChannel::vProcess(), HHChannelF::vProcess(), Leakage::vReinit(), HHChannel::vReinit(), HHChannelF::vReinit(), and Leakage::vSetGbar().
vSetIk()
void ChanCommon::vSetIk (const Eref & e, double Ic) override virtual
Ik is read-only for MOOSE, but we provide the set func for derived classes to update it.
Implements ChanBase.
Reimplemented in ZombieHHChannel.
Definition at line 79 of file ChanCommon.cpp.
{
    Ik_ = Ik;
}
References Ik_.
vSetModulation()
void ChanCommon::vSetModulation (const Eref & e, double modulation) override virtual
Implements ChanBase.
Reimplemented in ZombieHHChannel.
Definition at line 46 of file ChanCommon.cpp.
{
    modulation_ = modulation;
}
References modulation_.
Referenced by ZombieHHChannel::vSetModulation().
Member Data Documentation
Ek_
double ChanCommon::Ek_ private
Reversal potential of channel.
Definition at line 96 of file ChanCommon.h.
Referenced by ChanCommon(), sendProcessMsgs(), sendReinitMsgs(), updateIk(), vGetEk(), and vSetEk().
Gbar_
double ChanCommon::Gbar_ private
Channel maximal conductance.
Definition at line 92 of file ChanCommon.h.
Referenced by ChanCommon(), getGbar(), vGetGbar(), and vSetGbar().
Gk_
double ChanCommon::Gk_ private
Channel actual conductance depending on opening of gates.
Definition at line 99 of file ChanCommon.h.
Referenced by ChanCommon(), sendProcessMsgs(), sendReinitMsgs(), updateIk(), vGetGk(), and vSetGk().
Ik_
double ChanCommon::Ik_ private
Channel current.
Definition at line 101 of file ChanCommon.h.
Referenced by ChanCommon(), sendProcessMsgs(), sendReinitMsgs(), updateIk(), vGetIk(), and vSetIk().
modulation_
double ChanCommon::modulation_ private
Channel modulation. Scales conductance.
Definition at line 94 of file ChanCommon.h.
Referenced by ChanCommon(), getModulation(), vGetModulation(), and vSetModulation().
Vm_
double ChanCommon::Vm_ protected
Vm_ is input variable from compartment, used for most rates.
Definition at line 88 of file ChanCommon.h.
Referenced by ChanCommon(), HHChannel2D::depValue(), HHChannelF2D::depValue(), getVm(), MarkovChannel::getVm(), MarkovChannel::setVm(), updateIk(), vHandleVm(), MgBlock::vProcess(), NMDAChan::vProcess(), HHChannel::vProcess(), HHChannelF::vProcess(), HHChannel::vReinit(), and HHChannelF::vReinit().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/biophysics/ChanCommon.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/biophysics/ChanCommon.cpp