MOOSE - Multiscale Object Oriented Simulation Environment: Interpol2D Class Reference
Interpol2D Class Reference
#include <Interpol2D.h>
Public Member Functions
void appendTableVector (const vector< vector< double > > &value)
void appendTableVector (vector< vector< double > > value)
double getDx () const
double getDy () const
double getInterpolatedValue (vector< double > xy) const
double getSy () const
double getTableValue (vector< unsigned int > index) const
vector< vector< double > > getTableVector () const
unsigned int getXdivs () const
double getXmax () const
double getXmin () const
unsigned int getYdivs () const
double getYmax () const
double getYmin () const
double indexWithoutCheck (double x, double y) const
double innerLookup (double x, double y) const
Interpol2D ()
Interpol2D (unsigned int xdivs, double xmin, double xmax, unsigned int ydivs, double ymin, double ymax)
double interpolate (double x, double y) const
double invDy () const
void load (const string &fname, unsigned int skiplines)
void lookup (double v1, double v2)
void lookupReturn (const Eref &e, double v1, double v2)
bool operator< (const Interpol2D &other) const
bool operator== (const Interpol2D &other) const
void print (const string &fname, bool doAppend) const
void resize (unsigned int xsize, unsigned int ysize, double init=0.0)
void setDx (double value)
void setDy (double value)
void setSy (double value)
void setTableValue (vector< unsigned int > index, double value)
void setTableVector (vector< vector< double > > value)
void setXdivs (unsigned int value)
void setXmax (double value)
void setXmin (double value)
void setYdivs (unsigned int value)
void setYmax (double value)
void setYmin (double value)
unsigned int xdivs () const
unsigned int ydivs () const
Static Public Member Functions
static const Cinfo * initCinfo ()
Static Public Attributes
static const unsigned int MAX_DIVS = 100000
Private Attributes
double invDx_
double invDy_
double sy_
vector< vector< double > > table_
double xmax_
double xmin_
double ymax_
double ymin_
Friends
istream & operator>> (istream &, Interpol2D &)
Detailed Description
2 Dimensional table, with interpolation. The internal vector is accessed like this: table_[ xIndex ][ yIndex ], with the x- and y-coordinates used as the first and second indices respectively.
Definition at line 18 of file Interpol2D.h.
Constructor & Destructor Documentation
Interpol2D() [1/2]
Interpol2D::Interpol2D ()
Definition at line 163 of file Interpol2D.cpp.
    :   xmin_( 0.0 ), xmax_( 1.0 ), invDx_( 1.0 ),
        ymin_( 0.0 ), ymax_( 1.0 ), invDy_( 1.0 ),
        sy_( 1.0 )
{
    table_.resize( 2 );
    table_[ 0 ].resize( 2, 0.0 );
    table_[ 1 ].resize( 2, 0.0 );
}
References invDx_, invDy_, sy_, table_, xmax_, xmin_, ymax_, and ymin_.
Referenced by MarkovRateTable::innerSetInt2dChildTable().
Interpol2D() [2/2]
Interpol2D::Interpol2D (unsigned int xdivs, double xmin, double xmax, unsigned int ydivs, double ymin, double ymax)
Definition at line 173 of file Interpol2D.cpp.
    :   xmin_( xmin ), xmax_( xmax ),
        ymin_( ymin ), ymax_( ymax ),
        sy_( 1.0 )
{
    resize( xdivs+1, ydivs+1 );
    if ( !doubleEq( xmax_, xmin ) )
        invDx_ = xdivs / ( xmax_ - xmin_);
    else
        invDx_ = 1.0;
    if ( !doubleEq( ymax_, ymin ) )
        invDy_ = ydivs / ( ymax_ - ymin_);
    else
        invDy_ = 1.0;
}
References doubleEq(), invDx_, invDy_, resize(), sy_, xmax_, xmin_, ymax_, and ymin_.
Member Function Documentation
appendTableVector() [1/2]
void Interpol2D::appendTableVector (const vector< vector< double > > & value)
Definition at line 648 of file Interpol2D.cpp.
{
    if ( value.empty() )
        return;
    unsigned int ysize = value[ 0 ].size();
    vector< vector< double > >::const_iterator i;
    for ( i = value.begin() + 1; i != value.end(); i++ )
        if ( i->size() != ysize ) {
            ysize = ~0u;
            break;
        }
    if ( ysize == ~0u ) {
        cerr <<
            "Error: Interpol2D::localAppendTableVector: All rows should have a "
            "uniform width. Not changing anything.\n";
        return;
    }
    if ( ! table_.empty() && ysize != table_[ 0 ].size() ) {
        cerr <<
            "Error: Interpol2D: localAppendTableVector: Table widths must match. "
            "Not changing anything.\n";
        return;
    }
    table_.insert( table_.end(), value.begin(), value.end() );
    invDx_ = xdivs() / ( xmax_ - xmin_ );
}
References invDx_, table_, xdivs(), xmax_, and xmin_.
appendTableVector() [2/2]
void Interpol2D::appendTableVector (vector< vector< double > > value)
getDx()
double Interpol2D::getDx () const
Definition at line 282 of file Interpol2D.cpp.
{
    if ( xdivs() == 0 )
        return 0.0;
    else
        return ( xmax_ - xmin_ ) / xdivs();
}
References xdivs(), xmax_, and xmin_.
Referenced by initCinfo().
getDy()
double Interpol2D::getDy () const
Definition at line 352 of file Interpol2D.cpp.
{
    if ( ydivs() == 0 )
        return 0.0;
    else
        return ( ymax_ - ymin_ ) / ydivs();
}
References ydivs(), ymax_, and ymin_.
Referenced by initCinfo().
getInterpolatedValue()
double Interpol2D::getInterpolatedValue (vector< double > xy) const
Definition at line 443 of file Interpol2D.cpp.
{
    double x, y;
    if (xy.size() < 2){
        x = xmin_;
        y = ymin_;
    } else {
        if (xy[0] < xmin_){
            x = xmin_;
        } else if (xy[0] > xmax_){
            x = xmax_;
        } else {
            x = xy[0];
        }
        if (xy[1] < ymin_){
            y = ymin_;
        } else if (xy[1] > ymax_){
            y = ymax_;
        } else {
            y = xy[1];
        }
    }
    return interpolate(x, y);
}
References interpolate(), xmax_, xmin_, ymax_, and ymin_.
Referenced by initCinfo().
getSy()
double Interpol2D::getSy () const
Definition at line 359 of file Interpol2D.cpp.
{
    return sy_;
}
References sy_.
getTableValue()
double Interpol2D::getTableValue (vector< unsigned int > index) const
Definition at line 402 of file Interpol2D.cpp.
{
    assert( index.size() == 2 );
    unsigned int i0 = index[ 0 ];
    unsigned int i1 = index[ 1 ];
    //Above-said modifications.
    if ( i0 >= table_.size() )
        i0 = table_.size() - 1;
    if ( i1 >= table_[i0].size() )
        i1 = table_[i0].size() - 1;
    return table_[ i0 ][ i1 ];
}
References table_.
Referenced by initCinfo(), and MarkovRateTable::lookup2dIndex().
getTableVector()
vector< vector< double > > Interpol2D::getTableVector () const
Definition at line 379 of file Interpol2D.cpp.
{
    return table_;
}
References table_.
Referenced by HHGate2D::getTableA(), HHGate2D::getTableB(), and initCinfo().
getXdivs()
unsigned int Interpol2D::getXdivs () const
Definition at line 262 of file Interpol2D.cpp.
{
    if ( table_.empty() )
        return 0;
    return table_.size() - 1;
}
References table_.
Referenced by HHGate2D::getXdivs(), initCinfo(), and MarkovSolverBase::setLookupParams().
getXmax()
double Interpol2D::getXmax () const
Definition at line 252 of file Interpol2D.cpp.
{
    return xmax_;
}
References xmax_.
Referenced by HHGate2D::getXmax(), initCinfo(), and MarkovSolverBase::setLookupParams().
getXmin()
double Interpol2D::getXmin () const
Definition at line 238 of file Interpol2D.cpp.
{
    return xmin_;
}
References xmin_.
Referenced by HHGate2D::getXmin(), initCinfo(), and MarkovSolverBase::setLookupParams().
getYdivs()
unsigned int Interpol2D::getYdivs () const
Definition at line 325 of file Interpol2D.cpp.
{
    if ( table_.size() > 0 )
        if ( table_[0].size() > 0 )
            return table_[0].size() - 1;
    return 0;
}
References table_.
Referenced by HHGate2D::getYdivs(), initCinfo(), and MarkovSolverBase::setLookupParams().
getYmax()
double Interpol2D::getYmax () const
Definition at line 316 of file Interpol2D.cpp.
{
    return ymax_;
}
References ymax_.
Referenced by HHGate2D::getYmax(), initCinfo(), and MarkovSolverBase::setLookupParams().
getYmin()
double Interpol2D::getYmin () const
Definition at line 302 of file Interpol2D.cpp.
{
    return ymin_;
}
References ymin_.
Referenced by HHGate2D::getYmin(), initCinfo(), and MarkovSolverBase::setLookupParams().
indexWithoutCheck()
double Interpol2D::indexWithoutCheck (double x, double y) const
Definition at line 489 of file Interpol2D.cpp.
{
    assert( table_.size() > 1 );
    unsigned long xInteger = static_cast< unsigned long >( ( x - xmin_ ) * invDx_ );
    assert( xInteger < table_.size() );
    unsigned long yInteger = static_cast< unsigned long >( ( y - ymin_ ) * invDy_ );
    assert( yInteger < table_[ 0 ].size() );
    return table_[ xInteger ][ yInteger ];
}
References invDx_, invDy_, table_, xmin_, and ymin_.
initCinfo()
const Cinfo * Interpol2D::initCinfo () static
Definition at line 25 of file Interpol2D.cpp.
{
    // Shared message definitions
    static DestFinfo lookup( "lookup",
        "Looks up table value based on indices v1 and v2, and sends"
        "value back using the 'lookupOut' message",
        new EpFunc2< Interpol2D, double, double >( &Interpol2D::lookupReturn )
    );
    static Finfo* lookupReturnShared[] =
    {
        lookupOut(), &lookup
    };
    static SharedFinfo lookupReturn2D( "lookupReturn2D",
        "This is a shared message for doing lookups on the table. "
        "Receives 2 doubles: x, y. "
        "Sends back a double with the looked-up z value.",
        lookupReturnShared, sizeof( lookupReturnShared ) / sizeof( Finfo * )
    );
    // Field definitions
    static ValueFinfo< Interpol2D, double > xmin( "xmin",
        "Minimum value for x axis of lookup table",
            &Interpol2D::setXmin,
            &Interpol2D::getXmin
        );
    static ValueFinfo< Interpol2D, double > xmax( "xmax",
        "Maximum value for x axis of lookup table",
            &Interpol2D::setXmax,
            &Interpol2D::getXmax
        );
    static ValueFinfo< Interpol2D, unsigned int > xdivs( "xdivs",
        "# of divisions on x axis of lookup table",
            &Interpol2D::setXdivs,
            &Interpol2D::getXdivs
        );
    static ValueFinfo< Interpol2D, double > dx( "dx",
        "Increment on x axis of lookup table",
            &Interpol2D::setDx,
            &Interpol2D::getDx
        );
    static ValueFinfo< Interpol2D, double > ymin( "ymin",
        "Minimum value for y axis of lookup table",
            &Interpol2D::setYmin,
            &Interpol2D::getYmin
        );
    static ValueFinfo< Interpol2D, double > ymax( "ymax",
        "Maximum value for y axis of lookup table",
            &Interpol2D::setYmax,
            &Interpol2D::getYmax
        );
    static ValueFinfo< Interpol2D, unsigned int > ydivs( "ydivs",
        "# of divisions on y axis of lookup table",
            &Interpol2D::setYdivs,
            &Interpol2D::getYdivs
        );
    static ValueFinfo< Interpol2D, double > dy( "dy",
        "Increment on y axis of lookup table",
            &Interpol2D::setDy,
            &Interpol2D::getDy
        );
    static LookupValueFinfo< Interpol2D, vector< unsigned int >, double >
        table( "table",
        "Lookup an entry on the table",
            &Interpol2D::setTableValue,
            &Interpol2D::getTableValue
        );
    static ValueFinfo< Interpol2D, vector< vector< double > > >
        tableVector2D( "tableVector2D",
        "Get the entire table.",
            &Interpol2D::setTableVector,
            &Interpol2D::getTableVector
        );
    static ReadOnlyLookupValueFinfo< Interpol2D, vector < double >, double >
        z("z",
          "Interpolated value for specified x and y. This is provided for"
          " debugging. Normally other objects will retrieve interpolated values"
          " via lookup message.",
          &Interpol2D::getInterpolatedValue);
    // MsgSrc definitions
    // MsgDest definitions
    static Finfo* interpol2DFinfos[] =
    {
        &lookupReturn2D,    // Shared
        &xmin,              // Value
        &xmax,              // Value
        &xdivs,             // Value
        &dx,                // Value
        &ymin,              // Value
        &ymax,              // Value
        &ydivs,             // Value
        &dy,                // Value
        &table,             // Lookup
        &z,                 // Lookup
        &tableVector2D,     // Value
    };
    static string doc[] =
    {
        "Name", "Interpol2D",
        "Author", "Niraj Dudani, 2009, NCBS",
        "Description", "Interpol2D: Interpolation class. "
                "Handles lookup from a 2-dimensional grid of real-numbered values. "
                "Returns 'z' value based on given 'x' and 'y' values. "
                "Can either use interpolation or roundoff to the nearest index.",
    };
    static Dinfo< Interpol2D > dinfo;
    static Cinfo interpol2DCinfo(
        "Interpol2D",
        Neutral::initCinfo(),
        interpol2DFinfos, sizeof( interpol2DFinfos ) / sizeof( Finfo * ),
        &dinfo,
                doc,
                sizeof(doc)/sizeof(string)
    );
    return &interpol2DCinfo;
}
References Cinfo::Cinfo(), DestFinfo::DestFinfo(), EpFunc2< T, A1, A2 >::EpFunc2(), getDx(), getDy(), getInterpolatedValue(), getTableValue(), getTableVector(), getXdivs(), getXmax(), getXmin(), getYdivs(), getYmax(), getYmin(), Neutral::initCinfo(), lookupOut(), lookupReturn(), LookupValueFinfo< T, L, F >::LookupValueFinfo(), ReadOnlyLookupValueFinfo< T, L, F >::ReadOnlyLookupValueFinfo(), setDx(), setDy(), setTableValue(), setTableVector(), setXdivs(), setXmax(), setXmin(), setYdivs(), setYmax(), setYmin(), SharedFinfo::SharedFinfo(), and ValueFinfo< T, F >::ValueFinfo().
innerLookup()
double Interpol2D::innerLookup (double x, double y) const
Definition at line 574 of file Interpol2D.cpp.
{
    if ( table_.size() == 0 )
        return 0.0;
    if ( x < xmin_ ) {
        x = xmin_;
    }
    if ( x > xmax_ ) {
        x = xmax_;
    }
    if ( y < ymin_ ) {
        y = ymin_;
    }
    if ( y > ymax_ ) {
        y = ymax_;
    }
    return interpolate( x, y );
}
References interpolate(), table_, xmax_, xmin_, ymax_, and ymin_.
Referenced by MarkovRateTable::lookup2dValue(), HHGate2D::lookupA(), HHGate2D::lookupB(), HHGate2D::lookupBoth(), and lookupReturn().
interpolate()
double Interpol2D::interpolate (double x, double y) const
Performs bi-linear interpolation.
Modified by Vishaka Datta S, 2011, NCBS. Interpolation now performs bounds checking.
Definition at line 508 of file Interpol2D.cpp.
{
    bool isEndOfX = false;
    bool isEndOfY = false;
    double z00=0.0, z01=0.0, z10=0.0, z11=0.0;
    assert( table_.size() > 1 );
    double xv = ( x - xmin_ ) * invDx_;
    unsigned long xInteger = static_cast< unsigned long >(xv);
    if (xInteger >= table_.size()){
        xInteger = table_.size() - 1;
    }
    if (xInteger == table_.size() - 1){
        isEndOfX = true;
    }
    assert(xInteger >= 0);
    double xFraction = xv - xInteger;
    double yv = ( y - ymin_ ) * invDy_;
    unsigned long yInteger = static_cast< unsigned long >(yv);
    if (yInteger >= table_[xInteger].size()){
        yInteger = table_[xInteger].size() - 1;
    }
    assert(yInteger >= 0);
    if (yInteger == table_[xInteger].size() - 1){
        isEndOfY = true;
    }
    double yFraction = yv - yInteger;
    double xFyF = xFraction * yFraction;
    //If the value being looked up is at the boundary, we dont want to read past
    //the boundary for the x interpolation.
    // vector< vector< double > >::const_iterator iz0 = table_.begin() + xInteger;
    // vector< double >::const_iterator iz00 = iz0->begin() + yInteger;
    // vector< double >::const_iterator iz10;
    /* The following is the same as:
            double z00 = table_[ xInteger ][ yInteger ];
            double z01 = table_[ xInteger ][ yInteger + 1 ];
            double z10 = table_[ xInteger + 1 ][ yInteger ];
            double z11 = table_[ xInteger + 1 ][ yInteger + 1 ];
    */
    z00 = table_[xInteger][yInteger];
    if (!isEndOfX){
        z10 = table_[xInteger+1][yInteger];
        if (!isEndOfY){
            z11 = table_[xInteger+1][yInteger+1];
            z01 = table_[xInteger][yInteger+1];
        }
    } else if (!isEndOfY){
        z01 = table_[xInteger][yInteger+1];
    }
    /* The following is the same as:
            return (
                z00 * ( 1 - xFraction ) * ( 1 - yFraction ) +
                z10 * xFraction * ( 1 - yFraction ) +
                z01 * ( 1 - xFraction ) * yFraction +
                z11 * xFraction * yFraction );
    */
    return (
        z00 * ( 1 - xFraction - yFraction + xFyF ) +
        z10 * ( xFraction - xFyF ) +
        z01 * ( yFraction - xFyF ) +
        z11 * xFyF );
}
References invDx_, invDy_, table_, xmin_, and ymin_.
Referenced by getInterpolatedValue(), and innerLookup().
invDy()
double Interpol2D::invDy () const inline
Definition at line 76 of file Interpol2D.h.
{
            return invDy_;
        }
References invDy_.
load()
void Interpol2D::load (const string & fname, unsigned int skiplines)
Definition at line 699 of file Interpol2D.cpp.
{
    // Checking if xdivs/ydivs are different from default values. If they are,
    // then issue a warning.
    if ( xdivs() != 1 || ydivs() != 1 )
        cerr << "Warning: Interpol2D::innerLoad: Loading 2-D table from '" <<
            fname << "'. " <<
            "'xdivs' and 'ydivs' need not be specified. If you have set these fields, "
            "then they will be overridden while loading.\n";
    vector< double >::iterator i;
    std::ifstream fin( fname.c_str() );
    string line;
    if ( fin.good() ) {
        unsigned int i;
        for ( i = 0; i < skiplines; i++ ) {
                  if ( fin.good () ){
                    getline( fin, line );
                    line = moose::trim(line);
                  } else {
                    break;
                  }
        }
        if ( !fin.good() )
            return;
        table_.clear( );
        unsigned int lastWidth = ~0u;
        double y;
        while( fin.good() ) {
            table_.resize( table_.size() + 1 );
            getline( fin, line );
                        line = moose::trim(line);
            istringstream sstream( line );
            while( sstream >> y )
                table_.back().push_back( y );
            /*
             * In case the last line of a file is blank.
             */
            if ( table_.back().empty() ) {
                table_.pop_back();
                break;
            }
            if ( lastWidth != ~0u &&
                 table_.back().size() != lastWidth )
            {
                cerr << "Error: Interpol2D::innerLoad: " <<
                    "In file " << fname <<
                    ", line " << table_.size() <<
                    ", row widths are not uniform! Will stop loading now.\n";
                table_.clear();
                return;
            }
            lastWidth = table_.back().size();
        }
        invDx_ = xdivs() / ( xmax_ - xmin_ );
        invDy_ = ydivs() / ( ymax_ - ymin_ );
    } else {
        cerr << "Error: Interpol2D::innerLoad: Failed to open file " <<
            fname << endl;
    }
}
References invDx_, invDy_, table_, moose::trim(), xdivs(), xmax_, xmin_, ydivs(), ymax_, and ymin_.
lookup()
void Interpol2D::lookup (double v1, double v2)
lookupReturn()
void Interpol2D::lookupReturn (const Eref & e, double v1, double v2)
Looks up table value based on indices v1 and v2, and sends value back on the 'lookupOut' message.
lookupReturn uses its argument to do an interpolating lookup of the table. It sends a return message to the originating object with the looked up value. This should be avoided, instead use the fastGet function.
Definition at line 478 of file Interpol2D.cpp.
{
    double ret = innerLookup( v1, v2 );
    lookupOut()->send( e, ret );
}
References innerLookup(), lookupOut(), and SrcFinfo1< T >::send().
Referenced by initCinfo().
operator<()
bool Interpol2D::operator< (const Interpol2D & other) const
Definition at line 604 of file Interpol2D.cpp.
{
    if ( table_.size() < other.table_.size() )
        return 1;
    if ( table_.size() > other.table_.size() )
        return 0;
    for ( unsigned int i = 0; i < table_.size(); i++ ) {
        for ( unsigned int j = 0; j < table_[ i ].size(); j++ ) {
            if ( table_[ i ][ j ] < other.table_[ i ][ j ] )
                return 1;
            if ( table_[ i ][ j ] > other.table_[ i ][ j ] )
                return 0;
        }
    }
    return 0;
}
References table_.
operator==()
bool Interpol2D::operator== (const Interpol2D & other) const
Definition at line 594 of file Interpol2D.cpp.
{
    return (
        xmin_ == other.xmin_ &&
        xmax_ == other.xmax_ &&
        ymin_ == other.ymin_ &&
        ymax_ == other.ymax_ &&
        table_ == other.table_ );
}
References table_, xmax_, xmin_, ymax_, and ymin_.
print()
void Interpol2D::print (const string & fname, bool doAppend) const
Definition at line 680 of file Interpol2D.cpp.
{
    std::ofstream fout;
    if ( appendFlag )
        fout.open( fname.c_str(), std::ios::app );
    else
        fout.open( fname.c_str(), std::ios::trunc );
    vector< vector< double > >::const_iterator i;
    vector< double >::const_iterator j;
    for ( i = table_.begin(); i != table_.end(); i++ ) {
        for ( j = i->begin(); j != i->end(); j++ )
            fout << *j << "\t";
        fout << "\n";
    }
    fout.close();
}
References table_.
resize()
void Interpol2D::resize (unsigned int xsize, unsigned int ysize, double init = 0.0)
Resizes 2-D vector. If either argument is zero, it remains unchanged
Definition at line 200 of file Interpol2D.cpp.
{
    unsigned int oldx = table_.size();
    unsigned int oldy = 0;
    if ( oldx > 0 )
        oldy = table_[0].size();
    if ( xsize == 0 ) xsize = oldx;
    if ( ysize == 0 ) ysize = oldy;
    if ( xsize != oldx ) {
        table_.resize( xsize );
        if ( xsize > oldx ) {
            for ( unsigned int i = oldx; i < xsize; ++i )
                table_[i].resize( ysize, init );
        }
    }
    if ( ysize != oldy ) {
        for ( unsigned int i = 0; i < xsize; ++i )
            table_[i].resize( ysize, init );
    }
    invDx_ = xdivs() / ( xmax_ - xmin_ );
    invDy_ = ydivs() / ( ymax_ - ymin_ );
}
References invDx_, invDy_, table_, xdivs(), xmax_, xmin_, ydivs(), ymax_, and ymin_.
Referenced by Interpol2D(), setDx(), setXdivs(), and setYdivs().
setDx()
void Interpol2D::setDx (double value)
Definition at line 268 of file Interpol2D.cpp.
{
    if ( !doubleEq( value, 0.0 ) ) {
        unsigned int xdivs = static_cast< unsigned int >(
            0.5 + fabs( xmax_ - xmin_ ) / value );
        if ( xdivs < 1 || xdivs > MAX_DIVS ) {
            cerr <<
                "Error: Interpol2D::localSetDx Out of range:" <<
                xdivs + 1 << " entries in table.\n";
                return;
        }
        resize( xdivs + 1, 0 );
    }
}
References doubleEq(), MAX_DIVS, resize(), xmax_, and xmin_.
Referenced by initCinfo().
setDy()
void Interpol2D::setDy (double value)
Definition at line 336 of file Interpol2D.cpp.
{
    if ( !doubleEq( value, 0.0 ) ) {
        unsigned int ydivs = static_cast< unsigned int >(
            0.5 + fabs( ymax_ - ymin_ ) / value );
        if ( ydivs < 1 || ydivs > MAX_DIVS ) {
            cerr <<
                "Error: Interpol2D::localSetDy Out of range:" <<
                ydivs + 1 << " entries in table.\n";
                return;
        }
        setYdivs( ydivs );
        invDy_ = ydivs / ( ymax_ - ymin_ );
    }
}
References doubleEq(), invDy_, MAX_DIVS, setYdivs(), ymax_, and ymin_.
Referenced by initCinfo().
setSy()
void Interpol2D::setSy (double value)
Definition at line 364 of file Interpol2D.cpp.
{
    if ( !doubleEq( value, 0.0 ) ) {
        double ratio = value / sy_;
        vector< vector< double > >::iterator i;
        vector< double >::iterator j;
        for ( i = table_.begin(); i != table_.end(); i++ )
            for ( j = i->begin(); j != i->end(); j++ )
                *j *= ratio;
        sy_ = value;
    } else {
        cerr << "Error: Interpol2D::localSetSy: sy too small:" <<
            value << "\n";
    }
}
References doubleEq(), sy_, and table_.
setTableValue()
void Interpol2D::setTableValue (vector< unsigned int > index, double value)
Definition at line 384 of file Interpol2D.cpp.
{
    assert( index.size() == 2 );
    unsigned int i0 = index[ 0 ];
    unsigned int i1 = index[ 1 ];
    if ( i0 < table_.size() && i1 < table_[ 0 ].size() )
        table_[ i0 ][ i1 ] = value;
    else
        cerr << "Error: Interpol2D::setTableValue: Index out of bounds!\n";
}
References table_.
Referenced by initCinfo().
setTableVector()
void Interpol2D::setTableVector (vector< vector< double > > value)
Definition at line 420 of file Interpol2D.cpp.
{
    table_ = value;
    invDx_ = xdivs() / ( xmax_ - xmin_ );
    invDy_ = ydivs() / ( ymax_ - ymin_ );
}
References invDx_, invDy_, table_, xdivs(), xmax_, xmin_, ydivs(), ymax_, and ymin_.
Referenced by initCinfo(), HHGate2D::setTableA(), and HHGate2D::setTableB().
setXdivs()
void Interpol2D::setXdivs (unsigned int value)
Definition at line 257 of file Interpol2D.cpp.
{
        resize( value + 1, 0 );
}
References resize().
Referenced by initCinfo(), and HHGate2D::setXdivs().
setXmax()
void Interpol2D::setXmax (double value)
Definition at line 243 of file Interpol2D.cpp.
{
    if ( !doubleApprox( xmin_, value ) ) {
        xmax_ = value;
        invDx_ = xdivs() / ( xmax_ - xmin_ );
    } else {
        cerr << "Error: Interpol2D::setXmax: Xmin ~= Xmax : Assignment failed\n";
    }
}
References doubleApprox(), invDx_, xdivs(), xmax_, and xmin_.
Referenced by initCinfo(), and HHGate2D::setXmax().
setXmin()
void Interpol2D::setXmin (double value)
Definition at line 229 of file Interpol2D.cpp.
{
    if ( !doubleApprox( xmax_, value ) ) {
        xmin_ = value;
        invDx_ = xdivs() / ( xmax_ - xmin_ );
    } else {
        cerr << "Error: Interpol2D::setXmin: Xmin ~= Xmax : Assignment failed\n";
    }
}
References doubleApprox(), invDx_, xdivs(), xmax_, and xmin_.
Referenced by initCinfo(), and HHGate2D::setXmin().
setYdivs()
void Interpol2D::setYdivs (unsigned int value)
Definition at line 321 of file Interpol2D.cpp.
{
    resize( 0, value + 1 );
}
References resize().
Referenced by initCinfo(), setDy(), and HHGate2D::setYdivs().
setYmax()
void Interpol2D::setYmax (double value)
Definition at line 307 of file Interpol2D.cpp.
{
    if ( !doubleApprox( ymin_, value ) ) {
        ymax_ = value;
        invDy_ = ydivs() / ( ymax_ - ymin_ );
    } else {
        cerr << "Error: Interpol2D::setYmax: Ymin ~= Ymax : Assignment failed\n";
    }
}
References doubleApprox(), invDy_, ydivs(), ymax_, and ymin_.
Referenced by initCinfo(), and HHGate2D::setYmax().
setYmin()
void Interpol2D::setYmin (double value)
Definition at line 293 of file Interpol2D.cpp.
{
    if ( !doubleApprox( ymax_, value ) ) {
        ymin_ = value;
        invDy_ = ydivs() / ( ymax_ - ymin_ );
    } else {
        cerr << "Error: Interpol2D::setYmin: Ymin ~= Ymax : Assignment failed\n";
    }
}
References doubleApprox(), invDy_, ydivs(), ymax_, and ymin_.
Referenced by initCinfo(), and HHGate2D::setYmin().
xdivs()
unsigned int Interpol2D::xdivs () const
Definition at line 427 of file Interpol2D.cpp.
{
    if ( table_.empty() )
        return 0;
    return table_.size() - 1;
}
References table_.
Referenced by appendTableVector(), getDx(), load(), resize(), setTableVector(), setXmax(), and setXmin().
ydivs()
unsigned int Interpol2D::ydivs () const
Definition at line 434 of file Interpol2D.cpp.
{
    if ( table_.empty() || table_[0].empty() )
        return 0;
    return table_[0].size() - 1;
}
References table_.
Referenced by getDy(), load(), resize(), setTableVector(), setYmax(), and setYmin().
Friends And Related Symbol Documentation
operator>>
istream & operator>> (istream & , Interpol2D &) friend
Referenced by operator>>().
Member Data Documentation
invDx_
double Interpol2D::invDx_ private
Definition at line 105 of file Interpol2D.h.
Referenced by appendTableVector(), indexWithoutCheck(), Interpol2D(), Interpol2D(), interpolate(), load(), operator>>(), resize(), setTableVector(), setXmax(), and setXmin().
invDy_
double Interpol2D::invDy_ private
Definition at line 108 of file Interpol2D.h.
Referenced by indexWithoutCheck(), Interpol2D(), Interpol2D(), interpolate(), invDy(), load(), operator>>(), resize(), setDy(), setTableVector(), setYmax(), and setYmin().
MAX_DIVS
const unsigned int Interpol2D::MAX_DIVS = 100000 static
Definition at line 101 of file Interpol2D.h.
Referenced by setDx(), and setDy().
sy_
double Interpol2D::sy_ private
Definition at line 109 of file Interpol2D.h.
Referenced by getSy(), Interpol2D(), Interpol2D(), and setSy().
table_
vector< vector< double > > Interpol2D::table_ private
Definition at line 110 of file Interpol2D.h.
Referenced by appendTableVector(), getTableValue(), getTableVector(), getXdivs(), getYdivs(), indexWithoutCheck(), innerLookup(), Interpol2D(), interpolate(), load(), operator<(), operator==(), operator>>(), print(), resize(), setSy(), setTableValue(), setTableVector(), xdivs(), and ydivs().
xmax_
double Interpol2D::xmax_ private
Definition at line 104 of file Interpol2D.h.
Referenced by appendTableVector(), getDx(), getInterpolatedValue(), getXmax(), innerLookup(), Interpol2D(), Interpol2D(), load(), operator==(), operator>>(), resize(), setDx(), setTableVector(), setXmax(), and setXmin().
xmin_
double Interpol2D::xmin_ private
Definition at line 103 of file Interpol2D.h.
Referenced by appendTableVector(), getDx(), getInterpolatedValue(), getXmin(), indexWithoutCheck(), innerLookup(), Interpol2D(), Interpol2D(), interpolate(), load(), operator==(), operator>>(), resize(), setDx(), setTableVector(), setXmax(), and setXmin().
ymax_
double Interpol2D::ymax_ private
Definition at line 107 of file Interpol2D.h.
Referenced by getDy(), getInterpolatedValue(), getYmax(), innerLookup(), Interpol2D(), Interpol2D(), load(), operator==(), operator>>(), resize(), setDy(), setTableVector(), setYmax(), and setYmin().
ymin_
double Interpol2D::ymin_ private
Definition at line 106 of file Interpol2D.h.
Referenced by getDy(), getInterpolatedValue(), getYmin(), indexWithoutCheck(), innerLookup(), Interpol2D(), Interpol2D(), interpolate(), load(), operator==(), operator>>(), resize(), setDy(), setTableVector(), setYmax(), and setYmin().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/builtins/Interpol2D.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/builtins/Interpol2D.cpp