MOOSE - Multiscale Object Oriented Simulation Environment: SrcFinfo5< T1, T2, T3, T4, T5 > Class Template Reference
SrcFinfo5< T1, T2, T3, T4, T5 > Class Template Reference
#include <SrcFinfo.h>
Public Member Functions
string rttiType () const
void send (const Eref &e, const T1 &arg1, const T2 &arg2, const T3 &arg3, const T4 &arg4, const T5 &arg5) const
void sendBuffer (const Eref &e, double *buf) const
SrcFinfo5 (const string &name, const string &doc)
~SrcFinfo5 ()
Public Member Functions inherited from SrcFinfo
bool addMsg (const Finfo *target, ObjId mid, Element *src) const
bool checkTarget (const Finfo *target) const
BindIndex getBindIndex () const
void registerFinfo (Cinfo *c)
void setBindIndex (BindIndex b)
SrcFinfo (const string &name, const string &doc)
bool strGet (const Eref &tgt, const string &field, string &returnValue) const
bool strSet (const Eref &tgt, const string &field, const string &arg) const
~SrcFinfo ()
Public Member Functions inherited from Finfo
const string & docs () const
Returns documentation string.
Finfo (const string &name, const string &doc)
virtual vector< string > innerDest () const
virtual vector< string > innerSrc () const
const string & name () const
virtual void postCreationFunc (Id newId, Element *newElm) const
virtual ~Finfo ()
Additional Inherited Members
Static Public Member Functions inherited from Finfo
static const Cinfo * initCinfo ()
Static Public Attributes inherited from SrcFinfo
static const BindIndex BadBindIndex = 65535
Detailed Description
template<class T1, class T2, class T3, class T4, class T5>
class SrcFinfo5< T1, T2, T3, T4, T5 >
Definition at line 393 of file SrcFinfo.h.
Constructor & Destructor Documentation
~SrcFinfo5()
template<class T1 , class T2 , class T3 , class T4 , class T5 > SrcFinfo5< T1, T2, T3, T4, T5 >::~SrcFinfo5 () inline
Definition at line 396 of file SrcFinfo.h.
{;}
SrcFinfo5()
template<class T1 , class T2 , class T3 , class T4 , class T5 > SrcFinfo5< T1, T2, T3, T4, T5 >::SrcFinfo5 (const string & name, const string & doc) inline
Definition at line 398 of file SrcFinfo.h.
            : SrcFinfo( name, doc )
            { ; }
Referenced by remeshOut().
Member Function Documentation
rttiType()
template<class T1 , class T2 , class T3 , class T4 , class T5 > string SrcFinfo5< T1, T2, T3, T4, T5 >::rttiType () const inline virtual
Returns the documentation string for the Finfo string docs() const; Returns the RTTI type string for the finfo by referring to an internal virtual function. string type() const; Returns the list of subsidiary SrcFinfos. Used in Shared Finfos, empty otherwise. Goes via internal virtual function. vector< string > src() const; Returns the list of subsidiary destFinfos. Used in SharedFinfos and ValueFinfos, empty otherwise. Goes via internal virtual function. vector< string > dest() const; Returns an RTTI type string for this Finfo.
Reimplemented from Finfo.
Definition at line 439 of file SrcFinfo.h.
{
            return Conv<T1>::rttiType() + "," + Conv< T2 >::rttiType() +
                "," + Conv<T3>::rttiType() + "," + Conv< T4 >::rttiType() +
                "," + Conv<T5>::rttiType();
        }
send()
template<class T1 , class T2 , class T3 , class T4 , class T5 > void SrcFinfo5< T1, T2, T3, T4, T5 >::send (const Eref & e, const T1 & arg1, const T2 & arg2, const T3 & arg3, const T4 & arg4, const T5 & arg5) const inline
Definition at line 403 of file SrcFinfo.h.
        {
            const vector< MsgDigest >& md = e.msgDigest( getBindIndex() );
            for ( vector< MsgDigest >::const_iterator
                i = md.begin(); i != md.end(); ++i ) {
                const OpFunc5Base< T1, T2, T3, T4, T5 >* f =
                    dynamic_cast<
                    const OpFunc5Base< T1, T2, T3, T4, T5 >* >( i->func );
                assert( f );
                for ( vector< Eref >::const_iterator
                    j = i->targets.begin(); j != i->targets.end(); ++j ) {
                    if ( j->dataIndex() == ALLDATA ) {
                        Element* e = j->element();
                        unsigned int start = e->localDataStart();
                        unsigned int end = start + e->numData();
                        for ( unsigned int k = start; k < end; ++k )
                            f->op( Eref( e, k ),
                                            arg1, arg2, arg3, arg4, arg5 );
                    } else  {
                        f->op( *j, arg1, arg2, arg3, arg4, arg5 );
                    }
                }
            }
        }
References ALLDATA, Eref::dataIndex(), Eref::element(), Eref::Eref(), MsgDigest::func, SrcFinfo::getBindIndex(), Element::localDataStart(), Eref::msgDigest(), Element::numData(), and MsgDigest::targets.
Referenced by SrcFinfo5< T1, T2, T3, T4, T5 >::sendBuffer(), and MeshEntry::triggerRemesh().
sendBuffer()
template<class T1 , class T2 , class T3 , class T4 , class T5 > void SrcFinfo5< T1, T2, T3, T4, T5 >::sendBuffer (const Eref & e, double * buf) const inline virtual
Sends contents of buffer on to msg targets Buffer has a header with the TgtInfo.
Implements SrcFinfo.
Definition at line 430 of file SrcFinfo.h.
        {
            const T1& arg1 = Conv< T1 >::buf2val( &buf );
            const T2& arg2 = Conv< T2 >::buf2val( &buf );
            const T3& arg3 = Conv< T3 >::buf2val( &buf );
            const T4& arg4 = Conv< T4 >::buf2val( &buf );
            send( e, arg1, arg2, arg3, arg4, Conv< T5 >::buf2val( &buf ) );
        }
References SrcFinfo5< T1, T2, T3, T4, T5 >::send().
The documentation for this class was generated from the following file:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/basecode/SrcFinfo.h