MOOSE - Multiscale Object Oriented Simulation Environment: OpFunc4< T, A1, A2, A3, A4 > Class Template Reference
OpFunc4< T, A1, A2, A3, A4 > Class Template Reference
#include <OpFunc.h>
Public Member Functions
void op (const Eref &e, A1 arg1, A2 arg2, A3 arg3, A4 arg4) const
OpFunc4 (void(T::*func)(A1, A2, A3, A4))
Public Member Functions inherited from OpFunc4Base< A1, A2, A3, A4 >
bool checkFinfo (const Finfo *s) const
const OpFunc * makeHopFunc (HopIndex hopIndex) const
void opBuffer (const Eref &e, double *buf) const
Executes the OpFunc by converting args.
string rttiType () const
Public Member Functions inherited from OpFunc
OpFunc ()
unsigned int opIndex () const
virtual void opVecBuffer (const Eref &e, double *buf) const
Executes the OpFunc for all data by converting a vector of args.
bool setIndex (unsigned int i)
Used when rebuilding the Fid->OpFunc mapping.
virtual ~OpFunc ()
Private Attributes
void(T::* func_)(A1, A2, A3, A4)
Additional Inherited Members
Static Public Member Functions inherited from OpFunc
static const OpFunc * lookop (unsigned int opIndex)
static unsigned int rebuildOpIndex ()
cleans out the entire Ops vector. Returns size of orig vector.
Detailed Description
template<class T, class A1, class A2, class A3, class A4>
class OpFunc4< T, A1, A2, A3, A4 >
Definition at line 74 of file OpFunc.h.
Constructor & Destructor Documentation
OpFunc4()
template<class T , class A1 , class A2 , class A3 , class A4 > OpFunc4< T, A1, A2, A3, A4 >::OpFunc4 (void(T::*)(A1, A2, A3, A4) func) inline
Definition at line 78 of file OpFunc.h.
        : func_( func )
    {;}
References OpFunc4< T, A1, A2, A3, A4 >::func_.
Referenced by MarkovRateTable::initCinfo(), TableBase::initCinfo(), and CubeMesh::initCinfo().
Member Function Documentation
op()
template<class T , class A1 , class A2 , class A3 , class A4 > void OpFunc4< T, A1, A2, A3, A4 >::op (const Eref & e, A1 arg1, A2 arg2, A3 arg3, A4 arg4) const inline virtual
Implements OpFunc4Base< A1, A2, A3, A4 >.
Definition at line 82 of file OpFunc.h.
    {
        (reinterpret_cast< T* >( e.data() )->*func_)(
            arg1, arg2, arg3, arg4 );
    }
References Eref::data(), and OpFunc4< T, A1, A2, A3, A4 >::func_.
Member Data Documentation
func_
template<class T , class A1 , class A2 , class A3 , class A4 > void(T::* OpFunc4< T, A1, A2, A3, A4 >::func_) (A1, A2, A3, A4) private
Definition at line 89 of file OpFunc.h.
Referenced by OpFunc4< T, A1, A2, A3, A4 >::op(), and OpFunc4< T, A1, A2, A3, A4 >::OpFunc4().
The documentation for this class was generated from the following file:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/basecode/OpFunc.h