MOOSE - Multiscale Object Oriented Simulation Environment: OpFunc2Base< A1, A2 > Class Template Reference
OpFunc2Base< A1, A2 > Class Template Reference abstract
#include <OpFuncBase.h>
Public Member Functions
bool checkFinfo (const Finfo *s) const
const OpFunc * makeHopFunc (HopIndex hopIndex) const
virtual void op (const Eref &e, A1 arg1, A2 arg2) const =0
void opBuffer (const Eref &e, double *buf) const
Executes the OpFunc by converting args.
virtual void opVec (const Eref &e, const vector< A1 > &arg1, const vector< A2 > &arg2, const OpFunc2Base< A1, A2 > *op) const
void opVecBuffer (const Eref &e, double *buf) const
Executes the OpFunc for all data by converting a vector of args.
string rttiType () const
Public Member Functions inherited from OpFunc
OpFunc ()
unsigned int opIndex () const
bool setIndex (unsigned int i)
Used when rebuilding the Fid->OpFunc mapping.
virtual ~OpFunc ()
Additional Inherited Members
Static Public Member Functions inherited from OpFunc
static const OpFunc * lookop (unsigned int opIndex)
static unsigned int rebuildOpIndex ()
cleans out the entire Ops vector. Returns size of orig vector.
Detailed Description
template<class A1, class A2>
class OpFunc2Base< A1, A2 >
Definition at line 159 of file OpFuncBase.h.
Member Function Documentation
checkFinfo()
template<class A1 , class A2 > bool OpFunc2Base< A1, A2 >::checkFinfo (const Finfo * s) const inline virtual
Implements OpFunc.
Definition at line 162 of file OpFuncBase.h.
    {
        return dynamic_cast< const SrcFinfo2< A1, A2 >* >( s );
    }
makeHopFunc()
template<class A1 , class A2 > const OpFunc * OpFunc2Base< A1, A2 >::makeHopFunc (HopIndex hopIndex) const virtual
Implements OpFunc.
Definition at line 269 of file HopFunc.h.
{
    return new HopFunc2< A1, A2 >( hopIndex );
}
op()
template<class A1 , class A2 > virtual void OpFunc2Base< A1, A2 >::op (const Eref & e, A1 arg1, A2 arg2) const pure virtual
Implemented in EpFunc2< T, A1, A2 >, HopFunc2< A1, A2 >, and OpFunc2< T, A1, A2 >.
Referenced by OpFunc2Base< A1, A2 >::opBuffer(), and OpFunc2Base< A1, A2 >::opVecBuffer().
opBuffer()
template<class A1 , class A2 > void OpFunc2Base< A1, A2 >::opBuffer (const Eref & e, double * buf) const inline virtual
Executes the OpFunc by converting args.
Implements OpFunc.
Definition at line 172 of file OpFuncBase.h.
    {
        const A1& arg1 = Conv< A1 >::buf2val( &buf );
        op( e,
            arg1, Conv< A2 >::buf2val( &buf ) );
    }
References OpFunc2Base< A1, A2 >::op().
opVec()
template<class A1 , class A2 > virtual void OpFunc2Base< A1, A2 >::opVec (const Eref & e, const vector< A1 > & arg1, const vector< A2 > & arg2, const OpFunc2Base< A1, A2 > * op) const inline virtual
Definition at line 201 of file OpFuncBase.h.
    { ; } // overridden in HopFuncs.
opVecBuffer()
template<class A1 , class A2 > void OpFunc2Base< A1, A2 >::opVecBuffer (const Eref & e, double * buf) const inline virtual
Executes the OpFunc for all data by converting a vector of args.
Reimplemented from OpFunc.
Definition at line 179 of file OpFuncBase.h.
    {
        vector< A1 > temp1 = Conv< vector< A1 > >::buf2val( &buf );
        vector< A2 > temp2 = Conv< vector< A2 > >::buf2val( &buf );
        Element* elm = e.element();
        assert( temp1.size() >= elm->numLocalData() );
        unsigned int k = 0;
        unsigned int start = elm->localDataStart();
        unsigned int end = start + elm->numLocalData();
        for ( unsigned int i = start; i < end; ++i)
        {
            unsigned int nf = elm->numField( i - start );
            for ( unsigned int j = 0; j < nf; ++j)
            {
                Eref er( elm, i, j );
                op( er, temp1[ k % temp1.size() ],
                    temp2[ k % temp2.size() ] );
                ++k;
            }
        }
    }
References Eref::element(), Eref::Eref(), Element::localDataStart(), Element::numField(), Element::numLocalData(), and OpFunc2Base< A1, A2 >::op().
rttiType()
template<class A1 , class A2 > string OpFunc2Base< A1, A2 >::rttiType () const inline virtual
Implements OpFunc.
Definition at line 207 of file OpFuncBase.h.
    {
        return Conv< A1 >::rttiType() + "," + Conv< A2 >::rttiType();
    }
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/basecode/SrcFinfo.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/basecode/OpFuncBase.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/basecode/HopFunc.h