MOOSE - Multiscale Object Oriented Simulation Environment: OpFunc2< T, A1, A2 > Class Template Reference
OpFunc2< T, A1, A2 > Class Template Reference
#include <OpFunc.h>
Public Member Functions
void op (const Eref &e, A1 arg1, A2 arg2) const
OpFunc2 (void(T::*func)(A1, A2))
Public Member Functions inherited from OpFunc2Base< A1, A2 >
bool checkFinfo (const Finfo *s) const
const OpFunc * makeHopFunc (HopIndex hopIndex) const
void opBuffer (const Eref &e, double *buf) const
Executes the OpFunc by converting args.
virtual void opVec (const Eref &e, const vector< A1 > &arg1, const vector< A2 > &arg2, const OpFunc2Base< A1, A2 > *op) const
void opVecBuffer (const Eref &e, double *buf) const
Executes the OpFunc for all data by converting a vector of args.
string rttiType () const
Public Member Functions inherited from OpFunc
OpFunc ()
unsigned int opIndex () const
bool setIndex (unsigned int i)
Used when rebuilding the Fid->OpFunc mapping.
virtual ~OpFunc ()
Private Attributes
void(T::* func_)(A1, A2)
Additional Inherited Members
Static Public Member Functions inherited from OpFunc
static const OpFunc * lookop (unsigned int opIndex)
static unsigned int rebuildOpIndex ()
cleans out the entire Ops vector. Returns size of orig vector.
Detailed Description
template<class T, class A1, class A2>
class OpFunc2< T, A1, A2 >
Definition at line 42 of file OpFunc.h.
Constructor & Destructor Documentation
OpFunc2()
template<class T , class A1 , class A2 > OpFunc2< T, A1, A2 >::OpFunc2 (void(T::*)(A1, A2) func) inline
Definition at line 46 of file OpFunc.h.
        : func_( func )
    {;}
References OpFunc2< T, A1, A2 >::func_.
Referenced by moose::CompartmentBase::initCinfo(), IzhikevichNrn::initCinfo(), MarkovSolverBase::initCinfo(), Neuron::initCinfo(), SymCompartment::initCinfo(), Arith::initCinfo(), TableBase::initCinfo(), PulseGen::initCinfo(), Enz::initCinfo(), Stoich::initCinfo(), PresynMesh::initCinfo(), SparseMsg::initCinfo(), Shell::initCinfo(), and PoolBase::initPoolBaseCinfo().
Member Function Documentation
op()
template<class T , class A1 , class A2 > void OpFunc2< T, A1, A2 >::op (const Eref & e, A1 arg1, A2 arg2) const inline virtual
Implements OpFunc2Base< A1, A2 >.
Definition at line 50 of file OpFunc.h.
    {
        (reinterpret_cast< T* >( e.data() )->*func_)( arg1, arg2 );
    }
References Eref::data(), and OpFunc2< T, A1, A2 >::func_.
Member Data Documentation
func_
template<class T , class A1 , class A2 > void(T::* OpFunc2< T, A1, A2 >::func_) (A1, A2) private
Definition at line 56 of file OpFunc.h.
Referenced by OpFunc2< T, A1, A2 >::op(), and OpFunc2< T, A1, A2 >::OpFunc2().
The documentation for this class was generated from the following file:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/basecode/OpFunc.h