MOOSE - Multiscale Object Oriented Simulation Environment: SparseMsg Class Reference
SparseMsg Class Reference
#include <SparseMsg.h>
Public Member Functions
void clear ()
Msg * copy (Id origSrc, Id newSrc, Id newTgt, FuncId fid, unsigned int b, unsigned int n) const
ObjId findOtherEnd (ObjId end) const
Eref firstTgt (const Eref &src) const
vector< unsigned int > getColIndex () const
vector< unsigned int > getEntryPairs () const
SparseMatrix< unsigned int > & getMatrix ()
vector< unsigned int > getMatrixEntry () const
unsigned int getNumColumns () const
unsigned int getNumEntries () const
unsigned int getNumRows () const
double getProbability () const
vector< unsigned int > getRowStart () const
int getSeed () const
Id managerId () const
void pairFill (vector< unsigned int > src, vector< unsigned int > dest)
unsigned int randomConnect (double probability)
void setEntry (unsigned int row, unsigned int column, unsigned int value)
void setEntryPairs (vector< unsigned int > entries)
void setMatrix (const SparseMatrix< unsigned int > &m)
void setProbability (double value)
void setRandomConnectivity (double probability, long seed)
void setSeed (int value)
void sources (vector< vector< Eref > > &v) const
SparseMsg (Element *e1, Element *e2, unsigned int msgIndex)
void targets (vector< vector< Eref > > &v) const
void transpose ()
void tripletFill (vector< unsigned int > src, vector< unsigned int > dest, vector< unsigned int > field)
void tripletFill1 (vector< unsigned int > entries)
void unsetEntry (unsigned int row, unsigned int column)
void updateAfterFill ()
~SparseMsg ()
Public Member Functions inherited from Msg
Element * e1 () const
Element * e2 () const
ObjId getAdjacent (ObjId) const
vector< string > getDestFieldsOnE1 () const
vector< string > getDestFieldsOnE2 () const
Id getE1 () const
Id getE2 () const
vector< string > getSrcFieldsOnE1 () const
vector< string > getSrcFieldsOnE2 () const
bool isForward (const Element *src) const
ObjId mid () const
Msg (ObjId mid, Element *e1, Element *e2)
Constructor.
virtual void sources (vector< vector< Eref > > &v) const =0
virtual void targets (vector< vector< Eref > > &v) const =0
virtual ~Msg ()
Destructor.
Static Public Member Functions
static const Cinfo * initCinfo ()
static char * lookupMsg (unsigned int index)
Static function for Msg access.
static unsigned int numMsg ()
Msg lookup functions.
Static Public Member Functions inherited from Msg
static void clearAllMsgs ()
static void deleteMsg (ObjId mid)
static const Msg * getMsg (ObjId m)
static const Cinfo * initCinfo ()
static unsigned int initMsgManagers ()
static bool isLastTrump ()
True when MOOSE has been terminated and is being cleaned up.
static const Msg * lastMsg ()
Private Attributes
SparseMatrix< unsigned int > matrix_
unsigned int nrows_
unsigned int numThreads_
double p_
moose::RNG rng_
int seed_
Static Private Attributes
static Id managerId_
static vector< SparseMsg * > msg_
Friends
unsigned int Msg::initMsgManagers ()
Additional Inherited Members
Protected Attributes inherited from Msg
Element * e1_
Index of this Msg on the msg_ vector.
Element * e2_
Element 1 attached to Msg.
ObjId mid_
Static Protected Attributes inherited from Msg
static bool lastTrump_ = false
Flag to indicate termination of program.
static Id msgManagerId_
Element 2 attached to Msg.
Detailed Description
This is a parallelized sparse message. It is a general message type optimized for sparse matrix like projection patterns. For each source object[DataId] there can be a target object[DataId]. For parallel/multithreaded use, we need to guarantee that all requests to the same target object (and all its synapses) are on the same queue. So it builds up a separate SparseMatrix for each thread.
It has a function to do the node/thread decomposition to generate an equivalent of the original sparse matrix, but using only the appropriate RNG seed.
A typical case is from an array of IntFire objects to an array of Synapses, which are array fields of IntFire objects. The sparse connectivity maps between the source IntFire and target Synapses.
The location of the entry in the sparse matrix provides the index of the target IntFire. The data value in the sparse matrix provides the index of the Synapse at that specific connection. This assumes that only one Synapse mediates a given connection between any two IntFire objects.
It is optimized for input coming on Element e1, and going to Element e2. If you expect any significant backward data flow, please use BiSparseMsg. It can be modified after creation to add or remove message entries.
Definition at line 47 of file SparseMsg.h.
Constructor & Destructor Documentation
SparseMsg()
SparseMsg::SparseMsg (Element * e1, Element * e2, unsigned int msgIndex)
Definition at line 383 of file SparseMsg.cpp.
    : Msg(ObjId( managerId_, (msgIndex != 0) ? msgIndex: msg_.size() ), e1, e2),
      numThreads_( 1 ),
      nrows_( 0 ),
      p_( 0.0 ),
      seed_(-1)
{
    unsigned int nrows = 0;
    unsigned int ncolumns = 0;
    nrows = e1->numData();
    ncolumns = e2->numData();
    matrix_.setSize( nrows, ncolumns );
    if ( msgIndex == 0 )
    {
        msg_.push_back( this );
    }
    else
    {
        if ( msg_.size() <= msgIndex )
            msg_.resize( msgIndex + 1 );
        msg_[ msgIndex ] = this;
    }
    // cout << Shell::myNode() << ": SparseMsg constructor between " << e1->getName() << " and " << e2->getName() << endl;
    // Init rng with global seed if any.
    seed_ = moose::getGlobalSeed();
    if(seed_ >= 0)
        setSeed(seed_);
}
References moose::getGlobalSeed(), managerId_, matrix_, Msg::Msg(), msg_, nrows_, Element::numData(), numThreads_, ObjId::ObjId(), p_, seed_, setSeed(), and SparseMatrix< T >::setSize().
Referenced by copy(), Shell::innerAddMsg(), and testSparseMsg().
~SparseMsg()
SparseMsg::~SparseMsg ()
Definition at line 414 of file SparseMsg.cpp.
{
    assert( mid_.dataIndex < msg_.size() );
    msg_[ mid_.dataIndex ] = 0; // ensure deleted ptr isn't reused.
}
References ObjId::dataIndex, Msg::mid_, and msg_.
Member Function Documentation
clear()
void SparseMsg::clear ()
Definition at line 283 of file SparseMsg.cpp.
{
    matrix_.clear();
}
References SparseMatrix< T >::clear(), and matrix_.
Referenced by initCinfo().
copy()
Msg * SparseMsg::copy (Id origSrc, Id newSrc, Id newTgt, FuncId fid, unsigned int b, unsigned int n) const virtual
Make a copy of this Msg. The original msg was on origSrc. The new Msg should go from newSrc to newTgt, and have the function fid, on bindIndex b. The copy may have to be a higher-order Msg type to handle arrays if n > 1. Note that n is not the number of msgs, but the multiplier by which numData will be scaled.
Implements Msg.
Definition at line 565 of file SparseMsg.cpp.
{
    const Element* orig = origSrc.element();
    if ( n <= 1 )
    {
        SparseMsg* ret = 0;
        if ( orig == e1() )
        {
            ret = new SparseMsg( newSrc.element(), newTgt.element(), 0 );
            ret->e1()->addMsgAndFunc( ret->mid(), fid, b );
        }
        else if ( orig == e2() )
        {
            ret = new SparseMsg( newTgt.element(), newSrc.element(), 0 );
            ret->e2()->addMsgAndFunc( ret->mid(), fid, b );
        }
        else
        {
            assert( 0 );
        }
        ret->setMatrix( matrix_ );
        ret->nrows_ = nrows_;
        return ret;
    }
    else
    {
        // Here we need a SliceMsg which goes from one 2-d array to another.
        cout << "Error: SparseMsg::copy: SparseSliceMsg not yet implemented\n";
        return 0;
    }
}
References Element::addMsgAndFunc(), Msg::e1(), Msg::e2(), Id::element(), matrix_, Msg::mid(), nrows_, setMatrix(), and SparseMsg().
findOtherEnd()
ObjId SparseMsg::findOtherEnd (ObjId) const virtual
Find the other end of this Msg. In most cases this is a straightforward return of e1 or e2, plus perhaps a DataId. But in some complex msgs we need to figure out DataIds that match with the target. In many-to-one cases we just return the first entry. If no Element match, return ObjId(Id(), DataId::bad()) If Element e matches but not DataId, return ObjId(e.id(), DataId::bad())
Implements Msg.
Definition at line 539 of file SparseMsg.cpp.
{
    if ( f.element() == e1() )
    {
        const unsigned int* entry;
        const unsigned int* colIndex;
        unsigned int num = matrix_.getRow( f.dataIndex, &entry, &colIndex );
        if ( num > 0 )   // Return the first matching entry.
        {
            return ObjId( e2()->id(), colIndex[0] );
        }
        return ObjId( 0, BADINDEX );
    }
    else if ( f.element() == e2() )     // Bad! Slow! Avoid!
    {
        vector< unsigned int > entry;
        vector< unsigned int > rowIndex;
        unsigned int num = matrix_.getColumn( f.dataIndex, entry, rowIndex );
        if ( num > 0 )   // Return the first matching entry.
        {
            return ObjId( e1()->id(), DataId( rowIndex[0] ) );
        }
    }
    return ObjId( 0, BADINDEX );
}
References BADINDEX, ObjId::dataIndex, Msg::e1(), Msg::e2(), ObjId::element(), SparseMatrix< T >::getColumn(), SparseMatrix< T >::getRow(), Element::id(), matrix_, and ObjId::ObjId().
firstTgt()
Eref SparseMsg::firstTgt (const Eref & src) const virtual
Obtain the first target Eref for the specified Src Eref It is really meant only to work with messages with a single target ObjId for each given src, typically OneToOne.
Implements Msg.
Definition at line 428 of file SparseMsg.cpp.
{
    if ( matrix_.nEntries() == 0 )
        return Eref( 0, 0 );
    if ( src.element() == e1_ )
    {
        const unsigned int* fieldIndex;
        const unsigned int* colIndex;
        unsigned int n = matrix_.getRow( src.dataIndex(),
                                         &fieldIndex, &colIndex );
        if ( n != 0 )
        {
            return Eref( e2_, colIndex[0], fieldIndex[0] );
        }
    }
    else if ( src.element() == e2_ )
    {
        return Eref( e1_, 0 );
    }
    return Eref( 0, 0 );
}
References Eref::dataIndex(), Msg::e1_, Msg::e2_, Eref::element(), Eref::Eref(), SparseMatrix< T >::getRow(), matrix_, and SparseMatrix< T >::nEntries().
getColIndex()
vector< unsigned int > SparseMsg::getColIndex () const
Definition at line 228 of file SparseMsg.cpp.
{
    return matrix_.colIndex();
}
References SparseMatrix< T >::colIndex(), and matrix_.
Referenced by initCinfo().
getEntryPairs()
vector< unsigned int > SparseMsg::getEntryPairs () const
Definition at line 245 of file SparseMsg.cpp.
{
    vector< unsigned int > cols = matrix_.colIndex();
    vector< unsigned int > y;
    for ( unsigned int row = 0; row < matrix_.nRows(); ++row )
    {
        unsigned int begin = matrix_.rowStart()[row];
        unsigned int end = matrix_.rowStart()[row+1];
        for ( unsigned int j = begin; j < end; ++j )
            y.push_back( row );
    }
    assert( cols.size() == y.size() );
    y.insert( y.end(), cols.begin(), cols.end() );
    return y;
}
References SparseMatrix< T >::colIndex(), matrix_, SparseMatrix< T >::nRows(), and SparseMatrix< T >::rowStart().
Referenced by initCinfo().
getMatrix()
SparseMatrix< unsigned int > & SparseMsg::getMatrix ()
Returns the connection matrix
Definition at line 534 of file SparseMsg.cpp.
{
    return matrix_;
}
References matrix_.
getMatrixEntry()
vector< unsigned int > SparseMsg::getMatrixEntry () const
Definition at line 223 of file SparseMsg.cpp.
{
    return matrix_.matrixEntry();
}
References matrix_, and SparseMatrix< T >::matrixEntry().
Referenced by initCinfo().
getNumColumns()
unsigned int SparseMsg::getNumColumns () const
Definition at line 213 of file SparseMsg.cpp.
{
    return matrix_.nColumns();
}
References matrix_, and SparseMatrix< T >::nColumns().
Referenced by initCinfo().
getNumEntries()
unsigned int SparseMsg::getNumEntries () const
Definition at line 218 of file SparseMsg.cpp.
{
    return matrix_.nEntries();
}
References matrix_, and SparseMatrix< T >::nEntries().
Referenced by initCinfo().
getNumRows()
unsigned int SparseMsg::getNumRows () const
Definition at line 208 of file SparseMsg.cpp.
{
    return matrix_.nRows();
}
References matrix_, and SparseMatrix< T >::nRows().
Referenced by initCinfo().
getProbability()
double SparseMsg::getProbability () const
Definition at line 190 of file SparseMsg.cpp.
{
    return p_;
}
References p_.
Referenced by initCinfo().
getRowStart()
vector< unsigned int > SparseMsg::getRowStart () const
Definition at line 233 of file SparseMsg.cpp.
{
    return matrix_.rowStart();
}
References matrix_, and SparseMatrix< T >::rowStart().
Referenced by initCinfo().
getSeed()
int SparseMsg::getSeed () const
Definition at line 203 of file SparseMsg.cpp.
{
    return seed_;
}
References seed_.
Referenced by initCinfo().
initCinfo()
const Cinfo * SparseMsg::initCinfo () static
Connection matrix entries to manipulate in Python.
connection matrix column indices to manipulate in Python.
connection matrix rowStart to manipulate in Python.
Definition at line 25 of file SparseMsg.cpp.
{
    // Field definitions.
    static ReadOnlyValueFinfo< SparseMsg, unsigned int > numRows(
        "numRows",
        "Number of rows in matrix.",
        &SparseMsg::getNumRows
    );
    static ReadOnlyValueFinfo< SparseMsg, unsigned int > numColumns(
        "numColumns",
        "Number of columns in matrix.",
        &SparseMsg::getNumColumns
    );
    static ReadOnlyValueFinfo< SparseMsg, unsigned int > numEntries(
        "numEntries",
        "Number of Entries in matrix.",
        &SparseMsg::getNumEntries
    );
    static ValueFinfo< SparseMsg, vector< unsigned int > > connectionList(
        "connectionList",
        "Pairwise specification of connection matrix where each x,y value "
        "represents a connection from src[x] to dest[y]. "
        "The (x,y) entries are ordered in a single vector as \n"
        "(x0, x1,... x_n-1, y0, y1,... y_n-1)\n",
        &SparseMsg::setEntryPairs,
        &SparseMsg::getEntryPairs
    );
    static ReadOnlyValueFinfo< SparseMsg, vector< unsigned int > >
    matrixEntry(
        "matrixEntry",
        "The non-zero matrix entries in the sparse matrix. Their"
        "column indices are in a separate vector and the row"
        "informatino in a third",
        &SparseMsg::getMatrixEntry
    );
    static ReadOnlyValueFinfo< SparseMsg, vector< unsigned int > >
    columnIndex(
        "columnIndex",
        "Column Index of each matrix entry",
        &SparseMsg::getColIndex
    );
    static ReadOnlyValueFinfo< SparseMsg, vector< unsigned int > >
    rowStart(
        "rowStart",
        "Row start for each block of entries and column indices",
        &SparseMsg::getRowStart
    );
    static ValueFinfo< SparseMsg, double > probability(
        "probability",
        "connection probability for random connectivity.",
        &SparseMsg::setProbability,
        &SparseMsg::getProbability
    );
    static ValueFinfo< SparseMsg, int > seed(
        "seed",
        "Random number seed for generating probabilistic connectivity.",
        &SparseMsg::setSeed,
        &SparseMsg::getSeed
    );
// DestFinfos
    static DestFinfo setRandomConnectivity( "setRandomConnectivity",
            "Assigns connectivity with specified probability and seed",
            new OpFunc2< SparseMsg, double, long >(
                &SparseMsg::setRandomConnectivity ) );
    static DestFinfo setEntry( "setEntry",
            "Assigns single row,column value",
            new OpFunc3< SparseMsg, unsigned int, unsigned int, unsigned int >(
                &SparseMsg::setEntry ) );
    static DestFinfo unsetEntry( "unsetEntry",
            "Clears single row,column entry",
            new OpFunc2< SparseMsg, unsigned int, unsigned int >(
                &SparseMsg::unsetEntry ) );
    static DestFinfo clear( "clear",
            "Clears out the entire matrix",
            new OpFunc0< SparseMsg >(
                &SparseMsg::clear ) );
    static DestFinfo transpose( "transpose",
            "Transposes the sparse matrix",
            new OpFunc0< SparseMsg >(
                &SparseMsg::transpose ) );
    static DestFinfo pairFill( "pairFill",
            "Fills entire matrix using pairs of (x,y) indices to indicate "
            "presence of a connection. If the target is a FieldElement it"
            "automagically assigns FieldIndices.",
            new OpFunc2< SparseMsg,
            vector< unsigned int >, vector< unsigned int> >(
                &SparseMsg::pairFill ) );
    static DestFinfo tripletFill( "tripletFill",
            "Fills entire matrix using triplets of (x,y,fieldIndex) to fully "
            "specify every connection in the sparse matrix.",
            new OpFunc3< SparseMsg,
            vector< unsigned int >, vector< unsigned int>,
            vector< unsigned int >  >(
                &SparseMsg::tripletFill ) );
    static DestFinfo tripletFill1( "tripletFill1",
            "Single contiguous array to fill entire connection matrix using "
            "triplets of (x,y, fieldindex) ordered as \n"
            "(x0, x1,... xn-1, y0, y1,... yn-1, fi0, fi1,... fi_n-1)\n",
            new OpFunc1< SparseMsg, vector< unsigned int > >(
                &SparseMsg::tripletFill1 ) );
    // Assemble it all.
    static Finfo* sparseMsgFinfos[] =
    {
        &numRows,               // readonly value
        &numColumns,            // readonly value
        &numEntries,            // readonly value
        &connectionList,        // value
        &matrixEntry,           // ReadOnlyValue
        &columnIndex,           // ReadOnlyValue
        &rowStart,              // ReadOnlyValue
        &probability,           // value
        &seed,                  // value
        &setRandomConnectivity, // dest
        &setEntry,              // dest
        &unsetEntry,            // dest
        &clear,                 // dest
        &transpose,             // dest
        &pairFill,              // dest
        &tripletFill,           // dest
        &tripletFill1,          // dest
    };
    static Dinfo< short > dinfo;
    static Cinfo sparseMsgCinfo (
            "SparseMsg",                                  // name
            Msg::initCinfo(),                             // base class
            sparseMsgFinfos,
            sizeof( sparseMsgFinfos ) / sizeof( Finfo* ), // num Fields
            &dinfo
            );
    return &sparseMsgCinfo;
}
References Cinfo::Cinfo(), clear(), DestFinfo::DestFinfo(), getColIndex(), getEntryPairs(), getMatrixEntry(), getNumColumns(), getNumEntries(), getNumRows(), getProbability(), getRowStart(), getSeed(), Msg::initCinfo(), OpFunc0< T >::OpFunc0(), OpFunc1< T, A >::OpFunc1(), OpFunc2< T, A1, A2 >::OpFunc2(), OpFunc3< T, A1, A2, A3 >::OpFunc3(), pairFill(), ReadOnlyValueFinfo< T, F >::ReadOnlyValueFinfo(), setEntry(), setEntryPairs(), setProbability(), setRandomConnectivity(), setSeed(), transpose(), tripletFill(), tripletFill1(), unsetEntry(), and ValueFinfo< T, F >::ValueFinfo().
Referenced by Msg::initMsgManagers().
lookupMsg()
char * SparseMsg::lookupMsg (unsigned int index) static
Static function for Msg access.
Definition at line 638 of file SparseMsg.cpp.
{
    assert( index < msg_.size() );
    return reinterpret_cast< char* >( msg_[index] );
}
References msg_.
Referenced by Msg::clearAllMsgs(), and Msg::initMsgManagers().
managerId()
Id SparseMsg::managerId () const
Definition at line 524 of file SparseMsg.cpp.
{
    return SparseMsg::managerId_;
}
References managerId_.
numMsg()
unsigned int SparseMsg::numMsg () static
Msg lookup functions.
Static function for Msg access.
Definition at line 632 of file SparseMsg.cpp.
{
    return msg_.size();
}
References msg_.
Referenced by Msg::clearAllMsgs(), and Msg::initMsgManagers().
pairFill()
void SparseMsg::pairFill (vector< unsigned int > src, vector< unsigned int > dest)
Fills up the entire message based on pairs of src,dest (i.e., row,column) values. All filled entries are set to zero.
We set retainSize flag to true since the # of src/dest objects doesn't change. We can explicitly assign it elsewhere if needed.
Definition at line 317 of file SparseMsg.cpp.
{
    // Sanity check
    vector< unsigned int >::const_iterator i;
    for ( i = src.begin(); i != src.end(); ++i )
    {
        if (*i >= e1()->numData() )
        {
            cout << "Warning: SparseMsg::pairFill: Src index " << *i <<
                 " exceeds Src array size " << e1()->numData() <<
                 ". Aborting\n";
            return;
        }
    }
    for ( i = dest.begin(); i != dest.end(); ++i )
    {
        if (*i >= e2()->numData() )
        {
            cout << "Warning: SparseMsg::pairFill: Dest index " << *i <<
                 " exceeds Dest array size " << e2()->numData() <<
                 ". Aborting\n";
            return;
        }
    }
    vector< unsigned int > numAtDest( dest.size(), 0 );
    vector< unsigned int > fieldIndex( dest.size(), 0 );
    for ( unsigned int i = 0; i < dest.size(); ++i )
    {
        fieldIndex[i] = numAtDest[ dest[i] ];
        // Could do on previous line, but clarity
        ++numAtDest[ dest[i] ];
    }
    matrix_.tripletFill( src, dest, fieldIndex, true );
    updateAfterFill();
}
References Msg::e1(), Msg::e2(), matrix_, Element::numData(), SparseMatrix< T >::tripletFill(), and updateAfterFill().
Referenced by initCinfo(), and setEntryPairs().
randomConnect()
unsigned int SparseMsg::randomConnect (double probability)
Returns number of synapses formed. Fills it in transpose form, because we need to count and index the number of synapses on the target, so we need to iterate over the sources in the inner loop. Once full, does the transpose. Should really have a seed argument for the random number. Later need a way to fast-forward mtrand to just the entries we need to fill.
Definition at line 460 of file SparseMsg.cpp.
{
    unsigned int nRows = matrix_.nRows(); // Sources
    unsigned int nCols = matrix_.nColumns();    // Destinations
    matrix_.clear();
    unsigned int totalSynapses = 0;
    vector< unsigned int > sizes( nCols, 0 );
    unsigned int totSynNum = 0;
    Element* syn = e2_;
    unsigned int startData = syn->localDataStart();
    unsigned int endData = startData + syn->numLocalData();
    assert( nCols == syn->numData() );
    matrix_.transpose();
    for ( unsigned int i = 0; i < nCols; ++i )
    {
        vector< unsigned int > synIndex;
        // This needs to be obtained from current size of syn array.
        // unsigned int synNum = sizes[ i ];
        unsigned int synNum = 0;
        for ( unsigned int j = 0; j < nRows; ++j )
        {
            double r = rng_.uniform(); // Want to ensure it is called each time round the loop.
            if ( r < probability )
            {
                synIndex.push_back( synNum );
                ++synNum;
                ++totSynNum;
            }
            else
            {
                synIndex.push_back( ~0 );
            }
        }
        if ( i >= startData && i < endData )
        {
            e2_->resizeField( i - startData, synNum );
        }
        totalSynapses += synNum;
        matrix_.addRow( i, synIndex );
        /*
         * This is the correct form, but I need to implement something
         * to check up for target nodes in order to use this.
        if ( i >= startData && i < endData ) {
            e2_->resizeField( i - startData, synNum );
            totalSynapses += synNum;
            matrix_.addRow( i, synIndex );
        } else {
            synIndex.resize( 0 );
            synIndex.assign( nRows, ~0 );
            matrix_.addRow( i, synIndex );
        }
        */
    }
    matrix_.transpose();
    // cout << Shell::myNode() << ": sizes.size() = " << sizes.size() << ", ncols = " << nCols << ", startSynapse = " << startSynapse << endl;
    e1()->markRewired();
    e2()->markRewired();
    return totalSynapses;
}
References SparseMatrix< T >::addRow(), SparseMatrix< T >::clear(), Msg::e1(), Msg::e2(), Msg::e2_, Element::localDataStart(), Element::markRewired(), matrix_, SparseMatrix< T >::nColumns(), SparseMatrix< T >::nRows(), Element::numData(), Element::numLocalData(), Element::resizeField(), rng_, SparseMatrix< T >::transpose(), and moose::RNG::uniform().
Referenced by setProbability(), setRandomConnectivity(), setSeed(), and testSparseMsg().
setEntry()
void SparseMsg::setEntry (unsigned int row, unsigned int column, unsigned int value)
Definition at line 272 of file SparseMsg.cpp.
{
    matrix_.set( row, column, value );
}
References matrix_, and SparseMatrix< T >::set().
Referenced by initCinfo().
setEntryPairs()
void SparseMsg::setEntryPairs (vector< unsigned int > entries)
Definition at line 238 of file SparseMsg.cpp.
{
    vector< unsigned int > src( v.begin(), v.begin() + v.size()/2 );
    vector< unsigned int > dest( v.begin() + v.size()/2, v.end() );
    pairFill( src, dest );
}
References pairFill().
Referenced by initCinfo().
setMatrix()
void SparseMsg::setMatrix (const SparseMatrix< unsigned int > & m)
Assigns the whole connection matrix
Definition at line 529 of file SparseMsg.cpp.
{
    matrix_ = m;
}
References matrix_.
Referenced by copy().
setProbability()
void SparseMsg::setProbability (double value)
Definition at line 184 of file SparseMsg.cpp.
{
    p_ = probability;
    randomConnect( probability );
}
References p_, and randomConnect().
Referenced by initCinfo().
setRandomConnectivity()
void SparseMsg::setRandomConnectivity (double probability, long seed)
Definition at line 265 of file SparseMsg.cpp.
{
    p_ = probability;
    rng_.setSeed( seed );
    randomConnect( probability );
}
References p_, randomConnect(), rng_, and moose::RNG::setSeed().
Referenced by initCinfo().
setSeed()
void SparseMsg::setSeed (int value)
Definition at line 195 of file SparseMsg.cpp.
{
    seed_ = seed;
    if( seed_ >= 0)
        rng_.setSeed((size_t)seed_);
    randomConnect(p_);
}
References p_, randomConnect(), rng_, seed_, and moose::RNG::setSeed().
Referenced by initCinfo(), and SparseMsg().
sources()
void SparseMsg::sources (vector< vector< Eref > > & v) const
Definition at line 619 of file SparseMsg.cpp.
{
    SparseMatrix< unsigned int > temp( matrix_ );
    temp.transpose();
    fillErefsFromMatrix( temp, v, e2_, e1_ );
}
References Msg::e1_, Msg::e2_, fillErefsFromMatrix(), matrix_, and SparseMatrix< T >::transpose().
targets()
void SparseMsg::targets (vector< vector< Eref > > & v) const
Definition at line 626 of file SparseMsg.cpp.
{
    fillErefsFromMatrix( matrix_, v, e1_, e2_ );
}
References Msg::e1_, Msg::e2_, fillErefsFromMatrix(), and matrix_.
transpose()
void SparseMsg::transpose ()
Definition at line 288 of file SparseMsg.cpp.
{
    matrix_.transpose();
    e1()->markRewired();
    e2()->markRewired();
}
References Msg::e1(), Msg::e2(), Element::markRewired(), matrix_, and SparseMatrix< T >::transpose().
Referenced by initCinfo().
tripletFill()
void SparseMsg::tripletFill (vector< unsigned int > src, vector< unsigned int > dest, vector< unsigned int > field)
Fills up the entire message based on triplets of src,destDataIndex,destFieldIndex
Definition at line 360 of file SparseMsg.cpp.
{
    // We set retainSize flag to true
    matrix_.tripletFill( src, destDataIndex, destFieldIndex, true );
    updateAfterFill();
}
References matrix_, SparseMatrix< T >::tripletFill(), and updateAfterFill().
Referenced by initCinfo(), and tripletFill1().
tripletFill1()
void SparseMsg::tripletFill1 (vector< unsigned int > entries)
Fills up the entire message based on triplets of src,destDataIndex,destFieldIndex, but catenates them all into a single long vector since PyMoose doesn't know how to handle multiple vectors.
Definition at line 369 of file SparseMsg.cpp.
{
    unsigned int s3 = v.size() / 3;
    vector< unsigned int > src( v.begin(), v.begin() + s3 );
    vector< unsigned int > dest( v.begin() + s3, v.begin() + 2 * s3 );
    vector< unsigned int > fieldIndex( v.begin() + 2 * s3, v.end() );
    tripletFill( src, dest, fieldIndex );
}
References tripletFill().
Referenced by initCinfo().
unsetEntry()
void SparseMsg::unsetEntry (unsigned int row, unsigned int column)
Definition at line 278 of file SparseMsg.cpp.
{
    matrix_.unset( row, column );
}
References matrix_, and SparseMatrix< T >::unset().
Referenced by initCinfo().
updateAfterFill()
void SparseMsg::updateAfterFill ()
Utility function to update all sorts of values after we've rebuilt the matrix.
Definition at line 295 of file SparseMsg.cpp.
{
    unsigned int startData = e2_->localDataStart();
    unsigned int endData = startData + e2_->numLocalData();
    SparseMatrix< unsigned int > temp( matrix_);
    temp.transpose();
    for ( unsigned int i = 0; i < temp.nRows(); ++ i )
    {
        const unsigned int* colIndex;
        const unsigned int* entry;
        unsigned int num = temp.getRow( i, &entry, &colIndex );
        if ( i >= startData && i < endData )
        {
            // Inefficient. Better to do it in one pass after getting
            // the max num
            e2_->resizeField( i - startData, num + 1 );
        }
    }
    e1()->markRewired();
    e2()->markRewired();
}
References Msg::e1(), Msg::e2(), Msg::e2_, SparseMatrix< T >::getRow(), Element::localDataStart(), Element::markRewired(), matrix_, SparseMatrix< T >::nRows(), Element::numLocalData(), Element::resizeField(), and SparseMatrix< T >::transpose().
Referenced by pairFill(), and tripletFill().
Friends And Related Symbol Documentation
Msg::initMsgManagers
unsigned int Msg::initMsgManagers () friend
Member Data Documentation
managerId_
Id SparseMsg::managerId_ static private
Definition at line 149 of file SparseMsg.h.
Referenced by Msg::initMsgManagers(), managerId(), and SparseMsg().
matrix_
SparseMatrix< unsigned int > SparseMsg::matrix_ private
Definition at line 145 of file SparseMsg.h.
Referenced by clear(), copy(), findOtherEnd(), firstTgt(), getColIndex(), getEntryPairs(), getMatrix(), getMatrixEntry(), getNumColumns(), getNumEntries(), getNumRows(), getRowStart(), pairFill(), randomConnect(), setEntry(), setMatrix(), sources(), SparseMsg(), targets(), transpose(), tripletFill(), unsetEntry(), and updateAfterFill().
msg_
vector< SparseMsg * > SparseMsg::msg_ static private
Definition at line 150 of file SparseMsg.h.
Referenced by lookupMsg(), numMsg(), SparseMsg(), and ~SparseMsg().
nrows_
unsigned int SparseMsg::nrows_ private
Definition at line 147 of file SparseMsg.h.
Referenced by copy(), and SparseMsg().
numThreads_
unsigned int SparseMsg::numThreads_ private
Definition at line 146 of file SparseMsg.h.
Referenced by SparseMsg().
p_
double SparseMsg::p_ private
Definition at line 148 of file SparseMsg.h.
Referenced by getProbability(), setProbability(), setRandomConnectivity(), setSeed(), and SparseMsg().
rng_
moose::RNG SparseMsg::rng_ private
Definition at line 154 of file SparseMsg.h.
Referenced by randomConnect(), setRandomConnectivity(), and setSeed().
seed_
int SparseMsg::seed_ private
Definition at line 153 of file SparseMsg.h.
Referenced by getSeed(), setSeed(), and SparseMsg().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/msg/SparseMsg.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/msg/SparseMsg.cpp