MOOSE - Multiscale Object Oriented Simulation Environment: OpFunc Class Reference
OpFunc Class Reference abstract
#include <OpFuncBase.h>
Public Member Functions
virtual bool checkFinfo (const Finfo *s) const =0
virtual const OpFunc * makeHopFunc (HopIndex hopIndex) const =0
virtual void opBuffer (const Eref &e, double *buf) const =0
Executes the OpFunc by converting args.
OpFunc ()
unsigned int opIndex () const
virtual void opVecBuffer (const Eref &e, double *buf) const
Executes the OpFunc for all data by converting a vector of args.
virtual string rttiType () const =0
bool setIndex (unsigned int i)
Used when rebuilding the Fid->OpFunc mapping.
virtual ~OpFunc ()
Static Public Member Functions
static const OpFunc * lookop (unsigned int opIndex)
static unsigned int rebuildOpIndex ()
cleans out the entire Ops vector. Returns size of orig vector.
Static Private Member Functions
static vector< OpFunc * > & ops ()
Private Attributes
unsigned int opIndex_
Detailed Description
Definition at line 46 of file OpFuncBase.h.
Constructor & Destructor Documentation
OpFunc()
OpFunc::OpFunc ()
Definition at line 26 of file OpFuncBase.cpp.
{
    opIndex_ = ops().size();
    ops().push_back( this );
}
References opIndex_, and ops().
~OpFunc()
virtual OpFunc::~OpFunc () inline virtual
Definition at line 51 of file OpFuncBase.h.
    {;}
Member Function Documentation
checkFinfo()
virtual bool OpFunc::checkFinfo (const Finfo * s) const pure virtual
Implemented in OpFunc0Base, OpFunc1Base< A >, OpFunc1Base< A * >, OpFunc1Base< ProcPtr >, OpFunc1Base< vector< A > * >, OpFunc2Base< A1, A2 >, OpFunc3Base< A1, A2, A3 >, OpFunc4Base< A1, A2, A3, A4 >, OpFunc5Base< A1, A2, A3, A4, A5 >, OpFunc6Base< A1, A2, A3, A4, A5, A6 >, and LookupGetOpFuncBase< L, A >.
Referenced by SrcFinfo::addMsg(), and SrcFinfo::checkTarget().
lookop()
const OpFunc * OpFunc::lookop (unsigned int opIndex) static
Definition at line 42 of file OpFuncBase.cpp.
{
    assert ( opIndex < ops().size() );
    return ops()[ opIndex ];
}
References ops().
makeHopFunc()
virtual const OpFunc * OpFunc::makeHopFunc (HopIndex hopIndex) const pure virtual
Implemented in OpFunc0Base, OpFunc1Base< A >, OpFunc1Base< A * >, OpFunc1Base< ProcPtr >, OpFunc1Base< vector< A > * >, OpFunc2Base< A1, A2 >, OpFunc3Base< A1, A2, A3 >, OpFunc4Base< A1, A2, A3, A4 >, OpFunc5Base< A1, A2, A3, A4, A5 >, OpFunc6Base< A1, A2, A3, A4, A5, A6 >, GetOpFuncBase< A >, and LookupGetOpFuncBase< L, A >.
Referenced by Element::putOffNodeTargetsInDigest().
opBuffer()
virtual void OpFunc::opBuffer (const Eref & e, double * buf) const pure virtual
Executes the OpFunc by converting args.
Implemented in OpFunc0Base, OpFunc1Base< A >, OpFunc1Base< A * >, OpFunc1Base< ProcPtr >, OpFunc1Base< vector< A > * >, OpFunc2Base< A1, A2 >, OpFunc3Base< A1, A2, A3 >, OpFunc4Base< A1, A2, A3, A4 >, OpFunc5Base< A1, A2, A3, A4, A5 >, OpFunc6Base< A1, A2, A3, A4, A5, A6 >, GetOpFuncBase< A >, and LookupGetOpFuncBase< L, A >.
Referenced by innerGetVec().
opIndex()
unsigned int OpFunc::opIndex () const inline
Definition at line 68 of file OpFuncBase.h.
    {
        return opIndex_;
    }
References opIndex_.
Referenced by SetGet0::set().
ops()
vector< OpFunc * > & OpFunc::ops () static private
Definition at line 20 of file OpFuncBase.cpp.
{
    static vector< OpFunc* > op;
    return op;
}
Referenced by lookop(), OpFunc(), rebuildOpIndex(), and setIndex().
opVecBuffer()
virtual void OpFunc::opVecBuffer (const Eref & e, double * buf) const inline virtual
Executes the OpFunc for all data by converting a vector of args.
Reimplemented in OpFunc1Base< A >, OpFunc1Base< A * >, OpFunc1Base< ProcPtr >, OpFunc1Base< vector< A > * >, and OpFunc2Base< A1, A2 >.
Definition at line 63 of file OpFuncBase.h.
    {;}
rebuildOpIndex()
unsigned int OpFunc::rebuildOpIndex () static
cleans out the entire Ops vector. Returns size of orig vector.
Definition at line 49 of file OpFuncBase.cpp.
{
    for( vector< OpFunc* >::iterator
        i = ops().begin(); i != ops().end(); ++i ) {
        (*i)->opIndex_ = ~0U;
    }
    return ops().size();
}
References opIndex_, and ops().
Referenced by Cinfo::rebuildOpIndex().
rttiType()
virtual string OpFunc::rttiType () const pure virtual
Implemented in OpFunc0Base, OpFunc1Base< A >, OpFunc1Base< A * >, OpFunc1Base< ProcPtr >, OpFunc1Base< vector< A > * >, OpFunc2Base< A1, A2 >, OpFunc3Base< A1, A2, A3 >, OpFunc4Base< A1, A2, A3, A4 >, OpFunc5Base< A1, A2, A3, A4, A5 >, OpFunc6Base< A1, A2, A3, A4, A5, A6 >, LookupGetOpFuncBase< L, A >, and ProcOpFunc< T >.
Referenced by DestFinfo::rttiType().
setIndex()
bool OpFunc::setIndex (unsigned int i)
Used when rebuilding the Fid->OpFunc mapping.
Definition at line 58 of file OpFuncBase.cpp.
{
    if( opIndex_ == ~0U ) {
        opIndex_ = i;
        ops()[i] = this;
        return true;
    }
    /*
    cout << " OpFunc " << rttiType() <<
            " already setup. (old,new) index = (" <<
            opIndex_ << ", " << i << " )\n";
            */
    return false;
}
References opIndex_, and ops().
Referenced by Cinfo::rebuildOpIndex().
Member Data Documentation
opIndex_
unsigned int OpFunc::opIndex_ private
Definition at line 78 of file OpFuncBase.h.
Referenced by OpFunc(), opIndex(), rebuildOpIndex(), and setIndex().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/basecode/OpFuncBase.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/basecode/OpFuncBase.cpp