MOOSE - Multiscale Object Oriented Simulation Environment: MeshCompt Class Reference
MeshCompt Class Reference abstract
#include <MeshCompt.h>
Public Member Functions
void addRow (unsigned int index, const vector< double > &entry, const vector< unsigned int > &colIndex)
void clearExtendedMeshEntryVolume ()
Inherited virtual function to clear the vector of MeshEntryVolume.
double extendedMeshEntryVolume (unsigned int fid) const
Virtual function to return volume of mesh Entry, including.
void extendStencil (const ChemCompt *other, const vector< VoxelJunction > &vj)
Add boundary voxels to stencil for cross-solver junctions.
vector< unsigned int > getNeighbors (unsigned int fid) const
Looks up stencil to return vector of indices of coupled voxels.
virtual vector< unsigned int > getParentVoxel () const =0
const SparseMatrix< double > & getStencil () const
Returns entire sparse matrix of mesh. Used by diffusion solver.
unsigned int getStencilRow (unsigned int meshIndex, const double **entry, const unsigned int **colIndex) const
virtual const vector< double > & getVoxelArea () const =0
virtual const vector< double > & getVoxelLength () const =0
vector< double > innerGetStencilRate (unsigned int row) const
void innerResetStencil ()
virtual func implemented here.
MeshCompt ()
void setStencilSize (unsigned int numRows, unsigned int numCols)
~MeshCompt ()
Public Member Functions inherited from ChemCompt
void buildDefaultMesh (const Eref &e, double volume, unsigned int numEntries)
void buildJunction (ChemCompt *other, vector< VoxelJunction > &ret)
ChemCompt ()
void flipRet (vector< VoxelJunction > &ret) const
Utility function for swapping first and second in VoxelJunctions.
void getChildConcs (const Eref &e, vector< double > &childConcs) const
virtual vector< double > getCoordinates (unsigned int fid) const =0
Virtual function to return coords of mesh Entry.
virtual vector< double > getDiffusionArea (unsigned int fid) const =0
Virtual function to return diffusion X-section area per neighbor.
virtual vector< double > getDiffusionScaling (unsigned int fid) const =0
Virtual function to return scale factor for diffusion. 1 here.
unsigned int getDimensions () const
double getEntireVolume (const Eref &e) const
bool getIsMembraneBound () const
virtual unsigned int getMeshDimensions (unsigned int fid) const =0
Virtual function to return dimensions of specified entry.
virtual double getMeshEntryVolume (unsigned int fid) const =0
Virtual function to return volume of mesh Entry.
virtual unsigned int getMeshType (unsigned int fid) const =0
Virtual function to return MeshType of specified entry.
string getMethod () const
unsigned int getNumEntries () const
vector< double > getOneVoxelMidpoint (unsigned int vox) const
Looks up specified voxel midpoint, from vGetVoxelMidpoint.
double getOneVoxelVolume (const Eref &e, unsigned int voxel) const
vector< unsigned int > getStencilIndex (unsigned int row) const
vector< double > getStencilRate (unsigned int row) const
vector< double > getVoxelMidpoint () const
Returns vector of all voxel midpoints in compartment.
vector< double > getVoxelVolume () const
Returns vector of all voxel volumes in compartment.
void handleNodeInfo (const Eref &e, unsigned int numNodes, unsigned int numThreads)
virtual void indexToSpace (unsigned int index, double &x, double &y, double &z) const =0
virtual void innerBuildDefaultMesh (const Eref &e, double volume, unsigned int numEntries)=0
virtual unsigned int innerGetDimensions () const =0
virtual unsigned int innerGetNumEntries () const =0
virtual void innerHandleNodeInfo (const Eref &e, unsigned int numNodes, unsigned int numThreads)=0
virtual void innerSetNumEntries (unsigned int n)=0
MeshEntry * lookupEntry (unsigned int index)
virtual void matchMeshEntries (const ChemCompt *other, vector< VoxelJunction > &ret) const =0
virtual double nearest (double x, double y, double z, unsigned int &index) const =0
void resetStencil ()
unsigned int setChildConcs (const Eref &e, const vector< double > &childConcs, unsigned int start) const
void setEntireVolume (const Eref &e, double volume)
void setIsMembraneBound (bool v)
virtual void setMeshEntryVolume (unsigned int fid, double volume)
void setMethod (string method)
void setNumEntries (unsigned int num)
void setOneVoxelVolume (const Eref &e, unsigned int voxel, double volume)
void setVolumeNotRates (double volume)
virtual double vGetEntireVolume () const =0
virtual const vector< double > & vGetVoxelMidpoint () const =0
Virtual func so that derived classes can return voxel midpoint.
virtual const vector< double > & vGetVoxelVolume () const =0
Virtual func so that derived classes can pass voxel volume back.
virtual bool vSetVolumeNotRates (double volume)=0
Virtual function for actually doing this.
virtual ~ChemCompt ()
Private Attributes
SparseMatrix< double > coreStencil_
Handles the core stencil for own vol.
vector< double > extendedMeshEntryVolume_
SparseMatrix< double > m_
Handles stencil for core + abutting voxels.
Additional Inherited Members
Static Public Member Functions inherited from ChemCompt
static double distance (double x, double y, double z)
static const Cinfo * initCinfo ()
static SrcFinfo1< vector< double > > * voxelVolOut ()
Detailed Description
The MeshCompt represents the base class for all compartments which are set up as a meshes. These include CubeMesh, CylMesh and NeuroMesh. The MeshCompt handles the stencil that is the core of all the meshes. The stencil specifies which compartments diffuse into each other, and by how much.
Definition at line 20 of file MeshCompt.h.
Constructor & Destructor Documentation
MeshCompt()
MeshCompt::MeshCompt ()
Definition at line 24 of file MeshCompt.cpp.
{
    ;
}
~MeshCompt()
MeshCompt::~MeshCompt ()
Definition at line 29 of file MeshCompt.cpp.
{
    ;
}
Member Function Documentation
addRow()
void MeshCompt::addRow (unsigned int index, const vector< double > & entry, const vector< unsigned int > & colIndex)
Definition at line 98 of file MeshCompt.cpp.
{
    coreStencil_.addRow( index, entry, colIndex );
}
References SparseMatrix< T >::addRow(), and coreStencil_.
Referenced by CubeMesh::buildStencil(), CylMesh::buildStencil(), and NeuroMesh::buildStencil().
clearExtendedMeshEntryVolume()
void MeshCompt::clearExtendedMeshEntryVolume () virtual
Inherited virtual function to clear the vector of MeshEntryVolume.
Implements ChemCompt.
Definition at line 43 of file MeshCompt.cpp.
{
    extendedMeshEntryVolume_.clear();
}
References extendedMeshEntryVolume_.
extendedMeshEntryVolume()
double MeshCompt::extendedMeshEntryVolume (unsigned int fid) const virtual
Virtual function to return volume of mesh Entry, including.
Utility function to return volume of any voxel including those diffusively coupled and aubtting the present volume.
Implements ChemCompt.
Reimplemented in NeuroMesh, PresynMesh, PsdMesh, and SpineMesh.
Definition at line 36 of file MeshCompt.cpp.
{
    assert( index < extendedMeshEntryVolume_.size() );
    return extendedMeshEntryVolume_[ index ];
}
References extendedMeshEntryVolume_.
Referenced by CubeMesh::extendedMeshEntryVolume(), CylMesh::extendedMeshEntryVolume(), EndoMesh::extendedMeshEntryVolume(), NeuroMesh::extendedMeshEntryVolume(), PsdMesh::extendedMeshEntryVolume(), and SpineMesh::extendedMeshEntryVolume().
extendStencil()
void MeshCompt::extendStencil (const ChemCompt * other, const vector< VoxelJunction > & vj) virtual
Add boundary voxels to stencil for cross-solver junctions.
extendStencil adds voxels to the current stencil m_, to build up a monolithic stencil that also handles the entries just past all the boundaries. This function may be called many times to deal with the addition of multiple junctions. Before the first of these calls, the m_ matrix should be set to the coreStencil_.
Organizes vj by voxel, that is, by row.
Implements ChemCompt.
Definition at line 121 of file MeshCompt.cpp.
{
    // Maps from remote meshIndex (in vj) to local index of proxy voxel.
    map< unsigned int, unsigned int > meshMap;
    map< unsigned int, unsigned int >::iterator mmi;
    // Maps from local index of proxy voxel back to remote meshIndex.
    vector< unsigned int > meshBackMap;
    unsigned int coreSize = coreStencil_.nRows();
    unsigned int oldSize = m_.nRows();
    unsigned int newSize = oldSize;
    vector< vector< VoxelJunction > > vvj( coreSize );
    for ( vector< VoxelJunction >::const_iterator
                    i = vj.begin(); i != vj.end(); ++i ) {
        mmi = meshMap.find( i->second );
        if ( mmi == meshMap.end() ) {
            assert( i->first < coreSize );
            meshBackMap.push_back( i->second );
            meshMap[i->second] = newSize++;
            vvj[i->first].push_back( *i );
        }
    }
    vector< vector< VoxelJunction > > vvjCol( newSize );
    SparseMatrix< double > oldM = m_;
    m_.clear();
    m_.setSize( newSize, newSize );
    for ( unsigned int i = 0; i < newSize; ++i ) {
        vector< VoxelJunction > temp;
        if ( i < oldSize ) { // Copy over old matrix.
            const double* entry;
            const unsigned int* colIndex;
            unsigned int num = oldM.getRow( i, &entry, &colIndex );
            temp.resize( num );
            for ( unsigned int j = 0; j < num; ++j ) {
                temp[j].first = colIndex[j];
                temp[j].diffScale = entry[j];
            }
        }
        if ( i < coreSize ) { // Set up diffusion into proxy voxels.
            for ( vector< VoxelJunction >::const_iterator
                j = vvj[i].begin(); j != vvj[i].end(); ++j )
            {
                unsigned int row = j->first;
                assert( row == i );
                unsigned int col = meshMap[j->second];
                assert( col >= oldSize );
                temp.push_back(
                        VoxelJunction( col, EMPTY, j->diffScale ) );
                vvjCol[col].push_back(
                        VoxelJunction( row, EMPTY, j->diffScale ) );
            }
        }
        if ( i >= oldSize ) { // Set up diffusion from proxy to old voxels
            for ( vector< VoxelJunction >::const_iterator
                j = vvjCol[i].begin(); j != vvjCol[i].end(); ++j )
            {
                temp.push_back( *j );
            }
        }
        // Now we've filled in all the VoxelJunctions for the new row.
        sort( temp.begin(), temp.end() );
        vector< double > e( temp.size() );
        vector< unsigned int > c( temp.size() );
        for ( unsigned int j = 0; j < temp.size(); ++j ) {
            e[j] = temp[j].diffScale;
            c[j] = temp[j].first;
        }
        m_.addRow( i, e, c );
    }
    // Fill in the volumes of the external mesh entries
    for ( vector< unsigned int>::const_iterator
            i = meshBackMap.begin(); i != meshBackMap.end(); ++i ) {
        extendedMeshEntryVolume_.push_back( other->getMeshEntryVolume( *i ) );
    }
}
References SparseMatrix< T >::addRow(), SparseMatrix< T >::clear(), coreStencil_, VoxelJunction::diffScale, EMPTY, extendedMeshEntryVolume_, VoxelJunction::first, ChemCompt::getMeshEntryVolume(), SparseMatrix< T >::getRow(), m_, SparseMatrix< T >::nRows(), VoxelJunction::second, SparseMatrix< T >::setSize(), and VoxelJunction::VoxelJunction().
Referenced by testCubeMeshExtendStencil().
getNeighbors()
vector< unsigned int > MeshCompt::getNeighbors (unsigned int fid) const virtual
Looks up stencil to return vector of indices of coupled voxels.
Virtual function to return info on Entries connected to this one.
Implements ChemCompt.
Definition at line 69 of file MeshCompt.cpp.
{
    const double* entry;
    const unsigned int *colIndex;
    unsigned int n = m_.getRow( row, &entry, &colIndex );
    vector< unsigned int > ret;
    ret.insert( ret.end(), colIndex, colIndex + n );
    return ret;
}
References SparseMatrix< T >::getRow(), and m_.
Referenced by NeuroMesh::getDiffusionArea(), and testCubeMesh().
getParentVoxel()
virtual vector< unsigned int > MeshCompt::getParentVoxel () const pure virtual
Implemented in CubeMesh, CylMesh, EndoMesh, NeuroMesh, PresynMesh, PsdMesh, and SpineMesh.
Referenced by Dsolve::build(), and EndoMesh::getParentVoxel().
getStencil()
const SparseMatrix< double > & MeshCompt::getStencil () const
Returns entire sparse matrix of mesh. Used by diffusion solver.
Definition at line 60 of file MeshCompt.cpp.
{
        return coreStencil_;
}
References coreStencil_.
getStencilRow()
unsigned int MeshCompt::getStencilRow (unsigned int meshIndex, const double ** entry, const unsigned int ** colIndex) const virtual
Derived function to return SparseMatrix-style row info for specified mesh entry.
Implements ChemCompt.
Definition at line 54 of file MeshCompt.cpp.
{
        return m_.getRow( meshIndex, entry, colIndex );
}
References SparseMatrix< T >::getRow(), and m_.
Referenced by testCubeMeshExtendStencil().
getVoxelArea()
virtual const vector< double > & MeshCompt::getVoxelArea () const pure virtual
Implemented in CubeMesh, CylMesh, EndoMesh, NeuroMesh, PresynMesh, PsdMesh, and SpineMesh.
Referenced by Dsolve::build().
getVoxelLength()
virtual const vector< double > & MeshCompt::getVoxelLength () const pure virtual
Implemented in CubeMesh, CylMesh, EndoMesh, NeuroMesh, PresynMesh, PsdMesh, and SpineMesh.
Referenced by Dsolve::build(), and EndoMesh::matchMeshEntries().
innerGetStencilRate()
vector< double > MeshCompt::innerGetStencilRate (unsigned int row) const virtual
Looks up stencil to return vector of diffusion coupling to neighbor voxels.
Implements ChemCompt.
Definition at line 85 of file MeshCompt.cpp.
{
    const double* entry;
    const unsigned int *colIndex;
    unsigned int n = m_.getRow( row, &entry, &colIndex );
    vector< double > ret;
    ret.insert( ret.end(), entry, entry + n );
    return ret;
}
References SparseMatrix< T >::getRow(), and m_.
innerResetStencil()
void MeshCompt::innerResetStencil () virtual
virtual func implemented here.
Implements ChemCompt.
Definition at line 49 of file MeshCompt.cpp.
{
    m_ = coreStencil_;
}
References coreStencil_, and m_.
Referenced by CubeMesh::buildStencil(), CylMesh::buildStencil(), NeuroMesh::buildStencil(), PsdMesh::buildStencil(), and SpineMesh::buildStencil().
setStencilSize()
void MeshCompt::setStencilSize (unsigned int numRows, unsigned int numCols)
Definition at line 106 of file MeshCompt.cpp.
{
    coreStencil_.clear();
    coreStencil_.setSize( numRows, numCols );
}
References SparseMatrix< T >::clear(), coreStencil_, and SparseMatrix< T >::setSize().
Referenced by CubeMesh::buildStencil(), CylMesh::buildStencil(), NeuroMesh::buildStencil(), PsdMesh::buildStencil(), and SpineMesh::buildStencil().
Member Data Documentation
coreStencil_
SparseMatrix< double > MeshCompt::coreStencil_ private
Handles the core stencil for own vol.
Definition at line 74 of file MeshCompt.h.
Referenced by addRow(), extendStencil(), getStencil(), innerResetStencil(), and setStencilSize().
extendedMeshEntryVolume_
vector< double > MeshCompt::extendedMeshEntryVolume_ private
vector of meshEntryVolumes for abutting surfaces, needed to compute diffusion rates across junctions. Indexed from zero.
Definition at line 85 of file MeshCompt.h.
Referenced by clearExtendedMeshEntryVolume(), extendedMeshEntryVolume(), and extendStencil().
m_
SparseMatrix< double > MeshCompt::m_ private
Handles stencil for core + abutting voxels.
Definition at line 77 of file MeshCompt.h.
Referenced by extendStencil(), getNeighbors(), getStencilRow(), innerGetStencilRate(), and innerResetStencil().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/mesh/MeshCompt.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/mesh/MeshCompt.cpp