MOOSE - Multiscale Object Oriented Simulation Environment: DiffAmp Class Reference
DiffAmp Class Reference
#include <DiffAmp.h>
Public Member Functions
DiffAmp ()
double getGain () const
double getOutput () const
double getSaturation () const
void minusFunc (double input)
void plusFunc (double input)
void process (const Eref &e, ProcPtr p)
void reinit (const Eref &e, ProcPtr p)
void setGain (double gain)
void setSaturation (double saturation)
~DiffAmp ()
Static Public Member Functions
static const Cinfo * initCinfo ()
Protected Attributes
double gain_
double minus_
double output_
double plus_
double saturation_
Detailed Description
Definition at line 36 of file DiffAmp.h.
Constructor & Destructor Documentation
DiffAmp()
DiffAmp::DiffAmp ()
Definition at line 147 of file DiffAmp.cpp.
                :gain_(1.0), saturation_(DBL_MAX), plus_(0), minus_(0), output_(0)
{
}
References gain_, minus_, output_, plus_, and saturation_.
~DiffAmp()
DiffAmp::~DiffAmp ()
Definition at line 150 of file DiffAmp.cpp.
                 {
    ;
}
Member Function Documentation
getGain()
double DiffAmp::getGain () const
Definition at line 173 of file DiffAmp.cpp.
{
    return gain_;
}
References gain_.
Referenced by initCinfo().
getOutput()
double DiffAmp::getOutput () const
Definition at line 183 of file DiffAmp.cpp.
{
    return output_;
}
References output_.
Referenced by initCinfo().
getSaturation()
double DiffAmp::getSaturation () const
Definition at line 178 of file DiffAmp.cpp.
{
    return saturation_;
}
References saturation_.
Referenced by initCinfo().
initCinfo()
const Cinfo * DiffAmp::initCinfo () static
Definition at line 51 of file DiffAmp.cpp.
{
    static ValueFinfo<DiffAmp, double> gain( "gain",
                                             "Gain of the amplifier. The output of the amplifier is the difference"
                                             " between the totals in plus and minus inputs multiplied by the"
                                             " gain. Defaults to 1" ,
                                             &DiffAmp::setGain,
                                             &DiffAmp::getGain);
    static ValueFinfo<DiffAmp, double > saturation( "saturation",
                                                    "Saturation is the bound on the output. If output goes beyond the +/-"
                                                    "saturation range, it is truncated to the closer of +saturation and"
                                                    " -saturation. Defaults to the maximum double precision floating point"
                                                    " number representable on the system." ,
                                                    &DiffAmp::setSaturation,
                                                    &DiffAmp::getSaturation);
    static ReadOnlyValueFinfo<DiffAmp, double> output( "outputValue",
                                               "Output of the amplifier, i.e. gain * (plus - minus)." ,
                                               &DiffAmp::getOutput);
    // Dest messages
    static DestFinfo gainIn( "gainIn",
                             "Destination message to control gain dynamically.",
                             new OpFunc1<DiffAmp, double> (&DiffAmp::setGain));
    static DestFinfo plusIn( "plusIn",
                      "Positive input terminal of the amplifier. All the messages connected"
                      " here are summed up to get total positive input.",
                      new OpFunc1<DiffAmp, double> (&DiffAmp::plusFunc));
    static DestFinfo minusIn( "minusIn",
                      "Negative input terminal of the amplifier. All the messages connected"
                      " here are summed up to get total negative input.",
                      new OpFunc1<DiffAmp, double> (&DiffAmp::minusFunc));
    // Shared messages
    static DestFinfo process( "process",
                              "Handles process call, updates internal time stamp.",
                              new ProcOpFunc< DiffAmp >( &DiffAmp::process ) );
    static DestFinfo reinit( "reinit",
                             "Handles reinit call.",
                             new ProcOpFunc< DiffAmp >( &DiffAmp::reinit ) );
    static Finfo* processShared[] =
            {
        &process, &reinit
            };
    static SharedFinfo proc( "proc",
                             "This is a shared message to receive Process messages "
                             "from the scheduler objects."
                             "The first entry in the shared msg is a MsgDest "
                             "for the Process operation. It has a single argument, "
                             "ProcInfo, which holds lots of information about current "
                             "time, thread, dt and so on. The second entry is a MsgDest "
                             "for the Reinit operation. It also uses ProcInfo. ",
                             processShared, sizeof( processShared ) / sizeof( Finfo* )
                             );
    static Finfo * diffAmpFinfos[] = {
        &gain,
        &saturation,
        &output,
        &gainIn,
        &plusIn,
        &minusIn,
        outputOut(),
        &proc
    };
    static string doc[] = {
        "Name", "DiffAmp",
        "Author", "Subhasis Ray, 2008, NCBS",
        "Description", "A difference amplifier. "
        "Output is the difference between the total plus inputs and the total "
        "minus inputs multiplied by gain. Gain can be set statically as a field"
        " or can be a destination message and thus dynamically determined by the"
        " output of another object. Same as GENESIS diffamp object."
    };
    static Dinfo<DiffAmp> dinfo;
    static Cinfo diffAmpCinfo(
            "DiffAmp",
            Neutral::initCinfo(),
            diffAmpFinfos,
            sizeof(diffAmpFinfos)/sizeof(Finfo*),
            &dinfo,
            doc,
            sizeof(doc)/sizeof(string)
);
    return &diffAmpCinfo;
}
References Cinfo::Cinfo(), DestFinfo::DestFinfo(), getGain(), getOutput(), getSaturation(), Neutral::initCinfo(), minusFunc(), OpFunc1< T, A >::OpFunc1(), outputOut(), plusFunc(), process(), ProcOpFunc< T >::ProcOpFunc(), ReadOnlyValueFinfo< T, F >::ReadOnlyValueFinfo(), reinit(), setGain(), setSaturation(), SharedFinfo::SharedFinfo(), and ValueFinfo< T, F >::ValueFinfo().
minusFunc()
void DiffAmp::minusFunc (double input)
Definition at line 158 of file DiffAmp.cpp.
{
    minus_ += input;
}
References minus_.
Referenced by initCinfo().
plusFunc()
void DiffAmp::plusFunc (double input)
Definition at line 153 of file DiffAmp.cpp.
{
    plus_ += input;
}
References plus_.
Referenced by initCinfo().
process()
void DiffAmp::process (const Eref & e, ProcPtr p)
Definition at line 188 of file DiffAmp.cpp.
{
    double output = gain_ * (plus_ - minus_);
    plus_ = 0.0;
    minus_ = 0.0;
    if ( output > saturation_ ) {
    output = saturation_;
    }
    if ( output < -saturation_ ) {
    output = -saturation_;
    }
    output_ = output;
    outputOut()->send(e, output_);
}
References gain_, minus_, output_, outputOut(), plus_, saturation_, and SrcFinfo1< T >::send().
Referenced by initCinfo().
reinit()
void DiffAmp::reinit (const Eref & e, ProcPtr p)
Definition at line 203 of file DiffAmp.cpp.
{
    // What is the right thing to do?? Should we actually do a process step??
    output_ = 0.0;
    plus_ = 0.0;
    minus_ = 0.0;
    outputOut()->send(e, output_);
}
References minus_, output_, outputOut(), plus_, and SrcFinfo1< T >::send().
Referenced by initCinfo().
setGain()
void DiffAmp::setGain (double gain)
Definition at line 163 of file DiffAmp.cpp.
{
    gain_ = gain;
}
References gain_.
Referenced by initCinfo().
setSaturation()
void DiffAmp::setSaturation (double saturation)
Definition at line 168 of file DiffAmp.cpp.
{
    saturation_ = saturation;
}
References saturation_.
Referenced by initCinfo().
Member Data Documentation
gain_
double DiffAmp::gain_ protected
Definition at line 54 of file DiffAmp.h.
Referenced by DiffAmp(), getGain(), process(), and setGain().
minus_
double DiffAmp::minus_ protected
Definition at line 57 of file DiffAmp.h.
Referenced by DiffAmp(), minusFunc(), process(), and reinit().
output_
double DiffAmp::output_ protected
Definition at line 58 of file DiffAmp.h.
Referenced by DiffAmp(), getOutput(), process(), and reinit().
plus_
double DiffAmp::plus_ protected
Definition at line 56 of file DiffAmp.h.
Referenced by DiffAmp(), plusFunc(), process(), and reinit().
saturation_
double DiffAmp::saturation_ protected
Definition at line 55 of file DiffAmp.h.
Referenced by DiffAmp(), getSaturation(), process(), and setSaturation().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/device/DiffAmp.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/device/DiffAmp.cpp