MOOSE - Multiscale Object Oriented Simulation Environment: LookupTable Class Reference
LookupTable Class Reference
#include <RateLookup.h>
Public Member Functions
void addColumns (int species, const vector< double > &C1, const vector< double > &C2)
Adds the columns for a given species. Columns supplied are C1 and C2.
void column (unsigned int species, LookupColumn &column)
bool empty () const
void lookup (const LookupColumn &column, const LookupRow &row, double &C1, double &C2)
Actually performs the lookup and the linear interpolation.
LookupTable ()
LookupTable (double min, double max, unsigned int nDivs, unsigned int nSpecies)
number of species (no. of columns / 2)
void row (double x, LookupRow &row)
Private Attributes
double dx_
double max_
max of the voltage / caConc range
double min_
min of the voltage / caConc range
unsigned int nColumns_
(# columns) = 2 * (# species)
unsigned int nPts_
vector< double > table_
Flattened table.
Detailed Description
Definition at line 27 of file RateLookup.h.
Constructor & Destructor Documentation
LookupTable() [1/2]
LookupTable::LookupTable () inline
Definition at line 30 of file RateLookup.h.
{ ; }
LookupTable() [2/2]
LookupTable::LookupTable (double min, double max, unsigned int nDivs, unsigned int nSpecies)
number of species (no. of columns / 2)
Parameters
min min of range
max max of range
nDivs number of divisions (~ no. of rows)
Definition at line 17 of file RateLookup.cpp.
{
    min_ = min;
    max_ = max;
    // Number of points is 1 more than number of divisions.
    // Then add one more since we may interpolate at the last point in the table.
    nPts_ = nDivs + 1 + 1;
    dx_ = ( max - min ) / nDivs;
    // Every row has 2 entries for each type of gate
    nColumns_ = 2 * nSpecies;
    //~ interpolate_.resize( nSpecies );
    table_.resize( nPts_ * nColumns_ );
}
References dx_, max_, min_, nColumns_, nPts_, and table_.
Referenced by HSolveActive::createLookupTables().
Member Function Documentation
addColumns()
void LookupTable::addColumns (int species, const vector< double > & C1, const vector< double > & C2)
Adds the columns for a given species. Columns supplied are C1 and C2.
Definition at line 33 of file RateLookup.cpp.
{
    vector< double >::const_iterator ic1 = C1.begin();
    vector< double >::const_iterator ic2 = C2.begin();
    vector< double >::iterator iTable = table_.begin() + 2 * species;
    // Loop until last but one point
    for ( unsigned int igrid = 0; igrid < nPts_ - 1 ; ++igrid ) {
        *( iTable )     = *ic1;
        *( iTable + 1 ) = *ic2;
        iTable += nColumns_;
        ++ic1, ++ic2;
    }
    // Then duplicate the last point
    *( iTable )     = C1.back();
    *( iTable + 1 ) = C2.back();
    //~ interpolate_[ species ] = interpolate;
}
References nColumns_, nPts_, and table_.
Referenced by HSolveActive::createLookupTables().
column()
void LookupTable::column (unsigned int species, LookupColumn & column)
Definition at line 58 of file RateLookup.cpp.
{
    column.column = 2 * species;
    //~ column.interpolate = interpolate_[ species ];
}
References LookupColumn::column.
Referenced by HSolveActive::createLookupTables().
empty()
bool LookupTable::empty () const inline
Definition at line 65 of file RateLookup.h.
                       {
    return table_.empty();
    }
References table_.
Referenced by HSolveActive::advanceChannels(), and HSolveActive::reinitChannels().
lookup()
void LookupTable::lookup (const LookupColumn & column, const LookupRow & row, double & C1, double & C2)
Actually performs the lookup and the linear interpolation.
Definition at line 82 of file RateLookup.cpp.
{
    double a, b;
    double *ap, *bp;
    ap = row.row + column.column;
    //~ if ( ! column.interpolate ) {
        //~ C1 = *ap;
        //~ C2 = *( ap + 1 );
        //~
        //~ return;
    //~ }
    bp = ap + nColumns_;
    a = *ap;
    b = *bp;
    C1 = a + ( b - a ) * row.fraction;
    a = *( ap + 1 );
    b = *( bp + 1 );
    C2 = a + ( b - a ) * row.fraction;
}
References LookupColumn::column, LookupRow::fraction, nColumns_, and LookupRow::row.
Referenced by HSolveActive::advanceChannels(), and HSolveActive::reinitChannels().
row()
void LookupTable::row (double x, LookupRow & row)
Returns the row corresponding to x in the "row" parameter. i.e., returns the leftover fraction and the row's start address.
Definition at line 64 of file RateLookup.cpp.
{
    if(table_.empty()) {
    cerr << "LookupTable::row : Error: table is empty" << endl;
        return;
    }
    if ( x < min_ )
        x = min_;
    else if ( x > max_ )
        x = max_;
    double div = ( x - min_ ) / dx_;
    unsigned int integer = ( unsigned int )( div );
    row.fraction = div - integer;
    row.row = &( table_.front() ) + integer * nColumns_;
}
References dx_, LookupRow::fraction, max_, min_, nColumns_, LookupRow::row, and table_.
Referenced by HSolveActive::advanceChannels(), and HSolveActive::reinitChannels().
Member Data Documentation
dx_
double LookupTable::dx_ private
This is the smallest difference: (max - min) / nDivs
Definition at line 76 of file RateLookup.h.
Referenced by LookupTable(), and row().
max_
double LookupTable::max_ private
max of the voltage / caConc range
Definition at line 72 of file RateLookup.h.
Referenced by LookupTable(), and row().
min_
double LookupTable::min_ private
min of the voltage / caConc range
Definition at line 71 of file RateLookup.h.
Referenced by LookupTable(), and row().
nColumns_
unsigned int LookupTable::nColumns_ private
(# columns) = 2 * (# species)
Definition at line 78 of file RateLookup.h.
Referenced by addColumns(), lookup(), LookupTable(), and row().
nPts_
unsigned int LookupTable::nPts_ private
Number of rows in the table. Equal to nDivs + 2, so that interpol. is safe at either end.
Definition at line 73 of file RateLookup.h.
Referenced by addColumns(), and LookupTable().
table_
vector< double > LookupTable::table_ private
Flattened table.
Definition at line 70 of file RateLookup.h.
Referenced by addColumns(), empty(), LookupTable(), and row().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/hsolve/RateLookup.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/hsolve/RateLookup.cpp