MOOSE - Multiscale Object Oriented Simulation Environment: TestId Class Reference
TestId Class Reference
Public Member Functions
Id getId () const
void setId (Id id)
Static Public Member Functions
static const Cinfo * initCinfo ()
Private Attributes
Id id_
Detailed Description
Definition at line 913 of file testAsync.cpp.
Member Function Documentation
getId()
Id TestId::getId () const inline
Definition at line 919 of file testAsync.cpp.
    {
        return id_;
    }
References id_.
Referenced by initCinfo().
initCinfo()
const Cinfo * TestId::initCinfo () static
Definition at line 930 of file testAsync.cpp.
{
    static ValueFinfo<TestId, Id> id("id", "test", &TestId::setId,
                                     &TestId::getId);
    static Finfo* testIdFinfos[] = {&id};
    static Cinfo testIdCinfo(
        "TestIdRepeatAssignment", Neutral::initCinfo(), testIdFinfos,
        sizeof(testIdFinfos) / sizeof(Finfo*), new Dinfo<TestId>());
    return &testIdCinfo;
}
References Cinfo::Cinfo(), Dinfo< D >::Dinfo(), getId(), Neutral::initCinfo(), setId(), and ValueFinfo< T, F >::ValueFinfo().
setId()
void TestId::setId (Id id) inline
Definition at line 915 of file testAsync.cpp.
    {
        id_ = id;
    }
References id_.
Referenced by initCinfo().
Member Data Documentation
id_
Id TestId::id_ private
Definition at line 926 of file testAsync.cpp.
Referenced by getId(), and setId().
The documentation for this class was generated from the following file:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/basecode/testAsync.cpp