MOOSE - Multiscale Object Oriented Simulation Environment: HHChannel Class Reference
HHChannel Class Reference
#include <HHChannel.h>
Public Member Functions
bool checkOriginal (Id chanId) const override
Returns true if channel is original, false if copy.
void destroyGate (const Eref &e, string gateType) override
unsigned int getNumXgates () const
unsigned int getNumYgates () const
unsigned int getNumZgates () const
HHGate * getXgate (unsigned int i)
HHGate * getYgate (unsigned int i)
HHGate * getZgate (unsigned int i)
HHChannel ()
void innerCreateGate (const string &gateName, HHGate **gatePtr, Id chanId, Id gateId)
Inner utility function for creating the gate.
void innerDestroyGate (const string &gateName, HHGate **gatePtr, Id chanId)
void innerSetXpower (double Xpower)
void innerSetYpower (double Ypower)
void innerSetZpower (double Zpower)
void setNumGates (unsigned int num)
void vCreateGate (const Eref &e, string gateType) override
void vHandleConc (const Eref &e, double conc) override
void vProcess (const Eref &e, ProcPtr p) override
void vReinit (const Eref &e, ProcPtr p) override
~HHChannel ()
Public Member Functions inherited from HHChannelBase
void createGate (const Eref &e, string gateType)
int getInstant (const Eref &e) const
int getUseConcentration (const Eref &e) const
double getX (const Eref &e) const
HHGate * getXgate (unsigned int i)
double getXpower (const Eref &e) const
double getY (const Eref &e) const
HHGate * getYgate (unsigned int i)
double getYpower (const Eref &e) const
double getZ (const Eref &e) const
HHGate * getZgate (unsigned int i)
double getZpower (const Eref &e) const
void handleConc (const Eref &e, double conc)
HHChannelBase ()
bool setGatePower (const Eref &e, double power, double *assignee, const string &gateType)
void setInstant (const Eref &e, int Instant)
void setNumGates (unsigned int num)
void setUseConcentration (const Eref &e, int value)
void setX (const Eref &e, double X)
void setXpower (const Eref &e, double Xpower)
void setY (const Eref &e, double Y)
void setYpower (const Eref &e, double Ypower)
void setZ (const Eref &e, double Z)
void setZpower (const Eref &e, double Zpower)
virtual int vGetInstant (const Eref &e) const
virtual double vGetX (const Eref &e) const
virtual double vGetY (const Eref &e) const
virtual double vGetZ (const Eref &e) const
virtual void vSetInstant (const Eref &e, int Instant)
virtual void vSetSolver (const Eref &e, Id hsolve)
virtual void vSetUseConcentration (const Eref &e, int value)
virtual void vSetX (const Eref &e, double X)
virtual void vSetXpower (const Eref &e, double Xpower)
virtual void vSetY (const Eref &e, double Y)
virtual void vSetYpower (const Eref &e, double Ypower)
virtual void vSetZ (const Eref &e, double Z)
virtual void vSetZpower (const Eref &e, double Zpower)
virtual ~HHChannelBase ()=0
Public Member Functions inherited from ChanCommon
ChanCommon ()
double getGbar () const
Utility function to acces Gbar.
double getVm () const
Utility function to access Vm.
void sendProcessMsgs (const Eref &e, const ProcPtr info)
void sendReinitMsgs (const Eref &e, const ProcPtr info)
void updateIk ()
double vGetEk (const Eref &e) const override
double vGetGbar (const Eref &e) const override
double vGetGk (const Eref &e) const override
double vGetIk (const Eref &e) const override
double vGetModulation (const Eref &e) const override
void vHandleVm (double Vm) override
void vSetEk (const Eref &e, double Ek) override
void vSetGbar (const Eref &e, double Gbar) override
void vSetGk (const Eref &e, double Gk) override
void vSetIk (const Eref &e, double Ic) override
void vSetModulation (const Eref &e, double modulation) override
virtual ~ChanCommon ()=0
Public Member Functions inherited from ChanBase
ChanBase ()
double getEk (const Eref &e) const
double getGbar (const Eref &e) const
double getGk (const Eref &e) const
double getIk (const Eref &e) const
double getModulation (const Eref &e) const
void handleVm (double Vm)
void process (const Eref &e, const ProcPtr info)
void reinit (const Eref &e, const ProcPtr info)
void setEk (const Eref &e, double Ek)
void setGbar (const Eref &e, double Gbar)
void setGk (const Eref &e, double Gk)
void setIk (const Eref &e, double Ic)
void setModulation (const Eref &e, double modulation)
virtual ~ChanBase ()=0
Static Public Member Functions
static const Cinfo * initCinfo ()
Static Public Member Functions inherited from HHChannelBase
static const Cinfo * initCinfo ()
static double power1 (double x, double p)
static double power2 (double x, double p)
static double power3 (double x, double p)
static double power4 (double x, double p)
static double powerN (double x, double p)
static PFDD selectPower (double power)
static void zombify (Element *orig, const Cinfo *zClass, Id hsolve)
Static Public Member Functions inherited from ChanCommon
static const Cinfo * initCinfo ()
Specify the Class Info static variable for initialization.
Static Public Member Functions inherited from ChanBase
static SrcFinfo2< double, double > * channelOut ()
static SrcFinfo1< double > * IkOut ()
static const Cinfo * initCinfo ()
Specify the Class Info static variable for initialization.
static SrcFinfo1< double > * permeability ()
Private Attributes
double conc_
Conc_ is input variable for Ca-dependent channels.
HHGate * xGate_
HHGate * yGate_
HHGate data structure for the yGate.
HHGate * zGate_
HHGate data structure for the yGate.
Additional Inherited Members
Protected Member Functions inherited from HHChannelBase
double integrate (double state, double dt, double A, double B)
Protected Member Functions inherited from ChanCommon
double getModulation () const
Protected Attributes inherited from HHChannelBase
double g_
int instant_
Id myId_
double(* takeXpower_)(double, double)
double(* takeYpower_)(double, double)
double(* takeZpower_)(double, double)
bool useConcentration_
Flag for use of conc for input to Z gate calculations.
double X_
bool xInited_
Flag to indicate if gates have been created.
double Xpower_
Exponent for X gate.
double Y_
bool yInited_
double Ypower_
Exponent for Y gate.
double Z_
bool zInited_
double Zpower_
Exponent for Z gate.
Protected Attributes inherited from ChanCommon
double Vm_
Vm_ is input variable from compartment, used for most rates.
Static Protected Attributes inherited from HHChannelBase
static const double EPSILON = 1.0e-10
static const int INSTANT_X = 1
static const int INSTANT_Y = 2
static const int INSTANT_Z = 4
Detailed Description
The HHChannel class sets up a Hodkin-Huxley type ion channel. The form used here is quite general and can handle up to 3 gates, named X, Y and Z. The Z gate can be a function of concentration as well as voltage. The gates are normally computed using the form
       alpha(V)
closed <---------—> open beta(V)
where the rates for the transition are alpha and beta, and both are functions of V. The state variables for each gate (X_, Y_, and Z_) are the fraction in the open state.
Gates can also be computed instantaneously, giving the instantaneous ratio of alpha to beta rather than solving the above conversion process. The actual functions alpha and beta are provided by an auxiliary class, the HHGate. The idea is that all copies of a channel share the same gate, thus saving a great deal of space. It also makes it possible to cleanly change the parameters of all the channels of a give class, all at once. Should one want to mutate a subset of channels, they just need to set up separate gates.
HHGates are implemented as a special category of FieldElement, so that they can be accessed as readonly pointers available to the HHChannel. The FieldElement containing the HHGate appears as a child Element of the HHChannel. The HHChannel Element can be an array; the associated HHGate is a singleton. So there has to be a local copy of the HHGate on each node.
Definition at line 55 of file HHChannel.h.
Constructor & Destructor Documentation
HHChannel()
HHChannel::HHChannel ()
Definition at line 75 of file HHChannel.cpp.
: conc_(0.0), xGate_(nullptr), yGate_(nullptr), zGate_(nullptr) { ; }
References conc_, xGate_, yGate_, and zGate_.
~HHChannel()
HHChannel::~HHChannel ()
Definition at line 77 of file HHChannel.cpp.
                      {
    ;
    // if ( xGate_ && reinterpret_cast< char* >( this ) ==
    //  ObjId( xGate_->originalChannelId(), 0 ).data() )
    //  delete xGate_;
    // if ( yGate_ && reinterpret_cast< char* >( this ) ==
    //  ObjId( yGate_->originalChannelId(), 0 ).data() )
    //  delete yGate_;
    // if ( zGate_ && reinterpret_cast< char* >( this ) ==
    //  ObjId( zGate_->originalChannelId(), 0 ).data() )
    //  delete zGate_;
}
Member Function Documentation
checkOriginal()
bool HHChannel::checkOriginal (Id chanId) const override virtual
Returns true if channel is original, false if copy.
If the gate exists and has only this element for input, then change the gate power. If the gate exists and has multiple parents, then make a new gate, set its power. If the gate does not exist, make a new gate, set its power.
The function is designed with the idea that if copies of this channel are made, then they all point back to the original HHGate. (Unless they are cross-node copies). It is only if we subsequently alter the HHGate of this channel that we need to make our own variant of the HHGate, or disconnect from an existing one.
Reimplemented from HHChannelBase.
Definition at line 108 of file HHChannel.cpp.
{
    bool isOriginal = true;
    // cerr << "# HHChannel::checkOriginal(Id chanId) chanId: " << chanId << ", xGate: " << xGate_ << endl;
    if (xGate_ != nullptr) {
        isOriginal = xGate_->isOriginalChannel(chanId);
    } else if (yGate_ != nullptr) {
        isOriginal = yGate_->isOriginalChannel(chanId);
    } else if (zGate_ != nullptr) {
        isOriginal = zGate_->isOriginalChannel(chanId);
    }
    return isOriginal;
}
References HHGateBase::isOriginalChannel(), xGate_, yGate_, and zGate_.
Referenced by destroyGate(), and vCreateGate().
destroyGate()
void HHChannel::destroyGate (const Eref & e, string gateType) override virtual
Utility function for destroying gate. Works only on original HHChannel. Somewhat dangerous, should never be used after a copy has been made as the pointer of the gate will be in use elsewhere. This needs to be virtual as it needs to call subclass specific delete methods for the gate pointer.
Reimplemented from HHChannelBase.
Definition at line 162 of file HHChannel.cpp.
{
    if (!checkOriginal(e.id())) {
        cout << "Warning: HHChannel::destroyGate: Not allowed from copied "
                "channel:\n"
             << e.id().path() << "\n";
        return;
    }
    if (gateType == "X")
        innerDestroyGate("xGate", &xGate_, e.id());
    else if (gateType == "Y")
        innerDestroyGate("yGate", &yGate_, e.id());
    else if (gateType == "Z")
        innerDestroyGate("zGate", &zGate_, e.id());
    else
        cout << "Warning: HHChannel::destroyGate: Unknown gate type '"
             << gateType << "'. Ignored\n";
}
References checkOriginal(), Eref::id(), innerDestroyGate(), Id::path(), xGate_, yGate_, and zGate_.
getNumXgates()
unsigned int HHChannel::getNumXgates () const
Definition at line 197 of file HHChannel.cpp.
{ return xGate_ != nullptr; }
References xGate_.
Referenced by initCinfo().
getNumYgates()
unsigned int HHChannel::getNumYgates () const
Definition at line 199 of file HHChannel.cpp.
{ return yGate_ != nullptr; }
References yGate_.
Referenced by initCinfo().
getNumZgates()
unsigned int HHChannel::getNumZgates () const
Definition at line 201 of file HHChannel.cpp.
{ return zGate_ != nullptr; }
References zGate_.
Referenced by initCinfo().
getXgate()
HHGate * HHChannel::getXgate (unsigned int i)
Definition at line 189 of file HHChannel.cpp.
{ return xGate_; }
References xGate_.
Referenced by initCinfo().
getYgate()
HHGate * HHChannel::getYgate (unsigned int i)
Definition at line 191 of file HHChannel.cpp.
{ return yGate_; }
References yGate_.
Referenced by initCinfo().
getZgate()
HHGate * HHChannel::getZgate (unsigned int i)
Definition at line 193 of file HHChannel.cpp.
{ return zGate_; }
References zGate_.
Referenced by initCinfo().
initCinfo()
const Cinfo * HHChannel::initCinfo () static
Definition at line 23 of file HHChannel.cpp.
{
    static FieldElementFinfo<HHChannel, HHGate> gateX(
        "gateX", "Sets up HHGate X for channel", HHGate::initCinfo(),
        &HHChannel::getXgate, &HHChannel::setNumGates, &HHChannel::getNumXgates
        // 1
    );
    static FieldElementFinfo<HHChannel, HHGate> gateY(
        "gateY", "Sets up HHGate Y for channel", HHGate::initCinfo(),
        &HHChannel::getYgate, &HHChannel::setNumGates, &HHChannel::getNumYgates
        // 1
    );
    static FieldElementFinfo<HHChannel, HHGate> gateZ(
        "gateZ", "Sets up HHGate Z for channel", HHGate::initCinfo(),
        &HHChannel::getZgate, &HHChannel::setNumGates, &HHChannel::getNumZgates
        // 1
    );
    static Finfo* HHChannelFinfos[] = {
        &gateX,  // FieldElement
        &gateY,  // FieldElement
        &gateZ   // FieldElement
    };
    static string doc[] = {
        "Name",
        "HHChannel",
        "Author",
        "Upinder S. Bhalla, 2007, NCBS",
        "Description",
        "HHChannel: Hodgkin-Huxley type voltage-gated Ion channel. Something "
        "like the old tabchannel from GENESIS, but also presents "
        "a similar interface as hhchan from GENESIS. ",
    };
    static Dinfo<HHChannel> dinfo;
    static Cinfo HHChannelCinfo("HHChannel", HHChannelBase::initCinfo(),
                                HHChannelFinfos,
                                sizeof(HHChannelFinfos) / sizeof(Finfo*),
                                &dinfo, doc, sizeof(doc) / sizeof(string));
    return &HHChannelCinfo;
}
References Cinfo::Cinfo(), FieldElementFinfo< T, F >::FieldElementFinfo(), getNumXgates(), getNumYgates(), getNumZgates(), getXgate(), getYgate(), getZgate(), HHChannelBase::initCinfo(), HHGate::initCinfo(), and setNumGates().
Referenced by HSolve::unzombify().
innerCreateGate()
void HHChannel::innerCreateGate (const string & gateName, HHGate ** gatePtr, Id chanId, Id gateId)
Inner utility function for creating the gate.
Definition at line 121 of file HHChannel.cpp.
{
    // Shell* shell = reinterpret_cast< Shell* >( ObjId( Id(), 0 ).data() );
    if (*gatePtr) {
        cout << "Warning: HHChannel::createGate: '" << gateName
             << "' on Element '" << chanId.path() << "' already present\n";
        return;
    }
    *gatePtr = new HHGate(chanId, gateId);
}
References HHGate::HHGate(), and Id::path().
Referenced by vCreateGate().
innerDestroyGate()
void HHChannel::innerDestroyGate (const string & gateName, HHGate ** gatePtr, Id chanId)
Inner utility for destroying the gate
Definition at line 151 of file HHChannel.cpp.
{
    if (*gatePtr == nullptr) {
        cout << "Warning: HHChannel::destroyGate: '" << gateName
             << "' on Element '" << chanId.path() << "' not present\n";
        return;
    }
    delete (*gatePtr);
    *gatePtr = nullptr;
}
References Id::path().
Referenced by destroyGate().
innerSetXpower()
void HHChannel::innerSetXpower (double Xpower)
innerSetYpower()
void HHChannel::innerSetYpower (double Ypower)
innerSetZpower()
void HHChannel::innerSetZpower (double Zpower)
setNumGates()
void HHChannel::setNumGates (unsigned int num)
Definition at line 195 of file HHChannel.cpp.
{ ; }
Referenced by initCinfo().
vCreateGate()
void HHChannel::vCreateGate (const Eref & e, string gateType) override virtual
Implements HHChannelBase.
Definition at line 132 of file HHChannel.cpp.
{
    if (!checkOriginal(e.id())) {
        cout << "Warning: HHChannel::createGate: Not allowed from copied "
                "channel:\n"
             << e.id().path() << "\n";
        return;
    }
    if (gateType == "X")
        innerCreateGate("xGate", &xGate_, e.id(), Id(e.id().value() + 1));
    else if (gateType == "Y")
        innerCreateGate("yGate", &yGate_, e.id(), Id(e.id().value() + 2));
    else if (gateType == "Z")
        innerCreateGate("zGate", &zGate_, e.id(), Id(e.id().value() + 3));
    else
        cout << "Warning: HHChannel::createGate: Unknown gate type '"
             << gateType << "'. Ignored\n";
}
References checkOriginal(), Eref::id(), Id::Id(), innerCreateGate(), Id::path(), Id::value(), xGate_, yGate_, and zGate_.
vHandleConc()
void HHChannel::vHandleConc (const Eref & e, double conc) override virtual
Assign the local Vm_ to the incoming Vm from the compartment void handleVm(double Vm); Assign the local conc_ to the incoming conc from the concentration calculations for the compartment. Typically the message source will be a CaConc object, but there are other options for computing the conc.
Reimplemented from HHChannelBase.
Definition at line 353 of file HHChannel.cpp.
{ conc_ = conc; }
References conc_.
vProcess()
void HHChannel::vProcess (const Eref & e, ProcPtr p) override virtual
processFunc handles the update and calculations every clock tick. It first sends the request for evaluation of the gate variables to the respective gate objects and recieves their response immediately through a return message. This is done so that many channel instances can share the same gate lookup tables, but do so cleanly. Such messages should never go to a remote node. Then the function does its own little calculations to send back to the parent compartment through regular messages.
Implements ChanBase.
Definition at line 208 of file HHChannel.cpp.
{
    g_ += ChanCommon::vGetGbar(e);
    double A = 0;
    double B = 0;
    if (Xpower_ > 0) {
        xGate_->lookupBoth(Vm_, &A, &B);
        if (instant_ & INSTANT_X)
            X_ = A / B;
        else
            X_ = integrate(X_, info->dt, A, B);
        g_ *= takeXpower_(X_, Xpower_);
    }
    if (Ypower_ > 0) {
        yGate_->lookupBoth(Vm_, &A, &B);
        if (instant_ & INSTANT_Y)
            Y_ = A / B;
        else
            Y_ = integrate(Y_, info->dt, A, B);
        g_ *= takeYpower_(Y_, Ypower_);
    }
    if (Zpower_ > 0) {
        if (useConcentration_)
            zGate_->lookupBoth(conc_, &A, &B);
        else
            zGate_->lookupBoth(Vm_, &A, &B);
        if (instant_ & INSTANT_Z)
            Z_ = A / B;
        else
            Z_ = integrate(Z_, info->dt, A, B);
        g_ *= takeZpower_(Z_, Zpower_);
    }
    ChanCommon::vSetGk(e, g_ * ChanCommon::vGetModulation(e));
    ChanCommon::updateIk();
    // Gk_ = g_;
    // Ik_ = ( Ek_ - Vm_ ) * g_;
    // Send out the relevant channel messages.
    ChanCommon::sendProcessMsgs(e, info);
    g_ = 0.0;
}
References conc_, ProcInfo::dt, HHChannelBase::g_, HHChannelBase::instant_, HHChannelBase::INSTANT_X, HHChannelBase::INSTANT_Y, HHChannelBase::INSTANT_Z, HHChannelBase::integrate(), HHGate::lookupBoth(), ChanCommon::sendProcessMsgs(), HHChannelBase::takeXpower_, HHChannelBase::takeYpower_, HHChannelBase::takeZpower_, ChanCommon::updateIk(), HHChannelBase::useConcentration_, ChanCommon::vGetGbar(), ChanCommon::vGetModulation(), ChanCommon::Vm_, ChanCommon::vSetGk(), HHChannelBase::X_, xGate_, HHChannelBase::Xpower_, HHChannelBase::Y_, yGate_, HHChannelBase::Ypower_, HHChannelBase::Z_, zGate_, and HHChannelBase::Zpower_.
vReinit()
void HHChannel::vReinit (const Eref & er, ProcPtr info) override virtual
Reinitializes the values for the channel. This involves computing the steady-state value for the channel gates using the provided Vm from the parent compartment. It involves a similar cycle through the gates and then updates to the parent compartment as for the processFunc.
Here we get the steady-state values for the gate (the 'instant' calculation) as A_/B_.
Implements ChanBase.
Definition at line 259 of file HHChannel.cpp.
{
    g_ = ChanCommon::vGetGbar(er);
    Element* e = er.element();
    double A = 0.0;
    double B = 0.0;
    if (Xpower_ > 0) {
        assert(xGate_);
        if((xGate_->getMax(er) == 1) && (xGate_->getMin(er) == 0)) {
            cout << "Warning: " << er.objId().path()
                 << ".gateX: `min` and `max` have default values. Did you forget to "
         << "set them?"
                 << endl;
    }
    if(xGate_->getForm() > 0) // explicit string expression set, fill the tables by evaluating it
    {
        xGate_->fillFromExpr(er);
    }
        xGate_->lookupBoth(Vm_, &A, &B);
        if (B < EPSILON) {
            cout << "Warning: B_ value for " << e->getName()
                 << " is ~0. Check X table\n";
            return;
        }
        if (!xInited_) X_ = A / B;
        g_ *= takeXpower_(X_, Xpower_);
    }
    if (Ypower_ > 0) {
        assert(yGate_);
        if((yGate_->getMax(er) == 1) && (yGate_->getMin(er) == 0)) {
            cout << "Warning: " << er.objId().path()
                 << ".gateY: `min` and `max` have default values. Did you forget to "
         << "set them?"
                 << endl;
    }
    if(yGate_->getForm() > 0) // explicit string expression set, fill the tables by evaluating it
    {
        yGate_->fillFromExpr(er);
    }
        yGate_->lookupBoth(Vm_, &A, &B);
        if (B < EPSILON) {
            cout << "Warning: B value for " << e->getName()
                 << " is ~0. Check Y table\n";
            return;
        }
        if (!yInited_) Y_ = A / B;
        g_ *= takeYpower_(Y_, Ypower_);
    }
    if (Zpower_ > 0) {
        assert(zGate_);
        if((zGate_->getMax(er) == 1) && (zGate_->getMin(er) == 0)) {
            cout << "Warning: " << er.objId().path()
                 << ".gateZ: `min` and `max` have default values. Did you forget to "
         << "set them?"
                 << endl;
    }
    if(zGate_->getForm() > 0) // explicit string expression set, fill the tables by evaluating it
    {
        zGate_->fillFromExpr(er);
    }
        if (useConcentration_){
            zGate_->lookupBoth(conc_, &A, &B);
    }
        else {
        cout << "Warning: " << er.objId().path()
                 << ".gateZ: `useConcentration=False`, though this gate is"
         << " commonly used for concentration-dependency."
         << " Did you forget to set it?"
                 << endl;
            zGate_->lookupBoth(Vm_, &A, &B);
    }
        if (B < EPSILON) {
            cout << "Warning: B value for " << e->getName()
                 << " is ~0. Check Z table\n";
            return;
        }
        if (!zInited_) Z_ = A / B;
        g_ *= takeZpower_(Z_, Zpower_);
    }
    ChanCommon::vSetGk(er, g_ * ChanCommon::vGetModulation(er));
    ChanCommon::updateIk();
    // Gk_ = g_;
    // Ik_ = ( Ek_ - Vm_ ) * g_;
    // Send out the relevant channel messages.
    // Same for reinit as for process.
    ChanCommon::sendReinitMsgs(er, info);
    g_ = 0.0;
}
References conc_, Eref::element(), HHChannelBase::EPSILON, HHGate::fillFromExpr(), HHChannelBase::g_, HHGate::getForm(), HHGate::getMax(), HHGate::getMin(), Element::getName(), HHGate::lookupBoth(), Eref::objId(), ObjId::path(), ChanCommon::sendReinitMsgs(), HHChannelBase::takeXpower_, HHChannelBase::takeYpower_, HHChannelBase::takeZpower_, ChanCommon::updateIk(), HHChannelBase::useConcentration_, ChanCommon::vGetGbar(), ChanCommon::vGetModulation(), ChanCommon::Vm_, ChanCommon::vSetGk(), HHChannelBase::X_, xGate_, HHChannelBase::xInited_, HHChannelBase::Xpower_, HHChannelBase::Y_, yGate_, HHChannelBase::yInited_, HHChannelBase::Ypower_, HHChannelBase::Z_, zGate_, HHChannelBase::zInited_, and HHChannelBase::Zpower_.
Member Data Documentation
conc_
double HHChannel::conc_ private
Conc_ is input variable for Ca-dependent channels.
Definition at line 185 of file HHChannel.h.
Referenced by HHChannel(), vHandleConc(), vProcess(), and vReinit().
xGate_
HHGate* HHChannel::xGate_ private
HHGate data structure for the xGate. This is writable only on the HHChannel that originally created the HHGate, for others it must be treated as readonly.
Definition at line 192 of file HHChannel.h.
Referenced by checkOriginal(), destroyGate(), getNumXgates(), getXgate(), HHChannel(), vCreateGate(), vProcess(), and vReinit().
yGate_
HHGate* HHChannel::yGate_ private
HHGate data structure for the yGate.
Definition at line 195 of file HHChannel.h.
Referenced by checkOriginal(), destroyGate(), getNumYgates(), getYgate(), HHChannel(), vCreateGate(), vProcess(), and vReinit().
zGate_
HHGate* HHChannel::zGate_ private
HHGate data structure for the yGate.
Definition at line 198 of file HHChannel.h.
Referenced by checkOriginal(), destroyGate(), getNumZgates(), getZgate(), HHChannel(), vCreateGate(), vProcess(), and vReinit().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/biophysics/HHChannel.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/biophysics/HHChannel.cpp