MOOSE - Multiscale Object Oriented Simulation Environment: Ksolve Class Reference
Ksolve Class Reference
#include <Ksolve.h>
Public Member Functions
size_t advance_chunk (const size_t begin, const size_t end, ProcPtr p)
void advance_pool (const size_t i, ProcPtr p)
double getAbsoluteAccuracy () const
void getBlock (vector< double > &values) const
double getConcInit (const Eref &e) const
get initial conc of molecules in given pool and voxel. Bdry cond.
double getDiffConst (const Eref &e) const
Diffusion constant: Only one per pool, voxel number is ignored.
Id getDsolve () const
Inherited from KsolveBase.
double getEpsAbs () const
Assigns Absolute tolerance for integration.
double getEpsRel () const
Assigns Relative tolerance for integration.
double getEstimatedDt () const
string getMethod () const
Assigns integration method.
double getN (const Eref &e) const
Get # of molecules in given pool and voxel. Varies with time.
unsigned int getNumAllVoxels () const
unsigned int getNumLocalVoxels () const
Inherited from KsolveBase.
unsigned int getNumPools () const
gets number of pools (species) handled by system.
unsigned int getNumThreads () const
vector< double > getNvec (unsigned int voxel) const
Returns the vector of pool Num at the specified voxel.
unsigned int getPoolIndex (const Eref &e) const
Return pool index, using Stoich ptr to do lookup.
double getR1 (unsigned int reacIdx, const Eref &e) const
vector< double > getR1vec (unsigned int reacIdx) const
Unlike getNvec, this returns vector of R1 for this reac across voxels.
vector< double > getRateVecFromId (Id reacId) const
Unlike getNvec, this returns vector of R1 for this reac across voxels.
vector< double > getRateVecFromPath (string reacPath) const
Unlike getNvec, this returns vector of R1 for this reac across voxels.
double getRelativeAccuracy () const
Id getStoich () const
Assigns Stoich object to Ksolve.
double getVolumeOfPool (const Eref &e) const
Return volume of pool e.
unsigned int getVoxelIndex (const Eref &e) const
void initProc (const Eref &e, ProcPtr p)
void initReinit (const Eref &e, ProcPtr p)
Ksolve ()
void matchJunctionVols (vector< double > &vols, Id otherCompt) const
void notifyAddMsgDestPool (const Eref &e, ObjId msgId)
void notifyAddMsgSrcPool (const Eref &e, ObjId msgId)
void notifyAddPool (const Eref &e)
void notifyDestroyPool (const Eref &e)
void notifyRemovePool (const Eref &e)
VoxelPoolsBase * pools (unsigned int i)
Return a pointer to the specified VoxelPool.
void print () const
void process (const Eref &e, ProcPtr p)
void reinit (const Eref &e, ProcPtr p)
void setBlock (const vector< double > &values)
void setConcInit (const Eref &e, double v)
Set initial conc of molecules in given pool and voxel. Bdry cond.
void setDiffConst (const Eref &e, double v)
Diffusion constant: Only one per pool, voxel number is ignored.
void setDsolve (Id dsolve)
Assigns the diffusion solver. Used by the reac solvers.
void setEpsAbs (double val)
void setEpsRel (double val)
void setMethod (string method)
void setN (const Eref &e, double v)
Set # of molecules in given pool and voxel. Varies with time.
void setNumAllVoxels (unsigned int num)
void setNumPools (unsigned int num)
void setNumThreads (unsigned int x)
void setNumVarTotPools (unsigned int var, unsigned int tot)
Specifies number of var pools and total pools including buffered .
void setNvec (unsigned int voxel, vector< double > vec)
void setStoich (Id stoich)
void updateRateTerms (unsigned int index)
void updateVoxelVol (vector< double > vols)
double volume (unsigned int i) const
Return volume of voxel i.
~Ksolve ()
Public Member Functions inherited from KsolveBase
Id getCompartment () const
virtual double getMotorConst (const Eref &e)
KsolveBase ()
virtual void setCompartment (Id compartment)
Assigns compartment.
virtual void setIsBuffered (const Eref &e, bool val)
Set buffer status of pool. Changes class between Pool and BufPool.
virtual void setMotorConst (const Eref &e, double val)
virtual void setPrev ()
Used to tell Dsolver to assign 'prev' values.
virtual void updateJunctions (double dt)
Used for telling Dsolver to handle all ops across Junctions.
Static Public Member Functions
static const Cinfo * initCinfo ()
Private Attributes
Id dsolve_
KsolveBase * dsolvePtr_
Pointer to diffusion solver.
double epsAbs_
double epsRel_
size_t grainSize_
vector< std::pair< size_t, size_t > > intervals_
string method_
size_t numSteps_ = 0
size_t numThreads_
Number of threads to use. Only applicable for deterministic case.
vector< VoxelPools > pools_
unsigned int startVoxel_
First voxel indexed on the current node.
Stoich * stoichPtr_
Utility ptr used to help Pool Id lookups by the Ksolve.
double totalTime_ = 0.0
Static Private Attributes
static map< Id, unsigned int > defaultPoolLookup_
Additional Inherited Members
Protected Attributes inherited from KsolveBase
Id compartment_
Id of Chem compartment used to figure out volumes of voxels.
bool isBuilt_
Flag: True when solver setup has been completed.
Id stoich_
Detailed Description
Definition at line 19 of file Ksolve.h.
Constructor & Destructor Documentation
Ksolve()
Ksolve::Ksolve ()
Definition at line 238 of file Ksolve.cpp.
    :
    method_( "rk5" ),
    epsAbs_( 1e-7 ),
    epsRel_( 1e-7 ),
    numThreads_( 1 ),
    pools_( 1 ),
    startVoxel_( 0 ),
    dsolve_(),
    dsolvePtr_( nullptr )
{
    numThreads_ = moose::getEnvInt("MOOSE_NUM_THREADS", 1);
}
References dsolve_, dsolvePtr_, epsAbs_, epsRel_, moose::getEnvInt(), Id::Id(), method_, numThreads_, pools_, and startVoxel_.
~Ksolve()
Ksolve::~Ksolve ()
Definition at line 253 of file Ksolve.cpp.
{
    ;
}
Member Function Documentation
advance_chunk()
size_t Ksolve::advance_chunk (const size_t begin, const size_t end, ProcPtr p)
Definition at line 643 of file Ksolve.cpp.
{
    size_t tot = 0;
    for (size_t i = begin; i < std::min(end, pools_.size()); i++)
    {
        pools_[i].advance( p );
        tot += 1;
    }
    return tot;
}
References VoxelPools::advance(), and pools_.
Referenced by process().
advance_pool()
void Ksolve::advance_pool (const size_t i, ProcPtr p)
Definition at line 638 of file Ksolve.cpp.
{
    pools_[i].advance(p);
}
References VoxelPools::advance(), and pools_.
getAbsoluteAccuracy()
double Ksolve::getAbsoluteAccuracy () const
getBlock()
void Ksolve::getBlock (vector< double > & values) const virtual
Gets block of data. The first 4 entries are passed in on the 'values' vector: the start voxel, numVoxels, start pool#, numPools. These are followed by numVoxels * numPools of data values which are filled in by the function. We assert that the entire requested block is present in this KsolveBase. The block is organized as an array of arrays of voxels; values[pool#][voxel#]
Note that numVoxels and numPools are the number in the current block, not the upper limit of the block. So values.size() == 4 + numPools * numVoxels.
Implements KsolveBase.
Definition at line 878 of file Ksolve.cpp.
{
    unsigned int startVoxel = static_cast<unsigned int>(values[0]);
    unsigned int numVoxels = static_cast<unsigned int>(values[1]);
    unsigned int startPool = static_cast<unsigned int>(values[2]);
    unsigned int numPools = static_cast<unsigned int>(values[3]);
    assert( startVoxel >= startVoxel_ );
    assert( numVoxels <= pools_.size() );
    assert( pools_.size() > 0 );
    assert( numPools + startPool <= pools_[0].size() );
    values.resize( 4 + numVoxels * numPools );
    for ( unsigned int i = 0; i < numVoxels; ++i )
    {
        const double* v = pools_[ startVoxel + i ].S();
        for ( unsigned int j = 0; j < numPools; ++j )
        {
            values[ 4 + j * numVoxels + i]  = v[ j + startPool ];
        }
    }
}
References pools_, VoxelPoolsBase::S(), VoxelPoolsBase::size(), and startVoxel_.
Referenced by process().
getConcInit()
double Ksolve::getConcInit (const Eref & e) const virtual
get initial conc of molecules in given pool and voxel. Bdry cond.
Implements KsolveBase.
Definition at line 779 of file Ksolve.cpp.
{
    unsigned int vox = getVoxelIndex( e );
    if ( vox != OFFNODE )
        return pools_[vox].getConcInit( getPoolIndex( e ) );
    return 0.0;
}
References VoxelPoolsBase::getConcInit(), getPoolIndex(), getVoxelIndex(), OFFNODE, and pools_.
getDiffConst()
double Ksolve::getDiffConst (const Eref & e) const virtual
Diffusion constant: Only one per pool, voxel number is ignored.
Implements KsolveBase.
Definition at line 798 of file Ksolve.cpp.
{
    return 0;
}
getDsolve()
Id Ksolve::getDsolve () const
Inherited from KsolveBase.
Assigns Dsolve object to Ksolve.
Definition at line 429 of file Ksolve.cpp.
{
    return dsolve_;
}
References dsolve_.
getEpsAbs()
double Ksolve::getEpsAbs () const
Assigns Absolute tolerance for integration.
Definition at line 304 of file Ksolve.cpp.
{
    return epsAbs_;
}
References epsAbs_.
Referenced by initCinfo().
getEpsRel()
double Ksolve::getEpsRel () const
Assigns Relative tolerance for integration.
Definition at line 318 of file Ksolve.cpp.
{
    return epsRel_;
}
References epsRel_.
Referenced by initCinfo().
getEstimatedDt()
double Ksolve::getEstimatedDt () const
This does a quick and dirty estimate of the timestep suitable for this sytem
Definition at line 539 of file Ksolve.cpp.
{
    static const double EPSILON = 1e-15;
    vector< double > s( stoichPtr_->getNumAllPools(), 1.0 );
    vector< double > v( stoichPtr_->getNumRates(), 0.0 );
    double maxVel = 0.0;
    if ( pools_.size() > 0.0 )
    {
        pools_[0].updateReacVelocities( &s[0], v );
        for ( vector< double >::iterator
                i = v.begin(); i != v.end(); ++i )
            if ( maxVel < *i )
                maxVel = *i;
    }
    if ( maxVel < EPSILON )
        return 0.1; // Based on typical sig pathway reac rates.
    // Heuristic: the largest velocity times dt should be 10% of mol conc.
    return 0.1 / maxVel;
}
References Stoich::getNumAllPools(), Stoich::getNumRates(), pools_, stoichPtr_, and VoxelPools::updateReacVelocities().
Referenced by initCinfo().
getMethod()
string Ksolve::getMethod () const
Assigns integration method.
Definition at line 262 of file Ksolve.cpp.
{
    return method_;
}
References method_.
Referenced by VoxelPools::getMethod(), and initCinfo().
getN()
double Ksolve::getN (const Eref & e) const virtual
Get # of molecules in given pool and voxel. Varies with time.
Implements KsolveBase.
Definition at line 756 of file Ksolve.cpp.
{
    unsigned int vox = getVoxelIndex( e );
    if ( vox != OFFNODE )
        return pools_[vox].getN( getPoolIndex( e ) );
    return 0.0;
}
References VoxelPoolsBase::getN(), getPoolIndex(), getVoxelIndex(), OFFNODE, and pools_.
getNumAllVoxels()
unsigned int Ksolve::getNumAllVoxels () const
Definition at line 459 of file Ksolve.cpp.
{
    return pools_.size(); // Need to redo.
}
References pools_.
Referenced by initCinfo().
getNumLocalVoxels()
unsigned int Ksolve::getNumLocalVoxels () const virtual
Inherited from KsolveBase.
Implements KsolveBase.
Definition at line 454 of file Ksolve.cpp.
{
    return pools_.size();
}
References pools_.
Referenced by initCinfo(), and process().
getNumPools()
unsigned int Ksolve::getNumPools () const virtual
gets number of pools (species) handled by system.
Implements KsolveBase.
Definition at line 821 of file Ksolve.cpp.
{
    if ( pools_.size() > 0 )
        return pools_[0].size();
    return 0;
}
References pools_, and VoxelPoolsBase::size().
Referenced by initCinfo().
getNumThreads()
unsigned int Ksolve::getNumThreads () const
Definition at line 340 of file Ksolve.cpp.
{
    return numThreads_;
}
References numThreads_.
Referenced by initCinfo().
getNvec()
vector< double > Ksolve::getNvec (unsigned int voxel) const
Returns the vector of pool Num at the specified voxel.
Definition at line 474 of file Ksolve.cpp.
{
    static vector< double > dummy;
    if ( voxel < pools_.size() )
    {
        return const_cast< VoxelPools* >( &( pools_[ voxel ] ) )->Svec();
    }
    return dummy;
}
References pools_, and VoxelPoolsBase::Svec().
Referenced by initCinfo().
getPoolIndex()
unsigned int Ksolve::getPoolIndex (const Eref & er) const virtual
Return pool index, using Stoich ptr to do lookup.
Implements KsolveBase.
Definition at line 726 of file Ksolve.cpp.
{
    if (!stoichPtr_) {
        auto ret = defaultPoolLookup_.find( e.id() );
        if ( ret != defaultPoolLookup_.end() )
            return ret->second;
        return ~0U;
    }
    return stoichPtr_->convertIdToPoolIndex( e.id() );
}
References Stoich::convertIdToPoolIndex(), defaultPoolLookup_, Eref::id(), and stoichPtr_.
Referenced by getConcInit(), getN(), setConcInit(), and setN().
getR1()
double Ksolve::getR1 (unsigned int reacIdx, const Eref & e) const virtual
Get rate const in a given reac and voxel. Usually fixed but may vary if the reac is controlled by a function.
Implements KsolveBase.
Definition at line 764 of file Ksolve.cpp.
{
    unsigned int vox = getVoxelIndex( e );
    if ( vox != OFFNODE )
        return pools_[vox].getR1( reacIdx );
    return 0.0;
}
References VoxelPoolsBase::getR1(), getVoxelIndex(), OFFNODE, and pools_.
getR1vec()
vector< double > Ksolve::getR1vec (unsigned int reacIdx) const
Unlike getNvec, this returns vector of R1 for this reac across voxels.
Definition at line 501 of file Ksolve.cpp.
{
    vector< double > ret( pools_.size(), 0.0 );
    for ( unsigned int ii = 0; ii < pools_.size(); ++ii ) {
        ret[ii] = pools_[ii].getR1( reacIdx );
    }
    return ret;
}
References VoxelPoolsBase::getR1(), and pools_.
Referenced by getRateVecFromId(), and getRateVecFromPath().
getRateVecFromId()
vector< double > Ksolve::getRateVecFromId (Id reacId) const
Unlike getNvec, this returns vector of R1 for this reac across voxels.
Definition at line 511 of file Ksolve.cpp.
{
    if ( reacId != Id() ) {
        unsigned int idx = stoichPtr_->convertIdToReacIndex( reacId );
        if ( idx != ~0U )
            return getR1vec( idx );
    }
    return vector< double >( pools_.size(), 0.0 );
}
References Stoich::convertIdToReacIndex(), getR1vec(), Id::Id(), Id::operator!=(), pools_, and stoichPtr_.
getRateVecFromPath()
vector< double > Ksolve::getRateVecFromPath (string reacPath) const
Unlike getNvec, this returns vector of R1 for this reac across voxels.
Definition at line 522 of file Ksolve.cpp.
{
    Id reacId( reacPath );
    if ( reacId == Id() ) {
        cout << "Error: object not found on " << reacPath << endl;
        return vector< double >( pools_.size(), 0.0 );
    }
    if ( reacId != Id() ) {
        unsigned int idx = stoichPtr_->convertIdToReacIndex( reacId );
        if ( idx != ~0U )
            return getR1vec( idx );
    }
    return vector< double >( pools_.size(), 0.0 );
}
References Stoich::convertIdToReacIndex(), getR1vec(), Id::Id(), Id::Id(), Id::operator!=(), Id::operator==(), pools_, and stoichPtr_.
Referenced by initCinfo().
getRelativeAccuracy()
double Ksolve::getRelativeAccuracy () const
getStoich()
Id Ksolve::getStoich () const
Assigns Stoich object to Ksolve.
Definition at line 345 of file Ksolve.cpp.
{
    return stoich_;
}
References KsolveBase::stoich_.
Referenced by initCinfo().
getVolumeOfPool()
double Ksolve::getVolumeOfPool (const Eref & e) const virtual
Return volume of pool e.
Implements KsolveBase.
Definition at line 787 of file Ksolve.cpp.
{
    unsigned int vox = getVoxelIndex( e );
    return pools_[vox].getVolume();
}
References VoxelPoolsBase::getVolume(), getVoxelIndex(), and pools_.
getVoxelIndex()
unsigned int Ksolve::getVoxelIndex (const Eref & e) const
Definition at line 737 of file Ksolve.cpp.
{
    unsigned int ret = e.dataIndex();
    if ( ret < startVoxel_  || ret >= startVoxel_ + pools_.size() )
        return OFFNODE;
    return ret - startVoxel_;
}
References Eref::dataIndex(), OFFNODE, pools_, and startVoxel_.
Referenced by getConcInit(), getN(), getR1(), getVolumeOfPool(), setConcInit(), and setN().
initCinfo()
const Cinfo * Ksolve::initCinfo () static
Definition at line 50 of file Ksolve.cpp.
{
    // Field definitions
    static ValueFinfo< Ksolve, string > method (
        "method",
        "Integration method, using GSL. So far only explict. Options are:"
        "rk5: The default Runge-Kutta-Fehlberg 5th order adaptive dt method"
        "gsl: alias for the above"
        "rk4: The Runge-Kutta 4th order fixed dt method"
        "rk2: The Runge-Kutta 2,3 embedded fixed dt method"
        "rkck: The Runge-Kutta Cash-Karp (4,5) method"
        "rk8: The Runge-Kutta Prince-Dormand (8,9) method"
        "lsoda: LSODA method",
        &Ksolve::setMethod,
        &Ksolve::getMethod
    );
    static ValueFinfo< Ksolve, double > epsAbs (
        "epsAbs",
        "Absolute permissible integration error range.",
        &Ksolve::setEpsAbs,
        &Ksolve::getEpsAbs
    );
    static ValueFinfo< Ksolve, double > epsRel (
        "epsRel",
        "Relative permissible integration error range.",
        &Ksolve::setEpsRel,
        &Ksolve::getEpsRel
    );
    static ValueFinfo< Ksolve, Id > compartment(
        "compartment",
        "Compartment in which the Ksolve reaction system lives.",
        &Ksolve::setCompartment,
        &Ksolve::getCompartment
    );
    static ReadOnlyValueFinfo< Ksolve, unsigned int > numLocalVoxels(
        "numLocalVoxels",
        "Number of voxels in the core reac-diff system, on the "
        "current solver. ",
        &Ksolve::getNumLocalVoxels
    );
    static LookupValueFinfo< Ksolve, unsigned int, vector< double > > nVec(
        "nVec",
        "vector of pool counts. Index specifies which voxel.",
        &Ksolve::setNvec,
        &Ksolve::getNvec
    );
    static ReadOnlyLookupValueFinfo< Ksolve, string, vector< double > > rateVec(
        "rateVec",
        "vector of forward rate consts of specified reaction.",
        &Ksolve::getRateVecFromPath
    );
    static ValueFinfo< Ksolve, unsigned int > numAllVoxels(
        "numAllVoxels",
        "Number of voxels in the entire reac-diff system, "
        "including proxy voxels to represent abutting compartments.",
        &Ksolve::setNumAllVoxels,
        &Ksolve::getNumAllVoxels
    );
    static ValueFinfo< Ksolve, unsigned int > numThreads (
        "numThreads",
        "Number of threads to use",
        &Ksolve::setNumThreads,
        &Ksolve::getNumThreads
    );
    static ValueFinfo< Ksolve, unsigned int > numPools(
        "numPools",
        "Number of molecular pools in the entire reac-diff system, "
        "including variable, function and buffered.",
        &Ksolve::setNumPools,
        &Ksolve::getNumPools
    );
    static ReadOnlyValueFinfo< Ksolve, double > estimatedDt(
        "estimatedDt",
        "Estimated timestep for reac system based on Euler error",
        &Ksolve::getEstimatedDt
    );
    static ReadOnlyValueFinfo< Ksolve, Id > stoich(
        "stoich",
        "Id for stoichiometry object tied to this Ksolve",
        &Ksolve::getStoich
    );
    // DestFinfo definitions
    static DestFinfo process( "process",
            "Handles process call from Clock",
            new ProcOpFunc< Ksolve >( &Ksolve::process )
            );
    static DestFinfo reinit( "reinit",
            "Handles reinit call from Clock",
            new ProcOpFunc< Ksolve >( &Ksolve::reinit )
            );
    static DestFinfo initProc( "initProc",
            "Handles initProc call from Clock",
            new ProcOpFunc< Ksolve >( &Ksolve::initProc )
            );
    static DestFinfo initReinit( "initReinit",
            "Handles initReinit call from Clock",
            new ProcOpFunc< Ksolve >( &Ksolve::initReinit )
            );
    static DestFinfo voxelVol( "voxelVol",
            "Handles updates to all voxels. Comes from parent "
            "ChemCompt object.",
            new OpFunc1< Ksolve, vector< double > >(
                &Ksolve::updateVoxelVol )
            );
    // Shared definitions
    static Finfo* procShared[] =
    {
        &process, &reinit
    };
    static SharedFinfo proc( "proc",
            "Shared message for process and reinit. These are used for "
            "all regular Ksolve calculations including interfacing with "
            "the diffusion calculations by a Dsolve.",
            procShared, sizeof( procShared ) / sizeof( const Finfo* )
            );
    static Finfo* initShared[] =
    {
        &initProc, &initReinit
    };
    static SharedFinfo init( "init",
            "Shared message for initProc and initReinit. This is used"
            " when the system has cross-compartment reactions. ",
            initShared, sizeof( initShared ) / sizeof( const Finfo* )
            );
    static Finfo* ksolveFinfos[] =
    {
        &method,                         // Value
        &epsAbs,                         // Value
        &epsRel ,                        // Value
        &numThreads,                     // Value
        &compartment,                    // Value
        &numLocalVoxels,                 // ReadOnlyValue
        &nVec,                           // LookupValue
        &rateVec,                        // ReadOnlyLookupValue
        &numAllVoxels,                   // ReadOnlyValue
        &numPools,                       // Value
        &estimatedDt,                    // ReadOnlyValue
        &stoich,                         // ReadOnlyValue
        &voxelVol,                       // DestFinfo
        &proc,                           // SharedFinfo
        &init,                           // SharedFinfo
    };
    static Dinfo< Ksolve > dinfo;
    static  Cinfo ksolveCinfo(
        "Ksolve",
        Neutral::initCinfo(),
        ksolveFinfos,
        sizeof(ksolveFinfos)/sizeof(Finfo *),
        &dinfo
    );
    return &ksolveCinfo;
}
References Cinfo::Cinfo(), DestFinfo::DestFinfo(), KsolveBase::getCompartment(), getEpsAbs(), getEpsRel(), getEstimatedDt(), getMethod(), getNumAllVoxels(), getNumLocalVoxels(), getNumPools(), getNumThreads(), getNvec(), getRateVecFromPath(), getStoich(), Neutral::initCinfo(), initProc(), initReinit(), LookupValueFinfo< T, L, F >::LookupValueFinfo(), OpFunc1< T, A >::OpFunc1(), process(), ProcOpFunc< T >::ProcOpFunc(), ReadOnlyLookupValueFinfo< T, L, F >::ReadOnlyLookupValueFinfo(), ReadOnlyValueFinfo< T, F >::ReadOnlyValueFinfo(), reinit(), KsolveBase::setCompartment(), setEpsAbs(), setEpsRel(), setMethod(), setNumAllVoxels(), setNumPools(), setNumThreads(), setNvec(), SharedFinfo::SharedFinfo(), updateVoxelVol(), and ValueFinfo< T, F >::ValueFinfo().
initProc()
void Ksolve::initProc (const Eref & e, ProcPtr p)
Definition at line 688 of file Ksolve.cpp.
{
}
Referenced by initCinfo().
initReinit()
void Ksolve::initReinit (const Eref & e, ProcPtr p)
Definition at line 692 of file Ksolve.cpp.
{
    for ( unsigned int i = 0 ; i < pools_.size(); ++i )
        pools_[i].reinit( p->dt );
}
References ProcInfo::dt, pools_, and VoxelPools::reinit().
Referenced by initCinfo().
matchJunctionVols()
void Ksolve::matchJunctionVols (vector< double > & vols, Id otherCompt) const
notifyAddMsgDestPool()
void Ksolve::notifyAddMsgDestPool (const Eref & e, ObjId msgId) virtual
Reimplemented from KsolveBase.
Definition at line 873 of file Ksolve.cpp.
{
}
notifyAddMsgSrcPool()
void Ksolve::notifyAddMsgSrcPool (const Eref & e, ObjId msgId) virtual
Reimplemented from KsolveBase.
Definition at line 869 of file Ksolve.cpp.
{
}
notifyAddPool()
void Ksolve::notifyAddPool (const Eref & e) virtual
Reimplemented from KsolveBase.
Definition at line 849 of file Ksolve.cpp.
{
    if ( stoichPtr_ ) {
        // stoichPtr_->notifyAddPool( e );
    } else {
        size_t idx = pools_[0].size();
        pools_[0].resizeArrays( idx + 1 );
        defaultPoolLookup_[ e.id() ] = idx;
    }
}
References defaultPoolLookup_, Eref::id(), pools_, VoxelPoolsBase::resizeArrays(), VoxelPoolsBase::size(), and stoichPtr_.
notifyDestroyPool()
void Ksolve::notifyDestroyPool (const Eref & e) virtual
Reimplemented from KsolveBase.
Definition at line 844 of file Ksolve.cpp.
{
    notifyRemovePool( e );
}
References notifyRemovePool().
notifyRemovePool()
void Ksolve::notifyRemovePool (const Eref & e) virtual
Reimplemented from KsolveBase.
Definition at line 860 of file Ksolve.cpp.
{
    if ( stoichPtr_ ) {
        // stoichPtr_->notifyRemovePool( e );
    } else {
        defaultPoolLookup_[ e.id() ] = ~0U;
    }
}
References defaultPoolLookup_, Eref::id(), and stoichPtr_.
Referenced by notifyDestroyPool().
pools()
VoxelPoolsBase * Ksolve::pools (unsigned int i) virtual
Return a pointer to the specified VoxelPool.
Implements KsolveBase.
Definition at line 828 of file Ksolve.cpp.
{
    if ( pools_.size() > i )
        return &pools_[i];
    return 0;
}
References pools_.
print()
void Ksolve::print () const
Definition at line 941 of file Ksolve.cpp.
{
    cout << "path = " << stoichPtr_->getKsolve().path() <<
         ", numPools = " << pools_.size() << "\n";
    for ( unsigned int i = 0; i < pools_.size(); ++i )
    {
        cout << "pools[" << i << "] contents = ";
        pools_[i].print();
    }
    cout << "method = " << method_ << ", stoich=" << stoich_.path() <<endl;
    cout << "dsolve = " << dsolve_.path() << endl;
    cout << "compartment = " << compartment_.path() << endl;
}
References KsolveBase::compartment_, dsolve_, Stoich::getKsolve(), method_, Id::path(), pools_, VoxelPools::print(), KsolveBase::stoich_, and stoichPtr_.
process()
void Ksolve::process (const Eref & e, ProcPtr p)
Definition at line 562 of file Ksolve.cpp.
{
    if ( isBuilt_ == false )
        return;
    //t0_ = high_resolution_clock::now();
    // First, handle incoming diffusion values, update S with those.
    if ( dsolvePtr_ )
    {
        vector< double > dvalues( 4 );
        dvalues[0] = 0;
        dvalues[1] = getNumLocalVoxels();
        dvalues[2] = 0;
        dvalues[3] = stoichPtr_->getNumVarPools();
        dsolvePtr_->getBlock( dvalues );
        // Second, set the prev_ value in DiffPoolVec
        dsolvePtr_->setPrev();
        setBlock( dvalues );
    }
    if( 1 == numThreads_ || 1 == pools_.size() )
    {
        if( numThreads_ > 1 )
        {
            cerr << "Warn: Not enough voxels for multithreading. "
                << "Reverting to serial mode. " << endl;
            numThreads_ = 1;
        }
        for ( unsigned int i = 0; i < pools_.size(); i++ )
            pools_[i].advance( p );
    }
    else
    {
        std::vector<std::future<size_t>> vecFutures;
        // lambdas is faster than std::bind
        for (auto interval : intervals_)
        {
            vecFutures.push_back(
                    std::async( std::launch::async
                        , &Ksolve::advance_chunk
                        , this
                        , interval.first
                        , interval.second, p
                        )
                    );
        }
        size_t tot = 0;
        for (auto &v : vecFutures )
            tot += v.get();
        assert(tot == pools_.size());
    }
    // Assemble and send the integrated values off for the Dsolve.
    if ( dsolvePtr_ )
    {
        vector< double > kvalues( 4 );
        kvalues[0] = 0;
        kvalues[1] = getNumLocalVoxels();
        kvalues[2] = 0;
        kvalues[3] = stoichPtr_->getNumVarPools();
        getBlock( kvalues );
        dsolvePtr_->setBlock( kvalues );
        // Now use the values in the Dsolve to update junction fluxes
        // for diffusion, channels, and xreacs
        dsolvePtr_->updateJunctions( p->dt );
    }
    //t1_ = high_resolution_clock::now();
    //moose::addSolverProf( "Ksolve", duration_cast<duration<double>> (t1_ - t0_ ).count(), 1 );
}
References VoxelPools::advance(), advance_chunk(), dsolvePtr_, ProcInfo::dt, getBlock(), KsolveBase::getBlock(), getNumLocalVoxels(), Stoich::getNumVarPools(), intervals_, KsolveBase::isBuilt_, numThreads_, pools_, setBlock(), KsolveBase::setBlock(), KsolveBase::setPrev(), stoichPtr_, and KsolveBase::updateJunctions().
Referenced by initCinfo().
reinit()
void Ksolve::reinit (const Eref & e, ProcPtr p)
Definition at line 655 of file Ksolve.cpp.
{
    if ( !stoichPtr_ )
        return;
    if ( isBuilt_ )
    {
        for ( unsigned int i = 0 ; i < pools_.size(); ++i ) {
            pools_[i].setNumVoxels( pools_.size() );
            pools_[i].reinit( p->dt );
        }
    }
    else
    {
        cout << "Warning:Ksolve::reinit: Reaction system not initialized\n";
        return;
    }
    if(numThreads_ > pools_.size())
        numThreads_ = pools_.size();
    if(numThreads_ > 1)
        cout << "Info: Multi-threaded Ksolve (" << numThreads_ << " threads)."
            << endl;
    // Recompute the partition of interval.
    intervals_.clear();
    moose::splitIntervalInNParts(pools_.size(), numThreads_, intervals_);
}
References ProcInfo::dt, intervals_, KsolveBase::isBuilt_, numThreads_, pools_, VoxelPools::reinit(), VoxelPoolsBase::setNumVoxels(), moose::splitIntervalInNParts(), and stoichPtr_.
Referenced by initCinfo().
setBlock()
void Ksolve::setBlock (const vector< double > & values) virtual
Sets block of data. The first 4 entries on the 'values' vector are the start voxel, numVoxels, start pool#, numPools. These are followed by numVoxels * numPools of data values.
Implements KsolveBase.
Definition at line 901 of file Ksolve.cpp.
{
    unsigned int startVoxel = static_cast<unsigned int>(values[0]);
    unsigned int numVoxels = static_cast<unsigned int>(values[1]);
    unsigned int startPool = static_cast<unsigned int>(values[2]);
    unsigned int numPools = static_cast<unsigned int>(values[3]);
    assert( startVoxel >= startVoxel_ );
    assert( numVoxels <= pools_.size() );
    assert( pools_.size() > 0 );
    assert( numPools + startPool <= pools_[0].size() );
    assert( values.size() == 4 + numVoxels * numPools );
    for ( unsigned int i = 0; i < numVoxels; ++i )
    {
        double* v = pools_[ startVoxel + i ].varS();
        for ( unsigned int j = 0; j < numPools; ++j )
        {
            v[ j + startPool ] = values[ 4 + j * numVoxels + i ];
        }
    }
}
References pools_, VoxelPoolsBase::size(), startVoxel_, and VoxelPoolsBase::varS().
Referenced by process().
setConcInit()
void Ksolve::setConcInit (const Eref & e, double val) virtual
Set initial conc of molecules in given pool and voxel. Bdry cond.
Implements KsolveBase.
Definition at line 772 of file Ksolve.cpp.
{
    unsigned int vox = getVoxelIndex( e );
    if ( vox != OFFNODE )
        pools_[vox].setConcInit( getPoolIndex( e ), v );
}
References getPoolIndex(), getVoxelIndex(), OFFNODE, pools_, and VoxelPoolsBase::setConcInit().
setDiffConst()
void Ksolve::setDiffConst (const Eref & e, double val) virtual
Diffusion constant: Only one per pool, voxel number is ignored.
Implements KsolveBase.
Definition at line 793 of file Ksolve.cpp.
{
    ; // Do nothing.
}
setDsolve()
void Ksolve::setDsolve (Id dsolve) virtual
Assigns the diffusion solver. Used by the reac solvers.
Implements KsolveBase.
Definition at line 434 of file Ksolve.cpp.
{
    if ( dsolve == Id () )
    {
        dsolvePtr_ = nullptr;
        dsolve_ = Id();
    }
    else if ( dsolve.element()->cinfo()->isA( "Dsolve" ) )
    {
        dsolve_ = dsolve;
        dsolvePtr_ = reinterpret_cast<KsolveBase*>(dsolve.eref().data());
    }
    else
    {
        cout << "Warning: Ksolve::setDsolve: Object '" << dsolve.path()
            << "' should be class Dsolve, is: "
            << dsolve.element()->cinfo()->name() << endl;
    }
}
References Element::cinfo(), Eref::data(), dsolve_, dsolvePtr_, Id::element(), Id::eref(), Id::Id(), Cinfo::isA(), Cinfo::name(), Id::operator==(), and Id::path().
setEpsAbs()
void Ksolve::setEpsAbs (double val)
Definition at line 309 of file Ksolve.cpp.
{
    if ( epsAbs < 0 )
        epsAbs_ = 1.0e-4;
    else
        epsAbs_ = epsAbs;
}
References epsAbs_.
Referenced by initCinfo().
setEpsRel()
void Ksolve::setEpsRel (double val)
Definition at line 323 of file Ksolve.cpp.
{
    if ( epsRel < 0 )
    {
        epsRel_ = 1.0e-6;
    }
    else
    {
        epsRel_ = epsRel;
    }
}
References epsRel_.
Referenced by initCinfo().
setMethod()
void Ksolve::setMethod (string method)
Definition at line 267 of file Ksolve.cpp.
{
    std::transform(method.begin(), method.end(), method.begin(), ::tolower);
    // If user is trying to set ksolve method after ksolve has been initialized,
    // show a warning.
    if( isBuilt_ )
    {
        moose::showWarn(
            "You are trying to set Ksolve::method after moose::Stoich has been "
            " initialized. This will be ignored. Please do before ksolve is assigned to "
            " moose::Stoich."
            );
        return;
    }
#if USE_GSL
    if ( method == "rk5" || method == "gsl" )
    {
        method_ = "rk5";
    }
    else if ( method == "rk4"  || method == "rk2" ||
              method == "rk8" || method == "rkck" || method == "lsoda" )
    {
        method_ = method;
    }
    else
    {
        cout << "Warning: Ksolve::setMethod: '" << method <<
             "' is not known, using default rk5\n";
        method_ = "rk5";
    }
#elif USE_BOOST_ODE
    // TODO: Check for boost related methods.
    method_ = method;
#endif
}
References KsolveBase::isBuilt_, and moose::showWarn().
Referenced by initCinfo().
setN()
void Ksolve::setN (const Eref & e, double val) virtual
Set # of molecules in given pool and voxel. Varies with time.
Implements KsolveBase.
Definition at line 749 of file Ksolve.cpp.
{
    unsigned int vox = getVoxelIndex( e );
    if ( vox != OFFNODE )
        pools_[vox].setN( getPoolIndex( e ), v );
}
References getPoolIndex(), getVoxelIndex(), OFFNODE, pools_, and VoxelPoolsBase::setN().
setNumAllVoxels()
void Ksolve::setNumAllVoxels (unsigned int num) virtual
Assigns the number of voxels used in the entire reac-diff system. Note that fewer than this may be used on any given node.
Implements KsolveBase.
Definition at line 465 of file Ksolve.cpp.
{
    if ( numVoxels == 0 )
    {
        return;
    }
    pools_.resize( numVoxels );
}
References pools_.
Referenced by initCinfo().
setNumPools()
void Ksolve::setNumPools (unsigned int num) virtual
Assigns number of different pools (chemical species) present in each voxel. Inherited.
Implements KsolveBase.
Definition at line 803 of file Ksolve.cpp.
{
    unsigned int numVoxels = pools_.size();
    for ( unsigned int i = 0 ; i < numVoxels; ++i )
    {
        pools_[i].resizeArrays( numPoolSpecies );
    }
}
References pools_, and VoxelPoolsBase::resizeArrays().
Referenced by initCinfo().
setNumThreads()
void Ksolve::setNumThreads (unsigned int x)
Definition at line 335 of file Ksolve.cpp.
{
    numThreads_ = x;
}
References numThreads_.
Referenced by initCinfo().
setNumVarTotPools()
void Ksolve::setNumVarTotPools (unsigned int var, unsigned int tot) virtual
Specifies number of var pools and total pools including buffered .
Implements KsolveBase.
Definition at line 812 of file Ksolve.cpp.
{
    unsigned int numVoxels = pools_.size();
    for ( unsigned int i = 0 ; i < numVoxels; ++i )
    {
        pools_[i].resizeArrays( tot );
    }
}
References pools_, and VoxelPoolsBase::resizeArrays().
setNvec()
void Ksolve::setNvec (unsigned int voxel, vector< double > vec)
Definition at line 484 of file Ksolve.cpp.
{
    if ( voxel < pools_.size() )
    {
        if ( nVec.size() != pools_[voxel].size() )
        {
            cout << "Warning: Ksolve::setNvec: size mismatch ( " <<
                 nVec.size() << ", " << pools_[voxel].size() << ")\n";
            return;
        }
        double* s = pools_[voxel].varS();
        for ( unsigned int i = 0; i < nVec.size(); ++i )
            s[i] = nVec[i];
    }
}
References pools_, VoxelPoolsBase::size(), and VoxelPoolsBase::varS().
Referenced by initCinfo().
setStoich()
void Ksolve::setStoich (Id stoich) virtual
Informs the ZPI about the stoich, used during subsequent computations. Called to wrap up the model building. The Stoich does this call after it has set up its own path.
Implements KsolveBase.
Definition at line 381 of file Ksolve.cpp.
{
    assert( stoich.element()->cinfo()->isA( "Stoich" ) );
    stoich_ = stoich;
    stoichPtr_ = reinterpret_cast< Stoich* >( stoich.eref().data() );
    if ( !isBuilt_ )
    {
        OdeSystem ode;
        ode.epsAbs = epsAbs_;
        ode.epsRel = epsRel_;
        // ode.initStepSize = getEstimatedDt();
        ode.initStepSize = 0.01; // This will be overridden at reinit.
        ode.method = method_;
#ifdef USE_GSL
        ode.gslSys.dimension = stoichPtr_->getNumAllPools();
        if ( ode.gslSys.dimension == 0 )
        {
            stoichPtr_ = 0;
            return; // No pools, so don't bother.
        }
        innerSetMethod( ode, method_ );
        ode.gslSys.function = &VoxelPools::gslFunc;
        ode.gslSys.jacobian = 0;
        innerSetMethod( ode, method_ );
        unsigned int numVoxels = pools_.size();
        for ( unsigned int i = 0 ; i < numVoxels; ++i )
        {
            ode.gslSys.params = &pools_[i];
            pools_[i].setStoich( stoichPtr_, &ode );
            // pools_[i].setIntDt( ode.initStepSize ); // We're setting it up anyway
        }
#elif USE_BOOST_ODE
        ode.dimension = stoichPtr_->getNumAllPools();
        if ( ode.dimension == 0 )
            return; // No pools, so don't bother.
        unsigned int numVoxels = pools_.size();
        for ( unsigned int i = 0 ; i < numVoxels; ++i )
        {
            pools_[i].setStoich( stoichPtr_, &ode );
        }
#endif
        isBuilt_ = true;
    }
}
References Element::cinfo(), Eref::data(), Id::element(), OdeSystem::epsAbs, epsAbs_, OdeSystem::epsRel, epsRel_, Id::eref(), OdeSystem::initStepSize, Cinfo::isA(), KsolveBase::isBuilt_, OdeSystem::method, method_, KsolveBase::stoich_, and stoichPtr_.
updateRateTerms()
void Ksolve::updateRateTerms (unsigned int index) virtual
Rescale specified voxel rate term following rate constant change or volume change. If index == ~0U then does all terms.
updateRateTerms obtains the latest parameters for the rates_ vector, and has each of the pools update its parameters including rescaling for volumes.
Implements KsolveBase.
Definition at line 703 of file Ksolve.cpp.
{
    if ( index == ~0U )
    {
        for ( unsigned int i = 0 ; i < pools_.size(); ++i )
        {
            pools_[i].updateAllRateTerms( stoichPtr_->getRateTerms(),
                                          stoichPtr_->getNumCoreRates() );
        }
    }
    else if ( index < stoichPtr_->getNumRates() )
    {
        for ( unsigned int i = 0 ; i < pools_.size(); ++i )
            pools_[i].updateRateTerms( stoichPtr_->getRateTerms(),
                                       stoichPtr_->getNumCoreRates(), index );
    }
}
References Stoich::getNumCoreRates(), Stoich::getNumRates(), Stoich::getRateTerms(), pools_, stoichPtr_, VoxelPools::updateAllRateTerms(), and VoxelPools::updateRateTerms().
Referenced by updateVoxelVol().
updateVoxelVol()
void Ksolve::updateVoxelVol (vector< double > vols)
Handles request to change volumes of voxels in this Ksolve, and all cascading effects of this. At this point it won't handle change in size of voxel array.
Definition at line 924 of file Ksolve.cpp.
{
    // For now we assume identical numbers of voxels. Also assume
    // identical voxel junctions. But it should not be too hard to
    // update those too.
    if ( vols.size() == pools_.size() )
    {
        for ( unsigned int i = 0; i < vols.size(); ++i )
        {
            pools_[i].setVolumeAndDependencies( vols[i] );
        }
        updateRateTerms( ~0U );
    }
}
References pools_, VoxelPools::setVolumeAndDependencies(), and updateRateTerms().
Referenced by initCinfo().
volume()
double Ksolve::volume (unsigned int i) const virtual
Return volume of voxel i.
Implements KsolveBase.
Definition at line 835 of file Ksolve.cpp.
{
    if ( pools_.size() > i )
        return pools_[i].getVolume();
    return 0.0;
}
References VoxelPoolsBase::getVolume(), and pools_.
Member Data Documentation
defaultPoolLookup_
map< Id, unsigned int > Ksolve::defaultPoolLookup_ static private
Definition at line 198 of file Ksolve.h.
Referenced by getPoolIndex(), notifyAddPool(), and notifyRemovePool().
dsolve_
Id Ksolve::dsolve_ private
Id of diffusion solver, needed for coordinating numerics.
Definition at line 183 of file Ksolve.h.
Referenced by getDsolve(), Ksolve(), print(), and setDsolve().
dsolvePtr_
KsolveBase* Ksolve::dsolvePtr_ private
Pointer to diffusion solver.
Definition at line 186 of file Ksolve.h.
Referenced by Ksolve(), process(), and setDsolve().
epsAbs_
double Ksolve::epsAbs_ private
Definition at line 156 of file Ksolve.h.
Referenced by getEpsAbs(), Ksolve(), setEpsAbs(), and setStoich().
epsRel_
double Ksolve::epsRel_ private
Definition at line 157 of file Ksolve.h.
Referenced by getEpsRel(), Ksolve(), setEpsRel(), and setStoich().
grainSize_
size_t Ksolve::grainSize_ private
Definition at line 163 of file Ksolve.h.
intervals_
vector<std::pair<size_t, size_t> > Ksolve::intervals_ private
Definition at line 194 of file Ksolve.h.
Referenced by process(), and reinit().
method_
string Ksolve::method_ private
Definition at line 155 of file Ksolve.h.
Referenced by getMethod(), Ksolve(), print(), and setStoich().
numSteps_
size_t Ksolve::numSteps_ = 0 private
Definition at line 189 of file Ksolve.h.
numThreads_
size_t Ksolve::numThreads_ private
Number of threads to use. Only applicable for deterministic case.
Definition at line 162 of file Ksolve.h.
Referenced by getNumThreads(), Ksolve(), process(), reinit(), and setNumThreads().
pools_
vector< VoxelPools > Ksolve::pools_ private
Each VoxelPools entry handles all the pools in a single voxel. Each entry knows how to update itself in order to complete the kinetic calculations for that voxel. The ksolver does multinode management by indexing only the subset of entries present on this node.
Definition at line 172 of file Ksolve.h.
Referenced by advance_chunk(), advance_pool(), getBlock(), getConcInit(), getEstimatedDt(), getN(), getNumAllVoxels(), getNumLocalVoxels(), getNumPools(), getNvec(), getR1(), getR1vec(), getRateVecFromId(), getRateVecFromPath(), getVolumeOfPool(), getVoxelIndex(), initReinit(), Ksolve(), notifyAddPool(), pools(), print(), process(), reinit(), setBlock(), setConcInit(), setN(), setNumAllVoxels(), setNumPools(), setNumVarTotPools(), setNvec(), updateRateTerms(), updateVoxelVol(), and volume().
startVoxel_
unsigned int Ksolve::startVoxel_ private
First voxel indexed on the current node.
Definition at line 175 of file Ksolve.h.
Referenced by getBlock(), getVoxelIndex(), Ksolve(), and setBlock().
stoichPtr_
Stoich* Ksolve::stoichPtr_ private
Utility ptr used to help Pool Id lookups by the Ksolve.
Definition at line 178 of file Ksolve.h.
Referenced by getEstimatedDt(), getPoolIndex(), getRateVecFromId(), getRateVecFromPath(), notifyAddPool(), notifyRemovePool(), print(), process(), reinit(), setStoich(), and updateRateTerms().
totalTime_
double Ksolve::totalTime_ = 0.0 private
Definition at line 192 of file Ksolve.h.
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/ksolve/Ksolve.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/ksolve/Ksolve.cpp