MOOSE - Multiscale Object Oriented Simulation Environment: RC Class Reference
RC Class Reference
#include <RC.h>
Public Member Functions
double getCapacitance () const
double getInject () const
double getResistance () const
double getState () const
double getV0 () const
void process (const Eref &e, ProcPtr proc)
RC ()
void reinit (const Eref &e, ProcPtr proc)
void setCapacitance (double capacitance)
void setInject (double inject)
void setInjectMsg (double inject)
void setResistance (double resistance)
void setV0 (double voltage)
Static Public Member Functions
static const Cinfo * initCinfo ()
Private Attributes
double capacitance_
double dt_tau_
double expTau_
double inject_
double msg_inject_
double resistance_
double state_
double v0_
Detailed Description
Definition at line 46 of file RC.h.
Constructor & Destructor Documentation
RC()
RC::RC ()
Definition at line 125 of file RC.cpp.
      :
        v0_(0),
        resistance_(1.0),
        capacitance_(1.0),
        state_(0),
        inject_(0),
        msg_inject_(0.0),
        expTau_(0.0),
        dt_tau_(0.0)
{
    ;   // Do nothing
}
References capacitance_, dt_tau_, expTau_, inject_, msg_inject_, resistance_, state_, and v0_.
Member Function Documentation
getCapacitance()
double RC::getCapacitance () const
Definition at line 168 of file RC.cpp.
{
    return capacitance_;
}
References capacitance_.
Referenced by initCinfo().
getInject()
double RC::getInject () const
Definition at line 186 of file RC.cpp.
{
    return inject_;
}
References inject_.
Referenced by initCinfo().
getResistance()
double RC::getResistance () const
Definition at line 156 of file RC.cpp.
{
    return resistance_;
}
References resistance_.
Referenced by initCinfo().
getState()
double RC::getState () const
Definition at line 174 of file RC.cpp.
{
    return state_;
}
References state_.
Referenced by initCinfo().
getV0()
double RC::getV0 () const
Definition at line 144 of file RC.cpp.
{
    return v0_;
}
References v0_.
Referenced by initCinfo().
initCinfo()
const Cinfo * RC::initCinfo () static
Definition at line 50 of file RC.cpp.
{
        static DestFinfo process("process",
                      "Handles process call.",
                      new ProcOpFunc<RC>(&RC::process));
        static DestFinfo reinit( "reinit",
                       "Handle reinitialization",
                       new ProcOpFunc<RC>( &RC::reinit ));
    static Finfo* processShared[] = {
        &process, &reinit
    };
    static SharedFinfo proc("proc",
                                         "This is a shared message to receive Process messages "
                                         "from the scheduler objects."
                                         "The first entry in the shared msg is a MsgDest "
                                         "for the Process operation. It has a single argument, "
                                         "ProcInfo, which holds lots of information about current "
                                         "time, thread, dt and so on. The second entry is a MsgDest "
                                         "for the Reinit operation. It also uses ProcInfo. ",
                                         processShared,
                                         sizeof( processShared ) / sizeof( Finfo* ));
        static ValueFinfo<RC, double> V0( "V0",
                                    "Initial value of 'state'",
                                    &RC::setV0,
                                    &RC::getV0 );
        static ValueFinfo<RC, double> R( "R",
                                    "Series resistance of the RC circuit.",
                                    &RC::setResistance,
                                    &RC::getResistance);
        static ValueFinfo<RC, double> C( "C",
                                    "Parallel capacitance of the RC circuit.",
                                    &RC::setCapacitance,
                                    &RC::getCapacitance);
        static ReadOnlyValueFinfo<RC, double> state("state",
                               "Output value of the RC circuit. This is the voltage across the"
                               " capacitor.",
                               &RC::getState);
        static ValueFinfo<RC, double> inject( "inject",
                        "Input value to the RC circuit.This is handled as an input current to"
                        " the circuit.",
                        &RC::setInject,
                        &RC::getInject );
        static DestFinfo injectIn( "injectIn",
                       "Receives input to the RC circuit. All incoming messages are summed up"
                       " to give the total input current." ,
                       new OpFunc1<RC, double>(&RC::setInjectMsg));
    static Finfo* rcFinfos[] = {
        &V0,
        &R,
        &C,
        &state,
        &inject,
        outputOut(),
        &injectIn,
        &proc,
    };
    static string doc[] = {
        "Name", "RC",
        "Author", "Subhasis Ray, 2008, NCBS",
        "Description", "RC circuit: a series resistance R shunted by a capacitance C." };
    static Dinfo<RC> dinfo;
    static Cinfo rcCinfo("RC",
                         Neutral::initCinfo(),
                         rcFinfos,
                         sizeof( rcFinfos ) / sizeof( Finfo* ),
                         &dinfo,
                         doc,
                         sizeof(doc)/sizeof(string)
                         );
    return &rcCinfo;
}
References Cinfo::Cinfo(), DestFinfo::DestFinfo(), getCapacitance(), getInject(), getResistance(), getState(), getV0(), Neutral::initCinfo(), OpFunc1< T, A >::OpFunc1(), outputOut(), process(), ProcOpFunc< T >::ProcOpFunc(), ReadOnlyValueFinfo< T, F >::ReadOnlyValueFinfo(), reinit(), setCapacitance(), setInject(), setInjectMsg(), setResistance(), setV0(), SharedFinfo::SharedFinfo(), and ValueFinfo< T, F >::ValueFinfo().
process()
void RC::process (const Eref & e, ProcPtr proc)
calculates the new voltage across the capacitor. this is the exact solution as described in Electronic Circuit and System Simulation Methods by Lawrance Pillage, McGraw-Hill Professional, 1999. pp 87-100. Eqn: 4.7.21
OR, if we use simple Euler: ///
Definition at line 204 of file RC.cpp.
{
    /*
    double sum_inject_prev = inject_ + msg_inject_;
    double sum_inject = inject_ + msg_inject_;
    double dVin = (sum_inject - sum_inject_prev) * resistance_;
    double Vin = sum_inject * resistance_;
    state_ = Vin + dVin - dVin / dt_tau_ +
            (state_ - Vin + dVin / dt_tau_) * expTau_;
    sum_inject_prev = sum_inject;
    msg_inject_ = 0.0;
    outputOut()->send(e, state_);
    */
    // double A = inject + msgInject_;
    // double B = 1.0/resistance_;
    // double x = exp( -B * proc->dt / capacitance_ );
    // state_ = state_ * x + (A/B) * (1.0-x);
    // double x = exp( -dt_tau_ );
    state_ = state_ * expTau_ +
        resistance_*(inject_ + msg_inject_) * (1.0-expTau_);
    // state_ += (inject_ + msgInject_ - state_/resistance_ ) * proc->dt / capacitance_;
    msg_inject_ = 0.0;
    outputOut()->send(e, state_);
}
References expTau_, inject_, msg_inject_, outputOut(), resistance_, SrcFinfo1< T >::send(), and state_.
Referenced by initCinfo().
reinit()
void RC::reinit (const Eref & e, ProcPtr proc)
Definition at line 234 of file RC.cpp.
{
    dt_tau_ = proc->dt / (resistance_ * capacitance_);
    state_ = v0_;
    if (dt_tau_ > 1e-15){
        expTau_ = exp(-dt_tau_);
    } else {// use approximation
        expTau_ = 1 - dt_tau_;
    }
    msg_inject_ = 0.0;
    outputOut()->send(e, state_);
}
References capacitance_, ProcInfo::dt, dt_tau_, expTau_, msg_inject_, outputOut(), resistance_, SrcFinfo1< T >::send(), state_, and v0_.
Referenced by initCinfo().
setCapacitance()
void RC::setCapacitance (double capacitance)
Definition at line 162 of file RC.cpp.
{
    capacitance_ = capacitance;
}
References capacitance_.
Referenced by initCinfo().
setInject()
void RC::setInject (double inject)
Definition at line 180 of file RC.cpp.
{
    inject_ = inject;
}
References inject_.
Referenced by initCinfo().
setInjectMsg()
void RC::setInjectMsg (double inject)
Definition at line 192 of file RC.cpp.
{
    msg_inject_ += inject;
}
References msg_inject_.
Referenced by initCinfo().
setResistance()
void RC::setResistance (double resistance)
Definition at line 150 of file RC.cpp.
{
    resistance_ = resistance;
}
References resistance_.
Referenced by initCinfo().
setV0()
void RC::setV0 (double voltage)
Definition at line 138 of file RC.cpp.
{
    v0_ = v0;
}
References v0_.
Referenced by initCinfo().
Member Data Documentation
capacitance_
double RC::capacitance_ private
Definition at line 65 of file RC.h.
Referenced by getCapacitance(), RC(), reinit(), and setCapacitance().
dt_tau_
double RC::dt_tau_ private
Definition at line 70 of file RC.h.
Referenced by RC(), and reinit().
expTau_
double RC::expTau_ private
Definition at line 69 of file RC.h.
Referenced by process(), RC(), and reinit().
inject_
double RC::inject_ private
Definition at line 67 of file RC.h.
Referenced by getInject(), process(), RC(), and setInject().
msg_inject_
double RC::msg_inject_ private
Definition at line 68 of file RC.h.
Referenced by process(), RC(), reinit(), and setInjectMsg().
resistance_
double RC::resistance_ private
Definition at line 64 of file RC.h.
Referenced by getResistance(), process(), RC(), reinit(), and setResistance().
state_
double RC::state_ private
Definition at line 66 of file RC.h.
Referenced by getState(), process(), RC(), and reinit().
v0_
double RC::v0_ private
Definition at line 63 of file RC.h.
Referenced by getV0(), RC(), reinit(), and setV0().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/device/RC.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/device/RC.cpp