MOOSE - Multiscale Object Oriented Simulation Environment: moose::ExIF Class Reference
moose::ExIF Class Reference
#include <ExIF.h>
Public Member Functions
ExIF ()
double getDeltaThresh (const Eref &e) const
double getVPeak (const Eref &e) const
void setDeltaThresh (const Eref &e, double val)
void setVPeak (const Eref &e, double val)
void vProcess (const Eref &e, ProcPtr p)
void vReinit (const Eref &e, ProcPtr p)
virtual ~ExIF ()
Public Member Functions inherited from moose::IntFireBase
void activation (double val)
double getLastEventTime (const Eref &e) const
double getRefractoryPeriod (const Eref &e) const
double getThresh (const Eref &e) const
double getVReset (const Eref &e) const
bool hasFired (const Eref &e) const
IntFireBase ()
void setRefractoryPeriod (const Eref &e, double val)
void setThresh (const Eref &e, double val)
void setVReset (const Eref &e, double val)
virtual ~IntFireBase ()
Public Member Functions inherited from moose::Compartment
void cable ()
Compartment ()
virtual double vGetCm (const Eref &e) const
virtual double vGetEm (const Eref &e) const
virtual double vGetIm (const Eref &e) const
virtual double vGetInitVm (const Eref &e) const
virtual double vGetInject (const Eref &e) const
virtual double vGetRa (const Eref &e) const
virtual double vGetRm (const Eref &e) const
virtual double vGetVm (const Eref &e) const
void vHandleAxial (double Vm)
void vHandleChannel (const Eref &e, double Gk, double Ek)
void vHandleRaxial (double Ra, double Vm)
void vInitProc (const Eref &e, ProcPtr p)
void vInitReinit (const Eref &e, ProcPtr p)
void vInjectMsg (const Eref &e, double current)
void vRandInject (const Eref &e, double prob, double current)
virtual void vSetCm (const Eref &e, double Cm)
virtual void vSetEm (const Eref &e, double Em)
virtual void vSetInitVm (const Eref &e, double initVm)
virtual void vSetInject (const Eref &e, double Inject)
virtual void vSetRa (const Eref &e, double Ra)
virtual void vSetRm (const Eref &e, double Rm)
virtual void vSetVm (const Eref &e, double Vm)
virtual ~Compartment ()
Public Member Functions inherited from moose::CompartmentBase
void cable ()
CompartmentBase ()
void displace (double dx, double dy, double dz)
Displaces compartment by specified distance vector.
double getCm (const Eref &e) const
vector< double > getCoords () const
double getDiameter () const
double getEm (const Eref &e) const
double getIm (const Eref &e) const
double getInitVm (const Eref &e) const
double getInject (const Eref &e) const
double getLength () const
double getRa (const Eref &e) const
double getRm (const Eref &e) const
double getVm (const Eref &e) const
double getX () const
double getX0 () const
double getY () const
double getY0 () const
double getZ () const
double getZ0 () const
void handleAxial (double Vm)
void handleChannel (const Eref &e, double Gk, double Ek)
void handleRaxial (double Ra, double Vm)
void initProc (const Eref &e, ProcPtr p)
void initReinit (const Eref &e, ProcPtr p)
void injectMsg (const Eref &e, double current)
void process (const Eref &e, ProcPtr p)
void randInject (const Eref &e, double prob, double current)
bool rangeWarning (const string &field, double value)
void reinit (const Eref &e, ProcPtr p)
void setCm (const Eref &e, double Cm)
void setCoords (vector< double > value)
void setDiameter (double diameter)
void setEm (const Eref &e, double Em)
void setGeomAndElec (const Eref &e, double length, double dia)
Scales electrical values along with setting length, dia.
void setInitVm (const Eref &e, double initVm)
void setInject (const Eref &e, double Inject)
void setLength (double length)
void setRa (const Eref &e, double Ra)
void setRm (const Eref &e, double Rm)
void setVm (const Eref &e, double Vm)
void setX (double value)
void setX0 (double value)
void setY (double value)
void setY0 (double value)
void setZ (double value)
void setZ0 (double value)
void updateLength ()
virtual void vSetSolver (const Eref &e, Id hsolve)
virtual ~CompartmentBase ()
Static Public Member Functions
static const Cinfo * initCinfo ()
Static Public Member Functions inherited from moose::IntFireBase
static const Cinfo * initCinfo ()
static SrcFinfo1< double > * spikeOut ()
Message src for outgoing spikes.
Static Public Member Functions inherited from moose::Compartment
static const Cinfo * initCinfo ()
Static Public Member Functions inherited from moose::CompartmentBase
static const Cinfo * initCinfo ()
static SrcFinfo1< double > * VmOut ()
static void zombify (Element *orig, const Cinfo *zClass, Id hsolve)
Protected Attributes
double deltaThresh_
double vPeak_
Protected Attributes inherited from moose::IntFireBase
double activation_
bool fired_
double lastEvent_
double refractT_
double threshold_
double vReset_
Protected Attributes inherited from moose::Compartment
double A_
double B_
double Cm_
double Em_
double Im_
double initVm_
double inject_
double lastIm_
double Ra_
double Rm_
double sumInject_
double Vm_
Detailed Description
The IntFire class sets up an integrate-and-fire compartment.
Definition at line 19 of file ExIF.h.
Constructor & Destructor Documentation
ExIF()
ExIF::ExIF ()
Definition at line 70 of file ExIF.cpp.
{vPeak_ = 0.0;
deltaThresh_ = 0.0;}
References deltaThresh_, and vPeak_.
~ExIF()
ExIF::~ExIF () virtual
Definition at line 74 of file ExIF.cpp.
{;}
Member Function Documentation
getDeltaThresh()
double ExIF::getDeltaThresh (const Eref & e) const
Definition at line 125 of file ExIF.cpp.
{
    return deltaThresh_;
}
References deltaThresh_.
Referenced by initCinfo().
getVPeak()
double ExIF::getVPeak (const Eref & e) const
Definition at line 135 of file ExIF.cpp.
{
    return vPeak_;
}
References vPeak_.
Referenced by initCinfo().
initCinfo()
const Cinfo * ExIF::initCinfo () static
Initializes the class info.
Definition at line 19 of file ExIF.cpp.
{
    static string doc[] =
    {
        "Name", "ExIF",
        "Author", "Aditya Gilra",
        "Description", "Leaky Integrate-and-Fire neuron with Exponential spike rise."
        "Rm*Cm dVm/dt = -(Vm-Em) + deltaThresh * exp((Vm-thresh)/deltaThresh) + Rm*I"
    };
    static ElementValueFinfo< ExIF, double > deltaThresh(
        "deltaThresh",
        "Parameter in Vm evolution equation:"
        "Rm*Cm * dVm/dt = -(Vm-Em) + deltaThresh * exp((Vm-thresh)/deltaThresh) + Rm*I",
        &ExIF::setDeltaThresh,
        &ExIF::getDeltaThresh
    );
    static ElementValueFinfo< ExIF, double > vPeak(
        "vPeak",
        "Vm is reset on reaching vPeak, different from spike thresh below:"
        "Rm*Cm dVm/dt = -(Vm-Em) + deltaThresh * exp((Vm-thresh)/deltaThresh) + Rm*I",
        &ExIF::setVPeak,
        &ExIF::getVPeak
    );
    static Finfo* ExIFFinfos[] = {
        &deltaThresh,       // Value
        &vPeak,             // Value
    };
    static Dinfo< ExIF > dinfo;
    static Cinfo ExIFCinfo(
                "ExIF",
                IntFireBase::initCinfo(),
                ExIFFinfos,
                sizeof( ExIFFinfos ) / sizeof (Finfo*),
                &dinfo,
                doc,
                sizeof(doc)/sizeof(string)
    );
    return &ExIFCinfo;
}
References Cinfo::Cinfo(), ElementValueFinfo< T, F >::ElementValueFinfo(), getDeltaThresh(), getVPeak(), moose::IntFireBase::initCinfo(), setDeltaThresh(), and setVPeak().
Referenced by moose::AdExIF::initCinfo().
setDeltaThresh()
void ExIF::setDeltaThresh (const Eref & e, double val)
Definition at line 120 of file ExIF.cpp.
{
    deltaThresh_ = val;
}
References deltaThresh_.
Referenced by initCinfo().
setVPeak()
void ExIF::setVPeak (const Eref & e, double val)
Definition at line 130 of file ExIF.cpp.
{
    vPeak_ = val;
}
References vPeak_.
Referenced by initCinfo().
vProcess()
void ExIF::vProcess (const Eref & e, ProcPtr p) virtual
The process function does the object updating and sends out messages to channels, nernsts, and so on.
Implements moose::IntFireBase.
Definition at line 81 of file ExIF.cpp.
{
    fired_ = false;
    if ( p->currTime < lastEvent_ + refractT_ ) {
        Vm_ = vReset_;
        A_ = 0.0;
        B_ = 1.0 / Rm_;
        sumInject_ = 0.0;
        VmOut()->send( e, Vm_ );
    } else {
        // activation can be a continous variable (graded synapse).
        // So integrate it at every time step, thus *dt.
        // For a delta-fn synapse, SynHandler-s divide by dt and send activation.
        // See: http://www.genesis-sim.org/GENESIS/Hyperdoc/Manual-26.html#synchan
        //          for this continuous definition of activation.
        Vm_ += activation_ * p->dt;
        activation_ = 0.0;
        if ( Vm_ >= vPeak_ ) {
            Vm_ = vReset_;
            lastEvent_ = p->currTime;
            fired_ = true;
            spikeOut()->send( e, p->currTime );
            VmOut()->send( e, Vm_ );
        } else {
            Vm_ += deltaThresh_ * exp((Vm_-threshold_)/deltaThresh_) *p->dt/Rm_/Cm_;
            Compartment::vProcess( e, p );  // this sends out Vm message also,
                                            // so do calculations before
        }
    }
}
References moose::Compartment::A_, moose::IntFireBase::activation_, moose::Compartment::B_, moose::Compartment::Cm_, ProcInfo::currTime, deltaThresh_, ProcInfo::dt, moose::IntFireBase::fired_, moose::IntFireBase::lastEvent_, moose::IntFireBase::refractT_, moose::Compartment::Rm_, SrcFinfo1< T >::send(), moose::IntFireBase::spikeOut(), moose::Compartment::sumInject_, moose::IntFireBase::threshold_, moose::Compartment::Vm_, moose::CompartmentBase::VmOut(), vPeak_, moose::Compartment::vProcess(), and moose::IntFireBase::vReset_.
vReinit()
void ExIF::vReinit (const Eref & e, ProcPtr p) virtual
The reinit function reinitializes all fields.
Implements moose::IntFireBase.
Definition at line 112 of file ExIF.cpp.
{
    activation_ = 0.0;
    fired_ = false;
    lastEvent_ = -refractT_; // Allow it to fire right away.
    Compartment::vReinit( e, p );
}
References moose::IntFireBase::activation_, moose::IntFireBase::fired_, moose::IntFireBase::lastEvent_, moose::IntFireBase::refractT_, and moose::Compartment::vReinit().
Member Data Documentation
deltaThresh_
double moose::ExIF::deltaThresh_ protected
Definition at line 47 of file ExIF.h.
Referenced by ExIF(), getDeltaThresh(), setDeltaThresh(), moose::AdExIF::vProcess(), and vProcess().
vPeak_
double moose::ExIF::vPeak_ protected
Definition at line 48 of file ExIF.h.
Referenced by ExIF(), getVPeak(), setVPeak(), moose::AdExIF::vProcess(), and vProcess().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/intfire/ExIF.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/intfire/ExIF.cpp