MOOSE - Multiscale Object Oriented Simulation Environment: PsdMesh Class Reference
PsdMesh Class Reference
#include <PsdMesh.h>
Public Member Functions
void buildStencil ()
double extendedMeshEntryVolume (unsigned int fid) const
Vol of all mesh Entries including abutting diff-coupled voxels.
vector< double > getCoordinates (unsigned int fid) const
Virtual function to return coords of mesh Entry.
vector< double > getDiffusionArea (unsigned int fid) const
Virtual function to return diffusion X-section area.
vector< double > getDiffusionScaling (unsigned int fid) const
Virtual function to return scale factor for diffusion. 1 here.
vector< Id > getElecComptMap () const
vector< unsigned int > getEndVoxelInCompt () const
Returns index of end voxel mapping to elec compt, just first+1.
unsigned int getMeshDimensions (unsigned int fid) const
Virtual function to return dimensions of specified entry.
double getMeshEntryVolume (unsigned int fid) const
Virtual function to return volume of mesh Entry.
unsigned int getMeshType (unsigned int fid) const
Virtual function to return MeshType of specified entry.
vector< unsigned int > getNeuronVoxel () const
vector< unsigned int > getParentVoxel () const
vector< unsigned int > getStartVoxelInCompt () const
Returns index of first voxel mapping to elec compt.
double getThickness () const
const vector< double > & getVoxelArea () const
const vector< double > & getVoxelLength () const
void handlePsdList (const Eref &e, vector< double > params, vector< Id > elecCompts, vector< unsigned int > parentVoxel)
void indexToSpace (unsigned int index, double &x, double &y, double &z) const
void innerBuildDefaultMesh (const Eref &e, double volume, unsigned int numEntries)
Virtual func to make a mesh with specified Volume and numEntries.
unsigned int innerGetDimensions () const
Returns # of dimensions, always 3 here. Inherited pure virt func.
unsigned int innerGetNumEntries () const
void innerHandleNodeInfo (const Eref &e, unsigned int numNodes, unsigned int numThreads)
void innerHandleRequestMeshStats (const Eref &e, const SrcFinfo2< unsigned int, vector< double > > *meshStatsFinfo)
void innerSetNumEntries (unsigned int n)
Inherited virtual func.
void matchCubeMeshEntries (const ChemCompt *other, vector< VoxelJunction > &ret) const
void matchMeshEntries (const ChemCompt *other, vector< VoxelJunction > &ret) const
void matchNeuroMeshEntries (const ChemCompt *other, vector< VoxelJunction > &ret) const
void matchSpineMeshEntries (const ChemCompt *other, vector< VoxelJunction > &ret) const
double nearest (double x, double y, double z, unsigned int &index) const
unsigned int parent (unsigned int index) const
PsdMesh ()
PsdMesh (const PsdMesh &other)
void setMeshEntryVolume (unsigned int fid, double volume)
Virtual function to set volume of mesh Entry.
void setThickness (double v)
void transmitChange (const Eref &e)
void updateCoords ()
double vGetEntireVolume () const
Inherited virtual func.
const vector< double > & vGetVoxelMidpoint () const
Virtual func so that derived classes can return voxel midpoint.
const vector< double > & vGetVoxelVolume () const
Virtual func so that derived classes can pass voxel volume back.
bool vSetVolumeNotRates (double volume)
Inherited virtual func.
~PsdMesh ()
Public Member Functions inherited from MeshCompt
void addRow (unsigned int index, const vector< double > &entry, const vector< unsigned int > &colIndex)
void clearExtendedMeshEntryVolume ()
Inherited virtual function to clear the vector of MeshEntryVolume.
void extendStencil (const ChemCompt *other, const vector< VoxelJunction > &vj)
Add boundary voxels to stencil for cross-solver junctions.
vector< unsigned int > getNeighbors (unsigned int fid) const
Looks up stencil to return vector of indices of coupled voxels.
const SparseMatrix< double > & getStencil () const
Returns entire sparse matrix of mesh. Used by diffusion solver.
unsigned int getStencilRow (unsigned int meshIndex, const double **entry, const unsigned int **colIndex) const
vector< double > innerGetStencilRate (unsigned int row) const
void innerResetStencil ()
virtual func implemented here.
MeshCompt ()
void setStencilSize (unsigned int numRows, unsigned int numCols)
~MeshCompt ()
Public Member Functions inherited from ChemCompt
void buildDefaultMesh (const Eref &e, double volume, unsigned int numEntries)
void buildJunction (ChemCompt *other, vector< VoxelJunction > &ret)
ChemCompt ()
void flipRet (vector< VoxelJunction > &ret) const
Utility function for swapping first and second in VoxelJunctions.
void getChildConcs (const Eref &e, vector< double > &childConcs) const
unsigned int getDimensions () const
double getEntireVolume (const Eref &e) const
bool getIsMembraneBound () const
string getMethod () const
unsigned int getNumEntries () const
vector< double > getOneVoxelMidpoint (unsigned int vox) const
Looks up specified voxel midpoint, from vGetVoxelMidpoint.
double getOneVoxelVolume (const Eref &e, unsigned int voxel) const
vector< unsigned int > getStencilIndex (unsigned int row) const
vector< double > getStencilRate (unsigned int row) const
vector< double > getVoxelMidpoint () const
Returns vector of all voxel midpoints in compartment.
vector< double > getVoxelVolume () const
Returns vector of all voxel volumes in compartment.
void handleNodeInfo (const Eref &e, unsigned int numNodes, unsigned int numThreads)
MeshEntry * lookupEntry (unsigned int index)
void resetStencil ()
unsigned int setChildConcs (const Eref &e, const vector< double > &childConcs, unsigned int start) const
void setEntireVolume (const Eref &e, double volume)
void setIsMembraneBound (bool v)
void setMethod (string method)
void setNumEntries (unsigned int num)
void setOneVoxelVolume (const Eref &e, unsigned int voxel, double volume)
void setVolumeNotRates (double volume)
virtual ~ChemCompt ()
Static Public Member Functions
static const Cinfo * initCinfo ()
Static Public Member Functions inherited from ChemCompt
static double distance (double x, double y, double z)
static const Cinfo * initCinfo ()
static SrcFinfo1< vector< double > > * voxelVolOut ()
Private Attributes
vector< double > area_
Vol.
vector< Id > elecCompt_
Parent voxel index.
vector< double > length_
area
vector< CylBase > pa_
Specified disk of psd.
vector< unsigned int > parent_
Specifies diff distance to PSD.
vector< double > parentDist_
Specifies direction of psd. Length ignored.
vector< CylBase > psd_
double surfaceGranularity_
Ids of elec compts mapped to each voxel.
double thickness_
Thickness of PSD.
vector< double > vs_
Detailed Description
The PsdMesh sets up the diffusion geometries for the PSD. It has to work in two contexts: first, as a PSD sitting on a spine head. Second, as a PSD sitting directly on the dendrite. In either case it is treated as a surface disc, not as a volume. On the dendrite this is a little strange conceptually (flat disc on round cylinder) but will do for now. Later can fine-tune the cap geometry.
In either case, the PsdMesh is filled by a message that contains information about the matching voxel index (either on spineMesh or NeuroMesh), the coordinates, the radial vector, and the diameter. The PsdMesh does not have any internal diffusion, and it expects to pass only N to the parent dendrite or spine.
Definition at line 27 of file PsdMesh.h.
Constructor & Destructor Documentation
PsdMesh() [1/2]
PsdMesh::PsdMesh ()
Definition at line 134 of file PsdMesh.cpp.
    :
        thickness_( 50.0e-9 ),
        psd_( 1 ),
        pa_( 1 ),
        parentDist_( 1, 1e-6 ),
        parent_( 1, 0 ),
        surfaceGranularity_( 0.1 ),
        vs_(1, 5.0e-21 ),
        area_(1, 1.0e-13 ),
        length_(1, 50.0e-9 )
{
    const double defaultLength = 1e-6;
    psd_[0].setDia( defaultLength );
    psd_[0].setLength( thickness_ );
    psd_[0].setNumDivs( 1 );
    psd_[0].setIsCylinder( true );
}
References area_, length_, pa_, parent_, parentDist_, psd_, CylBase::setDia(), CylBase::setIsCylinder(), CylBase::setLength(), CylBase::setNumDivs(), surfaceGranularity_, thickness_, and vs_.
PsdMesh() [2/2]
PsdMesh::PsdMesh (const PsdMesh & other)
Definition at line 153 of file PsdMesh.cpp.
    :
        psd_( other.psd_ ),
        surfaceGranularity_( other.surfaceGranularity_ )
{;}
References psd_, and surfaceGranularity_.
~PsdMesh()
PsdMesh::~PsdMesh ()
Definition at line 159 of file PsdMesh.cpp.
{
    ;
}
Member Function Documentation
buildStencil()
void PsdMesh::buildStencil ()
Definition at line 431 of file PsdMesh.cpp.
{
    setStencilSize( psd_.size(), psd_.size() );
    innerResetStencil();
}
References MeshCompt::innerResetStencil(), psd_, and MeshCompt::setStencilSize().
Referenced by updateCoords().
extendedMeshEntryVolume()
double PsdMesh::extendedMeshEntryVolume (unsigned int fid) const virtual
Vol of all mesh Entries including abutting diff-coupled voxels.
Virtual function to return volume of mesh Entry, including for diffusively coupled voxels from other solvers.
Reimplemented from MeshCompt.
Definition at line 362 of file PsdMesh.cpp.
{
    if ( fid < psd_.size() ) {
        return getMeshEntryVolume( fid );
    } else {
        return MeshCompt::extendedMeshEntryVolume( fid - psd_.size() );
    }
}
References MeshCompt::extendedMeshEntryVolume(), getMeshEntryVolume(), and psd_.
getCoordinates()
vector< double > PsdMesh::getCoordinates (unsigned int fid) const virtual
Virtual function to return coords of mesh Entry.
Virtual function to return coords of mesh Entry. For PsdMesh, coords are x1y1z1 x2y2z2 dia
Implements ChemCompt.
Definition at line 329 of file PsdMesh.cpp.
{
    vector< double > ret;
    ret.push_back( psd_[fid].getX() );
    ret.push_back( psd_[fid].getY() );
    ret.push_back( psd_[fid].getZ() );
    ret.push_back( psd_[fid].getX() - pa_[fid].getX() );
    ret.push_back( psd_[fid].getY() - pa_[fid].getY() );
    ret.push_back( psd_[fid].getZ() - pa_[fid].getZ() );
    ret.push_back( psd_[fid].getDia() );
    return ret;
}
References CylBase::getDia(), CylBase::getX(), CylBase::getY(), CylBase::getZ(), pa_, and psd_.
getDiffusionArea()
vector< double > PsdMesh::getDiffusionArea (unsigned int fid) const virtual
Virtual function to return diffusion X-section area.
Virtual function to return diffusion X-section area for each neighbor.
Implements ChemCompt.
Definition at line 343 of file PsdMesh.cpp.
{
    vector< double > ret;
    assert( fid < psd_.size() );
    ret.push_back( psd_[ fid ].getDiffusionArea( pa_[fid], 0 ) );
    return ret;
}
References CylBase::getDiffusionArea(), pa_, and psd_.
getDiffusionScaling()
vector< double > PsdMesh::getDiffusionScaling (unsigned int fid) const virtual
Virtual function to return scale factor for diffusion. 1 here.
Virtual function to return scale factor for diffusion. I think all dendite tips need to return just one entry of 1.
Implements ChemCompt.
Definition at line 355 of file PsdMesh.cpp.
{
    return vector< double >( 2, 1.0 );
}
getElecComptMap()
vector< Id > PsdMesh::getElecComptMap () const
Definition at line 188 of file PsdMesh.cpp.
{
    return elecCompt_;
}
References elecCompt_.
Referenced by initCinfo().
getEndVoxelInCompt()
vector< unsigned int > PsdMesh::getEndVoxelInCompt () const
Returns index of end voxel mapping to elec compt, just first+1.
Definition at line 201 of file PsdMesh.cpp.
{
    vector< unsigned int > ret( elecCompt_.size() );
    for ( unsigned int i = 0; i < ret.size(); ++i )
        ret[i] = i+1;
    return ret;
}
References elecCompt_.
Referenced by initCinfo().
getMeshDimensions()
unsigned int PsdMesh::getMeshDimensions (unsigned int fid) const virtual
Virtual function to return dimensions of specified entry.
Implements ChemCompt.
Definition at line 301 of file PsdMesh.cpp.
{
    return 2;
}
getMeshEntryVolume()
double PsdMesh::getMeshEntryVolume (unsigned int fid) const virtual
Virtual function to return volume of mesh Entry.
Implements ChemCompt.
Definition at line 307 of file PsdMesh.cpp.
{
    if ( psd_.size() == 0 ) // Default for meshes before init.
        return 1.0;
    assert( fid < psd_.size() );
    return thickness_ * psd_[ fid ].getDiffusionArea( pa_[fid], 0 );
}
References CylBase::getDiffusionArea(), pa_, psd_, and thickness_.
Referenced by extendedMeshEntryVolume(), handlePsdList(), and matchSpineMeshEntries().
getMeshType()
unsigned int PsdMesh::getMeshType (unsigned int fid) const virtual
Virtual function to return MeshType of specified entry.
Implements ChemCompt.
Definition at line 294 of file PsdMesh.cpp.
{
    assert( fid < psd_.size() );
    return DISK;
}
References DISK, and psd_.
getNeuronVoxel()
vector< unsigned int > PsdMesh::getNeuronVoxel () const
Returns index of voxel on NeuroMesh to which this spine is connected. This isn't such a great function, as it only works if the spine is sitting directly on the NeuroMesh. Otherwise it returns the vector of voxels of parent spine heads, which isn't what the name indicates.
Definition at line 182 of file PsdMesh.cpp.
{
    cout << "Warning: PsdMesh::getNeuronVoxel. Currently not working\n";
    return parent_;
}
References parent_.
Referenced by initCinfo().
getParentVoxel()
vector< unsigned int > PsdMesh::getParentVoxel () const virtual
This function returns the diffusively connected parent voxel within the current (psd) mesh. Since each spine is treated as an independed voxel, there is no such voxel, so we return -1U for each psd. Note that there is a separate function that returns the parentVoxel referred to the NeuroMesh that this spine/psd sits on.
Implements MeshCompt.
Definition at line 540 of file PsdMesh.cpp.
{
    vector< unsigned int > ret( parent_.size(), ~0U );
    return ret;
    // return parent_;
}
References parent_.
getStartVoxelInCompt()
vector< unsigned int > PsdMesh::getStartVoxelInCompt () const
Returns index of first voxel mapping to elec compt.
Definition at line 193 of file PsdMesh.cpp.
{
    vector< unsigned int > ret( elecCompt_.size() );
    for ( unsigned int i = 0; i < ret.size(); ++i )
        ret[i] = i;
    return ret;
}
References elecCompt_.
Referenced by initCinfo().
getThickness()
double PsdMesh::getThickness () const
An assumed thickness for PSD. The volume is computed as the PSD area passed in to each PSD, times this value. Defaults to 50 nanometres. For reference, membranes are 5 nm.
Definition at line 167 of file PsdMesh.cpp.
{
    return thickness_;
}
References thickness_.
Referenced by initCinfo().
getVoxelArea()
const vector< double > & PsdMesh::getVoxelArea () const virtual
Implements MeshCompt.
Definition at line 576 of file PsdMesh.cpp.
{
    return area_;
}
References area_.
getVoxelLength()
const vector< double > & PsdMesh::getVoxelLength () const virtual
Implements MeshCompt.
Definition at line 581 of file PsdMesh.cpp.
{
    return length_;
}
References length_.
handlePsdList()
void PsdMesh::handlePsdList (const Eref & e, vector< double > params, vector< Id > elecCompts, vector< unsigned int > parentVoxel)
Definition at line 225 of file PsdMesh.cpp.
{
        double oldVol = getMeshEntryVolume( 0 );
        assert( diskCoords.size() == 8 * parentVoxel.size() );
        psd_.resize( parentVoxel.size() );
        pa_.resize( parentVoxel.size() );
        vs_.resize( parentVoxel.size() );
        area_.resize( parentVoxel.size() );
        length_.resize( parentVoxel.size() );
        elecCompt_ = elecCompt;
        psd_.clear();
        pa_.clear();
        parentDist_.clear();
        parent_.clear();
        vector< double >::const_iterator x = diskCoords.begin();
        for ( unsigned int i = 0; i < parentVoxel.size(); ++i ) {
            double p = *x;
            double q = *(x+1);
            double r = *(x+2);
            psd_.push_back( CylBase( p, q, r, 1, 0, 1 ));
            x += 3;
            pa_.push_back( CylBase( p - *x, q - *(x+1), r - *(x+2), 1, 0, 1 ));
            x += 3;
            psd_.back().setDia( *x++ );
            psd_.back().setIsCylinder( true );
                // This is an entirely nominal
                // length, so that the effective vol != 0.
            psd_.back().setLength( thickness_ );
            parentDist_.push_back( *x++ );
            vs_[i] = psd_.back().volume( psd_.back() );
            area_[i] = psd_.back().getDiffusionArea( psd_.back(), 0 );
            length_[i] = parentDist_.back();
        }
        parent_ = parentVoxel;
        updateCoords();
        Id meshEntry( e.id().value() + 1 );
        vector< unsigned int > localIndices( psd_.size() );
        vector< double > vols( psd_.size() );
        for ( unsigned int i = 0; i < psd_.size(); ++i ) {
            localIndices[i] = i;
            vols[i] = thickness_ * psd_[i].getDiffusionArea( pa_[i], 0 );
        }
        vector< vector< unsigned int > > outgoingEntries;
        vector< vector< unsigned int > > incomingEntries;
        // meshSplit()->send( e, oldVol, vols, localIndices, outgoingEntries, incomingEntries );
        lookupEntry( 0 )->triggerRemesh( meshEntry.eref(),
                        oldVol, 0, localIndices, vols );
}
References area_, CylBase::CylBase(), elecCompt_, Id::eref(), CylBase::getDiffusionArea(), getMeshEntryVolume(), Eref::id(), Id::Id(), length_, ChemCompt::lookupEntry(), pa_, parent_, parentDist_, psd_, CylBase::setDia(), CylBase::setIsCylinder(), CylBase::setLength(), thickness_, MeshEntry::triggerRemesh(), updateCoords(), Id::value(), CylBase::volume(), and vs_.
Referenced by initCinfo().
indexToSpace()
void PsdMesh::indexToSpace (unsigned int index, double & x, double & y, double & z) const virtual
Converts specified index to xyz coords of middle of voxel Values out of range return original xyz
Implements ChemCompt.
Definition at line 462 of file PsdMesh.cpp.
{
    if ( index >= innerGetNumEntries() )
        return;
    x = psd_[index].getX();
    y = psd_[index].getY();
    z = psd_[index].getZ();
}
References CylBase::getX(), CylBase::getY(), CylBase::getZ(), innerGetNumEntries(), and psd_.
initCinfo()
const Cinfo * PsdMesh::initCinfo () static
Definition at line 26 of file PsdMesh.cpp.
{
        // Field Definitions
        static ValueFinfo< PsdMesh, double > thickness(
            "thickness",
            "An assumed thickness for PSD. The volume is computed as the"
            "PSD area passed in to each PSD, times this value."
            "defaults to 50 nanometres. For reference, membranes are 5 nm.",
            &PsdMesh::setThickness,
            &PsdMesh::getThickness
        );
        static ReadOnlyValueFinfo< PsdMesh, vector< unsigned int > >
            neuronVoxel
        (
            "neuronVoxel",
            "Vector of indices of voxels on parent NeuroMesh, from which "
            "the respective spines emerge.",
            &PsdMesh::getNeuronVoxel
        );
        static ReadOnlyValueFinfo< PsdMesh, vector< Id > > elecComptMap(
            "elecComptMap",
            "Vector of Ids of electrical compartments that map to each "
            "voxel. This is necessary because the order of the IDs may "
            "differ from the ordering of the voxels. Note that there "
            "is always just one voxel per PSD. ",
            &PsdMesh::getElecComptMap
        );
        static ReadOnlyValueFinfo< PsdMesh, vector< Id > > elecComptList(
            "elecComptList",
            "Vector of Ids of all electrical compartments in this "
            "PsdMesh. Ordering is as per the tree structure built in "
            "the NeuroMesh, and may differ from Id order. Ordering "
            "matches that used for startVoxelInCompt and endVoxelInCompt",
            &PsdMesh::getElecComptMap
        );
        static ReadOnlyValueFinfo< PsdMesh, vector< unsigned int > > startVoxelInCompt(
            "startVoxelInCompt",
            "Index of first voxel that maps to each electrical "
            "compartment. This is a trivial function in the PsdMesh, as"
            "we have a single voxel per spine. So just a vector of "
            "its own indices.",
            &PsdMesh::getStartVoxelInCompt
        );
        static ReadOnlyValueFinfo< PsdMesh, vector< unsigned int > > endVoxelInCompt(
            "endVoxelInCompt",
            "Index of end voxel that maps to each electrical "
            "compartment. Since there is just one voxel per electrical "
            "compartment in the spine, this is just a vector of index+1",
            &PsdMesh::getEndVoxelInCompt
        );
        // MsgDest Definitions
        static DestFinfo psdList( "psdList",
            "Specifies the geometry of the spine,"
            "and the associated parent voxel"
            "Arguments: "
            "disk params vector with 8 entries per psd, "
            "vector of Ids of electrical compts mapped to voxels, "
            "parent voxel index ",
            new EpFunc3< PsdMesh,
                vector< double >,
                vector< Id >,
                vector< unsigned int > >(
                &PsdMesh::handlePsdList )
        );
        // Field Elements
    static Finfo* psdMeshFinfos[] = {
        &thickness,         // ValueFinfo
        &neuronVoxel,       // ReadOnlyValueFinfo
        &elecComptMap,      // ReadOnlyValueFinfo
        &elecComptList,     // ReadOnlyValueFinfo
        &startVoxelInCompt,     // ReadOnlyValueFinfo
        &endVoxelInCompt,       // ReadOnlyValueFinfo
        &psdList,           // DestFinfo
    };
    static Dinfo< PsdMesh > dinfo;
    static Cinfo psdMeshCinfo (
        "PsdMesh",
        ChemCompt::initCinfo(),
        psdMeshFinfos,
        sizeof( psdMeshFinfos ) / sizeof ( Finfo* ),
        &dinfo
    );
    return &psdMeshCinfo;
}
References Cinfo::Cinfo(), DestFinfo::DestFinfo(), EpFunc3< T, A1, A2, A3 >::EpFunc3(), getElecComptMap(), getEndVoxelInCompt(), getNeuronVoxel(), getStartVoxelInCompt(), getThickness(), handlePsdList(), ChemCompt::initCinfo(), ReadOnlyValueFinfo< T, F >::ReadOnlyValueFinfo(), setThickness(), and ValueFinfo< T, F >::ValueFinfo().
innerBuildDefaultMesh()
void PsdMesh::innerBuildDefaultMesh (const Eref & e, double volume, unsigned int numEntries) virtual
Virtual func to make a mesh with specified Volume and numEntries.
Not permitted
Implements ChemCompt.
Definition at line 422 of file PsdMesh.cpp.
{
    cout << "Warning: PsdMesh::innerBuildDefaultMesh: attempt to build a default psd: not permitted\n";
}
innerGetDimensions()
unsigned int PsdMesh::innerGetDimensions () const virtual
Returns # of dimensions, always 3 here. Inherited pure virt func.
Implements ChemCompt.
Definition at line 219 of file PsdMesh.cpp.
{
    return 2;
}
innerGetNumEntries()
unsigned int PsdMesh::innerGetNumEntries () const virtual
Inherited virtual func. Returns number of MeshEntry in array
Implements ChemCompt.
Definition at line 405 of file PsdMesh.cpp.
{
    return psd_.size();
}
References psd_.
Referenced by indexToSpace().
innerHandleNodeInfo()
void PsdMesh::innerHandleNodeInfo (const Eref & e, unsigned int numNodes, unsigned int numThreads) virtual
Implements ChemCompt.
Definition at line 386 of file PsdMesh.cpp.
{
}
innerHandleRequestMeshStats()
void PsdMesh::innerHandleRequestMeshStats (const Eref & e, const SrcFinfo2< unsigned int, vector< double > > * meshStatsFinfo)
More inherited virtual funcs: request comes in for mesh stats Not clear what this does.
Definition at line 379 of file PsdMesh.cpp.
{
        ;
}
innerSetNumEntries()
void PsdMesh::innerSetNumEntries (unsigned int n) virtual
Inherited virtual func.
Inherited virtual func. Assigns number of MeshEntries. Doesn't do anything, we have to set psd # from geometry.
Implements ChemCompt.
Definition at line 414 of file PsdMesh.cpp.
{
}
matchCubeMeshEntries()
void PsdMesh::matchCubeMeshEntries (const ChemCompt * other, vector< VoxelJunction > & ret) const
Definition at line 518 of file PsdMesh.cpp.
{
    for( unsigned int i = 0; i < psd_.size(); ++i ) {
        const CylBase& cb = psd_[i];
        cb.matchCubeMeshEntries( other, pa_[i],
        i, surfaceGranularity_, ret, false, true );
    }
}
References CylBase::matchCubeMeshEntries(), pa_, psd_, and surfaceGranularity_.
Referenced by matchMeshEntries().
matchMeshEntries()
void PsdMesh::matchMeshEntries (const ChemCompt * other, vector< VoxelJunction > & ret) const virtual
Returns the meshIndices (NOT spatial indices) of all adjacent mesh entry pairs on ether side of the (self, other) junction. meshIndices are the indices that look up entries in the vector of pools. spatialIndices are (iz * ny + iy) * nx + ix, that is, a linear conversion of cartesian spatial indices. So, for two touching cubes, the return vector is the paired meshIndices on either side of the plane of contact. If one mesh has a finer mesh than the other, or if there are more than one contact points from self to other (for example, at a corner), then we just have multiple pairs using the same meshIndex of the repeated voxel.
Implements ChemCompt.
Definition at line 441 of file PsdMesh.cpp.
{
    const SpineMesh* sm = dynamic_cast< const SpineMesh* >( other );
    if ( sm ) {
        matchSpineMeshEntries( other, ret );
        return;
    }
    const CubeMesh* cm = dynamic_cast< const CubeMesh* >( other );
    if ( cm ) {
        matchCubeMeshEntries( other, ret );
        return;
    }
    const NeuroMesh* nm = dynamic_cast< const NeuroMesh* >( other );
    if ( nm ) {
        matchNeuroMeshEntries( other, ret );
        return;
    }
    cout << "Warning: PsdMesh::matchMeshEntries: unknown class\n";
}
References matchCubeMeshEntries(), matchNeuroMeshEntries(), and matchSpineMeshEntries().
matchNeuroMeshEntries()
void PsdMesh::matchNeuroMeshEntries (const ChemCompt * other, vector< VoxelJunction > & ret) const
Definition at line 507 of file PsdMesh.cpp.
{
    const NeuroMesh* nm = dynamic_cast< const NeuroMesh* >( other );
    assert( nm );
    for ( unsigned int i = 0; i < psd_.size(); ++i ) {
        double xda = psd_[i].getDiffusionArea( pa_[i], 0) / parentDist_[i];
        ret.push_back( VoxelJunction( i, parent_[i], xda ) );
    }
}
References CylBase::getDiffusionArea(), pa_, parent_, parentDist_, psd_, and VoxelJunction::VoxelJunction().
Referenced by matchMeshEntries().
matchSpineMeshEntries()
void PsdMesh::matchSpineMeshEntries (const ChemCompt * other, vector< VoxelJunction > & ret) const
Definition at line 491 of file PsdMesh.cpp.
{
    const SpineMesh* sm = dynamic_cast< const SpineMesh* >( other );
    assert( sm );
    for ( unsigned int i = 0; i < psd_.size(); ++i ) {
        double xda = psd_[i].getDiffusionArea( pa_[i], 0 ) / parentDist_[i];
        ret.push_back( VoxelJunction( i, parent_[i], xda ) );
        ret.back().firstVol = getMeshEntryVolume( i );
        ret.back().secondVol = sm->getMeshEntryVolume( parent_[i] );
    }
}
References VoxelJunction::firstVol, CylBase::getDiffusionArea(), getMeshEntryVolume(), SpineMesh::getMeshEntryVolume(), pa_, parent_, parentDist_, psd_, VoxelJunction::secondVol, and VoxelJunction::VoxelJunction().
Referenced by matchMeshEntries(), and SpineMesh::matchMeshEntries().
nearest()
double PsdMesh::nearest (double x, double y, double z, unsigned int & index) const virtual
This works a little different from other subclass versions of the function. It finds the index of the mesh entry whose centre is closest to the specified coords, and returns the distance to the centre. Doesn't worry about whether this distance is inside or outside cell.
Implements ChemCompt.
Definition at line 472 of file PsdMesh.cpp.
{
    double best = 1e12;
    index = 0;
    for( unsigned int i = 0; i < psd_.size(); ++i ) {
        Vec a( psd_[i].getX(), psd_[i].getY(), psd_[i].getZ() );
        Vec b( x, y, z );
        double d = a.distance( b );
        if ( best > d ) {
            best = d;
            index = i;
        }
    }
    if ( best == 1e12 )
        return -1;
    return best;
}
References Vec::distance(), CylBase::getX(), CylBase::getY(), CylBase::getZ(), psd_, and Vec::Vec().
parent()
unsigned int PsdMesh::parent (unsigned int index) const
Return voxel# on parent compartment on spine or dendrite. For now PSD is always on spine, so it just returns the index.
Definition at line 393 of file PsdMesh.cpp.
{
    if ( i < parent_.size() )
        return parent_[i];
    cout << "Error: PsdMesh::parent: Index " << i << " out of range: " <<
                parent_.size() << "\n";
    return 0;
}
References parent_.
setMeshEntryVolume()
void PsdMesh::setMeshEntryVolume (unsigned int fid, double volume) virtual
Virtual function to set volume of mesh Entry.
Virtual function to assign volume of mesh Entry. Thickness not touched.
Reimplemented from ChemCompt.
Definition at line 316 of file PsdMesh.cpp.
{
    if ( psd_.size() == 0 ) // Default for meshes before init.
        return;
    assert( fid < psd_.size() );
    vs_[fid] = volume;
    area_[fid] = volume / thickness_;
    double dia = 2.0 * sqrt( area_[fid] / PI );
    psd_[ fid ].setDia( dia );
}
References area_, PI, psd_, CylBase::setDia(), thickness_, and vs_.
setThickness()
void PsdMesh::setThickness (double v)
Definition at line 171 of file PsdMesh.cpp.
{
    thickness_ = v;
}
References thickness_.
Referenced by initCinfo().
transmitChange()
void PsdMesh::transmitChange (const Eref & e)
updateCoords()
void PsdMesh::updateCoords ()
Recomputes all local coordinate and meshing data following a change in any of the coord parameters
This assumes that lambda is the quantity to preserve, over numEntries. So when the compartment changes volume, numEntries changes too. Assumes that the soma node is at index 0.
Definition at line 214 of file PsdMesh.cpp.
{
    buildStencil();
}
References buildStencil().
Referenced by handlePsdList().
vGetEntireVolume()
double PsdMesh::vGetEntireVolume () const virtual
Inherited virtual func.
Implements ChemCompt.
Definition at line 586 of file PsdMesh.cpp.
{
    double ret = 0.0;
    for ( vector< double >::const_iterator i =
                    vs_.begin(); i != vs_.end(); ++i )
        ret += *i;
    return ret;
}
References vs_.
Referenced by vSetVolumeNotRates().
vGetVoxelMidpoint()
const vector< double > & PsdMesh::vGetVoxelMidpoint () const virtual
Virtual func so that derived classes can return voxel midpoint.
Implements ChemCompt.
Definition at line 559 of file PsdMesh.cpp.
{
    static vector< double > midpoint;
    midpoint.resize( psd_.size() * 3 );
    vector< double >::iterator k = midpoint.begin();
    for ( unsigned int i = 0; i < psd_.size(); ++i ) {
        vector< double > coords =
                psd_[i].getCoordinates( pa_[i], 0 );
        *k = ( coords[0] + coords[3] ) / 2.0;
        *(k + psd_.size() ) = ( coords[1] + coords[4] ) / 2.0;
        *(k + 2 * psd_.size() ) = ( coords[2] + coords[5] ) / 2.0;
        k++;
        // cout << i << " " << coords[0] << " " << coords[3]<< " " << coords[1]<< " " << coords[4]<< " " << coords[2]<< " " << coords[5] << " " << coords[6] << endl;
    }
    return midpoint;
}
References CylBase::getCoordinates(), pa_, and psd_.
vGetVoxelVolume()
const vector< double > & PsdMesh::vGetVoxelVolume () const virtual
Virtual func so that derived classes can pass voxel volume back.
Implements ChemCompt.
Definition at line 547 of file PsdMesh.cpp.
{
    return vs_;
}
References vs_.
vSetVolumeNotRates()
bool PsdMesh::vSetVolumeNotRates (double volume) virtual
Inherited virtual func.
Implements ChemCompt.
Definition at line 595 of file PsdMesh.cpp.
{
    double volscale = volume / vGetEntireVolume();
    double linscale = pow( volscale, 1.0/3.0 );
    assert( vs_.size() == psd_.size() );
    assert( area_.size() == psd_.size() );
    assert( length_.size() == psd_.size() );
    thickness_ *= linscale;
    for ( unsigned int i = 0; i < psd_.size(); ++i ) {
        psd_[i].setLength( psd_[i].getLength() * linscale );
        psd_[i].setDia( psd_[i].getDia() * linscale );
        vs_[i] *= volscale;
        area_[i] *= linscale * linscale;
        length_[i] *= linscale;
    }
    return true;
}
References area_, CylBase::getDia(), CylBase::getLength(), length_, psd_, CylBase::setDia(), CylBase::setLength(), thickness_, vGetEntireVolume(), and vs_.
Member Data Documentation
area_
vector< double > PsdMesh::area_ private
Vol.
Definition at line 192 of file PsdMesh.h.
Referenced by getVoxelArea(), handlePsdList(), PsdMesh(), setMeshEntryVolume(), and vSetVolumeNotRates().
elecCompt_
vector< Id > PsdMesh::elecCompt_ private
Parent voxel index.
Definition at line 182 of file PsdMesh.h.
Referenced by getElecComptMap(), getEndVoxelInCompt(), getStartVoxelInCompt(), and handlePsdList().
length_
vector< double > PsdMesh::length_ private
area
Definition at line 193 of file PsdMesh.h.
Referenced by getVoxelLength(), handlePsdList(), PsdMesh(), and vSetVolumeNotRates().
pa_
vector< CylBase > PsdMesh::pa_ private
Specified disk of psd.
Definition at line 179 of file PsdMesh.h.
Referenced by getCoordinates(), getDiffusionArea(), getMeshEntryVolume(), handlePsdList(), matchCubeMeshEntries(), matchNeuroMeshEntries(), matchSpineMeshEntries(), PsdMesh(), and vGetVoxelMidpoint().
parent_
vector< unsigned int > PsdMesh::parent_ private
Specifies diff distance to PSD.
Definition at line 181 of file PsdMesh.h.
Referenced by getNeuronVoxel(), getParentVoxel(), handlePsdList(), matchNeuroMeshEntries(), matchSpineMeshEntries(), parent(), and PsdMesh().
parentDist_
vector< double > PsdMesh::parentDist_ private
Specifies direction of psd. Length ignored.
Definition at line 180 of file PsdMesh.h.
Referenced by handlePsdList(), matchNeuroMeshEntries(), matchSpineMeshEntries(), and PsdMesh().
psd_
vector< CylBase > PsdMesh::psd_ private
These do the actual work.
Definition at line 178 of file PsdMesh.h.
Referenced by buildStencil(), extendedMeshEntryVolume(), getCoordinates(), getDiffusionArea(), getMeshEntryVolume(), getMeshType(), handlePsdList(), indexToSpace(), innerGetNumEntries(), matchCubeMeshEntries(), matchNeuroMeshEntries(), matchSpineMeshEntries(), nearest(), PsdMesh(), PsdMesh(), setMeshEntryVolume(), vGetVoxelMidpoint(), and vSetVolumeNotRates().
surfaceGranularity_
double PsdMesh::surfaceGranularity_ private
Ids of elec compts mapped to each voxel.
Decides how finely to subdivide diffLength_ or radius or cubic mesh side when computing surfacearea of intersections with CubeMesh. Defaults to 0.1.
Definition at line 189 of file PsdMesh.h.
Referenced by matchCubeMeshEntries(), PsdMesh(), and PsdMesh().
thickness_
double PsdMesh::thickness_ private
Thickness of PSD.
Definition at line 173 of file PsdMesh.h.
Referenced by getMeshEntryVolume(), getThickness(), handlePsdList(), PsdMesh(), setMeshEntryVolume(), setThickness(), and vSetVolumeNotRates().
vs_
vector< double > PsdMesh::vs_ private
Definition at line 191 of file PsdMesh.h.
Referenced by handlePsdList(), PsdMesh(), setMeshEntryVolume(), vGetEntireVolume(), vGetVoxelVolume(), and vSetVolumeNotRates().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/mesh/PsdMesh.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/mesh/PsdMesh.cpp