MOOSE - Multiscale Object Oriented Simulation Environment: IzhikevichNrn Class Reference
IzhikevichNrn Class Reference
#include <IzhikevichNrn.h>
Public Member Functions
double getA () const
bool getAccommodating () const
double getAlpha () const
double getB () const
double getBeta () const
double getC () const
double getD () const
double getGamma () const
double getIm () const
double getInitU () const
double getInitVm () const
double getInject () const
double getRmByTau () const
double getU () const
double getU0 () const
double getVm () const
double getVmax () const
void handleChannel (double Gk, double Ek)
IzhikevichNrn ()
void process (const Eref &eref, ProcPtr proc)
void reinit (const Eref &eref, ProcPtr proc)
void setA (double value)
void setAccommodating (bool value)
void setAlpha (double value)
void setB (double value)
void setBeta (double value)
void setC (double value)
void setD (double value)
void setGamma (double value)
void setInitU (double value)
void setInitVm (double value)
void setInject (double value)
void setRmByTau (double value)
void setU0 (double value)
void setVm (double value)
void setVmax (double value)
~IzhikevichNrn ()
Static Public Member Functions
static const Cinfo * initCinfo ()
Private Attributes
double a_
bool accommodating_
double alpha_
double b_
double beta_
double c_
double d_
double gamma_
double Im_
double initU_
double initVm_
double inject_
double RmByTau_
double savedVm_
double sum_inject_
double u0_
double u_
double Vm_
double Vmax_
Detailed Description
Definition at line 35 of file IzhikevichNrn.h.
Constructor & Destructor Documentation
IzhikevichNrn()
IzhikevichNrn::IzhikevichNrn ()
Definition at line 273 of file IzhikevichNrn.cpp.
                            :
        alpha_(40000.0), // 0.04 physiological unit
        beta_(5000.0), // 5 physiological unit
        gamma_(140.0), // 140 physiological unit
        RmByTau_(1e6), // Assuming Izhikevich was using nA as unit of
        // current, 1e6 Ohm will be the scaling term for SI
        a_(20.0),
        b_(200.0),
        c_(-0.065), // -65 mV
        d_(2.0), // assuming u is in mV/ms
        Vm_(-0.065),
        u_(-13.0),
        Vmax_(0.03), // 30 mV
        initVm_(-0.065),// -65 mV
        initU_(-13.0),
        sum_inject_(0.0),
        Im_(0.0),
        savedVm_(-0.065),
        accommodating_(false),
        u0_(-0.065),
        inject_(0.0)
{
    ;
}
References a_, accommodating_, alpha_, b_, beta_, c_, d_, gamma_, Im_, initU_, initVm_, inject_, RmByTau_, savedVm_, sum_inject_, u0_, u_, Vm_, and Vmax_.
~IzhikevichNrn()
IzhikevichNrn::~IzhikevichNrn ()
Definition at line 298 of file IzhikevichNrn.cpp.
{
    ;
}
Member Function Documentation
getA()
double IzhikevichNrn::getA () const
Definition at line 307 of file IzhikevichNrn.cpp.
{
    return a_;
}
References a_.
Referenced by initCinfo().
getAccommodating()
bool IzhikevichNrn::getAccommodating () const
Definition at line 444 of file IzhikevichNrn.cpp.
{
    return accommodating_;
}
References accommodating_.
Referenced by initCinfo().
getAlpha()
double IzhikevichNrn::getAlpha () const
Definition at line 379 of file IzhikevichNrn.cpp.
{
    return alpha_;
}
References alpha_.
Referenced by initCinfo().
getB()
double IzhikevichNrn::getB () const
Definition at line 317 of file IzhikevichNrn.cpp.
{
    return b_;
}
References b_.
Referenced by initCinfo().
getBeta()
double IzhikevichNrn::getBeta () const
Definition at line 389 of file IzhikevichNrn.cpp.
{
    return beta_;
}
References beta_.
Referenced by initCinfo().
getC()
double IzhikevichNrn::getC () const
Definition at line 326 of file IzhikevichNrn.cpp.
{
    return c_;
}
References c_.
Referenced by initCinfo().
getD()
double IzhikevichNrn::getD () const
Definition at line 336 of file IzhikevichNrn.cpp.
{
    return d_;
}
References d_.
Referenced by initCinfo().
getGamma()
double IzhikevichNrn::getGamma () const
Definition at line 399 of file IzhikevichNrn.cpp.
{
    return gamma_;
}
References gamma_.
Referenced by initCinfo().
getIm()
double IzhikevichNrn::getIm () const
Definition at line 414 of file IzhikevichNrn.cpp.
{
    return Im_;
}
References Im_.
Referenced by initCinfo().
getInitU()
double IzhikevichNrn::getInitU () const
Definition at line 434 of file IzhikevichNrn.cpp.
{
    return initU_;
}
References initU_.
Referenced by initCinfo().
getInitVm()
double IzhikevichNrn::getInitVm () const
Definition at line 424 of file IzhikevichNrn.cpp.
{
    return initVm_;
}
References initVm_.
Referenced by initCinfo().
getInject()
double IzhikevichNrn::getInject () const
Definition at line 409 of file IzhikevichNrn.cpp.
{
    return inject_;
}
References inject_.
Referenced by initCinfo().
getRmByTau()
double IzhikevichNrn::getRmByTau () const
Definition at line 346 of file IzhikevichNrn.cpp.
{
    return RmByTau_;
}
References RmByTau_.
Referenced by initCinfo().
getU()
double IzhikevichNrn::getU () const
Definition at line 354 of file IzhikevichNrn.cpp.
{
    return u_;
}
References u_.
Referenced by initCinfo().
getU0()
double IzhikevichNrn::getU0 () const
Definition at line 454 of file IzhikevichNrn.cpp.
{
    return u0_;
}
References u0_.
Referenced by initCinfo().
getVm()
double IzhikevichNrn::getVm () const
Definition at line 359 of file IzhikevichNrn.cpp.
{
    return savedVm_;
}
References savedVm_.
Referenced by initCinfo().
getVmax()
double IzhikevichNrn::getVmax () const
Definition at line 369 of file IzhikevichNrn.cpp.
{
    return Vmax_;
}
References Vmax_.
Referenced by initCinfo().
handleChannel()
void IzhikevichNrn::handleChannel (double Gk, double Ek)
Definition at line 459 of file IzhikevichNrn.cpp.
{
    sum_inject_ += Gk * (Ek - Vm_);
}
References sum_inject_, and Vm_.
Referenced by initCinfo().
initCinfo()
const Cinfo * IzhikevichNrn::initCinfo () static
Definition at line 49 of file IzhikevichNrn.cpp.
{
    static DestFinfo process(
            "process",
            "Handles process call",
            new ProcOpFunc< IzhikevichNrn >( &IzhikevichNrn::process));
    static DestFinfo reinit(
            "reinit",
            "Handles reinit call",
            new ProcOpFunc<IzhikevichNrn>( &IzhikevichNrn::reinit));
    static Finfo * processShared[] = {
        &process,
        &reinit
    };
    static SharedFinfo proc(
            "proc",
            "Shared message to receive Process message from scheduler",
            processShared, sizeof( processShared ) / sizeof( Finfo* ) );
    // Field definitions
    static ValueFinfo<IzhikevichNrn, double> Vmax(
            "Vmax",
            "Maximum membrane potential. Membrane potential is reset to c whenever"
            " it reaches Vmax. NOTE: Izhikevich model specifies the PEAK voltage,"
            " rather than THRSHOLD voltage. The threshold depends on the previous"
            " history.",
            &IzhikevichNrn::setVmax,
            &IzhikevichNrn::getVmax);
    static ValueFinfo<IzhikevichNrn, double> c(
            "c",
            "Reset potential. Membrane potential is reset to c whenever it reaches"
            " Vmax.",
            &IzhikevichNrn::setC,
            &IzhikevichNrn::getC);
    static ValueFinfo<IzhikevichNrn, double> d(
            "d",
            "Parameter d in Izhikevich model. Unit is V/s.",
            &IzhikevichNrn::setD,
            &IzhikevichNrn::getD);
    static ValueFinfo<IzhikevichNrn, double> a(
            "a",
            "Parameter a in Izhikevich model. Unit is s^{-1}",
            &IzhikevichNrn::setA,
            &IzhikevichNrn::getA);
    static ValueFinfo<IzhikevichNrn, double> b(
            "b",
            "Parameter b in Izhikevich model. Unit is s^{-1}",
            &IzhikevichNrn::setB,
            &IzhikevichNrn::getB);
    static ValueFinfo<IzhikevichNrn, double> Vm(
            "Vm",
            "Membrane potential, equivalent to v in Izhikevich equation.",
            &IzhikevichNrn::setVm,
            &IzhikevichNrn::getVm);
    static ReadOnlyValueFinfo<IzhikevichNrn, double> u(
            "u",
            "Parameter u in Izhikevich equation. Unit is V/s",
            &IzhikevichNrn::getU);
    static ReadOnlyValueFinfo<IzhikevichNrn, double> Im(
            "Im",
            "Total current going through the membrane. Unit is A.",
            &IzhikevichNrn::getIm);
    static ValueFinfo<IzhikevichNrn, double> initVm(
            "initVm",
            "Initial membrane potential. Unit is V.",
            &IzhikevichNrn::setInitVm,
            &IzhikevichNrn::getInitVm);
    static ValueFinfo<IzhikevichNrn, double> inject(
            "inject",
            "External current injection into the neuron",
            &IzhikevichNrn::setInject,
            &IzhikevichNrn::getInject);
    static ValueFinfo<IzhikevichNrn, double> initU(
            "initU",
            "Initial value of u.",
            &IzhikevichNrn::setInitU,
            &IzhikevichNrn::getInitU);
    static ValueFinfo<IzhikevichNrn, double> alpha(
            "alpha",
            "Coefficient of v^2 in Izhikevich equation. Defaults to 0.04 in "
            "physiological unit. In SI it should be 40000.0. Unit is V^-1 s^{-1}",
            &IzhikevichNrn::setAlpha,
            &IzhikevichNrn::getAlpha);
    static ValueFinfo<IzhikevichNrn, double> beta(
            "beta",
            "Coefficient of v in Izhikevich model. Defaults to 5 in physiological"
            " unit, 5000.0 for SI units. Unit is s^{-1}",
            &IzhikevichNrn::setBeta,
            &IzhikevichNrn::getBeta);
    static ValueFinfo<IzhikevichNrn, double> gamma(
            "gamma",
            "Constant term in Izhikevich model. Defaults to 140 in both"
            " physiological and SI units. unit is V/s.",
            &IzhikevichNrn::setGamma,
            &IzhikevichNrn::getGamma);
    static ValueFinfo<IzhikevichNrn, double> RmByTau(
            "RmByTau",
            "Hidden coefficient of input current term (I) in Izhikevich model. Defaults to 1e9 Ohm/s.",
            &IzhikevichNrn::setRmByTau,
            &IzhikevichNrn::getRmByTau);
    static ValueFinfo<IzhikevichNrn, bool> accommodating(
            "accommodating",
            "True if this neuron is an accommodating one. The equation for recovery"
            " variable u is special in this case.",
            &IzhikevichNrn::setAccommodating,
            &IzhikevichNrn::getAccommodating);
    static ValueFinfo<IzhikevichNrn, double> u0(
            "u0",
            "This is used for accommodating neurons where recovery variables u is"
            " computed as: u += tau*a*(b*(Vm-u0))",
            &IzhikevichNrn::setU0,
            &IzhikevichNrn::getU0);
    // MsgDest definition
    static DestFinfo injectMsg(
            "injectMsg",
            "Injection current into the neuron.",
            new OpFunc1<IzhikevichNrn, double>( &IzhikevichNrn::setInject));
    static DestFinfo cDest(
            "cDest",
            "Destination message to modify parameter c at runtime.",
            new OpFunc1<IzhikevichNrn, double>(&IzhikevichNrn::setC));
    static DestFinfo dDest(
            "dDest",
            "Destination message to modify parameter d at runtime.",
            new OpFunc1<IzhikevichNrn, double>(&IzhikevichNrn::setD));
    static DestFinfo aDest(
            "aDest",
            "Destination message modify parameter a at runtime.",
            new OpFunc1<IzhikevichNrn, double>(&IzhikevichNrn::setA));
    static DestFinfo bDest(
            "bDest",
            "Destination message to modify parameter b at runtime",
            new OpFunc1<IzhikevichNrn, double>(&IzhikevichNrn::setB));
    static DestFinfo handleChannel("handleChannel",
                                   "Handles conductance and reversal potential arguments from Channel",
                                   new OpFunc2<IzhikevichNrn, double, double >(&IzhikevichNrn::handleChannel));
    static Finfo * channelShared[] = {
        &handleChannel,
        VmOut()
    };
    static SharedFinfo channel("channel",
            "This is a shared message from a IzhikevichNrn to channels."
            "The first entry is a MsgDest for the info coming from "
            "the channel. It expects Gk and Ek from the channel "
            "as args. The second entry is a MsgSrc sending Vm ",
                               channelShared, sizeof( channelShared ) / sizeof( Finfo* )
    );
    static Finfo* IzhikevichNrnFinfos[] = {
        &proc,
        &Vmax,
        &c,
        &d,
        &a,
        &b,
        &u,
        &Vm,
        &Im,
        &inject,
        &RmByTau,
        &accommodating,
        &u0,
        &initVm,
        &initU,
        &alpha,
        &beta,
        &gamma,
        &injectMsg,
        &cDest,
        &dDest,
        &bDest,
        &aDest,
        VmOut(),
        spikeOut(),
        &channel,
    };
    static string doc[] = {
        "Name", "IzhikevichNrn",
        "Author", "Subhasis Ray",
        "Description", "Izhikevich model of spiking neuron "
        "(Izhikevich,EM. 2003. Simple model of spiking neurons. Neural"
        " Networks, IEEE Transactions on 14(6). pp 1569-1572).\n"
        " This class obeys the equations (in physiological units):\n"
        "  dVm/dt = 0.04 * Vm^2 + 5 * Vm + 140 - u + inject\n"
        "  du/dt = a * (b * Vm - u)\n"
        " if Vm >= Vmax then Vm = c and u = u + d\n"
        " Vmax = 30 mV in the paper."
    };
    static Dinfo< IzhikevichNrn > dinfo;
    static Cinfo IzhikevichNrnCinfo(
        "IzhikevichNrn",
        Neutral::initCinfo(),
        IzhikevichNrnFinfos,
        sizeof( IzhikevichNrnFinfos ) / sizeof( Finfo* ),
        &dinfo,
        doc,
        sizeof(doc)/sizeof(string));
    return &IzhikevichNrnCinfo;
}
References Cinfo::Cinfo(), DestFinfo::DestFinfo(), getA(), getAccommodating(), getAlpha(), getB(), getBeta(), getC(), getD(), getGamma(), getIm(), getInitU(), getInitVm(), getInject(), getRmByTau(), getU(), getU0(), getVm(), getVmax(), handleChannel(), Neutral::initCinfo(), OpFunc1< T, A >::OpFunc1(), OpFunc2< T, A1, A2 >::OpFunc2(), process(), ProcOpFunc< T >::ProcOpFunc(), ReadOnlyValueFinfo< T, F >::ReadOnlyValueFinfo(), reinit(), setA(), setAccommodating(), setAlpha(), setB(), setBeta(), setC(), setD(), setGamma(), setInitU(), setInitVm(), setInject(), setRmByTau(), setU0(), setVm(), setVmax(), SharedFinfo::SharedFinfo(), spikeOut(), ValueFinfo< T, F >::ValueFinfo(), and VmOut().
process()
void IzhikevichNrn::process (const Eref & eref, ProcPtr proc)
Definition at line 464 of file IzhikevichNrn.cpp.
{
    Vm_ += proc->dt * ((alpha_ * Vm_ + beta_) * Vm_
                       + gamma_ - u_ + RmByTau_ * sum_inject_);
    if (accommodating_){
        u_ += proc->dt * a_ * b_ * (Vm_ - u0_);
    } else {
        u_ += proc->dt * a_ * (b_ * Vm_ - u_);
    }
    Im_ = sum_inject_;
    sum_inject_ = inject_;
    // This check is to ensure that checking Vm field will always
    // return Vmax when Vm actually crosses Vmax.
    if (Vm_ >= Vmax_){
        Vm_ = c_;
        u_ += d_;
        savedVm_ = Vmax_;
        VmOut()->send(eref, Vmax_);
        spikeOut()->send(eref, proc->currTime);
    } else {
        savedVm_ = Vm_;
        VmOut()->send(eref, Vm_);
    }
}
References a_, accommodating_, alpha_, b_, beta_, c_, ProcInfo::currTime, d_, ProcInfo::dt, gamma_, Im_, inject_, RmByTau_, savedVm_, SrcFinfo1< T >::send(), spikeOut(), sum_inject_, u0_, u_, Vm_, Vmax_, and VmOut().
Referenced by initCinfo().
reinit()
void IzhikevichNrn::reinit (const Eref & eref, ProcPtr proc)
Definition at line 489 of file IzhikevichNrn.cpp.
{
    sum_inject_ = 0.0;
    Vm_ = initVm_;
    u_ = initU_;
    Im_ = 0.0;
    savedVm_ = Vm_;
    VmOut()->send(eref, Vm_);
}
References Im_, initU_, initVm_, savedVm_, SrcFinfo1< T >::send(), sum_inject_, u_, Vm_, and VmOut().
Referenced by initCinfo().
setA()
void IzhikevichNrn::setA (double value)
Definition at line 302 of file IzhikevichNrn.cpp.
{
    a_ = value;
}
References a_.
Referenced by initCinfo().
setAccommodating()
void IzhikevichNrn::setAccommodating (bool value)
Definition at line 439 of file IzhikevichNrn.cpp.
{
    accommodating_ = value;
}
References accommodating_.
Referenced by initCinfo().
setAlpha()
void IzhikevichNrn::setAlpha (double value)
Definition at line 374 of file IzhikevichNrn.cpp.
{
    alpha_ = value;
}
References alpha_.
Referenced by initCinfo().
setB()
void IzhikevichNrn::setB (double value)
Definition at line 312 of file IzhikevichNrn.cpp.
{
    b_ = value;
}
References b_.
Referenced by initCinfo().
setBeta()
void IzhikevichNrn::setBeta (double value)
Definition at line 384 of file IzhikevichNrn.cpp.
{
    beta_ = value;
}
References beta_.
Referenced by initCinfo().
setC()
void IzhikevichNrn::setC (double value)
Definition at line 321 of file IzhikevichNrn.cpp.
{
    c_ = value;
}
References c_.
Referenced by initCinfo().
setD()
void IzhikevichNrn::setD (double value)
Definition at line 331 of file IzhikevichNrn.cpp.
{
    d_ = value;
}
References d_.
Referenced by initCinfo().
setGamma()
void IzhikevichNrn::setGamma (double value)
Definition at line 394 of file IzhikevichNrn.cpp.
{
    gamma_ = value;
}
References gamma_.
Referenced by initCinfo().
setInitU()
void IzhikevichNrn::setInitU (double value)
Definition at line 429 of file IzhikevichNrn.cpp.
{
    initU_ = value;
}
References initU_.
Referenced by initCinfo().
setInitVm()
void IzhikevichNrn::setInitVm (double value)
Definition at line 419 of file IzhikevichNrn.cpp.
{
    initVm_ = value;
}
References initVm_.
Referenced by initCinfo().
setInject()
void IzhikevichNrn::setInject (double value)
Definition at line 404 of file IzhikevichNrn.cpp.
{
    inject_ = value;
}
References inject_.
Referenced by initCinfo().
setRmByTau()
void IzhikevichNrn::setRmByTau (double value)
Definition at line 341 of file IzhikevichNrn.cpp.
{
    RmByTau_ = value;
}
References RmByTau_.
Referenced by initCinfo().
setU0()
void IzhikevichNrn::setU0 (double value)
Definition at line 449 of file IzhikevichNrn.cpp.
{
    u0_ = value;
}
References u0_.
Referenced by initCinfo().
setVm()
void IzhikevichNrn::setVm (double value)
Definition at line 350 of file IzhikevichNrn.cpp.
{
    Vm_ = value;
}
References Vm_.
Referenced by initCinfo().
setVmax()
void IzhikevichNrn::setVmax (double value)
Definition at line 364 of file IzhikevichNrn.cpp.
{
    Vmax_ = value;
}
References Vmax_.
Referenced by initCinfo().
Member Data Documentation
a_
double IzhikevichNrn::a_ private
Definition at line 101 of file IzhikevichNrn.h.
Referenced by getA(), IzhikevichNrn(), process(), and setA().
accommodating_
bool IzhikevichNrn::accommodating_ private
Definition at line 113 of file IzhikevichNrn.h.
Referenced by getAccommodating(), IzhikevichNrn(), process(), and setAccommodating().
alpha_
double IzhikevichNrn::alpha_ private
Definition at line 97 of file IzhikevichNrn.h.
Referenced by getAlpha(), IzhikevichNrn(), process(), and setAlpha().
b_
double IzhikevichNrn::b_ private
Definition at line 102 of file IzhikevichNrn.h.
Referenced by getB(), IzhikevichNrn(), process(), and setB().
beta_
double IzhikevichNrn::beta_ private
Definition at line 98 of file IzhikevichNrn.h.
Referenced by getBeta(), IzhikevichNrn(), process(), and setBeta().
c_
double IzhikevichNrn::c_ private
Definition at line 103 of file IzhikevichNrn.h.
Referenced by getC(), IzhikevichNrn(), process(), and setC().
d_
double IzhikevichNrn::d_ private
Definition at line 104 of file IzhikevichNrn.h.
Referenced by getD(), IzhikevichNrn(), process(), and setD().
gamma_
double IzhikevichNrn::gamma_ private
Definition at line 99 of file IzhikevichNrn.h.
Referenced by getGamma(), IzhikevichNrn(), process(), and setGamma().
Im_
double IzhikevichNrn::Im_ private
Definition at line 111 of file IzhikevichNrn.h.
Referenced by getIm(), IzhikevichNrn(), process(), and reinit().
initU_
double IzhikevichNrn::initU_ private
Definition at line 109 of file IzhikevichNrn.h.
Referenced by getInitU(), IzhikevichNrn(), reinit(), and setInitU().
initVm_
double IzhikevichNrn::initVm_ private
Definition at line 108 of file IzhikevichNrn.h.
Referenced by getInitVm(), IzhikevichNrn(), reinit(), and setInitVm().
inject_
double IzhikevichNrn::inject_ private
Definition at line 115 of file IzhikevichNrn.h.
Referenced by getInject(), IzhikevichNrn(), process(), and setInject().
RmByTau_
double IzhikevichNrn::RmByTau_ private
Definition at line 100 of file IzhikevichNrn.h.
Referenced by getRmByTau(), IzhikevichNrn(), process(), and setRmByTau().
savedVm_
double IzhikevichNrn::savedVm_ private
Definition at line 112 of file IzhikevichNrn.h.
Referenced by getVm(), IzhikevichNrn(), process(), and reinit().
sum_inject_
double IzhikevichNrn::sum_inject_ private
Definition at line 110 of file IzhikevichNrn.h.
Referenced by handleChannel(), IzhikevichNrn(), process(), and reinit().
u0_
double IzhikevichNrn::u0_ private
Definition at line 114 of file IzhikevichNrn.h.
Referenced by getU0(), IzhikevichNrn(), process(), and setU0().
u_
double IzhikevichNrn::u_ private
Definition at line 106 of file IzhikevichNrn.h.
Referenced by getU(), IzhikevichNrn(), process(), and reinit().
Vm_
double IzhikevichNrn::Vm_ private
Definition at line 105 of file IzhikevichNrn.h.
Referenced by handleChannel(), IzhikevichNrn(), process(), reinit(), and setVm().
Vmax_
double IzhikevichNrn::Vmax_ private
Definition at line 107 of file IzhikevichNrn.h.
Referenced by getVmax(), IzhikevichNrn(), process(), and setVmax().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/biophysics/IzhikevichNrn.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/biophysics/IzhikevichNrn.cpp