MOOSE - Multiscale Object Oriented Simulation Environment: ChanBase Class Reference
ChanBase Class Reference abstract
#include <ChanBase.h>
Public Member Functions
ChanBase ()
double getEk (const Eref &e) const
double getGbar (const Eref &e) const
double getGk (const Eref &e) const
double getIk (const Eref &e) const
double getModulation (const Eref &e) const
void handleVm (double Vm)
void process (const Eref &e, const ProcPtr info)
void reinit (const Eref &e, const ProcPtr info)
void setEk (const Eref &e, double Ek)
void setGbar (const Eref &e, double Gbar)
void setGk (const Eref &e, double Gk)
void setIk (const Eref &e, double Ic)
void setModulation (const Eref &e, double modulation)
virtual double vGetEk (const Eref &e) const =0
virtual double vGetGbar (const Eref &e) const =0
virtual double vGetGk (const Eref &e) const =0
virtual double vGetIk (const Eref &e) const =0
virtual double vGetModulation (const Eref &e) const =0
virtual void vHandleVm (double Vm)=0
virtual void vProcess (const Eref &e, const ProcPtr info)=0
virtual void vReinit (const Eref &e, const ProcPtr info)=0
virtual void vSetEk (const Eref &e, double Ek)=0
virtual void vSetGbar (const Eref &e, double Gbar)=0
virtual void vSetGk (const Eref &e, double Gk)=0
virtual void vSetIk (const Eref &e, double Ik)=0
virtual void vSetModulation (const Eref &e, double modulation)=0
virtual ~ChanBase ()=0
Static Public Member Functions
static SrcFinfo2< double, double > * channelOut ()
static SrcFinfo1< double > * IkOut ()
static const Cinfo * initCinfo ()
Specify the Class Info static variable for initialization.
static SrcFinfo1< double > * permeability ()
Detailed Description
The ChanBase is the base class for all ion channel classes in MOOSE. It knows how to communicate with the parent compartment, not much else.
Definition at line 21 of file ChanBase.h.
Constructor & Destructor Documentation
ChanBase()
ChanBase::ChanBase ()
Definition at line 175 of file ChanBase.cpp.
{ ; }
~ChanBase()
ChanBase::~ChanBase () pure virtual
Definition at line 178 of file ChanBase.cpp.
{;}
Member Function Documentation
channelOut()
SrcFinfo2< double, double > * ChanBase::channelOut () static
Definition at line 21 of file ChanBase.cpp.
{
    static SrcFinfo2< double, double > channelOut( "channelOut",
        "Sends channel variables Gk and Ek to compartment" );
    return &channelOut;
}
References SrcFinfo2< T1, T2 >::SrcFinfo2().
Referenced by initCinfo(), ChanCommon::sendProcessMsgs(), and ChanCommon::sendReinitMsgs().
getEk()
double ChanBase::getEk (const Eref & e) const
Definition at line 211 of file ChanBase.cpp.
{
    return vGetEk( e );
}
References vGetEk().
Referenced by initCinfo().
getGbar()
double ChanBase::getGbar (const Eref & e) const
Definition at line 191 of file ChanBase.cpp.
{
    return vGetGbar( e );
}
References vGetGbar().
Referenced by initCinfo(), NMDAChan::initCinfo(), HHChannel2D::vProcess(), HHChannelF2D::vProcess(), HHChannel2D::vReinit(), and HHChannelF2D::vReinit().
getGk()
double ChanBase::getGk (const Eref & e) const
Definition at line 220 of file ChanBase.cpp.
{
    return vGetGk( e );
}
References vGetGk().
Referenced by initCinfo().
getIk()
double ChanBase::getIk (const Eref & e) const
Definition at line 229 of file ChanBase.cpp.
{
    return vGetIk( e );
}
References vGetIk().
Referenced by initCinfo().
getModulation()
double ChanBase::getModulation (const Eref & e) const
Definition at line 202 of file ChanBase.cpp.
{
    return vGetModulation( e );
}
References vGetModulation().
Referenced by initCinfo().
handleVm()
void ChanBase::handleVm (double Vm)
Assign the local Vm_ to the incoming Vm from the compartment
Definition at line 238 of file ChanBase.cpp.
{
    vHandleVm( Vm );
}
References vHandleVm().
Referenced by initCinfo().
IkOut()
SrcFinfo1< double > * ChanBase::IkOut () static
Definition at line 28 of file ChanBase.cpp.
{
    static SrcFinfo1< double > IkOut( "IkOut",
        "Channel current. This message typically goes to concen"
        "objects that keep track of ion concentration." );
    return &IkOut;
}
References SrcFinfo1< T >::SrcFinfo1().
Referenced by initCinfo(), ChanCommon::sendProcessMsgs(), ChanCommon::sendReinitMsgs(), and HSolveActive::sendValues().
initCinfo()
const Cinfo * ChanBase::initCinfo () static
Specify the Class Info static variable for initialization.
ChannelOut SrcFinfo defined above.
Permability SrcFinfo defined above.
Definition at line 36 of file ChanBase.cpp.
{
    // Shared messages
    static DestFinfo process( "process",
        "Handles process call",
        new ProcOpFunc< ChanBase >( &ChanBase::process ) );
    static DestFinfo reinit( "reinit",
        "Handles reinit call",
        new ProcOpFunc< ChanBase >( &ChanBase::reinit ) );
    static Finfo* processShared[] =
    {
        &process, &reinit
    };
    static SharedFinfo proc( "proc",
        "Shared message to receive Process message from scheduler",
        processShared, sizeof( processShared ) / sizeof( Finfo* ) );
    static DestFinfo Vm( "Vm",
        "Handles Vm message coming in from compartment",
        new OpFunc1< ChanBase, double >( &ChanBase::handleVm ) );
    static Finfo* channelShared[] =
    {
        channelOut(), &Vm
    };
    static SharedFinfo channel( "channel",
        "This is a shared message to couple channel to compartment. "
        "The first entry is a MsgSrc to send Gk and Ek to the compartment "
        "The second entry is a MsgDest for Vm from the compartment.",
        channelShared, sizeof( channelShared ) / sizeof( Finfo* )
    );
    // Here we reuse the Vm DestFinfo declared above.
    static Finfo* ghkShared[] =
    {
        &Vm, permeability()
    };
    static SharedFinfo ghk( "ghk",
        "Message to Goldman-Hodgkin-Katz object",
        ghkShared, sizeof( ghkShared ) / sizeof( Finfo* ) );
// Field definitions
        static ElementValueFinfo< ChanBase, double > Gbar( "Gbar",
            "Maximal channel conductance",
            &ChanBase::setGbar,
            &ChanBase::getGbar
        );
        static ElementValueFinfo< ChanBase, double > modulation( "modulation",
            "Modulation, i.e, scale factor for channel conductance."
            "Note that this is a regular parameter, it is not "
            "recomputed each timestep. Thus one can use a slow update, "
            "say, from a molecule pool, to send a message to set "
            "the modulation, and it will stay at the set value even if "
            "the channel runs many timesteps before the next assignment. "
            "This differs from the GENESIS semantics of a similar message,"
            "which required update each timestep. ",
            &ChanBase::setModulation,
            &ChanBase::getModulation
        );
        static ElementValueFinfo< ChanBase, double > Ek( "Ek",
            "Reversal potential of channel",
            &ChanBase::setEk,
            &ChanBase::getEk
        );
        static ElementValueFinfo< ChanBase, double > Gk( "Gk",
            "Channel conductance variable",
            &ChanBase::setGk,
            &ChanBase::getGk
        );
        static ReadOnlyElementValueFinfo< ChanBase, double > Ik( "Ik",
            "Channel current variable",
            &ChanBase::getIk
        );
// MsgSrc definitions
    // IkOut SrcFinfo defined above.
// MsgDest definitions
    static Finfo* ChanBaseFinfos[] =
    {
        &channel,           // Shared
        &ghk,               // Shared
        &Gbar,              // Value
        &modulation,        // Value
        &Ek,                // Value
        &Gk,                // Value
        &Ik,                // ReadOnlyValue
        IkOut(),            // Src
        &proc,              // Shared
    };
    static string doc[] =
    {
        "Name", "ChanBase",
        "Author", "Upinder S. Bhalla, 2007-2014, NCBS",
        "Description", "ChanBase: Base class for assorted ion channels."
        "Presents a common interface for all of them. ",
    };
        static  ZeroSizeDinfo< int > dinfo;
    static Cinfo ChanBaseCinfo(
        "ChanBase",
        Neutral::initCinfo(),
        ChanBaseFinfos,
        sizeof( ChanBaseFinfos )/sizeof(Finfo *),
                &dinfo,
                doc,
                sizeof(doc)/sizeof(string)
    );
    return &ChanBaseCinfo;
}
References channelOut(), Cinfo::Cinfo(), DestFinfo::DestFinfo(), ElementValueFinfo< T, F >::ElementValueFinfo(), getEk(), getGbar(), getGk(), getIk(), getModulation(), handleVm(), IkOut(), Neutral::initCinfo(), OpFunc1< T, A >::OpFunc1(), permeability(), process(), ProcOpFunc< T >::ProcOpFunc(), ReadOnlyElementValueFinfo< T, F >::ReadOnlyElementValueFinfo(), reinit(), setEk(), setGbar(), setGk(), setModulation(), and SharedFinfo::SharedFinfo().
Referenced by HHChannelBase::initCinfo(), HHChannelF2D::initCinfo(), Leakage::initCinfo(), MarkovChannel::initCinfo(), MgBlock::initCinfo(), and SynChan::initCinfo().
permeability()
SrcFinfo1< double > * ChanBase::permeability () static
Definition at line 14 of file ChanBase.cpp.
{
    static SrcFinfo1< double > permeability( "permeabilityOut",
        "Conductance term going out to GHK object" );
    return &permeability;
}
References SrcFinfo1< T >::SrcFinfo1().
Referenced by initCinfo(), ChanCommon::sendProcessMsgs(), and ChanCommon::sendReinitMsgs().
process()
void ChanBase::process (const Eref & e, const ProcPtr info)
Takes over the Process and reinit functions of all derived classes.
Definition at line 248 of file ChanBase.cpp.
{
    vProcess( e, info );
}
References vProcess().
Referenced by initCinfo().
reinit()
void ChanBase::reinit (const Eref & e, const ProcPtr info)
Definition at line 254 of file ChanBase.cpp.
{
    vReinit( e, info );
}
References vReinit().
Referenced by initCinfo().
setEk()
void ChanBase::setEk (const Eref & e, double Ek)
Definition at line 207 of file ChanBase.cpp.
{
    vSetEk( e, Ek );
}
References vSetEk().
Referenced by initCinfo(), and MgBlock::origChannel().
setGbar()
void ChanBase::setGbar (const Eref & e, double Gbar)
Definition at line 185 of file ChanBase.cpp.
{
    // Call virtual functions of derived classes for this operation.
    vSetGbar( e, Gbar );
}
References vSetGbar().
Referenced by initCinfo(), and NMDAChan::initCinfo().
setGk()
void ChanBase::setGk (const Eref & e, double Gk)
Definition at line 216 of file ChanBase.cpp.
{
    vSetGk( e, Gk );
}
References vSetGk().
Referenced by initCinfo(), MarkovChannel::vProcess(), MgBlock::vProcess(), NMDAChan::vProcess(), SynChan::vProcess(), HHChannel2D::vProcess(), HHChannelF2D::vProcess(), SynChan::vReinit(), HHChannel2D::vReinit(), and HHChannelF2D::vReinit().
setIk()
void ChanBase::setIk (const Eref & e, double Ic)
Definition at line 225 of file ChanBase.cpp.
{
    vSetIk( e, Ik );
}
References vSetIk().
Referenced by SynChan::vReinit().
setModulation()
void ChanBase::setModulation (const Eref & e, double modulation)
Definition at line 196 of file ChanBase.cpp.
{
    // Call virtual functions of derived classes for this operation.
    vSetModulation( e, modulation );
}
References vSetModulation().
Referenced by initCinfo().
vGetEk()
virtual double ChanBase::vGetEk (const Eref & e) const pure virtual
Implemented in ChanCommon, and ZombieHHChannel.
Referenced by getEk().
vGetGbar()
virtual double ChanBase::vGetGbar (const Eref & e) const pure virtual
Implemented in ChanCommon, and ZombieHHChannel.
Referenced by getGbar().
vGetGk()
virtual double ChanBase::vGetGk (const Eref & e) const pure virtual
Implemented in ChanCommon, and ZombieHHChannel.
Referenced by getGk().
vGetIk()
virtual double ChanBase::vGetIk (const Eref & e) const pure virtual
Implemented in ChanCommon, and ZombieHHChannel.
Referenced by getIk().
vGetModulation()
virtual double ChanBase::vGetModulation (const Eref & e) const pure virtual
Implemented in ChanCommon.
Referenced by getModulation().
vHandleVm()
virtual void ChanBase::vHandleVm (double Vm) pure virtual
Implemented in ChanCommon, and ZombieHHChannel.
Referenced by handleVm().
vProcess()
virtual void ChanBase::vProcess (const Eref & e, const ProcPtr info) pure virtual
Implemented in MarkovChannel, Leakage, MgBlock, NMDAChan, SynChan, HHChannel, HHChannel2D, HHChannelF, HHChannelF2D, and ZombieHHChannel.
Referenced by process().
vReinit()
virtual void ChanBase::vReinit (const Eref & e, const ProcPtr info) pure virtual
Implemented in MarkovChannel, Leakage, MgBlock, NMDAChan, SynChan, HHChannel, HHChannel2D, HHChannelF, HHChannelF2D, and ZombieHHChannel.
Referenced by reinit().
vSetEk()
virtual void ChanBase::vSetEk (const Eref & e, double Ek) pure virtual
Implemented in ChanCommon, and ZombieHHChannel.
Referenced by setEk().
vSetGbar()
virtual void ChanBase::vSetGbar (const Eref & e, double Gbar) pure virtual
Implemented in Leakage, SynChan, ChanCommon, and ZombieHHChannel.
Referenced by setGbar().
vSetGk()
virtual void ChanBase::vSetGk (const Eref & e, double Gk) pure virtual
Implemented in ChanCommon, and ZombieHHChannel.
Referenced by setGk().
vSetIk()
virtual void ChanBase::vSetIk (const Eref & e, double Ik) pure virtual
Implemented in ChanCommon, and ZombieHHChannel.
Referenced by setIk().
vSetModulation()
virtual void ChanBase::vSetModulation (const Eref & e, double modulation) pure virtual
Implemented in ChanCommon, and ZombieHHChannel.
Referenced by setModulation().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/biophysics/ChanBase.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/biophysics/ChanBase.cpp