MOOSE - Multiscale Object Oriented Simulation Environment: LocalDataElement Class Reference
LocalDataElement Class Reference
#include <LocalDataElement.h>
Public Member Functions
Element * copyElement (Id newParent, Id newId, unsigned int n, bool toGlobal) const
unsigned int getNode (unsigned int dataId) const
Inherited virtual. Returns node location of specified object.
unsigned int getNumOnNode (unsigned int node) const
Inherited virtual.
bool isGlobal () const
Inherited virtual. Reports if this is Global, which it isn't.
LocalDataElement (Id id, const Cinfo *c, const string &name, unsigned int numData=1)
LocalDataElement (Id id, const Element *orig, unsigned int n)
unsigned int localDataStart () const
Inherited virtual. Returns index of first entry on this node.
unsigned int numData () const
Inherited virtual. Returns number of data entries over all nodes.
unsigned int rawIndex (unsigned int dataId) const
Converts dataId to index on current node.
void resize (unsigned int newNumData)
unsigned int setDataSize (unsigned int numData)
unsigned int startDataIndex (unsigned int node) const
Inherited virtual. Returns start DataIndex on specified node.
~LocalDataElement ()
Public Member Functions inherited from DataElement
char * data (unsigned int rawIndex, unsigned int fieldIndex=0) const
DataElement (Id id, const Cinfo *c, const string &name, unsigned int numData=1)
DataElement (Id id, const Element *orig, unsigned int n, unsigned int startEntry)
bool hasFields () const
Do not define getNode() or rawIndex() funcs, those are derived.
unsigned int numField (unsigned int rawIndex) const
Define only in derived classes: getNode(unsigned int dataIndex) const;.
unsigned int numLocalData () const
Defined only in derived classes: unsigned int numData() const;.
void resizeField (unsigned int rawIndex, unsigned int newNumField)
unsigned int totNumLocalField () const
void zombieSwap (const Cinfo *newCinfo)
Virtual func.
~DataElement ()
Public Member Functions inherited from Element
void addMsg (ObjId mid)
void addMsgAndFunc (ObjId mid, FuncId fid, BindIndex bindIndex)
const Cinfo * cinfo () const
void clearAllMsgs ()
Used upon ending of MOOSE session, to rapidly clear out messages.
void clearBinding (BindIndex b)
void digestMessages ()
void dropAllMsgsFromSrc (Id src)
void dropMsg (ObjId mid)
Element (Id id, const Cinfo *c, const string &name)
unsigned int findBinding (MsgFuncBinding b) const
ObjId findCaller (FuncId fid) const
unsigned int getFieldsOfOutgoingMsg (ObjId mid, vector< pair< BindIndex, FuncId > > &ret) const
unsigned int getInputMsgs (vector< ObjId > &caller, FuncId fid) const
unsigned int getInputsWithTgtIndex (vector< pair< Id, unsigned int > > &ret, const DestFinfo *finfo) const
const vector< MsgFuncBinding > * getMsgAndFunc (BindIndex b) const
unsigned int getMsgSourceAndSender (FuncId fid, vector< ObjId > &src, vector< string > &sender) const
unsigned int getMsgTargetAndFunctions (DataId srcDataId, const SrcFinfo *finfo, vector< ObjId > &tgt, vector< string > &func) const
vector< ObjId > getMsgTargets (DataId srcDataId, const SrcFinfo *finfo) const
const string & getName () const
unsigned int getNeighbors (vector< Id > &ret, const Finfo *finfo) const
int getTick () const
bool hasMsgs (BindIndex b) const
Id id () const
void innerSetTick (unsigned int tick)
bool isDoomed () const
void markAsDoomed ()
void markRewired ()
const vector< MsgDigest > & msgDigest (unsigned int index)
const vector< ObjId > & msgIn () const
void printMsgDigest (unsigned int srcIndex, unsigned int dataIndex) const
void putOffNodeTargetsInDigest (unsigned int srcNum, vector< vector< bool > > &targetNodes)
void putTargetsInDigest (unsigned int srcNum, const MsgFuncBinding &mfb, const FuncOrder &fo, vector< vector< bool > > &targetNodes)
void replaceCinfo (const Cinfo *newCinfo)
Support function for zombieSwap, replaces Cinfo.
void setName (const string &val)
void setTick (int t)
void showFields () const
void showMsg () const
virtual ~Element ()
Private Attributes
unsigned int localDataStart_
unsigned int numData_
unsigned int numPerNode_
Additional Inherited Members
Static Public Member Functions inherited from Element
static void destroyElementTree (const vector< Id > &tree)
Detailed Description
This is the class for handling the local portion of a data element that is distributed over many nodes. Does block-wise partitioning between nodes.
Definition at line 20 of file LocalDataElement.h.
Constructor & Destructor Documentation
LocalDataElement() [1/2]
LocalDataElement::LocalDataElement (Id id, const Cinfo * c, const string & name, unsigned int numData = 1)
This is the main constructor, used by Shell::innerCreate which makes most Elements. Also used to create base Elements to init the simulator in main.cpp. Id is the Id of the new Element Cinfo is the class name is its name numData is the number of data entries, defaults to a singleton.
Definition at line 14 of file LocalDataElement.cpp.
    :
        DataElement( id, c, name, setDataSize( numData ) )
{;}
References DataElement::DataElement(), and setDataSize().
Referenced by Shell::innerCreate(), and testFibonacci().
LocalDataElement() [2/2]
LocalDataElement::LocalDataElement (Id id, const Element * orig, unsigned int n)
This constructor copies over the original n times. It is used for doing all copies, in Shell::innerCopyElements.
Definition at line 28 of file LocalDataElement.cpp.
    :
        DataElement( id, orig, setDataSize( n ),
        ( 1 + (n - 1 ) / Shell::numNodes() ) * Shell::myNode() )
{;}
References DataElement::DataElement(), Shell::myNode(), Shell::numNodes(), and setDataSize().
Referenced by GlobalDataElement::copyElement(), and copyElement().
~LocalDataElement()
LocalDataElement::~LocalDataElement ()
Virtual Destructor
Definition at line 36 of file LocalDataElement.cpp.
{;}
Member Function Documentation
copyElement()
Element * LocalDataElement::copyElement (Id newParent, Id newId, unsigned int n, bool toGlobal) const virtual
Virtual copier. Makes a copy of self.
Implements Element.
Definition at line 41 of file LocalDataElement.cpp.
{
    if ( toGlobal ) {
        cout << "Don't know yet how to copy LocalDataElement to global\n";
        assert( 0 );
        return 0;
    } else {
        return new LocalDataElement( newId, this, n );
    }
}
References LocalDataElement().
getNode()
unsigned int LocalDataElement::getNode (unsigned int dataId) const virtual
Inherited virtual. Returns node location of specified object.
Implements Element.
Definition at line 72 of file LocalDataElement.cpp.
{
    // Assume numData = 95. DataId = 0-9: 0, DataId=80-89:8, DataId >= 90:9
    if ( dataId == ALLDATA ) {
        if ( numLocalData() > 0 ) {
            return Shell::myNode();
        } else {
            return 0; // Sure to have some data on node 0.
        }
    }
    return dataId / numPerNode_;
}
References ALLDATA, Shell::myNode(), DataElement::numLocalData(), and numPerNode_.
getNumOnNode()
unsigned int LocalDataElement::getNumOnNode (unsigned int node) const virtual
Inherited virtual.
Implements Element.
Definition at line 121 of file LocalDataElement.cpp.
{
    unsigned int lastUsedNode = numData_ / numPerNode_;
    if ( lastUsedNode > node )
        return numPerNode_;
    if ( lastUsedNode == node )
        return numData() - node * numPerNode_;
    return 0;
}
References numData(), numData_, and numPerNode_.
isGlobal()
bool LocalDataElement::isGlobal () const inline virtual
Inherited virtual. Reports if this is Global, which it isn't.
Implements Element.
Definition at line 73 of file LocalDataElement.h.
{
            return false;
        }
localDataStart()
unsigned int LocalDataElement::localDataStart () const virtual
Inherited virtual. Returns index of first entry on this node.
Implements Element.
Definition at line 64 of file LocalDataElement.cpp.
{
    // return numPerNode_ * Shell::myNode();
    return localDataStart_;
}
References localDataStart_.
numData()
unsigned int LocalDataElement::numData () const virtual
Inherited virtual. Returns number of data entries over all nodes.
Implements Element.
Definition at line 59 of file LocalDataElement.cpp.
{
    return numData_;
}
References numData_.
Referenced by getNumOnNode().
rawIndex()
unsigned int LocalDataElement::rawIndex (unsigned int dataId) const virtual
Converts dataId to index on current node.
Implements Element.
Definition at line 93 of file LocalDataElement.cpp.
{
    return dataId % numPerNode_;
}
References numPerNode_.
resize()
void LocalDataElement::resize (unsigned int newNumData) virtual
the data() function is inherited from DataElement and used as is. Inherited virtual. Changes the total number of data entries on Element in entire simulation. Not permitted for FieldElements since they are just fields on the data.
Reimplemented from DataElement.
Definition at line 116 of file LocalDataElement.cpp.
{
    DataElement::resize( setDataSize( newNumData ) );
}
References DataElement::resize(), and setDataSize().
setDataSize()
unsigned int LocalDataElement::setDataSize (unsigned int numData)
Definition at line 101 of file LocalDataElement.cpp.
{
    numData_ = numData;
    numPerNode_ = 1 + (numData_ -1 ) / Shell::numNodes();
    localDataStart_ = numPerNode_ * Shell::myNode();
    unsigned int lastUsedNode = numData / numPerNode_;
    if ( lastUsedNode > Shell::myNode() )
        return numPerNode_;
    if ( lastUsedNode == Shell::myNode() )
        return numData - Shell::myNode() * numPerNode_;
    return 0;
}
References localDataStart_, Shell::myNode(), numData_, Shell::numNodes(), and numPerNode_.
Referenced by LocalDataElement(), LocalDataElement(), and resize().
startDataIndex()
unsigned int LocalDataElement::startDataIndex (unsigned int node) const virtual
Inherited virtual. Returns start DataIndex on specified node.
Inherited virtual. Returns start DataId on specified node.
Implements Element.
Definition at line 85 of file LocalDataElement.cpp.
{
    if ( numPerNode_ * node < numData_ )
        return numPerNode_ * node;
    else
        return numData_; // error.
}
References numData_, and numPerNode_.
Member Data Documentation
localDataStart_
unsigned int LocalDataElement::localDataStart_ private
Precomputed value for start index of data on this node.
Definition at line 121 of file LocalDataElement.h.
Referenced by localDataStart(), and setDataSize().
numData_
unsigned int LocalDataElement::numData_ private
This is the total number of data entries on this Element, in the entire simulation. Note that these entries do not have to be on this node, some may be farmed out to other nodes.
Definition at line 109 of file LocalDataElement.h.
Referenced by getNumOnNode(), numData(), setDataSize(), and startDataIndex().
numPerNode_
unsigned int LocalDataElement::numPerNode_ private
This is the number of data entries per node, except for possibly the last node if they don't divide evenly. Useful for intermediate calculations.
Definition at line 116 of file LocalDataElement.h.
Referenced by getNode(), getNumOnNode(), rawIndex(), setDataSize(), and startDataIndex().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/basecode/LocalDataElement.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/basecode/LocalDataElement.cpp