MOOSE - Multiscale Object Oriented Simulation Environment: MeshEntry Class Reference
MeshEntry Class Reference
#include <MeshEntry.h>
Public Member Functions
void extent (DataId di, double volume, double area, double perimeter)
vector< double > getCoordinates (const Eref &e) const
vector< double > getDiffusionArea (const Eref &e) const
vector< double > getDiffusionScaling (const Eref &e) const
unsigned int getDimensions (const Eref &e) const
unsigned int getMeshType (const Eref &e) const
vector< unsigned int > getNeighbors (const Eref &e) const
double getVolume (const Eref &e) const
MeshEntry ()
MeshEntry (const ChemCompt *parent)
void process (const Eref &e, ProcPtr info)
void reinit (const Eref &e, ProcPtr info)
void triggerRemesh (const Eref &e, double oldvol, unsigned int startEntry, const vector< unsigned int > &localIndices, const vector< double > &vols)
Static Public Member Functions
static const Cinfo * initCinfo ()
Private Attributes
const ChemCompt * parent_
Volume or area.
double volume_
Detailed Description
The MeshEntry is a single 'compartment' in the mathematical sense, that is, all properties are assumed homogenous within it. It is a FieldElement, so it gets all its values from the parent ChemCompt.
Definition at line 34 of file MeshEntry.h.
Constructor & Destructor Documentation
MeshEntry() [1/2]
MeshEntry::MeshEntry ()
Definition at line 183 of file MeshEntry.cpp.
    : parent_( 0 )
{;}
References parent_.
MeshEntry() [2/2]
MeshEntry::MeshEntry (const ChemCompt * parent)
Definition at line 187 of file MeshEntry.cpp.
    : parent_( parent )
{;}
References parent_.
Referenced by ChemCompt::ChemCompt().
Member Function Documentation
extent()
void MeshEntry::extent (DataId di, double volume, double area, double perimeter)
getCoordinates()
vector< double > MeshEntry::getCoordinates (const Eref & e) const
Coords that define current MeshEntry. Usually generated on the fly by passing the current Field Index to the parent ChemCompt subclass, which will figure it out.
Definition at line 242 of file MeshEntry.cpp.
{
    return parent_->getCoordinates( e.fieldIndex() );
}
References Eref::fieldIndex(), ChemCompt::getCoordinates(), and parent_.
Referenced by initCinfo().
getDiffusionArea()
vector< double > MeshEntry::getDiffusionArea (const Eref & e) const
Diffusion scaling for area
Definition at line 253 of file MeshEntry.cpp.
{
    return parent_->getDiffusionArea( e.fieldIndex() );
}
References Eref::fieldIndex(), ChemCompt::getDiffusionArea(), and parent_.
Referenced by initCinfo().
getDiffusionScaling()
vector< double > MeshEntry::getDiffusionScaling (const Eref & e) const
Diffusion scaling for geometry of interface
Definition at line 259 of file MeshEntry.cpp.
{
    return parent_->getDiffusionScaling( e.fieldIndex() );
}
References Eref::fieldIndex(), ChemCompt::getDiffusionScaling(), and parent_.
Referenced by initCinfo().
getDimensions()
unsigned int MeshEntry::getDimensions (const Eref & e) const
returns number of dimension
Definition at line 232 of file MeshEntry.cpp.
{
    return parent_->getMeshDimensions( e.fieldIndex() );
}
References Eref::fieldIndex(), ChemCompt::getMeshDimensions(), and parent_.
Referenced by initCinfo().
getMeshType()
unsigned int MeshEntry::getMeshType (const Eref & e) const
The MeshType defines the shape of the mesh entry. 0: Not assigned 1: cuboid 2: cylinder
cylindrical shell 4: cylindrical shell segment 5: sphere 6: spherical shell 7: spherical shell segment 8: Tetrahedral 9: EndoMesh
Definition at line 237 of file MeshEntry.cpp.
{
    return parent_->getMeshType( e.fieldIndex() );
}
References Eref::fieldIndex(), ChemCompt::getMeshType(), and parent_.
Referenced by initCinfo().
getNeighbors()
vector< unsigned int > MeshEntry::getNeighbors (const Eref & e) const
Indices of other Entries that this one connects to, for diffusion
Definition at line 247 of file MeshEntry.cpp.
{
    return parent_->getNeighbors( e.fieldIndex() );
}
References Eref::fieldIndex(), ChemCompt::getNeighbors(), and parent_.
Referenced by initCinfo().
getVolume()
double MeshEntry::getVolume (const Eref & e) const
Definition at line 226 of file MeshEntry.cpp.
{
    //return parent_->getMeshEntryVolume( e.dataIndex() );
    return parent_->getMeshEntryVolume( e.fieldIndex() );
}
References Eref::fieldIndex(), ChemCompt::getMeshEntryVolume(), and parent_.
Referenced by initCinfo().
initCinfo()
const Cinfo * MeshEntry::initCinfo () static
Definition at line 47 of file MeshEntry.cpp.
{
        // Field Definitions
        static ReadOnlyElementValueFinfo< MeshEntry, double > volume(
            "volume",
            "Volume of this MeshEntry",
            &MeshEntry::getVolume
        );
        static ReadOnlyElementValueFinfo< MeshEntry, unsigned int >
            dimensions (
            "dimensions",
            "number of dimensions of this MeshEntry",
            &MeshEntry::getDimensions
        );
        static ReadOnlyElementValueFinfo< MeshEntry, unsigned int >
            meshType(
            "meshType",
            " The MeshType defines the shape of the mesh entry."
            " 0: Not assigned"
            " 1: cuboid"
            " 2: cylinder"
            " 3. cylindrical shell"
            " 4: cylindrical shell segment"
            " 5: sphere"
            " 6: spherical shell"
            " 7: spherical shell segment"
            " 8: Tetrahedral",
            &MeshEntry::getMeshType
        );
        static ReadOnlyElementValueFinfo< MeshEntry, vector< double >  >
            coordinates (
            "Coordinates",
            "Coordinates that define current MeshEntry. Depend on MeshType.",
            &MeshEntry::getCoordinates
        );
        static ReadOnlyElementValueFinfo< MeshEntry, vector< unsigned int >  >
            neighbors (
            "neighbors",
            "Indices of other MeshEntries that this one connects to",
            &MeshEntry::getNeighbors
        );
        static ReadOnlyElementValueFinfo< MeshEntry, vector< double >  >
            diffusionArea (
            "DiffusionArea",
            "Diffusion area for geometry of interface",
            &MeshEntry::getDiffusionArea
        );
        static ReadOnlyElementValueFinfo< MeshEntry, vector< double >  >
            diffusionScaling (
            "DiffusionScaling",
            "Diffusion scaling for geometry of interface",
            &MeshEntry::getDiffusionScaling
        );
        // MsgDest Definitions
        static DestFinfo process( "process",
            "Handles process call",
            new ProcOpFunc< MeshEntry >( &MeshEntry::process ) );
        static DestFinfo reinit( "reinit",
            "Handles reinit call",
            new ProcOpFunc< MeshEntry >( &MeshEntry::reinit ) );
        // Shared definitions
        static Finfo* procShared[] = {
            &process, &reinit
        };
        static SharedFinfo proc( "proc",
            "Shared message for process and reinit",
            procShared, sizeof( procShared ) / sizeof( const Finfo* )
        );
        static Finfo* meshShared[] = {
            remeshOut(), volume.getFinfo()
        };
        static SharedFinfo mesh( "mesh",
            "Shared message for updating mesh volumes and subdivisions,"
            "typically controls pool volumes",
            meshShared, sizeof( meshShared ) / sizeof( const Finfo* )
        );
        // SrcFinfo Definitions
    static Finfo* meshFinfos[] = {
        &volume,        // Readonly Value
        &dimensions,    // Readonly Value
        &meshType,      // Readonly Value
        &coordinates,   // Readonly Value
        &neighbors,     // Readonly Value
        &diffusionArea, // Readonly Value
        &diffusionScaling,  // Readonly Value
        &proc,          // SharedFinfo
        &mesh,          // SharedFinfo
        remeshReacsOut(),   // SrcFinfo
    };
    static string doc[] =
    {
            "Name", "MeshEntry",
            "Author", "Upi Bhalla",
            "Description", "One voxel in a chemical reaction compartment",
    };
    static Dinfo< MeshEntry > dinfo;
    static Cinfo meshEntryCinfo (
        "MeshEntry",
        Neutral::initCinfo(),
        meshFinfos,
        sizeof( meshFinfos ) / sizeof ( Finfo* ),
        &dinfo,
        doc,
        sizeof(doc)/sizeof( string ),
        true // This IS a FieldElement, not be be created directly.
    );
    return &meshEntryCinfo;
}
References Cinfo::Cinfo(), DestFinfo::DestFinfo(), getCoordinates(), getDiffusionArea(), getDiffusionScaling(), getDimensions(), ValueFinfoBase::getFinfo(), getMeshType(), getNeighbors(), getVolume(), Neutral::initCinfo(), process(), ProcOpFunc< T >::ProcOpFunc(), ReadOnlyElementValueFinfo< T, F >::ReadOnlyElementValueFinfo(), reinit(), remeshOut(), remeshReacsOut(), and SharedFinfo::SharedFinfo().
Referenced by ChemCompt::initCinfo().
process()
void MeshEntry::process (const Eref & e, ProcPtr info)
Update the diffusion rate terms. Note that these stay the same through the entire clock tick, even if the GSL solver takes many intermediate steps. The assumption is that the concs change slowly enough that the diffusion terms are not hugely changed over the duration of one tick. Also assume that diffusion itself is slow. The latter assumption is OK for suitable grid sizes. The first assumption is OK with a sensible tick step.
Definition at line 204 of file MeshEntry.cpp.
{
    // cout << "updateDiffusion for " << e.fieldIndex() << ", at t = " << info->currTime << ", on thr = " << info->threadIndexInGroup << endl << flush;
    // parent_->updateDiffusion( e.fieldIndex() );
}
Referenced by initCinfo().
reinit()
void MeshEntry::reinit (const Eref & e, ProcPtr info)
Assigns the Stoich Id to the parent.
Definition at line 213 of file MeshEntry.cpp.
{
    if ( e.dataIndex() == 0 ) {
        ObjId pa = Neutral::parent( e );
        // parent_->lookupStoich( pa );
    }
}
References Eref::dataIndex(), and Neutral::parent().
Referenced by initCinfo().
triggerRemesh()
void MeshEntry::triggerRemesh (const Eref & e, double oldvol, unsigned int startEntry, const vector< unsigned int > & localIndices, const vector< double > & vols)
Definition at line 267 of file MeshEntry.cpp.
{
    // cout << "MeshEntry::triggerRemesh on " << e.element()->getName() << endl;
    remeshOut()->send( e, oldvol, parent_->getNumEntries(),
        startEntry, localIndices, vols );
    remeshReacsOut()->send( e );
}
References ChemCompt::getNumEntries(), parent_, remeshOut(), remeshReacsOut(), SrcFinfo0::send(), and SrcFinfo5< T1, T2, T3, T4, T5 >::send().
Referenced by PsdMesh::handlePsdList(), and SpineMesh::handleSpineList().
Member Data Documentation
parent_
const ChemCompt* MeshEntry::parent_ private
Volume or area.
Definition at line 128 of file MeshEntry.h.
Referenced by getCoordinates(), getDiffusionArea(), getDiffusionScaling(), getDimensions(), getMeshType(), getNeighbors(), getVolume(), MeshEntry(), MeshEntry(), and triggerRemesh().
volume_
double MeshEntry::volume_ private
Definition at line 127 of file MeshEntry.h.
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/mesh/MeshEntry.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/mesh/MeshEntry.cpp