MOOSE - Multiscale Object Oriented Simulation Environment: SpikeStats Class Reference
SpikeStats Class Reference
#include <SpikeStats.h>
Public Member Functions
void addSpike (DataId synIndex, const double time)
void addSpike (double v)
double getThreshold () const
void setThreshold (double thresh)
SpikeStats ()
void Vm (double v)
void vProcess (const Eref &e, ProcPtr p)
Virtual func for handling process calls.
void vReinit (const Eref &e, ProcPtr p)
Public Member Functions inherited from Stats
void doWindowCalculation () const
double getMean () const
unsigned int getNum () const
double getSdev () const
double getSum () const
unsigned int getWindowLength () const
double getWmean () const
unsigned int getWnum () const
double getWsdev () const
double getWsum () const
void innerWindowCalculation ()
void input (double v)
void process (const Eref &e, ProcPtr p)
void reinit (const Eref &e, ProcPtr p)
void setWindowLength (unsigned int len)
Stats ()
Static Public Member Functions
static const Cinfo * initCinfo ()
Static Public Member Functions inherited from Stats
static const Cinfo * initCinfo ()
Private Attributes
bool fired_
unsigned int numSpikes_
double threshold_
Detailed Description
Definition at line 12 of file SpikeStats.h.
Constructor & Destructor Documentation
SpikeStats()
SpikeStats::SpikeStats ()
Definition at line 81 of file SpikeStats.cpp.
    : Stats(),
        numSpikes_( 0 ), threshold_( 0.0 ), fired_( false )
{ ; }
References fired_, numSpikes_, Stats::Stats(), and threshold_.
Member Function Documentation
addSpike() [1/2]
void SpikeStats::addSpike (DataId synIndex, const double time)
Inserts an event into the pendingEvents queue for spikes.
addSpike() [2/2]
void SpikeStats::addSpike (double v)
Definition at line 120 of file SpikeStats.cpp.
{
    numSpikes_ ++;
}
References numSpikes_.
Referenced by initCinfo().
getThreshold()
double SpikeStats::getThreshold () const
Definition at line 129 of file SpikeStats.cpp.
{
    return threshold_;
}
References threshold_.
Referenced by initCinfo().
initCinfo()
const Cinfo * SpikeStats::initCinfo () static
Definition at line 14 of file SpikeStats.cpp.
{
        // Field Definitions
        static ValueFinfo< SpikeStats, double > threshold(
            "threshold",
            "Spiking threshold. If Vm crosses this going up then the "
           "SpikeStats object considers that a spike has happened and "
           "adds it to the stats.",
            &SpikeStats::setThreshold,
            &SpikeStats::getThreshold
        );
        // MsgDest Definitions
        static DestFinfo addSpike( "addSpike",
            "Handles spike event time input, converts into a rate "
            "to do stats upon.",
            new OpFunc1< SpikeStats, double >( &SpikeStats::addSpike ) );
        static DestFinfo Vm( "Vm",
            "Handles continuous voltage input, can be coming in much "
            "than update rate of the SpikeStats. Looks for transitions "
            "above threshold to register the arrival of a spike. "
            "Doesn't do another spike till Vm falls below threshold. ",
            new OpFunc1< SpikeStats, double >( &SpikeStats::Vm ) );
    static Finfo* statsFinfos[] = {
        &threshold, // Value
        &addSpike,  // DestFinfo
        &Vm,    // DestFinfo
    };
    static string doc[] =
    {
        "Name", "SpikeStats",
        "Author", "Upi Bhalla Aug 2014",
        "Description",
        "Object to do some minimal stats on rate of a spike train. "
        "Derived from the Stats object and returns the same set of stats."
        "Can take either predigested spike event input, or can handle "
        "a continuous sampling of membrane potential Vm and decide if "
        "a spike has occured based on a threshold. "
    };
    static Dinfo< SpikeStats > dinfo;
    static Cinfo spikeStatsCinfo (
        "SpikeStats",
        Stats::initCinfo(),
        statsFinfos,
        sizeof( statsFinfos ) / sizeof ( Finfo* ),
        &dinfo,
        doc,
        sizeof( doc ) / sizeof( string )
    );
    return &spikeStatsCinfo;
}
References addSpike(), Cinfo::Cinfo(), DestFinfo::DestFinfo(), getThreshold(), Stats::initCinfo(), OpFunc1< T, A >::OpFunc1(), setThreshold(), ValueFinfo< T, F >::ValueFinfo(), and Vm().
setThreshold()
void SpikeStats::setThreshold (double thresh)
Definition at line 134 of file SpikeStats.cpp.
{
    threshold_ = v;
}
References threshold_.
Referenced by initCinfo().
Vm()
void SpikeStats::Vm (double v)
Definition at line 107 of file SpikeStats.cpp.
{
    if ( fired_ ) { // Wait for it to go below threshold
        if ( v < threshold_ )
            fired_ = false;
    } else {
        if ( v > threshold_ ) { // wait for it to go above threshold.
            fired_ = true;
            numSpikes_++;
        }
    }
}
References fired_, numSpikes_, and threshold_.
Referenced by initCinfo().
vProcess()
void SpikeStats::vProcess (const Eref & e, ProcPtr p) virtual
Virtual func for handling process calls.
Reimplemented from Stats.
Definition at line 90 of file SpikeStats.cpp.
{
    double rate = static_cast< double >( numSpikes_ ) / p->dt;
    numSpikes_ = 0;
    Stats::input( rate );
}
References ProcInfo::dt, Stats::input(), and numSpikes_.
vReinit()
void SpikeStats::vReinit (const Eref & e, ProcPtr p) virtual
Reimplemented from Stats.
Definition at line 97 of file SpikeStats.cpp.
{
    Stats::vReinit( e, p );
    numSpikes_ = 0;
    fired_ = 0;
}
References fired_, numSpikes_, and Stats::vReinit().
Member Data Documentation
fired_
bool SpikeStats::fired_ private
Definition at line 44 of file SpikeStats.h.
Referenced by SpikeStats(), Vm(), and vReinit().
numSpikes_
unsigned int SpikeStats::numSpikes_ private
Definition at line 42 of file SpikeStats.h.
Referenced by addSpike(), SpikeStats(), Vm(), vProcess(), and vReinit().
threshold_
double SpikeStats::threshold_ private
Definition at line 43 of file SpikeStats.h.
Referenced by getThreshold(), setThreshold(), SpikeStats(), and Vm().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/builtins/SpikeStats.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/builtins/SpikeStats.cpp