MOOSE - Multiscale Object Oriented Simulation Environment: EpFunc2< T, A1, A2 > Class Template Reference
EpFunc2< T, A1, A2 > Class Template Reference
#include <EpFunc.h>
Public Member Functions
EpFunc2 (void(T::*func)(const Eref &, A1, A2))
void op (const Eref &e, A1 arg1, A2 arg2) const
Public Member Functions inherited from OpFunc2Base< A1, A2 >
bool checkFinfo (const Finfo *s) const
const OpFunc * makeHopFunc (HopIndex hopIndex) const
void opBuffer (const Eref &e, double *buf) const
Executes the OpFunc by converting args.
virtual void opVec (const Eref &e, const vector< A1 > &arg1, const vector< A2 > &arg2, const OpFunc2Base< A1, A2 > *op) const
void opVecBuffer (const Eref &e, double *buf) const
Executes the OpFunc for all data by converting a vector of args.
string rttiType () const
Public Member Functions inherited from OpFunc
OpFunc ()
unsigned int opIndex () const
bool setIndex (unsigned int i)
Used when rebuilding the Fid->OpFunc mapping.
virtual ~OpFunc ()
Private Attributes
void(T::* func_)(const Eref &e, A1, A2)
Additional Inherited Members
Static Public Member Functions inherited from OpFunc
static const OpFunc * lookop (unsigned int opIndex)
static unsigned int rebuildOpIndex ()
cleans out the entire Ops vector. Returns size of orig vector.
Detailed Description
template<class T, class A1, class A2>
class EpFunc2< T, A1, A2 >
Definition at line 83 of file EpFunc.h.
Constructor & Destructor Documentation
EpFunc2()
template<class T , class A1 , class A2 > EpFunc2< T, A1, A2 >::EpFunc2 (void(T::*)(const Eref &, A1, A2) func) inline
Definition at line 87 of file EpFunc.h.
        : func_( func )
    {;}
References EpFunc2< T, A1, A2 >::func_.
Referenced by CaConcBase::initCinfo(), moose::CompartmentBase::initCinfo(), DifBufferBase::initCinfo(), DifShellBase::initCinfo(), MgBlock::initCinfo(), Interpol2D::initCinfo(), Dsolve::initCinfo(), ChemCompt::initCinfo(), Clock::initCinfo(), Neutral::initCinfo(), Shell::initCinfo(), PoolBase::initPoolBaseCinfo(), and testSharedMsg().
Member Function Documentation
op()
template<class T , class A1 , class A2 > void EpFunc2< T, A1, A2 >::op (const Eref & e, A1 arg1, A2 arg2) const inline virtual
Implements OpFunc2Base< A1, A2 >.
Definition at line 91 of file EpFunc.h.
    {
        ( reinterpret_cast< T* >( e.data() )->*func_ )( e, arg1, arg2 );
    }
References Eref::data(), and EpFunc2< T, A1, A2 >::func_.
Member Data Documentation
func_
template<class T , class A1 , class A2 > void(T::* EpFunc2< T, A1, A2 >::func_) (const Eref &e, A1, A2) private
Definition at line 97 of file EpFunc.h.
Referenced by EpFunc2< T, A1, A2 >::EpFunc2(), and EpFunc2< T, A1, A2 >::op().
The documentation for this class was generated from the following file:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/basecode/EpFunc.h