MOOSE - Multiscale Object Oriented Simulation Environment: Mstring Class Reference
Mstring Class Reference
#include <Mstring.h>
Public Member Functions
string getThis () const
Mstring ()
Mstring (string other)
void setThis (string v)
Static Public Member Functions
static const Cinfo * initCinfo ()
Private Attributes
string value_
Detailed Description
Definition at line 12 of file Mstring.h.
Constructor & Destructor Documentation
Mstring() [1/2]
Mstring::Mstring ()
Definition at line 40 of file Mstring.cpp.
                 : value_("")
{
    ;
}
References value_.
Mstring() [2/2]
Mstring::Mstring (string other)
Member Function Documentation
getThis()
string Mstring::getThis () const
Definition at line 55 of file Mstring.cpp.
{
    return value_;
}
References value_.
Referenced by initCinfo().
initCinfo()
const Cinfo * Mstring::initCinfo () static
Definition at line 12 of file Mstring.cpp.
{
    // Field Definitions
    static ValueFinfo<Mstring, string> thisFinfo(
        "this", "Access function for entire Mstring object.", &Mstring::setThis,
        &Mstring::getThis);
    static ValueFinfo<Mstring, string> valueFinfo(
        "value",
        "Access function for value field of Mstring object,"
        "which happens also to be the entire contents of the object.",
        &Mstring::setThis, &Mstring::getThis);
    static Finfo* mStringFinfos[] = {&thisFinfo,   // Value
                                     &valueFinfo,  // Value
    };
    static Dinfo<Mstring> dinfo;
    static Cinfo mStringCinfo("Mstring", Neutral::initCinfo(), mStringFinfos,
                              sizeof(mStringFinfos) / sizeof(Finfo*), &dinfo);
    return &mStringCinfo;
}
References Cinfo::Cinfo(), getThis(), Neutral::initCinfo(), setThis(), and ValueFinfo< T, F >::ValueFinfo().
setThis()
void Mstring::setThis (string v)
Definition at line 50 of file Mstring.cpp.
{
    value_ = v;
}
References value_.
Referenced by initCinfo().
Member Data Documentation
value_
string Mstring::value_ private
Definition at line 36 of file Mstring.h.
Referenced by getThis(), Mstring(), and setThis().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/builtins/Mstring.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/builtins/Mstring.cpp