MOOSE - Multiscale Object Oriented Simulation Environment: Msg Class Reference
Msg Class Reference abstract
#include <Msg.h>
Public Member Functions
virtual Msg * copy (Id origSrc, Id newSrc, Id newTgt, FuncId fid, unsigned int b, unsigned int n) const =0
Element * e1 () const
Element * e2 () const
virtual ObjId findOtherEnd (ObjId) const =0
virtual Eref firstTgt (const Eref &src) const =0
ObjId getAdjacent (ObjId) const
vector< string > getDestFieldsOnE1 () const
vector< string > getDestFieldsOnE2 () const
Id getE1 () const
Id getE2 () const
vector< string > getSrcFieldsOnE1 () const
vector< string > getSrcFieldsOnE2 () const
bool isForward (const Element *src) const
ObjId mid () const
Msg (ObjId mid, Element *e1, Element *e2)
Constructor.
virtual void sources (vector< vector< Eref > > &v) const =0
virtual void targets (vector< vector< Eref > > &v) const =0
virtual ~Msg ()
Destructor.
Static Public Member Functions
static void clearAllMsgs ()
static void deleteMsg (ObjId mid)
static const Msg * getMsg (ObjId m)
static const Cinfo * initCinfo ()
static unsigned int initMsgManagers ()
static bool isLastTrump ()
True when MOOSE has been terminated and is being cleaned up.
static const Msg * lastMsg ()
Protected Attributes
Element * e1_
Index of this Msg on the msg_ vector.
Element * e2_
Element 1 attached to Msg.
ObjId mid_
Static Protected Attributes
static bool lastTrump_ = false
Flag to indicate termination of program.
static Id msgManagerId_
Element 2 attached to Msg.
Static Private Attributes
static const Msg * lastMsg_ = 0
Detailed Description
Manages data flow between two elements. Is always many-to-many, with assorted variants.
Definition at line 18 of file Msg.h.
Constructor & Destructor Documentation
Msg()
Msg::Msg (ObjId mid, Element * e1, Element * e2)
Constructor.
Definition at line 30 of file Msg.cpp.
    : mid_( mid), e1_( e1 ), e2_( e2 )
{
    e1->addMsg( mid_ );
    e2->addMsg( mid_ );
    lastMsg_ = this;
}
References Element::addMsg(), e1_, e2_, lastMsg_, mid_, and ObjId::ObjId().
Referenced by DiagonalMsg::DiagonalMsg(), OneToAllMsg::OneToAllMsg(), OneToOneDataIndexMsg::OneToOneDataIndexMsg(), OneToOneMsg::OneToOneMsg(), SingleMsg::SingleMsg(), and SparseMsg::SparseMsg().
~Msg()
Msg::~Msg () virtual
Destructor.
Definition at line 38 of file Msg.cpp.
{
    if ( !lastTrump_ )
    {
        e1_->dropMsg( mid_ );
        e2_->dropMsg( mid_ );
    }
    /*
    if ( mid_ > 1 )
        garbageMsg_.push_back( mid_ );
        */
}
References Element::dropMsg(), e1_, e2_, lastTrump_, and mid_.
Member Function Documentation
clearAllMsgs()
void Msg::clearAllMsgs () static
Clears out the Msg data stored in each Msg subtype.
Definition at line 304 of file Msg.cpp.
{
    lastTrump_ = true;
    for ( unsigned int i = 0; i < SingleMsg::numMsg(); ++i )
    {
        Msg* m = reinterpret_cast< Msg* >( SingleMsg::lookupMsg( i ) );
        if ( m ) delete m;
    }
    for ( unsigned int i = 0; i < OneToOneMsg::numMsg(); ++i )
    {
        Msg* m = reinterpret_cast< Msg* >( OneToOneMsg::lookupMsg( i ) );
        if ( m ) delete m;
    }
    for ( unsigned int i = 0; i < OneToAllMsg::numMsg(); ++i )
    {
        Msg* m = reinterpret_cast< Msg* >( OneToAllMsg::lookupMsg( i ) );
        if ( m ) delete m;
    }
    for ( unsigned int i = 0; i < DiagonalMsg::numMsg(); ++i )
    {
        Msg* m = reinterpret_cast< Msg* >( DiagonalMsg::lookupMsg( i ) );
        if ( m ) delete m;
    }
    for ( unsigned int i = 0; i < SparseMsg::numMsg(); ++i )
    {
        Msg* m = reinterpret_cast< Msg* >( SparseMsg::lookupMsg( i ) );
        if ( m ) delete m;
    }
}
References lastTrump_, DiagonalMsg::lookupMsg(), OneToAllMsg::lookupMsg(), OneToOneMsg::lookupMsg(), SingleMsg::lookupMsg(), SparseMsg::lookupMsg(), DiagonalMsg::numMsg(), OneToAllMsg::numMsg(), OneToOneMsg::numMsg(), SingleMsg::numMsg(), and SparseMsg::numMsg().
Referenced by main().
copy()
virtual Msg * Msg::copy (Id origSrc, Id newSrc, Id newTgt, FuncId fid, unsigned int b, unsigned int n) const pure virtual
Make a copy of this Msg. The original msg was on origSrc. The new Msg should go from newSrc to newTgt, and have the function fid, on bindIndex b. The copy may have to be a higher-order Msg type to handle arrays if n > 1. Note that n is not the number of msgs, but the multiplier by which numData will be scaled.
Implemented in DiagonalMsg, OneToAllMsg, OneToOneDataIndexMsg, OneToOneMsg, SingleMsg, and SparseMsg.
Referenced by innerCopyMsgs().
deleteMsg()
void Msg::deleteMsg (ObjId mid) static
Deletes a message identified by its mid.
Definition at line 53 of file Msg.cpp.
{
    const Msg* msg = getMsg( mid );
    delete( msg );
}
References getMsg().
Referenced by Element::clearBinding(), HSolve::deleteIncomingMessages(), Neutral::destroy(), Element::dropAllMsgsFromSrc(), Shell::dropClockMsgs(), Shell::innerMove(), HSolveActive::readSynapses(), and Element::~Element().
e1()
Element * Msg::e1 () const inline
Return the first element
Definition at line 61 of file Msg.h.
{
            return e1_;
        }
References e1_.
Referenced by SharedFinfo::addMsg(), DiagonalMsg::copy(), OneToAllMsg::copy(), OneToOneDataIndexMsg::copy(), OneToOneMsg::copy(), SingleMsg::copy(), SparseMsg::copy(), Element::dropAllMsgsFromSrc(), Element::findCaller(), DiagonalMsg::findOtherEnd(), OneToAllMsg::findOtherEnd(), OneToOneDataIndexMsg::findOtherEnd(), OneToOneMsg::findOtherEnd(), SingleMsg::findOtherEnd(), SparseMsg::findOtherEnd(), Element::getInputMsgs(), Element::getInputs(), Element::getInputsWithTgtIndex(), Element::getMsgSourceAndSender(), Element::getMsgTargetAndFunctions(), Element::getOutputs(), getReactantVols(), innerCopyMsgs(), SparseMsg::pairFill(), putFuncsInOrder(), Element::putOffNodeTargetsInDigest(), Element::putTargetsInDigest(), SparseMsg::randomConnect(), SingleMsg::setI1(), OneToAllMsg::setI1(), SingleMsg::setI2(), DiagonalMsg::setStride(), SingleMsg::setTargetField(), Element::showMsg(), SparseMsg::transpose(), and SparseMsg::updateAfterFill().
e2()
Element * Msg::e2 () const inline
Return the second element
Definition at line 68 of file Msg.h.
{
            return e2_;
        }
References e2_.
Referenced by SharedFinfo::addMsg(), Neutral::child(), DiagonalMsg::copy(), OneToAllMsg::copy(), OneToOneDataIndexMsg::copy(), OneToOneMsg::copy(), SingleMsg::copy(), SparseMsg::copy(), Element::dropAllMsgsFromSrc(), Element::findCaller(), DiagonalMsg::findOtherEnd(), OneToAllMsg::findOtherEnd(), OneToOneDataIndexMsg::findOtherEnd(), OneToOneMsg::findOtherEnd(), SingleMsg::findOtherEnd(), SparseMsg::findOtherEnd(), Neutral::getIncomingMsgs(), Element::getInputMsgs(), Element::getInputs(), Element::getInputsWithTgtIndex(), Element::getMsgSourceAndSender(), Element::getMsgTargetAndFunctions(), Element::getOutputs(), getReactantVols(), innerCopyMsgs(), SparseMsg::pairFill(), putFuncsInOrder(), Element::putOffNodeTargetsInDigest(), Element::putTargetsInDigest(), SparseMsg::randomConnect(), SingleMsg::setI1(), OneToAllMsg::setI1(), SingleMsg::setI2(), DiagonalMsg::setStride(), Element::showMsg(), SparseMsg::transpose(), and SparseMsg::updateAfterFill().
findOtherEnd()
virtual ObjId Msg::findOtherEnd (ObjId) const pure virtual
Find the other end of this Msg. In most cases this is a straightforward return of e1 or e2, plus perhaps a DataId. But in some complex msgs we need to figure out DataIds that match with the target. In many-to-one cases we just return the first entry. If no Element match, return ObjId(Id(), DataId::bad()) If Element e matches but not DataId, return ObjId(e.id(), DataId::bad())
Implemented in DiagonalMsg, OneToAllMsg, OneToOneDataIndexMsg, OneToOneMsg, SingleMsg, and SparseMsg.
Referenced by Neutral::child(), HSolve::deleteIncomingMessages(), getAdjacent(), Neutral::isDescendant(), Neutral::parent(), Neutral::path(), and testAssortedMsg().
firstTgt()
virtual Eref Msg::firstTgt (const Eref & src) const pure virtual
Obtain the first target Eref for the specified Src Eref It is really meant only to work with messages with a single target ObjId for each given src, typically OneToOne.
Implemented in DiagonalMsg, OneToAllMsg, OneToOneDataIndexMsg, OneToOneMsg, SingleMsg, and SparseMsg.
Referenced by Element::getInputsWithTgtIndex().
getAdjacent()
ObjId Msg::getAdjacent (ObjId obj) const
Wrapper for findOtherEnd - to expose it as a LookupFinfo.
Definition at line 173 of file Msg.cpp.
{
    return findOtherEnd(obj);
}
References findOtherEnd().
Referenced by initCinfo().
getDestFieldsOnE1()
vector< string > Msg::getDestFieldsOnE1 () const
Return names of DestFinfos for messages going from e2 to e1.
Definition at line 150 of file Msg.cpp.
{
    vector< pair< BindIndex, FuncId > > ids;
    vector< string > ret;
    e2_->getFieldsOfOutgoingMsg( mid_, ids );
    for ( unsigned int i = 0; i < ids.size(); ++i )
    {
        string name = e1_->cinfo()->destFinfoName( ids[i].second );
        if ( name == "" )
        {
            cout << "Error: Msg::getDestFieldsOnE1: Failed to find field on msg " <<
                 e1_->getName() << "-->" << e2_->getName() << endl;
        }
        else
        {
            ret.push_back( name );
        }
    }
    return ret;
}
References Element::cinfo(), Cinfo::destFinfoName(), e1_, e2_, Element::getFieldsOfOutgoingMsg(), Element::getName(), and mid_.
Referenced by initCinfo(), and testMsgSrcDestFields().
getDestFieldsOnE2()
vector< string > Msg::getDestFieldsOnE2 () const
Return names of DestFinfos for messages going from e1 to e2.
Definition at line 104 of file Msg.cpp.
{
    vector< pair< BindIndex, FuncId > > ids;
    vector< string > ret;
    e1_->getFieldsOfOutgoingMsg( mid_, ids );
    for ( unsigned int i = 0; i < ids.size(); ++i )
    {
        string name = e2_->cinfo()->destFinfoName( ids[i].second );
        if ( name == "" )
        {
            cout << "Error: Msg::getDestFieldsOnE2: Failed to find field on msg " <<
                 e1_->getName() << "-->" << e2_->getName() << endl;
        }
        else
        {
            ret.push_back( name );
        }
    }
    return ret;
}
References Element::cinfo(), Cinfo::destFinfoName(), e1_, e2_, Element::getFieldsOfOutgoingMsg(), Element::getName(), and mid_.
Referenced by initCinfo(), and testMsgSrcDestFields().
getE1()
Id Msg::getE1 () const
Return the first element id
Definition at line 68 of file Msg.cpp.
{
    return e1_->id();
}
References e1_, and Element::id().
Referenced by initCinfo().
getE2()
Id Msg::getE2 () const
Return the second element id
Definition at line 76 of file Msg.cpp.
{
    return e2_->id();
}
References e2_, and Element::id().
Referenced by Neutral::child(), and initCinfo().
getMsg()
const Msg * Msg::getMsg (ObjId m) static
Looks up the message .
Definition at line 60 of file Msg.cpp.
{
    return reinterpret_cast< const Msg* >( m.data() );
}
References ObjId::data().
Referenced by SharedFinfo::addMsg(), Neutral::child(), Neutral::children(), HSolve::deleteIncomingMessages(), deleteMsg(), Element::dropAllMsgsFromSrc(), Element::findCaller(), Neutral::getIncomingMsgs(), Element::getInputMsgs(), Element::getInputs(), Element::getInputsWithTgtIndex(), Element::getMsgSourceAndSender(), Element::getMsgTargetAndFunctions(), Element::getOutputs(), getReactantVols(), innerCopyMsgs(), Neutral::isDescendant(), Neutral::parent(), Neutral::path(), putFuncsInOrder(), Element::putOffNodeTargetsInDigest(), Element::putTargetsInDigest(), Element::showMsg(), and testAssortedMsg().
getSrcFieldsOnE1()
vector< string > Msg::getSrcFieldsOnE1 () const
Return names of SrcFinfos for messages going from e1 to e2.
Definition at line 81 of file Msg.cpp.
{
    vector< pair< BindIndex, FuncId > > ids;
    vector< string > ret;
    e1_->getFieldsOfOutgoingMsg( mid_, ids );
    for ( unsigned int i = 0; i < ids.size(); ++i )
    {
        string name = e1_->cinfo()->srcFinfoName( ids[i].first );
        if ( name == "" )
        {
            cout << "Error: Msg::getSrcFieldsOnE1: Failed to find field on msg " <<
                 e1_->getName() << "-->" << e2_->getName() << endl;
        }
        else
        {
            ret.push_back( name );
        }
    }
    return ret;
}
References Element::cinfo(), e1_, e2_, Element::getFieldsOfOutgoingMsg(), Element::getName(), mid_, and Cinfo::srcFinfoName().
Referenced by initCinfo(), and testMsgSrcDestFields().
getSrcFieldsOnE2()
vector< string > Msg::getSrcFieldsOnE2 () const
Return names of SrcFinfos for messages going from e2 to e1.
Definition at line 127 of file Msg.cpp.
{
    vector< pair< BindIndex, FuncId > > ids;
    vector< string > ret;
    e2_->getFieldsOfOutgoingMsg( mid_, ids );
    for ( unsigned int i = 0; i < ids.size(); ++i )
    {
        string name = e2_->cinfo()->srcFinfoName( ids[i].first );
        if ( name == "" )
        {
            cout << "Error: Msg::getSrcFieldsOnE2: Failed to find field on msg " <<
                 e1_->getName() << "-->" << e2_->getName() << endl;
        }
        else
        {
            ret.push_back( name );
        }
    }
    return ret;
}
References Element::cinfo(), e1_, e2_, Element::getFieldsOfOutgoingMsg(), Element::getName(), mid_, and Cinfo::srcFinfoName().
Referenced by initCinfo(), and testMsgSrcDestFields().
initCinfo()
const Cinfo * Msg::initCinfo () static
Set up the Msg to be accessed like an Element Although the bare Msg class is never seen, we will use it as a base class and set up some common fields here.
Definition at line 182 of file Msg.cpp.
{
    // Field definitions.
    static ReadOnlyValueFinfo< Msg, Id > e1(
        "e1",
        "Id of source Element.",
        &Msg::getE1
    );
    static ReadOnlyValueFinfo< Msg, Id > e2(
        "e2",
        "Id of source Element.",
        &Msg::getE2
    );
    static ReadOnlyValueFinfo< Msg, vector< string > > srcFieldsOnE1(
        "srcFieldsOnE1",
        "Names of SrcFinfos for messages going from e1 to e2. There are"
        "matching entries in the destFieldsOnE2 vector",
        &Msg::getSrcFieldsOnE1
    );
    static ReadOnlyValueFinfo< Msg, vector< string > > destFieldsOnE2(
        "destFieldsOnE2",
        "Names of DestFinfos for messages going from e1 to e2. There are"
        "matching entries in the srcFieldsOnE1 vector",
        &Msg::getDestFieldsOnE2
    );
    static ReadOnlyValueFinfo< Msg, vector< string > > srcFieldsOnE2(
        "srcFieldsOnE2",
        "Names of SrcFinfos for messages going from e2 to e1. There are"
        "matching entries in the destFieldsOnE1 vector",
        &Msg::getSrcFieldsOnE2
    );
    static ReadOnlyValueFinfo< Msg, vector< string > > destFieldsOnE1(
        "destFieldsOnE1",
        "Names of destFinfos for messages going from e2 to e1. There are"
        "matching entries in the srcFieldsOnE2 vector",
        &Msg::getDestFieldsOnE1
    );
    static ReadOnlyLookupValueFinfo< Msg, ObjId, ObjId > adjacent(
        "adjacent",
        "The element adjacent to the specified element",
        &Msg::getAdjacent);
    static Finfo* msgFinfos[] =
    {
        &e1,        // readonly value
        &e2,        // readonly value
        &srcFieldsOnE1, // readonly value
        &destFieldsOnE2,    // readonly value
        &srcFieldsOnE2, // readonly value
        &destFieldsOnE1,    // readonly value
        &adjacent, // readonly lookup value
    };
    static Cinfo msgCinfo (
        "Msg",  // name
        Neutral::initCinfo(),               // base class
        msgFinfos,
        sizeof( msgFinfos ) / sizeof( Finfo* ), // num Fields
        0
        // new Dinfo< Msg >()
    );
    return &msgCinfo;
}
References Cinfo::Cinfo(), getAdjacent(), getDestFieldsOnE1(), getDestFieldsOnE2(), getE1(), getE2(), getSrcFieldsOnE1(), getSrcFieldsOnE2(), Neutral::initCinfo(), ReadOnlyLookupValueFinfo< T, L, F >::ReadOnlyLookupValueFinfo(), and ReadOnlyValueFinfo< T, F >::ReadOnlyValueFinfo().
Referenced by DiagonalMsg::initCinfo(), OneToAllMsg::initCinfo(), OneToOneDataIndexMsg::initCinfo(), OneToOneMsg::initCinfo(), SingleMsg::initCinfo(), and SparseMsg::initCinfo().
initMsgManagers()
unsigned int Msg::initMsgManagers () static
Sets up the Element managers for each of the Msg classes
Definition at line 254 of file Msg.cpp.
{
    Dinfo< short > dummyDinfo;
    // This is to be the parent of all the msg managers.
    msgManagerId_ = Id::nextId();
    new GlobalDataElement(
        msgManagerId_, Neutral::initCinfo(), "Msgs", 1 );
    SingleMsg::managerId_ = Id::nextId();
    new MsgElement( SingleMsg::managerId_, SingleMsg::initCinfo(),
                    "singleMsg", &SingleMsg::numMsg, &SingleMsg::lookupMsg );
    OneToOneMsg::managerId_ = Id::nextId();
    new MsgElement( OneToOneMsg::managerId_, OneToOneMsg::initCinfo(),
                    "oneToOneMsg", &OneToOneMsg::numMsg, &OneToOneMsg::lookupMsg );
    OneToAllMsg::managerId_ = Id::nextId();
    new MsgElement( OneToAllMsg::managerId_, OneToAllMsg::initCinfo(),
                    "oneToAllMsg", &OneToAllMsg::numMsg, &OneToAllMsg::lookupMsg );
    DiagonalMsg::managerId_ = Id::nextId();
    new MsgElement( DiagonalMsg::managerId_, DiagonalMsg::initCinfo(),
                    "diagonalMsg", &DiagonalMsg::numMsg, &DiagonalMsg::lookupMsg );
    SparseMsg::managerId_ = Id::nextId();
    new MsgElement( SparseMsg::managerId_, SparseMsg::initCinfo(),
                    "sparseMsg", &SparseMsg::numMsg, &SparseMsg::lookupMsg );
    OneToOneDataIndexMsg::managerId_ = Id::nextId();
    new MsgElement( OneToOneDataIndexMsg::managerId_,
                    OneToOneDataIndexMsg::initCinfo(),
                    "oneToOneDataIndexMsg",
                    &OneToOneDataIndexMsg::numMsg,
                    &OneToOneDataIndexMsg::lookupMsg );
    // Do the 'adopt' only after all the message managers exist - we need
    // the OneToAll manager for the adoption messages themselves.
    assert( OneToAllMsg::numMsg() == 0 );
    unsigned int n = 1;
    Shell::adopt( Id(), msgManagerId_, n++ );
    Shell::adopt( msgManagerId_, SingleMsg::managerId_, n++ );
    Shell::adopt( msgManagerId_, OneToOneMsg::managerId_, n++ );
    Shell::adopt( msgManagerId_, OneToAllMsg::managerId_, n++ );
    Shell::adopt( msgManagerId_, DiagonalMsg::managerId_, n++ );
    Shell::adopt( msgManagerId_, SparseMsg::managerId_, n++ );
    return n;
}
References Shell::adopt(), GlobalDataElement::GlobalDataElement(), Id::Id(), DiagonalMsg::initCinfo(), OneToAllMsg::initCinfo(), OneToOneDataIndexMsg::initCinfo(), OneToOneMsg::initCinfo(), SingleMsg::initCinfo(), SparseMsg::initCinfo(), Neutral::initCinfo(), DiagonalMsg::lookupMsg(), OneToAllMsg::lookupMsg(), OneToOneDataIndexMsg::lookupMsg(), OneToOneMsg::lookupMsg(), SingleMsg::lookupMsg(), SparseMsg::lookupMsg(), DiagonalMsg::managerId_, OneToAllMsg::managerId_, OneToOneDataIndexMsg::managerId_, OneToOneMsg::managerId_, SingleMsg::managerId_, SparseMsg::managerId_, MsgElement::MsgElement(), msgManagerId_, Id::nextId(), DiagonalMsg::numMsg(), OneToAllMsg::numMsg(), OneToOneDataIndexMsg::numMsg(), OneToOneMsg::numMsg(), SingleMsg::numMsg(), and SparseMsg::numMsg().
Referenced by init(), and pymoose::initShell().
isForward()
bool Msg::isForward (const Element * src) const inline
Checks if the message is going forward. Now merged into Msg::addToQ for most cases.
Definition at line 144 of file Msg.h.
{
            return ( e1_ == src );
        }
References e1_.
isLastTrump()
bool Msg::isLastTrump () static
True when MOOSE has been terminated and is being cleaned up.
Definition at line 343 of file Msg.cpp.
{
    return lastTrump_;
}
References lastTrump_.
Referenced by Clock::~Clock().
lastMsg()
const Msg * Msg::lastMsg () static
Returns the most recently constructed msg.
Static utility function, provided so that the shell function doing message creation can retrieve the most recent message made.
Definition at line 338 of file Msg.cpp.
{
    return lastMsg_;
}
References lastMsg_.
mid()
ObjId Msg::mid () const inline
return the Msg Id.
Definition at line 106 of file Msg.h.
{
            return mid_;
        }
References mid_.
Referenced by addClockMsg(), Shell::adopt(), DiagonalMsg::copy(), OneToAllMsg::copy(), OneToOneDataIndexMsg::copy(), OneToOneMsg::copy(), SingleMsg::copy(), SparseMsg::copy(), Shell::doAddMsg(), Neutral::getIncomingMsgs(), Shell::innerAddMsg(), innerCopyMsgs(), Shell::innerMove(), FieldElementFinfoBase::postCreationFunc(), testCreateMsg(), testFibonacci(), testMsgField(), testMsgSrcDestFields(), testSendMsg(), testSendSpike(), testSharedMsg(), and testSparseMsg().
sources()
virtual void Msg::sources (vector< vector< Eref > > & v) const pure virtual
Return all the sources of e2 from e1, that is, all the msgs coming into specified entries on e2 from e1.
ALLDATA used when the sources include all data entries on a source. Indexing is v[dataId in range e2.numData][src list]
Implemented in DiagonalMsg, OneToAllMsg, OneToOneDataIndexMsg, OneToOneMsg, and SingleMsg.
Referenced by Element::getMsgTargetAndFunctions(), and Element::putTargetsInDigest().
targets()
virtual void Msg::targets (vector< vector< Eref > > & v) const pure virtual
Return all the targets of e1 on e2, that is, all the msgs going from specified entries on e1 to e2. ALLDATA used when the targets include all data entries on a target. Indexing is v[dataId in range e1.numData][tgt list]
Implemented in DiagonalMsg, OneToAllMsg, OneToOneDataIndexMsg, OneToOneMsg, and SingleMsg.
Referenced by Neutral::children(), Element::getMsgTargetAndFunctions(), Element::putTargetsInDigest(), and testSendMsg().
Member Data Documentation
e1_
Element* Msg::e1_ protected
Index of this Msg on the msg_ vector.
Definition at line 180 of file Msg.h.
Referenced by e1(), DiagonalMsg::firstTgt(), OneToAllMsg::firstTgt(), OneToOneDataIndexMsg::firstTgt(), OneToOneMsg::firstTgt(), SingleMsg::firstTgt(), SparseMsg::firstTgt(), getDestFieldsOnE1(), getDestFieldsOnE2(), getE1(), getSrcFieldsOnE1(), getSrcFieldsOnE2(), isForward(), Msg(), DiagonalMsg::sources(), OneToAllMsg::sources(), OneToOneDataIndexMsg::sources(), OneToOneMsg::sources(), SingleMsg::sources(), SparseMsg::sources(), DiagonalMsg::targets(), OneToAllMsg::targets(), OneToOneDataIndexMsg::targets(), OneToOneMsg::targets(), SingleMsg::targets(), SparseMsg::targets(), and ~Msg().
e2_
Element* Msg::e2_ protected
Element 1 attached to Msg.
Definition at line 181 of file Msg.h.
Referenced by e2(), DiagonalMsg::firstTgt(), OneToAllMsg::firstTgt(), OneToOneDataIndexMsg::firstTgt(), OneToOneMsg::firstTgt(), SingleMsg::firstTgt(), SparseMsg::firstTgt(), getDestFieldsOnE1(), getDestFieldsOnE2(), getE2(), getSrcFieldsOnE1(), getSrcFieldsOnE2(), Msg(), SparseMsg::randomConnect(), DiagonalMsg::sources(), OneToAllMsg::sources(), OneToOneDataIndexMsg::sources(), OneToOneMsg::sources(), SingleMsg::sources(), SparseMsg::sources(), DiagonalMsg::targets(), OneToAllMsg::targets(), OneToOneDataIndexMsg::targets(), OneToOneMsg::targets(), SingleMsg::targets(), SparseMsg::targets(), SparseMsg::updateAfterFill(), and ~Msg().
lastMsg_
const Msg * Msg::lastMsg_ = 0 static private
Definition at line 192 of file Msg.h.
Referenced by lastMsg(), and Msg().
lastTrump_
bool Msg::lastTrump_ = false static protected
Flag to indicate termination of program.
Definition at line 189 of file Msg.h.
Referenced by clearAllMsgs(), isLastTrump(), and ~Msg().
mid_
ObjId Msg::mid_ protected
Definition at line 178 of file Msg.h.
Referenced by getDestFieldsOnE1(), getDestFieldsOnE2(), getSrcFieldsOnE1(), getSrcFieldsOnE2(), mid(), Msg(), DiagonalMsg::~DiagonalMsg(), ~Msg(), OneToAllMsg::~OneToAllMsg(), OneToOneDataIndexMsg::~OneToOneDataIndexMsg(), OneToOneMsg::~OneToOneMsg(), SingleMsg::~SingleMsg(), and SparseMsg::~SparseMsg().
msgManagerId_
Id Msg::msgManagerId_ static protected
Element 2 attached to Msg.
Keeps track of the Id of the parent of all the MsgManager Elms.
Definition at line 186 of file Msg.h.
Referenced by initMsgManagers().
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/msg/Msg.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/msg/Msg.cpp