MOOSE - Multiscale Object Oriented Simulation Environment: SimpleLogger Class Reference
SimpleLogger Class Reference
#include <simple_logger.hpp>
Public Member Functions
void dump (string type, string msg, bool autoFormat=true)
Dumps a message to console.
string dumpStats (int which)
Dump statistics onto console.
bool isDir (const std::string &name)
Checks if given directory path exists on system.
std::string log (string type, const string &msg)
Compose a message and log to logging file.
template<typename A , typename B >
string mapToString (const map< A, B > &m, string title="") const
template<typename A , typename B >
void mapToXML (ostringstream &ss, const map< A, B > &m, const char *tagName, unsigned indent) const
Converts a map to XML like staructure.
string save (const char *outFile="")
Convert this logger to XML.
SimpleLogger ()
Constructor of logger. The wrapper script of moose must make sure that $HOME/.moose is created. The logger will write to $HOME/.moose/log.
const std::string timeStamp ()
Get current timestamp.
void updateGlobalCount (string type)
When an element is created in moose, log its presense in this map.
~SimpleLogger ()
Public Attributes
vector< float > creationTime
string endTime
string homeDir
vector< float > initializationTime
ostringstream logSS
string mooseDir
string outputFile
vector< float > simulationTime
string startTime
Private Attributes
map< string, unsigned long > elementsMap
map< string, float > timekeeperMap
Detailed Description
Definition at line 69 of file simple_logger.hpp.
Constructor & Destructor Documentation
SimpleLogger()
SimpleLogger::SimpleLogger () inline
Constructor of logger. The wrapper script of moose must make sure that $HOME/.moose is created. The logger will write to $HOME/.moose/log.
Definition at line 78 of file simple_logger.hpp.
        {
            startTime = timeStamp();
            homeDir = getenv("HOME");
            logSS << "<log simulator=\"moose\">" << endl;
            logSS << "\t<start_time>" << startTime << "</start_time>" << endl;
            logSS << "\t<messages>" << endl;
#ifdef OS_WINDOWS
            outputFile = homeDir + "\\.moose\\log";
#else
            outputFile = homeDir + "/.moose/log";
#endif
        }
References homeDir, logSS, outputFile, startTime, and timeStamp().
~SimpleLogger()
SimpleLogger::~SimpleLogger () inline
Definition at line 94 of file simple_logger.hpp.
        {
        }
Member Function Documentation
dump()
void SimpleLogger::dump (string type, string msg, bool autoFormat = true) inline
Dumps a message to console.
Parameters
type Type of message e.g. WARN, ERROR, FATAL etc.
msg Message to dump.
autoFormat Use ` to demarcate coloring of output.
Definition at line 279 of file simple_logger.hpp.
        {
#if VERBOSITY < 0
            return;
#endif
            stringstream ss;
            ss.precision( 12 );
            ss << "[" << type << "] ";
            bool set = false;
            bool reset = true;
            string color = T_GREEN;
            if(type == "WARNING" || type == "WARN" || type == "FIXME")
                color = T_YELLOW;
            else if(type == "DEBUG")
                color = T_CYAN;
            else if(type == "ERROR" || type == "FAIL" || type == "FATAL" || type == "ASSERT_FAILURE")
                color = T_RED;
            else if(type == "INFO" || type == "EXPECT_FAILURE")
                color = T_MAGENTA;
            else if(type == "LOG")
                color = T_BLUE;
            for(unsigned int i = 0; i < msg.size(); ++i)
            {
                if('`' == msg[i])
                {
                    if(!set and reset)
                    {
                        set = true;
                        reset = false;
                        ss << color;
                    }
                    else if(set && !reset)
                    {
                        reset = true;
                        set = false;
                        ss << T_RESET;
                    }
                }
                else if('\n' == msg[i])
                    ss << "\n + ";
                else
                    ss << msg[i];
            }
            /*  Be safe than sorry */
            if(!reset)
                ss << T_RESET;
            logSS << ss.str() << endl;
            cerr << ss.str() << endl;
        }
References logSS.
dumpStats()
string SimpleLogger::dumpStats (int which) inline
Dump statistics onto console.
Parameters
which If which is 0 then print elements inside moose, if it is 1 then print total time taken during simulation.
Returns
Definition at line 159 of file simple_logger.hpp.
        {
            stringstream ss;
            // unsigned width = 50;
            ss << endl;
            if(which == 0)
                ss << mapToString<string, unsigned long>(elementsMap, "data_structure");
            else if( which == 1)
            {
                timekeeperMap["Simulation"] = accumulate(
                        simulationTime.begin()
                        , simulationTime.end()
                        , 0.0
                        );
                timekeeperMap["Initialization"] = accumulate(
                        initializationTime.begin()
                        , initializationTime.end()
                        , 0.0
                        );
                timekeeperMap["Creation"] = accumulate(
                        creationTime.begin()
                        , creationTime.end()
                        , 0.0
                        );
                ss << mapToString<string, float>( timekeeperMap, "simulation_stats" );
            }
            return ss.str();
        }
References creationTime, elementsMap, initializationTime, mapToString(), simulationTime, and timekeeperMap.
isDir()
bool SimpleLogger::isDir (const std::string & name) inline
Checks if given directory path exists on system.
Parameters
name Directory path as string.
Returns
true, if directory exists, false otherwise.
Definition at line 257 of file simple_logger.hpp.
        {
#ifdef OS_WINDOWS
            struct _stat buf;
            int result = _stat( name.c_str(), &buf );
#else
            struct stat buf;
            int result = stat( name.c_str(), &buf );
#endif
            if(result == 0 && S_ISDIR(buf.st_mode))
                return true;
            else
                return false;
        }
log()
std::string SimpleLogger::log (string type, const string & msg) inline
Compose a message and log to logging file.
Parameters
type
msg
level
Returns
Definition at line 344 of file simple_logger.hpp.
        {
#ifdef ENABLE_LOGGER
            stringstream ss;
            string time = timeStamp();
            fstream logF;
            logF.open(outputFile.c_str(), std::fstream::out | std::fstream::app);
            ss << "<" << type << " time=\"" << time << "\">";
            ss << msg << "</" << type << ">" << endl;
            logF << ss.str();
            logF.close();
            string newmsg = ss.str();
            return newmsg;
#else
            return string("");
#endif
        }
mapToString()
template<typename A , typename B > string SimpleLogger::mapToString (const map< A, B > & m, string title = "") const inline
Definition at line 130 of file simple_logger.hpp.
        {
            unsigned width = 50;
            stringstream ss;
            ss << title;
            for(unsigned i = 0; i < width - title.size(); ++i)
                ss << "~";
            ss << endl;
            typename map<A, B>::const_iterator it;
            for( it = m.begin(); it != m.end(); it++)
                ss << setw(width/2) << it->first << setw(width/2) << it->second << endl;
            for(unsigned i = 0; i < width; ++i)
                ss << "=";
            ss << endl;
            return ss.str();
        }
Referenced by dumpStats().
mapToXML()
template<typename A , typename B > void SimpleLogger::mapToXML (ostringstream & ss, const map< A, B > & m, const char * tagName, unsigned indent) const inline
Converts a map to XML like staructure.
Template Parameters
A
B
Parameters
ss Input ostringstream.
m std::map
tagName This is current tag name. Useful when recursing.
indent Usually a tag character.
Definition at line 202 of file simple_logger.hpp.
        {
            string prefix = "";
            for(unsigned int i = 0; i < indent; ++i)
                prefix += "\t";
            ss << prefix << "<" << tagName << ">" << endl;
            typename map<A, B>::const_iterator it;
            for(it = m.begin(); it != m.end(); it++)
            {
                ss << prefix << prefix
                    << "<" << it->first << ">"
                    << it->second
                    << "</" << it->first << ">" << endl;
            }
            ss << prefix << "</" << tagName << ">" << endl;
        }
Referenced by save().
save()
string SimpleLogger::save (const char * outFile = "") inline
Convert this logger to XML.
Returns
A XML string.
Definition at line 227 of file simple_logger.hpp.
        {
            string logFile = string(outFile);
            if(logFile.size() == 0)
                logFile = outputFile;
            // End of messages.
            logSS << "\t</messages>" << endl;
            mapToXML<string, unsigned long>(logSS, elementsMap, "data_structure", 1);
            mapToXML<string, float>(logSS, timekeeperMap, "times", 1);
            logSS << "\t<end_time>" << timeStamp() << "</end_time>" << endl;
            logSS << "</log>" << endl;
            fstream logF;
            logF.open(logFile.c_str(), std::fstream::out | std::fstream::app);
            logF << logSS.str();
            logF.close();
            return logSS.str();
        }
References elementsMap, logSS, mapToXML(), outputFile, timekeeperMap, and timeStamp().
timeStamp()
const std::string SimpleLogger::timeStamp () inline
Get current timestamp.
Returns
A string represeting current timestamp.
Definition at line 104 of file simple_logger.hpp.
        {
            time_t     now = time(0);
            struct tm  tstruct;
            char       buf[80];
            tstruct = *localtime(&now);
            strftime(buf, sizeof(buf), "%Y-%m-%d.%X", &tstruct);
            return buf;
        }
Referenced by save(), and SimpleLogger().
updateGlobalCount()
void SimpleLogger::updateGlobalCount (string type) inline
When an element is created in moose, log its presense in this map.
Parameters
type Type of element.
path Path of the element.
Definition at line 121 of file simple_logger.hpp.
        {
            if(elementsMap.find(type) == elementsMap.end())
                elementsMap[type] = 1;
            else
                elementsMap[type] = elementsMap[type] + 1;
        }
References elementsMap.
Member Data Documentation
creationTime
vector<float> SimpleLogger::creationTime
Definition at line 382 of file simple_logger.hpp.
Referenced by dumpStats().
elementsMap
map<string, unsigned long> SimpleLogger::elementsMap private
Definition at line 365 of file simple_logger.hpp.
Referenced by dumpStats(), save(), and updateGlobalCount().
endTime
string SimpleLogger::endTime
Definition at line 375 of file simple_logger.hpp.
homeDir
string SimpleLogger::homeDir
Definition at line 371 of file simple_logger.hpp.
Referenced by SimpleLogger().
initializationTime
vector<float> SimpleLogger::initializationTime
Definition at line 381 of file simple_logger.hpp.
Referenced by dumpStats().
logSS
ostringstream SimpleLogger::logSS
Definition at line 377 of file simple_logger.hpp.
Referenced by dump(), save(), and SimpleLogger().
mooseDir
string SimpleLogger::mooseDir
Definition at line 370 of file simple_logger.hpp.
outputFile
string SimpleLogger::outputFile
Definition at line 373 of file simple_logger.hpp.
Referenced by save(), and SimpleLogger().
simulationTime
vector<float> SimpleLogger::simulationTime
Definition at line 380 of file simple_logger.hpp.
Referenced by dumpStats().
startTime
string SimpleLogger::startTime
Definition at line 374 of file simple_logger.hpp.
Referenced by SimpleLogger().
timekeeperMap
map<string, float> SimpleLogger::timekeeperMap private
Definition at line 366 of file simple_logger.hpp.
Referenced by dumpStats(), and save().
The documentation for this class was generated from the following file:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/utility/simple_logger.hpp