MOOSE - Multiscale Object Oriented Simulation Environment: PreSynEvent Class Reference
PreSynEvent Class Reference
#include <SynEvent.h>
Public Member Functions
PreSynEvent ()
PreSynEvent (unsigned int i, double t, double w)
Public Member Functions inherited from SynEvent
SynEvent ()
SynEvent (double t, double w)
Public Attributes
unsigned int synIndex
Public Attributes inherited from SynEvent
double time
double weight
Detailed Description
Definition at line 38 of file SynEvent.h.
Constructor & Destructor Documentation
PreSynEvent() [1/2]
PreSynEvent::PreSynEvent () inline
Definition at line 41 of file SynEvent.h.
            : SynEvent(),   // call the parent constructor with default args
                            // by default calls without args, so no need really
              synIndex( 0 )
        {}
References SynEvent::SynEvent(), and synIndex.
PreSynEvent() [2/2]
PreSynEvent::PreSynEvent (unsigned int i, double t, double w) inline
Definition at line 47 of file SynEvent.h.
            : SynEvent(t,w),// call the parent constructor with given args
              synIndex( i )
        {;}
References SynEvent::SynEvent(), and synIndex.
Referenced by GraupnerBrunel2012CaPlasticitySynHandler::addSpike(), SeqSynHandler::addSpike(), and STDPSynHandler::addSpike().
Member Data Documentation
synIndex
unsigned int PreSynEvent::synIndex
Definition at line 52 of file SynEvent.h.
Referenced by PreSynEvent(), PreSynEvent(), GraupnerBrunel2012CaPlasticitySynHandler::vProcess(), SeqSynHandler::vProcess(), and STDPSynHandler::vProcess().
The documentation for this class was generated from the following file:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/synapse/SynEvent.h