MOOSE - Multiscale Object Oriented Simulation Environment: Nernst Class Reference
Nernst Class Reference
#include <Nernst.h>
Public Member Functions
double getCin () const
double getCout () const
double getE () const
double getScale () const
double getTemperature () const
int getValence () const
void handleCin (const Eref &e, double conc)
void handleCout (const Eref &e, double conc)
Nernst ()
void setCin (double value)
void setCout (double value)
void setScale (double value)
void setTemperature (double value)
void setValence (int value)
Static Public Member Functions
static const Cinfo * initCinfo ()
Private Member Functions
void updateE ()
Private Attributes
double Cin_
double Cout_
double E_
double factor_
double scale_
double Temperature_
int valence_
Static Private Attributes
static const double R_OVER_F = 8.6171458e-5
static const double ZERO_CELSIUS = 273.15
Detailed Description
This class does the Nernst equation calculations
Definition at line 16 of file Nernst.h.
Constructor & Destructor Documentation
Nernst()
Nernst::Nernst ()
Definition at line 118 of file Nernst.cpp.
    :
        E_( 0.0 ),
        Temperature_( 295 ),
        valence_( 1 ),
        Cin_( 1.0 ),
        Cout_( 1.0 ),
        scale_( 1.0 ),
        factor_( scale_ * R_OVER_F * Temperature_ / valence_ )
{;}
References Cin_, Cout_, E_, factor_, R_OVER_F, scale_, Temperature_, and valence_.
Member Function Documentation
getCin()
double Nernst::getCin () const
Definition at line 168 of file Nernst.cpp.
{
    return Cin_;
}
References Cin_.
Referenced by initCinfo().
getCout()
double Nernst::getCout () const
Definition at line 177 of file Nernst.cpp.
{
    return Cout_;
}
References Cout_.
Referenced by initCinfo().
getE()
double Nernst::getE () const
Definition at line 132 of file Nernst.cpp.
{
    return E_;
}
References E_.
Referenced by initCinfo().
getScale()
double Nernst::getScale () const
Definition at line 187 of file Nernst.cpp.
{
    return scale_;
}
References scale_.
Referenced by initCinfo().
getTemperature()
double Nernst::getTemperature () const
Definition at line 145 of file Nernst.cpp.
{
    return Temperature_;
}
References Temperature_.
Referenced by initCinfo().
getValence()
int Nernst::getValence () const
Definition at line 158 of file Nernst.cpp.
{
    return valence_;
}
References valence_.
Referenced by initCinfo().
handleCin()
void Nernst::handleCin (const Eref & e, double conc)
Definition at line 201 of file Nernst.cpp.
{
    Cin_ = conc;
    updateE();
    Eout()->send( er, E_ );
}
References Cin_, E_, Eout(), SrcFinfo1< T >::send(), and updateE().
Referenced by initCinfo().
handleCout()
void Nernst::handleCout (const Eref & e, double conc)
Definition at line 208 of file Nernst.cpp.
{
    Cout_ = conc;
    updateE();
    Eout()->send( er, E_ );
}
References Cout_, E_, Eout(), SrcFinfo1< T >::send(), and updateE().
Referenced by initCinfo().
initCinfo()
const Cinfo * Nernst::initCinfo () static
Definition at line 26 of file Nernst.cpp.
{
    static ReadOnlyValueFinfo< Nernst, double > E( "E",
        "Computed reversal potential",
            &Nernst::getE
    );
    static ValueFinfo< Nernst, double > temperature( "Temperature",
        "Temperature of cell",
        &Nernst::setTemperature,
        &Nernst::getTemperature
    );
    static ValueFinfo< Nernst, int > valence( "valence",
        "Valence of ion in Nernst calculation",
        &Nernst::setValence,
        &Nernst::getValence
    );
    static ValueFinfo< Nernst, double > Cin( "Cin",
        "Internal conc of ion",
        &Nernst::setCin,
        &Nernst::getCin
    );
    static ValueFinfo< Nernst, double > Cout( "Cout",
        "External conc of ion",
        &Nernst::setCout,
        &Nernst::getCout
    );
    static ValueFinfo< Nernst, double > scale( "scale",
        "Voltage scale factor",
        &Nernst::setScale,
        &Nernst::getScale
    );
    // Shared definitions
    // MsgDest definitions
    // These differ from field assignments because they trigger an
    // outgoing msg with the updated E.
    static DestFinfo ci( "ci",
        "Set internal conc of ion, and immediately send out the updated E",
        new EpFunc1< Nernst, double >( &Nernst::handleCin )
    );
    static DestFinfo co( "co",
        "Set external conc of ion, and immediately send out the updated E",
        new EpFunc1< Nernst, double >( &Nernst::handleCout )
    );
    // Field definitions
    static Finfo* NernstFinfos[] =
    {
        Eout(),     // SrcFinfo
        &E,         // ReadOnlyValue
        &temperature,   // Value
        &valence,       // Value
        &Cin,       // Value
        &Cout,      // Value
        &scale,     // Value
        &ci,        // Dest
        &co,        // Dest
    };
    static string doc[] =
    {
        "Name", "Nernst",
        "Author", "Upinder S. Bhalla, 2007, NCBS",
        "Description", "Nernst: Calculates Nernst potential for a given ion based on "
                "Cin and Cout, the inside and outside concentrations. "
                "Immediately sends out the potential to all targets.",
    };
    static Dinfo< Nernst > dinfo;
    static const Cinfo NernstCinfo(
        "Nernst",
        Neutral::initCinfo(),
        NernstFinfos,
        sizeof( NernstFinfos ) / sizeof(Finfo *),
        &dinfo,
        doc,
        sizeof( doc ) / sizeof( string )
    );
    return &NernstCinfo;
}
References Cinfo::Cinfo(), DestFinfo::DestFinfo(), Eout(), EpFunc1< T, A >::EpFunc1(), getCin(), getCout(), getE(), getScale(), getTemperature(), getValence(), handleCin(), handleCout(), Neutral::initCinfo(), ReadOnlyValueFinfo< T, F >::ReadOnlyValueFinfo(), setCin(), setCout(), setScale(), setTemperature(), setValence(), and ValueFinfo< T, F >::ValueFinfo().
setCin()
void Nernst::setCin (double value)
Definition at line 163 of file Nernst.cpp.
{
    Cin_ = value;
    updateE();
}
References Cin_, and updateE().
Referenced by initCinfo().
setCout()
void Nernst::setCout (double value)
Definition at line 173 of file Nernst.cpp.
{
    Cout_ = value;
    updateE();
}
References Cout_, and updateE().
Referenced by initCinfo().
setScale()
void Nernst::setScale (double value)
Definition at line 182 of file Nernst.cpp.
{
    scale_ = value;
    factor_ = scale_ * R_OVER_F * Temperature_ / valence_;
    updateE();
}
References factor_, R_OVER_F, scale_, Temperature_, updateE(), and valence_.
Referenced by initCinfo().
setTemperature()
void Nernst::setTemperature (double value)
Definition at line 137 of file Nernst.cpp.
{
    if ( value > 0.0 ) {
        Temperature_ = value;
        factor_ = scale_ * R_OVER_F * Temperature_ / valence_;
    }
    updateE();
}
References factor_, R_OVER_F, scale_, Temperature_, updateE(), and valence_.
Referenced by initCinfo().
setValence()
void Nernst::setValence (int value)
Definition at line 150 of file Nernst.cpp.
{
    if ( value != 0 ) {
        valence_ = value;
    }
    factor_ = scale_ * R_OVER_F * Temperature_ / valence_;
    updateE();
}
References factor_, R_OVER_F, scale_, Temperature_, updateE(), and valence_.
Referenced by initCinfo().
updateE()
void Nernst::updateE () private
Definition at line 196 of file Nernst.cpp.
{
    E_ = factor_ * log( Cout_ / Cin_ );
}
References Cin_, Cout_, E_, and factor_.
Referenced by handleCin(), handleCout(), setCin(), setCout(), setScale(), setTemperature(), and setValence().
Member Data Documentation
Cin_
double Nernst::Cin_ private
Definition at line 54 of file Nernst.h.
Referenced by getCin(), handleCin(), Nernst(), setCin(), and updateE().
Cout_
double Nernst::Cout_ private
Definition at line 55 of file Nernst.h.
Referenced by getCout(), handleCout(), Nernst(), setCout(), and updateE().
E_
double Nernst::E_ private
Definition at line 51 of file Nernst.h.
Referenced by getE(), handleCin(), handleCout(), Nernst(), and updateE().
factor_
double Nernst::factor_ private
Definition at line 57 of file Nernst.h.
Referenced by Nernst(), setScale(), setTemperature(), setValence(), and updateE().
R_OVER_F
const double Nernst::R_OVER_F = 8.6171458e-5 static private
Definition at line 58 of file Nernst.h.
Referenced by Nernst(), setScale(), setTemperature(), and setValence().
scale_
double Nernst::scale_ private
Definition at line 56 of file Nernst.h.
Referenced by getScale(), Nernst(), setScale(), setTemperature(), and setValence().
Temperature_
double Nernst::Temperature_ private
Definition at line 52 of file Nernst.h.
Referenced by getTemperature(), Nernst(), setScale(), setTemperature(), and setValence().
valence_
int Nernst::valence_ private
Definition at line 53 of file Nernst.h.
Referenced by getValence(), Nernst(), setScale(), setTemperature(), and setValence().
ZERO_CELSIUS
const double Nernst::ZERO_CELSIUS = 273.15 static private
Definition at line 59 of file Nernst.h.
The documentation for this class was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/biophysics/Nernst.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/biophysics/Nernst.cpp