MOOSE - Multiscale Object Oriented Simulation Environment: /home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/scheduling/Clock.cpp File Reference
Clock.cpp File Reference
#include "../basecode/header.h"
#include "../utility/print_function.hpp"
#include "Clock.h"
Functions
static vector< SrcFinfo1< ProcPtr > * > buildProcessVec (const string &name)
static SrcFinfo0 * finished ()
static vector< SrcFinfo1< ProcPtr > * > & processVec ()
static vector< SrcFinfo1< ProcPtr > * > & reinitVec ()
static vector< SharedFinfo * > & sharedProcVec ()
Variables
static const Cinfo * clockCinfo = Clock::initCinfo()
const double minimumDt = 1e-7
minimumDt is smaller than any known event on the scales MOOSE handles.
Function Documentation
buildProcessVec()
static vector< SrcFinfo1< ProcPtr > * > buildProcessVec (const string & name) static
Definition at line 80 of file Clock.cpp.
{
    vector< SrcFinfo1< ProcPtr >* > vec;
    vec.resize( Clock::numTicks );
    for ( unsigned int i = 0; i < Clock::numTicks; ++i )
    {
        stringstream ss;
        ss << name << i;
        stringstream ss2;
        ss2 << name << " for Tick " << i;
        vec[i] = new SrcFinfo1< ProcPtr >( ss.str(), ss2.str() );
    }
    return vec;
}
References Clock::numTicks, and SrcFinfo1< T >::SrcFinfo1().
Referenced by processVec(), and reinitVec().
finished()
static SrcFinfo0 * finished () static
Definition at line 70 of file Clock.cpp.
{
    static SrcFinfo0 finished(
        "finished",
        "Signal for completion of run"
    );
    return &finished;
}
References SrcFinfo0::SrcFinfo0().
Referenced by Clock::handleStep(), and Clock::initCinfo().
processVec()
static vector< SrcFinfo1< ProcPtr > * > & processVec () static
Definition at line 97 of file Clock.cpp.
{
    static vector< SrcFinfo1< ProcPtr >* > processVec =
        buildProcessVec( "process" );
    return processVec;
}
References buildProcessVec().
Referenced by Clock::buildTicks(), Clock::handleStep(), sharedProcVec(), and Clock::~Clock().
reinitVec()
static vector< SrcFinfo1< ProcPtr > * > & reinitVec () static
Definition at line 104 of file Clock.cpp.
{
    static vector< SrcFinfo1< ProcPtr >* > reinitVec =
        buildProcessVec( "reinit" );
    return reinitVec;
}
References buildProcessVec().
Referenced by Clock::handleReinit(), sharedProcVec(), and Clock::~Clock().
sharedProcVec()
static vector< SharedFinfo * > & sharedProcVec () static
Definition at line 111 of file Clock.cpp.
{
    static vector< SharedFinfo* > vec;
    if ( vec.size() == 0 )
    {
        vec.resize( Clock::numTicks );
        for ( unsigned int i = 0; i < Clock::numTicks; ++i )
        {
            stringstream ss;
            Finfo* temp[2];
            temp[0] = processVec()[i];
            temp[1] = reinitVec()[i];
            ss << "proc" << i;
            vec[i] = new SharedFinfo( ss.str(),
                                      "Shared process/reinit message",
                                      temp, 2 );
        }
    }
    return vec;
}
References Clock::numTicks, processVec(), reinitVec(), and SharedFinfo::SharedFinfo().
Referenced by Clock::initCinfo(), and Clock::~Clock().
Variable Documentation
clockCinfo
const Cinfo* clockCinfo = Clock::initCinfo() static
Definition at line 448 of file Clock.cpp.
minimumDt
const double minimumDt = 1e-7
minimumDt is smaller than any known event on the scales MOOSE handles.
Definition at line 62 of file Clock.cpp.
Referenced by Clock::setTickDt().