MOOSE - Multiscale Object Oriented Simulation Environment: /home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/biophysics/CompartmentBase.cpp File Reference
CompartmentBase.cpp File Reference
#include "../basecode/header.h"
#include "../basecode/ElementValueFinfo.h"
#include "CompartmentBase.h"
#include "CompartmentDataHolder.h"
#include "../shell/Wildcard.h"
Functions
static SrcFinfo1< double > * axialOut ()
static bool hasScaleFormula (const Eref &e)
static SrcFinfo2< double, double > * raxialOut ()
Variables
static const Cinfo * compartmentBaseCinfo = CompartmentBase::initCinfo()
static const double RANGE = 4.0e-17
Function Documentation
axialOut()
static SrcFinfo1< double > * axialOut () static
Definition at line 36 of file CompartmentBase.cpp.
{
    static SrcFinfo1< double > axialOut( "axialOut",
        "Sends out Vm value of compartment to adjacent compartments,"
        "on each timestep" );
    return &axialOut;
}
References SrcFinfo1< T >::SrcFinfo1().
Referenced by moose::CompartmentBase::initCinfo().
hasScaleFormula()
static bool hasScaleFormula (const Eref & e) static
Definition at line 666 of file CompartmentBase.cpp.
{
    vector< Id > kids;
    Neutral::children( e, kids );
    for ( vector< Id >::iterator j = kids.begin(); j != kids.end(); j++ )
        if ( j->element()->getName() == "scaleFormula" )
            return true;
    return false;
}
References Neutral::children(), Id::element(), and Element::getName().
Referenced by moose::CompartmentBase::setGeomAndElec().
raxialOut()
static SrcFinfo2< double, double > * raxialOut () static
Definition at line 43 of file CompartmentBase.cpp.
{
    static SrcFinfo2< double, double > raxialOut( "raxialOut",
        "Sends out Raxial information on each timestep, "
        "fields are Ra and Vm" );
    return &raxialOut;
}
References SrcFinfo2< T1, T2 >::SrcFinfo2().
Referenced by moose::CompartmentBase::initCinfo().
Variable Documentation
compartmentBaseCinfo
const Cinfo* compartmentBaseCinfo = CompartmentBase::initCinfo() static
Definition at line 364 of file CompartmentBase.cpp.
RANGE
const double RANGE = 4.0e-17 static
Definition at line 16 of file CompartmentBase.cpp.
Referenced by moose::CompartmentBase::rangeWarning().