MOOSE - Multiscale Object Oriented Simulation Environment: /home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/kinetics/ConcChan.cpp File Reference
ConcChan.cpp File Reference
#include "../basecode/header.h"
#include "ConcChan.h"
Functions
static SrcFinfo2< double, double > * inPoolOut ()
static SrcFinfo2< double, double > * outPoolOut ()
Variables
static const Cinfo * concChanCinfo = ConcChan::initCinfo()
Function Documentation
inPoolOut()
static SrcFinfo2< double, double > * inPoolOut () static
Definition at line 13 of file ConcChan.cpp.
{
    static SrcFinfo2< double, double > inPoolOut(
            "inPoolOut",
            "Sends out increment to molecules on inside of membrane"
            );
    return &inPoolOut;
}
References SrcFinfo2< T1, T2 >::SrcFinfo2().
Referenced by ConcChan::initCinfo().
outPoolOut()
static SrcFinfo2< double, double > * outPoolOut () static
Definition at line 21 of file ConcChan.cpp.
{
    static SrcFinfo2< double, double > outPoolOut(
            "outPoolOut",
            "Sends out increment to molecules on outside of membrane"
            );
    return &outPoolOut;
}
References SrcFinfo2< T1, T2 >::SrcFinfo2().
Referenced by ConcChan::initCinfo().
Variable Documentation
concChanCinfo
const Cinfo* concChanCinfo = ConcChan::initCinfo() static
Definition at line 128 of file ConcChan.cpp.