MOOSE - Multiscale Object Oriented Simulation Environment: /home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/mesh/CubeMesh.cpp File Reference
CubeMesh.cpp File Reference
#include "../basecode/header.h"
#include "../basecode/SparseMatrix.h"
#include "../basecode/ElementValueFinfo.h"
#include "Boundary.h"
#include "MeshEntry.h"
#include "VoxelJunction.h"
#include "ChemCompt.h"
#include "MeshCompt.h"
#include "CubeMesh.h"
#include "EndoMesh.h"
Typedefs
typedef pair< unsigned int, unsigned int > PII
Functions
void checkAbut (const vector< PII > &intersect, unsigned int ix, unsigned int iy, unsigned int iz, unsigned int nx, unsigned int ny, unsigned int nz, unsigned int meshIndex, vector< VoxelJunction > &ret)
void setAbut (PII &voxel, unsigned int meshIndex, unsigned int axis)
void setIntersectVoxel (vector< PII > &intersect, unsigned int ix, unsigned int iy, unsigned int iz, unsigned int nx, unsigned int ny, unsigned int nz, unsigned int meshIndex)
void swapIfBackward (double &x0, double &x1)
Variables
static const Cinfo * cubeMeshCinfo = CubeMesh::initCinfo()
Typedef Documentation
PII
typedef pair< unsigned int, unsigned int > PII
Definition at line 29 of file CubeMesh.cpp.
Function Documentation
checkAbut()
void checkAbut (const vector< PII > & intersect, unsigned int ix, unsigned int iy, unsigned int iz, unsigned int nx, unsigned int ny, unsigned int nz, unsigned int meshIndex, vector< VoxelJunction > & ret)
checkAbut checks the intersect vector for the current position ix, iy, iz, to determine how many diffusion terms to extract. It then puts each of the extracted terms into the ret vector. There is a minor efficiency for one and two diffusion terms as they are encoded within the intersect vector. Higher-order surface alignments require an in-line scan of neighboring voxels. In all casesl the function inserts a flag indicating surface direction into the diffScale field of the VoxelJunction. 0 = x; 1 = y; 2 = z.
Definition at line 1390 of file CubeMesh.cpp.
{
    unsigned int index = ( iz * ny + iy ) * nx + ix;
    unsigned int localFlag = intersect[index].second;
    if ( localFlag == CubeMesh::EMPTY || localFlag == CubeMesh::SURFACE )
        return; // Nothing to put into the ret vector
    if ( localFlag == CubeMesh::ABUTX )
    {
        ret.push_back(
            VoxelJunction( intersect[index].first, meshIndex, 0 ));
    }
    else if ( localFlag == CubeMesh::ABUTY )
    {
        ret.push_back(
            VoxelJunction( intersect[index].first, meshIndex, 1 ));
    }
    else if ( localFlag == CubeMesh::ABUTZ )
    {
        ret.push_back(
            VoxelJunction( intersect[index].first, meshIndex, 2 ));
    }
    else if ( localFlag == CubeMesh::MULTI )     // go through all 6 cases.
    {
        if ( ix > 0 )
        {
            index = ( iz * ny + iy ) * nx + ix - 1;
            if ( intersect[index].second == CubeMesh::SURFACE )
                ret.push_back(
                    VoxelJunction( intersect[index].first, meshIndex, 0 ));
        }
        if ( ix + 1 < nx )
        {
            index = ( iz * ny + iy ) * nx + ix + 1;
            if ( intersect[index].second == CubeMesh::SURFACE )
                ret.push_back(
                    VoxelJunction( intersect[index].first, meshIndex, 0 ));
        }
        if ( iy > 0 )
        {
            index = ( iz * ny + iy -1 ) * nx + ix;
            if ( intersect[index].second == CubeMesh::SURFACE )
                ret.push_back(
                    VoxelJunction( intersect[index].first, meshIndex, 1 ));
        }
        if ( iy + 1 < ny )
        {
            index = ( iz * ny + iy + 1 ) * nx + ix;
            if ( intersect[index].second == CubeMesh::SURFACE )
                ret.push_back(
                    VoxelJunction( intersect[index].first, meshIndex, 1 ));
        }
        if ( iz > 0 )
        {
            index = ( (iz-1) * ny + iy ) * nx + ix;
            if ( intersect[index].second == CubeMesh::SURFACE )
                ret.push_back(
                    VoxelJunction( intersect[index].first, meshIndex, 2 ));
        }
        if ( iz + 1 < nz )
        {
            index = ( (iz+1) * ny + iy ) * nx + ix;
            if ( intersect[index].second == CubeMesh::SURFACE )
                ret.push_back(
                    VoxelJunction( intersect[index].first, meshIndex, 2 ));
        }
    }
}
References CubeMesh::ABUTX, CubeMesh::ABUTY, CubeMesh::ABUTZ, CubeMesh::EMPTY, CubeMesh::MULTI, CubeMesh::SURFACE, and VoxelJunction::VoxelJunction().
Referenced by CubeMesh::matchCubeMeshEntries(), and testIntersectVoxel().
setAbut()
void setAbut (PII & voxel, unsigned int meshIndex, unsigned int axis)
The intersect pairs are always meshIndex in first, and a flag in the second. The flag can be: EMPTY: empty SURFACE: on the surface ABUT[X,Y,Z]: One place removed from the surface, only one entry MULTI: Multiple surface voxels are only one place removed from here. a number: Special case where 2 surface voxels abut. The number is the meshIndex of the second surface voxel. setAbut assigns the voxel flags based on what was already there
Definition at line 1336 of file CubeMesh.cpp.
{
    if ( voxel.second == CubeMesh::SURFACE ) // Don't touch surface voxels.
        return;
    if ( voxel.second == CubeMesh::EMPTY )
        voxel = PII( meshIndex, axis );
    else // 1 or more indices are already here.
        voxel.second = CubeMesh::MULTI;
}
References CubeMesh::EMPTY, CubeMesh::MULTI, and CubeMesh::SURFACE.
Referenced by setIntersectVoxel().
setIntersectVoxel()
void setIntersectVoxel (vector< PII > & intersect, unsigned int ix, unsigned int iy, unsigned int iz, unsigned int nx, unsigned int ny, unsigned int nz, unsigned int meshIndex)
Definition at line 1346 of file CubeMesh.cpp.
{
    assert( ix < nx && iy < ny && iz < nz );
    unsigned int index = ( iz * ny + iy ) * nx + ix;
    assert( index < intersect.size() );
    intersect[index] = PII( meshIndex, CubeMesh::SURFACE );
    if ( ix > 0 )
        setAbut( intersect[ (iz*ny + iy) * nx + ix-1 ], meshIndex,
                 CubeMesh::ABUTX );
    if ( ix + 1 < nx )
        setAbut( intersect[ (iz*ny + iy) * nx + ix+1 ], meshIndex,
                 CubeMesh::ABUTX );
    if ( iy > 0 )
        setAbut( intersect[ ( iz*ny + iy-1 ) * nx + ix ], meshIndex,
                 CubeMesh::ABUTY);
    if ( iy + 1 < ny )
        setAbut( intersect[ ( iz*ny + iy+1 ) * nx + ix ], meshIndex,
                 CubeMesh::ABUTY);
    if ( iz > 0 )
        setAbut( intersect[ ( (iz-1)*ny + iy ) * nx + ix ], meshIndex,
                 CubeMesh::ABUTZ);
    if ( iz + 1 < nz )
        setAbut( intersect[ ( (iz+1)*ny + iy ) * nx + ix ], meshIndex,
                 CubeMesh::ABUTZ);
}
References CubeMesh::ABUTX, CubeMesh::ABUTY, CubeMesh::ABUTZ, setAbut(), and CubeMesh::SURFACE.
Referenced by CubeMesh::assignVoxels(), and testIntersectVoxel().
swapIfBackward()
void swapIfBackward (double & x0, double & x1)
Definition at line 295 of file CubeMesh.cpp.
{
    if ( x0 > x1 )
    {
        double temp = x0;
        x0 = x1;
        x1 = temp;
    }
}
Referenced by CubeMesh::defineIntersection(), and CubeMesh::updateCoords().
Variable Documentation
cubeMeshCinfo
const Cinfo* cubeMeshCinfo = CubeMesh::initCinfo() static
Definition at line 257 of file CubeMesh.cpp.