MOOSE - Multiscale Object Oriented Simulation Environment: /home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/mesh/CylBase.cpp File Reference
CylBase.cpp File Reference
#include "../basecode/header.h"
#include "../basecode/SparseMatrix.h"
#include "Boundary.h"
#include "MeshEntry.h"
#include "VoxelJunction.h"
#include "ChemCompt.h"
#include "MeshCompt.h"
#include "CubeMesh.h"
#include "CylBase.h"
#include "../utility/Vec.h"
Functions
static void fillPointsOnCircle (const Vec &u, const Vec &v, const Vec &q, double h, double r, vector< double > &area, const CubeMesh *other)
static void fillPointsOnDisc (const Vec &u, const Vec &v, const Vec &q, double h, double r, vector< double > &area, const CubeMesh *other)
Function Documentation
fillPointsOnCircle()
static void fillPointsOnCircle (const Vec & u, const Vec & v, const Vec & q, double h, double r, vector< double > & area, const CubeMesh * other) static
Definition at line 260 of file CylBase.cpp.
{
    // fine-tune the h spacing so it is integral around circle.
    // This will cause small errors in area estimate but they will
    // be anisotropic. The alternative will have large errors toward
    // 360 degrees, but not elsewhere.
    unsigned int numAngle = static_cast<unsigned int>(floor( 2.0 * M_PI * r / h + 0.5 ));
    assert( numAngle > 0 );
    double dtheta = 2.0 * M_PI / numAngle;
    double dArea = h * dtheta * r;
    // March along points on surface of circle centred at q.
    for ( unsigned int j = 0; j < numAngle; ++j ) {
        double theta = j * dtheta;
        double c = cos( theta );
        double s = sin( theta );
        double p0 = q.a0() + r * ( u.a0() * c + v.a0() * s );
        double p1 = q.a1() + r * ( u.a1() * c + v.a1() * s );
        double p2 = q.a2() + r * ( u.a2() * c + v.a2() * s );
        unsigned int index = other->spaceToIndex( p0, p1, p2 );
        if ( index != CubeMesh::EMPTY )
            area[index] += dArea;
    }
}
References Vec::a0(), Vec::a1(), Vec::a2(), CubeMesh::EMPTY, and CubeMesh::spaceToIndex().
Referenced by CylBase::matchCubeMeshEntries().
fillPointsOnDisc()
static void fillPointsOnDisc (const Vec & u, const Vec & v, const Vec & q, double h, double r, vector< double > & area, const CubeMesh * other) static
Definition at line 288 of file CylBase.cpp.
{
    unsigned int numRadial = static_cast<unsigned int>(floor( r / h + 0.5 ));
    double dRadial = r / numRadial;
    for ( unsigned int i = 0; i < numRadial; ++i ) {
        double a = ( i + 0.5 ) * dRadial;
        unsigned int numAngle = static_cast<unsigned int>(floor( 2.0 * M_PI * a / h + 0.5 ));
        if ( i == 0 )
            numAngle = 1;
        double dtheta = 2.0 * M_PI / numAngle;
        double dArea = dRadial * dtheta * a;
        for ( unsigned int j = 0; j < numAngle; ++j ) {
            double theta = j * dtheta;
            double c = cos( theta );
            double s = sin( theta );
            double p0 = q.a0() + a * ( u.a0() * c + v.a0() * s );
            double p1 = q.a1() + a * ( u.a1() * c + v.a1() * s );
            double p2 = q.a2() + a * ( u.a2() * c + v.a2() * s );
            unsigned int index = other->spaceToIndex( p0, p1, p2 );
            if ( index != CubeMesh::EMPTY )
                area[index] += dArea;
        }
    }
}
References Vec::a0(), Vec::a1(), Vec::a2(), CubeMesh::EMPTY, and CubeMesh::spaceToIndex().
Referenced by CylBase::matchCubeMeshEntries().