MOOSE - Multiscale Object Oriented Simulation Environment: /home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/mesh/CylMesh.cpp File Reference
CylMesh.cpp File Reference
#include "../basecode/header.h"
#include "../basecode/SparseMatrix.h"
#include "../basecode/ElementValueFinfo.h"
#include "../utility/Vec.h"
#include "Boundary.h"
#include "MeshEntry.h"
#include "ChemCompt.h"
#include "MeshCompt.h"
#include "CubeMesh.h"
#include "CylBase.h"
#include "NeuroNode.h"
#include "NeuroMesh.h"
#include "CylMesh.h"
#include "EndoMesh.h"
#include "../utility/numutil.h"
#include "../utility/testing_macros.hpp"
Functions
static double dotprd (double x0, double y0, double z0, double x1, double y1, double z1)
void fillPointsOnCircle (const Vec &u, const Vec &v, const Vec &q, double h, double r, vector< double > &area, const CubeMesh *other)
Variables
static const Cinfo * cylMeshCinfo = CylMesh::initCinfo()
Function Documentation
dotprd()
static double dotprd (double x0, double y0, double z0, double x1, double y1, double z1) static
Definition at line 1067 of file CylMesh.cpp.
{
    return x0 * x1 + y0 * y1 + z0 * z1;
}
Referenced by CylMesh::nearest().
fillPointsOnCircle()
void fillPointsOnCircle (const Vec & u, const Vec & v, const Vec & q, double h, double r, vector< double > & area, const CubeMesh * other)
Definition at line 985 of file CylMesh.cpp.
{
    // fine-tune the h spacing so it is integral around circle.
    // This will cause small errors in area estimate but they will
    // be anisotropic. The alternative will have large errors toward
    // 360 degrees, but not elsewhere.
    unsigned int numAngle = static_cast<unsigned int>(floor( 2.0 * PI * r / h + 0.5 ));
    assert( numAngle > 0 );
    double dtheta = 2.0 * PI / numAngle;
    double dArea = h * dtheta * r;
    // March along points on surface of circle centred at q.
    for ( unsigned int j = 0; j < numAngle; ++j ) {
        double theta = j * dtheta;
        double c = cos( theta );
        double s = sin( theta );
        double p0 = q.a0() + r * ( u.a0() * c + v.a0() * s );
        double p1 = q.a1() + r * ( u.a1() * c + v.a1() * s );
        double p2 = q.a2() + r * ( u.a2() * c + v.a2() * s );
        unsigned int index = other->spaceToIndex( p0, p1, p2 );
        if ( index != CubeMesh::EMPTY )
            area[index] += dArea;
    }
}
References Vec::a0(), Vec::a1(), Vec::a2(), CubeMesh::EMPTY, PI, and CubeMesh::spaceToIndex().
Referenced by CylMesh::matchCubeMeshEntries().
Variable Documentation
cylMeshCinfo
const Cinfo* cylMeshCinfo = CylMesh::initCinfo() static
Definition at line 164 of file CylMesh.cpp.