MOOSE - Multiscale Object Oriented Simulation Environment: /home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/device/DiffAmp.cpp File Reference
DiffAmp.cpp File Reference
#include <cfloat>
#include "DiffAmp.h"
Functions
static SrcFinfo1< double > * outputOut ()
Variables
static const Cinfo * diffAmpCinfo = DiffAmp::initCinfo()
Function Documentation
outputOut()
static SrcFinfo1< double > * outputOut () static
Definition at line 44 of file DiffAmp.cpp.
{
    static SrcFinfo1< double > outputOut( "output",
                                          "Current output level.");
    return &outputOut;
}
References SrcFinfo1< T >::SrcFinfo1().
Referenced by DiffAmp::initCinfo(), DiffAmp::process(), and DiffAmp::reinit().
Variable Documentation
diffAmpCinfo
const Cinfo* diffAmpCinfo = DiffAmp::initCinfo() static
Definition at line 146 of file DiffAmp.cpp.