MOOSE - Multiscale Object Oriented Simulation Environment: /home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/basecode/doubleEq.cpp File Reference
doubleEq.cpp File Reference
#include <math.h>
Macros
#define EPS1 1e-6
#define EPS2 1e-12
#define EPS3 1e-3
Functions
bool doubleApprox (double x, double y)
bool doubleEq (double x, double y)
Macro Definition Documentation
EPS1
#define EPS1 1e-6
Definition at line 10 of file doubleEq.cpp.
EPS2
#define EPS2 1e-12
Definition at line 11 of file doubleEq.cpp.
EPS3
#define EPS3 1e-3
Definition at line 12 of file doubleEq.cpp.
Function Documentation
doubleApprox()
bool doubleApprox (double x, double y)
Definition at line 24 of file doubleEq.cpp.
{
    double denom = fabs( x ) + fabs( y );
    if ( denom < EPS1 )
        denom = EPS1;
    return ( fabs( x - y ) / denom ) < EPS3;
}
Referenced by CubeMesh::compareMeshSpacing(), Vec::orthogonalAxes(), Interpol2D::setXmax(), Interpol2D::setXmin(), Interpol2D::setYmax(), Interpol2D::setYmin(), testMMenzProcess(), and testStats().
doubleEq()
bool doubleEq (double x, double y)
Definition at line 16 of file doubleEq.cpp.
{
    double denom = fabs( x ) + fabs( y );
    if ( denom < EPS2 )
        denom = EPS1;
    return ( fabs( x - y ) / denom ) < EPS1;
}
Referenced by Dsolve::build(), checkOutput(), coordSystem(), doPartialPivot(), NeuroMesh::insertSingleDummy(), Interpol2D::Interpol2D(), VectorTable::lookupByValue(), matInv(), SynChan::normalizeGbar(), FastMatrixElim::operator==(), Vec::operator==(), Vec::orthogonalAxes(), Neuron::scaleBufAndRates(), HHChannelBase::selectPower(), Stoich::setCompartment(), CubeMesh::setDiffScale(), Interpol2D::setDx(), Interpol2D::setDy(), HHChannelBase::setGatePower(), moose::CompartmentBase::setGeomAndElec(), moose::CompartmentBase::setLength(), StimulusTable::setStopTime(), Interpol2D::setSy(), SynChan::setTau2(), test2ArgSetVec(), testCalcJunction(), testCellDiffn(), testConvVectorOfVectors(), testCopyFieldElement(), testCreateMsg(), testCubeMesh(), testCylDiffn(), testCylDiffnWithStoich(), testFuncTerm(), testGet(), testGetMsg(), testHopFunc(), testLookupSetGet(), testMMenz(), testMpiFibonacci(), testMsgField(), testObjIdToAndFromPath(), testPoolVolumeScaling(), testReacVolumeScaling(), ReadCspace::testReadModel(), testReMesh(), testSendMsg(), testSendSpike(), testSetDiffusionAndTransport(), testSetGet(), testSetGetDouble(), testSetGetExtField(), testSetGetSynapse(), testSetRepeat(), testShellAddMsg(), testShellSetGet(), testSmallCellDiffn(), testTable(), testTaperingCylDiffn(), testUtilsForCompareXplot(), testUtilsForLoadXplot(), testVec(), testVolScaling(), CylMesh::updateCoords(), MarkovRateTable::updateRates(), and SynChan::vReinit().