MOOSE - Multiscale Object Oriented Simulation Environment: /home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/diffusion/Dsolve.cpp File Reference
Dsolve.cpp File Reference
#include "../basecode/header.h"
#include "../basecode/ElementValueFinfo.h"
#include "../basecode/SparseMatrix.h"
#include "../ksolve/KinSparseMatrix.h"
#include "../ksolve/VoxelPoolsBase.h"
#include "../mesh/VoxelJunction.h"
#include "../ksolve/XferInfo.h"
#include "../ksolve/KsolveBase.h"
#include "../kinetics/ConcChan.h"
#include "DiffPoolVec.h"
#include "ConcChanInfo.h"
#include "FastMatrixElim.h"
#include "DiffJunction.h"
#include "../mesh/Boundary.h"
#include "../mesh/MeshEntry.h"
#include "../mesh/ChemCompt.h"
#include "../mesh/MeshCompt.h"
#include "../shell/Wildcard.h"
#include "../kinetics/PoolBase.h"
#include "Dsolve.h"
#include <thread>
Functions
static bool checkJn (const vector< DiffJunction > &jn, unsigned int voxel, const string &info)
static double integ (double myN, double rf, double rb, double dt)
static void mapVoxelsBetweenMeshes (DiffJunction &jn, Id self, Id other)
void printJunction (Id self, Id other, const DiffJunction &jn)
Variables
static const Cinfo * dsolveCinfo = Dsolve::initCinfo()
Function Documentation
checkJn()
static bool checkJn (const vector< DiffJunction > & jn, unsigned int voxel, const string & info) static
Definition at line 225 of file Dsolve.cpp.
{
    if ( jn.size() < 1 )
    {
        cout << "Warning: Dsolve::" << info << ": junctions not defined.\n";
        return false;
    }
    if ( jn[0].vj.size() < voxel + 1 )
    {
        cout << "Warning: Dsolve:: " << info << ": " << voxel <<
             "out of range.\n";
        return false;
    }
    return true;
}
References DiffJunction::vj.
Referenced by Dsolve::getDiffScale(), Dsolve::getDiffVol1(), Dsolve::getDiffVol2(), Dsolve::setDiffScale(), Dsolve::setDiffVol1(), and Dsolve::setDiffVol2().
integ()
static double integ (double myN, double rf, double rb, double dt) static
Definition at line 303 of file Dsolve.cpp.
{
    const double EPSILON = 1e-12;
    if ( myN > EPSILON && rf > EPSILON )
    {
        double C = exp( -rf * dt / myN );
        myN *= C + ( rb / rf ) * ( 1.0 - C );
    }
    else
    {
        myN += ( rb - rf ) * dt;
    }
    if ( myN < 0.0 )
        return 0.0;
    return myN;
}
Referenced by Dsolve::calcJnChan(), Dsolve::calcJnDiff(), Dsolve::calcLocalChan(), and Dsolve::calcOtherJnChan().
mapVoxelsBetweenMeshes()
static void mapVoxelsBetweenMeshes (DiffJunction & jn, Id self, Id other) static
Definition at line 1044 of file Dsolve.cpp.
{
    Id myMesh = Field< Id >::get( self, "compartment" );
    Id otherMesh = Field< Id >::get( other, "compartment" );
    const ChemCompt* myCompt = reinterpret_cast< const ChemCompt* >(
                                   myMesh.eref().data() );
    const ChemCompt* otherCompt = reinterpret_cast< const ChemCompt* >(
                                      otherMesh.eref().data() );
    myCompt->matchMeshEntries( otherCompt, jn.vj );
    vector< double > myVols = myCompt->getVoxelVolume();
    vector< double > otherVols = otherCompt->getVoxelVolume();
    for ( vector< VoxelJunction >::iterator
            i = jn.vj.begin(); i != jn.vj.end(); ++i )
    {
        i->firstVol = myVols[i->first];
        i->secondVol = otherVols[i->second];
    }
}
References Eref::data(), Id::eref(), VoxelJunction::first, VoxelJunction::firstVol, Field< A >::get(), ChemCompt::getVoxelVolume(), ChemCompt::matchMeshEntries(), VoxelJunction::second, VoxelJunction::secondVol, and DiffJunction::vj.
Referenced by Dsolve::innerBuildMeshJunctions().
printJunction()
void printJunction (Id self, Id other, const DiffJunction & jn)
Definition at line 911 of file Dsolve.cpp.
{
    cout << "Junction between " << self.path() << ", " << other.path() << endl;
    cout << "Pool indices: myPools, otherPools\n";
    for ( unsigned int i = 0; i < jn.myPools.size(); ++i )
        cout << i << "    " << jn.myPools[i] << "    " << jn.otherPools[i] << endl;
    cout << "Voxel junctions: first    second    firstVol    secondVol    diffScale\n";
    for ( unsigned int i = 0; i < jn.vj.size(); ++i )
    {
        cout << i << "    " << jn.vj[i].first << "    " << jn.vj[i].second <<
             "    " << jn.vj[i].firstVol << "    " << jn.vj[i].secondVol <<
             "    " << jn.vj[i].diffScale <<    endl;
    }
}
References VoxelJunction::diffScale, VoxelJunction::first, VoxelJunction::firstVol, DiffJunction::myPools, DiffJunction::otherPools, Id::path(), VoxelJunction::second, VoxelJunction::secondVol, and DiffJunction::vj.
Variable Documentation
dsolveCinfo
const Cinfo* dsolveCinfo = Dsolve::initCinfo() static
Definition at line 182 of file Dsolve.cpp.