MOOSE - Multiscale Object Oriented Simulation Environment: /home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/basecode/Element.cpp File Reference
Element.cpp File Reference
#include "header.h"
#include "FuncOrder.h"
#include "HopFunc.h"
#include "../msg/OneToAllMsg.h"
#include "../shell/Shell.h"
#include "../scheduling/Clock.h"
Classes
class matchMid
Functions
static bool addClockMsg (unsigned int tick, Id tgt, const Finfo *f2)
void filterOffNodeTargets (unsigned int start, unsigned int end, bool isSrcGlobal, unsigned int myNode, vector< vector< Eref > > &erefs, vector< vector< bool > > &targetNodes)
unsigned int findNumDigest (const vector< vector< MsgDigest > > &md, unsigned int totFunc, unsigned int numData, unsigned int funcNum)
vector< FuncOrder > putFuncsInOrder (const Element *elm, const vector< MsgFuncBinding > &vec)
Function Documentation
addClockMsg()
static bool addClockMsg (unsigned int tick, Id tgt, const Finfo * f2) static
Definition at line 228 of file Element.cpp.
{
    Id clockId( 1 );
    stringstream ss;
    ss << "proc" << tick;
    const Finfo* f1 = clockId.element()->cinfo()->findFinfo( ss.str() );
    assert( f1 );
    assert( f2 );
    Msg* m = new OneToAllMsg( clockId.eref(), tgt.element(), 0 );
    if ( m )
    {
        if ( f1->addMsg( f2, m->mid(), clockId.element() ) )
        {
            return true;
        }
        delete m;
    }
    cout << "Error: Element::setTick: failed to connect " << tgt <<
         " to clock\n";
    return false;
}
References Finfo::addMsg(), Element::cinfo(), Id::element(), Id::eref(), Cinfo::findFinfo(), Id::Id(), Msg::mid(), and OneToAllMsg::OneToAllMsg().
Referenced by Element::setTick().
filterOffNodeTargets()
void filterOffNodeTargets (unsigned int start, unsigned int end, bool isSrcGlobal, unsigned int myNode, vector< vector< Eref > > & erefs, vector< vector< bool > > & targetNodes)
Picks which messages we retain in the MsgDigest. Does so at two levels:
Builds an array[][] of bools to indicate messages sourced here that go off-node. These will have special HopFuncs added.
Retains entries in erefs that are sourced anywhere, but targetted here. Need to be able to handle off-node messages landing here, as well as the entirely local messages.
Definition at line 429 of file Element.cpp.
{
    // i is index of src dataid
    for ( unsigned int i = 0; i < erefs.size(); ++i )
    {
        vector< Eref > temp;
        vector< Eref >& vec = erefs[i];
        for ( unsigned int j = 0; j < vec.size(); ++j )   // list of tgts.
        {
            const Eref& er = vec[j];
            unsigned int node = er.getNode();
            if ( !isSrcGlobal && // Don't send any  msgs
                    // off-node, as it will be dealt with by the off-node src.
                    i >= start && i < end )   // Sourced from current node.
            {
                if ( node != myNode )               // Target is off-node
                    targetNodes[i][node] = true;
                if ( er.dataIndex() == ALLDATA || er.element()->isGlobal())
                {
                    for ( unsigned int k = 0; k < Shell::numNodes(); ++k )
                        if ( k != myNode )
                            targetNodes[i][k] = true;
                }
            }
            if ( node == myNode ) // Regardless of source, target is onNode.
                temp.push_back( er );
        }
        erefs[i] = temp; // Swap out the original set with the new one.
    }
}
References ALLDATA, Eref::dataIndex(), Eref::element(), Eref::getNode(), Element::isGlobal(), and Shell::numNodes().
Referenced by Element::putTargetsInDigest(), and testFilterOffNodeTargets().
findNumDigest()
unsigned int findNumDigest (const vector< vector< MsgDigest > > & md, unsigned int totFunc, unsigned int numData, unsigned int funcNum)
Definition at line 558 of file Element.cpp.
{
    unsigned int ret = 0;
    for ( unsigned int i = 0; i < numData; ++i )
    {
        ret += md[ totFunc * i + funcNum ].size();
    }
    return ret;
}
Referenced by Element::digestMessages().
putFuncsInOrder()
vector< FuncOrder > putFuncsInOrder (const Element * elm, const vector< MsgFuncBinding > & vec)
Definition at line 392 of file Element.cpp.
{
    vector< FuncOrder > fo( vec.size() );
    for ( unsigned int j = 0; j < vec.size(); ++j )
    {
        const MsgFuncBinding& mfb = vec[j];
        const Msg* msg = Msg::getMsg( mfb.mid );
        if ( msg->e1() == elm )
        {
            fo[j].set( msg->e2()->cinfo()->getOpFunc( mfb.fid ), j );
        }
        else
        {
            fo[j].set( msg->e1()->cinfo()->getOpFunc( mfb.fid ), j );
        }
    }
    sort( fo.begin(), fo.end() );
    return fo;
}
References Element::cinfo(), Msg::e1(), Msg::e2(), MsgFuncBinding::fid, Msg::getMsg(), Cinfo::getOpFunc(), MsgFuncBinding::mid, and FuncOrder::set().
Referenced by Element::digestMessages().