MOOSE - Multiscale Object Oriented Simulation Environment: /home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/kinetics/Enz.cpp File Reference
Enz.cpp File Reference
#include "../basecode/header.h"
#include "../basecode/ElementValueFinfo.h"
#include "lookupVolumeFromMesh.h"
#include "../basecode/SparseMatrix.h"
#include "../ksolve/RateTerm.h"
#include "../ksolve/KinSparseMatrix.h"
#include "../ksolve/Stoich.h"
#include "EnzBase.h"
#include "Enz.h"
Macros
#define EPSILON 1e-15
Functions
static SrcFinfo2< double, double > * cplxOut ()
DestFinfo * enzDest ()
static SrcFinfo2< double, double > * enzOut ()
Variables
static const Cinfo * enzCinfo = Enz::initCinfo()
static const SrcFinfo2< double, double > * subOut
Macro Definition Documentation
EPSILON
#define EPSILON 1e-15
Definition at line 29 of file Enz.cpp.
Function Documentation
cplxOut()
static SrcFinfo2< double, double > * cplxOut () static
Definition at line 40 of file Enz.cpp.
{
    static SrcFinfo2< double, double > cplxOut(
            "cplxOut",
            "Sends out increment of molecules on product each timestep"
            );
    return &cplxOut;
}
References SrcFinfo2< T1, T2 >::SrcFinfo2().
Referenced by Enz::initCinfo().
enzDest()
DestFinfo * enzDest ()
Definition at line 48 of file Enz.cpp.
{
    static const Finfo* f1 = EnzBase::initCinfo()->findFinfo( "enzDest" );
    static const DestFinfo* f2 = dynamic_cast< const DestFinfo* >( f1 );
    static DestFinfo* enzDest = const_cast< DestFinfo* >( f2 );
    assert( f1 );
    assert( f2 );
    return enzDest;
}
References Cinfo::findFinfo(), and EnzBase::initCinfo().
Referenced by Enz::initCinfo().
enzOut()
static SrcFinfo2< double, double > * enzOut () static
Definition at line 32 of file Enz.cpp.
{
    static SrcFinfo2< double, double > enzOut(
            "enzOut",
            "Sends out increment of molecules on product each timestep"
            );
    return &enzOut;
}
References SrcFinfo2< T1, T2 >::SrcFinfo2().
Referenced by Enz::initCinfo().
Variable Documentation
enzCinfo
const Cinfo* enzCinfo = Enz::initCinfo() static
Definition at line 189 of file Enz.cpp.
subOut
const SrcFinfo2< double, double >* subOut static
Initial value:
=
    dynamic_cast< const SrcFinfo2< double, double >* >(
    enzCinfo->findFinfo( "subOut" ) )
Definition at line 191 of file Enz.cpp.
Referenced by Enz::getK1(), and Enz::setK1().