MOOSE - Multiscale Object Oriented Simulation Environment: /home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/diffusion/FastMatrixElim.cpp File Reference
FastMatrixElim.cpp File Reference
#include <math.h>
#include <vector>
#include <algorithm>
#include <cassert>
#include <functional>
#include <iostream>
#include <iomanip>
#include "../basecode/SparseMatrix.h"
#include "../basecode/doubleEq.h"
#include "FastMatrixElim.h"
Functions
void buildColIndex (unsigned int nrows, const vector< unsigned int > &parentVoxel, vector< vector< unsigned int > > &colIndex)
static const unsigned int EMPTY_VOXEL (-1)
void findAreaProportion (vector< double > &areaProportion, const vector< unsigned int > &parentVoxel, const vector< double > &area)
void sortByColumn (vector< unsigned int > &col, vector< double > &entry)
void testSorting ()
Function Documentation
buildColIndex()
void buildColIndex (unsigned int nrows, const vector< unsigned int > & parentVoxel, vector< vector< unsigned int > > & colIndex)
Definition at line 510 of file FastMatrixElim.cpp.
{
    colIndex.clear();
    colIndex.resize( nrows );
    for ( unsigned int i = 0; i < nrows; ++i ) {
        if ( parentVoxel[i] != EMPTY_VOXEL ) {
            colIndex[i].push_back( parentVoxel[i] ); // parent
            colIndex[ parentVoxel[i] ].push_back( i ); // children
        }
        colIndex[i].push_back( i ); // diagonal: self
    }
    for ( unsigned int i = 0; i < nrows; ++i ) {
        vector< unsigned int >& c = colIndex[i];
        sort( c.begin(), c.end() );
        // Should check that there are no duplicates.
        for ( unsigned int j = 1; j < c.size(); ++j ) {
            assert( c[j -1 ] != c[j] );
        }
    }
}
References EMPTY_VOXEL().
Referenced by FastMatrixElim::buildForDiffusion().
EMPTY_VOXEL()
static const unsigned int EMPTY_VOXEL (- 1) static
Referenced by buildColIndex(), FastMatrixElim::buildForDiffusion(), findAreaProportion(), FastMatrixElim::hinesReorder(), and FastMatrixElim::setDiffusionAndTransport().
findAreaProportion()
void findAreaProportion (vector< double > & areaProportion, const vector< unsigned int > & parentVoxel, const vector< double > & area)
Motor transport into branches is divided between the child branches in proportion to their area. This function computes these proportions.
Definition at line 538 of file FastMatrixElim.cpp.
{
    unsigned int nrows = parentVoxel.size();
    vector< double > sumAreaOfChildren( nrows, 0.0 );
    for ( unsigned int i = 0; i < nrows; ++i ) {
        if ( parentVoxel[i] != EMPTY_VOXEL )
            sumAreaOfChildren[ parentVoxel[i] ] += area[i];
    }
    for ( unsigned int i = 0; i < nrows; ++i ) {
        if ( parentVoxel[i] != EMPTY_VOXEL )
            areaProportion[i] = area[i]/sumAreaOfChildren[ parentVoxel[i] ];
        else
            areaProportion[i] = 1.0;
    }
}
References EMPTY_VOXEL().
Referenced by FastMatrixElim::buildForDiffusion().
sortByColumn()
void sortByColumn (vector< unsigned int > & col, vector< double > & entry)
Definition at line 223 of file FastMatrixElim.cpp.
{
    unsigned int num = col.size();
    assert( num == entry.size() );
    // Stupid bubble sort, as we only have up to 5 entries and need to
    // sort both the col and reorder the entries by the same sequence.
    for ( unsigned int i = 0; i < num; ++i ) {
        for ( unsigned int j = 1; j < num; ++j ) {
            if ( col[j] < col[j-1] ) {
                unsigned int temp = col[j];
                col[j] = col[j-1];
                col[j-1] = temp;
                double v = entry[j];
                entry[j] = entry[j-1];
                entry[j-1] = v;
            }
        }
    }
}
testSorting()
void testSorting ()
Definition at line 684 of file standaloneTestFastElim.cpp.
{
    static unsigned int k[] = {20,40,60,80,100,10,30,50,70,90};
    static double d[] = {1,2,3,4,5,6,7,8,9,10};
    vector< unsigned int > col;
    col.insert( col.begin(), k, k+10);
    vector< double > entry;
    entry.insert( entry.begin(), d, d+10);
    sortByColumn( col, entry );
    cout << "testing sorting\n";
    for ( int i = 0; i < col.size(); ++i )
    {
        cout << "d[" << i << "]=    " << k[i] <<
             ", col[" << i << "]= " <<  col[i] << ", e=" << entry[i] << endl;
    }
    cout << endl;
}
References sortByColumn().
Referenced by testDiffusion().