MOOSE - Multiscale Object Oriented Simulation Environment: /home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/ksolve/FuncTerm.cpp File Reference
FuncTerm.cpp File Reference
#include <vector>
#include <sstream>
#include "FuncTerm.h"
#include "../utility/numutil.h"
Functions
void showError (moose::Parser::exception_type &e)
Function Documentation
showError()
void showError (moose::Parser::exception_type & e)
Definition at line 68 of file FuncTerm.cpp.
{
    cerr << "Error occurred in parser.\n"
         << "Message:  " << e.GetMsg() << endl;
}
References moose::Parser::ParserException::GetMsg().
Referenced by FuncTerm::evalPool(), and FuncTerm::setExpr().