MOOSE - Multiscale Object Oriented Simulation Environment: /home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/builtins/Function.cpp File Reference
Function.cpp File Reference
#include <regex>
#include <algorithm>
#include "../basecode/header.h"
#include "../basecode/global.h"
#include "../basecode/ElementValueFinfo.h"
#include "../basecode/LookupElementValueFinfo.h"
#include "../utility/strutil.h"
#include "../utility/numutil.h"
#include "../utility/testing_macros.hpp"
#include "../utility/print_function.hpp"
#include "../builtins/MooseParser.h"
#include "Variable.h"
#include "Function.h"
#include "../ksolve/RateTerm.h"
#include "../basecode/SparseMatrix.h"
#include "../ksolve/KinSparseMatrix.h"
#include "../ksolve/Stoich.h"
Functions
static SrcFinfo1< double > * derivativeOut ()
static SrcFinfo1< double > * rateOut ()
static SrcFinfo1< vector< double > * > * requestOut ()
static SrcFinfo1< double > * valueOut ()
Variables
static const Cinfo * functionCinfo = Function::initCinfo()
static const double TriggerThreshold = 0.0
Function Documentation
derivativeOut()
static SrcFinfo1< double > * derivativeOut () static
Definition at line 42 of file Function.cpp.
{
    static SrcFinfo1< double > derivativeOut("derivativeOut",
            "Value of derivative of the function for the current variable values");
    return &derivativeOut;
}
References SrcFinfo1< T >::SrcFinfo1().
Referenced by Function::clearVariables(), and Function::initCinfo().
rateOut()
static SrcFinfo1< double > * rateOut () static
Definition at line 49 of file Function.cpp.
{
    static SrcFinfo1< double > rateOut("rateOut",
            "Value of time-derivative of the function for the current variable values"
            );
    return &rateOut;
}
References SrcFinfo1< T >::SrcFinfo1().
Referenced by Function::clearAll(), and Function::initCinfo().
requestOut()
static SrcFinfo1< vector< double > * > * requestOut () static
Definition at line 57 of file Function.cpp.
{
    static SrcFinfo1< vector < double > * > requestOut(
            "requestOut",
            "Sends request for input variable from a field on target object");
    return &requestOut;
}
References SrcFinfo1< T >::SrcFinfo1().
Referenced by Function::initCinfo().
valueOut()
static SrcFinfo1< double > * valueOut () static
Definition at line 34 of file Function.cpp.
{
    static SrcFinfo1<double> valueOut("valueOut",
            "Evaluated value of the function for the current variable values."
            );
    return &valueOut;
}
References SrcFinfo1< T >::SrcFinfo1().
Referenced by Function::clearVariables(), and Function::initCinfo().
Variable Documentation
functionCinfo
const Cinfo* functionCinfo = Function::initCinfo() static
Definition at line 329 of file Function.cpp.
TriggerThreshold
const double TriggerThreshold = 0.0 static
Definition at line 32 of file Function.cpp.