MOOSE - Multiscale Object Oriented Simulation Environment: /home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/basecode/HopFunc.cpp File Reference
HopFunc.cpp File Reference
#include "header.h"
#include "HopFunc.h"
#include "../mpi/PostMaster.h"
#include "../shell/Shell.h"
Functions
double * addToBuf (const Eref &er, HopIndex hopIndex, unsigned int size)
static double * addToTestBuf (const Eref &e, unsigned int i, unsigned int size)
const double * checkHopFuncTestBuffer ()
void dispatchBuffers (const Eref &e, HopIndex hopIndex)
unsigned int mooseMyNode ()
unsigned int mooseNumNodes ()
void remoteFieldGetVec (const Eref &e, unsigned int bindIndex, vector< double > &getRecvBuf)
double * remoteGet (const Eref &e, unsigned int bindIndex)
void remoteGetVec (const Eref &e, unsigned int bindIndex, vector< vector< double > > &getRecvBuf, vector< unsigned int > &numOnNode)
Variables
static double testBuf [4096]
Function Documentation
addToBuf()
double * addToBuf (const Eref & er, HopIndex hopIndex, unsigned int size)
Definition at line 29 of file HopFunc.cpp.
{
    static ObjId oi( 3 );
    static PostMaster* p = reinterpret_cast< PostMaster* >( oi.data() );
    if ( hopIndex.hopType() == MooseSendHop ) {
        return p->addToSendBuf( er, hopIndex.bindIndex(), size );
    } else if ( hopIndex.hopType() == MooseSetHop ||
             hopIndex.hopType() == MooseSetVecHop ) {
        p->clearPendingSetGet(); // Cannot touch set buffer if pending.
        return p->addToSetBuf( er, hopIndex.bindIndex(),
                        size, hopIndex.hopType() );
    } else if ( hopIndex.hopType() == MooseTestHop ) {
        return addToTestBuf( er, hopIndex.bindIndex(), size );
    }
    assert( 0 ); // Should not get here.
    return 0;
}
References PostMaster::addToSendBuf(), PostMaster::addToSetBuf(), addToTestBuf(), HopIndex::bindIndex(), PostMaster::clearPendingSetGet(), ObjId::data(), HopIndex::hopType(), MooseSendHop, MooseSetHop, MooseSetVecHop, MooseTestHop, and ObjId::ObjId().
Referenced by HopFunc0::op().
addToTestBuf()
static double * addToTestBuf (const Eref & e, unsigned int i, unsigned int size) static
Definition at line 15 of file HopFunc.cpp.
{
    TgtInfo* tgt = reinterpret_cast< TgtInfo* >( &testBuf[0] );
    tgt->set( e.objId(), i, size );
    return &testBuf[ TgtInfo::headerSize ];
}
References TgtInfo::headerSize, Eref::objId(), TgtInfo::set(), and testBuf.
Referenced by addToBuf().
checkHopFuncTestBuffer()
const double * checkHopFuncTestBuffer ()
Definition at line 23 of file HopFunc.cpp.
{
    return &testBuf[0];
}
References testBuf.
Referenced by testHopFunc().
dispatchBuffers()
void dispatchBuffers (const Eref & e, HopIndex hopIndex)
Definition at line 47 of file HopFunc.cpp.
{
    static ObjId oi( 3 );
    static PostMaster* p = reinterpret_cast< PostMaster* >( oi.data() );
    if ( Shell::numNodes() == 1 )
        return;
    if ( hopIndex.hopType() == MooseSetHop ||
        hopIndex.hopType() == MooseGetHop ) {
        p->dispatchSetBuf( e );
    }
    if ( hopIndex.hopType() == MooseSetVecHop ) {
        p->dispatchSetBuf( e );
    }
    // More complicated stuff for get operations.
}
References ObjId::data(), PostMaster::dispatchSetBuf(), HopIndex::hopType(), MooseGetHop, MooseSetHop, MooseSetVecHop, Shell::numNodes(), and ObjId::ObjId().
Referenced by HopFunc0::op(), HopFunc1< A >::op(), HopFunc2< A1, A2 >::op(), HopFunc3< A1, A2, A3 >::op(), HopFunc4< A1, A2, A3, A4 >::op(), HopFunc5< A1, A2, A3, A4, A5 >::op(), HopFunc6< A1, A2, A3, A4, A5, A6 >::op(), and HopFunc2< A1, A2 >::opVec().
mooseMyNode()
unsigned int mooseMyNode ()
Definition at line 92 of file HopFunc.cpp.
{
    return Shell::myNode();
}
References Shell::myNode().
Referenced by HopFunc1< A >::dataOpVec(), GetHopFunc< A >::getMultiNodeVec(), HopFunc1< A >::localFieldOpVec(), GetHopFunc< A >::opGetVec(), HopFunc2< A1, A2 >::opVec(), and HopFunc1< A >::opVec().
mooseNumNodes()
unsigned int mooseNumNodes ()
Definition at line 87 of file HopFunc.cpp.
{
    return Shell::numNodes();
}
References Shell::numNodes().
Referenced by HopFunc1< A >::dataOpVec(), GetHopFunc< A >::getMultiNodeVec(), GetHopFunc< A >::opGetVec(), HopFunc2< A1, A2 >::opVec(), and HopFunc1< A >::remoteOpVec().
remoteFieldGetVec()
void remoteFieldGetVec (const Eref & e, unsigned int bindIndex, vector< double > & getRecvBuf)
Definition at line 79 of file HopFunc.cpp.
{
    static ObjId oi( 3 );
    static PostMaster* p = reinterpret_cast< PostMaster* >( oi.data() );
    p->remoteFieldGetVec( e, bindIndex, getRecvBuf );
}
References ObjId::data(), ObjId::ObjId(), and PostMaster::remoteFieldGetVec().
Referenced by GetHopFunc< A >::getRemoteFieldVec().
remoteGet()
double * remoteGet (const Eref & e, unsigned int bindIndex)
Definition at line 63 of file HopFunc.cpp.
{
    static ObjId oi( 3 );
    static PostMaster* p = reinterpret_cast< PostMaster* >( oi.data() );
    return p->remoteGet( e, bindIndex );
}
References ObjId::data(), ObjId::ObjId(), and PostMaster::remoteGet().
Referenced by GetHopFunc< A >::op().
remoteGetVec()
void remoteGetVec (const Eref & e, unsigned int bindIndex, vector< vector< double > > & getRecvBuf, vector< unsigned int > & numOnNode)
Definition at line 70 of file HopFunc.cpp.
{
    static ObjId oi( 3 );
    static PostMaster* p = reinterpret_cast< PostMaster* >( oi.data() );
    p->remoteGetVec( e, bindIndex, getRecvBuf, numOnNode );
}
References ObjId::data(), ObjId::ObjId(), and PostMaster::remoteGetVec().
Variable Documentation
testBuf
double testBuf[4096] static
Definition at line 14 of file HopFunc.cpp.
Referenced by addToTestBuf(), and checkHopFuncTestBuffer().