MOOSE - Multiscale Object Oriented Simulation Environment: /home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/hsolve/HSolvePassive.cpp File Reference
HSolvePassive.cpp File Reference
#include "HSolvePassive.h"
Functions
ostream & operator<< (ostream &s, const HinesMatrix &m)
Function Documentation
operator<<()
ostream & operator<< (ostream & s, const HinesMatrix & m) extern
Definition at line 449 of file HinesMatrix.cpp.
{
    unsigned int size = m.getSize();
    s << "\nA:\n";
    for ( unsigned int i = 0; i < size; i++ )
    {
        for ( unsigned int j = 0; j < size; j++ )
            s << setw( 12 ) << setprecision( 5 ) << m.getA( i, j );
        s << "\n";
    }
    s << "\n" << "V:\n";
    for ( unsigned int i = 0; i < size; i++ )
        s << m.getVMid( i ) << "\n";
    s << "\n" << "B:\n";
    for ( unsigned int i = 0; i < size; i++ )
        s << m.getB( i ) << "\n";
    return s;
}
References HinesMatrix::getA(), HinesMatrix::getB(), HinesMatrix::getSize(), and HinesMatrix::getVMid().