MOOSE - Multiscale Object Oriented Simulation Environment: /home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/builtins/Interpol2D.cpp File Reference
Interpol2D.cpp File Reference
#include <fstream>
#include <sstream>
#include "../basecode/header.h"
#include "../utility/strutil.h"
#include "Interpol2D.h"
Functions
static SrcFinfo1< double > * lookupOut ()
istream & operator>> (istream &in, Interpol2D &int2dTable)
Variables
static const Cinfo * interpol2DCinfo = Interpol2D::initCinfo()
Function Documentation
lookupOut()
static SrcFinfo1< double > * lookupOut () static
Definition at line 18 of file Interpol2D.cpp.
{
    static SrcFinfo1< double > lookupOut( "lookupOut",
        "respond to a request for a value lookup" );
    return &lookupOut;
}
References SrcFinfo1< T >::SrcFinfo1().
Referenced by Interpol2D::initCinfo(), and Interpol2D::lookupReturn().
operator>>()
istream & operator>> (istream & in, Interpol2D & int2dTable)
Definition at line 628 of file Interpol2D.cpp.
{
    in >> int2dTable.xmin_;
    in >> int2dTable.xmax_;
    in >> int2dTable.invDx_;
    in >> int2dTable.ymin_;
    in >> int2dTable.ymax_;
    in >> int2dTable.invDy_;
    for ( unsigned int i = 0; i < int2dTable.table_.size(); ++i )
    {
        for ( unsigned int j = 0; j < int2dTable.table_.size(); ++j )
            in >> int2dTable.table_[i][j];
    }
    return in;
}
References Interpol2D::invDx_, Interpol2D::invDy_, Interpol2D::table_, Interpol2D::xmax_, Interpol2D::xmin_, Interpol2D::ymax_, and Interpol2D::ymin_.
Variable Documentation
interpol2DCinfo
const Cinfo* interpol2DCinfo = Interpol2D::initCinfo() static
Definition at line 156 of file Interpol2D.cpp.