MOOSE - Multiscale Object Oriented Simulation Environment: /home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/shell/LoadModels.cpp File Reference
LoadModels.cpp File Reference
#include <fstream>
#include "../basecode/header.h"
#include "Shell.h"
#include "../utility/strutil.h"
#include "../utility/Vec.h"
#include "LoadModels.h"
#include "../biophysics/ReadCell.h"
#include "../biophysics/SwcSegment.h"
#include "../biophysics/ReadSwc.h"
#include "../kinetics/ReadKkit.h"
#include "../kinetics/ReadCspace.h"
#include "../utility/print_function.hpp"
Functions
bool findModelParent (Id cwe, const string &path, Id &parentId, string &modelName)
ModelType findModelType (string filename, ifstream &fin, string &line)
Function Documentation
findModelParent()
bool findModelParent (Id cwe, const string & path, Id & parentId, string & modelName)
Identify parent Id from path that can optionally have the model name as the last part. Pass back the parent Id, and the model name. Returns true on success. Cases: First set: we want to fill in "model" as modelName "" where we want <cwe>/model "/" where we want /model. "/foo" where foo exists, so we want /foo/model "foo" where <cwe>/foo exists, and we want <cwe>/foo/model Second set: the last part of the path has the model name. "bar" where we want <cwe>/bar "/bar" where we want /bar "/foo/bar" where we want /foo/bar "foo/bar" where we want <cwe>/foo/bar
Definition at line 81 of file LoadModels.cpp.
{
    modelName = "model";
    string fullPath = path;
    if ( path.length() == 0 )
    {
        parentId = cwe;
        return 1;
    }
    if ( path == "/" )
    {
        parentId = Id();
        return 1;
    }
    if ( path[0] != '/' )
    {
        string temp = cwe.path();
        if ( temp[temp.length() - 1] == '/' )
            fullPath = temp + path;
        else
            fullPath = temp + "/" + path;
    }
    Id paId( fullPath );
    if ( paId == Id() )   // Path includes new model name
    {
        auto pos = fullPath.find_last_of( "/" );
        assert( pos != string::npos );
        string head = fullPath.substr( 0, pos );
        Id ret( head );
        // When head = "" it means paId should be root.
        if ( ret == Id() && head != "" && head != "/root" )
            return 0;
        parentId = ret;
        modelName = fullPath.substr( pos + 1 );
        return 1;
    }
    else     // Path is an existing element.
    {
        parentId = Neutral::parent( paId ).id;
        modelName = paId.element()->getName();
        return 1;
    }
    return 0;
}
References Id::element(), Element::getName(), Id::Id(), Id::Id(), ObjId::id, Id::operator==(), Neutral::parent(), and Id::path().
Referenced by Shell::doLoadModel(), and testFindModelParent().
findModelType()
ModelType findModelType (string filename, ifstream & fin, string & line)
Definition at line 24 of file LoadModels.cpp.
{
    if ( filename.substr( filename.length() - 2 ) == ".p" )
        return DOTP;
    if ( filename.substr( filename.length() - 4 ) == ".swc" )
        return SWC;
    getline( fin, line );
    line = moose::trim(line);
    if ( line == "//genesis" )
    {
        getline( fin, line );
        line = moose::trim(line);
        if ( line.substr( 0, 7 ) == "// kkit" )
            return KKIT;
    }
    if ( line.substr( 0, 9 ) == "//  DOQCS" )
    {
        while ( getline( fin, line ) )
        {
            line = moose::trim(line);
            if ( line.substr( 0, 7 ) == "// kkit" )
                return KKIT;
        }
    }
    unsigned long pos = line.find_first_of( ":" );
    string copyLine= line;
    if (pos != string::npos )
    {
        copyLine = line.substr(pos+2);
    }
    if ( copyLine.length() >= 6 && copyLine[0] == '|' && copyLine[5] == '|' )
        return CSPACE;
    return UNKNOWN;
}
References CSPACE, DOTP, KKIT, SWC, moose::trim(), and UNKNOWN.
Referenced by Shell::doLoadModel().