MOOSE - Multiscale Object Oriented Simulation Environment: /home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/biophysics/MarkovRateTable.cpp File Reference
MarkovRateTable.cpp File Reference
#include <iomanip>
#include "../basecode/header.h"
#include "VectorTable.h"
#include "../builtins/Interpol2D.h"
#include "MarkovRateTable.h"
Functions
static SrcFinfo1< vector< vector< double > > > * instRatesOut ()
istream & operator>> (istream &in, MarkovRateTable &rateTable)
Variables
static const Cinfo * MarkovRateTableCinfo = MarkovRateTable::initCinfo()
Function Documentation
instRatesOut()
static SrcFinfo1< vector< vector< double > > > * instRatesOut () static
Definition at line 17 of file MarkovRateTable.cpp.
{
    static SrcFinfo1< vector< vector< double > > > instRatesOut(
        "instratesOut",
        "Sends out instantaneous rate information of varying transition rates"
        "at each time step.");
    return &instRatesOut;
}
References SrcFinfo1< T >::SrcFinfo1().
Referenced by MarkovRateTable::initCinfo(), MarkovRateTable::process(), and MarkovRateTable::reinit().
operator>>()
istream & operator>> (istream & in, MarkovRateTable & rateTable)
Definition at line 568 of file MarkovRateTable.cpp.
{
    for ( unsigned int i = 0; i < rateTable.size_; ++i )
    {
        for ( unsigned int j = 0; j < rateTable.size_; ++j )
        {
            if ( rateTable.isRate1d( i, j ) )
                in >> *rateTable.vtTables_[i][j];
        }
    }
    for ( unsigned int i = 0; i < rateTable.size_; ++i )
    {
        for ( unsigned int j = 0; j < rateTable.size_; ++j )
        {
            if ( rateTable.isRate2d( i, j ) )
                in >> *rateTable.int2dTables_[i][j];
        }
    }
    for ( unsigned int i = 0; i < rateTable.size_; ++i )
    {
        for ( unsigned int j = 0; j < rateTable.size_; ++j )
            in >> rateTable.useLigandConc_[i][j];
    }
    in >> rateTable.Vm_;
    in >> rateTable.ligandConc_;
    in >> rateTable.size_;
    return in;
}
References MarkovRateTable::int2dTables_, MarkovRateTable::isRate1d(), MarkovRateTable::isRate2d(), MarkovRateTable::ligandConc_, Interpol2D::operator>>, VectorTable::operator>>, MarkovRateTable::size_, MarkovRateTable::useLigandConc_, MarkovRateTable::Vm_, and MarkovRateTable::vtTables_.
Variable Documentation
MarkovRateTableCinfo
const Cinfo* MarkovRateTableCinfo = MarkovRateTable::initCinfo() static
Definition at line 168 of file MarkovRateTable.cpp.