MOOSE - Multiscale Object Oriented Simulation Environment: /home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/biophysics/MarkovOdeSolver.cpp File Reference
MarkovOdeSolver.cpp File Reference
#include "../basecode/header.h"
#include "MarkovOdeSolver.h"
Functions
static SrcFinfo1< vector< double > > * stateOut ()
Variables
static const Cinfo * MarkovOdeSolverCinfo = MarkovOdeSolver::initCinfo()
Function Documentation
stateOut()
static SrcFinfo1< vector< double > > * stateOut () static
Definition at line 26 of file MarkovOdeSolver.cpp.
{
    static SrcFinfo1< vector< double > > stateOut( "stateOut",
            "Sends updated state to the MarkovChannel class." );
    return &stateOut;
}
References SrcFinfo1< T >::SrcFinfo1().
Referenced by MarkovOdeSolver::initCinfo(), MarkovOdeSolver::process(), and MarkovOdeSolver::reinit().
Variable Documentation
MarkovOdeSolverCinfo
const Cinfo* MarkovOdeSolverCinfo = MarkovOdeSolver::initCinfo() static
Definition at line 133 of file MarkovOdeSolver.cpp.