MOOSE - Multiscale Object Oriented Simulation Environment: /home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/biophysics/MarkovSolverBase.cpp File Reference
MarkovSolverBase.cpp File Reference
#include <cfloat>
#include "../basecode/header.h"
#include "MatrixOps.h"
#include "VectorTable.h"
#include "../builtins/Interpol2D.h"
#include "MarkovRateTable.h"
#include "MarkovSolverBase.h"
Functions
SrcFinfo1< Vector > * stateOut ()
Variables
static const Cinfo * markovSolverBaseCinfo = MarkovSolverBase::initCinfo()
Function Documentation
stateOut()
SrcFinfo1< Vector > * stateOut ()
Definition at line 20 of file MarkovSolverBase.cpp.
{
    static SrcFinfo1< Vector > stateOut("stateOut",
        "Sends updated state to the MarkovChannel class."
        );
    return &stateOut;
}
References SrcFinfo1< T >::SrcFinfo1().
Referenced by MarkovSolverBase::initCinfo(), MarkovSolverBase::process(), and MarkovSolverBase::reinit().
Variable Documentation
markovSolverBaseCinfo
const Cinfo* markovSolverBaseCinfo = MarkovSolverBase::initCinfo() static
Definition at line 187 of file MarkovSolverBase.cpp.