MOOSE - Multiscale Object Oriented Simulation Environment: /home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/mesh/MeshEntry.cpp File Reference
MeshEntry.cpp File Reference
#include "../basecode/header.h"
#include "../basecode/ElementValueFinfo.h"
#include "MeshEntry.h"
#include "Boundary.h"
#include "ChemCompt.h"
Functions
static SrcFinfo5< double, unsigned int, unsigned int, vector< unsigned int >, vector< double > > * remeshOut ()
static SrcFinfo0 * remeshReacsOut ()
Variables
static const Cinfo * meshEntryCinfo = MeshEntry::initCinfo()
Function Documentation
remeshOut()
static SrcFinfo5< double, unsigned int, unsigned int, vector< unsigned int >, vector< double > > * remeshOut () static
Definition at line 17 of file MeshEntry.cpp.
{
    static SrcFinfo5< double, unsigned int, unsigned int, vector< unsigned int>, vector< double > >  remeshOut(
    "remeshOut",
    "Tells the target pool or other entity that the compartment subdivision"
    "(meshing) has changed, and that it has to redo its volume and "
    "memory allocation accordingly."
    "Arguments are: oldvol, numTotalEntries, startEntry, localIndices, vols"
    "The vols specifies volumes of each local mesh entry. It also specifies"
    "how many meshEntries are present on the local node."
    "The localIndices vector is used for general load balancing only."
    "It has a list of the all meshEntries on current node."
    "If it is empty, we assume block load balancing. In this second"
    "case the contents of the current node go from "
    "startEntry to startEntry + vols.size()."
    );
    return &remeshOut;
}
References SrcFinfo5< T1, T2, T3, T4, T5 >::SrcFinfo5().
Referenced by MeshEntry::initCinfo(), and MeshEntry::triggerRemesh().
remeshReacsOut()
static SrcFinfo0 * remeshReacsOut () static
Definition at line 36 of file MeshEntry.cpp.
{
    static SrcFinfo0 remeshReacsOut(
        "remeshReacsOut",
        "Tells connected enz or reac that the compartment subdivision"
        "(meshing) has changed, and that it has to redo its volume-"
        "dependent rate terms like numKf_ accordingly."
    );
    return &remeshReacsOut;
}
References SrcFinfo0::SrcFinfo0().
Referenced by MeshEntry::initCinfo(), and MeshEntry::triggerRemesh().
Variable Documentation
meshEntryCinfo
const Cinfo* meshEntryCinfo = MeshEntry::initCinfo() static
Definition at line 181 of file MeshEntry.cpp.