MOOSE - Multiscale Object Oriented Simulation Environment: moose Namespace Reference
moose Namespace Reference
Namespaces
namespace assertion
namespace detail
namespace details
namespace Parser
Classes
class AdExIF
class AdThreshIF
class Compartment
class CompartmentBase
class CompartmentDataHolder
class ExIF
class IntFireBase
class IzhIF
class LIF
class MooseParser
class normal_distribution
class QIF
class RNG
class VClamp
Typedefs
template<typename T = double>
using MOOSE_NORMAL_DISTRIBUTION = moose::normal_distribution< T >
typedef std::random_device MOOSE_RANDOM_DEVICE
typedef std::mersenne_twister_engine< std::uint_fast32_t, 32, 624, 397, 31, 0x9908b0df, 11, 0xffffffff, 7, 0x9d2c5680, 15, 0xefc60000, 18, 1812433253 > MOOSE_RNG_DEFAULT_ENGINE
template<typename T = double>
using MOOSE_UNIFORM_DISTRIBUTION = std::uniform_real_distribution< T >
Enumerations
enum serverity_level_ {
trace , debug , info , warning ,
fixme , error , fatal , failed
}
Enumerate type for debug and log.
Functions
void __dump__ (string msg, serverity_level_ type=debug, bool autoFormat=true)
void addSolverProf (const string &name, double time, size_t steps)
std::string basename (const std::string &path)
Givem path of MOOSE element, return its name. It's behaviour is like basename of unix command e.g. /a/b/c --> c.
std::string boxed (const std::string &text, const size_t width=70)
std::string capitalize (const string &f)
int checkPath (const string &path)
Checks if given path is correct. If not, return false and error-code as well.
std::string & clean_type_name (std::string &arg)
string colored (string msg)
string colored (string msg, string colorName)
string createMOOSEPath (const string &path)
Create a POSIX compatible path from a given string. Remove/replace bad characters.
bool createParentDirs (const string &path)
Create directories recursively needed to open the given file p.
string debugPrint (string msg, string prefix="DEBUG", string color=T_RESET, unsigned debugLevel=0)
bool endswith (const std::string &full, const std::string &ending)
std::string fix (const std::string myString, const std::string &delimiters=" \t\r\n")
string fixPath (string path)
Fix a path. For testing purpose.
string formattedMsg (string &msg)
const map< std::string, std::string > & getArgMap ()
string getEnv (const string &env)
int getEnvInt (const string &env, const int defaultVal=1)
string getExtension (const string &path, bool without_dot=true)
Get the extension of a given filepath.
int getGlobalSeed ()
void init_symtab (Parser::symbol_table_t &symtab)
char innerType (char typecode)
bool isPrefix (const std::string &a, const std::string &b)
string joinPath (string pathA, string pathB)
Append pathB to pathA and return the result.
void log (string msg, serverity_level_ type=debug, bool redirectToConsole=true, bool removeTicks=true)
Log to console (and to a log-file)
template<typename A , typename B >
string mapToString (const map< A, B > &m, bool value=true)
string moosePathToColumnName (const string &path, char delim, size_t maxParents)
string moosePathToUserPath (string path)
When user gives a path /a/b/c, moose creates a path /a[0]/b[0]/c[0]. This is helpful in cases where one needs to create more than 1 element.
double mtrand (double a, double b)
double mtrand (void)
Generate a random double between 0 and 1.
void mtseed (unsigned int seed)
Seed seed for RNG.
std::string normalizePath (const std::string &path)
string pathToName (const string &path)
Return the name when path is given. Its behaviour is exactly the same as of basename command on unix system.
template<typename T >
void print_array (T *a, size_t n, const string prefix="")
void printSolverProfMap ()
std::string random_string (const unsigned size)
void setGlobalSeed (int seed)
char shortFinfo (std::string ftype)
char shortType (std::string type)
void showDebug (const string msg)
void showError (string msg)
void showInfo (string msg)
void showWarn (string msg)
void split (const string &text, const string &splitat, vector< string > &res)
void splitIntervalInNParts (size_t max, size_t n, std::vector< std::pair< size_t, size_t > > &result)
std::pair< std::string, std::string > splitPath (const std::string &path)
void str_replace_all (std::string &str, const std::string &a, const std::string &b)
int strncasecmp (const std::string &a, const std::string &b, size_t n)
Compares the two strings a and b for first n characters, ignoring the case of the characters. Return 0 in case both are same upto first n characters. Othere a non-zero value is returned. When n is smaller or equal to the size of both strings, positive is return if a is larger than b, or negative when a is smaller than b.
int testTrim ()
std::string textwrap (const std::string &text, const std::string &prefix="", const size_t width=70)
string toFilename (const string &path)
Replace all directory sepearator with _. This creates a filepath which can be created in current directory without any need to create parent directory.
void tokenize (const std::string &str, const std::string &delimiters, std::vector< std::string > &tokens)
string toString (double x)
Convert a given value to string.
std::string trim (const std::string myString, const std::string &delimiters=" \t\r\n")
template<char U = '-'>
std::string underlined (const string &text)
template<typename T = double>
std::string vectorToCSV (const std::vector< T > &vec)
Variables
unsigned long __rng_seed__ = 0
A global seed for all RNGs in moose. When moose.seed(x) is called, this variable is set. Other's RNGs (except muparser) uses this seed to initialize them. By default it is initialized by random_device (see global.cpp).
static const char *const DELIMITERS = " \t\r\n"
static string levels_ [9]
RNG rng
map< string, valarray< double > > solverProfMap
Detailed Description
The CompartmentBase class sets up the interface for all the derived Compartment classes, used in branched nerve calculations. Handles electronic structure and also channels.
The Compartment class sets up an asymmetric compartment for branched nerve calculations. Handles electronic structure and also channels. This is not a particularly efficient way of doing this, so we should use a solver for any substantial calculations.
Typedef Documentation
MOOSE_NORMAL_DISTRIBUTION
template<typename T = double> using moose::MOOSE_NORMAL_DISTRIBUTION = typedef moose::normal_distribution<T>
Definition at line 29 of file Distributions.h.
MOOSE_RANDOM_DEVICE
typedef std::random_device moose::MOOSE_RANDOM_DEVICE
@Synopsis MOOSE's random device. Use it from <random>
Definition at line 29 of file Definitions.h.
MOOSE_RNG_DEFAULT_ENGINE
typedef std::mersenne_twister_engine< std::uint_fast32_t, 32, 624, 397, 31 , 0x9908b0df, 11 , 0xffffffff, 7 , 0x9d2c5680, 15 , 0xefc60000, 18, 1812433253 > moose::MOOSE_RNG_DEFAULT_ENGINE
@Synopsis Global random number generator engine. Everywhere we use this engine.
Definition at line 42 of file Definitions.h.
MOOSE_UNIFORM_DISTRIBUTION
template<typename T = double> using moose::MOOSE_UNIFORM_DISTRIBUTION = typedef std::uniform_real_distribution<T>
Definition at line 26 of file Distributions.h.
Enumeration Type Documentation
serverity_level_
enum moose::serverity_level_
Enumerate type for debug and log.
Enumerator
trace
debug
info
warning
fixme
error
fatal
failed
Definition at line 82 of file print_function.hpp.
{
        trace, debug, info , warning, fixme , error, fatal, failed
    };
Function Documentation
__dump__()
void moose::__dump__ (string msg, serverity_level_ type = debug, bool autoFormat = true) inline
Definition at line 175 of file print_function.hpp.
    {
        stringstream ss;
        ss << "[" << levels_[type] << "] ";
        bool set = false;
        bool reset = true;
        string color = T_GREEN;
        if(type == warning || type == fixme )
            color = T_YELLOW;
        else if(type ==  debug )
            color = T_CYAN;
        else if(type == error || type == failed )
            color = T_RED;
        else if(type == info )
            color = T_MAGENTA;
        for(unsigned int i = 0; i < msg.size(); ++i)
        {
            if('`' == msg[i])
            {
                if(!set && reset)
                {
                    set = true;
                    reset = false;
                    ss << color;
                }
                else if(set && !reset)
                {
                    reset = true;
                    set = false;
                    ss << T_RESET;
                }
            }
            else if('\n' == msg[i])
                ss << "\n | ";
            else
                ss << msg[i];
        }
        /*  Be safe than sorry */
        if(!reset)
            ss << T_RESET;
        cout << ss.str() << endl;
    }
References debug, error, failed, fixme, info, levels_, and warning.
Referenced by log(), showDebug(), showError(), showInfo(), and showWarn().
addSolverProf()
void moose::addSolverProf (const string & name, double time, size_t steps = 1)
@Synopsis Add solver performance into the global map.
@Param name Name of the solver. @Param time Time taken by the solver. @Param steps Steps.
Definition at line 234 of file global.cpp.
{
    solverProfMap[name] =
        solverProfMap[name] + valarray<double>({time, (double)steps});
}
References solverProfMap.
Referenced by HSolve::process().
basename()
std::string moose::basename (const std::string & path) inline
Givem path of MOOSE element, return its name. It's behaviour is like basename of unix command e.g. /a/b/c --> c.
Returns
Definition at line 47 of file utility.h.
    {
        return path.substr( path.find_last_of('/') + 1 );
    }
boxed()
std::string moose::boxed (const std::string & text, const size_t width = 70)
Definition at line 266 of file strutil.cpp.
{
    return fmt::format(
        "┌{0:─^{2}}┐\n"
        "│{1: ^{2}}│\n"
        "└{0:─^{2}}┘\n",
        "", text, width);
}
capitalize()
std::string moose::capitalize (const string & f)
Definition at line 275 of file strutil.cpp.
{
    string ff(f);
    ff[0] = std::toupper(ff[0]);
    return ff;
}
Referenced by pymoose::getClassFieldsDoc().
checkPath()
int moose::checkPath (const string & path)
Checks if given path is correct. If not, return false and error-code as well.
Parameters
path Path name.
Returns
0 if path is all-right. Negative number if path is not OK.
Definition at line 47 of file global.cpp.
{
    if (path.size() < 1)
        return EMPTY_PATH;
    if (path.find_first_of(" \\!") != std::string::npos)
        return BAD_CHARACTER_IN_PATH;
    if (path[path.size() - 1] != ']')
    {
        return MISSING_BRACKET_AT_END;
    }
    return 0;
}
Referenced by fixPath().
clean_type_name()
string & moose::clean_type_name (std::string & arg)
Definition at line 39 of file strutil.cpp.
{
    for(size_t pos = arg.find(' '); pos != string::npos; pos = arg.find(' ')) {
        arg.replace(pos, 1, 1, '_');
    }
    for(size_t pos = arg.find('<'); pos != string::npos; pos = arg.find('<')) {
        arg.replace(pos, 1, 1, '_');
    }
    for(size_t pos = arg.find('>'); pos != string::npos; pos = arg.find('>')) {
        arg.replace(pos, 1, 1, '_');
    }
    return arg;
}
colored() [1/2]
string moose::colored (string msg) inline
Definition at line 142 of file print_function.hpp.
    {
        stringstream ss;
        ss << T_RED << msg << T_RESET;
        return ss.str();
    }
colored() [2/2]
string moose::colored (string msg, string colorName) inline
Definition at line 149 of file print_function.hpp.
    {
        stringstream ss;
        ss << colorName << msg << T_RESET;
        return ss.str();
    }
createMOOSEPath()
string moose::createMOOSEPath (const string & path)
Create a POSIX compatible path from a given string. Remove/replace bad characters.
Parameters
path Reutrn path is given path if creation was successful, else directory is renamed to a filename.
Definition at line 84 of file global.cpp.
{
    string s = path; /* Local copy */
    // Remove [0] from paths. They will be annoying for normal users.
    std::string::size_type n = 0;
    string zeroIndex("[0]");
    while ((n = s.find(zeroIndex, n)) != std::string::npos)
        s.erase(n, zeroIndex.size());
    return s;
}
Referenced by moosePathToUserPath(), and Table::setDatafile().
createParentDirs()
bool moose::createParentDirs (const string & path)
Create directories recursively needed to open the given file p.
Create directory, recursively.
Parameters
path When successfully created, returns created path, else convert path to a filename by replacing '/' by '_'.
Definition at line 101 of file global.cpp.
{
    // Remove the filename from the given path so we only have the
    // directory.
    string p = path;
    bool failed = false;
    size_t pos = p.find_last_of('/');
    if (pos != std::string::npos)
        p = p.substr(0, pos);
    else /* no parent directory to create */
        return true;
    if (p.size() == 0)
        return true;
    string command("mkdir -p ");
    command += p;
    int ret = system(command.c_str());
    struct stat info;
    if (stat(p.c_str(), &info) != 0)
    {
        LOG(moose::warning, "cannot access " << p);
        return false;
    }
    else if (info.st_mode & S_IFDIR)
    {
        LOG(moose::info, "Created directory " << p);
        return true;
    }
    else
    {
        LOG(moose::warning, p << " is no directory");
        return false;
    }
    return true;
}
References info, and warning.
Referenced by Table::setDatafile(), and Streamer::setDatafilePath().
debugPrint()
string moose::debugPrint (string msg, string prefix = "DEBUG", string color = T_RESET, unsigned debugLevel = 0) inline
Definition at line 157 of file print_function.hpp.
    {
        stringstream ss; ss.str("");
        if(debugLevel <= DEBUG_LEVEL)
        {
            ss << setw(debugLevel/2) << "[" << prefix << "] "
                << color << msg << T_RESET;
        }
        return ss.str();
    }
endswith()
bool moose::endswith (const std::string & full, const std::string & ending)
Definition at line 129 of file strutil.cpp.
{
    if(full.length() < ending.length()) {
        return false;
    }
    return (0 == full.compare(full.length() - ending.length(), ending.length(),
                              ending));
}
fix()
std::string moose::fix (const std::string myString, const std::string & delimiters = " \t\r\n")
Fix the user-given path whenever possible
Definition at line 69 of file strutil.cpp.
{
    string trimmedPath = trim(userPath, delimiters);
    string fixedPath;
    char prev = 0;
    // In this loop, we check if there are more than one '/' together. If yes,
    // then accept only first one and reject other.
    for(unsigned int i = 0; i < trimmedPath.size(); ++i) {
        const char c = trimmedPath[i];
        if(c != '/' || c != prev)
            fixedPath.push_back(c);
        prev = c;
    }
    return fixedPath;
}
References trim().
fixPath()
string moose::fixPath (string path)
Fix a path. For testing purpose.
Parameters
path Path as string.
Returns
A fixed path.
Definition at line 71 of file global.cpp.
{
    int pathOk = moose::checkPath(path);
    if (pathOk == 0)
        return path;
    else if (pathOk == MISSING_BRACKET_AT_END)
        return path + "[0]";
    return path;
}
References checkPath().
Referenced by HSolveUtils::gates(), and joinPath().
formattedMsg()
string moose::formattedMsg (string & msg) inline
Definition at line 266 of file print_function.hpp.
    {
        msg.erase(remove_if(msg.begin(), msg.end(), [] (unsigned char x){return '`' == x;}));
        return msg;
    }
Referenced by log().
getArgMap()
const map< string, string > & moose::getArgMap ()
Definition at line 44 of file setupenv.cpp.
{
    static map<string, string> argmap;
    if (argmap.empty())
    {
        char * verbosity = getenv("VERBOSITY");
        if (verbosity != NULL)
        {
            argmap.insert(pair<string, string>("VERBOSITY", string(verbosity)));
        }
        else
        {
            argmap.insert(pair<string, string>("VERBOSITY", "0"));
        }
        char * isInfinite = getenv("INFINITE");
        if (isInfinite != NULL)
        {
            argmap.insert(pair<string, string>("INFINITE", string(isInfinite)));
        }
        char * numNodes = getenv("NUMNODES");
        if (numNodes != NULL)
        {
            argmap.insert(pair<string, string>("NUMNODES", string(numNodes)));
        }
        char * doQuit = getenv("QUIT");
        if (doQuit != NULL)
        {
            argmap.insert(pair<string, string>("QUIT", string(doQuit)));
        }
        char * doUnitTests = getenv("DOUNITTESTS");
        if (doUnitTests != NULL)
        {
            argmap.insert(pair<string, string>("DOUNITTESTS", string(doUnitTests)));
        }
    }
    return argmap;
}
getEnv()
string moose::getEnv (const string & env)
@Synopsis Get environment valus.
@Param env Name of the environment variable.
@Returns value of environment if set, empty string otherwise.
Definition at line 92 of file setupenv.cpp.
{
    const char* pEnv = std::getenv( env.c_str() );
    if( pEnv )
        return string(pEnv);
    return "";
}
Referenced by getEnvInt().
getEnvInt()
int moose::getEnvInt (const string & env, const int defaultVal = 1)
Definition at line 100 of file setupenv.cpp.
{
    string e = getEnv(env);
    if(e.empty())
        return defaultVal;
    try
    {
        return std::stoi(e);
    }
    catch(std::exception& exc)
    {
        return defaultVal;
    }
}
References getEnv().
Referenced by Gsolve::Gsolve(), and Ksolve::Ksolve().
getExtension()
string moose::getExtension (const string & path, bool without_dot = true)
Get the extension of a given filepath.
Parameters
path Given path.
Returns
Extension (with or without preceeding '.')
Definition at line 148 of file global.cpp.
{
    size_t dotPos = path.find_last_of('.');
    if (dotPos == std::string::npos)
        return "";
    if (without_dot)
        return path.substr(dotPos + 1);
    return path.substr(dotPos);
}
Referenced by Table::setDatafile(), and Streamer::setDatafilePath().
getGlobalSeed()
int moose::getGlobalSeed ()
@Synopsis Get the global seed set by call of moose.seed(X)
@Returns seed (int).
Definition at line 42 of file randnum.cpp.
{
    return __rng_seed__;
}
References __rng_seed__.
Referenced by Gsolve::Gsolve(), GssaVoxelPools::reinit(), GraupnerBrunel2012CaPlasticitySynHandler::reinitSeed(), and SparseMsg::SparseMsg().
init_symtab()
void moose::init_symtab (Parser::symbol_table_t & symtab)
Definition at line 31 of file MooseParser.cpp.
{
    symtab.add_function("ln", MooseParser::Ln);
    symtab.add_function("rand", MooseParser::Rand);  // between 0 and 1
    symtab.add_function("rnd", MooseParser::Rand);   // between 0 and 1
    symtab.add_function("srand", MooseParser::SRand);
    symtab.add_function("rand2", MooseParser::Rand2);
    symtab.add_function("srand2", MooseParser::SRand2);
    symtab.add_function("fmod", MooseParser::Fmod);
}
References moose::MooseParser::Fmod(), moose::MooseParser::Ln(), moose::MooseParser::Rand(), moose::MooseParser::Rand2(), moose::MooseParser::SRand(), and moose::MooseParser::SRand2().
Referenced by moose::MooseParser::MooseParser(), and moose::MooseParser::ParseVariables().
innerType()
char moose::innerType (char typecode)
isPrefix()
bool moose::isPrefix (const std::string & a, const std::string & b)
Definition at line 187 of file strutil.cpp.
{
    if(a.size() < b.size())
        return false;
    return (b.find(a, 0) == 0);
}
joinPath()
string moose::joinPath (string pathA, string pathB)
Append pathB to pathA and return the result.
If pathA does not have [indexs] at the end, append "[0]" to pathA and then add pathB to it. This version does not care if the result has '[0]' at its end.
Parameters
pathA First path.
pathB Second path.
Returns
A string representing moose-path.
Definition at line 63 of file global.cpp.
{
    pathA = moose::fixPath(pathA);
    string newPath = pathA + "/" + pathB;
    return moose::fixPath(newPath);
}
References fixPath().
log()
void moose::log (string msg, serverity_level_ type = debug, bool redirectToConsole = true, bool removeTicks = true) inline
Log to console (and to a log-file)
Parameters
msg String, message to be written.
type Type of the message.
redirectToConsole
removeTicks
Definition at line 280 of file print_function.hpp.
    {
        if(redirectToConsole)
            __dump__(msg, type, true);
        /* remove any backtick from the string. */
        formattedMsg( msg );
        fstream logF;
        logF.open( "__moose__.log", ios::app);
        time_t rawtime; time(&rawtime);
        struct tm* timeinfo;
        timeinfo = localtime(&rawtime);
        logF << asctime(timeinfo) << ": " << msg;
        logF.close();
    }
References __dump__(), and formattedMsg().
mapToString()
template<typename A , typename B > string moose::mapToString (const map< A, B > & m, bool value = true)
Definition at line 101 of file print_function.hpp.
        {
            unsigned int width = 81;
            unsigned int size = 0;
            vector<string> row;
            /* Get the maximum size of any entry in map */
            stringstream ss;
            typename map<A, B>::const_iterator it;
            for(it = m.begin(); it != m.end(); it++)
            {
                ss.str("");
                ss << it->first;
                if(value)
                    ss << ": " << it->second;
                row.push_back(ss.str());
                if(ss.str().size() > size)
                    size = ss.str().size()+1;
            }
            unsigned int colums = width / size;
            ss.str("");
            size_t i = 0;
            for(unsigned int ii = 0; ii < row.size(); ii++)
            {
                if(i < colums)
                {
                    ss << setw(size+1) << row[ii];
                    i++;
                }
                else
                {
                    ss << endl;
                    i = 0;
                }
            }
            return ss.str();
        }
moosePathToColumnName()
string moose::moosePathToColumnName (const string & path, char delim, size_t maxParents)
@Synopsis Generate a suitable column name based on given path. Replace [\d+] with \d+; and remove [\0+]. Replace / with given delim (default '.')
@Param path (string). @Param delim (char) @Param maxLevel (int). Max number of parents to include. Default 1.
@Returns Reformatted path suitable for column name.
Example:
/a[12]/d[0]/e[1]/d[0] -> e1.d /a[12]/d[0] -> e12.d /a[00]/b[0] -> a.b
@Synopsis Genearate a suitable string for column name which can be used in a spreadsheet/numpy table/csv file etc.
Definition at line 192 of file global.cpp.
{
    string s(path);
    static std::regex e0("\\[(0+)\\]");    // Remove [0+]
    static std::regex e1("\\[(\\d+)\\]");  // Replace [xyz] by xyz
    s = std::regex_replace(s, e0, "");
    s = std::regex_replace(s, e1, "$1");
    string s2;
    string colname = "";
    size_t nBreak = 0;
    // Keep as many parents as required by maxParents. Using reverse magic.
    for (auto rit = s.rbegin(); rit != s.rend(); rit++)
    {
        if (*rit == '/')
        {
            colname = s2 + delim + colname;
            s2 = "";
            nBreak += 1;
            if (nBreak == (1 + maxParents))
                break;
        }
        else
            s2 = *rit + s2;
    }
    colname.pop_back();
    return colname;
}
Referenced by Streamer::addTable(), and Table::reinit().
moosePathToUserPath()
string moose::moosePathToUserPath (string path)
When user gives a path /a/b/c, moose creates a path /a[0]/b[0]/c[0]. This is helpful in cases where one needs to create more than 1 element.
Parameters
path Removed '[0]' from path and return.
Returns
Definition at line 167 of file global.cpp.
{
    // Just write the moose path. Things becomes messy when indexing is
    // used.
    return createMOOSEPath(path);
}
References createMOOSEPath().
Referenced by SocketStreamer::addTable(), Streamer::reinit(), and Table::reinit().
mtrand() [1/2]
double moose::mtrand (double a, double b)
@Synopsis Overloaded function. Random number between a and b
@Param a lower limit. @Param b Upper limit.
@Returns
Definition at line 37 of file randnum.cpp.
{
    return (b - a) * mtrand() + a;
}
References mtrand().
Referenced by moose::MooseParser::Rand2(), and moose::MooseParser::SRand2().
mtrand() [2/2]
double moose::mtrand (void)
Generate a random double between 0 and 1.
Returns
A random number between 0 and 1.
Definition at line 32 of file randnum.cpp.
{
    return moose::rng.uniform();
}
References rng, and moose::RNG::uniform().
Referenced by addPos(), makeAngleDistrib(), makeSizeDistrib(), mtrand(), RandSpike::process(), moose::MooseParser::Rand(), SeqSynHandler::refillSynapseOrder(), RandSpike::reinit(), moose::MooseParser::SRand(), testSparseMsg(), and moose::Compartment::vRandInject().
mtseed()
void moose::mtseed (unsigned int x)
Seed seed for RNG.
Set the global seed or all rngs.
Parameters
seed
x
Definition at line 23 of file randnum.cpp.
{
    static bool isRNGInitialized = false;
    moose::__rng_seed__ = x;
    moose::rng.setSeed(x);
    isRNGInitialized = true;
}
References __rng_seed__, rng, and moose::RNG::setSeed().
Referenced by SeqSynHandler::refillSynapseOrder(), moose::MooseParser::SRand(), and moose::MooseParser::SRand2().
normalizePath()
string moose::normalizePath (const std::string & path)
@Synopsis Normalize given path.
@Param path
@Returns
@Synopsis Normalize a given path by removing multiple repeating // to / and /./ to /
@Param path
@Returns
Definition at line 222 of file strutil.cpp.
{
    string s(path);
    static std::regex e0("/+");  // Remove multiple / by single /
    s = std::regex_replace(s, e0, "/");
    static std::regex e1("/(\\./)+");  // Remove multiple / by single /
    s = std::regex_replace(s, e1, "/");
    return s;
}
Referenced by pymoose::createElementFromPath(), and test_normalize_path().
pathToName()
string moose::pathToName (const string & path)
Return the name when path is given. Its behaviour is exactly the same as of basename command on unix system.
Parameters
path
Returns
name.
Definition at line 161 of file global.cpp.
{
    return path.substr(path.find_last_of('/'));
}
print_array()
template<typename T > void moose::print_array (T * a, size_t n, const string prefix = "")
Definition at line 304 of file print_function.hpp.
    {
        stringstream ss;
        ss << prefix;
        for (size_t i = 0; i < n; i++)
        {
            ss << a[i] << ' ';
            if( (i+1) % 20 == 0 )
                ss << endl;
        }
        ss << endl;
        cerr << ss.str();
    }
printSolverProfMap()
void moose::printSolverProfMap ()
Definition at line 240 of file global.cpp.
{
    for (auto& v : solverProfMap)
        cout << '\t' << v.first << ": " << v.second[0] << " sec ("
             << v.second[1] << ")" << endl;
}
References solverProfMap.
Referenced by Shell::doStart().
random_string()
string moose::random_string (const unsigned size)
Generate random string of given length.
Definition at line 153 of file strutil.cpp.
{
    static const char alphanum[] =
        "0123456789"
        "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
        "abcdefghijklmnopqrstuvwxyz";
    string s(len, '_');
    for(unsigned i = 0; i < len; ++i) {
        s[i] = alphanum[rand() % (sizeof(alphanum) - 1)];
    }
    return s;
}
setGlobalSeed()
void moose::setGlobalSeed (int seed)
@Synopsis Set the seed for all random generator. When seed of a RNG is not set, this seed it used. It is set to -1 by default.
@Param seed
Definition at line 47 of file randnum.cpp.
{
    __rng_seed__ = seed;
}
References __rng_seed__.
Referenced by testSparseMsg().
shortFinfo()
char moose::shortFinfo (std::string ftype)
shortType()
char moose::shortType (std::string type)
showDebug()
void moose::showDebug (const string msg) inline
Definition at line 234 of file print_function.hpp.
    {
#ifdef DISABLE_DEBUG
#else
        moose::__dump__(msg, moose::debug );
#endif
    }
References __dump__(), and debug.
showError()
void moose::showError (string msg) inline
Definition at line 242 of file print_function.hpp.
    {
        moose::__dump__( msg, moose::error );
    }
References __dump__(), and error.
showInfo()
void moose::showInfo (string msg) inline
Definition at line 224 of file print_function.hpp.
    {
        moose::__dump__( msg, moose::info );
    }
References __dump__(), and info.
showWarn()
void moose::showWarn (string msg) inline
Definition at line 229 of file print_function.hpp.
    {
        moose::__dump__(msg, moose::warning );
    }
References __dump__(), and warning.
Referenced by cnpy2::appendNumpy(), Cell::findCompt(), SocketStreamer::reinit(), Streamer::reinit(), Ksolve::setMethod(), Cell::setupSolver(), Shell::warning(), and cnpy2::writeNumpy().
split()
void moose::split (const string & text, const string & splitat, vector< string > & res)
Definition at line 232 of file strutil.cpp.
{
    // From https://stackoverflow.com/a/46931770/1805129
    string token;
    size_t pos_start = 0, pos_end, delim_len = delimiter.size();
    while ((pos_end = text.find (delimiter, pos_start)) != string::npos) {
        token = text.substr (pos_start, pos_end - pos_start);
        pos_start = pos_end + delim_len;
        res.push_back (token);
    }
    res.push_back (text.substr (pos_start));
}
splitIntervalInNParts()
void moose::splitIntervalInNParts (size_t max, size_t n, std::vector< std::pair< size_t, size_t > > & result)
@Synopsis Split a interval (0, max) in n parts which are almost equal to each other.
@Param max @Param n @Param result. A vector of interval [start, end) (as std::pair).
Definition at line 16 of file utility.cpp.
    {
        size_t start = 0;
        size_t stop = 0;
        while(n > 0)
        {
            size_t f = (size_t) (max / n);
            stop += f;
            result.push_back({start, stop});
            start = stop;
            n -= 1;
            max -= f;
        }
        assert(max == 0);
    }
Referenced by Ksolve::reinit().
splitPath()
std::pair< std::string, std::string > moose::splitPath (const std::string & path)
@Synopsis Split a given path into (parent, name). The behaviour of this function is akin to unix'; dirname and basepath.
@Param path
@Returns A pair of strings <parent, name>
Definition at line 204 of file strutil.cpp.
{
    assert(path[0] == '/');
    auto i = path.find_last_of('/');
    auto parentPath = i > 0 ? path.substr(0, i) : "/";
    return std::make_pair(parentPath, path.substr(i + 1));
}
Referenced by pymoose::createElementFromPath().
str_replace_all()
void moose::str_replace_all (std::string & str, const std::string & a, const std::string & b)
Definition at line 168 of file strutil.cpp.
{
    if(a.size() == 0)
        return;
    size_t index = 0;
    while(true) {
        /* Locate the substring to replace. */
        index = str.find(a, index);
        if(index == std::string::npos)
            break;
        /* Make the replacement. */
        str.erase(index, a.size());
        str.insert(index, b);
    }
}
Referenced by moose::MooseParser::Reformat().
strncasecmp()
int moose::strncasecmp (const std::string & a, const std::string & b, size_t n)
Compares the two strings a and b for first n characters, ignoring the case of the characters. Return 0 in case both are same upto first n characters. Othere a non-zero value is returned. When n is smaller or equal to the size of both strings, positive is return if a is larger than b, or negative when a is smaller than b.
When n is larger than size of a or b, non-zero values is returned when a and b are not equal upto min(n, min(a.size(), b.size())) characters.
Parameters
a First string.
b Second string.
n Compare up n characters/bytes.
Definition at line 139 of file strutil.cpp.
{
    for(size_t i = 0; i < std::min(n, b.size()); ++i)
        if(tolower(a[i]) != tolower(b[i]))
            return tolower(a[i]) - tolower(b[i]);
    if(b.size() < n)
        return a.size() - b.size();
    return 0;
}
Referenced by NeuroNode::findStartNode(), and NeuroMesh::putSomaAtStart().
testTrim()
int moose::testTrim ()
Definition at line 87 of file strutil.cpp.
{
    std::string testStrings[] = {" space at beginning",
                                 "space at end ",
                                 " space at both sides ",
                                 "\ttab at beginning",
                                 "tab at end\t",
                                 "\ttab at both sides\t",
                                 "\nnewline at beginning",
                                 "newline at end\n",
                                 "\nnewline at both sides\n",
                                 "\n\tnewline and tab at beginning",
                                 "space and tab at end \t",
                                 "   \rtab and return at both sides \r"};
    std::string results[] = {"space at beginning",
                             "space at end",
                             "space at both sides",
                             "tab at beginning",
                             "tab at end",
                             "tab at both sides",
                             "newline at beginning",
                             "newline at end",
                             "newline at both sides",
                             "newline and tab at beginning",
                             "space and tab at end",
                             "tab and return at both sides"};
    bool success = true;
    for(unsigned int i = 0; i < sizeof(testStrings) / sizeof(*testStrings);
        ++i) {
        std::string trimmed = trim(testStrings[i]);
        success = (results[i].compare(trimmed) == 0);
        cout << "'" << trimmed << "'" << (success ? " SUCCESS" : "FAILED")
             << endl;
    }
    return success ? 1 : 0;
}
References trim().
textwrap()
string moose::textwrap (const std::string & text, const std::string & prefix = "", const size_t width = 70)
Definition at line 245 of file strutil.cpp.
{
    vector<string> words;
    tokenize(text, " \n", words);
    string res;
    size_t size = 0;
    for(const auto& w : words) {
        if(size == 0) {
            res += prefix;
            size = prefix.size();
        }
        res += w + ' ';
        size += w.size() + 1;
        if(size > width) {
            res += '\n';
            size = 0;
        }
    }
    return res;
}
References tokenize().
toFilename()
string moose::toFilename (const string & path)
Replace all directory sepearator with _. This creates a filepath which can be created in current directory without any need to create parent directory.
Parameters
path string
Returns
filename without directory separator.
Definition at line 139 of file global.cpp.
{
    string p = path;
    std::replace(p.begin(), p.end(), '/', '_');
    std::replace(p.begin(), p.end(), '\\', '_');
    return p;
}
Referenced by Table::setDatafile(), and Streamer::setDatafilePath().
tokenize()
void moose::tokenize (const std::string & str, const std::string & delimiters, std::vector< std::string > & tokens)
Splits given string into tokens
Definition at line 22 of file strutil.cpp.
{
    // Token boundaries
    string::size_type begin = str.find_first_not_of(delimiters, 0);
    string::size_type end = str.find_first_of(delimiters, begin);
    while(string::npos != begin || string::npos != end) {
        // Found a token, add it to the vector.
        tokens.push_back(str.substr(begin, end - begin));
        // Update boundaries
        begin = str.find_first_not_of(delimiters, end);
        end = str.find_first_of(delimiters, begin);
    }
}
Referenced by ReadCell::addChannelMessage(), pymoose::LookupField::LookupField(), ReadCell::readData(), ReadCell::readScript(), textwrap(), and pymoose::VecLookupField::VecLookupField().
toString()
string moose::toString (double x)
Convert a given value to string.
Template Parameters
T
Parameters
x
Returns
String representation
Definition at line 226 of file global.cpp.
{
    char buffer[50];
    snprintf(buffer, sizeof buffer, "%.17g", x);
    return string(buffer);
}
Referenced by StreamerBase::writeToCSVFile().
trim()
std::string moose::trim (const std::string myString, const std::string & delimiters = " \t\r\n")
trims the leading and trailing white spaces
Definition at line 53 of file strutil.cpp.
{
    if(myString.length() == 0) {
        return myString;
    }
    string::size_type end = myString.find_last_not_of(delimiters);
    string::size_type begin = myString.find_first_not_of(delimiters);
    if(begin != string::npos) {
        return std::string(myString, begin, end - begin + 1);
    }
    return "";
}
Referenced by chopLine(), HHGate::fillFromExpr(), findModelType(), fix(), innerLoadXplot(), ReadCell::innerRead(), ReadKkit::innerRead(), Interpol2D::load(), and testTrim().
underlined()
template<char U = '-'> std::string moose::underlined (const string & text)
Definition at line 90 of file strutil.h.
{
    // This is bit clumsy to read.
    return fmt::format(string("{1:^{2}}\n{0:") + U + string("^{2}}\n"), "",
                       text, text.size());
}
vectorToCSV()
template<typename T = double> std::string moose::vectorToCSV (const std::vector< T > & vec)
@Synopsis Converts a vector to string.
@Param vec
@Returns
Definition at line 107 of file strutil.h.
{
    std::stringstream ss;
    for(size_t i = 0; i < vec.size(); i++)
        ss << vec[i] << ',';
    auto res = ss.str();
    if(',' == res.back())
        res.pop_back();
    return res;
}
Variable Documentation
__rng_seed__
unsigned long moose::__rng_seed__ = 0
A global seed for all RNGs in moose. When moose.seed(x) is called, this variable is set. Other's RNGs (except muparser) uses this seed to initialize them. By default it is initialized by random_device (see global.cpp).
Definition at line 14 of file randnum.cpp.
Referenced by getGlobalSeed(), mtseed(), setGlobalSeed(), and ZombieCompartment::vReinit().
DELIMITERS
const char* const moose::DELIMITERS = " \t\r\n" static
List of characters considered to be whitespace
Definition at line 21 of file strutil.h.
levels_
string moose::levels_[9] static
Initial value:
= {
        "TRACE", "DEBUG", "INFO", "WARNING", "FIXME" , "ERROR", "FATAL", "FAILED"
    }
Definition at line 86 of file print_function.hpp.
{
        "TRACE", "DEBUG", "INFO", "WARNING", "FIXME" , "ERROR", "FATAL", "FAILED"
    };
Referenced by __dump__().
rng
RNG moose::rng
@Synopsis Global RNG.
Definition at line 16 of file randnum.cpp.
Referenced by approximateWithInteger(), mtrand(), and mtseed().
solverProfMap
map< string, valarray< double > > moose::solverProfMap
Initial value:
= {{"Ksolve", {0.0, 0}},
    {"HSolve", {0.0, 0}}
}
Definition at line 41 of file global.cpp.
                                              {{"Ksolve", {0.0, 0}},
    {"HSolve", {0.0, 0}}
};
Referenced by addSolverProf(), and printSolverProfMap().