MOOSE - Multiscale Object Oriented Simulation Environment: pymoose Namespace Reference
pymoose Namespace Reference
Namespaces
namespace docs
Classes
struct ElementField
For FieldElementFinfo - vector of elements.
struct ElementFieldIterator
Iterator class for ElementField.
struct LookupField
For LookupValueFinfo - dict-like access.
class MooseVec
struct MooseVecIterator
struct VecElementField
struct VecLookupField
Modified LookupField to allow vectorized assignment and lookup.
Typedefs
template<typename KeyT >
using LookupGetter = std::function< nb::object(const ObjId &, const string &, const KeyT &)>
Enumerations
enum class MsgDirection { Out = 0 , In = 1 , Both = 2 }
Functions
ObjId connect (const ObjId &src, const string &srcField, const ObjId &tgt, const string &tgtField, const string &msgType)
Connect to another ObjId.
ObjId connectToVec (const ObjId &src, const string &srcField, const MooseVec &tgt, const string &tgtField, const string &msgType)
Connect to a vec object.
ObjId convertToObjId (const nb::object &arg)
Convert Python object wrapping path or ObjId or Id into ObjId.
MooseVec copy (const nb::object &elem, const nb::object &newParent, const string &newName="", unsigned int n=1, bool toGlobal=false, bool copyExtMsgs=false)
Copy object, return the copied vec object.
nb::object createDestFunction (const ObjId &oid, const Finfo *finfo)
ObjId createElementFromPath (const string &type, const string &p, unsigned int numdata)
Create a new vector of class type at path p, with numdata elements.
bool doDelete (nb::object &obj)
string fieldDocFormatted (const string &name, const Cinfo *cinfo, const Finfo *finfo, const string &prefix="")
std::string getClassAttributeDoc (const Cinfo *cinfo, const std::string &fname)
std::string getClassDoc (const std::string &className)
std::string getClassFieldsDoc (const Cinfo *cinfo, const std::string &ftype, const std::string &prefix)
Get the class fields documentation.
nb::object getCwe ()
Get current working element.
std::string getDoc (const std::string &query)
nb::object getFieldGeneric (const ObjId &oid, const std::string &fieldName)
vector< string > getFieldNames (const string &className, const string &fieldType)
map< string, string > getFieldTypeDict (const string &className, const string &fieldType)
nb::object getFieldValue (const ObjId &oid, const Finfo *f)
Common function to get value fiields.
map< std::string, Finfo * > getFinfoDict (const Cinfo *cinfo, const std::string &fieldType)
Get a map of field names to Finfo*.
vector< ObjId > getNeighbors (const nb::object &obj, const string &fieldName, const string &msgType, MsgDirection direction)
Shell * getShellPtr (void)
Shorthand to access shell pointer.
map< string, string > getVersionInfo ()
void handleKeyboardInterrupts (int signum)
Id initShell ()
Initialize shell object.
void listElements (const nb::object &arg)
Show elements (le)
vector< ObjId > listMsg (const nb::object &arg, MsgDirection direction=MsgDirection::Both)
Get a list of Msg objects.
ObjId loadModelInternal (const string &fname, const string &modelpath, const string &solverclass="")
Model loaders built into Shell, others can be implemented in Python.
void move (const nb::object &elem, const nb::object &newParent)
Move object, return None.
void setClock (const unsigned int clockId, double dt)
void setCwe (const nb::object &arg)
Set current working element (ce)
bool setFieldGeneric (const ObjId &oid, const std::string &fieldName, const nb::object &val)
void showMsg (const nb::object &arg, MsgDirection direction=MsgDirection::Both)
Show messages (showmsg)
void start (double runtime, bool notify=false)
void useClock (size_t tick, const string &path, const string &fn)
Variables
static const std::map< std::string, LookupGetter< int > > intKeyGetters
static const std::map< std::string, LookupGetter< long > > longKeyGetters
static const std::map< std::string, LookupGetter< string > > stringKeyGetters
static const std::map< std::string, LookupGetter< unsigned int > > uintKeyGetters
Typedef Documentation
LookupGetter
template<typename KeyT > using pymoose::LookupGetter = typedef std::function<nb::object(const ObjId&, const string&, const KeyT&)>
Definition at line 26 of file Finfo.cpp.
Enumeration Type Documentation
MsgDirection
enum class pymoose::MsgDirection strong
Enumerator
Out
In
Both
Definition at line 27 of file pymoose.h.
{ Out = 0, In = 1, Both = 2 };
Function Documentation
connect()
ObjId pymoose::connect (const ObjId & src, const string & srcField, const ObjId & tgt, const string & tgtField, const string & msgType)
Connect to another ObjId.
Definition at line 872 of file helper.cpp.
{
    return getShellPtr()->doAddMsg(msgType, src, srcField, tgt, tgtField);
}
References Shell::doAddMsg(), and getShellPtr().
Referenced by pymoose::MooseVec::connectToSingle(), connectToVec(), and pymoose::MooseVec::connectToVec().
connectToVec()
ObjId pymoose::connectToVec (const ObjId & src, const string & srcField, const MooseVec & tgt, const string & tgtField, const string & msgType)
Connect to a vec object.
Definition at line 878 of file helper.cpp.
{
    return connect(src, srcField, tgt.oid(), tgtField, msgType);
}
References connect(), and pymoose::MooseVec::oid().
convertToObjId()
ObjId pymoose::convertToObjId (const nb::object & arg)
Convert Python object wrapping path or ObjId or Id into ObjId.
Definition at line 639 of file helper.cpp.
{
    ObjId ret;
    if(nb::isinstance<nb::str>(arg)) {
        ret = ObjId(nb::cast<string>(arg));
        if(ret.bad()) {
            throw nb::value_error(
                ("object does not exist: " + nb::cast<string>(arg)).c_str());
        }
    }
    else if(nb::isinstance<MooseVec>(arg)) {
        ret = nb::cast<MooseVec>(arg).oid();
    }
    else if(nb::isinstance<Id>(arg)) {
        ret = nb::cast<Id>(arg);
    }
    else if(nb::isinstance<ObjId>(arg)) {
        ret = nb::cast<ObjId>(arg);
    }
    else {
        throw nb::type_error("expected str, ObjId, Id, or MooseVec");
    }
    return ret;
}
References ObjId::bad().
copy()
MooseVec pymoose::copy (const nb::object & elem, const nb::object & newParent, const string & newName = "", unsigned int n = 1, bool toGlobal = false, bool copyExtMsgs = false)
Copy object, return the copied vec object.
Definition at line 675 of file helper.cpp.
{
    ObjId orig = convertToObjId(elem);
    ObjId newp = convertToObjId(newParent);
    string name = moose::trim(newName);
    if(name.empty()) {
        name = orig.element()->getName();
    }
    return MooseVec(
        getShellPtr()->doCopy(orig.id, newp, name, n, toGlobal, copyExtMsgs));
}
References Shell::doCopy(), ObjId::element(), Element::getName(), getShellPtr(), ObjId::id, and pymoose::MooseVec::MooseVec().
createDestFunction()
nb::object pymoose::createDestFunction (const ObjId & oid, const Finfo * finfo)
Definition at line 420 of file helper.cpp.
{
    auto rttiType = finfo->rttiType();
    auto fname = finfo->name();
    // Zero parameters
    if(rttiType == "void") {
        return nb::cpp_function(
            [oid, fname]() { return SetGet0::set(oid, fname); });
    }
    // One parameter
// Shorthand for defining single arg dest function
#define DEST_FUNC_1(TYPE)                                   \
    if(rttiType == #TYPE) {                                 \
        return nb::cpp_function(                            \
            [oid, fname](TYPE val) {                        \
                return SetGet1<TYPE>::set(oid, fname, val); \
            },                                              \
            nb::arg("value"));                              \
    }
    DEST_FUNC_1(double)
    DEST_FUNC_1(unsigned int)
    DEST_FUNC_1(int)
    DEST_FUNC_1(long)
    DEST_FUNC_1(unsigned long)
    DEST_FUNC_1(bool)
    DEST_FUNC_1(string)
    DEST_FUNC_1(Id)
    DEST_FUNC_1(ObjId)
    DEST_FUNC_1(vector<double>)
    DEST_FUNC_1(vector<int>)
    DEST_FUNC_1(vector<unsigned int>)
    DEST_FUNC_1(vector<Id>)
    DEST_FUNC_1(vector<ObjId>)
    DEST_FUNC_1(vector<string>)
#undef DEST_FUNC_1
    vector<string> types;
    moose::tokenize(rttiType, ",", types);
    // Two parameters
    // Short hand for 2-arg functions
#define DEST_FUNC_2(T1, T2, TOKENS)                            \
    if(TOKENS[0] == #T1 && TOKENS[1] == #T2) {                 \
        return nb::cpp_function(                               \
            [oid, fname](const T1 &a, const T2 &b) {           \
                return SetGet2<T1, T2>::set(oid, fname, a, b); \
            },                                                 \
            nb::arg("a"), nb::arg("b"));                       \
    }
    if(types.size() == 2) {
        DEST_FUNC_2(double, double, types)
        DEST_FUNC_2(unsigned int, unsigned int, types)
        DEST_FUNC_2(double, unsigned int, types)
        DEST_FUNC_2(unsigned int, unsigned int, types)
        DEST_FUNC_2(unsigned int, double, types)
        DEST_FUNC_2(double, long, types)
        DEST_FUNC_2(string, string, types)
        DEST_FUNC_2(ObjId, ObjId, types)
        DEST_FUNC_2(Id, double, types)
        DEST_FUNC_2(vector<double>, string, types)
    }
#undef DEST_FUNC_2
    // Three param destFinfo - rarely used (just the 6 specific cases)
    //
    // | CompartmentBase | displace     | double, double, double                                          |
    // | SparseMsg       | setEntry     | unsigned int, unsigned int, unsigned int                        |
    // | SparseMsg       | tripletFill  | vector<unsigne int>, vector<unsigned int>, vector<unsigned int> |
    // | TableBase       | compareXplot | string, string, string                                          |
    // | MarkovRateTable | set2d        | unsigned int, unsigned int, Id                                  |
    // | MarkovRateTable | setconst     | unsigned int, unsigned int, double                              |
#define DEST_FUNC_3(T1, T2, T3, TYPES)                                \
    if(TYPES[0] == #T1 && TYPES[1] == #T2 && TYPES[2] == #T3) {       \
        return nb::cpp_function(                                      \
            [oid, fname](const T1 &a, const T2 &b, const T3 &c) {     \
                return SetGet3<T1, T2, T3>::set(oid, fname, a, b, c); \
            },                                                        \
            nb::arg("a"), nb::arg("b"), nb::arg("c"));                \
    }
    if(types.size() == 3) {
        DEST_FUNC_3(double, double, double, types)
        DEST_FUNC_3(unsigned int, unsigned int, unsigned int, types)
        DEST_FUNC_3(unsigned int, unsigned int, double, types)
        DEST_FUNC_3(unsigned int, unsigned int, Id, types)
        DEST_FUNC_3(string, string, string, types)
        DEST_FUNC_3(vector<unsigned int>, vector<unsigned int>,
                    vector<unsigned int>, types)
    }
#undef DEST_FUNC_3
    // 4-arg (just the 4 specific cases)
    //
    //  | Class           | Function   | Types                                        |
    //  |-----------------|------------|----------------------------------------------|
    //  | CubeMesh        | buildMesh  | Id, double, double, double                   |
    //  | TableBase       | loadCSV    | string, int, int, char                       |
    //  | TableBase       | compareVec | string, string, unsigned int, unsigned int   |
    //  | MarkovRateTable | set1d      | unsigned int, unsigned int, Id, unsigned int |
    //
#define DEST_FUNC_4(T1, T2, T3, T4, TYPES)                                     \
    if(TYPES[0] == #T1 && TYPES[1] == #T2 && TYPES[2] == #T3 &&                \
       TYPES[3] == #T4) {                                                      \
        return nb::cpp_function(                                               \
            [oid, fname](const T1 &a, const T2 &b, const T3 &c, const T4 &d) { \
                return SetGet4<T1, T2, T3, T4>::set(oid, fname, a, b, c, d);   \
            },                                                                 \
            nb::arg("a"), nb::arg("b"), nb::arg("c"), nb::arg("d"));           \
    }
    DEST_FUNC_4(Id, double, double, double, types)
    DEST_FUNC_4(string, int, int, char, types)
    DEST_FUNC_4(string, string, unsigned int, unsigned int, types)
    DEST_FUNC_4(unsigned int, unsigned int, Id, unsigned int, types)
#undef DEST_FUNC_4
    throw nb::type_error(("Unsupported DestFinfo type: " + rttiType).c_str());
}
References Finfo::name(), and Finfo::rttiType().
createElementFromPath()
ObjId pymoose::createElementFromPath (const string & type, const string & p, unsigned int numdata)
Create a new vector of class type at path p, with numdata elements.
Definition at line 584 of file helper.cpp.
{
    // NOTE: This function is bit costly because of regex use. One can replace
    // it with bit more efficient one if required.
    auto path = moose::normalizePath(p);
    if(path.at(0) != '/') {
        string cwe = getShellPtr()->getCwe().path();
        if(cwe.back() != '/')
            cwe += '/';
        path = cwe + path;
    }
    // Split into dirname and basename component.
    auto pp = moose::splitPath(path);
    string name(pp.second);
    if(name.empty()) {
        throw nb::value_error(
            ("path= " + path + ": path must not end with '/' except for root.")
                .c_str());
    }
    if(name.back() == ']')
        name = name.substr(0, name.find_last_of('['));
    // Check if parent exists.
    auto parent = ObjId(pp.first);
    if(parent.bad()) {
        throw std::runtime_error("Parent '" + pp.first +
                                 "' is not found. Not creating...");
        return Id();
    }
    // If path exists and user is asking for the same type then return the
    // underlying object else raise an exception.
    auto oid = ObjId(path);
    if(!oid.bad()) {
        if(oid.element()->cinfo()->name() == type)
            return oid;
        else
            throw runtime_error("An object with path'" + path +
                                "' already "
                                "exists. Use moose.element to access it.");
    }
    Id newId = getShellPtr()->doCreate2(type, ObjId(pp.first), name, numdata);
    return ObjId(newId);
}
References ObjId::bad(), Element::cinfo(), Shell::doCreate2(), ObjId::element(), Shell::getCwe(), getShellPtr(), Id::Id(), Cinfo::name(), moose::normalizePath(), ObjId::ObjId(), ObjId::ObjId(), ObjId::path(), and moose::splitPath().
Referenced by pymoose::MooseVec::MooseVec().
doDelete()
bool pymoose::doDelete (nb::object & obj)
Definition at line 669 of file helper.cpp.
{
    ObjId oid = convertToObjId(arg);
    return getShellPtr()->doDelete(oid);
}
References Shell::doDelete(), and getShellPtr().
fieldDocFormatted()
string pymoose::fieldDocFormatted (const string & name, const Cinfo * cinfo, const Finfo * finfo, const string & prefix = "")
Definition at line 157 of file helper.cpp.
{
    return prefix + fmt::format("{0} (type: {1}, class: {3})\n{2}\n\n", name,
                                finfo->rttiType(),
                                moose::textwrap(finfo->docs(), prefix + "  "),
                                cinfo->name());
}
References Finfo::docs(), Cinfo::name(), and Finfo::rttiType().
getClassAttributeDoc()
std::string pymoose::getClassAttributeDoc (const Cinfo * cinfo, const std::string & fname)
getClassDoc()
string pymoose::getClassDoc (const std::string & className)
Definition at line 198 of file helper.cpp.
{
    stringstream ss;
    auto cinfo = Cinfo::find(className);
    if(!cinfo) {
        ss << "This class is not valid." << endl;
        return ss.str();
    }
    ss << "class " << className << "\n\n"
       << cinfo->getDocsEntry("Description") << "\n\n"
       << "Author: " << moose::textwrap(cinfo->getDocsEntry("Author"), "  ")
       << "\n\n";
    ss << moose::underlined<'='>("Attributes:");
    ss << endl;
    for(string f : {"value", "lookup", "src", "dest", "shared", "field"})
        ss << getClassFieldsDoc(cinfo, f, "");
    return ss.str();
}
References Cinfo::find(), and Cinfo::getDocsEntry().
getClassFieldsDoc()
string pymoose::getClassFieldsDoc (const Cinfo * cinfo, const std::string & ftype, const std::string & prefix)
Get the class fields documentation.
Definition at line 166 of file helper.cpp.
{
    stringstream ss;
    map<string, Finfo *> fmap = getFinfoDict(cinfo, ftype);
    if(fmap.size() == 0)
        return "\n";
    ss << moose::underlined<'-'>(moose::capitalize(ftype) + " Attributes:");
    for(auto v : fmap) {
        ss << fieldDocFormatted(v.first, cinfo, v.second, prefix);
    }
    // There are from base classes.
    const Cinfo *baseClassCinfo = cinfo->baseCinfo();
    while(baseClassCinfo) {
        ss << prefix << "Attributes inherited from " << baseClassCinfo->name()
           << ":\n";
        auto baseFmap = getFinfoDict(baseClassCinfo, ftype);
        for(const auto &vv : baseFmap) {
            if(fmap.find(vv.first) == fmap.end()) {
                fmap[vv.first] = vv.second;
                ss << fieldDocFormatted(vv.first, baseClassCinfo, vv.second,
                                        prefix);
            }
        }
        baseClassCinfo = baseClassCinfo->baseCinfo();
    }
    return ss.str();
}
References Cinfo::baseCinfo(), moose::capitalize(), and Cinfo::name().
getCwe()
nb::object pymoose::getCwe ()
Get current working element.
Definition at line 634 of file helper.cpp.
{
    return nb::cast(getShellPtr()->getCwe());
}
getDoc()
string pymoose::getDoc (const std::string & query)
Definition at line 220 of file helper.cpp.
{
    auto getClassAttributeDoc = [](const Cinfo *cinfo,
                                   const string &fname) -> string {
        const Finfo *finfo = cinfo->findFinfo(fname);
        if(!finfo)
            return "Error: '" + fname + "' not found.";
        return fmt::format("{0}: {1} - {2}\n{3}", fname, finfo->rttiType(),
                           cinfo->getFinfoType(finfo), finfo->docs());
    };
    vector<string> tokens;
    moose::tokenize(query, ".", tokens);
    auto cinfo = Cinfo::find(tokens[0]);
    string msg = "Class '" + tokens[0] + "' is not a valid MOOSE class.";
    if(!cinfo)
        throw nb::key_error(msg.c_str());
    if(tokens.size() == 1)
        return getClassDoc(tokens[0]);
    if(tokens.size() == 2) {
        cout << "Query: " << tokens[1] << endl;
        return getClassAttributeDoc(cinfo, tokens[1]);
    }
    throw runtime_error(__func__ + string(":: Not supported '" + query + "'"));
}
References Finfo::docs(), Cinfo::find(), Cinfo::findFinfo(), Cinfo::getFinfoType(), and Finfo::rttiType().
getFieldGeneric()
nb::object pymoose::getFieldGeneric (const ObjId & oid, const std::string & fieldName)
Definition at line 543 of file helper.cpp.
{
    // Special fields that do not depend on a valid element being there: empty
    // FieldElements
    if(fieldName == "numData") {
        return nb::cast(Field<unsigned int>::get(oid, "numData"));
    }
    else if(fieldName == "numFields") {
        return nb::cast(Field<unsigned int>::get(oid, "numField"));
    }
    auto cinfo = oid.element()->cinfo();
    auto finfo = cinfo->findFinfo(fieldName);
    if(!finfo) {
        throw nb::attribute_error(
            (fieldName + " is not found on '" + oid.path() + "'.").c_str());
    }
    string finfoType = cinfo->getFinfoType(finfo);
    if(finfoType == "ValueFinfo") {
        return getFieldValue(oid, finfo);
    }
    else if(finfoType == "FieldElementFinfo") {
        return nb::cast(ElementField(oid, finfo));
    }
    else if(finfoType == "LookupValueFinfo") {
        return nb::cast(LookupField(oid, finfo));
    }
    else if(finfoType == "DestFinfo") {
        return createDestFunction(oid, finfo);
    }
    throw runtime_error("getFieldGeneric::NotImplemented : " + fieldName +
                        " with rttType " + finfo->rttiType() + " and type: '" +
                        finfoType + "'");
    return nb::none();
}
References Element::cinfo(), ObjId::element(), Cinfo::findFinfo(), Cinfo::getFinfoType(), and Finfo::rttiType().
getFieldNames()
vector< string > pymoose::getFieldNames (const string & className, const string & fieldType)
Definition at line 127 of file helper.cpp.
{
    auto cinfo = Cinfo::find(className);
    if(!cinfo) {
        throw nb::key_error((className + ": no such class found").c_str());
    }
    auto finfoDict = getFinfoDict(cinfo, fieldType);
    vector<string> ret;
    ret.reserve(finfoDict.size());
    for(const auto &it : finfoDict) {
        ret.push_back(it.first);
    }
    return ret;
}
References Cinfo::find().
getFieldTypeDict()
map< string, string > pymoose::getFieldTypeDict (const string & className, const string & fieldType)
Definition at line 142 of file helper.cpp.
{
    auto cinfo = Cinfo::find(className);
    if(!cinfo) {
        throw nb::key_error((className + ": no such class found").c_str());
    }
    auto finfoDict = getFinfoDict(cinfo, fieldType);
    map<string, string> ret;
    for(const auto &it : finfoDict) {
        ret[it.first] = it.second->rttiType();
    }
    return ret;
}
References Cinfo::find().
getFieldValue()
nb::object pymoose::getFieldValue (const ObjId & oid, const Finfo * f)
Common function to get value fiields.
Definition at line 342 of file helper.cpp.
{
    auto rttType = f->rttiType();
    auto fname = f->name();
    nb::object r = nb::none();
    if(rttType == "double" || rttType == "float") {
        r = nb::float_(Field<double>::get(oid, fname));
    }
    else if(rttType == "vector<double>") {
        vector<double> val = Field<vector<double>>::get(oid, fname);
        // Must copy data - val goes out of scope!
        size_t size = val.size();
        // Allocate numpy array and copy data into it
        auto *data = new double[size];
        std::copy(val.begin(), val.end(), data);
        nb::capsule owner(
            data, [](void *p) noexcept { delete[] static_cast<double *>(p); });
        r = nb::cast(nb::ndarray<nb::numpy, double>(data, {size}, owner));
    }
    else if(rttType == "vector<unsigned int>") {
        vector<unsigned int> val = Field<vector<unsigned int>>::get(oid, fname);
        size_t size = val.size();
        auto *data = new unsigned int[size];
        std::copy(val.begin(), val.end(), data);
        nb::capsule owner(data, [](void *p) noexcept {
            delete[] static_cast<unsigned int *>(p);
        });
        r = nb::cast(nb::ndarray<nb::numpy, unsigned int>(data, {size}, owner));
    }
    else if(rttType == "vector<int>") {
        vector<int> val = Field<vector<int>>::get(oid, fname);
        size_t size = val.size();
        auto *data = new int[size];
        std::copy(val.begin(), val.end(), data);
        nb::capsule owner(
            data, [](void *p) noexcept { delete[] static_cast<int *>(p); });
        r = nb::cast(nb::ndarray<nb::numpy, int>(data, {size}, owner));
    }
    else if(rttType == "string")
        r = nb::cast(Field<string>::get(oid, fname));
    else if(rttType == "char")
        r = nb::int_(Field<char>::get(oid, fname));
    else if(rttType == "int")
        r = nb::int_(Field<int>::get(oid, fname));
    else if(rttType == "unsigned int")
        r = nb::int_(Field<unsigned int>::get(oid, fname));
    else if(rttType == "unsigned long")
        r = nb::int_(Field<unsigned long>::get(oid, fname));
    else if(rttType == "bool")
        r = nb::bool_(Field<bool>::get(oid, fname));
    else if(rttType == "Id")
        r = nb::cast(Field<Id>::get(oid, fname));
    else if(rttType == "ObjId")
        r = nb::cast(Field<ObjId>::get(oid, fname));
    else if(rttType == "Variable")
        r = nb::cast(Field<Variable>::get(oid, fname));
    else if(rttType == "vector<Id>")
        r = nb::cast(Field<vector<Id>>::get(oid, fname));
    else if(rttType == "vector<ObjId>")
        r = nb::cast(Field<vector<ObjId>>::get(oid, fname));
    else if(rttType == "vector<string>")
        r = nb::cast(Field<vector<string>>::get(oid, fname));
    else {
        cerr << "Warning: getValueFinfo:: Unsupported type '" + rttType + "'"
             << endl;
        r = nb::none();
    }
    return r;
}
References Finfo::name(), and Finfo::rttiType().
getFinfoDict()
map< string, Finfo * > pymoose::getFinfoDict (const Cinfo * cinfo, const std::string & fieldType)
Get a map of field names to Finfo*.
Definition at line 79 of file helper.cpp.
{
    // All field types - available via Cinfo.finfoMap()
    if(fieldType == "*") {
        return cinfo->finfoMap();
    }
    map<string, Finfo *> ret;
    // Other cases - for each field type XYZ, Cinfo has
    // getNumXYZFinfo() to get the number of fields of that type,
    // and getXYZFinfo(n) to get the n-th field of that type.
    Finfo *(Cinfo::*finfoGetter)(unsigned int) const = nullptr;
    unsigned int numFinfo{0};
    if(fieldType == "valueFinfo" || fieldType == "value") {
        numFinfo = cinfo->getNumValueFinfo();
        finfoGetter = &Cinfo::getValueFinfo;
    }
    else if(fieldType == "srcFinfo" || fieldType == "src") {
        numFinfo = cinfo->getNumSrcFinfo();
        finfoGetter = &Cinfo::getSrcFinfo;
    }
    else if(fieldType == "destFinfo" || fieldType == "dest") {
        numFinfo = cinfo->getNumDestFinfo();
        finfoGetter = &Cinfo::getDestFinfo;
    }
    else if(fieldType == "lookupFinfo" || fieldType == "lookup") {
        numFinfo = cinfo->getNumLookupFinfo();
        finfoGetter = &Cinfo::getLookupFinfo;
    }
    else if(fieldType == "sharedFinfo" || fieldType == "shared") {
        numFinfo = cinfo->getNumSharedFinfo();
        finfoGetter = &Cinfo::getSharedFinfo;
    }
    else if(fieldType == "element" || fieldType == "elementFinfo" ||
            fieldType == "field" || fieldType == "fieldElement" ||
            fieldType == "fieldElementFinfo") {
        numFinfo = cinfo->getNumFieldElementFinfo();
        finfoGetter = &Cinfo::getFieldElementFinfo;
    }
    if(!finfoGetter) {
        throw nb::value_error("Invalid field type");
    }
    for(unsigned int ii = 0; ii < numFinfo; ++ii) {
        Finfo *finfo = (cinfo->*finfoGetter)(ii);
        ret[finfo->name()] = finfo;
    }
    return ret;
}
References Cinfo::getDestFinfo(), Cinfo::getFieldElementFinfo(), Cinfo::getLookupFinfo(), Cinfo::getNumDestFinfo(), Cinfo::getNumFieldElementFinfo(), Cinfo::getNumLookupFinfo(), Cinfo::getNumSharedFinfo(), Cinfo::getNumSrcFinfo(), Cinfo::getNumValueFinfo(), Cinfo::getSharedFinfo(), Cinfo::getSrcFinfo(), Cinfo::getValueFinfo(), and Finfo::name().
getNeighbors()
vector< ObjId > pymoose::getNeighbors (const nb::object & obj, const string & fieldName, const string & msgType, MsgDirection direction = MsgDirection::Both)
Get neighbors of obj connected on fieldName, of type msgType, in direction direction.
Definition at line 803 of file helper.cpp.
{
    vector<ObjId> result;
    ObjId obj = convertToObjId(arg);
    // Normalize msgType once
    string lowerMsgType = msgType;
    std::transform(lowerMsgType.begin(), lowerMsgType.end(),
                   lowerMsgType.begin(), ::tolower);
    // Collect messages based on direction
    vector<ObjId> msgList;
    if(direction != MsgDirection::Out) {
        auto in = Field<vector<ObjId>>::get(obj, "msgIn");
        msgList.insert(msgList.end(), in.begin(), in.end());
    }
    if(direction != MsgDirection::In) {
        auto out = Field<vector<ObjId>>::get(obj, "msgOut");
        msgList.insert(msgList.end(), out.begin(), out.end());
    }
    for(const auto &mobj : msgList) {
        const Msg *msg = Msg::getMsg(mobj);
        if(!msg)
            continue;
        // Filter by message type
        if(!lowerMsgType.empty()) {
            bool matches = (lowerMsgType == "single" &&
                            dynamic_cast<const SingleMsg *>(msg)) ||
                           (lowerMsgType == "onetoone" &&
                            dynamic_cast<const OneToOneMsg *>(msg)) ||
                           (lowerMsgType == "onetoall" &&
                            dynamic_cast<const OneToAllMsg *>(msg)) ||
                           (lowerMsgType == "diagonal" &&
                            dynamic_cast<const DiagonalMsg *>(msg)) ||
                           (lowerMsgType == "sparse" &&
                            dynamic_cast<const SparseMsg *>(msg));
            if(!matches)
                continue;
        }
        // Determine which end we're on
        Id e1 = msg->getE1();
        Id e2 = msg->getE2();
        bool isE1 = (obj.id == e1);
        // Collect relevant fields based on direction
        set<string> fields;
        if(direction != MsgDirection::Out) {
            auto dest =
                isE1 ? msg->getDestFieldsOnE1() : msg->getDestFieldsOnE2();
            fields.insert(dest.begin(), dest.end());
        }
        if(direction != MsgDirection::In) {
            auto src = isE1 ? msg->getSrcFieldsOnE1() : msg->getSrcFieldsOnE2();
            fields.insert(src.begin(), src.end());
        }
        // Check field match and add neighbor
        if(fieldName == "*" || fields.count(fieldName)) {
            result.push_back(isE1 ? e2 : e1);
        }
    }
    return result;
}
References In, and Out.
getShellPtr()
Shell * pymoose::getShellPtr (void) inline
Shorthand to access shell pointer.
Definition at line 32 of file pymoose.h.
{
    return reinterpret_cast<Shell*>(Id().eref().data());
}
References Eref::data(), Id::eref(), and Id::Id().
Referenced by connect(), copy(), createElementFromPath(), doDelete(), handleKeyboardInterrupts(), loadModelInternal(), move(), setClock(), start(), and useClock().
getVersionInfo()
map< string, string > pymoose::getVersionInfo ()
Definition at line 937 of file helper.cpp.
{
    std::time_t t = std::time(nullptr);
    char mbstr[100];
    std::strftime(mbstr, sizeof(mbstr), "%A %c", ::localtime(&t));
    vector<string> vers;
    moose::tokenize(string(MOOSE_VERSION), ".", vers);
    if(vers.size() == 3)
        vers.push_back("1");
    return {{"major", vers[0]},
            {"minor", vers[1]},
            {"micro", vers[2]},
            {"releaselevel", vers[3]},
            {"build_datetime", string(mbstr)},
            {"compiler_string", string(COMPILER_STRING)}};
}
handleKeyboardInterrupts()
void pymoose::handleKeyboardInterrupts (int signum)
Definition at line 895 of file helper.cpp.
{
    getShellPtr()->cleanSimulation();
    exit(signum);
}
References Shell::cleanSimulation(), and getShellPtr().
initShell()
Id pymoose::initShell ()
Initialize shell object.
Sets up the Elements that represent each class of Msg.
Sets up the Elements that represent each class of Msg.
Definition at line 39 of file helper.cpp.
{
    Cinfo::rebuildOpIndex();
    Id shellId;
    Element *shelle =
        new GlobalDataElement(shellId, Shell::initCinfo(), "/", 1);
    Id clockId = Id::nextId();
    assert(clockId.value() == 1);
    Id classMasterId = Id::nextId();
    Id postMasterId = Id::nextId();
    Shell *s = reinterpret_cast<Shell *>(shellId.eref().data());
    s->setHardware(1, 1, 0);
    s->setShellElement(shelle);
    auto numMsg = Msg::initMsgManagers();
    new GlobalDataElement(clockId, Clock::initCinfo(), "clock", 1);
    new GlobalDataElement(classMasterId, Neutral::initCinfo(), "classes", 1);
    new GlobalDataElement(postMasterId, PostMaster::initCinfo(), "postmaster",
                          1);
    assert(shellId == Id());
    assert(clockId == Id(1));
    assert(classMasterId == Id(2));
    assert(postMasterId == Id(3));
    Shell::adopt(shellId, clockId, numMsg++);
    Shell::adopt(shellId, classMasterId, numMsg++);
    Shell::adopt(shellId, postMasterId, numMsg++);
    assert(numMsg == 10);  // Must be the same on all nodes.
    Cinfo::makeCinfoElements(classMasterId);
    return shellId;
}
References Shell::adopt(), Eref::data(), Id::eref(), Id::Id(), Id::Id(), Msg::initMsgManagers(), Cinfo::makeCinfoElements(), Id::nextId(), Id::operator==(), Cinfo::rebuildOpIndex(), Shell::setHardware(), Shell::setShellElement(), and Id::value().
Referenced by NB_MODULE().
listElements()
void pymoose::listElements (const nb::object & arg)
Show elements (le)
Definition at line 696 of file helper.cpp.
{
    vector<Id> children;
    vector<string> chPaths;
    ObjId obj = convertToObjId(arg);
    if(obj.bad())
        throw std::runtime_error("no such element.");
    Neutral::children(obj.eref(), children);
    stringstream ss;
    ss << "Elements under " << obj.path() << endl;
    for(auto ch : children) {
        ss << "    " + ch.path() << endl;
        chPaths.push_back(ch.path());
    }
    nb::print(ss.str().c_str());
}
References ObjId::bad(), ObjId::eref(), and ObjId::path().
listMsg()
vector< ObjId > pymoose::listMsg (const nb::object & arg, MsgDirection direction = MsgDirection::Both)
Get a list of Msg objects.
Definition at line 714 of file helper.cpp.
{
    ObjId obj = convertToObjId(arg);
    vector<ObjId> res;
    if(direction != MsgDirection::Out) {  // Only for 0 skip INCOMING, all other
                                          // cases keep it
        auto inmsgs = Field<vector<ObjId>>::get(obj, "msgIn");
        for(const auto &inobj : inmsgs) {
            const Msg *msg = Msg::getMsg(inobj);
            if(!msg) {
                cerr << "No incoming Msg found on " << obj.path() << endl;
                continue;
            }
            res.push_back(msg->mid());
        }
    }
    if(direction != MsgDirection::In) {  // Only for 1 skip OUTGOING, all other
                                         // cases keep it
        auto outmsgs = Field<vector<ObjId>>::get(obj, "msgOut");
        for(const auto &outobj : outmsgs) {
            const Msg *msg = Msg::getMsg(outobj);
            if(!msg) {
                cerr << "No outgoing Msg found on " << obj.path() << endl;
                continue;
            }
            res.push_back(msg->mid());
        }
    }
    return res;
}
References In, and Out.
loadModelInternal()
ObjId pymoose::loadModelInternal (const string & fname, const string & modelpath, const string & solverclass = "")
Model loaders built into Shell, others can be implemented in Python.
Definition at line 919 of file helper.cpp.
{
    Id model;
    if(solverclass.empty()) {
        model = getShellPtr()->doLoadModel(fname, modelpath);
    }
    else {
        model = getShellPtr()->doLoadModel(fname, modelpath, solverclass);
    }
    if(model == Id()) {
        throw std::runtime_error("could not load model");
        return Id();
    }
    return ObjId(model);
}
References Shell::doLoadModel(), getShellPtr(), Id::Id(), ObjId::ObjId(), and Id::operator==().
move()
void pymoose::move (const nb::object & elem, const nb::object & newParent)
Move object, return None.
Definition at line 689 of file helper.cpp.
{
    Id obj{convertToObjId(orig).id};
    ObjId tgt{convertToObjId(parent)};
    getShellPtr()->doMove(obj, tgt);
}
References Shell::doMove(), and getShellPtr().
setClock()
void pymoose::setClock (const unsigned int clockId, double dt)
Definition at line 885 of file helper.cpp.
{
    getShellPtr()->doSetClock(clockId, dt);
}
References Shell::doSetClock(), and getShellPtr().
setCwe()
void pymoose::setCwe (const nb::object & arg)
Set current working element (ce)
Definition at line 664 of file helper.cpp.
{
    getShellPtr()->setCwe(convertToObjId(arg));
}
setFieldGeneric()
bool pymoose::setFieldGeneric (const ObjId & oid, const std::string & fieldName, const nb::object & val)
Definition at line 250 of file helper.cpp.
{
    // if(fieldName == "dt") {
    //     throw nb::attribute_error(
    //         "Read-only property. Use `moose.setcClock(...)`");
    // }
    // else if(fieldName == "tick") {
    //     throw nb::warning("Setting . Use `moose.useClock(...)`");
    // }
    auto cinfo = oid.element()->cinfo();
    auto finfo = cinfo->findFinfo(fieldName);
    if(!finfo) {
        throw nb::attribute_error((__func__ + string("::") + fieldName +
                                   " is not found on path '" + oid.path() +
                                   "'.")
                                      .c_str());
        return false;
    }
    auto fieldType = finfo->rttiType();
    // Remove any space in fieldType
    fieldType.erase(
        std::remove_if(fieldType.begin(), fieldType.end(), ::isspace),
        fieldType.end());
    if(fieldType == "double") {
        return Field<double>::set(oid, fieldName, nb::cast<double>(val));
    }
    if(fieldType == "vector<double>")
        return Field<vector<double>>::set(oid, fieldName,
                                          nb::cast<vector<double>>(val));
    if(fieldType == "float")
        return Field<float>::set(oid, fieldName, nb::cast<float>(val));
    if(fieldType == "unsignedint")
        return Field<unsigned int>::set(oid, fieldName,
                                        nb::cast<unsigned int>(val));
    if(fieldType == "unsignedlong")
        return Field<unsigned long>::set(oid, fieldName,
                                         nb::cast<unsigned long>(val));
    if(fieldType == "int")
        return Field<int>::set(oid, fieldName, nb::cast<int>(val));
    if(fieldType == "bool")
        return Field<bool>::set(oid, fieldName, nb::cast<bool>(val));
    if(fieldType == "string")
        return Field<string>::set(oid, fieldName, nb::cast<string>(val));
    if(fieldType == "vector<string>")
        return Field<vector<string>>::set(oid, fieldName,
                                          nb::cast<vector<string>>(val));
    if(fieldType == "char")
        return Field<char>::set(oid, fieldName, nb::cast<char>(val));
    if(fieldType == "vector<ObjId>")
        return Field<vector<ObjId>>::set(oid, fieldName,
                                         nb::cast<vector<ObjId>>(val));
    if(fieldType == "ObjId")
        return Field<ObjId>::set(oid, fieldName, nb::cast<ObjId>(val));
    if(fieldType == "Id") {
        // NB: Handle MooseVec as well. Note that we send ObjId to the set
        // function. The C++ implicit conversion takes care of the rest.
        // Id tgt;
        if(nb::isinstance<MooseVec>(val)) {
            return Field<Id>::set(oid.id, fieldName,
                                  nb::cast<MooseVec>(val).id());
        }
        else if(nb::isinstance<ObjId>(val)) {
            return Field<Id>::set(oid.id, fieldName, nb::cast<ObjId>(val).id);
        }
        else if(nb::isinstance<Id>(val)) {
            return Field<Id>::set(oid.id, fieldName, nb::cast<Id>(val));
        }
    }
    if(fieldType == "vector<double>") {
        // NB: Note that we cast to ObjId here and not to Id.
        return Field<vector<double>>::set(oid.id, fieldName,
                                          nb::cast<vector<double>>(val));
    }
    if(fieldType == "vector<vector<double>>") {
        // NB: Note that we cast to ObjId here and not to Id.
        return Field<vector<vector<double>>>::set(
            oid.id, fieldName, nb::cast<vector<vector<double>>>(val));
    }
    if(fieldType == "Variable")
        if(fieldType == "Variable")
            return Field<Variable>::set(oid, fieldName,
                                        nb::cast<Variable>(val));
    throw runtime_error("NotImplemented::setField: '" + fieldName +
                        "' with value type '" + fieldType + "'.");
    return false;
}
References Element::cinfo(), ObjId::element(), Cinfo::findFinfo(), and Finfo::rttiType().
showMsg()
void pymoose::showMsg (const nb::object & arg, MsgDirection direction = MsgDirection::Both)
Show messages (showmsg)
Definition at line 745 of file helper.cpp.
{
    stringstream ss;
    ObjId obj = convertToObjId(arg);
    auto formatMessages = [&](const vector<ObjId> &msgs, bool isIncoming) {
        const char *arrow = isIncoming ? "<--" : "-->";
        for(const auto &msgObj : msgs) {
            const Msg *msg = Msg::getMsg(msgObj);
            if(!msg) {
                ss << "  (invalid message)\n";
                continue;
            }
            Id e1 = msg->getE1();
            Id e2 = msg->getE2();
            bool objIsE1 = (obj.id == e1);
            ObjId self = obj;
            ObjId other = objIsE1 ? ObjId(e2) : ObjId(e1);
            vector<string> selfFields, otherFields;
            if(isIncoming) {
                selfFields = objIsE1 ? msg->getDestFieldsOnE1()
                                     : msg->getDestFieldsOnE2();
                otherFields =
                    objIsE1 ? msg->getSrcFieldsOnE2() : msg->getSrcFieldsOnE1();
            }
            else {
                selfFields =
                    objIsE1 ? msg->getSrcFieldsOnE1() : msg->getSrcFieldsOnE2();
                otherFields = objIsE1 ? msg->getDestFieldsOnE2()
                                      : msg->getDestFieldsOnE1();
            }
            ss << fmt::format("  {0} [{1}] {2} {3} [{4}]\n", self.path(),
                              moose::vectorToCSV<string>(selfFields), arrow,
                              other.path(),
                              moose::vectorToCSV<string>(otherFields));
        }
    };
    if(direction != MsgDirection::Out) {
        ss << "INCOMING:\n";
        auto inmsgs = Field<vector<ObjId>>::get(obj, "msgIn");
        formatMessages(inmsgs, true);
        ss << "\n";
    }
    if(direction != MsgDirection::In) {
        ss << "OUTGOING:\n";
        auto outmsgs = Field<vector<ObjId>>::get(obj, "msgOut");
        formatMessages(outmsgs, false);
    }
    nb::print(ss.str().c_str());
}
References In, and Out.
start()
void pymoose::start (double runtime, bool notify = false)
Definition at line 901 of file helper.cpp.
{
    // TODO: handle keyboard interrupt on _WIN32
#if !defined(_WIN32)
    // Credit:
    // http://stackoverflow.com/questions/1641182/how-can-i-catch-a-ctrl-c-event-c
    struct sigaction sigHandler;
    sigHandler.sa_handler = [](int signum) {
        getShellPtr()->cleanSimulation();
        exit(signum);
    };
    sigemptyset(&sigHandler.sa_mask);
    sigHandler.sa_flags = 0;
    sigaction(SIGINT, &sigHandler, NULL);
#endif
    getShellPtr()->doStart(runtime, notify);
}
References Shell::cleanSimulation(), Shell::doStart(), and getShellPtr().
useClock()
void pymoose::useClock (size_t tick, const string & path, const string & fn)
Definition at line 890 of file helper.cpp.
{
    getShellPtr()->doUseClock(path, fn, tick);
}
References Shell::doUseClock(), and getShellPtr().
Variable Documentation
intKeyGetters
const std::map<std::string, LookupGetter<int> > pymoose::intKeyGetters static
Definition at line 88 of file Finfo.cpp.
{
    {"double",
     [](auto& oid, auto& fname, auto& key) {
         return nb::cast(::LookupField<int, double>::get(oid, fname, key));
     }},
    {"int",
     [](auto& oid, auto& fname, auto& key) {
         return nb::cast(::LookupField<int, int>::get(oid, fname, key));
     }},
    {"unsigned int",
     [](auto& oid, auto& fname, auto& key) {
         return nb::cast(
             ::LookupField<int, unsigned int>::get(oid, fname, key));
     }},
    {"long",
     [](auto& oid, auto& fname, auto& key) {
         return nb::cast(::LookupField<int, long>::get(oid, fname, key));
     }},
    {"string",
     [](auto& oid, auto& fname, auto& key) {
         return nb::cast(::LookupField<int, string>::get(oid, fname, key));
     }},
    {"vector<double>",
     [](auto& oid, auto& fname, auto& key) {
         return nb::cast(
             ::LookupField<int, vector<double>>::get(oid, fname, key));
     }},
    {"vector<int>",
     [](auto& oid, auto& fname, auto& key) {
         return nb::cast(::LookupField<int, vector<int>>::get(oid, fname, key));
     }},
    {"vector<unsigned int>",
     [](auto& oid, auto& fname, auto& key) {
         return nb::cast(
             ::LookupField<int, vector<unsigned int>>::get(oid, fname, key));
     }},
    {"vector<string>",
     [](auto& oid, auto& fname, auto& key) {
         return nb::cast(
             ::LookupField<int, vector<string>>::get(oid, fname, key));
     }},
};
longKeyGetters
const std::map<std::string, LookupGetter<long> > pymoose::longKeyGetters static
Definition at line 131 of file Finfo.cpp.
{
    {"double",
     [](auto& oid, auto& fname, auto& key) {
         return nb::cast(::LookupField<long, double>::get(oid, fname, key));
     }},
    {"int",
     [](auto& oid, auto& fname, auto& key) {
         return nb::cast(::LookupField<long, int>::get(oid, fname, key));
     }},
    {"unsigned int",
     [](auto& oid, auto& fname, auto& key) {
         return nb::cast(
             ::LookupField<long, unsigned int>::get(oid, fname, key));
     }},
    {"long",
     [](auto& oid, auto& fname, auto& key) {
         return nb::cast(::LookupField<long, long>::get(oid, fname, key));
     }},
    {"string",
     [](auto& oid, auto& fname, auto& key) {
         return nb::cast(::LookupField<long, string>::get(oid, fname, key));
     }},
    {"vector<double>",
     [](auto& oid, auto& fname, auto& key) {
         return nb::cast(
             ::LookupField<long, vector<double>>::get(oid, fname, key));
     }},
    {"vector<int>",
     [](auto& oid, auto& fname, auto& key) {
         return nb::cast(
             ::LookupField<long, vector<int>>::get(oid, fname, key));
     }},
    {"vector<unsigned int>",
     [](auto& oid, auto& fname, auto& key) {
         return nb::cast(
             ::LookupField<long, vector<unsigned int>>::get(oid, fname, key));
     }},
    {"vector<string>",
     [](auto& oid, auto& fname, auto& key) {
         return nb::cast(
             ::LookupField<long, vector<string>>::get(oid, fname, key));
     }},
};
stringKeyGetters
const std::map<std::string, LookupGetter<string> > pymoose::stringKeyGetters static
Definition at line 29 of file Finfo.cpp.
{
    {"bool",
     [](auto& oid, auto& fname, auto& key) {
         return nb::cast(::LookupField<string, bool>::get(oid, fname, key));
     }},
    {"double",
     [](auto& oid, auto& fname, auto& key) {
         return nb::cast(::LookupField<string, double>::get(oid, fname, key));
     }},
    {"int",
     [](auto& oid, auto& fname, auto& key) {
         return nb::cast(::LookupField<string, int>::get(oid, fname, key));
     }},
    {"unsigned int",
     [](auto& oid, auto& fname, auto& key) {
         return nb::cast(
             ::LookupField<string, unsigned int>::get(oid, fname, key));
     }},
    {"long",
     [](auto& oid, auto& fname, auto& key) {
         return nb::cast(::LookupField<string, long>::get(oid, fname, key));
     }},
    {"string",
     [](auto& oid, auto& fname, auto& key) {
         return nb::cast(::LookupField<string, string>::get(oid, fname, key));
     }},
    {"vector<double>",
     [](auto& oid, auto& fname, auto& key) {
         return nb::cast(
             ::LookupField<string, vector<double>>::get(oid, fname, key));
     }},
    {"vector<int>",
     [](auto& oid, auto& fname, auto& key) {
         return nb::cast(
             ::LookupField<string, vector<int>>::get(oid, fname, key));
     }},
    {"vector<unsigned int>",
     [](auto& oid, auto& fname, auto& key) {
         return nb::cast(
             ::LookupField<string, vector<unsigned int>>::get(oid, fname, key));
     }},
    {"vector<string>",
     [](auto& oid, auto& fname, auto& key) {
         return nb::cast(
             ::LookupField<string, vector<string>>::get(oid, fname, key));
     }},
    {"vector<Id>",
     [](auto& oid, auto& fname, auto& key) {
         return nb::cast(
             ::LookupField<string, vector<Id>>::get(oid, fname, key));
     }},
    {"vector<ObjId>",
     [](auto& oid, auto& fname, auto& key) {
         return nb::cast(
             ::LookupField<string, vector<ObjId>>::get(oid, fname, key));
     }},
};
uintKeyGetters
const std::map<std::string, LookupGetter<unsigned int> > pymoose::uintKeyGetters static
Definition at line 175 of file Finfo.cpp.
    {
        {"double",
         [](auto& oid, auto& fname, auto& key) {
             return nb::cast(
                 ::LookupField<unsigned int, double>::get(oid, fname, key));
         }},
        {"int",
         [](auto& oid, auto& fname, auto& key) {
             return nb::cast(
                 ::LookupField<unsigned int, int>::get(oid, fname, key));
         }},
        {"unsigned int",
         [](auto& oid, auto& fname, auto& key) {
             return nb::cast(::LookupField<unsigned int, unsigned int>::get(
                 oid, fname, key));
         }},
        {"long",
         [](auto& oid, auto& fname, auto& key) {
             return nb::cast(
                 ::LookupField<unsigned int, long>::get(oid, fname, key));
         }},
        {"string",
         [](auto& oid, auto& fname, auto& key) {
             return nb::cast(
                 ::LookupField<unsigned int, string>::get(oid, fname, key));
         }},
        {"vector<double>",
         [](auto& oid, auto& fname, auto& key) {
             return nb::cast(::LookupField<unsigned int, vector<double>>::get(
                 oid, fname, key));
         }},
        {"vector<int>",
         [](auto& oid, auto& fname, auto& key) {
             return nb::cast(::LookupField<unsigned int, vector<int>>::get(
                 oid, fname, key));
         }},
        {"vector<unsigned int>",
         [](auto& oid, auto& fname, auto& key) {
             return nb::cast(
                 ::LookupField<unsigned int, vector<unsigned int>>::get(
                     oid, fname, key));
         }},
        {"vector<string>",
         [](auto& oid, auto& fname, auto& key) {
             return nb::cast(::LookupField<unsigned int, vector<string>>::get(
                 oid, fname, key));
         }},
};