MOOSE - Multiscale Object Oriented Simulation Environment: cnpy2 Namespace Reference
cnpy2 Namespace Reference
Functions
void appendNumpy (const string &outfile, const vector< double > &vec, const vector< string > &colnames)
char BigEndianTest ()
void changeHeaderShape (std::fstream &fs, const size_t data_len, const size_t numcols)
Change shape in numpy header.
void changeHeaderShape (std::ofstream &fs, const size_t data_len, const size_t numcols)
Change shape in numpy header.
void findHeader (std::fstream &fp, string &header)
Parser header from a numpy file. Store it in vector.
size_t initNumpyFile (const string &outfile, const vector< string > &colnames)
bool isValidNumpyFile (std::ifstream &fp)
Check if a numpy file is sane or not.
bool isValidNumpyFile (string npy_file)
Check if a numpy file is sane or not.
void readNumpy (const string &infile, vector< double > &data)
string shapeToString (const vector< size_t > &shape)
void split (vector< string > &strs, string &input, const string &pat)
size_t writeHeader (std::fstream &fp, const vector< string > &colnames, const vector< size_t > &shape)
void writeNumpy (const string &outfile, const vector< double > &vec, const vector< string > &colnames)
Variables
static vector< char > __pre__
size_t headerSize = 0
Function Documentation
appendNumpy()
void cnpy2::appendNumpy (const string & outfile, const vector< double > & vec, const vector< string > & colnames)
Definition at line 264 of file cnpy.cpp.
{
    std::fstream fs;
    fs.open(outfile, std::fstream::in | std::fstream::out | std::fstream::binary);
    if( ! fs.is_open() )
    {
        moose::showWarn( "Could not open " + outfile + " to write " );
        return;
    }
    // And change the shape in header.
    changeHeaderShape(fs, vec.size(), colnames.size());
    // Go to the end.
    fs.seekp(0, std::ios_base::end);
    fs.write(reinterpret_cast<const char*>(&vec[0]), sizeof(double)*vec.size());
    fs.close();
}
References changeHeaderShape(), and moose::showWarn().
Referenced by main(), and StreamerBase::writeToNPYFile().
BigEndianTest()
char cnpy2::BigEndianTest ()
Definition at line 32 of file cnpy.cpp.
{
    unsigned char x[] = {1,0};
    short y = *(short*) x;
    return y == 1 ? '<' : '>';
}
Referenced by writeHeader().
changeHeaderShape() [1/2]
void cnpy2::changeHeaderShape (std::fstream & fs, const size_t data_len, const size_t numcols)
Change shape in numpy header.
Parameters
param data_len
Parameters
Definition at line 128 of file cnpy.cpp.
{
    string header{""};
    // Find header. Search for newline.
    findHeader(fs, header);
    const size_t headerSize = header.size();
    size_t shapePos = header.find( "'shape':" );
    size_t lbrac = header.find( '(', shapePos );
    size_t rbrac = header.find( ')', lbrac );
    assert( lbrac > shapePos );
    assert( rbrac > lbrac );
    string prefixHeader = header.substr( 0, lbrac + 1 );
    string postfixHeader = header.substr( rbrac );
    string shapeStr = header.substr( lbrac+1, rbrac-lbrac-1);
    vector<string> tokens;
    split( tokens, shapeStr, "," );
    string newShape = "";
    for (size_t i = 0; i < tokens.size(); i++)
        newShape += std::to_string( atoi( tokens[i].c_str() ) + data_len/numcols ) + ",";
    string newHeader = prefixHeader + newShape + postfixHeader;
    if( newHeader.size() < header.size() )
    {
        cout << "Warn: Modified header can not be smaller than old header" << endl;
    }
    // Resize to the old header size. Newline is not included in the header.
    newHeader.resize(header.size());
    newHeader += '\n';                          // Add newline before writing.
    fs.seekp(0);
    fs.write(newHeader.c_str(), newHeader.size());
}
References findHeader(), and split().
Referenced by appendNumpy().
changeHeaderShape() [2/2]
void cnpy2::changeHeaderShape (std::ofstream & fs, const size_t data_len, const size_t numcols)
Change shape in numpy header.
Parameters
param data_len
Parameters
findHeader()
void cnpy2::findHeader (std::fstream & fs, string & header)
Parser header from a numpy file. Store it in vector.
Parameters
header
Definition at line 105 of file cnpy.cpp.
{
    // Read header, till we hit newline character.
    char ch;
    fs.seekg(0);                                 // Go to the begining.
    header.clear();
    while(! fs.eof())
    {
        fs.get(ch);
        if( '\n' == ch )
            break;
        header.push_back(ch);
    }
    assert( header.size() >= __pre__.size() );
}
References __pre__.
Referenced by changeHeaderShape().
initNumpyFile()
size_t cnpy2::initNumpyFile (const string & outfile, const vector< string > & colnames)
@Synopsis initialize a numpy file with given column names.
@Param filename @Param colnames
Definition at line 214 of file cnpy.cpp.
{
    std::fstream fs;
    fs.open(outfile, std::fstream::in | std::fstream::out | std::fstream::trunc | std::ofstream::binary);
    if(! fs.is_open())
    {
        cerr << "Error: Could not create " << outfile << endl;
        return 0;
    }
    vector<size_t> shape;
    auto pos = writeHeader(fs, colnames, shape);
    fs.close();
    return pos;
}
References writeHeader().
Referenced by main().
isValidNumpyFile() [1/2]
bool cnpy2::isValidNumpyFile (std::ifstream & fp)
Check if a numpy file is sane or not.
Read first 8 bytes and compare with standard header.
Parameters
npy_file Path to file.
Returns
true if file is sane, else false.
isValidNumpyFile() [2/2]
bool cnpy2::isValidNumpyFile (string npy_file)
Check if a numpy file is sane or not.
Read first 8 bytes and compare with standard header.
Parameters
npy_file Path to file.
Returns
true if file is sane, else false.
Definition at line 82 of file cnpy.cpp.
{
    char c;
    istream_iterator<char> istream_iterator;
    ifstream file(npy_file);
    for(auto &current : __pre__)
    {
        file.get(c);
        if((c != current) || (c == EOF))
    {
            file.close();
        return false;
    }
    }
    file.close();
    return true;
}
References __pre__.
readNumpy()
void cnpy2::readNumpy (const string & infile, vector< double > & data)
@Synopsis read numpy file and return data in a vector. This for testing purpose and should not used to read data.
@Param infile @Param data
Definition at line 285 of file cnpy.cpp.
{
    cout << "Reading from " << infile << endl;
    std::ifstream fs;
    fs.open(infile, std::ios::in | std::ios::binary);
    if(! fs.is_open())
    {
        cerr << "Could not open " << infile << endl;
        return;
    }
    char ch;
    fs.get(ch);
    size_t nBytes = 1;
    while(ch != '\n')
    {
        fs.get(ch);
        nBytes += 1;
    }
    char buff[sizeof(double)];
    double x;
    fs.seekg(nBytes, std::ios_base::beg);
    while(! fs.eof())
    {
        fs.read(buff, sizeof(double));
        if(fs.gcount() != 8)
            break;
        memcpy(&x, buff, sizeof(double));
        data.push_back(x);
    }
    cout << endl;
    fs.close();
}
Referenced by main().
shapeToString()
string cnpy2::shapeToString (const vector< size_t > & shape)
Definition at line 53 of file cnpy.cpp.
{
    string s{"("};
    if(! shape.empty())
    {
        s += std::to_string(shape[0]);
        for(size_t i = 1; i < shape.size(); i++)
        {
            s += ",";
            s += std::to_string(shape[i]);
        }
        if(shape.size() == 1)
            s += ",";
    }
    else
        s += "0,";
    s += ")";
    return s;
}
Referenced by writeHeader().
split()
void cnpy2::split (vector< string > & strs, string & input, const string & pat)
Definition at line 41 of file cnpy.cpp.
{
    char* pch;
    pch = strtok( &input[0], pat.c_str() );
    while( pch != NULL )
    {
        strs.push_back( string(pch ) );
        pch = strtok( NULL, pat.c_str() );
    }
    delete pch;
}
Referenced by changeHeaderShape().
writeHeader()
size_t cnpy2::writeHeader (std::fstream & fp, const vector< string > & colnames, const vector< size_t > & shape)
Definition at line 167 of file cnpy.cpp.
{
    // Heder are always at the begining of file.
    fs.seekp(0);
    // Write the format string. 8 bytes.
    fs.write(&__pre__[0], __pre__.size());
    char endianChar = cnpy2::BigEndianTest();
    const char formatChar = 'd';
    // Next 4 bytes are header length. This is computed again when data is
    // appended to the file. We can have maximum of 2^32 bytes of header which
    // ~4GB.
    string header = ""; // This is the header to numpy file
    header += "{'descr':[";
    for( auto it = colnames.cbegin(); it != colnames.end(); it++ )
        header += "('" + *it + "','" + endianChar + formatChar + "'),";
    // shape is changed everytime we append the data. We use fixed number of
    // character in shape. Its a int, we will use 13 chars to represent shape.
    header += "], 'fortran_order':False,'shape':";
    header += shapeToString(shape);
    header += ",}";
    // Add some extra sapce for safety.
    header += string(12, ' ');
    // FROM THE DOC: It is terminated by a newline (\n) and padded with spaces
    // (\x20) to make the total of len(magic string) + 2 + len(length) +
    // HEADER_LEN be evenly divisible by 64 for alignment purposes.
    // pad with spaces so that preamble+headerlen+header is modulo 16 bytes.
    // preamble is 8 bytes, header len is 4 bytes, total 12.
    // header needs to end with \n
    unsigned int remainder = 16 - (12 + header.size()) % 16;
    header.insert(header.end(), remainder-1, ' ');
    header += '\n';                             // Add newline.
    // Now write the size of header. Its 4 byte long in version 2.
    uint32_t s = header.size();
    fs.write((char*)&s, 4);
    fs << header;
    return fs.tellp();
}
References __pre__, BigEndianTest(), and shapeToString().
Referenced by initNumpyFile(), and writeNumpy().
writeNumpy()
void cnpy2::writeNumpy (const string & outfile, const vector< double > & vec, const vector< string > & colnames)
Definition at line 230 of file cnpy.cpp.
{
    // In our application, we need to write a vector as matrix. We do not
    // support the stacking of matrices.
    vector<size_t> shape;
    if( colnames.size() == 0)
        return;
    shape.push_back(data.size() / colnames.size());
    // Create a new file.
    std::fstream fs;
    fs.open(outfile, std::ofstream::in | std::ofstream::out | std::ofstream::binary | std::ofstream::trunc);
    /* In mode "w", open the file and write a header as well. When file is open
     * in mode "a", we assume that file is alreay a valid numpy file.
     */
    if(! fs.is_open())
    {
        moose::showWarn( "Could not open file " + outfile );
        return;
    }
    auto p = writeHeader( fs, colnames, shape );
    fs.seekp(p);
    // Here the previous character is '\n'
    fs.write(reinterpret_cast<const char*>(data.data()), sizeof(double)*data.size());
    fs.close();
}
References moose::showWarn(), and writeHeader().
Referenced by main(), and StreamerBase::writeToNPYFile().
Variable Documentation
__pre__
vector<char> cnpy2::__pre__ static
Initial value:
{
    (char)0x93, 'N', 'U', 'M', 'P', 'Y'
    , (char)0x02, (char) 0x00
}
Definition at line 79 of file cnpy.hpp.
{
    (char)0x93, 'N', 'U', 'M', 'P', 'Y'         /* Magic */
    , (char)0x02, (char) 0x00               /* format */
};
Referenced by findHeader(), isValidNumpyFile(), and writeHeader().
headerSize
size_t cnpy2::headerSize = 0
Definition at line 39 of file cnpy.cpp.