MOOSE - Multiscale Object Oriented Simulation Environment: /home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/mesh/NeuroMesh.cpp File Reference
NeuroMesh.cpp File Reference
#include "../basecode/header.h"
#include "../basecode/SparseMatrix.h"
#include "../basecode/ElementValueFinfo.h"
#include "../utility/Vec.h"
#include "Boundary.h"
#include "MeshEntry.h"
#include "ChemCompt.h"
#include "MeshCompt.h"
#include "CubeMesh.h"
#include "CylBase.h"
#include "NeuroNode.h"
#include "NeuroMesh.h"
#include "SpineEntry.h"
#include "SpineMesh.h"
#include "EndoMesh.h"
#include "../utility/numutil.h"
#include "../utility/strutil.h"
#include "../shell/Wildcard.h"
Functions
Id getParentFromMsg (Id id)
static SrcFinfo3< vector< double >, vector< Id >, vector< unsigned int > > * psdListOut ()
static SrcFinfo3< vector< Id >, vector< Id >, vector< unsigned int > > * spineListOut ()
Id tryParent (Id id, const string &msgName)
Variables
static const Cinfo * neuroMeshCinfo = NeuroMesh::initCinfo()
Function Documentation
getParentFromMsg()
Id getParentFromMsg (Id id)
Definition at line 457 of file NeuroMesh.cpp.
{
    if ( id.element()->cinfo()->isA( "Compartment" ) )
        return tryParent( id, "axialOut" );
    if ( id.element()->cinfo()->isA( "SymCompartment" ) )
        return tryParent( id, "proximalOut" );
    return Id();
}
References Element::cinfo(), Id::element(), Id::Id(), Cinfo::isA(), and tryParent().
psdListOut()
static SrcFinfo3< vector< double >, vector< Id >, vector< unsigned int > > * psdListOut () static
Definition at line 46 of file NeuroMesh.cpp.
{
    static SrcFinfo3< vector< double >,
           vector< Id >, vector< unsigned int > >
           psdListOut(
               "psdListOut",
               "Tells PsdMesh to build a mesh. "
               "Arguments: (Cell Id, Coordinates of each psd, "
               "Id of electrical compartment mapped to each voxel, "
               "index of matching parent voxels for each spine.) "
               "The coordinates each have 8 entries:"
               "xyz of centre of psd, xyz of vector perpendicular to psd, "
               "psd diameter, "
               " diffusion distance from parent compartment to PSD"
           );
    return &psdListOut;
}
References SrcFinfo3< T1, T2, T3 >::SrcFinfo3().
Referenced by NeuroMesh::initCinfo(), and NeuroMesh::transmitSpineInfo().
spineListOut()
static SrcFinfo3< vector< Id >, vector< Id >, vector< unsigned int > > * spineListOut () static
Definition at line 30 of file NeuroMesh.cpp.
{
    static SrcFinfo3< vector< Id >, vector< Id >, vector< unsigned int > >
    spineListOut(
        "spineListOut",
        "Request SpineMesh to construct self based on list of electrical "
        "compartments that this NeuroMesh has determined are spine shaft "
        "and spine head respectively. Also passes in the info about where "
        "each spine is connected to the NeuroMesh. "
        "Arguments: shaft compartment Ids, head compartment Ids,"
        "index of matching parent voxels for each spine"
    );
    return &spineListOut;
}
References SrcFinfo3< T1, T2, T3 >::SrcFinfo3().
Referenced by NeuroMesh::initCinfo(), and NeuroMesh::transmitSpineInfo().
tryParent()
Id tryParent (Id id, const string & msgName)
Definition at line 444 of file NeuroMesh.cpp.
{
    const Finfo* finfo = id.element()->cinfo()->findFinfo( msgName );
    if ( !finfo )
        return Id();
    vector< Id > ret;
    id.element()->getNeighbors( ret, finfo );
    assert( ret.size() <= 1 );
    if ( ret.size() == 1 )
        return ret[0];
    return Id();
}
References Element::cinfo(), Id::element(), Cinfo::findFinfo(), Element::getNeighbors(), and Id::Id().
Referenced by getParentFromMsg().
Variable Documentation
neuroMeshCinfo
const Cinfo* neuroMeshCinfo = NeuroMesh::initCinfo() static
Definition at line 280 of file NeuroMesh.cpp.