MOOSE - Multiscale Object Oriented Simulation Environment: /home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/biophysics/Neuron.cpp File Reference
Neuron.cpp File Reference
#include "../basecode/header.h"
#include "../basecode/ElementValueFinfo.h"
#include "../basecode/LookupElementValueFinfo.h"
#include "../shell/Shell.h"
#include "../shell/Wildcard.h"
#include "../randnum/randnum.h"
#include "ReadCell.h"
#include "../utility/Vec.h"
#include "SwcSegment.h"
#include "Spine.h"
#include "Neuron.h"
#include "../builtins/MooseParser.h"
Classes
class nuParser
Functions
static void addPos (unsigned int segIndex, unsigned int eIndex, double spacing, double minSpacing, double dendLength, vector< unsigned int > &seglistIndex, vector< unsigned int > &elistIndex, vector< double > &pos)
Add entries into the pos vector for a given compartment i.
static vector< Id > addSpine (Id parentCompt, Id spineProto, double pos, double angle, Vec &x, Vec &y, Vec &z, double size, unsigned int k)
static void assignParam (Id obj, const string &field, double val, double len, double dia)
static void assignSingleCompartmentParams (ObjId compt, double val, const string &field, double len, double dia)
static bool buildFromProto (const string &name, const vector< ObjId > &elist, const vector< double > &val, vector< ObjId > &mech)
static double coordSystem (Id soma, Id dend, Vec &x, Vec &y, Vec &z)
static void doClassSpecificMessaging (Shell *shell, Id obj, ObjId compt)
Id fillSegIndex (const vector< Id > &kids, map< Id, unsigned int > &segIndex)
static void fillSegments (vector< SwcSegment > &segs, const map< Id, unsigned int > &segIndex, const vector< Id > &kids)
string findArg (const vector< string > &line, const string &field)
static Id getComptParent (Id id)
static void makeAngleDistrib (const vector< ObjId > &elist, const vector< double > &val, vector< unsigned int > &elistIndex, vector< double > &theta, const vector< string > &line)
static void makeSizeDistrib (const vector< ObjId > &elist, const vector< double > &val, vector< unsigned int > &elistIndex, vector< double > &size, const vector< string > &line)
bool parseDistrib (vector< vector< string > > &lines, const vector< string > &distrib)
static void reorientSpine (vector< Id > &spineCompts, vector< Vec > &coords, Vec &parentPos, double pos, double angle, Vec &x, Vec &y, Vec &z)
static void setCompartmentParams (const vector< ObjId > &elist, const vector< double > &val, const string &field, const string &expr)
static void setMechParams (const vector< ObjId > &mech, const vector< ObjId > &elist, const vector< double > &val, const string &field, const string &expr)
static void traverseCumulativeDistance (SwcSegment &self, vector< SwcSegment > &segs, const vector< Id > &lookupId, double len, double L, double pSoma, double eSoma)
Recursive function to fill in cumulative distances from soma.
Variables
static const Cinfo * neuronCinfo = Neuron::initCinfo()
Function Documentation
addPos()
static void addPos (unsigned int segIndex, unsigned int eIndex, double spacing, double minSpacing, double dendLength, vector< unsigned int > & seglistIndex, vector< unsigned int > & elistIndex, vector< double > & pos) static
Add entries into the pos vector for a given compartment i.
Definition at line 1843 of file Neuron.cpp.
{
    if ( minSpacing < 0.0 ) {
        // Use uniform spacing
        for ( double position = spacing * 0.5;
                position < dendLength; position += spacing ) {
            seglistIndex.push_back( segIndex );
            elistIndex.push_back( eIndex );
            pos.push_back( position );
        }
        if ( dendLength > spacing * 0.5 )
            return;
        // If the dend length is too small for regular placement,
        // fall back to using probability to decide if segment gets spine
    }
    if ( minSpacing < spacing * 0.1 && minSpacing < 1e-7 )
        minSpacing = spacing * 0.1;
    if ( minSpacing > spacing * 0.5 )
        minSpacing = spacing * 0.5;
    unsigned int n = 1 + dendLength / minSpacing;
    double dx = dendLength / n;
    for( unsigned int i = 0; i < n; ++i )
    {
        // Use global RNG.
        if ( moose::mtrand() < dx / spacing )
        {
            seglistIndex.push_back( segIndex );
            elistIndex.push_back( eIndex );
            pos.push_back( i * dx + dx*0.5 );
        }
    }
}
References moose::mtrand().
Referenced by Neuron::makeSpacingDistrib().
addSpine()
static vector< Id > addSpine (Id parentCompt, Id spineProto, double pos, double angle, Vec & x, Vec & y, Vec & z, double size, unsigned int k) static
Utility function to add a single spine to the given parent. Returns vector of added spine contents. parent is parent compartment for this spine. spineProto is just that. pos is position (in metres) along parent compartment angle is angle (in radians) to rotate spine wrt x in plane xy. Size is size scaling factor, 1 leaves as is. x, y, z are unit vectors. Z is along the parent compt. We first shift the spine over so that it is offset by the parent compt diameter. We then need to reorient the spine which lies along (i,0,0) to lie along x. X is a unit vector so this is done simply by multiplying each coord of the spine by x. Finally we rotate the spine around the z axis by the specified angle k is index of this spine.
Definition at line 1708 of file Neuron.cpp.
{
    Shell* shell = reinterpret_cast< Shell* >( Id().eref().data() );
    Id parentObject = Neutral::parent( parentCompt );
    stringstream sstemp;
    sstemp << k;
    string kstr = sstemp.str();
    Id spine = shell->doCopy( spineProto, parentObject, "_spine" + kstr,
                              1, false, false );
    vector< Id > kids;
    Neutral::children( spine.eref(), kids );
    double x0 = Field< double >::get( parentCompt, "x0" );
    double y0 = Field< double >::get( parentCompt, "y0" );
    double z0 = Field< double >::get( parentCompt, "z0" );
    double parentRadius = Field< double >::get( parentCompt, "diameter" )/2;
    Vec ppos( x0, y0, z0 );
    // First, build the coordinates vector for the spine. Assume that its
    // major axis is along the unit vector [1,0,0].
    vector< Vec > coords;
    vector< Id > ret; // Filtered to make sure that it returns only compts
    for ( vector< Id >::iterator i = kids.begin(); i != kids.end(); ++i )
    {
        if ( i->element()->cinfo()->isA( "CompartmentBase" ) )
        {
            i->element()->setName( i->element()->getName() + kstr );
            x0 = Field< double >::get( *i, "x0" ) * size;
            y0 = Field< double >::get( *i, "y0" ) * size;
            z0 = Field< double >::get( *i, "z0" ) * size;
            coords.push_back( Vec( x0 + parentRadius, y0, z0 ) );
            double x = Field< double >::get( *i, "x" ) * size;
            double y = Field< double >::get( *i, "y" ) * size;
            double z = Field< double >::get( *i, "z" ) * size;
            double dia = Field< double >::get( *i, "diameter" ) * size;
            // Field< double >::set( *i, "diameter", dia );
            double len = sqrt(
                             (x-x0)*(x-x0) +
                             (y-y0)*(y-y0) +
                             (z-z0)*(z-z0) );
            SetGet2< double, double >::set( *i, "setGeomAndElec", len, dia );
            coords.push_back( Vec( x + parentRadius, y, z ) );
            // scaleSpineCompt( *i, size );
            shell->doMove( *i, parentObject );
            ret.push_back( *i );
        }
    }
    // Then, take the projection of this along the x vector passed in.
    for( vector< Vec >::iterator i = coords.begin(); i != coords.end(); ++i)
        *i = x * i->a0();
    shell->doDelete( spine ); // get rid of the holder for the spine copy.
    shell->doAddMsg( "Single", parentCompt, "axial", kids[0], "raxial" );
    reorientSpine( kids, coords, ppos, pos, angle, x, y, z );
    return ret;
}
References Vec::a0(), Neutral::children(), Element::cinfo(), Eref::data(), Shell::doAddMsg(), Shell::doCopy(), Shell::doDelete(), Shell::doMove(), Id::element(), Id::eref(), Field< A >::get(), Element::getName(), Id::Id(), Cinfo::isA(), Vec::operator*(), Neutral::parent(), reorientSpine(), SetGet2< A1, A2 >::set(), Element::setName(), and Vec::Vec().
Referenced by Neuron::installSpines().
assignParam()
static void assignParam (Id obj, const string & field, double val, double len, double dia) static
Definition at line 703 of file Neuron.cpp.
{
    if ( obj.element()->cinfo()->isA( "ChanBase" ) )
    {
        if ( field == "Gbar" )
        {
            if ( val > 0 )
                Field< double >::set( obj, "Gbar", val * len * dia * PI );
        }
        else if ( field == "Ek" )
        {
            Field< double >::set( obj, "Ek", val );
        }
    }
    else if ( obj.element()->cinfo()->isA( "CaConcBase" ) )
    {
        Field< double >::set( obj, "length", len );
        Field< double >::set( obj, "diameter", dia );
        // cout << "len, dia = " << len << ", " << dia << endl;
        if ( field == "CaBasal" || field == "tau" || field == "thick" ||
                field == "floor" || field == "ceiling" )
        {
            Field< double >::set( obj, field, val );
        }
        else if ( field == "B" )
        {
            // The system obeys dC/dt = B*I_Ca - C/tau
            // So B = arg/( vol * F ). Here the system provides vol and F,
            // so the arg is just a scale factor over this, typically
            // to be thought of in terms of buffering. Small B is more
            // buffering. This field is deprecated but used in legacy
            // GENESIS scripts.
            Field< double >::set( obj, "B", val /
                                  ( FaradayConst * len * dia * dia * PI / 4.0 ) );
        }
    }
}
References Element::cinfo(), Id::element(), FaradayConst, Cinfo::isA(), PI, and Field< A >::set().
Referenced by setMechParams().
assignSingleCompartmentParams()
static void assignSingleCompartmentParams (ObjId compt, double val, const string & field, double len, double dia) static
Definition at line 742 of file Neuron.cpp.
{
    if ( field == "initVm" || field == "INITVM" )
    {
        Field< double >::set( compt, "initVm", val );
        return;
    }
    if ( field == "Em" || field == "EM" )
    {
        Field< double >::set( compt, "Em", val );
        return;
    }
    if ( val > 0.0 )
    {
        if ( field == "Rm" || field == "Ra" || field == "Cm" )
        {
            Field< double >::set( compt, field, val );
        }
        else if ( field == "RM" )
        {
            Field< double >::set( compt, "Rm", val / ( len  * dia * PI ) );
        }
        else if ( field == "RA" )
        {
            Field< double >::set( compt, "Ra", val*len*4 / (dia*dia*PI) );
        }
        else if ( field == "CM" )
        {
            Field< double >::set( compt, "Cm", val * len * dia * PI );
        }
        else
        {
            cout << "Warning: setCompartmentParam: field '" << field <<
                 "' not found\n";
        }
    }
}
References PI, and Field< A >::set().
Referenced by setCompartmentParams().
buildFromProto()
static bool buildFromProto (const string & name, const vector< ObjId > & elist, const vector< double > & val, vector< ObjId > & mech) static
Definition at line 670 of file Neuron.cpp.
{
    Shell* shell = reinterpret_cast< Shell* >( Id().eref().data() );
    Id proto( "/library/" + name );
    if ( proto == Id() )
    {
        cout << "Warning: Neuron::buildFromProto: proto '"
             << name << "' not found, skipping\n";
        return false;
    }
    mech.clear();
    mech.resize( elist.size() );
    for ( unsigned int i = 0; i < elist.size(); ++i )
    {
        unsigned int j = i * nuParser::numVal;
        if ( val[ j + nuParser::EXPR ] > 0 )
        {
            string name = proto.element()->getName();
            Id obj = Neutral::child( elist[i].eref(), name );
            if ( obj == Id() )   // Need to copy it in from proto.
            {
                obj = shell->doCopy( proto, elist[i], name, 1, false, false );
                doClassSpecificMessaging( shell, obj, elist[i] );
            }
            mech[i] = obj;
        }
    }
    return true;
}
References Neutral::child(), Eref::data(), doClassSpecificMessaging(), Shell::doCopy(), Id::element(), Id::eref(), ObjId::eref(), nuParser::EXPR, Element::getName(), Id::Id(), Id::Id(), nuParser::numVal, and Id::operator==().
Referenced by Neuron::setChannelDistribution().
coordSystem()
static double coordSystem (Id soma, Id dend, Vec & x, Vec & y, Vec & z) static
Utility function to return a coordinate system where z is the direction of a dendritic segment, x is the direction of spines outward from soma and perpendicular to z and y is the perpendicular to x and z.
Definition at line 1605 of file Neuron.cpp.
{
    static const double EPSILON = 1e-20;
    double x0 = Field< double >::get( dend, "x0" );
    double y0 = Field< double >::get( dend, "y0" );
    double z0 = Field< double >::get( dend, "z0" );
    double x1 = Field< double >::get( dend, "x" );
    double y1 = Field< double >::get( dend, "y" );
    double z1 = Field< double >::get( dend, "z" );
    Vec temp( x1-x0, y1-y0, z1-z0 );
    double len = temp.length();
    z = Vec( temp.a0()/len, temp.a1()/len, temp.a2()/len );
    double sx0 = Field< double >::get( soma, "x0" );
    double sy0 = Field< double >::get( soma, "y0" );
    double sz0 = Field< double >::get( soma, "z0" );
    Vec temp2( x0 - sx0, y0-sy0, z0-sz0 );
    Vec y2 = temp.crossProduct( z );
    double ylen = y2.length();
    double ytemp = 1.0;
    while ( ylen < EPSILON )
    {
        Vec t( ytemp , sqrt( 2.0 ), 0.0 );
        y2 = t.crossProduct( z );
        ylen = y2.length();
        ytemp += 1.0;
    }
    y = Vec( y2.a0()/ylen, y2.a1()/ylen, y2.a2()/ylen );
    x = z.crossProduct( y );
    assert( doubleEq( x.length(), 1.0 ) );
    return len;
}
References Vec::a0(), Vec::a1(), Vec::a2(), Vec::crossProduct(), doubleEq(), Field< A >::get(), Vec::length(), and Vec::Vec().
Referenced by Neuron::installSpines().
doClassSpecificMessaging()
static void doClassSpecificMessaging (Shell * shell, Id obj, ObjId compt) static
Definition at line 642 of file Neuron.cpp.
{
    if ( obj.element()->cinfo()->isA( "ChanBase" ) )
    {
        shell->doAddMsg( "Single", compt, "channel", obj, "channel" );
        // Add the message to the Ca pool if our obj has 'Ca' in its name.
        if ( obj.element()->getName().find( "Ca" ) != string::npos )
        {
            // Don't do it if we have the legacy GENESIS format
            if ( Neutral::child( obj.eref(), "addmsg1" ) == Id() )
            {
                vector< ObjId > elist;
                string path = Neutral::parent( obj ).path() + "/#[ISA=CaConcBase]";
                // cout << "OK2 to Add Ca Msg for " << path << endl;
                wildcardFind( path, elist );
                if ( elist.size() > 0 )
                {
                    // cout << "Added Ca Msg for " << obj.path() << ", name = " << obj.element()->getName() << endl;
                    ObjId mid = shell->doAddMsg(
                                    "single", obj, "IkOut", elist[0], "current" );
                    assert( !mid.bad());
                }
            }
        }
    }
    ReadCell::addChannelMessage( obj );
}
References ReadCell::addChannelMessage(), ObjId::bad(), Neutral::child(), Element::cinfo(), Shell::doAddMsg(), Id::element(), Id::eref(), Element::getName(), Id::Id(), Cinfo::isA(), Id::operator==(), Neutral::parent(), ObjId::path(), and wildcardFind().
Referenced by buildFromProto().
fillSegIndex()
Id fillSegIndex (const vector< Id > & kids, map< Id, unsigned int > & segIndex)
Definition at line 1287 of file Neuron.cpp.
{
    Id soma;
    segIndex.clear();
    Id fatty;
    double maxDia = 0.0;
    unsigned int numKids = 0;
    for ( unsigned int i = 0; i < kids.size(); ++i )
    {
        const Id& k = kids[i];
        if ( k.element()->cinfo()->isA( "CompartmentBase" ) )
        {
            segIndex[ k ] = numKids++;
            const string& s = k.element()->getName();
            if ( s.find( "soma" ) != s.npos ||
                    s.find( "Soma" ) != s.npos ||
                    s.find( "SOMA" ) != s.npos )
            {
                soma = k;
            }
            double dia = Field< double >::get( k, "diameter" );
            if ( dia > maxDia )
            {
                maxDia = dia;
                fatty = k;
            }
        }
    }
    if ( soma != Id() )
        return soma;
    return fatty; // Fallback.
}
References Element::cinfo(), Id::element(), Field< A >::get(), Element::getName(), Id::Id(), Cinfo::isA(), and Id::operator!=().
Referenced by Neuron::buildSegmentTree().
fillSegments()
static void fillSegments (vector< SwcSegment > & segs, const map< Id, unsigned int > & segIndex, const vector< Id > & kids) static
Definition at line 1321 of file Neuron.cpp.
{
    segs.clear();
    for ( unsigned int i = 0; i < kids.size(); ++i )
    {
        const Id& k = kids[i];
        if ( k.element()->cinfo()->isA( "CompartmentBase" ) )
        {
            double x = Field< double >::get( k, "x" );
            double y = Field< double >::get( k, "y" );
            double z = Field< double >::get( k, "z" );
            double dia = Field< double >::get( k, "diameter" );
            Id pa = getComptParent( k );
            unsigned int paIndex = ~0U; // soma
            int comptType = 1; // soma
            if ( pa != Id() )
            {
                map< Id, unsigned int >::const_iterator
                j = segIndex.find( pa );
                if ( j != segIndex.end() )
                {
                    paIndex = j->second;
                    comptType = 3; // generic dendrite
                }
            }
            // cout << "Seg[" << i << "].xy = " << int(x*1e6) << " " << int(y*1e6) << endl;
            segs.push_back(
                SwcSegment( i, comptType, x, y, z, dia/2.0, paIndex ) );
        }
    }
}
References Element::cinfo(), Id::element(), Field< A >::get(), getComptParent(), Id::Id(), Cinfo::isA(), Id::operator!=(), and SwcSegment::SwcSegment().
Referenced by Neuron::buildSegmentTree().
findArg()
string findArg (const vector< string > & line, const string & field)
Definition at line 1775 of file Neuron.cpp.
{
    // line has: proto path [field val]...
    assert( (line.size() % 2) != 1 );
    for ( unsigned int i = 2; i < line.size(); i+=2 )
        if ( line[i] == field )
            return line[i+1];
    string ret = "";
    if ( field == "spacing" )
    {
        ret = "1.0e-6";
    }
    else if ( field == "spacingDistrib" )
    {
        ret = "0";
    }
    else if ( field == "size" )
    {
        ret = "1";
    }
    else if ( field == "sizeDistrib" )
    {
        ret = "0";
    }
    else if ( field == "angle" )
    {
        ret = "0";
    }
    else if ( field == "angleDistrib" )
    {
        ret = "6.283185307";
    }
    else if ( field == "rotation" )
    {
        ret = "0";
    }
    else if ( field == "rotationDistrib" )
    {
        ret = "6.283185307"; // 2*PI
    }
    else if ( field == "shaftLen" )
    {
        ret = "1.0e-6";
    }
    else if ( field == "shaftDia" )
    {
        ret = "0.2e-6";
    }
    else if ( field == "headLen" )
    {
        ret = "0.5e-6";
    }
    else if ( field == "headDia" )
    {
        ret = "0.5e-6";
    }
    else if ( field == "theta" )
    {
        ret = "0";
    }
    else if ( field == "phi" )
    {
        ret = "1.5707963268"; // PI/2
    }
    return ret;
}
Referenced by makeAngleDistrib(), makeSizeDistrib(), and Neuron::makeSpacingDistrib().
getComptParent()
static Id getComptParent (Id id) static
Definition at line 1261 of file Neuron.cpp.
{
    // raxial points towards soma.
    static const Finfo* raxialFinfo =
        Cinfo::find( "Compartment" )->findFinfo( "raxialOut" );
    static const Finfo* proximalFinfo =
        Cinfo::find( "SymCompartment" )->findFinfo( "proximalOut" );
    if ( id.element()->cinfo()->isA( "CompartmentBase" ) )
    {
        vector< Id > ret;
        id.element()->getNeighbors( ret, raxialFinfo );
        if ( ret.size() == 1 )
            return ret[0];
        // If it didn't find an axial, maybe it is a symCompt
        if ( id.element()->cinfo()->isA( "SymCompartment" ) )
        {
            id.element()->getNeighbors( ret, proximalFinfo );
            if ( ret.size() == 1 )
                return ret[0];
        }
    }
    return Id();
}
References Element::cinfo(), Id::element(), Cinfo::find(), Cinfo::findFinfo(), Element::getNeighbors(), Id::Id(), and Cinfo::isA().
Referenced by fillSegments().
makeAngleDistrib()
static void makeAngleDistrib (const vector< ObjId > & elist, const vector< double > & val, vector< unsigned int > & elistIndex, vector< double > & theta, const vector< string > & line) static
Definition at line 1953 of file Neuron.cpp.
{
    string angleExpr = findArg( line, "angle" );
    string angleDistribExpr = findArg( line, "angleDistrib" );
    // I won't bother with rotation and rotation distrb for now.
    // Easy to add, but on reflection they don't make sense.
    theta.clear();
    theta.resize( elistIndex.size(), 0.0 );
    try
    {
        nuParser angleParser( angleExpr );
        nuParser distribParser( angleDistribExpr );
        unsigned int lastIndex = ~0U;
        double angle = 0;
        double angleDistrib = 0;
        for ( unsigned int k = 0; k < elistIndex.size(); ++k )
        {
            unsigned int i = elistIndex[k];
            if ( i != lastIndex )
            {
                lastIndex = i;
                unsigned int j = i * nuParser::numVal;
                angle = angleParser.eval( val.begin() + j );
                angleDistrib = distribParser.eval( val.begin() + j);
            }
            // Use global RNG.
            if ( angleDistrib > 0 )
                theta[k] = angle + ( moose::mtrand() - 0.5 ) * angleDistrib;
            else
                theta[k] = angle;
        }
    }
    catch ( moose::Parser::exception_type& err )
    {
        cout << err.GetMsg() << endl;
    }
}
References nuParser::eval(), findArg(), moose::Parser::ParserException::GetMsg(), moose::mtrand(), nuParser::numVal, and nuParser::nuParser().
Referenced by Neuron::installSpines().
makeSizeDistrib()
static void makeSizeDistrib (const vector< ObjId > & elist, const vector< double > & val, vector< unsigned int > & elistIndex, vector< double > & size, const vector< string > & line) static
Definition at line 1997 of file Neuron.cpp.
{
    string sizeExpr = findArg( line, "size" );
    string sizeDistribExpr = findArg( line, "sizeDistrib" );
    size.clear();
    size.resize( elistIndex.size(), 0.0 );
    try
    {
        nuParser sizeParser( sizeExpr );
        nuParser distribParser( sizeDistribExpr );
        unsigned int lastIndex = ~0U;
        double sz = 1.0;
        double sizeDistrib = 0;
        for ( unsigned int k = 0; k < elistIndex.size(); ++k )
        {
            unsigned int i = elistIndex[k];
            if ( i != lastIndex )
            {
                lastIndex = i;
                unsigned int j = i * nuParser::numVal;
                sz = sizeParser.eval( val.begin() + j );
                sizeDistrib = distribParser.eval( val.begin() + j);
            }
            // Use global RNG.
            if ( sizeDistrib > 0 )
                size[k] = sz + ( moose::mtrand() - 0.5 ) * sizeDistrib;
            else
                size[k] = sz;
        }
    }
    catch ( moose::Parser::exception_type& err )
    {
        cout << err.GetMsg() << endl;
    }
}
References nuParser::eval(), findArg(), moose::Parser::ParserException::GetMsg(), moose::mtrand(), nuParser::numVal, and nuParser::nuParser().
Referenced by Neuron::installSpines().
parseDistrib()
bool parseDistrib (vector< vector< string > > & lines, const vector< string > & distrib)
Definition at line 610 of file Neuron.cpp.
{
    lines.clear();
    vector< string > temp;
    for ( unsigned int i = 0; i < distrib.size(); ++i )
    {
        if ( distrib[i] == "" )
        {
            if ( temp.size() < 4 )
            {
                cout << "Warning: Neuron::parseDistrib: <4 args: " <<
                     temp.size() << endl;
                return false;
            }
            if ( temp.size() % 2 == 1 )
            {
                cout << "Warning: Neuron::parseDistrib: : odd # of args:"
                     << temp.size() << endl;
                return false;
            }
            lines.push_back( temp );
            temp.clear();
        }
        else
        {
            temp.push_back( distrib[i] );
        }
    }
    return true;
}
Referenced by Neuron::setChannelDistribution(), Neuron::setPassiveDistribution(), and Neuron::setSpineDistribution().
reorientSpine()
static void reorientSpine (vector< Id > & spineCompts, vector< Vec > & coords, Vec & parentPos, double pos, double angle, Vec & x, Vec & y, Vec & z) static
Utility function to change coords of spine so as to reorient it.
Definition at line 1642 of file Neuron.cpp.
{
    double c = cos( angle );
    double s = sin( angle );
    double omc = 1.0 - c;
    Vec rot0(       z.a0()*z.a0()*omc + c,
                    z.a1()*z.a0()*omc - z.a2()*s ,
                    z.a2()*z.a0()*omc + z.a1()*s );
    Vec rot1(       z.a0()*z.a1()*omc + z.a2()*s,
                    z.a1()*z.a1()*omc + c,
                    z.a2()*z.a1()*omc - z.a0()*s );
    Vec rot2(       z.a0()*z.a2()*omc - z.a1()*s,
                    z.a1()*z.a2()*omc + z.a0()*s,
                    z.a2()*z.a2()*omc + c );
    Vec translation = z * pos + parentPos;
    // Vec translation = parentPos;
    vector< Vec > ret( coords.size() );
    for ( unsigned int i = 0; i < coords.size(); ++i )
    {
        ret[i] = Vec(   rot0.dotProduct( coords[i] ) + translation.a0(),
                        rot1.dotProduct( coords[i] ) + translation.a1(),
                        rot2.dotProduct( coords[i] ) + translation.a2() );
    }
    assert( spineCompts.size() * 2 == ret.size() );
    for ( unsigned int i = 0; i < spineCompts.size(); ++i )
    {
        unsigned int j = 2 * i;
        Field< double >::set( spineCompts[i], "x0", ret[j].a0() );
        Field< double >::set( spineCompts[i], "y0", ret[j].a1() );
        Field< double >::set( spineCompts[i], "z0", ret[j].a2() );
        // cout << "(" << ret[j].a0() << ", " << ret[j].a1() << ", " << ret[j].a2() << ")";
        j = j + 1;
        Field< double >::set( spineCompts[i], "x", ret[j].a0() );
        Field< double >::set( spineCompts[i], "y", ret[j].a1() );
        Field< double >::set( spineCompts[i], "z", ret[j].a2() );
        // cout << "(" << ret[j].a0() << ", " << ret[j].a1() << ", " << ret[j].a2() << ")\n";
    }
}
References Vec::a0(), Vec::a1(), Vec::a2(), Vec::dotProduct(), Vec::operator*(), Vec::operator+(), Field< A >::set(), and Vec::Vec().
Referenced by addSpine().
setCompartmentParams()
static void setCompartmentParams (const vector< ObjId > & elist, const vector< double > & val, const string & field, const string & expr) static
Definition at line 781 of file Neuron.cpp.
{
    try
    {
        nuParser parser( expr );
        for ( unsigned int i = 0; i < elist.size(); ++i )
        {
            unsigned int j = i * nuParser::numVal;
                double len = val[j + nuParser::LEN ];
                double dia = val[j + nuParser::DIA ];
                double x = parser.eval( val.begin() + j );
                assignSingleCompartmentParams( elist[i],
                                               x, field, len, dia );
        }
    }
    catch ( moose::Parser::exception_type& err )
    {
        cout << err.GetMsg() << endl;
    }
}
References assignSingleCompartmentParams(), nuParser::DIA, nuParser::eval(), moose::Parser::ParserException::GetMsg(), nuParser::LEN, nuParser::numVal, and nuParser::nuParser().
Referenced by Neuron::setPassiveDistribution().
setMechParams()
static void setMechParams (const vector< ObjId > & mech, const vector< ObjId > & elist, const vector< double > & val, const string & field, const string & expr) static
Definition at line 804 of file Neuron.cpp.
{
    try
    {
        nuParser parser ( expr );
        for ( unsigned int i = 0; i < elist.size(); ++i )
        {
            unsigned int j = i * nuParser::numVal;
            if ( val[ j + nuParser::EXPR ] > 0 )
            {
                double len = val[j + nuParser::LEN ];
                double dia = val[j + nuParser::DIA ];
                double x = parser.eval( val.begin() + j );
                assignParam( mech[i], field, x, len, dia );
            }
        }
    }
    catch ( moose::Parser::exception_type& err )
    {
        cout << err.GetMsg() << endl;
    }
}
References assignParam(), nuParser::DIA, nuParser::eval(), nuParser::EXPR, moose::Parser::ParserException::GetMsg(), nuParser::LEN, nuParser::numVal, and nuParser::nuParser().
Referenced by Neuron::setChannelDistribution().
traverseCumulativeDistance()
static void traverseCumulativeDistance (SwcSegment & self, vector< SwcSegment > & segs, const vector< Id > & lookupId, double len, double L, double pSoma, double eSoma) static
Recursive function to fill in cumulative distances from soma.
Definition at line 1357 of file Neuron.cpp.
{
    self.setCumulativeDistance( len, L, pSoma, eSoma );
    for ( unsigned int i = 0; i < self.kids().size(); ++i )
    {
        SwcSegment& kid = segs[ self.kids()[i] ];
        double segmentLength = kid.distance( self );
        double p = pSoma + segmentLength;
        Id kidId = lookupId[ self.kids()[i] ];
        double Rm = Field< double >::get( kidId, "Rm" );
        double Ra = Field< double >::get( kidId, "Ra" );
        // Note that sqrt( Rm/Ra ) = lambda/length = 1/L.
        double electrotonicLength = sqrt( Ra / Rm );
        double e = eSoma + electrotonicLength;
        traverseCumulativeDistance( kid, segs, lookupId,
                                    segmentLength, electrotonicLength, p, e );
    }
}
References SwcSegment::distance(), Field< A >::get(), SwcSegment::kids(), SwcSegment::setCumulativeDistance(), and traverseCumulativeDistance().
Referenced by traverseCumulativeDistance(), and Neuron::updateSegmentLengths().
Variable Documentation
neuronCinfo
const Cinfo* neuronCinfo = Neuron::initCinfo() static
Definition at line 562 of file Neuron.cpp.