MOOSE - Multiscale Object Oriented Simulation Environment: /home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/mesh/NeuroNode.cpp File Reference
NeuroNode.cpp File Reference
#include "../basecode/header.h"
#include "../basecode/SparseMatrix.h"
#include "Boundary.h"
#include "MeshEntry.h"
#include "VoxelJunction.h"
#include "ChemCompt.h"
#include "MeshCompt.h"
#include "CubeMesh.h"
#include "../utility/Vec.h"
#include "../utility/strutil.h"
#include "CylBase.h"
#include "NeuroNode.h"
Functions
static bool checkForSpine (unsigned int dendIndex, Id compt, vector< Id > &shaftId, vector< Id > &headId, vector< unsigned int > &spineParent)
void diagnoseTree (const vector< NeuroNode > &tree, const vector< NeuroNode > &nodes)
static vector< Id > findAllConnectedCompartments (Id compt)
bool isPartOfDend (ObjId i)
void reassignNodeIndices (vector< NeuroNode > &temp, const vector< unsigned int > &nodeToTempMap)
static void sortByShaftIds (vector< Id > &shaftId, vector< Id > &headId, vector< unsigned int > &spineParent)
static void spinyTraverse (unsigned int dendIndex, vector< Id > &dend, const unordered_map< Id, unsigned int > &dendMap, vector< int > &seen, unsigned int numSeen, vector< Id > &shaftId, vector< Id > &headId, vector< int > &dendParent, vector< unsigned int > &spineParent)
Function Documentation
checkForSpine()
static bool checkForSpine (unsigned int dendIndex, Id compt, vector< Id > & shaftId, vector< Id > & headId, vector< unsigned int > & spineParent) static
Definition at line 391 of file NeuroNode.cpp.
{
    const string& name = compt.element()->getName();
    if ( name.find( "shaft" ) != string::npos ||
        name.find( "neck" ) != string::npos ) {
        spineParent.push_back( dendIndex );
        shaftId.push_back( compt );
        vector< Id > conn = findAllConnectedCompartments( compt );
        bool foundHead = false;
        for ( vector< Id >::iterator i =
                        conn.begin(); i != conn.end(); ++i ) {
            const string& n2 = i->element()->getName();
            if ( n2.find( "spine" ) != string::npos ||
                n2.find( "head" ) != string::npos ) {
                headId.push_back( *i );
                foundHead = true;
                break;
            }
        }
        if (!foundHead) {
            headId.push_back( Id() );
        }
        return true;
    }
    return false;
}
References Id::element(), findAllConnectedCompartments(), Element::getName(), and Id::Id().
Referenced by spinyTraverse().
diagnoseTree()
void diagnoseTree (const vector< NeuroNode > & tree, const vector< NeuroNode > & nodes)
static func
Definition at line 298 of file NeuroNode.cpp.
{
    map< Id , const NeuroNode* > m;
    for ( vector< NeuroNode >::const_iterator
                    i = tree.begin(); i != tree.end(); ++i ) {
        m[ i->elecCompt() ] = &( *i );
    }
    unsigned int j = 0;
    for ( vector< NeuroNode >::const_iterator
                    i = nodes.begin(); i != nodes.end(); ++i ) {
        if ( m.find( i->elecCompt() ) == m.end() ) {
            Id pa;
            if ( i->parent() != ~0U && i->parent() < nodes.size() )
                pa = nodes[ i->parent() ].elecCompt();
            cout << "diagnoseTree:" << j++ << " " << i->elecCompt().path() <<
                    ",  pa = " << i->parent() << ", " << pa.path() << endl;
        }
    }
}
References NeuroNode::elecCompt(), NeuroNode::parent(), and Id::path().
Referenced by NeuroNode::traverse().
findAllConnectedCompartments()
static vector< Id > findAllConnectedCompartments (Id compt) static
Finds all the compartments connected to current node, put them all into the return vector even if they may be 'parent' by the messaging. This is because this function has to be robust enough to sort this out
Definition at line 151 of file NeuroNode.cpp.
{
    static const Finfo* axialOut = Cinfo::find( "CompartmentBase" )->findFinfo( "axialOut" );
    static const Finfo* raxialOut = Cinfo::find( "CompartmentBase" )->findFinfo( "raxialOut" );
    static const Finfo* distalOut = Cinfo::find( "SymCompartment" )->findFinfo( "distalOut" );
    static const Finfo* proximalOut = Cinfo::find( "SymCompartment" )->findFinfo( "proximalOut" );
    static const Finfo* cylinderOut = Cinfo::find( "SymCompartment" )->findFinfo( "cylinderOut" );
    static const Finfo* sumRaxialOut = Cinfo::find( "SymCompartment" )->findFinfo( "sumRaxialOut" );
    assert( axialOut );
    assert( raxialOut );
    assert( distalOut );
    assert( proximalOut );
    assert( cylinderOut );
    assert( sumRaxialOut );
    const Cinfo* cinfo = compt.element()->cinfo();
    vector< Id > all;
    if ( cinfo->isA( "SymCompartment" ) ) { // Check derived first.
        vector< Id > ret;
        compt.element()->getNeighbors( ret, distalOut );
        all.insert( all.end(), ret.begin(), ret.end() );
        compt.element()->getNeighbors( ret, proximalOut );
        all.insert( all.end(), ret.begin(), ret.end() );
        compt.element()->getNeighbors( ret, cylinderOut );
        all.insert( all.end(), ret.begin(), ret.end() );
        compt.element()->getNeighbors( ret, sumRaxialOut );
        all.insert( all.end(), ret.begin(), ret.end() );
    }
    // In addition, check if the bog standard messaging applies.
    assert( cinfo->isA( "CompartmentBase" ) );
    vector< Id > ret;
    compt.element()->getNeighbors( ret, axialOut );
    all.insert( all.end(), ret.begin(), ret.end() );
    compt.element()->getNeighbors( ret, raxialOut );
    all.insert( all.end(), ret.begin(), ret.end() );
    sort( all.begin(), all.end() );
    all.erase( unique( all.begin(), all.end() ), all.end() ); //@#$%&* C++
    // Now we have a list of all compartments connected to the current one.
    return all;
}
References Element::cinfo(), Id::element(), Cinfo::find(), Cinfo::findFinfo(), Element::getNeighbors(), and Cinfo::isA().
Referenced by checkForSpine(), NeuroNode::findConnectedCompartments(), and spinyTraverse().
isPartOfDend()
bool isPartOfDend (ObjId i)
Definition at line 376 of file NeuroNode.cpp.
{
    if ( i.element()->cinfo()->isA( "CompartmentBase" ) ) {
        string name = i.element()->getName();
        if ( name.find( "shaft" ) == string::npos &&
            name.find( "neck" ) == string::npos &&
            name.find( "spine" ) == string::npos &&
            name.find( "head" ) == string::npos )
        {
            return true;
        }
    }
    return false;
}
References Element::cinfo(), ObjId::element(), Element::getName(), and Cinfo::isA().
Referenced by NeuroNode::buildSpinyTree().
reassignNodeIndices()
void reassignNodeIndices (vector< NeuroNode > & temp, const vector< unsigned int > & nodeToTempMap)
Definition at line 591 of file NeuroNode.cpp.
{
    for ( vector< NeuroNode >::iterator
            i = temp.begin(); i != temp.end(); ++i ) {
        unsigned int pa = i->parent();
        if ( pa != ~0U ) {
            assert( nodeToTempMap[ pa ] != ~0U );
            i->setParent( nodeToTempMap[ pa ] );
        }
        vector< unsigned int > kids = i->children();
        i->clearChildren();
        for ( unsigned int j = 0; j < kids.size(); ++j ) {
            unsigned int newKid = nodeToTempMap[ kids[j] ];
            if ( newKid != ~0U ) // Some may be spine shafts, no longer here
                i->addChild( newKid );
        }
    }
}
References NeuroNode::addChild(), NeuroNode::children(), NeuroNode::clearChildren(), NeuroNode::parent(), and NeuroNode::setParent().
Referenced by NeuroNode::filterSpines().
sortByShaftIds()
static void sortByShaftIds (vector< Id > & shaftId, vector< Id > & headId, vector< unsigned int > & spineParent) static
Definition at line 457 of file NeuroNode.cpp.
{
    unsigned int sortedIndex(0);
    vector<int> y(shaftId.size());
    generate(begin(y), end(y), [&]{ return sortedIndex++; });
    sort(  begin(y), end(y),
        [&](int i1, int i2) { return shaftId[i1] < shaftId[i2]; } );
    assert( sortedIndex == shaftId.size() );
    assert( sortedIndex == headId.size() );
    assert( sortedIndex == spineParent.size() );
    auto a = shaftId;
    auto b = headId;
    auto c = spineParent;
    for ( unsigned int i = 0; i < sortedIndex; ++i) {
        shaftId[i] = a[y[i]];
        headId[i] = b[y[i]];
        spineParent[i] = c[y[i]];
    }
}
References Id::operator<().
Referenced by NeuroNode::buildSpinyTree().
spinyTraverse()
static void spinyTraverse (unsigned int dendIndex, vector< Id > & dend, const unordered_map< Id, unsigned int > & dendMap, vector< int > & seen, unsigned int numSeen, vector< Id > & shaftId, vector< Id > & headId, vector< int > & dendParent, vector< unsigned int > & spineParent) static
spinyTraverse goes takes current dend entry and finds everything connected to it, recursively. Paints the 'seen' entries with the latest index for the number seen so we keep track of which subgroup the dend set belongs to. This does a depth-first recursive traverse. Looks for spines on every dend compt found.
Definition at line 429 of file NeuroNode.cpp.
{
    vector< Id > conn = findAllConnectedCompartments( dend[dendIndex] );
    seen[ dendIndex ] = numSeen;
    for ( vector< Id >::iterator i = conn.begin(); i != conn.end(); ++i ) {
        unordered_map< Id, unsigned int >::const_iterator idLookup =
                dendMap.find( *i );
        if ( idLookup != dendMap.end() ) {
            if ( !seen[ idLookup->second ] ) {
                dendParent[ idLookup->second ] = dendIndex;
                spinyTraverse( idLookup->second, dend, dendMap,
                    seen, numSeen,
                    shaftId, headId, dendParent, spineParent );
            }
        } else {
            checkForSpine( dendIndex, *i, shaftId, headId, spineParent );
        }
    }
}
References checkForSpine(), findAllConnectedCompartments(), and spinyTraverse().
Referenced by NeuroNode::buildSpinyTree(), and spinyTraverse().