MOOSE - Multiscale Object Oriented Simulation Environment: /home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/utility/numutil.h File Reference
numutil.h File Reference
#include <cmath>
#include <cfloat>
#include <limits>
#include "../randnum/RNG.h"
#include "../basecode/global.h"
Functions
bool almostEqual (double x, double y, double epsilon=DBL_EPSILON)
bool almostEqual (float x, float y, float epsilon=FLT_EPSILON)
bool almostEqual (long double x, long double y, long double epsilon=LDBL_EPSILON)
double approximateWithInteger (const double x)
double approximateWithInteger (const double x, moose::RNG &rng)
double approximateWithInteger_debug (const char *name, const double x, moose::RNG &rng)
template<class T >
bool isClose (T a, T b, T tolerance)
template<typename T >
bool isInfinity (T value)
template<class T >
bool isNaN (T value)
Function Documentation
almostEqual() [1/3]
bool almostEqual (double x, double y, double epsilon = DBL_EPSILON)
Definition at line 26 of file numutil.cpp.
{
    if (x == 0.0 && y == 0.0){
        return true;
    }
    if (fabs(x) > fabs(y)){
        return fabs((x - y) / x) < epsilon;
    } else {
        return fabs((x - y) / y) < epsilon;
    }
}
Referenced by Interpol::setXmax(), and Interpol::setXmin().
almostEqual() [2/3]
bool almostEqual (float x, float y, float epsilon = FLT_EPSILON)
Definition at line 13 of file numutil.cpp.
{
    if (x == 0.0 && y == 0.0) {
        return true;
    }
    if (fabs(x) > fabs(y)) {
        return fabs((x - y) / x) < epsilon;
    } else {
        return fabs((x - y) / y) < epsilon;
    }
}
almostEqual() [3/3]
bool almostEqual (long double x, long double y, long double epsilon = LDBL_EPSILON)
Definition at line 38 of file numutil.cpp.
{
    if (x == 0.0 && y == 0.0){
        return true;
    }
    if (std::fabs(x) > std::fabs(y)){
        return std::fabs((x - y) / x) < epsilon;
    } else {
        return std::fabs((x - y) / y) < epsilon;
    }
}
approximateWithInteger() [1/2]
double approximateWithInteger (const double x)
Definition at line 78 of file numutil.cpp.
{
    return approximateWithInteger(x, moose::rng);
}
References approximateWithInteger(), and moose::rng.
approximateWithInteger() [2/2]
double approximateWithInteger (const double x, moose::RNG & rng)
Definition at line 62 of file numutil.cpp.
{
#if 0
    return std::round(x);
#else
    assert(x >= 0.0);
    double xf = std::floor(x);
    double base = x - xf;
    if( base == 0.0)
        return x;
    if( rng.uniform() < base)
        return xf+1.0;
    return xf;
#endif
}
References moose::RNG::uniform().
Referenced by approximateWithInteger(), approximateWithInteger_debug(), Gsolve::process(), GssaVoxelPools::reinit(), and GssaVoxelPools::xferIn().
approximateWithInteger_debug()
double approximateWithInteger_debug (const char * name, const double x, moose::RNG & rng)
Definition at line 50 of file numutil.cpp.
{
    static size_t n = 0;
    n += 1;
    cerr << name << ' ' << ':' << x;
    auto y = approximateWithInteger(x, rng);
    cout << ' ' << y << ", ";
    if( std::fmod(n, 4) == 0)
        cerr << endl;
    return y;
}
References approximateWithInteger().
isClose()
template<class T > bool isClose (T a, T b, T tolerance)
Check 2 floating-point numbers for "equality". Algorithm (from Knuth) 'a' and 'b' are close if: | (a - b) / a | < e AND | (a - b) / b | < e where 'e' is a small number.
In this function, 'e' is computed as: e = tolerance * machine-epsilon
Definition at line 44 of file numutil.h.
{
    T epsilon = std::numeric_limits< T >::epsilon();
    if ( a == b )
        return true;
    if ( a == 0 || b == 0 )
        return ( fabs( a - b ) < tolerance * epsilon );
    return (
            fabs( ( a - b ) / a ) < tolerance * epsilon
            &&
            fabs( ( a - b ) / b ) < tolerance * epsilon
           );
}
isInfinity()
template<typename T > bool isInfinity (T value)
Definition at line 29 of file numutil.h.
{
    return value == std::numeric_limits< T >::infinity();
}
isNaN()
template<class T > bool isNaN (T value)
Functions for floating point comparisons
Definition at line 23 of file numutil.h.
{
    return value != value;
}