MOOSE - Multiscale Object Oriented Simulation Environment: /home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/kinetics/PoolBase.cpp File Reference
PoolBase.cpp File Reference
#include "../basecode/header.h"
#include "../basecode/ElementValueFinfo.h"
#include "../ksolve/VoxelPoolsBase.h"
#include "../ksolve/VoxelPools.h"
#include "../ksolve/KsolveBase.h"
#include "../ksolve/Ksolve.h"
#include "lookupVolumeFromMesh.h"
#include "PoolBase.h"
Macros
#define EPSILON 1e-15
Variables
static const Cinfo * bufPoolCinfo = PoolBase::initBufPoolCinfo()
const SpeciesId DefaultSpeciesId = 0
static const Cinfo * poolBaseCinfo = PoolBase::initPoolBaseCinfo()
static const Cinfo * poolCinfo = PoolBase::initPoolCinfo()
Macro Definition Documentation
EPSILON
#define EPSILON 1e-15
Definition at line 19 of file PoolBase.cpp.
Variable Documentation
bufPoolCinfo
const Cinfo* bufPoolCinfo = PoolBase::initBufPoolCinfo() static
Definition at line 314 of file PoolBase.cpp.
Referenced by PoolBase::getIsBuffered(), and PoolBase::setIsBuffered().
DefaultSpeciesId
const SpeciesId DefaultSpeciesId = 0
Definition at line 21 of file PoolBase.cpp.
poolBaseCinfo
const Cinfo* poolBaseCinfo = PoolBase::initPoolBaseCinfo() static
Definition at line 312 of file PoolBase.cpp.
poolCinfo
const Cinfo* poolCinfo = PoolBase::initPoolCinfo() static
Definition at line 313 of file PoolBase.cpp.
Referenced by PoolBase::setIsBuffered().