MOOSE - Multiscale Object Oriented Simulation Environment: /home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/mpi/PostMaster.cpp File Reference
PostMaster.cpp File Reference
#include "../basecode/header.h"
#include "PostMaster.h"
#include "../shell/Shell.h"
Functions
int innerGetVec (const Eref &e, const OpFunc *op, double *getReturnBuf)
Function Documentation
innerGetVec()
int innerGetVec (const Eref & e, const OpFunc * op, double * getReturnBuf)
Collects all the values and stuffs into getReturnBuf. Returns size of all contents of getReturnBuf, in doubles. Puts number of returned values in getReturnBuf[0]. Note that these are likely to differ if the values returned are not doubles. Examines the eref to decide if this is a DataElement or a FieldElement. If a DataElement, scans through all data entries to fill the returnBuf. If a FieldElement, fills in field entries only of the one specified DataId on this eref.
Definition at line 249 of file PostMaster.cpp.
{
    static double buf[PostMaster::reserveBufSize];
    // Would like to use eref iterator here.
    Element* elm = e.element();
    unsigned int start = elm->localDataStart();
    int k = 1; // first entry is for numOnNode;
    if ( elm->hasFields() ) {
        DataId di = e.dataIndex();
        unsigned int numField = elm->numField( di - start );
        getReturnBuf[0] = numField;
        for ( unsigned int j = 0; j < numField; ++j ) {
            Eref er( elm, di, j );
            // stuff return value into buf.
            op->opBuffer( er, buf );
            unsigned int size = static_cast<unsigned int>(buf[0]);
            memcpy( &getReturnBuf[k], &buf[1], size * sizeof( double ) );
            k += size;
        }
    } else {
        unsigned int end = start + elm->numLocalData();
        getReturnBuf[0] = elm->numLocalData();
        for ( unsigned int i = start; i < end; ++i ) {
            Eref er( elm, i, 0 );
            // stuff return value into buf.
            op->opBuffer( er, buf );
            unsigned int size = static_cast<unsigned int>(buf[0]);
            memcpy( &getReturnBuf[k], &buf[1], size * sizeof( double ) );
            k += size;
        }
    }
    return k;
}
References Eref::dataIndex(), Eref::element(), Eref::Eref(), Element::hasFields(), Element::localDataStart(), Element::numField(), Element::numLocalData(), OpFunc::opBuffer(), and PostMaster::reserveBufSize.