MOOSE - Multiscale Object Oriented Simulation Environment: /home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/pymoose/PyRun.cpp File Reference
PyRun.cpp File Reference
#include "../basecode/header.h"
#include "PyRun.h"
Functions
static SrcFinfo1< double > * outputOut ()
Variables
static const Cinfo * pyRunCinfo = PyRun::initCinfo()
Function Documentation
outputOut()
static SrcFinfo1< double > * outputOut () static
Definition at line 16 of file PyRun.cpp.
{
    static SrcFinfo1<double> outputOut(
        "output",
        "Sends out the value of local variable called `output`. Thus, you can"
        " have Python statements which compute some value and assign it to the"
        " variable called `output` (which is defined at `reinit` call). This"
        " will be sent out to any target connected to the `output` field.");
    return &outputOut;
}
Referenced by PyRun::initCinfo(), PyRun::process(), PyRun::run(), and PyRun::trigger().
Variable Documentation
pyRunCinfo
const Cinfo* pyRunCinfo = PyRun::initCinfo() static
Definition at line 119 of file PyRun.cpp.