MOOSE - Multiscale Object Oriented Simulation Environment: /home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/kinetics/Reac.cpp File Reference
Reac.cpp File Reference
#include "../basecode/header.h"
#include "../ksolve/RateTerm.h"
#include "../basecode/SparseMatrix.h"
#include "../ksolve/KinSparseMatrix.h"
#include "../ksolve/Stoich.h"
#include "../basecode/ElementValueFinfo.h"
#include "lookupVolumeFromMesh.h"
#include "Reac.h"
Macros
#define EPSILON 1e-15
Functions
static SrcFinfo2< double, double > * prdOut ()
static SrcFinfo2< double, double > * subOut ()
Variables
static const Cinfo * reacCinfo = Reac::initCinfo()
Macro Definition Documentation
EPSILON
#define EPSILON 1e-15
Definition at line 28 of file Reac.cpp.
Function Documentation
prdOut()
static SrcFinfo2< double, double > * prdOut () static
Definition at line 38 of file Reac.cpp.
{
    static SrcFinfo2< double, double > prdOut(
            "prdOut",
            "Sends out increment of molecules on product each timestep"
            );
    return &prdOut;
}
References SrcFinfo2< T1, T2 >::SrcFinfo2().
Referenced by Reac::getNumKb(), Reac::getNumPrd(), Reac::initCinfo(), Reac::setNumKb(), and Reac::setSolver().
subOut()
static SrcFinfo2< double, double > * subOut () static
Definition at line 30 of file Reac.cpp.
{
    static SrcFinfo2< double, double > subOut(
            "subOut",
            "Sends out increment of molecules on product each timestep"
            );
    return &subOut;
}
References SrcFinfo2< T1, T2 >::SrcFinfo2().
Referenced by Reac::getNumKf(), Reac::getNumSub(), Reac::initCinfo(), Reac::setNumKf(), and Reac::setSolver().
Variable Documentation
reacCinfo
const Cinfo* reacCinfo = Reac::initCinfo() static
Definition at line 184 of file Reac.cpp.