MOOSE - Multiscale Object Oriented Simulation Environment: /home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/kinetics/ReadKkit.cpp File Reference
ReadKkit.cpp File Reference
#include <iomanip>
#include <fstream>
#include "../basecode/header.h"
#include "Reac.h"
#include "EnzBase.h"
#include "lookupVolumeFromMesh.h"
#include "../shell/Shell.h"
#include "../shell/Wildcard.h"
#include "../utility/strutil.h"
#include "ReadKkit.h"
Enumerations
enum GenesisTableModes {
TAB_IO , TAB_LOOP , TAB_ONCE , TAB_BUF ,
TAB_SPIKE , TAB_FIELDS , TAB_DELAY
}
Functions
void assignArgs (map< string, int > &argConv, const vector< string > &args)
unsigned int chopLine (const string &line, vector< string > &ret)
Id findMeshOfEnz (Id enz)
Id findParentComptOfReac (Id reac)
vector< unsigned int > findVolOrder (const vector< double > &vols)
bool kineticsHasReactions (Id mgr)
string lower (const string &input)
void makeSolverOnCompt (Shell *s, const vector< ObjId > &compts, bool isGsolve)
Id makeStandardElements (Id pa, const string &modelname)
static void positionCompt (ObjId compt, double side, bool shiftUp)
void setMethod (Shell *s, Id mgr, double simdt, double plotdt, const string &method)
bool volCompare (const pair< unsigned int, double > &A, const pair< unsigned int, double > &B)
Variables
static const double KKIT_NA = 6.0e23
Enumeration Type Documentation
GenesisTableModes
enum GenesisTableModes
Enumerator
TAB_IO
TAB_LOOP
TAB_ONCE
TAB_BUF
TAB_SPIKE
TAB_FIELDS
TAB_DELAY
Definition at line 1400 of file ReadKkit.cpp.
                       {TAB_IO, TAB_LOOP, TAB_ONCE, TAB_BUF, TAB_SPIKE,
                        TAB_FIELDS, TAB_DELAY
                       };
Function Documentation
assignArgs()
void assignArgs (map< string, int > & argConv, const vector< string > & args)
Definition at line 693 of file ReadKkit.cpp.
{
    for ( unsigned int i = 2; i != args.size(); ++i )
        argConv[ args[i] ] = i + 2;
}
Referenced by ReadKkit::objdump().
chopLine()
unsigned int chopLine (const string & line, vector< string > & ret)
Definition at line 30 of file ReadKkit.cpp.
{
    ret.resize( 0 );
    stringstream ss( line );
    string arg;
    while ( ss >> arg )
    {
        ret.push_back( moose::trim(arg, "\"") );
    }
    return ret.size();
}
References moose::trim().
Referenced by ReadKkit::readData(), and ReadKkit::readInit().
findMeshOfEnz()
Id findMeshOfEnz (Id enz)
Return the MeshEntry into which the enzyme should be placed. This is simple: Just identify the compartment holding the enzyme molecule.
Definition at line 964 of file ReadKkit.cpp.
{
    static const Finfo* enzFinfo =
        EnzBase::initCinfo()->findFinfo( "enzOut" );
    assert( enzFinfo );
    vector< Id > enzVec;
    enz.element()->getNeighbors( enzVec, enzFinfo );
    assert( enzVec.size() == 1 );
    vector< Id > meshEntries;
    return getCompt( enzVec[0] );
}
References Id::element(), Cinfo::findFinfo(), getCompt(), Element::getNeighbors(), and EnzBase::initCinfo().
findParentComptOfReac()
Id findParentComptOfReac (Id reac)
Definition at line 923 of file ReadKkit.cpp.
{
    static const Finfo* subFinfo =
        Reac::initCinfo()->findFinfo( "subOut" );
    assert( subFinfo );
    vector< Id > subVec;
    reac.element()->getNeighbors( subVec, subFinfo );
    if ( subVec.size() == 0 ) // Dangling reaction
        return Id();
    // For now just put the reac in the compt belonging to the
    // first substrate
    return getCompt( subVec[0] );
}
References Id::element(), Cinfo::findFinfo(), getCompt(), Element::getNeighbors(), Id::Id(), and Reac::initCinfo().
Referenced by ReadKkit::assignReacCompartments().
findVolOrder()
vector< unsigned int > findVolOrder (const vector< double > & vols)
Definition at line 862 of file ReadKkit.cpp.
{
    vector< pair< unsigned int, double > > p( vols.size() );
    for ( unsigned int i = 0; i < vols.size(); ++i )
    {
        p[i].first = i;
        p[i].second = vols[i];
    }
    sort( p.begin(), p.end(), volCompare );
    vector< unsigned int > ret( vols.size() );
    for ( unsigned int i = 0; i < vols.size(); ++i )
    {
        ret[ vols.size() -i -1 ] = p[i].first;
    }
    return ret;
}
References volCompare().
Referenced by ReadKkit::assignPoolCompartments(), and testVolSort().
kineticsHasReactions()
bool kineticsHasReactions (Id mgr)
Definition at line 279 of file ReadKkit.cpp.
{
    static const string choices[] = { "Pool", "PoolBase", "Reac", "Enz", "MMEnz", "Neutral" };
    Id kinId = Neutral::child( mgr.eref(), "kinetics" );
    assert( kinId != Id() );
    vector< Id > kids;
    Neutral::children( kinId.eref(), kids );
    for( vector< Id >::iterator k = kids.begin(); k != kids.end(); ++k ) {
        string childClass = Field< string >::get( *k, "className" );
        auto const last = std::end( choices );
        auto const pos = std::find( std::begin(choices), std::end(choices), childClass );
        // cout << k->path() << "   " << childClass << endl;
        if ( pos!= last)
            return true;
    }
    return false;
}
References Neutral::child(), Neutral::children(), Id::eref(), Field< A >::get(), Id::Id(), and Id::operator!=().
Referenced by ReadKkit::read().
lower()
string lower (const string & input)
Definition at line 42 of file ReadKkit.cpp.
{
    string ret = input;
    for ( unsigned int i = 0; i < input.length(); ++i )
        ret[i] = tolower( ret[i] );
    return ret;
}
Referenced by setMethod().
makeSolverOnCompt()
void makeSolverOnCompt (Shell * s, const vector< ObjId > & compts, bool isGsolve)
Definition at line 170 of file ReadKkit.cpp.
{
    if ( compts.size() > 3 )
    {
        cout << "Warning: ReadKkit::makeSolverOnCompt: Cannot handle " <<
             compts.size() << " chemical compartments\n";
        return;
    }
    vector< Id > stoichVec;
    /*
    if ( compts.size() == 2 ) {
        double side = Field< double >::get( compts[1], "dy" );
        positionCompt( compts[0], side, true );
    }
    if ( compts.size() == 3 ) {
        double side = Field< double >::get( compts[1], "dy" );
        positionCompt( compts[0], side, true );
        positionCompt( compts[2], side, false );
    }
    */
    /*
    for ( vector< ObjId >::const_iterator
                    i = compts.begin(); i != compts.end(); ++i ) {
        string simpath = i->path() + "/##";
        Id ksolve;
        if ( isGsolve )
            ksolve = s->doCreate( "Gsolve", *i, "gsolve", 1 );
        else
            ksolve = s->doCreate( "Ksolve", *i, "ksolve", 1 );
        dsolve = s->doCreate("Dsolve,")
        Id stoich = s->doCreate( "Stoich", *i, "stoich", 1 );
        stoichVec.push_back( stoich );
        Field< Id >::set( stoich, "compartment", *i );
        Field< Id >::set( stoich, "ksolve", ksolve );
        Field< string >::set( stoich, "path", simpath );
    }
    */
    /* Not needed now that we use xfer pools to cross compartments.
    if ( stoichVec.size() == 2 ) {
        SetGet1< Id >::set( stoichVec[1], "buildXreacs", stoichVec[0] );
    }
    if ( stoichVec.size() == 3 ) {
        SetGet1< Id >::set( stoichVec[1], "buildXreacs", stoichVec[0] );
        SetGet1< Id >::set( stoichVec[1], "buildXreacs", stoichVec[2] );
    }
    for ( vector< Id >::iterator
                    i = stoichVec.begin(); i != stoichVec.end(); ++i ) {
        SetGet0::set( *i, "filterXreacs" );
    }
    */
}
makeStandardElements()
Id makeStandardElements (Id pa, const string & modelname)
Definition at line 123 of file ReadKkit.cpp.
{
    Shell* shell = reinterpret_cast< Shell* >( Id().eref().data() );
    string modelPath = pa.path() + "/" + modelname;
    if ( pa == Id() )
        modelPath = "/" + modelname;
    Id mgr( modelPath );
    if ( mgr == Id() )
        mgr = shell->doCreate( "Neutral", pa, modelname, 1, MooseGlobal );
    Id kinetics( modelPath + "/kinetics" );
    if ( kinetics == Id() )
    {
        kinetics = shell->doCreate( "CubeMesh", mgr, "kinetics", 1,  MooseGlobal );
        SetGet2< double, unsigned int >::set( kinetics, "buildDefaultMesh", 1e-15, 1 );
        Id cInfo = shell->doCreate( "Annotator", kinetics, "info", 1 );
        assert( cInfo != Id() );
    }
    assert( kinetics != Id() );
    Id graphs = shell->doCreate( "Neutral", mgr, "graphs", 1, MooseGlobal);
    assert( graphs != Id() );
    Id moregraphs = shell->doCreate( "Neutral", mgr, "moregraphs", 1, MooseGlobal );
    Id geometry = shell->doCreate( "Neutral", mgr, "geometry", 1, MooseGlobal );
    assert( geometry != Id() );
    Id groups = shell->doCreate( "Neutral", mgr, "groups", 1, MooseGlobal );
    assert( groups != Id() );
    return mgr;
}
References Eref::data(), Shell::doCreate(), Id::eref(), Id::Id(), Id::Id(), MooseGlobal, Id::operator!=(), Id::operator==(), Id::path(), and SetGet2< A1, A2 >::set().
Referenced by ReadKkit::read(), and ReadCspace::readModelString().
positionCompt()
static void positionCompt (ObjId compt, double side, bool shiftUp) static
Definition at line 154 of file ReadKkit.cpp.
{
    double y0 = Field< double >::get( compt, "y0" );
    double y1 = Field< double >::get( compt, "y1" );
    if ( shiftUp )
    {
        Field< double >::set( compt, "y0", y0 + side );
        Field< double >::set( compt, "y1", y1 + side );
    }
    else
    {
        Field< double >::set( compt, "y0", y0 - y1 );
        Field< double >::set( compt, "y1", 0 );
    }
}
References Field< A >::get(), and Field< A >::set().
setMethod()
void setMethod (Shell * s, Id mgr, double simdt, double plotdt, const string & method)
Definition at line 223 of file ReadKkit.cpp.
{
    vector< ObjId > ret;
    simpleWildcardFind( mgr.path() + "/#[ISA=ChemCompt]", ret );
    if ( ret.size() == 0 ) { // We may have converted /kinetics to a group
        simpleWildcardFind( mgr.path() + "/#/#[ISA=ChemCompt]", ret );
    }
    assert( ret.size() > 0 );
    Id compt( mgr.path() + "/kinetics" );
    assert( compt != Id() );
    string simpath2 = mgr.path() + "/##[ISA=StimulusTable]," +
                      mgr.path() + "/##[ISA=PulseGen]";
    string m = lower( method );
    /*
    if ( m == "ksolve" || m =="gsl" ||  m == "gssa" || m == "gsolve" ||
        m == "gillespie" || m == "stochastic" )
    {
        cout << " Warning:  Default solver set is Exponential Euler. To set  \'gsl\' or \'gssa\' solver use function mooseaddChemSolver(modelpath,\'solverType\')"<<"\n";
    }
    if ( m == "rk4" ) {
        cout << "Warning, not yet implemented. Using rk5 instead\n";
        m = "rk5";
    }
    if ( m == "ksolve" || m == "gsl" ||
        m == "rk5" || m == "rkf" || m == "rk" ) {
            makeSolverOnCompt( s, mgr, ret, false );
    } else if ( m == "gssa" || m == "gsolve" ||
        m == "gillespie" || m == "stochastic" ) {
            makeSolverOnCompt( s, mgr,ret, true );
    } else if ( m == "ee" || m == "neutral" ) {
            // s->doUseClock( simpath, "process", 4 );
            // s->doSetClock( 4, simdt );
    } else {
            cout << "ReadKkit::setMethod: option " << method <<
                    " not known, using Exponential Euler (ee)\n";
            // s->doUseClock( simpath, "process", 4 );
            // s->doSetClock( 4, simdt );
    }
    */
    s->doUseClock( simpath2, "proc", 11 );
    s->doSetClock( 10, simdt );
    s->doSetClock( 11, simdt );
    s->doSetClock( 12, simdt );
    s->doSetClock( 13, simdt );
    s->doSetClock( 14, simdt );
    s->doSetClock( 15, plotdt );    // Gsolve and Ksolve
    s->doSetClock( 16, plotdt );    // Gsolve and Ksolve
    s->doSetClock( 17, plotdt );    // Stats objects
    s->doSetClock( 18, plotdt );    // Table2 objects.
}
References Shell::doSetClock(), Shell::doUseClock(), Id::Id(), Id::Id(), lower(), Id::operator!=(), Id::path(), and simpleWildcardFind().
Referenced by ReadKkit::read().
volCompare()
bool volCompare (const pair< unsigned int, double > & A, const pair< unsigned int, double > & B)
Definition at line 854 of file ReadKkit.cpp.
{
    return A.second < B.second;
}
Referenced by findVolOrder().
Variable Documentation
KKIT_NA
const double KKIT_NA = 6.0e23 static
Definition at line 28 of file ReadKkit.cpp.
Referenced by ReadKkit::buildEnz(), ReadKkit::buildPool(), ReadKkit::convertEnzRatesToConcUnits(), ReadKkit::convertMMenzRatesToConcUnits(), ReadKkit::convertPoolAmountToConcUnits(), and ReadKkit::convertReacRatesToConcUnits().