MOOSE - Multiscale Object Oriented Simulation Environment: /home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/biophysics/ReadSwc.cpp File Reference
ReadSwc.cpp File Reference
#include "../basecode/header.h"
#include "../shell/Shell.h"
#include "../utility/Vec.h"
#include "SwcSegment.h"
#include "ReadSwc.h"
#include "CompartmentBase.h"
#include "Compartment.h"
#include "SymCompartment.h"
#include <fstream>
#include <iomanip>
Functions
bool isWhitespaceOnly (const std::string &s)
static Id makeCompt (Id parent, const string &__name, const SwcSegment &seg, const SwcSegment &pa, double RM, double RA, double CM)
Variables
static const double MinRadius = 0.04
Function Documentation
isWhitespaceOnly()
bool isWhitespaceOnly (const std::string & s)
Definition at line 25 of file ReadSwc.cpp.
{
    if (s.empty()) {
        return true;
    }
    for (char c : s) {
        if (!std::isspace(static_cast<unsigned char>(c))) {
            return false;  // Found a non-whitespace character
        }
    }
    return true;  // All characters were whitespace
}
Referenced by ReadSwc::ReadSwc().
makeCompt()
static Id makeCompt (Id parent, const string & __name, const SwcSegment & seg, const SwcSegment & pa, double RM, double RA, double CM) static
Definition at line 326 of file ReadSwc.cpp.
{
    Shell* shell = reinterpret_cast<Shell*>(Id().eref().data());
    double len = seg.radius() * 2.0;
    Id compt;
    double x0, y0, z0;
    if (seg.parent() != ~0U) {
        len = seg.distance(pa);
        x0 = pa.vec().a0();
        y0 = pa.vec().a1();
        z0 = pa.vec().a2();
    }
    else {
        x0 = seg.vec().a0() - len;
        y0 = seg.vec().a1();
        z0 = seg.vec().a2();
    }
    assert(len > 0.0);
    compt = shell->doCreate("Compartment", parent, __name, 1);
    Eref er = compt.eref();
    moose::CompartmentBase* cptr =
        reinterpret_cast<moose::CompartmentBase*>(compt.eref().data());
    double xa = seg.radius() * seg.radius() * PI * 1e-12;
    len *= 1e-6;
    double dia = seg.radius() * 2.0e-6;
    cptr->setRm(er, RM / (len * dia * PI));
    cptr->setRa(er, RA * len / xa);
    cptr->setCm(er, CM * (len * dia * PI));
    cptr->setDiameter(dia);
    cptr->setLength(len);
    cptr->setX0(x0 * 1e-6);
    cptr->setY0(y0 * 1e-6);
    cptr->setZ0(z0 * 1e-6);
    cptr->setX(seg.vec().a0() * 1e-6);
    cptr->setY(seg.vec().a1() * 1e-6);
    cptr->setZ(seg.vec().a2() * 1e-6);
    return compt;
}
References Vec::a0(), Vec::a1(), Vec::a2(), Eref::data(), SwcSegment::distance(), Shell::doCreate(), Id::eref(), Id::Id(), SwcSegment::parent(), PI, SwcSegment::radius(), moose::CompartmentBase::setCm(), moose::CompartmentBase::setDiameter(), moose::CompartmentBase::setLength(), moose::CompartmentBase::setRa(), moose::CompartmentBase::setRm(), moose::CompartmentBase::setX(), moose::CompartmentBase::setX0(), moose::CompartmentBase::setY(), moose::CompartmentBase::setY0(), moose::CompartmentBase::setZ(), moose::CompartmentBase::setZ0(), and SwcSegment::vec().
Referenced by ReadSwc::build().
Variable Documentation
MinRadius
const double MinRadius = 0.04 static
Definition at line 23 of file ReadSwc.cpp.
Referenced by ReadSwc::validate().