MOOSE - Multiscale Object Oriented Simulation Environment: /home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/biophysics/ReadCell.cpp File Reference
ReadCell.cpp File Reference
#include "../basecode/header.h"
#include "../shell/Shell.h"
#include "ReadCell.h"
#include "../utility/strutil.h"
#include "CompartmentBase.h"
#include "Compartment.h"
#include "SymCompartment.h"
#include <fstream>
Functions
double calcSurf (double, double)
Function Documentation
calcSurf()
double calcSurf (double len, double dia)
Definition at line 617 of file ReadCell.cpp.
{
    double area = 0.0;
    if ( len == 0.0 ) // Spherical. Safe to compare with 0.0.
        area = dia * dia * M_PI;
    else
        area = len * dia * M_PI;
    return area;
}
Referenced by ReadCell::addCanonicalChannel(), ReadCell::buildChannels(), and ReadCell::buildCompartment().