MOOSE - Multiscale Object Oriented Simulation Environment: /home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/shell/SaveModels.cpp File Reference
SaveModels.cpp File Reference
#include <fstream>
#include "../basecode/header.h"
#include "Shell.h"
Functions
void writeCspace (Id model, const string &fname)
void writeKkit (Id model, const string &fname)
Function Documentation
writeCspace()
void writeCspace (Id model, const string & fname) extern
writeKkit()
void writeKkit (Id model, const string & fname) extern
Definition at line 523 of file WriteKkit.cpp.
{
    ofstream fout( fname.c_str(), ios::out );
    vector< ObjId > chemCompt;
    vector< string > msgs;
    double simDt;
    double plotDt;
    double runTime = estimateSimTimes( simDt, plotDt );
    double defaultVol = estimateDefaultVol( model );
    writeHeader( fout, simDt, plotDt, runTime, defaultVol );
    string bg = "cyan";
    string fg = "black";
    double x = 0;
    double y = 0;
    map < double, pair<Id, int> > compt_vol;
    unsigned int num = wildcardFind( model.path() + "/##[ISA=ChemCompt]", chemCompt );
    if ( num == 0 )
    {
        cout << "Warning: writeKkit:: No model found on " << model <<
             endl;
        return;
    }
    for ( vector< ObjId >::iterator itr = chemCompt.begin(); itr != chemCompt.end(); itr++)
    {
        vector < unsigned int>dims;
        unsigned int dims_size;
        dims_size = 1;
        unsigned index = 0;
        string comptPath = Field<string>::get(*itr,"path");
        string comptname = Field<string>::get(*itr,"name");
        if (comptname != "kinetics")
        {
            fout << "simundump group /kinetics/" << comptname << " 0 " <<
                 "blue" << " " << "green"    << " x 0 0 \"\" defaultfile \\\n";
            fout << "  defaultfile.g 0 0 0 " << rand() % 10 + 1 << " " << rand() % 10 + 1 << " 0\n";
        }
        double size = Field<double>::get(ObjId(*itr,index),"Volume");
        unsigned int ndim = Field<unsigned int>::get(ObjId(*itr,index),"NumDimensions");
        ostringstream geometry;
        int vecIndex = itr-chemCompt.begin();
        if (vecIndex > 0)
            geometry << "simundump geometry /kinetics" <<  "/geometry[" << vecIndex <<"] 0 " << size << " " << ndim << " sphere " <<" \"\" white black 0 0 0\n";
        else
            geometry << "simundump geometry /kinetics"  <<  "/geometry 0 " << size << " " << ndim << " sphere " <<" \"\" white black 0 0 0\n";
        fout << geometry.str();
        compt_vol.insert(make_pair(size,make_pair(*itr,vecIndex)));
    } // compartmentclose
    writeGroup(fout, model);
    map<double, pair<Id, int> >::iterator compt;
    for (compt = compt_vol.begin(); compt != compt_vol.end(); compt++)
    {
        string comptPath = Field<string>::get(compt->second.first,"path");
        //  Species
        vector< ObjId > Compt_spe;
        wildcardFind(comptPath+"/##[ISA=PoolBase]",Compt_spe);
        int species_size = 1;
        string objname;
        for (vector <ObjId> :: iterator itrp = Compt_spe.begin(); itrp != Compt_spe.end(); itrp++)
        {
            string path = Field <string> :: get (*itrp,"path");
            Id enzPoolparent = Field <ObjId>  :: get(*itrp,"parent");
            string enzpoolClass = Field <string> :: get(enzPoolparent,"className");
            if (enzpoolClass != "ZombieEnz" || enzpoolClass != "Enz")
            {
                Id annotaId( path+"/info");
                if ( annotaId != Id() )
                {
                    double x = Field <double> :: get(annotaId,"x");
                    double y = Field <double> :: get(annotaId,"y");
                    string fg = Field <string> :: get(annotaId,"textColor");
                    string bg = Field <string> :: get(annotaId,"color");
                    writePool(fout, *itrp,bg,fg,x,y,compt->second.first,compt->second.second);
                }
            }
        } //species is closed
        vector< ObjId > Compt_Func;
        wildcardFind(comptPath+"/##[ISA=Function]",Compt_Func);
        for (vector <ObjId> :: iterator itrF= Compt_Func.begin(); itrF != Compt_Func.end(); itrF++)
        {
            storeFunctionMsgs( *itrF, msgs,compt_vol);
        }
        // Reaction
        vector< ObjId > Compt_Reac;
        wildcardFind(comptPath+"/##[ISA=Reac]",Compt_Reac);
        for (vector <ObjId> :: iterator itrR= Compt_Reac.begin(); itrR != Compt_Reac.end(); itrR++)
        {
            string path = Field<string> :: get(*itrR,"path");
            Id annotaId( path+"/info");
            string noteClass = Field<string> :: get(annotaId,"className");
            string notes;
            double x = Field <double> :: get(annotaId,"x");
            double y = Field <double> :: get(annotaId,"y");
            string fg = Field <string> :: get(annotaId,"textColor");
            string bg = Field <string> :: get(annotaId,"color");
            writeReac( fout, *itrR, bg, fg, x, y, compt->second.first);
            storeReacMsgs( *itrR, msgs, compt->second.first );
        }// reaction
        vector< ObjId > Compt_Enz;
        wildcardFind(comptPath+"/##[ISA=EnzBase]",Compt_Enz);
        for (vector <ObjId> :: iterator itrE= Compt_Enz.begin(); itrE != Compt_Enz.end(); itrE++)
        {
            string path = Field<string> :: get(*itrE,"path");
            Id annotaId( path+"/info");
            string noteClass = Field<string> :: get(annotaId,"className");
            string notes;
            double x = Field <double> :: get(annotaId,"x");
            double y = Field <double> :: get(annotaId,"y");
            string fg = Field <string> :: get(annotaId,"textColor");
            string bg = Field <string> :: get(annotaId,"color");
            writeEnz( fout, *itrE, bg, fg, x, y, compt->second.first);
            storeEnzMsgs( *itrE, msgs, compt->second.first);
        }// reaction
    } //compatment loop
    writeGui ( fout);
    /* Table */
    vector< ObjId > table;
    wildcardFind(model.path()+"/##[ISA=Table2]",table);
    for (vector <ObjId> :: iterator itrT= table.begin(); itrT != table.end(); itrT++)
    {
        string tabPath = Field <string> :: get(*itrT,"path");
        vector < Id > tabSrc = LookupField <string,vector < Id> >::get(*itrT, "neighbors","requestOut");
        for (vector <Id> :: iterator tabItem= tabSrc.begin(); tabItem != tabSrc.end(); tabItem++)
        {
            string path = Field <string> :: get(*tabItem,"path");
            double vol = Field < double> :: get (*tabItem,"Volume");
            //Trying to find the compartment name via volume
            //otherwise if we go via parent, sometimes it might
            // get groupname so maped compartment Id and volume
            Id parentId = compt_vol[vol].first;
            string parentname = Field <string> :: get(parentId,"name");
            Id annotaId(path+"/info");
            double x = Field <double> :: get(annotaId,"x");
            double y = Field <double> :: get(annotaId,"y");
            string bg = Field <string> :: get(annotaId,"textColor");
            string fg = Field <string> :: get(annotaId,"color");
            writePlot( fout, *itrT, bg, fg, x, y );
            storePlotMsgs( *itrT, msgs,*tabItem,fg, parentId);
        }
    }// table
    writeMsgs( fout, msgs );
    writeFooter( fout );
}
References estimateDefaultVol(), estimateSimTimes(), Field< A >::get(), LookupField< L, A >::get(), Id::Id(), Id::Id(), ObjId::ObjId(), Id::operator!=(), Id::path(), storeEnzMsgs(), storeFunctionMsgs(), storePlotMsgs(), storeReacMsgs(), wildcardFind(), writeEnz(), writeFooter(), writeGroup(), writeGui(), writeHeader(), writeMsgs(), writePlot(), writePool(), and writeReac().
Referenced by Shell::doSaveModel(), and testWriteKkit().