MOOSE - Multiscale Object Oriented Simulation Environment: /home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/basecode/SetGet.h File Reference
SetGet.h File Reference
#include <typeinfo>
Classes
class Field< A >
class LookupField< L, A >
class SetGet
class SetGet0
class SetGet1< A >
class SetGet2< A1, A2 >
class SetGet3< A1, A2, A3 >
class SetGet4< A1, A2, A3, A4 >
class SetGet5< A1, A2, A3, A4, A5 >
class SetGet6< A1, A2, A3, A4, A5, A6 >
Functions
template<class T , class A >
A localGet (const Eref &er, string field)
Function Documentation
localGet()
template<class T , class A > A localGet (const Eref & er, string field)
Similar to Field< A >::fastGet(), except that an existing Msg is not needed.
Instant-return call for a single value. Bypasses all the queueing stuff. It is hardcoded so type safety will have to be coded in too: the dynamic_cast will catch it only at runtime.
Perhaps analogous localSet(), localLookupGet(), localGetVec(), etc. should also be added.
Also, will be nice to change this to Field< A >::localGet() to make things more uniform.
Definition at line 36 of file SetGet.h.
{
    string fullFieldName = "get" + field;
    fullFieldName[3] = std::toupper( fullFieldName[3] );
    const Finfo* finfo = er.element()->cinfo()->findFinfo( fullFieldName );
    assert( finfo );
    const DestFinfo* dest = dynamic_cast< const DestFinfo* >( finfo );
    assert( dest );
    const OpFunc* op = dest->getOpFunc();
    assert( op );
    const GetOpFunc< T, A >* gop =
        dynamic_cast< const GetOpFunc< T, A >* >( op );
    assert( gop );
    return gop->reduceOp( er );
}
References Element::cinfo(), Eref::element(), Cinfo::findFinfo(), and DestFinfo::getOpFunc().