MOOSE - Multiscale Object Oriented Simulation Environment: /home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/shell/ShellCopy.cpp File Reference
ShellCopy.cpp File Reference
#include "../basecode/header.h"
#include "../msg/OneToAllMsg.h"
#include "Shell.h"
#include "../scheduling/Clock.h"
Functions
Element * innerCopyElements (Id orig, ObjId newParent, Id newId, unsigned int n, bool toGlobal, map< Id, Id > &tree)
void innerCopyMsgs (map< Id, Id > &tree, unsigned int n, bool copyExtMsgs)
Function Documentation
innerCopyElements()
Element * innerCopyElements (Id orig, ObjId newParent, Id newId, unsigned int n, bool toGlobal, map< Id, Id > & tree)
Runs in parallel on all nodes. Note that 'n' is the number of complete duplicates. If there were 10 dataEntries in the original, there will now be 10 x n.
Definition at line 63 of file ShellCopy.cpp.
{
    // Element* e = new Element( newId, orig.element(), n, toGlobal );
    unsigned int newNumData = orig.element()->numData() * n;
    Element* e =
        orig.element()->copyElement(newParent, newId, newNumData, toGlobal);
    assert(e);
    Shell::adopt(newParent, newId, 0);
    e->setTick(Clock::lookupDefaultTick(e->cinfo()->name()));
    SetGet1< ObjId >::set( newId, "notifyCopy", orig );
    // cout << Shell::myNode() << ": Copy: orig= " << orig << ", newParent = "
    // << newParent << ", newId = " << newId << endl;
    tree[orig] = e->id();
    // cout << Shell::myNode() << ": ice, pa = " << newParent << ", pair= (" <<
    // orig << "," << e->id() << ")\n";
    vector<Id> kids;
    Neutral::children(orig.eref(), kids);
    for (vector<Id>::iterator i = kids.begin(); i != kids.end(); ++i) {
        // Needed in case parent is not on zero dataIndex.
        ObjId pa = Neutral::parent(*i);
        ObjId newParent(e->id(), pa.dataIndex);
        innerCopyElements(*i, newParent, Id::nextId(), n, toGlobal, tree);
    }
    return e;
}
References Shell::adopt(), Neutral::children(), Element::cinfo(), Element::copyElement(), ObjId::dataIndex, Id::element(), Id::eref(), Element::id(), innerCopyElements(), Clock::lookupDefaultTick(), Cinfo::name(), Id::nextId(), Element::numData(), ObjId::ObjId(), Neutral::parent(), SetGet1< A >::set(), and Element::setTick().
Referenced by Shell::innerCopy(), and innerCopyElements().
innerCopyMsgs()
void innerCopyMsgs (map< Id, Id > & tree, unsigned int n, bool copyExtMsgs)
Definition at line 93 of file ShellCopy.cpp.
{
    static const Finfo* cf = Neutral::initCinfo()->findFinfo("childOut");
    static const SrcFinfo1<int>* cf2 = dynamic_cast<const SrcFinfo1<int>*>(cf);
    assert(cf);
    assert(cf2);
    /*
    cout << endl << Shell::myNode() << ": innerCopyMsg ";
    for ( map< Id, Id >::const_iterator i = tree.begin();
            i != tree.end(); ++i ) {
            cout << " (" << i->first << "," << i->second << ") ";
    }
    cout << endl;
    */
    for (map<Id, Id>::const_iterator i = tree.begin(); i != tree.end(); ++i) {
        Element* e = i->first.element();
        unsigned int j = 0;
        const vector<MsgFuncBinding>* b = e->getMsgAndFunc(j);
        while (b) {
            if (j != cf2->getBindIndex()) {
                for (vector<MsgFuncBinding>::const_iterator k = b->begin();
                     k != b->end(); ++k) {
                    ObjId mid = k->mid;
                    const Msg* m = Msg::getMsg(mid);
                    assert(m);
                    /*
                    cout << endl << Shell::myNode() << ": innerCopyMsg orig = ("
                    <<
                            e->id() << ", " << e->getName() << "), e1 = (" <<
                            m->e1()->id() << ", " << m->e1()->getName() << "),
                    e2 = (" <<
                            m->e2()->id() << ", " << m->e2()->getName() << "),
                    fid = " <<
                            k->fid << ", mid = " << k->mid << endl;
                            */
                    map<Id, Id>::const_iterator tgt;
                    if (m->e1() == e) {
                        tgt = tree.find(m->e2()->id());
                    } else if (m->e2() == e) {
                        tgt = tree.find(m->e1()->id());
                    } else {
                        assert(0);
                    }
                    if (tgt != tree.end()) {
                        m->copy(e->id(), i->second, tgt->second, k->fid, j, n);
                        SetGet1< ObjId >::set( i->second, "notifyAddMsgSrc", m->mid() );
                        SetGet1< ObjId >::set( tgt->second, "notifyAddMsgDest", m->mid() );
                    }
                }
            }
            b = e->getMsgAndFunc(++j);
        }
    }
}
References Msg::copy(), Msg::e1(), Msg::e2(), Id::element(), MsgFuncBinding::fid, Cinfo::findFinfo(), SrcFinfo::getBindIndex(), Msg::getMsg(), Element::getMsgAndFunc(), Element::id(), Neutral::initCinfo(), MsgFuncBinding::mid, Msg::mid(), and SetGet1< A >::set().
Referenced by Shell::innerCopy().