MOOSE - Multiscale Object Oriented Simulation Environment: /home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/shell/Shell.cpp File Reference
Shell.cpp File Reference
#include <string>
#include <algorithm>
#include <chrono>
#include "../basecode/header.h"
#include "../basecode/global.h"
#include "../basecode/Dinfo.h"
#include "../basecode/SparseMatrix.h"
#include "../msg/SingleMsg.h"
#include "../msg/DiagonalMsg.h"
#include "../msg/OneToOneMsg.h"
#include "../msg/OneToAllMsg.h"
#include "../msg/SparseMsg.h"
#include "../builtins/SocketStreamer.h"
#include "../builtins/Streamer.h"
#include "Shell.h"
#include "Wildcard.h"
#include "../scheduling/Clock.h"
Functions
bool extractIndex (const string &s, unsigned int &index)
void insertSharedMsgs (const Finfo *f, const Element *e, vector< ObjId > &msgs)
bool isDoingReinit ()
Variables
static const Cinfo * shellCinfo = Shell::initCinfo()
Function Documentation
extractIndex()
bool extractIndex (const string & s, unsigned int & index)
Definition at line 391 of file Shell.cpp.
{
    vector<unsigned int> open;
    vector<unsigned int> close;
    index = 0;
    if (s.length() == 0)  // a plain slash is OK
        return true;
    if (s[0] == '[')  // Cannot open with a brace
        return false;
    for (unsigned int i = 0; i < s.length(); ++i) {
        if (s[i] == '[')
            open.push_back(i + 1);
        else if (s[i] == ']')
            close.push_back(i);
    }
    if (open.size() != close.size()) return false;
    if (open.size() == 0) return true;  // the index was set already to zero.
    int j = atoi(s.c_str() + open[0]);
    if (j >= 0) {
        index = j;
        return true;
    }
    return false;
}
Referenced by Shell::chopPath(), and testExtractIndices().
insertSharedMsgs()
void insertSharedMsgs (const Finfo * f, const Element * e, vector< ObjId > & msgs)
Definition at line 785 of file Shell.cpp.
{
    const SharedFinfo* sf = dynamic_cast<const SharedFinfo*>(f);
    if (sf) {
        for (vector<Finfo*>::const_iterator j = sf->dest().begin();
             j != sf->dest().end(); ++j) {
            DestFinfo* df = dynamic_cast<DestFinfo*>(*j);
            assert(df);
            FuncId fid = df->getFid();
            // These are the messages to be zapped
            vector<ObjId> caller;
            if (e->getInputMsgs(caller, fid) > 0) {
                msgs.insert(msgs.end(), caller.begin(), caller.end());
            }
        }
    }
}
References SharedFinfo::dest(), DestFinfo::getFid(), and Element::getInputMsgs().
Referenced by Shell::dropClockMsgs().
isDoingReinit()
bool isDoingReinit ()
Definition at line 330 of file Shell.cpp.
{
    static Id clockId(1);
    assert(clockId.element() != 0);
    return (reinterpret_cast<const Clock*>(clockId.eref().data()))
        ->isDoingReinit();
}
References Eref::data(), Id::element(), Id::eref(), Id::Id(), and Clock::isDoingReinit().
Variable Documentation
shellCinfo
const Cinfo* shellCinfo = Shell::initCinfo() static
Definition at line 142 of file Shell.cpp.