MOOSE - Multiscale Object Oriented Simulation Environment: /home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/msg/SparseMsg.cpp File Reference
SparseMsg.cpp File Reference
#include "../basecode/header.h"
#include "../basecode/global.h"
#include "../randnum/randnum.h"
#include "../shell/Shell.h"
#include "../basecode/SparseMatrix.h"
#include "SparseMsg.h"
Functions
void fillErefsFromMatrix (const SparseMatrix< unsigned int > &matrix, vector< vector< Eref > > &v, Element *e1, Element *e2)
unsigned int rowIndex (const Element *e, const DataId &d)
Variables
static const Cinfo * sparseMsgCinfo = SparseMsg::initCinfo()
Function Documentation
fillErefsFromMatrix()
void fillErefsFromMatrix (const SparseMatrix< unsigned int > & matrix, vector< vector< Eref > > & v, Element * e1, Element * e2)
Definition at line 598 of file SparseMsg.cpp.
{
    v.clear();
    v.resize( e1->numData() );
    assert( e1->numData() == matrix.nRows() );
    assert( e2->numData() == matrix.nColumns() );
    for ( unsigned int i = 0; i < e1->numData(); ++i )
    {
        const unsigned int* entry;
        const unsigned int* colIndex;
        unsigned int num = matrix.getRow( i, &entry, &colIndex );
        v[i].resize( num );
        for ( unsigned int j = 0; j < num; ++j )
        {
            v[i][j] = Eref( e2, colIndex[j], entry[j] );
        }
    }
}
References Eref::Eref(), SparseMatrix< T >::getRow(), SparseMatrix< T >::nColumns(), SparseMatrix< T >::nRows(), and Element::numData().
Referenced by SparseMsg::sources(), and SparseMsg::targets().
rowIndex()
unsigned int rowIndex (const Element * e, const DataId & d)
Definition at line 420 of file SparseMsg.cpp.
{
    // FieldDataHandlerBase* fdh = dynamic_cast< FieldDataHandlerBase* >( e->dataHandler() );
    return d;
}
Variable Documentation
sparseMsgCinfo
const Cinfo* sparseMsgCinfo = SparseMsg::initCinfo() static
Definition at line 181 of file SparseMsg.cpp.