MOOSE - Multiscale Object Oriented Simulation Environment: /home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/kinetics/Species.cpp File Reference
Species.cpp File Reference
#include "../basecode/header.h"
#include "Species.h"
Functions
static SrcFinfo1< double > * molWtOut ()
Variables
static const Cinfo * speciesCinfo = Species::initCinfo()
Function Documentation
molWtOut()
static SrcFinfo1< double > * molWtOut () static
Definition at line 13 of file Species.cpp.
{
    static SrcFinfo1< double > molWtOut(
            "molWtOut",
            "returns molWt."
            );
    return &molWtOut;
}
References SrcFinfo1< T >::SrcFinfo1().
Referenced by Species::handleMolWtRequest(), and Species::initCinfo().
Variable Documentation
speciesCinfo
const Cinfo* speciesCinfo = Species::initCinfo() static
Definition at line 75 of file Species.cpp.