MOOSE - Multiscale Object Oriented Simulation Environment: /home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/builtins/Stats.cpp File Reference
Stats.cpp File Reference
#include "../basecode/header.h"
#include "Stats.h"
Functions
static SrcFinfo1< vector< double > * > * requestOut ()
Variables
static const Cinfo * statsCinfo = Stats::initCinfo()
Function Documentation
requestOut()
static SrcFinfo1< vector< double > * > * requestOut () static
Definition at line 13 of file Stats.cpp.
{
    static SrcFinfo1< vector< double >* > requestOut(
            "requestOut",
            "Sends request for a field to target object"
            );
    return &requestOut;
}
References SrcFinfo1< T >::SrcFinfo1().
Referenced by Stats::initCinfo(), and Stats::vProcess().
Variable Documentation
statsCinfo
const Cinfo* statsCinfo = Stats::initCinfo() static
Definition at line 128 of file Stats.cpp.