MOOSE - Multiscale Object Oriented Simulation Environment: /home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/mesh/Stencil.cpp File Reference
Stencil.cpp File Reference
#include <vector>
#include <cassert>
#include "Stencil.h"
Functions
void stencil1 (vector< double > &f, int index, unsigned int n, double invSq, const vector< vector< double > > &S, const vector< double > &diffConst)
void stencilN (vector< double > &f, int index, unsigned int n, int offset, double invSq, const vector< vector< double > > &S, const vector< double > &diffConst)
Function Documentation
stencil1()
void stencil1 (vector< double > & f, int index, unsigned int n, double invSq, const vector< vector< double > > & S, const vector< double > & diffConst)
Definition at line 18 of file Stencil.cpp.
{
    const vector< double >& t0 = S[ index ];
    if ( index - static_cast< int >( n ) < 0 ) {
        const vector< double >& temp = S[ index + n ];
        for ( unsigned int i = 0; i < f.size(); ++i ) {
            f[i] += 2 * diffConst[i] * ( temp[i] - t0[i] ) * invSq;
        }
    } else if ( index + n >= S.size() ) {
        const vector< double >& temp = S[ index - n ];
        for ( unsigned int i = 0; i < f.size(); ++i ) {
            f[i] += 2 * diffConst[i] * ( temp[i] - t0[i] ) * invSq;
        }
    } else {
        const vector< double >& tminus = S[ index - n ];
        const vector< double >& tplus = S[ index + n ];
        for ( unsigned int i = 0; i < f.size(); ++i ) {
            f[i] += diffConst[i] * ( tminus[i] + tplus[i] - 2 * t0[i] ) * invSq;
        }
    }
}
Referenced by LineStencil::addFlux(), RectangleStencil::addFlux(), and CuboidStencil::addFlux().
stencilN()
void stencilN (vector< double > & f, int index, unsigned int n, int offset, double invSq, const vector< vector< double > > & S, const vector< double > & diffConst)
f is the flux vector, returned to caller index is the meshIndex being computed n is the number of mesh entries in this stencil. It is nx for the x axis and nx*ny for the y axis. offset is the stencil displacement: 1 for the x axis, nx for the y axis, doesn't apply for the z axis as that will be done using stencil1. invSq is 1/dx for the x axis, 1/dy for the y axis, and so on. S is the matrix of [meshEntries][pools] diffConst is the vector of [pools]
Definition at line 55 of file Stencil.cpp.
{
    const vector< double >& t0 = S[ index ];
    int rem = index % n;
    if ( rem < offset ) {
        const vector< double >& temp = S[ index + offset];
        for ( unsigned int i = 0; i < f.size(); ++i ) {
            f[i] += 2 * diffConst[i] * ( temp[i] - t0[i] ) * invSq;
        }
    } else if ( rem >= static_cast< int >( n ) - offset ) {
        const vector< double >& temp = S[ index - offset ];
        for ( unsigned int i = 0; i < f.size(); ++i ) {
            f[i] += 2 * diffConst[i] * ( temp[i] - t0[i] ) * invSq;
        }
    } else {
        const vector< double >& tminus = S[ index - offset ];
        const vector< double >& tplus = S[ index + offset ];
        for ( unsigned int i = 0; i < f.size(); ++i ) {
            f[i] += diffConst[i] * ( tminus[i] + tplus[i] - 2 * t0[i] ) * invSq;
        }
    }
}
Referenced by RectangleStencil::addFlux(), and CuboidStencil::addFlux().