MOOSE - Multiscale Object Oriented Simulation Environment: /home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/builtins/StimulusTable.cpp File Reference
StimulusTable.cpp File Reference
#include "../basecode/header.h"
#include <fstream>
#include "TableBase.h"
#include "StimulusTable.h"
Functions
static SrcFinfo1< double > * output ()
Variables
static const Cinfo * stimulusTableCinfo = StimulusTable::initCinfo()
Function Documentation
output()
static SrcFinfo1< double > * output () static
Definition at line 15 of file StimulusTable.cpp.
{
    static SrcFinfo1< double > output (
            "output",
            "Sends out tabulated data according to lookup parameters."
            );
    return &output;
}
References SrcFinfo1< T >::SrcFinfo1().
Referenced by StimulusTable::initCinfo(), StimulusTable::process(), and StimulusTable::reinit().
Variable Documentation
stimulusTableCinfo
const Cinfo* stimulusTableCinfo = StimulusTable::initCinfo() static
Definition at line 136 of file StimulusTable.cpp.