MOOSE - Multiscale Object Oriented Simulation Environment: /home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/ksolve/Stoich.cpp File Reference
Stoich.cpp File Reference
#include "../basecode/header.h"
#include "../basecode/ElementValueFinfo.h"
#include "../kinetics/PoolBase.h"
#include "../kinetics/EnzBase.h"
#include "FuncTerm.h"
#include "RateTerm.h"
#include "FuncRateTerm.h"
#include "../basecode/SparseMatrix.h"
#include "KinSparseMatrix.h"
#include "VoxelPoolsBase.h"
#include "../mesh/VoxelJunction.h"
#include "XferInfo.h"
#include "KsolveBase.h"
#include "../builtins/Variable.h"
#include "../builtins/Function.h"
#include "Stoich.h"
#include "../kinetics/Reac.h"
#include "../kinetics/lookupVolumeFromMesh.h"
#include "../scheduling/Clock.h"
#include "../shell/Shell.h"
#include "../shell/Wildcard.h"
#include "../utility/testing_macros.hpp"
Functions
void convWildcards (vector< Id > &ret, const vector< ObjId > &elist)
pair< Id, Id > extractCompts (const vector< Id > &compts)
void filterWildcards (vector< Id > &ret, const vector< ObjId > &elist)
static Id findFuncMsgSrc (Id pa, const string &msg)
Returns Function, if any, acting as src of specified msg into pa.
void installDummy (RateTerm **entry, Id enzId, const string &s)
static bool isOffSolverReac (const Element *e, Id myCompt, vector< Id > &poolCompts, map< Id, Id > &poolComptMap)
void myUnique (vector< Id > &v)
Variables
static const Cinfo * stoichCinfo = Stoich::initCinfo()
Function Documentation
convWildcards()
void convWildcards (vector< Id > & ret, const vector< ObjId > & elist)
Definition at line 364 of file Stoich.cpp.
{
    ret.resize(elist.size());
    for(unsigned int i = 0; i < elist.size(); ++i)
        ret[i] = elist[i].id;
}
References ObjId::id.
extractCompts()
pair< Id, Id > extractCompts (const vector< Id > & compts)
Extracts and orders the compartments associated with a given reac.
Definition at line 707 of file Stoich.cpp.
{
    pair<Id, Id> ret;
    for(vector<Id>::const_iterator i = compts.begin(); i != compts.end(); ++i) {
        if(ret.first == Id()) {
            ret.first = *i;
        }
        else if(ret.first != *i) {
            if(ret.second == Id())
                ret.second = *i;
            else {
                cout << "Error: Stoich::extractCompts: more than 2 "
                        "compartments\n";
                assert(0);
            }
        }
    }
    if((ret.second != Id()) && ret.second < ret.first) {
        Id temp = ret.first;
        ret.first = ret.second;
        ret.second = ret.first;
    }
    return ret;
}
References Id::Id(), Id::operator!=(), Id::operator<(), and Id::operator==().
Referenced by Stoich::locateOffSolverReacs().
filterWildcards()
void filterWildcards (vector< Id > & ret, const vector< ObjId > & elist)
Definition at line 371 of file Stoich.cpp.
{
    ret.clear();
    ret.reserve(elist.size());
    for(vector<ObjId>::const_iterator i = elist.begin(); i != elist.end();
        ++i) {
        if(i->element()->cinfo()->isA("PoolBase") ||
           i->element()->cinfo()->isA("Reac") ||
           i->element()->cinfo()->isA("EnzBase") ||
           i->element()->cinfo()->isA("Function"))
            ret.push_back(i->id);
    }
}
References Element::cinfo(), ObjId::element(), ObjId::id, and Cinfo::isA().
Referenced by Stoich::setElist().
findFuncMsgSrc()
static Id findFuncMsgSrc (Id pa, const string & msg) static
Returns Function, if any, acting as src of specified msg into pa.
Definition at line 1227 of file Stoich.cpp.
{
    const Finfo* finfo = pa.element()->cinfo()->findFinfo(msg);
    if(!finfo)
        return Id();
    vector<Id> ret;
    if(pa.element()->getNeighbors(ret, finfo) > 0) {
        if(ret[0].element()->cinfo()->isA("Function"))
            return ret[0];
    }
    return Id();  // failure
}
References Element::cinfo(), Id::element(), Cinfo::findFinfo(), Element::getNeighbors(), Id::Id(), and Cinfo::isA().
Referenced by Stoich::zombifyModel(), and Stoich::zombifyPoolFuncWithScaling().
installDummy()
void installDummy (RateTerm ** entry, Id enzId, const string & s)
Definition at line 1526 of file Stoich.cpp.
{
    cout << "Warning: Stoich::installMMenz: No " << s
         << " for: " << enzId.path() << endl;
    *entry = new ZeroOrder(0.0);
}
References Id::path(), and ZeroOrder::ZeroOrder().
Referenced by Stoich::installMMenz().
isOffSolverReac()
static bool isOffSolverReac (const Element * e, Id myCompt, vector< Id > & poolCompts, map< Id, Id > & poolComptMap) static
Checks if specified reac is off solver. As side-effect it compiles a vector of the pools that are off-solver, and the corresponding compartments for those pools
Definition at line 675 of file Stoich.cpp.
{
    assert(myCompt != Id());
    assert(myCompt.element()->cinfo()->isA("ChemCompt"));
    bool ret = false;
    vector<Id> neighbors;
    e->getNeighbors(neighbors, e->cinfo()->findFinfo("subOut"));
    vector<Id> n2;
    e->getNeighbors(n2, e->cinfo()->findFinfo("prdOut"));
    neighbors.insert(neighbors.end(), n2.begin(), n2.end());
    for(vector<Id>::const_iterator j = neighbors.begin(); j != neighbors.end();
        ++j) {
        Id otherCompt = getCompt(*j);
        if(myCompt != otherCompt) {
            // offSolverPools.push_back( *j );
            poolCompts.push_back(otherCompt);
            poolComptMap[*j] = otherCompt;  // Avoids duplication of pools
            ret = true;
            if(j->element()->cinfo()->isA("BufPool")) {
                cout << "Warning: Avoid BufPool: " << j->path()
                     << "\n as reactant in cross-compartment reactions\n";
            }
        }
    }
    return ret;
}
References Element::cinfo(), Id::element(), Cinfo::findFinfo(), getCompt(), Element::getNeighbors(), Id::Id(), Cinfo::isA(), Id::operator!=(), and Id::path().
Referenced by Stoich::locateOffSolverReacs().
myUnique()
void myUnique (vector< Id > & v)
Definition at line 866 of file Stoich.cpp.
{
    sort(v.begin(), v.end());
    vector<Id>::iterator last = unique(v.begin(), v.end());
    v.erase(last, v.end());
}
Referenced by Stoich::resizeArrays().
Variable Documentation
stoichCinfo
const Cinfo* stoichCinfo = Stoich::initCinfo() static
Definition at line 278 of file Stoich.cpp.