MOOSE - Multiscale Object Oriented Simulation Environment: pymoose::VecElementField Struct Reference
pymoose::VecElementField Struct Reference
#include <Finfo.h>
Public Member Functions
nb::object getAttribute (const string &name)
ElementField getItem (int index) const
bool setAttribute (const string &name, const nb::object &val)
size_t size () const
nb::ndarray< unsigned int, nb::numpy > sizes () const
VecElementField (const Id &id, const Finfo *f)
Public Attributes
const Finfo * finfo_
size_t numParents_
Id parentId_
Detailed Description
Definition at line 89 of file Finfo.h.
Constructor & Destructor Documentation
VecElementField()
pymoose::VecElementField::VecElementField (const Id & id, const Finfo * f)
Definition at line 535 of file Finfo.cpp.
    : parentId_(id), finfo_(f), numParents_(id.element()->numData())
{
}
References Id::element(), finfo_, Element::numData(), numParents_, and parentId_.
Member Function Documentation
getAttribute()
nb::object pymoose::VecElementField::getAttribute (const string & name)
Definition at line 575 of file Finfo.cpp.
{
    // numField is common to the entire ElementField - return numpy ndarray
    if((name == "numField") || name == "num") {
        return nb::cast(sizes());
    }
    // Other attributes are specific to each entry in the ElementField
    // - return a list of lists
    nb::list result;
    for(size_t p = 0; p < numParents_; ++p) {
        ObjId parentOid(parentId_, p);
        ObjId fieldOid(parentOid.path() + "/" + finfo_->name());
        unsigned int num = Field<unsigned int>::get(fieldOid, "numField");
        nb::list innerList;  // Create inner list for this parent
        for(unsigned int f = 0; f < num; ++f) {
            ObjId elemOid(fieldOid.id, fieldOid.dataIndex, f);
            innerList.append(getFieldGeneric(elemOid, name));
        }
        result.append(innerList);  // Append inner list to outer list
    }
    return result;
}
References ObjId::dataIndex, finfo_, ObjId::id, Finfo::name(), numParents_, ObjId::ObjId(), parentId_, and ObjId::path().
getItem()
ElementField pymoose::VecElementField::getItem (int index) const
Definition at line 565 of file Finfo.cpp.
{
    size_t idx = (index < 0) ? numParents_ + index : static_cast<size_t>(index);
    if(idx >= numParents_) {
        throw nb::index_error("Index out of range");
    }
    ObjId parentOid(parentId_, idx);
    return ElementField(parentOid, finfo_);
}
References pymoose::ElementField::ElementField(), finfo_, numParents_, ObjId::ObjId(), and parentId_.
setAttribute()
bool pymoose::VecElementField::setAttribute (const string & name, const nb::object & val)
Definition at line 599 of file Finfo.cpp.
{
    bool isSequence =
        nb::isinstance<nb::sequence>(val) && !nb::isinstance<nb::str>(val);
    nb::sequence seq;
    if(isSequence) {
        seq = nb::cast<nb::sequence>(val);
        if(nb::len(seq) != numParents_) {
            throw nb::value_error("Length must match numData of parent vec");
        }
    }
    bool res = true;
    // num is a special field setting the number of elements in an
    // ElementField
    if((name == "num") || (name == "numField")) {
        if(isSequence) {
            for(size_t i = 0; i < numParents_; ++i) {
                ObjId parentOid(parentId_, i);
                ObjId fieldOid(parentOid.path() + "/" + finfo_->name());
                res &= Field<unsigned int>::set(fieldOid, "numField",
                                                nb::cast<unsigned int>(seq[i]));
            }
        }
        else {
            unsigned int numField = nb::cast<unsigned int>(val);
            for(size_t i = 0; i < numParents_; ++i) {
                ObjId parentOid(parentId_, i);
                ObjId fieldOid(parentOid.path() + "/" + finfo_->name());
                res &= Field<unsigned int>::set(fieldOid, "numField", numField);
            }
        }
        return res;
    }
    // All other fields::
    // Scalar value - broadcast
    if(!isSequence) {
        for(size_t i = 0; i < numParents_; ++i) {
            ObjId parentOid(parentId_, i);
            ObjId fieldOid(parentOid.path() + "/" + finfo_->name());
            unsigned int num = Field<unsigned int>::get(fieldOid, "numField");
            for(unsigned int f = 0; f < num; ++f) {
                ObjId elemOid(fieldOid.id, fieldOid.dataIndex, f);
                res &= setFieldGeneric(elemOid, name, nb::borrow(val));
            }
        }
        return res;
    }
    // isSequence::
    // Process inner lists if sequence
    for(size_t p = 0; p < numParents_; ++p) {
        ObjId parentOid(parentId_, p);
        ObjId fieldOid(parentOid.path() + "/" + finfo_->name());
        unsigned int num = Field<unsigned int>::get(fieldOid, "numField");
        if (nb::isinstance<nb::sequence>(seq[p]) && !nb::isinstance<nb::str>(seq[p])){
            nb::sequence inner = nb::cast<nb::sequence>(seq[p]);
            if(nb::len(inner) != num) {
                throw nb::value_error(("Inner sequence " + to_string(p) +
                        " length mismatch: expected " +
                        to_string(num) + ", got " +
                        to_string(nb::len(inner)))
                    .c_str());
            }
            for(unsigned int f = 0; f < num; ++f) {
                ObjId elemOid(fieldOid.id, fieldOid.dataIndex, f);
                res &= setFieldGeneric(elemOid, name, nb::borrow(inner[f]));
            }
        } else { // broadcast scalar across parent's elements
            for(unsigned int f = 0; f < num; ++f) {
                ObjId elemOid(fieldOid.id, fieldOid.dataIndex, f);
                res &= setFieldGeneric(elemOid, name, nb::borrow(seq[p]));
            }
        }
    }
    return res;
} // VecElementField::setAttribute
References ObjId::dataIndex, finfo_, ObjId::id, Finfo::name(), numParents_, ObjId::ObjId(), parentId_, and ObjId::path().
size()
size_t pymoose::VecElementField::size () const
Definition at line 540 of file Finfo.cpp.
{
    size_t total = 0;
    for(size_t i = 0; i < numParents_; ++i) {
        ObjId parentOid(parentId_, i);
        string path = parentOid.path() + "/" + finfo_->name();
        ObjId fieldOid(path);
        total += Field<unsigned int>::get(fieldOid, "numField");
    }
    return total;
}
References finfo_, Finfo::name(), numParents_, ObjId::ObjId(), ObjId::ObjId(), parentId_, and ObjId::path().
sizes()
nb::ndarray< unsigned int, nb::numpy > pymoose::VecElementField::sizes () const
Definition at line 552 of file Finfo.cpp.
{
    unsigned int* data = new unsigned int[numParents_];
    for(size_t i = 0; i < numParents_; ++i) {
        ObjId parentOid(parentId_, i);
        ObjId fieldOid(parentOid.path() + "/" + finfo_->name());
        data[i] = Field<unsigned int>::get(fieldOid, "numField");
    }
    nb::capsule owner(
        data, [](void* p) noexcept { delete[] static_cast<unsigned int*>(p); });
    return nb::ndarray<unsigned int, nb::numpy>(data, {numParents_}, owner);
}
References finfo_, Finfo::name(), numParents_, ObjId::ObjId(), parentId_, and ObjId::path().
Member Data Documentation
finfo_
const Finfo* pymoose::VecElementField::finfo_
Definition at line 91 of file Finfo.h.
Referenced by getAttribute(), getItem(), setAttribute(), size(), sizes(), and VecElementField().
numParents_
size_t pymoose::VecElementField::numParents_
Definition at line 92 of file Finfo.h.
Referenced by getAttribute(), getItem(), setAttribute(), size(), sizes(), and VecElementField().
parentId_
Id pymoose::VecElementField::parentId_
Definition at line 90 of file Finfo.h.
Referenced by getAttribute(), getItem(), setAttribute(), size(), sizes(), and VecElementField().
The documentation for this struct was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/pymoose/Finfo.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/pymoose/Finfo.cpp