MOOSE - Multiscale Object Oriented Simulation Environment: moose::Parser::ParserException Struct Reference
moose::Parser::ParserException Struct Reference
#include <MooseParser.h>
Public Member Functions
string GetMsg ()
ParserException (const string msg)
Public Attributes
string msg_
Detailed Description
Definition at line 40 of file MooseParser.h.
Constructor & Destructor Documentation
ParserException()
moose::Parser::ParserException::ParserException (const string msg) inline
Definition at line 42 of file MooseParser.h.
: msg_(msg) { ; }
References msg_.
Referenced by moose::MooseParser::CompileExpr(), and moose::MooseParser::ParseVariables().
Member Function Documentation
GetMsg()
string moose::Parser::ParserException::GetMsg () inline
Definition at line 44 of file MooseParser.h.
    {
        return msg_;
    }
References msg_.
Referenced by Neuron::evalExprForElist(), makeAngleDistrib(), makeSizeDistrib(), Neuron::makeSpacingDistrib(), FuncTerm::operator()(), setCompartmentParams(), setMechParams(), and showError().
Member Data Documentation
msg_
string moose::Parser::ParserException::msg_
Definition at line 49 of file MooseParser.h.
Referenced by GetMsg(), and ParserException().
The documentation for this struct was generated from the following file:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/builtins/MooseParser.h