MOOSE - Multiscale Object Oriented Simulation Environment: pymoose::ElementFieldIterator Struct Reference
pymoose::ElementFieldIterator Struct Reference
Iterator class for ElementField.
#include <Finfo.h>
Public Member Functions
ElementFieldIterator (const ObjId &fieldOid, size_t size)
ObjId next ()
Public Attributes
ObjId fieldOid_
size_t index_
size_t size_
Detailed Description
Iterator class for ElementField.
Definition at line 47 of file Finfo.h.
Constructor & Destructor Documentation
ElementFieldIterator()
pymoose::ElementFieldIterator::ElementFieldIterator (const ObjId & fieldOid, size_t size) inline
Definition at line 52 of file Finfo.h.
        : fieldOid_(fieldOid), index_(0), size_(size)
    {
    }
References fieldOid_, index_, ObjId::ObjId(), and size_.
Referenced by pymoose::ElementField::iter().
Member Function Documentation
next()
ObjId pymoose::ElementFieldIterator::next ()
Definition at line 378 of file Finfo.cpp.
{
    if(index_ >= size_) {
        throw nb::stop_iteration();
    }
    return ObjId(fieldOid_.id, fieldOid_.dataIndex, index_++);
}
References ObjId::dataIndex, fieldOid_, ObjId::id, index_, ObjId::ObjId(), and size_.
Member Data Documentation
fieldOid_
ObjId pymoose::ElementFieldIterator::fieldOid_
Definition at line 48 of file Finfo.h.
Referenced by ElementFieldIterator(), and next().
index_
size_t pymoose::ElementFieldIterator::index_
Definition at line 49 of file Finfo.h.
Referenced by ElementFieldIterator(), and next().
size_
size_t pymoose::ElementFieldIterator::size_
Definition at line 50 of file Finfo.h.
Referenced by ElementFieldIterator(), and next().
The documentation for this struct was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/pymoose/Finfo.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/pymoose/Finfo.cpp