MOOSE - Multiscale Object Oriented Simulation Environment: pymoose::VecLookupField Struct Reference
pymoose::VecLookupField Struct Reference
Modified LookupField to allow vectorized assignment and lookup.
#include <Finfo.h>
Public Member Functions
nb::object get (const nb::object &key)
bool set (const nb::object &key, const nb::object &val)
VecLookupField (const Id &id, const Finfo *f)
Public Attributes
const Finfo * finfo_
Id id_
string keyType_
size_t numData_
string valueType_
Detailed Description
Modified LookupField to allow vectorized assignment and lookup.
Definition at line 76 of file Finfo.h.
Constructor & Destructor Documentation
VecLookupField()
pymoose::VecLookupField::VecLookupField (const Id & id, const Finfo * f)
Definition at line 386 of file Finfo.cpp.
    : id_(id), finfo_(f)
{
    auto rttType = f->rttiType();
    vector<string> tokens;
    moose::tokenize(rttType, ",", tokens);
    if(tokens.size() != 2) {
        throw nb::type_error(
            ("Cannot handle LookupFinfo with type " + rttType).c_str());
    }
    keyType_ = tokens[0];
    valueType_ = tokens[1];
}
References finfo_, id_, keyType_, Finfo::rttiType(), moose::tokenize(), and valueType_.
Member Function Documentation
get()
nb::object pymoose::VecLookupField::get (const nb::object & key)
Definition at line 400 of file Finfo.cpp.
{
    size_t numData = id_.element()->numData();
    // Macro for simple value types that can be returned as numpy
#define VEC_LOOKUP_GET_NUMPY(KT, VT)                                         \
    if(keyType_ == #KT && valueType_ == #VT) {                               \
        auto typedKey = nb::cast<KT>(key);                                   \
        VT* data = new VT[numData];                                          \
        for(size_t ii = 0; ii < numData; ++ii) {                             \
            ObjId oid(id_, ii);                                              \
            data[ii] =                                                       \
                ::LookupField<KT, VT>::get(oid, finfo_->name(), typedKey);   \
        }                                                                    \
        nb::capsule owner(                                                   \
            data, [](void* p) noexcept { delete[] static_cast<VT*>(p); });   \
        return nb::cast(nb::ndarray<VT, nb::numpy>(data, {numData}, owner)); \
    }
    // Macro for complex value types that return a list
#define VEC_LOOKUP_GET_LIST(KT, VT)                                          \
    if(keyType_ == #KT && valueType_ == #VT) {                               \
        auto typedKey = nb::cast<KT>(key);                                   \
        nb::list result;                                                     \
        for(size_t ii = 0; ii < numData; ++ii) {                             \
            ObjId oid(id_, ii);                                              \
            result.append(nb::cast(                                          \
                ::LookupField<KT, VT>::get(oid, finfo_->name(), typedKey))); \
        }                                                                    \
        return result;                                                       \
    }
    // String key with numeric values -> numpy
    VEC_LOOKUP_GET_NUMPY(string, double)
    VEC_LOOKUP_GET_NUMPY(string, int)
    VEC_LOOKUP_GET_NUMPY(string, unsigned int)
    VEC_LOOKUP_GET_NUMPY(string, long)
    VEC_LOOKUP_GET_NUMPY(string, bool)
    // String key with complex values -> list
    VEC_LOOKUP_GET_LIST(string, string)
    VEC_LOOKUP_GET_LIST(string, vector<double>)
    VEC_LOOKUP_GET_LIST(string, vector<int>)
    VEC_LOOKUP_GET_LIST(string, vector<string>)
    // Int key
    VEC_LOOKUP_GET_NUMPY(int, double)
    VEC_LOOKUP_GET_NUMPY(int, int)
    VEC_LOOKUP_GET_NUMPY(int, unsigned int)
    VEC_LOOKUP_GET_NUMPY(int, long)
    VEC_LOOKUP_GET_LIST(int, string)
    VEC_LOOKUP_GET_LIST(int, vector<double>)
    // Unsigned int key
    VEC_LOOKUP_GET_NUMPY(unsigned int, double)
    VEC_LOOKUP_GET_NUMPY(unsigned int, int)
    VEC_LOOKUP_GET_NUMPY(unsigned int, unsigned int)
    VEC_LOOKUP_GET_NUMPY(unsigned int, long)
    VEC_LOOKUP_GET_LIST(unsigned int, string)
    VEC_LOOKUP_GET_LIST(unsigned int, vector<double>)
    // Long key
    VEC_LOOKUP_GET_NUMPY(long, double)
    VEC_LOOKUP_GET_NUMPY(long, int)
    VEC_LOOKUP_GET_NUMPY(long, unsigned int)
    VEC_LOOKUP_GET_NUMPY(long, long)
#undef VEC_LOOKUP_GET_NUMPY
#undef VEC_LOOKUP_GET_LIST
    throw nb::type_error(
        ("Unsupported VecLookupField type: " + keyType_ + "," + valueType_)
            .c_str());
}
References Id::element(), id_, and Element::numData().
set()
bool pymoose::VecLookupField::set (const nb::object & key, const nb::object & val)
Definition at line 474 of file Finfo.cpp.
{
    size_t numData = id_.element()->numData();
    bool isIterable =
        nb::isinstance<nb::iterable>(val) && !nb::isinstance<nb::str>(val);
    // Macro for broadcasting single value to all elements
#define VEC_LOOKUP_SET(KT, VT)                                           \
    if(keyType_ == #KT && valueType_ == #VT) {                           \
        auto typedKey = nb::cast<KT>(key);                               \
        if(isIterable) {                                                 \
            auto vals = nb::cast<vector<VT>>(val);                       \
            if(vals.size() != numData) {                                 \
                throw nb::value_error(("Length mismatch: expected " +    \
                                       to_string(numData) + ", got " +   \
                                       to_string(vals.size()))           \
                                          .c_str());                     \
            }                                                            \
            bool res = true;                                             \
            for(size_t ii = 0; ii < numData; ++ii) {                     \
                res &= ::LookupField<KT, VT>::set(                       \
                    ObjId(id_, ii), finfo_->name(), typedKey, vals[ii]); \
            }                                                            \
            return res;                                                  \
        }                                                                \
        else {                                                           \
            auto typedVal = nb::cast<VT>(val);                           \
            bool res = true;                                             \
            for(size_t ii = 0; ii < numData; ++ii) {                     \
                res &= ::LookupField<KT, VT>::set(                       \
                    ObjId(id_, ii), finfo_->name(), typedKey, typedVal); \
            }                                                            \
            return res;                                                  \
        }                                                                \
    }
    VEC_LOOKUP_SET(unsigned int, double)
    VEC_LOOKUP_SET(unsigned int, unsigned int)
    VEC_LOOKUP_SET(unsigned int, vector<double>)
    VEC_LOOKUP_SET(unsigned int, vector<unsigned int>)
    VEC_LOOKUP_SET(string, bool)
    VEC_LOOKUP_SET(string, unsigned int)
    VEC_LOOKUP_SET(string, double)
    VEC_LOOKUP_SET(string, long)
    VEC_LOOKUP_SET(string, string)
    VEC_LOOKUP_SET(string, vector<double>)
    VEC_LOOKUP_SET(string, vector<long>)
    VEC_LOOKUP_SET(string, vector<string>)
    VEC_LOOKUP_SET(ObjId, ObjId)
    VEC_LOOKUP_SET(ObjId, int)
    VEC_LOOKUP_SET(vector<double>, double)
    VEC_LOOKUP_SET(vector<unsigned int>, double)
#undef VEC_LOOKUP_SET
    throw nb::type_error(("Unsupported VecLookupField set type: " + keyType_ +
                          "," + valueType_ + ". Try looping through elements.")
                             .c_str());
}
References Id::element(), id_, and Element::numData().
Member Data Documentation
finfo_
const Finfo* pymoose::VecLookupField::finfo_
Definition at line 78 of file Finfo.h.
Referenced by VecLookupField().
id_
Id pymoose::VecLookupField::id_
Definition at line 77 of file Finfo.h.
Referenced by get(), set(), and VecLookupField().
keyType_
string pymoose::VecLookupField::keyType_
Definition at line 79 of file Finfo.h.
Referenced by VecLookupField().
numData_
size_t pymoose::VecLookupField::numData_
Definition at line 81 of file Finfo.h.
valueType_
string pymoose::VecLookupField::valueType_
Definition at line 80 of file Finfo.h.
Referenced by VecLookupField().
The documentation for this struct was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/pymoose/Finfo.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/pymoose/Finfo.cpp