MOOSE - Multiscale Object Oriented Simulation Environment: pymoose::ElementField Struct Reference
pymoose::ElementField Struct Reference
For FieldElementFinfo - vector of elements.
#include <Finfo.h>
Public Member Functions
ElementField (const ObjId &oid, const Finfo *f)
Finfo ObjId.
nb::object getAttribute (const string &field)
ObjId getItem (int index) const
unsigned int getNum () const
ElementFieldIterator iter () const
bool setAttribute (const string &field, nb::object value)
bool setNum (unsigned int n)
size_t size () const
Public Attributes
const Finfo * finfo_
Owner ObjId.
ObjId foid_
ObjId oid_
Detailed Description
For FieldElementFinfo - vector of elements.
Definition at line 60 of file Finfo.h.
Constructor & Destructor Documentation
ElementField()
pymoose::ElementField::ElementField (const ObjId & oid, const Finfo * f)
Finfo ObjId.
Definition at line 310 of file Finfo.cpp.
    : oid_(oid),
      finfo_(f),
      foid_(ObjId(oid.path() + "/" + f->name()))
{
}
References finfo_, foid_, Finfo::name(), ObjId::ObjId(), oid_, and ObjId::path().
Referenced by pymoose::VecElementField::getItem().
Member Function Documentation
getAttribute()
nb::object pymoose::ElementField::getAttribute (const string & field)
Definition at line 354 of file Finfo.cpp.
{
    unsigned int num = getNum();
    if(num > 0) {
        return MooseVec(foid_).getAttribute(field);
    }
    throw nb::index_error(
        "Trying to access attribute of an ElementField with 0 elements");
}
References foid_, getNum(), and pymoose::MooseVec::MooseVec().
getItem()
ObjId pymoose::ElementField::getItem (int index) const
Definition at line 332 of file Finfo.cpp.
{
    unsigned int numFields = getNum();
    size_t ii = (index < 0) ? numFields + index : static_cast<size_t>(index);
    // Bounds check
    if(ii >= numFields) {
        throw nb::index_error(
            ("Index " + std::to_string(index) +
             " out of range (size=" + std::to_string(numFields) + ")")
                .c_str());
    }
    // Return ObjId with fieldIndex set
    return ObjId(foid_.id, foid_.dataIndex, ii);
}
References ObjId::dataIndex, foid_, getNum(), ObjId::id, and ObjId::ObjId().
getNum()
unsigned int pymoose::ElementField::getNum () const
Definition at line 317 of file Finfo.cpp.
{
    return Field<unsigned int>::get(foid_, "numField");
}
Referenced by getAttribute(), getItem(), setAttribute(), and size().
iter()
ElementFieldIterator pymoose::ElementField::iter () const
Definition at line 349 of file Finfo.cpp.
{
    return ElementFieldIterator(foid_, size());
}
References pymoose::ElementFieldIterator::ElementFieldIterator(), foid_, and size().
setAttribute()
bool pymoose::ElementField::setAttribute (const string & field, nb::object value)
Definition at line 365 of file Finfo.cpp.
{
    unsigned int num = getNum();
    if((field == "num") || (field == "numField")) {
        return setNum(nb::cast<unsigned int>(value));
    }
    if(num > 0) {
        return MooseVec(foid_).setAttribute(field, value);
    }
    throw nb::index_error(
        "Trying to access attribute of an ElementField with 0 elements");
}
References foid_, getNum(), and pymoose::MooseVec::MooseVec().
setNum()
bool pymoose::ElementField::setNum (unsigned int n)
Definition at line 322 of file Finfo.cpp.
{
    return Field<unsigned int>::set(foid_, "numField", n);
}
size()
size_t pymoose::ElementField::size () const
Definition at line 327 of file Finfo.cpp.
{
    return static_cast<size_t>(getNum());
}
References getNum().
Referenced by iter().
Member Data Documentation
finfo_
const Finfo* pymoose::ElementField::finfo_
Owner ObjId.
Definition at line 62 of file Finfo.h.
Referenced by ElementField().
foid_
ObjId pymoose::ElementField::foid_
Definition at line 63 of file Finfo.h.
Referenced by ElementField(), getAttribute(), getItem(), iter(), and setAttribute().
oid_
ObjId pymoose::ElementField::oid_
Definition at line 61 of file Finfo.h.
Referenced by ElementField().
The documentation for this struct was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/pymoose/Finfo.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/pymoose/Finfo.cpp