MOOSE - Multiscale Object Oriented Simulation Environment: SpikeGenStruct Struct Reference
SpikeGenStruct Struct Reference
#include <HSolveStruct.h>
Public Member Functions
void reinit (ProcPtr info)
void send (ProcPtr info)
SpikeGenStruct (double *Vm, Eref e)
Public Attributes
Eref e_
double * Vm_
Detailed Description
Contains information about the spikegens that the HSolve object needs to talk with
Definition at line 114 of file HSolveStruct.h.
Constructor & Destructor Documentation
SpikeGenStruct()
SpikeGenStruct::SpikeGenStruct (double * Vm, Eref e) inline
Definition at line 116 of file HSolveStruct.h.
        :
        Vm_( Vm ),
        e_( e )
    { ; }
References e_, Eref::Eref(), and Vm_.
Referenced by HSolveActive::readSynapses().
Member Function Documentation
reinit()
void SpikeGenStruct::reinit (ProcPtr info)
Finds the spikegen object using e_ and calls reinit on the spikegen
Definition at line 67 of file HSolveStruct.cpp.
{
    SpikeGen* spike = reinterpret_cast< SpikeGen* >( e_.data() );
    spike->reinit( e_, info );
}
References Eref::data(), e_, and SpikeGen::reinit().
Referenced by HSolveActive::reinitSpikeGens().
send()
void SpikeGenStruct::send (ProcPtr info)
Definition at line 74 of file HSolveStruct.cpp.
{
    SpikeGen* spike = reinterpret_cast< SpikeGen* >( e_.data() );
    spike->handleVm( *Vm_ );
    spike->process( e_, info );
}
References Eref::data(), e_, SpikeGen::handleVm(), SpikeGen::process(), and Vm_.
Referenced by HSolveActive::sendSpikes().
Member Data Documentation
e_
Eref SpikeGenStruct::e_
Definition at line 123 of file HSolveStruct.h.
Referenced by reinit(), send(), and SpikeGenStruct().
Vm_
double* SpikeGenStruct::Vm_
Definition at line 122 of file HSolveStruct.h.
Referenced by send(), and SpikeGenStruct().
The documentation for this struct was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/hsolve/HSolveStruct.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/hsolve/HSolveStruct.cpp