MOOSE - Multiscale Object Oriented Simulation Environment: pymoose::LookupField Struct Reference
pymoose::LookupField Struct Reference
For LookupValueFinfo - dict-like access.
#include <Finfo.h>
Public Member Functions
nb::object get (const nb::object &key)
LookupField (const ObjId &oid, const Finfo *f)
bool set (const nb::object &key, const nb::object &val)
Public Attributes
const Finfo * finfo_
string keyType_
ObjId oid_
string valueType_
Detailed Description
For LookupValueFinfo - dict-like access.
Definition at line 36 of file Finfo.h.
Constructor & Destructor Documentation
LookupField()
LookupField< L, A >::LookupField (const ObjId & oid, const Finfo * f)
Definition at line 226 of file Finfo.cpp.
    : oid_(oid), finfo_(f)
{
    auto rttType = f->rttiType();
    vector<string> tokens;
    moose::tokenize(rttType, ",", tokens);
    if(tokens.size() != 2) {
        throw nb::type_error(
            ("Cannot handle LookupFinfo with type " + rttType).c_str());
    }
    keyType_ = tokens[0];
    valueType_ = tokens[1];
}
References finfo_, keyType_, ObjId::ObjId(), oid_, Finfo::rttiType(), moose::tokenize(), and valueType_.
Member Function Documentation
get()
nb::object LookupField< L, A >::get (const nb::object & key)
Definition at line 240 of file Finfo.cpp.
{
    if(keyType_ == "string") {
        auto it = stringKeyGetters.find(valueType_);
        if(it != stringKeyGetters.end()) {
            return it->second(oid_, finfo_->name(), nb::cast<string>(key));
        }
    }
    else if(keyType_ == "int") {
        auto it = intKeyGetters.find(valueType_);
        if(it != intKeyGetters.end()) {
            return it->second(oid_, finfo_->name(), nb::cast<int>(key));
        }
    }
    if(keyType_ == "unsigned int") {
        auto it = uintKeyGetters.find(valueType_);
        if(it != uintKeyGetters.end()) {
            return it->second(oid_, finfo_->name(),
                              nb::cast<unsigned int>(key));
        }
    }
    else if(keyType_ == "long") {
        auto it = longKeyGetters.find(valueType_);
        if(it != longKeyGetters.end()) {
            return it->second(oid_, finfo_->name(), nb::cast<long>(key));
        }
    }
    throw nb::type_error(
        ("Unsupported lookup type: " + finfo_->rttiType()).c_str());
}
References keyType_, and valueType_.
set()
bool LookupField< L, A >::set (const nb::object & key, const nb::object & val)
Definition at line 272 of file Finfo.cpp.
{
    // Subha: feeling lazy - will go with macro
#define LOOKUP_SET(K, V)                                                       \
    if((keyType_ == #K) && (valueType_ == #V)) {                               \
        return ::LookupField<K, V>::set(oid_, finfo_->name(),                  \
                                        nb::cast<K>(key), nb::cast<V>(value)); \
    }
    LOOKUP_SET(unsigned int, double)
    LOOKUP_SET(unsigned int, unsigned int)
    LOOKUP_SET(unsigned int, vector<double>)
    LOOKUP_SET(unsigned int, vector<unsigned int>)
    LOOKUP_SET(string, bool)
    LOOKUP_SET(string, unsigned int)
    LOOKUP_SET(string, double)
    LOOKUP_SET(string, long)
    LOOKUP_SET(string, string)
    LOOKUP_SET(string, vector<double>)
    LOOKUP_SET(string, vector<long>)
    LOOKUP_SET(string, vector<string>)
    LOOKUP_SET(ObjId, ObjId)
    LOOKUP_SET(ObjId, int)
    // Used in Stoich::proxyPools
    LOOKUP_SET(Id, vector<Id>)
    // Used in Interpol2D
    LOOKUP_SET(vector<double>, double)
    LOOKUP_SET(vector<unsigned int>, double)
#undef LOOKUP_SET
    throw nb::type_error(
        ("Unsupported LookupField type: " + keyType_ + "," + valueType_)
            .c_str());
}
Member Data Documentation
finfo_
const Finfo* pymoose::LookupField::finfo_
Definition at line 38 of file Finfo.h.
Referenced by LookupField().
keyType_
string pymoose::LookupField::keyType_
Definition at line 39 of file Finfo.h.
Referenced by get(), and LookupField().
oid_
ObjId pymoose::LookupField::oid_
Definition at line 37 of file Finfo.h.
Referenced by LookupField().
valueType_
string pymoose::LookupField::valueType_
Definition at line 40 of file Finfo.h.
Referenced by get(), and LookupField().
The documentation for this struct was generated from the following files:
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/pymoose/Finfo.h
/home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/pymoose/Finfo.cpp