MOOSE - Multiscale Object Oriented Simulation Environment: /home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/biophysics/SymCompartment.cpp File Reference
SymCompartment.cpp File Reference
#include "../basecode/header.h"
#include "CompartmentBase.h"
#include "Compartment.h"
#include "SymCompartment.h"
Functions
static SrcFinfo2< double, double > * cylinderOut ()
static SrcFinfo2< double, double > * distalOut ()
static SrcFinfo2< double, double > * proximalOut ()
static SrcFinfo1< double > * sumRaxialOut ()
Variables
static const Cinfo * symCompartmentCinfo = SymCompartment::initCinfo()
Function Documentation
cylinderOut()
static SrcFinfo2< double, double > * cylinderOut () static
Definition at line 35 of file SymCompartment.cpp.
{
    static SrcFinfo2< double, double > cylinderOut( "cylinderOut",
            " Sends out Ra and Vm to compartments (typically spines) on the"
            " curved surface of a cylinder. Ra is set to nearly zero,"
            " since we assume that the resistance from axis to surface is"
            " negligible." );
    return &cylinderOut;
}
References SrcFinfo2< T1, T2 >::SrcFinfo2().
Referenced by SymCompartment::initCinfo(), and SymCompartment::vInitProc().
distalOut()
static SrcFinfo2< double, double > * distalOut () static
Definition at line 16 of file SymCompartment.cpp.
{
    static SrcFinfo2< double, double > distalOut( "distalOut",
            "Sends out Ra and Vm on each timestep, on the distal end"
            " of a compartment. This end should be pointed away from the"
            " soma. Mathematically the same as proximalOut, but gives"
            " an orientation to the dendrite and helps traversal.");
    return &distalOut;
}
References SrcFinfo2< T1, T2 >::SrcFinfo2().
Referenced by SymCompartment::initCinfo(), and SymCompartment::vInitProc().
proximalOut()
static SrcFinfo2< double, double > * proximalOut () static
Definition at line 25 of file SymCompartment.cpp.
{
    static SrcFinfo2< double, double > proximalOut( "proximalOut",
            "Sends out Ra and Vm on each timestep, on the proximal"
           " end of a compartment. That is, this end should be "
           " pointed toward the soma. Mathematically the same as raxialOut"
           " but provides a logical orientation of the dendrite."
           " One can traverse proximalOut messages to get to the soma." );
    return &proximalOut;
}
References SrcFinfo2< T1, T2 >::SrcFinfo2().
Referenced by SymCompartment::initCinfo(), and SymCompartment::vInitProc().
sumRaxialOut()
static SrcFinfo1< double > * sumRaxialOut () static
Definition at line 44 of file SymCompartment.cpp.
{
    static SrcFinfo1< double > sumRaxialOut( "sumRaxialOut",
        "Sends out Ra" );
    return &sumRaxialOut;
}
References SrcFinfo1< T >::SrcFinfo1().
Referenced by SymCompartment::initCinfo(), and SymCompartment::vReinit().
Variable Documentation
symCompartmentCinfo
const Cinfo* symCompartmentCinfo = SymCompartment::initCinfo() static
Definition at line 277 of file SymCompartment.cpp.