MOOSE - Multiscale Object Oriented Simulation Environment: /home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/builtins/Table.cpp File Reference
Table.cpp File Reference
#include "../basecode/header.h"
#include "../basecode/global.h"
#include <fstream>
#include <array>
#include "TableBase.h"
#include "Table.h"
#include "../scheduling/Clock.h"
#include "StreamerBase.h"
Functions
static DestFinfo * handleInput ()
static SrcFinfo1< vector< double > * > * requestOut ()
Variables
static const Cinfo * tableCinfo = Table::initCinfo()
Function Documentation
handleInput()
static DestFinfo * handleInput () static
Definition at line 29 of file Table.cpp.
{
    static DestFinfo input(
        "input",
        "Fills data into table. Also handles data sent back following request",
        new OpFunc1< Table, double >( &Table::input )
    );
    return &input;
}
References DestFinfo::DestFinfo(), Table::input(), and OpFunc1< T, A >::OpFunc1().
Referenced by Table::initCinfo().
requestOut()
static SrcFinfo1< vector< double > * > * requestOut () static
Definition at line 20 of file Table.cpp.
{
    static SrcFinfo1< vector< double >* > requestOut(
        "requestOut",
        "Sends request for a field to target object"
    );
    return &requestOut;
}
References SrcFinfo1< T >::SrcFinfo1().
Referenced by Table::initCinfo(), Table::process(), and Table::reinit().
Variable Documentation
tableCinfo
const Cinfo* tableCinfo = Table::initCinfo() static
Definition at line 217 of file Table.cpp.