MOOSE - Multiscale Object Oriented Simulation Environment: /home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/builtins/TableBase.cpp File Reference
TableBase.cpp File Reference
#include "../basecode/header.h"
#include <fstream>
#include "../utility/strutil.h"
#include "TableBase.h"
Functions
double getRMS (const vector< double > &v)
double getRMSDiff (const vector< double > &v1, const vector< double > &v2)
double getRMSRatio (const vector< double > &v1, const vector< double > &v2)
double getYcolumn (const string &line)
string headop (const string &op)
bool innerLoadXplot (string fname, string plotname, vector< double > &v)
bool isNamedPlot (const string &line, const string &plotname)
Variables
static const Cinfo * tableBaseCinfo = TableBase::initCinfo()
Function Documentation
getRMS()
double getRMS (const vector< double > & v)
Definition at line 365 of file TableBase.cpp.
{
    double sumsq = 0;
    unsigned int size = v.size();
    if ( size == 0 )
        return -1;
    for ( vector< double >::const_iterator i = v.begin(); i != v.end(); ++i)
        sumsq += *i * *i;
    return sqrt( sumsq / size );
}
Referenced by getRMSRatio(), and testUtilsForCompareXplot().
getRMSDiff()
double getRMSDiff (const vector< double > & v1, const vector< double > & v2)
Definition at line 350 of file TableBase.cpp.
{
    unsigned int size = ( v1.size() < v2.size() ) ? v1.size() : v2.size();
    if ( size == 0 )
        return -1;
    double sumsq = 0;
    for ( unsigned int i = 0; i < size; ++i )
    {
        double temp = v1[i] - v2[i];
        sumsq += temp * temp;
    }
    return sqrt( sumsq / size );
}
Referenced by TableBase::compareVec(), TableBase::compareXplot(), getRMSRatio(), and testUtilsForCompareXplot().
getRMSRatio()
double getRMSRatio (const vector< double > & v1, const vector< double > & v2)
Definition at line 377 of file TableBase.cpp.
{
    double r1 = getRMS( v1 );
    double r2 = getRMS( v2 );
    if ( v1.size() == 0 || v2.size() == 0 )
        return -1;
    if ( r1 + r2 > 1e-20 )
        return getRMSDiff( v1, v2 ) / (r1 + r2);
    return -1;
}
References getRMS(), and getRMSDiff().
Referenced by TableBase::compareVec(), TableBase::compareXplot(), and testUtilsForCompareXplot().
getYcolumn()
double getYcolumn (const string & line)
Definition at line 239 of file TableBase.cpp.
{
    istringstream sstream( line );
    double y1 = 0.0;
    double y2;
    double y3;
    if ( sstream >> y1 )
    {
        if ( sstream >> y2 )
        {
            if ( sstream >> y3 )
            {
                return y1;
            }
            else
            {
                return y2;
            }
        }
    }
    return y1;
}
Referenced by innerLoadXplot(), and testUtilsForLoadXplot().
headop()
string headop (const string & op)
Definition at line 388 of file TableBase.cpp.
{
    const unsigned int len = 5;
    char temp[len];
    unsigned int i = 0;
    for ( i = 0; i < op.length() && i < len-1 ; ++i )
        temp[i] = tolower( op[i] );
    temp[i] = '\0';
    return string( temp );
}
Referenced by TableBase::compareVec(), and TableBase::compareXplot().
innerLoadXplot()
bool innerLoadXplot (string fname, string plotname, vector< double > & v)
Definition at line 263 of file TableBase.cpp.
{
    ifstream fin( fname.c_str() );
    if ( !fin.good() )
    {
        cout << "TableBase::innerLoadXplot: Failed to open file " << fname <<endl;
        return 0;
    }
    string line;
    // Here we advance to the first numerical line.
    if ( plotname == "" ) // Just load starting from the 1st numerical line.
    {
        while ( fin.good() )   // Break out of this loop if we find a number
        {
            getline( fin, line );
            line = moose::trim(line);
            if ( isdigit( line[0] ) )
                break;;
            if ( line[0] == '-' && line.length() > 1 && isdigit( line[1] ) )
                break;
        }
    }
    else     // Find plotname and then begin loading.
    {
        while ( fin.good() )
        {
            getline( fin, line );
            line = moose::trim(line);
            if ( isNamedPlot ( line, plotname ) )
            {
                if ( !getline ( fin, line ) )
                    return 0;
                break;
            }
        }
    }
    v.resize( 0 );
    do
    {
        if ( line.length() == 0 || line == "/newplot" || line == "/plotname" )
            break;
        v.push_back( getYcolumn( line ) );
        getline( fin, line );
        line = moose::trim(line);
    }
    while ( fin.good() );
    return ( v.size() > 0 );
}
References getYcolumn(), isNamedPlot(), and moose::trim().
Referenced by TableBase::compareXplot(), TableBase::loadXplot(), and TableBase::loadXplotRange().
isNamedPlot()
bool isNamedPlot (const string & line, const string & plotname)
Definition at line 198 of file TableBase.cpp.
{
    static const unsigned int len = strlen( "/plotname" ) ;
    if ( line.size() < len + 2 )
        return 0;
    if ( line[0] == '/' && line[1] == 'p' )
    {
        string name = line.substr( strlen( "/plotname" ) );
        auto pos = name.find_first_not_of( "    " );
        if ( pos == string::npos )
        {
            cout << "TableBase::loadXplot: Malformed plotname line '" <<
                 line << "'\n";
            return 0;
        }
        name = name.substr( pos );
        if ( plotname == name )
            return 1;
    }
    return 0;
}
Referenced by innerLoadXplot(), and testUtilsForLoadXplot().
Variable Documentation
tableBaseCinfo
const Cinfo* tableBaseCinfo = TableBase::initCinfo() static
Definition at line 162 of file TableBase.cpp.