MOOSE - Multiscale Object Oriented Simulation Environment: /home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/utility/test_util.cpp File Reference
test_util.cpp File Reference
#include <iostream>
#include "utility.h"
#include "strutil.h"
#include "testing_macros.hpp"
Functions
int main (int argc, const char *argv[])
void test_normalize_path ()
Function Documentation
main()
int main (int argc, const char * argv[])
Definition at line 29 of file test_util.cpp.
{
    test_normalize_path();
    return 0;
}
References test_normalize_path().
test_normalize_path()
void test_normalize_path ()
Definition at line 17 of file test_util.cpp.
{
    string p1("//a/./b");
    auto p1fixes = moose::normalizePath(p1);
    std::cout << p1 << " " << p1fixes << std::endl;
    string p2("//a/./././///b");
    auto p2fixes = moose::normalizePath(p2);
    std::cout << p2 << " " << p2fixes << std::endl;
    ASSERT_EQ( p2fixes, "/a/b", "PATH");
}
References moose::normalizePath().
Referenced by main().