MOOSE - Multiscale Object Oriented Simulation Environment: /home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/kinetics/testKinetics.cpp File Reference
testKinetics.cpp File Reference
#include "../basecode/header.h"
#include "../shell/Shell.h"
#include "ReadKkit.h"
#include "ReadCspace.h"
#include "Reac.h"
#include "EnzBase.h"
#include "MMenz.h"
#include "Enz.h"
Functions
double estT (double s)
bool isClose (double x, double y, double tol)
void testKinetics ()
void testKineticsProcess ()
void testMMenz ()
void testMMenzProcess ()
void testMpiKinetics ()
void testPoolVolumeScaling ()
void testReacVolumeScaling ()
void testReadCspace ()
void testReadKkit ()
void testTwoReacGetNeighbors ()
void testVolSort ()
void testWriteKkit (Id id)
Function Documentation
estT()
double estT (double s)
Definition at line 224 of file testKinetics.cpp.
{
    double E = 1.0;
    double Km = 1.0;
    double kcat = 1.0;
    double s0 = 1.0;
    double c = -Km * log( s0 ) - s0;
    double t = (-1.0 /( E * kcat ) ) * ( ( Km * log( s ) + s ) + c );
    return t;
}
Referenced by testMMenzProcess().
isClose()
bool isClose (double x, double y, double tol)
Definition at line 36 of file testKinetics.cpp.
{
    return ( fabs( x - y ) < tol * 1e-8 );
}
testKinetics()
void testKinetics ()
Definition at line 332 of file testKinetics.cpp.
{
    testTwoReacGetNeighbors();
    testMMenz();
    testPoolVolumeScaling();
    testReacVolumeScaling();
    testReadCspace();
    testVolSort();
    // This is now handled with real models in the regression tests.
    // testWriteKkit( Id() );
}
References testMMenz(), testPoolVolumeScaling(), testReacVolumeScaling(), testReadCspace(), testTwoReacGetNeighbors(), and testVolSort().
testKineticsProcess()
void testKineticsProcess ()
Definition at line 349 of file testKinetics.cpp.
{
    testMMenzProcess();
}
References testMMenzProcess().
testMMenz()
void testMMenz ()
Definition at line 199 of file testKinetics.cpp.
{
    Shell* shell = reinterpret_cast< Shell* >( Id().eref().data() );
    Id mmid = shell->doCreate( "MMenz", Id(), "mm", 1 ); // mmenz
    MMenz m;
    ProcInfo p;
    m.vSetKm( mmid.eref(), 5.0 );
    m.vSetKcat( mmid.eref(), 4.0 );
    // m.vReinit( mmid.eref(), &p );
    m.sub( 2 );
    m.enz( 3 );
    assert( doubleEq( m.getKm( mmid.eref() ), 5.0 ) );
    assert( doubleEq( m.getKcat( mmid.eref() ), 4.0 ) );
    // m.vProcess( mmid.eref(), &p );
    shell->doDelete( mmid );
    cout << "." << flush;
}
References Eref::data(), Shell::doCreate(), Shell::doDelete(), doubleEq(), EnzBase::enz(), Id::eref(), EnzBase::getKcat(), EnzBase::getKm(), Id::Id(), EnzBase::sub(), MMenz::vSetKcat(), and MMenz::vSetKm().
Referenced by testKinetics().
testMMenzProcess()
void testMMenzProcess ()
Definition at line 235 of file testKinetics.cpp.
{
    Shell* shell = reinterpret_cast< Shell* >( Id().eref().data() );
    // This set is the test kinetic calculation using MathFunc
    Id nid = shell->doCreate( "Neutral", Id(), "n", 1 );
    // This set is the reference kinetic calculation using MMEnz
    Id pid = shell->doCreate( "Pool", nid, "p", 1 ); // substrate
    Id qid = shell->doCreate( "Pool", nid, "q", 1 );    // enz mol
    Id rid = shell->doCreate( "Pool", nid, "r", 1 ); // product
    Id mmid = shell->doCreate( "MMenz", nid, "mm", 1 ); // mmenz
    Id tabid2 = shell->doCreate( "Table", nid, "tab2", 1 ); //output plot
    Field< double >::set( mmid, "Km", 1.0 );
    Field< double >::set( mmid, "kcat", 1.0 );
    Field< double >::set( pid, "nInit", 1.0 );
    Field< double >::set( qid, "nInit", 1.0 );
    Field< double >::set( rid, "nInit", 0.0 );
    shell->doAddMsg( "Single", ObjId( mmid ), "sub", ObjId( pid ), "reac" );
    shell->doAddMsg( "Single", ObjId( mmid ), "prd", ObjId( rid ), "reac" );
    shell->doAddMsg( "Single", ObjId( qid ), "nOut", ObjId( mmid ), "enzDest" );
    shell->doAddMsg( "Single", ObjId( pid ), "nOut", ObjId( tabid2 ), "input" );
    shell->doSetClock( 0, 0.01 );
    shell->doSetClock( 1, 0.01 );
    shell->doUseClock( "/n/mm,/n/tab2", "process", 0 );
    shell->doUseClock( "/n/#[ISA=Pool]", "process", 1 );
    // Now run models and compare outputs
    shell->doReinit();
    shell->doStart( 10 );
    vector< double > vec = Field< vector< double > >::get( tabid2, "vec" );
    assert( vec.size() == 1001 );
    for ( unsigned int i = 0; i < vec.size(); ++i ) {
        double t = 0.01 * i;
        double et = estT( vec[i] );
        assert( doubleApprox( t, et ) );
    }
    shell->doDelete( nid );
    cout << "." << flush;
}
References Eref::data(), Shell::doAddMsg(), Shell::doCreate(), Shell::doDelete(), Shell::doReinit(), Shell::doSetClock(), Shell::doStart(), doubleApprox(), Shell::doUseClock(), Id::eref(), estT(), Field< A >::get(), Id::Id(), ObjId::ObjId(), and Field< A >::set().
Referenced by testKineticsProcess().
testMpiKinetics()
void testMpiKinetics ()
Definition at line 345 of file testKinetics.cpp.
{
}
testPoolVolumeScaling()
void testPoolVolumeScaling ()
Definition at line 41 of file testKinetics.cpp.
{
    Shell* shell = reinterpret_cast< Shell* >( Id().eref().data() );
    Id comptId = shell->doCreate( "CylMesh", Id(), "cyl", 1 );
    Id meshId( comptId.value() + 1 );
    Id poolId = shell->doCreate( "Pool", comptId, "pool", 1 );
    ObjId mid = shell->doAddMsg( "OneToOne",
        ObjId( poolId, 0 ), "requestVolume",
        ObjId( meshId, 0 ), "get_volume" );
    assert( mid != ObjId() );
    vector< double > coords( 9, 0.0 );
    double x1 = 100e-6;
    double r0 = 10e-6;
    double r1 = 5e-6;
    double lambda = x1;
    coords[3] = x1;
    coords[6] = r0;
    coords[7] = r1;
    coords[8] = lambda;
    Field< vector< double > >::set( comptId, "coords", coords );
    double volume = Field< double >::get( poolId, "volume" );
    assert( doubleEq( volume, PI * x1 * (r0+r1) * (r0+r1) / 4.0 ) );
    Field< double >::set( poolId, "n", 400 );
    double volscale = 1 / ( NA * volume );
    double conc = Field< double >::get( poolId, "conc" );
    assert( doubleEq( conc, 400 * volscale ) );
    Field< double >::set( poolId, "conc", 500 * volscale );
    double n = Field< double >::get( poolId, "n" );
    assert( doubleEq( n, 500 ) );
    Field< double >::set( poolId, "nInit", 650 );
    double concInit = Field< double >::get( poolId, "concInit" );
    assert( doubleEq( concInit, 650 * volscale ) );
    Field< double >::set( poolId, "concInit", 10 * volscale );
    n = Field< double >::get( poolId, "nInit" );
    assert( doubleEq( n, 10 ) );
    shell->doDelete( comptId );
    cout << "." << flush;
}
References Eref::data(), Shell::doAddMsg(), Shell::doCreate(), Shell::doDelete(), doubleEq(), Id::eref(), Field< A >::get(), Id::Id(), Id::Id(), NA, ObjId::ObjId(), ObjId::ObjId(), ObjId::operator!=(), PI, Field< A >::set(), and Id::value().
Referenced by testKinetics().
testReacVolumeScaling()
void testReacVolumeScaling ()
Definition at line 88 of file testKinetics.cpp.
{
    Shell* shell = reinterpret_cast< Shell* >( Id().eref().data() );
    Id comptId = shell->doCreate( "CubeMesh", Id(), "cube", 1 );
    Id meshId( comptId.value() + 1 );
    Id subId = shell->doCreate( "Pool", comptId, "sub", 1 );
    Id prdId = shell->doCreate( "Pool", comptId, "prd", 1 );
    Id reacId = shell->doCreate( "Reac", comptId, "reac", 1 );
    double vol1 = 1e-15;
    ObjId mid = shell->doAddMsg( "OneToOne",
        subId, "requestVolume", meshId, "get_volume" );
    assert( mid != ObjId() );
    mid = shell->doAddMsg( "OneToOne",
        prdId, "requestVolume", meshId, "get_volume" );
    assert( mid != ObjId() );
    vector< double > coords( 9, 10.0e-6 );
    coords[0] = coords[1] = coords[2] = 0;
    Field< vector< double > >::set( comptId, "coords", coords );
    double volume = Field< double >::get( comptId, "volume" );
    assert( doubleEq( volume, vol1 ) );
    ObjId ret = shell->doAddMsg( "Single", reacId, "sub", subId, "reac" );
    assert( ret != ObjId() );
    ret = shell->doAddMsg( "Single", reacId, "prd", prdId, "reac" );
    assert( ret != ObjId() );
    Field< double >::set( reacId, "Kf", 2 );
    Field< double >::set( reacId, "Kb", 3 );
    double x = Field< double >::get( reacId, "kf" );
    assert( doubleEq( x, 2 ) );
    x = Field< double >::get( reacId, "kb" );
    assert( doubleEq( x, 3 ) );
    ret = shell->doAddMsg( "Single", reacId, "sub", subId, "reac" );
    assert( ret != ObjId() );
    double conv = 1.0 / ( NA * vol1 );
    x = Field< double >::get( reacId, "kf" );
    assert( doubleEq( x, 2 * conv ) );
    x = Field< double >::get( reacId, "kb" );
    assert( doubleEq( x, 3 ) );
    ret = shell->doAddMsg( "Single", reacId, "sub", subId, "reac" );
    assert( ret != ObjId() );
    ret = shell->doAddMsg( "Single", reacId, "prd", prdId, "reac" );
    assert( ret != ObjId() );
    x = Field< double >::get( reacId, "kf" );
    assert( doubleEq( x, 2 * conv * conv ) );
    x = Field< double >::get( reacId, "kb" );
    assert( doubleEq( x, 3 * conv ) );
    shell->doDelete( comptId );
    cout << "." << flush;
}
References Eref::data(), Shell::doAddMsg(), Shell::doCreate(), Shell::doDelete(), doubleEq(), Id::eref(), Field< A >::get(), Id::Id(), Id::Id(), NA, ObjId::ObjId(), ObjId::operator!=(), Field< A >::set(), and Id::value().
Referenced by testKinetics().
testReadCspace()
void testReadCspace ()
Definition at line 192 of file testKinetics.cpp.
{
    ReadCspace rc;
    rc.testReadModel();
    cout << "." << flush;
}
References ReadCspace::testReadModel().
Referenced by testKinetics().
testReadKkit()
void testReadKkit ()
Definition at line 20 of file testKinetics.cpp.
{
    ReadKkit rk;
    // rk.read( "test.g", "dend", 0 );
    Id base = rk.read( "foo.g", "dend", Id() );
    assert( base != Id() );
    // Id kinetics = s->doFind( "/kinetics" );
    Shell* s = reinterpret_cast< Shell* >( Id().eref().data() );
    rk.run();
    rk.dumpPlots( "dend.plot" );
    s->doDelete( base );
    cout << "." << flush;
}
References Eref::data(), Shell::doDelete(), ReadKkit::dumpPlots(), Id::eref(), Id::Id(), Id::operator!=(), ReadKkit::read(), and ReadKkit::run().
testTwoReacGetNeighbors()
void testTwoReacGetNeighbors ()
Definition at line 148 of file testKinetics.cpp.
{
    Shell* shell = reinterpret_cast< Shell* >( Id().eref().data() );
    Id comptId = shell->doCreate( "CubeMesh", Id(), "cube", 1 );
    Id meshId( comptId.value() + 1 );
    Id subId = shell->doCreate( "Pool", comptId, "sub", 1 );
    Id prdId = shell->doCreate( "Pool", comptId, "prd", 1 );
    Id reacId = shell->doCreate( "Reac", comptId, "reac", 1 );
    ObjId mid = shell->doAddMsg( "OneToOne",
        subId, "requestVolume", meshId, "get_volume" );
    assert( mid != ObjId() );
    mid = shell->doAddMsg( "OneToOne",
        prdId, "requestVolume", meshId, "get_volume" );
    assert( mid != ObjId() );
    ObjId ret = shell->doAddMsg( "Single", reacId, "sub", subId, "reac" );
    assert( ret != ObjId() );
    ret = shell->doAddMsg( "Single", reacId, "sub", subId, "reac" );
    assert( ret != ObjId() );
    ret = shell->doAddMsg( "Single", reacId, "prd", prdId, "reac" );
    assert( ret != ObjId() );
    vector< Id > pools;
    unsigned int num = reacId.element()->getNeighbors( pools,
        Reac::initCinfo()->findFinfo( "toSub" ) );
    assert( num == 2 );
    assert( pools[0] == subId );
    assert( pools[1] == subId );
    pools.clear();
    num = reacId.element()->getNeighbors( pools,
        Reac::initCinfo()->findFinfo( "sub" ) );
    assert( num == 2 );
    assert( pools[0] == subId );
    assert( pools[1] == subId );
    shell->doDelete( comptId );
    cout << "." << flush;
}
References Eref::data(), Shell::doAddMsg(), Shell::doCreate(), Shell::doDelete(), Id::element(), Id::eref(), Cinfo::findFinfo(), Element::getNeighbors(), Id::Id(), Id::Id(), Reac::initCinfo(), ObjId::ObjId(), ObjId::operator!=(), Id::operator==(), and Id::value().
Referenced by testKinetics().
testVolSort()
void testVolSort ()
Definition at line 293 of file testKinetics.cpp.
{
    vector< unsigned int > findVolOrder( const vector< double >& vols );
    vector< double > vols( 8 );
    vols[0] = 7;
    vols[1] = 8;
    vols[2] = 6;
    vols[3] = 5;
    vols[4] = 1;
    vols[5] = 2;
    vols[6] = 3;
    vols[7] = 4;
    vector< unsigned int > order = findVolOrder( vols );
    // The order is the rank of the volume entry, largest should be 0.
    assert( order[0] == 1 );
    assert( order[1] == 0 );
    assert( order[2] == 2 );
    assert( order[3] == 3 );
    assert( order[4] == 7 );
    assert( order[5] == 6 );
    assert( order[6] == 5 );
    assert( order[7] == 4 );
    // This is a sequence which failed in a model test, despite the
    // above test working.
    vols.resize(5);
    vols[0] = 1e-15;
    vols[1] = 3e-15;
    vols[2] = -1;
    vols[3] = 2e-15;
    vols[4] = 5e-15;
    order = findVolOrder( vols );
    assert( order[0] == 4 );
    assert( order[1] == 1 );
    assert( order[2] == 3 );
    assert( order[3] == 0 );
    assert( order[4] == 2 );
}
References findVolOrder().
Referenced by testKinetics().
testWriteKkit()
void testWriteKkit (Id id)
Definition at line 286 of file testKinetics.cpp.
{
    extern void writeKkit( Id model, const string& s );
    writeKkit( id, "kkitWriteTest.g" );
    cout << "." << flush;
}
References writeKkit().