MOOSE - Multiscale Object Oriented Simulation Environment: /home/runner/work/mooseneuro.github.io/mooseneuro.github.io/docs/moose-core/builtins/TimeTable.cpp File Reference
TimeTable.cpp File Reference
#include "../basecode/header.h"
#include <fstream>
#include "TableBase.h"
#include "TimeTable.h"
Functions
static SrcFinfo1< double > * eventOut ()
Variables
static const Cinfo * timeTableCinfo = TimeTable::initCinfo()
Function Documentation
eventOut()
static SrcFinfo1< double > * eventOut () static
Definition at line 17 of file TimeTable.cpp.
{
    static SrcFinfo1< double > eventOut(
        "eventOut",
        "Sends out spike time if it falls in current timestep.");
    return &eventOut;
}
References SrcFinfo1< T >::SrcFinfo1().
Referenced by TimeTable::initCinfo(), and TimeTable::process().
Variable Documentation
timeTableCinfo
const Cinfo* timeTableCinfo = TimeTable::initCinfo() static
Definition at line 95 of file TimeTable.cpp.